# Benchmarking Results from Classification and Regression

#### Set Up

In [1]:
import pandas as pd
import numpy as np
import site
import os

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import TimeSeriesSplit
from sklearn.utils.class_weight import compute_class_weight

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader
from torch.optim import Adam
from torch.optim.lr_scheduler import ReduceLROnPlateau
from contextlib import nullcontext

import random

from unicodedata import bidirectional

### Utility Classes and Functions

In [3]:
def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

# Datasets
class SequenceDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

class OrdinalSequenceDataset(Dataset):
    def __init__(self, X, T):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.T = torch.tensor(T, dtype=torch.float32)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.T[idx]

def make_cumulative_targets(y_int, K):
    y = y_int.reshape(-1, 1)
    ks = np.arange(K-1).reshape(1, -1)
    return (y > ks).astype(np.float32)

def decode_ordinal(probs, thr=0.5):
    return (probs >= thr).sum(axis=1)

# Models
class OrdinalHeadCORN(nn.Module):
    def __init__(self, in_dim, K):
        super().__init__()
        self.fc = nn.Linear(in_dim, K-1)

    def forward(self, h):
        return self.fc(h)


class OrdinalHeadCORAL(nn.Module):
    def __init__(self, in_dim, K):
        super().__init__()
        self.w = nn.Linear(in_dim, 1, bias=False)
        self._beta = nn.Parameter(torch.zeros(K-1))
        self.softplus = nn.Softplus()

    def forward(self, h):
        base = self.w(h)
        deltas = self.softplus(self._beta)
        b = torch.cumsum(deltas, dim=0)
        return base - b



class RNNHead(nn.Module):
    # Shared head:
    #   - RNN stack (LSTM/GRU, uni/bi)
    #   - BatchNorm + Dense(32, ReLU) + Dropout
    #   - Output layer (1 unit): linear (regression) or logits (classification)
    def __init__(self, input_size, rnn_type='LSTM', bidirectional=False, problem_type='classification',
                 n_classes=6, ordinal_head='coral', hidden1=128, hidden2=64, num_layers=1,
                 inter_rnn_drop=0.1, dropout=0.3, use_layernorm=False):
        super().__init__()
        self.problem_type = problem_type
        self.bidirectional = bidirectional
        self.rnn_type = rnn_type.upper()
        self.n_classes = n_classes
        self.ordinal_head = ordinal_head
        self.num_layers = int(num_layers)
        self.hidden1 = int(hidden1)
        self.hidden2 = int(hidden2)

        if self.num_layers not in (1, 2):
            raise ValueError("num_layers must be 1 or 2")

        rnn_cls = {'LSTM': nn.LSTM, 'GRU': nn.GRU}[('GRU' if 'GRU' in self.rnn_type else 'LSTM')]

        self.rnn1 = rnn_cls(
            input_size=input_size, hidden_size=self.hidden1, num_layers=1,
            batch_first=True, dropout=0.0, bidirectional=bidirectional
        )

        self.inter_rnn_drop = nn.Dropout(float(inter_rnn_drop))

        self.rnn2 = None
        if self.num_layers == 2:
            self.rnn2 = rnn_cls(
                input_size=self.hidden1*(2 if bidirectional else 1), hidden_size=self.hidden2, num_layers=1,
                batch_first=True, dropout=0.0, bidirectional=bidirectional
            )
            feat_dim = self.hidden2*(2 if bidirectional else 1)
        else:
            feat_dim = self.hidden1*(2 if bidirectional else 1)

        if use_layernorm:
            self.bn = nn.LayerNorm(feat_dim)
        else:
            self.bn = nn.BatchNorm1d(feat_dim)
        self.fc = nn.Linear(feat_dim, 32)
        self.drop = nn.Dropout(float(dropout))
        if self.problem_type == 'multiclass':
            head = self.ordinal_head.lower() if isinstance(self.ordinal_head, str) else 'coral'
            if head == 'corn':
                self.out = OrdinalHeadCORN(32, self.n_classes)
            else:
                self.out = OrdinalHeadCORAL(32, self.n_classes)
        else:
            self.out = nn.Linear(32, 1)

    def forward(self, x):
        # x: [B, T, F]
        out, _ = self.rnn1(x)
        if self.num_layers == 2:
            out = self.inter_rnn_drop(out)   # inter-layer dropout (sequence-wise)
            out, _ = self.rnn2(out)
        # take last timestep: [B, T, H] -> [B, H]
        out = out[:, -1, :]
        out = self.bn(out)
        out = F.relu(self.fc(out))
        out = self.drop(out)
        out = self.out(out)  # shape [B,1]
        return out  # regression: raw; classification: logits


def build_model(input_shape, model_type='LSTM', problem_type='regression', n_classes=6, ordinal_head='coral',
                hidden1=128, hidden2=64, num_layers=2, inter_rnn_drop=0.1, dropout=0.3, use_layernorm=False):
    seq_len, n_features = input_shape
    model_type = model_type.upper()
    kwargs = dict(
        problem_type=problem_type,
        n_classes=n_classes,
        ordinal_head=ordinal_head,
        hidden1=hidden1,
        hidden2=hidden2,
        num_layers=num_layers,
        inter_rnn_drop=inter_rnn_drop,
        dropout=dropout,
        use_layernorm=use_layernorm,
    )
    if model_type == 'LSTM':
        return RNNHead(n_features, rnn_type='LSTM', bidirectional=False, **kwargs)
    elif model_type == 'BILSTM':
        return RNNHead(n_features, rnn_type='LSTM', bidirectional=True, **kwargs)
    elif model_type == 'GRU':
        return RNNHead(n_features, rnn_type='GRU', bidirectional=False, **kwargs)
    elif model_type == 'BIGRU':
        return RNNHead(n_features, rnn_type='GRU', bidirectional=True, **kwargs)
    else:
        raise ValueError("Model type must be one of: ['LSTM','BiLSTM','GRU','BiGRU']")

# Early Stopping (PyTorch)
class EarlyStopper:
    def __init__(self, patience=15, min_delta=0.0, restore_best=True):
        self.patience = patience
        self.min_delta = min_delta
        self.restore_best = restore_best
        self.best_loss = float('inf')
        self.counter = 0
        self.best_state = None

    def step(self, val_loss, model):
        improved = (self.best_loss - val_loss) > self.min_delta
        if improved:
            self.best_loss = val_loss
            self.counter = 0
            if self.restore_best:
                # Deep copy state dict
                self.best_state = {k: v.detach().clone() for k, v in model.state_dict().items()}
        else:
            self.counter += 1
        return self.counter >= self.patience

    def restore(self, model):
        if self.restore_best and self.best_state is not None:
            model.load_state_dict(self.best_state)

In [4]:
def edge_labels_from_edges(edges, decimals=1):
    labels = []
    C = len(edges) - 1
    for i in range(C):
        lo, hi = edges[i], edges[i+1]
        if i == 0:
            labels.append(f"≤ {hi*100:.{decimals}f}%")
        elif i == C - 1:
            labels.append(f"> {lo*100:.{decimals}f}%")
        else:
            labels.append(f"({lo*100:.{decimals}f}%,{hi*100:.{decimals}f}%]")
    return labels

def pct_return(series, h):
    return series.shift(-h) / series - 1.0

def safe_quantile_edges(x, n_classes=6):
    qs = np.linspace(0, 1, n_classes + 1)
    edges = np.quantile(x, qs)
    for i in range(1, len(edges)):
        if edges[i] <= edges[i-1]:
            edges[i] = np.nextafter(edges[i-1], np.inf)
    return edges

def bucketize_with_edges(x, edges):
    inner = edges[1:-1]
    return np.digitize(x, inner, right=True).astype(int)

@torch.no_grad()
def collect_logits(model, loader, device):
    model.eval()
    chunks = []
    for xb, _ in loader:
        xb = xb.to(device)
        chunks.append(model(xb).detach().cpu())
    return torch.cat(chunks, dim=0)

def find_taus_per_threshold(Z_val, y_val_idx, grid=np.linspace(0, 1, 100)):
    if isinstance(Z_val, torch.Tensor):
        Z_val = Z_val.numpy()
    P_val = 1.0 / (1.0 + np.exp(-Z_val))
    P_rep = monotone_repair_numpy(P_val)
    K_1 = P_rep.shape[1]
    best_taus = np.full(K_1, 0.5, dtype=np.float32)
    for k in range(K_1):
        best_f1, best_tau = -1.0, 0.5
        for tau in grid:
            y_hat = decode_ordinal_with_taus(P_rep, taus_override={k: tau})
            f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
            if f1 > best_f1:
                best_f1, best_tau = f1, tau
        best_taus[k] = best_tau
    return best_taus

def monotone_repair_numpy(P):
    P = np.asarray(P).copy()
    for k in range(P.shape[1] - 2, -1, -1):
        P[:, k] = np.maximum(P[:, k], P[:, k+1])
    return P

def decode_ordinal_with_taus(P_rep, taus=None, taus_override=None):
    N, K_1 = P_rep.shape
    if taus is None:
        taus = np.full(K_1, 0.5, dtype=np.float32)
    if taus_override:
        taus = taus.copy()
        for k, v in taus_override.items():
            taus[k] = v
    comp = (P_rep >= taus.reshape(1, -1)).astype(np.int32)
    return comp.sum(axis=1).astype(np.int64)

def ordinal_to_class_probs(P_rep):
    N, K_1 = P_rep.shape
    K = K_1 + 1
    Pc = np.empty((N, K), dtype=np.float32)
    Pc[:, 0] = 1.0 - P_rep[:, 0]
    for c in range(1, K - 1):
        Pc[:, c] = np.clip(P_rep[:, c-1] - P_rep[:, c], 0.0, 1.0)
    Pc[:, K - 1] = P_rep[:, K_1 - 1]
    s = Pc.sum(axis=1, keepdims=True)
    return Pc / np.maximum(s, 1e-8)


def best_threshold_from_val(y_true, y_scores, metric='f1', grid=None):
    """
    Sweep probability thresholds on validation scores to maximize a metric.
    metric can be 'f1', 'mcc', 'accuracy', or a callable(y_true,y_pred)->float.
    Returns (best_threshold, best_metric_value).
    """
    y_true = np.asarray(y_true).astype(int)
    y_scores = np.asarray(y_scores).astype(float)
    if grid is None:
        grid = np.linspace(0.05, 0.95, 181)
    metric_fn = None
    if callable(metric):
        metric_fn = metric
    else:
        name = str(metric).lower()
        if name == 'f1':
            metric_fn = lambda yt, yp: f1_score(yt, yp, zero_division=0)
        elif name == 'mcc':
            metric_fn = lambda yt, yp: matthews_corrcoef(yt, yp)
        elif name in ('acc', 'accuracy'):
            metric_fn = lambda yt, yp: (yt == yp).mean()
        else:
            raise ValueError(f"Unsupported metric '{metric}'")
    best_thr = 0.5
    best_val = -np.inf
    for thr in grid:
        preds = (y_scores >= thr).astype(int)
        val = metric_fn(y_true, preds)
        if val > best_val + 1e-12 or (abs(val - best_val) <= 1e-12 and thr < best_thr):
            best_val = float(val)
            best_thr = float(thr)
    return best_thr, best_val

## Stock Prediction Pipeline

In [5]:
class StockPredictionPipeline:
    def __init__(self, df, feature_columns, model_type='LSTM', sequence_length=24, problem_type='regression', horizon_steps=1, n_classes=6, ordinal_head='coral', fixed_bucket_edges=None,
                 hidden1=256, hidden2=64, num_layers=1, inter_rnn_drop=0.0, dropout=0.4,
                 batch_size=32, learning_rate=7e-3, weight_decay=2e-3, lr_patience=7, lr_factor=0.5,
                 early_stopping_patience=20, max_epochs=20, use_layernorm=False, huber_delta=1.0, early_stopping_min_delta=0.0):
        self.df = df.copy()
        self.feature_columns = feature_columns
        self.model_type = model_type
        self.sequence_length = sequence_length
        self.problem_type = problem_type
        self.horizon_steps = horizon_steps
        self.results = []
        self.loss_curves = []
        self.skip_reasons = {}
        self.skipped_companies = []
        self.n_classes = n_classes
        self.ordinal_head = ordinal_head
        self.hidden1 = hidden1
        self.hidden2 = hidden2
        self.num_layers = num_layers
        self.inter_rnn_drop = inter_rnn_drop
        self.dropout = dropout
        self.batch_size = batch_size
        self.learning_rate = learning_rate
        self.weight_decay = weight_decay
        self.lr_patience = lr_patience
        self.lr_factor = lr_factor
        self.early_stopping_patience = early_stopping_patience
        self.max_epochs = max_epochs
        self.use_layernorm = use_layernorm
        self.huber_delta = huber_delta
        self.early_stopping_min_delta = early_stopping_min_delta
        self.fixed_bucket_edges = None
        if fixed_bucket_edges is not None:
            edges = np.asarray(fixed_bucket_edges, dtype=float)
            if edges.ndim != 1:
                raise ValueError("fixed_bucket_edges must be a 1D sequence of monotonically increasing numbers")
            if edges.size < 2:
                raise ValueError("fixed_bucket_edges must contain at least two values")
            if np.any(np.diff(edges) <= 0):
                raise ValueError("fixed_bucket_edges must be strictly increasing")
            self.n_classes = int(edges.size - 1)
            self.fixed_bucket_edges = edges

        # Validate
        self._validate_inputs()

        # Device & precision
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.mixed_precision = torch.cuda.is_available()

        print(f"Pipeline initialized for a '{self.problem_type}' problem "
              f"with horizon {self.horizon_steps} steps. Device: {self.device}")

    def _validate_inputs(self):
        missing_cols = [col for col in self.feature_columns if col not in self.df.columns]
        if missing_cols:
            raise ValueError(f"Missing feature columns: {missing_cols}")

        if 'close' not in self.df.columns and 'close_price' not in self.df.columns:
            raise ValueError("No 'close' or 'close_price' column found in data")

        valid_models = ['LSTM', 'BiLSTM', 'GRU', 'BiGRU']
        if self.model_type not in valid_models:
            raise ValueError(f"Model type must be one of: {valid_models}")

        if self.problem_type not in ['regression', 'classification', 'multiclass']:
            raise ValueError("Problem type must be 'regression', 'classification', or 'multiclass'")

    def _record_skip(self, company_name, reason, sector=None):
        self.skip_reasons[reason] = self.skip_reasons.get(reason, 0) + 1
        self.skipped_companies.append({'company': company_name, 'sector': sector, 'reason': reason})

    def create_target_variable(self, company_data):
        company_data = company_data.copy()
        price_col = 'close' if 'close' in company_data.columns else 'close_price'
        if 'date' in company_data.columns:
            company_data = company_data.sort_values('date')
            
        h = self.horizon_steps

        company_data['target_regression'] = (
            np.log(company_data[price_col].shift(-h)) - np.log(company_data[price_col])
        )
        company_data['target_direction'] = (company_data['target_regression'] > 0).astype(int)
        company_data['ret_h'] = pct_return(company_data[price_col], h)
        if self.problem_type == 'multiclass':
            company_data = company_data.dropna(subset=['ret_h'])
        else:
            company_data = company_data.dropna()
        return company_data

    def create_sequences(self, features, *targets):
        X = []
        y_sequences = [[] for _ in targets]
        for i in range(self.sequence_length, len(features)):
            X.append(features[i-self.sequence_length:i])
            for j, target in enumerate(targets):
                y_sequences[j].append(target[i])
        return (np.array(X),) + tuple(np.array(y) for y in y_sequences)

    def _train_one_epoch(self, model, loader, optimizer, loss_fn, scaler):
        model.train()
        total_loss = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device).view(-1, 1)

            optimizer.zero_grad(set_to_none=True)

            ctx = torch.amp.autocast('cuda') if self.mixed_precision else nullcontext()
            with ctx:
                logits = model(xb)
                loss = loss_fn(logits, yb)

            if self.mixed_precision:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                optimizer.step()

            total_loss += loss.item() * xb.size(0)

        return total_loss / len(loader.dataset)

    @torch.no_grad()
    def _eval_one_epoch(self, model, loader, loss_fn):
        model.eval()
        total_loss = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device).view(-1, 1)
            logits = model(xb)
            loss = loss_fn(logits, yb)
            total_loss += loss.item() * xb.size(0)
        return total_loss / len(loader.dataset)

    def _train_one_epoch_multiclass(self, model, loader, optimizer, scaler, *, pos_weight=None):
        model.train()
        total = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device)
            optimizer.zero_grad(set_to_none=True)
            ctx = torch.amp.autocast('cuda') if self.mixed_precision else nullcontext()
            with ctx:
                logits = model(xb)
                bces = []
                for k in range(logits.shape[1]):
                    w = None if pos_weight is None else pos_weight[k]
                    bce_k = F.binary_cross_entropy_with_logits(logits[:, k], yb[:, k], pos_weight=w)
                    bces.append(bce_k)
                loss = torch.stack(bces).mean()
            if self.mixed_precision:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
            total += float(loss.item()) * xb.size(0)
        return total / len(loader.dataset)

    @torch.no_grad()
    def _eval_one_epoch_multiclass(self, model, loader, pos_weight=None):
        model.eval()
        total = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device)
            logits = model(xb)
            bces = []
            for k in range(logits.shape[1]):
                w = None if pos_weight is None else pos_weight[k]
                bce_k = F.binary_cross_entropy_with_logits(logits[:, k], yb[:, k], pos_weight=w)
                bces.append(bce_k)
            loss = torch.stack(bces).mean()
            total += float(loss.item()) * xb.size(0)
        return total / len(loader.dataset)

    @torch.no_grad()
    def _predict(self, model, loader):
        model.eval()
        outs = []
        for xb, _ in loader:
            xb = xb.to(self.device)
            logits = model(xb).squeeze(1).detach().cpu().numpy()
            outs.append(logits)
        return np.concatenate(outs, axis=0)

    def build_model(self, input_shape):
        model = build_model(
            input_shape,
            model_type=self.model_type,
            problem_type=self.problem_type,
            n_classes=self.n_classes,
            ordinal_head=self.ordinal_head,
            hidden1=self.hidden1,
            hidden2=self.hidden2,
            num_layers=self.num_layers,
            inter_rnn_drop=self.inter_rnn_drop,
            dropout=self.dropout,
            use_layernorm=self.use_layernorm
        )
        return model.to(self.device)

    def process_company(self, company_name, company_data, sector):
        print(f"\nProcessing {company_name} ({sector})...")
        try:
            company_data = self.create_target_variable(company_data)

            # Min samples requirement (same heuristic)
            min_samples = self.sequence_length + self.horizon_steps
            if len(company_data) < min_samples:
                print(f"Insufficient data for {company_name} ({len(company_data)} < {min_samples}). Skipping...")
                self._record_skip(company_name, "insufficient_data", sector)
                return None

            if company_data[self.feature_columns].isnull().any().any():
                print(f"Missing values in features for {company_name}. Skipping...")
                self._record_skip(company_name, "missing_features", sector)
                return None

            features = company_data[self.feature_columns].values
            target_reg = company_data['target_regression'].values
            target_dir = company_data['target_direction'].values

            # Create sequences
            X_raw, y_reg, y_dir = self.create_sequences(features, target_reg, target_dir)

            # TimeSeriesSplit
            n_splits = min(5, len(X_raw) // 50)
            if n_splits < 3:
                print(f"Insufficient data for proper time series validation for {company_name}. Skipping...")
                self._record_skip(company_name, "tscv_too_short", sector)
                return None

            tscv = TimeSeriesSplit(n_splits=n_splits)
            splits = list(tscv.split(X_raw))
            train_idx, test_idx = splits[-1]

            # Train/Val split (last 20% of train for val)
            val_size = int(0.2 * len(train_idx))
            if val_size == 0:
                print(f'Insufficient data for validation split for {company_name}. Skipping...')
                self._record_skip(company_name, "val_split_empty", sector)
                return None
            final_train_idx = train_idx[:-val_size]
            val_idx = train_idx[-val_size:]
            
            if self.horizon_steps > 1:
                print("Adjusting for multi-step horizon...")
                gap = self.horizon_steps
                if len(final_train_idx) > gap:
                    final_train_idx = final_train_idx[:-gap]  # drop last h labels from train
                if len(val_idx) > gap:
                    val_idx = val_idx[gap:]  # drop last h labels from val
            if len(final_train_idx) == 0 or len(val_idx) == 0:
                print(f'Insufficient data after horizon adjustment for {company_name}. Skipping...')
                self._record_skip(company_name, "horizon_adjustment", sector)
                return None

            X_train_raw, X_val_raw, X_test_raw = X_raw[final_train_idx], X_raw[val_idx], X_raw[test_idx]
            
            F = X_raw.shape[-1]
            feat_scaler = StandardScaler()
            X_train = feat_scaler.fit_transform(X_train_raw.reshape(-1, F)).reshape(X_train_raw.shape)
            X_val   = feat_scaler.transform(X_val_raw.reshape(-1, F)).reshape(X_val_raw.shape)
            X_test  = feat_scaler.transform(X_test_raw.reshape(-1, F)).reshape(X_test_raw.shape)

            if self.problem_type == 'multiclass':
                if 'ret_h' not in company_data.columns:
                    raise RuntimeError("Expected 'ret_h' for ordinal targets but it was missing.")
                ret_full = company_data['ret_h'].values
                ret_seq_full = ret_full[self.sequence_length:]

                ret_train = ret_seq_full[final_train_idx]
                ret_val = ret_seq_full[val_idx]
                ret_test = ret_seq_full[test_idx]

                if self.fixed_bucket_edges is not None:
                    edges = self.fixed_bucket_edges
                    if int(edges.shape[0] - 1) != self.n_classes:
                        raise ValueError("fixed_bucket_edges length must match n_classes+1")
                else:
                    edges = safe_quantile_edges(ret_train, n_classes=self.n_classes)
                edges = np.asarray(edges, dtype=float)
                K = int(edges.shape[0] - 1)
                label_names = edge_labels_from_edges(edges, decimals=1)

                y_bucket = bucketize_with_edges(ret_seq_full, edges).astype(np.int64)
                y_train = y_bucket[final_train_idx]
                y_val = y_bucket[val_idx]
                y_test = y_bucket[test_idx]

                T_train = make_cumulative_targets(y_train.astype(np.int64), K)
                T_val = make_cumulative_targets(y_val.astype(np.int64), K)
                T_test = make_cumulative_targets(y_test.astype(np.int64), K)

                train_ds = OrdinalSequenceDataset(X_train, T_train)
                val_ds = OrdinalSequenceDataset(X_val, T_val)
                test_ds = OrdinalSequenceDataset(X_test, T_test)

                train_loader = DataLoader(train_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)
                val_loader = DataLoader(val_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)
                test_loader = DataLoader(test_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)

                model = self.build_model((self.sequence_length, len(self.feature_columns)))

                pos_rate = T_train.mean(axis=0)
                pos_weight = (1.0 - pos_rate) / np.clip(pos_rate, 1e-6, 1.0)
                pos_weight_tensor = torch.tensor(pos_weight, dtype=torch.float32).to(self.device)

                optimizer = Adam(model.parameters(), lr=self.learning_rate, eps=1e-7, weight_decay=self.weight_decay)
                scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=self.lr_factor, patience=self.lr_patience, min_lr=1e-7)
                early_stopper = EarlyStopper(patience=self.early_stopping_patience, min_delta=self.early_stopping_min_delta, restore_best=True)
                scaler = torch.amp.GradScaler('cuda', enabled=self.mixed_precision)

                max_epochs = self.max_epochs
                best_val = float('inf')
                epochs_trained = 0
                company_loss_rows = []

                for epoch in range(1, max_epochs + 1):
                    train_loss = self._train_one_epoch_multiclass(model, train_loader, optimizer, scaler, pos_weight=pos_weight_tensor)
                    val_loss = self._eval_one_epoch_multiclass(model, val_loader, pos_weight=pos_weight_tensor)
                    scheduler.step(val_loss)
                    stop = early_stopper.step(val_loss, model)
                    epochs_trained = epoch

                    row = {
                        'company': company_name,
                        'sector': sector,
                        'model_type': self.model_type,
                        'problem_type': self.problem_type,
                        'sequence_length': self.sequence_length,
                        'horizon_steps': self.horizon_steps,
                        'epoch': epoch,
                        'train_loss': float(train_loss),
                        'val_loss': float(val_loss),
                        'train_samples': len(X_train),
                        'val_samples': len(X_val),
                        'test_samples': len(X_test),
                    }

                    company_loss_rows.append(row)
                    self.loss_curves.append(row)

                    if epoch % 10 == 0 or stop:
                        print(f"  Epoch {epoch:03d} - train {train_loss:.5f} | val {val_loss:.5f}")

                    if stop:
                        break

                early_stopper.restore(model)

                Z_val = collect_logits(model, val_loader, self.device)
                taus = find_taus_per_threshold(Z_val, y_val.astype(np.int64))
                P_cum_val = torch.sigmoid(Z_val).cpu().numpy()
                P_rep_val = monotone_repair_numpy(P_cum_val)
                P_class_val = ordinal_to_class_probs(P_rep_val)
                mid_cut = (K // 2)
                y_val_dir = (y_val >= mid_cut).astype(int)
                prob_val_up = P_class_val[:, mid_cut:].sum(axis=1)
                dir_thr, dir_thr_score = best_threshold_from_val(y_val_dir, prob_val_up, metric='mcc')

                Z_test = collect_logits(model, test_loader, self.device)
                P_cum = torch.sigmoid(Z_test).cpu().numpy()
                P_rep = monotone_repair_numpy(P_cum)
                P_class = ordinal_to_class_probs(P_rep)

                y_pred_labels = decode_ordinal_with_taus(P_rep, taus=taus)
                y_true_labels = y_test

                labels = list(range(K))
                cm_counts = confusion_matrix(y_true_labels, y_pred_labels, labels=labels)
                cm_norm = confusion_matrix(y_true_labels, y_pred_labels, labels=labels, normalize='true')

                micro_acc = (y_true_labels == y_pred_labels).mean()
                macro_f1 = f1_score(y_true_labels, y_pred_labels, average='macro', zero_division=0)

                ret_seq_train = ret_seq_full[final_train_idx].astype(np.float32)
                mu_c = np.array([
                    ret_seq_train[y_train == c].mean() if np.any(y_train == c) else 0.0
                    for c in range(K)
                ], dtype=np.float32)

                expected_ret = (P_class * mu_c[None, :]).sum(axis=1)
                expected_ret_mean = float(expected_ret.mean())

                prob_test_up = P_class[:, mid_cut:].sum(axis=1)
                y_true_dir = (y_true_labels >= mid_cut).astype(int)
                y_pred_dir = (prob_test_up >= dir_thr).astype(int)
                precision = precision_score(y_true_dir, y_pred_dir, zero_division=0)
                recall = recall_score(y_true_dir, y_pred_dir, zero_division=0)
                f1 = f1_score(y_true_dir, y_pred_dir, zero_division=0)
                mcc = matthews_corrcoef(y_true_dir, y_pred_dir)
                directional_accuracy = (y_true_dir == y_pred_dir).mean()

                result = {
                    'company': company_name,
                    'sector': sector,
                    'model_type': self.model_type,
                    'problem_type': self.problem_type,
                    'horizon_steps': self.horizon_steps,
                    'macro_f1': macro_f1,
                    'micro_accuracy': micro_acc,
                    'expected_return_mean': expected_ret_mean,
                    'mse': np.nan,
                    'mae': np.nan,
                    'r2': np.nan,
                    'mcc': mcc,
                    'f1': f1,
                    'precision': precision,
                    'recall': recall,
                    'directional_accuracy': directional_accuracy,
                'val_directional_accuracy': val_directional_accuracy if self.problem_type == 'classification' else np.nan,
                'val_mcc': val_mcc if self.problem_type == 'classification' else np.nan,
                'val_f1': val_f1 if self.problem_type == 'classification' else np.nan,
                'val_precision': val_precision if self.problem_type == 'classification' else np.nan,
                'val_recall': val_recall if self.problem_type == 'classification' else np.nan,
                    'n_samples': int(X_raw.shape[0]),
                    'train_samples': int(X_train.shape[0]),
                    'val_samples': int(X_val.shape[0]),
                    'test_samples': int(X_test.shape[0]),
                    'epochs_trained': epochs_trained
                }
                result['confusion_matrix'] = cm_counts.tolist()
                result['confusion_matrix_normalized'] = cm_norm.tolist()
                result['bucket_edges'] = edges.tolist()
                result['bucket_labels'] = label_names
                result['taus'] = taus.astype(float).tolist()
                result['direction_threshold'] = dir_thr
                result['direction_threshold_metric'] = dir_thr_score

                print(f"  Multiclass -> Micro Acc: {micro_acc:.4f}, Macro F1: {macro_f1:.4f}, Expected Return: {expected_ret_mean:.6f}")
                print(f"  Directional threshold -> τ={dir_thr:.3f} (val F1={dir_thr_score:.4f})")

                del model
                torch.cuda.empty_cache()
                return result

            if self.problem_type == 'regression':
                y_train, y_val, y_test = y_reg[final_train_idx], y_reg[val_idx], y_reg[test_idx]
                target_scaler = StandardScaler()
                y_train_scaled = target_scaler.fit_transform(y_train.reshape(-1, 1)).flatten()
                y_val_scaled   = target_scaler.transform(y_val.reshape(-1, 1)).flatten()
                train_target, val_target = y_train_scaled, y_val_scaled
            else:
                y_train, y_val, y_test = y_dir[final_train_idx], y_dir[val_idx], y_dir[test_idx]
                train_target, val_target = y_train, y_val
                target_scaler = None

            # class balance note
            if self.problem_type == 'classification':
                class_ratio = np.mean(y_train)
                if class_ratio < 0.1 or class_ratio > 0.9:
                    print(f"Severe class imbalance for {company_name} ({class_ratio:.3f}). Consider using class weights.")

            # datasets & loaders
            train_ds = SequenceDataset(X_train, train_target)
            val_ds   = SequenceDataset(X_val,   val_target)
            test_ds  = SequenceDataset(X_test,  y_test)

            train_bs = min(self.batch_size, len(train_ds))
            if train_bs < 2:
                print(f'Insufficient training samples for {company_name} (train size={len(train_ds)}). Skipping...')
                self._record_skip(company_name, "train_batch_too_small", sector)
                return None
            if len(train_ds) % train_bs == 1 and train_bs > 2:
                train_bs -= 1  # avoid batch size 1 for BatchNorm
            val_bs = min(self.batch_size, len(val_ds))
            test_bs = min(self.batch_size, len(test_ds))

            train_loader = DataLoader(train_ds, batch_size=train_bs, shuffle=False,  drop_last=False, num_workers=0)
            val_loader   = DataLoader(val_ds,   batch_size=val_bs,   shuffle=False, drop_last=False, num_workers=0)
            test_loader  = DataLoader(test_ds,  batch_size=test_bs,  shuffle=False, drop_last=False, num_workers=0)

            # build model
            model = self.build_model((self.sequence_length, len(self.feature_columns)))

            # loss functions
            if self.problem_type == 'regression':
                loss_fn = nn.HuberLoss(delta=self.huber_delta)
            else:
                # use BCEWithLogitsLoss for numerical stability (logits input)
                loss_fn = nn.BCEWithLogitsLoss()

            # optimizer & scheduler
            optimizer = Adam(model.parameters(), lr=self.learning_rate, eps=1e-7, weight_decay=self.weight_decay)
            scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=self.lr_factor, patience=self.lr_patience, min_lr=1e-7)
            early_stopper = EarlyStopper(patience=self.early_stopping_patience, min_delta=self.early_stopping_min_delta, restore_best=True)
            scaler = torch.amp.GradScaler('cuda', enabled=self.mixed_precision)

            # training loop
            max_epochs = self.max_epochs
            best_val = float('inf')
            epochs_trained = 0
            company_loss_rows = []  

            for epoch in range(1, max_epochs + 1):
                train_loss = self._train_one_epoch(model, train_loader, optimizer, loss_fn, scaler)
                val_loss = self._eval_one_epoch(model, val_loader, loss_fn)
                scheduler.step(val_loss)
                stop = early_stopper.step(val_loss, model)
                epochs_trained = epoch

                
                row = {
                    'company': company_name,
                    'sector': sector,
                    'model_type': self.model_type,
                    'problem_type': self.problem_type,
                    'sequence_length': self.sequence_length,
                    'horizon_steps': self.horizon_steps,
                    'epoch': epoch,
                    'train_loss': float(train_loss),
                    'val_loss': float(val_loss),
                    'train_samples': len(X_train),
                    'val_samples': len(X_val),
                    'test_samples': len(X_test),
                }
                
                company_loss_rows.append(row)
                self.loss_curves.append(row)

                if epoch % 10 == 0 or stop:
                    print(f"  Epoch {epoch:03d} - train {train_loss:.5f} | val {val_loss:.5f}")

                if stop:
                    break

            # restore best model weights (like Keras restore_best_weights=True)
            early_stopper.restore(model)

            # summarize train/val loss for overfitting checks
            best_train_loss = np.nan
            best_val_loss = np.nan
            final_train_loss = np.nan
            final_val_loss = np.nan
            if company_loss_rows:
                best_val_loss = min(r['val_loss'] for r in company_loss_rows)
                best_train_loss = min(r['train_loss'] for r in company_loss_rows)
                final_train_loss = company_loss_rows[-1]['train_loss']
                final_val_loss = company_loss_rows[-1]['val_loss']

            # predictions
            y_pred_raw = self._predict(model, test_loader)  # raw/regression or logits

            if self.problem_type == 'regression':
                y_pred_unscaled = target_scaler.inverse_transform(y_pred_raw.reshape(-1,1)).flatten() if target_scaler is not None else y_pred_raw
                mse = mean_squared_error(y_test, y_pred_unscaled)
                mae = mean_absolute_error(y_test, y_pred_unscaled)
                r2  = r2_score(y_test, y_pred_unscaled)

                # directional metrics (derived)
                y_test_dir = (y_reg[test_idx] > 0).astype(int)
                y_pred_dir = (y_pred_unscaled > 0).astype(int)
            else:
                # logits -> probs via sigmoid -> learn best threshold on VAL
                val_logits = self._predict(model, val_loader)
                val_probs = 1.0 / (1.0 + np.exp(-val_logits))
                best_thr, best_thr_score = best_threshold_from_val(y_val, val_probs, metric='mcc')
                val_pred_dir = (val_probs >= best_thr).astype(int)
                val_precision = precision_score(y_val, val_pred_dir, zero_division=0)
                val_recall = recall_score(y_val, val_pred_dir, zero_division=0)
                val_f1 = f1_score(y_val, val_pred_dir, zero_division=0)
                val_mcc = matthews_corrcoef(y_val, val_pred_dir)
                val_directional_accuracy = (y_val == val_pred_dir).mean()
                probs = 1.0 / (1.0 + np.exp(-y_pred_raw))
                y_pred_dir = (probs >= best_thr).astype(int)
                y_test_dir = y_test
                mse = mae = r2 = np.nan

            precision = precision_score(y_test_dir, y_pred_dir, zero_division=0)
            recall    = recall_score(y_test_dir, y_pred_dir, zero_division=0)
            f1        = f1_score(y_test_dir, y_pred_dir, zero_division=0)
            mcc       = matthews_corrcoef(y_test_dir, y_pred_dir)
            directional_accuracy = np.mean(y_test_dir == y_pred_dir)

            result = {
                'company': company_name,
                'sector': sector,
                'model_type': self.model_type,
                'problem_type': self.problem_type,
                'horizon_steps': self.horizon_steps,
                'mse': mse,
                'mae': mae,
                'r2': r2,
                'mcc': mcc,
                'f1': f1,
                'precision': precision,
                'recall': recall,
                'directional_accuracy': directional_accuracy,
                'val_directional_accuracy': val_directional_accuracy if self.problem_type == 'classification' else np.nan,
                'val_mcc': val_mcc if self.problem_type == 'classification' else np.nan,
                'val_f1': val_f1 if self.problem_type == 'classification' else np.nan,
                'val_precision': val_precision if self.problem_type == 'classification' else np.nan,
                'val_recall': val_recall if self.problem_type == 'classification' else np.nan,
                'n_samples': int(X_raw.shape[0]),
                'train_samples': int(X_train.shape[0]),
                'val_samples': int(X_val.shape[0]),
                'test_samples': int(X_test.shape[0]),
                'epochs_trained': epochs_trained
            }
            if self.problem_type == 'classification':
                result['best_threshold'] = best_thr
                result['best_threshold_metric'] = best_thr_score

            if self.problem_type == 'regression':
                print(f"  Regression -> MSE: {mse:.6f}, MAE: {mae:.6f}, R²: {r2:.4f}")
            elif self.problem_type == 'classification':
                print(f"  Classification -> best τ={best_thr:.3f} (val F1={best_thr_score:.4f})")
            print(f"  Directional -> Accuracy: {directional_accuracy:.4f}, MCC: {mcc:.4f}, F1: {f1:.4f}")

            # explicit cleanup (PyTorch handles this, but keeps parity with Enrique2025)
            del model
            torch.cuda.empty_cache()

            return result

        except Exception as e:
            print(f"Error processing {company_name}: {str(e)}")
            self._record_skip(company_name, f"error:{type(e).__name__}", sector)
            torch.cuda.empty_cache()
            return None

    def run_pipeline(self):
        company_col = None
        for col_name in ['ticker', 'company', 'symbol']:
            if col_name in self.df.columns:
                company_col = col_name
                break
        if company_col is None:
            company_col = self.df.columns[0]
            print(f"Warning: Using '{company_col}' as company identifier column")

        companies = self.df[company_col].unique()
        print(f"Processing {len(companies)} companies with {self.model_type} model...")
        print(f"Problem type: {self.problem_type}")
        print(f"Sequence length: {self.sequence_length}")
        print(f"Features: {self.feature_columns}")

        successful_companies = 0
        for i, company in enumerate(companies, 1):
            print(f"\n[{i}/{len(companies)}] Processing {company}...")
            company_data = self.df[self.df[company_col] == company].copy()
            sector = company_data['sector'].iloc[0] if 'sector' in company_data.columns else 'Unknown'
            result = self.process_company(company, company_data, sector)
            if result:
                self.results.append(result)
                successful_companies += 1

        print(f"\n{'='*80}")
        print(f"Pipeline completed: {successful_companies}/{len(companies)} companies processed successfully")
        print(f"{'='*80}")
        if self.skip_reasons:
            print("Skip summary:")
            for reason, count in sorted(self.skip_reasons.items(), key=lambda x: (-x[1], x[0])):
                print(f"  {reason}: {count}")
        if self.skipped_companies:
            self.skipped_df = pd.DataFrame(self.skipped_companies)

        if self.results:
            self.results_df = pd.DataFrame(self.results)
            return self.results_df
        else:
            print("No companies were processed successfully!")
            return pd.DataFrame()


    def analyze_results(self):
        if not hasattr(self, 'results_df') or self.results_df.empty:
            print("No results to analyze!")
            return None

        df = self.results_df
        analysis = {}

        print("" + "="*80)
        print("STOCK PREDICTION PIPELINE RESULTS")
        print("="*80)
        print(f"Model: {self.model_type} | Problem: {self.problem_type}")
        print(f"Companies analyzed: {len(df)}")
        print(f"Average samples per company: {df['n_samples'].mean():.0f}")

        print("" + "="*50)
        print("OVERALL PERFORMANCE")
        print("="*50)
        if self.problem_type == 'regression':
            print(f"Mean Squared Error:     {df['mse'].mean():.6f} (±{df['mse'].std():.6f})")
            print(f"Mean Absolute Error:    {df['mae'].mean():.6f} (±{df['mae'].std():.6f})")
            print(f"R² Score:              {df['r2'].mean():.4f} (±{df['r2'].std():.4f})")
        if self.problem_type == 'multiclass' and 'micro_accuracy' in df.columns:
            print(f"Micro Accuracy:         {df['micro_accuracy'].mean():.4f} (±{df['micro_accuracy'].std():.4f})")
            print(f"Macro F1 Score:         {df['macro_f1'].mean():.4f} (±{df['macro_f1'].std():.4f})")
            if 'expected_return_mean' in df.columns:
                print(f"Expected Return:        {df['expected_return_mean'].mean():.6f} (±{df['expected_return_mean'].std():.4f})")

        print(f"Directional Accuracy:   {df['directional_accuracy'].mean():.4f} (±{df['directional_accuracy'].std():.4f})")
        print(f"Matthews Correlation:   {df['mcc'].mean():.4f} (±{df['mcc'].std():.4f})")
        print(f"F1 Score:              {df['f1'].mean():.4f} (±{df['f1'].std():.4f})")
        print(f"Precision:             {df['precision'].mean():.4f} (±{df['precision'].std():.4f})")
        print(f"Recall:                {df['recall'].mean():.4f} (±{df['recall'].std():.4f})")

        if self.problem_type == 'multiclass' and 'expected_return_mean' in df.columns:
            print("" + "="*50)
            print("TOP 10 BY EXPECTED RETURN (mean)")
            print("="*50)
            top_er = df.nlargest(10, 'expected_return_mean')
            for _, row in top_er.iterrows():
                print(f"{row['company']:<20} | {row['sector']:<15} | E[r]_mean: {row['expected_return_mean']:.4e} | Macro-F1: {row['macro_f1']:.3f}")

        if 'sector' in df.columns and df['sector'].nunique() > 1:
            print("" + "="*50)
            print("PERFORMANCE BY SECTOR")
            print("="*50)
            sector_stats = df.groupby('sector').agg({
                'directional_accuracy': ['mean', 'std', 'count'],
                'mcc': ['mean', 'std'],
                'r2': 'mean' if self.problem_type == 'regression' else lambda x: np.nan,
                'mae': 'mean' if self.problem_type == 'regression' else lambda x: np.nan
            }).round(4)
            sector_stats.columns = ['_'.join(col).strip() if col[1] else col[0] for col in sector_stats.columns]
            sector_stats = sector_stats.sort_values('directional_accuracy_mean', ascending=False)
            for sector, row in sector_stats.iterrows():
                print(f"{sector:<20} | Acc: {row['directional_accuracy_mean']:.3f}±{row['directional_accuracy_std']:.3f} | "
                      f"MCC: {row['mcc_mean']:.3f} | Companies: {int(row['directional_accuracy_count'])}")

        print("" + "="*50)
        print("TOP 10 PERFORMERS (by Directional Accuracy)")
        print("="*50)
        top_performers = df.nlargest(10, 'directional_accuracy')
        for _, row in top_performers.iterrows():
            print(f"{row['company']:<20} | {row['sector']:<15} | "
                  f"Acc: {row['directional_accuracy']:.3f} | MCC: {row['mcc']:.3f}")

        return analysis

    def save_results(self, results, output_dir='results/benchmarking'):
        if results is not None and not results.empty:
            model_name = self.model_type

            if self.problem_type == 'regression':
                out_dir = os.path.join(output_dir, 'regression')
            elif self.problem_type == 'classification':
                out_dir = os.path.join(output_dir, 'classification')
            else:
                out_dir = os.path.join(output_dir, 'multiclass')

            os.makedirs(out_dir, exist_ok=True)

            output_path = os.path.join(out_dir, f"{model_name}.csv")

            results.to_csv(output_path, index=False)
            print(f"Results saved to {output_path}")
        else:
            print("No results to save.")
            
    def get_loss_curves_df(self):
        if not self.loss_curves:
            print("No loss curves logged yet.")
            return pd.DataFrame()
        return pd.DataFrame(self.loss_curves)

    def save_loss_curves(self, out_path='results/benchmarking/'):
        df = self.get_loss_curves_df()
        if df.empty:
            print("No loss curves to save.")
            return
        if self.problem_type == 'regression':
            out_path = os.path.join(out_path, 'regression', f"{self.model_type}_loss_curves.csv")
        elif self.problem_type == 'classification':
            out_path = os.path.join(out_path, 'classification', f"{self.model_type}_loss_curves.csv")
        else:
            out_path = os.path.join(out_path, 'multiclass', f"{self.model_type}_loss_curves.csv")
            
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        
        df.to_csv(out_path, index=False)
        print(f"Loss curves saved to {out_path}")

    def get_feature_importance_analysis(self):
        print("Feature importance analysis not implemented yet.")
        print("Consider implementing SHAP values or permutation importance for better insights.")
        return None

## Data Preparation

In [6]:
master_df = pd.read_parquet('../data/dataset/ta_nlp_sector.parquet')

In [7]:
master_df.columns

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'ticker',
       'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
       'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
       'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'ret_1d',
       'roll_ret_1d', 'roll_ret_5d', 'roll_ret_20d', 'sentiment',
       'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
       'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
       'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
       'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
       'emotion_surprize_pct', 'positive_emotion', 'negative_emotion',
       'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct',
       'uncertainty_emotion_pct', 'stance_label', 'finbert_label',
       'stance_score', 'finbert_score', 'finbert_up', 'finbert_down',
       'finbert_neutral', 'sector', 'company_name', 'sector_open_mean',
       'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
       'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
       'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector',
       'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
       'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
       'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
       'market_close', 'sector_rel_strength', 'sector_dispersion_1d'],
      dtype='object')

In [8]:
master_df

,date,open,high,low,close,adj_close,volume,ticker,ema_12,ema_26,...,macd_12_26_9_sector,macdh_12_26_9_sector,macds_12_26_9_sector,rsi_14_sector,sector_bb_upper,sector_bb_middle,sector_bb_lower,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-09-04,95.108574,96.448570,94.928574,96.424286,87.121140,91973000.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1464.800169,NaN,NaN
1,2012-09-05,96.510002,96.621429,95.657143,95.747147,86.509338,84093800.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,1481.232189,NaN,0.006548
2,2012-09-06,96.167145,96.898575,95.828575,96.610001,87.288956,97799100.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,28.755774,NaN,NaN,NaN,1502.627054,NaN,0.006476
3,2012-09-07,96.864288,97.497147,96.538574,97.205711,87.827171,82416600.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,28.562466,NaN,NaN,NaN,1506.971629,NaN,0.008604
4,2012-09-10,97.207146,97.612854,94.585716,94.677139,85.542564,121999500.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,22.507443,NaN,NaN,NaN,1503.735325,NaN,0.012007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108587,2017-08-28,76.900002,76.940002,76.260002,76.470001,76.470001,8229700.0,XOM,77.187452,78.267858,...,-0.111192,0.016355,-0.127548,53.634155,63.049962,61.01430,58.978638,3101.328695,-0.007883,0.005228
108588,2017-08-29,76.209999,76.489998,76.080002,76.449997,76.449997,7060400.0,XOM,77.073998,78.133202,...,-0.067027,0.048417,-0.115443,54.205103,62.862103,60.94445,59.026797,3102.507723,-0.016661,0.002030
108589,2017-08-30,76.239998,76.449997,76.059998,76.099998,76.099998,8218000.0,XOM,76.924151,77.982594,...,-0.037643,0.062240,-0.099883,53.126723,62.639604,60.86875,59.097896,3128.753695,-0.017629,0.004873
108590,2017-08-31,76.269997,76.489998,76.050003,76.330002,76.330002,15641700.0,XOM,76.832744,77.860180,...,0.013408,0.090633,-0.077225,57.342960,62.525437,60.83190,59.138363,3141.201722,-0.008376,0.006185
108591,2017-09-01,76.370003,76.849998,76.320000,76.570000,76.570000,7340800.0,XOM,76.792322,77.764611,...,0.088512,0.132590,-0.044078,62.040301,62.426369,60.80760,59.188831,3136.813139,-0.001766,0.007085

In [9]:
columns_to_check = [
                    'sentiment',
                    
                    'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
                    'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
                    'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
                    'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
                    'emotion_surprize_pct', 
                    
                    'positive_emotion', 'negative_emotion','uncertainty_emotion', 
                    'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct', 
                    
                    'stance_label', 'stance_score', 
                    
                    'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
                    'finbert_neutral', 
                    
                    'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
                    'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
                    'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
                    
                    'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
                    'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
                    'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
                    'market_close', 'sector_rel_strength', 'sector_dispersion_1d'
                ]

print(f"Initial master_df shape: {master_df.shape}")

master_df = master_df.dropna(subset=columns_to_check)

print(f"After dropping NaNs in selected columns, master_df shape: {master_df.shape}")

master_df.reset_index(drop=True, inplace=True)

display(master_df)

Initial master_df shape: (108592, 79)
After dropping NaNs in selected columns, master_df shape: (104476, 79)

,date,open,high,low,close,adj_close,volume,ticker,ema_12,ema_26,...,macd_12_26_9_sector,macdh_12_26_9_sector,macds_12_26_9_sector,rsi_14_sector,sector_bb_upper,sector_bb_middle,sector_bb_lower,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-11-14,77.928574,78.207146,76.597145,76.697144,69.613815,119292600.0,AAPL,80.708033,84.949698,...,-0.913108,-0.181794,-0.731314,27.619972,63.948320,61.465736,58.983152,1484.350654,-0.003089,0.006800
1,2012-11-15,76.790001,77.071426,74.660004,75.088570,68.153778,197477700.0,AAPL,79.843501,84.219244,...,-0.926239,-0.155940,-0.770299,32.479352,63.646173,61.261193,58.876213,1484.574993,0.002003,0.019838
2,2012-11-16,75.028572,75.714287,72.250000,75.382858,68.420891,316723400.0,AAPL,79.157248,83.564697,...,-0.892113,-0.097452,-0.794662,37.450172,63.236926,61.078872,58.920817,1497.780485,0.010276,0.010265
3,2012-11-19,77.244286,81.071426,77.125717,80.818573,73.354591,205829400.0,AAPL,79.412836,83.361280,...,-0.733193,0.049174,-0.782368,51.350390,63.001827,61.010079,59.018330,1506.128807,0.024682,0.018850
4,2012-11-20,81.701431,81.707146,79.225716,80.129997,72.729614,160688500.0,AAPL,79.523169,83.121926,...,-0.579416,0.162361,-0.741778,53.267164,62.959435,60.996029,59.032623,1508.629302,0.025531,0.007554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104471,2017-08-28,76.900002,76.940002,76.260002,76.470001,76.470001,8229700.0,XOM,77.187452,78.267858,...,-0.111192,0.016355,-0.127548,53.634155,63.049962,61.014300,58.978638,3101.328695,-0.007883,0.005228
104472,2017-08-29,76.209999,76.489998,76.080002,76.449997,76.449997,7060400.0,XOM,77.073998,78.133202,...,-0.067027,0.048417,-0.115443,54.205103,62.862103,60.944450,59.026797,3102.507723,-0.016661,0.002030
104473,2017-08-30,76.239998,76.449997,76.059998,76.099998,76.099998,8218000.0,XOM,76.924151,77.982594,...,-0.037643,0.062240,-0.099883,53.126723,62.639604,60.868750,59.097896,3128.753695,-0.017629,0.004873
104474,2017-08-31,76.269997,76.489998,76.050003,76.330002,76.330002,15641700.0,XOM,76.832744,77.860180,...,0.013408,0.090633,-0.077225,57.342960,62.525437,60.831900,59.138363,3141.201722,-0.008376,0.006185
104475,2017-09-01,76.370003,76.849998,76.320000,76.570000,76.570000,7340800.0,XOM,76.792322,77.764611,...,0.088512,0.132590,-0.044078,62.040301,62.426369,60.807600,59.188831,3136.813139,-0.001766,0.007085

In [10]:
print(master_df.columns)

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'ticker',
       'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
       'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
       'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'ret_1d',
       'roll_ret_1d', 'roll_ret_5d', 'roll_ret_20d', 'sentiment',
       'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
       'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
       'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
       'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
       'emotion_surprize_pct', 'positive_emotion', 'negative_emotion',
       'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct',
       'uncertainty_emotion_pct', 'stance_label', 'finbert_label',
       'stance_score', 'finbert_score', 'finbert_up', 'finbert_down',
       'finbert_neutral', 'sector', 'company_name', 'sector_open_mean',
       'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
       'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
       'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector',
       'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
       'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
       'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
       'market_close', 'sector_rel_strength', 'sector_dispersion_1d'],
      dtype='object')

In [11]:
feature_columns = [
    'open', 'high', 'low', 'close', 'volume',
    # 'roll_ret_1d', 'roll_ret_5d', 
    # 'roll_ret_20d',
    
    'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
    'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
    'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv',
]

new_indicator_columns = [
    # 'sentiment',
                    
    # 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
    # 'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
    # 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
    # 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
    # 'emotion_surprize_pct', 
    
    # 'positive_emotion', 'negative_emotion','uncertainty_emotion', 
    # 'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct', 
    
    # 'stance_label', 'stance_score', 
    
    # 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
    # 'finbert_neutral', 
    
    # 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
    # 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
    # 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
    
    # 'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
    # 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
    # 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
    # 'market_close', 'sector_rel_strength', 'sector_dispersion_1d'
]

# feature_columns.extend(new_indicator_columns)



sequence_length=12



all_pipelines = {}
all_results_dfs = {}
all_analyses = {}
fixed_bucket_edges = np.array([-0.08, -0.03, -0.01, 0.0, 0.01, 0.03, 0.08], dtype=float)
n_classes = len(fixed_bucket_edges) - 1
ordinal_head = 'corn'

In [12]:
print(master_df.shape)
master_df = master_df.dropna(subset=feature_columns).sort_values(['ticker','date'])
print(master_df.shape)

(104476, 79)
(104220, 79)

## Pipeline Execution

In [13]:
# print(f"\n{'='*25}\n  RUNNING PIPELINE FOR: GRU\n{'='*25}\n")

# pipeline_GRU = StockPredictionPipeline(
#     df=master_df,
#     feature_columns=feature_columns,
#     model_type='GRU',
#     sequence_length=sequence_length,
#     problem_type='classification',
#     horizon_steps=1,
#     n_classes=n_classes,
#     ordinal_head=ordinal_head,
#     fixed_bucket_edges=fixed_bucket_edges
# )

# results_GRU = pipeline_GRU.run_pipeline()

# loss_df = pipeline_GRU.get_loss_curves_df()

# pipeline_GRU.save_loss_curves('results/benchmarking/')

# if results_GRU is not None and not results_GRU.empty:
#     analysis_GRU = pipeline_GRU.analyze_results()
#     pipeline_GRU.save_results(results_GRU, output_dir='results/benchmarking/')
#     all_pipelines["GRU"] = pipeline_GRU
#     all_results_dfs["GRU"] = results_GRU
#     all_analyses["GRU"] = analysis_GRU

#     print("\nDisplaying first 5 rows of GRU results:")
#     display(results_GRU.head())
# else:
#     print(f"\n[FAILED] Pipeline for GRU did not produce any results.")

# del pipeline_GRU

In [14]:
sentinemt_columns = [
    'sentiment',
]

emotion_columns = [
    'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
    'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
    'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
    'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
    'emotion_surprize_pct',
]

unified_emotion_columns = [
    'positive_emotion', 'negative_emotion','uncertainty_emotion',
    'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct',
]

stance_columns = [
    'stance_label', 'stance_score',
]

finbert_columns = [
    'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
    'finbert_neutral',
]

sector_columns = ['sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
                  'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
                  'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
                  
                  'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
                  'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
                  'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
                  'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

# Hyper Parameter Tuning

In [15]:
try:
    import optuna
except ImportError:
    import sys
    !{sys.executable} -m pip install optuna
    import optuna
    
from pathlib import Path
from datetime import datetime
    
# Define feature sets to test
feature_sets = {
    'base': feature_columns,
    # 'sentinment' : feature_columns + sentinemt_columns,
    # 'emotion' : feature_columns + emotion_columns,
    # 'unified_emotion': feature_columns + unified_emotion_columns,
    # 'finbert': feature_columns + finbert_columns,
    # 'all_nlp': feature_columns + sentinemt_columns + emotion_columns + unified_emotion_columns + stance_columns + finbert_columns,
    # 'sector': feature_columns + sector_columns,
    # 'sector_sentiment': feature_columns + sector_columns + sentinemt_columns,
    # 'sector_emotion': feature_columns + sector_columns + emotion_columns,
    # 'sector_unified_emotion': feature_columns + sector_columns + unified_emotion_columns,
    # 'sector_finbert': feature_columns + sector_columns + finbert_columns,
    # 'sector_all_nlp': feature_columns + sector_columns + sentinemt_columns + emotion_columns + unified_emotion_columns + stance_columns + finbert_columns,
}

def objective(trial):
    params = {
        'problem_type': 'classification',  # or 'classification'
        'feature_set': trial.suggest_categorical('feature_set', list(feature_sets.keys())),
        'model_type': trial.suggest_categorical('model_type', ['LSTM', 'BiLSTM', 'GRU', 'BiGRU']),
        'sequence_length': trial.suggest_int('sequence_length',5, 20, step=5),
        'horizon_steps': trial.suggest_categorical('horizon_steps', [1]),
        'hidden1': trial.suggest_categorical('hidden1', [64, 128, 256]),
        'hidden2': trial.suggest_categorical('hidden2', [32, 64, 128]),
        'num_layers': trial.suggest_categorical('num_layers', [1, 2]),
        'inter_rnn_drop': trial.suggest_float('inter_rnn_drop', 0.0, 0.4, step=0.1),
        'dropout': trial.suggest_float('dropout', 0.0, 0.8, step=0.1),
        'batch_size': trial.suggest_categorical('batch_size', [16, 32, 64]),
        'learning_rate': trial.suggest_float('learning_rate', 1e-6, 1e-2, log=True),
        'weight_decay': trial.suggest_float('weight_decay', 1e-7, 1e-3, log=True),
        'lr_patience': trial.suggest_categorical('lr_patience', [5, 7, 10]),
        'lr_factor': trial.suggest_categorical('lr_factor', [0.4, 0.8]),
        'early_stopping_patience': trial.suggest_categorical('early_stopping_patience', [10, 15, 20]),
        'max_epochs': trial.suggest_categorical('max_epochs', [20, 30, 50]),
        'huber_delta': trial.suggest_float('huber_delta', 0.1, 2.0),
        'early_stopping_min_delta': trial.suggest_float('early_stopping_min_delta', 0.0, 0.01),
    }

    selected_features = feature_sets[params['feature_set']]
    missing_cols = [c for c in selected_features if c not in master_df.columns]
    if missing_cols:
        print(f"Missing columns for feature_set={params['feature_set']}: {missing_cols}")
        return -1.0

    pipeline = StockPredictionPipeline(
        df=master_df,
        feature_columns=selected_features,
        model_type=params['model_type'],
        sequence_length=params['sequence_length'],
        problem_type=params['problem_type'],
        horizon_steps=params['horizon_steps'],
        n_classes=n_classes,
        ordinal_head=ordinal_head,
        fixed_bucket_edges=fixed_bucket_edges,
        hidden1=params['hidden1'],
        hidden2=params['hidden2'],
        num_layers=params['num_layers'],
        inter_rnn_drop=params['inter_rnn_drop'],
        dropout=params['dropout'],
        batch_size=params['batch_size'],
        learning_rate=params['learning_rate'],
        weight_decay=params['weight_decay'],
        lr_patience=params['lr_patience'],
        lr_factor=params['lr_factor'],
        early_stopping_patience=params['early_stopping_patience'],
        max_epochs=params['max_epochs'],
        huber_delta=params['huber_delta'],
        early_stopping_min_delta=params['early_stopping_min_delta']
    )

    results_df = pipeline.run_pipeline()
    del pipeline
    torch.cuda.empty_cache()

    if results_df is None or results_df.empty:
        print('[DEBUG] results_df empty or None')
        return -1.0

    print('[DEBUG] results_df shape:', results_df.shape)
    print('[DEBUG] results_df columns:', results_df.columns.tolist())

    # Aggregate validation metrics
    val_f1 = results_df['val_f1'].mean() if 'val_f1' in results_df.columns else np.nan
    if not np.isfinite(val_f1) and 'best_threshold_metric' in results_df.columns:
        val_f1 = results_df['best_threshold_metric'].mean()
    val_mcc = results_df['val_mcc'].mean() if 'val_mcc' in results_df.columns else np.nan
    print('[DEBUG] val_mcc:', val_mcc)
    val_precision = results_df['val_precision'].mean() if 'val_precision' in results_df.columns else np.nan
    val_recall = results_df['val_recall'].mean() if 'val_recall' in results_df.columns else np.nan
    val_dir_acc = results_df['val_directional_accuracy'].mean() if 'val_directional_accuracy' in results_df.columns else np.nan

    trial.set_user_attr('val_f1', float(val_f1))
    trial.set_user_attr('val_mcc', float(val_mcc))
    trial.set_user_attr('val_precision', float(val_precision))
    trial.set_user_attr('val_recall', float(val_recall))
    trial.set_user_attr('val_directional_accuracy', float(val_dir_acc))

    # Primary metric: mean val MCC (classification) or mean MAE (regression)
    if params['problem_type'] == 'classification':
        score = val_mcc
        if not np.isfinite(score):
            return -1.0
        return float(score)
    else:
        # minimize MAE -> maximize negative MAE
        if 'mae' not in results_df.columns:
            return -1.0
        mae = results_df['mae'].mean()
        if not np.isfinite(mae):
            return -1.0
        return float(-mae)


N_TRIALS = 250

# Run study
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=N_TRIALS, timeout=60*60*10)  # 10 hours max
# Collect results
optuna_results = study.trials_dataframe()
# include user attrs
user_attrs = pd.DataFrame([t.user_attrs for t in study.trials])
optuna_results = pd.concat([optuna_results, user_attrs], axis=1)
optuna_results = optuna_results.sort_values('value', ascending=False)
optuna_results

timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
out_path = f'../results/benchmarking/classification/optuna_tuning_base_1H.csv'
Path('../results/benchmarking/classification').mkdir(parents=True, exist_ok=True)
optuna_results.to_csv(out_path, index=False)
print(f'Saved Optuna results to {out_path}')

[I 2026-02-25 21:42:18,516] A new study created in memory with name: no-name-f7c00d41-bcb5-47f6-aedb-5c151cfc66e3

Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69687 | val 0.72722
  Epoch 016 - train 0.69490 | val 0.72713
  Classification -> best τ=0.435 (val F1=0.1826)
  Directional -> Accuracy: 0.4850, MCC: 0.0261, F1: 0.4432

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.68550 | val 0.79868
  Epoch 016 - train 0.69053 | val 0.79937
  Classification -> best τ=0.420 (val F1=0.1601)
  Directional -> Accuracy: 0.5350, MCC: 0.0793, F1: 0.3922

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68368 | val 0.72874
  Epoch 016 - train 0.68482 | val 0.72887
  Classification -> best τ=0.400 (val F1=0.2310)
  Directional -> Accuracy: 0.5080, MCC: -0.0258, F1: 0.5929

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.70811 | val 0.69823
  Epoch 016 - train 0.70478 | val 0.69763
  Classification -> best τ=0.530 (val F1=0.0697)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.7179

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.71455 | val 0.79007
  Epoch 016 - train 0.71473 | val 0.78875
  Classification -> best τ=0.475 (val F1=0.0684)
  Directional -> Accuracy: 0.5234, MCC: 0.0000, F1: 0.6871

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68960 | val 0.70677
  Epoch 016 - train 0.68954 | val 0.70664
  Classification -> best τ=0.545 (val F1=0.0937)
  Directional -> Accuracy: 0.4300, MCC: -0.1378, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69429 | val 0.80765
  Epoch 016 - train 0.69249 | val 0.80859
  Classification -> best τ=0.365 (val F1=0.1319)
  Directional -> Accuracy: 0.5350, MCC: 0.0301, F1: 0.6235

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69588 | val 0.71445
  Epoch 016 - train 0.69676 | val 0.71336
  Classification -> best τ=0.480 (val F1=0.0861)
  Directional -> Accuracy: 0.6050, MCC: 0.0000, F1: 0.7539

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70322 | val 0.73583
  Epoch 016 - train 0.69960 | val 0.73535
  Classification -> best τ=0.460 (val F1=0.0973)
  Directional -> Accuracy: 0.5217, MCC: -0.0528, F1: 0.6452

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71983 | val 0.71801
  Epoch 016 - train 0.71590 | val 0.71638
  Classification -> best τ=0.520 (val F1=0.0616)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.70651 | val 0.69192
  Epoch 016 - train 0.70492 | val 0.69175
  Classification -> best τ=0.495 (val F1=0.0776)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.68362 | val 0.70727
  Epoch 016 - train 0.68538 | val 0.70714
  Classification -> best τ=0.465 (val F1=0.1141)
  Directional -> Accuracy: 0.4900, MCC: -0.0435, F1: 0.5565

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71033 | val 0.69103
  Epoch 016 - train 0.70518 | val 0.69062
  Classification -> best τ=0.495 (val F1=0.0825)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.7179

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69235 | val 0.70801
  Epoch 016 - train 0.69587 | val 0.70721
  Classification -> best τ=0.470 (val F1=0.1120)
  Directional -> Accuracy: 0.4550, MCC: -0.0897, F1: 0.4631

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.71877 | val 0.70716
  Epoch 016 - train 0.72005 | val 0.70720
  Classification -> best τ=0.525 (val F1=0.0929)
  Directional -> Accuracy: 0.4700, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.72707 | val 0.69675
  Epoch 016 - train 0.72845 | val 0.69569
  Classification -> best τ=0.540 (val F1=0.0948)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5455

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.71283 | val 0.73234
  Epoch 016 - train 0.70974 | val 0.73096
  Classification -> best τ=0.485 (val F1=0.1015)
  Directional -> Accuracy: 0.5400, MCC: 0.0057, F1: 0.6714

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69035 | val 0.70120
  Epoch 016 - train 0.68922 | val 0.70124
  Classification -> best τ=0.530 (val F1=0.1134)
  Directional -> Accuracy: 0.4850, MCC: -0.0030, F1: 0.0190

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70178 | val 0.75673
  Epoch 016 - train 0.70363 | val 0.75570
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69360 | val 0.70204
  Epoch 016 - train 0.69377 | val 0.70174
  Classification -> best τ=0.500 (val F1=0.0027)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.71404 | val 0.74431
  Epoch 016 - train 0.71533 | val 0.74333
  Classification -> best τ=0.515 (val F1=0.0574)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.6577

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.69403 | val 0.72511
  Epoch 016 - train 0.69635 | val 0.72352
  Classification -> best τ=0.530 (val F1=0.1744)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.71126 | val 0.69408
  Epoch 019 - train 0.71031 | val 0.69394
  Classification -> best τ=0.490 (val F1=0.1361)
  Directional -> Accuracy: 0.5250, MCC: 0.0172, F1: 0.6154

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.71645 | val 0.69867
  Epoch 016 - train 0.71140 | val 0.69821
  Classification -> best τ=0.485 (val F1=0.0667)
  Directional -> Accuracy: 0.4100, MCC: -0.0541, F1: 0.5203

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69841 | val 0.71386
  Epoch 016 - train 0.69682 | val 0.71290
  Classification -> best τ=0.580 (val F1=0.0635)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.2016

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68799 | val 0.71690
  Epoch 016 - train 0.68975 | val 0.71650
  Classification -> best τ=0.435 (val F1=0.1042)
  Directional -> Accuracy: 0.5100, MCC: 0.0613, F1: 0.6370

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69286 | val 0.68518
  Epoch 016 - train 0.69149 | val 0.68483
  Classification -> best τ=0.545 (val F1=0.1279)
  Directional -> Accuracy: 0.4550, MCC: -0.0768, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.69106 | val 0.70941
  Epoch 016 - train 0.69537 | val 0.71029
  Classification -> best τ=0.465 (val F1=0.0605)
  Directional -> Accuracy: 0.5050, MCC: 0.0320, F1: 0.6644

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68868 | val 0.69118
  Epoch 016 - train 0.69373 | val 0.69114
  Classification -> best τ=0.525 (val F1=0.1310)
  Directional -> Accuracy: 0.4900, MCC: 0.0688, F1: 0.0192

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.72194 | val 0.72827
  Epoch 016 - train 0.71113 | val 0.72770
  Classification -> best τ=0.535 (val F1=0.0302)
  Directional -> Accuracy: 0.4700, MCC: 0.0447, F1: 0.0702

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.69708 | val 0.76248
  Epoch 016 - train 0.69252 | val 0.76293
  Classification -> best τ=0.495 (val F1=0.1292)
  Directional -> Accuracy: 0.4950, MCC: 0.0000, F1: 0.0000

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.71834 | val 0.85687
  Epoch 016 - train 0.71392 | val 0.85846
  Classification -> best τ=0.395 (val F1=0.1753)
  Directional -> Accuracy: 0.5550, MCC: 0.0487, F1: 0.6962

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.71481 | val 0.71282
  Epoch 016 - train 0.71669 | val 0.71214
  Classification -> best τ=0.445 (val F1=0.0388)
  Directional -> Accuracy: 0.5850, MCC: -0.0821, F1: 0.7365

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69941 | val 0.70580
  Epoch 016 - train 0.69882 | val 0.70671
  Classification -> best τ=0.530 (val F1=0.0995)
  Directional -> Accuracy: 0.5300, MCC: -0.0152, F1: 0.2419

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.71566 | val 0.68674
  Epoch 016 - train 0.72024 | val 0.68789
  Classification -> best τ=0.520 (val F1=0.1551)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6250

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69951 | val 0.76694
  Epoch 016 - train 0.69890 | val 0.76454
  Classification -> best τ=0.575 (val F1=0.0702)
  Directional -> Accuracy: 0.4250, MCC: -0.0609, F1: 0.2675

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69805 | val 0.70856
  Epoch 016 - train 0.69721 | val 0.70787
  Classification -> best τ=0.475 (val F1=0.0599)
  Directional -> Accuracy: 0.5300, MCC: -0.0209, F1: 0.6887

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.71378 | val 0.69374
  Epoch 016 - train 0.71135 | val 0.69333
  Classification -> best τ=0.490 (val F1=0.0747)
  Directional -> Accuracy: 0.5650, MCC: 0.0000, F1: 0.7220

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.70009 | val 0.70881
  Epoch 016 - train 0.69844 | val 0.71033
  Classification -> best τ=0.455 (val F1=0.0831)
  Directional -> Accuracy: 0.4600, MCC: 0.0648, F1: 0.0182

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.70141 | val 0.72017
  Epoch 016 - train 0.70104 | val 0.72046
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.6885

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.71092 | val 0.76258
  Epoch 016 - train 0.70642 | val 0.76305
  Classification -> best τ=0.570 (val F1=0.1199)
  Directional -> Accuracy: 0.5550, MCC: 0.1069, F1: 0.5899

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70541 | val 0.68929
  Epoch 016 - train 0.70248 | val 0.68993
  Classification -> best τ=0.510 (val F1=0.1102)
  Directional -> Accuracy: 0.5000, MCC: 0.0081, F1: 0.4949

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69540 | val 0.72448
  Epoch 016 - train 0.69447 | val 0.72240
  Classification -> best τ=0.505 (val F1=0.0797)
  Directional -> Accuracy: 0.4350, MCC: -0.1595, F1: 0.5425

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69615 | val 0.69399
  Epoch 016 - train 0.70097 | val 0.69363
  Classification -> best τ=0.565 (val F1=0.2425)
  Directional -> Accuracy: 0.5100, MCC: -0.0516, F1: 0.6711

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.72342 | val 0.78658
  Epoch 016 - train 0.72139 | val 0.78158
  Classification -> best τ=0.625 (val F1=0.0550)
  Directional -> Accuracy: 0.5200, MCC: 0.0975, F1: 0.3600

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69605 | val 0.71568
  Epoch 016 - train 0.69514 | val 0.71612
  Classification -> best τ=0.400 (val F1=0.1355)
  Directional -> Accuracy: 0.5850, MCC: 0.0000, F1: 0.7382

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71629 | val 0.70921
  Epoch 016 - train 0.71286 | val 0.70853
  Classification -> best τ=0.495 (val F1=0.1064)
  Directional -> Accuracy: 0.4150, MCC: -0.1181, F1: 0.0640

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.71277 | val 1.06229
  Epoch 016 - train 0.70772 | val 1.06305
  Classification -> best τ=0.375 (val F1=0.0409)
  Directional -> Accuracy: 0.3900, MCC: -0.0671, F1: 0.0317

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68530 | val 0.73620
  Epoch 016 - train 0.69009 | val 0.73728
  Classification -> best τ=0.430 (val F1=0.0842)
  Directional -> Accuracy: 0.5150, MCC: 0.0788, F1: 0.6523

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69099 | val 0.69152
  Epoch 016 - train 0.69170 | val 0.69146
  Classification -> best τ=0.540 (val F1=0.0408)
  Directional -> Accuracy: 0.4900, MCC: 0.0708, F1: 0.3377

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71719 | val 0.84468
  Epoch 016 - train 0.71765 | val 0.84559
  Classification -> best τ=0.375 (val F1=0.1370)
  Directional -> Accuracy: 0.5850, MCC: 0.1569, F1: 0.6311

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69487 | val 0.73812
  Epoch 016 - train 0.69642 | val 0.73853
  Classification -> best τ=0.470 (val F1=0.0498)
  Directional -> Accuracy: 0.4950, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69435 | val 0.82073
  Epoch 016 - train 0.69074 | val 0.82136
  Classification -> best τ=0.445 (val F1=0.0891)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.68600 | val 0.69576
  Epoch 016 - train 0.68815 | val 0.69577
  Classification -> best τ=0.545 (val F1=0.1305)
  Directional -> Accuracy: 0.4050, MCC: 0.0000, F1: 0.0000

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.69580 | val 0.71360
  Epoch 016 - train 0.69195 | val 0.71392
  Classification -> best τ=0.460 (val F1=0.1025)
  Directional -> Accuracy: 0.4750, MCC: -0.0633, F1: 0.6154

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.71103 | val 0.72606
  Epoch 016 - train 0.71029 | val 0.72576
  Classification -> best τ=0.580 (val F1=0.0738)
  Directional -> Accuracy: 0.4800, MCC: 0.0099, F1: 0.1034

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70311 | val 0.77606
  Epoch 016 - train 0.70455 | val 0.77565
  Classification -> best τ=0.525 (val F1=0.0709)
  Directional -> Accuracy: 0.5000, MCC: 0.1106, F1: 0.2647

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.69096 | val 0.75566
  Epoch 016 - train 0.69169 | val 0.75794
  Classification -> best τ=0.440 (val F1=0.1509)
  Directional -> Accuracy: 0.4950, MCC: -0.0020, F1: 0.4656

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.70673 | val 0.74528
  Epoch 016 - train 0.70724 | val 0.74271
  Classification -> best τ=0.655 (val F1=0.0722)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69848 | val 0.72328
  Epoch 016 - train 0.70361 | val 0.72163
  Classification -> best τ=0.565 (val F1=0.0661)
  Directional -> Accuracy: 0.4850, MCC: -0.0155, F1: 0.4309

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70757 | val 0.78026
  Epoch 016 - train 0.70548 | val 0.77911
  Classification -> best τ=0.560 (val F1=0.0400)
  Directional -> Accuracy: 0.5500, MCC: 0.0897, F1: 0.2969

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71994 | val 0.72836
  Epoch 016 - train 0.71795 | val 0.72666
  Classification -> best τ=0.500 (val F1=0.0755)
  Directional -> Accuracy: 0.5100, MCC: 0.0020, F1: 0.6733

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.70216 | val 0.70753
  Epoch 016 - train 0.70425 | val 0.70739
  Classification -> best τ=0.410 (val F1=0.0674)
  Directional -> Accuracy: 0.4650, MCC: 0.0000, F1: 0.6348

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.69541 | val 0.69270
  Epoch 016 - train 0.69563 | val 0.69428
  Classification -> best τ=0.540 (val F1=0.1782)
  Directional -> Accuracy: 0.4400, MCC: 0.0215, F1: 0.1250

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.69097 | val 0.71686
  Epoch 016 - train 0.69225 | val 0.71545
  Classification -> best τ=0.540 (val F1=0.0509)
  Directional -> Accuracy: 0.5400, MCC: 0.0109, F1: 0.6489

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.69988 | val 0.72716
  Epoch 016 - train 0.70214 | val 0.72638
  Classification -> best τ=0.480 (val F1=0.0036)
  Directional -> Accuracy: 0.4822, MCC: -0.1307, F1: 0.2273

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.70029 | val 0.68867
  Epoch 016 - train 0.70127 | val 0.68845
  Classification -> best τ=0.545 (val F1=0.0801)
  Directional -> Accuracy: 0.4700, MCC: 0.0000, F1: 0.0000

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.70456 | val 0.69313
  Epoch 016 - train 0.70110 | val 0.69328
  Classification -> best τ=0.540 (val F1=0.0938)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70434 | val 0.71348
  Epoch 016 - train 0.70348 | val 0.71287
  Classification -> best τ=0.470 (val F1=0.0568)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.6063

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.70878 | val 0.75962
  Epoch 016 - train 0.71004 | val 0.75928
  Classification -> best τ=0.630 (val F1=0.1008)
  Directional -> Accuracy: 0.5025, MCC: 0.0000, F1: 0.0000

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.71090 | val 0.69770
  Epoch 016 - train 0.71304 | val 0.69838
  Classification -> best τ=0.525 (val F1=0.0866)
  Directional -> Accuracy: 0.4400, MCC: -0.1635, F1: 0.5659

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70688 | val 0.77719
  Epoch 016 - train 0.70306 | val 0.77771
  Classification -> best τ=0.525 (val F1=0.0668)
  Directional -> Accuracy: 0.4850, MCC: -0.0043, F1: 0.0374

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.69064 | val 0.89175
  Epoch 016 - train 0.69282 | val 0.89588
  Classification -> best τ=0.460 (val F1=0.0277)
  Directional -> Accuracy: 0.4550, MCC: 0.0000, F1: 0.6254

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.69922 | val 0.70023
  Epoch 016 - train 0.69713 | val 0.70006
  Classification -> best τ=0.490 (val F1=0.1154)
  Directional -> Accuracy: 0.5250, MCC: -0.0338, F1: 0.6865

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70369 | val 0.74986
  Epoch 016 - train 0.70398 | val 0.74829
  Classification -> best τ=0.475 (val F1=0.1341)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
  Epoch 010 - train 0.70750 | val 0.70079
  Epoch 016 - train 0.70095 | val 0.70006
  Classification -> best τ=0.440 (val F1=0.0985)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
  Epoch 010 - train 0.70330 | val 0.70338
  Epoch 016 - train 0.69294 | val 0.70273
  Classification -> best τ=0.560 (val F1=0.0946)
  Directional -> Accuracy: 0.4700, MCC: 0.0000, F1: 0.0000

[78/88] Processing TSM...

Processing TSM (Technology)...

[I 2026-02-25 21:44:13,549] Trial 0 finished with value: 0.092435537020652 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 1.14202371184081e-06, 'weight_decay': 3.848989263428851e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.9345740712345617, 'early_stopping_min_delta': 0.00644972254518335}. Best is trial 0 with value: 0.092435537020652.

  Epoch 016 - train 0.68752 | val 0.69843
  Classification -> best τ=0.495 (val F1=0.1206)
  Directional -> Accuracy: 0.5350, MCC: 0.0685, F1: 0.5079

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.092435537020652
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67521 | val 0.76683
  Epoch 016 - train 0.67907 | val 0.74354
  Classification -> best τ=0.525 (val F1=0.0606)
  Directional -> Accuracy: 0.5000, MCC: -0.0262, F1: 0.5690

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.66862 | val 0.94789
  Epoch 016 - train 0.66280 | val 0.99211
  Classification -> best τ=0.490 (val F1=0.1151)
  Directional -> Accuracy: 0.5400, MCC: 0.0912, F1: 0.3947

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67894 | val 0.70667
  Epoch 016 - train 0.67626 | val 0.72328
  Classification -> best τ=0.475 (val F1=0.0537)
  Directional -> Accuracy: 0.4225, MCC: -0.0573, F1: 0.1692

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.67839 | val 0.71310
  Epoch 016 - train 0.67411 | val 0.73601
  Classification -> best τ=0.520 (val F1=0.0509)
  Directional -> Accuracy: 0.4700, MCC: -0.0081, F1: 0.3690

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.68775 | val 0.69539
  Epoch 016 - train 0.65588 | val 0.70904
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5234, MCC: 0.0000, F1: 0.6871

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67274 | val 0.72312
  Epoch 016 - train 0.66170 | val 0.75770
  Classification -> best τ=0.525 (val F1=0.0938)
  Directional -> Accuracy: 0.4650, MCC: 0.0355, F1: 0.1705

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68075 | val 0.79065
  Epoch 016 - train 0.67833 | val 0.82430
  Classification -> best τ=0.560 (val F1=0.1258)
  Directional -> Accuracy: 0.4200, MCC: -0.1154, F1: 0.0645

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67196 | val 0.69180
  Epoch 017 - train 0.65090 | val 0.69720
  Classification -> best τ=0.445 (val F1=0.2667)
  Directional -> Accuracy: 0.4600, MCC: 0.0836, F1: 0.2987

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66254 | val 1.06417
  Epoch 016 - train 0.66147 | val 1.09141
  Classification -> best τ=0.490 (val F1=0.1739)
  Directional -> Accuracy: 0.4174, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68840 | val 0.86539
  Epoch 016 - train 0.67333 | val 0.89558
  Classification -> best τ=0.520 (val F1=0.0668)
  Directional -> Accuracy: 0.4500, MCC: -0.0630, F1: 0.5736

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.67306 | val 0.69016
  Epoch 016 - train 0.66256 | val 0.71073
  Classification -> best τ=0.505 (val F1=0.0820)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.67590 | val 0.71516
  Epoch 016 - train 0.67118 | val 0.71449
  Classification -> best τ=0.530 (val F1=0.1500)
  Directional -> Accuracy: 0.4250, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68092 | val 0.73577
  Epoch 016 - train 0.65625 | val 0.71634
  Classification -> best τ=0.525 (val F1=0.0348)
  Directional -> Accuracy: 0.5600, MCC: 0.1029, F1: 0.6140

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67690 | val 0.78586
  Epoch 016 - train 0.66957 | val 0.85475
  Classification -> best τ=0.515 (val F1=0.1212)
  Directional -> Accuracy: 0.5100, MCC: 0.0174, F1: 0.3718

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.68316 | val 0.71035
  Epoch 016 - train 0.67183 | val 0.71305
  Classification -> best τ=0.480 (val F1=0.0889)
  Directional -> Accuracy: 0.4700, MCC: -0.0165, F1: 0.1167

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.67819 | val 0.72295
  Epoch 016 - train 0.66755 | val 0.74062
  Classification -> best τ=0.460 (val F1=0.0433)
  Directional -> Accuracy: 0.5100, MCC: 0.1005, F1: 0.0392

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.66970 | val 0.70209
  Epoch 016 - train 0.65933 | val 0.73793
  Classification -> best τ=0.455 (val F1=0.1119)
  Directional -> Accuracy: 0.5550, MCC: 0.0000, F1: 0.7138

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67659 | val 0.73553
  Epoch 016 - train 0.67163 | val 0.77084
  Classification -> best τ=0.530 (val F1=0.0918)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67171 | val 0.68559
  Epoch 019 - train 0.66945 | val 0.70136
  Classification -> best τ=0.570 (val F1=0.2330)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66724 | val 0.72508
  Epoch 016 - train 0.68039 | val 0.73107
  Classification -> best τ=0.520 (val F1=0.0385)
  Directional -> Accuracy: 0.5200, MCC: -0.0100, F1: 0.6418

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.67420 | val 0.68782
  Epoch 020 - train 0.66413 | val 0.69134
  Classification -> best τ=0.580 (val F1=0.1854)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.6577

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.68899 | val 0.99995
  Epoch 016 - train 0.68722 | val 1.06797
  Classification -> best τ=0.510 (val F1=0.1531)
  Directional -> Accuracy: 0.5550, MCC: -0.0093, F1: 0.7043

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67189 | val 0.70246
  Epoch 016 - train 0.67630 | val 0.72114
  Classification -> best τ=0.485 (val F1=0.1046)
  Directional -> Accuracy: 0.4700, MCC: 0.0530, F1: 0.1017

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.67591 | val 0.76599
  Epoch 016 - train 0.67143 | val 0.78692
  Classification -> best τ=0.500 (val F1=0.0861)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.5663

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68272 | val 0.81850
  Epoch 016 - train 0.68035 | val 0.88395
  Classification -> best τ=0.490 (val F1=0.0892)
  Directional -> Accuracy: 0.4650, MCC: -0.0576, F1: 0.2914

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66453 | val 0.69879
  Epoch 018 - train 0.66737 | val 0.70396
  Classification -> best τ=0.480 (val F1=0.1556)
  Directional -> Accuracy: 0.5450, MCC: 0.0884, F1: 0.5236

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67773 | val 0.84071
  Epoch 016 - train 0.67791 | val 0.92357
  Classification -> best τ=0.485 (val F1=0.0395)
  Directional -> Accuracy: 0.4650, MCC: -0.0008, F1: 0.1157

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.67976 | val 0.81160
  Epoch 016 - train 0.66792 | val 0.97751
  Classification -> best τ=0.540 (val F1=0.0449)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67383 | val 0.77384
  Epoch 016 - train 0.67663 | val 0.84451
  Classification -> best τ=0.510 (val F1=0.1517)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.68592 | val 0.71832
  Epoch 020 - train 0.66875 | val 0.74719
  Classification -> best τ=0.430 (val F1=0.1275)
  Directional -> Accuracy: 0.4550, MCC: -0.0664, F1: 0.3699

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.68091 | val 0.72464
  Epoch 016 - train 0.67171 | val 0.75030
  Classification -> best τ=0.465 (val F1=0.0740)
  Directional -> Accuracy: 0.5000, MCC: 0.0073, F1: 0.2958

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67904 | val 0.77166
  Epoch 016 - train 0.67506 | val 0.73410
  Classification -> best τ=0.480 (val F1=0.0438)
  Directional -> Accuracy: 0.5500, MCC: 0.0254, F1: 0.6980

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.70035 | val 0.69781
  Epoch 016 - train 0.68405 | val 0.70131
  Classification -> best τ=0.485 (val F1=0.0576)
  Directional -> Accuracy: 0.5500, MCC: -0.0136, F1: 0.6715

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66877 | val 0.78982
  Epoch 016 - train 0.67032 | val 0.80825
  Classification -> best τ=0.475 (val F1=0.1155)
  Directional -> Accuracy: 0.5650, MCC: 0.0871, F1: 0.3741

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.69491 | val 0.73138
  Epoch 016 - train 0.67286 | val 0.79224
  Classification -> best τ=0.480 (val F1=0.0368)
  Directional -> Accuracy: 0.4375, MCC: -0.2582, F1: 0.0000

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67829 | val 0.72405
  Epoch 016 - train 0.66997 | val 0.72531
  Classification -> best τ=0.480 (val F1=0.1448)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68422 | val 0.72440
  Epoch 016 - train 0.66875 | val 0.74166
  Classification -> best τ=0.515 (val F1=0.1272)
  Directional -> Accuracy: 0.4700, MCC: 0.0661, F1: 0.0185

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.67956 | val 0.74245
  Epoch 016 - train 0.66871 | val 0.76938
  Classification -> best τ=0.490 (val F1=0.0944)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.67766 | val 0.88069
  Epoch 016 - train 0.66084 | val 0.97818
  Classification -> best τ=0.475 (val F1=0.0729)
  Directional -> Accuracy: 0.4550, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.68376 | val 1.05019
  Epoch 016 - train 0.66995 | val 1.13536
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.6885

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.68004 | val 0.98530
  Epoch 016 - train 0.66636 | val 0.99752
  Classification -> best τ=0.570 (val F1=0.1659)
  Directional -> Accuracy: 0.4900, MCC: 0.0215, F1: 0.0727

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68193 | val 0.74386
  Epoch 016 - train 0.67851 | val 0.75631
  Classification -> best τ=0.530 (val F1=0.0685)
  Directional -> Accuracy: 0.5700, MCC: 0.1171, F1: 0.6884

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68306 | val 0.75584
  Epoch 016 - train 0.66722 | val 0.74012
  Classification -> best τ=0.470 (val F1=0.1196)
  Directional -> Accuracy: 0.4850, MCC: -0.0183, F1: 0.3439

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68469 | val 0.70815
  Epoch 016 - train 0.68180 | val 0.71274
  Classification -> best τ=0.505 (val F1=0.1582)
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67446 | val 1.14097
  Epoch 016 - train 0.66277 | val 1.38682
  Classification -> best τ=0.455 (val F1=0.0835)
  Directional -> Accuracy: 0.4700, MCC: -0.0527, F1: 0.4592

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68338 | val 0.72856
  Epoch 016 - train 0.67990 | val 0.73895
  Classification -> best τ=0.495 (val F1=0.0680)
  Directional -> Accuracy: 0.5850, MCC: 0.0000, F1: 0.7382

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67970 | val 0.70692
  Epoch 016 - train 0.67919 | val 0.70230
  Classification -> best τ=0.510 (val F1=0.1300)
  Directional -> Accuracy: 0.5800, MCC: 0.1041, F1: 0.6912

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68438 | val 0.77221
  Epoch 016 - train 0.67011 | val 0.77393
  Classification -> best τ=0.475 (val F1=0.1174)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67442 | val 0.73129
  Epoch 016 - train 0.67363 | val 0.76864
  Classification -> best τ=0.490 (val F1=0.0041)
  Directional -> Accuracy: 0.4700, MCC: -0.0660, F1: 0.3977

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68196 | val 0.70671
  Epoch 016 - train 0.66667 | val 0.70569
  Classification -> best τ=0.475 (val F1=0.0382)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68100 | val 0.81369
  Epoch 016 - train 0.67421 | val 0.87929
  Classification -> best τ=0.465 (val F1=0.0945)
  Directional -> Accuracy: 0.5500, MCC: 0.0353, F1: 0.6691

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68192 | val 0.69752
  Epoch 016 - train 0.67618 | val 0.70575
  Classification -> best τ=0.480 (val F1=0.0945)
  Directional -> Accuracy: 0.4950, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68826 | val 0.70868
  Epoch 016 - train 0.68144 | val 0.74455
  Classification -> best τ=0.515 (val F1=0.1502)
  Directional -> Accuracy: 0.5100, MCC: -0.0272, F1: 0.6711

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.68083 | val 1.01574
  Epoch 016 - train 0.67885 | val 1.02953
  Classification -> best τ=0.480 (val F1=0.0918)
  Directional -> Accuracy: 0.4050, MCC: -0.0276, F1: 0.0325

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.68381 | val 0.76366
  Epoch 016 - train 0.67842 | val 0.78364
  Classification -> best τ=0.455 (val F1=0.0884)
  Directional -> Accuracy: 0.4850, MCC: -0.0604, F1: 0.6485

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67086 | val 0.71411
  Epoch 016 - train 0.67694 | val 0.76721
  Classification -> best τ=0.515 (val F1=0.0499)
  Directional -> Accuracy: 0.4500, MCC: -0.1277, F1: 0.5455

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68887 | val 0.69896
  Epoch 016 - train 0.67337 | val 0.72834
  Classification -> best τ=0.500 (val F1=0.0414)
  Directional -> Accuracy: 0.4550, MCC: -0.0061, F1: 0.1138

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.68839 | val 0.70057
  Epoch 016 - train 0.67510 | val 0.73371
  Classification -> best τ=0.495 (val F1=0.0282)
  Directional -> Accuracy: 0.5100, MCC: 0.0591, F1: 0.3378

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66473 | val 0.80577
  Epoch 016 - train 0.66537 | val 0.86633
  Classification -> best τ=0.510 (val F1=0.1184)
  Directional -> Accuracy: 0.4200, MCC: -0.0130, F1: 0.0794

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66654 | val 0.81710
  Epoch 016 - train 0.66825 | val 0.93471
  Classification -> best τ=0.535 (val F1=0.1401)
  Directional -> Accuracy: 0.4800, MCC: -0.0064, F1: 0.2973

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68109 | val 0.73490
  Epoch 016 - train 0.68278 | val 0.75377
  Classification -> best τ=0.495 (val F1=0.0516)
  Directional -> Accuracy: 0.5350, MCC: 0.1057, F1: 0.0412

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67868 | val 0.76747
  Epoch 016 - train 0.67194 | val 0.88053
  Classification -> best τ=0.475 (val F1=0.1830)
  Directional -> Accuracy: 0.4750, MCC: -0.0498, F1: 0.4776

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.66951 | val 0.70901
  Epoch 016 - train 0.67150 | val 0.72475
  Classification -> best τ=0.515 (val F1=0.0493)
  Directional -> Accuracy: 0.5350, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.67036 | val 0.91088
  Epoch 016 - train 0.65554 | val 1.05722
  Classification -> best τ=0.490 (val F1=0.1103)
  Directional -> Accuracy: 0.4450, MCC: 0.0169, F1: 0.1778

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.68076 | val 1.01981
  Epoch 016 - train 0.67544 | val 1.09566
  Classification -> best τ=0.545 (val F1=0.0908)
  Directional -> Accuracy: 0.4500, MCC: 0.0141, F1: 0.2254

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.68284 | val 0.72504
  Epoch 016 - train 0.66867 | val 0.76648
  Classification -> best τ=0.525 (val F1=0.2243)
  Directional -> Accuracy: 0.5025, MCC: 0.0924, F1: 0.5776

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.67614 | val 0.69100
  Epoch 018 - train 0.67096 | val 0.80058
  Classification -> best τ=0.560 (val F1=0.1314)
  Directional -> Accuracy: 0.5150, MCC: 0.0783, F1: 0.3490

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.67972 | val 0.72922
  Epoch 016 - train 0.67159 | val 0.73982
  Classification -> best τ=0.515 (val F1=0.0211)
  Directional -> Accuracy: 0.5025, MCC: 0.0000, F1: 0.6689

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68355 | val 0.69803
  Epoch 018 - train 0.67360 | val 0.72865
  Classification -> best τ=0.510 (val F1=0.2684)
  Directional -> Accuracy: 0.4350, MCC: -0.0717, F1: 0.5311

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.67798 | val 0.70570
  Epoch 016 - train 0.68776 | val 0.72679
  Classification -> best τ=0.510 (val F1=0.1454)
  Directional -> Accuracy: 0.4569, MCC: -0.1145, F1: 0.2074

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.68451 | val 0.79380
  Epoch 016 - train 0.68530 | val 0.80644
  Classification -> best τ=0.505 (val F1=0.1100)
  Directional -> Accuracy: 0.4900, MCC: -0.0222, F1: 0.5143

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68629 | val 0.71451
  Epoch 016 - train 0.67928 | val 0.76192
  Classification -> best τ=0.530 (val F1=0.0047)
  Directional -> Accuracy: 0.5550, MCC: 0.2103, F1: 0.6983

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.68061 | val 1.33831
  Epoch 016 - train 0.66723 | val 1.97208
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4550, MCC: 0.0000, F1: 0.6254

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.67445 | val 0.81818
  Epoch 016 - train 0.67471 | val 0.81794
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5300, MCC: 0.0000, F1: 0.6928

[75/88] Processing T...


[I 2026-02-25 21:46:19,281] Trial 1 finished with value: 0.09740132288506914 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.0007317922010215577, 'weight_decay': 0.0007033113283574763, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.4566482413618725, 'early_stopping_min_delta': 0.006916262752870346}. Best is trial 1 with value: 0.09740132288506914.

  Epoch 016 - train 0.66961 | val 0.73387
  Classification -> best τ=0.520 (val F1=0.1238)
  Directional -> Accuracy: 0.5200, MCC: 0.1025, F1: 0.0400

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.09740132288506914
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69063 | val 0.69641
  Epoch 016 - train 0.68461 | val 0.69815
  Classification -> best τ=0.440 (val F1=0.1690)
  Directional -> Accuracy: 0.4798, MCC: 0.0451, F1: 0.3905

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.69483 | val 0.68176
  Epoch 020 - train 0.67862 | val 0.69875
  Classification -> best τ=0.510 (val F1=0.1367)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6644

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68351 | val 0.69676
  Epoch 016 - train 0.66833 | val 0.69944
  Classification -> best τ=0.530 (val F1=0.0718)
  Directional -> Accuracy: 0.4973, MCC: 0.0860, F1: 0.3922

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.68669 | val 0.75642
  Epoch 016 - train 0.67935 | val 0.80042
  Classification -> best τ=0.525 (val F1=0.0778)
  Directional -> Accuracy: 0.4293, MCC: -0.0813, F1: 0.0000

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.72722 | val 0.77007
  Epoch 016 - train 0.71367 | val 0.76523
  Classification -> best τ=0.575 (val F1=0.0391)
  Directional -> Accuracy: 0.4623, MCC: -0.0572, F1: 0.3448

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69335 | val 0.69559
  Epoch 016 - train 0.68204 | val 0.69773
  Classification -> best τ=0.515 (val F1=0.1543)
  Directional -> Accuracy: 0.5303, MCC: 0.0499, F1: 0.5753

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69092 | val 0.78962
  Epoch 016 - train 0.69017 | val 0.86048
  Classification -> best τ=0.520 (val F1=0.1057)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68432 | val 0.69171
  Epoch 020 - train 0.67636 | val 0.68537
  Classification -> best τ=0.405 (val F1=0.2850)
  Directional -> Accuracy: 0.5051, MCC: 0.0150, F1: 0.5505

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70608 | val 0.68936
  Epoch 016 - train 0.68950 | val 0.69113
  Classification -> best τ=0.475 (val F1=0.0980)
  Directional -> Accuracy: 0.4867, MCC: -0.0282, F1: 0.5246

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70218 | val 0.69886
  Epoch 016 - train 0.69780 | val 0.70183
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.6298

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.69312 | val 0.72769
  Epoch 016 - train 0.67288 | val 0.71757
  Classification -> best τ=0.425 (val F1=0.0774)
  Directional -> Accuracy: 0.5455, MCC: 0.0773, F1: 0.7039

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.69275 | val 0.68651
  Epoch 020 - train 0.67525 | val 0.69436
  Classification -> best τ=0.420 (val F1=0.1682)
  Directional -> Accuracy: 0.5505, MCC: 0.0528, F1: 0.6397

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67664 | val 0.71714
  Epoch 020 - train 0.66558 | val 0.70370
  Classification -> best τ=0.365 (val F1=0.1210)
  Directional -> Accuracy: 0.5303, MCC: 0.0312, F1: 0.6043

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69350 | val 0.69147
  Epoch 020 - train 0.68647 | val 0.70631
  Classification -> best τ=0.500 (val F1=0.1271)
  Directional -> Accuracy: 0.5152, MCC: 0.0329, F1: 0.5556

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.69198 | val 0.70529
  Epoch 016 - train 0.68798 | val 0.70617
  Classification -> best τ=0.515 (val F1=0.1039)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.69344 | val 0.70066
  Epoch 016 - train 0.68141 | val 0.70091
  Classification -> best τ=0.530 (val F1=0.0003)
  Directional -> Accuracy: 0.4646, MCC: -0.0708, F1: 0.4536

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.69160 | val 0.69367
  Epoch 020 - train 0.69129 | val 0.69732
  Classification -> best τ=0.640 (val F1=0.0766)
  Directional -> Accuracy: 0.4697, MCC: 0.0182, F1: 0.2657

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68486 | val 0.69282
  Epoch 016 - train 0.68135 | val 0.69429
  Classification -> best τ=0.505 (val F1=0.1230)
  Directional -> Accuracy: 0.4848, MCC: -0.0133, F1: 0.2388

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68957 | val 0.69883
  Epoch 016 - train 0.68585 | val 0.69293
  Classification -> best τ=0.480 (val F1=0.1927)
  Directional -> Accuracy: 0.4949, MCC: -0.0010, F1: 0.0196

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69416 | val 0.69740
  Epoch 016 - train 0.69759 | val 0.69672
  Classification -> best τ=0.560 (val F1=0.0519)
  Directional -> Accuracy: 0.5354, MCC: 0.0459, F1: 0.6167

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.68883 | val 0.69132
  Epoch 020 - train 0.69245 | val 0.68622
  Classification -> best τ=0.595 (val F1=0.1843)
  Directional -> Accuracy: 0.5758, MCC: 0.1621, F1: 0.4324

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.70412 | val 0.80690
  Epoch 016 - train 0.70338 | val 0.83126
  Classification -> best τ=0.375 (val F1=0.1076)
  Directional -> Accuracy: 0.5707, MCC: 0.0746, F1: 0.7157

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69698 | val 0.80455
  Epoch 016 - train 0.68578 | val 0.82333
  Classification -> best τ=0.480 (val F1=0.1037)
  Directional -> Accuracy: 0.4646, MCC: 0.0192, F1: 0.0536

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.68866 | val 0.71188
  Epoch 016 - train 0.67799 | val 0.71997
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3939, MCC: 0.0000, F1: 0.5652

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68833 | val 0.77037
  Epoch 016 - train 0.67824 | val 0.82105
  Classification -> best τ=0.535 (val F1=0.0916)
  Directional -> Accuracy: 0.4747, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67783 | val 0.69219
  Epoch 020 - train 0.67504 | val 0.69073
  Classification -> best τ=0.515 (val F1=0.1403)
  Directional -> Accuracy: 0.5101, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69829 | val 0.76004
  Epoch 016 - train 0.69267 | val 0.79652
  Classification -> best τ=0.545 (val F1=0.0896)
  Directional -> Accuracy: 0.4545, MCC: -0.0092, F1: 0.0182

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.69694 | val 0.72792
  Epoch 016 - train 0.69147 | val 0.74746
  Classification -> best τ=0.500 (val F1=0.1225)
  Directional -> Accuracy: 0.5101, MCC: 0.0204, F1: 0.5403

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68670 | val 0.69899
  Epoch 016 - train 0.67709 | val 0.69987
  Classification -> best τ=0.535 (val F1=0.1308)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.69200 | val 0.81193
  Epoch 016 - train 0.68867 | val 0.82814
  Classification -> best τ=0.410 (val F1=0.1321)
  Directional -> Accuracy: 0.5455, MCC: 0.0092, F1: 0.7039

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.69393 | val 0.68951
  Epoch 016 - train 0.70286 | val 0.68803
  Classification -> best τ=0.495 (val F1=0.1087)
  Directional -> Accuracy: 0.5101, MCC: 0.0000, F1: 0.6756

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68665 | val 0.68657
  Epoch 016 - train 0.68832 | val 0.68908
  Classification -> best τ=0.540 (val F1=0.0970)
  Directional -> Accuracy: 0.4646, MCC: -0.0250, F1: 0.3375

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.70278 | val 0.73300
  Epoch 016 - train 0.69555 | val 0.72830
  Classification -> best τ=0.495 (val F1=0.1028)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69042 | val 0.73419
  Epoch 016 - train 0.68701 | val 0.73006
  Classification -> best τ=0.430 (val F1=0.1274)
  Directional -> Accuracy: 0.5253, MCC: 0.0144, F1: 0.3896

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.67094 | val 0.70417
  Epoch 016 - train 0.67715 | val 0.72280
  Classification -> best τ=0.495 (val F1=0.1173)
  Directional -> Accuracy: 0.5652, MCC: 0.1391, F1: 0.4737

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69304 | val 0.73894
  Epoch 016 - train 0.68547 | val 0.73891
  Classification -> best τ=0.405 (val F1=0.1163)
  Directional -> Accuracy: 0.4798, MCC: -0.0130, F1: 0.4772

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69328 | val 0.73338
  Epoch 016 - train 0.68877 | val 0.73157
  Classification -> best τ=0.485 (val F1=0.1112)
  Directional -> Accuracy: 0.4646, MCC: -0.0757, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.68504 | val 0.74868
  Epoch 016 - train 0.68866 | val 0.78477
  Classification -> best τ=0.475 (val F1=0.0926)
  Directional -> Accuracy: 0.5101, MCC: -0.0706, F1: 0.6394

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.69566 | val 0.71513
  Epoch 016 - train 0.69183 | val 0.74223
  Classification -> best τ=0.480 (val F1=0.0806)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.68646 | val 0.73875
  Epoch 016 - train 0.67854 | val 0.78208
  Classification -> best τ=0.495 (val F1=0.1603)
  Directional -> Accuracy: 0.4192, MCC: -0.1562, F1: 0.2675

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.69043 | val 0.71228
  Epoch 016 - train 0.69511 | val 0.71252
  Classification -> best τ=0.540 (val F1=0.0256)
  Directional -> Accuracy: 0.4697, MCC: -0.0744, F1: 0.5494

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69015 | val 0.72503
  Epoch 016 - train 0.68587 | val 0.73954
  Classification -> best τ=0.505 (val F1=0.0651)
  Directional -> Accuracy: 0.4899, MCC: 0.0274, F1: 0.3399

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69376 | val 0.72331
  Epoch 020 - train 0.68142 | val 0.69812
  Classification -> best τ=0.530 (val F1=0.0752)
  Directional -> Accuracy: 0.4899, MCC: -0.0985, F1: 0.6529

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.71161 | val 0.73543
  Epoch 016 - train 0.69931 | val 0.72559
  Classification -> best τ=0.365 (val F1=0.0736)
  Directional -> Accuracy: 0.5505, MCC: 0.0961, F1: 0.5899

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68042 | val 0.88885
  Epoch 016 - train 0.68161 | val 0.91975
  Classification -> best τ=0.465 (val F1=0.0699)
  Directional -> Accuracy: 0.5505, MCC: 0.0620, F1: 0.6787

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69017 | val 0.75957
  Epoch 016 - train 0.68188 | val 0.76713
  Classification -> best τ=0.455 (val F1=0.1098)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68549 | val 0.72139
  Epoch 016 - train 0.68682 | val 0.71542
  Classification -> best τ=0.505 (val F1=0.0836)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69274 | val 0.72452
  Epoch 016 - train 0.68055 | val 0.72610
  Classification -> best τ=0.530 (val F1=0.0676)
  Directional -> Accuracy: 0.3990, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68936 | val 0.70307
  Epoch 016 - train 0.68458 | val 0.71042
  Classification -> best τ=0.570 (val F1=0.0945)
  Directional -> Accuracy: 0.5505, MCC: 0.1068, F1: 0.3206

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68029 | val 0.69586
  Epoch 016 - train 0.68718 | val 0.69624
  Classification -> best τ=0.470 (val F1=0.0759)
  Directional -> Accuracy: 0.5657, MCC: 0.0000, F1: 0.7226

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69152 | val 0.69479
  Epoch 016 - train 0.68287 | val 0.68834
  Classification -> best τ=0.545 (val F1=0.0627)
  Directional -> Accuracy: 0.4848, MCC: -0.0046, F1: 0.4516

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68933 | val 0.70039
  Epoch 016 - train 0.68505 | val 0.70736
  Classification -> best τ=0.500 (val F1=0.0967)
  Directional -> Accuracy: 0.5051, MCC: 0.0010, F1: 0.6689

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69018 | val 0.72201
  Epoch 016 - train 0.68422 | val 0.74379
  Classification -> best τ=0.505 (val F1=0.0920)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.69022 | val 0.72371
  Epoch 020 - train 0.68542 | val 0.69139
  Classification -> best τ=0.540 (val F1=0.0566)
  Directional -> Accuracy: 0.4949, MCC: -0.0123, F1: 0.5413

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.69243 | val 0.73245
  Epoch 016 - train 0.68881 | val 0.74597
  Classification -> best τ=0.505 (val F1=0.0834)
  Directional -> Accuracy: 0.5303, MCC: 0.0723, F1: 0.2901

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68829 | val 0.71815
  Epoch 016 - train 0.68886 | val 0.72661
  Classification -> best τ=0.450 (val F1=0.0031)
  Directional -> Accuracy: 0.5202, MCC: 0.0000, F1: 0.6844

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68046 | val 0.70048
  Epoch 016 - train 0.68108 | val 0.71051
  Classification -> best τ=0.515 (val F1=0.0419)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.69081 | val 0.84185
  Epoch 016 - train 0.69263 | val 0.87127
  Classification -> best τ=0.550 (val F1=0.0431)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67783 | val 0.85583
  Epoch 016 - train 0.67708 | val 0.86091
  Classification -> best τ=0.480 (val F1=0.1727)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69150 | val 0.71975
  Epoch 016 - train 0.68620 | val 0.71801
  Classification -> best τ=0.475 (val F1=0.1413)
  Directional -> Accuracy: 0.4545, MCC: -0.0591, F1: 0.1000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68732 | val 0.71522
  Epoch 016 - train 0.68772 | val 0.72804
  Classification -> best τ=0.540 (val F1=0.2190)
  Directional -> Accuracy: 0.4798, MCC: -0.0660, F1: 0.3087

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70131 | val 0.70496
  Epoch 016 - train 0.68700 | val 0.70814
  Classification -> best τ=0.490 (val F1=0.1065)
  Directional -> Accuracy: 0.5152, MCC: 0.0148, F1: 0.6336

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.68836 | val 0.77954
  Epoch 016 - train 0.68038 | val 0.79930
  Classification -> best τ=0.540 (val F1=0.1492)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.69001 | val 0.74924
  Epoch 016 - train 0.68169 | val 0.80146
  Classification -> best τ=0.545 (val F1=0.0283)
  Directional -> Accuracy: 0.5202, MCC: -0.0307, F1: 0.6332

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.69376 | val 0.82787
  Epoch 016 - train 0.69284 | val 0.84619
  Classification -> best τ=0.435 (val F1=0.1456)
  Directional -> Accuracy: 0.5152, MCC: -0.0235, F1: 0.6098

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.67795 | val 0.68784
  Epoch 020 - train 0.68150 | val 0.69107
  Classification -> best τ=0.585 (val F1=0.1248)
  Directional -> Accuracy: 0.5795, MCC: 0.0000, F1: 0.0000

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.67676 | val 0.75794
  Epoch 016 - train 0.68455 | val 0.75427
  Classification -> best τ=0.375 (val F1=0.0782)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.6931

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.69363 | val 0.70923
  Epoch 016 - train 0.68848 | val 0.71487
  Classification -> best τ=0.545 (val F1=0.0923)
  Directional -> Accuracy: 0.5026, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67969 | val 0.69233
  Epoch 020 - train 0.67535 | val 0.68566
  Classification -> best τ=0.420 (val F1=0.1823)
  Directional -> Accuracy: 0.4495, MCC: -0.0431, F1: 0.5439

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.69132 | val 0.71494
  Epoch 016 - train 0.68535 | val 0.71125
  Classification -> best τ=0.525 (val F1=0.0019)
  Directional -> Accuracy: 0.5026, MCC: 0.0077, F1: 0.5359

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.69638 | val 0.71446
  Epoch 016 - train 0.68993 | val 0.71626
  Classification -> best τ=0.555 (val F1=0.0315)
  Directional -> Accuracy: 0.4747, MCC: -0.0742, F1: 0.0000

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69077 | val 0.92283
  Epoch 016 - train 0.70042 | val 0.93574
  Classification -> best τ=0.425 (val F1=0.1087)
  Directional -> Accuracy: 0.5152, MCC: 0.0000, F1: 0.6800

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.68968 | val 0.75419
  Epoch 016 - train 0.68639 | val 0.78477
  Classification -> best τ=0.425 (val F1=0.1102)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.68750 | val 0.72456
  Epoch 016 - train 0.68251 | val 0.73342
  Classification -> best τ=0.510 (val F1=0.1079)
  Directional -> Accuracy: 0.5051, MCC: 0.0896, F1: 0.1967

[75/88] Processing T...


[I 2026-02-25 21:47:56,172] Trial 2 finished with value: 0.09993482326927444 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.6000000000000001, 'batch_size': 64, 'learning_rate': 8.698117093917212e-05, 'weight_decay': 0.0003657742902549558, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.4585381873270957, 'early_stopping_min_delta': 0.003640771101999322}. Best is trial 2 with value: 0.09993482326927444.

  Epoch 016 - train 0.68990 | val 0.69513
  Classification -> best τ=0.475 (val F1=0.1244)
  Directional -> Accuracy: 0.5000, MCC: 0.0306, F1: 0.6598

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.09993482326927444
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62077 | val 2.00285
  Epoch 020 - train 0.46116 | val 3.19950
  Epoch 021 - train 0.44374 | val 3.01757
  Classification -> best τ=0.715 (val F1=0.1825)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.55627 | val 4.55491
  Epoch 020 - train 0.27692 | val 16.64632
  Epoch 021 - train 0.25261 | val 17.67197
  Classification -> best τ=0.705 (val F1=0.1747)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59832 | val 1.15901
  Epoch 020 - train 0.34360 | val 2.31371
  Epoch 022 - train 0.26551 | val 2.58563
  Classification -> best τ=0.145 (val F1=0.2113)
  Directional -> Accuracy: 0.5401, MCC: -0.0566, F1: 0.6838

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.66280 | val 0.68518
  Epoch 020 - train 0.53515 | val 0.70071
  Epoch 027 - train 0.41996 | val 1.30511
  Classification -> best τ=0.615 (val F1=0.1847)
  Directional -> Accuracy: 0.4100, MCC: -0.1516, F1: 0.0635

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.62364 | val 1.10282
  Epoch 020 - train 0.36645 | val 1.71275
  Epoch 023 - train 0.30492 | val 1.67725
  Classification -> best τ=0.740 (val F1=0.1714)
  Directional -> Accuracy: 0.4766, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59587 | val 1.35791
  Epoch 020 - train 0.35390 | val 4.41421
  Epoch 021 - train 0.29595 | val 4.37613
  Classification -> best τ=0.665 (val F1=0.1403)
  Directional -> Accuracy: 0.4700, MCC: 0.0640, F1: 0.1587

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62495 | val 0.87463
  Epoch 020 - train 0.42563 | val 1.99994
  Epoch 021 - train 0.38309 | val 2.05605
  Classification -> best τ=0.650 (val F1=0.1038)
  Directional -> Accuracy: 0.5400, MCC: 0.0182, F1: 0.6541

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60098 | val 1.35516
  Epoch 020 - train 0.30250 | val 4.25837
  Epoch 023 - train 0.23489 | val 5.19480
  Classification -> best τ=0.450 (val F1=0.2349)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.48477 | val 4.44339
  Epoch 020 - train 0.21126 | val 12.05202
  Epoch 021 - train 0.16582 | val 12.33448
  Classification -> best τ=0.360 (val F1=0.1540)
  Directional -> Accuracy: 0.5826, MCC: 0.0000, F1: 0.7363

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63807 | val 1.19977
  Epoch 020 - train 0.33054 | val 4.21509
  Epoch 025 - train 0.23226 | val 5.29287
  Classification -> best τ=0.905 (val F1=0.0616)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.65357 | val 1.09291
  Epoch 020 - train 0.55188 | val 1.21192
  Epoch 028 - train 0.38395 | val 2.09547
  Classification -> best τ=0.535 (val F1=0.1566)
  Directional -> Accuracy: 0.4550, MCC: -0.0464, F1: 0.1926

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.64464 | val 0.77692
  Epoch 020 - train 0.37914 | val 1.13846
  Epoch 026 - train 0.22326 | val 1.52211
  Classification -> best τ=0.815 (val F1=0.1418)
  Directional -> Accuracy: 0.4250, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63138 | val 1.38936
  Epoch 020 - train 0.50410 | val 0.73734
  Epoch 030 - train 0.29208 | val 1.24754
  Classification -> best τ=0.500 (val F1=0.1806)
  Directional -> Accuracy: 0.4850, MCC: 0.0735, F1: 0.2797

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55772 | val 2.76681
  Epoch 020 - train 0.31015 | val 7.40640
  Epoch 021 - train 0.25910 | val 7.63586
  Classification -> best τ=0.490 (val F1=0.1323)
  Directional -> Accuracy: 0.4750, MCC: -0.0510, F1: 0.4503

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.68665 | val 1.01149
  Epoch 020 - train 0.56415 | val 2.76962
  Epoch 028 - train 0.38355 | val 4.55020
  Classification -> best τ=0.525 (val F1=0.0756)
  Directional -> Accuracy: 0.4700, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.58541 | val 3.06037
  Epoch 020 - train 0.35321 | val 6.34501
  Epoch 021 - train 0.30983 | val 6.80816
  Classification -> best τ=0.220 (val F1=0.0990)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6503

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.59085 | val 0.90849
  Epoch 020 - train 0.37863 | val 1.75978
  Epoch 021 - train 0.33295 | val 1.82910
  Classification -> best τ=0.260 (val F1=0.0820)
  Directional -> Accuracy: 0.5550, MCC: 0.0000, F1: 0.7138

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57975 | val 1.68130
  Epoch 020 - train 0.32992 | val 3.71813
  Epoch 021 - train 0.27750 | val 2.85083
  Classification -> best τ=0.305 (val F1=0.0776)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66763 | val 1.01751
  Epoch 020 - train 0.36215 | val 1.17145
  Epoch 024 - train 0.26271 | val 1.51548
  Classification -> best τ=0.390 (val F1=0.2695)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57978 | val 1.12672
  Epoch 020 - train 0.33042 | val 1.99404
  Epoch 021 - train 0.27186 | val 1.95901
  Classification -> best τ=0.240 (val F1=0.0772)
  Directional -> Accuracy: 0.5400, MCC: 0.0141, F1: 0.6954

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.66789 | val 1.58013
  Epoch 020 - train 0.47293 | val 5.11373
  Epoch 026 - train 0.34296 | val 7.30964
  Classification -> best τ=0.390 (val F1=0.1332)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.6577

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.64610 | val 3.67783
  Epoch 020 - train 0.46807 | val 13.65896
  Epoch 023 - train 0.39482 | val 16.15485
  Classification -> best τ=0.055 (val F1=0.2312)
  Directional -> Accuracy: 0.4400, MCC: 0.0622, F1: 0.0175

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64149 | val 0.88893
  Epoch 020 - train 0.57535 | val 1.84361
  Epoch 030 - train 0.27030 | val 4.40943
  Classification -> best τ=0.360 (val F1=0.1979)
  Directional -> Accuracy: 0.5500, MCC: 0.0571, F1: 0.6667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.63841 | val 2.24366
  Epoch 020 - train 0.35085 | val 5.72383
  Epoch 023 - train 0.26809 | val 6.93669
  Classification -> best τ=0.710 (val F1=0.1292)
  Directional -> Accuracy: 0.5900, MCC: -0.0056, F1: 0.1087

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57817 | val 3.77691
  Epoch 020 - train 0.35767 | val 6.89931
  Epoch 021 - train 0.30686 | val 7.09567
  Classification -> best τ=0.100 (val F1=0.1153)
  Directional -> Accuracy: 0.5550, MCC: 0.1026, F1: 0.6337

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61270 | val 1.53831
  Epoch 020 - train 0.41856 | val 4.42383
  Epoch 021 - train 0.36165 | val 4.63045
  Classification -> best τ=0.305 (val F1=0.1643)
  Directional -> Accuracy: 0.5400, MCC: 0.0810, F1: 0.5400

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59710 | val 1.34201
  Epoch 020 - train 0.42276 | val 3.80244
  Epoch 021 - train 0.32025 | val 4.17873
  Classification -> best τ=0.765 (val F1=0.1279)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.66075 | val 0.84035
  Epoch 020 - train 0.49224 | val 1.59047
  Epoch 027 - train 0.31534 | val 2.57905
  Classification -> best τ=0.420 (val F1=0.1188)
  Directional -> Accuracy: 0.4850, MCC: -0.1234, F1: 0.6532

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65706 | val 0.76504
  Epoch 020 - train 0.48298 | val 1.99841
  Epoch 024 - train 0.42298 | val 2.42610
  Classification -> best τ=0.610 (val F1=0.1536)
  Directional -> Accuracy: 0.4800, MCC: -0.0449, F1: 0.0189

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.61555 | val 1.19261
  Epoch 020 - train 0.33845 | val 1.99393
  Epoch 021 - train 0.28419 | val 2.19053
  Classification -> best τ=0.710 (val F1=0.1709)
  Directional -> Accuracy: 0.4550, MCC: -0.0414, F1: 0.0840

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.57688 | val 4.88428
  Epoch 020 - train 0.36867 | val 16.07409
  Epoch 022 - train 0.32453 | val 16.26900
  Classification -> best τ=0.320 (val F1=0.1508)
  Directional -> Accuracy: 0.4800, MCC: -0.0612, F1: 0.6090

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59790 | val 0.82690
  Epoch 020 - train 0.38516 | val 1.02219
  Epoch 021 - train 0.34105 | val 1.22704
  Classification -> best τ=0.685 (val F1=0.1345)
  Directional -> Accuracy: 0.4400, MCC: -0.0743, F1: 0.2432

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.64528 | val 0.95407
  Epoch 020 - train 0.57310 | val 2.63513
  Epoch 028 - train 0.41970 | val 5.28694
  Classification -> best τ=0.810 (val F1=0.0937)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63372 | val 0.69197
  Epoch 020 - train 0.45525 | val 0.87412
  Epoch 030 - train 0.23468 | val 0.99332
  Classification -> best τ=0.530 (val F1=0.0995)
  Directional -> Accuracy: 0.5900, MCC: 0.1434, F1: 0.3492

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.36282 | val 1.73626
  Epoch 020 - train 0.09965 | val 4.78570
  Epoch 021 - train 0.11300 | val 4.90101
  Classification -> best τ=0.460 (val F1=0.3227)
  Directional -> Accuracy: 0.5833, MCC: 0.1672, F1: 0.6000

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63787 | val 0.85957
  Epoch 020 - train 0.35019 | val 2.73354
  Epoch 024 - train 0.24344 | val 3.01366
  Classification -> best τ=0.440 (val F1=0.2492)
  Directional -> Accuracy: 0.5150, MCC: 0.0740, F1: 0.4974

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60935 | val 1.99993
  Epoch 020 - train 0.39405 | val 5.12992
  Epoch 021 - train 0.35685 | val 5.49027
  Classification -> best τ=0.490 (val F1=0.1711)
  Directional -> Accuracy: 0.4650, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.63301 | val 1.68474
  Epoch 020 - train 0.38954 | val 3.22604
  Epoch 026 - train 0.21897 | val 4.61496
  Classification -> best τ=0.240 (val F1=0.1187)
  Directional -> Accuracy: 0.5850, MCC: 0.1282, F1: 0.6745

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.64457 | val 1.76986
  Epoch 020 - train 0.40733 | val 7.63367
  Epoch 023 - train 0.32697 | val 8.43268
  Classification -> best τ=0.565 (val F1=0.0908)
  Directional -> Accuracy: 0.4450, MCC: -0.0676, F1: 0.2238

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.64821 | val 0.97823
  Epoch 020 - train 0.41416 | val 2.26363
  Epoch 023 - train 0.32747 | val 2.68834
  Classification -> best τ=0.645 (val F1=0.1025)
  Directional -> Accuracy: 0.5100, MCC: 0.1104, F1: 0.1967

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.63970 | val 1.03664
  Epoch 020 - train 0.40181 | val 1.80161
  Epoch 024 - train 0.33960 | val 4.32515
  Classification -> best τ=0.650 (val F1=0.0988)
  Directional -> Accuracy: 0.4800, MCC: -0.0730, F1: 0.0000

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62985 | val 1.36823
  Epoch 020 - train 0.45981 | val 1.38981
  Epoch 029 - train 0.25362 | val 1.76090
  Classification -> best τ=0.730 (val F1=0.0519)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65295 | val 0.79412
  Epoch 020 - train 0.58571 | val 2.29566
  Epoch 030 - train 0.37728 | val 2.91185
  Classification -> best τ=0.135 (val F1=0.1443)
  Directional -> Accuracy: 0.5200, MCC: 0.0449, F1: 0.6800

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57562 | val 2.94749
  Epoch 020 - train 0.25509 | val 9.74798
  Epoch 021 - train 0.19681 | val 10.13577
  Classification -> best τ=0.415 (val F1=0.1048)
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55278 | val 1.83854
  Epoch 020 - train 0.29388 | val 6.76766
  Epoch 028 - train 0.15716 | val 8.47266
  Classification -> best τ=0.085 (val F1=0.1319)
  Directional -> Accuracy: 0.5300, MCC: 0.0258, F1: 0.6412

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60279 | val 0.93685
  Epoch 020 - train 0.41590 | val 1.51603
  Epoch 021 - train 0.38368 | val 1.57042
  Classification -> best τ=0.600 (val F1=0.0909)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63900 | val 1.24642
  Epoch 020 - train 0.42034 | val 2.95092
  Epoch 026 - train 0.26261 | val 3.94445
  Classification -> best τ=0.800 (val F1=0.1418)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60539 | val 1.51788
  Epoch 020 - train 0.25369 | val 3.67891
  Epoch 022 - train 0.17930 | val 3.93089
  Classification -> best τ=0.290 (val F1=0.0645)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55870 | val 2.13938
  Epoch 020 - train 0.36009 | val 5.90527
  Epoch 021 - train 0.28737 | val 6.48791
  Classification -> best τ=0.305 (val F1=0.1477)
  Directional -> Accuracy: 0.5050, MCC: 0.0556, F1: 0.6526

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63069 | val 2.03205
  Epoch 020 - train 0.37725 | val 3.07082
  Epoch 025 - train 0.27424 | val 3.67970
  Classification -> best τ=0.730 (val F1=0.1181)
  Directional -> Accuracy: 0.5300, MCC: 0.0464, F1: 0.5804

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61256 | val 1.43631
  Epoch 020 - train 0.39733 | val 2.75839
  Epoch 021 - train 0.36283 | val 2.69535
  Classification -> best τ=0.690 (val F1=0.1176)
  Directional -> Accuracy: 0.4150, MCC: -0.1250, F1: 0.1069

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59113 | val 1.62243
  Epoch 020 - train 0.34278 | val 3.85086
  Epoch 021 - train 0.28287 | val 4.40482
  Classification -> best τ=0.830 (val F1=0.1073)
  Directional -> Accuracy: 0.4950, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60278 | val 0.71918
  Epoch 020 - train 0.44286 | val 0.71909
  Epoch 030 - train 0.18469 | val 0.98338
  Classification -> best τ=0.250 (val F1=0.2234)
  Directional -> Accuracy: 0.4600, MCC: -0.1779, F1: 0.6197

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.64065 | val 0.77538
  Epoch 020 - train 0.39577 | val 1.36505
  Epoch 023 - train 0.32851 | val 1.63915
  Classification -> best τ=0.635 (val F1=0.1607)
  Directional -> Accuracy: 0.4050, MCC: -0.0395, F1: 0.0630

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.65317 | val 0.82278
  Epoch 020 - train 0.35656 | val 4.19554
  Epoch 026 - train 0.17458 | val 5.97683
  Classification -> best τ=0.445 (val F1=0.1686)
  Directional -> Accuracy: 0.5100, MCC: 0.0173, F1: 0.3378

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64933 | val 9.14802
  Epoch 020 - train 0.50662 | val 35.55852
  Epoch 021 - train 0.46854 | val 36.40277
  Classification -> best τ=0.220 (val F1=0.1103)
  Directional -> Accuracy: 0.4900, MCC: -0.0549, F1: 0.6047

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65239 | val 1.30651
  Epoch 020 - train 0.42633 | val 3.63870
  Epoch 025 - train 0.33400 | val 4.94960
  Classification -> best τ=0.870 (val F1=0.1005)
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.66168 | val 0.69781
  Epoch 020 - train 0.42266 | val 0.81820
  Epoch 024 - train 0.34471 | val 1.08577
  Classification -> best τ=0.515 (val F1=0.2008)
  Directional -> Accuracy: 0.4850, MCC: 0.0013, F1: 0.2797

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60841 | val 0.88202
  Epoch 020 - train 0.32239 | val 1.42715
  Epoch 023 - train 0.24921 | val 1.50310
  Classification -> best τ=0.660 (val F1=0.1836)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64314 | val 0.97560
  Epoch 020 - train 0.48887 | val 1.32412
  Epoch 030 - train 0.24727 | val 4.01973
  Classification -> best τ=0.445 (val F1=0.1475)
  Directional -> Accuracy: 0.5500, MCC: 0.1330, F1: 0.4643

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56548 | val 2.57863
  Epoch 020 - train 0.29196 | val 2.61753
  Epoch 021 - train 0.25175 | val 2.80513
  Classification -> best τ=0.695 (val F1=0.1632)
  Directional -> Accuracy: 0.5050, MCC: -0.0307, F1: 0.2326

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56418 | val 1.81408
  Epoch 020 - train 0.33025 | val 4.90467
  Epoch 021 - train 0.28744 | val 5.00811
  Classification -> best τ=0.695 (val F1=0.1459)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.64939 | val 0.69993
  Epoch 020 - train 0.60962 | val 0.68822
  Epoch 030 - train 0.37914 | val 0.72550
  Classification -> best τ=0.725 (val F1=0.1635)
  Directional -> Accuracy: 0.5350, MCC: 0.0123, F1: 0.0606

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.56440 | val 3.38152
  Epoch 020 - train 0.23087 | val 8.73347

[I 2026-02-25 21:58:46,350] Trial 3 finished with value: 0.14280424915698534 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.009061504403397036, 'weight_decay': 1.5200010549298982e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.7025881589841729, 'early_stopping_min_delta': 0.0019589695559139543}. Best is trial 3 with value: 0.14280424915698534.

  Epoch 021 - train 0.31509 | val 6.09066
  Classification -> best τ=0.420 (val F1=0.1863)
  Directional -> Accuracy: 0.5450, MCC: 0.0880, F1: 0.5027

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14280424915698534
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.72746 | val 0.70531
  Epoch 011 - train 0.70703 | val 0.70510
  Classification -> best τ=0.520 (val F1=0.1292)
  Directional -> Accuracy: 0.5859, MCC: 0.0000, F1: 0.7389

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.70386 | val 0.68820
  Epoch 011 - train 0.69658 | val 0.68842
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.72284 | val 0.70591
  Epoch 011 - train 0.71678 | val 0.70590
  Classification -> best τ=0.475 (val F1=0.0761)
  Directional -> Accuracy: 0.4728, MCC: -0.0237, F1: 0.4581

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.71781 | val 0.83021
  Epoch 011 - train 0.73291 | val 0.83007
  Classification -> best τ=0.480 (val F1=0.0780)
  Directional -> Accuracy: 0.5859, MCC: 0.1140, F1: 0.7211

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.70779 | val 0.79504
  Epoch 011 - train 0.70591 | val 0.79361
  Classification -> best τ=0.470 (val F1=0.2301)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70621 | val 0.70526
  Epoch 011 - train 0.69729 | val 0.70602
  Classification -> best τ=0.455 (val F1=0.1107)
  Directional -> Accuracy: 0.5606, MCC: 0.0772, F1: 0.7110

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.72311 | val 0.69811
  Epoch 011 - train 0.71885 | val 0.70058
  Classification -> best τ=0.510 (val F1=0.0599)
  Directional -> Accuracy: 0.4444, MCC: -0.0113, F1: 0.0179

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.72676 | val 0.71668
  Epoch 011 - train 0.71651 | val 0.71464
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6111, MCC: 0.0000, F1: 0.7586

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.72999 | val 0.69650
  Epoch 011 - train 0.72167 | val 0.69613
  Classification -> best τ=0.460 (val F1=0.0357)
  Directional -> Accuracy: 0.5268, MCC: 0.0601, F1: 0.5546

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.73547 | val 0.74079
  Epoch 011 - train 0.71624 | val 0.74014
  Classification -> best τ=0.470 (val F1=0.1172)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.6298

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.71121 | val 0.68697
  Epoch 011 - train 0.72326 | val 0.68697
  Classification -> best τ=0.540 (val F1=0.0430)
  Directional -> Accuracy: 0.4747, MCC: 0.0045, F1: 0.2571

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.69042 | val 0.70782
  Epoch 011 - train 0.68878 | val 0.70717
  Classification -> best τ=0.535 (val F1=0.0452)
  Directional -> Accuracy: 0.4242, MCC: -0.0514, F1: 0.1493

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70944 | val 0.82412
  Epoch 011 - train 0.71865 | val 0.82059
  Classification -> best τ=0.490 (val F1=0.0746)
  Directional -> Accuracy: 0.4848, MCC: 0.0789, F1: 0.2714

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70536 | val 0.75553
  Epoch 011 - train 0.70764 | val 0.75918
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.6622

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.71014 | val 0.73182
  Epoch 011 - train 0.70151 | val 0.73295
  Classification -> best τ=0.485 (val F1=0.0254)
  Directional -> Accuracy: 0.4495, MCC: -0.0813, F1: 0.2781

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.71189 | val 0.69722
  Epoch 011 - train 0.71605 | val 0.69713
  Classification -> best τ=0.530 (val F1=0.0805)
  Directional -> Accuracy: 0.4747, MCC: -0.0547, F1: 0.5593

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.71937 | val 0.70472
  Epoch 011 - train 0.70664 | val 0.70399
  Classification -> best τ=0.495 (val F1=0.0072)
  Directional -> Accuracy: 0.4798, MCC: -0.0782, F1: 0.5690

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.71650 | val 0.72023
  Epoch 011 - train 0.70047 | val 0.72265
  Classification -> best τ=0.525 (val F1=0.0820)
  Directional -> Accuracy: 0.4545, MCC: -0.1358, F1: 0.5846

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69381 | val 0.74142
  Epoch 011 - train 0.69694 | val 0.73966
  Classification -> best τ=0.485 (val F1=0.0684)
  Directional -> Accuracy: 0.5101, MCC: 0.0179, F1: 0.5801

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70923 | val 0.69579
  Epoch 011 - train 0.70420 | val 0.69588
  Classification -> best τ=0.500 (val F1=0.0270)
  Directional -> Accuracy: 0.4949, MCC: 0.0247, F1: 0.3976

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.71049 | val 0.70806
  Epoch 011 - train 0.71548 | val 0.70686
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.6576

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.72084 | val 0.76034
  Epoch 011 - train 0.71278 | val 0.76285
  Classification -> best τ=0.445 (val F1=0.1122)
  Directional -> Accuracy: 0.4646, MCC: 0.0351, F1: 0.2090

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.71089 | val 0.71394
  Epoch 011 - train 0.71442 | val 0.71474
  Classification -> best τ=0.455 (val F1=0.0099)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.7016

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.70416 | val 0.69287
  Epoch 013 - train 0.69439 | val 0.69387
  Classification -> best τ=0.460 (val F1=0.2234)
  Directional -> Accuracy: 0.4141, MCC: 0.0315, F1: 0.5606

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68606 | val 0.71998
  Epoch 011 - train 0.69908 | val 0.72127
  Classification -> best τ=0.490 (val F1=0.1343)
  Directional -> Accuracy: 0.5354, MCC: 0.0554, F1: 0.6198

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.72880 | val 0.69471
  Epoch 011 - train 0.70547 | val 0.69464
  Classification -> best τ=0.455 (val F1=0.1041)
  Directional -> Accuracy: 0.4848, MCC: -0.0355, F1: 0.6483

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69340 | val 0.69558
  Epoch 011 - train 0.70445 | val 0.69619
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.70390 | val 0.78133
  Epoch 011 - train 0.71558 | val 0.78186
  Classification -> best τ=0.500 (val F1=0.1224)
  Directional -> Accuracy: 0.5202, MCC: 0.0415, F1: 0.5701

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70856 | val 0.69300
  Epoch 011 - train 0.70435 | val 0.69269
  Classification -> best τ=0.460 (val F1=0.0646)
  Directional -> Accuracy: 0.5202, MCC: 0.0747, F1: 0.6780

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.71095 | val 0.71716
  Epoch 011 - train 0.68651 | val 0.71962
  Classification -> best τ=0.470 (val F1=0.1826)
  Directional -> Accuracy: 0.5505, MCC: 0.0679, F1: 0.6454

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.71527 | val 0.78564
  Epoch 011 - train 0.71985 | val 0.78617
  Classification -> best τ=0.440 (val F1=0.1326)
  Directional -> Accuracy: 0.5101, MCC: 0.0000, F1: 0.6756

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.71872 | val 0.69735
  Epoch 012 - train 0.72651 | val 0.69905
  Classification -> best τ=0.425 (val F1=0.0797)
  Directional -> Accuracy: 0.5505, MCC: 0.0000, F1: 0.7101

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.72524 | val 0.71479
  Epoch 011 - train 0.71575 | val 0.71453
  Classification -> best τ=0.510 (val F1=0.0976)
  Directional -> Accuracy: 0.3990, MCC: 0.0806, F1: 0.0325

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.72574 | val 0.82670
  Epoch 011 - train 0.71796 | val 0.83191
  Classification -> best τ=0.450 (val F1=0.1299)
  Directional -> Accuracy: 0.5101, MCC: 0.0068, F1: 0.4457

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.72668 | val 0.68973
  Epoch 019 - train 0.72717 | val 0.69163
  Classification -> best τ=0.470 (val F1=0.1739)
  Directional -> Accuracy: 0.6000, MCC: 0.2020, F1: 0.6087

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69422 | val 0.71095
  Epoch 011 - train 0.68731 | val 0.70902
  Classification -> best τ=0.505 (val F1=0.0521)
  Directional -> Accuracy: 0.5556, MCC: 0.0539, F1: 0.6508

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.71562 | val 0.71196
  Epoch 011 - train 0.71388 | val 0.71212
  Classification -> best τ=0.510 (val F1=0.0160)
  Directional -> Accuracy: 0.5152, MCC: -0.0400, F1: 0.6667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.70150 | val 0.84019
  Epoch 011 - train 0.69931 | val 0.84506
  Classification -> best τ=0.530 (val F1=0.0929)
  Directional -> Accuracy: 0.4293, MCC: -0.0766, F1: 0.2416

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.70912 | val 0.70504
  Epoch 011 - train 0.70214 | val 0.70758
  Classification -> best τ=0.490 (val F1=0.0134)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.71480 | val 0.76522
  Epoch 011 - train 0.72465 | val 0.75676
  Classification -> best τ=0.445 (val F1=0.0899)
  Directional -> Accuracy: 0.5253, MCC: 0.0000, F1: 0.6887

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.70808 | val 0.70253
  Epoch 011 - train 0.71731 | val 0.70213
  Classification -> best τ=0.520 (val F1=0.0235)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71483 | val 0.69718
  Epoch 011 - train 0.70861 | val 0.69926
  Classification -> best τ=0.535 (val F1=0.0901)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71086 | val 0.70017
  Epoch 011 - train 0.70510 | val 0.70085
  Classification -> best τ=0.460 (val F1=0.1266)
  Directional -> Accuracy: 0.5101, MCC: 0.0000, F1: 0.6756

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.71866 | val 0.72814
  Epoch 011 - train 0.72380 | val 0.72716
  Classification -> best τ=0.470 (val F1=0.0744)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.71110 | val 0.80673
  Epoch 011 - train 0.69710 | val 0.80907
  Classification -> best τ=0.470 (val F1=0.0858)
  Directional -> Accuracy: 0.4798, MCC: -0.0464, F1: 0.5164

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69603 | val 0.75880
  Epoch 011 - train 0.70786 | val 0.75923
  Classification -> best τ=0.435 (val F1=0.0773)
  Directional -> Accuracy: 0.5758, MCC: -0.0336, F1: 0.7255

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70030 | val 0.69109
  Epoch 011 - train 0.70517 | val 0.69176
  Classification -> best τ=0.515 (val F1=0.1217)
  Directional -> Accuracy: 0.4343, MCC: -0.0805, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69712 | val 0.71998
  Epoch 011 - train 0.70533 | val 0.72332
  Classification -> best τ=0.465 (val F1=0.0645)
  Directional -> Accuracy: 0.5152, MCC: -0.0733, F1: 0.6364

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70552 | val 0.70188
  Epoch 011 - train 0.70545 | val 0.70162
  Classification -> best τ=0.485 (val F1=0.1205)
  Directional -> Accuracy: 0.4848, MCC: -0.0084, F1: 0.6357

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69902 | val 0.70684
  Epoch 011 - train 0.70543 | val 0.70768
  Classification -> best τ=0.470 (val F1=0.0490)
  Directional -> Accuracy: 0.5758, MCC: 0.1022, F1: 0.6744

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71607 | val 0.69140
  Epoch 011 - train 0.71016 | val 0.69103
  Classification -> best τ=0.545 (val F1=0.1129)
  Directional -> Accuracy: 0.5606, MCC: 0.0555, F1: 0.7148

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69680 | val 0.69545
  Epoch 011 - train 0.69865 | val 0.69665
  Classification -> best τ=0.515 (val F1=0.0475)
  Directional -> Accuracy: 0.5253, MCC: 0.0496, F1: 0.5804

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70285 | val 0.71330
  Epoch 011 - train 0.70386 | val 0.71475
  Classification -> best τ=0.440 (val F1=0.0773)
  Directional -> Accuracy: 0.5101, MCC: 0.0000, F1: 0.6756

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.72985 | val 0.72254
  Epoch 011 - train 0.71515 | val 0.72313
  Classification -> best τ=0.465 (val F1=0.0834)
  Directional -> Accuracy: 0.4646, MCC: -0.0701, F1: 0.5093

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.72770 | val 0.68709
  Epoch 014 - train 0.71731 | val 0.68658
  Classification -> best τ=0.580 (val F1=0.1891)
  Directional -> Accuracy: 0.5051, MCC: 0.0000, F1: 0.0000

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.71125 | val 0.70376
  Epoch 011 - train 0.71692 | val 0.70387
  Classification -> best τ=0.480 (val F1=0.0810)
  Directional -> Accuracy: 0.4596, MCC: -0.1114, F1: 0.5668

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70045 | val 0.70893
  Epoch 011 - train 0.70299 | val 0.70772
  Classification -> best τ=0.535 (val F1=0.0482)
  Directional -> Accuracy: 0.4444, MCC: -0.0787, F1: 0.3210

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.71863 | val 0.77174
  Epoch 011 - train 0.71033 | val 0.76527
  Classification -> best τ=0.495 (val F1=0.0780)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.6931

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.70513 | val 0.78140
  Epoch 011 - train 0.70521 | val 0.78406
  Classification -> best τ=0.485 (val F1=0.0369)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69177 | val 0.69507
  Epoch 011 - train 0.69729 | val 0.69567
  Classification -> best τ=0.525 (val F1=0.1015)
  Directional -> Accuracy: 0.4697, MCC: 0.0049, F1: 0.1026

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70666 | val 0.72711
  Epoch 011 - train 0.70391 | val 0.72935
  Classification -> best τ=0.485 (val F1=0.1145)
  Directional -> Accuracy: 0.4798, MCC: -0.0157, F1: 0.6142

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.72114 | val 0.70955
  Epoch 011 - train 0.70559 | val 0.70912
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5152, MCC: 0.0000, F1: 0.6800

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.72638 | val 0.70617
  Epoch 011 - train 0.69751 | val 0.70668
  Classification -> best τ=0.470 (val F1=0.1089)
  Directional -> Accuracy: 0.4495, MCC: -0.0836, F1: 0.5322

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.70259 | val 0.72909
  Epoch 011 - train 0.69760 | val 0.73353
  Classification -> best τ=0.475 (val F1=0.0720)
  Directional -> Accuracy: 0.5606, MCC: 0.0287, F1: 0.6926

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.71402 | val 0.69519
  Epoch 011 - train 0.71097 | val 0.69541
  Classification -> best τ=0.505 (val F1=0.1419)
  Directional -> Accuracy: 0.5101, MCC: -0.0078, F1: 0.5801

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.70756 | val 0.69142
  Epoch 017 - train 0.70043 | val 0.69775
  Classification -> best τ=0.485 (val F1=0.1266)
  Directional -> Accuracy: 0.4845, MCC: 0.0509, F1: 0.5575

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.70998 | val 0.71220
  Epoch 011 - train 0.70680 | val 0.71097
  Classification -> best τ=0.490 (val F1=0.0684)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.70791 | val 0.71053
  Epoch 011 - train 0.71374 | val 0.71140
  Classification -> best τ=0.535 (val F1=0.0654)
  Directional -> Accuracy: 0.5052, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69221 | val 0.75199
  Epoch 011 - train 0.70946 | val 0.75246
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.6105

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.69386 | val 0.69710
  Epoch 011 - train 0.71391 | val 0.69695
  Classification -> best τ=0.520 (val F1=0.1010)
  Directional -> Accuracy: 0.5052, MCC: 0.0000, F1: 0.0000

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.71131 | val 0.80574
  Epoch 011 - train 0.70767 | val 0.80959
  Classification -> best τ=0.535 (val F1=0.0997)
  Directional -> Accuracy: 0.5404, MCC: 0.0705, F1: 0.6255

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.72422 | val 0.94516
  Epoch 011 - train 0.72998 | val 0.94828
  Classification -> best τ=0.440 (val F1=0.0822)
  Directional -> Accuracy: 0.5152, MCC: 0.0000, F1: 0.6800

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.71094 | val 0.78115
  Epoch 011 - train 0.71247 | val 0.78333
  Classification -> best τ=0.485 (val F1=0.0904)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.70036 | val 0.75754
  Epoch 011 - train 0.71111 | val 0.75809
  Classification -> best τ=0.475 (val F1=0.0025)
  Directional -> Accuracy: 0.5152, MCC: 0.0278, F1: 0.5385

[75/88] Processing T...


[I 2026-02-25 22:05:28,265] Trial 4 finished with value: 0.08154656382347364 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 1.1582864851526195e-05, 'weight_decay': 5.590675476253039e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.4234822459464327, 'early_stopping_min_delta': 0.0051971737651878725}. Best is trial 3 with value: 0.14280424915698534.

  Epoch 011 - train 0.69833 | val 0.69611
  Classification -> best τ=0.525 (val F1=0.0944)
  Directional -> Accuracy: 0.5051, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.08154656382347364
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69452 | val 0.72774
  Epoch 016 - train 0.69363 | val 0.72874
  Classification -> best τ=0.510 (val F1=0.0227)
  Directional -> Accuracy: 0.4623, MCC: 0.0375, F1: 0.3007

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.69409 | val 0.73243
  Epoch 016 - train 0.69287 | val 0.73233
  Classification -> best τ=0.430 (val F1=0.1228)
  Directional -> Accuracy: 0.4774, MCC: -0.0531, F1: 0.5738

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68500 | val 0.72547
  Epoch 016 - train 0.68414 | val 0.72307
  Classification -> best τ=0.540 (val F1=0.1202)
  Directional -> Accuracy: 0.5269, MCC: -0.0241, F1: 0.6423

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.68656 | val 0.80444
  Epoch 016 - train 0.68570 | val 0.79368
  Classification -> best τ=0.760 (val F1=0.1266)
  Directional -> Accuracy: 0.4422, MCC: -0.0206, F1: 0.1395

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.69448 | val 0.71448
  Epoch 016 - train 0.69375 | val 0.71328
  Classification -> best τ=0.650 (val F1=0.1965)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69253 | val 0.71354
  Epoch 016 - train 0.69081 | val 0.71420
  Classification -> best τ=0.395 (val F1=0.1087)
  Directional -> Accuracy: 0.5528, MCC: 0.0000, F1: 0.7120

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69533 | val 0.71859
  Epoch 016 - train 0.69379 | val 0.71499
  Classification -> best τ=0.625 (val F1=0.0606)
  Directional -> Accuracy: 0.5578, MCC: 0.0000, F1: 0.7161

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70698 | val 0.71621
  Epoch 016 - train 0.70483 | val 0.71358
  Classification -> best τ=0.700 (val F1=0.1054)
  Directional -> Accuracy: 0.3769, MCC: -0.1428, F1: 0.2051

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69684 | val 0.70891
  Epoch 016 - train 0.69566 | val 0.70842
  Classification -> best τ=0.505 (val F1=0.0919)
  Directional -> Accuracy: 0.5088, MCC: -0.0377, F1: 0.6056

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69615 | val 0.73314
  Epoch 016 - train 0.69408 | val 0.73151
  Classification -> best τ=0.515 (val F1=0.0974)
  Directional -> Accuracy: 0.5226, MCC: -0.0563, F1: 0.0594

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.71522 | val 0.69476
  Epoch 016 - train 0.71386 | val 0.69441
  Classification -> best τ=0.455 (val F1=0.1731)
  Directional -> Accuracy: 0.5427, MCC: 0.0000, F1: 0.7036

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.71453 | val 0.73946
  Epoch 016 - train 0.71196 | val 0.73889
  Classification -> best τ=0.495 (val F1=0.0504)
  Directional -> Accuracy: 0.4221, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70589 | val 0.75557
  Epoch 016 - train 0.70405 | val 0.75229
  Classification -> best τ=0.290 (val F1=0.0586)
  Directional -> Accuracy: 0.5628, MCC: 0.0000, F1: 0.7203

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69301 | val 0.68252
  Epoch 016 - train 0.69163 | val 0.68091
  Classification -> best τ=0.390 (val F1=0.2181)
  Directional -> Accuracy: 0.4824, MCC: -0.0460, F1: 0.6199

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.69229 | val 0.70930
  Epoch 016 - train 0.69121 | val 0.70936
  Classification -> best τ=0.610 (val F1=0.0700)
  Directional -> Accuracy: 0.4673, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.69283 | val 0.88968
  Epoch 016 - train 0.69113 | val 0.89505
  Classification -> best τ=0.380 (val F1=0.1280)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.69099 | val 0.69839
  Epoch 016 - train 0.69004 | val 0.69849
  Classification -> best τ=0.575 (val F1=0.2044)
  Directional -> Accuracy: 0.4121, MCC: -0.1378, F1: 0.1203

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67764 | val 0.82183
  Epoch 016 - train 0.67653 | val 0.83113
  Classification -> best τ=0.530 (val F1=0.1366)
  Directional -> Accuracy: 0.4824, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69685 | val 0.68758
  Epoch 020 - train 0.69429 | val 0.68232
  Epoch 030 - train 0.69192 | val 0.67835
  Classification -> best τ=0.625 (val F1=0.2336)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68859 | val 0.69687
  Epoch 016 - train 0.68706 | val 0.69803
  Classification -> best τ=0.440 (val F1=0.1899)
  Directional -> Accuracy: 0.5126, MCC: -0.0136, F1: 0.6135

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.70089 | val 0.80264
  Epoch 016 - train 0.69923 | val 0.80049
  Classification -> best τ=0.675 (val F1=0.1193)
  Directional -> Accuracy: 0.4975, MCC: 0.0122, F1: 0.6403

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.70013 | val 0.70889
  Epoch 016 - train 0.69884 | val 0.70709
  Classification -> best τ=0.375 (val F1=0.0751)
  Directional -> Accuracy: 0.5628, MCC: 0.0000, F1: 0.7203

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70462 | val 0.72322
  Epoch 016 - train 0.70246 | val 0.72231
  Classification -> best τ=0.345 (val F1=0.1321)
  Directional -> Accuracy: 0.5427, MCC: 0.0000, F1: 0.7036

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.68823 | val 0.76770
  Epoch 016 - train 0.68622 | val 0.76979
  Classification -> best τ=0.435 (val F1=0.1878)
  Directional -> Accuracy: 0.4925, MCC: -0.0210, F1: 0.4229

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69189 | val 0.74665
  Epoch 016 - train 0.69085 | val 0.74943
  Classification -> best τ=0.460 (val F1=0.1040)
  Directional -> Accuracy: 0.4774, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70280 | val 0.71062
  Epoch 016 - train 0.70128 | val 0.70768
  Classification -> best τ=0.370 (val F1=0.1281)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.6554

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69067 | val 0.68994
  Epoch 016 - train 0.68879 | val 0.68966
  Classification -> best τ=0.440 (val F1=0.1514)
  Directional -> Accuracy: 0.5678, MCC: 0.1533, F1: 0.7133

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.70072 | val 0.69900
  Epoch 016 - train 0.69950 | val 0.69940
  Classification -> best τ=0.490 (val F1=0.2263)
  Directional -> Accuracy: 0.5025, MCC: 0.0000, F1: 0.0000

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69072 | val 0.69974
  Epoch 016 - train 0.68981 | val 0.69954
  Classification -> best τ=0.430 (val F1=0.0815)
  Directional -> Accuracy: 0.5126, MCC: 0.0000, F1: 0.6777

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.68633 | val 0.68660
  Epoch 016 - train 0.68569 | val 0.68898
  Classification -> best τ=0.500 (val F1=0.1835)
  Directional -> Accuracy: 0.5075, MCC: 0.0666, F1: 0.3797

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.70714 | val 0.71023
  Epoch 016 - train 0.70532 | val 0.70821
  Classification -> best τ=0.775 (val F1=0.0652)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68881 | val 0.91148
  Epoch 016 - train 0.68733 | val 0.90385
  Classification -> best τ=0.805 (val F1=0.0678)
  Directional -> Accuracy: 0.5377, MCC: 0.0317, F1: 0.6378

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.69394 | val 0.70187
  Epoch 016 - train 0.69260 | val 0.70072
  Classification -> best τ=0.600 (val F1=0.1519)
  Directional -> Accuracy: 0.4774, MCC: 0.0131, F1: 0.4639

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69037 | val 0.78057
  Epoch 016 - train 0.68955 | val 0.78044
  Classification -> best τ=0.390 (val F1=0.1003)
  Directional -> Accuracy: 0.4472, MCC: 0.0000, F1: 0.6181

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.69967 | val 0.80007
  Epoch 016 - train 0.69886 | val 0.80130
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70301 | val 0.70805
  Epoch 020 - train 0.69664 | val 0.70317
  Epoch 030 - train 0.69112 | val 0.70000
  Classification -> best τ=0.460 (val F1=0.0660)
  Directional -> Accuracy: 0.4774, MCC: 0.0228, F1: 0.4091

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68036 | val 0.69491
  Epoch 018 - train 0.67851 | val 0.69398
  Classification -> best τ=0.510 (val F1=0.1826)
  Directional -> Accuracy: 0.5628, MCC: 0.1076, F1: 0.6588

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.70167 | val 0.71868
  Epoch 016 - train 0.69976 | val 0.72052
  Classification -> best τ=0.390 (val F1=0.1259)
  Directional -> Accuracy: 0.5628, MCC: -0.0620, F1: 0.7203

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.69426 | val 0.68062
  Epoch 016 - train 0.69205 | val 0.68016
  Classification -> best τ=0.595 (val F1=0.1460)
  Directional -> Accuracy: 0.4774, MCC: -0.0801, F1: 0.5702

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.69719 | val 0.70981
  Epoch 016 - train 0.69581 | val 0.70845
  Classification -> best τ=0.500 (val F1=0.0729)
  Directional -> Accuracy: 0.4422, MCC: -0.1274, F1: 0.0826

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.70633 | val 0.80009
  Epoch 016 - train 0.70439 | val 0.80570
  Classification -> best τ=0.570 (val F1=0.0733)
  Directional -> Accuracy: 0.5427, MCC: 0.0858, F1: 0.6667

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.72467 | val 0.78744
  Epoch 016 - train 0.72102 | val 0.78530
  Classification -> best τ=0.465 (val F1=0.0933)
  Directional -> Accuracy: 0.5327, MCC: 0.0643, F1: 0.5550

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69742 | val 0.71983
  Epoch 016 - train 0.69574 | val 0.71465
  Classification -> best τ=0.595 (val F1=0.0967)
  Directional -> Accuracy: 0.5628, MCC: 0.1263, F1: 0.5628

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70596 | val 0.75976
  Epoch 016 - train 0.70419 | val 0.75536
  Classification -> best τ=0.390 (val F1=0.1166)
  Directional -> Accuracy: 0.4824, MCC: -0.0864, F1: 0.6171

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69525 | val 0.69646
  Epoch 020 - train 0.69272 | val 0.69505
  Epoch 025 - train 0.69152 | val 0.69477
  Classification -> best τ=0.505 (val F1=0.1044)
  Directional -> Accuracy: 0.4623, MCC: -0.0760, F1: 0.4831

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71494 | val 0.70323
  Epoch 016 - train 0.71134 | val 0.70438
  Classification -> best τ=0.490 (val F1=0.1631)
  Directional -> Accuracy: 0.5427, MCC: 0.0441, F1: 0.6224

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69735 | val 0.69013
  Epoch 020 - train 0.69530 | val 0.68770
  Epoch 030 - train 0.69339 | val 0.68597
  Classification -> best τ=0.525 (val F1=0.1703)
  Directional -> Accuracy: 0.5628, MCC: 0.1437, F1: 0.5628

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67831 | val 1.00566
  Epoch 016 - train 0.67734 | val 1.02159
  Classification -> best τ=0.190 (val F1=0.1305)
  Directional -> Accuracy: 0.5126, MCC: 0.0525, F1: 0.5314

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.70733 | val 0.83980
  Epoch 016 - train 0.70564 | val 0.83966
  Classification -> best τ=0.305 (val F1=0.1093)
  Directional -> Accuracy: 0.4472, MCC: -0.1092, F1: 0.5600

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70726 | val 0.72741
  Epoch 016 - train 0.70568 | val 0.72507
  Classification -> best τ=0.640 (val F1=0.1186)
  Directional -> Accuracy: 0.4925, MCC: -0.1240, F1: 0.6300

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69502 | val 0.70810
  Epoch 016 - train 0.69409 | val 0.70823
  Classification -> best τ=0.430 (val F1=0.0060)
  Directional -> Accuracy: 0.5578, MCC: 0.0117, F1: 0.7143

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.71438 | val 0.91144
  Epoch 016 - train 0.71155 | val 0.89633
  Classification -> best τ=0.865 (val F1=0.0700)
  Directional -> Accuracy: 0.4874, MCC: -0.0721, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69541 | val 0.84630
  Epoch 016 - train 0.69348 | val 0.84919
  Classification -> best τ=0.285 (val F1=0.0873)
  Directional -> Accuracy: 0.4874, MCC: -0.0069, F1: 0.1207

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.68522 | val 0.76214
  Epoch 016 - train 0.68377 | val 0.76666
  Classification -> best τ=0.395 (val F1=0.1139)
  Directional -> Accuracy: 0.4372, MCC: -0.0433, F1: 0.3563

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.69645 | val 0.68899
  Epoch 016 - train 0.69480 | val 0.68888
  Classification -> best τ=0.345 (val F1=0.1202)
  Directional -> Accuracy: 0.4372, MCC: -0.1655, F1: 0.1765

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.69506 | val 0.71331
  Epoch 016 - train 0.69311 | val 0.70942
  Classification -> best τ=0.460 (val F1=0.1247)
  Directional -> Accuracy: 0.5477, MCC: 0.0842, F1: 0.6371

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70973 | val 0.70208
  Epoch 016 - train 0.70750 | val 0.70207
  Classification -> best τ=0.520 (val F1=0.1255)
  Directional -> Accuracy: 0.4724, MCC: -0.0284, F1: 0.4134

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.68607 | val 0.70683
  Epoch 016 - train 0.68489 | val 0.70839
  Classification -> best τ=0.435 (val F1=0.0895)
  Directional -> Accuracy: 0.5226, MCC: -0.0122, F1: 0.6780

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.71446 | val 0.70472
  Epoch 016 - train 0.71106 | val 0.70416
  Classification -> best τ=0.405 (val F1=0.1644)
  Directional -> Accuracy: 0.5628, MCC: 0.0536, F1: 0.6692

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.74154 | val 0.75546
  Epoch 016 - train 0.73650 | val 0.75389
  Classification -> best τ=0.585 (val F1=0.0585)
  Directional -> Accuracy: 0.4925, MCC: 0.0512, F1: 0.2290

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69397 | val 0.68581
  Epoch 016 - train 0.69210 | val 0.68728
  Classification -> best τ=0.490 (val F1=0.2242)
  Directional -> Accuracy: 0.5075, MCC: 0.0909, F1: 0.6449

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69584 | val 0.74209
  Epoch 016 - train 0.69491 | val 0.74432
  Classification -> best τ=0.400 (val F1=0.1651)
  Directional -> Accuracy: 0.5377, MCC: 0.1344, F1: 0.2923

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.70161 | val 0.70844
  Epoch 016 - train 0.69989 | val 0.70839
  Classification -> best τ=0.620 (val F1=0.1073)
  Directional -> Accuracy: 0.4824, MCC: -0.0272, F1: 0.4976

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.72402 | val 1.43659
  Epoch 016 - train 0.72133 | val 1.44967
  Classification -> best τ=0.235 (val F1=0.1431)
  Directional -> Accuracy: 0.4271, MCC: 0.0000, F1: 0.0000

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.70020 | val 0.81495
  Epoch 016 - train 0.69808 | val 0.80101
  Classification -> best τ=0.780 (val F1=0.0840)
  Directional -> Accuracy: 0.4221, MCC: -0.0987, F1: 0.3275

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.69188 | val 0.94926
  Epoch 016 - train 0.69042 | val 0.93602
  Classification -> best τ=0.320 (val F1=0.0738)
  Directional -> Accuracy: 0.4490, MCC: -0.0776, F1: 0.4545

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.70052 | val 0.70075
  Epoch 016 - train 0.69899 | val 0.70052
  Classification -> best τ=0.530 (val F1=0.0950)
  Directional -> Accuracy: 0.4472, MCC: -0.0832, F1: 0.2568

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.69893 | val 0.69007
  Epoch 016 - train 0.69575 | val 0.69153
  Classification -> best τ=0.480 (val F1=0.1679)
  Directional -> Accuracy: 0.5153, MCC: 0.0400, F1: 0.2857

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69224 | val 0.69542
  Epoch 016 - train 0.69141 | val 0.69438
  Classification -> best τ=0.485 (val F1=0.1260)
  Directional -> Accuracy: 0.5075, MCC: 0.0222, F1: 0.4896

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.69600 | val 0.78029
  Epoch 016 - train 0.69399 | val 0.77934
  Classification -> best τ=0.580 (val F1=0.0597)
  Directional -> Accuracy: 0.5000, MCC: -0.0069, F1: 0.3000

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.68957 | val 0.69370
  Epoch 017 - train 0.68856 | val 0.69403
  Classification -> best τ=0.375 (val F1=0.0666)
  Directional -> Accuracy: 0.5176, MCC: 0.0000, F1: 0.6821

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69331 | val 1.09739
  Epoch 016 - train 0.69188 | val 1.10633
  Classification -> best τ=0.200 (val F1=0.0802)
  Directional -> Accuracy: 0.5427, MCC: 0.1050, F1: 0.6738

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.69715 | val 0.82977
  Epoch 016 - train 0.69621 | val 0.81637
  Classification -> best τ=0.380 (val F1=0.1082)
  Directional -> Accuracy: 0.5477, MCC: 0.0000, F1: 0.0000

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.70202 | val 0.78004

[I 2026-02-25 22:08:16,121] Trial 5 finished with value: 0.11945031487727921 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 2.2643497072876643e-06, 'weight_decay': 5.4069852827625455e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.8432525141586316, 'early_stopping_min_delta': 0.0021671238692653606}. Best is trial 3 with value: 0.14280424915698534.

  Epoch 016 - train 0.69247 | val 0.75869
  Classification -> best τ=0.375 (val F1=0.0783)
  Directional -> Accuracy: 0.5226, MCC: 0.0534, F1: 0.5887

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.11945031487727921
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69800 | val 0.68452
  Epoch 016 - train 0.68887 | val 0.68938
  Classification -> best τ=0.510 (val F1=0.1864)
  Directional -> Accuracy: 0.5606, MCC: -0.0470, F1: 0.7090

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.69987 | val 0.83084
  Epoch 011 - train 0.69143 | val 0.83881
  Classification -> best τ=0.455 (val F1=0.1479)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69085 | val 0.69323
  Epoch 011 - train 0.68452 | val 0.69323
  Classification -> best τ=0.480 (val F1=0.0828)
  Directional -> Accuracy: 0.5707, MCC: 0.0450, F1: 0.7019

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.71208 | val 0.92286
  Epoch 011 - train 0.71134 | val 0.92367
  Classification -> best τ=0.480 (val F1=0.0932)
  Directional -> Accuracy: 0.4343, MCC: 0.0000, F1: 0.0000

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.72701 | val 0.69392
  Epoch 011 - train 0.72903 | val 0.69310
  Classification -> best τ=0.530 (val F1=0.1765)
  Directional -> Accuracy: 0.5048, MCC: 0.0051, F1: 0.5357

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67982 | val 0.68750
  Epoch 011 - train 0.67880 | val 0.68754
  Classification -> best τ=0.435 (val F1=0.1359)
  Directional -> Accuracy: 0.5556, MCC: 0.0788, F1: 0.7124

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69892 | val 0.78606
  Epoch 011 - train 0.70337 | val 0.79223
  Classification -> best τ=0.420 (val F1=0.1242)
  Directional -> Accuracy: 0.5657, MCC: 0.0710, F1: 0.7095

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70755 | val 0.69525
  Epoch 020 - train 0.69313 | val 0.68383
  Classification -> best τ=0.360 (val F1=0.2753)
  Directional -> Accuracy: 0.6111, MCC: 0.0468, F1: 0.7524

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70551 | val 0.69063
  Epoch 011 - train 0.69096 | val 0.68976
  Classification -> best τ=0.510 (val F1=0.1423)
  Directional -> Accuracy: 0.5268, MCC: -0.0561, F1: 0.6581

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69588 | val 0.71720
  Epoch 011 - train 0.69628 | val 0.71948
  Classification -> best τ=0.470 (val F1=0.0709)
  Directional -> Accuracy: 0.5354, MCC: 0.0348, F1: 0.3429

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.71529 | val 0.73403
  Epoch 011 - train 0.70965 | val 0.73235
  Classification -> best τ=0.705 (val F1=0.0649)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.69944 | val 0.73823
  Epoch 011 - train 0.68212 | val 0.73657
  Classification -> best τ=0.510 (val F1=0.1888)
  Directional -> Accuracy: 0.4444, MCC: 0.0374, F1: 0.1406

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69807 | val 0.70759
  Epoch 011 - train 0.69779 | val 0.70710
  Classification -> best τ=0.550 (val F1=0.0240)
  Directional -> Accuracy: 0.4596, MCC: 0.0385, F1: 0.1575

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.72069 | val 0.71472
  Epoch 011 - train 0.70062 | val 0.71516
  Classification -> best τ=0.595 (val F1=0.0801)
  Directional -> Accuracy: 0.5303, MCC: 0.0650, F1: 0.3586

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.70256 | val 0.78514
  Epoch 011 - train 0.70713 | val 0.78651
  Classification -> best τ=0.440 (val F1=0.0966)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.69568 | val 0.70057
  Epoch 011 - train 0.69837 | val 0.70004
  Classification -> best τ=0.580 (val F1=0.0650)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.70389 | val 0.69789
  Epoch 011 - train 0.70067 | val 0.69742
  Classification -> best τ=0.515 (val F1=0.0948)
  Directional -> Accuracy: 0.5505, MCC: 0.0466, F1: 0.6642

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69255 | val 0.84285
  Epoch 011 - train 0.69134 | val 0.85135
  Classification -> best τ=0.550 (val F1=0.0695)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68717 | val 0.67675
  Epoch 014 - train 0.69621 | val 0.67746
  Classification -> best τ=0.515 (val F1=0.1879)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69755 | val 0.69524
  Epoch 011 - train 0.69511 | val 0.69578
  Classification -> best τ=0.460 (val F1=0.0778)
  Directional -> Accuracy: 0.5303, MCC: 0.0060, F1: 0.6618

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.70295 | val 0.71824
  Epoch 011 - train 0.68708 | val 0.71771
  Classification -> best τ=0.510 (val F1=0.1132)
  Directional -> Accuracy: 0.4697, MCC: -0.0649, F1: 0.6038

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.70122 | val 0.70206
  Epoch 011 - train 0.69462 | val 0.70321
  Classification -> best τ=0.585 (val F1=0.1338)
  Directional -> Accuracy: 0.4343, MCC: -0.0529, F1: 0.0968

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68880 | val 0.69568
  Epoch 011 - train 0.69287 | val 0.69642
  Classification -> best τ=0.445 (val F1=0.1084)
  Directional -> Accuracy: 0.5051, MCC: -0.0116, F1: 0.5776

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.69794 | val 0.82034
  Epoch 011 - train 0.69603 | val 0.82366
  Classification -> best τ=0.225 (val F1=0.0805)
  Directional -> Accuracy: 0.4141, MCC: 0.0315, F1: 0.5606

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71804 | val 0.70565
  Epoch 011 - train 0.73102 | val 0.70478
  Classification -> best τ=0.555 (val F1=0.0190)
  Directional -> Accuracy: 0.5253, MCC: 0.0000, F1: 0.6887

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69732 | val 0.71009
  Epoch 011 - train 0.70039 | val 0.70843
  Classification -> best τ=0.600 (val F1=0.0904)
  Directional -> Accuracy: 0.5000, MCC: -0.0115, F1: 0.3265

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69543 | val 0.74249
  Epoch 011 - train 0.68736 | val 0.74328
  Classification -> best τ=0.495 (val F1=0.1279)
  Directional -> Accuracy: 0.5101, MCC: 0.1089, F1: 0.3121

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.70284 | val 0.70958
  Epoch 011 - train 0.70218 | val 0.71049
  Classification -> best τ=0.430 (val F1=0.0773)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71191 | val 0.68785
  Epoch 018 - train 0.69786 | val 0.68694
  Classification -> best τ=0.455 (val F1=0.1647)
  Directional -> Accuracy: 0.5202, MCC: 0.0621, F1: 0.3448

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.69655 | val 0.69516
  Epoch 020 - train 0.69615 | val 0.68736
  Classification -> best τ=0.590 (val F1=0.1623)
  Directional -> Accuracy: 0.4495, MCC: -0.0533, F1: 0.2158

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.70649 | val 0.70487
  Epoch 011 - train 0.70436 | val 0.70515
  Classification -> best τ=0.465 (val F1=0.0444)
  Directional -> Accuracy: 0.5051, MCC: -0.0289, F1: 0.6667

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69126 | val 0.69274
  Epoch 011 - train 0.68954 | val 0.69318
  Classification -> best τ=0.595 (val F1=0.1290)
  Directional -> Accuracy: 0.4242, MCC: -0.1136, F1: 0.2083

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.70217 | val 0.70635
  Epoch 011 - train 0.69439 | val 0.70618
  Classification -> best τ=0.390 (val F1=0.1252)
  Directional -> Accuracy: 0.6111, MCC: 0.0000, F1: 0.7586

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69340 | val 0.83403
  Epoch 011 - train 0.68887 | val 0.83745
  Classification -> best τ=0.345 (val F1=0.1314)
  Directional -> Accuracy: 0.5101, MCC: 0.0226, F1: 0.4868

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.70470 | val 0.67501
  Epoch 015 - train 0.68737 | val 0.67835
  Classification -> best τ=0.505 (val F1=0.2548)
  Directional -> Accuracy: 0.6000, MCC: 0.2310, F1: 0.6667

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68336 | val 0.85008
  Epoch 011 - train 0.68958 | val 0.85208
  Classification -> best τ=0.475 (val F1=0.2016)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.70187 | val 0.70982
  Epoch 011 - train 0.70598 | val 0.70973
  Classification -> best τ=0.615 (val F1=0.0811)
  Directional -> Accuracy: 0.4697, MCC: -0.0061, F1: 0.0187

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.69474 | val 0.69957
  Epoch 011 - train 0.69027 | val 0.70037
  Classification -> best τ=0.535 (val F1=0.0904)
  Directional -> Accuracy: 0.5000, MCC: 0.0107, F1: 0.5123

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.70205 | val 0.78725
  Epoch 011 - train 0.69940 | val 0.79025
  Classification -> best τ=0.390 (val F1=0.1128)
  Directional -> Accuracy: 0.5859, MCC: 0.1734, F1: 0.6019

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.71148 | val 0.74215
  Epoch 011 - train 0.71101 | val 0.74362
  Classification -> best τ=0.655 (val F1=0.1196)
  Directional -> Accuracy: 0.5000, MCC: 0.1530, F1: 0.0917

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.70055 | val 0.77870
  Epoch 011 - train 0.71445 | val 0.78489
  Classification -> best τ=0.510 (val F1=0.0599)
  Directional -> Accuracy: 0.5303, MCC: 0.0692, F1: 0.6760

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71400 | val 0.75176
  Epoch 011 - train 0.70139 | val 0.75495
  Classification -> best τ=0.415 (val F1=0.2111)
  Directional -> Accuracy: 0.5303, MCC: -0.0009, F1: 0.6690

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69624 | val 0.72824
  Epoch 011 - train 0.71846 | val 0.73019
  Classification -> best τ=0.560 (val F1=0.0990)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68234 | val 0.73053
  Epoch 011 - train 0.68694 | val 0.73168
  Classification -> best τ=0.680 (val F1=0.1108)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68663 | val 0.83143
  Epoch 011 - train 0.67760 | val 0.83827
  Classification -> best τ=0.375 (val F1=0.0673)
  Directional -> Accuracy: 0.5505, MCC: 0.0745, F1: 0.6397

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69013 | val 0.71406
  Epoch 011 - train 0.69187 | val 0.71455
  Classification -> best τ=0.545 (val F1=0.1506)
  Directional -> Accuracy: 0.5152, MCC: -0.0184, F1: 0.6033

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68592 | val 0.72746
  Epoch 011 - train 0.68197 | val 0.72784
  Classification -> best τ=0.575 (val F1=0.1383)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.72803 | val 1.69014
  Epoch 011 - train 0.72483 | val 1.69715
  Classification -> best τ=0.120 (val F1=0.0822)
  Directional -> Accuracy: 0.5202, MCC: 0.0350, F1: 0.5701

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69528 | val 0.70682
  Epoch 011 - train 0.68220 | val 0.70735
  Classification -> best τ=0.490 (val F1=0.1060)
  Directional -> Accuracy: 0.5404, MCC: 0.0843, F1: 0.5561

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70645 | val 0.73784
  Epoch 011 - train 0.70795 | val 0.73871
  Classification -> best τ=0.440 (val F1=0.1273)
  Directional -> Accuracy: 0.5859, MCC: 0.1369, F1: 0.6639

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69740 | val 0.74624
  Epoch 011 - train 0.69265 | val 0.74725
  Classification -> best τ=0.420 (val F1=0.1042)
  Directional -> Accuracy: 0.5556, MCC: 0.0472, F1: 0.6835

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.71065 | val 0.70471
  Epoch 011 - train 0.69793 | val 0.70502
  Classification -> best τ=0.420 (val F1=0.0898)
  Directional -> Accuracy: 0.5101, MCC: 0.0176, F1: 0.6226

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69517 | val 0.82647
  Epoch 011 - train 0.68739 | val 0.82763
  Classification -> best τ=0.510 (val F1=0.0657)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.68536 | val 0.71437
  Epoch 011 - train 0.68587 | val 0.71329
  Classification -> best τ=0.625 (val F1=0.0553)
  Directional -> Accuracy: 0.5101, MCC: 0.0285, F1: 0.5446

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.70439 | val 0.71794
  Epoch 011 - train 0.70894 | val 0.71846
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.6622

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68741 | val 0.72589
  Epoch 011 - train 0.68444 | val 0.72705
  Classification -> best τ=0.545 (val F1=0.1431)
  Directional -> Accuracy: 0.4848, MCC: 0.0684, F1: 0.0192

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70816 | val 0.72872
  Epoch 011 - train 0.70260 | val 0.72816
  Classification -> best τ=0.480 (val F1=0.1253)
  Directional -> Accuracy: 0.5455, MCC: 0.0161, F1: 0.7000

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.70185 | val 0.75331
  Epoch 011 - train 0.69714 | val 0.75462
  Classification -> best τ=0.390 (val F1=0.1962)
  Directional -> Accuracy: 0.4697, MCC: -0.0400, F1: 0.3636

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68979 | val 0.76608
  Epoch 011 - train 0.68804 | val 0.76981
  Classification -> best τ=0.400 (val F1=0.0988)
  Directional -> Accuracy: 0.5253, MCC: 0.0348, F1: 0.5804

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69274 | val 0.69233
  Epoch 011 - train 0.69677 | val 0.69152
  Classification -> best τ=0.470 (val F1=0.0757)
  Directional -> Accuracy: 0.5354, MCC: 0.0000, F1: 0.6974

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68740 | val 0.72586
  Epoch 011 - train 0.68584 | val 0.72807
  Classification -> best τ=0.545 (val F1=0.1153)
  Directional -> Accuracy: 0.5202, MCC: 0.0354, F1: 0.4751

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69339 | val 0.81742
  Epoch 011 - train 0.69463 | val 0.81993
  Classification -> best τ=0.370 (val F1=0.1240)
  Directional -> Accuracy: 0.5253, MCC: 0.0693, F1: 0.4125

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.71118 | val 0.70695
  Epoch 011 - train 0.71587 | val 0.70603
  Classification -> best τ=0.480 (val F1=0.0671)
  Directional -> Accuracy: 0.4697, MCC: -0.0125, F1: 0.6290

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.70218 | val 1.32294
  Epoch 011 - train 0.69235 | val 1.32969
  Classification -> best τ=0.380 (val F1=0.1592)
  Directional -> Accuracy: 0.4343, MCC: 0.0003, F1: 0.0667

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.69353 | val 0.72288
  Epoch 011 - train 0.70624 | val 0.72139
  Classification -> best τ=0.620 (val F1=0.0505)
  Directional -> Accuracy: 0.5404, MCC: 0.0770, F1: 0.5806

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.69644 | val 1.07166
  Epoch 011 - train 0.69322 | val 1.07418
  Classification -> best τ=0.590 (val F1=0.1931)
  Directional -> Accuracy: 0.4485, MCC: 0.0362, F1: 0.5837

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.70782 | val 0.73531
  Epoch 011 - train 0.70270 | val 0.73434
  Classification -> best τ=0.535 (val F1=0.1010)
  Directional -> Accuracy: 0.5404, MCC: 0.0536, F1: 0.6715

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.70557 | val 0.74894
  Epoch 011 - train 0.70129 | val 0.75243
  Classification -> best τ=0.435 (val F1=0.1436)
  Directional -> Accuracy: 0.5567, MCC: 0.1133, F1: 0.5521

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69335 | val 0.75156
  Epoch 011 - train 0.69702 | val 0.75053
  Classification -> best τ=0.485 (val F1=0.0712)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.6105

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.70499 | val 0.72751
  Epoch 011 - train 0.71048 | val 0.72812
  Classification -> best τ=0.470 (val F1=0.0614)
  Directional -> Accuracy: 0.4433, MCC: -0.1663, F1: 0.5970

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.69247 | val 0.91878
  Epoch 011 - train 0.69906 | val 0.92258
  Classification -> best τ=0.505 (val F1=0.0782)
  Directional -> Accuracy: 0.5354, MCC: 0.1292, F1: 0.6913

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67586 | val 0.69523
  Epoch 011 - train 0.69533 | val 0.69614
  Classification -> best τ=0.480 (val F1=0.1397)
  Directional -> Accuracy: 0.5051, MCC: -0.0980, F1: 0.6711

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.72702 | val 0.69125
  Epoch 011 - train 0.72494 | val 0.69069
  Classification -> best τ=0.500 (val F1=0.1677)
  Directional -> Accuracy: 0.4091, MCC: -0.1600, F1: 0.5301

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.71496 | val 0.71302
  Epoch 011 - train 0.70766 | val 0.71273
  Classification -> best τ=0.630 (val F1=0.0253)
  Directional -> Accuracy: 0.4899, MCC: -0.0009, F1: 0.3879

[75/88] Processing T...


[I 2026-02-25 22:23:03,315] Trial 6 finished with value: 0.11265794016702359 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 3.1108079712638937e-06, 'weight_decay': 3.701517005869976e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.5232831978402217, 'early_stopping_min_delta': 0.005157745692055601}. Best is trial 3 with value: 0.14280424915698534.

  Classification -> best τ=0.395 (val F1=0.0742)
  Directional -> Accuracy: 0.4848, MCC: -0.0607, F1: 0.6483

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.11265794016702359
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67389 | val 0.92947
  Epoch 011 - train 0.66067 | val 0.93349
  Classification -> best τ=0.455 (val F1=0.1130)
  Directional -> Accuracy: 0.5556, MCC: 0.0808, F1: 0.6239

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.65395 | val 1.88917
  Epoch 011 - train 0.64549 | val 1.93179
  Classification -> best τ=0.445 (val F1=0.1826)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65953 | val 0.72003
  Epoch 011 - train 0.66193 | val 0.71829
  Classification -> best τ=0.530 (val F1=0.1210)
  Directional -> Accuracy: 0.4239, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.67087 | val 0.70752
  Epoch 011 - train 0.66962 | val 0.70518
  Classification -> best τ=0.560 (val F1=0.1359)
  Directional -> Accuracy: 0.4192, MCC: -0.0951, F1: 0.1085

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.66026 | val 0.83105
  Epoch 011 - train 0.66122 | val 0.83150
  Classification -> best τ=0.530 (val F1=0.1222)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65257 | val 0.89165
  Epoch 011 - train 0.66076 | val 0.89373
  Classification -> best τ=0.490 (val F1=0.1358)
  Directional -> Accuracy: 0.4495, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67460 | val 0.94733
  Epoch 011 - train 0.67157 | val 0.96516
  Classification -> best τ=0.425 (val F1=0.1436)
  Directional -> Accuracy: 0.5556, MCC: 0.0615, F1: 0.6641

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66698 | val 0.73401
  Epoch 011 - train 0.65851 | val 0.74192
  Classification -> best τ=0.445 (val F1=0.2097)
  Directional -> Accuracy: 0.6212, MCC: 0.1312, F1: 0.7368

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63818 | val 1.42638
  Epoch 011 - train 0.66635 | val 1.43169
  Classification -> best τ=0.470 (val F1=0.1415)
  Directional -> Accuracy: 0.4196, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67949 | val 0.80042
  Epoch 011 - train 0.67798 | val 0.79922
  Classification -> best τ=0.415 (val F1=0.1026)
  Directional -> Accuracy: 0.4747, MCC: -0.0320, F1: 0.5140

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.66165 | val 0.74706
  Epoch 011 - train 0.65587 | val 0.75049
  Classification -> best τ=0.535 (val F1=0.1439)
  Directional -> Accuracy: 0.4646, MCC: -0.0289, F1: 0.2838

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.66626 | val 0.73608
  Epoch 011 - train 0.65902 | val 0.73476
  Classification -> best τ=0.460 (val F1=0.0818)
  Directional -> Accuracy: 0.4596, MCC: 0.0494, F1: 0.2302

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65158 | val 0.84533
  Epoch 011 - train 0.65732 | val 0.85213
  Classification -> best τ=0.485 (val F1=0.1152)
  Directional -> Accuracy: 0.4646, MCC: 0.0256, F1: 0.2319

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66018 | val 0.79866
  Epoch 011 - train 0.66917 | val 0.80415
  Classification -> best τ=0.550 (val F1=0.1629)
  Directional -> Accuracy: 0.5101, MCC: 0.0211, F1: 0.1565

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.68513 | val 0.81011
  Epoch 011 - train 0.68009 | val 0.81636
  Classification -> best τ=0.485 (val F1=0.1131)
  Directional -> Accuracy: 0.4747, MCC: -0.0026, F1: 0.1613

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.65951 | val 1.19735
  Epoch 011 - train 0.66311 | val 1.20657
  Classification -> best τ=0.455 (val F1=0.0806)
  Directional -> Accuracy: 0.5152, MCC: 0.0356, F1: 0.6160

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.67840 | val 0.81583
  Epoch 011 - train 0.67171 | val 0.81825
  Classification -> best τ=0.515 (val F1=0.1337)
  Directional -> Accuracy: 0.5606, MCC: 0.0489, F1: 0.7110

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65937 | val 0.92876
  Epoch 011 - train 0.65673 | val 0.96399
  Classification -> best τ=0.495 (val F1=0.1134)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66556 | val 0.71688
  Epoch 012 - train 0.66346 | val 0.72123
  Classification -> best τ=0.415 (val F1=0.2809)
  Directional -> Accuracy: 0.4949, MCC: -0.0015, F1: 0.0385

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66098 | val 0.80181
  Epoch 011 - train 0.67238 | val 0.80028
  Classification -> best τ=0.525 (val F1=0.0827)
  Directional -> Accuracy: 0.4697, MCC: 0.0348, F1: 0.0870

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.67510 | val 0.74957
  Epoch 011 - train 0.67136 | val 0.74832
  Classification -> best τ=0.470 (val F1=0.0208)
  Directional -> Accuracy: 0.4747, MCC: -0.0504, F1: 0.6061

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.67098 | val 1.07817
  Epoch 011 - train 0.67043 | val 1.11871
  Classification -> best τ=0.555 (val F1=0.0854)
  Directional -> Accuracy: 0.4545, MCC: 0.0593, F1: 0.0847

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66664 | val 0.79431
  Epoch 011 - train 0.66096 | val 0.79030
  Classification -> best τ=0.590 (val F1=0.1338)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.66000 | val 0.85863
  Epoch 011 - train 0.66882 | val 0.86167
  Classification -> best τ=0.465 (val F1=0.1211)
  Directional -> Accuracy: 0.4091, MCC: 0.0271, F1: 0.5618

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67513 | val 0.90735
  Epoch 011 - train 0.67384 | val 0.89900
  Classification -> best τ=0.460 (val F1=0.1371)
  Directional -> Accuracy: 0.5051, MCC: -0.0306, F1: 0.6343

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66722 | val 0.78566
  Epoch 011 - train 0.66667 | val 0.78906
  Classification -> best τ=0.485 (val F1=0.1203)
  Directional -> Accuracy: 0.5101, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66425 | val 0.81618
  Epoch 011 - train 0.67129 | val 0.82679
  Classification -> best τ=0.495 (val F1=0.1456)
  Directional -> Accuracy: 0.4848, MCC: 0.0194, F1: 0.3462

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.68170 | val 0.81537
  Epoch 011 - train 0.66795 | val 0.82620
  Classification -> best τ=0.445 (val F1=0.1518)
  Directional -> Accuracy: 0.4747, MCC: -0.0594, F1: 0.2877

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66829 | val 0.77542
  Epoch 011 - train 0.66408 | val 0.78331
  Classification -> best τ=0.485 (val F1=0.1436)
  Directional -> Accuracy: 0.4949, MCC: 0.0021, F1: 0.2958

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.67704 | val 0.86550
  Epoch 011 - train 0.67306 | val 0.86386
  Classification -> best τ=0.465 (val F1=0.0757)
  Directional -> Accuracy: 0.5253, MCC: 0.0426, F1: 0.5648

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.68697 | val 1.02568
  Epoch 011 - train 0.68341 | val 0.97787
  Classification -> best τ=0.435 (val F1=0.1634)
  Directional -> Accuracy: 0.5000, MCC: 0.0135, F1: 0.3172

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67513 | val 0.82225
  Epoch 011 - train 0.67379 | val 0.84083
  Classification -> best τ=0.475 (val F1=0.1319)
  Directional -> Accuracy: 0.4798, MCC: 0.0111, F1: 0.3522

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.67632 | val 0.77092
  Epoch 011 - train 0.67377 | val 0.76955
  Classification -> best τ=0.465 (val F1=0.1318)
  Directional -> Accuracy: 0.5657, MCC: -0.1278, F1: 0.7190

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65987 | val 0.85971
  Epoch 011 - train 0.66483 | val 0.84531
  Classification -> best τ=0.445 (val F1=0.1296)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.6154

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.64493 | val 0.97674
  Epoch 011 - train 0.67011 | val 0.99576
  Classification -> best τ=0.460 (val F1=0.1131)
  Directional -> Accuracy: 0.5111, MCC: 0.0149, F1: 0.3889

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64367 | val 0.73297
  Epoch 011 - train 0.65949 | val 0.73291
  Classification -> best τ=0.525 (val F1=0.1825)
  Directional -> Accuracy: 0.4444, MCC: 0.0871, F1: 0.1129

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66934 | val 0.76443
  Epoch 011 - train 0.67597 | val 0.76278
  Classification -> best τ=0.515 (val F1=0.1599)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.66690 | val 0.81035
  Epoch 011 - train 0.65779 | val 0.82585
  Classification -> best τ=0.445 (val F1=0.0797)
  Directional -> Accuracy: 0.5657, MCC: 0.0000, F1: 0.7226

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.66812 | val 1.07721
  Epoch 011 - train 0.66617 | val 1.09451
  Classification -> best τ=0.530 (val F1=0.0885)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.66300 | val 1.09799
  Epoch 011 - train 0.66752 | val 1.10714
  Classification -> best τ=0.495 (val F1=0.1307)
  Directional -> Accuracy: 0.4596, MCC: -0.0701, F1: 0.3955

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.66532 | val 1.03860
  Epoch 011 - train 0.66196 | val 1.14115
  Classification -> best τ=0.560 (val F1=0.1202)
  Directional -> Accuracy: 0.5000, MCC: 0.0917, F1: 0.0748

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66920 | val 0.83854
  Epoch 011 - train 0.67597 | val 0.84429
  Classification -> best τ=0.440 (val F1=0.0608)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.7016

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67312 | val 0.71026
  Epoch 011 - train 0.67544 | val 0.70988
  Classification -> best τ=0.505 (val F1=0.0857)
  Directional -> Accuracy: 0.5051, MCC: -0.0172, F1: 0.6597

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66955 | val 0.71699
  Epoch 011 - train 0.67948 | val 0.71749
  Classification -> best τ=0.505 (val F1=0.1706)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65452 | val 1.39485
  Epoch 011 - train 0.65255 | val 1.40344
  Classification -> best τ=0.455 (val F1=0.1393)
  Directional -> Accuracy: 0.5354, MCC: 0.0319, F1: 0.6462

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66252 | val 0.90630
  Epoch 011 - train 0.66536 | val 0.93392
  Classification -> best τ=0.455 (val F1=0.0429)
  Directional -> Accuracy: 0.5859, MCC: 0.0224, F1: 0.7303

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66704 | val 0.75805
  Epoch 011 - train 0.66363 | val 0.75865
  Classification -> best τ=0.490 (val F1=0.1916)
  Directional -> Accuracy: 0.5758, MCC: 0.1307, F1: 0.6348

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67713 | val 0.75757
  Epoch 011 - train 0.66346 | val 0.76228
  Classification -> best τ=0.545 (val F1=0.0327)
  Directional -> Accuracy: 0.5101, MCC: 0.0752, F1: 0.4974

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67464 | val 0.76312
  Epoch 011 - train 0.67879 | val 0.76793
  Classification -> best τ=0.480 (val F1=0.1655)
  Directional -> Accuracy: 0.4848, MCC: -0.0096, F1: 0.6304

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66729 | val 0.86739
  Epoch 011 - train 0.66701 | val 0.88504
  Classification -> best τ=0.495 (val F1=0.0469)
  Directional -> Accuracy: 0.5101, MCC: 0.0541, F1: 0.4813

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67345 | val 0.77901
  Epoch 011 - train 0.67456 | val 0.79059
  Classification -> best τ=0.560 (val F1=0.0904)
  Directional -> Accuracy: 0.4394, MCC: -0.0512, F1: 0.1120

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67623 | val 0.78088
  Epoch 011 - train 0.66237 | val 0.79156
  Classification -> best τ=0.560 (val F1=0.1143)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66372 | val 0.79983
  Epoch 011 - train 0.67516 | val 0.80592
  Classification -> best τ=0.425 (val F1=0.1190)
  Directional -> Accuracy: 0.5505, MCC: 0.1039, F1: 0.5291

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.66926 | val 0.70544
  Epoch 011 - train 0.66683 | val 0.70367
  Classification -> best τ=0.545 (val F1=0.0932)
  Directional -> Accuracy: 0.4040, MCC: 0.0000, F1: 0.0000

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.67053 | val 0.77095
  Epoch 011 - train 0.67352 | val 0.77797
  Classification -> best τ=0.465 (val F1=0.1778)
  Directional -> Accuracy: 0.4899, MCC: -0.0276, F1: 0.3399

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67264 | val 0.75244
  Epoch 011 - train 0.67226 | val 0.75512
  Classification -> best τ=0.555 (val F1=0.1465)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66679 | val 0.76402
  Epoch 011 - train 0.66199 | val 0.77107
  Classification -> best τ=0.515 (val F1=0.0727)
  Directional -> Accuracy: 0.4949, MCC: 0.0488, F1: 0.3421

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.67787 | val 0.73613
  Epoch 011 - train 0.66394 | val 0.73344
  Classification -> best τ=0.505 (val F1=0.0968)
  Directional -> Accuracy: 0.5000, MCC: 0.0864, F1: 0.1951

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65698 | val 1.12593
  Epoch 011 - train 0.65473 | val 1.09800
  Classification -> best τ=0.360 (val F1=0.1541)
  Directional -> Accuracy: 0.4697, MCC: -0.0370, F1: 0.4724

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65620 | val 0.78390
  Epoch 011 - train 0.66534 | val 0.79040
  Classification -> best τ=0.465 (val F1=0.1281)
  Directional -> Accuracy: 0.4899, MCC: -0.0160, F1: 0.4925

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65673 | val 0.87735
  Epoch 011 - train 0.66827 | val 0.88410
  Classification -> best τ=0.540 (val F1=0.0970)
  Directional -> Accuracy: 0.5202, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66324 | val 0.87184
  Epoch 011 - train 0.66504 | val 0.88078
  Classification -> best τ=0.465 (val F1=0.0923)
  Directional -> Accuracy: 0.4747, MCC: -0.0429, F1: 0.3810

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.66822 | val 0.75573
  Epoch 011 - train 0.66795 | val 0.75317
  Classification -> best τ=0.515 (val F1=0.1065)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.66116 | val 1.28158
  Epoch 011 - train 0.66215 | val 1.25741
  Classification -> best τ=0.490 (val F1=0.1413)
  Directional -> Accuracy: 0.4495, MCC: 0.0049, F1: 0.2158

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.66884 | val 0.93382
  Epoch 011 - train 0.68325 | val 0.92846
  Classification -> best τ=0.440 (val F1=0.1097)
  Directional -> Accuracy: 0.4545, MCC: -0.0350, F1: 0.3933

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.66779 | val 0.68401
  Epoch 018 - train 0.65249 | val 0.68815
  Classification -> best τ=0.365 (val F1=0.2157)
  Directional -> Accuracy: 0.4536, MCC: 0.0058, F1: 0.5583

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.65928 | val 0.79679
  Epoch 011 - train 0.65030 | val 0.79916
  Classification -> best τ=0.515 (val F1=0.1052)
  Directional -> Accuracy: 0.5202, MCC: 0.0989, F1: 0.3357

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.66522 | val 0.88403
  Epoch 011 - train 0.67636 | val 0.87741
  Classification -> best τ=0.495 (val F1=0.0706)
  Directional -> Accuracy: 0.5052, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66699 | val 0.68079
  Epoch 014 - train 0.66435 | val 0.68482
  Classification -> best τ=0.505 (val F1=0.2395)
  Directional -> Accuracy: 0.4848, MCC: 0.0177, F1: 0.5446

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.66458 | val 0.70769
  Epoch 011 - train 0.67423 | val 0.71399
  Classification -> best τ=0.505 (val F1=0.1117)
  Directional -> Accuracy: 0.5206, MCC: 0.0452, F1: 0.5714

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.68621 | val 0.70953
  Epoch 011 - train 0.67751 | val 0.71186
  Classification -> best τ=0.520 (val F1=0.0490)
  Directional -> Accuracy: 0.4747, MCC: -0.0331, F1: 0.2778

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66934 | val 0.91774
  Epoch 011 - train 0.66617 | val 0.95937
  Classification -> best τ=0.430 (val F1=0.1148)
  Directional -> Accuracy: 0.4949, MCC: 0.0281, F1: 0.1525

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.67620 | val 1.26744
  Epoch 011 - train 0.68457 | val 1.29418
  Classification -> best τ=0.490 (val F1=0.1109)
  Directional -> Accuracy: 0.6162, MCC: 0.2183, F1: 0.4412

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.67252 | val 0.79017
  Epoch 011 - train 0.67639 | val 0.78861
  Classification -> best τ=0.500 (val F1=0.0748)
  Directional -> Accuracy: 0.4949, MCC: 0.0807, F1: 0.1228

[75/88] Processing T...

Processing T (Technology)...

[I 2026-02-25 22:37:29,972] Trial 7 finished with value: 0.12477118617689048 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00015830689709959232, 'weight_decay': 9.31402304144689e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.8474771741735326, 'early_stopping_min_delta': 0.0040927820185497}. Best is trial 3 with value: 0.14280424915698534.

  Epoch 011 - train 0.67262 | val 0.89740
  Classification -> best τ=0.455 (val F1=0.1495)
  Directional -> Accuracy: 0.4848, MCC: -0.1020, F1: 0.6531

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.12477118617689048
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67661 | val 1.31721
  Epoch 020 - train 0.64851 | val 1.04833
  Epoch 021 - train 0.65746 | val 1.27820
  Classification -> best τ=0.185 (val F1=0.1683)
  Directional -> Accuracy: 0.4750, MCC: 0.0199, F1: 0.4068

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.64112 | val 3.23503
  Epoch 020 - train 0.58720 | val 5.58428
  Epoch 021 - train 0.56259 | val 7.07179
  Classification -> best τ=0.435 (val F1=0.1112)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66688 | val 0.74714
  Epoch 020 - train 0.63482 | val 0.87456
  Epoch 025 - train 0.60979 | val 1.00522
  Classification -> best τ=0.240 (val F1=0.1643)
  Directional -> Accuracy: 0.5882, MCC: 0.0980, F1: 0.7354

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.67994 | val 0.72924
  Epoch 020 - train 0.64811 | val 0.73399
  Epoch 030 - train 0.61844 | val 0.70158
  Epoch 040 - train 0.53269 | val 0.77439
  Epoch 041 - train 0.52788 | val 0.78055
  Classification -> best τ=0.565 (val F1=0.2096)
  Directional -> Accuracy: 0.4350, MCC: -0.0504, F1: 0.0504

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.64268 | val 0.78667
  Epoch 020 - train 0.61425 | val 0.80043
  Epoch 023 - train 0.58969 | val 0.80875
  Classification -> best τ=0.515 (val F1=0.1830)
  Directional -> Accuracy: 0.4766, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68389 | val 0.78430
  Epoch 020 - train 0.61758 | val 1.24462
  Epoch 026 - train 0.59769 | val 1.29175
  Classification -> best τ=0.835 (val F1=0.1057)
  Directional -> Accuracy: 0.4550, MCC: 0.0900, F1: 0.0354

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67787 | val 0.78823
  Epoch 020 - train 0.65663 | val 1.39218
  Epoch 022 - train 0.64809 | val 1.74015
  Classification -> best τ=0.375 (val F1=0.1582)
  Directional -> Accuracy: 0.5600, MCC: 0.0754, F1: 0.6562

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65670 | val 1.19857
  Epoch 020 - train 0.63516 | val 1.76443
  Epoch 022 - train 0.59155 | val 1.82868
  Classification -> best τ=0.265 (val F1=0.2958)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65472 | val 2.12239
  Epoch 020 - train 0.60899 | val 2.27839
  Epoch 021 - train 0.58659 | val 2.42530
  Classification -> best τ=0.400 (val F1=0.1970)
  Directional -> Accuracy: 0.4174, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64942 | val 1.38561
  Epoch 020 - train 0.63292 | val 1.95103
  Epoch 021 - train 0.63772 | val 1.45129
  Classification -> best τ=0.905 (val F1=0.0873)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.66356 | val 0.68655
  Epoch 020 - train 0.63483 | val 0.83989
  Epoch 030 - train 0.57604 | val 0.92072
  Epoch 038 - train 0.54774 | val 1.21274
  Classification -> best τ=0.530 (val F1=0.1999)
  Directional -> Accuracy: 0.5150, MCC: 0.0088, F1: 0.5872

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.66951 | val 0.74026
  Epoch 020 - train 0.64437 | val 0.76750
  Epoch 023 - train 0.63635 | val 0.79012
  Classification -> best τ=0.655 (val F1=0.1472)
  Directional -> Accuracy: 0.4250, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65772 | val 1.12751
  Epoch 020 - train 0.62694 | val 1.26523
  Epoch 021 - train 0.62908 | val 1.30373
  Classification -> best τ=0.525 (val F1=0.1834)
  Directional -> Accuracy: 0.4850, MCC: 0.0156, F1: 0.4114

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66375 | val 0.95676
  Epoch 020 - train 0.60220 | val 1.33358
  Epoch 021 - train 0.58320 | val 1.61690
  Classification -> best τ=0.765 (val F1=0.2017)
  Directional -> Accuracy: 0.5000, MCC: -0.0149, F1: 0.1379

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.67996 | val 0.90817
  Epoch 020 - train 0.65828 | val 1.10045
  Epoch 028 - train 0.62442 | val 1.19954
  Classification -> best τ=0.405 (val F1=0.0850)
  Directional -> Accuracy: 0.4700, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.64433 | val 1.78240
  Epoch 020 - train 0.63110 | val 2.10987
  Epoch 021 - train 0.62198 | val 2.08922
  Classification -> best τ=0.265 (val F1=0.1493)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.68020 | val 0.79995
  Epoch 020 - train 0.62579 | val 1.00792
  Epoch 024 - train 0.61030 | val 1.13369
  Classification -> best τ=0.475 (val F1=0.1944)
  Directional -> Accuracy: 0.5550, MCC: 0.0000, F1: 0.7138

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64641 | val 1.00739
  Epoch 020 - train 0.61054 | val 0.90037
  Epoch 027 - train 0.55198 | val 0.86136
  Classification -> best τ=0.835 (val F1=0.1764)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67161 | val 0.94860
  Epoch 020 - train 0.61433 | val 1.31858
  Epoch 021 - train 0.64274 | val 1.22089
  Classification -> best τ=0.390 (val F1=0.2662)
  Directional -> Accuracy: 0.4950, MCC: -0.0709, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64744 | val 0.82972
  Epoch 020 - train 0.62123 | val 0.91674
  Epoch 021 - train 0.61810 | val 0.98175
  Classification -> best τ=0.540 (val F1=0.1294)
  Directional -> Accuracy: 0.4700, MCC: 0.0067, F1: 0.1719

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.67581 | val 0.81838
  Epoch 020 - train 0.62952 | val 1.14028
  Epoch 028 - train 0.57957 | val 1.23008
  Classification -> best τ=0.785 (val F1=0.1364)
  Directional -> Accuracy: 0.5150, MCC: 0.0298, F1: 0.5076

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.67478 | val 1.16300
  Epoch 020 - train 0.63506 | val 1.83558
  Epoch 024 - train 0.62749 | val 2.49490
  Classification -> best τ=0.450 (val F1=0.1649)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67173 | val 0.78645
  Epoch 020 - train 0.62707 | val 2.11340
  Epoch 025 - train 0.60509 | val 1.82967
  Classification -> best τ=0.325 (val F1=0.2305)
  Directional -> Accuracy: 0.5200, MCC: 0.0304, F1: 0.5636

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.67191 | val 1.05406
  Epoch 020 - train 0.63913 | val 1.23574
  Epoch 021 - train 0.63203 | val 1.15755
  Classification -> best τ=0.245 (val F1=0.1127)
  Directional -> Accuracy: 0.4550, MCC: 0.0591, F1: 0.5514

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66049 | val 1.04071
  Epoch 020 - train 0.60304 | val 1.57422
  Epoch 027 - train 0.57199 | val 2.19597
  Classification -> best τ=0.235 (val F1=0.1021)
  Directional -> Accuracy: 0.5150, MCC: 0.0403, F1: 0.4641

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67462 | val 0.93294
  Epoch 020 - train 0.65430 | val 1.08462
  Epoch 021 - train 0.66007 | val 1.08400
  Classification -> best τ=0.440 (val F1=0.1712)
  Directional -> Accuracy: 0.5450, MCC: 0.0922, F1: 0.3158

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66529 | val 0.77067
  Epoch 020 - train 0.64360 | val 0.79439
  Epoch 024 - train 0.61181 | val 0.85760
  Classification -> best τ=0.565 (val F1=0.1315)
  Directional -> Accuracy: 0.4800, MCC: 0.0449, F1: 0.1746

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.68463 | val 0.83736
  Epoch 020 - train 0.63939 | val 0.96242
  Epoch 021 - train 0.64444 | val 1.09645
  Classification -> best τ=0.395 (val F1=0.1338)
  Directional -> Accuracy: 0.5450, MCC: 0.1115, F1: 0.6486

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66877 | val 1.28864
  Epoch 020 - train 0.65316 | val 2.28749
  Epoch 021 - train 0.64350 | val 1.99675
  Classification -> best τ=0.825 (val F1=0.1244)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.68806 | val 0.69711
  Epoch 020 - train 0.65086 | val 0.79844
  Epoch 030 - train 0.58491 | val 1.09132
  Classification -> best τ=0.480 (val F1=0.0596)
  Directional -> Accuracy: 0.4800, MCC: -0.0307, F1: 0.4694

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.67807 | val 1.99589
  Epoch 020 - train 0.63086 | val 3.29753
  Epoch 024 - train 0.61295 | val 3.61089
  Classification -> best τ=0.520 (val F1=0.1448)
  Directional -> Accuracy: 0.4950, MCC: 0.0000, F1: 0.0000

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68213 | val 0.70481
  Epoch 020 - train 0.64852 | val 0.78697
  Epoch 030 - train 0.62436 | val 0.87310
  Classification -> best τ=0.395 (val F1=0.2561)
  Directional -> Accuracy: 0.5650, MCC: 0.1075, F1: 0.6329

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.67232 | val 0.85299
  Epoch 020 - train 0.66386 | val 0.89679
  Epoch 021 - train 0.65194 | val 1.17333
  Classification -> best τ=0.555 (val F1=0.1640)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65912 | val 1.06986
  Epoch 020 - train 0.62303 | val 1.06537
  Epoch 021 - train 0.62854 | val 1.09870
  Classification -> best τ=0.435 (val F1=0.0698)
  Directional -> Accuracy: 0.4900, MCC: 0.0422, F1: 0.5750

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.63667 | val 1.60845
  Epoch 020 - train 0.56632 | val 1.17604
  Epoch 021 - train 0.60562 | val 1.15792
  Classification -> best τ=0.455 (val F1=0.2493)
  Directional -> Accuracy: 0.5417, MCC: 0.0917, F1: 0.6207

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65087 | val 0.71641
  Epoch 020 - train 0.62443 | val 0.85136
  Epoch 021 - train 0.62625 | val 0.95580
  Classification -> best τ=0.580 (val F1=0.2415)
  Directional -> Accuracy: 0.4250, MCC: 0.0847, F1: 0.0336

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67278 | val 0.80226
  Epoch 020 - train 0.64440 | val 0.89115
  Epoch 025 - train 0.62287 | val 1.06280
  Classification -> best τ=0.700 (val F1=0.1882)
  Directional -> Accuracy: 0.4600, MCC: -0.0499, F1: 0.0182

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.66393 | val 1.01977
  Epoch 020 - train 0.62990 | val 1.12062
  Epoch 021 - train 0.62605 | val 1.21961
  Classification -> best τ=0.760 (val F1=0.0900)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.66888 | val 1.54783
  Epoch 020 - train 0.63063 | val 1.68717
  Epoch 021 - train 0.61636 | val 1.74323
  Classification -> best τ=0.605 (val F1=0.0584)
  Directional -> Accuracy: 0.4550, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.68389 | val 0.85194
  Epoch 020 - train 0.64076 | val 1.15871
  Epoch 028 - train 0.60248 | val 1.20229
  Classification -> best τ=0.375 (val F1=0.0929)
  Directional -> Accuracy: 0.4900, MCC: -0.0195, F1: 0.5000

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.67834 | val 0.91541
  Epoch 020 - train 0.66116 | val 1.02825
  Epoch 030 - train 0.61507 | val 1.52274
  Epoch 033 - train 0.59974 | val 1.89853
  Classification -> best τ=0.610 (val F1=0.1695)
  Directional -> Accuracy: 0.5050, MCC: 0.0088, F1: 0.5217

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66137 | val 0.97881
  Epoch 020 - train 0.63106 | val 0.99935
  Epoch 022 - train 0.61378 | val 1.28289
  Classification -> best τ=0.885 (val F1=0.0873)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67158 | val 0.88818
  Epoch 020 - train 0.64199 | val 0.97823
  Epoch 030 - train 0.60810 | val 1.11638
  Epoch 040 - train 0.54578 | val 1.41962
  Epoch 041 - train 0.52738 | val 1.58947
  Classification -> best τ=0.895 (val F1=0.1680)
  Directional -> Accuracy: 0.5050, MCC: 0.0767, F1: 0.1391

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65203 | val 1.02058
  Epoch 020 - train 0.62474 | val 1.45409
  Epoch 021 - train 0.63955 | val 1.32874
  Classification -> best τ=0.600 (val F1=0.1301)
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65069 | val 2.09228
  Epoch 020 - train 0.62127 | val 2.34911
  Epoch 028 - train 0.56015 | val 3.00987
  Classification -> best τ=0.415 (val F1=0.0966)
  Directional -> Accuracy: 0.4750, MCC: 0.0006, F1: 0.2222

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66013 | val 1.00612
  Epoch 020 - train 0.63804 | val 1.20364
  Epoch 021 - train 0.62881 | val 1.31921
  Classification -> best τ=0.305 (val F1=0.0840)
  Directional -> Accuracy: 0.5850, MCC: 0.0543, F1: 0.7224

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65943 | val 0.93237
  Epoch 020 - train 0.62461 | val 1.00491
  Epoch 021 - train 0.62146 | val 0.92850
  Classification -> best τ=0.385 (val F1=0.1456)
  Directional -> Accuracy: 0.5650, MCC: 0.0437, F1: 0.7031

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67909 | val 0.71736
  Epoch 020 - train 0.63355 | val 0.87054
  Epoch 030 - train 0.55312 | val 0.89945
  Epoch 033 - train 0.54988 | val 0.97246
  Classification -> best τ=0.570 (val F1=0.1121)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65762 | val 1.06950
  Epoch 020 - train 0.61538 | val 1.36746
  Epoch 024 - train 0.60432 | val 1.48834
  Classification -> best τ=0.605 (val F1=0.1391)
  Directional -> Accuracy: 0.5200, MCC: 0.0346, F1: 0.3514

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66357 | val 0.89229
  Epoch 020 - train 0.64391 | val 0.84143
  Epoch 030 - train 0.63400 | val 1.01110
  Epoch 037 - train 0.59581 | val 0.98560
  Classification -> best τ=0.335 (val F1=0.1526)
  Directional -> Accuracy: 0.5350, MCC: -0.0447, F1: 0.6782

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68008 | val 0.80785
  Epoch 020 - train 0.65556 | val 0.94880
  Epoch 021 - train 0.65960 | val 0.86282
  Classification -> best τ=0.340 (val F1=0.1037)
  Directional -> Accuracy: 0.5100, MCC: 0.0081, F1: 0.5586

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67174 | val 0.80161
  Epoch 020 - train 0.65883 | val 0.97029
  Epoch 021 - train 0.63299 | val 0.85068
  Classification -> best τ=0.555 (val F1=0.1295)
  Directional -> Accuracy: 0.5000, MCC: 0.0176, F1: 0.1228

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67387 | val 0.77287
  Epoch 020 - train 0.63977 | val 0.88519
  Epoch 030 - train 0.59105 | val 0.97932
  Epoch 034 - train 0.58368 | val 0.94396
  Classification -> best τ=0.375 (val F1=0.1452)
  Directional -> Accuracy: 0.5550, MCC: 0.1069, F1: 0.5899

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.66620 | val 0.86691
  Epoch 020 - train 0.65154 | val 0.83783
  Epoch 022 - train 0.63342 | val 0.92199
  Classification -> best τ=0.560 (val F1=0.1499)
  Directional -> Accuracy: 0.4050, MCC: -0.0571, F1: 0.1185

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.67625 | val 0.79462
  Epoch 020 - train 0.61352 | val 1.11827
  Epoch 023 - train 0.61501 | val 1.28813
  Classification -> best τ=0.495 (val F1=0.1636)
  Directional -> Accuracy: 0.5050, MCC: 0.0178, F1: 0.6056

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68066 | val 1.00482
  Epoch 020 - train 0.65791 | val 1.07058
  Epoch 024 - train 0.63069 | val 1.11965
  Classification -> best τ=0.630 (val F1=0.1387)
  Directional -> Accuracy: 0.5100, MCC: -0.0017, F1: 0.6048

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66890 | val 0.79597
  Epoch 020 - train 0.63723 | val 1.06115
  Epoch 029 - train 0.59405 | val 1.42354
  Classification -> best τ=0.625 (val F1=0.1661)
  Directional -> Accuracy: 0.4650, MCC: 0.0347, F1: 0.1301

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.68293 | val 0.69685
  Epoch 020 - train 0.63455 | val 0.77006
  Epoch 021 - train 0.63671 | val 0.79398
  Classification -> best τ=0.600 (val F1=0.1755)
  Directional -> Accuracy: 0.4600, MCC: -0.0741, F1: 0.0847

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67760 | val 1.05491
  Epoch 020 - train 0.62575 | val 1.33180
  Epoch 021 - train 0.63202 | val 1.25145
  Classification -> best τ=0.465 (val F1=0.1850)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66322 | val 1.02007
  Epoch 020 - train 0.61751 | val 1.24171
  Epoch 021 - train 0.63078 | val 1.29996
  Classification -> best τ=0.660 (val F1=0.0937)
  Directional -> Accuracy: 0.4750, MCC: 0.0668, F1: 0.0187

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66176 | val 0.92305
  Epoch 020 - train 0.63731 | val 1.41017
  Epoch 030 - train 0.59634 | val 1.19621
  Epoch 036 - train 0.57661 | val 1.61631
  Classification -> best τ=0.050 (val F1=0.0811)
  Directional -> Accuracy: 0.4750, MCC: -0.0102, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67269 | val 0.89070
  Epoch 020 - train 0.64313 | val 0.97222
  Epoch 021 - train 0.64904 | val 1.40443
  Classification -> best τ=0.505 (val F1=0.1626)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...

[I 2026-02-25 22:49:22,433] Trial 8 finished with value: 0.15238950933016568 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.0018191767192738042, 'weight_decay': 1.1560148949088917e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.0236000338616036, 'early_stopping_min_delta': 0.0011479160477991068}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 021 - train 0.62427 | val 1.41445
  Classification -> best τ=0.390 (val F1=0.1678)
  Directional -> Accuracy: 0.4950, MCC: -0.0040, F1: 0.5590

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.15238950933016568
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67420 | val 0.70633
  Epoch 020 - train 0.64878 | val 0.72269
  Classification -> best τ=0.460 (val F1=0.1099)
  Directional -> Accuracy: 0.4141, MCC: -0.0402, F1: 0.0794

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.65267 | val 0.92389
  Epoch 020 - train 0.62595 | val 1.21091
  Classification -> best τ=0.475 (val F1=0.1437)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64980 | val 0.75436
  Epoch 020 - train 0.63368 | val 0.80258
  Classification -> best τ=0.500 (val F1=0.1598)
  Directional -> Accuracy: 0.4973, MCC: -0.0289, F1: 0.5634

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.66988 | val 1.41331
  Epoch 020 - train 0.65402 | val 1.61172
  Classification -> best τ=0.475 (val F1=0.0659)
  Directional -> Accuracy: 0.4596, MCC: 0.0583, F1: 0.1575

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.64132 | val 0.77885
  Epoch 020 - train 0.62146 | val 0.87874
  Classification -> best τ=0.490 (val F1=0.0863)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65714 | val 0.73343
  Epoch 020 - train 0.63619 | val 0.76830
  Classification -> best τ=0.445 (val F1=0.1886)
  Directional -> Accuracy: 0.5303, MCC: -0.0444, F1: 0.6804

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66384 | val 1.53606
  Epoch 020 - train 0.64895 | val 2.06556
  Classification -> best τ=0.505 (val F1=0.1177)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64736 | val 0.67094
  Epoch 020 - train 0.63400 | val 0.66917
  Classification -> best τ=0.460 (val F1=0.2121)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65395 | val 0.74318
  Epoch 020 - train 0.64172 | val 0.76641
  Classification -> best τ=0.445 (val F1=0.1668)
  Directional -> Accuracy: 0.4867, MCC: 0.0042, F1: 0.4727

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65628 | val 0.76996
  Epoch 020 - train 0.64286 | val 0.86328
  Classification -> best τ=0.510 (val F1=0.1020)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.64349 | val 1.54621
  Epoch 020 - train 0.62423 | val 1.53890
  Classification -> best τ=0.530 (val F1=0.0927)
  Directional -> Accuracy: 0.5202, MCC: 0.0928, F1: 0.3949

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.65114 | val 0.87057
  Epoch 020 - train 0.63117 | val 0.88030
  Classification -> best τ=0.540 (val F1=0.1461)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64168 | val 1.02334
  Epoch 020 - train 0.62979 | val 1.06862
  Classification -> best τ=0.570 (val F1=0.0899)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66131 | val 0.88577
  Epoch 020 - train 0.63671 | val 0.96862
  Classification -> best τ=0.530 (val F1=0.1787)
  Directional -> Accuracy: 0.4949, MCC: -0.0398, F1: 0.0909

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.66740 | val 0.72802
  Epoch 020 - train 0.65250 | val 0.72966
  Classification -> best τ=0.520 (val F1=0.0499)
  Directional -> Accuracy: 0.4545, MCC: -0.0854, F1: 0.4433

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.64947 | val 0.76145
  Epoch 020 - train 0.62860 | val 0.79555
  Classification -> best τ=0.455 (val F1=0.0915)
  Directional -> Accuracy: 0.4949, MCC: -0.0101, F1: 0.4792

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.65390 | val 0.73856
  Epoch 020 - train 0.63855 | val 0.77610
  Classification -> best τ=0.445 (val F1=0.1259)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65321 | val 0.72186
  Epoch 020 - train 0.63713 | val 0.76286
  Classification -> best τ=0.505 (val F1=0.1091)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64519 | val 0.69285
  Epoch 020 - train 0.63398 | val 0.70682
  Classification -> best τ=0.475 (val F1=0.2030)
  Directional -> Accuracy: 0.5051, MCC: 0.0249, F1: 0.2344

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66279 | val 0.69754
  Epoch 020 - train 0.63572 | val 0.70221
  Classification -> best τ=0.490 (val F1=0.0952)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.65559 | val 0.68867
  Epoch 020 - train 0.63417 | val 0.69558
  Classification -> best τ=0.510 (val F1=0.1764)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.6576

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.66837 | val 1.62217
  Epoch 020 - train 0.65451 | val 1.95167
  Classification -> best τ=0.410 (val F1=0.1260)
  Directional -> Accuracy: 0.4596, MCC: 0.0128, F1: 0.2190

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65665 | val 1.09531
  Epoch 020 - train 0.64293 | val 1.12891
  Classification -> best τ=0.455 (val F1=0.0945)
  Directional -> Accuracy: 0.4949, MCC: -0.0101, F1: 0.5146

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.65296 | val 0.75233
  Epoch 020 - train 0.64728 | val 0.77207
  Classification -> best τ=0.505 (val F1=0.0876)
  Directional -> Accuracy: 0.4242, MCC: -0.0633, F1: 0.4865

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66072 | val 1.07907
  Epoch 020 - train 0.63131 | val 1.27454
  Classification -> best τ=0.495 (val F1=0.1637)
  Directional -> Accuracy: 0.5000, MCC: 0.0452, F1: 0.2774

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65448 | val 0.81450
  Epoch 020 - train 0.63478 | val 0.89697
  Classification -> best τ=0.495 (val F1=0.1837)
  Directional -> Accuracy: 0.5505, MCC: 0.1212, F1: 0.2992

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65103 | val 1.02798
  Epoch 020 - train 0.62382 | val 1.39775
  Classification -> best τ=0.430 (val F1=0.0774)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.66135 | val 0.94578
  Epoch 020 - train 0.65356 | val 1.11513
  Classification -> best τ=0.500 (val F1=0.0676)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65972 | val 0.73388
  Epoch 020 - train 0.64824 | val 0.77104
  Classification -> best τ=0.470 (val F1=0.0705)
  Directional -> Accuracy: 0.4949, MCC: -0.0077, F1: 0.4681

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.65632 | val 1.08688
  Epoch 020 - train 0.63102 | val 1.47430
  Classification -> best τ=0.460 (val F1=0.0940)
  Directional -> Accuracy: 0.5152, MCC: 0.0598, F1: 0.4607

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.65759 | val 0.81075
  Epoch 020 - train 0.64232 | val 0.91667
  Classification -> best τ=0.480 (val F1=0.1518)
  Directional -> Accuracy: 0.4848, MCC: -0.0493, F1: 0.5984

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66271 | val 0.71036
  Epoch 020 - train 0.63822 | val 0.73453
  Classification -> best τ=0.445 (val F1=0.1260)
  Directional -> Accuracy: 0.5556, MCC: 0.0788, F1: 0.7124

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.66337 | val 0.69333
  Epoch 020 - train 0.64856 | val 0.70409
  Classification -> best τ=0.460 (val F1=0.1293)
  Directional -> Accuracy: 0.5707, MCC: -0.0721, F1: 0.7176

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65191 | val 1.10097
  Epoch 020 - train 0.64769 | val 1.30530
  Classification -> best τ=0.505 (val F1=0.1003)
  Directional -> Accuracy: 0.5657, MCC: 0.0791, F1: 0.3065

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.63914 | val 0.74644
  Epoch 020 - train 0.64210 | val 0.88875
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65199 | val 0.70404
  Epoch 020 - train 0.63464 | val 0.69813
  Classification -> best τ=0.495 (val F1=0.2029)
  Directional -> Accuracy: 0.3990, MCC: -0.1250, F1: 0.0775

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64903 | val 0.73434
  Epoch 020 - train 0.62988 | val 0.78832
  Classification -> best τ=0.520 (val F1=0.1554)
  Directional -> Accuracy: 0.4646, MCC: -0.0757, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.67009 | val 1.10198
  Epoch 020 - train 0.65042 | val 1.29535
  Classification -> best τ=0.460 (val F1=0.0393)
  Directional -> Accuracy: 0.5707, MCC: 0.0840, F1: 0.6792

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.65556 | val 1.13608
  Epoch 020 - train 0.65031 | val 1.36803
  Classification -> best τ=0.500 (val F1=0.0369)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.65408 | val 0.69633
  Epoch 020 - train 0.63578 | val 0.70113
  Classification -> best τ=0.560 (val F1=0.1790)
  Directional -> Accuracy: 0.4747, MCC: -0.0254, F1: 0.2778

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.65728 | val 0.71858
  Epoch 020 - train 0.64377 | val 0.70323
  Classification -> best τ=0.570 (val F1=0.1352)
  Directional -> Accuracy: 0.5354, MCC: 0.0967, F1: 0.4026

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65595 | val 0.85621
  Epoch 020 - train 0.65060 | val 0.87180
  Classification -> best τ=0.475 (val F1=0.1275)
  Directional -> Accuracy: 0.5808, MCC: 0.1473, F1: 0.6376

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65650 | val 0.97936
  Epoch 020 - train 0.64642 | val 1.04547
  Classification -> best τ=0.505 (val F1=0.0901)
  Directional -> Accuracy: 0.4545, MCC: -0.1004, F1: 0.2174

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66427 | val 0.69977
  Epoch 020 - train 0.65018 | val 0.73024
  Classification -> best τ=0.475 (val F1=0.1878)
  Directional -> Accuracy: 0.4899, MCC: 0.0430, F1: 0.0901

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64931 | val 1.53651
  Epoch 020 - train 0.63068 | val 2.10458
  Classification -> best τ=0.405 (val F1=0.1399)
  Directional -> Accuracy: 0.5303, MCC: 0.0314, F1: 0.6204

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65510 | val 0.86725
  Epoch 020 - train 0.64076 | val 0.84239
  Classification -> best τ=0.510 (val F1=0.0386)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66393 | val 0.69640
  Epoch 020 - train 0.65166 | val 0.70326
  Classification -> best τ=0.510 (val F1=0.1567)
  Directional -> Accuracy: 0.5657, MCC: 0.0805, F1: 0.7208

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65189 | val 0.84784
  Epoch 020 - train 0.62550 | val 0.98427
  Classification -> best τ=0.365 (val F1=0.1334)
  Directional -> Accuracy: 0.4899, MCC: -0.1480, F1: 0.6245

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65156 | val 0.79526
  Epoch 020 - train 0.64047 | val 0.69639
  Classification -> best τ=0.520 (val F1=0.1567)
  Directional -> Accuracy: 0.5000, MCC: -0.0208, F1: 0.2878

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66139 | val 0.69460
  Epoch 020 - train 0.64356 | val 0.69794
  Classification -> best τ=0.525 (val F1=0.0962)
  Directional -> Accuracy: 0.5101, MCC: 0.0925, F1: 0.4121

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66036 | val 1.03244
  Epoch 020 - train 0.64550 | val 1.06375
  Classification -> best τ=0.430 (val F1=0.1239)
  Directional -> Accuracy: 0.5253, MCC: 0.0497, F1: 0.5524

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64335 | val 0.75291
  Epoch 020 - train 0.62649 | val 0.81251
  Classification -> best τ=0.475 (val F1=0.1054)
  Directional -> Accuracy: 0.5202, MCC: 0.0925, F1: 0.1739

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65547 | val 0.73863
  Epoch 020 - train 0.65019 | val 0.74986
  Classification -> best τ=0.525 (val F1=0.1048)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.65670 | val 1.48104
  Epoch 020 - train 0.64695 | val 1.89157
  Classification -> best τ=0.450 (val F1=0.1219)
  Directional -> Accuracy: 0.4192, MCC: -0.0172, F1: 0.1727

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.65877 | val 0.96330
  Epoch 020 - train 0.63951 | val 1.07710
  Classification -> best τ=0.510 (val F1=0.1351)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.6622

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65845 | val 0.80344
  Epoch 020 - train 0.64581 | val 0.83157
  Classification -> best τ=0.570 (val F1=0.0978)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63996 | val 0.76145
  Epoch 020 - train 0.61992 | val 0.84690
  Classification -> best τ=0.565 (val F1=0.1231)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.66171 | val 2.03538
  Epoch 020 - train 0.64293 | val 2.42578
  Classification -> best τ=0.480 (val F1=0.2120)
  Directional -> Accuracy: 0.5101, MCC: 0.1073, F1: 0.2362

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65139 | val 0.75143
  Epoch 020 - train 0.62406 | val 0.78808
  Classification -> best τ=0.495 (val F1=0.2358)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64522 | val 0.73840
  Epoch 020 - train 0.62930 | val 0.91047
  Classification -> best τ=0.505 (val F1=0.1487)
  Directional -> Accuracy: 0.5152, MCC: 0.0979, F1: 0.3239

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66234 | val 0.82537
  Epoch 020 - train 0.63698 | val 0.86466
  Classification -> best τ=0.455 (val F1=0.0456)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.6485

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64970 | val 0.75866
  Epoch 020 - train 0.63618 | val 0.82435
  Classification -> best τ=0.490 (val F1=0.1731)
  Directional -> Accuracy: 0.4848, MCC: -0.0031, F1: 0.0192

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.65314 | val 1.24405
  Epoch 020 - train 0.63932 | val 1.21472
  Classification -> best τ=0.525 (val F1=0.1534)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.65491 | val 0.90555
  Epoch 020 - train 0.64245 | val 0.82183
  Classification -> best τ=0.505 (val F1=0.1956)
  Directional -> Accuracy: 0.4545, MCC: 0.0473, F1: 0.1692

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.65605 | val 1.23571
  Epoch 020 - train 0.64442 | val 1.62978
  Classification -> best τ=0.500 (val F1=0.1312)
  Directional -> Accuracy: 0.4747, MCC: -0.0512, F1: 0.5140

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.64165 | val 0.75298
  Epoch 020 - train 0.62040 | val 1.12594
  Classification -> best τ=0.475 (val F1=0.2242)
  Directional -> Accuracy: 0.4769, MCC: 0.0342, F1: 0.5487

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.65504 | val 0.68784
  Epoch 020 - train 0.63949 | val 0.74852
  Classification -> best τ=0.565 (val F1=0.1829)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.65625 | val 0.71019
  Epoch 020 - train 0.64794 | val 0.74111
  Classification -> best τ=0.540 (val F1=0.0795)
  Directional -> Accuracy: 0.5026, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63976 | val 0.84202
  Epoch 020 - train 0.62304 | val 0.99790
  Classification -> best τ=0.510 (val F1=0.1802)
  Directional -> Accuracy: 0.4798, MCC: -0.0077, F1: 0.5164

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.65317 | val 0.74086
  Epoch 020 - train 0.63856 | val 0.80214
  Classification -> best τ=0.505 (val F1=0.1152)
  Directional -> Accuracy: 0.4974, MCC: -0.0070, F1: 0.4615

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.66707 | val 0.88500
  Epoch 020 - train 0.65473 | val 0.91241
  Classification -> best τ=0.560 (val F1=0.2244)
  Directional -> Accuracy: 0.5404, MCC: 0.0849, F1: 0.5285

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.65127 | val 1.27144
  Epoch 020 - train 0.63824 | val 1.31407
  Classification -> best τ=0.465 (val F1=0.1155)
  Directional -> Accuracy: 0.5404, MCC: 0.0813, F1: 0.6592

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.66299 | val 1.07239
  Epoch 020 - train 0.65362 | val 1.24910
  Classification -> best τ=0.525 (val F1=0.1295)
  Directional -> Accuracy: 0.5859, MCC: 0.1582, F1: 0.2807

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.67166 | val 0.82615
  Epoch 020 - train 0.64884 | val 0.90022
  Classification -> best τ=0.485 (val F1=0.0149)
  Directional -> Accuracy: 0.4798, MCC: 0.0677, F1: 0.0190

[75/88] Processing T...


[I 2026-02-25 22:55:09,089] Trial 9 finished with value: 0.12521011328903855 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 0.0002998788157400683, 'weight_decay': 3.482308060045359e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.9087423948880948, 'early_stopping_min_delta': 0.003415940200332356}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 020 - train 0.64387 | val 0.78963
  Classification -> best τ=0.485 (val F1=0.1543)
  Directional -> Accuracy: 0.5152, MCC: 0.0899, F1: 0.6643

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.12521011328903855
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69579 | val 0.69163
  Epoch 020 - train 0.69361 | val 0.75482
  Epoch 026 - train 0.69365 | val 0.72259
  Classification -> best τ=0.500 (val F1=0.0227)
  Directional -> Accuracy: 0.4724, MCC: 0.0431, F1: 0.3478

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.69618 | val 0.69958
  Epoch 020 - train 0.69348 | val 0.69619
  Epoch 022 - train 0.69346 | val 0.69599
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5025, MCC: 0.0000, F1: 0.6689

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69841 | val 0.69307
  Epoch 020 - train 0.69153 | val 0.69287
  Epoch 022 - train 0.69130 | val 0.69293
  Classification -> best τ=0.495 (val F1=0.0784)
  Directional -> Accuracy: 0.4194, MCC: -0.0856, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.69072 | val 0.68961
  Epoch 020 - train 0.69007 | val 0.68988
  Epoch 023 - train 0.69001 | val 0.68956
  Classification -> best τ=0.555 (val F1=0.0433)
  Directional -> Accuracy: 0.4523, MCC: 0.0359, F1: 0.1138

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.68525 | val 0.70514
  Epoch 020 - train 0.67561 | val 0.95668
  Epoch 024 - train 0.67447 | val 0.81192
  Classification -> best τ=0.445 (val F1=0.0100)
  Directional -> Accuracy: 0.4434, MCC: -0.0988, F1: 0.3218

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69355 | val 0.70210
  Epoch 020 - train 0.69285 | val 0.69177
  Epoch 021 - train 0.69189 | val 0.69167
  Classification -> best τ=0.575 (val F1=0.0507)
  Directional -> Accuracy: 0.5477, MCC: -0.0283, F1: 0.7059

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69309 | val 0.77905
  Epoch 020 - train 0.69251 | val 0.68818
  Epoch 021 - train 0.69268 | val 0.68814
  Classification -> best τ=0.330 (val F1=0.1912)
  Directional -> Accuracy: 0.4874, MCC: 0.0242, F1: 0.4000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69516 | val 0.68988
  Epoch 020 - train 0.69189 | val 0.69020
  Epoch 027 - train 0.69154 | val 0.68938
  Classification -> best τ=0.515 (val F1=0.1560)
  Directional -> Accuracy: 0.5377, MCC: 0.0257, F1: 0.6230

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69831 | val 0.74030
  Epoch 020 - train 0.69793 | val 0.74346
  Epoch 029 - train 0.69351 | val 0.89343
  Classification -> best τ=0.505 (val F1=0.2298)
  Directional -> Accuracy: 0.4211, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69393 | val 1.62453
  Epoch 020 - train 0.69315 | val 2.57056
  Epoch 029 - train 0.69319 | val 0.69509
  Classification -> best τ=0.630 (val F1=0.1135)
  Directional -> Accuracy: 0.5377, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.69267 | val 0.70093
  Epoch 020 - train 0.69050 | val 0.70211
  Epoch 024 - train 0.69069 | val 0.70210
  Classification -> best τ=0.530 (val F1=0.0846)
  Directional -> Accuracy: 0.4523, MCC: -0.0520, F1: 0.0180

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.69519 | val 0.69214
  Epoch 020 - train 0.69273 | val 0.69328
  Epoch 022 - train 0.69299 | val 0.69331
  Classification -> best τ=0.510 (val F1=0.1003)
  Directional -> Accuracy: 0.5528, MCC: -0.0070, F1: 0.6877

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68968 | val 2.10223
  Epoch 020 - train 0.68868 | val 3.60246
  Epoch 022 - train 0.68884 | val 3.20778
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5628, MCC: 0.0000, F1: 0.7203

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69516 | val 0.69375
  Epoch 020 - train 0.68934 | val 0.69397
  Epoch 022 - train 0.69366 | val 0.69138
  Classification -> best τ=0.525 (val F1=0.1274)
  Directional -> Accuracy: 0.4774, MCC: -0.1087, F1: 0.0545

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.69416 | val 0.69317
  Epoch 020 - train 0.69430 | val 0.79941
  Epoch 021 - train 0.69368 | val 0.74685
  Classification -> best τ=0.455 (val F1=0.0431)
  Directional -> Accuracy: 0.4623, MCC: -0.1246, F1: 0.5804

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.69502 | val 0.70956
  Epoch 020 - train 0.69115 | val 0.69924
  Epoch 024 - train 0.69137 | val 0.69946
  Classification -> best τ=0.810 (val F1=0.1136)
  Directional -> Accuracy: 0.4975, MCC: -0.0017, F1: 0.1667

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.69124 | val 0.84820
  Epoch 020 - train 0.69118 | val 0.75954
  Epoch 022 - train 0.69055 | val 0.80352
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5578, MCC: 0.0000, F1: 0.7161

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69071 | val 0.68479
  Epoch 020 - train 0.70441 | val 0.75505
  Epoch 022 - train 0.69633 | val 0.71683
  Classification -> best τ=0.520 (val F1=0.2479)
  Directional -> Accuracy: 0.4874, MCC: 0.0369, F1: 0.0377

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68729 | val 1.03719
  Epoch 020 - train 0.69099 | val 0.70628
  Epoch 022 - train 0.69290 | val 0.69513
  Classification -> best τ=0.410 (val F1=0.2250)
  Directional -> Accuracy: 0.5075, MCC: 0.0211, F1: 0.3288

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69346 | val 0.69312
  Epoch 020 - train 0.69142 | val 0.69361
  Epoch 021 - train 0.69135 | val 0.69361
  Classification -> best τ=0.555 (val F1=0.0693)
  Directional -> Accuracy: 0.4573, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.69333 | val 0.78895
  Epoch 020 - train 0.69324 | val 0.69228
  Epoch 021 - train 0.69324 | val 0.69228
  Classification -> best τ=0.525 (val F1=0.1663)
  Directional -> Accuracy: 0.5126, MCC: 0.0310, F1: 0.5727

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.69623 | val 0.69317
  Epoch 020 - train 0.69363 | val 0.69282
  Epoch 026 - train 0.69325 | val 0.69285
  Classification -> best τ=0.505 (val F1=0.1331)
  Directional -> Accuracy: 0.5528, MCC: -0.0540, F1: 0.7101

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69376 | val 0.69161
  Epoch 020 - train 0.69072 | val 0.69102
  Epoch 021 - train 0.69083 | val 0.69102
  Classification -> best τ=0.535 (val F1=0.1540)
  Directional -> Accuracy: 0.5729, MCC: 0.1216, F1: 0.6586

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.69097 | val 0.72527
  Epoch 020 - train 0.68297 | val 0.71578
  Epoch 023 - train 0.68036 | val 0.75501
  Classification -> best τ=0.515 (val F1=0.1151)
  Directional -> Accuracy: 0.5829, MCC: -0.0077, F1: 0.1616

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69387 | val 0.69881
  Epoch 020 - train 0.69395 | val 0.69741
  Epoch 029 - train 0.69296 | val 0.69639
  Classification -> best τ=0.595 (val F1=0.0646)
  Directional -> Accuracy: 0.4774, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69449 | val 0.69380
  Epoch 020 - train 0.69338 | val 0.69436
  Epoch 024 - train 0.69281 | val 0.69434
  Classification -> best τ=0.530 (val F1=0.0666)
  Directional -> Accuracy: 0.4824, MCC: -0.0873, F1: 0.1345

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69124 | val 0.70515
  Epoch 020 - train 0.69154 | val 0.68916
  Epoch 026 - train 0.67950 | val 1.02364
  Classification -> best τ=0.505 (val F1=0.1364)
  Directional -> Accuracy: 0.5126, MCC: 0.0256, F1: 0.5314

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.69181 | val 0.69033
  Epoch 020 - train 0.69339 | val 0.69112
  Epoch 021 - train 0.69200 | val 0.69473
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.6644

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68549 | val 0.70661
  Epoch 020 - train 0.68586 | val 1.39329
  Epoch 022 - train 0.68665 | val 1.34504
  Classification -> best τ=0.420 (val F1=0.0677)
  Directional -> Accuracy: 0.5025, MCC: -0.0295, F1: 0.6526

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.69639 | val 0.69047
  Epoch 020 - train 0.69155 | val 0.69006
  Epoch 021 - train 0.69107 | val 0.69003
  Classification -> best τ=0.515 (val F1=0.0206)
  Directional -> Accuracy: 0.5226, MCC: -0.0630, F1: 0.6780

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.69873 | val 0.69500
  Epoch 020 - train 0.69396 | val 0.69397
  Epoch 023 - train 0.69307 | val 0.68995
  Classification -> best τ=0.685 (val F1=0.1365)
  Directional -> Accuracy: 0.4975, MCC: 0.0700, F1: 0.0196

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69237 | val 0.68882
  Epoch 020 - train 0.69126 | val 0.68894
  Epoch 027 - train 0.69075 | val 0.68880
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5528, MCC: 0.0000, F1: 0.7120

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.69289 | val 0.69167
  Epoch 020 - train 0.69220 | val 0.69166
  Epoch 024 - train 0.69221 | val 0.69165
  Classification -> best τ=0.490 (val F1=0.1355)
  Directional -> Accuracy: 0.4070, MCC: 0.0993, F1: 0.0484

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69327 | val 0.69333
  Epoch 020 - train 0.69292 | val 0.69382
  Epoch 021 - train 0.69294 | val 0.69378
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4472, MCC: 0.0000, F1: 0.6181

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.74025 | val 0.76290
  Epoch 020 - train 0.65388 | val 0.85136
  Epoch 022 - train 0.63438 | val 1.40068
  Classification -> best τ=0.460 (val F1=0.1409)
  Directional -> Accuracy: 0.4894, MCC: -0.0045, F1: 0.6471

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69446 | val 0.69110
  Epoch 020 - train 0.69594 | val 0.69307
  Epoch 024 - train 0.69312 | val 0.69306
  Classification -> best τ=0.535 (val F1=0.1511)
  Directional -> Accuracy: 0.4372, MCC: 0.0180, F1: 0.1642

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69015 | val 0.69299
  Epoch 020 - train 0.68879 | val 0.69022
  Epoch 025 - train 0.69000 | val 0.69698
  Classification -> best τ=0.620 (val F1=0.1800)
  Directional -> Accuracy: 0.4673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.69399 | val 0.68966
  Epoch 020 - train 0.69300 | val 0.68956
  Epoch 022 - train 0.69114 | val 0.68983
  Classification -> best τ=0.520 (val F1=0.0970)
  Directional -> Accuracy: 0.4975, MCC: 0.0667, F1: 0.3976

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.69393 | val 0.69336
  Epoch 020 - train 0.69347 | val 0.69506
  Epoch 021 - train 0.69340 | val 0.69501
  Classification -> best τ=0.325 (val F1=0.0806)
  Directional -> Accuracy: 0.5427, MCC: 0.0000, F1: 0.7036

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.70036 | val 0.70576
  Epoch 020 - train 0.69386 | val 0.69713
  Epoch 030 - train 0.69227 | val 0.69287
  Epoch 031 - train 0.69384 | val 0.69307
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5276, MCC: 0.0000, F1: 0.6908

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.69528 | val 0.69940
  Epoch 020 - train 0.69347 | val 0.69321
  Epoch 024 - train 0.69349 | val 0.69321
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5176, MCC: 0.0000, F1: 0.6821

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69422 | val 0.68509
  Epoch 020 - train 0.69367 | val 0.69091
  Epoch 026 - train 0.69345 | val 0.68704
  Classification -> best τ=0.510 (val F1=0.0138)
  Directional -> Accuracy: 0.5427, MCC: 0.0000, F1: 0.7036

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69064 | val 0.69438
  Epoch 020 - train 0.68999 | val 0.68888
  Epoch 021 - train 0.68887 | val 0.68728
  Classification -> best τ=0.490 (val F1=0.1087)
  Directional -> Accuracy: 0.4925, MCC: -0.0585, F1: 0.6406

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69243 | val 0.69391
  Epoch 020 - train 0.69194 | val 0.69310
  Epoch 022 - train 0.69169 | val 0.69265
  Classification -> best τ=0.505 (val F1=0.1538)
  Directional -> Accuracy: 0.5377, MCC: 0.1398, F1: 0.3333

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69329 | val 0.69167
  Epoch 020 - train 0.69372 | val 0.69357
  Epoch 030 - train 0.69331 | val 0.69220
  Epoch 037 - train 0.69331 | val 0.69711
  Classification -> best τ=0.495 (val F1=0.1988)
  Directional -> Accuracy: 0.5427, MCC: 0.0657, F1: 0.6160

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68958 | val 0.68800
  Epoch 020 - train 0.68848 | val 0.68893
  Epoch 025 - train 0.68766 | val 0.68858
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5879, MCC: 0.0000, F1: 0.7405

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69046 | val 0.71316
  Epoch 020 - train 0.69006 | val 0.68550
  Epoch 023 - train 0.69022 | val 0.68550
  Classification -> best τ=0.580 (val F1=0.1155)
  Directional -> Accuracy: 0.5628, MCC: 0.0000, F1: 0.7203

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69129 | val 0.69125
  Epoch 020 - train 0.69095 | val 0.69102
  Epoch 023 - train 0.69086 | val 0.69101
  Classification -> best τ=0.525 (val F1=0.0544)
  Directional -> Accuracy: 0.4472, MCC: -0.0176, F1: 0.3750

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69279 | val 0.68860
  Epoch 020 - train 0.69157 | val 0.68862
  Epoch 023 - train 0.69055 | val 0.68841
  Classification -> best τ=0.530 (val F1=0.1379)
  Directional -> Accuracy: 0.4925, MCC: -0.0389, F1: 0.2519

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68494 | val 0.69582
  Epoch 020 - train 0.68275 | val 0.69227
  Epoch 024 - train 0.68602 | val 0.70198
  Classification -> best τ=0.510 (val F1=0.0069)
  Directional -> Accuracy: 0.4824, MCC: -0.0620, F1: 0.5541

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69253 | val 0.68689
  Epoch 020 - train 0.69155 | val 0.68775
  Epoch 021 - train 0.69156 | val 0.68777
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5578, MCC: 0.0000, F1: 0.7161

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69568 | val 0.69358
  Epoch 020 - train 0.69323 | val 0.69589
  Epoch 024 - train 0.69341 | val 0.69310
  Classification -> best τ=0.535 (val F1=0.0939)
  Directional -> Accuracy: 0.4874, MCC: -0.0721, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69636 | val 0.69246
  Epoch 020 - train 0.69371 | val 0.69265
  Epoch 022 - train 0.69323 | val 0.69247
  Classification -> best τ=0.515 (val F1=0.0496)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.68981 | val 0.71239
  Epoch 020 - train 0.68628 | val 0.68983
  Epoch 022 - train 0.68768 | val 0.68981
  Classification -> best τ=0.575 (val F1=0.0653)
  Directional -> Accuracy: 0.4573, MCC: 0.0854, F1: 0.2603

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.69451 | val 0.69308
  Epoch 020 - train 0.69225 | val 0.69320
  Epoch 024 - train 0.69220 | val 0.69024
  Classification -> best τ=0.455 (val F1=0.1632)
  Directional -> Accuracy: 0.4925, MCC: -0.0714, F1: 0.6599

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.69323 | val 4.35038
  Epoch 020 - train 0.69325 | val 5.20909
  Epoch 023 - train 0.68948 | val 11.17291
  Classification -> best τ=0.415 (val F1=0.1306)
  Directional -> Accuracy: 0.5477, MCC: 0.0843, F1: 0.6341

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69380 | val 0.69324
  Epoch 020 - train 0.69294 | val 0.69349
  Epoch 022 - train 0.69186 | val 0.69323
  Classification -> best τ=0.410 (val F1=0.1181)
  Directional -> Accuracy: 0.5126, MCC: 0.0875, F1: 0.3822

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.68942 | val 1.19204
  Epoch 020 - train 0.68888 | val 0.81795
  Epoch 021 - train 0.68858 | val 0.83973
  Classification -> best τ=0.475 (val F1=0.2017)
  Directional -> Accuracy: 0.5075, MCC: 0.0614, F1: 0.3194

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69465 | val 0.69253
  Epoch 020 - train 0.69311 | val 0.69229
  Epoch 025 - train 0.69311 | val 0.69217
  Classification -> best τ=0.515 (val F1=0.1408)
  Directional -> Accuracy: 0.4171, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69409 | val 0.69063
  Epoch 020 - train 0.69117 | val 1.18029
  Epoch 023 - train 0.68953 | val 0.91159
  Classification -> best τ=0.515 (val F1=0.0474)
  Directional -> Accuracy: 0.4774, MCC: 0.0379, F1: 0.0877

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69948 | val 0.69803
  Epoch 020 - train 0.69304 | val 0.69354
  Epoch 029 - train 0.69345 | val 0.72105
  Classification -> best τ=0.620 (val F1=0.0963)
  Directional -> Accuracy: 0.5226, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69400 | val 0.70091
  Epoch 020 - train 0.69193 | val 0.71313
  Epoch 024 - train 0.68846 | val 0.71646
  Classification -> best τ=0.525 (val F1=0.0920)
  Directional -> Accuracy: 0.4623, MCC: -0.0828, F1: 0.5202

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.69561 | val 0.69101
  Epoch 020 - train 0.69244 | val 0.70580
  Epoch 023 - train 0.69238 | val 0.69115
  Classification -> best τ=0.420 (val F1=0.0398)
  Directional -> Accuracy: 0.5276, MCC: -0.0666, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...

[I 2026-02-25 23:14:36,495] Trial 10 finished with value: 0.10091984391557308 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.009985689275850883, 'weight_decay': 8.237582009251466e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.14324476777849116, 'early_stopping_min_delta': 0.009662377103203872}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 025 - train 0.69191 | val 0.69776
  Classification -> best τ=0.460 (val F1=0.1863)
  Directional -> Accuracy: 0.4925, MCC: -0.0035, F1: 0.6481

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.10091984391557308
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68002 | val 1.07393
  Epoch 020 - train 0.61345 | val 1.60696
  Epoch 026 - train 0.58666 | val 1.80428
  Classification -> best τ=0.155 (val F1=0.1416)
  Directional -> Accuracy: 0.4500, MCC: 0.0358, F1: 0.2361

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.64329 | val 3.55788
  Epoch 020 - train 0.51322 | val 6.13322
  Epoch 021 - train 0.48404 | val 8.51830
  Classification -> best τ=0.130 (val F1=0.1193)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64706 | val 1.46370
  Epoch 020 - train 0.54979 | val 2.05284
  Epoch 021 - train 0.54411 | val 2.72410
  Classification -> best τ=0.235 (val F1=0.1892)
  Directional -> Accuracy: 0.5508, MCC: -0.0028, F1: 0.6818

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.67877 | val 0.68856
  Epoch 020 - train 0.62087 | val 0.69320
  Epoch 030 - train 0.55777 | val 0.73090
  Classification -> best τ=0.580 (val F1=0.1458)
  Directional -> Accuracy: 0.4350, MCC: -0.0516, F1: 0.0342

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.63149 | val 0.76302
  Epoch 020 - train 0.50230 | val 0.87719
  Epoch 025 - train 0.45708 | val 0.98668
  Classification -> best τ=0.860 (val F1=0.1989)
  Directional -> Accuracy: 0.4766, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65849 | val 1.28339
  Epoch 020 - train 0.56094 | val 1.75867
  Epoch 027 - train 0.48514 | val 3.18668
  Classification -> best τ=0.755 (val F1=0.1219)
  Directional -> Accuracy: 0.4400, MCC: -0.0488, F1: 0.0820

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66937 | val 1.28301
  Epoch 020 - train 0.59375 | val 0.92878
  Epoch 021 - train 0.57064 | val 1.38577
  Classification -> best τ=0.460 (val F1=0.1735)
  Directional -> Accuracy: 0.5100, MCC: 0.0452, F1: 0.4896

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65637 | val 1.33726
  Epoch 020 - train 0.51560 | val 2.58730
  Epoch 021 - train 0.50258 | val 2.88351
  Classification -> best τ=0.215 (val F1=0.2261)
  Directional -> Accuracy: 0.4050, MCC: 0.0084, F1: 0.0775

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61136 | val 3.41938
  Epoch 020 - train 0.42603 | val 6.47139
  Epoch 021 - train 0.39484 | val 6.92129
  Classification -> best τ=0.090 (val F1=0.1867)
  Directional -> Accuracy: 0.4174, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66739 | val 1.00689
  Epoch 020 - train 0.54806 | val 2.00480
  Epoch 023 - train 0.51641 | val 1.91058
  Classification -> best τ=0.630 (val F1=0.1072)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.66600 | val 0.74337
  Epoch 020 - train 0.59474 | val 0.72478
  Epoch 021 - train 0.58415 | val 0.81473
  Classification -> best τ=0.565 (val F1=0.1610)
  Directional -> Accuracy: 0.5300, MCC: 0.0555, F1: 0.5607

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.66517 | val 0.75909
  Epoch 020 - train 0.55159 | val 0.90744
  Epoch 025 - train 0.51260 | val 1.10711
  Classification -> best τ=0.435 (val F1=0.1495)
  Directional -> Accuracy: 0.4450, MCC: 0.0062, F1: 0.2014

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66806 | val 1.23269
  Epoch 020 - train 0.59608 | val 1.05878
  Epoch 026 - train 0.54106 | val 0.94394
  Classification -> best τ=0.285 (val F1=0.1566)
  Directional -> Accuracy: 0.5100, MCC: 0.0105, F1: 0.5545

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64538 | val 1.36739
  Epoch 020 - train 0.55579 | val 3.20042
  Epoch 021 - train 0.54642 | val 2.70447
  Classification -> best τ=0.610 (val F1=0.1503)
  Directional -> Accuracy: 0.5150, MCC: 0.0604, F1: 0.0762

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.67903 | val 1.78500
  Epoch 020 - train 0.59449 | val 2.34030
  Epoch 025 - train 0.57554 | val 2.50982
  Classification -> best τ=0.380 (val F1=0.0892)
  Directional -> Accuracy: 0.4650, MCC: -0.0417, F1: 0.0360

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.65773 | val 1.15510
  Epoch 020 - train 0.55208 | val 2.08127
  Epoch 023 - train 0.50372 | val 3.30892
  Classification -> best τ=0.210 (val F1=0.1267)
  Directional -> Accuracy: 0.4950, MCC: -0.0126, F1: 0.6130

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.66118 | val 1.08845
  Epoch 020 - train 0.63833 | val 0.83402
  Epoch 030 - train 0.48002 | val 1.74935
  Classification -> best τ=0.205 (val F1=0.1248)
  Directional -> Accuracy: 0.5550, MCC: 0.0000, F1: 0.7138

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66519 | val 2.34001
  Epoch 020 - train 0.52497 | val 5.65889
  Epoch 021 - train 0.51783 | val 5.35021
  Classification -> best τ=0.830 (val F1=0.2096)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65381 | val 0.73923
  Epoch 020 - train 0.50160 | val 1.52434
  Epoch 024 - train 0.46464 | val 1.40705
  Classification -> best τ=0.435 (val F1=0.3063)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67897 | val 0.93416
  Epoch 020 - train 0.54666 | val 1.29815
  Epoch 021 - train 0.52103 | val 1.30360
  Classification -> best τ=0.480 (val F1=0.0808)
  Directional -> Accuracy: 0.5050, MCC: 0.1004, F1: 0.2667

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.67823 | val 1.05339
  Epoch 020 - train 0.56602 | val 1.54240
  Epoch 021 - train 0.53536 | val 1.74928
  Classification -> best τ=0.245 (val F1=0.1591)
  Directional -> Accuracy: 0.5000, MCC: 0.0470, F1: 0.6552

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.65860 | val 1.85967
  Epoch 020 - train 0.60782 | val 6.15038
  Epoch 021 - train 0.59852 | val 7.00101
  Classification -> best τ=0.690 (val F1=0.1568)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66100 | val 1.11202
  Epoch 020 - train 0.54271 | val 1.90891
  Epoch 021 - train 0.54153 | val 1.60035
  Classification -> best τ=0.290 (val F1=0.1497)
  Directional -> Accuracy: 0.5400, MCC: -0.0177, F1: 0.6974

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.67396 | val 0.98779
  Epoch 020 - train 0.53029 | val 1.55282
  Epoch 021 - train 0.54676 | val 2.13523
  Classification -> best τ=0.165 (val F1=0.1364)
  Directional -> Accuracy: 0.4050, MCC: 0.0812, F1: 0.5704

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64703 | val 1.22373
  Epoch 020 - train 0.55598 | val 4.25105
  Epoch 022 - train 0.49140 | val 4.79704
  Classification -> best τ=0.080 (val F1=0.1225)
  Directional -> Accuracy: 0.5600, MCC: 0.1138, F1: 0.6140

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67266 | val 1.12413
  Epoch 020 - train 0.65720 | val 0.91246
  Epoch 030 - train 0.63103 | val 1.73715
  Classification -> best τ=0.105 (val F1=0.1315)
  Directional -> Accuracy: 0.5700, MCC: 0.1510, F1: 0.6091

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67184 | val 0.74125
  Epoch 020 - train 0.59287 | val 0.83180
  Epoch 022 - train 0.54699 | val 1.18938
  Classification -> best τ=0.575 (val F1=0.1910)
  Directional -> Accuracy: 0.4700, MCC: 0.0348, F1: 0.0862

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.66946 | val 0.85897
  Epoch 020 - train 0.58552 | val 1.06985
  Epoch 022 - train 0.56240 | val 1.15441
  Classification -> best τ=0.455 (val F1=0.1248)
  Directional -> Accuracy: 0.5050, MCC: 0.0126, F1: 0.6207

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66552 | val 1.09042
  Epoch 020 - train 0.60405 | val 1.28636
  Epoch 021 - train 0.60385 | val 2.02622
  Classification -> best τ=0.850 (val F1=0.1517)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.66761 | val 0.69111
  Epoch 020 - train 0.63445 | val 0.84410
  Epoch 030 - train 0.45327 | val 3.13908
  Classification -> best τ=0.545 (val F1=0.1217)
  Directional -> Accuracy: 0.4400, MCC: -0.1105, F1: 0.0508

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.66813 | val 2.69114
  Epoch 020 - train 0.56789 | val 2.25876
  Epoch 021 - train 0.57002 | val 5.75552
  Classification -> best τ=0.385 (val F1=0.1313)
  Directional -> Accuracy: 0.5100, MCC: 0.0507, F1: 0.1695

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67232 | val 0.70456
  Epoch 020 - train 0.65406 | val 0.85048
  Epoch 030 - train 0.53480 | val 1.10792
  Classification -> best τ=0.555 (val F1=0.1326)
  Directional -> Accuracy: 0.4250, MCC: -0.1127, F1: 0.1727

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.66306 | val 1.95772
  Epoch 020 - train 0.61659 | val 2.47453
  Epoch 021 - train 0.59647 | val 2.46174
  Classification -> best τ=0.480 (val F1=0.2113)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64422 | val 0.74795
  Epoch 020 - train 0.55132 | val 1.05145
  Epoch 024 - train 0.51178 | val 1.19796
  Classification -> best τ=0.555 (val F1=0.1414)
  Directional -> Accuracy: 0.5800, MCC: 0.1245, F1: 0.4167

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.54818 | val 1.26384
  Epoch 020 - train 0.28851 | val 2.51761
  Epoch 022 - train 0.24356 | val 2.37096
  Classification -> best τ=0.405 (val F1=0.2116)
  Directional -> Accuracy: 0.4583, MCC: -0.1026, F1: 0.2353

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65617 | val 0.70105
  Epoch 020 - train 0.62353 | val 0.68527
  Epoch 030 - train 0.57245 | val 0.68577
  Classification -> best τ=0.535 (val F1=0.2306)
  Directional -> Accuracy: 0.4400, MCC: 0.1052, F1: 0.0968

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66708 | val 0.81894
  Epoch 020 - train 0.58969 | val 1.42075
  Epoch 026 - train 0.53939 | val 2.71965
  Classification -> best τ=0.795 (val F1=0.1848)
  Directional -> Accuracy: 0.4650, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.63990 | val 1.58245
  Epoch 020 - train 0.53835 | val 1.41149
  Epoch 021 - train 0.51189 | val 2.78293
  Classification -> best τ=0.100 (val F1=0.1378)
  Directional -> Accuracy: 0.5650, MCC: 0.0000, F1: 0.7220

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.65260 | val 3.43689
  Epoch 020 - train 0.55180 | val 3.00875
  Epoch 026 - train 0.47687 | val 4.90917
  Classification -> best τ=0.725 (val F1=0.0993)
  Directional -> Accuracy: 0.4550, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.68662 | val 0.86192
  Epoch 020 - train 0.57035 | val 1.12206
  Epoch 021 - train 0.54855 | val 1.19161
  Classification -> best τ=0.475 (val F1=0.1200)
  Directional -> Accuracy: 0.4850, MCC: 0.0167, F1: 0.1760

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.66676 | val 2.26374
  Epoch 020 - train 0.60022 | val 1.66298
  Epoch 021 - train 0.59232 | val 0.79652
  Classification -> best τ=0.595 (val F1=0.1061)
  Directional -> Accuracy: 0.5000, MCC: 0.0321, F1: 0.2308

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65360 | val 0.88706
  Epoch 020 - train 0.60773 | val 1.51384
  Epoch 022 - train 0.57926 | val 1.81176
  Classification -> best τ=0.255 (val F1=0.1765)
  Directional -> Accuracy: 0.5400, MCC: 0.0115, F1: 0.6974

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64971 | val 0.91524
  Epoch 020 - train 0.62080 | val 0.82964
  Epoch 030 - train 0.60580 | val 0.91462
  Classification -> best τ=0.555 (val F1=0.1401)
  Directional -> Accuracy: 0.4900, MCC: 0.0073, F1: 0.1639

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67815 | val 1.15426
  Epoch 020 - train 0.58612 | val 1.55609
  Epoch 021 - train 0.57591 | val 1.62838
  Classification -> best τ=0.825 (val F1=0.1538)
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64906 | val 1.20130
  Epoch 020 - train 0.60098 | val 1.77880
  Epoch 030 - train 0.46049 | val 3.43833
  Classification -> best τ=0.480 (val F1=0.0966)
  Directional -> Accuracy: 0.4700, MCC: -0.0034, F1: 0.1452

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66713 | val 0.92936
  Epoch 020 - train 0.65264 | val 0.94452
  Epoch 030 - train 0.63096 | val 0.93529
  Classification -> best τ=0.335 (val F1=0.0903)
  Directional -> Accuracy: 0.5350, MCC: 0.0022, F1: 0.6381

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64280 | val 0.90281
  Epoch 020 - train 0.56135 | val 1.40445
  Epoch 021 - train 0.53472 | val 0.94837
  Classification -> best τ=0.640 (val F1=0.0677)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65360 | val 0.78610
  Epoch 020 - train 0.58677 | val 0.74466
  Epoch 030 - train 0.42650 | val 1.88163
  Classification -> best τ=0.300 (val F1=0.0834)
  Directional -> Accuracy: 0.5100, MCC: -0.0343, F1: 0.6016

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66311 | val 0.89175
  Epoch 020 - train 0.59515 | val 1.27701
  Epoch 027 - train 0.52855 | val 1.92327
  Classification -> best τ=0.390 (val F1=0.1612)
  Directional -> Accuracy: 0.4900, MCC: -0.0055, F1: 0.6408

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66478 | val 0.81147
  Epoch 020 - train 0.59351 | val 1.96758
  Epoch 026 - train 0.54390 | val 1.40101
  Classification -> best τ=0.495 (val F1=0.0928)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67218 | val 1.02021
  Epoch 020 - train 0.57250 | val 1.71604
  Epoch 023 - train 0.54415 | val 2.41031
  Classification -> best τ=0.540 (val F1=0.1448)
  Directional -> Accuracy: 0.4150, MCC: -0.1225, F1: 0.1333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66607 | val 1.26004
  Epoch 020 - train 0.56416 | val 1.95911
  Epoch 021 - train 0.55659 | val 2.06050
  Classification -> best τ=0.190 (val F1=0.1246)
  Directional -> Accuracy: 0.5450, MCC: 0.0905, F1: 0.5381

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67173 | val 0.71537
  Epoch 020 - train 0.60404 | val 0.93355
  Epoch 027 - train 0.53020 | val 1.64927
  Classification -> best τ=0.545 (val F1=0.1267)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.66087 | val 0.75468
  Epoch 020 - train 0.61692 | val 1.18178
  Epoch 027 - train 0.51970 | val 1.93995
  Classification -> best τ=0.535 (val F1=0.1372)
  Directional -> Accuracy: 0.4050, MCC: -0.0444, F1: 0.0775

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.65353 | val 0.73166
  Epoch 020 - train 0.55795 | val 0.88915
  Epoch 026 - train 0.49040 | val 1.45463
  Classification -> best τ=0.495 (val F1=0.2326)
  Directional -> Accuracy: 0.5150, MCC: 0.0756, F1: 0.6596

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68128 | val 1.87761
  Epoch 020 - train 0.60924 | val 3.62276
  Epoch 022 - train 0.60341 | val 6.25273
  Classification -> best τ=0.490 (val F1=0.1020)
  Directional -> Accuracy: 0.6150, MCC: 0.2284, F1: 0.6831

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66273 | val 0.79428
  Epoch 020 - train 0.61088 | val 1.54452
  Epoch 030 - train 0.52823 | val 2.28727
  Classification -> best τ=0.835 (val F1=0.2041)
  Directional -> Accuracy: 0.4550, MCC: 0.0024, F1: 0.0840

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.67203 | val 0.69461
  Epoch 020 - train 0.64365 | val 0.69214
  Epoch 030 - train 0.57774 | val 0.68827
  Classification -> best τ=0.445 (val F1=0.1977)
  Directional -> Accuracy: 0.4850, MCC: -0.0204, F1: 0.4432

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63348 | val 1.43069
  Epoch 020 - train 0.53229 | val 1.41107
  Epoch 022 - train 0.49171 | val 1.98394
  Classification -> best τ=0.765 (val F1=0.1716)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65701 | val 0.79471
  Epoch 020 - train 0.62350 | val 1.00671
  Epoch 030 - train 0.43496 | val 1.21812
  Classification -> best τ=0.370 (val F1=0.1584)
  Directional -> Accuracy: 0.4950, MCC: 0.0027, F1: 0.4541

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65796 | val 1.29965
  Epoch 020 - train 0.55315 | val 3.45579
  Epoch 021 - train 0.54895 | val 4.08277
  Classification -> best τ=0.250 (val F1=0.1046)
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.6441

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66896 | val 0.82977
  Epoch 020 - train 0.51992 | val 1.69319
  Epoch 024 - train 0.46303 | val 2.08231
  Classification -> best τ=0.455 (val F1=0.2161)
  Directional -> Accuracy: 0.4800, MCC: -0.0412, F1: 0.1333

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.66454 | val 0.82356
  Epoch 020 - train 0.57998 | val 1.73255
  Epoch 027 - train 0.51284 | val 2.43643
  Classification -> best τ=0.565 (val F1=0.1147)
  Directional -> Accuracy: 0.5350, MCC: 0.0207, F1: 0.1468

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.66155 | val 4.31942
  Epoch 020 - train 0.50488 | val 2.24811

[I 2026-02-25 23:26:26,806] Trial 11 finished with value: 0.15132161179722775 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.007742829392503634, 'weight_decay': 1.0824754880018991e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.3164974123905577, 'early_stopping_min_delta': 0.00041704374154139933}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 021 - train 0.55885 | val 2.67383
  Classification -> best τ=0.740 (val F1=0.1150)
  Directional -> Accuracy: 0.5100, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.15132161179722775
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67120 | val 1.83728
  Epoch 020 - train 0.59930 | val 1.36893
  Epoch 022 - train 0.59042 | val 1.43622
  Classification -> best τ=0.740 (val F1=0.1137)
  Directional -> Accuracy: 0.4171, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.65055 | val 2.11533
  Epoch 020 - train 0.52386 | val 3.50538
  Epoch 021 - train 0.50460 | val 3.52467
  Classification -> best τ=0.250 (val F1=0.1501)
  Directional -> Accuracy: 0.5126, MCC: 0.0715, F1: 0.1101

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63532 | val 0.88185
  Epoch 020 - train 0.57426 | val 0.97856
  Epoch 021 - train 0.57269 | val 1.01273
  Classification -> best τ=0.485 (val F1=0.1704)
  Directional -> Accuracy: 0.3925, MCC: -0.1810, F1: 0.0342

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.64332 | val 0.96751
  Epoch 020 - train 0.54589 | val 0.93568
  Epoch 028 - train 0.37085 | val 0.86029
  Classification -> best τ=0.455 (val F1=0.1450)
  Directional -> Accuracy: 0.4573, MCC: -0.0069, F1: 0.2703

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.62413 | val 0.73142
  Epoch 020 - train 0.50716 | val 0.80406
  Epoch 030 - train 0.39235 | val 0.79455
  Epoch 031 - train 0.40595 | val 0.83773
  Classification -> best τ=0.855 (val F1=0.2027)
  Directional -> Accuracy: 0.4340, MCC: -0.1222, F1: 0.2308

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66042 | val 0.96191
  Epoch 020 - train 0.55056 | val 1.29389
  Epoch 024 - train 0.49310 | val 1.53185
  Classification -> best τ=0.655 (val F1=0.1064)
  Directional -> Accuracy: 0.4774, MCC: 0.0654, F1: 0.2000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64377 | val 1.14763
  Epoch 020 - train 0.55757 | val 2.05156
  Epoch 021 - train 0.55315 | val 2.31268
  Classification -> best τ=0.440 (val F1=0.1475)
  Directional -> Accuracy: 0.4925, MCC: 0.1397, F1: 0.2171

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62662 | val 1.09010
  Epoch 020 - train 0.48906 | val 1.38293
  Epoch 021 - train 0.48061 | val 1.59436
  Classification -> best τ=0.080 (val F1=0.2602)
  Directional -> Accuracy: 0.6030, MCC: 0.1073, F1: 0.7127

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63291 | val 1.56813
  Epoch 020 - train 0.46391 | val 1.50904
  Epoch 021 - train 0.43823 | val 1.82146
  Classification -> best τ=0.535 (val F1=0.1836)
  Directional -> Accuracy: 0.4211, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64875 | val 1.33400
  Epoch 020 - train 0.53389 | val 2.14211
  Epoch 022 - train 0.51473 | val 1.87050
  Classification -> best τ=0.420 (val F1=0.0078)
  Directional -> Accuracy: 0.4724, MCC: -0.0428, F1: 0.4976

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.66403 | val 0.71131
  Epoch 020 - train 0.58265 | val 0.95005
  Epoch 029 - train 0.46342 | val 0.97512
  Classification -> best τ=0.620 (val F1=0.2230)
  Directional -> Accuracy: 0.5075, MCC: 0.0364, F1: 0.4674

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.63826 | val 0.89706
  Epoch 020 - train 0.56142 | val 0.79451
  Epoch 023 - train 0.54800 | val 0.84304
  Classification -> best τ=0.455 (val F1=0.1356)
  Directional -> Accuracy: 0.4472, MCC: 0.0170, F1: 0.2143

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65003 | val 0.92198
  Epoch 020 - train 0.52161 | val 1.41209
  Epoch 021 - train 0.50458 | val 1.14841
  Classification -> best τ=0.355 (val F1=0.1306)
  Directional -> Accuracy: 0.5226, MCC: 0.0412, F1: 0.5581

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62553 | val 1.30322
  Epoch 020 - train 0.51073 | val 1.60037
  Epoch 021 - train 0.50169 | val 1.54613
  Classification -> best τ=0.145 (val F1=0.1754)
  Directional -> Accuracy: 0.5025, MCC: 0.0406, F1: 0.6644

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.66829 | val 0.81423
  Epoch 020 - train 0.57656 | val 1.23864
  Epoch 021 - train 0.54873 | val 1.41031
  Classification -> best τ=0.275 (val F1=0.0466)
  Directional -> Accuracy: 0.5427, MCC: 0.0859, F1: 0.5561

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.62834 | val 1.06737
  Epoch 020 - train 0.49618 | val 2.19865
  Epoch 026 - train 0.42487 | val 2.89214
  Classification -> best τ=0.485 (val F1=0.1195)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.65929 | val 0.92380
  Epoch 020 - train 0.56212 | val 1.10274
  Epoch 024 - train 0.51024 | val 1.16444
  Classification -> best τ=0.335 (val F1=0.1306)
  Directional -> Accuracy: 0.5578, MCC: 0.0000, F1: 0.7161

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61745 | val 3.43745
  Epoch 020 - train 0.52431 | val 7.16147
  Epoch 021 - train 0.50834 | val 6.08576
  Classification -> best τ=0.885 (val F1=0.0475)
  Directional -> Accuracy: 0.4824, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66325 | val 0.75307
  Epoch 020 - train 0.50667 | val 0.90005
  Epoch 026 - train 0.44752 | val 1.22311
  Classification -> best τ=0.360 (val F1=0.2862)
  Directional -> Accuracy: 0.4975, MCC: -0.0009, F1: 0.0566

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62519 | val 1.19015
  Epoch 020 - train 0.52026 | val 1.72776
  Epoch 021 - train 0.49260 | val 2.00816
  Classification -> best τ=0.580 (val F1=0.1459)
  Directional -> Accuracy: 0.4573, MCC: -0.0254, F1: 0.1290

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.65965 | val 0.94838
  Epoch 020 - train 0.53263 | val 1.21650
  Epoch 021 - train 0.51759 | val 1.30700
  Classification -> best τ=0.725 (val F1=0.1478)
  Directional -> Accuracy: 0.5377, MCC: 0.1065, F1: 0.6434

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.67044 | val 0.71005
  Epoch 020 - train 0.55170 | val 0.78679
  Epoch 023 - train 0.52668 | val 0.98653
  Classification -> best τ=0.505 (val F1=0.1440)
  Directional -> Accuracy: 0.4372, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64186 | val 0.82687
  Epoch 020 - train 0.51479 | val 1.15340
  Epoch 021 - train 0.51389 | val 1.17520
  Classification -> best τ=0.755 (val F1=0.1242)
  Directional -> Accuracy: 0.4573, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.60790 | val 1.07220
  Epoch 020 - train 0.47978 | val 1.22838
  Epoch 021 - train 0.47662 | val 1.15468
  Classification -> best τ=0.735 (val F1=0.1275)
  Directional -> Accuracy: 0.5980, MCC: -0.0416, F1: 0.0244

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63952 | val 1.08296
  Epoch 020 - train 0.50771 | val 1.06010
  Epoch 025 - train 0.45980 | val 1.18325
  Classification -> best τ=0.250 (val F1=0.1484)
  Directional -> Accuracy: 0.5578, MCC: 0.1109, F1: 0.5926

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63833 | val 0.95861
  Epoch 020 - train 0.57570 | val 1.02968
  Epoch 026 - train 0.48393 | val 1.27220
  Classification -> best τ=0.130 (val F1=0.1663)
  Directional -> Accuracy: 0.5226, MCC: 0.0575, F1: 0.5887

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62165 | val 1.44679
  Epoch 020 - train 0.50514 | val 2.38501
  Epoch 021 - train 0.52292 | val 2.37833
  Classification -> best τ=0.290 (val F1=0.1122)
  Directional -> Accuracy: 0.5377, MCC: 0.0173, F1: 0.6738

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.63757 | val 0.94471
  Epoch 020 - train 0.53560 | val 2.42060
  Epoch 021 - train 0.54107 | val 2.00638
  Classification -> best τ=0.585 (val F1=0.1057)
  Directional -> Accuracy: 0.4975, MCC: -0.0313, F1: 0.0385

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65236 | val 1.31752
  Epoch 020 - train 0.56593 | val 2.21159
  Epoch 021 - train 0.56954 | val 1.97410
  Classification -> best τ=0.835 (val F1=0.1529)
  Directional -> Accuracy: 0.4925, MCC: 0.0693, F1: 0.0194

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.63759 | val 1.23826
  Epoch 020 - train 0.49645 | val 1.97492
  Epoch 022 - train 0.48609 | val 2.07416
  Classification -> best τ=0.270 (val F1=0.1312)
  Directional -> Accuracy: 0.5528, MCC: 0.0624, F1: 0.6877

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.63950 | val 1.93477
  Epoch 020 - train 0.49110 | val 3.00791
  Epoch 024 - train 0.43936 | val 2.92025
  Classification -> best τ=0.445 (val F1=0.1879)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64212 | val 0.76738
  Epoch 020 - train 0.56964 | val 1.27441
  Epoch 021 - train 0.56523 | val 1.16980
  Classification -> best τ=0.590 (val F1=0.1390)
  Directional -> Accuracy: 0.4322, MCC: -0.0868, F1: 0.1871

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.66248 | val 0.83372
  Epoch 020 - train 0.57828 | val 1.04666
  Epoch 023 - train 0.56264 | val 1.00491
  Classification -> best τ=0.220 (val F1=0.1308)
  Directional -> Accuracy: 0.6080, MCC: 0.0000, F1: 0.7562

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65193 | val 0.75059
  Epoch 020 - train 0.55308 | val 0.97633
  Epoch 024 - train 0.52586 | val 1.35148
  Classification -> best τ=0.520 (val F1=0.0909)
  Directional -> Accuracy: 0.5377, MCC: 0.0840, F1: 0.5306

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.50347 | val 1.48049
  Epoch 020 - train 0.45247 | val 1.54464
  Epoch 021 - train 0.39439 | val 1.48826
  Classification -> best τ=0.440 (val F1=0.2236)
  Directional -> Accuracy: 0.5745, MCC: 0.1515, F1: 0.4737

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63067 | val 0.70783
  Epoch 020 - train 0.53668 | val 0.86477
  Epoch 030 - train 0.39299 | val 1.48085
  Classification -> best τ=0.590 (val F1=0.1790)
  Directional -> Accuracy: 0.4372, MCC: 0.0334, F1: 0.1385

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64406 | val 1.17497
  Epoch 020 - train 0.52483 | val 2.98658
  Epoch 022 - train 0.48910 | val 2.70448
  Classification -> best τ=0.830 (val F1=0.1876)
  Directional -> Accuracy: 0.4673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.63143 | val 0.94048
  Epoch 020 - train 0.50571 | val 1.14171
  Epoch 021 - train 0.49044 | val 1.04793
  Classification -> best τ=0.295 (val F1=0.1362)
  Directional -> Accuracy: 0.5678, MCC: 0.0000, F1: 0.7244

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.63906 | val 1.09223
  Epoch 020 - train 0.49325 | val 1.13548
  Epoch 023 - train 0.46824 | val 1.12885
  Classification -> best τ=0.700 (val F1=0.0530)
  Directional -> Accuracy: 0.4573, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.66256 | val 0.85062
  Epoch 020 - train 0.55823 | val 1.08778
  Epoch 022 - train 0.53277 | val 1.06800
  Classification -> best τ=0.670 (val F1=0.1184)
  Directional -> Accuracy: 0.4724, MCC: 0.0000, F1: 0.0000

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.64340 | val 0.85311
  Epoch 020 - train 0.47936 | val 2.00124
  Epoch 024 - train 0.46966 | val 1.62620
  Classification -> best τ=0.310 (val F1=0.0723)
  Directional -> Accuracy: 0.5176, MCC: 0.0000, F1: 0.6821

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65247 | val 1.14190
  Epoch 020 - train 0.58932 | val 1.56015
  Epoch 021 - train 0.57719 | val 1.52454
  Classification -> best τ=0.215 (val F1=0.0978)
  Directional -> Accuracy: 0.5528, MCC: 0.0689, F1: 0.7023

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62500 | val 1.07237
  Epoch 020 - train 0.52176 | val 1.31012
  Epoch 021 - train 0.51822 | val 1.11425
  Classification -> best τ=0.365 (val F1=0.1460)
  Directional -> Accuracy: 0.5025, MCC: 0.0499, F1: 0.1538

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63732 | val 1.15546
  Epoch 020 - train 0.53439 | val 2.09750
  Epoch 021 - train 0.54989 | val 1.80066
  Classification -> best τ=0.675 (val F1=0.1299)
  Directional -> Accuracy: 0.4774, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63682 | val 1.40768
  Epoch 020 - train 0.51012 | val 1.94309
  Epoch 021 - train 0.51274 | val 2.47565
  Classification -> best τ=0.235 (val F1=0.1572)
  Directional -> Accuracy: 0.5226, MCC: -0.0170, F1: 0.6619

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63379 | val 1.10357
  Epoch 020 - train 0.56459 | val 1.34241
  Epoch 024 - train 0.51170 | val 1.30065
  Classification -> best τ=0.810 (val F1=0.1124)
  Directional -> Accuracy: 0.4121, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63859 | val 0.82454
  Epoch 020 - train 0.55076 | val 1.13127
  Epoch 023 - train 0.53228 | val 1.10804
  Classification -> best τ=0.680 (val F1=0.1411)
  Directional -> Accuracy: 0.4372, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61206 | val 1.62494
  Epoch 020 - train 0.52435 | val 1.96418
  Epoch 030 - train 0.33686 | val 3.21901
  Epoch 031 - train 0.34806 | val 3.23072
  Classification -> best τ=0.815 (val F1=0.1314)
  Directional -> Accuracy: 0.3970, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63708 | val 1.22675
  Epoch 020 - train 0.54574 | val 1.83093
  Epoch 021 - train 0.53271 | val 1.83575
  Classification -> best τ=0.610 (val F1=0.1415)
  Directional -> Accuracy: 0.4824, MCC: -0.0972, F1: 0.1043

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63069 | val 0.84746
  Epoch 020 - train 0.51163 | val 1.48498
  Epoch 024 - train 0.45920 | val 1.83860
  Classification -> best τ=0.525 (val F1=0.0863)
  Directional -> Accuracy: 0.5829, MCC: 0.1020, F1: 0.7025

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66632 | val 0.73305
  Epoch 020 - train 0.59057 | val 0.95910
  Epoch 030 - train 0.39695 | val 1.16767
  Epoch 032 - train 0.37043 | val 1.16087
  Classification -> best τ=0.335 (val F1=0.1132)
  Directional -> Accuracy: 0.5578, MCC: 0.0167, F1: 0.7124

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62910 | val 0.83663
  Epoch 020 - train 0.53036 | val 1.46475
  Epoch 021 - train 0.52019 | val 1.70401
  Classification -> best τ=0.430 (val F1=0.1667)
  Directional -> Accuracy: 0.5226, MCC: 0.0430, F1: 0.5701

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65232 | val 0.75446
  Epoch 020 - train 0.59168 | val 0.77603
  Epoch 030 - train 0.41711 | val 0.97159
  Epoch 032 - train 0.37525 | val 1.05389
  Classification -> best τ=0.620 (val F1=0.1342)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.63822 | val 0.90352
  Epoch 020 - train 0.51159 | val 1.12261
  Epoch 022 - train 0.50597 | val 1.30245
  Classification -> best τ=0.305 (val F1=0.1444)
  Directional -> Accuracy: 0.5678, MCC: 0.0189, F1: 0.6929

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.63209 | val 1.01561
  Epoch 020 - train 0.53543 | val 1.06271
  Epoch 021 - train 0.49547 | val 1.14018
  Classification -> best τ=0.275 (val F1=0.1870)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.6644

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64298 | val 2.64255
  Epoch 020 - train 0.54710 | val 3.30728
  Epoch 021 - train 0.54994 | val 3.83199
  Classification -> best τ=0.220 (val F1=0.1383)
  Directional -> Accuracy: 0.5176, MCC: -0.0111, F1: 0.6712

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64363 | val 0.86386
  Epoch 020 - train 0.54236 | val 0.99470
  Epoch 021 - train 0.53942 | val 1.07851
  Classification -> best τ=0.715 (val F1=0.0932)
  Directional -> Accuracy: 0.4422, MCC: -0.0857, F1: 0.0177

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.63324 | val 1.11161
  Epoch 020 - train 0.51396 | val 1.46292
  Epoch 027 - train 0.40668 | val 1.94127
  Classification -> best τ=0.365 (val F1=0.1563)
  Directional -> Accuracy: 0.5377, MCC: 0.1375, F1: 0.3611

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63052 | val 1.15747
  Epoch 020 - train 0.53823 | val 1.60924
  Epoch 022 - train 0.51350 | val 1.72296
  Classification -> best τ=0.575 (val F1=0.2196)
  Directional -> Accuracy: 0.4171, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63595 | val 0.85640
  Epoch 020 - train 0.49114 | val 1.27040
  Epoch 023 - train 0.44278 | val 1.11593
  Classification -> best τ=0.430 (val F1=0.1558)
  Directional -> Accuracy: 0.5075, MCC: 0.0739, F1: 0.3099

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61499 | val 1.86420
  Epoch 020 - train 0.51765 | val 1.78536
  Epoch 021 - train 0.49710 | val 2.00175
  Classification -> best τ=0.150 (val F1=0.1294)
  Directional -> Accuracy: 0.4774, MCC: -0.0080, F1: 0.6389

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62581 | val 1.83292
  Epoch 020 - train 0.51649 | val 2.22689
  Epoch 021 - train 0.50438 | val 1.92553
  Classification -> best τ=0.135 (val F1=0.1281)
  Directional -> Accuracy: 0.4523, MCC: -0.1044, F1: 0.5156

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.63773 | val 1.57331
  Epoch 020 - train 0.52710 | val 1.87388
  Epoch 021 - train 0.49385 | val 2.32859
  Classification -> best τ=0.560 (val F1=0.1305)
  Directional -> Accuracy: 0.5327, MCC: 0.0000, F1: 0.0000


[I 2026-02-25 23:44:14,849] Trial 12 finished with value: 0.14426815975321963 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 16, 'learning_rate': 0.0021733608548059227, 'weight_decay': 1.0724896892295657e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.2913294631937386, 'early_stopping_min_delta': 0.00025129308082111817}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 021 - train 0.54910 | val 1.26173
  Classification -> best τ=0.555 (val F1=0.1229)
  Directional -> Accuracy: 0.5075, MCC: 0.0068, F1: 0.2576

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14426815975321963
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64891 | val 1.08468
  Epoch 020 - train 0.58260 | val 1.20584
  Epoch 022 - train 0.59822 | val 1.06057
  Classification -> best τ=0.125 (val F1=0.1391)
  Directional -> Accuracy: 0.4350, MCC: -0.0280, F1: 0.2614

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.60600 | val 4.67841
  Epoch 020 - train 0.48956 | val 5.66305
  Epoch 021 - train 0.47793 | val 5.68036
  Classification -> best τ=0.060 (val F1=0.1380)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.1379

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63334 | val 0.73996
  Epoch 020 - train 0.58264 | val 0.94210
  Epoch 021 - train 0.56337 | val 0.98830
  Classification -> best τ=0.290 (val F1=0.1911)
  Directional -> Accuracy: 0.5187, MCC: -0.0509, F1: 0.6400

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.66163 | val 0.75424
  Epoch 020 - train 0.58936 | val 0.74990
  Epoch 030 - train 0.45967 | val 0.85946
  Epoch 036 - train 0.41469 | val 0.91904
  Classification -> best τ=0.330 (val F1=0.1210)
  Directional -> Accuracy: 0.5100, MCC: -0.0465, F1: 0.6260

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.61578 | val 1.23677
  Epoch 020 - train 0.51043 | val 1.36967
  Epoch 021 - train 0.52485 | val 1.23625
  Classification -> best τ=0.690 (val F1=0.2235)
  Directional -> Accuracy: 0.4766, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64917 | val 1.07468
  Epoch 020 - train 0.53335 | val 1.84637
  Epoch 021 - train 0.51752 | val 1.79428
  Classification -> best τ=0.785 (val F1=0.1052)
  Directional -> Accuracy: 0.4450, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65659 | val 1.43835
  Epoch 020 - train 0.58555 | val 3.01896
  Epoch 021 - train 0.57642 | val 2.82583
  Classification -> best τ=0.360 (val F1=0.1715)
  Directional -> Accuracy: 0.5750, MCC: 0.0910, F1: 0.7119

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62784 | val 0.98539
  Epoch 020 - train 0.54863 | val 1.49779
  Epoch 023 - train 0.53500 | val 1.48307
  Classification -> best τ=0.300 (val F1=0.2872)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62347 | val 3.60604
  Epoch 020 - train 0.49761 | val 4.20683
  Epoch 021 - train 0.47075 | val 3.90003
  Classification -> best τ=0.130 (val F1=0.2258)
  Directional -> Accuracy: 0.5043, MCC: 0.0698, F1: 0.4571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64026 | val 1.45584
  Epoch 020 - train 0.56208 | val 1.75331
  Epoch 021 - train 0.58086 | val 1.54813
  Classification -> best τ=0.695 (val F1=0.0486)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.65431 | val 0.73810
  Epoch 020 - train 0.53929 | val 0.89474
  Epoch 025 - train 0.50691 | val 1.01657
  Classification -> best τ=0.665 (val F1=0.1470)
  Directional -> Accuracy: 0.4500, MCC: -0.0652, F1: 0.2568

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.65586 | val 0.84466
  Epoch 020 - train 0.60501 | val 0.90660
  Epoch 030 - train 0.47747 | val 1.32025
  Epoch 034 - train 0.44698 | val 1.24618
  Classification -> best τ=0.930 (val F1=0.1593)
  Directional -> Accuracy: 0.4350, MCC: 0.0326, F1: 0.0661

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62951 | val 1.16475
  Epoch 020 - train 0.55299 | val 1.64266
  Epoch 029 - train 0.40914 | val 2.10181
  Classification -> best τ=0.790 (val F1=0.1508)
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63427 | val 1.11104
  Epoch 020 - train 0.50634 | val 2.52494
  Epoch 021 - train 0.51052 | val 2.63116
  Classification -> best τ=0.820 (val F1=0.2030)
  Directional -> Accuracy: 0.5000, MCC: -0.0702, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.67570 | val 1.05750
  Epoch 020 - train 0.61261 | val 1.56530
  Epoch 021 - train 0.59544 | val 1.88858
  Classification -> best τ=0.095 (val F1=0.1134)
  Directional -> Accuracy: 0.4950, MCC: -0.0617, F1: 0.6245

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.63712 | val 1.33441
  Epoch 020 - train 0.54958 | val 2.07275
  Epoch 021 - train 0.54599 | val 2.18416
  Classification -> best τ=0.580 (val F1=0.1899)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.63610 | val 1.05950
  Epoch 020 - train 0.53738 | val 1.64287
  Epoch 021 - train 0.52571 | val 1.44008
  Classification -> best τ=0.310 (val F1=0.1520)
  Directional -> Accuracy: 0.5550, MCC: 0.0000, F1: 0.7138

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63779 | val 1.09889
  Epoch 020 - train 0.51705 | val 1.35813
  Epoch 028 - train 0.37717 | val 2.81256
  Classification -> best τ=0.275 (val F1=0.0776)
  Directional -> Accuracy: 0.5150, MCC: 0.0954, F1: 0.1983

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63759 | val 0.77529
  Epoch 020 - train 0.54045 | val 1.15737
  Epoch 021 - train 0.53980 | val 0.87109
  Classification -> best τ=0.345 (val F1=0.2551)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64009 | val 0.94190
  Epoch 020 - train 0.56103 | val 1.08360
  Epoch 021 - train 0.54692 | val 1.23793
  Classification -> best τ=0.230 (val F1=0.0983)
  Directional -> Accuracy: 0.4950, MCC: -0.0157, F1: 0.5302

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.64897 | val 0.92609
  Epoch 020 - train 0.57482 | val 1.27379
  Epoch 028 - train 0.44445 | val 1.58802
  Classification -> best τ=0.815 (val F1=0.1525)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.6577

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.64691 | val 1.62475
  Epoch 020 - train 0.53913 | val 2.69686
  Epoch 026 - train 0.47859 | val 4.83039
  Classification -> best τ=0.215 (val F1=0.1915)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64823 | val 1.23230
  Epoch 020 - train 0.56097 | val 2.65177
  Epoch 021 - train 0.55159 | val 2.77061
  Classification -> best τ=0.345 (val F1=0.1845)
  Directional -> Accuracy: 0.5300, MCC: 0.0237, F1: 0.6270

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.63516 | val 1.25508
  Epoch 020 - train 0.56346 | val 1.50062
  Epoch 027 - train 0.48705 | val 1.77833
  Classification -> best τ=0.905 (val F1=0.0909)
  Directional -> Accuracy: 0.6050, MCC: 0.0000, F1: 0.0000

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61060 | val 2.83417
  Epoch 020 - train 0.48919 | val 4.24084
  Epoch 023 - train 0.47801 | val 3.73374
  Classification -> best τ=0.100 (val F1=0.1205)
  Directional -> Accuracy: 0.5700, MCC: 0.1351, F1: 0.6126

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65801 | val 0.84692
  Epoch 020 - train 0.60178 | val 1.28908
  Epoch 028 - train 0.53458 | val 1.45332
  Classification -> best τ=0.275 (val F1=0.1666)
  Directional -> Accuracy: 0.5550, MCC: 0.1125, F1: 0.3688

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64705 | val 0.85054
  Epoch 020 - train 0.56006 | val 1.04571
  Epoch 024 - train 0.53961 | val 1.25935
  Classification -> best τ=0.485 (val F1=0.1826)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.64442 | val 1.15859
  Epoch 020 - train 0.57801 | val 1.32193
  Epoch 023 - train 0.52866 | val 1.89627
  Classification -> best τ=0.465 (val F1=0.1382)
  Directional -> Accuracy: 0.5100, MCC: 0.0208, F1: 0.5702

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65825 | val 2.28713
  Epoch 020 - train 0.61762 | val 3.00418
  Epoch 021 - train 0.61543 | val 3.07490
  Classification -> best τ=0.490 (val F1=0.1317)
  Directional -> Accuracy: 0.5100, MCC: 0.0344, F1: 0.4024

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.64550 | val 0.98354
  Epoch 020 - train 0.54859 | val 1.59776
  Epoch 022 - train 0.53618 | val 1.47851
  Classification -> best τ=0.445 (val F1=0.1241)
  Directional -> Accuracy: 0.5750, MCC: 0.1294, F1: 0.6886

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.64699 | val 1.96611
  Epoch 020 - train 0.54695 | val 2.08418
  Epoch 021 - train 0.51927 | val 2.48935
  Classification -> best τ=0.285 (val F1=0.1605)
  Directional -> Accuracy: 0.5050, MCC: 0.0339, F1: 0.1538

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65479 | val 0.82763
  Epoch 020 - train 0.58020 | val 0.90094
  Epoch 021 - train 0.59240 | val 0.90989
  Classification -> best τ=0.465 (val F1=0.1261)
  Directional -> Accuracy: 0.5600, MCC: 0.0670, F1: 0.6966

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.65710 | val 0.89178
  Epoch 020 - train 0.60286 | val 1.25269
  Epoch 021 - train 0.57794 | val 1.19803
  Classification -> best τ=0.520 (val F1=0.1403)
  Directional -> Accuracy: 0.3950, MCC: -0.0438, F1: 0.0620

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63459 | val 0.92154
  Epoch 020 - train 0.57886 | val 1.06492
  Epoch 022 - train 0.55771 | val 1.11262
  Classification -> best τ=0.550 (val F1=0.1341)
  Directional -> Accuracy: 0.5750, MCC: 0.1074, F1: 0.3609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.65094 | val 2.87375
  Epoch 020 - train 0.48141 | val 2.43779
  Epoch 021 - train 0.41095 | val 2.35848
  Classification -> best τ=0.420 (val F1=0.2036)
  Directional -> Accuracy: 0.5833, MCC: 0.1925, F1: 0.6667

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62555 | val 0.82256
  Epoch 020 - train 0.55401 | val 0.96443
  Epoch 023 - train 0.52951 | val 1.07313
  Classification -> best τ=0.450 (val F1=0.2002)
  Directional -> Accuracy: 0.4250, MCC: 0.0847, F1: 0.0336

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65543 | val 0.83514
  Epoch 020 - train 0.56511 | val 1.23314
  Epoch 021 - train 0.55042 | val 1.49837
  Classification -> best τ=0.705 (val F1=0.2116)
  Directional -> Accuracy: 0.4650, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.63883 | val 1.12568
  Epoch 020 - train 0.54727 | val 1.45746
  Epoch 023 - train 0.52731 | val 1.57041
  Classification -> best τ=0.225 (val F1=0.2127)
  Directional -> Accuracy: 0.5600, MCC: 0.0315, F1: 0.6966

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.64222 | val 1.52585
  Epoch 020 - train 0.57114 | val 2.27358
  Epoch 030 - train 0.42789 | val 4.91851
  Epoch 032 - train 0.44517 | val 4.73475
  Classification -> best τ=0.590 (val F1=0.1121)
  Directional -> Accuracy: 0.4300, MCC: -0.1077, F1: 0.2083

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.65599 | val 1.25339
  Epoch 020 - train 0.58333 | val 1.48629
  Epoch 030 - train 0.43929 | val 1.71971
  Epoch 033 - train 0.39952 | val 2.12741
  Classification -> best τ=0.485 (val F1=0.0716)
  Directional -> Accuracy: 0.4950, MCC: 0.0431, F1: 0.2171

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.65601 | val 0.74809
  Epoch 020 - train 0.63184 | val 0.79172
  Epoch 030 - train 0.52733 | val 0.92784
  Epoch 034 - train 0.48393 | val 1.05511
  Classification -> best τ=0.585 (val F1=0.1037)
  Directional -> Accuracy: 0.4800, MCC: -0.0397, F1: 0.4851

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65190 | val 1.11214
  Epoch 020 - train 0.56783 | val 1.97501
  Epoch 021 - train 0.56604 | val 1.70523
  Classification -> best τ=0.225 (val F1=0.1192)
  Directional -> Accuracy: 0.5650, MCC: 0.1062, F1: 0.6926

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63935 | val 0.88563
  Epoch 020 - train 0.61422 | val 1.24045
  Epoch 028 - train 0.50835 | val 1.46235
  Classification -> best τ=0.195 (val F1=0.0850)
  Directional -> Accuracy: 0.5600, MCC: 0.1192, F1: 0.5728

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65323 | val 1.60396
  Epoch 020 - train 0.57289 | val 3.00710
  Epoch 021 - train 0.55109 | val 3.69223
  Classification -> best τ=0.620 (val F1=0.1548)
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62221 | val 2.12866
  Epoch 020 - train 0.55279 | val 2.55191
  Epoch 021 - train 0.53563 | val 2.14928
  Classification -> best τ=0.090 (val F1=0.1238)
  Directional -> Accuracy: 0.5000, MCC: -0.0315, F1: 0.5968

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63561 | val 1.19767
  Epoch 020 - train 0.55570 | val 1.51992
  Epoch 026 - train 0.52832 | val 1.83324
  Classification -> best τ=0.915 (val F1=0.0641)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65940 | val 1.17882
  Epoch 020 - train 0.58782 | val 1.31685
  Epoch 021 - train 0.58239 | val 1.11132
  Classification -> best τ=0.715 (val F1=0.1550)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64528 | val 0.83875
  Epoch 020 - train 0.56397 | val 1.46034
  Epoch 021 - train 0.53764 | val 1.23719
  Classification -> best τ=0.455 (val F1=0.0749)
  Directional -> Accuracy: 0.4050, MCC: -0.0658, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62782 | val 1.43056
  Epoch 020 - train 0.55473 | val 1.74631
  Epoch 021 - train 0.55088 | val 2.26951
  Classification -> best τ=0.200 (val F1=0.1615)
  Directional -> Accuracy: 0.4800, MCC: -0.0347, F1: 0.5840

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63796 | val 1.19734
  Epoch 020 - train 0.56778 | val 0.97796
  Epoch 030 - train 0.45366 | val 1.22758
  Epoch 036 - train 0.36717 | val 1.57678
  Classification -> best τ=0.660 (val F1=0.0959)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64921 | val 0.88199
  Epoch 020 - train 0.56519 | val 1.44794
  Epoch 021 - train 0.55678 | val 1.59214
  Classification -> best τ=0.350 (val F1=0.1127)
  Directional -> Accuracy: 0.5350, MCC: 0.0843, F1: 0.5373

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63217 | val 0.93005
  Epoch 020 - train 0.53739 | val 1.44372
  Epoch 023 - train 0.48595 | val 1.57176
  Classification -> best τ=0.170 (val F1=0.1314)
  Directional -> Accuracy: 0.5300, MCC: 0.0626, F1: 0.4891

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65562 | val 0.80196
  Epoch 020 - train 0.55118 | val 0.94794
  Epoch 026 - train 0.49523 | val 1.22885
  Classification -> best τ=0.270 (val F1=0.1849)
  Directional -> Accuracy: 0.5550, MCC: 0.1564, F1: 0.6899

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.65871 | val 0.81849
  Epoch 020 - train 0.58816 | val 1.01500
  Epoch 022 - train 0.56634 | val 1.06125
  Classification -> best τ=0.640 (val F1=0.1705)
  Directional -> Accuracy: 0.4050, MCC: -0.0444, F1: 0.0775

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.65299 | val 0.95485
  Epoch 020 - train 0.53396 | val 1.32635
  Epoch 021 - train 0.54066 | val 1.22216
  Classification -> best τ=0.570 (val F1=0.1400)
  Directional -> Accuracy: 0.4400, MCC: -0.1196, F1: 0.4667

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65698 | val 1.47696
  Epoch 020 - train 0.58042 | val 2.16304
  Epoch 021 - train 0.57757 | val 2.00096
  Classification -> best τ=0.325 (val F1=0.1186)
  Directional -> Accuracy: 0.5500, MCC: 0.1219, F1: 0.6939

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64772 | val 0.85575
  Epoch 020 - train 0.54762 | val 1.38747
  Epoch 021 - train 0.58195 | val 1.47643
  Classification -> best τ=0.690 (val F1=0.0521)
  Directional -> Accuracy: 0.4500, MCC: -0.0231, F1: 0.0833

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.66341 | val 0.71813
  Epoch 020 - train 0.58801 | val 0.76893
  Epoch 030 - train 0.42478 | val 0.97531
  Epoch 036 - train 0.35795 | val 1.04666
  Classification -> best τ=0.470 (val F1=0.1285)
  Directional -> Accuracy: 0.5100, MCC: -0.0182, F1: 0.6397

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64901 | val 0.90674
  Epoch 020 - train 0.56751 | val 1.36284
  Epoch 021 - train 0.54640 | val 1.39368
  Classification -> best τ=0.460 (val F1=0.1850)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64002 | val 1.41566
  Epoch 020 - train 0.56165 | val 1.49685
  Epoch 021 - train 0.54564 | val 1.66613
  Classification -> best τ=0.170 (val F1=0.2210)
  Directional -> Accuracy: 0.4850, MCC: 0.0007, F1: 0.3355

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64618 | val 1.33834
  Epoch 020 - train 0.55352 | val 1.63399
  Epoch 024 - train 0.53497 | val 1.56049
  Classification -> best τ=0.895 (val F1=0.1285)
  Directional -> Accuracy: 0.5200, MCC: -0.0099, F1: 0.0943

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63439 | val 1.18748
  Epoch 020 - train 0.55012 | val 1.55786
  Epoch 021 - train 0.54030 | val 1.62018
  Classification -> best τ=0.465 (val F1=0.1210)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.64890 | val 1.12025
  Epoch 020 - train 0.55602 | val 1.60409

[I 2026-02-25 23:56:31,021] Trial 13 finished with value: 0.15070605263972905 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.0020035434101800735, 'weight_decay': 7.243605947922555e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.1872756431970817, 'early_stopping_min_delta': 0.0007499715540613297}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 021 - train 0.55843 | val 2.08184
  Classification -> best τ=0.440 (val F1=0.1704)
  Directional -> Accuracy: 0.4950, MCC: -0.0071, F1: 0.5258

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.15070605263972905
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64270 | val 0.75859
  Epoch 020 - train 0.56526 | val 0.88249
  Epoch 021 - train 0.56135 | val 0.86447
  Classification -> best τ=0.370 (val F1=0.1614)
  Directional -> Accuracy: 0.5427, MCC: 0.0774, F1: 0.5882

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.60282 | val 1.77205
  Epoch 020 - train 0.50621 | val 2.03315
  Epoch 021 - train 0.47933 | val 2.54495
  Classification -> best τ=0.445 (val F1=0.1725)
  Directional -> Accuracy: 0.5025, MCC: 0.0707, F1: 0.0198

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62534 | val 0.92790
  Epoch 020 - train 0.56417 | val 0.90977
  Epoch 021 - train 0.57861 | val 1.09952
  Classification -> best τ=0.415 (val F1=0.1266)
  Directional -> Accuracy: 0.5860, MCC: 0.1332, F1: 0.6638

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.63808 | val 1.30646
  Epoch 020 - train 0.50637 | val 1.68054
  Epoch 022 - train 0.47440 | val 1.86819
  Classification -> best τ=0.585 (val F1=0.0925)
  Directional -> Accuracy: 0.4372, MCC: 0.0000, F1: 0.0000

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.57958 | val 0.80347
  Epoch 020 - train 0.45312 | val 0.93261
  Epoch 023 - train 0.43289 | val 1.04388
  Classification -> best τ=0.485 (val F1=0.1496)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64900 | val 0.73711
  Epoch 020 - train 0.56012 | val 0.86399
  Epoch 021 - train 0.56524 | val 0.83297
  Classification -> best τ=0.415 (val F1=0.1545)
  Directional -> Accuracy: 0.5528, MCC: 0.0107, F1: 0.7101

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63713 | val 0.80185
  Epoch 020 - train 0.55199 | val 1.31132
  Epoch 021 - train 0.54131 | val 1.34835
  Classification -> best τ=0.560 (val F1=0.1334)
  Directional -> Accuracy: 0.4422, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61685 | val 0.84699
  Epoch 020 - train 0.53312 | val 0.94921
  Epoch 021 - train 0.53258 | val 0.96530
  Classification -> best τ=0.400 (val F1=0.2761)
  Directional -> Accuracy: 0.3920, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61407 | val 0.82764
  Epoch 020 - train 0.48446 | val 1.01434
  Epoch 021 - train 0.47655 | val 1.11051
  Classification -> best τ=0.530 (val F1=0.2046)
  Directional -> Accuracy: 0.5175, MCC: 0.1514, F1: 0.3956

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65682 | val 0.96754
  Epoch 020 - train 0.55139 | val 1.30657
  Epoch 022 - train 0.53544 | val 1.34852
  Classification -> best τ=0.565 (val F1=0.1031)
  Directional -> Accuracy: 0.5377, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.64412 | val 0.75536
  Epoch 020 - train 0.53813 | val 1.00065
  Epoch 022 - train 0.52641 | val 0.99609
  Classification -> best τ=0.525 (val F1=0.0826)
  Directional -> Accuracy: 0.5276, MCC: 0.0192, F1: 0.6270

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.62474 | val 0.93131
  Epoch 020 - train 0.55510 | val 0.90056
  Epoch 023 - train 0.53283 | val 0.95343
  Classification -> best τ=0.640 (val F1=0.1309)
  Directional -> Accuracy: 0.4523, MCC: 0.0656, F1: 0.1679

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62934 | val 1.02025
  Epoch 020 - train 0.55584 | val 0.87048
  Epoch 021 - train 0.55492 | val 0.81921
  Classification -> best τ=0.560 (val F1=0.1079)
  Directional -> Accuracy: 0.4372, MCC: -0.0128, F1: 0.0175

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65763 | val 0.73721
  Epoch 020 - train 0.50348 | val 1.09503
  Epoch 021 - train 0.51011 | val 1.12747
  Classification -> best τ=0.585 (val F1=0.1030)
  Directional -> Accuracy: 0.5025, MCC: 0.0010, F1: 0.0748

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.65055 | val 0.79636
  Epoch 020 - train 0.56940 | val 0.80492
  Epoch 021 - train 0.57890 | val 0.83564
  Classification -> best τ=0.465 (val F1=0.0645)
  Directional -> Accuracy: 0.5327, MCC: 0.0685, F1: 0.5373

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.61928 | val 0.86601
  Epoch 020 - train 0.51497 | val 1.44832
  Epoch 021 - train 0.52146 | val 1.21378
  Classification -> best τ=0.440 (val F1=0.1065)
  Directional -> Accuracy: 0.5075, MCC: 0.0171, F1: 0.6423

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.65461 | val 0.87092
  Epoch 020 - train 0.54964 | val 1.12437
  Epoch 022 - train 0.57971 | val 0.95146
  Classification -> best τ=0.375 (val F1=0.1474)
  Directional -> Accuracy: 0.5477, MCC: -0.0195, F1: 0.7000

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62382 | val 0.85457
  Epoch 020 - train 0.44515 | val 1.04421
  Epoch 022 - train 0.43768 | val 1.09241
  Classification -> best τ=0.385 (val F1=0.1098)
  Directional -> Accuracy: 0.5075, MCC: 0.0070, F1: 0.5664

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61669 | val 0.77050
  Epoch 020 - train 0.54448 | val 0.95381
  Epoch 021 - train 0.53706 | val 0.91495
  Classification -> best τ=0.510 (val F1=0.2114)
  Directional -> Accuracy: 0.5176, MCC: 0.0971, F1: 0.6735

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63036 | val 0.87499
  Epoch 020 - train 0.54726 | val 1.05451
  Epoch 021 - train 0.53513 | val 1.31592
  Classification -> best τ=0.515 (val F1=0.0995)
  Directional -> Accuracy: 0.4623, MCC: 0.0185, F1: 0.0531

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.62375 | val 1.01283
  Epoch 020 - train 0.51786 | val 0.97085
  Epoch 021 - train 0.49467 | val 1.02388
  Classification -> best τ=0.535 (val F1=0.1830)
  Directional -> Accuracy: 0.5025, MCC: 0.0384, F1: 0.6526

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.67539 | val 0.73877
  Epoch 020 - train 0.58215 | val 0.86593
  Epoch 021 - train 0.58126 | val 0.81730
  Classification -> best τ=0.460 (val F1=0.0968)
  Directional -> Accuracy: 0.4422, MCC: -0.0299, F1: 0.1778

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63910 | val 0.78881
  Epoch 020 - train 0.62713 | val 0.73200
  Epoch 030 - train 0.43295 | val 0.89759
  Classification -> best τ=0.685 (val F1=0.1063)
  Directional -> Accuracy: 0.4573, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.64915 | val 0.75967
  Epoch 020 - train 0.51638 | val 1.03517
  Epoch 022 - train 0.54286 | val 1.01331
  Classification -> best τ=0.335 (val F1=0.1570)
  Directional -> Accuracy: 0.4121, MCC: 0.1150, F1: 0.5714

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62999 | val 1.11284
  Epoch 020 - train 0.52976 | val 1.20076
  Epoch 021 - train 0.51651 | val 1.37017
  Classification -> best τ=0.355 (val F1=0.1171)
  Directional -> Accuracy: 0.5327, MCC: 0.0472, F1: 0.6593

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62939 | val 0.79595
  Epoch 020 - train 0.55000 | val 1.48462
  Epoch 021 - train 0.52533 | val 1.29819
  Classification -> best τ=0.470 (val F1=0.1432)
  Directional -> Accuracy: 0.5226, MCC: 0.0566, F1: 0.5852

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61333 | val 1.09413
  Epoch 020 - train 0.52595 | val 1.86664
  Epoch 021 - train 0.51512 | val 1.68707
  Classification -> best τ=0.525 (val F1=0.0209)
  Directional -> Accuracy: 0.4925, MCC: -0.0489, F1: 0.5844

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.63534 | val 0.86497
  Epoch 020 - train 0.59301 | val 1.21453
  Epoch 021 - train 0.59250 | val 1.21383
  Classification -> best τ=0.400 (val F1=0.1518)
  Directional -> Accuracy: 0.5176, MCC: 0.0362, F1: 0.5472

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66211 | val 0.83046
  Epoch 020 - train 0.60131 | val 1.25919
  Epoch 022 - train 0.56955 | val 1.36890
  Classification -> best τ=0.505 (val F1=0.1308)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.64258 | val 0.82214
  Epoch 020 - train 0.55078 | val 1.66736
  Epoch 021 - train 0.54949 | val 2.13426
  Classification -> best τ=0.600 (val F1=0.0201)
  Directional -> Accuracy: 0.4573, MCC: 0.0000, F1: 0.0000

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.61257 | val 1.47012
  Epoch 020 - train 0.47412 | val 2.05548
  Epoch 021 - train 0.46100 | val 1.82208
  Classification -> best τ=0.480 (val F1=0.1481)
  Directional -> Accuracy: 0.4874, MCC: -0.0202, F1: 0.2388

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64317 | val 0.69824
  Epoch 020 - train 0.56708 | val 0.80436
  Epoch 022 - train 0.54244 | val 0.86829
  Classification -> best τ=0.555 (val F1=0.1358)
  Directional -> Accuracy: 0.4372, MCC: -0.0740, F1: 0.2113

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.66445 | val 0.78598
  Epoch 020 - train 0.62185 | val 0.87627
  Epoch 021 - train 0.60755 | val 0.85122
  Classification -> best τ=0.600 (val F1=0.1171)
  Directional -> Accuracy: 0.3920, MCC: 0.0000, F1: 0.0000

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63779 | val 1.50560
  Epoch 020 - train 0.53235 | val 2.17416
  Epoch 021 - train 0.55255 | val 1.85430
  Classification -> best τ=0.390 (val F1=0.1003)
  Directional -> Accuracy: 0.4422, MCC: -0.0493, F1: 0.6078

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.52133 | val 1.45831
  Epoch 020 - train 0.41420 | val 1.95191
  Epoch 021 - train 0.41700 | val 2.07612
  Classification -> best τ=0.430 (val F1=0.0908)
  Directional -> Accuracy: 0.6170, MCC: 0.2332, F1: 0.5909

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63773 | val 1.29606
  Epoch 020 - train 0.57954 | val 1.13644
  Epoch 030 - train 0.42452 | val 1.19769
  Classification -> best τ=0.395 (val F1=0.1033)
  Directional -> Accuracy: 0.5829, MCC: 0.0000, F1: 0.7365

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64175 | val 0.74099
  Epoch 020 - train 0.49721 | val 1.31564
  Epoch 022 - train 0.49916 | val 1.33407
  Classification -> best τ=0.485 (val F1=0.1682)
  Directional -> Accuracy: 0.5427, MCC: 0.0580, F1: 0.6566

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.66419 | val 0.75957
  Epoch 020 - train 0.54171 | val 1.19421
  Epoch 021 - train 0.54736 | val 1.18204
  Classification -> best τ=0.430 (val F1=0.1112)
  Directional -> Accuracy: 0.5528, MCC: 0.0556, F1: 0.6482

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.65966 | val 1.32733
  Epoch 020 - train 0.53782 | val 2.61067
  Epoch 022 - train 0.52518 | val 2.30982
  Classification -> best τ=0.370 (val F1=0.1822)
  Directional -> Accuracy: 0.5427, MCC: 0.0000, F1: 0.7036

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.64078 | val 0.69817
  Epoch 020 - train 0.55933 | val 1.01200
  Epoch 021 - train 0.54862 | val 1.04803
  Classification -> best τ=0.515 (val F1=0.0362)
  Directional -> Accuracy: 0.4724, MCC: 0.0000, F1: 0.0000

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.65862 | val 0.90780
  Epoch 020 - train 0.56005 | val 0.86518
  Epoch 022 - train 0.56503 | val 0.81851
  Classification -> best τ=0.470 (val F1=0.1437)
  Directional -> Accuracy: 0.4774, MCC: -0.0941, F1: 0.6148

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64676 | val 1.02127
  Epoch 020 - train 0.51466 | val 1.39543
  Epoch 021 - train 0.50013 | val 1.46020
  Classification -> best τ=0.370 (val F1=0.1133)
  Directional -> Accuracy: 0.5276, MCC: 0.0339, F1: 0.5983

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63844 | val 1.06373
  Epoch 020 - train 0.54211 | val 1.15879
  Epoch 021 - train 0.53349 | val 1.21699
  Classification -> best τ=0.400 (val F1=0.1576)
  Directional -> Accuracy: 0.5377, MCC: 0.0937, F1: 0.6738

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67053 | val 0.77993
  Epoch 020 - train 0.56483 | val 1.01472
  Epoch 023 - train 0.54179 | val 1.20391
  Classification -> best τ=0.405 (val F1=0.2241)
  Directional -> Accuracy: 0.5226, MCC: 0.0000, F1: 0.6865

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63365 | val 1.31852
  Epoch 020 - train 0.48605 | val 1.94009
  Epoch 022 - train 0.48325 | val 2.10707
  Classification -> best τ=0.230 (val F1=0.0858)
  Directional -> Accuracy: 0.5377, MCC: 0.0403, F1: 0.6489

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64186 | val 0.80292
  Epoch 020 - train 0.56321 | val 0.82372
  Epoch 021 - train 0.55333 | val 0.81319
  Classification -> best τ=0.610 (val F1=0.0646)
  Directional -> Accuracy: 0.4121, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62362 | val 0.72927
  Epoch 020 - train 0.56323 | val 0.81969
  Epoch 025 - train 0.50884 | val 1.05894
  Classification -> best τ=0.475 (val F1=0.1418)
  Directional -> Accuracy: 0.5628, MCC: 0.0000, F1: 0.7203

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62985 | val 1.61041
  Epoch 020 - train 0.49160 | val 1.11069
  Epoch 021 - train 0.48151 | val 0.95760
  Classification -> best τ=0.465 (val F1=0.0844)
  Directional -> Accuracy: 0.5829, MCC: -0.0615, F1: 0.7331

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67576 | val 0.75879
  Epoch 020 - train 0.54718 | val 1.05219
  Epoch 025 - train 0.53041 | val 1.25358
  Classification -> best τ=0.675 (val F1=0.1288)
  Directional -> Accuracy: 0.5075, MCC: -0.0159, F1: 0.0926

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64256 | val 0.72413
  Epoch 020 - train 0.54905 | val 0.83977
  Epoch 021 - train 0.52271 | val 0.86467
  Classification -> best τ=0.430 (val F1=0.1141)
  Directional -> Accuracy: 0.5678, MCC: 0.0000, F1: 0.7244

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65565 | val 0.77303
  Epoch 020 - train 0.57893 | val 0.72827
  Epoch 028 - train 0.47240 | val 0.90140
  Classification -> best τ=0.480 (val F1=0.1495)
  Directional -> Accuracy: 0.5427, MCC: 0.1110, F1: 0.5236

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62320 | val 0.82812
  Epoch 020 - train 0.53927 | val 0.87339
  Epoch 021 - train 0.54865 | val 0.85770
  Classification -> best τ=0.405 (val F1=0.1454)
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63502 | val 0.84875
  Epoch 020 - train 0.52902 | val 1.13291
  Epoch 021 - train 0.54177 | val 1.17633
  Classification -> best τ=0.585 (val F1=0.0891)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.63918 | val 1.11924
  Epoch 020 - train 0.53520 | val 1.59493
  Epoch 021 - train 0.51786 | val 1.78214
  Classification -> best τ=0.520 (val F1=0.1136)
  Directional -> Accuracy: 0.4020, MCC: 0.0000, F1: 0.0000

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.64147 | val 0.76852
  Epoch 020 - train 0.54175 | val 1.33324
  Epoch 021 - train 0.58707 | val 1.13829
  Classification -> best τ=0.490 (val F1=0.1621)
  Directional -> Accuracy: 0.4774, MCC: -0.0768, F1: 0.1475

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.62939 | val 0.96501
  Epoch 020 - train 0.54334 | val 1.39114
  Epoch 021 - train 0.54670 | val 1.19629
  Classification -> best τ=0.520 (val F1=0.1105)
  Directional -> Accuracy: 0.5176, MCC: 0.0044, F1: 0.6496

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62900 | val 0.76906
  Epoch 020 - train 0.52794 | val 0.78560
  Epoch 021 - train 0.55314 | val 0.81796
  Classification -> best τ=0.515 (val F1=0.0651)
  Directional -> Accuracy: 0.4774, MCC: 0.0162, F1: 0.2973

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.62726 | val 0.89108
  Epoch 020 - train 0.53049 | val 0.85793
  Epoch 021 - train 0.50763 | val 0.81808
  Classification -> best τ=0.535 (val F1=0.0477)
  Directional -> Accuracy: 0.5276, MCC: 0.0000, F1: 0.6908

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61785 | val 0.73882
  Epoch 020 - train 0.50475 | val 0.83846
  Epoch 022 - train 0.50281 | val 0.84386
  Classification -> best τ=0.545 (val F1=0.2021)
  Directional -> Accuracy: 0.4171, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61446 | val 0.85933
  Epoch 020 - train 0.50610 | val 0.77880
  Epoch 022 - train 0.49627 | val 0.75326
  Classification -> best τ=0.525 (val F1=0.1606)
  Directional -> Accuracy: 0.5075, MCC: 0.0850, F1: 0.2794

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64047 | val 0.96641
  Epoch 020 - train 0.53178 | val 1.12912
  Epoch 021 - train 0.52591 | val 1.16061
  Classification -> best τ=0.640 (val F1=0.0811)
  Directional -> Accuracy: 0.5226, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65191 | val 0.85145
  Epoch 020 - train 0.52027 | val 1.16315
  Epoch 022 - train 0.49912 | val 1.25489
  Classification -> best τ=0.675 (val F1=0.1194)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.64407 | val 0.93905
  Epoch 020 - train 0.52038 | val 1.31038
  Epoch 021 - train 0.51515 | val 1.29071
  Classification -> best τ=0.635 (val F1=0.0819)
  Directional -> Accuracy: 0.5327, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.60547 | val 1.03262
  Epoch 020 - train 0.43281 | val 1.10612

[I 2026-02-26 00:09:56,784] Trial 14 finished with value: 0.12635440513139817 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.002525269146492805, 'weight_decay': 1.978151768520242e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.7117181298734545, 'early_stopping_min_delta': 0.0017512175021972163}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 021 - train 0.57011 | val 1.01930
  Classification -> best τ=0.300 (val F1=0.1308)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.6599

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.12635440513139817
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68167 | val 0.76331
  Epoch 020 - train 0.67568 | val 0.78400
  Epoch 021 - train 0.66862 | val 0.78686
  Classification -> best τ=0.700 (val F1=0.0956)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.66328 | val 1.80453
  Epoch 020 - train 0.66402 | val 2.14381
  Epoch 021 - train 0.65451 | val 2.17148
  Classification -> best τ=0.255 (val F1=0.1574)
  Directional -> Accuracy: 0.5450, MCC: 0.0997, F1: 0.4204

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65348 | val 0.72382
  Epoch 020 - train 0.65058 | val 0.73589
  Epoch 021 - train 0.65487 | val 0.74050
  Classification -> best τ=0.575 (val F1=0.1769)
  Directional -> Accuracy: 0.4225, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.67549 | val 0.77614
  Epoch 020 - train 0.67581 | val 0.76231
  Epoch 021 - train 0.66883 | val 0.77901
  Classification -> best τ=0.465 (val F1=0.0918)
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.0000

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.67155 | val 0.83343
  Epoch 020 - train 0.67014 | val 0.91120
  Epoch 021 - train 0.67336 | val 0.92074
  Classification -> best τ=0.555 (val F1=0.1004)
  Directional -> Accuracy: 0.4579, MCC: -0.1079, F1: 0.0333

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66336 | val 0.83862
  Epoch 020 - train 0.65497 | val 0.87812
  Epoch 021 - train 0.65457 | val 0.88254
  Classification -> best τ=0.550 (val F1=0.1057)
  Directional -> Accuracy: 0.4300, MCC: -0.1032, F1: 0.0339

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68712 | val 0.79265
  Epoch 020 - train 0.68110 | val 0.84969
  Epoch 021 - train 0.67440 | val 0.87134
  Classification -> best τ=0.620 (val F1=0.0873)
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66785 | val 0.75304
  Epoch 020 - train 0.65699 | val 0.81241
  Epoch 022 - train 0.65581 | val 0.82735
  Classification -> best τ=0.565 (val F1=0.2111)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66553 | val 0.99977
  Epoch 020 - train 0.66109 | val 1.36839
  Epoch 022 - train 0.66252 | val 1.43270
  Classification -> best τ=0.645 (val F1=0.2018)
  Directional -> Accuracy: 0.4348, MCC: -0.0426, F1: 0.2857

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67047 | val 0.96939
  Epoch 020 - train 0.66123 | val 1.08107
  Epoch 021 - train 0.65832 | val 1.08008
  Classification -> best τ=0.645 (val F1=0.1654)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.66719 | val 0.71968
  Epoch 020 - train 0.66680 | val 0.71223
  Epoch 021 - train 0.66216 | val 0.71548
  Classification -> best τ=0.505 (val F1=0.1739)
  Directional -> Accuracy: 0.5300, MCC: 0.0262, F1: 0.6299

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.67501 | val 0.74932
  Epoch 020 - train 0.66092 | val 0.73798
  Epoch 021 - train 0.67122 | val 0.73925
  Classification -> best τ=0.360 (val F1=0.1120)
  Directional -> Accuracy: 0.5800, MCC: 0.0664, F1: 0.7162

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67404 | val 0.79215
  Epoch 020 - train 0.66632 | val 0.84901
  Epoch 021 - train 0.66483 | val 0.86113
  Classification -> best τ=0.535 (val F1=0.1180)
  Directional -> Accuracy: 0.4450, MCC: -0.0812, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67333 | val 0.69723
  Epoch 020 - train 0.66715 | val 0.71080
  Epoch 023 - train 0.65890 | val 0.72053
  Classification -> best τ=0.565 (val F1=0.1730)
  Directional -> Accuracy: 0.5300, MCC: 0.0771, F1: 0.2540

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.67519 | val 0.81965
  Epoch 020 - train 0.67610 | val 0.88714
  Epoch 021 - train 0.67600 | val 0.89056
  Classification -> best τ=0.475 (val F1=0.0750)
  Directional -> Accuracy: 0.4500, MCC: -0.0831, F1: 0.3373

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.65596 | val 0.86674
  Epoch 020 - train 0.66243 | val 0.96911
  Epoch 021 - train 0.65774 | val 0.97339
  Classification -> best τ=0.395 (val F1=0.1525)
  Directional -> Accuracy: 0.5100, MCC: 0.0308, F1: 0.6449

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.68384 | val 0.76576
  Epoch 020 - train 0.66702 | val 0.78286
  Epoch 021 - train 0.66778 | val 0.78332
  Classification -> best τ=0.430 (val F1=0.1463)
  Directional -> Accuracy: 0.5550, MCC: 0.0000, F1: 0.7138

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65901 | val 0.79684
  Epoch 020 - train 0.64781 | val 0.88111
  Epoch 021 - train 0.65352 | val 0.89125
  Classification -> best τ=0.560 (val F1=0.1288)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67740 | val 0.75903
  Epoch 020 - train 0.66725 | val 0.80134
  Epoch 021 - train 0.66444 | val 0.79100
  Classification -> best τ=0.495 (val F1=0.2050)
  Directional -> Accuracy: 0.5050, MCC: 0.0709, F1: 0.0198

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67407 | val 0.74762
  Epoch 020 - train 0.66428 | val 0.77103
  Epoch 021 - train 0.66185 | val 0.77352
  Classification -> best τ=0.440 (val F1=0.0801)
  Directional -> Accuracy: 0.5600, MCC: 0.0914, F1: 0.6901

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.68256 | val 0.71852
  Epoch 020 - train 0.66645 | val 0.72220
  Epoch 021 - train 0.67179 | val 0.72710
  Classification -> best τ=0.535 (val F1=0.0990)
  Directional -> Accuracy: 0.5150, MCC: 0.0225, F1: 0.3022

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.67484 | val 0.83598
  Epoch 020 - train 0.66654 | val 0.97741
  Epoch 021 - train 0.66690 | val 0.96323
  Classification -> best τ=0.575 (val F1=0.1523)
  Directional -> Accuracy: 0.4600, MCC: 0.0176, F1: 0.2394

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66502 | val 0.77031
  Epoch 020 - train 0.66822 | val 0.79396
  Epoch 021 - train 0.67144 | val 0.79787
  Classification -> best τ=0.500 (val F1=0.2246)
  Directional -> Accuracy: 0.4550, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.66791 | val 0.98115
  Epoch 020 - train 0.65831 | val 0.99172
  Epoch 021 - train 0.66564 | val 1.00333
  Classification -> best τ=0.545 (val F1=0.1300)
  Directional -> Accuracy: 0.6050, MCC: 0.0000, F1: 0.0000

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67219 | val 0.92992
  Epoch 020 - train 0.66404 | val 1.01400
  Epoch 021 - train 0.66470 | val 1.02795
  Classification -> best τ=0.450 (val F1=0.1040)
  Directional -> Accuracy: 0.5050, MCC: 0.0145, F1: 0.4870

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67813 | val 0.74317
  Epoch 020 - train 0.66987 | val 0.77365
  Epoch 021 - train 0.66482 | val 0.78317
  Classification -> best τ=0.475 (val F1=0.1839)
  Directional -> Accuracy: 0.5650, MCC: 0.1309, F1: 0.4238

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68361 | val 0.76113
  Epoch 020 - train 0.67239 | val 0.78414
  Epoch 021 - train 0.67371 | val 0.78857
  Classification -> best τ=0.535 (val F1=0.1541)
  Directional -> Accuracy: 0.4700, MCC: -0.0056, F1: 0.2319

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.67898 | val 0.87400
  Epoch 020 - train 0.67161 | val 0.91145
  Epoch 021 - train 0.66328 | val 0.92634
  Classification -> best τ=0.410 (val F1=0.0870)
  Directional -> Accuracy: 0.5500, MCC: 0.1010, F1: 0.5794

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66884 | val 0.77130
  Epoch 020 - train 0.66865 | val 0.81691
  Epoch 021 - train 0.66753 | val 0.82206
  Classification -> best τ=0.525 (val F1=0.1142)
  Directional -> Accuracy: 0.5200, MCC: 0.0359, F1: 0.5596

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.68740 | val 0.98871
  Epoch 020 - train 0.68075 | val 1.04420
  Epoch 021 - train 0.68124 | val 1.03659
  Classification -> best τ=0.390 (val F1=0.1448)
  Directional -> Accuracy: 0.5150, MCC: 0.0088, F1: 0.5872

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.68065 | val 0.79798
  Epoch 020 - train 0.67521 | val 0.78611
  Epoch 021 - train 0.67085 | val 0.78896
  Classification -> best τ=0.495 (val F1=0.1755)
  Directional -> Accuracy: 0.4850, MCC: -0.0604, F1: 0.0374

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67524 | val 0.71895
  Epoch 020 - train 0.67617 | val 0.73597
  Epoch 021 - train 0.66962 | val 0.73592
  Classification -> best τ=0.440 (val F1=0.1592)
  Directional -> Accuracy: 0.5500, MCC: 0.0422, F1: 0.6786

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.69831 | val 0.76153
  Epoch 020 - train 0.69704 | val 0.76615
  Epoch 021 - train 0.69929 | val 0.76707
  Classification -> best τ=0.375 (val F1=0.1247)
  Directional -> Accuracy: 0.4150, MCC: 0.0605, F1: 0.0930

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66322 | val 0.83090
  Epoch 020 - train 0.65584 | val 0.86790
  Epoch 021 - train 0.65956 | val 0.87996
  Classification -> best τ=0.485 (val F1=0.0891)
  Directional -> Accuracy: 0.5050, MCC: 0.0402, F1: 0.5395

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.66415 | val 0.74090
  Epoch 020 - train 0.68393 | val 0.78382
  Epoch 021 - train 0.69692 | val 0.78604
  Classification -> best τ=0.525 (val F1=0.0700)
  Directional -> Accuracy: 0.5625, MCC: 0.1487, F1: 0.4000

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66237 | val 0.71176
  Epoch 020 - train 0.65659 | val 0.74552
  Epoch 022 - train 0.65706 | val 0.75103
  Classification -> best τ=0.630 (val F1=0.1967)
  Directional -> Accuracy: 0.4250, MCC: -0.0544, F1: 0.2484

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66808 | val 0.72525
  Epoch 020 - train 0.66372 | val 0.75322
  Epoch 021 - train 0.66771 | val 0.74719
  Classification -> best τ=0.520 (val F1=0.1773)
  Directional -> Accuracy: 0.4650, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.67364 | val 0.85917
  Epoch 020 - train 0.65837 | val 0.95866
  Epoch 021 - train 0.66075 | val 0.94805
  Classification -> best τ=0.555 (val F1=0.1186)
  Directional -> Accuracy: 0.4500, MCC: -0.0291, F1: 0.2857

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.67528 | val 1.07843
  Epoch 020 - train 0.66790 | val 1.21627
  Epoch 021 - train 0.66480 | val 1.23026
  Classification -> best τ=0.475 (val F1=0.1406)
  Directional -> Accuracy: 0.5450, MCC: 0.1259, F1: 0.4859

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.66744 | val 0.96801
  Epoch 020 - train 0.66853 | val 1.12601
  Epoch 021 - train 0.65998 | val 1.13354
  Classification -> best τ=0.640 (val F1=0.1584)
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.0000

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.67889 | val 0.96763
  Epoch 020 - train 0.67135 | val 1.08269
  Epoch 021 - train 0.67141 | val 1.06315
  Classification -> best τ=0.560 (val F1=0.1227)
  Directional -> Accuracy: 0.5150, MCC: 0.0235, F1: 0.5727

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66273 | val 0.92894
  Epoch 020 - train 0.65767 | val 0.98618
  Epoch 021 - train 0.65487 | val 1.00760
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67893 | val 0.88010
  Epoch 020 - train 0.66882 | val 0.92431
  Epoch 021 - train 0.66907 | val 0.93306
  Classification -> best τ=0.510 (val F1=0.1000)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67692 | val 0.73189
  Epoch 020 - train 0.66415 | val 0.78296
  Epoch 022 - train 0.65446 | val 0.78611
  Classification -> best τ=0.525 (val F1=0.2005)
  Directional -> Accuracy: 0.4600, MCC: -0.0835, F1: 0.4906

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65130 | val 1.39167
  Epoch 020 - train 0.64741 | val 1.60194
  Epoch 021 - train 0.65402 | val 1.64922
  Classification -> best τ=0.425 (val F1=0.1904)
  Directional -> Accuracy: 0.5050, MCC: -0.0070, F1: 0.5714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66746 | val 0.93112
  Epoch 020 - train 0.66801 | val 0.99558
  Epoch 021 - train 0.66673 | val 0.99405
  Classification -> best τ=0.430 (val F1=0.0784)
  Directional -> Accuracy: 0.5850, MCC: 0.0352, F1: 0.7314

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66343 | val 0.78617
  Epoch 020 - train 0.66687 | val 0.83521
  Epoch 021 - train 0.65903 | val 0.84376
  Classification -> best τ=0.535 (val F1=0.1479)
  Directional -> Accuracy: 0.5400, MCC: 0.1107, F1: 0.5208

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67443 | val 0.82314
  Epoch 020 - train 0.67248 | val 0.84831
  Epoch 021 - train 0.66787 | val 0.84941
  Classification -> best τ=0.515 (val F1=0.1093)
  Directional -> Accuracy: 0.5800, MCC: 0.0906, F1: 0.6744

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66797 | val 0.80286
  Epoch 020 - train 0.66596 | val 0.83147
  Epoch 021 - train 0.65946 | val 0.83945
  Classification -> best τ=0.430 (val F1=0.1392)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.6577

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67155 | val 0.87528
  Epoch 020 - train 0.66355 | val 0.90287
  Epoch 021 - train 0.66428 | val 0.90383
  Classification -> best τ=0.425 (val F1=0.0668)
  Directional -> Accuracy: 0.5600, MCC: 0.0285, F1: 0.6986

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68136 | val 0.84187
  Epoch 020 - train 0.67283 | val 0.91025
  Epoch 021 - train 0.68016 | val 0.91157
  Classification -> best τ=0.380 (val F1=0.0784)
  Directional -> Accuracy: 0.5800, MCC: 0.1084, F1: 0.7143

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66960 | val 0.74548
  Epoch 020 - train 0.66622 | val 0.77012
  Epoch 021 - train 0.67374 | val 0.77045
  Classification -> best τ=0.410 (val F1=0.1015)
  Directional -> Accuracy: 0.5100, MCC: 0.0716, F1: 0.6733

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67710 | val 0.76035
  Epoch 020 - train 0.66634 | val 0.77823
  Epoch 021 - train 0.67053 | val 0.78670
  Classification -> best τ=0.625 (val F1=0.1431)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.66384 | val 0.78192
  Epoch 020 - train 0.67034 | val 0.79213
  Epoch 021 - train 0.67021 | val 0.78910
  Classification -> best τ=0.475 (val F1=0.1655)
  Directional -> Accuracy: 0.4050, MCC: -0.0571, F1: 0.1185

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.67662 | val 0.71577
  Epoch 020 - train 0.66988 | val 0.72612
  Epoch 021 - train 0.66685 | val 0.73094
  Classification -> best τ=0.440 (val F1=0.1606)
  Directional -> Accuracy: 0.4850, MCC: -0.0303, F1: 0.6054

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67089 | val 0.78136
  Epoch 020 - train 0.67425 | val 0.80898
  Epoch 021 - train 0.67321 | val 0.81692
  Classification -> best τ=0.535 (val F1=0.1148)
  Directional -> Accuracy: 0.5300, MCC: 0.0337, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67240 | val 0.77496
  Epoch 020 - train 0.66737 | val 0.79520
  Epoch 021 - train 0.66508 | val 0.78896
  Classification -> best τ=0.350 (val F1=0.0816)
  Directional -> Accuracy: 0.5550, MCC: 0.0508, F1: 0.6920

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.67999 | val 0.73641
  Epoch 020 - train 0.67879 | val 0.72873
  Epoch 021 - train 0.67704 | val 0.72991
  Classification -> best τ=0.445 (val F1=0.1180)
  Directional -> Accuracy: 0.5100, MCC: 0.0722, F1: 0.2899

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66722 | val 0.93068
  Epoch 020 - train 0.65459 | val 1.02840
  Epoch 021 - train 0.65394 | val 1.03162
  Classification -> best τ=0.510 (val F1=0.1388)
  Directional -> Accuracy: 0.5400, MCC: 0.0526, F1: 0.6068

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66269 | val 0.82456
  Epoch 020 - train 0.65421 | val 0.92762
  Epoch 021 - train 0.65455 | val 0.92837
  Classification -> best τ=0.475 (val F1=0.1662)
  Directional -> Accuracy: 0.4750, MCC: -0.0091, F1: 0.2105

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66585 | val 0.88530
  Epoch 020 - train 0.66505 | val 0.95421
  Epoch 021 - train 0.66516 | val 0.95207
  Classification -> best τ=0.650 (val F1=0.1373)
  Directional -> Accuracy: 0.5200, MCC: -0.0177, F1: 0.0588

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67843 | val 0.87006
  Epoch 020 - train 0.66648 | val 0.89688
  Epoch 021 - train 0.66407 | val 0.89615
  Classification -> best τ=0.445 (val F1=0.2210)
  Directional -> Accuracy: 0.4900, MCC: -0.0087, F1: 0.2388

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.68006 | val 0.73471
  Epoch 020 - train 0.67097 | val 0.74767
  Epoch 021 - train 0.66995 | val 0.75658
  Classification -> best τ=0.470 (val F1=0.1099)
  Directional -> Accuracy: 0.5250, MCC: 0.0343, F1: 0.4379

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.66969 | val 1.19318
  Epoch 020 - train 0.65087 | val 1.23386

[I 2026-02-26 00:23:36,751] Trial 15 finished with value: 0.13288614140668514 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 4.3121039246212396e-05, 'weight_decay': 2.7080299396494827e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.5833365742187508, 'early_stopping_min_delta': 5.552931825702633e-05}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 021 - train 0.66510 | val 0.99384
  Classification -> best τ=0.550 (val F1=0.1562)
  Directional -> Accuracy: 0.5050, MCC: -0.0695, F1: 0.0000

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.13288614140668514
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65299 | val 0.83076
  Epoch 020 - train 0.63036 | val 0.85103
  Epoch 021 - train 0.61967 | val 0.84021
  Classification -> best τ=0.430 (val F1=0.1092)
  Directional -> Accuracy: 0.4700, MCC: 0.0271, F1: 0.3690

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.62177 | val 1.94306
  Epoch 020 - train 0.59637 | val 2.22318
  Epoch 021 - train 0.58789 | val 2.21099
  Classification -> best τ=0.530 (val F1=0.1628)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63114 | val 0.76776
  Epoch 020 - train 0.60711 | val 0.80384
  Epoch 021 - train 0.61146 | val 0.77998
  Classification -> best τ=0.425 (val F1=0.1229)
  Directional -> Accuracy: 0.5775, MCC: 0.0480, F1: 0.7168

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.64870 | val 0.73914
  Epoch 020 - train 0.61167 | val 1.15462
  Epoch 023 - train 0.60012 | val 1.23554
  Classification -> best τ=0.485 (val F1=0.1655)
  Directional -> Accuracy: 0.5450, MCC: 0.0451, F1: 0.6403

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.62510 | val 1.04284
  Epoch 020 - train 0.59427 | val 1.22435
  Epoch 021 - train 0.57643 | val 1.20437
  Classification -> best τ=0.485 (val F1=0.1383)
  Directional -> Accuracy: 0.5514, MCC: 0.0971, F1: 0.6712

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63593 | val 0.91909
  Epoch 020 - train 0.60197 | val 1.11288
  Epoch 021 - train 0.59366 | val 1.14912
  Classification -> best τ=0.390 (val F1=0.1845)
  Directional -> Accuracy: 0.5250, MCC: -0.0707, F1: 0.6758

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64965 | val 1.50689
  Epoch 020 - train 0.63388 | val 1.93962
  Epoch 021 - train 0.63146 | val 2.17502
  Classification -> best τ=0.485 (val F1=0.1449)
  Directional -> Accuracy: 0.5450, MCC: 0.0240, F1: 0.6642

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62101 | val 1.05301
  Epoch 020 - train 0.58819 | val 1.27886
  Epoch 021 - train 0.58645 | val 1.26847
  Classification -> best τ=0.410 (val F1=0.3131)
  Directional -> Accuracy: 0.4800, MCC: 0.0925, F1: 0.3735

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61984 | val 1.89135
  Epoch 020 - train 0.58947 | val 2.21579
  Epoch 021 - train 0.58610 | val 2.26713
  Classification -> best τ=0.485 (val F1=0.1758)
  Directional -> Accuracy: 0.4174, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64421 | val 1.10470
  Epoch 020 - train 0.61786 | val 1.23579
  Epoch 021 - train 0.61280 | val 1.21705
  Classification -> best τ=0.365 (val F1=0.1449)
  Directional -> Accuracy: 0.4550, MCC: -0.0585, F1: 0.5477

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.64659 | val 0.90622
  Epoch 020 - train 0.60657 | val 0.81970
  Epoch 021 - train 0.60575 | val 0.82262
  Classification -> best τ=0.540 (val F1=0.1018)
  Directional -> Accuracy: 0.4600, MCC: -0.0081, F1: 0.0182

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.63886 | val 0.75230
  Epoch 020 - train 0.61985 | val 0.72847
  Epoch 021 - train 0.62575 | val 0.73120
  Classification -> best τ=0.460 (val F1=0.1267)
  Directional -> Accuracy: 0.4350, MCC: -0.0124, F1: 0.1504

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63181 | val 0.96646
  Epoch 020 - train 0.59377 | val 1.11761
  Epoch 021 - train 0.58416 | val 1.07288
  Classification -> best τ=0.530 (val F1=0.1239)
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61406 | val 0.93208
  Epoch 020 - train 0.58979 | val 1.05372
  Epoch 021 - train 0.58728 | val 1.06584
  Classification -> best τ=0.555 (val F1=0.2265)
  Directional -> Accuracy: 0.5050, MCC: 0.0023, F1: 0.0917

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.65025 | val 0.93430
  Epoch 020 - train 0.63297 | val 0.97585
  Epoch 021 - train 0.62780 | val 1.02061
  Classification -> best τ=0.380 (val F1=0.1025)
  Directional -> Accuracy: 0.5300, MCC: 0.0000, F1: 0.6928

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.62706 | val 1.52088
  Epoch 020 - train 0.59062 | val 1.94163
  Epoch 021 - train 0.60036 | val 1.88180
  Classification -> best τ=0.500 (val F1=0.1165)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.63828 | val 0.81507
  Epoch 020 - train 0.60049 | val 0.92730
  Epoch 021 - train 0.60581 | val 0.93994
  Classification -> best τ=0.480 (val F1=0.1231)
  Directional -> Accuracy: 0.5700, MCC: 0.1169, F1: 0.6356

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63558 | val 1.29703
  Epoch 020 - train 0.59586 | val 1.41440
  Epoch 021 - train 0.60038 | val 1.36841
  Classification -> best τ=0.440 (val F1=0.0952)
  Directional -> Accuracy: 0.4900, MCC: -0.0398, F1: 0.5952

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63185 | val 0.98495
  Epoch 020 - train 0.61569 | val 0.98697
  Epoch 021 - train 0.61595 | val 1.04145
  Classification -> best τ=0.410 (val F1=0.1082)
  Directional -> Accuracy: 0.5350, MCC: 0.0747, F1: 0.6043

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63948 | val 0.81083
  Epoch 020 - train 0.60653 | val 0.87033
  Epoch 021 - train 0.60948 | val 0.85724
  Classification -> best τ=0.525 (val F1=0.0863)
  Directional -> Accuracy: 0.4650, MCC: 0.0120, F1: 0.0696

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.64493 | val 0.73699
  Epoch 020 - train 0.60004 | val 0.78859
  Epoch 021 - train 0.60261 | val 0.78217
  Classification -> best τ=0.535 (val F1=0.1936)
  Directional -> Accuracy: 0.5500, MCC: 0.0982, F1: 0.4767

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.65197 | val 1.63714
  Epoch 020 - train 0.61667 | val 2.32680
  Epoch 021 - train 0.61990 | val 2.50060
  Classification -> best τ=0.420 (val F1=0.1523)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63194 | val 1.00897
  Epoch 020 - train 0.60941 | val 1.22968
  Epoch 021 - train 0.60731 | val 1.17668
  Classification -> best τ=0.475 (val F1=0.1415)
  Directional -> Accuracy: 0.4800, MCC: 0.0163, F1: 0.3067

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.63636 | val 1.01487
  Epoch 020 - train 0.60158 | val 1.18921
  Epoch 021 - train 0.60806 | val 1.12930
  Classification -> best τ=0.320 (val F1=0.1614)
  Directional -> Accuracy: 0.4100, MCC: 0.0426, F1: 0.5662

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63607 | val 1.14614
  Epoch 020 - train 0.60741 | val 1.36380
  Epoch 021 - train 0.58933 | val 1.36887
  Classification -> best τ=0.425 (val F1=0.1377)
  Directional -> Accuracy: 0.5300, MCC: 0.0798, F1: 0.4405

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64935 | val 0.81418
  Epoch 020 - train 0.61767 | val 0.92410
  Epoch 021 - train 0.60812 | val 0.91240
  Classification -> best τ=0.485 (val F1=0.1173)
  Directional -> Accuracy: 0.5350, MCC: 0.0700, F1: 0.5279

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63999 | val 0.77481
  Epoch 020 - train 0.61171 | val 0.89417
  Epoch 021 - train 0.61166 | val 0.91196
  Classification -> best τ=0.535 (val F1=0.1776)
  Directional -> Accuracy: 0.5100, MCC: 0.1068, F1: 0.2899

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.65007 | val 0.96355
  Epoch 020 - train 0.62889 | val 1.09503
  Epoch 021 - train 0.63207 | val 1.12012
  Classification -> best τ=0.475 (val F1=0.1050)
  Directional -> Accuracy: 0.5400, MCC: 0.0882, F1: 0.6198

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64369 | val 1.05292
  Epoch 020 - train 0.62525 | val 1.21809
  Epoch 021 - train 0.62069 | val 1.25811
  Classification -> best τ=0.630 (val F1=0.1517)
  Directional -> Accuracy: 0.4850, MCC: -0.0030, F1: 0.0190

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.65612 | val 0.83059
  Epoch 020 - train 0.62666 | val 1.00915
  Epoch 021 - train 0.62283 | val 1.11107
  Classification -> best τ=0.490 (val F1=0.1336)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.65278 | val 0.76788
  Epoch 020 - train 0.61702 | val 1.02749
  Epoch 021 - train 0.61158 | val 1.07063
  Classification -> best τ=0.490 (val F1=0.1595)
  Directional -> Accuracy: 0.4850, MCC: -0.1015, F1: 0.0000

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65950 | val 0.74675
  Epoch 020 - train 0.62375 | val 0.82650
  Epoch 024 - train 0.61712 | val 0.85211
  Classification -> best τ=0.365 (val F1=0.1759)
  Directional -> Accuracy: 0.5500, MCC: 0.0658, F1: 0.6400

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.65612 | val 0.85704
  Epoch 020 - train 0.63386 | val 0.89691
  Epoch 021 - train 0.63551 | val 0.88505
  Classification -> best τ=0.475 (val F1=0.1532)
  Directional -> Accuracy: 0.5050, MCC: -0.0998, F1: 0.6292

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63400 | val 0.87465
  Epoch 020 - train 0.60837 | val 0.92412
  Epoch 021 - train 0.60919 | val 0.94635
  Classification -> best τ=0.395 (val F1=0.1779)
  Directional -> Accuracy: 0.4600, MCC: -0.0057, F1: 0.5814

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.64940 | val 0.91306
  Epoch 020 - train 0.62355 | val 1.12102
  Epoch 021 - train 0.62088 | val 1.12872
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63156 | val 0.85077
  Epoch 020 - train 0.60267 | val 1.08768
  Epoch 021 - train 0.57980 | val 1.12610
  Classification -> best τ=0.510 (val F1=0.1445)
  Directional -> Accuracy: 0.4500, MCC: -0.0302, F1: 0.3678

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65039 | val 0.89097
  Epoch 020 - train 0.61894 | val 0.99057
  Epoch 021 - train 0.62264 | val 0.97243
  Classification -> best τ=0.550 (val F1=0.1361)
  Directional -> Accuracy: 0.4650, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.63637 | val 1.07218
  Epoch 020 - train 0.61164 | val 0.96443
  Epoch 021 - train 0.60920 | val 0.96791
  Classification -> best τ=0.465 (val F1=0.0665)
  Directional -> Accuracy: 0.4550, MCC: 0.0952, F1: 0.0840

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.63559 | val 1.32272
  Epoch 020 - train 0.60154 | val 1.74931
  Epoch 021 - train 0.59282 | val 1.74713
  Classification -> best τ=0.385 (val F1=0.0959)
  Directional -> Accuracy: 0.5450, MCC: 0.0000, F1: 0.7055

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.64377 | val 1.26999
  Epoch 020 - train 0.61575 | val 1.09169
  Epoch 021 - train 0.60363 | val 1.16110
  Classification -> best τ=0.465 (val F1=0.1490)
  Directional -> Accuracy: 0.4900, MCC: -0.0166, F1: 0.4848

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.64552 | val 0.90200
  Epoch 020 - train 0.61283 | val 1.10866
  Epoch 021 - train 0.61668 | val 1.13809
  Classification -> best τ=0.615 (val F1=0.1585)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63866 | val 1.10618
  Epoch 020 - train 0.61277 | val 1.16191
  Epoch 021 - train 0.62272 | val 1.18401
  Classification -> best τ=0.640 (val F1=0.0241)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63765 | val 1.32299
  Epoch 020 - train 0.61887 | val 1.59851
  Epoch 021 - train 0.61425 | val 1.39200
  Classification -> best τ=0.445 (val F1=0.1230)
  Directional -> Accuracy: 0.4600, MCC: -0.0940, F1: 0.5385

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63888 | val 0.83021
  Epoch 020 - train 0.60773 | val 0.97411
  Epoch 021 - train 0.60890 | val 0.94633
  Classification -> best τ=0.535 (val F1=0.1514)
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62631 | val 2.53665
  Epoch 020 - train 0.59426 | val 3.24363
  Epoch 021 - train 0.59746 | val 3.30256
  Classification -> best τ=0.295 (val F1=0.1201)
  Directional -> Accuracy: 0.5450, MCC: 0.0580, F1: 0.6691

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64096 | val 0.99329
  Epoch 020 - train 0.61367 | val 1.02165
  Epoch 021 - train 0.62206 | val 1.06016
  Classification -> best τ=0.470 (val F1=0.0848)
  Directional -> Accuracy: 0.4600, MCC: 0.0899, F1: 0.2174

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64996 | val 0.85343
  Epoch 020 - train 0.62182 | val 1.01513
  Epoch 021 - train 0.62133 | val 1.07204
  Classification -> best τ=0.420 (val F1=0.1398)
  Directional -> Accuracy: 0.5700, MCC: 0.1184, F1: 0.6293

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64190 | val 0.77580
  Epoch 020 - train 0.60505 | val 0.88802
  Epoch 021 - train 0.60274 | val 0.87956
  Classification -> best τ=0.510 (val F1=0.1004)
  Directional -> Accuracy: 0.3900, MCC: -0.1374, F1: 0.2907

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63775 | val 0.90089
  Epoch 020 - train 0.60956 | val 1.12888
  Epoch 021 - train 0.60481 | val 1.13141
  Classification -> best τ=0.495 (val F1=0.1432)
  Directional -> Accuracy: 0.4850, MCC: -0.0428, F1: 0.3355

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63196 | val 0.99455
  Epoch 020 - train 0.61262 | val 1.00019
  Epoch 021 - train 0.60837 | val 0.98904
  Classification -> best τ=0.545 (val F1=0.1212)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63489 | val 0.95065
  Epoch 020 - train 0.60173 | val 1.00159
  Epoch 021 - train 0.60343 | val 0.95895
  Classification -> best τ=0.415 (val F1=0.1231)
  Directional -> Accuracy: 0.5450, MCC: 0.0428, F1: 0.6431

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64539 | val 0.81019
  Epoch 020 - train 0.61192 | val 0.98736
  Epoch 021 - train 0.61581 | val 1.03362
  Classification -> best τ=0.515 (val F1=0.0775)
  Directional -> Accuracy: 0.4950, MCC: -0.0010, F1: 0.0194

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65076 | val 0.87804
  Epoch 020 - train 0.62307 | val 0.82127
  Epoch 021 - train 0.61282 | val 0.82247
  Classification -> best τ=0.565 (val F1=0.1582)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.64558 | val 0.90513
  Epoch 020 - train 0.61245 | val 0.94425
  Epoch 021 - train 0.60756 | val 1.04910
  Classification -> best τ=0.465 (val F1=0.1509)
  Directional -> Accuracy: 0.4350, MCC: 0.0043, F1: 0.2416

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.65028 | val 0.81828
  Epoch 020 - train 0.60975 | val 1.09764
  Epoch 021 - train 0.59612 | val 1.10863
  Classification -> best τ=0.425 (val F1=0.1732)
  Directional -> Accuracy: 0.4950, MCC: 0.0000, F1: 0.6622

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65341 | val 0.89527
  Epoch 020 - train 0.62374 | val 1.10753
  Epoch 021 - train 0.61823 | val 1.07434
  Classification -> best τ=0.720 (val F1=0.1284)
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64321 | val 0.79620
  Epoch 020 - train 0.61610 | val 0.80616
  Epoch 021 - train 0.60950 | val 0.82443
  Classification -> best τ=0.520 (val F1=0.0489)
  Directional -> Accuracy: 0.4500, MCC: -0.0144, F1: 0.0351

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.64329 | val 0.78642
  Epoch 020 - train 0.61314 | val 1.13996
  Epoch 021 - train 0.60617 | val 1.06225
  Classification -> best τ=0.575 (val F1=0.1256)
  Directional -> Accuracy: 0.5050, MCC: 0.0664, F1: 0.2556

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62102 | val 1.00715
  Epoch 020 - train 0.59901 | val 1.17103
  Epoch 021 - train 0.58739 | val 1.22534
  Classification -> best τ=0.360 (val F1=0.2097)
  Directional -> Accuracy: 0.5000, MCC: 0.0919, F1: 0.4118

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63496 | val 1.55316
  Epoch 020 - train 0.61368 | val 2.11854
  Epoch 021 - train 0.59763 | val 1.96751
  Classification -> best τ=0.435 (val F1=0.1919)
  Directional -> Accuracy: 0.4700, MCC: -0.0310, F1: 0.2838

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63588 | val 1.07779
  Epoch 020 - train 0.61411 | val 1.10227
  Epoch 021 - train 0.60206 | val 1.10649
  Classification -> best τ=0.600 (val F1=0.1120)
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63229 | val 0.84418
  Epoch 020 - train 0.60451 | val 0.87234
  Epoch 021 - train 0.60626 | val 0.90192
  Classification -> best τ=0.455 (val F1=0.1046)
  Directional -> Accuracy: 0.5050, MCC: -0.0053, F1: 0.6347

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.64231 | val 0.97086
  Epoch 020 - train 0.61429 | val 1.05138
  Epoch 021 - train 0.61952 | val 1.10020
  Classification -> best τ=0.455 (val F1=0.0811)
  Directional -> Accuracy: 0.5250, MCC: -0.0049, F1: 0.1880

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.61892 | val 1.15454
  Epoch 020 - train 0.57556 | val 1.28706

[I 2026-02-26 00:28:22,235] Trial 16 finished with value: 0.13436261249219203 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.000579650824321203, 'weight_decay': 1.5967945491720734e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.1198557161500746, 'early_stopping_min_delta': 0.0013576727959313927}. Best is trial 8 with value: 0.15238950933016568.

  Classification -> best τ=0.510 (val F1=0.1640)
  Directional -> Accuracy: 0.5100, MCC: 0.0055, F1: 0.1250

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.13436261249219203
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66942 | val 1.32170
  Epoch 020 - train 0.65892 | val 1.29220
  Epoch 021 - train 0.65448 | val 1.40887
  Classification -> best τ=0.780 (val F1=0.1596)
  Directional -> Accuracy: 0.4141, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.65710 | val 2.31842
  Epoch 020 - train 0.60650 | val 2.57479
  Epoch 022 - train 0.60224 | val 2.17829
  Classification -> best τ=0.300 (val F1=0.1386)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67113 | val 0.70478
  Epoch 020 - train 0.67625 | val 0.70159
  Epoch 030 - train 0.63443 | val 0.70837
  Epoch 031 - train 0.63750 | val 0.72650
  Classification -> best τ=0.410 (val F1=0.1925)
  Directional -> Accuracy: 0.4865, MCC: -0.0781, F1: 0.5815

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.67455 | val 0.71785
  Epoch 020 - train 0.63580 | val 0.87103
  Epoch 021 - train 0.63430 | val 0.77762
  Classification -> best τ=0.620 (val F1=0.1864)
  Directional -> Accuracy: 0.4242, MCC: -0.0782, F1: 0.1364

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.64673 | val 0.71429
  Epoch 020 - train 0.60668 | val 0.96175
  Epoch 023 - train 0.59746 | val 0.88165
  Classification -> best τ=0.525 (val F1=0.1750)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67945 | val 0.89047
  Epoch 020 - train 0.64121 | val 1.56332
  Epoch 024 - train 0.56057 | val 1.31034
  Classification -> best τ=0.680 (val F1=0.1487)
  Directional -> Accuracy: 0.4596, MCC: -0.0003, F1: 0.1705

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68285 | val 0.69892
  Epoch 020 - train 0.65367 | val 0.73825
  Epoch 027 - train 0.59933 | val 0.93453
  Classification -> best τ=0.620 (val F1=0.1443)
  Directional -> Accuracy: 0.5101, MCC: 0.0113, F1: 0.5530

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66375 | val 0.80945
  Epoch 020 - train 0.61475 | val 0.95289
  Epoch 023 - train 0.59794 | val 0.89438
  Classification -> best τ=0.585 (val F1=0.1576)
  Directional -> Accuracy: 0.3939, MCC: -0.0249, F1: 0.0769

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64033 | val 0.88171
  Epoch 020 - train 0.52796 | val 1.25594
  Epoch 021 - train 0.51950 | val 1.38634
  Classification -> best τ=0.390 (val F1=0.2019)
  Directional -> Accuracy: 0.5310, MCC: 0.0533, F1: 0.5760

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69141 | val 0.73649
  Epoch 020 - train 0.66655 | val 0.93955
  Epoch 030 - train 0.61764 | val 1.16915
  Epoch 031 - train 0.60671 | val 1.23419
  Classification -> best τ=0.450 (val F1=0.1659)
  Directional -> Accuracy: 0.5404, MCC: 0.0082, F1: 0.0215

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.69347 | val 0.75014
  Epoch 020 - train 0.66376 | val 0.89881
  Epoch 024 - train 0.62597 | val 0.71769
  Classification -> best τ=0.420 (val F1=0.1348)
  Directional -> Accuracy: 0.5556, MCC: 0.0768, F1: 0.6788

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.67639 | val 0.91352
  Epoch 020 - train 0.65407 | val 0.95450
  Epoch 024 - train 0.60949 | val 1.18674
  Classification -> best τ=0.410 (val F1=0.1727)
  Directional -> Accuracy: 0.4343, MCC: -0.0175, F1: 0.1642

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66874 | val 0.76582
  Epoch 020 - train 0.65245 | val 0.88219
  Epoch 022 - train 0.62066 | val 0.86866
  Classification -> best τ=0.570 (val F1=0.1167)
  Directional -> Accuracy: 0.5354, MCC: -0.0256, F1: 0.6738

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68415 | val 0.67900
  Epoch 020 - train 0.65119 | val 0.69718
  Epoch 027 - train 0.62385 | val 0.76107
  Classification -> best τ=0.490 (val F1=0.2286)
  Directional -> Accuracy: 0.5202, MCC: 0.0404, F1: 0.5178

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.66823 | val 0.92397
  Epoch 020 - train 0.64979 | val 1.03783
  Epoch 027 - train 0.61476 | val 1.65103
  Classification -> best τ=0.390 (val F1=0.1104)
  Directional -> Accuracy: 0.4444, MCC: -0.1057, F1: 0.4330

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.65416 | val 1.02501
  Epoch 020 - train 0.60237 | val 1.23329
  Epoch 023 - train 0.58455 | val 1.07032
  Classification -> best τ=0.670 (val F1=0.1029)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.67351 | val 0.74188
  Epoch 020 - train 0.64442 | val 0.76596
  Epoch 022 - train 0.64531 | val 0.76073
  Classification -> best τ=0.410 (val F1=0.1983)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64023 | val 1.17817
  Epoch 020 - train 0.56311 | val 2.96455
  Epoch 022 - train 0.54046 | val 2.45322
  Classification -> best τ=0.675 (val F1=0.1815)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65392 | val 0.74692
  Epoch 020 - train 0.59808 | val 1.12991
  Epoch 026 - train 0.54522 | val 1.46374
  Classification -> best τ=0.275 (val F1=0.2579)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68088 | val 0.83580
  Epoch 020 - train 0.62901 | val 1.07307
  Epoch 023 - train 0.59127 | val 1.14064
  Classification -> best τ=0.595 (val F1=0.1232)
  Directional -> Accuracy: 0.4495, MCC: -0.0631, F1: 0.0840

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.67183 | val 0.80554
  Epoch 020 - train 0.61883 | val 1.13818
  Epoch 023 - train 0.59107 | val 1.02840
  Classification -> best τ=0.645 (val F1=0.1841)
  Directional -> Accuracy: 0.5909, MCC: 0.2116, F1: 0.6611

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.68476 | val 0.72330
  Epoch 020 - train 0.65996 | val 1.29417
  Epoch 024 - train 0.62247 | val 1.82778
  Classification -> best τ=0.455 (val F1=0.1858)
  Directional -> Accuracy: 0.4697, MCC: 0.0854, F1: 0.1600

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65080 | val 1.10878
  Epoch 020 - train 0.62528 | val 1.42607
  Epoch 021 - train 0.60898 | val 1.71596
  Classification -> best τ=0.710 (val F1=0.1159)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.68800 | val 0.73686
  Epoch 020 - train 0.65257 | val 0.82589
  Epoch 021 - train 0.62832 | val 0.94477
  Classification -> best τ=0.360 (val F1=0.1212)
  Directional -> Accuracy: 0.4646, MCC: 0.0644, F1: 0.5470

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67292 | val 1.30364
  Epoch 020 - train 0.61269 | val 2.16027
  Epoch 021 - train 0.61734 | val 2.25197
  Classification -> best τ=0.395 (val F1=0.1196)
  Directional -> Accuracy: 0.5303, MCC: 0.0798, F1: 0.4624

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68701 | val 0.75111
  Epoch 020 - train 0.65001 | val 0.76096
  Epoch 022 - train 0.66302 | val 0.78769
  Classification -> best τ=0.375 (val F1=0.1670)
  Directional -> Accuracy: 0.5253, MCC: 0.0534, F1: 0.5481

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66052 | val 0.78773
  Epoch 020 - train 0.59743 | val 1.32879
  Epoch 023 - train 0.57726 | val 1.09566
  Classification -> best τ=0.590 (val F1=0.1650)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.68559 | val 0.71116
  Epoch 020 - train 0.66408 | val 0.71067
  Epoch 025 - train 0.64199 | val 0.80925
  Classification -> best τ=0.530 (val F1=0.1461)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65473 | val 0.84297
  Epoch 020 - train 0.60204 | val 1.27616
  Epoch 022 - train 0.61166 | val 1.15230
  Classification -> best τ=0.595 (val F1=0.1466)
  Directional -> Accuracy: 0.5101, MCC: 0.0544, F1: 0.2240

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.67926 | val 0.73848
  Epoch 020 - train 0.59626 | val 1.05033
  Epoch 024 - train 0.54938 | val 1.28494
  Classification -> best τ=0.490 (val F1=0.0865)
  Directional -> Accuracy: 0.4747, MCC: -0.0480, F1: 0.4902

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.66101 | val 0.99320
  Epoch 020 - train 0.63698 | val 1.66653
  Epoch 029 - train 0.53780 | val 1.19851
  Classification -> best τ=0.365 (val F1=0.1370)
  Directional -> Accuracy: 0.4899, MCC: -0.0184, F1: 0.4712

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66600 | val 0.71203
  Epoch 020 - train 0.61817 | val 0.77131
  Epoch 023 - train 0.56571 | val 0.91865
  Classification -> best τ=0.555 (val F1=0.1289)
  Directional -> Accuracy: 0.4596, MCC: -0.0170, F1: 0.2411

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.67569 | val 0.73788
  Epoch 020 - train 0.67088 | val 0.71943
  Epoch 030 - train 0.62820 | val 0.85653
  Epoch 034 - train 0.61552 | val 0.75639
  Classification -> best τ=0.480 (val F1=0.1051)
  Directional -> Accuracy: 0.5152, MCC: -0.0784, F1: 0.6364

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66695 | val 0.76200
  Epoch 020 - train 0.64068 | val 1.56481
  Epoch 023 - train 0.61251 | val 1.53166
  Classification -> best τ=0.500 (val F1=0.1003)
  Directional -> Accuracy: 0.5505, MCC: 0.0385, F1: 0.2764

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.57152 | val 1.66720
  Epoch 020 - train 0.48870 | val 2.17619
  Epoch 021 - train 0.43881 | val 1.86921
  Classification -> best τ=0.365 (val F1=0.2341)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6567

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66090 | val 0.73235
  Epoch 020 - train 0.60757 | val 0.74363
  Epoch 023 - train 0.57279 | val 0.89686
  Classification -> best τ=0.550 (val F1=0.1871)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67347 | val 0.79008
  Epoch 020 - train 0.65076 | val 0.79796
  Epoch 029 - train 0.57990 | val 1.23370
  Classification -> best τ=0.735 (val F1=0.1586)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.66576 | val 0.72125
  Epoch 020 - train 0.61466 | val 1.06406
  Epoch 024 - train 0.59013 | val 1.06635
  Classification -> best τ=0.535 (val F1=0.0995)
  Directional -> Accuracy: 0.4343, MCC: 0.0000, F1: 0.0000

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.66298 | val 1.01107
  Epoch 020 - train 0.64061 | val 2.37033
  Epoch 025 - train 0.58132 | val 2.47535
  Classification -> best τ=0.370 (val F1=0.0765)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.66682 | val 0.69480
  Epoch 020 - train 0.62301 | val 1.03078
  Epoch 030 - train 0.53555 | val 1.04544
  Classification -> best τ=0.615 (val F1=0.1256)
  Directional -> Accuracy: 0.4798, MCC: 0.0351, F1: 0.0374

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.68663 | val 0.69849
  Epoch 020 - train 0.62926 | val 1.29463
  Epoch 030 - train 0.58338 | val 1.71186
  Classification -> best τ=0.585 (val F1=0.1646)
  Directional -> Accuracy: 0.5152, MCC: 0.0816, F1: 0.2381

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66933 | val 0.79828
  Epoch 020 - train 0.63269 | val 0.89171
  Epoch 029 - train 0.52053 | val 1.43342
  Classification -> best τ=0.515 (val F1=0.1246)
  Directional -> Accuracy: 0.5505, MCC: 0.1005, F1: 0.5700

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67444 | val 1.40795
  Epoch 020 - train 0.64344 | val 1.54244
  Epoch 021 - train 0.65629 | val 2.01500
  Classification -> best τ=0.425 (val F1=0.1317)
  Directional -> Accuracy: 0.4798, MCC: -0.0410, F1: 0.4926

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66928 | val 0.73412
  Epoch 020 - train 0.63529 | val 0.80421
  Epoch 023 - train 0.62685 | val 0.82217
  Classification -> best τ=0.680 (val F1=0.1300)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66925 | val 1.05968
  Epoch 020 - train 0.58298 | val 1.80564
  Epoch 022 - train 0.55329 | val 1.96270
  Classification -> best τ=0.345 (val F1=0.1608)
  Directional -> Accuracy: 0.5253, MCC: -0.0553, F1: 0.6824

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66354 | val 0.79259
  Epoch 020 - train 0.60624 | val 1.85697
  Epoch 023 - train 0.59613 | val 1.64320
  Classification -> best τ=0.650 (val F1=0.0652)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68037 | val 0.69056
  Epoch 020 - train 0.62253 | val 0.75387
  Epoch 027 - train 0.55442 | val 0.91850
  Classification -> best τ=0.470 (val F1=0.1468)
  Directional -> Accuracy: 0.5606, MCC: 0.0000, F1: 0.7184

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68047 | val 0.84991
  Epoch 020 - train 0.61485 | val 1.17014
  Epoch 024 - train 0.57895 | val 1.46636
  Classification -> best τ=0.515 (val F1=0.0374)
  Directional -> Accuracy: 0.4192, MCC: -0.0191, F1: 0.2069

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66442 | val 0.78287
  Epoch 020 - train 0.60347 | val 1.01036
  Epoch 023 - train 0.60144 | val 1.14992
  Classification -> best τ=0.345 (val F1=0.1735)
  Directional -> Accuracy: 0.5051, MCC: 0.0507, F1: 0.6370

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67879 | val 0.83899
  Epoch 020 - train 0.65015 | val 0.98222
  Epoch 023 - train 0.63233 | val 1.17953
  Classification -> best τ=0.570 (val F1=0.0944)
  Directional -> Accuracy: 0.4343, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68285 | val 0.70412
  Epoch 020 - train 0.64370 | val 0.86661
  Epoch 022 - train 0.62429 | val 0.93311
  Classification -> best τ=0.475 (val F1=0.0389)
  Directional -> Accuracy: 0.5808, MCC: 0.1198, F1: 0.7088

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66750 | val 0.72282
  Epoch 020 - train 0.61206 | val 1.13670
  Epoch 030 - train 0.50876 | val 1.44563
  Classification -> best τ=0.500 (val F1=0.1182)
  Directional -> Accuracy: 0.4798, MCC: -0.0840, F1: 0.0374

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67570 | val 0.85500
  Epoch 020 - train 0.64260 | val 0.89104
  Epoch 028 - train 0.59508 | val 1.31985
  Classification -> best τ=0.485 (val F1=0.1079)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.65030 | val 0.75455
  Epoch 020 - train 0.58857 | val 0.75667
  Epoch 026 - train 0.56612 | val 1.04875
  Classification -> best τ=0.490 (val F1=0.1504)
  Directional -> Accuracy: 0.4141, MCC: -0.0138, F1: 0.1212

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.68335 | val 0.72822
  Epoch 020 - train 0.64667 | val 0.79288
  Epoch 023 - train 0.64306 | val 0.92211
  Classification -> best τ=0.510 (val F1=0.1436)
  Directional -> Accuracy: 0.4798, MCC: -0.0391, F1: 0.5381

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67005 | val 2.73473
  Epoch 020 - train 0.63161 | val 2.32244
  Epoch 023 - train 0.62294 | val 2.02866
  Classification -> best τ=0.735 (val F1=0.1220)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66804 | val 0.79360
  Epoch 020 - train 0.64703 | val 1.31208
  Epoch 023 - train 0.60866 | val 1.48210
  Classification -> best τ=0.645 (val F1=0.0406)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.67228 | val 0.70538
  Epoch 020 - train 0.65468 | val 0.87174
  Epoch 022 - train 0.62856 | val 0.89798
  Classification -> best τ=0.555 (val F1=0.1124)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66051 | val 0.81445
  Epoch 020 - train 0.62332 | val 0.98205
  Epoch 021 - train 0.61456 | val 0.95872
  Classification -> best τ=0.240 (val F1=0.2285)
  Directional -> Accuracy: 0.4949, MCC: -0.0169, F1: 0.5413

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66767 | val 0.80797
  Epoch 020 - train 0.60091 | val 1.10460
  Epoch 025 - train 0.55931 | val 1.31410
  Classification -> best τ=0.495 (val F1=0.1477)
  Directional -> Accuracy: 0.5000, MCC: 0.0277, F1: 0.4142

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67356 | val 1.21713
  Epoch 020 - train 0.62803 | val 1.77535
  Epoch 024 - train 0.56616 | val 2.40082
  Classification -> best τ=0.250 (val F1=0.1096)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.6485

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65952 | val 0.86526
  Epoch 020 - train 0.61021 | val 1.11364
  Epoch 021 - train 0.56639 | val 1.64391
  Classification -> best τ=0.635 (val F1=0.1206)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.65855 | val 0.71170
  Epoch 020 - train 0.62082 | val 0.87712
  Epoch 022 - train 0.62534 | val 0.88409
  Classification -> best τ=0.410 (val F1=0.0944)
  Directional -> Accuracy: 0.5505, MCC: 0.0810, F1: 0.3407

[64/88] Processing PM...

Processing PM (Consumer Goods)...

[I 2026-02-26 00:41:39,449] Trial 17 finished with value: 0.1447683860488279 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 16, 'learning_rate': 0.0041348559075932425, 'weight_decay': 1.0931907050693564e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.8947094981195591, 'early_stopping_min_delta': 0.003011767065801797}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 021 - train 0.63912 | val 1.54128
  Classification -> best τ=0.370 (val F1=0.1068)
  Directional -> Accuracy: 0.5000, MCC: 0.0012, F1: 0.5263

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1447683860488279
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65692 | val 0.80976
  Epoch 020 - train 0.65467 | val 0.85008
  Epoch 021 - train 0.65164 | val 0.81194
  Classification -> best τ=0.510 (val F1=0.1207)
  Directional -> Accuracy: 0.4774, MCC: 0.0392, F1: 0.3810

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.66998 | val 1.58640
  Epoch 020 - train 0.62666 | val 1.69224
  Epoch 021 - train 0.62423 | val 1.81772
  Classification -> best τ=0.585 (val F1=0.1224)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65681 | val 0.78788
  Epoch 020 - train 0.64810 | val 0.79259
  Epoch 021 - train 0.64777 | val 0.89090
  Classification -> best τ=0.485 (val F1=0.1287)
  Directional -> Accuracy: 0.5269, MCC: 0.0382, F1: 0.5810

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.66117 | val 0.71000
  Epoch 020 - train 0.64584 | val 0.75664
  Epoch 021 - train 0.64607 | val 0.82709
  Classification -> best τ=0.470 (val F1=0.0500)
  Directional -> Accuracy: 0.4925, MCC: 0.0647, F1: 0.3567

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.62763 | val 0.73898
  Epoch 020 - train 0.60444 | val 0.73484
  Epoch 021 - train 0.57904 | val 0.72643
  Classification -> best τ=0.515 (val F1=0.2027)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66640 | val 0.83550
  Epoch 020 - train 0.62667 | val 0.95614
  Epoch 021 - train 0.64667 | val 0.92647
  Classification -> best τ=0.525 (val F1=0.1423)
  Directional -> Accuracy: 0.4422, MCC: -0.0790, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67418 | val 0.91182
  Epoch 020 - train 0.64896 | val 0.95344
  Epoch 021 - train 0.65508 | val 1.06728
  Classification -> best τ=0.505 (val F1=0.1250)
  Directional -> Accuracy: 0.4422, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64716 | val 0.67695
  Epoch 020 - train 0.60548 | val 0.80360
  Epoch 024 - train 0.58556 | val 0.86601
  Classification -> best τ=0.460 (val F1=0.2326)
  Directional -> Accuracy: 0.3920, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64148 | val 1.07640
  Epoch 020 - train 0.60780 | val 0.82634
  Epoch 021 - train 0.60875 | val 0.78214
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5789, MCC: 0.0000, F1: 0.7333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66422 | val 0.97653
  Epoch 020 - train 0.63229 | val 1.34439
  Epoch 021 - train 0.63718 | val 1.80136
  Classification -> best τ=0.525 (val F1=0.0922)
  Directional -> Accuracy: 0.5377, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.66475 | val 1.07893
  Epoch 020 - train 0.63679 | val 0.99548
  Epoch 021 - train 0.64207 | val 0.86751
  Classification -> best τ=0.485 (val F1=0.0443)
  Directional -> Accuracy: 0.5327, MCC: 0.0405, F1: 0.6109

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.63363 | val 0.80495
  Epoch 020 - train 0.61424 | val 0.80158
  Epoch 021 - train 0.61310 | val 0.87844
  Classification -> best τ=0.575 (val F1=0.1037)
  Directional -> Accuracy: 0.4221, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65597 | val 0.76241
  Epoch 020 - train 0.62959 | val 0.73496
  Epoch 021 - train 0.64037 | val 0.72092
  Classification -> best τ=0.540 (val F1=0.1292)
  Directional -> Accuracy: 0.5377, MCC: 0.0242, F1: 0.6378

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64984 | val 0.72618
  Epoch 020 - train 0.60171 | val 0.94236
  Epoch 021 - train 0.59544 | val 0.94018
  Classification -> best τ=0.465 (val F1=0.1480)
  Directional -> Accuracy: 0.5327, MCC: 0.0674, F1: 0.5714

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.66971 | val 0.84913
  Epoch 020 - train 0.65276 | val 0.92743
  Epoch 021 - train 0.64407 | val 1.00207
  Classification -> best τ=0.510 (val F1=0.0908)
  Directional -> Accuracy: 0.4673, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.65904 | val 0.78231
  Epoch 020 - train 0.62363 | val 0.78113
  Epoch 021 - train 0.60919 | val 0.82374
  Classification -> best τ=0.510 (val F1=0.0838)
  Directional -> Accuracy: 0.5025, MCC: 0.0707, F1: 0.0198

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.65849 | val 0.73686
  Epoch 020 - train 0.62962 | val 0.90738
  Epoch 025 - train 0.63604 | val 0.83593
  Classification -> best τ=0.370 (val F1=0.1813)
  Directional -> Accuracy: 0.5578, MCC: 0.0000, F1: 0.7161

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64392 | val 1.33669
  Epoch 020 - train 0.59833 | val 1.83959
  Epoch 021 - train 0.60834 | val 1.93451
  Classification -> best τ=0.605 (val F1=0.0925)
  Directional -> Accuracy: 0.4824, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66907 | val 0.68399
  Epoch 020 - train 0.62339 | val 0.76451
  Epoch 022 - train 0.61451 | val 0.87036
  Classification -> best τ=0.475 (val F1=0.2634)
  Directional -> Accuracy: 0.4774, MCC: -0.0659, F1: 0.1475

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66038 | val 0.80914
  Epoch 020 - train 0.62922 | val 0.81703
  Epoch 021 - train 0.62947 | val 0.87522
  Classification -> best τ=0.505 (val F1=0.0891)
  Directional -> Accuracy: 0.4623, MCC: -0.0107, F1: 0.1575

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.65686 | val 0.82678
  Epoch 020 - train 0.60383 | val 0.89563
  Epoch 021 - train 0.61706 | val 0.93406
  Classification -> best τ=0.500 (val F1=0.1296)
  Directional -> Accuracy: 0.5327, MCC: 0.0716, F1: 0.5830

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.67253 | val 0.82552
  Epoch 020 - train 0.66417 | val 1.04077
  Epoch 021 - train 0.65441 | val 1.03323
  Classification -> best τ=0.475 (val F1=0.0821)
  Directional -> Accuracy: 0.5678, MCC: 0.0990, F1: 0.6504

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67954 | val 0.77056
  Epoch 020 - train 0.63650 | val 0.85432
  Epoch 021 - train 0.63481 | val 0.85694
  Classification -> best τ=0.475 (val F1=0.1008)
  Directional -> Accuracy: 0.4573, MCC: -0.0086, F1: 0.0182

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.65540 | val 0.88993
  Epoch 020 - train 0.62182 | val 0.96225
  Epoch 021 - train 0.62060 | val 0.94902
  Classification -> best τ=0.545 (val F1=0.1275)
  Directional -> Accuracy: 0.6080, MCC: 0.0000, F1: 0.0000

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67051 | val 1.32514
  Epoch 020 - train 0.63118 | val 1.08410
  Epoch 021 - train 0.63263 | val 1.35893
  Classification -> best τ=0.440 (val F1=0.1053)
  Directional -> Accuracy: 0.5477, MCC: 0.0888, F1: 0.6691

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65327 | val 0.88487
  Epoch 020 - train 0.62963 | val 0.84951
  Epoch 021 - train 0.63954 | val 0.90100
  Classification -> best τ=0.545 (val F1=0.1602)
  Directional -> Accuracy: 0.5678, MCC: 0.1349, F1: 0.4756

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64655 | val 1.36290
  Epoch 020 - train 0.61334 | val 2.14156
  Epoch 021 - train 0.59894 | val 2.37753
  Classification -> best τ=0.505 (val F1=0.1644)
  Directional -> Accuracy: 0.4824, MCC: 0.0526, F1: 0.2016

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.66761 | val 0.96975
  Epoch 020 - train 0.64886 | val 1.11705
  Epoch 021 - train 0.64163 | val 1.26025
  Classification -> best τ=0.460 (val F1=0.0076)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.6644

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67146 | val 0.91763
  Epoch 020 - train 0.64129 | val 1.04889
  Epoch 021 - train 0.64564 | val 1.13789
  Classification -> best τ=0.565 (val F1=0.1334)
  Directional -> Accuracy: 0.5126, MCC: 0.0774, F1: 0.1983

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.65948 | val 0.90745
  Epoch 020 - train 0.63448 | val 0.85119
  Epoch 021 - train 0.64063 | val 0.89541
  Classification -> best τ=0.480 (val F1=0.0747)
  Directional -> Accuracy: 0.4422, MCC: -0.0985, F1: 0.0348

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.65206 | val 0.84132
  Epoch 020 - train 0.61419 | val 1.19460
  Epoch 021 - train 0.62421 | val 1.00595
  Classification -> best τ=0.475 (val F1=0.1633)
  Directional -> Accuracy: 0.4975, MCC: 0.0183, F1: 0.1071

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67883 | val 0.71156
  Epoch 020 - train 0.64081 | val 0.74927
  Epoch 021 - train 0.65644 | val 0.75220
  Classification -> best τ=0.510 (val F1=0.0443)
  Directional -> Accuracy: 0.4673, MCC: -0.0028, F1: 0.2933

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.67845 | val 0.74700
  Epoch 020 - train 0.65408 | val 0.83320
  Epoch 021 - train 0.64223 | val 0.84316
  Classification -> best τ=0.485 (val F1=0.1065)
  Directional -> Accuracy: 0.6131, MCC: 0.0885, F1: 0.7586

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66408 | val 1.58033
  Epoch 020 - train 0.64347 | val 1.61395
  Epoch 021 - train 0.63587 | val 1.65430
  Classification -> best τ=0.465 (val F1=0.1023)
  Directional -> Accuracy: 0.4673, MCC: -0.0358, F1: 0.5138

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.59160 | val 1.09297
  Epoch 020 - train 0.54046 | val 1.60559
  Epoch 021 - train 0.55101 | val 1.86333
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65870 | val 0.96036
  Epoch 020 - train 0.61554 | val 1.06296
  Epoch 021 - train 0.62523 | val 0.83829
  Classification -> best τ=0.495 (val F1=0.1719)
  Directional -> Accuracy: 0.4171, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66062 | val 0.96877
  Epoch 020 - train 0.64884 | val 1.65205
  Epoch 021 - train 0.64650 | val 1.34082
  Classification -> best τ=0.545 (val F1=0.1745)
  Directional -> Accuracy: 0.4673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.66677 | val 1.21907
  Epoch 020 - train 0.65490 | val 1.79442
  Epoch 021 - train 0.63585 | val 1.42655
  Classification -> best τ=0.450 (val F1=0.0169)
  Directional -> Accuracy: 0.5678, MCC: 0.0347, F1: 0.7133

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.66439 | val 1.73351
  Epoch 020 - train 0.64861 | val 1.87146
  Epoch 021 - train 0.64683 | val 1.93413
  Classification -> best τ=0.520 (val F1=0.0933)
  Directional -> Accuracy: 0.5628, MCC: 0.1022, F1: 0.6420

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.67402 | val 1.22202
  Epoch 020 - train 0.64603 | val 1.78601
  Epoch 021 - train 0.63563 | val 2.02883
  Classification -> best τ=0.465 (val F1=0.0771)
  Directional -> Accuracy: 0.5477, MCC: 0.0781, F1: 0.6512

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.65756 | val 0.89479
  Epoch 020 - train 0.64413 | val 1.14292
  Epoch 021 - train 0.61652 | val 1.29759
  Classification -> best τ=0.520 (val F1=0.1437)
  Directional -> Accuracy: 0.4975, MCC: -0.0690, F1: 0.6528

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65945 | val 0.89383
  Epoch 020 - train 0.63352 | val 1.31668
  Epoch 021 - train 0.61511 | val 0.91394
  Classification -> best τ=0.485 (val F1=0.0786)
  Directional -> Accuracy: 0.5578, MCC: 0.0804, F1: 0.6716

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65794 | val 1.26031
  Epoch 020 - train 0.64137 | val 1.54689
  Epoch 021 - train 0.62968 | val 1.20682
  Classification -> best τ=0.500 (val F1=0.0993)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66401 | val 0.80509
  Epoch 020 - train 0.64627 | val 0.95323
  Epoch 021 - train 0.64217 | val 0.95323
  Classification -> best τ=0.505 (val F1=0.1127)
  Directional -> Accuracy: 0.4874, MCC: -0.0105, F1: 0.4000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65185 | val 1.70946
  Epoch 020 - train 0.61453 | val 2.73276
  Epoch 021 - train 0.62229 | val 2.51243
  Classification -> best τ=0.395 (val F1=0.0780)
  Directional -> Accuracy: 0.5276, MCC: 0.0128, F1: 0.6466

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66590 | val 0.82306
  Epoch 020 - train 0.65295 | val 0.98894
  Epoch 021 - train 0.65586 | val 1.03646
  Classification -> best τ=0.515 (val F1=0.0466)
  Directional -> Accuracy: 0.4975, MCC: -0.0114, F1: 0.5455

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66074 | val 0.89216
  Epoch 020 - train 0.62630 | val 0.96011
  Epoch 021 - train 0.61684 | val 0.91445
  Classification -> best τ=0.510 (val F1=0.1428)
  Directional -> Accuracy: 0.5075, MCC: 0.0988, F1: 0.3797

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64644 | val 1.11793
  Epoch 020 - train 0.61780 | val 1.88766
  Epoch 021 - train 0.60640 | val 2.74650
  Classification -> best τ=0.535 (val F1=0.0846)
  Directional -> Accuracy: 0.3970, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64948 | val 1.95989
  Epoch 020 - train 0.62412 | val 2.44124
  Epoch 021 - train 0.63707 | val 1.45223
  Classification -> best τ=0.455 (val F1=0.1245)
  Directional -> Accuracy: 0.4975, MCC: 0.0143, F1: 0.6154

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65334 | val 0.94709
  Epoch 020 - train 0.63764 | val 0.81608
  Epoch 021 - train 0.63288 | val 0.93064
  Classification -> best τ=0.510 (val F1=0.0380)
  Directional -> Accuracy: 0.5075, MCC: 0.0939, F1: 0.4024

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67723 | val 1.25949
  Epoch 020 - train 0.66265 | val 0.96914
  Epoch 021 - train 0.67309 | val 0.87837
  Classification -> best τ=0.500 (val F1=0.1275)
  Directional -> Accuracy: 0.4472, MCC: 0.0271, F1: 0.0351

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66187 | val 0.86257
  Epoch 020 - train 0.61921 | val 0.81184
  Epoch 021 - train 0.63418 | val 0.90147
  Classification -> best τ=0.535 (val F1=0.0806)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66690 | val 0.79419
  Epoch 020 - train 0.64044 | val 0.81126
  Epoch 021 - train 0.64309 | val 0.83611
  Classification -> best τ=0.475 (val F1=0.0944)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.65916 | val 0.91368
  Epoch 020 - train 0.64853 | val 1.21914
  Epoch 021 - train 0.63889 | val 1.34138
  Classification -> best τ=0.475 (val F1=0.1512)
  Directional -> Accuracy: 0.4070, MCC: -0.0188, F1: 0.0781

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.67001 | val 1.44727
  Epoch 020 - train 0.63035 | val 1.41686
  Epoch 021 - train 0.62972 | val 1.43801
  Classification -> best τ=0.460 (val F1=0.1312)
  Directional -> Accuracy: 0.4874, MCC: -0.0597, F1: 0.6507

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65773 | val 0.96673
  Epoch 020 - train 0.65041 | val 1.22162
  Epoch 021 - train 0.64654 | val 0.92377
  Classification -> best τ=0.505 (val F1=0.0995)
  Directional -> Accuracy: 0.5276, MCC: 0.0392, F1: 0.6210

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65314 | val 0.80809
  Epoch 020 - train 0.65125 | val 0.90095
  Epoch 021 - train 0.62555 | val 0.87299
  Classification -> best τ=0.530 (val F1=0.0760)
  Directional -> Accuracy: 0.4874, MCC: 0.0450, F1: 0.3014

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.66915 | val 0.87371
  Epoch 020 - train 0.63302 | val 0.84052
  Epoch 021 - train 0.63901 | val 1.01665
  Classification -> best τ=0.445 (val F1=0.1388)
  Directional -> Accuracy: 0.4925, MCC: 0.0263, F1: 0.2837

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63915 | val 0.71586
  Epoch 020 - train 0.60757 | val 0.86423
  Epoch 021 - train 0.61435 | val 0.88124
  Classification -> best τ=0.515 (val F1=0.1645)
  Directional -> Accuracy: 0.4472, MCC: -0.0304, F1: 0.3452

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65288 | val 0.87343
  Epoch 020 - train 0.62867 | val 0.84867
  Epoch 021 - train 0.60881 | val 1.17921
  Classification -> best τ=0.520 (val F1=0.0809)
  Directional -> Accuracy: 0.5377, MCC: 0.0852, F1: 0.5208

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65567 | val 1.29223
  Epoch 020 - train 0.60918 | val 1.48022
  Epoch 021 - train 0.61011 | val 1.30555
  Classification -> best τ=0.425 (val F1=0.0744)
  Directional -> Accuracy: 0.4774, MCC: 0.0000, F1: 0.6463

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65527 | val 1.03044
  Epoch 020 - train 0.60519 | val 1.32244
  Epoch 021 - train 0.61398 | val 1.06196
  Classification -> best τ=0.460 (val F1=0.1456)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.65635 | val 0.70106
  Epoch 020 - train 0.63414 | val 0.71191
  Epoch 021 - train 0.62008 | val 0.72959
  Classification -> best τ=0.450 (val F1=0.0666)
  Directional -> Accuracy: 0.4874, MCC: 0.0023, F1: 0.5641

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.65059 | val 1.47553
  Epoch 020 - train 0.61916 | val 1.04057

[I 2026-02-26 00:57:05,136] Trial 18 finished with value: 0.11732882957553943 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.0012477390883244425, 'weight_decay': 3.87021735941122e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.332493599503893, 'early_stopping_min_delta': 0.00940483011114811}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 021 - train 0.62258 | val 0.87839
  Classification -> best τ=0.485 (val F1=0.1130)
  Directional -> Accuracy: 0.5126, MCC: 0.0993, F1: 0.6644

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.11732882957553943
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65279 | val 0.86379
  Epoch 011 - train 0.65055 | val 0.86719
  Classification -> best τ=0.315 (val F1=0.1315)
  Directional -> Accuracy: 0.5200, MCC: -0.0941, F1: 0.6596

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.63228 | val 0.86552
  Epoch 011 - train 0.62182 | val 0.91489
  Classification -> best τ=0.585 (val F1=0.1546)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65368 | val 0.75458
  Epoch 011 - train 0.63446 | val 0.75608
  Classification -> best τ=0.435 (val F1=0.0873)
  Directional -> Accuracy: 0.5615, MCC: 0.0923, F1: 0.6306

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.66582 | val 0.72306
  Epoch 011 - train 0.65873 | val 0.71608
  Classification -> best τ=0.530 (val F1=0.1255)
  Directional -> Accuracy: 0.4900, MCC: 0.0613, F1: 0.3377

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.60397 | val 0.71533
  Epoch 011 - train 0.59534 | val 0.73573
  Classification -> best τ=0.570 (val F1=0.1314)
  Directional -> Accuracy: 0.4766, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66216 | val 0.77357
  Epoch 011 - train 0.65955 | val 0.70427
  Classification -> best τ=0.510 (val F1=0.0919)
  Directional -> Accuracy: 0.4700, MCC: -0.0571, F1: 0.4904

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66650 | val 0.88156
  Epoch 011 - train 0.66450 | val 0.86581
  Classification -> best τ=0.565 (val F1=0.1391)
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65619 | val 0.72174
  Epoch 012 - train 0.64039 | val 0.70616
  Classification -> best τ=0.440 (val F1=0.1866)
  Directional -> Accuracy: 0.5450, MCC: 0.0501, F1: 0.6224

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59880 | val 0.77648
  Epoch 011 - train 0.60088 | val 0.75966
  Classification -> best τ=0.470 (val F1=0.0995)
  Directional -> Accuracy: 0.4174, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65879 | val 0.79345
  Epoch 011 - train 0.65691 | val 0.84659
  Classification -> best τ=0.595 (val F1=0.0616)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.65206 | val 0.70334
  Epoch 011 - train 0.63754 | val 0.70447
  Classification -> best τ=0.580 (val F1=0.1873)
  Directional -> Accuracy: 0.5050, MCC: 0.0108, F1: 0.5217

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.66278 | val 0.72762
  Epoch 012 - train 0.62731 | val 0.76882
  Classification -> best τ=0.355 (val F1=0.1470)
  Directional -> Accuracy: 0.5750, MCC: 0.0152, F1: 0.7284

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63760 | val 0.70861
  Epoch 011 - train 0.62319 | val 0.71307
  Classification -> best τ=0.545 (val F1=0.0995)
  Directional -> Accuracy: 0.4550, MCC: -0.0734, F1: 0.4467

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64335 | val 0.81289
  Epoch 011 - train 0.62551 | val 0.87799
  Classification -> best τ=0.505 (val F1=0.1776)
  Directional -> Accuracy: 0.4950, MCC: 0.0000, F1: 0.6622

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.66326 | val 0.74046
  Epoch 011 - train 0.65709 | val 0.77844
  Classification -> best τ=0.490 (val F1=0.1250)
  Directional -> Accuracy: 0.4700, MCC: -0.0060, F1: 0.0185

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.65845 | val 0.76735
  Epoch 011 - train 0.64215 | val 0.79614
  Classification -> best τ=0.485 (val F1=0.0859)
  Directional -> Accuracy: 0.5100, MCC: 0.0297, F1: 0.2222

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.67477 | val 0.76213
  Epoch 011 - train 0.67339 | val 0.76032
  Classification -> best τ=0.580 (val F1=0.1100)
  Directional -> Accuracy: 0.5300, MCC: 0.1058, F1: 0.4659

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64794 | val 0.73099
  Epoch 011 - train 0.62118 | val 0.75848
  Classification -> best τ=0.460 (val F1=0.1305)
  Directional -> Accuracy: 0.4750, MCC: -0.0652, F1: 0.5607

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63324 | val 0.72204
  Epoch 012 - train 0.63360 | val 0.72907
  Classification -> best τ=0.480 (val F1=0.2535)
  Directional -> Accuracy: 0.4950, MCC: -0.0157, F1: 0.1789

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66625 | val 0.73406
  Epoch 011 - train 0.66310 | val 0.70667
  Classification -> best τ=0.415 (val F1=0.0461)
  Directional -> Accuracy: 0.5600, MCC: 0.1048, F1: 0.7027

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.65544 | val 0.76873
  Epoch 011 - train 0.64110 | val 0.82498
  Classification -> best τ=0.410 (val F1=0.1176)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.6577

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.66334 | val 0.79645
  Epoch 014 - train 0.64817 | val 0.76855
  Classification -> best τ=0.520 (val F1=0.1174)
  Directional -> Accuracy: 0.4500, MCC: 0.0573, F1: 0.0833

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66330 | val 0.78585
  Epoch 011 - train 0.64750 | val 0.75543
  Classification -> best τ=0.470 (val F1=0.0760)
  Directional -> Accuracy: 0.5300, MCC: -0.0443, F1: 0.6846

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.64689 | val 0.92075
  Epoch 012 - train 0.64226 | val 0.86533
  Classification -> best τ=0.275 (val F1=0.1345)
  Directional -> Accuracy: 0.4000, MCC: 0.0573, F1: 0.5683

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65181 | val 0.99581
  Epoch 011 - train 0.63250 | val 1.16730
  Classification -> best τ=0.400 (val F1=0.1432)
  Directional -> Accuracy: 0.4700, MCC: -0.0525, F1: 0.4176

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65343 | val 0.84113
  Epoch 011 - train 0.65051 | val 0.84193
  Classification -> best τ=0.390 (val F1=0.1493)
  Directional -> Accuracy: 0.5350, MCC: 0.0829, F1: 0.5903

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64164 | val 0.76787
  Epoch 011 - train 0.63609 | val 0.81143
  Classification -> best τ=0.560 (val F1=0.0789)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.67517 | val 0.76123
  Epoch 018 - train 0.65260 | val 0.70863
  Classification -> best τ=0.460 (val F1=0.0768)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66161 | val 0.76100
  Epoch 011 - train 0.65477 | val 0.78389
  Classification -> best τ=0.510 (val F1=0.1319)
  Directional -> Accuracy: 0.4850, MCC: -0.0438, F1: 0.5690

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.64061 | val 0.80124
  Epoch 011 - train 0.63142 | val 0.84798
  Classification -> best τ=0.450 (val F1=0.1100)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.65948 | val 0.99427
  Epoch 016 - train 0.59811 | val 0.75489
  Classification -> best τ=0.480 (val F1=0.1183)
  Directional -> Accuracy: 0.5250, MCC: 0.0516, F1: 0.4974

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67203 | val 0.69363
  Epoch 019 - train 0.63189 | val 0.74622
  Classification -> best τ=0.475 (val F1=0.1563)
  Directional -> Accuracy: 0.5100, MCC: 0.0020, F1: 0.5702

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.66913 | val 0.71624
  Epoch 011 - train 0.66291 | val 0.74354
  Classification -> best τ=0.480 (val F1=0.0931)
  Directional -> Accuracy: 0.5000, MCC: -0.0371, F1: 0.5798

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65145 | val 0.70581
  Epoch 011 - train 0.65141 | val 0.70529
  Classification -> best τ=0.430 (val F1=0.0531)
  Directional -> Accuracy: 0.4500, MCC: -0.0088, F1: 0.6014

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.56799 | val 1.01277
  Epoch 011 - train 0.55455 | val 1.02560
  Classification -> best τ=0.430 (val F1=0.2036)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6571

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65102 | val 0.73761
  Epoch 011 - train 0.65069 | val 0.75548
  Classification -> best τ=0.420 (val F1=0.1015)
  Directional -> Accuracy: 0.5850, MCC: 0.0000, F1: 0.7382

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66102 | val 0.69458
  Epoch 012 - train 0.64599 | val 0.71259
  Classification -> best τ=0.550 (val F1=0.1588)
  Directional -> Accuracy: 0.4650, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.66139 | val 0.73390
  Epoch 019 - train 0.60434 | val 0.86761
  Classification -> best τ=0.555 (val F1=0.1502)
  Directional -> Accuracy: 0.4550, MCC: 0.0762, F1: 0.0992

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.67034 | val 1.22919
  Epoch 011 - train 0.65831 | val 1.12665
  Classification -> best τ=0.385 (val F1=0.1145)
  Directional -> Accuracy: 0.5450, MCC: 0.0000, F1: 0.7055

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.64136 | val 0.80109
  Epoch 011 - train 0.63855 | val 0.80519
  Classification -> best τ=0.530 (val F1=0.0477)
  Directional -> Accuracy: 0.4500, MCC: -0.0946, F1: 0.1538

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.66198 | val 0.81147
  Epoch 011 - train 0.64809 | val 0.86491
  Classification -> best τ=0.555 (val F1=0.0854)
  Directional -> Accuracy: 0.5150, MCC: 0.0641, F1: 0.3022

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66548 | val 0.77538
  Epoch 011 - train 0.66076 | val 0.85681
  Classification -> best τ=0.500 (val F1=0.1964)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65828 | val 0.80155
  Epoch 011 - train 0.64855 | val 0.87057
  Classification -> best τ=0.450 (val F1=0.1942)
  Directional -> Accuracy: 0.5450, MCC: 0.0900, F1: 0.6540

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66813 | val 0.77244
  Epoch 011 - train 0.65804 | val 0.81017
  Classification -> best τ=0.435 (val F1=0.1756)
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64003 | val 0.93506
  Epoch 011 - train 0.61946 | val 0.96773
  Classification -> best τ=0.295 (val F1=0.1122)
  Directional -> Accuracy: 0.5450, MCC: 0.0567, F1: 0.6807

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65614 | val 0.72199
  Epoch 012 - train 0.64654 | val 0.71678
  Classification -> best τ=0.645 (val F1=0.0641)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66422 | val 0.74643
  Epoch 011 - train 0.64883 | val 0.77362
  Classification -> best τ=0.390 (val F1=0.0808)
  Directional -> Accuracy: 0.5650, MCC: 0.0000, F1: 0.7220

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65235 | val 0.76749
  Epoch 011 - train 0.63113 | val 0.75870
  Classification -> best τ=0.545 (val F1=0.0674)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66556 | val 0.68676
  Epoch 013 - train 0.64800 | val 0.74977
  Classification -> best τ=0.545 (val F1=0.1555)
  Directional -> Accuracy: 0.4950, MCC: -0.0048, F1: 0.5511

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65606 | val 0.68627
  Epoch 011 - train 0.66021 | val 0.70285
  Classification -> best τ=0.535 (val F1=0.1354)
  Directional -> Accuracy: 0.4750, MCC: 0.0393, F1: 0.3046

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65854 | val 0.74152
  Epoch 012 - train 0.66088 | val 0.75498
  Classification -> best τ=0.580 (val F1=0.1153)
  Directional -> Accuracy: 0.4450, MCC: -0.0305, F1: 0.1898

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66414 | val 0.69271
  Epoch 015 - train 0.59706 | val 0.71091
  Classification -> best τ=0.430 (val F1=0.1633)
  Directional -> Accuracy: 0.5100, MCC: 0.0716, F1: 0.6733

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65844 | val 0.96816
  Epoch 011 - train 0.63801 | val 1.08156
  Classification -> best τ=0.340 (val F1=0.1034)
  Directional -> Accuracy: 0.4950, MCC: -0.0415, F1: 0.6273

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.67448 | val 0.70473
  Epoch 011 - train 0.65225 | val 0.71003
  Classification -> best τ=0.505 (val F1=0.1305)
  Directional -> Accuracy: 0.4050, MCC: -0.0395, F1: 0.0630

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.66933 | val 0.79963
  Epoch 011 - train 0.65072 | val 0.99340
  Classification -> best τ=0.410 (val F1=0.1735)
  Directional -> Accuracy: 0.4900, MCC: -0.0243, F1: 0.3929

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67101 | val 0.99183
  Epoch 011 - train 0.64375 | val 1.06473
  Classification -> best τ=0.425 (val F1=0.1001)
  Directional -> Accuracy: 0.5200, MCC: -0.0133, F1: 0.6757

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63821 | val 0.74523
  Epoch 011 - train 0.62139 | val 0.79808
  Classification -> best τ=0.415 (val F1=0.1005)
  Directional -> Accuracy: 0.5350, MCC: 0.0714, F1: 0.5550

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.65561 | val 0.93792
  Epoch 011 - train 0.65165 | val 0.85668
  Classification -> best τ=0.435 (val F1=0.1816)
  Directional -> Accuracy: 0.5000, MCC: 0.0313, F1: 0.3421

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63975 | val 0.74772
  Epoch 011 - train 0.63277 | val 0.76379
  Classification -> best τ=0.495 (val F1=0.2033)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63795 | val 0.82398
  Epoch 011 - train 0.62028 | val 0.85483
  Classification -> best τ=0.445 (val F1=0.1674)
  Directional -> Accuracy: 0.4700, MCC: -0.0403, F1: 0.3690

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64812 | val 0.73674
  Epoch 011 - train 0.64244 | val 0.76821
  Classification -> best τ=0.605 (val F1=0.0261)
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63653 | val 0.84511
  Epoch 011 - train 0.61010 | val 0.88271
  Classification -> best τ=0.530 (val F1=0.1446)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.63075 | val 0.76746
  Epoch 011 - train 0.61850 | val 0.79028
  Classification -> best τ=0.515 (val F1=0.0946)
  Directional -> Accuracy: 0.5400, MCC: 0.0760, F1: 0.0213

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.64766 | val 0.70222
  Epoch 020 - train 0.55455 | val 1.32666
  Classification -> best τ=0.495 (val F1=0.1186)
  Directional -> Accuracy: 0.4550, MCC: 0.0583, F1: 0.1805

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.67402 | val 0.81978
  Epoch 011 - train 0.68103 | val 0.73745
  Classification -> best τ=0.540 (val F1=0.0897)
  Directional -> Accuracy: 0.4250, MCC: 0.0000, F1: 0.0000

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.63452 | val 0.71140
  Epoch 011 - train 0.61869 | val 0.72074
  Classification -> best τ=0.470 (val F1=0.1657)
  Directional -> Accuracy: 0.4518, MCC: -0.0199, F1: 0.5424

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.65321 | val 0.92148
  Epoch 011 - train 0.63751 | val 0.88414
  Classification -> best τ=0.590 (val F1=0.1547)
  Directional -> Accuracy: 0.5000, MCC: 0.1114, F1: 0.1525

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.65481 | val 0.87590
  Epoch 011 - train 0.64352 | val 0.89113
  Classification -> best τ=0.335 (val F1=0.1189)
  Directional -> Accuracy: 0.5025, MCC: 0.0000, F1: 0.6689

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63080 | val 0.86168
  Epoch 011 - train 0.61900 | val 0.81202
  Classification -> best τ=0.510 (val F1=0.1199)
  Directional -> Accuracy: 0.4200, MCC: -0.0947, F1: 0.5606

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.63637 | val 0.87118
  Epoch 011 - train 0.61643 | val 0.88185
  Classification -> best τ=0.485 (val F1=0.1450)
  Directional -> Accuracy: 0.5076, MCC: 0.0144, F1: 0.4192

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.65765 | val 0.77633
  Epoch 011 - train 0.64214 | val 0.81465
  Classification -> best τ=0.550 (val F1=0.1181)
  Directional -> Accuracy: 0.5050, MCC: -0.0002, F1: 0.5823

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.64740 | val 0.74193
  Epoch 011 - train 0.63599 | val 0.74764
  Classification -> best τ=0.500 (val F1=0.1310)
  Directional -> Accuracy: 0.5150, MCC: 0.0030, F1: 0.6777

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.63486 | val 1.71436
  Epoch 011 - train 0.62609 | val 1.69581
  Classification -> best τ=0.455 (val F1=0.0499)
  Directional -> Accuracy: 0.6000, MCC: 0.2036, F1: 0.5876

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.66241 | val 0.77928
  Epoch 012 - train 0.63774 | val 0.80707
  Classification -> best τ=0.400 (val F1=0.1161)
  Directional -> Accuracy: 0.5300, MCC: 0.0000, F1: 0.6928

[75/88] Processing T...


[I 2026-02-26 01:00:52,850] Trial 19 finished with value: 0.1309685534167037 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.005398960003203725, 'weight_decay': 6.359167031438771e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.0663463111334068, 'early_stopping_min_delta': 0.007792137776208165}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 018 - train 0.59901 | val 0.70865
  Classification -> best τ=0.630 (val F1=0.2376)
  Directional -> Accuracy: 0.5150, MCC: 0.0436, F1: 0.0396

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1309685534167037
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68459 | val 0.86074
  Epoch 020 - train 0.67094 | val 1.07793
  Epoch 021 - train 0.66637 | val 1.08022
  Classification -> best τ=0.565 (val F1=0.1051)
  Directional -> Accuracy: 0.4121, MCC: -0.0791, F1: 0.1702

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.68686 | val 1.94049
  Epoch 020 - train 0.64595 | val 2.36403
  Epoch 021 - train 0.63721 | val 2.70949
  Classification -> best τ=0.415 (val F1=0.1235)
  Directional -> Accuracy: 0.5075, MCC: 0.1003, F1: 0.0392

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66903 | val 0.86502
  Epoch 020 - train 0.64881 | val 0.90029
  Epoch 021 - train 0.64165 | val 0.88372
  Classification -> best τ=0.560 (val F1=0.1563)
  Directional -> Accuracy: 0.4301, MCC: -0.0090, F1: 0.0862

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.67066 | val 0.81141
  Epoch 020 - train 0.65306 | val 0.90160
  Epoch 021 - train 0.63853 | val 0.93223
  Classification -> best τ=0.525 (val F1=0.1434)
  Directional -> Accuracy: 0.4523, MCC: -0.0058, F1: 0.2158

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.67258 | val 0.70195
  Epoch 020 - train 0.63593 | val 0.83244
  Epoch 029 - train 0.59063 | val 0.73598
  Classification -> best τ=0.320 (val F1=0.1651)
  Directional -> Accuracy: 0.4528, MCC: -0.0895, F1: 0.4423

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66852 | val 0.97241
  Epoch 020 - train 0.64231 | val 1.12180
  Epoch 021 - train 0.64082 | val 1.12431
  Classification -> best τ=0.760 (val F1=0.0845)
  Directional -> Accuracy: 0.4472, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66369 | val 1.10221
  Epoch 020 - train 0.63760 | val 1.08573
  Epoch 021 - train 0.65283 | val 1.07468
  Classification -> best τ=0.635 (val F1=0.1200)
  Directional -> Accuracy: 0.4422, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64813 | val 0.86678
  Epoch 020 - train 0.61112 | val 0.89171
  Epoch 021 - train 0.61874 | val 0.94580
  Classification -> best τ=0.330 (val F1=0.2795)
  Directional -> Accuracy: 0.5226, MCC: 0.1525, F1: 0.4693

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65815 | val 1.30636
  Epoch 020 - train 0.63473 | val 1.09531
  Epoch 021 - train 0.62781 | val 1.01526
  Classification -> best τ=0.435 (val F1=0.1449)
  Directional -> Accuracy: 0.4211, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67075 | val 1.35920
  Epoch 020 - train 0.64463 | val 1.79269
  Epoch 021 - train 0.64627 | val 1.86940
  Classification -> best τ=0.915 (val F1=0.1079)
  Directional -> Accuracy: 0.5377, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.68075 | val 0.69933
  Epoch 020 - train 0.66410 | val 0.74175
  Epoch 030 - train 0.62436 | val 0.95329
  Classification -> best τ=0.550 (val F1=0.1946)
  Directional -> Accuracy: 0.4975, MCC: -0.0038, F1: 0.5146

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.67461 | val 0.76366
  Epoch 020 - train 0.62775 | val 0.78110
  Epoch 021 - train 0.62843 | val 0.81058
  Classification -> best τ=0.450 (val F1=0.1702)
  Directional -> Accuracy: 0.4372, MCC: 0.0391, F1: 0.0968

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67505 | val 0.90866
  Epoch 020 - train 0.64720 | val 1.13418
  Epoch 021 - train 0.64638 | val 1.12299
  Classification -> best τ=0.475 (val F1=0.1836)
  Directional -> Accuracy: 0.4874, MCC: 0.1367, F1: 0.2154

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67000 | val 0.71069
  Epoch 020 - train 0.63819 | val 0.83402
  Epoch 021 - train 0.63595 | val 0.81953
  Classification -> best τ=0.470 (val F1=0.2160)
  Directional -> Accuracy: 0.4724, MCC: -0.0551, F1: 0.5024

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.68900 | val 0.84820
  Epoch 020 - train 0.66134 | val 0.88104
  Epoch 021 - train 0.66994 | val 0.88659
  Classification -> best τ=0.295 (val F1=0.0995)
  Directional -> Accuracy: 0.5075, MCC: -0.0096, F1: 0.5950

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.67119 | val 0.94204
  Epoch 020 - train 0.64433 | val 1.06180
  Epoch 021 - train 0.62977 | val 1.08832
  Classification -> best τ=0.475 (val F1=0.1266)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.67150 | val 0.83933
  Epoch 020 - train 0.65309 | val 1.01422
  Epoch 021 - train 0.65512 | val 1.06496
  Classification -> best τ=0.390 (val F1=0.1894)
  Directional -> Accuracy: 0.5578, MCC: 0.0117, F1: 0.7143

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65269 | val 3.46393
  Epoch 020 - train 0.61968 | val 3.81176
  Epoch 021 - train 0.60352 | val 4.17841
  Classification -> best τ=0.705 (val F1=0.1366)
  Directional -> Accuracy: 0.4824, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66145 | val 0.77230
  Epoch 020 - train 0.65009 | val 0.79996
  Epoch 021 - train 0.64208 | val 0.81153
  Classification -> best τ=0.370 (val F1=0.2559)
  Directional -> Accuracy: 0.5226, MCC: 0.0478, F1: 0.6091

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65475 | val 0.87414
  Epoch 020 - train 0.61916 | val 0.99329
  Epoch 021 - train 0.61562 | val 0.97460
  Classification -> best τ=0.165 (val F1=0.1004)
  Directional -> Accuracy: 0.5528, MCC: 0.0630, F1: 0.6962

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.66003 | val 0.80864
  Epoch 020 - train 0.64836 | val 0.95785
  Epoch 021 - train 0.64078 | val 0.92136
  Classification -> best τ=0.650 (val F1=0.1541)
  Directional -> Accuracy: 0.4975, MCC: 0.0094, F1: 0.6324

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.67596 | val 1.03799
  Epoch 020 - train 0.66522 | val 0.80911
  Epoch 021 - train 0.66937 | val 0.84871
  Classification -> best τ=0.255 (val F1=0.1593)
  Directional -> Accuracy: 0.5276, MCC: 0.0426, F1: 0.5766

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66511 | val 0.74603
  Epoch 020 - train 0.65422 | val 0.77050
  Epoch 021 - train 0.65474 | val 0.79092
  Classification -> best τ=0.390 (val F1=0.1881)
  Directional -> Accuracy: 0.4724, MCC: 0.0386, F1: 0.1322

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.66029 | val 0.87295
  Epoch 020 - train 0.63251 | val 0.93429
  Epoch 021 - train 0.63336 | val 1.00259
  Classification -> best τ=0.720 (val F1=0.1275)
  Directional -> Accuracy: 0.6080, MCC: 0.0000, F1: 0.0000

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66436 | val 1.13909
  Epoch 020 - train 0.63158 | val 1.07822
  Epoch 021 - train 0.63563 | val 1.14472
  Classification -> best τ=0.310 (val F1=0.1206)
  Directional -> Accuracy: 0.5427, MCC: 0.0731, F1: 0.6316

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67342 | val 0.71584
  Epoch 020 - train 0.65400 | val 0.74472
  Epoch 030 - train 0.60881 | val 0.87775
  Classification -> best τ=0.575 (val F1=0.1598)
  Directional -> Accuracy: 0.5528, MCC: 0.1291, F1: 0.2764

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63372 | val 1.65110
  Epoch 020 - train 0.61906 | val 2.05056
  Epoch 021 - train 0.60408 | val 1.93546
  Classification -> best τ=0.480 (val F1=0.2151)
  Directional -> Accuracy: 0.4573, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.67391 | val 1.27871
  Epoch 020 - train 0.63824 | val 1.85140
  Epoch 021 - train 0.63395 | val 1.81625
  Classification -> best τ=0.365 (val F1=0.0802)
  Directional -> Accuracy: 0.5528, MCC: 0.1134, F1: 0.6147

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66279 | val 1.25040
  Epoch 020 - train 0.65281 | val 1.48756
  Epoch 021 - train 0.63345 | val 1.50913
  Classification -> best τ=0.720 (val F1=0.1536)
  Directional -> Accuracy: 0.5075, MCC: 0.0585, F1: 0.1967

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.67004 | val 1.33926
  Epoch 020 - train 0.64469 | val 1.44399
  Epoch 021 - train 0.64329 | val 1.52738
  Classification -> best τ=0.345 (val F1=0.1938)
  Directional -> Accuracy: 0.4975, MCC: 0.0865, F1: 0.2537

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.67078 | val 1.82390
  Epoch 020 - train 0.64214 | val 1.84589
  Epoch 021 - train 0.64114 | val 1.87087
  Classification -> best τ=0.430 (val F1=0.1183)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68123 | val 0.69897
  Epoch 020 - train 0.65386 | val 0.69508
  Epoch 030 - train 0.63653 | val 0.70721
  Classification -> best τ=0.475 (val F1=0.1486)
  Directional -> Accuracy: 0.5578, MCC: 0.0863, F1: 0.6364

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.67678 | val 0.75295
  Epoch 020 - train 0.65001 | val 0.79620
  Epoch 021 - train 0.65118 | val 0.80426
  Classification -> best τ=0.420 (val F1=0.1241)
  Directional -> Accuracy: 0.4472, MCC: -0.0809, F1: 0.4712

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68772 | val 0.70895
  Epoch 020 - train 0.66377 | val 0.71145
  Epoch 030 - train 0.63228 | val 0.69515
  Classification -> best τ=0.500 (val F1=0.1613)
  Directional -> Accuracy: 0.5829, MCC: 0.1287, F1: 0.3465

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.61955 | val 1.51192
  Epoch 020 - train 0.61813 | val 1.53033
  Epoch 021 - train 0.58050 | val 1.53851
  Classification -> best τ=0.515 (val F1=0.1800)
  Directional -> Accuracy: 0.6170, MCC: 0.2653, F1: 0.6786

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65255 | val 0.82092
  Epoch 020 - train 0.61796 | val 0.80648
  Epoch 021 - train 0.62688 | val 0.82317
  Classification -> best τ=0.765 (val F1=0.2171)
  Directional -> Accuracy: 0.4171, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65768 | val 1.29951
  Epoch 020 - train 0.64693 | val 1.45383
  Epoch 021 - train 0.63443 | val 1.53700
  Classification -> best τ=0.825 (val F1=0.1895)
  Directional -> Accuracy: 0.4673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.68301 | val 0.89591
  Epoch 020 - train 0.64331 | val 0.87852
  Epoch 021 - train 0.63411 | val 0.87227
  Classification -> best τ=0.365 (val F1=0.1365)
  Directional -> Accuracy: 0.4372, MCC: -0.0054, F1: 0.0820

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.65827 | val 1.48962
  Epoch 020 - train 0.63105 | val 1.57323
  Epoch 021 - train 0.63267 | val 1.47974
  Classification -> best τ=0.195 (val F1=0.1143)
  Directional -> Accuracy: 0.5427, MCC: 0.0000, F1: 0.7036

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.67957 | val 0.85633
  Epoch 020 - train 0.65864 | val 0.93811
  Epoch 021 - train 0.66199 | val 0.95367
  Classification -> best τ=0.410 (val F1=0.1132)
  Directional -> Accuracy: 0.5075, MCC: 0.0110, F1: 0.5377

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.68106 | val 0.98587
  Epoch 020 - train 0.63774 | val 1.05543
  Epoch 021 - train 0.64101 | val 1.09414
  Classification -> best τ=0.455 (val F1=0.1511)
  Directional -> Accuracy: 0.4975, MCC: -0.0248, F1: 0.6000

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67002 | val 0.87186
  Epoch 020 - train 0.64909 | val 1.02118
  Epoch 021 - train 0.65956 | val 1.02353
  Classification -> best τ=0.770 (val F1=0.1079)
  Directional -> Accuracy: 0.4573, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66773 | val 0.90510
  Epoch 020 - train 0.64222 | val 1.04938
  Epoch 021 - train 0.64109 | val 1.08891
  Classification -> best τ=0.405 (val F1=0.0994)
  Directional -> Accuracy: 0.4824, MCC: -0.0482, F1: 0.5690

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67353 | val 1.01982
  Epoch 020 - train 0.65260 | val 1.33540
  Epoch 021 - train 0.65341 | val 1.36909
  Classification -> best τ=0.745 (val F1=0.1489)
  Directional -> Accuracy: 0.4774, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67399 | val 1.07294
  Epoch 020 - train 0.64197 | val 1.22964
  Epoch 021 - train 0.65269 | val 1.18650
  Classification -> best τ=0.255 (val F1=0.1024)
  Directional -> Accuracy: 0.5176, MCC: 0.0041, F1: 0.6129

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66580 | val 1.00617
  Epoch 020 - train 0.63683 | val 1.07715
  Epoch 021 - train 0.64421 | val 1.11459
  Classification -> best τ=0.255 (val F1=0.0971)
  Directional -> Accuracy: 0.5427, MCC: 0.0191, F1: 0.6431

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66298 | val 0.76555
  Epoch 020 - train 0.64651 | val 0.86784
  Epoch 021 - train 0.65621 | val 0.87745
  Classification -> best τ=0.635 (val F1=0.1538)
  Directional -> Accuracy: 0.4372, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66259 | val 2.45686
  Epoch 020 - train 0.61680 | val 2.25605
  Epoch 021 - train 0.61550 | val 2.35082
  Classification -> best τ=0.145 (val F1=0.0612)
  Directional -> Accuracy: 0.5427, MCC: -0.0682, F1: 0.6807

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65641 | val 1.32779
  Epoch 020 - train 0.63038 | val 1.99127
  Epoch 021 - train 0.61957 | val 2.00881
  Classification -> best τ=0.535 (val F1=0.1313)
  Directional -> Accuracy: 0.5025, MCC: -0.0073, F1: 0.3444

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67272 | val 0.76862
  Epoch 020 - train 0.64716 | val 0.86811
  Epoch 022 - train 0.64896 | val 0.86751
  Classification -> best τ=0.650 (val F1=0.1159)
  Directional -> Accuracy: 0.4322, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68084 | val 0.75419
  Epoch 020 - train 0.63021 | val 0.91067
  Epoch 022 - train 0.62988 | val 0.83558
  Classification -> best τ=0.475 (val F1=0.1389)
  Directional -> Accuracy: 0.5578, MCC: 0.0000, F1: 0.7161

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64567 | val 0.77949
  Epoch 020 - train 0.63381 | val 0.78947
  Epoch 021 - train 0.62307 | val 0.82139
  Classification -> best τ=0.445 (val F1=0.1470)
  Directional -> Accuracy: 0.4975, MCC: 0.0209, F1: 0.0909

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67662 | val 0.77271
  Epoch 020 - train 0.66422 | val 0.75130
  Epoch 021 - train 0.64856 | val 0.74675
  Classification -> best τ=0.670 (val F1=0.1063)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.65129 | val 1.63810
  Epoch 020 - train 0.64033 | val 1.61872
  Epoch 021 - train 0.63606 | val 1.67309
  Classification -> best τ=0.285 (val F1=0.1423)
  Directional -> Accuracy: 0.4472, MCC: 0.0288, F1: 0.2857

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.66835 | val 0.95699
  Epoch 020 - train 0.63513 | val 1.12183
  Epoch 021 - train 0.62517 | val 1.16764
  Classification -> best τ=0.405 (val F1=0.1364)
  Directional -> Accuracy: 0.4925, MCC: -0.0163, F1: 0.6245

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67544 | val 1.18291
  Epoch 020 - train 0.64839 | val 1.37003
  Epoch 021 - train 0.64521 | val 1.34808
  Classification -> best τ=0.485 (val F1=0.1383)
  Directional -> Accuracy: 0.5377, MCC: 0.1037, F1: 0.6913

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68129 | val 1.00150
  Epoch 020 - train 0.64583 | val 1.01583
  Epoch 021 - train 0.64924 | val 0.97158
  Classification -> best τ=0.430 (val F1=0.1129)
  Directional -> Accuracy: 0.5025, MCC: 0.0954, F1: 0.2979

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.66702 | val 1.03068
  Epoch 020 - train 0.65197 | val 0.90076
  Epoch 021 - train 0.65221 | val 0.88344
  Classification -> best τ=0.340 (val F1=0.2046)
  Directional -> Accuracy: 0.5025, MCC: 0.0174, F1: 0.4590

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65267 | val 1.09843
  Epoch 020 - train 0.62447 | val 1.04707
  Epoch 021 - train 0.63100 | val 1.06850
  Classification -> best τ=0.565 (val F1=0.2671)
  Directional -> Accuracy: 0.4171, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66052 | val 0.83681
  Epoch 020 - train 0.64986 | val 0.78523
  Epoch 021 - train 0.65080 | val 0.78523
  Classification -> best τ=0.465 (val F1=0.1796)
  Directional -> Accuracy: 0.4975, MCC: 0.0604, F1: 0.2537

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65683 | val 1.24697
  Epoch 020 - train 0.62158 | val 1.38030
  Epoch 021 - train 0.62941 | val 1.41543
  Classification -> best τ=0.125 (val F1=0.1054)
  Directional -> Accuracy: 0.4774, MCC: 0.0000, F1: 0.6463

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65959 | val 1.26976
  Epoch 020 - train 0.61644 | val 1.68910
  Epoch 021 - train 0.62842 | val 1.51096
  Classification -> best τ=0.450 (val F1=0.2232)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.67925 | val 1.34380
  Epoch 020 - train 0.64205 | val 1.71848
  Epoch 021 - train 0.62484 | val 1.72093
  Classification -> best τ=0.680 (val F1=0.1076)
  Directional -> Accuracy: 0.5327, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.65396 | val 2.40863
  Epoch 020 - train 0.62000 | val 2.90542

[I 2026-02-26 01:18:33,783] Trial 20 finished with value: 0.15153526637466272 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.0005987227447867521, 'weight_decay': 2.1384697582109156e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.6595926039063158, 'early_stopping_min_delta': 0.0026592776231633016}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 021 - train 0.64107 | val 1.07354
  Classification -> best τ=0.385 (val F1=0.1524)
  Directional -> Accuracy: 0.5176, MCC: 0.0431, F1: 0.5862

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.15153526637466272
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69479 | val 0.79682
  Epoch 020 - train 0.66682 | val 0.90725
  Epoch 021 - train 0.66520 | val 0.93026
  Classification -> best τ=0.460 (val F1=0.1542)
  Directional -> Accuracy: 0.5377, MCC: 0.0123, F1: 0.6378

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.66134 | val 1.61506
  Epoch 020 - train 0.64862 | val 2.38068
  Epoch 021 - train 0.64816 | val 2.24654
  Classification -> best τ=0.400 (val F1=0.1640)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67355 | val 0.74054
  Epoch 020 - train 0.64223 | val 0.80391
  Epoch 021 - train 0.65748 | val 0.79840
  Classification -> best τ=0.515 (val F1=0.1810)
  Directional -> Accuracy: 0.4140, MCC: -0.0859, F1: 0.0522

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.68763 | val 1.09622
  Epoch 020 - train 0.63515 | val 1.01986
  Epoch 021 - train 0.64470 | val 1.02136
  Classification -> best τ=0.525 (val F1=0.1080)
  Directional -> Accuracy: 0.4573, MCC: 0.0251, F1: 0.1818

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.64058 | val 0.73205
  Epoch 020 - train 0.62416 | val 0.72359
  Epoch 021 - train 0.60071 | val 0.72889
  Classification -> best τ=0.520 (val F1=0.2027)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68135 | val 0.91958
  Epoch 020 - train 0.64237 | val 1.18636
  Epoch 021 - train 0.64380 | val 1.15450
  Classification -> best τ=0.470 (val F1=0.0972)
  Directional -> Accuracy: 0.4472, MCC: -0.0532, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67263 | val 1.15974
  Epoch 020 - train 0.64650 | val 1.14166
  Epoch 021 - train 0.64013 | val 1.12837
  Classification -> best τ=0.690 (val F1=0.1200)
  Directional -> Accuracy: 0.4422, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65528 | val 0.77846
  Epoch 020 - train 0.62405 | val 0.83012
  Epoch 021 - train 0.61613 | val 0.86980
  Classification -> best τ=0.295 (val F1=0.2688)
  Directional -> Accuracy: 0.3920, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67371 | val 1.39431
  Epoch 020 - train 0.64218 | val 1.54240
  Epoch 021 - train 0.63698 | val 1.58412
  Classification -> best τ=0.460 (val F1=0.2234)
  Directional -> Accuracy: 0.4211, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68246 | val 1.04469
  Epoch 020 - train 0.64840 | val 1.52570
  Epoch 021 - train 0.65060 | val 1.59840
  Classification -> best τ=0.700 (val F1=0.1079)
  Directional -> Accuracy: 0.5377, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.68002 | val 0.69944
  Epoch 020 - train 0.65697 | val 0.74760
  Epoch 027 - train 0.63582 | val 0.76613
  Classification -> best τ=0.705 (val F1=0.2157)
  Directional -> Accuracy: 0.4774, MCC: 0.0341, F1: 0.2000

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.65309 | val 0.76130
  Epoch 020 - train 0.64627 | val 0.78341
  Epoch 021 - train 0.63937 | val 0.83723
  Classification -> best τ=0.245 (val F1=0.0963)
  Directional -> Accuracy: 0.5427, MCC: 0.0110, F1: 0.6540

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66480 | val 0.92361
  Epoch 020 - train 0.64057 | val 1.07415
  Epoch 021 - train 0.63560 | val 1.10903
  Classification -> best τ=0.500 (val F1=0.1261)
  Directional -> Accuracy: 0.4724, MCC: 0.0131, F1: 0.3396

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65818 | val 0.74554
  Epoch 020 - train 0.64750 | val 0.79439
  Epoch 021 - train 0.63647 | val 0.78811
  Classification -> best τ=0.555 (val F1=0.1937)
  Directional -> Accuracy: 0.4874, MCC: -0.0260, F1: 0.4516

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.67372 | val 0.88147
  Epoch 020 - train 0.66533 | val 0.97190
  Epoch 021 - train 0.66386 | val 0.92043
  Classification -> best τ=0.380 (val F1=0.0953)
  Directional -> Accuracy: 0.4523, MCC: -0.0704, F1: 0.2483

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.67559 | val 1.30693
  Epoch 020 - train 0.65025 | val 1.48313
  Epoch 021 - train 0.64509 | val 1.43894
  Classification -> best τ=0.105 (val F1=0.1400)
  Directional -> Accuracy: 0.5075, MCC: 0.0144, F1: 0.5463

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.68739 | val 0.76181
  Epoch 020 - train 0.64054 | val 0.86220
  Epoch 024 - train 0.64002 | val 0.89237
  Classification -> best τ=0.225 (val F1=0.1902)
  Directional -> Accuracy: 0.5578, MCC: 0.0000, F1: 0.7161

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64438 | val 2.91203
  Epoch 020 - train 0.60846 | val 3.83417
  Epoch 021 - train 0.62493 | val 3.66348
  Classification -> best τ=0.600 (val F1=0.1200)
  Directional -> Accuracy: 0.4824, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66948 | val 0.76538
  Epoch 020 - train 0.65044 | val 0.75454
  Epoch 021 - train 0.65608 | val 0.74132
  Classification -> best τ=0.375 (val F1=0.2289)
  Directional -> Accuracy: 0.5578, MCC: 0.1180, F1: 0.6071

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65206 | val 1.00918
  Epoch 020 - train 0.63904 | val 1.15606
  Epoch 021 - train 0.63127 | val 1.15906
  Classification -> best τ=0.515 (val F1=0.1036)
  Directional -> Accuracy: 0.4925, MCC: 0.0216, F1: 0.3952

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.65637 | val 0.80921
  Epoch 020 - train 0.64912 | val 0.83030
  Epoch 021 - train 0.64273 | val 0.83901
  Classification -> best τ=0.265 (val F1=0.1113)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.6599

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.68694 | val 0.86511
  Epoch 020 - train 0.66183 | val 0.83877
  Epoch 030 - train 0.64816 | val 0.86609
  Classification -> best τ=0.460 (val F1=0.1410)
  Directional -> Accuracy: 0.4372, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66287 | val 0.75782
  Epoch 020 - train 0.63987 | val 0.87769
  Epoch 021 - train 0.64345 | val 0.82997
  Classification -> best τ=0.325 (val F1=0.1660)
  Directional -> Accuracy: 0.5427, MCC: 0.0550, F1: 0.6345

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.66036 | val 0.87132
  Epoch 020 - train 0.62907 | val 1.00351
  Epoch 021 - train 0.63608 | val 1.05545
  Classification -> best τ=0.705 (val F1=0.1275)
  Directional -> Accuracy: 0.6080, MCC: 0.0000, F1: 0.0000

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66912 | val 1.06612
  Epoch 020 - train 0.63184 | val 1.07691
  Epoch 021 - train 0.63239 | val 1.04137
  Classification -> best τ=0.330 (val F1=0.0926)
  Directional -> Accuracy: 0.5377, MCC: 0.0637, F1: 0.6134

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67495 | val 0.70786
  Epoch 020 - train 0.63540 | val 0.71837
  Epoch 030 - train 0.62820 | val 0.74315
  Classification -> best τ=0.555 (val F1=0.1423)
  Directional -> Accuracy: 0.5477, MCC: 0.1101, F1: 0.2857

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64737 | val 1.42488
  Epoch 020 - train 0.61565 | val 1.71344
  Epoch 021 - train 0.61158 | val 1.71850
  Classification -> best τ=0.490 (val F1=0.1314)
  Directional -> Accuracy: 0.4573, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.67877 | val 1.28482
  Epoch 020 - train 0.64462 | val 1.64867
  Epoch 021 - train 0.63815 | val 1.75399
  Classification -> best τ=0.375 (val F1=0.1036)
  Directional -> Accuracy: 0.4975, MCC: -0.0018, F1: 0.6377

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67431 | val 1.00562
  Epoch 020 - train 0.64388 | val 1.37145
  Epoch 021 - train 0.64173 | val 1.46201
  Classification -> best τ=0.700 (val F1=0.1321)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.67614 | val 1.20197
  Epoch 020 - train 0.62706 | val 1.63551
  Epoch 021 - train 0.63947 | val 1.70088
  Classification -> best τ=0.350 (val F1=0.1945)
  Directional -> Accuracy: 0.5025, MCC: 0.1110, F1: 0.2443

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.66154 | val 1.78006
  Epoch 020 - train 0.64416 | val 2.05307
  Epoch 021 - train 0.64314 | val 2.44282
  Classification -> best τ=0.345 (val F1=0.1429)
  Directional -> Accuracy: 0.5226, MCC: 0.1064, F1: 0.1880

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68115 | val 0.77495
  Epoch 020 - train 0.64364 | val 0.78123
  Epoch 021 - train 0.65389 | val 0.76221
  Classification -> best τ=0.460 (val F1=0.0724)
  Directional -> Accuracy: 0.4573, MCC: -0.0342, F1: 0.3077

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.69875 | val 0.80405
  Epoch 020 - train 0.65406 | val 0.81009
  Epoch 021 - train 0.65187 | val 0.82891
  Classification -> best τ=0.345 (val F1=0.1375)
  Directional -> Accuracy: 0.4322, MCC: 0.0030, F1: 0.2803

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67298 | val 0.81702
  Epoch 020 - train 0.65798 | val 0.76541
  Epoch 021 - train 0.66137 | val 0.75831
  Classification -> best τ=0.295 (val F1=0.1165)
  Directional -> Accuracy: 0.4472, MCC: -0.0244, F1: 0.6043

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.57885 | val 1.25509
  Epoch 020 - train 0.55850 | val 1.66969
  Epoch 021 - train 0.59984 | val 1.54847
  Classification -> best τ=0.470 (val F1=0.2713)
  Directional -> Accuracy: 0.4894, MCC: -0.0045, F1: 0.6471

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64640 | val 0.78255
  Epoch 020 - train 0.62739 | val 0.93554
  Epoch 021 - train 0.63236 | val 0.98028
  Classification -> best τ=0.500 (val F1=0.1953)
  Directional -> Accuracy: 0.4422, MCC: 0.0398, F1: 0.1654

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66213 | val 1.05291
  Epoch 020 - train 0.65116 | val 1.20333
  Epoch 021 - train 0.63410 | val 1.20263
  Classification -> best τ=0.730 (val F1=0.1995)
  Directional -> Accuracy: 0.4673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.65838 | val 0.85836
  Epoch 020 - train 0.63304 | val 0.92689
  Epoch 022 - train 0.63006 | val 0.96920
  Classification -> best τ=0.410 (val F1=0.0991)
  Directional -> Accuracy: 0.5025, MCC: 0.0267, F1: 0.4975

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.67090 | val 1.34195
  Epoch 020 - train 0.64865 | val 1.50619
  Epoch 021 - train 0.64053 | val 1.42464
  Classification -> best τ=0.425 (val F1=0.0549)
  Directional -> Accuracy: 0.4673, MCC: 0.0925, F1: 0.0364

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.68514 | val 0.97567
  Epoch 020 - train 0.65178 | val 1.06586
  Epoch 021 - train 0.64499 | val 1.08067
  Classification -> best τ=0.700 (val F1=0.2232)
  Directional -> Accuracy: 0.4724, MCC: 0.0000, F1: 0.0000

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.67419 | val 0.90325
  Epoch 020 - train 0.63291 | val 1.25172
  Epoch 021 - train 0.64267 | val 1.19527
  Classification -> best τ=0.670 (val F1=0.1829)
  Directional -> Accuracy: 0.5025, MCC: 0.0840, F1: 0.1239

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67933 | val 0.82755
  Epoch 020 - train 0.64862 | val 0.92287
  Epoch 023 - train 0.65475 | val 0.97084
  Classification -> best τ=0.815 (val F1=0.0879)
  Directional -> Accuracy: 0.4573, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67380 | val 1.03226
  Epoch 020 - train 0.65411 | val 1.10441
  Epoch 021 - train 0.63834 | val 1.20188
  Classification -> best τ=0.215 (val F1=0.1060)
  Directional -> Accuracy: 0.4824, MCC: -0.0303, F1: 0.4246

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66019 | val 1.18407
  Epoch 020 - train 0.64144 | val 1.32231
  Epoch 021 - train 0.63094 | val 1.31992
  Classification -> best τ=0.295 (val F1=0.1553)
  Directional -> Accuracy: 0.4774, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67575 | val 1.09021
  Epoch 020 - train 0.64883 | val 1.31185
  Epoch 021 - train 0.64559 | val 1.31832
  Classification -> best τ=0.135 (val F1=0.1194)
  Directional -> Accuracy: 0.5628, MCC: 0.1015, F1: 0.6813

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67508 | val 1.02344
  Epoch 020 - train 0.65377 | val 1.15937
  Epoch 021 - train 0.64505 | val 1.15644
  Classification -> best τ=0.205 (val F1=0.0655)
  Directional -> Accuracy: 0.5578, MCC: 0.0089, F1: 0.6835

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67283 | val 0.81077
  Epoch 020 - train 0.64700 | val 0.80565
  Epoch 021 - train 0.64967 | val 0.81109
  Classification -> best τ=0.650 (val F1=0.0954)
  Directional -> Accuracy: 0.4372, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65736 | val 1.79688
  Epoch 020 - train 0.62486 | val 1.37799
  Epoch 021 - train 0.63166 | val 1.46394
  Classification -> best τ=0.125 (val F1=0.0417)
  Directional -> Accuracy: 0.4171, MCC: 0.0224, F1: 0.1343

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66511 | val 1.11810
  Epoch 020 - train 0.63768 | val 1.66030
  Epoch 021 - train 0.64149 | val 1.61192
  Classification -> best τ=0.540 (val F1=0.1421)
  Directional -> Accuracy: 0.4724, MCC: -0.0699, F1: 0.3396

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68253 | val 0.76170
  Epoch 020 - train 0.64343 | val 0.80448
  Epoch 021 - train 0.63724 | val 0.78278
  Classification -> best τ=0.410 (val F1=0.0884)
  Directional -> Accuracy: 0.5226, MCC: 0.1131, F1: 0.4444

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66472 | val 0.83347
  Epoch 020 - train 0.64475 | val 0.94218
  Epoch 021 - train 0.64609 | val 0.89264
  Classification -> best τ=0.640 (val F1=0.1151)
  Directional -> Accuracy: 0.4221, MCC: -0.1072, F1: 0.1085

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66438 | val 0.87313
  Epoch 020 - train 0.63367 | val 0.79997
  Epoch 021 - train 0.63524 | val 0.76505
  Classification -> best τ=0.640 (val F1=0.1354)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66325 | val 0.73424
  Epoch 020 - train 0.65035 | val 0.77392
  Epoch 021 - train 0.63326 | val 0.80352
  Classification -> best τ=0.665 (val F1=0.0944)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.65108 | val 1.67341
  Epoch 020 - train 0.64206 | val 1.57324
  Epoch 021 - train 0.64215 | val 1.55997
  Classification -> best τ=0.400 (val F1=0.1483)
  Directional -> Accuracy: 0.4372, MCC: 0.0256, F1: 0.2329

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.65463 | val 1.01542
  Epoch 020 - train 0.65834 | val 1.15804
  Epoch 021 - train 0.63327 | val 1.18743
  Classification -> best τ=0.360 (val F1=0.1664)
  Directional -> Accuracy: 0.4975, MCC: -0.0020, F1: 0.6296

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67932 | val 1.08328
  Epoch 020 - train 0.65251 | val 1.15756
  Epoch 021 - train 0.64414 | val 1.26820
  Classification -> best τ=0.290 (val F1=0.1383)
  Directional -> Accuracy: 0.5226, MCC: 0.0000, F1: 0.6865

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66799 | val 0.83933
  Epoch 020 - train 0.65353 | val 0.93787
  Epoch 021 - train 0.64599 | val 0.93131
  Classification -> best τ=0.395 (val F1=0.0852)
  Directional -> Accuracy: 0.5226, MCC: 0.0971, F1: 0.4242

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.66914 | val 0.92864
  Epoch 020 - train 0.65344 | val 1.06505
  Epoch 021 - train 0.64928 | val 1.05143
  Classification -> best τ=0.325 (val F1=0.1396)
  Directional -> Accuracy: 0.4573, MCC: -0.0727, F1: 0.3864

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65704 | val 1.01061
  Epoch 020 - train 0.62730 | val 1.08610
  Epoch 021 - train 0.61591 | val 1.12558
  Classification -> best τ=0.530 (val F1=0.2279)
  Directional -> Accuracy: 0.4171, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67359 | val 0.91757
  Epoch 020 - train 0.64905 | val 1.00549
  Epoch 021 - train 0.63939 | val 0.99142
  Classification -> best τ=0.410 (val F1=0.1747)
  Directional -> Accuracy: 0.5276, MCC: 0.0986, F1: 0.4051

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65311 | val 1.42422
  Epoch 020 - train 0.64082 | val 1.36523
  Epoch 021 - train 0.62640 | val 1.40796
  Classification -> best τ=0.175 (val F1=0.1054)
  Directional -> Accuracy: 0.4774, MCC: 0.0000, F1: 0.6463

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66784 | val 1.36627
  Epoch 020 - train 0.62919 | val 1.64863
  Epoch 021 - train 0.62645 | val 1.55401
  Classification -> best τ=0.405 (val F1=0.1939)
  Directional -> Accuracy: 0.4975, MCC: 0.0295, F1: 0.1525

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.67359 | val 1.05377
  Epoch 020 - train 0.63131 | val 1.34066
  Epoch 021 - train 0.63851 | val 1.44656
  Classification -> best τ=0.610 (val F1=0.1134)
  Directional -> Accuracy: 0.5327, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.65048 | val 2.30271
  Epoch 020 - train 0.62501 | val 2.77498

[I 2026-02-26 01:36:49,321] Trial 21 finished with value: 0.1468921473633703 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.0006033808677406283, 'weight_decay': 2.7215172146069747e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.6726255759973994, 'early_stopping_min_delta': 0.002651547616898427}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 021 - train 0.65293 | val 0.97204
  Classification -> best τ=0.380 (val F1=0.1519)
  Directional -> Accuracy: 0.4925, MCC: -0.0066, F1: 0.6189

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1468921473633703
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68390 | val 0.96781
  Epoch 020 - train 0.66689 | val 1.01596
  Epoch 021 - train 0.65844 | val 1.08809
  Classification -> best τ=0.345 (val F1=0.1104)
  Directional -> Accuracy: 0.5400, MCC: 0.0899, F1: 0.5660

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.65749 | val 2.56337
  Epoch 020 - train 0.60983 | val 3.73410
  Epoch 021 - train 0.59536 | val 3.90672
  Classification -> best τ=0.065 (val F1=0.1290)
  Directional -> Accuracy: 0.5200, MCC: 0.0401, F1: 0.5052

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66626 | val 0.73425
  Epoch 020 - train 0.64484 | val 0.82203
  Epoch 022 - train 0.64253 | val 0.76580
  Classification -> best τ=0.300 (val F1=0.1851)
  Directional -> Accuracy: 0.5508, MCC: -0.0125, F1: 0.6866

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.67874 | val 0.73000
  Epoch 020 - train 0.66220 | val 0.75874
  Epoch 030 - train 0.63405 | val 0.76692
  Classification -> best τ=0.515 (val F1=0.1764)
  Directional -> Accuracy: 0.4350, MCC: -0.0504, F1: 0.0504

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.66953 | val 0.90981
  Epoch 020 - train 0.60053 | val 0.99446
  Epoch 021 - train 0.65055 | val 0.95557
  Classification -> best τ=0.635 (val F1=0.2235)
  Directional -> Accuracy: 0.4766, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66986 | val 0.80258
  Epoch 020 - train 0.64120 | val 1.01607
  Epoch 021 - train 0.64315 | val 0.99029
  Classification -> best τ=0.310 (val F1=0.0980)
  Directional -> Accuracy: 0.5300, MCC: 0.0274, F1: 0.6116

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66412 | val 0.91737
  Epoch 020 - train 0.66305 | val 1.11458
  Epoch 021 - train 0.66340 | val 1.06837
  Classification -> best τ=0.780 (val F1=0.1072)
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66403 | val 0.96988
  Epoch 020 - train 0.63936 | val 1.05215
  Epoch 021 - train 0.63240 | val 1.08272
  Classification -> best τ=0.220 (val F1=0.2667)
  Directional -> Accuracy: 0.5450, MCC: 0.0878, F1: 0.5919

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67297 | val 2.22430
  Epoch 020 - train 0.62358 | val 2.45377
  Epoch 021 - train 0.62828 | val 2.38609
  Classification -> best τ=0.440 (val F1=0.1679)
  Directional -> Accuracy: 0.4174, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67247 | val 0.99392
  Epoch 020 - train 0.64786 | val 1.25882
  Epoch 021 - train 0.64757 | val 1.33068
  Classification -> best τ=0.750 (val F1=0.0616)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.66806 | val 0.68244
  Epoch 020 - train 0.66342 | val 0.78075
  Epoch 029 - train 0.61449 | val 0.92802
  Classification -> best τ=0.595 (val F1=0.1843)
  Directional -> Accuracy: 0.4950, MCC: 0.0053, F1: 0.4656

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.67977 | val 0.70832
  Epoch 020 - train 0.65082 | val 0.77622
  Epoch 025 - train 0.64203 | val 0.79030
  Classification -> best τ=0.565 (val F1=0.1524)
  Directional -> Accuracy: 0.4250, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66370 | val 1.06055
  Epoch 020 - train 0.63285 | val 1.24610
  Epoch 024 - train 0.62258 | val 1.42932
  Classification -> best τ=0.695 (val F1=0.1377)
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67560 | val 0.88476
  Epoch 020 - train 0.63563 | val 1.18311
  Epoch 021 - train 0.64105 | val 1.14601
  Classification -> best τ=0.740 (val F1=0.1942)
  Directional -> Accuracy: 0.5050, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.69706 | val 0.86060
  Epoch 020 - train 0.65479 | val 0.85921
  Epoch 021 - train 0.66511 | val 0.86651
  Classification -> best τ=0.230 (val F1=0.0884)
  Directional -> Accuracy: 0.4850, MCC: -0.0811, F1: 0.6113

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.66206 | val 1.28840
  Epoch 020 - train 0.62720 | val 1.57694
  Epoch 021 - train 0.63699 | val 1.52637
  Classification -> best τ=0.605 (val F1=0.1560)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.68074 | val 0.88271
  Epoch 020 - train 0.64020 | val 1.06142
  Epoch 021 - train 0.65105 | val 1.00253
  Classification -> best τ=0.375 (val F1=0.1595)
  Directional -> Accuracy: 0.5550, MCC: 0.0000, F1: 0.7138

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66902 | val 0.97123
  Epoch 020 - train 0.64399 | val 1.08596
  Epoch 021 - train 0.62251 | val 1.10578
  Classification -> best τ=0.490 (val F1=0.1429)
  Directional -> Accuracy: 0.4900, MCC: 0.0374, F1: 0.0377

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68425 | val 0.71863
  Epoch 020 - train 0.66430 | val 0.80800
  Epoch 021 - train 0.65060 | val 0.80344
  Classification -> best τ=0.420 (val F1=0.2680)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66435 | val 0.84147
  Epoch 020 - train 0.64514 | val 0.87915
  Epoch 021 - train 0.63963 | val 0.88539
  Classification -> best τ=0.810 (val F1=0.1103)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.67087 | val 0.78860
  Epoch 020 - train 0.64752 | val 0.85245
  Epoch 024 - train 0.63534 | val 0.94912
  Classification -> best τ=0.630 (val F1=0.2397)
  Directional -> Accuracy: 0.4950, MCC: 0.0695, F1: 0.6599

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.69169 | val 0.91098
  Epoch 020 - train 0.66549 | val 1.22789
  Epoch 021 - train 0.66889 | val 1.29412
  Classification -> best τ=0.245 (val F1=0.1474)
  Directional -> Accuracy: 0.4750, MCC: 0.0353, F1: 0.3137

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68585 | val 0.77674
  Epoch 020 - train 0.64499 | val 0.96499
  Epoch 021 - train 0.64822 | val 0.98796
  Classification -> best τ=0.425 (val F1=0.1411)
  Directional -> Accuracy: 0.5050, MCC: 0.0767, F1: 0.3444

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.68126 | val 1.09436
  Epoch 020 - train 0.64511 | val 1.04269
  Epoch 021 - train 0.64372 | val 1.13783
  Classification -> best τ=0.215 (val F1=0.1665)
  Directional -> Accuracy: 0.4150, MCC: -0.0329, F1: 0.5301

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67580 | val 0.93790
  Epoch 020 - train 0.63415 | val 1.15244
  Epoch 021 - train 0.62199 | val 1.19861
  Classification -> best τ=0.320 (val F1=0.1133)
  Directional -> Accuracy: 0.5550, MCC: 0.1174, F1: 0.5291

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68389 | val 0.78603
  Epoch 020 - train 0.65709 | val 0.85480
  Epoch 026 - train 0.64645 | val 0.90947
  Classification -> best τ=0.455 (val F1=0.1559)
  Directional -> Accuracy: 0.5700, MCC: 0.1833, F1: 0.2833

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68464 | val 0.71728
  Epoch 020 - train 0.65068 | val 0.80190
  Epoch 025 - train 0.64672 | val 0.85834
  Classification -> best τ=0.535 (val F1=0.1559)
  Directional -> Accuracy: 0.4650, MCC: 0.0193, F1: 0.0531

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.67671 | val 0.90350
  Epoch 020 - train 0.64875 | val 1.12748
  Epoch 023 - train 0.64955 | val 1.13327
  Classification -> best τ=0.815 (val F1=0.0860)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66982 | val 1.06293
  Epoch 020 - train 0.64374 | val 1.75683
  Epoch 021 - train 0.64790 | val 1.95123
  Classification -> best τ=0.610 (val F1=0.1203)
  Directional -> Accuracy: 0.5100, MCC: 0.0587, F1: 0.2576

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.68303 | val 0.79345
  Epoch 020 - train 0.65646 | val 0.74365
  Epoch 024 - train 0.65787 | val 0.89367
  Classification -> best τ=0.610 (val F1=0.1635)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.67468 | val 1.52678
  Epoch 020 - train 0.65251 | val 2.68577
  Epoch 021 - train 0.64511 | val 2.14330
  Classification -> best τ=0.215 (val F1=0.2149)
  Directional -> Accuracy: 0.4950, MCC: -0.0048, F1: 0.2734

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68053 | val 0.74912
  Epoch 020 - train 0.65265 | val 0.84676
  Epoch 021 - train 0.66667 | val 0.83482
  Classification -> best τ=0.490 (val F1=0.1429)
  Directional -> Accuracy: 0.5650, MCC: 0.0836, F1: 0.6947

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.68870 | val 0.78714
  Epoch 020 - train 0.66863 | val 0.92138
  Epoch 026 - train 0.67005 | val 0.92452
  Classification -> best τ=0.270 (val F1=0.1225)
  Directional -> Accuracy: 0.5750, MCC: -0.0307, F1: 0.7176

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66411 | val 0.83680
  Epoch 020 - train 0.64615 | val 0.78337
  Epoch 030 - train 0.61727 | val 0.87338
  Classification -> best τ=0.635 (val F1=0.1222)
  Directional -> Accuracy: 0.5900, MCC: 0.1433, F1: 0.3594

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.63788 | val 1.19188
  Epoch 020 - train 0.65762 | val 1.15658
  Epoch 021 - train 0.63405 | val 1.10710
  Classification -> best τ=0.515 (val F1=0.2036)
  Directional -> Accuracy: 0.4792, MCC: -0.0861, F1: 0.6377

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66094 | val 0.76637
  Epoch 020 - train 0.63482 | val 0.78957
  Epoch 023 - train 0.62709 | val 0.80039
  Classification -> best τ=0.490 (val F1=0.1926)
  Directional -> Accuracy: 0.4500, MCC: 0.0652, F1: 0.1912

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67751 | val 0.72841
  Epoch 020 - train 0.65866 | val 0.79825
  Epoch 021 - train 0.65923 | val 0.83041
  Classification -> best τ=0.655 (val F1=0.1937)
  Directional -> Accuracy: 0.4750, MCC: 0.0464, F1: 0.0708

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.67026 | val 1.17785
  Epoch 020 - train 0.64921 | val 1.29594
  Epoch 021 - train 0.63761 | val 1.41067
  Classification -> best τ=0.250 (val F1=0.1595)
  Directional -> Accuracy: 0.5700, MCC: 0.0538, F1: 0.7152

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.66984 | val 1.30233
  Epoch 020 - train 0.64433 | val 1.67608
  Epoch 021 - train 0.62873 | val 1.64550
  Classification -> best τ=0.760 (val F1=0.0952)
  Directional -> Accuracy: 0.4550, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.67345 | val 0.86869
  Epoch 020 - train 0.66200 | val 0.98166
  Epoch 021 - train 0.64864 | val 1.00302
  Classification -> best τ=0.365 (val F1=0.0929)
  Directional -> Accuracy: 0.4800, MCC: -0.0396, F1: 0.4902

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.67967 | val 0.75903
  Epoch 020 - train 0.66072 | val 0.88365
  Epoch 021 - train 0.66518 | val 0.85229
  Classification -> best τ=0.745 (val F1=0.1511)
  Directional -> Accuracy: 0.4950, MCC: 0.0449, F1: 0.0901

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67726 | val 1.00103
  Epoch 020 - train 0.64380 | val 1.29088
  Epoch 021 - train 0.65368 | val 1.13265
  Classification -> best τ=0.215 (val F1=0.0975)
  Directional -> Accuracy: 0.5400, MCC: 0.0081, F1: 0.6993

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67821 | val 1.03414
  Epoch 020 - train 0.65670 | val 1.13975
  Epoch 026 - train 0.63964 | val 1.40496
  Classification -> best τ=0.195 (val F1=0.1559)
  Directional -> Accuracy: 0.5350, MCC: 0.0698, F1: 0.6618

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67519 | val 0.84815
  Epoch 020 - train 0.64863 | val 1.00116
  Epoch 021 - train 0.64376 | val 1.10419
  Classification -> best τ=0.385 (val F1=0.1787)
  Directional -> Accuracy: 0.4800, MCC: -0.0057, F1: 0.0370

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65668 | val 1.31046
  Epoch 020 - train 0.64460 | val 1.91532
  Epoch 021 - train 0.63965 | val 1.84822
  Classification -> best τ=0.075 (val F1=0.1189)
  Directional -> Accuracy: 0.5250, MCC: 0.0214, F1: 0.6215

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67120 | val 0.98302
  Epoch 020 - train 0.65422 | val 0.91561
  Epoch 021 - train 0.64877 | val 0.92521
  Classification -> best τ=0.565 (val F1=0.0427)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66559 | val 0.82408
  Epoch 020 - train 0.64600 | val 0.92592
  Epoch 026 - train 0.63799 | val 0.91311
  Classification -> best τ=0.230 (val F1=0.1406)
  Directional -> Accuracy: 0.5800, MCC: 0.0943, F1: 0.7123

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67620 | val 0.69929
  Epoch 020 - train 0.64218 | val 0.72627
  Epoch 030 - train 0.59145 | val 0.75832
  Classification -> best τ=0.595 (val F1=0.1482)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67711 | val 0.85296
  Epoch 020 - train 0.64788 | val 0.90929
  Epoch 024 - train 0.63865 | val 1.00992
  Classification -> best τ=0.520 (val F1=0.1432)
  Directional -> Accuracy: 0.5200, MCC: 0.0348, F1: 0.3766

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67778 | val 0.92588
  Epoch 020 - train 0.65764 | val 0.93272
  Epoch 029 - train 0.61633 | val 1.06095
  Classification -> best τ=0.610 (val F1=0.1487)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68774 | val 0.74041
  Epoch 020 - train 0.64830 | val 0.78976
  Epoch 021 - train 0.65277 | val 0.81322
  Classification -> best τ=0.575 (val F1=0.1116)
  Directional -> Accuracy: 0.4200, MCC: -0.1066, F1: 0.1471

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66904 | val 0.82056
  Epoch 020 - train 0.63464 | val 0.82758
  Epoch 025 - train 0.63780 | val 0.89985
  Classification -> best τ=0.265 (val F1=0.0987)
  Directional -> Accuracy: 0.5300, MCC: 0.0703, F1: 0.4125

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66569 | val 0.89859
  Epoch 020 - train 0.65674 | val 0.83876
  Epoch 021 - train 0.65208 | val 0.83865
  Classification -> best τ=0.580 (val F1=0.1263)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.67309 | val 0.80719
  Epoch 020 - train 0.65476 | val 0.80161
  Epoch 023 - train 0.64759 | val 0.84242
  Classification -> best τ=0.530 (val F1=0.1470)
  Directional -> Accuracy: 0.4200, MCC: -0.0106, F1: 0.1594

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.68709 | val 0.81235
  Epoch 020 - train 0.64401 | val 0.94507
  Epoch 024 - train 0.64976 | val 0.98353
  Classification -> best τ=0.235 (val F1=0.2015)
  Directional -> Accuracy: 0.4900, MCC: -0.0716, F1: 0.6577

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67641 | val 0.81497
  Epoch 020 - train 0.66172 | val 0.84908
  Epoch 021 - train 0.66052 | val 0.85379
  Classification -> best τ=0.455 (val F1=0.1186)
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.6885

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68006 | val 0.88327
  Epoch 020 - train 0.64208 | val 1.04077
  Epoch 021 - train 0.64023 | val 1.01916
  Classification -> best τ=0.365 (val F1=0.1056)
  Directional -> Accuracy: 0.5000, MCC: 0.0932, F1: 0.2958

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.67939 | val 0.70376
  Epoch 020 - train 0.64347 | val 0.74507
  Epoch 030 - train 0.63731 | val 0.71961
  Classification -> best τ=0.580 (val F1=0.1106)
  Directional -> Accuracy: 0.4650, MCC: -0.0507, F1: 0.1301

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65397 | val 1.18547
  Epoch 020 - train 0.63571 | val 1.18999
  Epoch 021 - train 0.64512 | val 1.26622
  Classification -> best τ=0.545 (val F1=0.1664)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67211 | val 0.85041
  Epoch 020 - train 0.63977 | val 0.82740
  Epoch 024 - train 0.64935 | val 0.85682
  Classification -> best τ=0.325 (val F1=0.1789)
  Directional -> Accuracy: 0.4800, MCC: -0.0275, F1: 0.4348

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67057 | val 1.22100
  Epoch 020 - train 0.65943 | val 1.11573
  Epoch 021 - train 0.65387 | val 1.20529
  Classification -> best τ=0.055 (val F1=0.1046)
  Directional -> Accuracy: 0.4700, MCC: -0.0745, F1: 0.6395

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67124 | val 0.81811
  Epoch 020 - train 0.65323 | val 1.07122
  Epoch 021 - train 0.63496 | val 1.15224
  Classification -> best τ=0.425 (val F1=0.1542)
  Directional -> Accuracy: 0.4750, MCC: -0.0482, F1: 0.2446

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.67377 | val 0.95243
  Epoch 020 - train 0.64895 | val 1.03956
  Epoch 021 - train 0.65730 | val 1.05901
  Classification -> best τ=0.240 (val F1=0.1359)
  Directional -> Accuracy: 0.4800, MCC: 0.0073, F1: 0.5969

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.67909 | val 1.29251
  Epoch 020 - train 0.64307 | val 1.01048

[I 2026-02-26 01:49:10,694] Trial 22 finished with value: 0.14896497173441947 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.0012414977022774671, 'weight_decay': 1.7581826741104575e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.17895812542603873, 'early_stopping_min_delta': 0.0009974402461391688}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 021 - train 0.66005 | val 1.37409
  Classification -> best τ=0.145 (val F1=0.1532)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.6577

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14896497173441947
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67287 | val 0.77607
  Epoch 020 - train 0.66949 | val 0.83899
  Epoch 021 - train 0.67856 | val 0.84418
  Classification -> best τ=0.365 (val F1=0.0906)
  Directional -> Accuracy: 0.5829, MCC: 0.0000, F1: 0.7365

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.67365 | val 1.85346
  Epoch 020 - train 0.65506 | val 1.98109
  Epoch 021 - train 0.64759 | val 1.95554
  Classification -> best τ=0.495 (val F1=0.1399)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66549 | val 0.78366
  Epoch 020 - train 0.64869 | val 0.82940
  Epoch 021 - train 0.64116 | val 0.82007
  Classification -> best τ=0.565 (val F1=0.1492)
  Directional -> Accuracy: 0.4140, MCC: -0.0894, F1: 0.0354

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.66990 | val 1.04190
  Epoch 020 - train 0.66212 | val 1.01882
  Epoch 021 - train 0.65687 | val 0.99653
  Classification -> best τ=0.485 (val F1=0.1586)
  Directional -> Accuracy: 0.4573, MCC: 0.0251, F1: 0.1818

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.65929 | val 0.69594
  Epoch 020 - train 0.63709 | val 0.71645
  Epoch 030 - train 0.62847 | val 0.69745
  Classification -> best τ=0.530 (val F1=0.1535)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66917 | val 1.02417
  Epoch 020 - train 0.63470 | val 1.07581
  Epoch 021 - train 0.64722 | val 1.09385
  Classification -> best τ=0.210 (val F1=0.1087)
  Directional -> Accuracy: 0.5327, MCC: -0.0580, F1: 0.6869

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66960 | val 0.92283
  Epoch 020 - train 0.65073 | val 1.09019
  Epoch 021 - train 0.65367 | val 1.11780
  Classification -> best τ=0.300 (val F1=0.1006)
  Directional -> Accuracy: 0.4975, MCC: -0.0931, F1: 0.6296

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64281 | val 0.82973
  Epoch 020 - train 0.63382 | val 0.81469
  Epoch 021 - train 0.62699 | val 0.80128
  Classification -> best τ=0.430 (val F1=0.2761)
  Directional -> Accuracy: 0.4221, MCC: 0.0129, F1: 0.2069

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65721 | val 0.97476
  Epoch 020 - train 0.65264 | val 0.98214
  Epoch 021 - train 0.65054 | val 0.96987
  Classification -> best τ=0.485 (val F1=0.1123)
  Directional -> Accuracy: 0.4211, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66232 | val 1.12227
  Epoch 020 - train 0.65166 | val 1.42976
  Epoch 021 - train 0.64974 | val 1.46552
  Classification -> best τ=0.450 (val F1=0.0963)
  Directional -> Accuracy: 0.5427, MCC: 0.0439, F1: 0.2222

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.68069 | val 0.73319
  Epoch 020 - train 0.65795 | val 0.80592
  Epoch 028 - train 0.64979 | val 0.82073
  Classification -> best τ=0.710 (val F1=0.1771)
  Directional -> Accuracy: 0.4573, MCC: 0.0000, F1: 0.0000

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.65818 | val 0.72418
  Epoch 020 - train 0.63851 | val 0.73697
  Epoch 021 - train 0.64176 | val 0.73659
  Classification -> best τ=0.750 (val F1=0.1054)
  Directional -> Accuracy: 0.4221, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67353 | val 0.81831
  Epoch 020 - train 0.66065 | val 0.88197
  Epoch 021 - train 0.65541 | val 0.89736
  Classification -> best τ=0.340 (val F1=0.1638)
  Directional -> Accuracy: 0.5528, MCC: 0.0123, F1: 0.6920

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67295 | val 0.69930
  Epoch 020 - train 0.64322 | val 0.72043
  Epoch 022 - train 0.64838 | val 0.73360
  Classification -> best τ=0.365 (val F1=0.1682)
  Directional -> Accuracy: 0.5126, MCC: 0.0383, F1: 0.6340

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.67823 | val 0.73913
  Epoch 020 - train 0.68326 | val 0.82067
  Epoch 021 - train 0.67844 | val 0.80232
  Classification -> best τ=0.455 (val F1=0.0671)
  Directional -> Accuracy: 0.4623, MCC: -0.0474, F1: 0.2914

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.66185 | val 1.06751
  Epoch 020 - train 0.64975 | val 1.20879
  Epoch 021 - train 0.64930 | val 1.18241
  Classification -> best τ=0.525 (val F1=0.1326)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.68351 | val 0.79190
  Epoch 020 - train 0.65777 | val 0.93720
  Epoch 021 - train 0.65966 | val 0.95538
  Classification -> best τ=0.395 (val F1=0.1463)
  Directional -> Accuracy: 0.5578, MCC: 0.0000, F1: 0.7161

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64831 | val 2.98659
  Epoch 020 - train 0.63264 | val 3.23227
  Epoch 021 - train 0.61753 | val 3.48573
  Classification -> best τ=0.425 (val F1=0.1749)
  Directional -> Accuracy: 0.4774, MCC: -0.0340, F1: 0.0545

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67422 | val 0.73405
  Epoch 020 - train 0.65380 | val 0.73579
  Epoch 023 - train 0.65713 | val 0.74078
  Classification -> best τ=0.440 (val F1=0.3368)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65510 | val 0.92300
  Epoch 020 - train 0.62965 | val 1.04584
  Epoch 021 - train 0.64523 | val 1.04241
  Classification -> best τ=0.270 (val F1=0.0867)
  Directional -> Accuracy: 0.5578, MCC: 0.0786, F1: 0.6812

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.65028 | val 0.81048
  Epoch 020 - train 0.64647 | val 0.80505
  Epoch 021 - train 0.64576 | val 0.81178
  Classification -> best τ=0.360 (val F1=0.1151)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.6599

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.67727 | val 1.01888
  Epoch 020 - train 0.66786 | val 1.10764
  Epoch 021 - train 0.68177 | val 1.07647
  Classification -> best τ=0.375 (val F1=0.1926)
  Directional -> Accuracy: 0.4372, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67400 | val 0.77981
  Epoch 020 - train 0.65812 | val 0.81582
  Epoch 021 - train 0.66670 | val 0.80889
  Classification -> best τ=0.350 (val F1=0.1193)
  Directional -> Accuracy: 0.5176, MCC: 0.0730, F1: 0.4353

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.66380 | val 1.02486
  Epoch 020 - train 0.64139 | val 0.94494
  Epoch 021 - train 0.65826 | val 0.95581
  Classification -> best τ=0.195 (val F1=0.1388)
  Directional -> Accuracy: 0.4171, MCC: 0.0591, F1: 0.5639

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66610 | val 0.95759
  Epoch 020 - train 0.64792 | val 0.97054
  Epoch 021 - train 0.65100 | val 0.98250
  Classification -> best τ=0.675 (val F1=0.0916)
  Directional -> Accuracy: 0.4774, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66562 | val 0.72832
  Epoch 020 - train 0.64841 | val 0.74128
  Epoch 021 - train 0.65930 | val 0.73223
  Classification -> best τ=0.290 (val F1=0.1312)
  Directional -> Accuracy: 0.5276, MCC: 0.0737, F1: 0.6083

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63610 | val 1.45572
  Epoch 020 - train 0.63040 | val 1.93162
  Epoch 021 - train 0.62782 | val 1.96444
  Classification -> best τ=0.485 (val F1=0.1979)
  Directional -> Accuracy: 0.4673, MCC: 0.0338, F1: 0.0862

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.66944 | val 1.33981
  Epoch 020 - train 0.65847 | val 1.58005
  Epoch 021 - train 0.65174 | val 1.52320
  Classification -> best τ=0.440 (val F1=0.0849)
  Directional -> Accuracy: 0.4925, MCC: -0.0148, F1: 0.6039

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67077 | val 0.86032
  Epoch 020 - train 0.66056 | val 0.95047
  Epoch 021 - train 0.66103 | val 0.94213
  Classification -> best τ=0.625 (val F1=0.1321)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.67646 | val 1.43192
  Epoch 020 - train 0.65308 | val 1.62843
  Epoch 021 - train 0.64575 | val 1.64639
  Classification -> best τ=0.510 (val F1=0.1695)
  Directional -> Accuracy: 0.5126, MCC: 0.1218, F1: 0.2920

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.65912 | val 1.08797
  Epoch 020 - train 0.64111 | val 1.23109
  Epoch 021 - train 0.64646 | val 1.32104
  Classification -> best τ=0.420 (val F1=0.1203)
  Directional -> Accuracy: 0.4874, MCC: -0.0806, F1: 0.6458

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67322 | val 0.74237
  Epoch 020 - train 0.65074 | val 0.80610
  Epoch 021 - train 0.66231 | val 0.81147
  Classification -> best τ=0.455 (val F1=0.1358)
  Directional -> Accuracy: 0.5779, MCC: 0.1211, F1: 0.6719

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.66434 | val 0.79381
  Epoch 020 - train 0.65646 | val 0.83211
  Epoch 021 - train 0.66726 | val 0.83894
  Classification -> best τ=0.410 (val F1=0.1459)
  Directional -> Accuracy: 0.4171, MCC: -0.0491, F1: 0.2840

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68737 | val 0.74744
  Epoch 020 - train 0.66834 | val 0.81660
  Epoch 021 - train 0.65924 | val 0.81408
  Classification -> best τ=0.375 (val F1=0.1231)
  Directional -> Accuracy: 0.4422, MCC: -0.0546, F1: 0.6105

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.61343 | val 1.07772
  Epoch 020 - train 0.60120 | val 1.18809
  Epoch 021 - train 0.61635 | val 1.20317
  Classification -> best τ=0.450 (val F1=0.1221)
  Directional -> Accuracy: 0.5106, MCC: 0.0815, F1: 0.6567

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64476 | val 0.84979
  Epoch 020 - train 0.64475 | val 0.82702
  Epoch 021 - train 0.63865 | val 0.83780
  Classification -> best τ=0.505 (val F1=0.1804)
  Directional -> Accuracy: 0.4221, MCC: 0.0210, F1: 0.0336

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65654 | val 0.95623
  Epoch 020 - train 0.63584 | val 1.03762
  Epoch 021 - train 0.63652 | val 1.09293
  Classification -> best τ=0.645 (val F1=0.2016)
  Directional -> Accuracy: 0.4673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.66480 | val 0.84987
  Epoch 020 - train 0.63915 | val 0.83027
  Epoch 021 - train 0.65222 | val 0.81289
  Classification -> best τ=0.595 (val F1=0.0916)
  Directional -> Accuracy: 0.4322, MCC: 0.0000, F1: 0.0000

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.68184 | val 1.18228
  Epoch 020 - train 0.65604 | val 1.38959
  Epoch 021 - train 0.66215 | val 1.39156
  Classification -> best τ=0.580 (val F1=0.0962)
  Directional -> Accuracy: 0.4573, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.66922 | val 1.02332
  Epoch 020 - train 0.66895 | val 0.98013
  Epoch 021 - train 0.64223 | val 0.98507
  Classification -> best τ=0.635 (val F1=0.2041)
  Directional -> Accuracy: 0.4673, MCC: -0.0363, F1: 0.0702

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.68088 | val 0.85237
  Epoch 020 - train 0.65558 | val 1.15363
  Epoch 021 - train 0.65675 | val 1.13852
  Classification -> best τ=0.635 (val F1=0.1318)
  Directional -> Accuracy: 0.4975, MCC: 0.0432, F1: 0.1667

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66784 | val 0.94865
  Epoch 020 - train 0.65961 | val 1.01813
  Epoch 021 - train 0.65418 | val 1.03359
  Classification -> best τ=0.350 (val F1=0.0967)
  Directional -> Accuracy: 0.5427, MCC: 0.0123, F1: 0.6997

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67357 | val 1.22790
  Epoch 020 - train 0.65090 | val 1.38361
  Epoch 021 - train 0.66953 | val 1.41385
  Classification -> best τ=0.385 (val F1=0.1732)
  Directional -> Accuracy: 0.5025, MCC: 0.0225, F1: 0.3265

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66242 | val 0.92310
  Epoch 020 - train 0.64993 | val 1.02964
  Epoch 021 - train 0.65493 | val 1.00226
  Classification -> best τ=0.525 (val F1=0.1818)
  Directional -> Accuracy: 0.4774, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67342 | val 1.39965
  Epoch 020 - train 0.66656 | val 1.49096
  Epoch 021 - train 0.65310 | val 1.53051
  Classification -> best τ=0.250 (val F1=0.1316)
  Directional -> Accuracy: 0.4724, MCC: -0.0543, F1: 0.4878

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66320 | val 0.97640
  Epoch 020 - train 0.65187 | val 0.98033
  Epoch 021 - train 0.65516 | val 0.98083
  Classification -> best τ=0.320 (val F1=0.1362)
  Directional -> Accuracy: 0.5879, MCC: 0.0000, F1: 0.7405

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66211 | val 0.81074
  Epoch 020 - train 0.66279 | val 0.86252
  Epoch 021 - train 0.65579 | val 0.84131
  Classification -> best τ=0.540 (val F1=0.1250)
  Directional -> Accuracy: 0.4372, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66832 | val 2.13185
  Epoch 020 - train 0.64191 | val 2.37406
  Epoch 021 - train 0.64436 | val 2.39545
  Classification -> best τ=0.230 (val F1=0.0759)
  Directional -> Accuracy: 0.5327, MCC: -0.0611, F1: 0.6618

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66570 | val 1.03922
  Epoch 020 - train 0.64107 | val 1.36121
  Epoch 021 - train 0.63171 | val 1.40036
  Classification -> best τ=0.615 (val F1=0.1683)
  Directional -> Accuracy: 0.5025, MCC: -0.0125, F1: 0.2774

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66892 | val 0.76671
  Epoch 020 - train 0.65030 | val 0.80419
  Epoch 026 - train 0.65935 | val 0.81457
  Classification -> best τ=0.615 (val F1=0.1342)
  Directional -> Accuracy: 0.4322, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67701 | val 0.73827
  Epoch 020 - train 0.66062 | val 0.78852
  Epoch 021 - train 0.65087 | val 0.79675
  Classification -> best τ=0.695 (val F1=0.1451)
  Directional -> Accuracy: 0.4221, MCC: -0.1062, F1: 0.1221

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65333 | val 0.79789
  Epoch 020 - train 0.63947 | val 0.82868
  Epoch 021 - train 0.64867 | val 0.82898
  Classification -> best τ=0.760 (val F1=0.1149)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66355 | val 0.78594
  Epoch 020 - train 0.64433 | val 0.81105
  Epoch 021 - train 0.65478 | val 0.80170
  Classification -> best τ=0.635 (val F1=0.1342)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.67240 | val 1.53708
  Epoch 020 - train 0.65309 | val 1.95332
  Epoch 021 - train 0.66102 | val 1.96641
  Classification -> best τ=0.340 (val F1=0.2110)
  Directional -> Accuracy: 0.4322, MCC: 0.0138, F1: 0.2207

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.65837 | val 0.88014
  Epoch 020 - train 0.64898 | val 1.08069
  Epoch 021 - train 0.64150 | val 1.09264
  Classification -> best τ=0.495 (val F1=0.0908)
  Directional -> Accuracy: 0.4573, MCC: -0.0968, F1: 0.5680

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67094 | val 1.19242
  Epoch 020 - train 0.64605 | val 1.54740
  Epoch 021 - train 0.65264 | val 1.52210
  Classification -> best τ=0.770 (val F1=0.1357)
  Directional -> Accuracy: 0.4774, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66275 | val 0.84000
  Epoch 020 - train 0.64984 | val 0.87093
  Epoch 021 - train 0.64918 | val 0.86276
  Classification -> best τ=0.625 (val F1=0.0971)
  Directional -> Accuracy: 0.4523, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.66828 | val 1.24570
  Epoch 020 - train 0.64985 | val 1.22631
  Epoch 021 - train 0.64643 | val 1.25381
  Classification -> best τ=0.380 (val F1=0.1699)
  Directional -> Accuracy: 0.5176, MCC: 0.0868, F1: 0.3333

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66369 | val 0.94030
  Epoch 020 - train 0.64048 | val 0.99189
  Epoch 021 - train 0.64704 | val 0.94428
  Classification -> best τ=0.450 (val F1=0.1989)
  Directional -> Accuracy: 0.4422, MCC: -0.0020, F1: 0.2449

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66745 | val 0.84194
  Epoch 020 - train 0.65284 | val 0.83684
  Epoch 021 - train 0.65478 | val 0.83314
  Classification -> best τ=0.470 (val F1=0.1640)
  Directional -> Accuracy: 0.4925, MCC: 0.0081, F1: 0.4094

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65403 | val 1.19568
  Epoch 020 - train 0.63353 | val 1.49155
  Epoch 021 - train 0.63450 | val 1.43596
  Classification -> best τ=0.650 (val F1=0.0892)
  Directional -> Accuracy: 0.5226, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66769 | val 1.26397
  Epoch 020 - train 0.65432 | val 1.33658
  Epoch 021 - train 0.64098 | val 1.39011
  Classification -> best τ=0.410 (val F1=0.2246)
  Directional -> Accuracy: 0.5126, MCC: 0.0369, F1: 0.4121

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.67139 | val 1.02778
  Epoch 020 - train 0.66249 | val 1.21512
  Epoch 021 - train 0.65814 | val 1.24966
  Classification -> best τ=0.610 (val F1=0.0759)
  Directional -> Accuracy: 0.5327, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.64929 | val 3.06051
  Epoch 020 - train 0.63259 | val 3.69953

[I 2026-02-26 02:06:37,933] Trial 23 finished with value: 0.14528125253371038 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.000270572946430065, 'weight_decay': 0.00012506581290423383, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.35138593450909783, 'early_stopping_min_delta': 0.0009772077619334494}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 021 - train 0.65569 | val 0.92854
  Classification -> best τ=0.460 (val F1=0.1768)
  Directional -> Accuracy: 0.5126, MCC: 0.0214, F1: 0.4121

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14528125253371038
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70029 | val 1.04973
  Epoch 020 - train 0.64980 | val 1.72948
  Epoch 024 - train 0.62073 | val 2.37570
  Classification -> best τ=0.180 (val F1=0.1736)
  Directional -> Accuracy: 0.5500, MCC: 0.0930, F1: 0.5946

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.65638 | val 3.37056
  Epoch 020 - train 0.52122 | val 8.61287
  Epoch 021 - train 0.54348 | val 8.89387
  Classification -> best τ=0.355 (val F1=0.1353)
  Directional -> Accuracy: 0.4950, MCC: -0.0320, F1: 0.0381

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66790 | val 0.79706
  Epoch 020 - train 0.61079 | val 1.30307
  Epoch 022 - train 0.58042 | val 1.27214
  Classification -> best τ=0.255 (val F1=0.1310)
  Directional -> Accuracy: 0.5882, MCC: 0.0980, F1: 0.7354

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.68290 | val 0.71417
  Epoch 020 - train 0.64466 | val 0.69389
  Epoch 027 - train 0.61851 | val 0.71538
  Classification -> best τ=0.565 (val F1=0.1608)
  Directional -> Accuracy: 0.4150, MCC: -0.1300, F1: 0.0787

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.65476 | val 0.81375
  Epoch 020 - train 0.57624 | val 0.86809
  Epoch 021 - train 0.56342 | val 0.79596
  Classification -> best τ=0.675 (val F1=0.2235)
  Directional -> Accuracy: 0.4766, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68584 | val 0.83290
  Epoch 020 - train 0.62137 | val 1.23419
  Epoch 026 - train 0.58449 | val 1.48389
  Classification -> best τ=0.730 (val F1=0.1061)
  Directional -> Accuracy: 0.4850, MCC: 0.0490, F1: 0.3087

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69368 | val 1.32552
  Epoch 020 - train 0.62732 | val 2.73378
  Epoch 023 - train 0.62027 | val 3.78150
  Classification -> best τ=0.590 (val F1=0.1313)
  Directional -> Accuracy: 0.4600, MCC: 0.1266, F1: 0.0690

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66926 | val 1.07834
  Epoch 020 - train 0.62980 | val 1.14958
  Epoch 026 - train 0.58303 | val 1.73889
  Classification -> best τ=0.295 (val F1=0.2106)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65666 | val 2.09583
  Epoch 020 - train 0.56188 | val 3.20322
  Epoch 021 - train 0.55652 | val 3.18418
  Classification -> best τ=0.180 (val F1=0.1589)
  Directional -> Accuracy: 0.4174, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67697 | val 1.15983
  Epoch 020 - train 0.62112 | val 1.99461
  Epoch 023 - train 0.60396 | val 2.18641
  Classification -> best τ=0.075 (val F1=0.0788)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.68073 | val 0.85677
  Epoch 020 - train 0.62902 | val 0.86208
  Epoch 021 - train 0.63131 | val 0.76833
  Classification -> best τ=0.545 (val F1=0.1678)
  Directional -> Accuracy: 0.5100, MCC: 0.0169, F1: 0.5377

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.66340 | val 0.75669
  Epoch 020 - train 0.63426 | val 0.77788
  Epoch 023 - train 0.61991 | val 0.87135
  Classification -> best τ=0.530 (val F1=0.1524)
  Directional -> Accuracy: 0.4650, MCC: 0.0554, F1: 0.2517

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66813 | val 0.79197
  Epoch 020 - train 0.62198 | val 0.75284
  Epoch 023 - train 0.60629 | val 0.81272
  Classification -> best τ=0.340 (val F1=0.1605)
  Directional -> Accuracy: 0.5400, MCC: 0.0666, F1: 0.5893

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67104 | val 1.01915
  Epoch 020 - train 0.59149 | val 1.19834
  Epoch 024 - train 0.54636 | val 1.54655
  Classification -> best τ=0.560 (val F1=0.1833)
  Directional -> Accuracy: 0.5100, MCC: 0.0183, F1: 0.2344

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.69683 | val 0.79787
  Epoch 020 - train 0.67218 | val 1.47997
  Epoch 027 - train 0.60403 | val 1.85996
  Classification -> best τ=0.265 (val F1=0.0796)
  Directional -> Accuracy: 0.5150, MCC: -0.0202, F1: 0.6523

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.66224 | val 1.79537
  Epoch 020 - train 0.58725 | val 3.12969
  Epoch 021 - train 0.59228 | val 2.57785
  Classification -> best τ=0.090 (val F1=0.1037)
  Directional -> Accuracy: 0.4850, MCC: -0.0306, F1: 0.5297

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.67181 | val 0.82318
  Epoch 020 - train 0.61563 | val 0.93047
  Epoch 024 - train 0.62450 | val 1.02619
  Classification -> best τ=0.330 (val F1=0.1470)
  Directional -> Accuracy: 0.5550, MCC: 0.0000, F1: 0.7138

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67001 | val 0.82061
  Epoch 020 - train 0.57075 | val 1.69523
  Epoch 026 - train 0.50659 | val 2.02237
  Classification -> best τ=0.805 (val F1=0.1470)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66596 | val 0.99957
  Epoch 020 - train 0.59265 | val 1.03775
  Epoch 023 - train 0.56644 | val 1.30140
  Classification -> best τ=0.515 (val F1=0.2691)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66906 | val 0.94743
  Epoch 020 - train 0.62444 | val 1.03119
  Epoch 022 - train 0.60047 | val 1.19588
  Classification -> best τ=0.295 (val F1=0.1009)
  Directional -> Accuracy: 0.5000, MCC: 0.0164, F1: 0.4681

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.68713 | val 0.74439
  Epoch 020 - train 0.66024 | val 1.14871
  Epoch 030 - train 0.53449 | val 2.88543
  Classification -> best τ=0.405 (val F1=0.1755)
  Directional -> Accuracy: 0.4850, MCC: -0.0723, F1: 0.6532

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.68567 | val 2.95214
  Epoch 020 - train 0.64166 | val 5.00176
  Epoch 021 - train 0.62034 | val 4.42034
  Classification -> best τ=0.515 (val F1=0.1232)
  Directional -> Accuracy: 0.4350, MCC: -0.0132, F1: 0.0174

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67856 | val 0.79405
  Epoch 020 - train 0.61170 | val 1.82119
  Epoch 021 - train 0.60787 | val 2.00188
  Classification -> best τ=0.425 (val F1=0.1953)
  Directional -> Accuracy: 0.4700, MCC: 0.0146, F1: 0.1970

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.67688 | val 1.12232
  Epoch 020 - train 0.65471 | val 1.05003
  Epoch 030 - train 0.66051 | val 1.30594
  Classification -> best τ=0.575 (val F1=0.1591)
  Directional -> Accuracy: 0.6050, MCC: 0.0307, F1: 0.0482

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66478 | val 0.97420
  Epoch 020 - train 0.57997 | val 3.91984
  Epoch 021 - train 0.56230 | val 3.39783
  Classification -> best τ=0.360 (val F1=0.0947)
  Directional -> Accuracy: 0.4800, MCC: -0.0057, F1: 0.0370

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69571 | val 0.74762
  Epoch 020 - train 0.64312 | val 0.86079
  Epoch 022 - train 0.63954 | val 0.91256
  Classification -> best τ=0.285 (val F1=0.1849)
  Directional -> Accuracy: 0.5600, MCC: 0.1520, F1: 0.6393

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68206 | val 0.71382
  Epoch 020 - train 0.61194 | val 0.93418
  Epoch 022 - train 0.63452 | val 0.94453
  Classification -> best τ=0.495 (val F1=0.0910)
  Directional -> Accuracy: 0.4950, MCC: -0.0044, F1: 0.4975

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.68011 | val 0.81291
  Epoch 020 - train 0.67005 | val 0.81817
  Epoch 029 - train 0.58787 | val 1.34799
  Classification -> best τ=0.610 (val F1=0.0860)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67817 | val 1.04971
  Epoch 020 - train 0.63377 | val 1.70637
  Epoch 021 - train 0.62372 | val 2.02691
  Classification -> best τ=0.710 (val F1=0.0768)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.69833 | val 0.71119
  Epoch 020 - train 0.64997 | val 0.76948
  Epoch 023 - train 0.62077 | val 0.86357
  Classification -> best τ=0.490 (val F1=0.1496)
  Directional -> Accuracy: 0.5800, MCC: 0.1421, F1: 0.6912

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.68501 | val 0.77948
  Epoch 020 - train 0.66346 | val 1.89416
  Epoch 029 - train 0.58579 | val 4.15009
  Classification -> best τ=0.480 (val F1=0.1553)
  Directional -> Accuracy: 0.4900, MCC: -0.0229, F1: 0.1053

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67284 | val 0.74794
  Epoch 020 - train 0.66666 | val 0.73559
  Epoch 030 - train 0.60291 | val 1.00080
  Classification -> best τ=0.575 (val F1=0.1608)
  Directional -> Accuracy: 0.4350, MCC: -0.0836, F1: 0.1630

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.68138 | val 1.23483
  Epoch 020 - train 0.63728 | val 2.27152
  Epoch 022 - train 0.63452 | val 2.44427
  Classification -> best τ=0.605 (val F1=0.1640)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66131 | val 0.79821
  Epoch 020 - train 0.64750 | val 0.82283
  Epoch 030 - train 0.57292 | val 1.03541
  Classification -> best τ=0.275 (val F1=0.0811)
  Directional -> Accuracy: 0.4550, MCC: -0.0034, F1: 0.5948

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.65041 | val 1.08832
  Epoch 020 - train 0.54112 | val 1.60753
  Epoch 022 - train 0.51919 | val 2.04425
  Classification -> best τ=0.425 (val F1=0.2927)
  Directional -> Accuracy: 0.5417, MCC: 0.0861, F1: 0.4762

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66829 | val 0.74271
  Epoch 020 - train 0.66624 | val 0.71506
  Epoch 030 - train 0.61837 | val 0.82598
  Classification -> best τ=0.485 (val F1=0.1977)
  Directional -> Accuracy: 0.4250, MCC: 0.0847, F1: 0.0336

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69262 | val 0.92843
  Epoch 020 - train 0.66808 | val 0.96060
  Epoch 030 - train 0.64170 | val 0.81775
  Classification -> best τ=0.720 (val F1=0.1822)
  Directional -> Accuracy: 0.4600, MCC: -0.0760, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.67129 | val 1.08091
  Epoch 020 - train 0.62305 | val 1.49353
  Epoch 022 - train 0.61264 | val 1.62043
  Classification -> best τ=0.270 (val F1=0.1068)
  Directional -> Accuracy: 0.5500, MCC: 0.0175, F1: 0.6786

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.66793 | val 1.74245
  Epoch 020 - train 0.60574 | val 3.75936
  Epoch 021 - train 0.57910 | val 3.35266
  Classification -> best τ=0.100 (val F1=0.0808)
  Directional -> Accuracy: 0.5450, MCC: 0.0000, F1: 0.7055

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.68898 | val 0.79968
  Epoch 020 - train 0.64359 | val 1.21837
  Epoch 022 - train 0.66076 | val 1.30162
  Classification -> best τ=0.425 (val F1=0.1137)
  Directional -> Accuracy: 0.4700, MCC: -0.0596, F1: 0.4804

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.70131 | val 0.72988
  Epoch 020 - train 0.67250 | val 0.73243
  Epoch 030 - train 0.66922 | val 0.83463
  Classification -> best τ=0.495 (val F1=0.1757)
  Directional -> Accuracy: 0.5050, MCC: -0.0058, F1: 0.6087

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66751 | val 1.16718
  Epoch 020 - train 0.62160 | val 1.55030
  Epoch 024 - train 0.60235 | val 1.92015
  Classification -> best τ=0.235 (val F1=0.0978)
  Directional -> Accuracy: 0.5350, MCC: -0.0120, F1: 0.6910

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67500 | val 1.08695
  Epoch 020 - train 0.60643 | val 1.57530
  Epoch 021 - train 0.60577 | val 1.42856
  Classification -> best τ=0.470 (val F1=0.1583)
  Directional -> Accuracy: 0.4950, MCC: 0.0255, F1: 0.1653

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67503 | val 0.91995
  Epoch 020 - train 0.63921 | val 1.39530
  Epoch 021 - train 0.63867 | val 1.42476
  Classification -> best τ=0.245 (val F1=0.1606)
  Directional -> Accuracy: 0.5200, MCC: 0.1036, F1: 0.2615

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66616 | val 1.98192
  Epoch 020 - train 0.58734 | val 2.94916
  Epoch 023 - train 0.54180 | val 3.68370
  Classification -> best τ=0.370 (val F1=0.0966)
  Directional -> Accuracy: 0.4900, MCC: 0.0287, F1: 0.3014

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66761 | val 1.18803
  Epoch 020 - train 0.64912 | val 1.46667
  Epoch 021 - train 0.62233 | val 1.63738
  Classification -> best τ=0.200 (val F1=0.0677)
  Directional -> Accuracy: 0.5700, MCC: -0.0020, F1: 0.7133

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67765 | val 0.92785
  Epoch 020 - train 0.65358 | val 0.95393
  Epoch 030 - train 0.54589 | val 2.15578
  Classification -> best τ=0.630 (val F1=0.1473)
  Directional -> Accuracy: 0.4450, MCC: 0.0533, F1: 0.0513

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67702 | val 0.73202
  Epoch 020 - train 0.58448 | val 1.03086
  Epoch 022 - train 0.57350 | val 1.31035
  Classification -> best τ=0.410 (val F1=0.0922)
  Directional -> Accuracy: 0.4750, MCC: -0.0775, F1: 0.5494

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66930 | val 0.91578
  Epoch 020 - train 0.64001 | val 0.90581
  Epoch 026 - train 0.57975 | val 0.97839
  Classification -> best τ=0.465 (val F1=0.1214)
  Directional -> Accuracy: 0.4900, MCC: -0.0313, F1: 0.3462

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67191 | val 0.87444
  Epoch 020 - train 0.63427 | val 0.73077
  Epoch 021 - train 0.63063 | val 0.76277
  Classification -> best τ=0.500 (val F1=0.0787)
  Directional -> Accuracy: 0.5100, MCC: -0.0368, F1: 0.6142

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68431 | val 0.91161
  Epoch 020 - train 0.64517 | val 0.98511
  Epoch 023 - train 0.60866 | val 1.23494
  Classification -> best τ=0.470 (val F1=0.0962)
  Directional -> Accuracy: 0.4350, MCC: -0.0657, F1: 0.2098

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69865 | val 0.73031
  Epoch 020 - train 0.64925 | val 0.75985
  Epoch 027 - train 0.58978 | val 1.00300
  Classification -> best τ=0.460 (val F1=0.1517)
  Directional -> Accuracy: 0.5150, MCC: 0.0397, F1: 0.3660

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67992 | val 0.76680
  Epoch 020 - train 0.66182 | val 0.70576
  Epoch 030 - train 0.58700 | val 0.86408
  Classification -> best τ=0.555 (val F1=0.1836)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.68223 | val 0.69325
  Epoch 020 - train 0.64162 | val 0.68931
  Epoch 026 - train 0.59105 | val 0.73542
  Classification -> best τ=0.635 (val F1=0.1463)
  Directional -> Accuracy: 0.4050, MCC: -0.0444, F1: 0.0775

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.65556 | val 0.81260
  Epoch 020 - train 0.63752 | val 1.04701
  Epoch 027 - train 0.56058 | val 1.44722
  Classification -> best τ=0.215 (val F1=0.2344)
  Directional -> Accuracy: 0.4700, MCC: -0.1228, F1: 0.6345

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68811 | val 1.64582
  Epoch 020 - train 0.63909 | val 2.67821
  Epoch 021 - train 0.62673 | val 1.83790
  Classification -> best τ=0.100 (val F1=0.1186)
  Directional -> Accuracy: 0.5400, MCC: 0.1042, F1: 0.6933

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68214 | val 0.75366
  Epoch 020 - train 0.62484 | val 1.02769
  Epoch 025 - train 0.59880 | val 1.48842
  Classification -> best τ=0.630 (val F1=0.1021)
  Directional -> Accuracy: 0.4500, MCC: -0.0177, F1: 0.0517

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.68738 | val 0.68707
  Epoch 020 - train 0.67529 | val 0.76670
  Epoch 024 - train 0.63498 | val 0.77945
  Classification -> best τ=0.675 (val F1=0.1591)
  Directional -> Accuracy: 0.4700, MCC: -0.0745, F1: 0.0000

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68147 | val 0.87855
  Epoch 020 - train 0.64661 | val 1.23693
  Epoch 025 - train 0.62581 | val 1.59001
  Classification -> best τ=0.535 (val F1=0.2313)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67048 | val 0.77601
  Epoch 020 - train 0.60301 | val 0.87101
  Epoch 026 - train 0.57293 | val 1.28307
  Classification -> best τ=0.390 (val F1=0.2151)
  Directional -> Accuracy: 0.4850, MCC: -0.0007, F1: 0.3439

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68132 | val 0.91488
  Epoch 020 - train 0.62784 | val 1.59074
  Epoch 022 - train 0.60493 | val 1.99641
  Classification -> best τ=0.855 (val F1=0.1186)
  Directional -> Accuracy: 0.5200, MCC: -0.0009, F1: 0.1579

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66233 | val 1.39506
  Epoch 020 - train 0.63157 | val 1.38688
  Epoch 030 - train 0.52717 | val 1.40766
  Classification -> best τ=0.155 (val F1=0.2152)
  Directional -> Accuracy: 0.5350, MCC: 0.0752, F1: 0.4918

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.68139 | val 1.15541
  Epoch 020 - train 0.60041 | val 1.18294
  Epoch 027 - train 0.54573 | val 2.34145
  Classification -> best τ=0.440 (val F1=0.1057)
  Directional -> Accuracy: 0.5350, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.67609 | val 1.83189
  Epoch 020 - train 0.61446 | val 1.19396

[I 2026-02-26 02:19:19,835] Trial 24 finished with value: 0.1458495441696632 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.00427370382548367, 'weight_decay': 2.444179951101184e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.7415649992774478, 'early_stopping_min_delta': 0.002347972839592463}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 030 - train 0.55439 | val 2.21545
  Classification -> best τ=0.340 (val F1=0.1611)
  Directional -> Accuracy: 0.4950, MCC: 0.0039, F1: 0.6160

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1458495441696632
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68285 | val 0.73872
  Epoch 020 - train 0.67808 | val 0.74089
  Epoch 021 - train 0.67424 | val 0.73791
  Classification -> best τ=0.415 (val F1=0.0394)
  Directional -> Accuracy: 0.5758, MCC: -0.0066, F1: 0.7237

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.67211 | val 1.16446
  Epoch 020 - train 0.67018 | val 1.26955
  Epoch 021 - train 0.66399 | val 1.28091
  Classification -> best τ=0.470 (val F1=0.1178)
  Directional -> Accuracy: 0.5101, MCC: 0.0274, F1: 0.2595

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67231 | val 0.71529
  Epoch 020 - train 0.66773 | val 0.71936
  Epoch 021 - train 0.67698 | val 0.71952
  Classification -> best τ=0.495 (val F1=0.1737)
  Directional -> Accuracy: 0.4757, MCC: 0.0787, F1: 0.2920

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.67928 | val 0.72034
  Epoch 020 - train 0.67675 | val 0.73192
  Epoch 021 - train 0.67835 | val 0.73293
  Classification -> best τ=0.555 (val F1=0.1156)
  Directional -> Accuracy: 0.4394, MCC: -0.0597, F1: 0.2930

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.66136 | val 0.73272
  Epoch 020 - train 0.66448 | val 0.73381
  Epoch 021 - train 0.66116 | val 0.73529
  Classification -> best τ=0.480 (val F1=0.0994)
  Directional -> Accuracy: 0.4434, MCC: -0.1190, F1: 0.0923

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67447 | val 0.75636
  Epoch 020 - train 0.67665 | val 0.76565
  Epoch 021 - train 0.67407 | val 0.76634
  Classification -> best τ=0.580 (val F1=0.1027)
  Directional -> Accuracy: 0.4495, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68425 | val 0.69458
  Epoch 020 - train 0.67909 | val 0.70246
  Epoch 021 - train 0.67835 | val 0.70736
  Classification -> best τ=0.560 (val F1=0.1392)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67145 | val 0.67548
  Epoch 020 - train 0.67000 | val 0.68232
  Epoch 028 - train 0.66890 | val 0.68172
  Classification -> best τ=0.300 (val F1=0.2608)
  Directional -> Accuracy: 0.4091, MCC: 0.1145, F1: 0.0640

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68319 | val 0.71044
  Epoch 020 - train 0.67117 | val 0.71235
  Epoch 021 - train 0.66141 | val 0.71333
  Classification -> best τ=0.560 (val F1=0.1442)
  Directional -> Accuracy: 0.4248, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68182 | val 0.77608
  Epoch 020 - train 0.68395 | val 0.79710
  Epoch 023 - train 0.67459 | val 0.79843
  Classification -> best τ=0.275 (val F1=0.1210)
  Directional -> Accuracy: 0.4697, MCC: 0.0604, F1: 0.6316

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.67978 | val 0.69424
  Epoch 020 - train 0.67611 | val 0.69917
  Epoch 021 - train 0.68425 | val 0.69774
  Classification -> best τ=0.465 (val F1=0.0774)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.7016

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.66172 | val 0.73083
  Epoch 020 - train 0.66281 | val 0.74082
  Epoch 021 - train 0.67051 | val 0.74035
  Classification -> best τ=0.590 (val F1=0.1020)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66923 | val 0.73775
  Epoch 020 - train 0.67595 | val 0.74037
  Epoch 021 - train 0.67504 | val 0.74260
  Classification -> best τ=0.500 (val F1=0.0854)
  Directional -> Accuracy: 0.4646, MCC: -0.0083, F1: 0.3291

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67513 | val 0.68856
  Epoch 020 - train 0.67323 | val 0.70153
  Epoch 025 - train 0.67336 | val 0.70055
  Classification -> best τ=0.610 (val F1=0.1730)
  Directional -> Accuracy: 0.5051, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.67469 | val 0.76438
  Epoch 020 - train 0.67586 | val 0.79318
  Epoch 021 - train 0.68176 | val 0.79177
  Classification -> best τ=0.325 (val F1=0.0518)
  Directional -> Accuracy: 0.5303, MCC: 0.0087, F1: 0.6890

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.67629 | val 0.78971
  Epoch 020 - train 0.67124 | val 0.81286
  Epoch 021 - train 0.66959 | val 0.82180
  Classification -> best τ=0.470 (val F1=0.1325)
  Directional -> Accuracy: 0.5303, MCC: 0.0689, F1: 0.6204

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.68123 | val 0.72776
  Epoch 020 - train 0.68103 | val 0.72835
  Epoch 021 - train 0.67436 | val 0.73098
  Classification -> best τ=0.415 (val F1=0.1147)
  Directional -> Accuracy: 0.5556, MCC: 0.0113, F1: 0.7124

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67093 | val 0.79812
  Epoch 020 - train 0.66987 | val 0.81101
  Epoch 021 - train 0.66110 | val 0.80809
  Classification -> best τ=0.480 (val F1=0.1304)
  Directional -> Accuracy: 0.4949, MCC: -0.0056, F1: 0.4624

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67238 | val 0.72545
  Epoch 020 - train 0.66957 | val 0.73912
  Epoch 021 - train 0.67390 | val 0.73879
  Classification -> best τ=0.435 (val F1=0.1954)
  Directional -> Accuracy: 0.5051, MCC: 0.0000, F1: 0.6711

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67370 | val 0.74456
  Epoch 020 - train 0.67068 | val 0.75585
  Epoch 021 - train 0.67363 | val 0.75662
  Classification -> best τ=0.605 (val F1=0.0973)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.67040 | val 0.73399
  Epoch 020 - train 0.67149 | val 0.75440
  Epoch 021 - train 0.66734 | val 0.75544
  Classification -> best τ=0.380 (val F1=0.0421)
  Directional -> Accuracy: 0.4444, MCC: -0.1186, F1: 0.3678

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.68404 | val 0.82868
  Epoch 020 - train 0.67783 | val 0.86023
  Epoch 021 - train 0.67835 | val 0.85056
  Classification -> best τ=0.475 (val F1=0.1603)
  Directional -> Accuracy: 0.5000, MCC: 0.0955, F1: 0.3356

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67122 | val 0.76552
  Epoch 020 - train 0.66456 | val 0.77529
  Epoch 021 - train 0.66482 | val 0.78060
  Classification -> best τ=0.425 (val F1=0.1417)
  Directional -> Accuracy: 0.5253, MCC: 0.0320, F1: 0.5913

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.67665 | val 0.77925
  Epoch 020 - train 0.67593 | val 0.80896
  Epoch 021 - train 0.68014 | val 0.80664
  Classification -> best τ=0.555 (val F1=0.0783)
  Directional -> Accuracy: 0.4899, MCC: -0.0960, F1: 0.3034

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67414 | val 1.04915
  Epoch 020 - train 0.66512 | val 1.12098
  Epoch 021 - train 0.67151 | val 1.14196
  Classification -> best τ=0.390 (val F1=0.2007)
  Directional -> Accuracy: 0.5606, MCC: 0.1125, F1: 0.6167

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68449 | val 0.72528
  Epoch 020 - train 0.68494 | val 0.73066
  Epoch 021 - train 0.67687 | val 0.73554
  Classification -> best τ=0.495 (val F1=0.1083)
  Directional -> Accuracy: 0.5051, MCC: -0.0172, F1: 0.0926

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67613 | val 0.72724
  Epoch 020 - train 0.67572 | val 0.73044
  Epoch 021 - train 0.67395 | val 0.73154
  Classification -> best τ=0.415 (val F1=0.1098)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.67776 | val 0.72268
  Epoch 020 - train 0.68112 | val 0.74104
  Epoch 021 - train 0.67749 | val 0.74352
  Classification -> best τ=0.525 (val F1=0.1783)
  Directional -> Accuracy: 0.5051, MCC: 0.0413, F1: 0.0392

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66822 | val 0.76591
  Epoch 020 - train 0.66543 | val 0.77913
  Epoch 021 - train 0.66405 | val 0.77973
  Classification -> best τ=0.565 (val F1=0.1253)
  Directional -> Accuracy: 0.5051, MCC: 0.0515, F1: 0.1552

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.67915 | val 0.79014
  Epoch 020 - train 0.67946 | val 0.80716
  Epoch 021 - train 0.67853 | val 0.80226
  Classification -> best τ=0.400 (val F1=0.1076)
  Directional -> Accuracy: 0.5354, MCC: -0.0430, F1: 0.6933

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.67218 | val 0.80332
  Epoch 020 - train 0.66892 | val 0.84188
  Epoch 021 - train 0.66700 | val 0.84218
  Classification -> best τ=0.365 (val F1=0.1545)
  Directional -> Accuracy: 0.5101, MCC: 0.0000, F1: 0.6756

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69463 | val 0.74412
  Epoch 020 - train 0.67924 | val 0.72529
  Epoch 030 - train 0.66265 | val 0.73157
  Classification -> best τ=0.640 (val F1=0.1113)
  Directional -> Accuracy: 0.4444, MCC: -0.0788, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.68048 | val 0.72780
  Epoch 020 - train 0.67684 | val 0.74193
  Epoch 021 - train 0.68037 | val 0.74254
  Classification -> best τ=0.450 (val F1=0.1391)
  Directional -> Accuracy: 0.5606, MCC: -0.0842, F1: 0.7071

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67734 | val 0.71753
  Epoch 020 - train 0.67902 | val 0.72287
  Epoch 021 - train 0.67517 | val 0.72181
  Classification -> best τ=0.395 (val F1=0.1243)
  Directional -> Accuracy: 0.4394, MCC: -0.0489, F1: 0.6022

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.69201 | val 0.71114
  Epoch 020 - train 0.68560 | val 0.73135
  Epoch 021 - train 0.68215 | val 0.73294
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66214 | val 0.73685
  Epoch 020 - train 0.66018 | val 0.74372
  Epoch 021 - train 0.65507 | val 0.75091
  Classification -> best τ=0.455 (val F1=0.1297)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67254 | val 0.73498
  Epoch 020 - train 0.66839 | val 0.74436
  Epoch 021 - train 0.66839 | val 0.74645
  Classification -> best τ=0.495 (val F1=0.1294)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.6931

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.68620 | val 0.78784
  Epoch 020 - train 0.67281 | val 0.81197
  Epoch 021 - train 0.67112 | val 0.81253
  Classification -> best τ=0.480 (val F1=0.0540)
  Directional -> Accuracy: 0.4343, MCC: 0.0000, F1: 0.0000

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.67266 | val 1.14340
  Epoch 020 - train 0.66704 | val 1.22697
  Epoch 021 - train 0.66930 | val 1.23695
  Classification -> best τ=0.510 (val F1=0.0790)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.67424 | val 0.76501
  Epoch 020 - train 0.67292 | val 0.77701
  Epoch 021 - train 0.66792 | val 0.77111
  Classification -> best τ=0.420 (val F1=0.0695)
  Directional -> Accuracy: 0.5455, MCC: 0.0758, F1: 0.6565

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.67902 | val 0.76789
  Epoch 020 - train 0.67172 | val 0.82061
  Epoch 021 - train 0.67175 | val 0.82039
  Classification -> best τ=0.450 (val F1=0.1013)
  Directional -> Accuracy: 0.4495, MCC: -0.1117, F1: 0.5156

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68066 | val 0.81574
  Epoch 020 - train 0.67529 | val 0.83539
  Epoch 021 - train 0.67669 | val 0.83986
  Classification -> best τ=0.320 (val F1=0.1167)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.7016

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67392 | val 0.76639
  Epoch 020 - train 0.67671 | val 0.78156
  Epoch 021 - train 0.67538 | val 0.78685
  Classification -> best τ=0.435 (val F1=0.1587)
  Directional -> Accuracy: 0.5101, MCC: 0.0000, F1: 0.6756

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67188 | val 0.68826
  Epoch 020 - train 0.67727 | val 0.69533
  Epoch 022 - train 0.67788 | val 0.69538
  Classification -> best τ=0.535 (val F1=0.2343)
  Directional -> Accuracy: 0.4798, MCC: -0.0957, F1: 0.6199

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67439 | val 0.75418
  Epoch 020 - train 0.67450 | val 0.75823
  Epoch 021 - train 0.67312 | val 0.76077
  Classification -> best τ=0.470 (val F1=0.1194)
  Directional -> Accuracy: 0.5253, MCC: 0.0523, F1: 0.5392

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66907 | val 0.83271
  Epoch 020 - train 0.67478 | val 0.84156
  Epoch 021 - train 0.67193 | val 0.83910
  Classification -> best τ=0.370 (val F1=0.0659)
  Directional -> Accuracy: 0.5909, MCC: 0.0426, F1: 0.7344

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67844 | val 0.72451
  Epoch 020 - train 0.67401 | val 0.72861
  Epoch 021 - train 0.66856 | val 0.72836
  Classification -> best τ=0.605 (val F1=0.1767)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68019 | val 0.87495
  Epoch 020 - train 0.67083 | val 0.91674
  Epoch 021 - train 0.67141 | val 0.92222
  Classification -> best τ=0.485 (val F1=0.0934)
  Directional -> Accuracy: 0.3990, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67331 | val 0.75830
  Epoch 020 - train 0.66923 | val 0.78244
  Epoch 021 - train 0.67046 | val 0.78167
  Classification -> best τ=0.530 (val F1=0.1309)
  Directional -> Accuracy: 0.4646, MCC: -0.0678, F1: 0.4854

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68068 | val 0.78056
  Epoch 020 - train 0.68058 | val 0.78641
  Epoch 021 - train 0.68055 | val 0.78744
  Classification -> best τ=0.500 (val F1=0.1159)
  Directional -> Accuracy: 0.4343, MCC: -0.0134, F1: 0.0175

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67925 | val 0.69655
  Epoch 020 - train 0.67945 | val 0.69856
  Epoch 021 - train 0.68110 | val 0.69855
  Classification -> best τ=0.475 (val F1=0.1225)
  Directional -> Accuracy: 0.5000, MCC: 0.0091, F1: 0.5075

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67774 | val 0.82203
  Epoch 020 - train 0.67549 | val 0.85129
  Epoch 021 - train 0.66434 | val 0.85352
  Classification -> best τ=0.455 (val F1=0.1008)
  Directional -> Accuracy: 0.5051, MCC: 0.0157, F1: 0.3797

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66965 | val 0.73707
  Epoch 020 - train 0.66803 | val 0.75155
  Epoch 021 - train 0.66539 | val 0.75271
  Classification -> best τ=0.570 (val F1=0.0927)
  Directional -> Accuracy: 0.5101, MCC: 0.0000, F1: 0.6756

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.67389 | val 0.82721
  Epoch 020 - train 0.67261 | val 0.86217
  Epoch 021 - train 0.66037 | val 0.86644
  Classification -> best τ=0.485 (val F1=0.1595)
  Directional -> Accuracy: 0.4141, MCC: -0.0617, F1: 0.2368

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.67583 | val 0.77413
  Epoch 020 - train 0.67433 | val 0.79112
  Epoch 021 - train 0.66678 | val 0.79017
  Classification -> best τ=0.490 (val F1=0.1351)
  Directional -> Accuracy: 0.4545, MCC: -0.0904, F1: 0.4906

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68303 | val 0.77847
  Epoch 020 - train 0.67671 | val 0.80489
  Epoch 021 - train 0.67696 | val 0.80242
  Classification -> best τ=0.480 (val F1=0.1096)
  Directional -> Accuracy: 0.5202, MCC: 0.0392, F1: 0.5366

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66723 | val 0.76272
  Epoch 020 - train 0.66543 | val 0.77514
  Epoch 021 - train 0.66821 | val 0.77515
  Classification -> best τ=0.570 (val F1=0.0297)
  Directional -> Accuracy: 0.4646, MCC: 0.0328, F1: 0.0862

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.68434 | val 0.72604
  Epoch 020 - train 0.67544 | val 0.73396
  Epoch 021 - train 0.67805 | val 0.73072
  Classification -> best τ=0.385 (val F1=0.1350)
  Directional -> Accuracy: 0.5556, MCC: 0.1089, F1: 0.6923

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66937 | val 0.74003
  Epoch 020 - train 0.66389 | val 0.76835
  Epoch 021 - train 0.66987 | val 0.77033
  Classification -> best τ=0.490 (val F1=0.1418)
  Directional -> Accuracy: 0.4949, MCC: 0.0451, F1: 0.4505

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67232 | val 0.84395
  Epoch 020 - train 0.66778 | val 0.85639
  Epoch 021 - train 0.67102 | val 0.85906
  Classification -> best τ=0.365 (val F1=0.1532)
  Directional -> Accuracy: 0.5202, MCC: 0.0595, F1: 0.4751

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67205 | val 0.85318
  Epoch 020 - train 0.67251 | val 0.90832
  Epoch 021 - train 0.67402 | val 0.90370
  Classification -> best τ=0.530 (val F1=0.0977)
  Directional -> Accuracy: 0.5101, MCC: -0.0660, F1: 0.0202

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68414 | val 0.74982
  Epoch 020 - train 0.68022 | val 0.77249
  Epoch 021 - train 0.68099 | val 0.77441
  Classification -> best τ=0.490 (val F1=0.0834)
  Directional -> Accuracy: 0.5152, MCC: 0.0000, F1: 0.6800

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.67486 | val 0.71780
  Epoch 020 - train 0.66878 | val 0.72303
  Epoch 021 - train 0.66851 | val 0.72358
  Classification -> best τ=0.480 (val F1=0.1064)
  Directional -> Accuracy: 0.5202, MCC: -0.0132, F1: 0.1593

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.67501 | val 1.13325
  Epoch 020 - train 0.67133 | val 1.12551

[I 2026-02-26 02:42:28,668] Trial 25 finished with value: 0.1267097909516379 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 4.995293352792396e-05, 'weight_decay': 3.973162402516842e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.2464801470975597, 'early_stopping_min_delta': 0.004208962760848632}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 021 - train 0.68175 | val 0.75783
  Classification -> best τ=0.475 (val F1=0.0846)
  Directional -> Accuracy: 0.4949, MCC: -0.0073, F1: 0.5614

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1267097909516379
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67829 | val 0.81195
  Epoch 020 - train 0.64800 | val 0.92107
  Epoch 021 - train 0.64091 | val 0.82838
  Classification -> best τ=0.530 (val F1=0.1054)
  Directional -> Accuracy: 0.4221, MCC: 0.0210, F1: 0.0336

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.65522 | val 1.56963
  Epoch 020 - train 0.62025 | val 1.69698
  Epoch 021 - train 0.61378 | val 1.69247
  Classification -> best τ=0.455 (val F1=0.1495)
  Directional -> Accuracy: 0.5126, MCC: 0.0338, F1: 0.6498

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65289 | val 0.72578
  Epoch 020 - train 0.62897 | val 0.75268
  Epoch 028 - train 0.61070 | val 0.81759
  Classification -> best τ=0.350 (val F1=0.1508)
  Directional -> Accuracy: 0.5323, MCC: -0.0876, F1: 0.6813

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.66839 | val 1.00865
  Epoch 020 - train 0.63039 | val 1.00042
  Epoch 021 - train 0.62693 | val 0.86681
  Classification -> best τ=0.470 (val F1=0.1131)
  Directional -> Accuracy: 0.4623, MCC: 0.0389, F1: 0.1955

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.62297 | val 1.23040
  Epoch 020 - train 0.58761 | val 1.01736
  Epoch 021 - train 0.58607 | val 1.04728
  Classification -> best τ=0.475 (val F1=0.2027)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65449 | val 0.87798
  Epoch 020 - train 0.61051 | val 0.84327
  Epoch 021 - train 0.61326 | val 0.92874
  Classification -> best τ=0.410 (val F1=0.1131)
  Directional -> Accuracy: 0.5176, MCC: -0.0135, F1: 0.6220

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66820 | val 1.00743
  Epoch 020 - train 0.62120 | val 1.26850
  Epoch 021 - train 0.62642 | val 1.25193
  Classification -> best τ=0.500 (val F1=0.1232)
  Directional -> Accuracy: 0.4874, MCC: -0.0390, F1: 0.5405

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64951 | val 0.76554
  Epoch 020 - train 0.58276 | val 0.96716
  Epoch 021 - train 0.59248 | val 1.02752
  Classification -> best τ=0.390 (val F1=0.2635)
  Directional -> Accuracy: 0.4975, MCC: 0.0320, F1: 0.5098

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64551 | val 0.82297
  Epoch 020 - train 0.59273 | val 0.81442
  Epoch 021 - train 0.61592 | val 0.81754
  Classification -> best τ=0.500 (val F1=0.1279)
  Directional -> Accuracy: 0.5088, MCC: 0.2108, F1: 0.3000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65371 | val 1.05606
  Epoch 020 - train 0.63475 | val 1.26807
  Epoch 021 - train 0.62449 | val 1.29108
  Classification -> best τ=0.625 (val F1=0.0932)
  Directional -> Accuracy: 0.5377, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.67717 | val 0.75026
  Epoch 020 - train 0.63026 | val 0.80040
  Epoch 021 - train 0.64352 | val 0.72500
  Classification -> best τ=0.565 (val F1=0.1089)
  Directional -> Accuracy: 0.4774, MCC: 0.0553, F1: 0.1475

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.65167 | val 0.74725
  Epoch 020 - train 0.62647 | val 0.74052
  Epoch 021 - train 0.61791 | val 0.73074
  Classification -> best τ=0.585 (val F1=0.1117)
  Directional -> Accuracy: 0.4221, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65996 | val 1.18274
  Epoch 020 - train 0.62336 | val 1.21190
  Epoch 021 - train 0.59954 | val 1.17378
  Classification -> best τ=0.485 (val F1=0.1346)
  Directional -> Accuracy: 0.5025, MCC: 0.0461, F1: 0.4530

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65607 | val 0.74580
  Epoch 020 - train 0.60293 | val 0.81531
  Epoch 021 - train 0.59763 | val 0.79749
  Classification -> best τ=0.480 (val F1=0.1900)
  Directional -> Accuracy: 0.5427, MCC: 0.1699, F1: 0.6784

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.67179 | val 0.78272
  Epoch 020 - train 0.64685 | val 0.80987
  Epoch 021 - train 0.63203 | val 0.99385
  Classification -> best τ=0.515 (val F1=0.0745)
  Directional -> Accuracy: 0.4673, MCC: -0.0166, F1: 0.1017

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.67543 | val 1.26839
  Epoch 020 - train 0.61831 | val 1.22404
  Epoch 021 - train 0.61431 | val 1.32884
  Classification -> best τ=0.530 (val F1=0.1266)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.65587 | val 0.70097
  Epoch 020 - train 0.63914 | val 0.75197
  Epoch 023 - train 0.61946 | val 0.80314
  Classification -> best τ=0.330 (val F1=0.1183)
  Directional -> Accuracy: 0.5578, MCC: 0.0000, F1: 0.7161

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63554 | val 2.13005
  Epoch 020 - train 0.61136 | val 2.10581
  Epoch 021 - train 0.60101 | val 2.27353
  Classification -> best τ=0.475 (val F1=0.1749)
  Directional -> Accuracy: 0.4824, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64869 | val 0.75095
  Epoch 020 - train 0.62630 | val 1.00571
  Epoch 021 - train 0.62029 | val 1.01246
  Classification -> best τ=0.500 (val F1=0.1391)
  Directional -> Accuracy: 0.5025, MCC: 0.0122, F1: 0.2326

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63363 | val 1.00176
  Epoch 020 - train 0.60901 | val 1.06962
  Epoch 021 - train 0.58908 | val 1.05524
  Classification -> best τ=0.445 (val F1=0.0752)
  Directional -> Accuracy: 0.5578, MCC: 0.0783, F1: 0.6901

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.65210 | val 0.84232
  Epoch 020 - train 0.61447 | val 0.91130
  Epoch 021 - train 0.61339 | val 0.90335
  Classification -> best τ=0.430 (val F1=0.0995)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.6599

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.66996 | val 0.79350
  Epoch 020 - train 0.65130 | val 0.82440
  Epoch 021 - train 0.64758 | val 0.79446
  Classification -> best τ=0.455 (val F1=0.1580)
  Directional -> Accuracy: 0.4372, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65270 | val 0.89836
  Epoch 020 - train 0.62028 | val 0.81268
  Epoch 021 - train 0.61537 | val 0.80816
  Classification -> best τ=0.585 (val F1=0.1159)
  Directional -> Accuracy: 0.4573, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.64251 | val 0.96579
  Epoch 020 - train 0.60162 | val 1.01541
  Epoch 021 - train 0.57890 | val 0.97163
  Classification -> best τ=0.550 (val F1=0.0897)
  Directional -> Accuracy: 0.6080, MCC: 0.0000, F1: 0.0000

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67042 | val 0.87441
  Epoch 020 - train 0.62081 | val 0.97849
  Epoch 021 - train 0.61484 | val 1.00708
  Classification -> best τ=0.375 (val F1=0.1649)
  Directional -> Accuracy: 0.5528, MCC: 0.0955, F1: 0.6337

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65725 | val 0.71491
  Epoch 020 - train 0.61581 | val 0.76656
  Epoch 021 - train 0.60394 | val 0.75889
  Classification -> best τ=0.495 (val F1=0.1368)
  Directional -> Accuracy: 0.5628, MCC: 0.1231, F1: 0.5085

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64303 | val 1.39098
  Epoch 020 - train 0.60009 | val 2.15283
  Epoch 021 - train 0.60055 | val 1.90803
  Classification -> best τ=0.495 (val F1=0.1633)
  Directional -> Accuracy: 0.4573, MCC: -0.0123, F1: 0.0357

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.67584 | val 1.00101
  Epoch 020 - train 0.62530 | val 1.31494
  Epoch 021 - train 0.62312 | val 1.51820
  Classification -> best τ=0.440 (val F1=0.1035)
  Directional -> Accuracy: 0.5126, MCC: 0.1231, F1: 0.6712

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66027 | val 1.79216
  Epoch 020 - train 0.63929 | val 1.77456
  Epoch 021 - train 0.62697 | val 2.56586
  Classification -> best τ=0.630 (val F1=0.1211)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.66234 | val 1.35302
  Epoch 020 - train 0.61422 | val 1.08811
  Epoch 024 - train 0.60254 | val 1.06248
  Classification -> best τ=0.455 (val F1=0.1761)
  Directional -> Accuracy: 0.4824, MCC: 0.0580, F1: 0.1890

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.66232 | val 2.06693
  Epoch 020 - train 0.60721 | val 1.92383
  Epoch 021 - train 0.59698 | val 1.92841
  Classification -> best τ=0.470 (val F1=0.1613)
  Directional -> Accuracy: 0.4925, MCC: -0.0078, F1: 0.2937

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67153 | val 0.71712
  Epoch 020 - train 0.63492 | val 0.70696
  Epoch 021 - train 0.64030 | val 0.70296
  Classification -> best τ=0.485 (val F1=0.1109)
  Directional -> Accuracy: 0.5528, MCC: 0.0000, F1: 0.7120

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.67158 | val 0.81200
  Epoch 020 - train 0.64043 | val 0.78287
  Epoch 021 - train 0.63262 | val 0.83798
  Classification -> best τ=0.425 (val F1=0.1459)
  Directional -> Accuracy: 0.4171, MCC: 0.0343, F1: 0.1471

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66932 | val 0.73585
  Epoch 020 - train 0.62363 | val 0.81109
  Epoch 021 - train 0.63149 | val 0.79926
  Classification -> best τ=0.590 (val F1=0.0932)
  Directional -> Accuracy: 0.5528, MCC: 0.0532, F1: 0.3101

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.60014 | val 0.99530
  Epoch 020 - train 0.57091 | val 0.85726
  Epoch 021 - train 0.58289 | val 0.94276
  Classification -> best τ=0.455 (val F1=0.0063)
  Directional -> Accuracy: 0.5532, MCC: 0.1997, F1: 0.6769

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64562 | val 0.87169
  Epoch 020 - train 0.60058 | val 0.96565
  Epoch 021 - train 0.60118 | val 1.11731
  Classification -> best τ=0.520 (val F1=0.1039)
  Directional -> Accuracy: 0.4623, MCC: -0.0014, F1: 0.3743

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65927 | val 0.96689
  Epoch 020 - train 0.62892 | val 0.93593
  Epoch 021 - train 0.61377 | val 0.93441
  Classification -> best τ=0.590 (val F1=0.1679)
  Directional -> Accuracy: 0.4673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.65729 | val 0.85273
  Epoch 020 - train 0.61462 | val 0.88226
  Epoch 023 - train 0.62130 | val 1.03188
  Classification -> best τ=0.455 (val F1=0.0921)
  Directional -> Accuracy: 0.5176, MCC: -0.0625, F1: 0.6496

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.65100 | val 1.24355
  Epoch 020 - train 0.60179 | val 1.33005
  Epoch 021 - train 0.60931 | val 1.18436
  Classification -> best τ=0.450 (val F1=0.0765)
  Directional -> Accuracy: 0.4372, MCC: -0.1184, F1: 0.4343

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.67529 | val 1.05417
  Epoch 020 - train 0.63050 | val 1.74183
  Epoch 021 - train 0.61341 | val 1.98510
  Classification -> best τ=0.495 (val F1=0.1249)
  Directional -> Accuracy: 0.4774, MCC: -0.0043, F1: 0.1875

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.64769 | val 1.08111
  Epoch 020 - train 0.60163 | val 1.28672
  Epoch 021 - train 0.59907 | val 1.24454
  Classification -> best τ=0.565 (val F1=0.0978)
  Directional -> Accuracy: 0.5025, MCC: 0.0297, F1: 0.3265

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66033 | val 0.86385
  Epoch 020 - train 0.62930 | val 0.89380
  Epoch 021 - train 0.64086 | val 1.01286
  Classification -> best τ=0.450 (val F1=0.0940)
  Directional -> Accuracy: 0.6181, MCC: 0.2272, F1: 0.7099

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66391 | val 1.22948
  Epoch 020 - train 0.61468 | val 1.46332
  Epoch 021 - train 0.61214 | val 1.62428
  Classification -> best τ=0.380 (val F1=0.1291)
  Directional -> Accuracy: 0.4874, MCC: -0.0219, F1: 0.4574

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65528 | val 1.02691
  Epoch 020 - train 0.62961 | val 1.09345
  Epoch 021 - train 0.63200 | val 1.04181
  Classification -> best τ=0.440 (val F1=0.1033)
  Directional -> Accuracy: 0.4774, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66423 | val 1.15281
  Epoch 020 - train 0.60441 | val 1.30921
  Epoch 021 - train 0.59814 | val 1.55898
  Classification -> best τ=0.370 (val F1=0.0394)
  Directional -> Accuracy: 0.5327, MCC: 0.0367, F1: 0.6265

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65048 | val 0.90738
  Epoch 020 - train 0.63136 | val 0.87786
  Epoch 021 - train 0.63526 | val 0.95597
  Classification -> best τ=0.420 (val F1=0.0827)
  Directional -> Accuracy: 0.5578, MCC: 0.0253, F1: 0.6741

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65407 | val 0.86630
  Epoch 020 - train 0.62538 | val 0.89814
  Epoch 021 - train 0.63364 | val 0.93821
  Classification -> best τ=0.530 (val F1=0.1338)
  Directional -> Accuracy: 0.4372, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64597 | val 1.56591
  Epoch 020 - train 0.60274 | val 1.75662
  Epoch 021 - train 0.60730 | val 2.88488
  Classification -> best τ=0.385 (val F1=0.1089)
  Directional -> Accuracy: 0.4422, MCC: 0.0515, F1: 0.2449

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66373 | val 0.90151
  Epoch 020 - train 0.59614 | val 1.30306
  Epoch 024 - train 0.61602 | val 1.33764
  Classification -> best τ=0.585 (val F1=0.1034)
  Directional -> Accuracy: 0.4623, MCC: -0.0714, F1: 0.5158

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66837 | val 0.77186
  Epoch 020 - train 0.64148 | val 0.83530
  Epoch 021 - train 0.62782 | val 0.83047
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5678, MCC: 0.0000, F1: 0.7244

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66384 | val 0.76298
  Epoch 020 - train 0.62821 | val 1.45683
  Epoch 021 - train 0.62401 | val 1.21408
  Classification -> best τ=0.440 (val F1=0.1389)
  Directional -> Accuracy: 0.5528, MCC: 0.0010, F1: 0.7043

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64734 | val 0.82448
  Epoch 020 - train 0.61429 | val 0.83057
  Epoch 021 - train 0.61079 | val 0.85650
  Classification -> best τ=0.475 (val F1=0.1361)
  Directional -> Accuracy: 0.4925, MCC: -0.0056, F1: 0.1920

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65868 | val 0.75916
  Epoch 020 - train 0.64291 | val 0.90372
  Epoch 021 - train 0.62831 | val 1.18726
  Classification -> best τ=0.520 (val F1=0.1061)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.64772 | val 0.86141
  Epoch 020 - train 0.60886 | val 1.15279
  Epoch 021 - train 0.59298 | val 1.21079
  Classification -> best τ=0.500 (val F1=0.1512)
  Directional -> Accuracy: 0.4070, MCC: -0.0427, F1: 0.1324

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.66837 | val 0.74045
  Epoch 020 - train 0.61802 | val 0.83739
  Epoch 021 - train 0.62272 | val 0.80880
  Classification -> best τ=0.460 (val F1=0.1263)
  Directional -> Accuracy: 0.4874, MCC: -0.0723, F1: 0.6531

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65328 | val 1.57935
  Epoch 020 - train 0.62873 | val 1.22398
  Epoch 021 - train 0.62687 | val 1.27038
  Classification -> best τ=0.630 (val F1=0.1432)
  Directional -> Accuracy: 0.4673, MCC: -0.0605, F1: 0.0536

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66013 | val 0.86076
  Epoch 020 - train 0.63933 | val 0.86083
  Epoch 021 - train 0.61781 | val 0.93950
  Classification -> best τ=0.475 (val F1=0.1023)
  Directional -> Accuracy: 0.5276, MCC: 0.1035, F1: 0.4405

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.65812 | val 1.07165
  Epoch 020 - train 0.60322 | val 0.99518
  Epoch 021 - train 0.60118 | val 0.97591
  Classification -> best τ=0.460 (val F1=0.1774)
  Directional -> Accuracy: 0.5176, MCC: 0.1157, F1: 0.2615

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65528 | val 1.10627
  Epoch 020 - train 0.59061 | val 1.85503
  Epoch 021 - train 0.59720 | val 2.18427
  Classification -> best τ=0.490 (val F1=0.1931)
  Directional -> Accuracy: 0.4171, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66371 | val 0.78964
  Epoch 020 - train 0.61463 | val 0.98266
  Epoch 021 - train 0.60174 | val 1.01431
  Classification -> best τ=0.480 (val F1=0.1588)
  Directional -> Accuracy: 0.4724, MCC: -0.0360, F1: 0.3931

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65193 | val 1.09758
  Epoch 020 - train 0.61604 | val 1.16864
  Epoch 021 - train 0.61205 | val 1.03564
  Classification -> best τ=0.625 (val F1=0.0587)
  Directional -> Accuracy: 0.5226, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66100 | val 1.33449
  Epoch 020 - train 0.61932 | val 1.04199
  Epoch 021 - train 0.60263 | val 0.97600
  Classification -> best τ=0.455 (val F1=0.1500)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.67329 | val 1.78990
  Epoch 020 - train 0.61890 | val 1.64124
  Epoch 021 - train 0.60819 | val 2.15738
  Classification -> best τ=0.375 (val F1=0.1198)
  Directional -> Accuracy: 0.5126, MCC: 0.0203, F1: 0.4757

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.65200 | val 4.24052
  Epoch 020 - train 0.58584 | val 5.23901

[I 2026-02-26 02:52:34,059] Trial 26 finished with value: 0.1272342486872744 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.0009687795718780406, 'weight_decay': 1.8631613572025742e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.559502567567129, 'early_stopping_min_delta': 0.00020985159053840295}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 021 - train 0.62136 | val 0.83274
  Classification -> best τ=0.430 (val F1=0.1514)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.6599

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1272342486872744
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64851 | val 0.93891
  Epoch 020 - train 0.65097 | val 0.92454
  Epoch 021 - train 0.64778 | val 0.91919
  Classification -> best τ=0.440 (val F1=0.1028)
  Directional -> Accuracy: 0.4300, MCC: -0.0499, F1: 0.2785

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.63425 | val 1.94605
  Epoch 020 - train 0.61277 | val 2.37327
  Epoch 021 - train 0.60652 | val 2.41118
  Classification -> best τ=0.525 (val F1=0.1242)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64547 | val 0.78036
  Epoch 020 - train 0.63691 | val 0.79174
  Epoch 021 - train 0.62743 | val 0.78907
  Classification -> best τ=0.480 (val F1=0.1387)
  Directional -> Accuracy: 0.5348, MCC: -0.0237, F1: 0.6588

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.66795 | val 0.70632
  Epoch 020 - train 0.64624 | val 0.71683
  Epoch 021 - train 0.64113 | val 0.72469
  Classification -> best τ=0.550 (val F1=0.1456)
  Directional -> Accuracy: 0.4150, MCC: -0.1214, F1: 0.1583

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.63402 | val 0.99159
  Epoch 020 - train 0.61536 | val 1.28907
  Epoch 021 - train 0.61269 | val 1.32778
  Classification -> best τ=0.475 (val F1=0.1393)
  Directional -> Accuracy: 0.4766, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64364 | val 0.90586
  Epoch 020 - train 0.63897 | val 1.04030
  Epoch 021 - train 0.62911 | val 1.01285
  Classification -> best τ=0.635 (val F1=0.0851)
  Directional -> Accuracy: 0.4450, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66563 | val 1.75042
  Epoch 020 - train 0.64356 | val 2.17999
  Epoch 021 - train 0.65585 | val 2.36400
  Classification -> best τ=0.530 (val F1=0.1391)
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64893 | val 0.91004
  Epoch 020 - train 0.63085 | val 1.01439
  Epoch 021 - train 0.63319 | val 1.02035
  Classification -> best τ=0.420 (val F1=0.2766)
  Directional -> Accuracy: 0.5450, MCC: 0.0626, F1: 0.6128

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63334 | val 1.96562
  Epoch 020 - train 0.61911 | val 2.10641
  Epoch 021 - train 0.62199 | val 2.10377
  Classification -> best τ=0.505 (val F1=0.1087)
  Directional -> Accuracy: 0.4174, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65023 | val 1.19241
  Epoch 020 - train 0.63943 | val 1.26003
  Epoch 021 - train 0.64363 | val 1.28637
  Classification -> best τ=0.615 (val F1=0.0873)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.66474 | val 0.78565
  Epoch 020 - train 0.63166 | val 0.82844
  Epoch 021 - train 0.62884 | val 0.84332
  Classification -> best τ=0.445 (val F1=0.1209)
  Directional -> Accuracy: 0.5600, MCC: 0.0933, F1: 0.6562

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.65977 | val 0.72902
  Epoch 020 - train 0.64984 | val 0.77779
  Epoch 021 - train 0.64023 | val 0.77376
  Classification -> best τ=0.550 (val F1=0.1036)
  Directional -> Accuracy: 0.4250, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64182 | val 1.09522
  Epoch 020 - train 0.63557 | val 1.13905
  Epoch 021 - train 0.62890 | val 1.16520
  Classification -> best τ=0.400 (val F1=0.1061)
  Directional -> Accuracy: 0.5250, MCC: 0.0061, F1: 0.6185

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63944 | val 0.81434
  Epoch 020 - train 0.62527 | val 1.05742
  Epoch 021 - train 0.61802 | val 1.08254
  Classification -> best τ=0.550 (val F1=0.1559)
  Directional -> Accuracy: 0.5200, MCC: 0.0635, F1: 0.1429

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.68061 | val 0.97123
  Epoch 020 - train 0.65744 | val 1.03750
  Epoch 021 - train 0.65647 | val 1.04215
  Classification -> best τ=0.415 (val F1=0.0918)
  Directional -> Accuracy: 0.4600, MCC: -0.1029, F1: 0.5424

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.63540 | val 1.78234
  Epoch 020 - train 0.62359 | val 2.14076
  Epoch 021 - train 0.61780 | val 2.17527
  Classification -> best τ=0.480 (val F1=0.1008)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.66209 | val 0.88089
  Epoch 020 - train 0.63280 | val 1.04699
  Epoch 021 - train 0.63755 | val 1.03659
  Classification -> best τ=0.535 (val F1=0.1336)
  Directional -> Accuracy: 0.5550, MCC: 0.0226, F1: 0.7063

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63842 | val 1.21129
  Epoch 020 - train 0.62613 | val 1.19996
  Epoch 021 - train 0.61973 | val 1.17107
  Classification -> best τ=0.560 (val F1=0.1607)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65391 | val 0.82737
  Epoch 020 - train 0.64338 | val 0.83049
  Epoch 021 - train 0.63784 | val 0.84225
  Classification -> best τ=0.480 (val F1=0.2334)
  Directional -> Accuracy: 0.5200, MCC: 0.0468, F1: 0.3514

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64961 | val 0.87612
  Epoch 020 - train 0.62164 | val 0.87320
  Epoch 021 - train 0.62763 | val 0.88437
  Classification -> best τ=0.590 (val F1=0.1103)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.65063 | val 0.77193
  Epoch 020 - train 0.63377 | val 0.80093
  Epoch 021 - train 0.61725 | val 0.79871
  Classification -> best τ=0.560 (val F1=0.1559)
  Directional -> Accuracy: 0.5150, MCC: 0.0302, F1: 0.5126

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.65657 | val 2.13761
  Epoch 020 - train 0.64989 | val 2.68863
  Epoch 021 - train 0.64283 | val 2.81122
  Classification -> best τ=0.430 (val F1=0.1629)
  Directional -> Accuracy: 0.4400, MCC: 0.0253, F1: 0.0345

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65643 | val 0.81657
  Epoch 020 - train 0.64519 | val 1.25344
  Epoch 021 - train 0.64152 | val 1.27385
  Classification -> best τ=0.490 (val F1=0.1913)
  Directional -> Accuracy: 0.5050, MCC: 0.0581, F1: 0.3926

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.65915 | val 1.03859
  Epoch 020 - train 0.64025 | val 1.18779
  Epoch 021 - train 0.62982 | val 1.20731
  Classification -> best τ=0.370 (val F1=0.1868)
  Directional -> Accuracy: 0.4150, MCC: 0.0212, F1: 0.5585

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64906 | val 1.34663
  Epoch 020 - train 0.62901 | val 1.47561
  Epoch 021 - train 0.62904 | val 1.46456
  Classification -> best τ=0.425 (val F1=0.1185)
  Directional -> Accuracy: 0.5200, MCC: 0.0225, F1: 0.6250

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65352 | val 0.89417
  Epoch 020 - train 0.65057 | val 1.13324
  Epoch 021 - train 0.65411 | val 1.09955
  Classification -> best τ=0.495 (val F1=0.1523)
  Directional -> Accuracy: 0.5150, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66691 | val 0.82456
  Epoch 020 - train 0.64824 | val 0.95500
  Epoch 021 - train 0.63481 | val 0.99763
  Classification -> best τ=0.500 (val F1=0.1116)
  Directional -> Accuracy: 0.4950, MCC: 0.0589, F1: 0.2837

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.65709 | val 1.31060
  Epoch 020 - train 0.64581 | val 1.21414
  Epoch 021 - train 0.64866 | val 1.24673
  Classification -> best τ=0.450 (val F1=0.1051)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66614 | val 1.02668
  Epoch 020 - train 0.64658 | val 1.23199
  Epoch 021 - train 0.65348 | val 1.24740
  Classification -> best τ=0.565 (val F1=0.1316)
  Directional -> Accuracy: 0.5000, MCC: 0.0219, F1: 0.3056

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.66624 | val 1.03053
  Epoch 020 - train 0.64941 | val 1.31386
  Epoch 021 - train 0.64811 | val 1.26817
  Classification -> best τ=0.535 (val F1=0.2035)
  Directional -> Accuracy: 0.4450, MCC: -0.0784, F1: 0.1120

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.66556 | val 1.14541
  Epoch 020 - train 0.64721 | val 1.40624
  Epoch 021 - train 0.63820 | val 1.50483
  Classification -> best τ=0.435 (val F1=0.1579)
  Directional -> Accuracy: 0.4900, MCC: -0.0945, F1: 0.6554

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66176 | val 0.80238
  Epoch 020 - train 0.64907 | val 0.95100
  Epoch 021 - train 0.64489 | val 0.95068
  Classification -> best τ=0.440 (val F1=0.1619)
  Directional -> Accuracy: 0.4600, MCC: -0.0329, F1: 0.3165

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.67043 | val 0.94025
  Epoch 020 - train 0.64593 | val 0.97382
  Epoch 021 - train 0.66021 | val 0.92406
  Classification -> best τ=0.485 (val F1=0.1440)
  Directional -> Accuracy: 0.4650, MCC: 0.0785, F1: 0.3270

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64847 | val 1.25251
  Epoch 020 - train 0.63293 | val 1.19402
  Epoch 021 - train 0.61787 | val 1.16783
  Classification -> best τ=0.390 (val F1=0.0941)
  Directional -> Accuracy: 0.4600, MCC: 0.1105, F1: 0.6224

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.64798 | val 0.86106
  Epoch 020 - train 0.61642 | val 0.92422
  Epoch 021 - train 0.60381 | val 0.92191
  Classification -> best τ=0.540 (val F1=0.1833)
  Directional -> Accuracy: 0.5208, MCC: 0.0682, F1: 0.6567

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65037 | val 0.80963
  Epoch 020 - train 0.62948 | val 0.92941
  Epoch 021 - train 0.63449 | val 0.92112
  Classification -> best τ=0.545 (val F1=0.1932)
  Directional -> Accuracy: 0.4200, MCC: 0.0597, F1: 0.0169

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66208 | val 0.81881
  Epoch 020 - train 0.65913 | val 0.84385
  Epoch 021 - train 0.65005 | val 0.86032
  Classification -> best τ=0.525 (val F1=0.1726)
  Directional -> Accuracy: 0.4650, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.65154 | val 1.32071
  Epoch 020 - train 0.62213 | val 1.36380
  Epoch 021 - train 0.63502 | val 1.37098
  Classification -> best τ=0.425 (val F1=0.0657)
  Directional -> Accuracy: 0.5750, MCC: 0.1116, F1: 0.6586

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.65294 | val 1.42362
  Epoch 020 - train 0.64236 | val 1.65330
  Epoch 021 - train 0.63146 | val 1.62410
  Classification -> best τ=0.580 (val F1=0.0759)
  Directional -> Accuracy: 0.4550, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.65554 | val 1.18542
  Epoch 020 - train 0.63414 | val 1.27898
  Epoch 021 - train 0.62644 | val 1.28290
  Classification -> best τ=0.530 (val F1=0.1305)
  Directional -> Accuracy: 0.4700, MCC: -0.0401, F1: 0.0364

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.66482 | val 0.95180
  Epoch 020 - train 0.64390 | val 1.24950
  Epoch 021 - train 0.64936 | val 1.30148
  Classification -> best τ=0.595 (val F1=0.1445)
  Directional -> Accuracy: 0.4850, MCC: -0.0053, F1: 0.0550

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65651 | val 1.09597
  Epoch 020 - train 0.63855 | val 1.24801
  Epoch 021 - train 0.63970 | val 1.23266
  Classification -> best τ=0.440 (val F1=0.0662)
  Directional -> Accuracy: 0.5450, MCC: 0.0431, F1: 0.6851

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65207 | val 1.36642
  Epoch 020 - train 0.63873 | val 1.55118
  Epoch 021 - train 0.64027 | val 1.56491
  Classification -> best τ=0.520 (val F1=0.1184)
  Directional -> Accuracy: 0.4850, MCC: -0.0094, F1: 0.1488

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66488 | val 0.93257
  Epoch 020 - train 0.63877 | val 1.06102
  Epoch 021 - train 0.63357 | val 1.09697
  Classification -> best τ=0.510 (val F1=0.1742)
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64556 | val 2.12998
  Epoch 020 - train 0.63742 | val 2.76004
  Epoch 021 - train 0.62305 | val 2.77835
  Classification -> best τ=0.430 (val F1=0.1513)
  Directional -> Accuracy: 0.5400, MCC: 0.0424, F1: 0.6714

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65762 | val 1.13045
  Epoch 020 - train 0.64632 | val 1.22498
  Epoch 021 - train 0.65135 | val 1.31196
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5850, MCC: 0.0000, F1: 0.7382

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65679 | val 0.97174
  Epoch 020 - train 0.63608 | val 0.97794
  Epoch 021 - train 0.63930 | val 0.99703
  Classification -> best τ=0.470 (val F1=0.1706)
  Directional -> Accuracy: 0.5650, MCC: 0.0529, F1: 0.6947

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64730 | val 0.83514
  Epoch 020 - train 0.62449 | val 0.88009
  Epoch 021 - train 0.62666 | val 0.88911
  Classification -> best τ=0.505 (val F1=0.1502)
  Directional -> Accuracy: 0.5550, MCC: -0.0263, F1: 0.6855

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65360 | val 1.36067
  Epoch 020 - train 0.64293 | val 1.58759
  Epoch 021 - train 0.63375 | val 1.71521
  Classification -> best τ=0.550 (val F1=0.1393)
  Directional -> Accuracy: 0.5200, MCC: 0.0347, F1: 0.3333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65520 | val 0.88536
  Epoch 020 - train 0.63682 | val 0.81543
  Epoch 021 - train 0.62948 | val 0.84238
  Classification -> best τ=0.455 (val F1=0.0768)
  Directional -> Accuracy: 0.5600, MCC: -0.0622, F1: 0.7179

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66701 | val 0.85396
  Epoch 020 - train 0.64232 | val 1.02613
  Epoch 021 - train 0.65111 | val 1.01112
  Classification -> best τ=0.610 (val F1=0.0641)
  Directional -> Accuracy: 0.4050, MCC: -0.1594, F1: 0.0916

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65888 | val 0.85991
  Epoch 020 - train 0.63539 | val 0.98250
  Epoch 021 - train 0.64302 | val 0.97108
  Classification -> best τ=0.465 (val F1=0.1203)
  Directional -> Accuracy: 0.5200, MCC: 0.1246, F1: 0.6779

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65731 | val 0.76988
  Epoch 020 - train 0.64423 | val 0.77798
  Epoch 021 - train 0.64382 | val 0.78534
  Classification -> best τ=0.495 (val F1=0.1138)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.65696 | val 0.92374
  Epoch 020 - train 0.64805 | val 0.94992
  Epoch 021 - train 0.64205 | val 0.98263
  Classification -> best τ=0.480 (val F1=0.0894)
  Directional -> Accuracy: 0.4850, MCC: -0.0306, F1: 0.5297

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.66649 | val 0.83619
  Epoch 020 - train 0.64762 | val 1.10372
  Epoch 021 - train 0.63651 | val 1.10251
  Classification -> best τ=0.495 (val F1=0.1810)
  Directional -> Accuracy: 0.4950, MCC: 0.0000, F1: 0.6622

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67144 | val 0.98951
  Epoch 020 - train 0.65424 | val 1.01467
  Epoch 021 - train 0.65298 | val 0.99569
  Classification -> best τ=0.550 (val F1=0.0825)
  Directional -> Accuracy: 0.4600, MCC: -0.0643, F1: 0.1692

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65126 | val 0.83227
  Epoch 020 - train 0.63051 | val 0.90006
  Epoch 021 - train 0.64352 | val 0.89654
  Classification -> best τ=0.480 (val F1=0.0701)
  Directional -> Accuracy: 0.5000, MCC: 0.1043, F1: 0.2754

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.67513 | val 0.71255
  Epoch 020 - train 0.64391 | val 0.71440
  Epoch 026 - train 0.63749 | val 0.71167
  Classification -> best τ=0.570 (val F1=0.1370)
  Directional -> Accuracy: 0.4450, MCC: -0.1635, F1: 0.0177

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63864 | val 1.22814
  Epoch 020 - train 0.60799 | val 1.25773
  Epoch 021 - train 0.62107 | val 1.23756
  Classification -> best τ=0.410 (val F1=0.1768)
  Directional -> Accuracy: 0.4700, MCC: -0.0149, F1: 0.4421

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64886 | val 1.37651
  Epoch 020 - train 0.61633 | val 1.52673
  Epoch 021 - train 0.62694 | val 1.57973
  Classification -> best τ=0.445 (val F1=0.2292)
  Directional -> Accuracy: 0.5050, MCC: 0.0589, F1: 0.3172

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65858 | val 1.05648
  Epoch 020 - train 0.64379 | val 1.06948
  Epoch 021 - train 0.63701 | val 1.05873
  Classification -> best τ=0.550 (val F1=0.1120)
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65266 | val 0.78080
  Epoch 020 - train 0.64804 | val 0.80314
  Epoch 021 - train 0.62993 | val 0.77201
  Classification -> best τ=0.470 (val F1=0.2008)
  Directional -> Accuracy: 0.4850, MCC: -0.0310, F1: 0.0550

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.66142 | val 0.93085
  Epoch 020 - train 0.64758 | val 1.00791
  Epoch 021 - train 0.64318 | val 1.01107
  Classification -> best τ=0.420 (val F1=0.0644)
  Directional -> Accuracy: 0.4600, MCC: -0.0625, F1: 0.5135

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.64963 | val 1.37592
  Epoch 020 - train 0.62808 | val 1.09500

[I 2026-02-26 03:04:31,340] Trial 27 finished with value: 0.13569739190592525 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.00029348002050085247, 'weight_decay': 5.124880765469319e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.0317840701787697, 'early_stopping_min_delta': 0.00157287600888924}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 021 - train 0.63836 | val 1.41287
  Classification -> best τ=0.400 (val F1=0.1324)
  Directional -> Accuracy: 0.4850, MCC: -0.0723, F1: 0.6532

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.13569739190592525
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69378 | val 0.71772
  Epoch 016 - train 0.67892 | val 0.70203
  Classification -> best τ=0.505 (val F1=0.1001)
  Directional -> Accuracy: 0.4100, MCC: -0.0619, F1: 0.0635

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.67913 | val 0.74262
  Epoch 019 - train 0.65249 | val 0.79471
  Classification -> best τ=0.420 (val F1=0.1202)
  Directional -> Accuracy: 0.5050, MCC: 0.0411, F1: 0.0388

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67240 | val 0.70570
  Epoch 016 - train 0.66495 | val 0.70477
  Classification -> best τ=0.505 (val F1=0.1632)
  Directional -> Accuracy: 0.4064, MCC: -0.1165, F1: 0.0348

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.68328 | val 0.69936
  Epoch 018 - train 0.67098 | val 0.70619
  Classification -> best τ=0.505 (val F1=0.1109)
  Directional -> Accuracy: 0.5350, MCC: -0.0952, F1: 0.6931

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.67208 | val 0.70397
  Epoch 020 - train 0.66124 | val 0.70741
  Epoch 021 - train 0.63147 | val 0.69707
  Classification -> best τ=0.605 (val F1=0.1989)
  Directional -> Accuracy: 0.4766, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68898 | val 0.69780
  Epoch 020 - train 0.67219 | val 0.69298
  Classification -> best τ=0.405 (val F1=0.1532)
  Directional -> Accuracy: 0.5550, MCC: 0.0000, F1: 0.7138

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68512 | val 0.71828
  Epoch 020 - train 0.68025 | val 0.75595
  Epoch 021 - train 0.67953 | val 0.73845
  Classification -> best τ=0.570 (val F1=0.1209)
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68539 | val 0.68775
  Epoch 020 - train 0.66772 | val 0.70430
  Epoch 030 - train 0.64997 | val 0.71720
  Classification -> best τ=0.475 (val F1=0.2198)
  Directional -> Accuracy: 0.4050, MCC: -0.0023, F1: 0.0916

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66951 | val 0.70616
  Epoch 016 - train 0.65374 | val 0.72265
  Classification -> best τ=0.445 (val F1=0.0752)
  Directional -> Accuracy: 0.4174, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69281 | val 0.69668
  Epoch 016 - train 0.68035 | val 0.70218
  Classification -> best τ=0.515 (val F1=0.0915)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.68162 | val 0.68936
  Epoch 020 - train 0.66985 | val 0.68439
  Epoch 030 - train 0.64927 | val 0.79704
  Classification -> best τ=0.535 (val F1=0.1559)
  Directional -> Accuracy: 0.4900, MCC: 0.0170, F1: 0.3780

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.68302 | val 0.71279
  Epoch 016 - train 0.66401 | val 0.71123
  Classification -> best τ=0.550 (val F1=0.0987)
  Directional -> Accuracy: 0.4250, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.67572 | val 0.68236
  Epoch 016 - train 0.65850 | val 0.68363
  Classification -> best τ=0.595 (val F1=0.0856)
  Directional -> Accuracy: 0.4700, MCC: 0.0220, F1: 0.2838

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68717 | val 0.70240
  Epoch 020 - train 0.66850 | val 0.70857
  Classification -> best τ=0.520 (val F1=0.1559)
  Directional -> Accuracy: 0.5050, MCC: 0.0436, F1: 0.6574

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.67590 | val 0.70983
  Epoch 016 - train 0.68199 | val 0.74531
  Classification -> best τ=0.470 (val F1=0.0902)
  Directional -> Accuracy: 0.4400, MCC: -0.1083, F1: 0.3778

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.68404 | val 0.70247
  Epoch 016 - train 0.68426 | val 0.71537
  Classification -> best τ=0.480 (val F1=0.0835)
  Directional -> Accuracy: 0.4850, MCC: -0.0365, F1: 0.2797

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.69009 | val 0.69744
  Epoch 019 - train 0.67183 | val 0.71065
  Classification -> best τ=0.435 (val F1=0.1328)
  Directional -> Accuracy: 0.5550, MCC: 0.0000, F1: 0.7138

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68495 | val 0.68871
  Epoch 020 - train 0.67283 | val 0.71870
  Epoch 028 - train 0.65196 | val 0.70154
  Classification -> best τ=0.605 (val F1=0.1950)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68410 | val 0.68090
  Epoch 020 - train 0.65989 | val 0.70806
  Epoch 021 - train 0.66760 | val 0.69156
  Classification -> best τ=0.495 (val F1=0.2536)
  Directional -> Accuracy: 0.4850, MCC: -0.0816, F1: 0.0374

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67913 | val 0.71182
  Epoch 016 - train 0.68179 | val 0.70055
  Classification -> best τ=0.495 (val F1=0.1364)
  Directional -> Accuracy: 0.4500, MCC: -0.0603, F1: 0.1270

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.68346 | val 0.70041
  Epoch 016 - train 0.66404 | val 0.73505
  Classification -> best τ=0.570 (val F1=0.1258)
  Directional -> Accuracy: 0.5300, MCC: 0.0948, F1: 0.6412

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.68805 | val 0.70772
  Epoch 017 - train 0.67807 | val 0.77377
  Classification -> best τ=0.455 (val F1=0.0368)
  Directional -> Accuracy: 0.5500, MCC: -0.1083, F1: 0.7097

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67887 | val 0.72682
  Epoch 019 - train 0.66613 | val 0.78231
  Classification -> best τ=0.515 (val F1=0.1332)
  Directional -> Accuracy: 0.4550, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.68266 | val 0.72612
  Epoch 016 - train 0.66745 | val 0.71287
  Classification -> best τ=0.405 (val F1=0.0861)
  Directional -> Accuracy: 0.4200, MCC: 0.0176, F1: 0.5538

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68934 | val 0.79731
  Epoch 016 - train 0.68025 | val 0.76345
  Classification -> best τ=0.385 (val F1=0.1420)
  Directional -> Accuracy: 0.4850, MCC: 0.0154, F1: 0.0885

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67243 | val 0.68478
  Epoch 020 - train 0.65617 | val 0.68928
  Classification -> best τ=0.585 (val F1=0.1569)
  Directional -> Accuracy: 0.5400, MCC: 0.0761, F1: 0.3521

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67757 | val 0.70256
  Epoch 020 - train 0.67426 | val 0.71400
  Epoch 026 - train 0.65979 | val 0.72134
  Classification -> best τ=0.555 (val F1=0.0384)
  Directional -> Accuracy: 0.4850, MCC: 0.0497, F1: 0.2137

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.69120 | val 0.69805
  Epoch 020 - train 0.67995 | val 0.69134
  Epoch 021 - train 0.68706 | val 0.69543
  Classification -> best τ=0.525 (val F1=0.1900)
  Directional -> Accuracy: 0.5150, MCC: 0.0569, F1: 0.1565

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67376 | val 0.76228
  Epoch 016 - train 0.67940 | val 0.75134
  Classification -> best τ=0.515 (val F1=0.1264)
  Directional -> Accuracy: 0.4800, MCC: -0.0443, F1: 0.5185

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.69412 | val 0.71468
  Epoch 016 - train 0.68434 | val 0.71113
  Classification -> best τ=0.465 (val F1=0.0998)
  Directional -> Accuracy: 0.4600, MCC: -0.0401, F1: 0.2703

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.67755 | val 0.71208
  Epoch 020 - train 0.67248 | val 0.70212
  Epoch 022 - train 0.66935 | val 0.70989
  Classification -> best τ=0.575 (val F1=0.1049)
  Directional -> Accuracy: 0.4950, MCC: 0.0000, F1: 0.0000

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68204 | val 0.70492
  Epoch 016 - train 0.67691 | val 0.71982
  Classification -> best τ=0.500 (val F1=0.0159)
  Directional -> Accuracy: 0.5350, MCC: -0.0509, F1: 0.6910

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.68758 | val 0.68832
  Epoch 020 - train 0.68371 | val 0.69764
  Epoch 030 - train 0.67578 | val 0.70756
  Classification -> best τ=0.515 (val F1=0.1566)
  Directional -> Accuracy: 0.4500, MCC: -0.0375, F1: 0.4211

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69383 | val 0.70652
  Epoch 017 - train 0.67693 | val 0.71799
  Classification -> best τ=0.455 (val F1=0.0835)
  Directional -> Accuracy: 0.4350, MCC: -0.0703, F1: 0.5921

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.69492 | val 0.82654
  Epoch 019 - train 0.66297 | val 0.95409
  Classification -> best τ=0.405 (val F1=0.2036)
  Directional -> Accuracy: 0.5208, MCC: 0.0426, F1: 0.4651

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67605 | val 0.69624
  Epoch 016 - train 0.66248 | val 0.70927
  Classification -> best τ=0.540 (val F1=0.1366)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68567 | val 0.69431
  Epoch 018 - train 0.67948 | val 0.69049
  Classification -> best τ=0.550 (val F1=0.1689)
  Directional -> Accuracy: 0.4650, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.68464 | val 0.73992
  Epoch 017 - train 0.68901 | val 0.71032
  Classification -> best τ=0.515 (val F1=0.0951)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.67921 | val 0.81461
  Epoch 020 - train 0.67603 | val 0.87351
  Classification -> best τ=0.355 (val F1=0.1150)
  Directional -> Accuracy: 0.5450, MCC: 0.0000, F1: 0.7055

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.68000 | val 0.72399
  Epoch 020 - train 0.65818 | val 0.73808
  Classification -> best τ=0.535 (val F1=0.1320)
  Directional -> Accuracy: 0.5700, MCC: 0.1310, F1: 0.6475

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.68890 | val 0.71483
  Epoch 020 - train 0.67330 | val 0.71137
  Epoch 023 - train 0.67889 | val 0.73236
  Classification -> best τ=0.560 (val F1=0.0490)
  Directional -> Accuracy: 0.5100, MCC: 0.0191, F1: 0.5243

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68551 | val 0.71615
  Epoch 016 - train 0.67366 | val 0.72982
  Classification -> best τ=0.490 (val F1=0.1100)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67166 | val 0.70517
  Epoch 020 - train 0.66802 | val 0.70516
  Epoch 022 - train 0.66869 | val 0.70862
  Classification -> best τ=0.475 (val F1=0.1972)
  Directional -> Accuracy: 0.5600, MCC: 0.1302, F1: 0.6692

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68838 | val 0.68966
  Epoch 018 - train 0.68305 | val 0.70498
  Classification -> best τ=0.525 (val F1=0.2236)
  Directional -> Accuracy: 0.4850, MCC: -0.0346, F1: 0.5209

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68240 | val 0.74630
  Epoch 020 - train 0.65754 | val 0.92854
  Classification -> best τ=0.355 (val F1=0.1643)
  Directional -> Accuracy: 0.5400, MCC: 0.0480, F1: 0.6541

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68046 | val 0.69201
  Epoch 020 - train 0.67682 | val 0.69575
  Epoch 024 - train 0.67838 | val 0.70425
  Classification -> best τ=0.610 (val F1=0.0592)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68508 | val 0.69836
  Epoch 016 - train 0.68124 | val 0.70837
  Classification -> best τ=0.505 (val F1=0.1270)
  Directional -> Accuracy: 0.5750, MCC: 0.1174, F1: 0.6502

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68857 | val 0.69464
  Epoch 016 - train 0.68295 | val 0.74434
  Classification -> best τ=0.490 (val F1=0.0627)
  Directional -> Accuracy: 0.5100, MCC: -0.0390, F1: 0.6048

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68513 | val 0.69474
  Epoch 020 - train 0.67758 | val 0.71104
  Epoch 022 - train 0.67119 | val 0.70135
  Classification -> best τ=0.475 (val F1=0.1477)
  Directional -> Accuracy: 0.5100, MCC: 0.0636, F1: 0.6500

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68174 | val 0.69374
  Epoch 016 - train 0.67554 | val 0.69095
  Classification -> best τ=0.525 (val F1=0.1989)
  Directional -> Accuracy: 0.4700, MCC: 0.0013, F1: 0.3614

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69188 | val 0.68868
  Epoch 019 - train 0.66939 | val 0.69882
  Classification -> best τ=0.535 (val F1=0.0819)
  Directional -> Accuracy: 0.4200, MCC: -0.1099, F1: 0.2267

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67915 | val 0.69401
  Epoch 016 - train 0.68269 | val 0.69427
  Classification -> best τ=0.490 (val F1=0.0617)
  Directional -> Accuracy: 0.5050, MCC: 0.0000, F1: 0.6711

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68732 | val 0.71905
  Epoch 016 - train 0.68785 | val 0.72321
  Classification -> best τ=0.525 (val F1=0.1267)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.68930 | val 0.70835
  Epoch 020 - train 0.67514 | val 0.76111
  Classification -> best τ=0.485 (val F1=0.0648)
  Directional -> Accuracy: 0.4050, MCC: 0.0000, F1: 0.0000

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.68158 | val 0.72825
  Epoch 020 - train 0.68012 | val 0.74403
  Epoch 023 - train 0.67732 | val 0.74822
  Classification -> best τ=0.405 (val F1=0.0958)
  Directional -> Accuracy: 0.4900, MCC: -0.0716, F1: 0.6577

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68631 | val 0.74508
  Epoch 016 - train 0.67866 | val 0.79117
  Classification -> best τ=0.575 (val F1=0.0772)
  Directional -> Accuracy: 0.4700, MCC: -0.0401, F1: 0.0364

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67829 | val 0.70975
  Epoch 020 - train 0.65961 | val 0.71548
  Epoch 023 - train 0.65449 | val 0.74678
  Classification -> best τ=0.555 (val F1=0.1414)
  Directional -> Accuracy: 0.5000, MCC: 0.0754, F1: 0.3333

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.68199 | val 0.69371
  Epoch 020 - train 0.67608 | val 0.70884
  Epoch 021 - train 0.67204 | val 0.71007
  Classification -> best τ=0.510 (val F1=0.1833)
  Directional -> Accuracy: 0.4550, MCC: -0.1124, F1: 0.0354

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67070 | val 0.70049
  Epoch 017 - train 0.66794 | val 0.70373
  Classification -> best τ=0.525 (val F1=0.1952)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67067 | val 0.75751
  Epoch 020 - train 0.66146 | val 0.81314
  Epoch 030 - train 0.64624 | val 0.86325
  Classification -> best τ=0.435 (val F1=0.1912)
  Directional -> Accuracy: 0.5050, MCC: 0.0539, F1: 0.3356

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68566 | val 0.72596
  Epoch 016 - train 0.67711 | val 0.73440
  Classification -> best τ=0.585 (val F1=0.0940)
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68251 | val 0.72071
  Epoch 016 - train 0.66937 | val 0.74048
  Classification -> best τ=0.510 (val F1=0.0986)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.68035 | val 0.71011
  Epoch 020 - train 0.66177 | val 0.72530
  Epoch 021 - train 0.65661 | val 0.72967
  Classification -> best τ=0.480 (val F1=0.0596)
  Directional -> Accuracy: 0.5350, MCC: 0.0259, F1: 0.2051

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.68114 | val 0.72316
  Epoch 020 - train 0.66232 | val 0.81677
  Epoch 030 - train 0.63988 | val 0.91453
  Classification -> best τ=0.645 (val F1=0.0966)
  Directional -> Accuracy: 0.4400, MCC: 0.0403, F1: 0.0968

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.68364 | val 0.71196
  Epoch 020 - train 0.66603 | val 0.72002
  Epoch 023 - train 0.68144 | val 0.74737
  Classification -> best τ=0.535 (val F1=0.1559)
  Directional -> Accuracy: 0.4450, MCC: -0.0071, F1: 0.2345

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.67160 | val 0.68992
  Epoch 020 - train 0.67008 | val 0.76243
  Epoch 023 - train 0.65258 | val 0.74193
  Classification -> best τ=0.445 (val F1=0.1778)
  Directional -> Accuracy: 0.4822, MCC: 0.0027, F1: 0.5096

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.68610 | val 0.68899
  Epoch 016 - train 0.67290 | val 0.71456
  Classification -> best τ=0.600 (val F1=0.0836)
  Directional -> Accuracy: 0.4750, MCC: 0.0045, F1: 0.1176

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.66494 | val 0.75918
  Epoch 017 - train 0.66606 | val 0.75822
  Classification -> best τ=0.600 (val F1=0.1052)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68317 | val 0.71522
  Epoch 019 - train 0.67149 | val 0.84758
  Classification -> best τ=0.565 (val F1=0.2861)
  Directional -> Accuracy: 0.4300, MCC: -0.0755, F1: 0.5440

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.68500 | val 0.69653
  Epoch 016 - train 0.67384 | val 0.69643
  Classification -> best τ=0.515 (val F1=0.2225)
  Directional -> Accuracy: 0.5533, MCC: 0.1366, F1: 0.3333

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.68617 | val 0.77080

[I 2026-02-26 03:07:41,839] Trial 28 finished with value: 0.1280492198894067 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 0.0030047513269258483, 'weight_decay': 1.0217972900762815e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.5432673904660495, 'early_stopping_min_delta': 0.0029299634882029085}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 016 - train 0.67800 | val 0.68948
  Classification -> best τ=0.395 (val F1=0.1532)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.6577

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1280492198894067
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59391 | val 1.30548
  Epoch 011 - train 0.63316 | val 1.10659
  Classification -> best τ=0.475 (val F1=0.1388)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.56830 | val 2.29418
  Epoch 011 - train 0.59898 | val 1.95471
  Classification -> best τ=0.175 (val F1=0.1230)
  Directional -> Accuracy: 0.4700, MCC: -0.0781, F1: 0.2206

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60485 | val 0.99970
  Epoch 011 - train 0.61514 | val 1.08023
  Classification -> best τ=0.295 (val F1=0.1344)
  Directional -> Accuracy: 0.5294, MCC: -0.0300, F1: 0.6508

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.59023 | val 0.96216
  Epoch 011 - train 0.59726 | val 1.61413
  Classification -> best τ=0.490 (val F1=0.0776)
  Directional -> Accuracy: 0.5600, MCC: 0.0277, F1: 0.7086

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.52529 | val 1.10379
  Epoch 011 - train 0.55043 | val 1.15925
  Classification -> best τ=0.565 (val F1=0.1061)
  Directional -> Accuracy: 0.4766, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59929 | val 1.39345
  Epoch 011 - train 0.58960 | val 1.34679
  Classification -> best τ=0.290 (val F1=0.1532)
  Directional -> Accuracy: 0.5600, MCC: 0.0484, F1: 0.7105

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60783 | val 1.81903
  Epoch 011 - train 0.62815 | val 0.75005
  Classification -> best τ=0.535 (val F1=0.0919)
  Directional -> Accuracy: 0.4200, MCC: -0.1394, F1: 0.0169

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61340 | val 0.86950
  Epoch 011 - train 0.60068 | val 0.78128
  Classification -> best τ=0.450 (val F1=0.2420)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55000 | val 1.67437
  Epoch 011 - train 0.57211 | val 2.17539
  Classification -> best τ=0.445 (val F1=0.2043)
  Directional -> Accuracy: 0.4174, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60625 | val 1.26062
  Epoch 011 - train 0.57854 | val 1.17023
  Classification -> best τ=0.435 (val F1=0.1525)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.59577 | val 1.04711
  Epoch 012 - train 0.59357 | val 0.79330
  Classification -> best τ=0.635 (val F1=0.1933)
  Directional -> Accuracy: 0.4700, MCC: 0.0928, F1: 0.0364

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.60610 | val 1.24349
  Epoch 011 - train 0.63480 | val 1.14776
  Classification -> best τ=0.650 (val F1=0.1603)
  Directional -> Accuracy: 0.4250, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61620 | val 1.24386
  Epoch 018 - train 0.55055 | val 1.17086
  Classification -> best τ=0.620 (val F1=0.1371)
  Directional -> Accuracy: 0.5350, MCC: 0.0897, F1: 0.5279

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58477 | val 1.60673
  Epoch 012 - train 0.59614 | val 1.82616
  Classification -> best τ=0.460 (val F1=0.1041)
  Directional -> Accuracy: 0.5550, MCC: 0.1097, F1: 0.5189

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.64116 | val 0.95961
  Epoch 011 - train 0.62771 | val 1.41327
  Classification -> best τ=0.255 (val F1=0.0839)
  Directional -> Accuracy: 0.4650, MCC: -0.0846, F1: 0.5286

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.60490 | val 1.26115
  Epoch 011 - train 0.59278 | val 1.19425
  Classification -> best τ=0.485 (val F1=0.0884)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.63567 | val 1.05034
  Epoch 011 - train 0.58806 | val 0.85936
  Classification -> best τ=0.450 (val F1=0.0969)
  Directional -> Accuracy: 0.5600, MCC: 0.0717, F1: 0.6692

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61754 | val 1.60638
  Epoch 011 - train 0.56606 | val 2.14959
  Classification -> best τ=0.610 (val F1=0.0798)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58741 | val 0.91997
  Epoch 011 - train 0.61143 | val 1.43925
  Classification -> best τ=0.375 (val F1=0.2453)
  Directional -> Accuracy: 0.5200, MCC: 0.0468, F1: 0.3514

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60346 | val 1.03097
  Epoch 011 - train 0.60146 | val 1.31562
  Classification -> best τ=0.295 (val F1=0.1046)
  Directional -> Accuracy: 0.5150, MCC: -0.0168, F1: 0.6312

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.64016 | val 0.83693
  Epoch 011 - train 0.60365 | val 1.06275
  Classification -> best τ=0.445 (val F1=0.1256)
  Directional -> Accuracy: 0.4950, MCC: 0.0387, F1: 0.6576

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.63907 | val 1.99161
  Epoch 011 - train 0.60589 | val 2.44075
  Classification -> best τ=0.285 (val F1=0.1370)
  Directional -> Accuracy: 0.4600, MCC: 0.0790, F1: 0.1290

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62834 | val 1.39409
  Epoch 011 - train 0.61106 | val 1.44812
  Classification -> best τ=0.655 (val F1=0.1150)
  Directional -> Accuracy: 0.4550, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.60904 | val 1.40327
  Epoch 011 - train 0.59058 | val 1.94694
  Classification -> best τ=0.300 (val F1=0.1284)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.5663

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60174 | val 0.88801
  Epoch 011 - train 0.60825 | val 1.20478
  Classification -> best τ=0.345 (val F1=0.1223)
  Directional -> Accuracy: 0.5250, MCC: 0.0530, F1: 0.5178

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62921 | val 1.41747
  Epoch 011 - train 0.60010 | val 1.66013
  Classification -> best τ=0.560 (val F1=0.1267)
  Directional -> Accuracy: 0.5150, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60927 | val 2.77351
  Epoch 011 - train 0.59808 | val 2.96331
  Classification -> best τ=0.715 (val F1=0.1279)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.63329 | val 1.36811
  Epoch 011 - train 0.61906 | val 1.65204
  Classification -> best τ=0.400 (val F1=0.1662)
  Directional -> Accuracy: 0.5400, MCC: 0.0820, F1: 0.4831

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63565 | val 1.56297
  Epoch 011 - train 0.60113 | val 2.35758
  Classification -> best τ=0.765 (val F1=0.0753)
  Directional -> Accuracy: 0.5000, MCC: 0.1198, F1: 0.0566

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.58959 | val 1.31840
  Epoch 011 - train 0.59852 | val 1.14593
  Classification -> best τ=0.655 (val F1=0.0918)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.58219 | val 2.23623
  Epoch 011 - train 0.57946 | val 3.28248
  Classification -> best τ=0.455 (val F1=0.1727)
  Directional -> Accuracy: 0.4850, MCC: -0.1015, F1: 0.0000

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62918 | val 1.99996
  Epoch 011 - train 0.67167 | val 1.26509
  Classification -> best τ=0.375 (val F1=0.1319)
  Directional -> Accuracy: 0.5450, MCC: -0.0289, F1: 0.7036

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.64701 | val 1.43128
  Epoch 014 - train 0.62264 | val 1.24278
  Classification -> best τ=0.545 (val F1=0.1444)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62412 | val 0.92955
  Epoch 011 - train 0.57756 | val 1.66898
  Classification -> best τ=0.660 (val F1=0.1585)
  Directional -> Accuracy: 0.5450, MCC: 0.0345, F1: 0.3158

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.42509 | val 1.50610
  Epoch 012 - train 0.38914 | val 1.60373
  Classification -> best τ=0.365 (val F1=0.2036)
  Directional -> Accuracy: 0.4792, MCC: -0.1459, F1: 0.6479

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56769 | val 1.41085
  Epoch 011 - train 0.60008 | val 0.78864
  Classification -> best τ=0.320 (val F1=0.1246)
  Directional -> Accuracy: 0.5500, MCC: -0.0568, F1: 0.6959

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59776 | val 4.31663
  Epoch 011 - train 0.60813 | val 3.18442
  Classification -> best τ=0.395 (val F1=0.1795)
  Directional -> Accuracy: 0.4650, MCC: -0.0071, F1: 0.0183

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.60545 | val 1.94027
  Epoch 011 - train 0.61357 | val 1.01581
  Classification -> best τ=0.370 (val F1=0.0929)
  Directional -> Accuracy: 0.5700, MCC: 0.0737, F1: 0.6906

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.56568 | val 1.63680
  Epoch 011 - train 0.57754 | val 2.54046
  Classification -> best τ=0.290 (val F1=0.1413)
  Directional -> Accuracy: 0.5450, MCC: 0.0000, F1: 0.7055

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.61323 | val 2.26465
  Epoch 012 - train 0.59015 | val 2.03980
  Classification -> best τ=0.845 (val F1=0.1882)
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.0000

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.60012 | val 2.37609
  Epoch 013 - train 0.58170 | val 1.69819
  Classification -> best τ=0.805 (val F1=0.1222)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60299 | val 0.97202
  Epoch 014 - train 0.58335 | val 1.09204
  Classification -> best τ=0.890 (val F1=0.1398)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62056 | val 1.17759
  Epoch 011 - train 0.62212 | val 1.56013
  Classification -> best τ=0.390 (val F1=0.1121)
  Directional -> Accuracy: 0.5150, MCC: 0.0155, F1: 0.6284

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62776 | val 1.32162
  Epoch 011 - train 0.63523 | val 1.33777
  Classification -> best τ=0.370 (val F1=0.0894)
  Directional -> Accuracy: 0.4900, MCC: 0.0966, F1: 0.0377

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54430 | val 3.11379
  Epoch 011 - train 0.54911 | val 3.70590
  Classification -> best τ=0.255 (val F1=0.0920)
  Directional -> Accuracy: 0.5150, MCC: 0.0095, F1: 0.5907

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66493 | val 0.89824
  Epoch 011 - train 0.63413 | val 0.93479
  Classification -> best τ=0.320 (val F1=0.1364)
  Directional -> Accuracy: 0.5850, MCC: 0.0000, F1: 0.7382

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61411 | val 1.35732
  Epoch 012 - train 0.59671 | val 1.32825
  Classification -> best τ=0.695 (val F1=0.0882)
  Directional -> Accuracy: 0.4450, MCC: 0.0882, F1: 0.0348

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57571 | val 1.31196
  Epoch 011 - train 0.59265 | val 1.30238
  Classification -> best τ=0.360 (val F1=0.1297)
  Directional -> Accuracy: 0.5000, MCC: -0.0151, F1: 0.5614

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64777 | val 1.36684
  Epoch 011 - train 0.62837 | val 1.25362
  Classification -> best τ=0.495 (val F1=0.1094)
  Directional -> Accuracy: 0.5150, MCC: 0.0224, F1: 0.2362

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60709 | val 0.77873
  Epoch 012 - train 0.59308 | val 0.81657
  Classification -> best τ=0.545 (val F1=0.1758)
  Directional -> Accuracy: 0.4500, MCC: 0.0759, F1: 0.0678

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63412 | val 0.85285
  Epoch 016 - train 0.56240 | val 1.80042
  Classification -> best τ=0.485 (val F1=0.1307)
  Directional -> Accuracy: 0.5400, MCC: 0.1330, F1: 0.4773

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58962 | val 1.56646
  Epoch 011 - train 0.65526 | val 1.34810
  Classification -> best τ=0.165 (val F1=0.1246)
  Directional -> Accuracy: 0.5300, MCC: 0.0820, F1: 0.6619

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63057 | val 0.90549
  Epoch 011 - train 0.60581 | val 1.32569
  Classification -> best τ=0.270 (val F1=0.1297)
  Directional -> Accuracy: 0.5150, MCC: 0.0082, F1: 0.6644

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.59396 | val 2.52781
  Epoch 011 - train 0.61505 | val 1.02422
  Classification -> best τ=0.400 (val F1=0.0534)
  Directional -> Accuracy: 0.4150, MCC: 0.0023, F1: 0.0930

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.59949 | val 2.41952
  Epoch 011 - train 0.60372 | val 1.74516
  Classification -> best τ=0.380 (val F1=0.1645)
  Directional -> Accuracy: 0.4900, MCC: -0.0336, F1: 0.6531

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.62281 | val 1.10534
  Epoch 011 - train 0.60540 | val 1.47611
  Classification -> best τ=0.515 (val F1=0.1272)
  Directional -> Accuracy: 0.5450, MCC: 0.0753, F1: 0.6592

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61440 | val 1.08863
  Epoch 011 - train 0.61729 | val 1.13960
  Classification -> best τ=0.310 (val F1=0.0714)
  Directional -> Accuracy: 0.5800, MCC: 0.1457, F1: 0.7162

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.64832 | val 0.97930
  Epoch 011 - train 0.59229 | val 2.18917
  Classification -> best τ=0.635 (val F1=0.1176)
  Directional -> Accuracy: 0.4700, MCC: -0.0745, F1: 0.0000

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61999 | val 1.00831
  Epoch 012 - train 0.57551 | val 1.06426
  Classification -> best τ=0.635 (val F1=0.1822)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58957 | val 0.74217
  Epoch 019 - train 0.49979 | val 0.87894
  Classification -> best τ=0.545 (val F1=0.1294)
  Directional -> Accuracy: 0.5100, MCC: 0.0761, F1: 0.3099

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59937 | val 0.93789
  Epoch 011 - train 0.56626 | val 1.16355
  Classification -> best τ=0.555 (val F1=0.1523)
  Directional -> Accuracy: 0.5050, MCC: 0.0070, F1: 0.4762

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66420 | val 1.04257
  Epoch 011 - train 0.61002 | val 1.36251
  Classification -> best τ=0.190 (val F1=0.1667)
  Directional -> Accuracy: 0.4700, MCC: -0.0839, F1: 0.0862

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.61623 | val 0.86389
  Epoch 012 - train 0.61918 | val 1.05744
  Classification -> best τ=0.505 (val F1=0.0627)
  Directional -> Accuracy: 0.5350, MCC: 0.0143, F1: 0.0792

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.58962 | val 2.23483
  Epoch 015 - train 0.49004 | val 1.16433
  Classification -> best τ=0.495 (val F1=0.1459)
  Directional -> Accuracy: 0.4800, MCC: 0.1029, F1: 0.2676

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.60628 | val 1.97900
  Epoch 011 - train 0.57676 | val 1.57880
  Classification -> best τ=0.370 (val F1=0.1576)
  Directional -> Accuracy: 0.4550, MCC: 0.0316, F1: 0.2270

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.60063 | val 0.83761
  Epoch 013 - train 0.53598 | val 0.77646
  Classification -> best τ=0.485 (val F1=0.1962)
  Directional -> Accuracy: 0.4569, MCC: 0.0014, F1: 0.5560

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.62634 | val 0.74769
  Epoch 011 - train 0.61722 | val 0.78771
  Classification -> best τ=0.510 (val F1=0.1410)
  Directional -> Accuracy: 0.4600, MCC: -0.1067, F1: 0.0000

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.63618 | val 1.08006
  Epoch 011 - train 0.62813 | val 1.30471
  Classification -> best τ=0.600 (val F1=0.1346)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57479 | val 1.76062
  Epoch 011 - train 0.59769 | val 0.98326
  Classification -> best τ=0.400 (val F1=0.1379)
  Directional -> Accuracy: 0.4750, MCC: 0.0693, F1: 0.5977

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.57205 | val 1.20702
  Epoch 011 - train 0.56199 | val 1.30853
  Classification -> best τ=0.490 (val F1=0.1039)
  Directional -> Accuracy: 0.5279, MCC: 0.0852, F1: 0.6517

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.60544 | val 2.25987
  Epoch 011 - train 0.60411 | val 2.55104
  Classification -> best τ=0.405 (val F1=0.1391)
  Directional -> Accuracy: 0.5250, MCC: 0.0639, F1: 0.6801

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.58833 | val 1.66136
  Epoch 013 - train 0.53117 | val 0.91571
  Classification -> best τ=0.240 (val F1=0.1868)
  Directional -> Accuracy: 0.4500, MCC: -0.0954, F1: 0.3678

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.58843 | val 5.64319
  Epoch 011 - train 0.62498 | val 4.02532
  Classification -> best τ=0.765 (val F1=0.0792)
  Directional -> Accuracy: 0.5450, MCC: 0.0000, F1: 0.0000

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.58889 | val 1.78277
  Epoch 011 - train 0.60640 | val 1.38387
  Classification -> best τ=0.540 (val F1=0.0853)
  Directional -> Accuracy: 0.4700, MCC: 0.0000, F1: 0.0000

[75/88] Processing T...


[I 2026-02-26 03:10:10,296] Trial 29 finished with value: 0.13261007002920558 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 0.0055622385761621845, 'weight_decay': 2.085448961737044e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.9726892580895441, 'early_stopping_min_delta': 0.0046264869954119135}. Best is trial 8 with value: 0.15238950933016568.

  Classification -> best τ=0.365 (val F1=0.1878)
  Directional -> Accuracy: 0.5000, MCC: 0.0310, F1: 0.6454

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.13261007002920558
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68060 | val 0.76885
  Epoch 016 - train 0.67921 | val 0.79296
  Classification -> best τ=0.410 (val F1=0.0843)
  Directional -> Accuracy: 0.4874, MCC: 0.0578, F1: 0.4000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.67049 | val 0.98392
  Epoch 016 - train 0.65893 | val 1.03464
  Classification -> best τ=0.335 (val F1=0.1576)
  Directional -> Accuracy: 0.5377, MCC: 0.1021, F1: 0.3235

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65573 | val 0.73611
  Epoch 016 - train 0.66284 | val 0.74877
  Classification -> best τ=0.530 (val F1=0.1851)
  Directional -> Accuracy: 0.4032, MCC: -0.1327, F1: 0.0513

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.67866 | val 0.72775
  Epoch 016 - train 0.66966 | val 0.73112
  Classification -> best τ=0.470 (val F1=0.1029)
  Directional -> Accuracy: 0.4573, MCC: 0.0307, F1: 0.1692

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.65716 | val 0.68697
  Epoch 020 - train 0.63246 | val 0.69890
  Classification -> best τ=0.690 (val F1=0.1747)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67450 | val 0.76908
  Epoch 016 - train 0.66299 | val 0.77087
  Classification -> best τ=0.365 (val F1=0.1087)
  Directional -> Accuracy: 0.5528, MCC: 0.0000, F1: 0.7120

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67325 | val 0.84005
  Epoch 016 - train 0.66892 | val 0.87757
  Classification -> best τ=0.385 (val F1=0.1468)
  Directional -> Accuracy: 0.5678, MCC: 0.0751, F1: 0.6972

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65219 | val 0.67307
  Epoch 020 - train 0.61128 | val 0.74479
  Classification -> best τ=0.410 (val F1=0.2684)
  Directional -> Accuracy: 0.3920, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67554 | val 0.76765
  Epoch 016 - train 0.65831 | val 0.77883
  Classification -> best τ=0.450 (val F1=0.0877)
  Directional -> Accuracy: 0.4561, MCC: -0.0022, F1: 0.3261

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67282 | val 0.77212
  Epoch 016 - train 0.67263 | val 0.83079
  Classification -> best τ=0.595 (val F1=0.0922)
  Directional -> Accuracy: 0.5377, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.67198 | val 0.68975
  Epoch 016 - train 0.66126 | val 0.69092
  Classification -> best τ=0.480 (val F1=0.1334)
  Directional -> Accuracy: 0.5377, MCC: 0.0388, F1: 0.6406

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.66052 | val 0.70805
  Epoch 016 - train 0.65313 | val 0.71396
  Classification -> best τ=0.670 (val F1=0.1037)
  Directional -> Accuracy: 0.4221, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66878 | val 0.73480
  Epoch 016 - train 0.65636 | val 0.75684
  Classification -> best τ=0.480 (val F1=0.0987)
  Directional -> Accuracy: 0.5126, MCC: 0.0209, F1: 0.5488

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65918 | val 0.76849
  Epoch 016 - train 0.65186 | val 0.77212
  Classification -> best τ=0.595 (val F1=0.2003)
  Directional -> Accuracy: 0.5025, MCC: 0.0031, F1: 0.3613

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.68134 | val 0.72147
  Epoch 016 - train 0.68108 | val 0.74978
  Classification -> best τ=0.455 (val F1=0.0894)
  Directional -> Accuracy: 0.4623, MCC: -0.0450, F1: 0.2621

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.66844 | val 0.74441
  Epoch 016 - train 0.65924 | val 0.74804
  Classification -> best τ=0.570 (val F1=0.1653)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.66669 | val 0.74547
  Epoch 016 - train 0.66618 | val 0.77864
  Classification -> best τ=0.485 (val F1=0.1308)
  Directional -> Accuracy: 0.5477, MCC: -0.0195, F1: 0.7000

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65832 | val 0.99184
  Epoch 016 - train 0.65556 | val 1.01209
  Classification -> best τ=0.690 (val F1=0.1272)
  Directional -> Accuracy: 0.4824, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67084 | val 0.66679
  Epoch 020 - train 0.67119 | val 0.68181
  Classification -> best τ=0.555 (val F1=0.2866)
  Directional -> Accuracy: 0.4975, MCC: -0.0005, F1: 0.0196

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66043 | val 0.75206
  Epoch 016 - train 0.65437 | val 0.76338
  Classification -> best τ=0.550 (val F1=0.1150)
  Directional -> Accuracy: 0.4673, MCC: -0.0141, F1: 0.2639

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.66587 | val 0.72354
  Epoch 016 - train 0.66995 | val 0.73243
  Classification -> best τ=0.525 (val F1=0.1504)
  Directional -> Accuracy: 0.4975, MCC: 0.0244, F1: 0.6552

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.67739 | val 0.77407
  Epoch 016 - train 0.67168 | val 0.78649
  Classification -> best τ=0.550 (val F1=0.1355)
  Directional -> Accuracy: 0.4372, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66928 | val 0.72792
  Epoch 016 - train 0.66615 | val 0.72425
  Classification -> best τ=0.440 (val F1=0.1197)
  Directional -> Accuracy: 0.5176, MCC: 0.0572, F1: 0.4783

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.66102 | val 0.82275
  Epoch 016 - train 0.65919 | val 0.82188
  Classification -> best τ=0.215 (val F1=0.1268)
  Directional -> Accuracy: 0.4121, MCC: 0.0196, F1: 0.5551

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68460 | val 0.79865
  Epoch 016 - train 0.66948 | val 0.84367
  Classification -> best τ=0.430 (val F1=0.0848)
  Directional -> Accuracy: 0.5276, MCC: 0.0355, F1: 0.6412

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67065 | val 0.71372
  Epoch 016 - train 0.65096 | val 0.71997
  Classification -> best τ=0.570 (val F1=0.1383)
  Directional -> Accuracy: 0.5126, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66376 | val 1.35910
  Epoch 016 - train 0.64550 | val 1.57801
  Classification -> best τ=0.520 (val F1=0.1180)
  Directional -> Accuracy: 0.5276, MCC: 0.1487, F1: 0.3380

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.68308 | val 0.84613
  Epoch 016 - train 0.67079 | val 0.83729
  Classification -> best τ=0.665 (val F1=0.0934)
  Directional -> Accuracy: 0.5025, MCC: 0.0000, F1: 0.0000

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67163 | val 0.84892
  Epoch 016 - train 0.66516 | val 0.91448
  Classification -> best τ=0.570 (val F1=0.1195)
  Directional -> Accuracy: 0.5025, MCC: 0.0341, F1: 0.2326

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.67791 | val 0.75522
  Epoch 016 - train 0.67102 | val 0.74408
  Classification -> best τ=0.430 (val F1=0.0908)
  Directional -> Accuracy: 0.5377, MCC: 0.0446, F1: 0.6290

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.68481 | val 0.74023
  Epoch 016 - train 0.66828 | val 0.75293
  Classification -> best τ=0.440 (val F1=0.1560)
  Directional -> Accuracy: 0.4925, MCC: -0.0493, F1: 0.6431

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67734 | val 0.71892
  Epoch 016 - train 0.67839 | val 0.73356
  Classification -> best τ=0.515 (val F1=0.1184)
  Directional -> Accuracy: 0.5176, MCC: 0.0480, F1: 0.5152

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.67507 | val 0.71010
  Epoch 016 - train 0.67533 | val 0.71469
  Classification -> best τ=0.460 (val F1=0.1353)
  Directional -> Accuracy: 0.4523, MCC: 0.0431, F1: 0.3230

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67546 | val 0.84010
  Epoch 016 - train 0.67586 | val 0.90252
  Classification -> best τ=0.545 (val F1=0.0714)
  Directional -> Accuracy: 0.5528, MCC: 0.0269, F1: 0.1188

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.66713 | val 1.08861
  Epoch 016 - train 0.67325 | val 1.26145
  Classification -> best τ=0.495 (val F1=0.1800)
  Directional -> Accuracy: 0.3830, MCC: -0.2808, F1: 0.5246

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65788 | val 0.72223
  Epoch 016 - train 0.66002 | val 0.71344
  Classification -> best τ=0.520 (val F1=0.1924)
  Directional -> Accuracy: 0.4372, MCC: -0.0047, F1: 0.2113

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66292 | val 0.74618
  Epoch 016 - train 0.66305 | val 0.77475
  Classification -> best τ=0.530 (val F1=0.2036)
  Directional -> Accuracy: 0.4673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.66821 | val 0.84496
  Epoch 016 - train 0.66528 | val 0.91459
  Classification -> best τ=0.375 (val F1=0.0895)
  Directional -> Accuracy: 0.5176, MCC: 0.0747, F1: 0.4839

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.67864 | val 0.82193
  Epoch 016 - train 0.66551 | val 0.83623
  Classification -> best τ=0.345 (val F1=0.1143)
  Directional -> Accuracy: 0.5427, MCC: 0.0000, F1: 0.7036

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.67245 | val 0.87121
  Epoch 016 - train 0.66608 | val 0.97468
  Classification -> best τ=0.510 (val F1=0.1316)
  Directional -> Accuracy: 0.4623, MCC: -0.0677, F1: 0.4339

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.67699 | val 0.91017
  Epoch 016 - train 0.68176 | val 0.96652
  Classification -> best τ=0.635 (val F1=0.2255)
  Directional -> Accuracy: 0.5075, MCC: 0.1297, F1: 0.1091

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66950 | val 0.79273
  Epoch 016 - train 0.66367 | val 0.82857
  Classification -> best τ=0.445 (val F1=0.0907)
  Directional -> Accuracy: 0.5528, MCC: 0.0650, F1: 0.6764

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67644 | val 0.85184
  Epoch 016 - train 0.66748 | val 0.90713
  Classification -> best τ=0.430 (val F1=0.1629)
  Directional -> Accuracy: 0.5327, MCC: 0.0657, F1: 0.6543

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67274 | val 0.75340
  Epoch 016 - train 0.66612 | val 0.76688
  Classification -> best τ=0.585 (val F1=0.1344)
  Directional -> Accuracy: 0.4774, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66306 | val 1.04150
  Epoch 016 - train 0.66209 | val 1.05077
  Classification -> best τ=0.400 (val F1=0.0489)
  Directional -> Accuracy: 0.4824, MCC: -0.0451, F1: 0.5297

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67439 | val 0.72606
  Epoch 016 - train 0.66209 | val 0.72933
  Classification -> best τ=0.425 (val F1=0.0683)
  Directional -> Accuracy: 0.5980, MCC: 0.0912, F1: 0.7419

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65301 | val 0.82303
  Epoch 016 - train 0.65962 | val 0.85600
  Classification -> best τ=0.490 (val F1=0.1617)
  Directional -> Accuracy: 0.5578, MCC: 0.0170, F1: 0.7027

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65789 | val 0.93690
  Epoch 016 - train 0.66823 | val 0.89894
  Classification -> best τ=0.360 (val F1=0.0759)
  Directional -> Accuracy: 0.5377, MCC: -0.0710, F1: 0.6738

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65425 | val 0.93926
  Epoch 016 - train 0.65457 | val 1.01722
  Classification -> best τ=0.460 (val F1=0.1178)
  Directional -> Accuracy: 0.4774, MCC: -0.0418, F1: 0.5094

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67265 | val 0.79151
  Epoch 016 - train 0.65266 | val 0.77866
  Classification -> best τ=0.435 (val F1=0.1194)
  Directional -> Accuracy: 0.5377, MCC: 0.0633, F1: 0.5856

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67337 | val 0.71693
  Epoch 020 - train 0.66864 | val 0.84996
  Classification -> best τ=0.510 (val F1=0.2154)
  Directional -> Accuracy: 0.4472, MCC: 0.0271, F1: 0.0351

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65933 | val 0.77127
  Epoch 016 - train 0.65290 | val 0.77899
  Classification -> best τ=0.465 (val F1=0.1099)
  Directional -> Accuracy: 0.4975, MCC: 0.0134, F1: 0.1525

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68289 | val 0.76903
  Epoch 016 - train 0.66560 | val 0.78954
  Classification -> best τ=0.580 (val F1=0.1069)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.66269 | val 0.84067
  Epoch 016 - train 0.66678 | val 0.84112
  Classification -> best τ=0.435 (val F1=0.1609)
  Directional -> Accuracy: 0.4121, MCC: -0.0273, F1: 0.1460

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.67192 | val 0.93719
  Epoch 016 - train 0.66876 | val 1.10921
  Classification -> best τ=0.460 (val F1=0.1146)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.6644

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66827 | val 0.88196
  Epoch 016 - train 0.66364 | val 0.85865
  Classification -> best τ=0.430 (val F1=0.1194)
  Directional -> Accuracy: 0.5276, MCC: 0.0394, F1: 0.6846

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66901 | val 0.77223
  Epoch 016 - train 0.65872 | val 0.79188
  Classification -> best τ=0.415 (val F1=0.0942)
  Directional -> Accuracy: 0.5126, MCC: 0.0690, F1: 0.4260

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.66845 | val 0.74653
  Epoch 016 - train 0.65795 | val 0.72231
  Classification -> best τ=0.560 (val F1=0.1029)
  Directional -> Accuracy: 0.4925, MCC: 0.0635, F1: 0.1513

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65439 | val 0.72143
  Epoch 016 - train 0.65352 | val 0.72734
  Classification -> best τ=0.535 (val F1=0.1939)
  Directional -> Accuracy: 0.4221, MCC: -0.0121, F1: 0.0800

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66179 | val 0.68497
  Epoch 016 - train 0.64745 | val 0.75946
  Classification -> best τ=0.500 (val F1=0.2022)
  Directional -> Accuracy: 0.5075, MCC: 0.0707, F1: 0.3194

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65708 | val 0.81897
  Epoch 016 - train 0.65304 | val 0.83979
  Classification -> best τ=0.630 (val F1=0.0892)
  Directional -> Accuracy: 0.5226, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67004 | val 1.06059
  Epoch 016 - train 0.66006 | val 1.15071
  Classification -> best τ=0.495 (val F1=0.2142)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.66776 | val 0.70715
  Epoch 020 - train 0.65555 | val 0.74528
  Classification -> best τ=0.630 (val F1=0.1076)
  Directional -> Accuracy: 0.5327, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.66526 | val 0.83029
  Epoch 016 - train 0.64847 | val 0.89905
  Classification -> best τ=0.425 (val F1=0.0963)
  Directional -> Accuracy: 0.4422, MCC: 0.0157, F1: 0.1395

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.67328 | val 1.04319
  Epoch 016 - train 0.66597 | val 1.13307
  Classification -> best τ=0.495 (val F1=0.1220)
  Directional -> Accuracy: 0.4171, MCC: -0.0832, F1: 0.0000

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.67699 | val 0.73987
  Epoch 016 - train 0.66342 | val 0.79670
  Classification -> best τ=0.480 (val F1=0.1668)
  Directional -> Accuracy: 0.4745, MCC: 0.0239, F1: 0.5463

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.67572 | val 0.71914
  Epoch 016 - train 0.66734 | val 0.75982
  Classification -> best τ=0.505 (val F1=0.1553)
  Directional -> Accuracy: 0.5678, MCC: 0.1200, F1: 0.6718

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.66968 | val 0.81286
  Epoch 016 - train 0.66015 | val 0.84118
  Classification -> best τ=0.555 (val F1=0.0505)
  Directional -> Accuracy: 0.4796, MCC: -0.0602, F1: 0.1774

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67024 | val 0.77321
  Epoch 016 - train 0.66192 | val 0.80942
  Classification -> best τ=0.515 (val F1=0.2794)
  Directional -> Accuracy: 0.4523, MCC: -0.0321, F1: 0.5477

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.66562 | val 0.73213
  Epoch 020 - train 0.66463 | val 0.75394
  Classification -> best τ=0.495 (val F1=0.1053)
  Directional -> Accuracy: 0.5561, MCC: 0.1194, F1: 0.4314

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.67893 | val 0.92058
  Epoch 016 - train 0.67022 | val 0.90774
  Classification -> best τ=0.635 (val F1=0.1413)
  Directional -> Accuracy: 0.5176, MCC: 0.1455, F1: 0.1579

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67366 | val 0.71438
  Epoch 020 - train 0.64630 | val 0.68564
  Classification -> best τ=0.545 (val F1=0.1398)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.67023 | val 1.38182
  Epoch 016 - train 0.67238 | val 1.33471
  Classification -> best τ=0.485 (val F1=0.1113)
  Directional -> Accuracy: 0.4724, MCC: 0.0704, F1: 0.6237

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.67261 | val 0.86765
  Epoch 016 - train 0.66973 | val 0.85883
  Classification -> best τ=0.520 (val F1=0.0888)
  Directional -> Accuracy: 0.4774, MCC: 0.0057, F1: 0.1186

[75/88] Processing T...

Processing T (Technology)...

[I 2026-02-26 03:15:17,265] Trial 30 finished with value: 0.13705324358068652 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.0014559197876906286, 'weight_decay': 4.056051131181077e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.7864517154645297, 'early_stopping_min_delta': 0.005956572932972987}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 016 - train 0.66993 | val 0.77970
  Classification -> best τ=0.420 (val F1=0.1368)
  Directional -> Accuracy: 0.5075, MCC: 0.0623, F1: 0.6573

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.13705324358068652
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64693 | val 1.16016
  Epoch 020 - train 0.58910 | val 1.35699
  Epoch 021 - train 0.60285 | val 1.22874
  Classification -> best τ=0.205 (val F1=0.1813)
  Directional -> Accuracy: 0.4650, MCC: 0.0219, F1: 0.3515

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.60665 | val 3.24577
  Epoch 020 - train 0.50885 | val 6.30719
  Epoch 021 - train 0.50242 | val 5.92273
  Classification -> best τ=0.340 (val F1=0.2010)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62009 | val 0.88128
  Epoch 020 - train 0.57320 | val 1.14384
  Epoch 021 - train 0.56065 | val 1.16296
  Classification -> best τ=0.335 (val F1=0.1702)
  Directional -> Accuracy: 0.5775, MCC: 0.0480, F1: 0.7168

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.64527 | val 0.72845
  Epoch 020 - train 0.58537 | val 0.84847
  Epoch 030 - train 0.42397 | val 1.02397
  Epoch 032 - train 0.37389 | val 1.03246
  Classification -> best τ=0.450 (val F1=0.0668)
  Directional -> Accuracy: 0.5650, MCC: 0.0564, F1: 0.7184

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.61993 | val 0.79050
  Epoch 020 - train 0.50427 | val 1.04909
  Epoch 021 - train 0.50422 | val 1.08329
  Classification -> best τ=0.545 (val F1=0.1483)
  Directional -> Accuracy: 0.4766, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62690 | val 1.37082
  Epoch 020 - train 0.55560 | val 2.20888
  Epoch 021 - train 0.52645 | val 2.34626
  Classification -> best τ=0.075 (val F1=0.0978)
  Directional -> Accuracy: 0.5250, MCC: -0.0470, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66184 | val 1.08009
  Epoch 020 - train 0.59457 | val 1.86795
  Epoch 021 - train 0.58415 | val 2.34677
  Classification -> best τ=0.315 (val F1=0.1465)
  Directional -> Accuracy: 0.5050, MCC: -0.0157, F1: 0.5751

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62183 | val 1.64431
  Epoch 020 - train 0.52069 | val 1.87974
  Epoch 021 - train 0.50957 | val 1.99333
  Classification -> best τ=0.205 (val F1=0.2750)
  Directional -> Accuracy: 0.4350, MCC: 0.0648, F1: 0.1986

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59419 | val 3.41069
  Epoch 020 - train 0.48798 | val 3.84099
  Epoch 021 - train 0.50890 | val 4.46176
  Classification -> best τ=0.140 (val F1=0.1371)
  Directional -> Accuracy: 0.4609, MCC: -0.0721, F1: 0.4918

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63675 | val 1.67413
  Epoch 020 - train 0.56042 | val 2.06685
  Epoch 021 - train 0.56656 | val 2.44774
  Classification -> best τ=0.245 (val F1=0.1050)
  Directional -> Accuracy: 0.4400, MCC: -0.0898, F1: 0.5692

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.64175 | val 0.74526
  Epoch 020 - train 0.54429 | val 0.87898
  Epoch 027 - train 0.47540 | val 0.86028
  Classification -> best τ=0.500 (val F1=0.2079)
  Directional -> Accuracy: 0.4850, MCC: 0.0031, F1: 0.3832

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.64797 | val 0.78611
  Epoch 020 - train 0.58424 | val 0.85214
  Epoch 021 - train 0.57109 | val 0.87748
  Classification -> best τ=0.540 (val F1=0.1401)
  Directional -> Accuracy: 0.4350, MCC: -0.0020, F1: 0.1240

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62932 | val 1.18067
  Epoch 020 - train 0.53907 | val 1.25000
  Epoch 021 - train 0.52410 | val 1.11999
  Classification -> best τ=0.465 (val F1=0.1115)
  Directional -> Accuracy: 0.4800, MCC: 0.0233, F1: 0.3580

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64232 | val 1.33613
  Epoch 020 - train 0.50055 | val 2.63442
  Epoch 021 - train 0.52621 | val 2.69396
  Classification -> best τ=0.655 (val F1=0.1697)
  Directional -> Accuracy: 0.5100, MCC: 0.0291, F1: 0.0755

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.66824 | val 1.02447
  Epoch 020 - train 0.61544 | val 1.37736
  Epoch 021 - train 0.59956 | val 1.41641
  Classification -> best τ=0.205 (val F1=0.0730)
  Directional -> Accuracy: 0.4850, MCC: -0.0756, F1: 0.6054

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.62996 | val 1.32511
  Epoch 020 - train 0.53285 | val 2.48638
  Epoch 021 - train 0.53496 | val 2.40065
  Classification -> best τ=0.505 (val F1=0.1458)
  Directional -> Accuracy: 0.5100, MCC: 0.1005, F1: 0.0392

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.62662 | val 1.08101
  Epoch 020 - train 0.55991 | val 1.62431
  Epoch 021 - train 0.54627 | val 1.57832
  Classification -> best τ=0.210 (val F1=0.2039)
  Directional -> Accuracy: 0.5550, MCC: 0.0000, F1: 0.7138

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62569 | val 1.21437
  Epoch 020 - train 0.47421 | val 2.38259
  Epoch 021 - train 0.46904 | val 2.60908
  Classification -> best τ=0.920 (val F1=0.2096)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63474 | val 0.84383
  Epoch 020 - train 0.57039 | val 0.77013
  Epoch 030 - train 0.42135 | val 1.09588
  Epoch 032 - train 0.40454 | val 1.21589
  Classification -> best τ=0.385 (val F1=0.1412)
  Directional -> Accuracy: 0.4450, MCC: -0.1109, F1: 0.4064

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64499 | val 0.87039
  Epoch 020 - train 0.54683 | val 1.20692
  Epoch 021 - train 0.53636 | val 1.22585
  Classification -> best τ=0.580 (val F1=0.1001)
  Directional -> Accuracy: 0.4650, MCC: -0.0152, F1: 0.1955

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.63321 | val 1.14024
  Epoch 020 - train 0.53642 | val 1.21270
  Epoch 026 - train 0.48483 | val 1.37578
  Classification -> best τ=0.225 (val F1=0.1977)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.6577

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.65523 | val 1.45744
  Epoch 020 - train 0.54466 | val 3.02185
  Epoch 021 - train 0.56638 | val 2.94913
  Classification -> best τ=0.480 (val F1=0.1909)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63586 | val 1.22090
  Epoch 020 - train 0.55077 | val 2.77825
  Epoch 021 - train 0.56946 | val 2.53370
  Classification -> best τ=0.265 (val F1=0.1878)
  Directional -> Accuracy: 0.5000, MCC: 0.0214, F1: 0.4624

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.64702 | val 1.20949
  Epoch 020 - train 0.55827 | val 1.51303
  Epoch 021 - train 0.57853 | val 1.65334
  Classification -> best τ=0.170 (val F1=0.1638)
  Directional -> Accuracy: 0.4300, MCC: 0.0348, F1: 0.5547

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62565 | val 1.59166
  Epoch 020 - train 0.53052 | val 3.16283
  Epoch 021 - train 0.54220 | val 3.14332
  Classification -> best τ=0.405 (val F1=0.1274)
  Directional -> Accuracy: 0.5200, MCC: 0.0511, F1: 0.4667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64464 | val 0.90398
  Epoch 020 - train 0.57567 | val 1.13209
  Epoch 021 - train 0.58973 | val 0.99299
  Classification -> best τ=0.440 (val F1=0.1898)
  Directional -> Accuracy: 0.5550, MCC: 0.1274, F1: 0.2880

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64522 | val 1.01041
  Epoch 020 - train 0.56397 | val 1.44067
  Epoch 021 - train 0.54577 | val 1.45195
  Classification -> best τ=0.420 (val F1=0.1479)
  Directional -> Accuracy: 0.4450, MCC: -0.1301, F1: 0.5153

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.65127 | val 0.88927
  Epoch 020 - train 0.55872 | val 1.62767
  Epoch 021 - train 0.57164 | val 1.32847
  Classification -> best τ=0.425 (val F1=0.1542)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4118

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65834 | val 1.36953
  Epoch 020 - train 0.60062 | val 3.46923
  Epoch 021 - train 0.58918 | val 3.39177
  Classification -> best τ=0.555 (val F1=0.1670)
  Directional -> Accuracy: 0.5100, MCC: 0.0162, F1: 0.5463

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.65883 | val 0.82000
  Epoch 020 - train 0.55308 | val 1.03145
  Epoch 023 - train 0.53156 | val 1.27763
  Classification -> best τ=0.460 (val F1=0.0950)
  Directional -> Accuracy: 0.5400, MCC: 0.0576, F1: 0.6167

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.65426 | val 1.91652
  Epoch 020 - train 0.55681 | val 1.23986
  Epoch 021 - train 0.53490 | val 1.48263
  Classification -> best τ=0.660 (val F1=0.1292)
  Directional -> Accuracy: 0.4950, MCC: 0.0000, F1: 0.0000

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64919 | val 0.96866
  Epoch 020 - train 0.58378 | val 1.09847
  Epoch 021 - train 0.58153 | val 1.17069
  Classification -> best τ=0.610 (val F1=0.1128)
  Directional -> Accuracy: 0.4450, MCC: -0.0784, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.65782 | val 1.08532
  Epoch 020 - train 0.57228 | val 1.44791
  Epoch 024 - train 0.54332 | val 1.94767
  Classification -> best τ=0.695 (val F1=0.1640)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63283 | val 0.87554
  Epoch 020 - train 0.58394 | val 0.78926
  Epoch 030 - train 0.53095 | val 0.98001
  Epoch 039 - train 0.44670 | val 1.07330
  Classification -> best τ=0.645 (val F1=0.1341)
  Directional -> Accuracy: 0.5650, MCC: 0.0844, F1: 0.3556

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.55693 | val 1.07915
  Epoch 020 - train 0.53509 | val 1.50445
  Epoch 021 - train 0.42423 | val 1.33974
  Classification -> best τ=0.520 (val F1=0.2120)
  Directional -> Accuracy: 0.5625, MCC: 0.1260, F1: 0.5882

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63160 | val 0.74520
  Epoch 020 - train 0.54952 | val 0.89033
  Epoch 022 - train 0.53870 | val 1.08242
  Classification -> best τ=0.635 (val F1=0.1799)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65171 | val 0.91540
  Epoch 020 - train 0.56596 | val 1.41240
  Epoch 021 - train 0.57734 | val 1.16564
  Classification -> best τ=0.730 (val F1=0.1707)
  Directional -> Accuracy: 0.4650, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.63748 | val 1.22060
  Epoch 020 - train 0.55941 | val 1.43962
  Epoch 021 - train 0.55540 | val 1.38469
  Classification -> best τ=0.115 (val F1=0.1454)
  Directional -> Accuracy: 0.5800, MCC: 0.1180, F1: 0.6693

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.63756 | val 1.54859
  Epoch 020 - train 0.55077 | val 2.72042
  Epoch 021 - train 0.54070 | val 3.08459
  Classification -> best τ=0.825 (val F1=0.0952)
  Directional -> Accuracy: 0.4550, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.66157 | val 1.19090
  Epoch 020 - train 0.58287 | val 1.59732
  Epoch 021 - train 0.57267 | val 1.77856
  Classification -> best τ=0.285 (val F1=0.0929)
  Directional -> Accuracy: 0.5200, MCC: 0.0276, F1: 0.5862

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.66671 | val 1.02816
  Epoch 020 - train 0.59390 | val 1.22272
  Epoch 021 - train 0.59508 | val 1.20727
  Classification -> best τ=0.835 (val F1=0.1667)
  Directional -> Accuracy: 0.4950, MCC: 0.0534, F1: 0.0734

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65363 | val 1.11540
  Epoch 020 - train 0.55826 | val 1.94524
  Epoch 021 - train 0.53530 | val 1.97314
  Classification -> best τ=0.245 (val F1=0.1068)
  Directional -> Accuracy: 0.5450, MCC: 0.0450, F1: 0.6997

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64590 | val 0.96029
  Epoch 020 - train 0.55364 | val 1.16554
  Epoch 027 - train 0.49129 | val 1.67628
  Classification -> best τ=0.385 (val F1=0.1414)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64462 | val 1.57806
  Epoch 020 - train 0.58436 | val 2.85641
  Epoch 021 - train 0.56166 | val 2.83394
  Classification -> best τ=0.145 (val F1=0.1661)
  Directional -> Accuracy: 0.4700, MCC: -0.0461, F1: 0.1587

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63862 | val 2.04540
  Epoch 020 - train 0.52955 | val 3.05330
  Epoch 021 - train 0.54060 | val 3.15715
  Classification -> best τ=0.060 (val F1=0.0929)
  Directional -> Accuracy: 0.5200, MCC: 0.0138, F1: 0.6098

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65214 | val 1.10118
  Epoch 020 - train 0.59554 | val 1.21804
  Epoch 021 - train 0.58309 | val 1.28628
  Classification -> best τ=0.860 (val F1=0.0909)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62952 | val 0.97245
  Epoch 020 - train 0.55961 | val 1.51772
  Epoch 021 - train 0.54679 | val 1.29576
  Classification -> best τ=0.620 (val F1=0.1123)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64932 | val 0.73338
  Epoch 020 - train 0.58363 | val 0.89018
  Epoch 030 - train 0.39751 | val 1.27764
  Epoch 031 - train 0.40424 | val 1.16941
  Classification -> best τ=0.685 (val F1=0.1184)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64150 | val 1.11165
  Epoch 020 - train 0.58000 | val 2.59613
  Epoch 021 - train 0.56269 | val 2.70699
  Classification -> best τ=0.610 (val F1=0.1571)
  Directional -> Accuracy: 0.5200, MCC: 0.0348, F1: 0.3239

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64114 | val 1.00175
  Epoch 020 - train 0.57734 | val 0.92471
  Epoch 028 - train 0.51890 | val 1.24396
  Classification -> best τ=0.260 (val F1=0.1377)
  Directional -> Accuracy: 0.5050, MCC: 0.0916, F1: 0.3851

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65952 | val 1.16897
  Epoch 020 - train 0.58918 | val 1.11536
  Epoch 027 - train 0.49513 | val 1.23637
  Classification -> best τ=0.365 (val F1=0.1663)
  Directional -> Accuracy: 0.4650, MCC: -0.0324, F1: 0.4022

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64827 | val 0.82492
  Epoch 020 - train 0.54199 | val 1.72387
  Epoch 025 - train 0.51875 | val 1.74015
  Classification -> best τ=0.850 (val F1=0.1918)
  Directional -> Accuracy: 0.4950, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64825 | val 0.74806
  Epoch 020 - train 0.59598 | val 0.88989
  Epoch 029 - train 0.45968 | val 0.82480
  Classification -> best τ=0.495 (val F1=0.0956)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.65000 | val 0.75504
  Epoch 020 - train 0.55396 | val 0.91920
  Epoch 021 - train 0.56699 | val 0.96764
  Classification -> best τ=0.650 (val F1=0.1607)
  Directional -> Accuracy: 0.4000, MCC: -0.0859, F1: 0.0000

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.63731 | val 1.05258
  Epoch 020 - train 0.54855 | val 1.44713
  Epoch 021 - train 0.53317 | val 1.41368
  Classification -> best τ=0.190 (val F1=0.1572)
  Directional -> Accuracy: 0.5050, MCC: 0.0396, F1: 0.6551

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66889 | val 1.10968
  Epoch 020 - train 0.58859 | val 2.30234
  Epoch 021 - train 0.57545 | val 2.01568
  Classification -> best τ=0.160 (val F1=0.1373)
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.6885

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65697 | val 0.74918
  Epoch 020 - train 0.57876 | val 1.27078
  Epoch 030 - train 0.45421 | val 1.78038
  Classification -> best τ=0.490 (val F1=0.1351)
  Directional -> Accuracy: 0.5300, MCC: 0.1361, F1: 0.3974

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.66365 | val 0.70487
  Epoch 020 - train 0.56587 | val 0.72746
  Epoch 021 - train 0.57200 | val 0.72798
  Classification -> best τ=0.655 (val F1=0.1300)
  Directional -> Accuracy: 0.4700, MCC: -0.0745, F1: 0.0000

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64042 | val 1.18058
  Epoch 020 - train 0.55184 | val 1.65829
  Epoch 022 - train 0.53927 | val 1.63275
  Classification -> best τ=0.475 (val F1=0.2172)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63827 | val 1.16901
  Epoch 020 - train 0.56039 | val 1.38824
  Epoch 021 - train 0.54582 | val 1.56879
  Classification -> best τ=0.315 (val F1=0.1371)
  Directional -> Accuracy: 0.4750, MCC: -0.1027, F1: 0.6008

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64889 | val 1.25830
  Epoch 020 - train 0.56885 | val 1.66412
  Epoch 021 - train 0.54897 | val 1.40119
  Classification -> best τ=0.770 (val F1=0.0658)
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65748 | val 1.30323
  Epoch 020 - train 0.54162 | val 1.27640
  Epoch 023 - train 0.50753 | val 1.84214
  Classification -> best τ=0.560 (val F1=0.1849)
  Directional -> Accuracy: 0.4850, MCC: -0.0436, F1: 0.0190

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.65936 | val 1.34994
  Epoch 020 - train 0.54554 | val 1.44827
  Epoch 022 - train 0.52587 | val 1.39687
  Classification -> best τ=0.670 (val F1=0.1168)
  Directional -> Accuracy: 0.5350, MCC: 0.0000, F1: 0.0000


[I 2026-02-26 03:26:36,402] Trial 31 finished with value: 0.14988398195701744 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.002005720561331927, 'weight_decay': 2.9029277740061943e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.1092287526746718, 'early_stopping_min_delta': 0.0010753573549319878}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 026 - train 0.49856 | val 2.28057
  Classification -> best τ=0.315 (val F1=0.1814)
  Directional -> Accuracy: 0.4800, MCC: -0.0352, F1: 0.6000

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14988398195701744
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65160 | val 1.05182
  Epoch 020 - train 0.62941 | val 1.03017
  Epoch 021 - train 0.61889 | val 1.00698
  Classification -> best τ=0.265 (val F1=0.1635)
  Directional -> Accuracy: 0.5400, MCC: 0.0326, F1: 0.6260

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.61927 | val 3.59116
  Epoch 020 - train 0.57353 | val 3.71323
  Epoch 021 - train 0.58679 | val 3.91909
  Classification -> best τ=0.055 (val F1=0.1666)
  Directional -> Accuracy: 0.5350, MCC: 0.0921, F1: 0.3111

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63654 | val 0.80351
  Epoch 020 - train 0.60676 | val 0.83762
  Epoch 021 - train 0.60287 | val 0.83708
  Classification -> best τ=0.340 (val F1=0.1382)
  Directional -> Accuracy: 0.5455, MCC: 0.0105, F1: 0.6614

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.66498 | val 0.77762
  Epoch 020 - train 0.61895 | val 0.80573
  Epoch 026 - train 0.62440 | val 0.82413
  Classification -> best τ=0.585 (val F1=0.0918)
  Directional -> Accuracy: 0.4150, MCC: -0.1396, F1: 0.0488

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.62127 | val 1.05273
  Epoch 020 - train 0.59408 | val 1.20230
  Epoch 021 - train 0.58763 | val 1.16875
  Classification -> best τ=0.585 (val F1=0.1714)
  Directional -> Accuracy: 0.4766, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63232 | val 1.20591
  Epoch 020 - train 0.60462 | val 1.53919
  Epoch 021 - train 0.59992 | val 1.58241
  Classification -> best τ=0.100 (val F1=0.0952)
  Directional -> Accuracy: 0.5400, MCC: -0.0204, F1: 0.6871

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65356 | val 1.62543
  Epoch 020 - train 0.63870 | val 2.04145
  Epoch 021 - train 0.63630 | val 2.04147
  Classification -> best τ=0.470 (val F1=0.1649)
  Directional -> Accuracy: 0.4800, MCC: -0.0476, F1: 0.5229

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62734 | val 1.11386
  Epoch 020 - train 0.59581 | val 1.45471
  Epoch 021 - train 0.60251 | val 1.43833
  Classification -> best τ=0.205 (val F1=0.3033)
  Directional -> Accuracy: 0.5200, MCC: 0.1476, F1: 0.4607

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62067 | val 2.65100
  Epoch 020 - train 0.58980 | val 2.79312
  Epoch 021 - train 0.58958 | val 2.79675
  Classification -> best τ=0.405 (val F1=0.1564)
  Directional -> Accuracy: 0.4174, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63875 | val 1.54496
  Epoch 020 - train 0.61601 | val 1.70907
  Epoch 021 - train 0.62564 | val 1.70358
  Classification -> best τ=0.825 (val F1=0.1072)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.64698 | val 0.74619
  Epoch 020 - train 0.61570 | val 0.88658
  Epoch 021 - train 0.61484 | val 0.91707
  Classification -> best τ=0.420 (val F1=0.0942)
  Directional -> Accuracy: 0.5300, MCC: 0.0393, F1: 0.6017

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.65244 | val 0.77872
  Epoch 020 - train 0.63538 | val 0.78580
  Epoch 021 - train 0.61981 | val 0.81043
  Classification -> best τ=0.485 (val F1=0.1684)
  Directional -> Accuracy: 0.4550, MCC: 0.0212, F1: 0.2483

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63384 | val 1.01305
  Epoch 020 - train 0.59888 | val 1.24275
  Epoch 021 - train 0.59025 | val 1.31892
  Classification -> best τ=0.225 (val F1=0.0904)
  Directional -> Accuracy: 0.5050, MCC: 0.0089, F1: 0.5352

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64756 | val 1.47721
  Epoch 020 - train 0.59310 | val 2.20372
  Epoch 021 - train 0.59099 | val 2.18811
  Classification -> best τ=0.685 (val F1=0.1807)
  Directional -> Accuracy: 0.5100, MCC: 0.0424, F1: 0.0392

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.66845 | val 0.96324
  Epoch 020 - train 0.64789 | val 1.11129
  Epoch 021 - train 0.65895 | val 1.06608
  Classification -> best τ=0.265 (val F1=0.1111)
  Directional -> Accuracy: 0.4900, MCC: -0.0831, F1: 0.6277

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.63939 | val 1.96760
  Epoch 020 - train 0.60281 | val 2.18644
  Epoch 021 - train 0.59872 | val 2.28244
  Classification -> best τ=0.670 (val F1=0.1333)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.64161 | val 0.98773
  Epoch 020 - train 0.62187 | val 1.12294
  Epoch 021 - train 0.60820 | val 1.09006
  Classification -> best τ=0.400 (val F1=0.1661)
  Directional -> Accuracy: 0.5550, MCC: 0.0000, F1: 0.7138

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63712 | val 1.51127
  Epoch 020 - train 0.59233 | val 1.43824
  Epoch 021 - train 0.58713 | val 1.45306
  Classification -> best τ=0.385 (val F1=0.1351)
  Directional -> Accuracy: 0.4750, MCC: -0.0457, F1: 0.1176

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64634 | val 0.81734
  Epoch 020 - train 0.61172 | val 0.77043
  Epoch 021 - train 0.60826 | val 0.78858
  Classification -> best τ=0.470 (val F1=0.2413)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65670 | val 0.85890
  Epoch 020 - train 0.61550 | val 0.92821
  Epoch 021 - train 0.61316 | val 0.94481
  Classification -> best τ=0.550 (val F1=0.1063)
  Directional -> Accuracy: 0.4600, MCC: -0.0203, F1: 0.1000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.65478 | val 0.80552
  Epoch 020 - train 0.61340 | val 0.94853
  Epoch 021 - train 0.62306 | val 0.96549
  Classification -> best τ=0.645 (val F1=0.1364)
  Directional -> Accuracy: 0.5400, MCC: 0.0790, F1: 0.5208

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.65676 | val 1.72798
  Epoch 020 - train 0.62236 | val 2.20429
  Epoch 021 - train 0.62570 | val 2.16608
  Classification -> best τ=0.500 (val F1=0.1396)
  Directional -> Accuracy: 0.4500, MCC: 0.0759, F1: 0.0678

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64550 | val 1.20103
  Epoch 020 - train 0.60985 | val 1.55775
  Epoch 021 - train 0.61455 | val 1.65619
  Classification -> best τ=0.395 (val F1=0.1613)
  Directional -> Accuracy: 0.4750, MCC: 0.0418, F1: 0.1732

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.65208 | val 1.13457
  Epoch 020 - train 0.62702 | val 1.35287
  Epoch 021 - train 0.61557 | val 1.38635
  Classification -> best τ=0.100 (val F1=0.1064)
  Directional -> Accuracy: 0.4250, MCC: 0.0307, F1: 0.5560

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65052 | val 1.32572
  Epoch 020 - train 0.59379 | val 1.82390
  Epoch 021 - train 0.61010 | val 1.80158
  Classification -> best τ=0.140 (val F1=0.1144)
  Directional -> Accuracy: 0.5300, MCC: 0.0450, F1: 0.6594

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66297 | val 0.97475
  Epoch 020 - train 0.63358 | val 1.27450
  Epoch 021 - train 0.63962 | val 1.31707
  Classification -> best τ=0.380 (val F1=0.1991)
  Directional -> Accuracy: 0.5500, MCC: 0.1096, F1: 0.2969

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65484 | val 1.55807
  Epoch 020 - train 0.62236 | val 1.93376
  Epoch 021 - train 0.61460 | val 1.96547
  Classification -> best τ=0.525 (val F1=0.1675)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.64942 | val 1.00153
  Epoch 020 - train 0.63288 | val 1.13592
  Epoch 021 - train 0.62319 | val 1.16332
  Classification -> best τ=0.445 (val F1=0.0849)
  Directional -> Accuracy: 0.5150, MCC: 0.0658, F1: 0.6644

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65970 | val 1.38138
  Epoch 020 - train 0.62355 | val 2.00740
  Epoch 021 - train 0.62817 | val 2.03335
  Classification -> best τ=0.695 (val F1=0.1528)
  Directional -> Accuracy: 0.5050, MCC: 0.0649, F1: 0.1681

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.65582 | val 1.68599
  Epoch 020 - train 0.62025 | val 2.02562
  Epoch 021 - train 0.61606 | val 1.99073
  Classification -> best τ=0.380 (val F1=0.1470)
  Directional -> Accuracy: 0.4600, MCC: -0.0081, F1: 0.0182

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.65586 | val 2.20400
  Epoch 020 - train 0.61499 | val 1.98340
  Epoch 021 - train 0.61922 | val 2.03442
  Classification -> best τ=0.450 (val F1=0.1702)
  Directional -> Accuracy: 0.4950, MCC: -0.0020, F1: 0.0734

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65683 | val 0.92731
  Epoch 020 - train 0.64031 | val 0.78347
  Epoch 021 - train 0.63273 | val 0.82047
  Classification -> best τ=0.375 (val F1=0.1280)
  Directional -> Accuracy: 0.5350, MCC: 0.0485, F1: 0.6009

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.66895 | val 0.87216
  Epoch 020 - train 0.65006 | val 0.97449
  Epoch 021 - train 0.63347 | val 0.98735
  Classification -> best τ=0.225 (val F1=0.1845)
  Directional -> Accuracy: 0.5250, MCC: -0.0483, F1: 0.6415

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63478 | val 1.33106
  Epoch 020 - train 0.61514 | val 1.47872
  Epoch 021 - train 0.60570 | val 1.46415
  Classification -> best τ=0.135 (val F1=0.1015)
  Directional -> Accuracy: 0.4450, MCC: 0.0000, F1: 0.6159

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.60826 | val 1.05222
  Epoch 020 - train 0.55166 | val 1.13079
  Epoch 021 - train 0.54244 | val 1.15844
  Classification -> best τ=0.500 (val F1=0.2036)
  Directional -> Accuracy: 0.5625, MCC: 0.1348, F1: 0.6316

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64151 | val 1.09112
  Epoch 020 - train 0.59788 | val 1.32022
  Epoch 021 - train 0.60092 | val 1.33215
  Classification -> best τ=0.455 (val F1=0.1991)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64589 | val 0.91139
  Epoch 020 - train 0.61711 | val 1.04611
  Epoch 021 - train 0.61948 | val 1.06385
  Classification -> best τ=0.695 (val F1=0.1707)
  Directional -> Accuracy: 0.4800, MCC: 0.0851, F1: 0.0714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.64750 | val 1.67305
  Epoch 020 - train 0.60835 | val 1.53022
  Epoch 021 - train 0.61928 | val 1.44483
  Classification -> best τ=0.140 (val F1=0.0792)
  Directional -> Accuracy: 0.5900, MCC: 0.1321, F1: 0.6917

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.64258 | val 1.62427
  Epoch 020 - train 0.60954 | val 1.72957
  Epoch 021 - train 0.60978 | val 1.78465
  Classification -> best τ=0.240 (val F1=0.0808)
  Directional -> Accuracy: 0.5450, MCC: 0.0000, F1: 0.7055

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.65475 | val 1.37373
  Epoch 020 - train 0.62742 | val 1.60660
  Epoch 021 - train 0.62682 | val 1.67179
  Classification -> best τ=0.815 (val F1=0.0993)
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.0000

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.65642 | val 2.35697
  Epoch 020 - train 0.62889 | val 1.98292
  Epoch 021 - train 0.63912 | val 1.96582
  Classification -> best τ=0.720 (val F1=0.1585)
  Directional -> Accuracy: 0.4800, MCC: -0.0449, F1: 0.0189

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64755 | val 1.20738
  Epoch 020 - train 0.62940 | val 1.42168
  Epoch 021 - train 0.62067 | val 1.42222
  Classification -> best τ=0.245 (val F1=0.1157)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64452 | val 1.94610
  Epoch 020 - train 0.62285 | val 2.28062
  Epoch 021 - train 0.61905 | val 1.99330
  Classification -> best τ=0.440 (val F1=0.1810)
  Directional -> Accuracy: 0.5000, MCC: 0.0340, F1: 0.2188

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63843 | val 1.08708
  Epoch 020 - train 0.61686 | val 1.30655
  Epoch 021 - train 0.59966 | val 1.28047
  Classification -> best τ=0.695 (val F1=0.1417)
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62580 | val 3.14387
  Epoch 020 - train 0.60363 | val 3.13907
  Epoch 021 - train 0.59603 | val 3.26261
  Classification -> best τ=0.100 (val F1=0.1201)
  Directional -> Accuracy: 0.5250, MCC: 0.0160, F1: 0.6332

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64936 | val 1.00687
  Epoch 020 - train 0.62148 | val 1.05817
  Epoch 021 - train 0.62891 | val 1.05554
  Classification -> best τ=0.225 (val F1=0.0861)
  Directional -> Accuracy: 0.5950, MCC: 0.0871, F1: 0.7327

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65863 | val 1.06657
  Epoch 020 - train 0.62323 | val 1.06635
  Epoch 021 - train 0.62138 | val 1.07579
  Classification -> best τ=0.390 (val F1=0.1622)
  Directional -> Accuracy: 0.5850, MCC: 0.1482, F1: 0.6438

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63780 | val 0.95791
  Epoch 020 - train 0.60019 | val 1.36991
  Epoch 022 - train 0.60050 | val 1.37576
  Classification -> best τ=0.680 (val F1=0.1099)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65202 | val 1.86051
  Epoch 020 - train 0.63075 | val 1.75545
  Epoch 021 - train 0.61245 | val 1.87739
  Classification -> best τ=0.565 (val F1=0.1413)
  Directional -> Accuracy: 0.5100, MCC: 0.0109, F1: 0.3194

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63825 | val 1.12693
  Epoch 020 - train 0.62280 | val 1.00730
  Epoch 021 - train 0.62547 | val 1.00888
  Classification -> best τ=0.615 (val F1=0.1319)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65454 | val 1.31390
  Epoch 020 - train 0.62675 | val 1.45609
  Epoch 021 - train 0.61131 | val 1.59234
  Classification -> best τ=0.660 (val F1=0.1116)
  Directional -> Accuracy: 0.4150, MCC: -0.1225, F1: 0.1333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65058 | val 0.99756
  Epoch 020 - train 0.61905 | val 1.27184
  Epoch 021 - train 0.61848 | val 1.26889
  Classification -> best τ=0.670 (val F1=0.1222)
  Directional -> Accuracy: 0.4950, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65289 | val 1.11436
  Epoch 020 - train 0.62627 | val 0.96895
  Epoch 021 - train 0.62775 | val 0.92797
  Classification -> best τ=0.575 (val F1=0.0882)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.65761 | val 0.87054
  Epoch 020 - train 0.63652 | val 0.94186
  Epoch 021 - train 0.63487 | val 0.93702
  Classification -> best τ=0.430 (val F1=0.1764)
  Directional -> Accuracy: 0.4050, MCC: -0.0444, F1: 0.0775

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.62836 | val 1.20753
  Epoch 020 - train 0.62844 | val 1.27078
  Epoch 021 - train 0.61953 | val 1.27720
  Classification -> best τ=0.400 (val F1=0.2400)
  Directional -> Accuracy: 0.4850, MCC: -0.0419, F1: 0.6386

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65362 | val 1.05477
  Epoch 020 - train 0.63119 | val 1.08451
  Epoch 021 - train 0.63272 | val 1.05323
  Classification -> best τ=0.320 (val F1=0.1285)
  Directional -> Accuracy: 0.5300, MCC: 0.0401, F1: 0.6867

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63697 | val 0.87059
  Epoch 020 - train 0.60527 | val 1.01707
  Epoch 021 - train 0.59974 | val 1.02853
  Classification -> best τ=0.670 (val F1=0.1172)
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.66009 | val 0.69720
  Epoch 020 - train 0.63023 | val 0.73188
  Epoch 021 - train 0.63190 | val 0.73002
  Classification -> best τ=0.530 (val F1=0.1341)
  Directional -> Accuracy: 0.5000, MCC: 0.0076, F1: 0.4737

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63267 | val 1.35009
  Epoch 020 - train 0.61240 | val 1.34608
  Epoch 021 - train 0.60097 | val 1.37873
  Classification -> best τ=0.465 (val F1=0.1972)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63692 | val 1.96864
  Epoch 020 - train 0.60624 | val 2.23279
  Epoch 021 - train 0.59564 | val 2.31992
  Classification -> best τ=0.415 (val F1=0.1668)
  Directional -> Accuracy: 0.5000, MCC: 0.0451, F1: 0.3151

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63379 | val 1.40056
  Epoch 020 - train 0.60052 | val 1.37639
  Epoch 021 - train 0.61198 | val 1.42227
  Classification -> best τ=0.800 (val F1=0.1103)
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64366 | val 0.82736
  Epoch 020 - train 0.59329 | val 0.90459
  Epoch 029 - train 0.55979 | val 1.10819
  Classification -> best τ=0.650 (val F1=0.1745)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.63439 | val 0.95005
  Epoch 020 - train 0.61622 | val 1.11830
  Epoch 021 - train 0.62589 | val 1.12685
  Classification -> best τ=0.625 (val F1=0.1262)
  Directional -> Accuracy: 0.5350, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.64006 | val 1.19126
  Epoch 020 - train 0.58762 | val 0.79087

[I 2026-02-26 03:37:14,771] Trial 32 finished with value: 0.14503592162343962 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 0.0004809969174530884, 'weight_decay': 1.0433910696972495e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.2103490608300456, 'early_stopping_min_delta': 0.0007571563653170648}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 021 - train 0.61608 | val 2.62723
  Classification -> best τ=0.075 (val F1=0.1532)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.6577

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14503592162343962
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68792 | val 1.57221
  Epoch 020 - train 0.65973 | val 2.32057
  Epoch 024 - train 0.60973 | val 2.91080
  Classification -> best τ=0.940 (val F1=0.1695)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.65875 | val 4.24250
  Epoch 020 - train 0.56484 | val 3.58711
  Epoch 024 - train 0.55301 | val 3.47287
  Classification -> best τ=0.100 (val F1=0.1251)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67545 | val 1.32475
  Epoch 020 - train 0.56445 | val 1.80505
  Epoch 021 - train 0.53641 | val 1.80139
  Classification -> best τ=0.445 (val F1=0.1538)
  Directional -> Accuracy: 0.5775, MCC: 0.0000, F1: 0.7322

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.69115 | val 0.69237
  Epoch 020 - train 0.68641 | val 0.68912
  Epoch 030 - train 0.68470 | val 0.71313
  Epoch 038 - train 0.66156 | val 0.79778
  Classification -> best τ=0.530 (val F1=0.1295)
  Directional -> Accuracy: 0.5300, MCC: 0.0324, F1: 0.6017

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.66865 | val 0.69612
  Epoch 020 - train 0.60784 | val 1.00861
  Epoch 023 - train 0.60087 | val 1.24803
  Classification -> best τ=0.630 (val F1=0.1915)
  Directional -> Accuracy: 0.4766, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68321 | val 0.80815
  Epoch 020 - train 0.66968 | val 0.72617
  Epoch 030 - train 0.55595 | val 1.21616
  Epoch 031 - train 0.56605 | val 1.17014
  Classification -> best τ=0.560 (val F1=0.1498)
  Directional -> Accuracy: 0.4300, MCC: -0.1032, F1: 0.0339

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68256 | val 0.68995
  Epoch 020 - train 0.67046 | val 0.71364
  Epoch 021 - train 0.67598 | val 0.70647
  Classification -> best τ=0.775 (val F1=0.1258)
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66600 | val 1.13677
  Epoch 020 - train 0.53978 | val 2.28543
  Epoch 022 - train 0.53295 | val 2.18866
  Classification -> best τ=0.075 (val F1=0.2915)
  Directional -> Accuracy: 0.6250, MCC: 0.1475, F1: 0.7423

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65946 | val 5.43199
  Epoch 020 - train 0.50445 | val 7.99954
  Epoch 021 - train 0.50046 | val 7.29974
  Classification -> best τ=0.210 (val F1=0.2188)
  Directional -> Accuracy: 0.4174, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69592 | val 2.85267
  Epoch 020 - train 0.64244 | val 3.64394
  Epoch 026 - train 0.59555 | val 9.19899
  Classification -> best τ=0.820 (val F1=0.1652)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.68311 | val 0.70239
  Epoch 020 - train 0.67042 | val 0.70599
  Epoch 030 - train 0.64450 | val 1.64694
  Epoch 040 - train 0.55669 | val 2.61396
  Epoch 042 - train 0.52310 | val 4.16307
  Classification -> best τ=0.715 (val F1=0.1463)
  Directional -> Accuracy: 0.4900, MCC: 0.0736, F1: 0.2031

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.70961 | val 0.69188
  Epoch 020 - train 0.67911 | val 0.69273
  Epoch 030 - train 0.62410 | val 0.72308
  Classification -> best τ=0.515 (val F1=0.1036)
  Directional -> Accuracy: 0.4500, MCC: 0.0528, F1: 0.1538

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66978 | val 0.70632
  Epoch 020 - train 0.65137 | val 0.67789
  Epoch 030 - train 0.64056 | val 0.68897
  Epoch 040 - train 0.52558 | val 1.92909
  Classification -> best τ=0.430 (val F1=0.1169)
  Directional -> Accuracy: 0.5150, MCC: -0.0301, F1: 0.6255

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68806 | val 0.93580
  Epoch 020 - train 0.65592 | val 0.74425
  Epoch 030 - train 0.52636 | val 5.03472
  Epoch 031 - train 0.51968 | val 6.64898
  Classification -> best τ=0.570 (val F1=0.1583)
  Directional -> Accuracy: 0.5050, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.68887 | val 0.72624
  Epoch 020 - train 0.67492 | val 0.69835
  Epoch 028 - train 0.68592 | val 0.73148
  Classification -> best τ=0.465 (val F1=0.1204)
  Directional -> Accuracy: 0.4100, MCC: -0.1703, F1: 0.3371

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.68447 | val 1.05769
  Epoch 020 - train 0.55731 | val 3.69862
  Epoch 022 - train 0.55661 | val 4.21447
  Classification -> best τ=0.490 (val F1=0.1479)
  Directional -> Accuracy: 0.5600, MCC: 0.1209, F1: 0.5319

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.69093 | val 0.70036
  Epoch 020 - train 0.69101 | val 0.70881
  Epoch 023 - train 0.66960 | val 0.73945
  Classification -> best τ=0.705 (val F1=0.1925)
  Directional -> Accuracy: 0.5250, MCC: 0.0875, F1: 0.4751

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68195 | val 2.56738
  Epoch 020 - train 0.57230 | val 3.14081
  Epoch 025 - train 0.49876 | val 5.71996
  Classification -> best τ=0.535 (val F1=0.0942)
  Directional -> Accuracy: 0.4800, MCC: -0.0730, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69108 | val 0.81684
  Epoch 020 - train 0.66934 | val 1.10135
  Epoch 030 - train 0.56840 | val 1.69157
  Epoch 033 - train 0.54093 | val 3.08966
  Classification -> best τ=0.300 (val F1=0.1763)
  Directional -> Accuracy: 0.5300, MCC: 0.0693, F1: 0.6240

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69822 | val 0.68857
  Epoch 020 - train 0.64637 | val 1.10950
  Epoch 030 - train 0.59743 | val 1.68710
  Classification -> best τ=0.610 (val F1=0.1603)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.68544 | val 3.33896
  Epoch 020 - train 0.61697 | val 1.44547
  Epoch 022 - train 0.60510 | val 1.89512
  Classification -> best τ=0.200 (val F1=0.0805)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.6577

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.68267 | val 1.56222
  Epoch 020 - train 0.61592 | val 10.29406
  Epoch 021 - train 0.60731 | val 8.26268
  Classification -> best τ=0.345 (val F1=0.1566)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67353 | val 0.70019
  Epoch 020 - train 0.59971 | val 1.32428
  Epoch 026 - train 0.57497 | val 1.97041
  Classification -> best τ=0.400 (val F1=0.2148)
  Directional -> Accuracy: 0.4850, MCC: -0.0105, F1: 0.4492

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.69943 | val 1.00225
  Epoch 020 - train 0.69716 | val 0.79319
  Epoch 030 - train 0.52564 | val 4.06185
  Epoch 031 - train 0.56588 | val 3.21605
  Classification -> best τ=0.665 (val F1=0.1563)
  Directional -> Accuracy: 0.6100, MCC: 0.0687, F1: 0.0930

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67190 | val 1.62857
  Epoch 020 - train 0.56878 | val 2.74154
  Epoch 026 - train 0.52187 | val 5.30162
  Classification -> best τ=0.060 (val F1=0.1579)
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68413 | val 1.20402
  Epoch 020 - train 0.67508 | val 1.24580
  Epoch 025 - train 0.64946 | val 1.15482
  Classification -> best τ=0.430 (val F1=0.1946)
  Directional -> Accuracy: 0.5400, MCC: 0.0870, F1: 0.2459

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69432 | val 0.68490
  Epoch 020 - train 0.60992 | val 3.25097
  Epoch 021 - train 0.60936 | val 2.20420
  Classification -> best τ=0.495 (val F1=0.1792)
  Directional -> Accuracy: 0.5050, MCC: 0.0311, F1: 0.4590

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.69142 | val 0.69133
  Epoch 020 - train 0.63269 | val 0.73921
  Epoch 022 - train 0.62679 | val 0.78911
  Classification -> best τ=0.650 (val F1=0.1487)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68443 | val 0.71731
  Epoch 020 - train 0.68170 | val 0.93233
  Epoch 030 - train 0.61574 | val 1.98282
  Epoch 032 - train 0.60115 | val 2.68861
  Classification -> best τ=0.455 (val F1=0.1013)
  Directional -> Accuracy: 0.4800, MCC: -0.0364, F1: 0.4526

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.68948 | val 0.69865
  Epoch 020 - train 0.64427 | val 0.80990
  Epoch 021 - train 0.64300 | val 0.90386
  Classification -> best τ=0.540 (val F1=0.1847)
  Directional -> Accuracy: 0.4700, MCC: 0.0173, F1: 0.1311

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.69205 | val 0.70829
  Epoch 020 - train 0.68504 | val 0.71538
  Epoch 029 - train 0.61529 | val 0.79523
  Classification -> best τ=0.575 (val F1=0.1741)
  Directional -> Accuracy: 0.4950, MCC: -0.0020, F1: 0.0734

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68203 | val 0.70263
  Epoch 020 - train 0.65924 | val 0.72767
  Epoch 028 - train 0.59094 | val 0.70824
  Classification -> best τ=0.505 (val F1=0.1351)
  Directional -> Accuracy: 0.5700, MCC: 0.0996, F1: 0.7014

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.69797 | val 0.78531
  Epoch 020 - train 0.65755 | val 1.58142
  Epoch 025 - train 0.64976 | val 1.46363
  Classification -> best τ=0.575 (val F1=0.1150)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66102 | val 0.69361
  Epoch 020 - train 0.65422 | val 0.97481
  Epoch 030 - train 0.53427 | val 0.76704
  Classification -> best τ=0.400 (val F1=0.0835)
  Directional -> Accuracy: 0.4650, MCC: 0.0985, F1: 0.6219

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.60376 | val 0.91016
  Epoch 020 - train 0.45606 | val 3.53986
  Epoch 021 - train 0.42442 | val 6.25508
  Classification -> best τ=0.490 (val F1=0.1833)
  Directional -> Accuracy: 0.4583, MCC: -0.1508, F1: 0.0714

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67685 | val 0.69810
  Epoch 020 - train 0.56573 | val 0.89471
  Epoch 021 - train 0.56120 | val 0.85788
  Classification -> best τ=0.660 (val F1=0.2086)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68394 | val 0.74888
  Epoch 020 - train 0.68085 | val 0.70656
  Epoch 029 - train 0.62827 | val 0.77984
  Classification -> best τ=0.545 (val F1=0.1208)
  Directional -> Accuracy: 0.4700, MCC: 0.0661, F1: 0.0185

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.66069 | val 1.48328
  Epoch 020 - train 0.63144 | val 1.44679
  Epoch 029 - train 0.53198 | val 1.32953
  Classification -> best τ=0.180 (val F1=0.1144)
  Directional -> Accuracy: 0.5500, MCC: -0.1083, F1: 0.7097

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.67600 | val 1.41848
  Epoch 020 - train 0.59494 | val 5.00904
  Epoch 021 - train 0.60338 | val 2.89215
  Classification -> best τ=0.365 (val F1=0.0755)
  Directional -> Accuracy: 0.4400, MCC: -0.0879, F1: 0.0667

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.69457 | val 0.76882
  Epoch 020 - train 0.68482 | val 0.73305
  Epoch 030 - train 0.67558 | val 0.78821
  Epoch 037 - train 0.61750 | val 1.04823
  Classification -> best τ=0.515 (val F1=0.0916)
  Directional -> Accuracy: 0.5500, MCC: 0.0883, F1: 0.6642

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.68816 | val 0.69857
  Epoch 020 - train 0.69420 | val 0.69324
  Epoch 030 - train 0.68905 | val 0.79035
  Epoch 036 - train 0.68476 | val 0.96020
  Classification -> best τ=0.485 (val F1=0.2155)
  Directional -> Accuracy: 0.5150, MCC: 0.1018, F1: 0.1849

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68577 | val 1.11369
  Epoch 020 - train 0.65455 | val 1.00818
  Epoch 028 - train 0.60049 | val 1.42648
  Classification -> best τ=0.285 (val F1=0.0978)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68608 | val 0.70578
  Epoch 020 - train 0.66315 | val 0.72463
  Epoch 030 - train 0.63309 | val 1.40168
  Epoch 038 - train 0.53955 | val 1.06357
  Classification -> best τ=0.495 (val F1=0.1502)
  Directional -> Accuracy: 0.5450, MCC: 0.0850, F1: 0.6224

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67496 | val 0.80025
  Epoch 020 - train 0.61172 | val 1.38985
  Epoch 021 - train 0.59534 | val 1.41853
  Classification -> best τ=0.510 (val F1=0.1660)
  Directional -> Accuracy: 0.4850, MCC: -0.0112, F1: 0.3268

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68279 | val 0.87716
  Epoch 020 - train 0.62230 | val 2.72456
  Epoch 030 - train 0.53733 | val 4.70626
  Epoch 032 - train 0.52335 | val 4.32699
  Classification -> best τ=0.375 (val F1=0.1323)
  Directional -> Accuracy: 0.4550, MCC: -0.0590, F1: 0.2378

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68595 | val 1.64410
  Epoch 020 - train 0.64636 | val 0.94482
  Epoch 027 - train 0.64613 | val 1.32732
  Classification -> best τ=0.640 (val F1=0.0386)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70050 | val 0.74342
  Epoch 020 - train 0.62766 | val 0.81600
  Epoch 021 - train 0.61307 | val 1.05699
  Classification -> best τ=0.630 (val F1=0.1367)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68788 | val 0.69349
  Epoch 020 - train 0.66158 | val 0.98652
  Epoch 030 - train 0.53647 | val 0.84909
  Classification -> best τ=0.470 (val F1=0.1169)
  Directional -> Accuracy: 0.3800, MCC: -0.1344, F1: 0.1842

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67350 | val 1.74096
  Epoch 020 - train 0.61413 | val 3.49770
  Epoch 023 - train 0.57676 | val 1.73783
  Classification -> best τ=0.395 (val F1=0.1396)
  Directional -> Accuracy: 0.4850, MCC: -0.0235, F1: 0.6308

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68766 | val 0.82691
  Epoch 020 - train 0.64523 | val 0.75748
  Epoch 030 - train 0.61716 | val 0.78947
  Epoch 037 - train 0.56382 | val 1.30259
  Classification -> best τ=0.500 (val F1=0.1758)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69320 | val 0.68722
  Epoch 020 - train 0.68421 | val 0.68653
  Epoch 025 - train 0.66843 | val 0.76525
  Classification -> best τ=0.565 (val F1=0.1556)
  Directional -> Accuracy: 0.4300, MCC: -0.0778, F1: 0.1857

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68891 | val 1.31980
  Epoch 020 - train 0.61690 | val 2.48319
  Epoch 021 - train 0.61020 | val 2.74408
  Classification -> best τ=0.755 (val F1=0.1155)
  Directional -> Accuracy: 0.4950, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69088 | val 0.74455
  Epoch 020 - train 0.62920 | val 0.72181
  Epoch 025 - train 0.60521 | val 0.69533
  Classification -> best τ=0.465 (val F1=0.1658)
  Directional -> Accuracy: 0.5350, MCC: 0.0653, F1: 0.5830

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.68988 | val 0.77107
  Epoch 020 - train 0.68240 | val 0.68926
  Epoch 026 - train 0.67479 | val 0.68913
  Classification -> best τ=0.590 (val F1=0.1128)
  Directional -> Accuracy: 0.4100, MCC: -0.0174, F1: 0.0781

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.67400 | val 0.79017
  Epoch 020 - train 0.60204 | val 0.75658
  Epoch 024 - train 0.54652 | val 0.89469
  Classification -> best τ=0.565 (val F1=0.2616)
  Directional -> Accuracy: 0.5050, MCC: 0.0000, F1: 0.0000

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.69453 | val 1.50233
  Epoch 020 - train 0.69363 | val 1.56005
  Epoch 030 - train 0.64797 | val 13.89403
  Epoch 032 - train 0.63923 | val 13.58950
  Classification -> best τ=0.200 (val F1=0.1186)
  Directional -> Accuracy: 0.5700, MCC: 0.2097, F1: 0.7075

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68678 | val 1.24051
  Epoch 020 - train 0.63850 | val 1.71461
  Epoch 025 - train 0.59262 | val 2.64529
  Classification -> best τ=0.420 (val F1=0.1456)
  Directional -> Accuracy: 0.4550, MCC: 0.0161, F1: 0.0522

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.68680 | val 0.69384
  Epoch 020 - train 0.68978 | val 0.70640
  Epoch 030 - train 0.65510 | val 1.09954
  Epoch 038 - train 0.58413 | val 1.09747
  Classification -> best τ=0.430 (val F1=0.2764)
  Directional -> Accuracy: 0.5000, MCC: 0.0045, F1: 0.4898

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67210 | val 1.30290
  Epoch 020 - train 0.64228 | val 2.21306
  Epoch 030 - train 0.50473 | val 2.76677
  Epoch 031 - train 0.53568 | val 2.57818
  Classification -> best τ=0.495 (val F1=0.2188)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67104 | val 0.69202
  Epoch 020 - train 0.65187 | val 1.24501
  Epoch 029 - train 0.54114 | val 3.81034
  Classification -> best τ=0.550 (val F1=0.2320)
  Directional -> Accuracy: 0.5000, MCC: 0.0428, F1: 0.3243

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67842 | val 1.03778
  Epoch 020 - train 0.60644 | val 3.91033
  Epoch 021 - train 0.60314 | val 1.23375
  Classification -> best τ=0.700 (val F1=0.0352)
  Directional -> Accuracy: 0.5250, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...


[I 2026-02-26 03:50:27,957] Trial 33 finished with value: 0.14969332914405198 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.007919018127625983, 'weight_decay': 4.090434604866462e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.446692770653681, 'early_stopping_min_delta': 0.0007175963405632966}. Best is trial 8 with value: 0.15238950933016568.

  Epoch 033 - train 0.53661 | val 4.81860
  Classification -> best τ=0.050 (val F1=0.1236)
  Directional -> Accuracy: 0.4900, MCC: -0.0020, F1: 0.6554

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14969332914405198
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63777 | val 1.07100
  Epoch 020 - train 0.51383 | val 2.01162
  Epoch 023 - train 0.49406 | val 1.93467
  Classification -> best τ=0.285 (val F1=0.1446)
  Directional -> Accuracy: 0.4350, MCC: 0.0042, F1: 0.1871

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.60558 | val 7.46887
  Epoch 020 - train 0.38373 | val 15.57305
  Epoch 021 - train 0.37290 | val 16.54824
  Classification -> best τ=0.415 (val F1=0.1736)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62677 | val 1.09884
  Epoch 020 - train 0.48113 | val 3.00970
  Epoch 022 - train 0.42888 | val 2.73076
  Classification -> best τ=0.215 (val F1=0.1329)
  Directional -> Accuracy: 0.5775, MCC: 0.0000, F1: 0.7322

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.64981 | val 0.73024
  Epoch 020 - train 0.50455 | val 1.79066
  Epoch 022 - train 0.52371 | val 1.55466
  Classification -> best τ=0.620 (val F1=0.1624)
  Directional -> Accuracy: 0.4400, MCC: -0.0488, F1: 0.2000

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.56574 | val 0.86821
  Epoch 020 - train 0.50791 | val 1.97565
  Epoch 021 - train 0.48141 | val 2.17619
  Classification -> best τ=0.435 (val F1=0.1367)
  Directional -> Accuracy: 0.5234, MCC: 0.0438, F1: 0.5487

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64648 | val 1.23552
  Epoch 020 - train 0.47444 | val 3.22742
  Epoch 021 - train 0.44673 | val 5.00133
  Classification -> best τ=0.145 (val F1=0.1112)
  Directional -> Accuracy: 0.5250, MCC: -0.0112, F1: 0.6415

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65188 | val 1.56810
  Epoch 020 - train 0.57012 | val 2.24218
  Epoch 021 - train 0.54732 | val 3.17703
  Classification -> best τ=0.190 (val F1=0.1906)
  Directional -> Accuracy: 0.5750, MCC: 0.0991, F1: 0.7195

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63301 | val 1.47126
  Epoch 020 - train 0.42765 | val 2.37502
  Epoch 024 - train 0.38830 | val 2.79951
  Classification -> best τ=0.400 (val F1=0.2634)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60994 | val 2.38254
  Epoch 020 - train 0.37681 | val 5.89938
  Epoch 021 - train 0.39029 | val 5.52224
  Classification -> best τ=0.210 (val F1=0.1352)
  Directional -> Accuracy: 0.4174, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63624 | val 1.70788
  Epoch 020 - train 0.50444 | val 4.70288
  Epoch 021 - train 0.48517 | val 3.87414
  Classification -> best τ=0.735 (val F1=0.0873)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.62431 | val 0.77674
  Epoch 020 - train 0.60444 | val 0.77191
  Epoch 030 - train 0.39412 | val 1.55282
  Epoch 036 - train 0.33029 | val 1.88807
  Classification -> best τ=0.710 (val F1=0.2529)
  Directional -> Accuracy: 0.5200, MCC: 0.0592, F1: 0.4839

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.62298 | val 0.73666
  Epoch 020 - train 0.51632 | val 0.81064
  Epoch 021 - train 0.48390 | val 1.39046
  Classification -> best τ=0.610 (val F1=0.1608)
  Directional -> Accuracy: 0.4250, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61604 | val 1.23449
  Epoch 020 - train 0.51747 | val 2.49490
  Epoch 021 - train 0.49274 | val 3.18163
  Classification -> best τ=0.500 (val F1=0.2009)
  Directional -> Accuracy: 0.4750, MCC: -0.0160, F1: 0.4262

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62572 | val 1.83433
  Epoch 020 - train 0.45451 | val 3.71330
  Epoch 021 - train 0.44063 | val 4.31039
  Classification -> best τ=0.765 (val F1=0.1327)
  Directional -> Accuracy: 0.5100, MCC: 0.0183, F1: 0.4494

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.65921 | val 0.83674
  Epoch 020 - train 0.56054 | val 1.46941
  Epoch 023 - train 0.49691 | val 2.31930
  Classification -> best τ=0.440 (val F1=0.0716)
  Directional -> Accuracy: 0.4600, MCC: -0.0546, F1: 0.2500

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.63134 | val 2.68963
  Epoch 020 - train 0.44961 | val 6.66903
  Epoch 021 - train 0.45843 | val 9.67528
  Classification -> best τ=0.525 (val F1=0.1622)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.63363 | val 0.85666
  Epoch 020 - train 0.46994 | val 1.85816
  Epoch 024 - train 0.38984 | val 1.84682
  Classification -> best τ=0.445 (val F1=0.1816)
  Directional -> Accuracy: 0.5550, MCC: 0.0000, F1: 0.7138

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59188 | val 2.33013
  Epoch 020 - train 0.35999 | val 1.81530
  Epoch 021 - train 0.37047 | val 2.08506
  Classification -> best τ=0.400 (val F1=0.1563)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61903 | val 1.35659
  Epoch 020 - train 0.45211 | val 1.88408
  Epoch 023 - train 0.41173 | val 2.80708
  Classification -> best τ=0.535 (val F1=0.2832)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63384 | val 1.19006
  Epoch 020 - train 0.49114 | val 1.46155
  Epoch 021 - train 0.48280 | val 1.21321
  Classification -> best τ=0.220 (val F1=0.1513)
  Directional -> Accuracy: 0.4900, MCC: 0.0325, F1: 0.3200

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.62513 | val 1.28878
  Epoch 020 - train 0.44571 | val 2.95190
  Epoch 023 - train 0.39457 | val 3.76962
  Classification -> best τ=0.225 (val F1=0.1116)
  Directional -> Accuracy: 0.4900, MCC: 0.0000, F1: 0.6577

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.63708 | val 3.18792
  Epoch 020 - train 0.47225 | val 8.22995
  Epoch 021 - train 0.49550 | val 9.38529
  Classification -> best τ=0.230 (val F1=0.1848)
  Directional -> Accuracy: 0.4400, MCC: 0.0253, F1: 0.0345

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62170 | val 1.84899
  Epoch 020 - train 0.48779 | val 2.90079
  Epoch 021 - train 0.49781 | val 3.65954
  Classification -> best τ=0.370 (val F1=0.1559)
  Directional -> Accuracy: 0.4850, MCC: 0.0151, F1: 0.3602

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.65831 | val 1.12066
  Epoch 020 - train 0.52878 | val 2.25273
  Epoch 021 - train 0.51284 | val 2.32086
  Classification -> best τ=0.280 (val F1=0.1124)
  Directional -> Accuracy: 0.4000, MCC: -0.0569, F1: 0.5349

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60338 | val 1.35981
  Epoch 020 - train 0.41075 | val 3.81213
  Epoch 025 - train 0.36990 | val 7.13343
  Classification -> best τ=0.085 (val F1=0.2127)
  Directional -> Accuracy: 0.5250, MCC: 0.0301, F1: 0.6619

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65488 | val 1.16676
  Epoch 020 - train 0.53302 | val 1.75586
  Epoch 021 - train 0.53662 | val 3.75217
  Classification -> best τ=0.450 (val F1=0.2118)
  Directional -> Accuracy: 0.5400, MCC: 0.0772, F1: 0.5054

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62765 | val 0.85187
  Epoch 020 - train 0.47242 | val 2.53779
  Epoch 022 - train 0.46294 | val 2.59273
  Classification -> best τ=0.655 (val F1=0.1593)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.65363 | val 0.85178
  Epoch 020 - train 0.49641 | val 2.97638
  Epoch 022 - train 0.48148 | val 2.55718
  Classification -> best τ=0.490 (val F1=0.1504)
  Directional -> Accuracy: 0.4900, MCC: -0.0273, F1: 0.2273

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64782 | val 0.91170
  Epoch 020 - train 0.51914 | val 2.53800
  Epoch 022 - train 0.53525 | val 1.91353
  Classification -> best τ=0.390 (val F1=0.1248)
  Directional -> Accuracy: 0.4900, MCC: -0.0387, F1: 0.5920

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.66725 | val 0.78185
  Epoch 020 - train 0.49020 | val 1.05296
  Epoch 026 - train 0.35595 | val 1.50080
  Classification -> best τ=0.510 (val F1=0.1393)
  Directional -> Accuracy: 0.4250, MCC: -0.1314, F1: 0.1727

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.62275 | val 3.95233
  Epoch 020 - train 0.44888 | val 7.10401
  Epoch 021 - train 0.43232 | val 8.86289
  Classification -> best τ=0.290 (val F1=0.1584)
  Directional -> Accuracy: 0.4900, MCC: -0.0336, F1: 0.0377

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65430 | val 0.94709
  Epoch 020 - train 0.53698 | val 1.09461
  Epoch 027 - train 0.41768 | val 2.68000
  Classification -> best τ=0.665 (val F1=0.1632)
  Directional -> Accuracy: 0.4250, MCC: -0.1132, F1: 0.1606

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.64341 | val 1.45432
  Epoch 020 - train 0.57182 | val 2.55038
  Epoch 021 - train 0.53279 | val 2.51207
  Classification -> best τ=0.105 (val F1=0.1678)
  Directional -> Accuracy: 0.5750, MCC: -0.0307, F1: 0.7176

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61318 | val 0.70558
  Epoch 020 - train 0.45388 | val 1.17416
  Epoch 026 - train 0.39197 | val 1.60814
  Classification -> best τ=0.600 (val F1=0.0702)
  Directional -> Accuracy: 0.5600, MCC: 0.0642, F1: 0.2903

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.54671 | val 3.46714
  Epoch 020 - train 0.33896 | val 5.39031
  Epoch 021 - train 0.32704 | val 5.85061
  Classification -> best τ=0.450 (val F1=0.1903)
  Directional -> Accuracy: 0.4792, MCC: -0.0417, F1: 0.4681

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62830 | val 1.04677
  Epoch 020 - train 0.46295 | val 2.71908
  Epoch 021 - train 0.46484 | val 3.12785
  Classification -> best τ=0.475 (val F1=0.2043)
  Directional -> Accuracy: 0.4200, MCC: 0.0597, F1: 0.0169

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65393 | val 1.12852
  Epoch 020 - train 0.50658 | val 2.44189
  Epoch 023 - train 0.46577 | val 2.57922
  Classification -> best τ=0.695 (val F1=0.1937)
  Directional -> Accuracy: 0.4700, MCC: 0.0661, F1: 0.0185

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.63082 | val 1.31334
  Epoch 020 - train 0.46060 | val 1.97449
  Epoch 024 - train 0.45734 | val 1.93882
  Classification -> best τ=0.090 (val F1=0.1624)
  Directional -> Accuracy: 0.4600, MCC: 0.0504, F1: 0.1692

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.64213 | val 2.16560
  Epoch 020 - train 0.46913 | val 4.92482
  Epoch 023 - train 0.42150 | val 5.10057
  Classification -> best τ=0.940 (val F1=0.0882)
  Directional -> Accuracy: 0.4550, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.63434 | val 1.37652
  Epoch 020 - train 0.50810 | val 3.31311
  Epoch 022 - train 0.43581 | val 3.49792
  Classification -> best τ=0.570 (val F1=0.1322)
  Directional -> Accuracy: 0.4800, MCC: -0.0376, F1: 0.4800

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.64446 | val 1.32523
  Epoch 020 - train 0.49948 | val 5.86741
  Epoch 022 - train 0.49551 | val 3.47987
  Classification -> best τ=0.580 (val F1=0.1667)
  Directional -> Accuracy: 0.4900, MCC: 0.0272, F1: 0.0556

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64069 | val 1.26861
  Epoch 020 - train 0.49394 | val 2.83278
  Epoch 023 - train 0.46505 | val 3.54007
  Classification -> best τ=0.240 (val F1=0.1698)
  Directional -> Accuracy: 0.5500, MCC: 0.0613, F1: 0.6939

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67412 | val 0.91550
  Epoch 020 - train 0.52710 | val 2.08287
  Epoch 023 - train 0.48540 | val 2.96374
  Classification -> best τ=0.330 (val F1=0.1716)
  Directional -> Accuracy: 0.5000, MCC: 0.0387, F1: 0.1935

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62446 | val 1.81820
  Epoch 020 - train 0.45639 | val 5.82643
  Epoch 021 - train 0.43870 | val 6.75623
  Classification -> best τ=0.645 (val F1=0.0908)
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63200 | val 2.46413
  Epoch 020 - train 0.45305 | val 6.31912
  Epoch 021 - train 0.45206 | val 8.06424
  Classification -> best τ=0.050 (val F1=0.0636)
  Directional -> Accuracy: 0.5000, MCC: -0.0213, F1: 0.5763

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64330 | val 1.05883
  Epoch 020 - train 0.50458 | val 1.48076
  Epoch 024 - train 0.48993 | val 1.78875
  Classification -> best τ=0.785 (val F1=0.0860)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64520 | val 1.45014
  Epoch 020 - train 0.47037 | val 2.40880
  Epoch 022 - train 0.50445 | val 2.23648
  Classification -> best τ=0.285 (val F1=0.1334)
  Directional -> Accuracy: 0.4750, MCC: 0.0481, F1: 0.2857

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63902 | val 1.22504
  Epoch 020 - train 0.40000 | val 2.32977
  Epoch 024 - train 0.36298 | val 2.51591
  Classification -> best τ=0.225 (val F1=0.1297)
  Directional -> Accuracy: 0.5150, MCC: -0.1013, F1: 0.6473

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62719 | val 1.39041
  Epoch 020 - train 0.51165 | val 3.27034
  Epoch 022 - train 0.45495 | val 4.12892
  Classification -> best τ=0.260 (val F1=0.1578)
  Directional -> Accuracy: 0.5350, MCC: 0.0991, F1: 0.6353

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63368 | val 1.26920
  Epoch 020 - train 0.56039 | val 0.92663
  Epoch 030 - train 0.45930 | val 1.02500
  Epoch 033 - train 0.42287 | val 0.94619
  Classification -> best τ=0.725 (val F1=0.1478)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64313 | val 1.01279
  Epoch 020 - train 0.53778 | val 1.50018
  Epoch 027 - train 0.46347 | val 1.86752
  Classification -> best τ=0.325 (val F1=0.1469)
  Directional -> Accuracy: 0.4800, MCC: 0.0673, F1: 0.2571

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64888 | val 1.30262
  Epoch 020 - train 0.48759 | val 2.98494
  Epoch 021 - train 0.48952 | val 2.28068
  Classification -> best τ=0.570 (val F1=0.1184)
  Directional -> Accuracy: 0.4950, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64024 | val 0.75295
  Epoch 020 - train 0.47617 | val 1.78320
  Epoch 021 - train 0.49477 | val 2.04144
  Classification -> best τ=0.615 (val F1=0.1138)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.64720 | val 0.79914
  Epoch 020 - train 0.48469 | val 2.22546
  Epoch 024 - train 0.43721 | val 2.31823
  Classification -> best τ=0.650 (val F1=0.1607)
  Directional -> Accuracy: 0.4000, MCC: -0.0636, F1: 0.0323

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.61391 | val 0.96674
  Epoch 020 - train 0.44324 | val 2.46971
  Epoch 021 - train 0.44193 | val 2.58099
  Classification -> best τ=0.435 (val F1=0.1592)
  Directional -> Accuracy: 0.4850, MCC: -0.0446, F1: 0.6411

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.65480 | val 2.29349
  Epoch 020 - train 0.52384 | val 5.92788
  Epoch 021 - train 0.52918 | val 6.35638
  Classification -> best τ=0.700 (val F1=0.1046)
  Directional -> Accuracy: 0.4500, MCC: -0.1016, F1: 0.1129

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61824 | val 1.55214
  Epoch 020 - train 0.46915 | val 2.44262
  Epoch 025 - train 0.39712 | val 3.58127
  Classification -> best τ=0.745 (val F1=0.1400)
  Directional -> Accuracy: 0.4450, MCC: -0.0465, F1: 0.0513

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.65913 | val 0.73075
  Epoch 020 - train 0.51133 | val 1.52537
  Epoch 021 - train 0.49213 | val 1.41361
  Classification -> best τ=0.510 (val F1=0.2078)
  Directional -> Accuracy: 0.4750, MCC: -0.0137, F1: 0.1176

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62552 | val 0.88853
  Epoch 020 - train 0.45868 | val 2.28398
  Epoch 021 - train 0.47417 | val 1.46201
  Classification -> best τ=0.110 (val F1=0.2099)
  Directional -> Accuracy: 0.5250, MCC: 0.0303, F1: 0.5852

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60586 | val 2.14030
  Epoch 020 - train 0.46555 | val 4.71504
  Epoch 021 - train 0.42148 | val 6.22942
  Classification -> best τ=0.340 (val F1=0.1854)
  Directional -> Accuracy: 0.4900, MCC: 0.0363, F1: 0.2273

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62378 | val 2.63319
  Epoch 020 - train 0.45155 | val 4.85083
  Epoch 021 - train 0.43303 | val 5.44358
  Classification -> best τ=0.070 (val F1=0.1046)
  Directional -> Accuracy: 0.4750, MCC: -0.0050, F1: 0.6416

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64266 | val 1.37291
  Epoch 020 - train 0.50096 | val 1.95939
  Epoch 021 - train 0.47899 | val 1.58232
  Classification -> best τ=0.320 (val F1=0.1332)
  Directional -> Accuracy: 0.4750, MCC: -0.0706, F1: 0.0708

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.64279 | val 1.42995
  Epoch 020 - train 0.47903 | val 0.88504
  Epoch 022 - train 0.45096 | val 0.92650
  Classification -> best τ=0.650 (val F1=0.1262)
  Directional -> Accuracy: 0.5350, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...

[I 2026-02-26 04:01:08,710] Trial 34 finished with value: 0.15332516303987392 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.0032286688198796014, 'weight_decay': 1.5994962291372579e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.160201403580957, 'early_stopping_min_delta': 0.0018371313157506675}. Best is trial 34 with value: 0.15332516303987392.

  Epoch 021 - train 0.48455 | val 4.22024
  Classification -> best τ=0.325 (val F1=0.1611)
  Directional -> Accuracy: 0.5100, MCC: 0.0267, F1: 0.5664

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.15332516303987392
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64122 | val 1.60414
  Epoch 016 - train 0.59564 | val 1.34256
  Classification -> best τ=0.415 (val F1=0.1429)
  Directional -> Accuracy: 0.4300, MCC: -0.0040, F1: 0.1618

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.61093 | val 2.54100
  Epoch 016 - train 0.51026 | val 5.52697
  Classification -> best τ=0.105 (val F1=0.1230)
  Directional -> Accuracy: 0.5300, MCC: 0.0702, F1: 0.3649

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61858 | val 0.92449
  Epoch 016 - train 0.57648 | val 1.15702
  Classification -> best τ=0.615 (val F1=0.1066)
  Directional -> Accuracy: 0.4545, MCC: 0.0681, F1: 0.1774

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.65983 | val 0.78438
  Epoch 017 - train 0.60610 | val 1.68222
  Classification -> best τ=0.460 (val F1=0.1497)
  Directional -> Accuracy: 0.5500, MCC: 0.0067, F1: 0.6918

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.56297 | val 2.03058
  Epoch 016 - train 0.56135 | val 1.92710
  Classification -> best τ=0.455 (val F1=0.0962)
  Directional -> Accuracy: 0.4953, MCC: 0.0083, F1: 0.4000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64684 | val 0.71772
  Epoch 020 - train 0.55190 | val 1.19720
  Classification -> best τ=0.735 (val F1=0.1517)
  Directional -> Accuracy: 0.4600, MCC: 0.0204, F1: 0.1562

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65140 | val 1.69768
  Epoch 018 - train 0.60286 | val 1.75877
  Classification -> best τ=0.485 (val F1=0.1222)
  Directional -> Accuracy: 0.4850, MCC: 0.0076, F1: 0.4309

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62356 | val 0.90351
  Epoch 016 - train 0.55393 | val 1.13521
  Classification -> best τ=0.420 (val F1=0.2650)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.56240 | val 4.21655
  Epoch 016 - train 0.51011 | val 3.65710
  Classification -> best τ=0.440 (val F1=0.1831)
  Directional -> Accuracy: 0.4348, MCC: 0.0235, F1: 0.1333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63838 | val 1.69829
  Epoch 016 - train 0.58208 | val 1.77263
  Classification -> best τ=0.260 (val F1=0.1150)
  Directional -> Accuracy: 0.4400, MCC: -0.0914, F1: 0.5821

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.64741 | val 0.84293
  Epoch 018 - train 0.58444 | val 0.86642
  Classification -> best τ=0.585 (val F1=0.2086)
  Directional -> Accuracy: 0.4800, MCC: -0.0137, F1: 0.4023

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.62874 | val 0.83480
  Epoch 016 - train 0.58900 | val 0.91618
  Classification -> best τ=0.515 (val F1=0.1294)
  Directional -> Accuracy: 0.4250, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62510 | val 1.08405
  Epoch 020 - train 0.57443 | val 0.74977
  Classification -> best τ=0.505 (val F1=0.1360)
  Directional -> Accuracy: 0.4650, MCC: 0.0073, F1: 0.2819

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61654 | val 1.13444
  Epoch 016 - train 0.55998 | val 1.07456
  Classification -> best τ=0.555 (val F1=0.1828)
  Directional -> Accuracy: 0.4900, MCC: -0.0385, F1: 0.2031

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.64858 | val 1.05061
  Epoch 016 - train 0.63610 | val 1.40213
  Classification -> best τ=0.115 (val F1=0.1029)
  Directional -> Accuracy: 0.5000, MCC: -0.0366, F1: 0.6124

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.61925 | val 1.83589
  Epoch 016 - train 0.55348 | val 3.78998
  Classification -> best τ=0.305 (val F1=0.1628)
  Directional -> Accuracy: 0.4800, MCC: -0.0576, F1: 0.1875

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.64771 | val 0.78533
  Epoch 016 - train 0.57765 | val 1.34472
  Classification -> best τ=0.550 (val F1=0.0949)
  Directional -> Accuracy: 0.5750, MCC: 0.1026, F1: 0.6996

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57957 | val 1.67509
  Epoch 016 - train 0.47627 | val 3.71000
  Classification -> best τ=0.825 (val F1=0.0918)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62551 | val 0.95823
  Epoch 016 - train 0.55924 | val 1.28275
  Classification -> best τ=0.415 (val F1=0.2638)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63648 | val 0.88640
  Epoch 016 - train 0.59476 | val 1.20653
  Classification -> best τ=0.475 (val F1=0.1038)
  Directional -> Accuracy: 0.4650, MCC: -0.0089, F1: 0.1575

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.65753 | val 0.79160
  Epoch 016 - train 0.59352 | val 1.02800
  Classification -> best τ=0.660 (val F1=0.1355)
  Directional -> Accuracy: 0.5550, MCC: 0.1087, F1: 0.5291

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.64496 | val 3.24696
  Epoch 016 - train 0.57787 | val 3.91093
  Classification -> best τ=0.235 (val F1=0.1866)
  Directional -> Accuracy: 0.5550, MCC: 0.0593, F1: 0.6537

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63702 | val 0.94806
  Epoch 016 - train 0.60137 | val 1.53687
  Classification -> best τ=0.570 (val F1=0.1118)
  Directional -> Accuracy: 0.4850, MCC: -0.0013, F1: 0.4181

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.63330 | val 0.99329
  Epoch 016 - train 0.57137 | val 1.06238
  Classification -> best τ=0.340 (val F1=0.1274)
  Directional -> Accuracy: 0.4100, MCC: -0.0348, F1: 0.5354

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59787 | val 1.79606
  Epoch 020 - train 0.49296 | val 2.89276
  Classification -> best τ=0.285 (val F1=0.1312)
  Directional -> Accuracy: 0.5350, MCC: 0.0586, F1: 0.6593

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65318 | val 0.82678
  Epoch 016 - train 0.61012 | val 1.06686
  Classification -> best τ=0.490 (val F1=0.0943)
  Directional -> Accuracy: 0.5500, MCC: 0.1415, F1: 0.1964

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65696 | val 0.70496
  Epoch 020 - train 0.57973 | val 0.87663
  Classification -> best τ=0.520 (val F1=0.2175)
  Directional -> Accuracy: 0.5200, MCC: 0.1239, F1: 0.3239

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.63873 | val 1.16235
  Epoch 016 - train 0.60858 | val 1.49989
  Classification -> best τ=0.340 (val F1=0.1338)
  Directional -> Accuracy: 0.4850, MCC: -0.0316, F1: 0.5541

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64527 | val 0.97587
  Epoch 016 - train 0.59007 | val 1.77027
  Classification -> best τ=0.525 (val F1=0.1033)
  Directional -> Accuracy: 0.5100, MCC: 0.0317, F1: 0.4235

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.64866 | val 0.77822
  Epoch 016 - train 0.58277 | val 0.81571
  Classification -> best τ=0.605 (val F1=0.0865)
  Directional -> Accuracy: 0.5300, MCC: 0.0115, F1: 0.6544

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.64253 | val 1.04358
  Epoch 016 - train 0.57222 | val 1.32319
  Classification -> best τ=0.470 (val F1=0.0904)
  Directional -> Accuracy: 0.4950, MCC: -0.0569, F1: 0.6576

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65483 | val 1.03449
  Epoch 019 - train 0.57952 | val 0.99846
  Classification -> best τ=0.485 (val F1=0.1407)
  Directional -> Accuracy: 0.5450, MCC: -0.0289, F1: 0.7036

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.65299 | val 1.07791
  Epoch 016 - train 0.63007 | val 1.49222
  Classification -> best τ=0.580 (val F1=0.1230)
  Directional -> Accuracy: 0.3950, MCC: 0.0000, F1: 0.0000

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60382 | val 0.72649
  Epoch 016 - train 0.52050 | val 0.75057
  Classification -> best τ=0.535 (val F1=0.1010)
  Directional -> Accuracy: 0.4500, MCC: -0.0335, F1: 0.5736

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.56520 | val 1.27250
  Epoch 016 - train 0.54400 | val 1.61452
  Classification -> best τ=0.500 (val F1=0.3625)
  Directional -> Accuracy: 0.5625, MCC: 0.1348, F1: 0.6316

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62235 | val 1.07531
  Epoch 016 - train 0.56846 | val 1.29299
  Classification -> best τ=0.355 (val F1=0.2483)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64447 | val 0.77279
  Epoch 016 - train 0.60517 | val 0.84581
  Classification -> best τ=0.560 (val F1=0.2267)
  Directional -> Accuracy: 0.4650, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.61432 | val 1.75437
  Epoch 016 - train 0.53916 | val 2.06568
  Classification -> best τ=0.315 (val F1=0.1144)
  Directional -> Accuracy: 0.5600, MCC: 0.0651, F1: 0.6641

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.64557 | val 1.52661
  Epoch 016 - train 0.57445 | val 2.39036
  Classification -> best τ=0.565 (val F1=0.0866)
  Directional -> Accuracy: 0.4400, MCC: -0.0815, F1: 0.1111

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.66049 | val 1.19995
  Epoch 016 - train 0.61364 | val 1.29577
  Classification -> best τ=0.570 (val F1=0.1400)
  Directional -> Accuracy: 0.4750, MCC: -0.0185, F1: 0.1860

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.64509 | val 1.34835
  Epoch 016 - train 0.62230 | val 1.37527
  Classification -> best τ=0.380 (val F1=0.1015)
  Directional -> Accuracy: 0.5150, MCC: 0.0000, F1: 0.6799

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65355 | val 0.98659
  Epoch 016 - train 0.60769 | val 1.68124
  Classification -> best τ=0.230 (val F1=0.1013)
  Directional -> Accuracy: 0.5500, MCC: 0.0603, F1: 0.6897

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65607 | val 0.75866
  Epoch 020 - train 0.58111 | val 0.78378
  Classification -> best τ=0.675 (val F1=0.1414)
  Directional -> Accuracy: 0.4850, MCC: -0.0053, F1: 0.0550

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64638 | val 1.55433
  Epoch 016 - train 0.57227 | val 2.75040
  Classification -> best τ=0.615 (val F1=0.1415)
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60047 | val 2.32589
  Epoch 016 - train 0.53263 | val 3.28839
  Classification -> best τ=0.215 (val F1=0.1284)
  Directional -> Accuracy: 0.5450, MCC: 0.0567, F1: 0.6807

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63851 | val 1.00974
  Epoch 016 - train 0.58238 | val 1.22074
  Classification -> best τ=0.310 (val F1=0.0483)
  Directional -> Accuracy: 0.5850, MCC: 0.0575, F1: 0.7205

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63922 | val 0.80862
  Epoch 016 - train 0.58144 | val 1.14720
  Classification -> best τ=0.430 (val F1=0.0808)
  Directional -> Accuracy: 0.5650, MCC: 0.0000, F1: 0.7220

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64022 | val 1.11240
  Epoch 020 - train 0.47963 | val 1.32479
  Classification -> best τ=0.220 (val F1=0.1493)
  Directional -> Accuracy: 0.4750, MCC: 0.0186, F1: 0.4444

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62237 | val 1.59741
  Epoch 016 - train 0.57165 | val 1.75666
  Classification -> best τ=0.560 (val F1=0.1438)
  Directional -> Accuracy: 0.5200, MCC: 0.0347, F1: 0.3333

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65177 | val 1.31199
  Epoch 016 - train 0.59615 | val 1.44851
  Classification -> best τ=0.210 (val F1=0.1089)
  Directional -> Accuracy: 0.5550, MCC: -0.0882, F1: 0.7138

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65268 | val 0.91198
  Epoch 018 - train 0.62338 | val 1.00244
  Classification -> best τ=0.430 (val F1=0.1012)
  Directional -> Accuracy: 0.5700, MCC: 0.0778, F1: 0.6972

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61233 | val 1.25352
  Epoch 016 - train 0.58842 | val 1.60584
  Classification -> best τ=0.510 (val F1=0.0960)
  Directional -> Accuracy: 0.4900, MCC: -0.0424, F1: 0.0192

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64964 | val 0.81717
  Epoch 020 - train 0.52389 | val 0.81346
  Classification -> best τ=0.640 (val F1=0.1267)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.63372 | val 0.76621
  Epoch 016 - train 0.59788 | val 1.00764
  Classification -> best τ=0.535 (val F1=0.1865)
  Directional -> Accuracy: 0.4100, MCC: 0.0180, F1: 0.0328

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.63543 | val 0.84379
  Epoch 016 - train 0.58691 | val 1.11056
  Classification -> best τ=0.435 (val F1=0.1535)
  Directional -> Accuracy: 0.4950, MCC: -0.0010, F1: 0.6599

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64732 | val 1.03485
  Epoch 017 - train 0.60194 | val 1.03587
  Classification -> best τ=0.330 (val F1=0.1186)
  Directional -> Accuracy: 0.5400, MCC: 0.1042, F1: 0.6933

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63863 | val 1.31126
  Epoch 016 - train 0.58476 | val 1.52293
  Classification -> best τ=0.140 (val F1=0.0709)
  Directional -> Accuracy: 0.5700, MCC: 0.1064, F1: 0.7095

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.66458 | val 0.71265
  Epoch 019 - train 0.58324 | val 0.93003
  Classification -> best τ=0.475 (val F1=0.1133)
  Directional -> Accuracy: 0.5300, MCC: 0.0335, F1: 0.6781

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62586 | val 1.09693
  Epoch 016 - train 0.54802 | val 1.43903
  Classification -> best τ=0.590 (val F1=0.1836)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62496 | val 1.60989
  Epoch 016 - train 0.57030 | val 1.79478
  Classification -> best τ=0.315 (val F1=0.1099)
  Directional -> Accuracy: 0.5450, MCC: 0.0920, F1: 0.5517

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63781 | val 1.38997
  Epoch 016 - train 0.56121 | val 2.13590
  Classification -> best τ=0.150 (val F1=0.1046)
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.6441

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64105 | val 0.74572
  Epoch 019 - train 0.53566 | val 0.88862
  Classification -> best τ=0.390 (val F1=0.2080)
  Directional -> Accuracy: 0.4850, MCC: -0.0723, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.64347 | val 0.75328
  Epoch 020 - train 0.60631 | val 0.86339
  Classification -> best τ=0.615 (val F1=0.1262)
  Directional -> Accuracy: 0.5350, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.60326 | val 1.41496
  Epoch 016 - train 0.53240 | val 2.86130
  Classification -> best τ=0.130 (val F1=0.1569)
  Directional -> Accuracy: 0.4650, MCC: 0.0095, F1: 0.3436

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.62404 | val 0.99271
  Epoch 016 - train 0.58242 | val 1.25318
  Classification -> best τ=0.475 (val F1=0.1398)
  Directional -> Accuracy: 0.4400, MCC: 0.0144, F1: 0.1385

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.61904 | val 1.33264
  Epoch 016 - train 0.58134 | val 1.17983
  Classification -> best τ=0.490 (val F1=0.1881)
  Directional -> Accuracy: 0.4518, MCC: 0.0456, F1: 0.5909

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.60146 | val 1.37433
  Epoch 016 - train 0.54781 | val 1.86170
  Classification -> best τ=0.305 (val F1=0.1207)
  Directional -> Accuracy: 0.5400, MCC: 0.0660, F1: 0.6068

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.65403 | val 0.90516
  Epoch 016 - train 0.59168 | val 1.37733
  Classification -> best τ=0.625 (val F1=0.1152)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62541 | val 2.05113
  Epoch 016 - train 0.57838 | val 2.33817
  Classification -> best τ=0.545 (val F1=0.2300)
  Directional -> Accuracy: 0.4550, MCC: -0.0209, F1: 0.5514

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.60104 | val 2.51548
  Epoch 016 - train 0.54657 | val 2.63263
  Classification -> best τ=0.385 (val F1=0.1441)
  Directional -> Accuracy: 0.4670, MCC: -0.0681, F1: 0.5415

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.65219 | val 1.11309
  Epoch 018 - train 0.57929 | val 2.34062
  Classification -> best τ=0.440 (val F1=0.1433)
  Directional -> Accuracy: 0.5150, MCC: 0.0000, F1: 0.6799

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.59722 | val 1.07752
  Epoch 018 - train 0.51591 | val 2.31945
  Classification -> best τ=0.405 (val F1=0.0742)
  Directional -> Accuracy: 0.4800, MCC: -0.1097, F1: 0.6338

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.63867 | val 4.81077
  Epoch 016 - train 0.58769 | val 4.90718
  Classification -> best τ=0.570 (val F1=0.1105)
  Directional -> Accuracy: 0.4550, MCC: 0.0000, F1: 0.6254

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.64560 | val 0.94140
  Epoch 016 - train 0.61467 | val 1.19471
  Classification -> best τ=0.485 (val F1=0.2108)
  Directional -> Accuracy: 0.5000, MCC: 0.0801, F1: 0.2063

[75/88] Processing T...


[I 2026-02-26 04:04:55,945] Trial 35 finished with value: 0.14125614538114642 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.0037430380922155145, 'weight_decay': 1.816877597406181e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 0.9229434058198894, 'early_stopping_min_delta': 0.001963918408749305}. Best is trial 34 with value: 0.15332516303987392.

  Epoch 016 - train 0.59697 | val 1.70469
  Classification -> best τ=0.425 (val F1=0.1483)
  Directional -> Accuracy: 0.4800, MCC: -0.0365, F1: 0.5273

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14125614538114642
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 10
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65925 | val 0.81697
  Epoch 020 - train 0.64326 | val 0.90271
  Epoch 021 - train 0.64435 | val 0.89980
  Classification -> best τ=0.475 (val F1=0.0716)
  Directional -> Accuracy: 0.5025, MCC: -0.0761, F1: 0.6178

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.64302 | val 1.16624
  Epoch 020 - train 0.62071 | val 1.31995
  Epoch 021 - train 0.62725 | val 1.32631
  Classification -> best τ=0.455 (val F1=0.1600)
  Directional -> Accuracy: 0.5578, MCC: 0.1183, F1: 0.5165

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65590 | val 0.95562
  Epoch 020 - train 0.62340 | val 1.02358
  Epoch 021 - train 0.63118 | val 1.02785
  Classification -> best τ=0.390 (val F1=0.1666)
  Directional -> Accuracy: 0.4247, MCC: -0.0999, F1: 0.3436

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.65856 | val 0.69729
  Epoch 020 - train 0.64002 | val 0.83051
  Epoch 021 - train 0.64182 | val 0.83546
  Classification -> best τ=0.550 (val F1=0.1378)
  Directional -> Accuracy: 0.4673, MCC: 0.0362, F1: 0.2429

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.63600 | val 0.71576
  Epoch 020 - train 0.60085 | val 0.79329
  Epoch 021 - train 0.59760 | val 0.78887
  Classification -> best τ=0.555 (val F1=0.1184)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65233 | val 0.97665
  Epoch 020 - train 0.62526 | val 1.19579
  Epoch 021 - train 0.63364 | val 1.20027
  Classification -> best τ=0.460 (val F1=0.1181)
  Directional -> Accuracy: 0.5377, MCC: -0.0091, F1: 0.6783

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65983 | val 0.78323
  Epoch 020 - train 0.63333 | val 0.96023
  Epoch 021 - train 0.63172 | val 0.96954
  Classification -> best τ=0.635 (val F1=0.1250)
  Directional -> Accuracy: 0.4422, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62722 | val 0.66446
  Epoch 020 - train 0.59927 | val 0.70759
  Epoch 025 - train 0.59782 | val 0.73584
  Classification -> best τ=0.530 (val F1=0.2420)
  Directional -> Accuracy: 0.3920, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.63947 | val 0.88468
  Epoch 020 - train 0.62687 | val 0.84105
  Epoch 021 - train 0.63076 | val 0.84847
  Classification -> best τ=0.495 (val F1=0.1871)
  Directional -> Accuracy: 0.4123, MCC: -0.1103, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65772 | val 1.29534
  Epoch 020 - train 0.63260 | val 1.53098
  Epoch 021 - train 0.63053 | val 1.51448
  Classification -> best τ=0.655 (val F1=0.0879)
  Directional -> Accuracy: 0.5377, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.65115 | val 0.76117
  Epoch 020 - train 0.63224 | val 0.80095
  Epoch 022 - train 0.62583 | val 0.79374
  Classification -> best τ=0.630 (val F1=0.1672)
  Directional -> Accuracy: 0.4573, MCC: 0.0000, F1: 0.0000

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.63379 | val 0.79823
  Epoch 020 - train 0.61647 | val 0.75654
  Epoch 021 - train 0.61406 | val 0.75471
  Classification -> best τ=0.670 (val F1=0.1294)
  Directional -> Accuracy: 0.4221, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63505 | val 0.75177
  Epoch 020 - train 0.60651 | val 0.75510
  Epoch 021 - train 0.61260 | val 0.75554
  Classification -> best τ=0.520 (val F1=0.1464)
  Directional -> Accuracy: 0.4623, MCC: 0.0154, F1: 0.2517

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63762 | val 0.75583
  Epoch 020 - train 0.60240 | val 0.78516
  Epoch 021 - train 0.60476 | val 0.78593
  Classification -> best τ=0.685 (val F1=0.1586)
  Directional -> Accuracy: 0.5025, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.66740 | val 0.83496
  Epoch 020 - train 0.65721 | val 0.93128
  Epoch 021 - train 0.64667 | val 0.92608
  Classification -> best τ=0.445 (val F1=0.1119)
  Directional -> Accuracy: 0.4523, MCC: -0.0698, F1: 0.2044

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.64379 | val 0.83860
  Epoch 020 - train 0.62450 | val 0.92952
  Epoch 021 - train 0.61921 | val 0.92630
  Classification -> best τ=0.540 (val F1=0.1381)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.64203 | val 0.83858
  Epoch 020 - train 0.62565 | val 1.05353
  Epoch 021 - train 0.62079 | val 1.04362
  Classification -> best τ=0.405 (val F1=0.2121)
  Directional -> Accuracy: 0.5578, MCC: 0.0000, F1: 0.7161

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63563 | val 0.84544
  Epoch 020 - train 0.61327 | val 0.89451
  Epoch 021 - train 0.61145 | val 0.86240
  Classification -> best τ=0.530 (val F1=0.1217)
  Directional -> Accuracy: 0.4824, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65837 | val 0.67931
  Epoch 020 - train 0.60086 | val 0.77193
  Epoch 027 - train 0.59573 | val 0.77925
  Classification -> best τ=0.495 (val F1=0.2645)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64402 | val 0.72011
  Epoch 020 - train 0.61143 | val 0.71072
  Epoch 021 - train 0.60900 | val 0.71300
  Classification -> best τ=0.505 (val F1=0.0938)
  Directional -> Accuracy: 0.4623, MCC: -0.0152, F1: 0.1832

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.65703 | val 0.83636
  Epoch 020 - train 0.63038 | val 0.86878
  Epoch 021 - train 0.63110 | val 0.88392
  Classification -> best τ=0.545 (val F1=0.1165)
  Directional -> Accuracy: 0.4975, MCC: 0.0244, F1: 0.6552

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.66669 | val 0.96781
  Epoch 020 - train 0.64747 | val 0.95902
  Epoch 021 - train 0.64385 | val 0.96976
  Classification -> best τ=0.395 (val F1=0.1601)
  Directional -> Accuracy: 0.5126, MCC: 0.0613, F1: 0.4757

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65500 | val 1.05596
  Epoch 020 - train 0.64185 | val 1.10153
  Epoch 021 - train 0.63357 | val 1.13864
  Classification -> best τ=0.415 (val F1=0.1473)
  Directional -> Accuracy: 0.4573, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.63953 | val 0.94164
  Epoch 020 - train 0.61821 | val 0.95468
  Epoch 021 - train 0.61751 | val 0.95624
  Classification -> best τ=0.640 (val F1=0.0897)
  Directional -> Accuracy: 0.6080, MCC: 0.0000, F1: 0.0000

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65054 | val 0.83661
  Epoch 020 - train 0.63448 | val 0.88598
  Epoch 021 - train 0.63167 | val 0.92728
  Classification -> best τ=0.455 (val F1=0.0945)
  Directional -> Accuracy: 0.5327, MCC: 0.0685, F1: 0.5279

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63840 | val 1.05596
  Epoch 020 - train 0.61747 | val 1.16591
  Epoch 021 - train 0.62717 | val 1.17018
  Classification -> best τ=0.590 (val F1=0.1438)
  Directional -> Accuracy: 0.5126, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62823 | val 1.83757
  Epoch 020 - train 0.59013 | val 2.64341
  Epoch 021 - train 0.58303 | val 2.69434
  Classification -> best τ=0.520 (val F1=0.1447)
  Directional -> Accuracy: 0.4623, MCC: 0.0185, F1: 0.0531

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.65150 | val 1.32363
  Epoch 020 - train 0.63593 | val 1.51130
  Epoch 021 - train 0.64054 | val 1.51506
  Classification -> best τ=0.455 (val F1=0.1366)
  Directional -> Accuracy: 0.5276, MCC: 0.0551, F1: 0.5155

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65402 | val 0.92230
  Epoch 020 - train 0.63296 | val 1.11596
  Epoch 021 - train 0.63874 | val 1.13623
  Classification -> best τ=0.455 (val F1=0.1504)
  Directional -> Accuracy: 0.5226, MCC: 0.0381, F1: 0.6442

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.65285 | val 0.72911
  Epoch 020 - train 0.63710 | val 0.75003
  Epoch 021 - train 0.62677 | val 0.75032
  Classification -> best τ=0.435 (val F1=0.1527)
  Directional -> Accuracy: 0.5628, MCC: 0.1065, F1: 0.7051

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.65511 | val 0.86947
  Epoch 020 - train 0.62761 | val 0.97582
  Epoch 021 - train 0.62564 | val 0.97806
  Classification -> best τ=0.440 (val F1=0.1128)
  Directional -> Accuracy: 0.4774, MCC: -0.0460, F1: 0.2464

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65898 | val 0.74087
  Epoch 020 - train 0.63655 | val 0.77629
  Epoch 021 - train 0.63736 | val 0.79679
  Classification -> best τ=0.455 (val F1=0.1484)
  Directional -> Accuracy: 0.5126, MCC: 0.0482, F1: 0.4868

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.65611 | val 0.82207
  Epoch 020 - train 0.63610 | val 0.93355
  Epoch 021 - train 0.64494 | val 0.92471
  Classification -> best τ=0.480 (val F1=0.1768)
  Directional -> Accuracy: 0.3920, MCC: 0.0000, F1: 0.0000

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64217 | val 2.38552
  Epoch 020 - train 0.62495 | val 3.01177
  Epoch 021 - train 0.62894 | val 3.06967
  Classification -> best τ=0.360 (val F1=0.1059)
  Directional -> Accuracy: 0.5126, MCC: 0.0555, F1: 0.5488

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.62039 | val 1.11412
  Epoch 020 - train 0.60208 | val 1.39716
  Epoch 021 - train 0.60910 | val 1.40189
  Classification -> best τ=0.500 (val F1=0.0494)
  Directional -> Accuracy: 0.5106, MCC: 0.0385, F1: 0.6102

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64072 | val 0.96604
  Epoch 020 - train 0.63251 | val 1.11521
  Epoch 021 - train 0.61658 | val 1.10781
  Classification -> best τ=0.440 (val F1=0.1876)
  Directional -> Accuracy: 0.4171, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64871 | val 1.36575
  Epoch 020 - train 0.62873 | val 1.59011
  Epoch 021 - train 0.63269 | val 1.59481
  Classification -> best τ=0.505 (val F1=0.1882)
  Directional -> Accuracy: 0.4673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.64169 | val 1.45339
  Epoch 020 - train 0.63442 | val 1.48795
  Epoch 021 - train 0.63411 | val 1.47009
  Classification -> best τ=0.320 (val F1=0.1362)
  Directional -> Accuracy: 0.5226, MCC: 0.1012, F1: 0.4633

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.65189 | val 1.48949
  Epoch 020 - train 0.64360 | val 1.72714
  Epoch 021 - train 0.63592 | val 1.72964
  Classification -> best τ=0.555 (val F1=0.0690)
  Directional -> Accuracy: 0.4573, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.65222 | val 1.50236
  Epoch 020 - train 0.63630 | val 1.97710
  Epoch 021 - train 0.63594 | val 1.95834
  Classification -> best τ=0.360 (val F1=0.1484)
  Directional -> Accuracy: 0.5276, MCC: 0.0000, F1: 0.6908

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.65287 | val 0.76109
  Epoch 020 - train 0.63467 | val 0.76328
  Epoch 021 - train 0.63221 | val 0.76787
  Classification -> best τ=0.620 (val F1=0.0707)
  Directional -> Accuracy: 0.4824, MCC: 0.0000, F1: 0.0000

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64232 | val 1.02902
  Epoch 020 - train 0.62543 | val 1.14081
  Epoch 021 - train 0.62539 | val 1.16880
  Classification -> best τ=0.340 (val F1=0.1638)
  Directional -> Accuracy: 0.5578, MCC: 0.0793, F1: 0.6944

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65261 | val 0.91759
  Epoch 020 - train 0.63608 | val 0.94050
  Epoch 021 - train 0.64419 | val 0.94283
  Classification -> best τ=0.465 (val F1=0.0700)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65841 | val 0.78824
  Epoch 020 - train 0.63940 | val 0.84626
  Epoch 021 - train 0.62920 | val 0.85690
  Classification -> best τ=0.570 (val F1=0.1532)
  Directional -> Accuracy: 0.4774, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63905 | val 1.78635
  Epoch 020 - train 0.61817 | val 2.14378
  Epoch 021 - train 0.63149 | val 2.16891
  Classification -> best τ=0.330 (val F1=0.1194)
  Directional -> Accuracy: 0.5377, MCC: 0.0391, F1: 0.6515

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64794 | val 0.98440
  Epoch 020 - train 0.63248 | val 1.11862
  Epoch 021 - train 0.62643 | val 1.12193
  Classification -> best τ=0.545 (val F1=0.1124)
  Directional -> Accuracy: 0.4121, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64414 | val 0.80589
  Epoch 020 - train 0.61921 | val 0.87729
  Epoch 021 - train 0.62520 | val 0.88752
  Classification -> best τ=0.425 (val F1=0.1565)
  Directional -> Accuracy: 0.5628, MCC: 0.1174, F1: 0.6027

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64375 | val 1.58235
  Epoch 020 - train 0.61614 | val 1.83117
  Epoch 021 - train 0.61845 | val 1.87393
  Classification -> best τ=0.430 (val F1=0.1101)
  Directional -> Accuracy: 0.4925, MCC: 0.0198, F1: 0.5025

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63993 | val 1.71158
  Epoch 020 - train 0.61032 | val 1.95877
  Epoch 021 - train 0.61477 | val 1.95333
  Classification -> best τ=0.565 (val F1=0.1717)
  Directional -> Accuracy: 0.5126, MCC: 0.0157, F1: 0.3660

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64566 | val 0.82114
  Epoch 020 - train 0.63317 | val 0.85991
  Epoch 021 - train 0.63185 | val 0.85351
  Classification -> best τ=0.480 (val F1=0.0918)
  Directional -> Accuracy: 0.4523, MCC: 0.0945, F1: 0.0840

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65569 | val 1.62584
  Epoch 020 - train 0.64135 | val 1.88292
  Epoch 021 - train 0.63510 | val 1.93225
  Classification -> best τ=0.460 (val F1=0.1609)
  Directional -> Accuracy: 0.5427, MCC: 0.0290, F1: 0.6540

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64544 | val 1.08188
  Epoch 020 - train 0.61980 | val 1.12533
  Epoch 021 - train 0.62411 | val 1.12990
  Classification -> best τ=0.490 (val F1=0.0870)
  Directional -> Accuracy: 0.4824, MCC: -0.0738, F1: 0.0190

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64300 | val 0.93690
  Epoch 020 - train 0.63549 | val 0.92216
  Epoch 021 - train 0.63515 | val 0.92981
  Classification -> best τ=0.475 (val F1=0.1063)
  Directional -> Accuracy: 0.4874, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.64634 | val 1.73154
  Epoch 020 - train 0.62186 | val 2.12145
  Epoch 021 - train 0.62325 | val 2.14651
  Classification -> best τ=0.405 (val F1=0.0925)
  Directional -> Accuracy: 0.4020, MCC: 0.0000, F1: 0.0000

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.64320 | val 1.41613
  Epoch 020 - train 0.63221 | val 1.61514
  Epoch 021 - train 0.61938 | val 1.62472
  Classification -> best τ=0.370 (val F1=0.0817)
  Directional -> Accuracy: 0.4975, MCC: 0.0000, F1: 0.6644

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64433 | val 1.15632
  Epoch 020 - train 0.62944 | val 1.06013
  Epoch 021 - train 0.63007 | val 1.04658
  Classification -> best τ=0.545 (val F1=0.1288)
  Directional -> Accuracy: 0.5678, MCC: 0.1470, F1: 0.6861

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65042 | val 0.77907
  Epoch 020 - train 0.63087 | val 0.88203
  Epoch 021 - train 0.62345 | val 0.88452
  Classification -> best τ=0.545 (val F1=0.0753)
  Directional -> Accuracy: 0.4523, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.65676 | val 1.26174
  Epoch 020 - train 0.63308 | val 1.24053
  Epoch 021 - train 0.64303 | val 1.23826
  Classification -> best τ=0.440 (val F1=0.1192)
  Directional -> Accuracy: 0.5025, MCC: 0.0644, F1: 0.2556

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64126 | val 0.70091
  Epoch 020 - train 0.61586 | val 0.70386
  Epoch 021 - train 0.63376 | val 0.70369
  Classification -> best τ=0.565 (val F1=0.1811)
  Directional -> Accuracy: 0.4171, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63906 | val 0.72546
  Epoch 020 - train 0.61941 | val 0.72871
  Epoch 021 - train 0.61610 | val 0.72914
  Classification -> best τ=0.500 (val F1=0.1866)
  Directional -> Accuracy: 0.5025, MCC: 0.0538, F1: 0.3265

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62270 | val 0.96049
  Epoch 020 - train 0.61369 | val 1.08553
  Epoch 021 - train 0.61486 | val 1.11303
  Classification -> best τ=0.285 (val F1=0.1256)
  Directional -> Accuracy: 0.4774, MCC: 0.0000, F1: 0.6463

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65230 | val 1.04539
  Epoch 020 - train 0.62842 | val 1.17242
  Epoch 021 - train 0.63301 | val 1.19951
  Classification -> best τ=0.360 (val F1=0.1765)
  Directional -> Accuracy: 0.4925, MCC: 0.0039, F1: 0.2290

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.64240 | val 1.13135
  Epoch 020 - train 0.63733 | val 1.02458
  Epoch 021 - train 0.63102 | val 1.03379
  Classification -> best τ=0.690 (val F1=0.1076)
  Directional -> Accuracy: 0.5327, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.65023 | val 1.09640
  Epoch 020 - train 0.63140 | val 1.13133
  Epoch 021 - train 0.61848 | val 1.17478

[I 2026-02-26 04:07:13,838] Trial 36 finished with value: 0.13833241373987007 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 10, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.0008973025722406537, 'weight_decay': 1.245796758623728e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.6062616901784201, 'early_stopping_min_delta': 0.003347479554977091}. Best is trial 34 with value: 0.15332516303987392.

  Epoch 020 - train 0.63375 | val 0.88805
  Epoch 021 - train 0.64042 | val 0.88389
  Classification -> best τ=0.335 (val F1=0.1514)
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.6599

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.13833241373987007
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 5
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66929 | val 0.81117
  Epoch 020 - train 0.66567 | val 0.81917
  Epoch 021 - train 0.64631 | val 0.83948
  Classification -> best τ=0.515 (val F1=0.0698)
  Directional -> Accuracy: 0.4500, MCC: 0.0857, F1: 0.1667

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.65910 | val 1.73451
  Epoch 020 - train 0.63306 | val 2.35208
  Epoch 021 - train 0.63175 | val 2.38766
  Classification -> best τ=0.505 (val F1=0.2097)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65120 | val 0.72656
  Epoch 020 - train 0.63697 | val 0.74533
  Epoch 021 - train 0.64149 | val 0.74724
  Classification -> best τ=0.530 (val F1=0.1365)
  Directional -> Accuracy: 0.4011, MCC: -0.1269, F1: 0.0820

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.68407 | val 0.82729
  Epoch 020 - train 0.66782 | val 0.78542
  Epoch 021 - train 0.66445 | val 0.78506
  Classification -> best τ=0.350 (val F1=0.1109)
  Directional -> Accuracy: 0.5600, MCC: 0.0305, F1: 0.7067

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.65220 | val 0.84429
  Epoch 020 - train 0.62547 | val 1.00564
  Epoch 021 - train 0.61970 | val 1.02888
  Classification -> best τ=0.540 (val F1=0.1648)
  Directional -> Accuracy: 0.4766, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65869 | val 0.81695
  Epoch 020 - train 0.63750 | val 0.92375
  Epoch 021 - train 0.63829 | val 0.92504
  Classification -> best τ=0.545 (val F1=0.1283)
  Directional -> Accuracy: 0.4450, MCC: -0.0304, F1: 0.1120

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66996 | val 0.85284
  Epoch 020 - train 0.65955 | val 1.08804
  Epoch 021 - train 0.65650 | val 1.16447
  Classification -> best τ=0.520 (val F1=0.0935)
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65761 | val 0.78502
  Epoch 020 - train 0.64332 | val 0.85910
  Epoch 021 - train 0.64839 | val 0.85632
  Classification -> best τ=0.355 (val F1=0.2536)
  Directional -> Accuracy: 0.5250, MCC: 0.0554, F1: 0.5662

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65992 | val 1.02322
  Epoch 020 - train 0.62245 | val 1.27394
  Epoch 022 - train 0.63643 | val 1.32580
  Classification -> best τ=0.410 (val F1=0.1832)
  Directional -> Accuracy: 0.4174, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65944 | val 0.94419
  Epoch 020 - train 0.64609 | val 1.04446
  Epoch 021 - train 0.65283 | val 1.05417
  Classification -> best τ=0.465 (val F1=0.0518)
  Directional -> Accuracy: 0.4950, MCC: -0.0592, F1: 0.2837

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.66373 | val 0.85972
  Epoch 020 - train 0.64868 | val 0.76062
  Epoch 021 - train 0.65408 | val 0.75516
  Classification -> best τ=0.370 (val F1=0.1616)
  Directional -> Accuracy: 0.5000, MCC: -0.0048, F1: 0.5327

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.66878 | val 0.72612
  Epoch 020 - train 0.65300 | val 0.73584
  Epoch 021 - train 0.64470 | val 0.74366
  Classification -> best τ=0.500 (val F1=0.0787)
  Directional -> Accuracy: 0.5550, MCC: -0.0062, F1: 0.6942

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65730 | val 0.79592
  Epoch 020 - train 0.64111 | val 0.82835
  Epoch 021 - train 0.63348 | val 0.83276
  Classification -> best τ=0.455 (val F1=0.1153)
  Directional -> Accuracy: 0.5150, MCC: 0.0339, F1: 0.5359

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65501 | val 0.81059
  Epoch 020 - train 0.63136 | val 1.05081
  Epoch 022 - train 0.64331 | val 1.04413
  Classification -> best τ=0.435 (val F1=0.1289)
  Directional -> Accuracy: 0.5300, MCC: 0.1511, F1: 0.6736

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.67422 | val 0.84063
  Epoch 020 - train 0.66817 | val 0.93049
  Epoch 021 - train 0.66934 | val 0.95070
  Classification -> best τ=0.610 (val F1=0.1322)
  Directional -> Accuracy: 0.4700, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.65402 | val 1.28418
  Epoch 020 - train 0.65246 | val 1.51680
  Epoch 021 - train 0.64995 | val 1.50861
  Classification -> best τ=0.440 (val F1=0.0847)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5652

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.67787 | val 0.72977
  Epoch 020 - train 0.64848 | val 0.75920
  Epoch 021 - train 0.65769 | val 0.75461
  Classification -> best τ=0.415 (val F1=0.1351)
  Directional -> Accuracy: 0.5550, MCC: 0.0000, F1: 0.7138

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66543 | val 0.82839
  Epoch 020 - train 0.63949 | val 1.08952
  Epoch 022 - train 0.64089 | val 1.08611
  Classification -> best τ=0.705 (val F1=0.1607)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67124 | val 0.82670
  Epoch 020 - train 0.65091 | val 0.79933
  Epoch 021 - train 0.65232 | val 0.79417
  Classification -> best τ=0.390 (val F1=0.2415)
  Directional -> Accuracy: 0.4950, MCC: -0.0132, F1: 0.2519

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66956 | val 0.75349
  Epoch 020 - train 0.65288 | val 0.79076
  Epoch 021 - train 0.64387 | val 0.79469
  Classification -> best τ=0.570 (val F1=0.1139)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.66452 | val 0.69305
  Epoch 020 - train 0.65936 | val 0.73633
  Epoch 026 - train 0.64682 | val 0.73766
  Classification -> best τ=0.605 (val F1=0.1971)
  Directional -> Accuracy: 0.5200, MCC: 0.0392, F1: 0.5052

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.66397 | val 1.22453
  Epoch 020 - train 0.65930 | val 1.66410
  Epoch 021 - train 0.64861 | val 1.63162
  Classification -> best τ=0.530 (val F1=0.1588)
  Directional -> Accuracy: 0.4850, MCC: 0.0095, F1: 0.4372

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66348 | val 0.78828
  Epoch 020 - train 0.66166 | val 0.87026
  Epoch 021 - train 0.67219 | val 0.85483
  Classification -> best τ=0.550 (val F1=0.1150)
  Directional -> Accuracy: 0.4550, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.67295 | val 1.07599
  Epoch 020 - train 0.64674 | val 1.22306
  Epoch 021 - train 0.65197 | val 1.24899
  Classification -> best τ=0.275 (val F1=0.1785)
  Directional -> Accuracy: 0.4150, MCC: 0.0446, F1: 0.5651

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66960 | val 1.15954
  Epoch 020 - train 0.65858 | val 1.27826
  Epoch 021 - train 0.64998 | val 1.34641
  Classification -> best τ=0.345 (val F1=0.1347)
  Directional -> Accuracy: 0.5150, MCC: 0.0329, F1: 0.5076

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66507 | val 0.74705
  Epoch 020 - train 0.67501 | val 0.77543
  Epoch 021 - train 0.66430 | val 0.77469
  Classification -> best τ=0.530 (val F1=0.1392)
  Directional -> Accuracy: 0.5000, MCC: -0.0064, F1: 0.4318

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66929 | val 0.78315
  Epoch 020 - train 0.65911 | val 0.94959
  Epoch 021 - train 0.66205 | val 0.94606
  Classification -> best τ=0.540 (val F1=0.1314)
  Directional -> Accuracy: 0.4700, MCC: 0.0928, F1: 0.0364

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.66557 | val 0.91076
  Epoch 020 - train 0.65348 | val 0.92124
  Epoch 021 - train 0.64628 | val 0.91043
  Classification -> best τ=0.625 (val F1=0.1297)
  Directional -> Accuracy: 0.5150, MCC: 0.0301, F1: 0.4974

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66297 | val 0.86149
  Epoch 020 - train 0.65680 | val 1.05210
  Epoch 021 - train 0.66518 | val 1.07293
  Classification -> best τ=0.600 (val F1=0.1517)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.68556 | val 0.84118
  Epoch 020 - train 0.66961 | val 0.92993
  Epoch 021 - train 0.67126 | val 0.93521
  Classification -> best τ=0.325 (val F1=0.1407)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.67261 | val 0.86061
  Epoch 020 - train 0.65693 | val 1.03814
  Epoch 021 - train 0.65125 | val 1.15911
  Classification -> best τ=0.265 (val F1=0.1579)
  Directional -> Accuracy: 0.5050, MCC: 0.0000, F1: 0.6711

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67737 | val 0.82295
  Epoch 020 - train 0.65919 | val 0.89956
  Epoch 021 - train 0.65612 | val 0.90306
  Classification -> best τ=0.380 (val F1=0.1074)
  Directional -> Accuracy: 0.5250, MCC: -0.0338, F1: 0.6643

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.66980 | val 0.76400
  Epoch 020 - train 0.66526 | val 0.79672
  Epoch 021 - train 0.65686 | val 0.80053
  Classification -> best τ=0.495 (val F1=0.1078)
  Directional -> Accuracy: 0.6150, MCC: 0.1244, F1: 0.7586

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66208 | val 0.86224
  Epoch 020 - train 0.63685 | val 0.95704
  Epoch 021 - train 0.64914 | val 0.94968
  Classification -> best τ=0.375 (val F1=0.1617)
  Directional -> Accuracy: 0.4450, MCC: -0.0111, F1: 0.6132

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.66790 | val 0.72152
  Epoch 020 - train 0.66950 | val 0.76658
  Epoch 021 - train 0.64210 | val 0.77047
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65421 | val 0.81183
  Epoch 020 - train 0.63720 | val 1.00964
  Epoch 021 - train 0.64380 | val 0.99485
  Classification -> best τ=0.525 (val F1=0.1583)
  Directional -> Accuracy: 0.4150, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66248 | val 0.77654
  Epoch 020 - train 0.65740 | val 0.79750
  Epoch 021 - train 0.65069 | val 0.81197
  Classification -> best τ=0.455 (val F1=0.1987)
  Directional -> Accuracy: 0.4600, MCC: -0.0760, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.65338 | val 0.88836
  Epoch 020 - train 0.65339 | val 1.04289
  Epoch 021 - train 0.65572 | val 1.04126
  Classification -> best τ=0.490 (val F1=0.0913)
  Directional -> Accuracy: 0.4400, MCC: 0.0253, F1: 0.0345

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.65953 | val 1.07672
  Epoch 020 - train 0.65744 | val 1.25109
  Epoch 021 - train 0.66517 | val 1.24559
  Classification -> best τ=0.355 (val F1=0.1145)
  Directional -> Accuracy: 0.5450, MCC: 0.0000, F1: 0.7055

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.67155 | val 0.83919
  Epoch 020 - train 0.65850 | val 1.14352
  Epoch 021 - train 0.65172 | val 1.21670
  Classification -> best τ=0.430 (val F1=0.0106)
  Directional -> Accuracy: 0.5850, MCC: 0.1632, F1: 0.6344

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.67212 | val 1.75164
  Epoch 020 - train 0.67009 | val 1.84326
  Epoch 021 - train 0.66865 | val 1.92956
  Classification -> best τ=0.770 (val F1=0.1892)
  Directional -> Accuracy: 0.5000, MCC: 0.0160, F1: 0.3590

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65893 | val 1.02738
  Epoch 020 - train 0.64437 | val 1.17349
  Epoch 021 - train 0.64639 | val 1.17772
  Classification -> best τ=0.360 (val F1=0.1197)
  Directional -> Accuracy: 0.5400, MCC: 0.0324, F1: 0.6714

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66839 | val 1.00895
  Epoch 020 - train 0.65054 | val 1.10513
  Epoch 021 - train 0.65033 | val 1.16589
  Classification -> best τ=0.480 (val F1=0.1403)
  Directional -> Accuracy: 0.4750, MCC: -0.0719, F1: 0.5783

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66831 | val 0.81406
  Epoch 020 - train 0.65158 | val 0.97342
  Epoch 021 - train 0.64308 | val 0.96104
  Classification -> best τ=0.465 (val F1=0.1064)
  Directional -> Accuracy: 0.5500, MCC: 0.1360, F1: 0.4231

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64896 | val 1.07730
  Epoch 020 - train 0.64453 | val 1.33723
  Epoch 021 - train 0.64198 | val 1.34634
  Classification -> best τ=0.610 (val F1=0.0923)
  Directional -> Accuracy: 0.4850, MCC: 0.0532, F1: 0.1626

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66761 | val 0.84371
  Epoch 020 - train 0.66536 | val 0.85804
  Epoch 021 - train 0.66484 | val 0.85122
  Classification -> best τ=0.150 (val F1=0.1111)
  Directional -> Accuracy: 0.5850, MCC: 0.0000, F1: 0.7382

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66488 | val 0.79569
  Epoch 020 - train 0.64221 | val 0.84570
  Epoch 021 - train 0.64840 | val 0.85193
  Classification -> best τ=0.530 (val F1=0.1201)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66890 | val 1.10456
  Epoch 020 - train 0.65267 | val 0.98062
  Epoch 021 - train 0.65555 | val 0.96255
  Classification -> best τ=0.160 (val F1=0.0922)
  Directional -> Accuracy: 0.4700, MCC: -0.0035, F1: 0.4536

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66341 | val 1.00082
  Epoch 020 - train 0.66556 | val 1.18271
  Epoch 021 - train 0.66074 | val 1.16962
  Classification -> best τ=0.375 (val F1=0.1612)
  Directional -> Accuracy: 0.5150, MCC: 0.0836, F1: 0.6548

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66476 | val 1.05678
  Epoch 020 - train 0.65001 | val 1.04944
  Epoch 021 - train 0.65752 | val 0.99086
  Classification -> best τ=0.495 (val F1=0.1319)
  Directional -> Accuracy: 0.4350, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66923 | val 1.14345
  Epoch 020 - train 0.65365 | val 1.60105
  Epoch 021 - train 0.65571 | val 1.59899
  Classification -> best τ=0.435 (val F1=0.1337)
  Directional -> Accuracy: 0.4500, MCC: -0.0399, F1: 0.2949

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67014 | val 0.81392
  Epoch 020 - train 0.66128 | val 0.87398
  Epoch 021 - train 0.65702 | val 0.87869
  Classification -> best τ=0.400 (val F1=0.1084)
  Directional -> Accuracy: 0.4900, MCC: -0.0189, F1: 0.1905

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67217 | val 0.72992
  Epoch 020 - train 0.65832 | val 0.77254
  Epoch 021 - train 0.66141 | val 0.77516
  Classification -> best τ=0.680 (val F1=0.0956)
  Directional -> Accuracy: 0.4850, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.66230 | val 0.73654
  Epoch 020 - train 0.65410 | val 0.85958
  Epoch 021 - train 0.65508 | val 0.85521
  Classification -> best τ=0.565 (val F1=0.1194)
  Directional -> Accuracy: 0.4150, MCC: 0.0257, F1: 0.0640

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.66187 | val 0.70071
  Epoch 020 - train 0.65441 | val 0.71948
  Epoch 021 - train 0.66315 | val 0.72902
  Classification -> best τ=0.475 (val F1=0.1216)
  Directional -> Accuracy: 0.4800, MCC: -0.0835, F1: 0.6438

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67723 | val 0.93083
  Epoch 020 - train 0.65193 | val 1.15660
  Epoch 021 - train 0.66107 | val 1.17919
  Classification -> best τ=0.565 (val F1=0.1487)
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66111 | val 0.77282
  Epoch 020 - train 0.64404 | val 0.79653
  Epoch 021 - train 0.65366 | val 0.80536
  Classification -> best τ=0.445 (val F1=0.1020)
  Directional -> Accuracy: 0.5450, MCC: 0.1279, F1: 0.4916

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.67385 | val 0.73698
  Epoch 020 - train 0.66117 | val 0.71488
  Epoch 030 - train 0.64950 | val 0.76847
  Classification -> best τ=0.515 (val F1=0.1755)
  Directional -> Accuracy: 0.4550, MCC: -0.0970, F1: 0.0684

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65533 | val 0.94286
  Epoch 020 - train 0.64556 | val 1.04941
  Epoch 021 - train 0.64383 | val 1.03326
  Classification -> best τ=0.420 (val F1=0.2130)
  Directional -> Accuracy: 0.4650, MCC: -0.0202, F1: 0.4278

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66550 | val 0.90145
  Epoch 020 - train 0.62821 | val 1.14295
  Epoch 021 - train 0.64056 | val 1.20335
  Classification -> best τ=0.575 (val F1=0.2317)
  Directional -> Accuracy: 0.5050, MCC: 0.0563, F1: 0.3265

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66597 | val 0.82075
  Epoch 020 - train 0.64600 | val 0.91345
  Epoch 021 - train 0.64781 | val 0.89222
  Classification -> best τ=0.320 (val F1=0.1438)
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.6441

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66760 | val 0.83491
  Epoch 020 - train 0.66350 | val 0.97704
  Epoch 021 - train 0.65713 | val 0.96510
  Classification -> best τ=0.490 (val F1=0.2067)
  Directional -> Accuracy: 0.5750, MCC: 0.1567, F1: 0.6531

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.66733 | val 0.74830
  Epoch 020 - train 0.66126 | val 0.81030
  Epoch 021 - train 0.65874 | val 0.80318
  Classification -> best τ=0.510 (val F1=0.1057)
  Directional -> Accuracy: 0.5350, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.67180 | val 1.27031

[I 2026-02-26 04:15:14,722] Trial 37 finished with value: 0.13884520894234698 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 5, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.000123317183013304, 'weight_decay': 0.000754030556253757, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.3650314076633733, 'early_stopping_min_delta': 0.0024624005335097893}. Best is trial 34 with value: 0.15332516303987392.

  Epoch 021 - train 0.65152 | val 1.07017
  Classification -> best τ=0.535 (val F1=0.1641)
  Directional -> Accuracy: 0.5200, MCC: 0.0370, F1: 0.4667

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.13884520894234698
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64450 | val 1.53664
  Epoch 016 - train 0.59543 | val 3.04412
  Classification -> best τ=0.475 (val F1=0.1068)
  Directional -> Accuracy: 0.4192, MCC: -0.0394, F1: 0.1481

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.63467 | val 3.13320
  Epoch 017 - train 0.54951 | val 6.11352
  Classification -> best τ=0.305 (val F1=0.1591)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65221 | val 0.74518
  Epoch 016 - train 0.60228 | val 0.88072
  Classification -> best τ=0.420 (val F1=0.2050)
  Directional -> Accuracy: 0.4919, MCC: -0.0455, F1: 0.5648

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.67603 | val 0.78385
  Epoch 019 - train 0.59088 | val 1.94440
  Classification -> best τ=0.515 (val F1=0.1458)
  Directional -> Accuracy: 0.4545, MCC: 0.0355, F1: 0.1562

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.61116 | val 0.70875
  Epoch 016 - train 0.58148 | val 0.69270
  Classification -> best τ=0.540 (val F1=0.1750)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65438 | val 1.45201
  Epoch 019 - train 0.58084 | val 1.66400
  Classification -> best τ=0.830 (val F1=0.1205)
  Directional -> Accuracy: 0.4495, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67589 | val 0.76956
  Epoch 019 - train 0.61889 | val 0.84153
  Classification -> best τ=0.625 (val F1=0.1502)
  Directional -> Accuracy: 0.4747, MCC: 0.1319, F1: 0.1186

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63165 | val 0.97338
  Epoch 016 - train 0.53994 | val 1.08268
  Classification -> best τ=0.420 (val F1=0.2750)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57163 | val 0.85580
  Epoch 016 - train 0.45876 | val 0.85873
  Classification -> best τ=0.430 (val F1=0.1310)
  Directional -> Accuracy: 0.4602, MCC: 0.0515, F1: 0.2278

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63677 | val 2.05782
  Epoch 016 - train 0.56982 | val 4.05199
  Classification -> best τ=0.605 (val F1=0.1090)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.65020 | val 0.81748
  Epoch 016 - train 0.58683 | val 1.56863
  Classification -> best τ=0.520 (val F1=0.2064)
  Directional -> Accuracy: 0.4747, MCC: -0.0095, F1: 0.3247

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.62980 | val 1.13547
  Epoch 016 - train 0.59109 | val 1.15354
  Classification -> best τ=0.760 (val F1=0.1286)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64491 | val 1.16154
  Epoch 017 - train 0.55246 | val 2.01284
  Classification -> best τ=0.305 (val F1=0.1343)
  Directional -> Accuracy: 0.5101, MCC: 0.0117, F1: 0.5530

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67325 | val 0.79407
  Epoch 019 - train 0.50227 | val 2.66998
  Classification -> best τ=0.590 (val F1=0.2719)
  Directional -> Accuracy: 0.5152, MCC: 0.0369, F1: 0.1864

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.66343 | val 1.74164
  Epoch 020 - train 0.59561 | val 2.19701
  Classification -> best τ=0.500 (val F1=0.1514)
  Directional -> Accuracy: 0.4697, MCC: -0.0087, F1: 0.0367

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.62107 | val 1.29731
  Epoch 017 - train 0.53596 | val 2.54961
  Classification -> best τ=0.665 (val F1=0.1840)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.65081 | val 1.04929
  Epoch 020 - train 0.50519 | val 1.35591
  Classification -> best τ=0.330 (val F1=0.1545)
  Directional -> Accuracy: 0.5606, MCC: 0.0797, F1: 0.7166

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62576 | val 1.22800
  Epoch 017 - train 0.51620 | val 2.15722
  Classification -> best τ=0.865 (val F1=0.1281)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63668 | val 1.16653
  Epoch 016 - train 0.56283 | val 1.46070
  Classification -> best τ=0.405 (val F1=0.2845)
  Directional -> Accuracy: 0.5101, MCC: 0.0418, F1: 0.2240

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66727 | val 0.81894
  Epoch 019 - train 0.59811 | val 1.14399
  Classification -> best τ=0.740 (val F1=0.2023)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.63758 | val 1.74451
  Epoch 016 - train 0.57181 | val 2.60391
  Classification -> best τ=0.690 (val F1=0.1684)
  Directional -> Accuracy: 0.5101, MCC: 0.0572, F1: 0.6447

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.68255 | val 0.94415
  Epoch 018 - train 0.57502 | val 2.48490
  Classification -> best τ=0.555 (val F1=0.2342)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64183 | val 1.20536
  Epoch 016 - train 0.56306 | val 2.41928
  Classification -> best τ=0.405 (val F1=0.1741)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.63830 | val 1.10605
  Epoch 016 - train 0.59769 | val 1.29976
  Classification -> best τ=0.620 (val F1=0.2070)
  Directional -> Accuracy: 0.6061, MCC: 0.0000, F1: 0.0000

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60780 | val 2.24659
  Epoch 016 - train 0.51025 | val 3.41309
  Classification -> best τ=0.130 (val F1=0.1767)
  Directional -> Accuracy: 0.5556, MCC: 0.0997, F1: 0.6562

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66921 | val 0.84173
  Epoch 020 - train 0.58889 | val 0.84887
  Classification -> best τ=0.470 (val F1=0.2545)
  Directional -> Accuracy: 0.5101, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62549 | val 0.99592
  Epoch 016 - train 0.53274 | val 1.59206
  Classification -> best τ=0.470 (val F1=0.1960)
  Directional -> Accuracy: 0.6010, MCC: 0.1813, F1: 0.6827

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.67325 | val 0.80817
  Epoch 016 - train 0.61364 | val 0.97645
  Classification -> best τ=0.470 (val F1=0.1874)
  Directional -> Accuracy: 0.5051, MCC: 0.0103, F1: 0.4556

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65942 | val 1.71346
  Epoch 020 - train 0.57612 | val 1.95181
  Classification -> best τ=0.760 (val F1=0.1601)
  Directional -> Accuracy: 0.5202, MCC: 0.0580, F1: 0.3709

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.66522 | val 0.73413
  Epoch 020 - train 0.55927 | val 0.81366
  Classification -> best τ=0.490 (val F1=0.1847)
  Directional -> Accuracy: 0.4747, MCC: 0.0843, F1: 0.1034

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.61017 | val 2.55614
  Epoch 016 - train 0.55112 | val 3.90875
  Classification -> best τ=0.260 (val F1=0.1960)
  Directional -> Accuracy: 0.5303, MCC: 0.0829, F1: 0.3758

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64269 | val 0.70431
  Epoch 016 - train 0.59742 | val 0.79366
  Classification -> best τ=0.455 (val F1=0.1362)
  Directional -> Accuracy: 0.5505, MCC: 0.0000, F1: 0.7101

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.65426 | val 0.82720
  Epoch 016 - train 0.61258 | val 0.93646
  Classification -> best τ=0.500 (val F1=0.1497)
  Directional -> Accuracy: 0.5707, MCC: -0.0988, F1: 0.7213

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62559 | val 1.76165
  Epoch 016 - train 0.57398 | val 2.43881
  Classification -> best τ=0.440 (val F1=0.0723)
  Directional -> Accuracy: 0.4495, MCC: 0.0277, F1: 0.6148

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.55426 | val 3.00543
  Epoch 016 - train 0.45386 | val 3.52901
  Classification -> best τ=0.390 (val F1=0.3039)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6567

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66412 | val 0.75205
  Epoch 020 - train 0.56805 | val 0.96840
  Classification -> best τ=0.500 (val F1=0.1839)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64601 | val 0.71278
  Epoch 016 - train 0.59162 | val 0.71603
  Classification -> best τ=0.485 (val F1=0.1396)
  Directional -> Accuracy: 0.4394, MCC: -0.1053, F1: 0.2649

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.66868 | val 1.00337
  Epoch 019 - train 0.55662 | val 0.92142
  Classification -> best τ=0.300 (val F1=0.1139)
  Directional -> Accuracy: 0.5657, MCC: 0.0000, F1: 0.7226

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.66927 | val 2.02102
  Epoch 020 - train 0.54047 | val 4.98220
  Classification -> best τ=0.050 (val F1=0.0823)
  Directional -> Accuracy: 0.4899, MCC: 0.0626, F1: 0.2628

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.66118 | val 0.71414
  Epoch 016 - train 0.60841 | val 0.74562
  Classification -> best τ=0.555 (val F1=0.2028)
  Directional -> Accuracy: 0.4697, MCC: -0.0344, F1: 0.1860

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.63544 | val 5.78906
  Epoch 016 - train 0.58618 | val 10.97845
  Classification -> best τ=0.495 (val F1=0.0847)
  Directional -> Accuracy: 0.5101, MCC: -0.0376, F1: 0.6734

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62245 | val 1.76369
  Epoch 016 - train 0.57718 | val 2.89202
  Classification -> best τ=0.190 (val F1=0.2008)
  Directional -> Accuracy: 0.5657, MCC: 0.1153, F1: 0.7014

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65203 | val 2.28988
  Epoch 017 - train 0.59186 | val 4.57232
  Classification -> best τ=0.215 (val F1=0.1283)
  Directional -> Accuracy: 0.4848, MCC: -0.0228, F1: 0.2817

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64329 | val 0.85013
  Epoch 016 - train 0.56666 | val 1.15313
  Classification -> best τ=0.530 (val F1=0.1998)
  Directional -> Accuracy: 0.5051, MCC: -0.0505, F1: 0.6597

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63747 | val 2.32210
  Epoch 016 - train 0.53615 | val 3.73561
  Classification -> best τ=0.070 (val F1=0.0814)
  Directional -> Accuracy: 0.5202, MCC: 0.0005, F1: 0.6275

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63382 | val 0.96236
  Epoch 016 - train 0.56869 | val 1.27557
  Classification -> best τ=0.645 (val F1=0.0308)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64074 | val 0.73233
  Epoch 018 - train 0.56136 | val 0.94812
  Classification -> best τ=0.435 (val F1=0.1853)
  Directional -> Accuracy: 0.5606, MCC: 0.0000, F1: 0.7184

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66390 | val 2.86045
  Epoch 019 - train 0.56700 | val 3.72963
  Classification -> best τ=0.115 (val F1=0.1334)
  Directional -> Accuracy: 0.6010, MCC: 0.1360, F1: 0.6926

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63962 | val 1.06316
  Epoch 020 - train 0.55212 | val 2.84696
  Classification -> best τ=0.435 (val F1=0.1638)
  Directional -> Accuracy: 0.5101, MCC: 0.0759, F1: 0.6473

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67439 | val 0.84264
  Epoch 016 - train 0.61460 | val 1.74904
  Classification -> best τ=0.505 (val F1=0.0846)
  Directional -> Accuracy: 0.4343, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66050 | val 0.75153
  Epoch 019 - train 0.57892 | val 0.83248
  Classification -> best τ=0.485 (val F1=0.1223)
  Directional -> Accuracy: 0.5354, MCC: -0.0568, F1: 0.6892

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60865 | val 1.28809
  Epoch 016 - train 0.55221 | val 1.40605
  Classification -> best τ=0.720 (val F1=0.1063)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64072 | val 0.72999
  Epoch 017 - train 0.57512 | val 0.78330
  Classification -> best τ=0.610 (val F1=0.1672)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.66481 | val 0.76772
  Epoch 020 - train 0.54784 | val 0.94013
  Classification -> best τ=0.455 (val F1=0.1278)
  Directional -> Accuracy: 0.4394, MCC: 0.0149, F1: 0.2550

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.60689 | val 1.71146
  Epoch 016 - train 0.52989 | val 2.31470
  Classification -> best τ=0.270 (val F1=0.2518)
  Directional -> Accuracy: 0.4949, MCC: -0.0015, F1: 0.6575

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66411 | val 1.53142
  Epoch 018 - train 0.58046 | val 3.31756
  Classification -> best τ=0.725 (val F1=0.0814)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64954 | val 1.03653
  Epoch 018 - train 0.53853 | val 1.50694
  Classification -> best τ=0.115 (val F1=0.1772)
  Directional -> Accuracy: 0.6061, MCC: 0.2054, F1: 0.7153

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.64393 | val 1.20560
  Epoch 017 - train 0.55060 | val 2.42681
  Classification -> best τ=0.365 (val F1=0.1570)
  Directional -> Accuracy: 0.5152, MCC: 0.0785, F1: 0.3514

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61205 | val 1.34494
  Epoch 016 - train 0.56966 | val 1.49639
  Classification -> best τ=0.205 (val F1=0.2158)
  Directional -> Accuracy: 0.4747, MCC: 0.0202, F1: 0.3953

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61482 | val 1.09656
  Epoch 016 - train 0.56493 | val 1.76703
  Classification -> best τ=0.380 (val F1=0.1925)
  Directional -> Accuracy: 0.4899, MCC: 0.0220, F1: 0.3311

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60884 | val 2.15709
  Epoch 017 - train 0.53408 | val 3.97895
  Classification -> best τ=0.120 (val F1=0.1044)
  Directional -> Accuracy: 0.4798, MCC: -0.0041, F1: 0.6460

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64291 | val 1.32081
  Epoch 016 - train 0.57998 | val 2.77088
  Classification -> best τ=0.360 (val F1=0.1642)
  Directional -> Accuracy: 0.4848, MCC: -0.0084, F1: 0.1207

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.62464 | val 0.97047
  Epoch 017 - train 0.53181 | val 1.31809
  Classification -> best τ=0.280 (val F1=0.0944)
  Directional -> Accuracy: 0.5354, MCC: 0.0481, F1: 0.3699

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.61944 | val 1.01078
  Epoch 016 - train 0.55387 | val 1.03715
  Classification -> best τ=0.335 (val F1=0.0065)
  Directional -> Accuracy: 0.5758, MCC: 0.0595, F1: 0.7273

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.65500 | val 0.99390
  Epoch 018 - train 0.57426 | val 2.73059
  Classification -> best τ=0.320 (val F1=0.1096)
  Directional -> Accuracy: 0.5859, MCC: 0.0662, F1: 0.7248

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.63842 | val 1.23059
  Epoch 017 - train 0.57848 | val 1.19529
  Classification -> best τ=0.490 (val F1=0.1116)
  Directional -> Accuracy: 0.4308, MCC: -0.0155, F1: 0.5714

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.67151 | val 0.67534
  Epoch 020 - train 0.54702 | val 1.24355
  Classification -> best τ=0.560 (val F1=0.2064)
  Directional -> Accuracy: 0.4798, MCC: 0.0483, F1: 0.0721

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.63539 | val 2.36485
  Epoch 016 - train 0.56109 | val 3.58064
  Classification -> best τ=0.570 (val F1=0.1180)
  Directional -> Accuracy: 0.5026, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64190 | val 0.99013
  Epoch 017 - train 0.55020 | val 2.45255
  Classification -> best τ=0.515 (val F1=0.2104)
  Directional -> Accuracy: 0.4697, MCC: -0.0407, F1: 0.4828

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.63455 | val 1.89343
  Epoch 016 - train 0.57141 | val 3.35907
  Classification -> best τ=0.515 (val F1=0.1811)
  Directional -> Accuracy: 0.5333, MCC: 0.0804, F1: 0.2602

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.65063 | val 1.54407
  Epoch 017 - train 0.56979 | val 2.05220
  Classification -> best τ=0.580 (val F1=0.1330)
  Directional -> Accuracy: 0.5253, MCC: 0.0700, F1: 0.4337

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61288 | val 4.41032
  Epoch 016 - train 0.53924 | val 6.28937
  Classification -> best τ=0.100 (val F1=0.1694)
  Directional -> Accuracy: 0.5152, MCC: 0.0000, F1: 0.6800

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.63757 | val 1.64176
  Epoch 016 - train 0.58889 | val 2.68843
  Classification -> best τ=0.815 (val F1=0.0288)
  Directional -> Accuracy: 0.5404, MCC: 0.0608, F1: 0.4485

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.64137 | val 0.94090
  Epoch 016 - train 0.59791 | val 1.24569
  Classification -> best τ=0.600 (val F1=0.1804)
  Directional -> Accuracy: 0.4697, MCC: -0.0404, F1: 0.0367

[75/88] Processing T...


[I 2026-02-26 04:22:51,302] Trial 38 finished with value: 0.1560660322497637 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.006597985447124883, 'weight_decay': 1.0239539653424162e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.3738987412879409, 'early_stopping_min_delta': 0.0016179650816007406}. Best is trial 38 with value: 0.1560660322497637.

  Epoch 019 - train 0.57538 | val 1.43952
  Classification -> best τ=0.130 (val F1=0.0997)
  Directional -> Accuracy: 0.5152, MCC: 0.1421, F1: 0.6712

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1560660322497637
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68278 | val 0.71036
  Epoch 016 - train 0.66152 | val 0.70450
  Classification -> best τ=0.525 (val F1=0.1207)
  Directional -> Accuracy: 0.4141, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.66727 | val 0.89040
  Epoch 016 - train 0.64665 | val 1.03199
  Classification -> best τ=0.530 (val F1=0.1164)
  Directional -> Accuracy: 0.5051, MCC: 0.0712, F1: 0.0200

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67049 | val 0.73439
  Epoch 019 - train 0.65245 | val 0.73442
  Classification -> best τ=0.445 (val F1=0.2007)
  Directional -> Accuracy: 0.5081, MCC: -0.0441, F1: 0.6094

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.67060 | val 0.97523
  Epoch 016 - train 0.67096 | val 1.08112
  Classification -> best τ=0.515 (val F1=0.1147)
  Directional -> Accuracy: 0.4646, MCC: 0.0945, F1: 0.1452

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.66278 | val 0.71565
  Epoch 016 - train 0.64143 | val 0.73846
  Classification -> best τ=0.535 (val F1=0.1397)
  Directional -> Accuracy: 0.5377, MCC: 0.0756, F1: 0.5505

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66430 | val 0.82401
  Epoch 016 - train 0.65049 | val 0.86408
  Classification -> best τ=0.460 (val F1=0.1323)
  Directional -> Accuracy: 0.5202, MCC: 0.0114, F1: 0.5992

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66071 | val 1.41863
  Epoch 016 - train 0.66101 | val 1.68390
  Classification -> best τ=0.540 (val F1=0.0881)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65798 | val 0.66896
  Epoch 020 - train 0.64639 | val 0.66936
  Classification -> best τ=0.460 (val F1=0.2565)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66475 | val 0.71901
  Epoch 016 - train 0.65464 | val 0.73692
  Classification -> best τ=0.490 (val F1=0.1603)
  Directional -> Accuracy: 0.4248, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67419 | val 0.71511
  Epoch 016 - train 0.66272 | val 0.72315
  Classification -> best τ=0.520 (val F1=0.0522)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.65280 | val 1.26365
  Epoch 016 - train 0.64650 | val 1.48279
  Classification -> best τ=0.495 (val F1=0.0141)
  Directional -> Accuracy: 0.5303, MCC: 0.0759, F1: 0.5079

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.66432 | val 0.72975
  Epoch 016 - train 0.64850 | val 0.73569
  Classification -> best τ=0.480 (val F1=0.0736)
  Directional -> Accuracy: 0.4242, MCC: -0.0220, F1: 0.0339

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65724 | val 0.94349
  Epoch 017 - train 0.64548 | val 1.00740
  Classification -> best τ=0.480 (val F1=0.0823)
  Directional -> Accuracy: 0.5253, MCC: 0.0070, F1: 0.6179

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67196 | val 0.82035
  Epoch 016 - train 0.65463 | val 0.83236
  Classification -> best τ=0.500 (val F1=0.1030)
  Directional -> Accuracy: 0.4747, MCC: -0.0872, F1: 0.6338

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.67315 | val 0.72119
  Epoch 016 - train 0.65435 | val 0.72041
  Classification -> best τ=0.500 (val F1=0.0444)
  Directional -> Accuracy: 0.5152, MCC: -0.0033, F1: 0.6279

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.66485 | val 0.77565
  Epoch 016 - train 0.65096 | val 0.80109
  Classification -> best τ=0.485 (val F1=0.0774)
  Directional -> Accuracy: 0.5202, MCC: 0.0449, F1: 0.6058

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.66946 | val 0.69400
  Epoch 020 - train 0.65972 | val 0.72900
  Classification -> best τ=0.390 (val F1=0.1759)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65914 | val 0.69431
  Epoch 020 - train 0.65722 | val 0.70392
  Classification -> best τ=0.665 (val F1=0.1978)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65337 | val 0.68829
  Epoch 020 - train 0.63531 | val 0.70938
  Classification -> best τ=0.590 (val F1=0.2430)
  Directional -> Accuracy: 0.4899, MCC: -0.0179, F1: 0.2519

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66694 | val 0.69807
  Epoch 016 - train 0.66277 | val 0.71011
  Classification -> best τ=0.490 (val F1=0.0697)
  Directional -> Accuracy: 0.4646, MCC: 0.0657, F1: 0.0185

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.66517 | val 0.69335
  Epoch 019 - train 0.64712 | val 0.70626
  Classification -> best τ=0.525 (val F1=0.1991)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.6576

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.67739 | val 1.26355
  Epoch 016 - train 0.66424 | val 1.46211
  Classification -> best τ=0.465 (val F1=0.1783)
  Directional -> Accuracy: 0.4343, MCC: -0.0509, F1: 0.0508

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67009 | val 0.82107
  Epoch 016 - train 0.65198 | val 0.84483
  Classification -> best τ=0.515 (val F1=0.0598)
  Directional -> Accuracy: 0.5354, MCC: 0.0243, F1: 0.6593

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.67126 | val 0.74410
  Epoch 016 - train 0.65407 | val 0.77777
  Classification -> best τ=0.560 (val F1=0.0980)
  Directional -> Accuracy: 0.6061, MCC: 0.0000, F1: 0.0000

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66202 | val 1.21105
  Epoch 016 - train 0.64986 | val 1.45985
  Classification -> best τ=0.500 (val F1=0.1943)
  Directional -> Accuracy: 0.5859, MCC: 0.1657, F1: 0.6273

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65921 | val 0.71745
  Epoch 018 - train 0.64562 | val 0.77885
  Classification -> best τ=0.495 (val F1=0.2144)
  Directional -> Accuracy: 0.5101, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65620 | val 1.03392
  Epoch 016 - train 0.64941 | val 1.31572
  Classification -> best τ=0.540 (val F1=0.1123)
  Directional -> Accuracy: 0.4798, MCC: 0.0782, F1: 0.1488

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.67105 | val 1.00120
  Epoch 016 - train 0.65989 | val 1.13792
  Classification -> best τ=0.540 (val F1=0.0676)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66924 | val 0.72890
  Epoch 016 - train 0.65595 | val 0.76997
  Classification -> best τ=0.490 (val F1=0.0672)
  Directional -> Accuracy: 0.5152, MCC: 0.0307, F1: 0.5152

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.66521 | val 1.26728
  Epoch 016 - train 0.65197 | val 1.48035
  Classification -> best τ=0.515 (val F1=0.0589)
  Directional -> Accuracy: 0.5404, MCC: -0.0650, F1: 0.7016

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.66638 | val 0.76918
  Epoch 016 - train 0.64868 | val 0.81287
  Classification -> best τ=0.525 (val F1=0.1461)
  Directional -> Accuracy: 0.4747, MCC: -0.0469, F1: 0.4023

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67523 | val 0.80509
  Epoch 016 - train 0.65827 | val 0.80761
  Classification -> best τ=0.480 (val F1=0.1165)
  Directional -> Accuracy: 0.5253, MCC: 0.0250, F1: 0.5983

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.67014 | val 0.69532
  Epoch 016 - train 0.67080 | val 0.69814
  Classification -> best τ=0.485 (val F1=0.1331)
  Directional -> Accuracy: 0.5152, MCC: -0.0399, F1: 0.6160

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67674 | val 1.08230
  Epoch 016 - train 0.66635 | val 1.17472
  Classification -> best τ=0.485 (val F1=0.0778)
  Directional -> Accuracy: 0.5000, MCC: 0.0091, F1: 0.4923

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.66413 | val 0.71608
  Epoch 016 - train 0.60606 | val 0.77413
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67021 | val 0.81628
  Epoch 016 - train 0.64701 | val 0.83554
  Classification -> best τ=0.440 (val F1=0.1351)
  Directional -> Accuracy: 0.4444, MCC: -0.0168, F1: 0.2857

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65768 | val 0.75113
  Epoch 016 - train 0.64819 | val 0.76516
  Classification -> best τ=0.500 (val F1=0.1051)
  Directional -> Accuracy: 0.4596, MCC: -0.0698, F1: 0.0360

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.67018 | val 0.90099
  Epoch 016 - train 0.65802 | val 0.95027
  Classification -> best τ=0.540 (val F1=0.0703)
  Directional -> Accuracy: 0.5152, MCC: -0.0559, F1: 0.6418

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.66640 | val 1.52392
  Epoch 016 - train 0.66023 | val 1.85509
  Classification -> best τ=0.495 (val F1=0.0690)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.66534 | val 0.69521
  Epoch 016 - train 0.65589 | val 0.70139
  Classification -> best τ=0.545 (val F1=0.1160)
  Directional -> Accuracy: 0.4798, MCC: 0.0070, F1: 0.1197

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.66849 | val 0.69953
  Epoch 016 - train 0.66855 | val 0.70369
  Classification -> best τ=0.555 (val F1=0.0806)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67402 | val 0.81406
  Epoch 016 - train 0.66084 | val 0.85850
  Classification -> best τ=0.475 (val F1=0.1023)
  Directional -> Accuracy: 0.5455, MCC: 0.0418, F1: 0.6939

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67304 | val 0.85937
  Epoch 016 - train 0.65836 | val 0.91677
  Classification -> best τ=0.480 (val F1=0.0959)
  Directional -> Accuracy: 0.4798, MCC: -0.0351, F1: 0.3439

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67880 | val 0.69379
  Epoch 016 - train 0.66516 | val 0.69604
  Classification -> best τ=0.505 (val F1=0.0690)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65639 | val 1.23754
  Epoch 016 - train 0.66206 | val 1.50238
  Classification -> best τ=0.430 (val F1=0.1122)
  Directional -> Accuracy: 0.5505, MCC: 0.0609, F1: 0.6855

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66340 | val 0.77604
  Epoch 016 - train 0.65585 | val 0.78504
  Classification -> best τ=0.510 (val F1=0.0596)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67937 | val 0.70974
  Epoch 016 - train 0.65531 | val 0.74201
  Classification -> best τ=0.455 (val F1=0.0561)
  Directional -> Accuracy: 0.5606, MCC: 0.0000, F1: 0.7184

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66980 | val 0.79911
  Epoch 016 - train 0.65479 | val 0.92022
  Classification -> best τ=0.445 (val F1=0.0443)
  Directional -> Accuracy: 0.5404, MCC: 0.0640, F1: 0.5991

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66762 | val 0.73512
  Epoch 019 - train 0.65182 | val 0.71046
  Classification -> best τ=0.600 (val F1=0.1785)
  Directional -> Accuracy: 0.5303, MCC: 0.0531, F1: 0.3111

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66887 | val 0.69649
  Epoch 016 - train 0.64911 | val 0.69152
  Classification -> best τ=0.505 (val F1=0.0631)
  Directional -> Accuracy: 0.4848, MCC: 0.0559, F1: 0.3377

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66835 | val 1.04380
  Epoch 016 - train 0.65891 | val 1.15241
  Classification -> best τ=0.510 (val F1=0.1405)
  Directional -> Accuracy: 0.4192, MCC: -0.1185, F1: 0.1606

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66456 | val 0.77349
  Epoch 016 - train 0.64468 | val 0.81110
  Classification -> best τ=0.445 (val F1=0.0747)
  Directional -> Accuracy: 0.4949, MCC: -0.0028, F1: 0.1228

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66691 | val 0.82171
  Epoch 016 - train 0.66371 | val 0.78528
  Classification -> best τ=0.455 (val F1=0.0826)
  Directional -> Accuracy: 0.4798, MCC: -0.0357, F1: 0.2482

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.66535 | val 1.27118
  Epoch 016 - train 0.66774 | val 1.43454
  Classification -> best τ=0.465 (val F1=0.0298)
  Directional -> Accuracy: 0.5404, MCC: 0.0242, F1: 0.6316

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.66141 | val 1.02658
  Epoch 016 - train 0.66538 | val 1.07523
  Classification -> best τ=0.475 (val F1=0.1341)
  Directional -> Accuracy: 0.4747, MCC: -0.0872, F1: 0.6338

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66418 | val 0.79830
  Epoch 016 - train 0.65413 | val 0.85286
  Classification -> best τ=0.545 (val F1=0.0854)
  Directional -> Accuracy: 0.4596, MCC: -0.0950, F1: 0.0696

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64273 | val 0.74346
  Epoch 016 - train 0.64024 | val 0.78357
  Classification -> best τ=0.520 (val F1=0.0724)
  Directional -> Accuracy: 0.4495, MCC: -0.0528, F1: 0.0180

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.66760 | val 1.22052
  Epoch 016 - train 0.66950 | val 1.39815
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.6931

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65959 | val 0.71887
  Epoch 016 - train 0.64724 | val 0.78164
  Classification -> best τ=0.495 (val F1=0.1791)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65685 | val 0.89635
  Epoch 016 - train 0.64141 | val 0.94269
  Classification -> best τ=0.515 (val F1=0.1514)
  Directional -> Accuracy: 0.5051, MCC: 0.0789, F1: 0.2899

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66989 | val 0.84811
  Epoch 016 - train 0.66033 | val 0.87699
  Classification -> best τ=0.505 (val F1=0.0369)
  Directional -> Accuracy: 0.5202, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65873 | val 0.79161
  Epoch 016 - train 0.64627 | val 0.80394
  Classification -> best τ=0.530 (val F1=0.1133)
  Directional -> Accuracy: 0.5051, MCC: 0.0770, F1: 0.1404

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.66818 | val 0.90309
  Epoch 016 - train 0.64286 | val 0.93415
  Classification -> best τ=0.525 (val F1=0.0944)
  Directional -> Accuracy: 0.4949, MCC: -0.0101, F1: 0.4792

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.66026 | val 0.78175
  Epoch 016 - train 0.64958 | val 0.80869
  Classification -> best τ=0.470 (val F1=0.0932)
  Directional -> Accuracy: 0.4495, MCC: -0.0210, F1: 0.2876

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.65642 | val 1.45598
  Epoch 016 - train 0.66541 | val 1.72575
  Classification -> best τ=0.510 (val F1=0.0980)
  Directional -> Accuracy: 0.4495, MCC: 0.0115, F1: 0.2585

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.65674 | val 0.69298
  Epoch 020 - train 0.62821 | val 0.72352
  Classification -> best τ=0.565 (val F1=0.2093)
  Directional -> Accuracy: 0.5282, MCC: 0.0481, F1: 0.4713

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.66277 | val 0.69532
  Epoch 019 - train 0.65716 | val 0.70187
  Classification -> best τ=0.535 (val F1=0.0651)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.66665 | val 0.68990
  Epoch 020 - train 0.65237 | val 0.70804
  Classification -> best τ=0.460 (val F1=0.1576)
  Directional -> Accuracy: 0.5077, MCC: 0.0149, F1: 0.3333

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65767 | val 0.89631
  Epoch 018 - train 0.64221 | val 0.98349
  Classification -> best τ=0.545 (val F1=0.1546)
  Directional -> Accuracy: 0.5354, MCC: 0.0688, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.66322 | val 0.72170
  Epoch 016 - train 0.65343 | val 0.82704
  Classification -> best τ=0.500 (val F1=0.0998)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.6598

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.67673 | val 0.83873
  Epoch 016 - train 0.66320 | val 0.87047
  Classification -> best τ=0.555 (val F1=0.1693)
  Directional -> Accuracy: 0.4949, MCC: 0.0088, F1: 0.3671

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66921 | val 1.35706
  Epoch 016 - train 0.66295 | val 1.42971
  Classification -> best τ=0.425 (val F1=0.2064)
  Directional -> Accuracy: 0.5152, MCC: 0.0000, F1: 0.6800

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.67296 | val 1.12632
  Epoch 016 - train 0.66057 | val 1.13167
  Classification -> best τ=0.580 (val F1=0.0278)
  Directional -> Accuracy: 0.6010, MCC: 0.1834, F1: 0.4060

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.67441 | val 0.85431
  Epoch 016 - train 0.66039 | val 0.89634
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5253, MCC: 0.0000, F1: 0.6887

[75/88] Processing T...


[I 2026-02-26 04:29:00,374] Trial 39 finished with value: 0.11078384891682741 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.000426541738722336, 'weight_decay': 0.0003068596100466441, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.5411385962668627, 'early_stopping_min_delta': 0.0038724789377326796}. Best is trial 38 with value: 0.1560660322497637.

  Epoch 016 - train 0.65574 | val 0.77511
  Classification -> best τ=0.525 (val F1=0.1616)
  Directional -> Accuracy: 0.4899, MCC: -0.0195, F1: 0.5073

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.11078384891682741
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.73973 | val 0.83630
  Epoch 016 - train 0.71911 | val 0.83472
  Classification -> best τ=0.495 (val F1=0.0144)
  Directional -> Accuracy: 0.4899, MCC: 0.0339, F1: 0.4541

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.71643 | val 0.75287
  Epoch 016 - train 0.71666 | val 0.76054
  Classification -> best τ=0.490 (val F1=0.2087)
  Directional -> Accuracy: 0.5152, MCC: 0.0374, F1: 0.3143

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.72976 | val 0.70182
  Epoch 016 - train 0.70893 | val 0.70143
  Classification -> best τ=0.525 (val F1=0.0757)
  Directional -> Accuracy: 0.5838, MCC: 0.0863, F1: 0.7354

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.71047 | val 0.75207
  Epoch 016 - train 0.69853 | val 0.75623
  Classification -> best τ=0.400 (val F1=0.1087)
  Directional -> Accuracy: 0.5556, MCC: -0.0885, F1: 0.7143

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.69769 | val 0.82181
  Epoch 016 - train 0.73238 | val 0.81726
  Classification -> best τ=0.460 (val F1=0.0113)
  Directional -> Accuracy: 0.5189, MCC: 0.1356, F1: 0.2388

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71104 | val 0.70937
  Epoch 016 - train 0.70589 | val 0.70732
  Classification -> best τ=0.560 (val F1=0.1097)
  Directional -> Accuracy: 0.5051, MCC: 0.0429, F1: 0.4494

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.72187 | val 0.76050
  Epoch 016 - train 0.72531 | val 0.76047
  Classification -> best τ=0.410 (val F1=0.0375)
  Directional -> Accuracy: 0.5354, MCC: 0.0338, F1: 0.6230

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.71509 | val 0.68140
  Epoch 020 - train 0.70732 | val 0.67355
  Classification -> best τ=0.495 (val F1=0.2425)
  Directional -> Accuracy: 0.4596, MCC: 0.0403, F1: 0.3669

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70450 | val 0.69958
  Epoch 017 - train 0.71917 | val 0.69922
  Classification -> best τ=0.485 (val F1=0.1846)
  Directional -> Accuracy: 0.5044, MCC: 0.0870, F1: 0.4167

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71171 | val 0.71547
  Epoch 016 - train 0.71009 | val 0.71623
  Classification -> best τ=0.640 (val F1=0.1386)
  Directional -> Accuracy: 0.5253, MCC: -0.1144, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.70336 | val 0.77244
  Epoch 016 - train 0.70071 | val 0.77159
  Classification -> best τ=0.430 (val F1=0.1378)
  Directional -> Accuracy: 0.4747, MCC: -0.0335, F1: 0.4348

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.71201 | val 0.72588
  Epoch 016 - train 0.69027 | val 0.72870
  Classification -> best τ=0.465 (val F1=0.1137)
  Directional -> Accuracy: 0.4394, MCC: -0.0239, F1: 0.2345

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70348 | val 0.69310
  Epoch 017 - train 0.69743 | val 0.69581
  Classification -> best τ=0.635 (val F1=0.1068)
  Directional -> Accuracy: 0.4444, MCC: -0.0074, F1: 0.0984

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70232 | val 0.72559
  Epoch 016 - train 0.71136 | val 0.72558
  Classification -> best τ=0.590 (val F1=0.1660)
  Directional -> Accuracy: 0.5202, MCC: 0.0397, F1: 0.3949

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.71466 | val 0.69808
  Epoch 020 - train 0.70394 | val 0.69406
  Classification -> best τ=0.645 (val F1=0.1206)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.70764 | val 0.70876
  Epoch 016 - train 0.70055 | val 0.71044
  Classification -> best τ=0.565 (val F1=0.0439)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.73985 | val 0.72645
  Epoch 016 - train 0.72849 | val 0.72695
  Classification -> best τ=0.515 (val F1=0.1352)
  Directional -> Accuracy: 0.5455, MCC: 0.0838, F1: 0.5833

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.72944 | val 0.73527
  Epoch 016 - train 0.71209 | val 0.73112
  Classification -> best τ=0.570 (val F1=0.0582)
  Directional -> Accuracy: 0.5152, MCC: 0.0747, F1: 0.2615

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.72645 | val 0.72775
  Epoch 016 - train 0.70924 | val 0.72650
  Classification -> best τ=0.425 (val F1=0.1594)
  Directional -> Accuracy: 0.4697, MCC: -0.0756, F1: 0.1860

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.72636 | val 0.72308
  Epoch 016 - train 0.72801 | val 0.72065
  Classification -> best τ=0.495 (val F1=0.1297)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.70287 | val 0.69227
  Epoch 016 - train 0.72440 | val 0.69280
  Classification -> best τ=0.440 (val F1=0.1249)
  Directional -> Accuracy: 0.4949, MCC: 0.0388, F1: 0.6575

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.70581 | val 0.73020
  Epoch 016 - train 0.71053 | val 0.72820
  Classification -> best τ=0.375 (val F1=0.0759)
  Directional -> Accuracy: 0.5606, MCC: 0.0000, F1: 0.7184

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.71442 | val 0.72839
  Epoch 016 - train 0.71099 | val 0.73000
  Classification -> best τ=0.435 (val F1=0.2193)
  Directional -> Accuracy: 0.4747, MCC: -0.0077, F1: 0.3158

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.71096 | val 0.71269
  Epoch 016 - train 0.71145 | val 0.71535
  Classification -> best τ=0.485 (val F1=0.0922)
  Directional -> Accuracy: 0.3939, MCC: 0.0000, F1: 0.5652

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71345 | val 0.73624
  Epoch 016 - train 0.71335 | val 0.74346
  Classification -> best τ=0.405 (val F1=0.1254)
  Directional -> Accuracy: 0.5000, MCC: 0.0237, F1: 0.3851

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70918 | val 0.69743
  Epoch 016 - train 0.70523 | val 0.69505
  Classification -> best τ=0.505 (val F1=0.1753)
  Directional -> Accuracy: 0.5051, MCC: 0.0400, F1: 0.6397

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70276 | val 0.71201
  Epoch 016 - train 0.70251 | val 0.71055
  Classification -> best τ=0.630 (val F1=0.1136)
  Directional -> Accuracy: 0.4545, MCC: -0.0131, F1: 0.0357

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.71736 | val 0.71746
  Epoch 016 - train 0.71022 | val 0.71629
  Classification -> best τ=0.615 (val F1=0.1147)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70008 | val 0.69931
  Epoch 016 - train 0.70439 | val 0.70025
  Classification -> best τ=0.505 (val F1=0.0797)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.71198 | val 0.69010
  Epoch 020 - train 0.68601 | val 0.69011
  Classification -> best τ=0.515 (val F1=0.1193)
  Directional -> Accuracy: 0.4949, MCC: 0.0459, F1: 0.3506

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.70066 | val 0.70344
  Epoch 016 - train 0.70903 | val 0.70414
  Classification -> best τ=0.455 (val F1=0.1137)
  Directional -> Accuracy: 0.5455, MCC: 0.1083, F1: 0.4375

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70669 | val 0.74907
  Epoch 016 - train 0.70485 | val 0.74976
  Classification -> best τ=0.385 (val F1=0.0546)
  Directional -> Accuracy: 0.5505, MCC: 0.0103, F1: 0.7082

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.70645 | val 0.70428
  Epoch 016 - train 0.69706 | val 0.70412
  Classification -> best τ=0.375 (val F1=0.1065)
  Directional -> Accuracy: 0.6111, MCC: 0.0000, F1: 0.7586

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69789 | val 0.71591
  Epoch 016 - train 0.69162 | val 0.71453
  Classification -> best τ=0.610 (val F1=0.1231)
  Directional -> Accuracy: 0.5505, MCC: 0.0000, F1: 0.0825

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.75059 | val 0.70065
  Epoch 016 - train 0.70770 | val 0.70157
  Classification -> best τ=0.540 (val F1=0.1376)
  Directional -> Accuracy: 0.4783, MCC: -0.0436, F1: 0.5000

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.71507 | val 0.70994
  Epoch 016 - train 0.71022 | val 0.70676
  Classification -> best τ=0.580 (val F1=0.0567)
  Directional -> Accuracy: 0.4949, MCC: -0.0880, F1: 0.6094

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.71990 | val 0.72223
  Epoch 016 - train 0.70778 | val 0.72017
  Classification -> best τ=0.405 (val F1=0.1054)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.6931

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.73354 | val 0.78574
  Epoch 016 - train 0.71279 | val 0.78772
  Classification -> best τ=0.280 (val F1=0.1120)
  Directional -> Accuracy: 0.5657, MCC: 0.0000, F1: 0.7226

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.70870 | val 0.70179
  Epoch 016 - train 0.69744 | val 0.70429
  Classification -> best τ=0.360 (val F1=0.1143)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.71220 | val 0.73093
  Epoch 016 - train 0.70795 | val 0.73509
  Classification -> best τ=0.535 (val F1=0.1054)
  Directional -> Accuracy: 0.4343, MCC: -0.1394, F1: 0.1385

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.71961 | val 0.98802
  Epoch 016 - train 0.69706 | val 0.96862
  Classification -> best τ=0.320 (val F1=0.0414)
  Directional -> Accuracy: 0.4646, MCC: -0.0915, F1: 0.5620

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69300 | val 0.69871
  Epoch 016 - train 0.70259 | val 0.70058
  Classification -> best τ=0.480 (val F1=0.0854)
  Directional -> Accuracy: 0.5455, MCC: 0.0773, F1: 0.7039

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69520 | val 0.69862
  Epoch 020 - train 0.70744 | val 0.69161
  Classification -> best τ=0.465 (val F1=0.1405)
  Directional -> Accuracy: 0.5253, MCC: 0.1266, F1: 0.6824

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.72030 | val 0.70653
  Epoch 020 - train 0.70556 | val 0.69722
  Classification -> best τ=0.430 (val F1=0.1207)
  Directional -> Accuracy: 0.5202, MCC: 0.0000, F1: 0.6844

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.71297 | val 0.73501
  Epoch 016 - train 0.71894 | val 0.74017
  Classification -> best τ=0.525 (val F1=0.1869)
  Directional -> Accuracy: 0.4596, MCC: -0.0206, F1: 0.1008

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70463 | val 0.71742
  Epoch 016 - train 0.70211 | val 0.71814
  Classification -> best τ=0.445 (val F1=0.2045)
  Directional -> Accuracy: 0.5960, MCC: 0.0632, F1: 0.7403

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71632 | val 0.72257
  Epoch 016 - train 0.71407 | val 0.72167
  Classification -> best τ=0.525 (val F1=0.0614)
  Directional -> Accuracy: 0.4646, MCC: 0.1144, F1: 0.1017

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.71051 | val 0.71085
  Epoch 016 - train 0.71302 | val 0.71289
  Classification -> best τ=0.525 (val F1=0.1523)
  Directional -> Accuracy: 0.5505, MCC: -0.0036, F1: 0.6691

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71663 | val 0.86972
  Epoch 016 - train 0.70364 | val 0.87164
  Classification -> best τ=0.380 (val F1=0.1015)
  Directional -> Accuracy: 0.4798, MCC: -0.0285, F1: 0.5863

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68876 | val 0.70618
  Epoch 016 - train 0.70083 | val 0.70762
  Classification -> best τ=0.410 (val F1=0.1076)
  Directional -> Accuracy: 0.5707, MCC: 0.0544, F1: 0.7157

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72294 | val 0.76680
  Epoch 016 - train 0.72037 | val 0.76563
  Classification -> best τ=0.365 (val F1=0.1268)
  Directional -> Accuracy: 0.5354, MCC: 0.0056, F1: 0.6567

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69521 | val 0.70127
  Epoch 016 - train 0.69217 | val 0.70102
  Classification -> best τ=0.480 (val F1=0.0758)
  Directional -> Accuracy: 0.4697, MCC: -0.0761, F1: 0.5783

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70727 | val 0.74072
  Epoch 016 - train 0.70392 | val 0.74097
  Classification -> best τ=0.445 (val F1=0.0700)
  Directional -> Accuracy: 0.4848, MCC: -0.0320, F1: 0.5096

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.68474 | val 0.68855
  Epoch 017 - train 0.69717 | val 0.68915
  Classification -> best τ=0.470 (val F1=0.1064)
  Directional -> Accuracy: 0.4596, MCC: -0.0360, F1: 0.4456

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.70406 | val 0.70092
  Epoch 016 - train 0.68708 | val 0.70112
  Classification -> best τ=0.465 (val F1=0.1264)
  Directional -> Accuracy: 0.4697, MCC: -0.0643, F1: 0.5749

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.72667 | val 0.76558
  Epoch 016 - train 0.71696 | val 0.76537
  Classification -> best τ=0.550 (val F1=0.0867)
  Directional -> Accuracy: 0.4646, MCC: -0.0899, F1: 0.0364

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70144 | val 0.76242
  Epoch 016 - train 0.71220 | val 0.76183
  Classification -> best τ=0.460 (val F1=0.0065)
  Directional -> Accuracy: 0.5101, MCC: -0.0226, F1: 0.6135

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.70197 | val 0.80657
  Epoch 016 - train 0.71728 | val 0.79599
  Classification -> best τ=0.700 (val F1=0.0034)
  Directional -> Accuracy: 0.4596, MCC: -0.0578, F1: 0.0855

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.71261 | val 0.70232
  Epoch 020 - train 0.71591 | val 0.68549
  Classification -> best τ=0.660 (val F1=0.1672)
  Directional -> Accuracy: 0.4242, MCC: -0.0174, F1: 0.0952

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.73281 | val 0.72822
  Epoch 016 - train 0.71841 | val 0.72304
  Classification -> best τ=0.645 (val F1=0.0666)
  Directional -> Accuracy: 0.4747, MCC: -0.0072, F1: 0.2676

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.71084 | val 0.70738
  Epoch 016 - train 0.71154 | val 0.71307
  Classification -> best τ=0.535 (val F1=0.1651)
  Directional -> Accuracy: 0.5152, MCC: 0.0064, F1: 0.2727

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70504 | val 0.71529
  Epoch 016 - train 0.70730 | val 0.71725
  Classification -> best τ=0.445 (val F1=0.1331)
  Directional -> Accuracy: 0.4697, MCC: -0.0526, F1: 0.2857

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.72380 | val 0.70929
  Epoch 016 - train 0.71198 | val 0.70793
  Classification -> best τ=0.620 (val F1=0.1141)
  Directional -> Accuracy: 0.4596, MCC: -0.0613, F1: 0.5408

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.74198 | val 0.80357
  Epoch 016 - train 0.70783 | val 0.79639
  Classification -> best τ=0.570 (val F1=0.0744)
  Directional -> Accuracy: 0.5707, MCC: 0.0000, F1: 0.7267

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.73750 | val 0.78411
  Epoch 016 - train 0.73838 | val 0.78543
  Classification -> best τ=0.425 (val F1=0.0830)
  Directional -> Accuracy: 0.5303, MCC: 0.0403, F1: 0.5903

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.73158 | val 0.84816
  Epoch 016 - train 0.71441 | val 0.85204
  Classification -> best τ=0.450 (val F1=0.0700)
  Directional -> Accuracy: 0.4205, MCC: 0.0000, F1: 0.5921

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.69673 | val 0.68955
  Epoch 016 - train 0.70913 | val 0.68873
  Classification -> best τ=0.375 (val F1=0.1362)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.6931

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.70918 | val 0.71874
  Epoch 016 - train 0.72167 | val 0.72179
  Classification -> best τ=0.600 (val F1=0.1600)
  Directional -> Accuracy: 0.4154, MCC: -0.1742, F1: 0.3448

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71399 | val 0.70314
  Epoch 020 - train 0.71292 | val 0.69750
  Classification -> best τ=0.525 (val F1=0.1329)
  Directional -> Accuracy: 0.5455, MCC: 0.0247, F1: 0.2969

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.72102 | val 0.72537
  Epoch 016 - train 0.70731 | val 0.72562
  Classification -> best τ=0.375 (val F1=0.1269)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.6598

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.69769 | val 0.72961
  Epoch 016 - train 0.71045 | val 0.73400
  Classification -> best τ=0.485 (val F1=0.1304)
  Directional -> Accuracy: 0.5505, MCC: 0.0927, F1: 0.6276

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71480 | val 0.92486
  Epoch 016 - train 0.70381 | val 0.94087
  Classification -> best τ=0.355 (val F1=0.1138)
  Directional -> Accuracy: 0.4848, MCC: -0.0717, F1: 0.6222

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.71432 | val 0.79613
  Epoch 016 - train 0.69870 | val 0.78821
  Classification -> best τ=0.365 (val F1=0.1502)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.71053 | val 0.71514
  Epoch 016 - train 0.69749 | val 0.71606
  Classification -> best τ=0.540 (val F1=0.0779)
  Directional -> Accuracy: 0.4343, MCC: -0.1236, F1: 0.2533


[I 2026-02-26 04:36:14,532] Trial 40 finished with value: 0.11263787005848594 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 1.365958130551427e-05, 'weight_decay': 1.8465408533018845e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.406795234216919, 'early_stopping_min_delta': 0.0017020844179159234}. Best is trial 38 with value: 0.1560660322497637.

  Epoch 016 - train 0.72180 | val 0.71501
  Classification -> best τ=0.650 (val F1=0.0679)
  Directional -> Accuracy: 0.4949, MCC: -0.1000, F1: 0.0000

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.11263787005848594
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 15
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63631 | val 1.49893
  Epoch 016 - train 0.60381 | val 2.47768
  Classification -> best τ=0.795 (val F1=0.1576)
  Directional -> Accuracy: 0.4141, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.60456 | val 3.94287
  Epoch 016 - train 0.51765 | val 6.23710
  Classification -> best τ=0.425 (val F1=0.1761)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68105 | val 0.75017
  Epoch 020 - train 0.55813 | val 0.84565
  Classification -> best τ=0.315 (val F1=0.1669)
  Directional -> Accuracy: 0.5514, MCC: -0.0021, F1: 0.6820

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.65391 | val 0.75549
  Epoch 017 - train 0.60078 | val 1.07719
  Classification -> best τ=0.590 (val F1=0.1195)
  Directional -> Accuracy: 0.4343, MCC: -0.0419, F1: 0.1385

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.59881 | val 0.76682
  Epoch 016 - train 0.56687 | val 0.79943
  Classification -> best τ=0.565 (val F1=0.1377)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67559 | val 0.84053
  Epoch 019 - train 0.58569 | val 1.64716
  Classification -> best τ=0.680 (val F1=0.1731)
  Directional -> Accuracy: 0.4697, MCC: 0.0287, F1: 0.1985

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67959 | val 0.88146
  Epoch 019 - train 0.59888 | val 1.90921
  Classification -> best τ=0.475 (val F1=0.1403)
  Directional -> Accuracy: 0.4899, MCC: 0.0419, F1: 0.3648

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64685 | val 0.93229
  Epoch 017 - train 0.57698 | val 1.44082
  Classification -> best τ=0.410 (val F1=0.2583)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57117 | val 0.85642
  Epoch 016 - train 0.49064 | val 0.89837
  Classification -> best τ=0.435 (val F1=0.1859)
  Directional -> Accuracy: 0.5664, MCC: -0.0306, F1: 0.7200

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65202 | val 1.93497
  Epoch 016 - train 0.58411 | val 4.19054
  Classification -> best τ=0.465 (val F1=0.1088)
  Directional -> Accuracy: 0.4697, MCC: 0.0276, F1: 0.6237

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.65369 | val 1.48173
  Epoch 016 - train 0.59176 | val 1.51621
  Classification -> best τ=0.685 (val F1=0.1136)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.63824 | val 1.06480
  Epoch 016 - train 0.56473 | val 1.37481
  Classification -> best τ=0.390 (val F1=0.1212)
  Directional -> Accuracy: 0.4495, MCC: 0.1090, F1: 0.0992

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61624 | val 1.02523
  Epoch 016 - train 0.56766 | val 1.73474
  Classification -> best τ=0.590 (val F1=0.1581)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65881 | val 0.72724
  Epoch 019 - train 0.56495 | val 1.43742
  Classification -> best τ=0.555 (val F1=0.2215)
  Directional -> Accuracy: 0.5101, MCC: 0.0211, F1: 0.1565

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.62850 | val 1.72912
  Epoch 016 - train 0.57747 | val 2.41795
  Classification -> best τ=0.455 (val F1=0.1035)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.64078 | val 1.18554
  Epoch 016 - train 0.56204 | val 1.90089
  Classification -> best τ=0.090 (val F1=0.1203)
  Directional -> Accuracy: 0.5051, MCC: 0.0102, F1: 0.5421

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.63631 | val 0.89833
  Epoch 016 - train 0.59091 | val 0.98772
  Classification -> best τ=0.255 (val F1=0.1489)
  Directional -> Accuracy: 0.5606, MCC: 0.0797, F1: 0.7166

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61341 | val 2.79188
  Epoch 016 - train 0.52999 | val 5.67560
  Classification -> best τ=0.910 (val F1=0.2198)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63087 | val 1.07107
  Epoch 016 - train 0.56241 | val 1.07419
  Classification -> best τ=0.410 (val F1=0.2750)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65505 | val 0.92529
  Epoch 017 - train 0.60775 | val 1.21268
  Classification -> best τ=0.800 (val F1=0.1976)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.66348 | val 1.00855
  Epoch 020 - train 0.53350 | val 1.88252
  Classification -> best τ=0.215 (val F1=0.1628)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.6576

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.67995 | val 0.81879
  Epoch 020 - train 0.59883 | val 1.71628
  Classification -> best τ=0.455 (val F1=0.2332)
  Directional -> Accuracy: 0.4747, MCC: 0.1259, F1: 0.1475

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63597 | val 1.04722
  Epoch 016 - train 0.55046 | val 1.73970
  Classification -> best τ=0.395 (val F1=0.1309)
  Directional -> Accuracy: 0.4949, MCC: 0.0461, F1: 0.3243

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.65848 | val 1.22468
  Epoch 016 - train 0.60087 | val 1.32343
  Classification -> best τ=0.190 (val F1=0.1771)
  Directional -> Accuracy: 0.4545, MCC: 0.0732, F1: 0.5574

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60876 | val 2.12282
  Epoch 017 - train 0.52046 | val 2.89250
  Classification -> best τ=0.055 (val F1=0.1649)
  Directional -> Accuracy: 0.5606, MCC: 0.1147, F1: 0.6027

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68046 | val 0.68873
  Epoch 020 - train 0.59158 | val 0.72661
  Classification -> best τ=0.525 (val F1=0.1970)
  Directional -> Accuracy: 0.5556, MCC: 0.1263, F1: 0.3433

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64707 | val 1.08482
  Epoch 017 - train 0.56383 | val 2.52110
  Classification -> best τ=0.575 (val F1=0.1425)
  Directional -> Accuracy: 0.5000, MCC: 0.1349, F1: 0.2080

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.66910 | val 0.87759
  Epoch 018 - train 0.59653 | val 1.05958
  Classification -> best τ=0.415 (val F1=0.1372)
  Directional -> Accuracy: 0.5253, MCC: 0.0695, F1: 0.6466

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64404 | val 0.75585
  Epoch 017 - train 0.58854 | val 0.78573
  Classification -> best τ=0.810 (val F1=0.1514)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.64037 | val 0.87239
  Epoch 017 - train 0.56926 | val 1.30771
  Classification -> best τ=0.540 (val F1=0.2039)
  Directional -> Accuracy: 0.4444, MCC: -0.0753, F1: 0.0351

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.65393 | val 1.73595
  Epoch 019 - train 0.52482 | val 3.36254
  Classification -> best τ=0.500 (val F1=0.1790)
  Directional -> Accuracy: 0.5000, MCC: 0.0472, F1: 0.0917

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67238 | val 0.76177
  Epoch 020 - train 0.57578 | val 0.75042
  Classification -> best τ=0.495 (val F1=0.1409)
  Directional -> Accuracy: 0.5859, MCC: 0.1411, F1: 0.6797

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.67395 | val 0.72138
  Epoch 017 - train 0.62657 | val 0.81919
  Classification -> best τ=0.690 (val F1=0.1519)
  Directional -> Accuracy: 0.4141, MCC: -0.0018, F1: 0.1944

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64270 | val 1.92792
  Epoch 016 - train 0.58262 | val 3.08355
  Classification -> best τ=0.260 (val F1=0.1184)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.6154

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.52605 | val 1.97590
  Epoch 016 - train 0.39596 | val 2.81474
  Classification -> best τ=0.425 (val F1=0.3039)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61931 | val 0.76436
  Epoch 017 - train 0.55372 | val 1.03449
  Classification -> best τ=0.420 (val F1=0.0736)
  Directional -> Accuracy: 0.5808, MCC: 0.0000, F1: 0.7348

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63624 | val 0.75849
  Epoch 016 - train 0.58192 | val 0.84370
  Classification -> best τ=0.605 (val F1=0.1586)
  Directional -> Accuracy: 0.4646, MCC: -0.0757, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.67113 | val 0.73447
  Epoch 020 - train 0.59100 | val 0.83744
  Classification -> best τ=0.245 (val F1=0.0872)
  Directional -> Accuracy: 0.5505, MCC: -0.0574, F1: 0.7063

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.62934 | val 2.50717
  Epoch 016 - train 0.55603 | val 4.17250
  Classification -> best τ=0.905 (val F1=0.0888)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.63828 | val 1.00702
  Epoch 016 - train 0.61105 | val 1.14681
  Classification -> best τ=0.715 (val F1=0.2016)
  Directional -> Accuracy: 0.4747, MCC: 0.0000, F1: 0.0000

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.64486 | val 3.25061
  Epoch 017 - train 0.57390 | val 8.63793
  Classification -> best τ=0.885 (val F1=0.1411)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64727 | val 1.56876
  Epoch 018 - train 0.55714 | val 2.97683
  Classification -> best τ=0.220 (val F1=0.1556)
  Directional -> Accuracy: 0.5455, MCC: 0.0515, F1: 0.7020

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65934 | val 1.90142
  Epoch 018 - train 0.59005 | val 3.85886
  Classification -> best τ=0.100 (val F1=0.1269)
  Directional -> Accuracy: 0.5000, MCC: -0.0990, F1: 0.6667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67673 | val 0.76310
  Epoch 020 - train 0.55439 | val 1.33283
  Classification -> best τ=0.465 (val F1=0.1848)
  Directional -> Accuracy: 0.5202, MCC: 0.0000, F1: 0.6844

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63344 | val 2.79743
  Epoch 016 - train 0.56872 | val 3.82741
  Classification -> best τ=0.155 (val F1=0.0961)
  Directional -> Accuracy: 0.5556, MCC: 0.0791, F1: 0.6944

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65054 | val 0.82983
  Epoch 020 - train 0.60218 | val 0.90403
  Classification -> best τ=0.740 (val F1=0.0652)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67746 | val 0.72150
  Epoch 020 - train 0.59806 | val 0.76908
  Classification -> best τ=0.560 (val F1=0.1221)
  Directional -> Accuracy: 0.4596, MCC: -0.0730, F1: 0.4729

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64345 | val 1.31609
  Epoch 016 - train 0.55620 | val 1.96505
  Classification -> best τ=0.320 (val F1=0.1174)
  Directional -> Accuracy: 0.4242, MCC: -0.0179, F1: 0.2400

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65148 | val 1.00704
  Epoch 017 - train 0.55403 | val 2.01541
  Classification -> best τ=0.555 (val F1=0.1638)
  Directional -> Accuracy: 0.4798, MCC: -0.0452, F1: 0.4309

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66651 | val 1.31491
  Epoch 018 - train 0.59229 | val 2.17484
  Classification -> best τ=0.685 (val F1=0.0944)
  Directional -> Accuracy: 0.4343, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65764 | val 0.71753
  Epoch 016 - train 0.60525 | val 0.72677
  Classification -> best τ=0.495 (val F1=0.0295)
  Directional -> Accuracy: 0.5707, MCC: 0.0901, F1: 0.6931

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60271 | val 1.22991
  Epoch 016 - train 0.53567 | val 1.38861
  Classification -> best τ=0.480 (val F1=0.1197)
  Directional -> Accuracy: 0.4899, MCC: -0.0720, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63993 | val 0.92841
  Epoch 017 - train 0.57272 | val 1.16781
  Classification -> best τ=0.615 (val F1=0.1361)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.63299 | val 0.73560
  Epoch 017 - train 0.58158 | val 0.74815
  Classification -> best τ=0.475 (val F1=0.0659)
  Directional -> Accuracy: 0.5909, MCC: 0.0250, F1: 0.7344

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.62963 | val 1.35892
  Epoch 016 - train 0.54602 | val 2.02012
  Classification -> best τ=0.295 (val F1=0.2127)
  Directional -> Accuracy: 0.4646, MCC: -0.0700, F1: 0.4952

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66297 | val 1.39176
  Epoch 016 - train 0.60348 | val 1.38292
  Classification -> best τ=0.810 (val F1=0.1004)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61999 | val 1.48765
  Epoch 016 - train 0.55552 | val 1.34879
  Classification -> best τ=0.820 (val F1=0.1003)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.67044 | val 0.89770
  Epoch 019 - train 0.56242 | val 1.59618
  Classification -> best τ=0.475 (val F1=0.1273)
  Directional -> Accuracy: 0.5051, MCC: 0.0379, F1: 0.4024

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61969 | val 1.54802
  Epoch 016 - train 0.53649 | val 2.17666
  Classification -> best τ=0.330 (val F1=0.2225)
  Directional -> Accuracy: 0.4444, MCC: 0.0267, F1: 0.1912

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62797 | val 1.54144
  Epoch 016 - train 0.56287 | val 2.61483
  Classification -> best τ=0.390 (val F1=0.1531)
  Directional -> Accuracy: 0.5000, MCC: 0.0116, F1: 0.4762

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58879 | val 3.88199
  Epoch 016 - train 0.52526 | val 6.34889
  Classification -> best τ=0.060 (val F1=0.1044)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.6485

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65437 | val 2.02660
  Epoch 016 - train 0.55348 | val 4.38885
  Classification -> best τ=0.350 (val F1=0.1291)
  Directional -> Accuracy: 0.4899, MCC: 0.0087, F1: 0.1513

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.61925 | val 1.05911
  Epoch 016 - train 0.55470 | val 1.13509
  Classification -> best τ=0.360 (val F1=0.1342)
  Directional -> Accuracy: 0.5152, MCC: 0.0113, F1: 0.4000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.62538 | val 1.06344
  Epoch 016 - train 0.55112 | val 1.19205
  Classification -> best τ=0.590 (val F1=0.1369)
  Directional -> Accuracy: 0.4444, MCC: 0.0169, F1: 0.1406

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.64909 | val 1.36943
  Epoch 016 - train 0.56034 | val 1.81100
  Classification -> best τ=0.415 (val F1=0.1978)
  Directional -> Accuracy: 0.5859, MCC: 0.0662, F1: 0.7248

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.64609 | val 1.78022
  Epoch 020 - train 0.53721 | val 5.27079
  Classification -> best τ=0.640 (val F1=0.2192)
  Directional -> Accuracy: 0.4308, MCC: -0.0561, F1: 0.5316

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.65202 | val 0.95673
  Epoch 017 - train 0.57850 | val 1.46600
  Classification -> best τ=0.610 (val F1=0.2362)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.63001 | val 1.97066
  Epoch 016 - train 0.54164 | val 2.34147
  Classification -> best τ=0.645 (val F1=0.1036)
  Directional -> Accuracy: 0.5026, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64817 | val 1.93395
  Epoch 016 - train 0.55926 | val 4.37522
  Classification -> best τ=0.470 (val F1=0.2466)
  Directional -> Accuracy: 0.4545, MCC: -0.0484, F1: 0.5179

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.64110 | val 1.33931
  Epoch 016 - train 0.53869 | val 2.96851
  Classification -> best τ=0.450 (val F1=0.1658)
  Directional -> Accuracy: 0.5436, MCC: 0.0917, F1: 0.3862

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.65273 | val 1.23899
  Epoch 016 - train 0.59845 | val 1.64067
  Classification -> best τ=0.605 (val F1=0.2018)
  Directional -> Accuracy: 0.5606, MCC: 0.1315, F1: 0.5246

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63002 | val 2.69846
  Epoch 017 - train 0.54852 | val 4.97007
  Classification -> best τ=0.130 (val F1=0.1396)
  Directional -> Accuracy: 0.5303, MCC: 0.0691, F1: 0.4804

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.65492 | val 1.23670
  Epoch 017 - train 0.59413 | val 2.84990
  Classification -> best τ=0.125 (val F1=0.0897)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.66083 | val 0.77933
  Epoch 018 - train 0.57161 | val 1.01421
  Classification -> best τ=0.530 (val F1=0.1799)
  Directional -> Accuracy: 0.4798, MCC: 0.0677, F1: 0.0190

[75/88] Processing T...


[I 2026-02-26 04:43:48,273] Trial 41 finished with value: 0.15085461397998534 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 15, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.007122852585991384, 'weight_decay': 1.1242996023414134e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.3342919234471713, 'early_stopping_min_delta': 0.0014004694737276687}. Best is trial 38 with value: 0.1560660322497637.

  Epoch 016 - train 0.58427 | val 3.43071
  Classification -> best τ=0.395 (val F1=0.1307)
  Directional -> Accuracy: 0.5051, MCC: 0.0113, F1: 0.5288

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.15085461397998534
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59477 | val 1.29458
  Epoch 016 - train 0.53225 | val 1.83109
  Classification -> best τ=0.400 (val F1=0.1704)
  Directional -> Accuracy: 0.4444, MCC: 0.1205, F1: 0.1129

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.54222 | val 6.35609
  Epoch 016 - train 0.47166 | val 8.92931
  Classification -> best τ=0.125 (val F1=0.1496)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58463 | val 1.50381
  Epoch 016 - train 0.53910 | val 1.57818
  Classification -> best τ=0.365 (val F1=0.1490)
  Directional -> Accuracy: 0.4511, MCC: -0.0843, F1: 0.4656

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.60751 | val 0.69558
  Epoch 016 - train 0.55048 | val 0.80361
  Classification -> best τ=0.625 (val F1=0.1251)
  Directional -> Accuracy: 0.4192, MCC: -0.0951, F1: 0.1085

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.52409 | val 2.50726
  Epoch 016 - train 0.46702 | val 3.55315
  Classification -> best τ=0.635 (val F1=0.1434)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57970 | val 1.44013
  Epoch 016 - train 0.50864 | val 2.00740
  Classification -> best τ=0.575 (val F1=0.0972)
  Directional -> Accuracy: 0.4495, MCC: -0.0702, F1: 0.3699

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60910 | val 2.81478
  Epoch 016 - train 0.54909 | val 4.97168
  Classification -> best τ=0.515 (val F1=0.1597)
  Directional -> Accuracy: 0.4545, MCC: 0.0904, F1: 0.0357

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57812 | val 1.39048
  Epoch 016 - train 0.50398 | val 1.76712
  Classification -> best τ=0.135 (val F1=0.3022)
  Directional -> Accuracy: 0.5303, MCC: 0.1028, F1: 0.5419

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51501 | val 6.18062
  Epoch 016 - train 0.45044 | val 7.08107
  Classification -> best τ=0.330 (val F1=0.1566)
  Directional -> Accuracy: 0.4196, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59780 | val 2.08598
  Epoch 016 - train 0.54933 | val 2.07495
  Classification -> best τ=0.625 (val F1=0.1741)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.57632 | val 0.83544
  Epoch 016 - train 0.49400 | val 1.20327
  Classification -> best τ=0.575 (val F1=0.1712)
  Directional -> Accuracy: 0.4545, MCC: -0.0515, F1: 0.0182

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.59853 | val 0.82608
  Epoch 016 - train 0.54374 | val 0.89147
  Classification -> best τ=0.430 (val F1=0.1567)
  Directional -> Accuracy: 0.4394, MCC: 0.0401, F1: 0.0976

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57985 | val 0.77486
  Epoch 016 - train 0.49827 | val 0.77461
  Classification -> best τ=0.360 (val F1=0.1457)
  Directional -> Accuracy: 0.4899, MCC: -0.0117, F1: 0.5025

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57504 | val 1.86034
  Epoch 016 - train 0.48967 | val 2.42118
  Classification -> best τ=0.655 (val F1=0.1966)
  Directional -> Accuracy: 0.5202, MCC: 0.0639, F1: 0.1441

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.62900 | val 1.90974
  Epoch 016 - train 0.55721 | val 2.71924
  Classification -> best τ=0.375 (val F1=0.0819)
  Directional -> Accuracy: 0.4596, MCC: -0.0537, F1: 0.1575

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.56683 | val 1.90150
  Epoch 016 - train 0.50206 | val 2.40228
  Classification -> best τ=0.545 (val F1=0.1667)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.59226 | val 0.98651
  Epoch 016 - train 0.52505 | val 1.14940
  Classification -> best τ=0.375 (val F1=0.1500)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54324 | val 2.25156
  Epoch 016 - train 0.44538 | val 2.58069
  Classification -> best τ=0.835 (val F1=0.1467)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56486 | val 0.86645
  Epoch 016 - train 0.49879 | val 0.99350
  Classification -> best τ=0.480 (val F1=0.2595)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60164 | val 1.28591
  Epoch 016 - train 0.56499 | val 1.48610
  Classification -> best τ=0.700 (val F1=0.1203)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.57695 | val 0.95901
  Epoch 016 - train 0.51173 | val 1.00238
  Classification -> best τ=0.720 (val F1=0.1600)
  Directional -> Accuracy: 0.5303, MCC: 0.0590, F1: 0.5027

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.62257 | val 2.82966
  Epoch 016 - train 0.54367 | val 3.90098
  Classification -> best τ=0.190 (val F1=0.1902)
  Directional -> Accuracy: 0.5455, MCC: 0.1100, F1: 0.5408

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59358 | val 0.88447
  Epoch 016 - train 0.53863 | val 1.36764
  Classification -> best τ=0.570 (val F1=0.1156)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.60414 | val 1.77874
  Epoch 016 - train 0.53713 | val 2.71477
  Classification -> best τ=0.635 (val F1=0.1505)
  Directional -> Accuracy: 0.6061, MCC: 0.0000, F1: 0.0000

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55195 | val 1.63452
  Epoch 016 - train 0.49868 | val 2.13483
  Classification -> best τ=0.785 (val F1=0.1132)
  Directional -> Accuracy: 0.4747, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60342 | val 0.90803
  Epoch 016 - train 0.55420 | val 0.95479
  Classification -> best τ=0.165 (val F1=0.1805)
  Directional -> Accuracy: 0.5404, MCC: 0.0953, F1: 0.6094

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57937 | val 1.41655
  Epoch 016 - train 0.51558 | val 2.15688
  Classification -> best τ=0.465 (val F1=0.1234)
  Directional -> Accuracy: 0.4697, MCC: 0.0531, F1: 0.1026

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.60496 | val 1.24486
  Epoch 016 - train 0.55212 | val 1.67753
  Classification -> best τ=0.675 (val F1=0.1039)
  Directional -> Accuracy: 0.5101, MCC: 0.0718, F1: 0.0583

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60153 | val 2.24059
  Epoch 016 - train 0.52858 | val 3.61725
  Classification -> best τ=0.745 (val F1=0.1342)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.58985 | val 2.68304
  Epoch 016 - train 0.51731 | val 3.89477
  Classification -> best τ=0.310 (val F1=0.1073)
  Directional -> Accuracy: 0.5758, MCC: 0.1316, F1: 0.7063

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.59032 | val 3.75904
  Epoch 016 - train 0.51688 | val 6.22638
  Classification -> best τ=0.065 (val F1=0.2076)
  Directional -> Accuracy: 0.5303, MCC: 0.0574, F1: 0.6141

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60596 | val 2.29413
  Epoch 016 - train 0.55550 | val 3.39026
  Classification -> best τ=0.380 (val F1=0.1562)
  Directional -> Accuracy: 0.5152, MCC: 0.0388, F1: 0.5200

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.62960 | val 1.03276
  Epoch 016 - train 0.58359 | val 1.28828
  Classification -> best τ=0.530 (val F1=0.1496)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58499 | val 2.17539
  Epoch 016 - train 0.50966 | val 3.00299
  Classification -> best τ=0.290 (val F1=0.1328)
  Directional -> Accuracy: 0.4596, MCC: -0.0310, F1: 0.5447

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.51659 | val 1.83223
  Epoch 016 - train 0.46473 | val 2.10333
  Classification -> best τ=0.510 (val F1=0.1974)
  Directional -> Accuracy: 0.5556, MCC: 0.1556, F1: 0.6552

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56814 | val 0.89903
  Epoch 017 - train 0.48043 | val 1.07510
  Classification -> best τ=0.550 (val F1=0.2116)
  Directional -> Accuracy: 0.4192, MCC: -0.0165, F1: 0.0171

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60518 | val 0.90942
  Epoch 016 - train 0.54473 | val 1.26405
  Classification -> best τ=0.575 (val F1=0.1701)
  Directional -> Accuracy: 0.4596, MCC: -0.1073, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.62215 | val 0.88824
  Epoch 020 - train 0.48888 | val 0.99994
  Classification -> best τ=0.305 (val F1=0.1272)
  Directional -> Accuracy: 0.4798, MCC: 0.0140, F1: 0.3977

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.59780 | val 1.88648
  Epoch 016 - train 0.50866 | val 2.92529
  Classification -> best τ=0.465 (val F1=0.0802)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.60225 | val 2.38655
  Epoch 017 - train 0.54402 | val 3.35295
  Classification -> best τ=0.350 (val F1=0.1518)
  Directional -> Accuracy: 0.4747, MCC: -0.0511, F1: 0.4902

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.57519 | val 2.15477
  Epoch 016 - train 0.50393 | val 3.19321
  Classification -> best τ=0.760 (val F1=0.1364)
  Directional -> Accuracy: 0.4949, MCC: -0.0117, F1: 0.5146

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58270 | val 1.86838
  Epoch 016 - train 0.51637 | val 2.71300
  Classification -> best τ=0.170 (val F1=0.1224)
  Directional -> Accuracy: 0.5505, MCC: 0.0681, F1: 0.7003

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63007 | val 0.72587
  Epoch 020 - train 0.50978 | val 0.78197
  Classification -> best τ=0.735 (val F1=0.1821)
  Directional -> Accuracy: 0.5253, MCC: 0.1135, F1: 0.2167

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58105 | val 1.87783
  Epoch 016 - train 0.53814 | val 2.42020
  Classification -> best τ=0.660 (val F1=0.1867)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55516 | val 3.06645
  Epoch 016 - train 0.49180 | val 3.95057
  Classification -> best τ=0.140 (val F1=0.1238)
  Directional -> Accuracy: 0.5253, MCC: 0.0113, F1: 0.6328

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61436 | val 1.54467
  Epoch 016 - train 0.56653 | val 2.03810
  Classification -> best τ=0.640 (val F1=0.1217)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59201 | val 0.94041
  Epoch 016 - train 0.53793 | val 1.21042
  Classification -> best τ=0.660 (val F1=0.1242)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56287 | val 1.88264
  Epoch 016 - train 0.52552 | val 2.44665
  Classification -> best τ=0.680 (val F1=0.1338)
  Directional -> Accuracy: 0.3990, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62675 | val 1.05452
  Epoch 018 - train 0.52043 | val 0.89451
  Classification -> best τ=0.560 (val F1=0.1771)
  Directional -> Accuracy: 0.5152, MCC: 0.0190, F1: 0.3684

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62211 | val 1.11098
  Epoch 016 - train 0.55285 | val 1.06214
  Classification -> best τ=0.465 (val F1=0.0671)
  Directional -> Accuracy: 0.4343, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60260 | val 0.82185
  Epoch 016 - train 0.52789 | val 0.96195
  Classification -> best τ=0.375 (val F1=0.1182)
  Directional -> Accuracy: 0.4697, MCC: -0.0679, F1: 0.5116

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57470 | val 1.49271
  Epoch 016 - train 0.50939 | val 2.09321
  Classification -> best τ=0.435 (val F1=0.1171)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57795 | val 1.98165
  Epoch 016 - train 0.52374 | val 2.71449
  Classification -> best τ=0.655 (val F1=0.1039)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.58752 | val 0.71466
  Epoch 018 - train 0.49023 | val 1.00547
  Classification -> best τ=0.470 (val F1=0.1168)
  Directional -> Accuracy: 0.4495, MCC: -0.0048, F1: 0.3473

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.57935 | val 1.64765
  Epoch 016 - train 0.50883 | val 2.15205
  Classification -> best τ=0.415 (val F1=0.0966)
  Directional -> Accuracy: 0.4848, MCC: -0.0607, F1: 0.6483

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60479 | val 1.44465
  Epoch 016 - train 0.54342 | val 2.04090
  Classification -> best τ=0.405 (val F1=0.1079)
  Directional -> Accuracy: 0.5808, MCC: 0.1953, F1: 0.6982

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57775 | val 1.20444
  Epoch 016 - train 0.52212 | val 1.35113
  Classification -> best τ=0.605 (val F1=0.1201)
  Directional -> Accuracy: 0.4545, MCC: -0.0211, F1: 0.0847

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.60498 | val 1.08655
  Epoch 016 - train 0.54032 | val 2.47199
  Classification -> best τ=0.535 (val F1=0.1094)
  Directional -> Accuracy: 0.4949, MCC: 0.0531, F1: 0.2308

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57872 | val 1.59136
  Epoch 016 - train 0.51115 | val 1.92297
  Classification -> best τ=0.480 (val F1=0.2714)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57823 | val 1.79857
  Epoch 016 - train 0.51851 | val 2.39424
  Classification -> best τ=0.280 (val F1=0.1793)
  Directional -> Accuracy: 0.5000, MCC: 0.0277, F1: 0.4142

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57074 | val 2.25401
  Epoch 016 - train 0.50026 | val 2.89327
  Classification -> best τ=0.055 (val F1=0.1052)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.6485

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59121 | val 2.23094
  Epoch 016 - train 0.52241 | val 2.40445
  Classification -> best τ=0.265 (val F1=0.1786)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.59564 | val 0.82284
  Epoch 019 - train 0.48255 | val 0.99621
  Classification -> best τ=0.140 (val F1=0.1664)
  Directional -> Accuracy: 0.5303, MCC: 0.0267, F1: 0.2560

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.57816 | val 2.10170
  Epoch 016 - train 0.50471 | val 2.38816
  Classification -> best τ=0.240 (val F1=0.1754)
  Directional -> Accuracy: 0.4596, MCC: 0.0044, F1: 0.3007

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.58028 | val 1.52583
  Epoch 016 - train 0.51515 | val 1.41177
  Classification -> best τ=0.555 (val F1=0.1279)
  Directional -> Accuracy: 0.4242, MCC: 0.0216, F1: 0.0339

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.58620 | val 1.39918
  Epoch 020 - train 0.42320 | val 2.02471
  Classification -> best τ=0.295 (val F1=0.2532)
  Directional -> Accuracy: 0.4845, MCC: 0.0509, F1: 0.5575

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.57694 | val 1.18287
  Epoch 016 - train 0.49703 | val 1.48998
  Classification -> best τ=0.470 (val F1=0.2077)
  Directional -> Accuracy: 0.5202, MCC: 0.1065, F1: 0.3165

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.58080 | val 1.38204
  Epoch 016 - train 0.52555 | val 1.51236
  Classification -> best τ=0.475 (val F1=0.0809)
  Directional -> Accuracy: 0.5052, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57687 | val 1.85764
  Epoch 016 - train 0.51319 | val 2.40222
  Classification -> best τ=0.495 (val F1=0.2481)
  Directional -> Accuracy: 0.4646, MCC: -0.0111, F1: 0.5508

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.56411 | val 1.92611
  Epoch 016 - train 0.49844 | val 2.72661
  Classification -> best τ=0.475 (val F1=0.1613)
  Directional -> Accuracy: 0.5206, MCC: 0.0993, F1: 0.0792

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.60840 | val 0.93916
  Epoch 016 - train 0.54215 | val 0.78897
  Classification -> best τ=0.635 (val F1=0.1949)
  Directional -> Accuracy: 0.5152, MCC: 0.0769, F1: 0.2941

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.59254 | val 2.12436
  Epoch 018 - train 0.47600 | val 3.37559
  Classification -> best τ=0.270 (val F1=0.1618)
  Directional -> Accuracy: 0.4899, MCC: 0.0176, F1: 0.0901

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.59585 | val 3.79522
  Epoch 016 - train 0.54191 | val 4.07360
  Classification -> best τ=0.855 (val F1=0.1129)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.60366 | val 2.10991
  Epoch 016 - train 0.54029 | val 3.21321
  Classification -> best τ=0.310 (val F1=0.1914)
  Directional -> Accuracy: 0.5000, MCC: 0.0173, F1: 0.4211

[75/88] Processing T...


[I 2026-02-26 04:52:38,471] Trial 42 finished with value: 0.15369369027415375 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.0029349720798910644, 'weight_decay': 3.1908976885652786e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.7301640911751797, 'early_stopping_min_delta': 0.0020839103606574367}. Best is trial 38 with value: 0.1560660322497637.

  Epoch 016 - train 0.53347 | val 3.57053
  Classification -> best τ=0.065 (val F1=0.1495)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.6622

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.15369369027415375
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58706 | val 1.25574
  Epoch 016 - train 0.53046 | val 1.47565
  Classification -> best τ=0.195 (val F1=0.1676)
  Directional -> Accuracy: 0.4697, MCC: 0.0450, F1: 0.3396

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.54042 | val 6.27771
  Epoch 016 - train 0.47561 | val 8.51412
  Classification -> best τ=0.140 (val F1=0.1201)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59408 | val 1.20949
  Epoch 016 - train 0.54056 | val 1.54316
  Classification -> best τ=0.285 (val F1=0.2203)
  Directional -> Accuracy: 0.5489, MCC: -0.0192, F1: 0.6868

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.63153 | val 1.03384
  Epoch 019 - train 0.50707 | val 1.24514
  Classification -> best τ=0.425 (val F1=0.1099)
  Directional -> Accuracy: 0.5556, MCC: 0.0019, F1: 0.7007

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.52318 | val 2.91083
  Epoch 016 - train 0.47458 | val 3.91769
  Classification -> best τ=0.515 (val F1=0.2040)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57039 | val 1.40254
  Epoch 016 - train 0.49974 | val 2.10450
  Classification -> best τ=0.630 (val F1=0.1361)
  Directional -> Accuracy: 0.4444, MCC: -0.0474, F1: 0.0984

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61573 | val 1.60871
  Epoch 016 - train 0.56776 | val 2.46100
  Classification -> best τ=0.465 (val F1=0.1654)
  Directional -> Accuracy: 0.4747, MCC: 0.1581, F1: 0.1034

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58224 | val 1.06580
  Epoch 016 - train 0.52267 | val 1.47826
  Classification -> best τ=0.330 (val F1=0.2684)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52722 | val 5.41047
  Epoch 016 - train 0.44405 | val 5.60015
  Classification -> best τ=0.310 (val F1=0.2049)
  Directional -> Accuracy: 0.4196, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59885 | val 1.96510
  Epoch 016 - train 0.53899 | val 2.66681
  Classification -> best τ=0.760 (val F1=0.1517)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.56460 | val 0.76065
  Epoch 016 - train 0.49858 | val 0.74531
  Classification -> best τ=0.240 (val F1=0.1573)
  Directional -> Accuracy: 0.5455, MCC: 0.0571, F1: 0.6512

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.60042 | val 0.77077
  Epoch 016 - train 0.53243 | val 0.89902
  Classification -> best τ=0.700 (val F1=0.1446)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57995 | val 0.78060
  Epoch 020 - train 0.46265 | val 1.05750
  Classification -> best τ=0.200 (val F1=0.1409)
  Directional -> Accuracy: 0.5152, MCC: 0.0405, F1: 0.5248

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.54576 | val 2.23018
  Epoch 016 - train 0.48538 | val 3.01634
  Classification -> best τ=0.635 (val F1=0.1918)
  Directional -> Accuracy: 0.5253, MCC: 0.0771, F1: 0.1754

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.62814 | val 1.93718
  Epoch 016 - train 0.57840 | val 2.52074
  Classification -> best τ=0.585 (val F1=0.0990)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.57317 | val 1.82465
  Epoch 016 - train 0.50557 | val 2.59451
  Classification -> best τ=0.495 (val F1=0.1601)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.59183 | val 1.09415
  Epoch 016 - train 0.51419 | val 1.16429
  Classification -> best τ=0.380 (val F1=0.1547)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54559 | val 4.27975
  Epoch 016 - train 0.45680 | val 5.02317
  Classification -> best τ=0.890 (val F1=0.1467)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57118 | val 0.89313
  Epoch 016 - train 0.50173 | val 1.01372
  Classification -> best τ=0.465 (val F1=0.2757)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59262 | val 1.13228
  Epoch 016 - train 0.53554 | val 1.38037
  Classification -> best τ=0.830 (val F1=0.1393)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.58399 | val 1.23244
  Epoch 016 - train 0.52184 | val 1.39348
  Classification -> best τ=0.805 (val F1=0.0930)
  Directional -> Accuracy: 0.5404, MCC: 0.0796, F1: 0.4129

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.61225 | val 2.95543
  Epoch 016 - train 0.54774 | val 4.22432
  Classification -> best τ=0.210 (val F1=0.1798)
  Directional -> Accuracy: 0.5000, MCC: 0.0774, F1: 0.3694

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59367 | val 1.22238
  Epoch 016 - train 0.52612 | val 2.13843
  Classification -> best τ=0.475 (val F1=0.2168)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.58725 | val 1.74516
  Epoch 016 - train 0.53092 | val 2.16754
  Classification -> best τ=0.740 (val F1=0.1565)
  Directional -> Accuracy: 0.6061, MCC: 0.0000, F1: 0.0000

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.56356 | val 2.12904
  Epoch 016 - train 0.49305 | val 2.76734
  Classification -> best τ=0.390 (val F1=0.1366)
  Directional -> Accuracy: 0.5000, MCC: 0.0083, F1: 0.4706

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61152 | val 0.83186
  Epoch 016 - train 0.57800 | val 0.95299
  Classification -> best τ=0.440 (val F1=0.1688)
  Directional -> Accuracy: 0.5556, MCC: 0.1285, F1: 0.3333

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59081 | val 1.24238
  Epoch 016 - train 0.51999 | val 1.53979
  Classification -> best τ=0.420 (val F1=0.1770)
  Directional -> Accuracy: 0.4495, MCC: -0.0470, F1: 0.1417

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.60248 | val 1.25845
  Epoch 016 - train 0.54590 | val 1.28946
  Classification -> best τ=0.310 (val F1=0.1666)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60636 | val 2.59715
  Epoch 016 - train 0.52752 | val 4.12048
  Classification -> best τ=0.505 (val F1=0.1294)
  Directional -> Accuracy: 0.5152, MCC: 0.0439, F1: 0.3846

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.59724 | val 1.65764
  Epoch 016 - train 0.52749 | val 2.38508
  Classification -> best τ=0.470 (val F1=0.0713)
  Directional -> Accuracy: 0.4495, MCC: -0.0500, F1: 0.1805

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.58895 | val 2.32484
  Epoch 016 - train 0.51495 | val 3.17514
  Classification -> best τ=0.160 (val F1=0.1745)
  Directional -> Accuracy: 0.5051, MCC: 0.0021, F1: 0.5917

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59595 | val 1.38380
  Epoch 016 - train 0.53005 | val 1.71309
  Classification -> best τ=0.325 (val F1=0.1572)
  Directional -> Accuracy: 0.4949, MCC: 0.0194, F1: 0.4444

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.62124 | val 0.97045
  Epoch 016 - train 0.59007 | val 1.18862
  Classification -> best τ=0.435 (val F1=0.1601)
  Directional -> Accuracy: 0.4899, MCC: -0.0138, F1: 0.5346

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58306 | val 0.93054
  Epoch 016 - train 0.51012 | val 1.08271
  Classification -> best τ=0.530 (val F1=0.1167)
  Directional -> Accuracy: 0.5404, MCC: 0.0538, F1: 0.4348

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.53959 | val 2.82218
  Epoch 016 - train 0.44951 | val 3.12757
  Classification -> best τ=0.430 (val F1=0.1840)
  Directional -> Accuracy: 0.5333, MCC: 0.1059, F1: 0.6441

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56677 | val 1.17277
  Epoch 016 - train 0.49055 | val 1.40794
  Classification -> best τ=0.455 (val F1=0.2107)
  Directional -> Accuracy: 0.4444, MCC: 0.0599, F1: 0.1406

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59994 | val 1.35887
  Epoch 016 - train 0.55157 | val 1.63506
  Classification -> best τ=0.470 (val F1=0.1614)
  Directional -> Accuracy: 0.4747, MCC: 0.0158, F1: 0.0714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.62373 | val 0.76693
  Epoch 019 - train 0.51935 | val 0.85114
  Classification -> best τ=0.340 (val F1=0.1613)
  Directional -> Accuracy: 0.4949, MCC: 0.0808, F1: 0.3506

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.57929 | val 2.72169
  Epoch 016 - train 0.51808 | val 3.09103
  Classification -> best τ=0.390 (val F1=0.0958)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.60894 | val 2.28416
  Epoch 016 - train 0.54883 | val 2.48829
  Classification -> best τ=0.455 (val F1=0.1161)
  Directional -> Accuracy: 0.4646, MCC: -0.0631, F1: 0.4301

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.57858 | val 2.58045
  Epoch 016 - train 0.51581 | val 4.72968
  Classification -> best τ=0.800 (val F1=0.1421)
  Directional -> Accuracy: 0.5202, MCC: 0.0320, F1: 0.5957

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58166 | val 1.71387
  Epoch 016 - train 0.50323 | val 2.35543
  Classification -> best τ=0.230 (val F1=0.0946)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.7016

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60210 | val 1.17007
  Epoch 016 - train 0.53589 | val 1.25521
  Classification -> best τ=0.540 (val F1=0.1216)
  Directional -> Accuracy: 0.4899, MCC: -0.0041, F1: 0.0734

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58913 | val 2.12520
  Epoch 016 - train 0.53019 | val 2.82339
  Classification -> best τ=0.620 (val F1=0.2020)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56526 | val 5.03498
  Epoch 016 - train 0.50139 | val 5.82585
  Classification -> best τ=0.055 (val F1=0.1039)
  Directional -> Accuracy: 0.5354, MCC: 0.0333, F1: 0.6434

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61134 | val 1.52427
  Epoch 016 - train 0.56299 | val 2.07589
  Classification -> best τ=0.645 (val F1=0.1144)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59410 | val 0.95226
  Epoch 016 - train 0.53873 | val 1.25488
  Classification -> best τ=0.410 (val F1=0.0967)
  Directional -> Accuracy: 0.5202, MCC: 0.0249, F1: 0.5740

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57733 | val 1.80344
  Epoch 016 - train 0.50577 | val 2.50625
  Classification -> best τ=0.155 (val F1=0.1210)
  Directional -> Accuracy: 0.5354, MCC: -0.0876, F1: 0.6761

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60580 | val 0.99026
  Epoch 016 - train 0.54369 | val 1.09602
  Classification -> best τ=0.280 (val F1=0.1879)
  Directional -> Accuracy: 0.4747, MCC: -0.0411, F1: 0.5702

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.59718 | val 1.36496
  Epoch 016 - train 0.55213 | val 1.28598
  Classification -> best τ=0.195 (val F1=0.0757)
  Directional -> Accuracy: 0.5354, MCC: -0.0249, F1: 0.6691

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60430 | val 0.80441
  Epoch 016 - train 0.54119 | val 0.84306
  Classification -> best τ=0.550 (val F1=0.1284)
  Directional -> Accuracy: 0.4242, MCC: -0.1038, F1: 0.1493

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58300 | val 1.72412
  Epoch 016 - train 0.53259 | val 1.87442
  Classification -> best τ=0.470 (val F1=0.1186)
  Directional -> Accuracy: 0.4949, MCC: -0.0021, F1: 0.0741

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58335 | val 1.64519
  Epoch 016 - train 0.51987 | val 1.92419
  Classification -> best τ=0.590 (val F1=0.1493)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.57361 | val 0.75594
  Epoch 016 - train 0.51867 | val 0.81666
  Classification -> best τ=0.590 (val F1=0.1506)
  Directional -> Accuracy: 0.4192, MCC: -0.0279, F1: 0.1958

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.59006 | val 1.48640
  Epoch 016 - train 0.52433 | val 2.15111
  Classification -> best τ=0.365 (val F1=0.1605)
  Directional -> Accuracy: 0.4899, MCC: -0.0720, F1: 0.6576

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.58744 | val 1.64024
  Epoch 016 - train 0.52882 | val 2.72364
  Classification -> best τ=0.905 (val F1=0.1642)
  Directional -> Accuracy: 0.4697, MCC: -0.0661, F1: 0.0367

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57664 | val 1.17692
  Epoch 016 - train 0.51193 | val 1.20864
  Classification -> best τ=0.700 (val F1=0.1228)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.59528 | val 0.81935
  Epoch 016 - train 0.54637 | val 1.31300
  Classification -> best τ=0.650 (val F1=0.1132)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58665 | val 1.23304
  Epoch 016 - train 0.53929 | val 1.61090
  Classification -> best τ=0.540 (val F1=0.2762)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58219 | val 1.86773
  Epoch 016 - train 0.51591 | val 2.53274
  Classification -> best τ=0.330 (val F1=0.2054)
  Directional -> Accuracy: 0.5051, MCC: 0.0875, F1: 0.2687

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57566 | val 2.05260
  Epoch 016 - train 0.49228 | val 2.51364
  Classification -> best τ=0.085 (val F1=0.1052)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.6485

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58896 | val 1.89936
  Epoch 016 - train 0.51810 | val 2.13257
  Classification -> best τ=0.100 (val F1=0.1623)
  Directional -> Accuracy: 0.5253, MCC: 0.0621, F1: 0.4535

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.58312 | val 0.89000
  Epoch 016 - train 0.52751 | val 0.94019
  Classification -> best τ=0.370 (val F1=0.0957)
  Directional -> Accuracy: 0.5303, MCC: 0.0343, F1: 0.3404

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.61221 | val 2.66557
  Epoch 020 - train 0.46683 | val 4.62721
  Classification -> best τ=0.550 (val F1=0.2072)
  Directional -> Accuracy: 0.4747, MCC: 0.0321, F1: 0.3418

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.56831 | val 1.96400
  Epoch 016 - train 0.50623 | val 2.32670
  Classification -> best τ=0.205 (val F1=0.1052)
  Directional -> Accuracy: 0.5556, MCC: 0.0312, F1: 0.6692

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.55614 | val 0.82843
  Epoch 016 - train 0.48010 | val 0.84249
  Classification -> best τ=0.450 (val F1=0.1867)
  Directional -> Accuracy: 0.4278, MCC: -0.0570, F1: 0.5432

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.59063 | val 1.68706
  Epoch 016 - train 0.52602 | val 1.66697
  Classification -> best τ=0.575 (val F1=0.2354)
  Directional -> Accuracy: 0.4848, MCC: 0.0706, F1: 0.0893

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.58239 | val 1.16822
  Epoch 016 - train 0.51055 | val 1.30319
  Classification -> best τ=0.590 (val F1=0.1094)
  Directional -> Accuracy: 0.5052, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56853 | val 3.79929
  Epoch 016 - train 0.51467 | val 5.01229
  Classification -> best τ=0.695 (val F1=0.2308)
  Directional -> Accuracy: 0.4747, MCC: -0.0195, F1: 0.5094

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.57263 | val 1.48533
  Epoch 016 - train 0.49683 | val 3.04796
  Classification -> best τ=0.335 (val F1=0.1711)
  Directional -> Accuracy: 0.5567, MCC: 0.1146, F1: 0.4881

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.61029 | val 1.31288
  Epoch 016 - train 0.55626 | val 1.46715
  Classification -> best τ=0.725 (val F1=0.1510)
  Directional -> Accuracy: 0.5101, MCC: 0.0223, F1: 0.5076

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.56932 | val 2.15124
  Epoch 016 - train 0.48385 | val 1.20594
  Classification -> best τ=0.265 (val F1=0.1641)
  Directional -> Accuracy: 0.5404, MCC: 0.0773, F1: 0.5767

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.59564 | val 4.84706
  Epoch 016 - train 0.54082 | val 5.91273
  Classification -> best τ=0.475 (val F1=0.0904)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.60323 | val 1.82359
  Epoch 018 - train 0.52180 | val 3.36313
  Classification -> best τ=0.235 (val F1=0.0914)
  Directional -> Accuracy: 0.5152, MCC: -0.0295, F1: 0.6690

[75/88] Processing T...


[I 2026-02-26 05:01:24,768] Trial 43 finished with value: 0.1552921786919067 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.002774378839888954, 'weight_decay': 3.5237444966550724e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.6495235834972664, 'early_stopping_min_delta': 0.0021468669789925865}. Best is trial 38 with value: 0.1560660322497637.

  Epoch 016 - train 0.53512 | val 2.77521
  Classification -> best τ=0.460 (val F1=0.1794)
  Directional -> Accuracy: 0.5556, MCC: 0.1115, F1: 0.5000

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1552921786919067
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60338 | val 1.39046
  Epoch 016 - train 0.54374 | val 1.90920
  Classification -> best τ=0.330 (val F1=0.1356)
  Directional -> Accuracy: 0.4293, MCC: -0.0046, F1: 0.1630

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.54151 | val 8.74051
  Epoch 016 - train 0.44856 | val 13.27328
  Classification -> best τ=0.105 (val F1=0.1007)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59249 | val 1.35824
  Epoch 016 - train 0.52058 | val 1.85476
  Classification -> best τ=0.355 (val F1=0.1741)
  Directional -> Accuracy: 0.5543, MCC: 0.0166, F1: 0.6797

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.60757 | val 0.71668
  Epoch 016 - train 0.54372 | val 0.85014
  Classification -> best τ=0.645 (val F1=0.0939)
  Directional -> Accuracy: 0.4394, MCC: -0.0480, F1: 0.2449

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.52445 | val 2.72965
  Epoch 016 - train 0.45530 | val 3.88316
  Classification -> best τ=0.450 (val F1=0.0939)
  Directional -> Accuracy: 0.5333, MCC: 0.0742, F1: 0.5243

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57158 | val 1.56835
  Epoch 016 - train 0.50739 | val 2.38477
  Classification -> best τ=0.070 (val F1=0.1218)
  Directional -> Accuracy: 0.5202, MCC: -0.0610, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61150 | val 3.42740
  Epoch 016 - train 0.57531 | val 4.83038
  Classification -> best τ=0.460 (val F1=0.1824)
  Directional -> Accuracy: 0.4848, MCC: -0.0182, F1: 0.4848

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57369 | val 1.13535
  Epoch 016 - train 0.50284 | val 1.50378
  Classification -> best τ=0.355 (val F1=0.2707)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50124 | val 6.49371
  Epoch 016 - train 0.44602 | val 7.41391
  Classification -> best τ=0.355 (val F1=0.1716)
  Directional -> Accuracy: 0.4196, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58395 | val 2.42513
  Epoch 016 - train 0.52825 | val 2.53482
  Classification -> best τ=0.725 (val F1=0.1233)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.57232 | val 1.06123
  Epoch 016 - train 0.50588 | val 1.12103
  Classification -> best τ=0.655 (val F1=0.1712)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.59432 | val 0.86656
  Epoch 016 - train 0.54107 | val 0.99100
  Classification -> best τ=0.820 (val F1=0.1446)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56374 | val 0.74820
  Epoch 016 - train 0.48996 | val 0.75195
  Classification -> best τ=0.745 (val F1=0.1396)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57634 | val 1.53699
  Epoch 016 - train 0.48921 | val 2.15536
  Classification -> best τ=0.720 (val F1=0.2274)
  Directional -> Accuracy: 0.5051, MCC: 0.0015, F1: 0.0392

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.62429 | val 1.82609
  Epoch 016 - train 0.57421 | val 2.27766
  Classification -> best τ=0.330 (val F1=0.0782)
  Directional -> Accuracy: 0.4444, MCC: -0.1244, F1: 0.5045

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.56957 | val 1.66377
  Epoch 016 - train 0.48185 | val 2.55257
  Classification -> best τ=0.420 (val F1=0.1263)
  Directional -> Accuracy: 0.5051, MCC: 0.0712, F1: 0.0200

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.59726 | val 0.93099
  Epoch 016 - train 0.53288 | val 1.10210
  Classification -> best τ=0.495 (val F1=0.1095)
  Directional -> Accuracy: 0.5960, MCC: 0.1689, F1: 0.7203

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53725 | val 3.20895
  Epoch 016 - train 0.47749 | val 3.80208
  Classification -> best τ=0.810 (val F1=0.1934)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58143 | val 0.80439
  Epoch 016 - train 0.49899 | val 0.98650
  Classification -> best τ=0.415 (val F1=0.2602)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60960 | val 1.10683
  Epoch 016 - train 0.52927 | val 1.40312
  Classification -> best τ=0.755 (val F1=0.1203)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.60118 | val 1.10623
  Epoch 016 - train 0.52615 | val 1.29551
  Classification -> best τ=0.425 (val F1=0.1321)
  Directional -> Accuracy: 0.4899, MCC: -0.0041, F1: 0.6481

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.61793 | val 1.77888
  Epoch 016 - train 0.53803 | val 2.61909
  Classification -> best τ=0.260 (val F1=0.2430)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59999 | val 1.02776
  Epoch 016 - train 0.53829 | val 1.46011
  Classification -> best τ=0.480 (val F1=0.1352)
  Directional -> Accuracy: 0.5657, MCC: 0.1042, F1: 0.6838

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.60334 | val 1.80084
  Epoch 016 - train 0.52728 | val 2.01115
  Classification -> best τ=0.220 (val F1=0.1311)
  Directional -> Accuracy: 0.4192, MCC: 0.0092, F1: 0.5490

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57017 | val 1.42326
  Epoch 016 - train 0.50438 | val 1.82877
  Classification -> best τ=0.395 (val F1=0.1042)
  Directional -> Accuracy: 0.5505, MCC: 0.1056, F1: 0.5436

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62158 | val 0.99861
  Epoch 016 - train 0.56717 | val 1.03690
  Classification -> best τ=0.440 (val F1=0.1877)
  Directional -> Accuracy: 0.5202, MCC: 0.1031, F1: 0.0404

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59345 | val 1.16463
  Epoch 016 - train 0.50833 | val 1.75679
  Classification -> best τ=0.475 (val F1=0.1856)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.61111 | val 1.03471
  Epoch 016 - train 0.54437 | val 1.19882
  Classification -> best τ=0.335 (val F1=0.1044)
  Directional -> Accuracy: 0.5101, MCC: 0.0282, F1: 0.6367

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58501 | val 3.20137
  Epoch 016 - train 0.52553 | val 4.85263
  Classification -> best τ=0.545 (val F1=0.1241)
  Directional -> Accuracy: 0.5404, MCC: 0.1368, F1: 0.2946

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.59776 | val 2.16229
  Epoch 016 - train 0.52581 | val 2.70762
  Classification -> best τ=0.465 (val F1=0.0566)
  Directional -> Accuracy: 0.5354, MCC: 0.0630, F1: 0.5741

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.59344 | val 3.41518
  Epoch 016 - train 0.51995 | val 5.27260
  Classification -> best τ=0.130 (val F1=0.1710)
  Directional -> Accuracy: 0.5354, MCC: 0.0745, F1: 0.6489

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59460 | val 2.19271
  Epoch 016 - train 0.55371 | val 3.23641
  Classification -> best τ=0.310 (val F1=0.1464)
  Directional -> Accuracy: 0.5404, MCC: 0.0170, F1: 0.6691

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.63618 | val 0.98050
  Epoch 016 - train 0.58877 | val 1.19757
  Classification -> best τ=0.145 (val F1=0.1427)
  Directional -> Accuracy: 0.5505, MCC: -0.1172, F1: 0.7003

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61652 | val 0.86954
  Epoch 020 - train 0.45332 | val 1.93837
  Classification -> best τ=0.210 (val F1=0.1253)
  Directional -> Accuracy: 0.4495, MCC: 0.0637, F1: 0.6175

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.50003 | val 2.40946
  Epoch 016 - train 0.46200 | val 2.90739
  Classification -> best τ=0.440 (val F1=0.1974)
  Directional -> Accuracy: 0.6222, MCC: 0.2621, F1: 0.6667

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58663 | val 1.20654
  Epoch 020 - train 0.44847 | val 2.15477
  Classification -> best τ=0.435 (val F1=0.2215)
  Directional -> Accuracy: 0.4747, MCC: 0.1264, F1: 0.2353

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61054 | val 1.53332
  Epoch 016 - train 0.53385 | val 2.05573
  Classification -> best τ=0.490 (val F1=0.1870)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.61491 | val 0.77195
  Epoch 018 - train 0.52979 | val 0.93256
  Classification -> best τ=0.370 (val F1=0.1578)
  Directional -> Accuracy: 0.5000, MCC: 0.0818, F1: 0.3774

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.58648 | val 2.35631
  Epoch 016 - train 0.52000 | val 3.06057
  Classification -> best τ=0.525 (val F1=0.1597)
  Directional -> Accuracy: 0.4242, MCC: -0.1231, F1: 0.2785

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.60291 | val 1.69607
  Epoch 016 - train 0.52659 | val 2.31341
  Classification -> best τ=0.675 (val F1=0.1208)
  Directional -> Accuracy: 0.4798, MCC: 0.0677, F1: 0.0190

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.58544 | val 2.15400
  Epoch 016 - train 0.52323 | val 2.12816
  Classification -> best τ=0.740 (val F1=0.1684)
  Directional -> Accuracy: 0.4949, MCC: -0.0214, F1: 0.5726

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60981 | val 1.54729
  Epoch 016 - train 0.53613 | val 2.06804
  Classification -> best τ=0.205 (val F1=0.1192)
  Directional -> Accuracy: 0.5404, MCC: 0.0315, F1: 0.6738

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62169 | val 1.01033
  Epoch 020 - train 0.49345 | val 0.87722
  Classification -> best τ=0.320 (val F1=0.2123)
  Directional -> Accuracy: 0.5303, MCC: 0.0619, F1: 0.6464

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60179 | val 1.94632
  Epoch 016 - train 0.52874 | val 2.57616
  Classification -> best τ=0.690 (val F1=0.1577)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53741 | val 4.14155
  Epoch 016 - train 0.48185 | val 4.87826
  Classification -> best τ=0.100 (val F1=0.0978)
  Directional -> Accuracy: 0.5404, MCC: 0.0408, F1: 0.6566

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61849 | val 1.44337
  Epoch 016 - train 0.56879 | val 1.88093
  Classification -> best τ=0.600 (val F1=0.0873)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58985 | val 0.91489
  Epoch 016 - train 0.54341 | val 0.99666
  Classification -> best τ=0.445 (val F1=0.1087)
  Directional -> Accuracy: 0.4899, MCC: 0.0653, F1: 0.3311

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56133 | val 1.59778
  Epoch 016 - train 0.49572 | val 2.87587
  Classification -> best τ=0.120 (val F1=0.0822)
  Directional -> Accuracy: 0.4899, MCC: -0.1552, F1: 0.6273

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60224 | val 1.31683
  Epoch 016 - train 0.54784 | val 1.88671
  Classification -> best τ=0.310 (val F1=0.1536)
  Directional -> Accuracy: 0.4899, MCC: 0.0104, F1: 0.6380

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62971 | val 1.06963
  Epoch 017 - train 0.56176 | val 0.98646
  Classification -> best τ=0.540 (val F1=0.0951)
  Directional -> Accuracy: 0.4343, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63530 | val 0.94907
  Epoch 019 - train 0.51565 | val 1.21949
  Classification -> best τ=0.280 (val F1=0.1450)
  Directional -> Accuracy: 0.5556, MCC: 0.0527, F1: 0.6765

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58127 | val 1.32729
  Epoch 016 - train 0.53360 | val 1.61838
  Classification -> best τ=0.465 (val F1=0.1104)
  Directional -> Accuracy: 0.5000, MCC: 0.0066, F1: 0.3172

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59280 | val 1.19183
  Epoch 016 - train 0.52599 | val 1.55720
  Classification -> best τ=0.485 (val F1=0.1018)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.59706 | val 0.78764
  Epoch 016 - train 0.53658 | val 0.92331
  Classification -> best τ=0.475 (val F1=0.1238)
  Directional -> Accuracy: 0.5253, MCC: -0.0522, F1: 0.6466

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.58341 | val 1.56257
  Epoch 016 - train 0.52670 | val 2.19833
  Classification -> best τ=0.440 (val F1=0.1704)
  Directional -> Accuracy: 0.4545, MCC: -0.0978, F1: 0.5574

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60962 | val 1.62669
  Epoch 016 - train 0.53514 | val 2.76582
  Classification -> best τ=0.725 (val F1=0.1406)
  Directional -> Accuracy: 0.4444, MCC: -0.1080, F1: 0.2361

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57862 | val 0.91366
  Epoch 017 - train 0.51652 | val 1.34751
  Classification -> best τ=0.605 (val F1=0.1226)
  Directional -> Accuracy: 0.4646, MCC: 0.0144, F1: 0.1311

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.60012 | val 0.75665
  Epoch 016 - train 0.53277 | val 1.07035
  Classification -> best τ=0.650 (val F1=0.0935)
  Directional -> Accuracy: 0.4798, MCC: 0.0191, F1: 0.1488

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56617 | val 1.58877
  Epoch 016 - train 0.50375 | val 1.70183
  Classification -> best τ=0.460 (val F1=0.2807)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58304 | val 1.78077
  Epoch 016 - train 0.51181 | val 2.35585
  Classification -> best τ=0.250 (val F1=0.1296)
  Directional -> Accuracy: 0.5202, MCC: 0.0804, F1: 0.4099

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58311 | val 1.83748
  Epoch 016 - train 0.49612 | val 2.65144
  Classification -> best τ=0.130 (val F1=0.1052)
  Directional -> Accuracy: 0.4848, MCC: 0.0257, F1: 0.6458

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57635 | val 2.25127
  Epoch 016 - train 0.50040 | val 3.02049
  Classification -> best τ=0.185 (val F1=0.1720)
  Directional -> Accuracy: 0.4747, MCC: -0.1041, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.61561 | val 0.75270
  Epoch 016 - train 0.54788 | val 0.75140
  Classification -> best τ=0.275 (val F1=0.1351)
  Directional -> Accuracy: 0.4899, MCC: 0.0283, F1: 0.6100

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.61132 | val 1.61152
  Epoch 019 - train 0.45404 | val 3.39131
  Classification -> best τ=0.380 (val F1=0.1839)
  Directional -> Accuracy: 0.4495, MCC: 0.0602, F1: 0.1138

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.58629 | val 1.37919
  Epoch 016 - train 0.48275 | val 1.69625
  Classification -> best τ=0.285 (val F1=0.1110)
  Directional -> Accuracy: 0.4949, MCC: -0.0235, F1: 0.5495

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.58823 | val 0.99316
  Epoch 018 - train 0.46801 | val 1.06648
  Classification -> best τ=0.265 (val F1=0.2305)
  Directional -> Accuracy: 0.4485, MCC: 0.0029, F1: 0.5633

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.56687 | val 1.22684
  Epoch 017 - train 0.50769 | val 1.65046
  Classification -> best τ=0.605 (val F1=0.2198)
  Directional -> Accuracy: 0.4798, MCC: 0.0951, F1: 0.0374

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.59684 | val 1.48952
  Epoch 016 - train 0.53250 | val 1.97052
  Classification -> best τ=0.635 (val F1=0.0916)
  Directional -> Accuracy: 0.5052, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58308 | val 2.68377
  Epoch 016 - train 0.49368 | val 3.93209
  Classification -> best τ=0.455 (val F1=0.2327)
  Directional -> Accuracy: 0.4646, MCC: -0.0055, F1: 0.5583

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.57282 | val 1.38862
  Epoch 016 - train 0.49232 | val 2.19539
  Classification -> best τ=0.195 (val F1=0.2031)
  Directional -> Accuracy: 0.5876, MCC: 0.1855, F1: 0.6364

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.62683 | val 1.31556
  Epoch 018 - train 0.50925 | val 1.52878
  Classification -> best τ=0.670 (val F1=0.2035)
  Directional -> Accuracy: 0.5556, MCC: 0.1090, F1: 0.6641

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.57625 | val 1.64513
  Epoch 016 - train 0.50556 | val 3.09500
  Classification -> best τ=0.350 (val F1=0.1817)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.60966 | val 3.85442
  Epoch 016 - train 0.53996 | val 4.43079
  Classification -> best τ=0.525 (val F1=0.0395)
  Directional -> Accuracy: 0.4545, MCC: -0.0131, F1: 0.6197

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.60873 | val 2.12383
  Epoch 016 - train 0.52981 | val 3.31142
  Classification -> best τ=0.260 (val F1=0.1252)
  Directional -> Accuracy: 0.5051, MCC: 0.0191, F1: 0.4731

[75/88] Processing T...


[I 2026-02-26 05:10:09,214] Trial 44 finished with value: 0.14980043192954218 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.0032306131738313922, 'weight_decay': 3.425890105334361e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.7310387118212283, 'early_stopping_min_delta': 0.0021309362073232193}. Best is trial 38 with value: 0.1560660322497637.

  Epoch 016 - train 0.55142 | val 3.08176
  Classification -> best τ=0.445 (val F1=0.1914)
  Directional -> Accuracy: 0.5455, MCC: 0.0905, F1: 0.5000

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14980043192954218
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63605 | val 1.23034
  Epoch 016 - train 0.60618 | val 1.35681
  Classification -> best τ=0.735 (val F1=0.1554)
  Directional -> Accuracy: 0.4394, MCC: 0.1054, F1: 0.0976

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.60407 | val 6.72409
  Epoch 016 - train 0.56957 | val 8.89146
  Classification -> best τ=0.390 (val F1=0.1740)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63419 | val 0.86053
  Epoch 016 - train 0.61274 | val 1.02607
  Classification -> best τ=0.345 (val F1=0.1404)
  Directional -> Accuracy: 0.4565, MCC: -0.0367, F1: 0.3976

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.66570 | val 0.69588
  Epoch 020 - train 0.60042 | val 0.74670
  Classification -> best τ=0.385 (val F1=0.1345)
  Directional -> Accuracy: 0.5202, MCC: 0.0544, F1: 0.5274

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.60129 | val 3.58670
  Epoch 016 - train 0.56330 | val 4.51189
  Classification -> best τ=0.530 (val F1=0.1653)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63041 | val 1.54343
  Epoch 016 - train 0.58186 | val 2.06891
  Classification -> best τ=0.600 (val F1=0.1142)
  Directional -> Accuracy: 0.4646, MCC: 0.0145, F1: 0.1846

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63219 | val 2.59742
  Epoch 016 - train 0.60224 | val 3.25327
  Classification -> best τ=0.340 (val F1=0.1815)
  Directional -> Accuracy: 0.4545, MCC: 0.0904, F1: 0.0357

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62983 | val 0.96021
  Epoch 016 - train 0.57674 | val 1.22278
  Classification -> best τ=0.230 (val F1=0.2904)
  Directional -> Accuracy: 0.3990, MCC: 0.0806, F1: 0.0325

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58725 | val 3.20760
  Epoch 016 - train 0.51755 | val 5.06288
  Classification -> best τ=0.475 (val F1=0.1750)
  Directional -> Accuracy: 0.4196, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65204 | val 1.68528
  Epoch 016 - train 0.61937 | val 2.67817
  Classification -> best τ=0.245 (val F1=0.1025)
  Directional -> Accuracy: 0.4444, MCC: -0.0773, F1: 0.5896

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.61958 | val 1.03103
  Epoch 016 - train 0.55680 | val 1.00239
  Classification -> best τ=0.600 (val F1=0.1755)
  Directional -> Accuracy: 0.4747, MCC: 0.0342, F1: 0.1475

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.63129 | val 0.97471
  Epoch 016 - train 0.59852 | val 1.14045
  Classification -> best τ=0.445 (val F1=0.1357)
  Directional -> Accuracy: 0.4495, MCC: 0.0527, F1: 0.1550

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62255 | val 0.79850
  Epoch 016 - train 0.58795 | val 0.75868
  Classification -> best τ=0.460 (val F1=0.1457)
  Directional -> Accuracy: 0.5000, MCC: 0.0087, F1: 0.5123

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61548 | val 2.16836
  Epoch 016 - train 0.58235 | val 2.98228
  Classification -> best τ=0.695 (val F1=0.1710)
  Directional -> Accuracy: 0.5051, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.65106 | val 1.50941
  Epoch 016 - train 0.63316 | val 2.08627
  Classification -> best τ=0.670 (val F1=0.0683)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.63018 | val 1.57239
  Epoch 016 - train 0.60409 | val 1.70690
  Classification -> best τ=0.565 (val F1=0.1132)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.63983 | val 0.98733
  Epoch 016 - train 0.61891 | val 0.93254
  Classification -> best τ=0.715 (val F1=0.1082)
  Directional -> Accuracy: 0.4545, MCC: 0.0088, F1: 0.1290

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62724 | val 3.03266
  Epoch 016 - train 0.57234 | val 4.63051
  Classification -> best τ=0.585 (val F1=0.0788)
  Directional -> Accuracy: 0.5000, MCC: 0.1203, F1: 0.0571

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63607 | val 0.75792
  Epoch 016 - train 0.60292 | val 0.94102
  Classification -> best τ=0.470 (val F1=0.2139)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62556 | val 0.83282
  Epoch 016 - train 0.59031 | val 0.88937
  Classification -> best τ=0.835 (val F1=0.0980)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.65833 | val 0.96178
  Epoch 016 - train 0.61054 | val 1.08222
  Classification -> best τ=0.670 (val F1=0.1573)
  Directional -> Accuracy: 0.5152, MCC: 0.0270, F1: 0.1111

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.64924 | val 3.07585
  Epoch 016 - train 0.61674 | val 3.74749
  Classification -> best τ=0.175 (val F1=0.1714)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65213 | val 0.81199
  Epoch 016 - train 0.62305 | val 1.06599
  Classification -> best τ=0.430 (val F1=0.2005)
  Directional -> Accuracy: 0.5354, MCC: 0.1227, F1: 0.4250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.65127 | val 1.52011
  Epoch 016 - train 0.61643 | val 2.03978
  Classification -> best τ=0.520 (val F1=0.1214)
  Directional -> Accuracy: 0.5808, MCC: 0.0110, F1: 0.2095

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62177 | val 1.38160
  Epoch 016 - train 0.57377 | val 1.42365
  Classification -> best τ=0.240 (val F1=0.1463)
  Directional -> Accuracy: 0.5606, MCC: 0.1141, F1: 0.6063

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64432 | val 0.96931
  Epoch 016 - train 0.61573 | val 1.05913
  Classification -> best τ=0.545 (val F1=0.2014)
  Directional -> Accuracy: 0.5101, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62668 | val 1.37290
  Epoch 016 - train 0.60198 | val 1.76815
  Classification -> best τ=0.385 (val F1=0.1107)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.6915

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.65293 | val 1.27710
  Epoch 016 - train 0.62165 | val 1.59537
  Classification -> best τ=0.590 (val F1=0.1039)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62143 | val 3.32396
  Epoch 016 - train 0.59850 | val 4.22756
  Classification -> best τ=0.410 (val F1=0.1365)
  Directional -> Accuracy: 0.5000, MCC: 0.0006, F1: 0.4975

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.66290 | val 1.61910
  Epoch 016 - train 0.63929 | val 2.35119
  Classification -> best τ=0.430 (val F1=0.1843)
  Directional -> Accuracy: 0.5101, MCC: 0.0951, F1: 0.3401

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.66334 | val 2.11719
  Epoch 018 - train 0.60071 | val 2.99903
  Classification -> best τ=0.520 (val F1=0.0778)
  Directional -> Accuracy: 0.5303, MCC: 0.1423, F1: 0.2051

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63404 | val 2.03780
  Epoch 016 - train 0.60375 | val 2.56673
  Classification -> best τ=0.275 (val F1=0.1952)
  Directional -> Accuracy: 0.4798, MCC: -0.0589, F1: 0.5422

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.65693 | val 0.84465
  Epoch 016 - train 0.63902 | val 0.96459
  Classification -> best τ=0.455 (val F1=0.1503)
  Directional -> Accuracy: 0.5404, MCC: -0.0591, F1: 0.6715

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61580 | val 1.03320
  Epoch 016 - train 0.59898 | val 1.14720
  Classification -> best τ=0.360 (val F1=0.0720)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.6154

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.55096 | val 2.62557
  Epoch 016 - train 0.51091 | val 2.12019
  Classification -> best τ=0.495 (val F1=0.2039)
  Directional -> Accuracy: 0.5778, MCC: 0.1633, F1: 0.6122

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62755 | val 2.05658
  Epoch 016 - train 0.58957 | val 1.70087
  Classification -> best τ=0.505 (val F1=0.1888)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63803 | val 1.00860
  Epoch 016 - train 0.60909 | val 1.18973
  Classification -> best τ=0.515 (val F1=0.2452)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.63405 | val 1.62599
  Epoch 016 - train 0.59023 | val 1.81940
  Classification -> best τ=0.395 (val F1=0.1420)
  Directional -> Accuracy: 0.4495, MCC: 0.0346, F1: 0.1138

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.66269 | val 2.37387
  Epoch 016 - train 0.61596 | val 3.30287
  Classification -> best τ=0.525 (val F1=0.1247)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.64155 | val 2.52239
  Epoch 016 - train 0.59394 | val 4.00093
  Classification -> best τ=0.300 (val F1=0.1348)
  Directional -> Accuracy: 0.5152, MCC: 0.0249, F1: 0.5514

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.64615 | val 3.09921
  Epoch 016 - train 0.59436 | val 3.32018
  Classification -> best τ=0.720 (val F1=0.1693)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.2519

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63787 | val 1.84256
  Epoch 016 - train 0.58373 | val 2.34512
  Classification -> best τ=0.285 (val F1=0.0834)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.7016

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66398 | val 1.05471
  Epoch 020 - train 0.60217 | val 1.47815
  Classification -> best τ=0.225 (val F1=0.2005)
  Directional -> Accuracy: 0.5354, MCC: 0.0707, F1: 0.5400

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62873 | val 1.26318
  Epoch 016 - train 0.60844 | val 1.76785
  Classification -> best τ=0.615 (val F1=0.1589)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60592 | val 4.28471
  Epoch 016 - train 0.58209 | val 5.61995
  Classification -> best τ=0.085 (val F1=0.0089)
  Directional -> Accuracy: 0.5000, MCC: -0.0159, F1: 0.5600

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64023 | val 1.68192
  Epoch 016 - train 0.63022 | val 1.87962
  Classification -> best τ=0.715 (val F1=0.0657)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63931 | val 0.86458
  Epoch 016 - train 0.61489 | val 0.97107
  Classification -> best τ=0.690 (val F1=0.0867)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64220 | val 2.23599
  Epoch 016 - train 0.62304 | val 2.51119
  Classification -> best τ=0.105 (val F1=0.0716)
  Directional -> Accuracy: 0.4949, MCC: -0.0442, F1: 0.5726

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64903 | val 1.40845
  Epoch 016 - train 0.62695 | val 1.57625
  Classification -> best τ=0.220 (val F1=0.1697)
  Directional -> Accuracy: 0.4747, MCC: -0.0417, F1: 0.5593

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65091 | val 1.05905
  Epoch 016 - train 0.61489 | val 1.10136
  Classification -> best τ=0.340 (val F1=0.1512)
  Directional -> Accuracy: 0.5152, MCC: 0.0631, F1: 0.4894

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63684 | val 0.95811
  Epoch 016 - train 0.59470 | val 0.96998
  Classification -> best τ=0.465 (val F1=0.1103)
  Directional -> Accuracy: 0.4394, MCC: -0.0578, F1: 0.1778

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63625 | val 1.87168
  Epoch 016 - train 0.57433 | val 2.38323
  Classification -> best τ=0.215 (val F1=0.1266)
  Directional -> Accuracy: 0.5404, MCC: 0.0802, F1: 0.5687

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63881 | val 1.87420
  Epoch 016 - train 0.60146 | val 2.20159
  Classification -> best τ=0.315 (val F1=0.1301)
  Directional -> Accuracy: 0.4798, MCC: -0.0747, F1: 0.0190

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.63256 | val 0.73544
  Epoch 017 - train 0.60408 | val 0.75534
  Classification -> best τ=0.450 (val F1=0.1356)
  Directional -> Accuracy: 0.5556, MCC: -0.0201, F1: 0.6879

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.64112 | val 1.40711
  Epoch 016 - train 0.60470 | val 2.06777
  Classification -> best τ=0.455 (val F1=0.1215)
  Directional -> Accuracy: 0.4747, MCC: -0.0562, F1: 0.5969

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64929 | val 0.90548
  Epoch 016 - train 0.61283 | val 1.26657
  Classification -> best τ=0.480 (val F1=0.1214)
  Directional -> Accuracy: 0.5556, MCC: 0.1288, F1: 0.6857

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63480 | val 0.89412
  Epoch 017 - train 0.59645 | val 1.06833
  Classification -> best τ=0.340 (val F1=0.1375)
  Directional -> Accuracy: 0.5051, MCC: 0.0929, F1: 0.3099

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.64422 | val 0.72775
  Epoch 016 - train 0.62150 | val 0.75495
  Classification -> best τ=0.440 (val F1=0.0187)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.6931

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62021 | val 1.04820
  Epoch 016 - train 0.59433 | val 1.05685
  Classification -> best τ=0.550 (val F1=0.2839)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63133 | val 2.01734
  Epoch 016 - train 0.56923 | val 2.80559
  Classification -> best τ=0.370 (val F1=0.1828)
  Directional -> Accuracy: 0.5051, MCC: 0.0623, F1: 0.3378

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62617 | val 1.57582
  Epoch 016 - train 0.59595 | val 1.80032
  Classification -> best τ=0.110 (val F1=0.0742)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.6485

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64246 | val 1.96274
  Epoch 016 - train 0.59539 | val 2.40508
  Classification -> best τ=0.175 (val F1=0.1944)
  Directional -> Accuracy: 0.4949, MCC: 0.0181, F1: 0.2188

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.64325 | val 0.76767
  Epoch 016 - train 0.59679 | val 0.78793
  Classification -> best τ=0.200 (val F1=0.1568)
  Directional -> Accuracy: 0.4747, MCC: -0.0108, F1: 0.6031

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.65790 | val 1.55883
  Epoch 020 - train 0.58306 | val 3.53208
  Classification -> best τ=0.525 (val F1=0.1753)
  Directional -> Accuracy: 0.4394, MCC: 0.0876, F1: 0.0348

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.62175 | val 2.52348
  Epoch 016 - train 0.58960 | val 3.15772
  Classification -> best τ=0.405 (val F1=0.2006)
  Directional -> Accuracy: 0.4596, MCC: 0.0510, F1: 0.2517

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.64552 | val 0.84072
  Epoch 016 - train 0.59468 | val 1.14714
  Classification -> best τ=0.520 (val F1=0.2028)
  Directional -> Accuracy: 0.4794, MCC: 0.0454, F1: 0.5590

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.62612 | val 0.83293
  Epoch 016 - train 0.57009 | val 1.08732
  Classification -> best τ=0.770 (val F1=0.2042)
  Directional -> Accuracy: 0.4747, MCC: 0.0339, F1: 0.0370

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.60957 | val 1.48704
  Epoch 016 - train 0.57619 | val 1.77356
  Classification -> best τ=0.555 (val F1=0.1261)
  Directional -> Accuracy: 0.5052, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62944 | val 1.26742
  Epoch 016 - train 0.59870 | val 1.68878
  Classification -> best τ=0.475 (val F1=0.2396)
  Directional -> Accuracy: 0.4949, MCC: 0.0634, F1: 0.5798

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.63210 | val 1.07777
  Epoch 016 - train 0.59551 | val 1.55749
  Classification -> best τ=0.250 (val F1=0.1308)
  Directional -> Accuracy: 0.5052, MCC: 0.0241, F1: 0.6308

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.69038 | val 0.77555
  Epoch 020 - train 0.62848 | val 1.67579
  Classification -> best τ=0.645 (val F1=0.1233)
  Directional -> Accuracy: 0.5202, MCC: 0.0347, F1: 0.5622

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.63972 | val 1.53975
  Epoch 016 - train 0.61133 | val 1.32618
  Classification -> best τ=0.540 (val F1=0.1407)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.64990 | val 2.23807
  Epoch 016 - train 0.61891 | val 3.99701
  Classification -> best τ=0.255 (val F1=0.0612)
  Directional -> Accuracy: 0.5000, MCC: 0.1992, F1: 0.6452

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.65430 | val 1.65115
  Epoch 016 - train 0.61699 | val 2.18048
  Classification -> best τ=0.335 (val F1=0.1400)
  Directional -> Accuracy: 0.5000, MCC: 0.0428, F1: 0.2878

[75/88] Processing T...


[I 2026-02-26 05:38:03,944] Trial 45 finished with value: 0.14720768523671068 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.001824892089279627, 'weight_decay': 1.6672609723859964e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.9666417140911203, 'early_stopping_min_delta': 0.0020748914168980557}. Best is trial 38 with value: 0.1560660322497637.

  Classification -> best τ=0.370 (val F1=0.1489)
  Directional -> Accuracy: 0.5101, MCC: 0.0281, F1: 0.6008

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14720768523671068
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66768 | val 1.31903
  Epoch 016 - train 0.63166 | val 1.84189
  Classification -> best τ=0.195 (val F1=0.1643)
  Directional -> Accuracy: 0.4697, MCC: 0.0220, F1: 0.3787

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.64832 | val 5.20652
  Epoch 016 - train 0.60379 | val 8.22441
  Classification -> best τ=0.495 (val F1=0.1632)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68150 | val 1.14474
  Epoch 020 - train 0.62310 | val 1.87863
  Classification -> best τ=0.195 (val F1=0.1428)
  Directional -> Accuracy: 0.5054, MCC: -0.0109, F1: 0.5687

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.69165 | val 0.70341
  Epoch 020 - train 0.66644 | val 0.76900
  Classification -> best τ=0.460 (val F1=0.0829)
  Directional -> Accuracy: 0.5556, MCC: 0.0245, F1: 0.6879

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.63098 | val 0.71693
  Epoch 017 - train 0.59903 | val 0.78679
  Classification -> best τ=0.515 (val F1=0.2017)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66919 | val 1.36683
  Epoch 016 - train 0.64509 | val 1.81589
  Classification -> best τ=0.600 (val F1=0.1444)
  Directional -> Accuracy: 0.4747, MCC: -0.0368, F1: 0.4639

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66877 | val 2.55030
  Epoch 016 - train 0.63985 | val 1.19162
  Classification -> best τ=0.440 (val F1=0.2426)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.67583 | val 0.76473
  Epoch 020 - train 0.62834 | val 1.03556
  Classification -> best τ=0.150 (val F1=0.2494)
  Directional -> Accuracy: 0.4091, MCC: 0.1145, F1: 0.0640

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62652 | val 4.41194
  Epoch 016 - train 0.58774 | val 9.13739
  Classification -> best τ=0.190 (val F1=0.1895)
  Directional -> Accuracy: 0.4196, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67140 | val 1.31131
  Epoch 018 - train 0.64345 | val 2.11291
  Classification -> best τ=0.790 (val F1=0.1383)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.65024 | val 0.86282
  Epoch 016 - train 0.63575 | val 0.94246
  Classification -> best τ=0.590 (val F1=0.1771)
  Directional -> Accuracy: 0.4646, MCC: 0.0066, F1: 0.0862

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.67602 | val 0.92481
  Epoch 018 - train 0.64227 | val 0.88596
  Classification -> best τ=0.695 (val F1=0.1536)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66445 | val 0.72185
  Epoch 020 - train 0.61126 | val 0.79755
  Classification -> best τ=0.510 (val F1=0.1552)
  Directional -> Accuracy: 0.4646, MCC: 0.0534, F1: 0.1719

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64331 | val 2.02928
  Epoch 017 - train 0.62851 | val 2.29110
  Classification -> best τ=0.570 (val F1=0.2073)
  Directional -> Accuracy: 0.5202, MCC: 0.0547, F1: 0.1880

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.68264 | val 0.97190
  Epoch 020 - train 0.67556 | val 0.80876
  Classification -> best τ=0.460 (val F1=0.1030)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.65681 | val 1.21414
  Epoch 016 - train 0.63628 | val 1.28309
  Classification -> best τ=0.270 (val F1=0.1491)
  Directional -> Accuracy: 0.4949, MCC: -0.0101, F1: 0.4898

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.67917 | val 0.78694
  Epoch 020 - train 0.60710 | val 1.02382
  Classification -> best τ=0.455 (val F1=0.2008)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64224 | val 3.48117
  Epoch 016 - train 0.54675 | val 6.73648
  Classification -> best τ=0.705 (val F1=0.1748)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67588 | val 0.74464
  Epoch 020 - train 0.61909 | val 0.97511
  Classification -> best τ=0.490 (val F1=0.3370)
  Directional -> Accuracy: 0.4899, MCC: -0.0199, F1: 0.1653

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66032 | val 0.86686
  Epoch 016 - train 0.64922 | val 1.28258
  Classification -> best τ=0.675 (val F1=0.1715)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.68974 | val 0.72153
  Epoch 020 - train 0.64065 | val 1.01160
  Classification -> best τ=0.575 (val F1=0.1600)
  Directional -> Accuracy: 0.5051, MCC: 0.0252, F1: 0.6080

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.68175 | val 1.49937
  Epoch 017 - train 0.66874 | val 1.43564
  Classification -> best τ=0.135 (val F1=0.1331)
  Directional -> Accuracy: 0.5606, MCC: 0.0000, F1: 0.7184

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66589 | val 0.73673
  Epoch 016 - train 0.62412 | val 0.85548
  Classification -> best τ=0.450 (val F1=0.1084)
  Directional -> Accuracy: 0.5202, MCC: -0.0120, F1: 0.6442

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.68329 | val 1.06354
  Epoch 016 - train 0.64535 | val 1.61352
  Classification -> best τ=0.225 (val F1=0.1351)
  Directional -> Accuracy: 0.4192, MCC: 0.0355, F1: 0.5594

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65517 | val 1.15290
  Epoch 018 - train 0.60612 | val 2.52602
  Classification -> best τ=0.235 (val F1=0.1609)
  Directional -> Accuracy: 0.5556, MCC: 0.0994, F1: 0.6535

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66955 | val 0.85201
  Epoch 016 - train 0.65262 | val 1.01093
  Classification -> best τ=0.295 (val F1=0.1776)
  Directional -> Accuracy: 0.5606, MCC: 0.1250, F1: 0.5837

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67323 | val 0.78789
  Epoch 018 - train 0.62691 | val 1.23959
  Classification -> best τ=0.500 (val F1=0.1747)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.67228 | val 0.79201
  Epoch 016 - train 0.61960 | val 0.92988
  Classification -> best τ=0.470 (val F1=0.0994)
  Directional -> Accuracy: 0.4899, MCC: -0.1010, F1: 0.6576

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66498 | val 2.57158
  Epoch 016 - train 0.64572 | val 6.17678
  Classification -> best τ=0.875 (val F1=0.1400)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.68063 | val 0.81347
  Epoch 020 - train 0.63370 | val 1.48957
  Classification -> best τ=0.520 (val F1=0.1955)
  Directional -> Accuracy: 0.4899, MCC: 0.0777, F1: 0.2290

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.68022 | val 2.85647
  Epoch 016 - train 0.64584 | val 4.44158
  Classification -> best τ=0.260 (val F1=0.2293)
  Directional -> Accuracy: 0.5101, MCC: 0.0733, F1: 0.1565

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67802 | val 1.00255
  Epoch 018 - train 0.64196 | val 0.78421
  Classification -> best τ=0.380 (val F1=0.1698)
  Directional -> Accuracy: 0.5000, MCC: -0.0156, F1: 0.5561

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.67651 | val 0.77258
  Epoch 017 - train 0.65876 | val 0.98285
  Classification -> best τ=0.540 (val F1=0.1623)
  Directional -> Accuracy: 0.3990, MCC: 0.0201, F1: 0.0630

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64721 | val 1.04648
  Epoch 019 - train 0.59421 | val 1.44945
  Classification -> best τ=0.605 (val F1=0.0703)
  Directional -> Accuracy: 0.5556, MCC: 0.0308, F1: 0.1373

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.62347 | val 1.55704
  Epoch 016 - train 0.56122 | val 2.33811
  Classification -> best τ=0.405 (val F1=0.2548)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.6567

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64531 | val 0.92740
  Epoch 017 - train 0.62192 | val 0.75089
  Classification -> best τ=0.710 (val F1=0.2334)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67232 | val 0.72395
  Epoch 016 - train 0.64745 | val 0.70581
  Classification -> best τ=0.595 (val F1=0.2117)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.68053 | val 1.08194
  Epoch 016 - train 0.63440 | val 1.22536
  Classification -> best τ=0.355 (val F1=0.1198)
  Directional -> Accuracy: 0.5505, MCC: 0.0243, F1: 0.6740

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.67203 | val 1.13066
  Epoch 017 - train 0.65359 | val 1.72952
  Classification -> best τ=0.895 (val F1=0.0955)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.67825 | val 0.73907
  Epoch 016 - train 0.65925 | val 0.83022
  Classification -> best τ=0.605 (val F1=0.1513)
  Directional -> Accuracy: 0.4848, MCC: 0.0960, F1: 0.0377

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.68043 | val 1.06753
  Epoch 020 - train 0.64106 | val 1.91278
  Classification -> best τ=0.525 (val F1=0.1527)
  Directional -> Accuracy: 0.4798, MCC: -0.0268, F1: 0.2137

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68843 | val 1.06355
  Epoch 020 - train 0.62221 | val 1.51956
  Classification -> best τ=0.225 (val F1=0.1463)
  Directional -> Accuracy: 0.5505, MCC: 0.0650, F1: 0.6983

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68280 | val 0.89781
  Epoch 016 - train 0.64025 | val 1.26569
  Classification -> best τ=0.645 (val F1=0.1216)
  Directional -> Accuracy: 0.4949, MCC: 0.0172, F1: 0.1071

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68003 | val 0.88175
  Epoch 020 - train 0.64379 | val 1.45326
  Classification -> best τ=0.720 (val F1=0.2255)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64587 | val 2.51898
  Epoch 016 - train 0.65025 | val 3.51613
  Classification -> best τ=0.080 (val F1=0.0758)
  Directional -> Accuracy: 0.4848, MCC: -0.0478, F1: 0.5487

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67330 | val 0.92407
  Epoch 016 - train 0.64154 | val 1.18426
  Classification -> best τ=0.675 (val F1=0.0668)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66823 | val 0.91597
  Epoch 020 - train 0.62155 | val 0.77717
  Classification -> best τ=0.575 (val F1=0.0756)
  Directional -> Accuracy: 0.4444, MCC: -0.0074, F1: 0.0984

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66910 | val 0.87353
  Epoch 018 - train 0.62146 | val 1.51562
  Classification -> best τ=0.580 (val F1=0.1338)
  Directional -> Accuracy: 0.3990, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67615 | val 0.86256
  Epoch 016 - train 0.64391 | val 0.89027
  Classification -> best τ=0.635 (val F1=0.1658)
  Directional -> Accuracy: 0.5202, MCC: 0.0291, F1: 0.3448

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68532 | val 0.83759
  Epoch 019 - train 0.64995 | val 0.94379
  Classification -> best τ=0.680 (val F1=0.0951)
  Directional -> Accuracy: 0.4343, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68127 | val 0.72959
  Epoch 016 - train 0.65991 | val 0.83317
  Classification -> best τ=0.605 (val F1=0.0976)
  Directional -> Accuracy: 0.4293, MCC: -0.0894, F1: 0.1871

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65420 | val 2.08051
  Epoch 016 - train 0.62240 | val 2.05306
  Classification -> best τ=0.535 (val F1=0.1378)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67121 | val 0.93870
  Epoch 016 - train 0.63160 | val 1.09502
  Classification -> best τ=0.415 (val F1=0.1345)
  Directional -> Accuracy: 0.5101, MCC: 0.0000, F1: 0.6756

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.67947 | val 0.80246
  Epoch 018 - train 0.65071 | val 0.99313
  Classification -> best τ=0.620 (val F1=0.1493)
  Directional -> Accuracy: 0.4040, MCC: -0.0539, F1: 0.1061

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.66339 | val 0.95000
  Epoch 016 - train 0.65470 | val 1.46003
  Classification -> best τ=0.410 (val F1=0.1888)
  Directional -> Accuracy: 0.4848, MCC: -0.0607, F1: 0.6483

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67361 | val 1.97250
  Epoch 016 - train 0.67183 | val 3.77021
  Classification -> best τ=0.220 (val F1=0.0990)
  Directional -> Accuracy: 0.5404, MCC: 0.1495, F1: 0.6936

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65885 | val 0.97413
  Epoch 017 - train 0.62087 | val 1.03640
  Classification -> best τ=0.560 (val F1=0.1092)
  Directional -> Accuracy: 0.4495, MCC: -0.0470, F1: 0.1417

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.67119 | val 0.76287
  Epoch 016 - train 0.62240 | val 0.86671
  Classification -> best τ=0.455 (val F1=0.1371)
  Directional -> Accuracy: 0.5051, MCC: -0.0128, F1: 0.5917

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66496 | val 0.85024
  Epoch 017 - train 0.61084 | val 1.13881
  Classification -> best τ=0.615 (val F1=0.2855)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65914 | val 0.83025
  Epoch 016 - train 0.62631 | val 1.18170
  Classification -> best τ=0.625 (val F1=0.0706)
  Directional -> Accuracy: 0.4646, MCC: -0.0196, F1: 0.1167

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67915 | val 0.95464
  Epoch 018 - train 0.62466 | val 1.33664
  Classification -> best τ=0.090 (val F1=0.1333)
  Directional -> Accuracy: 0.4848, MCC: 0.0097, F1: 0.6357

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.68891 | val 1.71192
  Epoch 016 - train 0.65105 | val 2.14146
  Classification -> best τ=0.330 (val F1=0.1712)
  Directional -> Accuracy: 0.4899, MCC: 0.0273, F1: 0.0561

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.68887 | val 0.69846
  Epoch 020 - train 0.62945 | val 0.69695
  Classification -> best τ=0.300 (val F1=0.1542)
  Directional -> Accuracy: 0.5000, MCC: -0.0119, F1: 0.4277

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.67341 | val 1.05954
  Epoch 020 - train 0.60517 | val 3.42543
  Classification -> best τ=0.435 (val F1=0.2020)
  Directional -> Accuracy: 0.4798, MCC: 0.0136, F1: 0.4114

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.67568 | val 0.74181
  Epoch 018 - train 0.61554 | val 0.88369
  Classification -> best τ=0.435 (val F1=0.1052)
  Directional -> Accuracy: 0.5960, MCC: 0.1242, F1: 0.7403

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.65772 | val 1.28413
  Epoch 020 - train 0.61481 | val 1.66649
  Classification -> best τ=0.610 (val F1=0.2028)
  Directional -> Accuracy: 0.5103, MCC: 0.0339, F1: 0.4920

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.66689 | val 0.95311
  Epoch 017 - train 0.60196 | val 1.50923
  Classification -> best τ=0.420 (val F1=0.2326)
  Directional -> Accuracy: 0.5657, MCC: 0.1399, F1: 0.5521

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.67351 | val 0.80016
  Epoch 020 - train 0.63785 | val 1.33413
  Classification -> best τ=0.665 (val F1=0.1484)
  Directional -> Accuracy: 0.4948, MCC: -0.0209, F1: 0.2687

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65177 | val 2.33466
  Epoch 016 - train 0.61821 | val 3.47331
  Classification -> best τ=0.545 (val F1=0.2198)
  Directional -> Accuracy: 0.5051, MCC: 0.0126, F1: 0.4787

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.67376 | val 1.09063
  Epoch 016 - train 0.64091 | val 1.01526
  Classification -> best τ=0.445 (val F1=0.1622)
  Directional -> Accuracy: 0.5361, MCC: 0.0922, F1: 0.2742

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.68424 | val 0.75916
  Epoch 020 - train 0.66422 | val 0.68647
  Classification -> best τ=0.380 (val F1=0.2012)
  Directional -> Accuracy: 0.5051, MCC: -0.0014, F1: 0.5739

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67968 | val 1.37340
  Epoch 019 - train 0.62014 | val 1.56421
  Classification -> best τ=0.390 (val F1=0.1901)
  Directional -> Accuracy: 0.4848, MCC: -0.0031, F1: 0.0192

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.68849 | val 1.09547
  Epoch 018 - train 0.64781 | val 4.22842
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.69528 | val 0.90597
  Epoch 020 - train 0.61776 | val 1.17756
  Classification -> best τ=0.670 (val F1=0.1258)
  Directional -> Accuracy: 0.4747, MCC: -0.0051, F1: 0.0189

[75/88] Processing T...

Processing T (Technology)...

[I 2026-02-26 05:47:39,165] Trial 46 finished with value: 0.15544950709326608 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.005838518590537817, 'weight_decay': 5.083460835212678e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.7032904162057811, 'early_stopping_min_delta': 0.003427381129158874}. Best is trial 38 with value: 0.1560660322497637.

  Epoch 016 - train 0.64209 | val 1.71659
  Classification -> best τ=0.655 (val F1=0.1191)
  Directional -> Accuracy: 0.5051, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.15544950709326608
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.73387 | val 0.73612
  Epoch 016 - train 0.72824 | val 0.73603
  Classification -> best τ=0.450 (val F1=0.0744)
  Directional -> Accuracy: 0.5859, MCC: 0.0176, F1: 0.7372

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.71758 | val 0.78361
  Epoch 016 - train 0.71744 | val 0.78474
  Classification -> best τ=0.585 (val F1=0.1342)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.72963 | val 0.73467
  Epoch 016 - train 0.73065 | val 0.73442
  Classification -> best τ=0.500 (val F1=0.0504)
  Directional -> Accuracy: 0.5761, MCC: 0.0000, F1: 0.7310

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.72946 | val 0.69782
  Epoch 016 - train 0.72712 | val 0.69766
  Classification -> best τ=0.405 (val F1=0.0773)
  Directional -> Accuracy: 0.5707, MCC: 0.0581, F1: 0.7231

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.74089 | val 0.73834
  Epoch 016 - train 0.72950 | val 0.73818
  Classification -> best τ=0.540 (val F1=0.0673)
  Directional -> Accuracy: 0.4667, MCC: -0.0093, F1: 0.0345

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69916 | val 0.71226
  Epoch 016 - train 0.71956 | val 0.71250
  Classification -> best τ=0.465 (val F1=0.1439)
  Directional -> Accuracy: 0.5505, MCC: 0.0000, F1: 0.7101

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70210 | val 0.75913
  Epoch 016 - train 0.70469 | val 0.75965
  Classification -> best τ=0.390 (val F1=0.1189)
  Directional -> Accuracy: 0.4697, MCC: -0.0413, F1: 0.4503

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.72383 | val 0.71602
  Epoch 016 - train 0.70721 | val 0.71547
  Classification -> best τ=0.610 (val F1=0.1712)
  Directional -> Accuracy: 0.4040, MCC: 0.0624, F1: 0.0635

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.72681 | val 0.78263
  Epoch 016 - train 0.71923 | val 0.78177
  Classification -> best τ=0.495 (val F1=0.0392)
  Directional -> Accuracy: 0.5804, MCC: 0.0000, F1: 0.7345

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.73630 | val 0.72327
  Epoch 016 - train 0.72578 | val 0.72257
  Classification -> best τ=0.615 (val F1=0.0867)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.70417 | val 0.72077
  Epoch 016 - train 0.69583 | val 0.72049
  Classification -> best τ=0.560 (val F1=0.0870)
  Directional -> Accuracy: 0.5404, MCC: 0.0668, F1: 0.5956

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.71295 | val 0.70780
  Epoch 016 - train 0.70131 | val 0.70793
  Classification -> best τ=0.540 (val F1=0.1453)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.73373 | val 0.71019
  Epoch 016 - train 0.72592 | val 0.70986
  Classification -> best τ=0.465 (val F1=0.1218)
  Directional -> Accuracy: 0.5606, MCC: 0.0000, F1: 0.7184

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.72805 | val 0.81171
  Epoch 016 - train 0.73259 | val 0.81079
  Classification -> best τ=0.440 (val F1=0.0357)
  Directional -> Accuracy: 0.5051, MCC: 0.0703, F1: 0.6644

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.70582 | val 0.70201
  Epoch 016 - train 0.72427 | val 0.70192
  Classification -> best τ=0.605 (val F1=0.0698)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.70540 | val 0.70028
  Epoch 016 - train 0.70117 | val 0.70063
  Classification -> best τ=0.385 (val F1=0.1328)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.73337 | val 0.71840
  Epoch 016 - train 0.72067 | val 0.71788
  Classification -> best τ=0.395 (val F1=0.1146)
  Directional -> Accuracy: 0.5707, MCC: 0.0912, F1: 0.7119

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.70223 | val 0.82939
  Epoch 016 - train 0.70193 | val 0.82981
  Classification -> best τ=0.485 (val F1=0.1134)
  Directional -> Accuracy: 0.4899, MCC: -0.1310, F1: 0.6553

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71526 | val 0.73633
  Epoch 016 - train 0.71138 | val 0.73628
  Classification -> best τ=0.365 (val F1=0.0806)
  Directional -> Accuracy: 0.4394, MCC: -0.1246, F1: 0.3353

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70980 | val 0.71025
  Epoch 016 - train 0.70396 | val 0.71018
  Classification -> best τ=0.465 (val F1=0.0752)
  Directional -> Accuracy: 0.5101, MCC: -0.0801, F1: 0.6620

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.72486 | val 0.70275
  Epoch 016 - train 0.72561 | val 0.70260
  Classification -> best τ=0.485 (val F1=0.0739)
  Directional -> Accuracy: 0.5051, MCC: 0.0515, F1: 0.6500

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.69894 | val 0.76423
  Epoch 016 - train 0.70858 | val 0.76474
  Classification -> best τ=0.500 (val F1=0.1199)
  Directional -> Accuracy: 0.4545, MCC: 0.0776, F1: 0.0690

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.72130 | val 0.71524
  Epoch 016 - train 0.74105 | val 0.71524
  Classification -> best τ=0.460 (val F1=0.2473)
  Directional -> Accuracy: 0.5404, MCC: 0.0484, F1: 0.6403

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.73185 | val 0.70578
  Epoch 016 - train 0.73035 | val 0.70520
  Classification -> best τ=0.535 (val F1=0.0562)
  Directional -> Accuracy: 0.3939, MCC: 0.0000, F1: 0.5652

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.73388 | val 0.77630
  Epoch 016 - train 0.71877 | val 0.77665
  Classification -> best τ=0.365 (val F1=0.1117)
  Directional -> Accuracy: 0.5101, MCC: -0.0290, F1: 0.6523

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.72999 | val 0.71393
  Epoch 016 - train 0.72398 | val 0.71382
  Classification -> best τ=0.465 (val F1=0.1764)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.6576

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.71654 | val 0.71240
  Epoch 016 - train 0.70561 | val 0.71242
  Classification -> best τ=0.555 (val F1=0.0741)
  Directional -> Accuracy: 0.5606, MCC: 0.1255, F1: 0.5714

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.74150 | val 0.75526
  Epoch 016 - train 0.72817 | val 0.75539
  Classification -> best τ=0.495 (val F1=0.1484)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.73930 | val 0.73252
  Epoch 016 - train 0.73681 | val 0.73187
  Classification -> best τ=0.505 (val F1=0.0666)
  Directional -> Accuracy: 0.4646, MCC: -0.0684, F1: 0.3375

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.72068 | val 0.70774
  Epoch 016 - train 0.69811 | val 0.70782
  Classification -> best τ=0.365 (val F1=0.0757)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.72000 | val 0.70927
  Epoch 016 - train 0.71674 | val 0.70912
  Classification -> best τ=0.585 (val F1=0.0925)
  Directional -> Accuracy: 0.4394, MCC: -0.1224, F1: 0.4585

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70186 | val 0.74020
  Epoch 016 - train 0.70666 | val 0.74027
  Classification -> best τ=0.415 (val F1=0.2121)
  Directional -> Accuracy: 0.5051, MCC: 0.0205, F1: 0.5051

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.70569 | val 0.78620
  Epoch 016 - train 0.72543 | val 0.78551
  Classification -> best τ=0.690 (val F1=0.0339)
  Directional -> Accuracy: 0.4697, MCC: -0.0325, F1: 0.4928

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.72694 | val 0.73613
  Epoch 016 - train 0.71923 | val 0.73557
  Classification -> best τ=0.660 (val F1=0.1113)
  Directional -> Accuracy: 0.5253, MCC: -0.0707, F1: 0.1132

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.73411 | val 0.67953
  Epoch 020 - train 0.74879 | val 0.67927
  Classification -> best τ=0.600 (val F1=0.1523)
  Directional -> Accuracy: 0.4889, MCC: -0.0165, F1: 0.5490

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.74457 | val 0.75321
  Epoch 016 - train 0.73431 | val 0.75242
  Classification -> best τ=0.460 (val F1=0.0777)
  Directional -> Accuracy: 0.5808, MCC: 0.0000, F1: 0.7348

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.72415 | val 0.72701
  Epoch 016 - train 0.74057 | val 0.72683
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.6931

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.73960 | val 0.71677
  Epoch 016 - train 0.74554 | val 0.71634
  Classification -> best τ=0.515 (val F1=0.0870)
  Directional -> Accuracy: 0.5000, MCC: -0.0818, F1: 0.6236

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.73178 | val 0.71181
  Epoch 016 - train 0.72445 | val 0.71185
  Classification -> best τ=0.460 (val F1=0.0957)
  Directional -> Accuracy: 0.4848, MCC: -0.0428, F1: 0.5364

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.70814 | val 0.73960
  Epoch 016 - train 0.71224 | val 0.73988
  Classification -> best τ=0.655 (val F1=0.1196)
  Directional -> Accuracy: 0.4747, MCC: 0.0000, F1: 0.0000

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.72508 | val 0.70299
  Epoch 016 - train 0.71980 | val 0.70309
  Classification -> best τ=0.550 (val F1=0.0792)
  Directional -> Accuracy: 0.4848, MCC: -0.0128, F1: 0.2273

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71706 | val 0.73982
  Epoch 016 - train 0.71698 | val 0.74015
  Classification -> best τ=0.465 (val F1=0.0079)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.7016

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.73070 | val 0.71758
  Epoch 016 - train 0.72085 | val 0.71742
  Classification -> best τ=0.565 (val F1=0.1133)
  Directional -> Accuracy: 0.5303, MCC: 0.0577, F1: 0.6204

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.72159 | val 0.68963
  Epoch 020 - train 0.72240 | val 0.68841
  Classification -> best τ=0.545 (val F1=0.1329)
  Directional -> Accuracy: 0.4747, MCC: -0.1413, F1: 0.6312

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.71982 | val 0.72128
  Epoch 016 - train 0.72132 | val 0.72056
  Classification -> best τ=0.555 (val F1=0.1175)
  Directional -> Accuracy: 0.4394, MCC: -0.0944, F1: 0.1260

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.74765 | val 0.73480
  Epoch 016 - train 0.71937 | val 0.73450
  Classification -> best τ=0.415 (val F1=0.1540)
  Directional -> Accuracy: 0.4545, MCC: -0.0634, F1: 0.4600

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72309 | val 0.72745
  Epoch 016 - train 0.72786 | val 0.72725
  Classification -> best τ=0.605 (val F1=0.0867)
  Directional -> Accuracy: 0.4192, MCC: -0.1096, F1: 0.2069

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.72104 | val 0.77311
  Epoch 016 - train 0.73158 | val 0.77223
  Classification -> best τ=0.640 (val F1=0.1031)
  Directional -> Accuracy: 0.5101, MCC: 0.0185, F1: 0.5571

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.73590 | val 0.81577
  Epoch 016 - train 0.75272 | val 0.81573
  Classification -> best τ=0.350 (val F1=0.1314)
  Directional -> Accuracy: 0.5000, MCC: 0.0388, F1: 0.6374

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70395 | val 0.72612
  Epoch 016 - train 0.71603 | val 0.72631
  Classification -> best τ=0.475 (val F1=0.1082)
  Directional -> Accuracy: 0.4343, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70767 | val 0.70329
  Epoch 016 - train 0.71688 | val 0.70317
  Classification -> best τ=0.525 (val F1=0.0797)
  Directional -> Accuracy: 0.5758, MCC: 0.1038, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.73902 | val 0.73389
  Epoch 016 - train 0.72950 | val 0.73386
  Classification -> best τ=0.420 (val F1=0.0573)
  Directional -> Accuracy: 0.4949, MCC: -0.0319, F1: 0.6429

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.71083 | val 0.73436
  Epoch 016 - train 0.73219 | val 0.73419
  Classification -> best τ=0.575 (val F1=0.1613)
  Directional -> Accuracy: 0.5152, MCC: 0.0229, F1: 0.6496

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.70720 | val 0.69373
  Epoch 016 - train 0.70647 | val 0.69363
  Classification -> best τ=0.465 (val F1=0.1473)
  Directional -> Accuracy: 0.5758, MCC: -0.0366, F1: 0.7237

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.71248 | val 0.70621
  Epoch 016 - train 0.71734 | val 0.70600
  Classification -> best τ=0.415 (val F1=0.1041)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.6622

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70137 | val 0.80149
  Epoch 016 - train 0.71590 | val 0.80111
  Classification -> best τ=0.310 (val F1=0.1577)
  Directional -> Accuracy: 0.5303, MCC: 0.0506, F1: 0.6760

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.72318 | val 0.71441
  Epoch 016 - train 0.73032 | val 0.71442
  Classification -> best τ=0.515 (val F1=0.1207)
  Directional -> Accuracy: 0.4495, MCC: -0.0732, F1: 0.3626

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.71902 | val 0.77856
  Epoch 016 - train 0.70573 | val 0.77823
  Classification -> best τ=0.630 (val F1=0.0770)
  Directional -> Accuracy: 0.5455, MCC: 0.0770, F1: 0.6121

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.73401 | val 0.70253
  Epoch 016 - train 0.71537 | val 0.70253
  Classification -> best τ=0.570 (val F1=0.1338)
  Directional -> Accuracy: 0.4040, MCC: -0.1242, F1: 0.0167

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.73968 | val 0.72037
  Epoch 016 - train 0.73604 | val 0.72047
  Classification -> best τ=0.390 (val F1=0.0896)
  Directional -> Accuracy: 0.5354, MCC: 0.0180, F1: 0.6849

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.73899 | val 0.69957
  Epoch 016 - train 0.73330 | val 0.69903
  Classification -> best τ=0.565 (val F1=0.1194)
  Directional -> Accuracy: 0.5051, MCC: -0.0181, F1: 0.2687

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.72194 | val 0.71550
  Epoch 016 - train 0.71492 | val 0.71553
  Classification -> best τ=0.490 (val F1=0.1043)
  Directional -> Accuracy: 0.4798, MCC: -0.0332, F1: 0.0550

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.70106 | val 0.71405
  Epoch 016 - train 0.70667 | val 0.71423
  Classification -> best τ=0.490 (val F1=0.1089)
  Directional -> Accuracy: 0.4798, MCC: -0.0531, F1: 0.4046

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.72783 | val 0.73202
  Epoch 016 - train 0.74033 | val 0.73147
  Classification -> best τ=0.435 (val F1=0.1110)
  Directional -> Accuracy: 0.5606, MCC: -0.0876, F1: 0.7184

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.71851 | val 0.70457
  Epoch 016 - train 0.72785 | val 0.70421
  Classification -> best τ=0.555 (val F1=0.0734)
  Directional -> Accuracy: 0.4747, MCC: -0.0016, F1: 0.4348

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.72370 | val 0.84737
  Epoch 016 - train 0.71317 | val 0.84684
  Classification -> best τ=0.425 (val F1=0.1053)
  Directional -> Accuracy: 0.5258, MCC: -0.0595, F1: 0.2203

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.70779 | val 0.72667
  Epoch 016 - train 0.70971 | val 0.72655
  Classification -> best τ=0.520 (val F1=0.0576)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.75071 | val 0.71121
  Epoch 016 - train 0.74777 | val 0.71100
  Classification -> best τ=0.630 (val F1=0.1537)
  Directional -> Accuracy: 0.4742, MCC: -0.0508, F1: 0.5405

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.73081 | val 0.68885
  Epoch 016 - train 0.72150 | val 0.68863
  Classification -> best τ=0.535 (val F1=0.1476)
  Directional -> Accuracy: 0.5707, MCC: 0.1213, F1: 0.4910

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.72866 | val 0.77349
  Epoch 016 - train 0.74562 | val 0.77333
  Classification -> best τ=0.420 (val F1=0.1716)
  Directional -> Accuracy: 0.4639, MCC: -0.0716, F1: 0.4800

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.71460 | val 0.69191
  Epoch 016 - train 0.70794 | val 0.69201
  Classification -> best τ=0.455 (val F1=0.1167)
  Directional -> Accuracy: 0.5253, MCC: 0.0433, F1: 0.5766

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71673 | val 0.70408
  Epoch 016 - train 0.72722 | val 0.70351
  Classification -> best τ=0.560 (val F1=0.0661)
  Directional -> Accuracy: 0.5253, MCC: 0.0422, F1: 0.6594

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.74480 | val 0.91989
  Epoch 016 - train 0.73796 | val 0.92090
  Classification -> best τ=0.585 (val F1=0.1129)
  Directional -> Accuracy: 0.4747, MCC: 0.0283, F1: 0.6061

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.71205 | val 0.69940
  Epoch 016 - train 0.71964 | val 0.69945
  Classification -> best τ=0.400 (val F1=0.1187)
  Directional -> Accuracy: 0.5253, MCC: 0.0000, F1: 0.6887


[I 2026-02-26 05:56:20,108] Trial 47 finished with value: 0.10622995842650385 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 1.2363830705728619e-06, 'weight_decay': 5.451201996665756e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.70188090992441, 'early_stopping_min_delta': 0.0033253386331091026}. Best is trial 38 with value: 0.1560660322497637.

  Epoch 016 - train 0.71354 | val 0.70117
  Classification -> best τ=0.585 (val F1=0.1191)
  Directional -> Accuracy: 0.5101, MCC: 0.0720, F1: 0.0202

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.10622995842650385
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68130 | val 0.80824
  Epoch 016 - train 0.67266 | val 1.07182
  Classification -> best τ=0.390 (val F1=0.1453)
  Directional -> Accuracy: 0.4444, MCC: -0.0341, F1: 0.3452

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.65705 | val 2.41855
  Epoch 016 - train 0.61710 | val 5.73535
  Classification -> best τ=0.625 (val F1=0.1207)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68385 | val 0.71351
  Epoch 016 - train 0.65849 | val 0.72178
  Classification -> best τ=0.480 (val F1=0.1688)
  Directional -> Accuracy: 0.5924, MCC: 0.1272, F1: 0.7368

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.67905 | val 0.72900
  Epoch 016 - train 0.67853 | val 0.71420
  Classification -> best τ=0.525 (val F1=0.0773)
  Directional -> Accuracy: 0.5657, MCC: 0.0000, F1: 0.7226

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.67768 | val 0.70217
  Epoch 020 - train 0.60837 | val 1.51864
  Classification -> best τ=0.525 (val F1=0.2562)
  Directional -> Accuracy: 0.4571, MCC: -0.1048, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65943 | val 0.78411
  Epoch 017 - train 0.64136 | val 0.78472
  Classification -> best τ=0.515 (val F1=0.1391)
  Directional -> Accuracy: 0.4949, MCC: 0.0263, F1: 0.4253

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67535 | val 1.38889
  Epoch 017 - train 0.65933 | val 1.14762
  Classification -> best τ=0.465 (val F1=0.1741)
  Directional -> Accuracy: 0.4949, MCC: -0.0023, F1: 0.5050

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66548 | val 0.72037
  Epoch 020 - train 0.66173 | val 0.73462
  Classification -> best τ=0.490 (val F1=0.2153)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64351 | val 2.38048
  Epoch 016 - train 0.60890 | val 4.23241
  Classification -> best τ=0.340 (val F1=0.1672)
  Directional -> Accuracy: 0.4911, MCC: -0.0674, F1: 0.5839

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67780 | val 0.77941
  Epoch 016 - train 0.64031 | val 1.16146
  Classification -> best τ=0.675 (val F1=0.1242)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.68831 | val 0.68350
  Epoch 019 - train 0.67420 | val 0.73103
  Classification -> best τ=0.475 (val F1=0.1220)
  Directional -> Accuracy: 0.5556, MCC: 0.0779, F1: 0.6716

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.68927 | val 0.71424
  Epoch 016 - train 0.66061 | val 0.73725
  Classification -> best τ=0.605 (val F1=0.0950)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66891 | val 0.90226
  Epoch 017 - train 0.66450 | val 0.91537
  Classification -> best τ=0.475 (val F1=0.1409)
  Directional -> Accuracy: 0.5051, MCC: 0.0077, F1: 0.5377

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68300 | val 0.79621
  Epoch 018 - train 0.64683 | val 0.83555
  Classification -> best τ=0.620 (val F1=0.1994)
  Directional -> Accuracy: 0.5101, MCC: 0.0204, F1: 0.1709

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.69210 | val 0.71723
  Epoch 016 - train 0.67377 | val 0.73728
  Classification -> best τ=0.470 (val F1=0.1085)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.68021 | val 0.80225
  Epoch 016 - train 0.64708 | val 1.08707
  Classification -> best τ=0.445 (val F1=0.0575)
  Directional -> Accuracy: 0.5202, MCC: 0.0580, F1: 0.2520

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.68181 | val 0.69775
  Epoch 019 - train 0.66407 | val 0.71184
  Classification -> best τ=0.390 (val F1=0.1648)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67312 | val 1.26513
  Epoch 016 - train 0.64308 | val 1.60974
  Classification -> best τ=0.610 (val F1=0.0867)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67079 | val 0.73314
  Epoch 019 - train 0.62974 | val 0.83674
  Classification -> best τ=0.435 (val F1=0.2430)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66759 | val 0.78736
  Epoch 016 - train 0.66980 | val 0.76704
  Classification -> best τ=0.570 (val F1=0.1250)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.69372 | val 0.73166
  Epoch 016 - train 0.67282 | val 1.10216
  Classification -> best τ=0.600 (val F1=0.1439)
  Directional -> Accuracy: 0.5152, MCC: 0.0382, F1: 0.5752

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.68781 | val 0.69234
  Epoch 020 - train 0.68445 | val 0.76741
  Classification -> best τ=0.590 (val F1=0.1338)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68625 | val 1.08099
  Epoch 016 - train 0.65714 | val 1.27972
  Classification -> best τ=0.500 (val F1=0.1344)
  Directional -> Accuracy: 0.5505, MCC: 0.0608, F1: 0.6877

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.67016 | val 0.93694
  Epoch 016 - train 0.67700 | val 1.39365
  Classification -> best τ=0.240 (val F1=0.0940)
  Directional -> Accuracy: 0.4141, MCC: 0.0115, F1: 0.5538

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66763 | val 0.94866
  Epoch 016 - train 0.64352 | val 1.17111
  Classification -> best τ=0.385 (val F1=0.0852)
  Directional -> Accuracy: 0.5354, MCC: 0.0679, F1: 0.6892

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70114 | val 0.68525
  Epoch 020 - train 0.66317 | val 0.96041
  Classification -> best τ=0.345 (val F1=0.1771)
  Directional -> Accuracy: 0.5202, MCC: 0.0500, F1: 0.5852

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66408 | val 0.76454
  Epoch 016 - train 0.66126 | val 0.92914
  Classification -> best τ=0.500 (val F1=0.1733)
  Directional -> Accuracy: 0.5455, MCC: 0.0232, F1: 0.6939

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.69314 | val 0.80529
  Epoch 016 - train 0.66821 | val 1.45078
  Classification -> best τ=0.520 (val F1=0.1398)
  Directional -> Accuracy: 0.5101, MCC: 0.0207, F1: 0.4520

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67217 | val 0.70785
  Epoch 016 - train 0.66552 | val 0.70280
  Classification -> best τ=0.675 (val F1=0.1502)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.68288 | val 0.71347
  Epoch 018 - train 0.68702 | val 0.73128
  Classification -> best τ=0.425 (val F1=0.1318)
  Directional -> Accuracy: 0.5101, MCC: 0.0708, F1: 0.3975

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.68778 | val 1.22813
  Epoch 019 - train 0.66336 | val 1.74401
  Classification -> best τ=0.305 (val F1=0.2076)
  Directional -> Accuracy: 0.5303, MCC: 0.0619, F1: 0.6464

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68588 | val 0.76884
  Epoch 020 - train 0.67914 | val 1.32023
  Classification -> best τ=0.680 (val F1=0.0994)
  Directional -> Accuracy: 0.4495, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.67626 | val 0.75919
  Epoch 016 - train 0.66738 | val 0.71176
  Classification -> best τ=0.480 (val F1=0.1511)
  Directional -> Accuracy: 0.4848, MCC: 0.0153, F1: 0.4900

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66685 | val 0.90342
  Epoch 016 - train 0.66306 | val 1.40484
  Classification -> best τ=0.425 (val F1=0.1348)
  Directional -> Accuracy: 0.5354, MCC: 0.0381, F1: 0.4103

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.70403 | val 1.01620
  Epoch 016 - train 0.59028 | val 1.41260
  Classification -> best τ=0.460 (val F1=0.2130)
  Directional -> Accuracy: 0.5333, MCC: 0.1221, F1: 0.6557

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66004 | val 0.93958
  Epoch 016 - train 0.61617 | val 1.35401
  Classification -> best τ=0.530 (val F1=0.2099)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66125 | val 0.69075
  Epoch 020 - train 0.65164 | val 0.72958
  Classification -> best τ=0.630 (val F1=0.1868)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.67328 | val 0.81000
  Epoch 020 - train 0.66268 | val 0.92411
  Classification -> best τ=0.460 (val F1=0.1129)
  Directional -> Accuracy: 0.5556, MCC: 0.0144, F1: 0.6944

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.68641 | val 1.00951
  Epoch 016 - train 0.62860 | val 1.79594
  Classification -> best τ=0.565 (val F1=0.0955)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.68341 | val 1.70732
  Epoch 016 - train 0.65538 | val 3.30502
  Classification -> best τ=0.595 (val F1=0.0585)
  Directional -> Accuracy: 0.4596, MCC: -0.0667, F1: 0.1440

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.69617 | val 0.80578
  Epoch 020 - train 0.66385 | val 0.74709
  Classification -> best τ=0.465 (val F1=0.0768)
  Directional -> Accuracy: 0.4949, MCC: -0.0176, F1: 0.5536

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67862 | val 0.91668
  Epoch 016 - train 0.66835 | val 1.03713
  Classification -> best τ=0.445 (val F1=0.1531)
  Directional -> Accuracy: 0.5556, MCC: 0.0907, F1: 0.7027

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69148 | val 1.04019
  Epoch 016 - train 0.67238 | val 1.66728
  Classification -> best τ=0.490 (val F1=0.1216)
  Directional -> Accuracy: 0.4949, MCC: 0.0198, F1: 0.0909

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67045 | val 0.70717
  Epoch 016 - train 0.65900 | val 0.78985
  Classification -> best τ=0.550 (val F1=0.1795)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68102 | val 2.25309
  Epoch 016 - train 0.66869 | val 3.91186
  Classification -> best τ=0.255 (val F1=0.1294)
  Directional -> Accuracy: 0.5354, MCC: 0.0041, F1: 0.6828

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67719 | val 0.88111
  Epoch 016 - train 0.68281 | val 0.81480
  Classification -> best τ=0.460 (val F1=0.0686)
  Directional -> Accuracy: 0.5505, MCC: 0.0472, F1: 0.6397

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66365 | val 0.78820
  Epoch 016 - train 0.66664 | val 0.71820
  Classification -> best τ=0.470 (val F1=0.1735)
  Directional -> Accuracy: 0.5758, MCC: 0.0940, F1: 0.7162

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66881 | val 1.22244
  Epoch 016 - train 0.65015 | val 0.87308
  Classification -> best τ=0.465 (val F1=0.0072)
  Directional -> Accuracy: 0.5202, MCC: 0.0392, F1: 0.5662

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69260 | val 0.70958
  Epoch 016 - train 0.67184 | val 0.74400
  Classification -> best τ=0.480 (val F1=0.1842)
  Directional -> Accuracy: 0.5152, MCC: 0.0176, F1: 0.3425

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68392 | val 0.71693
  Epoch 019 - train 0.65917 | val 1.02631
  Classification -> best τ=0.520 (val F1=0.0791)
  Directional -> Accuracy: 0.4394, MCC: 0.0624, F1: 0.0177

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68235 | val 0.77987
  Epoch 020 - train 0.67355 | val 0.84053
  Classification -> best τ=0.485 (val F1=0.1210)
  Directional -> Accuracy: 0.4949, MCC: -0.0274, F1: 0.5536

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67819 | val 0.77459
  Epoch 016 - train 0.63669 | val 1.14503
  Classification -> best τ=0.585 (val F1=0.1143)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69999 | val 0.79655
  Epoch 019 - train 0.65842 | val 0.89514
  Classification -> best τ=0.330 (val F1=0.1717)
  Directional -> Accuracy: 0.5152, MCC: 0.0351, F1: 0.4667

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.68117 | val 0.69062
  Epoch 020 - train 0.63784 | val 0.69094
  Classification -> best τ=0.560 (val F1=0.1261)
  Directional -> Accuracy: 0.4192, MCC: -0.0113, F1: 0.1606

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.69062 | val 0.75012
  Epoch 016 - train 0.66554 | val 0.96167
  Classification -> best τ=0.475 (val F1=0.1890)
  Directional -> Accuracy: 0.4798, MCC: -0.0840, F1: 0.6436

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.69182 | val 0.86922
  Epoch 016 - train 0.68132 | val 0.72197
  Classification -> best τ=0.430 (val F1=0.1054)
  Directional -> Accuracy: 0.5303, MCC: 0.1052, F1: 0.6890

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68228 | val 0.76325
  Epoch 016 - train 0.65208 | val 0.98052
  Classification -> best τ=0.495 (val F1=0.0803)
  Directional -> Accuracy: 0.4596, MCC: -0.0037, F1: 0.1157

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.68055 | val 0.69202
  Epoch 019 - train 0.66640 | val 0.69406
  Classification -> best τ=0.495 (val F1=0.1474)
  Directional -> Accuracy: 0.5253, MCC: 0.0391, F1: 0.5804

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68032 | val 0.80161
  Epoch 016 - train 0.63106 | val 0.98226
  Classification -> best τ=0.515 (val F1=0.2033)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66384 | val 1.16419
  Epoch 016 - train 0.64325 | val 1.78557
  Classification -> best τ=0.420 (val F1=0.1996)
  Directional -> Accuracy: 0.5152, MCC: 0.0809, F1: 0.3684

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.67984 | val 1.03181
  Epoch 020 - train 0.64455 | val 1.05505
  Classification -> best τ=0.600 (val F1=0.1119)
  Directional -> Accuracy: 0.5253, MCC: 0.0351, F1: 0.0784

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65724 | val 0.90670
  Epoch 016 - train 0.63913 | val 1.17429
  Classification -> best τ=0.585 (val F1=0.1216)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.67706 | val 0.69155
  Epoch 016 - train 0.66288 | val 0.72157
  Classification -> best τ=0.415 (val F1=0.0671)
  Directional -> Accuracy: 0.4697, MCC: -0.0306, F1: 0.5817

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.67756 | val 1.41319
  Epoch 016 - train 0.65933 | val 0.91138
  Classification -> best τ=0.425 (val F1=0.0890)
  Directional -> Accuracy: 0.5101, MCC: 0.0017, F1: 0.5689

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.67262 | val 0.71890
  Epoch 016 - train 0.66363 | val 0.71476
  Classification -> best τ=0.500 (val F1=0.1314)
  Directional -> Accuracy: 0.4545, MCC: -0.0250, F1: 0.3721

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.67275 | val 0.88544
  Epoch 018 - train 0.63435 | val 1.02555
  Classification -> best τ=0.580 (val F1=0.2018)
  Directional -> Accuracy: 0.5361, MCC: 0.0307, F1: 0.4079

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.66001 | val 0.97423
  Epoch 016 - train 0.65480 | val 1.37889
  Classification -> best τ=0.560 (val F1=0.1212)
  Directional -> Accuracy: 0.4697, MCC: -0.0061, F1: 0.0187

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.67042 | val 0.98643
  Epoch 017 - train 0.63490 | val 0.93584
  Classification -> best τ=0.335 (val F1=0.1154)
  Directional -> Accuracy: 0.4845, MCC: -0.0324, F1: 0.6124

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68760 | val 0.71015
  Epoch 019 - train 0.64158 | val 0.80460
  Classification -> best τ=0.545 (val F1=0.2357)
  Directional -> Accuracy: 0.5152, MCC: 0.0678, F1: 0.5514

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.67166 | val 0.80257
  Epoch 016 - train 0.66797 | val 0.76666
  Classification -> best τ=0.505 (val F1=0.1649)
  Directional -> Accuracy: 0.5464, MCC: 0.1027, F1: 0.3803

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.69641 | val 0.72652
  Epoch 020 - train 0.67585 | val 0.78690
  Classification -> best τ=0.460 (val F1=0.1416)
  Directional -> Accuracy: 0.5152, MCC: 0.0197, F1: 0.5826

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.68897 | val 0.95180
  Epoch 020 - train 0.67628 | val 0.84178
  Classification -> best τ=0.565 (val F1=0.1744)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.67357 | val 0.91640
  Epoch 016 - train 0.67636 | val 0.84214
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.68607 | val 0.70224
  Epoch 020 - train 0.67091 | val 0.75358
  Classification -> best τ=0.475 (val F1=0.1823)
  Directional -> Accuracy: 0.5152, MCC: 0.0581, F1: 0.4000

[75/88] Processing T...


[I 2026-02-26 06:02:02,752] Trial 48 finished with value: 0.14238698563590502 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.009510691138312774, 'weight_decay': 1.157685203406931e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.812603529600979, 'early_stopping_min_delta': 0.004537771165272915}. Best is trial 38 with value: 0.1560660322497637.

  Epoch 016 - train 0.66496 | val 1.02645
  Classification -> best τ=0.425 (val F1=0.1622)
  Directional -> Accuracy: 0.4848, MCC: -0.0319, F1: 0.6136

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14238698563590502
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61297 | val 1.33302
  Epoch 016 - train 0.55031 | val 1.40684
  Classification -> best τ=0.110 (val F1=0.1835)
  Directional -> Accuracy: 0.4495, MCC: -0.0168, F1: 0.3394

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.53904 | val 9.76799
  Epoch 016 - train 0.43758 | val 15.59404
  Classification -> best τ=0.535 (val F1=0.1401)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61060 | val 1.10417
  Epoch 016 - train 0.53701 | val 1.76423
  Classification -> best τ=0.395 (val F1=0.2192)
  Directional -> Accuracy: 0.5652, MCC: 0.0635, F1: 0.6721

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.62453 | val 0.76376
  Epoch 017 - train 0.52282 | val 1.01639
  Classification -> best τ=0.590 (val F1=0.1268)
  Directional -> Accuracy: 0.4495, MCC: 0.0140, F1: 0.1550

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.55026 | val 1.55566
  Epoch 016 - train 0.48589 | val 4.22710
  Classification -> best τ=0.630 (val F1=0.1765)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64841 | val 1.17624
  Epoch 020 - train 0.50040 | val 1.66773
  Classification -> best τ=0.180 (val F1=0.1138)
  Directional -> Accuracy: 0.5303, MCC: 0.0101, F1: 0.6409

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61281 | val 3.32805
  Epoch 016 - train 0.57501 | val 5.11484
  Classification -> best τ=0.395 (val F1=0.1689)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63141 | val 0.98599
  Epoch 020 - train 0.46231 | val 1.23106
  Classification -> best τ=0.630 (val F1=0.3187)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50755 | val 4.29094
  Epoch 016 - train 0.41708 | val 5.36664
  Classification -> best τ=0.365 (val F1=0.1910)
  Directional -> Accuracy: 0.4196, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60813 | val 2.52675
  Epoch 016 - train 0.56611 | val 2.97525
  Classification -> best τ=0.725 (val F1=0.1090)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.56789 | val 0.96821
  Epoch 016 - train 0.50846 | val 0.99839
  Classification -> best τ=0.330 (val F1=0.1345)
  Directional -> Accuracy: 0.5202, MCC: 0.0127, F1: 0.6058

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.61595 | val 1.06672
  Epoch 016 - train 0.55352 | val 1.61405
  Classification -> best τ=0.400 (val F1=0.1428)
  Directional -> Accuracy: 0.4545, MCC: 0.0207, F1: 0.2500

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57276 | val 0.74119
  Epoch 016 - train 0.52503 | val 0.75921
  Classification -> best τ=0.640 (val F1=0.1475)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56435 | val 2.23053
  Epoch 017 - train 0.48700 | val 2.95070
  Classification -> best τ=0.670 (val F1=0.1986)
  Directional -> Accuracy: 0.5202, MCC: 0.0572, F1: 0.1739

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.65714 | val 1.20683
  Epoch 017 - train 0.58431 | val 2.40830
  Classification -> best τ=0.605 (val F1=0.0796)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.59630 | val 1.65550
  Epoch 016 - train 0.54193 | val 2.48156
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.61024 | val 0.99384
  Epoch 016 - train 0.53888 | val 1.15552
  Classification -> best τ=0.385 (val F1=0.1686)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54076 | val 4.69764
  Epoch 016 - train 0.43595 | val 6.67211
  Classification -> best τ=0.540 (val F1=0.1160)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57639 | val 0.87494
  Epoch 016 - train 0.47695 | val 1.09284
  Classification -> best τ=0.395 (val F1=0.2507)
  Directional -> Accuracy: 0.4747, MCC: -0.0534, F1: 0.2877

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60652 | val 0.94726
  Epoch 016 - train 0.55506 | val 1.00280
  Classification -> best τ=0.340 (val F1=0.1104)
  Directional -> Accuracy: 0.5253, MCC: 0.0592, F1: 0.5204

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.60370 | val 1.05589
  Epoch 016 - train 0.51900 | val 1.86024
  Classification -> best τ=0.315 (val F1=0.1614)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.6576

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.62801 | val 2.23542
  Epoch 017 - train 0.54147 | val 3.86661
  Classification -> best τ=0.285 (val F1=0.1588)
  Directional -> Accuracy: 0.5101, MCC: 0.0852, F1: 0.4121

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63833 | val 0.83497
  Epoch 018 - train 0.50609 | val 1.06814
  Classification -> best τ=0.250 (val F1=0.1541)
  Directional -> Accuracy: 0.5303, MCC: -0.0604, F1: 0.6910

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.61358 | val 1.84925
  Epoch 016 - train 0.53582 | val 2.60540
  Classification -> best τ=0.595 (val F1=0.1300)
  Directional -> Accuracy: 0.6061, MCC: 0.0000, F1: 0.0000

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58636 | val 1.58944
  Epoch 016 - train 0.49554 | val 2.57759
  Classification -> best τ=0.340 (val F1=0.1347)
  Directional -> Accuracy: 0.5051, MCC: 0.0261, F1: 0.4368

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65524 | val 0.97213
  Epoch 020 - train 0.52706 | val 1.54939
  Classification -> best τ=0.235 (val F1=0.1740)
  Directional -> Accuracy: 0.4949, MCC: -0.0515, F1: 0.1071

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60589 | val 1.66157
  Epoch 016 - train 0.51980 | val 2.64239
  Classification -> best τ=0.475 (val F1=0.1208)
  Directional -> Accuracy: 0.4091, MCC: -0.1581, F1: 0.2642

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.62024 | val 1.14449
  Epoch 016 - train 0.56208 | val 1.21716
  Classification -> best τ=0.505 (val F1=0.1378)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59482 | val 3.40032
  Epoch 016 - train 0.52101 | val 6.12762
  Classification -> best τ=0.485 (val F1=0.1536)
  Directional -> Accuracy: 0.5303, MCC: 0.0953, F1: 0.3212

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.62921 | val 0.88367
  Epoch 016 - train 0.55350 | val 1.12823
  Classification -> best τ=0.415 (val F1=0.1710)
  Directional -> Accuracy: 0.5455, MCC: 0.0211, F1: 0.6959

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.60160 | val 5.10828
  Epoch 016 - train 0.52963 | val 8.41539
  Classification -> best τ=0.120 (val F1=0.1504)
  Directional -> Accuracy: 0.5101, MCC: 0.0544, F1: 0.2240

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61621 | val 1.53203
  Epoch 016 - train 0.52057 | val 2.15336
  Classification -> best τ=0.370 (val F1=0.1414)
  Directional -> Accuracy: 0.4444, MCC: -0.0542, F1: 0.0179

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.65405 | val 0.94075
  Epoch 016 - train 0.59610 | val 1.22659
  Classification -> best τ=0.545 (val F1=0.2086)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62124 | val 0.84681
  Epoch 017 - train 0.51433 | val 1.59340
  Classification -> best τ=0.280 (val F1=0.1020)
  Directional -> Accuracy: 0.4545, MCC: 0.0562, F1: 0.6170

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.49637 | val 3.49857
  Epoch 016 - train 0.39474 | val 3.65132
  Classification -> best τ=0.485 (val F1=0.2405)
  Directional -> Accuracy: 0.5778, MCC: 0.1561, F1: 0.5778

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58723 | val 0.83954
  Epoch 016 - train 0.49960 | val 1.06592
  Classification -> best τ=0.565 (val F1=0.2018)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61523 | val 1.44242
  Epoch 016 - train 0.53939 | val 2.56236
  Classification -> best τ=0.505 (val F1=0.2057)
  Directional -> Accuracy: 0.4646, MCC: -0.0757, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.61580 | val 1.04954
  Epoch 016 - train 0.53676 | val 1.20210
  Classification -> best τ=0.140 (val F1=0.1387)
  Directional -> Accuracy: 0.5606, MCC: 0.0929, F1: 0.6298

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.60609 | val 1.92077
  Epoch 016 - train 0.52218 | val 3.14993
  Classification -> best τ=0.810 (val F1=0.0955)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.63899 | val 1.23218
  Epoch 017 - train 0.56201 | val 2.56193
  Classification -> best τ=0.300 (val F1=0.0950)
  Directional -> Accuracy: 0.4949, MCC: -0.0127, F1: 0.5192

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.60288 | val 2.80752
  Epoch 016 - train 0.54131 | val 6.98221
  Classification -> best τ=0.680 (val F1=0.1529)
  Directional -> Accuracy: 0.4899, MCC: -0.0308, F1: 0.5628

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61175 | val 1.24726
  Epoch 016 - train 0.52755 | val 1.96604
  Classification -> best τ=0.740 (val F1=0.1065)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61959 | val 1.52856
  Epoch 016 - train 0.55447 | val 1.92322
  Classification -> best τ=0.510 (val F1=0.1876)
  Directional -> Accuracy: 0.5051, MCC: 0.0683, F1: 0.1091

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59189 | val 2.24493
  Epoch 016 - train 0.50288 | val 3.36415
  Classification -> best τ=0.740 (val F1=0.2016)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57847 | val 2.82245
  Epoch 017 - train 0.47080 | val 4.39274
  Classification -> best τ=0.055 (val F1=0.1277)
  Directional -> Accuracy: 0.5303, MCC: 0.0254, F1: 0.6324

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63120 | val 1.16140
  Epoch 016 - train 0.58049 | val 1.45162
  Classification -> best τ=0.685 (val F1=0.0657)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62600 | val 0.97838
  Epoch 017 - train 0.53734 | val 1.08547
  Classification -> best τ=0.305 (val F1=0.1354)
  Directional -> Accuracy: 0.5354, MCC: 0.0867, F1: 0.5354

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60021 | val 2.56349
  Epoch 016 - train 0.50574 | val 5.09381
  Classification -> best τ=0.210 (val F1=0.1331)
  Directional -> Accuracy: 0.4798, MCC: -0.1650, F1: 0.6142

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.61991 | val 0.88898
  Epoch 016 - train 0.53494 | val 1.14551
  Classification -> best τ=0.275 (val F1=0.1430)
  Directional -> Accuracy: 0.5152, MCC: 0.1022, F1: 0.6547

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61852 | val 1.16317
  Epoch 017 - train 0.54123 | val 1.24469
  Classification -> best τ=0.260 (val F1=0.0958)
  Directional -> Accuracy: 0.5505, MCC: -0.0761, F1: 0.7082

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.60018 | val 0.97388
  Epoch 016 - train 0.54006 | val 0.99334
  Classification -> best τ=0.355 (val F1=0.1322)
  Directional -> Accuracy: 0.4798, MCC: -0.0812, F1: 0.5726

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58673 | val 1.09059
  Epoch 016 - train 0.52693 | val 1.17464
  Classification -> best τ=0.470 (val F1=0.1556)
  Directional -> Accuracy: 0.4899, MCC: -0.0245, F1: 0.0901

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62616 | val 0.96335
  Epoch 020 - train 0.50268 | val 1.62729
  Classification -> best τ=0.430 (val F1=0.1520)
  Directional -> Accuracy: 0.4949, MCC: 0.0289, F1: 0.0566

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.63442 | val 0.96547
  Epoch 019 - train 0.51580 | val 0.84813
  Classification -> best τ=0.490 (val F1=0.1548)
  Directional -> Accuracy: 0.4192, MCC: -0.0172, F1: 0.1727

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.61347 | val 1.43775
  Epoch 016 - train 0.53452 | val 1.88622
  Classification -> best τ=0.370 (val F1=0.1930)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.6622

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.62440 | val 2.84792
  Epoch 016 - train 0.55517 | val 5.27865
  Classification -> best τ=0.475 (val F1=0.1017)
  Directional -> Accuracy: 0.5152, MCC: 0.0287, F1: 0.5340

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64649 | val 0.94707
  Epoch 018 - train 0.51803 | val 1.60643
  Classification -> best τ=0.570 (val F1=0.1962)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.62642 | val 0.82969
  Epoch 016 - train 0.55780 | val 1.41772
  Classification -> best τ=0.540 (val F1=0.0908)
  Directional -> Accuracy: 0.5404, MCC: 0.0687, F1: 0.5991

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61282 | val 1.07814
  Epoch 016 - train 0.51928 | val 1.41477
  Classification -> best τ=0.545 (val F1=0.2115)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61927 | val 1.38365
  Epoch 017 - train 0.50098 | val 1.94071
  Classification -> best τ=0.345 (val F1=0.1960)
  Directional -> Accuracy: 0.5101, MCC: 0.0949, F1: 0.2920

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61826 | val 1.62208
  Epoch 018 - train 0.48408 | val 2.94122
  Classification -> best τ=0.065 (val F1=0.1292)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.6485

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60499 | val 1.71783
  Epoch 017 - train 0.53013 | val 3.65786
  Classification -> best τ=0.335 (val F1=0.2341)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.59759 | val 0.76777
  Epoch 016 - train 0.52897 | val 0.81352
  Classification -> best τ=0.430 (val F1=0.1101)
  Directional -> Accuracy: 0.5152, MCC: -0.0254, F1: 0.1724

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.60528 | val 2.86362
  Epoch 016 - train 0.50537 | val 3.29483
  Classification -> best τ=0.245 (val F1=0.1860)
  Directional -> Accuracy: 0.4596, MCC: 0.0700, F1: 0.1705

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.59037 | val 1.42013
  Epoch 016 - train 0.49288 | val 1.83855
  Classification -> best τ=0.380 (val F1=0.1052)
  Directional -> Accuracy: 0.5808, MCC: 0.0000, F1: 0.7348

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.56015 | val 0.85913
  Epoch 016 - train 0.46594 | val 1.13106
  Classification -> best τ=0.610 (val F1=0.2028)
  Directional -> Accuracy: 0.5309, MCC: 0.0149, F1: 0.3893

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.59027 | val 0.97957
  Epoch 016 - train 0.50669 | val 1.71350
  Classification -> best τ=0.550 (val F1=0.1884)
  Directional -> Accuracy: 0.5455, MCC: 0.1264, F1: 0.4512

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.58904 | val 1.39754
  Epoch 017 - train 0.52799 | val 1.54734
  Classification -> best τ=0.605 (val F1=0.1204)
  Directional -> Accuracy: 0.5052, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60695 | val 1.93621
  Epoch 016 - train 0.50659 | val 3.25823
  Classification -> best τ=0.560 (val F1=0.2231)
  Directional -> Accuracy: 0.4545, MCC: -0.0247, F1: 0.5574

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.60973 | val 0.91319
  Epoch 016 - train 0.49110 | val 1.06295
  Classification -> best τ=0.345 (val F1=0.1512)
  Directional -> Accuracy: 0.5464, MCC: 0.1041, F1: 0.3714

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.67563 | val 0.77346
  Epoch 019 - train 0.54729 | val 1.05790
  Classification -> best τ=0.565 (val F1=0.1838)
  Directional -> Accuracy: 0.5253, MCC: 0.0634, F1: 0.4659

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.60590 | val 2.24473
  Epoch 017 - train 0.47422 | val 3.73085
  Classification -> best τ=0.325 (val F1=0.2068)
  Directional -> Accuracy: 0.5000, MCC: 0.0588, F1: 0.1239

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.60454 | val 3.87522
  Epoch 016 - train 0.51946 | val 7.08201
  Classification -> best τ=0.480 (val F1=0.1109)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.61280 | val 1.30516
  Epoch 016 - train 0.53249 | val 1.79419
  Classification -> best τ=0.210 (val F1=0.1081)
  Directional -> Accuracy: 0.5202, MCC: -0.0098, F1: 0.6735

[75/88] Processing T...


[I 2026-02-26 06:10:53,156] Trial 49 finished with value: 0.15376707628014782 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.0058421379847393975, 'weight_decay': 3.168676012274041e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.6450519010197007, 'early_stopping_min_delta': 0.00564773878783178}. Best is trial 38 with value: 0.1560660322497637.

  Epoch 016 - train 0.55078 | val 3.87114
  Classification -> best τ=0.465 (val F1=0.1641)
  Directional -> Accuracy: 0.4949, MCC: -0.0075, F1: 0.5575

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.15376707628014782
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68686 | val 0.73904
  Epoch 016 - train 0.67254 | val 0.76207
  Classification -> best τ=0.445 (val F1=0.1314)
  Directional -> Accuracy: 0.4394, MCC: 0.0232, F1: 0.1898

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.62517 | val 1.69262
  Epoch 016 - train 0.59371 | val 1.81624
  Classification -> best τ=0.505 (val F1=0.2358)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64765 | val 0.85763
  Epoch 016 - train 0.62681 | val 1.05135
  Classification -> best τ=0.465 (val F1=0.1620)
  Directional -> Accuracy: 0.4076, MCC: -0.1065, F1: 0.1280

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.67296 | val 0.89578
  Epoch 016 - train 0.65847 | val 1.06125
  Classification -> best τ=0.470 (val F1=0.0837)
  Directional -> Accuracy: 0.5657, MCC: 0.0000, F1: 0.7226

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.64919 | val 0.69083
  Epoch 016 - train 0.59147 | val 0.70912
  Classification -> best τ=0.540 (val F1=0.1406)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67323 | val 0.72424
  Epoch 016 - train 0.64628 | val 0.77972
  Classification -> best τ=0.510 (val F1=0.1155)
  Directional -> Accuracy: 0.4596, MCC: -0.0356, F1: 0.3270

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65583 | val 3.74404
  Epoch 016 - train 0.64999 | val 4.18304
  Classification -> best τ=0.520 (val F1=0.1367)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68742 | val 0.68238
  Epoch 020 - train 0.62787 | val 0.69642
  Classification -> best τ=0.405 (val F1=0.2390)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65088 | val 0.97754
  Epoch 016 - train 0.60224 | val 1.06324
  Classification -> best τ=0.430 (val F1=0.1962)
  Directional -> Accuracy: 0.4196, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67727 | val 0.71738
  Epoch 017 - train 0.66223 | val 0.73321
  Classification -> best τ=0.690 (val F1=0.1645)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.66685 | val 0.70892
  Epoch 016 - train 0.63764 | val 0.73843
  Classification -> best τ=0.505 (val F1=0.1714)
  Directional -> Accuracy: 0.5101, MCC: 0.0015, F1: 0.5764

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.64969 | val 0.69982
  Epoch 016 - train 0.64066 | val 0.69602
  Classification -> best τ=0.520 (val F1=0.1191)
  Directional -> Accuracy: 0.4394, MCC: -0.0524, F1: 0.3190

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66542 | val 0.70008
  Epoch 016 - train 0.65804 | val 0.71702
  Classification -> best τ=0.530 (val F1=0.0618)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64560 | val 1.33285
  Epoch 016 - train 0.62280 | val 1.37730
  Classification -> best τ=0.560 (val F1=0.1231)
  Directional -> Accuracy: 0.5051, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.68275 | val 0.79250
  Epoch 016 - train 0.66229 | val 0.76192
  Classification -> best τ=0.520 (val F1=0.0888)
  Directional -> Accuracy: 0.4697, MCC: -0.0087, F1: 0.0367

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.63860 | val 0.86390
  Epoch 016 - train 0.62142 | val 1.00985
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.66084 | val 0.75486
  Epoch 016 - train 0.64468 | val 0.77462
  Classification -> best τ=0.515 (val F1=0.1551)
  Directional -> Accuracy: 0.5152, MCC: 0.0362, F1: 0.5294

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64108 | val 0.73634
  Epoch 016 - train 0.62010 | val 0.80224
  Classification -> best τ=0.575 (val F1=0.1972)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67469 | val 0.68997
  Epoch 020 - train 0.60990 | val 1.22101
  Classification -> best τ=0.545 (val F1=0.2534)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67166 | val 0.70448
  Epoch 016 - train 0.65283 | val 0.74126
  Classification -> best τ=0.480 (val F1=0.0734)
  Directional -> Accuracy: 0.5202, MCC: -0.0075, F1: 0.6388

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.68021 | val 0.69559
  Epoch 020 - train 0.64286 | val 0.72222
  Classification -> best τ=0.525 (val F1=0.1413)
  Directional -> Accuracy: 0.4747, MCC: -0.0533, F1: 0.6148

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.67274 | val 1.29151
  Epoch 016 - train 0.66498 | val 1.65740
  Classification -> best τ=0.465 (val F1=0.1391)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66162 | val 0.87775
  Epoch 016 - train 0.65158 | val 1.13171
  Classification -> best τ=0.530 (val F1=0.0979)
  Directional -> Accuracy: 0.4495, MCC: -0.0608, F1: 0.1417

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.66593 | val 0.76175
  Epoch 016 - train 0.64662 | val 0.80517
  Classification -> best τ=0.510 (val F1=0.1079)
  Directional -> Accuracy: 0.4293, MCC: 0.0192, F1: 0.5462

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65287 | val 1.08318
  Epoch 016 - train 0.64221 | val 1.20606
  Classification -> best τ=0.380 (val F1=0.1869)
  Directional -> Accuracy: 0.5606, MCC: 0.1169, F1: 0.5915

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66559 | val 0.70959
  Epoch 018 - train 0.64145 | val 0.75805
  Classification -> best τ=0.450 (val F1=0.2120)
  Directional -> Accuracy: 0.4697, MCC: -0.0864, F1: 0.2553

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64216 | val 1.21933
  Epoch 016 - train 0.62538 | val 1.54542
  Classification -> best τ=0.545 (val F1=0.1359)
  Directional -> Accuracy: 0.4343, MCC: -0.1137, F1: 0.0508

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.66984 | val 0.91951
  Epoch 017 - train 0.65559 | val 1.31957
  Classification -> best τ=0.450 (val F1=0.1013)
  Directional -> Accuracy: 0.5051, MCC: 0.0164, F1: 0.1833

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66931 | val 0.70403
  Epoch 016 - train 0.66291 | val 0.71134
  Classification -> best τ=0.545 (val F1=0.1859)
  Directional -> Accuracy: 0.4949, MCC: 0.0698, F1: 0.0196

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.66432 | val 1.21622
  Epoch 016 - train 0.63905 | val 1.44630
  Classification -> best τ=0.485 (val F1=0.0757)
  Directional -> Accuracy: 0.5505, MCC: 0.0780, F1: 0.7082

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.67761 | val 0.78576
  Epoch 016 - train 0.65410 | val 0.79622
  Classification -> best τ=0.470 (val F1=0.1683)
  Directional -> Accuracy: 0.4949, MCC: 0.0039, F1: 0.2647

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66456 | val 1.04086
  Epoch 016 - train 0.64158 | val 1.23295
  Classification -> best τ=0.550 (val F1=0.0976)
  Directional -> Accuracy: 0.4394, MCC: -0.0703, F1: 0.1898

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.68525 | val 0.68806
  Epoch 017 - train 0.67795 | val 0.69059
  Classification -> best τ=0.580 (val F1=0.1439)
  Directional -> Accuracy: 0.4141, MCC: 0.0056, F1: 0.1831

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68141 | val 1.03193
  Epoch 016 - train 0.66690 | val 1.25743
  Classification -> best τ=0.500 (val F1=0.0705)
  Directional -> Accuracy: 0.5505, MCC: 0.0406, F1: 0.2880

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.63854 | val 0.77011
  Epoch 016 - train 0.62175 | val 0.82107
  Classification -> best τ=0.450 (val F1=0.2119)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.6567

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65232 | val 1.60730
  Epoch 016 - train 0.63265 | val 1.47668
  Classification -> best τ=0.460 (val F1=0.0742)
  Directional -> Accuracy: 0.5657, MCC: 0.0643, F1: 0.6692

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65503 | val 0.74823
  Epoch 018 - train 0.61079 | val 0.83778
  Classification -> best τ=0.575 (val F1=0.1844)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.66913 | val 1.05132
  Epoch 016 - train 0.66037 | val 1.16542
  Classification -> best τ=0.490 (val F1=0.1959)
  Directional -> Accuracy: 0.4798, MCC: 0.0541, F1: 0.3087

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.67661 | val 0.95855
  Epoch 016 - train 0.66762 | val 1.11480
  Classification -> best τ=0.445 (val F1=0.0989)
  Directional -> Accuracy: 0.5455, MCC: 0.0211, F1: 0.6959

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.65056 | val 1.07514
  Epoch 016 - train 0.65558 | val 1.21347
  Classification -> best τ=0.585 (val F1=0.1234)
  Directional -> Accuracy: 0.4747, MCC: -0.0051, F1: 0.0189

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.68018 | val 0.81699
  Epoch 016 - train 0.65231 | val 0.73435
  Classification -> best τ=0.455 (val F1=0.0477)
  Directional -> Accuracy: 0.4848, MCC: -0.0384, F1: 0.5446

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67468 | val 1.14394
  Epoch 016 - train 0.64579 | val 1.33479
  Classification -> best τ=0.485 (val F1=0.1977)
  Directional -> Accuracy: 0.5707, MCC: 0.1365, F1: 0.6009

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65738 | val 1.02649
  Epoch 016 - train 0.65473 | val 1.10547
  Classification -> best τ=0.445 (val F1=0.1581)
  Directional -> Accuracy: 0.5354, MCC: 0.0862, F1: 0.6667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68171 | val 0.70093
  Epoch 016 - train 0.65431 | val 0.69956
  Classification -> best τ=0.470 (val F1=0.1523)
  Directional -> Accuracy: 0.4646, MCC: -0.0664, F1: 0.4421

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65432 | val 1.97181
  Epoch 016 - train 0.65872 | val 2.40974
  Classification -> best τ=0.380 (val F1=0.1491)
  Directional -> Accuracy: 0.5354, MCC: 0.0348, F1: 0.6406

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67237 | val 0.76109
  Epoch 019 - train 0.65212 | val 0.76114
  Classification -> best τ=0.560 (val F1=0.1446)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67326 | val 0.69977
  Epoch 020 - train 0.62077 | val 0.70677
  Classification -> best τ=0.610 (val F1=0.1190)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66102 | val 0.78814
  Epoch 016 - train 0.64174 | val 0.96279
  Classification -> best τ=0.435 (val F1=0.1331)
  Directional -> Accuracy: 0.5202, MCC: -0.0700, F1: 0.6442

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66138 | val 1.05525
  Epoch 016 - train 0.64084 | val 1.11230
  Classification -> best τ=0.550 (val F1=0.0404)
  Directional -> Accuracy: 0.5202, MCC: 0.0294, F1: 0.3537

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66673 | val 0.71960
  Epoch 017 - train 0.64827 | val 0.80218
  Classification -> best τ=0.515 (val F1=0.0885)
  Directional -> Accuracy: 0.4343, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66809 | val 0.92192
  Epoch 016 - train 0.65831 | val 1.33671
  Classification -> best τ=0.420 (val F1=0.1329)
  Directional -> Accuracy: 0.5152, MCC: -0.0024, F1: 0.5966

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66897 | val 0.75079
  Epoch 020 - train 0.59579 | val 0.79366
  Classification -> best τ=0.460 (val F1=0.1491)
  Directional -> Accuracy: 0.5000, MCC: 0.0705, F1: 0.0198

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67136 | val 0.98490
  Epoch 016 - train 0.64005 | val 1.08218
  Classification -> best τ=0.565 (val F1=0.0909)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.66867 | val 0.70250
  Epoch 016 - train 0.62070 | val 0.70688
  Classification -> best τ=0.515 (val F1=0.0667)
  Directional -> Accuracy: 0.4343, MCC: 0.0456, F1: 0.1765

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.65496 | val 0.89383
  Epoch 018 - train 0.61188 | val 1.23055
  Classification -> best τ=0.450 (val F1=0.1661)
  Directional -> Accuracy: 0.4747, MCC: -0.0738, F1: 0.2239

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68998 | val 0.78327
  Epoch 020 - train 0.63995 | val 1.14029
  Classification -> best τ=0.480 (val F1=0.1660)
  Directional -> Accuracy: 0.5505, MCC: 0.0931, F1: 0.6180

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65756 | val 0.71832
  Epoch 016 - train 0.63416 | val 0.76481
  Classification -> best τ=0.500 (val F1=0.1601)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.65620 | val 1.23119
  Epoch 016 - train 0.64898 | val 2.28932
  Classification -> best τ=0.555 (val F1=0.0780)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.6931

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64642 | val 0.71164
  Epoch 016 - train 0.62353 | val 0.78293
  Classification -> best τ=0.525 (val F1=0.1481)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65654 | val 1.13933
  Epoch 016 - train 0.62962 | val 1.59270
  Classification -> best τ=0.405 (val F1=0.2067)
  Directional -> Accuracy: 0.4798, MCC: -0.0070, F1: 0.3439

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66612 | val 0.93930
  Epoch 016 - train 0.64080 | val 0.92993
  Classification -> best τ=0.470 (val F1=0.1233)
  Directional -> Accuracy: 0.4949, MCC: 0.0640, F1: 0.6479

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65394 | val 0.76943
  Epoch 016 - train 0.63112 | val 0.90519
  Classification -> best τ=0.560 (val F1=0.0990)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.66781 | val 0.74451
  Epoch 016 - train 0.64591 | val 0.77221
  Classification -> best τ=0.525 (val F1=0.0758)
  Directional -> Accuracy: 0.5253, MCC: 0.0045, F1: 0.1754

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.63609 | val 1.12884
  Epoch 017 - train 0.61370 | val 1.14932
  Classification -> best τ=0.445 (val F1=0.1768)
  Directional -> Accuracy: 0.4394, MCC: -0.0140, F1: 0.1654

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.65526 | val 1.09254
  Epoch 016 - train 0.63117 | val 1.48317
  Classification -> best τ=0.495 (val F1=0.1390)
  Directional -> Accuracy: 0.4394, MCC: -0.0512, F1: 0.3353

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.64684 | val 0.72860
  Epoch 020 - train 0.61114 | val 0.95904
  Classification -> best τ=0.425 (val F1=0.2061)
  Directional -> Accuracy: 0.4588, MCC: 0.0426, F1: 0.5783

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.66361 | val 0.70716
  Epoch 020 - train 0.63451 | val 0.73441
  Classification -> best τ=0.575 (val F1=0.2032)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.67408 | val 0.72608
  Epoch 016 - train 0.65419 | val 0.72300
  Classification -> best τ=0.560 (val F1=0.1497)
  Directional -> Accuracy: 0.5103, MCC: 0.0431, F1: 0.0404

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65741 | val 0.77106
  Epoch 017 - train 0.63109 | val 0.80219
  Classification -> best τ=0.555 (val F1=0.1879)
  Directional -> Accuracy: 0.5152, MCC: 0.0405, F1: 0.5052

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.65601 | val 0.74955
  Epoch 016 - train 0.63631 | val 0.81322
  Classification -> best τ=0.520 (val F1=0.1800)
  Directional -> Accuracy: 0.5052, MCC: 0.0011, F1: 0.0204

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.68172 | val 0.77840
  Epoch 016 - train 0.67383 | val 0.78458
  Classification -> best τ=0.460 (val F1=0.0043)
  Directional -> Accuracy: 0.4848, MCC: -0.0689, F1: 0.6107

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66990 | val 0.73854
  Epoch 016 - train 0.63187 | val 0.94127
  Classification -> best τ=0.515 (val F1=0.0059)
  Directional -> Accuracy: 0.5051, MCC: -0.0130, F1: 0.6316

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.66203 | val 0.98539
  Epoch 016 - train 0.64880 | val 1.18016
  Classification -> best τ=0.525 (val F1=0.0883)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.67714 | val 0.71261
  Epoch 016 - train 0.65084 | val 0.72609
  Classification -> best τ=0.530 (val F1=0.0869)
  Directional -> Accuracy: 0.5354, MCC: 0.0912, F1: 0.4651

[75/88] Processing T...


[I 2026-02-26 06:18:28,135] Trial 50 finished with value: 0.13305300473003184 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.005611424959445788, 'weight_decay': 1.0434279012756543e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.6316138357466157, 'early_stopping_min_delta': 0.00591905689389728}. Best is trial 38 with value: 0.1560660322497637.

  Epoch 017 - train 0.64494 | val 0.99290
  Classification -> best τ=0.555 (val F1=0.0944)
  Directional -> Accuracy: 0.4949, MCC: -0.0319, F1: 0.1379

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.13305300473003184
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58755 | val 1.52819
  Epoch 016 - train 0.53714 | val 1.87549
  Classification -> best τ=0.360 (val F1=0.1675)
  Directional -> Accuracy: 0.4747, MCC: 0.0838, F1: 0.3067

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.55072 | val 8.36660
  Epoch 016 - train 0.47158 | val 11.90863
  Classification -> best τ=0.225 (val F1=0.1972)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60645 | val 1.03036
  Epoch 016 - train 0.53391 | val 1.54213
  Classification -> best τ=0.255 (val F1=0.2055)
  Directional -> Accuracy: 0.5489, MCC: -0.0312, F1: 0.6914

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.60749 | val 0.72640
  Epoch 016 - train 0.53433 | val 0.84446
  Classification -> best τ=0.565 (val F1=0.1003)
  Directional -> Accuracy: 0.4444, MCC: -0.0213, F1: 0.2029

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.52423 | val 3.24281
  Epoch 016 - train 0.48565 | val 3.89700
  Classification -> best τ=0.630 (val F1=0.1765)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58144 | val 1.39401
  Epoch 016 - train 0.50750 | val 2.26525
  Classification -> best τ=0.095 (val F1=0.1345)
  Directional -> Accuracy: 0.5303, MCC: -0.0444, F1: 0.6804

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61366 | val 3.38820
  Epoch 016 - train 0.57398 | val 4.21316
  Classification -> best τ=0.515 (val F1=0.1873)
  Directional -> Accuracy: 0.4495, MCC: 0.0637, F1: 0.0180

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57798 | val 1.10990
  Epoch 016 - train 0.51092 | val 1.24812
  Classification -> best τ=0.355 (val F1=0.3039)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51729 | val 5.14931
  Epoch 016 - train 0.44007 | val 6.61660
  Classification -> best τ=0.320 (val F1=0.1825)
  Directional -> Accuracy: 0.4196, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59062 | val 1.53836
  Epoch 016 - train 0.54039 | val 1.77888
  Classification -> best τ=0.650 (val F1=0.1299)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.58651 | val 1.07062
  Epoch 016 - train 0.51119 | val 1.32056
  Classification -> best τ=0.485 (val F1=0.2112)
  Directional -> Accuracy: 0.5000, MCC: 0.0141, F1: 0.4762

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.59750 | val 0.84335
  Epoch 016 - train 0.53467 | val 0.89872
  Classification -> best τ=0.645 (val F1=0.1201)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58958 | val 0.87987
  Epoch 020 - train 0.48181 | val 1.06834
  Classification -> best τ=0.795 (val F1=0.1533)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56404 | val 2.72679
  Epoch 016 - train 0.50194 | val 4.21671
  Classification -> best τ=0.670 (val F1=0.2433)
  Directional -> Accuracy: 0.5051, MCC: 0.0030, F1: 0.1404

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.61837 | val 2.18464
  Epoch 016 - train 0.57002 | val 2.97784
  Classification -> best τ=0.590 (val F1=0.0990)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.58745 | val 1.67773
  Epoch 016 - train 0.52272 | val 2.08320
  Classification -> best τ=0.350 (val F1=0.1613)
  Directional -> Accuracy: 0.4899, MCC: -0.0299, F1: 0.1920

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.60608 | val 0.80165
  Epoch 016 - train 0.53621 | val 0.92126
  Classification -> best τ=0.225 (val F1=0.1889)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.53786 | val 5.46738
  Epoch 016 - train 0.46874 | val 6.81448
  Classification -> best τ=0.870 (val F1=0.1653)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56325 | val 0.99870
  Epoch 016 - train 0.48659 | val 1.07729
  Classification -> best τ=0.375 (val F1=0.3060)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59311 | val 1.09869
  Epoch 016 - train 0.53271 | val 1.29713
  Classification -> best τ=0.795 (val F1=0.0980)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.58389 | val 1.10173
  Epoch 016 - train 0.52406 | val 1.31843
  Classification -> best τ=0.265 (val F1=0.1505)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.6576

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.61054 | val 2.72678
  Epoch 016 - train 0.54895 | val 5.21308
  Classification -> best τ=0.310 (val F1=0.1803)
  Directional -> Accuracy: 0.4343, MCC: -0.0805, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59024 | val 1.96447
  Epoch 016 - train 0.54017 | val 2.62816
  Classification -> best τ=0.550 (val F1=0.1156)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.61404 | val 1.16461
  Epoch 016 - train 0.54173 | val 1.71233
  Classification -> best τ=0.330 (val F1=0.1001)
  Directional -> Accuracy: 0.4545, MCC: 0.0517, F1: 0.5462

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57646 | val 1.31174
  Epoch 016 - train 0.49845 | val 1.82138
  Classification -> best τ=0.180 (val F1=0.1346)
  Directional -> Accuracy: 0.5505, MCC: 0.1056, F1: 0.5436

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61867 | val 0.88350
  Epoch 016 - train 0.54966 | val 0.98698
  Classification -> best τ=0.425 (val F1=0.1850)
  Directional -> Accuracy: 0.5152, MCC: 0.0727, F1: 0.0204

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58993 | val 1.59591
  Epoch 016 - train 0.52717 | val 2.00514
  Classification -> best τ=0.395 (val F1=0.1724)
  Directional -> Accuracy: 0.4545, MCC: -0.0187, F1: 0.0690

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.60355 | val 0.87341
  Epoch 016 - train 0.54784 | val 1.12656
  Classification -> best τ=0.295 (val F1=0.1098)
  Directional -> Accuracy: 0.5202, MCC: 0.0429, F1: 0.5887

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58807 | val 3.07092
  Epoch 016 - train 0.54434 | val 4.65942
  Classification -> best τ=0.710 (val F1=0.1366)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.59777 | val 1.52304
  Epoch 016 - train 0.53097 | val 2.61944
  Classification -> best τ=0.375 (val F1=0.1313)
  Directional -> Accuracy: 0.4545, MCC: -0.0211, F1: 0.0847

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.58645 | val 3.23530
  Epoch 016 - train 0.52271 | val 5.05111
  Classification -> best τ=0.135 (val F1=0.2003)
  Directional -> Accuracy: 0.5101, MCC: 0.0681, F1: 0.1709

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.59385 | val 2.38804
  Epoch 016 - train 0.55289 | val 3.01389
  Classification -> best τ=0.425 (val F1=0.0912)
  Directional -> Accuracy: 0.4545, MCC: -0.0298, F1: 0.2286

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.62490 | val 1.32514
  Epoch 016 - train 0.56146 | val 1.40753
  Classification -> best τ=0.565 (val F1=0.1568)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58616 | val 1.06489
  Epoch 016 - train 0.51768 | val 1.18460
  Classification -> best τ=0.395 (val F1=0.1382)
  Directional -> Accuracy: 0.5253, MCC: 0.0233, F1: 0.4198

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.52371 | val 1.97839
  Epoch 016 - train 0.45441 | val 2.04637
  Classification -> best τ=0.440 (val F1=0.1818)
  Directional -> Accuracy: 0.6000, MCC: 0.2119, F1: 0.6400

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56180 | val 1.15121
  Epoch 016 - train 0.49143 | val 1.71634
  Classification -> best τ=0.535 (val F1=0.2190)
  Directional -> Accuracy: 0.4242, MCC: 0.0605, F1: 0.0172

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59307 | val 1.24619
  Epoch 016 - train 0.53043 | val 1.72547
  Classification -> best τ=0.560 (val F1=0.2184)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.61428 | val 0.82730
  Epoch 016 - train 0.53712 | val 0.81850
  Classification -> best τ=0.415 (val F1=0.0749)
  Directional -> Accuracy: 0.4394, MCC: 0.0253, F1: 0.0348

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.58274 | val 2.56815
  Epoch 016 - train 0.51183 | val 3.69173
  Classification -> best τ=0.600 (val F1=0.0955)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.59294 | val 3.05014
  Epoch 016 - train 0.53214 | val 4.10319
  Classification -> best τ=0.875 (val F1=0.0783)
  Directional -> Accuracy: 0.4747, MCC: 0.0000, F1: 0.0000

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.57600 | val 1.93253
  Epoch 016 - train 0.51668 | val 3.40518
  Classification -> best τ=0.785 (val F1=0.1408)
  Directional -> Accuracy: 0.5051, MCC: 0.0351, F1: 0.3099

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57897 | val 1.43566
  Epoch 016 - train 0.51933 | val 2.18658
  Classification -> best τ=0.220 (val F1=0.1677)
  Directional -> Accuracy: 0.5354, MCC: -0.0314, F1: 0.6954

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59408 | val 1.28341
  Epoch 017 - train 0.54696 | val 1.37050
  Classification -> best τ=0.380 (val F1=0.1258)
  Directional -> Accuracy: 0.4848, MCC: -0.0448, F1: 0.5854

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58860 | val 1.55950
  Epoch 016 - train 0.51394 | val 2.32628
  Classification -> best τ=0.715 (val F1=0.1888)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56063 | val 3.35514
  Epoch 016 - train 0.49073 | val 4.36515
  Classification -> best τ=0.050 (val F1=0.0861)
  Directional -> Accuracy: 0.5152, MCC: 0.0027, F1: 0.6000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60237 | val 1.31592
  Epoch 016 - train 0.54824 | val 1.68532
  Classification -> best τ=0.710 (val F1=0.0416)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59404 | val 0.92744
  Epoch 016 - train 0.54447 | val 1.00892
  Classification -> best τ=0.625 (val F1=0.1409)
  Directional -> Accuracy: 0.4394, MCC: -0.0123, F1: 0.0177

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59120 | val 1.32283
  Epoch 016 - train 0.50361 | val 1.71202
  Classification -> best τ=0.280 (val F1=0.1194)
  Directional -> Accuracy: 0.4848, MCC: -0.0981, F1: 0.5887

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59183 | val 1.35772
  Epoch 016 - train 0.54310 | val 1.42868
  Classification -> best τ=0.480 (val F1=0.1609)
  Directional -> Accuracy: 0.5051, MCC: 0.0000, F1: 0.3951

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61365 | val 1.23124
  Epoch 016 - train 0.56099 | val 1.15033
  Classification -> best τ=0.570 (val F1=0.0671)
  Directional -> Accuracy: 0.4343, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58907 | val 1.05558
  Epoch 016 - train 0.52967 | val 1.49466
  Classification -> best τ=0.315 (val F1=0.1498)
  Directional -> Accuracy: 0.5657, MCC: 0.0856, F1: 0.6718

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58249 | val 1.16022
  Epoch 016 - train 0.50361 | val 1.51097
  Classification -> best τ=0.690 (val F1=0.1127)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58853 | val 1.24843
  Epoch 016 - train 0.51703 | val 1.82835
  Classification -> best τ=0.550 (val F1=0.0909)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.57444 | val 0.70311
  Epoch 016 - train 0.50656 | val 0.74294
  Classification -> best τ=0.445 (val F1=0.1171)
  Directional -> Accuracy: 0.5152, MCC: 0.0329, F1: 0.5556

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.56553 | val 1.94967
  Epoch 016 - train 0.50493 | val 2.54300
  Classification -> best τ=0.390 (val F1=0.1233)
  Directional -> Accuracy: 0.4949, MCC: -0.0021, F1: 0.6528

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.60584 | val 2.06520
  Epoch 016 - train 0.52319 | val 3.49132
  Classification -> best τ=0.240 (val F1=0.1498)
  Directional -> Accuracy: 0.5606, MCC: 0.1940, F1: 0.7010

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59241 | val 1.22945
  Epoch 016 - train 0.51701 | val 1.58268
  Classification -> best τ=0.425 (val F1=0.1007)
  Directional -> Accuracy: 0.4949, MCC: 0.0904, F1: 0.2424

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.61674 | val 0.77853
  Epoch 018 - train 0.50409 | val 1.83782
  Classification -> best τ=0.675 (val F1=0.0650)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56699 | val 1.31561
  Epoch 016 - train 0.48272 | val 1.64481
  Classification -> best τ=0.525 (val F1=0.2745)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58171 | val 1.84053
  Epoch 016 - train 0.50207 | val 2.94045
  Classification -> best τ=0.450 (val F1=0.1388)
  Directional -> Accuracy: 0.5051, MCC: 0.0569, F1: 0.3553

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58500 | val 1.88330
  Epoch 016 - train 0.51512 | val 2.46161
  Classification -> best τ=0.140 (val F1=0.1292)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.6485

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59928 | val 2.60203
  Epoch 016 - train 0.53361 | val 3.07314
  Classification -> best τ=0.125 (val F1=0.1642)
  Directional -> Accuracy: 0.5505, MCC: 0.0966, F1: 0.6044

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.58110 | val 0.91993
  Epoch 016 - train 0.50854 | val 0.89586
  Classification -> best τ=0.550 (val F1=0.1526)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.59780 | val 1.12922
  Epoch 020 - train 0.44892 | val 1.76144
  Classification -> best τ=0.755 (val F1=0.1634)
  Directional -> Accuracy: 0.4343, MCC: -0.0843, F1: 0.3563

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.57170 | val 1.87225
  Epoch 016 - train 0.51189 | val 2.56339
  Classification -> best τ=0.510 (val F1=0.1233)
  Directional -> Accuracy: 0.4293, MCC: 0.0858, F1: 0.0342

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.58093 | val 0.86403
  Epoch 016 - train 0.48397 | val 1.24429
  Classification -> best τ=0.425 (val F1=0.2382)
  Directional -> Accuracy: 0.4381, MCC: -0.0177, F1: 0.5622

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.57599 | val 1.04740
  Epoch 016 - train 0.51982 | val 1.26527
  Classification -> best τ=0.485 (val F1=0.1884)
  Directional -> Accuracy: 0.5253, MCC: 0.0821, F1: 0.4268

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.58206 | val 1.65912
  Epoch 016 - train 0.53236 | val 1.98246
  Classification -> best τ=0.715 (val F1=0.1175)
  Directional -> Accuracy: 0.5052, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58022 | val 2.11804
  Epoch 016 - train 0.50063 | val 3.17103
  Classification -> best τ=0.600 (val F1=0.2520)
  Directional -> Accuracy: 0.4798, MCC: -0.0127, F1: 0.5072

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.56999 | val 1.79598
  Epoch 016 - train 0.48298 | val 2.36633
  Classification -> best τ=0.415 (val F1=0.1116)
  Directional -> Accuracy: 0.5309, MCC: 0.0611, F1: 0.4972

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.62476 | val 1.39486
  Epoch 020 - train 0.48866 | val 0.84740
  Classification -> best τ=0.480 (val F1=0.1476)
  Directional -> Accuracy: 0.5253, MCC: 0.0303, F1: 0.6643

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.56212 | val 1.81429
  Epoch 017 - train 0.47330 | val 3.09211
  Classification -> best τ=0.475 (val F1=0.1598)
  Directional -> Accuracy: 0.4848, MCC: -0.0031, F1: 0.0192

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.59148 | val 3.25361
  Epoch 016 - train 0.53806 | val 3.37027
  Classification -> best τ=0.635 (val F1=0.0637)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.60290 | val 1.35959
  Epoch 016 - train 0.53804 | val 1.81587
  Classification -> best τ=0.265 (val F1=0.0813)
  Directional -> Accuracy: 0.5253, MCC: 0.0000, F1: 0.6887

[75/88] Processing T...


[I 2026-02-26 06:27:35,733] Trial 51 finished with value: 0.14927563053415102 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.002933757081167181, 'weight_decay': 3.5523762208356615e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.8036078846799228, 'early_stopping_min_delta': 0.005848792173896899}. Best is trial 38 with value: 0.1560660322497637.

  Epoch 016 - train 0.53821 | val 2.55645
  Classification -> best τ=0.455 (val F1=0.1274)
  Directional -> Accuracy: 0.5051, MCC: 0.0106, F1: 0.5149

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14927563053415102
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61052 | val 1.64450
  Epoch 016 - train 0.55913 | val 1.82947
  Classification -> best τ=0.695 (val F1=0.1525)
  Directional -> Accuracy: 0.4141, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.56096 | val 8.68584
  Epoch 016 - train 0.46739 | val 13.44523
  Classification -> best τ=0.690 (val F1=0.1207)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61004 | val 1.12145
  Epoch 016 - train 0.54319 | val 1.83881
  Classification -> best τ=0.215 (val F1=0.1330)
  Directional -> Accuracy: 0.5435, MCC: -0.0266, F1: 0.6794

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.66497 | val 0.72482
  Epoch 020 - train 0.51404 | val 1.61209
  Classification -> best τ=0.440 (val F1=0.1095)
  Directional -> Accuracy: 0.5960, MCC: 0.1482, F1: 0.7260

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.55258 | val 2.01784
  Epoch 016 - train 0.49773 | val 2.94985
  Classification -> best τ=0.525 (val F1=0.1208)
  Directional -> Accuracy: 0.4667, MCC: -0.0093, F1: 0.0345

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59931 | val 1.18997
  Epoch 016 - train 0.53223 | val 1.55779
  Classification -> best τ=0.645 (val F1=0.1305)
  Directional -> Accuracy: 0.4495, MCC: -0.0377, F1: 0.1805

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62839 | val 2.10718
  Epoch 018 - train 0.55037 | val 3.10765
  Classification -> best τ=0.360 (val F1=0.1547)
  Directional -> Accuracy: 0.5303, MCC: 0.0284, F1: 0.6109

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58908 | val 1.08852
  Epoch 016 - train 0.50326 | val 1.42062
  Classification -> best τ=0.260 (val F1=0.2632)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51075 | val 5.79685
  Epoch 016 - train 0.39768 | val 6.97753
  Classification -> best τ=0.420 (val F1=0.2031)
  Directional -> Accuracy: 0.4196, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61743 | val 2.09193
  Epoch 016 - train 0.52514 | val 2.61297
  Classification -> best τ=0.480 (val F1=0.1645)
  Directional -> Accuracy: 0.5505, MCC: 0.0619, F1: 0.1524

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.59146 | val 1.25816
  Epoch 016 - train 0.51196 | val 1.96510
  Classification -> best τ=0.535 (val F1=0.1530)
  Directional -> Accuracy: 0.4545, MCC: -0.0489, F1: 0.2174

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.62345 | val 0.80540
  Epoch 016 - train 0.55910 | val 0.86336
  Classification -> best τ=0.395 (val F1=0.2037)
  Directional -> Accuracy: 0.4495, MCC: 0.1382, F1: 0.0840

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63994 | val 0.99055
  Epoch 018 - train 0.50152 | val 1.03485
  Classification -> best τ=0.680 (val F1=0.1415)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58968 | val 1.58887
  Epoch 016 - train 0.48893 | val 2.96867
  Classification -> best τ=0.580 (val F1=0.1877)
  Directional -> Accuracy: 0.5303, MCC: 0.0666, F1: 0.3404

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.65710 | val 1.29909
  Epoch 018 - train 0.57516 | val 2.30027
  Classification -> best τ=0.410 (val F1=0.1361)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.60886 | val 1.81862
  Epoch 016 - train 0.53053 | val 2.66361
  Classification -> best τ=0.340 (val F1=0.1092)
  Directional -> Accuracy: 0.5101, MCC: 0.0230, F1: 0.6041

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.58617 | val 1.04534
  Epoch 016 - train 0.51432 | val 1.13147
  Classification -> best τ=0.320 (val F1=0.1652)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57162 | val 4.66705
  Epoch 016 - train 0.47356 | val 7.32315
  Classification -> best τ=0.610 (val F1=0.1294)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62211 | val 0.79313
  Epoch 016 - train 0.51429 | val 1.11785
  Classification -> best τ=0.330 (val F1=0.2989)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62648 | val 1.05852
  Epoch 016 - train 0.56459 | val 1.29181
  Classification -> best τ=0.690 (val F1=0.1203)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.63907 | val 0.88383
  Epoch 020 - train 0.45254 | val 1.80133
  Classification -> best τ=0.380 (val F1=0.1674)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.6576

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.64013 | val 1.69968
  Epoch 016 - train 0.57379 | val 4.23781
  Classification -> best τ=0.190 (val F1=0.1628)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63075 | val 0.88039
  Epoch 018 - train 0.49942 | val 1.22030
  Classification -> best τ=0.590 (val F1=0.1315)
  Directional -> Accuracy: 0.5101, MCC: 0.1071, F1: 0.2920

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.61656 | val 1.88837
  Epoch 016 - train 0.54355 | val 2.71345
  Classification -> best τ=0.140 (val F1=0.1094)
  Directional -> Accuracy: 0.4242, MCC: 0.0392, F1: 0.5581

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58011 | val 2.29056
  Epoch 016 - train 0.50250 | val 3.67300
  Classification -> best τ=0.140 (val F1=0.1413)
  Directional -> Accuracy: 0.5556, MCC: 0.1029, F1: 0.6071

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62392 | val 0.96776
  Epoch 018 - train 0.54336 | val 1.57304
  Classification -> best τ=0.460 (val F1=0.1742)
  Directional -> Accuracy: 0.5253, MCC: 0.0998, F1: 0.0784

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60821 | val 1.04157
  Epoch 016 - train 0.53452 | val 1.57863
  Classification -> best τ=0.535 (val F1=0.1614)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.64526 | val 0.99471
  Epoch 020 - train 0.52648 | val 2.04474
  Classification -> best τ=0.610 (val F1=0.1068)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60834 | val 3.25260
  Epoch 016 - train 0.54897 | val 6.77181
  Classification -> best τ=0.855 (val F1=0.1859)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.67191 | val 1.20345
  Epoch 020 - train 0.52435 | val 5.84769
  Classification -> best τ=0.125 (val F1=0.1073)
  Directional -> Accuracy: 0.5505, MCC: 0.0500, F1: 0.6833

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.62339 | val 3.22126
  Epoch 016 - train 0.53164 | val 5.53218
  Classification -> best τ=0.165 (val F1=0.1345)
  Directional -> Accuracy: 0.5455, MCC: 0.0901, F1: 0.6218

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62723 | val 1.56198
  Epoch 016 - train 0.53803 | val 2.10673
  Classification -> best τ=0.380 (val F1=0.1452)
  Directional -> Accuracy: 0.5152, MCC: 0.0183, F1: 0.5636

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.64593 | val 1.04752
  Epoch 016 - train 0.56062 | val 1.39254
  Classification -> best τ=0.590 (val F1=0.1351)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58462 | val 1.33418
  Epoch 016 - train 0.50250 | val 1.49567
  Classification -> best τ=0.205 (val F1=0.1253)
  Directional -> Accuracy: 0.4495, MCC: 0.0061, F1: 0.6093

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.52490 | val 2.24427
  Epoch 016 - train 0.42616 | val 3.05435
  Classification -> best τ=0.380 (val F1=0.1974)
  Directional -> Accuracy: 0.6000, MCC: 0.2460, F1: 0.6786

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60913 | val 1.00917
  Epoch 019 - train 0.48131 | val 2.04477
  Classification -> best τ=0.685 (val F1=0.2099)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62216 | val 1.19139
  Epoch 016 - train 0.55978 | val 2.61623
  Classification -> best τ=0.515 (val F1=0.2322)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.61706 | val 0.84956
  Epoch 016 - train 0.56013 | val 1.08366
  Classification -> best τ=0.295 (val F1=0.1605)
  Directional -> Accuracy: 0.5657, MCC: 0.0582, F1: 0.6906

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.62705 | val 2.11644
  Epoch 016 - train 0.55921 | val 2.94906
  Classification -> best τ=0.780 (val F1=0.0885)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.64215 | val 1.20570
  Epoch 019 - train 0.52341 | val 1.89628
  Classification -> best τ=0.215 (val F1=0.1190)
  Directional -> Accuracy: 0.5354, MCC: 0.0566, F1: 0.6134

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.60099 | val 2.71529
  Epoch 016 - train 0.54277 | val 5.13440
  Classification -> best τ=0.650 (val F1=0.1390)
  Directional -> Accuracy: 0.4747, MCC: -0.0655, F1: 0.5593

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60701 | val 1.69845
  Epoch 016 - train 0.51936 | val 2.00651
  Classification -> best τ=0.220 (val F1=0.1177)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.7016

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62287 | val 0.92889
  Epoch 016 - train 0.56038 | val 0.94411
  Classification -> best τ=0.370 (val F1=0.1210)
  Directional -> Accuracy: 0.4848, MCC: -0.0271, F1: 0.4396

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59963 | val 1.74756
  Epoch 016 - train 0.53079 | val 2.78262
  Classification -> best τ=0.610 (val F1=0.1912)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57480 | val 4.27519
  Epoch 016 - train 0.47908 | val 7.06608
  Classification -> best τ=0.065 (val F1=0.0919)
  Directional -> Accuracy: 0.5051, MCC: -0.0013, F1: 0.5545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62976 | val 1.36818
  Epoch 016 - train 0.57664 | val 2.19219
  Classification -> best τ=0.645 (val F1=0.0932)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62774 | val 0.86031
  Epoch 017 - train 0.53673 | val 1.22589
  Classification -> best τ=0.380 (val F1=0.1652)
  Directional -> Accuracy: 0.5505, MCC: 0.0337, F1: 0.6716

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63190 | val 1.10541
  Epoch 016 - train 0.57035 | val 1.37884
  Classification -> best τ=0.435 (val F1=0.0475)
  Directional -> Accuracy: 0.3990, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60785 | val 0.85099
  Epoch 020 - train 0.51327 | val 0.72902
  Classification -> best τ=0.555 (val F1=0.1201)
  Directional -> Accuracy: 0.5051, MCC: -0.0197, F1: 0.1833

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64855 | val 0.98737
  Epoch 019 - train 0.52109 | val 0.96030
  Classification -> best τ=0.655 (val F1=0.0951)
  Directional -> Accuracy: 0.4343, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62094 | val 0.75750
  Epoch 016 - train 0.56308 | val 0.79784
  Classification -> best τ=0.355 (val F1=0.1498)
  Directional -> Accuracy: 0.4848, MCC: -0.0504, F1: 0.5487

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57953 | val 0.94167
  Epoch 016 - train 0.51830 | val 0.96498
  Classification -> best τ=0.470 (val F1=0.1625)
  Directional -> Accuracy: 0.5051, MCC: 0.0571, F1: 0.0755

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58730 | val 1.54995
  Epoch 016 - train 0.50841 | val 2.80201
  Classification -> best τ=0.355 (val F1=0.1351)
  Directional -> Accuracy: 0.4949, MCC: 0.0067, F1: 0.2188

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.62621 | val 0.70292
  Epoch 017 - train 0.54126 | val 0.91284
  Classification -> best τ=0.540 (val F1=0.1085)
  Directional -> Accuracy: 0.4091, MCC: -0.0416, F1: 0.1333

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.59918 | val 1.50116
  Epoch 016 - train 0.50019 | val 2.03490
  Classification -> best τ=0.345 (val F1=0.1182)
  Directional -> Accuracy: 0.4899, MCC: -0.0338, F1: 0.6529

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.61991 | val 1.15990
  Epoch 016 - train 0.54916 | val 2.06717
  Classification -> best τ=0.805 (val F1=0.1266)
  Directional -> Accuracy: 0.4798, MCC: -0.0041, F1: 0.0190

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61550 | val 1.18652
  Epoch 017 - train 0.51188 | val 1.76825
  Classification -> best τ=0.195 (val F1=0.1020)
  Directional -> Accuracy: 0.5707, MCC: 0.1158, F1: 0.7038

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.62504 | val 0.72242
  Epoch 016 - train 0.53568 | val 1.01942
  Classification -> best τ=0.705 (val F1=0.0922)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58657 | val 1.38079
  Epoch 016 - train 0.47574 | val 2.20864
  Classification -> best τ=0.570 (val F1=0.2451)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61179 | val 1.23631
  Epoch 016 - train 0.51456 | val 1.76535
  Classification -> best τ=0.385 (val F1=0.1925)
  Directional -> Accuracy: 0.4848, MCC: 0.0294, F1: 0.2388

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61436 | val 1.83191
  Epoch 017 - train 0.52483 | val 2.64061
  Classification -> best τ=0.100 (val F1=0.0950)
  Directional -> Accuracy: 0.4899, MCC: 0.0970, F1: 0.6529

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61400 | val 2.90010
  Epoch 016 - train 0.54999 | val 4.34091
  Classification -> best τ=0.235 (val F1=0.1516)
  Directional -> Accuracy: 0.4798, MCC: -0.0451, F1: 0.0190

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.60787 | val 0.85845
  Epoch 016 - train 0.52740 | val 1.03255
  Classification -> best τ=0.350 (val F1=0.1208)
  Directional -> Accuracy: 0.5000, MCC: -0.0172, F1: 0.4000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.62619 | val 5.49047
  Epoch 020 - train 0.44486 | val 23.71712
  Classification -> best τ=0.715 (val F1=0.1291)
  Directional -> Accuracy: 0.4293, MCC: -0.0144, F1: 0.0174

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.59980 | val 1.80965
  Epoch 016 - train 0.49419 | val 2.57958
  Classification -> best τ=0.105 (val F1=0.1032)
  Directional -> Accuracy: 0.5455, MCC: 0.0216, F1: 0.6512

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.63398 | val 0.78973
  Epoch 019 - train 0.45035 | val 2.69503
  Classification -> best τ=0.215 (val F1=0.2514)
  Directional -> Accuracy: 0.4536, MCC: 0.0058, F1: 0.5583

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.58806 | val 0.94982
  Epoch 016 - train 0.53588 | val 1.35218
  Classification -> best τ=0.580 (val F1=0.2335)
  Directional -> Accuracy: 0.5101, MCC: 0.1542, F1: 0.1709

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.57991 | val 1.37359
  Epoch 016 - train 0.52519 | val 1.47317
  Classification -> best τ=0.610 (val F1=0.0785)
  Directional -> Accuracy: 0.5052, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59690 | val 2.34370
  Epoch 016 - train 0.51251 | val 3.68724
  Classification -> best τ=0.615 (val F1=0.2224)
  Directional -> Accuracy: 0.4747, MCC: -0.0292, F1: 0.4902

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.60705 | val 1.24025
  Epoch 016 - train 0.47568 | val 1.79080
  Classification -> best τ=0.345 (val F1=0.1634)
  Directional -> Accuracy: 0.5052, MCC: 0.0104, F1: 0.5052

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.68098 | val 0.85586
  Epoch 018 - train 0.50945 | val 2.08480
  Classification -> best τ=0.555 (val F1=0.1609)
  Directional -> Accuracy: 0.5101, MCC: 0.0314, F1: 0.4520

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.60932 | val 1.84108
  Epoch 018 - train 0.46139 | val 3.70935
  Classification -> best τ=0.400 (val F1=0.1260)
  Directional -> Accuracy: 0.4899, MCC: 0.0073, F1: 0.1653

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.64197 | val 4.13986
  Epoch 017 - train 0.55149 | val 7.01160
  Classification -> best τ=0.320 (val F1=0.0637)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.60942 | val 1.69766
  Epoch 016 - train 0.54287 | val 2.62956
  Classification -> best τ=0.390 (val F1=0.0980)
  Directional -> Accuracy: 0.5000, MCC: 0.0062, F1: 0.4817

[75/88] Processing T...


[I 2026-02-26 06:36:55,443] Trial 52 finished with value: 0.14666052501335808 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.006064535382140299, 'weight_decay': 1.5536319271305898e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.5128532105426615, 'early_stopping_min_delta': 0.00663045999514654}. Best is trial 38 with value: 0.1560660322497637.

  Epoch 016 - train 0.54585 | val 2.87728
  Classification -> best τ=0.435 (val F1=0.1471)
  Directional -> Accuracy: 0.5455, MCC: 0.0906, F1: 0.5361

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14666052501335808
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62658 | val 1.17581
  Epoch 016 - train 0.57161 | val 1.63852
  Classification -> best τ=0.265 (val F1=0.1510)
  Directional -> Accuracy: 0.4343, MCC: 0.0096, F1: 0.1765

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.58170 | val 8.47768
  Epoch 016 - train 0.48654 | val 13.33837
  Classification -> best τ=0.510 (val F1=0.1551)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62968 | val 1.25081
  Epoch 016 - train 0.57828 | val 1.25918
  Classification -> best τ=0.350 (val F1=0.2283)
  Directional -> Accuracy: 0.5598, MCC: 0.0395, F1: 0.6773

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.64292 | val 0.83162
  Epoch 016 - train 0.59319 | val 0.83074
  Classification -> best τ=0.480 (val F1=0.0773)
  Directional -> Accuracy: 0.5657, MCC: 0.0000, F1: 0.7226

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.58442 | val 2.09789
  Epoch 016 - train 0.52757 | val 3.30290
  Classification -> best τ=0.490 (val F1=0.0953)
  Directional -> Accuracy: 0.4857, MCC: 0.0248, F1: 0.2500

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62939 | val 1.26871
  Epoch 019 - train 0.51273 | val 2.16101
  Classification -> best τ=0.710 (val F1=0.1638)
  Directional -> Accuracy: 0.4495, MCC: -0.0280, F1: 0.1138

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63192 | val 3.55015
  Epoch 016 - train 0.59659 | val 4.13592
  Classification -> best τ=0.435 (val F1=0.1725)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60380 | val 1.01788
  Epoch 016 - train 0.55317 | val 0.91335
  Classification -> best τ=0.130 (val F1=0.3136)
  Directional -> Accuracy: 0.5152, MCC: 0.0787, F1: 0.5200

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55459 | val 3.22817
  Epoch 016 - train 0.49232 | val 4.60368
  Classification -> best τ=0.435 (val F1=0.1825)
  Directional -> Accuracy: 0.4196, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61724 | val 1.43930
  Epoch 017 - train 0.55980 | val 2.15663
  Classification -> best τ=0.710 (val F1=0.1083)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.61375 | val 0.83993
  Epoch 016 - train 0.54692 | val 1.24623
  Classification -> best τ=0.400 (val F1=0.1774)
  Directional -> Accuracy: 0.4899, MCC: 0.0019, F1: 0.4358

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.62007 | val 0.84279
  Epoch 016 - train 0.57691 | val 0.85420
  Classification -> best τ=0.640 (val F1=0.1536)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.63693 | val 0.76172
  Epoch 020 - train 0.52727 | val 0.81163
  Classification -> best τ=0.545 (val F1=0.1221)
  Directional -> Accuracy: 0.4949, MCC: 0.0714, F1: 0.3506

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60204 | val 1.41676
  Epoch 016 - train 0.53675 | val 1.67381
  Classification -> best τ=0.720 (val F1=0.2387)
  Directional -> Accuracy: 0.5051, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.64560 | val 1.87759
  Epoch 016 - train 0.61281 | val 2.60929
  Classification -> best τ=0.445 (val F1=0.1423)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.60334 | val 2.68827
  Epoch 016 - train 0.51872 | val 2.72762
  Classification -> best τ=0.055 (val F1=0.1600)
  Directional -> Accuracy: 0.5051, MCC: 0.0105, F1: 0.5664

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.61356 | val 0.85044
  Epoch 016 - train 0.55708 | val 0.92574
  Classification -> best τ=0.300 (val F1=0.1686)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56154 | val 2.85566
  Epoch 016 - train 0.48362 | val 4.94324
  Classification -> best τ=0.810 (val F1=0.1854)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64137 | val 0.91950
  Epoch 019 - train 0.49223 | val 1.29378
  Classification -> best τ=0.500 (val F1=0.2909)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62309 | val 0.94895
  Epoch 016 - train 0.56610 | val 1.08673
  Classification -> best τ=0.610 (val F1=0.1541)
  Directional -> Accuracy: 0.4596, MCC: -0.0287, F1: 0.1705

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.62841 | val 0.90260
  Epoch 016 - train 0.54539 | val 1.40678
  Classification -> best τ=0.720 (val F1=0.1603)
  Directional -> Accuracy: 0.5404, MCC: 0.0789, F1: 0.5027

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.64672 | val 2.14028
  Epoch 016 - train 0.57968 | val 2.51014
  Classification -> best τ=0.210 (val F1=0.1892)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64807 | val 0.73152
  Epoch 020 - train 0.52781 | val 1.47419
  Classification -> best τ=0.380 (val F1=0.1486)
  Directional -> Accuracy: 0.5455, MCC: 0.0738, F1: 0.6087

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.63626 | val 1.27128
  Epoch 016 - train 0.56260 | val 1.77167
  Classification -> best τ=0.245 (val F1=0.1282)
  Directional -> Accuracy: 0.4293, MCC: 0.0342, F1: 0.5534

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58625 | val 1.14643
  Epoch 016 - train 0.53777 | val 1.39626
  Classification -> best τ=0.810 (val F1=0.1132)
  Directional -> Accuracy: 0.4747, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63223 | val 0.84065
  Epoch 020 - train 0.55983 | val 1.03568
  Classification -> best τ=0.320 (val F1=0.2101)
  Directional -> Accuracy: 0.5051, MCC: -0.0289, F1: 0.0392

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61764 | val 0.97717
  Epoch 016 - train 0.57294 | val 1.51881
  Classification -> best τ=0.510 (val F1=0.1716)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.63205 | val 1.04063
  Epoch 016 - train 0.57003 | val 1.12507
  Classification -> best τ=0.510 (val F1=0.1485)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2979

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62680 | val 1.96523
  Epoch 016 - train 0.56707 | val 4.14896
  Classification -> best τ=0.605 (val F1=0.1107)
  Directional -> Accuracy: 0.4949, MCC: 0.0698, F1: 0.0196

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.62039 | val 1.38797
  Epoch 016 - train 0.56174 | val 3.57636
  Classification -> best τ=0.515 (val F1=0.1459)
  Directional -> Accuracy: 0.4495, MCC: -0.0443, F1: 0.0840

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.61841 | val 4.44188
  Epoch 016 - train 0.56179 | val 6.20057
  Classification -> best τ=0.095 (val F1=0.1499)
  Directional -> Accuracy: 0.5101, MCC: 0.0572, F1: 0.2114

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63526 | val 1.59711
  Epoch 016 - train 0.57004 | val 2.01033
  Classification -> best τ=0.500 (val F1=0.0988)
  Directional -> Accuracy: 0.4444, MCC: -0.0469, F1: 0.0517

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.66403 | val 1.00572
  Epoch 016 - train 0.62638 | val 1.22234
  Classification -> best τ=0.560 (val F1=0.1664)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61328 | val 1.01265
  Epoch 016 - train 0.55179 | val 0.98869
  Classification -> best τ=0.430 (val F1=0.1022)
  Directional -> Accuracy: 0.5455, MCC: 0.0634, F1: 0.4375

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.55885 | val 2.39699
  Epoch 016 - train 0.46647 | val 2.77270
  Classification -> best τ=0.445 (val F1=0.1974)
  Directional -> Accuracy: 0.6000, MCC: 0.2310, F1: 0.6667

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60036 | val 0.71904
  Epoch 017 - train 0.51652 | val 0.93479
  Classification -> best τ=0.580 (val F1=0.2125)
  Directional -> Accuracy: 0.4192, MCC: -0.0165, F1: 0.0171

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63353 | val 0.96594
  Epoch 016 - train 0.58060 | val 1.28550
  Classification -> best τ=0.700 (val F1=0.1536)
  Directional -> Accuracy: 0.4697, MCC: -0.0087, F1: 0.0367

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.63515 | val 0.83916
  Epoch 020 - train 0.57366 | val 1.03719
  Classification -> best τ=0.300 (val F1=0.1740)
  Directional -> Accuracy: 0.5606, MCC: 0.0619, F1: 0.6692

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.64172 | val 1.94321
  Epoch 016 - train 0.56591 | val 2.49554
  Classification -> best τ=0.505 (val F1=0.1064)
  Directional -> Accuracy: 0.4495, MCC: -0.0447, F1: 0.0992

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.64779 | val 2.02677
  Epoch 016 - train 0.58022 | val 2.34840
  Classification -> best τ=0.360 (val F1=0.1518)
  Directional -> Accuracy: 0.5101, MCC: 0.0172, F1: 0.5359

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.61390 | val 2.36217
  Epoch 016 - train 0.55578 | val 2.90806
  Classification -> best τ=0.870 (val F1=0.1407)
  Directional -> Accuracy: 0.4848, MCC: -0.0054, F1: 0.0556

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60816 | val 1.39138
  Epoch 016 - train 0.55516 | val 2.44893
  Classification -> best τ=0.180 (val F1=0.1673)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.7016

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63222 | val 1.13267
  Epoch 016 - train 0.57083 | val 1.30805
  Classification -> best τ=0.590 (val F1=0.1342)
  Directional -> Accuracy: 0.4848, MCC: -0.0229, F1: 0.1905

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62150 | val 1.19117
  Epoch 016 - train 0.57722 | val 2.07876
  Classification -> best τ=0.660 (val F1=0.1912)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57649 | val 3.87413
  Epoch 016 - train 0.49559 | val 5.66763
  Classification -> best τ=0.180 (val F1=0.1586)
  Directional -> Accuracy: 0.5404, MCC: 0.0433, F1: 0.6513

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63857 | val 1.25402
  Epoch 016 - train 0.59155 | val 1.41572
  Classification -> best τ=0.110 (val F1=0.0143)
  Directional -> Accuracy: 0.5859, MCC: -0.0593, F1: 0.7389

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66240 | val 0.79859
  Epoch 019 - train 0.57045 | val 0.91260
  Classification -> best τ=0.495 (val F1=0.1517)
  Directional -> Accuracy: 0.4495, MCC: 0.0378, F1: 0.0684

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64604 | val 1.11470
  Epoch 018 - train 0.52393 | val 2.22102
  Classification -> best τ=0.470 (val F1=0.0933)
  Directional -> Accuracy: 0.3990, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62401 | val 1.24604
  Epoch 016 - train 0.58924 | val 1.37234
  Classification -> best τ=0.510 (val F1=0.1708)
  Directional -> Accuracy: 0.5253, MCC: 0.0432, F1: 0.4268

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63021 | val 1.01961
  Epoch 016 - train 0.59293 | val 0.93244
  Classification -> best τ=0.355 (val F1=0.1233)
  Directional -> Accuracy: 0.4848, MCC: -0.0186, F1: 0.4950

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62570 | val 0.84185
  Epoch 016 - train 0.59197 | val 0.95408
  Classification -> best τ=0.325 (val F1=0.1383)
  Directional -> Accuracy: 0.5606, MCC: 0.0550, F1: 0.6969

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59532 | val 1.04594
  Epoch 016 - train 0.53228 | val 1.56777
  Classification -> best τ=0.325 (val F1=0.1187)
  Directional -> Accuracy: 0.5000, MCC: 0.0053, F1: 0.3529

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.60421 | val 0.88474
  Epoch 016 - train 0.53695 | val 1.75540
  Classification -> best τ=0.225 (val F1=0.1095)
  Directional -> Accuracy: 0.5101, MCC: 0.0000, F1: 0.6756

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.63886 | val 0.72023
  Epoch 016 - train 0.59712 | val 0.70288
  Classification -> best τ=0.475 (val F1=0.1326)
  Directional -> Accuracy: 0.5707, MCC: -0.0809, F1: 0.7231

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.62688 | val 1.08309
  Epoch 016 - train 0.55754 | val 1.49942
  Classification -> best τ=0.430 (val F1=0.1356)
  Directional -> Accuracy: 0.4646, MCC: -0.0833, F1: 0.5923

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.62425 | val 1.11522
  Epoch 016 - train 0.58196 | val 1.52256
  Classification -> best τ=0.410 (val F1=0.1143)
  Directional -> Accuracy: 0.5455, MCC: 0.1128, F1: 0.6875

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64749 | val 0.96722
  Epoch 019 - train 0.52150 | val 1.22989
  Classification -> best τ=0.310 (val F1=0.1471)
  Directional -> Accuracy: 0.5202, MCC: 0.0970, F1: 0.4025

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.66235 | val 0.85154
  Epoch 018 - train 0.55963 | val 1.57840
  Classification -> best τ=0.630 (val F1=0.1132)
  Directional -> Accuracy: 0.4545, MCC: -0.0861, F1: 0.0526

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63121 | val 1.23113
  Epoch 016 - train 0.55405 | val 1.28575
  Classification -> best τ=0.440 (val F1=0.2342)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62339 | val 1.81598
  Epoch 016 - train 0.56638 | val 2.98561
  Classification -> best τ=0.380 (val F1=0.1879)
  Directional -> Accuracy: 0.5051, MCC: 0.0830, F1: 0.2794

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61429 | val 1.43697
  Epoch 016 - train 0.55953 | val 1.83171
  Classification -> best τ=0.665 (val F1=0.1457)
  Directional -> Accuracy: 0.5152, MCC: -0.0364, F1: 0.0204

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62995 | val 3.15159
  Epoch 016 - train 0.55509 | val 3.96240
  Classification -> best τ=0.095 (val F1=0.1811)
  Directional -> Accuracy: 0.4747, MCC: -0.0501, F1: 0.0877

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.61885 | val 0.75931
  Epoch 016 - train 0.51784 | val 0.90432
  Classification -> best τ=0.585 (val F1=0.1526)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.64182 | val 2.88571
  Epoch 020 - train 0.52594 | val 7.38588
  Classification -> best τ=0.290 (val F1=0.1739)
  Directional -> Accuracy: 0.4848, MCC: 0.0564, F1: 0.3544

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.61447 | val 1.18003
  Epoch 016 - train 0.54261 | val 1.61254
  Classification -> best τ=0.545 (val F1=0.1239)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.59794 | val 1.15338
  Epoch 016 - train 0.51519 | val 1.16707
  Classification -> best τ=0.730 (val F1=0.1851)
  Directional -> Accuracy: 0.5206, MCC: 0.0129, F1: 0.4224

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.62893 | val 0.95007
  Epoch 018 - train 0.52323 | val 1.17604
  Classification -> best τ=0.620 (val F1=0.2528)
  Directional -> Accuracy: 0.5202, MCC: 0.1476, F1: 0.2400

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.61868 | val 1.30434
  Epoch 016 - train 0.55814 | val 1.59335
  Classification -> best τ=0.560 (val F1=0.1051)
  Directional -> Accuracy: 0.5258, MCC: 0.1209, F1: 0.0980

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59723 | val 1.17512
  Epoch 016 - train 0.53444 | val 2.00180
  Classification -> best τ=0.560 (val F1=0.2535)
  Directional -> Accuracy: 0.5000, MCC: 0.0239, F1: 0.5171

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.61718 | val 1.03813
  Epoch 016 - train 0.53747 | val 1.31279
  Classification -> best τ=0.290 (val F1=0.1529)
  Directional -> Accuracy: 0.5155, MCC: 0.0348, F1: 0.5688

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.65126 | val 0.91987
  Epoch 016 - train 0.59612 | val 1.33029
  Classification -> best τ=0.575 (val F1=0.1811)
  Directional -> Accuracy: 0.5101, MCC: 0.0314, F1: 0.4520

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.59790 | val 2.64446
  Epoch 016 - train 0.54104 | val 3.09393
  Classification -> best τ=0.300 (val F1=0.1728)
  Directional -> Accuracy: 0.5152, MCC: 0.0214, F1: 0.5897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.63507 | val 3.53114
  Epoch 016 - train 0.58235 | val 4.85995
  Classification -> best τ=0.820 (val F1=0.0988)
  Directional -> Accuracy: 0.6010, MCC: 0.1873, F1: 0.5269

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.63058 | val 1.00230
  Epoch 016 - train 0.56168 | val 1.28225
  Classification -> best τ=0.265 (val F1=0.1153)
  Directional -> Accuracy: 0.5253, MCC: 0.0150, F1: 0.6713

[75/88] Processing T...


[I 2026-02-26 06:46:07,723] Trial 53 finished with value: 0.15712278789285605 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.004320436859666063, 'weight_decay': 3.107419577024999e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.6668414525364756, 'early_stopping_min_delta': 0.005272858631704909}. Best is trial 53 with value: 0.15712278789285605.

  Epoch 016 - train 0.56415 | val 3.06230
  Classification -> best τ=0.410 (val F1=0.1859)
  Directional -> Accuracy: 0.4949, MCC: -0.0063, F1: 0.5833

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.15712278789285605
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66404 | val 1.18399
  Epoch 016 - train 0.63731 | val 1.29432
  Classification -> best τ=0.250 (val F1=0.1623)
  Directional -> Accuracy: 0.4697, MCC: 0.0058, F1: 0.4068

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.61958 | val 5.82465
  Epoch 016 - train 0.56203 | val 9.43943
  Classification -> best τ=0.495 (val F1=0.1693)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66315 | val 0.89926
  Epoch 016 - train 0.61132 | val 1.36531
  Classification -> best τ=0.325 (val F1=0.1727)
  Directional -> Accuracy: 0.5870, MCC: 0.0984, F1: 0.7343

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.67647 | val 0.70758
  Epoch 016 - train 0.63781 | val 0.71225
  Classification -> best τ=0.655 (val F1=0.1378)
  Directional -> Accuracy: 0.4394, MCC: 0.0253, F1: 0.0348

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.63425 | val 1.12889
  Epoch 016 - train 0.56461 | val 1.37382
  Classification -> best τ=0.520 (val F1=0.1765)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63537 | val 0.83019
  Epoch 018 - train 0.57292 | val 1.12708
  Classification -> best τ=0.855 (val F1=0.1179)
  Directional -> Accuracy: 0.4495, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66324 | val 1.78803
  Epoch 016 - train 0.61805 | val 3.05012
  Classification -> best τ=0.520 (val F1=0.1508)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66736 | val 0.75327
  Epoch 016 - train 0.64181 | val 0.82769
  Classification -> best τ=0.170 (val F1=0.3248)
  Directional -> Accuracy: 0.5303, MCC: 0.0553, F1: 0.5830

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59921 | val 5.75404
  Epoch 016 - train 0.53541 | val 6.67644
  Classification -> best τ=0.365 (val F1=0.1825)
  Directional -> Accuracy: 0.4196, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63433 | val 1.28908
  Epoch 016 - train 0.61853 | val 1.58030
  Classification -> best τ=0.615 (val F1=0.1344)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.61045 | val 0.91464
  Epoch 016 - train 0.57065 | val 0.97872
  Classification -> best τ=0.620 (val F1=0.1421)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.67659 | val 0.85086
  Epoch 018 - train 0.58534 | val 1.02227
  Classification -> best τ=0.435 (val F1=0.1510)
  Directional -> Accuracy: 0.5051, MCC: 0.1397, F1: 0.3467

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61534 | val 0.72591
  Epoch 016 - train 0.60044 | val 0.77522
  Classification -> best τ=0.470 (val F1=0.1598)
  Directional -> Accuracy: 0.4848, MCC: -0.0158, F1: 0.4848

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.62726 | val 1.54798
  Epoch 016 - train 0.56553 | val 2.32953
  Classification -> best τ=0.630 (val F1=0.2302)
  Directional -> Accuracy: 0.5051, MCC: 0.0057, F1: 0.3288

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.68407 | val 0.74859
  Epoch 019 - train 0.65050 | val 0.90919
  Classification -> best τ=0.515 (val F1=0.1009)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.64103 | val 1.46615
  Epoch 016 - train 0.59355 | val 1.85278
  Classification -> best τ=0.500 (val F1=0.1421)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.68202 | val 0.81088
  Epoch 019 - train 0.58694 | val 0.91985
  Classification -> best τ=0.380 (val F1=0.1375)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61645 | val 3.21356
  Epoch 016 - train 0.52659 | val 4.92552
  Classification -> best τ=0.910 (val F1=0.1436)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65674 | val 0.80769
  Epoch 018 - train 0.56376 | val 0.98369
  Classification -> best τ=0.465 (val F1=0.2507)
  Directional -> Accuracy: 0.5051, MCC: 0.0571, F1: 0.0755

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65066 | val 0.86854
  Epoch 020 - train 0.60232 | val 1.05995
  Classification -> best τ=0.800 (val F1=0.1561)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.65182 | val 0.82378
  Epoch 016 - train 0.62570 | val 0.98503
  Classification -> best τ=0.280 (val F1=0.0863)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.6576

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.67158 | val 1.89217
  Epoch 016 - train 0.62281 | val 2.94729
  Classification -> best τ=0.265 (val F1=0.1899)
  Directional -> Accuracy: 0.4495, MCC: 0.0011, F1: 0.1417

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65385 | val 0.77581
  Epoch 016 - train 0.60055 | val 0.98616
  Classification -> best τ=0.280 (val F1=0.0765)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.7016

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.65982 | val 1.13909
  Epoch 016 - train 0.62078 | val 1.74458
  Classification -> best τ=0.155 (val F1=0.1762)
  Directional -> Accuracy: 0.4242, MCC: 0.1129, F1: 0.5746

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63045 | val 1.23387
  Epoch 016 - train 0.56502 | val 1.69692
  Classification -> best τ=0.450 (val F1=0.1414)
  Directional -> Accuracy: 0.5101, MCC: 0.0299, F1: 0.4757

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68542 | val 0.77915
  Epoch 020 - train 0.61753 | val 0.86896
  Classification -> best τ=0.470 (val F1=0.1870)
  Directional -> Accuracy: 0.5455, MCC: 0.1111, F1: 0.2742

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64674 | val 1.00099
  Epoch 016 - train 0.61967 | val 1.28037
  Classification -> best τ=0.395 (val F1=0.1342)
  Directional -> Accuracy: 0.5354, MCC: 0.0430, F1: 0.6167

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.68551 | val 0.72340
  Epoch 020 - train 0.62851 | val 0.93062
  Classification -> best τ=0.395 (val F1=0.1515)
  Directional -> Accuracy: 0.5051, MCC: 0.0204, F1: 0.6549

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64829 | val 1.48077
  Epoch 016 - train 0.62628 | val 2.55245
  Classification -> best τ=0.705 (val F1=0.1487)
  Directional -> Accuracy: 0.5101, MCC: 0.0876, F1: 0.1261

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.65801 | val 1.15511
  Epoch 016 - train 0.63263 | val 1.97406
  Classification -> best τ=0.340 (val F1=0.1638)
  Directional -> Accuracy: 0.5859, MCC: 0.1474, F1: 0.6720

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.65280 | val 1.39221
  Epoch 016 - train 0.60982 | val 1.61039
  Classification -> best τ=0.315 (val F1=0.1707)
  Directional -> Accuracy: 0.5253, MCC: 0.0916, F1: 0.2769

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65032 | val 0.95460
  Epoch 016 - train 0.60529 | val 1.35732
  Classification -> best τ=0.390 (val F1=0.1917)
  Directional -> Accuracy: 0.5202, MCC: 0.0235, F1: 0.5778

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.67120 | val 0.90917
  Epoch 017 - train 0.64777 | val 1.15068
  Classification -> best τ=0.285 (val F1=0.1409)
  Directional -> Accuracy: 0.5455, MCC: -0.0564, F1: 0.6786

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64174 | val 0.83517
  Epoch 020 - train 0.58773 | val 1.24705
  Classification -> best τ=0.125 (val F1=0.1020)
  Directional -> Accuracy: 0.4444, MCC: -0.0113, F1: 0.6127

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.60426 | val 1.72795
  Epoch 016 - train 0.59659 | val 2.36894
  Classification -> best τ=0.475 (val F1=0.1348)
  Directional -> Accuracy: 0.5333, MCC: 0.0632, F1: 0.4615

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60899 | val 1.19599
  Epoch 016 - train 0.56381 | val 1.26400
  Classification -> best τ=0.580 (val F1=0.2020)
  Directional -> Accuracy: 0.4242, MCC: 0.0605, F1: 0.0172

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66638 | val 1.02945
  Epoch 016 - train 0.62137 | val 1.13739
  Classification -> best τ=0.515 (val F1=0.1704)
  Directional -> Accuracy: 0.4596, MCC: -0.1073, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.64694 | val 0.86814
  Epoch 016 - train 0.63104 | val 0.99355
  Classification -> best τ=0.500 (val F1=0.1118)
  Directional -> Accuracy: 0.4343, MCC: -0.0134, F1: 0.0175

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.64717 | val 1.69066
  Epoch 016 - train 0.62924 | val 2.26303
  Classification -> best τ=0.095 (val F1=0.1187)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.66688 | val 0.91986
  Epoch 016 - train 0.63222 | val 1.21522
  Classification -> best τ=0.690 (val F1=0.1786)
  Directional -> Accuracy: 0.4747, MCC: 0.0000, F1: 0.0000

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.65592 | val 0.98796
  Epoch 020 - train 0.58838 | val 1.97374
  Classification -> best τ=0.690 (val F1=0.1462)
  Directional -> Accuracy: 0.4848, MCC: -0.0339, F1: 0.5189

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66983 | val 1.07931
  Epoch 019 - train 0.59272 | val 2.06307
  Classification -> best τ=0.235 (val F1=0.1535)
  Directional -> Accuracy: 0.5707, MCC: 0.1210, F1: 0.6473

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64341 | val 0.89223
  Epoch 016 - train 0.61936 | val 0.91439
  Classification -> best τ=0.515 (val F1=0.1245)
  Directional -> Accuracy: 0.5051, MCC: 0.0379, F1: 0.2222

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65308 | val 1.09468
  Epoch 017 - train 0.60385 | val 1.93798
  Classification -> best τ=0.760 (val F1=0.2016)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63511 | val 3.32611
  Epoch 016 - train 0.57350 | val 4.14580
  Classification -> best τ=0.075 (val F1=0.0942)
  Directional -> Accuracy: 0.5354, MCC: 0.0041, F1: 0.6828

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65874 | val 1.27812
  Epoch 017 - train 0.62631 | val 1.55747
  Classification -> best τ=0.150 (val F1=0.0984)
  Directional -> Accuracy: 0.5606, MCC: 0.0163, F1: 0.6836

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64736 | val 0.84484
  Epoch 016 - train 0.60045 | val 0.93882
  Classification -> best τ=0.550 (val F1=0.1299)
  Directional -> Accuracy: 0.4646, MCC: 0.0955, F1: 0.1167

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67861 | val 0.87434
  Epoch 019 - train 0.56956 | val 1.80382
  Classification -> best τ=0.100 (val F1=0.1084)
  Directional -> Accuracy: 0.5051, MCC: -0.1026, F1: 0.6316

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.66402 | val 0.85345
  Epoch 019 - train 0.59917 | val 0.80118
  Classification -> best τ=0.360 (val F1=0.1656)
  Directional -> Accuracy: 0.5101, MCC: 0.0868, F1: 0.6523

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66158 | val 0.83785
  Epoch 016 - train 0.61144 | val 0.91617
  Classification -> best τ=0.410 (val F1=0.0935)
  Directional -> Accuracy: 0.5404, MCC: 0.0459, F1: 0.6192

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67128 | val 1.01329
  Epoch 016 - train 0.64938 | val 0.88381
  Classification -> best τ=0.420 (val F1=0.1380)
  Directional -> Accuracy: 0.5202, MCC: -0.0212, F1: 0.6360

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62999 | val 0.99162
  Epoch 016 - train 0.60231 | val 1.58992
  Classification -> best τ=0.590 (val F1=0.1143)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64603 | val 1.38083
  Epoch 016 - train 0.60565 | val 1.91063
  Classification -> best τ=0.600 (val F1=0.1217)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.67867 | val 0.70607
  Epoch 016 - train 0.60732 | val 0.70289
  Classification -> best τ=0.720 (val F1=0.1039)
  Directional -> Accuracy: 0.4040, MCC: -0.0401, F1: 0.0635

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.66669 | val 0.87638
  Epoch 016 - train 0.60290 | val 1.09318
  Classification -> best τ=0.480 (val F1=0.0531)
  Directional -> Accuracy: 0.4899, MCC: -0.0185, F1: 0.6217

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66009 | val 1.00996
  Epoch 016 - train 0.61462 | val 1.23857
  Classification -> best τ=0.280 (val F1=0.1216)
  Directional -> Accuracy: 0.5152, MCC: -0.0684, F1: 0.6800

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63408 | val 0.88868
  Epoch 016 - train 0.59129 | val 1.02848
  Classification -> best τ=0.435 (val F1=0.0904)
  Directional -> Accuracy: 0.4899, MCC: 0.0626, F1: 0.2628

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.65721 | val 0.75016
  Epoch 016 - train 0.61437 | val 0.94003
  Classification -> best τ=0.625 (val F1=0.1166)
  Directional -> Accuracy: 0.5253, MCC: 0.0642, F1: 0.4891

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63109 | val 1.25552
  Epoch 016 - train 0.58747 | val 1.50293
  Classification -> best τ=0.530 (val F1=0.2570)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63455 | val 1.11970
  Epoch 016 - train 0.59529 | val 1.72816
  Classification -> best τ=0.425 (val F1=0.2226)
  Directional -> Accuracy: 0.5303, MCC: 0.1449, F1: 0.3309

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63962 | val 1.49447
  Epoch 016 - train 0.57732 | val 2.10120
  Classification -> best τ=0.110 (val F1=0.1292)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.6485

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64918 | val 2.02265
  Epoch 016 - train 0.60970 | val 1.68603
  Classification -> best τ=0.435 (val F1=0.2190)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.64147 | val 0.92332
  Epoch 016 - train 0.60320 | val 1.05639
  Classification -> best τ=0.360 (val F1=0.0671)
  Directional -> Accuracy: 0.4798, MCC: -0.0081, F1: 0.5830

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.64630 | val 3.54056
  Epoch 016 - train 0.59533 | val 4.88300
  Classification -> best τ=0.110 (val F1=0.2083)
  Directional -> Accuracy: 0.4697, MCC: -0.0203, F1: 0.4262

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.67761 | val 0.74212
  Epoch 020 - train 0.57012 | val 1.62963
  Classification -> best τ=0.310 (val F1=0.1201)
  Directional -> Accuracy: 0.5606, MCC: 0.0241, F1: 0.6859

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.66086 | val 0.78377
  Epoch 016 - train 0.60085 | val 0.76459
  Classification -> best τ=0.550 (val F1=0.1926)
  Directional -> Accuracy: 0.4485, MCC: -0.0096, F1: 0.5523

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.62899 | val 0.85341
  Epoch 016 - train 0.59224 | val 0.94437
  Classification -> best τ=0.550 (val F1=0.1618)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.65107 | val 0.97260
  Epoch 016 - train 0.59791 | val 1.35565
  Classification -> best τ=0.525 (val F1=0.1234)
  Directional -> Accuracy: 0.5052, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63354 | val 1.74714
  Epoch 016 - train 0.60400 | val 2.44787
  Classification -> best τ=0.495 (val F1=0.2187)
  Directional -> Accuracy: 0.4798, MCC: 0.0166, F1: 0.5541

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.62137 | val 0.99231
  Epoch 016 - train 0.59239 | val 1.18906
  Classification -> best τ=0.325 (val F1=0.1724)
  Directional -> Accuracy: 0.5206, MCC: 0.0473, F1: 0.5867

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.68778 | val 0.77006
  Epoch 020 - train 0.60954 | val 1.48096
  Classification -> best τ=0.540 (val F1=0.1602)
  Directional -> Accuracy: 0.5455, MCC: 0.0988, F1: 0.5161

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.65395 | val 1.17260
  Epoch 018 - train 0.56629 | val 2.16569
  Classification -> best τ=0.415 (val F1=0.1963)
  Directional -> Accuracy: 0.5404, MCC: 0.0920, F1: 0.4800

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.65996 | val 1.84248
  Epoch 016 - train 0.63198 | val 2.67211
  Classification -> best τ=0.545 (val F1=0.0580)
  Directional -> Accuracy: 0.5707, MCC: 0.1417, F1: 0.1414

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.68316 | val 0.89789
  Epoch 016 - train 0.63307 | val 1.27667
  Classification -> best τ=0.230 (val F1=0.1081)
  Directional -> Accuracy: 0.5202, MCC: -0.0351, F1: 0.6823

[75/88] Processing T...


[I 2026-02-26 06:55:12,802] Trial 54 finished with value: 0.1513172448677239 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.004701660615236838, 'weight_decay': 2.99973190423573e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.6508709561503692, 'early_stopping_min_delta': 0.0053909474353690725}. Best is trial 53 with value: 0.15712278789285605.

  Epoch 016 - train 0.63442 | val 2.97298
  Classification -> best τ=0.485 (val F1=0.1596)
  Directional -> Accuracy: 0.5152, MCC: 0.0324, F1: 0.2500

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1513172448677239
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69407 | val 0.69374
  Epoch 020 - train 0.69340 | val 0.69369
  Classification -> best τ=0.535 (val F1=0.0684)
  Directional -> Accuracy: 0.4141, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.64816 | val 5.07975
  Epoch 016 - train 0.59212 | val 7.03995
  Classification -> best τ=0.495 (val F1=0.1462)
  Directional -> Accuracy: 0.4949, MCC: -0.0220, F1: 0.0909

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67385 | val 1.11685
  Epoch 017 - train 0.66849 | val 1.12557
  Classification -> best τ=0.205 (val F1=0.1719)
  Directional -> Accuracy: 0.5109, MCC: -0.0735, F1: 0.6371

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.68102 | val 0.69039
  Epoch 018 - train 0.66975 | val 0.69684
  Classification -> best τ=0.520 (val F1=0.1283)
  Directional -> Accuracy: 0.4444, MCC: -0.0213, F1: 0.2029

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.69036 | val 0.82306
  Epoch 020 - train 0.56374 | val 0.77078
  Classification -> best τ=0.540 (val F1=0.1936)
  Directional -> Accuracy: 0.4667, MCC: -0.0240, F1: 0.1765

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71774 | val 0.75020
  Epoch 020 - train 0.65212 | val 0.94913
  Classification -> best τ=0.490 (val F1=0.1217)
  Directional -> Accuracy: 0.5000, MCC: -0.0359, F1: 0.5892

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68099 | val 1.79298
  Epoch 020 - train 0.63239 | val 4.43583
  Classification -> best τ=0.565 (val F1=0.1592)
  Directional -> Accuracy: 0.4545, MCC: 0.0904, F1: 0.0357

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69699 | val 0.66973
  Epoch 020 - train 0.67091 | val 0.68370
  Classification -> best τ=0.460 (val F1=0.2906)
  Directional -> Accuracy: 0.3889, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.59248 | val 6.46066
  Epoch 016 - train 0.52228 | val 9.94686
  Classification -> best τ=0.380 (val F1=0.1895)
  Directional -> Accuracy: 0.4196, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70834 | val 0.90262
  Epoch 019 - train 0.65503 | val 0.97355
  Classification -> best τ=0.425 (val F1=0.0997)
  Directional -> Accuracy: 0.5404, MCC: 0.0082, F1: 0.0215

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.69241 | val 1.16246
  Epoch 020 - train 0.68346 | val 0.86679
  Classification -> best τ=0.600 (val F1=0.1856)
  Directional -> Accuracy: 0.4646, MCC: 0.0119, F1: 0.0702

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.67926 | val 0.69642
  Epoch 020 - train 0.66248 | val 1.03437
  Classification -> best τ=0.470 (val F1=0.1374)
  Directional -> Accuracy: 0.4495, MCC: 0.0744, F1: 0.1280

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68761 | val 0.90669
  Epoch 020 - train 0.65824 | val 0.84968
  Classification -> best τ=0.720 (val F1=0.1466)
  Directional -> Accuracy: 0.4646, MCC: -0.0083, F1: 0.3291

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67121 | val 1.23770
  Epoch 016 - train 0.62785 | val 1.79799
  Classification -> best τ=0.490 (val F1=0.1722)
  Directional -> Accuracy: 0.5505, MCC: 0.1173, F1: 0.3597

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.69660 | val 0.69322
  Epoch 020 - train 0.68519 | val 0.69354
  Classification -> best τ=0.500 (val F1=0.0700)
  Directional -> Accuracy: 0.4798, MCC: -0.0237, F1: 0.4114

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.68521 | val 1.96497
  Epoch 020 - train 0.62864 | val 2.14456
  Classification -> best τ=0.515 (val F1=0.0922)
  Directional -> Accuracy: 0.5303, MCC: 0.1384, F1: 0.1468

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.70277 | val 0.74668
  Epoch 020 - train 0.65350 | val 1.04865
  Classification -> best τ=0.500 (val F1=0.1324)
  Directional -> Accuracy: 0.5606, MCC: 0.0797, F1: 0.7166

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69506 | val 2.30290
  Epoch 019 - train 0.56528 | val 6.85096
  Classification -> best τ=0.800 (val F1=0.1854)
  Directional -> Accuracy: 0.4899, MCC: -0.0262, F1: 0.5388

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70120 | val 0.72970
  Epoch 020 - train 0.64193 | val 1.61359
  Classification -> best τ=0.470 (val F1=0.1813)
  Directional -> Accuracy: 0.4646, MCC: -0.0868, F1: 0.1970

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65844 | val 0.96360
  Epoch 016 - train 0.62898 | val 1.36382
  Classification -> best τ=0.690 (val F1=0.1715)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.69678 | val 1.50227
  Epoch 016 - train 0.65690 | val 1.52865
  Classification -> best τ=0.680 (val F1=0.1582)
  Directional -> Accuracy: 0.5152, MCC: 0.0363, F1: 0.5636

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.69289 | val 4.14634
  Epoch 019 - train 0.68940 | val 8.55142
  Classification -> best τ=0.510 (val F1=0.2019)
  Directional -> Accuracy: 0.4394, MCC: -0.0175, F1: 0.0348

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69266 | val 0.71929
  Epoch 019 - train 0.68870 | val 0.68929
  Classification -> best τ=0.390 (val F1=0.1084)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.7016

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.71134 | val 0.77167
  Epoch 020 - train 0.70013 | val 0.97523
  Classification -> best τ=0.100 (val F1=0.1401)
  Directional -> Accuracy: 0.3990, MCC: 0.0574, F1: 0.5673

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69224 | val 0.70592
  Epoch 020 - train 0.67179 | val 2.20461
  Classification -> best τ=0.475 (val F1=0.0880)
  Directional -> Accuracy: 0.5101, MCC: 0.0494, F1: 0.3822

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69577 | val 0.78904
  Epoch 016 - train 0.66055 | val 1.11375
  Classification -> best τ=0.130 (val F1=0.1822)
  Directional -> Accuracy: 0.5354, MCC: 0.0850, F1: 0.6068

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.72293 | val 0.77367
  Epoch 020 - train 0.63395 | val 0.82847
  Classification -> best τ=0.575 (val F1=0.1200)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.70646 | val 0.68737
  Epoch 020 - train 0.69194 | val 1.84151
  Classification -> best τ=0.520 (val F1=0.1039)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67593 | val 0.88380
  Epoch 016 - train 0.66036 | val 1.49147
  Classification -> best τ=0.455 (val F1=0.0960)
  Directional -> Accuracy: 0.5859, MCC: 0.1773, F1: 0.5543

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.68297 | val 0.79025
  Epoch 016 - train 0.67852 | val 1.39264
  Classification -> best τ=0.440 (val F1=0.1281)
  Directional -> Accuracy: 0.4899, MCC: 0.0626, F1: 0.2628

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.69696 | val 0.78996
  Epoch 020 - train 0.66661 | val 5.40668
  Classification -> best τ=0.150 (val F1=0.1345)
  Directional -> Accuracy: 0.5101, MCC: 0.0000, F1: 0.6756

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70976 | val 0.72106
  Epoch 018 - train 0.64433 | val 0.73021
  Classification -> best τ=0.555 (val F1=0.1091)
  Directional -> Accuracy: 0.4848, MCC: -0.0367, F1: 0.5234

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.68823 | val 0.74102
  Epoch 016 - train 0.67813 | val 2.03502
  Classification -> best τ=0.380 (val F1=0.1503)
  Directional -> Accuracy: 0.4697, MCC: -0.0599, F1: 0.5205

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69193 | val 0.68886
  Epoch 020 - train 0.64582 | val 0.73148
  Classification -> best τ=0.535 (val F1=0.1568)
  Directional -> Accuracy: 0.4394, MCC: -0.0550, F1: 0.5811

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.58338 | val 2.19458
  Epoch 016 - train 0.50706 | val 2.60203
  Classification -> best τ=0.330 (val F1=0.2130)
  Directional -> Accuracy: 0.5333, MCC: 0.0667, F1: 0.3226

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65974 | val 0.86214
  Epoch 018 - train 0.57424 | val 3.02180
  Classification -> best τ=0.715 (val F1=0.2263)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68633 | val 0.68852
  Epoch 020 - train 0.67640 | val 0.69171
  Classification -> best τ=0.540 (val F1=0.1567)
  Directional -> Accuracy: 0.4697, MCC: -0.0154, F1: 0.1026

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.69526 | val 0.92674
  Epoch 020 - train 0.66943 | val 0.70310
  Classification -> best τ=0.485 (val F1=0.1259)
  Directional -> Accuracy: 0.5051, MCC: 0.0421, F1: 0.4787

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.70950 | val 1.74777
  Epoch 020 - train 0.66865 | val 1.77052
  Classification -> best τ=0.515 (val F1=0.0237)
  Directional -> Accuracy: 0.4747, MCC: 0.0843, F1: 0.1034

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.69544 | val 0.71966
  Epoch 020 - train 0.68149 | val 1.77692
  Classification -> best τ=0.430 (val F1=0.1184)
  Directional -> Accuracy: 0.4141, MCC: -0.1650, F1: 0.3626

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.68521 | val 1.06634
  Epoch 016 - train 0.66462 | val 2.99481
  Classification -> best τ=0.480 (val F1=0.0990)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68197 | val 1.39522
  Epoch 016 - train 0.65222 | val 1.14819
  Classification -> best τ=0.715 (val F1=0.0867)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68125 | val 0.81207
  Epoch 020 - train 0.63496 | val 0.75324
  Classification -> best τ=0.500 (val F1=0.1850)
  Directional -> Accuracy: 0.5000, MCC: 0.0158, F1: 0.2878

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.71452 | val 0.68611
  Epoch 020 - train 0.66346 | val 0.72087
  Classification -> best τ=0.695 (val F1=0.2138)
  Directional -> Accuracy: 0.4242, MCC: -0.2032, F1: 0.5512

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70902 | val 7.94764
  Epoch 020 - train 0.61333 | val 2.88194
  Classification -> best τ=0.125 (val F1=0.0879)
  Directional -> Accuracy: 0.5303, MCC: 0.0156, F1: 0.6491

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67173 | val 1.74936
  Epoch 016 - train 0.65298 | val 2.11548
  Classification -> best τ=0.525 (val F1=0.0036)
  Directional -> Accuracy: 0.4444, MCC: 0.0036, F1: 0.2857

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67883 | val 0.69578
  Epoch 017 - train 0.64958 | val 0.72364
  Classification -> best τ=0.585 (val F1=0.1872)
  Directional -> Accuracy: 0.4697, MCC: 0.1300, F1: 0.1176

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68964 | val 0.79369
  Epoch 020 - train 0.69097 | val 2.90932
  Classification -> best τ=0.325 (val F1=0.1331)
  Directional -> Accuracy: 0.5202, MCC: 0.0350, F1: 0.5701

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.68693 | val 0.73286
  Epoch 020 - train 0.63768 | val 3.32340
  Classification -> best τ=0.335 (val F1=0.1460)
  Directional -> Accuracy: 0.5152, MCC: 0.0857, F1: 0.6471

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68705 | val 0.70431
  Epoch 019 - train 0.66886 | val 0.69142
  Classification -> best τ=0.515 (val F1=0.1101)
  Directional -> Accuracy: 0.5505, MCC: -0.0761, F1: 0.7082

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69708 | val 0.84340
  Epoch 020 - train 0.66790 | val 1.06403
  Classification -> best τ=0.365 (val F1=0.1383)
  Directional -> Accuracy: 0.5505, MCC: 0.0247, F1: 0.6877

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64582 | val 1.24894
  Epoch 016 - train 0.61040 | val 2.26355
  Classification -> best τ=0.635 (val F1=0.1799)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69019 | val 0.70641
  Epoch 020 - train 0.64080 | val 0.80662
  Classification -> best τ=0.535 (val F1=0.1039)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.68704 | val 1.06885
  Epoch 020 - train 0.62792 | val 1.24604
  Classification -> best τ=0.560 (val F1=0.2257)
  Directional -> Accuracy: 0.4091, MCC: -0.0311, F1: 0.1069

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.68731 | val 0.97670
  Epoch 020 - train 0.64581 | val 0.88945
  Classification -> best τ=0.470 (val F1=0.0972)
  Directional -> Accuracy: 0.5152, MCC: 0.0306, F1: 0.2941

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.69296 | val 0.93010
  Epoch 016 - train 0.66256 | val 1.66634
  Classification -> best τ=0.500 (val F1=0.1809)
  Directional -> Accuracy: 0.5101, MCC: 0.0433, F1: 0.3822

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69711 | val 1.02746
  Epoch 020 - train 0.70051 | val 0.92160
  Classification -> best τ=0.345 (val F1=0.1020)
  Directional -> Accuracy: 0.5657, MCC: 0.0994, F1: 0.7014

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.68905 | val 0.72472
  Epoch 020 - train 0.68968 | val 0.68730
  Classification -> best τ=0.605 (val F1=0.0823)
  Directional -> Accuracy: 0.4798, MCC: 0.0064, F1: 0.2137

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65375 | val 1.80813
  Epoch 020 - train 0.59879 | val 1.99503
  Classification -> best τ=0.435 (val F1=0.2264)
  Directional -> Accuracy: 0.4141, MCC: -0.0823, F1: 0.1944

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69644 | val 1.66271
  Epoch 017 - train 0.62450 | val 2.17538
  Classification -> best τ=0.215 (val F1=0.2037)
  Directional -> Accuracy: 0.5354, MCC: 0.1188, F1: 0.4177

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68164 | val 1.40838
  Epoch 017 - train 0.65294 | val 2.00334
  Classification -> best τ=0.575 (val F1=0.1291)
  Directional -> Accuracy: 0.5202, MCC: 0.0071, F1: 0.0594

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65294 | val 2.09692
  Epoch 016 - train 0.63959 | val 2.63961
  Classification -> best τ=0.370 (val F1=0.2011)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.70433 | val 0.81559
  Epoch 020 - train 0.68710 | val 0.68765
  Classification -> best τ=0.670 (val F1=0.1318)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.69188 | val 0.84789
  Epoch 020 - train 0.66679 | val 2.29273
  Classification -> best τ=0.280 (val F1=0.1604)
  Directional -> Accuracy: 0.4747, MCC: 0.0139, F1: 0.3810

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.69501 | val 0.69622
  Epoch 020 - train 0.67944 | val 0.70854
  Classification -> best τ=0.450 (val F1=0.0786)
  Directional -> Accuracy: 0.4899, MCC: -0.0254, F1: 0.5346

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.68164 | val 1.02145
  Epoch 016 - train 0.63745 | val 1.42881
  Classification -> best τ=0.325 (val F1=0.1732)
  Directional -> Accuracy: 0.4433, MCC: 0.0289, F1: 0.5846

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.66026 | val 1.55536
  Epoch 020 - train 0.62369 | val 2.27227
  Classification -> best τ=0.535 (val F1=0.1647)
  Directional -> Accuracy: 0.4949, MCC: 0.0569, F1: 0.2188

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.68568 | val 1.35704
  Epoch 016 - train 0.65594 | val 1.31103
  Classification -> best τ=0.120 (val F1=0.1662)
  Directional -> Accuracy: 0.5052, MCC: 0.0054, F1: 0.3043

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66683 | val 1.16433
  Epoch 016 - train 0.62379 | val 3.02155
  Classification -> best τ=0.365 (val F1=0.2229)
  Directional -> Accuracy: 0.4697, MCC: 0.0253, F1: 0.5817

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.71405 | val 1.05567
  Epoch 020 - train 0.66729 | val 1.62211
  Classification -> best τ=0.480 (val F1=0.2105)
  Directional -> Accuracy: 0.5258, MCC: 0.0636, F1: 0.6134

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.70635 | val 0.71553
  Epoch 020 - train 0.69292 | val 0.70341
  Classification -> best τ=0.530 (val F1=0.1668)
  Directional -> Accuracy: 0.4949, MCC: -0.0455, F1: 0.6212

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.69601 | val 2.77954
  Epoch 016 - train 0.65053 | val 3.33336
  Classification -> best τ=0.685 (val F1=0.0995)
  Directional -> Accuracy: 0.5051, MCC: 0.0770, F1: 0.1404

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.69027 | val 0.70962
  Epoch 017 - train 0.68197 | val 1.11672
  Classification -> best τ=0.275 (val F1=0.0988)
  Directional -> Accuracy: 0.5505, MCC: 0.1355, F1: 0.5936

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.71658 | val 1.17837
  Epoch 016 - train 0.65174 | val 1.75501
  Classification -> best τ=0.195 (val F1=0.1674)
  Directional -> Accuracy: 0.4899, MCC: -0.0082, F1: 0.4358

[75/88] Processing T...


[I 2026-02-26 07:25:58,055] Trial 55 finished with value: 0.1473090163781333 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.009033866139894714, 'weight_decay': 6.666535547993022e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.9408454147992071, 'early_stopping_min_delta': 0.007771098377581558}. Best is trial 53 with value: 0.15712278789285605.

  Classification -> best τ=0.465 (val F1=0.1446)
  Directional -> Accuracy: 0.4949, MCC: -0.0015, F1: 0.6575

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1473090163781333
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64262 | val 1.53547
  Epoch 016 - train 0.60033 | val 1.77395
  Classification -> best τ=0.420 (val F1=0.1245)
  Directional -> Accuracy: 0.4394, MCC: 0.0232, F1: 0.1898

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.59446 | val 4.86426
  Epoch 016 - train 0.57540 | val 6.62514
  Classification -> best τ=0.205 (val F1=0.1678)
  Directional -> Accuracy: 0.5101, MCC: 0.0718, F1: 0.0583

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64881 | val 0.81988
  Epoch 016 - train 0.62563 | val 0.91703
  Classification -> best τ=0.245 (val F1=0.1669)
  Directional -> Accuracy: 0.5489, MCC: 0.0003, F1: 0.6770

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.66676 | val 0.70253
  Epoch 016 - train 0.63716 | val 0.77189
  Classification -> best τ=0.620 (val F1=0.1296)
  Directional -> Accuracy: 0.4495, MCC: -0.0043, F1: 0.2044

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.61144 | val 1.47725
  Epoch 016 - train 0.58958 | val 2.22583
  Classification -> best τ=0.515 (val F1=0.1986)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61568 | val 0.85497
  Epoch 016 - train 0.59440 | val 0.98601
  Classification -> best τ=0.745 (val F1=0.1198)
  Directional -> Accuracy: 0.4495, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64835 | val 2.07895
  Epoch 016 - train 0.62668 | val 2.90438
  Classification -> best τ=0.480 (val F1=0.1587)
  Directional -> Accuracy: 0.4949, MCC: 0.1846, F1: 0.1803

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63091 | val 0.74500
  Epoch 016 - train 0.59033 | val 0.73559
  Classification -> best τ=0.330 (val F1=0.2514)
  Directional -> Accuracy: 0.5000, MCC: 0.0595, F1: 0.4923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62489 | val 3.36658
  Epoch 016 - train 0.57041 | val 4.28962
  Classification -> best τ=0.425 (val F1=0.1910)
  Directional -> Accuracy: 0.4196, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64217 | val 1.06234
  Epoch 016 - train 0.61092 | val 1.25348
  Classification -> best τ=0.685 (val F1=0.1065)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.61912 | val 0.82086
  Epoch 016 - train 0.57767 | val 0.91441
  Classification -> best τ=0.615 (val F1=0.1837)
  Directional -> Accuracy: 0.4596, MCC: -0.0082, F1: 0.0183

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.63837 | val 0.82822
  Epoch 016 - train 0.59294 | val 0.87484
  Classification -> best τ=0.470 (val F1=0.1569)
  Directional -> Accuracy: 0.4697, MCC: 0.0605, F1: 0.2759

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62057 | val 0.76691
  Epoch 016 - train 0.58186 | val 0.73462
  Classification -> best τ=0.580 (val F1=0.1245)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61459 | val 1.72322
  Epoch 016 - train 0.58159 | val 2.41342
  Classification -> best τ=0.775 (val F1=0.1955)
  Directional -> Accuracy: 0.5051, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.64903 | val 1.37854
  Epoch 016 - train 0.64521 | val 1.91538
  Classification -> best τ=0.405 (val F1=0.0950)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.63742 | val 1.56457
  Epoch 016 - train 0.59062 | val 1.72234
  Classification -> best τ=0.480 (val F1=0.1474)
  Directional -> Accuracy: 0.5051, MCC: 0.0712, F1: 0.0200

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.64566 | val 0.83988
  Epoch 016 - train 0.61199 | val 0.87660
  Classification -> best τ=0.695 (val F1=0.1331)
  Directional -> Accuracy: 0.5960, MCC: 0.1576, F1: 0.6970

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60362 | val 2.00012
  Epoch 016 - train 0.54727 | val 2.78534
  Classification -> best τ=0.935 (val F1=0.0823)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64647 | val 0.74747
  Epoch 017 - train 0.58914 | val 0.86837
  Classification -> best τ=0.365 (val F1=0.2915)
  Directional -> Accuracy: 0.4949, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63356 | val 0.89285
  Epoch 016 - train 0.60677 | val 1.03084
  Classification -> best τ=0.635 (val F1=0.1348)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.62334 | val 0.81441
  Epoch 016 - train 0.61384 | val 0.96075
  Classification -> best τ=0.805 (val F1=0.1417)
  Directional -> Accuracy: 0.5455, MCC: 0.0887, F1: 0.4828

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.66746 | val 1.60652
  Epoch 016 - train 0.63401 | val 1.73893
  Classification -> best τ=0.420 (val F1=0.1768)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62723 | val 0.96779
  Epoch 016 - train 0.59053 | val 1.49985
  Classification -> best τ=0.430 (val F1=0.1397)
  Directional -> Accuracy: 0.5556, MCC: 0.0860, F1: 0.7007

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.62955 | val 1.25658
  Epoch 016 - train 0.62176 | val 1.52573
  Classification -> best τ=0.180 (val F1=0.1488)
  Directional -> Accuracy: 0.4040, MCC: 0.0080, F1: 0.5597

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62201 | val 1.83124
  Epoch 016 - train 0.58996 | val 2.09756
  Classification -> best τ=0.300 (val F1=0.1199)
  Directional -> Accuracy: 0.5000, MCC: 0.0210, F1: 0.4000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64829 | val 0.78620
  Epoch 016 - train 0.63017 | val 0.81353
  Classification -> best τ=0.455 (val F1=0.1735)
  Directional -> Accuracy: 0.5505, MCC: 0.1048, F1: 0.3946

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64755 | val 1.07585
  Epoch 016 - train 0.59082 | val 1.32744
  Classification -> best τ=0.465 (val F1=0.2060)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.66271 | val 0.91059
  Epoch 016 - train 0.61209 | val 1.25276
  Classification -> best τ=0.485 (val F1=0.1081)
  Directional -> Accuracy: 0.5051, MCC: 0.0242, F1: 0.6597

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64537 | val 1.30705
  Epoch 016 - train 0.61675 | val 1.93464
  Classification -> best τ=0.575 (val F1=0.1338)
  Directional -> Accuracy: 0.5152, MCC: 0.0631, F1: 0.2615

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.65120 | val 1.07058
  Epoch 016 - train 0.62312 | val 1.39287
  Classification -> best τ=0.440 (val F1=0.1388)
  Directional -> Accuracy: 0.5051, MCC: 0.1291, F1: 0.2462

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.63688 | val 3.65433
  Epoch 016 - train 0.59721 | val 5.11584
  Classification -> best τ=0.165 (val F1=0.2038)
  Directional -> Accuracy: 0.5253, MCC: 0.0481, F1: 0.5607

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65444 | val 1.49094
  Epoch 016 - train 0.60936 | val 2.10731
  Classification -> best τ=0.260 (val F1=0.1185)
  Directional -> Accuracy: 0.4444, MCC: -0.0672, F1: 0.2857

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.67160 | val 0.84963
  Epoch 016 - train 0.64788 | val 0.98545
  Classification -> best τ=0.395 (val F1=0.1396)
  Directional -> Accuracy: 0.5404, MCC: -0.0344, F1: 0.6617

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63987 | val 1.03380
  Epoch 016 - train 0.60146 | val 1.01587
  Classification -> best τ=0.460 (val F1=0.1228)
  Directional -> Accuracy: 0.5253, MCC: 0.0144, F1: 0.3896

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.55773 | val 1.63915
  Epoch 016 - train 0.56269 | val 1.75199
  Classification -> best τ=0.465 (val F1=0.2548)
  Directional -> Accuracy: 0.5778, MCC: 0.1877, F1: 0.6545

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61100 | val 1.13475
  Epoch 016 - train 0.57979 | val 0.96643
  Classification -> best τ=0.440 (val F1=0.2057)
  Directional -> Accuracy: 0.4091, MCC: -0.0963, F1: 0.0168

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64527 | val 0.83683
  Epoch 016 - train 0.61421 | val 0.82707
  Classification -> best τ=0.635 (val F1=0.1754)
  Directional -> Accuracy: 0.4646, MCC: -0.0490, F1: 0.0185

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.66054 | val 1.12522
  Epoch 016 - train 0.61801 | val 1.11666
  Classification -> best τ=0.670 (val F1=0.0904)
  Directional -> Accuracy: 0.4343, MCC: 0.0000, F1: 0.0000

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.63775 | val 1.86667
  Epoch 016 - train 0.60109 | val 2.25365
  Classification -> best τ=0.490 (val F1=0.1107)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.65479 | val 1.13421
  Epoch 016 - train 0.62263 | val 1.56817
  Classification -> best τ=0.560 (val F1=0.1005)
  Directional -> Accuracy: 0.4444, MCC: -0.1009, F1: 0.3678

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.63810 | val 2.68480
  Epoch 016 - train 0.62379 | val 3.28346
  Classification -> best τ=0.775 (val F1=0.1288)
  Directional -> Accuracy: 0.4747, MCC: -0.0406, F1: 0.2973

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63825 | val 1.31035
  Epoch 016 - train 0.60603 | val 1.87132
  Classification -> best τ=0.205 (val F1=0.1224)
  Directional -> Accuracy: 0.5455, MCC: 0.0515, F1: 0.7020

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66471 | val 1.00663
  Epoch 016 - train 0.62648 | val 1.24603
  Classification -> best τ=0.555 (val F1=0.1732)
  Directional -> Accuracy: 0.4949, MCC: 0.0106, F1: 0.1667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64386 | val 1.05820
  Epoch 016 - train 0.61216 | val 1.58679
  Classification -> best τ=0.720 (val F1=0.1465)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61590 | val 2.52059
  Epoch 016 - train 0.57291 | val 2.82586
  Classification -> best τ=0.185 (val F1=0.1231)
  Directional -> Accuracy: 0.5455, MCC: 0.0436, F1: 0.6853

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65085 | val 1.23719
  Epoch 016 - train 0.61343 | val 1.45159
  Classification -> best τ=0.150 (val F1=0.0773)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65509 | val 0.92603
  Epoch 020 - train 0.59772 | val 1.09279
  Classification -> best τ=0.265 (val F1=0.1445)
  Directional -> Accuracy: 0.5606, MCC: 0.0175, F1: 0.7148

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61001 | val 1.08703
  Epoch 016 - train 0.58487 | val 1.58300
  Classification -> best τ=0.375 (val F1=0.0835)
  Directional -> Accuracy: 0.6010, MCC: 0.0476, F1: 0.7427

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64853 | val 0.86594
  Epoch 016 - train 0.60696 | val 1.23539
  Classification -> best τ=0.300 (val F1=0.1430)
  Directional -> Accuracy: 0.4899, MCC: 0.0273, F1: 0.6505

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63082 | val 0.96081
  Epoch 016 - train 0.62921 | val 0.87927
  Classification -> best τ=0.550 (val F1=0.0951)
  Directional -> Accuracy: 0.4343, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65016 | val 0.89392
  Epoch 016 - train 0.61351 | val 0.97295
  Classification -> best τ=0.270 (val F1=0.0976)
  Directional -> Accuracy: 0.5051, MCC: -0.0262, F1: 0.5917

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64283 | val 0.83239
  Epoch 016 - train 0.59955 | val 1.02111
  Classification -> best τ=0.280 (val F1=0.1324)
  Directional -> Accuracy: 0.5455, MCC: 0.0919, F1: 0.5312

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63046 | val 1.05088
  Epoch 016 - train 0.60394 | val 1.41849
  Classification -> best τ=0.505 (val F1=0.1432)
  Directional -> Accuracy: 0.5606, MCC: 0.1532, F1: 0.6790

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.67308 | val 0.69488
  Epoch 017 - train 0.62719 | val 0.74606
  Classification -> best τ=0.460 (val F1=0.1326)
  Directional -> Accuracy: 0.5657, MCC: -0.0665, F1: 0.7152

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.64082 | val 1.00837
  Epoch 016 - train 0.61081 | val 1.14676
  Classification -> best τ=0.460 (val F1=0.1486)
  Directional -> Accuracy: 0.4798, MCC: -0.0840, F1: 0.6436

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.64789 | val 0.72657
  Epoch 016 - train 0.62041 | val 0.91215
  Classification -> best τ=0.695 (val F1=0.1409)
  Directional -> Accuracy: 0.4798, MCC: -0.0041, F1: 0.0190

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63619 | val 0.96294
  Epoch 016 - train 0.58356 | val 0.91452
  Classification -> best τ=0.790 (val F1=0.0950)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.65937 | val 0.77284
  Epoch 018 - train 0.61621 | val 1.09277
  Classification -> best τ=0.455 (val F1=0.0643)
  Directional -> Accuracy: 0.5101, MCC: -0.0694, F1: 0.6667

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63116 | val 1.21981
  Epoch 016 - train 0.58989 | val 1.31853
  Classification -> best τ=0.525 (val F1=0.2570)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63678 | val 1.31340
  Epoch 016 - train 0.57959 | val 1.92104
  Classification -> best τ=0.295 (val F1=0.2140)
  Directional -> Accuracy: 0.5202, MCC: 0.0779, F1: 0.4172

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63055 | val 1.11131
  Epoch 016 - train 0.61255 | val 1.32438
  Classification -> best τ=0.160 (val F1=0.1495)
  Directional -> Accuracy: 0.4747, MCC: -0.0742, F1: 0.6438

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63663 | val 1.57453
  Epoch 016 - train 0.61586 | val 1.74932
  Classification -> best τ=0.310 (val F1=0.1589)
  Directional -> Accuracy: 0.4949, MCC: 0.0451, F1: 0.0909

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.64391 | val 0.81918
  Epoch 016 - train 0.61063 | val 0.92591
  Classification -> best τ=0.530 (val F1=0.1065)
  Directional -> Accuracy: 0.5253, MCC: -0.0671, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.65011 | val 4.09772
  Epoch 020 - train 0.60545 | val 0.84388
  Classification -> best τ=0.915 (val F1=0.1753)
  Directional -> Accuracy: 0.4697, MCC: -0.0428, F1: 0.4724

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.63251 | val 1.43904
  Epoch 016 - train 0.59036 | val 1.65961
  Classification -> best τ=0.610 (val F1=0.1010)
  Directional -> Accuracy: 0.4242, MCC: 0.0216, F1: 0.0339

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.62374 | val 0.88452
  Epoch 016 - train 0.58657 | val 0.83716
  Classification -> best τ=0.425 (val F1=0.2492)
  Directional -> Accuracy: 0.4381, MCC: -0.0217, F1: 0.5587

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.62711 | val 0.93629
  Epoch 016 - train 0.56436 | val 1.14671
  Classification -> best τ=0.550 (val F1=0.1791)
  Directional -> Accuracy: 0.5354, MCC: 0.1240, F1: 0.3867

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.63716 | val 1.21390
  Epoch 016 - train 0.58917 | val 1.63229
  Classification -> best τ=0.720 (val F1=0.0656)
  Directional -> Accuracy: 0.5052, MCC: 0.0000, F1: 0.0000

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61950 | val 1.48816
  Epoch 016 - train 0.59246 | val 1.95988
  Classification -> best τ=0.480 (val F1=0.2789)
  Directional -> Accuracy: 0.4444, MCC: -0.0455, F1: 0.5565

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.62772 | val 0.88505
  Epoch 016 - train 0.59268 | val 1.07199
  Classification -> best τ=0.450 (val F1=0.1695)
  Directional -> Accuracy: 0.5103, MCC: 0.0179, F1: 0.3357

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.67189 | val 0.87977
  Epoch 019 - train 0.60925 | val 1.10492
  Classification -> best τ=0.515 (val F1=0.1446)
  Directional -> Accuracy: 0.5152, MCC: 0.0295, F1: 0.5294

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.62549 | val 1.01676
  Epoch 016 - train 0.59255 | val 1.65506
  Classification -> best τ=0.420 (val F1=0.1277)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.64364 | val 3.65109
  Epoch 016 - train 0.62074 | val 4.49793
  Classification -> best τ=0.570 (val F1=0.0792)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.65588 | val 0.80024
  Epoch 016 - train 0.62257 | val 0.98762
  Classification -> best τ=0.430 (val F1=0.1569)
  Directional -> Accuracy: 0.5253, MCC: 0.1073, F1: 0.3286

[75/88] Processing T...

Processing T (Technology)...

[I 2026-02-26 07:34:43,147] Trial 56 finished with value: 0.14975209754799515 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.0024820333424575383, 'weight_decay': 4.285248029873285e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.7528251299603252, 'early_stopping_min_delta': 0.0049832939427365075}. Best is trial 53 with value: 0.15712278789285605.

  Epoch 016 - train 0.60925 | val 2.30121
  Classification -> best τ=0.455 (val F1=0.1486)
  Directional -> Accuracy: 0.5404, MCC: 0.0802, F1: 0.5134

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.14975209754799515
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 20
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61724 | val 1.33308
  Epoch 016 - train 0.58074 | val 1.81545
  Classification -> best τ=0.370 (val F1=0.1495)
  Directional -> Accuracy: 0.4394, MCC: -0.0178, F1: 0.2745

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
  Epoch 010 - train 0.57242 | val 6.84153
  Epoch 016 - train 0.53013 | val 8.94292
  Classification -> best τ=0.250 (val F1=0.1646)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62551 | val 0.99595
  Epoch 016 - train 0.61376 | val 1.32757
  Classification -> best τ=0.355 (val F1=0.1405)
  Directional -> Accuracy: 0.5272, MCC: 0.0137, F1: 0.6099

[4/88] Processing AEP...

Processing AEP (Utilities)...
  Epoch 010 - train 0.64434 | val 0.74680
  Epoch 016 - train 0.59108 | val 1.08333
  Classification -> best τ=0.480 (val F1=0.0840)
  Directional -> Accuracy: 0.4545, MCC: 0.0180, F1: 0.1940

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
  Epoch 010 - train 0.57903 | val 2.11573
  Epoch 016 - train 0.52552 | val 3.42168
  Classification -> best τ=0.545 (val F1=0.2048)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59778 | val 1.06511
  Epoch 016 - train 0.57492 | val 1.58939
  Classification -> best τ=0.705 (val F1=0.1179)
  Directional -> Accuracy: 0.4495, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63799 | val 2.40729
  Epoch 016 - train 0.59479 | val 3.27758
  Classification -> best τ=0.565 (val F1=0.1378)
  Directional -> Accuracy: 0.4495, MCC: 0.0637, F1: 0.0180

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61815 | val 0.91508
  Epoch 016 - train 0.57267 | val 1.02676
  Classification -> best τ=0.270 (val F1=0.3022)
  Directional -> Accuracy: 0.5253, MCC: 0.0999, F1: 0.5300

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57016 | val 4.19598
  Epoch 016 - train 0.51004 | val 4.84979
  Classification -> best τ=0.490 (val F1=0.1616)
  Directional -> Accuracy: 0.4196, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62547 | val 1.73091
  Epoch 016 - train 0.61211 | val 2.10656
  Classification -> best τ=0.745 (val F1=0.1497)
  Directional -> Accuracy: 0.5404, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
  Epoch 010 - train 0.61196 | val 0.87271
  Epoch 016 - train 0.56768 | val 1.01692
  Classification -> best τ=0.555 (val F1=0.1727)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[12/88] Processing BCH...

Processing BCH (Financial)...
  Epoch 010 - train 0.61643 | val 0.85346
  Epoch 016 - train 0.58467 | val 0.92448
  Classification -> best τ=0.480 (val F1=0.1233)
  Directional -> Accuracy: 0.4444, MCC: 0.0164, F1: 0.1791

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.61847 | val 0.80714
  Epoch 016 - train 0.57471 | val 0.83720
  Classification -> best τ=0.440 (val F1=0.1588)
  Directional -> Accuracy: 0.5051, MCC: 0.0151, F1: 0.5243

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59591 | val 2.64852
  Epoch 016 - train 0.56124 | val 3.19953
  Classification -> best τ=0.760 (val F1=0.1924)
  Directional -> Accuracy: 0.5051, MCC: 0.0018, F1: 0.0577

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
  Epoch 010 - train 0.65387 | val 1.67491
  Epoch 016 - train 0.61577 | val 2.26115
  Classification -> best τ=0.455 (val F1=0.1247)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[16/88] Processing BSAC...

Processing BSAC (Financial)...
  Epoch 010 - train 0.59795 | val 1.44997
  Epoch 016 - train 0.55599 | val 1.72110
  Classification -> best τ=0.560 (val F1=0.1361)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
  Epoch 010 - train 0.62940 | val 0.86997
  Epoch 016 - train 0.59768 | val 0.92503
  Classification -> best τ=0.400 (val F1=0.1956)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58665 | val 2.22691
  Epoch 016 - train 0.53613 | val 2.79423
  Classification -> best τ=0.395 (val F1=0.1625)
  Directional -> Accuracy: 0.4848, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60331 | val 0.87326
  Epoch 016 - train 0.56444 | val 0.87303
  Classification -> best τ=0.455 (val F1=0.2125)
  Directional -> Accuracy: 0.4899, MCC: -0.0720, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61259 | val 0.99886
  Epoch 016 - train 0.58094 | val 1.20968
  Classification -> best τ=0.535 (val F1=0.1098)
  Directional -> Accuracy: 0.4495, MCC: -0.0631, F1: 0.0840

[21/88] Processing CHL...

Processing CHL (Technology)...
  Epoch 010 - train 0.61844 | val 0.81623
  Epoch 016 - train 0.57390 | val 0.93610
  Classification -> best τ=0.345 (val F1=0.1469)
  Directional -> Accuracy: 0.4899, MCC: 0.0000, F1: 0.6576

[22/88] Processing CHTR...

Processing CHTR (Services)...
  Epoch 010 - train 0.64138 | val 2.68118
  Epoch 016 - train 0.60034 | val 3.61499
  Classification -> best τ=0.365 (val F1=0.2459)
  Directional -> Accuracy: 0.4394, MCC: 0.0000, F1: 0.0000

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62609 | val 1.23066
  Epoch 016 - train 0.57914 | val 1.81532
  Classification -> best τ=0.450 (val F1=0.1241)
  Directional -> Accuracy: 0.4798, MCC: 0.0644, F1: 0.1345

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
  Epoch 010 - train 0.62058 | val 2.22892
  Epoch 016 - train 0.58822 | val 2.63956
  Classification -> best τ=0.195 (val F1=0.1590)
  Directional -> Accuracy: 0.3939, MCC: 0.0000, F1: 0.5652

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61082 | val 1.32775
  Epoch 016 - train 0.55876 | val 1.58122
  Classification -> best τ=0.490 (val F1=0.1035)
  Directional -> Accuracy: 0.5253, MCC: 0.0601, F1: 0.4946

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64163 | val 0.91183
  Epoch 016 - train 0.59614 | val 0.99526
  Classification -> best τ=0.390 (val F1=0.2411)
  Directional -> Accuracy: 0.5556, MCC: 0.1370, F1: 0.3016

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61801 | val 1.36808
  Epoch 016 - train 0.57346 | val 2.15706
  Classification -> best τ=0.400 (val F1=0.1856)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
  Epoch 010 - train 0.62873 | val 0.94271
  Epoch 016 - train 0.61210 | val 1.16805
  Classification -> best τ=0.355 (val F1=0.1175)
  Directional -> Accuracy: 0.4848, MCC: -0.0473, F1: 0.6277

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63432 | val 2.67044
  Epoch 016 - train 0.58869 | val 4.68188
  Classification -> best τ=0.650 (val F1=0.1570)
  Directional -> Accuracy: 0.5000, MCC: 0.0311, F1: 0.1538

[30/88] Processing DUK...

Processing DUK (Utilities)...
  Epoch 010 - train 0.64827 | val 1.44109
  Epoch 016 - train 0.59413 | val 2.37358
  Classification -> best τ=0.230 (val F1=0.1073)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[31/88] Processing EXC...

Processing EXC (Utilities)...
  Epoch 010 - train 0.61676 | val 2.90875
  Epoch 016 - train 0.57284 | val 5.06861
  Classification -> best τ=0.260 (val F1=0.1480)
  Directional -> Accuracy: 0.5505, MCC: 0.1119, F1: 0.4795

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62006 | val 2.08999
  Epoch 016 - train 0.60781 | val 2.21632
  Classification -> best τ=0.380 (val F1=0.1650)
  Directional -> Accuracy: 0.5606, MCC: 0.0775, F1: 0.6717

[33/88] Processing GD...

Processing GD (Industrial Goods)...
  Epoch 010 - train 0.66523 | val 0.87130
  Epoch 016 - train 0.61717 | val 0.92353
  Classification -> best τ=0.310 (val F1=0.1591)
  Directional -> Accuracy: 0.5556, MCC: -0.0849, F1: 0.7007

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61659 | val 1.28983
  Epoch 016 - train 0.57228 | val 1.19531
  Classification -> best τ=0.420 (val F1=0.1518)
  Directional -> Accuracy: 0.5303, MCC: 0.0328, F1: 0.4224

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
  Epoch 010 - train 0.57597 | val 1.70108
  Epoch 016 - train 0.55226 | val 2.14998
  Classification -> best τ=0.445 (val F1=0.1818)
  Directional -> Accuracy: 0.5333, MCC: 0.1493, F1: 0.6667

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59785 | val 0.89743
  Epoch 016 - train 0.56581 | val 1.06808
  Classification -> best τ=0.480 (val F1=0.1912)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.63555 | val 1.02187
  Epoch 016 - train 0.57933 | val 1.26527
  Classification -> best τ=0.535 (val F1=0.2148)
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
  Epoch 010 - train 0.62812 | val 0.87630
  Epoch 016 - train 0.60000 | val 1.11855
  Classification -> best τ=0.245 (val F1=0.1387)
  Directional -> Accuracy: 0.6061, MCC: 0.1902, F1: 0.6638

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
  Epoch 010 - train 0.62433 | val 1.94932
  Epoch 016 - train 0.57798 | val 2.94360
  Classification -> best τ=0.470 (val F1=0.0993)
  Directional -> Accuracy: 0.4495, MCC: -0.0443, F1: 0.0840

[40/88] Processing HSBC...

Processing HSBC (Financial)...
  Epoch 010 - train 0.62190 | val 2.68718
  Epoch 016 - train 0.59051 | val 3.78009
  Classification -> best τ=0.745 (val F1=0.1536)
  Directional -> Accuracy: 0.4747, MCC: 0.0000, F1: 0.0000

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
  Epoch 010 - train 0.61750 | val 2.22816
  Epoch 016 - train 0.57205 | val 2.52556
  Classification -> best τ=0.645 (val F1=0.1526)
  Directional -> Accuracy: 0.4495, MCC: -0.0969, F1: 0.3978

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62326 | val 1.43450
  Epoch 016 - train 0.56394 | val 2.04116
  Classification -> best τ=0.640 (val F1=0.0867)
  Directional -> Accuracy: 0.4596, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62868 | val 0.85419
  Epoch 016 - train 0.59615 | val 1.06658
  Classification -> best τ=0.430 (val F1=0.1266)
  Directional -> Accuracy: 0.4646, MCC: -0.0771, F1: 0.5225

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61070 | val 1.64764
  Epoch 016 - train 0.57624 | val 2.36393
  Classification -> best τ=0.605 (val F1=0.2020)
  Directional -> Accuracy: 0.4798, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60578 | val 3.81022
  Epoch 016 - train 0.54595 | val 4.78575
  Classification -> best τ=0.145 (val F1=0.1107)
  Directional -> Accuracy: 0.5455, MCC: 0.0499, F1: 0.6691

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63807 | val 1.26168
  Epoch 016 - train 0.58666 | val 1.90843
  Classification -> best τ=0.700 (val F1=0.0657)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65015 | val 0.94922
  Epoch 016 - train 0.60260 | val 1.09802
  Classification -> best τ=0.435 (val F1=0.1811)
  Directional -> Accuracy: 0.5758, MCC: 0.1054, F1: 0.6769

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60038 | val 1.39120
  Epoch 016 - train 0.57600 | val 1.64046
  Classification -> best τ=0.650 (val F1=0.1338)
  Directional -> Accuracy: 0.3990, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63017 | val 1.02860
  Epoch 016 - train 0.59197 | val 1.53021
  Classification -> best τ=0.450 (val F1=0.1981)
  Directional -> Accuracy: 0.4293, MCC: -0.1421, F1: 0.4145

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62760 | val 1.43865
  Epoch 016 - train 0.59969 | val 1.38466
  Classification -> best τ=0.615 (val F1=0.0951)
  Directional -> Accuracy: 0.4343, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64826 | val 0.75357
  Epoch 016 - train 0.59619 | val 0.72301
  Classification -> best τ=0.445 (val F1=0.0493)
  Directional -> Accuracy: 0.5101, MCC: -0.0637, F1: 0.6421

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62322 | val 1.04172
  Epoch 016 - train 0.58951 | val 1.11009
  Classification -> best τ=0.460 (val F1=0.1322)
  Directional -> Accuracy: 0.4848, MCC: -0.0449, F1: 0.0893

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61365 | val 1.34496
  Epoch 016 - train 0.58153 | val 2.03240
  Classification -> best τ=0.310 (val F1=0.1527)
  Directional -> Accuracy: 0.5859, MCC: 0.1708, F1: 0.6019

[54/88] Processing NEE...

Processing NEE (Utilities)...
  Epoch 010 - train 0.61545 | val 0.70702
  Epoch 017 - train 0.56124 | val 0.77479
  Classification -> best τ=0.485 (val F1=0.1861)
  Directional -> Accuracy: 0.4394, MCC: 0.0149, F1: 0.2550

[55/88] Processing NGG...

Processing NGG (Utilities)...
  Epoch 010 - train 0.62776 | val 1.43659
  Epoch 016 - train 0.57735 | val 2.19142
  Classification -> best τ=0.460 (val F1=0.1537)
  Directional -> Accuracy: 0.5000, MCC: 0.0101, F1: 0.6292

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.62240 | val 0.88766
  Epoch 016 - train 0.60079 | val 1.71090
  Classification -> best τ=0.390 (val F1=0.1216)
  Directional -> Accuracy: 0.5303, MCC: 0.0777, F1: 0.6869

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61373 | val 0.99507
  Epoch 016 - train 0.55192 | val 1.10974
  Classification -> best τ=0.250 (val F1=0.0732)
  Directional -> Accuracy: 0.5960, MCC: 0.1774, F1: 0.6491

[58/88] Processing PCG...

Processing PCG (Utilities)...
  Epoch 010 - train 0.63800 | val 0.94253
  Epoch 016 - train 0.59608 | val 1.48095
  Classification -> best τ=0.650 (val F1=0.0649)
  Directional -> Accuracy: 0.4949, MCC: 0.0860, F1: 0.1525

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60285 | val 1.29680
  Epoch 016 - train 0.56081 | val 1.13398
  Classification -> best τ=0.505 (val F1=0.2019)
  Directional -> Accuracy: 0.4192, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62449 | val 1.54541
  Epoch 016 - train 0.56712 | val 2.44042
  Classification -> best τ=0.385 (val F1=0.2122)
  Directional -> Accuracy: 0.5000, MCC: 0.0709, F1: 0.2667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61375 | val 1.62265
  Epoch 016 - train 0.56800 | val 1.83229
  Classification -> best τ=0.820 (val F1=0.1072)
  Directional -> Accuracy: 0.5202, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61687 | val 2.37368
  Epoch 016 - train 0.56936 | val 2.73593
  Classification -> best τ=0.110 (val F1=0.1994)
  Directional -> Accuracy: 0.5101, MCC: 0.0387, F1: 0.3742

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
  Epoch 010 - train 0.61636 | val 0.88120
  Epoch 016 - train 0.57125 | val 1.02236
  Classification -> best τ=0.570 (val F1=0.1526)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[64/88] Processing PM...

Processing PM (Consumer Goods)...
  Epoch 010 - train 0.60838 | val 1.31037
  Epoch 020 - train 0.55220 | val 1.23246
  Classification -> best τ=0.810 (val F1=0.1855)
  Directional -> Accuracy: 0.4545, MCC: 0.0913, F1: 0.1148

[65/88] Processing PPL...

Processing PPL (Utilities)...
  Epoch 010 - train 0.61365 | val 1.94930
  Epoch 016 - train 0.56737 | val 2.61257
  Classification -> best τ=0.520 (val F1=0.0866)
  Directional -> Accuracy: 0.4242, MCC: 0.0216, F1: 0.0339

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
  Epoch 010 - train 0.59729 | val 0.85590
  Epoch 020 - train 0.50635 | val 1.38741
  Classification -> best τ=0.215 (val F1=0.2390)
  Directional -> Accuracy: 0.4742, MCC: 0.0154, F1: 0.5364

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
  Epoch 010 - train 0.60969 | val 0.85721
  Epoch 016 - train 0.57498 | val 1.01654
  Classification -> best τ=0.510 (val F1=0.1823)
  Directional -> Accuracy: 0.5303, MCC: 0.1073, F1: 0.3922

[68/88] Processing REX...

Processing REX (Conglomerates)...
  Epoch 010 - train 0.60938 | val 1.21033
  Epoch 016 - train 0.57743 | val 1.37048
  Classification -> best τ=0.550 (val F1=0.1313)
  Directional -> Accuracy: 0.5103, MCC: 0.0207, F1: 0.1739

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60886 | val 1.82833
  Epoch 016 - train 0.56333 | val 2.42188
  Classification -> best τ=0.590 (val F1=0.2689)
  Directional -> Accuracy: 0.4646, MCC: -0.0264, F1: 0.5268

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
  Epoch 010 - train 0.62166 | val 1.20237
  Epoch 016 - train 0.57100 | val 1.60981
  Classification -> best τ=0.550 (val F1=0.1552)
  Directional -> Accuracy: 0.5361, MCC: 0.0978, F1: 0.2500

[71/88] Processing SNY...

Processing SNY (Healthcare)...
  Epoch 010 - train 0.64384 | val 1.40307
  Epoch 016 - train 0.58226 | val 0.95383
  Classification -> best τ=0.800 (val F1=0.1954)
  Directional -> Accuracy: 0.5202, MCC: 0.0613, F1: 0.4172

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61344 | val 1.50744
  Epoch 016 - train 0.55539 | val 1.53989
  Classification -> best τ=0.225 (val F1=0.1084)
  Directional -> Accuracy: 0.5152, MCC: 0.0000, F1: 0.6800

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
  Epoch 010 - train 0.64950 | val 3.59130
  Epoch 016 - train 0.59679 | val 5.53913
  Classification -> best τ=0.785 (val F1=0.1152)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[74/88] Processing SRE...

Processing SRE (Utilities)...
  Epoch 010 - train 0.62920 | val 1.37142
  Epoch 016 - train 0.58331 | val 1.88132
  Classification -> best τ=0.355 (val F1=0.1515)
  Directional -> Accuracy: 0.4949, MCC: 0.0060, F1: 0.4186

[75/88] Processing T...


[I 2026-02-26 07:43:37,762] Trial 57 finished with value: 0.15253182238230426 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 20, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.00138201931097663, 'weight_decay': 7.809524600310047e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 20, 'huber_delta': 1.640449832002117, 'early_stopping_min_delta': 0.005515693617148428}. Best is trial 53 with value: 0.15712278789285605.

  Epoch 016 - train 0.59523 | val 2.04949
  Classification -> best τ=0.440 (val F1=0.1508)
  Directional -> Accuracy: 0.5303, MCC: 0.0650, F1: 0.5792

================================================================================
Pipeline completed: 88/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (88, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.15253182238230426
Saved Optuna results to ../results/benchmarking/classification/optuna_tuning_base_1H.csv