# Benchmarking Results from Classification and Regression

#### Set Up

In [1]:
import pandas as pd
import numpy as np
import site
import os

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import TimeSeriesSplit
from sklearn.utils.class_weight import compute_class_weight

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader
from torch.optim import Adam
from torch.optim.lr_scheduler import ReduceLROnPlateau
from contextlib import nullcontext

import random

from unicodedata import bidirectional

### Utility Classes and Functions

In [3]:
def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

# Datasets
class SequenceDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

class OrdinalSequenceDataset(Dataset):
    def __init__(self, X, T):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.T = torch.tensor(T, dtype=torch.float32)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.T[idx]

def make_cumulative_targets(y_int, K):
    y = y_int.reshape(-1, 1)
    ks = np.arange(K-1).reshape(1, -1)
    return (y > ks).astype(np.float32)

def decode_ordinal(probs, thr=0.5):
    return (probs >= thr).sum(axis=1)

# Models
class OrdinalHeadCORN(nn.Module):
    def __init__(self, in_dim, K):
        super().__init__()
        self.fc = nn.Linear(in_dim, K-1)

    def forward(self, h):
        return self.fc(h)


class OrdinalHeadCORAL(nn.Module):
    def __init__(self, in_dim, K):
        super().__init__()
        self.w = nn.Linear(in_dim, 1, bias=False)
        self._beta = nn.Parameter(torch.zeros(K-1))
        self.softplus = nn.Softplus()

    def forward(self, h):
        base = self.w(h)
        deltas = self.softplus(self._beta)
        b = torch.cumsum(deltas, dim=0)
        return base - b



class RNNHead(nn.Module):
    # Shared head:
    #   - RNN stack (LSTM/GRU, uni/bi)
    #   - BatchNorm + Dense(32, ReLU) + Dropout
    #   - Output layer (1 unit): linear (regression) or logits (classification)
    def __init__(self, input_size, rnn_type='LSTM', bidirectional=False, problem_type='classification',
                 n_classes=6, ordinal_head='coral', hidden1=128, hidden2=64, num_layers=1,
                 inter_rnn_drop=0.1, dropout=0.3, use_layernorm=False):
        super().__init__()
        self.problem_type = problem_type
        self.bidirectional = bidirectional
        self.rnn_type = rnn_type.upper()
        self.n_classes = n_classes
        self.ordinal_head = ordinal_head
        self.num_layers = int(num_layers)
        self.hidden1 = int(hidden1)
        self.hidden2 = int(hidden2)

        if self.num_layers not in (1, 2):
            raise ValueError("num_layers must be 1 or 2")

        rnn_cls = {'LSTM': nn.LSTM, 'GRU': nn.GRU}[('GRU' if 'GRU' in self.rnn_type else 'LSTM')]

        self.rnn1 = rnn_cls(
            input_size=input_size, hidden_size=self.hidden1, num_layers=1,
            batch_first=True, dropout=0.0, bidirectional=bidirectional
        )

        self.inter_rnn_drop = nn.Dropout(float(inter_rnn_drop))

        self.rnn2 = None
        if self.num_layers == 2:
            self.rnn2 = rnn_cls(
                input_size=self.hidden1*(2 if bidirectional else 1), hidden_size=self.hidden2, num_layers=1,
                batch_first=True, dropout=0.0, bidirectional=bidirectional
            )
            feat_dim = self.hidden2*(2 if bidirectional else 1)
        else:
            feat_dim = self.hidden1*(2 if bidirectional else 1)

        if use_layernorm:
            self.bn = nn.LayerNorm(feat_dim)
        else:
            self.bn = nn.BatchNorm1d(feat_dim)
        self.fc = nn.Linear(feat_dim, 32)
        self.drop = nn.Dropout(float(dropout))
        if self.problem_type == 'multiclass':
            head = self.ordinal_head.lower() if isinstance(self.ordinal_head, str) else 'coral'
            if head == 'corn':
                self.out = OrdinalHeadCORN(32, self.n_classes)
            else:
                self.out = OrdinalHeadCORAL(32, self.n_classes)
        else:
            self.out = nn.Linear(32, 1)

    def forward(self, x):
        # x: [B, T, F]
        out, _ = self.rnn1(x)
        if self.num_layers == 2:
            out = self.inter_rnn_drop(out)   # inter-layer dropout (sequence-wise)
            out, _ = self.rnn2(out)
        # take last timestep: [B, T, H] -> [B, H]
        out = out[:, -1, :]
        out = self.bn(out)
        out = F.relu(self.fc(out))
        out = self.drop(out)
        out = self.out(out)  # shape [B,1]
        return out  # regression: raw; classification: logits


def build_model(input_shape, model_type='LSTM', problem_type='regression', n_classes=6, ordinal_head='coral',
                hidden1=128, hidden2=64, num_layers=2, inter_rnn_drop=0.1, dropout=0.3, use_layernorm=False):
    seq_len, n_features = input_shape
    model_type = model_type.upper()
    kwargs = dict(
        problem_type=problem_type,
        n_classes=n_classes,
        ordinal_head=ordinal_head,
        hidden1=hidden1,
        hidden2=hidden2,
        num_layers=num_layers,
        inter_rnn_drop=inter_rnn_drop,
        dropout=dropout,
        use_layernorm=use_layernorm,
    )
    if model_type == 'LSTM':
        return RNNHead(n_features, rnn_type='LSTM', bidirectional=False, **kwargs)
    elif model_type == 'BILSTM':
        return RNNHead(n_features, rnn_type='LSTM', bidirectional=True, **kwargs)
    elif model_type == 'GRU':
        return RNNHead(n_features, rnn_type='GRU', bidirectional=False, **kwargs)
    elif model_type == 'BIGRU':
        return RNNHead(n_features, rnn_type='GRU', bidirectional=True, **kwargs)
    else:
        raise ValueError("Model type must be one of: ['LSTM','BiLSTM','GRU','BiGRU']")

# Early Stopping (PyTorch)
class EarlyStopper:
    def __init__(self, patience=15, min_delta=0.0, restore_best=True):
        self.patience = patience
        self.min_delta = min_delta
        self.restore_best = restore_best
        self.best_loss = float('inf')
        self.counter = 0
        self.best_state = None

    def step(self, val_loss, model):
        improved = (self.best_loss - val_loss) > self.min_delta
        if improved:
            self.best_loss = val_loss
            self.counter = 0
            if self.restore_best:
                # Deep copy state dict
                self.best_state = {k: v.detach().clone() for k, v in model.state_dict().items()}
        else:
            self.counter += 1
        return self.counter >= self.patience

    def restore(self, model):
        if self.restore_best and self.best_state is not None:
            model.load_state_dict(self.best_state)

In [4]:
def edge_labels_from_edges(edges, decimals=1):
    labels = []
    C = len(edges) - 1
    for i in range(C):
        lo, hi = edges[i], edges[i+1]
        if i == 0:
            labels.append(f"≤ {hi*100:.{decimals}f}%")
        elif i == C - 1:
            labels.append(f"> {lo*100:.{decimals}f}%")
        else:
            labels.append(f"({lo*100:.{decimals}f}%,{hi*100:.{decimals}f}%]")
    return labels

def pct_return(series, h):
    return series.shift(-h) / series - 1.0

def safe_quantile_edges(x, n_classes=6):
    qs = np.linspace(0, 1, n_classes + 1)
    edges = np.quantile(x, qs)
    for i in range(1, len(edges)):
        if edges[i] <= edges[i-1]:
            edges[i] = np.nextafter(edges[i-1], np.inf)
    return edges

def bucketize_with_edges(x, edges):
    inner = edges[1:-1]
    return np.digitize(x, inner, right=True).astype(int)

@torch.no_grad()
def collect_logits(model, loader, device):
    model.eval()
    chunks = []
    for xb, _ in loader:
        xb = xb.to(device)
        chunks.append(model(xb).detach().cpu())
    return torch.cat(chunks, dim=0)

def find_taus_per_threshold(Z_val, y_val_idx, grid=np.linspace(0, 1, 100)):
    if isinstance(Z_val, torch.Tensor):
        Z_val = Z_val.numpy()
    P_val = 1.0 / (1.0 + np.exp(-Z_val))
    P_rep = monotone_repair_numpy(P_val)
    K_1 = P_rep.shape[1]
    best_taus = np.full(K_1, 0.5, dtype=np.float32)
    for k in range(K_1):
        best_f1, best_tau = -1.0, 0.5
        for tau in grid:
            y_hat = decode_ordinal_with_taus(P_rep, taus_override={k: tau})
            f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
            if f1 > best_f1:
                best_f1, best_tau = f1, tau
        best_taus[k] = best_tau
    return best_taus

def monotone_repair_numpy(P):
    P = np.asarray(P).copy()
    for k in range(P.shape[1] - 2, -1, -1):
        P[:, k] = np.maximum(P[:, k], P[:, k+1])
    return P

def decode_ordinal_with_taus(P_rep, taus=None, taus_override=None):
    N, K_1 = P_rep.shape
    if taus is None:
        taus = np.full(K_1, 0.5, dtype=np.float32)
    if taus_override:
        taus = taus.copy()
        for k, v in taus_override.items():
            taus[k] = v
    comp = (P_rep >= taus.reshape(1, -1)).astype(np.int32)
    return comp.sum(axis=1).astype(np.int64)

def ordinal_to_class_probs(P_rep):
    N, K_1 = P_rep.shape
    K = K_1 + 1
    Pc = np.empty((N, K), dtype=np.float32)
    Pc[:, 0] = 1.0 - P_rep[:, 0]
    for c in range(1, K - 1):
        Pc[:, c] = np.clip(P_rep[:, c-1] - P_rep[:, c], 0.0, 1.0)
    Pc[:, K - 1] = P_rep[:, K_1 - 1]
    s = Pc.sum(axis=1, keepdims=True)
    return Pc / np.maximum(s, 1e-8)


def best_threshold_from_val(y_true, y_scores, metric='f1', grid=None):
    """
    Sweep probability thresholds on validation scores to maximize a metric.
    metric can be 'f1', 'mcc', 'accuracy', or a callable(y_true,y_pred)->float.
    Returns (best_threshold, best_metric_value).
    """
    y_true = np.asarray(y_true).astype(int)
    y_scores = np.asarray(y_scores).astype(float)
    if grid is None:
        grid = np.linspace(0.05, 0.95, 181)
    metric_fn = None
    if callable(metric):
        metric_fn = metric
    else:
        name = str(metric).lower()
        if name == 'f1':
            metric_fn = lambda yt, yp: f1_score(yt, yp, zero_division=0)
        elif name == 'mcc':
            metric_fn = lambda yt, yp: matthews_corrcoef(yt, yp)
        elif name in ('acc', 'accuracy'):
            metric_fn = lambda yt, yp: (yt == yp).mean()
        else:
            raise ValueError(f"Unsupported metric '{metric}'")
    best_thr = 0.5
    best_val = -np.inf
    for thr in grid:
        preds = (y_scores >= thr).astype(int)
        val = metric_fn(y_true, preds)
        if val > best_val + 1e-12 or (abs(val - best_val) <= 1e-12 and thr < best_thr):
            best_val = float(val)
            best_thr = float(thr)
    return best_thr, best_val

## Stock Prediction Pipeline

In [5]:
class StockPredictionPipeline:
    def __init__(self, df, feature_columns, model_type='LSTM', sequence_length=24, problem_type='regression', horizon_steps=1, n_classes=6, ordinal_head='coral', fixed_bucket_edges=None,
                 hidden1=256, hidden2=64, num_layers=1, inter_rnn_drop=0.0, dropout=0.4,
                 batch_size=32, learning_rate=7e-3, weight_decay=2e-3, lr_patience=7, lr_factor=0.5,
                 early_stopping_patience=20, max_epochs=20, use_layernorm=False, huber_delta=1.0, early_stopping_min_delta=0.0):
        self.df = df.copy()
        self.feature_columns = feature_columns
        self.model_type = model_type
        self.sequence_length = sequence_length
        self.problem_type = problem_type
        self.horizon_steps = horizon_steps
        self.results = []
        self.loss_curves = []
        self.n_classes = n_classes
        self.ordinal_head = ordinal_head
        self.hidden1 = hidden1
        self.hidden2 = hidden2
        self.num_layers = num_layers
        self.inter_rnn_drop = inter_rnn_drop
        self.dropout = dropout
        self.batch_size = batch_size
        self.learning_rate = learning_rate
        self.weight_decay = weight_decay
        self.lr_patience = lr_patience
        self.lr_factor = lr_factor
        self.early_stopping_patience = early_stopping_patience
        self.max_epochs = max_epochs
        self.use_layernorm = use_layernorm
        self.huber_delta = huber_delta
        self.early_stopping_min_delta = early_stopping_min_delta
        self.fixed_bucket_edges = None
        if fixed_bucket_edges is not None:
            edges = np.asarray(fixed_bucket_edges, dtype=float)
            if edges.ndim != 1:
                raise ValueError("fixed_bucket_edges must be a 1D sequence of monotonically increasing numbers")
            if edges.size < 2:
                raise ValueError("fixed_bucket_edges must contain at least two values")
            if np.any(np.diff(edges) <= 0):
                raise ValueError("fixed_bucket_edges must be strictly increasing")
            self.n_classes = int(edges.size - 1)
            self.fixed_bucket_edges = edges

        # Validate
        self._validate_inputs()

        # Device & precision
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.mixed_precision = torch.cuda.is_available()

        print(f"Pipeline initialized for a '{self.problem_type}' problem "
              f"with horizon {self.horizon_steps} steps. Device: {self.device}")

    def _validate_inputs(self):
        missing_cols = [col for col in self.feature_columns if col not in self.df.columns]
        if missing_cols:
            raise ValueError(f"Missing feature columns: {missing_cols}")

        if 'close' not in self.df.columns and 'close_price' not in self.df.columns:
            raise ValueError("No 'close' or 'close_price' column found in data")

        valid_models = ['LSTM', 'BiLSTM', 'GRU', 'BiGRU']
        if self.model_type not in valid_models:
            raise ValueError(f"Model type must be one of: {valid_models}")

        if self.problem_type not in ['regression', 'classification', 'multiclass']:
            raise ValueError("Problem type must be 'regression', 'classification', or 'multiclass'")

    def create_target_variable(self, company_data):
        company_data = company_data.copy()
        price_col = 'close' if 'close' in company_data.columns else 'close_price'
        if 'date' in company_data.columns:
            company_data = company_data.sort_values('date')
            
        h = self.horizon_steps

        company_data['target_regression'] = (
            np.log(company_data[price_col].shift(-h)) - np.log(company_data[price_col])
        )
        company_data['target_direction'] = (company_data['target_regression'] > 0).astype(int)
        company_data['ret_h'] = pct_return(company_data[price_col], h)
        if self.problem_type == 'multiclass':
            company_data = company_data.dropna(subset=['ret_h'])
        else:
            company_data = company_data.dropna()
        return company_data

    def create_sequences(self, features, *targets):
        X = []
        y_sequences = [[] for _ in targets]
        for i in range(self.sequence_length, len(features)):
            X.append(features[i-self.sequence_length:i])
            for j, target in enumerate(targets):
                y_sequences[j].append(target[i])
        return (np.array(X),) + tuple(np.array(y) for y in y_sequences)

    def _train_one_epoch(self, model, loader, optimizer, loss_fn, scaler):
        model.train()
        total_loss = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device).view(-1, 1)

            optimizer.zero_grad(set_to_none=True)

            ctx = torch.amp.autocast('cuda') if self.mixed_precision else nullcontext()
            with ctx:
                logits = model(xb)
                loss = loss_fn(logits, yb)

            if self.mixed_precision:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                optimizer.step()

            total_loss += loss.item() * xb.size(0)

        return total_loss / len(loader.dataset)

    @torch.no_grad()
    def _eval_one_epoch(self, model, loader, loss_fn):
        model.eval()
        total_loss = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device).view(-1, 1)
            logits = model(xb)
            loss = loss_fn(logits, yb)
            total_loss += loss.item() * xb.size(0)
        return total_loss / len(loader.dataset)

    def _train_one_epoch_multiclass(self, model, loader, optimizer, scaler, *, pos_weight=None):
        model.train()
        total = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device)
            optimizer.zero_grad(set_to_none=True)
            ctx = torch.amp.autocast('cuda') if self.mixed_precision else nullcontext()
            with ctx:
                logits = model(xb)
                bces = []
                for k in range(logits.shape[1]):
                    w = None if pos_weight is None else pos_weight[k]
                    bce_k = F.binary_cross_entropy_with_logits(logits[:, k], yb[:, k], pos_weight=w)
                    bces.append(bce_k)
                loss = torch.stack(bces).mean()
            if self.mixed_precision:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
            total += float(loss.item()) * xb.size(0)
        return total / len(loader.dataset)

    @torch.no_grad()
    def _eval_one_epoch_multiclass(self, model, loader, pos_weight=None):
        model.eval()
        total = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device)
            logits = model(xb)
            bces = []
            for k in range(logits.shape[1]):
                w = None if pos_weight is None else pos_weight[k]
                bce_k = F.binary_cross_entropy_with_logits(logits[:, k], yb[:, k], pos_weight=w)
                bces.append(bce_k)
            loss = torch.stack(bces).mean()
            total += float(loss.item()) * xb.size(0)
        return total / len(loader.dataset)

    @torch.no_grad()
    def _predict(self, model, loader):
        model.eval()
        outs = []
        for xb, _ in loader:
            xb = xb.to(self.device)
            logits = model(xb).squeeze(1).detach().cpu().numpy()
            outs.append(logits)
        return np.concatenate(outs, axis=0)

    def build_model(self, input_shape):
        model = build_model(
            input_shape,
            model_type=self.model_type,
            problem_type=self.problem_type,
            n_classes=self.n_classes,
            ordinal_head=self.ordinal_head,
            hidden1=self.hidden1,
            hidden2=self.hidden2,
            num_layers=self.num_layers,
            inter_rnn_drop=self.inter_rnn_drop,
            dropout=self.dropout,
            use_layernorm=self.use_layernorm
        )
        return model.to(self.device)

    def process_company(self, company_name, company_data, sector):
        print(f"\nProcessing {company_name} ({sector})...")
        try:
            company_data = self.create_target_variable(company_data)

            # Min samples requirement (same heuristic)
            min_samples = self.sequence_length + 75 + self.horizon_steps
            if len(company_data) < min_samples:
                print(f"Insufficient data for {company_name} ({len(company_data)} < {min_samples}). Skipping...")
                return None

            if company_data[self.feature_columns].isnull().any().any():
                print(f"Missing values in features for {company_name}. Skipping...")
                return None

            features = company_data[self.feature_columns].values
            target_reg = company_data['target_regression'].values
            target_dir = company_data['target_direction'].values

            # Create sequences
            X_raw, y_reg, y_dir = self.create_sequences(features, target_reg, target_dir)

            # TimeSeriesSplit
            n_splits = min(5, len(X_raw) // 50)
            if n_splits < 3:
                print(f"Insufficient data for proper time series validation for {company_name}. Skipping...")
                return None

            tscv = TimeSeriesSplit(n_splits=n_splits)
            splits = list(tscv.split(X_raw))
            train_idx, test_idx = splits[-1]

            # Train/Val split (last 20% of train for val)
            val_size = int(0.2 * len(train_idx))
            if val_size == 0:
                print(f'Insufficient data for validation split for {company_name}. Skipping...')
                return None
            final_train_idx = train_idx[:-val_size]
            val_idx = train_idx[-val_size:]
            
            if self.horizon_steps > 1:
                print("Adjusting for multi-step horizon...")
                gap = self.horizon_steps
                if len(final_train_idx) > gap:
                    final_train_idx = final_train_idx[:-gap]  # drop last h labels from train
                if len(val_idx) > gap:
                    val_idx = val_idx[gap:]  # drop last h labels from val
            if len(final_train_idx) == 0 or len(val_idx) == 0:
                print(f'Insufficient data after horizon adjustment for {company_name}. Skipping...')
                return None

            X_train_raw, X_val_raw, X_test_raw = X_raw[final_train_idx], X_raw[val_idx], X_raw[test_idx]
            
            F = X_raw.shape[-1]
            feat_scaler = StandardScaler()
            X_train = feat_scaler.fit_transform(X_train_raw.reshape(-1, F)).reshape(X_train_raw.shape)
            X_val   = feat_scaler.transform(X_val_raw.reshape(-1, F)).reshape(X_val_raw.shape)
            X_test  = feat_scaler.transform(X_test_raw.reshape(-1, F)).reshape(X_test_raw.shape)

            if self.problem_type == 'multiclass':
                if 'ret_h' not in company_data.columns:
                    raise RuntimeError("Expected 'ret_h' for ordinal targets but it was missing.")
                ret_full = company_data['ret_h'].values
                ret_seq_full = ret_full[self.sequence_length:]

                ret_train = ret_seq_full[final_train_idx]
                ret_val = ret_seq_full[val_idx]
                ret_test = ret_seq_full[test_idx]

                if self.fixed_bucket_edges is not None:
                    edges = self.fixed_bucket_edges
                    if int(edges.shape[0] - 1) != self.n_classes:
                        raise ValueError("fixed_bucket_edges length must match n_classes+1")
                else:
                    edges = safe_quantile_edges(ret_train, n_classes=self.n_classes)
                edges = np.asarray(edges, dtype=float)
                K = int(edges.shape[0] - 1)
                label_names = edge_labels_from_edges(edges, decimals=1)

                y_bucket = bucketize_with_edges(ret_seq_full, edges).astype(np.int64)
                y_train = y_bucket[final_train_idx]
                y_val = y_bucket[val_idx]
                y_test = y_bucket[test_idx]

                T_train = make_cumulative_targets(y_train.astype(np.int64), K)
                T_val = make_cumulative_targets(y_val.astype(np.int64), K)
                T_test = make_cumulative_targets(y_test.astype(np.int64), K)

                train_ds = OrdinalSequenceDataset(X_train, T_train)
                val_ds = OrdinalSequenceDataset(X_val, T_val)
                test_ds = OrdinalSequenceDataset(X_test, T_test)

                train_loader = DataLoader(train_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)
                val_loader = DataLoader(val_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)
                test_loader = DataLoader(test_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)

                model = self.build_model((self.sequence_length, len(self.feature_columns)))

                pos_rate = T_train.mean(axis=0)
                pos_weight = (1.0 - pos_rate) / np.clip(pos_rate, 1e-6, 1.0)
                pos_weight_tensor = torch.tensor(pos_weight, dtype=torch.float32).to(self.device)

                optimizer = Adam(model.parameters(), lr=self.learning_rate, eps=1e-7, weight_decay=self.weight_decay)
                scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=self.lr_factor, patience=self.lr_patience, min_lr=1e-7)
                early_stopper = EarlyStopper(patience=self.early_stopping_patience, min_delta=self.early_stopping_min_delta, restore_best=True)
                scaler = torch.amp.GradScaler('cuda', enabled=self.mixed_precision)

                max_epochs = self.max_epochs
                best_val = float('inf')
                epochs_trained = 0
                company_loss_rows = []

                for epoch in range(1, max_epochs + 1):
                    train_loss = self._train_one_epoch_multiclass(model, train_loader, optimizer, scaler, pos_weight=pos_weight_tensor)
                    val_loss = self._eval_one_epoch_multiclass(model, val_loader, pos_weight=pos_weight_tensor)
                    scheduler.step(val_loss)
                    stop = early_stopper.step(val_loss, model)
                    epochs_trained = epoch

                    row = {
                        'company': company_name,
                        'sector': sector,
                        'model_type': self.model_type,
                        'problem_type': self.problem_type,
                        'sequence_length': self.sequence_length,
                        'horizon_steps': self.horizon_steps,
                        'epoch': epoch,
                        'train_loss': float(train_loss),
                        'val_loss': float(val_loss),
                        'train_samples': len(X_train),
                        'val_samples': len(X_val),
                        'test_samples': len(X_test),
                    }

                    company_loss_rows.append(row)
                    self.loss_curves.append(row)

                    if epoch % 10 == 0 or stop:
                        print(f"  Epoch {epoch:03d} - train {train_loss:.5f} | val {val_loss:.5f}")

                    if stop:
                        break

                early_stopper.restore(model)

                Z_val = collect_logits(model, val_loader, self.device)
                taus = find_taus_per_threshold(Z_val, y_val.astype(np.int64))
                P_cum_val = torch.sigmoid(Z_val).cpu().numpy()
                P_rep_val = monotone_repair_numpy(P_cum_val)
                P_class_val = ordinal_to_class_probs(P_rep_val)
                mid_cut = (K // 2)
                y_val_dir = (y_val >= mid_cut).astype(int)
                prob_val_up = P_class_val[:, mid_cut:].sum(axis=1)
                dir_thr, dir_thr_score = best_threshold_from_val(y_val_dir, prob_val_up, metric='mcc')

                Z_test = collect_logits(model, test_loader, self.device)
                P_cum = torch.sigmoid(Z_test).cpu().numpy()
                P_rep = monotone_repair_numpy(P_cum)
                P_class = ordinal_to_class_probs(P_rep)

                y_pred_labels = decode_ordinal_with_taus(P_rep, taus=taus)
                y_true_labels = y_test

                labels = list(range(K))
                cm_counts = confusion_matrix(y_true_labels, y_pred_labels, labels=labels)
                cm_norm = confusion_matrix(y_true_labels, y_pred_labels, labels=labels, normalize='true')

                micro_acc = (y_true_labels == y_pred_labels).mean()
                macro_f1 = f1_score(y_true_labels, y_pred_labels, average='macro', zero_division=0)

                ret_seq_train = ret_seq_full[final_train_idx].astype(np.float32)
                mu_c = np.array([
                    ret_seq_train[y_train == c].mean() if np.any(y_train == c) else 0.0
                    for c in range(K)
                ], dtype=np.float32)

                expected_ret = (P_class * mu_c[None, :]).sum(axis=1)
                expected_ret_mean = float(expected_ret.mean())

                prob_test_up = P_class[:, mid_cut:].sum(axis=1)
                y_true_dir = (y_true_labels >= mid_cut).astype(int)
                y_pred_dir = (prob_test_up >= dir_thr).astype(int)
                precision = precision_score(y_true_dir, y_pred_dir, zero_division=0)
                recall = recall_score(y_true_dir, y_pred_dir, zero_division=0)
                f1 = f1_score(y_true_dir, y_pred_dir, zero_division=0)
                mcc = matthews_corrcoef(y_true_dir, y_pred_dir)
                directional_accuracy = (y_true_dir == y_pred_dir).mean()

                result = {
                    'company': company_name,
                    'sector': sector,
                    'model_type': self.model_type,
                    'problem_type': self.problem_type,
                    'horizon_steps': self.horizon_steps,
                    'macro_f1': macro_f1,
                    'micro_accuracy': micro_acc,
                    'expected_return_mean': expected_ret_mean,
                    'mse': np.nan,
                    'mae': np.nan,
                    'r2': np.nan,
                    'mcc': mcc,
                    'f1': f1,
                    'precision': precision,
                    'recall': recall,
                    'directional_accuracy': directional_accuracy,
                'val_directional_accuracy': val_directional_accuracy if self.problem_type == 'classification' else np.nan,
                'val_mcc': val_mcc if self.problem_type == 'classification' else np.nan,
                'val_f1': val_f1 if self.problem_type == 'classification' else np.nan,
                'val_precision': val_precision if self.problem_type == 'classification' else np.nan,
                'val_recall': val_recall if self.problem_type == 'classification' else np.nan,
                    'n_samples': int(X_raw.shape[0]),
                    'train_samples': int(X_train.shape[0]),
                    'val_samples': int(X_val.shape[0]),
                    'test_samples': int(X_test.shape[0]),
                    'epochs_trained': epochs_trained
                }
                result['confusion_matrix'] = cm_counts.tolist()
                result['confusion_matrix_normalized'] = cm_norm.tolist()
                result['bucket_edges'] = edges.tolist()
                result['bucket_labels'] = label_names
                result['taus'] = taus.astype(float).tolist()
                result['direction_threshold'] = dir_thr
                result['direction_threshold_metric'] = dir_thr_score

                print(f"  Multiclass -> Micro Acc: {micro_acc:.4f}, Macro F1: {macro_f1:.4f}, Expected Return: {expected_ret_mean:.6f}")
                print(f"  Directional threshold -> τ={dir_thr:.3f} (val F1={dir_thr_score:.4f})")

                del model
                torch.cuda.empty_cache()
                return result

            if self.problem_type == 'regression':
                y_train, y_val, y_test = y_reg[final_train_idx], y_reg[val_idx], y_reg[test_idx]
                target_scaler = StandardScaler()
                y_train_scaled = target_scaler.fit_transform(y_train.reshape(-1, 1)).flatten()
                y_val_scaled   = target_scaler.transform(y_val.reshape(-1, 1)).flatten()
                train_target, val_target = y_train_scaled, y_val_scaled
            else:
                y_train, y_val, y_test = y_dir[final_train_idx], y_dir[val_idx], y_dir[test_idx]
                train_target, val_target = y_train, y_val
                target_scaler = None

            # class balance note
            if self.problem_type == 'classification':
                class_ratio = np.mean(y_train)
                if class_ratio < 0.1 or class_ratio > 0.9:
                    print(f"Severe class imbalance for {company_name} ({class_ratio:.3f}). Consider using class weights.")

            # datasets & loaders
            train_ds = SequenceDataset(X_train, train_target)
            val_ds   = SequenceDataset(X_val,   val_target)
            test_ds  = SequenceDataset(X_test,  y_test)

            train_bs = min(self.batch_size, len(train_ds))
            if train_bs < 2:
                print(f'Insufficient training samples for {company_name} (train size={len(train_ds)}). Skipping...')
                return None
            if len(train_ds) % train_bs == 1 and train_bs > 2:
                train_bs -= 1  # avoid batch size 1 for BatchNorm
            val_bs = min(self.batch_size, len(val_ds))
            test_bs = min(self.batch_size, len(test_ds))

            train_loader = DataLoader(train_ds, batch_size=train_bs, shuffle=False,  drop_last=False, num_workers=0)
            val_loader   = DataLoader(val_ds,   batch_size=val_bs,   shuffle=False, drop_last=False, num_workers=0)
            test_loader  = DataLoader(test_ds,  batch_size=test_bs,  shuffle=False, drop_last=False, num_workers=0)

            # build model
            model = self.build_model((self.sequence_length, len(self.feature_columns)))

            # loss functions
            if self.problem_type == 'regression':
                loss_fn = nn.HuberLoss(delta=self.huber_delta)
            else:
                # use BCEWithLogitsLoss for numerical stability (logits input)
                loss_fn = nn.BCEWithLogitsLoss()

            # optimizer & scheduler
            optimizer = Adam(model.parameters(), lr=self.learning_rate, eps=1e-7, weight_decay=self.weight_decay)
            scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=self.lr_factor, patience=self.lr_patience, min_lr=1e-7)
            early_stopper = EarlyStopper(patience=self.early_stopping_patience, min_delta=self.early_stopping_min_delta, restore_best=True)
            scaler = torch.amp.GradScaler('cuda', enabled=self.mixed_precision)

            # training loop
            max_epochs = self.max_epochs
            best_val = float('inf')
            epochs_trained = 0
            company_loss_rows = []  

            for epoch in range(1, max_epochs + 1):
                train_loss = self._train_one_epoch(model, train_loader, optimizer, loss_fn, scaler)
                val_loss = self._eval_one_epoch(model, val_loader, loss_fn)
                scheduler.step(val_loss)
                stop = early_stopper.step(val_loss, model)
                epochs_trained = epoch

                
                row = {
                    'company': company_name,
                    'sector': sector,
                    'model_type': self.model_type,
                    'problem_type': self.problem_type,
                    'sequence_length': self.sequence_length,
                    'horizon_steps': self.horizon_steps,
                    'epoch': epoch,
                    'train_loss': float(train_loss),
                    'val_loss': float(val_loss),
                    'train_samples': len(X_train),
                    'val_samples': len(X_val),
                    'test_samples': len(X_test),
                }
                
                company_loss_rows.append(row)
                self.loss_curves.append(row)

                if epoch % 10 == 0 or stop:
                    print(f"  Epoch {epoch:03d} - train {train_loss:.5f} | val {val_loss:.5f}")

                if stop:
                    break

            # restore best model weights (like Keras restore_best_weights=True)
            early_stopper.restore(model)

            # summarize train/val loss for overfitting checks
            best_train_loss = np.nan
            best_val_loss = np.nan
            final_train_loss = np.nan
            final_val_loss = np.nan
            if company_loss_rows:
                best_val_loss = min(r['val_loss'] for r in company_loss_rows)
                best_train_loss = min(r['train_loss'] for r in company_loss_rows)
                final_train_loss = company_loss_rows[-1]['train_loss']
                final_val_loss = company_loss_rows[-1]['val_loss']

            # predictions
            y_pred_raw = self._predict(model, test_loader)  # raw/regression or logits

            if self.problem_type == 'regression':
                y_pred_unscaled = target_scaler.inverse_transform(y_pred_raw.reshape(-1,1)).flatten() if target_scaler is not None else y_pred_raw
                mse = mean_squared_error(y_test, y_pred_unscaled)
                mae = mean_absolute_error(y_test, y_pred_unscaled)
                r2  = r2_score(y_test, y_pred_unscaled)

                # directional metrics (derived)
                y_test_dir = (y_reg[test_idx] > 0).astype(int)
                y_pred_dir = (y_pred_unscaled > 0).astype(int)
            else:
                # logits -> probs via sigmoid -> learn best threshold on VAL
                val_logits = self._predict(model, val_loader)
                val_probs = 1.0 / (1.0 + np.exp(-val_logits))
                best_thr, best_thr_score = best_threshold_from_val(y_val, val_probs, metric='mcc')
                val_pred_dir = (val_probs >= best_thr).astype(int)
                val_precision = precision_score(y_val, val_pred_dir, zero_division=0)
                val_recall = recall_score(y_val, val_pred_dir, zero_division=0)
                val_f1 = f1_score(y_val, val_pred_dir, zero_division=0)
                val_mcc = matthews_corrcoef(y_val, val_pred_dir)
                val_directional_accuracy = (y_val == val_pred_dir).mean()
                probs = 1.0 / (1.0 + np.exp(-y_pred_raw))
                y_pred_dir = (probs >= best_thr).astype(int)
                y_test_dir = y_test
                mse = mae = r2 = np.nan

            precision = precision_score(y_test_dir, y_pred_dir, zero_division=0)
            recall    = recall_score(y_test_dir, y_pred_dir, zero_division=0)
            f1        = f1_score(y_test_dir, y_pred_dir, zero_division=0)
            mcc       = matthews_corrcoef(y_test_dir, y_pred_dir)
            directional_accuracy = np.mean(y_test_dir == y_pred_dir)

            result = {
                'company': company_name,
                'sector': sector,
                'model_type': self.model_type,
                'problem_type': self.problem_type,
                'horizon_steps': self.horizon_steps,
                'mse': mse,
                'mae': mae,
                'r2': r2,
                'mcc': mcc,
                'f1': f1,
                'precision': precision,
                'recall': recall,
                'directional_accuracy': directional_accuracy,
                'val_directional_accuracy': val_directional_accuracy if self.problem_type == 'classification' else np.nan,
                'val_mcc': val_mcc if self.problem_type == 'classification' else np.nan,
                'val_f1': val_f1 if self.problem_type == 'classification' else np.nan,
                'val_precision': val_precision if self.problem_type == 'classification' else np.nan,
                'val_recall': val_recall if self.problem_type == 'classification' else np.nan,
                'n_samples': int(X_raw.shape[0]),
                'train_samples': int(X_train.shape[0]),
                'val_samples': int(X_val.shape[0]),
                'test_samples': int(X_test.shape[0]),
                'epochs_trained': epochs_trained
            }
            if self.problem_type == 'classification':
                result['best_threshold'] = best_thr
                result['best_threshold_metric'] = best_thr_score

            if self.problem_type == 'regression':
                print(f"  Regression -> MSE: {mse:.6f}, MAE: {mae:.6f}, R²: {r2:.4f}")
            elif self.problem_type == 'classification':
                print(f"  Classification -> best τ={best_thr:.3f} (val F1={best_thr_score:.4f})")
            print(f"  Directional -> Accuracy: {directional_accuracy:.4f}, MCC: {mcc:.4f}, F1: {f1:.4f}")

            # explicit cleanup (PyTorch handles this, but keeps parity with Enrique2025)
            del model
            torch.cuda.empty_cache()

            return result

        except Exception as e:
            print(f"Error processing {company_name}: {str(e)}")
            torch.cuda.empty_cache()
            return None

    def run_pipeline(self):
        company_col = None
        for col_name in ['ticker', 'company', 'symbol']:
            if col_name in self.df.columns:
                company_col = col_name
                break
        if company_col is None:
            company_col = self.df.columns[0]
            print(f"Warning: Using '{company_col}' as company identifier column")

        companies = self.df[company_col].unique()
        print(f"Processing {len(companies)} companies with {self.model_type} model...")
        print(f"Problem type: {self.problem_type}")
        print(f"Sequence length: {self.sequence_length}")
        print(f"Features: {self.feature_columns}")

        successful_companies = 0
        for i, company in enumerate(companies, 1):
            print(f"\n[{i}/{len(companies)}] Processing {company}...")
            company_data = self.df[self.df[company_col] == company].copy()
            sector = company_data['sector'].iloc[0] if 'sector' in company_data.columns else 'Unknown'
            result = self.process_company(company, company_data, sector)
            if result:
                self.results.append(result)
                successful_companies += 1

        print(f"\n{'='*80}")
        print(f"Pipeline completed: {successful_companies}/{len(companies)} companies processed successfully")
        print(f"{'='*80}")

        if self.results:
            self.results_df = pd.DataFrame(self.results)
            return self.results_df
        else:
            print("No companies were processed successfully!")
            return pd.DataFrame()


    def analyze_results(self):
        if not hasattr(self, 'results_df') or self.results_df.empty:
            print("No results to analyze!")
            return None

        df = self.results_df
        analysis = {}

        print("" + "="*80)
        print("STOCK PREDICTION PIPELINE RESULTS")
        print("="*80)
        print(f"Model: {self.model_type} | Problem: {self.problem_type}")
        print(f"Companies analyzed: {len(df)}")
        print(f"Average samples per company: {df['n_samples'].mean():.0f}")

        print("" + "="*50)
        print("OVERALL PERFORMANCE")
        print("="*50)
        if self.problem_type == 'regression':
            print(f"Mean Squared Error:     {df['mse'].mean():.6f} (±{df['mse'].std():.6f})")
            print(f"Mean Absolute Error:    {df['mae'].mean():.6f} (±{df['mae'].std():.6f})")
            print(f"R² Score:              {df['r2'].mean():.4f} (±{df['r2'].std():.4f})")
        if self.problem_type == 'multiclass' and 'micro_accuracy' in df.columns:
            print(f"Micro Accuracy:         {df['micro_accuracy'].mean():.4f} (±{df['micro_accuracy'].std():.4f})")
            print(f"Macro F1 Score:         {df['macro_f1'].mean():.4f} (±{df['macro_f1'].std():.4f})")
            if 'expected_return_mean' in df.columns:
                print(f"Expected Return:        {df['expected_return_mean'].mean():.6f} (±{df['expected_return_mean'].std():.4f})")

        print(f"Directional Accuracy:   {df['directional_accuracy'].mean():.4f} (±{df['directional_accuracy'].std():.4f})")
        print(f"Matthews Correlation:   {df['mcc'].mean():.4f} (±{df['mcc'].std():.4f})")
        print(f"F1 Score:              {df['f1'].mean():.4f} (±{df['f1'].std():.4f})")
        print(f"Precision:             {df['precision'].mean():.4f} (±{df['precision'].std():.4f})")
        print(f"Recall:                {df['recall'].mean():.4f} (±{df['recall'].std():.4f})")

        if self.problem_type == 'multiclass' and 'expected_return_mean' in df.columns:
            print("" + "="*50)
            print("TOP 10 BY EXPECTED RETURN (mean)")
            print("="*50)
            top_er = df.nlargest(10, 'expected_return_mean')
            for _, row in top_er.iterrows():
                print(f"{row['company']:<20} | {row['sector']:<15} | E[r]_mean: {row['expected_return_mean']:.4e} | Macro-F1: {row['macro_f1']:.3f}")

        if 'sector' in df.columns and df['sector'].nunique() > 1:
            print("" + "="*50)
            print("PERFORMANCE BY SECTOR")
            print("="*50)
            sector_stats = df.groupby('sector').agg({
                'directional_accuracy': ['mean', 'std', 'count'],
                'mcc': ['mean', 'std'],
                'r2': 'mean' if self.problem_type == 'regression' else lambda x: np.nan,
                'mae': 'mean' if self.problem_type == 'regression' else lambda x: np.nan
            }).round(4)
            sector_stats.columns = ['_'.join(col).strip() if col[1] else col[0] for col in sector_stats.columns]
            sector_stats = sector_stats.sort_values('directional_accuracy_mean', ascending=False)
            for sector, row in sector_stats.iterrows():
                print(f"{sector:<20} | Acc: {row['directional_accuracy_mean']:.3f}±{row['directional_accuracy_std']:.3f} | "
                      f"MCC: {row['mcc_mean']:.3f} | Companies: {int(row['directional_accuracy_count'])}")

        print("" + "="*50)
        print("TOP 10 PERFORMERS (by Directional Accuracy)")
        print("="*50)
        top_performers = df.nlargest(10, 'directional_accuracy')
        for _, row in top_performers.iterrows():
            print(f"{row['company']:<20} | {row['sector']:<15} | "
                  f"Acc: {row['directional_accuracy']:.3f} | MCC: {row['mcc']:.3f}")

        return analysis

    def save_results(self, results, output_dir='results/benchmarking'):
        if results is not None and not results.empty:
            model_name = self.model_type

            if self.problem_type == 'regression':
                out_dir = os.path.join(output_dir, 'regression')
            elif self.problem_type == 'classification':
                out_dir = os.path.join(output_dir, 'classification')
            else:
                out_dir = os.path.join(output_dir, 'multiclass')

            os.makedirs(out_dir, exist_ok=True)

            output_path = os.path.join(out_dir, f"{model_name}.csv")

            results.to_csv(output_path, index=False)
            print(f"Results saved to {output_path}")
        else:
            print("No results to save.")
            
    def get_loss_curves_df(self):
        if not self.loss_curves:
            print("No loss curves logged yet.")
            return pd.DataFrame()
        return pd.DataFrame(self.loss_curves)

    def save_loss_curves(self, out_path='results/benchmarking/'):
        df = self.get_loss_curves_df()
        if df.empty:
            print("No loss curves to save.")
            return
        if self.problem_type == 'regression':
            out_path = os.path.join(out_path, 'regression', f"{self.model_type}_loss_curves.csv")
        elif self.problem_type == 'classification':
            out_path = os.path.join(out_path, 'classification', f"{self.model_type}_loss_curves.csv")
        else:
            out_path = os.path.join(out_path, 'multiclass', f"{self.model_type}_loss_curves.csv")
            
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        
        df.to_csv(out_path, index=False)
        print(f"Loss curves saved to {out_path}")

    def get_feature_importance_analysis(self):
        print("Feature importance analysis not implemented yet.")
        print("Consider implementing SHAP values or permutation importance for better insights.")
        return None

## Data Preparation

In [6]:
master_df = pd.read_parquet('../data/dataset/ta_nlp_sector.parquet')

In [7]:
master_df.columns

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'ticker',
       'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
       'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
       'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'ret_1d',
       'roll_ret_1d', 'roll_ret_5d', 'roll_ret_20d', 'text', 'sentiment',
       'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
       'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
       'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
       'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
       'emotion_surprize_pct', 'positive_emotion', 'negative_emotion',
       'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct',
       'uncertainty_emotion_pct', 'stance_label', 'finbert_label',
       'stance_score', 'finbert_score', 'finbert_up', 'finbert_down',
       'finbert_neutral', 'sector', 'company_name', 'sector_open_mean',
       'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
       'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
       'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector',
       'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
       'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
       'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
       'market_close', 'sector_rel_strength', 'sector_dispersion_1d'],
      dtype='object')

In [8]:
master_df

,date,open,high,low,close,adj_close,volume,ticker,ema_12,ema_26,...,macd_12_26_9_sector,macdh_12_26_9_sector,macds_12_26_9_sector,rsi_14_sector,sector_bb_upper,sector_bb_middle,sector_bb_lower,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-09-04,95.108574,96.448570,94.928574,96.424286,87.121140,91973000.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1464.800169,NaN,NaN
1,2012-09-05,96.510002,96.621429,95.657143,95.747147,86.509338,84093800.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,1481.232189,NaN,0.006548
2,2012-09-06,96.167145,96.898575,95.828575,96.610001,87.288956,97799100.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,28.755774,NaN,NaN,NaN,1502.627054,NaN,0.006476
3,2012-09-07,96.864288,97.497147,96.538574,97.205711,87.827171,82416600.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,28.562466,NaN,NaN,NaN,1506.971629,NaN,0.008604
4,2012-09-10,97.207146,97.612854,94.585716,94.677139,85.542564,121999500.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,22.507443,NaN,NaN,NaN,1503.735325,NaN,0.012007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108587,2017-08-28,76.900002,76.940002,76.260002,76.470001,76.470001,8229700.0,XOM,77.187452,78.267858,...,-0.111192,0.016355,-0.127548,53.634155,63.049962,61.01430,58.978638,3101.328695,-0.007883,0.005228
108588,2017-08-29,76.209999,76.489998,76.080002,76.449997,76.449997,7060400.0,XOM,77.073998,78.133202,...,-0.067027,0.048417,-0.115443,54.205103,62.862103,60.94445,59.026797,3102.507723,-0.016661,0.002030
108589,2017-08-30,76.239998,76.449997,76.059998,76.099998,76.099998,8218000.0,XOM,76.924151,77.982594,...,-0.037643,0.062240,-0.099883,53.126723,62.639604,60.86875,59.097896,3128.753695,-0.017629,0.004873
108590,2017-08-31,76.269997,76.489998,76.050003,76.330002,76.330002,15641700.0,XOM,76.832744,77.860180,...,0.013408,0.090633,-0.077225,57.342960,62.525437,60.83190,59.138363,3141.201722,-0.008376,0.006185
108591,2017-09-01,76.370003,76.849998,76.320000,76.570000,76.570000,7340800.0,XOM,76.792322,77.764611,...,0.088512,0.132590,-0.044078,62.040301,62.426369,60.80760,59.188831,3136.813139,-0.001766,0.007085

In [9]:
columns_to_check = [
                    'sentiment',
                    
                    'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
                    'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
                    'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
                    'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
                    'emotion_surprize_pct', 
                    
                    'positive_emotion', 'negative_emotion','uncertainty_emotion', 
                    'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct', 
                    
                    'stance_label', 'stance_score', 
                    
                    'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
                    'finbert_neutral', 
                    
                    'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
                    'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
                    'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
                    
                    'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
                    'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
                    'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
                    'market_close', 'sector_rel_strength', 'sector_dispersion_1d'
                ]

print(f"Initial master_df shape: {master_df.shape}")

master_df = master_df.dropna(subset=columns_to_check)

print(f"After dropping NaNs in selected columns, master_df shape: {master_df.shape}")

master_df.reset_index(drop=True, inplace=True)

display(master_df)

Initial master_df shape: (108592, 80)
After dropping NaNs in selected columns, master_df shape: (104476, 80)

,date,open,high,low,close,adj_close,volume,ticker,ema_12,ema_26,...,macd_12_26_9_sector,macdh_12_26_9_sector,macds_12_26_9_sector,rsi_14_sector,sector_bb_upper,sector_bb_middle,sector_bb_lower,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-11-14,77.928574,78.207146,76.597145,76.697144,69.613815,119292600.0,AAPL,80.708033,84.949698,...,-0.913108,-0.181794,-0.731314,27.619972,63.948320,61.465736,58.983152,1484.350654,-0.003089,0.006800
1,2012-11-15,76.790001,77.071426,74.660004,75.088570,68.153778,197477700.0,AAPL,79.843501,84.219244,...,-0.926239,-0.155940,-0.770299,32.479352,63.646173,61.261193,58.876213,1484.574993,0.002003,0.019838
2,2012-11-16,75.028572,75.714287,72.250000,75.382858,68.420891,316723400.0,AAPL,79.157248,83.564697,...,-0.892113,-0.097452,-0.794662,37.450172,63.236926,61.078872,58.920817,1497.780485,0.010276,0.010265
3,2012-11-19,77.244286,81.071426,77.125717,80.818573,73.354591,205829400.0,AAPL,79.412836,83.361280,...,-0.733193,0.049174,-0.782368,51.350390,63.001827,61.010079,59.018330,1506.128807,0.024682,0.018850
4,2012-11-20,81.701431,81.707146,79.225716,80.129997,72.729614,160688500.0,AAPL,79.523169,83.121926,...,-0.579416,0.162361,-0.741778,53.267164,62.959435,60.996029,59.032623,1508.629302,0.025531,0.007554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104471,2017-08-28,76.900002,76.940002,76.260002,76.470001,76.470001,8229700.0,XOM,77.187452,78.267858,...,-0.111192,0.016355,-0.127548,53.634155,63.049962,61.014300,58.978638,3101.328695,-0.007883,0.005228
104472,2017-08-29,76.209999,76.489998,76.080002,76.449997,76.449997,7060400.0,XOM,77.073998,78.133202,...,-0.067027,0.048417,-0.115443,54.205103,62.862103,60.944450,59.026797,3102.507723,-0.016661,0.002030
104473,2017-08-30,76.239998,76.449997,76.059998,76.099998,76.099998,8218000.0,XOM,76.924151,77.982594,...,-0.037643,0.062240,-0.099883,53.126723,62.639604,60.868750,59.097896,3128.753695,-0.017629,0.004873
104474,2017-08-31,76.269997,76.489998,76.050003,76.330002,76.330002,15641700.0,XOM,76.832744,77.860180,...,0.013408,0.090633,-0.077225,57.342960,62.525437,60.831900,59.138363,3141.201722,-0.008376,0.006185
104475,2017-09-01,76.370003,76.849998,76.320000,76.570000,76.570000,7340800.0,XOM,76.792322,77.764611,...,0.088512,0.132590,-0.044078,62.040301,62.426369,60.807600,59.188831,3136.813139,-0.001766,0.007085

In [10]:
print(master_df.columns)

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'ticker',
       'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
       'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
       'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'ret_1d',
       'roll_ret_1d', 'roll_ret_5d', 'roll_ret_20d', 'text', 'sentiment',
       'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
       'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
       'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
       'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
       'emotion_surprize_pct', 'positive_emotion', 'negative_emotion',
       'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct',
       'uncertainty_emotion_pct', 'stance_label', 'finbert_label',
       'stance_score', 'finbert_score', 'finbert_up', 'finbert_down',
       'finbert_neutral', 'sector', 'company_name', 'sector_open_mean',
       'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
       'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
       'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector',
       'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
       'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
       'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
       'market_close', 'sector_rel_strength', 'sector_dispersion_1d'],
      dtype='object')

In [11]:
feature_columns = [
    'open', 'high', 'low', 'close', 'volume',
    # 'roll_ret_1d', 'roll_ret_5d', 
    # 'roll_ret_20d',
    
    'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
    'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
    'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv',
]

new_indicator_columns = [
    # 'sentiment',
                    
    # 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
    # 'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
    # 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
    # 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
    # 'emotion_surprize_pct', 
    
    # 'positive_emotion', 'negative_emotion','uncertainty_emotion', 
    # 'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct', 
    
    # 'stance_label', 'stance_score', 
    
    # 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
    # 'finbert_neutral', 
    
    # 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
    # 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
    # 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
    
    # 'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
    # 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
    # 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
    # 'market_close', 'sector_rel_strength', 'sector_dispersion_1d'
]

feature_columns.extend(new_indicator_columns)



sequence_length=12



all_pipelines = {}
all_results_dfs = {}
all_analyses = {}
fixed_bucket_edges = np.array([-0.08, -0.03, -0.01, 0.0, 0.01, 0.03, 0.08], dtype=float)
n_classes = len(fixed_bucket_edges) - 1
ordinal_head = 'corn'

In [12]:
print(master_df.shape)
master_df = master_df.dropna(subset=feature_columns).sort_values(['ticker','date'])
print(master_df.shape)

(104476, 80)
(104220, 80)

## Pipeline Execution

In [13]:
# print(f"\n{'='*25}\n  RUNNING PIPELINE FOR: GRU\n{'='*25}\n")

# pipeline_GRU = StockPredictionPipeline(
#     df=master_df,
#     feature_columns=feature_columns,
#     model_type='GRU',
#     sequence_length=sequence_length,
#     problem_type='classification',
#     horizon_steps=1,
#     n_classes=n_classes,
#     ordinal_head=ordinal_head,
#     fixed_bucket_edges=fixed_bucket_edges
# )

# results_GRU = pipeline_GRU.run_pipeline()

# loss_df = pipeline_GRU.get_loss_curves_df()

# pipeline_GRU.save_loss_curves('results/benchmarking/')

# if results_GRU is not None and not results_GRU.empty:
#     analysis_GRU = pipeline_GRU.analyze_results()
#     pipeline_GRU.save_results(results_GRU, output_dir='results/benchmarking/')
#     all_pipelines["GRU"] = pipeline_GRU
#     all_results_dfs["GRU"] = results_GRU
#     all_analyses["GRU"] = analysis_GRU

#     print("\nDisplaying first 5 rows of GRU results:")
#     display(results_GRU.head())
# else:
#     print(f"\n[FAILED] Pipeline for GRU did not produce any results.")

# del pipeline_GRU

In [14]:
try:
    import optuna
except ImportError:
    import sys
    !{sys.executable} -m pip install optuna
    import optuna
    
from pathlib import Path
from datetime import datetime
    
# Define feature sets to test
feature_sets = {
    'base': feature_columns,
    'sentinment' : feature_columns + ['sentiment'],
    'emotion' : feature_columns + ['emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
                                   'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
                                   'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
                                   'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
                                   'emotion_surprize_pct'],
    'unified_emotion': feature_columns + ['positive_emotion', 'negative_emotion','uncertainty_emotion', 
                                          'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct'],
    'stance': feature_columns + ['stance_label', 'stance_score'],
    'finbert': feature_columns + ['finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral'],
    'all_nlp': feature_columns + ['sentiment',
                                  'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
                                  'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
                                  'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
                                  'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
                                  'emotion_surprize_pct', 
                                  'positive_emotion', 'negative_emotion','uncertainty_emotion', 
                                  'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct', 
                                  'stance_label', 'stance_score', 
                                  'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
                                  'finbert_neutral']
    }

def objective(trial):
    params = {
        'problem_type': 'classification',  # or 'classification'
        'feature_set': trial.suggest_categorical('feature_set', list(feature_sets.keys())),
        'model_type': trial.suggest_categorical('model_type', ['LSTM', 'BiLSTM', 'GRU', 'BiGRU']),
        'sequence_length': trial.suggest_int('sequence_length', 6, 36, step=6),
        'horizon_steps': trial.suggest_categorical('horizon_steps', [1]),
        'hidden1': trial.suggest_categorical('hidden1', [64, 128, 256]),
        'hidden2': trial.suggest_categorical('hidden2', [32, 64, 128]),
        'num_layers': trial.suggest_categorical('num_layers', [1, 2]),
        'inter_rnn_drop': trial.suggest_float('inter_rnn_drop', 0.0, 0.4, step=0.1),
        'dropout': trial.suggest_float('dropout', 0.0, 0.8, step=0.1),
        'batch_size': trial.suggest_categorical('batch_size', [16, 32, 64]),
        'learning_rate': trial.suggest_float('learning_rate', 1e-6, 1e-2, log=True),
        'weight_decay': trial.suggest_float('weight_decay', 1e-7, 1e-3, log=True),
        'lr_patience': trial.suggest_categorical('lr_patience', [5, 7, 10]),
        'lr_factor': trial.suggest_categorical('lr_factor', [0.4, 0.8]),
        'early_stopping_patience': trial.suggest_categorical('early_stopping_patience', [10, 15, 20]),
        'max_epochs': trial.suggest_categorical('max_epochs', [20, 30, 50]),
        'huber_delta': trial.suggest_float('huber_delta', 0.1, 2.0),
        'early_stopping_min_delta': trial.suggest_float('early_stopping_min_delta', 0.0, 0.01),
    }

    selected_features = feature_sets[params['feature_set']]
    missing_cols = [c for c in selected_features if c not in master_df.columns]
    if missing_cols:
        print(f"Missing columns for feature_set={params['feature_set']}: {missing_cols}")
        return -1.0

    pipeline = StockPredictionPipeline(
        df=master_df,
        feature_columns=selected_features,
        model_type=params['model_type'],
        sequence_length=params['sequence_length'],
        problem_type=params['problem_type'],
        horizon_steps=params['horizon_steps'],
        n_classes=n_classes,
        ordinal_head=ordinal_head,
        fixed_bucket_edges=fixed_bucket_edges,
        hidden1=params['hidden1'],
        hidden2=params['hidden2'],
        num_layers=params['num_layers'],
        inter_rnn_drop=params['inter_rnn_drop'],
        dropout=params['dropout'],
        batch_size=params['batch_size'],
        learning_rate=params['learning_rate'],
        weight_decay=params['weight_decay'],
        lr_patience=params['lr_patience'],
        lr_factor=params['lr_factor'],
        early_stopping_patience=params['early_stopping_patience'],
        max_epochs=params['max_epochs'],
        huber_delta=params['huber_delta'],
        early_stopping_min_delta=params['early_stopping_min_delta']
    )

    results_df = pipeline.run_pipeline()
    del pipeline
    torch.cuda.empty_cache()

    if results_df is None or results_df.empty:
        print('[DEBUG] results_df empty or None')
        return -1.0

    print('[DEBUG] results_df shape:', results_df.shape)
    print('[DEBUG] results_df columns:', results_df.columns.tolist())

    # Aggregate validation metrics
    val_f1 = results_df['val_f1'].mean() if 'val_f1' in results_df.columns else np.nan
    if not np.isfinite(val_f1) and 'best_threshold_metric' in results_df.columns:
        val_f1 = results_df['best_threshold_metric'].mean()
    val_mcc = results_df['val_mcc'].mean() if 'val_mcc' in results_df.columns else np.nan
    print('[DEBUG] val_mcc:', val_mcc)
    val_precision = results_df['val_precision'].mean() if 'val_precision' in results_df.columns else np.nan
    val_recall = results_df['val_recall'].mean() if 'val_recall' in results_df.columns else np.nan
    val_dir_acc = results_df['val_directional_accuracy'].mean() if 'val_directional_accuracy' in results_df.columns else np.nan

    trial.set_user_attr('val_f1', float(val_f1))
    trial.set_user_attr('val_mcc', float(val_mcc))
    trial.set_user_attr('val_precision', float(val_precision))
    trial.set_user_attr('val_recall', float(val_recall))
    trial.set_user_attr('val_directional_accuracy', float(val_dir_acc))

    # Primary metric: mean val MCC (classification) or mean MAE (regression)
    if params['problem_type'] == 'classification':
        score = val_mcc
        if not np.isfinite(score):
            return -1.0
        return float(score)
    else:
        # minimize MAE -> maximize negative MAE
        if 'mae' not in results_df.columns:
            return -1.0
        mae = results_df['mae'].mean()
        if not np.isfinite(mae):
            return -1.0
        return float(-mae)


N_TRIALS = 250

# Run study
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=N_TRIALS, timeout=60*60*8)  # 8 hours max
# Collect results
optuna_results = study.trials_dataframe()
# include user attrs
user_attrs = pd.DataFrame([t.user_attrs for t in study.trials])
optuna_results = pd.concat([optuna_results, user_attrs], axis=1)
optuna_results = optuna_results.sort_values('value', ascending=False)
optuna_results

timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
out_path = f'results/benchmarking/classification/optuna_tuning_base_1H.csv'
Path('results/benchmarking/classification').mkdir(parents=True, exist_ok=True)
optuna_results.to_csv(out_path, index=False)
print(f'Saved Optuna results to {out_path}')

[I 2026-02-18 23:35:23,388] A new study created in memory with name: no-name-f2912bba-f321-481f-902d-cca6e142e73d

Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70557 | val 0.71519
  Epoch 020 - train 0.70848 | val 0.74013
  Classification -> best τ=0.500 (val F1=0.1430)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.73483 | val 0.68387
  Epoch 020 - train 0.71980 | val 0.68499
  Classification -> best τ=0.460 (val F1=0.0900)
  Directional -> Accuracy: 0.5333, MCC: -0.1844, F1: 0.6957

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68945 | val 0.68229
  Epoch 020 - train 0.69597 | val 0.67915
  Classification -> best τ=0.490 (val F1=0.2779)
  Directional -> Accuracy: 0.4783, MCC: -0.0948, F1: 0.6129

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71842 | val 0.81221
  Epoch 020 - train 0.71160 | val 0.83193
  Classification -> best τ=0.590 (val F1=0.1079)
  Directional -> Accuracy: 0.4324, MCC: -0.1167, F1: 0.3636

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69695 | val 0.69615
  Epoch 020 - train 0.69020 | val 0.69465
  Classification -> best τ=0.475 (val F1=0.2539)
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70753 | val 0.70513
  Epoch 020 - train 0.69096 | val 0.73981
  Classification -> best τ=0.495 (val F1=0.0495)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69869 | val 0.68418
  Epoch 020 - train 0.69441 | val 0.68404
  Classification -> best τ=0.460 (val F1=0.2481)
  Directional -> Accuracy: 0.5735, MCC: 0.1503, F1: 0.5246

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70796 | val 0.67359
  Epoch 020 - train 0.69078 | val 0.61138
  Classification -> best τ=0.415 (val F1=0.2566)
  Directional -> Accuracy: 0.5952, MCC: 0.1803, F1: 0.1053

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71201 | val 0.70552
  Epoch 020 - train 0.71313 | val 0.72587
  Classification -> best τ=0.505 (val F1=0.1188)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.70285 | val 0.68858
  Epoch 020 - train 0.70678 | val 0.68937
  Classification -> best τ=0.510 (val F1=0.2465)
  Directional -> Accuracy: 0.4203, MCC: -0.0585, F1: 0.5556

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69888 | val 0.68599
  Epoch 020 - train 0.68309 | val 0.70555
  Classification -> best τ=0.475 (val F1=0.0138)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71462 | val 0.71494
  Epoch 020 - train 0.71657 | val 0.72297
  Classification -> best τ=0.465 (val F1=0.1304)
  Directional -> Accuracy: 0.5614, MCC: 0.1217, F1: 0.6032

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69579 | val 0.68065
  Epoch 020 - train 0.69224 | val 0.69861
  Classification -> best τ=0.545 (val F1=0.0144)
  Directional -> Accuracy: 0.5238, MCC: 0.0784, F1: 0.5652

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70460 | val 0.67072
  Epoch 020 - train 0.69652 | val 0.65447
  Classification -> best τ=0.425 (val F1=0.2574)
  Directional -> Accuracy: 0.5167, MCC: 0.0765, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69438 | val 0.78319
  Epoch 020 - train 0.69943 | val 0.89188
  Classification -> best τ=0.565 (val F1=0.3062)
  Directional -> Accuracy: 0.6078, MCC: 0.2313, F1: 0.2857

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69665 | val 0.69784
  Epoch 020 - train 0.69136 | val 0.69947
  Classification -> best τ=0.515 (val F1=0.0972)
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69004 | val 0.71388
  Epoch 020 - train 0.69440 | val 0.74688
  Classification -> best τ=0.495 (val F1=0.0866)
  Directional -> Accuracy: 0.6379, MCC: 0.2380, F1: 0.7042

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70314 | val 0.70101
  Epoch 020 - train 0.70882 | val 0.70409
  Classification -> best τ=0.515 (val F1=0.1336)
  Directional -> Accuracy: 0.4933, MCC: -0.0109, F1: 0.5366

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69948 | val 0.70347
  Epoch 020 - train 0.69464 | val 0.70746
  Classification -> best τ=0.470 (val F1=0.2166)
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69631 | val 0.69370
  Epoch 020 - train 0.69884 | val 0.69990
  Classification -> best τ=0.480 (val F1=0.2011)
  Directional -> Accuracy: 0.4595, MCC: 0.1050, F1: 0.0476

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69870 | val 0.69027
  Epoch 020 - train 0.69932 | val 0.68826
  Classification -> best τ=0.495 (val F1=0.3458)
  Directional -> Accuracy: 0.5957, MCC: 0.2354, F1: 0.6122

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71246 | val 0.71019
  Epoch 020 - train 0.70889 | val 0.72327
  Classification -> best τ=0.480 (val F1=0.0157)
  Directional -> Accuracy: 0.4769, MCC: -0.0550, F1: 0.1500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69651 | val 0.69468
  Epoch 020 - train 0.69668 | val 0.69407
  Classification -> best τ=0.495 (val F1=0.1154)
  Directional -> Accuracy: 0.5789, MCC: 0.1083, F1: 0.7209

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70202 | val 0.75991
  Epoch 020 - train 0.69245 | val 0.77342
  Classification -> best τ=0.500 (val F1=0.1254)
  Directional -> Accuracy: 0.4154, MCC: -0.1798, F1: 0.3448

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70105 | val 0.70063
  Epoch 020 - train 0.71382 | val 0.69644
  Classification -> best τ=0.500 (val F1=0.0086)
  Directional -> Accuracy: 0.4364, MCC: -0.1587, F1: 0.5231

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68442 | val 0.69012
  Epoch 020 - train 0.69712 | val 0.68704
  Classification -> best τ=0.480 (val F1=0.2935)
  Directional -> Accuracy: 0.4222, MCC: -0.1286, F1: 0.4348

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70555 | val 0.71489
  Epoch 020 - train 0.69673 | val 0.81224
  Classification -> best τ=0.585 (val F1=0.0574)
  Directional -> Accuracy: 0.4762, MCC: -0.1021, F1: 0.5769

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.73440 | val 0.75809
  Epoch 020 - train 0.72097 | val 0.78512
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71191 | val 0.70637
  Epoch 020 - train 0.70556 | val 0.71886
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68558 | val 0.71424
  Epoch 020 - train 0.67492 | val 0.73615
  Classification -> best τ=0.545 (val F1=0.2271)
  Directional -> Accuracy: 0.5238, MCC: 0.0267, F1: 0.3333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70830 | val 0.71808
  Epoch 020 - train 0.72265 | val 0.72588
  Classification -> best τ=0.480 (val F1=0.0190)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70214 | val 0.70835
  Epoch 020 - train 0.70231 | val 0.70778
  Classification -> best τ=0.540 (val F1=0.2060)
  Directional -> Accuracy: 0.4490, MCC: -0.1535, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68424 | val 0.67249
  Epoch 020 - train 0.68138 | val 0.67161
  Classification -> best τ=0.475 (val F1=0.3530)
  Directional -> Accuracy: 0.5417, MCC: 0.1682, F1: 0.4211

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71233 | val 0.68146
  Epoch 020 - train 0.70993 | val 0.69491
  Classification -> best τ=0.480 (val F1=0.2126)
  Directional -> Accuracy: 0.5581, MCC: 0.1150, F1: 0.5366

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.70416 | val 0.70958
  Epoch 020 - train 0.71894 | val 0.71142
  Classification -> best τ=0.495 (val F1=0.2409)
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69486 | val 0.69107
  Epoch 020 - train 0.71510 | val 0.69150
  Classification -> best τ=0.470 (val F1=0.1822)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.75534 | val 0.81771
  Epoch 020 - train 0.75629 | val 0.92798
  Classification -> best τ=0.545 (val F1=0.2665)
  Directional -> Accuracy: 0.4821, MCC: 0.1255, F1: 0.6420

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.72210 | val 0.68843
  Epoch 020 - train 0.72260 | val 0.69574
  Classification -> best τ=0.465 (val F1=0.1055)
  Directional -> Accuracy: 0.6304, MCC: 0.2167, F1: 0.7018

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69855 | val 0.67834
  Epoch 020 - train 0.69241 | val 0.67563
  Classification -> best τ=0.480 (val F1=0.2392)
  Directional -> Accuracy: 0.6458, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.71198 | val 0.72076
  Epoch 020 - train 0.71876 | val 0.72546
  Classification -> best τ=0.480 (val F1=0.0466)
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.71093 | val 0.68906
  Epoch 020 - train 0.70783 | val 0.69116
  Classification -> best τ=0.505 (val F1=0.1890)
  Directional -> Accuracy: 0.4667, MCC: -0.0786, F1: 0.1429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69169 | val 0.69160
  Epoch 020 - train 0.67772 | val 0.69773
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72911 | val 0.68603
  Epoch 020 - train 0.73643 | val 0.68708
  Classification -> best τ=0.500 (val F1=0.4176)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68494 | val 0.67502
  Epoch 020 - train 0.68587 | val 0.69549
  Classification -> best τ=0.570 (val F1=0.2036)
  Directional -> Accuracy: 0.4909, MCC: 0.0852, F1: 0.2222

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69262 | val 0.70083
  Epoch 020 - train 0.69259 | val 0.70131
  Classification -> best τ=0.540 (val F1=0.1889)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70565 | val 0.71999
  Epoch 020 - train 0.70953 | val 0.75954
  Classification -> best τ=0.520 (val F1=0.0898)
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.73019 | val 0.70295
  Epoch 020 - train 0.71333 | val 0.70993
  Classification -> best τ=0.545 (val F1=0.1210)
  Directional -> Accuracy: 0.4000, MCC: -0.2958, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69351 | val 0.69385

[I 2026-02-18 23:36:31,548] Trial 0 finished with value: 0.15666448570732233 and parameters: {'feature_set': 'finbert', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 1.0085967472925463e-06, 'weight_decay': 1.0723022596468491e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.22672690704856407, 'early_stopping_min_delta': 0.009306619255311507}. Best is trial 0 with value: 0.15666448570732233.

  Epoch 020 - train 0.68977 | val 0.69886
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.15666448570732233
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68329 | val 0.77070
  Epoch 011 - train 0.68052 | val 0.77086
  Classification -> best τ=0.540 (val F1=0.1403)
  Directional -> Accuracy: 0.5513, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67937 | val 0.71911
  Epoch 011 - train 0.68072 | val 0.71911
  Classification -> best τ=0.490 (val F1=0.1111)
  Directional -> Accuracy: 0.5532, MCC: 0.0226, F1: 0.7042

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70366 | val 0.71424
  Epoch 011 - train 0.70222 | val 0.71402
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69472 | val 0.71326
  Epoch 013 - train 0.69324 | val 0.71225
  Classification -> best τ=0.485 (val F1=0.2797)
  Directional -> Accuracy: 0.5921, MCC: 0.2551, F1: 0.7257

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69108 | val 0.70731
  Epoch 011 - train 0.70025 | val 0.70690
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66466 | val 0.70944
  Epoch 011 - train 0.67805 | val 0.70930
  Classification -> best τ=0.455 (val F1=0.2371)
  Directional -> Accuracy: 0.5102, MCC: 0.1414, F1: 0.0769

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70163 | val 0.69780
  Epoch 011 - train 0.69668 | val 0.69790
  Classification -> best τ=0.515 (val F1=0.1316)
  Directional -> Accuracy: 0.4714, MCC: -0.0947, F1: 0.3509

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70664 | val 0.67245
  Epoch 020 - train 0.70862 | val 0.67510
  Epoch 021 - train 0.69001 | val 0.67591
  Classification -> best τ=0.525 (val F1=0.5714)
  Directional -> Accuracy: 0.5778, MCC: 0.0732, F1: 0.2963

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69081 | val 0.66337
  Epoch 020 - train 0.67357 | val 0.66204
  Epoch 028 - train 0.69016 | val 0.66188
  Classification -> best τ=0.475 (val F1=0.3920)
  Directional -> Accuracy: 0.4762, MCC: -0.1106, F1: 0.3125

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.70694 | val 0.73173
  Epoch 011 - train 0.70089 | val 0.73277
  Classification -> best τ=0.465 (val F1=0.1283)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69479 | val 0.67559
  Epoch 015 - train 0.71817 | val 0.67563
  Classification -> best τ=0.460 (val F1=0.3244)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.68855 | val 0.71919
  Epoch 011 - train 0.68370 | val 0.71914
  Classification -> best τ=0.520 (val F1=0.0249)
  Directional -> Accuracy: 0.5085, MCC: 0.1291, F1: 0.0645

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69079 | val 0.76668
  Epoch 011 - train 0.71035 | val 0.76778
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69214 | val 0.66125
  Epoch 020 - train 0.69386 | val 0.65645
  Epoch 030 - train 0.68297 | val 0.65222
  Epoch 040 - train 0.66925 | val 0.64850
  Epoch 050 - train 0.66286 | val 0.64568
  Classification -> best τ=0.440 (val F1=0.2009)
  Directional -> Accuracy: 0.5645, MCC: 0.1325, F1: 0.5091

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.71091 | val 0.70895
  Epoch 011 - train 0.68831 | val 0.71011
  Classification -> best τ=0.510 (val F1=0.0277)
  Directional -> Accuracy: 0.5094, MCC: -0.0176, F1: 0.2778

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.72414 | val 0.67636
  Epoch 014 - train 0.70263 | val 0.67521
  Classification -> best τ=0.490 (val F1=0.3786)
  Directional -> Accuracy: 0.6056, MCC: 0.2073, F1: 0.6316

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71500 | val 0.78046
  Epoch 011 - train 0.71792 | val 0.77996
  Classification -> best τ=0.515 (val F1=0.1681)
  Directional -> Accuracy: 0.4000, MCC: 0.1026, F1: 0.0526

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70100 | val 0.77144
  Epoch 011 - train 0.68719 | val 0.77166
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69303 | val 0.70107
  Epoch 011 - train 0.68413 | val 0.70095
  Classification -> best τ=0.510 (val F1=0.0651)
  Directional -> Accuracy: 0.4545, MCC: -0.0491, F1: 0.4375

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70064 | val 0.73361
  Epoch 011 - train 0.70434 | val 0.73243
  Classification -> best τ=0.510 (val F1=0.0951)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.71356 | val 0.71350
  Epoch 011 - train 0.67670 | val 0.71328
  Classification -> best τ=0.500 (val F1=0.1535)
  Directional -> Accuracy: 0.5918, MCC: -0.1572, F1: 0.7436

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70847 | val 0.71113
  Epoch 011 - train 0.69700 | val 0.71120
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68820 | val 0.68305
  Epoch 014 - train 0.68878 | val 0.68267
  Classification -> best τ=0.635 (val F1=0.2651)
  Directional -> Accuracy: 0.4746, MCC: 0.0776, F1: 0.2791

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68025 | val 0.76761
  Epoch 013 - train 0.69559 | val 0.76956
  Classification -> best τ=0.435 (val F1=0.1142)
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68787 | val 0.70122
  Epoch 011 - train 0.68469 | val 0.70112
  Classification -> best τ=0.545 (val F1=0.1167)
  Directional -> Accuracy: 0.5789, MCC: 0.2374, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68165 | val 0.70117
  Epoch 011 - train 0.69006 | val 0.70499
  Classification -> best τ=0.515 (val F1=0.2287)
  Directional -> Accuracy: 0.5625, MCC: -0.0436, F1: 0.0870

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.73913 | val 0.67864
  Epoch 016 - train 0.71948 | val 0.67742
  Classification -> best τ=0.565 (val F1=0.2968)
  Directional -> Accuracy: 0.4773, MCC: -0.0721, F1: 0.5490

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68970 | val 0.68295
  Epoch 016 - train 0.67751 | val 0.68425
  Classification -> best τ=0.440 (val F1=0.3581)
  Directional -> Accuracy: 0.5345, MCC: 0.1948, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67336 | val 0.69478
  Epoch 017 - train 0.68061 | val 0.71262
  Classification -> best τ=0.510 (val F1=0.2141)
  Directional -> Accuracy: 0.3953, MCC: -0.2435, F1: 0.0714

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70886 | val 0.71379
  Epoch 011 - train 0.70887 | val 0.71406
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69416 | val 0.70570
  Epoch 011 - train 0.70563 | val 0.70640
  Classification -> best τ=0.510 (val F1=0.0857)
  Directional -> Accuracy: 0.4889, MCC: -0.1048, F1: 0.6349

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70944 | val 0.69595
  Epoch 011 - train 0.71614 | val 0.69590
  Classification -> best τ=0.460 (val F1=0.1283)
  Directional -> Accuracy: 0.5098, MCC: -0.0242, F1: 0.6377

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68913 | val 0.74185
  Epoch 011 - train 0.70112 | val 0.74158
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.68928 | val 0.70364
  Epoch 011 - train 0.69725 | val 0.70640
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70370 | val 0.70756
  Epoch 014 - train 0.70504 | val 0.70871
  Classification -> best τ=0.500 (val F1=0.1935)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67587 | val 0.69209
  Epoch 011 - train 0.67382 | val 0.69180
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5735, MCC: 0.0000, F1: 0.7290

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70220 | val 0.70533
  Epoch 011 - train 0.70883 | val 0.70665
  Classification -> best τ=0.475 (val F1=0.0934)
  Directional -> Accuracy: 0.4545, MCC: -0.0945, F1: 0.3684

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69682 | val 0.70866
  Epoch 011 - train 0.70864 | val 0.70816
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70194 | val 0.77587
  Epoch 011 - train 0.70979 | val 0.77688
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70908 | val 0.65704
  Epoch 020 - train 0.69636 | val 0.65453
  Epoch 021 - train 0.70043 | val 0.65449
  Classification -> best τ=0.310 (val F1=0.3721)
  Directional -> Accuracy: 0.4000, MCC: -0.1791, F1: 0.3333

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.70089 | val 0.69148
  Epoch 011 - train 0.68033 | val 0.69266
  Classification -> best τ=0.485 (val F1=0.4781)
  Directional -> Accuracy: 0.3846, MCC: -0.3118, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69804 | val 0.70836
  Epoch 011 - train 0.70419 | val 0.70810
  Classification -> best τ=0.520 (val F1=0.1573)
  Directional -> Accuracy: 0.4737, MCC: -0.1644, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.74610 | val 0.70224
  Epoch 011 - train 0.71921 | val 0.70150
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67901 | val 0.68176
  Epoch 011 - train 0.68787 | val 0.68469
  Classification -> best τ=0.480 (val F1=0.1000)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70409 | val 0.72352
  Epoch 011 - train 0.72374 | val 0.72755
  Classification -> best τ=0.485 (val F1=0.2164)
  Directional -> Accuracy: 0.6341, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70395 | val 0.72472
  Epoch 011 - train 0.71400 | val 0.72502
  Classification -> best τ=0.500 (val F1=0.0418)
  Directional -> Accuracy: 0.5614, MCC: 0.0877, F1: 0.6753

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69491 | val 0.73922
  Epoch 011 - train 0.68880 | val 0.73910
  Classification -> best τ=0.535 (val F1=0.1113)
  Directional -> Accuracy: 0.5862, MCC: 0.2224, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69333 | val 0.72096
  Epoch 011 - train 0.68479 | val 0.72102
  Classification -> best τ=0.500 (val F1=0.1115)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.71476 | val 0.91739
  Epoch 011 - train 0.69669 | val 0.91794
  Classification -> best τ=0.505 (val F1=0.2258)
  Directional -> Accuracy: 0.5088, MCC: 0.0359, F1: 0.3000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69261 | val 0.70733

[I 2026-02-18 23:39:49,288] Trial 1 finished with value: 0.15091389470727987 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiLSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 1.6406212727370964e-06, 'weight_decay': 0.00011708733643542761, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.13025580173298382, 'early_stopping_min_delta': 0.002289624715557813}. Best is trial 0 with value: 0.15666448570732233.

  Epoch 013 - train 0.70068 | val 0.70748
  Classification -> best τ=0.500 (val F1=0.2068)
  Directional -> Accuracy: 0.5000, MCC: 0.0497, F1: 0.6437

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.15091389470727987
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68108 | val 0.76620
  Epoch 020 - train 0.69126 | val 0.76371
  Epoch 021 - train 0.69759 | val 0.76339
  Classification -> best τ=0.555 (val F1=0.0354)
  Directional -> Accuracy: 0.5395, MCC: -0.1039, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.71132 | val 0.69220
  Epoch 020 - train 0.70554 | val 0.68889
  Epoch 021 - train 0.70154 | val 0.68874
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.72384 | val 0.71867
  Epoch 020 - train 0.73053 | val 0.74946
  Epoch 021 - train 0.71925 | val 0.74909
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71833 | val 0.87523
  Epoch 020 - train 0.71328 | val 0.90467
  Epoch 021 - train 0.69830 | val 0.90757
  Classification -> best τ=0.445 (val F1=0.1411)
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.71515 | val 0.66187
  Epoch 020 - train 0.71740 | val 0.65259
  Epoch 030 - train 0.71222 | val 0.64835
  Classification -> best τ=0.540 (val F1=0.3688)
  Directional -> Accuracy: 0.5600, MCC: 0.1594, F1: 0.6944

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.72671 | val 0.68585
  Epoch 020 - train 0.73588 | val 0.68417
  Epoch 021 - train 0.69228 | val 0.68388
  Classification -> best τ=0.540 (val F1=0.1463)
  Directional -> Accuracy: 0.5217, MCC: 0.0349, F1: 0.4500

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.73288 | val 0.71470
  Epoch 020 - train 0.71183 | val 0.70936
  Epoch 021 - train 0.70975 | val 0.70874
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.74266 | val 0.70871
  Epoch 020 - train 0.70944 | val 0.73419
  Epoch 021 - train 0.72969 | val 0.73553
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70904 | val 0.70026
  Epoch 020 - train 0.71248 | val 0.70429
  Epoch 021 - train 0.70396 | val 0.70443
  Classification -> best τ=0.510 (val F1=0.1402)
  Directional -> Accuracy: 0.5417, MCC: 0.1005, F1: 0.5417

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.71879 | val 0.69855
  Epoch 020 - train 0.70205 | val 0.70395
  Epoch 021 - train 0.69735 | val 0.70418
  Classification -> best τ=0.530 (val F1=0.1810)
  Directional -> Accuracy: 0.3913, MCC: -0.2091, F1: 0.3636

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.72007 | val 0.71864
  Epoch 020 - train 0.71702 | val 0.72606
  Epoch 021 - train 0.71811 | val 0.72604
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71431 | val 0.69608
  Epoch 020 - train 0.69879 | val 0.69634
  Epoch 021 - train 0.70840 | val 0.69624
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.75746 | val 0.68010
  Epoch 020 - train 0.72971 | val 0.70690
  Epoch 026 - train 0.74000 | val 0.70212
  Classification -> best τ=0.570 (val F1=0.1370)
  Directional -> Accuracy: 0.5000, MCC: -0.0754, F1: 0.2222

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.73462 | val 0.81435
  Epoch 020 - train 0.72584 | val 0.81831
  Epoch 021 - train 0.69857 | val 0.81774
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70524 | val 0.70751
  Epoch 020 - train 0.70855 | val 0.69994
  Epoch 021 - train 0.69556 | val 0.69977
  Classification -> best τ=0.540 (val F1=0.1347)
  Directional -> Accuracy: 0.4902, MCC: 0.1178, F1: 0.6286

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.71142 | val 0.69526
  Epoch 020 - train 0.68544 | val 0.69301
  Epoch 021 - train 0.69579 | val 0.69306
  Classification -> best τ=0.490 (val F1=0.0367)
  Directional -> Accuracy: 0.4493, MCC: -0.0713, F1: 0.1739

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70077 | val 0.78487
  Epoch 020 - train 0.67816 | val 0.81906
  Epoch 021 - train 0.68781 | val 0.82068
  Classification -> best τ=0.530 (val F1=0.1774)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70723 | val 0.76600
  Epoch 020 - train 0.70020 | val 0.75268
  Epoch 021 - train 0.69741 | val 0.75160
  Classification -> best τ=0.500 (val F1=0.0155)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70151 | val 0.70508
  Epoch 020 - train 0.68818 | val 0.70424
  Epoch 021 - train 0.68807 | val 0.70413
  Classification -> best τ=0.515 (val F1=0.1809)
  Directional -> Accuracy: 0.5625, MCC: 0.2088, F1: 0.5000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.71081 | val 0.75344
  Epoch 020 - train 0.69311 | val 0.73878
  Epoch 021 - train 0.69819 | val 0.73745
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.71112 | val 0.70852
  Epoch 020 - train 0.73214 | val 0.70616
  Epoch 021 - train 0.69779 | val 0.70581
  Classification -> best τ=0.460 (val F1=0.2064)
  Directional -> Accuracy: 0.5532, MCC: 0.1469, F1: 0.5714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70898 | val 0.69836
  Epoch 020 - train 0.72411 | val 0.69901
  Epoch 021 - train 0.71881 | val 0.69880
  Classification -> best τ=0.500 (val F1=0.0356)
  Directional -> Accuracy: 0.4615, MCC: -0.0881, F1: 0.5455

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70332 | val 0.76236
  Epoch 020 - train 0.70809 | val 0.75683
  Epoch 021 - train 0.70065 | val 0.75565
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69861 | val 0.68657
  Epoch 020 - train 0.68269 | val 0.68654
  Epoch 025 - train 0.68808 | val 0.68635
  Classification -> best τ=0.455 (val F1=0.2452)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.72804 | val 0.74255
  Epoch 020 - train 0.75001 | val 0.74516
  Epoch 021 - train 0.74918 | val 0.74399
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70035 | val 0.69271
  Epoch 020 - train 0.68806 | val 0.70200
  Epoch 021 - train 0.70587 | val 0.70284
  Classification -> best τ=0.545 (val F1=0.1383)
  Directional -> Accuracy: 0.4000, MCC: -0.1419, F1: 0.4906

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72941 | val 0.70290
  Epoch 020 - train 0.70760 | val 0.70156
  Epoch 021 - train 0.71096 | val 0.70179
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.71865 | val 0.75477
  Epoch 020 - train 0.73532 | val 0.75289
  Epoch 021 - train 0.75824 | val 0.75252
  Classification -> best τ=0.555 (val F1=0.0349)
  Directional -> Accuracy: 0.4286, MCC: -0.2385, F1: 0.5676

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71100 | val 0.70737
  Epoch 020 - train 0.73323 | val 0.72785
  Epoch 021 - train 0.76149 | val 0.72907
  Classification -> best τ=0.465 (val F1=0.1459)
  Directional -> Accuracy: 0.5000, MCC: -0.0439, F1: 0.6000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.71515 | val 0.67947
  Epoch 020 - train 0.71186 | val 0.68358
  Epoch 030 - train 0.70132 | val 0.68503
  Classification -> best τ=0.535 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0195, F1: 0.2308

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69991 | val 0.70930
  Epoch 020 - train 0.66478 | val 0.77964
  Epoch 021 - train 0.69918 | val 0.78092
  Classification -> best τ=0.525 (val F1=0.1161)
  Directional -> Accuracy: 0.4524, MCC: -0.0677, F1: 0.3784

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.71261 | val 0.73532
  Epoch 020 - train 0.69265 | val 0.74852
  Epoch 021 - train 0.70866 | val 0.74852
  Classification -> best τ=0.530 (val F1=0.1679)
  Directional -> Accuracy: 0.5102, MCC: 0.1018, F1: 0.2500

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.72020 | val 0.68727
  Epoch 020 - train 0.70290 | val 0.68147
  Epoch 030 - train 0.69040 | val 0.67750
  Classification -> best τ=0.480 (val F1=0.3906)
  Directional -> Accuracy: 0.5556, MCC: 0.0449, F1: 0.6863

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.75566 | val 0.70565
  Epoch 020 - train 0.74262 | val 0.73678
  Epoch 021 - train 0.70821 | val 0.73753
  Classification -> best τ=0.475 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69096 | val 0.66976
  Epoch 020 - train 0.69918 | val 0.66574
  Epoch 029 - train 0.68846 | val 0.66452
  Classification -> best τ=0.465 (val F1=0.3525)
  Directional -> Accuracy: 0.6212, MCC: 0.1954, F1: 0.7126

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68817 | val 0.68454
  Epoch 020 - train 0.69229 | val 0.66823
  Epoch 030 - train 0.70865 | val 0.66589
  Classification -> best τ=0.525 (val F1=0.3589)
  Directional -> Accuracy: 0.4762, MCC: -0.0302, F1: 0.3529

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70543 | val 0.68323
  Epoch 020 - train 0.68685 | val 0.68254
  Epoch 021 - train 0.72442 | val 0.68237
  Classification -> best τ=0.475 (val F1=0.1288)
  Directional -> Accuracy: 0.5179, MCC: 0.0695, F1: 0.5846

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69437 | val 0.71254
  Epoch 020 - train 0.71308 | val 0.74253
  Epoch 021 - train 0.68560 | val 0.74146
  Classification -> best τ=0.470 (val F1=0.0324)
  Directional -> Accuracy: 0.5435, MCC: 0.1525, F1: 0.5333

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70446 | val 0.68067
  Epoch 020 - train 0.69229 | val 0.67254
  Epoch 030 - train 0.71072 | val 0.67052
  Classification -> best τ=0.480 (val F1=0.3006)
  Directional -> Accuracy: 0.4792, MCC: 0.1654, F1: 0.5455

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.74016 | val 0.69876
  Epoch 020 - train 0.73087 | val 0.69782
  Epoch 021 - train 0.72120 | val 0.69777
  Classification -> best τ=0.500 (val F1=0.1787)
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66331 | val 0.69857
  Epoch 020 - train 0.69133 | val 0.70486
  Epoch 021 - train 0.69695 | val 0.70447
  Classification -> best τ=0.475 (val F1=0.1512)
  Directional -> Accuracy: 0.4889, MCC: -0.0445, F1: 0.6102

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.71684 | val 0.69917
  Epoch 020 - train 0.72087 | val 0.70049
  Epoch 021 - train 0.72902 | val 0.70053
  Classification -> best τ=0.515 (val F1=0.1961)
  Directional -> Accuracy: 0.5238, MCC: 0.0550, F1: 0.5455

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72638 | val 0.69947
  Epoch 020 - train 0.69047 | val 0.71306
  Epoch 021 - train 0.72168 | val 0.71430
  Classification -> best τ=0.495 (val F1=0.2855)
  Directional -> Accuracy: 0.3542, MCC: -0.1556, F1: 0.5079

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.72553 | val 0.74404
  Epoch 020 - train 0.71279 | val 0.75670
  Epoch 021 - train 0.72984 | val 0.75644
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.74259 | val 0.69715
  Epoch 020 - train 0.70676 | val 0.69726
  Epoch 021 - train 0.71202 | val 0.69719
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.72145 | val 0.67927
  Epoch 020 - train 0.70941 | val 0.68288
  Epoch 026 - train 0.71181 | val 0.68253
  Classification -> best τ=0.550 (val F1=0.1479)
  Directional -> Accuracy: 0.5472, MCC: 0.1138, F1: 0.4286

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68270 | val 0.70617
  Epoch 020 - train 0.70186 | val 0.70809
  Epoch 021 - train 0.69602 | val 0.70715
  Classification -> best τ=0.495 (val F1=0.1738)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-18 23:44:52,753] Trial 2 finished with value: 0.12752156058924632 and parameters: {'feature_set': 'finbert', 'model_type': 'BiLSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 4.143875968476244e-06, 'weight_decay': 2.7742126105478495e-07, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.3040493728625201, 'early_stopping_min_delta': 0.00859132582957869}. Best is trial 0 with value: 0.15666448570732233.

  Epoch 021 - train 0.70981 | val 0.76804
  Classification -> best τ=0.545 (val F1=0.1013)
  Directional -> Accuracy: 0.4333, MCC: -0.1374, F1: 0.3929

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.12752156058924632
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62859 | val 0.68744
  Epoch 020 - train 0.58498 | val 0.70379
  Classification -> best τ=0.585 (val F1=0.2200)
  Directional -> Accuracy: 0.5263, MCC: -0.0499, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57453 | val 0.82967
  Epoch 020 - train 0.53645 | val 0.92399
  Classification -> best τ=0.490 (val F1=0.1764)
  Directional -> Accuracy: 0.4667, MCC: 0.1089, F1: 0.2000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61639 | val 0.66399
  Epoch 020 - train 0.56115 | val 0.64701
  Classification -> best τ=0.535 (val F1=0.4000)
  Directional -> Accuracy: 0.3913, MCC: -0.2340, F1: 0.1765

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62172 | val 0.97693
  Epoch 020 - train 0.58236 | val 0.99940
  Classification -> best τ=0.530 (val F1=0.1401)
  Directional -> Accuracy: 0.5135, MCC: 0.1745, F1: 0.2174

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61276 | val 0.71857
  Epoch 020 - train 0.58299 | val 0.74816
  Classification -> best τ=0.585 (val F1=0.3245)
  Directional -> Accuracy: 0.4800, MCC: -0.0118, F1: 0.1333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62873 | val 0.70753
  Epoch 020 - train 0.61666 | val 0.72460
  Classification -> best τ=0.500 (val F1=0.0635)
  Directional -> Accuracy: 0.4565, MCC: -0.0767, F1: 0.5283

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63405 | val 0.72094
  Epoch 020 - train 0.58477 | val 0.71605
  Classification -> best τ=0.455 (val F1=0.2648)
  Directional -> Accuracy: 0.5588, MCC: 0.0551, F1: 0.4000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60556 | val 0.77638
  Epoch 020 - train 0.57133 | val 0.85219
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63566 | val 0.71135
  Epoch 020 - train 0.59129 | val 0.71669
  Classification -> best τ=0.530 (val F1=0.0548)
  Directional -> Accuracy: 0.5417, MCC: -0.1286, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61402 | val 0.77132
  Epoch 020 - train 0.56543 | val 0.75412
  Classification -> best τ=0.490 (val F1=0.2293)
  Directional -> Accuracy: 0.3913, MCC: -0.2029, F1: 0.5625

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63311 | val 0.74169
  Epoch 020 - train 0.59090 | val 0.76813
  Classification -> best τ=0.470 (val F1=0.2187)
  Directional -> Accuracy: 0.4490, MCC: -0.0852, F1: 0.4706

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61106 | val 0.82415
  Epoch 020 - train 0.58911 | val 0.86548
  Classification -> best τ=0.520 (val F1=0.2258)
  Directional -> Accuracy: 0.4912, MCC: -0.0469, F1: 0.6329

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60074 | val 0.85923
  Epoch 020 - train 0.55068 | val 0.91787
  Classification -> best τ=0.485 (val F1=0.1225)
  Directional -> Accuracy: 0.5238, MCC: -0.1419, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64333 | val 0.84277
  Epoch 020 - train 0.62078 | val 0.81649
  Classification -> best τ=0.545 (val F1=0.0080)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6591

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58969 | val 0.72959
  Epoch 020 - train 0.59366 | val 0.73250
  Classification -> best τ=0.520 (val F1=0.2078)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62797 | val 0.66735
  Epoch 020 - train 0.57082 | val 0.69485
  Classification -> best τ=0.335 (val F1=0.3094)
  Directional -> Accuracy: 0.5507, MCC: 0.1304, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64505 | val 0.86171
  Epoch 020 - train 0.57524 | val 0.88051
  Classification -> best τ=0.535 (val F1=0.1291)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64461 | val 0.84228
  Epoch 020 - train 0.59394 | val 0.87231
  Classification -> best τ=0.515 (val F1=0.1548)
  Directional -> Accuracy: 0.4267, MCC: 0.0727, F1: 0.1224

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64807 | val 0.70282
  Epoch 020 - train 0.60382 | val 0.70975
  Classification -> best τ=0.485 (val F1=0.1777)
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.63584 | val 0.64786
  Epoch 020 - train 0.54975 | val 0.67151
  Classification -> best τ=0.480 (val F1=0.3714)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62312 | val 0.70327
  Epoch 020 - train 0.58585 | val 0.72406
  Classification -> best τ=0.525 (val F1=0.2258)
  Directional -> Accuracy: 0.5106, MCC: -0.1254, F1: 0.6462

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61871 | val 0.73321
  Epoch 020 - train 0.59965 | val 0.74030
  Classification -> best τ=0.490 (val F1=0.0594)
  Directional -> Accuracy: 0.4923, MCC: -0.0533, F1: 0.6452

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65181 | val 0.71600
  Epoch 020 - train 0.61333 | val 0.72255
  Classification -> best τ=0.530 (val F1=0.2236)
  Directional -> Accuracy: 0.5965, MCC: 0.2353, F1: 0.5660

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64846 | val 0.75797
  Epoch 020 - train 0.58755 | val 0.84827
  Classification -> best τ=0.495 (val F1=0.3065)
  Directional -> Accuracy: 0.4923, MCC: 0.1194, F1: 0.6526

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60508 | val 0.69780
  Epoch 020 - train 0.53844 | val 0.72608
  Classification -> best τ=0.550 (val F1=0.3472)
  Directional -> Accuracy: 0.4909, MCC: 0.0659, F1: 0.2632

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.61963 | val 0.69686
  Epoch 020 - train 0.56793 | val 0.70377
  Classification -> best τ=0.525 (val F1=0.2726)
  Directional -> Accuracy: 0.4444, MCC: 0.1289, F1: 0.6032

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62759 | val 0.79808
  Epoch 020 - train 0.58701 | val 0.77833
  Classification -> best τ=0.505 (val F1=0.2639)
  Directional -> Accuracy: 0.5238, MCC: 0.0142, F1: 0.6000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60485 | val 0.78398
  Epoch 020 - train 0.57968 | val 0.82173
  Classification -> best τ=0.485 (val F1=0.1615)
  Directional -> Accuracy: 0.4286, MCC: -0.1656, F1: 0.5000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.55166 | val 0.73020
  Epoch 020 - train 0.61734 | val 0.78866
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62098 | val 0.75604
  Epoch 020 - train 0.60809 | val 0.81222
  Classification -> best τ=0.545 (val F1=0.2814)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62516 | val 0.76891
  Epoch 020 - train 0.62970 | val 0.79436
  Classification -> best τ=0.490 (val F1=0.0128)
  Directional -> Accuracy: 0.5000, MCC: 0.0976, F1: 0.2759

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62882 | val 0.69351
  Epoch 020 - train 0.55197 | val 0.67516
  Classification -> best τ=0.415 (val F1=0.2918)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62943 | val 0.66074
  Epoch 020 - train 0.54649 | val 0.66615
  Classification -> best τ=0.410 (val F1=0.2869)
  Directional -> Accuracy: 0.5278, MCC: 0.1291, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62286 | val 0.86093
  Epoch 020 - train 0.62803 | val 0.90960
  Classification -> best τ=0.475 (val F1=0.1309)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62889 | val 0.75718
  Epoch 020 - train 0.58900 | val 0.77747
  Classification -> best τ=0.465 (val F1=0.1203)
  Directional -> Accuracy: 0.5758, MCC: 0.0485, F1: 0.7143

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62033 | val 0.68326
  Epoch 020 - train 0.50776 | val 0.71527
  Classification -> best τ=0.420 (val F1=0.3346)
  Directional -> Accuracy: 0.5952, MCC: 0.2656, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58280 | val 0.82297
  Epoch 020 - train 0.55802 | val 0.85950
  Classification -> best τ=0.485 (val F1=0.1995)
  Directional -> Accuracy: 0.5000, MCC: 0.0051, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62381 | val 0.84959
  Epoch 020 - train 0.58780 | val 0.89746
  Classification -> best τ=0.525 (val F1=0.1859)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.62774 | val 0.71816
  Epoch 020 - train 0.61572 | val 0.72848
  Classification -> best τ=0.525 (val F1=0.0157)
  Directional -> Accuracy: 0.5208, MCC: 0.0692, F1: 0.4651

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61208 | val 0.74273
  Epoch 020 - train 0.57135 | val 0.77793
  Classification -> best τ=0.535 (val F1=0.1863)
  Directional -> Accuracy: 0.5946, MCC: 0.1883, F1: 0.5312

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.63205 | val 0.68391
  Epoch 020 - train 0.56996 | val 0.70799
  Classification -> best τ=0.425 (val F1=0.2697)
  Directional -> Accuracy: 0.5333, MCC: 0.0950, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62400 | val 0.71809
  Epoch 020 - train 0.64274 | val 0.73004
  Classification -> best τ=0.525 (val F1=0.2041)
  Directional -> Accuracy: 0.5000, MCC: -0.1291, F1: 0.6441

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64454 | val 0.74586
  Epoch 020 - train 0.61672 | val 0.76456
  Classification -> best τ=0.460 (val F1=0.3458)
  Directional -> Accuracy: 0.3750, MCC: -0.0778, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63557 | val 0.68850
  Epoch 020 - train 0.54859 | val 0.68852
  Classification -> best τ=0.595 (val F1=0.2408)
  Directional -> Accuracy: 0.3273, MCC: -0.3351, F1: 0.2449

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63507 | val 0.80061
  Epoch 020 - train 0.60514 | val 0.84950
  Classification -> best τ=0.555 (val F1=0.3164)
  Directional -> Accuracy: 0.4464, MCC: -0.1032, F1: 0.4746

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64697 | val 0.82690
  Epoch 020 - train 0.59833 | val 0.87183
  Classification -> best τ=0.515 (val F1=0.0029)
  Directional -> Accuracy: 0.4906, MCC: -0.0080, F1: 0.2286

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65256 | val 0.98626
  Epoch 020 - train 0.61336 | val 1.08065
  Classification -> best τ=0.475 (val F1=0.2114)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62056 | val 0.80240

[I 2026-02-18 23:46:07,727] Trial 3 finished with value: 0.19592310397350557 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.00057800682811733, 'weight_decay': 9.038291780619316e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.6542678750640316, 'early_stopping_min_delta': 0.006606132006840606}. Best is trial 3 with value: 0.19592310397350557.

  Epoch 020 - train 0.61127 | val 0.86739
  Classification -> best τ=0.530 (val F1=0.1080)
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.19592310397350557
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65436 | val 0.74189
  Epoch 011 - train 0.64843 | val 0.74660
  Classification -> best τ=0.515 (val F1=0.2618)
  Directional -> Accuracy: 0.5949, MCC: 0.1614, F1: 0.2727

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64141 | val 0.74322
  Epoch 013 - train 0.62613 | val 0.79474
  Classification -> best τ=0.570 (val F1=0.1654)
  Directional -> Accuracy: 0.5000, MCC: 0.1264, F1: 0.2941

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66331 | val 0.66204
  Epoch 014 - train 0.64584 | val 0.66122
  Classification -> best τ=0.470 (val F1=0.5076)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65617 | val 0.73044
  Epoch 011 - train 0.66398 | val 0.72940
  Classification -> best τ=0.480 (val F1=0.1140)
  Directional -> Accuracy: 0.5455, MCC: 0.0468, F1: 0.6602

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64697 | val 0.65250
  Epoch 020 - train 0.62311 | val 0.64542
  Epoch 021 - train 0.60454 | val 0.64703
  Classification -> best τ=0.750 (val F1=0.3984)
  Directional -> Accuracy: 0.5094, MCC: 0.1269, F1: 0.1875

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.65059 | val 0.77763
  Epoch 011 - train 0.65142 | val 0.77711
  Classification -> best τ=0.505 (val F1=0.0391)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65584 | val 0.74611
  Epoch 011 - train 0.65086 | val 0.74913
  Classification -> best τ=0.520 (val F1=0.1005)
  Directional -> Accuracy: 0.3944, MCC: -0.1438, F1: 0.5657

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66250 | val 0.78379
  Epoch 011 - train 0.66353 | val 0.78339
  Classification -> best τ=0.550 (val F1=0.2921)
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66044 | val 0.82223
  Epoch 011 - train 0.65888 | val 0.82874
  Classification -> best τ=0.500 (val F1=0.2664)
  Directional -> Accuracy: 0.4884, MCC: 0.2590, F1: 0.6071

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63268 | val 0.83122
  Epoch 011 - train 0.62685 | val 0.85012
  Classification -> best τ=0.520 (val F1=0.1420)
  Directional -> Accuracy: 0.4306, MCC: 0.0000, F1: 0.6019

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64994 | val 0.82201
  Epoch 011 - train 0.65803 | val 0.82754
  Classification -> best τ=0.505 (val F1=0.1415)
  Directional -> Accuracy: 0.4615, MCC: -0.0976, F1: 0.3636

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65679 | val 0.76331
  Epoch 011 - train 0.64266 | val 0.76753
  Classification -> best τ=0.440 (val F1=0.1741)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63119 | val 0.81413
  Epoch 011 - train 0.62674 | val 0.81851
  Classification -> best τ=0.475 (val F1=0.3306)
  Directional -> Accuracy: 0.4889, MCC: -0.0299, F1: 0.4390

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65531 | val 0.62075
  Epoch 016 - train 0.63761 | val 0.63041
  Classification -> best τ=0.465 (val F1=0.3883)
  Directional -> Accuracy: 0.5397, MCC: 0.1459, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65448 | val 0.80441
  Epoch 011 - train 0.65963 | val 0.81895
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64471 | val 0.74333
  Epoch 011 - train 0.64389 | val 0.74768
  Classification -> best τ=0.525 (val F1=0.1607)
  Directional -> Accuracy: 0.4306, MCC: -0.1261, F1: 0.0889

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64059 | val 1.15116
  Epoch 011 - train 0.64590 | val 1.18095
  Classification -> best τ=0.450 (val F1=0.0374)
  Directional -> Accuracy: 0.5574, MCC: 0.0521, F1: 0.6494

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66645 | val 0.86086
  Epoch 011 - train 0.65892 | val 0.87976
  Classification -> best τ=0.565 (val F1=0.1083)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65330 | val 0.69767
  Epoch 011 - train 0.66302 | val 0.69606
  Classification -> best τ=0.550 (val F1=0.2160)
  Directional -> Accuracy: 0.4776, MCC: -0.1303, F1: 0.5977

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64871 | val 0.72846
  Epoch 011 - train 0.64550 | val 0.72684
  Classification -> best τ=0.460 (val F1=0.1697)
  Directional -> Accuracy: 0.5195, MCC: 0.1491, F1: 0.3019

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66749 | val 0.69742
  Epoch 011 - train 0.66144 | val 0.69737
  Classification -> best τ=0.535 (val F1=0.1154)
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65998 | val 0.68104
  Epoch 014 - train 0.64081 | val 0.68369
  Classification -> best τ=0.550 (val F1=0.2618)
  Directional -> Accuracy: 0.3824, MCC: -0.2357, F1: 0.4000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64699 | val 0.74322
  Epoch 011 - train 0.66669 | val 0.75169
  Classification -> best τ=0.500 (val F1=0.1920)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65333 | val 0.94844
  Epoch 011 - train 0.65042 | val 0.95392
  Classification -> best τ=0.470 (val F1=0.1806)
  Directional -> Accuracy: 0.5735, MCC: 0.1471, F1: 0.5672

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65346 | val 0.63392
  Epoch 017 - train 0.62614 | val 0.63450
  Classification -> best τ=0.480 (val F1=0.5149)
  Directional -> Accuracy: 0.5690, MCC: 0.2157, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.67428 | val 0.78506
  Epoch 011 - train 0.68331 | val 0.78711
  Classification -> best τ=0.490 (val F1=0.1009)
  Directional -> Accuracy: 0.5510, MCC: -0.0491, F1: 0.0833

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65760 | val 0.82099
  Epoch 011 - train 0.65442 | val 0.82491
  Classification -> best τ=0.490 (val F1=0.2017)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65107 | val 0.71766
  Epoch 011 - train 0.65178 | val 0.71953
  Classification -> best τ=0.525 (val F1=0.2045)
  Directional -> Accuracy: 0.4746, MCC: 0.0727, F1: 0.2051

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64026 | val 0.66766
  Epoch 011 - train 0.65476 | val 0.66615
  Classification -> best τ=0.600 (val F1=0.2345)
  Directional -> Accuracy: 0.5227, MCC: 0.2085, F1: 0.1600

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66055 | val 0.73402
  Epoch 011 - train 0.65617 | val 0.73471
  Classification -> best τ=0.480 (val F1=0.1326)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6349

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66367 | val 0.73598
  Epoch 011 - train 0.67807 | val 0.73368
  Classification -> best τ=0.490 (val F1=0.3248)
  Directional -> Accuracy: 0.5870, MCC: 0.1554, F1: 0.6545

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64851 | val 0.67740
  Epoch 014 - train 0.64352 | val 0.68074
  Classification -> best τ=0.500 (val F1=0.3389)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63702 | val 0.64549
  Epoch 019 - train 0.61613 | val 0.64134
  Classification -> best τ=0.390 (val F1=0.3523)
  Directional -> Accuracy: 0.5867, MCC: 0.2279, F1: 0.5373

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.67900 | val 0.71030
  Epoch 011 - train 0.66774 | val 0.71265
  Classification -> best τ=0.475 (val F1=0.2774)
  Directional -> Accuracy: 0.5366, MCC: 0.0719, F1: 0.3448

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65942 | val 0.79006
  Epoch 011 - train 0.65679 | val 0.79936
  Classification -> best τ=0.500 (val F1=0.4205)
  Directional -> Accuracy: 0.6304, MCC: 0.3772, F1: 0.7018

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64788 | val 0.67721
  Epoch 013 - train 0.62689 | val 0.68185
  Classification -> best τ=0.415 (val F1=0.3914)
  Directional -> Accuracy: 0.4348, MCC: 0.1033, F1: 0.0488

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66612 | val 0.66085
  Epoch 017 - train 0.63851 | val 0.65943
  Classification -> best τ=0.460 (val F1=0.3859)
  Directional -> Accuracy: 0.4222, MCC: -0.1771, F1: 0.5185

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65385 | val 0.77523
  Epoch 011 - train 0.63527 | val 0.77954
  Classification -> best τ=0.525 (val F1=0.1392)
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64916 | val 1.27931
  Epoch 011 - train 0.65457 | val 1.29515
  Classification -> best τ=0.575 (val F1=0.1814)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66359 | val 0.68584
  Epoch 020 - train 0.63654 | val 0.67677
  Epoch 024 - train 0.61171 | val 0.67475
  Classification -> best τ=0.465 (val F1=0.2665)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.67857 | val 0.71246
  Epoch 011 - train 0.67153 | val 0.71584
  Classification -> best τ=0.460 (val F1=0.3780)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64963 | val 0.72733
  Epoch 011 - train 0.63826 | val 0.73160
  Classification -> best τ=0.500 (val F1=0.1950)
  Directional -> Accuracy: 0.6104, MCC: 0.2204, F1: 0.6250

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.68799 | val 0.70523
  Epoch 011 - train 0.68056 | val 0.70453
  Classification -> best τ=0.500 (val F1=0.0866)
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65747 | val 0.67354
  Epoch 019 - train 0.62366 | val 0.69089
  Classification -> best τ=0.505 (val F1=0.3043)
  Directional -> Accuracy: 0.4681, MCC: 0.1814, F1: 0.1379

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64075 | val 0.83941
  Epoch 011 - train 0.66433 | val 0.84424
  Classification -> best τ=0.600 (val F1=0.2048)
  Directional -> Accuracy: 0.6429, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65656 | val 0.67816
  Epoch 013 - train 0.66225 | val 0.68324
  Classification -> best τ=0.535 (val F1=0.1801)
  Directional -> Accuracy: 0.6552, MCC: 0.3350, F1: 0.6429

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64400 | val 1.03488
  Epoch 011 - train 0.64185 | val 1.05057
  Classification -> best τ=0.515 (val F1=0.2258)
  Directional -> Accuracy: 0.5763, MCC: 0.1764, F1: 0.6479

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66731 | val 1.02924
  Epoch 011 - train 0.65805 | val 1.05202
  Classification -> best τ=0.455 (val F1=0.1694)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65321 | val 0.82819
  Epoch 011 - train 0.65187 | val 0.84382
  Classification -> best τ=0.470 (val F1=0.4096)
  Directional -> Accuracy: 0.5345, MCC: 0.0860, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-18 23:46:58,168] Trial 4 finished with value: 0.2326372255203152 and parameters: {'feature_set': 'finbert', 'model_type': 'GRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 3.857321258754576e-05, 'weight_decay': 0.00011697529484772715, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.976946947721217, 'early_stopping_min_delta': 0.008512871326485772}. Best is trial 4 with value: 0.2326372255203152.

  Epoch 010 - train 0.64226 | val 0.71400
  Epoch 011 - train 0.64604 | val 0.72038
  Classification -> best τ=0.510 (val F1=0.2475)
  Directional -> Accuracy: 0.5079, MCC: -0.1211, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2326372255203152
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69893 | val 0.73581
  Epoch 016 - train 0.69253 | val 0.73117
  Classification -> best τ=0.505 (val F1=0.0014)
  Directional -> Accuracy: 0.5195, MCC: 0.1491, F1: 0.6337

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.67721 | val 0.68590
  Epoch 020 - train 0.65808 | val 0.68980
  Classification -> best τ=0.420 (val F1=0.3130)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.75243 | val 0.73948
  Epoch 016 - train 0.71639 | val 0.73456
  Classification -> best τ=0.535 (val F1=0.1080)
  Directional -> Accuracy: 0.4894, MCC: -0.1033, F1: 0.6364

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71747 | val 0.71567
  Epoch 017 - train 0.70463 | val 0.72038
  Classification -> best τ=0.475 (val F1=0.2086)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.75887 | val 0.69867
  Epoch 020 - train 0.70361 | val 0.68593
  Epoch 030 - train 0.68588 | val 0.67529
  Classification -> best τ=0.475 (val F1=0.5666)
  Directional -> Accuracy: 0.6078, MCC: 0.3761, F1: 0.4118

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70449 | val 0.71618
  Epoch 018 - train 0.68511 | val 0.70159
  Classification -> best τ=0.525 (val F1=0.1644)
  Directional -> Accuracy: 0.4043, MCC: -0.1949, F1: 0.4815

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.73274 | val 0.70621
  Epoch 018 - train 0.71084 | val 0.71476
  Classification -> best τ=0.455 (val F1=0.2847)
  Directional -> Accuracy: 0.5217, MCC: 0.1549, F1: 0.5823

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.72394 | val 0.72391
  Epoch 016 - train 0.71826 | val 0.73936
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.75361 | val 0.69953
  Epoch 018 - train 0.71513 | val 0.70012
  Classification -> best τ=0.515 (val F1=0.2915)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68179 | val 0.70066
  Epoch 016 - train 0.70112 | val 0.69971
  Classification -> best τ=0.530 (val F1=0.0319)
  Directional -> Accuracy: 0.5286, MCC: -0.0739, F1: 0.1538

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69985 | val 0.67874
  Epoch 020 - train 0.70348 | val 0.68541
  Epoch 021 - train 0.71244 | val 0.68617
  Classification -> best τ=0.595 (val F1=0.1750)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.72339 | val 0.69244
  Epoch 020 - train 0.69995 | val 0.69457
  Epoch 025 - train 0.72440 | val 0.69657
  Classification -> best τ=0.530 (val F1=0.1121)
  Directional -> Accuracy: 0.5690, MCC: 0.1826, F1: 0.3590

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.70715 | val 0.79733
  Epoch 016 - train 0.74742 | val 0.79878
  Classification -> best τ=0.485 (val F1=0.1265)
  Directional -> Accuracy: 0.4186, MCC: -0.1150, F1: 0.5455

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69958 | val 0.67980
  Epoch 020 - train 0.69686 | val 0.67849
  Epoch 024 - train 0.70586 | val 0.67564
  Classification -> best τ=0.485 (val F1=0.3784)
  Directional -> Accuracy: 0.5574, MCC: 0.1210, F1: 0.5091

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70238 | val 0.72968
  Epoch 016 - train 0.68199 | val 0.72478
  Classification -> best τ=0.470 (val F1=0.0457)
  Directional -> Accuracy: 0.5385, MCC: 0.0223, F1: 0.1429

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70091 | val 0.66849
  Epoch 020 - train 0.67491 | val 0.66703
  Epoch 030 - train 0.69399 | val 0.66823
  Classification -> best τ=0.365 (val F1=0.2605)
  Directional -> Accuracy: 0.5857, MCC: 0.1721, F1: 0.7129

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.72255 | val 0.68075
  Epoch 020 - train 0.73125 | val 0.68895
  Classification -> best τ=0.370 (val F1=0.3015)
  Directional -> Accuracy: 0.6949, MCC: 0.3497, F1: 0.8043

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.74499 | val 0.70923
  Epoch 016 - train 0.70770 | val 0.70986
  Classification -> best τ=0.555 (val F1=0.0570)
  Directional -> Accuracy: 0.4079, MCC: 0.0933, F1: 0.0426

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.71827 | val 0.70269
  Epoch 016 - train 0.70110 | val 0.70291
  Classification -> best τ=0.505 (val F1=0.0794)
  Directional -> Accuracy: 0.5231, MCC: -0.0333, F1: 0.6353

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.74320 | val 0.74222
  Epoch 016 - train 0.71148 | val 0.73551
  Classification -> best τ=0.510 (val F1=0.1818)
  Directional -> Accuracy: 0.4400, MCC: -0.1101, F1: 0.4324

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.73884 | val 0.69115
  Epoch 019 - train 0.68755 | val 0.68930
  Classification -> best τ=0.525 (val F1=0.3126)
  Directional -> Accuracy: 0.5625, MCC: 0.2437, F1: 0.5333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.72901 | val 0.69798
  Epoch 020 - train 0.68961 | val 0.69881
  Epoch 024 - train 0.69625 | val 0.69689
  Classification -> best τ=0.615 (val F1=0.3123)
  Directional -> Accuracy: 0.5758, MCC: 0.2208, F1: 0.3333

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.74105 | val 0.75744
  Epoch 016 - train 0.70984 | val 0.74490
  Classification -> best τ=0.470 (val F1=0.1371)
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.74322 | val 0.69660
  Epoch 018 - train 0.69880 | val 0.71024
  Classification -> best τ=0.440 (val F1=0.1270)
  Directional -> Accuracy: 0.5303, MCC: 0.0921, F1: 0.5974

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.74099 | val 0.69755
  Epoch 020 - train 0.68531 | val 0.68737
  Epoch 030 - train 0.68843 | val 0.67673
  Classification -> best τ=0.430 (val F1=0.3464)
  Directional -> Accuracy: 0.4643, MCC: -0.0535, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70484 | val 0.69160
  Epoch 020 - train 0.67754 | val 0.69167
  Epoch 022 - train 0.69302 | val 0.69457
  Classification -> best τ=0.445 (val F1=0.2774)
  Directional -> Accuracy: 0.4783, MCC: 0.0793, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70869 | val 0.68784
  Epoch 020 - train 0.68595 | val 0.68629
  Epoch 023 - train 0.70151 | val 0.68762
  Classification -> best τ=0.495 (val F1=0.2587)
  Directional -> Accuracy: 0.4651, MCC: -0.2465, F1: 0.6230

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.75441 | val 0.70533
  Epoch 016 - train 0.73904 | val 0.70074
  Classification -> best τ=0.470 (val F1=0.1099)
  Directional -> Accuracy: 0.5614, MCC: 0.0236, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.74848 | val 0.71176
  Epoch 016 - train 0.68786 | val 0.70983
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.71433 | val 0.73472
  Epoch 016 - train 0.74151 | val 0.74002
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72383 | val 0.67908
  Epoch 020 - train 0.73221 | val 0.67895
  Epoch 026 - train 0.70179 | val 0.67949
  Classification -> best τ=0.590 (val F1=0.1667)
  Directional -> Accuracy: 0.4419, MCC: -0.1655, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.71573 | val 0.69937
  Epoch 018 - train 0.69978 | val 0.69800
  Classification -> best τ=0.545 (val F1=0.2320)
  Directional -> Accuracy: 0.5800, MCC: 0.1714, F1: 0.5714

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.71299 | val 0.65373
  Epoch 020 - train 0.68836 | val 0.64633
  Epoch 030 - train 0.70101 | val 0.63906
  Classification -> best τ=0.390 (val F1=0.4013)
  Directional -> Accuracy: 0.5479, MCC: 0.1713, F1: 0.4590

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.70733 | val 0.71676
  Epoch 016 - train 0.74577 | val 0.73392
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71098 | val 0.83006
  Epoch 016 - train 0.69456 | val 0.83511
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.72962 | val 0.68358
  Epoch 020 - train 0.71005 | val 0.69017
  Epoch 025 - train 0.68598 | val 0.69138
  Classification -> best τ=0.390 (val F1=0.2142)
  Directional -> Accuracy: 0.4925, MCC: 0.1685, F1: 0.2273

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.73840 | val 0.68509
  Epoch 020 - train 0.70349 | val 0.68112
  Epoch 030 - train 0.66978 | val 0.68089
  Classification -> best τ=0.410 (val F1=0.2819)
  Directional -> Accuracy: 0.7442, MCC: 0.4881, F1: 0.7556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.68639 | val 0.68353
  Epoch 019 - train 0.68462 | val 0.68892
  Classification -> best τ=0.430 (val F1=0.2993)
  Directional -> Accuracy: 0.5088, MCC: 0.0349, F1: 0.5625

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70136 | val 0.70896
  Epoch 020 - train 0.72880 | val 0.71804
  Classification -> best τ=0.470 (val F1=0.2066)
  Directional -> Accuracy: 0.4043, MCC: -0.0814, F1: 0.3000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71050 | val 0.70581
  Epoch 016 - train 0.70836 | val 0.70349
  Classification -> best τ=0.520 (val F1=0.3125)
  Directional -> Accuracy: 0.3673, MCC: -0.1028, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.71949 | val 0.67351
  Epoch 020 - train 0.72363 | val 0.67624
  Epoch 029 - train 0.68542 | val 0.67672
  Classification -> best τ=0.520 (val F1=0.4773)
  Directional -> Accuracy: 0.5526, MCC: 0.1566, F1: 0.4138

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.72569 | val 0.69148
  Epoch 020 - train 0.69990 | val 0.69036
  Epoch 030 - train 0.70884 | val 0.68961
  Classification -> best τ=0.485 (val F1=0.2528)
  Directional -> Accuracy: 0.5067, MCC: 0.0361, F1: 0.6408

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.72578 | val 0.68755
  Epoch 020 - train 0.75068 | val 0.68558
  Epoch 021 - train 0.73610 | val 0.68530
  Classification -> best τ=0.395 (val F1=0.3377)
  Directional -> Accuracy: 0.5319, MCC: 0.1506, F1: 0.6857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69245 | val 0.71969
  Epoch 016 - train 0.74376 | val 0.72327
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.70479 | val 0.72188
  Epoch 016 - train 0.69557 | val 0.72270
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.74589 | val 0.68177
  Epoch 020 - train 0.70032 | val 0.68145
  Epoch 030 - train 0.72572 | val 0.67783
  Classification -> best τ=0.615 (val F1=0.1914)
  Directional -> Accuracy: 0.4286, MCC: -0.1269, F1: 0.2000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.72542 | val 0.69507
  Epoch 019 - train 0.70741 | val 0.69526
  Classification -> best τ=0.450 (val F1=0.2083)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67013 | val 0.68556
  Epoch 019 - train 0.70079 | val 0.68573
  Classification -> best τ=0.595 (val F1=0.0533)
  Directional -> Accuracy: 0.4630, MCC: -0.1425, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69582 | val 0.73207
  Epoch 016 - train 0.70408 | val 0.73352
  Classification -> best τ=0.520 (val F1=0.1145)
  Directional -> Accuracy: 0.5536, MCC: 0.1017, F1: 0.6377

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.69420 | val 0.73106

[I 2026-02-18 23:50:35,620] Trial 5 finished with value: 0.186376159783867 and parameters: {'feature_set': 'emotion', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 3.0735151822493484e-05, 'weight_decay': 0.00014914289569227594, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.2523102204611343, 'early_stopping_min_delta': 0.00018771070095865427}. Best is trial 4 with value: 0.2326372255203152.

  Epoch 016 - train 0.70291 | val 0.73024
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.186376159783867
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69677 | val 0.80946
  Epoch 020 - train 0.70185 | val 0.82293
  Epoch 021 - train 0.70050 | val 0.81845
  Classification -> best τ=0.520 (val F1=0.0544)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.72556 | val 0.69786
  Epoch 020 - train 0.70702 | val 0.69807
  Epoch 021 - train 0.69422 | val 0.69984
  Classification -> best τ=0.470 (val F1=0.1329)
  Directional -> Accuracy: 0.4091, MCC: -0.1688, F1: 0.4348

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.72942 | val 0.71106
  Epoch 020 - train 0.70328 | val 0.70810
  Epoch 021 - train 0.70164 | val 0.70593
  Classification -> best τ=0.495 (val F1=0.1147)
  Directional -> Accuracy: 0.5333, MCC: 0.2500, F1: 0.2222

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70209 | val 0.69938
  Epoch 020 - train 0.69912 | val 0.69820
  Epoch 021 - train 0.69894 | val 0.69870
  Classification -> best τ=0.520 (val F1=0.1923)
  Directional -> Accuracy: 0.4658, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69254 | val 0.68446
  Epoch 020 - train 0.70515 | val 0.68078
  Epoch 030 - train 0.67702 | val 0.67420
  Classification -> best τ=0.545 (val F1=0.4155)
  Directional -> Accuracy: 0.6327, MCC: 0.3593, F1: 0.4706

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68992 | val 0.71920
  Epoch 020 - train 0.69510 | val 0.71642
  Epoch 021 - train 0.71567 | val 0.71182
  Classification -> best τ=0.500 (val F1=0.1787)
  Directional -> Accuracy: 0.4889, MCC: -0.0391, F1: 0.3030

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70076 | val 0.69036
  Epoch 020 - train 0.69204 | val 0.69064
  Epoch 021 - train 0.69297 | val 0.69153
  Classification -> best τ=0.530 (val F1=0.1417)
  Directional -> Accuracy: 0.6119, MCC: 0.1355, F1: 0.3500

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71631 | val 0.65026
  Epoch 020 - train 0.70076 | val 0.65329
  Epoch 030 - train 0.68436 | val 0.65086
  Classification -> best τ=0.485 (val F1=0.2646)
  Directional -> Accuracy: 0.5366, MCC: -0.0598, F1: 0.0952

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70769 | val 0.69262
  Epoch 020 - train 0.73537 | val 0.69438
  Epoch 021 - train 0.69652 | val 0.69109
  Classification -> best τ=0.505 (val F1=0.2018)
  Directional -> Accuracy: 0.4468, MCC: -0.1299, F1: 0.3500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69104 | val 0.70130
  Epoch 020 - train 0.69183 | val 0.70066
  Epoch 021 - train 0.68388 | val 0.69941
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68237 | val 0.70830
  Epoch 020 - train 0.68922 | val 0.70283
  Epoch 021 - train 0.69818 | val 0.71138
  Classification -> best τ=0.500 (val F1=0.1627)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70508 | val 0.68347
  Epoch 020 - train 0.71210 | val 0.68493
  Epoch 021 - train 0.69264 | val 0.68407
  Classification -> best τ=0.515 (val F1=0.1550)
  Directional -> Accuracy: 0.4464, MCC: -0.1487, F1: 0.0606

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68361 | val 0.72354
  Epoch 020 - train 0.68694 | val 0.72664
  Epoch 021 - train 0.70393 | val 0.72263
  Classification -> best τ=0.530 (val F1=0.1353)
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70302 | val 0.73214
  Epoch 020 - train 0.71338 | val 0.73498
  Epoch 021 - train 0.70522 | val 0.73015
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67892 | val 0.69639
  Epoch 020 - train 0.69756 | val 0.69788
  Epoch 021 - train 0.67861 | val 0.69672
  Classification -> best τ=0.505 (val F1=0.1289)
  Directional -> Accuracy: 0.5200, MCC: 0.0772, F1: 0.5556

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70040 | val 0.69282
  Epoch 020 - train 0.69660 | val 0.69089
  Epoch 021 - train 0.70022 | val 0.69255
  Classification -> best τ=0.505 (val F1=0.3005)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71318 | val 0.72728
  Epoch 020 - train 0.72257 | val 0.72836
  Epoch 021 - train 0.72986 | val 0.73143
  Classification -> best τ=0.435 (val F1=0.0614)
  Directional -> Accuracy: 0.5439, MCC: -0.0815, F1: 0.6829

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.72065 | val 0.74600
  Epoch 020 - train 0.70438 | val 0.74641
  Epoch 021 - train 0.71038 | val 0.74550
  Classification -> best τ=0.470 (val F1=0.0792)
  Directional -> Accuracy: 0.3784, MCC: -0.2018, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69401 | val 0.70270
  Epoch 020 - train 0.69473 | val 0.70228
  Epoch 021 - train 0.68954 | val 0.70070
  Classification -> best τ=0.515 (val F1=0.1372)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70705 | val 0.68361
  Epoch 020 - train 0.69254 | val 0.68107
  Epoch 030 - train 0.67818 | val 0.67914
  Classification -> best τ=0.380 (val F1=0.2187)
  Directional -> Accuracy: 0.5616, MCC: 0.1877, F1: 0.4667

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69062 | val 0.69706
  Epoch 020 - train 0.68951 | val 0.69722
  Epoch 021 - train 0.70092 | val 0.69700
  Classification -> best τ=0.490 (val F1=0.1288)
  Directional -> Accuracy: 0.5652, MCC: 0.1055, F1: 0.6296

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69439 | val 0.68981
  Epoch 020 - train 0.70164 | val 0.69089
  Epoch 024 - train 0.70093 | val 0.69100
  Classification -> best τ=0.600 (val F1=0.3004)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69401 | val 0.72381
  Epoch 020 - train 0.69557 | val 0.71822
  Epoch 021 - train 0.70608 | val 0.72089
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68910 | val 0.77388
  Epoch 020 - train 0.69518 | val 0.76343
  Epoch 021 - train 0.69279 | val 0.75707
  Classification -> best τ=0.450 (val F1=0.1785)
  Directional -> Accuracy: 0.5625, MCC: 0.3021, F1: 0.6818

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.69942 | val 0.69664
  Epoch 020 - train 0.69619 | val 0.69031
  Epoch 030 - train 0.69675 | val 0.68569
  Classification -> best τ=0.530 (val F1=0.2365)
  Directional -> Accuracy: 0.5926, MCC: 0.1989, F1: 0.5769

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71351 | val 0.68810
  Epoch 020 - train 0.70076 | val 0.68945
  Epoch 021 - train 0.70663 | val 0.68812
  Classification -> best τ=0.500 (val F1=0.3118)
  Directional -> Accuracy: 0.5116, MCC: 0.1634, F1: 0.6038

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68611 | val 0.69736
  Epoch 020 - train 0.69777 | val 0.69595
  Epoch 021 - train 0.70531 | val 0.69700
  Classification -> best τ=0.550 (val F1=0.0551)
  Directional -> Accuracy: 0.5102, MCC: -0.1114, F1: 0.6471

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69632 | val 0.70275
  Epoch 020 - train 0.70503 | val 0.70260
  Epoch 021 - train 0.70198 | val 0.70120
  Classification -> best τ=0.490 (val F1=0.0602)
  Directional -> Accuracy: 0.4909, MCC: -0.0133, F1: 0.5000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.71275 | val 0.69158
  Epoch 020 - train 0.68494 | val 0.68992
  Epoch 021 - train 0.71115 | val 0.68933
  Classification -> best τ=0.505 (val F1=0.0259)
  Directional -> Accuracy: 0.4737, MCC: -0.0644, F1: 0.5238

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70523 | val 0.69265
  Epoch 020 - train 0.69947 | val 0.69614
  Epoch 021 - train 0.73123 | val 0.69613
  Classification -> best τ=0.460 (val F1=0.2048)
  Directional -> Accuracy: 0.4878, MCC: -0.0101, F1: 0.6182

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71291 | val 0.70949
  Epoch 020 - train 0.69292 | val 0.70642
  Epoch 021 - train 0.68950 | val 0.70482
  Classification -> best τ=0.480 (val F1=0.2241)
  Directional -> Accuracy: 0.6098, MCC: 0.1871, F1: 0.6923

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68089 | val 0.68309
  Epoch 020 - train 0.68575 | val 0.68206
  Epoch 021 - train 0.69664 | val 0.68403
  Classification -> best τ=0.480 (val F1=0.2382)
  Directional -> Accuracy: 0.6042, MCC: 0.2044, F1: 0.6415

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70842 | val 0.69362
  Epoch 020 - train 0.66841 | val 0.68556
  Epoch 030 - train 0.68348 | val 0.67937
  Classification -> best τ=0.405 (val F1=0.2696)
  Directional -> Accuracy: 0.5493, MCC: 0.0976, F1: 0.5789

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69814 | val 0.70627
  Epoch 020 - train 0.70810 | val 0.70386
  Epoch 026 - train 0.69890 | val 0.70859
  Classification -> best τ=0.560 (val F1=0.3520)
  Directional -> Accuracy: 0.4762, MCC: -0.0302, F1: 0.5600

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.68683 | val 0.66472
  Epoch 020 - train 0.68892 | val 0.66197
  Epoch 030 - train 0.68544 | val 0.66007
  Classification -> best τ=0.355 (val F1=0.3828)
  Directional -> Accuracy: 0.5538, MCC: 0.1109, F1: 0.5797

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.72509 | val 0.70236
  Epoch 020 - train 0.71840 | val 0.69979
  Epoch 021 - train 0.70462 | val 0.69812
  Classification -> best τ=0.510 (val F1=0.1796)
  Directional -> Accuracy: 0.6750, MCC: 0.3831, F1: 0.6286

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.71483 | val 0.70057
  Epoch 020 - train 0.67979 | val 0.69909
  Epoch 021 - train 0.69949 | val 0.69831
  Classification -> best τ=0.460 (val F1=0.1197)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69609 | val 0.68683
  Epoch 020 - train 0.68632 | val 0.69896
  Epoch 026 - train 0.69815 | val 0.69802
  Classification -> best τ=0.415 (val F1=0.1907)
  Directional -> Accuracy: 0.3778, MCC: -0.2255, F1: 0.4167

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68946 | val 0.70682
  Epoch 020 - train 0.68592 | val 0.70606
  Epoch 021 - train 0.67223 | val 0.70429
  Classification -> best τ=0.545 (val F1=0.2067)
  Directional -> Accuracy: 0.4783, MCC: -0.2812, F1: 0.0769

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70436 | val 0.72466
  Epoch 020 - train 0.69307 | val 0.71952
  Epoch 021 - train 0.69497 | val 0.72316
  Classification -> best τ=0.590 (val F1=0.1237)
  Directional -> Accuracy: 0.4795, MCC: -0.0829, F1: 0.1364

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70804 | val 0.70057
  Epoch 020 - train 0.70232 | val 0.70054
  Epoch 021 - train 0.68395 | val 0.69877
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.72124 | val 0.70828
  Epoch 020 - train 0.68951 | val 0.70754
  Epoch 021 - train 0.69776 | val 0.70690
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5854, MCC: 0.0000, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.72453 | val 0.71209
  Epoch 020 - train 0.71627 | val 0.70892
  Epoch 021 - train 0.72115 | val 0.71084
  Classification -> best τ=0.485 (val F1=0.4688)
  Directional -> Accuracy: 0.6522, MCC: 0.2043, F1: 0.4286

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.72356 | val 0.73846
  Epoch 020 - train 0.70285 | val 0.73654
  Epoch 021 - train 0.73521 | val 0.74408
  Classification -> best τ=0.455 (val F1=0.1956)
  Directional -> Accuracy: 0.6111, MCC: 0.2094, F1: 0.6557

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.71890 | val 0.69326
  Epoch 020 - train 0.70731 | val 0.69320
  Epoch 021 - train 0.70148 | val 0.69256
  Classification -> best τ=0.480 (val F1=0.1771)
  Directional -> Accuracy: 0.5455, MCC: 0.1107, F1: 0.2857

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69778 | val 0.71815
  Epoch 020 - train 0.69687 | val 0.71660
  Epoch 021 - train 0.70367 | val 0.71710
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69440 | val 0.68499
  Epoch 020 - train 0.69286 | val 0.68232
  Epoch 021 - train 0.70263 | val 0.68393
  Classification -> best τ=0.505 (val F1=0.1657)
  Directional -> Accuracy: 0.4259, MCC: -0.2517, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-18 23:54:45,254] Trial 6 finished with value: 0.1713159057901227 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.4, 'batch_size': 16, 'learning_rate': 1.191348001821291e-05, 'weight_decay': 5.062769720723731e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.0850325017642364, 'early_stopping_min_delta': 0.006632794392615322}. Best is trial 4 with value: 0.2326372255203152.

  Epoch 026 - train 0.69758 | val 0.68370
  Classification -> best τ=0.465 (val F1=0.3516)
  Directional -> Accuracy: 0.4237, MCC: -0.2435, F1: 0.5952

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1713159057901227
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68258 | val 0.68480
  Epoch 016 - train 0.71717 | val 0.68379
  Classification -> best τ=0.480 (val F1=0.1979)
  Directional -> Accuracy: 0.5811, MCC: 0.1498, F1: 0.5231

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69029 | val 0.71119
  Epoch 016 - train 0.70340 | val 0.71718
  Classification -> best τ=0.545 (val F1=0.1847)
  Directional -> Accuracy: 0.6047, MCC: 0.1023, F1: 0.7213

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70690 | val 0.67918
  Epoch 020 - train 0.71364 | val 0.67760
  Epoch 024 - train 0.72961 | val 0.67747
  Classification -> best τ=0.450 (val F1=0.2614)
  Directional -> Accuracy: 0.5455, MCC: 0.1026, F1: 0.6875

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70148 | val 0.73706
  Epoch 016 - train 0.69957 | val 0.74451
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69936 | val 0.69170
  Epoch 020 - train 0.68913 | val 0.68674
  Epoch 027 - train 0.71220 | val 0.68701
  Classification -> best τ=0.505 (val F1=0.2992)
  Directional -> Accuracy: 0.4583, MCC: -0.0969, F1: 0.0714

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69469 | val 0.69470
  Epoch 016 - train 0.67669 | val 0.71052
  Classification -> best τ=0.490 (val F1=0.2567)
  Directional -> Accuracy: 0.5227, MCC: 0.1525, F1: 0.0870

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.73598 | val 0.71047
  Epoch 016 - train 0.70741 | val 0.71214
  Classification -> best τ=0.515 (val F1=0.1287)
  Directional -> Accuracy: 0.5758, MCC: 0.2050, F1: 0.5882

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69767 | val 0.67231
  Epoch 016 - train 0.71701 | val 0.67568
  Classification -> best τ=0.475 (val F1=0.2928)
  Directional -> Accuracy: 0.4615, MCC: 0.0278, F1: 0.5882

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.71066 | val 0.68725
  Epoch 016 - train 0.71191 | val 0.68673
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68227 | val 0.70732
  Epoch 016 - train 0.68668 | val 0.70733
  Classification -> best τ=0.535 (val F1=0.1644)
  Directional -> Accuracy: 0.5224, MCC: -0.0357, F1: 0.3043

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.71710 | val 0.68023
  Epoch 019 - train 0.69568 | val 0.68735
  Classification -> best τ=0.435 (val F1=0.1162)
  Directional -> Accuracy: 0.4681, MCC: 0.1325, F1: 0.6269

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70488 | val 0.70189
  Epoch 016 - train 0.69694 | val 0.70438
  Classification -> best τ=0.510 (val F1=0.0575)
  Directional -> Accuracy: 0.5455, MCC: 0.1841, F1: 0.3243

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68471 | val 0.67456
  Epoch 020 - train 0.69400 | val 0.66727
  Epoch 028 - train 0.69747 | val 0.66983
  Classification -> best τ=0.505 (val F1=0.4495)
  Directional -> Accuracy: 0.4583, MCC: -0.1600, F1: 0.1333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70783 | val 0.72428
  Epoch 016 - train 0.69871 | val 0.72093
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69190 | val 0.70819
  Epoch 016 - train 0.69694 | val 0.70962
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70761 | val 0.72575
  Epoch 016 - train 0.70993 | val 0.72298
  Classification -> best τ=0.470 (val F1=0.0439)
  Directional -> Accuracy: 0.5075, MCC: 0.0116, F1: 0.5352

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.73297 | val 0.75172
  Epoch 016 - train 0.73580 | val 0.75691
  Classification -> best τ=0.460 (val F1=0.1953)
  Directional -> Accuracy: 0.6429, MCC: 0.2111, F1: 0.7368

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.72565 | val 0.73862
  Epoch 016 - train 0.71790 | val 0.73890
  Classification -> best τ=0.465 (val F1=0.1334)
  Directional -> Accuracy: 0.5479, MCC: 0.1318, F1: 0.5479

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69350 | val 0.70545
  Epoch 016 - train 0.70747 | val 0.70687
  Classification -> best τ=0.475 (val F1=0.0853)
  Directional -> Accuracy: 0.4839, MCC: 0.0271, F1: 0.4286

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.71753 | val 0.69416
  Epoch 016 - train 0.70503 | val 0.69333
  Classification -> best τ=0.455 (val F1=0.1512)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69188 | val 0.69337
  Epoch 016 - train 0.68692 | val 0.69422
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.73588 | val 0.71991
  Epoch 016 - train 0.71667 | val 0.72391
  Classification -> best τ=0.485 (val F1=0.1348)
  Directional -> Accuracy: 0.5079, MCC: 0.0261, F1: 0.5974

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.72324 | val 0.71237
  Epoch 016 - train 0.69721 | val 0.71334
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5818, MCC: 0.0000, F1: 0.7356

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.69941 | val 0.68399
  Epoch 020 - train 0.69877 | val 0.68416
  Epoch 022 - train 0.70514 | val 0.68439
  Classification -> best τ=0.495 (val F1=0.2001)
  Directional -> Accuracy: 0.4921, MCC: -0.1179, F1: 0.0588

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.72339 | val 0.69994
  Epoch 016 - train 0.70002 | val 0.70190
  Classification -> best τ=0.500 (val F1=0.0124)
  Directional -> Accuracy: 0.4528, MCC: -0.1508, F1: 0.5672

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71233 | val 0.70849
  Epoch 016 - train 0.72483 | val 0.70459
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70898 | val 0.71675
  Epoch 016 - train 0.68378 | val 0.72952
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70115 | val 0.68400
  Epoch 016 - train 0.71027 | val 0.68407
  Classification -> best τ=0.485 (val F1=0.1657)
  Directional -> Accuracy: 0.4259, MCC: -0.1628, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.71049 | val 0.73525
  Epoch 016 - train 0.70725 | val 0.75874
  Classification -> best τ=0.540 (val F1=0.0976)
  Directional -> Accuracy: 0.5750, MCC: 0.1502, F1: 0.5641

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72107 | val 0.70837
  Epoch 016 - train 0.71804 | val 0.72031
  Classification -> best τ=0.500 (val F1=0.0137)
  Directional -> Accuracy: 0.4750, MCC: 0.0060, F1: 0.3226

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69666 | val 0.70312
  Epoch 016 - train 0.70246 | val 0.70935
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70230 | val 0.68643
  Epoch 020 - train 0.70605 | val 0.68546
  Epoch 021 - train 0.69526 | val 0.68539
  Classification -> best τ=0.455 (val F1=0.2879)
  Directional -> Accuracy: 0.5857, MCC: 0.1335, F1: 0.6813

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70550 | val 0.69793
  Epoch 016 - train 0.69765 | val 0.70521
  Classification -> best τ=0.495 (val F1=0.2257)
  Directional -> Accuracy: 0.6122, MCC: 0.2698, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.71859 | val 0.71360
  Epoch 016 - train 0.70287 | val 0.71400
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71582 | val 0.69619
  Epoch 016 - train 0.72093 | val 0.69722
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.74807 | val 0.70432
  Epoch 016 - train 0.71846 | val 0.70837
  Classification -> best τ=0.510 (val F1=0.0402)
  Directional -> Accuracy: 0.5185, MCC: 0.1685, F1: 0.6486

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.72516 | val 0.68989
  Epoch 020 - train 0.73858 | val 0.67692
  Epoch 030 - train 0.73339 | val 0.68118
  Classification -> best τ=0.475 (val F1=0.3811)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.72931 | val 0.68739
  Epoch 016 - train 0.70723 | val 0.69352
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70719 | val 0.70609
  Epoch 016 - train 0.69121 | val 0.70585
  Classification -> best τ=0.535 (val F1=0.0525)
  Directional -> Accuracy: 0.4583, MCC: -0.1158, F1: 0.5979

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.66263 | val 0.80159
  Epoch 016 - train 0.66203 | val 0.90099
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69246 | val 0.69216
  Epoch 016 - train 0.71978 | val 0.69508
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5897, MCC: 0.0000, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69541 | val 0.71930
  Epoch 016 - train 0.70297 | val 0.74419
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70864 | val 0.68036
  Epoch 020 - train 0.71125 | val 0.67788
  Epoch 023 - train 0.72327 | val 0.67885
  Classification -> best τ=0.560 (val F1=0.2539)
  Directional -> Accuracy: 0.4906, MCC: 0.0858, F1: 0.2286

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68574 | val 0.71538
  Epoch 016 - train 0.70090 | val 0.71848
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.72633 | val 0.68391
  Epoch 020 - train 0.70219 | val 0.68413
  Epoch 022 - train 0.71961 | val 0.68421
  Classification -> best τ=0.550 (val F1=0.2441)
  Directional -> Accuracy: 0.4902, MCC: -0.0234, F1: 0.4348

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.71924 | val 0.69603
  Epoch 016 - train 0.70220 | val 0.69657
  Classification -> best τ=0.470 (val F1=0.1168)
  Directional -> Accuracy: 0.4717, MCC: -0.0743, F1: 0.5758

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68874 | val 0.67400
  Epoch 020 - train 0.71327 | val 0.67242

[I 2026-02-18 23:58:31,215] Trial 7 finished with value: 0.11896385792242264 and parameters: {'feature_set': 'emotion', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.5, 'batch_size': 32, 'learning_rate': 2.1652451500892922e-06, 'weight_decay': 0.00033404491258125533, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.666616166228642, 'early_stopping_min_delta': 0.004744477623438457}. Best is trial 4 with value: 0.2326372255203152.

  Epoch 030 - train 0.70625 | val 0.67367
  Classification -> best τ=0.490 (val F1=0.3467)
  Directional -> Accuracy: 0.5517, MCC: 0.0880, F1: 0.4583

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.11896385792242264
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60850 | val 0.94136
  Epoch 020 - train 0.51016 | val 1.27382
  Epoch 022 - train 0.45949 | val 1.34789
  Classification -> best τ=0.430 (val F1=0.1695)
  Directional -> Accuracy: 0.6000, MCC: 0.1824, F1: 0.3750

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.48205 | val 1.12404
  Epoch 020 - train 0.18461 | val 2.31549
  Epoch 022 - train 0.21585 | val 2.00359
  Classification -> best τ=0.375 (val F1=0.1902)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61724 | val 1.12357
  Epoch 020 - train 0.33432 | val 2.15730
  Epoch 021 - train 0.30042 | val 2.11555
  Classification -> best τ=0.525 (val F1=0.2740)
  Directional -> Accuracy: 0.4889, MCC: 0.0714, F1: 0.1481

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69124 | val 0.77840
  Epoch 020 - train 0.46843 | val 1.47961
  Epoch 021 - train 0.49575 | val 1.78709
  Classification -> best τ=0.380 (val F1=0.1705)
  Directional -> Accuracy: 0.4658, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55697 | val 1.14142
  Epoch 020 - train 0.24864 | val 2.68457
  Epoch 023 - train 0.18652 | val 3.30031
  Classification -> best τ=0.580 (val F1=0.4483)
  Directional -> Accuracy: 0.4694, MCC: -0.0637, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41210 | val 0.83149
  Epoch 020 - train 0.14451 | val 2.29510
  Epoch 021 - train 0.11173 | val 2.61723
  Classification -> best τ=0.520 (val F1=0.0998)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61380 | val 0.73614
  Epoch 020 - train 0.45753 | val 1.42514
  Epoch 026 - train 0.26069 | val 2.39631
  Classification -> best τ=0.395 (val F1=0.3341)
  Directional -> Accuracy: 0.4478, MCC: 0.0559, F1: 0.5647

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.51828 | val 1.71217
  Epoch 020 - train 0.36215 | val 4.02646
  Epoch 025 - train 0.21029 | val 2.86267
  Classification -> best τ=0.375 (val F1=0.2582)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41878 | val 0.91898
  Epoch 020 - train 0.09165 | val 2.03321
  Epoch 025 - train 0.05179 | val 1.99827
  Classification -> best τ=0.380 (val F1=0.2115)
  Directional -> Accuracy: 0.4681, MCC: 0.0596, F1: 0.6154

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62132 | val 0.70429
  Epoch 020 - train 0.48075 | val 0.94786
  Epoch 027 - train 0.31580 | val 1.55361
  Classification -> best τ=0.400 (val F1=0.3873)
  Directional -> Accuracy: 0.3824, MCC: -0.2491, F1: 0.5532

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59220 | val 1.06339
  Epoch 020 - train 0.22600 | val 1.98252
  Epoch 025 - train 0.11373 | val 2.33051
  Classification -> best τ=0.445 (val F1=0.2437)
  Directional -> Accuracy: 0.4792, MCC: -0.0182, F1: 0.5283

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57801 | val 1.13397
  Epoch 020 - train 0.41171 | val 1.98907
  Epoch 022 - train 0.37737 | val 2.31190
  Classification -> best τ=0.545 (val F1=0.0801)
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50311 | val 1.75836
  Epoch 020 - train 0.24275 | val 2.09282
  Epoch 025 - train 0.18593 | val 3.16376
  Classification -> best τ=0.440 (val F1=0.3668)
  Directional -> Accuracy: 0.4694, MCC: -0.0904, F1: 0.6286

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.54497 | val 0.70300
  Epoch 020 - train 0.25041 | val 1.28390
  Epoch 023 - train 0.21290 | val 1.12451
  Classification -> best τ=0.340 (val F1=0.3119)
  Directional -> Accuracy: 0.5593, MCC: 0.1387, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.61471 | val 1.46182
  Epoch 020 - train 0.45493 | val 0.97276
  Epoch 024 - train 0.41480 | val 1.33845
  Classification -> best τ=0.450 (val F1=0.2861)
  Directional -> Accuracy: 0.4600, MCC: 0.1266, F1: 0.6197

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53770 | val 1.75724
  Epoch 020 - train 0.31370 | val 4.00498
  Epoch 023 - train 0.26482 | val 4.07341
  Classification -> best τ=0.445 (val F1=0.2160)
  Directional -> Accuracy: 0.6029, MCC: 0.2259, F1: 0.7097

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62833 | val 2.35950
  Epoch 020 - train 0.47609 | val 3.01522
  Epoch 021 - train 0.43928 | val 3.06111
  Classification -> best τ=0.445 (val F1=0.1969)
  Directional -> Accuracy: 0.4737, MCC: -0.2012, F1: 0.6154

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62387 | val 0.76839
  Epoch 020 - train 0.48300 | val 1.64144
  Epoch 022 - train 0.44094 | val 2.11823
  Classification -> best τ=0.525 (val F1=0.2204)
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.49397 | val 1.21477
  Epoch 020 - train 0.24041 | val 2.68301
  Epoch 023 - train 0.14940 | val 2.50450
  Classification -> best τ=0.385 (val F1=0.2503)
  Directional -> Accuracy: 0.5397, MCC: 0.1733, F1: 0.4727

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53477 | val 0.94590
  Epoch 020 - train 0.34085 | val 1.70516
  Epoch 021 - train 0.30457 | val 1.50029
  Classification -> best τ=0.490 (val F1=0.1663)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53721 | val 1.34729
  Epoch 020 - train 0.21520 | val 2.93954
  Epoch 021 - train 0.21495 | val 3.26500
  Classification -> best τ=0.550 (val F1=0.1090)
  Directional -> Accuracy: 0.4348, MCC: -0.2734, F1: 0.5806

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.60895 | val 1.40135
  Epoch 020 - train 0.33539 | val 2.34272
  Epoch 021 - train 0.30595 | val 2.76048
  Classification -> best τ=0.445 (val F1=0.1741)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57775 | val 1.02899
  Epoch 020 - train 0.43837 | val 1.49575
  Epoch 021 - train 0.39831 | val 1.39098
  Classification -> best τ=0.615 (val F1=0.2514)
  Directional -> Accuracy: 0.5000, MCC: 0.1211, F1: 0.3333

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.52868 | val 0.71702
  Epoch 020 - train 0.33354 | val 0.85296
  Epoch 021 - train 0.30735 | val 0.86991
  Classification -> best τ=0.495 (val F1=0.0880)
  Directional -> Accuracy: 0.5312, MCC: 0.0301, F1: 0.2857

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50854 | val 0.92163
  Epoch 020 - train 0.24599 | val 1.76528
  Epoch 022 - train 0.16689 | val 1.87744
  Classification -> best τ=0.415 (val F1=0.3993)
  Directional -> Accuracy: 0.5000, MCC: 0.0140, F1: 0.4706

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56854 | val 1.22442
  Epoch 020 - train 0.09779 | val 2.19669
  Epoch 021 - train 0.12552 | val 2.16474
  Classification -> best τ=0.515 (val F1=0.1682)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44603 | val 0.85949
  Epoch 020 - train 0.16781 | val 1.41393
  Epoch 021 - train 0.16720 | val 1.30709
  Classification -> best τ=0.535 (val F1=0.0615)
  Directional -> Accuracy: 0.5306, MCC: -0.0288, F1: 0.6462

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56369 | val 1.00871
  Epoch 020 - train 0.33909 | val 2.10021
  Epoch 023 - train 0.33308 | val 2.30615
  Classification -> best τ=0.470 (val F1=0.2228)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.40486 | val 0.78393
  Epoch 020 - train 0.15926 | val 1.02129
  Epoch 027 - train 0.11227 | val 1.27201
  Classification -> best τ=0.460 (val F1=0.3708)
  Directional -> Accuracy: 0.6053, MCC: 0.2088, F1: 0.7273

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46130 | val 1.12308
  Epoch 020 - train 0.21342 | val 1.40581
  Epoch 021 - train 0.20990 | val 1.56100
  Classification -> best τ=0.555 (val F1=0.2193)
  Directional -> Accuracy: 0.4634, MCC: -0.2210, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55021 | val 0.72356
  Epoch 020 - train 0.28226 | val 1.67048
  Epoch 026 - train 0.23014 | val 1.78749
  Classification -> best τ=0.700 (val F1=0.1920)
  Directional -> Accuracy: 0.4634, MCC: 0.0096, F1: 0.2667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45315 | val 0.91314
  Epoch 020 - train 0.08737 | val 1.69637
  Epoch 023 - train 0.03962 | val 2.06342
  Classification -> best τ=0.450 (val F1=0.2739)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58223 | val 0.75027
  Epoch 020 - train 0.43637 | val 1.48998
  Epoch 023 - train 0.37798 | val 1.90246
  Classification -> best τ=0.205 (val F1=0.2748)
  Directional -> Accuracy: 0.5493, MCC: 0.1386, F1: 0.5152

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.48391 | val 1.51358
  Epoch 020 - train 0.16474 | val 2.66074
  Epoch 022 - train 0.16591 | val 3.57408
  Classification -> best τ=0.535 (val F1=0.2960)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60426 | val 0.92699
  Epoch 020 - train 0.43639 | val 1.42718
  Epoch 022 - train 0.54470 | val 1.54815
  Classification -> best τ=0.320 (val F1=0.3218)
  Directional -> Accuracy: 0.6000, MCC: 0.1844, F1: 0.6486

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.35977 | val 0.91557
  Epoch 020 - train 0.11924 | val 1.30818
  Epoch 023 - train 0.08076 | val 1.79225
  Classification -> best τ=0.450 (val F1=0.3475)
  Directional -> Accuracy: 0.6250, MCC: 0.2503, F1: 0.6341

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49038 | val 0.99121
  Epoch 020 - train 0.31453 | val 0.95476
  Epoch 023 - train 0.24292 | val 1.33890
  Classification -> best τ=0.445 (val F1=0.2203)
  Directional -> Accuracy: 0.4545, MCC: -0.0637, F1: 0.5161

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54113 | val 1.00653
  Epoch 020 - train 0.20090 | val 2.64966
  Epoch 023 - train 0.16889 | val 2.13859
  Classification -> best τ=0.485 (val F1=0.2023)
  Directional -> Accuracy: 0.7111, MCC: 0.3593, F1: 0.7869

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43771 | val 0.70774
  Epoch 020 - train 0.15387 | val 1.16327
  Epoch 025 - train 0.07772 | val 1.43566
  Classification -> best τ=0.545 (val F1=0.5017)
  Directional -> Accuracy: 0.3043, MCC: -0.2143, F1: 0.4667

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.62022 | val 0.88887
  Epoch 020 - train 0.48501 | val 1.06844
  Epoch 028 - train 0.29915 | val 2.31202
  Classification -> best τ=0.240 (val F1=0.2637)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56717 | val 0.98954
  Epoch 020 - train 0.32215 | val 1.85224
  Epoch 025 - train 0.20701 | val 2.68787
  Classification -> best τ=0.525 (val F1=0.2887)
  Directional -> Accuracy: 0.4545, MCC: -0.1179, F1: 0.2000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50916 | val 0.58926
  Epoch 020 - train 0.20218 | val 1.51269
  Epoch 030 - train 0.02222 | val 1.46952
  Epoch 031 - train 0.03319 | val 1.54559
  Classification -> best τ=0.705 (val F1=0.6070)
  Directional -> Accuracy: 0.4878, MCC: -0.0462, F1: 0.5532

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.52986 | val 0.85259
  Epoch 020 - train 0.11147 | val 1.21113
  Epoch 024 - train 0.07452 | val 1.56284
  Classification -> best τ=0.640 (val F1=0.1841)
  Directional -> Accuracy: 0.6304, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.57947 | val 1.39939
  Epoch 020 - train 0.33194 | val 2.06809
  Epoch 021 - train 0.33821 | val 2.28110
  Classification -> best τ=0.475 (val F1=0.2697)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47968 | val 1.09258
  Epoch 020 - train 0.17344 | val 2.58916
  Epoch 021 - train 0.18619 | val 2.95956
  Classification -> best τ=0.505 (val F1=0.3169)
  Directional -> Accuracy: 0.5636, MCC: 0.1800, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.50524 | val 0.96489
  Epoch 020 - train 0.14912 | val 1.78867
  Epoch 025 - train 0.07485 | val 2.22142
  Classification -> best τ=0.645 (val F1=0.1746)
  Directional -> Accuracy: 0.5192, MCC: 0.0410, F1: 0.5902

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.50848 | val 1.22942
  Epoch 020 - train 0.21553 | val 1.76228
  Epoch 027 - train 0.05407 | val 1.91799
  Classification -> best τ=0.390 (val F1=0.2325)

[I 2026-02-19 00:06:32,095] Trial 8 finished with value: 0.25047840867205245 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 0.004656455322132289, 'weight_decay': 7.2070642136546435e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.2395500848575896, 'early_stopping_min_delta': 0.004319551910167796}. Best is trial 8 with value: 0.25047840867205245.

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25047840867205245
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54659 | val 0.90657
  Epoch 013 - train 0.53473 | val 1.04048
  Classification -> best τ=0.630 (val F1=0.1771)
  Directional -> Accuracy: 0.5200, MCC: -0.0711, F1: 0.1000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55001 | val 0.84289
  Epoch 011 - train 0.53485 | val 0.89433
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58329 | val 0.75463
  Epoch 013 - train 0.52886 | val 0.86473
  Classification -> best τ=0.540 (val F1=0.2641)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57979 | val 1.49143
  Epoch 011 - train 0.57927 | val 2.00659
  Classification -> best τ=0.510 (val F1=0.2279)
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52920 | val 0.96562
  Epoch 014 - train 0.48217 | val 1.37577
  Classification -> best τ=0.530 (val F1=0.3557)
  Directional -> Accuracy: 0.4490, MCC: -0.1061, F1: 0.4906

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54749 | val 0.97899
  Epoch 011 - train 0.53802 | val 1.01586
  Classification -> best τ=0.530 (val F1=0.2294)
  Directional -> Accuracy: 0.4667, MCC: -0.0653, F1: 0.4783

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60792 | val 0.73745
  Epoch 013 - train 0.55909 | val 0.78526
  Classification -> best τ=0.465 (val F1=0.2945)
  Directional -> Accuracy: 0.4925, MCC: 0.1229, F1: 0.5750

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53390 | val 1.27841
  Epoch 011 - train 0.54297 | val 1.42916
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56097 | val 0.66737
  Epoch 020 - train 0.45275 | val 0.74044
  Classification -> best τ=0.550 (val F1=0.5024)
  Directional -> Accuracy: 0.5106, MCC: -0.1207, F1: 0.0800

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55237 | val 0.81956
  Epoch 011 - train 0.54430 | val 0.84832
  Classification -> best τ=0.510 (val F1=0.0147)
  Directional -> Accuracy: 0.4118, MCC: -0.1417, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58129 | val 0.84339
  Epoch 011 - train 0.56387 | val 0.93223
  Classification -> best τ=0.510 (val F1=0.0861)
  Directional -> Accuracy: 0.5000, MCC: 0.0070, F1: 0.5000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.52486 | val 1.10556
  Epoch 011 - train 0.50204 | val 1.15674
  Classification -> best τ=0.495 (val F1=0.1792)
  Directional -> Accuracy: 0.6071, MCC: 0.2766, F1: 0.4762

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52532 | val 2.23304
  Epoch 011 - train 0.50991 | val 2.55531
  Classification -> best τ=0.490 (val F1=0.1505)
  Directional -> Accuracy: 0.4490, MCC: -0.1552, F1: 0.6087

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58910 | val 0.81300
  Epoch 014 - train 0.53507 | val 0.96714
  Classification -> best τ=0.515 (val F1=0.3087)
  Directional -> Accuracy: 0.5763, MCC: 0.1533, F1: 0.6269

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55235 | val 0.77513
  Epoch 011 - train 0.54102 | val 0.80229
  Classification -> best τ=0.510 (val F1=0.2060)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57445 | val 0.74973
  Epoch 014 - train 0.52960 | val 0.86992
  Classification -> best τ=0.525 (val F1=0.3355)
  Directional -> Accuracy: 0.5000, MCC: -0.0070, F1: 0.5405

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.58088 | val 1.44889
  Epoch 011 - train 0.56620 | val 1.43371
  Classification -> best τ=0.540 (val F1=0.1361)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56691 | val 2.75043
  Epoch 011 - train 0.55562 | val 1.70568
  Classification -> best τ=0.485 (val F1=0.1537)
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56036 | val 1.15990
  Epoch 012 - train 0.55988 | val 1.34493
  Classification -> best τ=0.470 (val F1=0.3021)
  Directional -> Accuracy: 0.4921, MCC: 0.1579, F1: 0.3043

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54883 | val 0.89465
  Epoch 019 - train 0.41388 | val 1.00348
  Classification -> best τ=0.565 (val F1=0.3105)
  Directional -> Accuracy: 0.5205, MCC: 0.1350, F1: 0.3396

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.55538 | val 0.78730
  Epoch 011 - train 0.54484 | val 0.82676
  Classification -> best τ=0.460 (val F1=0.0996)
  Directional -> Accuracy: 0.5870, MCC: 0.0062, F1: 0.7246

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.56291 | val 0.95100
  Epoch 011 - train 0.58005 | val 1.00036
  Classification -> best τ=0.550 (val F1=0.1853)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54933 | val 1.61863
  Epoch 011 - train 0.53913 | val 1.68912
  Classification -> best τ=0.510 (val F1=0.2474)
  Directional -> Accuracy: 0.5714, MCC: 0.1443, F1: 0.6000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56136 | val 1.22754
  Epoch 011 - train 0.52366 | val 1.30384
  Classification -> best τ=0.435 (val F1=0.1912)
  Directional -> Accuracy: 0.5625, MCC: 0.1604, F1: 0.6216

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53240 | val 0.66972
  Epoch 017 - train 0.42834 | val 0.75944
  Classification -> best τ=0.485 (val F1=0.3764)
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54272 | val 0.80891
  Epoch 011 - train 0.53960 | val 0.84290
  Classification -> best τ=0.495 (val F1=0.2829)
  Directional -> Accuracy: 0.4884, MCC: -0.1075, F1: 0.2667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55279 | val 1.12348
  Epoch 011 - train 0.53790 | val 1.32479
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5918, MCC: 0.0000, F1: 0.7436

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52921 | val 1.01027
  Epoch 011 - train 0.53949 | val 1.04766
  Classification -> best τ=0.480 (val F1=0.2577)
  Directional -> Accuracy: 0.6182, MCC: 0.2193, F1: 0.6866

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59854 | val 0.74686
  Epoch 011 - train 0.58274 | val 0.76808
  Classification -> best τ=0.485 (val F1=0.2550)
  Directional -> Accuracy: 0.6053, MCC: 0.1975, F1: 0.6512

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56515 | val 0.87543
  Epoch 011 - train 0.55761 | val 0.92627
  Classification -> best τ=0.545 (val F1=0.1617)
  Directional -> Accuracy: 0.4878, MCC: -0.0358, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55433 | val 0.84523
  Epoch 015 - train 0.50010 | val 1.30318
  Classification -> best τ=0.505 (val F1=0.1336)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55763 | val 0.72250
  Epoch 015 - train 0.49117 | val 0.80173
  Classification -> best τ=0.505 (val F1=0.3333)
  Directional -> Accuracy: 0.5000, MCC: -0.0334, F1: 0.6250

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53366 | val 1.05673
  Epoch 014 - train 0.50040 | val 1.23102
  Classification -> best τ=0.370 (val F1=0.3082)
  Directional -> Accuracy: 0.5352, MCC: 0.1239, F1: 0.4762

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55425 | val 0.77890
  Epoch 011 - train 0.56524 | val 0.83810
  Classification -> best τ=0.530 (val F1=0.3934)
  Directional -> Accuracy: 0.4524, MCC: -0.2644, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58306 | val 1.04599
  Epoch 012 - train 0.56524 | val 1.08412
  Classification -> best τ=0.430 (val F1=0.3577)
  Directional -> Accuracy: 0.5231, MCC: -0.0228, F1: 0.6353

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.53901 | val 0.73630
  Epoch 015 - train 0.47975 | val 0.86405
  Classification -> best τ=0.420 (val F1=0.2268)
  Directional -> Accuracy: 0.7000, MCC: 0.4127, F1: 0.6842

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51853 | val 0.66998
  Epoch 020 - train 0.43763 | val 0.70634
  Epoch 022 - train 0.42100 | val 0.72494
  Classification -> best τ=0.510 (val F1=0.3689)
  Directional -> Accuracy: 0.4000, MCC: -0.1797, F1: 0.5075

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52975 | val 1.84563
  Epoch 011 - train 0.49483 | val 2.15037
  Classification -> best τ=0.535 (val F1=0.3216)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.58070 | val 0.61868
  Epoch 020 - train 0.46212 | val 0.75881
  Epoch 021 - train 0.45277 | val 0.77131
  Classification -> best τ=0.625 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53210 | val 1.82289
  Epoch 011 - train 0.52385 | val 2.11911
  Classification -> best τ=0.485 (val F1=0.2042)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57263 | val 0.75500
  Epoch 011 - train 0.57233 | val 0.77431
  Classification -> best τ=0.485 (val F1=0.2843)
  Directional -> Accuracy: 0.4773, MCC: -0.1525, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58587 | val 0.70198
  Epoch 011 - train 0.58803 | val 0.70796
  Classification -> best τ=0.495 (val F1=0.2467)
  Directional -> Accuracy: 0.4390, MCC: 0.0111, F1: 0.2069

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56104 | val 0.80512
  Epoch 011 - train 0.52003 | val 0.83613
  Classification -> best τ=0.550 (val F1=0.2231)
  Directional -> Accuracy: 0.6304, MCC: 0.0576, F1: 0.1053

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.59661 | val 0.77874
  Epoch 011 - train 0.57379 | val 0.80132
  Classification -> best τ=0.500 (val F1=0.0428)
  Directional -> Accuracy: 0.6111, MCC: 0.2236, F1: 0.6316

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58309 | val 1.27821
  Epoch 011 - train 0.56350 | val 1.29799
  Classification -> best τ=0.520 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57242 | val 0.72760
  Epoch 014 - train 0.52913 | val 0.75879
  Classification -> best τ=0.420 (val F1=0.1701)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54044 | val 1.30185
  Epoch 011 - train 0.55655 | val 1.06594
  Classification -> best τ=0.455 (val F1=0.1626)
  Directional -> Accuracy: 0.6481, MCC: 0.3001, F1: 0.6415

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57816 | val 1.20394
  Epoch 013 - train 0.53228 | val 1.28412

[I 2026-02-19 00:07:01,022] Trial 9 finished with value: 0.22458701220629576 and parameters: {'feature_set': 'sentinment', 'model_type': 'LSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 0.0016113223642810206, 'weight_decay': 2.2096469207359042e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.7120149473005991, 'early_stopping_min_delta': 0.0034471601008460697}. Best is trial 8 with value: 0.25047840867205245.

  Classification -> best τ=0.475 (val F1=0.0322)
  Directional -> Accuracy: 0.4576, MCC: -0.1216, F1: 0.2727

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22458701220629576
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54041 | val 1.33722
  Epoch 020 - train 0.15604 | val 2.19260
  Epoch 021 - train 0.08054 | val 2.51258
  Classification -> best τ=0.490 (val F1=0.1265)
  Directional -> Accuracy: 0.5000, MCC: 0.0273, F1: 0.5316

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.36825 | val 1.54549
  Epoch 020 - train 0.08499 | val 2.87175
  Epoch 021 - train 0.08018 | val 2.85748
  Classification -> best τ=0.540 (val F1=0.3399)
  Directional -> Accuracy: 0.3953, MCC: -0.1332, F1: 0.3158

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.37780 | val 1.43216
  Epoch 020 - train 0.03201 | val 2.93588
  Epoch 023 - train 0.01449 | val 3.40504
  Classification -> best τ=0.585 (val F1=0.3327)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.53308 | val 1.98021
  Epoch 020 - train 0.14541 | val 5.42292
  Epoch 022 - train 0.07792 | val 5.59228
  Classification -> best τ=0.400 (val F1=0.1890)
  Directional -> Accuracy: 0.5139, MCC: -0.1555, F1: 0.6789

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46632 | val 0.81480
  Epoch 020 - train 0.07746 | val 2.15999
  Epoch 025 - train 0.01934 | val 2.78269
  Classification -> best τ=0.440 (val F1=0.3731)
  Directional -> Accuracy: 0.5625, MCC: 0.1180, F1: 0.6316

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.34283 | val 1.03913
  Epoch 020 - train 0.08277 | val 2.35480
  Epoch 023 - train 0.05459 | val 2.54253
  Classification -> best τ=0.470 (val F1=0.3491)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58972 | val 0.84565
  Epoch 020 - train 0.26276 | val 1.18580
  Epoch 030 - train 0.01155 | val 1.65615
  Epoch 033 - train 0.00621 | val 1.71450
  Classification -> best τ=0.375 (val F1=0.2982)
  Directional -> Accuracy: 0.5303, MCC: 0.0561, F1: 0.4746

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.38900 | val 1.29581
  Epoch 020 - train 0.18521 | val 2.63746
  Epoch 025 - train 0.08916 | val 3.44366
  Classification -> best τ=0.420 (val F1=0.1925)
  Directional -> Accuracy: 0.4615, MCC: -0.0615, F1: 0.4615

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.26433 | val 1.46885
  Epoch 020 - train 0.01679 | val 2.75467
  Epoch 022 - train 0.00984 | val 3.00117
  Classification -> best τ=0.595 (val F1=0.3292)
  Directional -> Accuracy: 0.4130, MCC: -0.1202, F1: 0.5263

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46802 | val 0.86919
  Epoch 020 - train 0.05216 | val 2.32227
  Epoch 024 - train 0.01432 | val 2.77779
  Classification -> best τ=0.590 (val F1=0.1808)
  Directional -> Accuracy: 0.4627, MCC: -0.1159, F1: 0.3333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43130 | val 1.03320
  Epoch 020 - train 0.08517 | val 2.14759
  Epoch 024 - train 0.02738 | val 2.57018
  Classification -> best τ=0.475 (val F1=0.1357)
  Directional -> Accuracy: 0.4681, MCC: 0.1325, F1: 0.6269

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.46987 | val 0.80317
  Epoch 020 - train 0.11143 | val 1.67078
  Epoch 023 - train 0.05569 | val 2.08911
  Classification -> best τ=0.625 (val F1=0.1908)
  Directional -> Accuracy: 0.4545, MCC: -0.1437, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.35351 | val 1.22411
  Epoch 020 - train 0.05199 | val 1.40066
  Epoch 028 - train 0.00734 | val 1.73654
  Classification -> best τ=0.655 (val F1=0.3233)
  Directional -> Accuracy: 0.4375, MCC: -0.1840, F1: 0.1818

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.42391 | val 0.88252
  Epoch 020 - train 0.04861 | val 2.00378
  Epoch 021 - train 0.04265 | val 2.23184
  Classification -> best τ=0.325 (val F1=0.3229)
  Directional -> Accuracy: 0.6034, MCC: 0.3179, F1: 0.7229

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41609 | val 1.38342
  Epoch 020 - train 0.07733 | val 3.03388
  Epoch 021 - train 0.06344 | val 3.30000
  Classification -> best τ=0.455 (val F1=0.1487)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.45175 | val 1.80216
  Epoch 020 - train 0.13674 | val 2.23786
  Epoch 022 - train 0.08464 | val 2.26323
  Classification -> best τ=0.645 (val F1=0.1724)
  Directional -> Accuracy: 0.4627, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42306 | val 1.00746
  Epoch 020 - train 0.07654 | val 1.61332
  Epoch 021 - train 0.05593 | val 1.64446
  Classification -> best τ=0.635 (val F1=0.1631)
  Directional -> Accuracy: 0.3393, MCC: -0.2610, F1: 0.0513

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47943 | val 0.92810
  Epoch 020 - train 0.10510 | val 1.25141
  Epoch 021 - train 0.06909 | val 1.30296
  Classification -> best τ=0.505 (val F1=0.1713)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.47081 | val 0.75993
  Epoch 020 - train 0.07519 | val 1.17630
  Epoch 024 - train 0.01845 | val 1.61710
  Classification -> best τ=0.440 (val F1=0.3548)
  Directional -> Accuracy: 0.4677, MCC: 0.0966, F1: 0.2326

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47847 | val 0.82402
  Epoch 020 - train 0.15882 | val 1.45503
  Epoch 024 - train 0.05400 | val 2.14419
  Classification -> best τ=0.450 (val F1=0.2948)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.29923 | val 1.37452
  Epoch 020 - train 0.04653 | val 3.04830
  Epoch 021 - train 0.03827 | val 3.23474
  Classification -> best τ=0.555 (val F1=0.1929)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41609 | val 1.58967
  Epoch 020 - train 0.04139 | val 3.34794
  Epoch 021 - train 0.03380 | val 3.57366
  Classification -> best τ=0.330 (val F1=0.1211)
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46323 | val 1.18318
  Epoch 020 - train 0.10505 | val 1.85317
  Epoch 026 - train 0.01543 | val 2.51395
  Classification -> best τ=0.900 (val F1=0.4051)
  Directional -> Accuracy: 0.5455, MCC: 0.1682, F1: 0.4898

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48632 | val 0.70461
  Epoch 020 - train 0.13129 | val 1.08398
  Epoch 025 - train 0.03432 | val 1.68655
  Classification -> best τ=0.450 (val F1=0.3173)
  Directional -> Accuracy: 0.5556, MCC: 0.1348, F1: 0.6111

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50964 | val 1.30671
  Epoch 020 - train 0.20321 | val 1.85150
  Epoch 024 - train 0.12569 | val 2.54158
  Classification -> best τ=0.540 (val F1=0.3164)
  Directional -> Accuracy: 0.4340, MCC: -0.0929, F1: 0.1667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.24509 | val 0.89226
  Epoch 020 - train 0.00968 | val 2.52258
  Epoch 024 - train 0.00399 | val 2.72337
  Classification -> best τ=0.480 (val F1=0.2303)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.37841 | val 0.80429
  Epoch 020 - train 0.05749 | val 0.88148
  Epoch 029 - train 0.00375 | val 1.04988
  Classification -> best τ=0.660 (val F1=0.3320)
  Directional -> Accuracy: 0.4167, MCC: -0.0756, F1: 0.2222

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43306 | val 1.44181
  Epoch 020 - train 0.18032 | val 2.68105
  Epoch 021 - train 0.17262 | val 2.69414
  Classification -> best τ=0.390 (val F1=0.2011)
  Directional -> Accuracy: 0.5926, MCC: 0.1714, F1: 0.6562

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.31292 | val 2.07610
  Epoch 020 - train 0.05950 | val 2.70891
  Epoch 022 - train 0.03975 | val 2.94192
  Classification -> best τ=0.745 (val F1=0.3333)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43730 | val 0.89005
  Epoch 020 - train 0.07251 | val 1.46186
  Epoch 023 - train 0.02963 | val 1.62532
  Classification -> best τ=0.710 (val F1=0.1302)
  Directional -> Accuracy: 0.4750, MCC: -0.0161, F1: 0.4000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.39781 | val 0.70459
  Epoch 020 - train 0.03196 | val 1.48021
  Epoch 026 - train 0.00593 | val 1.72894
  Classification -> best τ=0.485 (val F1=0.4006)
  Directional -> Accuracy: 0.4894, MCC: -0.0815, F1: 0.6471

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53810 | val 0.81425
  Epoch 020 - train 0.14642 | val 1.44777
  Epoch 022 - train 0.10016 | val 1.58923
  Classification -> best τ=0.345 (val F1=0.2976)
  Directional -> Accuracy: 0.5429, MCC: 0.0250, F1: 0.6596

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42113 | val 1.09970
  Epoch 020 - train 0.04978 | val 2.22664
  Epoch 023 - train 0.02020 | val 2.53767
  Classification -> best τ=0.445 (val F1=0.3800)
  Directional -> Accuracy: 0.5102, MCC: 0.1311, F1: 0.6471

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48041 | val 1.05047
  Epoch 020 - train 0.17533 | val 2.06135
  Epoch 021 - train 0.15440 | val 2.29443
  Classification -> best τ=0.385 (val F1=0.2718)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.30010 | val 0.95014
  Epoch 020 - train 0.03200 | val 2.74966
  Epoch 025 - train 0.00822 | val 3.14961
  Classification -> best τ=0.425 (val F1=0.3095)
  Directional -> Accuracy: 0.5918, MCC: 0.1849, F1: 0.5238

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.39679 | val 1.62859
  Epoch 020 - train 0.09503 | val 4.17826
  Epoch 021 - train 0.07630 | val 4.65148
  Classification -> best τ=0.595 (val F1=0.3284)
  Directional -> Accuracy: 0.5556, MCC: 0.0853, F1: 0.3684

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.31092 | val 1.54497
  Epoch 020 - train 0.04437 | val 2.89043
  Epoch 021 - train 0.03316 | val 2.97514
  Classification -> best τ=0.420 (val F1=0.1856)
  Directional -> Accuracy: 0.4091, MCC: -0.0605, F1: 0.2778

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39927 | val 0.69359
  Epoch 020 - train 0.04239 | val 1.81566
  Epoch 026 - train 0.01069 | val 2.08182
  Classification -> best τ=0.445 (val F1=0.4524)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.4815

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55896 | val 0.94618
  Epoch 020 - train 0.26534 | val 1.20019
  Epoch 024 - train 0.16020 | val 1.72779
  Classification -> best τ=0.380 (val F1=0.3591)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49341 | val 0.96417
  Epoch 020 - train 0.16175 | val 1.89678
  Epoch 024 - train 0.09232 | val 2.54809
  Classification -> best τ=0.540 (val F1=0.2762)
  Directional -> Accuracy: 0.5349, MCC: 0.0973, F1: 0.3750

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.28400 | val 1.13470
  Epoch 020 - train 0.00761 | val 2.60317
  Epoch 024 - train 0.00388 | val 2.83065
  Classification -> best τ=0.390 (val F1=0.1918)
  Directional -> Accuracy: 0.5897, MCC: 0.0424, F1: 0.7333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.31420 | val 1.04099
  Epoch 020 - train 0.03316 | val 1.89397
  Epoch 023 - train 0.02086 | val 2.02321
  Classification -> best τ=0.515 (val F1=0.4183)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.45065 | val 0.76623
  Epoch 020 - train 0.03051 | val 1.44042
  Epoch 023 - train 0.00988 | val 1.65493
  Classification -> best τ=0.605 (val F1=0.1984)
  Directional -> Accuracy: 0.4717, MCC: 0.1262, F1: 0.0667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42772 | val 1.63538
  Epoch 020 - train 0.08198 | val 6.49568
  Epoch 021 - train 0.06582 | val 6.81395
  Classification -> best τ=0.450 (val F1=0.2530)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.45512 | val 1.01390
  Epoch 020 - train 0.06923 | val 1.79645
  Epoch 023 - train 0.03079 | val 2.18134
  Classification -> best τ=0.445 (val F1=0.2714)
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.38309 | val 2.47782
  Epoch 020 - train 0.05302 | val 3.50191
  Epoch 021 - train 0.04085 | val 3.71046
  Classification -> best τ=0.410 (val F1=0.1787)
  Directional -> Accuracy: 0.4151, MCC: -0.2450, F1: 0.0606

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.42641 | val 0.86645
  Epoch 020 - train 0.14025 | val 1.46681

[I 2026-02-19 00:13:14,040] Trial 10 finished with value: 0.2688998415931245 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.005685827118639983, 'weight_decay': 1.520041568754514e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.6522659844312346, 'early_stopping_min_delta': 0.00141636140815511}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 028 - train 0.01279 | val 1.63426
  Classification -> best τ=0.510 (val F1=0.2969)
  Directional -> Accuracy: 0.5000, MCC: -0.0072, F1: 0.4528

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2688998415931245
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63287 | val 1.16215
  Epoch 020 - train 0.33729 | val 3.42467
  Epoch 021 - train 0.33816 | val 2.83254
  Classification -> best τ=0.295 (val F1=0.1974)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.6168

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42069 | val 0.99263
  Epoch 020 - train 0.13096 | val 1.47964
  Epoch 022 - train 0.11258 | val 1.67242
  Classification -> best τ=0.490 (val F1=0.0464)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.41173 | val 1.15912
  Epoch 020 - train 0.11117 | val 1.60389
  Epoch 024 - train 0.04125 | val 2.17273
  Classification -> best τ=0.350 (val F1=0.1744)
  Directional -> Accuracy: 0.5682, MCC: 0.1727, F1: 0.6984

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58957 | val 1.48655
  Epoch 020 - train 0.35210 | val 3.48700
  Epoch 021 - train 0.37972 | val 3.98701
  Classification -> best τ=0.480 (val F1=0.2383)
  Directional -> Accuracy: 0.4722, MCC: 0.1092, F1: 0.0500

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56565 | val 0.88639
  Epoch 020 - train 0.12977 | val 1.36406
  Epoch 024 - train 0.11785 | val 1.70747
  Classification -> best τ=0.485 (val F1=0.4398)
  Directional -> Accuracy: 0.6458, MCC: 0.3612, F1: 0.5405

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39000 | val 1.17943
  Epoch 020 - train 0.08436 | val 1.72054
  Epoch 023 - train 0.06413 | val 2.05737
  Classification -> best τ=0.460 (val F1=0.1694)
  Directional -> Accuracy: 0.5227, MCC: 0.1525, F1: 0.6769

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.54317 | val 1.04277
  Epoch 020 - train 0.12166 | val 2.21697
  Epoch 027 - train 0.01980 | val 2.92392
  Classification -> best τ=0.445 (val F1=0.3364)
  Directional -> Accuracy: 0.4848, MCC: 0.0526, F1: 0.5405

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48065 | val 1.78614
  Epoch 020 - train 0.15852 | val 2.56383
  Epoch 022 - train 0.12958 | val 2.81140
  Classification -> best τ=0.385 (val F1=0.1204)
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.33002 | val 3.16975
  Epoch 020 - train 0.05870 | val 5.63757
  Epoch 022 - train 0.03091 | val 5.72938
  Classification -> best τ=0.195 (val F1=0.2119)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52994 | val 0.98548
  Epoch 020 - train 0.19062 | val 1.17037
  Epoch 022 - train 0.15795 | val 1.59794
  Classification -> best τ=0.630 (val F1=0.3136)
  Directional -> Accuracy: 0.4030, MCC: -0.1063, F1: 0.5455

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51422 | val 1.11992
  Epoch 020 - train 0.17307 | val 2.25761
  Epoch 024 - train 0.06314 | val 3.17264
  Classification -> best τ=0.370 (val F1=0.1871)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.51486 | val 1.30370
  Epoch 020 - train 0.11399 | val 3.82322
  Epoch 021 - train 0.08906 | val 4.07109
  Classification -> best τ=0.435 (val F1=0.2545)
  Directional -> Accuracy: 0.6000, MCC: 0.2052, F1: 0.6944

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48574 | val 0.70608
  Epoch 020 - train 0.25205 | val 0.73744
  Epoch 025 - train 0.08893 | val 0.93635
  Classification -> best τ=0.525 (val F1=0.5420)
  Directional -> Accuracy: 0.4375, MCC: -0.1400, F1: 0.3415

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.49893 | val 1.13699
  Epoch 020 - train 0.17769 | val 1.88462
  Epoch 022 - train 0.13509 | val 2.13690
  Classification -> best τ=0.280 (val F1=0.2535)
  Directional -> Accuracy: 0.5690, MCC: 0.1487, F1: 0.6753

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52336 | val 1.19536
  Epoch 020 - train 0.27752 | val 2.94215
  Epoch 022 - train 0.23260 | val 2.49043
  Classification -> best τ=0.555 (val F1=0.2125)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60797 | val 1.56307
  Epoch 020 - train 0.27493 | val 2.08281
  Epoch 021 - train 0.27242 | val 2.27433
  Classification -> best τ=0.285 (val F1=0.3085)
  Directional -> Accuracy: 0.6269, MCC: 0.3045, F1: 0.7368

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62748 | val 1.64967
  Epoch 020 - train 0.20248 | val 2.19926
  Epoch 021 - train 0.18053 | val 2.03747
  Classification -> best τ=0.525 (val F1=0.1887)
  Directional -> Accuracy: 0.4107, MCC: -0.0624, F1: 0.2667

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58319 | val 0.70420
  Epoch 020 - train 0.28312 | val 1.22011
  Epoch 021 - train 0.24670 | val 1.28648
  Classification -> best τ=0.405 (val F1=0.2382)
  Directional -> Accuracy: 0.5890, MCC: 0.0000, F1: 0.7414

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55750 | val 0.69108
  Epoch 020 - train 0.23345 | val 1.23677
  Epoch 024 - train 0.19719 | val 1.75825
  Classification -> best τ=0.675 (val F1=0.2659)
  Directional -> Accuracy: 0.4839, MCC: 0.1321, F1: 0.2727

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58333 | val 0.80398
  Epoch 020 - train 0.25311 | val 1.22302
  Epoch 022 - train 0.16386 | val 1.34318
  Classification -> best τ=0.595 (val F1=0.1890)
  Directional -> Accuracy: 0.4444, MCC: -0.1936, F1: 0.5745

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.33298 | val 1.62894
  Epoch 020 - train 0.11429 | val 1.25845
  Epoch 024 - train 0.04105 | val 1.75003
  Classification -> best τ=0.620 (val F1=0.1348)
  Directional -> Accuracy: 0.4000, MCC: -0.0440, F1: 0.0690

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.52134 | val 1.54042
  Epoch 020 - train 0.19355 | val 2.61792
  Epoch 021 - train 0.16649 | val 2.76114
  Classification -> best τ=0.335 (val F1=0.1211)
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54124 | val 1.39384
  Epoch 020 - train 0.14573 | val 3.35077
  Epoch 023 - train 0.09104 | val 3.70266
  Classification -> best τ=0.590 (val F1=0.2895)
  Directional -> Accuracy: 0.6364, MCC: 0.2228, F1: 0.7436

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48266 | val 0.70648
  Epoch 020 - train 0.17186 | val 0.98671
  Epoch 021 - train 0.14044 | val 1.00496
  Classification -> best τ=0.500 (val F1=0.1690)
  Directional -> Accuracy: 0.5238, MCC: 0.0853, F1: 0.6154

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61920 | val 0.76208
  Epoch 020 - train 0.24249 | val 1.32482
  Epoch 026 - train 0.04124 | val 1.63131
  Classification -> best τ=0.350 (val F1=0.3323)
  Directional -> Accuracy: 0.4906, MCC: 0.0044, F1: 0.4490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37138 | val 0.80984
  Epoch 020 - train 0.03178 | val 2.29443
  Epoch 026 - train 0.00345 | val 2.61977
  Classification -> best τ=0.540 (val F1=0.2987)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.36561 | val 0.67343
  Epoch 020 - train 0.08568 | val 0.93335
  Epoch 029 - train 0.00962 | val 1.25395
  Classification -> best τ=0.465 (val F1=0.3433)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47896 | val 1.32806
  Epoch 020 - train 0.09486 | val 3.01900
  Epoch 021 - train 0.08432 | val 3.08021
  Classification -> best τ=0.605 (val F1=0.1657)
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55581 | val 4.24429
  Epoch 020 - train 0.13227 | val 5.74653
  Epoch 022 - train 0.07976 | val 5.29137
  Classification -> best τ=0.435 (val F1=0.2000)
  Directional -> Accuracy: 0.5250, MCC: 0.0501, F1: 0.5366

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47588 | val 1.58405
  Epoch 020 - train 0.23256 | val 1.50023
  Epoch 030 - train 0.11424 | val 1.46448
  Epoch 032 - train 0.14839 | val 1.37871
  Classification -> best τ=0.675 (val F1=0.2328)
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48296 | val 0.83800
  Epoch 020 - train 0.12635 | val 1.96438
  Epoch 028 - train 0.00821 | val 1.92120
  Classification -> best τ=0.855 (val F1=0.4286)
  Directional -> Accuracy: 0.6170, MCC: 0.2631, F1: 0.7000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53884 | val 0.96482
  Epoch 020 - train 0.17324 | val 1.68674
  Epoch 022 - train 0.15157 | val 1.79691
  Classification -> best τ=0.355 (val F1=0.2593)
  Directional -> Accuracy: 0.5286, MCC: 0.0091, F1: 0.6292

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.44331 | val 1.45774
  Epoch 020 - train 0.11300 | val 2.74850
  Epoch 022 - train 0.06246 | val 3.00526
  Classification -> best τ=0.400 (val F1=0.1919)
  Directional -> Accuracy: 0.5102, MCC: 0.0835, F1: 0.6250

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52126 | val 1.01942
  Epoch 020 - train 0.20757 | val 2.04058
  Epoch 021 - train 0.22403 | val 2.70418
  Classification -> best τ=0.760 (val F1=0.2288)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.41492 | val 0.81183
  Epoch 020 - train 0.11642 | val 1.45921
  Epoch 022 - train 0.08642 | val 1.64993
  Classification -> best τ=0.550 (val F1=0.3516)
  Directional -> Accuracy: 0.5102, MCC: 0.0061, F1: 0.1429

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53902 | val 1.08067
  Epoch 020 - train 0.10553 | val 5.30714
  Epoch 022 - train 0.07760 | val 4.61054
  Classification -> best τ=0.530 (val F1=0.1223)
  Directional -> Accuracy: 0.5926, MCC: 0.1759, F1: 0.3889

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43385 | val 1.08447
  Epoch 020 - train 0.09822 | val 2.62307
  Epoch 021 - train 0.07898 | val 2.86746
  Classification -> best τ=0.570 (val F1=0.1922)
  Directional -> Accuracy: 0.3864, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43154 | val 0.72515
  Epoch 020 - train 0.05721 | val 1.38639
  Epoch 024 - train 0.01798 | val 1.59335
  Classification -> best τ=0.445 (val F1=0.4973)
  Directional -> Accuracy: 0.3111, MCC: -0.2132, F1: 0.4746

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63230 | val 0.74407
  Epoch 020 - train 0.23276 | val 1.69193
  Epoch 024 - train 0.14291 | val 2.30647
  Classification -> best τ=0.455 (val F1=0.2229)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6604

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48252 | val 0.87203
  Epoch 020 - train 0.21312 | val 1.35891
  Epoch 022 - train 0.14848 | val 1.57463
  Classification -> best τ=0.435 (val F1=0.2762)
  Directional -> Accuracy: 0.5116, MCC: 0.0641, F1: 0.2222

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.39011 | val 0.86798
  Epoch 020 - train 0.02343 | val 2.52065
  Epoch 024 - train 0.00711 | val 2.97311
  Classification -> best τ=0.350 (val F1=0.1918)
  Directional -> Accuracy: 0.5897, MCC: 0.0000, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.34135 | val 0.87098
  Epoch 020 - train 0.02314 | val 1.88170
  Epoch 021 - train 0.01896 | val 1.96622
  Classification -> best τ=0.500 (val F1=0.4743)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.50065 | val 0.67580
  Epoch 020 - train 0.16908 | val 0.72073
  Epoch 026 - train 0.05586 | val 1.18186
  Classification -> best τ=0.440 (val F1=0.1712)
  Directional -> Accuracy: 0.5472, MCC: 0.0000, F1: 0.7073

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58698 | val 2.05757
  Epoch 020 - train 0.15847 | val 2.87281
  Epoch 023 - train 0.08907 | val 3.67128
  Classification -> best τ=0.505 (val F1=0.2169)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48193 | val 0.98449
  Epoch 020 - train 0.05879 | val 3.02607
  Epoch 021 - train 0.04194 | val 3.13369
  Classification -> best τ=0.560 (val F1=0.2828)
  Directional -> Accuracy: 0.6078, MCC: 0.2148, F1: 0.5833

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48809 | val 1.24715
  Epoch 020 - train 0.17421 | val 1.96886
  Epoch 022 - train 0.18678 | val 2.53757
  Classification -> best τ=0.545 (val F1=0.2203)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62474 | val 0.89306
  Epoch 020 - train 0.33903 | val 1.43307

[I 2026-02-19 00:19:16,736] Trial 11 finished with value: 0.2510766537752793 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.009775514233359196, 'weight_decay': 1.3641353339008515e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.6704254946341927, 'early_stopping_min_delta': 0.0008637551781329448}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 023 - train 0.25567 | val 2.28105
  Classification -> best τ=0.485 (val F1=0.2969)
  Directional -> Accuracy: 0.4138, MCC: -0.1600, F1: 0.4688

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2510766537752793
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.51568 | val 0.69402
  Epoch 020 - train 0.21565 | val 3.74517
  Epoch 024 - train 0.13620 | val 3.07252
  Classification -> best τ=0.345 (val F1=0.1376)
  Directional -> Accuracy: 0.4324, MCC: -0.1305, F1: 0.6038

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47188 | val 0.93076
  Epoch 020 - train 0.21118 | val 1.92363
  Epoch 024 - train 0.08892 | val 2.64072
  Classification -> best τ=0.440 (val F1=0.0471)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52468 | val 1.04271
  Epoch 020 - train 0.11421 | val 3.58625
  Epoch 022 - train 0.06318 | val 3.57723
  Classification -> best τ=0.595 (val F1=0.3327)
  Directional -> Accuracy: 0.5909, MCC: 0.2364, F1: 0.4706

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70159 | val 0.71648
  Epoch 020 - train 0.31497 | val 4.06966
  Epoch 023 - train 0.20090 | val 3.81872
  Classification -> best τ=0.575 (val F1=0.1270)
  Directional -> Accuracy: 0.5278, MCC: 0.1080, F1: 0.4138

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42981 | val 0.86308
  Epoch 020 - train 0.06945 | val 1.60536
  Epoch 024 - train 0.09331 | val 1.77013
  Classification -> best τ=0.585 (val F1=0.4398)
  Directional -> Accuracy: 0.6875, MCC: 0.4128, F1: 0.6341

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36770 | val 1.18068
  Epoch 020 - train 0.10285 | val 1.69840
  Epoch 024 - train 0.04720 | val 1.72300
  Classification -> best τ=0.420 (val F1=0.3929)
  Directional -> Accuracy: 0.4773, MCC: -0.1525, F1: 0.6462

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63420 | val 0.84817
  Epoch 020 - train 0.29222 | val 1.29935
  Epoch 024 - train 0.17796 | val 1.82360
  Classification -> best τ=0.525 (val F1=0.2322)
  Directional -> Accuracy: 0.4242, MCC: -0.0286, F1: 0.5476

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42338 | val 1.11785
  Epoch 020 - train 0.14012 | val 2.64122
  Epoch 023 - train 0.09871 | val 2.76296
  Classification -> best τ=0.500 (val F1=0.2414)
  Directional -> Accuracy: 0.4872, MCC: 0.0259, F1: 0.5455

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.32097 | val 1.29542
  Epoch 020 - train 0.08700 | val 1.25959
  Epoch 023 - train 0.04349 | val 1.48117
  Classification -> best τ=0.310 (val F1=0.3292)
  Directional -> Accuracy: 0.4130, MCC: -0.1700, F1: 0.5846

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.54311 | val 1.24439
  Epoch 020 - train 0.12659 | val 1.84958
  Epoch 023 - train 0.06132 | val 2.21967
  Classification -> best τ=0.480 (val F1=0.3084)
  Directional -> Accuracy: 0.3731, MCC: -0.2200, F1: 0.5333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45978 | val 0.81711
  Epoch 020 - train 0.05595 | val 1.09193
  Epoch 021 - train 0.03819 | val 1.21999
  Classification -> best τ=0.500 (val F1=0.1524)
  Directional -> Accuracy: 0.5532, MCC: 0.1093, F1: 0.5333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66843 | val 1.17733
  Epoch 020 - train 0.11001 | val 3.97143
  Epoch 024 - train 0.03423 | val 5.03055
  Classification -> best τ=0.460 (val F1=0.1978)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54553 | val 0.88075
  Epoch 020 - train 0.13811 | val 1.75358
  Epoch 026 - train 0.02017 | val 1.91099
  Classification -> best τ=0.635 (val F1=0.2935)
  Directional -> Accuracy: 0.4583, MCC: -0.0893, F1: 0.4091

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.45637 | val 1.28232
  Epoch 020 - train 0.13325 | val 1.90056
  Epoch 023 - train 0.08168 | val 2.09514
  Classification -> best τ=0.270 (val F1=0.2716)
  Directional -> Accuracy: 0.5862, MCC: 0.1984, F1: 0.6923

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51085 | val 1.37786
  Epoch 020 - train 0.16131 | val 2.90903
  Epoch 022 - train 0.12803 | val 3.78124
  Classification -> best τ=0.490 (val F1=0.1487)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49820 | val 1.52889
  Epoch 020 - train 0.31695 | val 1.70973
  Epoch 021 - train 0.30940 | val 1.93660
  Classification -> best τ=0.470 (val F1=0.3541)
  Directional -> Accuracy: 0.6269, MCC: 0.3045, F1: 0.7368

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.53977 | val 0.75964
  Epoch 020 - train 0.22477 | val 1.32457
  Epoch 022 - train 0.13638 | val 1.47215
  Classification -> best τ=0.615 (val F1=0.1887)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63377 | val 0.81035
  Epoch 020 - train 0.17470 | val 1.60131
  Epoch 023 - train 0.13154 | val 1.86373
  Classification -> best τ=0.590 (val F1=0.1829)
  Directional -> Accuracy: 0.4247, MCC: 0.0984, F1: 0.0455

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.49330 | val 0.87740
  Epoch 020 - train 0.14817 | val 1.15020
  Epoch 026 - train 0.03750 | val 1.61592
  Classification -> best τ=0.655 (val F1=0.2816)
  Directional -> Accuracy: 0.4516, MCC: 0.0571, F1: 0.1905

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59512 | val 0.76673
  Epoch 020 - train 0.24774 | val 0.97124
  Epoch 026 - train 0.18502 | val 1.51284
  Classification -> best τ=0.695 (val F1=0.3054)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.37438 | val 1.32500
  Epoch 020 - train 0.03726 | val 2.25073
  Epoch 021 - train 0.03455 | val 2.39801
  Classification -> best τ=0.615 (val F1=0.3177)
  Directional -> Accuracy: 0.4667, MCC: -0.1327, F1: 0.5714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.49526 | val 1.32852
  Epoch 020 - train 0.11227 | val 2.33003
  Epoch 021 - train 0.08604 | val 2.34921
  Classification -> best τ=0.325 (val F1=0.1726)
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.49535 | val 1.35806
  Epoch 020 - train 0.18126 | val 2.28751
  Epoch 024 - train 0.06708 | val 3.25548
  Classification -> best τ=0.505 (val F1=0.2452)
  Directional -> Accuracy: 0.5818, MCC: 0.0000, F1: 0.7356

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56271 | val 0.70105
  Epoch 020 - train 0.17208 | val 1.97492
  Epoch 022 - train 0.10441 | val 0.96768
  Classification -> best τ=0.515 (val F1=0.1375)
  Directional -> Accuracy: 0.5079, MCC: 0.0151, F1: 0.4918

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50119 | val 0.97434
  Epoch 020 - train 0.15286 | val 1.48313
  Epoch 027 - train 0.02206 | val 2.16331
  Classification -> best τ=0.635 (val F1=0.3652)
  Directional -> Accuracy: 0.4528, MCC: -0.0188, F1: 0.0645

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.32894 | val 0.81762
  Epoch 020 - train 0.02596 | val 1.41795
  Epoch 023 - train 0.01065 | val 1.94009
  Classification -> best τ=0.520 (val F1=0.2557)
  Directional -> Accuracy: 0.4762, MCC: 0.1171, F1: 0.6071

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.41874 | val 0.66611
  Epoch 020 - train 0.15810 | val 0.84343
  Epoch 030 - train 0.01460 | val 1.24166
  Epoch 032 - train 0.00812 | val 1.32394
  Classification -> best τ=0.495 (val F1=0.5191)
  Directional -> Accuracy: 0.4375, MCC: -0.1198, F1: 0.4706

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59770 | val 1.09364
  Epoch 020 - train 0.24898 | val 2.48318
  Epoch 023 - train 0.14636 | val 3.20422
  Classification -> best τ=0.405 (val F1=0.3200)
  Directional -> Accuracy: 0.5185, MCC: 0.1685, F1: 0.2353

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.40444 | val 1.66584
  Epoch 020 - train 0.09524 | val 3.24268
  Epoch 022 - train 0.05782 | val 3.65050
  Classification -> best τ=0.515 (val F1=0.1391)
  Directional -> Accuracy: 0.4750, MCC: -0.0756, F1: 0.6182

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.40277 | val 0.82271
  Epoch 020 - train 0.06367 | val 1.23002
  Epoch 022 - train 0.06190 | val 1.31695
  Classification -> best τ=0.610 (val F1=0.3233)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58834 | val 0.75617
  Epoch 020 - train 0.18090 | val 1.47962
  Epoch 027 - train 0.04571 | val 2.02123
  Classification -> best τ=0.495 (val F1=0.2308)
  Directional -> Accuracy: 0.6170, MCC: 0.2808, F1: 0.7097

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.46657 | val 0.93949
  Epoch 020 - train 0.11402 | val 2.25714
  Epoch 022 - train 0.06781 | val 2.64685
  Classification -> best τ=0.295 (val F1=0.3239)
  Directional -> Accuracy: 0.5571, MCC: 0.0000, F1: 0.7156

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.46410 | val 1.19407
  Epoch 020 - train 0.03801 | val 2.49353
  Epoch 022 - train 0.02304 | val 2.72208
  Classification -> best τ=0.445 (val F1=0.1899)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.50151 | val 0.93462
  Epoch 020 - train 0.10682 | val 1.81748
  Epoch 022 - train 0.06233 | val 2.27103
  Classification -> best τ=0.390 (val F1=0.3886)
  Directional -> Accuracy: 0.5781, MCC: 0.0954, F1: 0.7158

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.36830 | val 1.01922
  Epoch 020 - train 0.03444 | val 2.73331
  Epoch 024 - train 0.00788 | val 3.05596
  Classification -> best τ=0.440 (val F1=0.3092)
  Directional -> Accuracy: 0.6122, MCC: 0.2434, F1: 0.4865

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44245 | val 1.62075
  Epoch 020 - train 0.15188 | val 3.79521
  Epoch 022 - train 0.12764 | val 3.08831
  Classification -> best τ=0.435 (val F1=0.1238)
  Directional -> Accuracy: 0.4444, MCC: -0.1062, F1: 0.4444

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42320 | val 1.24823
  Epoch 020 - train 0.01564 | val 4.68860
  Epoch 023 - train 0.00582 | val 5.17943
  Classification -> best τ=0.520 (val F1=0.3409)
  Directional -> Accuracy: 0.3864, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48439 | val 0.68101
  Epoch 020 - train 0.21435 | val 0.82490
  Epoch 026 - train 0.05011 | val 1.22338
  Classification -> best τ=0.565 (val F1=0.4264)
  Directional -> Accuracy: 0.3778, MCC: -0.0756, F1: 0.4400

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51005 | val 1.57249
  Epoch 020 - train 0.23650 | val 2.17853
  Epoch 021 - train 0.21051 | val 2.23450
  Classification -> best τ=0.500 (val F1=0.1188)
  Directional -> Accuracy: 0.5278, MCC: 0.1213, F1: 0.1500

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52034 | val 0.97287
  Epoch 020 - train 0.27786 | val 1.48081
  Epoch 022 - train 0.21007 | val 1.63808
  Classification -> best τ=0.475 (val F1=0.2708)
  Directional -> Accuracy: 0.5349, MCC: 0.0660, F1: 0.6154

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.25532 | val 1.47561
  Epoch 020 - train 0.01021 | val 2.19017
  Epoch 023 - train 0.00371 | val 2.38945
  Classification -> best τ=0.520 (val F1=0.2267)
  Directional -> Accuracy: 0.4103, MCC: -0.0617, F1: 0.1481

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.34624 | val 0.98829
  Epoch 020 - train 0.04121 | val 1.66769
  Epoch 021 - train 0.02745 | val 1.79439
  Classification -> best τ=0.565 (val F1=0.4743)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.49891 | val 0.68787
  Epoch 020 - train 0.17443 | val 1.24170
  Epoch 027 - train 0.05087 | val 1.54689
  Classification -> best τ=0.690 (val F1=0.3160)
  Directional -> Accuracy: 0.4528, MCC: -0.0271, F1: 0.1212

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51679 | val 1.82580
  Epoch 020 - train 0.12961 | val 3.77756
  Epoch 021 - train 0.09379 | val 4.46533
  Classification -> best τ=0.395 (val F1=0.2286)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.1290

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44615 | val 0.87422
  Epoch 020 - train 0.12491 | val 1.30323
  Epoch 026 - train 0.02100 | val 1.50437
  Classification -> best τ=0.870 (val F1=0.2758)
  Directional -> Accuracy: 0.5882, MCC: 0.2025, F1: 0.6557

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.49912 | val 1.28819
  Epoch 020 - train 0.21516 | val 2.07603
  Epoch 024 - train 0.11917 | val 2.85914
  Classification -> best τ=0.485 (val F1=0.0381)
  Directional -> Accuracy: 0.5094, MCC: 0.0037, F1: 0.6667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.50796 | val 0.74972
  Epoch 020 - train 0.18982 | val 0.98538

[I 2026-02-19 00:25:29,172] Trial 12 finished with value: 0.2632848839256846 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.009646944334427048, 'weight_decay': 1.484719079635305e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.7541848903577626, 'early_stopping_min_delta': 0.000398496523109868}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 022 - train 0.10298 | val 1.01586
  Classification -> best τ=0.500 (val F1=0.3311)
  Directional -> Accuracy: 0.5517, MCC: 0.0828, F1: 0.1875

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2632848839256846
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62376 | val 1.11449
  Epoch 020 - train 0.59763 | val 1.93112
  Epoch 021 - train 0.59533 | val 1.97828
  Classification -> best τ=0.550 (val F1=0.1594)
  Directional -> Accuracy: 0.6081, MCC: 0.2665, F1: 0.2162

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60495 | val 0.75514
  Epoch 020 - train 0.56290 | val 1.13566
  Epoch 021 - train 0.55995 | val 1.17625
  Classification -> best τ=0.435 (val F1=0.0316)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.60474 | val 0.73609
  Epoch 020 - train 0.56898 | val 0.99053
  Epoch 021 - train 0.57341 | val 1.01273
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62090 | val 1.00445
  Epoch 020 - train 0.60145 | val 1.06566
  Epoch 021 - train 0.59130 | val 1.12087
  Classification -> best τ=0.405 (val F1=0.0845)
  Directional -> Accuracy: 0.5139, MCC: -0.1555, F1: 0.6789

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59443 | val 0.62252
  Epoch 020 - train 0.53184 | val 0.67338
  Epoch 030 - train 0.49593 | val 0.68969
  Classification -> best τ=0.465 (val F1=0.4126)
  Directional -> Accuracy: 0.7708, MCC: 0.5405, F1: 0.7843

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57937 | val 0.75479
  Epoch 020 - train 0.54493 | val 0.93514
  Epoch 021 - train 0.54118 | val 0.95413
  Classification -> best τ=0.565 (val F1=0.2287)
  Directional -> Accuracy: 0.5682, MCC: 0.2148, F1: 0.2963

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65400 | val 0.69621
  Epoch 020 - train 0.63088 | val 0.71597
  Epoch 021 - train 0.63214 | val 0.71934
  Classification -> best τ=0.510 (val F1=0.0209)
  Directional -> Accuracy: 0.5152, MCC: 0.0536, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57401 | val 0.87009
  Epoch 020 - train 0.53922 | val 1.29878
  Epoch 021 - train 0.53933 | val 1.36729
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59118 | val 0.78636
  Epoch 020 - train 0.57108 | val 1.28957
  Epoch 021 - train 0.56262 | val 1.33752
  Classification -> best τ=0.495 (val F1=0.2817)
  Directional -> Accuracy: 0.5652, MCC: 0.1260, F1: 0.5238

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60196 | val 0.72133
  Epoch 020 - train 0.55093 | val 0.70782
  Epoch 026 - train 0.53202 | val 0.71694
  Classification -> best τ=0.600 (val F1=0.1675)
  Directional -> Accuracy: 0.5821, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61748 | val 0.74826
  Epoch 020 - train 0.56343 | val 1.21690
  Epoch 024 - train 0.56101 | val 1.47657
  Classification -> best τ=0.510 (val F1=0.1871)
  Directional -> Accuracy: 0.5957, MCC: 0.2346, F1: 0.1739

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61080 | val 0.75007
  Epoch 020 - train 0.56759 | val 0.91615
  Epoch 021 - train 0.56848 | val 0.93243
  Classification -> best τ=0.535 (val F1=0.2359)
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55235 | val 0.80949
  Epoch 020 - train 0.52075 | val 1.37479
  Epoch 021 - train 0.52003 | val 1.37458
  Classification -> best τ=0.495 (val F1=0.2409)
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.6479

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62001 | val 0.66296
  Epoch 020 - train 0.56876 | val 0.73011
  Epoch 027 - train 0.55028 | val 0.76048
  Classification -> best τ=0.415 (val F1=0.2411)
  Directional -> Accuracy: 0.5517, MCC: 0.1456, F1: 0.6905

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59903 | val 0.79808
  Epoch 020 - train 0.57352 | val 1.06539
  Epoch 021 - train 0.57460 | val 1.09100
  Classification -> best τ=0.530 (val F1=0.2125)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58273 | val 0.82080
  Epoch 020 - train 0.55215 | val 1.08780
  Epoch 022 - train 0.54626 | val 1.06437
  Classification -> best τ=0.430 (val F1=0.2866)
  Directional -> Accuracy: 0.5970, MCC: 0.2715, F1: 0.7273

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60519 | val 1.05638
  Epoch 020 - train 0.58165 | val 1.50414
  Epoch 021 - train 0.57311 | val 1.51579
  Classification -> best τ=0.590 (val F1=0.1538)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63610 | val 0.71728
  Epoch 020 - train 0.60291 | val 0.76739
  Epoch 021 - train 0.60261 | val 0.76217
  Classification -> best τ=0.520 (val F1=0.1664)
  Directional -> Accuracy: 0.5616, MCC: 0.2233, F1: 0.5000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61113 | val 0.69144
  Epoch 020 - train 0.56523 | val 1.11484
  Epoch 027 - train 0.55586 | val 1.37305
  Classification -> best τ=0.320 (val F1=0.2799)
  Directional -> Accuracy: 0.5000, MCC: 0.1646, F1: 0.3111

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59789 | val 0.64892
  Epoch 020 - train 0.53936 | val 0.73054
  Epoch 029 - train 0.50320 | val 0.73701
  Classification -> best τ=0.485 (val F1=0.3750)
  Directional -> Accuracy: 0.4722, MCC: 0.1512, F1: 0.0952

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.59941 | val 0.68555
  Epoch 020 - train 0.53708 | val 0.95942
  Epoch 028 - train 0.49933 | val 1.19291
  Classification -> best τ=0.460 (val F1=0.3492)
  Directional -> Accuracy: 0.5111, MCC: 0.0551, F1: 0.5217

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62323 | val 0.75134
  Epoch 020 - train 0.59394 | val 0.87185
  Epoch 021 - train 0.59436 | val 0.87248
  Classification -> best τ=0.560 (val F1=0.0124)
  Directional -> Accuracy: 0.5079, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59900 | val 0.78139
  Epoch 020 - train 0.56666 | val 1.12742
  Epoch 021 - train 0.55702 | val 1.14417
  Classification -> best τ=0.535 (val F1=0.2182)
  Directional -> Accuracy: 0.5636, MCC: 0.1260, F1: 0.6000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61863 | val 0.71373
  Epoch 020 - train 0.58957 | val 0.76899
  Epoch 021 - train 0.58213 | val 0.76262
  Classification -> best τ=0.480 (val F1=0.1343)
  Directional -> Accuracy: 0.5397, MCC: 0.0818, F1: 0.5397

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61683 | val 0.63438
  Epoch 020 - train 0.56110 | val 0.63429
  Epoch 030 - train 0.51613 | val 0.64579
  Epoch 035 - train 0.49773 | val 0.66650
  Classification -> best τ=0.445 (val F1=0.4235)
  Directional -> Accuracy: 0.5283, MCC: 0.1152, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59386 | val 0.71148
  Epoch 020 - train 0.57165 | val 0.75389
  Epoch 021 - train 0.57123 | val 0.76242
  Classification -> best τ=0.550 (val F1=0.0452)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60264 | val 0.72737
  Epoch 020 - train 0.57802 | val 0.75741
  Epoch 021 - train 0.57041 | val 0.76751
  Classification -> best τ=0.530 (val F1=0.1928)
  Directional -> Accuracy: 0.5625, MCC: -0.1233, F1: 0.7200

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61880 | val 0.68721
  Epoch 020 - train 0.56366 | val 0.71738
  Epoch 026 - train 0.55506 | val 0.73985
  Classification -> best τ=0.430 (val F1=0.2932)
  Directional -> Accuracy: 0.5185, MCC: 0.1163, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61646 | val 0.74955
  Epoch 020 - train 0.58474 | val 0.88294
  Epoch 021 - train 0.58942 | val 0.88634
  Classification -> best τ=0.510 (val F1=0.1391)
  Directional -> Accuracy: 0.4750, MCC: -0.0599, F1: 0.2759

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61015 | val 0.71907
  Epoch 020 - train 0.56817 | val 0.84511
  Epoch 024 - train 0.56986 | val 0.86681
  Classification -> best τ=0.530 (val F1=0.0071)
  Directional -> Accuracy: 0.4000, MCC: -0.1755, F1: 0.2941

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.61244 | val 0.66787
  Epoch 020 - train 0.55969 | val 0.63662
  Epoch 030 - train 0.51184 | val 0.63932
  Epoch 040 - train 0.45786 | val 0.64538
  Epoch 043 - train 0.44629 | val 0.64210
  Classification -> best τ=0.585 (val F1=0.4783)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59226 | val 0.67501
  Epoch 020 - train 0.53935 | val 0.74418
  Epoch 026 - train 0.53409 | val 0.74570
  Classification -> best τ=0.390 (val F1=0.2593)
  Directional -> Accuracy: 0.5714, MCC: 0.1747, F1: 0.5455

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59937 | val 0.71332
  Epoch 020 - train 0.58199 | val 0.84742
  Epoch 021 - train 0.58118 | val 0.85843
  Classification -> best τ=0.495 (val F1=0.3015)
  Directional -> Accuracy: 0.5306, MCC: 0.1503, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.58321 | val 0.73688
  Epoch 020 - train 0.54096 | val 0.87847
  Epoch 021 - train 0.54706 | val 0.87959
  Classification -> best τ=0.465 (val F1=0.3310)
  Directional -> Accuracy: 0.5781, MCC: 0.2887, F1: 0.4490

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56236 | val 0.68266
  Epoch 020 - train 0.50131 | val 0.69845
  Epoch 030 - train 0.47050 | val 0.76949
  Classification -> best τ=0.560 (val F1=0.3516)
  Directional -> Accuracy: 0.5918, MCC: 0.2299, F1: 0.3750

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59362 | val 0.88735
  Epoch 020 - train 0.57521 | val 1.40409
  Epoch 021 - train 0.56878 | val 1.42217
  Classification -> best τ=0.480 (val F1=0.0714)
  Directional -> Accuracy: 0.5185, MCC: 0.0158, F1: 0.4091

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.55676 | val 0.88023
  Epoch 020 - train 0.49296 | val 1.99982
  Epoch 021 - train 0.50179 | val 2.13406
  Classification -> best τ=0.510 (val F1=0.2509)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61240 | val 0.67960
  Epoch 020 - train 0.57289 | val 0.66727
  Epoch 030 - train 0.52066 | val 0.68705
  Epoch 037 - train 0.51277 | val 0.70089
  Classification -> best τ=0.485 (val F1=0.4079)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57906 | val 0.95127
  Epoch 020 - train 0.53461 | val 1.28351
  Epoch 023 - train 0.52460 | val 1.30312
  Classification -> best τ=0.465 (val F1=0.1945)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59602 | val 0.70931
  Epoch 020 - train 0.54104 | val 0.72049
  Epoch 030 - train 0.53313 | val 0.72187
  Classification -> best τ=0.525 (val F1=0.1788)
  Directional -> Accuracy: 0.4419, MCC: -0.1294, F1: 0.5200

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.58971 | val 0.70138
  Epoch 020 - train 0.55568 | val 0.72224
  Epoch 021 - train 0.56153 | val 0.72524
  Classification -> best τ=0.515 (val F1=0.2660)
  Directional -> Accuracy: 0.5385, MCC: 0.0643, F1: 0.5909

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56594 | val 0.70561
  Epoch 020 - train 0.53720 | val 0.69540
  Epoch 021 - train 0.53337 | val 0.69513
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63321 | val 0.76327
  Epoch 020 - train 0.60590 | val 0.97139
  Epoch 021 - train 0.60173 | val 0.96835
  Classification -> best τ=0.505 (val F1=0.0854)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58896 | val 1.31874
  Epoch 020 - train 0.55276 | val 2.32258
  Epoch 021 - train 0.56070 | val 2.37846
  Classification -> best τ=0.500 (val F1=0.1412)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60091 | val 0.69396
  Epoch 020 - train 0.55772 | val 0.76373
  Epoch 026 - train 0.55274 | val 0.76435
  Classification -> best τ=0.580 (val F1=0.2092)
  Directional -> Accuracy: 0.5882, MCC: 0.1877, F1: 0.6316

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59675 | val 1.18131
  Epoch 020 - train 0.55856 | val 2.15201
  Epoch 021 - train 0.55627 | val 2.12709
  Classification -> best τ=0.540 (val F1=0.1687)
  Directional -> Accuracy: 0.5283, MCC: 0.0863, F1: 0.6753

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60971 | val 0.67632
  Epoch 020 - train 0.56674 | val 0.69278
  Epoch 030 - train 0.53466 | val 0.80633

[I 2026-02-19 00:31:53,252] Trial 13 finished with value: 0.20385580577040063 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.00037555730011104495, 'weight_decay': 1.607275928329127e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.6921395932212369, 'early_stopping_min_delta': 0.0019954283496867843}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 032 - train 0.53377 | val 0.79618
  Classification -> best τ=0.650 (val F1=0.3046)
  Directional -> Accuracy: 0.5000, MCC: 0.0418, F1: 0.5915

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.20385580577040063
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'stance_label', 'stance_score']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.53402 | val 1.10971
  Epoch 020 - train 0.36739 | val 2.21191
  Epoch 023 - train 0.33991 | val 2.39360
  Classification -> best τ=0.580 (val F1=0.2489)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51275 | val 1.25352
  Epoch 020 - train 0.38482 | val 1.77924
  Epoch 021 - train 0.38507 | val 1.43125
  Classification -> best τ=0.415 (val F1=0.0813)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52014 | val 0.88322
  Epoch 020 - train 0.33195 | val 1.27775
  Epoch 023 - train 0.31247 | val 1.31310
  Classification -> best τ=0.490 (val F1=0.3327)
  Directional -> Accuracy: 0.5227, MCC: 0.2085, F1: 0.1600

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.59060 | val 1.13856
  Epoch 020 - train 0.41881 | val 1.75032
  Epoch 021 - train 0.40512 | val 2.53294
  Classification -> best τ=0.455 (val F1=0.0691)
  Directional -> Accuracy: 0.5000, MCC: 0.1918, F1: 0.1429

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.47169 | val 0.72033
  Epoch 020 - train 0.28706 | val 0.90169
  Epoch 025 - train 0.25019 | val 0.96917
  Classification -> best τ=0.540 (val F1=0.4638)
  Directional -> Accuracy: 0.6042, MCC: 0.2867, F1: 0.4571

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45223 | val 1.67004
  Epoch 020 - train 0.30015 | val 2.72776
  Epoch 021 - train 0.28904 | val 2.73798
  Classification -> best τ=0.565 (val F1=0.0934)
  Directional -> Accuracy: 0.5682, MCC: 0.1494, F1: 0.4571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.61404 | val 0.75471
  Epoch 020 - train 0.45204 | val 0.95733
  Epoch 028 - train 0.28537 | val 1.50191
  Classification -> best τ=0.535 (val F1=0.4396)
  Directional -> Accuracy: 0.4545, MCC: -0.0925, F1: 0.4000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.44794 | val 1.63693
  Epoch 020 - train 0.32079 | val 2.39569
  Epoch 021 - train 0.31314 | val 2.04943
  Classification -> best τ=0.595 (val F1=0.1491)
  Directional -> Accuracy: 0.5128, MCC: 0.0292, F1: 0.4865

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.52500 | val 1.39714
  Epoch 020 - train 0.37619 | val 1.93369
  Epoch 021 - train 0.36216 | val 1.78502
  Classification -> best τ=0.565 (val F1=0.3030)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64388 | val 1.06845
  Epoch 020 - train 0.33401 | val 1.14246
  Epoch 025 - train 0.30148 | val 1.43619
  Classification -> best τ=0.680 (val F1=0.2557)
  Directional -> Accuracy: 0.4776, MCC: -0.1159, F1: 0.2857

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45443 | val 1.08425
  Epoch 020 - train 0.29155 | val 2.95253
  Epoch 022 - train 0.27827 | val 3.01525
  Classification -> best τ=0.525 (val F1=0.0734)
  Directional -> Accuracy: 0.5532, MCC: 0.0556, F1: 0.3226

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56670 | val 1.03418
  Epoch 020 - train 0.40196 | val 1.72498
  Epoch 021 - train 0.39768 | val 1.83831
  Classification -> best τ=0.430 (val F1=0.1451)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43788 | val 1.13548
  Epoch 020 - train 0.32167 | val 2.00457
  Epoch 021 - train 0.32436 | val 2.18901
  Classification -> best τ=0.395 (val F1=0.2919)
  Directional -> Accuracy: 0.4583, MCC: -0.1521, F1: 0.6286

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.53333 | val 0.78827
  Epoch 020 - train 0.41382 | val 1.14751
  Epoch 024 - train 0.38590 | val 1.22624
  Classification -> best τ=0.365 (val F1=0.2716)
  Directional -> Accuracy: 0.5172, MCC: 0.0065, F1: 0.6744

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.49822 | val 1.05404
  Epoch 020 - train 0.37516 | val 1.14472
  Epoch 021 - train 0.36556 | val 1.16944
  Classification -> best τ=0.490 (val F1=0.2125)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53134 | val 1.08578
  Epoch 020 - train 0.37427 | val 1.55942
  Epoch 023 - train 0.33951 | val 1.70271
  Classification -> best τ=0.550 (val F1=0.2709)
  Directional -> Accuracy: 0.5672, MCC: 0.1666, F1: 0.5085

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.52100 | val 1.61265
  Epoch 020 - train 0.39356 | val 2.78454
  Epoch 021 - train 0.38667 | val 2.76552
  Classification -> best τ=0.505 (val F1=0.0514)
  Directional -> Accuracy: 0.6071, MCC: 0.0896, F1: 0.7317

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55916 | val 0.71723
  Epoch 020 - train 0.43671 | val 1.37898
  Epoch 021 - train 0.40827 | val 1.28798
  Classification -> best τ=0.565 (val F1=0.2127)
  Directional -> Accuracy: 0.4247, MCC: 0.0984, F1: 0.0455

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54050 | val 0.77695
  Epoch 020 - train 0.36057 | val 1.33851
  Epoch 025 - train 0.27953 | val 1.74304
  Classification -> best τ=0.520 (val F1=0.2659)
  Directional -> Accuracy: 0.4839, MCC: 0.1676, F1: 0.2381

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52358 | val 0.84580
  Epoch 020 - train 0.35845 | val 0.99489
  Epoch 024 - train 0.27964 | val 1.15717
  Classification -> best τ=0.415 (val F1=0.2795)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48572 | val 0.72557
  Epoch 020 - train 0.30494 | val 0.92800
  Epoch 024 - train 0.26097 | val 1.33014
  Classification -> best τ=0.530 (val F1=0.2411)
  Directional -> Accuracy: 0.4222, MCC: -0.2037, F1: 0.5185

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.52232 | val 1.04528
  Epoch 020 - train 0.32822 | val 1.66035
  Epoch 021 - train 0.30296 | val 1.66666
  Classification -> best τ=0.510 (val F1=0.0151)
  Directional -> Accuracy: 0.5079, MCC: 0.0108, F1: 0.3922

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54981 | val 1.15249
  Epoch 020 - train 0.41843 | val 1.84843
  Epoch 021 - train 0.38704 | val 1.73675
  Classification -> best τ=0.570 (val F1=0.2182)
  Directional -> Accuracy: 0.5455, MCC: 0.1352, F1: 0.5283

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54944 | val 0.74260
  Epoch 020 - train 0.42196 | val 0.94981
  Epoch 023 - train 0.38463 | val 1.06106
  Classification -> best τ=0.465 (val F1=0.1196)
  Directional -> Accuracy: 0.5079, MCC: 0.0182, F1: 0.5079

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49502 | val 0.75292
  Epoch 020 - train 0.29130 | val 1.16144
  Epoch 025 - train 0.25573 | val 1.43617
  Classification -> best τ=0.540 (val F1=0.3746)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46485 | val 0.70721
  Epoch 020 - train 0.34327 | val 0.65477
  Epoch 030 - train 0.18411 | val 0.91508
  Epoch 040 - train 0.08998 | val 0.92106
  Epoch 044 - train 0.07891 | val 0.97658
  Classification -> best τ=0.595 (val F1=0.5130)
  Directional -> Accuracy: 0.5238, MCC: 0.2161, F1: 0.6296

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49990 | val 0.78856
  Epoch 020 - train 0.38630 | val 1.11665
  Epoch 021 - train 0.37132 | val 1.26251
  Classification -> best τ=0.535 (val F1=0.2010)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48206 | val 0.97670
  Epoch 020 - train 0.31835 | val 1.43011
  Epoch 021 - train 0.30228 | val 1.48230
  Classification -> best τ=0.490 (val F1=0.2457)
  Directional -> Accuracy: 0.5370, MCC: 0.2626, F1: 0.2424

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51439 | val 1.11531
  Epoch 020 - train 0.37772 | val 1.93829
  Epoch 021 - train 0.35407 | val 2.01529
  Classification -> best τ=0.535 (val F1=0.2000)
  Directional -> Accuracy: 0.4500, MCC: -0.1250, F1: 0.2143

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49484 | val 0.76987
  Epoch 020 - train 0.38874 | val 0.91733
  Epoch 021 - train 0.36601 | val 1.03836
  Classification -> best τ=0.545 (val F1=0.1791)
  Directional -> Accuracy: 0.4000, MCC: -0.1759, F1: 0.2000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51974 | val 0.70301
  Epoch 020 - train 0.32881 | val 0.88689
  Epoch 026 - train 0.26375 | val 0.94410
  Classification -> best τ=0.480 (val F1=0.2667)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.48004 | val 0.91687
  Epoch 020 - train 0.31396 | val 1.29570
  Epoch 024 - train 0.24915 | val 1.40855
  Classification -> best τ=0.235 (val F1=0.2695)
  Directional -> Accuracy: 0.5429, MCC: 0.0439, F1: 0.6364

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51027 | val 0.76125
  Epoch 020 - train 0.38365 | val 0.96596
  Epoch 021 - train 0.35558 | val 1.02559
  Classification -> best τ=0.505 (val F1=0.3800)
  Directional -> Accuracy: 0.5102, MCC: 0.1018, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46574 | val 0.90502
  Epoch 020 - train 0.32047 | val 1.53883
  Epoch 021 - train 0.29137 | val 1.49732
  Classification -> best τ=0.415 (val F1=0.3587)
  Directional -> Accuracy: 0.6094, MCC: 0.2033, F1: 0.6575

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.38544 | val 0.75759
  Epoch 020 - train 0.24547 | val 1.08725
  Epoch 021 - train 0.25915 | val 1.12232
  Classification -> best τ=0.430 (val F1=0.3498)
  Directional -> Accuracy: 0.6327, MCC: 0.2696, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51698 | val 1.00360
  Epoch 020 - train 0.39962 | val 1.19144
  Epoch 021 - train 0.39779 | val 1.20432
  Classification -> best τ=0.475 (val F1=0.2347)
  Directional -> Accuracy: 0.5370, MCC: 0.1050, F1: 0.5902

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42868 | val 1.80294
  Epoch 020 - train 0.31478 | val 2.80401
  Epoch 021 - train 0.28320 | val 3.06129
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47074 | val 0.65754
  Epoch 020 - train 0.25379 | val 1.08586
  Epoch 027 - train 0.22751 | val 1.53327
  Classification -> best τ=0.515 (val F1=0.4264)
  Directional -> Accuracy: 0.5111, MCC: 0.0632, F1: 0.4500

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51608 | val 1.34578
  Epoch 020 - train 0.40567 | val 2.88227
  Epoch 022 - train 0.37363 | val 3.07237
  Classification -> best τ=0.415 (val F1=0.2932)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.51989 | val 0.68699
  Epoch 020 - train 0.28296 | val 1.14757
  Epoch 028 - train 0.19230 | val 1.59068
  Classification -> best τ=0.495 (val F1=0.1860)
  Directional -> Accuracy: 0.4884, MCC: -0.0238, F1: 0.5000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49877 | val 0.77938
  Epoch 020 - train 0.33696 | val 0.90881
  Epoch 021 - train 0.32582 | val 0.96543
  Classification -> best τ=0.495 (val F1=0.1183)
  Directional -> Accuracy: 0.6154, MCC: 0.1723, F1: 0.7059

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45138 | val 0.75350
  Epoch 020 - train 0.26652 | val 0.93428
  Epoch 025 - train 0.20991 | val 1.19206
  Classification -> best τ=0.500 (val F1=0.2193)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.55528 | val 0.76951
  Epoch 020 - train 0.45887 | val 1.06704
  Epoch 021 - train 0.43585 | val 1.13056
  Classification -> best τ=0.570 (val F1=0.1604)
  Directional -> Accuracy: 0.4151, MCC: -0.1535, F1: 0.1143

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.49177 | val 2.38415
  Epoch 020 - train 0.38602 | val 3.84266
  Epoch 022 - train 0.37811 | val 4.24883
  Classification -> best τ=0.685 (val F1=0.2193)
  Directional -> Accuracy: 0.5185, MCC: 0.0639, F1: 0.1875

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.53645 | val 0.72311
  Epoch 020 - train 0.41892 | val 0.97445
  Epoch 025 - train 0.32927 | val 1.18205
  Classification -> best τ=0.470 (val F1=0.2601)
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.49426 | val 2.44314
  Epoch 020 - train 0.32036 | val 4.54546
  Epoch 021 - train 0.29278 | val 4.67233
  Classification -> best τ=0.610 (val F1=0.1238)
  Directional -> Accuracy: 0.4340, MCC: -0.1373, F1: 0.4828

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.52812 | val 0.71879
  Epoch 020 - train 0.36203 | val 1.76483

[I 2026-02-19 00:38:06,072] Trial 14 finished with value: 0.23365837314512136 and parameters: {'feature_set': 'stance', 'model_type': 'BiGRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 0.002221699549664413, 'weight_decay': 1.7167169193734489e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.8938163427764638, 'early_stopping_min_delta': 0.0014292507175386014}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 025 - train 0.27490 | val 1.84112
  Classification -> best τ=0.505 (val F1=0.2969)
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23365837314512136
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62596 | val 0.69206
  Epoch 016 - train 0.61542 | val 0.69638
  Classification -> best τ=0.505 (val F1=0.2524)
  Directional -> Accuracy: 0.5200, MCC: -0.0420, F1: 0.1818

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59327 | val 0.69788
  Epoch 016 - train 0.57444 | val 0.75247
  Classification -> best τ=0.480 (val F1=0.0547)
  Directional -> Accuracy: 0.6136, MCC: 0.1704, F1: 0.7018

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.63426 | val 0.70059
  Epoch 018 - train 0.59805 | val 0.75735
  Classification -> best τ=0.475 (val F1=0.3492)
  Directional -> Accuracy: 0.4444, MCC: -0.1071, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62584 | val 1.02407
  Epoch 016 - train 0.61147 | val 1.24710
  Classification -> best τ=0.500 (val F1=0.1451)
  Directional -> Accuracy: 0.4658, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60574 | val 0.64194
  Epoch 020 - train 0.53804 | val 0.62045
  Epoch 030 - train 0.50323 | val 0.63636
  Epoch 033 - train 0.49283 | val 0.64154
  Classification -> best τ=0.525 (val F1=0.4483)
  Directional -> Accuracy: 0.6735, MCC: 0.3624, F1: 0.7241

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61490 | val 0.69597
  Epoch 016 - train 0.58060 | val 0.72050
  Classification -> best τ=0.545 (val F1=0.2782)
  Directional -> Accuracy: 0.5556, MCC: 0.1089, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63962 | val 0.68449
  Epoch 020 - train 0.58888 | val 0.68637
  Epoch 023 - train 0.58265 | val 0.68227
  Classification -> best τ=0.480 (val F1=0.2945)
  Directional -> Accuracy: 0.4030, MCC: 0.0000, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.59775 | val 0.75360
  Epoch 016 - train 0.55869 | val 0.79986
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.60633 | val 0.72625
  Epoch 016 - train 0.58342 | val 0.78203
  Classification -> best τ=0.540 (val F1=0.3273)
  Directional -> Accuracy: 0.5745, MCC: 0.1475, F1: 0.5455

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61410 | val 0.69054
  Epoch 020 - train 0.57807 | val 0.69561
  Epoch 023 - train 0.57138 | val 0.69363
  Classification -> best τ=0.475 (val F1=0.2279)
  Directional -> Accuracy: 0.3971, MCC: -0.1468, F1: 0.5176

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.61119 | val 0.72085
  Epoch 016 - train 0.60379 | val 0.77563
  Classification -> best τ=0.515 (val F1=0.0689)
  Directional -> Accuracy: 0.5625, MCC: 0.1586, F1: 0.0870

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62899 | val 0.74487
  Epoch 016 - train 0.59445 | val 0.85989
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58104 | val 0.95196
  Epoch 016 - train 0.56421 | val 1.45938
  Classification -> best τ=0.455 (val F1=0.1101)
  Directional -> Accuracy: 0.4082, MCC: -0.1826, F1: 0.4314

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62134 | val 0.62660
  Epoch 020 - train 0.56900 | val 0.62982
  Epoch 026 - train 0.54411 | val 0.64575
  Classification -> best τ=0.340 (val F1=0.3384)
  Directional -> Accuracy: 0.5593, MCC: 0.2354, F1: 0.6977

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60918 | val 0.72070
  Epoch 016 - train 0.58952 | val 0.77938
  Classification -> best τ=0.530 (val F1=0.0621)
  Directional -> Accuracy: 0.4800, MCC: 0.1129, F1: 0.6176

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.63657 | val 0.76951
  Epoch 016 - train 0.60586 | val 0.81497
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62429 | val 0.81216
  Epoch 016 - train 0.61117 | val 1.06604
  Classification -> best τ=0.490 (val F1=0.1325)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62916 | val 0.85704
  Epoch 016 - train 0.60664 | val 1.11056
  Classification -> best τ=0.480 (val F1=0.1265)
  Directional -> Accuracy: 0.4459, MCC: 0.1697, F1: 0.1277

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.61930 | val 0.68358
  Epoch 020 - train 0.56756 | val 0.69679
  Epoch 027 - train 0.54295 | val 0.71226
  Classification -> best τ=0.590 (val F1=0.3318)
  Directional -> Accuracy: 0.4444, MCC: 0.0860, F1: 0.1463

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62165 | val 0.68045
  Epoch 020 - train 0.55980 | val 0.68679
  Epoch 023 - train 0.56518 | val 0.68615
  Classification -> best τ=0.510 (val F1=0.1826)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62311 | val 0.69184
  Epoch 016 - train 0.58394 | val 0.69872
  Classification -> best τ=0.520 (val F1=0.2624)
  Directional -> Accuracy: 0.4783, MCC: -0.1720, F1: 0.6129

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61666 | val 0.78897
  Epoch 016 - train 0.60509 | val 0.89544
  Classification -> best τ=0.530 (val F1=0.1300)
  Directional -> Accuracy: 0.5156, MCC: 0.0501, F1: 0.2051

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61935 | val 0.68602
  Epoch 020 - train 0.56023 | val 0.76111
  Epoch 023 - train 0.55633 | val 0.76154
  Classification -> best τ=0.570 (val F1=0.3931)
  Directional -> Accuracy: 0.5536, MCC: 0.0466, F1: 0.6575

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61630 | val 0.69773
  Epoch 016 - train 0.59685 | val 0.75752
  Classification -> best τ=0.465 (val F1=0.1604)
  Directional -> Accuracy: 0.5000, MCC: -0.0079, F1: 0.4483

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61976 | val 0.66171
  Epoch 020 - train 0.56161 | val 0.64338
  Epoch 030 - train 0.52051 | val 0.65689
  Epoch 031 - train 0.52580 | val 0.65720
  Classification -> best τ=0.555 (val F1=0.3995)
  Directional -> Accuracy: 0.4444, MCC: -0.0991, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60724 | val 0.69163
  Epoch 020 - train 0.55181 | val 0.70458
  Epoch 023 - train 0.54465 | val 0.71145
  Classification -> best τ=0.525 (val F1=0.1852)
  Directional -> Accuracy: 0.5349, MCC: -0.0696, F1: 0.1667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60628 | val 0.69287
  Epoch 020 - train 0.57561 | val 0.67869
  Epoch 030 - train 0.53661 | val 0.66714
  Epoch 040 - train 0.49418 | val 0.65949
  Epoch 050 - train 0.45378 | val 0.64698
  Classification -> best τ=0.485 (val F1=0.5229)
  Directional -> Accuracy: 0.5510, MCC: 0.0562, F1: 0.6333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61480 | val 0.71550
  Epoch 016 - train 0.59519 | val 0.78818
  Classification -> best τ=0.465 (val F1=0.2085)
  Directional -> Accuracy: 0.5455, MCC: 0.2887, F1: 0.2857

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63293 | val 0.69443
  Epoch 016 - train 0.60361 | val 0.69733
  Classification -> best τ=0.465 (val F1=0.2496)
  Directional -> Accuracy: 0.4211, MCC: -0.1291, F1: 0.0833

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60714 | val 0.74466
  Epoch 016 - train 0.59848 | val 0.81103
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62709 | val 0.69494
  Epoch 016 - train 0.61119 | val 0.71635
  Classification -> best τ=0.535 (val F1=0.1437)
  Directional -> Accuracy: 0.4878, MCC: 0.0447, F1: 0.3636

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59548 | val 0.68520
  Epoch 020 - train 0.55296 | val 0.70895
  Epoch 022 - train 0.54405 | val 0.70970
  Classification -> best τ=0.460 (val F1=0.2357)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61046 | val 0.66204
  Epoch 020 - train 0.55852 | val 0.69991
  Epoch 023 - train 0.55439 | val 0.70466
  Classification -> best τ=0.375 (val F1=0.2961)
  Directional -> Accuracy: 0.5634, MCC: 0.1538, F1: 0.5507

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61833 | val 0.71808
  Epoch 016 - train 0.57690 | val 0.76773
  Classification -> best τ=0.505 (val F1=0.1980)
  Directional -> Accuracy: 0.5952, MCC: 0.2132, F1: 0.6383

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60461 | val 0.70418
  Epoch 018 - train 0.57496 | val 0.79636
  Classification -> best τ=0.445 (val F1=0.3577)
  Directional -> Accuracy: 0.5846, MCC: 0.1240, F1: 0.6747

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58183 | val 0.68682
  Epoch 020 - train 0.52559 | val 0.72557
  Epoch 025 - train 0.51010 | val 0.76199
  Classification -> best τ=0.400 (val F1=0.2582)
  Directional -> Accuracy: 0.7000, MCC: 0.3985, F1: 0.7143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59617 | val 0.71162
  Epoch 016 - train 0.58324 | val 0.73507
  Classification -> best τ=0.515 (val F1=0.1052)
  Directional -> Accuracy: 0.5273, MCC: 0.0467, F1: 0.4800

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61082 | val 0.74116
  Epoch 016 - train 0.58879 | val 0.87997
  Classification -> best τ=0.505 (val F1=0.1662)
  Directional -> Accuracy: 0.6222, MCC: 0.1172, F1: 0.7385

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.61487 | val 0.68587
  Epoch 020 - train 0.56051 | val 0.66916
  Epoch 030 - train 0.51522 | val 0.68419
  Epoch 036 - train 0.49095 | val 0.70232
  Classification -> best τ=0.620 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61912 | val 0.69999
  Epoch 020 - train 0.56996 | val 0.83696
  Epoch 021 - train 0.56920 | val 0.83954
  Classification -> best τ=0.490 (val F1=0.1504)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61731 | val 0.71019
  Epoch 016 - train 0.58234 | val 0.73498
  Classification -> best τ=0.510 (val F1=0.1980)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4762

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61996 | val 0.69075
  Epoch 020 - train 0.56134 | val 0.67098
  Epoch 030 - train 0.50599 | val 0.68299
  Epoch 035 - train 0.48437 | val 0.68698
  Classification -> best τ=0.455 (val F1=0.2182)
  Directional -> Accuracy: 0.6341, MCC: 0.2238, F1: 0.7541

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61592 | val 0.69954
  Epoch 020 - train 0.55096 | val 0.68963
  Epoch 030 - train 0.51378 | val 0.66817
  Epoch 040 - train 0.46806 | val 0.67624
  Epoch 046 - train 0.45289 | val 0.70026
  Classification -> best τ=0.475 (val F1=0.3887)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61756 | val 0.77703
  Epoch 016 - train 0.60710 | val 0.93492
  Classification -> best τ=0.485 (val F1=0.1386)
  Directional -> Accuracy: 0.4444, MCC: -0.0219, F1: 0.0625

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61022 | val 0.80048
  Epoch 016 - train 0.59501 | val 1.00136
  Classification -> best τ=0.505 (val F1=0.1296)
  Directional -> Accuracy: 0.5091, MCC: 0.1336, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60786 | val 0.68678
  Epoch 020 - train 0.56098 | val 0.80966
  Epoch 023 - train 0.53651 | val 0.84622
  Classification -> best τ=0.535 (val F1=0.1493)
  Directional -> Accuracy: 0.5192, MCC: 0.0508, F1: 0.6377

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62395 | val 0.73037
  Epoch 020 - train 0.58274 | val 0.81289
  Classification -> best τ=0.545 (val F1=0.1866)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62981 | val 0.68689
  Epoch 020 - train 0.57985 | val 0.94943

[I 2026-02-19 00:40:40,048] Trial 15 finished with value: 0.21131312271893307 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 0.0002778379725135458, 'weight_decay': 1.3120901747355386e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5885647689922637, 'early_stopping_min_delta': 0.0028050946904807287}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 023 - train 0.56510 | val 1.03038
  Classification -> best τ=0.475 (val F1=0.1479)
  Directional -> Accuracy: 0.4407, MCC: -0.1164, F1: 0.4407

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21131312271893307
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.51386 | val 0.83127
  Epoch 020 - train 0.25271 | val 0.86606
  Epoch 026 - train 0.09770 | val 1.75118
  Classification -> best τ=0.560 (val F1=0.2453)
  Directional -> Accuracy: 0.5584, MCC: 0.0742, F1: 0.1905

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.39470 | val 0.72305
  Epoch 020 - train 0.09290 | val 0.98317
  Epoch 027 - train 0.03081 | val 1.56601
  Classification -> best τ=0.460 (val F1=0.3012)
  Directional -> Accuracy: 0.6522, MCC: 0.2923, F1: 0.6923

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.43721 | val 0.72299
  Epoch 020 - train 0.08798 | val 0.96318
  Epoch 026 - train 0.01900 | val 1.46535
  Classification -> best τ=0.510 (val F1=0.3534)
  Directional -> Accuracy: 0.5745, MCC: 0.1569, F1: 0.5652

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57602 | val 1.10606
  Epoch 020 - train 0.18449 | val 2.71342
  Epoch 021 - train 0.17159 | val 1.83737
  Classification -> best τ=0.395 (val F1=0.0642)
  Directional -> Accuracy: 0.5067, MCC: -0.0310, F1: 0.6105

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.37232 | val 1.12882
  Epoch 020 - train 0.08221 | val 1.90366
  Epoch 022 - train 0.06458 | val 2.17091
  Classification -> best τ=0.490 (val F1=0.4087)
  Directional -> Accuracy: 0.4118, MCC: -0.1718, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47895 | val 1.15080
  Epoch 020 - train 0.12905 | val 1.44455
  Epoch 026 - train 0.05578 | val 1.75072
  Classification -> best τ=0.400 (val F1=0.3892)
  Directional -> Accuracy: 0.5745, MCC: 0.1723, F1: 0.6429

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.49180 | val 1.34339
  Epoch 020 - train 0.13846 | val 1.38831
  Epoch 024 - train 0.07392 | val 1.81835
  Classification -> best τ=0.575 (val F1=0.3284)
  Directional -> Accuracy: 0.6087, MCC: 0.1302, F1: 0.3415

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.31901 | val 1.11198
  Epoch 020 - train 0.01219 | val 3.15217
  Epoch 027 - train 0.00285 | val 3.70261
  Classification -> best τ=0.545 (val F1=0.4113)
  Directional -> Accuracy: 0.4318, MCC: 0.0417, F1: 0.5763

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.39856 | val 1.00348
  Epoch 020 - train 0.08475 | val 2.54112
  Epoch 022 - train 0.05228 | val 2.93283
  Classification -> best τ=0.595 (val F1=0.2855)
  Directional -> Accuracy: 0.6122, MCC: 0.2829, F1: 0.2400

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57944 | val 1.14117
  Epoch 020 - train 0.29930 | val 1.99835
  Epoch 022 - train 0.31401 | val 2.10367
  Classification -> best τ=0.560 (val F1=0.1462)
  Directional -> Accuracy: 0.5286, MCC: 0.0496, F1: 0.4762

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56955 | val 1.14431
  Epoch 020 - train 0.18877 | val 2.50906
  Epoch 023 - train 0.16108 | val 2.65664
  Classification -> best τ=0.485 (val F1=0.1896)
  Directional -> Accuracy: 0.4800, MCC: 0.0401, F1: 0.6176

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.45005 | val 0.97382
  Epoch 020 - train 0.14204 | val 3.30094
  Epoch 029 - train 0.00667 | val 3.80665
  Classification -> best τ=0.535 (val F1=0.3062)
  Directional -> Accuracy: 0.6724, MCC: 0.3450, F1: 0.6780

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47668 | val 1.12880
  Epoch 020 - train 0.15581 | val 1.82373
  Epoch 021 - train 0.12474 | val 2.00992
  Classification -> best τ=0.480 (val F1=0.2719)
  Directional -> Accuracy: 0.4651, MCC: 0.1373, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.46210 | val 0.74914
  Epoch 020 - train 0.09059 | val 1.07496
  Epoch 025 - train 0.02237 | val 1.44100
  Classification -> best τ=0.310 (val F1=0.3536)
  Directional -> Accuracy: 0.5410, MCC: 0.0906, F1: 0.6500

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42557 | val 0.84227
  Epoch 020 - train 0.18421 | val 2.21521
  Epoch 021 - train 0.15665 | val 2.42580
  Classification -> best τ=0.450 (val F1=0.3756)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62895 | val 0.91451
  Epoch 020 - train 0.15931 | val 1.74600
  Epoch 022 - train 0.14055 | val 2.16766
  Classification -> best τ=0.780 (val F1=0.2751)
  Directional -> Accuracy: 0.5714, MCC: 0.1288, F1: 0.6250

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39933 | val 1.91852
  Epoch 020 - train 0.08714 | val 4.08577
  Epoch 021 - train 0.08175 | val 4.25581
  Classification -> best τ=0.585 (val F1=0.1302)
  Directional -> Accuracy: 0.4068, MCC: 0.1444, F1: 0.1026

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.53223 | val 1.34233
  Epoch 020 - train 0.31037 | val 2.68765
  Epoch 021 - train 0.26049 | val 3.11072
  Classification -> best τ=0.425 (val F1=0.0913)
  Directional -> Accuracy: 0.5921, MCC: 0.1126, F1: 0.6869

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.52070 | val 1.00077
  Epoch 020 - train 0.04780 | val 2.14406
  Epoch 022 - train 0.02946 | val 2.13241
  Classification -> best τ=0.465 (val F1=0.3001)
  Directional -> Accuracy: 0.4769, MCC: 0.1257, F1: 0.2609

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51621 | val 0.78401
  Epoch 020 - train 0.10858 | val 1.77106
  Epoch 022 - train 0.05702 | val 1.99118
  Classification -> best τ=0.535 (val F1=0.3214)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.44315 | val 1.24877
  Epoch 020 - train 0.07258 | val 2.71539
  Epoch 021 - train 0.05134 | val 2.93947
  Classification -> best τ=0.450 (val F1=0.2174)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63576 | val 0.97805
  Epoch 020 - train 0.15284 | val 1.59055
  Epoch 023 - train 0.08008 | val 1.83659
  Classification -> best τ=0.415 (val F1=0.1920)
  Directional -> Accuracy: 0.5455, MCC: 0.1085, F1: 0.6429

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.41025 | val 0.98625
  Epoch 020 - train 0.06348 | val 1.99262
  Epoch 025 - train 0.01151 | val 2.38416
  Classification -> best τ=0.575 (val F1=0.2332)
  Directional -> Accuracy: 0.5690, MCC: 0.1441, F1: 0.5902

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.52723 | val 0.68658
  Epoch 020 - train 0.10930 | val 0.94786
  Epoch 026 - train 0.02012 | val 1.23128
  Classification -> best τ=0.580 (val F1=0.3435)
  Directional -> Accuracy: 0.5000, MCC: 0.0310, F1: 0.5823

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51222 | val 0.84746
  Epoch 020 - train 0.11384 | val 1.67352
  Epoch 024 - train 0.03353 | val 2.09889
  Classification -> best τ=0.475 (val F1=0.3951)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.26240 | val 1.12488
  Epoch 020 - train 0.00736 | val 2.46670
  Epoch 023 - train 0.00372 | val 2.59001
  Classification -> best τ=0.415 (val F1=0.3464)
  Directional -> Accuracy: 0.4565, MCC: 0.1307, F1: 0.6154

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.38932 | val 0.73926
  Epoch 020 - train 0.12180 | val 1.09856
  Epoch 029 - train 0.00587 | val 1.21988
  Classification -> best τ=0.570 (val F1=0.3221)
  Directional -> Accuracy: 0.5116, MCC: -0.0112, F1: 0.5882

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42492 | val 1.57961
  Epoch 020 - train 0.14411 | val 2.70581
  Epoch 021 - train 0.13609 | val 2.83593
  Classification -> best τ=0.425 (val F1=0.2235)
  Directional -> Accuracy: 0.5088, MCC: 0.1880, F1: 0.2632

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.35182 | val 1.04018
  Epoch 020 - train 0.04327 | val 2.72348
  Epoch 027 - train 0.00819 | val 3.31973
  Classification -> best τ=0.340 (val F1=0.4543)
  Directional -> Accuracy: 0.5122, MCC: -0.0733, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.37798 | val 2.38834
  Epoch 020 - train 0.07466 | val 3.54767
  Epoch 021 - train 0.07137 | val 3.50879
  Classification -> best τ=0.590 (val F1=0.1869)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.37251 | val 1.17055
  Epoch 020 - train 0.04569 | val 2.79199
  Epoch 021 - train 0.03483 | val 2.94323
  Classification -> best τ=0.490 (val F1=0.0241)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44881 | val 1.21386
  Epoch 020 - train 0.05954 | val 2.48028
  Epoch 022 - train 0.04520 | val 2.64409
  Classification -> best τ=0.655 (val F1=0.2320)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.48251 | val 0.89180
  Epoch 020 - train 0.05107 | val 1.89413
  Epoch 022 - train 0.02284 | val 2.21293
  Classification -> best τ=0.465 (val F1=0.2419)
  Directional -> Accuracy: 0.5205, MCC: 0.1344, F1: 0.3860

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.40423 | val 1.14169
  Epoch 020 - train 0.04528 | val 2.48414
  Epoch 022 - train 0.02429 | val 2.48589
  Classification -> best τ=0.475 (val F1=0.2357)
  Directional -> Accuracy: 0.4737, MCC: -0.0538, F1: 0.5238

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.31367 | val 1.87142
  Epoch 020 - train 0.01732 | val 2.98665
  Epoch 021 - train 0.00796 | val 3.27781
  Classification -> best τ=0.420 (val F1=0.1329)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57858 | val 0.84680
  Epoch 020 - train 0.11667 | val 2.01476
  Epoch 021 - train 0.09383 | val 2.03185
  Classification -> best τ=0.425 (val F1=0.2715)
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.23389 | val 0.99690
  Epoch 020 - train 0.03285 | val 2.28955
  Epoch 023 - train 0.01562 | val 2.45890
  Classification -> best τ=0.565 (val F1=0.3556)
  Directional -> Accuracy: 0.5581, MCC: 0.1788, F1: 0.3448

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46506 | val 1.08535
  Epoch 020 - train 0.04362 | val 3.12213
  Epoch 022 - train 0.02928 | val 3.46300
  Classification -> best τ=0.280 (val F1=0.1626)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.32343 | val 1.24755
  Epoch 020 - train 0.01713 | val 3.22251
  Epoch 021 - train 0.01027 | val 3.36672
  Classification -> best τ=0.480 (val F1=0.0508)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.36318 | val 0.93690
  Epoch 020 - train 0.01811 | val 2.15058
  Epoch 022 - train 0.01584 | val 2.32625
  Classification -> best τ=0.530 (val F1=0.3894)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.31241 | val 2.12449
  Epoch 020 - train 0.02655 | val 4.43410
  Epoch 021 - train 0.01951 | val 4.63415
  Classification -> best τ=0.515 (val F1=0.2227)
  Directional -> Accuracy: 0.3947, MCC: -0.2270, F1: 0.4651

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57918 | val 0.96498
  Epoch 020 - train 0.20311 | val 2.15666
  Epoch 022 - train 0.18422 | val 2.36281
  Classification -> best τ=0.535 (val F1=0.2821)
  Directional -> Accuracy: 0.5467, MCC: 0.1126, F1: 0.6304

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42706 | val 0.90977
  Epoch 020 - train 0.07748 | val 2.08379
  Epoch 023 - train 0.02852 | val 2.47482
  Classification -> best τ=0.445 (val F1=0.1537)
  Directional -> Accuracy: 0.4894, MCC: -0.1443, F1: 0.6571

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.36418 | val 0.89499
  Epoch 020 - train 0.06999 | val 1.30732
  Epoch 021 - train 0.05430 | val 1.40811
  Classification -> best τ=0.545 (val F1=0.1951)
  Directional -> Accuracy: 0.4091, MCC: -0.1563, F1: 0.3810

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44124 | val 0.88927
  Epoch 020 - train 0.09342 | val 2.12655
  Epoch 022 - train 0.05667 | val 2.22813
  Classification -> best τ=0.395 (val F1=0.3780)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.48318 | val 0.93306
  Epoch 020 - train 0.08950 | val 1.88030
  Epoch 021 - train 0.08597 | val 1.88085
  Classification -> best τ=0.535 (val F1=0.1334)
  Directional -> Accuracy: 0.4821, MCC: -0.2215, F1: 0.6506

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43966 | val 2.48299
  Epoch 020 - train 0.04605 | val 4.28499
  Epoch 021 - train 0.03074 | val 4.17031
  Classification -> best τ=0.415 (val F1=0.2230)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.45310 | val 0.88666
  Epoch 020 - train 0.15432 | val 2.20000
  Epoch 022 - train 0.12333 | val 2.22694
  Classification -> best τ=0.415 (val F1=0.1143)

[I 2026-02-19 00:43:32,593] Trial 16 finished with value: 0.2559909066354822 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.0073335917662702204, 'weight_decay': 2.6179413710352626e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.2796703957199176, 'early_stopping_min_delta': 0.00026900745507814025}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 023 - train 0.25077 | val 1.19828
  Classification -> best τ=0.460 (val F1=0.2847)
  Directional -> Accuracy: 0.4918, MCC: -0.0077, F1: 0.5231

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2559909066354822
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.53224 | val 0.80884
  Epoch 020 - train 0.35857 | val 0.89086
  Classification -> best τ=0.560 (val F1=0.2018)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45078 | val 0.88408
  Epoch 020 - train 0.31405 | val 1.66951
  Classification -> best τ=0.420 (val F1=0.1965)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46306 | val 0.89522
  Epoch 020 - train 0.33614 | val 1.46372
  Classification -> best τ=0.450 (val F1=0.0950)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.52583 | val 1.82132
  Epoch 020 - train 0.43337 | val 2.75917
  Classification -> best τ=0.415 (val F1=0.2697)
  Directional -> Accuracy: 0.4722, MCC: 0.1092, F1: 0.0500

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43959 | val 0.72023
  Epoch 020 - train 0.30600 | val 0.81789
  Classification -> best τ=0.460 (val F1=0.5105)
  Directional -> Accuracy: 0.7292, MCC: 0.4638, F1: 0.7234

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45455 | val 0.94773
  Epoch 020 - train 0.38126 | val 1.15298
  Classification -> best τ=0.535 (val F1=0.1485)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.55790 | val 0.68808
  Epoch 020 - train 0.35444 | val 0.95127
  Classification -> best τ=0.575 (val F1=0.3156)
  Directional -> Accuracy: 0.5455, MCC: 0.0491, F1: 0.4231

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42775 | val 1.01167
  Epoch 020 - train 0.32566 | val 1.95394
  Classification -> best τ=0.545 (val F1=0.2041)
  Directional -> Accuracy: 0.5128, MCC: 0.0428, F1: 0.5128

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43796 | val 1.06982
  Epoch 020 - train 0.26060 | val 1.82308
  Classification -> best τ=0.565 (val F1=0.3944)
  Directional -> Accuracy: 0.3913, MCC: -0.1812, F1: 0.5333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47130 | val 0.97563
  Epoch 020 - train 0.37523 | val 1.34611
  Classification -> best τ=0.545 (val F1=0.1950)
  Directional -> Accuracy: 0.5821, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45948 | val 0.95891
  Epoch 020 - train 0.34270 | val 1.55600
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42607 | val 1.06602
  Epoch 020 - train 0.33869 | val 2.07657
  Classification -> best τ=0.575 (val F1=0.1183)
  Directional -> Accuracy: 0.4909, MCC: 0.0671, F1: 0.1250

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45731 | val 1.02328
  Epoch 020 - train 0.35506 | val 1.91378
  Classification -> best τ=0.450 (val F1=0.2919)
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.6479

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.46088 | val 0.72916
  Epoch 020 - train 0.33408 | val 0.90271
  Classification -> best τ=0.395 (val F1=0.3201)
  Directional -> Accuracy: 0.5517, MCC: 0.1456, F1: 0.6905

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45930 | val 1.01725
  Epoch 020 - train 0.31596 | val 1.74815
  Classification -> best τ=0.490 (val F1=0.2125)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53926 | val 0.99255
  Epoch 020 - train 0.39992 | val 1.35581
  Classification -> best τ=0.495 (val F1=0.1790)
  Directional -> Accuracy: 0.5672, MCC: 0.2497, F1: 0.3830

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.53394 | val 1.28174
  Epoch 020 - train 0.44816 | val 2.00500
  Classification -> best τ=0.665 (val F1=0.1806)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50356 | val 1.00348
  Epoch 020 - train 0.42259 | val 1.31262
  Classification -> best τ=0.555 (val F1=0.0723)
  Directional -> Accuracy: 0.3699, MCC: -0.2126, F1: 0.3030

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.46250 | val 0.77015
  Epoch 020 - train 0.27591 | val 1.40032
  Classification -> best τ=0.445 (val F1=0.3836)
  Directional -> Accuracy: 0.4516, MCC: 0.0571, F1: 0.1905

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51720 | val 0.89114
  Epoch 020 - train 0.38755 | val 1.72391
  Classification -> best τ=0.495 (val F1=0.2913)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.36135 | val 0.93330
  Epoch 020 - train 0.22385 | val 1.68656
  Classification -> best τ=0.500 (val F1=0.1826)
  Directional -> Accuracy: 0.4667, MCC: -0.0913, F1: 0.5385

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.49144 | val 0.91419
  Epoch 020 - train 0.38931 | val 1.12609
  Classification -> best τ=0.465 (val F1=0.1040)
  Directional -> Accuracy: 0.5079, MCC: 0.0449, F1: 0.6437

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46543 | val 0.86940
  Epoch 020 - train 0.34989 | val 1.06584
  Classification -> best τ=0.565 (val F1=0.2895)
  Directional -> Accuracy: 0.5818, MCC: 0.1817, F1: 0.5965

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49676 | val 0.74754
  Epoch 020 - train 0.38461 | val 0.98227
  Classification -> best τ=0.440 (val F1=0.1236)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47814 | val 0.77794
  Epoch 020 - train 0.32127 | val 1.06823
  Classification -> best τ=0.590 (val F1=0.3433)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.37668 | val 0.76996
  Epoch 020 - train 0.27689 | val 1.05572
  Classification -> best τ=0.520 (val F1=0.2303)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49253 | val 0.72883
  Epoch 020 - train 0.38605 | val 0.67989
  Classification -> best τ=0.625 (val F1=0.3096)
  Directional -> Accuracy: 0.3750, MCC: -0.1952, F1: 0.2500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47347 | val 0.83913
  Epoch 020 - train 0.39214 | val 1.20250
  Classification -> best τ=0.460 (val F1=0.1336)
  Directional -> Accuracy: 0.5185, MCC: 0.1008, F1: 0.3500

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42828 | val 0.86275
  Epoch 020 - train 0.28201 | val 1.26513
  Classification -> best τ=0.550 (val F1=0.2000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5652

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45385 | val 1.00970
  Epoch 020 - train 0.36838 | val 1.86440
  Classification -> best τ=0.525 (val F1=0.1601)
  Directional -> Accuracy: 0.5000, MCC: -0.0101, F1: 0.5455

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43728 | val 0.66745
  Epoch 020 - train 0.27962 | val 0.92488
  Classification -> best τ=0.450 (val F1=0.3780)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.49588 | val 0.83928
  Epoch 020 - train 0.35498 | val 0.87543
  Classification -> best τ=0.315 (val F1=0.2593)
  Directional -> Accuracy: 0.5571, MCC: 0.1409, F1: 0.5373

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.45992 | val 0.85419
  Epoch 020 - train 0.32495 | val 1.31215
  Classification -> best τ=0.505 (val F1=0.3015)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49146 | val 0.89066
  Epoch 020 - train 0.37422 | val 1.21465
  Classification -> best τ=0.405 (val F1=0.3663)
  Directional -> Accuracy: 0.5469, MCC: 0.0157, F1: 0.6742

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.38650 | val 0.69892
  Epoch 020 - train 0.21932 | val 0.91148
  Classification -> best τ=0.470 (val F1=0.4419)
  Directional -> Accuracy: 0.6735, MCC: 0.3624, F1: 0.6000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45333 | val 1.23525
  Epoch 020 - train 0.34844 | val 1.76408
  Classification -> best τ=0.545 (val F1=0.1496)
  Directional -> Accuracy: 0.4444, MCC: -0.1015, F1: 0.4643

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42097 | val 1.12513
  Epoch 020 - train 0.30653 | val 2.82835
  Classification -> best τ=0.525 (val F1=0.2287)
  Directional -> Accuracy: 0.3864, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46739 | val 0.68081
  Epoch 020 - train 0.30110 | val 0.69962
  Classification -> best τ=0.565 (val F1=0.3411)
  Directional -> Accuracy: 0.3778, MCC: -0.0411, F1: 0.4615

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51125 | val 1.10785
  Epoch 020 - train 0.40811 | val 1.49103
  Classification -> best τ=0.455 (val F1=0.3843)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50903 | val 0.73336
  Epoch 020 - train 0.41283 | val 0.96113
  Classification -> best τ=0.470 (val F1=0.1121)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.39660 | val 0.75827
  Epoch 020 - train 0.27911 | val 0.96925
  Classification -> best τ=0.460 (val F1=0.1918)
  Directional -> Accuracy: 0.6667, MCC: 0.3039, F1: 0.7719

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43943 | val 0.69092
  Epoch 020 - train 0.28795 | val 0.93461
  Classification -> best τ=0.485 (val F1=0.3953)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.49686 | val 0.76621
  Epoch 020 - train 0.42759 | val 0.94621
  Classification -> best τ=0.505 (val F1=0.1658)
  Directional -> Accuracy: 0.4528, MCC: -0.1508, F1: 0.5672

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46753 | val 1.85312
  Epoch 020 - train 0.38305 | val 3.03588
  Classification -> best τ=0.480 (val F1=0.1754)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42595 | val 0.89175
  Epoch 020 - train 0.33187 | val 1.22354
  Classification -> best τ=0.505 (val F1=0.3170)
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43110 | val 1.00428
  Epoch 020 - train 0.34666 | val 1.22833
  Classification -> best τ=0.505 (val F1=0.1668)
  Directional -> Accuracy: 0.4906, MCC: -0.1361, F1: 0.6582

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.49705 | val 0.68225

[I 2026-02-19 00:48:49,179] Trial 17 finished with value: 0.24361722687134796 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 0.0013988542063728528, 'weight_decay': 3.651211646644332e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.45581313986133626, 'early_stopping_min_delta': 0.0031853569020305525}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 020 - train 0.33183 | val 1.09998
  Classification -> best τ=0.525 (val F1=0.4177)
  Directional -> Accuracy: 0.5345, MCC: 0.1353, F1: 0.6301

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24361722687134796
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66254 | val 0.75272
  Epoch 011 - train 0.66183 | val 0.76885
  Classification -> best τ=0.490 (val F1=0.1314)
  Directional -> Accuracy: 0.4800, MCC: 0.1507, F1: 0.6355

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63255 | val 0.69329
  Epoch 020 - train 0.61792 | val 0.72082
  Classification -> best τ=0.450 (val F1=0.1730)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66715 | val 0.68699
  Epoch 017 - train 0.64971 | val 0.69867
  Classification -> best τ=0.475 (val F1=0.3441)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65639 | val 1.06878
  Epoch 011 - train 0.65410 | val 1.13741
  Classification -> best τ=0.500 (val F1=0.0856)
  Directional -> Accuracy: 0.5068, MCC: 0.0053, F1: 0.5500

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66380 | val 0.64140
  Epoch 020 - train 0.63652 | val 0.61722
  Epoch 024 - train 0.63101 | val 0.62522
  Classification -> best τ=0.490 (val F1=0.5569)
  Directional -> Accuracy: 0.7755, MCC: 0.5724, F1: 0.8070

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64049 | val 0.69840
  Epoch 011 - train 0.63541 | val 0.69912
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.6567

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67468 | val 0.70227
  Epoch 011 - train 0.67601 | val 0.69896
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4030, MCC: 0.0000, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64723 | val 0.72881
  Epoch 011 - train 0.64913 | val 0.73675
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64428 | val 0.71778
  Epoch 011 - train 0.64516 | val 0.71885
  Classification -> best τ=0.525 (val F1=0.1654)
  Directional -> Accuracy: 0.4255, MCC: -0.1049, F1: 0.5574

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65312 | val 0.68732
  Epoch 011 - train 0.64739 | val 0.68788
  Classification -> best τ=0.530 (val F1=0.0752)
  Directional -> Accuracy: 0.5588, MCC: 0.0432, F1: 0.3182

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66345 | val 0.68876
  Epoch 011 - train 0.65965 | val 0.69487
  Classification -> best τ=0.470 (val F1=0.2000)
  Directional -> Accuracy: 0.4792, MCC: -0.0527, F1: 0.4186

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66057 | val 0.73001
  Epoch 011 - train 0.65472 | val 0.74119
  Classification -> best τ=0.530 (val F1=0.0862)
  Directional -> Accuracy: 0.5357, MCC: 0.1397, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61902 | val 0.84947
  Epoch 011 - train 0.61977 | val 0.90286
  Classification -> best τ=0.480 (val F1=0.1533)
  Directional -> Accuracy: 0.4286, MCC: -0.2606, F1: 0.6000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66411 | val 0.65308
  Epoch 020 - train 0.63436 | val 0.65274
  Epoch 022 - train 0.63874 | val 0.65944
  Classification -> best τ=0.320 (val F1=0.3154)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63438 | val 0.74419
  Epoch 011 - train 0.62939 | val 0.75633
  Classification -> best τ=0.490 (val F1=0.0557)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64750 | val 0.71395
  Epoch 011 - train 0.64611 | val 0.72131
  Classification -> best τ=0.510 (val F1=0.2526)
  Directional -> Accuracy: 0.5735, MCC: 0.2279, F1: 0.7129

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65893 | val 0.83178
  Epoch 011 - train 0.65229 | val 0.86574
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6140, MCC: 0.0000, F1: 0.7609

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67672 | val 0.77513
  Epoch 011 - train 0.66691 | val 0.80214
  Classification -> best τ=0.510 (val F1=0.1745)
  Directional -> Accuracy: 0.5946, MCC: 0.1335, F1: 0.6809

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64645 | val 0.68543
  Epoch 017 - train 0.63557 | val 0.70014
  Classification -> best τ=0.415 (val F1=0.2149)
  Directional -> Accuracy: 0.4921, MCC: 0.1579, F1: 0.3043

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64709 | val 0.66628
  Epoch 020 - train 0.63104 | val 0.69299
  Classification -> best τ=0.480 (val F1=0.3604)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66680 | val 0.69146
  Epoch 020 - train 0.65009 | val 0.69961
  Epoch 021 - train 0.63732 | val 0.70278
  Classification -> best τ=0.455 (val F1=0.3223)
  Directional -> Accuracy: 0.5000, MCC: -0.0826, F1: 0.6102

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66864 | val 0.73436
  Epoch 011 - train 0.66831 | val 0.75164
  Classification -> best τ=0.470 (val F1=0.0996)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65033 | val 0.70379
  Epoch 011 - train 0.65218 | val 0.71112
  Classification -> best τ=0.550 (val F1=0.2431)
  Directional -> Accuracy: 0.4464, MCC: 0.0458, F1: 0.1143

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65777 | val 0.71512
  Epoch 011 - train 0.65513 | val 0.72244
  Classification -> best τ=0.470 (val F1=0.3028)
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65984 | val 0.65528
  Epoch 020 - train 0.64395 | val 0.60491
  Epoch 030 - train 0.62164 | val 0.59616
  Epoch 037 - train 0.60807 | val 0.59767
  Classification -> best τ=0.570 (val F1=0.4890)
  Directional -> Accuracy: 0.4444, MCC: -0.0991, F1: 0.0625

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64901 | val 0.69410
  Epoch 011 - train 0.65346 | val 0.69486
  Classification -> best τ=0.490 (val F1=0.2160)
  Directional -> Accuracy: 0.3953, MCC: -0.1334, F1: 0.5357

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65850 | val 0.70278
  Epoch 011 - train 0.64354 | val 0.70727
  Classification -> best τ=0.520 (val F1=0.0236)
  Directional -> Accuracy: 0.5918, MCC: 0.0000, F1: 0.7436

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65753 | val 0.70480
  Epoch 014 - train 0.65420 | val 0.73998
  Classification -> best τ=0.505 (val F1=0.2869)
  Directional -> Accuracy: 0.5273, MCC: 0.2023, F1: 0.2778

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65505 | val 0.69597
  Epoch 011 - train 0.64700 | val 0.69696
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65734 | val 0.69593
  Epoch 011 - train 0.66399 | val 0.70190
  Classification -> best τ=0.480 (val F1=0.0551)
  Directional -> Accuracy: 0.6098, MCC: 0.2302, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65280 | val 0.73392
  Epoch 011 - train 0.65727 | val 0.74369
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.63197 | val 0.68801
  Epoch 011 - train 0.62088 | val 0.68938
  Classification -> best τ=0.490 (val F1=0.2361)
  Directional -> Accuracy: 0.5000, MCC: -0.0754, F1: 0.6571

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65212 | val 0.65212
  Epoch 017 - train 0.63757 | val 0.66483
  Classification -> best τ=0.400 (val F1=0.3210)
  Directional -> Accuracy: 0.5352, MCC: 0.1239, F1: 0.4762

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64586 | val 0.71062
  Epoch 011 - train 0.65029 | val 0.71308
  Classification -> best τ=0.520 (val F1=0.1859)
  Directional -> Accuracy: 0.5476, MCC: 0.2033, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.63482 | val 0.69979
  Epoch 016 - train 0.63339 | val 0.77052
  Classification -> best τ=0.410 (val F1=0.3768)
  Directional -> Accuracy: 0.6308, MCC: 0.2541, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.63703 | val 0.68420
  Epoch 018 - train 0.62011 | val 0.69500
  Classification -> best τ=0.460 (val F1=0.2697)
  Directional -> Accuracy: 0.7000, MCC: 0.4266, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62862 | val 0.70325
  Epoch 011 - train 0.62702 | val 0.70969
  Classification -> best τ=0.490 (val F1=0.1255)
  Directional -> Accuracy: 0.4364, MCC: -0.0897, F1: 0.5634

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63442 | val 0.72803
  Epoch 011 - train 0.63357 | val 0.74000
  Classification -> best τ=0.520 (val F1=0.2626)
  Directional -> Accuracy: 0.4222, MCC: 0.0823, F1: 0.1875

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66381 | val 0.66881
  Epoch 020 - train 0.63041 | val 0.63520
  Epoch 030 - train 0.60614 | val 0.62921
  Epoch 031 - train 0.60613 | val 0.62911
  Classification -> best τ=0.570 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64852 | val 0.68403
  Epoch 017 - train 0.63089 | val 0.70514
  Classification -> best τ=0.510 (val F1=0.3012)
  Directional -> Accuracy: 0.5068, MCC: 0.0505, F1: 0.6538

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65355 | val 0.69483
  Epoch 011 - train 0.65072 | val 0.69578
  Classification -> best τ=0.470 (val F1=0.3339)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64911 | val 0.69800
  Epoch 011 - train 0.64293 | val 0.69717
  Classification -> best τ=0.520 (val F1=0.0756)
  Directional -> Accuracy: 0.4634, MCC: -0.0027, F1: 0.3889

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65245 | val 0.71875
  Epoch 011 - train 0.63775 | val 0.71838
  Classification -> best τ=0.455 (val F1=0.1942)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66554 | val 0.77308
  Epoch 011 - train 0.66679 | val 0.78646
  Classification -> best τ=0.465 (val F1=0.1914)
  Directional -> Accuracy: 0.6481, MCC: 0.3883, F1: 0.5778

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.63589 | val 0.83901
  Epoch 011 - train 0.64446 | val 0.89322
  Classification -> best τ=0.515 (val F1=0.0529)
  Directional -> Accuracy: 0.5091, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65935 | val 0.67710
  Epoch 020 - train 0.63891 | val 0.68586
  Epoch 022 - train 0.62883 | val 0.69346
  Classification -> best τ=0.590 (val F1=0.2423)
  Directional -> Accuracy: 0.5769, MCC: 0.1557, F1: 0.6071

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64984 | val 0.71501
  Epoch 011 - train 0.64823 | val 0.72591
  Classification -> best τ=0.475 (val F1=0.0666)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65764 | val 0.70475

[I 2026-02-19 00:51:02,162] Trial 18 finished with value: 0.1916531983886429 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.00014859929001842097, 'weight_decay': 3.979048435958124e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.9325358986953939, 'early_stopping_min_delta': 0.006073286010472326}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 011 - train 0.65197 | val 0.71413
  Classification -> best τ=0.475 (val F1=0.1479)
  Directional -> Accuracy: 0.3729, MCC: -0.2555, F1: 0.3509

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1916531983886429
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'stance_label', 'stance_score']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.55434 | val 1.14122
  Epoch 019 - train 0.44064 | val 1.94017
  Classification -> best τ=0.600 (val F1=0.2463)
  Directional -> Accuracy: 0.5513, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55950 | val 0.69043
  Epoch 020 - train 0.46367 | val 0.76518
  Classification -> best τ=0.500 (val F1=0.1641)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61160 | val 0.76837
  Epoch 020 - train 0.48357 | val 0.95595
  Epoch 023 - train 0.47863 | val 1.02093
  Classification -> best τ=0.575 (val F1=0.4805)
  Directional -> Accuracy: 0.5417, MCC: 0.1183, F1: 0.4762

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61611 | val 0.70466
  Epoch 020 - train 0.51411 | val 0.83783
  Epoch 029 - train 0.33732 | val 1.13012
  Classification -> best τ=0.595 (val F1=0.2329)
  Directional -> Accuracy: 0.5263, MCC: 0.1393, F1: 0.3333

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55850 | val 0.85931
  Epoch 020 - train 0.40776 | val 1.79195
  Classification -> best τ=0.505 (val F1=0.4225)
  Directional -> Accuracy: 0.6346, MCC: 0.2732, F1: 0.6415

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51580 | val 0.81218
  Epoch 016 - train 0.45895 | val 0.92127
  Classification -> best τ=0.475 (val F1=0.1349)
  Directional -> Accuracy: 0.4694, MCC: -0.0578, F1: 0.3810

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62683 | val 0.72311
  Epoch 020 - train 0.49228 | val 0.94297
  Classification -> best τ=0.525 (val F1=0.2785)
  Directional -> Accuracy: 0.4571, MCC: -0.0476, F1: 0.4571

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54198 | val 1.15578
  Epoch 016 - train 0.49363 | val 1.57560
  Classification -> best τ=0.540 (val F1=0.0714)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59917 | val 0.80823
  Epoch 016 - train 0.52242 | val 0.98926
  Classification -> best τ=0.525 (val F1=0.3403)
  Directional -> Accuracy: 0.5238, MCC: -0.0932, F1: 0.2308

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56596 | val 0.73833
  Epoch 018 - train 0.45537 | val 0.81453
  Classification -> best τ=0.455 (val F1=0.2056)
  Directional -> Accuracy: 0.4366, MCC: -0.0745, F1: 0.5238

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57093 | val 0.69772
  Epoch 016 - train 0.48789 | val 0.82676
  Classification -> best τ=0.480 (val F1=0.1835)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55917 | val 1.20977
  Epoch 016 - train 0.48001 | val 1.61964
  Classification -> best τ=0.465 (val F1=0.1532)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53241 | val 0.84712
  Epoch 019 - train 0.39852 | val 1.67226
  Classification -> best τ=0.450 (val F1=0.2929)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55092 | val 0.76033
  Epoch 016 - train 0.49824 | val 0.87256
  Classification -> best τ=0.455 (val F1=0.1714)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53426 | val 0.75508
  Epoch 020 - train 0.41006 | val 1.44273
  Epoch 023 - train 0.35109 | val 1.52560
  Classification -> best τ=0.445 (val F1=0.2809)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.55529 | val 0.92095
  Epoch 019 - train 0.45106 | val 1.32042
  Classification -> best τ=0.625 (val F1=0.3854)
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54958 | val 0.73244
  Epoch 018 - train 0.44587 | val 0.76274
  Classification -> best τ=0.565 (val F1=0.0940)
  Directional -> Accuracy: 0.4500, MCC: 0.2107, F1: 0.1951

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58622 | val 1.24117
  Epoch 016 - train 0.50817 | val 1.71859
  Classification -> best τ=0.465 (val F1=0.0635)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56307 | val 1.30264
  Epoch 017 - train 0.50335 | val 1.74493
  Classification -> best τ=0.415 (val F1=0.2409)
  Directional -> Accuracy: 0.5455, MCC: 0.2306, F1: 0.4444

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56790 | val 0.79460
  Epoch 018 - train 0.46316 | val 0.86847
  Classification -> best τ=0.490 (val F1=0.2588)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56950 | val 0.90823
  Epoch 016 - train 0.47443 | val 1.17771
  Classification -> best τ=0.470 (val F1=0.1358)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.55799 | val 0.95048
  Epoch 016 - train 0.45347 | val 0.96994
  Classification -> best τ=0.510 (val F1=0.1148)
  Directional -> Accuracy: 0.5075, MCC: 0.0055, F1: 0.6452

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57012 | val 0.84308
  Epoch 017 - train 0.49685 | val 1.04488
  Classification -> best τ=0.545 (val F1=0.2095)
  Directional -> Accuracy: 0.5593, MCC: 0.1074, F1: 0.6061

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57715 | val 0.93481
  Epoch 016 - train 0.49632 | val 1.57235
  Classification -> best τ=0.475 (val F1=0.1628)
  Directional -> Accuracy: 0.4478, MCC: -0.1187, F1: 0.6022

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.51405 | val 0.78566
  Epoch 020 - train 0.36012 | val 1.25828
  Classification -> best τ=0.510 (val F1=0.3305)
  Directional -> Accuracy: 0.5789, MCC: 0.1378, F1: 0.6364

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55748 | val 0.71649
  Epoch 016 - train 0.47581 | val 0.79352
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57562 | val 0.70392
  Epoch 020 - train 0.46169 | val 0.78500
  Classification -> best τ=0.480 (val F1=0.1394)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58285 | val 0.81786
  Epoch 016 - train 0.46385 | val 1.25994
  Classification -> best τ=0.505 (val F1=0.2576)
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56511 | val 0.72040
  Epoch 020 - train 0.41980 | val 0.90049
  Epoch 021 - train 0.40332 | val 0.93651
  Classification -> best τ=0.585 (val F1=0.3344)
  Directional -> Accuracy: 0.5349, MCC: 0.0865, F1: 0.5000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.56684 | val 0.81753
  Epoch 016 - train 0.52492 | val 0.76584
  Classification -> best τ=0.495 (val F1=0.0157)
  Directional -> Accuracy: 0.4444, MCC: -0.2043, F1: 0.6032

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58870 | val 0.71901
  Epoch 016 - train 0.53794 | val 0.76856
  Classification -> best τ=0.500 (val F1=0.2840)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58141 | val 0.69039
  Epoch 020 - train 0.41485 | val 0.86529
  Classification -> best τ=0.690 (val F1=0.2335)
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57211 | val 1.08803
  Epoch 016 - train 0.47288 | val 1.49863
  Classification -> best τ=0.465 (val F1=0.3679)
  Directional -> Accuracy: 0.5135, MCC: 0.0803, F1: 0.4545

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.56421 | val 0.72307
  Epoch 016 - train 0.49271 | val 0.84475
  Classification -> best τ=0.500 (val F1=0.2137)
  Directional -> Accuracy: 0.4872, MCC: -0.0060, F1: 0.6429

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.56196 | val 0.89918
  Epoch 016 - train 0.50410 | val 0.87970
  Classification -> best τ=0.595 (val F1=0.1071)
  Directional -> Accuracy: 0.5556, MCC: 0.1195, F1: 0.5652

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52780 | val 1.02719
  Epoch 016 - train 0.45639 | val 1.11155
  Classification -> best τ=0.490 (val F1=0.3342)
  Directional -> Accuracy: 0.6029, MCC: 0.1782, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.57042 | val 0.74363
  Epoch 016 - train 0.48939 | val 0.80950
  Classification -> best τ=0.490 (val F1=0.1794)
  Directional -> Accuracy: 0.7045, MCC: 0.4201, F1: 0.7347

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54541 | val 0.80863
  Epoch 016 - train 0.45568 | val 0.87991
  Classification -> best τ=0.525 (val F1=0.2413)
  Directional -> Accuracy: 0.4655, MCC: -0.0716, F1: 0.4364

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52408 | val 0.80448
  Epoch 016 - train 0.46955 | val 1.11954
  Classification -> best τ=0.465 (val F1=0.2799)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55761 | val 0.81047
  Epoch 017 - train 0.48630 | val 1.30186
  Classification -> best τ=0.515 (val F1=0.3410)
  Directional -> Accuracy: 0.3500, MCC: -0.0721, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.55560 | val 0.76746
  Epoch 016 - train 0.53673 | val 0.89336
  Classification -> best τ=0.470 (val F1=0.2548)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56785 | val 1.59935
  Epoch 018 - train 0.46557 | val 2.31408
  Classification -> best τ=0.430 (val F1=0.2420)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55801 | val 0.71443
  Epoch 016 - train 0.49287 | val 0.85346
  Classification -> best τ=0.460 (val F1=0.3236)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52183 | val 0.78387
  Epoch 016 - train 0.45507 | val 0.81431
  Classification -> best τ=0.550 (val F1=0.2774)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59724 | val 1.01119
  Epoch 016 - train 0.53697 | val 1.18188
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58251 | val 0.96057
  Epoch 016 - train 0.49186 | val 1.06662
  Classification -> best τ=0.485 (val F1=0.1581)
  Directional -> Accuracy: 0.6667, MCC: 0.3643, F1: 0.6415

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52406 | val 1.04115
  Epoch 016 - train 0.47433 | val 1.47334
  Classification -> best τ=0.520 (val F1=0.2908)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56906 | val 1.49134
  Epoch 016 - train 0.51316 | val 1.75302
  Classification -> best τ=0.435 (val F1=0.2054)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56604 | val 0.92573
  Epoch 017 - train 0.46627 | val 1.50456
  Classification -> best τ=0.520 (val F1=0.2112)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.53439 | val 0.75908
  Epoch 016 - train 0.45859 | val 0.73322

[I 2026-02-19 00:51:30,595] Trial 19 finished with value: 0.22025389742464427 and parameters: {'feature_set': 'stance', 'model_type': 'GRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.0033681334336737073, 'weight_decay': 4.056245972363487e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.4706635713817673, 'early_stopping_min_delta': 0.0014759099361088164}. Best is trial 10 with value: 0.2688998415931245.

  Classification -> best τ=0.485 (val F1=0.0654)
  Directional -> Accuracy: 0.4355, MCC: -0.1250, F1: 0.4928

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22025389742464427
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61960 | val 0.74714
  Epoch 020 - train 0.60587 | val 1.19243
  Classification -> best τ=0.495 (val F1=0.2018)
  Directional -> Accuracy: 0.5405, MCC: -0.0466, F1: 0.0556

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59049 | val 0.69589
  Epoch 020 - train 0.54041 | val 1.11311
  Classification -> best τ=0.415 (val F1=0.2804)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62033 | val 0.69001
  Epoch 020 - train 0.57136 | val 0.72673
  Classification -> best τ=0.495 (val F1=0.3194)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63811 | val 1.06140
  Epoch 020 - train 0.63260 | val 1.30188
  Classification -> best τ=0.480 (val F1=0.1496)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59862 | val 0.64422
  Epoch 020 - train 0.53976 | val 0.85685
  Classification -> best τ=0.465 (val F1=0.5017)
  Directional -> Accuracy: 0.6875, MCC: 0.4320, F1: 0.6154

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60384 | val 0.73118
  Epoch 020 - train 0.56808 | val 1.07864
  Classification -> best τ=0.540 (val F1=0.1654)
  Directional -> Accuracy: 0.4545, MCC: -0.0909, F1: 0.4545

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65243 | val 0.70011
  Epoch 020 - train 0.65018 | val 0.74841
  Classification -> best τ=0.485 (val F1=0.2142)
  Directional -> Accuracy: 0.4545, MCC: 0.0612, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56010 | val 0.78478
  Epoch 020 - train 0.57335 | val 1.03455
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61155 | val 0.71273
  Epoch 020 - train 0.59034 | val 0.82231
  Classification -> best τ=0.525 (val F1=0.2817)
  Directional -> Accuracy: 0.5870, MCC: 0.1754, F1: 0.5581

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61034 | val 0.73058
  Epoch 020 - train 0.57387 | val 0.85926
  Classification -> best τ=0.540 (val F1=0.2557)
  Directional -> Accuracy: 0.6119, MCC: 0.1546, F1: 0.2778

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62664 | val 0.69659
  Epoch 020 - train 0.58310 | val 0.75921
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63530 | val 0.70728
  Epoch 020 - train 0.62186 | val 0.77663
  Classification -> best τ=0.540 (val F1=0.0411)
  Directional -> Accuracy: 0.4909, MCC: 0.0251, F1: 0.2632

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56142 | val 0.72596
  Epoch 020 - train 0.53443 | val 1.25940
  Classification -> best τ=0.475 (val F1=0.1060)
  Directional -> Accuracy: 0.5208, MCC: 0.0384, F1: 0.4889

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.60265 | val 0.67789
  Epoch 020 - train 0.58637 | val 1.06057
  Classification -> best τ=0.495 (val F1=0.2535)
  Directional -> Accuracy: 0.5517, MCC: 0.1250, F1: 0.6829

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57930 | val 0.71487
  Epoch 020 - train 0.56109 | val 1.02351
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60747 | val 0.78128
  Epoch 020 - train 0.57516 | val 1.08730
  Classification -> best τ=0.445 (val F1=0.2401)
  Directional -> Accuracy: 0.6269, MCC: 0.3045, F1: 0.7368

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62345 | val 0.81075
  Epoch 020 - train 0.59853 | val 1.21244
  Classification -> best τ=0.540 (val F1=0.1083)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66112 | val 0.68973
  Epoch 020 - train 0.63483 | val 0.75066
  Classification -> best τ=0.505 (val F1=0.2340)
  Directional -> Accuracy: 0.5479, MCC: -0.0113, F1: 0.6733

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.62867 | val 0.67995
  Epoch 020 - train 0.56834 | val 0.87024
  Classification -> best τ=0.425 (val F1=0.2992)
  Directional -> Accuracy: 0.4839, MCC: -0.0169, F1: 0.5000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62108 | val 0.68736
  Epoch 020 - train 0.55835 | val 0.71331
  Classification -> best τ=0.510 (val F1=0.3168)
  Directional -> Accuracy: 0.6111, MCC: 0.2767, F1: 0.5625

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64116 | val 0.68472
  Epoch 020 - train 0.60361 | val 0.87563
  Classification -> best τ=0.520 (val F1=0.3070)
  Directional -> Accuracy: 0.4889, MCC: -0.0962, F1: 0.5965

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61149 | val 0.71204
  Epoch 020 - train 0.60177 | val 0.80079
  Classification -> best τ=0.520 (val F1=0.0773)
  Directional -> Accuracy: 0.5556, MCC: 0.2112, F1: 0.6818

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61854 | val 0.71546
  Epoch 020 - train 0.58055 | val 0.97936
  Classification -> best τ=0.550 (val F1=0.2368)
  Directional -> Accuracy: 0.5818, MCC: 0.1062, F1: 0.6761

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63452 | val 0.70945
  Epoch 020 - train 0.60408 | val 0.92894
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62138 | val 0.66727
  Epoch 020 - train 0.56053 | val 0.59917
  Classification -> best τ=0.525 (val F1=0.4785)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.63138 | val 0.70129
  Epoch 020 - train 0.59150 | val 0.73735
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62279 | val 0.69280
  Epoch 020 - train 0.62223 | val 0.72741
  Classification -> best τ=0.555 (val F1=0.0255)
  Directional -> Accuracy: 0.4167, MCC: -0.2000, F1: 0.5000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61745 | val 0.67828
  Epoch 020 - train 0.59018 | val 0.75920
  Classification -> best τ=0.440 (val F1=0.2749)
  Directional -> Accuracy: 0.5741, MCC: 0.1339, F1: 0.6349

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.62250 | val 0.75572
  Epoch 020 - train 0.61941 | val 0.77278
  Classification -> best τ=0.545 (val F1=0.2000)
  Directional -> Accuracy: 0.4500, MCC: -0.1667, F1: 0.0833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62915 | val 0.71401
  Epoch 020 - train 0.59291 | val 0.75379
  Classification -> best τ=0.510 (val F1=0.1302)
  Directional -> Accuracy: 0.4250, MCC: -0.1182, F1: 0.3030

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.62392 | val 0.68605
  Epoch 020 - train 0.57414 | val 0.65244
  Classification -> best τ=0.575 (val F1=0.4472)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63536 | val 0.69384
  Epoch 020 - train 0.56833 | val 0.93291
  Classification -> best τ=0.345 (val F1=0.2625)
  Directional -> Accuracy: 0.5714, MCC: 0.1747, F1: 0.5455

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63641 | val 0.69851
  Epoch 020 - train 0.60916 | val 0.79115
  Classification -> best τ=0.480 (val F1=0.4422)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60659 | val 0.72594
  Epoch 020 - train 0.57986 | val 0.96793
  Classification -> best τ=0.455 (val F1=0.3021)
  Directional -> Accuracy: 0.5938, MCC: 0.1529, F1: 0.6750

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60649 | val 0.68816
  Epoch 020 - train 0.52976 | val 0.69298
  Classification -> best τ=0.550 (val F1=0.2817)
  Directional -> Accuracy: 0.4898, MCC: -0.0799, F1: 0.0741

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60966 | val 0.74320
  Epoch 020 - train 0.59394 | val 0.90276
  Classification -> best τ=0.530 (val F1=0.1579)
  Directional -> Accuracy: 0.4630, MCC: -0.0616, F1: 0.4912

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62285 | val 0.73192
  Epoch 020 - train 0.56250 | val 1.43394
  Classification -> best τ=0.515 (val F1=0.1709)
  Directional -> Accuracy: 0.4545, MCC: 0.1370, F1: 0.2500

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60589 | val 0.68570
  Epoch 020 - train 0.55387 | val 0.68822
  Classification -> best τ=0.515 (val F1=0.4524)
  Directional -> Accuracy: 0.4444, MCC: 0.0347, F1: 0.4681

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56839 | val 0.82815
  Epoch 020 - train 0.55385 | val 1.16446
  Classification -> best τ=0.490 (val F1=0.1485)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58845 | val 0.69889
  Epoch 020 - train 0.56707 | val 0.68605
  Classification -> best τ=0.370 (val F1=0.5441)
  Directional -> Accuracy: 0.5349, MCC: 0.0810, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57380 | val 0.69149
  Epoch 020 - train 0.51292 | val 0.71148
  Classification -> best τ=0.485 (val F1=0.2365)
  Directional -> Accuracy: 0.5385, MCC: -0.1101, F1: 0.6897

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58919 | val 0.70777
  Epoch 020 - train 0.56454 | val 0.71493
  Classification -> best τ=0.580 (val F1=0.2530)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65625 | val 0.72163
  Epoch 020 - train 0.63570 | val 0.76285
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5472, MCC: 0.0000, F1: 0.7073

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60529 | val 0.88192
  Epoch 020 - train 0.57116 | val 1.66563
  Classification -> best τ=0.505 (val F1=0.1754)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62714 | val 0.65489
  Epoch 020 - train 0.58275 | val 0.81417
  Classification -> best τ=0.695 (val F1=0.2758)
  Directional -> Accuracy: 0.5686, MCC: 0.1369, F1: 0.5600

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.61618 | val 0.89915
  Epoch 020 - train 0.59432 | val 1.55116
  Classification -> best τ=0.485 (val F1=0.1687)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61631 | val 0.68432

[I 2026-02-19 00:54:41,947] Trial 20 finished with value: 0.22035757881708964 and parameters: {'feature_set': 'sentinment', 'model_type': 'LSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.001006472505121864, 'weight_decay': 9.08142664587439e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.909714583710943, 'early_stopping_min_delta': 6.172551191507619e-05}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 020 - train 0.59383 | val 1.12803
  Classification -> best τ=0.535 (val F1=0.3385)
  Directional -> Accuracy: 0.5690, MCC: 0.1680, F1: 0.6154

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22035757881708964
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54539 | val 1.00003
  Epoch 020 - train 0.14566 | val 1.15963
  Epoch 024 - train 0.07136 | val 1.27444
  Classification -> best τ=0.505 (val F1=0.2054)
  Directional -> Accuracy: 0.4156, MCC: -0.1550, F1: 0.5631

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.32628 | val 1.15136
  Epoch 020 - train 0.07110 | val 1.40667
  Epoch 023 - train 0.03897 | val 1.82820
  Classification -> best τ=0.420 (val F1=0.2867)
  Directional -> Accuracy: 0.5652, MCC: 0.0406, F1: 0.7059

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48677 | val 0.90556
  Epoch 020 - train 0.10242 | val 1.17192
  Epoch 022 - train 0.06602 | val 1.42485
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60709 | val 1.48916
  Epoch 020 - train 0.20527 | val 1.81001
  Epoch 022 - train 0.39155 | val 1.65656
  Classification -> best τ=0.360 (val F1=0.1868)
  Directional -> Accuracy: 0.5200, MCC: 0.0267, F1: 0.5714

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40258 | val 1.03364
  Epoch 020 - train 0.10708 | val 1.13387
  Epoch 021 - train 0.10305 | val 1.25825
  Classification -> best τ=0.500 (val F1=0.5045)
  Directional -> Accuracy: 0.6471, MCC: 0.2917, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52804 | val 0.82566
  Epoch 020 - train 0.13668 | val 2.05506
  Epoch 021 - train 0.12286 | val 2.14459
  Classification -> best τ=0.525 (val F1=0.2928)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63508 | val 0.98370
  Epoch 020 - train 0.16541 | val 1.47411
  Epoch 022 - train 0.11525 | val 1.63113
  Classification -> best τ=0.480 (val F1=0.2198)
  Directional -> Accuracy: 0.5652, MCC: 0.1655, F1: 0.5588

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.32092 | val 0.57350
  Epoch 020 - train 0.01176 | val 2.88301
  Epoch 029 - train 0.00142 | val 3.25972
  Classification -> best τ=0.195 (val F1=0.3325)
  Directional -> Accuracy: 0.4318, MCC: 0.0417, F1: 0.5763

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48549 | val 1.11632
  Epoch 020 - train 0.10908 | val 2.95217
  Epoch 022 - train 0.06476 | val 3.27721
  Classification -> best τ=0.575 (val F1=0.1945)
  Directional -> Accuracy: 0.6122, MCC: 0.2379, F1: 0.2963

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60707 | val 0.77944
  Epoch 020 - train 0.15764 | val 1.01560
  Epoch 022 - train 0.16286 | val 1.05000
  Classification -> best τ=0.515 (val F1=0.1733)
  Directional -> Accuracy: 0.5000, MCC: 0.0339, F1: 0.5205

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40871 | val 2.59809
  Epoch 020 - train 0.11997 | val 4.04641
  Epoch 022 - train 0.06093 | val 4.60150
  Classification -> best τ=0.510 (val F1=0.1750)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50399 | val 1.23602
  Epoch 020 - train 0.10809 | val 3.33468
  Epoch 021 - train 0.09671 | val 3.55965
  Classification -> best τ=0.485 (val F1=0.1005)
  Directional -> Accuracy: 0.6379, MCC: 0.3405, F1: 0.7200

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45967 | val 1.08114
  Epoch 020 - train 0.15688 | val 2.41950
  Epoch 021 - train 0.13022 | val 2.29701
  Classification -> best τ=0.485 (val F1=0.1710)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.51108 | val 0.60991
  Epoch 020 - train 0.27667 | val 0.88745
  Epoch 030 - train 0.02649 | val 1.42544
  Epoch 031 - train 0.02297 | val 1.48152
  Classification -> best τ=0.270 (val F1=0.4128)
  Directional -> Accuracy: 0.5246, MCC: 0.0474, F1: 0.6234

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46140 | val 1.03853
  Epoch 020 - train 0.10601 | val 1.90431
  Epoch 023 - train 0.07949 | val 2.90736
  Classification -> best τ=0.530 (val F1=0.2058)
  Directional -> Accuracy: 0.5577, MCC: 0.1255, F1: 0.5660

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50156 | val 1.01254
  Epoch 020 - train 0.11280 | val 1.98511
  Epoch 022 - train 0.10103 | val 2.33028
  Classification -> best τ=0.465 (val F1=0.3678)
  Directional -> Accuracy: 0.6286, MCC: 0.2674, F1: 0.7292

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.37749 | val 1.62828
  Epoch 020 - train 0.02245 | val 3.82858
  Epoch 021 - train 0.01538 | val 4.02966
  Classification -> best τ=0.450 (val F1=0.1302)
  Directional -> Accuracy: 0.5763, MCC: -0.1088, F1: 0.7253

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58364 | val 1.23732
  Epoch 020 - train 0.26952 | val 2.10354
  Epoch 021 - train 0.26574 | val 1.81768
  Classification -> best τ=0.445 (val F1=0.2485)
  Directional -> Accuracy: 0.5921, MCC: 0.0621, F1: 0.7156

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.47591 | val 0.83277
  Epoch 020 - train 0.12376 | val 1.36933
  Epoch 022 - train 0.10391 | val 1.43408
  Classification -> best τ=0.370 (val F1=0.2464)
  Directional -> Accuracy: 0.5077, MCC: 0.1193, F1: 0.4074

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.55145 | val 1.07565
  Epoch 020 - train 0.46198 | val 1.34297
  Epoch 023 - train 0.34607 | val 1.80991
  Classification -> best τ=0.470 (val F1=0.2940)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51054 | val 0.88900
  Epoch 020 - train 0.12320 | val 2.07860
  Epoch 021 - train 0.09384 | val 2.15796
  Classification -> best τ=0.475 (val F1=0.1521)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54866 | val 1.12733
  Epoch 020 - train 0.12492 | val 2.04111
  Epoch 021 - train 0.11484 | val 2.16832
  Classification -> best τ=0.395 (val F1=0.2054)
  Directional -> Accuracy: 0.4848, MCC: -0.1240, F1: 0.6531

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63326 | val 0.81330
  Epoch 020 - train 0.28426 | val 0.90462
  Epoch 027 - train 0.02845 | val 1.48356
  Classification -> best τ=0.595 (val F1=0.2428)
  Directional -> Accuracy: 0.5172, MCC: -0.0504, F1: 0.6410

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55424 | val 0.79346
  Epoch 020 - train 0.08502 | val 0.84641
  Epoch 030 - train 0.00698 | val 1.05124
  Epoch 037 - train 0.00635 | val 1.13062
  Classification -> best τ=0.430 (val F1=0.3382)
  Directional -> Accuracy: 0.5303, MCC: 0.1288, F1: 0.6353

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50682 | val 1.06112
  Epoch 020 - train 0.10769 | val 1.94782
  Epoch 022 - train 0.07704 | val 2.25337
  Classification -> best τ=0.485 (val F1=0.2925)
  Directional -> Accuracy: 0.5714, MCC: 0.2023, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.25231 | val 2.06842
  Epoch 020 - train 0.00506 | val 4.03546
  Epoch 021 - train 0.00500 | val 4.18451
  Classification -> best τ=0.410 (val F1=0.1443)
  Directional -> Accuracy: 0.6087, MCC: 0.2431, F1: 0.1818

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.39331 | val 0.76186
  Epoch 020 - train 0.02489 | val 1.67835
  Epoch 025 - train 0.00460 | val 1.99719
  Classification -> best τ=0.560 (val F1=0.1816)
  Directional -> Accuracy: 0.4651, MCC: -0.0905, F1: 0.5306

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54092 | val 1.61914
  Epoch 020 - train 0.21289 | val 2.95271
  Epoch 024 - train 0.17029 | val 3.70862
  Classification -> best τ=0.440 (val F1=0.1446)
  Directional -> Accuracy: 0.4386, MCC: -0.0236, F1: 0.0588

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.31430 | val 0.91634
  Epoch 020 - train 0.02578 | val 1.78148
  Epoch 021 - train 0.01877 | val 2.06422
  Classification -> best τ=0.555 (val F1=0.1961)
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51890 | val 2.03917
  Epoch 020 - train 0.20333 | val 4.10061
  Epoch 021 - train 0.18422 | val 4.13037
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48798 | val 0.82470
  Epoch 020 - train 0.26205 | val 1.59407
  Epoch 021 - train 0.24961 | val 1.59626
  Classification -> best τ=0.520 (val F1=0.2324)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58413 | val 0.91871
  Epoch 020 - train 0.16896 | val 1.32009
  Epoch 022 - train 0.12714 | val 1.65073
  Classification -> best τ=0.425 (val F1=0.2449)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.57848 | val 1.48103
  Epoch 020 - train 0.17643 | val 1.81633
  Epoch 022 - train 0.11853 | val 1.42257
  Classification -> best τ=0.345 (val F1=0.2717)
  Directional -> Accuracy: 0.5205, MCC: 0.0806, F1: 0.4776

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.41239 | val 1.03879
  Epoch 020 - train 0.06491 | val 2.25907
  Epoch 022 - train 0.02991 | val 2.55113
  Classification -> best τ=0.450 (val F1=0.2182)
  Directional -> Accuracy: 0.5263, MCC: 0.1644, F1: 0.6786

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.36919 | val 1.38952
  Epoch 020 - train 0.02768 | val 3.37196
  Epoch 021 - train 0.02314 | val 3.62060
  Classification -> best τ=0.595 (val F1=0.2506)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55145 | val 0.84644
  Epoch 020 - train 0.19661 | val 1.52402
  Epoch 021 - train 0.17716 | val 1.35300
  Classification -> best τ=0.370 (val F1=0.2014)
  Directional -> Accuracy: 0.5522, MCC: 0.1203, F1: 0.5588

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.39420 | val 1.15288
  Epoch 020 - train 0.09519 | val 2.13437
  Epoch 023 - train 0.07528 | val 2.32970
  Classification -> best τ=0.570 (val F1=0.2652)
  Directional -> Accuracy: 0.5581, MCC: 0.2093, F1: 0.2963

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47751 | val 1.10830
  Epoch 020 - train 0.07414 | val 2.83891
  Epoch 021 - train 0.06240 | val 2.97314
  Classification -> best τ=0.420 (val F1=0.1590)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43603 | val 0.83988
  Epoch 020 - train 0.03088 | val 1.42139
  Epoch 021 - train 0.02389 | val 1.48043
  Classification -> best τ=0.370 (val F1=0.1162)
  Directional -> Accuracy: 0.5745, MCC: -0.0834, F1: 0.7222

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.32554 | val 1.05974
  Epoch 020 - train 0.01898 | val 2.96189
  Epoch 022 - train 0.01971 | val 3.05525
  Classification -> best τ=0.490 (val F1=0.3973)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.33685 | val 1.70662
  Epoch 020 - train 0.02920 | val 3.38299
  Epoch 021 - train 0.02349 | val 3.54239
  Classification -> best τ=0.400 (val F1=0.4223)
  Directional -> Accuracy: 0.3421, MCC: -0.4045, F1: 0.4898

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52910 | val 1.12284
  Epoch 020 - train 0.20753 | val 1.92505
  Epoch 024 - train 0.10934 | val 2.85416
  Classification -> best τ=0.405 (val F1=0.3620)
  Directional -> Accuracy: 0.5333, MCC: 0.2014, F1: 0.6789

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47659 | val 0.82285
  Epoch 020 - train 0.10383 | val 1.77206
  Epoch 023 - train 0.07688 | val 1.78663
  Classification -> best τ=0.490 (val F1=0.2470)
  Directional -> Accuracy: 0.5319, MCC: 0.0653, F1: 0.5217

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48146 | val 1.25181
  Epoch 020 - train 0.07377 | val 3.23657
  Epoch 021 - train 0.05282 | val 3.35175
  Classification -> best τ=0.500 (val F1=0.5752)
  Directional -> Accuracy: 0.4773, MCC: -0.0586, F1: 0.5306

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.33703 | val 0.98843
  Epoch 020 - train 0.03854 | val 1.72450
  Epoch 022 - train 0.02249 | val 1.61018
  Classification -> best τ=0.470 (val F1=0.6659)
  Directional -> Accuracy: 0.3673, MCC: -0.1814, F1: 0.5373

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42495 | val 0.85283
  Epoch 020 - train 0.04138 | val 2.78908
  Epoch 021 - train 0.04690 | val 2.98943
  Classification -> best τ=0.605 (val F1=0.1914)
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40389 | val 1.89036
  Epoch 020 - train 0.02320 | val 3.36677
  Epoch 022 - train 0.01262 | val 3.93622
  Classification -> best τ=0.555 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44860 | val 0.81658
  Epoch 020 - train 0.17571 | val 1.74835

[I 2026-02-19 00:57:32,029] Trial 21 finished with value: 0.2455105016768623 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.009920016916743582, 'weight_decay': 3.3487337520188137e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.303657701666853, 'early_stopping_min_delta': 0.000966873267358941}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 026 - train 0.09090 | val 3.23147
  Classification -> best τ=0.445 (val F1=0.2063)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2455105016768623
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.48585 | val 0.74258
  Epoch 020 - train 0.10614 | val 1.83758
  Epoch 025 - train 0.02819 | val 2.39058
  Classification -> best τ=0.670 (val F1=0.2851)
  Directional -> Accuracy: 0.5325, MCC: 0.0120, F1: 0.2800

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42937 | val 0.84822
  Epoch 020 - train 0.09503 | val 1.50316
  Epoch 022 - train 0.06944 | val 1.66993
  Classification -> best τ=0.525 (val F1=0.1236)
  Directional -> Accuracy: 0.5870, MCC: 0.1462, F1: 0.6545

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.40423 | val 0.75144
  Epoch 020 - train 0.07357 | val 1.31289
  Epoch 022 - train 0.04735 | val 1.53744
  Classification -> best τ=0.540 (val F1=0.2616)
  Directional -> Accuracy: 0.4681, MCC: -0.0135, F1: 0.0741

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57900 | val 1.30432
  Epoch 020 - train 0.14473 | val 2.76666
  Epoch 021 - train 0.16971 | val 3.44452
  Classification -> best τ=0.395 (val F1=0.1713)
  Directional -> Accuracy: 0.5067, MCC: 0.0573, F1: 0.4127

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41370 | val 0.78095
  Epoch 020 - train 0.09074 | val 1.90510
  Epoch 022 - train 0.06122 | val 2.26317
  Classification -> best τ=0.480 (val F1=0.4598)
  Directional -> Accuracy: 0.6275, MCC: 0.2542, F1: 0.6415

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.33668 | val 0.90465
  Epoch 020 - train 0.07718 | val 1.44487
  Epoch 023 - train 0.03818 | val 1.62064
  Classification -> best τ=0.505 (val F1=0.2582)
  Directional -> Accuracy: 0.5319, MCC: 0.1506, F1: 0.0833

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47889 | val 1.15162
  Epoch 020 - train 0.06663 | val 2.01592
  Epoch 022 - train 0.03627 | val 2.12453
  Classification -> best τ=0.520 (val F1=0.2656)
  Directional -> Accuracy: 0.5797, MCC: 0.0653, F1: 0.3256

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.27915 | val 1.18309
  Epoch 020 - train 0.01349 | val 2.95967
  Epoch 026 - train 0.00722 | val 3.82546
  Classification -> best τ=0.355 (val F1=0.2192)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.38722 | val 1.23106
  Epoch 020 - train 0.03829 | val 2.79467
  Epoch 022 - train 0.02125 | val 3.07298
  Classification -> best τ=0.600 (val F1=0.2891)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.47712 | val 0.78745
  Epoch 020 - train 0.08601 | val 1.15958
  Epoch 024 - train 0.02696 | val 1.58924
  Classification -> best τ=0.485 (val F1=0.2005)
  Directional -> Accuracy: 0.3714, MCC: -0.2165, F1: 0.4884

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.39508 | val 2.03065
  Epoch 020 - train 0.06935 | val 3.01500
  Epoch 022 - train 0.05023 | val 2.16323
  Classification -> best τ=0.520 (val F1=0.2107)
  Directional -> Accuracy: 0.5400, MCC: 0.0164, F1: 0.0800

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.35489 | val 2.76054
  Epoch 020 - train 0.03582 | val 4.68897
  Epoch 021 - train 0.02594 | val 5.04781
  Classification -> best τ=0.505 (val F1=0.1234)
  Directional -> Accuracy: 0.6379, MCC: 0.2774, F1: 0.6182

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42552 | val 1.24403
  Epoch 020 - train 0.15322 | val 3.63469
  Epoch 021 - train 0.13150 | val 3.35766
  Classification -> best τ=0.435 (val F1=0.2719)
  Directional -> Accuracy: 0.4419, MCC: -0.0375, F1: 0.5862

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39993 | val 0.77049
  Epoch 020 - train 0.03359 | val 1.24991
  Epoch 025 - train 0.01195 | val 1.32690
  Classification -> best τ=0.320 (val F1=0.3915)
  Directional -> Accuracy: 0.5574, MCC: 0.1455, F1: 0.6747

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46540 | val 1.39224
  Epoch 020 - train 0.09994 | val 1.76719
  Epoch 021 - train 0.08688 | val 1.87427
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.40382 | val 1.24259
  Epoch 020 - train 0.08812 | val 1.81798
  Epoch 022 - train 0.05491 | val 1.98574
  Classification -> best τ=0.580 (val F1=0.3197)
  Directional -> Accuracy: 0.5857, MCC: 0.1518, F1: 0.6588

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43386 | val 1.31093
  Epoch 020 - train 0.04568 | val 2.76290
  Epoch 021 - train 0.03213 | val 3.05143
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47848 | val 1.12896
  Epoch 020 - train 0.10665 | val 3.63961
  Epoch 021 - train 0.08241 | val 3.99242
  Classification -> best τ=0.550 (val F1=0.1056)
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.39932 | val 1.23960
  Epoch 020 - train 0.02531 | val 2.05232
  Epoch 022 - train 0.01391 | val 2.19990
  Classification -> best τ=0.350 (val F1=0.3342)
  Directional -> Accuracy: 0.5077, MCC: 0.1597, F1: 0.3600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49027 | val 1.04076
  Epoch 020 - train 0.18490 | val 1.81353
  Epoch 021 - train 0.17445 | val 1.99323
  Classification -> best τ=0.435 (val F1=0.1698)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.36650 | val 1.40753
  Epoch 020 - train 0.05350 | val 2.45063
  Epoch 021 - train 0.03954 | val 2.51843
  Classification -> best τ=0.465 (val F1=0.1521)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42991 | val 1.43417
  Epoch 020 - train 0.06947 | val 2.27410
  Epoch 022 - train 0.05027 | val 2.31276
  Classification -> best τ=0.395 (val F1=0.2390)
  Directional -> Accuracy: 0.4697, MCC: -0.1768, F1: 0.6392

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.38914 | val 0.89021
  Epoch 020 - train 0.07698 | val 1.71316
  Epoch 024 - train 0.03255 | val 1.92384
  Classification -> best τ=0.575 (val F1=0.2894)
  Directional -> Accuracy: 0.5345, MCC: 0.0278, F1: 0.6197

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.44929 | val 0.72574
  Epoch 020 - train 0.10219 | val 1.01115
  Epoch 028 - train 0.01447 | val 1.35515
  Classification -> best τ=0.365 (val F1=0.2631)
  Directional -> Accuracy: 0.4697, MCC: -0.0257, F1: 0.5977

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.45607 | val 0.84870
  Epoch 020 - train 0.06105 | val 1.24706
  Epoch 024 - train 0.01970 | val 1.42442
  Classification -> best τ=0.590 (val F1=0.3824)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.20341 | val 1.07624
  Epoch 020 - train 0.03977 | val 2.01766
  Epoch 021 - train 0.02899 | val 2.14388
  Classification -> best τ=0.445 (val F1=0.2774)
  Directional -> Accuracy: 0.4130, MCC: -0.1462, F1: 0.4490

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.34078 | val 0.66781
  Epoch 020 - train 0.03234 | val 1.27609
  Epoch 028 - train 0.00371 | val 1.59060
  Classification -> best τ=0.540 (val F1=0.3745)
  Directional -> Accuracy: 0.4651, MCC: -0.1076, F1: 0.5490

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46655 | val 1.38334
  Epoch 020 - train 0.14089 | val 2.49378
  Epoch 022 - train 0.12312 | val 2.63925
  Classification -> best τ=0.450 (val F1=0.1789)
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.32074 | val 0.81799
  Epoch 020 - train 0.08371 | val 2.37423
  Epoch 021 - train 0.08507 | val 2.47370
  Classification -> best τ=0.520 (val F1=0.3069)
  Directional -> Accuracy: 0.5366, MCC: 0.0241, F1: 0.6780

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.34227 | val 2.47755
  Epoch 020 - train 0.09263 | val 3.59207
  Epoch 021 - train 0.07820 | val 3.66745
  Classification -> best τ=0.615 (val F1=0.2683)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42491 | val 1.07915
  Epoch 020 - train 0.08200 | val 2.53120
  Epoch 021 - train 0.06138 | val 2.76974
  Classification -> best τ=0.460 (val F1=0.2533)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.33685 | val 1.36296
  Epoch 020 - train 0.04960 | val 2.83306
  Epoch 023 - train 0.02496 | val 3.04990
  Classification -> best τ=0.270 (val F1=0.2668)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.45910 | val 0.86967
  Epoch 020 - train 0.07433 | val 1.49010
  Epoch 023 - train 0.03495 | val 1.81227
  Classification -> best τ=0.320 (val F1=0.2492)
  Directional -> Accuracy: 0.5479, MCC: 0.1054, F1: 0.5600

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.37836 | val 0.97486
  Epoch 020 - train 0.06107 | val 2.74186
  Epoch 021 - train 0.04768 | val 2.77799
  Classification -> best τ=0.445 (val F1=0.3254)
  Directional -> Accuracy: 0.5789, MCC: 0.1857, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.35952 | val 1.51606
  Epoch 020 - train 0.08136 | val 2.61137
  Epoch 021 - train 0.07422 | val 2.75540
  Classification -> best τ=0.520 (val F1=0.2920)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48840 | val 0.90931
  Epoch 020 - train 0.13994 | val 1.67967
  Epoch 021 - train 0.12474 | val 1.68835
  Classification -> best τ=0.470 (val F1=0.2999)
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.28224 | val 1.10660
  Epoch 020 - train 0.02950 | val 2.09426
  Epoch 024 - train 0.01339 | val 2.29633
  Classification -> best τ=0.535 (val F1=0.4296)
  Directional -> Accuracy: 0.6744, MCC: 0.3671, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.37472 | val 1.15213
  Epoch 020 - train 0.06610 | val 1.95116
  Epoch 021 - train 0.05230 | val 2.03990
  Classification -> best τ=0.360 (val F1=0.3769)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.37033 | val 0.89785
  Epoch 020 - train 0.06569 | val 1.84076
  Epoch 021 - train 0.05337 | val 1.97657
  Classification -> best τ=0.435 (val F1=0.1661)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39043 | val 0.94427
  Epoch 020 - train 0.03749 | val 2.86506
  Epoch 025 - train 0.01448 | val 3.21840
  Classification -> best τ=0.470 (val F1=0.3300)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.30490 | val 2.01554
  Epoch 020 - train 0.04580 | val 4.92339
  Epoch 021 - train 0.03374 | val 5.12337
  Classification -> best τ=0.485 (val F1=0.3223)
  Directional -> Accuracy: 0.3947, MCC: -0.2806, F1: 0.5306

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.49740 | val 1.33484
  Epoch 020 - train 0.09774 | val 2.57643
  Epoch 023 - train 0.06585 | val 2.87294
  Classification -> best τ=0.435 (val F1=0.3707)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.38916 | val 0.96506
  Epoch 020 - train 0.06543 | val 1.76800
  Epoch 023 - train 0.03041 | val 2.19344
  Classification -> best τ=0.440 (val F1=0.1463)
  Directional -> Accuracy: 0.4894, MCC: -0.1443, F1: 0.6571

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.35016 | val 1.07115
  Epoch 020 - train 0.07147 | val 1.88032
  Epoch 022 - train 0.03627 | val 2.08443
  Classification -> best τ=0.530 (val F1=0.1951)
  Directional -> Accuracy: 0.4773, MCC: -0.0212, F1: 0.4651

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.36491 | val 0.69042
  Epoch 020 - train 0.05125 | val 1.82883
  Epoch 030 - train 0.00962 | val 2.16579
  Classification -> best τ=0.655 (val F1=0.3330)
  Directional -> Accuracy: 0.4898, MCC: 0.2683, F1: 0.6032

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.41296 | val 1.22431
  Epoch 020 - train 0.05785 | val 3.36021
  Epoch 021 - train 0.04706 | val 3.49394
  Classification -> best τ=0.595 (val F1=0.1850)
  Directional -> Accuracy: 0.3571, MCC: -0.2821, F1: 0.3571

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.35305 | val 2.14753
  Epoch 020 - train 0.03703 | val 4.73701
  Epoch 021 - train 0.02676 | val 4.98113
  Classification -> best τ=0.425 (val F1=0.2554)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42432 | val 1.06041
  Epoch 020 - train 0.07922 | val 3.26248
  Epoch 021 - train 0.06513 | val 3.34903
  Classification -> best τ=0.360 (val F1=0.2048)

[I 2026-02-19 01:00:20,220] Trial 22 finished with value: 0.2502112562490774 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 0.004990912479577214, 'weight_decay': 3.2149377117879414e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.170257051622941, 'early_stopping_min_delta': 2.4542069745080923e-05}. Best is trial 10 with value: 0.2688998415931245.

  Classification -> best τ=0.480 (val F1=0.1396)
  Directional -> Accuracy: 0.4098, MCC: -0.1752, F1: 0.4375

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2502112562490774
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46953 | val 0.79906
  Epoch 020 - train 0.12655 | val 1.34680
  Epoch 029 - train 0.00762 | val 1.74241
  Classification -> best τ=0.590 (val F1=0.3554)
  Directional -> Accuracy: 0.5000, MCC: -0.0303, F1: 0.3810

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40107 | val 0.80804
  Epoch 020 - train 0.06648 | val 1.83531
  Epoch 023 - train 0.03141 | val 2.38325
  Classification -> best τ=0.460 (val F1=0.1860)
  Directional -> Accuracy: 0.5532, MCC: 0.0226, F1: 0.7042

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49736 | val 0.85007
  Epoch 020 - train 0.10499 | val 1.27213
  Epoch 021 - train 0.07966 | val 1.28365
  Classification -> best τ=0.440 (val F1=0.1535)
  Directional -> Accuracy: 0.5208, MCC: -0.1342, F1: 0.6849

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.53013 | val 0.80441
  Epoch 020 - train 0.09978 | val 1.75819
  Epoch 029 - train 0.00517 | val 2.00194
  Classification -> best τ=0.295 (val F1=0.2396)
  Directional -> Accuracy: 0.5132, MCC: -0.0996, F1: 0.6726

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42552 | val 0.97280
  Epoch 020 - train 0.03990 | val 1.62113
  Epoch 025 - train 0.01417 | val 2.04425
  Classification -> best τ=0.565 (val F1=0.3920)
  Directional -> Accuracy: 0.5577, MCC: 0.1637, F1: 0.4651

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46074 | val 2.29109
  Epoch 020 - train 0.12483 | val 4.47532
  Epoch 023 - train 0.08898 | val 4.73404
  Classification -> best τ=0.460 (val F1=0.2673)
  Directional -> Accuracy: 0.4694, MCC: -0.0585, F1: 0.3158

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.53985 | val 1.13680
  Epoch 020 - train 0.04918 | val 1.18890
  Epoch 025 - train 0.01143 | val 1.36764
  Classification -> best τ=0.625 (val F1=0.2949)
  Directional -> Accuracy: 0.5857, MCC: 0.0600, F1: 0.2927

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.32740 | val 1.78586
  Epoch 020 - train 0.06082 | val 4.46216
  Epoch 021 - train 0.05025 | val 4.81166
  Classification -> best τ=0.640 (val F1=0.3764)
  Directional -> Accuracy: 0.6000, MCC: 0.1802, F1: 0.5263

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.33772 | val 0.97803
  Epoch 020 - train 0.02149 | val 2.65346
  Epoch 023 - train 0.00936 | val 2.94039
  Classification -> best τ=0.520 (val F1=0.3441)
  Directional -> Accuracy: 0.5714, MCC: 0.0219, F1: 0.3077

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.44058 | val 1.54288
  Epoch 020 - train 0.08329 | val 1.96686
  Epoch 027 - train 0.01077 | val 2.09096
  Classification -> best τ=0.555 (val F1=0.2646)
  Directional -> Accuracy: 0.4648, MCC: -0.1046, F1: 0.3448

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.46681 | val 1.51068
  Epoch 020 - train 0.08668 | val 1.81439
  Epoch 021 - train 0.06846 | val 1.66902
  Classification -> best τ=0.360 (val F1=0.1895)
  Directional -> Accuracy: 0.4314, MCC: -0.1253, F1: 0.5397

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.36641 | val 2.26368
  Epoch 020 - train 0.03512 | val 3.45809
  Epoch 021 - train 0.02369 | val 3.67372
  Classification -> best τ=0.500 (val F1=0.1734)
  Directional -> Accuracy: 0.6441, MCC: 0.2942, F1: 0.6182

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38706 | val 1.04391
  Epoch 020 - train 0.07319 | val 2.05577
  Epoch 021 - train 0.05931 | val 2.06581
  Classification -> best τ=0.470 (val F1=0.2763)
  Directional -> Accuracy: 0.5227, MCC: 0.0415, F1: 0.4878

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.42709 | val 0.66322
  Epoch 020 - train 0.09340 | val 1.36925
  Epoch 021 - train 0.06767 | val 1.40803
  Classification -> best τ=0.510 (val F1=0.3848)
  Directional -> Accuracy: 0.5968, MCC: 0.1936, F1: 0.5902

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50648 | val 1.37211
  Epoch 020 - train 0.06514 | val 2.77477
  Epoch 022 - train 0.03800 | val 2.84470
  Classification -> best τ=0.465 (val F1=0.2193)
  Directional -> Accuracy: 0.5283, MCC: 0.0112, F1: 0.0741

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47956 | val 1.08265
  Epoch 020 - train 0.07343 | val 1.54123
  Epoch 022 - train 0.05447 | val 1.69237
  Classification -> best τ=0.685 (val F1=0.3764)
  Directional -> Accuracy: 0.4789, MCC: -0.0337, F1: 0.4638

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38899 | val 1.07078
  Epoch 020 - train 0.04893 | val 2.67610
  Epoch 021 - train 0.03776 | val 2.83894
  Classification -> best τ=0.550 (val F1=0.2165)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47211 | val 1.35723
  Epoch 020 - train 0.09342 | val 3.08590
  Epoch 021 - train 0.09764 | val 3.68519
  Classification -> best τ=0.540 (val F1=0.1233)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.34014 | val 0.97208
  Epoch 020 - train 0.04918 | val 2.15655
  Epoch 022 - train 0.03055 | val 2.29131
  Classification -> best τ=0.415 (val F1=0.3521)
  Directional -> Accuracy: 0.5152, MCC: 0.1571, F1: 0.4074

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49125 | val 0.79905
  Epoch 020 - train 0.10053 | val 1.31318
  Epoch 021 - train 0.08270 | val 1.48276
  Classification -> best τ=0.505 (val F1=0.3386)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.37066 | val 0.99030
  Epoch 020 - train 0.04658 | val 2.09327
  Epoch 024 - train 0.01754 | val 2.40250
  Classification -> best τ=0.455 (val F1=0.3172)
  Directional -> Accuracy: 0.5102, MCC: -0.1758, F1: 0.6571

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.46922 | val 1.09064
  Epoch 020 - train 0.08154 | val 1.68232
  Epoch 022 - train 0.04905 | val 1.95192
  Classification -> best τ=0.455 (val F1=0.1678)
  Directional -> Accuracy: 0.4776, MCC: -0.0999, F1: 0.6316

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.35010 | val 0.79897
  Epoch 020 - train 0.02433 | val 1.44432
  Epoch 022 - train 0.01001 | val 1.57236
  Classification -> best τ=0.690 (val F1=0.3228)
  Directional -> Accuracy: 0.5424, MCC: 0.3146, F1: 0.3415

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49663 | val 0.93884
  Epoch 020 - train 0.11028 | val 1.31859
  Epoch 022 - train 0.13635 | val 1.50038
  Classification -> best τ=0.535 (val F1=0.1890)
  Directional -> Accuracy: 0.4478, MCC: -0.1116, F1: 0.3934

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.35372 | val 1.12285
  Epoch 020 - train 0.07175 | val 1.84332
  Epoch 023 - train 0.04226 | val 1.93454
  Classification -> best τ=0.595 (val F1=0.4748)
  Directional -> Accuracy: 0.4912, MCC: 0.0739, F1: 0.3256

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.21156 | val 1.11934
  Epoch 020 - train 0.01150 | val 2.32685
  Epoch 022 - train 0.00607 | val 2.38463
  Classification -> best τ=0.560 (val F1=0.2563)
  Directional -> Accuracy: 0.6250, MCC: 0.3904, F1: 0.6786

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.26486 | val 1.04021
  Epoch 020 - train 0.00887 | val 2.22432
  Epoch 026 - train 0.00248 | val 2.75827
  Classification -> best τ=0.520 (val F1=0.4308)
  Directional -> Accuracy: 0.5455, MCC: 0.0598, F1: 0.6154

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.43302 | val 1.38016
  Epoch 020 - train 0.19901 | val 2.45281
  Epoch 021 - train 0.17729 | val 2.58876
  Classification -> best τ=0.485 (val F1=0.0514)
  Directional -> Accuracy: 0.5000, MCC: 0.0823, F1: 0.3256

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.31598 | val 0.72639
  Epoch 020 - train 0.04639 | val 2.91447
  Epoch 026 - train 0.01517 | val 3.07707
  Classification -> best τ=0.460 (val F1=0.3901)
  Directional -> Accuracy: 0.5581, MCC: 0.1655, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.32690 | val 1.16205
  Epoch 020 - train 0.07220 | val 1.68836
  Epoch 022 - train 0.05053 | val 1.71795
  Classification -> best τ=0.500 (val F1=0.1512)
  Directional -> Accuracy: 0.5333, MCC: 0.0786, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.37641 | val 0.95778
  Epoch 020 - train 0.07608 | val 1.81577
  Epoch 025 - train 0.02726 | val 2.00309
  Classification -> best τ=0.590 (val F1=0.1179)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.34329 | val 1.02235
  Epoch 020 - train 0.01893 | val 1.92304
  Epoch 022 - train 0.01406 | val 2.08339
  Classification -> best τ=0.355 (val F1=0.2335)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.50257 | val 0.86699
  Epoch 020 - train 0.03998 | val 2.69180
  Epoch 022 - train 0.02222 | val 3.00213
  Classification -> best τ=0.525 (val F1=0.2419)
  Directional -> Accuracy: 0.5135, MCC: 0.1271, F1: 0.3793

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.31973 | val 0.94957
  Epoch 020 - train 0.06964 | val 1.11436
  Epoch 021 - train 0.05546 | val 1.12528
  Classification -> best τ=0.485 (val F1=0.0658)
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.35835 | val 0.92611
  Epoch 020 - train 0.04340 | val 2.19584
  Epoch 021 - train 0.03193 | val 2.30033
  Classification -> best τ=0.485 (val F1=0.2922)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.44728 | val 0.97321
  Epoch 020 - train 0.09404 | val 1.50299
  Epoch 024 - train 0.02858 | val 1.85200
  Classification -> best τ=0.345 (val F1=0.4237)
  Directional -> Accuracy: 0.5735, MCC: 0.2303, F1: 0.5085

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.34459 | val 0.83184
  Epoch 020 - train 0.11792 | val 1.83924
  Epoch 024 - train 0.05287 | val 2.06004
  Classification -> best τ=0.595 (val F1=0.3438)
  Directional -> Accuracy: 0.6136, MCC: 0.2817, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.38639 | val 0.99671
  Epoch 020 - train 0.08123 | val 1.90207
  Epoch 021 - train 0.05799 | val 1.99640
  Classification -> best τ=0.520 (val F1=0.2413)
  Directional -> Accuracy: 0.5000, MCC: 0.0283, F1: 0.5672

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.28470 | val 1.35060
  Epoch 020 - train 0.03024 | val 2.78504
  Epoch 021 - train 0.02292 | val 2.96566
  Classification -> best τ=0.445 (val F1=0.2143)
  Directional -> Accuracy: 0.6042, MCC: -0.1130, F1: 0.7532

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47155 | val 1.47820
  Epoch 020 - train 0.14092 | val 2.31673
  Epoch 021 - train 0.11189 | val 2.63234
  Classification -> best τ=0.455 (val F1=0.2928)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.29127 | val 1.61498
  Epoch 020 - train 0.03197 | val 3.68845
  Epoch 021 - train 0.02744 | val 3.86415
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.49057 | val 1.05013
  Epoch 020 - train 0.19310 | val 1.82045
  Epoch 024 - train 0.08398 | val 2.35638
  Classification -> best τ=0.275 (val F1=0.2727)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57824 | val 0.85197
  Epoch 020 - train 0.07423 | val 2.11451
  Epoch 022 - train 0.04239 | val 2.46485
  Classification -> best τ=0.490 (val F1=0.2626)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5556

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.34568 | val 1.35555
  Epoch 020 - train 0.06679 | val 2.58596
  Epoch 021 - train 0.05215 | val 2.74371
  Classification -> best τ=0.615 (val F1=0.4000)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.36662 | val 1.08801
  Epoch 020 - train 0.06212 | val 2.11106
  Epoch 021 - train 0.05236 | val 2.10057
  Classification -> best τ=0.440 (val F1=0.2037)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43569 | val 0.98906
  Epoch 020 - train 0.07133 | val 2.57484
  Epoch 021 - train 0.05184 | val 2.61298
  Classification -> best τ=0.430 (val F1=0.2405)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.33525 | val 2.27354
  Epoch 020 - train 0.02124 | val 4.84351
  Epoch 021 - train 0.01561 | val 5.10959
  Classification -> best τ=0.610 (val F1=0.4216)
  Directional -> Accuracy: 0.4828, MCC: -0.0231, F1: 0.5588

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44052 | val 1.19818
  Epoch 020 - train 0.11679 | val 1.43930
  Epoch 021 - train 0.09326 | val 1.46324
  Classification -> best τ=0.380 (val F1=0.1828)

[I 2026-02-19 01:02:34,686] Trial 23 finished with value: 0.26024579978677836 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.005158284767236719, 'weight_decay': 6.989492668172096e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.4755641303617, 'early_stopping_min_delta': 0.0020768444917826077}. Best is trial 10 with value: 0.2688998415931245.

  Classification -> best τ=0.420 (val F1=0.1088)
  Directional -> Accuracy: 0.4839, MCC: 0.0000, F1: 0.6522

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26024579978677836
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45906 | val 0.94289
  Epoch 020 - train 0.13998 | val 1.85829
  Epoch 023 - train 0.09009 | val 2.15042
  Classification -> best τ=0.615 (val F1=0.2346)
  Directional -> Accuracy: 0.5949, MCC: 0.2228, F1: 0.1579

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46157 | val 1.30288
  Epoch 020 - train 0.17575 | val 1.20501
  Epoch 021 - train 0.14963 | val 1.28349
  Classification -> best τ=0.430 (val F1=0.1690)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.41840 | val 0.81138
  Epoch 020 - train 0.15747 | val 1.47325
  Epoch 021 - train 0.13860 | val 1.53859
  Classification -> best τ=0.545 (val F1=0.3077)
  Directional -> Accuracy: 0.4898, MCC: 0.0334, F1: 0.2424

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.54790 | val 0.94878
  Epoch 020 - train 0.26271 | val 1.51439
  Epoch 021 - train 0.23810 | val 1.56963
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43272 | val 0.69486
  Epoch 020 - train 0.12626 | val 0.96599
  Epoch 025 - train 0.06280 | val 1.20572
  Classification -> best τ=0.620 (val F1=0.3984)
  Directional -> Accuracy: 0.6981, MCC: 0.4125, F1: 0.6800

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41603 | val 1.03206
  Epoch 020 - train 0.21162 | val 2.67351
  Epoch 021 - train 0.19624 | val 2.32693
  Classification -> best τ=0.485 (val F1=0.2032)
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.6333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.47582 | val 0.99588
  Epoch 020 - train 0.07976 | val 1.36231
  Epoch 025 - train 0.03526 | val 1.63187
  Classification -> best τ=0.475 (val F1=0.2582)
  Directional -> Accuracy: 0.4930, MCC: 0.0611, F1: 0.5385

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.36179 | val 1.32295
  Epoch 020 - train 0.14907 | val 3.85064
  Epoch 021 - train 0.13609 | val 3.81291
  Classification -> best τ=0.550 (val F1=0.1217)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.41271 | val 0.73370
  Epoch 020 - train 0.06354 | val 1.81767
  Epoch 028 - train 0.01932 | val 1.95463
  Classification -> best τ=0.590 (val F1=0.4391)
  Directional -> Accuracy: 0.5349, MCC: -0.0989, F1: 0.1667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.39263 | val 0.93995
  Epoch 020 - train 0.05633 | val 1.05827
  Epoch 029 - train 0.00505 | val 1.51798
  Classification -> best τ=0.435 (val F1=0.2957)
  Directional -> Accuracy: 0.4028, MCC: -0.1888, F1: 0.3768

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45726 | val 1.22854
  Epoch 020 - train 0.07841 | val 1.60266
  Epoch 021 - train 0.06724 | val 1.65170
  Classification -> best τ=0.475 (val F1=0.2250)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42284 | val 1.46330
  Epoch 020 - train 0.11618 | val 2.37790
  Epoch 021 - train 0.10159 | val 2.66472
  Classification -> best τ=0.530 (val F1=0.1680)
  Directional -> Accuracy: 0.5333, MCC: 0.1111, F1: 0.2222

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41516 | val 1.07618
  Epoch 020 - train 0.20183 | val 1.76605
  Epoch 021 - train 0.18605 | val 1.63704
  Classification -> best τ=0.465 (val F1=0.4005)
  Directional -> Accuracy: 0.4889, MCC: 0.1410, F1: 0.6462

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.47535 | val 1.48102
  Epoch 020 - train 0.18893 | val 1.70011
  Epoch 021 - train 0.17812 | val 1.73014
  Classification -> best τ=0.505 (val F1=0.3883)
  Directional -> Accuracy: 0.5079, MCC: 0.0261, F1: 0.5974

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47702 | val 1.14293
  Epoch 020 - train 0.13732 | val 1.99025
  Epoch 022 - train 0.10481 | val 2.33302
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46692 | val 1.12627
  Epoch 020 - train 0.16907 | val 1.91507
  Epoch 021 - train 0.17403 | val 2.02984
  Classification -> best τ=0.490 (val F1=0.1694)
  Directional -> Accuracy: 0.5278, MCC: 0.0230, F1: 0.6222

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42563 | val 1.50485
  Epoch 020 - train 0.12323 | val 3.22424
  Epoch 021 - train 0.11336 | val 3.36169
  Classification -> best τ=0.545 (val F1=0.1411)
  Directional -> Accuracy: 0.5902, MCC: -0.1040, F1: 0.7423

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46182 | val 1.22571
  Epoch 020 - train 0.18367 | val 2.22263
  Epoch 021 - train 0.16880 | val 2.31188
  Classification -> best τ=0.465 (val F1=0.1462)
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.39516 | val 1.04533
  Epoch 020 - train 0.12164 | val 2.32113
  Epoch 021 - train 0.12228 | val 2.38178
  Classification -> best τ=0.440 (val F1=0.2656)
  Directional -> Accuracy: 0.5522, MCC: 0.1811, F1: 0.5000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57105 | val 0.96129
  Epoch 020 - train 0.19996 | val 1.35914
  Epoch 023 - train 0.15244 | val 1.39740
  Classification -> best τ=0.495 (val F1=0.3714)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.32486 | val 1.71470
  Epoch 020 - train 0.11423 | val 3.19285
  Epoch 021 - train 0.11037 | val 3.37773
  Classification -> best τ=0.545 (val F1=0.1809)
  Directional -> Accuracy: 0.3800, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42733 | val 1.10868
  Epoch 020 - train 0.12578 | val 2.05399
  Epoch 021 - train 0.10551 | val 2.10316
  Classification -> best τ=0.460 (val F1=0.1302)
  Directional -> Accuracy: 0.5588, MCC: 0.1231, F1: 0.6154

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43520 | val 1.01681
  Epoch 020 - train 0.09756 | val 2.04952
  Epoch 021 - train 0.07511 | val 2.10881
  Classification -> best τ=0.555 (val F1=0.2719)
  Directional -> Accuracy: 0.5333, MCC: 0.1393, F1: 0.4815

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.45800 | val 0.68638
  Epoch 020 - train 0.13094 | val 1.10056
  Epoch 026 - train 0.04523 | val 1.39531
  Classification -> best τ=0.495 (val F1=0.2593)
  Directional -> Accuracy: 0.4706, MCC: -0.0647, F1: 0.6250

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.43986 | val 0.93790
  Epoch 020 - train 0.13999 | val 1.47397
  Epoch 024 - train 0.08920 | val 1.75922
  Classification -> best τ=0.490 (val F1=0.5153)
  Directional -> Accuracy: 0.5517, MCC: 0.1685, F1: 0.4583

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.25922 | val 0.86359
  Epoch 020 - train 0.05729 | val 1.55279
  Epoch 021 - train 0.05402 | val 1.59559
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.38829 | val 0.74350
  Epoch 020 - train 0.04943 | val 2.22561
  Epoch 028 - train 0.01136 | val 2.71249
  Classification -> best τ=0.620 (val F1=0.3014)
  Directional -> Accuracy: 0.5556, MCC: 0.1273, F1: 0.5833

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46858 | val 1.72543
  Epoch 020 - train 0.22356 | val 2.28401
  Epoch 021 - train 0.21276 | val 2.38473
  Classification -> best τ=0.480 (val F1=0.1212)
  Directional -> Accuracy: 0.5424, MCC: 0.2190, F1: 0.3721

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.38436 | val 0.64943
  Epoch 020 - train 0.13039 | val 1.33774
  Epoch 030 - train 0.03089 | val 1.84901
  Epoch 031 - train 0.03504 | val 1.93086
  Classification -> best τ=0.415 (val F1=0.5030)
  Directional -> Accuracy: 0.5455, MCC: 0.1596, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44925 | val 1.00901
  Epoch 020 - train 0.14669 | val 1.92371
  Epoch 024 - train 0.09700 | val 2.31787
  Classification -> best τ=0.530 (val F1=0.3488)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5306

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.40730 | val 0.86387
  Epoch 020 - train 0.15287 | val 1.75451
  Epoch 021 - train 0.13469 | val 1.76648
  Classification -> best τ=0.480 (val F1=0.2265)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.36811 | val 1.22451
  Epoch 020 - train 0.07077 | val 2.26592
  Epoch 023 - train 0.04161 | val 2.58080
  Classification -> best τ=0.455 (val F1=0.3367)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41621 | val 0.84735
  Epoch 020 - train 0.10089 | val 1.43664
  Epoch 022 - train 0.06938 | val 1.55394
  Classification -> best τ=0.435 (val F1=0.3135)
  Directional -> Accuracy: 0.5200, MCC: 0.0898, F1: 0.4545

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.37778 | val 0.95674
  Epoch 020 - train 0.18646 | val 1.95411
  Epoch 021 - train 0.17019 | val 1.85785
  Classification -> best τ=0.520 (val F1=0.1457)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38652 | val 1.18143
  Epoch 020 - train 0.11079 | val 2.13916
  Epoch 021 - train 0.09930 | val 2.16211
  Classification -> best τ=0.515 (val F1=0.2828)
  Directional -> Accuracy: 0.5000, MCC: 0.0958, F1: 0.6230

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.45241 | val 0.84239
  Epoch 020 - train 0.15168 | val 1.22226
  Epoch 023 - train 0.09752 | val 1.32964
  Classification -> best τ=0.370 (val F1=0.2607)
  Directional -> Accuracy: 0.4783, MCC: 0.1249, F1: 0.2500

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.36135 | val 0.83409
  Epoch 020 - train 0.13355 | val 1.17334
  Epoch 023 - train 0.09586 | val 1.34571
  Classification -> best τ=0.500 (val F1=0.3241)
  Directional -> Accuracy: 0.7111, MCC: 0.4356, F1: 0.6829

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42102 | val 1.57725
  Epoch 020 - train 0.16720 | val 2.14391
  Epoch 021 - train 0.14147 | val 2.19772
  Classification -> best τ=0.445 (val F1=0.1985)
  Directional -> Accuracy: 0.4915, MCC: 0.1248, F1: 0.6512

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42615 | val 0.98617
  Epoch 020 - train 0.10644 | val 2.09444
  Epoch 021 - train 0.09430 | val 2.03723
  Classification -> best τ=0.465 (val F1=0.2373)
  Directional -> Accuracy: 0.5714, MCC: -0.1642, F1: 0.7273

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38734 | val 0.96148
  Epoch 020 - train 0.11802 | val 1.77660
  Epoch 024 - train 0.05756 | val 2.03587
  Classification -> best τ=0.340 (val F1=0.2180)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.41752 | val 0.84129
  Epoch 020 - train 0.16150 | val 1.80612
  Epoch 023 - train 0.11790 | val 2.10398
  Classification -> best τ=0.430 (val F1=0.2548)
  Directional -> Accuracy: 0.5366, MCC: 0.0837, F1: 0.6667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47368 | val 1.73352
  Epoch 020 - train 0.14451 | val 3.08463
  Epoch 021 - train 0.11618 | val 3.28018
  Classification -> best τ=0.515 (val F1=0.1596)
  Directional -> Accuracy: 0.5455, MCC: 0.0901, F1: 0.5679

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.46782 | val 1.37110
  Epoch 020 - train 0.21173 | val 2.93970
  Epoch 021 - train 0.18815 | val 2.49031
  Classification -> best τ=0.510 (val F1=0.1789)
  Directional -> Accuracy: 0.5510, MCC: 0.1138, F1: 0.6071

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.33225 | val 1.64063
  Epoch 020 - train 0.13712 | val 3.29720
  Epoch 021 - train 0.13027 | val 3.43813
  Classification -> best τ=0.600 (val F1=0.4385)
  Directional -> Accuracy: 0.4043, MCC: -0.1218, F1: 0.1250

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.37890 | val 0.81709
  Epoch 020 - train 0.15014 | val 1.10051
  Epoch 021 - train 0.13515 | val 1.24312
  Classification -> best τ=0.720 (val F1=0.1425)
  Directional -> Accuracy: 0.3810, MCC: 0.1164, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43572 | val 0.93987
  Epoch 020 - train 0.09671 | val 2.25724
  Epoch 022 - train 0.07160 | val 2.51574
  Classification -> best τ=0.460 (val F1=0.2200)
  Directional -> Accuracy: 0.3966, MCC: -0.1955, F1: 0.3860

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40227 | val 1.86998
  Epoch 020 - train 0.09054 | val 2.92519
  Epoch 021 - train 0.07326 | val 3.14975
  Classification -> best τ=0.600 (val F1=0.3610)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.47076 | val 0.79034
  Epoch 020 - train 0.12571 | val 1.13123
  Epoch 023 - train 0.08810 | val 1.22050

[I 2026-02-19 01:03:52,965] Trial 24 finished with value: 0.24527185334744542 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.0028966767913925716, 'weight_decay': 1.0309219919572375e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.4228915140240554, 'early_stopping_min_delta': 0.0022433657116561773}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 020 - train 0.15622 | val 1.09077
  Epoch 021 - train 0.14633 | val 1.16726
  Classification -> best τ=0.490 (val F1=0.3459)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24527185334744542
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54143 | val 0.79305
  Epoch 020 - train 0.42712 | val 1.07405
  Epoch 022 - train 0.41721 | val 1.10606
  Classification -> best τ=0.490 (val F1=0.2262)
  Directional -> Accuracy: 0.6076, MCC: 0.1867, F1: 0.3673

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50648 | val 0.77636
  Epoch 020 - train 0.41373 | val 0.89749
  Epoch 024 - train 0.38579 | val 0.89900
  Classification -> best τ=0.425 (val F1=0.3007)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.53997 | val 0.74438
  Epoch 020 - train 0.42767 | val 0.83490
  Epoch 022 - train 0.40737 | val 0.87900
  Classification -> best τ=0.480 (val F1=0.2737)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56144 | val 0.92739
  Epoch 020 - train 0.48306 | val 1.57803
  Epoch 021 - train 0.46335 | val 1.42630
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51876 | val 0.63327
  Epoch 020 - train 0.39157 | val 0.74814
  Epoch 027 - train 0.32806 | val 0.79161
  Classification -> best τ=0.555 (val F1=0.3984)
  Directional -> Accuracy: 0.5472, MCC: 0.1003, F1: 0.5385

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51769 | val 0.79592
  Epoch 020 - train 0.44264 | val 0.94101
  Epoch 021 - train 0.43588 | val 0.94266
  Classification -> best τ=0.520 (val F1=0.1419)
  Directional -> Accuracy: 0.5610, MCC: 0.0983, F1: 0.3077

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57390 | val 0.70017
  Epoch 020 - train 0.45342 | val 0.81944
  Epoch 024 - train 0.42534 | val 0.86236
  Classification -> best τ=0.455 (val F1=0.3057)
  Directional -> Accuracy: 0.4930, MCC: 0.0891, F1: 0.5610

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52898 | val 0.89007
  Epoch 020 - train 0.44931 | val 1.32838
  Epoch 021 - train 0.44238 | val 1.35925
  Classification -> best τ=0.495 (val F1=0.1754)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.53684 | val 0.69440
  Epoch 020 - train 0.39179 | val 0.81062
  Epoch 024 - train 0.35408 | val 0.81596
  Classification -> best τ=0.545 (val F1=0.2998)
  Directional -> Accuracy: 0.6744, MCC: 0.3387, F1: 0.3000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51563 | val 0.67337
  Epoch 020 - train 0.39057 | val 1.03967
  Epoch 030 - train 0.25575 | val 0.74945
  Epoch 033 - train 0.23334 | val 0.79127
  Classification -> best τ=0.535 (val F1=0.2932)
  Directional -> Accuracy: 0.5417, MCC: 0.0244, F1: 0.3529

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.54696 | val 0.79235
  Epoch 020 - train 0.43766 | val 1.23766
  Epoch 021 - train 0.42479 | val 1.29112
  Classification -> best τ=0.485 (val F1=0.0026)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49924 | val 0.97083
  Epoch 020 - train 0.38846 | val 1.60211
  Epoch 021 - train 0.38946 | val 1.65174
  Classification -> best τ=0.485 (val F1=0.1018)
  Directional -> Accuracy: 0.6833, MCC: 0.3719, F1: 0.7077

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54056 | val 0.71526
  Epoch 020 - train 0.45505 | val 0.86749
  Epoch 021 - train 0.44819 | val 0.92390
  Classification -> best τ=0.535 (val F1=0.1443)
  Directional -> Accuracy: 0.5778, MCC: 0.1494, F1: 0.5366

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55157 | val 0.72498
  Epoch 020 - train 0.44135 | val 1.05306
  Epoch 022 - train 0.42930 | val 1.03748
  Classification -> best τ=0.485 (val F1=0.3883)
  Directional -> Accuracy: 0.5397, MCC: 0.0796, F1: 0.5397

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51503 | val 0.68811
  Epoch 020 - train 0.34606 | val 1.03235
  Epoch 030 - train 0.24763 | val 1.38350
  Classification -> best τ=0.375 (val F1=0.2132)
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.51507 | val 0.81705
  Epoch 020 - train 0.40977 | val 1.00602
  Epoch 022 - train 0.38843 | val 1.04260
  Classification -> best τ=0.440 (val F1=0.2650)
  Directional -> Accuracy: 0.5556, MCC: 0.0872, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55226 | val 1.13571
  Epoch 020 - train 0.46152 | val 1.77113
  Epoch 021 - train 0.45142 | val 1.78311
  Classification -> best τ=0.530 (val F1=0.1189)
  Directional -> Accuracy: 0.3934, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.53217 | val 1.10226
  Epoch 020 - train 0.45152 | val 1.53630
  Epoch 021 - train 0.44399 | val 1.57289
  Classification -> best τ=0.495 (val F1=0.1020)
  Directional -> Accuracy: 0.5256, MCC: -0.0569, F1: 0.6476

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.51869 | val 0.72814
  Epoch 020 - train 0.36650 | val 1.01904
  Epoch 026 - train 0.32373 | val 1.12540
  Classification -> best τ=0.370 (val F1=0.2615)
  Directional -> Accuracy: 0.4776, MCC: 0.1001, F1: 0.2857

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.52885 | val 0.74331
  Epoch 020 - train 0.42348 | val 0.92188
  Epoch 024 - train 0.40755 | val 0.92691
  Classification -> best τ=0.350 (val F1=0.2654)
  Directional -> Accuracy: 0.5455, MCC: 0.1491, F1: 0.4444

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46664 | val 0.88161
  Epoch 020 - train 0.36687 | val 1.36840
  Epoch 021 - train 0.37177 | val 1.46650
  Classification -> best τ=0.475 (val F1=0.2850)
  Directional -> Accuracy: 0.5600, MCC: 0.0056, F1: 0.6765

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53016 | val 0.90261
  Epoch 020 - train 0.42888 | val 1.11485
  Epoch 021 - train 0.41668 | val 1.14296
  Classification -> best τ=0.435 (val F1=0.2148)
  Directional -> Accuracy: 0.4706, MCC: -0.1250, F1: 0.6327

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.53961 | val 0.69994
  Epoch 020 - train 0.38355 | val 1.04429
  Epoch 026 - train 0.33776 | val 1.20571
  Classification -> best τ=0.605 (val F1=0.3729)
  Directional -> Accuracy: 0.5500, MCC: 0.0904, F1: 0.5970

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.51664 | val 0.88620
  Epoch 020 - train 0.39595 | val 1.28268
  Epoch 021 - train 0.39943 | val 1.47882
  Classification -> best τ=0.445 (val F1=0.1689)
  Directional -> Accuracy: 0.5735, MCC: 0.1918, F1: 0.6588

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53200 | val 0.66784
  Epoch 020 - train 0.36045 | val 0.86508
  Epoch 027 - train 0.30077 | val 0.96510
  Classification -> best τ=0.535 (val F1=0.4865)
  Directional -> Accuracy: 0.5517, MCC: 0.1685, F1: 0.4583

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46038 | val 0.71131
  Epoch 020 - train 0.37094 | val 0.74667
  Epoch 021 - train 0.36476 | val 0.75602
  Classification -> best τ=0.485 (val F1=0.2337)
  Directional -> Accuracy: 0.5510, MCC: 0.0152, F1: 0.2667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.52509 | val 0.67547
  Epoch 020 - train 0.38805 | val 0.67349
  Epoch 030 - train 0.26197 | val 0.98014
  Epoch 033 - train 0.23746 | val 1.08490
  Classification -> best τ=0.595 (val F1=0.4015)
  Directional -> Accuracy: 0.5333, MCC: 0.0546, F1: 0.5882

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.52508 | val 1.07547
  Epoch 020 - train 0.42548 | val 1.64870
  Epoch 021 - train 0.42423 | val 1.70770
  Classification -> best τ=0.470 (val F1=0.1776)
  Directional -> Accuracy: 0.5593, MCC: 0.2816, F1: 0.3810

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50185 | val 0.72558
  Epoch 020 - train 0.36256 | val 0.65301
  Epoch 030 - train 0.25962 | val 0.83361
  Epoch 036 - train 0.22602 | val 1.01460
  Classification -> best τ=0.515 (val F1=0.4382)
  Directional -> Accuracy: 0.5909, MCC: 0.1775, F1: 0.6250

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48791 | val 0.74887
  Epoch 020 - train 0.39370 | val 0.96695
  Epoch 021 - train 0.38450 | val 0.96107
  Classification -> best τ=0.520 (val F1=0.2202)
  Directional -> Accuracy: 0.5435, MCC: 0.0913, F1: 0.6038

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56160 | val 0.71023
  Epoch 020 - train 0.46116 | val 0.92619
  Epoch 021 - train 0.46251 | val 0.95526
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49787 | val 0.70606
  Epoch 020 - train 0.34714 | val 1.07188
  Epoch 026 - train 0.29733 | val 1.20255
  Classification -> best τ=0.305 (val F1=0.2826)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.53614 | val 0.72441
  Epoch 020 - train 0.39096 | val 0.99843
  Epoch 024 - train 0.35451 | val 1.10110
  Classification -> best τ=0.440 (val F1=0.2693)
  Directional -> Accuracy: 0.5067, MCC: 0.0492, F1: 0.4638

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.50404 | val 0.71781
  Epoch 020 - train 0.41905 | val 0.81191
  Epoch 021 - train 0.41690 | val 0.83869
  Classification -> best τ=0.485 (val F1=0.1459)
  Directional -> Accuracy: 0.5122, MCC: 0.0868, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52033 | val 0.77343
  Epoch 020 - train 0.43407 | val 0.88147
  Epoch 021 - train 0.42829 | val 0.88296
  Classification -> best τ=0.580 (val F1=0.2081)
  Directional -> Accuracy: 0.5217, MCC: 0.0436, F1: 0.5000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.55881 | val 0.70205
  Epoch 020 - train 0.42854 | val 0.81663
  Epoch 022 - train 0.40880 | val 0.85776
  Classification -> best τ=0.460 (val F1=0.2070)
  Directional -> Accuracy: 0.5507, MCC: 0.0913, F1: 0.5974

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50881 | val 0.71380
  Epoch 020 - train 0.41516 | val 0.73628
  Epoch 021 - train 0.40732 | val 0.73587
  Classification -> best τ=0.505 (val F1=0.1967)
  Directional -> Accuracy: 0.6667, MCC: 0.3550, F1: 0.6154

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.50695 | val 0.92275
  Epoch 020 - train 0.40239 | val 1.36345
  Epoch 021 - train 0.39722 | val 1.41062
  Classification -> best τ=0.500 (val F1=0.1234)
  Directional -> Accuracy: 0.4746, MCC: -0.0452, F1: 0.4918

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51377 | val 0.94468
  Epoch 020 - train 0.40322 | val 1.28886
  Epoch 021 - train 0.39409 | val 1.28318
  Classification -> best τ=0.485 (val F1=0.2373)
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.53055 | val 0.70989
  Epoch 020 - train 0.39825 | val 1.14915
  Epoch 025 - train 0.36623 | val 1.35340
  Classification -> best τ=0.390 (val F1=0.2180)
  Directional -> Accuracy: 0.4048, MCC: 0.1040, F1: 0.5098

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.53604 | val 0.70039
  Epoch 020 - train 0.37896 | val 0.84587
  Epoch 029 - train 0.31935 | val 1.05707
  Classification -> best τ=0.430 (val F1=0.3194)
  Directional -> Accuracy: 0.4878, MCC: -0.0655, F1: 0.6316

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54345 | val 1.06673
  Epoch 020 - train 0.42298 | val 2.19562
  Epoch 021 - train 0.42005 | val 2.21274
  Classification -> best τ=0.480 (val F1=0.0901)
  Directional -> Accuracy: 0.5195, MCC: 0.1162, F1: 0.6783

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50981 | val 0.98041
  Epoch 020 - train 0.43486 | val 1.61052
  Epoch 021 - train 0.42258 | val 1.71146
  Classification -> best τ=0.490 (val F1=0.1401)
  Directional -> Accuracy: 0.4694, MCC: -0.0589, F1: 0.5000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48446 | val 0.84920
  Epoch 020 - train 0.38057 | val 1.27330
  Epoch 021 - train 0.38162 | val 1.33529
  Classification -> best τ=0.515 (val F1=0.2717)
  Directional -> Accuracy: 0.4894, MCC: -0.0183, F1: 0.5200

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56387 | val 0.92659
  Epoch 020 - train 0.48759 | val 0.94880
  Epoch 021 - train 0.48184 | val 0.93364
  Classification -> best τ=0.560 (val F1=0.1425)
  Directional -> Accuracy: 0.5000, MCC: 0.2350, F1: 0.5714

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.55789 | val 0.80907
  Epoch 020 - train 0.45895 | val 0.87552
  Epoch 021 - train 0.45514 | val 0.87860
  Classification -> best τ=0.460 (val F1=0.1805)
  Directional -> Accuracy: 0.5517, MCC: 0.0874, F1: 0.6061

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.52604 | val 0.89251
  Epoch 020 - train 0.43436 | val 1.08316
  Epoch 021 - train 0.41867 | val 1.04666
  Classification -> best τ=0.525 (val F1=0.3078)
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591


[I 2026-02-19 01:05:13,945] Trial 25 finished with value: 0.2228943951546062 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.0007922838018708121, 'weight_decay': 6.762645892609172e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.5565734888435674, 'early_stopping_min_delta': 0.0037956585965330824}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 020 - train 0.46915 | val 1.03509
  Epoch 021 - train 0.45345 | val 0.96988
  Classification -> best τ=0.525 (val F1=0.2193)
  Directional -> Accuracy: 0.4603, MCC: -0.0728, F1: 0.6136

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2228943951546062
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41745 | val 0.84805
  Epoch 020 - train 0.12508 | val 2.44452
  Epoch 024 - train 0.14002 | val 3.05951
  Classification -> best τ=0.460 (val F1=0.2264)
  Directional -> Accuracy: 0.4615, MCC: 0.0127, F1: 0.6038

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.37282 | val 0.70873
  Epoch 020 - train 0.15812 | val 1.13749
  Epoch 021 - train 0.15047 | val 1.26807
  Classification -> best τ=0.535 (val F1=0.2346)
  Directional -> Accuracy: 0.5745, MCC: 0.1140, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.41788 | val 0.75603
  Epoch 020 - train 0.11415 | val 1.46914
  Epoch 027 - train 0.03744 | val 1.97405
  Classification -> best τ=0.585 (val F1=0.3100)
  Directional -> Accuracy: 0.4375, MCC: -0.1080, F1: 0.0690

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.48363 | val 0.89507
  Epoch 020 - train 0.19313 | val 2.12164
  Epoch 021 - train 0.16574 | val 3.53770
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44079 | val 0.78188
  Epoch 020 - train 0.10675 | val 1.31124
  Epoch 022 - train 0.10853 | val 1.44721
  Classification -> best τ=0.520 (val F1=0.3719)
  Directional -> Accuracy: 0.6154, MCC: 0.2829, F1: 0.5455

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36497 | val 1.37751
  Epoch 020 - train 0.14319 | val 3.79512
  Epoch 021 - train 0.10512 | val 4.17710
  Classification -> best τ=0.535 (val F1=0.2511)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45219 | val 0.94185
  Epoch 020 - train 0.17071 | val 1.36702
  Epoch 026 - train 0.07183 | val 1.83697
  Classification -> best τ=0.380 (val F1=0.3514)
  Directional -> Accuracy: 0.3857, MCC: -0.1152, F1: 0.5474

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.28298 | val 1.37873
  Epoch 020 - train 0.06673 | val 3.92313
  Epoch 021 - train 0.06149 | val 3.32766
  Classification -> best τ=0.590 (val F1=0.5292)
  Directional -> Accuracy: 0.4444, MCC: 0.0159, F1: 0.5763

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.34081 | val 0.78245
  Epoch 020 - train 0.08620 | val 2.14316
  Epoch 021 - train 0.08238 | val 2.66680
  Classification -> best τ=0.515 (val F1=0.3786)
  Directional -> Accuracy: 0.5952, MCC: 0.3131, F1: 0.6222

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43256 | val 1.06692
  Epoch 020 - train 0.17312 | val 1.54606
  Epoch 026 - train 0.07785 | val 1.56825
  Classification -> best τ=0.445 (val F1=0.2601)
  Directional -> Accuracy: 0.4507, MCC: -0.0839, F1: 0.4507

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.35521 | val 0.74339
  Epoch 020 - train 0.10278 | val 1.13721
  Epoch 025 - train 0.03227 | val 1.95427
  Classification -> best τ=0.500 (val F1=0.2622)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.39536 | val 2.03082
  Epoch 020 - train 0.10376 | val 5.09804
  Epoch 021 - train 0.05991 | val 6.18725
  Classification -> best τ=0.415 (val F1=0.1891)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38218 | val 0.89544
  Epoch 020 - train 0.16853 | val 2.24030
  Epoch 023 - train 0.14554 | val 2.78612
  Classification -> best τ=0.515 (val F1=0.1793)
  Directional -> Accuracy: 0.5227, MCC: -0.0392, F1: 0.1600

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.41462 | val 1.09963
  Epoch 020 - train 0.18739 | val 3.16023
  Epoch 021 - train 0.16404 | val 2.99558
  Classification -> best τ=0.515 (val F1=0.3380)
  Directional -> Accuracy: 0.5806, MCC: 0.1981, F1: 0.6750

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.31611 | val 0.87704
  Epoch 020 - train 0.12224 | val 2.40302
  Epoch 024 - train 0.04681 | val 2.67349
  Classification -> best τ=0.455 (val F1=0.1937)
  Directional -> Accuracy: 0.4340, MCC: -0.1197, F1: 0.5312

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.40964 | val 0.82046
  Epoch 020 - train 0.14146 | val 1.57220
  Epoch 022 - train 0.12356 | val 1.60909
  Classification -> best τ=0.375 (val F1=0.3552)
  Directional -> Accuracy: 0.5352, MCC: 0.0000, F1: 0.6972

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.34587 | val 1.56425
  Epoch 020 - train 0.10019 | val 2.64496
  Epoch 021 - train 0.10221 | val 3.95481
  Classification -> best τ=0.445 (val F1=0.0657)
  Directional -> Accuracy: 0.6000, MCC: -0.1026, F1: 0.7500

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.46563 | val 1.53284
  Epoch 020 - train 0.18987 | val 3.52836
  Epoch 021 - train 0.20215 | val 3.46629
  Classification -> best τ=0.505 (val F1=0.1378)
  Directional -> Accuracy: 0.5065, MCC: 0.0714, F1: 0.5000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.41624 | val 1.26216
  Epoch 020 - train 0.15145 | val 2.94267
  Epoch 022 - train 0.09283 | val 3.36087
  Classification -> best τ=0.490 (val F1=0.2033)
  Directional -> Accuracy: 0.4394, MCC: 0.1471, F1: 0.0976

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47239 | val 1.04984
  Epoch 020 - train 0.26981 | val 1.56588
  Epoch 023 - train 0.22208 | val 2.38251
  Classification -> best τ=0.545 (val F1=0.3357)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.34353 | val 0.99823
  Epoch 020 - train 0.10374 | val 2.78432
  Epoch 021 - train 0.06964 | val 2.94977
  Classification -> best τ=0.515 (val F1=0.2193)
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.46502 | val 1.04187
  Epoch 020 - train 0.21736 | val 1.69160
  Epoch 021 - train 0.16296 | val 1.82822
  Classification -> best τ=0.445 (val F1=0.2070)
  Directional -> Accuracy: 0.4925, MCC: -0.0526, F1: 0.6458

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.40103 | val 0.76039
  Epoch 020 - train 0.11020 | val 1.32727
  Epoch 023 - train 0.08913 | val 1.59408
  Classification -> best τ=0.645 (val F1=0.3228)
  Directional -> Accuracy: 0.4576, MCC: -0.0278, F1: 0.3846

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42839 | val 1.18531
  Epoch 020 - train 0.20665 | val 4.49852
  Epoch 022 - train 0.16662 | val 5.04438
  Classification -> best τ=0.545 (val F1=0.1326)
  Directional -> Accuracy: 0.5224, MCC: 0.0404, F1: 0.4839

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.44243 | val 0.88023
  Epoch 020 - train 0.16291 | val 2.07830
  Epoch 025 - train 0.07328 | val 2.41743
  Classification -> best τ=0.510 (val F1=0.2981)
  Directional -> Accuracy: 0.4386, MCC: -0.1216, F1: 0.4667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.19992 | val 0.78827
  Epoch 020 - train 0.04758 | val 1.21108
  Epoch 021 - train 0.03626 | val 1.26711
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.35280 | val 0.74681
  Epoch 020 - train 0.10545 | val 1.85588
  Epoch 021 - train 0.07964 | val 1.91166
  Classification -> best τ=0.515 (val F1=0.3366)
  Directional -> Accuracy: 0.6136, MCC: 0.1390, F1: 0.7385

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.46087 | val 1.14946
  Epoch 020 - train 0.22244 | val 2.33734
  Epoch 021 - train 0.15181 | val 2.46849
  Classification -> best τ=0.475 (val F1=0.0148)
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.35424 | val 0.67478
  Epoch 020 - train 0.11580 | val 1.64668
  Epoch 027 - train 0.03568 | val 3.79294
  Classification -> best τ=0.500 (val F1=0.3901)
  Directional -> Accuracy: 0.5581, MCC: 0.1655, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.31172 | val 1.35497
  Epoch 020 - train 0.12851 | val 2.50210
  Epoch 021 - train 0.10804 | val 2.22176
  Classification -> best τ=0.580 (val F1=0.2874)
  Directional -> Accuracy: 0.5111, MCC: 0.1474, F1: 0.0833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.37069 | val 0.86383
  Epoch 020 - train 0.10719 | val 2.80312
  Epoch 021 - train 0.11198 | val 2.96437
  Classification -> best τ=0.505 (val F1=0.2045)
  Directional -> Accuracy: 0.5111, MCC: -0.0223, F1: 0.6333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.34508 | val 0.97998
  Epoch 020 - train 0.08695 | val 1.98620
  Epoch 024 - train 0.05046 | val 2.60815
  Classification -> best τ=0.430 (val F1=0.3191)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37535 | val 1.49132
  Epoch 020 - train 0.14660 | val 3.49094
  Epoch 022 - train 0.12753 | val 4.19428
  Classification -> best τ=0.460 (val F1=0.2881)
  Directional -> Accuracy: 0.5405, MCC: 0.1500, F1: 0.4688

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.28695 | val 0.75090
  Epoch 020 - train 0.10051 | val 1.36347
  Epoch 021 - train 0.05827 | val 1.31204
  Classification -> best τ=0.465 (val F1=0.2041)
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.31655 | val 0.82655
  Epoch 020 - train 0.09052 | val 2.06983
  Epoch 023 - train 0.06028 | val 2.16937
  Classification -> best τ=0.510 (val F1=0.3669)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.43928 | val 0.83006
  Epoch 020 - train 0.15977 | val 1.24911
  Epoch 021 - train 0.11974 | val 1.25400
  Classification -> best τ=0.490 (val F1=0.2197)
  Directional -> Accuracy: 0.4853, MCC: 0.0577, F1: 0.3636

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.34819 | val 0.68189
  Epoch 020 - train 0.07371 | val 1.31504
  Epoch 028 - train 0.01613 | val 2.00407
  Classification -> best τ=0.565 (val F1=0.3151)
  Directional -> Accuracy: 0.5682, MCC: 0.1400, F1: 0.5128

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.43373 | val 0.91704
  Epoch 020 - train 0.13273 | val 1.60858
  Epoch 021 - train 0.12760 | val 1.85181
  Classification -> best τ=0.595 (val F1=0.2171)
  Directional -> Accuracy: 0.5517, MCC: 0.0774, F1: 0.2778

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.33672 | val 1.25422
  Epoch 020 - train 0.13284 | val 1.74437
  Epoch 021 - train 0.11386 | val 1.80508
  Classification -> best τ=0.470 (val F1=0.1912)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38180 | val 0.75097
  Epoch 020 - train 0.11205 | val 1.82515
  Epoch 025 - train 0.04930 | val 2.74525
  Classification -> best τ=0.440 (val F1=0.2067)
  Directional -> Accuracy: 0.3750, MCC: 0.1175, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.36894 | val 0.86654
  Epoch 020 - train 0.09423 | val 2.42935
  Epoch 021 - train 0.09790 | val 2.49401
  Classification -> best τ=0.350 (val F1=0.2548)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44238 | val 0.97187
  Epoch 020 - train 0.16808 | val 2.44421
  Epoch 021 - train 0.16502 | val 2.63110
  Classification -> best τ=0.465 (val F1=0.2367)
  Directional -> Accuracy: 0.5132, MCC: 0.1155, F1: 0.6726

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.38434 | val 0.74009
  Epoch 020 - train 0.14090 | val 1.73678
  Epoch 021 - train 0.12123 | val 1.49582
  Classification -> best τ=0.490 (val F1=0.1733)
  Directional -> Accuracy: 0.5625, MCC: 0.2046, F1: 0.2759

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.26002 | val 0.91880
  Epoch 020 - train 0.05067 | val 1.85446
  Epoch 021 - train 0.06466 | val 2.01378
  Classification -> best τ=0.460 (val F1=0.2949)
  Directional -> Accuracy: 0.5333, MCC: -0.0598, F1: 0.6866

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.36068 | val 1.50258
  Epoch 020 - train 0.10047 | val 2.84973
  Epoch 021 - train 0.09441 | val 2.55382
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.39402 | val 0.79088
  Epoch 020 - train 0.14707 | val 2.32222
  Epoch 022 - train 0.10547 | val 2.50376
  Classification -> best τ=0.510 (val F1=0.2178)
  Directional -> Accuracy: 0.3684, MCC: -0.2662, F1: 0.1429

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.38421 | val 0.90627
  Epoch 020 - train 0.08124 | val 3.42280
  Epoch 023 - train 0.03721 | val 4.23657
  Classification -> best τ=0.645 (val F1=0.4260)
  Directional -> Accuracy: 0.5000, MCC: 0.0024, F1: 0.5085

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.40089 | val 1.38119
  Epoch 020 - train 0.14773 | val 2.12833

[I 2026-02-19 01:06:53,917] Trial 26 finished with value: 0.24284072100938395 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 0.00275245309095435, 'weight_decay': 3.165391023283808e-07, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.8824867953858662, 'early_stopping_min_delta': 0.0054807114085950485}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 020 - train 0.12387 | val 1.37598
  Epoch 021 - train 0.10662 | val 1.56230
  Classification -> best τ=0.545 (val F1=0.1765)
  Directional -> Accuracy: 0.4516, MCC: -0.1285, F1: 0.2609

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24284072100938395
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47919 | val 0.73258
  Epoch 020 - train 0.21164 | val 1.10899
  Epoch 022 - train 0.14025 | val 1.14390
  Classification -> best τ=0.545 (val F1=0.2950)
  Directional -> Accuracy: 0.5256, MCC: 0.0597, F1: 0.5195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47729 | val 0.73213
  Epoch 020 - train 0.16117 | val 1.20282
  Classification -> best τ=0.395 (val F1=0.2156)
  Directional -> Accuracy: 0.5319, MCC: -0.0153, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.50749 | val 0.76771
  Epoch 017 - train 0.33101 | val 1.01657
  Classification -> best τ=0.475 (val F1=0.1758)
  Directional -> Accuracy: 0.5000, MCC: -0.0948, F1: 0.6471

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57061 | val 1.27332
  Epoch 016 - train 0.42378 | val 1.08627
  Classification -> best τ=0.505 (val F1=0.1095)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49647 | val 0.90338
  Epoch 019 - train 0.15740 | val 1.35776
  Classification -> best τ=0.515 (val F1=0.4234)
  Directional -> Accuracy: 0.6923, MCC: 0.3929, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43231 | val 1.67222
  Epoch 017 - train 0.22238 | val 3.43296
  Classification -> best τ=0.485 (val F1=0.2152)
  Directional -> Accuracy: 0.5102, MCC: 0.0236, F1: 0.4783

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.53746 | val 0.94469
  Epoch 018 - train 0.25621 | val 1.25726
  Classification -> best τ=0.505 (val F1=0.2432)
  Directional -> Accuracy: 0.5000, MCC: 0.0479, F1: 0.5070

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.46378 | val 1.68796
  Epoch 016 - train 0.30056 | val 2.92622
  Classification -> best τ=0.550 (val F1=0.3780)
  Directional -> Accuracy: 0.4444, MCC: 0.0481, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43598 | val 0.95742
  Epoch 019 - train 0.13096 | val 1.67460
  Classification -> best τ=0.560 (val F1=0.2821)
  Directional -> Accuracy: 0.5714, MCC: -0.0059, F1: 0.2500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48015 | val 1.08993
  Epoch 017 - train 0.13145 | val 1.21665
  Classification -> best τ=0.430 (val F1=0.2910)
  Directional -> Accuracy: 0.4366, MCC: -0.0576, F1: 0.5556

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43884 | val 1.20449
  Epoch 016 - train 0.19914 | val 1.57468
  Classification -> best τ=0.435 (val F1=0.2622)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43585 | val 1.40781
  Epoch 016 - train 0.17406 | val 2.16149
  Classification -> best τ=0.490 (val F1=0.1424)
  Directional -> Accuracy: 0.5932, MCC: 0.1973, F1: 0.5385

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42983 | val 1.56739
  Epoch 016 - train 0.24229 | val 3.15420
  Classification -> best τ=0.510 (val F1=0.1370)
  Directional -> Accuracy: 0.5227, MCC: -0.0103, F1: 0.2759

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.51620 | val 1.16584
  Epoch 017 - train 0.22823 | val 1.22734
  Classification -> best τ=0.435 (val F1=0.3076)
  Directional -> Accuracy: 0.5484, MCC: 0.1374, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53034 | val 0.74477
  Epoch 020 - train 0.15729 | val 1.19701
  Classification -> best τ=0.440 (val F1=0.2681)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.49423 | val 1.03364
  Epoch 016 - train 0.30752 | val 1.23014
  Classification -> best τ=0.555 (val F1=0.2645)
  Directional -> Accuracy: 0.5493, MCC: 0.0844, F1: 0.6098

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.45177 | val 0.88456
  Epoch 016 - train 0.25729 | val 1.17491
  Classification -> best τ=0.635 (val F1=0.0647)
  Directional -> Accuracy: 0.3833, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55332 | val 1.43312
  Epoch 016 - train 0.38114 | val 1.63151
  Classification -> best τ=0.540 (val F1=0.1936)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.45401 | val 1.04031
  Epoch 018 - train 0.11373 | val 1.97187
  Classification -> best τ=0.505 (val F1=0.3170)
  Directional -> Accuracy: 0.4091, MCC: -0.0327, F1: 0.0488

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49413 | val 0.91223
  Epoch 017 - train 0.29103 | val 1.05469
  Classification -> best τ=0.550 (val F1=0.2355)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.40740 | val 1.43592
  Epoch 016 - train 0.22111 | val 1.66909
  Classification -> best τ=0.525 (val F1=0.2597)
  Directional -> Accuracy: 0.3469, MCC: -0.2450, F1: 0.3333

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.49556 | val 1.19159
  Epoch 016 - train 0.31817 | val 1.28844
  Classification -> best τ=0.420 (val F1=0.2715)
  Directional -> Accuracy: 0.5075, MCC: 0.0084, F1: 0.6118

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.41813 | val 0.87130
  Epoch 016 - train 0.21840 | val 1.16805
  Classification -> best τ=0.565 (val F1=0.1913)
  Directional -> Accuracy: 0.4746, MCC: 0.1025, F1: 0.2439

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54407 | val 0.78933
  Epoch 020 - train 0.42510 | val 1.17512
  Epoch 024 - train 0.16451 | val 1.39758
  Classification -> best τ=0.600 (val F1=0.2715)
  Directional -> Accuracy: 0.4627, MCC: -0.1014, F1: 0.3077

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41791 | val 0.96385
  Epoch 018 - train 0.18939 | val 1.35008
  Classification -> best τ=0.475 (val F1=0.3329)
  Directional -> Accuracy: 0.5263, MCC: 0.1268, F1: 0.4255

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.32317 | val 0.91581
  Epoch 018 - train 0.07441 | val 1.86438
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44307 | val 1.20818
  Epoch 018 - train 0.14086 | val 1.53305
  Classification -> best τ=0.495 (val F1=0.2948)
  Directional -> Accuracy: 0.5227, MCC: -0.0781, F1: 0.6557

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51526 | val 1.36546
  Epoch 016 - train 0.32769 | val 1.94813
  Classification -> best τ=0.450 (val F1=0.1624)
  Directional -> Accuracy: 0.5172, MCC: 0.0025, F1: 0.6000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.45126 | val 0.74469
  Epoch 020 - train 0.17393 | val 1.07495
  Epoch 026 - train 0.06944 | val 1.54004
  Classification -> best τ=0.500 (val F1=0.4606)
  Directional -> Accuracy: 0.5581, MCC: 0.1655, F1: 0.7077

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44419 | val 1.05568
  Epoch 016 - train 0.21854 | val 1.44390
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54997 | val 0.76478
  Epoch 020 - train 0.27194 | val 1.21784
  Epoch 022 - train 0.23301 | val 1.35496
  Classification -> best τ=0.535 (val F1=0.3070)
  Directional -> Accuracy: 0.5333, MCC: 0.1557, F1: 0.3226

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48971 | val 1.02679
  Epoch 020 - train 0.08238 | val 2.23109
  Classification -> best τ=0.680 (val F1=0.2889)
  Directional -> Accuracy: 0.5098, MCC: -0.1333, F1: 0.6753

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.51679 | val 1.07327
  Epoch 017 - train 0.27082 | val 1.25921
  Classification -> best τ=0.440 (val F1=0.3470)
  Directional -> Accuracy: 0.5946, MCC: 0.1805, F1: 0.6341

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.41056 | val 0.94679
  Epoch 016 - train 0.22175 | val 1.27301
  Classification -> best τ=0.510 (val F1=0.2550)
  Directional -> Accuracy: 0.4872, MCC: -0.0109, F1: 0.6154

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.45873 | val 1.22722
  Epoch 016 - train 0.25167 | val 1.73536
  Classification -> best τ=0.420 (val F1=0.2500)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53584 | val 0.79630
  Epoch 016 - train 0.29468 | val 1.10323
  Classification -> best τ=0.455 (val F1=0.1597)
  Directional -> Accuracy: 0.5294, MCC: 0.0729, F1: 0.5429

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43911 | val 1.01501
  Epoch 017 - train 0.18109 | val 1.75943
  Classification -> best τ=0.510 (val F1=0.2615)
  Directional -> Accuracy: 0.6364, MCC: 0.2835, F1: 0.5789

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49021 | val 1.01776
  Epoch 016 - train 0.26959 | val 1.60360
  Classification -> best τ=0.490 (val F1=0.2001)
  Directional -> Accuracy: 0.4310, MCC: -0.1229, F1: 0.4923

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.38390 | val 1.18511
  Epoch 016 - train 0.19334 | val 1.93531
  Classification -> best τ=0.650 (val F1=0.2470)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49523 | val 1.96779
  Epoch 016 - train 0.36995 | val 1.94435
  Classification -> best τ=0.500 (val F1=0.3410)
  Directional -> Accuracy: 0.3000, MCC: -0.3126, F1: 0.4615

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48158 | val 1.08632
  Epoch 016 - train 0.29820 | val 1.49961
  Classification -> best τ=0.430 (val F1=0.2548)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47618 | val 1.11957
  Epoch 017 - train 0.19839 | val 1.92554
  Classification -> best τ=0.350 (val F1=0.3270)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.51226 | val 0.83437
  Epoch 019 - train 0.17726 | val 1.74897
  Classification -> best τ=0.425 (val F1=0.1560)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44407 | val 1.53899
  Epoch 016 - train 0.31036 | val 2.00157
  Classification -> best τ=0.560 (val F1=0.4000)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50463 | val 1.28444
  Epoch 016 - train 0.31460 | val 1.57626
  Classification -> best τ=0.480 (val F1=0.0605)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.48458 | val 1.21571
  Epoch 017 - train 0.24106 | val 1.58430
  Classification -> best τ=0.490 (val F1=0.2382)
  Directional -> Accuracy: 0.5614, MCC: 0.1675, F1: 0.4898

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.50987 | val 1.83616
  Epoch 016 - train 0.21121 | val 2.72312
  Classification -> best τ=0.675 (val F1=0.4332)
  Directional -> Accuracy: 0.5172, MCC: 0.0383, F1: 0.5333

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.50567 | val 1.06794
  Epoch 016 - train 0.28592 | val 1.06416
  Classification -> best τ=0.340 (val F1=0.2054)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42209 | val 1.49101
  Epoch 017 - train 0.18527 | val 1.56862
  Classification -> best τ=0.545 (val F1=0.2874)
  Directional -> Accuracy: 0.5088, MCC: 0.0033, F1: 0.6667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.54315 | val 1.37347

[I 2026-02-19 01:08:25,684] Trial 27 finished with value: 0.24601338020666497 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.005422842520907323, 'weight_decay': 8.749114009330935e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.8256640993897152, 'early_stopping_min_delta': 0.0012235610050413516}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 016 - train 0.30135 | val 1.06256
  Classification -> best τ=0.465 (val F1=0.2148)
  Directional -> Accuracy: 0.4194, MCC: -0.1849, F1: 0.2800

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24601338020666497
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'stance_label', 'stance_score']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64282 | val 0.83605
  Epoch 011 - train 0.64436 | val 0.84094
  Classification -> best τ=0.525 (val F1=0.1637)
  Directional -> Accuracy: 0.5263, MCC: 0.0910, F1: 0.5714

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63085 | val 0.80070
  Epoch 015 - train 0.63245 | val 0.84430
  Classification -> best τ=0.430 (val F1=0.2285)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66474 | val 0.65451
  Epoch 019 - train 0.65702 | val 0.65425
  Classification -> best τ=0.465 (val F1=0.4104)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65733 | val 0.73051
  Epoch 012 - train 0.64887 | val 0.73061
  Classification -> best τ=0.515 (val F1=0.1269)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63565 | val 0.86190
  Epoch 014 - train 0.60802 | val 0.96464
  Classification -> best τ=0.570 (val F1=0.4751)
  Directional -> Accuracy: 0.5000, MCC: 0.0415, F1: 0.2424

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64930 | val 0.68773
  Epoch 015 - train 0.62642 | val 0.69417
  Classification -> best τ=0.520 (val F1=0.1722)
  Directional -> Accuracy: 0.5435, MCC: 0.0754, F1: 0.3636

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66194 | val 0.77870
  Epoch 013 - train 0.65435 | val 0.78963
  Classification -> best τ=0.520 (val F1=0.2009)
  Directional -> Accuracy: 0.5000, MCC: 0.0719, F1: 0.5278

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65674 | val 0.82788
  Epoch 011 - train 0.65201 | val 0.85469
  Classification -> best τ=0.510 (val F1=0.1657)
  Directional -> Accuracy: 0.5476, MCC: -0.1353, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63654 | val 0.83910
  Epoch 011 - train 0.63984 | val 0.84954
  Classification -> best τ=0.520 (val F1=0.0618)
  Directional -> Accuracy: 0.6042, MCC: 0.1917, F1: 0.5366

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.64517 | val 0.73103
  Epoch 013 - train 0.64261 | val 0.73829
  Classification -> best τ=0.485 (val F1=0.1950)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65966 | val 0.70344
  Epoch 011 - train 0.66436 | val 0.70276
  Classification -> best τ=0.475 (val F1=0.3075)
  Directional -> Accuracy: 0.4694, MCC: -0.0152, F1: 0.5517

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67553 | val 0.69641
  Epoch 011 - train 0.68046 | val 0.69808
  Classification -> best τ=0.540 (val F1=0.1500)
  Directional -> Accuracy: 0.3860, MCC: -0.3027, F1: 0.5333

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61549 | val 0.82705
  Epoch 011 - train 0.61108 | val 0.84284
  Classification -> best τ=0.480 (val F1=0.1754)
  Directional -> Accuracy: 0.4762, MCC: 0.0083, F1: 0.5769

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66632 | val 0.63233
  Epoch 020 - train 0.64754 | val 0.63963
  Classification -> best τ=0.395 (val F1=0.3477)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6341

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64897 | val 0.83715
  Epoch 011 - train 0.64769 | val 0.84660
  Classification -> best τ=0.505 (val F1=0.1229)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65660 | val 0.73074
  Epoch 011 - train 0.65634 | val 0.72909
  Classification -> best τ=0.490 (val F1=0.2155)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65677 | val 1.22283
  Epoch 011 - train 0.65987 | val 1.26798
  Classification -> best τ=0.550 (val F1=0.1842)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65812 | val 0.83562
  Epoch 011 - train 0.64745 | val 0.83648
  Classification -> best τ=0.530 (val F1=0.0164)
  Directional -> Accuracy: 0.4400, MCC: 0.1667, F1: 0.1250

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66182 | val 0.70192
  Epoch 013 - train 0.64501 | val 0.70761
  Classification -> best τ=0.480 (val F1=0.2711)
  Directional -> Accuracy: 0.4844, MCC: 0.1062, F1: 0.2979

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64391 | val 0.84897
  Epoch 013 - train 0.64215 | val 0.88953
  Classification -> best τ=0.465 (val F1=0.2333)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65887 | val 0.77116
  Epoch 011 - train 0.67111 | val 0.76533
  Classification -> best τ=0.525 (val F1=0.0471)
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67932 | val 0.71633
  Epoch 011 - train 0.67978 | val 0.71594
  Classification -> best τ=0.490 (val F1=0.0230)
  Directional -> Accuracy: 0.5692, MCC: 0.1436, F1: 0.6410

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66489 | val 0.68749
  Epoch 017 - train 0.65320 | val 0.69641
  Classification -> best τ=0.550 (val F1=0.2721)
  Directional -> Accuracy: 0.5439, MCC: 0.2218, F1: 0.3810

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65173 | val 0.77074
  Epoch 011 - train 0.65546 | val 0.79176
  Classification -> best τ=0.510 (val F1=0.1565)
  Directional -> Accuracy: 0.5385, MCC: 0.0619, F1: 0.3478

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64442 | val 0.66763
  Epoch 019 - train 0.60952 | val 0.68873
  Classification -> best τ=0.645 (val F1=0.3472)
  Directional -> Accuracy: 0.4727, MCC: 0.0199, F1: 0.2162

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.64410 | val 0.73338
  Epoch 011 - train 0.63560 | val 0.75231
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67635 | val 1.15445
  Epoch 011 - train 0.66583 | val 1.16732
  Classification -> best τ=0.475 (val F1=0.0694)
  Directional -> Accuracy: 0.5476, MCC: 0.0962, F1: 0.5778

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64039 | val 0.67912
  Epoch 015 - train 0.64799 | val 0.69039
  Classification -> best τ=0.500 (val F1=0.2203)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65723 | val 0.74642
  Epoch 011 - train 0.64884 | val 0.76697
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66480 | val 0.67521
  Epoch 019 - train 0.65258 | val 0.68250
  Classification -> best τ=0.575 (val F1=0.4594)
  Directional -> Accuracy: 0.4762, MCC: -0.0550, F1: 0.4211

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66800 | val 0.70563
  Epoch 016 - train 0.65721 | val 0.73148
  Classification -> best τ=0.475 (val F1=0.2357)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64796 | val 0.70095
  Epoch 014 - train 0.64377 | val 0.70391
  Classification -> best τ=0.475 (val F1=0.2498)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65659 | val 0.69296
  Epoch 020 - train 0.64383 | val 0.68155
  Classification -> best τ=0.520 (val F1=0.3145)
  Directional -> Accuracy: 0.5417, MCC: 0.1682, F1: 0.4211

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.64723 | val 0.93547
  Epoch 011 - train 0.64788 | val 0.94992
  Classification -> best τ=0.545 (val F1=0.2603)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66250 | val 0.71699
  Epoch 014 - train 0.65171 | val 0.73389
  Classification -> best τ=0.325 (val F1=0.3603)
  Directional -> Accuracy: 0.6212, MCC: 0.2364, F1: 0.6575

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66733 | val 0.69430
  Epoch 020 - train 0.63525 | val 0.69526
  Classification -> best τ=0.375 (val F1=0.1715)
  Directional -> Accuracy: 0.6429, MCC: 0.2919, F1: 0.6341

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63488 | val 0.69309
  Epoch 015 - train 0.61768 | val 0.71381
  Classification -> best τ=0.465 (val F1=0.2382)
  Directional -> Accuracy: 0.4821, MCC: -0.0555, F1: 0.3830

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65854 | val 0.69802
  Epoch 015 - train 0.65199 | val 0.71701
  Classification -> best τ=0.480 (val F1=0.3679)
  Directional -> Accuracy: 0.3913, MCC: -0.1022, F1: 0.2222

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.64865 | val 0.64889
  Epoch 020 - train 0.61005 | val 0.62700
  Classification -> best τ=0.330 (val F1=0.4556)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64529 | val 0.78192
  Epoch 011 - train 0.64578 | val 0.78241
  Classification -> best τ=0.500 (val F1=0.1669)
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67022 | val 0.73811
  Epoch 011 - train 0.65808 | val 0.73172
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66433 | val 0.68608
  Epoch 011 - train 0.66154 | val 0.68581
  Classification -> best τ=0.470 (val F1=0.2041)
  Directional -> Accuracy: 0.3810, MCC: -0.1936, F1: 0.2353

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64233 | val 0.73917
  Epoch 011 - train 0.64358 | val 0.75000
  Classification -> best τ=0.495 (val F1=0.0684)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67828 | val 0.73248
  Epoch 011 - train 0.68345 | val 0.73895
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64081 | val 0.86029
  Epoch 011 - train 0.63154 | val 0.89822
  Classification -> best τ=0.520 (val F1=0.2491)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.66234 | val 0.73119
  Epoch 011 - train 0.65220 | val 0.74784
  Classification -> best τ=0.535 (val F1=0.1409)
  Directional -> Accuracy: 0.5849, MCC: 0.1704, F1: 0.6333

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63287 | val 1.33446
  Epoch 011 - train 0.63125 | val 1.34578
  Classification -> best τ=0.470 (val F1=0.0150)
  Directional -> Accuracy: 0.4909, MCC: -0.1839, F1: 0.6585

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65818 | val 0.99477
  Epoch 011 - train 0.65217 | val 0.99939

[I 2026-02-19 01:09:58,840] Trial 28 finished with value: 0.19411693515775885 and parameters: {'feature_set': 'stance', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.0001072792368437294, 'weight_decay': 5.665837973688964e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.0646840395160664, 'early_stopping_min_delta': 0.0025420392528229443}. Best is trial 10 with value: 0.2688998415931245.

  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.19411693515775885
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63629 | val 0.70203
  Epoch 020 - train 0.59984 | val 0.67459
  Epoch 030 - train 0.54570 | val 0.68501
  Epoch 039 - train 0.50650 | val 0.71491
  Classification -> best τ=0.305 (val F1=0.2143)
  Directional -> Accuracy: 0.4868, MCC: 0.1824, F1: 0.6355

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62742 | val 0.70457
  Epoch 020 - train 0.60164 | val 0.73372
  Epoch 021 - train 0.59444 | val 0.73598
  Classification -> best τ=0.420 (val F1=0.2670)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65902 | val 0.70008
  Epoch 020 - train 0.62867 | val 0.71013
  Epoch 021 - train 0.62236 | val 0.71122
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64218 | val 0.82559
  Epoch 020 - train 0.62897 | val 0.88062
  Epoch 021 - train 0.62930 | val 0.88650
  Classification -> best τ=0.450 (val F1=0.2025)
  Directional -> Accuracy: 0.5135, MCC: 0.2204, F1: 0.1818

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64194 | val 0.68543
  Epoch 020 - train 0.60411 | val 0.70195
  Epoch 025 - train 0.58442 | val 0.73190
  Classification -> best τ=0.570 (val F1=0.3529)
  Directional -> Accuracy: 0.5800, MCC: 0.1748, F1: 0.5333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.64164 | val 0.70278
  Epoch 020 - train 0.61835 | val 0.70039
  Epoch 021 - train 0.60234 | val 0.70069
  Classification -> best τ=0.500 (val F1=0.0358)
  Directional -> Accuracy: 0.5217, MCC: 0.0169, F1: 0.2143

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65775 | val 0.68631
  Epoch 020 - train 0.62346 | val 0.70759
  Epoch 027 - train 0.60918 | val 0.71696
  Classification -> best τ=0.450 (val F1=0.2823)
  Directional -> Accuracy: 0.5441, MCC: 0.1437, F1: 0.5507

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65931 | val 0.75821
  Epoch 020 - train 0.60384 | val 0.75371
  Epoch 030 - train 0.57170 | val 0.84950
  Epoch 035 - train 0.56783 | val 0.86244
  Classification -> best τ=0.530 (val F1=0.1418)
  Directional -> Accuracy: 0.4524, MCC: -0.0446, F1: 0.5106

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64214 | val 0.68615
  Epoch 020 - train 0.59870 | val 0.68549
  Epoch 030 - train 0.56988 | val 0.69178
  Epoch 033 - train 0.55842 | val 0.69868
  Classification -> best τ=0.555 (val F1=0.2822)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63147 | val 0.68028
  Epoch 020 - train 0.60057 | val 0.67566
  Epoch 030 - train 0.55271 | val 0.68103
  Epoch 040 - train 0.49703 | val 0.69017
  Epoch 042 - train 0.50251 | val 0.69306
  Classification -> best τ=0.500 (val F1=0.2964)
  Directional -> Accuracy: 0.5507, MCC: 0.1004, F1: 0.5079

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63731 | val 0.73851
  Epoch 020 - train 0.62280 | val 0.76138
  Epoch 021 - train 0.61298 | val 0.76289
  Classification -> best τ=0.480 (val F1=0.0479)
  Directional -> Accuracy: 0.5510, MCC: 0.0714, F1: 0.4211

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64585 | val 0.77242
  Epoch 020 - train 0.60552 | val 0.87598
  Epoch 021 - train 0.58953 | val 0.88973
  Classification -> best τ=0.420 (val F1=0.3170)
  Directional -> Accuracy: 0.4912, MCC: -0.0269, F1: 0.5797

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64563 | val 0.87310
  Epoch 020 - train 0.60551 | val 1.02461
  Epoch 021 - train 0.58890 | val 1.02620
  Classification -> best τ=0.470 (val F1=0.0059)
  Directional -> Accuracy: 0.4762, MCC: -0.1249, F1: 0.2143

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66294 | val 0.64204
  Epoch 020 - train 0.61968 | val 0.64042
  Epoch 030 - train 0.56242 | val 0.64370
  Epoch 035 - train 0.53921 | val 0.66064
  Classification -> best τ=0.340 (val F1=0.3011)
  Directional -> Accuracy: 0.5333, MCC: 0.1111, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63037 | val 0.75261
  Epoch 020 - train 0.60156 | val 0.74642
  Epoch 021 - train 0.59746 | val 0.74594
  Classification -> best τ=0.525 (val F1=0.1347)
  Directional -> Accuracy: 0.5098, MCC: 0.0780, F1: 0.5902

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64218 | val 0.68495
  Epoch 020 - train 0.60860 | val 0.69884
  Epoch 027 - train 0.57884 | val 0.72792
  Classification -> best τ=0.455 (val F1=0.3067)
  Directional -> Accuracy: 0.5217, MCC: -0.0022, F1: 0.6452

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63244 | val 0.85354
  Epoch 020 - train 0.61029 | val 1.01709
  Epoch 021 - train 0.61331 | val 1.02404
  Classification -> best τ=0.455 (val F1=0.1336)
  Directional -> Accuracy: 0.6552, MCC: 0.2076, F1: 0.7619

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64772 | val 0.74322
  Epoch 020 - train 0.60342 | val 0.81557
  Epoch 021 - train 0.59830 | val 0.82202
  Classification -> best τ=0.530 (val F1=0.2303)
  Directional -> Accuracy: 0.5733, MCC: -0.0727, F1: 0.7241

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65114 | val 0.67723
  Epoch 020 - train 0.59877 | val 0.71626
  Epoch 029 - train 0.57317 | val 0.78864
  Classification -> best τ=0.560 (val F1=0.2289)
  Directional -> Accuracy: 0.4688, MCC: 0.0966, F1: 0.2273

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65000 | val 0.66870
  Epoch 020 - train 0.62838 | val 0.66825
  Epoch 030 - train 0.58500 | val 0.67364
  Epoch 031 - train 0.58095 | val 0.67613
  Classification -> best τ=0.410 (val F1=0.3121)
  Directional -> Accuracy: 0.5000, MCC: 0.1161, F1: 0.2745

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64728 | val 0.69210
  Epoch 020 - train 0.59136 | val 0.69791
  Epoch 021 - train 0.58721 | val 0.69741
  Classification -> best τ=0.485 (val F1=0.1572)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64857 | val 0.73732
  Epoch 020 - train 0.62308 | val 0.76865
  Epoch 021 - train 0.61060 | val 0.77128
  Classification -> best τ=0.520 (val F1=0.1925)
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63926 | val 0.67005
  Epoch 020 - train 0.61458 | val 0.67454
  Epoch 029 - train 0.57950 | val 0.68781
  Classification -> best τ=0.685 (val F1=0.3749)
  Directional -> Accuracy: 0.4912, MCC: 0.0465, F1: 0.3830

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65519 | val 0.71317
  Epoch 020 - train 0.62903 | val 0.74697
  Epoch 021 - train 0.61285 | val 0.74584
  Classification -> best τ=0.490 (val F1=0.0345)
  Directional -> Accuracy: 0.5538, MCC: 0.1014, F1: 0.3256

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.64667 | val 0.67030
  Epoch 020 - train 0.60574 | val 0.66101
  Epoch 030 - train 0.57898 | val 0.67045
  Epoch 035 - train 0.54375 | val 0.68685
  Classification -> best τ=0.495 (val F1=0.4629)
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66363 | val 0.67696
  Epoch 020 - train 0.60846 | val 0.67895
  Epoch 030 - train 0.57411 | val 0.69380
  Epoch 034 - train 0.56900 | val 0.69313
  Classification -> best τ=0.570 (val F1=0.4594)
  Directional -> Accuracy: 0.6222, MCC: 0.2523, F1: 0.1905

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66534 | val 0.68386
  Epoch 020 - train 0.61405 | val 0.72782
  Epoch 027 - train 0.59693 | val 0.73454
  Classification -> best τ=0.580 (val F1=0.1936)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64864 | val 0.76375
  Epoch 020 - train 0.60871 | val 0.81956
  Epoch 021 - train 0.60485 | val 0.82367
  Classification -> best τ=0.525 (val F1=0.1986)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64791 | val 0.69803
  Epoch 020 - train 0.60485 | val 0.72809
  Epoch 021 - train 0.62082 | val 0.73115
  Classification -> best τ=0.560 (val F1=0.1918)
  Directional -> Accuracy: 0.4500, MCC: -0.0422, F1: 0.2143

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64426 | val 0.70962
  Epoch 020 - train 0.62657 | val 0.76600
  Epoch 021 - train 0.63026 | val 0.77274
  Classification -> best τ=0.505 (val F1=0.2814)
  Directional -> Accuracy: 0.5952, MCC: 0.2132, F1: 0.3704

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64268 | val 0.75802
  Epoch 020 - train 0.61025 | val 0.84714
  Epoch 021 - train 0.60676 | val 0.85132
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65096 | val 0.70105
  Epoch 020 - train 0.60076 | val 0.71340
  Epoch 024 - train 0.60361 | val 0.71529
  Classification -> best τ=0.515 (val F1=0.1423)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64910 | val 0.67327
  Epoch 020 - train 0.62338 | val 0.67494
  Epoch 030 - train 0.58485 | val 0.69144
  Epoch 032 - train 0.57207 | val 0.69755
  Classification -> best τ=0.395 (val F1=0.2905)
  Directional -> Accuracy: 0.5556, MCC: 0.1803, F1: 0.4667

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65249 | val 0.70264
  Epoch 020 - train 0.62470 | val 0.72572
  Epoch 021 - train 0.63033 | val 0.72979
  Classification -> best τ=0.460 (val F1=0.2717)
  Directional -> Accuracy: 0.5581, MCC: 0.1198, F1: 0.5778

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65814 | val 0.69270
  Epoch 020 - train 0.62594 | val 0.72163
  Epoch 021 - train 0.63325 | val 0.72416
  Classification -> best τ=0.500 (val F1=0.2249)
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61698 | val 0.68244
  Epoch 020 - train 0.57920 | val 0.67814
  Epoch 030 - train 0.55410 | val 0.68003
  Epoch 033 - train 0.53765 | val 0.68163
  Classification -> best τ=0.475 (val F1=0.3321)
  Directional -> Accuracy: 0.6190, MCC: 0.2697, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62015 | val 0.67000
  Epoch 020 - train 0.58498 | val 0.68491
  Epoch 026 - train 0.56397 | val 0.69866
  Classification -> best τ=0.480 (val F1=0.2755)
  Directional -> Accuracy: 0.5536, MCC: 0.1474, F1: 0.6154

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64779 | val 0.74896
  Epoch 020 - train 0.60501 | val 0.90065
  Epoch 021 - train 0.59413 | val 0.91121
  Classification -> best τ=0.515 (val F1=0.2024)
  Directional -> Accuracy: 0.5000, MCC: -0.0393, F1: 0.5818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65567 | val 0.68539
  Epoch 020 - train 0.60576 | val 0.67505
  Epoch 030 - train 0.55639 | val 0.66317
  Epoch 040 - train 0.51028 | val 0.65659
  Epoch 050 - train 0.47039 | val 0.64953
  Classification -> best τ=0.480 (val F1=0.3800)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65119 | val 0.68999
  Epoch 020 - train 0.60992 | val 0.69067
  Epoch 030 - train 0.56167 | val 0.71259
  Epoch 032 - train 0.56084 | val 0.71749
  Classification -> best τ=0.565 (val F1=0.2485)
  Directional -> Accuracy: 0.5405, MCC: 0.0878, F1: 0.5750

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61798 | val 0.68082
  Epoch 020 - train 0.58287 | val 0.67490
  Epoch 030 - train 0.55476 | val 0.68159
  Epoch 040 - train 0.48934 | val 0.69425
  Epoch 041 - train 0.51878 | val 0.69290
  Classification -> best τ=0.450 (val F1=0.3051)
  Directional -> Accuracy: 0.5333, MCC: 0.1541, F1: 0.6866

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.64812 | val 0.72929
  Epoch 020 - train 0.61729 | val 0.73109
  Epoch 021 - train 0.61070 | val 0.73036
  Classification -> best τ=0.540 (val F1=0.0765)
  Directional -> Accuracy: 0.4762, MCC: -0.1217, F1: 0.5926

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64829 | val 0.72837
  Epoch 020 - train 0.63602 | val 0.71849
  Epoch 021 - train 0.62978 | val 0.71682
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63963 | val 0.68738
  Epoch 020 - train 0.60513 | val 0.67622
  Epoch 030 - train 0.55044 | val 0.68751
  Epoch 040 - train 0.51028 | val 0.70916
  Classification -> best τ=0.555 (val F1=0.3000)
  Directional -> Accuracy: 0.4000, MCC: -0.1992, F1: 0.4211

[85/88] Processing VZ...

Processing VZ (Technology)...

[I 2026-02-19 01:10:34,244] Trial 29 finished with value: 0.21891146194944977 and parameters: {'feature_set': 'emotion', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.0004335655005914231, 'weight_decay': 1.666113926896173e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.44229294092553, 'early_stopping_min_delta': 0.0018884730544964261}. Best is trial 10 with value: 0.2688998415931245.

  Classification -> best τ=0.455 (val F1=0.1138)
  Directional -> Accuracy: 0.4500, MCC: -0.1223, F1: 0.6024

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21891146194944977
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68731 | val 0.69639
  Epoch 020 - train 0.66604 | val 0.72633
  Classification -> best τ=0.425 (val F1=0.1903)
  Directional -> Accuracy: 0.6133, MCC: 0.2802, F1: 0.6588

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69387 | val 0.68106
  Epoch 020 - train 0.63905 | val 0.73635
  Classification -> best τ=0.420 (val F1=0.2775)
  Directional -> Accuracy: 0.6591, MCC: 0.2847, F1: 0.7692

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68022 | val 0.67399
  Epoch 020 - train 0.66376 | val 0.68885
  Classification -> best τ=0.515 (val F1=0.3162)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67382 | val 0.89704
  Epoch 020 - train 0.66165 | val 0.95716
  Classification -> best τ=0.480 (val F1=0.1614)
  Directional -> Accuracy: 0.4658, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.66559 | val 0.66796
  Epoch 020 - train 0.64839 | val 0.65723
  Classification -> best τ=0.490 (val F1=0.2735)
  Directional -> Accuracy: 0.5714, MCC: 0.1433, F1: 0.5714

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66477 | val 0.70354
  Epoch 020 - train 0.64750 | val 0.72037
  Classification -> best τ=0.475 (val F1=0.2139)
  Directional -> Accuracy: 0.4889, MCC: -0.0285, F1: 0.4103

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68748 | val 0.68255
  Epoch 020 - train 0.66829 | val 0.68758
  Classification -> best τ=0.540 (val F1=0.2926)
  Directional -> Accuracy: 0.5224, MCC: 0.1209, F1: 0.5556

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69271 | val 0.72087
  Epoch 020 - train 0.63594 | val 0.79321
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65638 | val 0.69352
  Epoch 020 - train 0.64832 | val 0.70740
  Classification -> best τ=0.500 (val F1=0.3000)
  Directional -> Accuracy: 0.3191, MCC: -0.3484, F1: 0.3600

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66491 | val 0.67765
  Epoch 020 - train 0.64800 | val 0.67930
  Classification -> best τ=0.510 (val F1=0.2601)
  Directional -> Accuracy: 0.5000, MCC: 0.0132, F1: 0.4848

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67315 | val 0.71218
  Epoch 020 - train 0.65158 | val 0.72796
  Classification -> best τ=0.485 (val F1=0.2046)
  Directional -> Accuracy: 0.4583, MCC: -0.0252, F1: 0.6061

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66092 | val 0.75504
  Epoch 020 - train 0.65960 | val 0.85757
  Classification -> best τ=0.560 (val F1=0.1192)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63475 | val 0.96107
  Epoch 020 - train 0.63229 | val 1.42727
  Classification -> best τ=0.445 (val F1=0.2891)
  Directional -> Accuracy: 0.5306, MCC: 0.0617, F1: 0.5306

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67378 | val 0.64043
  Epoch 020 - train 0.66106 | val 0.65900
  Classification -> best τ=0.355 (val F1=0.3210)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67201 | val 0.70727
  Epoch 020 - train 0.64960 | val 0.73146
  Classification -> best τ=0.450 (val F1=0.2135)
  Directional -> Accuracy: 0.5200, MCC: 0.1041, F1: 0.5862

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67020 | val 0.75345
  Epoch 020 - train 0.64198 | val 0.78356
  Classification -> best τ=0.510 (val F1=0.1522)
  Directional -> Accuracy: 0.5147, MCC: -0.0398, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67877 | val 0.80855
  Epoch 020 - train 0.65248 | val 0.96069
  Classification -> best τ=0.490 (val F1=0.1132)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69943 | val 0.80118
  Epoch 020 - train 0.68268 | val 0.76860
  Classification -> best τ=0.445 (val F1=0.1716)
  Directional -> Accuracy: 0.5405, MCC: 0.0774, F1: 0.5854

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67268 | val 0.68826
  Epoch 020 - train 0.64550 | val 0.67786
  Classification -> best τ=0.560 (val F1=0.3191)
  Directional -> Accuracy: 0.4603, MCC: 0.1268, F1: 0.1905

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67016 | val 0.68311
  Epoch 020 - train 0.65313 | val 0.68591
  Classification -> best τ=0.460 (val F1=0.2302)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67632 | val 0.69640
  Epoch 020 - train 0.66361 | val 0.70169
  Classification -> best τ=0.585 (val F1=0.1427)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67652 | val 0.73285
  Epoch 020 - train 0.66667 | val 0.73608
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66265 | val 0.71249
  Epoch 020 - train 0.64030 | val 0.72784
  Classification -> best τ=0.600 (val F1=0.3062)
  Directional -> Accuracy: 0.5357, MCC: 0.2154, F1: 0.3810

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67520 | val 0.69762
  Epoch 020 - train 0.66836 | val 0.70856
  Classification -> best τ=0.425 (val F1=0.2083)
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67315 | val 0.66736
  Epoch 020 - train 0.67843 | val 0.65353
  Classification -> best τ=0.470 (val F1=0.5110)
  Directional -> Accuracy: 0.4630, MCC: -0.0210, F1: 0.1212

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65918 | val 0.69354
  Epoch 020 - train 0.65810 | val 0.70820
  Classification -> best τ=0.510 (val F1=0.0929)
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65799 | val 0.69723
  Epoch 020 - train 0.64559 | val 0.69939
  Classification -> best τ=0.520 (val F1=0.2645)
  Directional -> Accuracy: 0.5306, MCC: 0.0209, F1: 0.6102

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.68442 | val 0.68834
  Epoch 020 - train 0.67055 | val 0.69777
  Classification -> best τ=0.475 (val F1=0.0042)
  Directional -> Accuracy: 0.4909, MCC: -0.0671, F1: 0.6000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.65526 | val 0.70314
  Epoch 020 - train 0.66604 | val 0.71645
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68407 | val 0.71199
  Epoch 020 - train 0.64806 | val 0.73451
  Classification -> best τ=0.525 (val F1=0.3418)
  Directional -> Accuracy: 0.5122, MCC: 0.0238, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.67084 | val 0.75831
  Epoch 020 - train 0.65268 | val 0.94159
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66291 | val 0.69861
  Epoch 020 - train 0.64569 | val 0.71732
  Classification -> best τ=0.525 (val F1=0.2382)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.67268 | val 0.64865
  Epoch 020 - train 0.64766 | val 0.64274
  Classification -> best τ=0.470 (val F1=0.3206)
  Directional -> Accuracy: 0.5352, MCC: 0.1239, F1: 0.4762

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67178 | val 0.74354
  Epoch 020 - train 0.66752 | val 0.75188
  Classification -> best τ=0.525 (val F1=0.0036)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67213 | val 0.70488
  Epoch 020 - train 0.65143 | val 0.72781
  Classification -> best τ=0.470 (val F1=0.3488)
  Directional -> Accuracy: 0.5692, MCC: 0.1889, F1: 0.5333

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67024 | val 0.69157
  Epoch 020 - train 0.61927 | val 0.73902
  Classification -> best τ=0.465 (val F1=0.2582)
  Directional -> Accuracy: 0.6000, MCC: 0.2727, F1: 0.4667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64518 | val 0.70324
  Epoch 020 - train 0.62023 | val 0.70990
  Classification -> best τ=0.535 (val F1=0.1633)
  Directional -> Accuracy: 0.4909, MCC: -0.0067, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67149 | val 0.69546
  Epoch 020 - train 0.65166 | val 0.79466
  Classification -> best τ=0.495 (val F1=0.2030)
  Directional -> Accuracy: 0.3556, MCC: -0.1935, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65756 | val 0.67938
  Epoch 020 - train 0.66241 | val 0.65093
  Classification -> best τ=0.560 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65732 | val 0.70715
  Epoch 020 - train 0.64873 | val 0.71879
  Classification -> best τ=0.485 (val F1=0.1237)
  Directional -> Accuracy: 0.5616, MCC: 0.1626, F1: 0.6596

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67741 | val 0.68874
  Epoch 020 - train 0.64972 | val 0.69471
  Classification -> best τ=0.480 (val F1=0.3536)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65549 | val 0.68469
  Epoch 020 - train 0.62780 | val 0.68397
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5854, MCC: 0.0000, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66464 | val 0.70515
  Epoch 020 - train 0.66236 | val 0.72589
  Classification -> best τ=0.510 (val F1=0.0608)
  Directional -> Accuracy: 0.5652, MCC: -0.0069, F1: 0.2857

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68223 | val 0.74976
  Epoch 020 - train 0.67296 | val 0.77268
  Classification -> best τ=0.480 (val F1=0.1066)
  Directional -> Accuracy: 0.6481, MCC: 0.2774, F1: 0.7246

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65756 | val 0.82418
  Epoch 020 - train 0.64993 | val 0.94399
  Classification -> best τ=0.525 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65910 | val 0.66923
  Epoch 020 - train 0.65918 | val 0.66505
  Classification -> best τ=0.655 (val F1=0.3246)
  Directional -> Accuracy: 0.5577, MCC: 0.1957, F1: 0.6849

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66814 | val 0.72022
  Epoch 020 - train 0.65484 | val 0.75180
  Classification -> best τ=0.505 (val F1=0.2397)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67284 | val 0.68539

[I 2026-02-19 01:12:38,401] Trial 30 finished with value: 0.2073358984864652 and parameters: {'feature_set': 'sentinment', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.6000000000000001, 'batch_size': 64, 'learning_rate': 0.00021476314544075168, 'weight_decay': 2.5527006183463317e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.4033762827794065, 'early_stopping_min_delta': 0.0006984227642822312}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 020 - train 0.65303 | val 0.86123
  Classification -> best τ=0.430 (val F1=0.2378)
  Directional -> Accuracy: 0.4068, MCC: -0.2299, F1: 0.2222

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2073358984864652
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45554 | val 1.13356
  Epoch 020 - train 0.15553 | val 1.00137
  Epoch 025 - train 0.05597 | val 1.52016
  Classification -> best τ=0.705 (val F1=0.2453)
  Directional -> Accuracy: 0.5974, MCC: 0.1904, F1: 0.3111

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.34584 | val 0.90275
  Epoch 020 - train 0.07922 | val 1.49034
  Epoch 023 - train 0.02868 | val 1.71276
  Classification -> best τ=0.410 (val F1=0.2495)
  Directional -> Accuracy: 0.5652, MCC: 0.0406, F1: 0.7059

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.38794 | val 0.99279
  Epoch 020 - train 0.01939 | val 2.06438
  Epoch 021 - train 0.01235 | val 2.10079
  Classification -> best τ=0.520 (val F1=0.2845)
  Directional -> Accuracy: 0.4468, MCC: -0.1340, F1: 0.5357

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.55114 | val 1.60850
  Epoch 020 - train 0.14678 | val 2.24066
  Epoch 022 - train 0.16041 | val 2.38269
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41948 | val 0.83840
  Epoch 020 - train 0.07936 | val 2.90628
  Epoch 026 - train 0.02478 | val 4.07413
  Classification -> best τ=0.515 (val F1=0.3463)
  Directional -> Accuracy: 0.4706, MCC: -0.1124, F1: 0.5970

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43226 | val 0.93151
  Epoch 020 - train 0.10557 | val 1.58301
  Epoch 021 - train 0.08291 | val 1.52456
  Classification -> best τ=0.520 (val F1=0.2265)
  Directional -> Accuracy: 0.4681, MCC: -0.1506, F1: 0.6377

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.51113 | val 1.40570
  Epoch 020 - train 0.06558 | val 2.04595
  Epoch 022 - train 0.05114 | val 2.43326
  Classification -> best τ=0.460 (val F1=0.2448)
  Directional -> Accuracy: 0.3768, MCC: -0.2091, F1: 0.5474

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.38662 | val 1.47366
  Epoch 020 - train 0.04009 | val 3.57315
  Epoch 022 - train 0.02565 | val 3.74400
  Classification -> best τ=0.490 (val F1=0.3325)
  Directional -> Accuracy: 0.4545, MCC: 0.1023, F1: 0.5862

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.37409 | val 1.43562
  Epoch 020 - train 0.08689 | val 2.57023
  Epoch 022 - train 0.05808 | val 2.50432
  Classification -> best τ=0.600 (val F1=0.2265)
  Directional -> Accuracy: 0.6327, MCC: 0.2887, F1: 0.3571

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59964 | val 0.69715
  Epoch 020 - train 0.10603 | val 1.13528
  Epoch 024 - train 0.03145 | val 1.54694
  Classification -> best τ=0.460 (val F1=0.2237)
  Directional -> Accuracy: 0.4286, MCC: -0.0849, F1: 0.5122

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41819 | val 1.76720
  Epoch 020 - train 0.06920 | val 2.35637
  Epoch 021 - train 0.04974 | val 2.38926
  Classification -> best τ=0.550 (val F1=0.1750)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.52190 | val 1.17210
  Epoch 020 - train 0.11518 | val 3.02063
  Epoch 021 - train 0.09999 | val 3.24054
  Classification -> best τ=0.710 (val F1=0.2453)
  Directional -> Accuracy: 0.6207, MCC: 0.2894, F1: 0.4762

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45642 | val 0.95069
  Epoch 020 - train 0.10661 | val 2.04085
  Epoch 024 - train 0.03447 | val 2.51037
  Classification -> best τ=0.585 (val F1=0.1188)
  Directional -> Accuracy: 0.4419, MCC: -0.1997, F1: 0.2000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44856 | val 0.70298
  Epoch 020 - train 0.07210 | val 0.99283
  Epoch 024 - train 0.02044 | val 1.24998
  Classification -> best τ=0.310 (val F1=0.4128)
  Directional -> Accuracy: 0.5246, MCC: 0.0468, F1: 0.6133

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52259 | val 1.03703
  Epoch 020 - train 0.11123 | val 2.85286
  Epoch 021 - train 0.09599 | val 3.04483
  Classification -> best τ=0.425 (val F1=0.2731)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46328 | val 1.11970
  Epoch 020 - train 0.09284 | val 1.97193
  Epoch 022 - train 0.04969 | val 2.22310
  Classification -> best τ=0.325 (val F1=0.3360)
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.53735 | val 1.30036
  Epoch 020 - train 0.12498 | val 2.32878
  Epoch 021 - train 0.12552 | val 2.46028
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.55573 | val 1.03392
  Epoch 020 - train 0.18260 | val 2.51479
  Epoch 022 - train 0.10465 | val 2.95174
  Classification -> best τ=0.425 (val F1=0.0936)
  Directional -> Accuracy: 0.5526, MCC: 0.0638, F1: 0.6304

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.49319 | val 0.79339
  Epoch 020 - train 0.08779 | val 1.33355
  Epoch 023 - train 0.03265 | val 1.71441
  Classification -> best τ=0.645 (val F1=0.2899)
  Directional -> Accuracy: 0.4462, MCC: 0.0531, F1: 0.1818

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.54585 | val 0.82533
  Epoch 020 - train 0.22252 | val 1.63991
  Epoch 021 - train 0.26583 | val 1.65330
  Classification -> best τ=0.520 (val F1=0.1859)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.40078 | val 1.41269
  Epoch 020 - train 0.07952 | val 2.76075
  Epoch 021 - train 0.06763 | val 2.87429
  Classification -> best τ=0.470 (val F1=0.3143)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57256 | val 1.12581
  Epoch 020 - train 0.11673 | val 2.18382
  Epoch 021 - train 0.07655 | val 2.29246
  Classification -> best τ=0.490 (val F1=0.2490)
  Directional -> Accuracy: 0.4394, MCC: -0.1319, F1: 0.3019

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45982 | val 0.91124
  Epoch 020 - train 0.06308 | val 1.44178
  Epoch 024 - train 0.01551 | val 1.80027
  Classification -> best τ=0.645 (val F1=0.3579)
  Directional -> Accuracy: 0.6034, MCC: 0.2245, F1: 0.6102

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56368 | val 1.31709
  Epoch 020 - train 0.17556 | val 1.08917
  Epoch 030 - train 0.00925 | val 1.73160
  Epoch 032 - train 0.00668 | val 1.85421
  Classification -> best τ=0.485 (val F1=0.3736)
  Directional -> Accuracy: 0.5455, MCC: 0.1290, F1: 0.6154

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.55466 | val 0.81713
  Epoch 020 - train 0.26924 | val 1.58866
  Epoch 026 - train 0.10095 | val 2.38278
  Classification -> best τ=0.660 (val F1=0.3824)
  Directional -> Accuracy: 0.4643, MCC: 0.0136, F1: 0.2105

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.22000 | val 1.16722
  Epoch 020 - train 0.01475 | val 1.92870
  Epoch 021 - train 0.01057 | val 1.99641
  Classification -> best τ=0.445 (val F1=0.2041)
  Directional -> Accuracy: 0.4565, MCC: 0.1307, F1: 0.6154

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.34019 | val 0.71706
  Epoch 020 - train 0.02319 | val 1.33018
  Epoch 021 - train 0.01962 | val 1.41313
  Classification -> best τ=0.570 (val F1=0.1818)
  Directional -> Accuracy: 0.5581, MCC: -0.0137, F1: 0.6984

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45433 | val 1.18569
  Epoch 020 - train 0.19708 | val 2.03003
  Epoch 021 - train 0.18244 | val 2.09959
  Classification -> best τ=0.440 (val F1=0.1099)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.37125 | val 0.81360
  Epoch 020 - train 0.05199 | val 2.33653
  Epoch 024 - train 0.02375 | val 2.49896
  Classification -> best τ=0.475 (val F1=0.3844)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41320 | val 2.20365
  Epoch 020 - train 0.09082 | val 4.57286
  Epoch 021 - train 0.07160 | val 4.58918
  Classification -> best τ=0.555 (val F1=0.1288)
  Directional -> Accuracy: 0.5116, MCC: 0.0261, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41815 | val 1.12983
  Epoch 020 - train 0.08616 | val 3.02235
  Epoch 021 - train 0.05066 | val 3.40962
  Classification -> best τ=0.450 (val F1=0.2324)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.39269 | val 0.84042
  Epoch 020 - train 0.08891 | val 2.29736
  Epoch 025 - train 0.02848 | val 2.56756
  Classification -> best τ=0.745 (val F1=0.2870)
  Directional -> Accuracy: 0.4400, MCC: -0.2235, F1: 0.5882

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.45555 | val 0.93293
  Epoch 020 - train 0.06134 | val 1.88088
  Epoch 023 - train 0.02496 | val 2.09522
  Classification -> best τ=0.320 (val F1=0.2679)
  Directional -> Accuracy: 0.5890, MCC: 0.1847, F1: 0.6053

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.38664 | val 1.11560
  Epoch 020 - train 0.02906 | val 2.46367
  Epoch 022 - train 0.02180 | val 2.55848
  Classification -> best τ=0.485 (val F1=0.2182)
  Directional -> Accuracy: 0.5789, MCC: 0.1857, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.35445 | val 1.25992
  Epoch 020 - train 0.04771 | val 2.76870
  Epoch 021 - train 0.03667 | val 2.98206
  Classification -> best τ=0.680 (val F1=0.3028)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49061 | val 0.78146
  Epoch 020 - train 0.12364 | val 1.64193
  Epoch 021 - train 0.08273 | val 1.67830
  Classification -> best τ=0.505 (val F1=0.1890)
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.31147 | val 1.42782
  Epoch 020 - train 0.12461 | val 2.64538
  Epoch 023 - train 0.07897 | val 2.80191
  Classification -> best τ=0.505 (val F1=0.3780)
  Directional -> Accuracy: 0.6279, MCC: 0.2581, F1: 0.6190

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51947 | val 1.08827
  Epoch 020 - train 0.21466 | val 1.39239
  Epoch 021 - train 0.20483 | val 1.70915
  Classification -> best τ=0.555 (val F1=0.2236)
  Directional -> Accuracy: 0.5614, MCC: 0.1225, F1: 0.2857

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.38894 | val 0.96091
  Epoch 020 - train 0.03210 | val 2.53522
  Epoch 021 - train 0.02349 | val 2.72132
  Classification -> best τ=0.400 (val F1=0.1661)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39426 | val 0.95804
  Epoch 020 - train 0.03125 | val 2.18383
  Epoch 024 - train 0.01105 | val 2.44983
  Classification -> best τ=0.525 (val F1=0.3894)
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.32611 | val 1.60398
  Epoch 020 - train 0.07385 | val 4.30801
  Epoch 022 - train 0.05117 | val 4.63726
  Classification -> best τ=0.470 (val F1=0.3223)
  Directional -> Accuracy: 0.4737, MCC: -0.0618, F1: 0.5238

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.49290 | val 1.12369
  Epoch 020 - train 0.12049 | val 2.03327
  Epoch 022 - train 0.09134 | val 2.51362
  Classification -> best τ=0.590 (val F1=0.3289)
  Directional -> Accuracy: 0.4933, MCC: -0.0091, F1: 0.5682

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.52636 | val 0.99235
  Epoch 020 - train 0.05710 | val 2.11324
  Epoch 024 - train 0.01949 | val 2.49132
  Classification -> best τ=0.435 (val F1=0.2699)
  Directional -> Accuracy: 0.5319, MCC: 0.0687, F1: 0.6562

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48534 | val 0.88064
  Epoch 020 - train 0.05201 | val 2.20291
  Epoch 028 - train 0.00417 | val 2.33318
  Classification -> best τ=0.360 (val F1=0.4594)
  Directional -> Accuracy: 0.5455, MCC: -0.0029, F1: 0.6774

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.37686 | val 1.08940
  Epoch 020 - train 0.04107 | val 2.69468
  Epoch 023 - train 0.02053 | val 2.94483
  Classification -> best τ=0.510 (val F1=0.1543)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.46935 | val 1.00142
  Epoch 020 - train 0.04853 | val 3.22007
  Epoch 021 - train 0.03643 | val 3.29368
  Classification -> best τ=0.620 (val F1=0.2077)
  Directional -> Accuracy: 0.3571, MCC: -0.2923, F1: 0.4000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.47307 | val 1.50077
  Epoch 020 - train 0.05079 | val 3.99514
  Epoch 021 - train 0.05274 | val 3.61776
  Classification -> best τ=0.560 (val F1=0.2777)
  Directional -> Accuracy: 0.4561, MCC: -0.1409, F1: 0.6265

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.45699 | val 0.87061
  Epoch 020 - train 0.10682 | val 2.27622
  Epoch 027 - train 0.01781 | val 2.77340

[I 2026-02-19 01:15:31,105] Trial 31 finished with value: 0.24593893855290028 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.007636901108401721, 'weight_decay': 2.2701671594380845e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.479886934839603, 'early_stopping_min_delta': 0.00048657822616037216}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 023 - train 0.05500 | val 2.69424
  Classification -> best τ=0.430 (val F1=0.1734)
  Directional -> Accuracy: 0.4918, MCC: 0.1229, F1: 0.6517

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24593893855290028
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.30314 | val 1.77328
  Epoch 020 - train 0.00671 | val 3.60338
  Epoch 021 - train 0.00498 | val 3.71766
  Classification -> best τ=0.555 (val F1=0.1084)
  Directional -> Accuracy: 0.5455, MCC: 0.0690, F1: 0.4444

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16667 | val 1.36313
  Epoch 020 - train 0.00434 | val 2.50504
  Epoch 021 - train 0.00342 | val 2.54791
  Classification -> best τ=0.465 (val F1=0.0881)
  Directional -> Accuracy: 0.6522, MCC: 0.2923, F1: 0.6923

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.06252 | val 1.57284
  Epoch 020 - train 0.00079 | val 2.75740
  Epoch 025 - train 0.00087 | val 2.80416
  Classification -> best τ=0.230 (val F1=0.3278)
  Directional -> Accuracy: 0.5319, MCC: 0.0290, F1: 0.6562

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.18344 | val 2.61056
  Epoch 020 - train 0.00327 | val 4.72314
  Epoch 021 - train 0.00334 | val 4.81602
  Classification -> best τ=0.445 (val F1=0.2086)
  Directional -> Accuracy: 0.5333, MCC: 0.0657, F1: 0.5570

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12180 | val 1.49325
  Epoch 020 - train 0.00335 | val 3.01941
  Epoch 022 - train 0.00215 | val 3.12659
  Classification -> best τ=0.510 (val F1=0.3725)
  Directional -> Accuracy: 0.5490, MCC: 0.1295, F1: 0.4651

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10995 | val 1.64464
  Epoch 020 - train 0.00195 | val 2.90263
  Epoch 023 - train 0.00160 | val 2.93988
  Classification -> best τ=0.350 (val F1=0.2357)
  Directional -> Accuracy: 0.4894, MCC: -0.0045, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16598 | val 1.14636
  Epoch 020 - train 0.00325 | val 1.94044
  Epoch 022 - train 0.00252 | val 1.99565
  Classification -> best τ=0.520 (val F1=0.3135)
  Directional -> Accuracy: 0.6232, MCC: 0.1702, F1: 0.3810

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.04947 | val 2.86512
  Epoch 020 - train 0.00305 | val 4.34730
  Epoch 021 - train 0.00354 | val 4.51489
  Classification -> best τ=0.465 (val F1=0.1214)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.06312 | val 2.76101
  Epoch 020 - train 0.00136 | val 4.02379
  Epoch 022 - train 0.00144 | val 4.09602
  Classification -> best τ=0.600 (val F1=0.2788)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.19756 | val 0.92355
  Epoch 020 - train 0.00424 | val 2.00508
  Epoch 022 - train 0.00361 | val 2.04871
  Classification -> best τ=0.460 (val F1=0.2262)
  Directional -> Accuracy: 0.4143, MCC: -0.1106, F1: 0.5176

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08836 | val 2.09765
  Epoch 020 - train 0.00197 | val 3.11301
  Epoch 021 - train 0.00203 | val 3.15287
  Classification -> best τ=0.575 (val F1=0.0833)
  Directional -> Accuracy: 0.5600, MCC: 0.0902, F1: 0.2667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.06449 | val 2.25336
  Epoch 020 - train 0.00156 | val 3.10393
  Epoch 021 - train 0.00174 | val 3.12575
  Classification -> best τ=0.330 (val F1=0.1830)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09775 | val 2.61367
  Epoch 020 - train 0.00225 | val 3.67537
  Epoch 021 - train 0.00213 | val 3.72423
  Classification -> best τ=0.460 (val F1=0.2004)
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13284 | val 1.10700
  Epoch 020 - train 0.00194 | val 1.77860
  Epoch 024 - train 0.00196 | val 1.88279
  Classification -> best τ=0.390 (val F1=0.3180)
  Directional -> Accuracy: 0.5246, MCC: 0.0468, F1: 0.6133

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.30887 | val 1.62478
  Epoch 020 - train 0.00592 | val 2.33602
  Epoch 022 - train 0.00417 | val 2.40064
  Classification -> best τ=0.460 (val F1=0.1262)
  Directional -> Accuracy: 0.5385, MCC: 0.2673, F1: 0.6667

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.23752 | val 1.50713
  Epoch 020 - train 0.00769 | val 2.01688
  Epoch 022 - train 0.00534 | val 2.24872
  Classification -> best τ=0.520 (val F1=0.3190)
  Directional -> Accuracy: 0.5429, MCC: 0.0544, F1: 0.6364

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.22485 | val 2.17655
  Epoch 020 - train 0.00540 | val 4.06012
  Epoch 021 - train 0.00546 | val 4.13144
  Classification -> best τ=0.650 (val F1=0.1857)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16210 | val 2.29004
  Epoch 020 - train 0.00197 | val 3.84948
  Epoch 021 - train 0.00205 | val 3.89086
  Classification -> best τ=0.465 (val F1=0.2089)
  Directional -> Accuracy: 0.5789, MCC: 0.0042, F1: 0.7143

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.15281 | val 2.20614
  Epoch 020 - train 0.00564 | val 2.17781
  Epoch 022 - train 0.00367 | val 2.23386
  Classification -> best τ=0.500 (val F1=0.2382)
  Directional -> Accuracy: 0.4615, MCC: 0.0668, F1: 0.2553

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.25512 | val 1.32219
  Epoch 020 - train 0.00525 | val 2.02509
  Epoch 021 - train 0.00488 | val 2.07995
  Classification -> best τ=0.520 (val F1=0.2137)
  Directional -> Accuracy: 0.4533, MCC: -0.0724, F1: 0.4058

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11183 | val 2.06224
  Epoch 020 - train 0.00195 | val 2.94881
  Epoch 022 - train 0.00226 | val 3.01081
  Classification -> best τ=0.600 (val F1=0.0053)
  Directional -> Accuracy: 0.3958, MCC: -0.1277, F1: 0.3556

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.26495 | val 1.43302
  Epoch 020 - train 0.00737 | val 2.51872
  Epoch 021 - train 0.00577 | val 2.57985
  Classification -> best τ=0.400 (val F1=0.2054)
  Directional -> Accuracy: 0.4697, MCC: -0.0845, F1: 0.6067

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16751 | val 1.75850
  Epoch 020 - train 0.00462 | val 2.42991
  Epoch 021 - train 0.00284 | val 2.45751
  Classification -> best τ=0.455 (val F1=0.2417)
  Directional -> Accuracy: 0.5690, MCC: 0.0263, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.17786 | val 1.29928
  Epoch 020 - train 0.00334 | val 2.23456
  Epoch 023 - train 0.00230 | val 2.35199
  Classification -> best τ=0.475 (val F1=0.2865)
  Directional -> Accuracy: 0.5303, MCC: 0.0554, F1: 0.4918

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14827 | val 1.46077
  Epoch 020 - train 0.00284 | val 2.47239
  Epoch 022 - train 0.00305 | val 2.53468
  Classification -> best τ=0.520 (val F1=0.4330)
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.04321 | val 1.78720
  Epoch 020 - train 0.00126 | val 4.11401
  Epoch 021 - train 0.00101 | val 4.18901
  Classification -> best τ=0.415 (val F1=0.1925)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09683 | val 0.90105
  Epoch 020 - train 0.00369 | val 1.85423
  Epoch 021 - train 0.00230 | val 1.87744
  Classification -> best τ=0.580 (val F1=0.2057)
  Directional -> Accuracy: 0.5349, MCC: 0.1734, F1: 0.4444

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.18344 | val 2.22147
  Epoch 020 - train 0.00677 | val 2.89797
  Epoch 021 - train 0.00509 | val 2.92210
  Classification -> best τ=0.485 (val F1=0.0502)
  Directional -> Accuracy: 0.4561, MCC: 0.1181, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14427 | val 2.96801
  Epoch 020 - train 0.00839 | val 4.84203
  Epoch 021 - train 0.00336 | val 4.91085
  Classification -> best τ=0.460 (val F1=0.2359)
  Directional -> Accuracy: 0.5854, MCC: 0.2437, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14665 | val 1.74866
  Epoch 020 - train 0.00429 | val 2.82824
  Epoch 021 - train 0.00388 | val 2.87709
  Classification -> best τ=0.550 (val F1=0.2112)
  Directional -> Accuracy: 0.5581, MCC: 0.1307, F1: 0.3448

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.19789 | val 1.37832
  Epoch 020 - train 0.00488 | val 2.46175
  Epoch 021 - train 0.00407 | val 2.48841
  Classification -> best τ=0.485 (val F1=0.3636)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11023 | val 1.96848
  Epoch 020 - train 0.00389 | val 2.92486
  Epoch 022 - train 0.00285 | val 2.95985
  Classification -> best τ=0.670 (val F1=0.2320)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.22580 | val 1.05273
  Epoch 020 - train 0.00563 | val 2.11022
  Epoch 023 - train 0.00278 | val 2.20118
  Classification -> best τ=0.390 (val F1=0.2994)
  Directional -> Accuracy: 0.5890, MCC: 0.1778, F1: 0.6154

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.06745 | val 1.13529
  Epoch 020 - train 0.00137 | val 2.23738
  Epoch 022 - train 0.00146 | val 2.29595
  Classification -> best τ=0.475 (val F1=0.0976)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6415

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.07734 | val 2.36103
  Epoch 020 - train 0.00193 | val 3.59961
  Epoch 021 - train 0.00214 | val 3.65044
  Classification -> best τ=0.540 (val F1=0.1775)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.24359 | val 1.15909
  Epoch 020 - train 0.00528 | val 2.26694
  Epoch 021 - train 0.00420 | val 2.30627
  Classification -> best τ=0.345 (val F1=0.1148)
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.04841 | val 1.55645
  Epoch 020 - train 0.00042 | val 2.02083
  Epoch 023 - train 0.00032 | val 2.02795
  Classification -> best τ=0.655 (val F1=0.3943)
  Directional -> Accuracy: 0.6047, MCC: 0.2739, F1: 0.4516

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12441 | val 2.36154
  Epoch 020 - train 0.00186 | val 2.57160
  Epoch 024 - train 0.00119 | val 2.64158
  Classification -> best τ=0.235 (val F1=0.2718)
  Directional -> Accuracy: 0.4737, MCC: -0.0145, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11971 | val 1.13809
  Epoch 020 - train 0.00369 | val 1.87102
  Epoch 021 - train 0.00281 | val 1.90729
  Classification -> best τ=0.445 (val F1=0.1162)
  Directional -> Accuracy: 0.4894, MCC: -0.0805, F1: 0.5862

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.04318 | val 1.62061
  Epoch 020 - train 0.00091 | val 2.55882
  Epoch 021 - train 0.00083 | val 2.58197
  Classification -> best τ=0.605 (val F1=0.2076)
  Directional -> Accuracy: 0.4082, MCC: 0.0264, F1: 0.5246

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07992 | val 1.54109
  Epoch 020 - train 0.00199 | val 2.92126
  Epoch 021 - train 0.00150 | val 2.97896
  Classification -> best τ=0.475 (val F1=0.2227)
  Directional -> Accuracy: 0.3947, MCC: -0.2806, F1: 0.5306

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.20403 | val 1.43909
  Epoch 020 - train 0.00494 | val 2.27162
  Epoch 022 - train 0.00292 | val 2.34415
  Classification -> best τ=0.350 (val F1=0.2782)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12856 | val 2.03027
  Epoch 020 - train 0.00617 | val 2.39844
  Epoch 021 - train 0.00255 | val 2.41638
  Classification -> best τ=0.420 (val F1=0.2739)
  Directional -> Accuracy: 0.5106, MCC: 0.0065, F1: 0.6567

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.06967 | val 1.84427
  Epoch 020 - train 0.00208 | val 2.60024
  Epoch 021 - train 0.00153 | val 2.62162
  Classification -> best τ=0.495 (val F1=0.1499)
  Directional -> Accuracy: 0.5000, MCC: -0.1283, F1: 0.6452

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10730 | val 2.13537
  Epoch 020 - train 0.00467 | val 3.35984
  Epoch 022 - train 0.00365 | val 3.55022
  Classification -> best τ=0.455 (val F1=0.4714)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13559 | val 2.28298
  Epoch 020 - train 0.00227 | val 2.92683
  Epoch 021 - train 0.00208 | val 2.95962
  Classification -> best τ=0.605 (val F1=0.2524)
  Directional -> Accuracy: 0.4107, MCC: -0.2108, F1: 0.0571

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.04865 | val 3.35520
  Epoch 020 - train 0.00188 | val 4.30804

[I 2026-02-19 01:18:18,340] Trial 32 finished with value: 0.21898579452372138 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 0.00623749277897472, 'weight_decay': 1.1001609129806894e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.2791304222187907, 'early_stopping_min_delta': 0.0016751054906412113}. Best is trial 10 with value: 0.2688998415931245.

  Classification -> best τ=0.385 (val F1=0.0944)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21898579452372138
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45984 | val 1.08365
  Epoch 020 - train 0.23450 | val 1.48170
  Epoch 021 - train 0.23204 | val 1.88086
  Classification -> best τ=0.505 (val F1=0.2346)
  Directional -> Accuracy: 0.5256, MCC: -0.0501, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43667 | val 0.73776
  Epoch 020 - train 0.19203 | val 1.13257
  Epoch 021 - train 0.17846 | val 1.16969
  Classification -> best τ=0.430 (val F1=0.1895)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46017 | val 0.73368
  Epoch 020 - train 0.23318 | val 1.18888
  Epoch 021 - train 0.23275 | val 1.13718
  Classification -> best τ=0.580 (val F1=0.1358)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51827 | val 0.92599
  Epoch 020 - train 0.34119 | val 2.13211
  Epoch 021 - train 0.32555 | val 2.38922
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50179 | val 0.70538
  Epoch 020 - train 0.21943 | val 1.08506
  Epoch 023 - train 0.17960 | val 1.16277
  Classification -> best τ=0.515 (val F1=0.3651)
  Directional -> Accuracy: 0.6154, MCC: 0.2682, F1: 0.5652

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44039 | val 1.33253
  Epoch 020 - train 0.25442 | val 4.19279
  Epoch 021 - train 0.23994 | val 4.40555
  Classification -> best τ=0.555 (val F1=0.3081)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.54536 | val 0.80588
  Epoch 020 - train 0.28087 | val 0.97181
  Epoch 023 - train 0.22297 | val 1.08393
  Classification -> best τ=0.475 (val F1=0.2996)
  Directional -> Accuracy: 0.4000, MCC: -0.1021, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42608 | val 1.27578
  Epoch 020 - train 0.24996 | val 2.44067
  Epoch 021 - train 0.23673 | val 2.45184
  Classification -> best τ=0.500 (val F1=0.1512)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.38895 | val 0.77691
  Epoch 020 - train 0.13655 | val 1.43568
  Epoch 021 - train 0.12330 | val 1.47757
  Classification -> best τ=0.535 (val F1=0.1638)
  Directional -> Accuracy: 0.6190, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43922 | val 0.73037
  Epoch 020 - train 0.19492 | val 1.01679
  Epoch 022 - train 0.13902 | val 1.08913
  Classification -> best τ=0.460 (val F1=0.0850)
  Directional -> Accuracy: 0.3944, MCC: -0.1706, F1: 0.5169

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.45393 | val 0.77748
  Epoch 020 - train 0.18264 | val 1.81350
  Epoch 023 - train 0.13431 | val 2.11466
  Classification -> best τ=0.420 (val F1=0.1926)
  Directional -> Accuracy: 0.4118, MCC: -0.1742, F1: 0.5312

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.39582 | val 1.88530
  Epoch 020 - train 0.16918 | val 3.33168
  Epoch 021 - train 0.15165 | val 3.42017
  Classification -> best τ=0.415 (val F1=0.1479)
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43063 | val 1.07465
  Epoch 020 - train 0.25457 | val 1.61527
  Epoch 021 - train 0.23983 | val 1.74387
  Classification -> best τ=0.445 (val F1=0.2477)
  Directional -> Accuracy: 0.4773, MCC: 0.0227, F1: 0.5965

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.46974 | val 1.20757
  Epoch 020 - train 0.22970 | val 2.14806
  Epoch 021 - train 0.21372 | val 2.36030
  Classification -> best τ=0.495 (val F1=0.2853)
  Directional -> Accuracy: 0.5806, MCC: 0.1981, F1: 0.6750

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42935 | val 0.84476
  Epoch 020 - train 0.18117 | val 1.66683
  Epoch 021 - train 0.16678 | val 1.66380
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48515 | val 0.82456
  Epoch 020 - train 0.24754 | val 1.33670
  Epoch 022 - train 0.21766 | val 1.50043
  Classification -> best τ=0.370 (val F1=0.3866)
  Directional -> Accuracy: 0.5352, MCC: 0.0120, F1: 0.6916

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43639 | val 0.84652
  Epoch 020 - train 0.22612 | val 1.97701
  Epoch 021 - train 0.21580 | val 1.97714
  Classification -> best τ=0.510 (val F1=0.2859)
  Directional -> Accuracy: 0.3667, MCC: -0.1488, F1: 0.1739

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48351 | val 1.44229
  Epoch 020 - train 0.29164 | val 2.39601
  Epoch 021 - train 0.28367 | val 2.60375
  Classification -> best τ=0.465 (val F1=0.1936)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.50102 | val 1.39001
  Epoch 020 - train 0.24951 | val 2.39820
  Epoch 021 - train 0.24044 | val 2.20666
  Classification -> best τ=0.475 (val F1=0.1768)
  Directional -> Accuracy: 0.4697, MCC: 0.0938, F1: 0.2857

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48373 | val 0.78988
  Epoch 020 - train 0.28910 | val 1.06261
  Epoch 023 - train 0.23564 | val 1.30406
  Classification -> best τ=0.475 (val F1=0.2914)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.41589 | val 0.87695
  Epoch 020 - train 0.17019 | val 1.78312
  Epoch 021 - train 0.15835 | val 1.83383
  Classification -> best τ=0.510 (val F1=0.0987)
  Directional -> Accuracy: 0.4694, MCC: -0.0244, F1: 0.5000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40644 | val 1.05816
  Epoch 020 - train 0.19079 | val 1.53620
  Epoch 021 - train 0.17690 | val 1.56387
  Classification -> best τ=0.490 (val F1=0.2070)
  Directional -> Accuracy: 0.4478, MCC: -0.1487, F1: 0.5843

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.44457 | val 0.70869
  Epoch 020 - train 0.20089 | val 0.99390
  Epoch 024 - train 0.13452 | val 1.14913
  Classification -> best τ=0.635 (val F1=0.3228)
  Directional -> Accuracy: 0.5593, MCC: 0.1281, F1: 0.5806

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47911 | val 1.26829
  Epoch 020 - train 0.25105 | val 1.63527
  Epoch 021 - train 0.23427 | val 1.55091
  Classification -> best τ=0.505 (val F1=0.1452)
  Directional -> Accuracy: 0.5522, MCC: 0.0970, F1: 0.4828

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.44364 | val 0.79279
  Epoch 020 - train 0.20442 | val 1.37836
  Epoch 023 - train 0.16106 | val 1.52371
  Classification -> best τ=0.560 (val F1=0.3457)
  Directional -> Accuracy: 0.4561, MCC: -0.0051, F1: 0.2439

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.35056 | val 0.77286
  Epoch 020 - train 0.14275 | val 1.48706
  Epoch 021 - train 0.13207 | val 1.60627
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.41804 | val 0.67604
  Epoch 020 - train 0.16471 | val 1.37689
  Epoch 027 - train 0.06693 | val 1.92400
  Classification -> best τ=0.515 (val F1=0.3283)
  Directional -> Accuracy: 0.5909, MCC: 0.1132, F1: 0.6897

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47470 | val 1.21201
  Epoch 020 - train 0.28555 | val 1.84275
  Epoch 021 - train 0.27117 | val 1.90963
  Classification -> best τ=0.445 (val F1=0.2211)
  Directional -> Accuracy: 0.5345, MCC: 0.2275, F1: 0.3077

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.41361 | val 0.69916
  Epoch 020 - train 0.20067 | val 0.98729
  Epoch 025 - train 0.15940 | val 1.26532
  Classification -> best τ=0.540 (val F1=0.4606)
  Directional -> Accuracy: 0.5814, MCC: 0.2368, F1: 0.7188

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49801 | val 0.98532
  Epoch 020 - train 0.27391 | val 1.62220
  Epoch 021 - train 0.26005 | val 1.73595
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42927 | val 0.81688
  Epoch 020 - train 0.22508 | val 1.57465
  Epoch 022 - train 0.19500 | val 1.75959
  Classification -> best τ=0.460 (val F1=0.2272)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42918 | val 0.88602
  Epoch 020 - train 0.18508 | val 1.67002
  Epoch 025 - train 0.11427 | val 2.04629
  Classification -> best τ=0.270 (val F1=0.2793)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.47945 | val 0.90059
  Epoch 020 - train 0.21234 | val 2.34350
  Epoch 023 - train 0.17013 | val 2.66404
  Classification -> best τ=0.450 (val F1=0.2823)
  Directional -> Accuracy: 0.5135, MCC: 0.0803, F1: 0.4545

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.41131 | val 0.76613
  Epoch 020 - train 0.24561 | val 0.95807
  Epoch 021 - train 0.23082 | val 0.98938
  Classification -> best τ=0.445 (val F1=0.2145)
  Directional -> Accuracy: 0.5128, MCC: 0.0468, F1: 0.6122

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39278 | val 1.08846
  Epoch 020 - train 0.19563 | val 1.59510
  Epoch 021 - train 0.18080 | val 1.51827
  Classification -> best τ=0.495 (val F1=0.2500)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53629 | val 0.73462
  Epoch 020 - train 0.30168 | val 0.90218
  Epoch 021 - train 0.29658 | val 0.95090
  Classification -> best τ=0.455 (val F1=0.3219)
  Directional -> Accuracy: 0.5294, MCC: 0.1025, F1: 0.5000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.37651 | val 0.74561
  Epoch 020 - train 0.20463 | val 0.97252
  Epoch 021 - train 0.19108 | val 1.01798
  Classification -> best τ=0.460 (val F1=0.1654)
  Directional -> Accuracy: 0.7045, MCC: 0.4201, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42930 | val 1.14629
  Epoch 020 - train 0.25053 | val 1.18013
  Epoch 021 - train 0.23598 | val 1.23931
  Classification -> best τ=0.515 (val F1=0.2044)
  Directional -> Accuracy: 0.4483, MCC: -0.0851, F1: 0.5152

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42861 | val 1.10323
  Epoch 020 - train 0.23497 | val 1.46932
  Epoch 021 - train 0.22209 | val 1.54706
  Classification -> best τ=0.460 (val F1=0.2799)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46590 | val 0.96946
  Epoch 020 - train 0.25687 | val 1.26572
  Epoch 022 - train 0.23210 | val 1.37477
  Classification -> best τ=0.530 (val F1=0.2981)
  Directional -> Accuracy: 0.3750, MCC: 0.1175, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.40814 | val 0.82797
  Epoch 020 - train 0.20939 | val 1.24979
  Epoch 021 - train 0.19359 | val 1.30872
  Classification -> best τ=0.515 (val F1=0.0510)
  Directional -> Accuracy: 0.4615, MCC: -0.1091, F1: 0.5532

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.46644 | val 1.63069
  Epoch 020 - train 0.24622 | val 2.24284
  Epoch 021 - train 0.22943 | val 2.30294
  Classification -> best τ=0.450 (val F1=0.1898)
  Directional -> Accuracy: 0.5132, MCC: 0.1155, F1: 0.6726

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42443 | val 0.72917
  Epoch 020 - train 0.23634 | val 1.08983
  Epoch 021 - train 0.22079 | val 1.05498
  Classification -> best τ=0.450 (val F1=0.2236)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.39580 | val 0.81102
  Epoch 020 - train 0.22798 | val 0.81244
  Epoch 021 - train 0.21606 | val 0.79730
  Classification -> best τ=0.530 (val F1=0.2774)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44922 | val 0.92755
  Epoch 020 - train 0.27094 | val 1.56004
  Epoch 021 - train 0.25567 | val 1.48977
  Classification -> best τ=0.450 (val F1=0.0325)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42770 | val 0.96377
  Epoch 020 - train 0.23276 | val 1.74318
  Epoch 021 - train 0.21608 | val 1.93829
  Classification -> best τ=0.390 (val F1=0.2973)
  Directional -> Accuracy: 0.5439, MCC: 0.0356, F1: 0.6750

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43850 | val 1.39334
  Epoch 020 - train 0.21012 | val 2.13956
  Epoch 021 - train 0.19276 | val 2.27459
  Classification -> best τ=0.575 (val F1=0.2961)
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.46947 | val 1.14982
  Epoch 020 - train 0.22808 | val 2.36666
  Epoch 021 - train 0.21103 | val 2.42307
  Classification -> best τ=0.430 (val F1=0.2276)

[I 2026-02-19 01:20:23,075] Trial 33 finished with value: 0.2164523396602899 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 0.0016230116808722329, 'weight_decay': 2.615866105211091e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.7534587601039104, 'early_stopping_min_delta': 0.009934644908905006}. Best is trial 10 with value: 0.2688998415931245.

  Classification -> best τ=0.480 (val F1=0.1916)
  Directional -> Accuracy: 0.5000, MCC: 0.0064, F1: 0.5373

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2164523396602899
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.45102 | val 0.77295
  Epoch 020 - train 0.11601 | val 2.03474
  Epoch 028 - train 0.02576 | val 2.66298
  Classification -> best τ=0.830 (val F1=0.2463)
  Directional -> Accuracy: 0.5897, MCC: 0.1484, F1: 0.3600

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42760 | val 0.69381
  Epoch 020 - train 0.11183 | val 1.27832
  Epoch 026 - train 0.02290 | val 2.44989
  Classification -> best τ=0.410 (val F1=0.3286)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.51090 | val 0.86585
  Epoch 020 - train 0.09416 | val 1.63046
  Epoch 022 - train 0.05465 | val 1.79407
  Classification -> best τ=0.550 (val F1=0.3171)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.51413 | val 0.73077
  Epoch 020 - train 0.19277 | val 2.52047
  Epoch 021 - train 0.14179 | val 2.69794
  Classification -> best τ=0.545 (val F1=0.1095)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.46042 | val 0.78776
  Epoch 020 - train 0.15771 | val 1.21224
  Epoch 023 - train 0.09115 | val 1.53911
  Classification -> best τ=0.525 (val F1=0.4234)
  Directional -> Accuracy: 0.6923, MCC: 0.3929, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46419 | val 1.50081
  Epoch 020 - train 0.16277 | val 3.47453
  Epoch 022 - train 0.16748 | val 4.07070
  Classification -> best τ=0.505 (val F1=0.3118)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.50490 | val 0.76284
  Epoch 020 - train 0.09279 | val 1.06136
  Epoch 025 - train 0.01347 | val 1.55756
  Classification -> best τ=0.620 (val F1=0.2488)
  Directional -> Accuracy: 0.5714, MCC: 0.0155, F1: 0.2500

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.38478 | val 1.76000
  Epoch 020 - train 0.06747 | val 4.58955
  Epoch 022 - train 0.03999 | val 5.27157
  Classification -> best τ=0.630 (val F1=0.2548)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.45876 | val 0.72505
  Epoch 020 - train 0.06583 | val 2.12996
  Epoch 022 - train 0.03487 | val 2.47400
  Classification -> best τ=0.550 (val F1=0.3303)
  Directional -> Accuracy: 0.5476, MCC: 0.1475, F1: 0.5366

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43267 | val 0.71396
  Epoch 020 - train 0.11280 | val 1.44765
  Epoch 025 - train 0.05275 | val 1.69627
  Classification -> best τ=0.485 (val F1=0.1825)
  Directional -> Accuracy: 0.5211, MCC: 0.0555, F1: 0.5143

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43485 | val 1.56221
  Epoch 020 - train 0.08701 | val 2.72224
  Epoch 025 - train 0.01491 | val 3.71221
  Classification -> best τ=0.505 (val F1=0.2252)
  Directional -> Accuracy: 0.5490, MCC: 0.0788, F1: 0.3030

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43191 | val 1.84052
  Epoch 020 - train 0.05091 | val 4.33775
  Epoch 021 - train 0.10213 | val 4.27945
  Classification -> best τ=0.575 (val F1=0.1663)
  Directional -> Accuracy: 0.5424, MCC: 0.1774, F1: 0.2286

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.45095 | val 1.14400
  Epoch 020 - train 0.12778 | val 3.38777
  Epoch 021 - train 0.11715 | val 4.09372
  Classification -> best τ=0.400 (val F1=0.2750)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.47409 | val 0.85845
  Epoch 020 - train 0.16801 | val 1.19731
  Epoch 022 - train 0.11349 | val 1.82114
  Classification -> best τ=0.505 (val F1=0.2838)
  Directional -> Accuracy: 0.5968, MCC: 0.2631, F1: 0.6988

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.38520 | val 0.86767
  Epoch 020 - train 0.06922 | val 1.68556
  Epoch 023 - train 0.07036 | val 2.04837
  Classification -> best τ=0.535 (val F1=0.1536)
  Directional -> Accuracy: 0.5094, MCC: -0.1310, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47117 | val 1.12203
  Epoch 020 - train 0.15929 | val 1.90837
  Epoch 021 - train 0.12739 | val 2.08966
  Classification -> best τ=0.640 (val F1=0.2402)
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43557 | val 0.88331
  Epoch 020 - train 0.06144 | val 4.29725
  Epoch 022 - train 0.08390 | val 4.11636
  Classification -> best τ=0.565 (val F1=0.0647)
  Directional -> Accuracy: 0.4167, MCC: 0.1464, F1: 0.1026

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.52139 | val 1.90222
  Epoch 020 - train 0.18521 | val 4.30106
  Epoch 021 - train 0.18958 | val 3.87383
  Classification -> best τ=0.490 (val F1=0.1384)
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.41624 | val 1.20248
  Epoch 020 - train 0.06536 | val 2.45630
  Epoch 023 - train 0.01579 | val 2.40632
  Classification -> best τ=0.485 (val F1=0.2435)
  Directional -> Accuracy: 0.4091, MCC: -0.0327, F1: 0.0488

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53697 | val 0.78300
  Epoch 020 - train 0.21349 | val 1.62264
  Epoch 023 - train 0.14619 | val 1.76231
  Classification -> best τ=0.480 (val F1=0.3413)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.36949 | val 1.05278
  Epoch 020 - train 0.06297 | val 1.89932
  Epoch 024 - train 0.02427 | val 2.25846
  Classification -> best τ=0.410 (val F1=0.2484)
  Directional -> Accuracy: 0.5306, MCC: -0.1428, F1: 0.6761

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.52006 | val 1.11606
  Epoch 020 - train 0.15178 | val 1.90632
  Epoch 021 - train 0.13871 | val 1.92700
  Classification -> best τ=0.430 (val F1=0.2409)
  Directional -> Accuracy: 0.4776, MCC: -0.0866, F1: 0.6237

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45646 | val 0.91763
  Epoch 020 - train 0.08515 | val 1.74590
  Epoch 021 - train 0.05102 | val 1.83002
  Classification -> best τ=0.580 (val F1=0.3228)
  Directional -> Accuracy: 0.5085, MCC: 0.0911, F1: 0.4314

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50593 | val 0.72628
  Epoch 020 - train 0.15218 | val 1.69826
  Epoch 023 - train 0.15574 | val 1.50957
  Classification -> best τ=0.465 (val F1=0.1326)
  Directional -> Accuracy: 0.5224, MCC: 0.0663, F1: 0.5897

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.47498 | val 0.90833
  Epoch 020 - train 0.10488 | val 2.33393
  Epoch 023 - train 0.08931 | val 2.52532
  Classification -> best τ=0.430 (val F1=0.4074)
  Directional -> Accuracy: 0.5088, MCC: 0.0572, F1: 0.4615

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.24745 | val 0.97249
  Epoch 020 - train 0.02486 | val 2.31480
  Epoch 021 - train 0.01315 | val 2.57773
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43772 | val 0.82759
  Epoch 020 - train 0.06449 | val 3.09860
  Epoch 022 - train 0.05020 | val 3.70950
  Classification -> best τ=0.480 (val F1=0.2503)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47618 | val 1.31557
  Epoch 020 - train 0.28130 | val 2.99898
  Epoch 021 - train 0.22834 | val 2.79797
  Classification -> best τ=0.445 (val F1=0.0461)
  Directional -> Accuracy: 0.5690, MCC: 0.1469, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.39179 | val 1.09561
  Epoch 020 - train 0.13163 | val 1.80420
  Epoch 021 - train 0.11346 | val 1.83387
  Classification -> best τ=0.565 (val F1=0.3344)
  Directional -> Accuracy: 0.5116, MCC: 0.0352, F1: 0.4878

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.37856 | val 1.63651
  Epoch 020 - train 0.10811 | val 2.95533
  Epoch 021 - train 0.08531 | val 2.97426
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43535 | val 0.76046
  Epoch 020 - train 0.14059 | val 1.95745
  Epoch 023 - train 0.06229 | val 1.83039
  Classification -> best τ=0.535 (val F1=0.3162)
  Directional -> Accuracy: 0.5333, MCC: 0.0782, F1: 0.5116

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40475 | val 0.96408
  Epoch 020 - train 0.05341 | val 2.06571
  Epoch 025 - train 0.00922 | val 2.56155
  Classification -> best τ=0.360 (val F1=0.3114)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.42169 | val 1.22739
  Epoch 020 - train 0.07610 | val 2.90264
  Epoch 022 - train 0.05507 | val 3.62078
  Classification -> best τ=0.540 (val F1=0.2677)
  Directional -> Accuracy: 0.4595, MCC: 0.0404, F1: 0.2000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.38060 | val 0.94381
  Epoch 020 - train 0.10615 | val 1.44763
  Epoch 021 - train 0.10042 | val 1.50539
  Classification -> best τ=0.430 (val F1=0.1234)
  Directional -> Accuracy: 0.5385, MCC: 0.1312, F1: 0.6538

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.35293 | val 1.26705
  Epoch 020 - train 0.07931 | val 3.11947
  Epoch 021 - train 0.06908 | val 2.46721
  Classification -> best τ=0.450 (val F1=0.2500)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52561 | val 0.76182
  Epoch 020 - train 0.13083 | val 1.40544
  Epoch 021 - train 0.10980 | val 1.60152
  Classification -> best τ=0.460 (val F1=0.3930)
  Directional -> Accuracy: 0.5588, MCC: 0.2056, F1: 0.4828

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40013 | val 0.87667
  Epoch 020 - train 0.09619 | val 1.95114
  Epoch 023 - train 0.06682 | val 1.97930
  Classification -> best τ=0.505 (val F1=0.3705)
  Directional -> Accuracy: 0.6364, MCC: 0.3062, F1: 0.5294

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.41655 | val 1.39632
  Epoch 020 - train 0.10430 | val 2.89829
  Epoch 021 - train 0.07794 | val 3.02992
  Classification -> best τ=0.430 (val F1=0.1687)
  Directional -> Accuracy: 0.4655, MCC: -0.0316, F1: 0.5867

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40285 | val 1.07171
  Epoch 020 - train 0.07614 | val 1.66490
  Epoch 021 - train 0.04620 | val 1.96945
  Classification -> best τ=0.415 (val F1=0.2233)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48554 | val 1.38909
  Epoch 020 - train 0.12333 | val 2.86833
  Epoch 021 - train 0.08994 | val 2.79604
  Classification -> best τ=0.495 (val F1=0.3779)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.39442 | val 1.10941
  Epoch 020 - train 0.08258 | val 3.15941
  Epoch 022 - train 0.05312 | val 3.99560
  Classification -> best τ=0.490 (val F1=0.2467)
  Directional -> Accuracy: 0.5128, MCC: 0.0725, F1: 0.3871

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.47855 | val 1.24605
  Epoch 020 - train 0.10646 | val 2.56181
  Epoch 022 - train 0.23855 | val 2.62768
  Classification -> best τ=0.340 (val F1=0.3270)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.39348 | val 0.87124
  Epoch 020 - train 0.09996 | val 2.28782
  Epoch 021 - train 0.10090 | val 2.60128
  Classification -> best τ=0.530 (val F1=0.1674)
  Directional -> Accuracy: 0.5417, MCC: 0.1260, F1: 0.2667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.31876 | val 1.55701
  Epoch 020 - train 0.04196 | val 3.11062
  Epoch 021 - train 0.04229 | val 3.12160
  Classification -> best τ=0.580 (val F1=0.2774)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43826 | val 1.21161
  Epoch 020 - train 0.11731 | val 2.67827
  Epoch 021 - train 0.13124 | val 3.08661
  Classification -> best τ=0.455 (val F1=0.0325)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40159 | val 1.92430
  Epoch 020 - train 0.09255 | val 3.43904
  Epoch 021 - train 0.08017 | val 3.84074
  Classification -> best τ=0.395 (val F1=0.2973)
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.41596 | val 1.77154
  Epoch 020 - train 0.04234 | val 3.66672
  Epoch 021 - train 0.02583 | val 4.22068
  Classification -> best τ=0.635 (val F1=0.4201)
  Directional -> Accuracy: 0.5345, MCC: 0.0778, F1: 0.5714

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.43708 | val 1.12817
  Epoch 020 - train 0.10998 | val 2.60282
  Epoch 022 - train 0.06201 | val 2.51244
  Classification -> best τ=0.355 (val F1=0.1569)

[I 2026-02-19 01:22:29,166] Trial 34 finished with value: 0.2395771273572471 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.0038288482060472263, 'weight_decay': 5.901617080758288e-07, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.8071716814889653, 'early_stopping_min_delta': 0.0006692095732986568}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 023 - train 0.03409 | val 1.84047
  Classification -> best τ=0.560 (val F1=0.2653)
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2395771273572471
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.19738 | val 1.88234
  Epoch 020 - train 0.08444 | val 2.64014
  Epoch 021 - train 0.08033 | val 2.67683
  Classification -> best τ=0.700 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0174, F1: 0.0556

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.18092 | val 3.37223
  Epoch 020 - train 0.09425 | val 3.99887
  Epoch 021 - train 0.08210 | val 4.13924
  Classification -> best τ=0.350 (val F1=0.1844)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.19567 | val 1.70066
  Epoch 020 - train 0.08845 | val 2.30299
  Epoch 021 - train 0.09142 | val 2.27576
  Classification -> best τ=0.500 (val F1=0.3214)
  Directional -> Accuracy: 0.5000, MCC: -0.0266, F1: 0.6102

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.18372 | val 2.62933
  Epoch 020 - train 0.08660 | val 3.66115
  Epoch 021 - train 0.07712 | val 3.71214
  Classification -> best τ=0.210 (val F1=0.2217)
  Directional -> Accuracy: 0.5135, MCC: 0.2204, F1: 0.1818

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10570 | val 1.67970
  Epoch 020 - train 0.03794 | val 2.65311
  Epoch 023 - train 0.03563 | val 2.80006
  Classification -> best τ=0.460 (val F1=0.3678)
  Directional -> Accuracy: 0.5400, MCC: 0.0726, F1: 0.5965

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11742 | val 2.98489
  Epoch 020 - train 0.05393 | val 3.90542
  Epoch 021 - train 0.05429 | val 3.96188
  Classification -> best τ=0.630 (val F1=0.3525)
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16490 | val 1.49149
  Epoch 020 - train 0.06601 | val 1.76243
  Epoch 021 - train 0.07187 | val 1.78370
  Classification -> best τ=0.530 (val F1=0.3010)
  Directional -> Accuracy: 0.5882, MCC: 0.1742, F1: 0.5333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13241 | val 2.61281
  Epoch 020 - train 0.07534 | val 3.66330
  Epoch 021 - train 0.07706 | val 3.68784
  Classification -> best τ=0.560 (val F1=0.2075)
  Directional -> Accuracy: 0.3810, MCC: -0.2107, F1: 0.5357

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13255 | val 1.65189
  Epoch 020 - train 0.05615 | val 1.98617
  Epoch 021 - train 0.06047 | val 1.98588
  Classification -> best τ=0.455 (val F1=0.3320)
  Directional -> Accuracy: 0.4167, MCC: -0.1654, F1: 0.5882

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13274 | val 1.89162
  Epoch 020 - train 0.05539 | val 1.82356
  Epoch 021 - train 0.04692 | val 1.83588
  Classification -> best τ=0.300 (val F1=0.4258)
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14064 | val 1.78481
  Epoch 020 - train 0.05442 | val 2.12268
  Epoch 021 - train 0.05609 | val 2.11804
  Classification -> best τ=0.600 (val F1=0.1738)
  Directional -> Accuracy: 0.5714, MCC: 0.1044, F1: 0.3636

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.20802 | val 3.36913
  Epoch 020 - train 0.09412 | val 4.82717
  Epoch 021 - train 0.09064 | val 4.81768
  Classification -> best τ=0.460 (val F1=0.1843)
  Directional -> Accuracy: 0.5439, MCC: 0.0915, F1: 0.6389

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.15531 | val 2.68525
  Epoch 020 - train 0.07496 | val 3.17299
  Epoch 021 - train 0.06963 | val 3.20211
  Classification -> best τ=0.440 (val F1=0.2557)
  Directional -> Accuracy: 0.5000, MCC: -0.0235, F1: 0.4000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.19186 | val 1.26108
  Epoch 020 - train 0.08079 | val 1.49396
  Epoch 021 - train 0.08348 | val 1.50945
  Classification -> best τ=0.575 (val F1=0.1774)
  Directional -> Accuracy: 0.4833, MCC: -0.1302, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.17605 | val 1.46659
  Epoch 020 - train 0.08270 | val 2.16450
  Epoch 021 - train 0.08148 | val 2.22773
  Classification -> best τ=0.675 (val F1=0.1455)
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.20452 | val 1.07451
  Epoch 020 - train 0.09703 | val 1.38634
  Epoch 021 - train 0.08700 | val 1.39716
  Classification -> best τ=0.385 (val F1=0.2659)
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.19611 | val 4.69385
  Epoch 020 - train 0.08629 | val 5.82069
  Epoch 021 - train 0.08456 | val 5.82869
  Classification -> best τ=0.605 (val F1=0.2276)
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.17441 | val 2.99658
  Epoch 020 - train 0.06869 | val 3.89331
  Epoch 021 - train 0.06787 | val 3.87934
  Classification -> best τ=0.495 (val F1=0.1909)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.15921 | val 1.34931
  Epoch 020 - train 0.05916 | val 1.72417
  Epoch 021 - train 0.06318 | val 1.75475
  Classification -> best τ=0.620 (val F1=0.2868)
  Directional -> Accuracy: 0.4219, MCC: -0.0284, F1: 0.0513

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.17797 | val 1.63547
  Epoch 020 - train 0.07967 | val 1.64898
  Epoch 021 - train 0.07394 | val 1.67688
  Classification -> best τ=0.560 (val F1=0.2937)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12731 | val 1.72847
  Epoch 020 - train 0.05606 | val 2.17289
  Epoch 021 - train 0.05884 | val 2.19877
  Classification -> best τ=0.430 (val F1=0.2295)
  Directional -> Accuracy: 0.5319, MCC: -0.0887, F1: 0.6667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15680 | val 1.28365
  Epoch 020 - train 0.06259 | val 1.61658
  Epoch 021 - train 0.06553 | val 1.62898
  Classification -> best τ=0.475 (val F1=0.2673)
  Directional -> Accuracy: 0.5077, MCC: 0.0066, F1: 0.6364

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.17808 | val 1.48384
  Epoch 020 - train 0.06810 | val 1.98152
  Epoch 022 - train 0.06560 | val 1.99084
  Classification -> best τ=0.655 (val F1=0.3294)
  Directional -> Accuracy: 0.4561, MCC: -0.0157, F1: 0.2791

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.19815 | val 1.59221
  Epoch 020 - train 0.09013 | val 2.33858
  Epoch 021 - train 0.09149 | val 2.32529
  Classification -> best τ=0.395 (val F1=0.1122)
  Directional -> Accuracy: 0.4769, MCC: -0.0082, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.18781 | val 1.76953
  Epoch 020 - train 0.08074 | val 2.10077
  Epoch 021 - train 0.08106 | val 2.12883
  Classification -> best τ=0.540 (val F1=0.3512)
  Directional -> Accuracy: 0.5091, MCC: 0.0913, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13878 | val 2.82705
  Epoch 020 - train 0.07400 | val 3.62945
  Epoch 021 - train 0.07299 | val 3.64444
  Classification -> best τ=0.520 (val F1=0.1981)
  Directional -> Accuracy: 0.4667, MCC: 0.1844, F1: 0.6129

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14923 | val 1.46406
  Epoch 020 - train 0.06479 | val 1.53249
  Epoch 021 - train 0.06296 | val 1.55432
  Classification -> best τ=0.410 (val F1=0.2582)
  Directional -> Accuracy: 0.5714, MCC: 0.0468, F1: 0.7097

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.16400 | val 1.57026
  Epoch 020 - train 0.07293 | val 1.92945
  Epoch 021 - train 0.06496 | val 1.94420
  Classification -> best τ=0.440 (val F1=0.0951)
  Directional -> Accuracy: 0.5000, MCC: 0.1552, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16927 | val 2.21183
  Epoch 020 - train 0.08436 | val 2.77916
  Epoch 021 - train 0.08444 | val 2.82713
  Classification -> best τ=0.525 (val F1=0.1448)
  Directional -> Accuracy: 0.4500, MCC: -0.0821, F1: 0.4211

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16931 | val 1.97924
  Epoch 020 - train 0.07590 | val 2.53485
  Epoch 021 - train 0.07608 | val 2.52694
  Classification -> best τ=0.505 (val F1=0.3501)
  Directional -> Accuracy: 0.5714, MCC: 0.1779, F1: 0.2500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.20685 | val 1.01514
  Epoch 020 - train 0.10422 | val 1.08213
  Epoch 021 - train 0.09717 | val 1.09073
  Classification -> best τ=0.505 (val F1=0.1707)
  Directional -> Accuracy: 0.5476, MCC: 0.0535, F1: 0.6545

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.20707 | val 1.46812
  Epoch 020 - train 0.10131 | val 1.85598
  Epoch 021 - train 0.10254 | val 1.86330
  Classification -> best τ=0.470 (val F1=0.2368)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.17214 | val 0.83924
  Epoch 020 - train 0.05496 | val 0.94228
  Epoch 022 - train 0.05398 | val 0.95518
  Classification -> best τ=0.515 (val F1=0.3260)
  Directional -> Accuracy: 0.4861, MCC: 0.0459, F1: 0.3273

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15816 | val 1.99771
  Epoch 020 - train 0.07301 | val 2.39386
  Epoch 021 - train 0.07368 | val 2.40155
  Classification -> best τ=0.440 (val F1=0.1874)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.17896 | val 1.04273
  Epoch 020 - train 0.08027 | val 1.30266
  Epoch 021 - train 0.07491 | val 1.33042
  Classification -> best τ=0.395 (val F1=0.2972)
  Directional -> Accuracy: 0.6212, MCC: 0.2658, F1: 0.6269

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08485 | val 1.21679
  Epoch 020 - train 0.03770 | val 1.69986
  Epoch 022 - train 0.02926 | val 1.72336
  Classification -> best τ=0.455 (val F1=0.3941)
  Directional -> Accuracy: 0.6190, MCC: 0.3091, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17297 | val 1.59981
  Epoch 020 - train 0.07365 | val 2.33243
  Epoch 021 - train 0.06988 | val 2.37626
  Classification -> best τ=0.435 (val F1=0.2541)
  Directional -> Accuracy: 0.4821, MCC: -0.0234, F1: 0.5085

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15550 | val 1.04171
  Epoch 020 - train 0.06669 | val 1.08297
  Epoch 021 - train 0.06802 | val 1.10606
  Classification -> best τ=0.575 (val F1=0.3497)
  Directional -> Accuracy: 0.4565, MCC: 0.0318, F1: 0.3590

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12593 | val 1.12012
  Epoch 020 - train 0.06452 | val 1.32043
  Epoch 021 - train 0.06331 | val 1.32188
  Classification -> best τ=0.545 (val F1=0.3378)
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16963 | val 2.51806
  Epoch 020 - train 0.06264 | val 3.44942
  Epoch 021 - train 0.06715 | val 3.49206
  Classification -> best τ=0.515 (val F1=0.1940)
  Directional -> Accuracy: 0.4865, MCC: -0.0165, F1: 0.5778

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17309 | val 1.66764
  Epoch 020 - train 0.08974 | val 2.13823
  Epoch 021 - train 0.08878 | val 2.13858
  Classification -> best τ=0.460 (val F1=0.1890)
  Directional -> Accuracy: 0.6222, MCC: 0.2731, F1: 0.5405

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13280 | val 1.26378
  Epoch 020 - train 0.08039 | val 1.44419
  Epoch 021 - train 0.08561 | val 1.44825
  Classification -> best τ=0.500 (val F1=0.2408)
  Directional -> Accuracy: 0.6429, MCC: 0.2513, F1: 0.7368

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17923 | val 1.44987
  Epoch 020 - train 0.09370 | val 1.73727
  Epoch 021 - train 0.09504 | val 1.75727
  Classification -> best τ=0.510 (val F1=0.1974)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.17334 | val 1.08908
  Epoch 020 - train 0.08473 | val 1.24737
  Epoch 021 - train 0.08042 | val 1.25274
  Classification -> best τ=0.490 (val F1=0.2694)
  Directional -> Accuracy: 0.4364, MCC: -0.1491, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14405 | val 2.52652
  Epoch 020 - train 0.05890 | val 3.09668
  Epoch 021 - train 0.05796 | val 3.09247
  Classification -> best τ=0.640 (val F1=0.3294)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.18727 | val 1.37450
  Epoch 020 - train 0.08561 | val 1.58398
  Epoch 021 - train 0.08312 | val 1.61537

[I 2026-02-19 01:27:21,438] Trial 35 finished with value: 0.25022983701433427 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.0007471804765489876, 'weight_decay': 1.8536779558168304e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.9980252685689724, 'early_stopping_min_delta': 0.0011774306729401937}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 021 - train 0.09671 | val 1.22644
  Classification -> best τ=0.535 (val F1=0.1072)
  Directional -> Accuracy: 0.5333, MCC: 0.0704, F1: 0.1765

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25022983701433427
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66163 | val 0.68369
  Epoch 016 - train 0.65074 | val 0.71139
  Classification -> best τ=0.525 (val F1=0.2135)
  Directional -> Accuracy: 0.5065, MCC: -0.0886, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64040 | val 0.68215
  Epoch 017 - train 0.63024 | val 0.72137
  Classification -> best τ=0.475 (val F1=0.1962)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67802 | val 0.68758
  Epoch 020 - train 0.66649 | val 0.67559
  Epoch 026 - train 0.65140 | val 0.68308
  Classification -> best τ=0.485 (val F1=0.2403)
  Directional -> Accuracy: 0.4043, MCC: -0.1864, F1: 0.2222

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66020 | val 1.70537
  Epoch 011 - train 0.66029 | val 1.75201
  Classification -> best τ=0.435 (val F1=0.1691)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65192 | val 0.69459
  Epoch 018 - train 0.64133 | val 0.73574
  Classification -> best τ=0.415 (val F1=0.4876)
  Directional -> Accuracy: 0.5294, MCC: 0.0556, F1: 0.5556

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67116 | val 0.70501
  Epoch 011 - train 0.66722 | val 0.71054
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67185 | val 0.70239
  Epoch 011 - train 0.66652 | val 0.70433
  Classification -> best τ=0.500 (val F1=0.0645)
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65615 | val 0.78220
  Epoch 011 - train 0.64349 | val 0.80265
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66693 | val 0.68655
  Epoch 011 - train 0.66082 | val 0.68623
  Classification -> best τ=0.480 (val F1=0.0857)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65110 | val 0.73920
  Epoch 014 - train 0.64919 | val 0.75624
  Classification -> best τ=0.515 (val F1=0.1974)
  Directional -> Accuracy: 0.4143, MCC: -0.1390, F1: 0.5859

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66113 | val 0.84925
  Epoch 011 - train 0.65974 | val 0.88632
  Classification -> best τ=0.495 (val F1=0.1375)
  Directional -> Accuracy: 0.5000, MCC: 0.0489, F1: 0.5902

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.66779 | val 0.76171
  Epoch 011 - train 0.66796 | val 0.77762
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.63961 | val 0.73557
  Epoch 011 - train 0.63939 | val 0.75483
  Classification -> best τ=0.515 (val F1=0.3135)
  Directional -> Accuracy: 0.3488, MCC: -0.3174, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67110 | val 0.69654
  Epoch 020 - train 0.66903 | val 0.65662
  Epoch 030 - train 0.64094 | val 0.64130
  Classification -> best τ=0.385 (val F1=0.4326)
  Directional -> Accuracy: 0.5738, MCC: 0.1844, F1: 0.6829

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67497 | val 0.84068
  Epoch 011 - train 0.66600 | val 0.87109
  Classification -> best τ=0.510 (val F1=0.1945)
  Directional -> Accuracy: 0.5385, MCC: 0.0223, F1: 0.1429

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67291 | val 0.71085
  Epoch 019 - train 0.65220 | val 0.72086
  Classification -> best τ=0.220 (val F1=0.2172)
  Directional -> Accuracy: 0.5857, MCC: 0.2306, F1: 0.7238

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65229 | val 0.94273
  Epoch 011 - train 0.65323 | val 0.99047
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67241 | val 1.11847
  Epoch 011 - train 0.66558 | val 1.17161
  Classification -> best τ=0.505 (val F1=0.0380)
  Directional -> Accuracy: 0.5789, MCC: 0.1980, F1: 0.5897

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65569 | val 0.69259
  Epoch 019 - train 0.64543 | val 0.69385
  Classification -> best τ=0.605 (val F1=0.2249)
  Directional -> Accuracy: 0.4154, MCC: -0.0306, F1: 0.0500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64555 | val 0.79691
  Epoch 014 - train 0.63832 | val 0.80130
  Classification -> best τ=0.515 (val F1=0.1859)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67465 | val 0.70609
  Epoch 011 - train 0.66638 | val 0.71294
  Classification -> best τ=0.525 (val F1=0.0268)
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67373 | val 0.71875
  Epoch 011 - train 0.66818 | val 0.72602
  Classification -> best τ=0.460 (val F1=0.2086)
  Directional -> Accuracy: 0.4545, MCC: -0.1085, F1: 0.2500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67742 | val 0.68686
  Epoch 017 - train 0.66616 | val 0.70561
  Classification -> best τ=0.560 (val F1=0.2379)
  Directional -> Accuracy: 0.4655, MCC: 0.0286, F1: 0.2791

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66553 | val 0.69970
  Epoch 016 - train 0.65038 | val 0.72723
  Classification -> best τ=0.500 (val F1=0.1111)
  Directional -> Accuracy: 0.5152, MCC: 0.0950, F1: 0.6279

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66405 | val 0.66368
  Epoch 020 - train 0.65185 | val 0.64729
  Epoch 030 - train 0.63347 | val 0.64555
  Classification -> best τ=0.460 (val F1=0.3730)
  Directional -> Accuracy: 0.6071, MCC: 0.2804, F1: 0.5417

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65533 | val 0.70397
  Epoch 011 - train 0.65809 | val 0.70856
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65869 | val 0.71858
  Epoch 011 - train 0.66332 | val 0.72330
  Classification -> best τ=0.480 (val F1=0.1309)
  Directional -> Accuracy: 0.4884, MCC: 0.0454, F1: 0.4211

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67359 | val 0.68668
  Epoch 011 - train 0.67292 | val 0.68676
  Classification -> best τ=0.480 (val F1=0.1568)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67395 | val 0.69563
  Epoch 011 - train 0.67752 | val 0.69581
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65583 | val 0.74855
  Epoch 011 - train 0.65247 | val 0.77074
  Classification -> best τ=0.540 (val F1=0.2683)
  Directional -> Accuracy: 0.5349, MCC: 0.0893, F1: 0.6154

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66703 | val 0.71498
  Epoch 011 - train 0.65144 | val 0.72035
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65279 | val 0.70411
  Epoch 011 - train 0.64966 | val 0.71056
  Classification -> best τ=0.520 (val F1=0.2454)
  Directional -> Accuracy: 0.5000, MCC: -0.0393, F1: 0.6032

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65923 | val 0.63680
  Epoch 020 - train 0.64222 | val 0.61575
  Epoch 030 - train 0.62832 | val 0.61525
  Classification -> best τ=0.395 (val F1=0.3773)
  Directional -> Accuracy: 0.5342, MCC: 0.1140, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.66252 | val 0.69965
  Epoch 011 - train 0.65222 | val 0.70184
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.66895 | val 0.73260
  Epoch 011 - train 0.66892 | val 0.74095
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64054 | val 0.67627
  Epoch 017 - train 0.62603 | val 0.68590
  Classification -> best τ=0.365 (val F1=0.3767)
  Directional -> Accuracy: 0.6119, MCC: 0.2757, F1: 0.5806

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67141 | val 0.69737
  Epoch 011 - train 0.66273 | val 0.69699
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.65544 | val 0.71042
  Epoch 015 - train 0.64557 | val 0.73289
  Classification -> best τ=0.505 (val F1=0.1508)
  Directional -> Accuracy: 0.5263, MCC: 0.1078, F1: 0.6301

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.66492 | val 0.73545
  Epoch 011 - train 0.65423 | val 0.74902
  Classification -> best τ=0.485 (val F1=0.0182)
  Directional -> Accuracy: 0.4468, MCC: 0.0497, F1: 0.3158

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67420 | val 0.67636
  Epoch 020 - train 0.64571 | val 0.63857
  Epoch 030 - train 0.63598 | val 0.62227
  Classification -> best τ=0.545 (val F1=0.3894)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.66295 | val 0.70378
  Epoch 011 - train 0.66751 | val 0.70635
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65593 | val 0.68921
  Epoch 017 - train 0.64402 | val 0.69476
  Classification -> best τ=0.405 (val F1=0.2265)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67252 | val 0.69041
  Epoch 011 - train 0.66704 | val 0.68906
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.65169 | val 0.71137
  Epoch 011 - train 0.64812 | val 0.71596
  Classification -> best τ=0.515 (val F1=0.3550)
  Directional -> Accuracy: 0.5682, MCC: 0.0435, F1: 0.7077

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66285 | val 0.72072
  Epoch 011 - train 0.65840 | val 0.72318
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68368 | val 0.70495
  Epoch 011 - train 0.67489 | val 0.70389
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65566 | val 0.71771
  Epoch 011 - train 0.65431 | val 0.73306
  Classification -> best τ=0.495 (val F1=0.1055)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65949 | val 0.72626
  Epoch 011 - train 0.66706 | val 0.73618
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.66815 | val 0.74023
  Epoch 011 - train 0.66156 | val 0.75097
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66863 | val 0.74426

[I 2026-02-19 01:30:10,646] Trial 36 finished with value: 0.1431311017141808 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 4.807716509737639e-05, 'weight_decay': 1.1954727370825302e-05, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1881839209276617, 'early_stopping_min_delta': 0.00279853362944612}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 011 - train 0.66463 | val 0.75899
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1431311017141808
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.49104 | val 0.77573
  Epoch 020 - train 0.40484 | val 1.03604
  Epoch 021 - train 0.38961 | val 1.05998
  Classification -> best τ=0.550 (val F1=0.2463)
  Directional -> Accuracy: 0.5513, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41119 | val 0.71144
  Epoch 020 - train 0.30416 | val 0.84600
  Epoch 021 - train 0.29132 | val 0.84836
  Classification -> best τ=0.475 (val F1=0.2346)
  Directional -> Accuracy: 0.5319, MCC: -0.1325, F1: 0.6944

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.46989 | val 0.90002
  Epoch 020 - train 0.26672 | val 1.19808
  Epoch 027 - train 0.22740 | val 1.37779
  Classification -> best τ=0.615 (val F1=0.3748)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.49793 | val 1.08199
  Epoch 020 - train 0.41302 | val 1.98307
  Epoch 021 - train 0.40640 | val 1.93473
  Classification -> best τ=0.485 (val F1=0.0392)
  Directional -> Accuracy: 0.4737, MCC: 0.0049, F1: 0.2308

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42614 | val 0.74593
  Epoch 020 - train 0.27184 | val 0.94159
  Epoch 026 - train 0.24918 | val 1.01345
  Classification -> best τ=0.605 (val F1=0.3578)
  Directional -> Accuracy: 0.6346, MCC: 0.2732, F1: 0.6415

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39401 | val 0.92985
  Epoch 020 - train 0.29598 | val 1.62011
  Epoch 021 - train 0.28544 | val 1.68243
  Classification -> best τ=0.540 (val F1=0.2604)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.48102 | val 0.84690
  Epoch 020 - train 0.35961 | val 1.18720
  Epoch 022 - train 0.34400 | val 1.23305
  Classification -> best τ=0.510 (val F1=0.1005)
  Directional -> Accuracy: 0.4429, MCC: -0.0262, F1: 0.5063

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.31148 | val 0.74213
  Epoch 020 - train 0.11213 | val 0.94593
  Epoch 030 - train 0.02771 | val 1.10533
  Epoch 036 - train 0.03339 | val 1.14801
  Classification -> best τ=0.155 (val F1=0.3162)
  Directional -> Accuracy: 0.4889, MCC: 0.0675, F1: 0.5660

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44427 | val 0.71108
  Epoch 020 - train 0.34129 | val 0.89662
  Epoch 021 - train 0.34648 | val 0.90408
  Classification -> best τ=0.520 (val F1=0.3467)
  Directional -> Accuracy: 0.5476, MCC: -0.0512, F1: 0.2400

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42230 | val 0.71581
  Epoch 020 - train 0.30563 | val 0.94522
  Epoch 022 - train 0.28062 | val 0.86660
  Classification -> best τ=0.465 (val F1=0.2359)
  Directional -> Accuracy: 0.4789, MCC: 0.0105, F1: 0.5432

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.40486 | val 0.72314
  Epoch 020 - train 0.22718 | val 1.14635
  Epoch 027 - train 0.19823 | val 1.33690
  Classification -> best τ=0.455 (val F1=0.3244)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.41742 | val 1.27590
  Epoch 020 - train 0.33450 | val 2.34583
  Epoch 021 - train 0.32932 | val 2.37752
  Classification -> best τ=0.405 (val F1=0.1748)
  Directional -> Accuracy: 0.5424, MCC: 0.1394, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42278 | val 1.35987
  Epoch 020 - train 0.33435 | val 3.04001
  Epoch 022 - train 0.32574 | val 3.26359
  Classification -> best τ=0.390 (val F1=0.1557)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.50437 | val 0.76677
  Epoch 020 - train 0.30142 | val 1.49191
  Epoch 026 - train 0.26635 | val 1.71312
  Classification -> best τ=0.550 (val F1=0.4274)
  Directional -> Accuracy: 0.6129, MCC: 0.2449, F1: 0.6757

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.38953 | val 0.94252
  Epoch 020 - train 0.22942 | val 1.32547
  Epoch 028 - train 0.18969 | val 1.52701
  Classification -> best τ=0.660 (val F1=0.3162)
  Directional -> Accuracy: 0.5472, MCC: 0.0756, F1: 0.3333

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.47797 | val 0.98832
  Epoch 020 - train 0.30476 | val 1.31695
  Epoch 024 - train 0.29108 | val 1.36935
  Classification -> best τ=0.645 (val F1=0.4569)
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43254 | val 0.85196
  Epoch 020 - train 0.32148 | val 1.10242
  Epoch 021 - train 0.31709 | val 1.13160
  Classification -> best τ=0.470 (val F1=0.1593)
  Directional -> Accuracy: 0.6333, MCC: 0.1337, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.45679 | val 1.53907
  Epoch 020 - train 0.35942 | val 3.11612
  Epoch 021 - train 0.34556 | val 3.10436
  Classification -> best τ=0.440 (val F1=0.1193)
  Directional -> Accuracy: 0.5325, MCC: -0.2323, F1: 0.6949

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.46577 | val 1.11039
  Epoch 020 - train 0.36738 | val 1.60792
  Epoch 021 - train 0.35662 | val 1.66667
  Classification -> best τ=0.400 (val F1=0.2409)
  Directional -> Accuracy: 0.5606, MCC: 0.2134, F1: 0.5085

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44967 | val 0.78104
  Epoch 020 - train 0.33879 | val 1.00763
  Epoch 022 - train 0.31107 | val 1.01464
  Classification -> best τ=0.500 (val F1=0.2637)
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42093 | val 0.87854
  Epoch 020 - train 0.24099 | val 1.72679
  Epoch 026 - train 0.21326 | val 1.93945
  Classification -> best τ=0.505 (val F1=0.3915)
  Directional -> Accuracy: 0.4694, MCC: 0.0469, F1: 0.4348

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43403 | val 0.94448
  Epoch 020 - train 0.33946 | val 1.19607
  Epoch 021 - train 0.32716 | val 1.21860
  Classification -> best τ=0.555 (val F1=0.1026)
  Directional -> Accuracy: 0.4776, MCC: -0.0754, F1: 0.0541

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46283 | val 0.90530
  Epoch 020 - train 0.33102 | val 1.28456
  Epoch 021 - train 0.32533 | val 1.33144
  Classification -> best τ=0.495 (val F1=0.2296)
  Directional -> Accuracy: 0.5763, MCC: 0.1680, F1: 0.5902

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47008 | val 0.77435
  Epoch 020 - train 0.30499 | val 0.89210
  Epoch 023 - train 0.28895 | val 0.91796
  Classification -> best τ=0.455 (val F1=0.1753)
  Directional -> Accuracy: 0.5075, MCC: 0.1677, F1: 0.6598

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.42907 | val 0.66869
  Epoch 020 - train 0.25266 | val 1.14831
  Epoch 028 - train 0.20233 | val 1.24660
  Classification -> best τ=0.470 (val F1=0.3304)
  Directional -> Accuracy: 0.4386, MCC: -0.3307, F1: 0.6098

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.36702 | val 0.86097
  Epoch 020 - train 0.30567 | val 1.44593
  Epoch 021 - train 0.29252 | val 1.52434
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.47880 | val 0.80116
  Epoch 020 - train 0.42093 | val 1.00200
  Epoch 021 - train 0.38605 | val 1.03835
  Classification -> best τ=0.465 (val F1=0.1775)
  Directional -> Accuracy: 0.6136, MCC: 0.1833, F1: 0.7536

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41805 | val 1.11910
  Epoch 020 - train 0.34718 | val 1.86975
  Epoch 021 - train 0.33318 | val 1.89196
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.40826 | val 0.68790
  Epoch 020 - train 0.29150 | val 0.88735
  Epoch 026 - train 0.26936 | val 1.04559
  Classification -> best τ=0.605 (val F1=0.2673)
  Directional -> Accuracy: 0.4651, MCC: -0.0593, F1: 0.4390

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43008 | val 0.84990
  Epoch 020 - train 0.31447 | val 1.14991
  Epoch 021 - train 0.31776 | val 1.17209
  Classification -> best τ=0.540 (val F1=0.1512)
  Directional -> Accuracy: 0.4889, MCC: -0.0199, F1: 0.4651

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44482 | val 0.76565
  Epoch 020 - train 0.35206 | val 0.93782
  Epoch 022 - train 0.34001 | val 0.98071
  Classification -> best τ=0.455 (val F1=0.2390)
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42008 | val 1.00375
  Epoch 020 - train 0.31355 | val 1.64967
  Epoch 021 - train 0.30407 | val 1.67382
  Classification -> best τ=0.465 (val F1=0.1199)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.42006 | val 1.65086
  Epoch 020 - train 0.31175 | val 3.23709
  Epoch 023 - train 0.29165 | val 3.29933
  Classification -> best τ=0.550 (val F1=0.3318)
  Directional -> Accuracy: 0.5541, MCC: 0.1330, F1: 0.5479

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.44398 | val 0.74588
  Epoch 020 - train 0.35343 | val 1.01042
  Epoch 021 - train 0.36302 | val 1.04517
  Classification -> best τ=0.435 (val F1=0.2145)
  Directional -> Accuracy: 0.5385, MCC: 0.1140, F1: 0.6400

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40832 | val 0.73361
  Epoch 020 - train 0.31521 | val 0.95361
  Epoch 021 - train 0.31645 | val 0.96494
  Classification -> best τ=0.445 (val F1=0.2500)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.47137 | val 1.00801
  Epoch 020 - train 0.36953 | val 1.20833
  Epoch 021 - train 0.37307 | val 1.21144
  Classification -> best τ=0.500 (val F1=0.2288)
  Directional -> Accuracy: 0.4706, MCC: -0.0120, F1: 0.4194

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40560 | val 0.65118
  Epoch 020 - train 0.22537 | val 0.98829
  Epoch 029 - train 0.17543 | val 1.09281
  Classification -> best τ=0.535 (val F1=0.4901)
  Directional -> Accuracy: 0.6136, MCC: 0.2334, F1: 0.5641

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40928 | val 1.14766
  Epoch 020 - train 0.33560 | val 1.60616
  Epoch 021 - train 0.33213 | val 1.59594
  Classification -> best τ=0.490 (val F1=0.1687)
  Directional -> Accuracy: 0.5000, MCC: 0.0347, F1: 0.5797

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43117 | val 0.83977
  Epoch 020 - train 0.32569 | val 1.11614
  Epoch 021 - train 0.33227 | val 1.07035
  Classification -> best τ=0.480 (val F1=0.2233)
  Directional -> Accuracy: 0.6042, MCC: -0.0222, F1: 0.7467

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.36195 | val 0.82271
  Epoch 020 - train 0.27009 | val 1.53761
  Epoch 021 - train 0.27978 | val 1.56870
  Classification -> best τ=0.455 (val F1=0.2067)
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.43147 | val 0.77409
  Epoch 020 - train 0.34631 | val 1.00623
  Epoch 021 - train 0.35089 | val 1.03857
  Classification -> best τ=0.465 (val F1=0.2467)
  Directional -> Accuracy: 0.5128, MCC: 0.0725, F1: 0.3871

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.46095 | val 1.00061
  Epoch 020 - train 0.32209 | val 2.17711
  Epoch 021 - train 0.33449 | val 2.20138
  Classification -> best τ=0.505 (val F1=0.2444)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.38930 | val 0.81208
  Epoch 020 - train 0.27085 | val 1.20757
  Epoch 021 - train 0.26221 | val 1.23922
  Classification -> best τ=0.550 (val F1=0.0245)
  Directional -> Accuracy: 0.3750, MCC: -0.2750, F1: 0.2105

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43823 | val 0.72204
  Epoch 020 - train 0.35974 | val 0.79266
  Epoch 021 - train 0.34751 | val 0.80595
  Classification -> best τ=0.480 (val F1=0.3371)
  Directional -> Accuracy: 0.5556, MCC: 0.0830, F1: 0.6296

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43057 | val 0.97086
  Epoch 020 - train 0.30857 | val 1.82051
  Epoch 021 - train 0.30332 | val 1.86672
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.44655 | val 0.81701
  Epoch 020 - train 0.35843 | val 0.92107
  Epoch 021 - train 0.36188 | val 0.92748
  Classification -> best τ=0.530 (val F1=0.1512)
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40526 | val 1.14492
  Epoch 020 - train 0.29271 | val 2.32971
  Epoch 023 - train 0.25911 | val 2.37625
  Classification -> best τ=0.540 (val F1=0.3350)
  Directional -> Accuracy: 0.5690, MCC: 0.2033, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.46139 | val 1.18233
  Epoch 020 - train 0.35978 | val 1.57097
  Epoch 021 - train 0.34741 | val 1.63378

[I 2026-02-19 01:31:47,587] Trial 37 finished with value: 0.22542385265444762 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 0.0020208166395994653, 'weight_decay': 4.927368384121244e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.12670211172874823, 'early_stopping_min_delta': 0.007907938235745274}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 020 - train 0.36495 | val 1.07863
  Epoch 021 - train 0.36327 | val 1.06561
  Classification -> best τ=0.510 (val F1=0.1970)
  Directional -> Accuracy: 0.3387, MCC: -0.3227, F1: 0.3279

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22542385265444762
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69056 | val 0.68581
  Epoch 020 - train 0.69533 | val 0.67758
  Epoch 030 - train 0.69498 | val 0.67244
  Classification -> best τ=0.415 (val F1=0.1430)
  Directional -> Accuracy: 0.5263, MCC: 0.1937, F1: 0.6400

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66219 | val 0.69984
  Epoch 020 - train 0.66671 | val 0.70941
  Epoch 025 - train 0.67722 | val 0.71303
  Classification -> best τ=0.480 (val F1=0.0230)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.72862 | val 0.68321
  Epoch 020 - train 0.69499 | val 0.67672
  Epoch 030 - train 0.67853 | val 0.67253
  Classification -> best τ=0.570 (val F1=0.2625)
  Directional -> Accuracy: 0.4783, MCC: -0.0093, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69766 | val 0.89591
  Epoch 020 - train 0.69286 | val 0.93881
  Epoch 021 - train 0.69913 | val 0.95564
  Classification -> best τ=0.490 (val F1=0.0116)
  Directional -> Accuracy: 0.4459, MCC: -0.0767, F1: 0.2807

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69297 | val 0.67765
  Epoch 020 - train 0.67315 | val 0.66172
  Epoch 030 - train 0.67154 | val 0.65279
  Classification -> best τ=0.500 (val F1=0.4247)
  Directional -> Accuracy: 0.6400, MCC: 0.3524, F1: 0.5263

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.72081 | val 0.91991
  Epoch 020 - train 0.71121 | val 0.91861
  Epoch 021 - train 0.69554 | val 0.92338
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71387 | val 0.70043
  Epoch 020 - train 0.69303 | val 0.68791
  Epoch 030 - train 0.69444 | val 0.68664
  Classification -> best τ=0.365 (val F1=0.2228)
  Directional -> Accuracy: 0.4412, MCC: 0.0509, F1: 0.5581

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.70510 | val 0.74752
  Epoch 020 - train 0.68969 | val 0.75907
  Epoch 021 - train 0.70930 | val 0.76382
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.70144 | val 0.72948
  Epoch 020 - train 0.70522 | val 0.73488
  Epoch 021 - train 0.68644 | val 0.73567
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69650 | val 0.78557
  Epoch 020 - train 0.70150 | val 0.79810
  Epoch 021 - train 0.67667 | val 0.79863
  Classification -> best τ=0.470 (val F1=0.1200)
  Directional -> Accuracy: 0.4783, MCC: -0.0921, F1: 0.3333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68278 | val 0.66640
  Epoch 020 - train 0.68529 | val 0.66974
  Epoch 027 - train 0.68027 | val 0.67145
  Classification -> best τ=0.430 (val F1=0.3075)
  Directional -> Accuracy: 0.5918, MCC: 0.1537, F1: 0.3750

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70672 | val 0.71774
  Epoch 020 - train 0.71026 | val 0.72119
  Epoch 021 - train 0.71057 | val 0.71872
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66729 | val 0.69269
  Epoch 020 - train 0.64625 | val 0.69445
  Epoch 026 - train 0.64317 | val 0.69402
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69667 | val 0.67527
  Epoch 020 - train 0.70100 | val 0.67207
  Epoch 030 - train 0.68752 | val 0.66936
  Classification -> best τ=0.490 (val F1=0.3407)
  Directional -> Accuracy: 0.5667, MCC: 0.1383, F1: 0.6176

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70076 | val 0.72060
  Epoch 020 - train 0.68828 | val 0.72916
  Epoch 021 - train 0.68873 | val 0.72862
  Classification -> best τ=0.505 (val F1=0.1455)
  Directional -> Accuracy: 0.4902, MCC: -0.0780, F1: 0.2778

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69299 | val 0.68510
  Epoch 020 - train 0.70253 | val 0.68714
  Epoch 030 - train 0.69219 | val 0.68050
  Classification -> best τ=0.490 (val F1=0.3063)
  Directional -> Accuracy: 0.4928, MCC: 0.0035, F1: 0.4444

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.70303 | val 0.74370
  Epoch 020 - train 0.69860 | val 0.75628
  Epoch 021 - train 0.67935 | val 0.75947
  Classification -> best τ=0.470 (val F1=0.0480)
  Directional -> Accuracy: 0.6897, MCC: 0.3671, F1: 0.7353

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68810 | val 0.79389
  Epoch 020 - train 0.69561 | val 0.80293
  Epoch 021 - train 0.68782 | val 0.81136
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.71890 | val 0.73560
  Epoch 020 - train 0.70382 | val 0.72841
  Epoch 021 - train 0.68475 | val 0.73165
  Classification -> best τ=0.555 (val F1=0.1112)
  Directional -> Accuracy: 0.4688, MCC: -0.1954, F1: 0.6136

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.71548 | val 0.75358
  Epoch 020 - train 0.69920 | val 0.71719
  Epoch 021 - train 0.70560 | val 0.71154
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69623 | val 0.72387
  Epoch 020 - train 0.65691 | val 0.72214
  Epoch 021 - train 0.68459 | val 0.72214
  Classification -> best τ=0.515 (val F1=0.0019)
  Directional -> Accuracy: 0.3830, MCC: -0.1897, F1: 0.3830

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69868 | val 0.68833
  Epoch 020 - train 0.68890 | val 0.68306
  Epoch 030 - train 0.68924 | val 0.68137
  Classification -> best τ=0.465 (val F1=0.2184)
  Directional -> Accuracy: 0.4462, MCC: -0.1341, F1: 0.5610

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71062 | val 0.69237
  Epoch 020 - train 0.70148 | val 0.69036
  Epoch 030 - train 0.68552 | val 0.69017
  Classification -> best τ=0.480 (val F1=0.3601)
  Directional -> Accuracy: 0.5088, MCC: -0.0353, F1: 0.6111

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68296 | val 0.86788
  Epoch 020 - train 0.69858 | val 0.86090
  Epoch 021 - train 0.71005 | val 0.84953
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.71196 | val 0.69355
  Epoch 020 - train 0.69708 | val 0.68308
  Epoch 030 - train 0.68313 | val 0.67503
  Classification -> best τ=0.475 (val F1=0.3426)
  Directional -> Accuracy: 0.5818, MCC: 0.2024, F1: 0.5306

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.66359 | val 0.72494
  Epoch 020 - train 0.69250 | val 0.75109
  Epoch 021 - train 0.65370 | val 0.75442
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71280 | val 0.74471
  Epoch 020 - train 0.71018 | val 0.74986
  Epoch 021 - train 0.71048 | val 0.74915
  Classification -> best τ=0.460 (val F1=0.1353)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.4211

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69663 | val 0.74439
  Epoch 020 - train 0.69273 | val 0.73815
  Epoch 021 - train 0.68600 | val 0.74246
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.67038 | val 0.69710
  Epoch 020 - train 0.68047 | val 0.71201
  Epoch 021 - train 0.68920 | val 0.70766
  Classification -> best τ=0.535 (val F1=0.2403)
  Directional -> Accuracy: 0.5250, MCC: 0.0553, F1: 0.5366

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69103 | val 0.69170
  Epoch 020 - train 0.68536 | val 0.69201
  Epoch 021 - train 0.70262 | val 0.69077
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70301 | val 0.72413
  Epoch 020 - train 0.70257 | val 0.73307
  Epoch 021 - train 0.68373 | val 0.73339
  Classification -> best τ=0.500 (val F1=0.0769)
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69536 | val 0.68904
  Epoch 020 - train 0.70510 | val 0.68603
  Epoch 030 - train 0.70617 | val 0.68227
  Classification -> best τ=0.455 (val F1=0.1829)
  Directional -> Accuracy: 0.5102, MCC: -0.0160, F1: 0.6250

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69128 | val 0.64620
  Epoch 020 - train 0.68958 | val 0.64637
  Epoch 028 - train 0.70306 | val 0.64917
  Classification -> best τ=0.470 (val F1=0.3583)
  Directional -> Accuracy: 0.5000, MCC: 0.1383, F1: 0.2500

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70525 | val 0.70363
  Epoch 020 - train 0.69682 | val 0.70914
  Epoch 021 - train 0.68974 | val 0.70962
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.70803 | val 0.71259
  Epoch 020 - train 0.69226 | val 0.70427
  Epoch 021 - train 0.68426 | val 0.70669
  Classification -> best τ=0.475 (val F1=0.0229)
  Directional -> Accuracy: 0.4091, MCC: -0.1445, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70090 | val 0.71336
  Epoch 020 - train 0.71647 | val 0.71452
  Epoch 021 - train 0.71636 | val 0.71426
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66886 | val 0.71772
  Epoch 020 - train 0.68505 | val 0.71824
  Epoch 021 - train 0.69092 | val 0.71360
  Classification -> best τ=0.500 (val F1=0.1048)
  Directional -> Accuracy: 0.4821, MCC: -0.0555, F1: 0.3830

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70240 | val 0.71614
  Epoch 020 - train 0.67971 | val 0.71856
  Epoch 021 - train 0.68391 | val 0.72470
  Classification -> best τ=0.525 (val F1=0.2197)
  Directional -> Accuracy: 0.5870, MCC: 0.0062, F1: 0.7246

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70210 | val 0.73411
  Epoch 020 - train 0.69120 | val 0.74149
  Epoch 021 - train 0.71076 | val 0.74078
  Classification -> best τ=0.520 (val F1=0.2231)
  Directional -> Accuracy: 0.6250, MCC: 0.1368, F1: 0.4000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68336 | val 0.68838
  Epoch 020 - train 0.67164 | val 0.69235
  Epoch 027 - train 0.67556 | val 0.69391
  Classification -> best τ=0.470 (val F1=0.2456)
  Directional -> Accuracy: 0.4459, MCC: -0.1068, F1: 0.4533

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.73947 | val 0.68926
  Epoch 020 - train 0.73342 | val 0.69237
  Epoch 021 - train 0.70910 | val 0.69205
  Classification -> best τ=0.470 (val F1=0.1890)
  Directional -> Accuracy: 0.5111, MCC: 0.0069, F1: 0.6562

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69965 | val 0.72270
  Epoch 020 - train 0.68795 | val 0.73113
  Epoch 021 - train 0.70815 | val 0.73305
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68912 | val 0.75334
  Epoch 020 - train 0.67821 | val 0.78364
  Epoch 021 - train 0.67817 | val 0.77876
  Classification -> best τ=0.490 (val F1=0.0842)
  Directional -> Accuracy: 0.3750, MCC: -0.0976, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70703 | val 0.70234
  Epoch 020 - train 0.69036 | val 0.69977
  Epoch 024 - train 0.69375 | val 0.70326
  Classification -> best τ=0.475 (val F1=0.1383)
  Directional -> Accuracy: 0.5818, MCC: 0.2024, F1: 0.5306

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68965 | val 0.75461
  Epoch 020 - train 0.67835 | val 0.75960
  Epoch 021 - train 0.68059 | val 0.75860
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69325 | val 0.69308
  Epoch 020 - train 0.69111 | val 0.69202
  Epoch 030 - train 0.67934 | val 0.69150
  Classification -> best τ=0.500 (val F1=0.1895)
  Directional -> Accuracy: 0.4340, MCC: -0.1325, F1: 0.4444

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69163 | val 0.81247
  Epoch 020 - train 0.69353 | val 0.89431
  Epoch 021 - train 0.69797 | val 0.88491
  Classification -> best τ=0.480 (val F1=0.1033)

[I 2026-02-19 01:35:30,713] Trial 38 finished with value: 0.1231027087455661 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 1.187043437042514e-05, 'weight_decay': 4.546140279943116e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.3298311773851525, 'early_stopping_min_delta': 0.002305775191748803}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 021 - train 0.69572 | val 0.69506
  Classification -> best τ=0.490 (val F1=0.0053)
  Directional -> Accuracy: 0.5167, MCC: 0.0509, F1: 0.5915

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1231027087455661
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62309 | val 0.69329
  Epoch 020 - train 0.31458 | val 1.27734
  Epoch 023 - train 0.27641 | val 1.48594
  Classification -> best τ=0.500 (val F1=0.3131)
  Directional -> Accuracy: 0.5325, MCC: 0.0617, F1: 0.5000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43865 | val 1.08397
  Epoch 016 - train 0.25764 | val 1.32255
  Classification -> best τ=0.420 (val F1=0.1307)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52229 | val 0.93975
  Epoch 020 - train 0.28085 | val 1.13922
  Epoch 022 - train 0.20589 | val 1.44998
  Classification -> best τ=0.630 (val F1=0.4063)
  Directional -> Accuracy: 0.5319, MCC: 0.0776, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.57426 | val 1.37795
  Epoch 020 - train 0.41136 | val 1.15996
  Epoch 021 - train 0.35468 | val 2.33444
  Classification -> best τ=0.325 (val F1=0.1283)
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69156 | val 0.64515
  Epoch 020 - train 0.35618 | val 1.12078
  Epoch 025 - train 0.10757 | val 1.36927
  Classification -> best τ=0.560 (val F1=0.4429)
  Directional -> Accuracy: 0.5686, MCC: 0.2079, F1: 0.4211

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.50745 | val 0.99994
  Epoch 016 - train 0.31918 | val 1.22957
  Classification -> best τ=0.500 (val F1=0.1644)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68379 | val 0.70078
  Epoch 020 - train 0.48523 | val 1.08220
  Epoch 026 - train 0.30227 | val 1.64608
  Classification -> best τ=0.580 (val F1=0.2287)
  Directional -> Accuracy: 0.6087, MCC: 0.1439, F1: 0.4000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.45495 | val 1.61163
  Epoch 016 - train 0.25440 | val 2.53120
  Classification -> best τ=0.475 (val F1=0.1752)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.53436 | val 1.59495
  Epoch 016 - train 0.32836 | val 3.15090
  Classification -> best τ=0.520 (val F1=0.2881)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.50621 | val 0.99571
  Epoch 016 - train 0.25588 | val 1.46879
  Classification -> best τ=0.410 (val F1=0.2241)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42555 | val 2.59220
  Epoch 016 - train 0.12975 | val 4.48237
  Classification -> best τ=0.560 (val F1=0.1166)
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48908 | val 1.63035
  Epoch 016 - train 0.26888 | val 2.30465
  Classification -> best τ=0.425 (val F1=0.2105)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0645

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61762 | val 0.79433
  Epoch 018 - train 0.28635 | val 2.73903
  Classification -> best τ=0.455 (val F1=0.2719)
  Directional -> Accuracy: 0.4419, MCC: -0.0375, F1: 0.5862

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.56937 | val 1.52878
  Epoch 016 - train 0.41934 | val 1.68494
  Classification -> best τ=0.530 (val F1=0.2739)
  Directional -> Accuracy: 0.4918, MCC: -0.0081, F1: 0.2791

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54843 | val 1.02582
  Epoch 018 - train 0.21117 | val 1.08972
  Classification -> best τ=0.410 (val F1=0.2684)
  Directional -> Accuracy: 0.5769, MCC: 0.1670, F1: 0.2143

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62536 | val 0.77505
  Epoch 017 - train 0.53214 | val 0.72484
  Classification -> best τ=0.595 (val F1=0.3738)
  Directional -> Accuracy: 0.5143, MCC: 0.0362, F1: 0.5143

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.54004 | val 0.82430
  Epoch 016 - train 0.28813 | val 2.21303
  Classification -> best τ=0.380 (val F1=0.1302)
  Directional -> Accuracy: 0.6102, MCC: -0.1013, F1: 0.7579

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56796 | val 0.99496
  Epoch 017 - train 0.38767 | val 2.02582
  Classification -> best τ=0.500 (val F1=0.1533)
  Directional -> Accuracy: 0.5921, MCC: 0.2187, F1: 0.6076

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.53496 | val 0.72724
  Epoch 018 - train 0.24233 | val 1.10193
  Classification -> best τ=0.350 (val F1=0.3068)
  Directional -> Accuracy: 0.5538, MCC: -0.0307, F1: 0.6947

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50425 | val 0.83176
  Epoch 016 - train 0.30118 | val 1.83111
  Classification -> best τ=0.505 (val F1=0.2691)
  Directional -> Accuracy: 0.4800, MCC: 0.1507, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57769 | val 2.35493
  Epoch 020 - train 0.13354 | val 2.19941
  Epoch 021 - train 0.09200 | val 2.65014
  Classification -> best τ=0.460 (val F1=0.3143)
  Directional -> Accuracy: 0.4583, MCC: -0.1080, F1: 0.5357

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62678 | val 0.81325
  Epoch 017 - train 0.33981 | val 1.25311
  Classification -> best τ=0.515 (val F1=0.1149)
  Directional -> Accuracy: 0.4697, MCC: -0.0620, F1: 0.4068

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.53419 | val 1.25274
  Epoch 017 - train 0.27301 | val 1.46227
  Classification -> best τ=0.585 (val F1=0.2971)
  Directional -> Accuracy: 0.5000, MCC: -0.0571, F1: 0.6027

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64367 | val 0.69843
  Epoch 020 - train 0.30396 | val 0.84977
  Epoch 021 - train 0.26275 | val 1.18355
  Classification -> best τ=0.390 (val F1=0.2694)
  Directional -> Accuracy: 0.5000, MCC: 0.0864, F1: 0.6374

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65823 | val 0.65616
  Epoch 020 - train 0.30147 | val 0.86679
  Epoch 023 - train 0.26105 | val 1.20167
  Classification -> best τ=0.520 (val F1=0.4297)
  Directional -> Accuracy: 0.5000, MCC: 0.0460, F1: 0.4167

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48009 | val 1.07750
  Epoch 016 - train 0.19615 | val 1.15112
  Classification -> best τ=0.470 (val F1=0.1925)
  Directional -> Accuracy: 0.4130, MCC: -0.1700, F1: 0.5846

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58540 | val 0.80177
  Epoch 020 - train 0.22879 | val 2.39479
  Epoch 026 - train 0.07211 | val 2.41868
  Classification -> best τ=0.595 (val F1=0.3680)
  Directional -> Accuracy: 0.5116, MCC: 0.0511, F1: 0.5116

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62012 | val 0.91827
  Epoch 016 - train 0.47787 | val 1.28022
  Classification -> best τ=0.455 (val F1=0.1656)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.53757 | val 0.80081
  Epoch 020 - train 0.11615 | val 0.91069
  Epoch 021 - train 0.08857 | val 1.14333
  Classification -> best τ=0.515 (val F1=0.3203)
  Directional -> Accuracy: 0.4878, MCC: -0.2104, F1: 0.6557

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42744 | val 1.99922
  Epoch 016 - train 0.16748 | val 4.24930
  Classification -> best τ=0.690 (val F1=0.1288)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.57104 | val 0.80305
  Epoch 019 - train 0.06711 | val 2.90579
  Classification -> best τ=0.795 (val F1=0.1667)
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.48055 | val 1.09189
  Epoch 017 - train 0.19512 | val 1.72868
  Classification -> best τ=0.460 (val F1=0.2461)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55639 | val 1.15291
  Epoch 016 - train 0.35803 | val 2.01465
  Classification -> best τ=0.485 (val F1=0.2924)
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.50728 | val 0.74669
  Epoch 017 - train 0.32227 | val 1.37837
  Classification -> best τ=0.395 (val F1=0.2928)
  Directional -> Accuracy: 0.5263, MCC: 0.0778, F1: 0.6538

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53159 | val 1.13196
  Epoch 020 - train 0.19132 | val 1.39251
  Classification -> best τ=0.685 (val F1=0.3103)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53761 | val 1.02666
  Epoch 017 - train 0.24363 | val 1.60456
  Classification -> best τ=0.290 (val F1=0.3266)
  Directional -> Accuracy: 0.5224, MCC: -0.0150, F1: 0.6279

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44888 | val 0.81167
  Epoch 016 - train 0.18922 | val 0.77175
  Classification -> best τ=0.525 (val F1=0.3536)
  Directional -> Accuracy: 0.5814, MCC: 0.2280, F1: 0.4000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.52986 | val 0.85998
  Epoch 017 - train 0.29747 | val 1.12968
  Classification -> best τ=0.435 (val F1=0.2693)
  Directional -> Accuracy: 0.5088, MCC: 0.0964, F1: 0.6410

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57940 | val 0.85707
  Epoch 018 - train 0.27799 | val 1.57647
  Classification -> best τ=0.480 (val F1=0.3568)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52061 | val 1.66549
  Epoch 018 - train 0.20613 | val 2.06802
  Classification -> best τ=0.565 (val F1=0.3125)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.52934 | val 1.13453
  Epoch 016 - train 0.40534 | val 1.41398
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57200 | val 0.71553
  Epoch 020 - train 0.38589 | val 1.41787
  Classification -> best τ=0.550 (val F1=0.2673)
  Directional -> Accuracy: 0.5067, MCC: 0.0499, F1: 0.6542

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58507 | val 0.69177
  Epoch 020 - train 0.13093 | val 2.26401
  Epoch 022 - train 0.10018 | val 3.21498
  Classification -> best τ=0.565 (val F1=0.3776)
  Directional -> Accuracy: 0.4894, MCC: -0.0045, F1: 0.0769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.50371 | val 1.03918
  Epoch 020 - train 0.28016 | val 2.26270
  Epoch 021 - train 0.24038 | val 2.21290
  Classification -> best τ=0.530 (val F1=0.3203)
  Directional -> Accuracy: 0.4318, MCC: -0.1821, F1: 0.5283

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53927 | val 0.93457
  Epoch 016 - train 0.36295 | val 1.55049
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.54940 | val 1.27588
  Epoch 016 - train 0.36623 | val 3.86195
  Classification -> best τ=0.630 (val F1=0.1622)
  Directional -> Accuracy: 0.6607, MCC: 0.3164, F1: 0.6885

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57342 | val 0.65909
  Epoch 020 - train 0.35709 | val 0.87346
  Epoch 025 - train 0.11302 | val 1.31600
  Classification -> best τ=0.390 (val F1=0.3027)
  Directional -> Accuracy: 0.4211, MCC: -0.1528, F1: 0.4407

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.51477 | val 1.25706
  Epoch 016 - train 0.26463 | val 2.03206
  Classification -> best τ=0.445 (val F1=0.1712)
  Directional -> Accuracy: 0.5926, MCC: 0.2085, F1: 0.6944

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.53016 | val 0.84695
  Epoch 020 - train 0.20366 | val 0.87738
  Epoch 022 - train 0.14987 | val 0.95964
  Classification -> best τ=0.455 (val F1=0.2829)
  Directional -> Accuracy: 0.4821, MCC: -0.1857, F1: 0.6506

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64428 | val 0.69116

[I 2026-02-19 01:37:01,303] Trial 39 finished with value: 0.25180650006822586 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 0.007226026920284312, 'weight_decay': 4.929431185274571e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5698774082299235, 'early_stopping_min_delta': 0.00041603495836095225}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 017 - train 0.48604 | val 0.74461
  Classification -> best τ=0.445 (val F1=0.3022)
  Directional -> Accuracy: 0.6230, MCC: 0.2665, F1: 0.6567

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25180650006822586
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.37162 | val 1.36739
  Epoch 020 - train 0.08378 | val 2.98776
  Classification -> best τ=0.460 (val F1=0.2262)
  Directional -> Accuracy: 0.4937, MCC: 0.0425, F1: 0.5652

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.35466 | val 0.86001
  Epoch 020 - train 0.07637 | val 1.40791
  Classification -> best τ=0.535 (val F1=0.1654)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.29897 | val 1.54772
  Epoch 020 - train 0.02652 | val 2.77077
  Classification -> best τ=0.500 (val F1=0.1319)
  Directional -> Accuracy: 0.4490, MCC: -0.1010, F1: 0.0690

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.41968 | val 1.26681
  Epoch 020 - train 0.07411 | val 1.94578
  Classification -> best τ=0.520 (val F1=0.1162)
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.33478 | val 0.68511
  Epoch 020 - train 0.02622 | val 1.57085
  Classification -> best τ=0.600 (val F1=0.3267)
  Directional -> Accuracy: 0.5094, MCC: 0.0338, F1: 0.4583

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.30539 | val 0.84665
  Epoch 020 - train 0.07330 | val 1.60130
  Classification -> best τ=0.465 (val F1=0.2460)
  Directional -> Accuracy: 0.4390, MCC: -0.1145, F1: 0.5965

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.52533 | val 0.79842
  Epoch 020 - train 0.07928 | val 1.92919
  Classification -> best τ=0.525 (val F1=0.2702)
  Directional -> Accuracy: 0.5070, MCC: -0.0041, F1: 0.4262

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.26864 | val 1.20967
  Epoch 020 - train 0.04462 | val 5.40974
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.34122 | val 0.96794
  Epoch 020 - train 0.02086 | val 2.22315
  Classification -> best τ=0.455 (val F1=0.3726)
  Directional -> Accuracy: 0.4884, MCC: -0.0928, F1: 0.3125

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45809 | val 1.08966
  Epoch 020 - train 0.05159 | val 1.93132
  Classification -> best τ=0.510 (val F1=0.1555)
  Directional -> Accuracy: 0.4861, MCC: -0.1437, F1: 0.1778

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.37635 | val 1.02957
  Epoch 020 - train 0.03711 | val 2.76180
  Classification -> best τ=0.495 (val F1=0.3161)
  Directional -> Accuracy: 0.6154, MCC: 0.3118, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.35696 | val 0.91867
  Epoch 020 - train 0.02483 | val 3.59546
  Classification -> best τ=0.490 (val F1=0.1898)
  Directional -> Accuracy: 0.5333, MCC: 0.1336, F1: 0.1765

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.25682 | val 0.77506
  Epoch 020 - train 0.01505 | val 2.55775
  Classification -> best τ=0.505 (val F1=0.0364)
  Directional -> Accuracy: 0.4889, MCC: -0.0714, F1: 0.2581

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.35636 | val 1.69482
  Epoch 020 - train 0.06812 | val 2.77266
  Classification -> best τ=0.530 (val F1=0.4287)
  Directional -> Accuracy: 0.4444, MCC: -0.1216, F1: 0.3396

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.33755 | val 0.93382
  Epoch 020 - train 0.05217 | val 3.04238
  Classification -> best τ=0.495 (val F1=0.2833)
  Directional -> Accuracy: 0.4444, MCC: -0.1052, F1: 0.5000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.33163 | val 1.45351
  Epoch 020 - train 0.07924 | val 2.68846
  Classification -> best τ=0.545 (val F1=0.2909)
  Directional -> Accuracy: 0.5000, MCC: 0.0117, F1: 0.4857

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.32777 | val 1.78445
  Epoch 020 - train 0.03987 | val 4.12220
  Classification -> best τ=0.545 (val F1=0.0293)
  Directional -> Accuracy: 0.4262, MCC: -0.1935, F1: 0.5205

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.41061 | val 1.32252
  Epoch 020 - train 0.08672 | val 3.43237
  Classification -> best τ=0.495 (val F1=0.1578)
  Directional -> Accuracy: 0.5641, MCC: 0.0799, F1: 0.6458

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.39421 | val 1.08139
  Epoch 020 - train 0.05033 | val 2.39637
  Classification -> best τ=0.370 (val F1=0.2933)
  Directional -> Accuracy: 0.4925, MCC: -0.0027, F1: 0.5143

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50263 | val 1.16120
  Epoch 020 - train 0.13472 | val 2.12718
  Classification -> best τ=0.485 (val F1=0.3227)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.30003 | val 1.26404
  Epoch 020 - train 0.03462 | val 3.56753
  Classification -> best τ=0.465 (val F1=0.2229)
  Directional -> Accuracy: 0.5800, MCC: -0.0355, F1: 0.7200

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.36082 | val 1.07373
  Epoch 020 - train 0.05956 | val 2.41405
  Classification -> best τ=0.480 (val F1=0.2420)
  Directional -> Accuracy: 0.4853, MCC: -0.0374, F1: 0.6067

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.32411 | val 1.20872
  Epoch 020 - train 0.03619 | val 2.18225
  Classification -> best τ=0.500 (val F1=0.2515)
  Directional -> Accuracy: 0.5167, MCC: 0.1107, F1: 0.4528

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.40170 | val 0.92250
  Epoch 020 - train 0.09205 | val 1.64887
  Classification -> best τ=0.460 (val F1=0.1215)
  Directional -> Accuracy: 0.4706, MCC: -0.1258, F1: 0.6400

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.32651 | val 0.98235
  Epoch 020 - train 0.04010 | val 1.92167
  Classification -> best τ=0.525 (val F1=0.4793)
  Directional -> Accuracy: 0.4655, MCC: -0.0061, F1: 0.2791

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17799 | val 0.88414
  Epoch 020 - train 0.00906 | val 1.92657
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.24621 | val 0.75233
  Epoch 020 - train 0.02087 | val 2.42672
  Classification -> best τ=0.480 (val F1=0.3425)
  Directional -> Accuracy: 0.6222, MCC: 0.2541, F1: 0.6531

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.38106 | val 1.64029
  Epoch 020 - train 0.08010 | val 2.73243
  Classification -> best τ=0.450 (val F1=0.1776)
  Directional -> Accuracy: 0.5424, MCC: 0.1741, F1: 0.4255

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.27562 | val 0.66473
  Epoch 020 - train 0.05695 | val 2.01441
  Classification -> best τ=0.385 (val F1=0.2908)
  Directional -> Accuracy: 0.5455, MCC: 0.1596, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.30685 | val 1.04468
  Epoch 020 - train 0.04189 | val 3.35713
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.41839 | val 0.79193
  Epoch 020 - train 0.12289 | val 1.96047
  Classification -> best τ=0.505 (val F1=0.1084)
  Directional -> Accuracy: 0.5217, MCC: -0.1366, F1: 0.6857

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.25480 | val 1.23124
  Epoch 020 - train 0.01300 | val 2.98325
  Classification -> best τ=0.485 (val F1=0.2689)
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.34910 | val 0.80444
  Epoch 020 - train 0.05571 | val 1.57567
  Classification -> best τ=0.545 (val F1=0.2551)
  Directional -> Accuracy: 0.4533, MCC: -0.0033, F1: 0.1961

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.25394 | val 0.75234
  Epoch 020 - train 0.01316 | val 1.77984
  Classification -> best τ=0.255 (val F1=0.3518)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.29017 | val 1.17042
  Epoch 020 - train 0.03043 | val 2.91658
  Classification -> best τ=0.470 (val F1=0.2421)
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.39229 | val 0.76720
  Epoch 020 - train 0.07807 | val 1.66726
  Classification -> best τ=0.490 (val F1=0.3271)
  Directional -> Accuracy: 0.5217, MCC: 0.0921, F1: 0.4923

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.27465 | val 0.80532
  Epoch 020 - train 0.04527 | val 1.86082
  Classification -> best τ=0.535 (val F1=0.2980)
  Directional -> Accuracy: 0.6444, MCC: 0.3291, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.31606 | val 0.98763
  Epoch 020 - train 0.07427 | val 2.92298
  Classification -> best τ=0.505 (val F1=0.1713)
  Directional -> Accuracy: 0.4407, MCC: -0.1075, F1: 0.5217

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.22970 | val 1.19922
  Epoch 020 - train 0.01504 | val 3.43141
  Classification -> best τ=0.515 (val F1=0.2807)
  Directional -> Accuracy: 0.5510, MCC: 0.1094, F1: 0.5926

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.37529 | val 0.77398
  Epoch 020 - train 0.03759 | val 2.08075
  Classification -> best τ=0.460 (val F1=0.3246)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.32981 | val 0.76843
  Epoch 020 - train 0.03770 | val 1.70879
  Classification -> best τ=0.535 (val F1=0.2988)
  Directional -> Accuracy: 0.6585, MCC: 0.3198, F1: 0.6500

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.38680 | val 1.54441
  Epoch 020 - train 0.05042 | val 2.96854
  Classification -> best τ=0.530 (val F1=0.1810)
  Directional -> Accuracy: 0.5325, MCC: 0.0648, F1: 0.5385

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.33970 | val 0.90473
  Epoch 020 - train 0.02168 | val 3.74719
  Classification -> best τ=0.580 (val F1=0.3990)
  Directional -> Accuracy: 0.5102, MCC: 0.0184, F1: 0.4783

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.29513 | val 1.05156
  Epoch 020 - train 0.04890 | val 2.60502
  Classification -> best τ=0.505 (val F1=0.2191)
  Directional -> Accuracy: 0.6383, MCC: 0.2357, F1: 0.7302

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.28338 | val 1.03635
  Epoch 020 - train 0.03591 | val 2.62951
  Classification -> best τ=0.535 (val F1=0.1677)
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40989 | val 0.71686
  Epoch 020 - train 0.04060 | val 3.25612
  Classification -> best τ=0.535 (val F1=0.1588)
  Directional -> Accuracy: 0.4655, MCC: 0.1194, F1: 0.0606

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.30176 | val 1.09132
  Epoch 020 - train 0.01523 | val 3.90099
  Classification -> best τ=0.560 (val F1=0.3257)
  Directional -> Accuracy: 0.5085, MCC: 0.0557, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.27067 | val 0.93110
  Epoch 020 - train 0.02660 | val 2.60658
  Classification -> best τ=0.490 (val F1=0.1878)
  Directional -> Accuracy: 0.5536, MCC: 0.1448, F1: 0.7059

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.39030 | val 1.06008
  Epoch 020 - train 0.07043 | val 3.08328
  Classification -> best τ=0.470 (val F1=0.1645)
  Directional -> Accuracy: 0.5345, MCC: 0.0860, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.38238 | val 0.74327

[I 2026-02-19 01:38:30,750] Trial 40 finished with value: 0.22935026501700886 and parameters: {'feature_set': 'emotion', 'model_type': 'BiLSTM', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.004004511883400609, 'weight_decay': 1.9949274732544777e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.558132753129745, 'early_stopping_min_delta': 0.004172075989880258}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 020 - train 0.06864 | val 1.49356
  Classification -> best τ=0.515 (val F1=0.2500)
  Directional -> Accuracy: 0.5556, MCC: 0.1008, F1: 0.3913

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.22935026501700886
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62435 | val 1.22410
  Epoch 020 - train 0.30840 | val 2.26468
  Classification -> best τ=0.470 (val F1=0.1137)
  Directional -> Accuracy: 0.4026, MCC: -0.2020, F1: 0.5577

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45363 | val 1.18011
  Epoch 017 - train 0.20084 | val 1.71049
  Classification -> best τ=0.510 (val F1=0.1236)
  Directional -> Accuracy: 0.5652, MCC: 0.2867, F1: 0.4118

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62174 | val 0.65162
  Epoch 020 - train 0.54420 | val 3.15601
  Epoch 026 - train 0.09153 | val 3.73640
  Classification -> best τ=0.545 (val F1=0.3898)
  Directional -> Accuracy: 0.5532, MCC: 0.1448, F1: 0.4615

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60296 | val 0.76224
  Epoch 016 - train 0.47256 | val 1.96201
  Classification -> best τ=0.415 (val F1=0.2163)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59637 | val 0.86085
  Epoch 017 - train 0.22970 | val 2.21164
  Classification -> best τ=0.560 (val F1=0.4427)
  Directional -> Accuracy: 0.4118, MCC: -0.1718, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36739 | val 1.32465
  Epoch 016 - train 0.16152 | val 2.65579
  Classification -> best τ=0.565 (val F1=0.3769)
  Directional -> Accuracy: 0.4681, MCC: -0.0687, F1: 0.6032

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57426 | val 1.00073
  Epoch 018 - train 0.49059 | val 1.04539
  Classification -> best τ=0.510 (val F1=0.2557)
  Directional -> Accuracy: 0.5362, MCC: 0.1618, F1: 0.5789

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50533 | val 1.57712
  Epoch 016 - train 0.31886 | val 2.42907
  Classification -> best τ=0.605 (val F1=0.3295)
  Directional -> Accuracy: 0.6136, MCC: 0.1417, F1: 0.1905

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.48975 | val 0.74633
  Epoch 020 - train 0.16837 | val 1.30673
  Classification -> best τ=0.425 (val F1=0.2129)
  Directional -> Accuracy: 0.5714, MCC: 0.3372, F1: 0.6769

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58325 | val 0.95679
  Epoch 018 - train 0.30556 | val 1.65709
  Classification -> best τ=0.465 (val F1=0.1717)
  Directional -> Accuracy: 0.4429, MCC: -0.0775, F1: 0.4800

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43158 | val 1.44721
  Epoch 016 - train 0.16619 | val 2.64189
  Classification -> best τ=0.545 (val F1=0.1750)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.52787 | val 0.90405
  Epoch 018 - train 0.32104 | val 3.40247
  Classification -> best τ=0.420 (val F1=0.2969)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.55076 | val 2.65334
  Epoch 020 - train 0.19804 | val 2.17038
  Epoch 022 - train 0.12335 | val 2.17299
  Classification -> best τ=0.660 (val F1=0.2631)
  Directional -> Accuracy: 0.5116, MCC: -0.0068, F1: 0.4000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.55743 | val 1.65472
  Epoch 018 - train 0.27534 | val 1.75651
  Classification -> best τ=0.345 (val F1=0.2314)
  Directional -> Accuracy: 0.5574, MCC: 0.1842, F1: 0.6897

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.47439 | val 0.87290
  Epoch 018 - train 0.09263 | val 3.06334
  Classification -> best τ=0.490 (val F1=0.2177)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.57980 | val 0.78206
  Epoch 020 - train 0.27182 | val 1.48094
  Epoch 022 - train 0.27236 | val 1.44922
  Classification -> best τ=0.380 (val F1=0.4271)
  Directional -> Accuracy: 0.5429, MCC: 0.0212, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.47367 | val 1.89826
  Epoch 017 - train 0.20291 | val 3.20114
  Classification -> best τ=0.710 (val F1=0.1558)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60650 | val 1.22816
  Epoch 017 - train 0.34215 | val 1.30780
  Classification -> best τ=0.470 (val F1=0.1340)
  Directional -> Accuracy: 0.5921, MCC: 0.1514, F1: 0.6593

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.55935 | val 0.68328
  Epoch 020 - train 0.19204 | val 0.88689
  Epoch 025 - train 0.08470 | val 1.13348
  Classification -> best τ=0.660 (val F1=0.2618)
  Directional -> Accuracy: 0.4615, MCC: 0.1854, F1: 0.1463

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47975 | val 1.15788
  Epoch 016 - train 0.40042 | val 1.11741
  Classification -> best τ=0.445 (val F1=0.1894)
  Directional -> Accuracy: 0.3867, MCC: -0.2316, F1: 0.4250

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54078 | val 0.76608
  Epoch 018 - train 0.20503 | val 2.59413
  Classification -> best τ=0.485 (val F1=0.2680)
  Directional -> Accuracy: 0.5208, MCC: -0.1516, F1: 0.6667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.62746 | val 0.77929
  Epoch 017 - train 0.39258 | val 1.53975
  Classification -> best τ=0.510 (val F1=0.2580)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6118

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62861 | val 0.74857
  Epoch 020 - train 0.39419 | val 1.26202
  Epoch 021 - train 0.32900 | val 1.41670
  Classification -> best τ=0.685 (val F1=0.4419)
  Directional -> Accuracy: 0.4655, MCC: -0.0371, F1: 0.4364

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57199 | val 1.90061
  Epoch 017 - train 0.23346 | val 3.22775
  Classification -> best τ=0.435 (val F1=0.1895)
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57569 | val 0.72186
  Epoch 020 - train 0.30143 | val 1.23935
  Epoch 024 - train 0.18160 | val 1.49965
  Classification -> best τ=0.560 (val F1=0.2864)
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46186 | val 1.10612
  Epoch 017 - train 0.14257 | val 1.24600
  Classification -> best τ=0.515 (val F1=0.3581)
  Directional -> Accuracy: 0.5652, MCC: 0.0782, F1: 0.3750

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49946 | val 0.67050
  Epoch 020 - train 0.11316 | val 1.41202
  Epoch 022 - train 0.07763 | val 1.98660
  Classification -> best τ=0.480 (val F1=0.4275)
  Directional -> Accuracy: 0.5581, MCC: 0.0269, F1: 0.6780

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59287 | val 0.93830
  Epoch 016 - train 0.50041 | val 1.27838
  Classification -> best τ=0.415 (val F1=0.1099)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57968 | val 0.69868
  Epoch 020 - train 0.44354 | val 0.70903
  Epoch 028 - train 0.14038 | val 1.11877
  Classification -> best τ=0.520 (val F1=0.5204)
  Directional -> Accuracy: 0.4878, MCC: -0.0416, F1: 0.5532

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.54586 | val 2.04641
  Epoch 017 - train 0.27105 | val 4.92018
  Classification -> best τ=0.720 (val F1=0.2683)
  Directional -> Accuracy: 0.4884, MCC: -0.0849, F1: 0.0833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.51582 | val 0.72486
  Epoch 019 - train 0.12763 | val 2.28361
  Classification -> best τ=0.650 (val F1=0.1667)
  Directional -> Accuracy: 0.4419, MCC: -0.0981, F1: 0.1429

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.51188 | val 0.79432
  Epoch 018 - train 0.11961 | val 2.13868
  Classification -> best τ=0.285 (val F1=0.3180)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55315 | val 0.67452
  Epoch 020 - train 0.32350 | val 0.74379
  Epoch 022 - train 0.27491 | val 0.86030
  Classification -> best τ=0.450 (val F1=0.3223)
  Directional -> Accuracy: 0.4384, MCC: -0.0299, F1: 0.0889

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.52468 | val 1.09394
  Epoch 017 - train 0.29041 | val 1.60296
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54240 | val 1.13119
  Epoch 016 - train 0.27785 | val 2.01476
  Classification -> best τ=0.480 (val F1=0.1902)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49849 | val 1.05706
  Epoch 020 - train 0.21684 | val 1.95298
  Epoch 022 - train 0.16478 | val 2.33632
  Classification -> best τ=0.300 (val F1=0.3759)
  Directional -> Accuracy: 0.5373, MCC: 0.1240, F1: 0.4918

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45381 | val 0.76832
  Epoch 016 - train 0.20793 | val 1.51622
  Classification -> best τ=0.470 (val F1=0.2443)
  Directional -> Accuracy: 0.6279, MCC: 0.3176, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49535 | val 1.12302
  Epoch 017 - train 0.18004 | val 2.25049
  Classification -> best τ=0.385 (val F1=0.2083)
  Directional -> Accuracy: 0.5263, MCC: 0.0596, F1: 0.5424

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.49750 | val 1.21525
  Epoch 020 - train 0.08594 | val 1.37797
  Epoch 022 - train 0.04692 | val 1.32524
  Classification -> best τ=0.500 (val F1=0.4096)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43643 | val 1.15146
  Epoch 018 - train 0.13658 | val 1.71462
  Classification -> best τ=0.430 (val F1=0.2128)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48757 | val 1.22734
  Epoch 016 - train 0.31439 | val 1.67939
  Classification -> best τ=0.505 (val F1=0.0134)
  Directional -> Accuracy: 0.4211, MCC: -0.1685, F1: 0.4762

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63909 | val 0.67757
  Epoch 018 - train 0.42712 | val 1.04720
  Classification -> best τ=0.540 (val F1=0.3002)
  Directional -> Accuracy: 0.5200, MCC: 0.0582, F1: 0.6250

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50998 | val 1.50361
  Epoch 016 - train 0.25801 | val 3.78673
  Classification -> best τ=0.435 (val F1=0.2585)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62114 | val 0.70882
  Epoch 020 - train 0.23720 | val 2.06264
  Epoch 023 - train 0.17204 | val 2.32057
  Classification -> best τ=0.315 (val F1=0.3595)
  Directional -> Accuracy: 0.5000, MCC: -0.2358, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.55157 | val 1.14594
  Epoch 017 - train 0.31960 | val 1.84711
  Classification -> best τ=0.515 (val F1=0.1903)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.53390 | val 1.57624
  Epoch 018 - train 0.22127 | val 1.94238
  Classification -> best τ=0.620 (val F1=0.2505)
  Directional -> Accuracy: 0.3393, MCC: -0.3646, F1: 0.4478

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54072 | val 1.27998
  Epoch 016 - train 0.27671 | val 1.86205
  Classification -> best τ=0.505 (val F1=0.1181)
  Directional -> Accuracy: 0.4386, MCC: -0.1225, F1: 0.5789

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.50191 | val 0.74778
  Epoch 018 - train 0.22197 | val 1.10258
  Classification -> best τ=0.460 (val F1=0.1712)
  Directional -> Accuracy: 0.5926, MCC: 0.1823, F1: 0.6207

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57710 | val 0.96162
  Epoch 016 - train 0.32370 | val 1.41932
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59005 | val 0.68546
  Epoch 020 - train 0.24329 | val 1.98718
  Epoch 022 - train 0.15627 | val 2.33477

[I 2026-02-19 01:40:02,023] Trial 41 finished with value: 0.24986113370817192 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 0.0071026302443741845, 'weight_decay': 4.425629991743544e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5474147096444643, 'early_stopping_min_delta': 0.00031363092843247756}. Best is trial 10 with value: 0.2688998415931245.

  Classification -> best τ=0.420 (val F1=0.2705)
  Directional -> Accuracy: 0.4918, MCC: -0.0940, F1: 0.1143

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24986113370817192
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60773 | val 0.92638
  Epoch 018 - train 0.47089 | val 1.36544
  Classification -> best τ=0.430 (val F1=0.0942)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46337 | val 1.01367
  Epoch 020 - train 0.20166 | val 1.69885
  Classification -> best τ=0.470 (val F1=0.1962)
  Directional -> Accuracy: 0.6522, MCC: 0.3438, F1: 0.6364

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.51377 | val 0.86032
  Epoch 018 - train 0.27394 | val 0.77401
  Classification -> best τ=0.535 (val F1=0.3345)
  Directional -> Accuracy: 0.5957, MCC: 0.2381, F1: 0.5128

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63339 | val 2.36559
  Epoch 016 - train 0.46920 | val 2.91769
  Classification -> best τ=0.365 (val F1=0.2163)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.61649 | val 0.65834
  Epoch 020 - train 0.38597 | val 1.40462
  Epoch 022 - train 0.38539 | val 1.28957
  Classification -> best τ=0.455 (val F1=0.4946)
  Directional -> Accuracy: 0.6275, MCC: 0.2745, F1: 0.5957

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54301 | val 1.09878
  Epoch 018 - train 0.29652 | val 1.91895
  Classification -> best τ=0.555 (val F1=0.3162)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62834 | val 0.77757
  Epoch 017 - train 0.40889 | val 1.09734
  Classification -> best τ=0.520 (val F1=0.3161)
  Directional -> Accuracy: 0.5072, MCC: 0.0231, F1: 0.4688

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48431 | val 1.32748
  Epoch 016 - train 0.35945 | val 2.09799
  Classification -> best τ=0.575 (val F1=0.3295)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59090 | val 0.79032
  Epoch 019 - train 0.30853 | val 1.25297
  Classification -> best τ=0.500 (val F1=0.2891)
  Directional -> Accuracy: 0.6327, MCC: 0.3303, F1: 0.3077

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56060 | val 0.71112
  Epoch 020 - train 0.28887 | val 0.95137
  Epoch 024 - train 0.16338 | val 0.89801
  Classification -> best τ=0.490 (val F1=0.2142)
  Directional -> Accuracy: 0.5857, MCC: 0.1390, F1: 0.0645

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.38272 | val 1.39177
  Epoch 016 - train 0.21420 | val 1.88665
  Classification -> best τ=0.635 (val F1=0.2010)
  Directional -> Accuracy: 0.6000, MCC: 0.2737, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50759 | val 1.32438
  Epoch 018 - train 0.24275 | val 1.96192
  Classification -> best τ=0.575 (val F1=0.1703)
  Directional -> Accuracy: 0.5862, MCC: 0.2381, F1: 0.3684

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56812 | val 0.82633
  Epoch 020 - train 0.29730 | val 1.05110
  Epoch 024 - train 0.19588 | val 1.08095
  Classification -> best τ=0.565 (val F1=0.2644)
  Directional -> Accuracy: 0.5116, MCC: 0.0153, F1: 0.4615

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67562 | val 0.66093
  Epoch 020 - train 0.58765 | val 0.70832
  Epoch 030 - train 0.41529 | val 1.28849
  Epoch 034 - train 0.34491 | val 0.81494
  Classification -> best τ=0.590 (val F1=0.3400)
  Directional -> Accuracy: 0.5246, MCC: 0.1811, F1: 0.1212

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40547 | val 1.43180
  Epoch 017 - train 0.19787 | val 2.28609
  Classification -> best τ=0.430 (val F1=0.0029)
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.58167 | val 0.64824
  Epoch 020 - train 0.35345 | val 0.85625
  Epoch 025 - train 0.19322 | val 1.27682
  Classification -> best τ=0.470 (val F1=0.4258)
  Directional -> Accuracy: 0.5143, MCC: 0.0166, F1: 0.5641

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59795 | val 0.96401
  Epoch 020 - train 0.31527 | val 1.39101
  Epoch 026 - train 0.08048 | val 1.82069
  Classification -> best τ=0.715 (val F1=0.1302)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56552 | val 0.82764
  Epoch 017 - train 0.35222 | val 2.32964
  Classification -> best τ=0.540 (val F1=0.1768)
  Directional -> Accuracy: 0.4342, MCC: 0.0710, F1: 0.1887

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56659 | val 0.66978
  Epoch 020 - train 0.20264 | val 1.29489
  Epoch 025 - train 0.04248 | val 1.53014
  Classification -> best τ=0.460 (val F1=0.4158)
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60551 | val 0.96379
  Epoch 017 - train 0.36280 | val 1.30360
  Classification -> best τ=0.590 (val F1=0.2366)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.46327 | val 2.01130
  Epoch 019 - train 0.12436 | val 22.02231
  Classification -> best τ=0.550 (val F1=0.3143)
  Directional -> Accuracy: 0.6042, MCC: -0.0222, F1: 0.7467

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63585 | val 0.96426
  Epoch 020 - train 0.39190 | val 1.36430
  Epoch 021 - train 0.38670 | val 1.12470
  Classification -> best τ=0.595 (val F1=0.3177)
  Directional -> Accuracy: 0.5303, MCC: 0.0741, F1: 0.3404

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54136 | val 0.85378
  Epoch 016 - train 0.34142 | val 1.21367
  Classification -> best τ=0.645 (val F1=0.3803)
  Directional -> Accuracy: 0.5862, MCC: 0.2545, F1: 0.5200

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61950 | val 0.76509
  Epoch 017 - train 0.49404 | val 1.33028
  Classification -> best τ=0.480 (val F1=0.0429)
  Directional -> Accuracy: 0.5455, MCC: 0.0861, F1: 0.1176

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67414 | val 0.66774
  Epoch 020 - train 0.46683 | val 0.83025
  Epoch 023 - train 0.38152 | val 1.07185
  Classification -> best τ=0.495 (val F1=0.3495)
  Directional -> Accuracy: 0.5000, MCC: 0.0460, F1: 0.4167

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51209 | val 0.72616
  Epoch 019 - train 0.22390 | val 1.01880
  Classification -> best τ=0.535 (val F1=0.2774)
  Directional -> Accuracy: 0.5870, MCC: 0.1164, F1: 0.2400

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50309 | val 1.19278
  Epoch 018 - train 0.20631 | val 1.37927
  Classification -> best τ=0.560 (val F1=0.1872)
  Directional -> Accuracy: 0.5116, MCC: 0.0197, F1: 0.5532

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59514 | val 1.05018
  Epoch 017 - train 0.39900 | val 1.57791
  Classification -> best τ=0.415 (val F1=0.2668)
  Directional -> Accuracy: 0.4912, MCC: 0.1491, F1: 0.2162

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.56765 | val 0.71848
  Epoch 020 - train 0.26165 | val 1.27510
  Classification -> best τ=0.495 (val F1=0.4708)
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.47318 | val 2.17840
  Epoch 016 - train 0.28865 | val 2.84266
  Classification -> best τ=0.615 (val F1=0.2683)
  Directional -> Accuracy: 0.5349, MCC: 0.1579, F1: 0.0909

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.55207 | val 1.19983
  Epoch 020 - train 0.14572 | val 2.71370
  Epoch 022 - train 0.09625 | val 3.11809
  Classification -> best τ=0.530 (val F1=0.2178)
  Directional -> Accuracy: 0.5349, MCC: 0.1193, F1: 0.4118

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.47628 | val 0.87389
  Epoch 016 - train 0.31243 | val 1.08280
  Classification -> best τ=0.380 (val F1=0.1955)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54607 | val 0.74175
  Epoch 020 - train 0.31118 | val 0.90468
  Classification -> best τ=0.400 (val F1=0.2794)
  Directional -> Accuracy: 0.5205, MCC: 0.1344, F1: 0.3860

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.56130 | val 0.91753
  Epoch 020 - train 0.30599 | val 1.18291
  Epoch 021 - train 0.27870 | val 1.27183
  Classification -> best τ=0.385 (val F1=0.2357)
  Directional -> Accuracy: 0.5263, MCC: 0.0976, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57995 | val 0.82646
  Epoch 020 - train 0.28596 | val 0.96750
  Epoch 022 - train 0.20945 | val 1.12756
  Classification -> best τ=0.445 (val F1=0.3000)
  Directional -> Accuracy: 0.5455, MCC: 0.1988, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.54209 | val 0.78506
  Epoch 016 - train 0.36495 | val 1.12737
  Classification -> best τ=0.290 (val F1=0.2715)
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45704 | val 1.17655
  Epoch 016 - train 0.28847 | val 1.93616
  Classification -> best τ=0.570 (val F1=0.2044)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56494 | val 1.18015
  Epoch 017 - train 0.28879 | val 3.12531
  Classification -> best τ=0.335 (val F1=0.2803)
  Directional -> Accuracy: 0.5439, MCC: 0.1810, F1: 0.6579

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51957 | val 1.92656
  Epoch 016 - train 0.27441 | val 3.35984
  Classification -> best τ=0.445 (val F1=0.3296)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49041 | val 0.84258
  Epoch 018 - train 0.26814 | val 1.29282
  Classification -> best τ=0.390 (val F1=0.2681)
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.54600 | val 0.84552
  Epoch 016 - train 0.46918 | val 1.07979
  Classification -> best τ=0.510 (val F1=0.2227)
  Directional -> Accuracy: 0.4211, MCC: -0.1685, F1: 0.4762

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57338 | val 0.85447
  Epoch 016 - train 0.44550 | val 1.26149
  Classification -> best τ=0.385 (val F1=0.2422)
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.51907 | val 1.21665
  Epoch 016 - train 0.39045 | val 2.28256
  Classification -> best τ=0.430 (val F1=0.3168)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46775 | val 1.44490
  Epoch 016 - train 0.35963 | val 1.00298
  Classification -> best τ=0.435 (val F1=0.2100)
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61415 | val 1.01966
  Epoch 020 - train 0.32722 | val 1.46160
  Epoch 022 - train 0.28066 | val 2.28537
  Classification -> best τ=0.435 (val F1=0.4714)
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.54736 | val 0.77907
  Epoch 020 - train 0.29652 | val 0.83431
  Epoch 023 - train 0.21107 | val 0.81693
  Classification -> best τ=0.650 (val F1=0.1850)
  Directional -> Accuracy: 0.4107, MCC: -0.1648, F1: 0.3265

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56534 | val 0.91352
  Epoch 020 - train 0.23035 | val 1.19663
  Epoch 023 - train 0.11357 | val 1.71815
  Classification -> best τ=0.235 (val F1=0.3147)
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59584 | val 0.90102
  Epoch 019 - train 0.34247 | val 1.04117
  Classification -> best τ=0.615 (val F1=0.1348)
  Directional -> Accuracy: 0.5741, MCC: 0.1839, F1: 0.4651

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63004 | val 1.35206
  Epoch 017 - train 0.47054 | val 1.43208
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.59284 | val 0.84395

[I 2026-02-19 01:41:33,101] Trial 42 finished with value: 0.2606045333541017 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 0.0058381394875615875, 'weight_decay': 0.00011708370972593947, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.5999249190040615, 'early_stopping_min_delta': 0.0006841648929653656}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 018 - train 0.33761 | val 1.16469
  Classification -> best τ=0.380 (val F1=0.3103)
  Directional -> Accuracy: 0.4918, MCC: 0.0647, F1: 0.6437

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2606045333541017
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65029 | val 0.97005
  Epoch 020 - train 0.43726 | val 1.69740
  Epoch 021 - train 0.44978 | val 1.74782
  Classification -> best τ=0.445 (val F1=0.2510)
  Directional -> Accuracy: 0.5526, MCC: 0.0174, F1: 0.0556

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56104 | val 0.73336
  Epoch 016 - train 0.38185 | val 0.93435
  Classification -> best τ=0.475 (val F1=0.3126)
  Directional -> Accuracy: 0.6222, MCC: 0.2523, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55780 | val 1.70183
  Epoch 017 - train 0.41832 | val 1.54164
  Classification -> best τ=0.600 (val F1=0.3114)
  Directional -> Accuracy: 0.4565, MCC: -0.1557, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66120 | val 1.25145
  Epoch 017 - train 0.59413 | val 0.72683
  Classification -> best τ=0.450 (val F1=0.0721)
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.64335 | val 0.79168
  Epoch 017 - train 0.44129 | val 1.77688
  Classification -> best τ=0.575 (val F1=0.5167)
  Directional -> Accuracy: 0.4600, MCC: -0.1487, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55505 | val 0.74760
  Epoch 016 - train 0.45071 | val 0.77891
  Classification -> best τ=0.520 (val F1=0.0194)
  Directional -> Accuracy: 0.5870, MCC: 0.2759, F1: 0.2400

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.68163 | val 0.69537
  Epoch 018 - train 0.57928 | val 0.74684
  Classification -> best τ=0.510 (val F1=0.1515)
  Directional -> Accuracy: 0.4412, MCC: -0.0669, F1: 0.4571

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53461 | val 0.60302
  Epoch 020 - train 0.22382 | val 1.47087
  Epoch 024 - train 0.15744 | val 1.71635
  Classification -> best τ=0.285 (val F1=0.2075)
  Directional -> Accuracy: 0.5000, MCC: 0.1698, F1: 0.6182

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58202 | val 0.95589
  Epoch 020 - train 0.29279 | val 3.80995
  Classification -> best τ=0.440 (val F1=0.2838)
  Directional -> Accuracy: 0.5208, MCC: 0.1690, F1: 0.6230

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62012 | val 0.70587
  Epoch 020 - train 0.62704 | val 1.08553
  Epoch 030 - train 0.34565 | val 0.92648
  Classification -> best τ=0.625 (val F1=0.2462)
  Directional -> Accuracy: 0.5797, MCC: 0.2142, F1: 0.6027

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59287 | val 0.73361
  Epoch 016 - train 0.49555 | val 0.76923
  Classification -> best τ=0.435 (val F1=0.2484)
  Directional -> Accuracy: 0.5918, MCC: 0.1635, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59267 | val 1.30321
  Epoch 017 - train 0.39332 | val 2.29754
  Classification -> best τ=0.380 (val F1=0.1518)
  Directional -> Accuracy: 0.5263, MCC: 0.0675, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62885 | val 0.73316
  Epoch 018 - train 0.44360 | val 2.78329
  Classification -> best τ=0.565 (val F1=0.1225)
  Directional -> Accuracy: 0.5952, MCC: 0.1758, F1: 0.3200

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65483 | val 0.62262
  Epoch 020 - train 0.56228 | val 0.92818
  Epoch 025 - train 0.43863 | val 0.66503
  Classification -> best τ=0.580 (val F1=0.3768)
  Directional -> Accuracy: 0.4833, MCC: -0.0603, F1: 0.1143

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59827 | val 0.70515
  Epoch 017 - train 0.49906 | val 0.77596
  Classification -> best τ=0.500 (val F1=0.2078)
  Directional -> Accuracy: 0.5686, MCC: 0.1084, F1: 0.1538

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69740 | val 0.67035
  Epoch 018 - train 0.69701 | val 0.69285
  Classification -> best τ=0.585 (val F1=0.2998)
  Directional -> Accuracy: 0.4638, MCC: -0.2162, F1: 0.6263

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64645 | val 1.46627
  Epoch 016 - train 0.49174 | val 2.25923
  Classification -> best τ=0.495 (val F1=0.0032)
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67065 | val 0.73917
  Epoch 020 - train 0.60468 | val 0.73103
  Epoch 023 - train 0.53956 | val 0.79536
  Classification -> best τ=0.605 (val F1=0.1909)
  Directional -> Accuracy: 0.4267, MCC: 0.0401, F1: 0.1569

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57813 | val 0.97940
  Epoch 016 - train 0.48754 | val 2.06166
  Classification -> best τ=0.445 (val F1=0.2433)
  Directional -> Accuracy: 0.5312, MCC: -0.0966, F1: 0.6809

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.61575 | val 0.70796
  Epoch 018 - train 0.46710 | val 0.90272
  Classification -> best τ=0.440 (val F1=0.2937)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61932 | val 0.71517
  Epoch 020 - train 0.50810 | val 1.22913
  Epoch 024 - train 0.37938 | val 1.65117
  Classification -> best τ=0.530 (val F1=0.3308)
  Directional -> Accuracy: 0.5532, MCC: -0.0497, F1: 0.6866

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63917 | val 0.78054
  Epoch 016 - train 0.59031 | val 0.94114
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62534 | val 0.73235
  Epoch 020 - train 0.38533 | val 1.24707
  Epoch 022 - train 0.36134 | val 1.63903
  Classification -> best τ=0.320 (val F1=0.3269)
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63156 | val 0.74340
  Epoch 016 - train 0.53265 | val 0.72125
  Classification -> best τ=0.450 (val F1=0.2056)
  Directional -> Accuracy: 0.5385, MCC: 0.1166, F1: 0.6250

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65856 | val 0.69961
  Epoch 020 - train 0.52482 | val 1.15054
  Epoch 029 - train 0.31401 | val 1.10794
  Classification -> best τ=0.480 (val F1=0.5472)
  Directional -> Accuracy: 0.4909, MCC: 0.0402, F1: 0.3333

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54702 | val 1.14742
  Epoch 016 - train 0.37389 | val 2.03914
  Classification -> best τ=0.595 (val F1=0.1310)
  Directional -> Accuracy: 0.5333, MCC: 0.0367, F1: 0.4324

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64960 | val 0.72799
  Epoch 018 - train 0.44995 | val 0.85884
  Classification -> best τ=0.535 (val F1=0.1750)
  Directional -> Accuracy: 0.4048, MCC: -0.1340, F1: 0.2424

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62998 | val 0.73426
  Epoch 016 - train 0.46392 | val 1.05596
  Classification -> best τ=0.505 (val F1=0.2110)
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.58731 | val 0.95661
  Epoch 016 - train 0.40795 | val 2.34007
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.63945 | val 0.76428
  Epoch 018 - train 0.49506 | val 0.74101
  Classification -> best τ=0.585 (val F1=0.3501)
  Directional -> Accuracy: 0.5238, MCC: 0.0455, F1: 0.5000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61426 | val 0.89272
  Epoch 020 - train 0.29221 | val 1.87813
  Classification -> best τ=0.425 (val F1=0.2357)
  Directional -> Accuracy: 0.5952, MCC: 0.1682, F1: 0.7018

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58357 | val 0.75135
  Epoch 016 - train 0.40600 | val 1.34206
  Classification -> best τ=0.435 (val F1=0.2599)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.65437 | val 0.69665
  Epoch 017 - train 0.52980 | val 0.74201
  Classification -> best τ=0.360 (val F1=0.3576)
  Directional -> Accuracy: 0.5278, MCC: 0.1179, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.62812 | val 1.07207
  Epoch 020 - train 0.41242 | val 1.57084
  Classification -> best τ=0.360 (val F1=0.1874)
  Directional -> Accuracy: 0.5581, MCC: 0.2676, F1: 0.6885

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67572 | val 0.72395
  Epoch 020 - train 0.50867 | val 1.24945
  Epoch 023 - train 0.48595 | val 1.20739
  Classification -> best τ=0.420 (val F1=0.3814)
  Directional -> Accuracy: 0.5758, MCC: 0.2503, F1: 0.5000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50067 | val 0.69341
  Epoch 020 - train 0.27613 | val 1.56375
  Epoch 028 - train 0.10848 | val 1.93848
  Classification -> best τ=0.485 (val F1=0.4416)
  Directional -> Accuracy: 0.6429, MCC: 0.2828, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56186 | val 0.76114
  Epoch 016 - train 0.40900 | val 0.93107
  Classification -> best τ=0.580 (val F1=0.1354)
  Directional -> Accuracy: 0.4821, MCC: -0.0437, F1: 0.4314

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61729 | val 0.68072
  Epoch 020 - train 0.34882 | val 1.05608
  Epoch 023 - train 0.22747 | val 2.10159
  Classification -> best τ=0.415 (val F1=0.3611)
  Directional -> Accuracy: 0.5870, MCC: -0.1195, F1: 0.7397

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67488 | val 0.69652
  Epoch 020 - train 0.52236 | val 0.76532
  Classification -> best τ=0.325 (val F1=0.3161)
  Directional -> Accuracy: 0.5000, MCC: 0.1572, F1: 0.5385

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67165 | val 0.69768
  Epoch 020 - train 0.42496 | val 0.84010
  Epoch 021 - train 0.41843 | val 0.87268
  Classification -> best τ=0.565 (val F1=0.2782)
  Directional -> Accuracy: 0.5000, MCC: 0.0230, F1: 0.6186

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62946 | val 0.69629
  Epoch 020 - train 0.35122 | val 1.98872
  Epoch 023 - train 0.26237 | val 2.47175
  Classification -> best τ=0.500 (val F1=0.3190)
  Directional -> Accuracy: 0.4889, MCC: -0.0181, F1: 0.4390

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60891 | val 0.85816
  Epoch 016 - train 0.57891 | val 0.94686
  Classification -> best τ=0.450 (val F1=0.2722)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63373 | val 0.91658
  Epoch 020 - train 0.48390 | val 0.87596
  Classification -> best τ=0.515 (val F1=0.2974)
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64793 | val 0.65528
  Epoch 020 - train 0.52440 | val 0.70891
  Epoch 029 - train 0.31193 | val 0.66073
  Classification -> best τ=0.545 (val F1=0.2786)
  Directional -> Accuracy: 0.4545, MCC: -0.0864, F1: 0.4643

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64757 | val 0.71341
  Epoch 020 - train 0.61146 | val 0.89984
  Classification -> best τ=0.500 (val F1=0.2386)
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68486 | val 0.69291
  Epoch 019 - train 0.54416 | val 0.83269
  Classification -> best τ=0.560 (val F1=0.2155)
  Directional -> Accuracy: 0.4906, MCC: -0.0091, F1: 0.2703

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67558 | val 0.71762
  Epoch 018 - train 0.57251 | val 0.81832
  Classification -> best τ=0.560 (val F1=0.3554)
  Directional -> Accuracy: 0.4727, MCC: -0.0289, F1: 0.2927

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64754 | val 0.69235

[I 2026-02-19 01:43:24,005] Trial 43 finished with value: 0.24739318155980153 and parameters: {'feature_set': 'finbert', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.009920424318807774, 'weight_decay': 0.00028844142659613424, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.7590265947390219, 'early_stopping_min_delta': 0.0010383834536643692}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 016 - train 0.54872 | val 0.87718
  Classification -> best τ=0.465 (val F1=0.1555)
  Directional -> Accuracy: 0.6167, MCC: 0.2668, F1: 0.4390

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24739318155980153
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.58117 | val 0.87404
  Epoch 020 - train 0.45239 | val 1.32738
  Classification -> best τ=0.605 (val F1=0.2349)
  Directional -> Accuracy: 0.5676, MCC: 0.1359, F1: 0.5429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55776 | val 0.93754
  Epoch 016 - train 0.51371 | val 1.02037
  Classification -> best τ=0.475 (val F1=0.1778)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.56720 | val 0.89896
  Epoch 017 - train 0.50311 | val 1.11376
  Classification -> best τ=0.525 (val F1=0.2733)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62562 | val 1.13078
  Epoch 016 - train 0.58631 | val 1.61041
  Classification -> best τ=0.340 (val F1=0.0951)
  Directional -> Accuracy: 0.5556, MCC: 0.1290, F1: 0.7091

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52366 | val 0.65337
  Epoch 020 - train 0.39998 | val 0.81429
  Epoch 022 - train 0.36351 | val 0.89037
  Classification -> best τ=0.465 (val F1=0.4568)
  Directional -> Accuracy: 0.6458, MCC: 0.3130, F1: 0.7213

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55780 | val 0.78240
  Epoch 017 - train 0.47038 | val 0.83005
  Classification -> best τ=0.455 (val F1=0.2392)
  Directional -> Accuracy: 0.4545, MCC: -0.0925, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64318 | val 0.70659
  Epoch 020 - train 0.52451 | val 0.68228
  Epoch 030 - train 0.43957 | val 0.81819
  Epoch 034 - train 0.40116 | val 0.79901
  Classification -> best τ=0.715 (val F1=0.3620)
  Directional -> Accuracy: 0.5909, MCC: 0.1046, F1: 0.3721

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58444 | val 1.35152
  Epoch 016 - train 0.52646 | val 1.48746
  Classification -> best τ=0.520 (val F1=0.1204)
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56524 | val 0.99809
  Epoch 016 - train 0.53447 | val 1.04413
  Classification -> best τ=0.520 (val F1=0.3660)
  Directional -> Accuracy: 0.5652, MCC: 0.1641, F1: 0.5833

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.56415 | val 0.79325
  Epoch 016 - train 0.49901 | val 0.85944
  Classification -> best τ=0.435 (val F1=0.2432)
  Directional -> Accuracy: 0.4030, MCC: -0.1453, F1: 0.5745

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.54346 | val 0.81485
  Epoch 016 - train 0.50482 | val 1.06658
  Classification -> best τ=0.515 (val F1=0.1871)
  Directional -> Accuracy: 0.5745, MCC: 0.1049, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56559 | val 0.88901
  Epoch 016 - train 0.48240 | val 1.11209
  Classification -> best τ=0.555 (val F1=0.1336)
  Directional -> Accuracy: 0.5273, MCC: 0.1727, F1: 0.2353

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53718 | val 0.77843
  Epoch 016 - train 0.49975 | val 0.90476
  Classification -> best τ=0.440 (val F1=0.2036)
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.6479

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58859 | val 0.87534
  Epoch 016 - train 0.56569 | val 1.01780
  Classification -> best τ=0.490 (val F1=0.0998)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.57059 | val 0.73408
  Epoch 020 - train 0.43478 | val 1.32483
  Epoch 023 - train 0.38877 | val 1.17030
  Classification -> best τ=0.560 (val F1=0.2065)
  Directional -> Accuracy: 0.5510, MCC: 0.1407, F1: 0.5926

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59480 | val 0.75907
  Epoch 017 - train 0.55266 | val 0.94229
  Classification -> best τ=0.410 (val F1=0.1105)
  Directional -> Accuracy: 0.5373, MCC: 0.0385, F1: 0.6517

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57795 | val 1.33919
  Epoch 016 - train 0.52374 | val 1.78009
  Classification -> best τ=0.510 (val F1=0.0230)
  Directional -> Accuracy: 0.5714, MCC: 0.1161, F1: 0.6364

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60185 | val 0.71672
  Epoch 016 - train 0.55704 | val 0.83153
  Classification -> best τ=0.585 (val F1=0.1041)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57891 | val 0.72168
  Epoch 019 - train 0.46901 | val 0.74528
  Classification -> best τ=0.440 (val F1=0.3056)
  Directional -> Accuracy: 0.5000, MCC: 0.1646, F1: 0.3111

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.59723 | val 0.78795
  Epoch 016 - train 0.53259 | val 0.78809
  Classification -> best τ=0.520 (val F1=0.1955)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48255 | val 0.89995
  Epoch 016 - train 0.40184 | val 1.39003
  Classification -> best τ=0.470 (val F1=0.3953)
  Directional -> Accuracy: 0.5778, MCC: 0.0962, F1: 0.6667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57562 | val 0.78548
  Epoch 016 - train 0.53498 | val 0.78102
  Classification -> best τ=0.465 (val F1=0.1537)
  Directional -> Accuracy: 0.5556, MCC: 0.1142, F1: 0.4400

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.58778 | val 0.82777
  Epoch 016 - train 0.55690 | val 0.88312
  Classification -> best τ=0.610 (val F1=0.2377)
  Directional -> Accuracy: 0.5273, MCC: 0.2085, F1: 0.3810

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57985 | val 0.73124
  Epoch 016 - train 0.55942 | val 0.77797
  Classification -> best τ=0.440 (val F1=0.1802)
  Directional -> Accuracy: 0.5556, MCC: 0.1028, F1: 0.4815

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61338 | val 0.66613
  Epoch 020 - train 0.43663 | val 1.21764
  Epoch 024 - train 0.37868 | val 1.44821
  Classification -> best τ=0.565 (val F1=0.3671)
  Directional -> Accuracy: 0.4528, MCC: -0.0271, F1: 0.1212

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56493 | val 0.77441
  Epoch 016 - train 0.51436 | val 0.83255
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57122 | val 1.15702
  Epoch 016 - train 0.52450 | val 1.26673
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.56149 | val 0.86714
  Epoch 017 - train 0.51111 | val 0.99026
  Classification -> best τ=0.415 (val F1=0.1139)
  Directional -> Accuracy: 0.5185, MCC: -0.1275, F1: 0.6829

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.57551 | val 1.23049
  Epoch 016 - train 0.51231 | val 1.47142
  Classification -> best τ=0.570 (val F1=0.2981)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54792 | val 0.84105
  Epoch 018 - train 0.48579 | val 1.08475
  Classification -> best τ=0.600 (val F1=0.1300)
  Directional -> Accuracy: 0.4500, MCC: -0.0658, F1: 0.3529

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60744 | val 0.62946
  Epoch 020 - train 0.44406 | val 0.81342
  Epoch 025 - train 0.34638 | val 0.91214
  Classification -> best τ=0.430 (val F1=0.5421)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58149 | val 0.77155
  Epoch 017 - train 0.50261 | val 1.10479
  Classification -> best τ=0.355 (val F1=0.2879)
  Directional -> Accuracy: 0.5286, MCC: 0.1080, F1: 0.4590

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.59695 | val 0.76979
  Epoch 016 - train 0.57630 | val 0.79268
  Classification -> best τ=0.445 (val F1=0.2576)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56944 | val 0.99132
  Epoch 016 - train 0.52902 | val 1.05189
  Classification -> best τ=0.340 (val F1=0.3397)
  Directional -> Accuracy: 0.5938, MCC: 0.1455, F1: 0.6905

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54027 | val 0.76836
  Epoch 018 - train 0.48737 | val 1.04373
  Classification -> best τ=0.495 (val F1=0.4105)
  Directional -> Accuracy: 0.6122, MCC: 0.2556, F1: 0.4571

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55787 | val 0.75362
  Epoch 016 - train 0.50328 | val 0.88438
  Classification -> best τ=0.475 (val F1=0.1842)
  Directional -> Accuracy: 0.5370, MCC: 0.1558, F1: 0.6377

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.56719 | val 0.83733
  Epoch 017 - train 0.45110 | val 1.08192
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60094 | val 0.68429
  Epoch 020 - train 0.45233 | val 0.72226
  Epoch 024 - train 0.41898 | val 0.71338
  Classification -> best τ=0.540 (val F1=0.3006)
  Directional -> Accuracy: 0.6222, MCC: -0.0552, F1: 0.1053

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57128 | val 1.22085
  Epoch 016 - train 0.51098 | val 1.57112
  Classification -> best τ=0.495 (val F1=0.0839)
  Directional -> Accuracy: 0.5139, MCC: 0.1187, F1: 0.6729

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57144 | val 0.71173
  Epoch 018 - train 0.50453 | val 0.73964
  Classification -> best τ=0.475 (val F1=0.2212)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56902 | val 0.70977
  Epoch 016 - train 0.49689 | val 0.79275
  Classification -> best τ=0.500 (val F1=0.2660)
  Directional -> Accuracy: 0.6923, MCC: 0.3475, F1: 0.7600

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.57150 | val 0.98868
  Epoch 016 - train 0.52119 | val 0.96216
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60435 | val 0.72030
  Epoch 020 - train 0.46245 | val 0.76182
  Epoch 023 - train 0.41580 | val 0.76577
  Classification -> best τ=0.705 (val F1=0.1984)
  Directional -> Accuracy: 0.5094, MCC: 0.2228, F1: 0.1875

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55264 | val 1.55491
  Epoch 016 - train 0.51307 | val 1.64138
  Classification -> best τ=0.465 (val F1=0.1754)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59545 | val 0.75918
  Epoch 020 - train 0.44927 | val 1.63841
  Epoch 028 - train 0.36288 | val 1.79542
  Classification -> best τ=0.510 (val F1=0.2714)
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.58908 | val 1.25040
  Epoch 016 - train 0.54175 | val 1.37442
  Classification -> best τ=0.565 (val F1=0.2457)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.58218 | val 0.78031

[I 2026-02-19 01:45:39,230] Trial 44 finished with value: 0.21044991962596393 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'GRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 0.0012415242857922836, 'weight_decay': 8.688094729323795e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 0.3384850329597924, 'early_stopping_min_delta': 0.0015928850552758016}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 016 - train 0.52595 | val 0.74884
  Classification -> best τ=0.395 (val F1=0.0925)
  Directional -> Accuracy: 0.4483, MCC: -0.1701, F1: 0.2000

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21044991962596393
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.59494 | val 0.86015
  Epoch 016 - train 0.55749 | val 0.92569
  Classification -> best τ=0.590 (val F1=0.1352)
  Directional -> Accuracy: 0.5067, MCC: -0.0890, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.57555 | val 1.02873
  Epoch 018 - train 0.52278 | val 1.28455
  Classification -> best τ=0.430 (val F1=0.0617)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57837 | val 0.79626
  Epoch 020 - train 0.45713 | val 0.97730
  Epoch 021 - train 0.47584 | val 0.99076
  Classification -> best τ=0.530 (val F1=0.4237)
  Directional -> Accuracy: 0.4222, MCC: -0.1774, F1: 0.0714

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.60824 | val 1.57855
  Epoch 016 - train 0.57966 | val 1.83891
  Classification -> best τ=0.555 (val F1=0.1880)
  Directional -> Accuracy: 0.6301, MCC: 0.2517, F1: 0.6824

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50875 | val 0.76818
  Epoch 018 - train 0.45235 | val 0.88335
  Classification -> best τ=0.500 (val F1=0.4313)
  Directional -> Accuracy: 0.5306, MCC: 0.0589, F1: 0.5660

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.57710 | val 0.77642
  Epoch 016 - train 0.53842 | val 0.84468
  Classification -> best τ=0.490 (val F1=0.2198)
  Directional -> Accuracy: 0.5111, MCC: 0.0199, F1: 0.4762

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63136 | val 0.68049
  Epoch 020 - train 0.53944 | val 0.87973
  Epoch 026 - train 0.47290 | val 0.92844
  Classification -> best τ=0.215 (val F1=0.3021)
  Directional -> Accuracy: 0.4030, MCC: 0.0000, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.60090 | val 1.38456
  Epoch 017 - train 0.47776 | val 1.96101
  Classification -> best τ=0.540 (val F1=0.0529)
  Directional -> Accuracy: 0.4390, MCC: -0.0885, F1: 0.4889

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55903 | val 0.67796
  Epoch 020 - train 0.42699 | val 0.89980
  Epoch 025 - train 0.37631 | val 1.02643
  Classification -> best τ=0.520 (val F1=0.3687)
  Directional -> Accuracy: 0.6383, MCC: 0.2719, F1: 0.6047

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55587 | val 0.73552
  Epoch 016 - train 0.50728 | val 0.81041
  Classification -> best τ=0.440 (val F1=0.1531)
  Directional -> Accuracy: 0.3971, MCC: -0.1566, F1: 0.4810

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56674 | val 1.04444
  Epoch 018 - train 0.49618 | val 1.74017
  Classification -> best τ=0.575 (val F1=0.3550)
  Directional -> Accuracy: 0.6042, MCC: 0.1948, F1: 0.4242

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55921 | val 0.94576
  Epoch 016 - train 0.53656 | val 1.22634
  Classification -> best τ=0.525 (val F1=0.0103)
  Directional -> Accuracy: 0.5893, MCC: 0.1857, F1: 0.6761

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52307 | val 1.73707
  Epoch 016 - train 0.49638 | val 2.39764
  Classification -> best τ=0.520 (val F1=0.0462)
  Directional -> Accuracy: 0.5102, MCC: 0.0500, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58592 | val 0.79818
  Epoch 019 - train 0.49632 | val 1.11114
  Classification -> best τ=0.340 (val F1=0.2169)
  Directional -> Accuracy: 0.5763, MCC: 0.2743, F1: 0.7059

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.55430 | val 0.72815
  Epoch 018 - train 0.48593 | val 0.89796
  Classification -> best τ=0.510 (val F1=0.1033)
  Directional -> Accuracy: 0.5400, MCC: -0.1266, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59024 | val 0.90002
  Epoch 016 - train 0.56472 | val 1.12053
  Classification -> best τ=0.560 (val F1=0.3581)
  Directional -> Accuracy: 0.5147, MCC: 0.0177, F1: 0.5714

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59861 | val 1.36027
  Epoch 016 - train 0.57183 | val 1.65954
  Classification -> best τ=0.590 (val F1=0.2265)
  Directional -> Accuracy: 0.4035, MCC: -0.0089, F1: 0.1500

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60873 | val 1.15889
  Epoch 020 - train 0.50935 | val 1.93137
  Classification -> best τ=0.365 (val F1=0.2377)
  Directional -> Accuracy: 0.6081, MCC: 0.1447, F1: 0.7071

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57280 | val 0.97114
  Epoch 018 - train 0.49953 | val 1.21701
  Classification -> best τ=0.340 (val F1=0.2822)
  Directional -> Accuracy: 0.4921, MCC: 0.1308, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62119 | val 0.68858
  Epoch 020 - train 0.50990 | val 0.75712
  Classification -> best τ=0.620 (val F1=0.2785)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.49038 | val 0.98211
  Epoch 016 - train 0.45842 | val 1.06089
  Classification -> best τ=0.495 (val F1=0.1679)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58607 | val 1.00568
  Epoch 016 - train 0.54109 | val 1.01198
  Classification -> best τ=0.445 (val F1=0.2149)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60385 | val 1.10498
  Epoch 016 - train 0.53610 | val 1.31743
  Classification -> best τ=0.660 (val F1=0.3062)
  Directional -> Accuracy: 0.5179, MCC: 0.1009, F1: 0.4490

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.58997 | val 0.75185
  Epoch 016 - train 0.55092 | val 0.80412
  Classification -> best τ=0.440 (val F1=0.2149)
  Directional -> Accuracy: 0.5781, MCC: 0.2105, F1: 0.6494

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.56342 | val 0.70188
  Epoch 020 - train 0.47473 | val 0.93180
  Epoch 021 - train 0.45314 | val 0.87163
  Classification -> best τ=0.670 (val F1=0.3669)
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54645 | val 0.86701
  Epoch 017 - train 0.52240 | val 0.97510
  Classification -> best τ=0.530 (val F1=0.1852)
  Directional -> Accuracy: 0.5116, MCC: -0.0889, F1: 0.2222

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49609 | val 1.16704
  Epoch 016 - train 0.52338 | val 1.20132
  Classification -> best τ=0.460 (val F1=0.2534)
  Directional -> Accuracy: 0.6122, MCC: 0.1798, F1: 0.6885

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59317 | val 1.01755
  Epoch 017 - train 0.50306 | val 1.20506
  Classification -> best τ=0.450 (val F1=0.2995)
  Directional -> Accuracy: 0.5273, MCC: 0.2023, F1: 0.2778

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.57793 | val 0.77036
  Epoch 016 - train 0.50527 | val 0.85138
  Classification -> best τ=0.550 (val F1=0.1724)
  Directional -> Accuracy: 0.5526, MCC: 0.0458, F1: 0.6792

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60996 | val 0.80110
  Epoch 016 - train 0.57435 | val 0.88514
  Classification -> best τ=0.535 (val F1=0.2617)
  Directional -> Accuracy: 0.5122, MCC: 0.0080, F1: 0.1667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58133 | val 0.86890
  Epoch 017 - train 0.52233 | val 1.08785
  Classification -> best τ=0.480 (val F1=0.0720)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.57484 | val 0.69694
  Epoch 020 - train 0.45646 | val 0.86632
  Epoch 022 - train 0.45260 | val 0.78697
  Classification -> best τ=0.355 (val F1=0.3713)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.55077 | val 1.01949
  Epoch 018 - train 0.50777 | val 1.42877
  Classification -> best τ=0.345 (val F1=0.3449)
  Directional -> Accuracy: 0.5634, MCC: 0.1733, F1: 0.5231

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57603 | val 0.81850
  Epoch 016 - train 0.53776 | val 0.85282
  Classification -> best τ=0.580 (val F1=0.3375)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56253 | val 0.83275
  Epoch 016 - train 0.53193 | val 0.93959
  Classification -> best τ=0.475 (val F1=0.4004)
  Directional -> Accuracy: 0.5692, MCC: 0.1070, F1: 0.6410

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52541 | val 0.75250
  Epoch 019 - train 0.43861 | val 0.97523
  Classification -> best τ=0.380 (val F1=0.2697)
  Directional -> Accuracy: 0.7250, MCC: 0.4579, F1: 0.7179

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56007 | val 0.71342
  Epoch 016 - train 0.52132 | val 0.75586
  Classification -> best τ=0.495 (val F1=0.1796)
  Directional -> Accuracy: 0.4727, MCC: -0.0404, F1: 0.4912

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51758 | val 1.43314
  Epoch 016 - train 0.46669 | val 2.23778
  Classification -> best τ=0.500 (val F1=0.0124)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59562 | val 0.71749
  Epoch 020 - train 0.45576 | val 0.80098
  Epoch 022 - train 0.46679 | val 0.82908
  Classification -> best τ=0.665 (val F1=0.3139)
  Directional -> Accuracy: 0.3043, MCC: -0.2217, F1: 0.4074

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.54760 | val 1.72003
  Epoch 016 - train 0.50828 | val 2.35109
  Classification -> best τ=0.520 (val F1=0.1642)
  Directional -> Accuracy: 0.5753, MCC: 0.1556, F1: 0.6076

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58428 | val 0.82589
  Epoch 019 - train 0.47275 | val 0.88770
  Classification -> best τ=0.535 (val F1=0.3536)
  Directional -> Accuracy: 0.5227, MCC: 0.1525, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57469 | val 0.67093
  Epoch 020 - train 0.42443 | val 0.66336
  Epoch 029 - train 0.31523 | val 0.73973
  Classification -> best τ=0.635 (val F1=0.3568)
  Directional -> Accuracy: 0.4878, MCC: 0.0049, F1: 0.4878

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.58525 | val 0.79103
  Epoch 016 - train 0.52773 | val 0.78905
  Classification -> best τ=0.455 (val F1=0.0608)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.58983 | val 1.10068
  Epoch 016 - train 0.57286 | val 1.32519
  Classification -> best τ=0.430 (val F1=0.1657)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57273 | val 1.08091
  Epoch 016 - train 0.53699 | val 1.37258
  Classification -> best τ=0.450 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.60712 | val 0.67846
  Epoch 020 - train 0.50894 | val 0.79215
  Epoch 021 - train 0.47444 | val 0.79707
  Classification -> best τ=0.630 (val F1=0.2037)
  Directional -> Accuracy: 0.5385, MCC: 0.0791, F1: 0.5862

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56968 | val 0.67362
  Epoch 020 - train 0.47163 | val 0.71136
  Epoch 021 - train 0.43468 | val 0.97679
  Classification -> best τ=0.275 (val F1=0.2397)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60296 | val 1.03060

[I 2026-02-19 01:47:31,426] Trial 45 finished with value: 0.23217450419352526 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 0.002380568679776028, 'weight_decay': 0.0006190225244673708, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.6729082842629627, 'early_stopping_min_delta': 3.722304406741407e-08}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 016 - train 0.52267 | val 1.39583
  Classification -> best τ=0.495 (val F1=0.1577)
  Directional -> Accuracy: 0.5254, MCC: 0.0685, F1: 0.5758

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23217450419352526
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: classification
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.49266 | val 1.24039
  Epoch 011 - train 0.45035 | val 1.00438
  Classification -> best τ=0.475 (val F1=0.1886)
  Directional -> Accuracy: 0.4675, MCC: -0.0571, F1: 0.4675

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.37229 | val 1.81639
  Epoch 012 - train 0.37480 | val 2.44655
  Classification -> best τ=0.355 (val F1=0.1870)
  Directional -> Accuracy: 0.5870, MCC: 0.1700, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44086 | val 0.91340
  Epoch 011 - train 0.40278 | val 0.78379
  Classification -> best τ=0.535 (val F1=0.4126)
  Directional -> Accuracy: 0.5745, MCC: 0.2164, F1: 0.4444

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.43524 | val 3.48481
  Epoch 011 - train 0.41239 | val 4.83505
  Classification -> best τ=0.300 (val F1=0.1178)
  Directional -> Accuracy: 0.4667, MCC: 0.1059, F1: 0.0476

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.34706 | val 1.61766
  Epoch 012 - train 0.33951 | val 1.46398
  Classification -> best τ=0.490 (val F1=0.4827)
  Directional -> Accuracy: 0.5490, MCC: 0.0892, F1: 0.5965

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36174 | val 2.01112
  Epoch 011 - train 0.36467 | val 2.32144
  Classification -> best τ=0.660 (val F1=0.2182)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.46078 | val 0.97247
  Epoch 011 - train 0.36852 | val 0.99681
  Classification -> best τ=0.530 (val F1=0.1781)
  Directional -> Accuracy: 0.5652, MCC: 0.1413, F1: 0.5312

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.37247 | val 2.96705
  Epoch 011 - train 0.28682 | val 3.44267
  Classification -> best τ=0.520 (val F1=0.3295)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.39674 | val 0.95816
  Epoch 011 - train 0.37922 | val 1.08478
  Classification -> best τ=0.470 (val F1=0.2308)
  Directional -> Accuracy: 0.5306, MCC: -0.0594, F1: 0.0800

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41517 | val 1.30740
  Epoch 011 - train 0.41040 | val 1.56142
  Classification -> best τ=0.400 (val F1=0.2879)
  Directional -> Accuracy: 0.3857, MCC: -0.2443, F1: 0.5567

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.37366 | val 2.39672
  Epoch 011 - train 0.28884 | val 2.79051
  Classification -> best τ=0.665 (val F1=0.2041)
  Directional -> Accuracy: 0.4800, MCC: 0.0146, F1: 0.5938

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.35880 | val 2.75794
  Epoch 011 - train 0.34103 | val 3.53166
  Classification -> best τ=0.315 (val F1=0.2097)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.38110 | val 1.24662
  Epoch 011 - train 0.42735 | val 1.39683
  Classification -> best τ=0.370 (val F1=0.2719)
  Directional -> Accuracy: 0.4186, MCC: -0.1150, F1: 0.5455

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.45715 | val 1.06057
  Epoch 014 - train 0.30309 | val 1.20666
  Classification -> best τ=0.425 (val F1=0.3812)
  Directional -> Accuracy: 0.5082, MCC: 0.0141, F1: 0.5455

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.38519 | val 1.04110
  Epoch 011 - train 0.33220 | val 1.13259
  Classification -> best τ=0.395 (val F1=0.1262)
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.45413 | val 0.82524
  Epoch 012 - train 0.38788 | val 0.88067
  Classification -> best τ=0.365 (val F1=0.2927)
  Directional -> Accuracy: 0.6000, MCC: 0.2683, F1: 0.7308

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44537 | val 2.45031
  Epoch 011 - train 0.41982 | val 2.72403
  Classification -> best τ=0.680 (val F1=0.2294)
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.40684 | val 1.31081
  Epoch 011 - train 0.37288 | val 2.02181
  Classification -> best τ=0.370 (val F1=0.2232)
  Directional -> Accuracy: 0.5921, MCC: 0.1514, F1: 0.6593

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.41181 | val 1.11580
  Epoch 012 - train 0.31512 | val 1.88829
  Classification -> best τ=0.655 (val F1=0.2899)
  Directional -> Accuracy: 0.4308, MCC: 0.1054, F1: 0.0513

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42819 | val 0.80688
  Epoch 012 - train 0.43991 | val 0.87616
  Classification -> best τ=0.255 (val F1=0.1859)
  Directional -> Accuracy: 0.5600, MCC: 0.0761, F1: 0.6972

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.34597 | val 1.10428
  Epoch 012 - train 0.24949 | val 1.49968
  Classification -> best τ=0.455 (val F1=0.2064)
  Directional -> Accuracy: 0.5625, MCC: 0.0348, F1: 0.6667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41048 | val 1.14008
  Epoch 011 - train 0.36078 | val 1.51461
  Classification -> best τ=0.410 (val F1=0.1167)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46487 | val 0.99810
  Epoch 012 - train 0.42166 | val 1.09109
  Classification -> best τ=0.435 (val F1=0.3179)
  Directional -> Accuracy: 0.5172, MCC: -0.0846, F1: 0.6585

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.49163 | val 2.19557
  Epoch 011 - train 0.40185 | val 2.21264
  Classification -> best τ=0.435 (val F1=0.0921)
  Directional -> Accuracy: 0.5000, MCC: 0.1664, F1: 0.6526

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38462 | val 1.23890
  Epoch 013 - train 0.30914 | val 1.45719
  Classification -> best τ=0.600 (val F1=0.3267)
  Directional -> Accuracy: 0.5357, MCC: 0.1534, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.38224 | val 1.51645
  Epoch 011 - train 0.30874 | val 1.64267
  Classification -> best τ=0.445 (val F1=0.2798)
  Directional -> Accuracy: 0.5435, MCC: 0.1424, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.32712 | val 0.98535
  Epoch 011 - train 0.31745 | val 1.14883
  Classification -> best τ=0.470 (val F1=0.3221)
  Directional -> Accuracy: 0.5116, MCC: -0.0889, F1: 0.6441

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44579 | val 1.38367
  Epoch 011 - train 0.39761 | val 1.53358
  Classification -> best τ=0.510 (val F1=0.2073)
  Directional -> Accuracy: 0.4561, MCC: -0.0906, F1: 0.4918

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46552 | val 0.86630
  Epoch 011 - train 0.43310 | val 0.98465
  Classification -> best τ=0.465 (val F1=0.2125)
  Directional -> Accuracy: 0.5122, MCC: -0.1469, F1: 0.6774

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.35152 | val 5.45275
  Epoch 011 - train 0.30100 | val 5.05335
  Classification -> best τ=0.625 (val F1=0.1834)
  Directional -> Accuracy: 0.5581, MCC: 0.1436, F1: 0.2963

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44893 | val 0.76800
  Epoch 016 - train 0.25488 | val 1.10520
  Classification -> best τ=0.400 (val F1=0.2533)
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.39132 | val 1.20186
  Epoch 011 - train 0.36968 | val 1.19954
  Classification -> best τ=0.380 (val F1=0.2541)
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.43334 | val 0.92063
  Epoch 015 - train 0.29260 | val 1.21866
  Classification -> best τ=0.420 (val F1=0.4698)
  Directional -> Accuracy: 0.5068, MCC: 0.0558, F1: 0.4545

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.46717 | val 0.97856
  Epoch 011 - train 0.36517 | val 1.06546
  Classification -> best τ=0.465 (val F1=0.1826)
  Directional -> Accuracy: 0.5526, MCC: 0.1715, F1: 0.6792

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.35385 | val 1.09696
  Epoch 011 - train 0.32392 | val 1.12785
  Classification -> best τ=0.395 (val F1=0.1902)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42842 | val 1.14774
  Epoch 011 - train 0.40138 | val 1.19953
  Classification -> best τ=0.365 (val F1=0.3521)
  Directional -> Accuracy: 0.5821, MCC: 0.2576, F1: 0.5000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.26081 | val 1.87009
  Epoch 011 - train 0.24043 | val 2.02679
  Classification -> best τ=0.500 (val F1=0.1736)
  Directional -> Accuracy: 0.5581, MCC: 0.1366, F1: 0.4571

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.31075 | val 2.27570
  Epoch 011 - train 0.27405 | val 3.16909
  Classification -> best τ=0.450 (val F1=0.2261)
  Directional -> Accuracy: 0.5439, MCC: 0.1154, F1: 0.6061

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39058 | val 2.41320
  Epoch 011 - train 0.35322 | val 2.25597
  Classification -> best τ=0.540 (val F1=0.2403)
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.33552 | val 1.09605
  Epoch 011 - train 0.28666 | val 1.19945
  Classification -> best τ=0.480 (val F1=0.3682)
  Directional -> Accuracy: 0.4082, MCC: 0.0726, F1: 0.5397

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.41569 | val 1.12840
  Epoch 011 - train 0.38429 | val 1.21769
  Classification -> best τ=0.520 (val F1=0.1461)
  Directional -> Accuracy: 0.4474, MCC: -0.1192, F1: 0.5116

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44937 | val 1.54174
  Epoch 011 - train 0.40602 | val 1.67760
  Classification -> best τ=0.460 (val F1=0.2202)
  Directional -> Accuracy: 0.5067, MCC: 0.1147, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43823 | val 0.96440
  Epoch 011 - train 0.40228 | val 0.88729
  Classification -> best τ=0.460 (val F1=0.2357)
  Directional -> Accuracy: 0.6383, MCC: 0.3053, F1: 0.7119

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.39329 | val 1.34685
  Epoch 011 - train 0.36303 | val 1.62474
  Classification -> best τ=0.450 (val F1=0.3550)
  Directional -> Accuracy: 0.6591, MCC: 0.3028, F1: 0.7541

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.38505 | val 1.41032
  Epoch 015 - train 0.26138 | val 1.77764
  Classification -> best τ=0.425 (val F1=0.5303)
  Directional -> Accuracy: 0.3673, MCC: -0.1814, F1: 0.5373

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.39661 | val 0.95432
  Epoch 013 - train 0.34082 | val 1.13116
  Classification -> best τ=0.540 (val F1=0.2130)
  Directional -> Accuracy: 0.4286, MCC: -0.1247, F1: 0.2381

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46355 | val 1.13897
  Epoch 011 - train 0.41132 | val 1.09353
  Classification -> best τ=0.660 (val F1=0.2667)
  Directional -> Accuracy: 0.5439, MCC: 0.0714, F1: 0.3810

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.43293 | val 1.66607
  Epoch 011 - train 0.42202 | val 2.26700
  Classification -> best τ=0.430 (val F1=0.1280)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48100 | val 1.21574
  Epoch 011 - train 0.39737 | val 0.88732
  Classification -> best τ=0.420 (val F1=0.2402)
  Directional -> Accuracy: 0.5357, MCC: 0.0879, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.45562 | val 1.24525

[I 2026-02-19 01:48:32,434] Trial 46 finished with value: 0.25142873293677515 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0037575901972981274, 'weight_decay': 7.549941929610719e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.131510156500466, 'early_stopping_min_delta': 0.0019233255473715706}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 014 - train 0.32267 | val 1.97813
  Classification -> best τ=0.700 (val F1=0.2136)
  Directional -> Accuracy: 0.5082, MCC: -0.0647, F1: 0.0625

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25142873293677515
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61302 | val 1.65428
  Epoch 020 - train 0.44568 | val 1.20751
  Epoch 021 - train 0.44492 | val 2.46662
  Classification -> best τ=0.450 (val F1=0.0990)
  Directional -> Accuracy: 0.5000, MCC: -0.0482, F1: 0.3273

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59081 | val 0.94634
  Epoch 020 - train 0.26977 | val 2.21094
  Epoch 025 - train 0.17771 | val 2.73795
  Classification -> best τ=0.470 (val F1=0.3072)
  Directional -> Accuracy: 0.6047, MCC: 0.0473, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55630 | val 0.68308
  Epoch 020 - train 0.28751 | val 1.52383
  Epoch 021 - train 0.25588 | val 1.43052
  Classification -> best τ=0.510 (val F1=0.3327)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.64174 | val 1.97905
  Epoch 020 - train 0.60495 | val 2.68934
  Epoch 022 - train 0.57759 | val 2.43643
  Classification -> best τ=0.365 (val F1=0.2712)
  Directional -> Accuracy: 0.5139, MCC: 0.0476, F1: 0.4776

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58495 | val 0.83873
  Epoch 020 - train 0.27350 | val 1.42635
  Epoch 021 - train 0.38417 | val 1.13834
  Classification -> best τ=0.675 (val F1=0.4063)
  Directional -> Accuracy: 0.5208, MCC: 0.0813, F1: 0.3429

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43757 | val 5.06155
  Epoch 020 - train 0.08945 | val 8.14355
  Epoch 021 - train 0.11373 | val 8.23325
  Classification -> best τ=0.390 (val F1=0.0572)
  Directional -> Accuracy: 0.4091, MCC: -0.3162, F1: 0.5806

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64700 | val 1.06078
  Epoch 020 - train 0.37632 | val 1.29197
  Epoch 021 - train 0.46785 | val 1.62898
  Classification -> best τ=0.480 (val F1=0.2502)
  Directional -> Accuracy: 0.4848, MCC: -0.0780, F1: 0.3462

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42577 | val 2.56987
  Epoch 020 - train 0.11684 | val 4.54107
  Epoch 025 - train 0.05465 | val 6.70545
  Classification -> best τ=0.235 (val F1=0.2928)
  Directional -> Accuracy: 0.4615, MCC: 0.0069, F1: 0.5714

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56443 | val 1.12569
  Epoch 020 - train 0.18508 | val 2.31826
  Epoch 021 - train 0.16587 | val 1.76294
  Classification -> best τ=0.480 (val F1=0.2835)
  Directional -> Accuracy: 0.6739, MCC: 0.3982, F1: 0.4000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.60818 | val 0.90285
  Epoch 020 - train 0.47077 | val 1.59475
  Epoch 021 - train 0.45576 | val 1.51026
  Classification -> best τ=0.540 (val F1=0.1787)
  Directional -> Accuracy: 0.4627, MCC: -0.2122, F1: 0.1429

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.56932 | val 2.96070
  Epoch 020 - train 0.46937 | val 3.50585
  Epoch 022 - train 0.38251 | val 4.58210
  Classification -> best τ=0.595 (val F1=0.1871)
  Directional -> Accuracy: 0.4681, MCC: -0.1336, F1: 0.2424

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58630 | val 1.28465
  Epoch 020 - train 0.50928 | val 1.86552
  Epoch 021 - train 0.48058 | val 2.49809
  Classification -> best τ=0.435 (val F1=0.1386)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57702 | val 0.65803
  Epoch 020 - train 0.42765 | val 0.70779
  Epoch 030 - train 0.18689 | val 1.21542
  Classification -> best τ=0.435 (val F1=0.4366)
  Directional -> Accuracy: 0.4583, MCC: -0.0764, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.58009 | val 1.48078
  Epoch 020 - train 0.37332 | val 2.04101
  Epoch 021 - train 0.31516 | val 1.96138
  Classification -> best τ=0.415 (val F1=0.2688)
  Directional -> Accuracy: 0.5172, MCC: 0.0250, F1: 0.5882

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.59268 | val 0.94434
  Epoch 020 - train 0.36515 | val 1.89324
  Epoch 022 - train 0.37363 | val 2.41419
  Classification -> best τ=0.625 (val F1=0.2125)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68548 | val 0.76800
  Epoch 020 - train 0.51355 | val 1.25059
  Epoch 021 - train 0.47158 | val 1.23039
  Classification -> best τ=0.410 (val F1=0.2866)
  Directional -> Accuracy: 0.5821, MCC: 0.2333, F1: 0.7200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.60678 | val 1.47372
  Epoch 020 - train 0.51053 | val 2.23448
  Epoch 021 - train 0.47963 | val 2.00709
  Classification -> best τ=0.410 (val F1=0.0060)
  Directional -> Accuracy: 0.3929, MCC: -0.2943, F1: 0.5143

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64171 | val 0.85887
  Epoch 020 - train 0.60404 | val 1.19900
  Epoch 029 - train 0.55873 | val 0.78553
  Classification -> best τ=0.440 (val F1=0.2077)
  Directional -> Accuracy: 0.4384, MCC: 0.0472, F1: 0.1633

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64338 | val 1.02875
  Epoch 020 - train 0.49159 | val 1.20303
  Epoch 021 - train 0.48634 | val 1.53696
  Classification -> best τ=0.380 (val F1=0.2483)
  Directional -> Accuracy: 0.4839, MCC: 0.1321, F1: 0.2727

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60528 | val 0.79496
  Epoch 020 - train 0.44482 | val 1.40357
  Epoch 022 - train 0.41460 | val 2.59209
  Classification -> best τ=0.430 (val F1=0.2870)
  Directional -> Accuracy: 0.4861, MCC: 0.1865, F1: 0.1395

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53529 | val 1.17279
  Epoch 020 - train 0.35145 | val 2.09372
  Epoch 021 - train 0.33990 | val 2.17049
  Classification -> best τ=0.340 (val F1=0.1685)
  Directional -> Accuracy: 0.5111, MCC: 0.0181, F1: 0.5600

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57033 | val 0.93884
  Epoch 020 - train 0.34461 | val 1.63013
  Epoch 021 - train 0.35002 | val 1.49752
  Classification -> best τ=0.465 (val F1=0.1500)
  Directional -> Accuracy: 0.4286, MCC: -0.1423, F1: 0.4706

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.67109 | val 0.76652
  Epoch 020 - train 0.46010 | val 1.59574
  Epoch 021 - train 0.45480 | val 1.50445
  Classification -> best τ=0.500 (val F1=0.3087)
  Directional -> Accuracy: 0.5091, MCC: 0.0336, F1: 0.5263

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.59024 | val 0.77809
  Epoch 020 - train 0.42239 | val 0.82848
  Epoch 021 - train 0.37429 | val 0.92752
  Classification -> best τ=0.500 (val F1=0.2217)
  Directional -> Accuracy: 0.4921, MCC: -0.0246, F1: 0.4286

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61459 | val 0.67537
  Epoch 020 - train 0.57656 | val 0.66366
  Epoch 028 - train 0.46271 | val 1.30277
  Classification -> best τ=0.535 (val F1=0.4055)
  Directional -> Accuracy: 0.5283, MCC: 0.1718, F1: 0.3243

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42933 | val 1.91862
  Epoch 020 - train 0.08469 | val 1.72963
  Epoch 022 - train 0.14916 | val 2.18936
  Classification -> best τ=0.580 (val F1=0.2987)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50792 | val 0.62303
  Epoch 020 - train 0.38614 | val 1.51753
  Epoch 030 - train 0.24665 | val 0.83189
  Epoch 038 - train 0.05827 | val 1.43954
  Classification -> best τ=0.660 (val F1=0.4888)
  Directional -> Accuracy: 0.4583, MCC: -0.0989, F1: 0.5185

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57210 | val 1.86147
  Epoch 020 - train 0.31709 | val 3.26939
  Epoch 021 - train 0.30477 | val 3.44440
  Classification -> best τ=0.480 (val F1=0.1657)
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49585 | val 2.34666
  Epoch 020 - train 0.31863 | val 1.98977
  Epoch 021 - train 0.23855 | val 2.24918
  Classification -> best τ=0.505 (val F1=0.1779)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45083 | val 1.10154
  Epoch 020 - train 0.16010 | val 1.59085
  Epoch 023 - train 0.14695 | val 1.79132
  Classification -> best τ=0.640 (val F1=0.2736)
  Directional -> Accuracy: 0.4750, MCC: 0.0668, F1: 0.1600

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.54295 | val 0.64034
  Epoch 020 - train 0.37748 | val 0.76861
  Epoch 027 - train 0.32029 | val 1.10285
  Classification -> best τ=0.330 (val F1=0.4775)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.63420 | val 0.70934
  Epoch 020 - train 0.61857 | val 0.68816
  Epoch 030 - train 0.49921 | val 0.68280
  Epoch 032 - train 0.53891 | val 0.81794
  Classification -> best τ=0.370 (val F1=0.3171)
  Directional -> Accuracy: 0.5714, MCC: 0.1660, F1: 0.5588

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.55421 | val 1.54225
  Epoch 020 - train 0.24437 | val 2.53183
  Epoch 021 - train 0.23479 | val 1.70106
  Classification -> best τ=0.400 (val F1=0.3419)
  Directional -> Accuracy: 0.5714, MCC: 0.1811, F1: 0.6316

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60414 | val 0.78194
  Epoch 020 - train 0.43827 | val 1.17247
  Epoch 022 - train 0.43793 | val 0.93602
  Classification -> best τ=0.325 (val F1=0.4656)
  Directional -> Accuracy: 0.6250, MCC: 0.2446, F1: 0.6571

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52042 | val 1.31754
  Epoch 020 - train 0.18415 | val 3.09911
  Epoch 021 - train 0.16595 | val 2.68788
  Classification -> best τ=0.520 (val F1=0.2006)
  Directional -> Accuracy: 0.6122, MCC: 0.2434, F1: 0.4865

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59050 | val 1.91076
  Epoch 020 - train 0.48999 | val 1.98060
  Epoch 022 - train 0.40390 | val 2.35733
  Classification -> best τ=0.430 (val F1=0.1006)
  Directional -> Accuracy: 0.4630, MCC: -0.0146, F1: 0.6234

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47850 | val 1.53265
  Epoch 020 - train 0.11271 | val 2.49721
  Epoch 021 - train 0.19742 | val 1.96111
  Classification -> best τ=0.415 (val F1=0.2841)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57586 | val 0.68993
  Epoch 020 - train 0.38162 | val 1.13468
  Epoch 025 - train 0.24604 | val 1.39364
  Classification -> best τ=0.455 (val F1=0.4719)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61244 | val 1.82256
  Epoch 020 - train 0.49343 | val 2.83659
  Epoch 021 - train 0.47394 | val 3.40271
  Classification -> best τ=0.620 (val F1=0.1738)
  Directional -> Accuracy: 0.6111, MCC: 0.2807, F1: 0.7021

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48575 | val 0.91566
  Epoch 020 - train 0.22835 | val 2.19580
  Epoch 021 - train 0.21780 | val 2.16414
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.37554 | val 0.79101
  Epoch 020 - train 0.02355 | val 1.30493
  Epoch 024 - train 0.01732 | val 1.30244
  Classification -> best τ=0.560 (val F1=0.3671)
  Directional -> Accuracy: 0.6667, MCC: 0.2855, F1: 0.7547

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.39346 | val 1.57736
  Epoch 020 - train 0.11789 | val 2.95795
  Epoch 025 - train 0.07531 | val 3.77880
  Classification -> best τ=0.610 (val F1=0.3990)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.62250 | val 0.85914
  Epoch 020 - train 0.45076 | val 1.40420
  Epoch 023 - train 0.41989 | val 1.91973
  Classification -> best τ=0.670 (val F1=0.2618)
  Directional -> Accuracy: 0.4340, MCC: -0.1722, F1: 0.5312

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60267 | val 2.09217
  Epoch 020 - train 0.54537 | val 2.17752
  Epoch 021 - train 0.51662 | val 2.09809
  Classification -> best τ=0.375 (val F1=0.1028)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62701 | val 1.01064
  Epoch 020 - train 0.44798 | val 0.83176
  Epoch 023 - train 0.42406 | val 0.89421
  Classification -> best τ=0.620 (val F1=0.2828)
  Directional -> Accuracy: 0.5294, MCC: 0.1146, F1: 0.6571

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60756 | val 1.95195
  Epoch 020 - train 0.44410 | val 2.28928
  Epoch 021 - train 0.43199 | val 5.15825
  Classification -> best τ=0.485 (val F1=0.1479)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62833 | val 0.65878
  Epoch 020 - train 0.39088 | val 1.54388

[I 2026-02-19 02:00:24,237] Trial 47 finished with value: 0.2571714107291945 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.005100857253524911, 'weight_decay': 0.0009061680427138236, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.356361784327063, 'early_stopping_min_delta': 0.003209363318146287}. Best is trial 10 with value: 0.2688998415931245.

Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69091 | val 0.72525
  Epoch 020 - train 0.68906 | val 0.72921
  Epoch 021 - train 0.69244 | val 0.72921
  Classification -> best τ=0.505 (val F1=0.1567)
  Directional -> Accuracy: 0.5135, MCC: -0.0570, F1: 0.2174

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.71601 | val 0.71884
  Epoch 020 - train 0.70694 | val 0.71488
  Epoch 021 - train 0.70685 | val 0.71719
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68677 | val 0.66758
  Epoch 020 - train 0.68061 | val 0.66657
  Epoch 030 - train 0.68788 | val 0.66256
  Epoch 040 - train 0.68330 | val 0.66411
  Epoch 044 - train 0.68235 | val 0.66478
  Classification -> best τ=0.540 (val F1=0.4396)
  Directional -> Accuracy: 0.5227, MCC: 0.1439, F1: 0.2222

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68474 | val 0.76443
  Epoch 020 - train 0.69679 | val 0.74387
  Epoch 021 - train 0.68807 | val 0.73807
  Classification -> best τ=0.470 (val F1=0.1327)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68469 | val 0.71749
  Epoch 020 - train 0.68933 | val 0.71374
  Epoch 021 - train 0.68990 | val 0.71530
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67860 | val 0.71684
  Epoch 020 - train 0.68430 | val 0.72120
  Epoch 021 - train 0.68690 | val 0.71848
  Classification -> best τ=0.470 (val F1=0.0486)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69427 | val 0.68726
  Epoch 020 - train 0.70113 | val 0.68620
  Epoch 024 - train 0.69551 | val 0.68800
  Classification -> best τ=0.500 (val F1=0.3280)
  Directional -> Accuracy: 0.5909, MCC: 0.0470, F1: 0.1290

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71558 | val 0.64655
  Epoch 020 - train 0.72127 | val 0.65462
  Epoch 030 - train 0.71088 | val 0.65167
  Epoch 032 - train 0.71332 | val 0.65850
  Classification -> best τ=0.460 (val F1=0.5556)
  Directional -> Accuracy: 0.4103, MCC: -0.1463, F1: 0.4651

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69895 | val 0.69832
  Epoch 020 - train 0.69711 | val 0.69956
  Epoch 021 - train 0.70210 | val 0.69729
  Classification -> best τ=0.480 (val F1=0.0598)
  Directional -> Accuracy: 0.5217, MCC: 0.1710, F1: 0.6207

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69169 | val 0.70220
  Epoch 020 - train 0.69097 | val 0.70196
  Epoch 021 - train 0.68967 | val 0.70232
  Classification -> best τ=0.505 (val F1=0.0516)
  Directional -> Accuracy: 0.5373, MCC: 0.0732, F1: 0.4918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69683 | val 0.72507
  Epoch 020 - train 0.68486 | val 0.72604
  Epoch 021 - train 0.68568 | val 0.72787
  Classification -> best τ=0.470 (val F1=0.2676)
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70252 | val 0.72276
  Epoch 020 - train 0.71319 | val 0.72064
  Epoch 021 - train 0.71895 | val 0.72296
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.71839 | val 0.73023
  Epoch 020 - train 0.71240 | val 0.73139
  Epoch 021 - train 0.72014 | val 0.72843
  Classification -> best τ=0.480 (val F1=0.2692)
  Directional -> Accuracy: 0.4583, MCC: -0.0723, F1: 0.5667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69611 | val 0.68254
  Epoch 020 - train 0.69343 | val 0.67966
  Epoch 021 - train 0.69887 | val 0.68313
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68235 | val 0.69842
  Epoch 020 - train 0.68818 | val 0.69974
  Epoch 021 - train 0.69959 | val 0.69966
  Classification -> best τ=0.495 (val F1=0.1373)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68967 | val 0.68833
  Epoch 020 - train 0.68753 | val 0.68714
  Epoch 023 - train 0.68689 | val 0.68982
  Classification -> best τ=0.490 (val F1=0.2289)
  Directional -> Accuracy: 0.5522, MCC: 0.0746, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68855 | val 0.74737
  Epoch 020 - train 0.68954 | val 0.75276
  Epoch 021 - train 0.68508 | val 0.75284
  Classification -> best τ=0.480 (val F1=0.1368)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69602 | val 0.70977
  Epoch 020 - train 0.70131 | val 0.71009
  Epoch 021 - train 0.69812 | val 0.70948
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5890, MCC: 0.0000, F1: 0.7414

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70546 | val 0.70523
  Epoch 020 - train 0.69830 | val 0.70700
  Epoch 021 - train 0.70128 | val 0.70750
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5806, MCC: 0.0000, F1: 0.7347

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.69159 | val 0.95220
  Epoch 020 - train 0.69161 | val 0.96268
  Epoch 021 - train 0.69546 | val 0.94249
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.70146 | val 0.70445
  Epoch 020 - train 0.69787 | val 0.70710
  Epoch 021 - train 0.68482 | val 0.70733
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69144 | val 0.69569
  Epoch 020 - train 0.69725 | val 0.70023
  Epoch 024 - train 0.68914 | val 0.69915
  Classification -> best τ=0.505 (val F1=0.3411)
  Directional -> Accuracy: 0.5556, MCC: 0.1109, F1: 0.5484

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69511 | val 0.69769
  Epoch 020 - train 0.69584 | val 0.69708
  Epoch 021 - train 0.69222 | val 0.69625
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5818, MCC: 0.0000, F1: 0.7356

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70140 | val 0.85097
  Epoch 020 - train 0.70094 | val 0.84793
  Epoch 021 - train 0.69468 | val 0.84034
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68728 | val 0.67704
  Epoch 020 - train 0.68278 | val 0.67337
  Epoch 030 - train 0.69250 | val 0.67105
  Epoch 040 - train 0.68400 | val 0.66434
  Epoch 050 - train 0.68061 | val 0.66410
  Classification -> best τ=0.415 (val F1=0.4235)
  Directional -> Accuracy: 0.4528, MCC: -0.0457, F1: 0.2564

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.72442 | val 0.69926
  Epoch 020 - train 0.72165 | val 0.70722
  Epoch 028 - train 0.70776 | val 0.70604
  Classification -> best τ=0.470 (val F1=0.2726)
  Directional -> Accuracy: 0.5238, MCC: 0.0413, F1: 0.4737

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69548 | val 0.68945
  Epoch 020 - train 0.69393 | val 0.68912
  Epoch 026 - train 0.69783 | val 0.69038
  Classification -> best τ=0.535 (val F1=0.0692)
  Directional -> Accuracy: 0.5000, MCC: -0.0598, F1: 0.6000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70022 | val 0.68867
  Epoch 020 - train 0.70149 | val 0.68973
  Epoch 021 - train 0.70657 | val 0.68948
  Classification -> best τ=0.460 (val F1=0.1139)
  Directional -> Accuracy: 0.5000, MCC: 0.0083, F1: 0.4906

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68595 | val 0.67307
  Epoch 020 - train 0.68644 | val 0.67117
  Epoch 030 - train 0.68934 | val 0.67115
  Epoch 039 - train 0.68269 | val 0.67209
  Classification -> best τ=0.540 (val F1=0.3333)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69361 | val 0.68452
  Epoch 020 - train 0.70110 | val 0.68761
  Epoch 021 - train 0.70180 | val 0.68646
  Classification -> best τ=0.515 (val F1=0.2482)
  Directional -> Accuracy: 0.5000, MCC: -0.1340, F1: 0.6552

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.70908 | val 0.68958
  Epoch 020 - train 0.70753 | val 0.68774
  Epoch 021 - train 0.70091 | val 0.68770
  Classification -> best τ=0.475 (val F1=0.2140)
  Directional -> Accuracy: 0.5319, MCC: 0.1194, F1: 0.2667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.71052 | val 0.79156
  Epoch 020 - train 0.70064 | val 0.79005
  Epoch 021 - train 0.70553 | val 0.78698
  Classification -> best τ=0.495 (val F1=0.0572)
  Directional -> Accuracy: 0.5000, MCC: -0.0863, F1: 0.6316

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69710 | val 0.68232
  Epoch 020 - train 0.69776 | val 0.68358
  Epoch 030 - train 0.67596 | val 0.68331
  Epoch 032 - train 0.69388 | val 0.68468
  Classification -> best τ=0.525 (val F1=0.4445)
  Directional -> Accuracy: 0.4082, MCC: -0.2003, F1: 0.5538

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69060 | val 0.69368
  Epoch 020 - train 0.68375 | val 0.69369
  Epoch 021 - train 0.68169 | val 0.69364
  Classification -> best τ=0.465 (val F1=0.0557)
  Directional -> Accuracy: 0.4375, MCC: -0.0405, F1: 0.1429

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71118 | val 0.70767
  Epoch 020 - train 0.69744 | val 0.71188
  Epoch 021 - train 0.69427 | val 0.71399
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70107 | val 0.70524
  Epoch 020 - train 0.69264 | val 0.70459
  Epoch 021 - train 0.69135 | val 0.70579
  Classification -> best τ=0.460 (val F1=0.1125)
  Directional -> Accuracy: 0.5370, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69402 | val 0.80889
  Epoch 020 - train 0.69881 | val 0.81034
  Epoch 021 - train 0.70119 | val 0.81673
  Classification -> best τ=0.510 (val F1=0.1768)
  Directional -> Accuracy: 0.4773, MCC: -0.1412, F1: 0.5965

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69744 | val 0.73011
  Epoch 020 - train 0.71306 | val 0.74872
  Epoch 021 - train 0.71088 | val 0.74905
  Classification -> best τ=0.535 (val F1=0.0116)
  Directional -> Accuracy: 0.3333, MCC: -0.0762, F1: 0.4828

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69432 | val 0.68888
  Epoch 020 - train 0.68114 | val 0.68689
  Epoch 024 - train 0.67471 | val 0.68700
  Classification -> best τ=0.525 (val F1=0.3439)
  Directional -> Accuracy: 0.5139, MCC: 0.0546, F1: 0.6602

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69043 | val 0.71498
  Epoch 020 - train 0.69410 | val 0.72496
  Epoch 021 - train 0.68118 | val 0.72527
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69883 | val 0.68692
  Epoch 020 - train 0.69953 | val 0.68389
  Epoch 030 - train 0.69358 | val 0.68254
  Epoch 036 - train 0.70883 | val 0.68308
  Classification -> best τ=0.490 (val F1=0.2957)
  Directional -> Accuracy: 0.5128, MCC: 0.1316, F1: 0.4242

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69643 | val 0.68503
  Epoch 020 - train 0.68800 | val 0.69065
  Epoch 021 - train 0.68657 | val 0.68815
  Classification -> best τ=0.545 (val F1=0.1754)
  Directional -> Accuracy: 0.4222, MCC: -0.1549, F1: 0.3500

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69903 | val 0.69687
  Epoch 020 - train 0.69278 | val 0.69690
  Epoch 024 - train 0.70450 | val 0.69796
  Classification -> best τ=0.555 (val F1=0.0846)
  Directional -> Accuracy: 0.4906, MCC: -0.2228, F1: 0.6582

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70448 | val 0.69376
  Epoch 020 - train 0.70559 | val 0.69207
  Epoch 021 - train 0.70636 | val 0.69037
  Classification -> best τ=0.475 (val F1=0.1274)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68818 | val 0.69586
  Epoch 020 - train 0.70843 | val 0.69965
  Epoch 021 - train 0.69786 | val 0.69986
  Classification -> best τ=0.525 (val F1=0.1122)
  Directional -> Accuracy: 0.4510, MCC: -0.1328, F1: 0.2222

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70573 | val 0.70339
  Epoch 020 - train 0.69820 | val 0.70105
  Epoch 021 - train 0.69414 | val 0.70306
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.71050 | val 0.71043
  Epoch 020 - train 0.71670 | val 0.71108
  Epoch 021 - train 0.71261 | val 0.70884
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)

[I 2026-02-19 02:12:37,614] Trial 48 finished with value: 0.14521733778307905 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 1.1822141145888152e-06, 'weight_decay': 0.0007159444120464133, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.7091868816902291, 'early_stopping_min_delta': 0.0031586519799406024}. Best is trial 10 with value: 0.2688998415931245.

Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64186 | val 0.71069
  Epoch 018 - train 0.56736 | val 0.93052
  Classification -> best τ=0.455 (val F1=0.1936)
  Directional -> Accuracy: 0.5867, MCC: 0.1569, F1: 0.5079

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60833 | val 0.83858
  Epoch 016 - train 0.52015 | val 0.90225
  Classification -> best τ=0.475 (val F1=0.0230)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61962 | val 1.12154
  Epoch 017 - train 0.48596 | val 1.08148
  Classification -> best τ=0.515 (val F1=0.2740)
  Directional -> Accuracy: 0.4889, MCC: 0.0066, F1: 0.3784

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65640 | val 2.29420
  Epoch 016 - train 0.59905 | val 2.40093
  Classification -> best τ=0.340 (val F1=0.1848)
  Directional -> Accuracy: 0.5205, MCC: -0.0357, F1: 0.6729

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49664 | val 1.08841
  Epoch 016 - train 0.47253 | val 1.03660
  Classification -> best τ=0.535 (val F1=0.3405)
  Directional -> Accuracy: 0.5510, MCC: 0.1667, F1: 0.3125

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47819 | val 0.89289
  Epoch 018 - train 0.34426 | val 1.97372
  Classification -> best τ=0.620 (val F1=0.2737)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59336 | val 0.97928
  Epoch 016 - train 0.54105 | val 1.41942
  Classification -> best τ=0.565 (val F1=0.1417)
  Directional -> Accuracy: 0.6269, MCC: 0.1686, F1: 0.2424

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53307 | val 2.57283
  Epoch 016 - train 0.48319 | val 5.00540
  Classification -> best τ=0.570 (val F1=0.0976)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58688 | val 1.20471
  Epoch 016 - train 0.43968 | val 1.21059
  Classification -> best τ=0.530 (val F1=0.2329)
  Directional -> Accuracy: 0.5106, MCC: 0.0645, F1: 0.5660

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.58871 | val 1.45798
  Epoch 016 - train 0.50661 | val 1.62500
  Classification -> best τ=0.465 (val F1=0.2300)
  Directional -> Accuracy: 0.4706, MCC: 0.1853, F1: 0.6170

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58489 | val 1.42829
  Epoch 016 - train 0.51484 | val 1.51411
  Classification -> best τ=0.520 (val F1=0.2000)
  Directional -> Accuracy: 0.5208, MCC: 0.0182, F1: 0.4103

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58005 | val 1.31565
  Epoch 016 - train 0.48845 | val 1.83519
  Classification -> best τ=0.460 (val F1=0.1646)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53460 | val 3.92193
  Epoch 016 - train 0.38294 | val 5.22717
  Classification -> best τ=0.400 (val F1=0.2335)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65859 | val 0.80660
  Epoch 018 - train 0.59315 | val 0.95300
  Classification -> best τ=0.380 (val F1=0.3764)
  Directional -> Accuracy: 0.5763, MCC: 0.1585, F1: 0.6479

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58657 | val 1.50151
  Epoch 016 - train 0.51734 | val 1.84634
  Classification -> best τ=0.580 (val F1=0.3265)
  Directional -> Accuracy: 0.5400, MCC: -0.1266, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53861 | val 1.17015
  Epoch 016 - train 0.51517 | val 1.60586
  Classification -> best τ=0.410 (val F1=0.3279)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.61684 | val 0.94220
  Epoch 016 - train 0.56275 | val 1.22630
  Classification -> best τ=0.550 (val F1=0.1588)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.65884 | val 1.14091
  Epoch 016 - train 0.63854 | val 1.10110
  Classification -> best τ=0.435 (val F1=0.2030)
  Directional -> Accuracy: 0.6081, MCC: 0.1314, F1: 0.7184

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.57730 | val 0.88102
  Epoch 017 - train 0.51931 | val 1.00654
  Classification -> best τ=0.595 (val F1=0.2288)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60156 | val 0.78109
  Epoch 016 - train 0.48866 | val 1.25175
  Classification -> best τ=0.460 (val F1=0.1828)
  Directional -> Accuracy: 0.5753, MCC: 0.2124, F1: 0.4918

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58236 | val 1.04724
  Epoch 016 - train 0.47167 | val 1.00069
  Classification -> best τ=0.465 (val F1=0.2227)
  Directional -> Accuracy: 0.6087, MCC: 0.2326, F1: 0.6400

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63563 | val 1.42091
  Epoch 016 - train 0.51373 | val 2.00872
  Classification -> best τ=0.545 (val F1=0.0276)
  Directional -> Accuracy: 0.5469, MCC: 0.1165, F1: 0.3556

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56933 | val 2.13330
  Epoch 016 - train 0.44428 | val 2.48488
  Classification -> best τ=0.525 (val F1=0.3162)
  Directional -> Accuracy: 0.5536, MCC: 0.0561, F1: 0.6479

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.54788 | val 0.88754
  Epoch 016 - train 0.50882 | val 1.14617
  Classification -> best τ=0.490 (val F1=0.1932)
  Directional -> Accuracy: 0.5469, MCC: 0.1306, F1: 0.6133

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58149 | val 0.90197
  Epoch 017 - train 0.47110 | val 1.52768
  Classification -> best τ=0.560 (val F1=0.5635)
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.52756 | val 1.37977
  Epoch 019 - train 0.35673 | val 1.84166
  Classification -> best τ=0.650 (val F1=0.3344)
  Directional -> Accuracy: 0.6977, MCC: 0.3680, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.60557 | val 0.76876
  Epoch 016 - train 0.51051 | val 1.35215
  Classification -> best τ=0.485 (val F1=0.0366)
  Directional -> Accuracy: 0.5510, MCC: 0.1000, F1: 0.5926

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62094 | val 0.88848
  Epoch 016 - train 0.49776 | val 1.19233
  Classification -> best τ=0.460 (val F1=0.1154)
  Directional -> Accuracy: 0.5455, MCC: 0.0177, F1: 0.6988

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54076 | val 0.93182
  Epoch 020 - train 0.41460 | val 1.11620
  Epoch 021 - train 0.39751 | val 1.12129
  Classification -> best τ=0.420 (val F1=0.2955)
  Directional -> Accuracy: 0.5263, MCC: 0.0206, F1: 0.6087

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55417 | val 2.19608
  Epoch 016 - train 0.47668 | val 2.25395
  Classification -> best τ=0.580 (val F1=0.2706)
  Directional -> Accuracy: 0.5122, MCC: 0.0055, F1: 0.0909

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.52722 | val 1.64818
  Epoch 016 - train 0.40601 | val 3.45609
  Classification -> best τ=0.525 (val F1=0.1053)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.52674 | val 1.14922
  Epoch 017 - train 0.37895 | val 1.03755
  Classification -> best τ=0.490 (val F1=0.2764)
  Directional -> Accuracy: 0.5833, MCC: 0.2190, F1: 0.7059

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62335 | val 0.99974
  Epoch 017 - train 0.53976 | val 1.15271
  Classification -> best τ=0.510 (val F1=0.2999)
  Directional -> Accuracy: 0.5352, MCC: 0.1773, F1: 0.4000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54779 | val 0.87152
  Epoch 016 - train 0.47668 | val 1.20404
  Classification -> best τ=0.530 (val F1=0.2873)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52405 | val 0.94408
  Epoch 016 - train 0.46669 | val 1.00472
  Classification -> best τ=0.460 (val F1=0.2667)
  Directional -> Accuracy: 0.6154, MCC: 0.2939, F1: 0.5763

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51793 | val 0.86569
  Epoch 017 - train 0.37554 | val 0.92492
  Classification -> best τ=0.490 (val F1=0.2697)
  Directional -> Accuracy: 0.6500, MCC: 0.3616, F1: 0.5625

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57697 | val 0.83280
  Epoch 016 - train 0.49548 | val 1.04023
  Classification -> best τ=0.455 (val F1=0.2436)
  Directional -> Accuracy: 0.5091, MCC: 0.0336, F1: 0.5263

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45381 | val 2.80476
  Epoch 016 - train 0.37250 | val 3.21635
  Classification -> best τ=0.515 (val F1=0.3283)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50329 | val 0.75228
  Epoch 020 - train 0.35720 | val 1.07382
  Epoch 021 - train 0.35072 | val 1.11366
  Classification -> best τ=0.745 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58927 | val 2.89211
  Epoch 017 - train 0.49498 | val 2.79889
  Classification -> best τ=0.355 (val F1=0.2842)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56369 | val 0.96793
  Epoch 020 - train 0.43467 | val 0.99634
  Epoch 022 - train 0.42278 | val 1.03317
  Classification -> best τ=0.435 (val F1=0.2887)
  Directional -> Accuracy: 0.4773, MCC: -0.0902, F1: 0.0800

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44840 | val 1.03389
  Epoch 016 - train 0.29979 | val 1.61076
  Classification -> best τ=0.555 (val F1=0.0510)
  Directional -> Accuracy: 0.4146, MCC: -0.0570, F1: 0.1429

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.48157 | val 0.97620
  Epoch 020 - train 0.28336 | val 1.65508
  Classification -> best τ=0.485 (val F1=0.2392)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66837 | val 1.30995
  Epoch 020 - train 0.62314 | val 1.09369
  Epoch 021 - train 0.61469 | val 1.17687
  Classification -> best τ=0.555 (val F1=0.1847)
  Directional -> Accuracy: 0.4074, MCC: -0.3305, F1: 0.5676

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58122 | val 1.82785
  Epoch 016 - train 0.52683 | val 3.11318
  Classification -> best τ=0.460 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67687 | val 0.79050
  Epoch 020 - train 0.54165 | val 0.84202
  Epoch 022 - train 0.47421 | val 0.87471
  Classification -> best τ=0.700 (val F1=0.4752)
  Directional -> Accuracy: 0.5385, MCC: 0.0976, F1: 0.6471

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55741 | val 1.94815
  Epoch 016 - train 0.44755 | val 2.66773
  Classification -> best τ=0.590 (val F1=0.2330)
  Directional -> Accuracy: 0.5741, MCC: 0.2517, F1: 0.7089

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62988 | val 1.06893

[I 2026-02-19 02:20:26,048] Trial 49 finished with value: 0.24089164179745257 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.0020463421738637737, 'weight_decay': 0.00021713783915321404, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.9873815965581025, 'early_stopping_min_delta': 0.0049671087095709415}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 017 - train 0.50672 | val 1.23000
  Classification -> best τ=0.500 (val F1=0.2811)
  Directional -> Accuracy: 0.4407, MCC: -0.1094, F1: 0.4923

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24089164179745257
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63394 | val 0.89933
  Epoch 020 - train 0.57586 | val 1.14548
  Epoch 021 - train 0.55959 | val 1.13629
  Classification -> best τ=0.500 (val F1=0.2683)
  Directional -> Accuracy: 0.5405, MCC: 0.0271, F1: 0.3200

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56522 | val 0.88229
  Epoch 020 - train 0.44128 | val 1.54859
  Epoch 023 - train 0.37403 | val 2.27762
  Classification -> best τ=0.445 (val F1=0.3341)
  Directional -> Accuracy: 0.6047, MCC: 0.0473, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62290 | val 1.40300
  Epoch 020 - train 0.46183 | val 1.03694
  Epoch 029 - train 0.29124 | val 1.70324
  Classification -> best τ=0.500 (val F1=0.5407)
  Directional -> Accuracy: 0.4545, MCC: -0.0828, F1: 0.4000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61715 | val 2.17923
  Epoch 020 - train 0.47009 | val 1.02095
  Epoch 021 - train 0.50650 | val 1.38510
  Classification -> best τ=0.430 (val F1=0.1568)
  Directional -> Accuracy: 0.4444, MCC: -0.0755, F1: 0.2308

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55633 | val 1.08654
  Epoch 020 - train 0.37196 | val 1.30227
  Epoch 023 - train 0.36541 | val 1.65857
  Classification -> best τ=0.495 (val F1=0.3679)
  Directional -> Accuracy: 0.5000, MCC: -0.0269, F1: 0.6129

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.46487 | val 2.89128
  Epoch 020 - train 0.35380 | val 8.84114
  Epoch 021 - train 0.27820 | val 9.77502
  Classification -> best τ=0.475 (val F1=0.0130)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63847 | val 1.06896
  Epoch 020 - train 0.46368 | val 0.91917
  Epoch 021 - train 0.50815 | val 1.23035
  Classification -> best τ=0.480 (val F1=0.1978)
  Directional -> Accuracy: 0.5758, MCC: 0.1909, F1: 0.5758

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55463 | val 1.48400
  Epoch 020 - train 0.33574 | val 4.42278
  Epoch 021 - train 0.33646 | val 4.60920
  Classification -> best τ=0.490 (val F1=0.1448)
  Directional -> Accuracy: 0.5385, MCC: 0.0878, F1: 0.5263

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.59946 | val 0.94482
  Epoch 020 - train 0.38617 | val 1.52630
  Epoch 025 - train 0.31470 | val 2.26225
  Classification -> best τ=0.675 (val F1=0.4390)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61251 | val 0.91722
  Epoch 020 - train 0.57238 | val 0.78505
  Epoch 027 - train 0.46521 | val 0.86275
  Classification -> best τ=0.420 (val F1=0.2413)
  Directional -> Accuracy: 0.3881, MCC: -0.1582, F1: 0.5393

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57880 | val 1.44848
  Epoch 020 - train 0.44323 | val 2.00742
  Epoch 021 - train 0.43972 | val 2.48596
  Classification -> best τ=0.580 (val F1=0.2606)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.59430 | val 1.70283
  Epoch 020 - train 0.48889 | val 1.65328
  Epoch 021 - train 0.48012 | val 1.59724
  Classification -> best τ=0.485 (val F1=0.1302)
  Directional -> Accuracy: 0.6364, MCC: 0.2742, F1: 0.6429

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.53471 | val 0.73744
  Epoch 020 - train 0.37260 | val 0.72902
  Epoch 023 - train 0.35751 | val 0.87292
  Classification -> best τ=0.485 (val F1=0.1718)
  Directional -> Accuracy: 0.4792, MCC: -0.0352, F1: 0.5098

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61868 | val 1.03053
  Epoch 020 - train 0.54027 | val 1.92069
  Epoch 021 - train 0.53272 | val 1.87111
  Classification -> best τ=0.485 (val F1=0.2050)
  Directional -> Accuracy: 0.5862, MCC: 0.1880, F1: 0.6842

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53343 | val 0.94801
  Epoch 020 - train 0.43460 | val 2.78273
  Epoch 023 - train 0.43837 | val 3.15065
  Classification -> best τ=0.435 (val F1=0.2573)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61453 | val 1.16924
  Epoch 020 - train 0.47064 | val 1.36236
  Epoch 021 - train 0.44054 | val 1.80622
  Classification -> best τ=0.525 (val F1=0.3063)
  Directional -> Accuracy: 0.6567, MCC: 0.3674, F1: 0.7527

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65018 | val 2.32161
  Epoch 020 - train 0.58340 | val 1.88621
  Epoch 021 - train 0.53559 | val 2.33553
  Classification -> best τ=0.590 (val F1=0.1874)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62878 | val 1.32533
  Epoch 020 - train 0.56366 | val 1.05110
  Epoch 022 - train 0.56486 | val 1.29791
  Classification -> best τ=0.530 (val F1=0.1829)
  Directional -> Accuracy: 0.4247, MCC: 0.0984, F1: 0.0455

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.60110 | val 0.98538
  Epoch 020 - train 0.51287 | val 1.15506
  Epoch 025 - train 0.50267 | val 1.32111
  Classification -> best τ=0.365 (val F1=0.3272)
  Directional -> Accuracy: 0.4677, MCC: 0.0966, F1: 0.2326

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.58273 | val 0.81950
  Epoch 020 - train 0.43547 | val 1.18481
  Epoch 021 - train 0.45559 | val 1.80709
  Classification -> best τ=0.525 (val F1=0.1327)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.57311 | val 1.45893
  Epoch 020 - train 0.37402 | val 1.65639
  Epoch 023 - train 0.35288 | val 1.77303
  Classification -> best τ=0.485 (val F1=0.3354)
  Directional -> Accuracy: 0.6222, MCC: 0.1443, F1: 0.7463

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63022 | val 1.60634
  Epoch 020 - train 0.56534 | val 1.09919
  Epoch 030 - train 0.42978 | val 0.82233
  Epoch 033 - train 0.43112 | val 0.97698
  Classification -> best τ=0.410 (val F1=0.3553)
  Directional -> Accuracy: 0.3968, MCC: -0.2114, F1: 0.4722

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60235 | val 1.06813
  Epoch 020 - train 0.47655 | val 1.14384
  Epoch 021 - train 0.43442 | val 1.25069
  Classification -> best τ=0.550 (val F1=0.1706)
  Directional -> Accuracy: 0.4909, MCC: 0.1784, F1: 0.2632

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.61844 | val 0.86559
  Epoch 020 - train 0.52513 | val 0.74212
  Epoch 021 - train 0.55690 | val 0.70029
  Classification -> best τ=0.470 (val F1=0.1173)
  Directional -> Accuracy: 0.4444, MCC: -0.1427, F1: 0.6067

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.54311 | val 0.90459
  Epoch 020 - train 0.40328 | val 1.67449
  Epoch 023 - train 0.39847 | val 1.35893
  Classification -> best τ=0.640 (val F1=0.3989)
  Directional -> Accuracy: 0.5660, MCC: 0.2449, F1: 0.4103

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.55934 | val 1.38961
  Epoch 020 - train 0.37940 | val 2.71626
  Epoch 021 - train 0.40705 | val 2.86195
  Classification -> best τ=0.510 (val F1=0.1612)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.56326 | val 0.95678
  Epoch 020 - train 0.38627 | val 1.81060
  Epoch 021 - train 0.36817 | val 2.09292
  Classification -> best τ=0.515 (val F1=0.0795)
  Directional -> Accuracy: 0.5417, MCC: 0.0707, F1: 0.5926

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60467 | val 0.84308
  Epoch 020 - train 0.43622 | val 0.91400
  Epoch 022 - train 0.38161 | val 0.95955
  Classification -> best τ=0.440 (val F1=0.2749)
  Directional -> Accuracy: 0.5185, MCC: 0.1685, F1: 0.2353

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.51376 | val 1.31089
  Epoch 020 - train 0.30498 | val 2.96968
  Epoch 021 - train 0.30064 | val 2.62143
  Classification -> best τ=0.515 (val F1=0.2491)
  Directional -> Accuracy: 0.5500, MCC: 0.1000, F1: 0.5500

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54817 | val 0.87028
  Epoch 020 - train 0.44200 | val 1.10814
  Epoch 022 - train 0.36580 | val 1.37144
  Classification -> best τ=0.550 (val F1=0.2736)
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53503 | val 0.80677
  Epoch 020 - train 0.47583 | val 0.92664
  Epoch 028 - train 0.32934 | val 1.39493
  Classification -> best τ=0.545 (val F1=0.3185)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62552 | val 0.66797
  Epoch 020 - train 0.60416 | val 0.87363
  Epoch 030 - train 0.41801 | val 1.13310
  Classification -> best τ=0.575 (val F1=0.3135)
  Directional -> Accuracy: 0.5286, MCC: 0.1429, F1: 0.4000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60513 | val 0.78943
  Epoch 020 - train 0.40670 | val 0.97833
  Epoch 021 - train 0.43237 | val 0.93840
  Classification -> best τ=0.505 (val F1=0.3015)
  Directional -> Accuracy: 0.3469, MCC: -0.3110, F1: 0.3043

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.51807 | val 1.02916
  Epoch 020 - train 0.39165 | val 0.95442
  Epoch 021 - train 0.40505 | val 1.34239
  Classification -> best τ=0.455 (val F1=0.0323)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43131 | val 3.27506
  Epoch 020 - train 0.29425 | val 2.97600
  Epoch 021 - train 0.33651 | val 2.83622
  Classification -> best τ=0.555 (val F1=0.0756)
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56686 | val 1.36577
  Epoch 020 - train 0.41012 | val 3.54747
  Epoch 021 - train 0.39124 | val 3.19563
  Classification -> best τ=0.480 (val F1=0.2426)
  Directional -> Accuracy: 0.5370, MCC: 0.1558, F1: 0.6377

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.52207 | val 1.64686
  Epoch 020 - train 0.36201 | val 1.61199
  Epoch 021 - train 0.35189 | val 0.93331
  Classification -> best τ=0.475 (val F1=0.2146)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47193 | val 0.93812
  Epoch 020 - train 0.32118 | val 1.66026
  Epoch 021 - train 0.27430 | val 1.69222
  Classification -> best τ=0.505 (val F1=0.1975)
  Directional -> Accuracy: 0.4444, MCC: 0.1734, F1: 0.5283

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58715 | val 1.16690
  Epoch 020 - train 0.45710 | val 3.60861
  Epoch 021 - train 0.47328 | val 3.26524
  Classification -> best τ=0.470 (val F1=0.1362)
  Directional -> Accuracy: 0.5278, MCC: 0.1213, F1: 0.6731

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56219 | val 1.06053
  Epoch 020 - train 0.36164 | val 1.16600
  Epoch 023 - train 0.34391 | val 1.13365
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46988 | val 0.59351
  Epoch 020 - train 0.40200 | val 0.77051
  Epoch 030 - train 0.11716 | val 0.86661
  Classification -> best τ=0.515 (val F1=0.5577)
  Directional -> Accuracy: 0.6410, MCC: 0.2223, F1: 0.7500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49139 | val 1.00287
  Epoch 020 - train 0.25626 | val 1.48788
  Epoch 021 - train 0.19370 | val 1.96011
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60581 | val 1.37522
  Epoch 020 - train 0.45048 | val 1.37274
  Epoch 021 - train 0.42219 | val 1.46523
  Classification -> best τ=0.530 (val F1=0.1984)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.56618 | val 1.83217
  Epoch 020 - train 0.40369 | val 3.16661
  Epoch 023 - train 0.35350 | val 2.86555
  Classification -> best τ=0.530 (val F1=0.4458)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4706

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59920 | val 0.91623
  Epoch 020 - train 0.49285 | val 0.97906
  Epoch 021 - train 0.44070 | val 1.07143
  Classification -> best τ=0.485 (val F1=0.3337)
  Directional -> Accuracy: 0.5686, MCC: 0.1413, F1: 0.5926

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.56663 | val 3.39512
  Epoch 020 - train 0.41709 | val 4.48171
  Epoch 021 - train 0.34621 | val 5.80157
  Classification -> best τ=0.530 (val F1=0.1657)
  Directional -> Accuracy: 0.4906, MCC: -0.0585, F1: 0.6400

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.64543 | val 0.69641
  Epoch 020 - train 0.56980 | val 0.88688

[I 2026-02-19 02:27:04,079] Trial 50 finished with value: 0.23659891969936112 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.0047583987143279575, 'weight_decay': 0.0009966608431748647, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.24884394151601807, 'early_stopping_min_delta': 0.0038412874477192246}. Best is trial 10 with value: 0.2688998415931245.

  Epoch 028 - train 0.49061 | val 1.39366
  Classification -> best τ=0.445 (val F1=0.3055)
  Directional -> Accuracy: 0.4655, MCC: -0.0131, F1: 0.6265

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.23659891969936112
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.54964 | val 1.11533
  Epoch 020 - train 0.26527 | val 2.42753
  Epoch 021 - train 0.21089 | val 3.42210
  Classification -> best τ=0.480 (val F1=0.2005)
  Directional -> Accuracy: 0.4459, MCC: -0.0753, F1: 0.5060

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41804 | val 1.38595
  Epoch 020 - train 0.06046 | val 3.32547
  Epoch 022 - train 0.03549 | val 3.60182
  Classification -> best τ=0.425 (val F1=0.3050)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49937 | val 1.13833
  Epoch 020 - train 0.14663 | val 2.09878
  Epoch 025 - train 0.04784 | val 2.80578
  Classification -> best τ=0.510 (val F1=0.3887)
  Directional -> Accuracy: 0.6136, MCC: 0.2418, F1: 0.7018

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.58613 | val 2.32727
  Epoch 020 - train 0.34885 | val 2.92035
  Epoch 021 - train 0.26906 | val 2.13058
  Classification -> best τ=0.410 (val F1=0.1367)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49595 | val 6.36121
  Epoch 020 - train 0.15534 | val 31.40232
  Epoch 021 - train 0.10775 | val 31.03799
  Classification -> best τ=0.410 (val F1=0.4102)
  Directional -> Accuracy: 0.5208, MCC: 0.0241, F1: 0.6230

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.31919 | val 2.96189
  Epoch 020 - train 0.02616 | val 5.93523
  Epoch 021 - train 0.02025 | val 6.19074
  Classification -> best τ=0.510 (val F1=0.1438)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.58470 | val 1.42572
  Epoch 020 - train 0.21729 | val 2.49373
  Epoch 021 - train 0.24736 | val 2.47120
  Classification -> best τ=0.475 (val F1=0.2807)
  Directional -> Accuracy: 0.5455, MCC: 0.1887, F1: 0.5946

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.34849 | val 0.84696
  Epoch 020 - train 0.03032 | val 1.71584
  Epoch 028 - train 0.00307 | val 2.92341
  Classification -> best τ=0.225 (val F1=0.3705)
  Directional -> Accuracy: 0.4872, MCC: 0.1267, F1: 0.6154

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.32480 | val 1.53257
  Epoch 020 - train 0.02765 | val 3.17392
  Epoch 023 - train 0.01700 | val 3.41259
  Classification -> best τ=0.390 (val F1=0.2817)
  Directional -> Accuracy: 0.6522, MCC: 0.3114, F1: 0.3846

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.50364 | val 0.96726
  Epoch 020 - train 0.14504 | val 1.36043
  Epoch 021 - train 0.11417 | val 1.80087
  Classification -> best τ=0.510 (val F1=0.1579)
  Directional -> Accuracy: 0.5821, MCC: 0.0419, F1: 0.1250

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.47706 | val 3.87881
  Epoch 020 - train 0.14376 | val 6.78562
  Epoch 022 - train 0.09728 | val 5.87976
  Classification -> best τ=0.485 (val F1=0.1043)
  Directional -> Accuracy: 0.4681, MCC: 0.1325, F1: 0.6269

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.53746 | val 1.47723
  Epoch 020 - train 0.24753 | val 2.85477
  Epoch 021 - train 0.20415 | val 2.99868
  Classification -> best τ=0.465 (val F1=0.1336)
  Directional -> Accuracy: 0.6000, MCC: 0.2527, F1: 0.5000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49166 | val 0.85985
  Epoch 020 - train 0.12109 | val 1.72209
  Epoch 021 - train 0.08767 | val 1.51572
  Classification -> best τ=0.425 (val F1=0.3121)
  Directional -> Accuracy: 0.5833, MCC: 0.1662, F1: 0.4444

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.53582 | val 1.33389
  Epoch 020 - train 0.26157 | val 3.50167
  Epoch 021 - train 0.43002 | val 4.19207
  Classification -> best τ=0.570 (val F1=0.1285)
  Directional -> Accuracy: 0.4483, MCC: -0.0976, F1: 0.3600

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.53275 | val 1.08042
  Epoch 020 - train 0.16887 | val 4.31914
  Epoch 021 - train 0.11569 | val 5.34108
  Classification -> best τ=0.405 (val F1=0.1662)
  Directional -> Accuracy: 0.5306, MCC: 0.0554, F1: 0.4889

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61621 | val 1.08109
  Epoch 020 - train 0.28921 | val 2.53760
  Epoch 022 - train 0.23019 | val 3.02607
  Classification -> best τ=0.480 (val F1=0.2719)
  Directional -> Accuracy: 0.5373, MCC: 0.0000, F1: 0.6990

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.49722 | val 1.36488
  Epoch 020 - train 0.23896 | val 3.38367
  Epoch 022 - train 0.16342 | val 3.68125
  Classification -> best τ=0.510 (val F1=0.3808)
  Directional -> Accuracy: 0.6071, MCC: 0.0608, F1: 0.7442

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.57980 | val 0.70145
  Epoch 020 - train 0.32234 | val 0.69054
  Epoch 030 - train 0.08211 | val 1.76418
  Epoch 037 - train 0.01529 | val 2.50286
  Classification -> best τ=0.475 (val F1=0.3434)
  Directional -> Accuracy: 0.5479, MCC: -0.0829, F1: 0.6972

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54091 | val 0.95573
  Epoch 020 - train 0.08929 | val 2.32528
  Epoch 023 - train 0.06390 | val 3.23670
  Classification -> best τ=0.420 (val F1=0.2483)
  Directional -> Accuracy: 0.5000, MCC: 0.1646, F1: 0.3111

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.56099 | val 1.11884
  Epoch 020 - train 0.25325 | val 1.29566
  Epoch 022 - train 0.21556 | val 2.42715
  Classification -> best τ=0.505 (val F1=0.2069)
  Directional -> Accuracy: 0.5000, MCC: -0.0555, F1: 0.6087

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.47614 | val 1.78894
  Epoch 020 - train 0.15307 | val 3.61547
  Epoch 021 - train 0.23940 | val 3.70494
  Classification -> best τ=0.505 (val F1=0.2411)
  Directional -> Accuracy: 0.6000, MCC: 0.0801, F1: 0.7273

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.54064 | val 1.26347
  Epoch 020 - train 0.20667 | val 2.87734
  Epoch 021 - train 0.17570 | val 3.16141
  Classification -> best τ=0.595 (val F1=0.1332)
  Directional -> Accuracy: 0.4603, MCC: -0.2201, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62709 | val 0.95340
  Epoch 020 - train 0.13018 | val 0.99629
  Epoch 026 - train 0.01416 | val 1.64763
  Classification -> best τ=0.590 (val F1=0.4209)
  Directional -> Accuracy: 0.3455, MCC: -0.2786, F1: 0.3077

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50521 | val 0.70314
  Epoch 020 - train 0.19131 | val 1.52231
  Epoch 022 - train 0.16454 | val 2.27010
  Classification -> best τ=0.525 (val F1=0.2819)
  Directional -> Accuracy: 0.4603, MCC: -0.0891, F1: 0.3929

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.40984 | val 1.23714
  Epoch 020 - train 0.06121 | val 2.73939
  Epoch 022 - train 0.02929 | val 2.70864
  Classification -> best τ=0.580 (val F1=0.4023)
  Directional -> Accuracy: 0.4151, MCC: -0.1706, F1: 0.0606

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28466 | val 5.86642
  Epoch 020 - train 0.00666 | val 5.81776
  Epoch 021 - train 0.00854 | val 5.91182
  Classification -> best τ=0.565 (val F1=0.3327)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43018 | val 0.81397
  Epoch 020 - train 0.08685 | val 0.75778
  Epoch 030 - train 0.01275 | val 1.59048
  Epoch 037 - train 0.00927 | val 2.04046
  Classification -> best τ=0.660 (val F1=0.4052)
  Directional -> Accuracy: 0.4792, MCC: 0.0396, F1: 0.3902

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42817 | val 2.04241
  Epoch 020 - train 0.09552 | val 3.31678
  Epoch 021 - train 0.08526 | val 3.65172
  Classification -> best τ=0.430 (val F1=0.2011)
  Directional -> Accuracy: 0.5556, MCC: 0.0936, F1: 0.6250

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.40623 | val 2.06204
  Epoch 020 - train 0.09364 | val 3.66691
  Epoch 021 - train 0.05571 | val 4.31124
  Classification -> best τ=0.535 (val F1=0.1529)
  Directional -> Accuracy: 0.5500, MCC: 0.1005, F1: 0.5714

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.40012 | val 1.30596
  Epoch 020 - train 0.04868 | val 2.20107
  Epoch 022 - train 0.05017 | val 2.13176
  Classification -> best τ=0.605 (val F1=0.2187)
  Directional -> Accuracy: 0.5500, MCC: 0.0335, F1: 0.6897

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.35136 | val 1.28152
  Epoch 020 - train 0.04210 | val 1.83955
  Epoch 023 - train 0.02359 | val 2.36765
  Classification -> best τ=0.495 (val F1=0.3310)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56980 | val 0.83565
  Epoch 020 - train 0.13729 | val 1.99867
  Epoch 022 - train 0.12099 | val 2.33101
  Classification -> best τ=0.255 (val F1=0.3411)
  Directional -> Accuracy: 0.5714, MCC: 0.1660, F1: 0.5588

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41430 | val 2.11830
  Epoch 020 - train 0.04289 | val 2.55844
  Epoch 021 - train 0.04760 | val 3.22692
  Classification -> best τ=0.455 (val F1=0.2576)
  Directional -> Accuracy: 0.4490, MCC: -0.0877, F1: 0.5091

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48843 | val 0.88834
  Epoch 020 - train 0.13135 | val 2.74906
  Epoch 021 - train 0.14460 | val 2.85378
  Classification -> best τ=0.380 (val F1=0.2449)
  Directional -> Accuracy: 0.6562, MCC: 0.2890, F1: 0.7317

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.36066 | val 2.03596
  Epoch 020 - train 0.11417 | val 3.55685
  Epoch 022 - train 0.07383 | val 3.85208
  Classification -> best τ=0.600 (val F1=0.2614)
  Directional -> Accuracy: 0.4898, MCC: -0.1414, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.58287 | val 1.71203
  Epoch 020 - train 0.20757 | val 4.30523
  Epoch 022 - train 0.15468 | val 5.01414
  Classification -> best τ=0.500 (val F1=0.2816)
  Directional -> Accuracy: 0.6111, MCC: 0.2109, F1: 0.4878

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40615 | val 1.30828
  Epoch 020 - train 0.07462 | val 3.28568
  Epoch 021 - train 0.03572 | val 3.51676
  Classification -> best τ=0.430 (val F1=0.1210)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43794 | val 0.62024
  Epoch 020 - train 0.09995 | val 1.74150
  Epoch 030 - train 0.00881 | val 2.25814
  Classification -> best τ=0.560 (val F1=0.5587)
  Directional -> Accuracy: 0.4000, MCC: 0.0434, F1: 0.4906

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53364 | val 2.46367
  Epoch 020 - train 0.29538 | val 3.48048
  Epoch 021 - train 0.28140 | val 3.46021
  Classification -> best τ=0.525 (val F1=0.1738)
  Directional -> Accuracy: 0.5833, MCC: 0.1809, F1: 0.6512

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.34598 | val 1.32704
  Epoch 020 - train 0.06579 | val 2.17934
  Epoch 023 - train 0.02079 | val 2.53532
  Classification -> best τ=0.455 (val F1=0.0521)
  Directional -> Accuracy: 0.4186, MCC: -0.1635, F1: 0.3243

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14701 | val 1.54768
  Epoch 020 - train 0.00244 | val 2.51297
  Epoch 024 - train 0.00163 | val 2.56815
  Classification -> best τ=0.520 (val F1=0.5136)
  Directional -> Accuracy: 0.6154, MCC: 0.1618, F1: 0.7170

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42646 | val 2.42187
  Epoch 020 - train 0.06461 | val 2.89494
  Epoch 023 - train 0.03635 | val 2.92664
  Classification -> best τ=0.540 (val F1=0.2564)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.48188 | val 1.32075
  Epoch 020 - train 0.20375 | val 1.96788
  Epoch 021 - train 0.23006 | val 2.17456
  Classification -> best τ=0.520 (val F1=0.1984)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.54178 | val 2.38991
  Epoch 020 - train 0.20710 | val 4.09906
  Epoch 021 - train 0.19554 | val 4.31406
  Classification -> best τ=0.395 (val F1=0.2429)
  Directional -> Accuracy: 0.4815, MCC: -0.0371, F1: 0.5000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.52110 | val 1.06806
  Epoch 020 - train 0.11586 | val 3.12097
  Epoch 021 - train 0.13109 | val 3.21086
  Classification -> best τ=0.460 (val F1=0.2953)
  Directional -> Accuracy: 0.5294, MCC: 0.0891, F1: 0.6364

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46376 | val 2.14286
  Epoch 020 - train 0.25213 | val 7.91885
  Epoch 022 - train 0.12389 | val 8.42786
  Classification -> best τ=0.525 (val F1=0.3310)
  Directional -> Accuracy: 0.5094, MCC: 0.0037, F1: 0.6667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.57299 | val 0.75961
  Epoch 020 - train 0.45349 | val 1.34959

[I 2026-02-19 02:38:55,559] Trial 51 finished with value: 0.2677340474124773 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.0054554502982690585, 'weight_decay': 1.1320078734379874e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.3732123467366237, 'early_stopping_min_delta': 0.0008255070849794669}. Best is trial 10 with value: 0.2688998415931245.

  Classification -> best τ=0.430 (val F1=0.3606)
  Directional -> Accuracy: 0.4483, MCC: -0.1419, F1: 0.6190

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2677340474124773
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57728 | val 0.95981
  Epoch 020 - train 0.25275 | val 2.46705
  Epoch 021 - train 0.24990 | val 2.85361
  Classification -> best τ=0.505 (val F1=0.1974)
  Directional -> Accuracy: 0.4459, MCC: -0.0181, F1: 0.6095

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45182 | val 0.76666
  Epoch 020 - train 0.09967 | val 1.04175
  Epoch 022 - train 0.08526 | val 1.18782
  Classification -> best τ=0.475 (val F1=0.1987)
  Directional -> Accuracy: 0.6047, MCC: 0.0473, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.49963 | val 1.70944
  Epoch 020 - train 0.21234 | val 2.40141
  Epoch 023 - train 0.12814 | val 3.23075
  Classification -> best τ=0.435 (val F1=0.2043)
  Directional -> Accuracy: 0.5000, MCC: -0.0554, F1: 0.6452

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.56087 | val 4.24199
  Epoch 020 - train 0.32822 | val 3.65983
  Epoch 021 - train 0.28415 | val 2.82420
  Classification -> best τ=0.515 (val F1=0.1696)
  Directional -> Accuracy: 0.3889, MCC: -0.2369, F1: 0.4500

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55601 | val 0.83691
  Epoch 020 - train 0.30464 | val 2.11980
  Epoch 021 - train 0.30992 | val 2.52199
  Classification -> best τ=0.475 (val F1=0.4638)
  Directional -> Accuracy: 0.6667, MCC: 0.3500, F1: 0.6364

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45903 | val 0.87326
  Epoch 020 - train 0.09053 | val 1.72779
  Epoch 022 - train 0.07685 | val 2.68043
  Classification -> best τ=0.595 (val F1=0.2567)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.51099 | val 0.91635
  Epoch 020 - train 0.12492 | val 2.42925
  Epoch 021 - train 0.08597 | val 2.65406
  Classification -> best τ=0.670 (val F1=0.1287)
  Directional -> Accuracy: 0.6061, MCC: 0.1491, F1: 0.0714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.34605 | val 0.93983
  Epoch 020 - train 0.01074 | val 3.08857
  Epoch 026 - train 0.00348 | val 3.42930
  Classification -> best τ=0.330 (val F1=0.3637)
  Directional -> Accuracy: 0.5641, MCC: 0.1326, F1: 0.5405

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.35127 | val 1.40076
  Epoch 020 - train 0.02828 | val 2.87660
  Epoch 022 - train 0.02874 | val 3.40286
  Classification -> best τ=0.435 (val F1=0.3292)
  Directional -> Accuracy: 0.5870, MCC: 0.3220, F1: 0.6667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.51312 | val 2.26835
  Epoch 020 - train 0.34060 | val 1.83202
  Epoch 021 - train 0.26906 | val 1.85339
  Classification -> best τ=0.655 (val F1=0.2345)
  Directional -> Accuracy: 0.3881, MCC: -0.1546, F1: 0.5176

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.51560 | val 3.16256
  Epoch 020 - train 0.30956 | val 5.17219
  Epoch 021 - train 0.29909 | val 3.97163
  Classification -> best τ=0.575 (val F1=0.2881)
  Directional -> Accuracy: 0.5745, MCC: 0.1065, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.56581 | val 1.48026
  Epoch 020 - train 0.22084 | val 3.97678
  Epoch 021 - train 0.23549 | val 4.00840
  Classification -> best τ=0.480 (val F1=0.1567)
  Directional -> Accuracy: 0.6364, MCC: 0.2859, F1: 0.6154

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44686 | val 1.44158
  Epoch 020 - train 0.07068 | val 1.72691
  Epoch 025 - train 0.02035 | val 2.70994
  Classification -> best τ=0.770 (val F1=0.3348)
  Directional -> Accuracy: 0.5208, MCC: 0.0295, F1: 0.4103

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.49263 | val 1.39696
  Epoch 020 - train 0.12153 | val 4.19021
  Epoch 021 - train 0.11311 | val 4.35224
  Classification -> best τ=0.545 (val F1=0.0296)
  Directional -> Accuracy: 0.4828, MCC: -0.0195, F1: 0.3182

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.50674 | val 2.02077
  Epoch 020 - train 0.19266 | val 3.72800
  Epoch 021 - train 0.17029 | val 3.85738
  Classification -> best τ=0.395 (val F1=0.2125)
  Directional -> Accuracy: 0.5102, MCC: -0.0161, F1: 0.3684

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50749 | val 1.32052
  Epoch 020 - train 0.17355 | val 3.13041
  Epoch 021 - train 0.12317 | val 3.35542
  Classification -> best τ=0.635 (val F1=0.3071)
  Directional -> Accuracy: 0.6716, MCC: 0.3968, F1: 0.7609

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.53914 | val 1.11456
  Epoch 020 - train 0.28051 | val 1.93585
  Epoch 022 - train 0.20435 | val 2.15181
  Classification -> best τ=0.635 (val F1=0.1874)
  Directional -> Accuracy: 0.3393, MCC: -0.2488, F1: 0.0976

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.58680 | val 0.73131
  Epoch 020 - train 0.42263 | val 0.79892
  Epoch 030 - train 0.33388 | val 1.81112
  Epoch 032 - train 0.18845 | val 1.79950
  Classification -> best τ=0.545 (val F1=0.2473)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.47391 | val 1.67977
  Epoch 020 - train 0.17805 | val 2.08899
  Epoch 022 - train 0.14092 | val 2.73899
  Classification -> best τ=0.470 (val F1=0.2477)
  Directional -> Accuracy: 0.5645, MCC: 0.2771, F1: 0.4490

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48920 | val 1.43410
  Epoch 020 - train 0.18145 | val 3.54124
  Epoch 021 - train 0.11713 | val 2.72250
  Classification -> best τ=0.545 (val F1=0.1941)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48374 | val 1.60514
  Epoch 020 - train 0.10417 | val 2.82583
  Epoch 021 - train 0.13329 | val 2.59955
  Classification -> best τ=0.570 (val F1=0.2197)
  Directional -> Accuracy: 0.4444, MCC: 0.0237, F1: 0.2857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.64907 | val 0.90234
  Epoch 020 - train 0.16814 | val 4.29893
  Epoch 021 - train 0.20503 | val 4.64175
  Classification -> best τ=0.400 (val F1=0.1211)
  Directional -> Accuracy: 0.4921, MCC: -0.0041, F1: 0.6444

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54703 | val 1.80334
  Epoch 020 - train 0.12796 | val 2.81556
  Epoch 023 - train 0.05993 | val 4.03990
  Classification -> best τ=0.615 (val F1=0.3093)
  Directional -> Accuracy: 0.5273, MCC: 0.0903, F1: 0.5185

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48589 | val 0.73756
  Epoch 020 - train 0.20491 | val 1.37505
  Epoch 021 - train 0.14243 | val 1.51459
  Classification -> best τ=0.475 (val F1=0.1564)
  Directional -> Accuracy: 0.5714, MCC: 0.1589, F1: 0.6087

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53972 | val 2.48377
  Epoch 020 - train 0.23918 | val 4.35373
  Epoch 021 - train 0.11587 | val 5.34847
  Classification -> best τ=0.540 (val F1=0.4393)
  Directional -> Accuracy: 0.5849, MCC: 0.1847, F1: 0.5769

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.36553 | val 2.71886
  Epoch 020 - train 0.03560 | val 5.43696
  Epoch 021 - train 0.00622 | val 5.50839
  Classification -> best τ=0.600 (val F1=0.1809)
  Directional -> Accuracy: 0.3810, MCC: -0.2123, F1: 0.4091

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.38770 | val 0.95079
  Epoch 020 - train 0.14098 | val 0.93676
  Epoch 030 - train 0.00469 | val 1.77517
  Epoch 031 - train 0.00317 | val 1.79018
  Classification -> best τ=0.755 (val F1=0.5096)
  Directional -> Accuracy: 0.4167, MCC: -0.1195, F1: 0.3636

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47711 | val 1.55794
  Epoch 020 - train 0.07111 | val 3.01001
  Epoch 021 - train 0.08605 | val 2.90528
  Classification -> best τ=0.395 (val F1=0.2649)
  Directional -> Accuracy: 0.5185, MCC: 0.1163, F1: 0.3158

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48322 | val 1.42781
  Epoch 020 - train 0.03694 | val 2.07273
  Epoch 027 - train 0.00407 | val 2.34868
  Classification -> best τ=0.110 (val F1=0.2928)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.32503 | val 1.09744
  Epoch 020 - train 0.02260 | val 1.72202
  Epoch 022 - train 0.00946 | val 1.84713
  Classification -> best τ=0.680 (val F1=0.1869)
  Directional -> Accuracy: 0.4000, MCC: -0.1846, F1: 0.3684

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59391 | val 0.77636
  Epoch 020 - train 0.10932 | val 1.66659
  Epoch 026 - train 0.03552 | val 2.60590
  Classification -> best τ=0.490 (val F1=0.3687)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.52573 | val 1.57673
  Epoch 020 - train 0.20588 | val 1.35837
  Epoch 026 - train 0.14957 | val 1.83784
  Classification -> best τ=0.450 (val F1=0.2615)
  Directional -> Accuracy: 0.5143, MCC: 0.1300, F1: 0.3462

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51873 | val 2.33631
  Epoch 020 - train 0.03276 | val 3.26708
  Epoch 021 - train 0.02124 | val 3.34525
  Classification -> best τ=0.525 (val F1=0.3148)
  Directional -> Accuracy: 0.5510, MCC: 0.1535, F1: 0.0833

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53851 | val 1.02435
  Epoch 020 - train 0.20368 | val 2.53039
  Epoch 021 - train 0.19250 | val 2.86308
  Classification -> best τ=0.330 (val F1=0.3117)
  Directional -> Accuracy: 0.5938, MCC: 0.1455, F1: 0.6905

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.31634 | val 4.79259
  Epoch 020 - train 0.03232 | val 5.24032
  Epoch 021 - train 0.02281 | val 5.59697
  Classification -> best τ=0.545 (val F1=0.2224)
  Directional -> Accuracy: 0.5714, MCC: 0.1833, F1: 0.3226

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55048 | val 2.62564
  Epoch 020 - train 0.27374 | val 3.19284
  Epoch 021 - train 0.20473 | val 3.42695
  Classification -> best τ=0.335 (val F1=0.1223)
  Directional -> Accuracy: 0.5185, MCC: 0.0104, F1: 0.3810

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40095 | val 2.25118
  Epoch 020 - train 0.02391 | val 4.59102
  Epoch 023 - train 0.00815 | val 5.18903
  Classification -> best τ=0.320 (val F1=0.2763)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39974 | val 1.49024
  Epoch 020 - train 0.03600 | val 2.14817
  Epoch 026 - train 0.00422 | val 2.45688
  Classification -> best τ=0.410 (val F1=0.4432)
  Directional -> Accuracy: 0.2889, MCC: -0.3050, F1: 0.4483

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52354 | val 1.86569
  Epoch 020 - train 0.33941 | val 3.34264
  Epoch 021 - train 0.28563 | val 3.37914
  Classification -> best τ=0.500 (val F1=0.1444)
  Directional -> Accuracy: 0.5139, MCC: 0.1187, F1: 0.6729

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45060 | val 0.98800
  Epoch 020 - train 0.07044 | val 2.01867
  Epoch 023 - train 0.02230 | val 2.63897
  Classification -> best τ=0.370 (val F1=0.2138)
  Directional -> Accuracy: 0.4419, MCC: -0.1154, F1: 0.3333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.19553 | val 1.32596
  Epoch 020 - train 0.00506 | val 2.26292
  Epoch 025 - train 0.00148 | val 2.37445
  Classification -> best τ=0.445 (val F1=0.4966)
  Directional -> Accuracy: 0.6154, MCC: 0.1533, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.28753 | val 1.85163
  Epoch 020 - train 0.02420 | val 3.59521
  Epoch 023 - train 0.00887 | val 3.70126
  Classification -> best τ=0.435 (val F1=0.3162)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.51455 | val 0.93150
  Epoch 020 - train 0.19255 | val 2.21394
  Epoch 021 - train 0.17049 | val 1.92254
  Classification -> best τ=0.430 (val F1=0.1604)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45336 | val 2.45031
  Epoch 020 - train 0.18301 | val 3.30831
  Epoch 021 - train 0.14401 | val 3.59272
  Classification -> best τ=0.480 (val F1=0.2569)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4906

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.48040 | val 1.32887
  Epoch 020 - train 0.07460 | val 3.16551
  Epoch 021 - train 0.06086 | val 3.61934
  Classification -> best τ=0.490 (val F1=0.3065)
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57187 | val 1.46736
  Epoch 020 - train 0.14401 | val 7.58507
  Epoch 022 - train 0.09323 | val 10.30139
  Classification -> best τ=0.395 (val F1=0.3872)
  Directional -> Accuracy: 0.5283, MCC: 0.1413, F1: 0.6835

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61004 | val 2.77689
  Epoch 020 - train 0.19298 | val 2.46066
  Epoch 024 - train 0.13633 | val 1.57297

[I 2026-02-19 02:50:46,496] Trial 52 finished with value: 0.26297360752248855 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.005443356974995109, 'weight_decay': 1.325820979954573e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.3591807152714361, 'early_stopping_min_delta': 0.001221102916624469}. Best is trial 10 with value: 0.2688998415931245.

  Classification -> best τ=0.370 (val F1=0.3236)
  Directional -> Accuracy: 0.5172, MCC: 0.0776, F1: 0.6000

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26297360752248855
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68864 | val 1.03256
  Epoch 020 - train 0.55901 | val 1.55185
  Epoch 025 - train 0.58235 | val 1.99166
  Classification -> best τ=0.505 (val F1=0.2444)
  Directional -> Accuracy: 0.5270, MCC: -0.0365, F1: 0.1860

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.70971 | val 0.73193
  Epoch 020 - train 0.55401 | val 1.29167
  Epoch 022 - train 0.59318 | val 0.89355
  Classification -> best τ=0.460 (val F1=0.1373)
  Directional -> Accuracy: 0.6047, MCC: 0.1487, F1: 0.6909

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65184 | val 0.77793
  Epoch 020 - train 0.63563 | val 0.87292
  Epoch 030 - train 0.50140 | val 0.98127
  Epoch 033 - train 0.41400 | val 1.32451
  Classification -> best τ=0.440 (val F1=0.2971)
  Directional -> Accuracy: 0.5682, MCC: 0.1727, F1: 0.6984

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66725 | val 0.67657
  Epoch 020 - train 0.60317 | val 1.11501
  Epoch 030 - train 0.54846 | val 1.64312
  Epoch 037 - train 0.40785 | val 1.18282
  Classification -> best τ=0.485 (val F1=0.3421)
  Directional -> Accuracy: 0.4722, MCC: 0.0196, F1: 0.1739

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57920 | val 1.17327
  Epoch 020 - train 0.43498 | val 1.52053
  Epoch 022 - train 0.44103 | val 2.09363
  Classification -> best τ=0.545 (val F1=0.4189)
  Directional -> Accuracy: 0.6250, MCC: 0.3539, F1: 0.4706

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68070 | val 1.45229
  Epoch 020 - train 0.39594 | val 4.49513
  Epoch 021 - train 0.32986 | val 4.95842
  Classification -> best τ=0.535 (val F1=0.2567)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.64527 | val 1.05297
  Epoch 020 - train 0.53122 | val 1.20016
  Epoch 021 - train 0.48738 | val 1.30107
  Classification -> best τ=0.455 (val F1=0.2251)
  Directional -> Accuracy: 0.5303, MCC: 0.1636, F1: 0.5867

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68494 | val 0.65146
  Epoch 020 - train 0.49334 | val 0.53911
  Epoch 030 - train 0.45234 | val 1.58112
  Epoch 039 - train 0.25152 | val 1.76781
  Classification -> best τ=0.220 (val F1=0.4472)
  Directional -> Accuracy: 0.4359, MCC: -0.0301, F1: 0.5926

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66632 | val 1.51899
  Epoch 020 - train 0.41321 | val 1.67136
  Epoch 022 - train 0.37198 | val 1.91149
  Classification -> best τ=0.405 (val F1=0.2988)
  Directional -> Accuracy: 0.6087, MCC: 0.2038, F1: 0.5500

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.73952 | val 0.94190
  Epoch 020 - train 0.61011 | val 0.75911
  Epoch 021 - train 0.52556 | val 0.79173
  Classification -> best τ=0.410 (val F1=0.2016)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.59037 | val 0.81784
  Epoch 020 - train 0.45606 | val 2.04621
  Epoch 026 - train 0.43443 | val 3.88168
  Classification -> best τ=0.615 (val F1=0.4584)
  Directional -> Accuracy: 0.6170, MCC: 0.2152, F1: 0.4000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61637 | val 1.46352
  Epoch 020 - train 0.57453 | val 2.40258
  Epoch 021 - train 0.55748 | val 2.47935
  Classification -> best τ=0.515 (val F1=0.0957)
  Directional -> Accuracy: 0.5636, MCC: 0.2003, F1: 0.4000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65128 | val 0.73795
  Epoch 020 - train 0.51392 | val 0.85839
  Epoch 027 - train 0.42972 | val 0.96760
  Classification -> best τ=0.505 (val F1=0.4427)
  Directional -> Accuracy: 0.5417, MCC: 0.0825, F1: 0.2143

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62402 | val 0.70039
  Epoch 020 - train 0.56618 | val 0.80432
  Epoch 022 - train 0.50745 | val 0.85801
  Classification -> best τ=0.255 (val F1=0.2962)
  Directional -> Accuracy: 0.5172, MCC: 0.0117, F1: 0.6585

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66670 | val 0.81373
  Epoch 020 - train 0.54039 | val 0.91602
  Epoch 027 - train 0.49170 | val 1.54945
  Classification -> best τ=0.505 (val F1=0.1968)
  Directional -> Accuracy: 0.5714, MCC: 0.1118, F1: 0.1600

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.72318 | val 0.80848
  Epoch 020 - train 0.57018 | val 1.55041
  Epoch 021 - train 0.55739 | val 1.46643
  Classification -> best τ=0.645 (val F1=0.3795)
  Directional -> Accuracy: 0.5522, MCC: 0.0887, F1: 0.6154

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66645 | val 1.27621
  Epoch 020 - train 0.50176 | val 2.05827
  Epoch 021 - train 0.48258 | val 2.40739
  Classification -> best τ=0.565 (val F1=0.1313)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67994 | val 0.76384
  Epoch 020 - train 0.63589 | val 1.08753
  Epoch 022 - train 0.61786 | val 1.19611
  Classification -> best τ=0.535 (val F1=0.2127)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.67398 | val 0.73508
  Epoch 020 - train 0.54570 | val 1.18394
  Epoch 026 - train 0.44867 | val 1.57214
  Classification -> best τ=0.300 (val F1=0.2360)
  Directional -> Accuracy: 0.4839, MCC: 0.1321, F1: 0.2727

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66143 | val 0.83510
  Epoch 020 - train 0.53040 | val 1.56528
  Epoch 023 - train 0.51764 | val 2.12210
  Classification -> best τ=0.340 (val F1=0.2443)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.56342 | val 1.71040
  Epoch 020 - train 0.39600 | val 3.52167
  Epoch 021 - train 0.43985 | val 3.27957
  Classification -> best τ=0.510 (val F1=0.1308)
  Directional -> Accuracy: 0.4667, MCC: 0.0200, F1: 0.4000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69496 | val 0.94443
  Epoch 020 - train 0.62283 | val 1.26688
  Epoch 022 - train 0.61732 | val 1.33831
  Classification -> best τ=0.580 (val F1=0.1237)
  Directional -> Accuracy: 0.4444, MCC: -0.1216, F1: 0.3396

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66922 | val 0.75541
  Epoch 020 - train 0.63182 | val 0.95166
  Epoch 030 - train 0.44360 | val 1.42024
  Epoch 037 - train 0.33565 | val 1.95859
  Classification -> best τ=0.715 (val F1=0.4207)
  Directional -> Accuracy: 0.4364, MCC: -0.0369, F1: 0.2791

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68270 | val 0.80915
  Epoch 020 - train 0.63431 | val 0.83241
  Epoch 021 - train 0.54822 | val 0.78251
  Classification -> best τ=0.470 (val F1=0.2278)
  Directional -> Accuracy: 0.5397, MCC: 0.1387, F1: 0.6420

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63799 | val 0.69711
  Epoch 020 - train 0.51358 | val 0.86510
  Epoch 023 - train 0.58638 | val 0.88995
  Classification -> best τ=0.420 (val F1=0.4235)
  Directional -> Accuracy: 0.5283, MCC: 0.1299, F1: 0.3902

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51072 | val 3.44660
  Epoch 020 - train 0.37969 | val 6.02140
  Epoch 021 - train 0.43217 | val 7.42883
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.61491 | val 1.37819
  Epoch 020 - train 0.63502 | val 1.39892
  Epoch 025 - train 0.45794 | val 1.23593
  Classification -> best τ=0.455 (val F1=0.4303)
  Directional -> Accuracy: 0.5000, MCC: 0.0436, F1: 0.4783

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63793 | val 0.84930
  Epoch 020 - train 0.50445 | val 1.62949
  Epoch 021 - train 0.46299 | val 1.49219
  Classification -> best τ=0.445 (val F1=0.0935)
  Directional -> Accuracy: 0.5185, MCC: 0.0696, F1: 0.4348

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.72096 | val 2.01410
  Epoch 020 - train 0.44380 | val 2.32126
  Epoch 021 - train 0.48705 | val 1.69502
  Classification -> best τ=0.525 (val F1=0.3333)
  Directional -> Accuracy: 0.4750, MCC: -0.0599, F1: 0.2759

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62429 | val 0.99176
  Epoch 020 - train 0.51925 | val 0.66337
  Epoch 024 - train 0.47640 | val 0.67200
  Classification -> best τ=0.585 (val F1=0.3233)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65880 | val 0.79241
  Epoch 020 - train 0.52967 | val 1.08291
  Epoch 025 - train 0.54344 | val 1.31554
  Classification -> best τ=0.390 (val F1=0.4898)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66086 | val 0.71575
  Epoch 020 - train 0.63537 | val 0.88557
  Epoch 030 - train 0.39070 | val 1.73372
  Epoch 034 - train 0.33164 | val 2.56337
  Classification -> best τ=0.685 (val F1=0.2405)
  Directional -> Accuracy: 0.4857, MCC: 0.0689, F1: 0.2800

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63182 | val 0.93514
  Epoch 020 - train 0.40155 | val 1.66093
  Epoch 022 - train 0.36129 | val 1.71985
  Classification -> best τ=0.465 (val F1=0.2694)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61476 | val 0.75609
  Epoch 020 - train 0.56697 | val 1.18276
  Epoch 030 - train 0.44387 | val 1.56200
  Epoch 038 - train 0.30784 | val 2.17744
  Classification -> best τ=0.165 (val F1=0.3921)
  Directional -> Accuracy: 0.4219, MCC: -0.0946, F1: 0.1395

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60856 | val 1.89952
  Epoch 020 - train 0.40209 | val 2.64376
  Epoch 021 - train 0.47772 | val 2.63303
  Classification -> best τ=0.530 (val F1=0.2875)
  Directional -> Accuracy: 0.6122, MCC: 0.2434, F1: 0.4865

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70853 | val 1.05847
  Epoch 020 - train 0.40530 | val 2.98799
  Epoch 021 - train 0.51645 | val 3.70301
  Classification -> best τ=0.490 (val F1=0.2225)
  Directional -> Accuracy: 0.5556, MCC: 0.1397, F1: 0.6000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60162 | val 4.34108
  Epoch 020 - train 0.29147 | val 5.91158
  Epoch 021 - train 0.32880 | val 6.71174
  Classification -> best τ=0.465 (val F1=0.2841)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63894 | val 0.67493
  Epoch 020 - train 0.53891 | val 0.65349
  Epoch 030 - train 0.34462 | val 0.75732
  Epoch 034 - train 0.35081 | val 0.79618
  Classification -> best τ=0.410 (val F1=0.3864)
  Directional -> Accuracy: 0.3111, MCC: -0.2132, F1: 0.4746

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63348 | val 1.42402
  Epoch 020 - train 0.52886 | val 2.32814
  Epoch 022 - train 0.54239 | val 2.47257
  Classification -> best τ=0.405 (val F1=0.2657)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64035 | val 0.68447
  Epoch 020 - train 0.56256 | val 0.75848
  Epoch 023 - train 0.55838 | val 0.80610
  Classification -> best τ=0.400 (val F1=0.2212)
  Directional -> Accuracy: 0.4186, MCC: -0.1835, F1: 0.1935

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59441 | val 0.94263
  Epoch 020 - train 0.36269 | val 2.59738
  Epoch 029 - train 0.19947 | val 2.08038
  Classification -> best τ=0.535 (val F1=0.4109)
  Directional -> Accuracy: 0.5128, MCC: 0.0598, F1: 0.5128

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66908 | val 0.87589
  Epoch 020 - train 0.61039 | val 1.02931
  Epoch 021 - train 0.55762 | val 1.26129
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67672 | val 0.76986
  Epoch 020 - train 0.56746 | val 0.76431
  Epoch 024 - train 0.52057 | val 0.75585
  Classification -> best τ=0.560 (val F1=0.2070)
  Directional -> Accuracy: 0.3585, MCC: -0.3731, F1: 0.5000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64535 | val 1.05732
  Epoch 020 - train 0.57453 | val 1.51542
  Epoch 022 - train 0.55817 | val 1.80750
  Classification -> best τ=0.450 (val F1=0.2907)
  Directional -> Accuracy: 0.5185, MCC: 0.0639, F1: 0.1875

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65186 | val 0.79069
  Epoch 020 - train 0.54350 | val 0.96463
  Epoch 030 - train 0.33666 | val 2.61941
  Epoch 032 - train 0.33937 | val 3.01709
  Classification -> best τ=0.595 (val F1=0.2441)
  Directional -> Accuracy: 0.5098, MCC: 0.0277, F1: 0.5763

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67444 | val 2.54856
  Epoch 020 - train 0.53497 | val 3.30747
  Epoch 026 - train 0.45696 | val 3.39905
  Classification -> best τ=0.305 (val F1=0.2279)

[I 2026-02-19 03:03:47,480] Trial 53 finished with value: 0.2732635960250114 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.0030593324734686693, 'weight_decay': 1.5207829224578209e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.5526731879158233, 'early_stopping_min_delta': 0.0012682796271165492}. Best is trial 53 with value: 0.2732635960250114.

  Classification -> best τ=0.320 (val F1=0.3339)
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2732635960250114
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'stance_label', 'stance_score']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.72126 | val 0.70443
  Epoch 020 - train 0.66679 | val 1.17204
  Epoch 025 - train 0.60963 | val 0.92607
  Classification -> best τ=0.480 (val F1=0.2589)
  Directional -> Accuracy: 0.5135, MCC: -0.0843, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.70392 | val 0.77953
  Epoch 020 - train 0.60307 | val 1.09922
  Epoch 021 - train 0.66055 | val 1.17035
  Classification -> best τ=0.490 (val F1=0.3480)
  Directional -> Accuracy: 0.3488, MCC: -0.2304, F1: 0.2222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.67115 | val 0.80760
  Epoch 020 - train 0.62304 | val 1.24795
  Epoch 021 - train 0.61886 | val 1.29463
  Classification -> best τ=0.525 (val F1=0.4010)
  Directional -> Accuracy: 0.5455, MCC: 0.1461, F1: 0.3750

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67309 | val 1.10947
  Epoch 020 - train 0.65462 | val 1.87757
  Epoch 021 - train 0.66011 | val 1.84558
  Classification -> best τ=0.500 (val F1=0.1491)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.62193 | val 1.00306
  Epoch 020 - train 0.47312 | val 0.98983
  Epoch 023 - train 0.43384 | val 1.04924
  Classification -> best τ=0.460 (val F1=0.4345)
  Directional -> Accuracy: 0.6458, MCC: 0.3612, F1: 0.5405

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.69172 | val 0.74636
  Epoch 020 - train 0.53289 | val 0.88350
  Epoch 021 - train 0.54135 | val 0.91088
  Classification -> best τ=0.480 (val F1=0.0181)
  Directional -> Accuracy: 0.5227, MCC: 0.1525, F1: 0.0870

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66278 | val 0.66759
  Epoch 020 - train 0.64164 | val 0.69348
  Epoch 030 - train 0.51963 | val 1.37010
  Classification -> best τ=0.445 (val F1=0.2502)
  Directional -> Accuracy: 0.4848, MCC: 0.1240, F1: 0.5854

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.56475 | val 0.95456
  Epoch 020 - train 0.50451 | val 1.57506
  Epoch 021 - train 0.56286 | val 1.97624
  Classification -> best τ=0.480 (val F1=0.2041)
  Directional -> Accuracy: 0.5897, MCC: 0.1463, F1: 0.4667

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67425 | val 0.84395
  Epoch 020 - train 0.57549 | val 1.40948
  Epoch 023 - train 0.55136 | val 1.56837
  Classification -> best τ=0.455 (val F1=0.2817)
  Directional -> Accuracy: 0.6304, MCC: 0.2370, F1: 0.5405

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.67983 | val 1.08708
  Epoch 020 - train 0.59380 | val 1.24631
  Epoch 021 - train 0.63154 | val 1.27059
  Classification -> best τ=0.410 (val F1=0.4337)
  Directional -> Accuracy: 0.4328, MCC: 0.1043, F1: 0.5957

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64291 | val 1.56782
  Epoch 020 - train 0.61241 | val 3.17742
  Epoch 021 - train 0.58432 | val 3.26605
  Classification -> best τ=0.590 (val F1=0.2679)
  Directional -> Accuracy: 0.4894, MCC: 0.0355, F1: 0.5714

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64529 | val 1.38072
  Epoch 020 - train 0.58484 | val 2.21462
  Epoch 023 - train 0.56617 | val 2.16754
  Classification -> best τ=0.480 (val F1=0.2406)
  Directional -> Accuracy: 0.6545, MCC: 0.3053, F1: 0.6984

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.64966 | val 1.23178
  Epoch 020 - train 0.47525 | val 1.03862
  Epoch 028 - train 0.39461 | val 1.37907
  Classification -> best τ=0.405 (val F1=0.3885)
  Directional -> Accuracy: 0.5208, MCC: 0.0384, F1: 0.4889

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.68986 | val 0.83664
  Epoch 020 - train 0.63343 | val 0.85550
  Epoch 021 - train 0.60303 | val 0.82264
  Classification -> best τ=0.490 (val F1=0.2574)
  Directional -> Accuracy: 0.5690, MCC: 0.1441, F1: 0.5455

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.65506 | val 0.70788
  Epoch 020 - train 0.64965 | val 1.24409
  Epoch 021 - train 0.62168 | val 1.20905
  Classification -> best τ=0.565 (val F1=0.1594)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67544 | val 0.72275
  Epoch 020 - train 0.63796 | val 1.08138
  Epoch 024 - train 0.63078 | val 1.22874
  Classification -> best τ=0.475 (val F1=0.2355)
  Directional -> Accuracy: 0.3881, MCC: -0.2117, F1: 0.3051

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67811 | val 2.39760
  Epoch 020 - train 0.64682 | val 1.04686
  Epoch 021 - train 0.64543 | val 1.25286
  Classification -> best τ=0.610 (val F1=0.1887)
  Directional -> Accuracy: 0.4286, MCC: 0.1548, F1: 0.1111

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67678 | val 0.87532
  Epoch 020 - train 0.64259 | val 1.06849
  Epoch 023 - train 0.62840 | val 1.10659
  Classification -> best τ=0.485 (val F1=0.2210)
  Directional -> Accuracy: 0.4658, MCC: 0.1486, F1: 0.2041

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69874 | val 0.91302
  Epoch 020 - train 0.60026 | val 2.02403
  Epoch 025 - train 0.59714 | val 2.50167
  Classification -> best τ=0.360 (val F1=0.3636)
  Directional -> Accuracy: 0.4677, MCC: 0.0966, F1: 0.2326

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68327 | val 0.70206
  Epoch 020 - train 0.60706 | val 0.83116
  Epoch 021 - train 0.57510 | val 0.84951
  Classification -> best τ=0.495 (val F1=0.2582)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65853 | val 0.64226
  Epoch 020 - train 0.62532 | val 0.69510
  Epoch 030 - train 0.49300 | val 1.53142
  Epoch 031 - train 0.48002 | val 1.70295
  Classification -> best τ=0.580 (val F1=0.3777)
  Directional -> Accuracy: 0.4222, MCC: 0.1231, F1: 0.0714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70743 | val 0.76785
  Epoch 020 - train 0.64071 | val 1.12464
  Epoch 022 - train 0.58767 | val 1.23805
  Classification -> best τ=0.520 (val F1=0.1947)
  Directional -> Accuracy: 0.5079, MCC: 0.0242, F1: 0.5867

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71091 | val 0.71755
  Epoch 020 - train 0.66767 | val 0.73971
  Epoch 023 - train 0.65638 | val 0.78744
  Classification -> best τ=0.590 (val F1=0.3360)
  Directional -> Accuracy: 0.4182, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67458 | val 0.68957
  Epoch 020 - train 0.64133 | val 0.69834
  Epoch 022 - train 0.65879 | val 0.71934
  Classification -> best τ=0.490 (val F1=0.1961)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62788 | val 0.69345
  Epoch 020 - train 0.51336 | val 1.08593
  Epoch 023 - train 0.55383 | val 1.25438
  Classification -> best τ=0.465 (val F1=0.3709)
  Directional -> Accuracy: 0.5849, MCC: 0.2350, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.72586 | val 0.68384
  Epoch 020 - train 0.62946 | val 1.01735
  Epoch 030 - train 0.41437 | val 2.44719
  Classification -> best τ=0.580 (val F1=0.4284)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72944 | val 1.20231
  Epoch 020 - train 0.58863 | val 1.50389
  Epoch 022 - train 0.61035 | val 1.57816
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.64470 | val 0.72708
  Epoch 020 - train 0.62078 | val 0.87956
  Epoch 021 - train 0.59180 | val 0.87137
  Classification -> best τ=0.465 (val F1=0.3040)
  Directional -> Accuracy: 0.5370, MCC: 0.2626, F1: 0.2424

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64337 | val 1.01155
  Epoch 020 - train 0.52547 | val 2.64143
  Epoch 021 - train 0.55295 | val 2.41957
  Classification -> best τ=0.520 (val F1=0.2000)
  Directional -> Accuracy: 0.5500, MCC: 0.1005, F1: 0.5263

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.76577 | val 0.64462
  Epoch 020 - train 0.66261 | val 0.75059
  Epoch 030 - train 0.51657 | val 0.68539
  Classification -> best τ=0.695 (val F1=0.1869)
  Directional -> Accuracy: 0.4750, MCC: 0.1448, F1: 0.0870

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64040 | val 0.70787
  Epoch 020 - train 0.60401 | val 0.73178
  Epoch 023 - train 0.59523 | val 0.78022
  Classification -> best τ=0.625 (val F1=0.2928)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.66382 | val 0.72515
  Epoch 020 - train 0.57732 | val 0.84975
  Epoch 024 - train 0.60771 | val 1.00689
  Classification -> best τ=0.290 (val F1=0.2976)
  Directional -> Accuracy: 0.5571, MCC: 0.1328, F1: 0.5507

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71199 | val 0.89368
  Epoch 020 - train 0.56191 | val 1.07937
  Epoch 022 - train 0.54059 | val 1.19839
  Classification -> best τ=0.570 (val F1=0.2536)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.62024 | val 0.70796
  Epoch 020 - train 0.57068 | val 1.12706
  Epoch 021 - train 0.54881 | val 1.14988
  Classification -> best τ=0.420 (val F1=0.3587)
  Directional -> Accuracy: 0.6250, MCC: 0.2190, F1: 0.7209

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55425 | val 3.29597
  Epoch 020 - train 0.42824 | val 4.03689
  Epoch 021 - train 0.40049 | val 4.07649
  Classification -> best τ=0.545 (val F1=0.0176)
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66281 | val 0.76565
  Epoch 020 - train 0.61255 | val 1.36475
  Epoch 021 - train 0.58555 | val 1.07984
  Classification -> best τ=0.450 (val F1=0.2089)
  Directional -> Accuracy: 0.5000, MCC: 0.0408, F1: 0.5846

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64714 | val 2.00686
  Epoch 020 - train 0.43349 | val 2.32233
  Epoch 021 - train 0.47840 | val 2.37561
  Classification -> best τ=0.510 (val F1=0.0110)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.73776 | val 0.71476
  Epoch 020 - train 0.55567 | val 0.82296
  Epoch 030 - train 0.45779 | val 1.09735
  Epoch 031 - train 0.45853 | val 1.12267
  Classification -> best τ=0.340 (val F1=0.4798)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64631 | val 0.89995
  Epoch 020 - train 0.58947 | val 2.27899
  Epoch 021 - train 0.56658 | val 2.30778
  Classification -> best τ=0.410 (val F1=0.1367)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67240 | val 0.76369
  Epoch 020 - train 0.59378 | val 1.01698
  Epoch 022 - train 0.61658 | val 1.23474
  Classification -> best τ=0.410 (val F1=0.2011)
  Directional -> Accuracy: 0.4651, MCC: -0.1249, F1: 0.6102

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69158 | val 0.89233
  Epoch 020 - train 0.58702 | val 0.70594
  Epoch 030 - train 0.43941 | val 0.99470
  Epoch 031 - train 0.57498 | val 1.10301
  Classification -> best τ=0.530 (val F1=0.4862)
  Directional -> Accuracy: 0.4103, MCC: -0.0927, F1: 0.2581

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68507 | val 1.04531
  Epoch 020 - train 0.62772 | val 1.07998
  Epoch 021 - train 0.53830 | val 1.18830
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68477 | val 1.19546
  Epoch 020 - train 0.68797 | val 1.01974
  Epoch 021 - train 0.67760 | val 0.98972
  Classification -> best τ=0.465 (val F1=0.2338)
  Directional -> Accuracy: 0.4717, MCC: 0.1262, F1: 0.0667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66590 | val 1.76632
  Epoch 020 - train 0.59835 | val 2.02588
  Epoch 021 - train 0.59593 | val 1.85774
  Classification -> best τ=0.490 (val F1=0.3591)
  Directional -> Accuracy: 0.5926, MCC: 0.2067, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65110 | val 0.82694
  Epoch 020 - train 0.62348 | val 1.05065
  Epoch 021 - train 0.62582 | val 1.09824
  Classification -> best τ=0.475 (val F1=0.2758)
  Directional -> Accuracy: 0.5686, MCC: 0.1449, F1: 0.6071

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65733 | val 2.62268
  Epoch 020 - train 0.57839 | val 4.40032
  Epoch 021 - train 0.54620 | val 4.40317
  Classification -> best τ=0.665 (val F1=0.2337)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.74406 | val 0.67957
  Epoch 020 - train 0.66295 | val 0.71739
  Epoch 025 - train 0.60616 | val 0.70032
  Classification -> best τ=0.535 (val F1=0.3598)

[I 2026-02-19 03:15:40,499] Trial 54 finished with value: 0.2587510583519484 and parameters: {'feature_set': 'stance', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.002951663795104518, 'weight_decay': 1.1884521037885349e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.8502541681706048, 'early_stopping_min_delta': 0.0008979069337368803}. Best is trial 53 with value: 0.2732635960250114.

Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.72207 | val 0.71480
  Epoch 020 - train 0.59109 | val 2.81121
  Epoch 028 - train 0.49314 | val 2.81490
  Classification -> best τ=0.785 (val F1=0.2895)
  Directional -> Accuracy: 0.5270, MCC: -0.0673, F1: 0.1026

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56877 | val 0.76997
  Epoch 020 - train 0.39108 | val 2.02913
  Epoch 024 - train 0.44851 | val 2.52301
  Classification -> best τ=0.575 (val F1=0.1734)
  Directional -> Accuracy: 0.3721, MCC: -0.1520, F1: 0.0690

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65148 | val 1.25192
  Epoch 020 - train 0.48305 | val 1.53918
  Epoch 025 - train 0.30287 | val 3.57525
  Classification -> best τ=0.510 (val F1=0.3327)
  Directional -> Accuracy: 0.5227, MCC: 0.0415, F1: 0.5532

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69095 | val 0.69062
  Epoch 020 - train 0.65777 | val 0.69701
  Epoch 030 - train 0.50390 | val 2.48519
  Epoch 037 - train 0.42577 | val 0.71082
  Classification -> best τ=0.580 (val F1=0.2383)
  Directional -> Accuracy: 0.5139, MCC: 0.2231, F1: 0.1860

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60080 | val 1.34292
  Epoch 020 - train 0.38183 | val 2.00341
  Epoch 021 - train 0.33242 | val 1.24561
  Classification -> best τ=0.690 (val F1=0.4398)
  Directional -> Accuracy: 0.5833, MCC: 0.2253, F1: 0.4444

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.62339 | val 2.26816
  Epoch 020 - train 0.30536 | val 1.50804
  Epoch 026 - train 0.14777 | val 1.88197
  Classification -> best τ=0.465 (val F1=0.3180)
  Directional -> Accuracy: 0.5909, MCC: 0.1890, F1: 0.5263

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65268 | val 0.79772
  Epoch 020 - train 0.41271 | val 1.41727
  Epoch 025 - train 0.31344 | val 1.58462
  Classification -> best τ=0.625 (val F1=0.1913)
  Directional -> Accuracy: 0.4697, MCC: -0.0561, F1: 0.4262

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.55054 | val 0.73720
  Epoch 020 - train 0.29285 | val 0.57216
  Epoch 028 - train 0.11934 | val 0.59418
  Classification -> best τ=0.260 (val F1=0.4763)
  Directional -> Accuracy: 0.5385, MCC: 0.1379, F1: 0.5909

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56076 | val 4.04726
  Epoch 020 - train 0.26355 | val 4.65081
  Epoch 023 - train 0.29565 | val 6.46290
  Classification -> best τ=0.485 (val F1=0.2817)
  Directional -> Accuracy: 0.4565, MCC: -0.0447, F1: 0.5098

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59176 | val 0.96514
  Epoch 020 - train 0.42023 | val 2.51032
  Epoch 021 - train 0.37080 | val 2.39294
  Classification -> best τ=0.335 (val F1=0.1524)
  Directional -> Accuracy: 0.4328, MCC: -0.0434, F1: 0.5366

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57449 | val 1.89531
  Epoch 020 - train 0.31233 | val 8.29742
  Epoch 021 - train 0.29824 | val 8.10229
  Classification -> best τ=0.570 (val F1=0.2881)
  Directional -> Accuracy: 0.5745, MCC: 0.1065, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58188 | val 2.16017
  Epoch 020 - train 0.36787 | val 4.39729
  Epoch 021 - train 0.38513 | val 4.52235
  Classification -> best τ=0.450 (val F1=0.1394)
  Directional -> Accuracy: 0.6545, MCC: 0.3130, F1: 0.6545

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61643 | val 1.48359
  Epoch 020 - train 0.28445 | val 1.39582
  Epoch 021 - train 0.27594 | val 2.11789
  Classification -> best τ=0.570 (val F1=0.1551)
  Directional -> Accuracy: 0.5625, MCC: 0.1241, F1: 0.3636

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.63393 | val 1.13379
  Epoch 020 - train 0.52111 | val 2.69708
  Epoch 022 - train 0.43975 | val 2.91431
  Classification -> best τ=0.370 (val F1=0.0252)
  Directional -> Accuracy: 0.4483, MCC: -0.0985, F1: 0.3043

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64043 | val 2.67036
  Epoch 020 - train 0.46995 | val 2.01317
  Epoch 023 - train 0.37739 | val 2.57531
  Classification -> best τ=0.485 (val F1=0.1961)
  Directional -> Accuracy: 0.5102, MCC: 0.0778, F1: 0.5862

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.75992 | val 0.80192
  Epoch 020 - train 0.56530 | val 1.24794
  Epoch 021 - train 0.55888 | val 1.45588
  Classification -> best τ=0.325 (val F1=0.1546)
  Directional -> Accuracy: 0.5373, MCC: 0.0000, F1: 0.6990

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62434 | val 1.55863
  Epoch 020 - train 0.40209 | val 2.71999
  Epoch 021 - train 0.40889 | val 2.90113
  Classification -> best τ=0.580 (val F1=0.1874)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66756 | val 0.90091
  Epoch 020 - train 0.48190 | val 1.69207
  Epoch 021 - train 0.47719 | val 0.93125
  Classification -> best τ=0.530 (val F1=0.1829)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.56546 | val 0.96879
  Epoch 020 - train 0.44136 | val 1.60050
  Epoch 024 - train 0.27372 | val 2.67191
  Classification -> best τ=0.570 (val F1=0.2731)
  Directional -> Accuracy: 0.4677, MCC: 0.1317, F1: 0.1951

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60452 | val 1.00786
  Epoch 020 - train 0.40387 | val 1.43320
  Epoch 021 - train 0.35970 | val 1.35400
  Classification -> best τ=0.465 (val F1=0.1782)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53680 | val 1.64529
  Epoch 020 - train 0.38223 | val 3.25675
  Epoch 021 - train 0.34416 | val 2.85699
  Classification -> best τ=0.545 (val F1=0.1754)
  Directional -> Accuracy: 0.4222, MCC: 0.1231, F1: 0.0714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65768 | val 0.92272
  Epoch 020 - train 0.46144 | val 3.49789
  Epoch 022 - train 0.40916 | val 4.27693
  Classification -> best τ=0.385 (val F1=0.2132)
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.62411 | val 0.66446
  Epoch 020 - train 0.47236 | val 0.82564
  Epoch 027 - train 0.24262 | val 1.06470
  Classification -> best τ=0.460 (val F1=0.4810)
  Directional -> Accuracy: 0.3636, MCC: -0.2527, F1: 0.3636

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.64288 | val 0.70923
  Epoch 020 - train 0.49115 | val 0.82073
  Epoch 022 - train 0.43483 | val 0.71281
  Classification -> best τ=0.470 (val F1=0.1961)
  Directional -> Accuracy: 0.5397, MCC: 0.0728, F1: 0.1714

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68456 | val 1.01591
  Epoch 020 - train 0.42720 | val 1.58261
  Epoch 027 - train 0.26399 | val 3.22191
  Classification -> best τ=0.320 (val F1=0.4932)
  Directional -> Accuracy: 0.5094, MCC: 0.0395, F1: 0.4800

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.45913 | val 2.79914
  Epoch 020 - train 0.07963 | val 6.78856
  Epoch 021 - train 0.04859 | val 8.12430
  Classification -> best τ=0.560 (val F1=0.2065)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63223 | val 1.46787
  Epoch 020 - train 0.44204 | val 1.07474
  Epoch 027 - train 0.28327 | val 1.32018
  Classification -> best τ=0.560 (val F1=0.4647)
  Directional -> Accuracy: 0.3958, MCC: -0.1800, F1: 0.3830

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66106 | val 0.84441
  Epoch 020 - train 0.41057 | val 2.01697
  Epoch 025 - train 0.34121 | val 2.81371
  Classification -> best τ=0.370 (val F1=0.3807)
  Directional -> Accuracy: 0.5000, MCC: 0.1821, F1: 0.1290

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.65719 | val 0.85555
  Epoch 020 - train 0.26436 | val 5.33572
  Epoch 023 - train 0.18073 | val 2.88972
  Classification -> best τ=0.685 (val F1=0.4152)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.1667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.69664 | val 1.02587
  Epoch 020 - train 0.47531 | val 1.52879
  Epoch 023 - train 0.25466 | val 1.95969
  Classification -> best τ=0.585 (val F1=0.3074)
  Directional -> Accuracy: 0.6000, MCC: 0.2632, F1: 0.5294

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.50366 | val 1.56642
  Epoch 020 - train 0.26443 | val 2.36399
  Epoch 024 - train 0.19620 | val 2.60941
  Classification -> best τ=0.520 (val F1=0.4775)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68547 | val 1.21518
  Epoch 020 - train 0.51636 | val 1.20647
  Epoch 022 - train 0.46750 | val 1.12413
  Classification -> best τ=0.620 (val F1=0.3001)
  Directional -> Accuracy: 0.5000, MCC: 0.1395, F1: 0.2553

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.57336 | val 1.65074
  Epoch 020 - train 0.37907 | val 3.04774
  Epoch 023 - train 0.26182 | val 2.25167
  Classification -> best τ=0.550 (val F1=0.1448)
  Directional -> Accuracy: 0.5102, MCC: 0.1311, F1: 0.6471

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59478 | val 1.38570
  Epoch 020 - train 0.29309 | val 3.74336
  Epoch 021 - train 0.31569 | val 4.04973
  Classification -> best τ=0.375 (val F1=0.2708)
  Directional -> Accuracy: 0.4375, MCC: -0.0405, F1: 0.1429

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44558 | val 2.17375
  Epoch 020 - train 0.12735 | val 6.13861
  Epoch 021 - train 0.17652 | val 6.67861
  Classification -> best τ=0.665 (val F1=0.1757)
  Directional -> Accuracy: 0.5306, MCC: 0.0743, F1: 0.2069

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.56627 | val 1.05117
  Epoch 020 - train 0.38929 | val 3.79309
  Epoch 021 - train 0.40353 | val 4.17765
  Classification -> best τ=0.495 (val F1=0.1595)
  Directional -> Accuracy: 0.5370, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54511 | val 2.60333
  Epoch 020 - train 0.24148 | val 5.36924
  Epoch 021 - train 0.19735 | val 6.49377
  Classification -> best τ=0.415 (val F1=0.1653)
  Directional -> Accuracy: 0.3864, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.59814 | val 0.67025
  Epoch 020 - train 0.30111 | val 0.85050
  Epoch 024 - train 0.17603 | val 1.09877
  Classification -> best τ=0.650 (val F1=0.5750)
  Directional -> Accuracy: 0.4889, MCC: 0.1000, F1: 0.4889

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70210 | val 1.26699
  Epoch 020 - train 0.62715 | val 1.18961
  Epoch 027 - train 0.47342 | val 2.83586
  Classification -> best τ=0.370 (val F1=0.2788)
  Directional -> Accuracy: 0.5278, MCC: 0.1690, F1: 0.6792

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58855 | val 0.70387
  Epoch 020 - train 0.39565 | val 1.16999
  Epoch 023 - train 0.23977 | val 1.57143
  Classification -> best τ=0.375 (val F1=0.2873)
  Directional -> Accuracy: 0.4651, MCC: -0.0893, F1: 0.5660

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.54663 | val 0.81989
  Epoch 020 - train 0.19146 | val 2.01377
  Epoch 027 - train 0.10633 | val 2.44180
  Classification -> best τ=0.520 (val F1=0.4139)
  Directional -> Accuracy: 0.5897, MCC: 0.1216, F1: 0.6800

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51894 | val 1.86633
  Epoch 020 - train 0.27431 | val 2.38789
  Epoch 021 - train 0.27135 | val 3.19917
  Classification -> best τ=0.480 (val F1=0.3213)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61632 | val 4.02703
  Epoch 020 - train 0.51015 | val 1.68148
  Epoch 021 - train 0.50971 | val 1.55230
  Classification -> best τ=0.445 (val F1=0.0895)
  Directional -> Accuracy: 0.4906, MCC: -0.2228, F1: 0.6582

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60882 | val 1.34104
  Epoch 020 - train 0.40830 | val 3.37868
  Epoch 022 - train 0.41077 | val 3.76672
  Classification -> best τ=0.570 (val F1=0.3313)
  Directional -> Accuracy: 0.5185, MCC: 0.0413, F1: 0.6061

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.62446 | val 0.94681
  Epoch 020 - train 0.43497 | val 1.28577
  Epoch 027 - train 0.28819 | val 3.07242
  Classification -> best τ=0.750 (val F1=0.2513)
  Directional -> Accuracy: 0.5490, MCC: 0.1066, F1: 0.5965

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62303 | val 1.76315
  Epoch 020 - train 0.40994 | val 4.62294
  Epoch 021 - train 0.31628 | val 6.82745
  Classification -> best τ=0.390 (val F1=0.2155)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65709 | val 0.69474
  Epoch 020 - train 0.59421 | val 0.86501
  Epoch 030 - train 0.50847 | val 0.88317
  Epoch 039 - train 0.36235 | val 1.58030

[I 2026-02-19 03:28:01,896] Trial 55 finished with value: 0.2707612260748753 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.009740509312903812, 'weight_decay': 1.7830392279935212e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.8012325020302997, 'early_stopping_min_delta': 0.0013268165599804379}. Best is trial 53 with value: 0.2732635960250114.

  Classification -> best τ=0.440 (val F1=0.2615)
  Directional -> Accuracy: 0.5345, MCC: 0.0316, F1: 0.2703

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2707612260748753
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.62364 | val 2.69566
  Epoch 020 - train 0.48996 | val 1.11666
  Epoch 021 - train 0.46156 | val 2.41949
  Classification -> best τ=0.600 (val F1=0.1388)
  Directional -> Accuracy: 0.4189, MCC: -0.1462, F1: 0.5825

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.63955 | val 0.78497
  Epoch 020 - train 0.37507 | val 0.88519
  Epoch 022 - train 0.44542 | val 1.10552
  Classification -> best τ=0.575 (val F1=0.1987)
  Directional -> Accuracy: 0.4884, MCC: -0.1470, F1: 0.6207

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62401 | val 3.84798
  Epoch 020 - train 0.43463 | val 3.74358
  Epoch 022 - train 0.33165 | val 4.26200
  Classification -> best τ=0.575 (val F1=0.3327)
  Directional -> Accuracy: 0.5000, MCC: 0.0554, F1: 0.2143

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68054 | val 0.70421
  Epoch 020 - train 0.51705 | val 2.63914
  Epoch 030 - train 0.33900 | val 3.79635
  Classification -> best τ=0.505 (val F1=0.1061)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63860 | val 0.62958
  Epoch 020 - train 0.40186 | val 2.65526
  Epoch 030 - train 0.09469 | val 4.29774
  Classification -> best τ=0.595 (val F1=0.4189)
  Directional -> Accuracy: 0.6042, MCC: 0.2648, F1: 0.4865

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60490 | val 1.52313
  Epoch 020 - train 0.33646 | val 3.44073
  Epoch 024 - train 0.23252 | val 3.50456
  Classification -> best τ=0.380 (val F1=0.2976)
  Directional -> Accuracy: 0.5682, MCC: 0.1438, F1: 0.6275

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65139 | val 0.80259
  Epoch 020 - train 0.39834 | val 1.42204
  Epoch 021 - train 0.40847 | val 1.58867
  Classification -> best τ=0.450 (val F1=0.2508)
  Directional -> Accuracy: 0.5909, MCC: 0.2804, F1: 0.6301

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49997 | val 0.66838
  Epoch 020 - train 0.28321 | val 0.96619
  Epoch 030 - train 0.11311 | val 2.21996
  Epoch 032 - train 0.05519 | val 2.65730
  Classification -> best τ=0.100 (val F1=0.2182)
  Directional -> Accuracy: 0.5128, MCC: 0.2538, F1: 0.6415

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56101 | val 1.11390
  Epoch 020 - train 0.27229 | val 2.40057
  Epoch 022 - train 0.24902 | val 2.43096
  Classification -> best τ=0.450 (val F1=0.2504)
  Directional -> Accuracy: 0.4783, MCC: 0.1150, F1: 0.6129

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66013 | val 0.87070
  Epoch 020 - train 0.45043 | val 1.64784
  Epoch 027 - train 0.29763 | val 2.98314
  Classification -> best τ=0.320 (val F1=0.1831)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63822 | val 2.04888
  Epoch 020 - train 0.31000 | val 7.28882
  Epoch 021 - train 0.33256 | val 7.23641
  Classification -> best τ=0.475 (val F1=0.4584)
  Directional -> Accuracy: 0.6383, MCC: 0.3394, F1: 0.3200

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.61576 | val 1.75871
  Epoch 020 - train 0.40202 | val 4.77246
  Epoch 022 - train 0.37886 | val 8.18331
  Classification -> best τ=0.505 (val F1=0.2013)
  Directional -> Accuracy: 0.5091, MCC: 0.0055, F1: 0.5714

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58475 | val 0.89450
  Epoch 020 - train 0.35339 | val 1.61965
  Epoch 021 - train 0.37223 | val 2.35768
  Classification -> best τ=0.540 (val F1=0.2493)
  Directional -> Accuracy: 0.4167, MCC: -0.1716, F1: 0.5333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.65423 | val 0.79142
  Epoch 020 - train 0.37912 | val 1.67596
  Epoch 023 - train 0.34483 | val 1.75999
  Classification -> best τ=0.300 (val F1=0.2573)
  Directional -> Accuracy: 0.5862, MCC: 0.1723, F1: 0.6571

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64622 | val 1.01268
  Epoch 020 - train 0.55198 | val 0.80266
  Epoch 021 - train 0.44865 | val 0.89476
  Classification -> best τ=0.480 (val F1=0.0118)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64266 | val 1.11253
  Epoch 020 - train 0.43613 | val 3.32916
  Epoch 021 - train 0.49652 | val 3.12463
  Classification -> best τ=0.510 (val F1=0.1498)
  Directional -> Accuracy: 0.5373, MCC: 0.0716, F1: 0.5634

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62849 | val 1.46277
  Epoch 020 - train 0.55069 | val 1.78597
  Epoch 022 - train 0.40933 | val 1.94292
  Classification -> best τ=0.695 (val F1=0.2227)
  Directional -> Accuracy: 0.4107, MCC: 0.0290, F1: 0.1081

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64826 | val 2.82957
  Epoch 020 - train 0.57981 | val 0.89617
  Epoch 026 - train 0.44912 | val 1.69496
  Classification -> best τ=0.425 (val F1=0.2340)
  Directional -> Accuracy: 0.6164, MCC: 0.1736, F1: 0.7083

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65604 | val 1.10570
  Epoch 020 - train 0.41418 | val 1.73193
  Epoch 022 - train 0.32264 | val 2.13885
  Classification -> best τ=0.620 (val F1=0.2697)
  Directional -> Accuracy: 0.4194, MCC: -0.0298, F1: 0.0526

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62262 | val 2.20969
  Epoch 020 - train 0.39263 | val 2.12381
  Epoch 021 - train 0.42049 | val 1.79992
  Classification -> best τ=0.365 (val F1=0.1690)
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54213 | val 0.95343
  Epoch 020 - train 0.34489 | val 1.01694
  Epoch 021 - train 0.29268 | val 1.18898
  Classification -> best τ=0.590 (val F1=0.2360)
  Directional -> Accuracy: 0.4000, MCC: -0.0801, F1: 0.1818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.61805 | val 1.29999
  Epoch 020 - train 0.43340 | val 11.45784
  Epoch 022 - train 0.42486 | val 10.46338
  Classification -> best τ=0.490 (val F1=0.2402)
  Directional -> Accuracy: 0.5556, MCC: 0.1305, F1: 0.6316

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66104 | val 0.71497
  Epoch 020 - train 0.52775 | val 0.81466
  Epoch 027 - train 0.37333 | val 1.89571
  Classification -> best τ=0.505 (val F1=0.3858)
  Directional -> Accuracy: 0.6000, MCC: 0.2121, F1: 0.6207

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62109 | val 0.74856
  Epoch 020 - train 0.43376 | val 0.77232
  Epoch 021 - train 0.39836 | val 0.84489
  Classification -> best τ=0.470 (val F1=0.2972)
  Directional -> Accuracy: 0.4762, MCC: -0.0182, F1: 0.6118

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68408 | val 1.46177
  Epoch 020 - train 0.27973 | val 2.60453
  Epoch 022 - train 0.28883 | val 2.97926
  Classification -> best τ=0.535 (val F1=0.4611)
  Directional -> Accuracy: 0.5472, MCC: 0.1852, F1: 0.4000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.40940 | val 5.14762
  Epoch 020 - train 0.18589 | val 8.89046
  Epoch 023 - train 0.04898 | val 10.06711
  Classification -> best τ=0.650 (val F1=0.2626)
  Directional -> Accuracy: 0.5714, MCC: 0.0913, F1: 0.4000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62244 | val 0.92674
  Epoch 020 - train 0.37369 | val 1.14250
  Epoch 021 - train 0.33306 | val 0.86822
  Classification -> best τ=0.495 (val F1=0.0903)
  Directional -> Accuracy: 0.5208, MCC: 0.0792, F1: 0.5106

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58364 | val 1.28039
  Epoch 020 - train 0.35699 | val 1.61058
  Epoch 022 - train 0.33805 | val 2.70050
  Classification -> best τ=0.520 (val F1=0.2665)
  Directional -> Accuracy: 0.5000, MCC: 0.1208, F1: 0.1818

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.52951 | val 1.19980
  Epoch 020 - train 0.19973 | val 3.52366
  Epoch 024 - train 0.13617 | val 4.53525
  Classification -> best τ=0.465 (val F1=0.2537)
  Directional -> Accuracy: 0.4750, MCC: -0.0949, F1: 0.6316

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58191 | val 0.67582
  Epoch 020 - train 0.32330 | val 5.93885
  Epoch 027 - train 0.12477 | val 11.43493
  Classification -> best τ=0.685 (val F1=0.1974)
  Directional -> Accuracy: 0.4750, MCC: 0.0060, F1: 0.3226

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59002 | val 0.89492
  Epoch 020 - train 0.26317 | val 1.77511
  Epoch 024 - train 0.23846 | val 2.53501
  Classification -> best τ=0.445 (val F1=0.4809)
  Directional -> Accuracy: 0.5319, MCC: 0.1506, F1: 0.6857

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64588 | val 0.77710
  Epoch 020 - train 0.48890 | val 1.00612
  Epoch 026 - train 0.39792 | val 1.78581
  Classification -> best τ=0.270 (val F1=0.2904)
  Directional -> Accuracy: 0.5714, MCC: 0.1660, F1: 0.5588

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51635 | val 1.63975
  Epoch 020 - train 0.26648 | val 3.36456
  Epoch 021 - train 0.26861 | val 3.68555
  Classification -> best τ=0.550 (val F1=0.1182)
  Directional -> Accuracy: 0.6531, MCC: 0.3110, F1: 0.6531

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60015 | val 1.83830
  Epoch 020 - train 0.31698 | val 3.29544
  Epoch 022 - train 0.27752 | val 3.71222
  Classification -> best τ=0.355 (val F1=0.3310)
  Directional -> Accuracy: 0.5781, MCC: 0.1429, F1: 0.7273

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42161 | val 6.79718
  Epoch 020 - train 0.18145 | val 9.97276
  Epoch 021 - train 0.19475 | val 10.52653
  Classification -> best τ=0.645 (val F1=0.3825)
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60980 | val 0.78484
  Epoch 020 - train 0.37372 | val 2.09465
  Epoch 022 - train 0.35563 | val 2.13027
  Classification -> best τ=0.320 (val F1=0.1183)
  Directional -> Accuracy: 0.4444, MCC: -0.0875, F1: 0.5312

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46015 | val 2.62263
  Epoch 020 - train 0.27544 | val 6.53554
  Epoch 021 - train 0.25066 | val 8.21148
  Classification -> best τ=0.435 (val F1=0.2146)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55485 | val 0.73790
  Epoch 020 - train 0.32080 | val 0.65677
  Epoch 025 - train 0.23077 | val 0.86794
  Classification -> best τ=0.380 (val F1=0.5899)
  Directional -> Accuracy: 0.3111, MCC: -0.2132, F1: 0.4746

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59390 | val 1.12022
  Epoch 020 - train 0.45863 | val 2.24854
  Epoch 021 - train 0.42371 | val 3.36395
  Classification -> best τ=0.470 (val F1=0.1927)
  Directional -> Accuracy: 0.5417, MCC: 0.2085, F1: 0.6857

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58161 | val 0.72708
  Epoch 020 - train 0.33688 | val 1.33975
  Epoch 021 - train 0.25921 | val 1.03531
  Classification -> best τ=0.440 (val F1=0.1981)
  Directional -> Accuracy: 0.5581, MCC: 0.1140, F1: 0.5957

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.57823 | val 0.77796
  Epoch 020 - train 0.30480 | val 3.04553
  Epoch 029 - train 0.23662 | val 2.45854
  Classification -> best τ=0.370 (val F1=0.5913)
  Directional -> Accuracy: 0.4872, MCC: -0.1655, F1: 0.6296

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56050 | val 1.79634
  Epoch 020 - train 0.27708 | val 3.20107
  Epoch 021 - train 0.26494 | val 3.48628
  Classification -> best τ=0.515 (val F1=0.5899)
  Directional -> Accuracy: 0.3778, MCC: -0.0787, F1: 0.5172

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68462 | val 0.69915
  Epoch 020 - train 0.50953 | val 1.20631
  Epoch 021 - train 0.47906 | val 1.52888
  Classification -> best τ=0.505 (val F1=0.1155)
  Directional -> Accuracy: 0.5094, MCC: 0.0667, F1: 0.4091

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64329 | val 1.70513
  Epoch 020 - train 0.43472 | val 4.25942
  Epoch 021 - train 0.35814 | val 5.04693
  Classification -> best τ=0.590 (val F1=0.2000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.59437 | val 1.22437
  Epoch 020 - train 0.31952 | val 2.90906
  Epoch 024 - train 0.24423 | val 2.67532
  Classification -> best τ=0.580 (val F1=0.2450)
  Directional -> Accuracy: 0.5882, MCC: 0.1828, F1: 0.6182

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54197 | val 2.81805
  Epoch 020 - train 0.33899 | val 7.62398
  Epoch 021 - train 0.30009 | val 5.52136
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66444 | val 0.63929
  Epoch 020 - train 0.56461 | val 1.09857
  Epoch 029 - train 0.34460 | val 1.49006

[I 2026-02-19 03:40:07,135] Trial 56 finished with value: 0.2642764985624934 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.008633243655924031, 'weight_decay': 1.4661551390080591e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.8302950275869572, 'early_stopping_min_delta': 0.0013038548030175957}. Best is trial 53 with value: 0.2732635960250114.

  Classification -> best τ=0.375 (val F1=0.4532)
  Directional -> Accuracy: 0.4483, MCC: -0.1419, F1: 0.6190

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2642764985624934
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66397 | val 1.14575
  Epoch 020 - train 0.44376 | val 1.51668
  Epoch 024 - train 0.37600 | val 1.72416
  Classification -> best τ=0.465 (val F1=0.3260)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.60710 | val 1.05104
  Epoch 020 - train 0.14688 | val 2.70892
  Epoch 021 - train 0.11249 | val 2.65622
  Classification -> best τ=0.545 (val F1=0.0644)
  Directional -> Accuracy: 0.3953, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.61213 | val 0.95707
  Epoch 020 - train 0.09203 | val 5.39976
  Epoch 021 - train 0.11635 | val 5.27754
  Classification -> best τ=0.595 (val F1=0.2205)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69070 | val 0.97340
  Epoch 020 - train 0.49348 | val 2.32657
  Epoch 021 - train 0.40333 | val 1.17935
  Classification -> best τ=0.500 (val F1=0.1512)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.44083 | val 2.71691
  Epoch 020 - train 0.09457 | val 4.63783
  Epoch 021 - train 0.12495 | val 4.25197
  Classification -> best τ=0.595 (val F1=0.3477)
  Directional -> Accuracy: 0.5208, MCC: 0.2000, F1: 0.1481

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41003 | val 2.52447
  Epoch 020 - train 0.07360 | val 5.64969
  Epoch 021 - train 0.06485 | val 6.54955
  Classification -> best τ=0.465 (val F1=0.2885)
  Directional -> Accuracy: 0.6364, MCC: 0.2835, F1: 0.6800

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59882 | val 0.85853
  Epoch 020 - train 0.35065 | val 2.76625
  Epoch 024 - train 0.23602 | val 3.00056
  Classification -> best τ=0.645 (val F1=0.1287)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41837 | val 0.75867
  Epoch 020 - train 0.10781 | val 4.64264
  Epoch 026 - train 0.08646 | val 5.78546
  Classification -> best τ=0.285 (val F1=0.2582)
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.39734 | val 1.16916
  Epoch 020 - train 0.07045 | val 2.25451
  Epoch 023 - train 0.05391 | val 2.28621
  Classification -> best τ=0.330 (val F1=0.4430)
  Directional -> Accuracy: 0.5870, MCC: 0.2583, F1: 0.6415

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.57708 | val 3.92620
  Epoch 020 - train 0.33106 | val 1.82638
  Epoch 022 - train 0.24931 | val 2.00381
  Classification -> best τ=0.475 (val F1=0.4231)
  Directional -> Accuracy: 0.4179, MCC: -0.0419, F1: 0.5714

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64818 | val 5.61101
  Epoch 020 - train 0.14212 | val 11.24740
  Epoch 021 - train 0.17223 | val 8.71946
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.72204 | val 1.09719
  Epoch 020 - train 0.27659 | val 3.59504
  Epoch 023 - train 0.25450 | val 3.78090
  Classification -> best τ=0.390 (val F1=0.1451)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50457 | val 0.91048
  Epoch 020 - train 0.11793 | val 2.12280
  Epoch 021 - train 0.11001 | val 2.65325
  Classification -> best τ=0.630 (val F1=0.2020)
  Directional -> Accuracy: 0.5208, MCC: 0.0268, F1: 0.3784

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.74729 | val 1.27125
  Epoch 020 - train 0.34572 | val 2.34689
  Epoch 026 - train 0.18122 | val 3.44996
  Classification -> best τ=0.420 (val F1=0.2105)
  Directional -> Accuracy: 0.5345, MCC: 0.1056, F1: 0.3721

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63873 | val 1.19082
  Epoch 020 - train 0.27886 | val 10.05964
  Epoch 023 - train 0.16963 | val 13.78305
  Classification -> best τ=0.405 (val F1=0.1373)
  Directional -> Accuracy: 0.4286, MCC: -0.1118, F1: 0.5882

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.67442 | val 1.18025
  Epoch 020 - train 0.25809 | val 5.09898
  Epoch 022 - train 0.28032 | val 5.89577
  Classification -> best τ=0.465 (val F1=0.3150)
  Directional -> Accuracy: 0.5672, MCC: 0.1452, F1: 0.7071

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.69560 | val 1.14565
  Epoch 020 - train 0.25443 | val 2.93263
  Epoch 024 - train 0.09394 | val 4.62785
  Classification -> best τ=0.380 (val F1=0.1669)
  Directional -> Accuracy: 0.5536, MCC: -0.0533, F1: 0.6914

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61224 | val 0.78372
  Epoch 020 - train 0.43593 | val 1.00227
  Epoch 024 - train 0.33381 | val 1.83300
  Classification -> best τ=0.555 (val F1=0.1684)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58960 | val 1.04538
  Epoch 020 - train 0.11761 | val 3.30658
  Epoch 022 - train 0.13651 | val 3.51852
  Classification -> best τ=0.410 (val F1=0.2392)
  Directional -> Accuracy: 0.5323, MCC: 0.2236, F1: 0.3830

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60664 | val 0.89005
  Epoch 020 - train 0.29075 | val 2.02303
  Epoch 023 - train 0.22065 | val 3.28842
  Classification -> best τ=0.520 (val F1=0.2562)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60689 | val 1.65327
  Epoch 020 - train 0.15008 | val 4.20588
  Epoch 021 - train 0.12631 | val 5.64968
  Classification -> best τ=0.595 (val F1=0.1348)
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69425 | val 1.34119
  Epoch 020 - train 0.30678 | val 3.47927
  Epoch 022 - train 0.30723 | val 3.88463
  Classification -> best τ=0.550 (val F1=0.1651)
  Directional -> Accuracy: 0.4286, MCC: -0.1423, F1: 0.4375

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.55324 | val 1.86300
  Epoch 020 - train 0.30052 | val 2.67456
  Epoch 021 - train 0.20961 | val 2.29316
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5818, MCC: 0.0000, F1: 0.7356

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65363 | val 0.70871
  Epoch 020 - train 0.22622 | val 0.80533
  Epoch 022 - train 0.26611 | val 1.25761
  Classification -> best τ=0.420 (val F1=0.1533)
  Directional -> Accuracy: 0.5397, MCC: 0.1727, F1: 0.6588

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53377 | val 1.60447
  Epoch 020 - train 0.14872 | val 4.53033
  Epoch 023 - train 0.14629 | val 6.01798
  Classification -> best τ=0.405 (val F1=0.3289)
  Directional -> Accuracy: 0.5849, MCC: 0.1945, F1: 0.5600

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.32112 | val 4.93210
  Epoch 020 - train 0.05466 | val 8.14064
  Epoch 021 - train 0.01477 | val 7.83143
  Classification -> best τ=0.570 (val F1=0.3506)
  Directional -> Accuracy: 0.6429, MCC: 0.3717, F1: 0.6809

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46855 | val 1.34963
  Epoch 020 - train 0.13842 | val 1.94816
  Epoch 022 - train 0.11915 | val 1.53126
  Classification -> best τ=0.595 (val F1=0.4052)
  Directional -> Accuracy: 0.5417, MCC: 0.1143, F1: 0.5417

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.54775 | val 1.48423
  Epoch 020 - train 0.20905 | val 4.58494
  Epoch 021 - train 0.21923 | val 4.66843
  Classification -> best τ=0.460 (val F1=0.1677)
  Directional -> Accuracy: 0.5185, MCC: 0.2252, F1: 0.1875

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49335 | val 2.24570
  Epoch 020 - train 0.05345 | val 2.51014
  Epoch 022 - train 0.03136 | val 2.11411
  Classification -> best τ=0.535 (val F1=0.3333)
  Directional -> Accuracy: 0.5250, MCC: 0.0560, F1: 0.6122

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.54804 | val 0.71364
  Epoch 020 - train 0.22452 | val 1.80997
  Epoch 022 - train 0.18469 | val 1.75072
  Classification -> best τ=0.585 (val F1=0.2482)
  Directional -> Accuracy: 0.4750, MCC: -0.1899, F1: 0.6316

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60652 | val 1.00868
  Epoch 020 - train 0.23611 | val 3.40704
  Epoch 023 - train 0.24533 | val 3.26952
  Classification -> best τ=0.435 (val F1=0.3780)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61894 | val 1.10986
  Epoch 020 - train 0.30811 | val 1.74132
  Epoch 021 - train 0.27342 | val 1.43008
  Classification -> best τ=0.450 (val F1=0.2718)
  Directional -> Accuracy: 0.5000, MCC: 0.0863, F1: 0.3396

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.52430 | val 1.52814
  Epoch 020 - train 0.15176 | val 2.99524
  Epoch 021 - train 0.15762 | val 2.40375
  Classification -> best τ=0.540 (val F1=0.2010)
  Directional -> Accuracy: 0.4898, MCC: -0.1311, F1: 0.0741

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57226 | val 1.23993
  Epoch 020 - train 0.20507 | val 3.74691
  Epoch 022 - train 0.13152 | val 4.03091
  Classification -> best τ=0.400 (val F1=0.3855)
  Directional -> Accuracy: 0.5312, MCC: 0.1078, F1: 0.4828

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.30802 | val 3.99103
  Epoch 020 - train 0.07262 | val 7.32278
  Epoch 021 - train 0.06916 | val 7.90956
  Classification -> best τ=0.680 (val F1=0.1956)
  Directional -> Accuracy: 0.4694, MCC: -0.2021, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60756 | val 1.18081
  Epoch 020 - train 0.23570 | val 3.56742
  Epoch 021 - train 0.30083 | val 3.54764
  Classification -> best τ=0.420 (val F1=0.2816)
  Directional -> Accuracy: 0.5556, MCC: 0.0875, F1: 0.4000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44290 | val 0.92698
  Epoch 020 - train 0.15573 | val 5.03272
  Epoch 022 - train 0.11749 | val 6.44932
  Classification -> best τ=0.385 (val F1=0.4091)
  Directional -> Accuracy: 0.3864, MCC: -0.1266, F1: 0.2703

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39806 | val 0.82231
  Epoch 020 - train 0.05182 | val 1.96949
  Epoch 024 - train 0.02913 | val 2.72933
  Classification -> best τ=0.430 (val F1=0.4264)
  Directional -> Accuracy: 0.4222, MCC: -0.1890, F1: 0.2778

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61267 | val 1.63904
  Epoch 020 - train 0.32062 | val 3.16240
  Epoch 026 - train 0.23073 | val 4.37501
  Classification -> best τ=0.265 (val F1=0.3103)
  Directional -> Accuracy: 0.5139, MCC: 0.0546, F1: 0.6602

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47867 | val 1.17327
  Epoch 020 - train 0.05647 | val 3.41422
  Epoch 021 - train 0.06748 | val 3.13345
  Classification -> best τ=0.470 (val F1=0.1967)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.60615 | val 1.39477
  Epoch 020 - train 0.02144 | val 5.25894
  Epoch 022 - train 0.01739 | val 5.40394
  Classification -> best τ=0.420 (val F1=0.2774)
  Directional -> Accuracy: 0.5897, MCC: 0.0778, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.40919 | val 2.48183
  Epoch 020 - train 0.06709 | val 3.35848
  Epoch 022 - train 0.04297 | val 3.62205
  Classification -> best τ=0.465 (val F1=0.3162)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60893 | val 0.68185
  Epoch 020 - train 0.25892 | val 1.30688
  Epoch 025 - train 0.13893 | val 1.50040
  Classification -> best τ=0.355 (val F1=0.3024)
  Directional -> Accuracy: 0.5660, MCC: 0.1052, F1: 0.7089

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.58393 | val 1.38645
  Epoch 020 - train 0.13540 | val 5.88012
  Epoch 022 - train 0.11599 | val 4.63510
  Classification -> best τ=0.425 (val F1=0.2988)
  Directional -> Accuracy: 0.4630, MCC: -0.0786, F1: 0.3556

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68367 | val 0.89890
  Epoch 020 - train 0.19659 | val 1.40797
  Epoch 021 - train 0.18469 | val 1.68775
  Classification -> best τ=0.525 (val F1=0.2535)
  Directional -> Accuracy: 0.5098, MCC: 0.0255, F1: 0.5614

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.63871 | val 0.78093
  Epoch 020 - train 0.16431 | val 4.80099
  Epoch 021 - train 0.23636 | val 4.23212
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.60958 | val 0.72170

[I 2026-02-19 03:47:45,627] Trial 57 finished with value: 0.2469397181368797 and parameters: {'feature_set': 'emotion', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.009959185505682802, 'weight_decay': 1.6903640474405019e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.9542400587106212, 'early_stopping_min_delta': 0.0016235048067109134}. Best is trial 53 with value: 0.2732635960250114.

  Epoch 026 - train 0.35376 | val 1.60804
  Classification -> best τ=0.595 (val F1=0.3228)
  Directional -> Accuracy: 0.6207, MCC: 0.2539, F1: 0.4211

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2469397181368797
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69385 | val 0.81350
  Epoch 020 - train 0.68500 | val 1.43292
  Classification -> best τ=0.470 (val F1=0.2578)
  Directional -> Accuracy: 0.5200, MCC: -0.0321, F1: 0.2174

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.59070 | val 1.05749
  Epoch 020 - train 0.52931 | val 1.28752
  Classification -> best τ=0.630 (val F1=0.0300)
  Directional -> Accuracy: 0.5682, MCC: 0.1472, F1: 0.5957

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.65663 | val 1.37169
  Epoch 020 - train 0.64079 | val 1.10714
  Classification -> best τ=0.520 (val F1=0.3492)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71196 | val 0.68876
  Epoch 020 - train 0.67169 | val 0.71225
  Classification -> best τ=0.560 (val F1=0.2023)
  Directional -> Accuracy: 0.4658, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55903 | val 1.30572
  Epoch 020 - train 0.51251 | val 1.90041
  Classification -> best τ=0.520 (val F1=0.3748)
  Directional -> Accuracy: 0.6939, MCC: 0.4631, F1: 0.5946

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.61082 | val 0.76033
  Epoch 020 - train 0.45537 | val 0.71483
  Classification -> best τ=0.540 (val F1=0.2382)
  Directional -> Accuracy: 0.4889, MCC: -0.0048, F1: 0.6462

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65219 | val 0.92763
  Epoch 020 - train 0.56211 | val 0.95151
  Classification -> best τ=0.420 (val F1=0.1868)
  Directional -> Accuracy: 0.4030, MCC: 0.0000, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68840 | val 1.14287
  Epoch 020 - train 0.43640 | val 3.82100
  Classification -> best τ=0.490 (val F1=0.6547)
  Directional -> Accuracy: 0.6341, MCC: 0.2433, F1: 0.4444

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69033 | val 1.28889
  Epoch 020 - train 0.35424 | val 4.21735
  Classification -> best τ=0.485 (val F1=0.2333)
  Directional -> Accuracy: 0.3830, MCC: -0.2451, F1: 0.5397

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62060 | val 0.69773
  Epoch 020 - train 0.56313 | val 0.78225
  Classification -> best τ=0.445 (val F1=0.1179)
  Directional -> Accuracy: 0.4853, MCC: 0.0714, F1: 0.5783

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67969 | val 1.39688
  Epoch 020 - train 0.59204 | val 1.85107
  Classification -> best τ=0.555 (val F1=0.2692)
  Directional -> Accuracy: 0.5833, MCC: 0.1496, F1: 0.3333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69671 | val 0.95646
  Epoch 020 - train 0.58343 | val 3.57801
  Classification -> best τ=0.560 (val F1=0.2215)
  Directional -> Accuracy: 0.5000, MCC: 0.0121, F1: 0.4167

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.60731 | val 1.36041
  Epoch 020 - train 0.49743 | val 3.55403
  Classification -> best τ=0.575 (val F1=0.2094)
  Directional -> Accuracy: 0.4082, MCC: -0.2189, F1: 0.2162

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.73874 | val 0.66431
  Epoch 020 - train 0.61925 | val 0.73181
  Classification -> best τ=0.425 (val F1=0.2400)
  Directional -> Accuracy: 0.6441, MCC: 0.2942, F1: 0.6182

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70174 | val 1.24621
  Epoch 020 - train 0.62491 | val 2.33482
  Classification -> best τ=0.405 (val F1=0.4399)
  Directional -> Accuracy: 0.4200, MCC: -0.1714, F1: 0.3556

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68348 | val 1.06243
  Epoch 020 - train 0.65119 | val 1.70325
  Classification -> best τ=0.470 (val F1=0.2818)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67636 | val 1.51398
  Epoch 020 - train 0.59799 | val 1.39677
  Classification -> best τ=0.570 (val F1=0.1894)
  Directional -> Accuracy: 0.3509, MCC: -0.2869, F1: 0.3934

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67972 | val 0.73048
  Epoch 020 - train 0.62420 | val 0.70622
  Classification -> best τ=0.460 (val F1=0.2377)
  Directional -> Accuracy: 0.4595, MCC: 0.0191, F1: 0.3548

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.69164 | val 0.75917
  Epoch 020 - train 0.68136 | val 0.93597
  Classification -> best τ=0.835 (val F1=0.2288)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66877 | val 1.47194
  Epoch 020 - train 0.59373 | val 0.83997
  Classification -> best τ=0.495 (val F1=0.3060)
  Directional -> Accuracy: 0.3288, MCC: -0.3305, F1: 0.2462

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.60716 | val 2.05589
  Epoch 020 - train 0.51241 | val 3.22443
  Classification -> best τ=0.565 (val F1=0.1510)
  Directional -> Accuracy: 0.5000, MCC: -0.0393, F1: 0.5818

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69637 | val 0.98389
  Epoch 020 - train 0.58675 | val 1.70479
  Classification -> best τ=0.555 (val F1=0.1241)
  Directional -> Accuracy: 0.5312, MCC: 0.0801, F1: 0.6429

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71984 | val 0.92024
  Epoch 020 - train 0.61111 | val 1.55142
  Classification -> best τ=0.575 (val F1=0.3931)
  Directional -> Accuracy: 0.6250, MCC: 0.2476, F1: 0.6557

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63895 | val 0.92282
  Epoch 020 - train 0.67120 | val 1.96159
  Classification -> best τ=0.485 (val F1=0.2361)
  Directional -> Accuracy: 0.4844, MCC: -0.0416, F1: 0.4211

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70577 | val 0.81856
  Epoch 020 - train 0.57185 | val 2.84731
  Classification -> best τ=0.450 (val F1=0.3692)
  Directional -> Accuracy: 0.4815, MCC: 0.0166, F1: 0.2632

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62336 | val 2.29215
  Epoch 020 - train 0.63714 | val 7.70326
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68294 | val 1.02340
  Epoch 020 - train 0.49311 | val 3.40938
  Classification -> best τ=0.350 (val F1=0.1133)
  Directional -> Accuracy: 0.4898, MCC: 0.0867, F1: 0.3902

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66973 | val 0.91071
  Epoch 020 - train 0.60157 | val 2.03497
  Classification -> best τ=0.510 (val F1=0.2257)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.62434 | val 0.88922
  Epoch 020 - train 0.39080 | val 2.15513
  Classification -> best τ=0.240 (val F1=0.3708)
  Directional -> Accuracy: 0.5789, MCC: 0.1291, F1: 0.7143

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64183 | val 1.85554
  Epoch 020 - train 0.51184 | val 3.44615
  Classification -> best τ=0.390 (val F1=0.3156)
  Directional -> Accuracy: 0.5122, MCC: 0.0263, F1: 0.5238

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66088 | val 0.88984
  Epoch 020 - train 0.51859 | val 1.87619
  Classification -> best τ=0.630 (val F1=0.2390)
  Directional -> Accuracy: 0.5366, MCC: 0.1370, F1: 0.4571

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65245 | val 0.74442
  Epoch 020 - train 0.50876 | val 0.88456
  Classification -> best τ=0.500 (val F1=0.3790)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62535 | val 1.00897
  Epoch 020 - train 0.52173 | val 1.42851
  Classification -> best τ=0.525 (val F1=0.3199)
  Directional -> Accuracy: 0.5211, MCC: 0.0986, F1: 0.4516

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67671 | val 0.73537
  Epoch 020 - train 0.59285 | val 0.88024
  Classification -> best τ=0.335 (val F1=0.2765)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.72468 | val 0.89873
  Epoch 020 - train 0.59897 | val 1.21184
  Classification -> best τ=0.250 (val F1=0.3488)
  Directional -> Accuracy: 0.6154, MCC: 0.2445, F1: 0.6269

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54093 | val 3.84119
  Epoch 020 - train 0.44625 | val 6.93666
  Classification -> best τ=0.465 (val F1=0.3216)
  Directional -> Accuracy: 0.6000, MCC: 0.2727, F1: 0.4667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.64947 | val 0.99764
  Epoch 020 - train 0.61218 | val 3.84996
  Classification -> best τ=0.390 (val F1=0.1145)
  Directional -> Accuracy: 0.5818, MCC: 0.1449, F1: 0.4889

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58613 | val 1.12834
  Epoch 020 - train 0.39120 | val 2.78227
  Classification -> best τ=0.490 (val F1=0.2256)
  Directional -> Accuracy: 0.3556, MCC: -0.1935, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.63611 | val 2.83656
  Epoch 020 - train 0.60117 | val 3.54532
  Classification -> best τ=0.620 (val F1=0.4548)
  Directional -> Accuracy: 0.3043, MCC: -0.2143, F1: 0.4667

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69306 | val 1.03662
  Epoch 020 - train 0.54161 | val 1.84253
  Classification -> best τ=0.540 (val F1=0.2621)
  Directional -> Accuracy: 0.5068, MCC: 0.0505, F1: 0.6538

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.61850 | val 1.00029
  Epoch 020 - train 0.55721 | val 1.54744
  Classification -> best τ=0.410 (val F1=0.2902)
  Directional -> Accuracy: 0.6136, MCC: 0.2397, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62890 | val 0.68200
  Epoch 020 - train 0.51871 | val 1.39449
  Classification -> best τ=0.230 (val F1=0.4336)
  Directional -> Accuracy: 0.5610, MCC: -0.1331, F1: 0.7188

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.64272 | val 0.85893
  Epoch 020 - train 0.49327 | val 2.21945
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66774 | val 1.01099
  Epoch 020 - train 0.65222 | val 0.94250
  Classification -> best τ=0.460 (val F1=0.3265)
  Directional -> Accuracy: 0.4444, MCC: -0.1890, F1: 0.5714

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65803 | val 1.39674
  Epoch 020 - train 0.61250 | val 2.97588
  Classification -> best τ=0.470 (val F1=0.2782)
  Directional -> Accuracy: 0.5455, MCC: 0.2359, F1: 0.6835

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67581 | val 0.82915
  Epoch 020 - train 0.55052 | val 0.81965
  Classification -> best τ=0.580 (val F1=0.2645)
  Directional -> Accuracy: 0.6538, MCC: 0.3162, F1: 0.6897

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.64028 | val 1.22220
  Epoch 020 - train 0.61558 | val 0.67549
  Classification -> best τ=0.475 (val F1=0.3953)
  Directional -> Accuracy: 0.5370, MCC: 0.0899, F1: 0.6835

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.77243 | val 0.83746

[I 2026-02-19 03:57:12,349] Trial 58 finished with value: 0.262530078926316 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.007824535904025895, 'weight_decay': 8.765005492855665e-07, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.7957212392320536, 'early_stopping_min_delta': 0.007509507525966885}. Best is trial 53 with value: 0.2732635960250114.

  Epoch 020 - train 0.65844 | val 1.08176
  Classification -> best τ=0.425 (val F1=0.1036)
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.262530078926316
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60389 | val 1.00848
  Epoch 020 - train 0.46320 | val 2.37876
  Epoch 021 - train 0.46569 | val 2.79897
  Classification -> best τ=0.560 (val F1=0.2489)
  Directional -> Accuracy: 0.5405, MCC: -0.0113, F1: 0.1500

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.52216 | val 0.69717
  Epoch 020 - train 0.35133 | val 1.57325
  Epoch 023 - train 0.28133 | val 1.94222
  Classification -> best τ=0.490 (val F1=0.3599)
  Directional -> Accuracy: 0.4884, MCC: 0.0320, F1: 0.4762

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.59645 | val 1.06823
  Epoch 020 - train 0.44834 | val 1.66074
  Epoch 026 - train 0.38105 | val 2.15020
  Classification -> best τ=0.515 (val F1=0.4664)
  Directional -> Accuracy: 0.5682, MCC: 0.1548, F1: 0.5128

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63508 | val 2.83457
  Epoch 020 - train 0.54945 | val 3.68919
  Epoch 021 - train 0.48392 | val 2.91269
  Classification -> best τ=0.450 (val F1=0.1058)
  Directional -> Accuracy: 0.5694, MCC: 0.1239, F1: 0.6265

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.54979 | val 1.26388
  Epoch 020 - train 0.32941 | val 1.61023
  Epoch 023 - train 0.28920 | val 1.62458
  Classification -> best τ=0.400 (val F1=0.4638)
  Directional -> Accuracy: 0.7292, MCC: 0.4845, F1: 0.6977

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53555 | val 3.88047
  Epoch 020 - train 0.27215 | val 12.25358
  Epoch 021 - train 0.28404 | val 13.65295
  Classification -> best τ=0.480 (val F1=0.1667)
  Directional -> Accuracy: 0.4773, MCC: -0.0467, F1: 0.4103

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66490 | val 0.86046
  Epoch 020 - train 0.55446 | val 1.37271
  Epoch 021 - train 0.54886 | val 1.62473
  Classification -> best τ=0.455 (val F1=0.2204)
  Directional -> Accuracy: 0.5455, MCC: 0.0925, F1: 0.5000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.53443 | val 1.49337
  Epoch 020 - train 0.36768 | val 3.03654
  Epoch 024 - train 0.31966 | val 2.89591
  Classification -> best τ=0.470 (val F1=0.2582)
  Directional -> Accuracy: 0.6154, MCC: 0.1937, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51128 | val 1.10664
  Epoch 020 - train 0.27824 | val 1.80098
  Epoch 025 - train 0.21212 | val 1.97143
  Classification -> best τ=0.500 (val F1=0.3030)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61229 | val 1.21876
  Epoch 020 - train 0.44022 | val 2.51167
  Epoch 021 - train 0.44116 | val 1.72219
  Classification -> best τ=0.440 (val F1=0.2413)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.57204 | val 4.20790
  Epoch 020 - train 0.46585 | val 5.78855
  Epoch 021 - train 0.39858 | val 6.31112
  Classification -> best τ=0.520 (val F1=0.0999)
  Directional -> Accuracy: 0.6383, MCC: 0.2648, F1: 0.4516

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62510 | val 1.65940
  Epoch 020 - train 0.47657 | val 1.84086
  Epoch 023 - train 0.43255 | val 2.21467
  Classification -> best τ=0.495 (val F1=0.3095)
  Directional -> Accuracy: 0.6182, MCC: 0.2303, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.61321 | val 0.94697
  Epoch 020 - train 0.39717 | val 0.88043
  Epoch 021 - train 0.37027 | val 0.90521
  Classification -> best τ=0.540 (val F1=0.0746)
  Directional -> Accuracy: 0.3542, MCC: -0.2895, F1: 0.3673

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.61234 | val 1.25377
  Epoch 020 - train 0.44702 | val 1.93817
  Epoch 021 - train 0.43954 | val 2.21709
  Classification -> best τ=0.530 (val F1=0.2693)
  Directional -> Accuracy: 0.5517, MCC: 0.0990, F1: 0.5938

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56676 | val 1.37415
  Epoch 020 - train 0.38438 | val 1.45014
  Epoch 023 - train 0.35324 | val 1.95226
  Classification -> best τ=0.440 (val F1=0.1748)
  Directional -> Accuracy: 0.5102, MCC: 0.1340, F1: 0.6250

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.59289 | val 1.03857
  Epoch 020 - train 0.44549 | val 1.99396
  Epoch 024 - train 0.37290 | val 2.14615
  Classification -> best τ=0.680 (val F1=0.3182)
  Directional -> Accuracy: 0.5821, MCC: 0.1530, F1: 0.6316

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.59987 | val 1.02985
  Epoch 020 - train 0.48910 | val 2.89922
  Epoch 021 - train 0.48616 | val 3.27106
  Classification -> best τ=0.540 (val F1=0.1091)
  Directional -> Accuracy: 0.4107, MCC: 0.1085, F1: 0.0571

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60124 | val 0.76201
  Epoch 020 - train 0.51110 | val 1.83280
  Epoch 021 - train 0.49679 | val 1.88585
  Classification -> best τ=0.490 (val F1=0.1829)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.53695 | val 1.06992
  Epoch 020 - train 0.39974 | val 2.00479
  Epoch 021 - train 0.34788 | val 1.93021
  Classification -> best τ=0.500 (val F1=0.1738)
  Directional -> Accuracy: 0.4839, MCC: 0.1321, F1: 0.2727

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62245 | val 1.03874
  Epoch 020 - train 0.42919 | val 2.13374
  Epoch 023 - train 0.39319 | val 1.80192
  Classification -> best τ=0.275 (val F1=0.2273)
  Directional -> Accuracy: 0.5139, MCC: -0.0065, F1: 0.5977

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.40520 | val 2.29364
  Epoch 020 - train 0.24406 | val 4.17044
  Epoch 021 - train 0.21642 | val 4.39579
  Classification -> best τ=0.495 (val F1=0.2988)
  Directional -> Accuracy: 0.5333, MCC: -0.1443, F1: 0.6866

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.58571 | val 0.89805
  Epoch 020 - train 0.42618 | val 1.11936
  Epoch 021 - train 0.41175 | val 1.20705
  Classification -> best τ=0.485 (val F1=0.2345)
  Directional -> Accuracy: 0.5714, MCC: 0.1466, F1: 0.5970

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.57311 | val 0.84745
  Epoch 020 - train 0.32872 | val 1.19438
  Epoch 021 - train 0.35588 | val 1.19414
  Classification -> best τ=0.530 (val F1=0.1706)
  Directional -> Accuracy: 0.5818, MCC: 0.2480, F1: 0.5306

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62789 | val 0.96885
  Epoch 020 - train 0.45719 | val 1.18292
  Epoch 021 - train 0.42948 | val 1.33745
  Classification -> best τ=0.455 (val F1=0.2252)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61009 | val 1.02538
  Epoch 020 - train 0.32832 | val 1.73167
  Epoch 022 - train 0.33004 | val 1.94268
  Classification -> best τ=0.515 (val F1=0.4819)
  Directional -> Accuracy: 0.4906, MCC: 0.0858, F1: 0.2286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.50019 | val 1.80229
  Epoch 020 - train 0.24345 | val 3.91334
  Epoch 023 - train 0.22676 | val 4.80377
  Classification -> best τ=0.525 (val F1=0.0679)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57698 | val 0.72389
  Epoch 020 - train 0.46271 | val 0.98272
  Epoch 021 - train 0.42036 | val 1.27096
  Classification -> best τ=0.475 (val F1=0.0618)
  Directional -> Accuracy: 0.4167, MCC: -0.1085, F1: 0.3333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.57068 | val 1.12853
  Epoch 020 - train 0.38286 | val 1.80300
  Epoch 021 - train 0.34564 | val 2.02739
  Classification -> best τ=0.490 (val F1=0.1657)
  Directional -> Accuracy: 0.4444, MCC: -0.1479, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49266 | val 1.54918
  Epoch 020 - train 0.32275 | val 1.75669
  Epoch 021 - train 0.27553 | val 2.04321
  Classification -> best τ=0.520 (val F1=0.2000)
  Directional -> Accuracy: 0.5250, MCC: 0.0560, F1: 0.3871

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53974 | val 0.99816
  Epoch 020 - train 0.32530 | val 1.57097
  Epoch 025 - train 0.26708 | val 1.89826
  Classification -> best τ=0.740 (val F1=0.2328)
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55086 | val 0.77825
  Epoch 020 - train 0.26173 | val 1.25493
  Epoch 024 - train 0.19408 | val 1.52959
  Classification -> best τ=0.440 (val F1=0.4454)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.56289 | val 0.79517
  Epoch 020 - train 0.46386 | val 0.96305
  Epoch 022 - train 0.41787 | val 1.06092
  Classification -> best τ=0.330 (val F1=0.3102)
  Directional -> Accuracy: 0.5857, MCC: 0.1831, F1: 0.5915

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.51948 | val 1.42996
  Epoch 020 - train 0.23043 | val 2.46895
  Epoch 021 - train 0.24411 | val 2.49966
  Classification -> best τ=0.475 (val F1=0.2075)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.56425 | val 1.05380
  Epoch 020 - train 0.42812 | val 1.65936
  Epoch 021 - train 0.34974 | val 1.68503
  Classification -> best τ=0.410 (val F1=0.2449)
  Directional -> Accuracy: 0.4062, MCC: -0.1627, F1: 0.0500

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44061 | val 2.09581
  Epoch 020 - train 0.30486 | val 3.62561
  Epoch 021 - train 0.23469 | val 3.70491
  Classification -> best τ=0.490 (val F1=0.3837)
  Directional -> Accuracy: 0.6327, MCC: 0.2696, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.53238 | val 1.54735
  Epoch 020 - train 0.37569 | val 2.04002
  Epoch 021 - train 0.37998 | val 2.24009
  Classification -> best τ=0.465 (val F1=0.2193)
  Directional -> Accuracy: 0.5370, MCC: 0.1256, F1: 0.6154

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.47252 | val 4.36551
  Epoch 020 - train 0.24166 | val 2.87719
  Epoch 021 - train 0.20986 | val 3.18256
  Classification -> best τ=0.530 (val F1=0.2734)
  Directional -> Accuracy: 0.5227, MCC: -0.1320, F1: 0.6667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55045 | val 0.66720
  Epoch 020 - train 0.28056 | val 0.89549
  Epoch 026 - train 0.21344 | val 0.90780
  Classification -> best τ=0.325 (val F1=0.5380)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.57873 | val 2.20136
  Epoch 020 - train 0.41998 | val 2.72542
  Epoch 021 - train 0.44628 | val 2.65739
  Classification -> best τ=0.495 (val F1=0.1220)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54090 | val 0.77791
  Epoch 020 - train 0.41763 | val 0.95741
  Epoch 024 - train 0.34525 | val 0.99108
  Classification -> best τ=0.455 (val F1=0.1820)
  Directional -> Accuracy: 0.3953, MCC: -0.2331, F1: 0.1875

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43220 | val 0.75251
  Epoch 020 - train 0.26404 | val 1.47069
  Epoch 028 - train 0.14129 | val 1.35441
  Classification -> best τ=0.395 (val F1=0.4181)
  Directional -> Accuracy: 0.6154, MCC: 0.1479, F1: 0.7368

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49932 | val 0.89433
  Epoch 020 - train 0.35880 | val 1.78518
  Epoch 021 - train 0.33870 | val 1.79839
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60298 | val 1.32449
  Epoch 020 - train 0.48626 | val 2.14655
  Epoch 021 - train 0.41646 | val 1.63014
  Classification -> best τ=0.515 (val F1=0.0707)
  Directional -> Accuracy: 0.4151, MCC: -0.1688, F1: 0.4364

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.59393 | val 1.44421
  Epoch 020 - train 0.41087 | val 2.29029
  Epoch 021 - train 0.43538 | val 2.29257
  Classification -> best τ=0.640 (val F1=0.2325)
  Directional -> Accuracy: 0.5926, MCC: 0.2485, F1: 0.6944

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56868 | val 1.48472
  Epoch 020 - train 0.35637 | val 1.45274
  Epoch 021 - train 0.35782 | val 1.46460
  Classification -> best τ=0.510 (val F1=0.2513)
  Directional -> Accuracy: 0.5882, MCC: 0.1757, F1: 0.5714

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54349 | val 4.87351
  Epoch 020 - train 0.37233 | val 4.89194
  Epoch 021 - train 0.32111 | val 6.51984
  Classification -> best τ=0.540 (val F1=0.2728)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67465 | val 0.64692
  Epoch 020 - train 0.48630 | val 0.80353
  Epoch 030 - train 0.38801 | val 0.95518
  Classification -> best τ=0.690 (val F1=0.3407)

[I 2026-02-19 04:08:56,757] Trial 59 finished with value: 0.24310284539726063 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.0016773134970278483, 'weight_decay': 4.5914784389638277e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.614949431294748, 'early_stopping_min_delta': 0.0024105425525147734}. Best is trial 53 with value: 0.2732635960250114.

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24310284539726063
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70657 | val 0.71324
  Epoch 020 - train 0.70918 | val 0.71544
  Epoch 021 - train 0.70257 | val 0.71576
  Classification -> best τ=0.520 (val F1=0.1651)
  Directional -> Accuracy: 0.5676, MCC: 0.1064, F1: 0.4483

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.73589 | val 0.70057
  Epoch 020 - train 0.71645 | val 0.70075
  Epoch 021 - train 0.70591 | val 0.70078
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69421 | val 0.69644
  Epoch 020 - train 0.72397 | val 0.69381
  Epoch 024 - train 0.71243 | val 0.69279
  Classification -> best τ=0.515 (val F1=0.3494)
  Directional -> Accuracy: 0.5227, MCC: 0.0415, F1: 0.5532

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.72852 | val 0.70216
  Epoch 020 - train 0.72301 | val 0.70024
  Epoch 022 - train 0.72237 | val 0.70016
  Classification -> best τ=0.510 (val F1=0.0888)
  Directional -> Accuracy: 0.4861, MCC: 0.0000, F1: 0.4127

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.73662 | val 0.72972
  Epoch 020 - train 0.71536 | val 0.72598
  Epoch 021 - train 0.70598 | val 0.72559
  Classification -> best τ=0.495 (val F1=0.0384)
  Directional -> Accuracy: 0.4583, MCC: -0.1402, F1: 0.5938

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70005 | val 0.68613
  Epoch 020 - train 0.68585 | val 0.67737
  Epoch 030 - train 0.67221 | val 0.67681
  Epoch 040 - train 0.69408 | val 0.67731
  Epoch 050 - train 0.69007 | val 0.67746
  Classification -> best τ=0.485 (val F1=0.2878)
  Directional -> Accuracy: 0.4773, MCC: -0.1525, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71426 | val 0.69484
  Epoch 020 - train 0.70534 | val 0.69609
  Epoch 023 - train 0.68679 | val 0.69632
  Classification -> best τ=0.470 (val F1=0.2513)
  Directional -> Accuracy: 0.4697, MCC: 0.0938, F1: 0.5783

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.73506 | val 0.67720
  Epoch 020 - train 0.77536 | val 0.65356
  Epoch 030 - train 0.72020 | val 0.65979
  Epoch 037 - train 0.68951 | val 0.66137
  Classification -> best τ=0.570 (val F1=0.3612)
  Directional -> Accuracy: 0.5128, MCC: -0.1267, F1: 0.0952

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69183 | val 0.74155
  Epoch 020 - train 0.66777 | val 0.74235
  Epoch 021 - train 0.70470 | val 0.74247
  Classification -> best τ=0.530 (val F1=0.1195)
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.72882 | val 0.73046
  Epoch 020 - train 0.69560 | val 0.73395
  Epoch 021 - train 0.68451 | val 0.73428
  Classification -> best τ=0.490 (val F1=0.2269)
  Directional -> Accuracy: 0.5821, MCC: 0.0697, F1: 0.2632

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70049 | val 0.72566
  Epoch 020 - train 0.72515 | val 0.73358
  Epoch 021 - train 0.71868 | val 0.73399
  Classification -> best τ=0.470 (val F1=0.1540)
  Directional -> Accuracy: 0.5745, MCC: 0.1063, F1: 0.2308

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.72636 | val 0.69784
  Epoch 020 - train 0.69481 | val 0.70113
  Epoch 021 - train 0.70473 | val 0.70134
  Classification -> best τ=0.520 (val F1=0.1386)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.71109 | val 0.67951
  Epoch 020 - train 0.70937 | val 0.68139
  Epoch 026 - train 0.68536 | val 0.68142
  Classification -> best τ=0.480 (val F1=0.2036)
  Directional -> Accuracy: 0.4792, MCC: -0.0158, F1: 0.6154

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70342 | val 0.67507
  Epoch 020 - train 0.70308 | val 0.67653
  Epoch 026 - train 0.70145 | val 0.67686
  Classification -> best τ=0.490 (val F1=0.1771)
  Directional -> Accuracy: 0.6034, MCC: 0.2070, F1: 0.6102

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70908 | val 0.88210
  Epoch 020 - train 0.73232 | val 0.88927
  Epoch 021 - train 0.71528 | val 0.89003
  Classification -> best τ=0.540 (val F1=0.3816)
  Directional -> Accuracy: 0.5714, MCC: 0.1179, F1: 0.4615

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.73459 | val 0.74697
  Epoch 020 - train 0.72462 | val 0.74344
  Epoch 021 - train 0.73302 | val 0.74315
  Classification -> best τ=0.460 (val F1=0.0010)
  Directional -> Accuracy: 0.5224, MCC: -0.0357, F1: 0.6735

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.72974 | val 0.83736
  Epoch 020 - train 0.70539 | val 0.84644
  Epoch 021 - train 0.70303 | val 0.84707
  Classification -> best τ=0.490 (val F1=0.0150)
  Directional -> Accuracy: 0.6250, MCC: 0.2203, F1: 0.6866

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.72557 | val 0.83320
  Epoch 020 - train 0.72411 | val 0.83374
  Epoch 021 - train 0.69544 | val 0.83384
  Classification -> best τ=0.495 (val F1=0.1334)
  Directional -> Accuracy: 0.5890, MCC: 0.0000, F1: 0.7414

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.71970 | val 0.70100
  Epoch 020 - train 0.72128 | val 0.69931
  Epoch 021 - train 0.68206 | val 0.69921
  Classification -> best τ=0.490 (val F1=0.1211)
  Directional -> Accuracy: 0.5000, MCC: -0.0213, F1: 0.5634

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.73496 | val 0.71410
  Epoch 020 - train 0.71087 | val 0.71863
  Epoch 022 - train 0.70748 | val 0.71913
  Classification -> best τ=0.500 (val F1=0.1239)
  Directional -> Accuracy: 0.5556, MCC: 0.2500, F1: 0.3846

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.72859 | val 0.71916
  Epoch 020 - train 0.71450 | val 0.71886
  Epoch 021 - train 0.71487 | val 0.71877
  Classification -> best τ=0.465 (val F1=0.0116)
  Directional -> Accuracy: 0.4444, MCC: -0.2202, F1: 0.5763

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.73942 | val 0.72549
  Epoch 020 - train 0.71767 | val 0.72220
  Epoch 021 - train 0.72365 | val 0.72211
  Classification -> best τ=0.475 (val F1=0.0773)
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.75193 | val 0.71207
  Epoch 020 - train 0.72731 | val 0.70983
  Epoch 021 - train 0.71386 | val 0.70974
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5818, MCC: 0.0000, F1: 0.7356

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.70115 | val 0.86747
  Epoch 020 - train 0.72396 | val 0.84763
  Epoch 021 - train 0.72629 | val 0.84594
  Classification -> best τ=0.505 (val F1=0.1260)
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.72135 | val 0.72169
  Epoch 020 - train 0.72596 | val 0.71916
  Epoch 021 - train 0.75948 | val 0.71889
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5472, MCC: 0.0000, F1: 0.7073

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.75328 | val 0.73544
  Epoch 020 - train 0.73086 | val 0.75459
  Epoch 021 - train 0.75337 | val 0.75443
  Classification -> best τ=0.490 (val F1=0.2303)
  Directional -> Accuracy: 0.6190, MCC: 0.2582, F1: 0.2000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.70329 | val 1.02589
  Epoch 020 - train 0.71850 | val 1.03479
  Epoch 021 - train 0.75850 | val 1.03461
  Classification -> best τ=0.450 (val F1=0.1518)
  Directional -> Accuracy: 0.5000, MCC: 0.0436, F1: 0.4783

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70325 | val 0.69643
  Epoch 020 - train 0.71304 | val 0.69659
  Epoch 021 - train 0.69894 | val 0.69666
  Classification -> best τ=0.455 (val F1=0.3708)
  Directional -> Accuracy: 0.5370, MCC: 0.1256, F1: 0.4186

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.72759 | val 0.66846
  Epoch 020 - train 0.69139 | val 0.66711
  Epoch 030 - train 0.71087 | val 0.66579
  Epoch 040 - train 0.72741 | val 0.66441
  Epoch 050 - train 0.68654 | val 0.66370
  Classification -> best τ=0.355 (val F1=0.2000)
  Directional -> Accuracy: 0.4750, MCC: -0.0949, F1: 0.6316

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72666 | val 0.73460
  Epoch 020 - train 0.72811 | val 0.73834
  Epoch 021 - train 0.69535 | val 0.73849
  Classification -> best τ=0.490 (val F1=0.2328)
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.74085 | val 0.72189
  Epoch 020 - train 0.74794 | val 0.72106
  Epoch 021 - train 0.76668 | val 0.72098
  Classification -> best τ=0.545 (val F1=0.2928)
  Directional -> Accuracy: 0.4043, MCC: -0.2054, F1: 0.4815

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.73481 | val 0.68876
  Epoch 020 - train 0.72694 | val 0.68574
  Epoch 030 - train 0.72040 | val 0.68309
  Epoch 040 - train 0.69757 | val 0.68005
  Epoch 050 - train 0.70094 | val 0.67808
  Classification -> best τ=0.550 (val F1=0.2495)
  Directional -> Accuracy: 0.5286, MCC: 0.1582, F1: 0.3774

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.71627 | val 0.71205
  Epoch 020 - train 0.74626 | val 0.71715
  Epoch 024 - train 0.73667 | val 0.71809
  Classification -> best τ=0.495 (val F1=0.1448)
  Directional -> Accuracy: 0.4490, MCC: -0.0882, F1: 0.5970

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.71634 | val 0.72137
  Epoch 020 - train 0.71445 | val 0.71678
  Epoch 021 - train 0.73114 | val 0.71643
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.73360 | val 0.72932
  Epoch 020 - train 0.71654 | val 0.73867
  Epoch 024 - train 0.68449 | val 0.73744
  Classification -> best τ=0.435 (val F1=0.3498)
  Directional -> Accuracy: 0.3878, MCC: -0.2732, F1: 0.1667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70563 | val 0.70566
  Epoch 020 - train 0.70379 | val 0.70571
  Epoch 021 - train 0.69499 | val 0.70563
  Classification -> best τ=0.505 (val F1=0.1242)
  Directional -> Accuracy: 0.6111, MCC: 0.2101, F1: 0.5116

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.72432 | val 0.70528
  Epoch 020 - train 0.76142 | val 0.70562
  Epoch 021 - train 0.73259 | val 0.70570
  Classification -> best τ=0.500 (val F1=0.0201)
  Directional -> Accuracy: 0.5000, MCC: -0.2175, F1: 0.6562

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.74124 | val 0.72964
  Epoch 020 - train 0.77204 | val 0.74490
  Epoch 021 - train 0.73669 | val 0.74479
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.71765 | val 0.74912
  Epoch 020 - train 0.72168 | val 0.74944
  Epoch 021 - train 0.72376 | val 0.74935
  Classification -> best τ=0.500 (val F1=0.1316)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.76835 | val 0.66381
  Epoch 020 - train 0.78890 | val 0.66091
  Epoch 030 - train 0.78037 | val 0.65756
  Epoch 040 - train 0.74434 | val 0.65458
  Epoch 050 - train 0.74859 | val 0.65102
  Classification -> best τ=0.505 (val F1=0.3478)
  Directional -> Accuracy: 0.5349, MCC: 0.0783, F1: 0.4737

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.75875 | val 0.71105
  Epoch 020 - train 0.74431 | val 0.71848
  Epoch 021 - train 0.73993 | val 0.71846
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5897, MCC: 0.0000, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.71818 | val 0.71913
  Epoch 020 - train 0.71392 | val 0.72787
  Epoch 021 - train 0.74142 | val 0.72804
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.72225 | val 0.72611
  Epoch 020 - train 0.73041 | val 0.73118
  Epoch 021 - train 0.71883 | val 0.73152
  Classification -> best τ=0.485 (val F1=0.0479)
  Directional -> Accuracy: 0.6038, MCC: 0.3110, F1: 0.4878

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70640 | val 0.71899
  Epoch 020 - train 0.71303 | val 0.70500
  Epoch 023 - train 0.73086 | val 0.70277
  Classification -> best τ=0.425 (val F1=0.2981)
  Directional -> Accuracy: 0.5556, MCC: 0.2425, F1: 0.2000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.71746 | val 0.69620
  Epoch 020 - train 0.71448 | val 0.69640
  Epoch 021 - train 0.69445 | val 0.69641
  Classification -> best τ=0.525 (val F1=0.1029)
  Directional -> Accuracy: 0.5490, MCC: 0.1066, F1: 0.5965

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.73367 | val 0.80039
  Epoch 020 - train 0.72983 | val 0.81195
  Epoch 021 - train 0.72185 | val 0.81278
  Classification -> best τ=0.510 (val F1=0.1646)
  Directional -> Accuracy: 0.4340, MCC: -0.1998, F1: 0.0625

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-19 04:17:54,080] Trial 60 finished with value: 0.15232611884414335 and parameters: {'feature_set': 'finbert', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 2.779341435997256e-06, 'weight_decay': 3.8022948698445875e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.9008413354614535, 'early_stopping_min_delta': 0.001414625897059356}. Best is trial 53 with value: 0.2732635960250114.

Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.65339 | val 1.25289
  Epoch 020 - train 0.55465 | val 2.52833
  Epoch 021 - train 0.57889 | val 2.47976
  Classification -> best τ=0.555 (val F1=0.2489)
  Directional -> Accuracy: 0.5541, MCC: 0.0260, F1: 0.1081

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.62209 | val 0.77845
  Epoch 020 - train 0.49456 | val 2.14086
  Epoch 028 - train 0.21341 | val 2.86920
  Classification -> best τ=0.520 (val F1=0.4077)
  Directional -> Accuracy: 0.5814, MCC: 0.1819, F1: 0.6087

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62720 | val 0.77512
  Epoch 020 - train 0.52125 | val 1.00326
  Epoch 021 - train 0.47067 | val 1.23929
  Classification -> best τ=0.485 (val F1=0.3775)
  Directional -> Accuracy: 0.5455, MCC: 0.1201, F1: 0.4444

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65152 | val 1.00062
  Epoch 020 - train 0.57243 | val 1.15247
  Epoch 021 - train 0.54209 | val 1.19089
  Classification -> best τ=0.555 (val F1=0.0905)
  Directional -> Accuracy: 0.5417, MCC: 0.0791, F1: 0.5714

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57036 | val 1.89664
  Epoch 020 - train 0.43915 | val 2.32707
  Epoch 023 - train 0.41568 | val 2.86725
  Classification -> best τ=0.510 (val F1=0.4398)
  Directional -> Accuracy: 0.6042, MCC: 0.3171, F1: 0.4242

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54831 | val 2.57210
  Epoch 020 - train 0.31031 | val 7.70892
  Epoch 021 - train 0.29355 | val 8.64013
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67336 | val 0.73010
  Epoch 020 - train 0.56721 | val 1.08412
  Epoch 021 - train 0.53325 | val 1.13460
  Classification -> best τ=0.450 (val F1=0.1939)
  Directional -> Accuracy: 0.5152, MCC: 0.1053, F1: 0.5556

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.68413 | val 0.56239
  Epoch 020 - train 0.30183 | val 2.19941
  Epoch 025 - train 0.25794 | val 3.12349
  Classification -> best τ=0.350 (val F1=0.4345)
  Directional -> Accuracy: 0.4872, MCC: 0.0259, F1: 0.5455

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.57135 | val 1.54699
  Epoch 020 - train 0.30458 | val 4.54727
  Epoch 022 - train 0.30780 | val 4.93740
  Classification -> best τ=0.440 (val F1=0.1223)
  Directional -> Accuracy: 0.5217, MCC: -0.0793, F1: 0.1538

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63623 | val 1.73719
  Epoch 020 - train 0.49712 | val 1.14502
  Epoch 021 - train 0.45282 | val 1.26700
  Classification -> best τ=0.405 (val F1=0.1948)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60401 | val 4.10926
  Epoch 020 - train 0.37660 | val 7.82661
  Epoch 022 - train 0.37381 | val 6.87416
  Classification -> best τ=0.615 (val F1=0.2676)
  Directional -> Accuracy: 0.5957, MCC: 0.1860, F1: 0.2400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65759 | val 1.32716
  Epoch 020 - train 0.46230 | val 1.95333
  Epoch 021 - train 0.49254 | val 2.36818
  Classification -> best τ=0.485 (val F1=0.2359)
  Directional -> Accuracy: 0.4909, MCC: 0.0338, F1: 0.2222

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62927 | val 0.76169
  Epoch 020 - train 0.41219 | val 0.83941
  Epoch 022 - train 0.31182 | val 1.24754
  Classification -> best τ=0.480 (val F1=0.3616)
  Directional -> Accuracy: 0.5625, MCC: 0.1419, F1: 0.2759

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.64610 | val 0.87628
  Epoch 020 - train 0.43006 | val 2.10979
  Epoch 021 - train 0.43665 | val 2.84371
  Classification -> best τ=0.470 (val F1=0.1177)
  Directional -> Accuracy: 0.5345, MCC: 0.0598, F1: 0.6301

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.58098 | val 1.26964
  Epoch 020 - train 0.41306 | val 1.25921
  Epoch 021 - train 0.42486 | val 1.41704
  Classification -> best τ=0.550 (val F1=0.2849)
  Directional -> Accuracy: 0.4898, MCC: -0.0923, F1: 0.2424

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60771 | val 1.01730
  Epoch 020 - train 0.42123 | val 1.95380
  Epoch 022 - train 0.41277 | val 1.77631
  Classification -> best τ=0.545 (val F1=0.2199)
  Directional -> Accuracy: 0.5075, MCC: -0.0018, F1: 0.5714

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.63610 | val 1.35492
  Epoch 020 - train 0.51105 | val 2.47641
  Epoch 022 - train 0.47972 | val 2.93232
  Classification -> best τ=0.500 (val F1=0.0557)
  Directional -> Accuracy: 0.5536, MCC: -0.1236, F1: 0.7059

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63297 | val 0.75030
  Epoch 020 - train 0.55540 | val 1.69815
  Epoch 021 - train 0.54960 | val 1.92564
  Classification -> best τ=0.470 (val F1=0.1657)
  Directional -> Accuracy: 0.5205, MCC: 0.1385, F1: 0.4444

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65233 | val 0.70438
  Epoch 020 - train 0.42336 | val 1.16175
  Epoch 022 - train 0.35558 | val 1.32892
  Classification -> best τ=0.680 (val F1=0.2091)
  Directional -> Accuracy: 0.4839, MCC: 0.1321, F1: 0.2727

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60445 | val 0.88843
  Epoch 020 - train 0.52683 | val 3.19210
  Epoch 021 - train 0.56962 | val 2.40443
  Classification -> best τ=0.510 (val F1=0.2331)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62432 | val 1.67732
  Epoch 020 - train 0.41764 | val 1.88627
  Epoch 022 - train 0.38575 | val 1.93820
  Classification -> best τ=0.445 (val F1=0.0520)
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7164

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68944 | val 1.06571
  Epoch 020 - train 0.58450 | val 2.86483
  Epoch 021 - train 0.52136 | val 3.25686
  Classification -> best τ=0.450 (val F1=0.1274)
  Directional -> Accuracy: 0.4603, MCC: -0.0849, F1: 0.5750

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.60915 | val 0.84551
  Epoch 020 - train 0.39820 | val 2.14793
  Epoch 024 - train 0.39784 | val 2.57854
  Classification -> best τ=0.475 (val F1=0.2519)
  Directional -> Accuracy: 0.6182, MCC: 0.1874, F1: 0.7042

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68277 | val 0.77607
  Epoch 020 - train 0.51202 | val 0.88221
  Epoch 022 - train 0.52281 | val 1.00037
  Classification -> best τ=0.550 (val F1=0.1375)
  Directional -> Accuracy: 0.5714, MCC: 0.1557, F1: 0.3077

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.60865 | val 1.01943
  Epoch 020 - train 0.38063 | val 2.00214
  Epoch 023 - train 0.35810 | val 2.22965
  Classification -> best τ=0.440 (val F1=0.3289)
  Directional -> Accuracy: 0.5472, MCC: 0.1268, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54472 | val 1.72599
  Epoch 020 - train 0.24528 | val 2.25664
  Epoch 022 - train 0.17135 | val 2.93608
  Classification -> best τ=0.525 (val F1=0.2303)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55147 | val 1.44207
  Epoch 020 - train 0.48621 | val 0.78273
  Epoch 030 - train 0.42779 | val 1.28263
  Epoch 036 - train 0.35414 | val 1.25385
  Classification -> best τ=0.815 (val F1=0.3693)
  Directional -> Accuracy: 0.4583, MCC: -0.0571, F1: 0.4583

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60323 | val 1.13859
  Epoch 020 - train 0.43595 | val 2.29618
  Epoch 021 - train 0.41771 | val 2.34581
  Classification -> best τ=0.460 (val F1=0.2952)
  Directional -> Accuracy: 0.4630, MCC: -0.0146, F1: 0.0645

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.55492 | val 2.22200
  Epoch 020 - train 0.27213 | val 3.35709
  Epoch 021 - train 0.28539 | val 2.64881
  Classification -> best τ=0.555 (val F1=0.3333)
  Directional -> Accuracy: 0.5750, MCC: 0.1517, F1: 0.5405

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58300 | val 0.75941
  Epoch 020 - train 0.38016 | val 1.01159
  Epoch 028 - train 0.23959 | val 1.59727
  Classification -> best τ=0.725 (val F1=0.3477)
  Directional -> Accuracy: 0.5500, MCC: 0.1741, F1: 0.4375

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55463 | val 1.05494
  Epoch 020 - train 0.30278 | val 1.16264
  Epoch 024 - train 0.24129 | val 1.83251
  Classification -> best τ=0.365 (val F1=0.4524)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61680 | val 0.75019
  Epoch 020 - train 0.47435 | val 0.99490
  Epoch 023 - train 0.45083 | val 1.16281
  Classification -> best τ=0.540 (val F1=0.2712)
  Directional -> Accuracy: 0.5143, MCC: 0.1300, F1: 0.3462

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60351 | val 0.90732
  Epoch 020 - train 0.47562 | val 1.94353
  Epoch 021 - train 0.43854 | val 1.74735
  Classification -> best τ=0.500 (val F1=0.4271)
  Directional -> Accuracy: 0.5102, MCC: 0.1018, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66345 | val 0.76586
  Epoch 020 - train 0.54993 | val 1.08625
  Epoch 021 - train 0.48740 | val 1.06781
  Classification -> best τ=0.430 (val F1=0.3021)
  Directional -> Accuracy: 0.5781, MCC: 0.1216, F1: 0.6582

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62843 | val 2.16241
  Epoch 020 - train 0.33297 | val 2.89894
  Epoch 021 - train 0.34213 | val 3.00674
  Classification -> best τ=0.550 (val F1=0.3498)
  Directional -> Accuracy: 0.6122, MCC: 0.2434, F1: 0.4865

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60872 | val 2.42856
  Epoch 020 - train 0.40400 | val 4.68658
  Epoch 022 - train 0.36949 | val 3.03793
  Classification -> best τ=0.470 (val F1=0.3529)
  Directional -> Accuracy: 0.5000, MCC: 0.0028, F1: 0.4906

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.57126 | val 2.67263
  Epoch 020 - train 0.26234 | val 2.23060
  Epoch 021 - train 0.20833 | val 2.36028
  Classification -> best τ=0.515 (val F1=0.4418)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.60714 | val 0.74345
  Epoch 020 - train 0.34414 | val 1.07507
  Epoch 023 - train 0.38444 | val 1.68220
  Classification -> best τ=0.435 (val F1=0.4567)
  Directional -> Accuracy: 0.4222, MCC: 0.2209, F1: 0.5357

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63014 | val 1.41261
  Epoch 020 - train 0.49004 | val 2.95853
  Epoch 021 - train 0.48940 | val 2.98679
  Classification -> best τ=0.465 (val F1=0.1660)
  Directional -> Accuracy: 0.5417, MCC: 0.2085, F1: 0.6857

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.60252 | val 0.91818
  Epoch 020 - train 0.46885 | val 1.17486
  Epoch 022 - train 0.41320 | val 1.29569
  Classification -> best τ=0.435 (val F1=0.0605)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40343 | val 0.80006
  Epoch 020 - train 0.28944 | val 1.60699
  Epoch 028 - train 0.12749 | val 2.05556
  Classification -> best τ=0.480 (val F1=0.4345)
  Directional -> Accuracy: 0.6154, MCC: 0.1723, F1: 0.7059

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56962 | val 0.94921
  Epoch 020 - train 0.37485 | val 1.32076
  Epoch 021 - train 0.34496 | val 1.50423
  Classification -> best τ=0.490 (val F1=0.0316)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64480 | val 0.80381
  Epoch 020 - train 0.55666 | val 0.84846
  Epoch 030 - train 0.31736 | val 1.99000
  Epoch 032 - train 0.33779 | val 1.85981
  Classification -> best τ=0.860 (val F1=0.1984)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64029 | val 0.89235
  Epoch 020 - train 0.44235 | val 1.46817
  Epoch 021 - train 0.42521 | val 1.92158
  Classification -> best τ=0.630 (val F1=0.2673)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.55842 | val 1.61395
  Epoch 020 - train 0.42843 | val 3.69788
  Epoch 021 - train 0.45857 | val 4.68366
  Classification -> best τ=0.495 (val F1=0.2758)
  Directional -> Accuracy: 0.5686, MCC: 0.1497, F1: 0.6207

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.59897 | val 2.97866
  Epoch 020 - train 0.38432 | val 5.45163
  Epoch 021 - train 0.39009 | val 7.51878
  Classification -> best τ=0.535 (val F1=0.1168)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.66887 | val 0.87301
  Epoch 020 - train 0.57296 | val 0.63984
  Epoch 030 - train 0.41528 | val 0.80998
  Epoch 040 - train 0.11308 | val 6.04749

[I 2026-02-19 04:29:48,389] Trial 61 finished with value: 0.25688537006767853 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.0032947047660104273, 'weight_decay': 1.2817724959902626e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.8195259654232045, 'early_stopping_min_delta': 0.0012901684909212817}. Best is trial 53 with value: 0.2732635960250114.

  Classification -> best τ=0.270 (val F1=0.3339)
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25688537006767853
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60998 | val 3.47058
  Epoch 020 - train 0.51790 | val 3.39088
  Epoch 021 - train 0.48596 | val 5.26922
  Classification -> best τ=0.660 (val F1=0.2489)
  Directional -> Accuracy: 0.5676, MCC: 0.0816, F1: 0.2000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.54991 | val 1.24578
  Epoch 020 - train 0.37435 | val 1.15540
  Epoch 021 - train 0.34935 | val 1.22858
  Classification -> best τ=0.535 (val F1=0.2850)
  Directional -> Accuracy: 0.3721, MCC: -0.2567, F1: 0.4255

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.64888 | val 1.02130
  Epoch 020 - train 0.44295 | val 0.99495
  Epoch 023 - train 0.42444 | val 0.92908
  Classification -> best τ=0.620 (val F1=0.2200)
  Directional -> Accuracy: 0.4318, MCC: -0.1507, F1: 0.1379

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.66218 | val 0.98455
  Epoch 020 - train 0.54848 | val 17.78531
  Epoch 024 - train 0.47909 | val 2.70931
  Classification -> best τ=0.565 (val F1=0.2383)
  Directional -> Accuracy: 0.5139, MCC: 0.2231, F1: 0.1860

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.57682 | val 3.75923
  Epoch 020 - train 0.34017 | val 4.57657
  Epoch 021 - train 0.27641 | val 7.07376
  Classification -> best τ=0.430 (val F1=0.3171)
  Directional -> Accuracy: 0.5208, MCC: 0.0087, F1: 0.6761

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.51112 | val 1.63870
  Epoch 020 - train 0.25471 | val 2.60974
  Epoch 021 - train 0.28938 | val 3.12891
  Classification -> best τ=0.425 (val F1=0.1765)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.62940 | val 1.30495
  Epoch 020 - train 0.36947 | val 2.07462
  Epoch 022 - train 0.30530 | val 3.09469
  Classification -> best τ=0.525 (val F1=0.2197)
  Directional -> Accuracy: 0.5152, MCC: 0.0911, F1: 0.5429

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52355 | val 0.73734
  Epoch 020 - train 0.34346 | val 1.38424
  Epoch 030 - train 0.21096 | val 2.30670
  Epoch 036 - train 0.13644 | val 2.68309
  Classification -> best τ=0.505 (val F1=0.3612)
  Directional -> Accuracy: 0.6410, MCC: 0.2816, F1: 0.3636

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.58066 | val 1.35042
  Epoch 020 - train 0.21422 | val 3.95014
  Epoch 021 - train 0.12822 | val 4.16058
  Classification -> best τ=0.465 (val F1=0.3275)
  Directional -> Accuracy: 0.3913, MCC: -0.1823, F1: 0.4615

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61608 | val 1.24172
  Epoch 020 - train 0.71576 | val 1.06007
  Epoch 030 - train 0.31236 | val 1.41974
  Epoch 037 - train 0.15060 | val 2.24639
  Classification -> best τ=0.480 (val F1=0.1464)
  Directional -> Accuracy: 0.4627, MCC: -0.0442, F1: 0.4706

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.58326 | val 1.30891
  Epoch 020 - train 0.31615 | val 3.00663
  Epoch 021 - train 0.38021 | val 3.52029
  Classification -> best τ=0.370 (val F1=0.0391)
  Directional -> Accuracy: 0.4681, MCC: 0.1325, F1: 0.6269

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.62240 | val 0.80120
  Epoch 020 - train 0.46660 | val 1.77569
  Epoch 022 - train 0.47358 | val 2.48826
  Classification -> best τ=0.435 (val F1=0.1955)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.57817 | val 0.81713
  Epoch 020 - train 0.41736 | val 1.96558
  Epoch 021 - train 0.42557 | val 1.64466
  Classification -> best τ=0.435 (val F1=0.2820)
  Directional -> Accuracy: 0.5625, MCC: 0.1204, F1: 0.4000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.59163 | val 1.18808
  Epoch 020 - train 0.43096 | val 3.92715
  Epoch 022 - train 0.36711 | val 2.27085
  Classification -> best τ=0.290 (val F1=0.2559)
  Directional -> Accuracy: 0.5345, MCC: 0.0608, F1: 0.6087

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69084 | val 1.05564
  Epoch 020 - train 0.37865 | val 1.23528
  Epoch 022 - train 0.28079 | val 1.28117
  Classification -> best τ=0.425 (val F1=0.1687)
  Directional -> Accuracy: 0.6531, MCC: 0.3350, F1: 0.4138

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66301 | val 0.81951
  Epoch 020 - train 0.53627 | val 1.66187
  Epoch 021 - train 0.49701 | val 1.95800
  Classification -> best τ=0.570 (val F1=0.3099)
  Directional -> Accuracy: 0.6119, MCC: 0.2131, F1: 0.6905

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.55475 | val 2.40944
  Epoch 020 - train 0.41816 | val 3.42079
  Epoch 021 - train 0.37933 | val 3.98461
  Classification -> best τ=0.545 (val F1=0.2699)
  Directional -> Accuracy: 0.5179, MCC: 0.1563, F1: 0.4490

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69231 | val 0.90259
  Epoch 020 - train 0.50678 | val 2.06809
  Epoch 026 - train 0.41597 | val 1.97365
  Classification -> best τ=0.685 (val F1=0.2127)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64367 | val 0.80624
  Epoch 020 - train 0.40213 | val 1.71070
  Epoch 022 - train 0.32696 | val 2.03102
  Classification -> best τ=0.615 (val F1=0.2697)
  Directional -> Accuracy: 0.4355, MCC: 0.0393, F1: 0.1026

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60437 | val 1.25863
  Epoch 020 - train 0.38801 | val 1.87267
  Epoch 021 - train 0.45104 | val 1.92773
  Classification -> best τ=0.445 (val F1=0.1750)
  Directional -> Accuracy: 0.5139, MCC: -0.0845, F1: 0.6602

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.61821 | val 1.25801
  Epoch 020 - train 0.41873 | val 2.42302
  Epoch 022 - train 0.47268 | val 2.01406
  Classification -> best τ=0.495 (val F1=0.1754)
  Directional -> Accuracy: 0.4889, MCC: -0.0364, F1: 0.5490

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65127 | val 1.23751
  Epoch 020 - train 0.47907 | val 1.87954
  Epoch 021 - train 0.45880 | val 1.48634
  Classification -> best τ=0.430 (val F1=0.1211)
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61642 | val 0.84207
  Epoch 020 - train 0.43834 | val 2.07870
  Epoch 024 - train 0.32804 | val 2.79433
  Classification -> best τ=0.525 (val F1=0.2887)
  Directional -> Accuracy: 0.4364, MCC: 0.1154, F1: 0.0606

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63172 | val 0.71742
  Epoch 020 - train 0.55489 | val 0.71276
  Epoch 029 - train 0.33953 | val 0.92585
  Classification -> best τ=0.435 (val F1=0.2635)
  Directional -> Accuracy: 0.5238, MCC: 0.1037, F1: 0.6341

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.57387 | val 1.69286
  Epoch 020 - train 0.35303 | val 4.65521
  Epoch 021 - train 0.33102 | val 3.98810
  Classification -> best τ=0.420 (val F1=0.4297)
  Directional -> Accuracy: 0.3774, MCC: -0.3424, F1: 0.5217

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65248 | val 1.70390
  Epoch 020 - train 0.12905 | val 7.52472
  Epoch 021 - train 0.16150 | val 7.44700
  Classification -> best τ=0.625 (val F1=0.1809)
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.64181 | val 0.74839
  Epoch 020 - train 0.36254 | val 1.58566
  Epoch 023 - train 0.30134 | val 3.03065
  Classification -> best τ=0.510 (val F1=0.2925)
  Directional -> Accuracy: 0.3750, MCC: -0.1908, F1: 0.2105

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.60847 | val 0.85148
  Epoch 020 - train 0.40725 | val 1.65207
  Epoch 021 - train 0.37616 | val 1.59305
  Classification -> best τ=0.465 (val F1=0.1712)
  Directional -> Accuracy: 0.5556, MCC: 0.0830, F1: 0.6757

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.52528 | val 1.90277
  Epoch 020 - train 0.28110 | val 0.96134
  Epoch 021 - train 0.24126 | val 1.16653
  Classification -> best τ=0.655 (val F1=0.2928)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0909

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63633 | val 0.98588
  Epoch 020 - train 0.30311 | val 1.41773
  Epoch 022 - train 0.29569 | val 2.54836
  Classification -> best τ=0.570 (val F1=0.2537)
  Directional -> Accuracy: 0.5250, MCC: 0.0161, F1: 0.6122

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.64443 | val 0.81001
  Epoch 020 - train 0.42861 | val 1.25704
  Epoch 030 - train 0.11095 | val 2.40105
  Epoch 031 - train 0.07579 | val 2.85093
  Classification -> best τ=0.315 (val F1=0.3687)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62552 | val 0.84000
  Epoch 020 - train 0.50229 | val 1.08706
  Epoch 026 - train 0.32641 | val 1.46756
  Classification -> best τ=0.750 (val F1=0.2854)
  Directional -> Accuracy: 0.4857, MCC: 0.1055, F1: 0.2174

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58053 | val 1.47676
  Epoch 020 - train 0.30096 | val 2.96979
  Epoch 021 - train 0.27985 | val 3.03129
  Classification -> best τ=0.595 (val F1=0.4558)
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60496 | val 1.27577
  Epoch 020 - train 0.41430 | val 2.57632
  Epoch 021 - train 0.45540 | val 2.23726
  Classification -> best τ=0.330 (val F1=0.3921)
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64978 | val 2.04865
  Epoch 020 - train 0.24211 | val 4.87663
  Epoch 021 - train 0.23249 | val 5.54075
  Classification -> best τ=0.485 (val F1=0.3282)
  Directional -> Accuracy: 0.5510, MCC: 0.1035, F1: 0.5600

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60367 | val 2.13649
  Epoch 020 - train 0.48217 | val 3.59107
  Epoch 021 - train 0.41197 | val 3.72710
  Classification -> best τ=0.630 (val F1=0.1595)
  Directional -> Accuracy: 0.5741, MCC: 0.2112, F1: 0.1481

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51108 | val 4.09028
  Epoch 020 - train 0.20509 | val 9.06263
  Epoch 021 - train 0.17338 | val 9.06847
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56664 | val 2.22503
  Epoch 020 - train 0.30007 | val 3.98510
  Epoch 022 - train 0.22687 | val 6.12823
  Classification -> best τ=0.370 (val F1=0.4567)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63952 | val 1.18017
  Epoch 020 - train 0.41023 | val 3.36314
  Epoch 025 - train 0.33989 | val 3.01367
  Classification -> best τ=0.430 (val F1=0.3613)
  Directional -> Accuracy: 0.5278, MCC: 0.1690, F1: 0.6792

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.58263 | val 1.30647
  Epoch 020 - train 0.41073 | val 2.70591
  Epoch 021 - train 0.39003 | val 3.11814
  Classification -> best τ=0.495 (val F1=0.2212)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.59485 | val 0.83640
  Epoch 020 - train 0.26048 | val 1.85402
  Epoch 024 - train 0.31549 | val 2.76500
  Classification -> best τ=0.430 (val F1=0.0483)
  Directional -> Accuracy: 0.5641, MCC: -0.0080, F1: 0.7018

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54692 | val 1.87793
  Epoch 020 - train 0.17290 | val 7.17842
  Epoch 021 - train 0.14768 | val 8.08704
  Classification -> best τ=0.425 (val F1=0.2193)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.61258 | val 0.85826
  Epoch 020 - train 0.49410 | val 0.75305
  Epoch 027 - train 0.32593 | val 1.50721
  Classification -> best τ=0.625 (val F1=0.2615)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61958 | val 1.85825
  Epoch 020 - train 0.39935 | val 3.31449
  Epoch 021 - train 0.38881 | val 4.73359
  Classification -> best τ=0.650 (val F1=0.3073)
  Directional -> Accuracy: 0.5185, MCC: 0.0380, F1: 0.4583

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.57005 | val 0.91790
  Epoch 020 - train 0.47284 | val 2.39821
  Epoch 025 - train 0.46282 | val 2.09139
  Classification -> best τ=0.690 (val F1=0.2179)
  Directional -> Accuracy: 0.5294, MCC: 0.0585, F1: 0.5200

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60340 | val 2.10739
  Epoch 020 - train 0.30520 | val 6.69319
  Epoch 022 - train 0.28760 | val 6.92697
  Classification -> best τ=0.325 (val F1=0.4311)
  Directional -> Accuracy: 0.4906, MCC: -0.1361, F1: 0.6582

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.65094 | val 0.73296
  Epoch 020 - train 0.57022 | val 0.73727

[I 2026-02-19 04:41:58,326] Trial 62 finished with value: 0.2572115360216253 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.007634905350652626, 'weight_decay': 1.618330743941035e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.6015629548131205, 'early_stopping_min_delta': 0.0009333523466975523}. Best is trial 53 with value: 0.2732635960250114.

Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70084 | val 0.74953
  Epoch 020 - train 0.62980 | val 0.67818
  Epoch 030 - train 0.51524 | val 0.68541
  Epoch 040 - train 0.42594 | val 0.70493
  Epoch 047 - train 0.32856 | val 0.77980
  Classification -> best τ=0.655 (val F1=0.3100)
  Directional -> Accuracy: 0.5067, MCC: -0.0890, F1: 0.1395

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66629 | val 0.86154
  Epoch 020 - train 0.50154 | val 1.16164
  Epoch 021 - train 0.53882 | val 1.34096
  Classification -> best τ=0.430 (val F1=0.1329)
  Directional -> Accuracy: 0.5909, MCC: 0.0735, F1: 0.7188

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71512 | val 0.79777
  Epoch 020 - train 0.54529 | val 0.74312
  Epoch 023 - train 0.50269 | val 0.80350
  Classification -> best τ=0.500 (val F1=0.2970)
  Directional -> Accuracy: 0.5111, MCC: 0.1048, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68677 | val 0.95323
  Epoch 020 - train 0.60453 | val 1.09930
  Epoch 030 - train 0.49666 | val 1.29923
  Epoch 038 - train 0.35239 | val 1.10681
  Classification -> best τ=0.505 (val F1=0.2732)
  Directional -> Accuracy: 0.5342, MCC: 0.0451, F1: 0.6222

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.60207 | val 1.75109
  Epoch 020 - train 0.40864 | val 1.80815
  Epoch 024 - train 0.35101 | val 2.58395
  Classification -> best τ=0.510 (val F1=0.4726)
  Directional -> Accuracy: 0.5510, MCC: 0.1005, F1: 0.5769

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67324 | val 0.79479
  Epoch 020 - train 0.46727 | val 0.85858
  Epoch 021 - train 0.52889 | val 0.95585
  Classification -> best τ=0.555 (val F1=0.2190)
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66782 | val 2.46003
  Epoch 020 - train 0.60435 | val 1.39192
  Epoch 022 - train 0.60091 | val 1.38264
  Classification -> best τ=0.465 (val F1=0.3570)
  Directional -> Accuracy: 0.3582, MCC: -0.2168, F1: 0.5057

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66607 | val 0.68451
  Epoch 020 - train 0.46562 | val 2.20904
  Epoch 028 - train 0.34822 | val 1.74343
  Classification -> best τ=0.445 (val F1=0.4880)
  Directional -> Accuracy: 0.5122, MCC: 0.0920, F1: 0.5833

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65890 | val 0.82089
  Epoch 020 - train 0.57064 | val 1.00334
  Epoch 024 - train 0.44293 | val 1.36869
  Classification -> best τ=0.430 (val F1=0.2962)
  Directional -> Accuracy: 0.4894, MCC: 0.1207, F1: 0.6250

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66888 | val 0.69607
  Epoch 020 - train 0.43528 | val 0.87241
  Epoch 025 - train 0.41034 | val 0.96214
  Classification -> best τ=0.385 (val F1=0.3300)
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64968 | val 0.88518
  Epoch 020 - train 0.56063 | val 1.85852
  Epoch 021 - train 0.54801 | val 2.12094
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65491 | val 0.76497
  Epoch 020 - train 0.60867 | val 1.21071
  Epoch 022 - train 0.56875 | val 1.51023
  Classification -> best τ=0.565 (val F1=0.1294)
  Directional -> Accuracy: 0.5179, MCC: 0.0479, F1: 0.4490

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.59542 | val 2.05753
  Epoch 020 - train 0.46115 | val 3.15416
  Epoch 021 - train 0.47068 | val 3.57899
  Classification -> best τ=0.450 (val F1=0.0279)
  Directional -> Accuracy: 0.4490, MCC: -0.1017, F1: 0.4490

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.73034 | val 0.68386
  Epoch 020 - train 0.56542 | val 0.69034
  Epoch 028 - train 0.50484 | val 1.26101
  Classification -> best τ=0.210 (val F1=0.3527)
  Directional -> Accuracy: 0.5254, MCC: 0.1336, F1: 0.6818

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67341 | val 0.80514
  Epoch 020 - train 0.59588 | val 1.34863
  Epoch 028 - train 0.51267 | val 1.31076
  Classification -> best τ=0.495 (val F1=0.1453)
  Directional -> Accuracy: 0.5800, MCC: 0.1829, F1: 0.5882

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.71506 | val 0.80888
  Epoch 020 - train 0.63623 | val 0.96234
  Epoch 021 - train 0.61673 | val 0.89780
  Classification -> best τ=0.375 (val F1=0.3279)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65942 | val 0.82253
  Epoch 020 - train 0.56407 | val 1.36825
  Epoch 021 - train 0.54412 | val 1.51608
  Classification -> best τ=0.460 (val F1=0.2739)
  Directional -> Accuracy: 0.4737, MCC: -0.1298, F1: 0.5833

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60733 | val 0.71084
  Epoch 020 - train 0.54779 | val 1.00486
  Epoch 021 - train 0.53655 | val 0.90726
  Classification -> best τ=0.545 (val F1=0.1895)
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66211 | val 0.82813
  Epoch 020 - train 0.43092 | val 1.98424
  Epoch 021 - train 0.44745 | val 2.09809
  Classification -> best τ=0.645 (val F1=0.1300)
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.64646 | val 0.98452
  Epoch 020 - train 0.55898 | val 0.96063
  Epoch 022 - train 0.56841 | val 1.02262
  Classification -> best τ=0.525 (val F1=0.3060)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.69402 | val 1.12447
  Epoch 020 - train 0.53706 | val 2.18873
  Epoch 021 - train 0.52401 | val 2.12256
  Classification -> best τ=0.540 (val F1=0.1557)
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68089 | val 1.09660
  Epoch 020 - train 0.59960 | val 1.16360
  Epoch 021 - train 0.56291 | val 1.12447
  Classification -> best τ=0.640 (val F1=0.1300)
  Directional -> Accuracy: 0.5312, MCC: 0.1072, F1: 0.2105

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65628 | val 0.78210
  Epoch 020 - train 0.57771 | val 1.16568
  Epoch 027 - train 0.49689 | val 1.69341
  Classification -> best τ=0.390 (val F1=0.3131)
  Directional -> Accuracy: 0.5179, MCC: -0.2060, F1: 0.6824

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67105 | val 1.69577
  Epoch 020 - train 0.53806 | val 2.29457
  Epoch 021 - train 0.56210 | val 2.45168
  Classification -> best τ=0.395 (val F1=0.0237)
  Directional -> Accuracy: 0.5781, MCC: 0.1438, F1: 0.4706

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.62000 | val 0.63804
  Epoch 020 - train 0.58596 | val 1.11286
  Epoch 030 - train 0.31467 | val 2.02053
  Classification -> best τ=0.455 (val F1=0.3717)
  Directional -> Accuracy: 0.4815, MCC: 0.0266, F1: 0.2222

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.59238 | val 2.77635
  Epoch 020 - train 0.28335 | val 4.10248
  Epoch 021 - train 0.35200 | val 4.15995
  Classification -> best τ=0.565 (val F1=0.1355)
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.63255 | val 0.68924
  Epoch 020 - train 0.52405 | val 0.79521
  Epoch 027 - train 0.43900 | val 1.22621
  Classification -> best τ=0.575 (val F1=0.2764)
  Directional -> Accuracy: 0.3878, MCC: -0.1356, F1: 0.1667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.61045 | val 1.04202
  Epoch 020 - train 0.51033 | val 2.15737
  Epoch 022 - train 0.46331 | val 2.23648
  Classification -> best τ=0.465 (val F1=0.1757)
  Directional -> Accuracy: 0.5455, MCC: 0.1257, F1: 0.4898

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.63412 | val 0.92156
  Epoch 020 - train 0.48445 | val 0.65565
  Epoch 030 - train 0.38554 | val 0.60658
  Epoch 040 - train 0.14328 | val 1.58095
  Epoch 049 - train 0.06947 | val 1.40217
  Classification -> best τ=0.275 (val F1=0.5046)
  Directional -> Accuracy: 0.5526, MCC: 0.0808, F1: 0.6222

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.74142 | val 2.33424
  Epoch 020 - train 0.57577 | val 3.63105
  Epoch 021 - train 0.46397 | val 3.82558
  Classification -> best τ=0.580 (val F1=0.3922)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.74475 | val 0.66534
  Epoch 020 - train 0.62713 | val 1.15494
  Epoch 030 - train 0.33662 | val 1.36870
  Classification -> best τ=0.530 (val F1=0.1992)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59649 | val 1.00951
  Epoch 020 - train 0.46033 | val 0.99649
  Epoch 021 - train 0.50161 | val 1.08514
  Classification -> best τ=0.605 (val F1=0.2382)
  Directional -> Accuracy: 0.4583, MCC: -0.0969, F1: 0.0714

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62443 | val 0.85549
  Epoch 020 - train 0.53854 | val 1.32571
  Epoch 025 - train 0.45474 | val 1.50534
  Classification -> best τ=0.765 (val F1=0.2622)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.67372 | val 1.38513
  Epoch 020 - train 0.54104 | val 1.85015
  Epoch 021 - train 0.49440 | val 2.07224
  Classification -> best τ=0.485 (val F1=0.2386)
  Directional -> Accuracy: 0.5952, MCC: 0.1848, F1: 0.5143

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65152 | val 0.82473
  Epoch 020 - train 0.48825 | val 1.19895
  Epoch 021 - train 0.48099 | val 1.17823
  Classification -> best τ=0.315 (val F1=0.3577)
  Directional -> Accuracy: 0.6308, MCC: 0.2471, F1: 0.6757

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.62454 | val 1.04376
  Epoch 020 - train 0.41447 | val 2.34979
  Epoch 024 - train 0.35446 | val 2.44165
  Classification -> best τ=0.410 (val F1=0.2582)
  Directional -> Accuracy: 0.6250, MCC: 0.2950, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60312 | val 0.94586
  Epoch 020 - train 0.45705 | val 1.62462
  Epoch 021 - train 0.47828 | val 1.61316
  Classification -> best τ=0.515 (val F1=0.2008)
  Directional -> Accuracy: 0.5455, MCC: 0.0690, F1: 0.4444

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.70243 | val 0.78659
  Epoch 020 - train 0.49259 | val 1.00893
  Epoch 021 - train 0.46198 | val 1.13130
  Classification -> best τ=0.585 (val F1=0.1548)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57659 | val 0.62934
  Epoch 020 - train 0.62403 | val 1.56482
  Epoch 026 - train 0.46268 | val 1.00622
  Classification -> best τ=0.640 (val F1=0.5008)
  Directional -> Accuracy: 0.3043, MCC: -0.1919, F1: 0.4483

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.65850 | val 0.83061
  Epoch 020 - train 0.57401 | val 1.38156
  Epoch 022 - train 0.53793 | val 1.54401
  Classification -> best τ=0.260 (val F1=0.2988)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65972 | val 0.92474
  Epoch 020 - train 0.57958 | val 1.65679
  Epoch 021 - train 0.56918 | val 1.66708
  Classification -> best τ=0.510 (val F1=0.2843)
  Directional -> Accuracy: 0.4773, MCC: -0.1525, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66567 | val 0.69246
  Epoch 020 - train 0.60155 | val 0.95063
  Epoch 029 - train 0.29610 | val 0.87776
  Classification -> best τ=0.390 (val F1=0.3143)
  Directional -> Accuracy: 0.5854, MCC: 0.0570, F1: 0.7213

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.60680 | val 1.24116
  Epoch 020 - train 0.45775 | val 1.32857
  Epoch 022 - train 0.42074 | val 1.70499
  Classification -> best τ=0.460 (val F1=0.2392)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67163 | val 0.67140
  Epoch 020 - train 0.60158 | val 0.85055
  Epoch 026 - train 0.59774 | val 1.02480
  Classification -> best τ=0.500 (val F1=0.3695)
  Directional -> Accuracy: 0.4630, MCC: -0.0921, F1: 0.5246

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.64483 | val 1.92649
  Epoch 020 - train 0.57621 | val 3.80536
  Epoch 021 - train 0.55743 | val 3.62931
  Classification -> best τ=0.500 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67008 | val 0.87174
  Epoch 020 - train 0.55733 | val 0.89065
  Epoch 022 - train 0.61231 | val 0.93449
  Classification -> best τ=0.520 (val F1=0.0392)
  Directional -> Accuracy: 0.4615, MCC: -0.2000, F1: 0.6316

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.65253 | val 0.84728
  Epoch 020 - train 0.58908 | val 0.99061
  Epoch 025 - train 0.54728 | val 0.89831
  Classification -> best τ=0.510 (val F1=0.2397)
  Directional -> Accuracy: 0.5370, MCC: 0.1425, F1: 0.6914

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68851 | val 0.69222
  Epoch 020 - train 0.66245 | val 1.26807
  Epoch 030 - train 0.53577 | val 2.89510

[I 2026-02-19 04:53:23,213] Trial 63 finished with value: 0.25384323377634316 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.00407911901079742, 'weight_decay': 2.7683503242415317e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.6797840613716528, 'early_stopping_min_delta': 0.0018535649575981586}. Best is trial 53 with value: 0.2732635960250114.

  Epoch 031 - train 0.49165 | val 3.16734
  Classification -> best τ=0.340 (val F1=0.2054)
  Directional -> Accuracy: 0.4576, MCC: -0.1382, F1: 0.6279

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.25384323377634316
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64454 | val 1.01653
  Epoch 020 - train 0.54895 | val 1.33397
  Epoch 022 - train 0.54461 | val 1.38772
  Classification -> best τ=0.595 (val F1=0.2895)
  Directional -> Accuracy: 0.5405, MCC: -0.0249, F1: 0.1053

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.56877 | val 0.79172
  Epoch 020 - train 0.46621 | val 1.42554
  Epoch 023 - train 0.45576 | val 1.30310
  Classification -> best τ=0.445 (val F1=0.2135)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57880 | val 0.90472
  Epoch 020 - train 0.54807 | val 1.70976
  Epoch 022 - train 0.54206 | val 1.54412
  Classification -> best τ=0.500 (val F1=0.2885)
  Directional -> Accuracy: 0.5682, MCC: 0.2145, F1: 0.3871

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62902 | val 1.94630
  Epoch 020 - train 0.57178 | val 5.56880
  Epoch 021 - train 0.55027 | val 5.61675
  Classification -> best τ=0.485 (val F1=0.0472)
  Directional -> Accuracy: 0.5556, MCC: 0.1189, F1: 0.5556

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.58736 | val 1.35088
  Epoch 020 - train 0.43237 | val 1.37061
  Epoch 022 - train 0.39886 | val 1.38791
  Classification -> best τ=0.435 (val F1=0.4181)
  Directional -> Accuracy: 0.7500, MCC: 0.4991, F1: 0.7600

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.55421 | val 1.97846
  Epoch 020 - train 0.44705 | val 6.63224
  Epoch 021 - train 0.43264 | val 5.77359
  Classification -> best τ=0.515 (val F1=0.2392)
  Directional -> Accuracy: 0.5682, MCC: 0.1690, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.63486 | val 1.02573
  Epoch 020 - train 0.53417 | val 1.13802
  Epoch 022 - train 0.50495 | val 1.24254
  Classification -> best τ=0.460 (val F1=0.3521)
  Directional -> Accuracy: 0.4242, MCC: 0.0336, F1: 0.5778

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64328 | val 1.17408
  Epoch 020 - train 0.53058 | val 1.40160
  Epoch 021 - train 0.45370 | val 2.00641
  Classification -> best τ=0.480 (val F1=0.1741)
  Directional -> Accuracy: 0.5128, MCC: 0.2538, F1: 0.6415

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61688 | val 0.83997
  Epoch 020 - train 0.46039 | val 1.23303
  Epoch 026 - train 0.31931 | val 1.37526
  Classification -> best τ=0.500 (val F1=0.4179)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62377 | val 1.37476
  Epoch 020 - train 0.53467 | val 1.48806
  Epoch 021 - train 0.52145 | val 1.59082
  Classification -> best τ=0.470 (val F1=0.2614)
  Directional -> Accuracy: 0.4179, MCC: -0.0292, F1: 0.5806

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60610 | val 3.24603
  Epoch 020 - train 0.47300 | val 3.69672
  Epoch 021 - train 0.43785 | val 4.43883
  Classification -> best τ=0.525 (val F1=0.0267)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65543 | val 0.94311
  Epoch 020 - train 0.55424 | val 2.21987
  Epoch 022 - train 0.53816 | val 2.08499
  Classification -> best τ=0.490 (val F1=0.2368)
  Directional -> Accuracy: 0.5818, MCC: 0.1561, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.62434 | val 0.87242
  Epoch 020 - train 0.46555 | val 1.30422
  Epoch 021 - train 0.48158 | val 1.34556
  Classification -> best τ=0.545 (val F1=0.0368)
  Directional -> Accuracy: 0.5417, MCC: 0.0731, F1: 0.4211

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66439 | val 1.73055
  Epoch 020 - train 0.58470 | val 2.32753
  Epoch 021 - train 0.55804 | val 2.26195
  Classification -> best τ=0.525 (val F1=0.2242)
  Directional -> Accuracy: 0.5690, MCC: 0.1597, F1: 0.4898

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64128 | val 1.10632
  Epoch 020 - train 0.47807 | val 1.02071
  Epoch 021 - train 0.47690 | val 1.08644
  Classification -> best τ=0.520 (val F1=0.0944)
  Directional -> Accuracy: 0.5306, MCC: -0.1303, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62632 | val 0.94592
  Epoch 020 - train 0.51343 | val 1.22356
  Epoch 021 - train 0.53524 | val 1.30411
  Classification -> best τ=0.440 (val F1=0.2287)
  Directional -> Accuracy: 0.5821, MCC: 0.2333, F1: 0.7200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65260 | val 0.96735
  Epoch 020 - train 0.53803 | val 1.84534
  Epoch 021 - train 0.53312 | val 1.77806
  Classification -> best τ=0.580 (val F1=0.0842)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.62622 | val 1.11736
  Epoch 020 - train 0.55771 | val 1.19375
  Epoch 023 - train 0.52746 | val 1.37296
  Classification -> best τ=0.525 (val F1=0.2041)
  Directional -> Accuracy: 0.5616, MCC: -0.0788, F1: 0.7143

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.58529 | val 0.82088
  Epoch 020 - train 0.49715 | val 1.13693
  Epoch 022 - train 0.48044 | val 1.19985
  Classification -> best τ=0.455 (val F1=0.2412)
  Directional -> Accuracy: 0.5000, MCC: 0.1646, F1: 0.3111

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65136 | val 0.94577
  Epoch 020 - train 0.52479 | val 0.92384
  Epoch 022 - train 0.50689 | val 0.90248
  Classification -> best τ=0.400 (val F1=0.2292)
  Directional -> Accuracy: 0.5278, MCC: 0.1179, F1: 0.4333

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.54084 | val 1.66189
  Epoch 020 - train 0.37220 | val 3.11754
  Epoch 023 - train 0.32307 | val 3.86216
  Classification -> best τ=0.480 (val F1=0.2739)
  Directional -> Accuracy: 0.4222, MCC: -0.0962, F1: 0.3810

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.65511 | val 1.01691
  Epoch 020 - train 0.54268 | val 1.06375
  Epoch 021 - train 0.50458 | val 1.01470
  Classification -> best τ=0.510 (val F1=0.2364)
  Directional -> Accuracy: 0.5238, MCC: 0.0518, F1: 0.2500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.65416 | val 0.96018
  Epoch 020 - train 0.53833 | val 0.88829
  Epoch 023 - train 0.47242 | val 0.76034
  Classification -> best τ=0.520 (val F1=0.2738)
  Directional -> Accuracy: 0.3636, MCC: -0.2833, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63673 | val 0.70315
  Epoch 020 - train 0.55262 | val 0.73341
  Epoch 021 - train 0.53434 | val 0.72331
  Classification -> best τ=0.460 (val F1=0.1217)
  Directional -> Accuracy: 0.5556, MCC: 0.1237, F1: 0.5882

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.61895 | val 0.94725
  Epoch 020 - train 0.40659 | val 1.14042
  Epoch 024 - train 0.46379 | val 1.17294
  Classification -> best τ=0.605 (val F1=0.3963)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60752 | val 1.33741
  Epoch 020 - train 0.41362 | val 2.61864
  Epoch 024 - train 0.35660 | val 5.32002
  Classification -> best τ=0.495 (val F1=0.3327)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.58371 | val 1.52070
  Epoch 020 - train 0.55885 | val 2.39462
  Epoch 021 - train 0.52846 | val 2.59345
  Classification -> best τ=0.475 (val F1=0.0795)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5385

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.62249 | val 1.31054
  Epoch 020 - train 0.50231 | val 1.69074
  Epoch 021 - train 0.47581 | val 1.61488
  Classification -> best τ=0.525 (val F1=0.1062)
  Directional -> Accuracy: 0.4259, MCC: -0.2112, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.54025 | val 2.53066
  Epoch 020 - train 0.47563 | val 4.86859
  Epoch 021 - train 0.44812 | val 3.37583
  Classification -> best τ=0.515 (val F1=0.1491)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3750

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.63079 | val 0.80265
  Epoch 020 - train 0.42120 | val 1.03586
  Epoch 024 - train 0.40690 | val 1.11029
  Classification -> best τ=0.520 (val F1=0.1869)
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56665 | val 0.73254
  Epoch 020 - train 0.45696 | val 1.00322
  Epoch 024 - train 0.39119 | val 1.07804
  Classification -> best τ=0.410 (val F1=0.2845)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64248 | val 0.88251
  Epoch 020 - train 0.52576 | val 0.90191
  Epoch 023 - train 0.50264 | val 1.06817
  Classification -> best τ=0.500 (val F1=0.3067)
  Directional -> Accuracy: 0.5143, MCC: 0.1300, F1: 0.3462

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.61977 | val 1.13529
  Epoch 020 - train 0.46519 | val 1.29885
  Epoch 024 - train 0.42034 | val 1.61804
  Classification -> best τ=0.400 (val F1=0.3015)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60720 | val 0.93573
  Epoch 020 - train 0.53390 | val 1.21158
  Epoch 022 - train 0.52561 | val 1.27219
  Classification -> best τ=0.400 (val F1=0.3921)
  Directional -> Accuracy: 0.5469, MCC: 0.0615, F1: 0.6234

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52855 | val 2.47761
  Epoch 020 - train 0.39633 | val 3.94645
  Epoch 022 - train 0.42636 | val 4.05447
  Classification -> best τ=0.530 (val F1=0.3837)
  Directional -> Accuracy: 0.5918, MCC: 0.2129, F1: 0.4118

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59088 | val 0.97051
  Epoch 020 - train 0.41927 | val 1.44198
  Epoch 024 - train 0.43919 | val 1.81022
  Classification -> best τ=0.365 (val F1=0.2517)
  Directional -> Accuracy: 0.5370, MCC: 0.1781, F1: 0.6479

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51517 | val 3.30593
  Epoch 020 - train 0.31573 | val 4.28709
  Epoch 021 - train 0.37095 | val 4.03029
  Classification -> best τ=0.505 (val F1=0.2331)
  Directional -> Accuracy: 0.3864, MCC: -0.0738, F1: 0.1290

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.65834 | val 0.58684
  Epoch 020 - train 0.48644 | val 0.67496
  Epoch 029 - train 0.31066 | val 0.85983
  Classification -> best τ=0.500 (val F1=0.5415)
  Directional -> Accuracy: 0.4667, MCC: 0.0328, F1: 0.4545

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.61162 | val 1.89344
  Epoch 020 - train 0.49495 | val 2.36869
  Epoch 021 - train 0.48547 | val 2.48063
  Classification -> best τ=0.490 (val F1=0.1965)
  Directional -> Accuracy: 0.5278, MCC: 0.1213, F1: 0.6731

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.59929 | val 0.82364
  Epoch 020 - train 0.43835 | val 0.79374
  Epoch 024 - train 0.40669 | val 1.02679
  Classification -> best τ=0.400 (val F1=0.3054)
  Directional -> Accuracy: 0.4186, MCC: -0.2280, F1: 0.5614

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56047 | val 0.68277
  Epoch 020 - train 0.41219 | val 1.31025
  Epoch 030 - train 0.26151 | val 1.29819
  Epoch 031 - train 0.28604 | val 1.14498
  Classification -> best τ=0.200 (val F1=0.4114)
  Directional -> Accuracy: 0.5897, MCC: 0.0000, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61137 | val 1.33864
  Epoch 020 - train 0.46092 | val 1.36007
  Epoch 021 - train 0.50102 | val 1.56596
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.60679 | val 1.27490
  Epoch 020 - train 0.54321 | val 1.17198
  Epoch 021 - train 0.55172 | val 1.28402
  Classification -> best τ=0.480 (val F1=0.2315)
  Directional -> Accuracy: 0.4717, MCC: 0.1262, F1: 0.0667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65469 | val 0.80495
  Epoch 020 - train 0.54919 | val 1.08427
  Epoch 024 - train 0.48115 | val 1.21505
  Classification -> best τ=0.650 (val F1=0.3213)
  Directional -> Accuracy: 0.5556, MCC: 0.1654, F1: 0.2941

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.61608 | val 1.89599
  Epoch 020 - train 0.51217 | val 2.09611
  Epoch 021 - train 0.51440 | val 1.90733
  Classification -> best τ=0.465 (val F1=0.2469)
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57370 | val 1.97013
  Epoch 020 - train 0.47752 | val 2.57263
  Epoch 021 - train 0.45966 | val 1.40789
  Classification -> best τ=0.505 (val F1=0.3010)
  Directional -> Accuracy: 0.5472, MCC: 0.1483, F1: 0.6842

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.63626 | val 0.88780
  Epoch 020 - train 0.52616 | val 1.27125
  Epoch 021 - train 0.55587 | val 1.34578

[I 2026-02-19 05:04:48,624] Trial 64 finished with value: 0.24123356924570738 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.00109002078001365, 'weight_decay': 7.69265322383985e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.541590607147073, 'early_stopping_min_delta': 0.0004328198311610047}. Best is trial 53 with value: 0.2732635960250114.

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24123356924570738
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.63804 | val 1.56807
  Epoch 020 - train 0.43299 | val 1.19829
  Epoch 021 - train 0.37382 | val 1.99556
  Classification -> best τ=0.555 (val F1=0.2034)
  Directional -> Accuracy: 0.5676, MCC: 0.0821, F1: 0.2381

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51010 | val 0.95225
  Epoch 020 - train 0.19301 | val 3.20532
  Epoch 022 - train 0.15915 | val 3.92372
  Classification -> best τ=0.465 (val F1=0.0598)
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.54623 | val 0.88087
  Epoch 020 - train 0.33905 | val 1.83596
  Epoch 022 - train 0.24287 | val 2.05105
  Classification -> best τ=0.505 (val F1=0.2890)
  Directional -> Accuracy: 0.6136, MCC: 0.2243, F1: 0.6383

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.62004 | val 1.27672
  Epoch 020 - train 0.46778 | val 2.22056
  Epoch 022 - train 0.40259 | val 2.18796
  Classification -> best τ=0.585 (val F1=0.1685)
  Directional -> Accuracy: 0.4167, MCC: -0.1449, F1: 0.2500

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49486 | val 1.58786
  Epoch 020 - train 0.22782 | val 2.31956
  Epoch 024 - train 0.14597 | val 3.26209
  Classification -> best τ=0.665 (val F1=0.4189)
  Directional -> Accuracy: 0.6042, MCC: 0.3171, F1: 0.4242

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47820 | val 5.93306
  Epoch 020 - train 0.14343 | val 10.28912
  Epoch 021 - train 0.10328 | val 12.06168
  Classification -> best τ=0.450 (val F1=0.0934)
  Directional -> Accuracy: 0.4091, MCC: -0.1849, F1: 0.3500

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.59398 | val 1.20522
  Epoch 020 - train 0.35906 | val 1.87798
  Epoch 022 - train 0.25873 | val 2.27740
  Classification -> best τ=0.565 (val F1=0.1834)
  Directional -> Accuracy: 0.5758, MCC: -0.1032, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42599 | val 0.82405
  Epoch 020 - train 0.15751 | val 2.42281
  Epoch 021 - train 0.15383 | val 2.97743
  Classification -> best τ=0.530 (val F1=0.1925)
  Directional -> Accuracy: 0.3590, MCC: -0.2616, F1: 0.3902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51049 | val 1.24517
  Epoch 020 - train 0.11285 | val 1.88232
  Epoch 023 - train 0.06558 | val 2.17005
  Classification -> best τ=0.380 (val F1=0.3292)
  Directional -> Accuracy: 0.5217, MCC: -0.1150, F1: 0.0833

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65599 | val 0.88387
  Epoch 020 - train 0.42710 | val 2.28311
  Epoch 021 - train 0.38860 | val 1.52121
  Classification -> best τ=0.460 (val F1=0.1367)
  Directional -> Accuracy: 0.4478, MCC: -0.0424, F1: 0.5067

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.54442 | val 2.75729
  Epoch 020 - train 0.25198 | val 8.52644
  Epoch 023 - train 0.21009 | val 7.91763
  Classification -> best τ=0.455 (val F1=0.2525)
  Directional -> Accuracy: 0.5532, MCC: 0.0626, F1: 0.3636

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.55590 | val 1.80169
  Epoch 020 - train 0.27487 | val 4.82964
  Epoch 022 - train 0.38174 | val 4.64969
  Classification -> best τ=0.455 (val F1=0.3095)
  Directional -> Accuracy: 0.6727, MCC: 0.3470, F1: 0.6786

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50715 | val 2.81053
  Epoch 020 - train 0.22457 | val 1.88845
  Epoch 024 - train 0.18332 | val 1.99884
  Classification -> best τ=0.610 (val F1=0.4200)
  Directional -> Accuracy: 0.5208, MCC: 0.0268, F1: 0.3784

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62315 | val 1.19200
  Epoch 020 - train 0.31381 | val 4.80675
  Epoch 021 - train 0.29015 | val 5.36032
  Classification -> best τ=0.475 (val F1=0.3491)
  Directional -> Accuracy: 0.5345, MCC: 0.0619, F1: 0.5970

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.56403 | val 1.27194
  Epoch 020 - train 0.21777 | val 3.39046
  Epoch 021 - train 0.25357 | val 3.50709
  Classification -> best τ=0.540 (val F1=0.1487)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.65352 | val 1.67225
  Epoch 020 - train 0.25812 | val 2.68951
  Epoch 022 - train 0.24966 | val 3.44163
  Classification -> best τ=0.670 (val F1=0.3563)
  Directional -> Accuracy: 0.5672, MCC: 0.1276, F1: 0.6027

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.57206 | val 2.48150
  Epoch 020 - train 0.36354 | val 3.43911
  Epoch 021 - train 0.35404 | val 3.64867
  Classification -> best τ=0.590 (val F1=0.1313)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60317 | val 2.16102
  Epoch 020 - train 0.43307 | val 1.11968
  Epoch 022 - train 0.43468 | val 1.67819
  Classification -> best τ=0.475 (val F1=0.1368)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.53364 | val 1.88347
  Epoch 020 - train 0.18408 | val 2.97742
  Epoch 022 - train 0.18738 | val 3.24041
  Classification -> best τ=0.530 (val F1=0.1738)
  Directional -> Accuracy: 0.5000, MCC: 0.1646, F1: 0.3111

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57926 | val 1.36767
  Epoch 020 - train 0.27156 | val 2.49736
  Epoch 021 - train 0.28241 | val 2.50966
  Classification -> best τ=0.585 (val F1=0.2331)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53976 | val 2.64088
  Epoch 020 - train 0.21080 | val 4.20730
  Epoch 022 - train 0.17744 | val 4.62611
  Classification -> best τ=0.410 (val F1=0.2988)
  Directional -> Accuracy: 0.5333, MCC: -0.1001, F1: 0.6769

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.57074 | val 1.99291
  Epoch 020 - train 0.30939 | val 3.37346
  Epoch 022 - train 0.26616 | val 2.71162
  Classification -> best τ=0.555 (val F1=0.0640)
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.47777 | val 1.43176
  Epoch 020 - train 0.20364 | val 13.31917
  Epoch 022 - train 0.13267 | val 5.80022
  Classification -> best τ=0.550 (val F1=0.2895)
  Directional -> Accuracy: 0.4182, MCC: -0.0322, F1: 0.0588

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.57158 | val 2.66863
  Epoch 020 - train 0.36475 | val 1.37054
  Epoch 021 - train 0.40937 | val 1.11207
  Classification -> best τ=0.380 (val F1=0.1217)
  Directional -> Accuracy: 0.5714, MCC: 0.1651, F1: 0.6197

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.58954 | val 1.34070
  Epoch 020 - train 0.24777 | val 3.11117
  Epoch 024 - train 0.15612 | val 3.50255
  Classification -> best τ=0.470 (val F1=0.2896)
  Directional -> Accuracy: 0.4906, MCC: 0.0659, F1: 0.2703

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.31463 | val 3.40239
  Epoch 020 - train 0.03903 | val 6.28691
  Epoch 021 - train 0.07007 | val 7.43120
  Classification -> best τ=0.515 (val F1=0.0356)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.51736 | val 2.31168
  Epoch 020 - train 0.29704 | val 0.98401
  Epoch 030 - train 0.06639 | val 2.76018
  Epoch 032 - train 0.05845 | val 3.08082
  Classification -> best τ=0.630 (val F1=0.4268)
  Directional -> Accuracy: 0.4792, MCC: 0.0074, F1: 0.4444

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.50782 | val 2.05461
  Epoch 020 - train 0.18340 | val 2.85227
  Epoch 021 - train 0.23419 | val 2.55123
  Classification -> best τ=0.465 (val F1=0.1139)
  Directional -> Accuracy: 0.5370, MCC: 0.0000, F1: 0.6988

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.48442 | val 2.34176
  Epoch 020 - train 0.22143 | val 5.49774
  Epoch 022 - train 0.14100 | val 6.89344
  Classification -> best τ=0.620 (val F1=0.2928)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5238

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.51429 | val 1.01578
  Epoch 020 - train 0.28037 | val 1.74728
  Epoch 025 - train 0.11807 | val 2.16161
  Classification -> best τ=0.805 (val F1=0.1869)
  Directional -> Accuracy: 0.4750, MCC: 0.1448, F1: 0.0870

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44427 | val 1.04182
  Epoch 020 - train 0.09559 | val 2.66327
  Epoch 024 - train 0.01181 | val 3.39346
  Classification -> best τ=0.400 (val F1=0.4454)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64106 | val 0.80554
  Epoch 020 - train 0.40280 | val 1.18063
  Epoch 022 - train 0.42329 | val 1.57964
  Classification -> best τ=0.335 (val F1=0.2625)
  Directional -> Accuracy: 0.5857, MCC: 0.1910, F1: 0.5797

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39020 | val 2.08239
  Epoch 020 - train 0.12319 | val 2.70571
  Epoch 021 - train 0.12375 | val 2.21822
  Classification -> best τ=0.460 (val F1=0.2075)
  Directional -> Accuracy: 0.5306, MCC: 0.2402, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.53796 | val 1.04393
  Epoch 020 - train 0.23684 | val 2.20531
  Epoch 021 - train 0.26307 | val 2.41119
  Classification -> best τ=0.430 (val F1=0.3977)
  Directional -> Accuracy: 0.6406, MCC: 0.2876, F1: 0.6567

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42474 | val 2.20199
  Epoch 020 - train 0.09384 | val 5.70501
  Epoch 021 - train 0.06638 | val 5.78603
  Classification -> best τ=0.540 (val F1=0.3810)
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59900 | val 2.12310
  Epoch 020 - train 0.29658 | val 2.99776
  Epoch 021 - train 0.28809 | val 2.86609
  Classification -> best τ=0.475 (val F1=0.2517)
  Directional -> Accuracy: 0.5185, MCC: 0.0619, F1: 0.5667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44040 | val 1.64630
  Epoch 020 - train 0.12105 | val 8.88574
  Epoch 021 - train 0.11459 | val 9.84410
  Classification -> best τ=0.480 (val F1=0.2130)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52414 | val 1.53693
  Epoch 020 - train 0.17550 | val 5.01994
  Epoch 023 - train 0.08779 | val 7.87271
  Classification -> best τ=0.430 (val F1=0.4567)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.56819 | val 2.18506
  Epoch 020 - train 0.40425 | val 3.31456
  Epoch 021 - train 0.32306 | val 3.57868
  Classification -> best τ=0.480 (val F1=0.1485)
  Directional -> Accuracy: 0.5139, MCC: 0.0283, F1: 0.4615

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55086 | val 0.80332
  Epoch 020 - train 0.25689 | val 1.59529
  Epoch 023 - train 0.17561 | val 2.41954
  Classification -> best τ=0.380 (val F1=0.2138)
  Directional -> Accuracy: 0.4884, MCC: -0.0197, F1: 0.4500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.32752 | val 0.92762
  Epoch 020 - train 0.04515 | val 1.50334
  Epoch 025 - train 0.03947 | val 1.57287
  Classification -> best τ=0.575 (val F1=0.2618)
  Directional -> Accuracy: 0.6154, MCC: 0.2300, F1: 0.6512

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.37356 | val 1.82781
  Epoch 020 - train 0.10080 | val 3.91621
  Epoch 021 - train 0.17448 | val 3.29140
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.63466 | val 1.17889
  Epoch 020 - train 0.34862 | val 3.07762
  Epoch 021 - train 0.38577 | val 3.23037
  Classification -> best τ=0.460 (val F1=0.1712)
  Directional -> Accuracy: 0.5849, MCC: 0.1458, F1: 0.7027

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.55526 | val 1.63766
  Epoch 020 - train 0.29278 | val 4.70887
  Epoch 021 - train 0.25131 | val 4.76341
  Classification -> best τ=0.600 (val F1=0.2390)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.3721

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.55938 | val 1.46465
  Epoch 020 - train 0.22893 | val 2.73780
  Epoch 023 - train 0.17566 | val 4.29706
  Classification -> best τ=0.445 (val F1=0.3128)
  Directional -> Accuracy: 0.5686, MCC: 0.2861, F1: 0.6944

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.46267 | val 4.07606
  Epoch 020 - train 0.18747 | val 4.83534
  Epoch 021 - train 0.17760 | val 3.44986
  Classification -> best τ=0.510 (val F1=0.3616)
  Directional -> Accuracy: 0.5094, MCC: 0.0037, F1: 0.6667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62160 | val 0.70014
  Epoch 020 - train 0.47926 | val 0.80002
  Epoch 030 - train 0.18275 | val 1.42191

[I 2026-02-19 05:10:55,377] Trial 65 finished with value: 0.2417735932356923 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.005933761154957567, 'weight_decay': 1.0674629141446888e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.9966308887372937, 'early_stopping_min_delta': 0.0026055305207062004}. Best is trial 53 with value: 0.2732635960250114.

  Epoch 032 - train 0.07268 | val 2.22129
  Classification -> best τ=0.635 (val F1=0.3335)
  Directional -> Accuracy: 0.5345, MCC: 0.1226, F1: 0.6197

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2417735932356923
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.71716 | val 0.75124
  Epoch 011 - train 0.70224 | val 0.75170
  Classification -> best τ=0.530 (val F1=0.1376)
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.6168

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68926 | val 0.68810
  Epoch 017 - train 0.68020 | val 0.69427
  Classification -> best τ=0.475 (val F1=0.3320)
  Directional -> Accuracy: 0.5581, MCC: 0.0052, F1: 0.6780

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69845 | val 0.71277
  Epoch 011 - train 0.69896 | val 0.71558
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.71711 | val 0.80923
  Epoch 011 - train 0.70393 | val 0.77743
  Classification -> best τ=0.475 (val F1=0.0063)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69498 | val 0.68380
  Epoch 020 - train 0.67450 | val 0.67206
  Epoch 030 - train 0.65174 | val 0.66208
  Epoch 040 - train 0.65694 | val 0.65956
  Epoch 050 - train 0.62444 | val 0.66071
  Classification -> best τ=0.415 (val F1=0.5105)
  Directional -> Accuracy: 0.7083, MCC: 0.4487, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66355 | val 0.71134
  Epoch 011 - train 0.67438 | val 0.71201
  Classification -> best τ=0.460 (val F1=0.0809)
  Directional -> Accuracy: 0.5227, MCC: 0.1525, F1: 0.6769

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69554 | val 0.69329
  Epoch 013 - train 0.68876 | val 0.69360
  Classification -> best τ=0.465 (val F1=0.1952)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.72149 | val 0.62413
  Epoch 020 - train 0.73932 | val 0.62616
  Epoch 022 - train 0.75685 | val 0.62970
  Classification -> best τ=0.380 (val F1=0.1448)
  Directional -> Accuracy: 0.5897, MCC: 0.1845, F1: 0.1111

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.73615 | val 0.70408
  Epoch 017 - train 0.70615 | val 0.70666
  Classification -> best τ=0.490 (val F1=0.2050)
  Directional -> Accuracy: 0.2609, MCC: -0.4692, F1: 0.2609

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69456 | val 0.69959
  Epoch 011 - train 0.69806 | val 0.70107
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70292 | val 0.65326
  Epoch 020 - train 0.68232 | val 0.66358
  Classification -> best τ=0.435 (val F1=0.3952)
  Directional -> Accuracy: 0.5745, MCC: 0.1641, F1: 0.0909

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69314 | val 0.75794
  Epoch 011 - train 0.69891 | val 0.75720
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.69934 | val 0.68775
  Epoch 020 - train 0.66271 | val 0.70036
  Epoch 023 - train 0.69924 | val 0.70476
  Classification -> best τ=0.455 (val F1=0.3155)
  Directional -> Accuracy: 0.5208, MCC: 0.0493, F1: 0.5490

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71536 | val 0.72012
  Epoch 011 - train 0.69705 | val 0.71866
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.71179 | val 0.70126
  Epoch 011 - train 0.66687 | val 0.70130
  Classification -> best τ=0.465 (val F1=0.0944)
  Directional -> Accuracy: 0.3265, MCC: -0.3672, F1: 0.2326

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69491 | val 0.72611
  Epoch 011 - train 0.71458 | val 0.72383
  Classification -> best τ=0.490 (val F1=0.0605)
  Directional -> Accuracy: 0.4925, MCC: -0.0525, F1: 0.5952

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71078 | val 0.76699
  Epoch 011 - train 0.73061 | val 0.77729
  Classification -> best τ=0.480 (val F1=0.0139)
  Directional -> Accuracy: 0.6429, MCC: 0.2293, F1: 0.7222

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.70382 | val 0.73491
  Epoch 011 - train 0.68876 | val 0.73732
  Classification -> best τ=0.490 (val F1=0.1111)
  Directional -> Accuracy: 0.4247, MCC: 0.0984, F1: 0.0455

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68386 | val 0.70324
  Epoch 011 - train 0.69317 | val 0.70204
  Classification -> best τ=0.515 (val F1=0.1211)
  Directional -> Accuracy: 0.5806, MCC: 0.0000, F1: 0.7347

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.68916 | val 0.75637
  Epoch 012 - train 0.67884 | val 0.76000
  Classification -> best τ=0.480 (val F1=0.1773)
  Directional -> Accuracy: 0.4722, MCC: 0.1512, F1: 0.0952

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.68674 | val 0.72849
  Epoch 011 - train 0.68260 | val 0.73147
  Classification -> best τ=0.540 (val F1=0.2411)
  Directional -> Accuracy: 0.6444, MCC: 0.2641, F1: 0.7714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71658 | val 0.71190
  Epoch 011 - train 0.71569 | val 0.71133
  Classification -> best τ=0.495 (val F1=0.1850)
  Directional -> Accuracy: 0.5079, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.71133 | val 0.75784
  Epoch 011 - train 0.71378 | val 0.75537
  Classification -> best τ=0.505 (val F1=0.1978)
  Directional -> Accuracy: 0.5091, MCC: -0.2374, F1: 0.6747

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68655 | val 0.69859
  Epoch 020 - train 0.67361 | val 0.68822
  Epoch 028 - train 0.67633 | val 0.69008
  Classification -> best τ=0.460 (val F1=0.1920)
  Directional -> Accuracy: 0.4921, MCC: 0.0259, F1: 0.6190

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.72848 | val 0.71683
  Epoch 011 - train 0.73207 | val 0.71311
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5472, MCC: 0.0000, F1: 0.7073

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.68177 | val 0.69183
  Epoch 011 - train 0.68021 | val 0.69267
  Classification -> best τ=0.525 (val F1=0.0403)
  Directional -> Accuracy: 0.6190, MCC: 0.2107, F1: 0.2727

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72418 | val 0.72338
  Epoch 011 - train 0.70318 | val 0.72964
  Classification -> best τ=0.485 (val F1=0.0769)
  Directional -> Accuracy: 0.4792, MCC: -0.0639, F1: 0.5455

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69262 | val 0.72088
  Epoch 011 - train 0.68505 | val 0.72122
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5370, MCC: 0.0000, F1: 0.6988

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69317 | val 0.76840
  Epoch 011 - train 0.71371 | val 0.78430
  Classification -> best τ=0.475 (val F1=0.2319)
  Directional -> Accuracy: 0.4750, MCC: -0.1601, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.71248 | val 0.69963
  Epoch 018 - train 0.70777 | val 0.71698
  Classification -> best τ=0.385 (val F1=0.2482)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.72710 | val 0.69885
  Epoch 016 - train 0.70795 | val 0.69895
  Classification -> best τ=0.545 (val F1=0.3637)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69149 | val 0.71496
  Epoch 011 - train 0.69162 | val 0.71206
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5571, MCC: 0.0000, F1: 0.7156

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70433 | val 0.72102
  Epoch 011 - train 0.70692 | val 0.72187
  Classification -> best τ=0.520 (val F1=0.0737)
  Directional -> Accuracy: 0.4694, MCC: -0.1820, F1: 0.0714

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69485 | val 0.67769
  Epoch 020 - train 0.67713 | val 0.67388
  Epoch 024 - train 0.69257 | val 0.67925
  Classification -> best τ=0.355 (val F1=0.3921)
  Directional -> Accuracy: 0.6406, MCC: 0.2558, F1: 0.7089

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66219 | val 0.68277
  Epoch 020 - train 0.64723 | val 0.68019
  Epoch 025 - train 0.66603 | val 0.68208
  Classification -> best τ=0.455 (val F1=0.3498)
  Directional -> Accuracy: 0.6735, MCC: 0.3744, F1: 0.5789

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.71313 | val 0.68280
  Epoch 016 - train 0.66435 | val 0.68508
  Classification -> best τ=0.495 (val F1=0.2277)
  Directional -> Accuracy: 0.5370, MCC: 0.0210, F1: 0.1379

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71780 | val 0.77955
  Epoch 011 - train 0.71422 | val 0.78426
  Classification -> best τ=0.535 (val F1=0.2734)
  Directional -> Accuracy: 0.3864, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.67263 | val 0.66933
  Epoch 020 - train 0.66843 | val 0.64904
  Epoch 030 - train 0.64742 | val 0.64634
  Epoch 040 - train 0.66830 | val 0.64239
  Epoch 050 - train 0.67641 | val 0.64065
  Classification -> best τ=0.475 (val F1=0.4973)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66730 | val 0.73946
  Epoch 011 - train 0.66118 | val 0.74150
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.69884 | val 0.70437
  Epoch 016 - train 0.68854 | val 0.70856
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.69419 | val 0.70333
  Epoch 011 - train 0.68469 | val 0.70375
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5897, MCC: 0.0000, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68557 | val 0.67514
  Epoch 018 - train 0.67292 | val 0.71480
  Classification -> best τ=0.520 (val F1=0.3213)
  Directional -> Accuracy: 0.6444, MCC: 0.1935, F1: 0.1111

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69186 | val 0.67247
  Epoch 019 - train 0.69537 | val 0.67647
  Classification -> best τ=0.465 (val F1=0.3676)
  Directional -> Accuracy: 0.5472, MCC: 0.0000, F1: 0.7073

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68810 | val 0.73718
  Epoch 013 - train 0.68564 | val 0.75718
  Classification -> best τ=0.545 (val F1=0.1159)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70949 | val 0.67873
  Epoch 015 - train 0.68313 | val 0.67671
  Classification -> best τ=0.570 (val F1=0.2468)
  Directional -> Accuracy: 0.5490, MCC: 0.1031, F1: 0.5818

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.69452 | val 0.72333
  Epoch 015 - train 0.69389 | val 0.75980
  Classification -> best τ=0.470 (val F1=0.3810)
  Directional -> Accuracy: 0.5849, MCC: 0.2450, F1: 0.7027

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70367 | val 0.69891
  Epoch 015 - train 0.68267 | val 0.69199
  Classification -> best τ=0.485 (val F1=0.1144)
  Directional -> Accuracy: 0.4483, MCC: -0.0787, F1: 0.5897

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1710498143877789

[I 2026-02-19 05:18:43,988] Trial 66 finished with value: 0.1710498143877789 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 7.880919493558746e-06, 'weight_decay': 5.050213697087681e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 1.2195053107413425, 'early_stopping_min_delta': 0.0011943856940571386}. Best is trial 53 with value: 0.2732635960250114.

Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64447 | val 0.66087
  Epoch 020 - train 0.65124 | val 1.21492
  Epoch 030 - train 0.55165 | val 1.07711
  Epoch 031 - train 0.56447 | val 1.14224
  Classification -> best τ=0.340 (val F1=0.3292)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.6239

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58364 | val 0.76885
  Epoch 020 - train 0.40008 | val 1.06231
  Epoch 022 - train 0.31087 | val 1.20926
  Classification -> best τ=0.505 (val F1=0.0649)
  Directional -> Accuracy: 0.5455, MCC: -0.1816, F1: 0.7059

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66596 | val 0.73422
  Epoch 020 - train 0.58470 | val 0.85111
  Epoch 022 - train 0.53927 | val 0.83455
  Classification -> best τ=0.585 (val F1=0.3380)
  Directional -> Accuracy: 0.4667, MCC: -0.0144, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67438 | val 0.68274
  Epoch 020 - train 0.64825 | val 1.94698
  Epoch 030 - train 0.51253 | val 1.68741
  Epoch 036 - train 0.48013 | val 1.57393
  Classification -> best τ=0.415 (val F1=0.2651)
  Directional -> Accuracy: 0.5342, MCC: 0.0799, F1: 0.5143

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.56856 | val 1.47696
  Epoch 020 - train 0.34415 | val 2.57208
  Epoch 023 - train 0.34448 | val 2.37094
  Classification -> best τ=0.485 (val F1=0.4709)
  Directional -> Accuracy: 0.5510, MCC: 0.1017, F1: 0.5600

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53581 | val 0.70159
  Epoch 020 - train 0.30026 | val 2.07809
  Epoch 023 - train 0.28390 | val 1.61226
  Classification -> best τ=0.560 (val F1=0.3241)
  Directional -> Accuracy: 0.5778, MCC: 0.1678, F1: 0.4242

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66423 | val 0.85382
  Epoch 020 - train 0.60598 | val 1.17865
  Epoch 021 - train 0.56733 | val 1.17375
  Classification -> best τ=0.430 (val F1=0.1186)
  Directional -> Accuracy: 0.4030, MCC: 0.0000, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.52086 | val 3.23193
  Epoch 020 - train 0.39426 | val 3.24311
  Epoch 021 - train 0.40130 | val 3.98603
  Classification -> best τ=0.540 (val F1=0.1491)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.55947 | val 1.48547
  Epoch 020 - train 0.55151 | val 1.92639
  Epoch 021 - train 0.50997 | val 2.49054
  Classification -> best τ=0.515 (val F1=0.2329)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.62066 | val 0.99574
  Epoch 020 - train 0.49607 | val 1.47804
  Epoch 021 - train 0.49774 | val 1.56007
  Classification -> best τ=0.390 (val F1=0.2304)
  Directional -> Accuracy: 0.4412, MCC: 0.0405, F1: 0.5957

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.68017 | val 1.95598
  Epoch 020 - train 0.52589 | val 1.83647
  Epoch 021 - train 0.53552 | val 1.91460
  Classification -> best τ=0.505 (val F1=0.2994)
  Directional -> Accuracy: 0.5625, MCC: 0.1015, F1: 0.4324

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.60929 | val 1.05892
  Epoch 020 - train 0.49280 | val 1.56288
  Epoch 022 - train 0.48251 | val 1.83168
  Classification -> best τ=0.455 (val F1=0.2556)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.54102 | val 4.25341
  Epoch 020 - train 0.42402 | val 7.11469
  Epoch 021 - train 0.43384 | val 7.28739
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.62993 | val 0.64623
  Epoch 020 - train 0.58255 | val 0.61599
  Epoch 030 - train 0.41416 | val 0.90260
  Epoch 032 - train 0.42434 | val 1.01574
  Classification -> best τ=0.285 (val F1=0.3536)
  Directional -> Accuracy: 0.4915, MCC: -0.0400, F1: 0.6250

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.62017 | val 0.88495
  Epoch 020 - train 0.44052 | val 1.41137
  Epoch 022 - train 0.44391 | val 1.70675
  Classification -> best τ=0.485 (val F1=0.2550)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68990 | val 0.65762
  Epoch 020 - train 0.59787 | val 0.96795
  Epoch 030 - train 0.34938 | val 2.07595
  Classification -> best τ=0.180 (val F1=0.2526)
  Directional -> Accuracy: 0.4706, MCC: -0.1419, F1: 0.6170

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64910 | val 0.84359
  Epoch 020 - train 0.53473 | val 1.87547
  Epoch 021 - train 0.55934 | val 1.93552
  Classification -> best τ=0.605 (val F1=0.2265)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63348 | val 1.60444
  Epoch 020 - train 0.49294 | val 3.01292
  Epoch 021 - train 0.50426 | val 2.98519
  Classification -> best τ=0.585 (val F1=0.1537)
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.63685 | val 0.96894
  Epoch 020 - train 0.44928 | val 1.82562
  Epoch 027 - train 0.38097 | val 2.88948
  Classification -> best τ=0.500 (val F1=0.2859)
  Directional -> Accuracy: 0.4127, MCC: -0.0462, F1: 0.0976

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62581 | val 1.33914
  Epoch 020 - train 0.50256 | val 1.63536
  Epoch 021 - train 0.51181 | val 1.39383
  Classification -> best τ=0.510 (val F1=0.2432)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.58226 | val 3.26450
  Epoch 020 - train 0.44115 | val 1.63905
  Epoch 023 - train 0.42735 | val 2.00270
  Classification -> best τ=0.575 (val F1=0.3232)
  Directional -> Accuracy: 0.4348, MCC: 0.0460, F1: 0.2353

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67439 | val 2.08022
  Epoch 020 - train 0.61107 | val 3.18801
  Epoch 021 - train 0.58637 | val 3.50659
  Classification -> best τ=0.480 (val F1=0.2149)
  Directional -> Accuracy: 0.5312, MCC: 0.0861, F1: 0.6512

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.61796 | val 2.06118
  Epoch 020 - train 0.47495 | val 2.46193
  Epoch 021 - train 0.47967 | val 2.37029
  Classification -> best τ=0.595 (val F1=0.2474)
  Directional -> Accuracy: 0.5000, MCC: 0.1005, F1: 0.3636

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.62937 | val 1.49383
  Epoch 020 - train 0.53906 | val 2.15705
  Epoch 022 - train 0.49768 | val 2.73620
  Classification -> best τ=0.430 (val F1=0.1604)
  Directional -> Accuracy: 0.5312, MCC: 0.0929, F1: 0.5946

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.52951 | val 1.24866
  Epoch 020 - train 0.38380 | val 1.42552
  Epoch 024 - train 0.34863 | val 1.67823
  Classification -> best τ=0.570 (val F1=0.4646)
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.53584 | val 0.94933
  Epoch 020 - train 0.40600 | val 0.97265
  Epoch 030 - train 0.23837 | val 1.45348
  Epoch 032 - train 0.18201 | val 1.51757
  Classification -> best τ=0.580 (val F1=0.3782)
  Directional -> Accuracy: 0.6279, MCC: 0.2025, F1: 0.3333

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.59843 | val 0.67944
  Epoch 020 - train 0.50673 | val 2.29063
  Epoch 030 - train 0.25211 | val 2.10589
  Classification -> best τ=0.610 (val F1=0.3344)
  Directional -> Accuracy: 0.5306, MCC: 0.1160, F1: 0.5106

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58969 | val 1.25370
  Epoch 020 - train 0.46243 | val 2.47049
  Epoch 021 - train 0.45634 | val 2.64509
  Classification -> best τ=0.460 (val F1=0.1943)
  Directional -> Accuracy: 0.5455, MCC: 0.0745, F1: 0.6032

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.60015 | val 0.71697
  Epoch 020 - train 0.42577 | val 0.69083
  Epoch 030 - train 0.38214 | val 0.71892
  Epoch 040 - train 0.28372 | val 0.82539
  Epoch 042 - train 0.25109 | val 0.85909
  Classification -> best τ=0.555 (val F1=0.3223)
  Directional -> Accuracy: 0.5000, MCC: 0.0289, F1: 0.4571

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60850 | val 2.28940
  Epoch 020 - train 0.45181 | val 3.18863
  Epoch 021 - train 0.35610 | val 2.80655
  Classification -> best τ=0.545 (val F1=0.2706)
  Directional -> Accuracy: 0.4634, MCC: -0.2210, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.65201 | val 1.30008
  Epoch 020 - train 0.39518 | val 1.60314
  Epoch 021 - train 0.38164 | val 2.21099
  Classification -> best τ=0.530 (val F1=0.1336)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.56716 | val 0.74295
  Epoch 020 - train 0.34429 | val 1.48824
  Epoch 022 - train 0.29911 | val 1.56848
  Classification -> best τ=0.505 (val F1=0.2843)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.62042 | val 0.82257
  Epoch 020 - train 0.54936 | val 0.78329
  Epoch 021 - train 0.56085 | val 0.78451
  Classification -> best τ=0.580 (val F1=0.2787)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65731 | val 0.94497
  Epoch 020 - train 0.54289 | val 1.13228
  Epoch 023 - train 0.48943 | val 1.04596
  Classification -> best τ=0.395 (val F1=0.4000)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.60699 | val 0.97317
  Epoch 020 - train 0.41591 | val 1.61187
  Epoch 021 - train 0.40716 | val 1.16803
  Classification -> best τ=0.350 (val F1=0.3577)
  Directional -> Accuracy: 0.5692, MCC: 0.0799, F1: 0.6744

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58056 | val 1.05943
  Epoch 020 - train 0.43949 | val 1.19169
  Epoch 023 - train 0.47587 | val 1.15458
  Classification -> best τ=0.490 (val F1=0.3475)
  Directional -> Accuracy: 0.7000, MCC: 0.4127, F1: 0.6842

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54542 | val 0.90864
  Epoch 020 - train 0.38929 | val 1.74016
  Epoch 024 - train 0.32942 | val 1.98282
  Classification -> best τ=0.450 (val F1=0.2433)
  Directional -> Accuracy: 0.5273, MCC: 0.0467, F1: 0.4800

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.58325 | val 3.09308
  Epoch 020 - train 0.37020 | val 2.60143
  Epoch 021 - train 0.38560 | val 2.75320
  Classification -> best τ=0.530 (val F1=0.0943)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.50378 | val 1.09172
  Epoch 020 - train 0.33121 | val 1.41493
  Epoch 024 - train 0.26601 | val 1.72187
  Classification -> best τ=0.660 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.59900 | val 1.95194
  Epoch 020 - train 0.44249 | val 4.57503
  Epoch 021 - train 0.45253 | val 5.22648
  Classification -> best τ=0.615 (val F1=0.1237)
  Directional -> Accuracy: 0.5068, MCC: 0.0505, F1: 0.6538

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56665 | val 1.60636
  Epoch 020 - train 0.38627 | val 2.70358
  Epoch 023 - train 0.36635 | val 2.74486
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.48903 | val 1.09818
  Epoch 020 - train 0.44237 | val 1.35715
  Epoch 021 - train 0.37196 | val 1.39665
  Classification -> best τ=0.470 (val F1=0.2254)
  Directional -> Accuracy: 0.6098, MCC: 0.1517, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.45505 | val 1.62609
  Epoch 020 - train 0.28127 | val 2.61147
  Epoch 026 - train 0.17717 | val 3.05544
  Classification -> best τ=0.565 (val F1=0.6333)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65728 | val 0.68169
  Epoch 020 - train 0.59171 | val 1.02637
  Epoch 028 - train 0.50247 | val 1.12795
  Classification -> best τ=0.405 (val F1=0.2839)
  Directional -> Accuracy: 0.4444, MCC: -0.1581, F1: 0.5455

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66374 | val 1.33880
  Epoch 020 - train 0.54532 | val 2.04929
  Epoch 021 - train 0.54882 | val 1.55242
  Classification -> best τ=0.480 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69752 | val 0.90765
  Epoch 020 - train 0.56366 | val 0.84595
  Epoch 030 - train 0.44236 | val 0.89583
  Epoch 034 - train 0.47278 | val 1.19666
  Classification -> best τ=0.455 (val F1=0.3008)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57551 | val 3.23876
  Epoch 020 - train 0.40941 | val 3.66655
  Epoch 022 - train 0.38291 | val 3.23348
  Classification -> best τ=0.640 (val F1=0.2444)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67649 | val 0.77482
  Epoch 020 - train 0.61532 | val 0.85894
  Epoch 030 - train 0.55703 | val 0.92041

[I 2026-02-19 05:29:41,271] Trial 67 finished with value: 0.26515256316258246 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiLSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.002682605409531048, 'weight_decay': 2.2774758386397047e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.4710523407392135, 'early_stopping_min_delta': 0.0020746910423637146}. Best is trial 53 with value: 0.2732635960250114.

  Epoch 031 - train 0.54674 | val 0.97026
  Classification -> best τ=0.330 (val F1=0.3386)
  Directional -> Accuracy: 0.4407, MCC: -0.1294, F1: 0.5926

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.26515256316258246
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64298 | val 0.78485
  Epoch 020 - train 0.57036 | val 0.98397
  Epoch 024 - train 0.52296 | val 1.01816
  Classification -> best τ=0.270 (val F1=0.1503)
  Directional -> Accuracy: 0.4800, MCC: 0.0969, F1: 0.6286

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.64738 | val 1.17454
  Epoch 020 - train 0.47744 | val 1.20589
  Epoch 023 - train 0.41799 | val 1.07601
  Classification -> best τ=0.395 (val F1=0.2920)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66583 | val 0.90317
  Epoch 020 - train 0.56139 | val 0.84052
  Epoch 021 - train 0.55783 | val 0.86175
  Classification -> best τ=0.525 (val F1=0.3508)
  Directional -> Accuracy: 0.4222, MCC: -0.1455, F1: 0.3810

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70039 | val 1.31039
  Epoch 020 - train 0.60017 | val 2.79854
  Epoch 021 - train 0.61219 | val 3.20679
  Classification -> best τ=0.455 (val F1=0.1859)
  Directional -> Accuracy: 0.4795, MCC: 0.0550, F1: 0.0952

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52238 | val 0.92320
  Epoch 020 - train 0.35537 | val 1.71025
  Epoch 022 - train 0.38991 | val 1.58182
  Classification -> best τ=0.570 (val F1=0.5084)
  Directional -> Accuracy: 0.6327, MCC: 0.2770, F1: 0.5909

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.52928 | val 1.42196
  Epoch 020 - train 0.32432 | val 1.15513
  Epoch 021 - train 0.31178 | val 1.51071
  Classification -> best τ=0.500 (val F1=0.2564)
  Directional -> Accuracy: 0.5778, MCC: 0.1877, F1: 0.6545

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.66758 | val 0.82791
  Epoch 020 - train 0.57551 | val 0.90993
  Epoch 021 - train 0.58443 | val 0.96299
  Classification -> best τ=0.530 (val F1=0.2177)
  Directional -> Accuracy: 0.5373, MCC: 0.0087, F1: 0.3673

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.50175 | val 3.65066
  Epoch 020 - train 0.32482 | val 4.98813
  Epoch 021 - train 0.32227 | val 4.69910
  Classification -> best τ=0.550 (val F1=0.0727)
  Directional -> Accuracy: 0.4146, MCC: -0.1299, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64026 | val 1.15500
  Epoch 020 - train 0.50916 | val 1.20539
  Epoch 021 - train 0.51674 | val 1.15464
  Classification -> best τ=0.520 (val F1=0.2329)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66953 | val 0.68358
  Epoch 020 - train 0.55264 | val 0.81538
  Epoch 030 - train 0.40123 | val 1.71458
  Classification -> best τ=0.495 (val F1=0.3105)
  Directional -> Accuracy: 0.4265, MCC: -0.0617, F1: 0.5517

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.63578 | val 1.46538
  Epoch 020 - train 0.57485 | val 1.26012
  Epoch 023 - train 0.57112 | val 1.20090
  Classification -> best τ=0.425 (val F1=0.1826)
  Directional -> Accuracy: 0.5625, MCC: 0.1159, F1: 0.5116

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.57480 | val 1.43624
  Epoch 020 - train 0.48493 | val 2.07204
  Epoch 022 - train 0.47286 | val 2.10284
  Classification -> best τ=0.360 (val F1=0.2556)
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50996 | val 3.85612
  Epoch 020 - train 0.33160 | val 7.30670
  Epoch 021 - train 0.36015 | val 8.52166
  Classification -> best τ=0.465 (val F1=0.1639)
  Directional -> Accuracy: 0.4898, MCC: -0.0500, F1: 0.1935

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66251 | val 0.75279
  Epoch 020 - train 0.55735 | val 0.65160
  Epoch 030 - train 0.34602 | val 1.15138
  Epoch 031 - train 0.35792 | val 1.11180
  Classification -> best τ=0.365 (val F1=0.3746)
  Directional -> Accuracy: 0.5593, MCC: 0.1205, F1: 0.6286

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.67756 | val 1.71777
  Epoch 020 - train 0.46640 | val 2.43472
  Epoch 021 - train 0.44969 | val 2.66586
  Classification -> best τ=0.560 (val F1=0.3061)
  Directional -> Accuracy: 0.4000, MCC: -0.1693, F1: 0.4643

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.66336 | val 0.89866
  Epoch 020 - train 0.48269 | val 1.15389
  Epoch 025 - train 0.47361 | val 1.83034
  Classification -> best τ=0.340 (val F1=0.3279)
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65225 | val 1.33538
  Epoch 020 - train 0.58107 | val 1.25441
  Epoch 021 - train 0.59546 | val 1.31601
  Classification -> best τ=0.610 (val F1=0.0529)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.64396 | val 1.36383
  Epoch 020 - train 0.60136 | val 2.11716
  Epoch 022 - train 0.57045 | val 2.52041
  Classification -> best τ=0.445 (val F1=0.1829)
  Directional -> Accuracy: 0.5946, MCC: 0.1979, F1: 0.6250

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66206 | val 0.85183
  Epoch 020 - train 0.54789 | val 1.15508
  Epoch 021 - train 0.57065 | val 1.21712
  Classification -> best τ=0.435 (val F1=0.1221)
  Directional -> Accuracy: 0.5873, MCC: 0.0000, F1: 0.7400

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.60489 | val 1.39043
  Epoch 020 - train 0.51751 | val 1.52456
  Epoch 022 - train 0.46003 | val 2.06666
  Classification -> best τ=0.380 (val F1=0.2777)
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.62572 | val 3.62819
  Epoch 020 - train 0.39633 | val 2.38280
  Epoch 021 - train 0.42773 | val 3.03329
  Classification -> best τ=0.430 (val F1=0.1410)
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68875 | val 0.91894
  Epoch 020 - train 0.62922 | val 1.74915
  Epoch 021 - train 0.62669 | val 1.62318
  Classification -> best τ=0.620 (val F1=0.0276)
  Directional -> Accuracy: 0.5469, MCC: 0.0938, F1: 0.5538

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63761 | val 2.31155
  Epoch 020 - train 0.61478 | val 2.12655
  Epoch 021 - train 0.62710 | val 2.40663
  Classification -> best τ=0.605 (val F1=0.2823)
  Directional -> Accuracy: 0.5893, MCC: 0.1970, F1: 0.5965

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60680 | val 1.13066
  Epoch 020 - train 0.48579 | val 1.68633
  Epoch 023 - train 0.40579 | val 2.75358
  Classification -> best τ=0.405 (val F1=0.2387)
  Directional -> Accuracy: 0.4219, MCC: -0.1932, F1: 0.5843

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.53782 | val 1.55720
  Epoch 020 - train 0.36707 | val 1.80604
  Epoch 023 - train 0.32966 | val 2.22742
  Classification -> best τ=0.375 (val F1=0.3953)
  Directional -> Accuracy: 0.4630, MCC: -0.0439, F1: 0.3256

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.60096 | val 0.99074
  Epoch 020 - train 0.36949 | val 1.22335
  Epoch 025 - train 0.35035 | val 1.54889
  Classification -> best τ=0.560 (val F1=0.2560)
  Directional -> Accuracy: 0.5814, MCC: 0.2254, F1: 0.6087

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65254 | val 0.75734
  Epoch 020 - train 0.56638 | val 0.70008
  Epoch 023 - train 0.57081 | val 0.83172
  Classification -> best τ=0.525 (val F1=0.2816)
  Directional -> Accuracy: 0.5510, MCC: 0.1496, F1: 0.5417

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.59468 | val 1.08620
  Epoch 020 - train 0.46068 | val 1.64134
  Epoch 021 - train 0.46093 | val 1.89432
  Classification -> best τ=0.440 (val F1=0.1474)
  Directional -> Accuracy: 0.5455, MCC: 0.0377, F1: 0.6753

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52737 | val 0.69227
  Epoch 020 - train 0.48458 | val 0.74321
  Epoch 029 - train 0.32067 | val 0.76380
  Classification -> best τ=0.430 (val F1=0.3337)
  Directional -> Accuracy: 0.5526, MCC: 0.0719, F1: 0.6383

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60257 | val 2.46612
  Epoch 020 - train 0.34417 | val 4.79704
  Epoch 021 - train 0.32299 | val 6.21356
  Classification -> best τ=0.575 (val F1=0.3150)
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.58879 | val 1.00766
  Epoch 020 - train 0.40277 | val 1.67955
  Epoch 021 - train 0.42056 | val 1.62554
  Classification -> best τ=0.555 (val F1=0.0199)
  Directional -> Accuracy: 0.3902, MCC: -0.1845, F1: 0.1935

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53898 | val 0.72226
  Epoch 020 - train 0.31586 | val 0.96483
  Epoch 022 - train 0.25627 | val 1.06604
  Classification -> best τ=0.585 (val F1=0.2382)
  Directional -> Accuracy: 0.5625, MCC: 0.1474, F1: 0.4878

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.61799 | val 1.01383
  Epoch 020 - train 0.56349 | val 1.20508
  Epoch 021 - train 0.55918 | val 1.22615
  Classification -> best τ=0.480 (val F1=0.2702)
  Directional -> Accuracy: 0.5070, MCC: 0.1078, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.60797 | val 0.96610
  Epoch 020 - train 0.43989 | val 1.04749
  Epoch 021 - train 0.46782 | val 1.07421
  Classification -> best τ=0.510 (val F1=0.3363)
  Directional -> Accuracy: 0.5000, MCC: -0.0426, F1: 0.2222

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.57338 | val 0.82457
  Epoch 020 - train 0.38977 | val 1.53430
  Epoch 022 - train 0.33994 | val 1.38829
  Classification -> best τ=0.265 (val F1=0.3218)
  Directional -> Accuracy: 0.6000, MCC: 0.1605, F1: 0.6829

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.58669 | val 0.84168
  Epoch 020 - train 0.40669 | val 1.69903
  Epoch 021 - train 0.37664 | val 1.79087
  Classification -> best τ=0.525 (val F1=0.3216)
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.61715 | val 0.96894
  Epoch 020 - train 0.41880 | val 1.12576
  Epoch 022 - train 0.42540 | val 1.45083
  Classification -> best τ=0.450 (val F1=0.2544)
  Directional -> Accuracy: 0.5455, MCC: 0.1077, F1: 0.5614

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.62802 | val 2.37681
  Epoch 020 - train 0.48264 | val 1.97749
  Epoch 021 - train 0.49115 | val 2.58711
  Classification -> best τ=0.555 (val F1=0.2913)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.52561 | val 0.87683
  Epoch 020 - train 0.35400 | val 1.19213
  Epoch 024 - train 0.30454 | val 1.65854
  Classification -> best τ=0.430 (val F1=0.4556)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64524 | val 1.05657
  Epoch 020 - train 0.53842 | val 1.62394
  Epoch 022 - train 0.51597 | val 1.63541
  Classification -> best τ=0.310 (val F1=0.2464)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.55518 | val 1.50216
  Epoch 020 - train 0.43167 | val 1.67500
  Epoch 023 - train 0.42328 | val 1.82693
  Classification -> best τ=0.415 (val F1=0.4910)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.47630 | val 1.16326
  Epoch 020 - train 0.20558 | val 1.42850
  Epoch 027 - train 0.13768 | val 2.78594
  Classification -> best τ=0.325 (val F1=0.3194)
  Directional -> Accuracy: 0.5854, MCC: 0.0000, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49063 | val 1.79803
  Epoch 020 - train 0.26117 | val 1.96615
  Epoch 021 - train 0.26118 | val 2.75389
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.66439 | val 0.82105
  Epoch 020 - train 0.58534 | val 1.01730
  Epoch 021 - train 0.54764 | val 1.09236
  Classification -> best τ=0.550 (val F1=0.1626)
  Directional -> Accuracy: 0.4444, MCC: -0.0219, F1: 0.0625

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.60319 | val 2.00551
  Epoch 020 - train 0.51949 | val 2.40292
  Epoch 021 - train 0.51563 | val 3.17954
  Classification -> best τ=0.410 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.63941 | val 0.67151
  Epoch 020 - train 0.54695 | val 2.06099
  Epoch 027 - train 0.50301 | val 2.25141
  Classification -> best τ=0.640 (val F1=0.2429)
  Directional -> Accuracy: 0.4808, MCC: -0.1400, F1: 0.6494

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.55983 | val 2.37999
  Epoch 020 - train 0.42813 | val 2.79161
  Epoch 021 - train 0.44917 | val 2.10805
  Classification -> best τ=0.580 (val F1=0.2107)
  Directional -> Accuracy: 0.5926, MCC: 0.2935, F1: 0.7179

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67803 | val 0.97351

[I 2026-02-19 05:40:10,228] Trial 68 finished with value: 0.24978336338676965 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiLSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.0027252760687000864, 'weight_decay': 2.175672636901006e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.4568185964068494, 'early_stopping_min_delta': 0.002156513155116833}. Best is trial 53 with value: 0.2732635960250114.

  Classification -> best τ=0.355 (val F1=0.3180)
  Directional -> Accuracy: 0.4407, MCC: -0.1135, F1: 0.5714

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24978336338676965
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.61565 | val 0.76740
  Epoch 020 - train 0.62483 | val 0.87490
  Classification -> best τ=0.410 (val F1=0.1744)
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.6239

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.58724 | val 1.33693
  Epoch 020 - train 0.53082 | val 1.34474
  Classification -> best τ=0.440 (val F1=0.2398)
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62058 | val 0.68903
  Epoch 020 - train 0.58210 | val 0.94179
  Classification -> best τ=0.315 (val F1=0.3086)
  Directional -> Accuracy: 0.5556, MCC: 0.1612, F1: 0.7059

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.65883 | val 1.38356
  Epoch 020 - train 0.61735 | val 1.89680
  Classification -> best τ=0.540 (val F1=0.0175)
  Directional -> Accuracy: 0.4521, MCC: -0.0934, F1: 0.4595

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.59283 | val 0.87217
  Epoch 020 - train 0.52175 | val 1.02370
  Classification -> best τ=0.695 (val F1=0.3048)
  Directional -> Accuracy: 0.5918, MCC: 0.2189, F1: 0.4737

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.58671 | val 0.74857
  Epoch 020 - train 0.51220 | val 1.22687
  Classification -> best τ=0.405 (val F1=0.3292)
  Directional -> Accuracy: 0.5778, MCC: 0.1771, F1: 0.6415

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65636 | val 0.90265
  Epoch 020 - train 0.61343 | val 0.93363
  Classification -> best τ=0.435 (val F1=0.2632)
  Directional -> Accuracy: 0.4328, MCC: 0.0445, F1: 0.5682

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58194 | val 2.25500
  Epoch 020 - train 0.55476 | val 3.93519
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56529 | val 0.83397
  Epoch 020 - train 0.54909 | val 0.80567
  Classification -> best τ=0.540 (val F1=0.1429)
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.61686 | val 1.45445
  Epoch 020 - train 0.57093 | val 0.77526
  Classification -> best τ=0.495 (val F1=0.0730)
  Directional -> Accuracy: 0.4412, MCC: 0.0405, F1: 0.5957

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.60329 | val 0.94896
  Epoch 020 - train 0.55077 | val 1.08344
  Classification -> best τ=0.490 (val F1=0.2176)
  Directional -> Accuracy: 0.5417, MCC: 0.0429, F1: 0.3125

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.64957 | val 1.14732
  Epoch 020 - train 0.58620 | val 1.12075
  Classification -> best τ=0.545 (val F1=0.2436)
  Directional -> Accuracy: 0.6071, MCC: 0.2766, F1: 0.4762

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.56431 | val 4.86933
  Epoch 020 - train 0.52154 | val 6.59749
  Classification -> best τ=0.520 (val F1=0.1101)
  Directional -> Accuracy: 0.5102, MCC: 0.0042, F1: 0.0769

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66721 | val 0.76624
  Epoch 020 - train 0.61400 | val 0.81355
  Classification -> best τ=0.500 (val F1=0.2881)
  Directional -> Accuracy: 0.4746, MCC: -0.0550, F1: 0.5231

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.60813 | val 1.55863
  Epoch 020 - train 0.53751 | val 1.40814
  Classification -> best τ=0.520 (val F1=0.2173)
  Directional -> Accuracy: 0.5600, MCC: 0.0907, F1: 0.4500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.61034 | val 0.87206
  Epoch 020 - train 0.58038 | val 1.21700
  Classification -> best τ=0.395 (val F1=0.3005)
  Directional -> Accuracy: 0.5735, MCC: 0.1654, F1: 0.7010

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.64584 | val 1.30916
  Epoch 020 - train 0.60529 | val 1.48945
  Classification -> best τ=0.525 (val F1=0.1361)
  Directional -> Accuracy: 0.3860, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.63406 | val 1.50088
  Epoch 020 - train 0.59074 | val 2.39257
  Classification -> best τ=0.495 (val F1=0.1444)
  Directional -> Accuracy: 0.6081, MCC: 0.1379, F1: 0.7129

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64159 | val 0.73105
  Epoch 020 - train 0.57634 | val 0.67841
  Classification -> best τ=0.445 (val F1=0.2987)
  Directional -> Accuracy: 0.4762, MCC: -0.0626, F1: 0.5352

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62605 | val 0.81158
  Epoch 020 - train 0.52748 | val 0.90795
  Classification -> best τ=0.375 (val F1=0.2187)
  Directional -> Accuracy: 0.5479, MCC: 0.0000, F1: 0.7080

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65528 | val 1.27664
  Epoch 020 - train 0.56977 | val 0.87745
  Classification -> best τ=0.470 (val F1=0.0763)
  Directional -> Accuracy: 0.5000, MCC: 0.2157, F1: 0.3429

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.63879 | val 1.50034
  Epoch 020 - train 0.60206 | val 1.52855
  Classification -> best τ=0.550 (val F1=0.1372)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63219 | val 1.22741
  Epoch 020 - train 0.58049 | val 1.97416
  Classification -> best τ=0.575 (val F1=0.2474)
  Directional -> Accuracy: 0.5357, MCC: 0.0521, F1: 0.5938

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.60627 | val 0.75458
  Epoch 020 - train 0.53515 | val 1.02273
  Classification -> best τ=0.485 (val F1=0.2106)
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.59398 | val 0.69227
  Epoch 020 - train 0.51033 | val 0.84865
  Classification -> best τ=0.515 (val F1=0.3407)
  Directional -> Accuracy: 0.4815, MCC: 0.0166, F1: 0.2632

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58588 | val 0.74297
  Epoch 020 - train 0.49875 | val 1.04152
  Classification -> best τ=0.535 (val F1=0.1486)
  Directional -> Accuracy: 0.3953, MCC: -0.1428, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65119 | val 1.09514
  Epoch 020 - train 0.60928 | val 1.49891
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5918, MCC: 0.0000, F1: 0.7436

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.63878 | val 0.86379
  Epoch 020 - train 0.56093 | val 1.27757
  Classification -> best τ=0.465 (val F1=0.2111)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6486

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.64718 | val 0.78603
  Epoch 020 - train 0.57328 | val 0.79609
  Classification -> best τ=0.490 (val F1=0.1510)
  Directional -> Accuracy: 0.5526, MCC: 0.1116, F1: 0.5641

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60370 | val 2.23179
  Epoch 020 - train 0.57894 | val 3.22243
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.64924 | val 1.00246
  Epoch 020 - train 0.58936 | val 1.16016
  Classification -> best τ=0.475 (val F1=0.2339)
  Directional -> Accuracy: 0.5854, MCC: 0.1245, F1: 0.6909

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.59296 | val 0.76738
  Epoch 020 - train 0.55136 | val 0.86068
  Classification -> best τ=0.510 (val F1=0.2268)
  Directional -> Accuracy: 0.6667, MCC: 0.3430, F1: 0.7241

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.59902 | val 0.97476
  Epoch 020 - train 0.54219 | val 1.31500
  Classification -> best τ=0.275 (val F1=0.2961)
  Directional -> Accuracy: 0.5634, MCC: 0.1538, F1: 0.5507

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.58858 | val 1.01731
  Epoch 020 - train 0.56907 | val 1.28715
  Classification -> best τ=0.465 (val F1=0.0275)
  Directional -> Accuracy: 0.5000, MCC: 0.1489, F1: 0.6557

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61173 | val 0.80994
  Epoch 020 - train 0.56818 | val 1.10302
  Classification -> best τ=0.410 (val F1=0.2640)
  Directional -> Accuracy: 0.6000, MCC: 0.1844, F1: 0.6486

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.60210 | val 0.71011
  Epoch 020 - train 0.50759 | val 0.75134
  Classification -> best τ=0.455 (val F1=0.2582)
  Directional -> Accuracy: 0.6000, MCC: 0.1951, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.59352 | val 0.90655
  Epoch 020 - train 0.52859 | val 0.96112
  Classification -> best τ=0.465 (val F1=0.1197)
  Directional -> Accuracy: 0.4909, MCC: -0.0199, F1: 0.4615

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.61385 | val 1.86298
  Epoch 020 - train 0.49036 | val 3.84173
  Classification -> best τ=0.550 (val F1=0.2626)
  Directional -> Accuracy: 0.6000, MCC: -0.1175, F1: 0.7500

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.56868 | val 0.59752
  Epoch 020 - train 0.54855 | val 0.63905
  Classification -> best τ=0.440 (val F1=0.5795)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.58378 | val 1.43266
  Epoch 020 - train 0.54646 | val 2.15536
  Classification -> best τ=0.450 (val F1=0.1727)
  Directional -> Accuracy: 0.4932, MCC: 0.0000, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.62082 | val 0.75810
  Epoch 020 - train 0.56773 | val 0.77067
  Classification -> best τ=0.455 (val F1=0.2652)
  Directional -> Accuracy: 0.5455, MCC: 0.1179, F1: 0.6552

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62583 | val 0.71901
  Epoch 020 - train 0.51415 | val 0.71148
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5854, MCC: 0.0000, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.61549 | val 0.93829
  Epoch 020 - train 0.56042 | val 1.27816
  Classification -> best τ=0.500 (val F1=0.0422)
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.64981 | val 1.30687
  Epoch 020 - train 0.57738 | val 1.31399
  Classification -> best τ=0.450 (val F1=0.1502)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61989 | val 1.63294
  Epoch 020 - train 0.58427 | val 2.10056
  Classification -> best τ=0.505 (val F1=0.2464)
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.58361 | val 0.84091
  Epoch 020 - train 0.59967 | val 1.28936
  Classification -> best τ=0.500 (val F1=0.2780)
  Directional -> Accuracy: 0.5385, MCC: 0.0913, F1: 0.6364

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.60787 | val 2.43232
  Epoch 020 - train 0.57705 | val 1.69890
  Classification -> best τ=0.515 (val F1=0.1336)
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.62212 | val 0.68345

[I 2026-02-19 05:45:07,549] Trial 69 finished with value: 0.1961594194523024 and parameters: {'feature_set': 'sentinment', 'model_type': 'LSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 0.0005834763811440056, 'weight_decay': 1.0699744097501304e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.720465586795787, 'early_stopping_min_delta': 0.0006996634868342155}. Best is trial 53 with value: 0.2732635960250114.

  Epoch 020 - train 0.58094 | val 0.83014
  Classification -> best τ=0.535 (val F1=0.3078)
  Directional -> Accuracy: 0.4915, MCC: -0.0232, F1: 0.4444

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.1961594194523024
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.66618 | val 0.85274
  Epoch 020 - train 0.65542 | val 0.83796
  Epoch 021 - train 0.64774 | val 0.83535
  Classification -> best τ=0.540 (val F1=0.1464)
  Directional -> Accuracy: 0.5867, MCC: 0.2242, F1: 0.1622

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.65446 | val 0.70922
  Epoch 020 - train 0.64597 | val 0.73396
  Epoch 023 - train 0.63497 | val 0.73691
  Classification -> best τ=0.465 (val F1=0.2503)
  Directional -> Accuracy: 0.4773, MCC: -0.0043, F1: 0.4651

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68861 | val 0.66496
  Epoch 020 - train 0.65028 | val 0.66359
  Epoch 030 - train 0.62959 | val 0.66807
  Classification -> best τ=0.580 (val F1=0.3961)
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.69177 | val 1.08838
  Epoch 020 - train 0.68012 | val 1.27821
  Epoch 021 - train 0.67305 | val 1.29324
  Classification -> best τ=0.425 (val F1=0.2651)
  Directional -> Accuracy: 0.5068, MCC: 0.1933, F1: 0.1429

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.65550 | val 0.69549
  Epoch 020 - train 0.61847 | val 0.64548
  Epoch 030 - train 0.61825 | val 0.62878
  Epoch 040 - train 0.60976 | val 0.62765
  Epoch 050 - train 0.60874 | val 0.63261
  Classification -> best τ=0.505 (val F1=0.4264)
  Directional -> Accuracy: 0.5918, MCC: 0.1995, F1: 0.5238

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67217 | val 0.76438
  Epoch 020 - train 0.62020 | val 0.80067
  Epoch 025 - train 0.61998 | val 0.82329
  Classification -> best τ=0.560 (val F1=0.2737)
  Directional -> Accuracy: 0.5333, MCC: 0.0709, F1: 0.2759

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.67439 | val 0.68712
  Epoch 020 - train 0.67511 | val 0.69134
  Epoch 028 - train 0.64143 | val 0.69054
  Classification -> best τ=0.535 (val F1=0.2212)
  Directional -> Accuracy: 0.5522, MCC: 0.0920, F1: 0.4828

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66117 | val 0.82649
  Epoch 020 - train 0.64957 | val 0.91261
  Epoch 021 - train 0.64266 | val 0.91976
  Classification -> best τ=0.520 (val F1=0.4082)
  Directional -> Accuracy: 0.5122, MCC: -0.0882, F1: 0.1667

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.65504 | val 0.71294
  Epoch 020 - train 0.64745 | val 0.71830
  Epoch 026 - train 0.63452 | val 0.72562
  Classification -> best τ=0.545 (val F1=0.3148)
  Directional -> Accuracy: 0.4468, MCC: -0.0556, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.66198 | val 0.83308
  Epoch 020 - train 0.63472 | val 0.97500
  Epoch 021 - train 0.65745 | val 0.98936
  Classification -> best τ=0.470 (val F1=0.1859)
  Directional -> Accuracy: 0.4118, MCC: -0.1417, F1: 0.5833

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.67215 | val 0.88317
  Epoch 020 - train 0.65302 | val 0.97267
  Epoch 021 - train 0.65298 | val 0.97486
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65344 | val 0.78559
  Epoch 020 - train 0.64156 | val 0.81741
  Epoch 021 - train 0.62308 | val 0.82018
  Classification -> best τ=0.480 (val F1=0.0274)
  Directional -> Accuracy: 0.5357, MCC: 0.0680, F1: 0.5667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67248 | val 1.03307
  Epoch 020 - train 0.65490 | val 1.34958
  Epoch 021 - train 0.62097 | val 1.37127
  Classification -> best τ=0.505 (val F1=0.0424)
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67007 | val 0.65925
  Epoch 020 - train 0.66172 | val 0.66616
  Epoch 024 - train 0.65064 | val 0.67242
  Classification -> best τ=0.450 (val F1=0.1651)
  Directional -> Accuracy: 0.5593, MCC: 0.1311, F1: 0.4800

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66210 | val 0.84743
  Epoch 020 - train 0.65996 | val 0.85244
  Epoch 021 - train 0.66633 | val 0.85649
  Classification -> best τ=0.550 (val F1=0.0605)
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.64903 | val 0.71099
  Epoch 020 - train 0.66253 | val 0.72711
  Epoch 022 - train 0.63273 | val 0.73477
  Classification -> best τ=0.510 (val F1=0.2588)
  Directional -> Accuracy: 0.5294, MCC: 0.0493, F1: 0.5789

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.67046 | val 0.94913
  Epoch 020 - train 0.65608 | val 1.10540
  Epoch 021 - train 0.65211 | val 1.12265
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6140, MCC: 0.0000, F1: 0.7609

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.66848 | val 0.77232
  Epoch 020 - train 0.66101 | val 0.90793
  Epoch 021 - train 0.66054 | val 0.90945
  Classification -> best τ=0.445 (val F1=0.1269)
  Directional -> Accuracy: 0.5946, MCC: 0.0000, F1: 0.7458

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65086 | val 0.75566
  Epoch 020 - train 0.64899 | val 0.81793
  Epoch 023 - train 0.63334 | val 0.83450
  Classification -> best τ=0.555 (val F1=0.1853)
  Directional -> Accuracy: 0.3968, MCC: -0.1515, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66344 | val 0.68424
  Epoch 020 - train 0.64495 | val 0.66243
  Epoch 030 - train 0.61512 | val 0.67178
  Epoch 040 - train 0.61778 | val 0.67629
  Epoch 041 - train 0.60648 | val 0.68000
  Classification -> best τ=0.480 (val F1=0.2734)
  Directional -> Accuracy: 0.4795, MCC: 0.0543, F1: 0.2083

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67582 | val 0.72739
  Epoch 020 - train 0.63343 | val 0.79994
  Epoch 024 - train 0.63401 | val 0.82868
  Classification -> best τ=0.490 (val F1=0.2249)
  Directional -> Accuracy: 0.6087, MCC: 0.1627, F1: 0.6897

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.66837 | val 0.97975
  Epoch 020 - train 0.64410 | val 1.16167
  Epoch 021 - train 0.64475 | val 1.17561
  Classification -> best τ=0.565 (val F1=0.2288)
  Directional -> Accuracy: 0.4844, MCC: -0.1260, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.68136 | val 0.67157
  Epoch 020 - train 0.63839 | val 0.69044
  Epoch 028 - train 0.63953 | val 0.70538
  Classification -> best τ=0.545 (val F1=0.3216)
  Directional -> Accuracy: 0.5536, MCC: 0.2198, F1: 0.4444

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.65361 | val 1.35610
  Epoch 020 - train 0.61684 | val 1.62638
  Epoch 021 - train 0.62986 | val 1.62965
  Classification -> best τ=0.455 (val F1=0.1687)
  Directional -> Accuracy: 0.4531, MCC: -0.1341, F1: 0.6237

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66481 | val 0.62416
  Epoch 020 - train 0.64288 | val 0.63661
  Epoch 026 - train 0.61908 | val 0.64459
  Classification -> best τ=0.500 (val F1=0.4781)
  Directional -> Accuracy: 0.5185, MCC: 0.1163, F1: 0.3158

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.71353 | val 0.68954
  Epoch 020 - train 0.65676 | val 0.70232
  Epoch 027 - train 0.67218 | val 0.70775
  Classification -> best τ=0.505 (val F1=0.2673)
  Directional -> Accuracy: 0.4884, MCC: -0.2057, F1: 0.0833

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68241 | val 0.68977
  Epoch 020 - train 0.66157 | val 0.69012
  Epoch 024 - train 0.65681 | val 0.68795
  Classification -> best τ=0.505 (val F1=0.2645)
  Directional -> Accuracy: 0.5510, MCC: -0.0569, F1: 0.6944

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67518 | val 0.70459
  Epoch 020 - train 0.65664 | val 0.70193
  Epoch 021 - train 0.67089 | val 0.70319
  Classification -> best τ=0.505 (val F1=0.0236)
  Directional -> Accuracy: 0.5091, MCC: -0.1773, F1: 0.6747

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.69148 | val 0.68168
  Epoch 020 - train 0.64581 | val 0.68234
  Epoch 030 - train 0.64274 | val 0.68243
  Epoch 031 - train 0.61418 | val 0.68235
  Classification -> best τ=0.390 (val F1=0.2955)
  Directional -> Accuracy: 0.5526, MCC: 0.0547, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66864 | val 0.82488
  Epoch 020 - train 0.63287 | val 0.88981
  Epoch 021 - train 0.64772 | val 0.89572
  Classification -> best τ=0.500 (val F1=0.2706)
  Directional -> Accuracy: 0.4878, MCC: -0.0358, F1: 0.3636

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68874 | val 0.77566
  Epoch 020 - train 0.64916 | val 0.80897
  Epoch 021 - train 0.66053 | val 0.81167
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.66978 | val 0.67170
  Epoch 020 - train 0.62699 | val 0.67800
  Epoch 029 - train 0.62464 | val 0.69032
  Classification -> best τ=0.410 (val F1=0.2055)
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64997 | val 0.74212
  Epoch 020 - train 0.63339 | val 0.75194
  Epoch 021 - train 0.63847 | val 0.75309
  Classification -> best τ=0.545 (val F1=0.2295)
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63955 | val 0.69730
  Epoch 020 - train 0.63555 | val 0.71604
  Epoch 025 - train 0.65484 | val 0.71854
  Classification -> best τ=0.520 (val F1=0.2811)
  Directional -> Accuracy: 0.5714, MCC: 0.1445, F1: 0.3571

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.64632 | val 0.69953
  Epoch 020 - train 0.63779 | val 0.70915
  Epoch 023 - train 0.62406 | val 0.71223
  Classification -> best τ=0.360 (val F1=0.2956)
  Directional -> Accuracy: 0.5231, MCC: 0.1987, F1: 0.3404

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.67112 | val 0.68396
  Epoch 020 - train 0.64761 | val 0.68918
  Epoch 026 - train 0.59565 | val 0.69494
  Classification -> best τ=0.450 (val F1=0.2697)
  Directional -> Accuracy: 0.4750, MCC: -0.0501, F1: 0.4878

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.63553 | val 0.73014
  Epoch 020 - train 0.61142 | val 0.78562
  Epoch 024 - train 0.61539 | val 0.79283
  Classification -> best τ=0.305 (val F1=0.2782)
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64987 | val 1.05093
  Epoch 020 - train 0.62292 | val 1.25338
  Epoch 021 - train 0.62871 | val 1.26449
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.66965 | val 0.65537
  Epoch 020 - train 0.65336 | val 0.64591
  Epoch 030 - train 0.61003 | val 0.64250
  Epoch 040 - train 0.58201 | val 0.64099
  Epoch 050 - train 0.60581 | val 0.63859
  Classification -> best τ=0.655 (val F1=0.4326)
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66063 | val 0.81334
  Epoch 020 - train 0.64210 | val 0.90857
  Epoch 021 - train 0.63212 | val 0.91473
  Classification -> best τ=0.485 (val F1=0.1656)
  Directional -> Accuracy: 0.4932, MCC: -0.0033, F1: 0.6476

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70191 | val 0.76452
  Epoch 020 - train 0.65908 | val 0.73749
  Epoch 021 - train 0.65948 | val 0.73556
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.66845 | val 0.70260
  Epoch 020 - train 0.63851 | val 0.70888
  Epoch 021 - train 0.67003 | val 0.70952
  Classification -> best τ=0.480 (val F1=0.1917)
  Directional -> Accuracy: 0.4146, MCC: -0.0392, F1: 0.0769

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68551 | val 0.76509
  Epoch 020 - train 0.63597 | val 0.82252
  Epoch 021 - train 0.62450 | val 0.82698
  Classification -> best τ=0.500 (val F1=0.1548)
  Directional -> Accuracy: 0.6522, MCC: 0.1667, F1: 0.2727

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.67774 | val 0.69482
  Epoch 020 - train 0.65827 | val 0.76651
  Epoch 026 - train 0.65218 | val 0.80702
  Classification -> best τ=0.465 (val F1=0.2925)
  Directional -> Accuracy: 0.4815, MCC: -0.1632, F1: 0.6316

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65401 | val 0.75238
  Epoch 020 - train 0.62877 | val 0.86600
  Epoch 024 - train 0.64106 | val 0.88906
  Classification -> best τ=0.560 (val F1=0.2933)
  Directional -> Accuracy: 0.5636, MCC: 0.1955, F1: 0.2500

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.67542 | val 0.69328
  Epoch 020 - train 0.67086 | val 0.69870
  Epoch 023 - train 0.66480 | val 0.70402
  Classification -> best τ=0.485 (val F1=0.1951)
  Directional -> Accuracy: 0.5962, MCC: 0.2817, F1: 0.7042

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67525 | val 0.83718
  Epoch 020 - train 0.65444 | val 1.01948

[I 2026-02-19 05:48:51,566] Trial 70 finished with value: 0.21196919783160206 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiLSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 4.5993945127379285e-05, 'weight_decay': 6.15425686439474e-07, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.8197094902151845, 'early_stopping_min_delta': 0.0017683534329748995}. Best is trial 53 with value: 0.2732635960250114.

  Epoch 021 - train 0.66196 | val 0.69487
  Classification -> best τ=0.490 (val F1=0.1166)
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.21196919783160206
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'stance_label', 'stance_score']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.60835 | val 1.52229
  Epoch 020 - train 0.48864 | val 3.51068
  Epoch 021 - train 0.45527 | val 2.76522
  Classification -> best τ=0.655 (val F1=0.2489)
  Directional -> Accuracy: 0.5270, MCC: -0.1495, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.55478 | val 1.61451
  Epoch 020 - train 0.41198 | val 2.91937
  Epoch 023 - train 0.33150 | val 2.40888
  Classification -> best τ=0.485 (val F1=0.1965)
  Directional -> Accuracy: 0.6512, MCC: 0.2235, F1: 0.7619

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.62106 | val 0.73869
  Epoch 020 - train 0.43371 | val 1.40549
  Epoch 026 - train 0.32233 | val 2.38211
  Classification -> best τ=0.745 (val F1=0.3592)
  Directional -> Accuracy: 0.4773, MCC: -0.0099, F1: 0.0800

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.61664 | val 1.75198
  Epoch 020 - train 0.44289 | val 1.09537
  Epoch 021 - train 0.47222 | val 1.38254
  Classification -> best τ=0.570 (val F1=0.1773)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50041 | val 2.07654
  Epoch 020 - train 0.25134 | val 2.40721
  Epoch 021 - train 0.26658 | val 2.24342
  Classification -> best τ=0.495 (val F1=0.4730)
  Directional -> Accuracy: 0.5625, MCC: 0.1241, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41029 | val 1.55308
  Epoch 020 - train 0.15894 | val 3.21399
  Epoch 021 - train 0.16616 | val 2.91664
  Classification -> best τ=0.475 (val F1=0.1899)
  Directional -> Accuracy: 0.4091, MCC: -0.1952, F1: 0.2778

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.57800 | val 1.32985
  Epoch 020 - train 0.25722 | val 2.64281
  Epoch 022 - train 0.21563 | val 3.17781
  Classification -> best τ=0.515 (val F1=0.2197)
  Directional -> Accuracy: 0.5152, MCC: 0.1207, F1: 0.5676

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.54768 | val 2.20922
  Epoch 020 - train 0.23557 | val 4.61309
  Epoch 022 - train 0.16406 | val 6.80088
  Classification -> best τ=0.325 (val F1=0.0976)
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.56768 | val 0.83319
  Epoch 020 - train 0.30741 | val 1.83155
  Epoch 024 - train 0.24732 | val 3.05187
  Classification -> best τ=0.495 (val F1=0.2817)
  Directional -> Accuracy: 0.5435, MCC: 0.1833, F1: 0.6182

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.55246 | val 12.65838
  Epoch 020 - train 0.37772 | val 2.26118
  Epoch 021 - train 0.39564 | val 1.88844
  Classification -> best τ=0.485 (val F1=0.2393)
  Directional -> Accuracy: 0.4030, MCC: -0.1092, F1: 0.5652

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.54077 | val 1.22937
  Epoch 020 - train 0.36063 | val 3.71145
  Epoch 021 - train 0.34836 | val 4.16208
  Classification -> best τ=0.580 (val F1=0.2851)
  Directional -> Accuracy: 0.6170, MCC: 0.2905, F1: 0.2500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.58361 | val 0.97055
  Epoch 020 - train 0.42101 | val 2.21415
  Epoch 021 - train 0.37244 | val 2.45448
  Classification -> best τ=0.510 (val F1=0.1273)
  Directional -> Accuracy: 0.6909, MCC: 0.3786, F1: 0.7213

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.50720 | val 4.81875
  Epoch 020 - train 0.26338 | val 1.01859
  Epoch 021 - train 0.24837 | val 1.43248
  Classification -> best τ=0.490 (val F1=0.2020)
  Directional -> Accuracy: 0.5000, MCC: -0.0334, F1: 0.2500

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57692 | val 0.75053
  Epoch 020 - train 0.38532 | val 1.78531
  Epoch 021 - train 0.41709 | val 1.96249
  Classification -> best τ=0.465 (val F1=0.1771)
  Directional -> Accuracy: 0.5690, MCC: 0.1360, F1: 0.5902

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.63490 | val 0.81129
  Epoch 020 - train 0.42051 | val 0.67373
  Epoch 030 - train 0.24232 | val 1.18374
  Epoch 040 - train 0.08372 | val 1.78599
  Classification -> best τ=0.255 (val F1=0.3398)
  Directional -> Accuracy: 0.5102, MCC: 0.2305, F1: 0.6471

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.62435 | val 0.71961
  Epoch 020 - train 0.41776 | val 2.03349
  Epoch 023 - train 0.36389 | val 2.43094
  Classification -> best τ=0.545 (val F1=0.2866)
  Directional -> Accuracy: 0.4627, MCC: -0.2635, F1: 0.6327

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.62966 | val 4.28406
  Epoch 020 - train 0.43644 | val 4.01873
  Epoch 021 - train 0.46748 | val 4.46854
  Classification -> best τ=0.420 (val F1=0.1360)
  Directional -> Accuracy: 0.6071, MCC: 0.0000, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.60760 | val 0.70844
  Epoch 020 - train 0.52983 | val 0.85895
  Epoch 025 - train 0.45623 | val 0.84724
  Classification -> best τ=0.570 (val F1=0.1829)
  Directional -> Accuracy: 0.4247, MCC: -0.1185, F1: 0.4167

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.54407 | val 1.31228
  Epoch 020 - train 0.29493 | val 5.20787
  Epoch 022 - train 0.27362 | val 6.51391
  Classification -> best τ=0.295 (val F1=0.3371)
  Directional -> Accuracy: 0.5806, MCC: 0.0000, F1: 0.7347

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.57688 | val 0.93203
  Epoch 020 - train 0.29017 | val 1.73847
  Epoch 021 - train 0.28411 | val 1.81608
  Classification -> best τ=0.435 (val F1=0.2565)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51040 | val 2.58582
  Epoch 020 - train 0.53761 | val 1.20189
  Epoch 029 - train 0.26150 | val 3.21011
  Classification -> best τ=0.575 (val F1=0.3633)
  Directional -> Accuracy: 0.4667, MCC: 0.2182, F1: 0.2000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.59134 | val 2.30826
  Epoch 020 - train 0.36934 | val 5.87323
  Epoch 021 - train 0.31488 | val 5.33850
  Classification -> best τ=0.560 (val F1=0.1899)
  Directional -> Accuracy: 0.5079, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.56921 | val 1.07277
  Epoch 020 - train 0.31347 | val 1.79169
  Epoch 021 - train 0.25769 | val 2.57061
  Classification -> best τ=0.455 (val F1=0.2138)
  Directional -> Accuracy: 0.5818, MCC: 0.0000, F1: 0.7356

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67404 | val 0.85719
  Epoch 020 - train 0.52436 | val 2.44423
  Epoch 022 - train 0.45378 | val 4.42360
  Classification -> best τ=0.490 (val F1=0.1343)
  Directional -> Accuracy: 0.5397, MCC: 0.0734, F1: 0.4912

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.50982 | val 2.54379
  Epoch 020 - train 0.24389 | val 3.57890
  Epoch 024 - train 0.17163 | val 4.41040
  Classification -> best τ=0.615 (val F1=0.4023)
  Directional -> Accuracy: 0.5094, MCC: 0.0917, F1: 0.3500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.54488 | val 0.93131
  Epoch 020 - train 0.40161 | val 0.97954
  Epoch 027 - train 0.10862 | val 2.50041
  Classification -> best τ=0.445 (val F1=0.3446)
  Directional -> Accuracy: 0.5238, MCC: 0.2810, F1: 0.6429

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49001 | val 0.89065
  Epoch 020 - train 0.22699 | val 1.25537
  Epoch 022 - train 0.16814 | val 1.27110
  Classification -> best τ=0.460 (val F1=0.0169)
  Directional -> Accuracy: 0.5625, MCC: 0.0810, F1: 0.6441

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.58552 | val 0.98240
  Epoch 020 - train 0.30748 | val 1.64519
  Epoch 022 - train 0.31733 | val 2.09569
  Classification -> best τ=0.460 (val F1=0.2569)
  Directional -> Accuracy: 0.4815, MCC: -0.0212, F1: 0.4400

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49471 | val 1.32759
  Epoch 020 - train 0.13335 | val 2.73999
  Epoch 024 - train 0.05632 | val 3.63057
  Classification -> best τ=0.355 (val F1=0.4472)
  Directional -> Accuracy: 0.4750, MCC: -0.0560, F1: 0.3226

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.51188 | val 0.81590
  Epoch 020 - train 0.15828 | val 1.92416
  Epoch 024 - train 0.10915 | val 1.61438
  Classification -> best τ=0.605 (val F1=0.2328)
  Directional -> Accuracy: 0.4750, MCC: 0.1448, F1: 0.0870

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53310 | val 0.96896
  Epoch 020 - train 0.23565 | val 1.87629
  Epoch 022 - train 0.21203 | val 2.53965
  Classification -> best τ=0.470 (val F1=0.3563)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.58900 | val 0.82195
  Epoch 020 - train 0.34337 | val 1.32670
  Epoch 021 - train 0.30493 | val 1.66464
  Classification -> best τ=0.460 (val F1=0.2565)
  Directional -> Accuracy: 0.5429, MCC: 0.1852, F1: 0.4074

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.53520 | val 1.21487
  Epoch 020 - train 0.32458 | val 1.47767
  Epoch 021 - train 0.29194 | val 1.43355
  Classification -> best τ=0.360 (val F1=0.2121)
  Directional -> Accuracy: 0.5918, MCC: 0.1736, F1: 0.5000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52894 | val 1.12314
  Epoch 020 - train 0.44785 | val 0.93606
  Epoch 029 - train 0.23566 | val 2.46403
  Classification -> best τ=0.400 (val F1=0.1657)
  Directional -> Accuracy: 0.4375, MCC: -0.0667, F1: 0.2800

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45379 | val 1.16986
  Epoch 020 - train 0.13319 | val 1.13308
  Epoch 021 - train 0.12241 | val 0.80675
  Classification -> best τ=0.475 (val F1=0.1863)
  Directional -> Accuracy: 0.5918, MCC: 0.1833, F1: 0.5833

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.54126 | val 1.61181
  Epoch 020 - train 0.40987 | val 2.17241
  Epoch 021 - train 0.39912 | val 2.41051
  Classification -> best τ=0.505 (val F1=0.2347)
  Directional -> Accuracy: 0.5185, MCC: -0.0166, F1: 0.2353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.59129 | val 0.81009
  Epoch 020 - train 0.25157 | val 1.64483
  Epoch 023 - train 0.18353 | val 1.48736
  Classification -> best τ=0.335 (val F1=0.2146)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49929 | val 1.45119
  Epoch 020 - train 0.17715 | val 1.16581
  Epoch 022 - train 0.13824 | val 1.27353
  Classification -> best τ=0.470 (val F1=0.0533)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.53750 | val 1.94702
  Epoch 020 - train 0.29321 | val 6.43556
  Epoch 021 - train 0.27685 | val 4.02053
  Classification -> best τ=0.310 (val F1=0.2028)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.48794 | val 1.53126
  Epoch 020 - train 0.23775 | val 1.93833
  Epoch 024 - train 0.04199 | val 1.87930
  Classification -> best τ=0.415 (val F1=0.1820)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40139 | val 0.91358
  Epoch 020 - train 0.07768 | val 1.40224
  Epoch 022 - train 0.05396 | val 2.12043
  Classification -> best τ=0.425 (val F1=0.3380)
  Directional -> Accuracy: 0.4615, MCC: -0.1236, F1: 0.5532

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51126 | val 1.34342
  Epoch 020 - train 0.15565 | val 1.33767
  Epoch 021 - train 0.13373 | val 1.81595
  Classification -> best τ=0.490 (val F1=0.1000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.54866 | val 0.70173
  Epoch 020 - train 0.50045 | val 0.77261
  Epoch 030 - train 0.15823 | val 1.39801
  Epoch 033 - train 0.17513 | val 2.53490
  Classification -> best τ=0.565 (val F1=0.3495)
  Directional -> Accuracy: 0.5283, MCC: 0.1028, F1: 0.4444

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.57984 | val 2.80383
  Epoch 020 - train 0.37077 | val 3.28031
  Epoch 021 - train 0.32636 | val 3.55603
  Classification -> best τ=0.555 (val F1=0.4171)
  Directional -> Accuracy: 0.5370, MCC: 0.0811, F1: 0.6154

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.56367 | val 1.46740
  Epoch 020 - train 0.30081 | val 1.84285
  Epoch 023 - train 0.37507 | val 1.64050
  Classification -> best τ=0.585 (val F1=0.2952)
  Directional -> Accuracy: 0.4706, MCC: -0.1442, F1: 0.6400

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.57029 | val 6.69881
  Epoch 020 - train 0.37117 | val 12.94156
  Epoch 022 - train 0.27793 | val 14.54344
  Classification -> best τ=0.470 (val F1=0.1413)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.61016 | val 0.75148
  Epoch 020 - train 0.40152 | val 1.01090
  Epoch 022 - train 0.36215 | val 0.83361
  Classification -> best τ=0.380 (val F1=0.3062)

[I 2026-02-19 06:00:48,034] Trial 71 finished with value: 0.24313914300030415 and parameters: {'feature_set': 'stance', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 0.008269710234373714, 'weight_decay': 1.3939930207718683e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.3286053978278611, 'early_stopping_min_delta': 0.0014881738419224868}. Best is trial 53 with value: 0.2732635960250114.

Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.64392 | val 0.74260
  Epoch 020 - train 0.61450 | val 1.33702
  Epoch 021 - train 0.57818 | val 1.90587
  Classification -> best τ=0.585 (val F1=0.2895)
  Directional -> Accuracy: 0.5676, MCC: 0.0821, F1: 0.2381

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.61843 | val 0.70413
  Epoch 020 - train 0.53712 | val 0.78980
  Epoch 022 - train 0.51576 | val 0.90164
  Classification -> best τ=0.455 (val F1=0.2419)
  Directional -> Accuracy: 0.5581, MCC: 0.1926, F1: 0.5366

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.66878 | val 0.75118
  Epoch 020 - train 0.58781 | val 1.31247
  Epoch 027 - train 0.51952 | val 2.55097
  Classification -> best τ=0.495 (val F1=0.3143)
  Directional -> Accuracy: 0.6136, MCC: 0.2275, F1: 0.6222

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.63967 | val 1.08960
  Epoch 020 - train 0.59599 | val 0.95799
  Epoch 028 - train 0.54190 | val 1.11344
  Classification -> best τ=0.515 (val F1=0.2457)
  Directional -> Accuracy: 0.4722, MCC: 0.1092, F1: 0.0500

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.63892 | val 0.73678
  Epoch 020 - train 0.55667 | val 0.99425
  Epoch 023 - train 0.52596 | val 0.95068
  Classification -> best τ=0.650 (val F1=0.4730)
  Directional -> Accuracy: 0.5833, MCC: 0.2471, F1: 0.4118

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.53997 | val 0.94684
  Epoch 020 - train 0.46755 | val 1.58713
  Epoch 023 - train 0.37660 | val 1.80834
  Classification -> best τ=0.475 (val F1=0.2130)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.65136 | val 0.74836
  Epoch 020 - train 0.57944 | val 0.94915
  Epoch 027 - train 0.46799 | val 1.11381
  Classification -> best τ=0.530 (val F1=0.2354)
  Directional -> Accuracy: 0.5303, MCC: 0.0673, F1: 0.4918

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.57638 | val 1.03439
  Epoch 020 - train 0.46170 | val 1.87937
  Epoch 025 - train 0.33387 | val 3.18016
  Classification -> best τ=0.480 (val F1=0.1741)
  Directional -> Accuracy: 0.5385, MCC: 0.0366, F1: 0.4000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.61145 | val 0.78606
  Epoch 020 - train 0.59199 | val 0.80321
  Epoch 026 - train 0.51976 | val 0.87198
  Classification -> best τ=0.380 (val F1=0.2817)
  Directional -> Accuracy: 0.6304, MCC: 0.2440, F1: 0.5641

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.65014 | val 0.71874
  Epoch 020 - train 0.54675 | val 0.76161
  Epoch 025 - train 0.49428 | val 0.77318
  Classification -> best τ=0.580 (val F1=0.2269)
  Directional -> Accuracy: 0.4925, MCC: -0.0226, F1: 0.4333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.62274 | val 1.83336
  Epoch 020 - train 0.61418 | val 1.85985
  Epoch 025 - train 0.53679 | val 2.40778
  Classification -> best τ=0.630 (val F1=0.4584)
  Directional -> Accuracy: 0.5745, MCC: 0.1192, F1: 0.4444

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.63436 | val 1.32909
  Epoch 020 - train 0.51658 | val 2.57153
  Epoch 022 - train 0.48615 | val 2.30472
  Classification -> best τ=0.515 (val F1=0.2750)
  Directional -> Accuracy: 0.6909, MCC: 0.3925, F1: 0.6792

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58944 | val 1.24529
  Epoch 020 - train 0.50446 | val 0.91276
  Epoch 022 - train 0.45926 | val 0.95435
  Classification -> best τ=0.530 (val F1=0.1966)
  Directional -> Accuracy: 0.4583, MCC: -0.1402, F1: 0.1875

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.66336 | val 0.78161
  Epoch 020 - train 0.56125 | val 0.84589
  Epoch 021 - train 0.55261 | val 0.82831
  Classification -> best τ=0.430 (val F1=0.2193)
  Directional -> Accuracy: 0.5345, MCC: 0.0598, F1: 0.6301

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.64513 | val 1.09009
  Epoch 020 - train 0.57873 | val 0.67028
  Epoch 030 - train 0.39894 | val 1.13431
  Epoch 034 - train 0.46229 | val 0.87297
  Classification -> best τ=0.470 (val F1=0.4423)
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.68308 | val 0.72027
  Epoch 020 - train 0.58592 | val 1.16729
  Epoch 021 - train 0.58387 | val 1.55496
  Classification -> best τ=0.410 (val F1=0.2866)
  Directional -> Accuracy: 0.5821, MCC: 0.2333, F1: 0.7200

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65732 | val 0.76318
  Epoch 020 - train 0.58354 | val 0.70599
  Epoch 030 - train 0.50627 | val 1.02926
  Epoch 034 - train 0.46094 | val 1.04406
  Classification -> best τ=0.530 (val F1=0.1313)
  Directional -> Accuracy: 0.4643, MCC: 0.0636, F1: 0.3478

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67031 | val 0.74193
  Epoch 020 - train 0.59768 | val 0.75267
  Epoch 022 - train 0.61935 | val 0.71492
  Classification -> best τ=0.580 (val F1=0.2127)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64872 | val 1.03487
  Epoch 020 - train 0.61081 | val 1.00539
  Epoch 022 - train 0.58887 | val 1.39474
  Classification -> best τ=0.385 (val F1=0.2483)
  Directional -> Accuracy: 0.5323, MCC: 0.2236, F1: 0.3830

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.62329 | val 0.75261
  Epoch 020 - train 0.55570 | val 1.09858
  Epoch 022 - train 0.54760 | val 1.10382
  Classification -> best τ=0.460 (val F1=0.3169)
  Directional -> Accuracy: 0.4583, MCC: 0.1061, F1: 0.0488

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.64953 | val 0.69731
  Epoch 020 - train 0.59942 | val 1.01714
  Epoch 030 - train 0.52485 | val 1.05239
  Epoch 036 - train 0.54269 | val 1.26506
  Classification -> best τ=0.490 (val F1=0.3825)
  Directional -> Accuracy: 0.3556, MCC: -0.2464, F1: 0.3256

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.67086 | val 1.41688
  Epoch 020 - train 0.59413 | val 3.42717
  Epoch 024 - train 0.57093 | val 2.97300
  Classification -> best τ=0.425 (val F1=0.2694)
  Directional -> Accuracy: 0.4286, MCC: -0.1775, F1: 0.2174

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.64865 | val 0.80393
  Epoch 020 - train 0.51341 | val 1.16156
  Epoch 021 - train 0.51818 | val 1.47407
  Classification -> best τ=0.575 (val F1=0.1665)
  Directional -> Accuracy: 0.4727, MCC: 0.2036, F1: 0.1714

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.63421 | val 0.73426
  Epoch 020 - train 0.61111 | val 0.69898
  Epoch 021 - train 0.60374 | val 0.70347
  Classification -> best τ=0.420 (val F1=0.1633)
  Directional -> Accuracy: 0.4444, MCC: -0.1019, F1: 0.5570

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.63755 | val 0.76517
  Epoch 020 - train 0.51225 | val 1.41767
  Epoch 024 - train 0.44597 | val 1.84504
  Classification -> best τ=0.365 (val F1=0.4285)
  Directional -> Accuracy: 0.5660, MCC: 0.2204, F1: 0.4390

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.56118 | val 0.89109
  Epoch 020 - train 0.52208 | val 1.21903
  Epoch 022 - train 0.44751 | val 1.10507
  Classification -> best τ=0.605 (val F1=0.1612)
  Directional -> Accuracy: 0.4048, MCC: -0.1803, F1: 0.5763

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.62414 | val 0.87436
  Epoch 020 - train 0.58720 | val 1.12430
  Epoch 025 - train 0.43090 | val 1.36520
  Classification -> best τ=0.620 (val F1=0.1456)
  Directional -> Accuracy: 0.4167, MCC: -0.2182, F1: 0.5172

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.66796 | val 0.76123
  Epoch 020 - train 0.54366 | val 0.92906
  Epoch 023 - train 0.53225 | val 0.88169
  Classification -> best τ=0.370 (val F1=0.2932)
  Directional -> Accuracy: 0.5370, MCC: 0.2626, F1: 0.2424

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.66051 | val 1.88701
  Epoch 020 - train 0.58893 | val 1.63855
  Epoch 021 - train 0.53963 | val 1.90055
  Classification -> best τ=0.490 (val F1=0.2000)
  Directional -> Accuracy: 0.5500, MCC: 0.1048, F1: 0.6087

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.62450 | val 0.63838
  Epoch 020 - train 0.55812 | val 0.97829
  Epoch 029 - train 0.44713 | val 0.76958
  Classification -> best τ=0.685 (val F1=0.2328)
  Directional -> Accuracy: 0.5750, MCC: 0.1985, F1: 0.5143

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.60903 | val 0.73256
  Epoch 020 - train 0.58336 | val 0.79507
  Epoch 030 - train 0.40821 | val 1.55035
  Epoch 036 - train 0.35682 | val 1.82368
  Classification -> best τ=0.440 (val F1=0.3415)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.64449 | val 0.71039
  Epoch 020 - train 0.62683 | val 0.70850
  Epoch 023 - train 0.61317 | val 0.74149
  Classification -> best τ=0.485 (val F1=0.2885)
  Directional -> Accuracy: 0.5143, MCC: 0.1300, F1: 0.3462

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.63809 | val 0.84578
  Epoch 020 - train 0.56893 | val 0.90841
  Epoch 022 - train 0.52816 | val 0.92905
  Classification -> best τ=0.520 (val F1=0.3419)
  Directional -> Accuracy: 0.5510, MCC: 0.2804, F1: 0.6765

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59913 | val 0.87427
  Epoch 020 - train 0.56074 | val 1.02081
  Epoch 022 - train 0.55302 | val 1.06278
  Classification -> best τ=0.700 (val F1=0.2288)
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.55320 | val 2.18674
  Epoch 020 - train 0.48569 | val 2.28034
  Epoch 021 - train 0.42664 | val 2.24904
  Classification -> best τ=0.580 (val F1=0.2469)
  Directional -> Accuracy: 0.5102, MCC: 0.0042, F1: 0.0769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.62524 | val 0.84809
  Epoch 020 - train 0.53093 | val 1.18103
  Epoch 021 - train 0.49573 | val 1.22823
  Classification -> best τ=0.610 (val F1=0.2277)
  Directional -> Accuracy: 0.5926, MCC: 0.1759, F1: 0.3889

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.60425 | val 0.68005
  Epoch 020 - train 0.36583 | val 0.95758
  Epoch 021 - train 0.35024 | val 0.91594
  Classification -> best τ=0.345 (val F1=0.2841)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.55605 | val 0.78507
  Epoch 020 - train 0.32351 | val 1.47542
  Epoch 021 - train 0.33070 | val 1.59595
  Classification -> best τ=0.480 (val F1=0.2665)
  Directional -> Accuracy: 0.4000, MCC: 0.1000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.63317 | val 1.00812
  Epoch 020 - train 0.54929 | val 2.33166
  Epoch 026 - train 0.49280 | val 3.40647
  Classification -> best τ=0.510 (val F1=0.2872)
  Directional -> Accuracy: 0.5417, MCC: 0.2085, F1: 0.6857

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56026 | val 0.71343
  Epoch 020 - train 0.39643 | val 0.81706
  Epoch 025 - train 0.40081 | val 0.97699
  Classification -> best τ=0.515 (val F1=0.2212)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.54846 | val 0.91944
  Epoch 020 - train 0.30097 | val 0.67021
  Epoch 030 - train 0.11004 | val 1.33643
  Epoch 039 - train 0.02355 | val 0.79754
  Classification -> best τ=0.380 (val F1=0.4966)
  Directional -> Accuracy: 0.3590, MCC: -0.2735, F1: 0.3902

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.68444 | val 1.11570
  Epoch 020 - train 0.50532 | val 1.12407
  Epoch 021 - train 0.46459 | val 1.24382
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.65913 | val 0.66381
  Epoch 020 - train 0.58736 | val 1.06483
  Epoch 023 - train 0.59479 | val 0.97472
  Classification -> best τ=0.640 (val F1=0.2619)
  Directional -> Accuracy: 0.5283, MCC: 0.2054, F1: 0.2857

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.61655 | val 1.44270
  Epoch 020 - train 0.56455 | val 2.83488
  Epoch 021 - train 0.55262 | val 3.99059
  Classification -> best τ=0.475 (val F1=0.4171)
  Directional -> Accuracy: 0.5185, MCC: 0.0371, F1: 0.5000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.64276 | val 0.98111
  Epoch 020 - train 0.57720 | val 1.85471
  Epoch 030 - train 0.46101 | val 2.12250
  Epoch 033 - train 0.48752 | val 2.13097
  Classification -> best τ=0.400 (val F1=0.2892)
  Directional -> Accuracy: 0.5294, MCC: 0.1146, F1: 0.6571

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.62136 | val 1.97289
  Epoch 020 - train 0.58310 | val 3.69611
  Epoch 022 - train 0.55561 | val 3.48559
  Classification -> best τ=0.595 (val F1=0.2905)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.67928 | val 0.69027
  Epoch 020 - train 0.63140 | val 0.92338
  Epoch 024 - train 0.64345 | val 0.72127

[I 2026-02-19 06:13:20,864] Trial 72 finished with value: 0.27004976522462126 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.0, 'batch_size': 16, 'learning_rate': 0.004591891309522184, 'weight_decay': 3.1874304018930114e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.5122580604015798, 'early_stopping_min_delta': 0.0010423969269114772}. Best is trial 53 with value: 0.2732635960250114.

  Classification -> best τ=0.420 (val F1=0.2769)
  Directional -> Accuracy: 0.4828, MCC: 0.0274, F1: 0.6154

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27004976522462126
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.72413 | val 0.69052
  Epoch 020 - train 0.67435 | val 0.86643
  Epoch 028 - train 0.67746 | val 0.93273
  Classification -> best τ=0.510 (val F1=0.2489)
  Directional -> Accuracy: 0.5405, MCC: -0.0249, F1: 0.1053

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.71242 | val 0.76096
  Epoch 020 - train 0.65559 | val 0.66519
  Epoch 030 - train 0.57887 | val 0.66663
  Epoch 040 - train 0.64433 | val 0.72311
  Epoch 048 - train 0.60901 | val 0.69243
  Classification -> best τ=0.420 (val F1=0.3943)
  Directional -> Accuracy: 0.4884, MCC: 0.1074, F1: 0.3889

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70637 | val 0.72404
  Epoch 020 - train 0.65241 | val 0.73369
  Epoch 026 - train 0.62609 | val 0.75811
  Classification -> best τ=0.625 (val F1=0.4388)
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70838 | val 0.85614
  Epoch 020 - train 0.69731 | val 0.76592
  Epoch 030 - train 0.67375 | val 0.85453
  Epoch 034 - train 0.65979 | val 0.93775
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.71225 | val 0.77204
  Epoch 020 - train 0.60718 | val 0.71802
  Epoch 023 - train 0.60737 | val 0.86149
  Classification -> best τ=0.495 (val F1=0.4568)
  Directional -> Accuracy: 0.7708, MCC: 0.5569, F1: 0.7556

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.67222 | val 0.79715
  Epoch 020 - train 0.68645 | val 0.77825
  Epoch 022 - train 0.62395 | val 0.80503
  Classification -> best τ=0.440 (val F1=0.2392)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70826 | val 0.68978
  Epoch 020 - train 0.66154 | val 0.72512
  Epoch 022 - train 0.69337 | val 0.75172
  Classification -> best τ=0.415 (val F1=0.1678)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66007 | val 0.85650
  Epoch 020 - train 0.61068 | val 1.16759
  Epoch 027 - train 0.61042 | val 1.43964
  Classification -> best τ=0.485 (val F1=0.0976)
  Directional -> Accuracy: 0.5897, MCC: 0.2266, F1: 0.6190

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.69487 | val 0.71366
  Epoch 020 - train 0.70815 | val 0.72924
  Epoch 030 - train 0.61020 | val 0.63624
  Epoch 040 - train 0.63470 | val 0.70885
  Epoch 042 - train 0.65579 | val 0.60593
  Classification -> best τ=0.505 (val F1=0.4781)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.68104 | val 1.09257
  Epoch 020 - train 0.64061 | val 1.27887
  Epoch 024 - train 0.63546 | val 1.21208
  Classification -> best τ=0.510 (val F1=0.3475)
  Directional -> Accuracy: 0.4179, MCC: -0.0292, F1: 0.5806

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65592 | val 0.66493
  Epoch 020 - train 0.68703 | val 1.49278
  Epoch 030 - train 0.62428 | val 2.65626
  Classification -> best τ=0.530 (val F1=0.4013)
  Directional -> Accuracy: 0.5532, MCC: 0.0409, F1: 0.2222

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67268 | val 1.07657
  Epoch 020 - train 0.67577 | val 1.64314
  Epoch 021 - train 0.63257 | val 1.69546
  Classification -> best τ=0.480 (val F1=0.1633)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68245 | val 0.82629
  Epoch 020 - train 0.58380 | val 0.75209
  Epoch 021 - train 0.60929 | val 0.82986
  Classification -> best τ=0.515 (val F1=0.3099)
  Directional -> Accuracy: 0.5000, MCC: 0.0754, F1: 0.6471

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.70344 | val 0.65856
  Epoch 020 - train 0.69235 | val 0.67102
  Epoch 030 - train 0.61028 | val 0.88979
  Epoch 040 - train 0.56348 | val 1.00925
  Epoch 045 - train 0.54510 | val 1.52223
  Classification -> best τ=0.325 (val F1=0.2811)
  Directional -> Accuracy: 0.5172, MCC: 0.0270, F1: 0.5758

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69870 | val 0.69322
  Epoch 020 - train 0.65405 | val 0.69489
  Epoch 030 - train 0.61335 | val 0.75205
  Epoch 040 - train 0.60750 | val 0.81605
  Epoch 042 - train 0.55888 | val 0.83321
  Classification -> best τ=0.500 (val F1=0.2368)
  Directional -> Accuracy: 0.5102, MCC: -0.1862, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.71289 | val 0.70196
  Epoch 020 - train 0.67786 | val 0.75723
  Epoch 021 - train 0.68118 | val 0.77437
  Classification -> best τ=0.465 (val F1=0.3288)
  Directional -> Accuracy: 0.5672, MCC: 0.1452, F1: 0.7071

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68662 | val 0.89179
  Epoch 020 - train 0.66557 | val 1.03469
  Epoch 021 - train 0.66557 | val 1.02365
  Classification -> best τ=0.570 (val F1=0.1083)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68050 | val 0.73293
  Epoch 020 - train 0.68646 | val 0.76108
  Epoch 024 - train 0.70373 | val 0.78610
  Classification -> best τ=0.620 (val F1=0.1829)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66595 | val 0.95159
  Epoch 020 - train 0.64139 | val 0.86225
  Epoch 022 - train 0.63725 | val 0.93385
  Classification -> best τ=0.425 (val F1=0.3371)
  Directional -> Accuracy: 0.5323, MCC: 0.2236, F1: 0.3830

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70496 | val 0.69888
  Epoch 020 - train 0.64214 | val 0.72250
  Epoch 022 - train 0.64543 | val 0.69621
  Classification -> best τ=0.540 (val F1=0.2582)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.70428 | val 0.91177
  Epoch 020 - train 0.65570 | val 0.72477
  Epoch 021 - train 0.65569 | val 0.74184
  Classification -> best τ=0.530 (val F1=0.2197)
  Directional -> Accuracy: 0.5778, MCC: -0.0364, F1: 0.7246

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68561 | val 0.78115
  Epoch 020 - train 0.68361 | val 0.78548
  Epoch 021 - train 0.68226 | val 0.75016
  Classification -> best τ=0.560 (val F1=0.2345)
  Directional -> Accuracy: 0.5079, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70440 | val 0.75280
  Epoch 020 - train 0.69488 | val 0.74432
  Epoch 026 - train 0.65483 | val 0.82974
  Classification -> best τ=0.545 (val F1=0.3086)
  Directional -> Accuracy: 0.5818, MCC: 0.1817, F1: 0.5965

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.71535 | val 0.69236
  Epoch 020 - train 0.68440 | val 0.70369
  Epoch 027 - train 0.66061 | val 0.69427
  Classification -> best τ=0.485 (val F1=0.1375)
  Directional -> Accuracy: 0.5714, MCC: 0.1492, F1: 0.5846

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66041 | val 0.64556
  Epoch 020 - train 0.66965 | val 0.72291
  Epoch 030 - train 0.64123 | val 1.07511
  Epoch 033 - train 0.57167 | val 1.26211
  Classification -> best τ=0.485 (val F1=0.4609)
  Directional -> Accuracy: 0.5283, MCC: 0.1718, F1: 0.3243

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.75707 | val 1.16846
  Epoch 020 - train 0.68720 | val 0.77473
  Epoch 024 - train 0.65831 | val 0.71357
  Classification -> best τ=0.580 (val F1=0.1364)
  Directional -> Accuracy: 0.5476, MCC: 0.2178, F1: 0.6275

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.65659 | val 0.68599
  Epoch 020 - train 0.71613 | val 0.71492
  Epoch 030 - train 0.61516 | val 0.70505
  Epoch 034 - train 0.59544 | val 0.69774
  Classification -> best τ=0.550 (val F1=0.0284)
  Directional -> Accuracy: 0.4792, MCC: -0.0792, F1: 0.5614

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70932 | val 0.70654
  Epoch 020 - train 0.64762 | val 0.83579
  Epoch 024 - train 0.66275 | val 0.92190
  Classification -> best τ=0.345 (val F1=0.2649)
  Directional -> Accuracy: 0.5741, MCC: 0.2103, F1: 0.4651

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.69897 | val 1.05570
  Epoch 020 - train 0.65610 | val 1.02320
  Epoch 022 - train 0.63299 | val 1.09736
  Classification -> best τ=0.595 (val F1=0.3333)
  Directional -> Accuracy: 0.5250, MCC: 0.0516, F1: 0.4571

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68122 | val 0.64285
  Epoch 020 - train 0.57227 | val 0.74330
  Epoch 030 - train 0.59510 | val 0.68104
  Epoch 034 - train 0.58074 | val 0.66381
  Classification -> best τ=0.630 (val F1=0.2736)
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68071 | val 0.74823
  Epoch 020 - train 0.64886 | val 0.72804
  Epoch 024 - train 0.63870 | val 0.67475
  Classification -> best τ=0.380 (val F1=0.3578)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69063 | val 0.72621
  Epoch 020 - train 0.66313 | val 0.78758
  Epoch 022 - train 0.66482 | val 0.80092
  Classification -> best τ=0.380 (val F1=0.3131)
  Directional -> Accuracy: 0.5143, MCC: 0.0816, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.72503 | val 0.81616
  Epoch 020 - train 0.66009 | val 0.83153
  Epoch 021 - train 0.66834 | val 0.87622
  Classification -> best τ=0.445 (val F1=0.2576)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66525 | val 0.75229
  Epoch 020 - train 0.64401 | val 0.76330
  Epoch 021 - train 0.62557 | val 0.80858
  Classification -> best τ=0.325 (val F1=0.3921)
  Directional -> Accuracy: 0.6094, MCC: 0.1812, F1: 0.7059

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.69564 | val 0.89194
  Epoch 020 - train 0.60849 | val 0.95324
  Epoch 030 - train 0.59131 | val 1.65146
  Epoch 031 - train 0.58667 | val 1.69417
  Classification -> best τ=0.715 (val F1=0.2817)
  Directional -> Accuracy: 0.4898, MCC: -0.0799, F1: 0.0741

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70885 | val 0.93507
  Epoch 020 - train 0.62233 | val 0.99894
  Epoch 022 - train 0.65386 | val 1.20378
  Classification -> best τ=0.405 (val F1=0.2004)
  Directional -> Accuracy: 0.5000, MCC: 0.0331, F1: 0.5714

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.69695 | val 0.88075
  Epoch 020 - train 0.63643 | val 1.07662
  Epoch 023 - train 0.61408 | val 1.06972
  Classification -> best τ=0.430 (val F1=0.2734)
  Directional -> Accuracy: 0.4318, MCC: 0.0886, F1: 0.1935

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.73951 | val 0.78360
  Epoch 020 - train 0.68559 | val 0.81496
  Epoch 027 - train 0.59567 | val 0.78862
  Classification -> best τ=0.385 (val F1=0.4973)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66844 | val 0.93068
  Epoch 020 - train 0.62521 | val 0.91303
  Epoch 021 - train 0.60355 | val 1.04704
  Classification -> best τ=0.350 (val F1=0.3184)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.65301 | val 0.70326
  Epoch 020 - train 0.66375 | val 0.68627
  Epoch 028 - train 0.65455 | val 0.70940
  Classification -> best τ=0.410 (val F1=0.3177)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.72284 | val 0.71732
  Epoch 020 - train 0.64039 | val 0.69574
  Epoch 022 - train 0.59826 | val 0.75811
  Classification -> best τ=0.480 (val F1=0.3477)
  Directional -> Accuracy: 0.5897, MCC: 0.1365, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69824 | val 1.00363
  Epoch 020 - train 0.63056 | val 1.03724
  Epoch 021 - train 0.57840 | val 1.07800
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.68795 | val 0.73152
  Epoch 020 - train 0.66329 | val 0.69854
  Epoch 030 - train 0.62712 | val 0.66105
  Epoch 040 - train 0.62444 | val 0.68163
  Epoch 050 - train 0.62989 | val 0.67087
  Classification -> best τ=0.575 (val F1=0.2570)
  Directional -> Accuracy: 0.5283, MCC: 0.1718, F1: 0.3243

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.69326 | val 1.23696
  Epoch 020 - train 0.64277 | val 2.39754
  Epoch 021 - train 0.66289 | val 2.56637
  Classification -> best τ=0.640 (val F1=0.3398)
  Directional -> Accuracy: 0.5556, MCC: 0.1114, F1: 0.5385

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70579 | val 0.71525
  Epoch 020 - train 0.66369 | val 0.68721
  Epoch 030 - train 0.61969 | val 0.70785
  Epoch 040 - train 0.61078 | val 0.75411
  Epoch 050 - train 0.50951 | val 0.79845
  Classification -> best τ=0.875 (val F1=0.2758)

[I 2026-02-19 06:27:18,254] Trial 73 finished with value: 0.27358491829294407 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.003596094231753264, 'weight_decay': 3.498850224936222e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.5134234160712188, 'early_stopping_min_delta': 0.0003456626225366462}. Best is trial 73 with value: 0.27358491829294407.

  Classification -> best τ=0.475 (val F1=0.2969)
  Directional -> Accuracy: 0.6034, MCC: 0.2060, F1: 0.4103

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.27358491829294407
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68256 | val 0.79165
  Epoch 020 - train 0.65846 | val 1.08494
  Epoch 024 - train 0.65600 | val 1.20606
  Classification -> best τ=0.575 (val F1=0.2489)
  Directional -> Accuracy: 0.5405, MCC: -0.0113, F1: 0.1500

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.73031 | val 0.70012
  Epoch 020 - train 0.71756 | val 0.70917
  Epoch 024 - train 0.70996 | val 0.76859
  Classification -> best τ=0.535 (val F1=0.3970)
  Directional -> Accuracy: 0.5349, MCC: 0.1558, F1: 0.5000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.75986 | val 0.72525
  Epoch 020 - train 0.63740 | val 0.73427
  Epoch 023 - train 0.67547 | val 0.79301
  Classification -> best τ=0.510 (val F1=0.2733)
  Directional -> Accuracy: 0.5227, MCC: 0.0498, F1: 0.5116

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70527 | val 0.80800
  Epoch 020 - train 0.68113 | val 1.23447
  Epoch 021 - train 0.67127 | val 1.27851
  Classification -> best τ=0.530 (val F1=0.1309)
  Directional -> Accuracy: 0.5139, MCC: 0.0424, F1: 0.4928

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69223 | val 0.66603
  Epoch 020 - train 0.66294 | val 0.66257
  Epoch 028 - train 0.62102 | val 0.70821
  Classification -> best τ=0.420 (val F1=0.4965)
  Directional -> Accuracy: 0.7292, MCC: 0.4723, F1: 0.7111

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60537 | val 0.96248
  Epoch 020 - train 0.52648 | val 1.64260
  Epoch 021 - train 0.56403 | val 1.91865
  Classification -> best τ=0.475 (val F1=0.0572)
  Directional -> Accuracy: 0.5682, MCC: 0.1690, F1: 0.3871

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.73720 | val 0.74592
  Epoch 020 - train 0.69771 | val 0.69076
  Epoch 030 - train 0.68202 | val 0.71804
  Epoch 037 - train 0.65142 | val 0.72486
  Classification -> best τ=0.325 (val F1=0.2715)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.71669 | val 1.81602
  Epoch 020 - train 0.72336 | val 1.22356
  Epoch 021 - train 0.61202 | val 1.18480
  Classification -> best τ=0.505 (val F1=0.2582)
  Directional -> Accuracy: 0.5897, MCC: 0.1463, F1: 0.4667

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.64521 | val 0.82320
  Epoch 020 - train 0.62040 | val 0.79558
  Epoch 030 - train 0.60379 | val 0.89419
  Epoch 034 - train 0.54497 | val 0.97304
  Classification -> best τ=0.680 (val F1=0.4390)
  Directional -> Accuracy: 0.6304, MCC: 0.3012, F1: 0.2609

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.74147 | val 0.87499
  Epoch 020 - train 0.67353 | val 0.84206
  Epoch 021 - train 0.67484 | val 1.19626
  Classification -> best τ=0.455 (val F1=0.3540)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66508 | val 1.86295
  Epoch 020 - train 0.66160 | val 2.05470
  Epoch 021 - train 0.62420 | val 1.50579
  Classification -> best τ=0.515 (val F1=0.3506)
  Directional -> Accuracy: 0.4468, MCC: -0.0226, F1: 0.6061

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71250 | val 0.84970
  Epoch 020 - train 0.70284 | val 0.92188
  Epoch 021 - train 0.66586 | val 0.94856
  Classification -> best τ=0.460 (val F1=0.0523)
  Directional -> Accuracy: 0.6364, MCC: 0.3090, F1: 0.7297

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.71148 | val 0.76435
  Epoch 020 - train 0.55612 | val 0.81485
  Epoch 024 - train 0.53984 | val 0.78408
  Classification -> best τ=0.690 (val F1=0.2020)
  Directional -> Accuracy: 0.5625, MCC: 0.1180, F1: 0.4615

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67997 | val 0.90881
  Epoch 020 - train 0.65757 | val 0.77188
  Epoch 021 - train 0.69673 | val 0.79583
  Classification -> best τ=0.470 (val F1=0.2319)
  Directional -> Accuracy: 0.5172, MCC: 0.0250, F1: 0.5882

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.73013 | val 0.83031
  Epoch 020 - train 0.64597 | val 0.92887
  Epoch 022 - train 0.63712 | val 0.95737
  Classification -> best τ=0.455 (val F1=0.2630)
  Directional -> Accuracy: 0.5306, MCC: 0.0152, F1: 0.3429

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.71306 | val 0.71307
  Epoch 020 - train 0.64307 | val 1.03016
  Epoch 022 - train 0.66432 | val 1.07111
  Classification -> best τ=0.410 (val F1=0.2837)
  Directional -> Accuracy: 0.6418, MCC: 0.2844, F1: 0.7209

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71044 | val 0.75397
  Epoch 020 - train 0.68351 | val 0.82429
  Epoch 021 - train 0.67254 | val 0.86092
  Classification -> best τ=0.570 (val F1=0.0566)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69869 | val 0.68351
  Epoch 020 - train 0.64553 | val 0.75277
  Epoch 030 - train 0.65988 | val 0.74752
  Epoch 031 - train 0.65985 | val 0.74215
  Classification -> best τ=0.565 (val F1=0.2216)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.70664 | val 0.68900
  Epoch 020 - train 0.67780 | val 0.82760
  Epoch 027 - train 0.65226 | val 0.85206
  Classification -> best τ=0.325 (val F1=0.2799)
  Directional -> Accuracy: 0.5161, MCC: 0.1949, F1: 0.3478

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.72244 | val 0.67882
  Epoch 020 - train 0.66970 | val 0.67351
  Epoch 030 - train 0.61893 | val 0.70478
  Epoch 031 - train 0.60953 | val 0.71751
  Classification -> best τ=0.475 (val F1=0.3162)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67752 | val 0.67998
  Epoch 020 - train 0.65704 | val 0.71573
  Epoch 026 - train 0.60908 | val 0.71086
  Classification -> best τ=0.425 (val F1=0.3492)
  Directional -> Accuracy: 0.4222, MCC: -0.1826, F1: 0.5000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.69167 | val 0.76747
  Epoch 020 - train 0.67454 | val 0.74566
  Epoch 021 - train 0.68409 | val 0.77036
  Classification -> best τ=0.520 (val F1=0.2697)
  Directional -> Accuracy: 0.5397, MCC: 0.0822, F1: 0.3830

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.73211 | val 0.69751
  Epoch 020 - train 0.70083 | val 0.74565
  Epoch 023 - train 0.68290 | val 0.73456
  Classification -> best τ=0.450 (val F1=0.3121)
  Directional -> Accuracy: 0.4182, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.71307 | val 0.89468
  Epoch 020 - train 0.68782 | val 0.74180
  Epoch 021 - train 0.67472 | val 0.73964
  Classification -> best τ=0.470 (val F1=0.1567)
  Directional -> Accuracy: 0.5714, MCC: 0.2039, F1: 0.6582

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.72085 | val 0.63400
  Epoch 020 - train 0.64480 | val 0.73781
  Epoch 029 - train 0.61762 | val 0.96870
  Classification -> best τ=0.420 (val F1=0.4736)
  Directional -> Accuracy: 0.5094, MCC: 0.1310, F1: 0.2778

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70724 | val 0.94087
  Epoch 020 - train 0.61324 | val 0.87947
  Epoch 022 - train 0.61245 | val 0.88255
  Classification -> best τ=0.490 (val F1=0.3327)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.72593 | val 0.79217
  Epoch 020 - train 0.66720 | val 0.71386
  Epoch 022 - train 0.66996 | val 0.71035
  Classification -> best τ=0.480 (val F1=0.0903)
  Directional -> Accuracy: 0.5417, MCC: 0.0845, F1: 0.5769

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69687 | val 0.79039
  Epoch 020 - train 0.63833 | val 0.78688
  Epoch 021 - train 0.61510 | val 0.75958
  Classification -> best τ=0.535 (val F1=0.1657)
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.60927 | val 1.15141
  Epoch 020 - train 0.66446 | val 0.79063
  Epoch 027 - train 0.62430 | val 0.93656
  Classification -> best τ=0.615 (val F1=0.3333)
  Directional -> Accuracy: 0.5500, MCC: 0.1250, F1: 0.3571

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72315 | val 0.74183
  Epoch 020 - train 0.72718 | val 0.68276
  Epoch 030 - train 0.65682 | val 0.65064
  Epoch 040 - train 0.60694 | val 0.65509
  Epoch 042 - train 0.62116 | val 0.67891
  Classification -> best τ=0.650 (val F1=0.1300)
  Directional -> Accuracy: 0.5250, MCC: -0.0198, F1: 0.6545

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69068 | val 0.72902
  Epoch 020 - train 0.67784 | val 0.79582
  Epoch 025 - train 0.62116 | val 0.74490
  Classification -> best τ=0.350 (val F1=0.3703)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68724 | val 0.73276
  Epoch 020 - train 0.65055 | val 0.75934
  Epoch 022 - train 0.66587 | val 0.80675
  Classification -> best τ=0.340 (val F1=0.2620)
  Directional -> Accuracy: 0.5286, MCC: 0.1429, F1: 0.4000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68705 | val 0.84909
  Epoch 020 - train 0.69070 | val 0.88657
  Epoch 021 - train 0.67919 | val 0.86986
  Classification -> best τ=0.495 (val F1=0.2843)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.66616 | val 0.94841
  Epoch 020 - train 0.57821 | val 0.92166
  Epoch 024 - train 0.60602 | val 1.05026
  Classification -> best τ=0.265 (val F1=0.4116)
  Directional -> Accuracy: 0.5938, MCC: 0.1486, F1: 0.7234

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.66810 | val 1.16176
  Epoch 020 - train 0.62715 | val 1.37198
  Epoch 022 - train 0.57719 | val 1.40642
  Classification -> best τ=0.530 (val F1=0.3837)
  Directional -> Accuracy: 0.5918, MCC: 0.1936, F1: 0.4737

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.69900 | val 1.07030
  Epoch 020 - train 0.65025 | val 0.80689
  Epoch 022 - train 0.63076 | val 0.75789
  Classification -> best τ=0.405 (val F1=0.2766)
  Directional -> Accuracy: 0.5556, MCC: 0.1312, F1: 0.5862

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.63017 | val 1.64730
  Epoch 020 - train 0.52217 | val 3.35406
  Epoch 021 - train 0.53282 | val 3.53459
  Classification -> best τ=0.460 (val F1=0.2841)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.70669 | val 0.70511
  Epoch 020 - train 0.69023 | val 0.88552
  Epoch 030 - train 0.57770 | val 0.74694
  Epoch 039 - train 0.60823 | val 0.68287
  Classification -> best τ=0.340 (val F1=0.4264)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66405 | val 0.68169
  Epoch 020 - train 0.62462 | val 0.83692
  Epoch 029 - train 0.64248 | val 0.93488
  Classification -> best τ=0.425 (val F1=0.4225)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.75624 | val 0.66089
  Epoch 020 - train 0.62197 | val 0.67452
  Epoch 029 - train 0.58140 | val 0.69642
  Classification -> best τ=0.435 (val F1=0.3177)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.71074 | val 0.64880
  Epoch 020 - train 0.64369 | val 0.59610
  Epoch 030 - train 0.52225 | val 0.71824
  Epoch 040 - train 0.43607 | val 0.77840
  Epoch 043 - train 0.37586 | val 1.70353
  Classification -> best τ=0.360 (val F1=0.5398)
  Directional -> Accuracy: 0.5641, MCC: 0.0381, F1: 0.6792

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.62938 | val 0.91952
  Epoch 020 - train 0.68429 | val 1.52139
  Epoch 023 - train 0.58246 | val 1.09932
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69128 | val 1.07241
  Epoch 020 - train 0.65400 | val 0.97972
  Epoch 021 - train 0.69256 | val 0.99753
  Classification -> best τ=0.495 (val F1=0.1984)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65628 | val 1.24502
  Epoch 020 - train 0.61294 | val 1.60691
  Epoch 022 - train 0.62128 | val 1.52364
  Classification -> best τ=0.515 (val F1=0.4171)
  Directional -> Accuracy: 0.4815, MCC: -0.0371, F1: 0.4615

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.68306 | val 0.79559
  Epoch 020 - train 0.62551 | val 0.80307
  Epoch 030 - train 0.59967 | val 0.82037
  Epoch 031 - train 0.56667 | val 0.74686
  Classification -> best τ=0.775 (val F1=0.2758)
  Directional -> Accuracy: 0.5686, MCC: 0.1369, F1: 0.5600

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70057 | val 0.87968
  Epoch 020 - train 0.65066 | val 2.39193
  Epoch 021 - train 0.59980 | val 2.71728
  Classification -> best τ=0.615 (val F1=0.1687)

[I 2026-02-19 06:40:07,772] Trial 74 finished with value: 0.2805031313371805 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.002049918152246856, 'weight_decay': 6.9448254467498285e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.6321619987986522, 'early_stopping_min_delta': 0.000821367734629032}. Best is trial 74 with value: 0.2805031313371805.

  Classification -> best τ=0.450 (val F1=0.3469)
  Directional -> Accuracy: 0.5690, MCC: 0.2207, F1: 0.6575

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2805031313371805
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68352 | val 0.93221
  Epoch 020 - train 0.68098 | val 0.84769
  Epoch 021 - train 0.66639 | val 0.87201
  Classification -> best τ=0.545 (val F1=0.2895)
  Directional -> Accuracy: 0.5946, MCC: 0.1574, F1: 0.3478

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.72707 | val 0.99829
  Epoch 020 - train 0.63536 | val 0.95836
  Epoch 024 - train 0.64333 | val 1.00771
  Classification -> best τ=0.415 (val F1=0.2296)
  Directional -> Accuracy: 0.6512, MCC: 0.2304, F1: 0.7458

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.74238 | val 0.69825
  Epoch 020 - train 0.68366 | val 0.69964
  Epoch 022 - train 0.65203 | val 0.73412
  Classification -> best τ=0.520 (val F1=0.3340)
  Directional -> Accuracy: 0.5909, MCC: 0.2589, F1: 0.4375

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67955 | val 0.98002
  Epoch 020 - train 0.66481 | val 0.95817
  Epoch 021 - train 0.68755 | val 0.95664
  Classification -> best τ=0.420 (val F1=0.0549)
  Directional -> Accuracy: 0.5278, MCC: -0.1092, F1: 0.6909

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.73724 | val 0.66575
  Epoch 020 - train 0.63989 | val 1.19371
  Epoch 030 - train 0.60866 | val 1.36063
  Classification -> best τ=0.680 (val F1=0.4965)
  Directional -> Accuracy: 0.5625, MCC: 0.1685, F1: 0.4324

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.60156 | val 1.08368
  Epoch 020 - train 0.54244 | val 2.73649
  Epoch 021 - train 0.52168 | val 2.99159
  Classification -> best τ=0.515 (val F1=0.1647)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.73772 | val 0.69839
  Epoch 020 - train 0.67460 | val 0.69732
  Epoch 030 - train 0.67197 | val 0.71795
  Epoch 034 - train 0.66992 | val 0.72431
  Classification -> best τ=0.205 (val F1=0.2070)
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.66559 | val 0.92173
  Epoch 020 - train 0.63742 | val 0.98886
  Epoch 024 - train 0.61306 | val 0.69056
  Classification -> best τ=0.490 (val F1=0.2582)
  Directional -> Accuracy: 0.6410, MCC: 0.2816, F1: 0.3636

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68506 | val 0.79817
  Epoch 020 - train 0.61524 | val 0.77560
  Epoch 024 - train 0.58412 | val 0.94951
  Classification -> best τ=0.490 (val F1=0.4286)
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.71682 | val 0.90420
  Epoch 020 - train 0.65726 | val 1.05452
  Epoch 021 - train 0.61759 | val 0.92349
  Classification -> best τ=0.440 (val F1=0.2238)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70664 | val 1.06810
  Epoch 020 - train 0.63652 | val 1.83152
  Epoch 021 - train 0.66314 | val 1.79026
  Classification -> best τ=0.525 (val F1=0.3544)
  Directional -> Accuracy: 0.6170, MCC: 0.2905, F1: 0.2500

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71060 | val 0.70511
  Epoch 020 - train 0.64642 | val 0.89831
  Epoch 021 - train 0.68178 | val 0.84844
  Classification -> best τ=0.505 (val F1=0.1908)
  Directional -> Accuracy: 0.4909, MCC: 0.0461, F1: 0.1765

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66235 | val 0.74429
  Epoch 020 - train 0.57372 | val 1.01881
  Epoch 021 - train 0.55818 | val 0.91582
  Classification -> best τ=0.490 (val F1=0.1060)
  Directional -> Accuracy: 0.5208, MCC: 0.0323, F1: 0.4390

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69821 | val 0.88960
  Epoch 020 - train 0.65009 | val 1.68960
  Epoch 021 - train 0.62534 | val 1.56185
  Classification -> best τ=0.505 (val F1=0.3030)
  Directional -> Accuracy: 0.5862, MCC: 0.2006, F1: 0.5000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.69622 | val 0.70816
  Epoch 020 - train 0.66670 | val 0.78812
  Epoch 024 - train 0.63540 | val 0.71801
  Classification -> best τ=0.490 (val F1=0.2630)
  Directional -> Accuracy: 0.5306, MCC: -0.1303, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70086 | val 0.74456
  Epoch 020 - train 0.67163 | val 0.74735
  Epoch 021 - train 0.65614 | val 0.77234
  Classification -> best τ=0.435 (val F1=0.2681)
  Directional -> Accuracy: 0.5522, MCC: 0.0886, F1: 0.7000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.66521 | val 1.21932
  Epoch 020 - train 0.69507 | val 1.21137
  Epoch 021 - train 0.65741 | val 1.30138
  Classification -> best τ=0.485 (val F1=0.0827)
  Directional -> Accuracy: 0.6071, MCC: 0.0000, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.68193 | val 0.69577
  Epoch 020 - train 0.66205 | val 0.73138
  Epoch 026 - train 0.67076 | val 0.76714
  Classification -> best τ=0.630 (val F1=0.1829)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.66682 | val 0.75009
  Epoch 020 - train 0.60814 | val 0.97018
  Epoch 022 - train 0.61679 | val 1.07001
  Classification -> best τ=0.345 (val F1=0.2799)
  Directional -> Accuracy: 0.5484, MCC: 0.1669, F1: 0.5000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66692 | val 0.71591
  Epoch 020 - train 0.60067 | val 1.12611
  Epoch 022 - train 0.63576 | val 0.91579
  Classification -> best τ=0.490 (val F1=0.3194)
  Directional -> Accuracy: 0.4722, MCC: 0.1512, F1: 0.0952

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.72091 | val 0.79378
  Epoch 020 - train 0.63765 | val 1.10664
  Epoch 025 - train 0.65327 | val 1.22889
  Classification -> best τ=0.410 (val F1=0.3492)
  Directional -> Accuracy: 0.5333, MCC: 0.0187, F1: 0.6182

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.74526 | val 0.76413
  Epoch 020 - train 0.68124 | val 0.85812
  Epoch 021 - train 0.66319 | val 0.90838
  Classification -> best τ=0.555 (val F1=0.1947)
  Directional -> Accuracy: 0.5079, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.74540 | val 0.69334
  Epoch 020 - train 0.70862 | val 0.70119
  Epoch 023 - train 0.69641 | val 0.70303
  Classification -> best τ=0.610 (val F1=0.2974)
  Directional -> Accuracy: 0.4182, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68975 | val 0.69339
  Epoch 020 - train 0.68411 | val 0.81213
  Epoch 028 - train 0.66829 | val 0.80263
  Classification -> best τ=0.430 (val F1=0.2376)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.65377 | val 0.64116
  Epoch 020 - train 0.64010 | val 0.65221
  Epoch 030 - train 0.63618 | val 0.75464
  Epoch 032 - train 0.58115 | val 0.84204
  Classification -> best τ=0.490 (val F1=0.4235)
  Directional -> Accuracy: 0.5660, MCC: 0.2449, F1: 0.4103

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.70301 | val 1.27345
  Epoch 020 - train 0.62193 | val 0.87238
  Epoch 022 - train 0.69162 | val 1.02067
  Classification -> best τ=0.530 (val F1=0.1612)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71553 | val 0.79697
  Epoch 020 - train 0.64773 | val 0.72220
  Epoch 028 - train 0.60577 | val 0.78324
  Classification -> best τ=0.640 (val F1=0.1402)
  Directional -> Accuracy: 0.4792, MCC: 0.0396, F1: 0.3902

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.73402 | val 0.71066
  Epoch 020 - train 0.62775 | val 0.83047
  Epoch 023 - train 0.64621 | val 0.86644
  Classification -> best τ=0.410 (val F1=0.2457)
  Directional -> Accuracy: 0.5000, MCC: 0.1208, F1: 0.1818

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.64461 | val 0.77617
  Epoch 020 - train 0.61475 | val 1.26951
  Epoch 023 - train 0.60323 | val 1.48084
  Classification -> best τ=0.535 (val F1=0.2928)
  Directional -> Accuracy: 0.5250, MCC: 0.0506, F1: 0.5581

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.68128 | val 0.73942
  Epoch 020 - train 0.69645 | val 0.86465
  Epoch 026 - train 0.66697 | val 0.84943
  Classification -> best τ=0.635 (val F1=0.1243)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69932 | val 0.76762
  Epoch 020 - train 0.58996 | val 0.88684
  Epoch 023 - train 0.56325 | val 1.00825
  Classification -> best τ=0.415 (val F1=0.3007)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70966 | val 0.77339
  Epoch 020 - train 0.67013 | val 0.70552
  Epoch 028 - train 0.67256 | val 0.68724
  Classification -> best τ=0.305 (val F1=0.3411)
  Directional -> Accuracy: 0.5429, MCC: 0.1243, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68120 | val 0.71124
  Epoch 020 - train 0.66202 | val 0.74476
  Epoch 028 - train 0.64031 | val 0.75083
  Classification -> best τ=0.360 (val F1=0.2576)
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67555 | val 0.77537
  Epoch 020 - train 0.68540 | val 1.10795
  Epoch 022 - train 0.60820 | val 0.93412
  Classification -> best τ=0.370 (val F1=0.3397)
  Directional -> Accuracy: 0.5625, MCC: 0.0849, F1: 0.6500

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.65596 | val 1.77179
  Epoch 020 - train 0.54196 | val 1.66687
  Epoch 023 - train 0.54683 | val 1.80136
  Classification -> best τ=0.475 (val F1=0.3837)
  Directional -> Accuracy: 0.5714, MCC: 0.1435, F1: 0.4878

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.70504 | val 0.95723
  Epoch 020 - train 0.63507 | val 1.03577
  Epoch 022 - train 0.59419 | val 1.16068
  Classification -> best τ=0.415 (val F1=0.2347)
  Directional -> Accuracy: 0.5556, MCC: 0.1930, F1: 0.6471

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.54710 | val 1.61717
  Epoch 020 - train 0.51430 | val 1.81483
  Epoch 022 - train 0.54021 | val 1.65229
  Classification -> best τ=0.535 (val F1=0.3046)
  Directional -> Accuracy: 0.3636, MCC: -0.1922, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69249 | val 0.66074
  Epoch 020 - train 0.66498 | val 0.67083
  Epoch 030 - train 0.57329 | val 0.87683
  Epoch 036 - train 0.61441 | val 1.11806
  Classification -> best τ=0.500 (val F1=0.4973)
  Directional -> Accuracy: 0.3111, MCC: -0.1890, F1: 0.4561

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.64076 | val 1.17040
  Epoch 020 - train 0.60558 | val 1.89430
  Epoch 021 - train 0.59311 | val 2.00996
  Classification -> best τ=0.435 (val F1=0.1300)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.71940 | val 0.66785
  Epoch 020 - train 0.68832 | val 0.66959
  Epoch 028 - train 0.63135 | val 0.69144
  Classification -> best τ=0.445 (val F1=0.3177)
  Directional -> Accuracy: 0.5349, MCC: 0.2158, F1: 0.1667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.74692 | val 0.69379
  Epoch 020 - train 0.63829 | val 0.71211
  Epoch 030 - train 0.57518 | val 1.07341
  Epoch 037 - train 0.45813 | val 1.42614
  Classification -> best τ=0.335 (val F1=0.3380)
  Directional -> Accuracy: 0.6154, MCC: 0.1479, F1: 0.7368

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65069 | val 0.99533
  Epoch 020 - train 0.60101 | val 1.64579
  Epoch 021 - train 0.58068 | val 1.21663
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.72221 | val 0.90746
  Epoch 020 - train 0.64770 | val 0.68969
  Epoch 030 - train 0.63479 | val 1.08991
  Epoch 035 - train 0.62032 | val 1.11433
  Classification -> best τ=0.370 (val F1=0.3024)
  Directional -> Accuracy: 0.6604, MCC: 0.3100, F1: 0.7273

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66740 | val 0.74483
  Epoch 020 - train 0.59211 | val 2.03956
  Epoch 021 - train 0.63823 | val 2.18997
  Classification -> best τ=0.580 (val F1=0.3305)
  Directional -> Accuracy: 0.5556, MCC: 0.1654, F1: 0.6757

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69081 | val 1.68826
  Epoch 020 - train 0.66590 | val 1.40811
  Epoch 021 - train 0.62304 | val 1.58413
  Classification -> best τ=0.440 (val F1=0.2777)
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.68417 | val 0.95382
  Epoch 020 - train 0.61733 | val 1.51393
  Epoch 021 - train 0.66057 | val 1.24529
  Classification -> best τ=0.535 (val F1=0.1770)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70401 | val 0.67273
  Epoch 020 - train 0.68138 | val 0.66944

[I 2026-02-19 06:52:44,971] Trial 75 finished with value: 0.2625083097396167 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.0017918285094106283, 'weight_decay': 4.180680059834518e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.5105215503171499, 'early_stopping_min_delta': 0.00021490939260286005}. Best is trial 74 with value: 0.2805031313371805.

  Epoch 027 - train 0.65827 | val 0.67623
  Classification -> best τ=0.560 (val F1=0.3017)
  Directional -> Accuracy: 0.5517, MCC: 0.0775, F1: 0.3158

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2625083097396167
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.69778 | val 0.66560
  Epoch 020 - train 0.67477 | val 0.68612
  Epoch 030 - train 0.66859 | val 0.98866
  Classification -> best τ=0.535 (val F1=0.2489)
  Directional -> Accuracy: 0.5135, MCC: -0.0843, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.68425 | val 0.67508
  Epoch 020 - train 0.64617 | val 0.71264
  Epoch 030 - train 0.64795 | val 0.80913
  Classification -> best τ=0.360 (val F1=0.3227)
  Directional -> Accuracy: 0.6047, MCC: 0.2191, F1: 0.6383

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.70231 | val 0.70020
  Epoch 020 - train 0.68516 | val 0.81623
  Epoch 030 - train 0.62983 | val 0.79271
  Classification -> best τ=0.380 (val F1=0.2971)
  Directional -> Accuracy: 0.4318, MCC: -0.1643, F1: 0.5283

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.67991 | val 0.96732
  Epoch 020 - train 0.67630 | val 1.12228
  Epoch 021 - train 0.67753 | val 1.10008
  Classification -> best τ=0.455 (val F1=0.2548)
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.70315 | val 0.61480
  Epoch 020 - train 0.64091 | val 0.72431
  Epoch 024 - train 0.59980 | val 0.80048
  Classification -> best τ=0.545 (val F1=0.5017)
  Directional -> Accuracy: 0.5833, MCC: 0.1968, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66244 | val 0.79485
  Epoch 020 - train 0.64536 | val 0.91804
  Epoch 021 - train 0.63063 | val 0.89478
  Classification -> best τ=0.470 (val F1=0.2392)
  Directional -> Accuracy: 0.3864, MCC: -0.3581, F1: 0.5574

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.71194 | val 0.69019
  Epoch 020 - train 0.69343 | val 0.69826
  Epoch 026 - train 0.69323 | val 0.72842
  Classification -> best τ=0.430 (val F1=0.2709)
  Directional -> Accuracy: 0.4242, MCC: -0.0286, F1: 0.5476

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.64867 | val 2.12914
  Epoch 020 - train 0.66047 | val 1.16530
  Epoch 022 - train 0.59175 | val 1.31590
  Classification -> best τ=0.515 (val F1=0.2582)
  Directional -> Accuracy: 0.5641, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.75462 | val 1.02095
  Epoch 020 - train 0.61398 | val 0.86088
  Epoch 030 - train 0.61177 | val 0.93058
  Classification -> best τ=0.165 (val F1=0.3983)
  Directional -> Accuracy: 0.5435, MCC: 0.0877, F1: 0.5116

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69153 | val 0.77805
  Epoch 020 - train 0.66144 | val 0.81433
  Epoch 021 - train 0.64265 | val 0.83767
  Classification -> best τ=0.435 (val F1=0.1183)
  Directional -> Accuracy: 0.4776, MCC: 0.1001, F1: 0.5882

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.70338 | val 1.67507
  Epoch 020 - train 0.62221 | val 1.62908
  Epoch 021 - train 0.63642 | val 1.52093
  Classification -> best τ=0.550 (val F1=0.3057)
  Directional -> Accuracy: 0.5532, MCC: 0.1093, F1: 0.5333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.71586 | val 1.27573
  Epoch 020 - train 0.67019 | val 1.21288
  Epoch 021 - train 0.67477 | val 1.24124
  Classification -> best τ=0.430 (val F1=0.1955)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66323 | val 0.88078
  Epoch 020 - train 0.63082 | val 1.01548
  Epoch 021 - train 0.64433 | val 0.92287
  Classification -> best τ=0.490 (val F1=0.0544)
  Directional -> Accuracy: 0.5417, MCC: 0.0731, F1: 0.4211

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.77757 | val 0.71231
  Epoch 020 - train 0.70672 | val 0.74513
  Epoch 025 - train 0.69444 | val 0.78258
  Classification -> best τ=0.365 (val F1=0.2411)
  Directional -> Accuracy: 0.4828, MCC: -0.0290, F1: 0.4444

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68468 | val 0.82987
  Epoch 020 - train 0.65995 | val 0.72055
  Epoch 021 - train 0.63162 | val 0.71969
  Classification -> best τ=0.520 (val F1=0.1594)
  Directional -> Accuracy: 0.5102, MCC: -0.0499, F1: 0.2500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.71517 | val 0.69698
  Epoch 020 - train 0.67597 | val 0.76938
  Epoch 028 - train 0.65428 | val 0.94856
  Classification -> best τ=0.260 (val F1=0.2866)
  Directional -> Accuracy: 0.5672, MCC: 0.1890, F1: 0.7129

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.71862 | val 0.80490
  Epoch 020 - train 0.69680 | val 0.72119
  Epoch 030 - train 0.64155 | val 0.84897
  Classification -> best τ=0.510 (val F1=0.2316)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.67967 | val 0.72576
  Epoch 020 - train 0.66864 | val 0.69973
  Epoch 025 - train 0.68284 | val 0.72435
  Classification -> best τ=0.595 (val F1=0.2127)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.72022 | val 0.72339
  Epoch 020 - train 0.63623 | val 0.72296
  Epoch 022 - train 0.65211 | val 0.76098
  Classification -> best τ=0.405 (val F1=0.2984)
  Directional -> Accuracy: 0.5161, MCC: 0.1949, F1: 0.3478

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.67780 | val 0.67006
  Epoch 020 - train 0.65235 | val 0.80144
  Epoch 030 - train 0.59165 | val 0.91353
  Classification -> best τ=0.480 (val F1=0.3464)
  Directional -> Accuracy: 0.4583, MCC: 0.1061, F1: 0.0488

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67276 | val 0.66906
  Epoch 020 - train 0.67474 | val 0.65062
  Epoch 030 - train 0.66502 | val 0.68509
  Classification -> best τ=0.505 (val F1=0.4615)
  Directional -> Accuracy: 0.3556, MCC: -0.2257, F1: 0.2564

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68314 | val 0.70769
  Epoch 020 - train 0.67679 | val 0.88881
  Epoch 021 - train 0.68227 | val 0.80666
  Classification -> best τ=0.550 (val F1=0.2992)
  Directional -> Accuracy: 0.3968, MCC: -0.2407, F1: 0.2083

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.73072 | val 0.69057
  Epoch 020 - train 0.67175 | val 0.76280
  Epoch 025 - train 0.68221 | val 0.79591
  Classification -> best τ=0.450 (val F1=0.2722)
  Directional -> Accuracy: 0.5455, MCC: 0.2114, F1: 0.4444

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68537 | val 0.74202
  Epoch 020 - train 0.67795 | val 0.68585
  Epoch 030 - train 0.65699 | val 0.74478
  Classification -> best τ=0.430 (val F1=0.1730)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.68921 | val 0.60836
  Epoch 020 - train 0.65014 | val 0.67000
  Epoch 030 - train 0.61905 | val 0.91126
  Classification -> best τ=0.470 (val F1=0.5250)
  Directional -> Accuracy: 0.5660, MCC: 0.2777, F1: 0.3784

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.72290 | val 0.92704
  Epoch 020 - train 0.71846 | val 1.71754
  Epoch 022 - train 0.69317 | val 1.67711
  Classification -> best τ=0.540 (val F1=0.1809)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.67496 | val 0.69634
  Epoch 020 - train 0.67036 | val 0.69883
  Epoch 030 - train 0.58992 | val 0.71336
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.70192 | val 0.68191
  Epoch 020 - train 0.70370 | val 0.69202
  Epoch 030 - train 0.64157 | val 0.77626
  Classification -> best τ=0.260 (val F1=0.2011)
  Directional -> Accuracy: 0.5000, MCC: 0.0919, F1: 0.2286

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70233 | val 0.98093
  Epoch 020 - train 0.65603 | val 1.15375
  Epoch 021 - train 0.64105 | val 1.14174
  Classification -> best τ=0.565 (val F1=0.2000)
  Directional -> Accuracy: 0.4500, MCC: -0.1250, F1: 0.2143

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70609 | val 0.64594
  Epoch 020 - train 0.70453 | val 0.64372
  Epoch 029 - train 0.65352 | val 0.65949
  Classification -> best τ=0.645 (val F1=0.2328)
  Directional -> Accuracy: 0.4250, MCC: -0.1240, F1: 0.0800

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.68731 | val 0.69755
  Epoch 020 - train 0.63227 | val 0.71163
  Epoch 025 - train 0.62953 | val 0.76319
  Classification -> best τ=0.325 (val F1=0.4775)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69194 | val 0.70444
  Epoch 020 - train 0.67998 | val 0.79279
  Epoch 030 - train 0.66437 | val 0.74769
  Classification -> best τ=0.295 (val F1=0.2625)
  Directional -> Accuracy: 0.5286, MCC: 0.0747, F1: 0.5217

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.74858 | val 0.79573
  Epoch 020 - train 0.68857 | val 0.83475
  Epoch 021 - train 0.67264 | val 0.84167
  Classification -> best τ=0.535 (val F1=0.2659)
  Directional -> Accuracy: 0.5306, MCC: 0.1820, F1: 0.6567

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.71641 | val 0.71096
  Epoch 020 - train 0.59054 | val 0.93510
  Epoch 021 - train 0.60733 | val 1.08659
  Classification -> best τ=0.400 (val F1=0.3921)
  Directional -> Accuracy: 0.5469, MCC: 0.0615, F1: 0.6234

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.70426 | val 1.55763
  Epoch 020 - train 0.54008 | val 1.43589
  Epoch 021 - train 0.59134 | val 1.47213
  Classification -> best τ=0.485 (val F1=0.3837)
  Directional -> Accuracy: 0.6122, MCC: 0.2293, F1: 0.5366

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66378 | val 0.72852
  Epoch 020 - train 0.63191 | val 0.78377
  Epoch 021 - train 0.61136 | val 0.82602
  Classification -> best τ=0.475 (val F1=0.2225)
  Directional -> Accuracy: 0.5185, MCC: 0.0619, F1: 0.5667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67741 | val 1.02706
  Epoch 020 - train 0.57041 | val 2.44283
  Epoch 022 - train 0.51577 | val 2.61290
  Classification -> best τ=0.605 (val F1=0.2734)
  Directional -> Accuracy: 0.3864, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.72232 | val 0.66566
  Epoch 020 - train 0.63569 | val 0.65124
  Epoch 028 - train 0.67670 | val 0.64655
  Classification -> best τ=0.395 (val F1=0.4973)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.68075 | val 0.73113
  Epoch 020 - train 0.65456 | val 1.37825
  Epoch 021 - train 0.60681 | val 1.42309
  Classification -> best τ=0.435 (val F1=0.3444)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.72890 | val 0.72771
  Epoch 020 - train 0.68730 | val 0.66585
  Epoch 030 - train 0.63261 | val 0.69272
  Classification -> best τ=0.455 (val F1=0.2708)
  Directional -> Accuracy: 0.4884, MCC: -0.0051, F1: 0.0833

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.71430 | val 0.70472
  Epoch 020 - train 0.66668 | val 1.00153
  Epoch 030 - train 0.62896 | val 1.60081
  Classification -> best τ=0.385 (val F1=0.4114)
  Directional -> Accuracy: 0.5897, MCC: 0.1071, F1: 0.6923

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69037 | val 1.61344
  Epoch 020 - train 0.58800 | val 1.61643
  Epoch 021 - train 0.56367 | val 1.84430
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69007 | val 0.76134
  Epoch 020 - train 0.66219 | val 0.75294
  Epoch 021 - train 0.64748 | val 0.80348
  Classification -> best τ=0.510 (val F1=0.1604)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.73121 | val 0.96787
  Epoch 020 - train 0.68240 | val 1.31818
  Epoch 021 - train 0.66295 | val 1.39379
  Classification -> best τ=0.610 (val F1=0.3468)
  Directional -> Accuracy: 0.5370, MCC: 0.0767, F1: 0.5902

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.71086 | val 0.69068
  Epoch 020 - train 0.66425 | val 0.99302
  Epoch 030 - train 0.63164 | val 0.93442
  Classification -> best τ=0.710 (val F1=0.2758)
  Directional -> Accuracy: 0.5686, MCC: 0.1387, F1: 0.5769

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67656 | val 1.74493
  Epoch 020 - train 0.63193 | val 1.56026
  Epoch 021 - train 0.63600 | val 1.55195
  Classification -> best τ=0.595 (val F1=0.0932)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68990 | val 0.73999
  Epoch 020 - train 0.70510 | val 0.67380
  Epoch 030 - train 0.69563 | val 0.67128
  Classification -> best τ=0.360 (val F1=0.2769)
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353


[I 2026-02-19 07:05:47,870] Trial 76 finished with value: 0.27111710641890924 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.002537701805590938, 'weight_decay': 6.546016675974261e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.6289579313161826, 'early_stopping_min_delta': 0.0006516749972830671}. Best is trial 74 with value: 0.2805031313371805.

Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68761 | val 1.16246
  Epoch 020 - train 0.66673 | val 1.69455
  Classification -> best τ=0.705 (val F1=0.2489)
  Directional -> Accuracy: 0.5405, MCC: -0.0466, F1: 0.0556

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.71561 | val 0.68580
  Epoch 020 - train 0.68026 | val 0.81865
  Classification -> best τ=0.335 (val F1=0.2850)
  Directional -> Accuracy: 0.4186, MCC: -0.0710, F1: 0.3243

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68374 | val 0.69410
  Epoch 020 - train 0.66077 | val 0.69617
  Classification -> best τ=0.475 (val F1=0.3385)
  Directional -> Accuracy: 0.4773, MCC: -0.0743, F1: 0.5818

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.70847 | val 0.68358
  Epoch 020 - train 0.66529 | val 0.75653
  Classification -> best τ=0.525 (val F1=0.1936)
  Directional -> Accuracy: 0.5556, MCC: 0.2144, F1: 0.3846

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.71886 | val 0.66433
  Epoch 020 - train 0.62180 | val 0.71329
  Classification -> best τ=0.380 (val F1=0.4102)
  Directional -> Accuracy: 0.6875, MCC: 0.3801, F1: 0.6809

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.66917 | val 1.21629
  Epoch 020 - train 0.61704 | val 0.85834
  Classification -> best τ=0.455 (val F1=0.0262)
  Directional -> Accuracy: 0.4091, MCC: -0.3162, F1: 0.5806

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.70199 | val 0.68660
  Epoch 020 - train 0.69164 | val 0.68881
  Classification -> best τ=0.495 (val F1=0.2828)
  Directional -> Accuracy: 0.5606, MCC: 0.1289, F1: 0.5246

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.75443 | val 0.59340
  Epoch 020 - train 0.68027 | val 0.61376
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.68053 | val 1.05141
  Epoch 020 - train 0.64742 | val 0.75570
  Classification -> best τ=0.550 (val F1=0.3780)
  Directional -> Accuracy: 0.6304, MCC: 0.2370, F1: 0.5405

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69764 | val 0.90514
  Epoch 020 - train 0.63479 | val 0.98812
  Classification -> best τ=0.405 (val F1=0.2364)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.64449 | val 0.93473
  Epoch 020 - train 0.63629 | val 0.69105
  Classification -> best τ=0.450 (val F1=0.3057)
  Directional -> Accuracy: 0.5106, MCC: 0.0531, F1: 0.5490

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.70830 | val 0.77039
  Epoch 020 - train 0.64850 | val 1.21624
  Classification -> best τ=0.515 (val F1=0.0185)
  Directional -> Accuracy: 0.6000, MCC: 0.2291, F1: 0.7105

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.67415 | val 0.84237
  Epoch 020 - train 0.65191 | val 0.77009
  Classification -> best τ=0.580 (val F1=0.1551)
  Directional -> Accuracy: 0.5208, MCC: 0.0295, F1: 0.4103

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.69183 | val 0.68794
  Epoch 020 - train 0.66337 | val 0.78946
  Classification -> best τ=0.395 (val F1=0.2837)
  Directional -> Accuracy: 0.5172, MCC: 0.0311, F1: 0.5484

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68896 | val 0.69274
  Epoch 020 - train 0.66078 | val 0.69246
  Classification -> best τ=0.490 (val F1=0.2630)
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70394 | val 0.74928
  Epoch 020 - train 0.67844 | val 0.86132
  Classification -> best τ=0.500 (val F1=0.2735)
  Directional -> Accuracy: 0.4478, MCC: -0.2207, F1: 0.6022

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.73018 | val 0.75978
  Epoch 020 - train 0.67738 | val 0.93204
  Classification -> best τ=0.645 (val F1=0.2607)
  Directional -> Accuracy: 0.4107, MCC: 0.1085, F1: 0.0571

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69826 | val 0.70679
  Epoch 020 - train 0.68023 | val 0.85146
  Classification -> best τ=0.555 (val F1=0.2127)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.71741 | val 0.76199
  Epoch 020 - train 0.66850 | val 0.90528
  Classification -> best τ=0.435 (val F1=0.1738)
  Directional -> Accuracy: 0.5161, MCC: 0.1463, F1: 0.4000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.66370 | val 0.78875
  Epoch 020 - train 0.62667 | val 0.71509
  Classification -> best τ=0.520 (val F1=0.2565)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.66435 | val 0.75660
  Epoch 020 - train 0.66497 | val 0.72807
  Classification -> best τ=0.550 (val F1=0.4472)
  Directional -> Accuracy: 0.4444, MCC: 0.0534, F1: 0.2424

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.70383 | val 0.74508
  Epoch 020 - train 0.69018 | val 0.85848
  Classification -> best τ=0.500 (val F1=0.2206)
  Directional -> Accuracy: 0.4762, MCC: -0.1261, F1: 0.0571

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.69033 | val 0.71295
  Epoch 020 - train 0.67809 | val 0.71839
  Classification -> best τ=0.450 (val F1=0.2538)
  Directional -> Accuracy: 0.4182, MCC: -0.0684, F1: 0.2000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67651 | val 0.73429
  Epoch 020 - train 0.70301 | val 0.71154
  Classification -> best τ=0.395 (val F1=0.2257)
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.67146 | val 0.73142
  Epoch 020 - train 0.64801 | val 0.69172
  Classification -> best τ=0.495 (val F1=0.5565)
  Directional -> Accuracy: 0.5283, MCC: 0.1718, F1: 0.3243

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.76025 | val 0.97788
  Epoch 020 - train 0.62956 | val 0.86995
  Classification -> best τ=0.525 (val F1=0.3425)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.68205 | val 0.68121
  Epoch 020 - train 0.63718 | val 0.77822
  Classification -> best τ=0.575 (val F1=0.0903)
  Directional -> Accuracy: 0.4792, MCC: -0.0213, F1: 0.4898

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.65249 | val 0.66431
  Epoch 020 - train 0.61305 | val 0.96319
  Classification -> best τ=0.530 (val F1=0.3006)
  Directional -> Accuracy: 0.5000, MCC: 0.1821, F1: 0.1290

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.70021 | val 0.81712
  Epoch 020 - train 0.67422 | val 0.66566
  Classification -> best τ=0.435 (val F1=0.3333)
  Directional -> Accuracy: 0.4500, MCC: -0.1091, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.66579 | val 0.77233
  Epoch 020 - train 0.69344 | val 0.72848
  Classification -> best τ=0.570 (val F1=0.2328)
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.69005 | val 0.72340
  Epoch 020 - train 0.63075 | val 0.69829
  Classification -> best τ=0.375 (val F1=0.4237)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.70514 | val 0.68687
  Epoch 020 - train 0.69639 | val 0.71725
  Classification -> best τ=0.315 (val F1=0.2879)
  Directional -> Accuracy: 0.5571, MCC: 0.1409, F1: 0.5373

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.69558 | val 0.71107
  Epoch 020 - train 0.68095 | val 0.70985
  Classification -> best τ=0.405 (val F1=0.2075)
  Directional -> Accuracy: 0.5306, MCC: 0.0923, F1: 0.5965

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.65429 | val 0.86446
  Epoch 020 - train 0.62138 | val 0.85019
  Classification -> best τ=0.365 (val F1=0.3587)
  Directional -> Accuracy: 0.5625, MCC: 0.0476, F1: 0.6957

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.68467 | val 0.70336
  Epoch 020 - train 0.58121 | val 1.05509
  Classification -> best τ=0.460 (val F1=0.3231)
  Directional -> Accuracy: 0.5918, MCC: 0.1936, F1: 0.4737

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66552 | val 0.76035
  Epoch 020 - train 0.62343 | val 1.05111
  Classification -> best τ=0.415 (val F1=0.2094)
  Directional -> Accuracy: 0.5370, MCC: 0.1558, F1: 0.6377

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.64371 | val 1.50031
  Epoch 020 - train 0.62676 | val 2.42440
  Classification -> best τ=0.535 (val F1=0.2171)
  Directional -> Accuracy: 0.3636, MCC: -0.1922, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.69294 | val 0.86674
  Epoch 020 - train 0.63752 | val 0.64886
  Classification -> best τ=0.420 (val F1=0.5899)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.69119 | val 0.80142
  Epoch 020 - train 0.62364 | val 1.01141
  Classification -> best τ=0.490 (val F1=0.1662)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70638 | val 0.68273
  Epoch 020 - train 0.64749 | val 0.67155
  Classification -> best τ=0.505 (val F1=0.3177)
  Directional -> Accuracy: 0.4651, MCC: -0.1579, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.61522 | val 0.66590
  Epoch 020 - train 0.67727 | val 1.00315
  Classification -> best τ=0.390 (val F1=0.4730)
  Directional -> Accuracy: 0.5897, MCC: 0.0927, F1: 0.7037

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.63927 | val 0.95875
  Epoch 020 - train 0.57908 | val 1.43073
  Classification -> best τ=0.685 (val F1=0.1754)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71455 | val 0.71242
  Epoch 020 - train 0.65704 | val 0.86044
  Classification -> best τ=0.630 (val F1=0.1984)
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.68782 | val 1.50310
  Epoch 020 - train 0.65890 | val 2.45841
  Classification -> best τ=0.580 (val F1=0.2988)
  Directional -> Accuracy: 0.5926, MCC: 0.2299, F1: 0.6857

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.70617 | val 0.67297
  Epoch 020 - train 0.66604 | val 0.70592
  Classification -> best τ=0.570 (val F1=0.2513)
  Directional -> Accuracy: 0.5882, MCC: 0.1793, F1: 0.6038

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.71328 | val 1.31486
  Epoch 020 - train 0.66503 | val 1.27434
  Classification -> best τ=0.525 (val F1=0.3084)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.70150 | val 0.68008
  Epoch 020 - train 0.67913 | val 0.69703
  Classification -> best τ=0.405 (val F1=0.2769)
  Directional -> Accuracy: 0.5000, MCC: 0.1764, F1: 0.6506

[I 2026-02-19 07:16:08,704] Trial 77 finished with value: 0.2699929935146259 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.003654744838489731, 'weight_decay': 1.8514901671028395e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.6522570421696146, 'early_stopping_min_delta': 0.0009398192202741339}. Best is trial 74 with value: 0.2805031313371805.

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2699929935146259
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.67668 | val 0.72645
  Epoch 016 - train 0.64963 | val 0.88364
  Classification -> best τ=0.660 (val F1=0.2489)
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69012 | val 0.72239
  Epoch 016 - train 0.66862 | val 0.71923
  Classification -> best τ=0.525 (val F1=0.1734)
  Directional -> Accuracy: 0.6512, MCC: 0.2246, F1: 0.7541

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.68700 | val 0.64617
  Epoch 019 - train 0.67585 | val 0.72939
  Classification -> best τ=0.480 (val F1=0.3448)
  Directional -> Accuracy: 0.5455, MCC: 0.1041, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.72278 | val 1.45302
  Epoch 011 - train 0.68617 | val 1.32470
  Classification -> best τ=0.450 (val F1=0.1640)
  Directional -> Accuracy: 0.5417, MCC: 0.1348, F1: 0.4407

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.69055 | val 0.84106
  Epoch 017 - train 0.60045 | val 1.20409
  Classification -> best τ=0.645 (val F1=0.4638)
  Directional -> Accuracy: 0.6667, MCC: 0.3615, F1: 0.6190

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.68402 | val 0.76301
  Epoch 012 - train 0.68252 | val 0.95831
  Classification -> best τ=0.530 (val F1=0.1993)
  Directional -> Accuracy: 0.5682, MCC: 0.1365, F1: 0.5581

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.72343 | val 0.70582
  Epoch 011 - train 0.69473 | val 0.72051
  Classification -> best τ=0.435 (val F1=0.1851)
  Directional -> Accuracy: 0.4394, MCC: 0.0487, F1: 0.5747

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69733 | val 0.97668
  Epoch 011 - train 0.61005 | val 1.18329
  Classification -> best τ=0.490 (val F1=0.2582)
  Directional -> Accuracy: 0.5897, MCC: 0.1553, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.63151 | val 0.64895
  Epoch 020 - train 0.59245 | val 0.85772
  Classification -> best τ=0.470 (val F1=0.4822)
  Directional -> Accuracy: 0.6087, MCC: 0.2431, F1: 0.1818

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69046 | val 0.84814
  Epoch 012 - train 0.69005 | val 0.75984
  Classification -> best τ=0.410 (val F1=0.2326)
  Directional -> Accuracy: 0.3881, MCC: -0.1546, F1: 0.5287

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.65403 | val 1.26494
  Epoch 011 - train 0.65040 | val 1.31778
  Classification -> best τ=0.525 (val F1=0.2577)
  Directional -> Accuracy: 0.4681, MCC: 0.0153, F1: 0.5902

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.65320 | val 0.82438
  Epoch 011 - train 0.68648 | val 0.92268
  Classification -> best τ=0.435 (val F1=0.1386)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.68089 | val 0.78249
  Epoch 018 - train 0.53690 | val 0.95830
  Classification -> best τ=0.510 (val F1=0.1551)
  Directional -> Accuracy: 0.4375, MCC: -0.1567, F1: 0.2703

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67628 | val 0.87923
  Epoch 012 - train 0.69909 | val 0.89065
  Classification -> best τ=0.495 (val F1=0.1866)
  Directional -> Accuracy: 0.5345, MCC: 0.0619, F1: 0.5970

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.66485 | val 1.09218
  Epoch 011 - train 0.67965 | val 1.19026
  Classification -> best τ=0.540 (val F1=0.1825)
  Directional -> Accuracy: 0.6122, MCC: 0.2079, F1: 0.5366

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.70049 | val 0.89151
  Epoch 013 - train 0.68039 | val 0.93367
  Classification -> best τ=0.525 (val F1=0.1942)
  Directional -> Accuracy: 0.5373, MCC: 0.1035, F1: 0.4746

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.65637 | val 1.17812
  Epoch 011 - train 0.67224 | val 1.16070
  Classification -> best τ=0.455 (val F1=0.0514)
  Directional -> Accuracy: 0.6429, MCC: 0.1941, F1: 0.7561

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.71168 | val 0.78756
  Epoch 016 - train 0.64960 | val 0.80354
  Classification -> best τ=0.560 (val F1=0.2127)
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.65151 | val 0.80938
  Epoch 012 - train 0.66026 | val 0.81925
  Classification -> best τ=0.405 (val F1=0.2799)
  Directional -> Accuracy: 0.5161, MCC: 0.1949, F1: 0.3478

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.65027 | val 0.72381
  Epoch 012 - train 0.67286 | val 0.66828
  Classification -> best τ=0.470 (val F1=0.2889)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.65724 | val 0.69610
  Epoch 020 - train 0.64430 | val 0.68413
  Epoch 023 - train 0.62985 | val 0.68013
  Classification -> best τ=0.440 (val F1=0.3492)
  Directional -> Accuracy: 0.4667, MCC: -0.1111, F1: 0.5556

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.71567 | val 0.93017
  Epoch 011 - train 0.66213 | val 1.04439
  Classification -> best τ=0.560 (val F1=0.2312)
  Directional -> Accuracy: 0.5397, MCC: 0.1014, F1: 0.2564

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70143 | val 0.73979
  Epoch 011 - train 0.69203 | val 0.74881
  Classification -> best τ=0.535 (val F1=0.2750)
  Directional -> Accuracy: 0.4909, MCC: 0.2374, F1: 0.2222

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.67884 | val 0.72767
  Epoch 011 - train 0.67492 | val 0.74072
  Classification -> best τ=0.525 (val F1=0.1343)
  Directional -> Accuracy: 0.4762, MCC: -0.0725, F1: 0.3265

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70847 | val 0.65628
  Epoch 020 - train 0.67229 | val 0.70941
  Epoch 023 - train 0.61681 | val 0.78517
  Classification -> best τ=0.560 (val F1=0.5479)
  Directional -> Accuracy: 0.4528, MCC: -0.0188, F1: 0.0645

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.69255 | val 0.96210
  Epoch 011 - train 0.68644 | val 1.00379
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.66498 | val 1.02580
  Epoch 011 - train 0.68150 | val 1.11844
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.69522 | val 0.75933
  Epoch 012 - train 0.68507 | val 0.81840
  Classification -> best τ=0.465 (val F1=0.2011)
  Directional -> Accuracy: 0.5741, MCC: 0.1313, F1: 0.6462

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.61618 | val 1.09112
  Epoch 011 - train 0.64994 | val 1.11391
  Classification -> best τ=0.485 (val F1=0.1938)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.70976 | val 0.69987
  Epoch 014 - train 0.60931 | val 0.67651
  Classification -> best τ=0.545 (val F1=0.0510)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65827 | val 0.73259
  Epoch 013 - train 0.62794 | val 0.86241
  Classification -> best τ=0.415 (val F1=0.2277)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.68934 | val 0.73380
  Epoch 012 - train 0.70168 | val 0.77639
  Classification -> best τ=0.370 (val F1=0.2976)
  Directional -> Accuracy: 0.5429, MCC: 0.0676, F1: 0.6000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.70031 | val 0.85259
  Epoch 012 - train 0.71631 | val 0.82040
  Classification -> best τ=0.495 (val F1=0.2536)
  Directional -> Accuracy: 0.6122, MCC: 0.3170, F1: 0.2963

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.67730 | val 0.89702
  Epoch 011 - train 0.59859 | val 0.93135
  Classification -> best τ=0.415 (val F1=0.3663)
  Directional -> Accuracy: 0.5469, MCC: 0.1251, F1: 0.5246

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64082 | val 1.13314
  Epoch 013 - train 0.61433 | val 1.25222
  Classification -> best τ=0.535 (val F1=0.3498)
  Directional -> Accuracy: 0.5510, MCC: 0.1195, F1: 0.3125

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66773 | val 0.72989
  Epoch 015 - train 0.60777 | val 0.75136
  Classification -> best τ=0.340 (val F1=0.3491)
  Directional -> Accuracy: 0.5370, MCC: 0.1256, F1: 0.6154

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.65413 | val 2.24834
  Epoch 012 - train 0.63129 | val 2.15054
  Classification -> best τ=0.530 (val F1=0.1856)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.68047 | val 0.60460
  Epoch 020 - train 0.65970 | val 0.75422
  Epoch 024 - train 0.61677 | val 0.68580
  Classification -> best τ=0.350 (val F1=0.5899)
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.67595 | val 0.86214
  Epoch 011 - train 0.67792 | val 0.86087
  Classification -> best τ=0.495 (val F1=0.1840)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.64581 | val 0.67914
  Epoch 019 - train 0.63822 | val 0.70404
  Classification -> best τ=0.430 (val F1=0.2762)
  Directional -> Accuracy: 0.5116, MCC: 0.1508, F1: 0.0870

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67356 | val 0.66377
  Epoch 020 - train 0.64805 | val 0.65772
  Epoch 030 - train 0.49217 | val 0.64484
  Classification -> best τ=0.375 (val F1=0.5398)
  Directional -> Accuracy: 0.6154, MCC: 0.1945, F1: 0.7541

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.69630 | val 1.32099
  Epoch 011 - train 0.64032 | val 1.36545
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.70120 | val 0.85607
  Epoch 013 - train 0.66899 | val 0.86911
  Classification -> best τ=0.565 (val F1=0.1830)
  Directional -> Accuracy: 0.6038, MCC: 0.1894, F1: 0.6667

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.65382 | val 1.11073
  Epoch 017 - train 0.67063 | val 0.98898
  Classification -> best τ=0.345 (val F1=0.3000)
  Directional -> Accuracy: 0.5185, MCC: 0.0370, F1: 0.5185

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65086 | val 1.30627
  Epoch 011 - train 0.66448 | val 1.30494
  Classification -> best τ=0.480 (val F1=0.1823)
  Directional -> Accuracy: 0.5098, MCC: 0.1387, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.67264 | val 1.51522
  Epoch 011 - train 0.68121 | val 1.50488
  Classification -> best τ=0.525 (val F1=0.2155)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.71747 | val 0.69032
  Epoch 018 - train 0.69797 | val 0.69987
  Classification -> best τ=0.410 (val F1=0.3062)
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[I 2026-02-19 07:23:19,151] Trial 78 finished with value: 0.24447469690336815 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.0013417299058233053, 'weight_decay': 1.9177159204761553e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.6152285082869031, 'early_stopping_min_delta': 0.0005751707212763727}. Best is trial 74 with value: 0.2805031313371805.

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.24447469690336815
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.70761 | val 0.68578
  Epoch 020 - train 0.68746 | val 0.82890
  Classification -> best τ=0.570 (val F1=0.2163)
  Directional -> Accuracy: 0.5811, MCC: 0.1858, F1: 0.1143

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.73704 | val 0.68765
  Epoch 020 - train 0.69996 | val 0.70762
  Classification -> best τ=0.350 (val F1=0.2850)
  Directional -> Accuracy: 0.5814, MCC: 0.1615, F1: 0.6250

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.71434 | val 0.79403
  Epoch 020 - train 0.67381 | val 0.70903
  Classification -> best τ=0.455 (val F1=0.4809)
  Directional -> Accuracy: 0.4773, MCC: -0.0666, F1: 0.5660

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.73233 | val 0.70222
  Epoch 020 - train 0.69642 | val 0.69315
  Classification -> best τ=0.550 (val F1=0.1941)
  Directional -> Accuracy: 0.5278, MCC: 0.1080, F1: 0.4138

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.72220 | val 0.66204
  Epoch 020 - train 0.63411 | val 0.73032
  Classification -> best τ=0.545 (val F1=0.4965)
  Directional -> Accuracy: 0.6250, MCC: 0.2522, F1: 0.6250

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.70505 | val 0.71603
  Epoch 020 - train 0.64869 | val 0.85815
  Classification -> best τ=0.480 (val F1=0.1667)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4211

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.69470 | val 0.68483
  Epoch 020 - train 0.71797 | val 0.68115
  Classification -> best τ=0.350 (val F1=0.2868)
  Directional -> Accuracy: 0.4242, MCC: -0.0286, F1: 0.5476

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.65218 | val 0.78211
  Epoch 020 - train 0.67681 | val 0.95891
  Classification -> best τ=0.245 (val F1=0.2414)
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.66478 | val 0.80559
  Epoch 020 - train 0.68831 | val 0.88644
  Classification -> best τ=0.465 (val F1=0.2817)
  Directional -> Accuracy: 0.6304, MCC: 0.3012, F1: 0.2609

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.69233 | val 0.68793
  Epoch 020 - train 0.69901 | val 0.70711
  Classification -> best τ=0.425 (val F1=0.2812)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.69382 | val 0.73666
  Epoch 020 - train 0.71464 | val 0.90549
  Classification -> best τ=0.370 (val F1=0.2606)
  Directional -> Accuracy: 0.5532, MCC: 0.1093, F1: 0.5333

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.69048 | val 0.76718
  Epoch 020 - train 0.69711 | val 0.86191
  Classification -> best τ=0.450 (val F1=0.0917)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.65643 | val 1.08602
  Epoch 020 - train 0.58327 | val 0.75593
  Classification -> best τ=0.475 (val F1=0.3099)
  Directional -> Accuracy: 0.5208, MCC: 0.2000, F1: 0.6667

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.71321 | val 0.67119
  Epoch 020 - train 0.67986 | val 0.74226
  Classification -> best τ=0.395 (val F1=0.0466)
  Directional -> Accuracy: 0.5517, MCC: 0.0981, F1: 0.6061

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.70189 | val 0.70410
  Epoch 020 - train 0.67299 | val 0.69438
  Classification -> best τ=0.480 (val F1=0.2942)
  Directional -> Accuracy: 0.5714, MCC: 0.1081, F1: 0.4000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69213 | val 0.67394
  Epoch 020 - train 0.68951 | val 0.68743
  Classification -> best τ=0.340 (val F1=0.3164)
  Directional -> Accuracy: 0.5672, MCC: 0.1890, F1: 0.7129

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.72603 | val 0.71721
  Epoch 020 - train 0.70272 | val 0.69252
  Classification -> best τ=0.555 (val F1=0.2699)
  Directional -> Accuracy: 0.3929, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69958 | val 0.70887
  Epoch 020 - train 0.72126 | val 0.69126
  Classification -> best τ=0.575 (val F1=0.2011)
  Directional -> Accuracy: 0.4247, MCC: 0.0060, F1: 0.1250

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.68416 | val 0.68972
  Epoch 020 - train 0.71793 | val 0.68227
  Classification -> best τ=0.405 (val F1=0.3548)
  Directional -> Accuracy: 0.4677, MCC: 0.0966, F1: 0.2326

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70322 | val 0.70146
  Epoch 020 - train 0.68327 | val 0.69547
  Classification -> best τ=0.495 (val F1=0.2255)
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.73967 | val 0.78234
  Epoch 020 - train 0.68898 | val 0.70194
  Classification -> best τ=0.525 (val F1=0.1972)
  Directional -> Accuracy: 0.4000, MCC: -0.0440, F1: 0.0690

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68499 | val 0.68143
  Epoch 020 - train 0.70410 | val 0.69485
  Classification -> best τ=0.730 (val F1=0.2345)
  Directional -> Accuracy: 0.4921, MCC: -0.0389, F1: 0.2000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.70427 | val 0.78065
  Epoch 020 - train 0.68182 | val 0.69720
  Classification -> best τ=0.545 (val F1=0.2359)
  Directional -> Accuracy: 0.4182, MCC: -0.1062, F1: 0.3333

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.68871 | val 0.72295
  Epoch 020 - train 0.64989 | val 0.74544
  Classification -> best τ=0.505 (val F1=0.1343)
  Directional -> Accuracy: 0.4762, MCC: -0.0588, F1: 0.4000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.70939 | val 0.71817
  Epoch 020 - train 0.69957 | val 0.71345
  Classification -> best τ=0.450 (val F1=0.3950)
  Directional -> Accuracy: 0.5660, MCC: 0.1510, F1: 0.5490

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.65670 | val 0.73224
  Epoch 020 - train 0.64428 | val 0.76889
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.69151 | val 0.75235
  Epoch 020 - train 0.71838 | val 0.95764
  Classification -> best τ=0.515 (val F1=0.0169)
  Directional -> Accuracy: 0.5208, MCC: 0.0792, F1: 0.5106

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.73350 | val 0.67501
  Epoch 020 - train 0.70516 | val 0.68531
  Classification -> best τ=0.425 (val F1=0.2457)
  Directional -> Accuracy: 0.5556, MCC: 0.1312, F1: 0.5200

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.67868 | val 1.41083
  Epoch 020 - train 0.67040 | val 3.51033
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.73408 | val 0.65126
  Epoch 020 - train 0.69491 | val 0.65651
  Classification -> best τ=0.670 (val F1=0.1791)
  Directional -> Accuracy: 0.4500, MCC: -0.0580, F1: 0.3125

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.67839 | val 0.71321
  Epoch 020 - train 0.64340 | val 0.72841
  Classification -> best τ=0.330 (val F1=0.3944)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69551 | val 0.86667
  Epoch 020 - train 0.67739 | val 0.66651
  Classification -> best τ=0.310 (val F1=0.3682)
  Directional -> Accuracy: 0.5286, MCC: 0.0987, F1: 0.4762

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.68213 | val 0.71842
  Epoch 020 - train 0.66760 | val 0.74537
  Classification -> best τ=0.415 (val F1=0.2576)
  Directional -> Accuracy: 0.5510, MCC: 0.2266, F1: 0.6667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.69212 | val 0.85775
  Epoch 020 - train 0.64269 | val 0.83192
  Classification -> best τ=0.395 (val F1=0.3663)
  Directional -> Accuracy: 0.5781, MCC: 0.1163, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.71365 | val 1.52452
  Epoch 020 - train 0.67486 | val 2.18617
  Classification -> best τ=0.540 (val F1=0.3913)
  Directional -> Accuracy: 0.5918, MCC: 0.2015, F1: 0.4444

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66983 | val 0.67080
  Epoch 020 - train 0.67761 | val 0.72276
  Classification -> best τ=0.420 (val F1=0.2347)
  Directional -> Accuracy: 0.5370, MCC: 0.1781, F1: 0.6479

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.67296 | val 1.46122
  Epoch 020 - train 0.58662 | val 0.95656
  Classification -> best τ=0.510 (val F1=0.2734)
  Directional -> Accuracy: 0.6136, MCC: 0.0509, F1: 0.7536

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71344 | val 0.68432
  Epoch 020 - train 0.67820 | val 0.89582
  Classification -> best τ=0.365 (val F1=0.4905)
  Directional -> Accuracy: 0.3333, MCC: -0.0762, F1: 0.4828

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.70134 | val 0.70441
  Epoch 020 - train 0.65715 | val 0.79136
  Classification -> best τ=0.525 (val F1=0.0870)
  Directional -> Accuracy: 0.5417, MCC: 0.2085, F1: 0.6857

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.67560 | val 0.72047
  Epoch 020 - train 0.73051 | val 0.66960
  Classification -> best τ=0.385 (val F1=0.2212)
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.62643 | val 0.70135
  Epoch 020 - train 0.64070 | val 1.38249
  Classification -> best τ=0.475 (val F1=0.3427)
  Directional -> Accuracy: 0.5897, MCC: 0.0927, F1: 0.7037

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.65450 | val 1.10829
  Epoch 020 - train 0.65779 | val 1.08356
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.71373 | val 0.69758
  Epoch 020 - train 0.69058 | val 0.68273
  Classification -> best τ=0.525 (val F1=0.2513)
  Directional -> Accuracy: 0.4528, MCC: -0.1662, F1: 0.5797

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.70463 | val 0.71708
  Epoch 020 - train 0.71114 | val 0.99910
  Classification -> best τ=0.475 (val F1=0.4165)
  Directional -> Accuracy: 0.5926, MCC: 0.2166, F1: 0.6765

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.69697 | val 1.85597
  Epoch 020 - train 0.62583 | val 1.36582
  Classification -> best τ=0.400 (val F1=0.2777)
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.70506 | val 0.83596
  Epoch 020 - train 0.70490 | val 1.31365
  Classification -> best τ=0.320 (val F1=0.1818)
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68568 | val 0.69313

[I 2026-02-19 07:29:04,262] Trial 79 finished with value: 0.2516667950890768 and parameters: {'feature_set': 'sentinment', 'model_type': 'LSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.002136743300984046, 'weight_decay': 2.6039407944517294e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.7559549510496382, 'early_stopping_min_delta': 0.0010376131628866284}. Best is trial 74 with value: 0.2805031313371805.

  Epoch 020 - train 0.68286 | val 0.77042
  Classification -> best τ=0.485 (val F1=0.3335)
  Directional -> Accuracy: 0.5000, MCC: -0.0121, F1: 0.4314

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2516667950890768
Pipeline initialized for a 'classification' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: classification
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.68649 | val 0.83913
  Epoch 020 - train 0.67017 | val 0.77667
  Epoch 024 - train 0.65517 | val 0.81300
  Classification -> best τ=0.490 (val F1=0.2589)
  Directional -> Accuracy: 0.5541, MCC: 0.0617, F1: 0.3529

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.69845 | val 0.64675
  Epoch 020 - train 0.64711 | val 0.62474
  Epoch 030 - train 0.60573 | val 0.74663
  Classification -> best τ=0.415 (val F1=0.5810)
  Directional -> Accuracy: 0.5349, MCC: 0.0271, F1: 0.6154

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.69571 | val 0.66992
  Epoch 020 - train 0.66390 | val 0.67630
  Epoch 028 - train 0.64326 | val 0.79915
  Classification -> best τ=0.485 (val F1=0.3448)
  Directional -> Accuracy: 0.5682, MCC: 0.1412, F1: 0.5581

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.68360 | val 0.76673
  Epoch 020 - train 0.67451 | val 0.81630
  Epoch 021 - train 0.65783 | val 0.84326
  Classification -> best τ=0.475 (val F1=0.0500)
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.68110 | val 0.73440
  Epoch 020 - train 0.59295 | val 1.19584
  Epoch 024 - train 0.56564 | val 1.80063
  Classification -> best τ=0.435 (val F1=0.4965)
  Directional -> Accuracy: 0.7292, MCC: 0.4845, F1: 0.6977

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.73592 | val 0.84297
  Epoch 020 - train 0.57800 | val 1.75367
  Epoch 021 - train 0.54430 | val 1.94529
  Classification -> best τ=0.500 (val F1=0.2287)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.72270 | val 0.73186
  Epoch 020 - train 0.66796 | val 0.77412
  Epoch 023 - train 0.64809 | val 0.77537
  Classification -> best τ=0.510 (val F1=0.3495)
  Directional -> Accuracy: 0.4394, MCC: -0.0206, F1: 0.5316

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.69581 | val 1.46860
  Epoch 020 - train 0.58384 | val 0.60002
  Epoch 030 - train 0.54970 | val 1.34230
  Classification -> best τ=0.430 (val F1=0.2582)
  Directional -> Accuracy: 0.6667, MCC: 0.3418, F1: 0.4348

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.67936 | val 0.90104
  Epoch 020 - train 0.59858 | val 0.95253
  Epoch 023 - train 0.58946 | val 1.41627
  Classification -> best τ=0.505 (val F1=0.2817)
  Directional -> Accuracy: 0.6304, MCC: 0.2389, F1: 0.3704

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.63816 | val 0.90802
  Epoch 020 - train 0.63516 | val 0.77492
  Epoch 021 - train 0.65418 | val 0.77541
  Classification -> best τ=0.495 (val F1=0.2012)
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.66682 | val 0.74201
  Epoch 020 - train 0.65711 | val 0.68214
  Epoch 029 - train 0.60490 | val 0.92242
  Classification -> best τ=0.415 (val F1=0.1239)
  Directional -> Accuracy: 0.4681, MCC: -0.0086, F1: 0.5614

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.67741 | val 0.84231
  Epoch 020 - train 0.67280 | val 0.81527
  Epoch 021 - train 0.68015 | val 0.92133
  Classification -> best τ=0.465 (val F1=0.0844)
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.66082 | val 0.85163
  Epoch 020 - train 0.53080 | val 0.95388
  Epoch 022 - train 0.54016 | val 0.97333
  Classification -> best τ=0.560 (val F1=0.1551)
  Directional -> Accuracy: 0.4375, MCC: -0.1685, F1: 0.2286

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.67053 | val 1.16147
  Epoch 020 - train 0.64939 | val 0.91132
  Epoch 023 - train 0.62636 | val 1.28366
  Classification -> best τ=0.395 (val F1=0.2244)
  Directional -> Accuracy: 0.5862, MCC: 0.1692, F1: 0.6364

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.68700 | val 0.70146
  Epoch 020 - train 0.66849 | val 1.22907
  Epoch 030 - train 0.58263 | val 0.74416
  Classification -> best τ=0.440 (val F1=0.4025)
  Directional -> Accuracy: 0.5510, MCC: 0.0782, F1: 0.4500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.69360 | val 0.80182
  Epoch 020 - train 0.62234 | val 1.23043
  Epoch 021 - train 0.64304 | val 1.15697
  Classification -> best τ=0.510 (val F1=0.2934)
  Directional -> Accuracy: 0.5821, MCC: 0.2389, F1: 0.4615

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.68722 | val 0.96265
  Epoch 020 - train 0.63383 | val 1.20791
  Epoch 021 - train 0.61061 | val 1.41620
  Classification -> best τ=0.520 (val F1=0.0671)
  Directional -> Accuracy: 0.4286, MCC: 0.1548, F1: 0.1111

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.69935 | val 0.78422
  Epoch 020 - train 0.65924 | val 0.88939
  Epoch 030 - train 0.67765 | val 0.71466
  Classification -> best τ=0.565 (val F1=0.2127)
  Directional -> Accuracy: 0.4247, MCC: 0.0984, F1: 0.0455

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.64327 | val 0.74901
  Epoch 020 - train 0.63138 | val 0.82206
  Epoch 030 - train 0.60730 | val 0.92201
  Classification -> best τ=0.165 (val F1=0.2483)
  Directional -> Accuracy: 0.5323, MCC: 0.1748, F1: 0.4314

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.70049 | val 0.67711
  Epoch 020 - train 0.62912 | val 0.75703
  Epoch 026 - train 0.60405 | val 0.83915
  Classification -> best τ=0.430 (val F1=0.3500)
  Directional -> Accuracy: 0.5694, MCC: 0.2184, F1: 0.4746

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.71687 | val 0.68476
  Epoch 020 - train 0.65648 | val 0.74169
  Epoch 026 - train 0.59082 | val 0.91899
  Classification -> best τ=0.410 (val F1=0.3492)
  Directional -> Accuracy: 0.5111, MCC: -0.0379, F1: 0.6071

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.68663 | val 1.20705
  Epoch 020 - train 0.65867 | val 0.89237
  Epoch 022 - train 0.65485 | val 0.95349
  Classification -> best τ=0.515 (val F1=0.2483)
  Directional -> Accuracy: 0.4921, MCC: -0.0085, F1: 0.6000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.66045 | val 1.01331
  Epoch 020 - train 0.62662 | val 0.99460
  Epoch 021 - train 0.65630 | val 0.97948
  Classification -> best τ=0.535 (val F1=0.1336)
  Directional -> Accuracy: 0.4182, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.66508 | val 0.70664
  Epoch 020 - train 0.66569 | val 0.71167
  Epoch 023 - train 0.65097 | val 0.71300
  Classification -> best τ=0.520 (val F1=0.1260)
  Directional -> Accuracy: 0.5079, MCC: -0.1211, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.66652 | val 0.73250
  Epoch 020 - train 0.60597 | val 0.99954
  Epoch 024 - train 0.58834 | val 0.98468
  Classification -> best τ=0.445 (val F1=0.4393)
  Directional -> Accuracy: 0.5283, MCC: 0.1718, F1: 0.3243

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.76193 | val 0.87629
  Epoch 020 - train 0.61681 | val 1.08394
  Epoch 023 - train 0.60667 | val 1.25236
  Classification -> best τ=0.050 (val F1=0.0000)
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.71042 | val 0.73160
  Epoch 020 - train 0.63971 | val 0.72827
  Epoch 021 - train 0.65823 | val 0.73686
  Classification -> best τ=0.495 (val F1=0.2753)
  Directional -> Accuracy: 0.5625, MCC: 0.0419, F1: 0.6769

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.67739 | val 0.71242
  Epoch 020 - train 0.63564 | val 0.74133
  Epoch 024 - train 0.62856 | val 0.79200
  Classification -> best τ=0.215 (val F1=0.2345)
  Directional -> Accuracy: 0.5370, MCC: 0.2626, F1: 0.2424

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.68984 | val 1.13518
  Epoch 020 - train 0.60666 | val 0.91267
  Epoch 021 - train 0.59435 | val 0.92559
  Classification -> best τ=0.550 (val F1=0.3333)
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.72201 | val 0.69521
  Epoch 020 - train 0.69219 | val 0.74019
  Epoch 030 - train 0.63238 | val 0.96616
  Classification -> best τ=0.560 (val F1=0.2482)
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.65575 | val 0.81126
  Epoch 020 - train 0.64004 | val 0.80117
  Epoch 023 - train 0.57009 | val 0.76140
  Classification -> best τ=0.440 (val F1=0.3703)
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.69314 | val 0.69557
  Epoch 020 - train 0.65872 | val 0.66335
  Epoch 030 - train 0.62390 | val 0.72047
  Classification -> best τ=0.430 (val F1=0.3003)
  Directional -> Accuracy: 0.5286, MCC: 0.1182, F1: 0.4407

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.65938 | val 1.07429
  Epoch 020 - train 0.66305 | val 1.00600
  Epoch 023 - train 0.64774 | val 0.96199
  Classification -> best τ=0.480 (val F1=0.3898)
  Directional -> Accuracy: 0.5306, MCC: 0.1503, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.61833 | val 0.88031
  Epoch 020 - train 0.63833 | val 1.01460
  Epoch 022 - train 0.60319 | val 1.12652
  Classification -> best τ=0.345 (val F1=0.3663)
  Directional -> Accuracy: 0.5625, MCC: 0.0912, F1: 0.6410

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.64585 | val 1.70298
  Epoch 020 - train 0.57215 | val 2.59386
  Epoch 022 - train 0.58017 | val 2.59197
  Classification -> best τ=0.490 (val F1=0.2875)
  Directional -> Accuracy: 0.6327, MCC: 0.2754, F1: 0.5500

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.66524 | val 0.84669
  Epoch 020 - train 0.59089 | val 1.17280
  Epoch 022 - train 0.61302 | val 1.13020
  Classification -> best τ=0.515 (val F1=0.1678)
  Directional -> Accuracy: 0.5370, MCC: 0.0771, F1: 0.5283

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.71340 | val 2.07420
  Epoch 020 - train 0.54879 | val 3.08718
  Epoch 021 - train 0.53963 | val 2.92726
  Classification -> best τ=0.495 (val F1=0.3451)
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.71509 | val 0.70883
  Epoch 020 - train 0.61805 | val 0.72406
  Epoch 027 - train 0.56148 | val 0.71264
  Classification -> best τ=0.405 (val F1=0.4973)
  Directional -> Accuracy: 0.4000, MCC: 0.1000, F1: 0.5091

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.66684 | val 1.16770
  Epoch 020 - train 0.61526 | val 1.74710
  Epoch 021 - train 0.60290 | val 1.72532
  Classification -> best τ=0.500 (val F1=0.1485)
  Directional -> Accuracy: 0.5139, MCC: 0.0546, F1: 0.6602

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.70092 | val 0.67550
  Epoch 020 - train 0.62698 | val 0.69560
  Epoch 030 - train 0.62125 | val 0.73680
  Classification -> best τ=0.370 (val F1=0.2138)
  Directional -> Accuracy: 0.4884, MCC: -0.0051, F1: 0.0833

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.67839 | val 0.67367
  Epoch 020 - train 0.52520 | val 0.70024
  Epoch 030 - train 0.52087 | val 0.73130
  Classification -> best τ=0.385 (val F1=0.4181)
  Directional -> Accuracy: 0.5641, MCC: 0.0174, F1: 0.6909

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.66868 | val 0.82145
  Epoch 020 - train 0.61153 | val 1.32215
  Epoch 021 - train 0.62119 | val 1.26648
  Classification -> best τ=0.555 (val F1=0.2530)
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.69405 | val 0.95654
  Epoch 020 - train 0.70183 | val 1.22964
  Epoch 022 - train 0.67381 | val 0.87993
  Classification -> best τ=0.450 (val F1=0.2067)
  Directional -> Accuracy: 0.5472, MCC: 0.0000, F1: 0.7073

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.66415 | val 0.96610
  Epoch 020 - train 0.64571 | val 1.32522
  Epoch 021 - train 0.66382 | val 1.33593
  Classification -> best τ=0.555 (val F1=0.3305)
  Directional -> Accuracy: 0.5741, MCC: 0.1622, F1: 0.6462

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.65987 | val 1.27913
  Epoch 020 - train 0.65858 | val 0.90930
  Epoch 030 - train 0.57174 | val 0.91089
  Classification -> best τ=0.565 (val F1=0.2828)
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.72369 | val 1.98770
  Epoch 020 - train 0.61594 | val 1.56873
  Epoch 021 - train 0.61586 | val 1.69966
  Classification -> best τ=0.590 (val F1=0.1354)
  Directional -> Accuracy: 0.5094, MCC: 0.0113, F1: 0.6061

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.68492 | val 0.70872
  Epoch 020 - train 0.65830 | val 0.75273

[I 2026-02-19 07:35:53,691] Trial 80 finished with value: 0.2678533257469475 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiLSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.0034002636632532468, 'weight_decay': 6.837021272311225e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.6293293800063144, 'early_stopping_min_delta': 0.00015047487802641063}. Best is trial 74 with value: 0.2805031313371805.

  Epoch 027 - train 0.67251 | val 0.70588
  Classification -> best τ=0.425 (val F1=0.2758)
  Directional -> Accuracy: 0.4828, MCC: 0.0619, F1: 0.6341

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 25)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained', 'best_threshold', 'best_threshold_metric']
[DEBUG] val_mcc: 0.2678533257469475
Saved Optuna results to results/benchmarking/classification/optuna_tuning_base_1H.csv