# Benchmarking Results from Classification and Regression

#### Set Up

In [1]:
import pandas as pd
import numpy as np
import site
import os

In [2]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import TimeSeriesSplit
from sklearn.utils.class_weight import compute_class_weight

from sklearn.metrics import (
    precision_score, recall_score, f1_score, matthews_corrcoef,
    mean_squared_error, mean_absolute_error, r2_score, confusion_matrix
)

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader
from torch.optim import Adam
from torch.optim.lr_scheduler import ReduceLROnPlateau
from contextlib import nullcontext

import random

from unicodedata import bidirectional

### Utility Classes and Functions

In [3]:
def set_global_seeds(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seeds(42)

# Datasets
class SequenceDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

class OrdinalSequenceDataset(Dataset):
    def __init__(self, X, T):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.T = torch.tensor(T, dtype=torch.float32)

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        return self.X[idx], self.T[idx]

def make_cumulative_targets(y_int, K):
    y = y_int.reshape(-1, 1)
    ks = np.arange(K-1).reshape(1, -1)
    return (y > ks).astype(np.float32)

def decode_ordinal(probs, thr=0.5):
    return (probs >= thr).sum(axis=1)

# Models
class OrdinalHeadCORN(nn.Module):
    def __init__(self, in_dim, K):
        super().__init__()
        self.fc = nn.Linear(in_dim, K-1)

    def forward(self, h):
        return self.fc(h)


class OrdinalHeadCORAL(nn.Module):
    def __init__(self, in_dim, K):
        super().__init__()
        self.w = nn.Linear(in_dim, 1, bias=False)
        self._beta = nn.Parameter(torch.zeros(K-1))
        self.softplus = nn.Softplus()

    def forward(self, h):
        base = self.w(h)
        deltas = self.softplus(self._beta)
        b = torch.cumsum(deltas, dim=0)
        return base - b



class RNNHead(nn.Module):
    # Shared head:
    #   - RNN stack (LSTM/GRU, uni/bi)
    #   - BatchNorm + Dense(32, ReLU) + Dropout
    #   - Output layer (1 unit): linear (regression) or logits (classification)
    def __init__(self, input_size, rnn_type='LSTM', bidirectional=False, problem_type='classification',
                 n_classes=6, ordinal_head='coral', hidden1=128, hidden2=64, num_layers=1,
                 inter_rnn_drop=0.1, dropout=0.3, use_layernorm=False):
        super().__init__()
        self.problem_type = problem_type
        self.bidirectional = bidirectional
        self.rnn_type = rnn_type.upper()
        self.n_classes = n_classes
        self.ordinal_head = ordinal_head
        self.num_layers = int(num_layers)
        self.hidden1 = int(hidden1)
        self.hidden2 = int(hidden2)

        if self.num_layers not in (1, 2):
            raise ValueError("num_layers must be 1 or 2")

        rnn_cls = {'LSTM': nn.LSTM, 'GRU': nn.GRU}[('GRU' if 'GRU' in self.rnn_type else 'LSTM')]

        self.rnn1 = rnn_cls(
            input_size=input_size, hidden_size=self.hidden1, num_layers=1,
            batch_first=True, dropout=0.0, bidirectional=bidirectional
        )

        self.inter_rnn_drop = nn.Dropout(float(inter_rnn_drop))

        self.rnn2 = None
        if self.num_layers == 2:
            self.rnn2 = rnn_cls(
                input_size=self.hidden1*(2 if bidirectional else 1), hidden_size=self.hidden2, num_layers=1,
                batch_first=True, dropout=0.0, bidirectional=bidirectional
            )
            feat_dim = self.hidden2*(2 if bidirectional else 1)
        else:
            feat_dim = self.hidden1*(2 if bidirectional else 1)

        if use_layernorm:
            self.bn = nn.LayerNorm(feat_dim)
        else:
            self.bn = nn.BatchNorm1d(feat_dim)
        self.fc = nn.Linear(feat_dim, 32)
        self.drop = nn.Dropout(float(dropout))
        if self.problem_type == 'multiclass':
            head = self.ordinal_head.lower() if isinstance(self.ordinal_head, str) else 'coral'
            if head == 'corn':
                self.out = OrdinalHeadCORN(32, self.n_classes)
            else:
                self.out = OrdinalHeadCORAL(32, self.n_classes)
        else:
            self.out = nn.Linear(32, 1)

    def forward(self, x):
        # x: [B, T, F]
        out, _ = self.rnn1(x)
        if self.num_layers == 2:
            out = self.inter_rnn_drop(out)   # inter-layer dropout (sequence-wise)
            out, _ = self.rnn2(out)
        # take last timestep: [B, T, H] -> [B, H]
        out = out[:, -1, :]
        out = self.bn(out)
        out = F.relu(self.fc(out))
        out = self.drop(out)
        out = self.out(out)  # shape [B,1]
        return out  # regression: raw; classification: logits


def build_model(input_shape, model_type='LSTM', problem_type='regression', n_classes=6, ordinal_head='coral',
                hidden1=128, hidden2=64, num_layers=2, inter_rnn_drop=0.1, dropout=0.3, use_layernorm=False):
    seq_len, n_features = input_shape
    model_type = model_type.upper()
    kwargs = dict(
        problem_type=problem_type,
        n_classes=n_classes,
        ordinal_head=ordinal_head,
        hidden1=hidden1,
        hidden2=hidden2,
        num_layers=num_layers,
        inter_rnn_drop=inter_rnn_drop,
        dropout=dropout,
        use_layernorm=use_layernorm,
    )
    if model_type == 'LSTM':
        return RNNHead(n_features, rnn_type='LSTM', bidirectional=False, **kwargs)
    elif model_type == 'BILSTM':
        return RNNHead(n_features, rnn_type='LSTM', bidirectional=True, **kwargs)
    elif model_type == 'GRU':
        return RNNHead(n_features, rnn_type='GRU', bidirectional=False, **kwargs)
    elif model_type == 'BIGRU':
        return RNNHead(n_features, rnn_type='GRU', bidirectional=True, **kwargs)
    else:
        raise ValueError("Model type must be one of: ['LSTM','BiLSTM','GRU','BiGRU']")

# Early Stopping (PyTorch)
class EarlyStopper:
    def __init__(self, patience=15, min_delta=0.0, restore_best=True):
        self.patience = patience
        self.min_delta = min_delta
        self.restore_best = restore_best
        self.best_loss = float('inf')
        self.counter = 0
        self.best_state = None

    def step(self, val_loss, model):
        improved = (self.best_loss - val_loss) > self.min_delta
        if improved:
            self.best_loss = val_loss
            self.counter = 0
            if self.restore_best:
                # Deep copy state dict
                self.best_state = {k: v.detach().clone() for k, v in model.state_dict().items()}
        else:
            self.counter += 1
        return self.counter >= self.patience

    def restore(self, model):
        if self.restore_best and self.best_state is not None:
            model.load_state_dict(self.best_state)

In [4]:
def edge_labels_from_edges(edges, decimals=1):
    labels = []
    C = len(edges) - 1
    for i in range(C):
        lo, hi = edges[i], edges[i+1]
        if i == 0:
            labels.append(f"≤ {hi*100:.{decimals}f}%")
        elif i == C - 1:
            labels.append(f"> {lo*100:.{decimals}f}%")
        else:
            labels.append(f"({lo*100:.{decimals}f}%,{hi*100:.{decimals}f}%]")
    return labels

def pct_return(series, h):
    return series.shift(-h) / series - 1.0

def safe_quantile_edges(x, n_classes=6):
    qs = np.linspace(0, 1, n_classes + 1)
    edges = np.quantile(x, qs)
    for i in range(1, len(edges)):
        if edges[i] <= edges[i-1]:
            edges[i] = np.nextafter(edges[i-1], np.inf)
    return edges

def bucketize_with_edges(x, edges):
    inner = edges[1:-1]
    return np.digitize(x, inner, right=True).astype(int)

@torch.no_grad()
def collect_logits(model, loader, device):
    model.eval()
    chunks = []
    for xb, _ in loader:
        xb = xb.to(device)
        chunks.append(model(xb).detach().cpu())
    return torch.cat(chunks, dim=0)

def find_taus_per_threshold(Z_val, y_val_idx, grid=np.linspace(0, 1, 100)):
    if isinstance(Z_val, torch.Tensor):
        Z_val = Z_val.numpy()
    P_val = 1.0 / (1.0 + np.exp(-Z_val))
    P_rep = monotone_repair_numpy(P_val)
    K_1 = P_rep.shape[1]
    best_taus = np.full(K_1, 0.5, dtype=np.float32)
    for k in range(K_1):
        best_f1, best_tau = -1.0, 0.5
        for tau in grid:
            y_hat = decode_ordinal_with_taus(P_rep, taus_override={k: tau})
            f1 = f1_score(y_val_idx, y_hat, average='macro', zero_division=0)
            if f1 > best_f1:
                best_f1, best_tau = f1, tau
        best_taus[k] = best_tau
    return best_taus

def monotone_repair_numpy(P):
    P = np.asarray(P).copy()
    for k in range(P.shape[1] - 2, -1, -1):
        P[:, k] = np.maximum(P[:, k], P[:, k+1])
    return P

def decode_ordinal_with_taus(P_rep, taus=None, taus_override=None):
    N, K_1 = P_rep.shape
    if taus is None:
        taus = np.full(K_1, 0.5, dtype=np.float32)
    if taus_override:
        taus = taus.copy()
        for k, v in taus_override.items():
            taus[k] = v
    comp = (P_rep >= taus.reshape(1, -1)).astype(np.int32)
    return comp.sum(axis=1).astype(np.int64)

def ordinal_to_class_probs(P_rep):
    N, K_1 = P_rep.shape
    K = K_1 + 1
    Pc = np.empty((N, K), dtype=np.float32)
    Pc[:, 0] = 1.0 - P_rep[:, 0]
    for c in range(1, K - 1):
        Pc[:, c] = np.clip(P_rep[:, c-1] - P_rep[:, c], 0.0, 1.0)
    Pc[:, K - 1] = P_rep[:, K_1 - 1]
    s = Pc.sum(axis=1, keepdims=True)
    return Pc / np.maximum(s, 1e-8)


def best_threshold_from_val(y_true, y_scores, metric='f1', grid=None):
    """
    Sweep probability thresholds on validation scores to maximize a metric.
    metric can be 'f1', 'mcc', 'accuracy', or a callable(y_true,y_pred)->float.
    Returns (best_threshold, best_metric_value).
    """
    y_true = np.asarray(y_true).astype(int)
    y_scores = np.asarray(y_scores).astype(float)
    if grid is None:
        grid = np.linspace(0.05, 0.95, 181)
    metric_fn = None
    if callable(metric):
        metric_fn = metric
    else:
        name = str(metric).lower()
        if name == 'f1':
            metric_fn = lambda yt, yp: f1_score(yt, yp, zero_division=0)
        elif name == 'mcc':
            metric_fn = lambda yt, yp: matthews_corrcoef(yt, yp)
        elif name in ('acc', 'accuracy'):
            metric_fn = lambda yt, yp: (yt == yp).mean()
        else:
            raise ValueError(f"Unsupported metric '{metric}'")
    best_thr = 0.5
    best_val = -np.inf
    for thr in grid:
        preds = (y_scores >= thr).astype(int)
        val = metric_fn(y_true, preds)
        if val > best_val + 1e-12 or (abs(val - best_val) <= 1e-12 and thr < best_thr):
            best_val = float(val)
            best_thr = float(thr)
    return best_thr, best_val

## Stock Prediction Pipeline

In [ ]:
class StockPredictionPipeline:
    def __init__(self, df, feature_columns, model_type='LSTM', sequence_length=24, problem_type='regression', horizon_steps=1, n_classes=6, ordinal_head='coral', fixed_bucket_edges=None,
                 hidden1=256, hidden2=64, num_layers=1, inter_rnn_drop=0.0, dropout=0.4,
                 batch_size=32, learning_rate=7e-3, weight_decay=2e-3, lr_patience=7, lr_factor=0.5,
                 early_stopping_patience=20, max_epochs=20, use_layernorm=False, huber_delta=1.0, early_stopping_min_delta=0.0):
        self.df = df.copy()
        self.feature_columns = feature_columns
        self.model_type = model_type
        self.sequence_length = sequence_length
        self.problem_type = problem_type
        self.horizon_steps = horizon_steps
        self.results = []
        self.loss_curves = []
        self.n_classes = n_classes
        self.ordinal_head = ordinal_head
        self.hidden1 = hidden1
        self.hidden2 = hidden2
        self.num_layers = num_layers
        self.inter_rnn_drop = inter_rnn_drop
        self.dropout = dropout
        self.batch_size = batch_size
        self.learning_rate = learning_rate
        self.weight_decay = weight_decay
        self.lr_patience = lr_patience
        self.lr_factor = lr_factor
        self.early_stopping_patience = early_stopping_patience
        self.max_epochs = max_epochs
        self.use_layernorm = use_layernorm
        self.huber_delta = huber_delta
        self.early_stopping_min_delta = early_stopping_min_delta
        self.fixed_bucket_edges = None
        if fixed_bucket_edges is not None:
            edges = np.asarray(fixed_bucket_edges, dtype=float)
            if edges.ndim != 1:
                raise ValueError("fixed_bucket_edges must be a 1D sequence of monotonically increasing numbers")
            if edges.size < 2:
                raise ValueError("fixed_bucket_edges must contain at least two values")
            if np.any(np.diff(edges) <= 0):
                raise ValueError("fixed_bucket_edges must be strictly increasing")
            self.n_classes = int(edges.size - 1)
            self.fixed_bucket_edges = edges

        # Validate
        self._validate_inputs()

        # Device & precision
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.mixed_precision = torch.cuda.is_available()

        print(f"Pipeline initialized for a '{self.problem_type}' problem "
              f"with horizon {self.horizon_steps} steps. Device: {self.device}")

    def _validate_inputs(self):
        missing_cols = [col for col in self.feature_columns if col not in self.df.columns]
        if missing_cols:
            raise ValueError(f"Missing feature columns: {missing_cols}")

        if 'close' not in self.df.columns and 'close_price' not in self.df.columns:
            raise ValueError("No 'close' or 'close_price' column found in data")

        valid_models = ['LSTM', 'BiLSTM', 'GRU', 'BiGRU']
        if self.model_type not in valid_models:
            raise ValueError(f"Model type must be one of: {valid_models}")

        if self.problem_type not in ['regression', 'classification', 'multiclass']:
            raise ValueError("Problem type must be 'regression', 'classification', or 'multiclass'")

    def create_target_variable(self, company_data):
        company_data = company_data.copy()
        price_col = 'close' if 'close' in company_data.columns else 'close_price'
        if 'date' in company_data.columns:
            company_data = company_data.sort_values('date')
            
        h = self.horizon_steps

        company_data['target_regression'] = (
            np.log(company_data[price_col].shift(-h)) - np.log(company_data[price_col])
        )
        company_data['target_direction'] = (company_data['target_regression'] > 0).astype(int)
        company_data['ret_h'] = pct_return(company_data[price_col], h)
        if self.problem_type == 'multiclass':
            company_data = company_data.dropna(subset=['ret_h'])
        else:
            company_data = company_data.dropna()
        return company_data

    def create_sequences(self, features, *targets):
        X = []
        y_sequences = [[] for _ in targets]
        for i in range(self.sequence_length, len(features)):
            X.append(features[i-self.sequence_length:i])
            for j, target in enumerate(targets):
                y_sequences[j].append(target[i])
        return (np.array(X),) + tuple(np.array(y) for y in y_sequences)

    def _train_one_epoch(self, model, loader, optimizer, loss_fn, scaler):
        model.train()
        total_loss = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device).view(-1, 1)

            optimizer.zero_grad(set_to_none=True)

            ctx = torch.amp.autocast('cuda') if self.mixed_precision else nullcontext()
            with ctx:
                logits = model(xb)
                loss = loss_fn(logits, yb)

            if self.mixed_precision:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                optimizer.step()

            total_loss += loss.item() * xb.size(0)

        return total_loss / len(loader.dataset)

    @torch.no_grad()
    def _eval_one_epoch(self, model, loader, loss_fn):
        model.eval()
        total_loss = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device).view(-1, 1)
            logits = model(xb)
            loss = loss_fn(logits, yb)
            total_loss += loss.item() * xb.size(0)
        return total_loss / len(loader.dataset)

    def _train_one_epoch_multiclass(self, model, loader, optimizer, scaler, *, pos_weight=None):
        model.train()
        total = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device)
            optimizer.zero_grad(set_to_none=True)
            ctx = torch.amp.autocast('cuda') if self.mixed_precision else nullcontext()
            with ctx:
                logits = model(xb)
                bces = []
                for k in range(logits.shape[1]):
                    w = None if pos_weight is None else pos_weight[k]
                    bce_k = F.binary_cross_entropy_with_logits(logits[:, k], yb[:, k], pos_weight=w)
                    bces.append(bce_k)
                loss = torch.stack(bces).mean()
            if self.mixed_precision:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
            total += float(loss.item()) * xb.size(0)
        return total / len(loader.dataset)

    @torch.no_grad()
    def _eval_one_epoch_multiclass(self, model, loader, pos_weight=None):
        model.eval()
        total = 0.0
        for xb, yb in loader:
            xb = xb.to(self.device)
            yb = yb.to(self.device)
            logits = model(xb)
            bces = []
            for k in range(logits.shape[1]):
                w = None if pos_weight is None else pos_weight[k]
                bce_k = F.binary_cross_entropy_with_logits(logits[:, k], yb[:, k], pos_weight=w)
                bces.append(bce_k)
            loss = torch.stack(bces).mean()
            total += float(loss.item()) * xb.size(0)
        return total / len(loader.dataset)

    @torch.no_grad()
    def _predict(self, model, loader):
        model.eval()
        outs = []
        for xb, _ in loader:
            xb = xb.to(self.device)
            logits = model(xb).squeeze(1).detach().cpu().numpy()
            outs.append(logits)
        return np.concatenate(outs, axis=0)

    def build_model(self, input_shape):
        model = build_model(
            input_shape,
            model_type=self.model_type,
            problem_type=self.problem_type,
            n_classes=self.n_classes,
            ordinal_head=self.ordinal_head,
            hidden1=self.hidden1,
            hidden2=self.hidden2,
            num_layers=self.num_layers,
            inter_rnn_drop=self.inter_rnn_drop,
            dropout=self.dropout,
            use_layernorm=self.use_layernorm
        )
        return model.to(self.device)

    def process_company(self, company_name, company_data, sector):
        print(f"\nProcessing {company_name} ({sector})...")
        try:
            company_data = self.create_target_variable(company_data)

            # Min samples requirement (same heuristic)
            min_samples = self.sequence_length + self.horizon_steps
            if len(company_data) < min_samples:
                print(f"Insufficient data for {company_name} ({len(company_data)} < {min_samples}). Skipping...")
                return None

            if company_data[self.feature_columns].isnull().any().any():
                print(f"Missing values in features for {company_name}. Skipping...")
                return None

            features = company_data[self.feature_columns].values
            target_reg = company_data['target_regression'].values
            target_dir = company_data['target_direction'].values

            # Create sequences
            X_raw, y_reg, y_dir = self.create_sequences(features, target_reg, target_dir)

            # TimeSeriesSplit
            n_splits = min(5, len(X_raw) // 50)
            if n_splits < 3:
                print(f"Insufficient data for proper time series validation for {company_name}. Skipping...")
                return None

            tscv = TimeSeriesSplit(n_splits=n_splits)
            splits = list(tscv.split(X_raw))
            train_idx, test_idx = splits[-1]

            # Train/Val split (last 20% of train for val)
            val_size = int(0.2 * len(train_idx))
            if val_size == 0:
                print(f'Insufficient data for validation split for {company_name}. Skipping...')
                return None
            final_train_idx = train_idx[:-val_size]
            val_idx = train_idx[-val_size:]
            
            if self.horizon_steps > 1:
                print("Adjusting for multi-step horizon...")
                gap = self.horizon_steps
                if len(final_train_idx) > gap:
                    final_train_idx = final_train_idx[:-gap]  # drop last h labels from train
                if len(val_idx) > gap:
                    val_idx = val_idx[gap:]  # drop last h labels from val
            if len(final_train_idx) == 0 or len(val_idx) == 0:
                print(f'Insufficient data after horizon adjustment for {company_name}. Skipping...')
                return None

            X_train_raw, X_val_raw, X_test_raw = X_raw[final_train_idx], X_raw[val_idx], X_raw[test_idx]
            
            F = X_raw.shape[-1]
            feat_scaler = StandardScaler()
            X_train = feat_scaler.fit_transform(X_train_raw.reshape(-1, F)).reshape(X_train_raw.shape)
            X_val   = feat_scaler.transform(X_val_raw.reshape(-1, F)).reshape(X_val_raw.shape)
            X_test  = feat_scaler.transform(X_test_raw.reshape(-1, F)).reshape(X_test_raw.shape)

            if self.problem_type == 'multiclass':
                if 'ret_h' not in company_data.columns:
                    raise RuntimeError("Expected 'ret_h' for ordinal targets but it was missing.")
                ret_full = company_data['ret_h'].values
                ret_seq_full = ret_full[self.sequence_length:]

                ret_train = ret_seq_full[final_train_idx]
                ret_val = ret_seq_full[val_idx]
                ret_test = ret_seq_full[test_idx]

                if self.fixed_bucket_edges is not None:
                    edges = self.fixed_bucket_edges
                    if int(edges.shape[0] - 1) != self.n_classes:
                        raise ValueError("fixed_bucket_edges length must match n_classes+1")
                else:
                    edges = safe_quantile_edges(ret_train, n_classes=self.n_classes)
                edges = np.asarray(edges, dtype=float)
                K = int(edges.shape[0] - 1)
                label_names = edge_labels_from_edges(edges, decimals=1)

                y_bucket = bucketize_with_edges(ret_seq_full, edges).astype(np.int64)
                y_train = y_bucket[final_train_idx]
                y_val = y_bucket[val_idx]
                y_test = y_bucket[test_idx]

                T_train = make_cumulative_targets(y_train.astype(np.int64), K)
                T_val = make_cumulative_targets(y_val.astype(np.int64), K)
                T_test = make_cumulative_targets(y_test.astype(np.int64), K)

                train_ds = OrdinalSequenceDataset(X_train, T_train)
                val_ds = OrdinalSequenceDataset(X_val, T_val)
                test_ds = OrdinalSequenceDataset(X_test, T_test)

                train_loader = DataLoader(train_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)
                val_loader = DataLoader(val_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)
                test_loader = DataLoader(test_ds, batch_size=self.batch_size, shuffle=False, drop_last=False, num_workers=0)

                model = self.build_model((self.sequence_length, len(self.feature_columns)))

                pos_rate = T_train.mean(axis=0)
                pos_weight = (1.0 - pos_rate) / np.clip(pos_rate, 1e-6, 1.0)
                pos_weight_tensor = torch.tensor(pos_weight, dtype=torch.float32).to(self.device)

                optimizer = Adam(model.parameters(), lr=self.learning_rate, eps=1e-7, weight_decay=self.weight_decay)
                scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=self.lr_factor, patience=self.lr_patience, min_lr=1e-7)
                early_stopper = EarlyStopper(patience=self.early_stopping_patience, min_delta=self.early_stopping_min_delta, restore_best=True)
                scaler = torch.amp.GradScaler('cuda', enabled=self.mixed_precision)

                max_epochs = self.max_epochs
                best_val = float('inf')
                epochs_trained = 0
                company_loss_rows = []

                for epoch in range(1, max_epochs + 1):
                    train_loss = self._train_one_epoch_multiclass(model, train_loader, optimizer, scaler, pos_weight=pos_weight_tensor)
                    val_loss = self._eval_one_epoch_multiclass(model, val_loader, pos_weight=pos_weight_tensor)
                    scheduler.step(val_loss)
                    stop = early_stopper.step(val_loss, model)
                    epochs_trained = epoch

                    row = {
                        'company': company_name,
                        'sector': sector,
                        'model_type': self.model_type,
                        'problem_type': self.problem_type,
                        'sequence_length': self.sequence_length,
                        'horizon_steps': self.horizon_steps,
                        'epoch': epoch,
                        'train_loss': float(train_loss),
                        'val_loss': float(val_loss),
                        'train_samples': len(X_train),
                        'val_samples': len(X_val),
                        'test_samples': len(X_test),
                    }

                    company_loss_rows.append(row)
                    self.loss_curves.append(row)

                    if epoch % 10 == 0 or stop:
                        print(f"  Epoch {epoch:03d} - train {train_loss:.5f} | val {val_loss:.5f}")

                    if stop:
                        break

                early_stopper.restore(model)

                Z_val = collect_logits(model, val_loader, self.device)
                taus = find_taus_per_threshold(Z_val, y_val.astype(np.int64))
                P_cum_val = torch.sigmoid(Z_val).cpu().numpy()
                P_rep_val = monotone_repair_numpy(P_cum_val)
                P_class_val = ordinal_to_class_probs(P_rep_val)
                mid_cut = (K // 2)
                y_val_dir = (y_val >= mid_cut).astype(int)
                prob_val_up = P_class_val[:, mid_cut:].sum(axis=1)
                dir_thr, dir_thr_score = best_threshold_from_val(y_val_dir, prob_val_up, metric='mcc')

                Z_test = collect_logits(model, test_loader, self.device)
                P_cum = torch.sigmoid(Z_test).cpu().numpy()
                P_rep = monotone_repair_numpy(P_cum)
                P_class = ordinal_to_class_probs(P_rep)

                y_pred_labels = decode_ordinal_with_taus(P_rep, taus=taus)
                y_true_labels = y_test

                labels = list(range(K))
                cm_counts = confusion_matrix(y_true_labels, y_pred_labels, labels=labels)
                cm_norm = confusion_matrix(y_true_labels, y_pred_labels, labels=labels, normalize='true')

                micro_acc = (y_true_labels == y_pred_labels).mean()
                macro_f1 = f1_score(y_true_labels, y_pred_labels, average='macro', zero_division=0)

                ret_seq_train = ret_seq_full[final_train_idx].astype(np.float32)
                mu_c = np.array([
                    ret_seq_train[y_train == c].mean() if np.any(y_train == c) else 0.0
                    for c in range(K)
                ], dtype=np.float32)

                expected_ret = (P_class * mu_c[None, :]).sum(axis=1)
                expected_ret_mean = float(expected_ret.mean())

                prob_test_up = P_class[:, mid_cut:].sum(axis=1)
                y_true_dir = (y_true_labels >= mid_cut).astype(int)
                y_pred_dir = (prob_test_up >= dir_thr).astype(int)
                precision = precision_score(y_true_dir, y_pred_dir, zero_division=0)
                recall = recall_score(y_true_dir, y_pred_dir, zero_division=0)
                f1 = f1_score(y_true_dir, y_pred_dir, zero_division=0)
                mcc = matthews_corrcoef(y_true_dir, y_pred_dir)
                directional_accuracy = (y_true_dir == y_pred_dir).mean()

                result = {
                    'company': company_name,
                    'sector': sector,
                    'model_type': self.model_type,
                    'problem_type': self.problem_type,
                    'horizon_steps': self.horizon_steps,
                    'macro_f1': macro_f1,
                    'micro_accuracy': micro_acc,
                    'expected_return_mean': expected_ret_mean,
                    'mse': np.nan,
                    'mae': np.nan,
                    'r2': np.nan,
                    'mcc': mcc,
                    'f1': f1,
                    'precision': precision,
                    'recall': recall,
                    'directional_accuracy': directional_accuracy,
                'val_directional_accuracy': val_directional_accuracy if self.problem_type == 'classification' else np.nan,
                'val_mcc': val_mcc if self.problem_type == 'classification' else np.nan,
                'val_f1': val_f1 if self.problem_type == 'classification' else np.nan,
                'val_precision': val_precision if self.problem_type == 'classification' else np.nan,
                'val_recall': val_recall if self.problem_type == 'classification' else np.nan,
                    'n_samples': int(X_raw.shape[0]),
                    'train_samples': int(X_train.shape[0]),
                    'val_samples': int(X_val.shape[0]),
                    'test_samples': int(X_test.shape[0]),
                    'epochs_trained': epochs_trained
                }
                result['confusion_matrix'] = cm_counts.tolist()
                result['confusion_matrix_normalized'] = cm_norm.tolist()
                result['bucket_edges'] = edges.tolist()
                result['bucket_labels'] = label_names
                result['taus'] = taus.astype(float).tolist()
                result['direction_threshold'] = dir_thr
                result['direction_threshold_metric'] = dir_thr_score

                print(f"  Multiclass -> Micro Acc: {micro_acc:.4f}, Macro F1: {macro_f1:.4f}, Expected Return: {expected_ret_mean:.6f}")
                print(f"  Directional threshold -> τ={dir_thr:.3f} (val F1={dir_thr_score:.4f})")

                del model
                torch.cuda.empty_cache()
                return result

            if self.problem_type == 'regression':
                y_train, y_val, y_test = y_reg[final_train_idx], y_reg[val_idx], y_reg[test_idx]
                target_scaler = StandardScaler()
                y_train_scaled = target_scaler.fit_transform(y_train.reshape(-1, 1)).flatten()
                y_val_scaled   = target_scaler.transform(y_val.reshape(-1, 1)).flatten()
                train_target, val_target = y_train_scaled, y_val_scaled
            else:
                y_train, y_val, y_test = y_dir[final_train_idx], y_dir[val_idx], y_dir[test_idx]
                train_target, val_target = y_train, y_val
                target_scaler = None

            # class balance note
            if self.problem_type == 'classification':
                class_ratio = np.mean(y_train)
                if class_ratio < 0.1 or class_ratio > 0.9:
                    print(f"Severe class imbalance for {company_name} ({class_ratio:.3f}). Consider using class weights.")

            # datasets & loaders
            train_ds = SequenceDataset(X_train, train_target)
            val_ds   = SequenceDataset(X_val,   val_target)
            test_ds  = SequenceDataset(X_test,  y_test)

            train_bs = min(self.batch_size, len(train_ds))
            if train_bs < 2:
                print(f'Insufficient training samples for {company_name} (train size={len(train_ds)}). Skipping...')
                return None
            if len(train_ds) % train_bs == 1 and train_bs > 2:
                train_bs -= 1  # avoid batch size 1 for BatchNorm
            val_bs = min(self.batch_size, len(val_ds))
            test_bs = min(self.batch_size, len(test_ds))

            train_loader = DataLoader(train_ds, batch_size=train_bs, shuffle=False,  drop_last=False, num_workers=0)
            val_loader   = DataLoader(val_ds,   batch_size=val_bs,   shuffle=False, drop_last=False, num_workers=0)
            test_loader  = DataLoader(test_ds,  batch_size=test_bs,  shuffle=False, drop_last=False, num_workers=0)

            # build model
            model = self.build_model((self.sequence_length, len(self.feature_columns)))

            # loss functions
            if self.problem_type == 'regression':
                loss_fn = nn.HuberLoss(delta=self.huber_delta)
            else:
                # use BCEWithLogitsLoss for numerical stability (logits input)
                loss_fn = nn.BCEWithLogitsLoss()

            # optimizer & scheduler
            optimizer = Adam(model.parameters(), lr=self.learning_rate, eps=1e-7, weight_decay=self.weight_decay)
            scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=self.lr_factor, patience=self.lr_patience, min_lr=1e-7)
            early_stopper = EarlyStopper(patience=self.early_stopping_patience, min_delta=self.early_stopping_min_delta, restore_best=True)
            scaler = torch.amp.GradScaler('cuda', enabled=self.mixed_precision)

            # training loop
            max_epochs = self.max_epochs
            best_val = float('inf')
            epochs_trained = 0
            company_loss_rows = []  

            for epoch in range(1, max_epochs + 1):
                train_loss = self._train_one_epoch(model, train_loader, optimizer, loss_fn, scaler)
                val_loss = self._eval_one_epoch(model, val_loader, loss_fn)
                scheduler.step(val_loss)
                stop = early_stopper.step(val_loss, model)
                epochs_trained = epoch

                
                row = {
                    'company': company_name,
                    'sector': sector,
                    'model_type': self.model_type,
                    'problem_type': self.problem_type,
                    'sequence_length': self.sequence_length,
                    'horizon_steps': self.horizon_steps,
                    'epoch': epoch,
                    'train_loss': float(train_loss),
                    'val_loss': float(val_loss),
                    'train_samples': len(X_train),
                    'val_samples': len(X_val),
                    'test_samples': len(X_test),
                }
                
                company_loss_rows.append(row)
                self.loss_curves.append(row)

                if epoch % 10 == 0 or stop:
                    print(f"  Epoch {epoch:03d} - train {train_loss:.5f} | val {val_loss:.5f}")

                if stop:
                    break

            # restore best model weights (like Keras restore_best_weights=True)
            early_stopper.restore(model)

            # summarize train/val loss for overfitting checks
            best_train_loss = np.nan
            best_val_loss = np.nan
            final_train_loss = np.nan
            final_val_loss = np.nan
            if company_loss_rows:
                best_val_loss = min(r['val_loss'] for r in company_loss_rows)
                best_train_loss = min(r['train_loss'] for r in company_loss_rows)
                final_train_loss = company_loss_rows[-1]['train_loss']
                final_val_loss = company_loss_rows[-1]['val_loss']

            # predictions
            y_pred_raw = self._predict(model, test_loader)  # raw/regression or logits

            if self.problem_type == 'regression':
                y_pred_unscaled = target_scaler.inverse_transform(y_pred_raw.reshape(-1,1)).flatten() if target_scaler is not None else y_pred_raw
                mse = mean_squared_error(y_test, y_pred_unscaled)
                mae = mean_absolute_error(y_test, y_pred_unscaled)
                r2  = r2_score(y_test, y_pred_unscaled)

                # directional metrics (derived)
                y_test_dir = (y_reg[test_idx] > 0).astype(int)
                y_pred_dir = (y_pred_unscaled > 0).astype(int)
            else:
                # logits -> probs via sigmoid -> learn best threshold on VAL
                val_logits = self._predict(model, val_loader)
                val_probs = 1.0 / (1.0 + np.exp(-val_logits))
                best_thr, best_thr_score = best_threshold_from_val(y_val, val_probs, metric='mcc')
                val_pred_dir = (val_probs >= best_thr).astype(int)
                val_precision = precision_score(y_val, val_pred_dir, zero_division=0)
                val_recall = recall_score(y_val, val_pred_dir, zero_division=0)
                val_f1 = f1_score(y_val, val_pred_dir, zero_division=0)
                val_mcc = matthews_corrcoef(y_val, val_pred_dir)
                val_directional_accuracy = (y_val == val_pred_dir).mean()
                probs = 1.0 / (1.0 + np.exp(-y_pred_raw))
                y_pred_dir = (probs >= best_thr).astype(int)
                y_test_dir = y_test
                mse = mae = r2 = np.nan

            precision = precision_score(y_test_dir, y_pred_dir, zero_division=0)
            recall    = recall_score(y_test_dir, y_pred_dir, zero_division=0)
            f1        = f1_score(y_test_dir, y_pred_dir, zero_division=0)
            mcc       = matthews_corrcoef(y_test_dir, y_pred_dir)
            directional_accuracy = np.mean(y_test_dir == y_pred_dir)

            result = {
                'company': company_name,
                'sector': sector,
                'model_type': self.model_type,
                'problem_type': self.problem_type,
                'horizon_steps': self.horizon_steps,
                'mse': mse,
                'mae': mae,
                'r2': r2,
                'mcc': mcc,
                'f1': f1,
                'precision': precision,
                'recall': recall,
                'directional_accuracy': directional_accuracy,
                'val_directional_accuracy': val_directional_accuracy if self.problem_type == 'classification' else np.nan,
                'val_mcc': val_mcc if self.problem_type == 'classification' else np.nan,
                'val_f1': val_f1 if self.problem_type == 'classification' else np.nan,
                'val_precision': val_precision if self.problem_type == 'classification' else np.nan,
                'val_recall': val_recall if self.problem_type == 'classification' else np.nan,
                'n_samples': int(X_raw.shape[0]),
                'train_samples': int(X_train.shape[0]),
                'val_samples': int(X_val.shape[0]),
                'test_samples': int(X_test.shape[0]),
                'epochs_trained': epochs_trained
            }
            if self.problem_type == 'classification':
                result['best_threshold'] = best_thr
                result['best_threshold_metric'] = best_thr_score

            if self.problem_type == 'regression':
                print(f"  Regression -> MSE: {mse:.6f}, MAE: {mae:.6f}, R²: {r2:.4f}")
            elif self.problem_type == 'classification':
                print(f"  Classification -> best τ={best_thr:.3f} (val F1={best_thr_score:.4f})")
            print(f"  Directional -> Accuracy: {directional_accuracy:.4f}, MCC: {mcc:.4f}, F1: {f1:.4f}")

            # explicit cleanup (PyTorch handles this, but keeps parity with Enrique2025)
            del model
            torch.cuda.empty_cache()

            return result

        except Exception as e:
            print(f"Error processing {company_name}: {str(e)}")
            torch.cuda.empty_cache()
            return None

    def run_pipeline(self):
        company_col = None
        for col_name in ['ticker', 'company', 'symbol']:
            if col_name in self.df.columns:
                company_col = col_name
                break
        if company_col is None:
            company_col = self.df.columns[0]
            print(f"Warning: Using '{company_col}' as company identifier column")

        companies = self.df[company_col].unique()
        print(f"Processing {len(companies)} companies with {self.model_type} model...")
        print(f"Problem type: {self.problem_type}")
        print(f"Sequence length: {self.sequence_length}")
        print(f"Features: {self.feature_columns}")

        successful_companies = 0
        for i, company in enumerate(companies, 1):
            print(f"\n[{i}/{len(companies)}] Processing {company}...")
            company_data = self.df[self.df[company_col] == company].copy()
            sector = company_data['sector'].iloc[0] if 'sector' in company_data.columns else 'Unknown'
            result = self.process_company(company, company_data, sector)
            if result:
                self.results.append(result)
                successful_companies += 1

        print(f"\n{'='*80}")
        print(f"Pipeline completed: {successful_companies}/{len(companies)} companies processed successfully")
        print(f"{'='*80}")

        if self.results:
            self.results_df = pd.DataFrame(self.results)
            return self.results_df
        else:
            print("No companies were processed successfully!")
            return pd.DataFrame()


    def analyze_results(self):
        if not hasattr(self, 'results_df') or self.results_df.empty:
            print("No results to analyze!")
            return None

        df = self.results_df
        analysis = {}

        print("" + "="*80)
        print("STOCK PREDICTION PIPELINE RESULTS")
        print("="*80)
        print(f"Model: {self.model_type} | Problem: {self.problem_type}")
        print(f"Companies analyzed: {len(df)}")
        print(f"Average samples per company: {df['n_samples'].mean():.0f}")

        print("" + "="*50)
        print("OVERALL PERFORMANCE")
        print("="*50)
        if self.problem_type == 'regression':
            print(f"Mean Squared Error:     {df['mse'].mean():.6f} (±{df['mse'].std():.6f})")
            print(f"Mean Absolute Error:    {df['mae'].mean():.6f} (±{df['mae'].std():.6f})")
            print(f"R² Score:              {df['r2'].mean():.4f} (±{df['r2'].std():.4f})")
        if self.problem_type == 'multiclass' and 'micro_accuracy' in df.columns:
            print(f"Micro Accuracy:         {df['micro_accuracy'].mean():.4f} (±{df['micro_accuracy'].std():.4f})")
            print(f"Macro F1 Score:         {df['macro_f1'].mean():.4f} (±{df['macro_f1'].std():.4f})")
            if 'expected_return_mean' in df.columns:
                print(f"Expected Return:        {df['expected_return_mean'].mean():.6f} (±{df['expected_return_mean'].std():.4f})")

        print(f"Directional Accuracy:   {df['directional_accuracy'].mean():.4f} (±{df['directional_accuracy'].std():.4f})")
        print(f"Matthews Correlation:   {df['mcc'].mean():.4f} (±{df['mcc'].std():.4f})")
        print(f"F1 Score:              {df['f1'].mean():.4f} (±{df['f1'].std():.4f})")
        print(f"Precision:             {df['precision'].mean():.4f} (±{df['precision'].std():.4f})")
        print(f"Recall:                {df['recall'].mean():.4f} (±{df['recall'].std():.4f})")

        if self.problem_type == 'multiclass' and 'expected_return_mean' in df.columns:
            print("" + "="*50)
            print("TOP 10 BY EXPECTED RETURN (mean)")
            print("="*50)
            top_er = df.nlargest(10, 'expected_return_mean')
            for _, row in top_er.iterrows():
                print(f"{row['company']:<20} | {row['sector']:<15} | E[r]_mean: {row['expected_return_mean']:.4e} | Macro-F1: {row['macro_f1']:.3f}")

        if 'sector' in df.columns and df['sector'].nunique() > 1:
            print("" + "="*50)
            print("PERFORMANCE BY SECTOR")
            print("="*50)
            sector_stats = df.groupby('sector').agg({
                'directional_accuracy': ['mean', 'std', 'count'],
                'mcc': ['mean', 'std'],
                'r2': 'mean' if self.problem_type == 'regression' else lambda x: np.nan,
                'mae': 'mean' if self.problem_type == 'regression' else lambda x: np.nan
            }).round(4)
            sector_stats.columns = ['_'.join(col).strip() if col[1] else col[0] for col in sector_stats.columns]
            sector_stats = sector_stats.sort_values('directional_accuracy_mean', ascending=False)
            for sector, row in sector_stats.iterrows():
                print(f"{sector:<20} | Acc: {row['directional_accuracy_mean']:.3f}±{row['directional_accuracy_std']:.3f} | "
                      f"MCC: {row['mcc_mean']:.3f} | Companies: {int(row['directional_accuracy_count'])}")

        print("" + "="*50)
        print("TOP 10 PERFORMERS (by Directional Accuracy)")
        print("="*50)
        top_performers = df.nlargest(10, 'directional_accuracy')
        for _, row in top_performers.iterrows():
            print(f"{row['company']:<20} | {row['sector']:<15} | "
                  f"Acc: {row['directional_accuracy']:.3f} | MCC: {row['mcc']:.3f}")

        return analysis

    def save_results(self, results, output_dir='results/benchmarking'):
        if results is not None and not results.empty:
            model_name = self.model_type

            if self.problem_type == 'regression':
                out_dir = os.path.join(output_dir, 'regression')
            elif self.problem_type == 'classification':
                out_dir = os.path.join(output_dir, 'classification')
            else:
                out_dir = os.path.join(output_dir, 'multiclass')

            os.makedirs(out_dir, exist_ok=True)

            output_path = os.path.join(out_dir, f"{model_name}.csv")

            results.to_csv(output_path, index=False)
            print(f"Results saved to {output_path}")
        else:
            print("No results to save.")
            
    def get_loss_curves_df(self):
        if not self.loss_curves:
            print("No loss curves logged yet.")
            return pd.DataFrame()
        return pd.DataFrame(self.loss_curves)

    def save_loss_curves(self, out_path='results/benchmarking/'):
        df = self.get_loss_curves_df()
        if df.empty:
            print("No loss curves to save.")
            return
        if self.problem_type == 'regression':
            out_path = os.path.join(out_path, 'regression', f"{self.model_type}_loss_curves.csv")
        elif self.problem_type == 'classification':
            out_path = os.path.join(out_path, 'classification', f"{self.model_type}_loss_curves.csv")
        else:
            out_path = os.path.join(out_path, 'multiclass', f"{self.model_type}_loss_curves.csv")
            
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        
        df.to_csv(out_path, index=False)
        print(f"Loss curves saved to {out_path}")

    def get_feature_importance_analysis(self):
        print("Feature importance analysis not implemented yet.")
        print("Consider implementing SHAP values or permutation importance for better insights.")
        return None

## Data Preparation

In [6]:
master_df = pd.read_parquet('../data/dataset/ta_nlp_sector.parquet')

In [7]:
master_df.columns

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'ticker',
       'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
       'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
       'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'ret_1d',
       'roll_ret_1d', 'roll_ret_5d', 'roll_ret_20d', 'text', 'sentiment',
       'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
       'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
       'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
       'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
       'emotion_surprize_pct', 'positive_emotion', 'negative_emotion',
       'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct',
       'uncertainty_emotion_pct', 'stance_label', 'finbert_label',
       'stance_score', 'finbert_score', 'finbert_up', 'finbert_down',
       'finbert_neutral', 'sector', 'company_name', 'sector_open_mean',
       'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
       'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
       'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector',
       'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
       'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
       'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
       'market_close', 'sector_rel_strength', 'sector_dispersion_1d'],
      dtype='object')

In [8]:
master_df

,date,open,high,low,close,adj_close,volume,ticker,ema_12,ema_26,...,macd_12_26_9_sector,macdh_12_26_9_sector,macds_12_26_9_sector,rsi_14_sector,sector_bb_upper,sector_bb_middle,sector_bb_lower,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-09-04,95.108574,96.448570,94.928574,96.424286,87.121140,91973000.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1464.800169,NaN,NaN
1,2012-09-05,96.510002,96.621429,95.657143,95.747147,86.509338,84093800.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,1481.232189,NaN,0.006548
2,2012-09-06,96.167145,96.898575,95.828575,96.610001,87.288956,97799100.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,28.755774,NaN,NaN,NaN,1502.627054,NaN,0.006476
3,2012-09-07,96.864288,97.497147,96.538574,97.205711,87.827171,82416600.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,28.562466,NaN,NaN,NaN,1506.971629,NaN,0.008604
4,2012-09-10,97.207146,97.612854,94.585716,94.677139,85.542564,121999500.0,AAPL,NaN,NaN,...,NaN,NaN,NaN,22.507443,NaN,NaN,NaN,1503.735325,NaN,0.012007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108587,2017-08-28,76.900002,76.940002,76.260002,76.470001,76.470001,8229700.0,XOM,77.187452,78.267858,...,-0.111192,0.016355,-0.127548,53.634155,63.049962,61.01430,58.978638,3101.328695,-0.007883,0.005228
108588,2017-08-29,76.209999,76.489998,76.080002,76.449997,76.449997,7060400.0,XOM,77.073998,78.133202,...,-0.067027,0.048417,-0.115443,54.205103,62.862103,60.94445,59.026797,3102.507723,-0.016661,0.002030
108589,2017-08-30,76.239998,76.449997,76.059998,76.099998,76.099998,8218000.0,XOM,76.924151,77.982594,...,-0.037643,0.062240,-0.099883,53.126723,62.639604,60.86875,59.097896,3128.753695,-0.017629,0.004873
108590,2017-08-31,76.269997,76.489998,76.050003,76.330002,76.330002,15641700.0,XOM,76.832744,77.860180,...,0.013408,0.090633,-0.077225,57.342960,62.525437,60.83190,59.138363,3141.201722,-0.008376,0.006185
108591,2017-09-01,76.370003,76.849998,76.320000,76.570000,76.570000,7340800.0,XOM,76.792322,77.764611,...,0.088512,0.132590,-0.044078,62.040301,62.426369,60.80760,59.188831,3136.813139,-0.001766,0.007085

In [9]:
columns_to_check = [
                    'sentiment',
                    
                    'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
                    'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
                    'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
                    'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
                    'emotion_surprize_pct', 
                    
                    'positive_emotion', 'negative_emotion','uncertainty_emotion', 
                    'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct', 
                    
                    'stance_label', 'stance_score', 
                    
                    'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
                    'finbert_neutral', 
                    
                    'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
                    'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
                    'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
                    
                    'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
                    'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
                    'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
                    'market_close', 'sector_rel_strength', 'sector_dispersion_1d'
                ]

print(f"Initial master_df shape: {master_df.shape}")

master_df = master_df.dropna(subset=columns_to_check)

print(f"After dropping NaNs in selected columns, master_df shape: {master_df.shape}")

master_df.reset_index(drop=True, inplace=True)

display(master_df)

Initial master_df shape: (108592, 80)
After dropping NaNs in selected columns, master_df shape: (104476, 80)

,date,open,high,low,close,adj_close,volume,ticker,ema_12,ema_26,...,macd_12_26_9_sector,macdh_12_26_9_sector,macds_12_26_9_sector,rsi_14_sector,sector_bb_upper,sector_bb_middle,sector_bb_lower,market_close,sector_rel_strength,sector_dispersion_1d
0,2012-11-14,77.928574,78.207146,76.597145,76.697144,69.613815,119292600.0,AAPL,80.708033,84.949698,...,-0.913108,-0.181794,-0.731314,27.619972,63.948320,61.465736,58.983152,1484.350654,-0.003089,0.006800
1,2012-11-15,76.790001,77.071426,74.660004,75.088570,68.153778,197477700.0,AAPL,79.843501,84.219244,...,-0.926239,-0.155940,-0.770299,32.479352,63.646173,61.261193,58.876213,1484.574993,0.002003,0.019838
2,2012-11-16,75.028572,75.714287,72.250000,75.382858,68.420891,316723400.0,AAPL,79.157248,83.564697,...,-0.892113,-0.097452,-0.794662,37.450172,63.236926,61.078872,58.920817,1497.780485,0.010276,0.010265
3,2012-11-19,77.244286,81.071426,77.125717,80.818573,73.354591,205829400.0,AAPL,79.412836,83.361280,...,-0.733193,0.049174,-0.782368,51.350390,63.001827,61.010079,59.018330,1506.128807,0.024682,0.018850
4,2012-11-20,81.701431,81.707146,79.225716,80.129997,72.729614,160688500.0,AAPL,79.523169,83.121926,...,-0.579416,0.162361,-0.741778,53.267164,62.959435,60.996029,59.032623,1508.629302,0.025531,0.007554
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104471,2017-08-28,76.900002,76.940002,76.260002,76.470001,76.470001,8229700.0,XOM,77.187452,78.267858,...,-0.111192,0.016355,-0.127548,53.634155,63.049962,61.014300,58.978638,3101.328695,-0.007883,0.005228
104472,2017-08-29,76.209999,76.489998,76.080002,76.449997,76.449997,7060400.0,XOM,77.073998,78.133202,...,-0.067027,0.048417,-0.115443,54.205103,62.862103,60.944450,59.026797,3102.507723,-0.016661,0.002030
104473,2017-08-30,76.239998,76.449997,76.059998,76.099998,76.099998,8218000.0,XOM,76.924151,77.982594,...,-0.037643,0.062240,-0.099883,53.126723,62.639604,60.868750,59.097896,3128.753695,-0.017629,0.004873
104474,2017-08-31,76.269997,76.489998,76.050003,76.330002,76.330002,15641700.0,XOM,76.832744,77.860180,...,0.013408,0.090633,-0.077225,57.342960,62.525437,60.831900,59.138363,3141.201722,-0.008376,0.006185
104475,2017-09-01,76.370003,76.849998,76.320000,76.570000,76.570000,7340800.0,XOM,76.792322,77.764611,...,0.088512,0.132590,-0.044078,62.040301,62.426369,60.807600,59.188831,3136.813139,-0.001766,0.007085

In [10]:
print(master_df.columns)

Index(['date', 'open', 'high', 'low', 'close', 'adj_close', 'volume', 'ticker',
       'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
       'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
       'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'ret_1d',
       'roll_ret_1d', 'roll_ret_5d', 'roll_ret_20d', 'text', 'sentiment',
       'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
       'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
       'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
       'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
       'emotion_surprize_pct', 'positive_emotion', 'negative_emotion',
       'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct',
       'uncertainty_emotion_pct', 'stance_label', 'finbert_label',
       'stance_score', 'finbert_score', 'finbert_up', 'finbert_down',
       'finbert_neutral', 'sector', 'company_name', 'sector_open_mean',
       'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
       'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
       'sector_ret_20d', 'sector_range', 'sector_vol_20d', 'ema_12_sector',
       'ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
       'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
       'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
       'market_close', 'sector_rel_strength', 'sector_dispersion_1d'],
      dtype='object')

In [11]:
feature_columns = [
    'open', 'high', 'low', 'close', 'volume',
    # 'roll_ret_1d', 'roll_ret_5d', 
    # 'roll_ret_20d',
    
    'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9',
    'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3',
    'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv',
]

new_indicator_columns = [
    # 'sentiment',
                    
    # 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
    # 'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
    # 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
    # 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
    # 'emotion_surprize_pct', 
    
    # 'positive_emotion', 'negative_emotion','uncertainty_emotion', 
    # 'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct', 
    
    # 'stance_label', 'stance_score', 
    
    # 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
    # 'finbert_neutral', 
    
    # 'sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
    # 'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
    # 'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
    
    # 'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
    # 'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
    # 'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
    # 'market_close', 'sector_rel_strength', 'sector_dispersion_1d'
]

# feature_columns.extend(new_indicator_columns)



sequence_length=12



all_pipelines = {}
all_results_dfs = {}
all_analyses = {}
fixed_bucket_edges = np.array([-0.08, -0.03, -0.01, 0.0, 0.01, 0.03, 0.08], dtype=float)
n_classes = len(fixed_bucket_edges) - 1
ordinal_head = 'corn'

In [12]:
print(master_df.shape)
master_df = master_df.dropna(subset=feature_columns).sort_values(['ticker','date'])
print(master_df.shape)

(104476, 80)
(104220, 80)

## Pipeline Execution

In [13]:
# print(f"\n{'='*25}\n  RUNNING PIPELINE FOR: GRU\n{'='*25}\n")

# pipeline_GRU = StockPredictionPipeline(
#     df=master_df,
#     feature_columns=feature_columns,
#     model_type='GRU',
#     sequence_length=sequence_length,
#     problem_type='classification',
#     horizon_steps=1,
#     n_classes=n_classes,
#     ordinal_head=ordinal_head,
#     fixed_bucket_edges=fixed_bucket_edges
# )

# results_GRU = pipeline_GRU.run_pipeline()

# loss_df = pipeline_GRU.get_loss_curves_df()

# pipeline_GRU.save_loss_curves('results/benchmarking/')

# if results_GRU is not None and not results_GRU.empty:
#     analysis_GRU = pipeline_GRU.analyze_results()
#     pipeline_GRU.save_results(results_GRU, output_dir='results/benchmarking/')
#     all_pipelines["GRU"] = pipeline_GRU
#     all_results_dfs["GRU"] = results_GRU
#     all_analyses["GRU"] = analysis_GRU

#     print("\nDisplaying first 5 rows of GRU results:")
#     display(results_GRU.head())
# else:
#     print(f"\n[FAILED] Pipeline for GRU did not produce any results.")

# del pipeline_GRU

In [14]:
sentinemt_columns = [
    'sentiment',
]

emotion_columns = [
    'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy',
    'emotion_neutral', 'emotion_sadness', 'emotion_surprize',
    'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct',
    'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct',
    'emotion_surprize_pct',
]

unified_emotion_columns = [
    'positive_emotion', 'negative_emotion','uncertainty_emotion',
    'positive_emotion_pct', 'negative_emotion_pct','uncertainty_emotion_pct',
]

stance_columns = [
    'stance_label', 'stance_score',
]

finbert_columns = [
    'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down',
    'finbert_neutral',
]

sector_columns = ['sector_open_mean', 'sector_high_mean', 'sector_low_mean', 'sector_close_mean',
                  'sector_volume_mean', 'sector_ret_1d', 'sector_ret_5d',
                  'sector_ret_20d', 'sector_range', 'sector_vol_20d', 
                  
                  'ema_12_sector','ema_26_sector', 'ema_50_sector', 'macd_12_26_9_sector',
                  'macdh_12_26_9_sector', 'macds_12_26_9_sector', 'rsi_14_sector',
                  'sector_bb_upper', 'sector_bb_middle', 'sector_bb_lower',
                  'market_close', 'sector_rel_strength', 'sector_dispersion_1d']

In [ ]:
try:
    import optuna
except ImportError:
    import sys
    !{sys.executable} -m pip install optuna
    import optuna
    
from pathlib import Path
from datetime import datetime
    
# Define feature sets to test
feature_sets = {
    'base': feature_columns,
    'sentinment' : feature_columns + sentinemt_columns,
    'emotion' : feature_columns + emotion_columns,
    'unified_emotion': feature_columns + unified_emotion_columns,
    'finbert': feature_columns + finbert_columns,
    'all_nlp': feature_columns + sentinemt_columns + emotion_columns + unified_emotion_columns + stance_columns + finbert_columns,
    # 'sector': feature_columns + sector_columns,
    # 'sector_sentiment': feature_columns + sector_columns + sentinemt_columns,
    # 'sector_emotion': feature_columns + sector_columns + emotion_columns,
    # 'sector_unified_emotion': feature_columns + sector_columns + unified_emotion_columns,
    # 'sector_finbert': feature_columns + sector_columns + finbert_columns,
    # 'sector_all_nlp': feature_columns + sector_columns + sentinemt_columns + emotion_columns + unified_emotion_columns + stance_columns + finbert_columns,
}

def objective(trial):
    params = {
        'problem_type': 'regression',  # or 'classification'
        'feature_set': trial.suggest_categorical('feature_set', list(feature_sets.keys())),
        'model_type': trial.suggest_categorical('model_type', ['LSTM', 'BiLSTM', 'GRU', 'BiGRU']),
        'sequence_length': trial.suggest_int('sequence_length',5, 20, step=5),
        'horizon_steps': trial.suggest_categorical('horizon_steps', [1]),
        'hidden1': trial.suggest_categorical('hidden1', [64, 128, 256]),
        'hidden2': trial.suggest_categorical('hidden2', [32, 64, 128]),
        'num_layers': trial.suggest_categorical('num_layers', [1, 2]),
        'inter_rnn_drop': trial.suggest_float('inter_rnn_drop', 0.0, 0.4, step=0.1),
        'dropout': trial.suggest_float('dropout', 0.0, 0.8, step=0.1),
        'batch_size': trial.suggest_categorical('batch_size', [16, 32, 64]),
        'learning_rate': trial.suggest_float('learning_rate', 1e-6, 1e-2, log=True),
        'weight_decay': trial.suggest_float('weight_decay', 1e-7, 1e-3, log=True),
        'lr_patience': trial.suggest_categorical('lr_patience', [5, 7, 10]),
        'lr_factor': trial.suggest_categorical('lr_factor', [0.4, 0.8]),
        'early_stopping_patience': trial.suggest_categorical('early_stopping_patience', [10, 15, 20]),
        'max_epochs': trial.suggest_categorical('max_epochs', [20, 30, 50]),
        'huber_delta': trial.suggest_float('huber_delta', 0.1, 2.0),
        'early_stopping_min_delta': trial.suggest_float('early_stopping_min_delta', 0.0, 0.01),
    }

    selected_features = feature_sets[params['feature_set']]
    missing_cols = [c for c in selected_features if c not in master_df.columns]
    if missing_cols:
        print(f"Missing columns for feature_set={params['feature_set']}: {missing_cols}")
        return -1.0

    pipeline = StockPredictionPipeline(
        df=master_df,
        feature_columns=selected_features,
        model_type=params['model_type'],
        sequence_length=params['sequence_length'],
        problem_type=params['problem_type'],
        horizon_steps=params['horizon_steps'],
        n_classes=n_classes,
        ordinal_head=ordinal_head,
        fixed_bucket_edges=fixed_bucket_edges,
        hidden1=params['hidden1'],
        hidden2=params['hidden2'],
        num_layers=params['num_layers'],
        inter_rnn_drop=params['inter_rnn_drop'],
        dropout=params['dropout'],
        batch_size=params['batch_size'],
        learning_rate=params['learning_rate'],
        weight_decay=params['weight_decay'],
        lr_patience=params['lr_patience'],
        lr_factor=params['lr_factor'],
        early_stopping_patience=params['early_stopping_patience'],
        max_epochs=params['max_epochs'],
        huber_delta=params['huber_delta'],
        early_stopping_min_delta=params['early_stopping_min_delta']
    )

    results_df = pipeline.run_pipeline()
    del pipeline
    torch.cuda.empty_cache()

    if results_df is None or results_df.empty:
        print('[DEBUG] results_df empty or None')
        return -1.0

    print('[DEBUG] results_df shape:', results_df.shape)
    print('[DEBUG] results_df columns:', results_df.columns.tolist())

    # Aggregate validation metrics
    val_f1 = results_df['val_f1'].mean() if 'val_f1' in results_df.columns else np.nan
    if not np.isfinite(val_f1) and 'best_threshold_metric' in results_df.columns:
        val_f1 = results_df['best_threshold_metric'].mean()
    val_mcc = results_df['val_mcc'].mean() if 'val_mcc' in results_df.columns else np.nan
    print('[DEBUG] val_mcc:', val_mcc)
    val_precision = results_df['val_precision'].mean() if 'val_precision' in results_df.columns else np.nan
    val_recall = results_df['val_recall'].mean() if 'val_recall' in results_df.columns else np.nan
    val_dir_acc = results_df['val_directional_accuracy'].mean() if 'val_directional_accuracy' in results_df.columns else np.nan

    trial.set_user_attr('val_f1', float(val_f1))
    trial.set_user_attr('val_mcc', float(val_mcc))
    trial.set_user_attr('val_precision', float(val_precision))
    trial.set_user_attr('val_recall', float(val_recall))
    trial.set_user_attr('val_directional_accuracy', float(val_dir_acc))

    # Primary metric: mean val MCC (classification) or mean MAE (regression)
    if params['problem_type'] == 'classification':
        score = val_mcc
        if not np.isfinite(score):
            return -1.0
        return float(score)
    else:
        # minimize MAE -> maximize negative MAE
        if 'mae' not in results_df.columns:
            return -1.0
        mae = results_df['mae'].mean()
        if not np.isfinite(mae):
            return -1.0
        return float(-mae)


N_TRIALS = 250

# Run study
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=N_TRIALS, timeout=60*60*8)  # 8 hours max
# Collect results
optuna_results = study.trials_dataframe()
# include user attrs
user_attrs = pd.DataFrame([t.user_attrs for t in study.trials])
optuna_results = pd.concat([optuna_results, user_attrs], axis=1)
optuna_results = optuna_results.sort_values('value', ascending=False)
optuna_results

timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
out_path = f'../results/benchmarking/regression/optuna_tuning_NLP_1H.csv'
Path('../results/benchmarking/regression').mkdir(parents=True, exist_ok=True)
optuna_results.to_csv(out_path, index=False)
print(f'Saved Optuna results to {out_path}')

[I 2026-02-23 22:34:51,010] A new study created in memory with name: no-name-9bca0472-e63a-454f-9a7b-2aa32feb6e72

Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15562 | val 0.34990
  Epoch 011 - train 0.16037 | val 0.36200
  Regression -> MSE: 0.000254, MAE: 0.012813, R²: -0.0270
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16268 | val 0.17903
  Epoch 011 - train 0.16205 | val 0.18026
  Regression -> MSE: 0.000694, MAE: 0.019485, R²: -0.0133
  Directional -> Accuracy: 0.5870, MCC: 0.1202, F1: 0.6984

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16705 | val 0.32870
  Epoch 011 - train 0.16503 | val 0.33086
  Regression -> MSE: 0.000311, MAE: 0.014465, R²: -0.0036
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13613 | val 0.36900
  Epoch 011 - train 0.13649 | val 0.37209
  Regression -> MSE: 0.000348, MAE: 0.014546, R²: 0.0049
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16197 | val 0.19308
  Epoch 011 - train 0.15717 | val 0.19685
  Regression -> MSE: 0.000203, MAE: 0.010224, R²: 0.0015
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15692 | val 0.36892
  Epoch 011 - train 0.14533 | val 0.36709
  Regression -> MSE: 0.000565, MAE: 0.018259, R²: -0.0181
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16803 | val 0.24157
  Epoch 011 - train 0.17061 | val 0.25821
  Regression -> MSE: 0.000247, MAE: 0.012336, R²: -0.0059
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13412 | val 0.27820
  Epoch 011 - train 0.14202 | val 0.28113
  Regression -> MSE: 0.000614, MAE: 0.019570, R²: -0.0283
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15359 | val 0.23918
  Epoch 011 - train 0.14899 | val 0.23700
  Regression -> MSE: 0.000384, MAE: 0.016033, R²: -0.0008
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16301 | val 0.28939
  Epoch 011 - train 0.15529 | val 0.26668
  Regression -> MSE: 0.000245, MAE: 0.011606, R²: -0.0162
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15111 | val 0.31565
  Epoch 011 - train 0.14518 | val 0.34363
  Regression -> MSE: 0.000312, MAE: 0.013549, R²: -0.0022
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.16374 | val 0.22485
  Epoch 011 - train 0.15698 | val 0.22692
  Regression -> MSE: 0.000673, MAE: 0.019467, R²: 0.0062
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16478 | val 0.21360
  Epoch 011 - train 0.15691 | val 0.21533
  Regression -> MSE: 0.000139, MAE: 0.009066, R²: -0.0092
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14766 | val 0.25404
  Epoch 017 - train 0.13764 | val 0.27677
  Regression -> MSE: 0.000223, MAE: 0.010563, R²: 0.0098
  Directional -> Accuracy: 0.5902, MCC: 0.3037, F1: 0.7126

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15248 | val 0.48544
  Epoch 011 - train 0.15813 | val 0.47790
  Regression -> MSE: 0.000362, MAE: 0.015898, R²: 0.0007
  Directional -> Accuracy: 0.6154, MCC: 0.2334, F1: 0.4118

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16467 | val 0.21379
  Epoch 011 - train 0.17469 | val 0.23990
  Regression -> MSE: 0.000107, MAE: 0.008061, R²: 0.0058
  Directional -> Accuracy: 0.4714, MCC: 0.1105, F1: 0.0513

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15906 | val 0.33513
  Epoch 011 - train 0.16443 | val 0.34332
  Regression -> MSE: 0.000157, MAE: 0.009910, R²: -0.0074
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16730 | val 0.25528
  Epoch 011 - train 0.16769 | val 0.27116
  Regression -> MSE: 0.000275, MAE: 0.013143, R²: -0.0088
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.15097 | val 0.24815
  Epoch 017 - train 0.14487 | val 0.24184
  Regression -> MSE: 0.000186, MAE: 0.009814, R²: -0.2460
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16634 | val 0.27155
  Epoch 011 - train 0.15943 | val 0.27594
  Regression -> MSE: 0.000260, MAE: 0.011553, R²: -0.1487
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16366 | val 0.23659
  Epoch 011 - train 0.16602 | val 0.23441
  Regression -> MSE: 0.000154, MAE: 0.008883, R²: -0.0777
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15897 | val 0.22955
  Epoch 011 - train 0.15722 | val 0.23186
  Regression -> MSE: 0.000177, MAE: 0.010241, R²: -0.0723
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16867 | val 0.23169
  Epoch 011 - train 0.15936 | val 0.24182
  Regression -> MSE: 0.000089, MAE: 0.007295, R²: -0.0462
  Directional -> Accuracy: 0.4138, MCC: -0.1111, F1: 0.0556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16407 | val 0.24145
  Epoch 011 - train 0.15928 | val 0.24835
  Regression -> MSE: 0.000213, MAE: 0.011057, R²: -0.0071
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14182 | val 0.15943
  Epoch 020 - train 0.12633 | val 0.15978
  Regression -> MSE: 0.000098, MAE: 0.008089, R²: -0.0685
  Directional -> Accuracy: 0.4821, MCC: 0.0114, F1: 0.3830

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16798 | val 0.14787
  Epoch 011 - train 0.18168 | val 0.14856
  Regression -> MSE: 0.000109, MAE: 0.008990, R²: -0.0567
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16234 | val 0.17946
  Epoch 011 - train 0.17241 | val 0.17850
  Regression -> MSE: 0.000233, MAE: 0.012550, R²: -0.0050
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15770 | val 0.22472
  Epoch 017 - train 0.14949 | val 0.23557
  Regression -> MSE: 0.000183, MAE: 0.007826, R²: -0.0989
  Directional -> Accuracy: 0.5789, MCC: 0.1312, F1: 0.6471

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.15353 | val 0.16525
  Epoch 014 - train 0.15904 | val 0.17010
  Regression -> MSE: 0.000234, MAE: 0.011894, R²: 0.0123
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.15780 | val 0.32637
  Epoch 011 - train 0.15954 | val 0.32636
  Regression -> MSE: 0.000230, MAE: 0.009934, R²: 0.0000
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16134 | val 0.25039
  Epoch 011 - train 0.15949 | val 0.25135
  Regression -> MSE: 0.000138, MAE: 0.008282, R²: -0.0218
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.16355 | val 0.24780
  Epoch 011 - train 0.15677 | val 0.24917
  Regression -> MSE: 0.000189, MAE: 0.010343, R²: -0.0017
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13963 | val 0.21525
  Epoch 016 - train 0.13359 | val 0.23057
  Regression -> MSE: 0.000267, MAE: 0.010776, R²: -0.0197
  Directional -> Accuracy: 0.5616, MCC: 0.1295, F1: 0.5789

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15963 | val 0.16698
  Epoch 011 - train 0.14968 | val 0.17188
  Regression -> MSE: 0.000167, MAE: 0.010356, R²: -0.0026
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14229 | val 0.19877
  Epoch 011 - train 0.14153 | val 0.19433
  Regression -> MSE: 0.000177, MAE: 0.010225, R²: 0.0152
  Directional -> Accuracy: 0.5455, MCC: 0.1668, F1: 0.6552

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15248 | val 0.19067
  Epoch 011 - train 0.15498 | val 0.19277
  Regression -> MSE: 0.000345, MAE: 0.012165, R²: -0.0073
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16248 | val 0.12198
  Epoch 011 - train 0.16197 | val 0.12348
  Regression -> MSE: 0.000109, MAE: 0.008093, R²: -0.0395
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15191 | val 0.26406
  Epoch 016 - train 0.14557 | val 0.31598
  Regression -> MSE: 0.000226, MAE: 0.011581, R²: -0.0352
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15836 | val 0.33988
  Epoch 011 - train 0.15090 | val 0.33857
  Regression -> MSE: 0.000090, MAE: 0.007437, R²: -0.1632
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14669 | val 0.15854
  Epoch 011 - train 0.15218 | val 0.15834
  Regression -> MSE: 0.000357, MAE: 0.015899, R²: -0.1599
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.16315 | val 0.12000
  Epoch 011 - train 0.14355 | val 0.12052
  Regression -> MSE: 0.000249, MAE: 0.011525, R²: -0.0205
  Directional -> Accuracy: 0.5000, MCC: 0.0175, F1: 0.4242

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15246 | val 0.27057
  Epoch 011 - train 0.15194 | val 0.27236
  Regression -> MSE: 0.000081, MAE: 0.007012, R²: 0.0013
  Directional -> Accuracy: 0.5467, MCC: 0.0927, F1: 0.4848

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.15559 | val 0.23926
  Epoch 011 - train 0.16214 | val 0.23995
  Regression -> MSE: 0.000306, MAE: 0.014472, R²: 0.0032
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14702 | val 0.22458
  Epoch 011 - train 0.13924 | val 0.22529
  Regression -> MSE: 0.000101, MAE: 0.007098, R²: -0.0233
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17509 | val 0.24047
  Epoch 013 - train 0.15986 | val 0.23762
  Regression -> MSE: 0.000173, MAE: 0.009727, R²: -0.0045
  Directional -> Accuracy: 0.4490, MCC: -0.0167, F1: 0.4906

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14703 | val 0.25781
  Epoch 011 - train 0.14135 | val 0.27102
  Regression -> MSE: 0.000229, MAE: 0.011846, R²: -0.0276
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.15625 | val 0.23301
  Epoch 011 - train 0.15256 | val 0.23284
  Regression -> MSE: 0.000098, MAE: 0.008043, R²: -0.0611
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.17420 | val 0.34075
  Epoch 011 - train 0.17228 | val 0.38631
  Regression -> MSE: 0.000166, MAE: 0.010224, R²: -0.0141
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.15078 | val 0.25330
  Epoch 011 - train 0.15023 | val 0.24890
  Regression -> MSE: 0.000123, MAE: 0.009000, R²: -0.0586
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 22:35:30,932] Trial 0 finished with value: -0.011474062271054221 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.001959448933125866, 'weight_decay': 0.0001867953730941007, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.31113308668719547, 'early_stopping_min_delta': 0.008450644778908391}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.16468 | val 0.32673
  Epoch 011 - train 0.16616 | val 0.31151
  Regression -> MSE: 0.000238, MAE: 0.012478, R²: -0.0034
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.18460 | val 0.28066
  Epoch 020 - train 0.16686 | val 0.31013
  Regression -> MSE: 0.000237, MAE: 0.012224, R²: 0.0068
  Directional -> Accuracy: 0.4933, MCC: 0.0029, F1: 0.5128

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.17836 | val 0.21995
  Epoch 020 - train 0.15946 | val 0.20282
  Regression -> MSE: 0.000695, MAE: 0.019419, R²: 0.0138
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.19233 | val 0.31713
  Epoch 020 - train 0.18664 | val 0.32469
  Regression -> MSE: 0.000342, MAE: 0.015099, R²: -0.0652
  Directional -> Accuracy: 0.4667, MCC: -0.0144, F1: 0.0769

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.16138 | val 0.19015
  Epoch 020 - train 0.15772 | val 0.24874
  Regression -> MSE: 0.000362, MAE: 0.014829, R²: -0.0155
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.17975 | val 0.18351
  Epoch 020 - train 0.17330 | val 0.19892
  Regression -> MSE: 0.000274, MAE: 0.012371, R²: -0.3035
  Directional -> Accuracy: 0.4082, MCC: -0.1932, F1: 0.4727

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.17782 | val 0.31876
  Epoch 020 - train 0.15760 | val 0.34471
  Regression -> MSE: 0.000576, MAE: 0.018478, R²: -0.0031
  Directional -> Accuracy: 0.5333, MCC: 0.0644, F1: 0.3636

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.18624 | val 0.32141
  Epoch 020 - train 0.17894 | val 0.39299
  Regression -> MSE: 0.000255, MAE: 0.012109, R²: -0.0119
  Directional -> Accuracy: 0.5522, MCC: 0.0694, F1: 0.4444

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.17684 | val 0.27865
  Epoch 020 - train 0.17225 | val 0.42160
  Regression -> MSE: 0.000643, MAE: 0.020094, R²: -0.0276
  Directional -> Accuracy: 0.4878, MCC: 0.2003, F1: 0.6316

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.18767 | val 0.27125
  Epoch 020 - train 0.15820 | val 0.26896
  Regression -> MSE: 0.000418, MAE: 0.016443, R²: -0.1174
  Directional -> Accuracy: 0.4681, MCC: -0.1535, F1: 0.1935

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.18704 | val 0.27782
  Epoch 020 - train 0.16702 | val 0.30737
  Regression -> MSE: 0.000248, MAE: 0.012250, R²: 0.0031
  Directional -> Accuracy: 0.4412, MCC: -0.0014, F1: 0.5778

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.16864 | val 0.35660
  Epoch 020 - train 0.15827 | val 0.36841
  Regression -> MSE: 0.000321, MAE: 0.013557, R²: -0.0242
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.18841 | val 0.27566
  Epoch 020 - train 0.18083 | val 0.27236
  Regression -> MSE: 0.000693, MAE: 0.019853, R²: 0.0067
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.18983 | val 0.47564
  Epoch 020 - train 0.18118 | val 0.65621
  Regression -> MSE: 0.000152, MAE: 0.009519, R²: -0.0750
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.16135 | val 0.27054
  Epoch 020 - train 0.15959 | val 0.27516
  Regression -> MSE: 0.000235, MAE: 0.011640, R²: -0.0297
  Directional -> Accuracy: 0.5424, MCC: 0.0838, F1: 0.6087

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.17680 | val 0.50067
  Epoch 020 - train 0.17456 | val 0.53603
  Regression -> MSE: 0.000364, MAE: 0.015909, R²: 0.0079
  Directional -> Accuracy: 0.4600, MCC: -0.0620, F1: 0.4706

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.19992 | val 0.22354
  Epoch 020 - train 0.18668 | val 0.22386
  Regression -> MSE: 0.000109, MAE: 0.007859, R²: -0.0134
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.18951 | val 0.43251
  Epoch 020 - train 0.17724 | val 0.38351
  Regression -> MSE: 0.000150, MAE: 0.009759, R²: -0.0095
  Directional -> Accuracy: 0.5088, MCC: -0.0192, F1: 0.5882

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.18730 | val 0.26281
  Epoch 020 - train 0.16781 | val 0.29166
  Regression -> MSE: 0.000284, MAE: 0.013571, R²: -0.0286
  Directional -> Accuracy: 0.3919, MCC: -0.1591, F1: 0.3284

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.16577 | val 0.25360
  Epoch 020 - train 0.15298 | val 0.25827
  Regression -> MSE: 0.000264, MAE: 0.012573, R²: -0.7414
  Directional -> Accuracy: 0.4127, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.18600 | val 0.31170
  Epoch 020 - train 0.18041 | val 0.30499
  Regression -> MSE: 0.000265, MAE: 0.011615, R²: -0.1785
  Directional -> Accuracy: 0.5479, MCC: 0.2070, F1: 0.3774

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.18894 | val 0.30381
  Epoch 020 - train 0.16695 | val 0.28209
  Regression -> MSE: 0.000147, MAE: 0.008392, R²: -0.0002
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.16429 | val 0.24000
  Epoch 020 - train 0.16823 | val 0.26152
  Regression -> MSE: 0.000168, MAE: 0.010216, R²: 0.0032
  Directional -> Accuracy: 0.5625, MCC: 0.1273, F1: 0.6000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.20681 | val 0.31537
  Epoch 020 - train 0.17963 | val 0.42534
  Regression -> MSE: 0.000088, MAE: 0.007227, R²: 0.0026
  Directional -> Accuracy: 0.6429, MCC: 0.3203, F1: 0.7619

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.18367 | val 0.38984
  Epoch 020 - train 0.16643 | val 0.39551
  Regression -> MSE: 0.000217, MAE: 0.010992, R²: -0.0172
  Directional -> Accuracy: 0.5312, MCC: 0.0588, F1: 0.5000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.17774 | val 0.17319
  Epoch 020 - train 0.15711 | val 0.16219
  Regression -> MSE: 0.000132, MAE: 0.008992, R²: -0.4501
  Directional -> Accuracy: 0.5370, MCC: 0.1558, F1: 0.3590

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.19719 | val 0.22460
  Epoch 020 - train 0.18839 | val 0.20244
  Regression -> MSE: 0.000096, MAE: 0.008304, R²: 0.0055
  Directional -> Accuracy: 0.6744, MCC: 0.3753, F1: 0.6667

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.19360 | val 0.19044
  Epoch 020 - train 0.19305 | val 0.16297
  Regression -> MSE: 0.000272, MAE: 0.012931, R²: 0.0004
  Directional -> Accuracy: 0.5918, MCC: 0.0000, F1: 0.7436

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.19011 | val 0.25956
  Epoch 020 - train 0.17629 | val 0.25217
  Regression -> MSE: 0.000238, MAE: 0.009947, R²: -0.4037
  Directional -> Accuracy: 0.4909, MCC: 0.1773, F1: 0.1250

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.17867 | val 0.16209
  Epoch 020 - train 0.17814 | val 0.22987
  Regression -> MSE: 0.000263, MAE: 0.012777, R²: -0.0487
  Directional -> Accuracy: 0.5000, MCC: 0.0993, F1: 0.2963

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.19313 | val 0.39766
  Epoch 020 - train 0.17063 | val 0.37838
  Regression -> MSE: 0.000238, MAE: 0.010125, R²: -0.0208
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.19017 | val 0.32642
  Epoch 020 - train 0.16648 | val 0.30675
  Regression -> MSE: 0.000141, MAE: 0.008244, R²: -0.0101
  Directional -> Accuracy: 0.5610, MCC: 0.0000, F1: 0.7188

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.19161 | val 0.24690
  Epoch 020 - train 0.17050 | val 0.24766
  Regression -> MSE: 0.000190, MAE: 0.010496, R²: -0.0195
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15991 | val 0.23944
  Epoch 020 - train 0.15159 | val 0.24633
  Regression -> MSE: 0.000290, MAE: 0.011140, R²: -0.0855
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.16751 | val 0.19562
  Epoch 020 - train 0.16640 | val 0.22067
  Regression -> MSE: 0.000188, MAE: 0.010713, R²: -0.0035
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.17768 | val 0.22167
  Epoch 020 - train 0.16776 | val 0.22480
  Regression -> MSE: 0.000351, MAE: 0.012426, R²: 0.0035
  Directional -> Accuracy: 0.4308, MCC: -0.0249, F1: 0.0513

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18968 | val 0.13804
  Epoch 020 - train 0.17640 | val 0.12401
  Regression -> MSE: 0.000139, MAE: 0.008866, R²: -0.2639
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.20607 | val 0.28306
  Epoch 020 - train 0.16614 | val 0.31624
  Regression -> MSE: 0.000227, MAE: 0.011516, R²: -0.0137
  Directional -> Accuracy: 0.4545, MCC: -0.0745, F1: 0.4828

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.18228 | val 0.48806
  Epoch 020 - train 0.15332 | val 0.55705
  Regression -> MSE: 0.000078, MAE: 0.006858, R²: -0.1069
  Directional -> Accuracy: 0.3778, MCC: -0.0544, F1: 0.0667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.18943 | val 0.20362
  Epoch 020 - train 0.15862 | val 0.27082
  Regression -> MSE: 0.000347, MAE: 0.015408, R²: -0.0907
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.17377 | val 0.27709
  Epoch 020 - train 0.16468 | val 0.35828
  Regression -> MSE: 0.000075, MAE: 0.006734, R²: 0.0291
  Directional -> Accuracy: 0.5068, MCC: 0.0505, F1: 0.6538

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.20507 | val 0.30332
  Epoch 020 - train 0.18671 | val 0.28773
  Regression -> MSE: 0.000284, MAE: 0.014077, R²: -0.0194
  Directional -> Accuracy: 0.5227, MCC: 0.0498, F1: 0.6038

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.18890 | val 0.21485
  Epoch 020 - train 0.16732 | val 0.20659
  Regression -> MSE: 0.000103, MAE: 0.007297, R²: 0.0048
  Directional -> Accuracy: 0.5610, MCC: 0.0321, F1: 0.6786

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.19036 | val 0.33878
  Epoch 020 - train 0.18602 | val 0.33859
  Regression -> MSE: 0.000185, MAE: 0.010625, R²: -0.0383
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.17618 | val 0.35267
  Epoch 020 - train 0.15674 | val 0.32783
  Regression -> MSE: 0.000240, MAE: 0.012134, R²: -0.0556
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.18385 | val 0.35652
  Epoch 020 - train 0.16589 | val 0.34169
  Regression -> MSE: 0.000088, MAE: 0.007567, R²: -0.0043
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.20168 | val 0.36556
  Epoch 020 - train 0.19358 | val 0.37227
  Regression -> MSE: 0.000168, MAE: 0.010274, R²: -0.0044
  Directional -> Accuracy: 0.5385, MCC: 0.0833, F1: 0.4286

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.17846 | val 0.28812
  Epoch 020 - train 0.16682 | val 0.28441
  Regression -> MSE: 0.000119, MAE: 0.009044, R²: 0.0047
  Directional -> Accuracy: 0.5926, MCC: 0.2935, F1: 0.7179

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.19104 | val 0.30539

[I 2026-02-23 22:38:50,677] Trial 1 finished with value: -0.011776009582029954 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 0.0011061298113636722, 'weight_decay': 1.3698423463269317e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.3201289638065694, 'early_stopping_min_delta': 0.006472483463945002}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 020 - train 0.17901 | val 0.28909
  Regression -> MSE: 0.000245, MAE: 0.012756, R²: -0.0052
  Directional -> Accuracy: 0.4915, MCC: -0.0309, F1: 0.4000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09717 | val 0.12430
  Epoch 020 - train 0.09738 | val 0.12476
  Epoch 021 - train 0.09828 | val 0.12471
  Regression -> MSE: 0.000247, MAE: 0.012559, R²: -0.0042
  Directional -> Accuracy: 0.5823, MCC: 0.2129, F1: 0.6207

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10356 | val 0.10146
  Epoch 020 - train 0.10361 | val 0.10380
  Epoch 021 - train 0.10252 | val 0.10383
  Regression -> MSE: 0.000680, MAE: 0.019326, R²: -0.0039
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11045 | val 0.17262
  Epoch 020 - train 0.10763 | val 0.17440
  Epoch 021 - train 0.10786 | val 0.17460
  Regression -> MSE: 0.000346, MAE: 0.015206, R²: 0.0033
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09214 | val 0.11321
  Epoch 020 - train 0.08986 | val 0.12321
  Epoch 021 - train 0.09028 | val 0.12201
  Regression -> MSE: 0.000358, MAE: 0.014740, R²: -0.0088
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10307 | val 0.09554
  Epoch 020 - train 0.09968 | val 0.09237
  Epoch 030 - train 0.10027 | val 0.09131
  Regression -> MSE: 0.000211, MAE: 0.010476, R²: -0.0655
  Directional -> Accuracy: 0.4906, MCC: -0.0289, F1: 0.5424

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09943 | val 0.20033
  Epoch 020 - train 0.10031 | val 0.20191
  Epoch 021 - train 0.09850 | val 0.20151
  Regression -> MSE: 0.000524, MAE: 0.017796, R²: -0.0548
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10857 | val 0.12331
  Epoch 020 - train 0.10945 | val 0.12322
  Epoch 021 - train 0.10808 | val 0.12314
  Regression -> MSE: 0.000259, MAE: 0.012291, R²: -0.0079
  Directional -> Accuracy: 0.5634, MCC: -0.0788, F1: 0.0606

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10051 | val 0.14612
  Epoch 020 - train 0.09898 | val 0.16448
  Epoch 021 - train 0.09940 | val 0.16713
  Regression -> MSE: 0.000649, MAE: 0.020160, R²: -0.1442
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10113 | val 0.13684
  Epoch 020 - train 0.09925 | val 0.13879
  Epoch 021 - train 0.09870 | val 0.13889
  Regression -> MSE: 0.000387, MAE: 0.015606, R²: -0.0055
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10244 | val 0.13016
  Epoch 020 - train 0.10325 | val 0.13476
  Epoch 021 - train 0.10279 | val 0.13493
  Regression -> MSE: 0.000238, MAE: 0.011681, R²: -0.0004
  Directional -> Accuracy: 0.4028, MCC: -0.1944, F1: 0.5743

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09816 | val 0.15079
  Epoch 020 - train 0.09472 | val 0.15523
  Epoch 021 - train 0.09699 | val 0.15529
  Regression -> MSE: 0.000307, MAE: 0.013748, R²: -0.0006
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10617 | val 0.11616
  Epoch 020 - train 0.10389 | val 0.12350
  Epoch 021 - train 0.10556 | val 0.12351
  Regression -> MSE: 0.000656, MAE: 0.019214, R²: 0.0049
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10439 | val 0.11044
  Epoch 020 - train 0.10465 | val 0.12099
  Epoch 021 - train 0.10445 | val 0.12181
  Regression -> MSE: 0.000148, MAE: 0.009337, R²: -0.0102
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10070 | val 0.12806
  Epoch 020 - train 0.09657 | val 0.12659
  Epoch 021 - train 0.09612 | val 0.12607
  Regression -> MSE: 0.000227, MAE: 0.010857, R²: -0.0074
  Directional -> Accuracy: 0.5079, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09910 | val 0.19747
  Epoch 020 - train 0.10070 | val 0.20422
  Epoch 021 - train 0.09910 | val 0.20451
  Regression -> MSE: 0.000388, MAE: 0.016625, R²: -0.0125
  Directional -> Accuracy: 0.4630, MCC: -0.1425, F1: 0.6329

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10705 | val 0.11108
  Epoch 020 - train 0.10590 | val 0.11557
  Epoch 021 - train 0.10342 | val 0.11586
  Regression -> MSE: 0.000105, MAE: 0.007913, R²: -0.0013
  Directional -> Accuracy: 0.4583, MCC: -0.0141, F1: 0.0488

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10087 | val 0.15490
  Epoch 020 - train 0.10109 | val 0.15646
  Epoch 021 - train 0.10079 | val 0.15655
  Regression -> MSE: 0.000158, MAE: 0.009738, R²: -0.0032
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10247 | val 0.09564
  Epoch 020 - train 0.10205 | val 0.09941
  Epoch 021 - train 0.10060 | val 0.09949
  Regression -> MSE: 0.000271, MAE: 0.013021, R²: -0.0003
  Directional -> Accuracy: 0.6026, MCC: 0.0000, F1: 0.7520

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10094 | val 0.13622
  Epoch 020 - train 0.09757 | val 0.13818
  Epoch 021 - train 0.09901 | val 0.13821
  Regression -> MSE: 0.000164, MAE: 0.009079, R²: -0.0606
  Directional -> Accuracy: 0.4179, MCC: -0.1499, F1: 0.4348

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10763 | val 0.13952
  Epoch 020 - train 0.10359 | val 0.14247
  Epoch 021 - train 0.10381 | val 0.14240
  Regression -> MSE: 0.000237, MAE: 0.011213, R²: -0.0243
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10282 | val 0.12189
  Epoch 020 - train 0.10165 | val 0.12782
  Epoch 021 - train 0.10053 | val 0.12786
  Regression -> MSE: 0.000150, MAE: 0.008691, R²: -0.0070
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09757 | val 0.11637
  Epoch 020 - train 0.09730 | val 0.11656
  Epoch 021 - train 0.09861 | val 0.11666
  Regression -> MSE: 0.000193, MAE: 0.010752, R²: -0.0615
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10877 | val 0.11906
  Epoch 020 - train 0.10547 | val 0.11864
  Epoch 030 - train 0.10586 | val 0.11787
  Regression -> MSE: 0.000086, MAE: 0.007201, R²: -0.0410
  Directional -> Accuracy: 0.6167, MCC: 0.2197, F1: 0.7527

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10464 | val 0.12325
  Epoch 020 - train 0.10197 | val 0.13722
  Epoch 021 - train 0.10333 | val 0.13681
  Regression -> MSE: 0.000215, MAE: 0.011293, R²: 0.0016
  Directional -> Accuracy: 0.4853, MCC: 0.0000, F1: 0.6535

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09746 | val 0.08905
  Epoch 020 - train 0.09874 | val 0.09065
  Epoch 021 - train 0.09670 | val 0.09072
  Regression -> MSE: 0.000097, MAE: 0.008102, R²: -0.0724
  Directional -> Accuracy: 0.4483, MCC: -0.1434, F1: 0.5429

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11001 | val 0.06059
  Epoch 020 - train 0.10919 | val 0.06197
  Epoch 021 - train 0.10808 | val 0.06223
  Regression -> MSE: 0.000129, MAE: 0.009385, R²: -0.0343
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10179 | val 0.06921
  Epoch 020 - train 0.10202 | val 0.07224
  Epoch 021 - train 0.10324 | val 0.07267
  Regression -> MSE: 0.000305, MAE: 0.013891, R²: -0.0462
  Directional -> Accuracy: 0.6444, MCC: 0.2232, F1: 0.7647

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10085 | val 0.12126
  Epoch 020 - train 0.10090 | val 0.12184
  Epoch 021 - train 0.10114 | val 0.12180
  Regression -> MSE: 0.000176, MAE: 0.007748, R²: -0.0954
  Directional -> Accuracy: 0.4407, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11183 | val 0.10086
  Epoch 020 - train 0.10586 | val 0.10308
  Epoch 021 - train 0.10959 | val 0.10333
  Regression -> MSE: 0.000232, MAE: 0.011900, R²: -0.0075
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10519 | val 0.12863
  Epoch 020 - train 0.10697 | val 0.13135
  Epoch 021 - train 0.10529 | val 0.13149
  Regression -> MSE: 0.000260, MAE: 0.010742, R²: -0.0023
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11626 | val 0.12472
  Epoch 020 - train 0.11325 | val 0.12575
  Epoch 021 - train 0.11206 | val 0.12592
  Regression -> MSE: 0.000141, MAE: 0.008447, R²: -0.0044
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10304 | val 0.12756
  Epoch 020 - train 0.10119 | val 0.12542
  Epoch 030 - train 0.09918 | val 0.12490
  Regression -> MSE: 0.000200, MAE: 0.010979, R²: -0.0766
  Directional -> Accuracy: 0.4038, MCC: -0.2038, F1: 0.2051

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09446 | val 0.11380
  Epoch 020 - train 0.09273 | val 0.11297
  Epoch 030 - train 0.09241 | val 0.11277
  Regression -> MSE: 0.000267, MAE: 0.010765, R²: -0.0241
  Directional -> Accuracy: 0.5333, MCC: 0.1340, F1: 0.4444

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09605 | val 0.11121
  Epoch 020 - train 0.09786 | val 0.11626
  Epoch 021 - train 0.09503 | val 0.11712
  Regression -> MSE: 0.000161, MAE: 0.010103, R²: 0.0072
  Directional -> Accuracy: 0.5122, MCC: 0.0263, F1: 0.5238

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09366 | val 0.09915
  Epoch 020 - train 0.09053 | val 0.11169
  Epoch 021 - train 0.09166 | val 0.11253
  Regression -> MSE: 0.000220, MAE: 0.011232, R²: -0.0273
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09888 | val 0.09618
  Epoch 020 - train 0.09723 | val 0.09734
  Epoch 021 - train 0.09849 | val 0.09734
  Regression -> MSE: 0.000348, MAE: 0.012246, R²: -0.0105
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11102 | val 0.07442
  Epoch 020 - train 0.11123 | val 0.07572
  Epoch 021 - train 0.11113 | val 0.07579
  Regression -> MSE: 0.000113, MAE: 0.008107, R²: -0.1136
  Directional -> Accuracy: 0.4222, MCC: -0.1572, F1: 0.3158

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10738 | val 0.12678
  Epoch 020 - train 0.10495 | val 0.12666
  Epoch 021 - train 0.10540 | val 0.12686
  Regression -> MSE: 0.000212, MAE: 0.010986, R²: -0.0027
  Directional -> Accuracy: 0.5932, MCC: 0.1799, F1: 0.5000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10528 | val 0.17519
  Epoch 020 - train 0.10774 | val 0.18018
  Epoch 021 - train 0.10461 | val 0.17999
  Regression -> MSE: 0.000096, MAE: 0.007684, R²: -0.2077
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10201 | val 0.08503
  Epoch 020 - train 0.10116 | val 0.08523
  Epoch 021 - train 0.10100 | val 0.08536
  Regression -> MSE: 0.000318, MAE: 0.014237, R²: -0.0147
  Directional -> Accuracy: 0.2857, MCC: -0.3162, F1: 0.4444

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11234 | val 0.07726
  Epoch 020 - train 0.11102 | val 0.08643
  Epoch 021 - train 0.11308 | val 0.08760
  Regression -> MSE: 0.000234, MAE: 0.010987, R²: -0.0257
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11162 | val 0.13393
  Epoch 020 - train 0.11085 | val 0.13992
  Epoch 021 - train 0.11061 | val 0.13970
  Regression -> MSE: 0.000091, MAE: 0.007268, R²: -0.1077
  Directional -> Accuracy: 0.4935, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10239 | val 0.10840
  Epoch 020 - train 0.10336 | val 0.10450
  Epoch 030 - train 0.10015 | val 0.10396
  Regression -> MSE: 0.000374, MAE: 0.015641, R²: -0.0103
  Directional -> Accuracy: 0.5306, MCC: 0.0599, F1: 0.3429

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09903 | val 0.12565
  Epoch 020 - train 0.09462 | val 0.12124
  Epoch 030 - train 0.09431 | val 0.11817
  Regression -> MSE: 0.000091, MAE: 0.006884, R²: 0.0464
  Directional -> Accuracy: 0.6170, MCC: 0.1869, F1: 0.7097

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10983 | val 0.14303
  Epoch 020 - train 0.10628 | val 0.16158
  Epoch 021 - train 0.11002 | val 0.16249
  Regression -> MSE: 0.000194, MAE: 0.010661, R²: -0.0169
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10920 | val 0.12644
  Epoch 020 - train 0.10749 | val 0.13471
  Epoch 021 - train 0.10813 | val 0.13457
  Regression -> MSE: 0.000230, MAE: 0.011767, R²: -0.0634
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11058 | val 0.12306

[I 2026-02-23 22:39:51,823] Trial 2 finished with value: -0.011538977153312691 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 64, 'learning_rate': 9.72505751789171e-06, 'weight_decay': 8.327183275539654e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.15459119534246876, 'early_stopping_min_delta': 0.0025952496423544925}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 020 - train 0.10444 | val 0.13927
  Epoch 021 - train 0.10532 | val 0.13921
  Regression -> MSE: 0.000231, MAE: 0.012134, R²: -0.0026
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.36608 | val 0.65720
  Epoch 020 - train 0.30154 | val 0.68150
  Regression -> MSE: 0.000278, MAE: 0.013089, R²: -0.1304
  Directional -> Accuracy: 0.5443, MCC: 0.0454, F1: 0.3793

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41206 | val 0.43264
  Epoch 019 - train 0.36803 | val 0.50570
  Regression -> MSE: 0.000640, MAE: 0.018721, R²: 0.0548
  Directional -> Accuracy: 0.6667, MCC: 0.3897, F1: 0.6364

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44416 | val 0.92869
  Epoch 020 - train 0.37809 | val 1.01954
  Regression -> MSE: 0.000376, MAE: 0.015593, R²: -0.0826
  Directional -> Accuracy: 0.5102, MCC: 0.1311, F1: 0.2000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33799 | val 0.50951
  Epoch 013 - train 0.34157 | val 0.41583
  Regression -> MSE: 0.000354, MAE: 0.014691, R²: 0.0039
  Directional -> Accuracy: 0.5325, MCC: 0.0000, F1: 0.6667

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.38512 | val 0.64285
  Epoch 013 - train 0.36245 | val 0.45215
  Regression -> MSE: 0.000181, MAE: 0.008684, R²: 0.0857
  Directional -> Accuracy: 0.6981, MCC: 0.3937, F1: 0.7333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.37464 | val 1.04151
  Epoch 017 - train 0.28367 | val 1.07903
  Regression -> MSE: 0.000519, MAE: 0.017566, R²: -0.0454
  Directional -> Accuracy: 0.6098, MCC: 0.3341, F1: 0.6923

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.40000 | val 0.59409
  Epoch 015 - train 0.38383 | val 0.79288
  Regression -> MSE: 0.000253, MAE: 0.012354, R²: 0.0132
  Directional -> Accuracy: 0.5915, MCC: 0.2241, F1: 0.5915

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.37331 | val 0.62780
  Epoch 013 - train 0.31280 | val 0.85255
  Regression -> MSE: 0.000565, MAE: 0.018355, R²: 0.0028
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.40231 | val 0.79570
  Epoch 014 - train 0.39714 | val 0.75002
  Regression -> MSE: 0.000384, MAE: 0.015641, R²: 0.0017
  Directional -> Accuracy: 0.5349, MCC: -0.0145, F1: 0.3333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.40655 | val 0.96598
  Epoch 011 - train 0.40559 | val 0.91612
  Regression -> MSE: 0.000244, MAE: 0.011709, R²: -0.0251
  Directional -> Accuracy: 0.5139, MCC: -0.0114, F1: 0.3860

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.38422 | val 0.75855
  Epoch 020 - train 0.28341 | val 0.83777
  Regression -> MSE: 0.000279, MAE: 0.013252, R²: 0.0905
  Directional -> Accuracy: 0.5385, MCC: 0.1060, F1: 0.5862

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42709 | val 0.55972
  Epoch 011 - train 0.40603 | val 0.64432
  Regression -> MSE: 0.000660, MAE: 0.019203, R²: -0.0017
  Directional -> Accuracy: 0.4833, MCC: -0.1302, F1: 0.6517

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.36169 | val 0.55444
  Epoch 020 - train 0.28060 | val 0.70007
  Regression -> MSE: 0.000158, MAE: 0.009529, R²: -0.0800
  Directional -> Accuracy: 0.5778, MCC: 0.1494, F1: 0.5366

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.36963 | val 0.67098
  Epoch 011 - train 0.35850 | val 0.67422
  Regression -> MSE: 0.000224, MAE: 0.010789, R²: 0.0023
  Directional -> Accuracy: 0.5873, MCC: 0.2206, F1: 0.6750

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.38290 | val 2.33137
  Epoch 011 - train 0.39200 | val 2.28820
  Regression -> MSE: 0.000431, MAE: 0.017386, R²: -0.1246
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.40741 | val 0.64315
  Epoch 011 - train 0.41746 | val 0.70381
  Regression -> MSE: 0.000103, MAE: 0.007934, R²: 0.0203
  Directional -> Accuracy: 0.5556, MCC: 0.0936, F1: 0.6190

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38705 | val 1.04142
  Epoch 017 - train 0.30774 | val 0.96003
  Regression -> MSE: 0.000160, MAE: 0.010060, R²: -0.0145
  Directional -> Accuracy: 0.6066, MCC: 0.1523, F1: 0.6923

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.38538 | val 0.57776
  Epoch 011 - train 0.37690 | val 0.63516
  Regression -> MSE: 0.000329, MAE: 0.015031, R²: -0.2129
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.34932 | val 0.62479
  Epoch 018 - train 0.30624 | val 0.65232
  Regression -> MSE: 0.000192, MAE: 0.010344, R²: -0.2405
  Directional -> Accuracy: 0.4776, MCC: 0.1598, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.40176 | val 0.94600
  Epoch 020 - train 0.32702 | val 0.95435
  Regression -> MSE: 0.000536, MAE: 0.018646, R²: -1.3170
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42169 | val 0.71573
  Epoch 012 - train 0.37153 | val 0.58125
  Regression -> MSE: 0.000159, MAE: 0.009184, R²: -0.0688
  Directional -> Accuracy: 0.4600, MCC: 0.0071, F1: 0.4255

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.39174 | val 0.58347
  Epoch 011 - train 0.38626 | val 0.58860
  Regression -> MSE: 0.000181, MAE: 0.010722, R²: 0.0057
  Directional -> Accuracy: 0.5588, MCC: 0.1210, F1: 0.6053

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.42130 | val 0.65721
  Epoch 011 - train 0.42377 | val 0.63925
  Regression -> MSE: 0.000081, MAE: 0.006760, R²: 0.0116
  Directional -> Accuracy: 0.6000, MCC: 0.1680, F1: 0.6667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.38723 | val 0.82582
  Epoch 013 - train 0.39473 | val 0.73805
  Regression -> MSE: 0.000215, MAE: 0.011227, R²: 0.0030
  Directional -> Accuracy: 0.5441, MCC: 0.0883, F1: 0.5373

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.32740 | val 0.35757
  Epoch 011 - train 0.31997 | val 0.34989
  Regression -> MSE: 0.000113, MAE: 0.008480, R²: -0.2564
  Directional -> Accuracy: 0.5000, MCC: 0.0991, F1: 0.2927

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.38269 | val 1.40626
  Epoch 011 - train 0.38880 | val 1.24347
  Regression -> MSE: 0.000130, MAE: 0.009369, R²: -0.0373
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45249 | val 0.20450
  Epoch 013 - train 0.41441 | val 0.29249
  Regression -> MSE: 0.000311, MAE: 0.013977, R²: -0.0664
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.6774

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40628 | val 0.67929
  Epoch 011 - train 0.40516 | val 0.72462
  Regression -> MSE: 0.000207, MAE: 0.008785, R²: -0.2873
  Directional -> Accuracy: 0.4915, MCC: 0.2054, F1: 0.1667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46554 | val 0.59753
  Epoch 014 - train 0.38065 | val 0.44306
  Regression -> MSE: 0.000226, MAE: 0.011849, R²: 0.0205
  Directional -> Accuracy: 0.5000, MCC: -0.1457, F1: 0.6667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.40552 | val 0.71280
  Epoch 016 - train 0.34231 | val 0.70893
  Regression -> MSE: 0.000253, MAE: 0.010798, R²: 0.0245
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4390

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.39939 | val 0.78386
  Epoch 011 - train 0.39133 | val 0.76320
  Regression -> MSE: 0.000154, MAE: 0.008824, R²: -0.0971
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.40916 | val 0.70320
  Epoch 011 - train 0.39778 | val 0.64806
  Regression -> MSE: 0.000199, MAE: 0.010986, R²: -0.0700
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.35475 | val 0.72113
  Epoch 011 - train 0.36020 | val 0.68760
  Regression -> MSE: 0.000336, MAE: 0.012405, R²: -0.2873
  Directional -> Accuracy: 0.5067, MCC: 0.0950, F1: 0.3729

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.37986 | val 0.65291
  Epoch 012 - train 0.35837 | val 0.89442
  Regression -> MSE: 0.000162, MAE: 0.010147, R²: -0.0008
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37769 | val 1.13156
  Epoch 012 - train 0.36495 | val 1.02281
  Regression -> MSE: 0.000222, MAE: 0.011357, R²: -0.0364
  Directional -> Accuracy: 0.3696, MCC: -0.2583, F1: 0.3556

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.38169 | val 0.43493
  Epoch 011 - train 0.35559 | val 0.46099
  Regression -> MSE: 0.000345, MAE: 0.012080, R²: -0.0035
  Directional -> Accuracy: 0.4783, MCC: -0.0232, F1: 0.4857

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.33483 | val 0.35914
  Epoch 011 - train 0.32308 | val 0.38972
  Regression -> MSE: 0.000122, MAE: 0.008030, R²: -0.2038
  Directional -> Accuracy: 0.6222, MCC: 0.2882, F1: 0.5143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.38810 | val 0.91624
  Epoch 011 - train 0.40764 | val 0.83640
  Regression -> MSE: 0.000220, MAE: 0.011419, R²: -0.0414
  Directional -> Accuracy: 0.4068, MCC: -0.1917, F1: 0.3636

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.36864 | val 1.16474
  Epoch 011 - train 0.38164 | val 1.17157
  Regression -> MSE: 0.000084, MAE: 0.007250, R²: -0.0502
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.37746 | val 0.36825
  Epoch 012 - train 0.36924 | val 0.38816
  Regression -> MSE: 0.000324, MAE: 0.014739, R²: -0.0331
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.37134 | val 0.32636
  Epoch 012 - train 0.39755 | val 0.35108
  Regression -> MSE: 0.000250, MAE: 0.010932, R²: -0.0946
  Directional -> Accuracy: 0.6341, MCC: 0.2718, F1: 0.6809

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.35658 | val 0.91968
  Epoch 011 - train 0.35634 | val 1.10548
  Regression -> MSE: 0.000091, MAE: 0.007749, R²: -0.1153
  Directional -> Accuracy: 0.5325, MCC: 0.1007, F1: 0.6727

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43664 | val 0.59374
  Epoch 020 - train 0.37745 | val 0.52410
  Regression -> MSE: 0.000353, MAE: 0.015491, R²: 0.0458
  Directional -> Accuracy: 0.5714, MCC: 0.1492, F1: 0.6038

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40087 | val 0.64456
  Epoch 011 - train 0.37710 | val 0.65491
  Regression -> MSE: 0.000091, MAE: 0.007016, R²: 0.0402
  Directional -> Accuracy: 0.5957, MCC: 0.1280, F1: 0.7077

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43805 | val 0.82920
  Epoch 015 - train 0.33567 | val 1.09978
  Regression -> MSE: 0.000379, MAE: 0.016606, R²: -0.9823
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.39031 | val 0.53852
  Epoch 020 - train 0.34400 | val 0.51886
  Regression -> MSE: 0.000212, MAE: 0.011211, R²: 0.0213
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.39039 | val 0.98868
  Epoch 011 - train 0.40725 | val 0.70981
  Regression -> MSE: 0.000104, MAE: 0.008363, R²: -0.1615
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44116 | val 1.23990
  Epoch 013 - train 0.40301 | val 1.41485
  Regression -> MSE: 0.000161, MAE: 0.009839, R²: -0.0185
  Directional -> Accuracy: 0.5714, MCC: 0.1281, F1: 0.6364

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.37820 | val 1.14115
  Epoch 011 - train 0.36963 | val 1.68325
  Regression -> MSE: 0.000115, MAE: 0.008817, R²: -0.0248
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.43862 | val 1.01959

[I 2026-02-23 22:41:46,598] Trial 3 finished with value: -0.011899360520839973 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.00235502835981708, 'weight_decay': 9.307591524488368e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.5303338092134653, 'early_stopping_min_delta': 0.002312703436402508}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 017 - train 0.38239 | val 0.87309
  Regression -> MSE: 0.000225, MAE: 0.011977, R²: 0.0237
  Directional -> Accuracy: 0.5397, MCC: 0.1040, F1: 0.6027

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.34077 | val 0.85962
  Epoch 017 - train 0.31532 | val 0.61675
  Regression -> MSE: 0.000319, MAE: 0.014238, R²: -0.3259
  Directional -> Accuracy: 0.4605, MCC: 0.0253, F1: 0.6095

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.30132 | val 0.48293
  Epoch 016 - train 0.26796 | val 0.41416
  Regression -> MSE: 0.000685, MAE: 0.019224, R²: 0.0178
  Directional -> Accuracy: 0.6222, MCC: 0.2523, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.34472 | val 0.75786
  Epoch 020 - train 0.27630 | val 0.76897
  Regression -> MSE: 0.000366, MAE: 0.015374, R²: -0.1641
  Directional -> Accuracy: 0.4783, MCC: -0.0417, F1: 0.4783

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.27982 | val 0.73658
  Epoch 012 - train 0.29008 | val 0.75288
  Regression -> MSE: 0.000377, MAE: 0.015022, R²: -0.0681
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.32699 | val 0.45039
  Epoch 012 - train 0.30741 | val 0.47585
  Regression -> MSE: 0.000207, MAE: 0.010089, R²: -0.0059
  Directional -> Accuracy: 0.5600, MCC: 0.1442, F1: 0.4762

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.23838 | val 1.81280
  Epoch 011 - train 0.26756 | val 1.28744
  Regression -> MSE: 0.000569, MAE: 0.018347, R²: -0.0047
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.33231 | val 0.62794
  Epoch 011 - train 0.32080 | val 0.85563
  Regression -> MSE: 0.000246, MAE: 0.012201, R²: 0.0087
  Directional -> Accuracy: 0.5441, MCC: 0.1027, F1: 0.5079

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.26799 | val 1.24849
  Epoch 011 - train 0.25351 | val 0.99427
  Regression -> MSE: 0.000618, MAE: 0.019616, R²: -0.0113
  Directional -> Accuracy: 0.5238, MCC: -0.0323, F1: 0.2857

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.30527 | val 0.82660
  Epoch 011 - train 0.30382 | val 1.48135
  Regression -> MSE: 0.000382, MAE: 0.015641, R²: -0.0230
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.31945 | val 0.81658
  Epoch 013 - train 0.34119 | val 0.58947
  Regression -> MSE: 0.000246, MAE: 0.012095, R²: -0.0048
  Directional -> Accuracy: 0.4203, MCC: -0.0887, F1: 0.5122

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.29341 | val 1.21210
  Epoch 011 - train 0.28874 | val 0.96070
  Regression -> MSE: 0.000334, MAE: 0.013524, R²: -0.0684
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.34999 | val 0.78154
  Epoch 011 - train 0.35743 | val 0.68024
  Regression -> MSE: 0.000703, MAE: 0.019937, R²: -0.0247
  Directional -> Accuracy: 0.3684, MCC: -0.2635, F1: 0.3793

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.30745 | val 1.03111
  Epoch 011 - train 0.29821 | val 0.77993
  Regression -> MSE: 0.000139, MAE: 0.009171, R²: -0.0067
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.28617 | val 0.69925
  Epoch 012 - train 0.29594 | val 0.68063
  Regression -> MSE: 0.000223, MAE: 0.010562, R²: 0.0144
  Directional -> Accuracy: 0.5333, MCC: 0.0668, F1: 0.5172

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.29325 | val 1.02980
  Epoch 016 - train 0.26364 | val 1.04398
  Regression -> MSE: 0.000359, MAE: 0.015839, R²: 0.0204
  Directional -> Accuracy: 0.4510, MCC: -0.0199, F1: 0.6111

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.32883 | val 0.52038
  Epoch 012 - train 0.32160 | val 0.49973
  Regression -> MSE: 0.000104, MAE: 0.007757, R²: 0.0377
  Directional -> Accuracy: 0.5797, MCC: 0.1455, F1: 0.6420

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.31497 | val 0.84177
  Epoch 017 - train 0.32126 | val 0.97416
  Regression -> MSE: 0.000169, MAE: 0.010636, R²: -0.0688
  Directional -> Accuracy: 0.3966, MCC: -0.2132, F1: 0.4615

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.32107 | val 0.59139
  Epoch 012 - train 0.32264 | val 0.50372
  Regression -> MSE: 0.000291, MAE: 0.013104, R²: -0.0637
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.28287 | val 0.69004
  Epoch 014 - train 0.26820 | val 0.63229
  Regression -> MSE: 0.000188, MAE: 0.009888, R²: -0.2411
  Directional -> Accuracy: 0.4219, MCC: -0.0284, F1: 0.0513

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.33357 | val 0.95550
  Epoch 012 - train 0.33973 | val 0.94665
  Regression -> MSE: 0.000328, MAE: 0.013480, R²: -0.4405
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.28593 | val 0.73857
  Epoch 011 - train 0.27628 | val 0.71774
  Regression -> MSE: 0.000143, MAE: 0.008318, R²: 0.0049
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.32299 | val 0.55784
  Epoch 011 - train 0.31604 | val 0.54632
  Regression -> MSE: 0.000173, MAE: 0.010405, R²: -0.0450
  Directional -> Accuracy: 0.5077, MCC: 0.0081, F1: 0.6190

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.34828 | val 0.78508
  Epoch 011 - train 0.33706 | val 0.84722
  Regression -> MSE: 0.000094, MAE: 0.007454, R²: -0.0807
  Directional -> Accuracy: 0.4386, MCC: -0.0340, F1: 0.1111

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.33996 | val 0.64279
  Epoch 020 - train 0.28212 | val 0.66298
  Regression -> MSE: 0.000211, MAE: 0.010942, R²: -0.0010
  Directional -> Accuracy: 0.5385, MCC: 0.0702, F1: 0.4828

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.26366 | val 0.49969
  Epoch 012 - train 0.29010 | val 0.49529
  Regression -> MSE: 0.000091, MAE: 0.007770, R²: -0.0107
  Directional -> Accuracy: 0.5273, MCC: 0.0669, F1: 0.5185

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.29891 | val 0.77081
  Epoch 011 - train 0.29765 | val 0.87226
  Regression -> MSE: 0.000115, MAE: 0.009117, R²: -0.1566
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.34552 | val 0.78774
  Epoch 011 - train 0.36925 | val 0.52303
  Regression -> MSE: 0.000247, MAE: 0.012995, R²: -0.0422
  Directional -> Accuracy: 0.5476, MCC: 0.1876, F1: 0.4571

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.34769 | val 0.55324
  Epoch 011 - train 0.33063 | val 0.52724
  Regression -> MSE: 0.000214, MAE: 0.009008, R²: -0.2661
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.31729 | val 0.33152
  Epoch 016 - train 0.26683 | val 0.43927
  Regression -> MSE: 0.000239, MAE: 0.012115, R²: 0.0146
  Directional -> Accuracy: 0.6000, MCC: 0.1759, F1: 0.7037

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.30072 | val 0.75137
  Epoch 019 - train 0.26384 | val 0.74813
  Regression -> MSE: 0.000236, MAE: 0.010445, R²: -0.0023
  Directional -> Accuracy: 0.4524, MCC: -0.1064, F1: 0.3784

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.28308 | val 0.66745
  Epoch 011 - train 0.27200 | val 0.59841
  Regression -> MSE: 0.000147, MAE: 0.008577, R²: -0.0665
  Directional -> Accuracy: 0.3810, MCC: -0.2353, F1: 0.1333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.30976 | val 0.61250
  Epoch 011 - train 0.30686 | val 0.63586
  Regression -> MSE: 0.000189, MAE: 0.010286, R²: -0.0326
  Directional -> Accuracy: 0.4694, MCC: -0.0311, F1: 0.2778

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.26848 | val 0.62808
  Epoch 014 - train 0.27229 | val 0.68719
  Regression -> MSE: 0.000305, MAE: 0.012068, R²: -0.1473
  Directional -> Accuracy: 0.5139, MCC: 0.1147, F1: 0.3636

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.24631 | val 0.65037
  Epoch 012 - train 0.24637 | val 0.64593
  Regression -> MSE: 0.000179, MAE: 0.010302, R²: 0.0222
  Directional -> Accuracy: 0.5349, MCC: 0.1249, F1: 0.6552

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.29037 | val 0.44261
  Epoch 020 - train 0.27430 | val 0.55960
  Regression -> MSE: 0.000533, MAE: 0.018449, R²: -0.5316
  Directional -> Accuracy: 0.4394, MCC: 0.0401, F1: 0.0976

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.27946 | val 0.22415
  Epoch 013 - train 0.26406 | val 0.29443
  Regression -> MSE: 0.000120, MAE: 0.007939, R²: -0.1353
  Directional -> Accuracy: 0.6429, MCC: 0.3290, F1: 0.5714

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.31285 | val 0.97191
  Epoch 011 - train 0.30834 | val 1.24090
  Regression -> MSE: 0.000225, MAE: 0.011414, R²: -0.0212
  Directional -> Accuracy: 0.4821, MCC: -0.0494, F1: 0.4082

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.28702 | val 0.90977
  Epoch 011 - train 0.27032 | val 0.97152
  Regression -> MSE: 0.000078, MAE: 0.006891, R²: -0.0624
  Directional -> Accuracy: 0.4565, MCC: -0.0124, F1: 0.4186

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.29108 | val 0.32548
  Epoch 017 - train 0.26973 | val 0.25281
  Regression -> MSE: 0.000554, MAE: 0.020547, R²: -0.7785
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.32198 | val 0.78732
  Epoch 013 - train 0.28758 | val 0.60091
  Regression -> MSE: 0.000086, MAE: 0.007428, R²: -0.1071
  Directional -> Accuracy: 0.4730, MCC: -0.0480, F1: 0.5979

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.30919 | val 0.65977
  Epoch 011 - train 0.33747 | val 0.81974
  Regression -> MSE: 0.000301, MAE: 0.014372, R²: 0.0007
  Directional -> Accuracy: 0.5556, MCC: 0.1094, F1: 0.6154

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.28855 | val 0.50039
  Epoch 011 - train 0.28798 | val 0.56463
  Regression -> MSE: 0.000101, MAE: 0.007260, R²: 0.0112
  Directional -> Accuracy: 0.6190, MCC: 0.1978, F1: 0.7037

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.29824 | val 0.60564
  Epoch 018 - train 0.19998 | val 0.59215
  Regression -> MSE: 0.000310, MAE: 0.014743, R²: -0.7662
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.29854 | val 0.68233
  Epoch 015 - train 0.28525 | val 0.50524
  Regression -> MSE: 0.000238, MAE: 0.012619, R²: -0.0565
  Directional -> Accuracy: 0.3273, MCC: -0.4033, F1: 0.4478

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.31673 | val 0.89444
  Epoch 011 - train 0.29763 | val 1.17709
  Regression -> MSE: 0.000093, MAE: 0.007723, R²: 0.0065
  Directional -> Accuracy: 0.5000, MCC: 0.1301, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.35177 | val 0.89303
  Epoch 011 - train 0.33744 | val 1.19769
  Regression -> MSE: 0.000168, MAE: 0.010304, R²: -0.0094
  Directional -> Accuracy: 0.5660, MCC: 0.1599, F1: 0.4390

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.29126 | val 0.56129
  Epoch 013 - train 0.29964 | val 0.57612
  Regression -> MSE: 0.000126, MAE: 0.009122, R²: -0.0667
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 22:42:50,421] Trial 4 finished with value: -0.012016309986644458 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 0.003974755721847982, 'weight_decay': 2.613475666587197e-06, 'lr_patience': 10, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.995071988449304, 'early_stopping_min_delta': 0.003810698409584027}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.33449 | val 1.27275
  Epoch 011 - train 0.33977 | val 0.75209
  Regression -> MSE: 0.000242, MAE: 0.012428, R²: -0.0068
  Directional -> Accuracy: 0.4833, MCC: -0.1001, F1: 0.1143

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.38235 | val 0.63682
  Epoch 020 - train 0.37646 | val 0.64533
  Epoch 021 - train 0.34677 | val 0.65262
  Regression -> MSE: 0.000239, MAE: 0.012261, R²: -0.0021
  Directional -> Accuracy: 0.5200, MCC: 0.1092, F1: 0.6087

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.39370 | val 0.40577
  Epoch 020 - train 0.36421 | val 0.41908
  Epoch 023 - train 0.37150 | val 0.40041
  Regression -> MSE: 0.000726, MAE: 0.020120, R²: -0.0299
  Directional -> Accuracy: 0.4318, MCC: 0.1269, F1: 0.0741

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44748 | val 0.77481
  Epoch 020 - train 0.39334 | val 0.77068
  Epoch 030 - train 0.37766 | val 0.78705
  Epoch 032 - train 0.38152 | val 0.78202
  Regression -> MSE: 0.000344, MAE: 0.014868, R²: -0.0698
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.32508 | val 0.36113
  Epoch 020 - train 0.31593 | val 0.36604
  Epoch 030 - train 0.30979 | val 0.37159
  Epoch 037 - train 0.30646 | val 0.36556
  Regression -> MSE: 0.000359, MAE: 0.014793, R²: -0.0076
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40562 | val 0.35421
  Epoch 020 - train 0.35999 | val 0.35201
  Epoch 030 - train 0.36184 | val 0.36569
  Epoch 040 - train 0.35293 | val 0.34996
  Epoch 041 - train 0.35837 | val 0.35140
  Regression -> MSE: 0.000205, MAE: 0.009377, R²: 0.0253
  Directional -> Accuracy: 0.6939, MCC: 0.4513, F1: 0.7619

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.37442 | val 0.76028
  Epoch 020 - train 0.36590 | val 0.74602
  Epoch 021 - train 0.35379 | val 0.74923
  Regression -> MSE: 0.000579, MAE: 0.018509, R²: -0.0073
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44859 | val 0.64887
  Epoch 020 - train 0.39109 | val 0.64518
  Epoch 027 - train 0.37737 | val 0.57622
  Regression -> MSE: 0.000247, MAE: 0.011954, R²: 0.0200
  Directional -> Accuracy: 0.5522, MCC: 0.1547, F1: 0.5588

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42013 | val 0.42249
  Epoch 020 - train 0.34707 | val 0.56520
  Epoch 021 - train 0.41099 | val 0.54389
  Regression -> MSE: 0.000642, MAE: 0.020065, R²: -0.0269
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.39304 | val 0.57086
  Epoch 020 - train 0.35669 | val 0.67431
  Epoch 021 - train 0.41388 | val 0.64407
  Regression -> MSE: 0.000378, MAE: 0.015539, R²: -0.0108
  Directional -> Accuracy: 0.7234, MCC: 0.4434, F1: 0.6977

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41066 | val 0.54842
  Epoch 020 - train 0.39049 | val 0.59092
  Epoch 030 - train 0.36721 | val 0.71182
  Epoch 035 - train 0.35092 | val 0.55840
  Regression -> MSE: 0.000258, MAE: 0.012706, R²: -0.0380
  Directional -> Accuracy: 0.4118, MCC: -0.0993, F1: 0.5556

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.39307 | val 0.71712
  Epoch 020 - train 0.36422 | val 0.68312
  Epoch 021 - train 0.35037 | val 0.67907
  Regression -> MSE: 0.000314, MAE: 0.013502, R²: -0.0016
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44221 | val 0.54254
  Epoch 020 - train 0.41548 | val 0.60484
  Epoch 021 - train 0.42264 | val 0.58179
  Regression -> MSE: 0.000700, MAE: 0.020057, R²: -0.0031
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.40923 | val 0.49557
  Epoch 020 - train 0.40943 | val 0.88708
  Epoch 024 - train 0.37048 | val 0.99315
  Regression -> MSE: 0.000142, MAE: 0.009391, R²: -0.0056
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37036 | val 0.56823
  Epoch 020 - train 0.36128 | val 0.55952
  Epoch 030 - train 0.32461 | val 0.56295
  Epoch 040 - train 0.30715 | val 0.58169
  Epoch 047 - train 0.31311 | val 0.57015
  Regression -> MSE: 0.000231, MAE: 0.010622, R²: -0.0083
  Directional -> Accuracy: 0.5763, MCC: 0.1519, F1: 0.5902

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40488 | val 1.07731
  Epoch 020 - train 0.39743 | val 1.10861
  Epoch 021 - train 0.37389 | val 1.08450
  Regression -> MSE: 0.000368, MAE: 0.016269, R²: -0.0036
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.6111

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.39271 | val 0.41836
  Epoch 020 - train 0.40458 | val 0.41616
  Epoch 021 - train 0.39920 | val 0.41957
  Regression -> MSE: 0.000107, MAE: 0.007838, R²: 0.0112
  Directional -> Accuracy: 0.5294, MCC: 0.0354, F1: 0.6279

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.40471 | val 0.82682
  Epoch 020 - train 0.40059 | val 0.93823
  Epoch 021 - train 0.36191 | val 0.94045
  Regression -> MSE: 0.000152, MAE: 0.009901, R²: -0.0242
  Directional -> Accuracy: 0.4035, MCC: -0.0991, F1: 0.3200

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.38560 | val 0.48126
  Epoch 020 - train 0.39292 | val 0.46551
  Epoch 021 - train 0.38159 | val 0.45237
  Regression -> MSE: 0.000288, MAE: 0.013654, R²: -0.0423
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35991 | val 0.56685
  Epoch 020 - train 0.33071 | val 0.54535
  Epoch 030 - train 0.32015 | val 0.54220
  Epoch 040 - train 0.31770 | val 0.55106
  Epoch 048 - train 0.31086 | val 0.55706
  Regression -> MSE: 0.000196, MAE: 0.010050, R²: -0.2897
  Directional -> Accuracy: 0.3968, MCC: -0.1515, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.43924 | val 0.71903
  Epoch 020 - train 0.39359 | val 0.71401
  Epoch 030 - train 0.37528 | val 0.72791
  Epoch 036 - train 0.37724 | val 0.71891
  Regression -> MSE: 0.000361, MAE: 0.014399, R²: -0.6048
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.40624 | val 0.57407
  Epoch 020 - train 0.39438 | val 0.57585
  Epoch 030 - train 0.35435 | val 0.57149
  Epoch 038 - train 0.35510 | val 0.58821
  Regression -> MSE: 0.000149, MAE: 0.008678, R²: -0.0167
  Directional -> Accuracy: 0.5870, MCC: 0.3451, F1: 0.5128

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.38003 | val 0.53129
  Epoch 020 - train 0.38478 | val 0.50950
  Epoch 030 - train 0.36032 | val 0.50732
  Epoch 034 - train 0.34783 | val 0.51427
  Regression -> MSE: 0.000167, MAE: 0.010558, R²: 0.0085
  Directional -> Accuracy: 0.5156, MCC: 0.0342, F1: 0.5974

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.41426 | val 0.52927
  Epoch 020 - train 0.39347 | val 0.61440
  Epoch 021 - train 0.39344 | val 0.60050
  Regression -> MSE: 0.000087, MAE: 0.007173, R²: 0.0159
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.39242 | val 0.57832
  Epoch 020 - train 0.38248 | val 0.55635
  Epoch 022 - train 0.40255 | val 0.56636
  Regression -> MSE: 0.000214, MAE: 0.010959, R²: -0.0045
  Directional -> Accuracy: 0.5312, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39221 | val 0.34262
  Epoch 020 - train 0.36850 | val 0.30155
  Epoch 030 - train 0.33447 | val 0.30974
  Epoch 039 - train 0.32729 | val 0.30686
  Regression -> MSE: 0.000116, MAE: 0.008732, R²: -0.2693
  Directional -> Accuracy: 0.5185, MCC: 0.1163, F1: 0.3158

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43255 | val 0.35367
  Epoch 020 - train 0.41264 | val 0.34844
  Epoch 030 - train 0.40048 | val 0.35579
  Epoch 040 - train 0.43221 | val 0.35222
  Epoch 042 - train 0.38298 | val 0.35621
  Regression -> MSE: 0.000097, MAE: 0.008425, R²: -0.0089
  Directional -> Accuracy: 0.4419, MCC: -0.0573, F1: 0.5000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.41108 | val 0.26299
  Epoch 020 - train 0.39006 | val 0.29576
  Epoch 027 - train 0.41823 | val 0.26332
  Regression -> MSE: 0.000278, MAE: 0.012913, R²: -0.0204
  Directional -> Accuracy: 0.5306, MCC: -0.2121, F1: 0.6933

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39623 | val 0.50219
  Epoch 020 - train 0.39327 | val 0.52245
  Epoch 030 - train 0.35934 | val 0.51445
  Epoch 031 - train 0.37596 | val 0.51360
  Regression -> MSE: 0.000230, MAE: 0.009742, R²: -0.3586
  Directional -> Accuracy: 0.5273, MCC: 0.2023, F1: 0.2778

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.38114 | val 0.34719
  Epoch 020 - train 0.41760 | val 0.32960
  Epoch 030 - train 0.38855 | val 0.28609
  Epoch 040 - train 0.36777 | val 0.29947
  Epoch 047 - train 0.37008 | val 0.32465
  Regression -> MSE: 0.000248, MAE: 0.012488, R²: 0.0114
  Directional -> Accuracy: 0.5263, MCC: -0.0671, F1: 0.6786

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42464 | val 0.82832
  Epoch 020 - train 0.39894 | val 0.89745
  Epoch 021 - train 0.40169 | val 0.87839
  Regression -> MSE: 0.000233, MAE: 0.009949, R²: 0.0018
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43282 | val 0.49286
  Epoch 020 - train 0.42017 | val 0.68565
  Epoch 028 - train 0.39876 | val 0.62353
  Regression -> MSE: 0.000149, MAE: 0.008404, R²: -0.0681
  Directional -> Accuracy: 0.6829, MCC: 0.3528, F1: 0.7234

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43981 | val 0.54108
  Epoch 020 - train 0.37468 | val 0.56999
  Epoch 030 - train 0.39842 | val 0.54708
  Epoch 032 - train 0.36607 | val 0.55536
  Regression -> MSE: 0.000191, MAE: 0.010235, R²: -0.0261
  Directional -> Accuracy: 0.6458, MCC: 0.3544, F1: 0.7385

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.33920 | val 0.52008
  Epoch 020 - train 0.33679 | val 0.50315
  Epoch 027 - train 0.31178 | val 0.51831
  Regression -> MSE: 0.000311, MAE: 0.011786, R²: -0.1658
  Directional -> Accuracy: 0.5211, MCC: 0.1508, F1: 0.3704

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37713 | val 0.45340
  Epoch 020 - train 0.34776 | val 0.46726
  Epoch 030 - train 0.34598 | val 0.52726
  Epoch 038 - train 0.33898 | val 0.49953
  Regression -> MSE: 0.000193, MAE: 0.010684, R²: -0.0300
  Directional -> Accuracy: 0.5000, MCC: 0.1489, F1: 0.6557

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.37200 | val 0.38735
  Epoch 020 - train 0.37086 | val 0.39787
  Epoch 027 - train 0.33643 | val 0.40329
  Regression -> MSE: 0.000366, MAE: 0.013175, R²: -0.0391
  Directional -> Accuracy: 0.4308, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.40968 | val 0.23944
  Epoch 020 - train 0.39047 | val 0.28001
  Epoch 030 - train 0.39689 | val 0.27993
  Regression -> MSE: 0.000158, MAE: 0.009299, R²: -0.4355
  Directional -> Accuracy: 0.5750, MCC: 0.2253, F1: 0.4138

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42196 | val 0.64432
  Epoch 020 - train 0.38988 | val 0.66269
  Epoch 021 - train 0.35242 | val 0.67137
  Regression -> MSE: 0.000223, MAE: 0.011385, R²: 0.0012
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41035 | val 0.85063
  Epoch 020 - train 0.37122 | val 1.09601
  Epoch 022 - train 0.38394 | val 1.16605
  Regression -> MSE: 0.000080, MAE: 0.006941, R²: -0.1303
  Directional -> Accuracy: 0.4444, MCC: 0.1296, F1: 0.2424

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.43251 | val 0.19811
  Epoch 020 - train 0.39301 | val 0.19952
  Epoch 027 - train 0.36303 | val 0.20331
  Regression -> MSE: 0.000361, MAE: 0.016029, R²: -0.1335
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.38665 | val 0.58629
  Epoch 020 - train 0.33337 | val 0.64449
  Epoch 024 - train 0.34752 | val 0.62468
  Regression -> MSE: 0.000076, MAE: 0.006808, R²: 0.0156
  Directional -> Accuracy: 0.5205, MCC: 0.1656, F1: 0.6729

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.42341 | val 0.59028
  Epoch 020 - train 0.38503 | val 0.58044
  Epoch 030 - train 0.40074 | val 0.60967
  Epoch 040 - train 0.37741 | val 0.60394
  Regression -> MSE: 0.000277, MAE: 0.013726, R²: 0.0059
  Directional -> Accuracy: 0.5227, MCC: 0.1525, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40469 | val 0.44847
  Epoch 020 - train 0.39674 | val 0.43346
  Epoch 030 - train 0.35962 | val 0.43333
  Epoch 040 - train 0.35702 | val 0.42660
  Epoch 050 - train 0.34883 | val 0.42975
  Regression -> MSE: 0.000108, MAE: 0.007157, R²: -0.0423
  Directional -> Accuracy: 0.5854, MCC: 0.0000, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.40084 | val 0.57099
  Epoch 020 - train 0.33626 | val 0.57086
  Epoch 021 - train 0.38524 | val 0.57273
  Regression -> MSE: 0.000180, MAE: 0.010183, R²: -0.0078
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397


[I 2026-02-23 22:49:32,203] Trial 5 finished with value: -0.01173615714265569 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 0.0005133093886270982, 'weight_decay': 2.073957985398117e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.964952927272992, 'early_stopping_min_delta': 0.0023978651024223717}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 026 - train 0.38580 | val 0.69603
  Regression -> MSE: 0.000242, MAE: 0.012587, R²: 0.0062
  Directional -> Accuracy: 0.5254, MCC: 0.1673, F1: 0.6585

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41872 | val 0.69357
  Epoch 016 - train 0.41501 | val 0.69559
  Regression -> MSE: 0.000245, MAE: 0.012438, R²: -0.0423
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.6168

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41667 | val 0.67641
  Epoch 016 - train 0.41707 | val 0.78967
  Regression -> MSE: 0.000718, MAE: 0.019843, R²: -0.0073
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.42201 | val 0.80892
  Epoch 020 - train 0.41038 | val 0.79325
  Epoch 030 - train 0.42819 | val 0.79217
  Epoch 031 - train 0.41354 | val 0.79225
  Regression -> MSE: 0.000320, MAE: 0.014334, R²: -0.0033
  Directional -> Accuracy: 0.5909, MCC: 0.3421, F1: 0.3571

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33484 | val 0.50409
  Epoch 016 - train 0.34569 | val 0.53229
  Regression -> MSE: 0.000417, MAE: 0.015784, R²: -0.1688
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41082 | val 0.42773
  Epoch 016 - train 0.42005 | val 0.42713
  Regression -> MSE: 0.000212, MAE: 0.010432, R²: -0.0099
  Directional -> Accuracy: 0.4583, MCC: -0.1521, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.38923 | val 0.78628
  Epoch 020 - train 0.37365 | val 0.78992
  Epoch 024 - train 0.37265 | val 0.78989
  Regression -> MSE: 0.000551, MAE: 0.017756, R²: 0.0170
  Directional -> Accuracy: 0.5682, MCC: 0.1400, F1: 0.6122

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.43872 | val 0.58040
  Epoch 016 - train 0.42852 | val 0.58430
  Regression -> MSE: 0.000265, MAE: 0.012346, R²: -0.0384
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39329 | val 0.45967
  Epoch 016 - train 0.39427 | val 0.48821
  Regression -> MSE: 0.000595, MAE: 0.019182, R²: -0.0277
  Directional -> Accuracy: 0.4615, MCC: -0.0366, F1: 0.5116

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.38991 | val 0.58018
  Epoch 016 - train 0.41538 | val 0.58321
  Regression -> MSE: 0.000386, MAE: 0.015822, R²: -0.0113
  Directional -> Accuracy: 0.4565, MCC: 0.0541, F1: 0.6032

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43875 | val 0.81128
  Epoch 016 - train 0.43290 | val 0.84019
  Regression -> MSE: 0.000251, MAE: 0.012335, R²: -0.0167
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.38049 | val 0.64743
  Epoch 020 - train 0.38349 | val 0.65266
  Epoch 023 - train 0.39132 | val 0.65278
  Regression -> MSE: 0.000368, MAE: 0.014217, R²: -0.1797
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.41124 | val 0.53985
  Epoch 016 - train 0.41239 | val 0.55610
  Regression -> MSE: 0.000693, MAE: 0.019839, R²: 0.0035
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41600 | val 0.41681
  Epoch 016 - train 0.39625 | val 0.43598
  Regression -> MSE: 0.000146, MAE: 0.009531, R²: -0.0084
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.6479

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.36668 | val 0.63888
  Epoch 016 - train 0.36995 | val 0.63900
  Regression -> MSE: 0.000229, MAE: 0.010721, R²: 0.0002
  Directional -> Accuracy: 0.5345, MCC: 0.0860, F1: 0.6824

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42261 | val 1.05117
  Epoch 020 - train 0.41326 | val 1.04730
  Epoch 027 - train 0.42110 | val 1.04796
  Regression -> MSE: 0.000376, MAE: 0.016460, R²: -0.0054
  Directional -> Accuracy: 0.4490, MCC: -0.0212, F1: 0.6087

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43064 | val 0.44496
  Epoch 016 - train 0.42891 | val 0.44872
  Regression -> MSE: 0.000109, MAE: 0.008075, R²: 0.0055
  Directional -> Accuracy: 0.4776, MCC: 0.0562, F1: 0.1026

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38669 | val 0.90245
  Epoch 016 - train 0.37690 | val 0.91677
  Regression -> MSE: 0.000153, MAE: 0.009853, R²: -0.0121
  Directional -> Accuracy: 0.5536, MCC: -0.0829, F1: 0.6988

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.40970 | val 0.44473
  Epoch 016 - train 0.41490 | val 0.45133
  Regression -> MSE: 0.000278, MAE: 0.013177, R²: -0.0040
  Directional -> Accuracy: 0.5890, MCC: 0.0000, F1: 0.7414

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36974 | val 0.63125
  Epoch 016 - train 0.37240 | val 0.62901
  Regression -> MSE: 0.000158, MAE: 0.009025, R²: -0.0280
  Directional -> Accuracy: 0.5645, MCC: 0.2511, F1: 0.4706

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44659 | val 0.80960
  Epoch 016 - train 0.45604 | val 0.80600
  Regression -> MSE: 0.000251, MAE: 0.011473, R²: -0.1013
  Directional -> Accuracy: 0.3611, MCC: -0.2795, F1: 0.3947

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42589 | val 0.61908
  Epoch 016 - train 0.44294 | val 0.64361
  Regression -> MSE: 0.000154, MAE: 0.008568, R²: -0.0438
  Directional -> Accuracy: 0.6000, MCC: 0.1996, F1: 0.6400

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.50318 | val 0.65609
  Epoch 016 - train 0.49975 | val 0.71245
  Regression -> MSE: 0.000174, MAE: 0.011080, R²: -0.0185
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43681 | val 0.56298
  Epoch 016 - train 0.45310 | val 0.56517
  Regression -> MSE: 0.000093, MAE: 0.007452, R²: -0.0479
  Directional -> Accuracy: 0.4545, MCC: -0.0602, F1: 0.4444

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42078 | val 0.60757
  Epoch 016 - train 0.42409 | val 0.65035
  Regression -> MSE: 0.000218, MAE: 0.011151, R²: -0.0061
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37359 | val 0.41500
  Epoch 016 - train 0.37676 | val 0.41006
  Regression -> MSE: 0.000101, MAE: 0.008067, R²: -0.1216
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.45015 | val 0.53007
  Epoch 016 - train 0.45123 | val 0.56363
  Regression -> MSE: 0.000122, MAE: 0.009234, R²: -0.3288
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44873 | val 0.30123
  Epoch 016 - train 0.44084 | val 0.33985
  Regression -> MSE: 0.000283, MAE: 0.013262, R²: -0.0180
  Directional -> Accuracy: 0.6042, MCC: 0.1726, F1: 0.7467

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41338 | val 0.59385
  Epoch 016 - train 0.40991 | val 0.60533
  Regression -> MSE: 0.000178, MAE: 0.007824, R²: -0.0386
  Directional -> Accuracy: 0.5370, MCC: 0.0146, F1: 0.6914

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41856 | val 0.85006
  Epoch 020 - train 0.42872 | val 0.85614
  Epoch 022 - train 0.42003 | val 0.85739
  Regression -> MSE: 0.000245, MAE: 0.010447, R²: -0.0216
  Directional -> Accuracy: 0.4750, MCC: -0.0949, F1: 0.6316

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43986 | val 0.46026
  Epoch 016 - train 0.42815 | val 0.46790
  Regression -> MSE: 0.000147, MAE: 0.008535, R²: -0.0321
  Directional -> Accuracy: 0.5250, MCC: -0.0668, F1: 0.6780

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43317 | val 0.58387
  Epoch 016 - train 0.42537 | val 0.58555
  Regression -> MSE: 0.000192, MAE: 0.010440, R²: -0.0064
  Directional -> Accuracy: 0.5532, MCC: 0.1224, F1: 0.4615

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.39391 | val 0.58674
  Epoch 016 - train 0.37965 | val 0.59644
  Regression -> MSE: 0.000280, MAE: 0.010855, R²: -0.0550
  Directional -> Accuracy: 0.4429, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.36732 | val 0.39932
  Epoch 016 - train 0.35385 | val 0.41049
  Regression -> MSE: 0.000214, MAE: 0.011160, R²: -0.0250
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41319 | val 0.41362
  Epoch 016 - train 0.41853 | val 0.42285
  Regression -> MSE: 0.000368, MAE: 0.012127, R²: -0.0294
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44531 | val 0.29195
  Epoch 016 - train 0.45205 | val 0.29744
  Regression -> MSE: 0.000110, MAE: 0.007873, R²: -0.1365
  Directional -> Accuracy: 0.5102, MCC: 0.0042, F1: 0.0769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42298 | val 0.76525
  Epoch 016 - train 0.41965 | val 0.77032
  Regression -> MSE: 0.000223, MAE: 0.011413, R²: -0.0270
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.6329

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44550 | val 0.98028
  Epoch 016 - train 0.45396 | val 1.02754
  Regression -> MSE: 0.000074, MAE: 0.006616, R²: -0.0341
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45866 | val 0.30683
  Epoch 016 - train 0.46682 | val 0.31172
  Regression -> MSE: 0.000312, MAE: 0.014327, R²: -0.0461
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.52933 | val 0.61585
  Epoch 016 - train 0.51362 | val 0.62322
  Regression -> MSE: 0.000086, MAE: 0.007041, R²: -0.1039
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44126 | val 0.66252
  Epoch 020 - train 0.44389 | val 0.65468
  Epoch 030 - train 0.43052 | val 0.65256
  Epoch 032 - train 0.43638 | val 0.65228
  Regression -> MSE: 0.000296, MAE: 0.014215, R²: -0.0462
  Directional -> Accuracy: 0.4884, MCC: -0.0641, F1: 0.6333

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42696 | val 0.38880
  Epoch 016 - train 0.44693 | val 0.40488
  Regression -> MSE: 0.000114, MAE: 0.008133, R²: -0.0454
  Directional -> Accuracy: 0.4103, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.43885 | val 0.61833
  Epoch 020 - train 0.44322 | val 0.61660
  Epoch 027 - train 0.43469 | val 0.61777
  Regression -> MSE: 0.000187, MAE: 0.010020, R²: -0.0259
  Directional -> Accuracy: 0.4889, MCC: -0.1960, F1: 0.1481

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.39202 | val 0.52684
  Epoch 016 - train 0.39804 | val 0.52872
  Regression -> MSE: 0.000253, MAE: 0.012466, R²: -0.0938
  Directional -> Accuracy: 0.4528, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42187 | val 0.60909
  Epoch 016 - train 0.41910 | val 0.64254
  Regression -> MSE: 0.000089, MAE: 0.007559, R²: -0.0123
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.43351 | val 0.78008
  Epoch 016 - train 0.43284 | val 0.79019
  Regression -> MSE: 0.000172, MAE: 0.010553, R²: -0.0112
  Directional -> Accuracy: 0.4314, MCC: -0.2043, F1: 0.5915

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41196 | val 0.60101
  Epoch 016 - train 0.40017 | val 0.60702
  Regression -> MSE: 0.000126, MAE: 0.009199, R²: -0.0633
  Directional -> Accuracy: 0.4717, MCC: -0.0863, F1: 0.0667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.41433 | val 0.74760

[I 2026-02-23 22:50:29,492] Trial 6 finished with value: -0.01159453935414421 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiGRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 4.285326878819229e-06, 'weight_decay': 1.2587865967366938e-06, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 15, 'max_epochs': 50, 'huber_delta': 1.0325585953889227, 'early_stopping_min_delta': 0.008728618197144435}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 016 - train 0.41989 | val 0.74718
  Regression -> MSE: 0.000253, MAE: 0.012680, R²: -0.0227
  Directional -> Accuracy: 0.5345, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.49793 | val 0.76148
  Epoch 020 - train 0.45706 | val 0.74473
  Regression -> MSE: 0.000276, MAE: 0.013231, R²: -0.1218
  Directional -> Accuracy: 0.4430, MCC: 0.0000, F1: 0.6140

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53712 | val 0.40575
  Epoch 015 - train 0.47182 | val 0.44542
  Regression -> MSE: 0.000661, MAE: 0.019097, R²: 0.0232
  Directional -> Accuracy: 0.6667, MCC: 0.3295, F1: 0.7576

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.57392 | val 1.28699
  Epoch 011 - train 0.58600 | val 1.33678
  Regression -> MSE: 0.000352, MAE: 0.015369, R²: -0.0128
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.44565 | val 0.42131
  Epoch 011 - train 0.44752 | val 0.41640
  Regression -> MSE: 0.000356, MAE: 0.014765, R²: -0.0035
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.55490 | val 0.49488
  Epoch 011 - train 0.52590 | val 0.50298
  Regression -> MSE: 0.000200, MAE: 0.010176, R²: -0.0067
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.45492 | val 1.17803
  Epoch 011 - train 0.46256 | val 1.18063
  Regression -> MSE: 0.000498, MAE: 0.017193, R²: -0.0036
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.51458 | val 0.66258
  Epoch 011 - train 0.50793 | val 0.66615
  Regression -> MSE: 0.000261, MAE: 0.012302, R²: -0.0186
  Directional -> Accuracy: 0.5915, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.58760 | val 0.59142
  Epoch 019 - train 0.55998 | val 0.59423
  Regression -> MSE: 0.000581, MAE: 0.018717, R²: -0.0254
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.53902 | val 0.68422
  Epoch 011 - train 0.50850 | val 0.68446
  Regression -> MSE: 0.000388, MAE: 0.015709, R²: -0.0096
  Directional -> Accuracy: 0.4419, MCC: -0.0852, F1: 0.4286

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52927 | val 0.71217
  Epoch 011 - train 0.51031 | val 0.71570
  Regression -> MSE: 0.000244, MAE: 0.011513, R²: -0.0220
  Directional -> Accuracy: 0.5694, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.46649 | val 0.86103
  Epoch 011 - train 0.43304 | val 0.87306
  Regression -> MSE: 0.000308, MAE: 0.013710, R²: -0.0017
  Directional -> Accuracy: 0.5000, MCC: 0.0740, F1: 0.6176

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.51768 | val 0.61662
  Epoch 011 - train 0.52849 | val 0.62865
  Regression -> MSE: 0.000654, MAE: 0.019094, R²: 0.0077
  Directional -> Accuracy: 0.5667, MCC: 0.2673, F1: 0.6977

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49962 | val 0.46993
  Epoch 011 - train 0.48238 | val 0.47133
  Regression -> MSE: 0.000147, MAE: 0.009456, R²: 0.0014
  Directional -> Accuracy: 0.4444, MCC: -0.1612, F1: 0.6154

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44218 | val 0.68465
  Epoch 011 - train 0.44634 | val 0.68456
  Regression -> MSE: 0.000228, MAE: 0.010918, R²: -0.0117
  Directional -> Accuracy: 0.4603, MCC: -0.2201, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.54699 | val 1.29093
  Epoch 011 - train 0.50001 | val 1.29737
  Regression -> MSE: 0.000404, MAE: 0.016529, R²: -0.0534
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.52384 | val 0.53545
  Epoch 011 - train 0.52159 | val 0.53941
  Regression -> MSE: 0.000105, MAE: 0.007833, R²: 0.0008
  Directional -> Accuracy: 0.5278, MCC: -0.0196, F1: 0.6731

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.48496 | val 1.12446
  Epoch 011 - train 0.48592 | val 1.15323
  Regression -> MSE: 0.000158, MAE: 0.009663, R²: -0.0005
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.56133 | val 0.53982
  Epoch 011 - train 0.56795 | val 0.57284
  Regression -> MSE: 0.000277, MAE: 0.013311, R²: -0.0220
  Directional -> Accuracy: 0.4744, MCC: -0.1961, F1: 0.6168

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.47414 | val 0.72603
  Epoch 016 - train 0.47800 | val 0.72491
  Regression -> MSE: 0.000166, MAE: 0.009190, R²: -0.0736
  Directional -> Accuracy: 0.5672, MCC: -0.1043, F1: 0.7238

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.47483 | val 0.94196
  Epoch 014 - train 0.50656 | val 0.97235
  Regression -> MSE: 0.000253, MAE: 0.011517, R²: -0.0910
  Directional -> Accuracy: 0.4545, MCC: -0.0149, F1: 0.0455

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.52037 | val 0.71327
  Epoch 011 - train 0.49571 | val 0.72584
  Regression -> MSE: 0.000152, MAE: 0.008844, R²: -0.0225
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.45678 | val 0.54554
  Epoch 011 - train 0.45082 | val 0.54591
  Regression -> MSE: 0.000182, MAE: 0.011070, R²: -0.0032
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51232 | val 0.65225
  Epoch 011 - train 0.53516 | val 0.65170
  Regression -> MSE: 0.000084, MAE: 0.006971, R²: -0.0176
  Directional -> Accuracy: 0.6000, MCC: 0.1973, F1: 0.6364

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.51008 | val 0.64482
  Epoch 011 - train 0.54328 | val 0.64508
  Regression -> MSE: 0.000227, MAE: 0.011271, R²: -0.0547
  Directional -> Accuracy: 0.5147, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.44993 | val 0.34316
  Epoch 011 - train 0.46720 | val 0.34542
  Regression -> MSE: 0.000090, MAE: 0.007961, R²: -0.0003
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.62326 | val 0.21855
  Epoch 011 - train 0.61082 | val 0.22309
  Regression -> MSE: 0.000124, MAE: 0.009147, R²: 0.0055
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.51734 | val 0.21736
  Epoch 011 - train 0.50643 | val 0.22068
  Regression -> MSE: 0.000303, MAE: 0.013822, R²: -0.0393
  Directional -> Accuracy: 0.6444, MCC: 0.2136, F1: 0.7500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.51187 | val 0.65483
  Epoch 011 - train 0.53348 | val 0.66094
  Regression -> MSE: 0.000169, MAE: 0.007763, R²: -0.0460
  Directional -> Accuracy: 0.5593, MCC: 0.0000, F1: 0.7174

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.51231 | val 0.44993
  Epoch 011 - train 0.51224 | val 0.45403
  Regression -> MSE: 0.000233, MAE: 0.011885, R²: -0.0112
  Directional -> Accuracy: 0.5227, MCC: 0.0666, F1: 0.4324

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50640 | val 0.74260
  Epoch 011 - train 0.48609 | val 0.74478
  Regression -> MSE: 0.000260, MAE: 0.010788, R²: -0.0032
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.51014 | val 0.67104
  Epoch 020 - train 0.53413 | val 0.66470
  Regression -> MSE: 0.000139, MAE: 0.008600, R²: 0.0092
  Directional -> Accuracy: 0.5000, MCC: -0.0371, F1: 0.5965

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.53289 | val 0.69681
  Epoch 011 - train 0.53156 | val 0.69695
  Regression -> MSE: 0.000186, MAE: 0.010402, R²: -0.0008
  Directional -> Accuracy: 0.5385, MCC: 0.0716, F1: 0.6667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.42280 | val 0.61303
  Epoch 015 - train 0.45485 | val 0.61684
  Regression -> MSE: 0.000288, MAE: 0.011302, R²: -0.1044
  Directional -> Accuracy: 0.4400, MCC: -0.0418, F1: 0.1600

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47951 | val 0.49568
  Epoch 011 - train 0.49856 | val 0.49561
  Regression -> MSE: 0.000160, MAE: 0.010085, R²: 0.0138
  Directional -> Accuracy: 0.5610, MCC: 0.1407, F1: 0.6250

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.43125 | val 0.52233
  Epoch 011 - train 0.43674 | val 0.54009
  Regression -> MSE: 0.000215, MAE: 0.011111, R²: -0.0034
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48567 | val 0.46047
  Epoch 011 - train 0.47214 | val 0.46164
  Regression -> MSE: 0.000350, MAE: 0.012219, R²: -0.0159
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56212 | val 0.27894
  Epoch 011 - train 0.57946 | val 0.27919
  Regression -> MSE: 0.000116, MAE: 0.008194, R²: -0.1425
  Directional -> Accuracy: 0.4889, MCC: -0.0069, F1: 0.1481

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.57512 | val 0.92207
  Epoch 011 - train 0.57346 | val 0.94798
  Regression -> MSE: 0.000220, MAE: 0.011281, R²: -0.0382
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.48653 | val 1.17784
  Epoch 011 - train 0.47652 | val 1.18293
  Regression -> MSE: 0.000088, MAE: 0.007366, R²: -0.1080
  Directional -> Accuracy: 0.3673, MCC: -0.2119, F1: 0.3404

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.47788 | val 0.33910
  Epoch 020 - train 0.48586 | val 0.31451
  Regression -> MSE: 0.000321, MAE: 0.012871, R²: -0.0218
  Directional -> Accuracy: 0.6667, MCC: 0.1147, F1: 0.2222

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.53169 | val 0.21562
  Epoch 020 - train 0.51610 | val 0.20470
  Regression -> MSE: 0.000238, MAE: 0.011116, R²: -0.0417
  Directional -> Accuracy: 0.4878, MCC: -0.0655, F1: 0.6316

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.55687 | val 0.70683
  Epoch 011 - train 0.52405 | val 0.72274
  Regression -> MSE: 0.000087, MAE: 0.007208, R²: -0.0632
  Directional -> Accuracy: 0.4935, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.56903 | val 0.50195
  Epoch 011 - train 0.53254 | val 0.50656
  Regression -> MSE: 0.000389, MAE: 0.015723, R²: -0.0507
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.52186 | val 0.58387
  Epoch 020 - train 0.50949 | val 0.56794
  Regression -> MSE: 0.000099, MAE: 0.007215, R²: -0.0417
  Directional -> Accuracy: 0.5745, MCC: 0.0981, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54566 | val 0.78389
  Epoch 020 - train 0.53553 | val 0.78401
  Regression -> MSE: 0.000200, MAE: 0.011136, R²: -0.0485
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.48015 | val 0.64147
  Epoch 011 - train 0.50753 | val 0.65768
  Regression -> MSE: 0.000221, MAE: 0.011592, R²: -0.0209
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.46874 | val 0.64362
  Epoch 011 - train 0.47806 | val 0.65825
  Regression -> MSE: 0.000091, MAE: 0.007567, R²: -0.0109
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.54707 | val 1.00339
  Epoch 011 - train 0.52111 | val 1.00562
  Regression -> MSE: 0.000162, MAE: 0.010119, R²: -0.0214
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.54661 | val 0.72060
  Epoch 011 - train 0.54550 | val 0.72616
  Regression -> MSE: 0.000112, MAE: 0.008608, R²: 0.0003
  Directional -> Accuracy: 0.5517, MCC: 0.1956, F1: 0.6977

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 22:50:49,093] Trial 7 finished with value: -0.011491777952554828 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'GRU', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 1.5296818198921999e-06, 'weight_decay': 3.61882290390357e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.8500904007094678, 'early_stopping_min_delta': 0.00529299843068477}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.51164 | val 0.89282
  Epoch 011 - train 0.51760 | val 0.89487
  Regression -> MSE: 0.000233, MAE: 0.012056, R²: -0.0126
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.21425 | val 0.38872
  Epoch 011 - train 0.20749 | val 0.41870
  Regression -> MSE: 0.000256, MAE: 0.012804, R²: -0.0407
  Directional -> Accuracy: 0.5385, MCC: 0.2174, F1: 0.6471

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.24232 | val 0.24552
  Epoch 016 - train 0.19895 | val 0.23021
  Regression -> MSE: 0.000722, MAE: 0.019646, R²: -0.0443
  Directional -> Accuracy: 0.5532, MCC: 0.0226, F1: 0.7042

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.25535 | val 0.49031
  Epoch 012 - train 0.23107 | val 0.58643
  Regression -> MSE: 0.000376, MAE: 0.015104, R²: -0.0887
  Directional -> Accuracy: 0.4792, MCC: 0.0399, F1: 0.1935

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.19227 | val 0.52636
  Epoch 017 - train 0.17745 | val 1.22790
  Regression -> MSE: 0.000384, MAE: 0.015245, R²: -0.1140
  Directional -> Accuracy: 0.4868, MCC: 0.0996, F1: 0.1333

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.21425 | val 0.27044
  Epoch 014 - train 0.19754 | val 0.37004
  Regression -> MSE: 0.000215, MAE: 0.009810, R²: -0.0718
  Directional -> Accuracy: 0.7115, MCC: 0.4173, F1: 0.7458

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.21720 | val 0.57546
  Epoch 011 - train 0.20450 | val 0.53910
  Regression -> MSE: 0.000559, MAE: 0.018176, R²: 0.0239
  Directional -> Accuracy: 0.6327, MCC: 0.2671, F1: 0.6250

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.23814 | val 0.41777
  Epoch 012 - train 0.22339 | val 0.44359
  Regression -> MSE: 0.000268, MAE: 0.012794, R²: -0.0903
  Directional -> Accuracy: 0.4571, MCC: -0.0702, F1: 0.4242

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.21945 | val 0.55240
  Epoch 011 - train 0.24371 | val 0.82349
  Regression -> MSE: 0.000670, MAE: 0.020250, R²: -0.1463
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.24522 | val 0.36970
  Epoch 016 - train 0.20623 | val 0.48387
  Regression -> MSE: 0.000388, MAE: 0.017030, R²: -0.1475
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.22717 | val 0.62073
  Epoch 011 - train 0.21552 | val 0.84839
  Regression -> MSE: 0.000235, MAE: 0.011415, R²: 0.0123
  Directional -> Accuracy: 0.5775, MCC: 0.1411, F1: 0.5161

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.21186 | val 0.66140
  Epoch 011 - train 0.19796 | val 0.78811
  Regression -> MSE: 0.000311, MAE: 0.013403, R²: -0.0161
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.23424 | val 0.37677
  Epoch 016 - train 0.22599 | val 0.57503
  Regression -> MSE: 0.000663, MAE: 0.019542, R²: 0.0094
  Directional -> Accuracy: 0.5424, MCC: 0.1394, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.23159 | val 0.70294
  Epoch 011 - train 0.22735 | val 0.53242
  Regression -> MSE: 0.000160, MAE: 0.010134, R²: -0.0681
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.21240 | val 0.38561
  Epoch 011 - train 0.21376 | val 0.38153
  Regression -> MSE: 0.000228, MAE: 0.010938, R²: -0.0156
  Directional -> Accuracy: 0.5484, MCC: 0.1022, F1: 0.6111

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.20369 | val 1.51490
  Epoch 011 - train 0.20668 | val 1.01374
  Regression -> MSE: 0.000381, MAE: 0.016722, R²: -0.0148
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.23831 | val 0.39032
  Epoch 011 - train 0.23739 | val 0.34587
  Regression -> MSE: 0.000107, MAE: 0.007948, R²: -0.0016
  Directional -> Accuracy: 0.4789, MCC: -0.0187, F1: 0.3934

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.22344 | val 0.56523
  Epoch 011 - train 0.21214 | val 0.59122
  Regression -> MSE: 0.000177, MAE: 0.010778, R²: -0.1080
  Directional -> Accuracy: 0.4333, MCC: -0.2192, F1: 0.5526

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.21421 | val 0.65887
  Epoch 011 - train 0.21010 | val 0.59070
  Regression -> MSE: 0.000279, MAE: 0.012852, R²: -0.0386
  Directional -> Accuracy: 0.5974, MCC: 0.0777, F1: 0.7156

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.20818 | val 0.41731
  Epoch 015 - train 0.19167 | val 0.33576
  Regression -> MSE: 0.000295, MAE: 0.013786, R²: -1.0032
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.24293 | val 0.44037
  Epoch 020 - train 0.20309 | val 0.41822
  Regression -> MSE: 0.000571, MAE: 0.019162, R²: -1.5193
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.22994 | val 0.54277
  Epoch 011 - train 0.20212 | val 0.44457
  Regression -> MSE: 0.000157, MAE: 0.008942, R²: -0.0565
  Directional -> Accuracy: 0.5510, MCC: 0.2661, F1: 0.5000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.22148 | val 0.34999
  Epoch 011 - train 0.22382 | val 0.33047
  Regression -> MSE: 0.000184, MAE: 0.010316, R²: -0.0404
  Directional -> Accuracy: 0.5672, MCC: 0.1508, F1: 0.4727

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.24165 | val 0.51365
  Epoch 011 - train 0.24075 | val 0.57627
  Regression -> MSE: 0.000086, MAE: 0.007017, R²: -0.0226
  Directional -> Accuracy: 0.6441, MCC: 0.2485, F1: 0.7273

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.22529 | val 0.31970
  Epoch 020 - train 0.20209 | val 0.53406
  Regression -> MSE: 0.000223, MAE: 0.011461, R²: -0.0223
  Directional -> Accuracy: 0.5373, MCC: 0.0832, F1: 0.5634

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.18699 | val 0.18938
  Epoch 013 - train 0.18463 | val 0.21712
  Regression -> MSE: 0.000115, MAE: 0.009130, R²: -0.2521
  Directional -> Accuracy: 0.3860, MCC: -0.2416, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.24618 | val 0.52550
  Epoch 011 - train 0.23713 | val 0.66615
  Regression -> MSE: 0.000124, MAE: 0.009079, R²: 0.0119
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.25544 | val 0.51219
  Epoch 011 - train 0.25722 | val 0.73906
  Regression -> MSE: 0.000260, MAE: 0.013320, R²: -0.0913
  Directional -> Accuracy: 0.4545, MCC: 0.1816, F1: 0.1429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.21241 | val 0.39028
  Epoch 011 - train 0.22145 | val 0.38372
  Regression -> MSE: 0.000288, MAE: 0.012031, R²: -0.7586
  Directional -> Accuracy: 0.4483, MCC: -0.0197, F1: 0.0588

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22332 | val 0.19886
  Epoch 020 - train 0.18660 | val 0.24373
  Regression -> MSE: 0.000216, MAE: 0.011834, R²: 0.0782
  Directional -> Accuracy: 0.5349, MCC: 0.0435, F1: 0.6296

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.24546 | val 0.55454
  Epoch 016 - train 0.21973 | val 0.44789
  Regression -> MSE: 0.000266, MAE: 0.011720, R²: -0.0638
  Directional -> Accuracy: 0.4444, MCC: -0.1188, F1: 0.2424

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.24281 | val 0.83818
  Epoch 012 - train 0.22492 | val 0.79828
  Regression -> MSE: 0.000139, MAE: 0.008386, R²: -0.0441
  Directional -> Accuracy: 0.4222, MCC: -0.1429, F1: 0.2353

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.23104 | val 0.36616
  Epoch 011 - train 0.21250 | val 0.38693
  Regression -> MSE: 0.000188, MAE: 0.010326, R²: -0.0005
  Directional -> Accuracy: 0.6275, MCC: 0.3089, F1: 0.7324

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.19237 | val 0.35358
  Epoch 014 - train 0.18421 | val 0.32879
  Regression -> MSE: 0.000389, MAE: 0.013975, R²: -0.5058
  Directional -> Accuracy: 0.5676, MCC: 0.1969, F1: 0.5152

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.22617 | val 0.23856
  Epoch 011 - train 0.23293 | val 0.23618
  Regression -> MSE: 0.000154, MAE: 0.009901, R²: 0.0544
  Directional -> Accuracy: 0.5128, MCC: 0.0263, F1: 0.5128

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.19409 | val 0.53584
  Epoch 011 - train 0.21845 | val 0.53694
  Regression -> MSE: 0.000188, MAE: 0.010637, R²: -0.0305
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.21159 | val 0.39922
  Epoch 011 - train 0.19978 | val 0.28062
  Regression -> MSE: 0.000515, MAE: 0.017936, R²: -0.4746
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.23435 | val 0.20229
  Epoch 011 - train 0.23337 | val 0.28255
  Regression -> MSE: 0.000113, MAE: 0.007949, R²: -0.0876
  Directional -> Accuracy: 0.6591, MCC: 0.3674, F1: 0.5455

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.22749 | val 0.49057
  Epoch 011 - train 0.21720 | val 0.40053
  Regression -> MSE: 0.000219, MAE: 0.011228, R²: -0.0176
  Directional -> Accuracy: 0.4828, MCC: -0.1335, F1: 0.1176

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.21702 | val 0.58422
  Epoch 012 - train 0.20505 | val 0.58441
  Regression -> MSE: 0.000099, MAE: 0.007929, R²: -0.2466
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.2632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.23432 | val 0.22097
  Epoch 016 - train 0.21871 | val 0.20373
  Regression -> MSE: 0.000594, MAE: 0.018503, R²: -0.8093
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.24420 | val 0.23610
  Epoch 013 - train 0.21823 | val 0.23030
  Regression -> MSE: 0.000247, MAE: 0.011409, R²: -0.0397
  Directional -> Accuracy: 0.4103, MCC: -0.2629, F1: 0.5490

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.21694 | val 0.37050
  Epoch 014 - train 0.21278 | val 0.48365
  Regression -> MSE: 0.000115, MAE: 0.008688, R²: -0.4291
  Directional -> Accuracy: 0.5132, MCC: 0.0531, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.22497 | val 0.33861
  Epoch 011 - train 0.21578 | val 0.42347
  Regression -> MSE: 0.000339, MAE: 0.014982, R²: 0.0581
  Directional -> Accuracy: 0.5625, MCC: 0.1307, F1: 0.6182

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.23144 | val 0.41103
  Epoch 015 - train 0.17765 | val 0.39419
  Regression -> MSE: 0.000102, MAE: 0.007787, R²: -0.0510
  Directional -> Accuracy: 0.5333, MCC: 0.0598, F1: 0.5714

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.24485 | val 0.62634
  Epoch 011 - train 0.22221 | val 0.70314
  Regression -> MSE: 0.000211, MAE: 0.011770, R²: -0.1662
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.21458 | val 1.13763
  Epoch 011 - train 0.21201 | val 1.09561
  Regression -> MSE: 0.000282, MAE: 0.013231, R²: -0.2835
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.21893 | val 0.73452
  Epoch 012 - train 0.21677 | val 0.69319
  Regression -> MSE: 0.000134, MAE: 0.009870, R²: -0.4705
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.25189 | val 0.46996
  Epoch 011 - train 0.23771 | val 0.47297
  Regression -> MSE: 0.000171, MAE: 0.010511, R²: -0.0643
  Directional -> Accuracy: 0.3818, MCC: -0.2379, F1: 0.2273

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.21773 | val 0.35696
  Epoch 012 - train 0.21060 | val 0.38726
  Regression -> MSE: 0.000120, MAE: 0.008982, R²: -0.0559
  Directional -> Accuracy: 0.5088, MCC: 0.0033, F1: 0.6667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.23004 | val 1.22482

[I 2026-02-23 22:52:42,538] Trial 8 finished with value: -0.012375765591170589 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.0021612726884053185, 'weight_decay': 0.0001739182035206773, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.46537541845137104, 'early_stopping_min_delta': 0.004758503742604154}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 011 - train 0.25142 | val 1.24448
  Regression -> MSE: 0.000237, MAE: 0.012400, R²: -0.0133
  Directional -> Accuracy: 0.5161, MCC: 0.0547, F1: 0.6053

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.48237 | val 0.84360
  Epoch 011 - train 0.43904 | val 0.84772
  Regression -> MSE: 0.000249, MAE: 0.012657, R²: -0.0160
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.50847 | val 0.45611
  Epoch 011 - train 0.52574 | val 0.45673
  Regression -> MSE: 0.000729, MAE: 0.020277, R²: -0.0545
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.55584 | val 1.15895
  Epoch 011 - train 0.56398 | val 1.16439
  Regression -> MSE: 0.000356, MAE: 0.015412, R²: -0.0313
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.43934 | val 0.44644
  Epoch 011 - train 0.43236 | val 0.44252
  Regression -> MSE: 0.000349, MAE: 0.014499, R²: -0.0117
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.49711 | val 0.47782
  Epoch 011 - train 0.49335 | val 0.46808
  Regression -> MSE: 0.000204, MAE: 0.009965, R²: -0.0156
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47142 | val 1.13609
  Epoch 011 - train 0.46052 | val 1.13653
  Regression -> MSE: 0.000566, MAE: 0.018245, R²: 0.0105
  Directional -> Accuracy: 0.6122, MCC: 0.2582, F1: 0.5128

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.48996 | val 0.66790
  Epoch 014 - train 0.49928 | val 0.67109
  Regression -> MSE: 0.000248, MAE: 0.012313, R²: -0.0085
  Directional -> Accuracy: 0.4286, MCC: -0.0155, F1: 0.5349

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48976 | val 0.76046
  Epoch 011 - train 0.48071 | val 0.76602
  Regression -> MSE: 0.000616, MAE: 0.019428, R²: -0.0538
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.51949 | val 0.89223
  Epoch 011 - train 0.52703 | val 0.89525
  Regression -> MSE: 0.000341, MAE: 0.015191, R²: -0.0099
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52052 | val 0.75021
  Epoch 011 - train 0.49408 | val 0.75542
  Regression -> MSE: 0.000242, MAE: 0.011732, R²: -0.0169
  Directional -> Accuracy: 0.5352, MCC: 0.0169, F1: 0.3529

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.47446 | val 1.04856
  Epoch 011 - train 0.45234 | val 1.04953
  Regression -> MSE: 0.000311, MAE: 0.013745, R²: -0.0160
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50315 | val 0.60632
  Epoch 011 - train 0.47415 | val 0.60898
  Regression -> MSE: 0.000667, MAE: 0.019424, R²: 0.0038
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.52542 | val 0.92103
  Epoch 011 - train 0.49877 | val 0.94721
  Regression -> MSE: 0.000150, MAE: 0.009339, R²: -0.0009
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44538 | val 0.71565
  Epoch 020 - train 0.45459 | val 0.69871
  Regression -> MSE: 0.000227, MAE: 0.010901, R²: -0.0102
  Directional -> Accuracy: 0.5161, MCC: 0.0325, F1: 0.4828

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51672 | val 1.45014
  Epoch 011 - train 0.50341 | val 1.45784
  Regression -> MSE: 0.000378, MAE: 0.016618, R²: -0.0063
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.50686 | val 0.55732
  Epoch 011 - train 0.51535 | val 0.55806
  Regression -> MSE: 0.000105, MAE: 0.007905, R²: 0.0084
  Directional -> Accuracy: 0.5211, MCC: 0.1070, F1: 0.3462

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.52591 | val 1.14882
  Epoch 011 - train 0.54420 | val 1.14374
  Regression -> MSE: 0.000163, MAE: 0.009722, R²: -0.0181
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47038 | val 0.50470
  Epoch 011 - train 0.47974 | val 0.51295
  Regression -> MSE: 0.000286, MAE: 0.013648, R²: -0.0643
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.43519 | val 0.90024
  Epoch 011 - train 0.46993 | val 0.89575
  Regression -> MSE: 0.000153, MAE: 0.008769, R²: -0.0360
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.53853 | val 1.12277
  Epoch 011 - train 0.52687 | val 1.11148
  Regression -> MSE: 0.000237, MAE: 0.011509, R²: -0.0474
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51934 | val 0.70745
  Epoch 011 - train 0.51239 | val 0.70526
  Regression -> MSE: 0.000165, MAE: 0.009235, R²: -0.1118
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.47521 | val 0.56070
  Epoch 011 - train 0.46911 | val 0.56109
  Regression -> MSE: 0.000187, MAE: 0.010859, R²: -0.0583
  Directional -> Accuracy: 0.4478, MCC: -0.1613, F1: 0.5934

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.59957 | val 0.68740
  Epoch 011 - train 0.55606 | val 0.68664
  Regression -> MSE: 0.000091, MAE: 0.007341, R²: -0.0830
  Directional -> Accuracy: 0.4237, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.50248 | val 0.79953
  Epoch 011 - train 0.50182 | val 0.79476
  Regression -> MSE: 0.000217, MAE: 0.011409, R²: 0.0074
  Directional -> Accuracy: 0.4627, MCC: -0.0642, F1: 0.6087

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.44194 | val 0.30514
  Epoch 020 - train 0.44808 | val 0.29933
  Regression -> MSE: 0.000110, MAE: 0.008506, R²: -0.1965
  Directional -> Accuracy: 0.5439, MCC: 0.1587, F1: 0.4583

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.51530 | val 0.24468
  Epoch 011 - train 0.53656 | val 0.25198
  Regression -> MSE: 0.000132, MAE: 0.009460, R²: -0.0483
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.55479 | val 0.51443
  Epoch 011 - train 0.56501 | val 0.52388
  Regression -> MSE: 0.000249, MAE: 0.013131, R²: -0.0452
  Directional -> Accuracy: 0.4318, MCC: 0.0417, F1: 0.1379

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48409 | val 0.58589
  Epoch 020 - train 0.46481 | val 0.57881
  Regression -> MSE: 0.000311, MAE: 0.012940, R²: -0.8951
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.50516 | val 0.25270
  Epoch 011 - train 0.51864 | val 0.25507
  Regression -> MSE: 0.000236, MAE: 0.011977, R²: -0.0071
  Directional -> Accuracy: 0.5349, MCC: 0.0334, F1: 0.6552

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.53573 | val 0.84144
  Epoch 018 - train 0.56352 | val 0.85661
  Regression -> MSE: 0.000246, MAE: 0.010730, R²: 0.0185
  Directional -> Accuracy: 0.4667, MCC: -0.1493, F1: 0.6250

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47512 | val 0.76357
  Epoch 020 - train 0.50389 | val 0.76701
  Regression -> MSE: 0.000141, MAE: 0.008273, R²: -0.0626
  Directional -> Accuracy: 0.5778, MCC: 0.1494, F1: 0.6122

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46870 | val 0.73862
  Epoch 011 - train 0.46529 | val 0.73959
  Regression -> MSE: 0.000188, MAE: 0.010526, R²: 0.0036
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.43628 | val 0.72561
  Epoch 011 - train 0.47145 | val 0.72416
  Regression -> MSE: 0.000265, MAE: 0.010509, R²: -0.0265
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.49916 | val 0.36217
  Epoch 011 - train 0.48499 | val 0.36236
  Regression -> MSE: 0.000160, MAE: 0.010148, R²: 0.0145
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41014 | val 0.67207
  Epoch 011 - train 0.43102 | val 0.67880
  Regression -> MSE: 0.000186, MAE: 0.010583, R²: -0.0197
  Directional -> Accuracy: 0.4000, MCC: -0.1899, F1: 0.4490

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.49251 | val 0.42628
  Epoch 011 - train 0.48379 | val 0.42524
  Regression -> MSE: 0.000358, MAE: 0.011972, R²: -0.0263
  Directional -> Accuracy: 0.5735, MCC: 0.0000, F1: 0.7290

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.54140 | val 0.26924
  Epoch 011 - train 0.53003 | val 0.26870
  Regression -> MSE: 0.000116, MAE: 0.008144, R²: -0.1165
  Directional -> Accuracy: 0.5909, MCC: 0.2169, F1: 0.4375

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.49705 | val 0.81548
  Epoch 011 - train 0.52832 | val 0.81375
  Regression -> MSE: 0.000216, MAE: 0.011183, R²: -0.0039
  Directional -> Accuracy: 0.5690, MCC: 0.1680, F1: 0.6154

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.51388 | val 1.14821
  Epoch 017 - train 0.47617 | val 1.16331
  Regression -> MSE: 0.000084, MAE: 0.007200, R²: -0.0593
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49066 | val 0.31809
  Epoch 017 - train 0.49352 | val 0.32325
  Regression -> MSE: 0.000334, MAE: 0.014459, R²: -0.0168
  Directional -> Accuracy: 0.4250, MCC: -0.1732, F1: 0.3030

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.54462 | val 0.25167
  Epoch 011 - train 0.51882 | val 0.25514
  Regression -> MSE: 0.000241, MAE: 0.011250, R²: -0.0113
  Directional -> Accuracy: 0.5128, MCC: -0.0473, F1: 0.6545

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.48032 | val 0.59300
  Epoch 018 - train 0.45070 | val 0.59312
  Regression -> MSE: 0.000078, MAE: 0.006867, R²: 0.0278
  Directional -> Accuracy: 0.6184, MCC: 0.2369, F1: 0.6234

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.54164 | val 0.52243
  Epoch 020 - train 0.49087 | val 0.50952
  Regression -> MSE: 0.000408, MAE: 0.016106, R²: -0.1331
  Directional -> Accuracy: 0.4375, MCC: -0.1487, F1: 0.2286

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49040 | val 0.52233
  Epoch 020 - train 0.49253 | val 0.51102
  Regression -> MSE: 0.000102, MAE: 0.007436, R²: -0.0597
  Directional -> Accuracy: 0.4667, MCC: -0.0696, F1: 0.5000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.59247 | val 1.15341
  Epoch 011 - train 0.53658 | val 1.17730
  Regression -> MSE: 0.000189, MAE: 0.010731, R²: -0.0475
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.45213 | val 0.64610
  Epoch 011 - train 0.46343 | val 0.64863
  Regression -> MSE: 0.000219, MAE: 0.011579, R²: 0.0026
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.51824 | val 0.59984
  Epoch 011 - train 0.47048 | val 0.59907
  Regression -> MSE: 0.000093, MAE: 0.007655, R²: -0.0142
  Directional -> Accuracy: 0.4138, MCC: -0.1702, F1: 0.4848

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.50575 | val 1.01719
  Epoch 011 - train 0.50360 | val 1.01795
  Regression -> MSE: 0.000162, MAE: 0.010162, R²: -0.0073
  Directional -> Accuracy: 0.3636, MCC: -0.2742, F1: 0.3860

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.50568 | val 0.69914
  Epoch 013 - train 0.49544 | val 0.69819
  Regression -> MSE: 0.000141, MAE: 0.009334, R²: -0.2384
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 22:54:18,816] Trial 9 finished with value: -0.01166973461665524 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 32, 'learning_rate': 9.493829181832671e-06, 'weight_decay': 5.23926763980049e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.8758449043142293, 'early_stopping_min_delta': 0.0038519741464576674}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.57570 | val 1.00603
  Epoch 011 - train 0.56359 | val 1.01029
  Regression -> MSE: 0.000236, MAE: 0.012481, R²: -0.0114
  Directional -> Accuracy: 0.4839, MCC: 0.0000, F1: 0.6522

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.29485 | val 0.49832
  Epoch 016 - train 0.29001 | val 0.50466
  Regression -> MSE: 0.000248, MAE: 0.012531, R²: -0.0013
  Directional -> Accuracy: 0.5065, MCC: -0.0886, F1: 0.1364

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.29790 | val 0.33050
  Epoch 020 - train 0.27720 | val 0.35137
  Epoch 027 - train 0.26981 | val 0.37178
  Regression -> MSE: 0.000667, MAE: 0.018776, R²: 0.0251
  Directional -> Accuracy: 0.6304, MCC: 0.2573, F1: 0.7463

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.31606 | val 0.64652
  Epoch 016 - train 0.30499 | val 0.65813
  Regression -> MSE: 0.000314, MAE: 0.014458, R²: -0.0116
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.23760 | val 0.31073
  Epoch 016 - train 0.23884 | val 0.33204
  Regression -> MSE: 0.000376, MAE: 0.015033, R²: -0.0752
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.30285 | val 0.33520
  Epoch 020 - train 0.28194 | val 0.33840
  Epoch 022 - train 0.27479 | val 0.33933
  Regression -> MSE: 0.000201, MAE: 0.009925, R²: 0.0129
  Directional -> Accuracy: 0.6471, MCC: 0.2901, F1: 0.7000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.27712 | val 0.73954
  Epoch 020 - train 0.25521 | val 0.72885
  Epoch 030 - train 0.24466 | val 0.73410
  Regression -> MSE: 0.000600, MAE: 0.018913, R²: -0.0801
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.31195 | val 0.44367
  Epoch 020 - train 0.29264 | val 0.46128
  Epoch 022 - train 0.29127 | val 0.46197
  Regression -> MSE: 0.000245, MAE: 0.012019, R²: 0.0033
  Directional -> Accuracy: 0.4783, MCC: -0.0583, F1: 0.4000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.29524 | val 0.48438
  Epoch 016 - train 0.29309 | val 0.48114
  Regression -> MSE: 0.000617, MAE: 0.019655, R²: -0.0323
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.29113 | val 0.45147
  Epoch 016 - train 0.28259 | val 0.45954
  Regression -> MSE: 0.000389, MAE: 0.016087, R²: -0.0133
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.28807 | val 0.48724
  Epoch 016 - train 0.28545 | val 0.52062
  Regression -> MSE: 0.000240, MAE: 0.011755, R²: 0.0038
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.28384 | val 0.54961
  Epoch 016 - train 0.28184 | val 0.56050
  Regression -> MSE: 0.000313, MAE: 0.013641, R²: -0.0068
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.31736 | val 0.44142
  Epoch 016 - train 0.30926 | val 0.47456
  Regression -> MSE: 0.000677, MAE: 0.019525, R²: 0.0004
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.30850 | val 0.36137
  Epoch 016 - train 0.29501 | val 0.41379
  Regression -> MSE: 0.000147, MAE: 0.009636, R²: -0.0669
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.26544 | val 0.49506
  Epoch 020 - train 0.25583 | val 0.50251
  Epoch 022 - train 0.24577 | val 0.50263
  Regression -> MSE: 0.000223, MAE: 0.010804, R²: 0.0071
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.29773 | val 0.82659
  Epoch 016 - train 0.27612 | val 0.83021
  Regression -> MSE: 0.000362, MAE: 0.016153, R²: -0.0007
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.31253 | val 0.34944
  Epoch 020 - train 0.29388 | val 0.35686
  Epoch 023 - train 0.28698 | val 0.35836
  Regression -> MSE: 0.000108, MAE: 0.007907, R²: -0.0031
  Directional -> Accuracy: 0.5571, MCC: 0.0799, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.29163 | val 0.67512
  Epoch 016 - train 0.28665 | val 0.71797
  Regression -> MSE: 0.000156, MAE: 0.009669, R²: -0.0019
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.30773 | val 0.42011
  Epoch 016 - train 0.29769 | val 0.53763
  Regression -> MSE: 0.000277, MAE: 0.013260, R²: -0.0168
  Directional -> Accuracy: 0.5263, MCC: 0.0538, F1: 0.5714

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.25647 | val 0.47712
  Epoch 020 - train 0.23284 | val 0.47258
  Epoch 024 - train 0.22312 | val 0.47163
  Regression -> MSE: 0.000220, MAE: 0.010988, R²: -0.4734
  Directional -> Accuracy: 0.4000, MCC: -0.1483, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.29823 | val 0.53470
  Epoch 020 - train 0.27321 | val 0.56727
  Epoch 021 - train 0.27539 | val 0.56822
  Regression -> MSE: 0.000262, MAE: 0.011571, R²: -0.1562
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.30315 | val 0.46587
  Epoch 016 - train 0.28707 | val 0.50380
  Regression -> MSE: 0.000143, MAE: 0.008332, R²: 0.0051
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.28693 | val 0.42170
  Epoch 020 - train 0.26252 | val 0.41705
  Epoch 026 - train 0.25670 | val 0.41930
  Regression -> MSE: 0.000159, MAE: 0.010248, R²: 0.0365
  Directional -> Accuracy: 0.5455, MCC: 0.1476, F1: 0.6739

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.31413 | val 0.43123
  Epoch 016 - train 0.29375 | val 0.43169
  Regression -> MSE: 0.000088, MAE: 0.007188, R²: -0.0331
  Directional -> Accuracy: 0.4828, MCC: 0.0658, F1: 0.3182

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.31833 | val 0.47482
  Epoch 016 - train 0.30215 | val 0.47367
  Regression -> MSE: 0.000213, MAE: 0.011190, R²: -0.0070
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.26930 | val 0.29197
  Epoch 020 - train 0.24419 | val 0.27266
  Epoch 030 - train 0.22307 | val 0.27010
  Regression -> MSE: 0.000112, MAE: 0.008711, R²: -0.2185
  Directional -> Accuracy: 0.4643, MCC: 0.0136, F1: 0.2105

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.30750 | val 0.25831
  Epoch 016 - train 0.29304 | val 0.25506
  Regression -> MSE: 0.000107, MAE: 0.008899, R²: -0.0329
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.30168 | val 0.32654
  Epoch 020 - train 0.28244 | val 0.33471
  Epoch 026 - train 0.26731 | val 0.34875
  Regression -> MSE: 0.000234, MAE: 0.012531, R²: -0.0123
  Directional -> Accuracy: 0.6279, MCC: 0.2603, F1: 0.7576

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.30308 | val 0.42882
  Epoch 020 - train 0.27827 | val 0.43271
  Epoch 027 - train 0.28285 | val 0.43436
  Regression -> MSE: 0.000195, MAE: 0.008365, R²: -0.1731
  Directional -> Accuracy: 0.5614, MCC: 0.2858, F1: 0.3902

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.32733 | val 0.28656
  Epoch 020 - train 0.28882 | val 0.28204
  Epoch 030 - train 0.25868 | val 0.29594
  Regression -> MSE: 0.000242, MAE: 0.012070, R²: -0.0213
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.30969 | val 0.61800
  Epoch 016 - train 0.29151 | val 0.62802
  Regression -> MSE: 0.000231, MAE: 0.009891, R²: -0.0038
  Directional -> Accuracy: 0.5116, MCC: 0.0849, F1: 0.6557

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.30784 | val 0.45577
  Epoch 016 - train 0.29287 | val 0.46595
  Regression -> MSE: 0.000139, MAE: 0.008330, R²: -0.0261
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.31096 | val 0.45675
  Epoch 016 - train 0.30943 | val 0.47004
  Regression -> MSE: 0.000202, MAE: 0.010796, R²: -0.0743
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.25367 | val 0.40427
  Epoch 020 - train 0.23910 | val 0.39879
  Epoch 030 - train 0.22238 | val 0.39227
  Regression -> MSE: 0.000474, MAE: 0.015707, R²: -0.8116
  Directional -> Accuracy: 0.4658, MCC: 0.0633, F1: 0.1702

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.30710 | val 0.28890
  Epoch 016 - train 0.29315 | val 0.29338
  Regression -> MSE: 0.000171, MAE: 0.010375, R²: -0.0251
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.27917 | val 0.36258
  Epoch 016 - train 0.27274 | val 0.37481
  Regression -> MSE: 0.000183, MAE: 0.010340, R²: -0.0174
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.27909 | val 0.34118
  Epoch 016 - train 0.26994 | val 0.35708
  Regression -> MSE: 0.000351, MAE: 0.012423, R²: -0.0235
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.30773 | val 0.19631
  Epoch 016 - train 0.26737 | val 0.19945
  Regression -> MSE: 0.000113, MAE: 0.008407, R²: -0.0711
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.29709 | val 0.51735
  Epoch 016 - train 0.27663 | val 0.56073
  Regression -> MSE: 0.000220, MAE: 0.011335, R²: -0.0077
  Directional -> Accuracy: 0.4912, MCC: 0.1268, F1: 0.6506

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.29433 | val 0.69674
  Epoch 016 - train 0.29809 | val 0.71131
  Regression -> MSE: 0.000084, MAE: 0.007151, R²: -0.0860
  Directional -> Accuracy: 0.4894, MCC: 0.0465, F1: 0.4783

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.32178 | val 0.29968
  Epoch 016 - train 0.31826 | val 0.31330
  Regression -> MSE: 0.000334, MAE: 0.015190, R²: -0.0865
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.32720 | val 0.19209
  Epoch 020 - train 0.29237 | val 0.18932
  Epoch 027 - train 0.27079 | val 0.20074
  Regression -> MSE: 0.000260, MAE: 0.011399, R²: -0.0673
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.28280 | val 0.42505
  Epoch 016 - train 0.26224 | val 0.44498
  Regression -> MSE: 0.000081, MAE: 0.007037, R²: -0.0033
  Directional -> Accuracy: 0.5067, MCC: 0.0653, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.29455 | val 0.43294
  Epoch 020 - train 0.27716 | val 0.43331
  Epoch 025 - train 0.27922 | val 0.43608
  Regression -> MSE: 0.000314, MAE: 0.014582, R²: -0.0240
  Directional -> Accuracy: 0.4468, MCC: -0.1229, F1: 0.1875

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.31363 | val 0.39819
  Epoch 016 - train 0.29069 | val 0.39637
  Regression -> MSE: 0.000099, MAE: 0.007173, R²: -0.0041
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.34212 | val 0.46681
  Epoch 016 - train 0.33698 | val 0.47184
  Regression -> MSE: 0.000173, MAE: 0.009444, R²: -0.0076
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.27411 | val 0.41593
  Epoch 016 - train 0.26467 | val 0.46542
  Regression -> MSE: 0.000224, MAE: 0.011764, R²: -0.0063
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.28990 | val 0.40243
  Epoch 016 - train 0.28224 | val 0.45512
  Regression -> MSE: 0.000092, MAE: 0.007635, R²: 0.0017
  Directional -> Accuracy: 0.5439, MCC: 0.0888, F1: 0.5357

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.32775 | val 0.61926
  Epoch 016 - train 0.31271 | val 0.70116
  Regression -> MSE: 0.000163, MAE: 0.010245, R²: 0.0031
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.27924 | val 0.47020
  Epoch 016 - train 0.27813 | val 0.50252
  Regression -> MSE: 0.000124, MAE: 0.009013, R²: -0.0658
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.32459 | val 0.55566

[I 2026-02-23 22:55:32,783] Trial 10 finished with value: -0.011611270961993643 and parameters: {'feature_set': 'emotion', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 0.00012222651984821452, 'weight_decay': 0.0009593907676693504, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.7437895939219032, 'early_stopping_min_delta': 0.009845193389136092}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 016 - train 0.31492 | val 0.56964
  Regression -> MSE: 0.000249, MAE: 0.012484, R²: -0.0516
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.46455 | val 0.74777
  Epoch 011 - train 0.46896 | val 0.75099
  Regression -> MSE: 0.000250, MAE: 0.012649, R²: -0.0112
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53050 | val 0.42891
  Epoch 011 - train 0.51911 | val 0.43102
  Regression -> MSE: 0.000726, MAE: 0.020071, R²: -0.0603
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.50825 | val 0.93558
  Epoch 011 - train 0.49088 | val 0.93670
  Regression -> MSE: 0.000309, MAE: 0.014422, R²: 0.0046
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.38681 | val 0.66641
  Epoch 011 - train 0.38918 | val 0.74125
  Regression -> MSE: 0.000357, MAE: 0.014704, R²: -0.0231
  Directional -> Accuracy: 0.5467, MCC: 0.0683, F1: 0.6222

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.48980 | val 0.43650
  Epoch 020 - train 0.46604 | val 0.44595
  Regression -> MSE: 0.000220, MAE: 0.010614, R²: -0.0805
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41632 | val 1.11202
  Epoch 011 - train 0.45170 | val 1.11549
  Regression -> MSE: 0.000560, MAE: 0.018171, R²: -0.0084
  Directional -> Accuracy: 0.4894, MCC: -0.0311, F1: 0.3684

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.49131 | val 0.63508
  Epoch 011 - train 0.48040 | val 0.63911
  Regression -> MSE: 0.000250, MAE: 0.012443, R²: -0.0191
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43271 | val 0.66579
  Epoch 020 - train 0.45232 | val 0.64725
  Regression -> MSE: 0.000611, MAE: 0.019695, R²: -0.0222
  Directional -> Accuracy: 0.5455, MCC: 0.0094, F1: 0.3333

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44061 | val 0.58645
  Epoch 011 - train 0.45961 | val 0.58857
  Regression -> MSE: 0.000390, MAE: 0.015893, R²: -0.0157
  Directional -> Accuracy: 0.5102, MCC: 0.0355, F1: 0.5200

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46881 | val 0.66526
  Epoch 011 - train 0.45508 | val 0.66820
  Regression -> MSE: 0.000243, MAE: 0.011711, R²: -0.0080
  Directional -> Accuracy: 0.5714, MCC: 0.1043, F1: 0.4444

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.48528 | val 0.70853
  Epoch 011 - train 0.45550 | val 0.70801
  Regression -> MSE: 0.000324, MAE: 0.013608, R²: -0.0419
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50127 | val 0.57948
  Epoch 011 - train 0.48826 | val 0.58104
  Regression -> MSE: 0.000682, MAE: 0.019641, R²: -0.0069
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48789 | val 0.48525
  Epoch 011 - train 0.48742 | val 0.49162
  Regression -> MSE: 0.000146, MAE: 0.009579, R²: -0.0553
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44098 | val 0.66016
  Epoch 011 - train 0.44882 | val 0.66042
  Regression -> MSE: 0.000231, MAE: 0.010936, R²: -0.0264
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.49926 | val 1.26805
  Epoch 011 - train 0.50546 | val 1.27027
  Regression -> MSE: 0.000364, MAE: 0.015959, R²: -0.0038
  Directional -> Accuracy: 0.4808, MCC: -0.1391, F1: 0.1290

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48848 | val 0.47997
  Epoch 011 - train 0.49016 | val 0.48143
  Regression -> MSE: 0.000108, MAE: 0.008035, R²: -0.0000
  Directional -> Accuracy: 0.4143, MCC: -0.1773, F1: 0.4533

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43343 | val 0.97169
  Epoch 011 - train 0.46843 | val 0.97652
  Regression -> MSE: 0.000158, MAE: 0.009943, R²: -0.0159
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47235 | val 0.47323
  Epoch 020 - train 0.48927 | val 0.47043
  Regression -> MSE: 0.000286, MAE: 0.013665, R²: -0.0504
  Directional -> Accuracy: 0.4605, MCC: 0.1641, F1: 0.2264

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.46149 | val 0.89079
  Epoch 011 - train 0.46403 | val 0.91664
  Regression -> MSE: 0.000150, MAE: 0.008724, R²: -0.0043
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.49387 | val 0.92883
  Epoch 011 - train 0.49853 | val 0.93324
  Regression -> MSE: 0.000226, MAE: 0.010888, R²: 0.0014
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51441 | val 0.71071
  Epoch 011 - train 0.49615 | val 0.71595
  Regression -> MSE: 0.000145, MAE: 0.008348, R²: -0.0092
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.44288 | val 0.53663
  Epoch 011 - train 0.44870 | val 0.53948
  Regression -> MSE: 0.000171, MAE: 0.010297, R²: -0.0343
  Directional -> Accuracy: 0.4848, MCC: -0.0362, F1: 0.5952

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51070 | val 0.63363
  Epoch 011 - train 0.51324 | val 0.63568
  Regression -> MSE: 0.000085, MAE: 0.006992, R²: 0.0035
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.48321 | val 0.71604
  Epoch 011 - train 0.48572 | val 0.73270
  Regression -> MSE: 0.000216, MAE: 0.011144, R²: -0.0184
  Directional -> Accuracy: 0.4697, MCC: -0.1920, F1: 0.0541

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.42427 | val 0.35957
  Epoch 011 - train 0.42162 | val 0.35933
  Regression -> MSE: 0.000092, MAE: 0.008110, R²: -0.0027
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44264 | val 0.33207
  Epoch 020 - train 0.44337 | val 0.29928
  Regression -> MSE: 0.000101, MAE: 0.008547, R²: 0.0229
  Directional -> Accuracy: 0.6087, MCC: 0.2252, F1: 0.5909

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.48094 | val 0.43574
  Epoch 011 - train 0.46588 | val 0.43632
  Regression -> MSE: 0.000231, MAE: 0.012535, R²: 0.0003
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48006 | val 0.53662
  Epoch 020 - train 0.50281 | val 0.52898
  Regression -> MSE: 0.000314, MAE: 0.012988, R²: -0.8859
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46217 | val 0.28992
  Epoch 020 - train 0.44867 | val 0.26752
  Regression -> MSE: 0.000234, MAE: 0.011913, R²: 0.0101
  Directional -> Accuracy: 0.5854, MCC: 0.2437, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.46384 | val 0.98873
  Epoch 011 - train 0.48779 | val 0.99615
  Regression -> MSE: 0.000233, MAE: 0.010091, R²: -0.0129
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47391 | val 0.64982
  Epoch 020 - train 0.46636 | val 0.66580
  Regression -> MSE: 0.000144, MAE: 0.008506, R²: -0.0638
  Directional -> Accuracy: 0.4419, MCC: -0.2062, F1: 0.5862

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.46739 | val 0.64468
  Epoch 011 - train 0.48076 | val 0.64771
  Regression -> MSE: 0.000199, MAE: 0.010759, R²: -0.0561
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.40765 | val 0.57612
  Epoch 020 - train 0.42074 | val 0.56935
  Regression -> MSE: 0.000280, MAE: 0.010906, R²: -0.0702
  Directional -> Accuracy: 0.4658, MCC: -0.0144, F1: 0.3607

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.45416 | val 0.37778
  Epoch 011 - train 0.47596 | val 0.37777
  Regression -> MSE: 0.000169, MAE: 0.010401, R²: -0.0124
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.45258 | val 0.57945
  Epoch 011 - train 0.43030 | val 0.58632
  Regression -> MSE: 0.000189, MAE: 0.010689, R²: -0.0524
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46824 | val 0.44628
  Epoch 011 - train 0.46872 | val 0.44842
  Regression -> MSE: 0.000344, MAE: 0.011703, R²: -0.0038
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50034 | val 0.23909
  Epoch 011 - train 0.52386 | val 0.23922
  Regression -> MSE: 0.000120, MAE: 0.008368, R²: -0.1371
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.55393 | val 0.76959
  Epoch 011 - train 0.53715 | val 0.77401
  Regression -> MSE: 0.000219, MAE: 0.011256, R²: -0.0013
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44542 | val 1.04462
  Epoch 011 - train 0.48187 | val 1.04520
  Regression -> MSE: 0.000089, MAE: 0.007355, R²: -0.1434
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.48019 | val 0.40669
  Epoch 011 - train 0.48072 | val 0.41238
  Regression -> MSE: 0.000347, MAE: 0.015541, R²: -0.1271
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51671 | val 0.19205
  Epoch 020 - train 0.49599 | val 0.17409
  Regression -> MSE: 0.000254, MAE: 0.011685, R²: -0.0425
  Directional -> Accuracy: 0.4211, MCC: -0.2079, F1: 0.5417

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43311 | val 0.60538
  Epoch 011 - train 0.45888 | val 0.60921
  Regression -> MSE: 0.000083, MAE: 0.007061, R²: -0.0314
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47985 | val 0.58315
  Epoch 020 - train 0.51075 | val 0.55702
  Regression -> MSE: 0.000316, MAE: 0.014710, R²: -0.0301
  Directional -> Accuracy: 0.5745, MCC: 0.1506, F1: 0.5652

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44114 | val 0.52298
  Epoch 011 - train 0.44704 | val 0.52405
  Regression -> MSE: 0.000098, MAE: 0.007269, R²: -0.0018
  Directional -> Accuracy: 0.5227, MCC: -0.1161, F1: 0.6769

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.53270 | val 0.68691
  Epoch 011 - train 0.47924 | val 0.68690
  Regression -> MSE: 0.000173, MAE: 0.009878, R²: -0.0042
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.44495 | val 0.58309
  Epoch 011 - train 0.45350 | val 0.58578
  Regression -> MSE: 0.000223, MAE: 0.011697, R²: 0.0014
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45182 | val 0.58943
  Epoch 011 - train 0.44111 | val 0.59409
  Regression -> MSE: 0.000096, MAE: 0.007895, R²: -0.0406
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.49472 | val 0.90964
  Epoch 011 - train 0.48923 | val 0.91205
  Regression -> MSE: 0.000166, MAE: 0.010303, R²: -0.0141
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.45640 | val 0.64627
  Epoch 011 - train 0.46985 | val 0.64606
  Regression -> MSE: 0.000120, MAE: 0.008981, R²: -0.0347
  Directional -> Accuracy: 0.5536, MCC: 0.1032, F1: 0.6479

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 22:56:25,809] Trial 11 finished with value: -0.01159223511434014 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 1.4638043522248675e-06, 'weight_decay': 1.4615723986910507e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.4188466498547547, 'early_stopping_min_delta': 0.006705100856017483}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.47353 | val 0.86329
  Epoch 011 - train 0.47163 | val 0.87396
  Regression -> MSE: 0.000238, MAE: 0.012332, R²: -0.0046
  Directional -> Accuracy: 0.5738, MCC: 0.1425, F1: 0.4091

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.39203 | val 0.73939
  Epoch 020 - train 0.37786 | val 0.77358
  Regression -> MSE: 0.000256, MAE: 0.012815, R²: -0.0433
  Directional -> Accuracy: 0.4487, MCC: -0.0298, F1: 0.5981

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43004 | val 0.44962
  Epoch 020 - train 0.40241 | val 0.42247
  Regression -> MSE: 0.000650, MAE: 0.018926, R²: 0.0600
  Directional -> Accuracy: 0.5745, MCC: 0.1641, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45767 | val 0.96499
  Epoch 020 - train 0.43387 | val 0.96952
  Regression -> MSE: 0.000353, MAE: 0.014954, R²: -0.0210
  Directional -> Accuracy: 0.5833, MCC: 0.1943, F1: 0.5455

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.37294 | val 0.43606
  Epoch 011 - train 0.37123 | val 0.45294
  Regression -> MSE: 0.000347, MAE: 0.014418, R²: -0.0049
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.41219 | val 0.42008
  Epoch 020 - train 0.38951 | val 0.44959
  Regression -> MSE: 0.000215, MAE: 0.010137, R²: -0.0693
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.40460 | val 1.14188
  Epoch 011 - train 0.41796 | val 1.14423
  Regression -> MSE: 0.000582, MAE: 0.018459, R²: -0.0165
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45245 | val 0.68168
  Epoch 016 - train 0.42613 | val 0.74392
  Regression -> MSE: 0.000245, MAE: 0.011877, R²: 0.0051
  Directional -> Accuracy: 0.5571, MCC: 0.0262, F1: 0.3404

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39430 | val 0.79191
  Epoch 011 - train 0.40551 | val 0.79879
  Regression -> MSE: 0.000625, MAE: 0.019638, R²: -0.0685
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42247 | val 0.81692
  Epoch 020 - train 0.40508 | val 0.81192
  Regression -> MSE: 0.000343, MAE: 0.015477, R²: -0.0132
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43347 | val 0.80582
  Epoch 011 - train 0.43571 | val 0.82574
  Regression -> MSE: 0.000247, MAE: 0.011533, R²: -0.0364
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42091 | val 0.85827
  Epoch 011 - train 0.40008 | val 0.87896
  Regression -> MSE: 0.000313, MAE: 0.013537, R²: -0.0228
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44066 | val 0.61830
  Epoch 016 - train 0.43628 | val 0.81627
  Regression -> MSE: 0.000653, MAE: 0.019168, R²: 0.0252
  Directional -> Accuracy: 0.5424, MCC: 0.1394, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41689 | val 0.49065
  Epoch 011 - train 0.42507 | val 0.49785
  Regression -> MSE: 0.000150, MAE: 0.009512, R²: 0.0010
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37993 | val 0.73004
  Epoch 020 - train 0.37436 | val 0.72326
  Regression -> MSE: 0.000219, MAE: 0.010489, R²: 0.0239
  Directional -> Accuracy: 0.5806, MCC: 0.1627, F1: 0.6061

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41413 | val 1.43661
  Epoch 011 - train 0.42263 | val 1.44081
  Regression -> MSE: 0.000381, MAE: 0.016338, R²: -0.0138
  Directional -> Accuracy: 0.5660, MCC: 0.2096, F1: 0.1481

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43098 | val 0.51893
  Epoch 020 - train 0.41572 | val 0.53804
  Regression -> MSE: 0.000105, MAE: 0.007852, R²: 0.0160
  Directional -> Accuracy: 0.5070, MCC: -0.0360, F1: 0.6316

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.40986 | val 1.10421
  Epoch 020 - train 0.40725 | val 1.13089
  Regression -> MSE: 0.000168, MAE: 0.010478, R²: -0.0521
  Directional -> Accuracy: 0.4333, MCC: 0.1137, F1: 0.1905

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.42286 | val 0.61957
  Epoch 011 - train 0.42992 | val 0.71774
  Regression -> MSE: 0.000277, MAE: 0.013305, R²: -0.0327
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36353 | val 0.74387
  Epoch 020 - train 0.35118 | val 0.72546
  Regression -> MSE: 0.000226, MAE: 0.011289, R²: -0.5354
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42936 | val 0.97064
  Epoch 019 - train 0.40299 | val 1.03413
  Regression -> MSE: 0.000258, MAE: 0.011739, R²: -0.1370
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42322 | val 0.67041
  Epoch 019 - train 0.40941 | val 0.72335
  Regression -> MSE: 0.000150, MAE: 0.008725, R²: -0.0090
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.41833 | val 0.58322
  Epoch 020 - train 0.40508 | val 0.58577
  Regression -> MSE: 0.000176, MAE: 0.010490, R²: 0.0068
  Directional -> Accuracy: 0.5970, MCC: 0.2055, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43979 | val 0.70722
  Epoch 011 - train 0.45235 | val 0.71184
  Regression -> MSE: 0.000084, MAE: 0.006925, R²: -0.0080
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.43822 | val 0.70543
  Epoch 017 - train 0.42885 | val 1.02544
  Regression -> MSE: 0.000216, MAE: 0.011419, R²: 0.0098
  Directional -> Accuracy: 0.5224, MCC: 0.1011, F1: 0.6364

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37283 | val 0.31610
  Epoch 020 - train 0.35481 | val 0.29231
  Regression -> MSE: 0.000103, MAE: 0.008207, R²: -0.1248
  Directional -> Accuracy: 0.4561, MCC: 0.0076, F1: 0.2051

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44576 | val 0.20202
  Epoch 011 - train 0.45946 | val 0.20201
  Regression -> MSE: 0.000129, MAE: 0.009386, R²: -0.0297
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43955 | val 0.40816
  Epoch 011 - train 0.44513 | val 0.40927
  Regression -> MSE: 0.000242, MAE: 0.012897, R²: -0.0191
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41828 | val 0.62332
  Epoch 014 - train 0.42601 | val 0.63651
  Regression -> MSE: 0.000177, MAE: 0.007825, R²: -0.0827
  Directional -> Accuracy: 0.4828, MCC: -0.0099, F1: 0.4444

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.46118 | val 0.25807
  Epoch 011 - train 0.44012 | val 0.25932
  Regression -> MSE: 0.000234, MAE: 0.011922, R²: -0.0004
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45607 | val 0.85489
  Epoch 011 - train 0.45370 | val 0.85735
  Regression -> MSE: 0.000251, MAE: 0.010438, R²: -0.0050
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.42878 | val 0.78779
  Epoch 011 - train 0.41985 | val 0.79110
  Regression -> MSE: 0.000134, MAE: 0.008251, R²: -0.0107
  Directional -> Accuracy: 0.5556, MCC: 0.1612, F1: 0.7059

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44108 | val 0.69625
  Epoch 017 - train 0.40568 | val 0.71862
  Regression -> MSE: 0.000189, MAE: 0.010339, R²: -0.0045
  Directional -> Accuracy: 0.6275, MCC: 0.3089, F1: 0.7324

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38929 | val 0.64663
  Epoch 020 - train 0.36198 | val 0.64943
  Regression -> MSE: 0.000317, MAE: 0.012095, R²: -0.2278
  Directional -> Accuracy: 0.5405, MCC: 0.1627, F1: 0.4516

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.42949 | val 0.39596
  Epoch 020 - train 0.42265 | val 0.38498
  Regression -> MSE: 0.000166, MAE: 0.010329, R²: -0.0230
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37385 | val 0.62178
  Epoch 011 - train 0.37457 | val 0.62838
  Regression -> MSE: 0.000194, MAE: 0.010930, R²: -0.0609
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41480 | val 0.41151
  Epoch 017 - train 0.40206 | val 0.45498
  Regression -> MSE: 0.000381, MAE: 0.013915, R²: -0.0907
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42937 | val 0.29039
  Epoch 020 - train 0.38275 | val 0.27775
  Regression -> MSE: 0.000126, MAE: 0.008057, R²: -0.2144
  Directional -> Accuracy: 0.6364, MCC: 0.2928, F1: 0.5556

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.43093 | val 0.80905
  Epoch 016 - train 0.41185 | val 0.86551
  Regression -> MSE: 0.000218, MAE: 0.011361, R²: -0.0131
  Directional -> Accuracy: 0.5000, MCC: 0.0500, F1: 0.6027

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44249 | val 1.16948
  Epoch 020 - train 0.40690 | val 1.16186
  Regression -> MSE: 0.000093, MAE: 0.007575, R²: -0.1697
  Directional -> Accuracy: 0.3750, MCC: -0.0538, F1: 0.0625

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42852 | val 0.33364
  Epoch 020 - train 0.40314 | val 0.34595
  Regression -> MSE: 0.000392, MAE: 0.017189, R²: -0.1936
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.44251 | val 0.21411
  Epoch 011 - train 0.43020 | val 0.21485
  Regression -> MSE: 0.000240, MAE: 0.011305, R²: -0.0094
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.39211 | val 0.63030
  Epoch 017 - train 0.39440 | val 0.84751
  Regression -> MSE: 0.000081, MAE: 0.007101, R²: -0.0087
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43610 | val 0.52296
  Epoch 020 - train 0.41793 | val 0.51489
  Regression -> MSE: 0.000373, MAE: 0.015409, R²: -0.0373
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6571

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.43362 | val 0.63858
  Epoch 011 - train 0.42074 | val 0.63822
  Regression -> MSE: 0.000097, MAE: 0.007137, R²: -0.0087
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42127 | val 0.91426
  Epoch 012 - train 0.44857 | val 0.93951
  Regression -> MSE: 0.000186, MAE: 0.010597, R²: -0.0267
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.40048 | val 0.65573
  Epoch 011 - train 0.40105 | val 0.66394
  Regression -> MSE: 0.000227, MAE: 0.011853, R²: -0.0360
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.43707 | val 0.59731
  Epoch 016 - train 0.41976 | val 0.68466
  Regression -> MSE: 0.000091, MAE: 0.007610, R²: 0.0067
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.45660 | val 1.01491
  Epoch 012 - train 0.44360 | val 1.04300
  Regression -> MSE: 0.000161, MAE: 0.010094, R²: -0.0019
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.43201 | val 0.69429
  Epoch 012 - train 0.44091 | val 0.72291
  Regression -> MSE: 0.000127, MAE: 0.008932, R²: -0.1103
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 22:57:12,418] Trial 12 finished with value: -0.011650248888944668 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 6.984695170568027e-05, 'weight_decay': 1.2121638120949539e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.9653599848307253, 'early_stopping_min_delta': 3.876452795993808e-05}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.43943 | val 0.97231
  Epoch 011 - train 0.44370 | val 0.99169
  Regression -> MSE: 0.000239, MAE: 0.012262, R²: -0.0246
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.38620 | val 0.65701
  Epoch 018 - train 0.37095 | val 0.75861
  Regression -> MSE: 0.000251, MAE: 0.012640, R²: -0.0181
  Directional -> Accuracy: 0.4937, MCC: 0.0281, F1: 0.5455

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41959 | val 0.40819
  Epoch 011 - train 0.40678 | val 0.41107
  Regression -> MSE: 0.000682, MAE: 0.019402, R²: -0.0073
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45733 | val 0.94374
  Epoch 011 - train 0.43902 | val 0.94822
  Regression -> MSE: 0.000355, MAE: 0.015236, R²: -0.0221
  Directional -> Accuracy: 0.5102, MCC: -0.0696, F1: 0.6667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.37402 | val 0.35044
  Epoch 011 - train 0.36412 | val 0.35232
  Regression -> MSE: 0.000356, MAE: 0.014641, R²: -0.0033
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.43425 | val 0.39299
  Epoch 020 - train 0.41184 | val 0.36651
  Regression -> MSE: 0.000182, MAE: 0.009759, R²: 0.0806
  Directional -> Accuracy: 0.5660, MCC: 0.1473, F1: 0.5306

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41345 | val 1.07050
  Epoch 011 - train 0.39555 | val 1.06937
  Regression -> MSE: 0.000506, MAE: 0.017419, R²: -0.0198
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.42942 | val 0.57456
  Epoch 018 - train 0.42545 | val 0.57342
  Regression -> MSE: 0.000265, MAE: 0.012380, R²: -0.0344
  Directional -> Accuracy: 0.5915, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41504 | val 0.65749
  Epoch 011 - train 0.40108 | val 0.66406
  Regression -> MSE: 0.000617, MAE: 0.019636, R²: -0.0888
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.37941 | val 0.62711
  Epoch 020 - train 0.36941 | val 0.61332
  Regression -> MSE: 0.000368, MAE: 0.015636, R²: 0.0431
  Directional -> Accuracy: 0.5814, MCC: 0.3325, F1: 0.6400

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42369 | val 0.67645
  Epoch 011 - train 0.44413 | val 0.68657
  Regression -> MSE: 0.000245, MAE: 0.011594, R²: -0.0297
  Directional -> Accuracy: 0.5694, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.39795 | val 0.75865
  Epoch 011 - train 0.43348 | val 0.78222
  Regression -> MSE: 0.000317, MAE: 0.013574, R²: -0.0311
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.45346 | val 0.56733
  Epoch 011 - train 0.45698 | val 0.57816
  Regression -> MSE: 0.000660, MAE: 0.019198, R²: -0.0019
  Directional -> Accuracy: 0.5167, MCC: 0.1302, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42279 | val 0.44301
  Epoch 011 - train 0.42298 | val 0.44492
  Regression -> MSE: 0.000149, MAE: 0.009564, R²: -0.0145
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38740 | val 0.64014
  Epoch 020 - train 0.34211 | val 0.62256
  Regression -> MSE: 0.000224, MAE: 0.010980, R²: 0.0020
  Directional -> Accuracy: 0.4603, MCC: -0.0790, F1: 0.5405

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42239 | val 1.15529
  Epoch 011 - train 0.43291 | val 1.17530
  Regression -> MSE: 0.000403, MAE: 0.016581, R²: -0.0523
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43859 | val 0.53226
  Epoch 011 - train 0.43114 | val 0.54042
  Regression -> MSE: 0.000106, MAE: 0.007824, R²: -0.0117
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39041 | val 0.88252
  Epoch 011 - train 0.38445 | val 0.88623
  Regression -> MSE: 0.000159, MAE: 0.010014, R²: -0.0097
  Directional -> Accuracy: 0.5902, MCC: -0.1040, F1: 0.7423

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.40808 | val 0.41392
  Epoch 011 - train 0.39828 | val 0.42820
  Regression -> MSE: 0.000274, MAE: 0.013247, R²: -0.0122
  Directional -> Accuracy: 0.5128, MCC: 0.0370, F1: 0.5476

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.35112 | val 0.64132
  Epoch 011 - train 0.34420 | val 0.64194
  Regression -> MSE: 0.000174, MAE: 0.009358, R²: -0.1221
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.41693 | val 0.80137
  Epoch 020 - train 0.39215 | val 0.79060
  Regression -> MSE: 0.000307, MAE: 0.012958, R²: -0.3275
  Directional -> Accuracy: 0.4416, MCC: -0.1257, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.40814 | val 0.59140
  Epoch 011 - train 0.40786 | val 0.59515
  Regression -> MSE: 0.000157, MAE: 0.009022, R²: -0.0547
  Directional -> Accuracy: 0.5200, MCC: -0.0883, F1: 0.6471

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.39188 | val 0.49772
  Epoch 011 - train 0.39705 | val 0.50174
  Regression -> MSE: 0.000195, MAE: 0.010768, R²: -0.0734
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43449 | val 0.60050
  Epoch 011 - train 0.42706 | val 0.60090
  Regression -> MSE: 0.000083, MAE: 0.006936, R²: -0.0132
  Directional -> Accuracy: 0.5500, MCC: -0.0563, F1: 0.6966

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42744 | val 0.60217
  Epoch 011 - train 0.39638 | val 0.60635
  Regression -> MSE: 0.000215, MAE: 0.011188, R²: 0.0005
  Directional -> Accuracy: 0.4853, MCC: 0.0000, F1: 0.6535

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39456 | val 0.31296
  Epoch 020 - train 0.36576 | val 0.29655
  Regression -> MSE: 0.000114, MAE: 0.008643, R²: -0.2640
  Directional -> Accuracy: 0.5000, MCC: 0.0688, F1: 0.3556

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44009 | val 0.17303
  Epoch 011 - train 0.41842 | val 0.17239
  Regression -> MSE: 0.000127, MAE: 0.009272, R²: -0.0173
  Directional -> Accuracy: 0.5714, MCC: 0.3043, F1: 0.6557

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45232 | val 0.23819
  Epoch 011 - train 0.42669 | val 0.24518
  Regression -> MSE: 0.000333, MAE: 0.014554, R²: -0.1441
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41883 | val 0.57269
  Epoch 011 - train 0.41904 | val 0.57449
  Regression -> MSE: 0.000170, MAE: 0.007598, R²: -0.0556
  Directional -> Accuracy: 0.6102, MCC: 0.2609, F1: 0.5818

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.44398 | val 0.39561
  Epoch 011 - train 0.42202 | val 0.39585
  Regression -> MSE: 0.000231, MAE: 0.011860, R²: -0.0016
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45142 | val 0.67896
  Epoch 011 - train 0.44469 | val 0.68265
  Regression -> MSE: 0.000258, MAE: 0.010748, R²: 0.0036
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45532 | val 0.63754
  Epoch 011 - train 0.44830 | val 0.64009
  Regression -> MSE: 0.000141, MAE: 0.008508, R²: -0.0058
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.44295 | val 0.63547
  Epoch 020 - train 0.39521 | val 0.61833
  Regression -> MSE: 0.000197, MAE: 0.010779, R²: -0.0580
  Directional -> Accuracy: 0.4231, MCC: -0.2157, F1: 0.5588

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.36519 | val 0.56669
  Epoch 011 - train 0.36550 | val 0.56681
  Regression -> MSE: 0.000273, MAE: 0.010833, R²: -0.0452
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.47204 | val 0.47548
  Epoch 011 - train 0.43368 | val 0.47506
  Regression -> MSE: 0.000168, MAE: 0.010245, R²: -0.0353
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37552 | val 0.43343
  Epoch 011 - train 0.37670 | val 0.43676
  Regression -> MSE: 0.000220, MAE: 0.011288, R²: -0.0298
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41833 | val 0.43619
  Epoch 011 - train 0.42129 | val 0.43849
  Regression -> MSE: 0.000351, MAE: 0.012450, R²: -0.0194
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44571 | val 0.27150
  Epoch 011 - train 0.41369 | val 0.27170
  Regression -> MSE: 0.000109, MAE: 0.008094, R²: -0.0703
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47023 | val 0.67445
  Epoch 020 - train 0.40800 | val 0.68312
  Regression -> MSE: 0.000219, MAE: 0.011197, R²: -0.0343
  Directional -> Accuracy: 0.4407, MCC: -0.1294, F1: 0.5926

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43350 | val 0.99261
  Epoch 019 - train 0.39924 | val 0.99193
  Regression -> MSE: 0.000088, MAE: 0.007417, R²: -0.1043
  Directional -> Accuracy: 0.4286, MCC: -0.1419, F1: 0.4815

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39467 | val 0.35025
  Epoch 020 - train 0.36785 | val 0.31981
  Regression -> MSE: 0.000360, MAE: 0.016128, R²: -0.1474
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.44955 | val 0.20262
  Epoch 011 - train 0.45421 | val 0.20220
  Regression -> MSE: 0.000238, MAE: 0.011072, R²: -0.0426
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.39434 | val 0.55979
  Epoch 011 - train 0.40261 | val 0.55925
  Regression -> MSE: 0.000083, MAE: 0.007155, R²: -0.0105
  Directional -> Accuracy: 0.4935, MCC: -0.1132, F1: 0.6609

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43188 | val 0.42581
  Epoch 011 - train 0.44398 | val 0.42613
  Regression -> MSE: 0.000371, MAE: 0.015591, R²: -0.0025
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42281 | val 0.64205
  Epoch 011 - train 0.40822 | val 0.64253
  Regression -> MSE: 0.000099, MAE: 0.007045, R²: -0.0428
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.7297

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42568 | val 0.70937
  Epoch 011 - train 0.39534 | val 0.71263
  Regression -> MSE: 0.000194, MAE: 0.010670, R²: -0.0139
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.37636 | val 0.58642
  Epoch 011 - train 0.39659 | val 0.60048
  Regression -> MSE: 0.000223, MAE: 0.011648, R²: -0.0324
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40927 | val 0.54058
  Epoch 011 - train 0.39634 | val 0.54798
  Regression -> MSE: 0.000089, MAE: 0.007454, R²: 0.0112
  Directional -> Accuracy: 0.5763, MCC: 0.2559, F1: 0.6914

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.46386 | val 0.92173
  Epoch 011 - train 0.45818 | val 0.92534
  Regression -> MSE: 0.000165, MAE: 0.010156, R²: -0.0392
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41217 | val 0.64915
  Epoch 011 - train 0.42508 | val 0.65303
  Regression -> MSE: 0.000113, MAE: 0.008692, R²: -0.0045
  Directional -> Accuracy: 0.5000, MCC: -0.1280, F1: 0.6667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 22:57:36,014] Trial 13 finished with value: -0.011614553959620189 and parameters: {'feature_set': 'emotion', 'model_type': 'BiLSTM', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 9.318987354049691e-05, 'weight_decay': 2.088906984079272e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.43440096111045, 'early_stopping_min_delta': 0.007968356972928433}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.43779 | val 0.81399
  Epoch 011 - train 0.44006 | val 0.83479
  Regression -> MSE: 0.000237, MAE: 0.012074, R²: -0.0317
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.23218 | val 0.48173
  Epoch 012 - train 0.22578 | val 0.50962
  Regression -> MSE: 0.000244, MAE: 0.012432, R²: -0.0143
  Directional -> Accuracy: 0.5526, MCC: 0.0719, F1: 0.4138

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.23394 | val 0.28647
  Epoch 011 - train 0.22760 | val 0.28883
  Regression -> MSE: 0.000688, MAE: 0.019252, R²: 0.0140
  Directional -> Accuracy: 0.6000, MCC: 0.1273, F1: 0.7273

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.23401 | val 0.56360
  Epoch 012 - train 0.22902 | val 0.55419
  Regression -> MSE: 0.000334, MAE: 0.014607, R²: -0.0620
  Directional -> Accuracy: 0.4348, MCC: -0.2227, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.21345 | val 0.39051
  Epoch 011 - train 0.21356 | val 0.34786
  Regression -> MSE: 0.000354, MAE: 0.014625, R²: -0.0021
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.24633 | val 0.27530
  Epoch 017 - train 0.20737 | val 0.33639
  Regression -> MSE: 0.000222, MAE: 0.010866, R²: -0.0752
  Directional -> Accuracy: 0.4800, MCC: -0.1961, F1: 0.6486

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.23963 | val 0.58022
  Epoch 011 - train 0.20939 | val 0.59882
  Regression -> MSE: 0.000566, MAE: 0.018411, R²: -0.0005
  Directional -> Accuracy: 0.5000, MCC: -0.0210, F1: 0.3429

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.22123 | val 0.54441
  Epoch 011 - train 0.21342 | val 0.57706
  Regression -> MSE: 0.000249, MAE: 0.012378, R²: -0.0044
  Directional -> Accuracy: 0.5294, MCC: 0.0663, F1: 0.4839

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.16887 | val 0.26008
  Epoch 012 - train 0.16363 | val 0.28858
  Regression -> MSE: 0.000621, MAE: 0.019513, R²: -0.0158
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.20448 | val 0.52998
  Epoch 012 - train 0.19896 | val 0.41484
  Regression -> MSE: 0.000371, MAE: 0.015502, R²: 0.0046
  Directional -> Accuracy: 0.5833, MCC: 0.1372, F1: 0.4737

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.23127 | val 0.39757
  Epoch 020 - train 0.15334 | val 0.44568
  Regression -> MSE: 0.000322, MAE: 0.013776, R²: -0.3144
  Directional -> Accuracy: 0.4638, MCC: -0.0758, F1: 0.4127

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.21668 | val 0.52136
  Epoch 012 - train 0.20699 | val 0.53012
  Regression -> MSE: 0.000312, MAE: 0.013421, R²: 0.0021
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.23029 | val 0.40908
  Epoch 012 - train 0.21829 | val 0.41617
  Regression -> MSE: 0.000686, MAE: 0.019439, R²: -0.0002
  Directional -> Accuracy: 0.6316, MCC: 0.2799, F1: 0.6957

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.22021 | val 0.46913
  Epoch 011 - train 0.20764 | val 0.47710
  Regression -> MSE: 0.000144, MAE: 0.009218, R²: -0.0449
  Directional -> Accuracy: 0.5238, MCC: 0.1249, F1: 0.6154

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.20300 | val 0.45373
  Epoch 011 - train 0.20097 | val 0.46062
  Regression -> MSE: 0.000226, MAE: 0.010705, R²: 0.0036
  Directional -> Accuracy: 0.4500, MCC: -0.1155, F1: 0.2667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.21553 | val 0.67104
  Epoch 019 - train 0.17827 | val 0.80933
  Regression -> MSE: 0.000373, MAE: 0.016346, R²: -0.0178
  Directional -> Accuracy: 0.4902, MCC: 0.0659, F1: 0.6061

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.25136 | val 0.48011
  Epoch 011 - train 0.23748 | val 0.57948
  Regression -> MSE: 0.000116, MAE: 0.008420, R²: -0.0716
  Directional -> Accuracy: 0.4058, MCC: -0.1950, F1: 0.1277

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.22950 | val 0.64147
  Epoch 011 - train 0.21707 | val 0.65194
  Regression -> MSE: 0.000157, MAE: 0.009644, R²: 0.0042
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.24827 | val 0.57968
  Epoch 011 - train 0.23712 | val 0.62675
  Regression -> MSE: 0.000276, MAE: 0.013139, R²: -0.0095
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.23667 | val 0.39895
  Epoch 016 - train 0.21027 | val 0.39825
  Regression -> MSE: 0.000170, MAE: 0.009335, R²: -0.1216
  Directional -> Accuracy: 0.5000, MCC: 0.1376, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.25377 | val 0.47287
  Epoch 014 - train 0.21936 | val 0.46873
  Regression -> MSE: 0.000395, MAE: 0.015393, R²: -0.7357
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.21979 | val 0.43106
  Epoch 011 - train 0.22821 | val 0.44684
  Regression -> MSE: 0.000144, MAE: 0.008455, R²: -0.0012
  Directional -> Accuracy: 0.4894, MCC: -0.0805, F1: 0.5862

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.22846 | val 0.38891
  Epoch 011 - train 0.22376 | val 0.37510
  Regression -> MSE: 0.000174, MAE: 0.010203, R²: -0.0525
  Directional -> Accuracy: 0.5538, MCC: 0.1513, F1: 0.3556

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.24998 | val 0.38575
  Epoch 011 - train 0.24609 | val 0.38916
  Regression -> MSE: 0.000087, MAE: 0.007171, R²: -0.0014
  Directional -> Accuracy: 0.5263, MCC: 0.0784, F1: 0.5091

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.24595 | val 0.42883
  Epoch 013 - train 0.22743 | val 0.47381
  Regression -> MSE: 0.000210, MAE: 0.011159, R²: 0.0039
  Directional -> Accuracy: 0.5385, MCC: 0.1027, F1: 0.6053

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.20733 | val 0.26353
  Epoch 016 - train 0.17032 | val 0.27493
  Regression -> MSE: 0.000105, MAE: 0.008092, R²: -0.1685
  Directional -> Accuracy: 0.5636, MCC: 0.2170, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.21101 | val 0.31880
  Epoch 011 - train 0.20890 | val 0.31695
  Regression -> MSE: 0.000108, MAE: 0.008902, R²: -0.0889
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.23842 | val 0.28949
  Epoch 012 - train 0.22306 | val 0.29465
  Regression -> MSE: 0.000239, MAE: 0.012893, R²: -0.0097
  Directional -> Accuracy: 0.5952, MCC: 0.1334, F1: 0.7302

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.24817 | val 0.39890
  Epoch 011 - train 0.23413 | val 0.40091
  Regression -> MSE: 0.000243, MAE: 0.010240, R²: -0.4318
  Directional -> Accuracy: 0.4643, MCC: 0.1211, F1: 0.0625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.20982 | val 0.30473
  Epoch 011 - train 0.19920 | val 0.32625
  Regression -> MSE: 0.000240, MAE: 0.012025, R²: 0.0084
  Directional -> Accuracy: 0.5750, MCC: 0.1770, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.23484 | val 0.54906
  Epoch 012 - train 0.22082 | val 0.54501
  Regression -> MSE: 0.000231, MAE: 0.010021, R²: 0.0187
  Directional -> Accuracy: 0.4524, MCC: -0.0830, F1: 0.5660

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.23620 | val 0.47313
  Epoch 011 - train 0.21505 | val 0.47713
  Regression -> MSE: 0.000146, MAE: 0.008511, R²: -0.0611
  Directional -> Accuracy: 0.4524, MCC: -0.0912, F1: 0.4651

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.23752 | val 0.45173
  Epoch 011 - train 0.22340 | val 0.45351
  Regression -> MSE: 0.000183, MAE: 0.010233, R²: -0.0019
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.20512 | val 0.36442
  Epoch 011 - train 0.20702 | val 0.37613
  Regression -> MSE: 0.000317, MAE: 0.012000, R²: -0.1940
  Directional -> Accuracy: 0.5278, MCC: 0.1419, F1: 0.3929

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.18017 | val 0.44082
  Epoch 013 - train 0.16719 | val 0.42926
  Regression -> MSE: 0.000174, MAE: 0.009987, R²: 0.0487
  Directional -> Accuracy: 0.5581, MCC: 0.1239, F1: 0.5957

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.22825 | val 0.31536
  Epoch 011 - train 0.22745 | val 0.32393
  Regression -> MSE: 0.000357, MAE: 0.012676, R²: -0.0271
  Directional -> Accuracy: 0.4091, MCC: -0.1445, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.21494 | val 0.18478
  Epoch 020 - train 0.16404 | val 0.17599
  Epoch 024 - train 0.14171 | val 0.18633
  Regression -> MSE: 0.000206, MAE: 0.010174, R²: -0.9494
  Directional -> Accuracy: 0.6667, MCC: 0.3708, F1: 0.6111

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.22005 | val 0.50561
  Epoch 011 - train 0.21662 | val 0.54928
  Regression -> MSE: 0.000223, MAE: 0.011282, R²: -0.0134
  Directional -> Accuracy: 0.5357, MCC: 0.0890, F1: 0.5667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.20336 | val 0.65500
  Epoch 011 - train 0.19604 | val 0.70250
  Regression -> MSE: 0.000084, MAE: 0.007192, R²: -0.1390
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.20322 | val 0.17262
  Epoch 020 - train 0.17414 | val 0.18111
  Regression -> MSE: 0.000527, MAE: 0.019659, R²: -0.6936
  Directional -> Accuracy: 0.3333, MCC: -0.1970, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.23146 | val 0.49282
  Epoch 011 - train 0.22125 | val 0.55003
  Regression -> MSE: 0.000079, MAE: 0.007000, R²: -0.0144
  Directional -> Accuracy: 0.5135, MCC: 0.1622, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.22080 | val 0.40612
  Epoch 011 - train 0.22558 | val 0.40393
  Regression -> MSE: 0.000302, MAE: 0.014385, R²: -0.0049
  Directional -> Accuracy: 0.5556, MCC: 0.1094, F1: 0.6154

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.22979 | val 0.34483
  Epoch 017 - train 0.19120 | val 0.35771
  Regression -> MSE: 0.000098, MAE: 0.007173, R²: 0.0376
  Directional -> Accuracy: 0.6190, MCC: 0.2123, F1: 0.6800

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.24572 | val 0.41342
  Epoch 013 - train 0.23194 | val 0.43246
  Regression -> MSE: 0.000180, MAE: 0.010397, R²: -0.0274
  Directional -> Accuracy: 0.3542, MCC: -0.1585, F1: 0.4918

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.20011 | val 0.43176
  Epoch 011 - train 0.19026 | val 0.45915
  Regression -> MSE: 0.000226, MAE: 0.011864, R²: -0.0002
  Directional -> Accuracy: 0.5636, MCC: 0.1491, F1: 0.7143

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.22082 | val 0.90136
  Epoch 012 - train 0.20145 | val 1.00450
  Regression -> MSE: 0.000101, MAE: 0.008153, R²: -0.0709
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.24794 | val 0.53436
  Epoch 011 - train 0.24934 | val 0.53142
  Regression -> MSE: 0.000166, MAE: 0.010323, R²: 0.0026
  Directional -> Accuracy: 0.5660, MCC: 0.1343, F1: 0.6349

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.22903 | val 0.40899
  Epoch 011 - train 0.21803 | val 0.39973
  Regression -> MSE: 0.000140, MAE: 0.009433, R²: -0.1869
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.24630 | val 0.46574

[I 2026-02-23 22:57:53,868] Trial 14 finished with value: -0.011839089784867059 and parameters: {'feature_set': 'finbert', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.009578413958991552, 'weight_decay': 0.000665052163937797, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.5862567977836898, 'early_stopping_min_delta': 0.006485099031659643}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 018 - train 0.21626 | val 0.49143
  Regression -> MSE: 0.000239, MAE: 0.012250, R²: 0.0046
  Directional -> Accuracy: 0.5167, MCC: 0.0111, F1: 0.1714

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.31030 | val 0.82712
  Epoch 018 - train 0.24152 | val 1.00432
  Regression -> MSE: 0.000253, MAE: 0.012662, R²: -0.0220
  Directional -> Accuracy: 0.4675, MCC: -0.0220, F1: 0.5591

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.28411 | val 0.61275
  Epoch 018 - train 0.24106 | val 0.93619
  Regression -> MSE: 0.000674, MAE: 0.019118, R²: 0.0155
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.31409 | val 1.05877
  Epoch 016 - train 0.25721 | val 1.06777
  Regression -> MSE: 0.000317, MAE: 0.014462, R²: -0.0224
  Directional -> Accuracy: 0.4468, MCC: -0.0853, F1: 0.2353

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.25670 | val 1.89231
  Epoch 016 - train 0.21029 | val 2.42440
  Regression -> MSE: 0.000394, MAE: 0.015365, R²: -0.1278
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.31826 | val 0.70444
  Epoch 018 - train 0.25245 | val 0.83067
  Regression -> MSE: 0.000197, MAE: 0.009944, R²: 0.0321
  Directional -> Accuracy: 0.5882, MCC: 0.2986, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.25993 | val 1.39334
  Epoch 020 - train 0.16929 | val 2.25230
  Regression -> MSE: 0.000565, MAE: 0.018378, R²: -0.0173
  Directional -> Accuracy: 0.5106, MCC: 0.0065, F1: 0.1481

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.32459 | val 0.73216
  Epoch 019 - train 0.23977 | val 0.81774
  Regression -> MSE: 0.000242, MAE: 0.011942, R²: 0.0121
  Directional -> Accuracy: 0.5362, MCC: 0.0492, F1: 0.4483

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.24194 | val 0.94136
  Epoch 016 - train 0.22630 | val 1.33467
  Regression -> MSE: 0.000636, MAE: 0.019980, R²: -0.0646
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.29067 | val 0.67391
  Epoch 016 - train 0.26603 | val 0.71801
  Regression -> MSE: 0.000386, MAE: 0.016007, R²: -0.0066
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.28204 | val 0.87413
  Epoch 016 - train 0.26810 | val 0.91600
  Regression -> MSE: 0.000240, MAE: 0.011914, R²: 0.0068
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.28329 | val 1.52535
  Epoch 016 - train 0.23960 | val 1.69767
  Regression -> MSE: 0.000311, MAE: 0.013787, R²: -0.0014
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.33490 | val 0.92609
  Epoch 016 - train 0.27299 | val 0.91833
  Regression -> MSE: 0.000676, MAE: 0.019624, R²: 0.0024
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.32364 | val 0.69188
  Epoch 016 - train 0.27577 | val 0.76563
  Regression -> MSE: 0.000138, MAE: 0.009049, R²: -0.0009
  Directional -> Accuracy: 0.5116, MCC: -0.1965, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.28900 | val 0.69295
  Epoch 020 - train 0.22694 | val 0.67641
  Epoch 030 - train 0.18674 | val 0.69060
  Regression -> MSE: 0.000251, MAE: 0.011743, R²: -0.1167
  Directional -> Accuracy: 0.5246, MCC: 0.0470, F1: 0.5672

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.31489 | val 1.60456
  Epoch 016 - train 0.27174 | val 1.95405
  Regression -> MSE: 0.000372, MAE: 0.015923, R²: -0.0279
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.32685 | val 0.69468
  Epoch 016 - train 0.27647 | val 0.73814
  Regression -> MSE: 0.000107, MAE: 0.008056, R²: 0.0067
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.29761 | val 1.35809
  Epoch 016 - train 0.27018 | val 1.47541
  Regression -> MSE: 0.000156, MAE: 0.009514, R²: -0.0022
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.33547 | val 0.73763
  Epoch 016 - train 0.27138 | val 0.85806
  Regression -> MSE: 0.000283, MAE: 0.013521, R²: -0.0406
  Directional -> Accuracy: 0.4079, MCC: 0.0933, F1: 0.0426

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.26385 | val 0.73817
  Epoch 020 - train 0.19363 | val 0.70844
  Epoch 022 - train 0.19192 | val 0.70954
  Regression -> MSE: 0.000291, MAE: 0.013542, R²: -0.9481
  Directional -> Accuracy: 0.4308, MCC: 0.0366, F1: 0.0976

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.32112 | val 0.86661
  Epoch 020 - train 0.25276 | val 0.90845
  Regression -> MSE: 0.000561, MAE: 0.019655, R²: -1.4773
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.30524 | val 0.74341
  Epoch 016 - train 0.24319 | val 0.78150
  Regression -> MSE: 0.000146, MAE: 0.008503, R²: -0.0177
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.28763 | val 0.61448
  Epoch 016 - train 0.25287 | val 0.62380
  Regression -> MSE: 0.000170, MAE: 0.010262, R²: -0.0278
  Directional -> Accuracy: 0.4848, MCC: -0.0727, F1: 0.6458

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.32954 | val 0.71165
  Epoch 016 - train 0.26220 | val 0.71663
  Regression -> MSE: 0.000085, MAE: 0.007049, R²: -0.0032
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.36198 | val 1.42681
  Epoch 016 - train 0.27886 | val 1.46072
  Regression -> MSE: 0.000215, MAE: 0.010926, R²: -0.0131
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.26701 | val 0.39292
  Epoch 019 - train 0.20529 | val 0.41178
  Regression -> MSE: 0.000104, MAE: 0.008329, R²: -0.1335
  Directional -> Accuracy: 0.4643, MCC: -0.0081, F1: 0.2857

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.31309 | val 0.33053
  Epoch 020 - train 0.17970 | val 0.31063
  Epoch 030 - train 0.11417 | val 0.32237
  Regression -> MSE: 0.000155, MAE: 0.010216, R²: -0.5035
  Directional -> Accuracy: 0.5000, MCC: 0.0488, F1: 0.5490

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.27580 | val 0.47434
  Epoch 020 - train 0.22166 | val 0.51136
  Epoch 021 - train 0.23955 | val 0.52270
  Regression -> MSE: 0.000243, MAE: 0.012791, R²: -0.0503
  Directional -> Accuracy: 0.5116, MCC: 0.0044, F1: 0.5714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.29869 | val 0.69027
  Epoch 016 - train 0.25991 | val 0.70203
  Regression -> MSE: 0.000181, MAE: 0.007970, R²: -0.0889
  Directional -> Accuracy: 0.4035, MCC: -0.1724, F1: 0.0556

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.24239 | val 0.32238
  Epoch 016 - train 0.22914 | val 0.40233
  Regression -> MSE: 0.000236, MAE: 0.011830, R²: 0.0040
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.27673 | val 1.17247
  Epoch 016 - train 0.26657 | val 1.37632
  Regression -> MSE: 0.000232, MAE: 0.009904, R²: -0.0049
  Directional -> Accuracy: 0.4884, MCC: -0.0111, F1: 0.6071

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.25475 | val 0.77589
  Epoch 016 - train 0.24580 | val 0.87635
  Regression -> MSE: 0.000139, MAE: 0.008403, R²: -0.0279
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.31782 | val 0.69893
  Epoch 016 - train 0.25452 | val 0.72996
  Regression -> MSE: 0.000193, MAE: 0.010441, R²: -0.0240
  Directional -> Accuracy: 0.4200, MCC: -0.1391, F1: 0.2564

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.26250 | val 0.57109
  Epoch 020 - train 0.21693 | val 0.58530
  Regression -> MSE: 0.000444, MAE: 0.015023, R²: -0.6969
  Directional -> Accuracy: 0.5068, MCC: 0.1076, F1: 0.3571

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.29728 | val 0.40781
  Epoch 016 - train 0.22110 | val 0.61799
  Regression -> MSE: 0.000165, MAE: 0.010324, R²: 0.0122
  Directional -> Accuracy: 0.5263, MCC: 0.0529, F1: 0.5000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.27822 | val 0.63688
  Epoch 016 - train 0.22287 | val 0.68023
  Regression -> MSE: 0.000179, MAE: 0.010251, R²: 0.0033
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.30061 | val 0.54378
  Epoch 016 - train 0.26851 | val 0.53285
  Regression -> MSE: 0.000342, MAE: 0.012137, R²: 0.0008
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.26636 | val 0.24998
  Epoch 016 - train 0.22196 | val 0.28202
  Regression -> MSE: 0.000116, MAE: 0.008315, R²: -0.1066
  Directional -> Accuracy: 0.5349, MCC: 0.0664, F1: 0.5833

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.29537 | val 1.08515
  Epoch 017 - train 0.28444 | val 1.09814
  Regression -> MSE: 0.000221, MAE: 0.011385, R²: -0.0126
  Directional -> Accuracy: 0.4561, MCC: -0.1409, F1: 0.6265

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.29380 | val 1.52688
  Epoch 020 - train 0.19568 | val 1.67777
  Regression -> MSE: 0.000078, MAE: 0.006979, R²: -0.0066
  Directional -> Accuracy: 0.6383, MCC: 0.1871, F1: 0.7733

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.28278 | val 0.30115
  Epoch 016 - train 0.25464 | val 0.33410
  Regression -> MSE: 0.000316, MAE: 0.014324, R²: -0.0275
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.5152

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.32922 | val 0.23279
  Epoch 016 - train 0.21743 | val 0.25816
  Regression -> MSE: 0.000258, MAE: 0.011455, R²: -0.0591
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.28855 | val 0.76844
  Epoch 016 - train 0.24262 | val 0.78548
  Regression -> MSE: 0.000081, MAE: 0.007126, R²: -0.0059
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.23794 | val 0.66430
  Epoch 020 - train 0.20994 | val 0.94707
  Regression -> MSE: 0.000310, MAE: 0.014563, R²: -0.0099
  Directional -> Accuracy: 0.5319, MCC: 0.0792, F1: 0.4211

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.29820 | val 0.55387
  Epoch 020 - train 0.18024 | val 0.58615
  Epoch 027 - train 0.19009 | val 0.59680
  Regression -> MSE: 0.000101, MAE: 0.007222, R²: -0.0313
  Directional -> Accuracy: 0.5227, MCC: -0.0348, F1: 0.6441

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.27381 | val 0.78176
  Epoch 016 - train 0.28967 | val 0.84482
  Regression -> MSE: 0.000172, MAE: 0.009742, R²: -0.0006
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.28846 | val 0.89378
  Epoch 016 - train 0.26330 | val 0.86076
  Regression -> MSE: 0.000227, MAE: 0.011805, R²: -0.0168
  Directional -> Accuracy: 0.4464, MCC: -0.1448, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.30284 | val 0.86411
  Epoch 016 - train 0.23925 | val 0.92233
  Regression -> MSE: 0.000093, MAE: 0.007739, R²: -0.0098
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.28618 | val 1.31568
  Epoch 016 - train 0.27200 | val 1.59819
  Regression -> MSE: 0.000163, MAE: 0.010219, R²: 0.0018
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.28783 | val 0.95216
  Epoch 016 - train 0.26422 | val 1.01209
  Regression -> MSE: 0.000123, MAE: 0.009022, R²: -0.0617
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.33647 | val 0.89284
  Epoch 020 - train 0.26246 | val 1.01305

[I 2026-02-23 22:59:33,751] Trial 15 finished with value: -0.011822183658632185 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.5, 'batch_size': 32, 'learning_rate': 0.0003473123789919666, 'weight_decay': 7.525519565675031e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 1.6606229745087508, 'early_stopping_min_delta': 0.00782759923654495}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 023 - train 0.24568 | val 0.96057
  Regression -> MSE: 0.000238, MAE: 0.012667, R²: -0.0054
  Directional -> Accuracy: 0.5082, MCC: 0.0453, F1: 0.5946

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.39197 | val 0.62424
  Epoch 011 - train 0.38743 | val 0.62569
  Regression -> MSE: 0.000249, MAE: 0.012648, R²: -0.0142
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.41293 | val 0.41454
  Epoch 011 - train 0.41067 | val 0.41663
  Regression -> MSE: 0.000704, MAE: 0.019850, R²: -0.0182
  Directional -> Accuracy: 0.4894, MCC: -0.2347, F1: 0.6571

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.42190 | val 0.81957
  Epoch 011 - train 0.42515 | val 0.81855
  Regression -> MSE: 0.000365, MAE: 0.015258, R²: -0.0580
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33698 | val 0.44748
  Epoch 011 - train 0.33546 | val 0.46988
  Regression -> MSE: 0.000344, MAE: 0.014362, R²: 0.0026
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42703 | val 0.41194
  Epoch 011 - train 0.42660 | val 0.41203
  Regression -> MSE: 0.000202, MAE: 0.010191, R²: -0.0053
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39477 | val 0.96993
  Epoch 011 - train 0.38610 | val 0.97114
  Regression -> MSE: 0.000588, MAE: 0.018568, R²: -0.0273
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.43399 | val 0.63296
  Epoch 011 - train 0.43726 | val 0.63591
  Regression -> MSE: 0.000250, MAE: 0.011965, R²: -0.0164
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41836 | val 0.71161
  Epoch 011 - train 0.42806 | val 0.72318
  Regression -> MSE: 0.000633, MAE: 0.019737, R²: -0.0822
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43451 | val 0.71468
  Epoch 011 - train 0.43781 | val 0.71471
  Regression -> MSE: 0.000338, MAE: 0.014808, R²: -0.0007
  Directional -> Accuracy: 0.6429, MCC: 0.1991, F1: 0.1176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42285 | val 0.64708
  Epoch 011 - train 0.41973 | val 0.65485
  Regression -> MSE: 0.000244, MAE: 0.011548, R²: -0.0244
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.39863 | val 0.68996
  Epoch 011 - train 0.39397 | val 0.70096
  Regression -> MSE: 0.000322, MAE: 0.013578, R²: -0.0540
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43681 | val 0.57702
  Epoch 011 - train 0.43717 | val 0.58079
  Regression -> MSE: 0.000680, MAE: 0.019568, R²: -0.0160
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42591 | val 0.41381
  Epoch 011 - train 0.41052 | val 0.41467
  Regression -> MSE: 0.000150, MAE: 0.009525, R²: -0.0035
  Directional -> Accuracy: 0.5227, MCC: 0.1475, F1: 0.6316

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38513 | val 0.61438
  Epoch 011 - train 0.37281 | val 0.61386
  Regression -> MSE: 0.000226, MAE: 0.010796, R²: -0.0065
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42059 | val 1.18183
  Epoch 011 - train 0.40233 | val 1.19113
  Regression -> MSE: 0.000380, MAE: 0.016495, R²: -0.0121
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.43389 | val 0.46328
  Epoch 011 - train 0.43346 | val 0.46288
  Regression -> MSE: 0.000107, MAE: 0.007921, R²: -0.0095
  Directional -> Accuracy: 0.5352, MCC: 0.0000, F1: 0.6972

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39294 | val 0.88897
  Epoch 011 - train 0.38888 | val 0.89369
  Regression -> MSE: 0.000161, MAE: 0.009902, R²: -0.0028
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.43362 | val 0.47235
  Epoch 011 - train 0.42749 | val 0.50326
  Regression -> MSE: 0.000277, MAE: 0.013234, R²: -0.0302
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.34771 | val 0.65317
  Epoch 020 - train 0.33838 | val 0.65767
  Regression -> MSE: 0.000181, MAE: 0.009851, R²: -0.2268
  Directional -> Accuracy: 0.4545, MCC: 0.1218, F1: 0.1818

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42587 | val 0.77818
  Epoch 011 - train 0.42038 | val 0.78328
  Regression -> MSE: 0.000227, MAE: 0.010924, R²: -0.0024
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43438 | val 0.55010
  Epoch 020 - train 0.41986 | val 0.58302
  Regression -> MSE: 0.000166, MAE: 0.009266, R²: -0.1183
  Directional -> Accuracy: 0.4898, MCC: 0.1758, F1: 0.3902

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.37487 | val 0.49831
  Epoch 011 - train 0.36904 | val 0.50087
  Regression -> MSE: 0.000188, MAE: 0.010608, R²: -0.0641
  Directional -> Accuracy: 0.4478, MCC: -0.1154, F1: 0.2449

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.44472 | val 0.56446
  Epoch 011 - train 0.44219 | val 0.56524
  Regression -> MSE: 0.000085, MAE: 0.007025, R²: -0.0126
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42375 | val 0.56641
  Epoch 011 - train 0.42187 | val 0.56654
  Regression -> MSE: 0.000219, MAE: 0.011427, R²: -0.0011
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39362 | val 0.32124
  Epoch 011 - train 0.38334 | val 0.32071
  Regression -> MSE: 0.000099, MAE: 0.008249, R²: -0.0824
  Directional -> Accuracy: 0.4386, MCC: -0.1055, F1: 0.4286

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42524 | val 0.19572
  Epoch 011 - train 0.42342 | val 0.19574
  Regression -> MSE: 0.000139, MAE: 0.009687, R²: -0.1066
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46375 | val 0.35952
  Epoch 020 - train 0.43550 | val 0.36422
  Regression -> MSE: 0.000244, MAE: 0.012873, R²: -0.0268
  Directional -> Accuracy: 0.5682, MCC: -0.1269, F1: 0.7246

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41922 | val 0.51305
  Epoch 020 - train 0.40525 | val 0.50081
  Regression -> MSE: 0.000213, MAE: 0.009142, R²: -0.3011
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43495 | val 0.24500
  Epoch 011 - train 0.41825 | val 0.24505
  Regression -> MSE: 0.000234, MAE: 0.011897, R²: 0.0035
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.43506 | val 0.70573
  Epoch 011 - train 0.41981 | val 0.70575
  Regression -> MSE: 0.000251, MAE: 0.010403, R²: -0.0034
  Directional -> Accuracy: 0.4222, MCC: -0.1935, F1: 0.1333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43151 | val 0.65694
  Epoch 011 - train 0.42074 | val 0.65976
  Regression -> MSE: 0.000133, MAE: 0.008162, R²: 0.0017
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43068 | val 0.62217
  Epoch 011 - train 0.43023 | val 0.62111
  Regression -> MSE: 0.000189, MAE: 0.010495, R²: -0.0014
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37046 | val 0.57863
  Epoch 020 - train 0.35845 | val 0.56608
  Regression -> MSE: 0.000275, MAE: 0.010919, R²: -0.0662
  Directional -> Accuracy: 0.5135, MCC: 0.1013, F1: 0.4194

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.39933 | val 0.35825
  Epoch 011 - train 0.40757 | val 0.35770
  Regression -> MSE: 0.000162, MAE: 0.010175, R²: 0.0014
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.36693 | val 0.48267
  Epoch 011 - train 0.37530 | val 0.48744
  Regression -> MSE: 0.000181, MAE: 0.010378, R²: 0.0078
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42255 | val 0.41283
  Epoch 011 - train 0.41096 | val 0.41456
  Regression -> MSE: 0.000367, MAE: 0.013085, R²: -0.0506
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45973 | val 0.24714
  Epoch 011 - train 0.45052 | val 0.24639
  Regression -> MSE: 0.000113, MAE: 0.008259, R²: -0.0919
  Directional -> Accuracy: 0.4545, MCC: -0.1581, F1: 0.6129

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42291 | val 0.66549
  Epoch 020 - train 0.40983 | val 0.65882
  Regression -> MSE: 0.000223, MAE: 0.011394, R²: -0.0354
  Directional -> Accuracy: 0.5172, MCC: 0.2180, F1: 0.6585

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40040 | val 0.91967
  Epoch 011 - train 0.39180 | val 0.92221
  Regression -> MSE: 0.000098, MAE: 0.007764, R²: -0.2339
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49238 | val 0.35683
  Epoch 011 - train 0.47845 | val 0.35680
  Regression -> MSE: 0.000358, MAE: 0.016213, R²: -0.0920
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.42454 | val 0.23251
  Epoch 011 - train 0.43446 | val 0.23136
  Regression -> MSE: 0.000249, MAE: 0.011172, R²: -0.0476
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.39251 | val 0.54052
  Epoch 020 - train 0.36708 | val 0.53251
  Regression -> MSE: 0.000083, MAE: 0.007221, R²: -0.0403
  Directional -> Accuracy: 0.4868, MCC: -0.1155, F1: 0.6549

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43204 | val 0.47098
  Epoch 011 - train 0.44971 | val 0.47144
  Regression -> MSE: 0.000359, MAE: 0.015282, R²: 0.0025
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.41081 | val 0.53415
  Epoch 011 - train 0.42196 | val 0.53414
  Regression -> MSE: 0.000097, MAE: 0.007185, R²: -0.0082
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46797 | val 0.71133
  Epoch 011 - train 0.46618 | val 0.71390
  Regression -> MSE: 0.000183, MAE: 0.010480, R²: -0.0144
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.36849 | val 0.53118
  Epoch 011 - train 0.37549 | val 0.53051
  Regression -> MSE: 0.000226, MAE: 0.011789, R²: -0.0276
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.42665 | val 0.50334
  Epoch 011 - train 0.41344 | val 0.50388
  Regression -> MSE: 0.000092, MAE: 0.007635, R²: -0.0088
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.42736 | val 0.82603
  Epoch 011 - train 0.42900 | val 0.83114
  Regression -> MSE: 0.000162, MAE: 0.010138, R²: -0.0065
  Directional -> Accuracy: 0.4727, MCC: -0.0752, F1: 0.5538

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41578 | val 0.61328
  Epoch 011 - train 0.42412 | val 0.62477
  Regression -> MSE: 0.000123, MAE: 0.008891, R²: -0.0804
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 23:00:12,366] Trial 16 finished with value: -0.01160390659996257 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.2, 'batch_size': 64, 'learning_rate': 3.061322340705873e-05, 'weight_decay': 3.8468948701885915e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.2594573646684228, 'early_stopping_min_delta': 0.00979891367442017}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.44089 | val 0.76367
  Epoch 011 - train 0.43908 | val 0.76802
  Regression -> MSE: 0.000235, MAE: 0.012250, R²: -0.0055
  Directional -> Accuracy: 0.4355, MCC: -0.1250, F1: 0.4928

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.35294 | val 0.59304
  Epoch 011 - train 0.37388 | val 0.60731
  Regression -> MSE: 0.000263, MAE: 0.013031, R²: -0.0923
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.37105 | val 0.39174
  Epoch 011 - train 0.36902 | val 0.39832
  Regression -> MSE: 0.000713, MAE: 0.020013, R²: -0.0219
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.38516 | val 0.64333
  Epoch 018 - train 0.37932 | val 0.65629
  Regression -> MSE: 0.000316, MAE: 0.014209, R²: -0.0034
  Directional -> Accuracy: 0.5217, MCC: 0.1124, F1: 0.2667

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33012 | val 0.38111
  Epoch 011 - train 0.33162 | val 0.39417
  Regression -> MSE: 0.000359, MAE: 0.014828, R²: -0.0168
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.37798 | val 0.37165
  Epoch 011 - train 0.37434 | val 0.37659
  Regression -> MSE: 0.000208, MAE: 0.010149, R²: -0.0101
  Directional -> Accuracy: 0.4800, MCC: -0.1358, F1: 0.6389

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.37056 | val 0.73085
  Epoch 011 - train 0.37955 | val 0.73271
  Regression -> MSE: 0.000584, MAE: 0.018629, R²: -0.0324
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.38295 | val 0.47166
  Epoch 011 - train 0.38806 | val 0.47283
  Regression -> MSE: 0.000252, MAE: 0.011969, R²: -0.0151
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.37278 | val 0.39058
  Epoch 011 - train 0.35621 | val 0.39597
  Regression -> MSE: 0.000666, MAE: 0.020352, R²: -0.0908
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.37803 | val 0.44833
  Epoch 011 - train 0.35913 | val 0.44867
  Regression -> MSE: 0.000379, MAE: 0.015622, R²: -0.0169
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.35913 | val 0.52911
  Epoch 011 - train 0.37332 | val 0.53371
  Regression -> MSE: 0.000245, MAE: 0.011896, R²: -0.0014
  Directional -> Accuracy: 0.4928, MCC: 0.0648, F1: 0.5570

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.33657 | val 0.64405
  Epoch 011 - train 0.34171 | val 0.65428
  Regression -> MSE: 0.000313, MAE: 0.013893, R²: -0.0034
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.37776 | val 0.46151
  Epoch 011 - train 0.37583 | val 0.46808
  Regression -> MSE: 0.000679, MAE: 0.019501, R²: 0.0097
  Directional -> Accuracy: 0.5263, MCC: 0.1360, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.34662 | val 0.38997
  Epoch 011 - train 0.33712 | val 0.39093
  Regression -> MSE: 0.000144, MAE: 0.009436, R²: -0.0452
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.30694 | val 0.49210
  Epoch 018 - train 0.32503 | val 0.49474
  Regression -> MSE: 0.000223, MAE: 0.010697, R²: 0.0151
  Directional -> Accuracy: 0.5167, MCC: 0.0349, F1: 0.5797

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.35042 | val 0.89387
  Epoch 011 - train 0.36215 | val 0.90279
  Regression -> MSE: 0.000369, MAE: 0.016126, R²: -0.0072
  Directional -> Accuracy: 0.4510, MCC: -0.0728, F1: 0.5000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.37765 | val 0.36889
  Epoch 011 - train 0.37482 | val 0.37173
  Regression -> MSE: 0.000111, MAE: 0.007972, R²: -0.0232
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.36879 | val 0.75273
  Epoch 011 - train 0.37634 | val 0.78038
  Regression -> MSE: 0.000157, MAE: 0.009854, R²: 0.0052
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.35899 | val 0.38505
  Epoch 011 - train 0.37976 | val 0.40109
  Regression -> MSE: 0.000274, MAE: 0.013064, R²: 0.0002
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.30582 | val 0.50285
  Epoch 011 - train 0.31206 | val 0.50396
  Regression -> MSE: 0.000158, MAE: 0.008927, R²: -0.0429
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.38567 | val 0.65320
  Epoch 011 - train 0.39669 | val 0.66373
  Regression -> MSE: 0.000227, MAE: 0.010859, R²: 0.0016
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.38341 | val 0.47470
  Epoch 019 - train 0.38299 | val 0.47148
  Regression -> MSE: 0.000154, MAE: 0.008846, R²: -0.0709
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.32907 | val 0.43393
  Epoch 016 - train 0.33176 | val 0.43302
  Regression -> MSE: 0.000170, MAE: 0.010199, R²: -0.0258
  Directional -> Accuracy: 0.5846, MCC: 0.1686, F1: 0.6087

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.39965 | val 0.44766
  Epoch 011 - train 0.39427 | val 0.44848
  Regression -> MSE: 0.000090, MAE: 0.007349, R²: -0.0394
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.37225 | val 0.63393
  Epoch 011 - train 0.37736 | val 0.66388
  Regression -> MSE: 0.000219, MAE: 0.011004, R²: -0.0373
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.31777 | val 0.30534
  Epoch 020 - train 0.31173 | val 0.29709
  Regression -> MSE: 0.000094, MAE: 0.008029, R²: -0.0455
  Directional -> Accuracy: 0.5091, MCC: -0.0659, F1: 0.6494

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.35249 | val 0.32980
  Epoch 011 - train 0.40596 | val 0.33227
  Regression -> MSE: 0.000116, MAE: 0.009152, R²: -0.1625
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.38751 | val 0.33957
  Epoch 011 - train 0.39203 | val 0.34074
  Regression -> MSE: 0.000239, MAE: 0.012924, R²: -0.0109
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.36507 | val 0.44552
  Epoch 011 - train 0.35983 | val 0.44690
  Regression -> MSE: 0.000179, MAE: 0.007989, R²: -0.0557
  Directional -> Accuracy: 0.5000, MCC: -0.0196, F1: 0.5625

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.39044 | val 0.32282
  Epoch 011 - train 0.38351 | val 0.32491
  Regression -> MSE: 0.000247, MAE: 0.012260, R²: -0.0208
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.37215 | val 0.65312
  Epoch 011 - train 0.36372 | val 0.65322
  Regression -> MSE: 0.000236, MAE: 0.010085, R²: -0.0029
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.35476 | val 0.43846
  Epoch 011 - train 0.35995 | val 0.44000
  Regression -> MSE: 0.000143, MAE: 0.008581, R²: -0.0374
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.36406 | val 0.50493
  Epoch 011 - train 0.34781 | val 0.50476
  Regression -> MSE: 0.000185, MAE: 0.010460, R²: -0.0100
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.34136 | val 0.48842
  Epoch 011 - train 0.34878 | val 0.49284
  Regression -> MSE: 0.000274, MAE: 0.010932, R²: -0.0323
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.33783 | val 0.40143
  Epoch 011 - train 0.33343 | val 0.40247
  Regression -> MSE: 0.000187, MAE: 0.010540, R²: -0.0185
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.33983 | val 0.34102
  Epoch 011 - train 0.34588 | val 0.34024
  Regression -> MSE: 0.000352, MAE: 0.012193, R²: -0.0110
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.38049 | val 0.22169
  Epoch 011 - train 0.37484 | val 0.22785
  Regression -> MSE: 0.000127, MAE: 0.008481, R²: -0.2056
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.39449 | val 0.60321
  Epoch 011 - train 0.38586 | val 0.62565
  Regression -> MSE: 0.000221, MAE: 0.011294, R²: -0.0064
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.37180 | val 0.75090
  Epoch 011 - train 0.35233 | val 0.75525
  Regression -> MSE: 0.000084, MAE: 0.007182, R²: -0.1420
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.34086 | val 0.22024
  Epoch 011 - train 0.34912 | val 0.22021
  Regression -> MSE: 0.000321, MAE: 0.014406, R²: -0.0298
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.35351 | val 0.49258
  Epoch 011 - train 0.34549 | val 0.49562
  Regression -> MSE: 0.000078, MAE: 0.006901, R²: -0.0026
  Directional -> Accuracy: 0.5135, MCC: 0.0199, F1: 0.4194

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.36956 | val 0.46918
  Epoch 020 - train 0.35928 | val 0.45948
  Regression -> MSE: 0.000296, MAE: 0.014361, R²: 0.0174
  Directional -> Accuracy: 0.5111, MCC: 0.0165, F1: 0.5769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40337 | val 0.40046
  Epoch 011 - train 0.40051 | val 0.40099
  Regression -> MSE: 0.000102, MAE: 0.007547, R²: -0.0018
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.41904 | val 0.49185
  Epoch 011 - train 0.41216 | val 0.49125
  Regression -> MSE: 0.000177, MAE: 0.009912, R²: -0.0107
  Directional -> Accuracy: 0.4583, MCC: -0.1080, F1: 0.3500

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.31759 | val 0.43190
  Epoch 011 - train 0.32118 | val 0.43886
  Regression -> MSE: 0.000226, MAE: 0.011824, R²: -0.0032
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.35223 | val 0.43441
  Epoch 011 - train 0.34868 | val 0.43688
  Regression -> MSE: 0.000094, MAE: 0.007755, R²: -0.0024
  Directional -> Accuracy: 0.4643, MCC: -0.1486, F1: 0.1176

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.38504 | val 0.64438
  Epoch 011 - train 0.39088 | val 0.64703
  Regression -> MSE: 0.000169, MAE: 0.010324, R²: -0.0111
  Directional -> Accuracy: 0.4906, MCC: -0.0054, F1: 0.1290

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.38975 | val 0.47310
  Epoch 011 - train 0.36081 | val 0.47715
  Regression -> MSE: 0.000122, MAE: 0.009160, R²: -0.0363
  Directional -> Accuracy: 0.4727, MCC: -0.0598, F1: 0.5085

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 23:01:09,615] Trial 17 finished with value: -0.011524598417342975 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 1.128341420662171e-06, 'weight_decay': 5.407432734048977e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.7625707606808072, 'early_stopping_min_delta': 0.005347047006091131}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.38697 | val 0.62189
  Epoch 011 - train 0.40675 | val 0.63835
  Regression -> MSE: 0.000244, MAE: 0.012467, R²: -0.0146
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.06580 | val 0.09494
  Epoch 017 - train 0.05996 | val 0.10049
  Regression -> MSE: 0.000258, MAE: 0.012972, R²: -0.0472
  Directional -> Accuracy: 0.4937, MCC: 0.1595, F1: 0.6296

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.06253 | val 0.17207
  Epoch 017 - train 0.05764 | val 0.18501
  Regression -> MSE: 0.000664, MAE: 0.019068, R²: 0.0196
  Directional -> Accuracy: 0.6667, MCC: 0.3295, F1: 0.7576

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.06714 | val 0.14163
  Epoch 016 - train 0.06560 | val 0.14541
  Regression -> MSE: 0.000362, MAE: 0.015307, R²: -0.0437
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.05527 | val 0.17633
  Epoch 016 - train 0.05226 | val 0.15229
  Regression -> MSE: 0.000377, MAE: 0.014981, R²: -0.0612
  Directional -> Accuracy: 0.4416, MCC: -0.1257, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.06727 | val 0.06961
  Epoch 020 - train 0.05795 | val 0.07058
  Epoch 027 - train 0.05848 | val 0.07157
  Regression -> MSE: 0.000204, MAE: 0.010485, R²: -0.0271
  Directional -> Accuracy: 0.6604, MCC: 0.3744, F1: 0.5909

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.06536 | val 0.14373
  Epoch 020 - train 0.05510 | val 0.13983
  Regression -> MSE: 0.000515, MAE: 0.017829, R²: -0.0384
  Directional -> Accuracy: 0.5854, MCC: 0.1688, F1: 0.3200

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07005 | val 0.11776
  Epoch 016 - train 0.06504 | val 0.12466
  Regression -> MSE: 0.000257, MAE: 0.012166, R²: -0.0028
  Directional -> Accuracy: 0.5915, MCC: 0.0317, F1: 0.0645

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.06055 | val 0.11240
  Epoch 016 - train 0.06392 | val 0.10638
  Regression -> MSE: 0.000596, MAE: 0.019215, R²: -0.0521
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.06077 | val 0.10234
  Epoch 016 - train 0.06018 | val 0.10476
  Regression -> MSE: 0.000385, MAE: 0.015589, R²: -0.0008
  Directional -> Accuracy: 0.5814, MCC: 0.1068, F1: 0.4375

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.06504 | val 0.12038
  Epoch 016 - train 0.06309 | val 0.12047
  Regression -> MSE: 0.000243, MAE: 0.011510, R²: -0.0203
  Directional -> Accuracy: 0.5694, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06174 | val 0.11927
  Epoch 016 - train 0.05753 | val 0.11758
  Regression -> MSE: 0.000305, MAE: 0.013558, R²: 0.0050
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.06788 | val 0.14647
  Epoch 016 - train 0.06709 | val 0.15746
  Regression -> MSE: 0.000665, MAE: 0.019260, R²: -0.0099
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.06595 | val 0.07894
  Epoch 016 - train 0.06421 | val 0.08560
  Regression -> MSE: 0.000147, MAE: 0.009402, R²: -0.0033
  Directional -> Accuracy: 0.4444, MCC: -0.0891, F1: 0.5614

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06449 | val 0.11744
  Epoch 016 - train 0.05611 | val 0.11823
  Regression -> MSE: 0.000231, MAE: 0.011208, R²: -0.0261
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.06476 | val 0.25562
  Epoch 016 - train 0.06298 | val 0.27081
  Regression -> MSE: 0.000390, MAE: 0.016633, R²: -0.0164
  Directional -> Accuracy: 0.4444, MCC: -0.1198, F1: 0.5833

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.06984 | val 0.11425
  Epoch 016 - train 0.06894 | val 0.11986
  Regression -> MSE: 0.000108, MAE: 0.007760, R²: -0.0230
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.06429 | val 0.16346
  Epoch 016 - train 0.06180 | val 0.18290
  Regression -> MSE: 0.000158, MAE: 0.009820, R²: -0.0032
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.06403 | val 0.12449
  Epoch 016 - train 0.06061 | val 0.12761
  Regression -> MSE: 0.000272, MAE: 0.013087, R²: -0.0048
  Directional -> Accuracy: 0.5769, MCC: 0.1856, F1: 0.5926

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06171 | val 0.10654
  Epoch 017 - train 0.05927 | val 0.10743
  Regression -> MSE: 0.000205, MAE: 0.010667, R²: -0.3226
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.06680 | val 0.11053
  Epoch 016 - train 0.06270 | val 0.11600
  Regression -> MSE: 0.000252, MAE: 0.011435, R²: -0.0883
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.06335 | val 0.11611
  Epoch 016 - train 0.06185 | val 0.12677
  Regression -> MSE: 0.000155, MAE: 0.009000, R²: -0.0417
  Directional -> Accuracy: 0.5600, MCC: 0.0662, F1: 0.6452

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.06417 | val 0.08440
  Epoch 020 - train 0.06102 | val 0.08579
  Epoch 024 - train 0.05685 | val 0.08502
  Regression -> MSE: 0.000225, MAE: 0.011871, R²: -0.2359
  Directional -> Accuracy: 0.4559, MCC: -0.0883, F1: 0.4638

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07516 | val 0.08756
  Epoch 020 - train 0.06294 | val 0.08846
  Epoch 030 - train 0.05902 | val 0.09181
  Regression -> MSE: 0.000104, MAE: 0.007702, R²: -0.2607
  Directional -> Accuracy: 0.4000, MCC: -0.1973, F1: 0.4375

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07024 | val 0.11249
  Epoch 016 - train 0.06459 | val 0.09609
  Regression -> MSE: 0.000218, MAE: 0.011133, R²: -0.0133
  Directional -> Accuracy: 0.5147, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06193 | val 0.06025
  Epoch 020 - train 0.05721 | val 0.06513
  Epoch 023 - train 0.05565 | val 0.06555
  Regression -> MSE: 0.000115, MAE: 0.008734, R²: -0.2767
  Directional -> Accuracy: 0.5517, MCC: 0.1685, F1: 0.4583

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.06755 | val 0.05415
  Epoch 018 - train 0.06439 | val 0.06404
  Regression -> MSE: 0.000127, MAE: 0.009278, R²: -0.0187
  Directional -> Accuracy: 0.4694, MCC: 0.1786, F1: 0.6176

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07026 | val 0.05240
  Epoch 016 - train 0.06585 | val 0.05395
  Regression -> MSE: 0.000308, MAE: 0.013986, R²: -0.0581
  Directional -> Accuracy: 0.4667, MCC: 0.0680, F1: 0.3333

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.06888 | val 0.10309
  Epoch 016 - train 0.06354 | val 0.09971
  Regression -> MSE: 0.000175, MAE: 0.007715, R²: -0.0882
  Directional -> Accuracy: 0.4407, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.06871 | val 0.09187
  Epoch 016 - train 0.06093 | val 0.09397
  Regression -> MSE: 0.000232, MAE: 0.011875, R²: -0.0063
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.06973 | val 0.09562
  Epoch 020 - train 0.06120 | val 0.09518
  Epoch 024 - train 0.05347 | val 0.09598
  Regression -> MSE: 0.000246, MAE: 0.010616, R²: 0.0486
  Directional -> Accuracy: 0.5652, MCC: 0.1304, F1: 0.5652

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.06796 | val 0.10447
  Epoch 016 - train 0.06517 | val 0.10638
  Regression -> MSE: 0.000142, MAE: 0.008445, R²: -0.0119
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.06597 | val 0.10045
  Epoch 019 - train 0.06233 | val 0.10407
  Regression -> MSE: 0.000251, MAE: 0.012718, R²: -0.3491
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06316 | val 0.09824
  Epoch 016 - train 0.05705 | val 0.09995
  Regression -> MSE: 0.000278, MAE: 0.010955, R²: -0.0626
  Directional -> Accuracy: 0.5067, MCC: 0.1074, F1: 0.3509

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.05725 | val 0.08687
  Epoch 019 - train 0.05328 | val 0.10052
  Regression -> MSE: 0.000157, MAE: 0.009955, R²: 0.0336
  Directional -> Accuracy: 0.5122, MCC: 0.1543, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06039 | val 0.11554
  Epoch 016 - train 0.05621 | val 0.12354
  Regression -> MSE: 0.000231, MAE: 0.011662, R²: -0.0793
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.06329 | val 0.07958
  Epoch 016 - train 0.05923 | val 0.07770
  Regression -> MSE: 0.000357, MAE: 0.012823, R²: -0.0389
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.06689 | val 0.05653
  Epoch 020 - train 0.05779 | val 0.06608
  Regression -> MSE: 0.000122, MAE: 0.008079, R²: -0.2077
  Directional -> Accuracy: 0.6222, MCC: 0.2731, F1: 0.5405

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.06855 | val 0.12051
  Epoch 016 - train 0.06490 | val 0.11690
  Regression -> MSE: 0.000212, MAE: 0.010991, R²: -0.0010
  Directional -> Accuracy: 0.5254, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.06187 | val 0.18456
  Epoch 016 - train 0.05872 | val 0.18631
  Regression -> MSE: 0.000083, MAE: 0.007163, R²: -0.0427
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.06712 | val 0.06466
  Epoch 020 - train 0.05400 | val 0.06565
  Epoch 021 - train 0.05584 | val 0.06623
  Regression -> MSE: 0.000463, MAE: 0.018954, R²: -0.4745
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07195 | val 0.07150
  Epoch 016 - train 0.06088 | val 0.07422
  Regression -> MSE: 0.000234, MAE: 0.011037, R²: -0.0268
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.06505 | val 0.14292
  Epoch 017 - train 0.06056 | val 0.13757
  Regression -> MSE: 0.000083, MAE: 0.007190, R²: -0.0125
  Directional -> Accuracy: 0.5325, MCC: 0.1654, F1: 0.6842

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07003 | val 0.08613
  Epoch 020 - train 0.06132 | val 0.08158
  Epoch 022 - train 0.06324 | val 0.08448
  Regression -> MSE: 0.000391, MAE: 0.015872, R²: -0.0569
  Directional -> Accuracy: 0.4898, MCC: -0.0184, F1: 0.5098

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.06423 | val 0.08931
  Epoch 016 - train 0.06380 | val 0.09307
  Regression -> MSE: 0.000095, MAE: 0.007234, R²: 0.0011
  Directional -> Accuracy: 0.4468, MCC: -0.0026, F1: 0.2353

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.07317 | val 0.11978
  Epoch 016 - train 0.06368 | val 0.12868
  Regression -> MSE: 0.000194, MAE: 0.010615, R²: -0.0126
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.06762 | val 0.08731
  Epoch 016 - train 0.06315 | val 0.08771
  Regression -> MSE: 0.000218, MAE: 0.011636, R²: -0.0088
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.06404 | val 0.12607
  Epoch 016 - train 0.05939 | val 0.12279
  Regression -> MSE: 0.000096, MAE: 0.007907, R²: -0.0714
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.6591

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.06947 | val 0.13494
  Epoch 016 - train 0.06619 | val 0.14529
  Regression -> MSE: 0.000163, MAE: 0.010112, R²: -0.0304
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.06278 | val 0.17124
  Epoch 016 - train 0.06022 | val 0.19082
  Regression -> MSE: 0.000112, MAE: 0.008634, R²: 0.0008
  Directional -> Accuracy: 0.5345, MCC: 0.1371, F1: 0.6897

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.07014 | val 0.12252

[I 2026-02-23 23:02:15,618] Trial 18 finished with value: -0.011772780870371946 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.0, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.00027987068548516477, 'weight_decay': 0.0003104670769985169, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.11229024055640391, 'early_stopping_min_delta': 0.0005437670064311392}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 018 - train 0.06298 | val 0.11488
  Regression -> MSE: 0.000248, MAE: 0.012797, R²: -0.0782
  Directional -> Accuracy: 0.3968, MCC: -0.2023, F1: 0.4722

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42036 | val 0.91933
  Epoch 020 - train 0.41684 | val 0.90348
  Epoch 021 - train 0.41721 | val 0.90320
  Regression -> MSE: 0.000244, MAE: 0.012388, R²: -0.0357
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.6168

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.43167 | val 0.50782
  Epoch 020 - train 0.42583 | val 0.50506
  Epoch 021 - train 0.43518 | val 0.50493
  Regression -> MSE: 0.000751, MAE: 0.020644, R²: -0.0542
  Directional -> Accuracy: 0.3953, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.42408 | val 1.01614
  Epoch 020 - train 0.42019 | val 1.03299
  Epoch 021 - train 0.41628 | val 1.03303
  Regression -> MSE: 0.000324, MAE: 0.014569, R²: -0.0157
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.36987 | val 0.49237
  Epoch 020 - train 0.36110 | val 0.47534
  Epoch 021 - train 0.35978 | val 0.47486
  Regression -> MSE: 0.000364, MAE: 0.014772, R²: -0.0211
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40839 | val 0.41097
  Epoch 020 - train 0.40641 | val 0.40799
  Epoch 030 - train 0.39024 | val 0.40589
  Epoch 040 - train 0.38793 | val 0.40479
  Epoch 043 - train 0.39466 | val 0.40479
  Regression -> MSE: 0.000194, MAE: 0.008919, R²: 0.0797
  Directional -> Accuracy: 0.7500, MCC: 0.4991, F1: 0.7600

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41611 | val 1.01304
  Epoch 020 - train 0.41385 | val 1.01701
  Epoch 021 - train 0.41920 | val 1.01669
  Regression -> MSE: 0.000674, MAE: 0.020470, R²: -0.2037
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44523 | val 0.64322
  Epoch 020 - train 0.43044 | val 0.63080
  Epoch 021 - train 0.43964 | val 0.63047
  Regression -> MSE: 0.000256, MAE: 0.012355, R²: -0.0041
  Directional -> Accuracy: 0.4091, MCC: -0.0687, F1: 0.5412

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.42295 | val 0.63806
  Epoch 020 - train 0.43036 | val 0.78949
  Epoch 021 - train 0.43694 | val 0.79377
  Regression -> MSE: 0.000631, MAE: 0.019633, R²: -0.0893
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.43564 | val 0.64963
  Epoch 020 - train 0.42354 | val 0.65361
  Epoch 028 - train 0.42199 | val 0.65458
  Regression -> MSE: 0.000377, MAE: 0.015741, R²: 0.0124
  Directional -> Accuracy: 0.4130, MCC: -0.1164, F1: 0.5574

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.46168 | val 0.87803
  Epoch 020 - train 0.45918 | val 0.87024
  Epoch 021 - train 0.45531 | val 0.86995
  Regression -> MSE: 0.000257, MAE: 0.011842, R²: -0.0415
  Directional -> Accuracy: 0.5821, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41159 | val 1.28308
  Epoch 020 - train 0.40912 | val 1.28596
  Epoch 021 - train 0.40036 | val 1.28561
  Regression -> MSE: 0.000334, MAE: 0.014325, R²: -0.0698
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43869 | val 0.58195
  Epoch 020 - train 0.43781 | val 0.58180
  Epoch 021 - train 0.43763 | val 0.58181
  Regression -> MSE: 0.000690, MAE: 0.019635, R²: 0.0078
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46167 | val 0.74565
  Epoch 020 - train 0.45351 | val 0.88199
  Epoch 021 - train 0.45505 | val 0.88273
  Regression -> MSE: 0.000144, MAE: 0.009436, R²: 0.0039
  Directional -> Accuracy: 0.5625, MCC: 0.2892, F1: 0.6866

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39176 | val 0.75860
  Epoch 020 - train 0.39325 | val 0.75522
  Epoch 021 - train 0.38764 | val 0.75507
  Regression -> MSE: 0.000248, MAE: 0.011355, R²: -0.0822
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46656 | val 1.58239
  Epoch 020 - train 0.45731 | val 1.56444
  Epoch 021 - train 0.46613 | val 1.56332
  Regression -> MSE: 0.000392, MAE: 0.016107, R²: -0.0497
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.45131 | val 0.46128
  Epoch 020 - train 0.44790 | val 0.45913
  Epoch 021 - train 0.43472 | val 0.45906
  Regression -> MSE: 0.000108, MAE: 0.007901, R²: 0.0120
  Directional -> Accuracy: 0.5970, MCC: 0.2122, F1: 0.7158

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.41363 | val 0.98228
  Epoch 020 - train 0.41411 | val 0.97909
  Epoch 021 - train 0.40384 | val 0.97899
  Regression -> MSE: 0.000153, MAE: 0.009882, R²: -0.0108
  Directional -> Accuracy: 0.5357, MCC: -0.0056, F1: 0.6389

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.47774 | val 0.51070
  Epoch 020 - train 0.46895 | val 0.51083
  Epoch 021 - train 0.46796 | val 0.51083
  Regression -> MSE: 0.000325, MAE: 0.014706, R²: -0.1737
  Directional -> Accuracy: 0.4110, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37444 | val 0.79950
  Epoch 020 - train 0.37315 | val 0.78478
  Epoch 021 - train 0.36778 | val 0.78437
  Regression -> MSE: 0.000171, MAE: 0.009356, R²: -0.1072
  Directional -> Accuracy: 0.4677, MCC: -0.1748, F1: 0.6024

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48967 | val 0.97204
  Epoch 020 - train 0.48770 | val 0.95007
  Epoch 021 - train 0.48149 | val 0.94953
  Regression -> MSE: 0.000229, MAE: 0.010912, R²: -0.0066
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45283 | val 0.71652
  Epoch 020 - train 0.44408 | val 0.72653
  Epoch 021 - train 0.44672 | val 0.72652
  Regression -> MSE: 0.000149, MAE: 0.008405, R²: -0.0063
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.42038 | val 0.56653
  Epoch 020 - train 0.41492 | val 0.56606
  Epoch 021 - train 0.41277 | val 0.56606
  Regression -> MSE: 0.000173, MAE: 0.010960, R²: -0.0148
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.47483 | val 0.62325
  Epoch 020 - train 0.47024 | val 0.62402
  Epoch 021 - train 0.45667 | val 0.62407
  Regression -> MSE: 0.000087, MAE: 0.007142, R²: 0.0222
  Directional -> Accuracy: 0.5818, MCC: 0.0000, F1: 0.7356

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.41100 | val 0.73072
  Epoch 020 - train 0.41445 | val 0.71930
  Epoch 021 - train 0.41705 | val 0.71891
  Regression -> MSE: 0.000215, MAE: 0.011399, R²: 0.0069
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39558 | val 0.46206
  Epoch 020 - train 0.39011 | val 0.45786
  Epoch 021 - train 0.39357 | val 0.45769
  Regression -> MSE: 0.000087, MAE: 0.007806, R²: 0.0379
  Directional -> Accuracy: 0.5472, MCC: 0.0000, F1: 0.7073

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44553 | val 0.49478
  Epoch 020 - train 0.42806 | val 0.48261
  Epoch 030 - train 0.42582 | val 0.47671
  Epoch 040 - train 0.42160 | val 0.47341
  Epoch 050 - train 0.41077 | val 0.47273
  Regression -> MSE: 0.000128, MAE: 0.009304, R²: -0.3934
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.46991 | val 0.35054
  Epoch 020 - train 0.47050 | val 0.33998
  Epoch 021 - train 0.46825 | val 0.33952
  Regression -> MSE: 0.000278, MAE: 0.013119, R²: 0.0017
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.42582 | val 0.62357
  Epoch 020 - train 0.41489 | val 0.62418
  Epoch 021 - train 0.42088 | val 0.62410
  Regression -> MSE: 0.000194, MAE: 0.008225, R²: -0.1285
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42076 | val 0.96684
  Epoch 020 - train 0.40831 | val 0.96579
  Epoch 030 - train 0.41205 | val 0.96661
  Epoch 033 - train 0.40923 | val 0.96673
  Regression -> MSE: 0.000246, MAE: 0.010496, R²: -0.0291
  Directional -> Accuracy: 0.4500, MCC: -0.1091, F1: 0.5417

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.45018 | val 0.59383
  Epoch 020 - train 0.44211 | val 0.64139
  Epoch 021 - train 0.45438 | val 0.64166
  Regression -> MSE: 0.000139, MAE: 0.008395, R²: 0.0233
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43702 | val 0.66922
  Epoch 020 - train 0.43044 | val 0.66812
  Epoch 021 - train 0.42359 | val 0.66797
  Regression -> MSE: 0.000196, MAE: 0.010626, R²: -0.0301
  Directional -> Accuracy: 0.3191, MCC: -0.3826, F1: 0.4074

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37110 | val 0.75198
  Epoch 020 - train 0.36096 | val 0.73738
  Epoch 021 - train 0.36355 | val 0.73696
  Regression -> MSE: 0.000268, MAE: 0.010703, R²: -0.0080
  Directional -> Accuracy: 0.5571, MCC: 0.0000, F1: 0.7156

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38811 | val 0.48818
  Epoch 020 - train 0.39192 | val 0.49616
  Epoch 021 - train 0.38511 | val 0.49618
  Regression -> MSE: 0.000217, MAE: 0.011221, R²: -0.0390
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41198 | val 0.44592
  Epoch 020 - train 0.40678 | val 0.44589
  Epoch 021 - train 0.40541 | val 0.44586
  Regression -> MSE: 0.000358, MAE: 0.012474, R²: -0.0013
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.44656 | val 0.27427
  Epoch 020 - train 0.44504 | val 0.28229
  Epoch 029 - train 0.42190 | val 0.28324
  Regression -> MSE: 0.000122, MAE: 0.008256, R²: -0.2558
  Directional -> Accuracy: 0.4898, MCC: -0.0379, F1: 0.2857

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42888 | val 1.05031
  Epoch 020 - train 0.43331 | val 1.05552
  Epoch 021 - train 0.43201 | val 1.05526
  Regression -> MSE: 0.000223, MAE: 0.011501, R²: -0.0269
  Directional -> Accuracy: 0.4815, MCC: 0.0403, F1: 0.6216

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44689 | val 1.12184
  Epoch 020 - train 0.44782 | val 1.11752
  Epoch 021 - train 0.44121 | val 1.11745
  Regression -> MSE: 0.000088, MAE: 0.007236, R²: -0.2324
  Directional -> Accuracy: 0.3864, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45896 | val 0.28865
  Epoch 020 - train 0.44542 | val 0.29215
  Epoch 021 - train 0.45392 | val 0.29213
  Regression -> MSE: 0.000299, MAE: 0.012994, R²: -0.0021
  Directional -> Accuracy: 0.6667, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40273 | val 0.68743
  Epoch 020 - train 0.40199 | val 0.68949
  Epoch 021 - train 0.40050 | val 0.68954
  Regression -> MSE: 0.000077, MAE: 0.006892, R²: 0.0146
  Directional -> Accuracy: 0.5556, MCC: 0.1179, F1: 0.6190

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.44069 | val 0.71566
  Epoch 020 - train 0.44116 | val 0.71965
  Epoch 021 - train 0.44444 | val 0.71959
  Regression -> MSE: 0.000284, MAE: 0.013981, R²: -0.0043
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.44600 | val 0.41124
  Epoch 020 - train 0.43704 | val 0.42478
  Epoch 021 - train 0.44577 | val 0.42527
  Regression -> MSE: 0.000109, MAE: 0.007674, R²: -0.0021
  Directional -> Accuracy: 0.5897, MCC: 0.0000, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.49223 | val 0.66919
  Epoch 020 - train 0.48839 | val 0.68081
  Epoch 024 - train 0.49235 | val 0.68106
  Regression -> MSE: 0.000196, MAE: 0.009896, R²: -0.0744
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.37973 | val 0.56011
  Epoch 020 - train 0.37485 | val 0.56387
  Epoch 021 - train 0.37666 | val 0.56392
  Regression -> MSE: 0.000232, MAE: 0.011967, R²: -0.0029
  Directional -> Accuracy: 0.5472, MCC: 0.0000, F1: 0.7073

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.40851 | val 0.64020
  Epoch 020 - train 0.39661 | val 0.63837
  Epoch 029 - train 0.39735 | val 0.64379
  Regression -> MSE: 0.000098, MAE: 0.007897, R²: -0.1168
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.44933 | val 1.02482
  Epoch 020 - train 0.45110 | val 1.02250
  Epoch 021 - train 0.45825 | val 1.02211
  Regression -> MSE: 0.000172, MAE: 0.010597, R²: -0.0148
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41000 | val 0.71087

[I 2026-02-23 23:03:06,188] Trial 19 finished with value: -0.011616429368708953 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 2.0527878951989088e-05, 'weight_decay': 3.4691881928619707e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 1.2605984033488435, 'early_stopping_min_delta': 0.005480058028981291}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 020 - train 0.42674 | val 0.91730
  Epoch 021 - train 0.41305 | val 0.91720
  Regression -> MSE: 0.000251, MAE: 0.012792, R²: -0.0124
  Directional -> Accuracy: 0.4138, MCC: -0.1587, F1: 0.4848

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.27919 | val 0.83670
  Epoch 017 - train 0.20176 | val 0.88769
  Regression -> MSE: 0.000254, MAE: 0.012631, R²: -0.0615
  Directional -> Accuracy: 0.4933, MCC: 0.0632, F1: 0.6042

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.28275 | val 0.50233
  Epoch 015 - train 0.23666 | val 0.54512
  Regression -> MSE: 0.000696, MAE: 0.019645, R²: 0.0125
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.29563 | val 1.05487
  Epoch 011 - train 0.32354 | val 1.04842
  Regression -> MSE: 0.000326, MAE: 0.014812, R²: -0.0149
  Directional -> Accuracy: 0.5111, MCC: 0.2017, F1: 0.1538

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.26613 | val 0.49074
  Epoch 011 - train 0.26472 | val 0.50798
  Regression -> MSE: 0.000369, MAE: 0.014878, R²: -0.0365
  Directional -> Accuracy: 0.4658, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.31410 | val 0.41885
  Epoch 020 - train 0.19673 | val 0.41413
  Regression -> MSE: 0.000201, MAE: 0.009977, R²: 0.0433
  Directional -> Accuracy: 0.5714, MCC: 0.1435, F1: 0.6316

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.24251 | val 0.96016
  Epoch 020 - train 0.15537 | val 1.08667
  Regression -> MSE: 0.000617, MAE: 0.019252, R²: -0.0737
  Directional -> Accuracy: 0.4889, MCC: -0.1474, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.31029 | val 0.67645
  Epoch 016 - train 0.21915 | val 0.71135
  Regression -> MSE: 0.000259, MAE: 0.012062, R²: -0.0287
  Directional -> Accuracy: 0.5224, MCC: -0.1177, F1: 0.1579

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.22792 | val 0.43015
  Epoch 011 - train 0.23532 | val 0.44942
  Regression -> MSE: 0.000648, MAE: 0.020146, R²: -0.0353
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.24800 | val 0.78436
  Epoch 011 - train 0.21778 | val 0.80544
  Regression -> MSE: 0.000374, MAE: 0.015912, R²: 0.0006
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.28524 | val 0.80792
  Epoch 011 - train 0.25291 | val 0.83624
  Regression -> MSE: 0.000249, MAE: 0.011944, R²: -0.0040
  Directional -> Accuracy: 0.5441, MCC: 0.0640, F1: 0.4561

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.27676 | val 0.93586
  Epoch 011 - train 0.26662 | val 0.94733
  Regression -> MSE: 0.000315, MAE: 0.013766, R²: -0.0050
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.6286

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.29494 | val 0.76685
  Epoch 011 - train 0.28460 | val 0.81304
  Regression -> MSE: 0.000698, MAE: 0.019831, R²: -0.0002
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.29101 | val 0.58736
  Epoch 011 - train 0.27750 | val 0.61452
  Regression -> MSE: 0.000145, MAE: 0.009467, R²: -0.0213
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.27282 | val 0.73825
  Epoch 017 - train 0.19975 | val 0.72860
  Regression -> MSE: 0.000227, MAE: 0.010657, R²: 0.0068
  Directional -> Accuracy: 0.5424, MCC: 0.0936, F1: 0.4706

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.29124 | val 1.51379
  Epoch 011 - train 0.25899 | val 1.54011
  Regression -> MSE: 0.000368, MAE: 0.016123, R²: -0.0032
  Directional -> Accuracy: 0.4400, MCC: 0.0000, F1: 0.6111

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.30945 | val 0.72723
  Epoch 011 - train 0.28884 | val 0.77706
  Regression -> MSE: 0.000109, MAE: 0.007869, R²: -0.0075
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.26213 | val 1.26472
  Epoch 011 - train 0.25346 | val 1.29339
  Regression -> MSE: 0.000150, MAE: 0.009775, R²: -0.0079
  Directional -> Accuracy: 0.5965, MCC: 0.1861, F1: 0.6462

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.30042 | val 0.68128
  Epoch 011 - train 0.28191 | val 0.85514
  Regression -> MSE: 0.000277, MAE: 0.013051, R²: -0.0003
  Directional -> Accuracy: 0.5946, MCC: 0.0000, F1: 0.7458

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.24364 | val 0.70292
  Epoch 019 - train 0.16942 | val 0.78035
  Regression -> MSE: 0.000192, MAE: 0.009896, R²: -0.2620
  Directional -> Accuracy: 0.3968, MCC: -0.1185, F1: 0.1739

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.31573 | val 1.09490
  Epoch 011 - train 0.30459 | val 1.11418
  Regression -> MSE: 0.000229, MAE: 0.010789, R²: -0.0203
  Directional -> Accuracy: 0.5479, MCC: 0.0000, F1: 0.7080

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.29798 | val 0.81439
  Epoch 011 - train 0.28780 | val 0.82512
  Regression -> MSE: 0.000148, MAE: 0.008451, R²: -0.0074
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.28439 | val 0.63070
  Epoch 011 - train 0.26693 | val 0.64894
  Regression -> MSE: 0.000170, MAE: 0.010409, R²: -0.0078
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.28532 | val 0.68177
  Epoch 013 - train 0.22939 | val 0.74004
  Regression -> MSE: 0.000089, MAE: 0.007260, R²: -0.0132
  Directional -> Accuracy: 0.5714, MCC: 0.1794, F1: 0.5556

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.27405 | val 0.87818
  Epoch 011 - train 0.29534 | val 0.94181
  Regression -> MSE: 0.000216, MAE: 0.010930, R²: -0.0136
  Directional -> Accuracy: 0.5312, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.25826 | val 0.39365
  Epoch 015 - train 0.20485 | val 0.43598
  Regression -> MSE: 0.000095, MAE: 0.008029, R²: -0.0406
  Directional -> Accuracy: 0.5370, MCC: 0.0482, F1: 0.6269

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28646 | val 0.41383
  Epoch 020 - train 0.15488 | val 0.39015
  Regression -> MSE: 0.000126, MAE: 0.009182, R²: -0.3122
  Directional -> Accuracy: 0.5116, MCC: 0.2057, F1: 0.6182

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.26010 | val 0.25074
  Epoch 020 - train 0.15859 | val 0.28793
  Regression -> MSE: 0.000301, MAE: 0.013704, R²: -0.1032
  Directional -> Accuracy: 0.4898, MCC: -0.0323, F1: 0.5455

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.27942 | val 0.72577
  Epoch 011 - train 0.25944 | val 0.74743
  Regression -> MSE: 0.000176, MAE: 0.007754, R²: -0.0362
  Directional -> Accuracy: 0.6000, MCC: 0.1845, F1: 0.6562

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.24341 | val 0.35723
  Epoch 011 - train 0.22374 | val 0.34924
  Regression -> MSE: 0.000252, MAE: 0.012459, R²: -0.0030
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.29338 | val 1.23630
  Epoch 011 - train 0.26203 | val 1.24515
  Regression -> MSE: 0.000233, MAE: 0.009886, R²: 0.0014
  Directional -> Accuracy: 0.3902, MCC: -0.2583, F1: 0.5283

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.24573 | val 0.73952
  Epoch 011 - train 0.23418 | val 0.76125
  Regression -> MSE: 0.000142, MAE: 0.008399, R²: -0.0208
  Directional -> Accuracy: 0.4878, MCC: 0.0025, F1: 0.4615

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.27275 | val 0.70359
  Epoch 020 - train 0.16499 | val 0.70326
  Regression -> MSE: 0.000195, MAE: 0.010674, R²: -0.0473
  Directional -> Accuracy: 0.4792, MCC: -0.0493, F1: 0.5283

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.25596 | val 0.66768
  Epoch 011 - train 0.23644 | val 0.67336
  Regression -> MSE: 0.000277, MAE: 0.010747, R²: -0.0369
  Directional -> Accuracy: 0.5352, MCC: 0.1350, F1: 0.4590

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.24059 | val 0.59541
  Epoch 011 - train 0.20506 | val 0.59687
  Regression -> MSE: 0.000190, MAE: 0.010807, R²: -0.0131
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.30542 | val 0.45414
  Epoch 011 - train 0.27688 | val 0.45739
  Regression -> MSE: 0.000347, MAE: 0.011891, R²: 0.0148
  Directional -> Accuracy: 0.6154, MCC: 0.1923, F1: 0.6988

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.24572 | val 0.29296
  Epoch 015 - train 0.18550 | val 0.32661
  Regression -> MSE: 0.000141, MAE: 0.008932, R²: -0.2823
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.28058 | val 0.86589
  Epoch 017 - train 0.18491 | val 0.93511
  Regression -> MSE: 0.000236, MAE: 0.011750, R²: -0.0575
  Directional -> Accuracy: 0.5273, MCC: 0.1286, F1: 0.6176

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.27476 | val 1.26756
  Epoch 011 - train 0.27438 | val 1.28382
  Regression -> MSE: 0.000073, MAE: 0.006619, R²: -0.0380
  Directional -> Accuracy: 0.6222, MCC: 0.0000, F1: 0.7671

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.25412 | val 0.24597
  Epoch 011 - train 0.24630 | val 0.24626
  Regression -> MSE: 0.000339, MAE: 0.015163, R²: -0.0647
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.24633 | val 0.92421
  Epoch 011 - train 0.24345 | val 1.00419
  Regression -> MSE: 0.000079, MAE: 0.006817, R²: -0.0263
  Directional -> Accuracy: 0.5205, MCC: 0.1195, F1: 0.0541

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.26476 | val 0.77414
  Epoch 014 - train 0.24537 | val 0.83742
  Regression -> MSE: 0.000279, MAE: 0.013881, R²: -0.0031
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.28456 | val 0.54968
  Epoch 011 - train 0.25339 | val 0.55021
  Regression -> MSE: 0.000104, MAE: 0.007399, R²: -0.0030
  Directional -> Accuracy: 0.5854, MCC: 0.0392, F1: 0.7302

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.34203 | val 0.77974
  Epoch 011 - train 0.33428 | val 0.78335
  Regression -> MSE: 0.000179, MAE: 0.009727, R²: -0.0025
  Directional -> Accuracy: 0.6304, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.25304 | val 0.61242
  Epoch 011 - train 0.22454 | val 0.61268
  Regression -> MSE: 0.000239, MAE: 0.012104, R²: -0.0523
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.29112 | val 0.97178
  Epoch 011 - train 0.28798 | val 1.03827
  Regression -> MSE: 0.000091, MAE: 0.007781, R²: -0.0402
  Directional -> Accuracy: 0.4909, MCC: 0.0000, F1: 0.6585

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.29388 | val 1.06308
  Epoch 011 - train 0.24751 | val 1.07988
  Regression -> MSE: 0.000167, MAE: 0.010339, R²: 0.0019
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.28144 | val 0.83704
  Epoch 011 - train 0.26647 | val 0.86272
  Regression -> MSE: 0.000120, MAE: 0.009133, R²: 0.0030
  Directional -> Accuracy: 0.5370, MCC: 0.0899, F1: 0.6835

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 23:03:44,485] Trial 20 finished with value: -0.011566257521266969 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 0.0007824293951101179, 'weight_decay': 3.3288515444557354e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.780172171657844, 'early_stopping_min_delta': 0.007697971015901104}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.29986 | val 1.04915
  Epoch 011 - train 0.29533 | val 1.05747
  Regression -> MSE: 0.000245, MAE: 0.012473, R²: -0.0045
  Directional -> Accuracy: 0.5254, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.36324 | val 0.54247
  Epoch 011 - train 0.35957 | val 0.54653
  Regression -> MSE: 0.000240, MAE: 0.012242, R²: 0.0016
  Directional -> Accuracy: 0.5658, MCC: 0.0886, F1: 0.3529

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.34797 | val 0.37040
  Epoch 011 - train 0.33424 | val 0.37323
  Regression -> MSE: 0.000703, MAE: 0.019556, R²: -0.0070
  Directional -> Accuracy: 0.6000, MCC: 0.1273, F1: 0.7273

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.37387 | val 0.68042
  Epoch 011 - train 0.36754 | val 0.68389
  Regression -> MSE: 0.000317, MAE: 0.014564, R²: -0.0082
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.39336 | val 0.63284
  Epoch 011 - train 0.38461 | val 0.66291
  Regression -> MSE: 0.000379, MAE: 0.015169, R²: -0.0736
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40068 | val 0.38384
  Epoch 011 - train 0.41205 | val 0.38827
  Regression -> MSE: 0.000211, MAE: 0.010339, R²: -0.0252
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35745 | val 0.70915
  Epoch 017 - train 0.33663 | val 0.72207
  Regression -> MSE: 0.000568, MAE: 0.018441, R²: -0.0034
  Directional -> Accuracy: 0.5000, MCC: -0.0038, F1: 0.4651

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.37664 | val 0.49546
  Epoch 011 - train 0.37642 | val 0.50018
  Regression -> MSE: 0.000248, MAE: 0.011917, R²: -0.0018
  Directional -> Accuracy: 0.5147, MCC: -0.0333, F1: 0.3529

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39384 | val 0.36808
  Epoch 011 - train 0.36065 | val 0.36821
  Regression -> MSE: 0.000663, MAE: 0.020357, R²: -0.0848
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.36966 | val 0.45812
  Epoch 011 - train 0.36425 | val 0.45862
  Regression -> MSE: 0.000392, MAE: 0.015813, R²: -0.0498
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.35289 | val 0.52365
  Epoch 011 - train 0.34506 | val 0.52992
  Regression -> MSE: 0.000249, MAE: 0.011798, R²: -0.0155
  Directional -> Accuracy: 0.5797, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.33948 | val 0.57674
  Epoch 011 - train 0.33981 | val 0.58184
  Regression -> MSE: 0.000320, MAE: 0.013507, R²: -0.0260
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.37844 | val 0.43213
  Epoch 019 - train 0.38553 | val 0.45185
  Regression -> MSE: 0.000686, MAE: 0.019578, R²: 0.0003
  Directional -> Accuracy: 0.5614, MCC: 0.1216, F1: 0.5902

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37847 | val 0.38633
  Epoch 011 - train 0.38326 | val 0.38569
  Regression -> MSE: 0.000140, MAE: 0.009244, R²: -0.0177
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.32917 | val 0.51328
  Epoch 011 - train 0.31759 | val 0.51587
  Regression -> MSE: 0.000229, MAE: 0.010765, R²: -0.0102
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.35178 | val 0.87053
  Epoch 011 - train 0.34706 | val 0.87133
  Regression -> MSE: 0.000367, MAE: 0.016139, R²: -0.0020
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.37968 | val 0.36667
  Epoch 014 - train 0.36545 | val 0.37385
  Regression -> MSE: 0.000105, MAE: 0.007879, R²: 0.0237
  Directional -> Accuracy: 0.5507, MCC: 0.0850, F1: 0.6173

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38287 | val 0.67858
  Epoch 011 - train 0.37324 | val 0.68451
  Regression -> MSE: 0.000170, MAE: 0.010480, R²: -0.0788
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.35916 | val 0.40665
  Epoch 011 - train 0.36693 | val 0.42078
  Regression -> MSE: 0.000273, MAE: 0.012912, R²: 0.0021
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.34475 | val 0.64729
  Epoch 011 - train 0.35852 | val 0.66671
  Regression -> MSE: 0.000151, MAE: 0.009087, R²: 0.0073
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.40975 | val 0.61831
  Epoch 011 - train 0.40584 | val 0.61809
  Regression -> MSE: 0.000251, MAE: 0.011297, R²: -0.1030
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.38639 | val 0.55132
  Epoch 011 - train 0.40937 | val 0.56535
  Regression -> MSE: 0.000146, MAE: 0.008390, R²: -0.0144
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.35144 | val 0.42969
  Epoch 016 - train 0.34288 | val 0.43097
  Regression -> MSE: 0.000181, MAE: 0.010568, R²: -0.0946
  Directional -> Accuracy: 0.4154, MCC: -0.1910, F1: 0.2083

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.38061 | val 0.44595
  Epoch 011 - train 0.38843 | val 0.44589
  Regression -> MSE: 0.000088, MAE: 0.007248, R²: -0.0189
  Directional -> Accuracy: 0.5789, MCC: 0.1083, F1: 0.7209

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.39912 | val 0.93164
  Epoch 011 - train 0.39396 | val 1.01677
  Regression -> MSE: 0.000216, MAE: 0.011466, R²: -0.0231
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.38534 | val 0.34278
  Epoch 011 - train 0.37774 | val 0.34355
  Regression -> MSE: 0.000090, MAE: 0.007987, R²: -0.0033
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.35404 | val 0.33749
  Epoch 011 - train 0.36798 | val 0.33868
  Regression -> MSE: 0.000118, MAE: 0.009240, R²: -0.1843
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.38401 | val 0.34437
  Epoch 011 - train 0.40106 | val 0.34511
  Regression -> MSE: 0.000237, MAE: 0.012812, R²: -0.0026
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.34875 | val 0.44196
  Epoch 016 - train 0.33445 | val 0.45531
  Regression -> MSE: 0.000177, MAE: 0.007847, R²: -0.0465
  Directional -> Accuracy: 0.6071, MCC: 0.1883, F1: 0.6857

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.37483 | val 0.28817
  Epoch 011 - train 0.37722 | val 0.28966
  Regression -> MSE: 0.000242, MAE: 0.012135, R²: 0.0019
  Directional -> Accuracy: 0.5250, MCC: 0.0356, F1: 0.5778

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.37046 | val 0.67906
  Epoch 011 - train 0.36543 | val 0.68065
  Regression -> MSE: 0.000234, MAE: 0.010063, R²: 0.0080
  Directional -> Accuracy: 0.5238, MCC: 0.0754, F1: 0.6000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43253 | val 0.42029
  Epoch 011 - train 0.44267 | val 0.42648
  Regression -> MSE: 0.000138, MAE: 0.008292, R²: -0.0030
  Directional -> Accuracy: 0.5476, MCC: 0.0214, F1: 0.6984

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42040 | val 0.54631
  Epoch 011 - train 0.40089 | val 0.54964
  Regression -> MSE: 0.000184, MAE: 0.010317, R²: -0.0052
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.32550 | val 0.44175
  Epoch 011 - train 0.32885 | val 0.44230
  Regression -> MSE: 0.000276, MAE: 0.010813, R²: -0.0388
  Directional -> Accuracy: 0.4167, MCC: -0.1617, F1: 0.4324

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.32955 | val 0.41544
  Epoch 011 - train 0.33533 | val 0.41913
  Regression -> MSE: 0.000185, MAE: 0.010479, R²: -0.0107
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.35048 | val 0.37816
  Epoch 011 - train 0.35984 | val 0.38157
  Regression -> MSE: 0.000348, MAE: 0.012154, R²: -0.0001
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.37811 | val 0.21670
  Epoch 011 - train 0.38159 | val 0.21637
  Regression -> MSE: 0.000131, MAE: 0.008688, R²: -0.2418
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.36099 | val 0.55040
  Epoch 011 - train 0.35984 | val 0.55263
  Regression -> MSE: 0.000221, MAE: 0.011358, R²: -0.0069
  Directional -> Accuracy: 0.5179, MCC: -0.1255, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.39125 | val 0.77044
  Epoch 011 - train 0.39834 | val 0.77642
  Regression -> MSE: 0.000079, MAE: 0.006936, R²: -0.0708
  Directional -> Accuracy: 0.5000, MCC: -0.0393, F1: 0.5818

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.36672 | val 0.26528
  Epoch 011 - train 0.36729 | val 0.26557
  Regression -> MSE: 0.000361, MAE: 0.016088, R²: -0.1590
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.34923 | val 0.46196
  Epoch 020 - train 0.35650 | val 0.45637
  Regression -> MSE: 0.000079, MAE: 0.007050, R²: -0.0129
  Directional -> Accuracy: 0.4865, MCC: -0.0045, F1: 0.6481

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.35735 | val 0.48825
  Epoch 020 - train 0.36304 | val 0.47582
  Regression -> MSE: 0.000293, MAE: 0.014205, R²: 0.0248
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40515 | val 0.47936
  Epoch 011 - train 0.39763 | val 0.47970
  Regression -> MSE: 0.000110, MAE: 0.007261, R²: -0.0857
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44540 | val 0.50072
  Epoch 011 - train 0.43318 | val 0.50090
  Regression -> MSE: 0.000184, MAE: 0.009596, R²: -0.0475
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.35811 | val 0.47144
  Epoch 011 - train 0.35041 | val 0.48795
  Regression -> MSE: 0.000229, MAE: 0.011942, R²: -0.0164
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.35424 | val 0.47945
  Epoch 011 - train 0.36015 | val 0.48616
  Regression -> MSE: 0.000096, MAE: 0.007906, R²: -0.0201
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.41341 | val 0.63879
  Epoch 011 - train 0.40876 | val 0.63795
  Regression -> MSE: 0.000169, MAE: 0.010431, R²: -0.0129
  Directional -> Accuracy: 0.4906, MCC: -0.0054, F1: 0.1290

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.36666 | val 0.46446
  Epoch 020 - train 0.36290 | val 0.45101
  Regression -> MSE: 0.000205, MAE: 0.011455, R²: -0.7444
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 23:04:36,123] Trial 21 finished with value: -0.011590892908066154 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 2.032434627589634e-06, 'weight_decay': 8.552553858402022e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.7864029250721392, 'early_stopping_min_delta': 0.005223102136996808}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.38287 | val 0.64281
  Epoch 011 - train 0.36895 | val 0.65599
  Regression -> MSE: 0.000246, MAE: 0.012552, R²: -0.0220
  Directional -> Accuracy: 0.4667, MCC: -0.1039, F1: 0.2381

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.24304 | val 0.33373
  Epoch 016 - train 0.24486 | val 0.37064
  Regression -> MSE: 0.000253, MAE: 0.012836, R²: -0.0215
  Directional -> Accuracy: 0.4286, MCC: -0.1111, F1: 0.5600

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.25204 | val 0.30145
  Epoch 011 - train 0.25818 | val 0.31605
  Regression -> MSE: 0.000709, MAE: 0.019748, R²: -0.0355
  Directional -> Accuracy: 0.4565, MCC: -0.2495, F1: 0.6154

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.24569 | val 0.42470
  Epoch 011 - train 0.25623 | val 0.42599
  Regression -> MSE: 0.000312, MAE: 0.014500, R²: -0.0065
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.21413 | val 0.35456
  Epoch 011 - train 0.21323 | val 0.37428
  Regression -> MSE: 0.000447, MAE: 0.016759, R²: -0.2799
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.24899 | val 0.26223
  Epoch 011 - train 0.25668 | val 0.26610
  Regression -> MSE: 0.000201, MAE: 0.010130, R²: 0.0106
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.23227 | val 0.50660
  Epoch 011 - train 0.22814 | val 0.51252
  Regression -> MSE: 0.000566, MAE: 0.018262, R²: -0.0192
  Directional -> Accuracy: 0.4894, MCC: -0.1443, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.25195 | val 0.34738
  Epoch 011 - train 0.25020 | val 0.35215
  Regression -> MSE: 0.000247, MAE: 0.012156, R²: -0.0060
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.26001 | val 0.36038
  Epoch 011 - train 0.25242 | val 0.36272
  Regression -> MSE: 0.000640, MAE: 0.020068, R²: -0.0706
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.23365 | val 0.31104
  Epoch 011 - train 0.23397 | val 0.31211
  Regression -> MSE: 0.000385, MAE: 0.016177, R²: -0.0025
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.23988 | val 0.32135
  Epoch 011 - train 0.23606 | val 0.32216
  Regression -> MSE: 0.000245, MAE: 0.011626, R²: -0.0137
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.21174 | val 0.38687
  Epoch 011 - train 0.22091 | val 0.39130
  Regression -> MSE: 0.000312, MAE: 0.013726, R²: -0.0042
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.25257 | val 0.30528
  Epoch 011 - train 0.24989 | val 0.31105
  Regression -> MSE: 0.000672, MAE: 0.019401, R²: 0.0080
  Directional -> Accuracy: 0.6034, MCC: 0.2132, F1: 0.5490

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.23912 | val 0.27549
  Epoch 011 - train 0.24034 | val 0.28144
  Regression -> MSE: 0.000138, MAE: 0.009098, R²: 0.0009
  Directional -> Accuracy: 0.4651, MCC: -0.1036, F1: 0.3429

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.21410 | val 0.35212
  Epoch 011 - train 0.22192 | val 0.35673
  Regression -> MSE: 0.000227, MAE: 0.010725, R²: -0.0072
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.24998 | val 0.53642
  Epoch 011 - train 0.23976 | val 0.53999
  Regression -> MSE: 0.000365, MAE: 0.016030, R²: -0.0083
  Directional -> Accuracy: 0.4615, MCC: -0.0901, F1: 0.3913

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.26431 | val 0.25344
  Epoch 011 - train 0.26741 | val 0.25520
  Regression -> MSE: 0.000108, MAE: 0.007930, R²: -0.0048
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.23400 | val 0.45255
  Epoch 011 - train 0.23104 | val 0.46449
  Regression -> MSE: 0.000159, MAE: 0.010024, R²: -0.0185
  Directional -> Accuracy: 0.6271, MCC: 0.2862, F1: 0.6562

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.25752 | val 0.26497
  Epoch 011 - train 0.24804 | val 0.26929
  Regression -> MSE: 0.000285, MAE: 0.013616, R²: -0.0458
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.21616 | val 0.33877
  Epoch 011 - train 0.21594 | val 0.33967
  Regression -> MSE: 0.000167, MAE: 0.009126, R²: -0.1186
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.25114 | val 0.36335
  Epoch 011 - train 0.24582 | val 0.36511
  Regression -> MSE: 0.000227, MAE: 0.010908, R²: -0.0037
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.24023 | val 0.31014
  Epoch 011 - train 0.23891 | val 0.31148
  Regression -> MSE: 0.000150, MAE: 0.008658, R²: -0.0487
  Directional -> Accuracy: 0.5833, MCC: 0.0913, F1: 0.6774

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.23277 | val 0.28524
  Epoch 011 - train 0.23777 | val 0.28513
  Regression -> MSE: 0.000170, MAE: 0.010266, R²: -0.0283
  Directional -> Accuracy: 0.4848, MCC: -0.1240, F1: 0.6531

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.27647 | val 0.32554
  Epoch 011 - train 0.26502 | val 0.32679
  Regression -> MSE: 0.000093, MAE: 0.007394, R²: -0.0901
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.24571 | val 0.34221
  Epoch 011 - train 0.25229 | val 0.34547
  Regression -> MSE: 0.000212, MAE: 0.011285, R²: -0.0024
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.22293 | val 0.21634
  Epoch 011 - train 0.23119 | val 0.21596
  Regression -> MSE: 0.000103, MAE: 0.008263, R²: -0.1139
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.24208 | val 0.19102
  Epoch 011 - train 0.24751 | val 0.19191
  Regression -> MSE: 0.000108, MAE: 0.008952, R²: -0.0496
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.25701 | val 0.23119
  Epoch 011 - train 0.26921 | val 0.23172
  Regression -> MSE: 0.000232, MAE: 0.012594, R²: -0.0002
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.23921 | val 0.30364
  Epoch 011 - train 0.22665 | val 0.30485
  Regression -> MSE: 0.000175, MAE: 0.007826, R²: -0.0517
  Directional -> Accuracy: 0.6140, MCC: 0.1990, F1: 0.7250

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.25657 | val 0.22607
  Epoch 011 - train 0.24965 | val 0.22809
  Regression -> MSE: 0.000241, MAE: 0.012015, R²: -0.0198
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.25650 | val 0.40761
  Epoch 020 - train 0.26285 | val 0.40261
  Regression -> MSE: 0.000235, MAE: 0.010304, R²: -0.0209
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.24437 | val 0.28948
  Epoch 011 - train 0.24124 | val 0.29030
  Regression -> MSE: 0.000138, MAE: 0.008200, R²: -0.0200
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.26450 | val 0.32258
  Epoch 011 - train 0.25393 | val 0.32546
  Regression -> MSE: 0.000200, MAE: 0.010693, R²: -0.0606
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.22098 | val 0.27450
  Epoch 011 - train 0.21734 | val 0.27519
  Regression -> MSE: 0.000285, MAE: 0.011126, R²: -0.0866
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.23308 | val 0.20334
  Epoch 011 - train 0.24640 | val 0.20371
  Regression -> MSE: 0.000168, MAE: 0.010365, R²: -0.0101
  Directional -> Accuracy: 0.5526, MCC: 0.1715, F1: 0.2609

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.22091 | val 0.25505
  Epoch 011 - train 0.23067 | val 0.25698
  Regression -> MSE: 0.000183, MAE: 0.010414, R²: -0.0179
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.23830 | val 0.25418
  Epoch 011 - train 0.24132 | val 0.25735
  Regression -> MSE: 0.000349, MAE: 0.012359, R²: -0.0182
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.25778 | val 0.14518
  Epoch 011 - train 0.26310 | val 0.14525
  Regression -> MSE: 0.000123, MAE: 0.008374, R²: -0.1718
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.25038 | val 0.35267
  Epoch 011 - train 0.25200 | val 0.35331
  Regression -> MSE: 0.000225, MAE: 0.011469, R²: -0.0289
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.25935 | val 0.50653
  Epoch 011 - train 0.26436 | val 0.51460
  Regression -> MSE: 0.000078, MAE: 0.006942, R²: -0.0026
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.24122 | val 0.19395
  Epoch 020 - train 0.24200 | val 0.18682
  Regression -> MSE: 0.000311, MAE: 0.013483, R²: -0.0114
  Directional -> Accuracy: 0.7143, MCC: 0.3913, F1: 0.3636

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.26631 | val 0.15406
  Epoch 011 - train 0.27390 | val 0.15486
  Regression -> MSE: 0.000261, MAE: 0.011525, R²: -0.0704
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.25085 | val 0.31511
  Epoch 011 - train 0.24920 | val 0.31648
  Regression -> MSE: 0.000082, MAE: 0.007153, R²: -0.0165
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.22862 | val 0.30244
  Epoch 020 - train 0.24084 | val 0.29296
  Regression -> MSE: 0.000356, MAE: 0.015550, R²: -0.1604
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.25210 | val 0.26227
  Epoch 011 - train 0.26362 | val 0.26287
  Regression -> MSE: 0.000099, MAE: 0.007310, R²: -0.0029
  Directional -> Accuracy: 0.4318, MCC: -0.0547, F1: 0.1935

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.27470 | val 0.32120
  Epoch 011 - train 0.27712 | val 0.32269
  Regression -> MSE: 0.000186, MAE: 0.010740, R²: -0.0835
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.21230 | val 0.28816
  Epoch 011 - train 0.21811 | val 0.28754
  Regression -> MSE: 0.000227, MAE: 0.011771, R²: -0.0179
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.24484 | val 0.27889
  Epoch 011 - train 0.24692 | val 0.28030
  Regression -> MSE: 0.000094, MAE: 0.007723, R²: -0.0182
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.28032 | val 0.40409
  Epoch 011 - train 0.28232 | val 0.40728
  Regression -> MSE: 0.000164, MAE: 0.010344, R²: -0.0034
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.24144 | val 0.31133
  Epoch 011 - train 0.23638 | val 0.31282
  Regression -> MSE: 0.000120, MAE: 0.009060, R²: -0.0382
  Directional -> Accuracy: 0.4286, MCC: -0.1427, F1: 0.2727

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 23:05:16,733] Trial 22 finished with value: -0.011547887115246194 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 3.896373725480764e-06, 'weight_decay': 4.047383849924139e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.42310008649132663, 'early_stopping_min_delta': 0.0038935724059331427}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.24145 | val 0.36749
  Epoch 011 - train 0.25122 | val 0.36873
  Regression -> MSE: 0.000248, MAE: 0.012393, R²: -0.0474
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.34902 | val 0.73100
  Epoch 011 - train 0.34968 | val 0.77722
  Regression -> MSE: 0.000266, MAE: 0.013089, R²: -0.1050
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.33977 | val 0.30782
  Epoch 016 - train 0.34022 | val 0.31763
  Regression -> MSE: 0.000693, MAE: 0.019439, R²: 0.0071
  Directional -> Accuracy: 0.6222, MCC: 0.1909, F1: 0.7302

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.36028 | val 0.61117
  Epoch 011 - train 0.37617 | val 0.61490
  Regression -> MSE: 0.000315, MAE: 0.014471, R²: -0.0013
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.30738 | val 0.37033
  Epoch 011 - train 0.30672 | val 0.37768
  Regression -> MSE: 0.000357, MAE: 0.014739, R²: -0.0115
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.34408 | val 0.33277
  Epoch 011 - train 0.35531 | val 0.33437
  Regression -> MSE: 0.000213, MAE: 0.010227, R²: -0.0324
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.35526 | val 0.63423
  Epoch 018 - train 0.34532 | val 0.71770
  Regression -> MSE: 0.000556, MAE: 0.018326, R²: 0.0178
  Directional -> Accuracy: 0.5217, MCC: 0.0349, F1: 0.4500

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.35477 | val 0.47471
  Epoch 011 - train 0.37166 | val 0.48383
  Regression -> MSE: 0.000256, MAE: 0.012104, R²: -0.0332
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.35390 | val 0.32014
  Epoch 011 - train 0.37942 | val 0.32325
  Regression -> MSE: 0.000626, MAE: 0.019732, R²: -0.0249
  Directional -> Accuracy: 0.4762, MCC: 0.1936, F1: 0.6207

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.38432 | val 0.41647
  Epoch 011 - train 0.34573 | val 0.41704
  Regression -> MSE: 0.000390, MAE: 0.015803, R²: -0.0456
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.36524 | val 0.96584
  Epoch 011 - train 0.36481 | val 1.05576
  Regression -> MSE: 0.000246, MAE: 0.011725, R²: -0.0057
  Directional -> Accuracy: 0.5507, MCC: -0.1471, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.33579 | val 0.51704
  Epoch 011 - train 0.33201 | val 0.51857
  Regression -> MSE: 0.000320, MAE: 0.013492, R²: -0.0241
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.37870 | val 0.42004
  Epoch 011 - train 0.37477 | val 0.42180
  Regression -> MSE: 0.000685, MAE: 0.019572, R²: 0.0010
  Directional -> Accuracy: 0.4912, MCC: -0.0048, F1: 0.1212

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.37333 | val 0.38505
  Epoch 011 - train 0.39084 | val 0.38468
  Regression -> MSE: 0.000139, MAE: 0.009003, R²: -0.0050
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.35404 | val 0.46041
  Epoch 011 - train 0.35976 | val 0.46120
  Regression -> MSE: 0.000227, MAE: 0.010683, R²: -0.0029
  Directional -> Accuracy: 0.4833, MCC: -0.0765, F1: 0.0606

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.36588 | val 0.83555
  Epoch 011 - train 0.37164 | val 0.84325
  Regression -> MSE: 0.000385, MAE: 0.015958, R²: -0.0500
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.38165 | val 0.40760
  Epoch 011 - train 0.38106 | val 0.41556
  Regression -> MSE: 0.000110, MAE: 0.007989, R²: -0.0162
  Directional -> Accuracy: 0.5072, MCC: -0.0645, F1: 0.6531

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.38301 | val 0.85175
  Epoch 011 - train 0.37110 | val 0.89782
  Regression -> MSE: 0.000166, MAE: 0.009687, R²: -0.0520
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.35462 | val 0.33739
  Epoch 011 - train 0.36510 | val 0.34062
  Regression -> MSE: 0.000274, MAE: 0.013085, R²: -0.0013
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.31863 | val 0.48745
  Epoch 011 - train 0.29947 | val 0.49022
  Regression -> MSE: 0.000182, MAE: 0.009700, R²: -0.1963
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.35981 | val 0.61888
  Epoch 011 - train 0.36320 | val 0.63116
  Regression -> MSE: 0.000238, MAE: 0.010983, R²: -0.0486
  Directional -> Accuracy: 0.4865, MCC: -0.0392, F1: 0.5366

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.36756 | val 0.45483
  Epoch 011 - train 0.36966 | val 0.45517
  Regression -> MSE: 0.000147, MAE: 0.008482, R²: -0.0178
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.32478 | val 0.48400
  Epoch 011 - train 0.33394 | val 0.49230
  Regression -> MSE: 0.000164, MAE: 0.010422, R²: 0.0078
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.37602 | val 0.43376
  Epoch 011 - train 0.38127 | val 0.43540
  Regression -> MSE: 0.000092, MAE: 0.007403, R²: -0.0575
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.38508 | val 0.53205
  Epoch 011 - train 0.37104 | val 0.52874
  Regression -> MSE: 0.000215, MAE: 0.011317, R²: -0.0172
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.33566 | val 0.32227
  Epoch 011 - train 0.31534 | val 0.32318
  Regression -> MSE: 0.000094, MAE: 0.008001, R²: -0.0400
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.35721 | val 0.27094
  Epoch 011 - train 0.39383 | val 0.27054
  Regression -> MSE: 0.000102, MAE: 0.008680, R²: -0.0228
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.35815 | val 0.31948
  Epoch 011 - train 0.36254 | val 0.31963
  Regression -> MSE: 0.000243, MAE: 0.013081, R²: -0.0265
  Directional -> Accuracy: 0.3810, MCC: -0.1925, F1: 0.1875

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.37450 | val 0.43416
  Epoch 011 - train 0.39877 | val 0.43698
  Regression -> MSE: 0.000177, MAE: 0.008270, R²: -0.0431
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.36636 | val 0.27414
  Epoch 011 - train 0.33608 | val 0.27546
  Regression -> MSE: 0.000244, MAE: 0.012161, R²: -0.0081
  Directional -> Accuracy: 0.4500, MCC: -0.0503, F1: 0.2667

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.36327 | val 0.65648
  Epoch 011 - train 0.37708 | val 0.66255
  Regression -> MSE: 0.000242, MAE: 0.010420, R²: -0.0256
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.34046 | val 0.40334
  Epoch 011 - train 0.38048 | val 0.40508
  Regression -> MSE: 0.000146, MAE: 0.008740, R²: -0.0589
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.35310 | val 0.49362
  Epoch 011 - train 0.36177 | val 0.49592
  Regression -> MSE: 0.000183, MAE: 0.010318, R²: -0.0020
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.33447 | val 0.42530
  Epoch 011 - train 0.33857 | val 0.42687
  Regression -> MSE: 0.000266, MAE: 0.010741, R²: -0.0007
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.32871 | val 0.39103
  Epoch 011 - train 0.33327 | val 0.39304
  Regression -> MSE: 0.000187, MAE: 0.010514, R²: -0.0199
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.33461 | val 0.32473
  Epoch 020 - train 0.33581 | val 0.31576
  Regression -> MSE: 0.000371, MAE: 0.013312, R²: -0.0660
  Directional -> Accuracy: 0.4242, MCC: -0.0723, F1: 0.2400

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.37039 | val 0.22809
  Epoch 011 - train 0.36372 | val 0.23429
  Regression -> MSE: 0.000129, MAE: 0.008533, R²: -0.2232
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.35464 | val 0.50472
  Epoch 011 - train 0.37441 | val 0.50685
  Regression -> MSE: 0.000225, MAE: 0.011423, R²: -0.0230
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.33971 | val 0.69209
  Epoch 011 - train 0.37637 | val 0.69425
  Regression -> MSE: 0.000080, MAE: 0.007003, R²: -0.0877
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.33371 | val 0.20634
  Epoch 011 - train 0.30404 | val 0.20689
  Regression -> MSE: 0.000320, MAE: 0.014354, R²: -0.0281
  Directional -> Accuracy: 0.3542, MCC: -0.0919, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.34340 | val 0.46185
  Epoch 011 - train 0.34651 | val 0.46524
  Regression -> MSE: 0.000078, MAE: 0.006941, R²: 0.0000
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.36828 | val 0.46307
  Epoch 011 - train 0.38542 | val 0.46491
  Regression -> MSE: 0.000304, MAE: 0.014424, R²: -0.0107
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.32536 | val 0.40227
  Epoch 011 - train 0.35387 | val 0.40277
  Regression -> MSE: 0.000101, MAE: 0.007275, R²: 0.0067
  Directional -> Accuracy: 0.5952, MCC: 0.1334, F1: 0.7302

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.34088 | val 0.46106
  Epoch 011 - train 0.37572 | val 0.46132
  Regression -> MSE: 0.000182, MAE: 0.010543, R²: -0.0397
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.33396 | val 0.37469
  Epoch 011 - train 0.31935 | val 0.37560
  Regression -> MSE: 0.000226, MAE: 0.011779, R²: -0.0010
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.34796 | val 0.41117
  Epoch 019 - train 0.36726 | val 0.41304
  Regression -> MSE: 0.000100, MAE: 0.008010, R²: -0.0619
  Directional -> Accuracy: 0.4464, MCC: -0.1279, F1: 0.5974

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.41129 | val 0.79322
  Epoch 011 - train 0.41765 | val 0.84124
  Regression -> MSE: 0.000168, MAE: 0.010406, R²: -0.0079
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.32942 | val 0.43813
  Epoch 011 - train 0.34024 | val 0.44044
  Regression -> MSE: 0.000129, MAE: 0.009231, R²: -0.0950
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 23:06:05,806] Trial 23 finished with value: -0.011545443223461222 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 64, 'learning_rate': 1.1178282154111943e-06, 'weight_decay': 4.956055382960131e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.6897724682999031, 'early_stopping_min_delta': 0.006116470103762225}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.36730 | val 0.60468
  Epoch 011 - train 0.36021 | val 0.62039
  Regression -> MSE: 0.000240, MAE: 0.012590, R²: 0.0013
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.19631 | val 0.31020
  Epoch 011 - train 0.19644 | val 0.31746
  Regression -> MSE: 0.000260, MAE: 0.012917, R²: -0.0865
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.6239

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.18237 | val 0.17461
  Epoch 011 - train 0.18103 | val 0.17422
  Regression -> MSE: 0.000704, MAE: 0.019538, R²: 0.0017
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.18532 | val 0.29715
  Epoch 011 - train 0.18629 | val 0.29746
  Regression -> MSE: 0.000323, MAE: 0.014611, R²: -0.0049
  Directional -> Accuracy: 0.5778, MCC: 0.2450, F1: 0.4242

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15937 | val 0.19207
  Epoch 011 - train 0.15804 | val 0.20234
  Regression -> MSE: 0.000358, MAE: 0.014689, R²: -0.0040
  Directional -> Accuracy: 0.5342, MCC: 0.0000, F1: 0.6964

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.18078 | val 0.18203
  Epoch 011 - train 0.17871 | val 0.18513
  Regression -> MSE: 0.000210, MAE: 0.010205, R²: 0.0035
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.6757

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.16268 | val 0.31403
  Epoch 011 - train 0.16823 | val 0.31799
  Regression -> MSE: 0.000589, MAE: 0.018654, R²: -0.0254
  Directional -> Accuracy: 0.4889, MCC: -0.0260, F1: 0.4390

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.19667 | val 0.24776
  Epoch 011 - train 0.19249 | val 0.25289
  Regression -> MSE: 0.000253, MAE: 0.012168, R²: -0.0041
  Directional -> Accuracy: 0.5522, MCC: -0.0356, F1: 0.2105

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.17761 | val 0.16791
  Epoch 011 - train 0.18218 | val 0.16764
  Regression -> MSE: 0.000643, MAE: 0.020111, R²: -0.0277
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.17496 | val 0.24618
  Epoch 011 - train 0.17843 | val 0.24576
  Regression -> MSE: 0.000378, MAE: 0.015738, R²: -0.0095
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.6176

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.18228 | val 0.24027
  Epoch 011 - train 0.17705 | val 0.24142
  Regression -> MSE: 0.000248, MAE: 0.012217, R²: 0.0013
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.5979

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.16424 | val 0.26698
  Epoch 020 - train 0.16128 | val 0.25790
  Regression -> MSE: 0.000396, MAE: 0.014769, R²: -0.2616
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.19540 | val 0.23100
  Epoch 011 - train 0.19911 | val 0.23417
  Regression -> MSE: 0.000708, MAE: 0.020205, R²: -0.0151
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.18279 | val 0.18871
  Epoch 011 - train 0.18784 | val 0.19043
  Regression -> MSE: 0.000143, MAE: 0.009400, R²: -0.0060
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.16720 | val 0.26352
  Epoch 011 - train 0.16467 | val 0.26622
  Regression -> MSE: 0.000229, MAE: 0.010699, R²: -0.0023
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.17427 | val 0.37487
  Epoch 019 - train 0.18353 | val 0.37757
  Regression -> MSE: 0.000380, MAE: 0.016634, R²: -0.0357
  Directional -> Accuracy: 0.4000, MCC: -0.1842, F1: 0.5588

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.19643 | val 0.20599
  Epoch 011 - train 0.19175 | val 0.21018
  Regression -> MSE: 0.000109, MAE: 0.007922, R²: -0.0044
  Directional -> Accuracy: 0.5441, MCC: 0.0730, F1: 0.6869

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.17250 | val 0.34834
  Epoch 011 - train 0.17340 | val 0.35661
  Regression -> MSE: 0.000151, MAE: 0.009778, R²: -0.0148
  Directional -> Accuracy: 0.6140, MCC: 0.0447, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.18388 | val 0.19227
  Epoch 011 - train 0.18381 | val 0.19349
  Regression -> MSE: 0.000291, MAE: 0.013846, R²: -0.0524
  Directional -> Accuracy: 0.4054, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.17298 | val 0.23857
  Epoch 011 - train 0.16874 | val 0.23788
  Regression -> MSE: 0.000159, MAE: 0.008887, R²: -0.0487
  Directional -> Accuracy: 0.5873, MCC: 0.0000, F1: 0.7400

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.20136 | val 0.30086
  Epoch 011 - train 0.19846 | val 0.30701
  Regression -> MSE: 0.000263, MAE: 0.011557, R²: -0.1711
  Directional -> Accuracy: 0.4521, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.19169 | val 0.25289
  Epoch 011 - train 0.19558 | val 0.25573
  Regression -> MSE: 0.000148, MAE: 0.008406, R²: -0.0110
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.17938 | val 0.20757
  Epoch 020 - train 0.17278 | val 0.20635
  Regression -> MSE: 0.000188, MAE: 0.010781, R²: -0.1149
  Directional -> Accuracy: 0.5312, MCC: 0.0695, F1: 0.4000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.18441 | val 0.21134
  Epoch 011 - train 0.18816 | val 0.21155
  Regression -> MSE: 0.000087, MAE: 0.007189, R²: 0.0127
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.18138 | val 0.22585
  Epoch 011 - train 0.17882 | val 0.22613
  Regression -> MSE: 0.000213, MAE: 0.011123, R²: 0.0016
  Directional -> Accuracy: 0.4688, MCC: 0.0000, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.16823 | val 0.17433
  Epoch 011 - train 0.16815 | val 0.17476
  Regression -> MSE: 0.000100, MAE: 0.008062, R²: -0.0908
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17900 | val 0.17541
  Epoch 011 - train 0.17449 | val 0.17668
  Regression -> MSE: 0.000107, MAE: 0.008823, R²: -0.1087
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.19459 | val 0.15515
  Epoch 011 - train 0.19429 | val 0.16066
  Regression -> MSE: 0.000277, MAE: 0.013054, R²: -0.0148
  Directional -> Accuracy: 0.5918, MCC: 0.0000, F1: 0.7436

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.19423 | val 0.22533
  Epoch 011 - train 0.19315 | val 0.22534
  Regression -> MSE: 0.000172, MAE: 0.007895, R²: -0.0133
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.18740 | val 0.16098
  Epoch 011 - train 0.18153 | val 0.16154
  Regression -> MSE: 0.000254, MAE: 0.012475, R²: -0.0103
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.7119

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.17989 | val 0.30716
  Epoch 020 - train 0.18224 | val 0.30563
  Regression -> MSE: 0.000228, MAE: 0.009830, R²: 0.0260
  Directional -> Accuracy: 0.4878, MCC: -0.0120, F1: 0.6038

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.20158 | val 0.22472
  Epoch 011 - train 0.19867 | val 0.22560
  Regression -> MSE: 0.000150, MAE: 0.009033, R²: -0.0799
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.20041 | val 0.24007
  Epoch 011 - train 0.19715 | val 0.24266
  Regression -> MSE: 0.000206, MAE: 0.010985, R²: -0.1045
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15782 | val 0.21982
  Epoch 011 - train 0.16573 | val 0.22074
  Regression -> MSE: 0.000279, MAE: 0.010771, R²: -0.0441
  Directional -> Accuracy: 0.4366, MCC: -0.1631, F1: 0.5238

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.17033 | val 0.18190
  Epoch 011 - train 0.16970 | val 0.18186
  Regression -> MSE: 0.000188, MAE: 0.010613, R²: -0.0017
  Directional -> Accuracy: 0.4286, MCC: -0.2345, F1: 0.6000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.18094 | val 0.17655
  Epoch 011 - train 0.17730 | val 0.17767
  Regression -> MSE: 0.000355, MAE: 0.011861, R²: -0.0089
  Directional -> Accuracy: 0.5692, MCC: 0.0000, F1: 0.7255

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.20725 | val 0.13206
  Epoch 011 - train 0.21000 | val 0.13459
  Regression -> MSE: 0.000140, MAE: 0.008969, R²: -0.2785
  Directional -> Accuracy: 0.4750, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.18264 | val 0.25611
  Epoch 011 - train 0.18571 | val 0.25648
  Regression -> MSE: 0.000225, MAE: 0.011398, R²: -0.0049
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.17533 | val 0.34242
  Epoch 011 - train 0.17505 | val 0.34542
  Regression -> MSE: 0.000076, MAE: 0.006743, R²: -0.0748
  Directional -> Accuracy: 0.6444, MCC: 0.2817, F1: 0.6923

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.17541 | val 0.11472
  Epoch 011 - train 0.18532 | val 0.11498
  Regression -> MSE: 0.000337, MAE: 0.014943, R²: -0.0597
  Directional -> Accuracy: 0.3261, MCC: 0.0000, F1: 0.4918

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.17998 | val 0.23711
  Epoch 011 - train 0.18183 | val 0.23756
  Regression -> MSE: 0.000078, MAE: 0.006816, R²: -0.0142
  Directional -> Accuracy: 0.5068, MCC: 0.0055, F1: 0.2174

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.19506 | val 0.25904
  Epoch 011 - train 0.19671 | val 0.26089
  Regression -> MSE: 0.000282, MAE: 0.013912, R²: -0.0130
  Directional -> Accuracy: 0.4773, MCC: -0.1525, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.18199 | val 0.19082
  Epoch 011 - train 0.18155 | val 0.19090
  Regression -> MSE: 0.000104, MAE: 0.007497, R²: -0.0065
  Directional -> Accuracy: 0.4146, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.19420 | val 0.22161
  Epoch 011 - train 0.19066 | val 0.22131
  Regression -> MSE: 0.000178, MAE: 0.009780, R²: 0.0036
  Directional -> Accuracy: 0.5870, MCC: 0.0809, F1: 0.3871

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.18238 | val 0.21174
  Epoch 011 - train 0.18708 | val 0.21500
  Regression -> MSE: 0.000234, MAE: 0.012067, R²: -0.0318
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.17871 | val 0.24218
  Epoch 011 - train 0.18595 | val 0.24553
  Regression -> MSE: 0.000088, MAE: 0.007535, R²: -0.0021
  Directional -> Accuracy: 0.5273, MCC: 0.0957, F1: 0.6486

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.21182 | val 0.31177
  Epoch 011 - train 0.21180 | val 0.31279
  Regression -> MSE: 0.000172, MAE: 0.010388, R²: -0.0272
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.17397 | val 0.22513
  Epoch 011 - train 0.17486 | val 0.22545
  Regression -> MSE: 0.000129, MAE: 0.009289, R²: -0.0762
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 23:07:03,123] Trial 24 finished with value: -0.011612624182549719 and parameters: {'feature_set': 'base', 'model_type': 'GRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.4, 'batch_size': 64, 'learning_rate': 3.4865369992681753e-06, 'weight_decay': 6.103070568402088e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.287735637831702, 'early_stopping_min_delta': 0.004704879002919833}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.18965 | val 0.32051
  Epoch 011 - train 0.19564 | val 0.33615
  Regression -> MSE: 0.000251, MAE: 0.012626, R²: -0.0290
  Directional -> Accuracy: 0.5254, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41841 | val 0.61299
  Epoch 011 - train 0.41167 | val 0.62244
  Regression -> MSE: 0.000246, MAE: 0.012474, R²: -0.0015
  Directional -> Accuracy: 0.5513, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.42970 | val 0.39943
  Epoch 011 - train 0.42334 | val 0.39883
  Regression -> MSE: 0.000692, MAE: 0.019628, R²: -0.0009
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.42037 | val 0.80438
  Epoch 011 - train 0.41892 | val 0.80460
  Regression -> MSE: 0.000343, MAE: 0.015040, R²: 0.0055
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33039 | val 0.35435
  Epoch 011 - train 0.34101 | val 0.35674
  Regression -> MSE: 0.000351, MAE: 0.014580, R²: -0.0182
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.39931 | val 0.40524
  Epoch 020 - train 0.39142 | val 0.37531
  Regression -> MSE: 0.000212, MAE: 0.010340, R²: -0.0580
  Directional -> Accuracy: 0.5577, MCC: 0.0891, F1: 0.6567

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39920 | val 0.92913
  Epoch 011 - train 0.40159 | val 0.92828
  Regression -> MSE: 0.000589, MAE: 0.018593, R²: -0.0296
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.42869 | val 0.55349
  Epoch 017 - train 0.41445 | val 0.58510
  Regression -> MSE: 0.000244, MAE: 0.011964, R²: 0.0061
  Directional -> Accuracy: 0.5286, MCC: 0.0352, F1: 0.4407

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41171 | val 0.56387
  Epoch 011 - train 0.41161 | val 0.56441
  Regression -> MSE: 0.000594, MAE: 0.019013, R²: -0.0161
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.40683 | val 0.69492
  Epoch 011 - train 0.40440 | val 0.69547
  Regression -> MSE: 0.000339, MAE: 0.014855, R²: -0.0012
  Directional -> Accuracy: 0.4524, MCC: -0.0981, F1: 0.3784

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41090 | val 0.59295
  Epoch 011 - train 0.40696 | val 0.60263
  Regression -> MSE: 0.000239, MAE: 0.011680, R²: -0.0017
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.38510 | val 0.76301
  Epoch 011 - train 0.39278 | val 0.76946
  Regression -> MSE: 0.000307, MAE: 0.013685, R²: -0.0044
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43181 | val 0.52374
  Epoch 011 - train 0.42911 | val 0.52645
  Regression -> MSE: 0.000668, MAE: 0.019393, R²: 0.0014
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43362 | val 0.42230
  Epoch 011 - train 0.41858 | val 0.42595
  Regression -> MSE: 0.000150, MAE: 0.009472, R²: -0.0015
  Directional -> Accuracy: 0.5455, MCC: 0.0833, F1: 0.5000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39423 | val 0.60567
  Epoch 011 - train 0.39043 | val 0.60622
  Regression -> MSE: 0.000224, MAE: 0.010728, R²: 0.0016
  Directional -> Accuracy: 0.5323, MCC: 0.0674, F1: 0.5915

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.40486 | val 1.09526
  Epoch 011 - train 0.40225 | val 1.09443
  Regression -> MSE: 0.000394, MAE: 0.016330, R²: -0.0476
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44683 | val 0.46023
  Epoch 011 - train 0.45063 | val 0.46126
  Regression -> MSE: 0.000107, MAE: 0.007872, R²: -0.0077
  Directional -> Accuracy: 0.5352, MCC: 0.0000, F1: 0.6972

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.40352 | val 0.84993
  Epoch 011 - train 0.41091 | val 0.85200
  Regression -> MSE: 0.000163, MAE: 0.010246, R²: -0.0190
  Directional -> Accuracy: 0.5667, MCC: 0.1292, F1: 0.6176

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.39330 | val 0.38474
  Epoch 011 - train 0.39349 | val 0.39202
  Regression -> MSE: 0.000269, MAE: 0.012915, R²: -0.0024
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37549 | val 0.68045
  Epoch 011 - train 0.37547 | val 0.69700
  Regression -> MSE: 0.000153, MAE: 0.008636, R²: -0.0377
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44988 | val 0.76726
  Epoch 011 - train 0.46074 | val 0.77014
  Regression -> MSE: 0.000241, MAE: 0.011120, R²: -0.0646
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43181 | val 0.53637
  Epoch 020 - train 0.41595 | val 0.52263
  Regression -> MSE: 0.000158, MAE: 0.009008, R²: -0.0671
  Directional -> Accuracy: 0.5714, MCC: 0.1772, F1: 0.6038

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.38954 | val 0.50344
  Epoch 020 - train 0.37542 | val 0.50229
  Regression -> MSE: 0.000177, MAE: 0.010508, R²: -0.0006
  Directional -> Accuracy: 0.4627, MCC: -0.0864, F1: 0.5500

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.46066 | val 0.55195
  Epoch 011 - train 0.46535 | val 0.55245
  Regression -> MSE: 0.000084, MAE: 0.006933, R²: -0.0043
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.43613 | val 0.58251
  Epoch 011 - train 0.42648 | val 0.58514
  Regression -> MSE: 0.000221, MAE: 0.011678, R²: -0.0112
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.35666 | val 0.30459
  Epoch 020 - train 0.35635 | val 0.29634
  Regression -> MSE: 0.000095, MAE: 0.008007, R²: -0.0386
  Directional -> Accuracy: 0.5263, MCC: 0.0887, F1: 0.4906

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46590 | val 0.20011
  Epoch 011 - train 0.44402 | val 0.19964
  Regression -> MSE: 0.000143, MAE: 0.009808, R²: -0.1407
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.43935 | val 0.36146
  Epoch 011 - train 0.42763 | val 0.36280
  Regression -> MSE: 0.000250, MAE: 0.013135, R²: -0.0499
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41336 | val 0.53683
  Epoch 020 - train 0.40393 | val 0.51774
  Regression -> MSE: 0.000232, MAE: 0.009785, R²: -0.4176
  Directional -> Accuracy: 0.5172, MCC: 0.2453, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.48717 | val 0.24485
  Epoch 011 - train 0.47379 | val 0.24451
  Regression -> MSE: 0.000235, MAE: 0.011917, R²: -0.0025
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.40840 | val 0.73075
  Epoch 020 - train 0.40842 | val 0.71025
  Regression -> MSE: 0.000249, MAE: 0.010411, R²: 0.0062
  Directional -> Accuracy: 0.4889, MCC: -0.0349, F1: 0.5818

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.46544 | val 0.69155
  Epoch 011 - train 0.47677 | val 0.69586
  Regression -> MSE: 0.000140, MAE: 0.008616, R²: -0.0552
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42805 | val 0.56643
  Epoch 011 - train 0.43502 | val 0.56509
  Regression -> MSE: 0.000197, MAE: 0.010637, R²: -0.0432
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37152 | val 0.54491
  Epoch 019 - train 0.35024 | val 0.54307
  Regression -> MSE: 0.000277, MAE: 0.011015, R²: -0.0724
  Directional -> Accuracy: 0.5135, MCC: 0.0803, F1: 0.4545

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.42140 | val 0.38259
  Epoch 011 - train 0.41478 | val 0.38334
  Regression -> MSE: 0.000165, MAE: 0.010218, R²: -0.0167
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.39018 | val 0.49148
  Epoch 011 - train 0.39018 | val 0.49580
  Regression -> MSE: 0.000188, MAE: 0.010641, R²: -0.0274
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41235 | val 0.37895
  Epoch 020 - train 0.39155 | val 0.36058
  Regression -> MSE: 0.000342, MAE: 0.012128, R²: 0.0188
  Directional -> Accuracy: 0.5588, MCC: 0.1902, F1: 0.5000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43273 | val 0.25659
  Epoch 011 - train 0.42977 | val 0.25598
  Regression -> MSE: 0.000121, MAE: 0.008275, R²: -0.1624
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42716 | val 0.65798
  Epoch 011 - train 0.41988 | val 0.66055
  Regression -> MSE: 0.000215, MAE: 0.011136, R²: -0.0004
  Directional -> Accuracy: 0.5345, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40914 | val 0.87621
  Epoch 011 - train 0.42368 | val 0.87611
  Regression -> MSE: 0.000094, MAE: 0.007600, R²: -0.1760
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.41638 | val 0.34667
  Epoch 011 - train 0.41157 | val 0.34638
  Regression -> MSE: 0.000352, MAE: 0.015898, R²: -0.0715
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.44173 | val 0.25810
  Epoch 011 - train 0.44360 | val 0.25913
  Regression -> MSE: 0.000251, MAE: 0.011185, R²: -0.0535
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40406 | val 0.54392
  Epoch 011 - train 0.39731 | val 0.54419
  Regression -> MSE: 0.000081, MAE: 0.007105, R²: -0.0069
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45400 | val 0.45942
  Epoch 011 - train 0.46393 | val 0.45957
  Regression -> MSE: 0.000361, MAE: 0.015331, R²: -0.0036
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.35817 | val 0.53246
  Epoch 011 - train 0.37922 | val 0.53294
  Regression -> MSE: 0.000098, MAE: 0.007179, R²: -0.0130
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.46024 | val 0.67965
  Epoch 011 - train 0.45436 | val 0.68446
  Regression -> MSE: 0.000183, MAE: 0.010423, R²: -0.0128
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.37727 | val 0.49733
  Epoch 011 - train 0.39120 | val 0.49801
  Regression -> MSE: 0.000220, MAE: 0.011655, R²: -0.0035
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.41406 | val 0.51695
  Epoch 011 - train 0.41342 | val 0.52108
  Regression -> MSE: 0.000092, MAE: 0.007645, R²: -0.0059
  Directional -> Accuracy: 0.4828, MCC: 0.0000, F1: 0.6512

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.43801 | val 0.78047
  Epoch 011 - train 0.44069 | val 0.78070
  Regression -> MSE: 0.000161, MAE: 0.010092, R²: -0.0038
  Directional -> Accuracy: 0.6000, MCC: 0.1954, F1: 0.6765

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.41285 | val 0.56857
  Epoch 011 - train 0.41625 | val 0.56929
  Regression -> MSE: 0.000120, MAE: 0.008867, R²: -0.0560
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 23:08:14,752] Trial 25 finished with value: -0.011552913060305738 and parameters: {'feature_set': 'sentinment', 'model_type': 'BiLSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 64, 'learning_rate': 1.1890000206719205e-05, 'weight_decay': 4.922499929561801e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 1.184608063028084, 'early_stopping_min_delta': 0.008480653500045367}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.43219 | val 0.71159
  Epoch 011 - train 0.45208 | val 0.71050
  Regression -> MSE: 0.000237, MAE: 0.012248, R²: -0.0160
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.38234 | val 0.61402
  Epoch 011 - train 0.38396 | val 0.62150
  Regression -> MSE: 0.000255, MAE: 0.012833, R²: -0.0295
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.35877 | val 0.37086
  Epoch 011 - train 0.37769 | val 0.37440
  Regression -> MSE: 0.000709, MAE: 0.019803, R²: -0.0364
  Directional -> Accuracy: 0.4348, MCC: -0.0693, F1: 0.2778

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.42072 | val 0.73958
  Epoch 011 - train 0.38698 | val 0.74960
  Regression -> MSE: 0.000315, MAE: 0.014533, R²: -0.0157
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.35447 | val 0.61257
  Epoch 011 - train 0.34059 | val 0.62653
  Regression -> MSE: 0.000403, MAE: 0.015536, R²: -0.1545
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.38988 | val 0.35388
  Epoch 020 - train 0.39983 | val 0.35236
  Regression -> MSE: 0.000213, MAE: 0.010553, R²: -0.0441
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.4091

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.34462 | val 0.79503
  Epoch 016 - train 0.37788 | val 0.80048
  Regression -> MSE: 0.000547, MAE: 0.017969, R²: 0.0151
  Directional -> Accuracy: 0.5106, MCC: 0.0183, F1: 0.4651

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.41241 | val 0.52187
  Epoch 011 - train 0.40654 | val 0.52717
  Regression -> MSE: 0.000244, MAE: 0.011904, R²: 0.0055
  Directional -> Accuracy: 0.5217, MCC: 0.0026, F1: 0.4000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39671 | val 0.55449
  Epoch 020 - train 0.38745 | val 0.54049
  Regression -> MSE: 0.000669, MAE: 0.020768, R²: -0.1194
  Directional -> Accuracy: 0.4318, MCC: -0.0365, F1: 0.5283

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.36652 | val 0.47356
  Epoch 011 - train 0.40950 | val 0.47342
  Regression -> MSE: 0.000390, MAE: 0.016028, R²: -0.0165
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.40066 | val 0.70669
  Epoch 011 - train 0.38236 | val 0.73215
  Regression -> MSE: 0.000242, MAE: 0.011828, R²: -0.0038
  Directional -> Accuracy: 0.4429, MCC: 0.0160, F1: 0.5895

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.36050 | val 0.55815
  Epoch 018 - train 0.36718 | val 0.56047
  Regression -> MSE: 0.000326, MAE: 0.013680, R²: -0.0495
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42489 | val 0.48066
  Epoch 011 - train 0.41798 | val 0.48677
  Regression -> MSE: 0.000687, MAE: 0.019811, R²: -0.0142
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.36530 | val 0.39233
  Epoch 011 - train 0.38317 | val 0.39275
  Regression -> MSE: 0.000139, MAE: 0.009042, R²: -0.0067
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37198 | val 0.50847
  Epoch 011 - train 0.37311 | val 0.50927
  Regression -> MSE: 0.000232, MAE: 0.010935, R²: -0.0323
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41159 | val 0.90525
  Epoch 011 - train 0.42577 | val 0.90578
  Regression -> MSE: 0.000376, MAE: 0.015957, R²: -0.0372
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.40609 | val 0.45617
  Epoch 011 - train 0.40439 | val 0.45911
  Regression -> MSE: 0.000112, MAE: 0.008301, R²: -0.0381
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.35718 | val 0.71491
  Epoch 011 - train 0.34266 | val 0.71974
  Regression -> MSE: 0.000156, MAE: 0.009775, R²: 0.0011
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.38747 | val 0.40341
  Epoch 011 - train 0.38171 | val 0.40745
  Regression -> MSE: 0.000283, MAE: 0.013479, R²: -0.0386
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.34684 | val 0.61265
  Epoch 011 - train 0.33803 | val 0.61782
  Regression -> MSE: 0.000158, MAE: 0.008838, R²: -0.0537
  Directional -> Accuracy: 0.5077, MCC: -0.1571, F1: 0.6596

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.39075 | val 0.61829
  Epoch 011 - train 0.40068 | val 0.62012
  Regression -> MSE: 0.000230, MAE: 0.010915, R²: -0.0178
  Directional -> Accuracy: 0.5733, MCC: 0.1818, F1: 0.7193

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42978 | val 0.55245
  Epoch 011 - train 0.43405 | val 0.56200
  Regression -> MSE: 0.000143, MAE: 0.008324, R²: 0.0009
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.35942 | val 0.43220
  Epoch 019 - train 0.35376 | val 0.43275
  Regression -> MSE: 0.000187, MAE: 0.011110, R²: -0.1300
  Directional -> Accuracy: 0.4091, MCC: -0.2121, F1: 0.5301

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.42883 | val 0.49905
  Epoch 011 - train 0.42253 | val 0.50220
  Regression -> MSE: 0.000090, MAE: 0.007288, R²: -0.0567
  Directional -> Accuracy: 0.4310, MCC: -0.0473, F1: 0.1538

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42188 | val 0.48210
  Epoch 011 - train 0.43843 | val 0.48096
  Regression -> MSE: 0.000208, MAE: 0.011227, R²: 0.0173
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.35155 | val 0.32126
  Epoch 011 - train 0.34733 | val 0.32115
  Regression -> MSE: 0.000105, MAE: 0.008376, R²: -0.1381
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.39011 | val 0.27806
  Epoch 011 - train 0.38019 | val 0.27767
  Regression -> MSE: 0.000106, MAE: 0.008896, R²: -0.0315
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.40472 | val 0.37605
  Epoch 011 - train 0.40069 | val 0.38125
  Regression -> MSE: 0.000237, MAE: 0.012724, R²: -0.0241
  Directional -> Accuracy: 0.5116, MCC: -0.0276, F1: 0.6038

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39022 | val 0.50958
  Epoch 011 - train 0.39668 | val 0.51429
  Regression -> MSE: 0.000169, MAE: 0.007858, R²: -0.0152
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.37885 | val 0.28149
  Epoch 011 - train 0.40774 | val 0.28239
  Regression -> MSE: 0.000236, MAE: 0.011867, R²: 0.0015
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.37083 | val 0.65924
  Epoch 011 - train 0.38966 | val 0.65841
  Regression -> MSE: 0.000231, MAE: 0.009892, R²: -0.0017
  Directional -> Accuracy: 0.4186, MCC: -0.2803, F1: 0.5902

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.38801 | val 0.51324
  Epoch 011 - train 0.39496 | val 0.51471
  Regression -> MSE: 0.000143, MAE: 0.008683, R²: -0.0561
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.37203 | val 0.50628
  Epoch 011 - train 0.36279 | val 0.50859
  Regression -> MSE: 0.000188, MAE: 0.010469, R²: 0.0020
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.34476 | val 0.50091
  Epoch 011 - train 0.33792 | val 0.50642
  Regression -> MSE: 0.000263, MAE: 0.010488, R²: -0.0032
  Directional -> Accuracy: 0.5342, MCC: -0.0914, F1: 0.6909

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.36620 | val 0.30982
  Epoch 011 - train 0.34973 | val 0.30968
  Regression -> MSE: 0.000165, MAE: 0.010349, R²: 0.0076
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37011 | val 0.43290
  Epoch 011 - train 0.35249 | val 0.43920
  Regression -> MSE: 0.000183, MAE: 0.010380, R²: -0.0145
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.35541 | val 0.32982
  Epoch 020 - train 0.35535 | val 0.32877
  Regression -> MSE: 0.000342, MAE: 0.012499, R²: 0.0016
  Directional -> Accuracy: 0.4776, MCC: 0.0356, F1: 0.3396

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.41219 | val 0.21501
  Epoch 011 - train 0.42980 | val 0.21686
  Regression -> MSE: 0.000113, MAE: 0.008249, R²: -0.0761
  Directional -> Accuracy: 0.5814, MCC: 0.1835, F1: 0.6786

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40458 | val 0.56879
  Epoch 011 - train 0.37600 | val 0.57600
  Regression -> MSE: 0.000220, MAE: 0.011344, R²: -0.0060
  Directional -> Accuracy: 0.4561, MCC: -0.0767, F1: 0.5079

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.40405 | val 0.77684
  Epoch 011 - train 0.39815 | val 0.78358
  Regression -> MSE: 0.000096, MAE: 0.007616, R²: -0.2314
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.38668 | val 0.28307
  Epoch 011 - train 0.38644 | val 0.28254
  Regression -> MSE: 0.000331, MAE: 0.015001, R²: -0.0759
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.38600 | val 0.19477
  Epoch 011 - train 0.40704 | val 0.19652
  Regression -> MSE: 0.000246, MAE: 0.011527, R²: -0.0083
  Directional -> Accuracy: 0.4737, MCC: -0.0228, F1: 0.2308

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.38666 | val 0.50196
  Epoch 011 - train 0.36901 | val 0.50479
  Regression -> MSE: 0.000083, MAE: 0.007015, R²: -0.0243
  Directional -> Accuracy: 0.5067, MCC: 0.0022, F1: 0.0513

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.39136 | val 0.52052
  Epoch 011 - train 0.41411 | val 0.52554
  Regression -> MSE: 0.000307, MAE: 0.014491, R²: -0.0003
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.39071 | val 0.43628
  Epoch 011 - train 0.37853 | val 0.43739
  Regression -> MSE: 0.000098, MAE: 0.007174, R²: -0.0027
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.41241 | val 0.50106
  Epoch 011 - train 0.38687 | val 0.50106
  Regression -> MSE: 0.000178, MAE: 0.010377, R²: -0.0383
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.35537 | val 0.45086
  Epoch 011 - train 0.36163 | val 0.45282
  Regression -> MSE: 0.000227, MAE: 0.011842, R²: -0.0161
  Directional -> Accuracy: 0.5179, MCC: -0.1255, F1: 0.6824

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.37154 | val 0.43343
  Epoch 011 - train 0.39450 | val 0.43585
  Regression -> MSE: 0.000096, MAE: 0.007809, R²: -0.0360
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.39148 | val 0.69473
  Epoch 011 - train 0.39515 | val 0.69890
  Regression -> MSE: 0.000166, MAE: 0.010224, R²: -0.0122
  Directional -> Accuracy: 0.5000, MCC: 0.0719, F1: 0.1290

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.36336 | val 0.52684
  Epoch 011 - train 0.36828 | val 0.53243
  Regression -> MSE: 0.000118, MAE: 0.008897, R²: -0.0188
  Directional -> Accuracy: 0.5357, MCC: 0.0739, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 23:08:55,686] Trial 26 finished with value: -0.011535768689283495 and parameters: {'feature_set': 'emotion', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.5, 'batch_size': 64, 'learning_rate': 1.9660445378974564e-06, 'weight_decay': 1.343893775643396e-05, 'lr_patience': 7, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.8273550566988029, 'early_stopping_min_delta': 0.007252332476718826}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.36990 | val 0.60647
  Epoch 011 - train 0.39542 | val 0.60848
  Regression -> MSE: 0.000235, MAE: 0.012306, R²: 0.0072
  Directional -> Accuracy: 0.5574, MCC: 0.1904, F1: 0.6582

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.34269 | val 0.42900
  Epoch 011 - train 0.32541 | val 0.42935
  Regression -> MSE: 0.000245, MAE: 0.012527, R²: -0.0208
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.31812 | val 0.28500
  Epoch 011 - train 0.31223 | val 0.28493
  Regression -> MSE: 0.000706, MAE: 0.019859, R²: -0.0112
  Directional -> Accuracy: 0.5778, MCC: 0.2471, F1: 0.5128

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.34229 | val 0.53754
  Epoch 011 - train 0.32147 | val 0.53657
  Regression -> MSE: 0.000316, MAE: 0.014546, R²: -0.0051
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.30973 | val 0.28802
  Epoch 011 - train 0.30584 | val 0.29008
  Regression -> MSE: 0.000359, MAE: 0.014746, R²: -0.0162
  Directional -> Accuracy: 0.5270, MCC: 0.0168, F1: 0.6316

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.34094 | val 0.33494
  Epoch 011 - train 0.31932 | val 0.33846
  Regression -> MSE: 0.000211, MAE: 0.010443, R²: -0.0251
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.32738 | val 0.58462
  Epoch 020 - train 0.31895 | val 0.57395
  Regression -> MSE: 0.000560, MAE: 0.018632, R²: 0.0112
  Directional -> Accuracy: 0.5217, MCC: 0.0417, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.32228 | val 0.40002
  Epoch 011 - train 0.33185 | val 0.40039
  Regression -> MSE: 0.000248, MAE: 0.011991, R²: 0.0012
  Directional -> Accuracy: 0.5294, MCC: 0.0046, F1: 0.3846

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.30822 | val 0.27770
  Epoch 011 - train 0.35122 | val 0.28158
  Regression -> MSE: 0.000614, MAE: 0.019556, R²: -0.0056
  Directional -> Accuracy: 0.5476, MCC: -0.1353, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.31753 | val 0.38605
  Epoch 011 - train 0.33611 | val 0.38704
  Regression -> MSE: 0.000379, MAE: 0.015583, R²: -0.0159
  Directional -> Accuracy: 0.5417, MCC: -0.0258, F1: 0.1538

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.36015 | val 0.50745
  Epoch 011 - train 0.35695 | val 0.52033
  Regression -> MSE: 0.000254, MAE: 0.011812, R²: -0.0354
  Directional -> Accuracy: 0.5797, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.30083 | val 0.50192
  Epoch 011 - train 0.32273 | val 0.50486
  Regression -> MSE: 0.000318, MAE: 0.013680, R²: -0.0170
  Directional -> Accuracy: 0.3878, MCC: -0.2079, F1: 0.4231

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.35343 | val 0.37662
  Epoch 011 - train 0.33867 | val 0.38265
  Regression -> MSE: 0.000683, MAE: 0.019639, R²: 0.0041
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.32894 | val 0.33709
  Epoch 011 - train 0.34024 | val 0.33945
  Regression -> MSE: 0.000141, MAE: 0.009279, R²: -0.0186
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37386 | val 0.49536
  Epoch 011 - train 0.38251 | val 0.50576
  Regression -> MSE: 0.000231, MAE: 0.011077, R²: -0.0214
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.32880 | val 0.70074
  Epoch 011 - train 0.32476 | val 0.70399
  Regression -> MSE: 0.000370, MAE: 0.015941, R²: -0.0080
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.37523 | val 0.38227
  Epoch 011 - train 0.35491 | val 0.38408
  Regression -> MSE: 0.000114, MAE: 0.008337, R²: -0.0509
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.34283 | val 0.55846
  Epoch 011 - train 0.30509 | val 0.56188
  Regression -> MSE: 0.000159, MAE: 0.009921, R²: -0.0075
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.33843 | val 0.33501
  Epoch 011 - train 0.33981 | val 0.33871
  Regression -> MSE: 0.000284, MAE: 0.012995, R²: -0.0375
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.31238 | val 0.45463
  Epoch 011 - train 0.30064 | val 0.45961
  Regression -> MSE: 0.000162, MAE: 0.009024, R²: -0.0673
  Directional -> Accuracy: 0.5000, MCC: -0.0250, F1: 0.5676

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.33218 | val 0.48652
  Epoch 011 - train 0.31475 | val 0.48628
  Regression -> MSE: 0.000245, MAE: 0.011256, R²: -0.0766
  Directional -> Accuracy: 0.4324, MCC: -0.0816, F1: 0.1250

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.33943 | val 0.42891
  Epoch 011 - train 0.34920 | val 0.43445
  Regression -> MSE: 0.000145, MAE: 0.008399, R²: -0.0086
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.31422 | val 0.37250
  Epoch 017 - train 0.31595 | val 0.37344
  Regression -> MSE: 0.000175, MAE: 0.010886, R²: -0.0554
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.34969 | val 0.38773
  Epoch 011 - train 0.33651 | val 0.39042
  Regression -> MSE: 0.000090, MAE: 0.007335, R²: -0.0367
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.34265 | val 0.41049
  Epoch 011 - train 0.33175 | val 0.41650
  Regression -> MSE: 0.000211, MAE: 0.011063, R²: 0.0015
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.31039 | val 0.30289
  Epoch 011 - train 0.31599 | val 0.30651
  Regression -> MSE: 0.000095, MAE: 0.008069, R²: -0.0588
  Directional -> Accuracy: 0.3818, MCC: -0.2665, F1: 0.4688

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.34916 | val 0.26724
  Epoch 011 - train 0.34181 | val 0.26958
  Regression -> MSE: 0.000111, MAE: 0.009030, R²: -0.1119
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.31217 | val 0.29170
  Epoch 011 - train 0.33655 | val 0.29250
  Regression -> MSE: 0.000239, MAE: 0.012933, R²: -0.0083
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.31832 | val 0.37392
  Epoch 011 - train 0.32118 | val 0.37548
  Regression -> MSE: 0.000180, MAE: 0.008077, R²: -0.0621
  Directional -> Accuracy: 0.4643, MCC: -0.2812, F1: 0.6341

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.37645 | val 0.28750
  Epoch 011 - train 0.40987 | val 0.29087
  Regression -> MSE: 0.000247, MAE: 0.012232, R²: -0.0203
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.31940 | val 0.53967
  Epoch 011 - train 0.30937 | val 0.53986
  Regression -> MSE: 0.000236, MAE: 0.010091, R²: -0.0027
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.36718 | val 0.36729
  Epoch 011 - train 0.34208 | val 0.36726
  Regression -> MSE: 0.000144, MAE: 0.008602, R²: -0.0446
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.31416 | val 0.42332
  Epoch 011 - train 0.32954 | val 0.42346
  Regression -> MSE: 0.000187, MAE: 0.010147, R²: -0.0206
  Directional -> Accuracy: 0.5510, MCC: 0.1553, F1: 0.4211

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.29732 | val 0.39590
  Epoch 011 - train 0.30806 | val 0.39628
  Regression -> MSE: 0.000268, MAE: 0.010680, R²: -0.0089
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.33668 | val 0.32491
  Epoch 011 - train 0.33086 | val 0.32609
  Regression -> MSE: 0.000188, MAE: 0.010623, R²: -0.0276
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.30248 | val 0.30189
  Epoch 011 - train 0.32503 | val 0.30317
  Regression -> MSE: 0.000352, MAE: 0.012358, R²: -0.0110
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.32210 | val 0.18001
  Epoch 011 - train 0.35344 | val 0.18000
  Regression -> MSE: 0.000113, MAE: 0.008216, R²: -0.0648
  Directional -> Accuracy: 0.5000, MCC: -0.0793, F1: 0.6557

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.35430 | val 0.47949
  Epoch 011 - train 0.35121 | val 0.48358
  Regression -> MSE: 0.000229, MAE: 0.011566, R²: -0.0426
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.32654 | val 0.60988
  Epoch 011 - train 0.33652 | val 0.61248
  Regression -> MSE: 0.000089, MAE: 0.007345, R²: -0.2019
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.33217 | val 0.20218
  Epoch 011 - train 0.33849 | val 0.20165
  Regression -> MSE: 0.000315, MAE: 0.014031, R²: -0.0108
  Directional -> Accuracy: 0.6250, MCC: 0.1144, F1: 0.3571

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.32568 | val 0.40237
  Epoch 011 - train 0.34751 | val 0.40202
  Regression -> MSE: 0.000078, MAE: 0.006926, R²: -0.0050
  Directional -> Accuracy: 0.5000, MCC: 0.1139, F1: 0.6606

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.37633 | val 0.40709
  Epoch 011 - train 0.36532 | val 0.40641
  Regression -> MSE: 0.000298, MAE: 0.014308, R²: 0.0104
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.35173 | val 0.35289
  Epoch 011 - train 0.35240 | val 0.35393
  Regression -> MSE: 0.000101, MAE: 0.007353, R²: 0.0094
  Directional -> Accuracy: 0.5238, MCC: 0.0694, F1: 0.5238

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.35274 | val 0.39829
  Epoch 011 - train 0.34200 | val 0.39778
  Regression -> MSE: 0.000178, MAE: 0.010152, R²: -0.0121
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.30513 | val 0.42617
  Epoch 011 - train 0.31335 | val 0.44160
  Regression -> MSE: 0.000237, MAE: 0.011963, R²: -0.0503
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.31855 | val 0.38613
  Epoch 011 - train 0.33735 | val 0.39080
  Regression -> MSE: 0.000095, MAE: 0.007803, R²: -0.0092
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.32884 | val 0.52309
  Epoch 011 - train 0.36073 | val 0.52684
  Regression -> MSE: 0.000167, MAE: 0.010304, R²: 0.0013
  Directional -> Accuracy: 0.5849, MCC: 0.1825, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.33546 | val 0.39364
  Epoch 011 - train 0.35845 | val 0.39367
  Regression -> MSE: 0.000121, MAE: 0.009160, R²: -0.0237
  Directional -> Accuracy: 0.5273, MCC: 0.0000, F1: 0.6905

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-23 23:09:42,828] Trial 27 finished with value: -0.011519416821460357 and parameters: {'feature_set': 'finbert', 'model_type': 'GRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 1.022183252723288e-06, 'weight_decay': 4.7848548671281065e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.5915243956071086, 'early_stopping_min_delta': 0.00898587003106631}. Best is trial 0 with value: -0.011474062271054221.

  Epoch 010 - train 0.38844 | val 0.59049
  Epoch 011 - train 0.36325 | val 0.61469
  Regression -> MSE: 0.000237, MAE: 0.012436, R²: 0.0117
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.30508 | val 0.40793
  Epoch 020 - train 0.29523 | val 0.40646
  Epoch 021 - train 0.30333 | val 0.40636
  Regression -> MSE: 0.000261, MAE: 0.013000, R²: -0.0531
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.30798 | val 0.27261
  Epoch 020 - train 0.28018 | val 0.27642
  Epoch 021 - train 0.30705 | val 0.27643
  Regression -> MSE: 0.000717, MAE: 0.019914, R²: -0.0471
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.29370 | val 0.49355
  Epoch 020 - train 0.30233 | val 0.49824
  Epoch 021 - train 0.30668 | val 0.49837
  Regression -> MSE: 0.000308, MAE: 0.014368, R²: 0.0067
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.25869 | val 0.24963
  Epoch 020 - train 0.26090 | val 0.24072
  Epoch 021 - train 0.25636 | val 0.24058
  Regression -> MSE: 0.000352, MAE: 0.014569, R²: -0.0063
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.27057 | val 0.35052
  Epoch 020 - train 0.27977 | val 0.37425
  Epoch 021 - train 0.28080 | val 0.37455
  Regression -> MSE: 0.000202, MAE: 0.009893, R²: 0.0097
  Directional -> Accuracy: 0.6078, MCC: 0.2415, F1: 0.7143

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.27938 | val 0.58236
  Epoch 020 - train 0.26684 | val 0.61923
  Epoch 021 - train 0.28524 | val 0.61975
  Regression -> MSE: 0.000586, MAE: 0.018711, R²: -0.0563
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.30430 | val 0.38060
  Epoch 020 - train 0.29084 | val 0.38172
  Epoch 021 - train 0.29635 | val 0.38174
  Regression -> MSE: 0.000249, MAE: 0.011926, R²: -0.0145
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.32034 | val 0.34882
  Epoch 020 - train 0.30138 | val 0.36995
  Epoch 021 - train 0.31564 | val 0.37038
  Regression -> MSE: 0.000603, MAE: 0.019295, R²: -0.0100
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.29327 | val 0.35107
  Epoch 020 - train 0.31420 | val 0.35238
  Epoch 021 - train 0.31660 | val 0.35234
  Regression -> MSE: 0.000403, MAE: 0.016139, R²: -0.0514
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.28681 | val 0.38818
  Epoch 020 - train 0.29913 | val 0.38423
  Epoch 021 - train 0.29447 | val 0.38395
  Regression -> MSE: 0.000241, MAE: 0.011624, R²: 0.0016
  Directional -> Accuracy: 0.6000, MCC: 0.1414, F1: 0.3000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.29585 | val 0.49089
  Epoch 020 - train 0.28112 | val 0.50644
  Epoch 021 - train 0.28424 | val 0.50659
  Regression -> MSE: 0.000313, MAE: 0.013801, R²: -0.0064
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.32727 | val 0.39240
  Epoch 020 - train 0.31470 | val 0.39042
  Epoch 021 - train 0.31240 | val 0.39038
  Regression -> MSE: 0.000677, MAE: 0.019452, R²: 0.0003
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.31268 | val 0.32830
  Epoch 020 - train 0.30044 | val 0.34629
  Epoch 021 - train 0.28311 | val 0.34644
  Regression -> MSE: 0.000139, MAE: 0.009307, R²: -0.0085
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.27821 | val 0.39627
  Epoch 020 - train 0.27973 | val 0.39619
  Epoch 021 - train 0.28353 | val 0.39622
  Regression -> MSE: 0.000227, MAE: 0.010747, R²: -0.0081
  Directional -> Accuracy: 0.4590, MCC: -0.0958, F1: 0.1951

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.29807 | val 0.80766
  Epoch 020 - train 0.29536 | val 0.80750
  Epoch 021 - train 0.29740 | val 0.80723
  Regression -> MSE: 0.000360, MAE: 0.016081, R²: 0.0047
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.30356 | val 0.31472
  Epoch 020 - train 0.30203 | val 0.31146
  Epoch 021 - train 0.31498 | val 0.31137
  Regression -> MSE: 0.000110, MAE: 0.008187, R²: -0.0154
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.28065 | val 0.53751
  Epoch 020 - train 0.29970 | val 0.53228
  Epoch 021 - train 0.28714 | val 0.53212
  Regression -> MSE: 0.000158, MAE: 0.009723, R²: -0.0113
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.30517 | val 0.41445
  Epoch 020 - train 0.28883 | val 0.42527
  Epoch 021 - train 0.29782 | val 0.42555
  Regression -> MSE: 0.000296, MAE: 0.014070, R²: -0.0892
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.25807 | val 0.40377
  Epoch 020 - train 0.25345 | val 0.40129
  Epoch 021 - train 0.26683 | val 0.40123
  Regression -> MSE: 0.000161, MAE: 0.008961, R²: -0.0749
  Directional -> Accuracy: 0.4769, MCC: -0.1150, F1: 0.5854

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.30602 | val 0.48427
  Epoch 020 - train 0.31253 | val 0.48131
  Epoch 021 - train 0.32144 | val 0.48117
  Regression -> MSE: 0.000271, MAE: 0.011839, R²: -0.1965
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.32574 | val 0.51291
  Epoch 020 - train 0.31847 | val 0.53976
  Epoch 021 - train 0.32564 | val 0.53973
  Regression -> MSE: 0.000156, MAE: 0.008935, R²: -0.0915
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.30524 | val 0.41663
  Epoch 020 - train 0.28915 | val 0.41379
  Epoch 021 - train 0.28756 | val 0.41368
  Regression -> MSE: 0.000167, MAE: 0.010275, R²: -0.0106
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.30155 | val 0.36767
  Epoch 020 - train 0.29957 | val 0.36885
  Epoch 021 - train 0.31629 | val 0.36883
  Regression -> MSE: 0.000088, MAE: 0.007212, R²: -0.0330
  Directional -> Accuracy: 0.4828, MCC: 0.2033, F1: 0.1667

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.31337 | val 0.36534
  Epoch 020 - train 0.30032 | val 0.36785
  Epoch 021 - train 0.29762 | val 0.36790
  Regression -> MSE: 0.000212, MAE: 0.011157, R²: -0.0025
  Directional -> Accuracy: 0.4394, MCC: -0.1156, F1: 0.5843

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.26971 | val 0.27118
  Epoch 020 - train 0.27953 | val 0.26858
  Epoch 021 - train 0.28623 | val 0.26844
  Regression -> MSE: 0.000097, MAE: 0.008168, R²: -0.0583
  Directional -> Accuracy: 0.4643, MCC: -0.1124, F1: 0.5588

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.29434 | val 0.20790
  Epoch 020 - train 0.26796 | val 0.19991
  Epoch 030 - train 0.29874 | val 0.20169
  Regression -> MSE: 0.000111, MAE: 0.008941, R²: -0.0724
  Directional -> Accuracy: 0.4783, MCC: 0.0370, F1: 0.5714

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.34393 | val 0.29079
  Epoch 020 - train 0.33765 | val 0.29412
  Epoch 021 - train 0.31907 | val 0.29400
  Regression -> MSE: 0.000232, MAE: 0.012604, R²: -0.0010
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.35130 | val 0.38651
  Epoch 020 - train 0.32624 | val 0.38346
  Epoch 021 - train 0.32957 | val 0.38333
  Regression -> MSE: 0.000172, MAE: 0.007960, R²: -0.0364
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.34054 | val 0.23064
  Epoch 020 - train 0.33816 | val 0.24072
  Epoch 021 - train 0.33206 | val 0.24103
  Regression -> MSE: 0.000240, MAE: 0.011978, R²: -0.0164
  Directional -> Accuracy: 0.4878, MCC: 0.1469, F1: 0.0870

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.30999 | val 0.48632
  Epoch 020 - train 0.29500 | val 0.48577
  Epoch 021 - train 0.32863 | val 0.48579
  Regression -> MSE: 0.000230, MAE: 0.009870, R²: 0.0035
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.28065 | val 0.36607
  Epoch 020 - train 0.32434 | val 0.37385
  Epoch 021 - train 0.28973 | val 0.37386
  Regression -> MSE: 0.000135, MAE: 0.008173, R²: -0.0026
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.31385 | val 0.37104
  Epoch 020 - train 0.31588 | val 0.37164
  Epoch 021 - train 0.30015 | val 0.37168
  Regression -> MSE: 0.000195, MAE: 0.010524, R²: -0.0366
  Directional -> Accuracy: 0.4200, MCC: -0.1391, F1: 0.2564

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.27366 | val 0.32749
  Epoch 020 - train 0.24771 | val 0.32733
  Epoch 024 - train 0.25231 | val 0.32733
  Regression -> MSE: 0.000270, MAE: 0.010784, R²: -0.0327
  Directional -> Accuracy: 0.5342, MCC: 0.0966, F1: 0.5143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.29496 | val 0.24995
  Epoch 020 - train 0.29437 | val 0.25364
  Epoch 021 - train 0.32197 | val 0.25370
  Regression -> MSE: 0.000168, MAE: 0.010398, R²: -0.0071
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.26108 | val 0.31464
  Epoch 020 - train 0.27591 | val 0.33331
  Epoch 021 - train 0.25070 | val 0.33343
  Regression -> MSE: 0.000180, MAE: 0.010353, R²: 0.0001
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.27604 | val 0.25863
  Epoch 020 - train 0.27973 | val 0.26101
  Epoch 026 - train 0.26555 | val 0.26149
  Regression -> MSE: 0.000339, MAE: 0.011804, R²: 0.0105
  Directional -> Accuracy: 0.6269, MCC: 0.2179, F1: 0.7253

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.32600 | val 0.17955
  Epoch 020 - train 0.31082 | val 0.19761
  Epoch 021 - train 0.31241 | val 0.19772
  Regression -> MSE: 0.000118, MAE: 0.008356, R²: -0.1269
  Directional -> Accuracy: 0.4651, MCC: -0.0670, F1: 0.3030

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.29635 | val 0.40426
  Epoch 020 - train 0.27576 | val 0.40883
  Epoch 021 - train 0.26993 | val 0.40906
  Regression -> MSE: 0.000222, MAE: 0.011419, R²: -0.0154
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.28871 | val 0.67070
  Epoch 020 - train 0.30891 | val 0.72217
  Epoch 021 - train 0.29952 | val 0.72222
  Regression -> MSE: 0.000082, MAE: 0.007034, R²: -0.0523
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.31345 | val 0.21035
  Epoch 020 - train 0.29424 | val 0.21645
  Epoch 021 - train 0.32170 | val 0.21647
  Regression -> MSE: 0.000309, MAE: 0.013702, R²: -0.0031
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.35301 | val 0.17285
  Epoch 020 - train 0.32839 | val 0.18492
  Epoch 021 - train 0.36863 | val 0.18535
  Regression -> MSE: 0.000252, MAE: 0.011477, R²: -0.0340
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.27218 | val 0.33150
  Epoch 020 - train 0.26434 | val 0.33426
  Epoch 024 - train 0.25975 | val 0.33482
  Regression -> MSE: 0.000082, MAE: 0.007085, R²: -0.0177
  Directional -> Accuracy: 0.5600, MCC: 0.1600, F1: 0.6598

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.29550 | val 0.33326
  Epoch 020 - train 0.31489 | val 0.34143
  Epoch 030 - train 0.31203 | val 0.34471
  Regression -> MSE: 0.000297, MAE: 0.014294, R²: 0.0326
  Directional -> Accuracy: 0.6596, MCC: 0.3440, F1: 0.6000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.29792 | val 0.33190
  Epoch 020 - train 0.31489 | val 0.34251
  Epoch 021 - train 0.31935 | val 0.34271
  Regression -> MSE: 0.000100, MAE: 0.007137, R²: -0.0151
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.33311 | val 0.38057
  Epoch 020 - train 0.31388 | val 0.39759
  Epoch 021 - train 0.32707 | val 0.39798
  Regression -> MSE: 0.000176, MAE: 0.010279, R²: -0.0269
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.29166 | val 0.33240
  Epoch 020 - train 0.27769 | val 0.33420
  Epoch 021 - train 0.27231 | val 0.33424
  Regression -> MSE: 0.000224, MAE: 0.011822, R²: -0.0050
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.30952 | val 0.32117
  Epoch 020 - train 0.30757 | val 0.31749
  Epoch 021 - train 0.29480 | val 0.31725

[I 2026-02-23 23:10:40,302] Trial 28 finished with value: -0.0114561253945094 and parameters: {'feature_set': 'finbert', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 4.301162071718581e-05, 'weight_decay': 2.1523455865138763e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.5366623951621282, 'early_stopping_min_delta': 0.009052777197557945}. Best is trial 28 with value: -0.0114561253945094.

  Epoch 020 - train 0.31483 | val 0.50847
  Epoch 021 - train 0.30260 | val 0.50847
  Regression -> MSE: 0.000237, MAE: 0.012428, R²: -0.0006
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.17450 | val 0.22468
  Epoch 020 - train 0.17671 | val 0.24405
  Epoch 025 - train 0.17730 | val 0.23915
  Regression -> MSE: 0.000256, MAE: 0.012909, R²: -0.0441
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16746 | val 0.16161
  Epoch 020 - train 0.16896 | val 0.21607
  Epoch 021 - train 0.17486 | val 0.22456
  Regression -> MSE: 0.000689, MAE: 0.019562, R²: 0.0033
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.19179 | val 0.30015
  Epoch 020 - train 0.18854 | val 0.30871
  Epoch 021 - train 0.18662 | val 0.31318
  Regression -> MSE: 0.000368, MAE: 0.015266, R²: -0.0654
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15470 | val 0.16401
  Epoch 020 - train 0.15334 | val 0.16933
  Epoch 021 - train 0.14837 | val 0.18685
  Regression -> MSE: 0.000346, MAE: 0.014443, R²: -0.0030
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.18117 | val 0.17128
  Epoch 020 - train 0.18218 | val 0.17332
  Epoch 029 - train 0.16860 | val 0.17363
  Regression -> MSE: 0.000197, MAE: 0.009903, R²: 0.0193
  Directional -> Accuracy: 0.5577, MCC: 0.2521, F1: 0.3429

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.17932 | val 0.33630
  Epoch 020 - train 0.16180 | val 0.37498
  Epoch 021 - train 0.17486 | val 0.37886
  Regression -> MSE: 0.000593, MAE: 0.018660, R²: -0.0356
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.18748 | val 0.22409
  Epoch 020 - train 0.18165 | val 0.23965
  Epoch 021 - train 0.18208 | val 0.24169
  Regression -> MSE: 0.000246, MAE: 0.012016, R²: -0.0011
  Directional -> Accuracy: 0.4857, MCC: -0.1131, F1: 0.2800

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.18473 | val 0.27689
  Epoch 020 - train 0.17040 | val 0.33762
  Epoch 021 - train 0.18562 | val 0.34812
  Regression -> MSE: 0.000644, MAE: 0.020013, R²: -0.1022
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.18048 | val 0.26751
  Epoch 020 - train 0.16964 | val 0.28995
  Epoch 021 - train 0.16628 | val 0.29029
  Regression -> MSE: 0.000338, MAE: 0.014916, R²: 0.0016
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.19145 | val 0.26673
  Epoch 020 - train 0.18146 | val 0.26975
  Epoch 021 - train 0.19211 | val 0.26577
  Regression -> MSE: 0.000247, MAE: 0.011557, R²: -0.0384
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.18087 | val 0.31607
  Epoch 020 - train 0.17184 | val 0.38906
  Epoch 021 - train 0.16139 | val 0.38661
  Regression -> MSE: 0.000306, MAE: 0.013622, R²: -0.0011
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.19607 | val 0.24269
  Epoch 020 - train 0.18031 | val 0.23971
  Epoch 021 - train 0.18624 | val 0.24325
  Regression -> MSE: 0.000673, MAE: 0.019453, R²: -0.0053
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.18619 | val 0.19212
  Epoch 020 - train 0.17529 | val 0.32158
  Epoch 021 - train 0.17004 | val 0.31531
  Regression -> MSE: 0.000154, MAE: 0.009840, R²: -0.0294
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.16944 | val 0.24229
  Epoch 020 - train 0.16898 | val 0.22969
  Epoch 030 - train 0.16715 | val 0.22767
  Epoch 035 - train 0.15587 | val 0.23062
  Regression -> MSE: 0.000217, MAE: 0.010614, R²: 0.0340
  Directional -> Accuracy: 0.5161, MCC: 0.0592, F1: 0.6591

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.18065 | val 0.40688
  Epoch 020 - train 0.17376 | val 0.45496
  Epoch 021 - train 0.17369 | val 0.45690
  Regression -> MSE: 0.000378, MAE: 0.016398, R²: -0.0060
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.20334 | val 0.20757
  Epoch 020 - train 0.19273 | val 0.21833
  Epoch 021 - train 0.18632 | val 0.21762
  Regression -> MSE: 0.000109, MAE: 0.008101, R²: -0.0205
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.18113 | val 0.34872
  Epoch 020 - train 0.17228 | val 0.39573
  Epoch 021 - train 0.16398 | val 0.39212
  Regression -> MSE: 0.000162, MAE: 0.010138, R²: -0.0110
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.17233 | val 0.18349
  Epoch 020 - train 0.17795 | val 0.20723
  Epoch 021 - train 0.17307 | val 0.20833
  Regression -> MSE: 0.000269, MAE: 0.012914, R²: -0.0022
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.17029 | val 0.23957
  Epoch 020 - train 0.16678 | val 0.24670
  Epoch 021 - train 0.15550 | val 0.24555
  Regression -> MSE: 0.000165, MAE: 0.009037, R²: -0.1197
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.18881 | val 0.27554
  Epoch 020 - train 0.17875 | val 0.26244
  Epoch 021 - train 0.17598 | val 0.26272
  Regression -> MSE: 0.000240, MAE: 0.011124, R²: -0.0611
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.18491 | val 0.21456
  Epoch 020 - train 0.17618 | val 0.21744
  Epoch 021 - train 0.18354 | val 0.21858
  Regression -> MSE: 0.000150, MAE: 0.008609, R²: -0.0095
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.17566 | val 0.22298
  Epoch 020 - train 0.16973 | val 0.24124
  Epoch 021 - train 0.17364 | val 0.24217
  Regression -> MSE: 0.000189, MAE: 0.010617, R²: -0.0666
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.20252 | val 0.21146
  Epoch 020 - train 0.18117 | val 0.21903
  Epoch 021 - train 0.18059 | val 0.22039
  Regression -> MSE: 0.000087, MAE: 0.007122, R²: -0.0347
  Directional -> Accuracy: 0.4237, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.17695 | val 0.40574
  Epoch 020 - train 0.16720 | val 0.45882
  Epoch 021 - train 0.17456 | val 0.45832
  Regression -> MSE: 0.000219, MAE: 0.011327, R²: -0.0033
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.17432 | val 0.14555
  Epoch 020 - train 0.16176 | val 0.14203
  Epoch 030 - train 0.15627 | val 0.14184
  Epoch 031 - train 0.14870 | val 0.14070
  Regression -> MSE: 0.000115, MAE: 0.008640, R²: -0.2600
  Directional -> Accuracy: 0.5439, MCC: 0.1963, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.19140 | val 0.11671
  Epoch 020 - train 0.19508 | val 0.13894
  Epoch 021 - train 0.17678 | val 0.13936
  Regression -> MSE: 0.000129, MAE: 0.009348, R²: -0.0227
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.5357

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.18918 | val 0.17850
  Epoch 020 - train 0.18876 | val 0.22501
  Epoch 021 - train 0.17466 | val 0.22352
  Regression -> MSE: 0.000250, MAE: 0.013133, R²: -0.0491
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.18855 | val 0.20658
  Epoch 020 - train 0.17969 | val 0.21486
  Epoch 029 - train 0.18300 | val 0.21854
  Regression -> MSE: 0.000188, MAE: 0.007920, R²: -0.1503
  Directional -> Accuracy: 0.5345, MCC: 0.0845, F1: 0.5263

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.19900 | val 0.14529
  Epoch 020 - train 0.18239 | val 0.14420
  Epoch 021 - train 0.19465 | val 0.14688
  Regression -> MSE: 0.000239, MAE: 0.012087, R²: -0.0179
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.19103 | val 0.26611
  Epoch 020 - train 0.16844 | val 0.29441
  Epoch 021 - train 0.18986 | val 0.29557
  Regression -> MSE: 0.000250, MAE: 0.010420, R²: -0.0004
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18471 | val 0.24611
  Epoch 020 - train 0.18815 | val 0.26627
  Epoch 021 - train 0.19032 | val 0.26790
  Regression -> MSE: 0.000133, MAE: 0.008191, R²: -0.0013
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.17665 | val 0.23072
  Epoch 020 - train 0.18432 | val 0.23712
  Epoch 021 - train 0.17430 | val 0.23849
  Regression -> MSE: 0.000189, MAE: 0.010508, R²: -0.0008
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.16890 | val 0.21251
  Epoch 020 - train 0.15400 | val 0.21574
  Epoch 021 - train 0.14972 | val 0.21805
  Regression -> MSE: 0.000265, MAE: 0.010517, R²: -0.0269
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.17282 | val 0.16134
  Epoch 020 - train 0.15217 | val 0.16123
  Epoch 021 - train 0.16128 | val 0.16152
  Regression -> MSE: 0.000163, MAE: 0.010169, R²: -0.0002
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.16147 | val 0.19338
  Epoch 020 - train 0.15707 | val 0.24096
  Epoch 021 - train 0.16191 | val 0.24036
  Regression -> MSE: 0.000185, MAE: 0.010552, R²: -0.0102
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.17495 | val 0.16633
  Epoch 020 - train 0.16114 | val 0.16780
  Epoch 021 - train 0.16057 | val 0.17121
  Regression -> MSE: 0.000352, MAE: 0.011959, R²: -0.0097
  Directional -> Accuracy: 0.5735, MCC: 0.0000, F1: 0.7290

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.20283 | val 0.12270
  Epoch 020 - train 0.18629 | val 0.12505
  Epoch 021 - train 0.18201 | val 0.12515
  Regression -> MSE: 0.000124, MAE: 0.008349, R²: -0.1975
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.18708 | val 0.24978
  Epoch 020 - train 0.18460 | val 0.25517
  Epoch 021 - train 0.17448 | val 0.25695
  Regression -> MSE: 0.000218, MAE: 0.011271, R²: -0.0114
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.17844 | val 0.33701
  Epoch 020 - train 0.17001 | val 0.38223
  Epoch 021 - train 0.16341 | val 0.38489
  Regression -> MSE: 0.000089, MAE: 0.007409, R²: -0.1184
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.18224 | val 0.14418
  Epoch 020 - train 0.18294 | val 0.14887
  Epoch 021 - train 0.18419 | val 0.14877
  Regression -> MSE: 0.000332, MAE: 0.014723, R²: -0.0131
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.20130 | val 0.14290
  Epoch 020 - train 0.19179 | val 0.14916
  Epoch 021 - train 0.19993 | val 0.15036
  Regression -> MSE: 0.000257, MAE: 0.011239, R²: -0.0805
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.17494 | val 0.23940
  Epoch 020 - train 0.17137 | val 0.24747
  Epoch 021 - train 0.16711 | val 0.25001
  Regression -> MSE: 0.000080, MAE: 0.007043, R²: -0.0034
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.19652 | val 0.20830
  Epoch 020 - train 0.18393 | val 0.20176
  Epoch 030 - train 0.19363 | val 0.20132
  Regression -> MSE: 0.000362, MAE: 0.015362, R²: -0.0072
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.18034 | val 0.23135
  Epoch 020 - train 0.17176 | val 0.23758
  Epoch 021 - train 0.17809 | val 0.23834
  Regression -> MSE: 0.000100, MAE: 0.007109, R²: -0.0336
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17806 | val 0.24976
  Epoch 020 - train 0.18510 | val 0.31994
  Epoch 021 - train 0.18698 | val 0.32341
  Regression -> MSE: 0.000181, MAE: 0.009878, R²: -0.0023
  Directional -> Accuracy: 0.6341, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.18314 | val 0.23258
  Epoch 020 - train 0.16782 | val 0.25630
  Epoch 021 - train 0.16977 | val 0.25914
  Regression -> MSE: 0.000219, MAE: 0.011632, R²: 0.0006
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...

[I 2026-02-23 23:13:08,343] Trial 29 finished with value: -0.01149023243689406 and parameters: {'feature_set': 'finbert', 'model_type': 'BiLSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.00017572994038674304, 'weight_decay': 0.00042310333390775987, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.29917722837041855, 'early_stopping_min_delta': 0.009230101034037836}. Best is trial 28 with value: -0.0114561253945094.

  Epoch 020 - train 0.18141 | val 0.26191
  Epoch 021 - train 0.18543 | val 0.26246
  Regression -> MSE: 0.000242, MAE: 0.012280, R²: -0.0339
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14888 | val 0.20741
  Epoch 020 - train 0.14052 | val 0.20951
  Epoch 021 - train 0.15275 | val 0.21024
  Regression -> MSE: 0.000246, MAE: 0.012517, R²: -0.0017
  Directional -> Accuracy: 0.5641, MCC: 0.0776, F1: 0.2273

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16017 | val 0.15120
  Epoch 020 - train 0.14768 | val 0.21336
  Epoch 021 - train 0.14327 | val 0.20396
  Regression -> MSE: 0.000698, MAE: 0.019728, R²: -0.0092
  Directional -> Accuracy: 0.5319, MCC: -0.0023, F1: 0.6562

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.17021 | val 0.26991
  Epoch 020 - train 0.16765 | val 0.26777
  Epoch 021 - train 0.15517 | val 0.27033
  Regression -> MSE: 0.000352, MAE: 0.015098, R²: -0.0180
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14027 | val 0.26163
  Epoch 020 - train 0.13806 | val 0.23616
  Epoch 021 - train 0.12962 | val 0.22017
  Regression -> MSE: 0.000372, MAE: 0.014824, R²: -0.0795
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.17134 | val 0.15351
  Epoch 020 - train 0.15094 | val 0.15744
  Epoch 021 - train 0.14640 | val 0.15745
  Regression -> MSE: 0.000202, MAE: 0.009969, R²: -0.0091
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.14538 | val 0.30430
  Epoch 020 - train 0.14653 | val 0.31521
  Epoch 021 - train 0.13890 | val 0.31829
  Regression -> MSE: 0.000580, MAE: 0.018424, R²: -0.0136
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16628 | val 0.21564
  Epoch 020 - train 0.16068 | val 0.23135
  Epoch 021 - train 0.16049 | val 0.22787
  Regression -> MSE: 0.000246, MAE: 0.011991, R²: -0.0007
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.16276 | val 0.21809
  Epoch 020 - train 0.15521 | val 0.33394
  Epoch 021 - train 0.16227 | val 0.35840
  Regression -> MSE: 0.000590, MAE: 0.018904, R²: -0.0095
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15329 | val 0.25786
  Epoch 020 - train 0.14880 | val 0.26252
  Epoch 021 - train 0.13672 | val 0.26250
  Regression -> MSE: 0.000340, MAE: 0.015208, R²: -0.0061
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16241 | val 0.29951
  Epoch 020 - train 0.14726 | val 0.27784
  Epoch 021 - train 0.14971 | val 0.27662
  Regression -> MSE: 0.000241, MAE: 0.011540, R²: -0.0116
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15905 | val 0.26869
  Epoch 020 - train 0.14184 | val 0.29418
  Epoch 021 - train 0.13887 | val 0.29762
  Regression -> MSE: 0.000307, MAE: 0.013546, R²: -0.0031
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.16395 | val 0.20567
  Epoch 020 - train 0.15123 | val 0.21807
  Epoch 021 - train 0.15130 | val 0.21570
  Regression -> MSE: 0.000669, MAE: 0.019385, R²: 0.0007
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17057 | val 0.17840
  Epoch 020 - train 0.14894 | val 0.34745
  Epoch 021 - train 0.15681 | val 0.34491
  Regression -> MSE: 0.000154, MAE: 0.009831, R²: -0.0277
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14792 | val 0.21078
  Epoch 020 - train 0.14335 | val 0.23154
  Epoch 021 - train 0.13823 | val 0.23398
  Regression -> MSE: 0.000226, MAE: 0.010781, R²: -0.0062
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16117 | val 0.41911
  Epoch 020 - train 0.15007 | val 0.53863
  Epoch 021 - train 0.14792 | val 0.53385
  Regression -> MSE: 0.000376, MAE: 0.016555, R²: -0.0005
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16357 | val 0.19306
  Epoch 020 - train 0.16139 | val 0.20180
  Epoch 021 - train 0.17008 | val 0.19860
  Regression -> MSE: 0.000107, MAE: 0.007980, R²: -0.0037
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15875 | val 0.29315
  Epoch 020 - train 0.14402 | val 0.36552
  Epoch 021 - train 0.15158 | val 0.36396
  Regression -> MSE: 0.000162, MAE: 0.009721, R²: -0.0121
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15114 | val 0.16301
  Epoch 020 - train 0.14771 | val 0.21877
  Epoch 021 - train 0.13960 | val 0.23148
  Regression -> MSE: 0.000274, MAE: 0.013151, R²: -0.0184
  Directional -> Accuracy: 0.4156, MCC: -0.0734, F1: 0.3284

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.15138 | val 0.22138
  Epoch 020 - train 0.13713 | val 0.21646
  Epoch 021 - train 0.14736 | val 0.21616
  Regression -> MSE: 0.000153, MAE: 0.008653, R²: -0.0392
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16267 | val 0.24101
  Epoch 020 - train 0.14931 | val 0.23874
  Epoch 021 - train 0.15207 | val 0.23885
  Regression -> MSE: 0.000228, MAE: 0.010940, R²: -0.0075
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15967 | val 0.19186
  Epoch 020 - train 0.15112 | val 0.20802
  Epoch 021 - train 0.14526 | val 0.21115
  Regression -> MSE: 0.000151, MAE: 0.008706, R²: -0.0187
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15238 | val 0.19919
  Epoch 020 - train 0.14462 | val 0.19942
  Epoch 021 - train 0.14134 | val 0.19917
  Regression -> MSE: 0.000180, MAE: 0.010600, R²: -0.0148
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16390 | val 0.20431
  Epoch 020 - train 0.15398 | val 0.22150
  Epoch 021 - train 0.15646 | val 0.21957
  Regression -> MSE: 0.000084, MAE: 0.006960, R²: -0.0021
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15848 | val 0.34258
  Epoch 020 - train 0.15261 | val 0.36553
  Epoch 021 - train 0.15156 | val 0.36548
  Regression -> MSE: 0.000226, MAE: 0.011289, R²: -0.0343
  Directional -> Accuracy: 0.5224, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14459 | val 0.12476
  Epoch 020 - train 0.13899 | val 0.12732
  Epoch 028 - train 0.13589 | val 0.12964
  Regression -> MSE: 0.000100, MAE: 0.008162, R²: -0.0915
  Directional -> Accuracy: 0.5439, MCC: 0.1963, F1: 0.4091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16105 | val 0.10239
  Epoch 020 - train 0.13210 | val 0.13266
  Epoch 021 - train 0.13894 | val 0.14221
  Regression -> MSE: 0.000138, MAE: 0.009666, R²: -0.0960
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.17261 | val 0.15226
  Epoch 020 - train 0.15987 | val 0.18316
  Epoch 021 - train 0.16014 | val 0.18579
  Regression -> MSE: 0.000242, MAE: 0.012917, R²: -0.0192
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15869 | val 0.20258
  Epoch 020 - train 0.15057 | val 0.21153
  Epoch 021 - train 0.14471 | val 0.21244
  Regression -> MSE: 0.000176, MAE: 0.007806, R²: -0.0719
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16196 | val 0.13087
  Epoch 020 - train 0.15958 | val 0.13449
  Epoch 021 - train 0.15510 | val 0.13462
  Regression -> MSE: 0.000235, MAE: 0.011921, R²: -0.0019
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14914 | val 0.25557
  Epoch 020 - train 0.15689 | val 0.25786
  Epoch 021 - train 0.15375 | val 0.25743
  Regression -> MSE: 0.000252, MAE: 0.010623, R²: -0.0063
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16544 | val 0.21628
  Epoch 020 - train 0.15224 | val 0.22773
  Epoch 021 - train 0.15635 | val 0.22906
  Regression -> MSE: 0.000134, MAE: 0.008152, R²: -0.0037
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15922 | val 0.20547
  Epoch 020 - train 0.15475 | val 0.21806
  Epoch 030 - train 0.14413 | val 0.20974
  Regression -> MSE: 0.000189, MAE: 0.010525, R²: -0.0046
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14492 | val 0.18942
  Epoch 020 - train 0.13489 | val 0.19788
  Epoch 021 - train 0.13816 | val 0.19984
  Regression -> MSE: 0.000270, MAE: 0.010627, R²: -0.0432
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15192 | val 0.14684
  Epoch 020 - train 0.13379 | val 0.15297
  Epoch 021 - train 0.14119 | val 0.15278
  Regression -> MSE: 0.000163, MAE: 0.010162, R²: -0.0007
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14926 | val 0.17933
  Epoch 020 - train 0.14225 | val 0.21752
  Epoch 021 - train 0.13596 | val 0.21600
  Regression -> MSE: 0.000193, MAE: 0.010851, R²: -0.0575
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14808 | val 0.14793
  Epoch 020 - train 0.13719 | val 0.16336
  Epoch 021 - train 0.14235 | val 0.16547
  Regression -> MSE: 0.000349, MAE: 0.012100, R²: 0.0005
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18283 | val 0.11396
  Epoch 020 - train 0.16023 | val 0.11229
  Epoch 021 - train 0.15720 | val 0.11221
  Regression -> MSE: 0.000126, MAE: 0.008389, R²: -0.2141
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16671 | val 0.25005
  Epoch 020 - train 0.14993 | val 0.26715
  Epoch 021 - train 0.15283 | val 0.27050
  Regression -> MSE: 0.000215, MAE: 0.011139, R²: 0.0006
  Directional -> Accuracy: 0.5345, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15251 | val 0.30186
  Epoch 020 - train 0.15332 | val 0.36339
  Epoch 021 - train 0.15359 | val 0.36448
  Regression -> MSE: 0.000084, MAE: 0.007202, R²: -0.0618
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15569 | val 0.14351
  Epoch 020 - train 0.15712 | val 0.13932
  Epoch 030 - train 0.14811 | val 0.13713
  Epoch 035 - train 0.14395 | val 0.13932
  Regression -> MSE: 0.000413, MAE: 0.017510, R²: -0.2587
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.18816 | val 0.10988
  Epoch 020 - train 0.16487 | val 0.11420
  Epoch 021 - train 0.15172 | val 0.11482
  Regression -> MSE: 0.000242, MAE: 0.011289, R²: -0.0162
  Directional -> Accuracy: 0.6154, MCC: 0.2381, F1: 0.6154

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15228 | val 0.23596
  Epoch 020 - train 0.14854 | val 0.24263
  Epoch 021 - train 0.14187 | val 0.24678
  Regression -> MSE: 0.000081, MAE: 0.007051, R²: -0.0122
  Directional -> Accuracy: 0.5395, MCC: 0.1592, F1: 0.1860

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.15810 | val 0.19478
  Epoch 020 - train 0.15937 | val 0.20674
  Epoch 021 - train 0.14770 | val 0.20962
  Regression -> MSE: 0.000367, MAE: 0.015342, R²: -0.0190
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.15780 | val 0.21928
  Epoch 020 - train 0.14968 | val 0.21337
  Epoch 021 - train 0.14272 | val 0.21345
  Regression -> MSE: 0.000105, MAE: 0.007149, R²: -0.0835
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17848 | val 0.23535
  Epoch 020 - train 0.16204 | val 0.27386
  Epoch 021 - train 0.15482 | val 0.27412
  Regression -> MSE: 0.000188, MAE: 0.010781, R²: -0.0414
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14152 | val 0.24887
  Epoch 020 - train 0.14013 | val 0.31101
  Epoch 021 - train 0.14774 | val 0.30681
  Regression -> MSE: 0.000221, MAE: 0.011673, R²: -0.0062
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.16169 | val 0.19092

[I 2026-02-23 23:15:19,889] Trial 30 finished with value: -0.011543027724229642 and parameters: {'feature_set': 'finbert', 'model_type': 'BiLSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.00019663929550787148, 'weight_decay': 0.0003991076651281229, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.26598424690901296, 'early_stopping_min_delta': 0.009229905858571918}. Best is trial 28 with value: -0.0114561253945094.

  Epoch 020 - train 0.15772 | val 0.30623
  Epoch 021 - train 0.15496 | val 0.30737
  Regression -> MSE: 0.000238, MAE: 0.012251, R²: -0.0172
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.22787 | val 0.29714
  Epoch 020 - train 0.22596 | val 0.29773
  Epoch 021 - train 0.22622 | val 0.29856
  Regression -> MSE: 0.000251, MAE: 0.012743, R²: -0.0189
  Directional -> Accuracy: 0.4430, MCC: 0.0000, F1: 0.6140

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.23649 | val 0.20322
  Epoch 020 - train 0.24956 | val 0.20479
  Epoch 021 - train 0.23196 | val 0.20722
  Regression -> MSE: 0.000699, MAE: 0.019704, R²: -0.0320
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.25702 | val 0.38802
  Epoch 020 - train 0.24210 | val 0.38110
  Epoch 030 - train 0.21641 | val 0.38797
  Epoch 032 - train 0.23909 | val 0.38894
  Regression -> MSE: 0.000362, MAE: 0.015306, R²: -0.0422
  Directional -> Accuracy: 0.4082, MCC: -0.2233, F1: 0.0645

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.19491 | val 0.18494
  Epoch 020 - train 0.19716 | val 0.18732
  Epoch 021 - train 0.19662 | val 0.18747
  Regression -> MSE: 0.000369, MAE: 0.014871, R²: -0.0389
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.22701 | val 0.20388
  Epoch 020 - train 0.23102 | val 0.20062
  Epoch 030 - train 0.22739 | val 0.19973
  Regression -> MSE: 0.000194, MAE: 0.009660, R²: 0.0229
  Directional -> Accuracy: 0.6981, MCC: 0.4040, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.22366 | val 0.45063
  Epoch 020 - train 0.22387 | val 0.44732
  Epoch 021 - train 0.22301 | val 0.44597
  Regression -> MSE: 0.000507, MAE: 0.017441, R²: -0.0216
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.25604 | val 0.28277
  Epoch 020 - train 0.23248 | val 0.29315
  Epoch 021 - train 0.23519 | val 0.29249
  Regression -> MSE: 0.000258, MAE: 0.012634, R²: -0.0052
  Directional -> Accuracy: 0.4085, MCC: 0.0000, F1: 0.5800

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.24264 | val 0.28285
  Epoch 020 - train 0.22661 | val 0.28258
  Epoch 021 - train 0.24097 | val 0.28307
  Regression -> MSE: 0.000596, MAE: 0.019218, R²: -0.0507
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.24957 | val 0.30621
  Epoch 020 - train 0.25273 | val 0.31673
  Epoch 021 - train 0.24619 | val 0.31736
  Regression -> MSE: 0.000395, MAE: 0.015699, R²: -0.0266
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.24354 | val 0.32634
  Epoch 020 - train 0.22825 | val 0.33371
  Epoch 021 - train 0.24534 | val 0.33433
  Regression -> MSE: 0.000239, MAE: 0.011658, R²: -0.0027
  Directional -> Accuracy: 0.4583, MCC: -0.0075, F1: 0.5517

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.22074 | val 0.38019
  Epoch 020 - train 0.21098 | val 0.43519
  Epoch 021 - train 0.20848 | val 0.43392
  Regression -> MSE: 0.000307, MAE: 0.013628, R²: 0.0003
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.25515 | val 0.26824
  Epoch 020 - train 0.24260 | val 0.28399
  Epoch 021 - train 0.23839 | val 0.28391
  Regression -> MSE: 0.000664, MAE: 0.019446, R²: -0.0083
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.23601 | val 0.24720
  Epoch 020 - train 0.23954 | val 0.31362
  Epoch 021 - train 0.22489 | val 0.31435
  Regression -> MSE: 0.000147, MAE: 0.009461, R²: -0.0013
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.24406 | val 0.29451
  Epoch 020 - train 0.21188 | val 0.29119
  Epoch 030 - train 0.20994 | val 0.28977
  Epoch 032 - train 0.21906 | val 0.29038
  Regression -> MSE: 0.000224, MAE: 0.011110, R²: 0.0019
  Directional -> Accuracy: 0.5079, MCC: 0.0261, F1: 0.5974

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.22506 | val 0.48695
  Epoch 020 - train 0.22775 | val 0.56583
  Epoch 021 - train 0.22832 | val 0.56368
  Regression -> MSE: 0.000384, MAE: 0.016676, R²: -0.0033
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.25543 | val 0.25824
  Epoch 020 - train 0.24249 | val 0.26729
  Epoch 021 - train 0.24077 | val 0.26698
  Regression -> MSE: 0.000106, MAE: 0.007987, R²: -0.0083
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.22186 | val 0.39817
  Epoch 020 - train 0.22372 | val 0.43120
  Epoch 021 - train 0.21823 | val 0.43180
  Regression -> MSE: 0.000159, MAE: 0.009673, R²: -0.0094
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.23031 | val 0.20249
  Epoch 020 - train 0.22616 | val 0.20388
  Epoch 021 - train 0.22073 | val 0.20496
  Regression -> MSE: 0.000272, MAE: 0.013042, R²: -0.0022
  Directional -> Accuracy: 0.6026, MCC: 0.0000, F1: 0.7520

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.21574 | val 0.29550
  Epoch 020 - train 0.21333 | val 0.29960
  Epoch 021 - train 0.21515 | val 0.30097
  Regression -> MSE: 0.000170, MAE: 0.009213, R²: -0.0957
  Directional -> Accuracy: 0.4179, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.24735 | val 0.38071
  Epoch 020 - train 0.24443 | val 0.36832
  Epoch 021 - train 0.25041 | val 0.36923
  Regression -> MSE: 0.000253, MAE: 0.011452, R²: -0.0916
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.24047 | val 0.30589
  Epoch 020 - train 0.24796 | val 0.37035
  Epoch 021 - train 0.23944 | val 0.36881
  Regression -> MSE: 0.000156, MAE: 0.009012, R²: -0.0505
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.22802 | val 0.26229
  Epoch 020 - train 0.22623 | val 0.26551
  Epoch 021 - train 0.21294 | val 0.26583
  Regression -> MSE: 0.000182, MAE: 0.011044, R²: -0.0005
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.24629 | val 0.27249
  Epoch 020 - train 0.22907 | val 0.28401
  Epoch 021 - train 0.25551 | val 0.28453
  Regression -> MSE: 0.000088, MAE: 0.007201, R²: -0.0676
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.23996 | val 0.33490
  Epoch 020 - train 0.22860 | val 0.35692
  Epoch 021 - train 0.21076 | val 0.35900
  Regression -> MSE: 0.000219, MAE: 0.011152, R²: -0.0189
  Directional -> Accuracy: 0.5147, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.20314 | val 0.17449
  Epoch 020 - train 0.22443 | val 0.16802
  Epoch 030 - train 0.20262 | val 0.16560
  Regression -> MSE: 0.000090, MAE: 0.007855, R²: -0.0022
  Directional -> Accuracy: 0.6207, MCC: 0.2630, F1: 0.7381

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28448 | val 0.12604
  Epoch 020 - train 0.27276 | val 0.12598
  Epoch 021 - train 0.24792 | val 0.12692
  Regression -> MSE: 0.000127, MAE: 0.009308, R²: -0.0158
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.23990 | val 0.14399
  Epoch 020 - train 0.23855 | val 0.14314
  Epoch 021 - train 0.23632 | val 0.14300
  Regression -> MSE: 0.000313, MAE: 0.014091, R²: -0.0737
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.24662 | val 0.27151
  Epoch 020 - train 0.22646 | val 0.27962
  Epoch 021 - train 0.22702 | val 0.28017
  Regression -> MSE: 0.000168, MAE: 0.007635, R²: -0.0412
  Directional -> Accuracy: 0.5593, MCC: 0.0000, F1: 0.7174

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.24531 | val 0.21767
  Epoch 020 - train 0.21849 | val 0.22247
  Epoch 021 - train 0.24358 | val 0.22398
  Regression -> MSE: 0.000231, MAE: 0.011851, R²: -0.0017
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.23822 | val 0.28945
  Epoch 020 - train 0.22501 | val 0.29293
  Epoch 021 - train 0.22943 | val 0.29292
  Regression -> MSE: 0.000259, MAE: 0.010736, R²: 0.0008
  Directional -> Accuracy: 0.5217, MCC: 0.0605, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.23170 | val 0.29575
  Epoch 020 - train 0.27100 | val 0.31888
  Epoch 021 - train 0.24932 | val 0.32091
  Regression -> MSE: 0.000142, MAE: 0.008559, R²: -0.0132
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.25744 | val 0.28950
  Epoch 020 - train 0.24039 | val 0.28464
  Epoch 021 - train 0.24603 | val 0.28486
  Regression -> MSE: 0.000194, MAE: 0.010581, R²: -0.0453
  Directional -> Accuracy: 0.4808, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.22246 | val 0.26885
  Epoch 020 - train 0.20158 | val 0.26906
  Epoch 021 - train 0.20381 | val 0.27011
  Regression -> MSE: 0.000266, MAE: 0.010600, R²: -0.0189
  Directional -> Accuracy: 0.5600, MCC: 0.0000, F1: 0.7179

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.21889 | val 0.24406
  Epoch 020 - train 0.21887 | val 0.23991
  Epoch 021 - train 0.22956 | val 0.24073
  Regression -> MSE: 0.000163, MAE: 0.010128, R²: -0.0043
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.22527 | val 0.20203
  Epoch 020 - train 0.21314 | val 0.21841
  Epoch 021 - train 0.21125 | val 0.22027
  Regression -> MSE: 0.000214, MAE: 0.011055, R²: -0.0005
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.22184 | val 0.21667
  Epoch 020 - train 0.22558 | val 0.21735
  Epoch 021 - train 0.21892 | val 0.21711
  Regression -> MSE: 0.000356, MAE: 0.012708, R²: -0.0353
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.27705 | val 0.16198
  Epoch 020 - train 0.25804 | val 0.19631
  Epoch 021 - train 0.25809 | val 0.19780
  Regression -> MSE: 0.000124, MAE: 0.008293, R²: -0.2221
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.24182 | val 0.29928
  Epoch 020 - train 0.23239 | val 0.31174
  Epoch 021 - train 0.23508 | val 0.31298
  Regression -> MSE: 0.000212, MAE: 0.011025, R²: -0.0020
  Directional -> Accuracy: 0.5254, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.23037 | val 0.41008
  Epoch 020 - train 0.23694 | val 0.44867
  Epoch 021 - train 0.23207 | val 0.44943
  Regression -> MSE: 0.000092, MAE: 0.007555, R²: -0.1572
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.23302 | val 0.19995
  Epoch 020 - train 0.22527 | val 0.18948
  Epoch 030 - train 0.22171 | val 0.18986
  Epoch 034 - train 0.21632 | val 0.18903
  Regression -> MSE: 0.000325, MAE: 0.014537, R²: -0.0366
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.25073 | val 0.14858
  Epoch 020 - train 0.24315 | val 0.15237
  Epoch 021 - train 0.23738 | val 0.15309
  Regression -> MSE: 0.000235, MAE: 0.011010, R²: -0.0305
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.6774

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.23091 | val 0.27942
  Epoch 020 - train 0.21700 | val 0.27921
  Epoch 021 - train 0.22207 | val 0.27939
  Regression -> MSE: 0.000086, MAE: 0.007184, R²: -0.0566
  Directional -> Accuracy: 0.4935, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.25026 | val 0.23947
  Epoch 020 - train 0.23101 | val 0.26979
  Epoch 021 - train 0.25062 | val 0.27117
  Regression -> MSE: 0.000370, MAE: 0.015597, R²: 0.0005
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.23867 | val 0.24685
  Epoch 020 - train 0.24918 | val 0.23002
  Epoch 030 - train 0.21333 | val 0.23223
  Epoch 039 - train 0.23098 | val 0.23452
  Regression -> MSE: 0.000095, MAE: 0.007410, R²: -0.0014
  Directional -> Accuracy: 0.4894, MCC: 0.0512, F1: 0.4000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.24169 | val 0.30655
  Epoch 020 - train 0.24365 | val 0.35020
  Epoch 021 - train 0.25064 | val 0.35148
  Regression -> MSE: 0.000192, MAE: 0.010097, R²: -0.0038
  Directional -> Accuracy: 0.6429, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.21702 | val 0.25517
  Epoch 020 - train 0.22212 | val 0.24789
  Epoch 021 - train 0.22601 | val 0.24737
  Regression -> MSE: 0.000222, MAE: 0.011700, R²: -0.0240

[I 2026-02-23 23:16:43,516] Trial 31 finished with value: -0.011545512883220664 and parameters: {'feature_set': 'finbert', 'model_type': 'BiLSTM', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 3.296594760970239e-05, 'weight_decay': 0.00013481767169278664, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.39801399972271306, 'early_stopping_min_delta': 0.009334830370175698}. Best is trial 28 with value: -0.0114561253945094.

  Epoch 020 - train 0.24062 | val 0.36184
  Epoch 021 - train 0.22968 | val 0.36169
  Regression -> MSE: 0.000231, MAE: 0.012061, R²: -0.0037
  Directional -> Accuracy: 0.5238, MCC: 0.0086, F1: 0.0625

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14861 | val 0.19356
  Epoch 020 - train 0.14349 | val 0.19999
  Epoch 030 - train 0.13353 | val 0.19583
  Epoch 031 - train 0.13597 | val 0.19811
  Regression -> MSE: 0.000253, MAE: 0.012681, R²: -0.0309
  Directional -> Accuracy: 0.5256, MCC: 0.1166, F1: 0.6022

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.15518 | val 0.13949
  Epoch 020 - train 0.15271 | val 0.14023
  Epoch 021 - train 0.14430 | val 0.13800
  Regression -> MSE: 0.000699, MAE: 0.019748, R²: -0.0114
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16769 | val 0.25384
  Epoch 020 - train 0.15413 | val 0.23987
  Epoch 030 - train 0.15492 | val 0.24690
  Epoch 039 - train 0.14221 | val 0.26725
  Regression -> MSE: 0.000382, MAE: 0.015130, R²: -0.1062
  Directional -> Accuracy: 0.5000, MCC: 0.0948, F1: 0.2500

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13084 | val 0.15448
  Epoch 020 - train 0.12763 | val 0.14211
  Epoch 021 - train 0.12298 | val 0.14493
  Regression -> MSE: 0.000360, MAE: 0.014625, R²: -0.0427
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15069 | val 0.14485
  Epoch 020 - train 0.13715 | val 0.14866
  Epoch 021 - train 0.13654 | val 0.14684
  Regression -> MSE: 0.000200, MAE: 0.009966, R²: 0.0009
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15100 | val 0.28943
  Epoch 020 - train 0.13540 | val 0.36258
  Epoch 021 - train 0.14053 | val 0.37994
  Regression -> MSE: 0.000587, MAE: 0.018541, R²: -0.0258
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.17081 | val 0.22863
  Epoch 020 - train 0.14608 | val 0.31096
  Epoch 021 - train 0.15353 | val 0.28612
  Regression -> MSE: 0.000246, MAE: 0.012065, R²: -0.0015
  Directional -> Accuracy: 0.4000, MCC: -0.0733, F1: 0.5333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15472 | val 0.25240
  Epoch 020 - train 0.13672 | val 0.27202
  Epoch 021 - train 0.12861 | val 0.27912
  Regression -> MSE: 0.000651, MAE: 0.020102, R²: -0.1137
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15524 | val 0.22603
  Epoch 020 - train 0.14146 | val 0.22299
  Epoch 021 - train 0.12738 | val 0.22420
  Regression -> MSE: 0.000339, MAE: 0.014792, R²: -0.0028
  Directional -> Accuracy: 0.6190, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16008 | val 0.21066
  Epoch 020 - train 0.13752 | val 0.24436
  Epoch 021 - train 0.13924 | val 0.24585
  Regression -> MSE: 0.000245, MAE: 0.011542, R²: -0.0281
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13861 | val 0.29967
  Epoch 020 - train 0.13789 | val 0.43619
  Epoch 021 - train 0.13200 | val 0.42244
  Regression -> MSE: 0.000316, MAE: 0.013535, R²: -0.0333
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.16240 | val 0.19838
  Epoch 020 - train 0.15439 | val 0.23913
  Epoch 021 - train 0.15211 | val 0.22966
  Regression -> MSE: 0.000668, MAE: 0.019422, R²: 0.0016
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.15626 | val 0.18576
  Epoch 020 - train 0.15473 | val 0.30500
  Epoch 021 - train 0.14867 | val 0.26761
  Regression -> MSE: 0.000150, MAE: 0.009496, R²: -0.0009
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14155 | val 0.19561
  Epoch 020 - train 0.13247 | val 0.20045
  Epoch 021 - train 0.13732 | val 0.20253
  Regression -> MSE: 0.000228, MAE: 0.010845, R²: -0.0131
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15634 | val 0.36130
  Epoch 020 - train 0.14615 | val 0.38243
  Epoch 021 - train 0.13533 | val 0.39634
  Regression -> MSE: 0.000379, MAE: 0.016354, R²: -0.0078
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15868 | val 0.17587
  Epoch 020 - train 0.15309 | val 0.19699
  Epoch 021 - train 0.14952 | val 0.20460
  Regression -> MSE: 0.000106, MAE: 0.007869, R²: 0.0032
  Directional -> Accuracy: 0.5493, MCC: 0.1283, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15137 | val 0.32108
  Epoch 020 - train 0.14735 | val 0.33123
  Epoch 021 - train 0.14702 | val 0.33192
  Regression -> MSE: 0.000164, MAE: 0.010271, R²: -0.0219
  Directional -> Accuracy: 0.4667, MCC: 0.1078, F1: 0.3333

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15651 | val 0.20061
  Epoch 020 - train 0.14463 | val 0.23421
  Epoch 021 - train 0.13230 | val 0.22812
  Regression -> MSE: 0.000281, MAE: 0.013514, R²: -0.0474
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14380 | val 0.20180
  Epoch 020 - train 0.13642 | val 0.19783
  Epoch 029 - train 0.13377 | val 0.20143
  Regression -> MSE: 0.000172, MAE: 0.009250, R²: -0.1683
  Directional -> Accuracy: 0.4545, MCC: -0.0382, F1: 0.4194

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15422 | val 0.21964
  Epoch 020 - train 0.14840 | val 0.22433
  Epoch 021 - train 0.15030 | val 0.22090
  Regression -> MSE: 0.000231, MAE: 0.010919, R²: -0.0179
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16049 | val 0.18530
  Epoch 020 - train 0.14041 | val 0.20406
  Epoch 021 - train 0.13785 | val 0.20030
  Regression -> MSE: 0.000154, MAE: 0.008827, R²: -0.0357
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15373 | val 0.19881
  Epoch 020 - train 0.14499 | val 0.19333
  Epoch 021 - train 0.13873 | val 0.19495
  Regression -> MSE: 0.000190, MAE: 0.010620, R²: -0.0729
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15754 | val 0.21711
  Epoch 020 - train 0.14836 | val 0.27832
  Epoch 021 - train 0.13981 | val 0.26191
  Regression -> MSE: 0.000084, MAE: 0.006925, R²: -0.0003
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14870 | val 0.21655
  Epoch 020 - train 0.13376 | val 0.20685
  Epoch 021 - train 0.13792 | val 0.20783
  Regression -> MSE: 0.000219, MAE: 0.011298, R²: -0.0034
  Directional -> Accuracy: 0.5672, MCC: 0.1273, F1: 0.4912

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13248 | val 0.12225
  Epoch 020 - train 0.12556 | val 0.12360
  Epoch 028 - train 0.12268 | val 0.12282
  Regression -> MSE: 0.000101, MAE: 0.008336, R²: -0.0987
  Directional -> Accuracy: 0.4035, MCC: -0.1527, F1: 0.2609

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14715 | val 0.09924
  Epoch 020 - train 0.14523 | val 0.12823
  Epoch 021 - train 0.15141 | val 0.13494
  Regression -> MSE: 0.000130, MAE: 0.009420, R²: -0.0357
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16394 | val 0.16200
  Epoch 020 - train 0.16495 | val 0.19419
  Epoch 021 - train 0.15559 | val 0.23478
  Regression -> MSE: 0.000238, MAE: 0.012737, R²: -0.0006
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15102 | val 0.18296
  Epoch 020 - train 0.15023 | val 0.19701
  Epoch 021 - train 0.14007 | val 0.19671
  Regression -> MSE: 0.000178, MAE: 0.007850, R²: -0.0879
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16405 | val 0.12609
  Epoch 020 - train 0.16069 | val 0.13252
  Epoch 021 - train 0.14276 | val 0.13528
  Regression -> MSE: 0.000237, MAE: 0.011992, R²: -0.0095
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.15533 | val 0.23064
  Epoch 020 - train 0.14683 | val 0.24648
  Epoch 021 - train 0.13828 | val 0.24566
  Regression -> MSE: 0.000250, MAE: 0.010469, R²: -0.0002
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15085 | val 0.21527
  Epoch 020 - train 0.16317 | val 0.25432
  Epoch 021 - train 0.15594 | val 0.26636
  Regression -> MSE: 0.000136, MAE: 0.008350, R²: -0.0217
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.16901 | val 0.19382
  Epoch 020 - train 0.14833 | val 0.20532
  Epoch 021 - train 0.13627 | val 0.20542
  Regression -> MSE: 0.000188, MAE: 0.010508, R²: -0.0003
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14394 | val 0.18351
  Epoch 020 - train 0.12736 | val 0.19650
  Epoch 021 - train 0.12896 | val 0.19671
  Regression -> MSE: 0.000263, MAE: 0.010429, R²: -0.0163
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15657 | val 0.14876
  Epoch 020 - train 0.14403 | val 0.15481
  Epoch 021 - train 0.14137 | val 0.16119
  Regression -> MSE: 0.000168, MAE: 0.010265, R²: -0.0335
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14101 | val 0.17499
  Epoch 020 - train 0.12630 | val 0.23161
  Epoch 021 - train 0.12903 | val 0.24049
  Regression -> MSE: 0.000184, MAE: 0.010530, R²: -0.0066
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15057 | val 0.15425
  Epoch 020 - train 0.13397 | val 0.15636
  Epoch 021 - train 0.13545 | val 0.15564
  Regression -> MSE: 0.000350, MAE: 0.012267, R²: -0.0037
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16728 | val 0.10476
  Epoch 020 - train 0.14706 | val 0.11270
  Epoch 021 - train 0.14734 | val 0.11734
  Regression -> MSE: 0.000118, MAE: 0.008230, R²: -0.1350
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16526 | val 0.20898
  Epoch 020 - train 0.13023 | val 0.22816
  Epoch 021 - train 0.14345 | val 0.22574
  Regression -> MSE: 0.000217, MAE: 0.011249, R²: -0.0091
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.17358 | val 0.27674
  Epoch 020 - train 0.13805 | val 0.30366
  Epoch 021 - train 0.14416 | val 0.33180
  Regression -> MSE: 0.000084, MAE: 0.007158, R²: -0.0514
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15765 | val 0.12910
  Epoch 020 - train 0.14349 | val 0.12921
  Epoch 021 - train 0.13768 | val 0.12706
  Regression -> MSE: 0.000343, MAE: 0.015479, R²: -0.0447
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15446 | val 0.12035
  Epoch 020 - train 0.15108 | val 0.12122
  Epoch 021 - train 0.16000 | val 0.12386
  Regression -> MSE: 0.000257, MAE: 0.011233, R²: -0.0785
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14467 | val 0.19876
  Epoch 020 - train 0.14242 | val 0.22392
  Epoch 021 - train 0.13498 | val 0.23045
  Regression -> MSE: 0.000082, MAE: 0.007036, R²: -0.0214
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.15017 | val 0.18699
  Epoch 020 - train 0.14961 | val 0.19086
  Epoch 021 - train 0.14071 | val 0.19112
  Regression -> MSE: 0.000362, MAE: 0.015312, R²: -0.0049
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13451 | val 0.19391
  Epoch 020 - train 0.15235 | val 0.19743
  Epoch 021 - train 0.13368 | val 0.19782
  Regression -> MSE: 0.000100, MAE: 0.007111, R²: -0.0331
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16390 | val 0.21115
  Epoch 020 - train 0.15624 | val 0.23314
  Epoch 021 - train 0.14031 | val 0.24318
  Regression -> MSE: 0.000185, MAE: 0.010574, R²: -0.0220
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.15095 | val 0.25157
  Epoch 020 - train 0.13790 | val 0.27137
  Epoch 021 - train 0.14160 | val 0.27112
  Regression -> MSE: 0.000221, MAE: 0.011644, R²: -0.0068
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...

[I 2026-02-23 23:19:03,070] Trial 32 finished with value: -0.011507533681137067 and parameters: {'feature_set': 'finbert', 'model_type': 'BiLSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.0009670923762001546, 'weight_decay': 0.0002674615462748629, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.248691236059306, 'early_stopping_min_delta': 0.00833559542524289}. Best is trial 28 with value: -0.0114561253945094.

  Epoch 020 - train 0.14439 | val 0.42620
  Epoch 021 - train 0.14530 | val 0.38247
  Regression -> MSE: 0.000238, MAE: 0.012234, R²: -0.0200
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10171 | val 0.14621
  Epoch 020 - train 0.09141 | val 0.19977
  Epoch 021 - train 0.09311 | val 0.20488
  Regression -> MSE: 0.000261, MAE: 0.013109, R²: -0.0620
  Directional -> Accuracy: 0.4430, MCC: 0.0000, F1: 0.6140

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10598 | val 0.10430
  Epoch 020 - train 0.09491 | val 0.13081
  Epoch 021 - train 0.09309 | val 0.12231
  Regression -> MSE: 0.000677, MAE: 0.019297, R²: -0.0002
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.7200

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11257 | val 0.19599
  Epoch 020 - train 0.09919 | val 0.21336
  Epoch 021 - train 0.09873 | val 0.20810
  Regression -> MSE: 0.000351, MAE: 0.015179, R²: -0.0109
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09068 | val 0.09242
  Epoch 020 - train 0.08867 | val 0.10827
  Epoch 021 - train 0.08650 | val 0.09973
  Regression -> MSE: 0.000374, MAE: 0.014919, R²: -0.0531
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10524 | val 0.09684
  Epoch 020 - train 0.09569 | val 0.09847
  Epoch 030 - train 0.08600 | val 0.11210
  Regression -> MSE: 0.000190, MAE: 0.009229, R²: 0.0437
  Directional -> Accuracy: 0.6604, MCC: 0.3182, F1: 0.7097

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10830 | val 0.20298
  Epoch 020 - train 0.08918 | val 0.20301
  Epoch 021 - train 0.08342 | val 0.19926
  Regression -> MSE: 0.000496, MAE: 0.017177, R²: 0.0018
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10890 | val 0.14648
  Epoch 020 - train 0.10150 | val 0.16819
  Epoch 021 - train 0.09931 | val 0.16403
  Regression -> MSE: 0.000257, MAE: 0.012636, R²: -0.0030
  Directional -> Accuracy: 0.4085, MCC: 0.0000, F1: 0.5800

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09769 | val 0.15681
  Epoch 020 - train 0.09223 | val 0.25206
  Epoch 021 - train 0.07419 | val 0.26025
  Regression -> MSE: 0.000618, MAE: 0.019684, R²: -0.0896
  Directional -> Accuracy: 0.4043, MCC: 0.0000, F1: 0.5758

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09370 | val 0.14621
  Epoch 020 - train 0.08442 | val 0.14084
  Epoch 030 - train 0.07743 | val 0.14664
  Epoch 036 - train 0.07275 | val 0.14065
  Regression -> MSE: 0.000369, MAE: 0.015207, R²: 0.0415
  Directional -> Accuracy: 0.6047, MCC: 0.2647, F1: 0.6047

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10264 | val 0.14056
  Epoch 020 - train 0.09814 | val 0.14738
  Epoch 021 - train 0.09403 | val 0.14775
  Regression -> MSE: 0.000243, MAE: 0.011574, R²: -0.0189
  Directional -> Accuracy: 0.5694, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09346 | val 0.16555
  Epoch 020 - train 0.08782 | val 0.19466
  Epoch 021 - train 0.09174 | val 0.18617
  Regression -> MSE: 0.000310, MAE: 0.013614, R²: -0.0084
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10310 | val 0.16061
  Epoch 020 - train 0.09975 | val 0.17366
  Epoch 021 - train 0.10067 | val 0.16401
  Regression -> MSE: 0.000656, MAE: 0.019125, R²: 0.0038
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10927 | val 0.11963
  Epoch 020 - train 0.10025 | val 0.11684
  Epoch 021 - train 0.09609 | val 0.11722
  Regression -> MSE: 0.000147, MAE: 0.009359, R²: -0.0016
  Directional -> Accuracy: 0.5556, MCC: 0.1612, F1: 0.6296

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09684 | val 0.13571
  Epoch 020 - train 0.08612 | val 0.15279
  Epoch 024 - train 0.08404 | val 0.13951
  Regression -> MSE: 0.000219, MAE: 0.010697, R²: 0.0251
  Directional -> Accuracy: 0.5079, MCC: 0.0284, F1: 0.6076

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10139 | val 0.23225
  Epoch 020 - train 0.08965 | val 0.35797
  Epoch 021 - train 0.09099 | val 0.35101
  Regression -> MSE: 0.000386, MAE: 0.016586, R²: -0.0062
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.6500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11210 | val 0.13217
  Epoch 020 - train 0.10065 | val 0.14382
  Epoch 021 - train 0.09931 | val 0.12409
  Regression -> MSE: 0.000105, MAE: 0.007792, R²: 0.0010
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09785 | val 0.17561
  Epoch 020 - train 0.09769 | val 0.18967
  Epoch 021 - train 0.09415 | val 0.19770
  Regression -> MSE: 0.000161, MAE: 0.010138, R²: -0.0192
  Directional -> Accuracy: 0.5410, MCC: -0.0609, F1: 0.6744

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10217 | val 0.12338
  Epoch 020 - train 0.09473 | val 0.20983
  Epoch 021 - train 0.09182 | val 0.23058
  Regression -> MSE: 0.000279, MAE: 0.013420, R²: -0.0285
  Directional -> Accuracy: 0.3974, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09552 | val 0.14365
  Epoch 020 - train 0.08805 | val 0.14075
  Epoch 021 - train 0.08444 | val 0.14456
  Regression -> MSE: 0.000161, MAE: 0.008952, R²: -0.0376
  Directional -> Accuracy: 0.5224, MCC: -0.1254, F1: 0.6735

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10800 | val 0.15796
  Epoch 020 - train 0.10045 | val 0.14660
  Epoch 021 - train 0.09706 | val 0.15271
  Regression -> MSE: 0.000237, MAE: 0.011185, R²: -0.0250
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10460 | val 0.13721
  Epoch 020 - train 0.09947 | val 0.15140
  Epoch 021 - train 0.08778 | val 0.14933
  Regression -> MSE: 0.000156, MAE: 0.009013, R²: -0.0474
  Directional -> Accuracy: 0.5200, MCC: 0.0017, F1: 0.6000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09596 | val 0.13076
  Epoch 020 - train 0.08877 | val 0.13376
  Epoch 021 - train 0.09232 | val 0.13354
  Regression -> MSE: 0.000187, MAE: 0.010714, R²: -0.0302
  Directional -> Accuracy: 0.5294, MCC: 0.1741, F1: 0.6800

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10313 | val 0.12927
  Epoch 020 - train 0.09802 | val 0.13257
  Epoch 030 - train 0.08175 | val 0.12886
  Epoch 036 - train 0.08210 | val 0.12577
  Regression -> MSE: 0.000102, MAE: 0.007633, R²: -0.2337
  Directional -> Accuracy: 0.5167, MCC: 0.0569, F1: 0.5246

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10221 | val 0.13862
  Epoch 020 - train 0.09524 | val 0.12757
  Epoch 021 - train 0.09585 | val 0.13177
  Regression -> MSE: 0.000215, MAE: 0.011227, R²: 0.0004
  Directional -> Accuracy: 0.4853, MCC: 0.0000, F1: 0.6535

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08818 | val 0.09195
  Epoch 020 - train 0.08610 | val 0.09159
  Epoch 027 - train 0.08316 | val 0.09692
  Regression -> MSE: 0.000094, MAE: 0.007924, R²: -0.0434
  Directional -> Accuracy: 0.5345, MCC: 0.0693, F1: 0.5574

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10124 | val 0.06406
  Epoch 020 - train 0.09378 | val 0.18415
  Epoch 021 - train 0.09185 | val 0.17158
  Regression -> MSE: 0.000129, MAE: 0.009386, R²: -0.0283
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10812 | val 0.08015
  Epoch 020 - train 0.09337 | val 0.08016
  Epoch 021 - train 0.09341 | val 0.08173
  Regression -> MSE: 0.000303, MAE: 0.013837, R²: -0.0402
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10238 | val 0.13675
  Epoch 020 - train 0.09383 | val 0.14330
  Epoch 021 - train 0.09338 | val 0.14559
  Regression -> MSE: 0.000183, MAE: 0.007936, R²: -0.1384
  Directional -> Accuracy: 0.4407, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11138 | val 0.10631
  Epoch 020 - train 0.10465 | val 0.10760
  Epoch 021 - train 0.10490 | val 0.10792
  Regression -> MSE: 0.000231, MAE: 0.011849, R²: -0.0014
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09596 | val 0.14722
  Epoch 020 - train 0.08685 | val 0.16990
  Epoch 021 - train 0.08881 | val 0.16946
  Regression -> MSE: 0.000259, MAE: 0.010761, R²: 0.0011
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11251 | val 0.14042
  Epoch 020 - train 0.09297 | val 0.16626
  Epoch 021 - train 0.09536 | val 0.16703
  Regression -> MSE: 0.000140, MAE: 0.008427, R²: 0.0006
  Directional -> Accuracy: 0.5435, MCC: 0.0000, F1: 0.7042

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10791 | val 0.13790
  Epoch 020 - train 0.10002 | val 0.15080
  Epoch 021 - train 0.09221 | val 0.17159
  Regression -> MSE: 0.000190, MAE: 0.010429, R²: -0.0209
  Directional -> Accuracy: 0.4808, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09344 | val 0.13375
  Epoch 020 - train 0.08606 | val 0.14577
  Epoch 021 - train 0.08862 | val 0.14669
  Regression -> MSE: 0.000265, MAE: 0.010579, R²: -0.0144
  Directional -> Accuracy: 0.5733, MCC: 0.1140, F1: 0.6522

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11098 | val 0.11689
  Epoch 020 - train 0.09894 | val 0.12458
  Epoch 021 - train 0.09330 | val 0.12615
  Regression -> MSE: 0.000162, MAE: 0.010085, R²: 0.0010
  Directional -> Accuracy: 0.5122, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09400 | val 0.10370
  Epoch 020 - train 0.07876 | val 0.10813
  Epoch 021 - train 0.08254 | val 0.12292
  Regression -> MSE: 0.000217, MAE: 0.011165, R²: -0.0146
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10124 | val 0.11705
  Epoch 020 - train 0.09227 | val 0.12556
  Epoch 021 - train 0.09290 | val 0.12834
  Regression -> MSE: 0.000342, MAE: 0.011886, R²: 0.0058
  Directional -> Accuracy: 0.5507, MCC: 0.0475, F1: 0.6437

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10211 | val 0.07901
  Epoch 020 - train 0.09447 | val 0.08827
  Epoch 021 - train 0.08613 | val 0.09204
  Regression -> MSE: 0.000122, MAE: 0.008235, R²: -0.2017
  Directional -> Accuracy: 0.4889, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10537 | val 0.14060
  Epoch 020 - train 0.09362 | val 0.14860
  Epoch 021 - train 0.09238 | val 0.14977
  Regression -> MSE: 0.000218, MAE: 0.011215, R²: -0.0320
  Directional -> Accuracy: 0.4746, MCC: 0.0000, F1: 0.6437

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11067 | val 0.19124
  Epoch 020 - train 0.09001 | val 0.22504
  Epoch 021 - train 0.09526 | val 0.21747
  Regression -> MSE: 0.000085, MAE: 0.007242, R²: -0.0645
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.7595

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11044 | val 0.09271
  Epoch 020 - train 0.09864 | val 0.09770
  Epoch 021 - train 0.08930 | val 0.09638
  Regression -> MSE: 0.000323, MAE: 0.014562, R²: -0.0284
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10767 | val 0.08022
  Epoch 020 - train 0.09874 | val 0.09769
  Epoch 021 - train 0.09764 | val 0.10226
  Regression -> MSE: 0.000232, MAE: 0.011052, R²: -0.0180
  Directional -> Accuracy: 0.5122, MCC: 0.0868, F1: 0.1667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09954 | val 0.15425
  Epoch 020 - train 0.09322 | val 0.15313
  Epoch 021 - train 0.09053 | val 0.17561
  Regression -> MSE: 0.000082, MAE: 0.007151, R²: 0.0018
  Directional -> Accuracy: 0.5065, MCC: 0.0000, F1: 0.6724

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10945 | val 0.12058
  Epoch 020 - train 0.10108 | val 0.18419
  Epoch 021 - train 0.09616 | val 0.18482
  Regression -> MSE: 0.000382, MAE: 0.015685, R²: -0.0321
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09099 | val 0.13145
  Epoch 020 - train 0.07494 | val 0.13829
  Epoch 021 - train 0.08476 | val 0.14395
  Regression -> MSE: 0.000096, MAE: 0.007058, R²: -0.0057
  Directional -> Accuracy: 0.5745, MCC: 0.0000, F1: 0.7297

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11149 | val 0.14474
  Epoch 020 - train 0.10043 | val 0.15331
  Epoch 021 - train 0.10300 | val 0.15198
  Regression -> MSE: 0.000195, MAE: 0.010787, R²: -0.0199
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10733 | val 0.12260
  Epoch 020 - train 0.09735 | val 0.13071
  Epoch 021 - train 0.09043 | val 0.13478
  Regression -> MSE: 0.000217, MAE: 0.011568, R²: -0.0050
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111


[I 2026-02-23 23:20:33,942] Trial 33 finished with value: -0.011497664072137048 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0017248043090036347, 'weight_decay': 7.935428606845462e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.16735439726119383, 'early_stopping_min_delta': 0.00691508076294846}. Best is trial 28 with value: -0.0114561253945094.

  Epoch 020 - train 0.09995 | val 0.20988
  Epoch 021 - train 0.10178 | val 0.18115
  Regression -> MSE: 0.000237, MAE: 0.012088, R²: -0.0298
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.27154 | val 0.41571
  Epoch 020 - train 0.26315 | val 0.39737
  Epoch 030 - train 0.24189 | val 0.41303
  Epoch 032 - train 0.23759 | val 0.48417
  Regression -> MSE: 0.000248, MAE: 0.012422, R²: -0.0030
  Directional -> Accuracy: 0.5455, MCC: 0.0541, F1: 0.3636

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.25618 | val 0.27512
  Epoch 020 - train 0.25414 | val 0.36658
  Epoch 025 - train 0.22918 | val 0.54539
  Regression -> MSE: 0.000676, MAE: 0.019127, R²: 0.0125
  Directional -> Accuracy: 0.5652, MCC: 0.0280, F1: 0.7143

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.27032 | val 0.49563
  Epoch 020 - train 0.27919 | val 0.50633
  Epoch 030 - train 0.25150 | val 0.57625
  Epoch 035 - train 0.25752 | val 0.49041
  Regression -> MSE: 0.000307, MAE: 0.013840, R²: 0.0108
  Directional -> Accuracy: 0.5745, MCC: 0.1988, F1: 0.4737

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.21848 | val 0.85688
  Epoch 020 - train 0.21123 | val 1.06310
  Epoch 021 - train 0.20641 | val 1.37528
  Regression -> MSE: 0.000355, MAE: 0.014672, R²: -0.0174
  Directional -> Accuracy: 0.5867, MCC: 0.1540, F1: 0.6517

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.25665 | val 0.26811
  Epoch 020 - train 0.24830 | val 0.26807
  Epoch 030 - train 0.24660 | val 0.41205
  Epoch 032 - train 0.23076 | val 0.34098
  Regression -> MSE: 0.000217, MAE: 0.010336, R²: -0.0679
  Directional -> Accuracy: 0.4118, MCC: -0.2451, F1: 0.5455

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.25462 | val 0.57431
  Epoch 020 - train 0.23867 | val 0.58909
  Epoch 023 - train 0.22096 | val 0.58787
  Regression -> MSE: 0.000555, MAE: 0.018124, R²: -0.0004
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.27657 | val 0.38879
  Epoch 020 - train 0.26369 | val 0.37498
  Epoch 024 - train 0.25242 | val 0.36834
  Regression -> MSE: 0.000248, MAE: 0.011911, R²: -0.0110
  Directional -> Accuracy: 0.6232, MCC: 0.1628, F1: 0.3158

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.24760 | val 0.33919
  Epoch 020 - train 0.24492 | val 0.41745
  Epoch 030 - train 0.20762 | val 0.54674
  Epoch 035 - train 0.20082 | val 0.43453
  Regression -> MSE: 0.000603, MAE: 0.019252, R²: -0.0096
  Directional -> Accuracy: 0.5682, MCC: -0.0417, F1: 0.0952

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.25289 | val 0.33319
  Epoch 020 - train 0.23310 | val 0.33990
  Epoch 030 - train 0.21475 | val 0.46302
  Epoch 032 - train 0.21312 | val 0.47382
  Regression -> MSE: 0.000405, MAE: 0.016158, R²: -0.0559
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.28224 | val 0.37817
  Epoch 020 - train 0.26190 | val 0.37443
  Epoch 021 - train 0.26069 | val 0.38323
  Regression -> MSE: 0.000240, MAE: 0.011772, R²: 0.0070
  Directional -> Accuracy: 0.5286, MCC: 0.1391, F1: 0.5926

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.23975 | val 0.47635
  Epoch 020 - train 0.21893 | val 0.59401
  Epoch 021 - train 0.21355 | val 0.56331
  Regression -> MSE: 0.000310, MAE: 0.013634, R²: 0.0019
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.27952 | val 0.40607
  Epoch 020 - train 0.24407 | val 0.48655
  Epoch 021 - train 0.24380 | val 0.38225
  Regression -> MSE: 0.000684, MAE: 0.019730, R²: -0.0094
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.26942 | val 0.28261
  Epoch 020 - train 0.23803 | val 0.31712
  Epoch 030 - train 0.22503 | val 0.36354
  Epoch 036 - train 0.21849 | val 0.34132
  Regression -> MSE: 0.000157, MAE: 0.009841, R²: -0.1380
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.24999 | val 0.37254
  Epoch 020 - train 0.23473 | val 0.37371
  Epoch 030 - train 0.23922 | val 0.40769
  Epoch 040 - train 0.20219 | val 0.45126
  Epoch 045 - train 0.17923 | val 0.64939
  Regression -> MSE: 0.000236, MAE: 0.010607, R²: -0.0474
  Directional -> Accuracy: 0.5738, MCC: 0.1607, F1: 0.5000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.27329 | val 0.60621
  Epoch 020 - train 0.25998 | val 0.76413
  Epoch 030 - train 0.21097 | val 1.33958
  Regression -> MSE: 0.000354, MAE: 0.015899, R²: 0.0227
  Directional -> Accuracy: 0.5000, MCC: 0.1225, F1: 0.6389

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.28457 | val 0.30807
  Epoch 020 - train 0.27166 | val 0.31565
  Epoch 030 - train 0.26211 | val 0.30804
  Epoch 034 - train 0.24369 | val 0.31217
  Regression -> MSE: 0.000105, MAE: 0.007953, R²: 0.0233
  Directional -> Accuracy: 0.5571, MCC: 0.0907, F1: 0.6353

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.25370 | val 0.65076
  Epoch 020 - train 0.23970 | val 0.68984
  Epoch 024 - train 0.24435 | val 0.78428
  Regression -> MSE: 0.000169, MAE: 0.010503, R²: -0.0845
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.27758 | val 0.30300
  Epoch 020 - train 0.26310 | val 0.31889
  Epoch 024 - train 0.24841 | val 0.36770
  Regression -> MSE: 0.000278, MAE: 0.013361, R²: -0.0225
  Directional -> Accuracy: 0.4079, MCC: 0.0933, F1: 0.0426

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.24601 | val 0.38615
  Epoch 020 - train 0.22163 | val 0.37305
  Epoch 030 - train 0.21970 | val 0.38629
  Epoch 040 - train 0.19698 | val 0.38106
  Epoch 050 - train 0.18178 | val 0.36973
  Regression -> MSE: 0.000210, MAE: 0.010211, R²: -0.4012
  Directional -> Accuracy: 0.4615, MCC: 0.0474, F1: 0.2857

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.28311 | val 0.42639
  Epoch 020 - train 0.25726 | val 0.46796
  Epoch 030 - train 0.22794 | val 0.50751
  Epoch 040 - train 0.20804 | val 0.49965
  Epoch 050 - train 0.18619 | val 0.45478
  Regression -> MSE: 0.000430, MAE: 0.016177, R²: -0.9000
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.26744 | val 0.35426
  Epoch 020 - train 0.26211 | val 0.48374
  Epoch 030 - train 0.24747 | val 0.45006
  Epoch 037 - train 0.22725 | val 0.34488
  Regression -> MSE: 0.000158, MAE: 0.009123, R²: -0.1027
  Directional -> Accuracy: 0.3750, MCC: -0.2375, F1: 0.4231

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.25728 | val 0.35062
  Epoch 020 - train 0.24263 | val 0.39965
  Epoch 022 - train 0.22560 | val 0.38242
  Regression -> MSE: 0.000178, MAE: 0.010452, R²: -0.0755
  Directional -> Accuracy: 0.4091, MCC: -0.1861, F1: 0.4658

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.27868 | val 0.38263
  Epoch 020 - train 0.27109 | val 0.40840
  Epoch 023 - train 0.26664 | val 0.55049
  Regression -> MSE: 0.000089, MAE: 0.007231, R²: -0.0476
  Directional -> Accuracy: 0.4655, MCC: -0.0278, F1: 0.4151

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.28492 | val 0.36923
  Epoch 020 - train 0.27185 | val 0.56153
  Epoch 025 - train 0.25324 | val 0.39119
  Regression -> MSE: 0.000213, MAE: 0.010972, R²: -0.0077
  Directional -> Accuracy: 0.5455, MCC: 0.0684, F1: 0.2500

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.23731 | val 0.24314
  Epoch 020 - train 0.23422 | val 0.23291
  Epoch 030 - train 0.21448 | val 0.24733
  Epoch 040 - train 0.20865 | val 0.23675
  Epoch 044 - train 0.19003 | val 0.26629
  Regression -> MSE: 0.000114, MAE: 0.008451, R²: -0.2410
  Directional -> Accuracy: 0.5357, MCC: 0.1728, F1: 0.3810

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.29295 | val 0.21129
  Epoch 020 - train 0.26482 | val 0.21761
  Epoch 027 - train 0.22802 | val 0.22880
  Regression -> MSE: 0.000102, MAE: 0.008598, R²: 0.0141
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.30187 | val 0.27106
  Epoch 020 - train 0.27437 | val 0.37056
  Epoch 030 - train 0.26164 | val 0.35390
  Epoch 031 - train 0.25846 | val 0.48821
  Regression -> MSE: 0.000232, MAE: 0.012600, R²: -0.0026
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.25973 | val 0.35641
  Epoch 020 - train 0.24902 | val 0.36695
  Epoch 030 - train 0.24438 | val 0.35032
  Epoch 033 - train 0.22325 | val 0.41827
  Regression -> MSE: 0.000217, MAE: 0.008765, R²: -0.3052
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.28884 | val 0.22670
  Epoch 020 - train 0.25420 | val 0.26213
  Epoch 028 - train 0.23229 | val 0.24655
  Regression -> MSE: 0.000233, MAE: 0.011841, R²: 0.0149
  Directional -> Accuracy: 0.5366, MCC: 0.0166, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.27461 | val 0.47802
  Epoch 020 - train 0.21775 | val 0.50563
  Epoch 030 - train 0.21444 | val 0.51129
  Regression -> MSE: 0.000219, MAE: 0.009630, R²: 0.0488
  Directional -> Accuracy: 0.5349, MCC: 0.2158, F1: 0.6774

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.29360 | val 0.33436
  Epoch 020 - train 0.24224 | val 0.34778
  Epoch 028 - train 0.25096 | val 0.36642
  Regression -> MSE: 0.000138, MAE: 0.008244, R²: -0.0227
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.26579 | val 0.38391
  Epoch 020 - train 0.23890 | val 0.45446
  Epoch 021 - train 0.25702 | val 0.40763
  Regression -> MSE: 0.000192, MAE: 0.010463, R²: -0.0206
  Directional -> Accuracy: 0.5200, MCC: 0.0467, F1: 0.5200

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.23472 | val 0.33221
  Epoch 020 - train 0.22853 | val 0.31483
  Epoch 030 - train 0.21416 | val 0.36373
  Epoch 040 - train 0.20552 | val 0.30466
  Epoch 050 - train 0.19478 | val 0.32202
  Regression -> MSE: 0.000348, MAE: 0.012713, R²: -0.3297
  Directional -> Accuracy: 0.4932, MCC: 0.0797, F1: 0.3273

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.26888 | val 0.24107
  Epoch 020 - train 0.23318 | val 0.24740
  Epoch 021 - train 0.23499 | val 0.24432
  Regression -> MSE: 0.000166, MAE: 0.010363, R²: 0.0023
  Directional -> Accuracy: 0.4211, MCC: -0.2928, F1: 0.5926

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.22637 | val 0.33725
  Epoch 020 - train 0.21873 | val 0.40971
  Epoch 024 - train 0.21301 | val 0.36178
  Regression -> MSE: 0.000179, MAE: 0.010289, R²: 0.0029
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.26037 | val 0.25620
  Epoch 020 - train 0.23831 | val 0.26953
  Epoch 030 - train 0.22339 | val 0.29858
  Regression -> MSE: 0.000349, MAE: 0.012614, R²: -0.0188
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.28715 | val 0.16573
  Epoch 020 - train 0.22215 | val 0.18735
  Epoch 030 - train 0.21788 | val 0.17253
  Epoch 036 - train 0.23243 | val 0.16548
  Regression -> MSE: 0.000107, MAE: 0.007766, R²: -0.0207
  Directional -> Accuracy: 0.6977, MCC: 0.3961, F1: 0.6977

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.27031 | val 0.40326
  Epoch 020 - train 0.23590 | val 0.46367
  Epoch 029 - train 0.23584 | val 0.42959
  Regression -> MSE: 0.000218, MAE: 0.011282, R²: 0.0036
  Directional -> Accuracy: 0.5263, MCC: 0.0596, F1: 0.5424

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.25848 | val 0.54028
  Epoch 020 - train 0.24617 | val 0.62934
  Epoch 027 - train 0.20874 | val 0.69357
  Regression -> MSE: 0.000083, MAE: 0.007113, R²: -0.0681
  Directional -> Accuracy: 0.4681, MCC: -0.0504, F1: 0.5098

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.28142 | val 0.22723
  Epoch 020 - train 0.23469 | val 0.21732
  Epoch 030 - train 0.21625 | val 0.24351
  Epoch 040 - train 0.19472 | val 0.24759
  Epoch 044 - train 0.20282 | val 0.20956
  Regression -> MSE: 0.000400, MAE: 0.016489, R²: -0.2997
  Directional -> Accuracy: 0.3469, MCC: -0.1627, F1: 0.4839

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.29296 | val 0.18120
  Epoch 020 - train 0.28811 | val 0.18971
  Epoch 027 - train 0.21502 | val 0.23416
  Regression -> MSE: 0.000249, MAE: 0.011480, R²: -0.0217
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.24910 | val 0.41426
  Epoch 020 - train 0.24719 | val 0.37616
  Epoch 030 - train 0.22858 | val 0.48234
  Epoch 032 - train 0.22080 | val 0.64145
  Regression -> MSE: 0.000080, MAE: 0.007037, R²: 0.0093
  Directional -> Accuracy: 0.5200, MCC: 0.1155, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.27462 | val 0.35876
  Epoch 020 - train 0.26221 | val 0.53084
  Epoch 022 - train 0.26138 | val 0.49543
  Regression -> MSE: 0.000327, MAE: 0.014731, R²: -0.0658
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.26431 | val 0.33366

[I 2026-02-23 23:25:06,362] Trial 34 finished with value: -0.011633553582318955 and parameters: {'feature_set': 'finbert', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.007659440962658805, 'weight_decay': 0.0005259651762673656, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.5269995252422239, 'early_stopping_min_delta': 0.0014352478361329326}. Best is trial 28 with value: -0.0114561253945094.

  Epoch 037 - train 0.23072 | val 0.45329
  Regression -> MSE: 0.000226, MAE: 0.012092, R²: 0.0477
  Directional -> Accuracy: 0.5738, MCC: 0.2442, F1: 0.6750

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 6
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.16862 | val 0.36271
  Epoch 020 - train 0.16046 | val 0.34587
  Epoch 021 - train 0.15635 | val 0.44085
  Regression -> MSE: 0.000251, MAE: 0.012627, R²: -0.0210
  Directional -> Accuracy: 0.5316, MCC: 0.1896, F1: 0.6337

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 82). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16905 | val 0.35347
  Epoch 020 - train 0.14240 | val 0.27661
  Epoch 021 - train 0.14420 | val 0.29188
  Regression -> MSE: 0.000681, MAE: 0.019300, R²: -0.0051
  Directional -> Accuracy: 0.6667, MCC: 0.3115, F1: 0.7333

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 82). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.19808 | val 0.34767
  Epoch 020 - train 0.17167 | val 0.40426
  Epoch 022 - train 0.16328 | val 0.43709
  Regression -> MSE: 0.000346, MAE: 0.015108, R²: 0.0022
  Directional -> Accuracy: 0.5306, MCC: 0.0271, F1: 0.6567

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15148 | val 0.18652
  Epoch 020 - train 0.13383 | val 0.51174
  Epoch 021 - train 0.12964 | val 0.25545
  Regression -> MSE: 0.000354, MAE: 0.014667, R²: 0.0020
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16587 | val 0.23481
  Epoch 020 - train 0.14743 | val 0.37563
  Epoch 025 - train 0.14093 | val 0.35782
  Regression -> MSE: 0.000213, MAE: 0.009604, R²: -0.0728
  Directional -> Accuracy: 0.6792, MCC: 0.3769, F1: 0.7463

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.17109 | val 0.38214
  Epoch 020 - train 0.16116 | val 0.37251
  Epoch 026 - train 0.14467 | val 0.45037
  Regression -> MSE: 0.000491, MAE: 0.017173, R²: 0.0104
  Directional -> Accuracy: 0.5854, MCC: 0.1560, F1: 0.4848

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.18124 | val 0.26793
  Epoch 020 - train 0.16316 | val 0.33223
  Epoch 021 - train 0.15692 | val 0.41815
  Regression -> MSE: 0.000256, MAE: 0.012166, R²: 0.0033
  Directional -> Accuracy: 0.5493, MCC: 0.0038, F1: 0.3043

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 82). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 82). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.17299 | val 0.26325
  Epoch 020 - train 0.13591 | val 0.27648
  Epoch 027 - train 0.12313 | val 0.29861
  Regression -> MSE: 0.000568, MAE: 0.018538, R²: -0.0024
  Directional -> Accuracy: 0.5957, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.17092 | val 0.35678
  Epoch 020 - train 0.12971 | val 0.33462
  Epoch 021 - train 0.12999 | val 0.36100
  Regression -> MSE: 0.000385, MAE: 0.016070, R²: -0.0000
  Directional -> Accuracy: 0.3953, MCC: 0.0000, F1: 0.5667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 82). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 82). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.17325 | val 0.24278
  Epoch 020 - train 0.15707 | val 0.26707
  Epoch 030 - train 0.13901 | val 0.35626
  Regression -> MSE: 0.000300, MAE: 0.013297, R²: -0.2566
  Directional -> Accuracy: 0.4583, MCC: -0.0765, F1: 0.4348

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.16322 | val 0.29372
  Epoch 020 - train 0.15130 | val 0.34532
  Epoch 030 - train 0.14044 | val 0.34426
  Epoch 037 - train 0.11007 | val 0.29436
  Regression -> MSE: 0.000289, MAE: 0.013008, R²: 0.0599
  Directional -> Accuracy: 0.5769, MCC: 0.1338, F1: 0.4211

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.19117 | val 0.29573
  Epoch 020 - train 0.17856 | val 0.35436
  Epoch 021 - train 0.16683 | val 0.42390
  Regression -> MSE: 0.000662, MAE: 0.019373, R²: -0.0055
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17097 | val 0.29413
  Epoch 020 - train 0.14592 | val 0.25374
  Epoch 021 - train 0.13810 | val 0.33774
  Regression -> MSE: 0.000148, MAE: 0.009527, R²: -0.0082
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 82). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.16454 | val 0.27037
  Epoch 020 - train 0.14336 | val 0.35776
  Epoch 027 - train 0.13361 | val 0.36044
  Regression -> MSE: 0.000241, MAE: 0.011511, R²: -0.0713
  Directional -> Accuracy: 0.5397, MCC: 0.0869, F1: 0.5915

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.17101 | val 0.44366
  Epoch 020 - train 0.14116 | val 0.69488
  Epoch 023 - train 0.14361 | val 0.95519
  Regression -> MSE: 0.000387, MAE: 0.016839, R²: -0.0094
  Directional -> Accuracy: 0.5000, MCC: 0.0521, F1: 0.6400

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.18892 | val 0.25924
  Epoch 020 - train 0.16675 | val 0.28029
  Epoch 030 - train 0.15008 | val 0.24682
  Epoch 039 - train 0.13131 | val 0.21596
  Regression -> MSE: 0.000109, MAE: 0.007951, R²: -0.0345
  Directional -> Accuracy: 0.5417, MCC: 0.0519, F1: 0.6374

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.17013 | val 0.39862
  Epoch 020 - train 0.14610 | val 0.45755
  Epoch 021 - train 0.14630 | val 0.46630
  Regression -> MSE: 0.000157, MAE: 0.009716, R²: 0.0052
  Directional -> Accuracy: 0.6066, MCC: 0.0000, F1: 0.7551

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.17303 | val 0.26436
  Epoch 020 - train 0.15299 | val 0.28276
  Epoch 021 - train 0.15186 | val 0.29486
  Regression -> MSE: 0.000280, MAE: 0.013363, R²: -0.0340
  Directional -> Accuracy: 0.4487, MCC: 0.1019, F1: 0.2182

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.16759 | val 0.27576
  Epoch 020 - train 0.15675 | val 0.36361
  Epoch 030 - train 0.12801 | val 0.38916
  Epoch 034 - train 0.11415 | val 0.30603
  Regression -> MSE: 0.000222, MAE: 0.011504, R²: -0.4327
  Directional -> Accuracy: 0.4478, MCC: 0.0538, F1: 0.1778

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 82). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.18093 | val 0.30617
  Epoch 020 - train 0.15719 | val 0.30480
  Epoch 021 - train 0.15582 | val 0.33033
  Regression -> MSE: 0.000267, MAE: 0.011737, R²: -0.1535
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17471 | val 0.23597
  Epoch 020 - train 0.14627 | val 0.24494
  Epoch 021 - train 0.14027 | val 0.25377
  Regression -> MSE: 0.000151, MAE: 0.008816, R²: -0.0155
  Directional -> Accuracy: 0.6200, MCC: 0.0000, F1: 0.7654

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 82). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 82). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 82). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.16944 | val 0.23695
  Epoch 020 - train 0.15393 | val 0.23723
  Epoch 021 - train 0.14947 | val 0.24554
  Regression -> MSE: 0.000191, MAE: 0.010864, R²: -0.0514
  Directional -> Accuracy: 0.4412, MCC: -0.1195, F1: 0.4865

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.19221 | val 0.32735
  Epoch 020 - train 0.17447 | val 0.32492
  Epoch 021 - train 0.16235 | val 0.32513
  Regression -> MSE: 0.000083, MAE: 0.006924, R²: -0.0073
  Directional -> Accuracy: 0.6167, MCC: 0.2070, F1: 0.6761

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.18770 | val 0.26996
  Epoch 020 - train 0.16575 | val 0.47905
  Epoch 021 - train 0.16377 | val 0.34619
  Regression -> MSE: 0.000221, MAE: 0.011144, R²: -0.0268
  Directional -> Accuracy: 0.5147, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.15677 | val 0.16484
  Epoch 020 - train 0.12893 | val 0.20296
  Epoch 024 - train 0.12679 | val 0.17948
  Regression -> MSE: 0.000113, MAE: 0.008545, R²: -0.2501
  Directional -> Accuracy: 0.4138, MCC: -0.1421, F1: 0.1500

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18417 | val 0.32508
  Epoch 020 - train 0.14393 | val 0.23824
  Epoch 021 - train 0.13309 | val 0.26338
  Regression -> MSE: 0.000130, MAE: 0.009423, R²: -0.0364
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.18664 | val 0.30730
  Epoch 020 - train 0.15742 | val 0.19505
  Epoch 021 - train 0.15943 | val 0.14434
  Regression -> MSE: 0.000298, MAE: 0.013714, R²: -0.0216
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.18422 | val 0.30969
  Epoch 020 - train 0.16985 | val 0.28619
  Epoch 022 - train 0.16116 | val 0.32732
  Regression -> MSE: 0.000190, MAE: 0.008248, R²: -0.1792
  Directional -> Accuracy: 0.5593, MCC: 0.2496, F1: 0.4091

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.19167 | val 0.22818
  Epoch 020 - train 0.14865 | val 0.50558
  Epoch 021 - train 0.16908 | val 0.45523
  Regression -> MSE: 0.000235, MAE: 0.012015, R²: -0.0173
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.6866

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.17510 | val 0.27900
  Epoch 020 - train 0.13662 | val 0.29079
  Epoch 024 - train 0.14092 | val 0.33655
  Regression -> MSE: 0.000254, MAE: 0.010782, R²: 0.0208
  Directional -> Accuracy: 0.5435, MCC: 0.0870, F1: 0.5333

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18927 | val 0.27956
  Epoch 020 - train 0.16615 | val 0.37342
  Epoch 021 - train 0.16060 | val 0.37095
  Regression -> MSE: 0.000144, MAE: 0.008610, R²: -0.0234
  Directional -> Accuracy: 0.3043, MCC: -0.3928, F1: 0.3333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.17605 | val 0.38328
  Epoch 020 - train 0.14725 | val 0.39803
  Epoch 022 - train 0.14496 | val 0.31360
  Regression -> MSE: 0.000192, MAE: 0.010975, R²: -0.0335
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.6835

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.16264 | val 0.27225
  Epoch 020 - train 0.13706 | val 0.25706
  Epoch 021 - train 0.13605 | val 0.26502
  Regression -> MSE: 0.000265, MAE: 0.010897, R²: -0.0166
  Directional -> Accuracy: 0.5733, MCC: 0.1400, F1: 0.6098

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 82). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15668 | val 0.21643
  Epoch 020 - train 0.14283 | val 0.22670
  Epoch 021 - train 0.13982 | val 0.22123
  Regression -> MSE: 0.000165, MAE: 0.010176, R²: -0.0150
  Directional -> Accuracy: 0.4878, MCC: 0.0000, F1: 0.6557

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15051 | val 0.26278
  Epoch 020 - train 0.13414 | val 0.28487
  Epoch 021 - train 0.13045 | val 0.27334
  Regression -> MSE: 0.000222, MAE: 0.011301, R²: -0.0366
  Directional -> Accuracy: 0.4565, MCC: 0.0000, F1: 0.6269

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.17305 | val 0.19679
  Epoch 020 - train 0.15754 | val 0.18832
  Epoch 030 - train 0.13421 | val 0.22068
  Epoch 039 - train 0.12160 | val 0.20006
  Regression -> MSE: 0.000382, MAE: 0.013997, R²: -0.1105
  Directional -> Accuracy: 0.5217, MCC: 0.1640, F1: 0.4000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16645 | val 0.15789
  Epoch 020 - train 0.15533 | val 0.18867
  Epoch 021 - train 0.14906 | val 0.23668
  Regression -> MSE: 0.000108, MAE: 0.008073, R²: -0.0640
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17507 | val 0.31741
  Epoch 020 - train 0.15720 | val 0.45171
  Epoch 021 - train 0.15138 | val 0.38514
  Regression -> MSE: 0.000212, MAE: 0.011047, R²: -0.0004
  Directional -> Accuracy: 0.4576, MCC: -0.1312, F1: 0.2381

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16773 | val 0.46775
  Epoch 020 - train 0.14381 | val 0.50703
  Epoch 021 - train 0.14638 | val 0.43168
  Regression -> MSE: 0.000091, MAE: 0.007530, R²: -0.1426
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 82). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 82). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 82). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 82). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.16651 | val 0.17185
  Epoch 020 - train 0.14721 | val 0.17555
  Epoch 024 - train 0.13681 | val 0.17103
  Regression -> MSE: 0.000359, MAE: 0.016091, R²: -0.1443
  Directional -> Accuracy: 0.3333, MCC: 0.0000, F1: 0.5000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 82). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17546 | val 0.16662
  Epoch 020 - train 0.11505 | val 0.23896
  Epoch 025 - train 0.13270 | val 0.30770
  Regression -> MSE: 0.000248, MAE: 0.011109, R²: -0.0865
  Directional -> Accuracy: 0.5122, MCC: 0.0263, F1: 0.5000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 82). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 82). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16409 | val 0.61228
  Epoch 020 - train 0.14521 | val 0.46945
  Epoch 021 - train 0.14149 | val 0.51825
  Regression -> MSE: 0.000082, MAE: 0.007111, R²: -0.0012
  Directional -> Accuracy: 0.5325, MCC: 0.0664, F1: 0.5135

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for proper time series validation for TSM. Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 82). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 82). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.19117 | val 0.25130
  Epoch 020 - train 0.15562 | val 0.24859
  Epoch 024 - train 0.15250 | val 0.26232
  Regression -> MSE: 0.000373, MAE: 0.015696, R²: -0.0084
  Directional -> Accuracy: 0.5102, MCC: 0.1414, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16220 | val 0.24556
  Epoch 020 - train 0.14512 | val 0.28116
  Epoch 024 - train 0.13436 | val 0.28858
  Regression -> MSE: 0.000095, MAE: 0.007142, R²: -0.0018
  Directional -> Accuracy: 0.5319, MCC: -0.0268, F1: 0.6562

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.18748 | val 0.33424
  Epoch 020 - train 0.14668 | val 0.41635
  Epoch 023 - train 0.13916 | val 0.35057
  Regression -> MSE: 0.000191, MAE: 0.010390, R²: 0.0012
  Directional -> Accuracy: 0.3571, MCC: 0.0000, F1: 0.5263

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.17602 | val 0.24084
  Epoch 020 - train 0.14439 | val 0.24400
  Epoch 021 - train 0.15436 | val 0.24658
  Regression -> MSE: 0.000216, MAE: 0.011510, R²: 0.0014
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111


[I 2026-02-23 23:27:41,877] Trial 35 finished with value: -0.011666215585531292 and parameters: {'feature_set': 'finbert', 'model_type': 'BiLSTM', 'sequence_length': 6, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 0.0038475738848462626, 'weight_decay': 0.00016117860487487747, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.3401526860143408, 'early_stopping_min_delta': 0.007382781846630278}. Best is trial 28 with value: -0.0114561253945094.

  Epoch 020 - train 0.17056 | val 0.36825
  Epoch 021 - train 0.16122 | val 0.36074
  Regression -> MSE: 0.000237, MAE: 0.012079, R²: -0.0319
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.31246 | val 0.40739
  Epoch 020 - train 0.29628 | val 0.41173
  Epoch 030 - train 0.28895 | val 0.41770
  Regression -> MSE: 0.000252, MAE: 0.012503, R²: -0.0257
  Directional -> Accuracy: 0.5513, MCC: 0.1114, F1: 0.5455

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.34597 | val 0.30098
  Epoch 020 - train 0.31279 | val 0.34660
  Epoch 021 - train 0.30618 | val 0.34513
  Regression -> MSE: 0.000710, MAE: 0.019941, R²: -0.0262
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.32074 | val 0.55314
  Epoch 020 - train 0.32894 | val 0.54802
  Epoch 030 - train 0.33742 | val 0.55221
  Epoch 033 - train 0.32475 | val 0.55126
  Regression -> MSE: 0.000391, MAE: 0.015635, R²: -0.1314
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.28086 | val 0.34608
  Epoch 020 - train 0.28173 | val 0.38112
  Epoch 021 - train 0.26359 | val 0.37610
  Regression -> MSE: 0.000349, MAE: 0.014490, R²: -0.0124
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.29867 | val 0.28105
  Epoch 020 - train 0.28406 | val 0.27140
  Epoch 030 - train 0.29340 | val 0.27207
  Epoch 033 - train 0.29190 | val 0.27283
  Regression -> MSE: 0.000186, MAE: 0.008914, R²: 0.0731
  Directional -> Accuracy: 0.7885, MCC: 0.5736, F1: 0.8070

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.33665 | val 0.62985
  Epoch 020 - train 0.34523 | val 0.65803
  Epoch 030 - train 0.30163 | val 0.68391
  Epoch 031 - train 0.30672 | val 0.68894
  Regression -> MSE: 0.000593, MAE: 0.018772, R²: -0.0362
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.32931 | val 0.43112
  Epoch 020 - train 0.34263 | val 0.42696
  Epoch 021 - train 0.32707 | val 0.42681
  Regression -> MSE: 0.000248, MAE: 0.011986, R²: -0.0088
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.34304 | val 0.42142
  Epoch 020 - train 0.32577 | val 0.59482
  Epoch 021 - train 0.32669 | val 0.61333
  Regression -> MSE: 0.000594, MAE: 0.018990, R²: -0.0154
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.31455 | val 0.50995
  Epoch 020 - train 0.32325 | val 0.51070
  Epoch 021 - train 0.29252 | val 0.51066
  Regression -> MSE: 0.000341, MAE: 0.015328, R²: -0.0099
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.31690 | val 0.55187
  Epoch 020 - train 0.31020 | val 0.56619
  Epoch 021 - train 0.30396 | val 0.57438
  Regression -> MSE: 0.000239, MAE: 0.011628, R²: -0.0022
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.30829 | val 0.48017
  Epoch 020 - train 0.29115 | val 0.49850
  Epoch 028 - train 0.29881 | val 0.51122
  Regression -> MSE: 0.000309, MAE: 0.013492, R²: -0.0098
  Directional -> Accuracy: 0.5294, MCC: 0.0119, F1: 0.0769

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.33885 | val 0.37938
  Epoch 020 - train 0.33259 | val 0.38430
  Epoch 021 - train 0.32982 | val 0.38441
  Regression -> MSE: 0.000669, MAE: 0.019413, R²: 0.0003
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.34182 | val 0.29431
  Epoch 020 - train 0.32513 | val 0.36323
  Epoch 026 - train 0.33343 | val 0.38929
  Regression -> MSE: 0.000158, MAE: 0.009941, R²: -0.0531
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.30132 | val 0.42825
  Epoch 020 - train 0.28020 | val 0.42031
  Epoch 030 - train 0.27813 | val 0.41852
  Epoch 036 - train 0.27225 | val 0.42003
  Regression -> MSE: 0.000226, MAE: 0.011051, R²: -0.0065
  Directional -> Accuracy: 0.4677, MCC: -0.0690, F1: 0.3529

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.33163 | val 0.71769
  Epoch 020 - train 0.31720 | val 0.73928
  Epoch 021 - train 0.33331 | val 0.74000
  Regression -> MSE: 0.000390, MAE: 0.016298, R²: -0.0366
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.32912 | val 0.33729
  Epoch 020 - train 0.32039 | val 0.34301
  Epoch 027 - train 0.32203 | val 0.34444
  Regression -> MSE: 0.000103, MAE: 0.007741, R²: 0.0274
  Directional -> Accuracy: 0.5634, MCC: 0.1084, F1: 0.6437

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.32487 | val 0.59688
  Epoch 020 - train 0.29627 | val 0.62573
  Epoch 021 - train 0.31239 | val 0.63000
  Regression -> MSE: 0.000160, MAE: 0.009820, R²: 0.0007
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.32703 | val 0.35977
  Epoch 020 - train 0.30544 | val 0.36467
  Epoch 021 - train 0.31521 | val 0.37286
  Regression -> MSE: 0.000269, MAE: 0.012902, R²: -0.0019
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.27699 | val 0.42977
  Epoch 020 - train 0.30653 | val 0.42932
  Epoch 030 - train 0.27305 | val 0.42131
  Epoch 032 - train 0.27473 | val 0.42226
  Regression -> MSE: 0.000178, MAE: 0.009931, R²: -0.2064
  Directional -> Accuracy: 0.4697, MCC: 0.1559, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.33863 | val 0.56887
  Epoch 020 - train 0.32374 | val 0.55092
  Epoch 025 - train 0.32553 | val 0.54387
  Regression -> MSE: 0.000242, MAE: 0.011088, R²: -0.0667
  Directional -> Accuracy: 0.4868, MCC: 0.1519, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.36455 | val 0.42309
  Epoch 020 - train 0.34097 | val 0.41867
  Epoch 021 - train 0.32884 | val 0.41642
  Regression -> MSE: 0.000149, MAE: 0.008561, R²: -0.0054
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.29623 | val 0.37543
  Epoch 020 - train 0.29735 | val 0.38150
  Epoch 021 - train 0.29380 | val 0.38160
  Regression -> MSE: 0.000181, MAE: 0.010640, R²: -0.0215
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.34545 | val 0.39200
  Epoch 020 - train 0.34047 | val 0.40241
  Epoch 021 - train 0.34473 | val 0.40211
  Regression -> MSE: 0.000084, MAE: 0.006927, R²: 0.0002
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.33489 | val 0.49461
  Epoch 020 - train 0.32561 | val 0.52241
  Epoch 021 - train 0.32106 | val 0.52693
  Regression -> MSE: 0.000224, MAE: 0.011286, R²: -0.0241
  Directional -> Accuracy: 0.5224, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.30476 | val 0.22593
  Epoch 020 - train 0.29322 | val 0.21801
  Epoch 030 - train 0.28238 | val 0.21803
  Epoch 040 - train 0.26623 | val 0.21834
  Regression -> MSE: 0.000112, MAE: 0.008536, R²: -0.2266
  Directional -> Accuracy: 0.5614, MCC: 0.2277, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.34136 | val 0.17621
  Epoch 020 - train 0.31916 | val 0.19767
  Epoch 021 - train 0.31854 | val 0.20044
  Regression -> MSE: 0.000145, MAE: 0.009877, R²: -0.1562
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.36366 | val 0.30004
  Epoch 020 - train 0.34087 | val 0.33500
  Epoch 021 - train 0.32526 | val 0.33058
  Regression -> MSE: 0.000238, MAE: 0.012748, R²: -0.0009
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.34370 | val 0.37661
  Epoch 020 - train 0.31135 | val 0.37345
  Epoch 030 - train 0.32110 | val 0.37196
  Epoch 033 - train 0.31305 | val 0.37281
  Regression -> MSE: 0.000226, MAE: 0.009583, R²: -0.3781
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.34817 | val 0.21891
  Epoch 020 - train 0.32637 | val 0.21521
  Epoch 030 - train 0.31927 | val 0.20925
  Epoch 040 - train 0.32571 | val 0.21145
  Epoch 046 - train 0.30157 | val 0.21138
  Regression -> MSE: 0.000235, MAE: 0.012066, R²: -0.0042
  Directional -> Accuracy: 0.5349, MCC: 0.0385, F1: 0.6429

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.32485 | val 0.49234
  Epoch 020 - train 0.33094 | val 0.52738
  Epoch 021 - train 0.29489 | val 0.52847
  Regression -> MSE: 0.000251, MAE: 0.010425, R²: -0.0018
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.35971 | val 0.46526
  Epoch 020 - train 0.35741 | val 0.48945
  Epoch 021 - train 0.36351 | val 0.49244
  Regression -> MSE: 0.000136, MAE: 0.008321, R²: -0.0215
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.33438 | val 0.42817
  Epoch 020 - train 0.31921 | val 0.40984
  Epoch 030 - train 0.30013 | val 0.40390
  Epoch 040 - train 0.30496 | val 0.39892
  Epoch 050 - train 0.30144 | val 0.39490
  Regression -> MSE: 0.000252, MAE: 0.012536, R²: -0.3386
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.28626 | val 0.38421
  Epoch 020 - train 0.27624 | val 0.38304
  Epoch 027 - train 0.28591 | val 0.38196
  Regression -> MSE: 0.000281, MAE: 0.011026, R²: -0.0867
  Directional -> Accuracy: 0.5405, MCC: 0.2360, F1: 0.3704

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.29570 | val 0.27654
  Epoch 020 - train 0.30776 | val 0.27792
  Epoch 021 - train 0.28997 | val 0.27902
  Regression -> MSE: 0.000162, MAE: 0.010168, R²: 0.0024
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.29958 | val 0.35584
  Epoch 020 - train 0.29081 | val 0.40037
  Epoch 021 - train 0.27298 | val 0.40176
  Regression -> MSE: 0.000190, MAE: 0.010751, R²: -0.0418
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.29690 | val 0.29873
  Epoch 020 - train 0.29942 | val 0.31058
  Epoch 024 - train 0.28584 | val 0.30913
  Regression -> MSE: 0.000349, MAE: 0.012403, R²: -0.0013
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.33843 | val 0.19802
  Epoch 020 - train 0.33316 | val 0.20183
  Epoch 021 - train 0.31198 | val 0.20201
  Regression -> MSE: 0.000114, MAE: 0.008209, R²: -0.1011
  Directional -> Accuracy: 0.5682, MCC: 0.1494, F1: 0.6415

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.34250 | val 0.45351
  Epoch 020 - train 0.34502 | val 0.45414
  Epoch 021 - train 0.34424 | val 0.45400
  Regression -> MSE: 0.000217, MAE: 0.011240, R²: -0.0088
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.33494 | val 0.61055
  Epoch 020 - train 0.31218 | val 0.65734
  Epoch 021 - train 0.33427 | val 0.65870
  Regression -> MSE: 0.000084, MAE: 0.007160, R²: -0.0523
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.30656 | val 0.26638
  Epoch 020 - train 0.32543 | val 0.27415
  Epoch 021 - train 0.30277 | val 0.27660
  Regression -> MSE: 0.000350, MAE: 0.015866, R²: -0.0669
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.36534 | val 0.19864
  Epoch 020 - train 0.33328 | val 0.19741
  Epoch 021 - train 0.33977 | val 0.19729
  Regression -> MSE: 0.000247, MAE: 0.011208, R²: -0.0366
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.31483 | val 0.46570
  Epoch 020 - train 0.31254 | val 0.46357
  Epoch 024 - train 0.29748 | val 0.47121
  Regression -> MSE: 0.000080, MAE: 0.007031, R²: 0.0063
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.37853 | val 0.38067
  Epoch 020 - train 0.35064 | val 0.37697
  Epoch 021 - train 0.37006 | val 0.37663
  Regression -> MSE: 0.000368, MAE: 0.015350, R²: -0.0231
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.31783 | val 0.36371
  Epoch 020 - train 0.31843 | val 0.38279
  Epoch 027 - train 0.29802 | val 0.40232
  Regression -> MSE: 0.000096, MAE: 0.007209, R²: 0.0072
  Directional -> Accuracy: 0.6000, MCC: 0.2357, F1: 0.5714

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.33882 | val 0.43047
  Epoch 020 - train 0.33613 | val 0.46847
  Epoch 029 - train 0.34503 | val 0.48710
  Regression -> MSE: 0.000183, MAE: 0.010294, R²: -0.0107

[I 2026-02-23 23:30:21,784] Trial 36 finished with value: -0.011596790617694355 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'BiLSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 5.524178689389159e-05, 'weight_decay': 6.053160356725631e-05, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.6481053804599505, 'early_stopping_min_delta': 0.0032014329839861154}. Best is trial 28 with value: -0.0114561253945094.

  Epoch 020 - train 0.32727 | val 0.52267
  Epoch 021 - train 0.32522 | val 0.52752
  Regression -> MSE: 0.000237, MAE: 0.012233, R²: -0.0159
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15828 | val 0.24476
  Epoch 020 - train 0.15525 | val 0.24801
  Epoch 021 - train 0.15908 | val 0.24792
  Regression -> MSE: 0.000262, MAE: 0.013063, R²: -0.0595
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14399 | val 0.12804
  Epoch 020 - train 0.14126 | val 0.12672
  Epoch 030 - train 0.14274 | val 0.12689
  Regression -> MSE: 0.000687, MAE: 0.019531, R²: -0.0034
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15313 | val 0.23372
  Epoch 020 - train 0.14818 | val 0.24949
  Epoch 021 - train 0.16254 | val 0.24910
  Regression -> MSE: 0.000312, MAE: 0.014506, R²: -0.0066
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14474 | val 0.14009
  Epoch 020 - train 0.14116 | val 0.14858
  Epoch 021 - train 0.14754 | val 0.14499
  Regression -> MSE: 0.000368, MAE: 0.014879, R²: -0.0545
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16994 | val 0.14098
  Epoch 020 - train 0.16550 | val 0.14417
  Epoch 021 - train 0.16995 | val 0.14377
  Regression -> MSE: 0.000206, MAE: 0.010111, R²: -0.0112
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.14141 | val 0.25283
  Epoch 020 - train 0.15198 | val 0.26646
  Epoch 030 - train 0.15419 | val 0.26677
  Regression -> MSE: 0.000566, MAE: 0.018395, R²: -0.0203
  Directional -> Accuracy: 0.5745, MCC: 0.1882, F1: 0.3333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15851 | val 0.18048
  Epoch 020 - train 0.16141 | val 0.18127
  Epoch 021 - train 0.15828 | val 0.18185
  Regression -> MSE: 0.000249, MAE: 0.011924, R²: -0.0136
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.17737 | val 0.19011
  Epoch 020 - train 0.16342 | val 0.16566
  Epoch 030 - train 0.15848 | val 0.15862
  Regression -> MSE: 0.000611, MAE: 0.019303, R²: -0.0231
  Directional -> Accuracy: 0.5455, MCC: -0.1816, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15616 | val 0.16781
  Epoch 020 - train 0.15216 | val 0.17046
  Epoch 021 - train 0.16237 | val 0.16991
  Regression -> MSE: 0.000391, MAE: 0.015976, R²: -0.0203
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15371 | val 0.19383
  Epoch 020 - train 0.15802 | val 0.19687
  Epoch 021 - train 0.15187 | val 0.19719
  Regression -> MSE: 0.000248, MAE: 0.011664, R²: -0.0258
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15117 | val 0.20421
  Epoch 020 - train 0.15566 | val 0.22422
  Epoch 021 - train 0.14726 | val 0.22396
  Regression -> MSE: 0.000313, MAE: 0.013635, R²: -0.0063
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.16585 | val 0.15534
  Epoch 020 - train 0.15431 | val 0.15455
  Epoch 021 - train 0.15556 | val 0.15465
  Regression -> MSE: 0.000685, MAE: 0.019819, R²: -0.0109
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.15296 | val 0.16055
  Epoch 020 - train 0.15503 | val 0.21310
  Epoch 021 - train 0.17438 | val 0.21374
  Regression -> MSE: 0.000138, MAE: 0.009079, R²: -0.0005
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15810 | val 0.24859
  Epoch 020 - train 0.16567 | val 0.27711
  Epoch 021 - train 0.15625 | val 0.27765
  Regression -> MSE: 0.000229, MAE: 0.010993, R²: -0.0165
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16045 | val 0.27765
  Epoch 020 - train 0.15744 | val 0.27939
  Epoch 021 - train 0.15807 | val 0.27912
  Regression -> MSE: 0.000373, MAE: 0.015919, R²: -0.0286
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16097 | val 0.14153
  Epoch 020 - train 0.15923 | val 0.14103
  Epoch 021 - train 0.16063 | val 0.14090
  Regression -> MSE: 0.000109, MAE: 0.007941, R²: -0.0148
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15238 | val 0.22101
  Epoch 020 - train 0.15095 | val 0.22172
  Epoch 021 - train 0.15327 | val 0.22190
  Regression -> MSE: 0.000157, MAE: 0.009724, R²: -0.0049
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16452 | val 0.15222
  Epoch 020 - train 0.15685 | val 0.15157
  Epoch 021 - train 0.15949 | val 0.15119
  Regression -> MSE: 0.000275, MAE: 0.013182, R²: -0.0089
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14488 | val 0.18388
  Epoch 020 - train 0.14397 | val 0.18466
  Epoch 021 - train 0.13853 | val 0.18495
  Regression -> MSE: 0.000166, MAE: 0.009091, R²: -0.1066
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14773 | val 0.20649
  Epoch 020 - train 0.15751 | val 0.20743
  Epoch 021 - train 0.15129 | val 0.20655
  Regression -> MSE: 0.000251, MAE: 0.011339, R²: -0.1071
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16403 | val 0.16902
  Epoch 020 - train 0.16720 | val 0.17021
  Epoch 021 - train 0.15331 | val 0.17009
  Regression -> MSE: 0.000147, MAE: 0.008548, R²: -0.0250
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14217 | val 0.16071
  Epoch 020 - train 0.15625 | val 0.16092
  Epoch 021 - train 0.14039 | val 0.16104
  Regression -> MSE: 0.000173, MAE: 0.010265, R²: -0.0456
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15298 | val 0.16990
  Epoch 020 - train 0.15464 | val 0.16993
  Epoch 021 - train 0.15767 | val 0.17012
  Regression -> MSE: 0.000092, MAE: 0.007423, R²: -0.0841
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16000 | val 0.17189
  Epoch 020 - train 0.14875 | val 0.17427
  Epoch 021 - train 0.15214 | val 0.17398
  Regression -> MSE: 0.000212, MAE: 0.011184, R²: -0.0013
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.15593 | val 0.13312
  Epoch 020 - train 0.16422 | val 0.13556
  Epoch 021 - train 0.15455 | val 0.13625
  Regression -> MSE: 0.000097, MAE: 0.008161, R²: -0.0591
  Directional -> Accuracy: 0.5536, MCC: 0.0207, F1: 0.7059

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16336 | val 0.10706
  Epoch 020 - train 0.16887 | val 0.12171
  Epoch 021 - train 0.16725 | val 0.12290
  Regression -> MSE: 0.000104, MAE: 0.008791, R²: -0.0095
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16291 | val 0.13107
  Epoch 020 - train 0.15560 | val 0.13362
  Epoch 021 - train 0.15464 | val 0.13384
  Regression -> MSE: 0.000232, MAE: 0.012561, R²: -0.0020
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.16308 | val 0.18686
  Epoch 020 - train 0.16289 | val 0.19266
  Epoch 021 - train 0.16134 | val 0.19287
  Regression -> MSE: 0.000170, MAE: 0.007816, R²: -0.0185
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.15804 | val 0.11793
  Epoch 020 - train 0.17254 | val 0.11824
  Epoch 021 - train 0.16476 | val 0.11865
  Regression -> MSE: 0.000237, MAE: 0.011875, R²: -0.0029
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16005 | val 0.22681
  Epoch 020 - train 0.14705 | val 0.24380
  Epoch 021 - train 0.16006 | val 0.24314
  Regression -> MSE: 0.000234, MAE: 0.010117, R²: -0.0170
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15694 | val 0.18136
  Epoch 020 - train 0.15496 | val 0.19306
  Epoch 021 - train 0.16342 | val 0.19332
  Regression -> MSE: 0.000145, MAE: 0.008723, R²: -0.0741
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15179 | val 0.17274
  Epoch 020 - train 0.15570 | val 0.17362
  Epoch 021 - train 0.15307 | val 0.17370
  Regression -> MSE: 0.000188, MAE: 0.010421, R²: -0.0008
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13809 | val 0.15985
  Epoch 020 - train 0.13373 | val 0.15928
  Epoch 021 - train 0.13441 | val 0.15937
  Regression -> MSE: 0.000266, MAE: 0.010546, R²: -0.0174
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15321 | val 0.11980
  Epoch 020 - train 0.14599 | val 0.12091
  Epoch 021 - train 0.15757 | val 0.12107
  Regression -> MSE: 0.000168, MAE: 0.010374, R²: -0.0058
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13613 | val 0.13851
  Epoch 020 - train 0.14421 | val 0.14586
  Epoch 021 - train 0.15628 | val 0.14542
  Regression -> MSE: 0.000180, MAE: 0.010280, R²: -0.0015
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14244 | val 0.12961
  Epoch 020 - train 0.15753 | val 0.12952
  Epoch 021 - train 0.15004 | val 0.12975
  Regression -> MSE: 0.000344, MAE: 0.012008, R²: -0.0041
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16293 | val 0.09081
  Epoch 020 - train 0.16185 | val 0.09924
  Epoch 021 - train 0.15340 | val 0.09910
  Regression -> MSE: 0.000112, MAE: 0.008322, R²: -0.0685
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15529 | val 0.24643
  Epoch 020 - train 0.16379 | val 0.28127
  Epoch 021 - train 0.15857 | val 0.27882
  Regression -> MSE: 0.000219, MAE: 0.011288, R²: -0.0006
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16279 | val 0.24363
  Epoch 020 - train 0.14875 | val 0.25204
  Epoch 021 - train 0.14679 | val 0.25164
  Regression -> MSE: 0.000082, MAE: 0.007070, R²: -0.0590
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15874 | val 0.10951
  Epoch 020 - train 0.15431 | val 0.11774
  Epoch 021 - train 0.14119 | val 0.11839
  Regression -> MSE: 0.000322, MAE: 0.014633, R²: -0.0482
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15899 | val 0.08439
  Epoch 020 - train 0.16886 | val 0.08547
  Epoch 021 - train 0.17645 | val 0.08553
  Regression -> MSE: 0.000254, MAE: 0.011455, R²: -0.0433
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14229 | val 0.16354
  Epoch 020 - train 0.14839 | val 0.16404
  Epoch 021 - train 0.14517 | val 0.16391
  Regression -> MSE: 0.000082, MAE: 0.007056, R²: -0.0126
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16565 | val 0.16490
  Epoch 020 - train 0.15810 | val 0.15949
  Epoch 030 - train 0.15596 | val 0.16014
  Regression -> MSE: 0.000304, MAE: 0.014475, R²: 0.0084
  Directional -> Accuracy: 0.5957, MCC: 0.1919, F1: 0.6415

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14437 | val 0.15057
  Epoch 020 - train 0.15639 | val 0.14823
  Epoch 021 - train 0.15092 | val 0.14855
  Regression -> MSE: 0.000099, MAE: 0.007173, R²: -0.0072
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16856 | val 0.16328
  Epoch 020 - train 0.14775 | val 0.16489
  Epoch 021 - train 0.15449 | val 0.16475
  Regression -> MSE: 0.000172, MAE: 0.009579, R²: -0.0012
  Directional -> Accuracy: 0.5918, MCC: 0.0342, F1: 0.2308

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14814 | val 0.15080
  Epoch 020 - train 0.14446 | val 0.15190
  Epoch 021 - train 0.14793 | val 0.15150
  Regression -> MSE: 0.000224, MAE: 0.011786, R²: -0.0060
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.16230 | val 0.15187
  Epoch 020 - train 0.15103 | val 0.15335
  Epoch 021 - train 0.14578 | val 0.15371

[I 2026-02-23 23:32:51,407] Trial 37 finished with value: -0.011438400778891087 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 7.206070364357948e-06, 'weight_decay': 1.7345790752717691e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.20750422620778192, 'early_stopping_min_delta': 0.005976380238283565}. Best is trial 37 with value: -0.011438400778891087.

  Epoch 030 - train 0.15824 | val 0.18791
  Regression -> MSE: 0.000265, MAE: 0.013005, R²: -0.1169
  Directional -> Accuracy: 0.5082, MCC: -0.0258, F1: 0.2105

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13531 | val 0.17522
  Epoch 020 - train 0.12442 | val 0.16994
  Epoch 021 - train 0.12931 | val 0.16920
  Regression -> MSE: 0.000265, MAE: 0.013132, R²: -0.0701
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12412 | val 0.12741
  Epoch 020 - train 0.12687 | val 0.13812
  Epoch 021 - train 0.13006 | val 0.13545
  Regression -> MSE: 0.000708, MAE: 0.019758, R²: -0.0341
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13160 | val 0.20404
  Epoch 020 - train 0.13487 | val 0.20689
  Epoch 021 - train 0.13049 | val 0.20633
  Regression -> MSE: 0.000313, MAE: 0.014418, R²: -0.0087
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11116 | val 0.11777
  Epoch 020 - train 0.10278 | val 0.12546
  Epoch 021 - train 0.10406 | val 0.12805
  Regression -> MSE: 0.000355, MAE: 0.014670, R²: -0.0158
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14705 | val 0.14552
  Epoch 020 - train 0.12597 | val 0.16982
  Epoch 021 - train 0.11734 | val 0.17133
  Regression -> MSE: 0.000206, MAE: 0.010312, R²: -0.0093
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12481 | val 0.23288
  Epoch 020 - train 0.12758 | val 0.23846
  Epoch 021 - train 0.11413 | val 0.24002
  Regression -> MSE: 0.000595, MAE: 0.018892, R²: -0.0723
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13030 | val 0.15458
  Epoch 020 - train 0.12654 | val 0.15626
  Epoch 021 - train 0.12128 | val 0.15634
  Regression -> MSE: 0.000246, MAE: 0.012147, R²: -0.0025
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11945 | val 0.18053
  Epoch 020 - train 0.13037 | val 0.22853
  Epoch 021 - train 0.11798 | val 0.23251
  Regression -> MSE: 0.000641, MAE: 0.020094, R²: -0.0726
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13361 | val 0.15485
  Epoch 020 - train 0.11025 | val 0.14907
  Epoch 030 - train 0.11882 | val 0.14687
  Regression -> MSE: 0.000395, MAE: 0.015711, R²: -0.0286
  Directional -> Accuracy: 0.6327, MCC: 0.3303, F1: 0.3077

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12370 | val 0.16365
  Epoch 020 - train 0.12353 | val 0.16567
  Epoch 021 - train 0.12288 | val 0.16585
  Regression -> MSE: 0.000242, MAE: 0.011725, R²: -0.0044
  Directional -> Accuracy: 0.4143, MCC: -0.0961, F1: 0.5684

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11888 | val 0.19385
  Epoch 020 - train 0.11717 | val 0.21133
  Epoch 021 - train 0.12433 | val 0.21418
  Regression -> MSE: 0.000319, MAE: 0.013580, R²: -0.0265
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13146 | val 0.15111
  Epoch 020 - train 0.12994 | val 0.15665
  Epoch 021 - train 0.13031 | val 0.15652
  Regression -> MSE: 0.000679, MAE: 0.019566, R²: -0.0020
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12266 | val 0.12506
  Epoch 020 - train 0.11322 | val 0.14654
  Epoch 021 - train 0.11870 | val 0.14944
  Regression -> MSE: 0.000141, MAE: 0.009340, R²: -0.0227
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12389 | val 0.16717
  Epoch 020 - train 0.11939 | val 0.16378
  Epoch 030 - train 0.11112 | val 0.16012
  Regression -> MSE: 0.000226, MAE: 0.010904, R²: -0.0058
  Directional -> Accuracy: 0.4918, MCC: -0.0721, F1: 0.6517

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12973 | val 0.25602
  Epoch 020 - train 0.12106 | val 0.25511
  Epoch 021 - train 0.12429 | val 0.25531
  Regression -> MSE: 0.000363, MAE: 0.016242, R²: -0.0037
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12694 | val 0.13957
  Epoch 020 - train 0.13089 | val 0.13579
  Epoch 021 - train 0.12977 | val 0.13728
  Regression -> MSE: 0.000108, MAE: 0.007979, R²: 0.0031
  Directional -> Accuracy: 0.6000, MCC: 0.2312, F1: 0.7255

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12285 | val 0.25232
  Epoch 020 - train 0.12348 | val 0.27266
  Epoch 021 - train 0.11959 | val 0.27520
  Regression -> MSE: 0.000156, MAE: 0.009712, R²: -0.0012
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12757 | val 0.13670
  Epoch 020 - train 0.12586 | val 0.13836
  Epoch 021 - train 0.12891 | val 0.13876
  Regression -> MSE: 0.000272, MAE: 0.012994, R²: 0.0005
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12012 | val 0.16425
  Epoch 020 - train 0.11481 | val 0.16110
  Epoch 030 - train 0.11465 | val 0.15942
  Regression -> MSE: 0.000169, MAE: 0.009473, R²: -0.1322
  Directional -> Accuracy: 0.4923, MCC: 0.0029, F1: 0.5075

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13141 | val 0.17092
  Epoch 020 - train 0.12376 | val 0.16951
  Epoch 021 - train 0.12635 | val 0.16994
  Regression -> MSE: 0.000249, MAE: 0.011279, R²: -0.1003
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13304 | val 0.15440
  Epoch 020 - train 0.12453 | val 0.16277
  Epoch 021 - train 0.12374 | val 0.16229
  Regression -> MSE: 0.000143, MAE: 0.008310, R²: -0.0001
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12581 | val 0.15507
  Epoch 020 - train 0.12520 | val 0.15504
  Epoch 021 - train 0.12159 | val 0.15458
  Regression -> MSE: 0.000165, MAE: 0.010611, R²: -0.0013
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13835 | val 0.14729
  Epoch 020 - train 0.12949 | val 0.14945
  Epoch 021 - train 0.13118 | val 0.14951
  Regression -> MSE: 0.000088, MAE: 0.007222, R²: -0.0375
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12126 | val 0.16142
  Epoch 020 - train 0.11957 | val 0.15756
  Epoch 021 - train 0.12406 | val 0.15745
  Regression -> MSE: 0.000212, MAE: 0.011150, R²: 0.0009
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11386 | val 0.11041
  Epoch 020 - train 0.11527 | val 0.10800
  Epoch 021 - train 0.11327 | val 0.10764
  Regression -> MSE: 0.000094, MAE: 0.008101, R²: -0.0190
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13115 | val 0.09773
  Epoch 020 - train 0.12893 | val 0.09939
  Epoch 021 - train 0.12023 | val 0.09911
  Regression -> MSE: 0.000105, MAE: 0.008827, R²: -0.0157
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13850 | val 0.12322
  Epoch 020 - train 0.13606 | val 0.13453
  Epoch 021 - train 0.13343 | val 0.13692
  Regression -> MSE: 0.000232, MAE: 0.012566, R²: -0.0017
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14028 | val 0.14697
  Epoch 020 - train 0.12382 | val 0.14529
  Epoch 021 - train 0.12601 | val 0.14564
  Regression -> MSE: 0.000174, MAE: 0.007846, R²: -0.0458
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13569 | val 0.10845
  Epoch 020 - train 0.12614 | val 0.11092
  Epoch 021 - train 0.13490 | val 0.11125
  Regression -> MSE: 0.000237, MAE: 0.011877, R²: -0.0027
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13720 | val 0.19510
  Epoch 020 - train 0.12559 | val 0.20860
  Epoch 021 - train 0.12786 | val 0.20920
  Regression -> MSE: 0.000231, MAE: 0.009864, R²: -0.0018
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12811 | val 0.15734
  Epoch 020 - train 0.12009 | val 0.16468
  Epoch 021 - train 0.13090 | val 0.16475
  Regression -> MSE: 0.000139, MAE: 0.008350, R²: -0.0281
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12219 | val 0.16062
  Epoch 020 - train 0.11878 | val 0.16748
  Epoch 021 - train 0.12520 | val 0.16761
  Regression -> MSE: 0.000188, MAE: 0.010473, R²: 0.0003
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11472 | val 0.14863
  Epoch 020 - train 0.11097 | val 0.14456
  Epoch 021 - train 0.11172 | val 0.14358
  Regression -> MSE: 0.000278, MAE: 0.010883, R²: -0.0628
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11691 | val 0.11373
  Epoch 020 - train 0.13352 | val 0.10401
  Epoch 030 - train 0.12354 | val 0.10996
  Regression -> MSE: 0.000169, MAE: 0.010409, R²: -0.0143
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10996 | val 0.13181
  Epoch 020 - train 0.11427 | val 0.14068
  Epoch 021 - train 0.11159 | val 0.14139
  Regression -> MSE: 0.000183, MAE: 0.010436, R²: -0.0162
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12289 | val 0.12307
  Epoch 020 - train 0.12054 | val 0.12434
  Epoch 021 - train 0.11676 | val 0.12478
  Regression -> MSE: 0.000351, MAE: 0.011827, R²: -0.0245
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13090 | val 0.08329
  Epoch 020 - train 0.12547 | val 0.09272
  Epoch 021 - train 0.13604 | val 0.09299
  Regression -> MSE: 0.000111, MAE: 0.008317, R²: -0.0514
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13134 | val 0.17201
  Epoch 020 - train 0.11988 | val 0.17744
  Epoch 021 - train 0.12001 | val 0.17639
  Regression -> MSE: 0.000221, MAE: 0.011371, R²: -0.0092
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12851 | val 0.22271
  Epoch 020 - train 0.12388 | val 0.27532
  Epoch 021 - train 0.12251 | val 0.27047
  Regression -> MSE: 0.000091, MAE: 0.007473, R²: -0.1745
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13644 | val 0.11140
  Epoch 020 - train 0.13326 | val 0.11418
  Epoch 021 - train 0.12709 | val 0.11461
  Regression -> MSE: 0.000345, MAE: 0.015534, R²: -0.1224
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13542 | val 0.07708
  Epoch 020 - train 0.13060 | val 0.08266
  Epoch 021 - train 0.13607 | val 0.08345
  Regression -> MSE: 0.000248, MAE: 0.011518, R²: -0.0165
  Directional -> Accuracy: 0.5789, MCC: 0.2485, F1: 0.7143

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11924 | val 0.14999
  Epoch 020 - train 0.12063 | val 0.15675
  Epoch 021 - train 0.11621 | val 0.15738
  Regression -> MSE: 0.000083, MAE: 0.007053, R²: -0.0244
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12297 | val 0.15327
  Epoch 020 - train 0.12955 | val 0.16591
  Epoch 021 - train 0.12001 | val 0.16656
  Regression -> MSE: 0.000307, MAE: 0.014494, R²: -0.0020
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11449 | val 0.14938
  Epoch 020 - train 0.12491 | val 0.14237
  Epoch 030 - train 0.11940 | val 0.14294
  Regression -> MSE: 0.000097, MAE: 0.007121, R²: 0.0103
  Directional -> Accuracy: 0.5227, MCC: 0.0087, F1: 0.6038

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12658 | val 0.15185
  Epoch 020 - train 0.13043 | val 0.16335
  Epoch 021 - train 0.12866 | val 0.16497
  Regression -> MSE: 0.000172, MAE: 0.009588, R²: 0.0009
  Directional -> Accuracy: 0.5714, MCC: 0.0338, F1: 0.3226

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12168 | val 0.15835
  Epoch 020 - train 0.11563 | val 0.18207
  Epoch 021 - train 0.11296 | val 0.18413
  Regression -> MSE: 0.000224, MAE: 0.011778, R²: -0.0037
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12713 | val 0.14377
  Epoch 020 - train 0.12566 | val 0.15057
  Epoch 021 - train 0.12059 | val 0.14988
  Regression -> MSE: 0.000093, MAE: 0.007639, R²: -0.0031

[I 2026-02-23 23:34:53,978] Trial 38 finished with value: -0.011484552762581464 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.00015976878654187332, 'weight_decay': 1.9371918696971656e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.18752055946578228, 'early_stopping_min_delta': 0.008398648060674979}. Best is trial 37 with value: -0.011438400778891087.

  Epoch 020 - train 0.12880 | val 0.27697
  Epoch 021 - train 0.12806 | val 0.27647
  Regression -> MSE: 0.000245, MAE: 0.012372, R²: -0.0323
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13926 | val 0.17130
  Epoch 020 - train 0.13036 | val 0.17083
  Epoch 021 - train 0.13554 | val 0.17116
  Regression -> MSE: 0.000251, MAE: 0.012688, R²: -0.0136
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13285 | val 0.12804
  Epoch 020 - train 0.15202 | val 0.17070
  Epoch 021 - train 0.13708 | val 0.17102
  Regression -> MSE: 0.000716, MAE: 0.019888, R²: -0.0465
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.14645 | val 0.20444
  Epoch 020 - train 0.14340 | val 0.20619
  Epoch 021 - train 0.15165 | val 0.20630
  Regression -> MSE: 0.000322, MAE: 0.014519, R²: -0.0392
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12293 | val 0.11491
  Epoch 020 - train 0.12190 | val 0.11750
  Epoch 021 - train 0.13126 | val 0.11613
  Regression -> MSE: 0.000349, MAE: 0.014568, R²: 0.0003
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14144 | val 0.13955
  Epoch 020 - train 0.15705 | val 0.14938
  Epoch 021 - train 0.15328 | val 0.15099
  Regression -> MSE: 0.000210, MAE: 0.010218, R²: -0.0290
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12753 | val 0.23090
  Epoch 020 - train 0.12755 | val 0.24682
  Epoch 021 - train 0.13413 | val 0.24844
  Regression -> MSE: 0.000562, MAE: 0.018207, R²: -0.0129
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13934 | val 0.15897
  Epoch 020 - train 0.13748 | val 0.16029
  Epoch 021 - train 0.13994 | val 0.16055
  Regression -> MSE: 0.000247, MAE: 0.011921, R²: -0.0052
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14715 | val 0.17563
  Epoch 020 - train 0.14999 | val 0.14534
  Epoch 030 - train 0.13547 | val 0.13878
  Regression -> MSE: 0.000620, MAE: 0.019438, R²: -0.0374
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13591 | val 0.16424
  Epoch 020 - train 0.13431 | val 0.16592
  Epoch 021 - train 0.14083 | val 0.16592
  Regression -> MSE: 0.000384, MAE: 0.016204, R²: -0.0004
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13028 | val 0.15965
  Epoch 020 - train 0.13839 | val 0.16052
  Epoch 021 - train 0.14386 | val 0.16021
  Regression -> MSE: 0.000242, MAE: 0.012031, R²: -0.0020
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13623 | val 0.20855
  Epoch 020 - train 0.13673 | val 0.22767
  Epoch 021 - train 0.13319 | val 0.22854
  Regression -> MSE: 0.000311, MAE: 0.013709, R²: 0.0012
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14458 | val 0.15635
  Epoch 020 - train 0.14838 | val 0.16440
  Epoch 021 - train 0.13192 | val 0.16552
  Regression -> MSE: 0.000677, MAE: 0.019494, R²: 0.0011
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14943 | val 0.12573
  Epoch 020 - train 0.13826 | val 0.12480
  Epoch 021 - train 0.12967 | val 0.12399
  Regression -> MSE: 0.000139, MAE: 0.009145, R²: -0.0029
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12994 | val 0.16236
  Epoch 020 - train 0.12522 | val 0.16085
  Epoch 021 - train 0.12714 | val 0.16074
  Regression -> MSE: 0.000225, MAE: 0.010731, R²: -0.0023
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14179 | val 0.26444
  Epoch 020 - train 0.13913 | val 0.29246
  Epoch 021 - train 0.14226 | val 0.29445
  Regression -> MSE: 0.000365, MAE: 0.015995, R²: -0.0065
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14333 | val 0.14644
  Epoch 020 - train 0.14413 | val 0.14749
  Epoch 021 - train 0.14399 | val 0.14747
  Regression -> MSE: 0.000109, MAE: 0.008116, R²: -0.0083
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12871 | val 0.22001
  Epoch 020 - train 0.13305 | val 0.23992
  Epoch 021 - train 0.12904 | val 0.23879
  Regression -> MSE: 0.000162, MAE: 0.010213, R²: -0.0420
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14479 | val 0.16205
  Epoch 020 - train 0.14122 | val 0.16551
  Epoch 021 - train 0.14975 | val 0.16540
  Regression -> MSE: 0.000299, MAE: 0.014100, R²: -0.0978
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12422 | val 0.16934
  Epoch 020 - train 0.12920 | val 0.16943
  Epoch 021 - train 0.12947 | val 0.16930
  Regression -> MSE: 0.000169, MAE: 0.009177, R²: -0.1283
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14895 | val 0.18003
  Epoch 020 - train 0.15389 | val 0.17977
  Epoch 021 - train 0.14312 | val 0.18000
  Regression -> MSE: 0.000245, MAE: 0.011184, R²: -0.0849
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13503 | val 0.16511
  Epoch 020 - train 0.13688 | val 0.18828
  Epoch 021 - train 0.14617 | val 0.19062
  Regression -> MSE: 0.000145, MAE: 0.008464, R²: -0.0137
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15620 | val 0.17453
  Epoch 020 - train 0.14516 | val 0.17606
  Epoch 021 - train 0.15519 | val 0.17612
  Regression -> MSE: 0.000165, MAE: 0.010604, R²: -0.0007
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14857 | val 0.15419
  Epoch 020 - train 0.14924 | val 0.15542
  Epoch 021 - train 0.15018 | val 0.15515
  Regression -> MSE: 0.000085, MAE: 0.007050, R²: -0.0019
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14191 | val 0.15516
  Epoch 020 - train 0.14150 | val 0.15552
  Epoch 021 - train 0.14223 | val 0.15555
  Regression -> MSE: 0.000214, MAE: 0.011041, R²: -0.0106
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13058 | val 0.11711
  Epoch 020 - train 0.12809 | val 0.11785
  Epoch 021 - train 0.12927 | val 0.11761
  Regression -> MSE: 0.000099, MAE: 0.008202, R²: -0.0768
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14776 | val 0.09889
  Epoch 020 - train 0.15412 | val 0.10715
  Epoch 021 - train 0.15147 | val 0.10809
  Regression -> MSE: 0.000105, MAE: 0.008870, R²: -0.0222
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13931 | val 0.12330
  Epoch 020 - train 0.14455 | val 0.14726
  Epoch 021 - train 0.14599 | val 0.14757
  Regression -> MSE: 0.000237, MAE: 0.012753, R²: -0.0249
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13204 | val 0.14386
  Epoch 020 - train 0.14270 | val 0.14392
  Epoch 021 - train 0.14029 | val 0.14355
  Regression -> MSE: 0.000181, MAE: 0.007975, R²: -0.0877
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14616 | val 0.10959
  Epoch 020 - train 0.14814 | val 0.12259
  Epoch 021 - train 0.13895 | val 0.12405
  Regression -> MSE: 0.000236, MAE: 0.011856, R²: 0.0006
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14212 | val 0.20370
  Epoch 020 - train 0.14127 | val 0.21145
  Epoch 021 - train 0.14036 | val 0.21239
  Regression -> MSE: 0.000233, MAE: 0.010050, R²: -0.0094
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14530 | val 0.15406
  Epoch 020 - train 0.14703 | val 0.14506
  Epoch 030 - train 0.13598 | val 0.14492
  Regression -> MSE: 0.000136, MAE: 0.008206, R²: -0.0081
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14223 | val 0.16208
  Epoch 020 - train 0.14444 | val 0.16103
  Epoch 021 - train 0.14638 | val 0.16083
  Regression -> MSE: 0.000188, MAE: 0.010439, R²: 0.0001
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12545 | val 0.14786
  Epoch 020 - train 0.12726 | val 0.14757
  Epoch 021 - train 0.11967 | val 0.14757
  Regression -> MSE: 0.000266, MAE: 0.010525, R²: -0.0158
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14294 | val 0.11600
  Epoch 020 - train 0.13476 | val 0.11379
  Epoch 021 - train 0.12704 | val 0.11362
  Regression -> MSE: 0.000170, MAE: 0.010381, R²: -0.0199
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13784 | val 0.14107
  Epoch 020 - train 0.13026 | val 0.14647
  Epoch 021 - train 0.13097 | val 0.14652
  Regression -> MSE: 0.000186, MAE: 0.010569, R²: -0.0342
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13049 | val 0.12254
  Epoch 020 - train 0.13601 | val 0.12351
  Epoch 021 - train 0.13286 | val 0.12307
  Regression -> MSE: 0.000342, MAE: 0.011820, R²: 0.0028
  Directional -> Accuracy: 0.5075, MCC: 0.1674, F1: 0.2979

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14512 | val 0.08249
  Epoch 020 - train 0.16897 | val 0.08637
  Epoch 021 - train 0.15155 | val 0.08655
  Regression -> MSE: 0.000114, MAE: 0.008308, R²: -0.0836
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15184 | val 0.19214
  Epoch 020 - train 0.15824 | val 0.19926
  Epoch 021 - train 0.14311 | val 0.19862
  Regression -> MSE: 0.000223, MAE: 0.011436, R²: -0.0222
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.17151 | val 0.24131
  Epoch 020 - train 0.15312 | val 0.29653
  Epoch 021 - train 0.14964 | val 0.29650
  Regression -> MSE: 0.000080, MAE: 0.006957, R²: -0.0287
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13257 | val 0.09718
  Epoch 020 - train 0.13966 | val 0.10365
  Epoch 021 - train 0.14424 | val 0.10411
  Regression -> MSE: 0.000311, MAE: 0.014017, R²: -0.0122
  Directional -> Accuracy: 0.4490, MCC: 0.0707, F1: 0.5263

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14388 | val 0.08071
  Epoch 020 - train 0.15068 | val 0.08012
  Epoch 021 - train 0.14155 | val 0.08003
  Regression -> MSE: 0.000256, MAE: 0.011473, R²: -0.0520
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14383 | val 0.15458
  Epoch 020 - train 0.14027 | val 0.15473
  Epoch 021 - train 0.13750 | val 0.15466
  Regression -> MSE: 0.000085, MAE: 0.007051, R²: -0.0478
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13886 | val 0.16358
  Epoch 020 - train 0.13505 | val 0.16501
  Epoch 021 - train 0.16013 | val 0.16483
  Regression -> MSE: 0.000310, MAE: 0.014491, R²: -0.0092
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14034 | val 0.15709
  Epoch 020 - train 0.13901 | val 0.16831
  Epoch 021 - train 0.15123 | val 0.16826
  Regression -> MSE: 0.000105, MAE: 0.007124, R²: -0.0693
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14352 | val 0.15287
  Epoch 020 - train 0.13437 | val 0.17356
  Epoch 021 - train 0.14973 | val 0.17573
  Regression -> MSE: 0.000173, MAE: 0.009958, R²: -0.0071
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13184 | val 0.22576
  Epoch 020 - train 0.12887 | val 0.27089
  Epoch 021 - train 0.13516 | val 0.26922
  Regression -> MSE: 0.000224, MAE: 0.011716, R²: -0.0064
  Directional -> Accuracy: 0.6429, MCC: 0.3341, F1: 0.5833

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14607 | val 0.15330
  Epoch 020 - train 0.15044 | val 0.16232
  Epoch 021 - train 0.14392 | val 0.16367

[I 2026-02-23 23:36:57,169] Trial 39 finished with value: -0.011442080126094944 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 8.11081091807206e-06, 'weight_decay': 1.423262660676237e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.18923348286683067, 'early_stopping_min_delta': 0.008297865679825198}. Best is trial 37 with value: -0.011438400778891087.

  Epoch 020 - train 0.14217 | val 0.19746
  Epoch 021 - train 0.15000 | val 0.19973
  Regression -> MSE: 0.000238, MAE: 0.012344, R²: -0.0040
  Directional -> Accuracy: 0.4426, MCC: -0.1258, F1: 0.3704

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42334 | val 0.58075
  Epoch 020 - train 0.43713 | val 0.58398
  Epoch 029 - train 0.40601 | val 0.58196
  Regression -> MSE: 0.000268, MAE: 0.013383, R²: -0.0844
  Directional -> Accuracy: 0.3896, MCC: -0.2079, F1: 0.4198

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45876 | val 0.35199
  Epoch 020 - train 0.43295 | val 0.35425
  Epoch 021 - train 0.41370 | val 0.35448
  Regression -> MSE: 0.000712, MAE: 0.019836, R²: -0.0408
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45176 | val 0.75274
  Epoch 020 - train 0.44542 | val 0.83552
  Epoch 021 - train 0.46157 | val 0.83578
  Regression -> MSE: 0.000313, MAE: 0.014512, R²: -0.0076
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33922 | val 0.38391
  Epoch 020 - train 0.33093 | val 0.37323
  Epoch 021 - train 0.33340 | val 0.37642
  Regression -> MSE: 0.000352, MAE: 0.014601, R²: -0.0089
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.39936 | val 0.40274
  Epoch 020 - train 0.42086 | val 0.42181
  Epoch 021 - train 0.41124 | val 0.42209
  Regression -> MSE: 0.000206, MAE: 0.010130, R²: -0.0097
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.37494 | val 0.86292
  Epoch 020 - train 0.37373 | val 0.95449
  Epoch 021 - train 0.39331 | val 0.95726
  Regression -> MSE: 0.000563, MAE: 0.018211, R²: -0.0148
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.41701 | val 0.51243
  Epoch 020 - train 0.42386 | val 0.51208
  Epoch 021 - train 0.41810 | val 0.51178
  Regression -> MSE: 0.000248, MAE: 0.011945, R²: -0.0100
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41728 | val 0.52397
  Epoch 020 - train 0.42233 | val 0.56222
  Epoch 021 - train 0.40677 | val 0.56730
  Regression -> MSE: 0.000615, MAE: 0.019578, R²: -0.0286
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42470 | val 0.48635
  Epoch 020 - train 0.38320 | val 0.48546
  Epoch 021 - train 0.38204 | val 0.48416
  Regression -> MSE: 0.000392, MAE: 0.015953, R²: -0.0216
  Directional -> Accuracy: 0.5306, MCC: -0.1303, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42220 | val 0.53801
  Epoch 020 - train 0.42897 | val 0.53724
  Epoch 021 - train 0.41050 | val 0.53728
  Regression -> MSE: 0.000242, MAE: 0.011835, R²: -0.0006
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41953 | val 0.59350
  Epoch 020 - train 0.36848 | val 0.59517
  Epoch 030 - train 0.39065 | val 0.59557
  Regression -> MSE: 0.000359, MAE: 0.014088, R²: -0.1550
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.42089 | val 0.47154
  Epoch 020 - train 0.42125 | val 0.47472
  Epoch 021 - train 0.41914 | val 0.47471
  Regression -> MSE: 0.000681, MAE: 0.019536, R²: -0.0058
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.43792 | val 0.38796
  Epoch 020 - train 0.39659 | val 0.43221
  Epoch 021 - train 0.41085 | val 0.43669
  Regression -> MSE: 0.000144, MAE: 0.009450, R²: -0.0387
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37420 | val 0.54604
  Epoch 020 - train 0.35169 | val 0.55074
  Epoch 021 - train 0.34418 | val 0.55116
  Regression -> MSE: 0.000229, MAE: 0.010829, R²: -0.0183
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.39300 | val 1.03503
  Epoch 020 - train 0.40565 | val 1.26746
  Epoch 021 - train 0.41888 | val 1.26760
  Regression -> MSE: 0.000364, MAE: 0.015953, R²: -0.0061
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.42234 | val 0.40167
  Epoch 020 - train 0.43391 | val 0.40145
  Epoch 021 - train 0.42586 | val 0.40086
  Regression -> MSE: 0.000109, MAE: 0.007953, R²: -0.0122
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.46270 | val 0.74453
  Epoch 020 - train 0.46043 | val 0.75466
  Epoch 021 - train 0.46612 | val 0.75560
  Regression -> MSE: 0.000162, MAE: 0.010184, R²: -0.0392
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.45000 | val 0.55639
  Epoch 020 - train 0.45331 | val 0.55263
  Epoch 021 - train 0.45631 | val 0.55002
  Regression -> MSE: 0.000277, MAE: 0.012910, R²: -0.0178
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.37534 | val 0.58875
  Epoch 020 - train 0.38262 | val 0.58843
  Epoch 021 - train 0.36621 | val 0.59068
  Regression -> MSE: 0.000152, MAE: 0.008730, R²: -0.0163
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44711 | val 0.62079
  Epoch 020 - train 0.42651 | val 0.62256
  Epoch 025 - train 0.41488 | val 0.62255
  Regression -> MSE: 0.000289, MAE: 0.012350, R²: -0.2772
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42794 | val 0.53352
  Epoch 020 - train 0.41580 | val 0.57951
  Epoch 021 - train 0.40036 | val 0.57587
  Regression -> MSE: 0.000150, MAE: 0.008695, R²: -0.0475
  Directional -> Accuracy: 0.6667, MCC: 0.2335, F1: 0.7838

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40226 | val 0.48562
  Epoch 020 - train 0.40639 | val 0.48974
  Epoch 021 - train 0.40754 | val 0.48952
  Regression -> MSE: 0.000167, MAE: 0.010274, R²: -0.0091
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45385 | val 0.50586
  Epoch 020 - train 0.46413 | val 0.51506
  Epoch 021 - train 0.48138 | val 0.51509
  Regression -> MSE: 0.000093, MAE: 0.007447, R²: -0.0903
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.40737 | val 0.51527
  Epoch 020 - train 0.43459 | val 0.51694
  Epoch 021 - train 0.40930 | val 0.51681
  Regression -> MSE: 0.000212, MAE: 0.011093, R²: -0.0008
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41314 | val 0.32652
  Epoch 020 - train 0.39635 | val 0.33302
  Epoch 021 - train 0.38992 | val 0.33380
  Regression -> MSE: 0.000092, MAE: 0.008086, R²: -0.0021
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.41088 | val 0.28587
  Epoch 020 - train 0.39755 | val 0.27487
  Epoch 030 - train 0.39614 | val 0.28256
  Regression -> MSE: 0.000100, MAE: 0.008454, R²: 0.0322
  Directional -> Accuracy: 0.5870, MCC: 0.1549, F1: 0.5128

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44656 | val 0.37690
  Epoch 020 - train 0.44524 | val 0.40140
  Epoch 021 - train 0.44392 | val 0.40005
  Regression -> MSE: 0.000232, MAE: 0.012531, R²: -0.0007
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39582 | val 0.53668
  Epoch 020 - train 0.39637 | val 0.56187
  Epoch 021 - train 0.38512 | val 0.55823
  Regression -> MSE: 0.000174, MAE: 0.007856, R²: -0.0445
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.43096 | val 0.28352
  Epoch 020 - train 0.42945 | val 0.33113
  Epoch 021 - train 0.45359 | val 0.34228
  Regression -> MSE: 0.000238, MAE: 0.011886, R²: -0.0044
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.38837 | val 0.69576
  Epoch 020 - train 0.43134 | val 0.69728
  Epoch 021 - train 0.42406 | val 0.69724
  Regression -> MSE: 0.000231, MAE: 0.009866, R²: -0.0010
  Directional -> Accuracy: 0.4884, MCC: -0.0318, F1: 0.3889

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43992 | val 0.57226
  Epoch 020 - train 0.39853 | val 0.66737
  Epoch 021 - train 0.45565 | val 0.67294
  Regression -> MSE: 0.000145, MAE: 0.008745, R²: -0.0768
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.41718 | val 0.52328
  Epoch 020 - train 0.43102 | val 0.52370
  Epoch 021 - train 0.39634 | val 0.52331
  Regression -> MSE: 0.000190, MAE: 0.010405, R²: -0.0076
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37356 | val 0.48044
  Epoch 020 - train 0.38748 | val 0.47920
  Epoch 021 - train 0.35966 | val 0.47925
  Regression -> MSE: 0.000278, MAE: 0.010881, R²: -0.0607
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.38619 | val 0.31849
  Epoch 020 - train 0.38302 | val 0.32019
  Epoch 021 - train 0.38881 | val 0.32272
  Regression -> MSE: 0.000167, MAE: 0.010369, R²: 0.0004
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.37231 | val 0.40891
  Epoch 020 - train 0.38518 | val 0.40610
  Epoch 030 - train 0.37850 | val 0.40933
  Regression -> MSE: 0.000195, MAE: 0.010869, R²: -0.0848
  Directional -> Accuracy: 0.4545, MCC: -0.1988, F1: 0.0769

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.39457 | val 0.40972
  Epoch 020 - train 0.40265 | val 0.40834
  Epoch 021 - train 0.39835 | val 0.40951
  Regression -> MSE: 0.000354, MAE: 0.012582, R²: -0.0324
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.42581 | val 0.21908
  Epoch 020 - train 0.41781 | val 0.22691
  Epoch 021 - train 0.41528 | val 0.22725
  Regression -> MSE: 0.000123, MAE: 0.008426, R²: -0.1739
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.38757 | val 0.58747
  Epoch 020 - train 0.38302 | val 0.59064
  Epoch 021 - train 0.40793 | val 0.58927
  Regression -> MSE: 0.000219, MAE: 0.011287, R²: 0.0003
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.42890 | val 0.79152
  Epoch 020 - train 0.41341 | val 0.86399
  Epoch 021 - train 0.45361 | val 0.86449
  Regression -> MSE: 0.000092, MAE: 0.007507, R²: -0.1874
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.42003 | val 0.29916
  Epoch 020 - train 0.42440 | val 0.25852
  Epoch 030 - train 0.43999 | val 0.24875
  Regression -> MSE: 0.000345, MAE: 0.015553, R²: -0.1229
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.43261 | val 0.22071
  Epoch 020 - train 0.45635 | val 0.21059
  Epoch 030 - train 0.42131 | val 0.21012
  Regression -> MSE: 0.000267, MAE: 0.011539, R²: -0.0951
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.41753 | val 0.51338
  Epoch 020 - train 0.38338 | val 0.52144
  Epoch 021 - train 0.40161 | val 0.52004
  Regression -> MSE: 0.000081, MAE: 0.007076, R²: -0.0011
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.39622 | val 0.51377
  Epoch 020 - train 0.44843 | val 0.49489
  Epoch 030 - train 0.39250 | val 0.49555
  Regression -> MSE: 0.000328, MAE: 0.014976, R²: -0.0675
  Directional -> Accuracy: 0.4681, MCC: -0.1506, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.40965 | val 0.41714
  Epoch 020 - train 0.40717 | val 0.43205
  Epoch 021 - train 0.45769 | val 0.43495
  Regression -> MSE: 0.000099, MAE: 0.007362, R²: -0.0036
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50245 | val 0.52787
  Epoch 020 - train 0.48115 | val 0.57822
  Epoch 021 - train 0.44139 | val 0.58288
  Regression -> MSE: 0.000172, MAE: 0.009856, R²: -0.0033
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.34922 | val 0.46938
  Epoch 020 - train 0.35782 | val 0.47619
  Epoch 021 - train 0.35796 | val 0.47686
  Regression -> MSE: 0.000225, MAE: 0.011776, R²: -0.0073
  Directional -> Accuracy: 0.4107, MCC: -0.2034, F1: 0.4923

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44339 | val 0.53274
  Epoch 020 - train 0.44715 | val 0.55054
  Epoch 021 - train 0.41372 | val 0.54522

[I 2026-02-23 23:39:09,137] Trial 40 finished with value: -0.011537263750871173 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 7.3894302155231665e-06, 'weight_decay': 8.963871604563767e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.8982152835535457, 'early_stopping_min_delta': 0.009880200225241432}. Best is trial 37 with value: -0.011438400778891087.

  Epoch 020 - train 0.42107 | val 0.64362
  Epoch 021 - train 0.41524 | val 0.64759
  Regression -> MSE: 0.000237, MAE: 0.012379, R²: -0.0004
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13330 | val 0.18340
  Epoch 020 - train 0.13698 | val 0.18561
  Epoch 021 - train 0.13995 | val 0.18516
  Regression -> MSE: 0.000255, MAE: 0.012836, R²: -0.0285
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12774 | val 0.11416
  Epoch 020 - train 0.13254 | val 0.11779
  Epoch 021 - train 0.12239 | val 0.11765
  Regression -> MSE: 0.000707, MAE: 0.019751, R²: -0.0325
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13240 | val 0.19397
  Epoch 020 - train 0.13520 | val 0.19713
  Epoch 021 - train 0.13484 | val 0.19698
  Regression -> MSE: 0.000310, MAE: 0.014417, R²: 0.0001
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11021 | val 0.10875
  Epoch 020 - train 0.11850 | val 0.10801
  Epoch 021 - train 0.11517 | val 0.10935
  Regression -> MSE: 0.000373, MAE: 0.014961, R²: -0.0682
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12816 | val 0.12245
  Epoch 020 - train 0.12827 | val 0.12175
  Epoch 021 - train 0.13291 | val 0.12117
  Regression -> MSE: 0.000205, MAE: 0.010295, R²: -0.0048
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12877 | val 0.22854
  Epoch 020 - train 0.12183 | val 0.23934
  Epoch 021 - train 0.13180 | val 0.23906
  Regression -> MSE: 0.000591, MAE: 0.018794, R²: -0.0646
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14272 | val 0.14947
  Epoch 020 - train 0.13869 | val 0.14949
  Epoch 021 - train 0.13851 | val 0.14927
  Regression -> MSE: 0.000247, MAE: 0.012301, R²: -0.0055
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13598 | val 0.15777
  Epoch 020 - train 0.12482 | val 0.16675
  Epoch 021 - train 0.12632 | val 0.16701
  Regression -> MSE: 0.000628, MAE: 0.019870, R²: -0.0513
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12869 | val 0.15016
  Epoch 020 - train 0.12931 | val 0.15709
  Epoch 021 - train 0.13843 | val 0.15782
  Regression -> MSE: 0.000388, MAE: 0.016104, R²: -0.0112
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12935 | val 0.15211
  Epoch 020 - train 0.13092 | val 0.15246
  Epoch 021 - train 0.13034 | val 0.15253
  Regression -> MSE: 0.000241, MAE: 0.011874, R²: 0.0019
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12457 | val 0.17255
  Epoch 020 - train 0.11987 | val 0.17321
  Epoch 021 - train 0.12646 | val 0.17325
  Regression -> MSE: 0.000312, MAE: 0.013679, R²: -0.0025
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14278 | val 0.14362
  Epoch 020 - train 0.14444 | val 0.14504
  Epoch 021 - train 0.14050 | val 0.14523
  Regression -> MSE: 0.000681, MAE: 0.019628, R²: -0.0062
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13730 | val 0.12185
  Epoch 020 - train 0.13241 | val 0.13003
  Epoch 021 - train 0.13935 | val 0.13009
  Regression -> MSE: 0.000139, MAE: 0.009210, R²: -0.0065
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13999 | val 0.16076
  Epoch 020 - train 0.13540 | val 0.16266
  Epoch 021 - train 0.13235 | val 0.16203
  Regression -> MSE: 0.000229, MAE: 0.010795, R²: -0.0160
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12336 | val 0.26088
  Epoch 020 - train 0.13524 | val 0.28890
  Epoch 021 - train 0.13842 | val 0.29014
  Regression -> MSE: 0.000372, MAE: 0.015940, R²: -0.0281
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13979 | val 0.12374
  Epoch 020 - train 0.13516 | val 0.12494
  Epoch 021 - train 0.13242 | val 0.12533
  Regression -> MSE: 0.000108, MAE: 0.007967, R²: -0.0001
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13182 | val 0.20344
  Epoch 020 - train 0.12612 | val 0.20693
  Epoch 021 - train 0.11950 | val 0.20690
  Regression -> MSE: 0.000156, MAE: 0.009547, R²: -0.0024
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14780 | val 0.12666
  Epoch 020 - train 0.13175 | val 0.12696
  Epoch 021 - train 0.14955 | val 0.12740
  Regression -> MSE: 0.000272, MAE: 0.012994, R²: 0.0010
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11660 | val 0.17447
  Epoch 020 - train 0.12520 | val 0.17712
  Epoch 021 - train 0.11557 | val 0.17710
  Regression -> MSE: 0.000154, MAE: 0.008754, R²: -0.0266
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14839 | val 0.20714
  Epoch 020 - train 0.14280 | val 0.20963
  Epoch 021 - train 0.13950 | val 0.20921
  Regression -> MSE: 0.000244, MAE: 0.011148, R²: -0.0788
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13427 | val 0.15549
  Epoch 020 - train 0.13423 | val 0.15941
  Epoch 021 - train 0.12314 | val 0.15990
  Regression -> MSE: 0.000143, MAE: 0.008297, R²: 0.0004
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13077 | val 0.14845
  Epoch 020 - train 0.13054 | val 0.15046
  Epoch 021 - train 0.13312 | val 0.15011
  Regression -> MSE: 0.000166, MAE: 0.010254, R²: -0.0056
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14154 | val 0.14530
  Epoch 020 - train 0.13314 | val 0.15015
  Epoch 021 - train 0.13481 | val 0.14982
  Regression -> MSE: 0.000086, MAE: 0.007081, R²: -0.0054
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14672 | val 0.16869
  Epoch 020 - train 0.14376 | val 0.17833
  Epoch 021 - train 0.13845 | val 0.17699
  Regression -> MSE: 0.000212, MAE: 0.011066, R²: -0.0032
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12628 | val 0.11174
  Epoch 020 - train 0.12075 | val 0.11389
  Epoch 021 - train 0.12213 | val 0.11362
  Regression -> MSE: 0.000099, MAE: 0.008208, R²: -0.0746
  Directional -> Accuracy: 0.5179, MCC: 0.1949, F1: 0.2703

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14686 | val 0.09313
  Epoch 020 - train 0.14810 | val 0.10351
  Epoch 021 - train 0.14596 | val 0.10529
  Regression -> MSE: 0.000105, MAE: 0.008826, R²: -0.0145
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13786 | val 0.12973
  Epoch 020 - train 0.13218 | val 0.17016
  Epoch 021 - train 0.13453 | val 0.17222
  Regression -> MSE: 0.000236, MAE: 0.012721, R²: -0.0208
  Directional -> Accuracy: 0.6047, MCC: 0.2242, F1: 0.6222

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14303 | val 0.14636
  Epoch 020 - train 0.13657 | val 0.14512
  Epoch 021 - train 0.14397 | val 0.14515
  Regression -> MSE: 0.000170, MAE: 0.007828, R²: -0.0200
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12519 | val 0.10567
  Epoch 020 - train 0.14187 | val 0.10599
  Epoch 021 - train 0.13957 | val 0.10595
  Regression -> MSE: 0.000239, MAE: 0.011987, R²: -0.0091
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12215 | val 0.18784
  Epoch 020 - train 0.12035 | val 0.18515
  Epoch 021 - train 0.13272 | val 0.18482
  Regression -> MSE: 0.000231, MAE: 0.009939, R²: -0.0041
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14131 | val 0.15361
  Epoch 020 - train 0.13695 | val 0.15571
  Epoch 021 - train 0.12975 | val 0.15574
  Regression -> MSE: 0.000141, MAE: 0.008480, R²: -0.0432
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13530 | val 0.15863
  Epoch 020 - train 0.13857 | val 0.16685
  Epoch 021 - train 0.13410 | val 0.16663
  Regression -> MSE: 0.000191, MAE: 0.010405, R²: -0.0151
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11967 | val 0.14697
  Epoch 020 - train 0.11416 | val 0.14819
  Epoch 021 - train 0.12135 | val 0.14801
  Regression -> MSE: 0.000270, MAE: 0.010622, R²: -0.0320
  Directional -> Accuracy: 0.5342, MCC: 0.1602, F1: 0.4138

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14521 | val 0.10011
  Epoch 020 - train 0.14203 | val 0.10902
  Epoch 021 - train 0.14915 | val 0.11104
  Regression -> MSE: 0.000169, MAE: 0.010371, R²: -0.0143
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12494 | val 0.12773
  Epoch 020 - train 0.13297 | val 0.12853
  Epoch 021 - train 0.13218 | val 0.12835
  Regression -> MSE: 0.000189, MAE: 0.010639, R²: -0.0475
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13477 | val 0.11827
  Epoch 020 - train 0.14274 | val 0.11865
  Epoch 021 - train 0.13593 | val 0.11891
  Regression -> MSE: 0.000348, MAE: 0.011749, R²: -0.0146
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14244 | val 0.08287
  Epoch 020 - train 0.15320 | val 0.10091
  Epoch 021 - train 0.14147 | val 0.10205
  Regression -> MSE: 0.000132, MAE: 0.008612, R²: -0.2589
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13246 | val 0.16577
  Epoch 020 - train 0.13648 | val 0.17193
  Epoch 021 - train 0.13786 | val 0.17156
  Regression -> MSE: 0.000219, MAE: 0.011266, R²: -0.0011
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13541 | val 0.20179
  Epoch 020 - train 0.13449 | val 0.20009
  Epoch 021 - train 0.13917 | val 0.20011
  Regression -> MSE: 0.000084, MAE: 0.007152, R²: -0.0819
  Directional -> Accuracy: 0.4043, MCC: 0.0267, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13060 | val 0.08862
  Epoch 020 - train 0.12831 | val 0.08856
  Epoch 021 - train 0.12870 | val 0.08869
  Regression -> MSE: 0.000311, MAE: 0.014002, R²: -0.0099
  Directional -> Accuracy: 0.5102, MCC: 0.2071, F1: 0.5714

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15173 | val 0.07973
  Epoch 020 - train 0.15177 | val 0.09191
  Epoch 021 - train 0.13747 | val 0.09405
  Regression -> MSE: 0.000256, MAE: 0.011457, R²: -0.0500
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14071 | val 0.14296
  Epoch 020 - train 0.12495 | val 0.14256
  Epoch 021 - train 0.13170 | val 0.14283
  Regression -> MSE: 0.000083, MAE: 0.007055, R²: -0.0265
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12826 | val 0.15012
  Epoch 020 - train 0.13162 | val 0.15555
  Epoch 021 - train 0.13895 | val 0.15541
  Regression -> MSE: 0.000307, MAE: 0.014481, R²: -0.0009
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14683 | val 0.13740
  Epoch 020 - train 0.13125 | val 0.14685
  Epoch 021 - train 0.13621 | val 0.14772
  Regression -> MSE: 0.000100, MAE: 0.007136, R²: -0.0169
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15658 | val 0.14708
  Epoch 020 - train 0.16052 | val 0.16509
  Epoch 021 - train 0.15440 | val 0.16614
  Regression -> MSE: 0.000176, MAE: 0.010268, R²: -0.0263
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12920 | val 0.13829
  Epoch 020 - train 0.12411 | val 0.14471
  Epoch 021 - train 0.12901 | val 0.14570
  Regression -> MSE: 0.000223, MAE: 0.011758, R²: 0.0006
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13323 | val 0.13396
  Epoch 020 - train 0.14004 | val 0.13617
  Epoch 021 - train 0.14047 | val 0.13643

[I 2026-02-23 23:41:12,162] Trial 41 finished with value: -0.011436715176040049 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 6.58172476870409e-06, 'weight_decay': 2.0838955686531e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.17830359610760593, 'early_stopping_min_delta': 0.00826123032309715}. Best is trial 41 with value: -0.011436715176040049.

  Epoch 020 - train 0.12300 | val 0.21836
  Epoch 021 - train 0.13352 | val 0.22057
  Regression -> MSE: 0.000243, MAE: 0.012362, R²: -0.0247
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.30638 | val 0.37019
  Epoch 020 - train 0.29915 | val 0.36782
  Epoch 021 - train 0.28382 | val 0.36825
  Regression -> MSE: 0.000248, MAE: 0.012544, R²: -0.0021
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.28001 | val 0.27851
  Epoch 020 - train 0.32005 | val 0.32583
  Epoch 021 - train 0.29711 | val 0.32678
  Regression -> MSE: 0.000696, MAE: 0.019530, R²: -0.0168
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.29383 | val 0.45642
  Epoch 020 - train 0.29540 | val 0.45492
  Epoch 030 - train 0.27296 | val 0.45336
  Regression -> MSE: 0.000305, MAE: 0.014282, R²: 0.0184
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.29548 | val 0.28764
  Epoch 020 - train 0.28898 | val 0.32039
  Epoch 021 - train 0.29355 | val 0.30924
  Regression -> MSE: 0.000395, MAE: 0.015387, R²: -0.1310
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.28798 | val 0.27161
  Epoch 020 - train 0.32089 | val 0.26858
  Epoch 021 - train 0.29582 | val 0.26868
  Regression -> MSE: 0.000204, MAE: 0.010059, R²: -0.0009
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.30810 | val 0.58503
  Epoch 020 - train 0.32153 | val 0.75406
  Epoch 021 - train 0.33429 | val 0.75771
  Regression -> MSE: 0.000611, MAE: 0.019242, R²: -0.1013
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.31499 | val 0.33190
  Epoch 020 - train 0.29074 | val 0.33183
  Epoch 028 - train 0.31534 | val 0.33308
  Regression -> MSE: 0.000246, MAE: 0.012067, R²: -0.0025
  Directional -> Accuracy: 0.5217, MCC: 0.1078, F1: 0.5479

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.33750 | val 0.36851
  Epoch 020 - train 0.33757 | val 0.40396
  Epoch 021 - train 0.30921 | val 0.40550
  Regression -> MSE: 0.000626, MAE: 0.019804, R²: -0.0469
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.27002 | val 0.34992
  Epoch 020 - train 0.30147 | val 0.37794
  Epoch 021 - train 0.27820 | val 0.37778
  Regression -> MSE: 0.000384, MAE: 0.016091, R²: -0.0016
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.31371 | val 0.41068
  Epoch 020 - train 0.30262 | val 0.41511
  Epoch 021 - train 0.30221 | val 0.41622
  Regression -> MSE: 0.000242, MAE: 0.011945, R²: -0.0013
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.30611 | val 0.39204
  Epoch 020 - train 0.28112 | val 0.41660
  Epoch 021 - train 0.28615 | val 0.41596
  Regression -> MSE: 0.000324, MAE: 0.013597, R²: -0.0411
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.30895 | val 0.34072
  Epoch 020 - train 0.29639 | val 0.34689
  Epoch 021 - train 0.29153 | val 0.34813
  Regression -> MSE: 0.000678, MAE: 0.019489, R²: -0.0018
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.31816 | val 0.25677
  Epoch 020 - train 0.30970 | val 0.28404
  Epoch 030 - train 0.27753 | val 0.28474
  Regression -> MSE: 0.000162, MAE: 0.010007, R²: -0.1725
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.27572 | val 0.41014
  Epoch 020 - train 0.28628 | val 0.42333
  Epoch 021 - train 0.28545 | val 0.42283
  Regression -> MSE: 0.000226, MAE: 0.010791, R²: -0.0047
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.32486 | val 0.59676
  Epoch 020 - train 0.31774 | val 0.62070
  Epoch 021 - train 0.30572 | val 0.62291
  Regression -> MSE: 0.000363, MAE: 0.016122, R²: -0.0020
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.30194 | val 0.28221
  Epoch 020 - train 0.30473 | val 0.28344
  Epoch 021 - train 0.29753 | val 0.28334
  Regression -> MSE: 0.000111, MAE: 0.007972, R²: -0.0333
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.30575 | val 0.48307
  Epoch 020 - train 0.29390 | val 0.48557
  Epoch 021 - train 0.29072 | val 0.48805
  Regression -> MSE: 0.000157, MAE: 0.009560, R²: -0.0099
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.31579 | val 0.28668
  Epoch 020 - train 0.29707 | val 0.29042
  Epoch 021 - train 0.28908 | val 0.29033
  Regression -> MSE: 0.000280, MAE: 0.013400, R²: -0.0279
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.26219 | val 0.37423
  Epoch 020 - train 0.25046 | val 0.37273
  Epoch 021 - train 0.27043 | val 0.37277
  Regression -> MSE: 0.000156, MAE: 0.008781, R²: -0.0396
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.30404 | val 0.42036
  Epoch 020 - train 0.31091 | val 0.42311
  Epoch 021 - train 0.31777 | val 0.42266
  Regression -> MSE: 0.000235, MAE: 0.011002, R²: -0.0379
  Directional -> Accuracy: 0.4133, MCC: -0.1836, F1: 0.4634

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.30453 | val 0.34783
  Epoch 020 - train 0.31984 | val 0.36779
  Epoch 021 - train 0.32495 | val 0.36963
  Regression -> MSE: 0.000153, MAE: 0.008806, R²: -0.0646
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.29233 | val 0.32472
  Epoch 020 - train 0.25712 | val 0.32515
  Epoch 021 - train 0.29640 | val 0.32509
  Regression -> MSE: 0.000170, MAE: 0.010264, R²: -0.0274
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.30854 | val 0.33365
  Epoch 020 - train 0.29001 | val 0.33934
  Epoch 021 - train 0.30291 | val 0.33839
  Regression -> MSE: 0.000085, MAE: 0.007054, R²: -0.0012
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.32744 | val 0.49799
  Epoch 020 - train 0.31352 | val 0.49798
  Epoch 021 - train 0.30807 | val 0.49312
  Regression -> MSE: 0.000215, MAE: 0.011469, R²: -0.0147
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.25514 | val 0.23789
  Epoch 020 - train 0.26780 | val 0.23696
  Epoch 021 - train 0.26633 | val 0.23689
  Regression -> MSE: 0.000095, MAE: 0.008103, R²: -0.0289
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.30697 | val 0.20208
  Epoch 020 - train 0.29828 | val 0.21178
  Epoch 021 - train 0.33589 | val 0.21369
  Regression -> MSE: 0.000106, MAE: 0.008881, R²: -0.0280
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.33639 | val 0.25679
  Epoch 020 - train 0.32840 | val 0.26022
  Epoch 021 - train 0.31487 | val 0.25954
  Regression -> MSE: 0.000239, MAE: 0.012813, R²: -0.0328
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.31681 | val 0.30869
  Epoch 020 - train 0.29877 | val 0.30715
  Epoch 029 - train 0.29960 | val 0.30520
  Regression -> MSE: 0.000197, MAE: 0.008704, R²: -0.1810
  Directional -> Accuracy: 0.4737, MCC: -0.0169, F1: 0.4231

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.28767 | val 0.23561
  Epoch 020 - train 0.29242 | val 0.25532
  Epoch 021 - train 0.31917 | val 0.25458
  Regression -> MSE: 0.000239, MAE: 0.011977, R²: -0.0104
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.30738 | val 0.44830
  Epoch 020 - train 0.27324 | val 0.45398
  Epoch 021 - train 0.30583 | val 0.45211
  Regression -> MSE: 0.000231, MAE: 0.009886, R²: -0.0025
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.35418 | val 0.32598
  Epoch 020 - train 0.33032 | val 0.36634
  Epoch 021 - train 0.33034 | val 0.36776
  Regression -> MSE: 0.000136, MAE: 0.008194, R²: -0.0097
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.31135 | val 0.37341
  Epoch 020 - train 0.31155 | val 0.38411
  Epoch 021 - train 0.34177 | val 0.38414
  Regression -> MSE: 0.000188, MAE: 0.010441, R²: -0.0003
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.28840 | val 0.33084
  Epoch 020 - train 0.28053 | val 0.32606
  Epoch 021 - train 0.28445 | val 0.32685
  Regression -> MSE: 0.000262, MAE: 0.010534, R²: -0.0012
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.29404 | val 0.23175
  Epoch 020 - train 0.26996 | val 0.23160
  Epoch 021 - train 0.28694 | val 0.23128
  Regression -> MSE: 0.000167, MAE: 0.010368, R²: -0.0030
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.27980 | val 0.28512
  Epoch 020 - train 0.25815 | val 0.28671
  Epoch 021 - train 0.28576 | val 0.28623
  Regression -> MSE: 0.000185, MAE: 0.010510, R²: -0.0272
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.28603 | val 0.26065
  Epoch 020 - train 0.27739 | val 0.25733
  Epoch 021 - train 0.29607 | val 0.25722
  Regression -> MSE: 0.000352, MAE: 0.011821, R²: -0.0278
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.30806 | val 0.16365
  Epoch 020 - train 0.31571 | val 0.17396
  Epoch 021 - train 0.31698 | val 0.17452
  Regression -> MSE: 0.000127, MAE: 0.008520, R²: -0.2079
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.31452 | val 0.37611
  Epoch 020 - train 0.30626 | val 0.37648
  Epoch 021 - train 0.31204 | val 0.37734
  Regression -> MSE: 0.000220, MAE: 0.011321, R²: -0.0043
  Directional -> Accuracy: 0.4912, MCC: 0.0458, F1: 0.6329

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.30274 | val 0.50124
  Epoch 020 - train 0.30844 | val 0.51413
  Epoch 021 - train 0.29906 | val 0.51532
  Regression -> MSE: 0.000086, MAE: 0.007240, R²: -0.1033
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.34961 | val 0.19003
  Epoch 020 - train 0.33731 | val 0.18958
  Epoch 021 - train 0.34227 | val 0.18988
  Regression -> MSE: 0.000310, MAE: 0.013898, R²: -0.0071
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.33680 | val 0.15260
  Epoch 020 - train 0.31693 | val 0.14715
  Epoch 030 - train 0.29348 | val 0.14392
  Regression -> MSE: 0.000253, MAE: 0.011589, R²: -0.0370
  Directional -> Accuracy: 0.5000, MCC: -0.0823, F1: 0.6545

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.27413 | val 0.35151
  Epoch 020 - train 0.29035 | val 0.35460
  Epoch 021 - train 0.26657 | val 0.35428
  Regression -> MSE: 0.000084, MAE: 0.007048, R²: -0.0424
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.34315 | val 0.34610
  Epoch 020 - train 0.30266 | val 0.33764
  Epoch 030 - train 0.31958 | val 0.33180
  Regression -> MSE: 0.000324, MAE: 0.014495, R²: -0.0575
  Directional -> Accuracy: 0.5745, MCC: 0.1476, F1: 0.6154

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.29453 | val 0.32077
  Epoch 020 - train 0.31050 | val 0.35456
  Epoch 021 - train 0.32045 | val 0.35699
  Regression -> MSE: 0.000102, MAE: 0.007115, R²: -0.0354
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.31455 | val 0.33651
  Epoch 020 - train 0.32040 | val 0.33150
  Epoch 030 - train 0.31518 | val 0.33290
  Regression -> MSE: 0.000179, MAE: 0.010066, R²: -0.0411
  Directional -> Accuracy: 0.3673, MCC: -0.1462, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.26454 | val 0.29515
  Epoch 020 - train 0.28702 | val 0.29623
  Epoch 029 - train 0.29342 | val 0.29731
  Regression -> MSE: 0.000224, MAE: 0.011422, R²: -0.0033
  Directional -> Accuracy: 0.6786, MCC: 0.3641, F1: 0.6786

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.28909 | val 0.30447
  Epoch 020 - train 0.28269 | val 0.30821
  Epoch 021 - train 0.31159 | val 0.30804

[I 2026-02-23 23:43:26,325] Trial 42 finished with value: -0.011470196976652296 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 1.572416721919316e-05, 'weight_decay': 1.1972714568180678e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.4839546722056245, 'early_stopping_min_delta': 0.005836685762704103}. Best is trial 41 with value: -0.011436715176040049.

  Epoch 020 - train 0.28921 | val 0.41225
  Epoch 021 - train 0.29450 | val 0.41295
  Regression -> MSE: 0.000237, MAE: 0.012442, R²: 0.0022
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.29687 | val 0.40635
  Epoch 020 - train 0.29237 | val 0.40310
  Epoch 021 - train 0.28689 | val 0.40357
  Regression -> MSE: 0.000256, MAE: 0.012882, R²: -0.0338
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.29434 | val 0.25159
  Epoch 020 - train 0.29779 | val 0.30151
  Epoch 027 - train 0.26891 | val 0.30542
  Regression -> MSE: 0.000688, MAE: 0.019382, R²: -0.0056
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.35934 | val 0.48612
  Epoch 020 - train 0.33442 | val 0.49852
  Epoch 021 - train 0.31855 | val 0.49798
  Regression -> MSE: 0.000326, MAE: 0.014568, R²: -0.0501
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.25064 | val 0.26606
  Epoch 020 - train 0.25312 | val 0.25283
  Epoch 021 - train 0.26308 | val 0.25329
  Regression -> MSE: 0.000360, MAE: 0.014770, R²: -0.0318
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.28895 | val 0.26649
  Epoch 020 - train 0.30904 | val 0.26200
  Epoch 030 - train 0.30485 | val 0.26360
  Regression -> MSE: 0.000196, MAE: 0.010111, R²: 0.0355
  Directional -> Accuracy: 0.5882, MCC: 0.2986, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.29938 | val 0.56509
  Epoch 020 - train 0.29511 | val 0.60598
  Epoch 021 - train 0.28117 | val 0.60905
  Regression -> MSE: 0.000592, MAE: 0.018828, R²: -0.0671
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.34508 | val 0.35758
  Epoch 020 - train 0.32893 | val 0.35709
  Epoch 021 - train 0.31344 | val 0.35753
  Regression -> MSE: 0.000251, MAE: 0.011949, R²: -0.0214
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.31891 | val 0.36945
  Epoch 020 - train 0.32484 | val 0.43253
  Epoch 021 - train 0.34264 | val 0.43957
  Regression -> MSE: 0.000619, MAE: 0.019661, R²: -0.0362
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.29490 | val 0.33120
  Epoch 020 - train 0.28137 | val 0.35318
  Epoch 021 - train 0.30141 | val 0.35486
  Regression -> MSE: 0.000400, MAE: 0.016048, R²: -0.0420
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.29299 | val 0.41086
  Epoch 020 - train 0.30125 | val 0.42641
  Epoch 021 - train 0.32235 | val 0.42726
  Regression -> MSE: 0.000249, MAE: 0.011639, R²: -0.0301
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.29512 | val 0.41908
  Epoch 020 - train 0.27707 | val 0.42628
  Epoch 021 - train 0.30013 | val 0.42643
  Regression -> MSE: 0.000314, MAE: 0.013629, R²: -0.0089
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.29349 | val 0.34347
  Epoch 020 - train 0.32625 | val 0.35973
  Epoch 021 - train 0.30353 | val 0.35996
  Regression -> MSE: 0.000677, MAE: 0.019473, R²: 0.0006
  Directional -> Accuracy: 0.6034, MCC: 0.2417, F1: 0.6849

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.30382 | val 0.26441
  Epoch 020 - train 0.27851 | val 0.26562
  Epoch 021 - train 0.29473 | val 0.26590
  Regression -> MSE: 0.000145, MAE: 0.009529, R²: -0.0518
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.29142 | val 0.42764
  Epoch 020 - train 0.29060 | val 0.44327
  Epoch 021 - train 0.28511 | val 0.44271
  Regression -> MSE: 0.000226, MAE: 0.010808, R²: -0.0028
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.29708 | val 0.63649
  Epoch 020 - train 0.27651 | val 0.75116
  Epoch 021 - train 0.29671 | val 0.74954
  Regression -> MSE: 0.000362, MAE: 0.016041, R²: -0.0000
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.32678 | val 0.28041
  Epoch 020 - train 0.30914 | val 0.27744
  Epoch 030 - train 0.30751 | val 0.27711
  Regression -> MSE: 0.000109, MAE: 0.007926, R²: -0.0060
  Directional -> Accuracy: 0.5143, MCC: -0.0035, F1: 0.6047

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.29346 | val 0.51244
  Epoch 020 - train 0.27189 | val 0.53751
  Epoch 021 - train 0.28524 | val 0.53941
  Regression -> MSE: 0.000156, MAE: 0.009669, R²: -0.0037
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.31176 | val 0.33969
  Epoch 020 - train 0.28611 | val 0.34353
  Epoch 021 - train 0.31657 | val 0.34267
  Regression -> MSE: 0.000273, MAE: 0.013057, R²: -0.0017
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.26335 | val 0.36610
  Epoch 020 - train 0.25463 | val 0.36492
  Epoch 030 - train 0.25535 | val 0.36136
  Regression -> MSE: 0.000174, MAE: 0.009571, R²: -0.1642
  Directional -> Accuracy: 0.4769, MCC: 0.0333, F1: 0.3929

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.31565 | val 0.47041
  Epoch 020 - train 0.31417 | val 0.46333
  Epoch 021 - train 0.31224 | val 0.46292
  Regression -> MSE: 0.000238, MAE: 0.011046, R²: -0.0525
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.31215 | val 0.34481
  Epoch 020 - train 0.28054 | val 0.34375
  Epoch 021 - train 0.28426 | val 0.34424
  Regression -> MSE: 0.000149, MAE: 0.008669, R²: -0.0417
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.28172 | val 0.33813
  Epoch 020 - train 0.26523 | val 0.34148
  Epoch 021 - train 0.27204 | val 0.34204
  Regression -> MSE: 0.000174, MAE: 0.010272, R²: -0.0559
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.35535 | val 0.34944
  Epoch 020 - train 0.32678 | val 0.35178
  Epoch 021 - train 0.33746 | val 0.35331
  Regression -> MSE: 0.000095, MAE: 0.007522, R²: -0.1152
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.30569 | val 0.55478
  Epoch 020 - train 0.27665 | val 0.62742
  Epoch 021 - train 0.30697 | val 0.64365
  Regression -> MSE: 0.000211, MAE: 0.011077, R²: 0.0018
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.27320 | val 0.22817
  Epoch 020 - train 0.26924 | val 0.22476
  Epoch 030 - train 0.28018 | val 0.22135
  Regression -> MSE: 0.000095, MAE: 0.007963, R²: -0.0359
  Directional -> Accuracy: 0.4464, MCC: -0.1158, F1: 0.4918

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.32645 | val 0.21330
  Epoch 020 - train 0.29403 | val 0.21841
  Epoch 030 - train 0.26740 | val 0.23789
  Regression -> MSE: 0.000104, MAE: 0.008665, R²: -0.0113
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.33332 | val 0.25752
  Epoch 020 - train 0.33219 | val 0.26454
  Epoch 021 - train 0.31819 | val 0.26424
  Regression -> MSE: 0.000234, MAE: 0.012621, R²: -0.0095
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.29609 | val 0.31985
  Epoch 020 - train 0.27360 | val 0.32131
  Epoch 021 - train 0.30020 | val 0.32124
  Regression -> MSE: 0.000177, MAE: 0.007917, R²: -0.0662
  Directional -> Accuracy: 0.3684, MCC: -0.2434, F1: 0.3333

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.32233 | val 0.21490
  Epoch 020 - train 0.31256 | val 0.22536
  Epoch 021 - train 0.32334 | val 0.22776
  Regression -> MSE: 0.000238, MAE: 0.011894, R²: -0.0043
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.30964 | val 0.46160
  Epoch 020 - train 0.31125 | val 0.48465
  Epoch 021 - train 0.31251 | val 0.48579
  Regression -> MSE: 0.000232, MAE: 0.009961, R²: -0.0063
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.33844 | val 0.33245
  Epoch 020 - train 0.31902 | val 0.33164
  Epoch 021 - train 0.31894 | val 0.33232
  Regression -> MSE: 0.000136, MAE: 0.008268, R²: -0.0105
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.28593 | val 0.36732
  Epoch 020 - train 0.29323 | val 0.37214
  Epoch 021 - train 0.30198 | val 0.37318
  Regression -> MSE: 0.000188, MAE: 0.010486, R²: 0.0018
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.28361 | val 0.33370
  Epoch 020 - train 0.26593 | val 0.33108
  Epoch 021 - train 0.27091 | val 0.33157
  Regression -> MSE: 0.000274, MAE: 0.010750, R²: -0.0447
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.29367 | val 0.22484
  Epoch 020 - train 0.30026 | val 0.23012
  Epoch 021 - train 0.30700 | val 0.23074
  Regression -> MSE: 0.000169, MAE: 0.010367, R²: -0.0129
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.30376 | val 0.26770
  Epoch 020 - train 0.29417 | val 0.28180
  Epoch 021 - train 0.29280 | val 0.28117
  Regression -> MSE: 0.000183, MAE: 0.010417, R²: -0.0181
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.29725 | val 0.26337
  Epoch 020 - train 0.29186 | val 0.26515
  Epoch 021 - train 0.31468 | val 0.26479
  Regression -> MSE: 0.000342, MAE: 0.011795, R²: 0.0011
  Directional -> Accuracy: 0.5373, MCC: 0.0693, F1: 0.5753

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.34746 | val 0.16032
  Epoch 020 - train 0.29839 | val 0.15902
  Epoch 021 - train 0.30670 | val 0.15888
  Regression -> MSE: 0.000113, MAE: 0.008359, R²: -0.0739
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.30299 | val 0.38661
  Epoch 020 - train 0.31047 | val 0.39713
  Epoch 021 - train 0.30909 | val 0.39767
  Regression -> MSE: 0.000219, MAE: 0.011283, R²: -0.0007
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.29665 | val 0.49186
  Epoch 020 - train 0.29437 | val 0.49087
  Epoch 021 - train 0.29582 | val 0.49016
  Regression -> MSE: 0.000095, MAE: 0.007607, R²: -0.2236
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.33225 | val 0.22347
  Epoch 020 - train 0.34791 | val 0.23419
  Epoch 021 - train 0.30980 | val 0.23401
  Regression -> MSE: 0.000333, MAE: 0.015096, R²: -0.0811
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.33625 | val 0.14683
  Epoch 020 - train 0.29001 | val 0.15293
  Epoch 021 - train 0.28941 | val 0.15495
  Regression -> MSE: 0.000249, MAE: 0.011523, R²: -0.0224
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.28000 | val 0.35265
  Epoch 020 - train 0.28374 | val 0.35108
  Epoch 021 - train 0.27668 | val 0.35151
  Regression -> MSE: 0.000081, MAE: 0.007096, R²: -0.0033
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.31654 | val 0.37795
  Epoch 020 - train 0.30779 | val 0.47047
  Epoch 021 - train 0.35233 | val 0.46829
  Regression -> MSE: 0.000309, MAE: 0.014478, R²: -0.0075
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.27984 | val 0.30459
  Epoch 020 - train 0.28071 | val 0.29592
  Epoch 030 - train 0.27794 | val 0.29295
  Regression -> MSE: 0.000097, MAE: 0.007322, R²: 0.0099
  Directional -> Accuracy: 0.3864, MCC: -0.1839, F1: 0.1818

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.33237 | val 0.34585
  Epoch 020 - train 0.35706 | val 0.36364
  Epoch 021 - train 0.36111 | val 0.36446
  Regression -> MSE: 0.000174, MAE: 0.010004, R²: -0.0097
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.28854 | val 0.36924
  Epoch 020 - train 0.29764 | val 0.40140
  Epoch 021 - train 0.29230 | val 0.40757
  Regression -> MSE: 0.000224, MAE: 0.011757, R²: -0.0024
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.34589 | val 0.32210
  Epoch 020 - train 0.36069 | val 0.32895
  Epoch 021 - train 0.38379 | val 0.32917

[I 2026-02-23 23:45:35,239] Trial 43 finished with value: -0.011465236398915023 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 1.5730843519164924e-05, 'weight_decay': 1.5386504809571702e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.49397923962326096, 'early_stopping_min_delta': 0.006017056142354408}. Best is trial 41 with value: -0.011436715176040049.

  Epoch 020 - train 0.30431 | val 0.43062
  Epoch 021 - train 0.29839 | val 0.43059
  Regression -> MSE: 0.000238, MAE: 0.012412, R²: -0.0020
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07700 | val 0.08977
  Epoch 020 - train 0.08106 | val 0.08948
  Epoch 021 - train 0.07579 | val 0.08932
  Regression -> MSE: 0.000248, MAE: 0.012541, R²: -0.0010
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07956 | val 0.06798
  Epoch 020 - train 0.08449 | val 0.06746
  Epoch 021 - train 0.07675 | val 0.06745
  Regression -> MSE: 0.000685, MAE: 0.019356, R²: -0.0006
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.08633 | val 0.12179
  Epoch 020 - train 0.09044 | val 0.13763
  Epoch 021 - train 0.08086 | val 0.13724
  Regression -> MSE: 0.000310, MAE: 0.014443, R²: -0.0008
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06871 | val 0.08841
  Epoch 020 - train 0.07058 | val 0.08925
  Epoch 021 - train 0.07258 | val 0.09006
  Regression -> MSE: 0.000351, MAE: 0.014624, R²: -0.0035
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.08131 | val 0.07954
  Epoch 020 - train 0.08601 | val 0.08589
  Epoch 021 - train 0.08754 | val 0.08542
  Regression -> MSE: 0.000204, MAE: 0.010188, R²: -0.0034
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07842 | val 0.13372
  Epoch 020 - train 0.07455 | val 0.13984
  Epoch 021 - train 0.07484 | val 0.14042
  Regression -> MSE: 0.000582, MAE: 0.018612, R²: -0.0476
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.08182 | val 0.08847
  Epoch 020 - train 0.08233 | val 0.08822
  Epoch 021 - train 0.07665 | val 0.08837
  Regression -> MSE: 0.000247, MAE: 0.011953, R²: -0.0057
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07941 | val 0.08850
  Epoch 020 - train 0.08006 | val 0.08459
  Epoch 030 - train 0.07768 | val 0.08560
  Regression -> MSE: 0.000602, MAE: 0.018969, R²: -0.0081
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07989 | val 0.08659
  Epoch 020 - train 0.08130 | val 0.08559
  Epoch 021 - train 0.07475 | val 0.08549
  Regression -> MSE: 0.000388, MAE: 0.015962, R²: -0.0119
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.08267 | val 0.10884
  Epoch 020 - train 0.08191 | val 0.10932
  Epoch 021 - train 0.07743 | val 0.10937
  Regression -> MSE: 0.000246, MAE: 0.011640, R²: -0.0203
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.07688 | val 0.09991
  Epoch 020 - train 0.07381 | val 0.10171
  Epoch 021 - train 0.08033 | val 0.10168
  Regression -> MSE: 0.000323, MAE: 0.013602, R²: -0.0383
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08387 | val 0.09167
  Epoch 020 - train 0.07737 | val 0.09865
  Epoch 021 - train 0.08636 | val 0.09836
  Regression -> MSE: 0.000676, MAE: 0.019488, R²: 0.0025
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.08435 | val 0.07213
  Epoch 020 - train 0.08064 | val 0.07723
  Epoch 021 - train 0.07841 | val 0.07728
  Regression -> MSE: 0.000146, MAE: 0.009558, R²: -0.0586
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.07713 | val 0.09416
  Epoch 020 - train 0.07708 | val 0.10338
  Epoch 027 - train 0.07790 | val 0.10219
  Regression -> MSE: 0.000226, MAE: 0.010694, R²: -0.0044
  Directional -> Accuracy: 0.5246, MCC: 0.0690, F1: 0.3556

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07678 | val 0.14089
  Epoch 020 - train 0.07657 | val 0.14468
  Epoch 021 - train 0.07459 | val 0.14489
  Regression -> MSE: 0.000362, MAE: 0.016157, R²: 0.0005
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.08149 | val 0.07623
  Epoch 020 - train 0.08048 | val 0.07710
  Epoch 021 - train 0.08207 | val 0.07692
  Regression -> MSE: 0.000107, MAE: 0.007968, R²: 0.0034
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08045 | val 0.14324
  Epoch 020 - train 0.07678 | val 0.16106
  Epoch 021 - train 0.07939 | val 0.16034
  Regression -> MSE: 0.000156, MAE: 0.009667, R²: -0.0000
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07971 | val 0.07844
  Epoch 020 - train 0.08032 | val 0.07848
  Epoch 021 - train 0.08183 | val 0.07860
  Regression -> MSE: 0.000282, MAE: 0.013496, R²: -0.0357
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07341 | val 0.09363
  Epoch 020 - train 0.07144 | val 0.09355
  Epoch 021 - train 0.06894 | val 0.09358
  Regression -> MSE: 0.000167, MAE: 0.009136, R²: -0.1196
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.08717 | val 0.12071
  Epoch 020 - train 0.08152 | val 0.12098
  Epoch 021 - train 0.07707 | val 0.12095
  Regression -> MSE: 0.000235, MAE: 0.010975, R²: -0.0404
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08405 | val 0.08887
  Epoch 020 - train 0.08679 | val 0.08959
  Epoch 021 - train 0.08143 | val 0.08952
  Regression -> MSE: 0.000143, MAE: 0.008319, R²: -0.0009
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07651 | val 0.08161
  Epoch 020 - train 0.07462 | val 0.08151
  Epoch 021 - train 0.07637 | val 0.08142
  Regression -> MSE: 0.000166, MAE: 0.010293, R²: -0.0049
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08109 | val 0.08582
  Epoch 020 - train 0.08164 | val 0.08571
  Epoch 021 - train 0.07902 | val 0.08550
  Regression -> MSE: 0.000086, MAE: 0.007112, R²: -0.0127
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.08408 | val 0.09097
  Epoch 020 - train 0.08478 | val 0.09275
  Epoch 021 - train 0.08366 | val 0.09345
  Regression -> MSE: 0.000213, MAE: 0.011077, R²: -0.0037
  Directional -> Accuracy: 0.5000, MCC: -0.0172, F1: 0.4000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07893 | val 0.07003
  Epoch 020 - train 0.07854 | val 0.07100
  Epoch 021 - train 0.07989 | val 0.07088
  Regression -> MSE: 0.000105, MAE: 0.008361, R²: -0.1447
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07805 | val 0.05662
  Epoch 020 - train 0.07735 | val 0.05612
  Epoch 021 - train 0.07877 | val 0.05631
  Regression -> MSE: 0.000105, MAE: 0.008857, R²: -0.0213
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.08307 | val 0.06845
  Epoch 020 - train 0.07855 | val 0.06967
  Epoch 021 - train 0.08114 | val 0.06968
  Regression -> MSE: 0.000232, MAE: 0.012555, R²: -0.0011
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.08238 | val 0.08377
  Epoch 020 - train 0.08038 | val 0.08376
  Epoch 021 - train 0.07452 | val 0.08362
  Regression -> MSE: 0.000173, MAE: 0.007819, R²: -0.0390
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08312 | val 0.06144
  Epoch 020 - train 0.08017 | val 0.06286
  Epoch 021 - train 0.08363 | val 0.06332
  Regression -> MSE: 0.000237, MAE: 0.011881, R²: -0.0018
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07973 | val 0.11037
  Epoch 020 - train 0.09143 | val 0.11245
  Epoch 021 - train 0.07997 | val 0.11260
  Regression -> MSE: 0.000231, MAE: 0.009881, R²: -0.0019
  Directional -> Accuracy: 0.4651, MCC: -0.0810, F1: 0.6102

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.08165 | val 0.08300
  Epoch 020 - train 0.07757 | val 0.08618
  Epoch 021 - train 0.07593 | val 0.08637
  Regression -> MSE: 0.000135, MAE: 0.008173, R²: -0.0005
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08239 | val 0.08990
  Epoch 020 - train 0.08162 | val 0.09078
  Epoch 021 - train 0.08122 | val 0.09060
  Regression -> MSE: 0.000189, MAE: 0.010376, R²: -0.0053
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07635 | val 0.08188
  Epoch 020 - train 0.07365 | val 0.07960
  Epoch 021 - train 0.07366 | val 0.08021
  Regression -> MSE: 0.000263, MAE: 0.010541, R²: -0.0044
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08445 | val 0.06083
  Epoch 020 - train 0.07794 | val 0.06203
  Epoch 021 - train 0.07687 | val 0.06240
  Regression -> MSE: 0.000168, MAE: 0.010372, R²: -0.0062
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.07988 | val 0.07396
  Epoch 020 - train 0.07954 | val 0.08467
  Epoch 021 - train 0.08180 | val 0.08478
  Regression -> MSE: 0.000181, MAE: 0.010265, R²: -0.0046
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07829 | val 0.06677
  Epoch 020 - train 0.07411 | val 0.06717
  Epoch 021 - train 0.07399 | val 0.06704
  Regression -> MSE: 0.000346, MAE: 0.011723, R²: -0.0088
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08463 | val 0.04819
  Epoch 020 - train 0.08257 | val 0.05081
  Epoch 021 - train 0.07663 | val 0.05094
  Regression -> MSE: 0.000119, MAE: 0.008360, R²: -0.1282
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07967 | val 0.09621
  Epoch 020 - train 0.07973 | val 0.09753
  Epoch 021 - train 0.07456 | val 0.09751
  Regression -> MSE: 0.000220, MAE: 0.011368, R²: -0.0089
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.08024 | val 0.12044
  Epoch 020 - train 0.07986 | val 0.12180
  Epoch 021 - train 0.07720 | val 0.12202
  Regression -> MSE: 0.000087, MAE: 0.007307, R²: -0.1229
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07615 | val 0.06027
  Epoch 020 - train 0.08355 | val 0.05580
  Epoch 030 - train 0.07824 | val 0.05430
  Regression -> MSE: 0.000309, MAE: 0.013352, R²: -0.0048
  Directional -> Accuracy: 0.5918, MCC: 0.0343, F1: 0.2857

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.08107 | val 0.04506
  Epoch 020 - train 0.08165 | val 0.04551
  Epoch 021 - train 0.08929 | val 0.04563
  Regression -> MSE: 0.000244, MAE: 0.011584, R²: -0.0016
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08008 | val 0.08939
  Epoch 020 - train 0.08365 | val 0.08957
  Epoch 021 - train 0.07709 | val 0.08966
  Regression -> MSE: 0.000081, MAE: 0.007103, R²: -0.0039
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.08704 | val 0.08654
  Epoch 020 - train 0.07881 | val 0.09300
  Epoch 021 - train 0.07925 | val 0.09345
  Regression -> MSE: 0.000308, MAE: 0.014523, R²: -0.0029
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08178 | val 0.07918
  Epoch 020 - train 0.08190 | val 0.07803
  Epoch 021 - train 0.07578 | val 0.07773
  Regression -> MSE: 0.000099, MAE: 0.007193, R²: -0.0069
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.09195 | val 0.08212
  Epoch 020 - train 0.08535 | val 0.08115
  Epoch 021 - train 0.08458 | val 0.08106
  Regression -> MSE: 0.000172, MAE: 0.009716, R²: -0.0008
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07246 | val 0.08366
  Epoch 020 - train 0.07626 | val 0.08630
  Epoch 021 - train 0.07086 | val 0.08629
  Regression -> MSE: 0.000223, MAE: 0.011772, R²: -0.0005
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.08129 | val 0.08024
  Epoch 020 - train 0.07589 | val 0.08355
  Epoch 021 - train 0.07501 | val 0.08375

[I 2026-02-23 23:47:42,930] Trial 44 finished with value: -0.011362814469631832 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 6.376504186839398e-06, 'weight_decay': 2.503769291151163e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.10138018540459826, 'early_stopping_min_delta': 0.004466701790377047}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.07512 | val 0.11325
  Epoch 021 - train 0.08089 | val 0.11337
  Regression -> MSE: 0.000240, MAE: 0.012362, R²: -0.0103
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13833 | val 0.18429
  Epoch 020 - train 0.12893 | val 0.18356
  Epoch 021 - train 0.13717 | val 0.18351
  Regression -> MSE: 0.000242, MAE: 0.012379, R²: -0.0062
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13908 | val 0.12801
  Epoch 020 - train 0.13866 | val 0.15082
  Epoch 021 - train 0.13685 | val 0.14957
  Regression -> MSE: 0.000734, MAE: 0.020284, R²: -0.0511
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13823 | val 0.21776
  Epoch 020 - train 0.14417 | val 0.22086
  Epoch 021 - train 0.13387 | val 0.22121
  Regression -> MSE: 0.000315, MAE: 0.014547, R²: -0.0022
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13212 | val 0.17194
  Epoch 020 - train 0.13292 | val 0.16703
  Epoch 021 - train 0.12789 | val 0.16914
  Regression -> MSE: 0.000356, MAE: 0.014712, R²: -0.0078
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14653 | val 0.13013
  Epoch 020 - train 0.14137 | val 0.13162
  Epoch 021 - train 0.14947 | val 0.13127
  Regression -> MSE: 0.000207, MAE: 0.010185, R²: -0.0021
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12650 | val 0.23361
  Epoch 020 - train 0.12681 | val 0.24785
  Epoch 021 - train 0.12298 | val 0.24719
  Regression -> MSE: 0.000583, MAE: 0.018587, R²: -0.0300
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13997 | val 0.16280
  Epoch 020 - train 0.14353 | val 0.16275
  Epoch 021 - train 0.14186 | val 0.16241
  Regression -> MSE: 0.000251, MAE: 0.011956, R²: -0.0107
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13586 | val 0.12793
  Epoch 020 - train 0.13842 | val 0.11328
  Epoch 030 - train 0.13181 | val 0.11164
  Regression -> MSE: 0.000646, MAE: 0.020598, R²: -0.0572
  Directional -> Accuracy: 0.4048, MCC: -0.1578, F1: 0.4444

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13360 | val 0.15612
  Epoch 020 - train 0.13972 | val 0.15777
  Epoch 021 - train 0.13161 | val 0.15787
  Regression -> MSE: 0.000389, MAE: 0.015775, R²: -0.0433
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13827 | val 0.18075
  Epoch 020 - train 0.14047 | val 0.18175
  Epoch 021 - train 0.14276 | val 0.18195
  Regression -> MSE: 0.000245, MAE: 0.012098, R²: -0.0013
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13066 | val 0.18015
  Epoch 020 - train 0.13308 | val 0.17833
  Epoch 030 - train 0.12621 | val 0.17871
  Regression -> MSE: 0.000387, MAE: 0.014713, R²: -0.2387
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.17126 | val 0.18274
  Epoch 020 - train 0.16442 | val 0.19737
  Epoch 021 - train 0.17302 | val 0.19642
  Regression -> MSE: 0.000698, MAE: 0.020036, R²: -0.0183
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13792 | val 0.13993
  Epoch 020 - train 0.13648 | val 0.14497
  Epoch 021 - train 0.13813 | val 0.14534
  Regression -> MSE: 0.000138, MAE: 0.009075, R²: -0.0025
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12616 | val 0.16715
  Epoch 020 - train 0.12679 | val 0.16709
  Epoch 021 - train 0.11871 | val 0.16718
  Regression -> MSE: 0.000227, MAE: 0.010695, R²: -0.0037
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15682 | val 0.27975
  Epoch 020 - train 0.15645 | val 0.30624
  Epoch 021 - train 0.15770 | val 0.30411
  Regression -> MSE: 0.000371, MAE: 0.016439, R²: -0.0110
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13708 | val 0.14441
  Epoch 020 - train 0.13640 | val 0.14621
  Epoch 021 - train 0.13541 | val 0.14542
  Regression -> MSE: 0.000109, MAE: 0.007969, R²: -0.0048
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14143 | val 0.20750
  Epoch 020 - train 0.13739 | val 0.20360
  Epoch 030 - train 0.14029 | val 0.20358
  Regression -> MSE: 0.000160, MAE: 0.009616, R²: -0.0164
  Directional -> Accuracy: 0.5862, MCC: 0.1057, F1: 0.6757

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13722 | val 0.12573
  Epoch 020 - train 0.13819 | val 0.12539
  Epoch 021 - train 0.13169 | val 0.12590
  Regression -> MSE: 0.000282, MAE: 0.013452, R²: -0.0288
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12270 | val 0.17600
  Epoch 020 - train 0.12349 | val 0.17652
  Epoch 021 - train 0.11987 | val 0.17690
  Regression -> MSE: 0.000162, MAE: 0.009038, R²: -0.0681
  Directional -> Accuracy: 0.5156, MCC: 0.1672, F1: 0.3673

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14784 | val 0.20663
  Epoch 020 - train 0.14396 | val 0.20770
  Epoch 021 - train 0.14588 | val 0.20829
  Regression -> MSE: 0.000230, MAE: 0.010923, R²: -0.0104
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15669 | val 0.18600
  Epoch 020 - train 0.16314 | val 0.22259
  Epoch 021 - train 0.15510 | val 0.22254
  Regression -> MSE: 0.000145, MAE: 0.008353, R²: -0.0094
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13561 | val 0.16109
  Epoch 020 - train 0.13568 | val 0.16119
  Epoch 021 - train 0.13761 | val 0.16119
  Regression -> MSE: 0.000167, MAE: 0.010369, R²: -0.0048
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13735 | val 0.15489
  Epoch 020 - train 0.14388 | val 0.15990
  Epoch 027 - train 0.14753 | val 0.15970
  Regression -> MSE: 0.000088, MAE: 0.007215, R²: -0.0203
  Directional -> Accuracy: 0.5263, MCC: 0.0784, F1: 0.5091

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14742 | val 0.17506
  Epoch 020 - train 0.14106 | val 0.18289
  Epoch 025 - train 0.13859 | val 0.18383
  Regression -> MSE: 0.000210, MAE: 0.011134, R²: 0.0048
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12944 | val 0.12598
  Epoch 020 - train 0.12035 | val 0.12611
  Epoch 021 - train 0.12785 | val 0.12638
  Regression -> MSE: 0.000091, MAE: 0.007955, R²: -0.0125
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13669 | val 0.11258
  Epoch 020 - train 0.13551 | val 0.11975
  Epoch 021 - train 0.13555 | val 0.12071
  Regression -> MSE: 0.000106, MAE: 0.008858, R²: -0.0669
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13935 | val 0.12766
  Epoch 020 - train 0.15208 | val 0.15073
  Epoch 021 - train 0.14601 | val 0.14816
  Regression -> MSE: 0.000241, MAE: 0.012973, R²: -0.0158
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13951 | val 0.15532
  Epoch 020 - train 0.13799 | val 0.15704
  Epoch 021 - train 0.14309 | val 0.15721
  Regression -> MSE: 0.000176, MAE: 0.007947, R²: -0.0379
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13195 | val 0.11348
  Epoch 020 - train 0.13565 | val 0.11702
  Epoch 021 - train 0.12621 | val 0.11792
  Regression -> MSE: 0.000242, MAE: 0.012081, R²: 0.0001
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16966 | val 0.20636
  Epoch 020 - train 0.15984 | val 0.20997
  Epoch 021 - train 0.16177 | val 0.20976
  Regression -> MSE: 0.000236, MAE: 0.010038, R²: -0.0023
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13195 | val 0.14771
  Epoch 020 - train 0.14496 | val 0.17356
  Epoch 021 - train 0.14491 | val 0.17530
  Regression -> MSE: 0.000138, MAE: 0.008323, R²: -0.0011
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13500 | val 0.17038
  Epoch 020 - train 0.13397 | val 0.17155
  Epoch 021 - train 0.14119 | val 0.17138
  Regression -> MSE: 0.000192, MAE: 0.010454, R²: -0.0481
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12794 | val 0.15110
  Epoch 020 - train 0.13389 | val 0.15145
  Epoch 021 - train 0.12667 | val 0.15226
  Regression -> MSE: 0.000284, MAE: 0.011049, R²: -0.0690
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13518 | val 0.14931
  Epoch 020 - train 0.12614 | val 0.16938
  Epoch 021 - train 0.12371 | val 0.16955
  Regression -> MSE: 0.000187, MAE: 0.010564, R²: -0.0209
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13721 | val 0.14317
  Epoch 020 - train 0.13830 | val 0.14641
  Epoch 021 - train 0.13994 | val 0.14574
  Regression -> MSE: 0.000357, MAE: 0.012733, R²: -0.0274
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13975 | val 0.08538
  Epoch 020 - train 0.13880 | val 0.08708
  Epoch 021 - train 0.14028 | val 0.08709
  Regression -> MSE: 0.000127, MAE: 0.008545, R²: -0.2043
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13254 | val 0.17470
  Epoch 020 - train 0.13554 | val 0.17691
  Epoch 030 - train 0.13933 | val 0.17674
  Regression -> MSE: 0.000226, MAE: 0.011525, R²: -0.0300
  Directional -> Accuracy: 0.4286, MCC: -0.1247, F1: 0.5429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14091 | val 0.22983
  Epoch 020 - train 0.14626 | val 0.23963
  Epoch 021 - train 0.14748 | val 0.23974
  Regression -> MSE: 0.000092, MAE: 0.007492, R²: -0.2473
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13170 | val 0.09490
  Epoch 020 - train 0.14111 | val 0.09646
  Epoch 021 - train 0.14040 | val 0.09711
  Regression -> MSE: 0.000332, MAE: 0.015004, R²: -0.0676
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12856 | val 0.16777
  Epoch 020 - train 0.13466 | val 0.16752
  Epoch 021 - train 0.13207 | val 0.16791
  Regression -> MSE: 0.000078, MAE: 0.006939, R²: 0.0006
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14698 | val 0.17342
  Epoch 020 - train 0.14437 | val 0.17675
  Epoch 021 - train 0.13933 | val 0.17637
  Regression -> MSE: 0.000302, MAE: 0.014338, R²: -0.0039
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12687 | val 0.15775
  Epoch 020 - train 0.13958 | val 0.16176
  Epoch 021 - train 0.13963 | val 0.16209
  Regression -> MSE: 0.000105, MAE: 0.007214, R²: -0.0358
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14449 | val 0.16443
  Epoch 020 - train 0.13520 | val 0.18669
  Epoch 021 - train 0.14735 | val 0.18938
  Regression -> MSE: 0.000175, MAE: 0.009786, R²: -0.0003
  Directional -> Accuracy: 0.4583, MCC: -0.1556, F1: 0.2778

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13714 | val 0.15590
  Epoch 020 - train 0.14566 | val 0.16764
  Epoch 021 - train 0.13350 | val 0.16705
  Regression -> MSE: 0.000229, MAE: 0.011879, R²: -0.0164
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13406 | val 0.15660
  Epoch 020 - train 0.13871 | val 0.15881
  Epoch 021 - train 0.13862 | val 0.15923
  Regression -> MSE: 0.000095, MAE: 0.007806, R²: -0.0111
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.15201 | val 0.20158
  Epoch 020 - train 0.15054 | val 0.21006
  Epoch 021 - train 0.15026 | val 0.21076
  Regression -> MSE: 0.000167, MAE: 0.010447, R²: -0.0028

[I 2026-02-23 23:50:23,477] Trial 45 finished with value: -0.011577191111189685 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 6.818547360983132e-06, 'weight_decay': 2.675359506093967e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.19528051414334396, 'early_stopping_min_delta': 0.003278741750366446}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 030 - train 0.13561 | val 0.18349
  Regression -> MSE: 0.000239, MAE: 0.012360, R²: 0.0054
  Directional -> Accuracy: 0.6500, MCC: 0.3074, F1: 0.6667

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.08834 | val 0.10120
  Epoch 020 - train 0.08193 | val 0.10152
  Epoch 021 - train 0.08706 | val 0.10153
  Regression -> MSE: 0.000248, MAE: 0.012527, R²: -0.0007
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08396 | val 0.07534
  Epoch 020 - train 0.08283 | val 0.08710
  Epoch 021 - train 0.08666 | val 0.08754
  Regression -> MSE: 0.000715, MAE: 0.019870, R²: -0.0444
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09015 | val 0.12269
  Epoch 020 - train 0.08896 | val 0.12386
  Epoch 021 - train 0.08305 | val 0.12380
  Regression -> MSE: 0.000310, MAE: 0.014438, R²: -0.0008
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07699 | val 0.09135
  Epoch 020 - train 0.08176 | val 0.09131
  Epoch 021 - train 0.07824 | val 0.09165
  Regression -> MSE: 0.000369, MAE: 0.014888, R²: -0.0569
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.08739 | val 0.08612
  Epoch 020 - train 0.08758 | val 0.09384
  Epoch 021 - train 0.08716 | val 0.09388
  Regression -> MSE: 0.000205, MAE: 0.010268, R²: -0.0051
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08100 | val 0.13986
  Epoch 020 - train 0.08745 | val 0.14105
  Epoch 021 - train 0.08523 | val 0.14122
  Regression -> MSE: 0.000557, MAE: 0.018164, R²: -0.0038
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.08988 | val 0.10480
  Epoch 020 - train 0.09163 | val 0.10622
  Epoch 021 - train 0.09336 | val 0.10589
  Regression -> MSE: 0.000247, MAE: 0.012274, R²: -0.0081
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08915 | val 0.08969
  Epoch 020 - train 0.09521 | val 0.08819
  Epoch 021 - train 0.10109 | val 0.08825
  Regression -> MSE: 0.000600, MAE: 0.019185, R²: -0.0036
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08676 | val 0.09495
  Epoch 020 - train 0.08494 | val 0.10173
  Epoch 021 - train 0.07926 | val 0.10171
  Regression -> MSE: 0.000393, MAE: 0.015930, R²: -0.0243
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09288 | val 0.10658
  Epoch 020 - train 0.08962 | val 0.10725
  Epoch 021 - train 0.09103 | val 0.10796
  Regression -> MSE: 0.000242, MAE: 0.011852, R²: -0.0022
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08114 | val 0.11502
  Epoch 020 - train 0.08108 | val 0.12291
  Epoch 021 - train 0.08376 | val 0.12300
  Regression -> MSE: 0.000318, MAE: 0.013580, R²: -0.0238
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09165 | val 0.09529
  Epoch 020 - train 0.09487 | val 0.09639
  Epoch 021 - train 0.09617 | val 0.09669
  Regression -> MSE: 0.000685, MAE: 0.019502, R²: -0.0117
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.08983 | val 0.08668
  Epoch 020 - train 0.08469 | val 0.08866
  Epoch 021 - train 0.08582 | val 0.08997
  Regression -> MSE: 0.000139, MAE: 0.009006, R²: -0.0086
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08211 | val 0.11527
  Epoch 020 - train 0.08282 | val 0.12183
  Epoch 021 - train 0.08416 | val 0.12160
  Regression -> MSE: 0.000225, MAE: 0.010690, R²: -0.0007
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08387 | val 0.15506
  Epoch 020 - train 0.08268 | val 0.16229
  Epoch 021 - train 0.08533 | val 0.16168
  Regression -> MSE: 0.000366, MAE: 0.015983, R²: -0.0099
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09779 | val 0.07898
  Epoch 020 - train 0.09212 | val 0.07912
  Epoch 021 - train 0.08958 | val 0.07888
  Regression -> MSE: 0.000111, MAE: 0.007953, R²: -0.0247
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08111 | val 0.15034
  Epoch 020 - train 0.08063 | val 0.16444
  Epoch 021 - train 0.08056 | val 0.16397
  Regression -> MSE: 0.000157, MAE: 0.009545, R²: -0.0078
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08679 | val 0.08209
  Epoch 020 - train 0.08526 | val 0.08269
  Epoch 021 - train 0.08638 | val 0.08249
  Regression -> MSE: 0.000276, MAE: 0.013229, R²: -0.0141
  Directional -> Accuracy: 0.5789, MCC: -0.1328, F1: 0.7333

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07843 | val 0.10489
  Epoch 020 - train 0.07779 | val 0.10458
  Epoch 021 - train 0.08288 | val 0.10452
  Regression -> MSE: 0.000155, MAE: 0.008784, R²: -0.0346
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.08383 | val 0.11290
  Epoch 020 - train 0.08605 | val 0.11340
  Epoch 021 - train 0.08565 | val 0.11324
  Regression -> MSE: 0.000235, MAE: 0.010977, R²: -0.0378
  Directional -> Accuracy: 0.4000, MCC: -0.1808, F1: 0.3284

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08430 | val 0.09759
  Epoch 020 - train 0.08671 | val 0.10000
  Epoch 021 - train 0.08989 | val 0.09985
  Regression -> MSE: 0.000148, MAE: 0.008581, R²: -0.0293
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.08422 | val 0.08807
  Epoch 020 - train 0.08790 | val 0.08821
  Epoch 021 - train 0.08410 | val 0.08835
  Regression -> MSE: 0.000175, MAE: 0.010275, R²: -0.0581
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09068 | val 0.10299
  Epoch 020 - train 0.09791 | val 0.10696
  Epoch 021 - train 0.10503 | val 0.10719
  Regression -> MSE: 0.000098, MAE: 0.007613, R²: -0.1466
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.08480 | val 0.13443
  Epoch 020 - train 0.08762 | val 0.13309
  Epoch 021 - train 0.08705 | val 0.13732
  Regression -> MSE: 0.000212, MAE: 0.011116, R²: -0.0026
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07997 | val 0.06917
  Epoch 020 - train 0.07948 | val 0.06944
  Epoch 021 - train 0.07820 | val 0.06922
  Regression -> MSE: 0.000103, MAE: 0.008305, R²: -0.1229
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.08441 | val 0.06497
  Epoch 020 - train 0.08956 | val 0.06542
  Epoch 021 - train 0.08787 | val 0.06553
  Regression -> MSE: 0.000116, MAE: 0.009199, R²: -0.1213
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.08492 | val 0.07352
  Epoch 020 - train 0.09296 | val 0.07473
  Epoch 021 - train 0.09212 | val 0.07481
  Regression -> MSE: 0.000232, MAE: 0.012523, R²: -0.0007
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.08242 | val 0.09193
  Epoch 020 - train 0.07990 | val 0.09204
  Epoch 021 - train 0.08573 | val 0.09212
  Regression -> MSE: 0.000178, MAE: 0.007928, R²: -0.0722
  Directional -> Accuracy: 0.4737, MCC: -0.0169, F1: 0.4231

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08605 | val 0.06665
  Epoch 020 - train 0.08387 | val 0.06651
  Epoch 021 - train 0.08387 | val 0.06662
  Regression -> MSE: 0.000239, MAE: 0.011926, R²: -0.0086
  Directional -> Accuracy: 0.5610, MCC: 0.1535, F1: 0.5000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.08889 | val 0.11872
  Epoch 020 - train 0.08755 | val 0.11760
  Epoch 021 - train 0.08437 | val 0.11748
  Regression -> MSE: 0.000231, MAE: 0.009872, R²: -0.0006
  Directional -> Accuracy: 0.5116, MCC: 0.0051, F1: 0.0870

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.08841 | val 0.09132
  Epoch 020 - train 0.09056 | val 0.10655
  Epoch 021 - train 0.08475 | val 0.10593
  Regression -> MSE: 0.000135, MAE: 0.008178, R²: -0.0029
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08800 | val 0.10083
  Epoch 020 - train 0.08982 | val 0.10578
  Epoch 021 - train 0.08311 | val 0.10577
  Regression -> MSE: 0.000202, MAE: 0.010826, R²: -0.0742
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08102 | val 0.09780
  Epoch 020 - train 0.08009 | val 0.09796
  Epoch 021 - train 0.08041 | val 0.09832
  Regression -> MSE: 0.000275, MAE: 0.010785, R²: -0.0506
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08732 | val 0.07118
  Epoch 020 - train 0.09248 | val 0.07761
  Epoch 021 - train 0.09197 | val 0.07859
  Regression -> MSE: 0.000168, MAE: 0.010370, R²: -0.0101
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08616 | val 0.07833
  Epoch 020 - train 0.07991 | val 0.08102
  Epoch 021 - train 0.08192 | val 0.08110
  Regression -> MSE: 0.000182, MAE: 0.010407, R²: -0.0120
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.08734 | val 0.07579
  Epoch 020 - train 0.08426 | val 0.07603
  Epoch 021 - train 0.08173 | val 0.07588
  Regression -> MSE: 0.000348, MAE: 0.012270, R²: -0.0157
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.09914 | val 0.05349
  Epoch 020 - train 0.10549 | val 0.05336
  Epoch 021 - train 0.09171 | val 0.05319
  Regression -> MSE: 0.000109, MAE: 0.008310, R²: -0.0385
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.08734 | val 0.10219
  Epoch 020 - train 0.08946 | val 0.10426
  Epoch 021 - train 0.08578 | val 0.10466
  Regression -> MSE: 0.000220, MAE: 0.011345, R²: -0.0075
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09176 | val 0.13308
  Epoch 020 - train 0.08887 | val 0.14073
  Epoch 021 - train 0.09219 | val 0.14110
  Regression -> MSE: 0.000086, MAE: 0.007232, R²: -0.1023
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08665 | val 0.06621
  Epoch 020 - train 0.08668 | val 0.06786
  Epoch 021 - train 0.09426 | val 0.06829
  Regression -> MSE: 0.000330, MAE: 0.014984, R²: -0.0742
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10547 | val 0.04885
  Epoch 020 - train 0.10191 | val 0.05223
  Epoch 021 - train 0.10239 | val 0.05270
  Regression -> MSE: 0.000245, MAE: 0.011564, R²: -0.0064
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09373 | val 0.09289
  Epoch 020 - train 0.09062 | val 0.09300
  Epoch 021 - train 0.08919 | val 0.09302
  Regression -> MSE: 0.000084, MAE: 0.007051, R²: -0.0367
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.09204 | val 0.09437
  Epoch 020 - train 0.09315 | val 0.09364
  Epoch 021 - train 0.09046 | val 0.09374
  Regression -> MSE: 0.000308, MAE: 0.014516, R²: -0.0038
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08238 | val 0.08136
  Epoch 020 - train 0.09241 | val 0.08165
  Epoch 021 - train 0.08891 | val 0.08155
  Regression -> MSE: 0.000098, MAE: 0.007358, R²: -0.0007
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08859 | val 0.09133
  Epoch 020 - train 0.08370 | val 0.09720
  Epoch 021 - train 0.08964 | val 0.09764
  Regression -> MSE: 0.000172, MAE: 0.009672, R²: 0.0002
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08388 | val 0.10214
  Epoch 020 - train 0.08883 | val 0.10787
  Epoch 021 - train 0.08784 | val 0.10810
  Regression -> MSE: 0.000229, MAE: 0.011848, R²: -0.0259
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09111 | val 0.09380
  Epoch 020 - train 0.08882 | val 0.09574
  Epoch 021 - train 0.09410 | val 0.09559
  Regression -> MSE: 0.000093, MAE: 0.007678, R²: -0.0065

[I 2026-02-23 23:52:27,159] Trial 46 finished with value: -0.011439632993467484 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 5.022123939936248e-06, 'weight_decay': 2.1675156696026534e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.11100470636444591, 'early_stopping_min_delta': 0.004444896248281309}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.09356 | val 0.11247
  Epoch 021 - train 0.08766 | val 0.11280
  Regression -> MSE: 0.000239, MAE: 0.012372, R²: -0.0077
  Directional -> Accuracy: 0.4426, MCC: -0.1441, F1: 0.2917

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.24707 | val 0.30255
  Epoch 020 - train 0.25246 | val 0.30290
  Epoch 021 - train 0.25558 | val 0.30278
  Regression -> MSE: 0.000249, MAE: 0.012627, R²: -0.0068
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.26985 | val 0.21471
  Epoch 020 - train 0.24540 | val 0.24988
  Epoch 021 - train 0.25511 | val 0.24887
  Regression -> MSE: 0.000718, MAE: 0.019947, R²: -0.0489
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.24895 | val 0.37872
  Epoch 020 - train 0.24944 | val 0.37609
  Epoch 030 - train 0.23977 | val 0.37552
  Regression -> MSE: 0.000307, MAE: 0.014351, R²: 0.0093
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.23639 | val 0.42829
  Epoch 020 - train 0.22390 | val 0.45649
  Epoch 021 - train 0.23052 | val 0.44613
  Regression -> MSE: 0.000398, MAE: 0.015516, R²: -0.1396
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.26409 | val 0.22384
  Epoch 020 - train 0.25303 | val 0.22054
  Epoch 030 - train 0.25195 | val 0.21955
  Regression -> MSE: 0.000206, MAE: 0.010104, R²: -0.0138
  Directional -> Accuracy: 0.5882, MCC: 0.2141, F1: 0.5116

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.24620 | val 0.43570
  Epoch 020 - train 0.24869 | val 0.45614
  Epoch 021 - train 0.25173 | val 0.45686
  Regression -> MSE: 0.000558, MAE: 0.018140, R²: -0.0052
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.27447 | val 0.38643
  Epoch 020 - train 0.27446 | val 0.39230
  Epoch 021 - train 0.27836 | val 0.38589
  Regression -> MSE: 0.000247, MAE: 0.012029, R²: -0.0048
  Directional -> Accuracy: 0.4493, MCC: -0.0843, F1: 0.4242

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.24228 | val 0.31698
  Epoch 020 - train 0.24402 | val 0.30456
  Epoch 030 - train 0.24364 | val 0.29894
  Regression -> MSE: 0.000592, MAE: 0.018993, R²: 0.0092
  Directional -> Accuracy: 0.5682, MCC: 0.0365, F1: 0.2963

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.23260 | val 0.30278
  Epoch 020 - train 0.25608 | val 0.32106
  Epoch 021 - train 0.25940 | val 0.32096
  Regression -> MSE: 0.000384, MAE: 0.016159, R²: 0.0002
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.24442 | val 0.29507
  Epoch 020 - train 0.24304 | val 0.29548
  Epoch 021 - train 0.23181 | val 0.29469
  Regression -> MSE: 0.000242, MAE: 0.011901, R²: -0.0005
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.27797 | val 0.31355
  Epoch 020 - train 0.22351 | val 0.31229
  Epoch 030 - train 0.25017 | val 0.31238
  Regression -> MSE: 0.000353, MAE: 0.014431, R²: -0.1362
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.27694 | val 0.30499
  Epoch 020 - train 0.27181 | val 0.31955
  Epoch 021 - train 0.26277 | val 0.31912
  Regression -> MSE: 0.000679, MAE: 0.019490, R²: -0.0019
  Directional -> Accuracy: 0.4655, MCC: -0.0745, F1: 0.3404

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.24980 | val 0.24243
  Epoch 020 - train 0.24399 | val 0.25381
  Epoch 021 - train 0.27863 | val 0.25286
  Regression -> MSE: 0.000138, MAE: 0.009021, R²: -0.0016
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.22874 | val 0.31748
  Epoch 020 - train 0.23147 | val 0.32144
  Epoch 021 - train 0.23651 | val 0.32273
  Regression -> MSE: 0.000225, MAE: 0.010849, R²: -0.0010
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.27948 | val 0.52466
  Epoch 020 - train 0.27790 | val 0.59199
  Epoch 021 - train 0.26617 | val 0.59524
  Regression -> MSE: 0.000363, MAE: 0.016257, R²: -0.0037
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.29350 | val 0.32690
  Epoch 020 - train 0.27669 | val 0.33195
  Epoch 021 - train 0.28869 | val 0.33061
  Regression -> MSE: 0.000109, MAE: 0.007987, R²: -0.0063
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.25343 | val 0.38228
  Epoch 020 - train 0.26297 | val 0.38345
  Epoch 021 - train 0.25433 | val 0.38222
  Regression -> MSE: 0.000157, MAE: 0.009700, R²: -0.0059
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.27713 | val 0.26308
  Epoch 020 - train 0.27612 | val 0.26540
  Epoch 021 - train 0.26138 | val 0.26343
  Regression -> MSE: 0.000278, MAE: 0.013376, R²: -0.0233
  Directional -> Accuracy: 0.3947, MCC: -0.2043, F1: 0.4390

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.24578 | val 0.32127
  Epoch 020 - train 0.24980 | val 0.32337
  Epoch 021 - train 0.24897 | val 0.32413
  Regression -> MSE: 0.000174, MAE: 0.009365, R²: -0.1652
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.26499 | val 0.35400
  Epoch 020 - train 0.27641 | val 0.35525
  Epoch 021 - train 0.25674 | val 0.35357
  Regression -> MSE: 0.000241, MAE: 0.011137, R²: -0.0668
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.24818 | val 0.29539
  Epoch 020 - train 0.25043 | val 0.31284
  Epoch 021 - train 0.26020 | val 0.31304
  Regression -> MSE: 0.000151, MAE: 0.008758, R²: -0.0558
  Directional -> Accuracy: 0.2708, MCC: -0.4290, F1: 0.2857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.25890 | val 0.29809
  Epoch 020 - train 0.24653 | val 0.30141
  Epoch 021 - train 0.26439 | val 0.30012
  Regression -> MSE: 0.000173, MAE: 0.010227, R²: -0.0457
  Directional -> Accuracy: 0.5152, MCC: 0.0362, F1: 0.3333

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.26966 | val 0.28443
  Epoch 020 - train 0.28192 | val 0.28305
  Epoch 021 - train 0.27671 | val 0.28413
  Regression -> MSE: 0.000092, MAE: 0.007419, R²: -0.0848
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.26629 | val 0.28323
  Epoch 020 - train 0.24965 | val 0.28174
  Epoch 021 - train 0.26448 | val 0.28220
  Regression -> MSE: 0.000212, MAE: 0.011100, R²: 0.0011
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.23815 | val 0.19087
  Epoch 020 - train 0.24256 | val 0.18947
  Epoch 029 - train 0.23404 | val 0.18995
  Regression -> MSE: 0.000105, MAE: 0.007988, R²: -0.1406
  Directional -> Accuracy: 0.5893, MCC: 0.2335, F1: 0.5306

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.27573 | val 0.17158
  Epoch 020 - train 0.27873 | val 0.16898
  Epoch 021 - train 0.26593 | val 0.16864
  Regression -> MSE: 0.000107, MAE: 0.008926, R²: -0.0389
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.26663 | val 0.21179
  Epoch 020 - train 0.27044 | val 0.21276
  Epoch 021 - train 0.26996 | val 0.21253
  Regression -> MSE: 0.000235, MAE: 0.012685, R²: -0.0152
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.27173 | val 0.26503
  Epoch 020 - train 0.24078 | val 0.26356
  Epoch 029 - train 0.24375 | val 0.26418
  Regression -> MSE: 0.000209, MAE: 0.008706, R²: -0.2540
  Directional -> Accuracy: 0.5614, MCC: 0.3307, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.25281 | val 0.18500
  Epoch 020 - train 0.23039 | val 0.18961
  Epoch 030 - train 0.25240 | val 0.20286
  Regression -> MSE: 0.000237, MAE: 0.011837, R²: -0.0024
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.26660 | val 0.37840
  Epoch 020 - train 0.22401 | val 0.38936
  Epoch 021 - train 0.24979 | val 0.38860
  Regression -> MSE: 0.000233, MAE: 0.010084, R²: -0.0118
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.27272 | val 0.31429
  Epoch 020 - train 0.27494 | val 0.37972
  Epoch 021 - train 0.25176 | val 0.37950
  Regression -> MSE: 0.000141, MAE: 0.008431, R²: -0.0420
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.25353 | val 0.28649
  Epoch 020 - train 0.25498 | val 0.28742
  Epoch 021 - train 0.24446 | val 0.28709
  Regression -> MSE: 0.000198, MAE: 0.010677, R²: -0.0530
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.22388 | val 0.26536
  Epoch 020 - train 0.23033 | val 0.26481
  Epoch 021 - train 0.21392 | val 0.26574
  Regression -> MSE: 0.000268, MAE: 0.010586, R²: -0.0238
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.27029 | val 0.20896
  Epoch 020 - train 0.24778 | val 0.21306
  Epoch 021 - train 0.25934 | val 0.21413
  Regression -> MSE: 0.000170, MAE: 0.010377, R²: -0.0220
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.26798 | val 0.22757
  Epoch 020 - train 0.24758 | val 0.22897
  Epoch 021 - train 0.27386 | val 0.22904
  Regression -> MSE: 0.000180, MAE: 0.010258, R²: -0.0015
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.28734 | val 0.23735
  Epoch 020 - train 0.26494 | val 0.23958
  Epoch 021 - train 0.26039 | val 0.23828
  Regression -> MSE: 0.000344, MAE: 0.011775, R²: -0.0032
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.25878 | val 0.14060
  Epoch 020 - train 0.29418 | val 0.15055
  Epoch 021 - train 0.27466 | val 0.15158
  Regression -> MSE: 0.000112, MAE: 0.008352, R²: -0.0699
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.25967 | val 0.31240
  Epoch 020 - train 0.29377 | val 0.31505
  Epoch 021 - train 0.24560 | val 0.31413
  Regression -> MSE: 0.000219, MAE: 0.011314, R²: -0.0029
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.26368 | val 0.40567
  Epoch 020 - train 0.25775 | val 0.40528
  Epoch 030 - train 0.26529 | val 0.40440
  Regression -> MSE: 0.000081, MAE: 0.007058, R²: -0.0492
  Directional -> Accuracy: 0.6170, MCC: 0.1410, F1: 0.7188

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.26721 | val 0.18430
  Epoch 020 - train 0.24874 | val 0.17920
  Epoch 030 - train 0.25492 | val 0.17857
  Regression -> MSE: 0.000305, MAE: 0.013294, R²: 0.0087
  Directional -> Accuracy: 0.6531, MCC: 0.1627, F1: 0.2609

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.29764 | val 0.12576
  Epoch 020 - train 0.27528 | val 0.12393
  Epoch 021 - train 0.28290 | val 0.12379
  Regression -> MSE: 0.000246, MAE: 0.011580, R²: -0.0108
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.26399 | val 0.29284
  Epoch 020 - train 0.26877 | val 0.29228
  Epoch 021 - train 0.25033 | val 0.29294
  Regression -> MSE: 0.000083, MAE: 0.007052, R²: -0.0216
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.27858 | val 0.32855
  Epoch 020 - train 0.26861 | val 0.48759
  Epoch 021 - train 0.27054 | val 0.49581
  Regression -> MSE: 0.000306, MAE: 0.014502, R²: 0.0015
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.25781 | val 0.28114
  Epoch 020 - train 0.25964 | val 0.30863
  Epoch 021 - train 0.25186 | val 0.30984
  Regression -> MSE: 0.000103, MAE: 0.007113, R²: -0.0535
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.27035 | val 0.27948
  Epoch 020 - train 0.25474 | val 0.30344
  Epoch 021 - train 0.24732 | val 0.30461
  Regression -> MSE: 0.000172, MAE: 0.009704, R²: 0.0015
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.23288 | val 0.26504
  Epoch 020 - train 0.21519 | val 0.26933
  Epoch 021 - train 0.23396 | val 0.27134
  Regression -> MSE: 0.000225, MAE: 0.011809, R²: -0.0071
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.26693 | val 0.25860
  Epoch 020 - train 0.25245 | val 0.25965
  Epoch 021 - train 0.25482 | val 0.26004

[I 2026-02-23 23:54:09,369] Trial 47 finished with value: -0.011447574147305477 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 6.260406317461185e-06, 'weight_decay': 2.21066418391023e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.38088474678647655, 'early_stopping_min_delta': 0.0047617948140362375}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.25299 | val 0.33822
  Epoch 021 - train 0.23760 | val 0.33973
  Regression -> MSE: 0.000246, MAE: 0.012371, R²: -0.0353
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.08797 | val 0.12511
  Epoch 020 - train 0.08865 | val 0.12389
  Epoch 021 - train 0.08822 | val 0.12449
  Regression -> MSE: 0.000258, MAE: 0.012917, R²: -0.0750
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08341 | val 0.08321
  Epoch 020 - train 0.08695 | val 0.08966
  Epoch 021 - train 0.08766 | val 0.08930
  Regression -> MSE: 0.000700, MAE: 0.019625, R²: -0.0028
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.08695 | val 0.13111
  Epoch 020 - train 0.08970 | val 0.13296
  Epoch 021 - train 0.08306 | val 0.13260
  Regression -> MSE: 0.000316, MAE: 0.014472, R²: -0.0040
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07457 | val 0.12220
  Epoch 020 - train 0.07432 | val 0.12553
  Epoch 021 - train 0.07542 | val 0.12166
  Regression -> MSE: 0.000393, MAE: 0.015295, R²: -0.1118
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.08473 | val 0.08128
  Epoch 020 - train 0.08680 | val 0.08049
  Epoch 021 - train 0.08770 | val 0.08015
  Regression -> MSE: 0.000207, MAE: 0.010276, R²: -0.0029
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08101 | val 0.14335
  Epoch 020 - train 0.07727 | val 0.14214
  Epoch 021 - train 0.07786 | val 0.14221
  Regression -> MSE: 0.000589, MAE: 0.018696, R²: -0.0400
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.08297 | val 0.10949
  Epoch 020 - train 0.08493 | val 0.11156
  Epoch 021 - train 0.08362 | val 0.11082
  Regression -> MSE: 0.000249, MAE: 0.011959, R²: -0.0041
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07636 | val 0.07241
  Epoch 020 - train 0.08372 | val 0.08022
  Epoch 021 - train 0.08385 | val 0.08047
  Regression -> MSE: 0.000614, MAE: 0.019505, R²: -0.0055
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08284 | val 0.09902
  Epoch 020 - train 0.07867 | val 0.09921
  Epoch 021 - train 0.08002 | val 0.09923
  Regression -> MSE: 0.000378, MAE: 0.015623, R²: -0.0123
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.08519 | val 0.11219
  Epoch 020 - train 0.08151 | val 0.11283
  Epoch 021 - train 0.08705 | val 0.11301
  Regression -> MSE: 0.000245, MAE: 0.011974, R²: -0.0009
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08068 | val 0.11424
  Epoch 020 - train 0.08122 | val 0.11561
  Epoch 021 - train 0.08178 | val 0.11554
  Regression -> MSE: 0.000326, MAE: 0.013506, R²: -0.0439
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08880 | val 0.09514
  Epoch 020 - train 0.08259 | val 0.09797
  Epoch 021 - train 0.08813 | val 0.09740
  Regression -> MSE: 0.000687, MAE: 0.019593, R²: -0.0018
  Directional -> Accuracy: 0.5614, MCC: 0.1303, F1: 0.5098

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09043 | val 0.09291
  Epoch 020 - train 0.09295 | val 0.09755
  Epoch 021 - train 0.09527 | val 0.09774
  Regression -> MSE: 0.000140, MAE: 0.008983, R²: -0.0149
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08096 | val 0.10193
  Epoch 020 - train 0.07980 | val 0.10421
  Epoch 028 - train 0.08023 | val 0.10464
  Regression -> MSE: 0.000233, MAE: 0.010829, R²: -0.0288
  Directional -> Accuracy: 0.4833, MCC: -0.0370, F1: 0.3404

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08489 | val 0.16376
  Epoch 020 - train 0.08270 | val 0.16732
  Epoch 021 - train 0.08530 | val 0.16690
  Regression -> MSE: 0.000367, MAE: 0.016194, R²: -0.0015
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.08870 | val 0.08312
  Epoch 020 - train 0.09084 | val 0.08412
  Epoch 021 - train 0.08804 | val 0.08441
  Regression -> MSE: 0.000108, MAE: 0.008002, R²: 0.0013
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08885 | val 0.15558
  Epoch 020 - train 0.08768 | val 0.16905
  Epoch 021 - train 0.08098 | val 0.16813
  Regression -> MSE: 0.000157, MAE: 0.009698, R²: 0.0046
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08828 | val 0.10189
  Epoch 020 - train 0.08696 | val 0.10307
  Epoch 021 - train 0.08416 | val 0.10329
  Regression -> MSE: 0.000291, MAE: 0.013831, R²: -0.0648
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07941 | val 0.10601
  Epoch 020 - train 0.07484 | val 0.10587
  Epoch 021 - train 0.08200 | val 0.10578
  Regression -> MSE: 0.000156, MAE: 0.008879, R²: -0.0241
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.08937 | val 0.12555
  Epoch 020 - train 0.08754 | val 0.12609
  Epoch 021 - train 0.08847 | val 0.12601
  Regression -> MSE: 0.000229, MAE: 0.010924, R²: -0.0066
  Directional -> Accuracy: 0.5541, MCC: 0.0000, F1: 0.7130

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08560 | val 0.10289
  Epoch 020 - train 0.08669 | val 0.10224
  Epoch 021 - train 0.08625 | val 0.10216
  Regression -> MSE: 0.000144, MAE: 0.008260, R²: -0.0011
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07887 | val 0.09880
  Epoch 020 - train 0.08411 | val 0.09917
  Epoch 021 - train 0.07972 | val 0.09903
  Regression -> MSE: 0.000166, MAE: 0.010491, R²: -0.0016
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08888 | val 0.09861
  Epoch 020 - train 0.08923 | val 0.09921
  Epoch 021 - train 0.08572 | val 0.09939
  Regression -> MSE: 0.000089, MAE: 0.007290, R²: -0.0300
  Directional -> Accuracy: 0.4211, MCC: -0.1706, F1: 0.4762

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.08450 | val 0.10098
  Epoch 020 - train 0.08398 | val 0.10115
  Epoch 021 - train 0.08697 | val 0.10111
  Regression -> MSE: 0.000211, MAE: 0.011127, R²: -0.0012
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08276 | val 0.08548
  Epoch 020 - train 0.07870 | val 0.09102
  Epoch 021 - train 0.08478 | val 0.09126
  Regression -> MSE: 0.000091, MAE: 0.007974, R²: -0.0128
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.08903 | val 0.07415
  Epoch 020 - train 0.08364 | val 0.07635
  Epoch 021 - train 0.08385 | val 0.07606
  Regression -> MSE: 0.000116, MAE: 0.009178, R²: -0.1686
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.08506 | val 0.08012
  Epoch 020 - train 0.08240 | val 0.08202
  Epoch 021 - train 0.09294 | val 0.08185
  Regression -> MSE: 0.000246, MAE: 0.013114, R²: -0.0372
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.08224 | val 0.09217
  Epoch 020 - train 0.08767 | val 0.09211
  Epoch 021 - train 0.08910 | val 0.09196
  Regression -> MSE: 0.000177, MAE: 0.007946, R²: -0.0421
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08595 | val 0.07151
  Epoch 020 - train 0.08973 | val 0.07865
  Epoch 021 - train 0.08536 | val 0.07933
  Regression -> MSE: 0.000243, MAE: 0.012094, R²: -0.0015
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.08415 | val 0.13237
  Epoch 020 - train 0.08380 | val 0.13209
  Epoch 021 - train 0.08728 | val 0.13262
  Regression -> MSE: 0.000238, MAE: 0.010254, R²: -0.0100
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09248 | val 0.09038
  Epoch 020 - train 0.09851 | val 0.09154
  Epoch 021 - train 0.08859 | val 0.09215
  Regression -> MSE: 0.000139, MAE: 0.008393, R²: -0.0083
  Directional -> Accuracy: 0.5714, MCC: 0.1070, F1: 0.6897

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08811 | val 0.10490
  Epoch 020 - train 0.08842 | val 0.10447
  Epoch 021 - train 0.08770 | val 0.10444
  Regression -> MSE: 0.000185, MAE: 0.010140, R²: -0.0109
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07881 | val 0.11697
  Epoch 020 - train 0.08126 | val 0.11712
  Epoch 021 - train 0.08095 | val 0.11805
  Regression -> MSE: 0.000268, MAE: 0.010656, R²: -0.0091
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.07803 | val 0.08609
  Epoch 020 - train 0.07566 | val 0.08418
  Epoch 030 - train 0.07541 | val 0.08410
  Regression -> MSE: 0.000172, MAE: 0.010263, R²: 0.0634
  Directional -> Accuracy: 0.5349, MCC: 0.0746, F1: 0.5652

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.08539 | val 0.08447
  Epoch 020 - train 0.08546 | val 0.08579
  Epoch 021 - train 0.08354 | val 0.08532
  Regression -> MSE: 0.000357, MAE: 0.012708, R²: -0.0268
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08578 | val 0.05501
  Epoch 020 - train 0.09185 | val 0.05867
  Epoch 021 - train 0.08621 | val 0.05879
  Regression -> MSE: 0.000129, MAE: 0.008596, R²: -0.2210
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09117 | val 0.10803
  Epoch 020 - train 0.08973 | val 0.11391
  Epoch 021 - train 0.08720 | val 0.11344
  Regression -> MSE: 0.000223, MAE: 0.011394, R²: -0.0151
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09620 | val 0.13883
  Epoch 020 - train 0.09274 | val 0.14153
  Epoch 021 - train 0.09005 | val 0.14151
  Regression -> MSE: 0.000088, MAE: 0.007319, R²: -0.1902
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08892 | val 0.06499
  Epoch 020 - train 0.08338 | val 0.07392
  Epoch 021 - train 0.08781 | val 0.07470
  Regression -> MSE: 0.000343, MAE: 0.015452, R²: -0.1017
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08448 | val 0.10268
  Epoch 020 - train 0.08262 | val 0.10277
  Epoch 021 - train 0.07991 | val 0.10287
  Regression -> MSE: 0.000078, MAE: 0.006963, R²: -0.0048
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.08661 | val 0.10335
  Epoch 020 - train 0.08430 | val 0.10503
  Epoch 021 - train 0.08647 | val 0.10478
  Regression -> MSE: 0.000301, MAE: 0.014374, R²: -0.0010
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08913 | val 0.09047
  Epoch 020 - train 0.09278 | val 0.09058
  Epoch 021 - train 0.08883 | val 0.09071
  Regression -> MSE: 0.000102, MAE: 0.007447, R²: -0.0024
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08889 | val 0.10090
  Epoch 020 - train 0.09011 | val 0.10798
  Epoch 021 - train 0.09846 | val 0.10837
  Regression -> MSE: 0.000177, MAE: 0.010209, R²: -0.0102
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08830 | val 0.08757
  Epoch 020 - train 0.08736 | val 0.09179
  Epoch 021 - train 0.08242 | val 0.09205
  Regression -> MSE: 0.000230, MAE: 0.011886, R²: -0.0181
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.08375 | val 0.09597
  Epoch 020 - train 0.08300 | val 0.09702
  Epoch 021 - train 0.08926 | val 0.09719
  Regression -> MSE: 0.000094, MAE: 0.007742, R²: 0.0008
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.08751 | val 0.12604
  Epoch 020 - train 0.08825 | val 0.12734
  Epoch 021 - train 0.08690 | val 0.12758
  Regression -> MSE: 0.000167, MAE: 0.010400, R²: -0.0026
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...


[I 2026-02-23 23:56:43,282] Trial 48 finished with value: -0.01154309604723974 and parameters: {'feature_set': 'sentinment', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 3.17715444122671e-06, 'weight_decay': 1.1967455466801387e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.11625467345766038, 'early_stopping_min_delta': 0.004311496811140983}. Best is trial 44 with value: -0.011362814469631832.

  Regression -> MSE: 0.000247, MAE: 0.012483, R²: -0.0299
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13956 | val 0.17216
  Epoch 016 - train 0.14228 | val 0.17346
  Regression -> MSE: 0.000261, MAE: 0.013034, R²: -0.0562
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13469 | val 0.12298
  Epoch 016 - train 0.13486 | val 0.12251
  Regression -> MSE: 0.000694, MAE: 0.019513, R²: -0.0142
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15437 | val 0.21564
  Epoch 016 - train 0.14895 | val 0.21551
  Regression -> MSE: 0.000315, MAE: 0.014463, R²: -0.0145
  Directional -> Accuracy: 0.3830, MCC: -0.2258, F1: 0.3256

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12604 | val 0.19419
  Epoch 016 - train 0.12436 | val 0.19631
  Regression -> MSE: 0.000350, MAE: 0.014596, R²: -0.0013
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15020 | val 0.19126
  Epoch 016 - train 0.14932 | val 0.18555
  Regression -> MSE: 0.000206, MAE: 0.010375, R²: -0.0105
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13692 | val 0.25562
  Epoch 016 - train 0.13814 | val 0.25684
  Regression -> MSE: 0.000565, MAE: 0.018235, R²: -0.0175
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14253 | val 0.16534
  Epoch 016 - train 0.14348 | val 0.16539
  Regression -> MSE: 0.000246, MAE: 0.012135, R²: -0.0017
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14315 | val 0.22470
  Epoch 016 - train 0.16353 | val 0.27474
  Regression -> MSE: 0.000676, MAE: 0.020646, R²: -0.1313
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13442 | val 0.16479
  Epoch 016 - train 0.12625 | val 0.16564
  Regression -> MSE: 0.000393, MAE: 0.015946, R²: -0.0254
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13480 | val 0.16197
  Epoch 016 - train 0.13624 | val 0.16247
  Regression -> MSE: 0.000242, MAE: 0.012001, R²: -0.0022
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14580 | val 0.18505
  Epoch 016 - train 0.14140 | val 0.18579
  Regression -> MSE: 0.000316, MAE: 0.013634, R²: -0.0179
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14423 | val 0.16298
  Epoch 016 - train 0.15488 | val 0.16665
  Regression -> MSE: 0.000678, MAE: 0.019471, R²: -0.0017
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13556 | val 0.15687
  Epoch 016 - train 0.14113 | val 0.14856
  Regression -> MSE: 0.000141, MAE: 0.009325, R²: -0.0197
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13980 | val 0.19682
  Epoch 016 - train 0.14353 | val 0.18896
  Regression -> MSE: 0.000231, MAE: 0.010919, R²: -0.0260
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14377 | val 0.26197
  Epoch 016 - train 0.13249 | val 0.26283
  Regression -> MSE: 0.000362, MAE: 0.016136, R²: -0.0003
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14865 | val 0.16406
  Epoch 016 - train 0.15081 | val 0.16350
  Regression -> MSE: 0.000108, MAE: 0.008100, R²: -0.0055
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14050 | val 0.21744
  Epoch 016 - train 0.13823 | val 0.21663
  Regression -> MSE: 0.000156, MAE: 0.009722, R²: -0.0030
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14045 | val 0.15615
  Epoch 016 - train 0.14498 | val 0.15074
  Regression -> MSE: 0.000273, MAE: 0.013055, R²: -0.0044
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12963 | val 0.17700
  Epoch 016 - train 0.13862 | val 0.17791
  Regression -> MSE: 0.000161, MAE: 0.008935, R²: -0.0744
  Directional -> Accuracy: 0.4615, MCC: 0.0668, F1: 0.2553

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13657 | val 0.18559
  Epoch 016 - train 0.13955 | val 0.18662
  Regression -> MSE: 0.000252, MAE: 0.011351, R²: -0.1155
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13741 | val 0.18919
  Epoch 016 - train 0.14950 | val 0.18754
  Regression -> MSE: 0.000144, MAE: 0.008427, R²: -0.0075
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14429 | val 0.15778
  Epoch 016 - train 0.13117 | val 0.15925
  Regression -> MSE: 0.000181, MAE: 0.010337, R²: -0.0936
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14040 | val 0.15930
  Epoch 016 - train 0.14471 | val 0.15954
  Regression -> MSE: 0.000085, MAE: 0.007036, R²: -0.0005
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14638 | val 0.26580
  Epoch 016 - train 0.15442 | val 0.26248
  Regression -> MSE: 0.000213, MAE: 0.011265, R²: -0.0074
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12992 | val 0.10836
  Epoch 019 - train 0.13558 | val 0.10812
  Regression -> MSE: 0.000092, MAE: 0.008014, R²: 0.0028
  Directional -> Accuracy: 0.5357, MCC: -0.1211, F1: 0.6977

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13705 | val 0.09947
  Epoch 020 - train 0.14999 | val 0.10524
  Epoch 024 - train 0.14627 | val 0.10624
  Regression -> MSE: 0.000113, MAE: 0.009068, R²: -0.1000
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13612 | val 0.13362
  Epoch 016 - train 0.14201 | val 0.13235
  Regression -> MSE: 0.000232, MAE: 0.012568, R²: -0.0016
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13560 | val 0.14364
  Epoch 019 - train 0.13989 | val 0.14367
  Regression -> MSE: 0.000184, MAE: 0.007951, R²: -0.1075
  Directional -> Accuracy: 0.4737, MCC: 0.0115, F1: 0.3478

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13052 | val 0.11035
  Epoch 016 - train 0.13985 | val 0.11143
  Regression -> MSE: 0.000238, MAE: 0.011926, R²: -0.0047
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.15296 | val 0.19616
  Epoch 016 - train 0.16426 | val 0.19993
  Regression -> MSE: 0.000232, MAE: 0.009912, R²: -0.0053
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14288 | val 0.15363
  Epoch 016 - train 0.13557 | val 0.15572
  Regression -> MSE: 0.000136, MAE: 0.008223, R²: -0.0053
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13726 | val 0.15482
  Epoch 016 - train 0.14907 | val 0.15509
  Regression -> MSE: 0.000196, MAE: 0.010571, R²: -0.0417
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12691 | val 0.14576
  Epoch 016 - train 0.12294 | val 0.14525
  Regression -> MSE: 0.000262, MAE: 0.010514, R²: -0.0002
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12247 | val 0.10117
  Epoch 020 - train 0.13908 | val 0.09662
  Epoch 028 - train 0.13858 | val 0.09667
  Regression -> MSE: 0.000164, MAE: 0.010270, R²: 0.0170
  Directional -> Accuracy: 0.4737, MCC: -0.0555, F1: 0.5455

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12592 | val 0.12585
  Epoch 016 - train 0.12815 | val 0.12576
  Regression -> MSE: 0.000181, MAE: 0.010342, R²: -0.0031
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14081 | val 0.12396
  Epoch 016 - train 0.14516 | val 0.12441
  Regression -> MSE: 0.000349, MAE: 0.012338, R²: -0.0199
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.15449 | val 0.10898
  Epoch 016 - train 0.14932 | val 0.11549
  Regression -> MSE: 0.000129, MAE: 0.008544, R²: -0.2257
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14200 | val 0.17902
  Epoch 016 - train 0.14792 | val 0.17921
  Regression -> MSE: 0.000218, MAE: 0.011280, R²: 0.0009
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14190 | val 0.25537
  Epoch 016 - train 0.14893 | val 0.25130
  Regression -> MSE: 0.000085, MAE: 0.007193, R²: -0.0915
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14865 | val 0.09767
  Epoch 016 - train 0.13383 | val 0.09759
  Regression -> MSE: 0.000311, MAE: 0.014032, R²: -0.0120
  Directional -> Accuracy: 0.3878, MCC: 0.1100, F1: 0.5455

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14525 | val 0.08362
  Epoch 016 - train 0.14591 | val 0.10063
  Regression -> MSE: 0.000253, MAE: 0.011479, R²: -0.0369
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13471 | val 0.15541
  Epoch 016 - train 0.13591 | val 0.15752
  Regression -> MSE: 0.000081, MAE: 0.007058, R²: -0.0071
  Directional -> Accuracy: 0.4667, MCC: -0.0837, F1: 0.6078

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14574 | val 0.16111
  Epoch 020 - train 0.14636 | val 0.16183
  Epoch 021 - train 0.14284 | val 0.16181
  Regression -> MSE: 0.000314, MAE: 0.014599, R²: -0.0226
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14508 | val 0.16289
  Epoch 016 - train 0.14369 | val 0.17191
  Regression -> MSE: 0.000105, MAE: 0.007120, R²: -0.0689
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15848 | val 0.15802
  Epoch 016 - train 0.14249 | val 0.15992
  Regression -> MSE: 0.000172, MAE: 0.009682, R²: 0.0007
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13900 | val 0.15164
  Epoch 016 - train 0.13724 | val 0.15272
  Regression -> MSE: 0.000223, MAE: 0.011691, R²: 0.0007
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13275 | val 0.13669
  Epoch 016 - train 0.13962 | val 0.13690
  Regression -> MSE: 0.000092, MAE: 0.007662, R²: -0.0006
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.14765 | val 0.22332
  Epoch 018 - train 0.14924 | val 0.22126
  Regression -> MSE: 0.000165, MAE: 0.010272, R²: -0.0105
  Directional -> Accuracy: 0.5000, MCC: 0.0521, F1: 0.1818

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.14488 | val 0.17858
  Epoch 016 - train 0.14249 | val 0.17616
  Regression -> MSE: 0.000123, MAE: 0.009011, R²: -0.0595
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.13747 | val 0.20661

[I 2026-02-23 23:58:55,183] Trial 49 finished with value: -0.011447083274223923 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 5.315648200661745e-06, 'weight_decay': 7.795249475374209e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.18830304243691182, 'early_stopping_min_delta': 0.002868115176438783}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 016 - train 0.13781 | val 0.20840
  Regression -> MSE: 0.000246, MAE: 0.012378, R²: -0.0363
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15356 | val 0.19718
  Epoch 020 - train 0.15150 | val 0.19692
  Epoch 027 - train 0.14542 | val 0.19714
  Regression -> MSE: 0.000256, MAE: 0.012857, R²: -0.0333
  Directional -> Accuracy: 0.4675, MCC: 0.0490, F1: 0.6239

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.15230 | val 0.14069
  Epoch 020 - train 0.14993 | val 0.14383
  Epoch 021 - train 0.15290 | val 0.14285
  Regression -> MSE: 0.000692, MAE: 0.019501, R²: -0.0114
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.17656 | val 0.24111
  Epoch 020 - train 0.16065 | val 0.23950
  Epoch 030 - train 0.16108 | val 0.23926
  Regression -> MSE: 0.000318, MAE: 0.014705, R²: -0.0241
  Directional -> Accuracy: 0.4894, MCC: -0.0255, F1: 0.5200

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12859 | val 0.29074
  Epoch 020 - train 0.13479 | val 0.29896
  Epoch 021 - train 0.13626 | val 0.29919
  Regression -> MSE: 0.000370, MAE: 0.014904, R²: -0.0584
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.17109 | val 0.15429
  Epoch 020 - train 0.16346 | val 0.16032
  Epoch 021 - train 0.15366 | val 0.16004
  Regression -> MSE: 0.000205, MAE: 0.010104, R²: -0.0052
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15120 | val 0.28981
  Epoch 020 - train 0.14984 | val 0.30376
  Epoch 021 - train 0.15385 | val 0.30363
  Regression -> MSE: 0.000602, MAE: 0.019014, R²: -0.0837
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16077 | val 0.18937
  Epoch 020 - train 0.16522 | val 0.18873
  Epoch 021 - train 0.15908 | val 0.18920
  Regression -> MSE: 0.000246, MAE: 0.011923, R²: -0.0032
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.16414 | val 0.21433
  Epoch 020 - train 0.15561 | val 0.21669
  Epoch 021 - train 0.15187 | val 0.21691
  Regression -> MSE: 0.000656, MAE: 0.020347, R²: -0.0982
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15195 | val 0.17280
  Epoch 020 - train 0.14932 | val 0.17139
  Epoch 030 - train 0.14694 | val 0.17110
  Regression -> MSE: 0.000453, MAE: 0.016983, R²: -0.1796
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16011 | val 0.19142
  Epoch 020 - train 0.15600 | val 0.19180
  Epoch 021 - train 0.15998 | val 0.19178
  Regression -> MSE: 0.000241, MAE: 0.011808, R²: -0.0002
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15311 | val 0.23225
  Epoch 020 - train 0.15418 | val 0.24476
  Epoch 021 - train 0.15490 | val 0.24414
  Regression -> MSE: 0.000310, MAE: 0.013717, R²: 0.0034
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.16721 | val 0.19650
  Epoch 020 - train 0.16546 | val 0.21208
  Epoch 021 - train 0.16046 | val 0.21162
  Regression -> MSE: 0.000683, MAE: 0.019641, R²: -0.0078
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16128 | val 0.17328
  Epoch 020 - train 0.16529 | val 0.21042
  Epoch 021 - train 0.16024 | val 0.20744
  Regression -> MSE: 0.000138, MAE: 0.009082, R²: -0.0004
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15438 | val 0.20662
  Epoch 020 - train 0.15195 | val 0.20682
  Epoch 030 - train 0.14454 | val 0.20617
  Regression -> MSE: 0.000235, MAE: 0.011195, R²: -0.0428
  Directional -> Accuracy: 0.4918, MCC: -0.1270, F1: 0.6593

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16512 | val 0.30174
  Epoch 020 - train 0.16692 | val 0.30143
  Epoch 030 - train 0.16100 | val 0.30084
  Regression -> MSE: 0.000427, MAE: 0.017250, R²: -0.1804
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16839 | val 0.15513
  Epoch 020 - train 0.15837 | val 0.15480
  Epoch 026 - train 0.16065 | val 0.15502
  Regression -> MSE: 0.000106, MAE: 0.007846, R²: 0.0197
  Directional -> Accuracy: 0.6429, MCC: 0.3329, F1: 0.7475

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15980 | val 0.24409
  Epoch 020 - train 0.15440 | val 0.24734
  Epoch 021 - train 0.14864 | val 0.24820
  Regression -> MSE: 0.000159, MAE: 0.010031, R²: -0.0216
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16508 | val 0.18477
  Epoch 020 - train 0.15460 | val 0.18586
  Epoch 021 - train 0.16319 | val 0.18615
  Regression -> MSE: 0.000278, MAE: 0.013324, R²: -0.0218
  Directional -> Accuracy: 0.4211, MCC: 0.1328, F1: 0.0833

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14689 | val 0.19849
  Epoch 020 - train 0.13510 | val 0.19891
  Epoch 028 - train 0.13382 | val 0.19934
  Regression -> MSE: 0.000154, MAE: 0.008821, R²: -0.0262
  Directional -> Accuracy: 0.5692, MCC: -0.0090, F1: 0.7143

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.17557 | val 0.21275
  Epoch 020 - train 0.16563 | val 0.21297
  Epoch 021 - train 0.17085 | val 0.21269
  Regression -> MSE: 0.000261, MAE: 0.011576, R²: -0.1540
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15198 | val 0.18356
  Epoch 020 - train 0.16059 | val 0.18133
  Epoch 030 - train 0.15849 | val 0.18079
  Regression -> MSE: 0.000143, MAE: 0.008456, R²: 0.0041
  Directional -> Accuracy: 0.5833, MCC: -0.0325, F1: 0.7222

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15028 | val 0.18596
  Epoch 020 - train 0.15482 | val 0.18591
  Epoch 021 - train 0.14931 | val 0.18565
  Regression -> MSE: 0.000167, MAE: 0.010329, R²: -0.0088
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15513 | val 0.17478
  Epoch 020 - train 0.17113 | val 0.17474
  Epoch 030 - train 0.15051 | val 0.17452
  Regression -> MSE: 0.000094, MAE: 0.007577, R²: -0.1029
  Directional -> Accuracy: 0.4828, MCC: 0.0846, F1: 0.2857

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15571 | val 0.23279
  Epoch 020 - train 0.15434 | val 0.23636
  Epoch 021 - train 0.15385 | val 0.24497
  Regression -> MSE: 0.000213, MAE: 0.011284, R²: -0.0059
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14585 | val 0.13997
  Epoch 020 - train 0.15463 | val 0.13950
  Epoch 021 - train 0.15235 | val 0.13911
  Regression -> MSE: 0.000092, MAE: 0.008078, R²: 0.0032
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17318 | val 0.12009
  Epoch 020 - train 0.18211 | val 0.11960
  Epoch 030 - train 0.16129 | val 0.12721
  Regression -> MSE: 0.000106, MAE: 0.008785, R²: -0.0264
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16635 | val 0.15341
  Epoch 020 - train 0.15936 | val 0.16373
  Epoch 021 - train 0.16630 | val 0.16305
  Regression -> MSE: 0.000240, MAE: 0.012858, R²: -0.0376
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15101 | val 0.17197
  Epoch 020 - train 0.15154 | val 0.17034
  Epoch 030 - train 0.14750 | val 0.17023
  Regression -> MSE: 0.000177, MAE: 0.007895, R²: -0.0651
  Directional -> Accuracy: 0.5614, MCC: 0.0340, F1: 0.7059

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.18018 | val 0.13148
  Epoch 020 - train 0.17382 | val 0.14649
  Epoch 021 - train 0.16913 | val 0.14783
  Regression -> MSE: 0.000237, MAE: 0.011899, R²: -0.0040
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16191 | val 0.23600
  Epoch 020 - train 0.16195 | val 0.23628
  Epoch 021 - train 0.15799 | val 0.23648
  Regression -> MSE: 0.000232, MAE: 0.009935, R²: -0.0059
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16338 | val 0.17171
  Epoch 020 - train 0.16934 | val 0.17570
  Epoch 021 - train 0.16369 | val 0.17582
  Regression -> MSE: 0.000135, MAE: 0.008168, R²: -0.0007
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15813 | val 0.19317
  Epoch 020 - train 0.16171 | val 0.19940
  Epoch 021 - train 0.15120 | val 0.19944
  Regression -> MSE: 0.000197, MAE: 0.010597, R²: -0.0457
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14727 | val 0.19086
  Epoch 020 - train 0.14507 | val 0.18972
  Epoch 021 - train 0.14845 | val 0.18836
  Regression -> MSE: 0.000262, MAE: 0.010518, R²: 0.0005
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16925 | val 0.12863
  Epoch 020 - train 0.16129 | val 0.12211
  Epoch 030 - train 0.15069 | val 0.11777
  Regression -> MSE: 0.000169, MAE: 0.010502, R²: -0.0150
  Directional -> Accuracy: 0.3947, MCC: -0.2887, F1: 0.5490

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14663 | val 0.14962
  Epoch 020 - train 0.14971 | val 0.14867
  Epoch 030 - train 0.14353 | val 0.14848
  Regression -> MSE: 0.000199, MAE: 0.010841, R²: -0.1074
  Directional -> Accuracy: 0.5000, MCC: -0.0263, F1: 0.3125

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14917 | val 0.14590
  Epoch 020 - train 0.14962 | val 0.14692
  Epoch 021 - train 0.15286 | val 0.14703
  Regression -> MSE: 0.000342, MAE: 0.011871, R²: 0.0008
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.17156 | val 0.09668
  Epoch 020 - train 0.16304 | val 0.09674
  Epoch 030 - train 0.16663 | val 0.09699
  Regression -> MSE: 0.000111, MAE: 0.008352, R²: -0.0516
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17585 | val 0.21241
  Epoch 020 - train 0.16636 | val 0.21403
  Epoch 021 - train 0.15946 | val 0.21332
  Regression -> MSE: 0.000226, MAE: 0.011502, R²: -0.0353
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.17857 | val 0.26133
  Epoch 020 - train 0.16745 | val 0.28257
  Epoch 021 - train 0.17445 | val 0.28302
  Regression -> MSE: 0.000095, MAE: 0.007618, R²: -0.2284
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15086 | val 0.11704
  Epoch 020 - train 0.16772 | val 0.11577
  Epoch 030 - train 0.15617 | val 0.11641
  Regression -> MSE: 0.000323, MAE: 0.014776, R²: -0.0509
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.16912 | val 0.08727
  Epoch 020 - train 0.16162 | val 0.08523
  Epoch 030 - train 0.15530 | val 0.08649
  Regression -> MSE: 0.000251, MAE: 0.011583, R²: -0.0280
  Directional -> Accuracy: 0.4211, MCC: -0.2313, F1: 0.5600

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15454 | val 0.18275
  Epoch 020 - train 0.15581 | val 0.18273
  Epoch 021 - train 0.15819 | val 0.18288
  Regression -> MSE: 0.000081, MAE: 0.007054, R²: -0.0006
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16430 | val 0.18469
  Epoch 020 - train 0.15160 | val 0.18508
  Epoch 030 - train 0.15442 | val 0.18665
  Regression -> MSE: 0.000306, MAE: 0.014461, R²: 0.0041
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.15522 | val 0.16365
  Epoch 020 - train 0.15138 | val 0.17250
  Epoch 021 - train 0.17734 | val 0.17327
  Regression -> MSE: 0.000099, MAE: 0.007204, R²: -0.0037
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15964 | val 0.18022
  Epoch 020 - train 0.16745 | val 0.17583
  Epoch 030 - train 0.15960 | val 0.17642
  Regression -> MSE: 0.000178, MAE: 0.009959, R²: -0.0347
  Directional -> Accuracy: 0.3878, MCC: -0.0687, F1: 0.5312

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14743 | val 0.16585
  Epoch 020 - train 0.14819 | val 0.16970
  Epoch 028 - train 0.15085 | val 0.16974
  Regression -> MSE: 0.000230, MAE: 0.011636, R²: -0.0310
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...

[I 2026-02-24 00:01:11,471] Trial 50 finished with value: -0.011553945803652958 and parameters: {'feature_set': 'emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 9.751261447520311e-06, 'weight_decay': 3.251971671007187e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2281582174973902, 'early_stopping_min_delta': 0.001637089258933837}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.15445 | val 0.21139
  Epoch 021 - train 0.15951 | val 0.21083
  Regression -> MSE: 0.000238, MAE: 0.012367, R²: -0.0022
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.08396 | val 0.10120
  Epoch 016 - train 0.08142 | val 0.10080
  Regression -> MSE: 0.000256, MAE: 0.012877, R²: -0.0324
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08882 | val 0.07378
  Epoch 016 - train 0.07952 | val 0.07280
  Regression -> MSE: 0.000714, MAE: 0.019838, R²: -0.0423
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09492 | val 0.14203
  Epoch 016 - train 0.08612 | val 0.14102
  Regression -> MSE: 0.000312, MAE: 0.014408, R²: -0.0069
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07426 | val 0.10772
  Epoch 016 - train 0.06969 | val 0.10606
  Regression -> MSE: 0.000371, MAE: 0.014934, R²: -0.0614
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09020 | val 0.07606
  Epoch 016 - train 0.08803 | val 0.07587
  Regression -> MSE: 0.000204, MAE: 0.010127, R²: 0.0003
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09330 | val 0.14282
  Epoch 016 - train 0.08211 | val 0.14281
  Regression -> MSE: 0.000556, MAE: 0.018216, R²: -0.0023
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.08570 | val 0.09971
  Epoch 016 - train 0.08589 | val 0.09776
  Regression -> MSE: 0.000245, MAE: 0.012019, R²: 0.0000
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08400 | val 0.14013
  Epoch 016 - train 0.07755 | val 0.17282
  Regression -> MSE: 0.000645, MAE: 0.020146, R²: -0.0800
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08910 | val 0.08490
  Epoch 020 - train 0.08502 | val 0.08512
  Epoch 024 - train 0.08739 | val 0.08493
  Regression -> MSE: 0.000404, MAE: 0.015975, R²: -0.0534
  Directional -> Accuracy: 0.5306, MCC: 0.0474, F1: 0.4651

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09087 | val 0.09285
  Epoch 016 - train 0.09105 | val 0.09272
  Regression -> MSE: 0.000244, MAE: 0.011659, R²: -0.0086
  Directional -> Accuracy: 0.6143, MCC: 0.2082, F1: 0.2286

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08114 | val 0.10532
  Epoch 020 - train 0.08071 | val 0.10558
  Regression -> MSE: 0.000322, MAE: 0.013749, R²: -0.0358
  Directional -> Accuracy: 0.5000, MCC: -0.1242, F1: 0.0741

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08775 | val 0.11638
  Epoch 016 - train 0.08460 | val 0.11635
  Regression -> MSE: 0.000679, MAE: 0.019497, R²: -0.0027
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09352 | val 0.12988
  Epoch 016 - train 0.09423 | val 0.13230
  Regression -> MSE: 0.000138, MAE: 0.009106, R²: -0.0023
  Directional -> Accuracy: 0.4884, MCC: 0.0068, F1: 0.5217

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.07807 | val 0.09967
  Epoch 019 - train 0.07517 | val 0.09982
  Regression -> MSE: 0.000221, MAE: 0.010616, R²: 0.0187
  Directional -> Accuracy: 0.5574, MCC: 0.1165, F1: 0.5424

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08027 | val 0.15050
  Epoch 016 - train 0.08194 | val 0.15079
  Regression -> MSE: 0.000362, MAE: 0.016007, R²: 0.0016
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09037 | val 0.08384
  Epoch 016 - train 0.08701 | val 0.08339
  Regression -> MSE: 0.000108, MAE: 0.007994, R²: -0.0012
  Directional -> Accuracy: 0.5571, MCC: 0.0795, F1: 0.6990

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08571 | val 0.13169
  Epoch 016 - train 0.08489 | val 0.13074
  Regression -> MSE: 0.000156, MAE: 0.009745, R²: -0.0029
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08728 | val 0.09005
  Epoch 016 - train 0.08696 | val 0.09071
  Regression -> MSE: 0.000296, MAE: 0.014030, R²: -0.0863
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07958 | val 0.09931
  Epoch 016 - train 0.08087 | val 0.09821
  Regression -> MSE: 0.000157, MAE: 0.008813, R²: -0.0497
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.08640 | val 0.11863
  Epoch 016 - train 0.08678 | val 0.11842
  Regression -> MSE: 0.000229, MAE: 0.011021, R²: -0.0103
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08553 | val 0.15361
  Epoch 016 - train 0.08567 | val 0.15342
  Regression -> MSE: 0.000146, MAE: 0.008532, R²: -0.0199
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07935 | val 0.09608
  Epoch 016 - train 0.07694 | val 0.09613
  Regression -> MSE: 0.000180, MAE: 0.010320, R²: -0.0905
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08563 | val 0.09859
  Epoch 016 - train 0.08518 | val 0.09799
  Regression -> MSE: 0.000085, MAE: 0.007031, R²: 0.0075
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.08509 | val 0.10366
  Epoch 016 - train 0.08060 | val 0.10147
  Regression -> MSE: 0.000212, MAE: 0.011193, R²: -0.0011
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08675 | val 0.06979
  Epoch 016 - train 0.09428 | val 0.07014
  Regression -> MSE: 0.000093, MAE: 0.008100, R²: -0.0118
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.08616 | val 0.06220
  Epoch 020 - train 0.08685 | val 0.06398
  Epoch 023 - train 0.07938 | val 0.06298
  Regression -> MSE: 0.000099, MAE: 0.008519, R²: 0.0365
  Directional -> Accuracy: 0.5870, MCC: 0.1646, F1: 0.5366

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.08194 | val 0.07211
  Epoch 016 - train 0.08599 | val 0.07199
  Regression -> MSE: 0.000233, MAE: 0.012591, R²: -0.0060
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07540 | val 0.09168
  Epoch 016 - train 0.07832 | val 0.09106
  Regression -> MSE: 0.000187, MAE: 0.008101, R²: -0.1239
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07581 | val 0.06785
  Epoch 016 - train 0.08073 | val 0.07902
  Regression -> MSE: 0.000238, MAE: 0.011913, R²: -0.0052
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09156 | val 0.12093
  Epoch 016 - train 0.09267 | val 0.12314
  Regression -> MSE: 0.000232, MAE: 0.009961, R²: -0.0079
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.08337 | val 0.09246
  Epoch 016 - train 0.08095 | val 0.09343
  Regression -> MSE: 0.000135, MAE: 0.008208, R²: -0.0019
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09217 | val 0.10649
  Epoch 016 - train 0.08659 | val 0.10652
  Regression -> MSE: 0.000188, MAE: 0.010410, R²: -0.0005
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07929 | val 0.09519
  Epoch 016 - train 0.08025 | val 0.09513
  Regression -> MSE: 0.000263, MAE: 0.010691, R²: -0.0029
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08561 | val 0.06403
  Epoch 016 - train 0.07990 | val 0.06721
  Regression -> MSE: 0.000170, MAE: 0.010380, R²: -0.0177
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08427 | val 0.10035
  Epoch 016 - train 0.08486 | val 0.10263
  Regression -> MSE: 0.000193, MAE: 0.010786, R²: -0.0738
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.08872 | val 0.07263
  Epoch 016 - train 0.08530 | val 0.07280
  Regression -> MSE: 0.000349, MAE: 0.012286, R²: -0.0176
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08196 | val 0.05302
  Epoch 016 - train 0.08433 | val 0.05376
  Regression -> MSE: 0.000113, MAE: 0.008331, R²: -0.0745
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.08249 | val 0.10585
  Epoch 016 - train 0.08469 | val 0.10693
  Regression -> MSE: 0.000220, MAE: 0.011345, R²: -0.0064
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.08334 | val 0.13559
  Epoch 016 - train 0.08480 | val 0.13514
  Regression -> MSE: 0.000091, MAE: 0.007467, R²: -0.1734
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08242 | val 0.07347
  Epoch 016 - train 0.09193 | val 0.07811
  Regression -> MSE: 0.000329, MAE: 0.014952, R²: -0.0702
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10003 | val 0.04867
  Epoch 020 - train 0.09078 | val 0.04243
  Epoch 030 - train 0.08560 | val 0.04140
  Regression -> MSE: 0.000268, MAE: 0.011825, R²: -0.0986
  Directional -> Accuracy: 0.5000, MCC: -0.0823, F1: 0.6545

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08357 | val 0.08968
  Epoch 016 - train 0.08484 | val 0.08977
  Regression -> MSE: 0.000081, MAE: 0.007103, R²: -0.0022
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.08317 | val 0.10691
  Epoch 016 - train 0.07670 | val 0.10634
  Regression -> MSE: 0.000316, MAE: 0.014524, R²: -0.0284
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07972 | val 0.09078
  Epoch 016 - train 0.07454 | val 0.09332
  Regression -> MSE: 0.000100, MAE: 0.007119, R²: -0.0171
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.09951 | val 0.08336
  Epoch 020 - train 0.08786 | val 0.08272
  Epoch 024 - train 0.09061 | val 0.08292
  Regression -> MSE: 0.000212, MAE: 0.010429, R²: -0.2360
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07852 | val 0.09388
  Epoch 016 - train 0.07899 | val 0.09417
  Regression -> MSE: 0.000223, MAE: 0.011760, R²: -0.0007
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.08658 | val 0.08775
  Epoch 016 - train 0.08520 | val 0.08761
  Regression -> MSE: 0.000092, MAE: 0.007631, R²: -0.0016
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.08630 | val 0.12860
  Epoch 016 - train 0.08656 | val 0.12772
  Regression -> MSE: 0.000164, MAE: 0.010271, R²: -0.0028
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.08267 | val 0.09166
  Epoch 016 - train 0.08171 | val 0.09158
  Regression -> MSE: 0.000120, MAE: 0.008990, R²: -0.0350
  Directional -> Accuracy: 0.4643, MCC: -0.1397, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.09037 | val 0.11296

[I 2026-02-24 00:03:23,979] Trial 51 finished with value: -0.011477039939180143 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 5.1249824840274714e-06, 'weight_decay': 7.358423437813372e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.10775691804484663, 'early_stopping_min_delta': 0.0028376573734034214}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 016 - train 0.08739 | val 0.11163
  Regression -> MSE: 0.000238, MAE: 0.012306, R²: -0.0022
  Directional -> Accuracy: 0.5410, MCC: 0.0871, F1: 0.1250

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.23499 | val 0.38401
  Epoch 017 - train 0.23865 | val 0.37928
  Regression -> MSE: 0.000252, MAE: 0.012729, R²: -0.0165
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.23513 | val 0.20661
  Epoch 016 - train 0.23267 | val 0.20532
  Regression -> MSE: 0.000721, MAE: 0.019957, R²: -0.0529
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.22578 | val 0.34000
  Epoch 020 - train 0.21942 | val 0.33930
  Regression -> MSE: 0.000310, MAE: 0.014305, R²: 0.0012
  Directional -> Accuracy: 0.5106, MCC: -0.0231, F1: 0.6349

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.19537 | val 0.21546
  Epoch 016 - train 0.21082 | val 0.21836
  Regression -> MSE: 0.000360, MAE: 0.014776, R²: -0.0320
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.24865 | val 0.22231
  Epoch 016 - train 0.23328 | val 0.22224
  Regression -> MSE: 0.000204, MAE: 0.010158, R²: -0.0025
  Directional -> Accuracy: 0.3725, MCC: -0.2536, F1: 0.2381

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.24362 | val 0.44455
  Epoch 016 - train 0.22630 | val 0.44715
  Regression -> MSE: 0.000581, MAE: 0.018592, R²: -0.0469
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.26053 | val 0.35975
  Epoch 016 - train 0.25984 | val 0.35779
  Regression -> MSE: 0.000247, MAE: 0.011926, R²: -0.0048
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.21962 | val 0.40227
  Epoch 016 - train 0.23879 | val 0.45014
  Regression -> MSE: 0.000684, MAE: 0.020780, R²: -0.1448
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.22529 | val 0.27612
  Epoch 016 - train 0.22371 | val 0.27794
  Regression -> MSE: 0.000383, MAE: 0.016160, R²: 0.0016
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.23243 | val 0.27699
  Epoch 016 - train 0.21994 | val 0.27800
  Regression -> MSE: 0.000241, MAE: 0.011779, R²: 0.0014
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.19794 | val 0.31181
  Epoch 020 - train 0.19913 | val 0.31160
  Epoch 022 - train 0.21101 | val 0.31478
  Regression -> MSE: 0.000288, MAE: 0.013488, R²: 0.0735
  Directional -> Accuracy: 0.5000, MCC: 0.0032, F1: 0.4898

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.25127 | val 0.27163
  Epoch 016 - train 0.25946 | val 0.27223
  Regression -> MSE: 0.000686, MAE: 0.019560, R²: -0.0124
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.22890 | val 0.20706
  Epoch 016 - train 0.22455 | val 0.20812
  Regression -> MSE: 0.000144, MAE: 0.009467, R²: -0.0425
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.21108 | val 0.31432
  Epoch 016 - train 0.20637 | val 0.31246
  Regression -> MSE: 0.000227, MAE: 0.010740, R²: -0.0083
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.23470 | val 0.46102
  Epoch 016 - train 0.22725 | val 0.46341
  Regression -> MSE: 0.000365, MAE: 0.016017, R²: -0.0073
  Directional -> Accuracy: 0.4231, MCC: -0.2141, F1: 0.2105

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.23452 | val 0.27529
  Epoch 016 - train 0.24935 | val 0.27416
  Regression -> MSE: 0.000108, MAE: 0.007957, R²: 0.0022
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.24663 | val 0.35864
  Epoch 019 - train 0.24499 | val 0.35585
  Regression -> MSE: 0.000176, MAE: 0.010531, R²: -0.1283
  Directional -> Accuracy: 0.3729, MCC: -0.2674, F1: 0.4478

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.23813 | val 0.24305
  Epoch 016 - train 0.24257 | val 0.24100
  Regression -> MSE: 0.000272, MAE: 0.013041, R²: -0.0012
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.22395 | val 0.27963
  Epoch 016 - train 0.21482 | val 0.27771
  Regression -> MSE: 0.000171, MAE: 0.009252, R²: -0.1451
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.23856 | val 0.30852
  Epoch 016 - train 0.23760 | val 0.30663
  Regression -> MSE: 0.000243, MAE: 0.011124, R²: -0.0723
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.24826 | val 0.26048
  Epoch 016 - train 0.24365 | val 0.26112
  Regression -> MSE: 0.000146, MAE: 0.008517, R²: -0.0198
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.21931 | val 0.28316
  Epoch 016 - train 0.20114 | val 0.28124
  Regression -> MSE: 0.000165, MAE: 0.010380, R²: 0.0021
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.24787 | val 0.28098
  Epoch 016 - train 0.25090 | val 0.28039
  Regression -> MSE: 0.000091, MAE: 0.007342, R²: -0.0680
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.23803 | val 0.30846
  Epoch 016 - train 0.22820 | val 0.30811
  Regression -> MSE: 0.000212, MAE: 0.011147, R²: -0.0008
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.23229 | val 0.21272
  Epoch 016 - train 0.22642 | val 0.21057
  Regression -> MSE: 0.000093, MAE: 0.008067, R²: -0.0148
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.24218 | val 0.17549
  Epoch 016 - train 0.22985 | val 0.18253
  Regression -> MSE: 0.000116, MAE: 0.009216, R²: -0.1271
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.22322 | val 0.23774
  Epoch 016 - train 0.22843 | val 0.24378
  Regression -> MSE: 0.000234, MAE: 0.012635, R²: -0.0099
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.22766 | val 0.28335
  Epoch 016 - train 0.23356 | val 0.28357
  Regression -> MSE: 0.000169, MAE: 0.007826, R²: -0.0161
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.23993 | val 0.17374
  Epoch 020 - train 0.24143 | val 0.17042
  Epoch 030 - train 0.22660 | val 0.16852
  Regression -> MSE: 0.000290, MAE: 0.012455, R²: -0.2263
  Directional -> Accuracy: 0.4390, MCC: -0.1065, F1: 0.3784

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.24049 | val 0.34736
  Epoch 016 - train 0.23549 | val 0.34974
  Regression -> MSE: 0.000231, MAE: 0.009870, R²: -0.0022
  Directional -> Accuracy: 0.4884, MCC: -0.0197, F1: 0.5217

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.26879 | val 0.26545
  Epoch 016 - train 0.24385 | val 0.27183
  Regression -> MSE: 0.000136, MAE: 0.008182, R²: -0.0065
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.22443 | val 0.26405
  Epoch 016 - train 0.23159 | val 0.26468
  Regression -> MSE: 0.000188, MAE: 0.010444, R²: -0.0006
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.21313 | val 0.25530
  Epoch 016 - train 0.22909 | val 0.25660
  Regression -> MSE: 0.000267, MAE: 0.010550, R²: -0.0199
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.23317 | val 0.17689
  Epoch 020 - train 0.20629 | val 0.17312
  Epoch 029 - train 0.22636 | val 0.17078
  Regression -> MSE: 0.000188, MAE: 0.010849, R²: -0.1251
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.21234 | val 0.23799
  Epoch 016 - train 0.22791 | val 0.23423
  Regression -> MSE: 0.000187, MAE: 0.010615, R²: -0.0402
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.21760 | val 0.19606
  Epoch 016 - train 0.23436 | val 0.19564
  Regression -> MSE: 0.000344, MAE: 0.012052, R²: -0.0039
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.25090 | val 0.14378
  Epoch 016 - train 0.25335 | val 0.14807
  Regression -> MSE: 0.000126, MAE: 0.008487, R²: -0.1985
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.24007 | val 0.33060
  Epoch 016 - train 0.22744 | val 0.33493
  Regression -> MSE: 0.000225, MAE: 0.011466, R²: -0.0272
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.24472 | val 0.47847
  Epoch 016 - train 0.24328 | val 0.48495
  Regression -> MSE: 0.000098, MAE: 0.007723, R²: -0.2661
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.25462 | val 0.19750
  Epoch 016 - train 0.24170 | val 0.20298
  Regression -> MSE: 0.000333, MAE: 0.015105, R²: -0.0825
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.22151 | val 0.12206
  Epoch 016 - train 0.24722 | val 0.12837
  Regression -> MSE: 0.000252, MAE: 0.011482, R²: -0.0332
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.23324 | val 0.25033
  Epoch 016 - train 0.22920 | val 0.25116
  Regression -> MSE: 0.000083, MAE: 0.007056, R²: -0.0292
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.24143 | val 0.45368
  Epoch 016 - train 0.24959 | val 0.47365
  Regression -> MSE: 0.000308, MAE: 0.014501, R²: -0.0025
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.23396 | val 0.23714
  Epoch 016 - train 0.22539 | val 0.24230
  Regression -> MSE: 0.000099, MAE: 0.007196, R²: -0.0090
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.24927 | val 0.27040
  Epoch 016 - train 0.23782 | val 0.27711
  Regression -> MSE: 0.000177, MAE: 0.010310, R²: -0.0311
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.23518 | val 0.28592
  Epoch 016 - train 0.22369 | val 0.28991
  Regression -> MSE: 0.000224, MAE: 0.011801, R²: -0.0032
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.22212 | val 0.27516
  Epoch 016 - train 0.23841 | val 0.27579
  Regression -> MSE: 0.000093, MAE: 0.007684, R²: -0.0072
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.24345 | val 0.35956
  Epoch 016 - train 0.23727 | val 0.35628
  Regression -> MSE: 0.000167, MAE: 0.010315, R²: -0.0181
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.22716 | val 0.36970
  Epoch 016 - train 0.24708 | val 0.36754
  Regression -> MSE: 0.000118, MAE: 0.008936, R²: -0.0138
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.23838 | val 0.33342

[I 2026-02-24 00:05:37,392] Trial 52 finished with value: -0.011539650832954763 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 2.04773488014689e-06, 'weight_decay': 2.7281815091107073e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.34160991464755586, 'early_stopping_min_delta': 0.004209409531221211}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 016 - train 0.23380 | val 0.33117
  Regression -> MSE: 0.000237, MAE: 0.012436, R²: -0.0014
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14909 | val 0.26287
  Epoch 016 - train 0.14913 | val 0.26367
  Regression -> MSE: 0.000264, MAE: 0.013063, R²: -0.0973
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13846 | val 0.12280
  Epoch 016 - train 0.14387 | val 0.12329
  Regression -> MSE: 0.000705, MAE: 0.019748, R²: -0.0099
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15085 | val 0.23011
  Epoch 016 - train 0.16708 | val 0.23004
  Regression -> MSE: 0.000326, MAE: 0.014582, R²: -0.0365
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14030 | val 0.17123
  Epoch 016 - train 0.12823 | val 0.17113
  Regression -> MSE: 0.000371, MAE: 0.014924, R²: -0.0492
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13649 | val 0.14150
  Epoch 016 - train 0.15683 | val 0.14113
  Regression -> MSE: 0.000207, MAE: 0.010135, R²: -0.0019
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13961 | val 0.26316
  Epoch 016 - train 0.13638 | val 0.26551
  Regression -> MSE: 0.000576, MAE: 0.018421, R²: -0.0177
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14240 | val 0.16798
  Epoch 016 - train 0.14117 | val 0.16796
  Regression -> MSE: 0.000248, MAE: 0.012033, R²: -0.0015
  Directional -> Accuracy: 0.4853, MCC: -0.1115, F1: 0.2857

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13165 | val 0.20914
  Epoch 016 - train 0.12862 | val 0.28767
  Regression -> MSE: 0.000637, MAE: 0.019962, R²: -0.0433
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14290 | val 0.15402
  Epoch 016 - train 0.13828 | val 0.15351
  Regression -> MSE: 0.000385, MAE: 0.015689, R²: -0.0331
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14825 | val 0.18081
  Epoch 016 - train 0.15058 | val 0.18004
  Regression -> MSE: 0.000250, MAE: 0.011801, R²: -0.0190
  Directional -> Accuracy: 0.5797, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13539 | val 0.19117
  Epoch 020 - train 0.14224 | val 0.19051
  Regression -> MSE: 0.000406, MAE: 0.014990, R²: -0.3013
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15883 | val 0.16047
  Epoch 016 - train 0.15171 | val 0.15996
  Regression -> MSE: 0.000690, MAE: 0.019782, R²: -0.0065
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.18242 | val 0.21908
  Epoch 016 - train 0.17519 | val 0.22160
  Regression -> MSE: 0.000138, MAE: 0.008963, R²: 0.0010
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12313 | val 0.16643
  Epoch 020 - train 0.13281 | val 0.16596
  Epoch 024 - train 0.12585 | val 0.16593
  Regression -> MSE: 0.000232, MAE: 0.011027, R²: -0.0253
  Directional -> Accuracy: 0.4167, MCC: -0.1925, F1: 0.2222

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12962 | val 0.26618
  Epoch 016 - train 0.13598 | val 0.26559
  Regression -> MSE: 0.000367, MAE: 0.016093, R²: 0.0001
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15656 | val 0.14069
  Epoch 016 - train 0.15489 | val 0.14094
  Regression -> MSE: 0.000109, MAE: 0.007943, R²: -0.0128
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13994 | val 0.21032
  Epoch 016 - train 0.14125 | val 0.21047
  Regression -> MSE: 0.000158, MAE: 0.009601, R²: -0.0039
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14256 | val 0.13237
  Epoch 016 - train 0.14172 | val 0.13338
  Regression -> MSE: 0.000289, MAE: 0.013787, R²: -0.0564
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13607 | val 0.17390
  Epoch 016 - train 0.12777 | val 0.17447
  Regression -> MSE: 0.000155, MAE: 0.008866, R²: -0.0186
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14280 | val 0.19095
  Epoch 016 - train 0.14897 | val 0.18897
  Regression -> MSE: 0.000248, MAE: 0.011255, R²: -0.0909
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14673 | val 0.17024
  Epoch 016 - train 0.15162 | val 0.16945
  Regression -> MSE: 0.000144, MAE: 0.008284, R²: -0.0009
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13771 | val 0.16832
  Epoch 016 - train 0.13971 | val 0.16973
  Regression -> MSE: 0.000175, MAE: 0.010310, R²: -0.0543
  Directional -> Accuracy: 0.4769, MCC: -0.0767, F1: 0.0556

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15922 | val 0.16578
  Epoch 016 - train 0.14754 | val 0.16605
  Regression -> MSE: 0.000087, MAE: 0.007181, R²: -0.0051
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14729 | val 0.17376
  Epoch 016 - train 0.14629 | val 0.17622
  Regression -> MSE: 0.000213, MAE: 0.011328, R²: -0.0094
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14355 | val 0.12215
  Epoch 016 - train 0.13276 | val 0.12209
  Regression -> MSE: 0.000102, MAE: 0.008179, R²: -0.1345
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.15390 | val 0.11747
  Epoch 016 - train 0.15028 | val 0.13657
  Regression -> MSE: 0.000106, MAE: 0.008845, R²: -0.0650
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14441 | val 0.12628
  Epoch 016 - train 0.16062 | val 0.12517
  Regression -> MSE: 0.000244, MAE: 0.013074, R²: -0.0296
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14548 | val 0.14677
  Epoch 020 - train 0.14110 | val 0.14599
  Regression -> MSE: 0.000192, MAE: 0.008816, R²: -0.1338
  Directional -> Accuracy: 0.4286, MCC: -0.2632, F1: 0.5789

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14532 | val 0.11895
  Epoch 016 - train 0.14216 | val 0.13280
  Regression -> MSE: 0.000244, MAE: 0.012167, R²: -0.0082
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12713 | val 0.21769
  Epoch 016 - train 0.13168 | val 0.21797
  Regression -> MSE: 0.000240, MAE: 0.010363, R²: -0.0176
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14654 | val 0.14654
  Epoch 016 - train 0.15295 | val 0.15023
  Regression -> MSE: 0.000137, MAE: 0.008333, R²: 0.0027
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14682 | val 0.16973
  Epoch 016 - train 0.14930 | val 0.17010
  Regression -> MSE: 0.000184, MAE: 0.010217, R²: -0.0032
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13713 | val 0.16562
  Epoch 016 - train 0.15437 | val 0.16741
  Regression -> MSE: 0.000273, MAE: 0.010710, R²: -0.0274
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13987 | val 0.18469
  Epoch 016 - train 0.13943 | val 0.18606
  Regression -> MSE: 0.000186, MAE: 0.010521, R²: -0.0167
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13616 | val 0.13579
  Epoch 016 - train 0.12680 | val 0.13659
  Regression -> MSE: 0.000347, MAE: 0.012078, R²: 0.0014
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14377 | val 0.09552
  Epoch 016 - train 0.15357 | val 0.10127
  Regression -> MSE: 0.000114, MAE: 0.008377, R²: -0.0786
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15308 | val 0.19048
  Epoch 016 - train 0.14772 | val 0.18986
  Regression -> MSE: 0.000227, MAE: 0.011475, R²: -0.0303
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14117 | val 0.22767
  Epoch 016 - train 0.14228 | val 0.22710
  Regression -> MSE: 0.000080, MAE: 0.006994, R²: -0.0854
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14723 | val 0.08652
  Epoch 016 - train 0.13493 | val 0.08714
  Regression -> MSE: 0.000316, MAE: 0.014156, R²: -0.0156
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14244 | val 0.18957
  Epoch 016 - train 0.13946 | val 0.18931
  Regression -> MSE: 0.000078, MAE: 0.006944, R²: -0.0020
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13872 | val 0.16647
  Epoch 016 - train 0.15276 | val 0.16618
  Regression -> MSE: 0.000304, MAE: 0.014408, R²: -0.0100
  Directional -> Accuracy: 0.4667, MCC: -0.0764, F1: 0.5385

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13891 | val 0.14835
  Epoch 016 - train 0.13748 | val 0.14815
  Regression -> MSE: 0.000103, MAE: 0.007242, R²: -0.0145
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15091 | val 0.16342
  Epoch 016 - train 0.15289 | val 0.16716
  Regression -> MSE: 0.000180, MAE: 0.010436, R²: -0.0245
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.15128 | val 0.16502
  Epoch 016 - train 0.14163 | val 0.16415
  Regression -> MSE: 0.000227, MAE: 0.011893, R²: -0.0071
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14350 | val 0.15210
  Epoch 016 - train 0.15032 | val 0.15147
  Regression -> MSE: 0.000094, MAE: 0.007762, R²: -0.0011
  Directional -> Accuracy: 0.5179, MCC: 0.0124, F1: 0.1818

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.14544 | val 0.20619
  Epoch 016 - train 0.14357 | val 0.20548
  Regression -> MSE: 0.000168, MAE: 0.010481, R²: -0.0060
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.14092 | val 0.17088
  Epoch 016 - train 0.14240 | val 0.17195
  Regression -> MSE: 0.000121, MAE: 0.009079, R²: -0.0253
  Directional -> Accuracy: 0.5455, MCC: 0.0734, F1: 0.6667

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.14211 | val 0.21203

[I 2026-02-24 00:08:14,927] Trial 53 finished with value: -0.011559792433305821 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 2.504799540780335e-06, 'weight_decay': 4.233655510077824e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.19145596192249054, 'early_stopping_min_delta': 0.0034716079431722697}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 016 - train 0.14349 | val 0.21181
  Regression -> MSE: 0.000242, MAE: 0.012551, R²: -0.0059
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07580 | val 0.09916
  Epoch 016 - train 0.07328 | val 0.09779
  Regression -> MSE: 0.000255, MAE: 0.012857, R²: -0.0301
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07401 | val 0.07416
  Epoch 016 - train 0.07561 | val 0.07411
  Regression -> MSE: 0.000707, MAE: 0.019736, R²: -0.0322
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07982 | val 0.12149
  Epoch 016 - train 0.08023 | val 0.12160
  Regression -> MSE: 0.000312, MAE: 0.014525, R²: -0.0064
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06810 | val 0.07770
  Epoch 016 - train 0.06690 | val 0.07992
  Regression -> MSE: 0.000354, MAE: 0.014705, R²: -0.0134
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07521 | val 0.07102
  Epoch 016 - train 0.07488 | val 0.07067
  Regression -> MSE: 0.000204, MAE: 0.010064, R²: -0.0004
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07298 | val 0.13522
  Epoch 016 - train 0.07116 | val 0.13492
  Regression -> MSE: 0.000607, MAE: 0.019137, R²: -0.0930
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07841 | val 0.09166
  Epoch 016 - train 0.07643 | val 0.09245
  Regression -> MSE: 0.000246, MAE: 0.011915, R²: -0.0006
  Directional -> Accuracy: 0.5217, MCC: -0.0089, F1: 0.3774

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07330 | val 0.09639
  Epoch 016 - train 0.07188 | val 0.10219
  Regression -> MSE: 0.000606, MAE: 0.019366, R²: -0.0137
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.06875 | val 0.08579
  Epoch 016 - train 0.07042 | val 0.08584
  Regression -> MSE: 0.000387, MAE: 0.016007, R²: -0.0083
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07294 | val 0.10105
  Epoch 016 - train 0.07638 | val 0.10071
  Regression -> MSE: 0.000241, MAE: 0.011887, R²: 0.0020
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.07258 | val 0.09570
  Epoch 020 - train 0.06408 | val 0.09714
  Epoch 025 - train 0.07065 | val 0.09739
  Regression -> MSE: 0.000448, MAE: 0.015912, R²: -0.4404
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07603 | val 0.08605
  Epoch 016 - train 0.07332 | val 0.08665
  Regression -> MSE: 0.000681, MAE: 0.019534, R²: -0.0049
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07666 | val 0.07957
  Epoch 016 - train 0.07578 | val 0.07991
  Regression -> MSE: 0.000139, MAE: 0.009183, R²: -0.0045
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06593 | val 0.08902
  Epoch 016 - train 0.06587 | val 0.09023
  Regression -> MSE: 0.000227, MAE: 0.010713, R²: -0.0078
  Directional -> Accuracy: 0.5082, MCC: 0.0350, F1: 0.2857

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07792 | val 0.14263
  Epoch 016 - train 0.07473 | val 0.14289
  Regression -> MSE: 0.000364, MAE: 0.016236, R²: -0.0047
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07453 | val 0.07033
  Epoch 018 - train 0.07748 | val 0.06958
  Regression -> MSE: 0.000105, MAE: 0.007963, R²: 0.0242
  Directional -> Accuracy: 0.5286, MCC: 0.0432, F1: 0.5823

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07147 | val 0.11767
  Epoch 016 - train 0.06906 | val 0.11802
  Regression -> MSE: 0.000157, MAE: 0.009571, R²: -0.0041
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07450 | val 0.07263
  Epoch 016 - train 0.07727 | val 0.07299
  Regression -> MSE: 0.000272, MAE: 0.013035, R²: -0.0009
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06860 | val 0.08965
  Epoch 020 - train 0.06961 | val 0.08985
  Regression -> MSE: 0.000207, MAE: 0.010515, R²: -0.3821
  Directional -> Accuracy: 0.4923, MCC: -0.0289, F1: 0.5479

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07508 | val 0.09858
  Epoch 016 - train 0.07542 | val 0.09758
  Regression -> MSE: 0.000229, MAE: 0.010952, R²: -0.0116
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07412 | val 0.08792
  Epoch 016 - train 0.06829 | val 0.08797
  Regression -> MSE: 0.000152, MAE: 0.008786, R²: -0.0593
  Directional -> Accuracy: 0.4167, MCC: -0.0265, F1: 0.3000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.06907 | val 0.07942
  Epoch 020 - train 0.07045 | val 0.07922
  Epoch 025 - train 0.06847 | val 0.07945
  Regression -> MSE: 0.000172, MAE: 0.010199, R²: -0.0414
  Directional -> Accuracy: 0.5303, MCC: 0.0620, F1: 0.4746

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08447 | val 0.10204
  Epoch 016 - train 0.07890 | val 0.10003
  Regression -> MSE: 0.000096, MAE: 0.007546, R²: -0.1247
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07587 | val 0.08701
  Epoch 016 - train 0.07503 | val 0.08702
  Regression -> MSE: 0.000213, MAE: 0.011319, R²: -0.0055
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06773 | val 0.06342
  Epoch 016 - train 0.06869 | val 0.06322
  Regression -> MSE: 0.000099, MAE: 0.008216, R²: -0.0744
  Directional -> Accuracy: 0.3750, MCC: -0.2493, F1: 0.1026

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07534 | val 0.07563
  Epoch 016 - train 0.07750 | val 0.08015
  Regression -> MSE: 0.000125, MAE: 0.009499, R²: -0.2141
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.08095 | val 0.06903
  Epoch 016 - train 0.07348 | val 0.06903
  Regression -> MSE: 0.000234, MAE: 0.012646, R²: -0.0129
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07096 | val 0.08493
  Epoch 016 - train 0.07583 | val 0.08526
  Regression -> MSE: 0.000182, MAE: 0.008030, R²: -0.0939
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08273 | val 0.06785
  Epoch 016 - train 0.07896 | val 0.07305
  Regression -> MSE: 0.000237, MAE: 0.011888, R²: -0.0033
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07649 | val 0.11497
  Epoch 016 - train 0.07540 | val 0.11535
  Regression -> MSE: 0.000231, MAE: 0.009967, R²: -0.0044
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07683 | val 0.08070
  Epoch 016 - train 0.07591 | val 0.08127
  Regression -> MSE: 0.000135, MAE: 0.008183, R²: -0.0001
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07105 | val 0.08847
  Epoch 016 - train 0.07243 | val 0.08873
  Regression -> MSE: 0.000189, MAE: 0.010464, R²: -0.0034
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07155 | val 0.07795
  Epoch 016 - train 0.06513 | val 0.07797
  Regression -> MSE: 0.000270, MAE: 0.010608, R²: -0.0307
  Directional -> Accuracy: 0.5068, MCC: 0.0735, F1: 0.4194

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07305 | val 0.07017
  Epoch 016 - train 0.07087 | val 0.07807
  Regression -> MSE: 0.000171, MAE: 0.010391, R²: -0.0234
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06923 | val 0.07860
  Epoch 016 - train 0.07384 | val 0.07781
  Regression -> MSE: 0.000186, MAE: 0.010548, R²: -0.0313
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07487 | val 0.07130
  Epoch 016 - train 0.07210 | val 0.07140
  Regression -> MSE: 0.000345, MAE: 0.011711, R²: -0.0079
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08545 | val 0.04865
  Epoch 016 - train 0.07904 | val 0.04829
  Regression -> MSE: 0.000110, MAE: 0.008329, R²: -0.0487
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07207 | val 0.10398
  Epoch 016 - train 0.07186 | val 0.10447
  Regression -> MSE: 0.000219, MAE: 0.011339, R²: -0.0039
  Directional -> Accuracy: 0.4737, MCC: -0.0970, F1: 0.2500

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07613 | val 0.12316
  Epoch 016 - train 0.07514 | val 0.12384
  Regression -> MSE: 0.000089, MAE: 0.007405, R²: -0.1508
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07734 | val 0.05473
  Epoch 016 - train 0.07298 | val 0.05536
  Regression -> MSE: 0.000314, MAE: 0.014194, R²: -0.0211
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07620 | val 0.04694
  Epoch 016 - train 0.07161 | val 0.05148
  Regression -> MSE: 0.000249, MAE: 0.011533, R²: -0.0201
  Directional -> Accuracy: 0.5526, MCC: 0.0930, F1: 0.6667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.07583 | val 0.08530
  Epoch 016 - train 0.07457 | val 0.08532
  Regression -> MSE: 0.000081, MAE: 0.007103, R²: -0.0056
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07680 | val 0.08598
  Epoch 016 - train 0.07838 | val 0.08585
  Regression -> MSE: 0.000310, MAE: 0.014544, R²: -0.0108
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07343 | val 0.07632
  Epoch 016 - train 0.07438 | val 0.07760
  Regression -> MSE: 0.000098, MAE: 0.007245, R²: 0.0021
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08257 | val 0.08340
  Epoch 016 - train 0.08053 | val 0.08480
  Regression -> MSE: 0.000172, MAE: 0.009819, R²: -0.0016
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07394 | val 0.07945
  Epoch 016 - train 0.07275 | val 0.07848
  Regression -> MSE: 0.000226, MAE: 0.011825, R²: -0.0133
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07110 | val 0.07854
  Epoch 016 - train 0.06962 | val 0.07749
  Regression -> MSE: 0.000092, MAE: 0.007659, R²: -0.0008
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.08092 | val 0.11827
  Epoch 016 - train 0.07837 | val 0.11919
  Regression -> MSE: 0.000164, MAE: 0.010218, R²: 0.0007
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.07507 | val 0.14277
  Epoch 016 - train 0.07519 | val 0.13858
  Regression -> MSE: 0.000122, MAE: 0.008984, R²: -0.0482
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.07184 | val 0.09571

[I 2026-02-24 00:10:33,390] Trial 54 finished with value: -0.01152827245920862 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 2.3450580772077888e-05, 'weight_decay': 1.930970629396016e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.10091018899467254, 'early_stopping_min_delta': 0.0026335482004867005}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 019 - train 0.07227 | val 0.09451
  Regression -> MSE: 0.000247, MAE: 0.012403, R²: -0.0411
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.18246 | val 0.19595
  Epoch 020 - train 0.17892 | val 0.19595
  Epoch 021 - train 0.17604 | val 0.19584
  Regression -> MSE: 0.000246, MAE: 0.012484, R²: -0.0015
  Directional -> Accuracy: 0.5513, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.18817 | val 0.17455
  Epoch 020 - train 0.17414 | val 0.17800
  Epoch 021 - train 0.17348 | val 0.17747
  Regression -> MSE: 0.000709, MAE: 0.020028, R²: -0.0249
  Directional -> Accuracy: 0.4468, MCC: -0.2198, F1: 0.5938

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.18873 | val 0.25185
  Epoch 020 - train 0.18957 | val 0.25186
  Epoch 028 - train 0.18904 | val 0.25233
  Regression -> MSE: 0.000333, MAE: 0.014739, R²: 0.0354
  Directional -> Accuracy: 0.6458, MCC: 0.2814, F1: 0.6909

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.17127 | val 0.13478
  Epoch 020 - train 0.17567 | val 0.13446
  Epoch 021 - train 0.16789 | val 0.13431
  Regression -> MSE: 0.000345, MAE: 0.014433, R²: -0.0005
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.18363 | val 0.16614
  Epoch 020 - train 0.18760 | val 0.16568
  Epoch 021 - train 0.17999 | val 0.16563
  Regression -> MSE: 0.000204, MAE: 0.010198, R²: -0.0182
  Directional -> Accuracy: 0.4231, MCC: -0.1769, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.18190 | val 0.29669
  Epoch 020 - train 0.17593 | val 0.29848
  Epoch 021 - train 0.17100 | val 0.29897
  Regression -> MSE: 0.000597, MAE: 0.018758, R²: -0.0423
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.19434 | val 0.20809
  Epoch 020 - train 0.18671 | val 0.20782
  Epoch 021 - train 0.18752 | val 0.20708
  Regression -> MSE: 0.000246, MAE: 0.012195, R²: 0.0010
  Directional -> Accuracy: 0.5143, MCC: 0.0983, F1: 0.5405

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.18210 | val 0.21199
  Epoch 020 - train 0.16952 | val 0.21432
  Epoch 021 - train 0.15982 | val 0.21403
  Regression -> MSE: 0.000602, MAE: 0.019182, R²: -0.0297
  Directional -> Accuracy: 0.4667, MCC: 0.0706, F1: 0.5862

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.18784 | val 0.24942
  Epoch 020 - train 0.18405 | val 0.24963
  Epoch 021 - train 0.18023 | val 0.25043
  Regression -> MSE: 0.000352, MAE: 0.015764, R²: -0.0411
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.18340 | val 0.21597
  Epoch 020 - train 0.19003 | val 0.21822
  Epoch 021 - train 0.18487 | val 0.21788
  Regression -> MSE: 0.000239, MAE: 0.011616, R²: -0.0054
  Directional -> Accuracy: 0.5352, MCC: 0.0382, F1: 0.4211

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.17780 | val 0.24783
  Epoch 020 - train 0.17008 | val 0.24768
  Epoch 021 - train 0.16520 | val 0.24847
  Regression -> MSE: 0.000305, MAE: 0.013627, R²: 0.0039
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.18167 | val 0.21070
  Epoch 020 - train 0.18010 | val 0.21082
  Epoch 021 - train 0.20063 | val 0.21057
  Regression -> MSE: 0.000675, MAE: 0.019494, R²: -0.0079
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17438 | val 0.17903
  Epoch 020 - train 0.19126 | val 0.18726
  Epoch 021 - train 0.17741 | val 0.18965
  Regression -> MSE: 0.000155, MAE: 0.009850, R²: -0.0336
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.16615 | val 0.21788
  Epoch 020 - train 0.17036 | val 0.21872
  Epoch 021 - train 0.16363 | val 0.21960
  Regression -> MSE: 0.000227, MAE: 0.010788, R²: -0.0103
  Directional -> Accuracy: 0.5484, MCC: 0.1189, F1: 0.3636

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.19096 | val 0.32978
  Epoch 020 - train 0.19205 | val 0.33025
  Epoch 021 - train 0.19130 | val 0.33052
  Regression -> MSE: 0.000394, MAE: 0.016347, R²: -0.0477
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.18114 | val 0.16903
  Epoch 020 - train 0.18492 | val 0.16843
  Epoch 021 - train 0.19648 | val 0.16852
  Regression -> MSE: 0.000107, MAE: 0.007842, R²: -0.0107
  Directional -> Accuracy: 0.5352, MCC: 0.0000, F1: 0.6972

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.19057 | val 0.29881
  Epoch 020 - train 0.18051 | val 0.29856
  Epoch 021 - train 0.19072 | val 0.29835
  Regression -> MSE: 0.000164, MAE: 0.009792, R²: -0.0219
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.19269 | val 0.19916
  Epoch 020 - train 0.17395 | val 0.19612
  Epoch 021 - train 0.17859 | val 0.19677
  Regression -> MSE: 0.000286, MAE: 0.013538, R²: -0.0648
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.16824 | val 0.22716
  Epoch 020 - train 0.17749 | val 0.22634
  Epoch 021 - train 0.17112 | val 0.22633
  Regression -> MSE: 0.000146, MAE: 0.008724, R²: 0.0070
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.19025 | val 0.26181
  Epoch 020 - train 0.20231 | val 0.25736
  Epoch 021 - train 0.20857 | val 0.25768
  Regression -> MSE: 0.000229, MAE: 0.011060, R²: -0.0096
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17932 | val 0.19287
  Epoch 020 - train 0.18960 | val 0.19221
  Epoch 021 - train 0.17405 | val 0.19210
  Regression -> MSE: 0.000150, MAE: 0.008565, R²: -0.0084
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.17738 | val 0.17344
  Epoch 020 - train 0.16883 | val 0.17287
  Epoch 028 - train 0.16907 | val 0.17329
  Regression -> MSE: 0.000204, MAE: 0.010874, R²: -0.1494
  Directional -> Accuracy: 0.5224, MCC: 0.0866, F1: 0.2381

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.18773 | val 0.18575
  Epoch 020 - train 0.21411 | val 0.18429
  Epoch 030 - train 0.18806 | val 0.18379
  Regression -> MSE: 0.000098, MAE: 0.007648, R²: -0.1703
  Directional -> Accuracy: 0.5593, MCC: 0.2145, F1: 0.4800

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.17686 | val 0.18916
  Epoch 020 - train 0.17306 | val 0.19064
  Epoch 021 - train 0.16270 | val 0.18978
  Regression -> MSE: 0.000217, MAE: 0.011351, R²: 0.0052
  Directional -> Accuracy: 0.4925, MCC: 0.0441, F1: 0.6383

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.19551 | val 0.14079
  Epoch 020 - train 0.17159 | val 0.13981
  Epoch 021 - train 0.19297 | val 0.13972
  Regression -> MSE: 0.000107, MAE: 0.008482, R²: -0.1699
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18926 | val 0.10810
  Epoch 020 - train 0.18931 | val 0.12566
  Epoch 021 - train 0.18462 | val 0.12471
  Regression -> MSE: 0.000142, MAE: 0.009797, R²: -0.1323
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.19968 | val 0.16961
  Epoch 020 - train 0.20151 | val 0.17606
  Epoch 021 - train 0.20928 | val 0.17560
  Regression -> MSE: 0.000238, MAE: 0.012741, R²: 0.0001
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.17959 | val 0.17626
  Epoch 020 - train 0.17746 | val 0.17662
  Epoch 030 - train 0.18258 | val 0.17613
  Regression -> MSE: 0.000215, MAE: 0.009072, R²: -0.3132
  Directional -> Accuracy: 0.5345, MCC: 0.1948, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.20219 | val 0.12657
  Epoch 020 - train 0.19908 | val 0.13107
  Epoch 021 - train 0.19521 | val 0.13131
  Regression -> MSE: 0.000234, MAE: 0.011943, R²: 0.0005
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.18810 | val 0.24006
  Epoch 020 - train 0.18008 | val 0.24242
  Epoch 021 - train 0.17249 | val 0.24316
  Regression -> MSE: 0.000249, MAE: 0.010428, R²: 0.0040
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18489 | val 0.20223
  Epoch 020 - train 0.21169 | val 0.20320
  Epoch 021 - train 0.18416 | val 0.20351
  Regression -> MSE: 0.000135, MAE: 0.008164, R²: -0.0118
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.19489 | val 0.21020
  Epoch 020 - train 0.19208 | val 0.21031
  Epoch 021 - train 0.18372 | val 0.21059
  Regression -> MSE: 0.000195, MAE: 0.010439, R²: -0.0333
  Directional -> Accuracy: 0.5686, MCC: 0.1775, F1: 0.4762

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.17471 | val 0.22369
  Epoch 020 - train 0.16678 | val 0.22315
  Epoch 021 - train 0.17176 | val 0.22412
  Regression -> MSE: 0.000261, MAE: 0.010510, R²: -0.0091
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16436 | val 0.13613
  Epoch 020 - train 0.18447 | val 0.13798
  Epoch 028 - train 0.17190 | val 0.13877
  Regression -> MSE: 0.000157, MAE: 0.010070, R²: 0.0373
  Directional -> Accuracy: 0.6154, MCC: 0.2539, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.18201 | val 0.15770
  Epoch 020 - train 0.16840 | val 0.15842
  Epoch 024 - train 0.17190 | val 0.15839
  Regression -> MSE: 0.000189, MAE: 0.010642, R²: -0.0320
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.20431 | val 0.17233
  Epoch 020 - train 0.18830 | val 0.17064
  Epoch 021 - train 0.19120 | val 0.17049
  Regression -> MSE: 0.000353, MAE: 0.012006, R²: -0.0118
  Directional -> Accuracy: 0.5441, MCC: -0.0892, F1: 0.6990

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.19368 | val 0.11784
  Epoch 020 - train 0.18502 | val 0.12103
  Epoch 021 - train 0.21089 | val 0.12007
  Regression -> MSE: 0.000119, MAE: 0.008264, R²: -0.1451
  Directional -> Accuracy: 0.5227, MCC: 0.0716, F1: 0.2222

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.19068 | val 0.22618
  Epoch 020 - train 0.18702 | val 0.22709
  Epoch 021 - train 0.19284 | val 0.22783
  Regression -> MSE: 0.000215, MAE: 0.011196, R²: -0.0018
  Directional -> Accuracy: 0.5862, MCC: 0.1584, F1: 0.4545

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.20257 | val 0.25979
  Epoch 020 - train 0.17135 | val 0.26034
  Epoch 030 - train 0.18971 | val 0.26026
  Regression -> MSE: 0.000143, MAE: 0.009600, R²: -0.7940
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.17373 | val 0.15076
  Epoch 020 - train 0.18541 | val 0.15518
  Epoch 021 - train 0.18669 | val 0.15457
  Regression -> MSE: 0.000361, MAE: 0.016319, R²: -0.1000
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17924 | val 0.11963
  Epoch 020 - train 0.17424 | val 0.12295
  Epoch 021 - train 0.18220 | val 0.12297
  Regression -> MSE: 0.000255, MAE: 0.011233, R²: -0.0727
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.17358 | val 0.19741
  Epoch 020 - train 0.18605 | val 0.19721
  Epoch 021 - train 0.17025 | val 0.19720
  Regression -> MSE: 0.000081, MAE: 0.007102, R²: -0.0039
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.19269 | val 0.18046
  Epoch 020 - train 0.18409 | val 0.18160
  Epoch 028 - train 0.18254 | val 0.18114
  Regression -> MSE: 0.000362, MAE: 0.015237, R²: -0.0070
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.19867 | val 0.19424
  Epoch 020 - train 0.18123 | val 0.19077
  Epoch 030 - train 0.17721 | val 0.19141
  Regression -> MSE: 0.000106, MAE: 0.007245, R²: -0.0999
  Directional -> Accuracy: 0.5333, MCC: -0.1348, F1: 0.6957

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.19924 | val 0.21883
  Epoch 020 - train 0.19261 | val 0.22319
  Epoch 021 - train 0.18147 | val 0.22394
  Regression -> MSE: 0.000186, MAE: 0.010731, R²: -0.0306
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.17972 | val 0.21544
  Epoch 020 - train 0.17668 | val 0.21681
  Epoch 021 - train 0.17279 | val 0.21848
  Regression -> MSE: 0.000220, MAE: 0.011602, R²: -0.0034
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.17249 | val 0.18643
  Epoch 020 - train 0.18954 | val 0.18636
  Epoch 021 - train 0.19160 | val 0.18608

[I 2026-02-24 00:12:37,699] Trial 55 finished with value: -0.011613161670917365 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 5.355083539064744e-06, 'weight_decay': 9.438189104277422e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2519102467992077, 'early_stopping_min_delta': 0.00212779239908025}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.18819 | val 0.23506
  Epoch 021 - train 0.17839 | val 0.23576
  Regression -> MSE: 0.000235, MAE: 0.012345, R²: -0.0062
  Directional -> Accuracy: 0.4677, MCC: -0.0572, F1: 0.5926

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.25942 | val 0.35404
  Epoch 016 - train 0.26377 | val 0.35237
  Regression -> MSE: 0.000267, MAE: 0.013168, R²: -0.0772
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.25676 | val 0.23058
  Epoch 016 - train 0.25960 | val 0.23162
  Regression -> MSE: 0.000704, MAE: 0.019694, R²: -0.0283
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.27051 | val 0.44439
  Epoch 016 - train 0.28614 | val 0.44178
  Regression -> MSE: 0.000328, MAE: 0.014595, R²: -0.0580
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.21142 | val 0.20010
  Epoch 016 - train 0.21386 | val 0.19922
  Regression -> MSE: 0.000352, MAE: 0.014600, R²: -0.0066
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.27182 | val 0.30188
  Epoch 016 - train 0.26607 | val 0.30176
  Regression -> MSE: 0.000208, MAE: 0.010138, R²: -0.0233
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.25905 | val 0.52109
  Epoch 016 - train 0.26648 | val 0.52287
  Regression -> MSE: 0.000558, MAE: 0.018157, R²: -0.0054
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.26763 | val 0.31299
  Epoch 020 - train 0.27189 | val 0.31056
  Epoch 030 - train 0.27469 | val 0.31046
  Regression -> MSE: 0.000244, MAE: 0.012007, R²: 0.0043
  Directional -> Accuracy: 0.4638, MCC: 0.0500, F1: 0.5542

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.27114 | val 0.45497
  Epoch 016 - train 0.26048 | val 0.52159
  Regression -> MSE: 0.000648, MAE: 0.020219, R²: -0.0844
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.25852 | val 0.30448
  Epoch 016 - train 0.25907 | val 0.30232
  Regression -> MSE: 0.000396, MAE: 0.015994, R²: -0.0322
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.28262 | val 0.37628
  Epoch 016 - train 0.26871 | val 0.37657
  Regression -> MSE: 0.000243, MAE: 0.011740, R²: -0.0049
  Directional -> Accuracy: 0.4429, MCC: 0.0000, F1: 0.5806

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.23233 | val 0.39091
  Epoch 016 - train 0.23343 | val 0.39891
  Regression -> MSE: 0.000319, MAE: 0.013574, R²: -0.0275
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.28083 | val 0.33688
  Epoch 016 - train 0.28949 | val 0.33448
  Regression -> MSE: 0.000691, MAE: 0.019995, R²: -0.0200
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.26429 | val 0.51309
  Epoch 016 - train 0.28404 | val 0.53804
  Regression -> MSE: 0.000139, MAE: 0.009011, R²: -0.0028
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.26563 | val 0.38134
  Epoch 016 - train 0.22706 | val 0.37580
  Regression -> MSE: 0.000225, MAE: 0.010719, R²: 0.0018
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.25944 | val 0.57721
  Epoch 016 - train 0.24222 | val 0.56680
  Regression -> MSE: 0.000369, MAE: 0.015935, R²: -0.0196
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.27499 | val 0.31561
  Epoch 016 - train 0.26953 | val 0.31254
  Regression -> MSE: 0.000109, MAE: 0.008125, R²: -0.0086
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.25996 | val 0.48542
  Epoch 016 - train 0.24762 | val 0.48534
  Regression -> MSE: 0.000156, MAE: 0.009525, R²: 0.0009
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.26134 | val 0.26684
  Epoch 016 - train 0.25382 | val 0.26806
  Regression -> MSE: 0.000285, MAE: 0.013642, R²: -0.0472
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.24872 | val 0.34910
  Epoch 016 - train 0.23526 | val 0.34355
  Regression -> MSE: 0.000168, MAE: 0.009150, R²: -0.1228
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.24628 | val 0.39564
  Epoch 016 - train 0.25325 | val 0.39846
  Regression -> MSE: 0.000232, MAE: 0.010965, R²: -0.0251
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.29910 | val 0.36135
  Epoch 016 - train 0.26467 | val 0.36056
  Regression -> MSE: 0.000150, MAE: 0.008709, R²: -0.0463
  Directional -> Accuracy: 0.5625, MCC: 0.0770, F1: 0.6441

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.24451 | val 0.29287
  Epoch 016 - train 0.23081 | val 0.29255
  Regression -> MSE: 0.000167, MAE: 0.010269, R²: -0.0089
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.27879 | val 0.33775
  Epoch 019 - train 0.28959 | val 0.33858
  Regression -> MSE: 0.000087, MAE: 0.007126, R²: -0.0256
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.27749 | val 0.46337
  Epoch 016 - train 0.27006 | val 0.45487
  Regression -> MSE: 0.000213, MAE: 0.011132, R²: -0.0042
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.24752 | val 0.21068
  Epoch 020 - train 0.22437 | val 0.20774
  Epoch 022 - train 0.22254 | val 0.20733
  Regression -> MSE: 0.000115, MAE: 0.008530, R²: -0.2491
  Directional -> Accuracy: 0.4821, MCC: 0.1728, F1: 0.1212

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.26816 | val 0.19786
  Epoch 016 - train 0.25907 | val 0.20210
  Regression -> MSE: 0.000107, MAE: 0.008920, R²: -0.0378
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.27306 | val 0.40591
  Epoch 016 - train 0.27302 | val 0.40966
  Regression -> MSE: 0.000243, MAE: 0.012908, R²: -0.0490
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.25463 | val 0.29723
  Epoch 016 - train 0.24365 | val 0.29706
  Regression -> MSE: 0.000176, MAE: 0.007892, R²: -0.0590
  Directional -> Accuracy: 0.5088, MCC: -0.0063, F1: 0.5758

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.27027 | val 0.19962
  Epoch 020 - train 0.25637 | val 0.20204
  Epoch 024 - train 0.27792 | val 0.20194
  Regression -> MSE: 0.000236, MAE: 0.011893, R²: 0.0029
  Directional -> Accuracy: 0.4634, MCC: -0.1383, F1: 0.5926

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.25611 | val 0.42661
  Epoch 020 - train 0.26415 | val 0.43485
  Regression -> MSE: 0.000232, MAE: 0.009958, R²: -0.0052
  Directional -> Accuracy: 0.5349, MCC: 0.1527, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.27171 | val 0.29352
  Epoch 020 - train 0.24321 | val 0.29660
  Epoch 023 - train 0.24924 | val 0.29785
  Regression -> MSE: 0.000138, MAE: 0.008414, R²: -0.0254
  Directional -> Accuracy: 0.4419, MCC: -0.1644, F1: 0.5556

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.25942 | val 0.32124
  Epoch 016 - train 0.24930 | val 0.32199
  Regression -> MSE: 0.000192, MAE: 0.010375, R²: -0.0176
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.24502 | val 0.28983
  Epoch 016 - train 0.23985 | val 0.28569
  Regression -> MSE: 0.000277, MAE: 0.010854, R²: -0.0589
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.27471 | val 0.21573
  Epoch 016 - train 0.24483 | val 0.31512
  Regression -> MSE: 0.000169, MAE: 0.010364, R²: -0.0118
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.23074 | val 0.28206
  Epoch 016 - train 0.22973 | val 0.27939
  Regression -> MSE: 0.000182, MAE: 0.010356, R²: -0.0127
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.25493 | val 0.23475
  Epoch 016 - train 0.25540 | val 0.23468
  Regression -> MSE: 0.000347, MAE: 0.012152, R²: -0.0124
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.28215 | val 0.15397
  Epoch 016 - train 0.26869 | val 0.15582
  Regression -> MSE: 0.000111, MAE: 0.008292, R²: -0.0586
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.25424 | val 0.38820
  Epoch 016 - train 0.25665 | val 0.38583
  Regression -> MSE: 0.000227, MAE: 0.011555, R²: -0.0407
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.25950 | val 0.48342
  Epoch 016 - train 0.27211 | val 0.48238
  Regression -> MSE: 0.000086, MAE: 0.007269, R²: -0.1130
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.25623 | val 0.19611
  Epoch 016 - train 0.26018 | val 0.20057
  Regression -> MSE: 0.000317, MAE: 0.014322, R²: -0.0302
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.28640 | val 0.15390
  Epoch 016 - train 0.26495 | val 0.20515
  Regression -> MSE: 0.000254, MAE: 0.011460, R²: -0.0407
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.24250 | val 0.30268
  Epoch 016 - train 0.23190 | val 0.30496
  Regression -> MSE: 0.000081, MAE: 0.007073, R²: 0.0011
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.27402 | val 0.37868
  Epoch 016 - train 0.29426 | val 0.38285
  Regression -> MSE: 0.000307, MAE: 0.014490, R²: -0.0011
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.26265 | val 0.26908
  Epoch 016 - train 0.24631 | val 0.27276
  Regression -> MSE: 0.000098, MAE: 0.007237, R²: -0.0023
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.30854 | val 0.33694
  Epoch 016 - train 0.27646 | val 0.34008
  Regression -> MSE: 0.000173, MAE: 0.009485, R²: -0.0046
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.24044 | val 0.32610
  Epoch 016 - train 0.24087 | val 0.33355
  Regression -> MSE: 0.000227, MAE: 0.011863, R²: -0.0174
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.26442 | val 0.28645
  Epoch 016 - train 0.25946 | val 0.28803
  Regression -> MSE: 0.000094, MAE: 0.007738, R²: -0.0166
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.26947 | val 0.45017
  Epoch 016 - train 0.28198 | val 0.44971
  Regression -> MSE: 0.000164, MAE: 0.010244, R²: -0.0036
  Directional -> Accuracy: 0.5926, MCC: 0.1816, F1: 0.6333

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.25125 | val 0.33153
  Epoch 016 - train 0.25333 | val 0.33022
  Regression -> MSE: 0.000117, MAE: 0.008963, R²: -0.0109
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.29735 | val 0.44557

[I 2026-02-24 00:14:45,332] Trial 56 finished with value: -0.01146289913660561 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 1.2075339274615143e-05, 'weight_decay': 1.6415874848788136e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.430198477819305, 'early_stopping_min_delta': 0.00437465243162136}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 016 - train 0.28076 | val 0.43111
  Regression -> MSE: 0.000243, MAE: 0.012350, R²: -0.0235
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.20545 | val 0.26910
  Epoch 020 - train 0.20331 | val 0.26820
  Epoch 026 - train 0.20465 | val 0.26840
  Regression -> MSE: 0.000247, MAE: 0.012567, R²: -0.0069
  Directional -> Accuracy: 0.4744, MCC: -0.0840, F1: 0.3492

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.21779 | val 0.18914
  Epoch 020 - train 0.20825 | val 0.18518
  Epoch 021 - train 0.20425 | val 0.18518
  Regression -> MSE: 0.000713, MAE: 0.020013, R²: -0.0317
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.23092 | val 0.36088
  Epoch 020 - train 0.22192 | val 0.36317
  Epoch 021 - train 0.22896 | val 0.36363
  Regression -> MSE: 0.000368, MAE: 0.015277, R²: -0.0645
  Directional -> Accuracy: 0.4583, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.17801 | val 0.19995
  Epoch 020 - train 0.17823 | val 0.20923
  Epoch 021 - train 0.17479 | val 0.20973
  Regression -> MSE: 0.000345, MAE: 0.014435, R²: 0.0001
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.21549 | val 0.23190
  Epoch 020 - train 0.21078 | val 0.23714
  Epoch 021 - train 0.21556 | val 0.23754
  Regression -> MSE: 0.000209, MAE: 0.010711, R²: -0.0402
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.20684 | val 0.40306
  Epoch 020 - train 0.20323 | val 0.40302
  Epoch 021 - train 0.20176 | val 0.40322
  Regression -> MSE: 0.000581, MAE: 0.018436, R²: -0.0149
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.21526 | val 0.27327
  Epoch 020 - train 0.22111 | val 0.27067
  Epoch 021 - train 0.21926 | val 0.27053
  Regression -> MSE: 0.000247, MAE: 0.011987, R²: -0.0054
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.21736 | val 0.26787
  Epoch 020 - train 0.21183 | val 0.28218
  Epoch 021 - train 0.22033 | val 0.28282
  Regression -> MSE: 0.000598, MAE: 0.019097, R²: -0.0229
  Directional -> Accuracy: 0.5556, MCC: 0.0636, F1: 0.4118

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.21457 | val 0.32773
  Epoch 020 - train 0.20759 | val 0.33661
  Epoch 021 - train 0.20297 | val 0.33820
  Regression -> MSE: 0.000341, MAE: 0.015295, R²: -0.0083
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.21675 | val 0.29276
  Epoch 020 - train 0.21063 | val 0.29555
  Epoch 021 - train 0.21061 | val 0.29577
  Regression -> MSE: 0.000240, MAE: 0.011586, R²: -0.0080
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.19393 | val 0.30604
  Epoch 020 - train 0.20010 | val 0.31017
  Epoch 021 - train 0.19183 | val 0.31040
  Regression -> MSE: 0.000316, MAE: 0.013532, R²: -0.0326
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.22588 | val 0.26540
  Epoch 020 - train 0.22851 | val 0.27304
  Epoch 021 - train 0.23062 | val 0.27317
  Regression -> MSE: 0.000673, MAE: 0.019570, R²: -0.0047
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.23357 | val 0.22177
  Epoch 020 - train 0.23213 | val 0.27527
  Epoch 021 - train 0.23628 | val 0.27576
  Regression -> MSE: 0.000158, MAE: 0.009965, R²: -0.0518
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.19650 | val 0.27719
  Epoch 020 - train 0.19220 | val 0.26955
  Epoch 030 - train 0.19125 | val 0.26647
  Regression -> MSE: 0.000225, MAE: 0.010742, R²: -0.0027
  Directional -> Accuracy: 0.4839, MCC: -0.0458, F1: 0.2000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.21057 | val 0.44380
  Epoch 020 - train 0.20341 | val 0.44714
  Epoch 021 - train 0.20377 | val 0.44814
  Regression -> MSE: 0.000385, MAE: 0.016329, R²: -0.0252
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.21596 | val 0.21952
  Epoch 020 - train 0.21465 | val 0.22759
  Epoch 028 - train 0.21635 | val 0.22851
  Regression -> MSE: 0.000106, MAE: 0.007953, R²: 0.0004
  Directional -> Accuracy: 0.4930, MCC: -0.0032, F1: 0.4706

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.20270 | val 0.36339
  Epoch 020 - train 0.20272 | val 0.37255
  Epoch 021 - train 0.20031 | val 0.37146
  Regression -> MSE: 0.000161, MAE: 0.009981, R²: -0.0034
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.20600 | val 0.21362
  Epoch 020 - train 0.20877 | val 0.22253
  Epoch 021 - train 0.20269 | val 0.22375
  Regression -> MSE: 0.000273, MAE: 0.012762, R²: -0.0163
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.19340 | val 0.28997
  Epoch 020 - train 0.19443 | val 0.29024
  Epoch 021 - train 0.18710 | val 0.28996
  Regression -> MSE: 0.000165, MAE: 0.009029, R²: -0.1219
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.22526 | val 0.31697
  Epoch 020 - train 0.22239 | val 0.31974
  Epoch 026 - train 0.22160 | val 0.31943
  Regression -> MSE: 0.000277, MAE: 0.012063, R²: -0.2237
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.21607 | val 0.25298
  Epoch 020 - train 0.21878 | val 0.25571
  Epoch 021 - train 0.21766 | val 0.25502
  Regression -> MSE: 0.000159, MAE: 0.009027, R²: -0.0690
  Directional -> Accuracy: 0.3469, MCC: -0.1894, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.21132 | val 0.24339
  Epoch 020 - train 0.19831 | val 0.24523
  Epoch 021 - train 0.20278 | val 0.24549
  Regression -> MSE: 0.000200, MAE: 0.010771, R²: -0.1316
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.22505 | val 0.25155
  Epoch 020 - train 0.22187 | val 0.26277
  Epoch 021 - train 0.22125 | val 0.26202
  Regression -> MSE: 0.000084, MAE: 0.006964, R²: -0.0039
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.21221 | val 0.25554
  Epoch 020 - train 0.21206 | val 0.26277
  Epoch 021 - train 0.21375 | val 0.26666
  Regression -> MSE: 0.000219, MAE: 0.011473, R²: -0.0019
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.19390 | val 0.18151
  Epoch 020 - train 0.19120 | val 0.17929
  Epoch 021 - train 0.18952 | val 0.17985
  Regression -> MSE: 0.000097, MAE: 0.008185, R²: -0.0606
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.22238 | val 0.12567
  Epoch 020 - train 0.22096 | val 0.14487
  Epoch 021 - train 0.21615 | val 0.14927
  Regression -> MSE: 0.000137, MAE: 0.009644, R²: -0.0887
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.22283 | val 0.18813
  Epoch 020 - train 0.21401 | val 0.19021
  Epoch 021 - train 0.21848 | val 0.18985
  Regression -> MSE: 0.000240, MAE: 0.012822, R²: -0.0086
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.21448 | val 0.24290
  Epoch 020 - train 0.21291 | val 0.23803
  Epoch 030 - train 0.20364 | val 0.23855
  Regression -> MSE: 0.000185, MAE: 0.008413, R²: -0.1272
  Directional -> Accuracy: 0.4310, MCC: -0.1255, F1: 0.4211

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22045 | val 0.16653
  Epoch 020 - train 0.21797 | val 0.16768
  Epoch 021 - train 0.21812 | val 0.16836
  Regression -> MSE: 0.000237, MAE: 0.012015, R²: -0.0104
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.21242 | val 0.30439
  Epoch 020 - train 0.21415 | val 0.30308
  Epoch 021 - train 0.20689 | val 0.30337
  Regression -> MSE: 0.000251, MAE: 0.010424, R²: -0.0049
  Directional -> Accuracy: 0.4444, MCC: -0.1129, F1: 0.4681

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.23061 | val 0.29815
  Epoch 020 - train 0.23551 | val 0.31304
  Epoch 021 - train 0.23015 | val 0.31349
  Regression -> MSE: 0.000134, MAE: 0.008282, R²: -0.0085
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.24524 | val 0.28499
  Epoch 020 - train 0.24501 | val 0.30619
  Epoch 021 - train 0.24263 | val 0.30542
  Regression -> MSE: 0.000198, MAE: 0.010712, R²: -0.0521
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.20179 | val 0.25306
  Epoch 020 - train 0.19252 | val 0.25318
  Epoch 021 - train 0.19174 | val 0.25386
  Regression -> MSE: 0.000266, MAE: 0.010525, R²: -0.0298
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.22248 | val 0.22924
  Epoch 020 - train 0.21482 | val 0.27776
  Epoch 021 - train 0.22404 | val 0.28619
  Regression -> MSE: 0.000169, MAE: 0.010281, R²: -0.0420
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.19620 | val 0.25797
  Epoch 020 - train 0.19116 | val 0.32416
  Epoch 021 - train 0.19103 | val 0.32491
  Regression -> MSE: 0.000190, MAE: 0.010760, R²: -0.0420
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.19751 | val 0.19311
  Epoch 020 - train 0.20240 | val 0.19678
  Epoch 021 - train 0.19867 | val 0.19626
  Regression -> MSE: 0.000349, MAE: 0.012142, R²: 0.0003
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.22326 | val 0.14462
  Epoch 020 - train 0.22647 | val 0.17720
  Epoch 021 - train 0.23150 | val 0.17826
  Regression -> MSE: 0.000118, MAE: 0.008251, R²: -0.1347
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.23287 | val 0.30524
  Epoch 020 - train 0.22704 | val 0.30622
  Epoch 021 - train 0.23147 | val 0.30756
  Regression -> MSE: 0.000223, MAE: 0.011426, R²: -0.0353
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.22959 | val 0.36329
  Epoch 020 - train 0.23031 | val 0.36780
  Epoch 021 - train 0.23223 | val 0.36768
  Regression -> MSE: 0.000098, MAE: 0.007760, R²: -0.2299
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.21355 | val 0.16259
  Epoch 020 - train 0.21378 | val 0.16576
  Epoch 021 - train 0.21774 | val 0.16640
  Regression -> MSE: 0.000329, MAE: 0.014378, R²: -0.0023
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.23064 | val 0.14615
  Epoch 020 - train 0.22266 | val 0.14252
  Epoch 030 - train 0.22904 | val 0.15439
  Regression -> MSE: 0.000251, MAE: 0.011215, R²: -0.0543
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.23199 | val 0.31825
  Epoch 020 - train 0.22104 | val 0.32260
  Epoch 021 - train 0.22598 | val 0.32162
  Regression -> MSE: 0.000083, MAE: 0.007052, R²: -0.0334
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.23094 | val 0.24189
  Epoch 020 - train 0.22595 | val 0.24587
  Epoch 021 - train 0.22607 | val 0.24547
  Regression -> MSE: 0.000361, MAE: 0.015325, R²: -0.0034
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.21975 | val 0.28039
  Epoch 020 - train 0.21917 | val 0.28831
  Epoch 021 - train 0.21194 | val 0.28878
  Regression -> MSE: 0.000102, MAE: 0.007116, R²: -0.0577
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.22066 | val 0.28159
  Epoch 020 - train 0.22211 | val 0.30103
  Epoch 021 - train 0.21893 | val 0.30340
  Regression -> MSE: 0.000182, MAE: 0.010323, R²: -0.0062
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.20358 | val 0.27488
  Epoch 020 - train 0.20267 | val 0.29115
  Epoch 021 - train 0.20549 | val 0.29221
  Regression -> MSE: 0.000220, MAE: 0.011642, R²: -0.0021
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.21005 | val 0.24827
  Epoch 020 - train 0.20774 | val 0.25380
  Epoch 021 - train 0.21487 | val 0.25309

[I 2026-02-24 00:16:24,153] Trial 57 finished with value: -0.011547850244538192 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 9.040629871202094e-06, 'weight_decay': 1.1580060967745967e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.3671413171421908, 'early_stopping_min_delta': 0.0055959399960388}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 029 - train 0.22314 | val 0.30228
  Regression -> MSE: 0.000243, MAE: 0.012461, R²: -0.0418
  Directional -> Accuracy: 0.5161, MCC: 0.0085, F1: 0.1176

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13988 | val 0.17748
  Epoch 020 - train 0.13774 | val 0.17761
  Epoch 021 - train 0.14041 | val 0.17734
  Regression -> MSE: 0.000241, MAE: 0.012332, R²: -0.0021
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12946 | val 0.11479
  Epoch 020 - train 0.12546 | val 0.11692
  Epoch 021 - train 0.13460 | val 0.11710
  Regression -> MSE: 0.000725, MAE: 0.020129, R²: -0.0394
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15384 | val 0.20872
  Epoch 020 - train 0.13672 | val 0.22317
  Epoch 021 - train 0.14061 | val 0.22387
  Regression -> MSE: 0.000317, MAE: 0.014614, R²: -0.0068
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12045 | val 0.13159
  Epoch 020 - train 0.12492 | val 0.13270
  Epoch 021 - train 0.12042 | val 0.13162
  Regression -> MSE: 0.000356, MAE: 0.014713, R²: -0.0082
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14356 | val 0.12141
  Epoch 020 - train 0.14656 | val 0.12429
  Epoch 021 - train 0.14287 | val 0.12515
  Regression -> MSE: 0.000208, MAE: 0.010275, R²: -0.0060
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13561 | val 0.21201
  Epoch 020 - train 0.13633 | val 0.21178
  Epoch 021 - train 0.14031 | val 0.21233
  Regression -> MSE: 0.000566, MAE: 0.018367, R²: -0.0006
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14082 | val 0.16068
  Epoch 020 - train 0.14402 | val 0.16093
  Epoch 021 - train 0.14466 | val 0.16158
  Regression -> MSE: 0.000252, MAE: 0.012511, R²: -0.0167
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15194 | val 0.10466
  Epoch 020 - train 0.14457 | val 0.10843
  Epoch 021 - train 0.13943 | val 0.10901
  Regression -> MSE: 0.000613, MAE: 0.019456, R²: -0.0029
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12927 | val 0.16173
  Epoch 020 - train 0.12788 | val 0.17777
  Epoch 021 - train 0.13140 | val 0.17799
  Regression -> MSE: 0.000373, MAE: 0.015806, R²: 0.0014
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15383 | val 0.19303
  Epoch 020 - train 0.14840 | val 0.19775
  Epoch 021 - train 0.15195 | val 0.19878
  Regression -> MSE: 0.000248, MAE: 0.011793, R²: -0.0111
  Directional -> Accuracy: 0.5797, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14330 | val 0.17938
  Epoch 020 - train 0.13162 | val 0.18049
  Epoch 021 - train 0.15347 | val 0.18104
  Regression -> MSE: 0.000320, MAE: 0.013496, R²: -0.0237
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14717 | val 0.14843
  Epoch 020 - train 0.14589 | val 0.14960
  Epoch 021 - train 0.14681 | val 0.14915
  Regression -> MSE: 0.000689, MAE: 0.019647, R²: -0.0048
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12959 | val 0.13813
  Epoch 020 - train 0.13360 | val 0.14566
  Epoch 021 - train 0.13982 | val 0.14538
  Regression -> MSE: 0.000140, MAE: 0.009211, R²: -0.0106
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13034 | val 0.18347
  Epoch 020 - train 0.13216 | val 0.18839
  Epoch 021 - train 0.13698 | val 0.18805
  Regression -> MSE: 0.000229, MAE: 0.010937, R²: -0.0129
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13106 | val 0.25473
  Epoch 020 - train 0.14528 | val 0.26031
  Epoch 021 - train 0.13400 | val 0.26091
  Regression -> MSE: 0.000368, MAE: 0.016293, R²: -0.0026
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15031 | val 0.13517
  Epoch 020 - train 0.14584 | val 0.13540
  Epoch 021 - train 0.14673 | val 0.13562
  Regression -> MSE: 0.000110, MAE: 0.008140, R²: -0.0157
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14168 | val 0.21665
  Epoch 020 - train 0.13109 | val 0.22445
  Epoch 021 - train 0.13221 | val 0.22551
  Regression -> MSE: 0.000162, MAE: 0.010148, R²: -0.0290
  Directional -> Accuracy: 0.4483, MCC: -0.2172, F1: 0.5789

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14220 | val 0.18293
  Epoch 020 - train 0.13261 | val 0.18785
  Epoch 021 - train 0.14204 | val 0.18495
  Regression -> MSE: 0.000282, MAE: 0.013433, R²: -0.0285
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13319 | val 0.16475
  Epoch 020 - train 0.13259 | val 0.16319
  Epoch 021 - train 0.13287 | val 0.16320
  Regression -> MSE: 0.000153, MAE: 0.008856, R²: -0.0042
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14910 | val 0.19963
  Epoch 020 - train 0.14982 | val 0.19983
  Epoch 021 - train 0.15005 | val 0.19984
  Regression -> MSE: 0.000246, MAE: 0.011212, R²: -0.0826
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14103 | val 0.16127
  Epoch 020 - train 0.13890 | val 0.16954
  Epoch 021 - train 0.15066 | val 0.16926
  Regression -> MSE: 0.000145, MAE: 0.008347, R²: -0.0063
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13242 | val 0.15466
  Epoch 020 - train 0.12727 | val 0.15458
  Epoch 021 - train 0.13696 | val 0.15478
  Regression -> MSE: 0.000166, MAE: 0.010634, R²: -0.0005
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13812 | val 0.16095
  Epoch 020 - train 0.14688 | val 0.16873
  Epoch 021 - train 0.15322 | val 0.16857
  Regression -> MSE: 0.000086, MAE: 0.007150, R²: 0.0048
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13805 | val 0.17439
  Epoch 020 - train 0.14773 | val 0.18142
  Epoch 021 - train 0.14955 | val 0.18140
  Regression -> MSE: 0.000214, MAE: 0.010988, R²: -0.0141
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13130 | val 0.11918
  Epoch 020 - train 0.13865 | val 0.11945
  Epoch 021 - train 0.13640 | val 0.11940
  Regression -> MSE: 0.000095, MAE: 0.008030, R²: -0.0587
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.15508 | val 0.10715
  Epoch 020 - train 0.15317 | val 0.13166
  Epoch 021 - train 0.15332 | val 0.13410
  Regression -> MSE: 0.000101, MAE: 0.008614, R²: -0.0116
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14176 | val 0.13085
  Epoch 020 - train 0.13697 | val 0.14854
  Epoch 021 - train 0.13727 | val 0.14719
  Regression -> MSE: 0.000249, MAE: 0.013198, R²: -0.0521
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13702 | val 0.14401
  Epoch 020 - train 0.12826 | val 0.14381
  Epoch 021 - train 0.13373 | val 0.14393
  Regression -> MSE: 0.000184, MAE: 0.008058, R²: -0.0874
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13588 | val 0.10727
  Epoch 020 - train 0.12841 | val 0.10809
  Epoch 021 - train 0.13926 | val 0.10809
  Regression -> MSE: 0.000243, MAE: 0.012110, R²: -0.0013
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13501 | val 0.20033
  Epoch 020 - train 0.13473 | val 0.19654
  Epoch 021 - train 0.13436 | val 0.19664
  Regression -> MSE: 0.000237, MAE: 0.010144, R²: -0.0037
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15170 | val 0.14218
  Epoch 020 - train 0.13474 | val 0.14482
  Epoch 030 - train 0.15613 | val 0.14534
  Regression -> MSE: 0.000136, MAE: 0.008222, R²: 0.0164
  Directional -> Accuracy: 0.5714, MCC: 0.1090, F1: 0.7000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14496 | val 0.16912
  Epoch 020 - train 0.14907 | val 0.17660
  Epoch 021 - train 0.15314 | val 0.17626
  Regression -> MSE: 0.000187, MAE: 0.010178, R²: -0.0189
  Directional -> Accuracy: 0.3878, MCC: -0.3170, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12908 | val 0.14062
  Epoch 020 - train 0.12758 | val 0.14122
  Epoch 021 - train 0.12559 | val 0.14163
  Regression -> MSE: 0.000273, MAE: 0.010702, R²: -0.0287
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13911 | val 0.13342
  Epoch 020 - train 0.13841 | val 0.13912
  Epoch 021 - train 0.13805 | val 0.13900
  Regression -> MSE: 0.000184, MAE: 0.010463, R²: -0.0062
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13913 | val 0.12006
  Epoch 020 - train 0.13141 | val 0.12017
  Epoch 021 - train 0.14448 | val 0.11999
  Regression -> MSE: 0.000354, MAE: 0.012572, R²: -0.0183
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13885 | val 0.08269
  Epoch 020 - train 0.13375 | val 0.08901
  Epoch 021 - train 0.13691 | val 0.08954
  Regression -> MSE: 0.000116, MAE: 0.008398, R²: -0.1017
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14385 | val 0.16911
  Epoch 020 - train 0.14216 | val 0.17580
  Epoch 021 - train 0.15006 | val 0.17594
  Regression -> MSE: 0.000220, MAE: 0.011236, R²: 0.0002
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14723 | val 0.21656
  Epoch 020 - train 0.13434 | val 0.21875
  Epoch 021 - train 0.13902 | val 0.21887
  Regression -> MSE: 0.000086, MAE: 0.007240, R²: -0.1610
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13519 | val 0.08465
  Epoch 020 - train 0.14459 | val 0.07950
  Epoch 030 - train 0.13430 | val 0.07887
  Regression -> MSE: 0.000406, MAE: 0.017251, R²: -0.3038
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14559 | val 0.16273
  Epoch 020 - train 0.15018 | val 0.16258
  Epoch 021 - train 0.14164 | val 0.16340
  Regression -> MSE: 0.000080, MAE: 0.006897, R²: -0.0204
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.15802 | val 0.17413
  Epoch 020 - train 0.13933 | val 0.20255
  Epoch 021 - train 0.14186 | val 0.20215
  Regression -> MSE: 0.000303, MAE: 0.014336, R²: -0.0064
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13846 | val 0.14946
  Epoch 020 - train 0.14573 | val 0.15620
  Epoch 021 - train 0.14301 | val 0.15646
  Regression -> MSE: 0.000104, MAE: 0.007212, R²: -0.0269
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14902 | val 0.15158
  Epoch 020 - train 0.15186 | val 0.15237
  Epoch 021 - train 0.13928 | val 0.15308
  Regression -> MSE: 0.000175, MAE: 0.009852, R²: 0.0003
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14724 | val 0.13841
  Epoch 020 - train 0.13218 | val 0.14279
  Epoch 021 - train 0.13641 | val 0.14321
  Regression -> MSE: 0.000226, MAE: 0.011807, R²: -0.0018
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13322 | val 0.14649
  Epoch 020 - train 0.13025 | val 0.14620
  Epoch 021 - train 0.12830 | val 0.14623
  Regression -> MSE: 0.000095, MAE: 0.007794, R²: -0.0107
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.15999 | val 0.22757
  Epoch 020 - train 0.16033 | val 0.25913
  Epoch 021 - train 0.17019 | val 0.25805
  Regression -> MSE: 0.000174, MAE: 0.010439, R²: -0.0415
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000


[I 2026-02-24 00:19:00,207] Trial 58 finished with value: -0.011559653232123449 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 4.244785937727355e-06, 'weight_decay': 2.170605171272578e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.18622617585318219, 'early_stopping_min_delta': 0.006430830429015218}. Best is trial 44 with value: -0.011362814469631832.

Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.18539 | val 0.26286
  Epoch 016 - train 0.19530 | val 0.26377
  Regression -> MSE: 0.000249, MAE: 0.012597, R²: -0.0046
  Directional -> Accuracy: 0.4026, MCC: -0.2020, F1: 0.5577

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.17061 | val 0.17554
  Epoch 020 - train 0.17523 | val 0.22728
  Epoch 021 - train 0.17874 | val 0.22542
  Regression -> MSE: 0.000674, MAE: 0.019193, R²: 0.0160
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.19941 | val 0.29254
  Epoch 016 - train 0.19373 | val 0.29626
  Regression -> MSE: 0.000311, MAE: 0.014456, R²: -0.0011
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15835 | val 0.31640
  Epoch 016 - train 0.16174 | val 0.32957
  Regression -> MSE: 0.000402, MAE: 0.015539, R²: -0.1514
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.19056 | val 0.17979
  Epoch 016 - train 0.20916 | val 0.18412
  Regression -> MSE: 0.000208, MAE: 0.010140, R²: -0.0212
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.18463 | val 0.34019
  Epoch 016 - train 0.17768 | val 0.34563
  Regression -> MSE: 0.000559, MAE: 0.018155, R²: -0.0075
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.21055 | val 0.24503
  Epoch 016 - train 0.19247 | val 0.24562
  Regression -> MSE: 0.000249, MAE: 0.011965, R²: -0.0125
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.19518 | val 0.26398
  Epoch 016 - train 0.18511 | val 0.26643
  Regression -> MSE: 0.000666, MAE: 0.020490, R²: -0.1145
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.16994 | val 0.21181
  Epoch 016 - train 0.17978 | val 0.21372
  Regression -> MSE: 0.000403, MAE: 0.016101, R²: -0.0501
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.20215 | val 0.37456
  Epoch 016 - train 0.20557 | val 0.38856
  Regression -> MSE: 0.000243, MAE: 0.012152, R²: -0.0070
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.18596 | val 0.26028
  Epoch 020 - train 0.17752 | val 0.25882
  Epoch 026 - train 0.17602 | val 0.25658
  Regression -> MSE: 0.000323, MAE: 0.014042, R²: -0.0394
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.20175 | val 0.21223
  Epoch 016 - train 0.20721 | val 0.21415
  Regression -> MSE: 0.000694, MAE: 0.020060, R²: -0.0254
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.19728 | val 0.18488
  Epoch 016 - train 0.19957 | val 0.20600
  Regression -> MSE: 0.000145, MAE: 0.009495, R²: -0.0467
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.16415 | val 0.24041
  Epoch 016 - train 0.17661 | val 0.24487
  Regression -> MSE: 0.000225, MAE: 0.010700, R²: -0.0003
  Directional -> Accuracy: 0.4754, MCC: -0.0531, F1: 0.2000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.18076 | val 0.36554
  Epoch 016 - train 0.17685 | val 0.36885
  Regression -> MSE: 0.000365, MAE: 0.015987, R²: -0.0069
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.19652 | val 0.21178
  Epoch 016 - train 0.19653 | val 0.21419
  Regression -> MSE: 0.000110, MAE: 0.008177, R²: -0.0157
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.19305 | val 0.31058
  Epoch 016 - train 0.18493 | val 0.31796
  Regression -> MSE: 0.000156, MAE: 0.009636, R²: 0.0001
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.19535 | val 0.18853
  Epoch 016 - train 0.19249 | val 0.18653
  Regression -> MSE: 0.000272, MAE: 0.013059, R²: 0.0012
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.17266 | val 0.23940
  Epoch 016 - train 0.16724 | val 0.23946
  Regression -> MSE: 0.000156, MAE: 0.008776, R²: -0.0411
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.18965 | val 0.25431
  Epoch 016 - train 0.18857 | val 0.25454
  Regression -> MSE: 0.000249, MAE: 0.011263, R²: -0.0983
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17737 | val 0.23715
  Epoch 016 - train 0.18681 | val 0.24634
  Regression -> MSE: 0.000144, MAE: 0.008355, R²: -0.0037
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.17652 | val 0.23271
  Epoch 016 - train 0.18799 | val 0.23512
  Regression -> MSE: 0.000166, MAE: 0.010373, R²: -0.0048
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.19841 | val 0.24275
  Epoch 016 - train 0.19367 | val 0.25931
  Regression -> MSE: 0.000085, MAE: 0.007026, R²: 0.0046
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.18000 | val 0.22429
  Epoch 016 - train 0.18056 | val 0.22519
  Regression -> MSE: 0.000212, MAE: 0.011074, R²: -0.0005
  Directional -> Accuracy: 0.5152, MCC: 0.1086, F1: 0.6364

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.17522 | val 0.15860
  Epoch 016 - train 0.17358 | val 0.15706
  Regression -> MSE: 0.000094, MAE: 0.008073, R²: -0.0207
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18662 | val 0.14842
  Epoch 016 - train 0.20248 | val 0.16983
  Regression -> MSE: 0.000109, MAE: 0.009017, R²: -0.0611
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.19379 | val 0.16848
  Epoch 020 - train 0.19975 | val 0.16679
  Epoch 027 - train 0.19223 | val 0.16664
  Regression -> MSE: 0.000234, MAE: 0.012574, R²: -0.0108
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.19029 | val 0.24567
  Epoch 016 - train 0.19548 | val 0.25263
  Regression -> MSE: 0.000179, MAE: 0.007954, R²: -0.0768
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.18537 | val 0.14931
  Epoch 016 - train 0.18702 | val 0.14934
  Regression -> MSE: 0.000237, MAE: 0.011861, R²: -0.0009
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.18215 | val 0.29165
  Epoch 016 - train 0.19604 | val 0.29456
  Regression -> MSE: 0.000234, MAE: 0.010137, R²: -0.0174
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.19480 | val 0.21508
  Epoch 020 - train 0.19341 | val 0.22079
  Epoch 026 - train 0.18669 | val 0.22284
  Regression -> MSE: 0.000141, MAE: 0.008239, R²: -0.0461
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.19483 | val 0.22356
  Epoch 016 - train 0.18439 | val 0.22310
  Regression -> MSE: 0.000192, MAE: 0.010413, R²: -0.0215
  Directional -> Accuracy: 0.5000, MCC: 0.0939, F1: 0.2424

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.16079 | val 0.20103
  Epoch 016 - train 0.15853 | val 0.20154
  Regression -> MSE: 0.000268, MAE: 0.010572, R²: -0.0225
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.17931 | val 0.14932
  Epoch 016 - train 0.16827 | val 0.15201
  Regression -> MSE: 0.000167, MAE: 0.010362, R²: -0.0041
  Directional -> Accuracy: 0.5789, MCC: 0.1615, F1: 0.6190

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.18046 | val 0.20654
  Epoch 016 - train 0.17537 | val 0.23635
  Regression -> MSE: 0.000186, MAE: 0.010567, R²: -0.0359
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.17840 | val 0.16722
  Epoch 016 - train 0.17856 | val 0.16724
  Regression -> MSE: 0.000347, MAE: 0.012241, R²: -0.0136
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.20983 | val 0.11411
  Epoch 016 - train 0.20289 | val 0.11758
  Regression -> MSE: 0.000128, MAE: 0.008527, R²: -0.2193
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.18767 | val 0.23847
  Epoch 016 - train 0.19161 | val 0.23933
  Regression -> MSE: 0.000219, MAE: 0.011260, R²: -0.0016
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.20827 | val 0.33078
  Epoch 016 - train 0.20245 | val 0.35558
  Regression -> MSE: 0.000081, MAE: 0.007031, R²: -0.0481
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.18834 | val 0.14302
  Epoch 016 - train 0.20713 | val 0.14907
  Regression -> MSE: 0.000324, MAE: 0.014694, R²: -0.0521
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.18395 | val 0.10721
  Epoch 016 - train 0.20352 | val 0.10751
  Regression -> MSE: 0.000253, MAE: 0.011443, R²: -0.0396
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.18723 | val 0.21008
  Epoch 020 - train 0.18907 | val 0.20996
  Epoch 025 - train 0.18386 | val 0.20958
  Regression -> MSE: 0.000097, MAE: 0.007887, R²: -0.2052
  Directional -> Accuracy: 0.4800, MCC: -0.1178, F1: 0.6486

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.20270 | val 0.23890
  Epoch 016 - train 0.20417 | val 0.25751
  Regression -> MSE: 0.000311, MAE: 0.014502, R²: -0.0128
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.18468 | val 0.20082
  Epoch 020 - train 0.18490 | val 0.19411
  Epoch 030 - train 0.18562 | val 0.19395
  Regression -> MSE: 0.000099, MAE: 0.007611, R²: -0.0055
  Directional -> Accuracy: 0.3864, MCC: -0.2503, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.20055 | val 0.21158
  Epoch 016 - train 0.21072 | val 0.20980
  Regression -> MSE: 0.000172, MAE: 0.009643, R²: 0.0013
  Directional -> Accuracy: 0.4286, MCC: -0.0338, F1: 0.5000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.16500 | val 0.21616
  Epoch 016 - train 0.17884 | val 0.21956
  Regression -> MSE: 0.000226, MAE: 0.011783, R²: -0.0156
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.20014 | val 0.20272
  Epoch 016 - train 0.19929 | val 0.20713
  Regression -> MSE: 0.000094, MAE: 0.007674, R²: -0.0185
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.19062 | val 0.29397
  Epoch 016 - train 0.18693 | val 0.30781
  Regression -> MSE: 0.000164, MAE: 0.010263, R²: -0.0022
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.18238 | val 0.24925
  Epoch 016 - train 0.19440 | val 0.26173
  Regression -> MSE: 0.000126, MAE: 0.009042, R²: -0.0849
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.20168 | val 0.26384

[I 2026-02-24 00:20:22,632] Trial 59 finished with value: -0.011492500691125918 and parameters: {'feature_set': 'sentinment', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 3.047462924864393e-06, 'weight_decay': 2.979344967854647e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.28208272961877834, 'early_stopping_min_delta': 0.003862220902060142}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 016 - train 0.19998 | val 0.26953
  Regression -> MSE: 0.000237, MAE: 0.012446, R²: -0.0012
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09816 | val 0.11985
  Epoch 020 - train 0.09470 | val 0.11879
  Epoch 021 - train 0.09711 | val 0.11879
  Regression -> MSE: 0.000260, MAE: 0.012998, R²: -0.0499
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10671 | val 0.10688
  Epoch 020 - train 0.10213 | val 0.09912
  Epoch 021 - train 0.10470 | val 0.09993
  Regression -> MSE: 0.000728, MAE: 0.020032, R²: -0.0629
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09409 | val 0.14589
  Epoch 020 - train 0.09421 | val 0.14383
  Epoch 021 - train 0.09415 | val 0.14407
  Regression -> MSE: 0.000319, MAE: 0.014485, R²: -0.0289
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08550 | val 0.18719
  Epoch 020 - train 0.08296 | val 0.17833
  Epoch 021 - train 0.08621 | val 0.17985
  Regression -> MSE: 0.000363, MAE: 0.014794, R²: -0.0384
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09378 | val 0.10715
  Epoch 020 - train 0.09580 | val 0.10789
  Epoch 021 - train 0.09668 | val 0.10753
  Regression -> MSE: 0.000205, MAE: 0.010265, R²: -0.0045
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09641 | val 0.19234
  Epoch 020 - train 0.09375 | val 0.20946
  Epoch 021 - train 0.09643 | val 0.20750
  Regression -> MSE: 0.000575, MAE: 0.018496, R²: -0.0350
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09840 | val 0.11259
  Epoch 020 - train 0.09550 | val 0.11462
  Epoch 021 - train 0.09753 | val 0.11474
  Regression -> MSE: 0.000246, MAE: 0.012129, R²: -0.0031
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10721 | val 0.11010
  Epoch 020 - train 0.09129 | val 0.10545
  Epoch 030 - train 0.09305 | val 0.10718
  Regression -> MSE: 0.000598, MAE: 0.019022, R²: -0.0009
  Directional -> Accuracy: 0.5455, MCC: -0.1816, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09130 | val 0.11117
  Epoch 020 - train 0.09048 | val 0.11159
  Epoch 021 - train 0.08757 | val 0.11115
  Regression -> MSE: 0.000405, MAE: 0.016148, R²: -0.0556
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09534 | val 0.12145
  Epoch 020 - train 0.09454 | val 0.12191
  Epoch 021 - train 0.09464 | val 0.12224
  Regression -> MSE: 0.000242, MAE: 0.011844, R²: -0.0017
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08795 | val 0.14083
  Epoch 020 - train 0.08827 | val 0.14318
  Epoch 021 - train 0.09016 | val 0.14363
  Regression -> MSE: 0.000311, MAE: 0.013631, R²: -0.0010
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09923 | val 0.10854
  Epoch 020 - train 0.09339 | val 0.11043
  Epoch 021 - train 0.09641 | val 0.11054
  Regression -> MSE: 0.000680, MAE: 0.019586, R²: -0.0034
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09611 | val 0.12448
  Epoch 020 - train 0.09477 | val 0.12588
  Epoch 021 - train 0.10079 | val 0.12429
  Regression -> MSE: 0.000141, MAE: 0.009322, R²: -0.0179
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08778 | val 0.12120
  Epoch 020 - train 0.08730 | val 0.12124
  Epoch 021 - train 0.09072 | val 0.12098
  Regression -> MSE: 0.000228, MAE: 0.010778, R²: -0.0119
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09464 | val 0.19556
  Epoch 020 - train 0.09928 | val 0.19634
  Epoch 021 - train 0.10048 | val 0.19512
  Regression -> MSE: 0.000362, MAE: 0.016160, R²: -0.0002
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09795 | val 0.09693
  Epoch 020 - train 0.09637 | val 0.09612
  Epoch 021 - train 0.09375 | val 0.09596
  Regression -> MSE: 0.000108, MAE: 0.007923, R²: -0.0052
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10241 | val 0.14639
  Epoch 020 - train 0.09950 | val 0.15292
  Epoch 021 - train 0.09608 | val 0.15247
  Regression -> MSE: 0.000164, MAE: 0.010257, R²: -0.0502
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09990 | val 0.09478
  Epoch 020 - train 0.09583 | val 0.09427
  Epoch 021 - train 0.09960 | val 0.09456
  Regression -> MSE: 0.000274, MAE: 0.013169, R²: -0.0080
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08848 | val 0.12319
  Epoch 020 - train 0.09101 | val 0.12236
  Epoch 021 - train 0.08933 | val 0.12199
  Regression -> MSE: 0.000160, MAE: 0.008862, R²: -0.0673
  Directional -> Accuracy: 0.5538, MCC: 0.1818, F1: 0.5085

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10187 | val 0.14602
  Epoch 020 - train 0.09737 | val 0.14745
  Epoch 021 - train 0.10007 | val 0.14696
  Regression -> MSE: 0.000229, MAE: 0.010831, R²: -0.0112
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08811 | val 0.11532
  Epoch 020 - train 0.09067 | val 0.11536
  Epoch 021 - train 0.09455 | val 0.11566
  Regression -> MSE: 0.000145, MAE: 0.008462, R²: -0.0132
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10106 | val 0.10611
  Epoch 020 - train 0.09620 | val 0.10770
  Epoch 021 - train 0.09299 | val 0.10755
  Regression -> MSE: 0.000170, MAE: 0.010242, R²: -0.0289
  Directional -> Accuracy: 0.5303, MCC: 0.0928, F1: 0.6593

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10369 | val 0.11786
  Epoch 020 - train 0.10070 | val 0.11678
  Epoch 021 - train 0.09927 | val 0.11577
  Regression -> MSE: 0.000093, MAE: 0.007438, R²: -0.0926
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10244 | val 0.11693
  Epoch 020 - train 0.10016 | val 0.11779
  Epoch 021 - train 0.09948 | val 0.11733
  Regression -> MSE: 0.000215, MAE: 0.011017, R²: -0.0170
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09148 | val 0.07902
  Epoch 020 - train 0.08479 | val 0.07875
  Epoch 021 - train 0.08622 | val 0.07874
  Regression -> MSE: 0.000097, MAE: 0.008142, R²: -0.0485
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09716 | val 0.07510
  Epoch 020 - train 0.09756 | val 0.07546
  Epoch 021 - train 0.08990 | val 0.07631
  Regression -> MSE: 0.000109, MAE: 0.009011, R²: -0.0606
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09947 | val 0.09911
  Epoch 020 - train 0.10060 | val 0.10037
  Epoch 021 - train 0.09194 | val 0.10047
  Regression -> MSE: 0.000237, MAE: 0.012749, R²: -0.0243
  Directional -> Accuracy: 0.4186, MCC: -0.0908, F1: 0.2857

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10164 | val 0.12332
  Epoch 020 - train 0.09633 | val 0.12404
  Epoch 021 - train 0.09999 | val 0.12368
  Regression -> MSE: 0.000169, MAE: 0.007838, R²: -0.0131
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10477 | val 0.07653
  Epoch 020 - train 0.09419 | val 0.07632
  Epoch 021 - train 0.10093 | val 0.07657
  Regression -> MSE: 0.000237, MAE: 0.011881, R²: -0.0037
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09904 | val 0.14788
  Epoch 020 - train 0.09703 | val 0.14826
  Epoch 021 - train 0.09911 | val 0.14828
  Regression -> MSE: 0.000234, MAE: 0.010080, R²: -0.0133
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10167 | val 0.10506
  Epoch 020 - train 0.09296 | val 0.10602
  Epoch 021 - train 0.09523 | val 0.10678
  Regression -> MSE: 0.000135, MAE: 0.008185, R²: -0.0002
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09737 | val 0.11641
  Epoch 020 - train 0.09073 | val 0.11730
  Epoch 021 - train 0.09771 | val 0.11734
  Regression -> MSE: 0.000190, MAE: 0.010400, R²: -0.0113
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09122 | val 0.11229
  Epoch 020 - train 0.08841 | val 0.11063
  Epoch 021 - train 0.08580 | val 0.11028
  Regression -> MSE: 0.000264, MAE: 0.010526, R²: -0.0089
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09482 | val 0.08006
  Epoch 020 - train 0.09257 | val 0.08490
  Epoch 021 - train 0.08817 | val 0.08487
  Regression -> MSE: 0.000167, MAE: 0.010357, R²: -0.0002
  Directional -> Accuracy: 0.5263, MCC: 0.0778, F1: 0.6538

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09341 | val 0.12456
  Epoch 020 - train 0.09424 | val 0.12314
  Epoch 021 - train 0.09356 | val 0.12275
  Regression -> MSE: 0.000186, MAE: 0.010585, R²: -0.0335
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09236 | val 0.08714
  Epoch 020 - train 0.09467 | val 0.08644
  Epoch 021 - train 0.09286 | val 0.08663
  Regression -> MSE: 0.000347, MAE: 0.011705, R²: -0.0127
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10497 | val 0.06785
  Epoch 020 - train 0.10026 | val 0.06954
  Epoch 021 - train 0.09451 | val 0.06910
  Regression -> MSE: 0.000120, MAE: 0.008370, R²: -0.1440
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09524 | val 0.14328
  Epoch 020 - train 0.09580 | val 0.14008
  Epoch 021 - train 0.09513 | val 0.14004
  Regression -> MSE: 0.000220, MAE: 0.011390, R²: -0.0086
  Directional -> Accuracy: 0.4386, MCC: -0.2010, F1: 0.6098

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09638 | val 0.19588
  Epoch 020 - train 0.09825 | val 0.19421
  Epoch 021 - train 0.09536 | val 0.19483
  Regression -> MSE: 0.000079, MAE: 0.006928, R²: -0.0201
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09152 | val 0.07245
  Epoch 020 - train 0.09836 | val 0.07250
  Epoch 021 - train 0.10083 | val 0.07259
  Regression -> MSE: 0.000309, MAE: 0.013833, R²: -0.0029
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11185 | val 0.06523
  Epoch 020 - train 0.10668 | val 0.06746
  Epoch 021 - train 0.10094 | val 0.06850
  Regression -> MSE: 0.000262, MAE: 0.011508, R²: -0.0753
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10080 | val 0.11805
  Epoch 020 - train 0.09566 | val 0.11824
  Epoch 021 - train 0.09222 | val 0.11847
  Regression -> MSE: 0.000084, MAE: 0.007078, R²: -0.0399
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.09739 | val 0.11759
  Epoch 020 - train 0.09526 | val 0.11912
  Epoch 021 - train 0.09291 | val 0.11890
  Regression -> MSE: 0.000306, MAE: 0.014491, R²: 0.0014
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09827 | val 0.11221
  Epoch 020 - train 0.10351 | val 0.11767
  Epoch 021 - train 0.09854 | val 0.11720
  Regression -> MSE: 0.000104, MAE: 0.007137, R²: -0.0609
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10234 | val 0.11112
  Epoch 020 - train 0.09962 | val 0.10935
  Epoch 021 - train 0.09750 | val 0.10985
  Regression -> MSE: 0.000175, MAE: 0.010121, R²: -0.0160
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 00:23:10,922] Trial 60 finished with value: -0.011426239503080209 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 1.7840741449066517e-05, 'weight_decay': 6.6515505469954475e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.13376882298892415, 'early_stopping_min_delta': 0.007060364727628449}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.09232 | val 0.12658
  Epoch 021 - train 0.09767 | val 0.12672
  Regression -> MSE: 0.000246, MAE: 0.012388, R²: -0.0383
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11690 | val 0.14785
  Epoch 020 - train 0.10804 | val 0.14616
  Epoch 021 - train 0.12228 | val 0.14693
  Regression -> MSE: 0.000247, MAE: 0.012502, R²: 0.0004
  Directional -> Accuracy: 0.5455, MCC: 0.0214, F1: 0.1026

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11226 | val 0.09805
  Epoch 020 - train 0.10938 | val 0.09877
  Epoch 021 - train 0.10462 | val 0.09898
  Regression -> MSE: 0.000704, MAE: 0.019684, R²: -0.0289
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11966 | val 0.17858
  Epoch 020 - train 0.11870 | val 0.17721
  Epoch 021 - train 0.12165 | val 0.17751
  Regression -> MSE: 0.000311, MAE: 0.014403, R²: -0.0036
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09947 | val 0.09037
  Epoch 020 - train 0.10003 | val 0.08950
  Epoch 021 - train 0.10125 | val 0.09037
  Regression -> MSE: 0.000384, MAE: 0.015177, R²: -0.0992
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11583 | val 0.10638
  Epoch 020 - train 0.11707 | val 0.10586
  Epoch 021 - train 0.10856 | val 0.10608
  Regression -> MSE: 0.000206, MAE: 0.010361, R²: -0.0127
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10877 | val 0.19948
  Epoch 020 - train 0.10684 | val 0.19909
  Epoch 021 - train 0.10375 | val 0.20001
  Regression -> MSE: 0.000586, MAE: 0.018692, R²: -0.0559
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10846 | val 0.13593
  Epoch 020 - train 0.11154 | val 0.13480
  Epoch 021 - train 0.11299 | val 0.13436
  Regression -> MSE: 0.000249, MAE: 0.011908, R²: -0.0130
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10562 | val 0.16173
  Epoch 020 - train 0.10599 | val 0.17855
  Epoch 021 - train 0.10502 | val 0.17747
  Regression -> MSE: 0.000636, MAE: 0.020017, R²: -0.0641
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10987 | val 0.14351
  Epoch 020 - train 0.10363 | val 0.14279
  Epoch 021 - train 0.11593 | val 0.14288
  Regression -> MSE: 0.000384, MAE: 0.016196, R²: 0.0002
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11679 | val 0.14179
  Epoch 020 - train 0.11205 | val 0.14176
  Epoch 021 - train 0.11760 | val 0.14367
  Regression -> MSE: 0.000243, MAE: 0.011709, R²: -0.0054
  Directional -> Accuracy: 0.6000, MCC: 0.1510, F1: 0.4167

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11180 | val 0.18162
  Epoch 020 - train 0.09964 | val 0.17952
  Epoch 021 - train 0.10583 | val 0.17876
  Regression -> MSE: 0.000314, MAE: 0.013623, R²: -0.0103
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11964 | val 0.13708
  Epoch 020 - train 0.10969 | val 0.13653
  Epoch 021 - train 0.11709 | val 0.13670
  Regression -> MSE: 0.000676, MAE: 0.019476, R²: 0.0022
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12211 | val 0.13639
  Epoch 020 - train 0.11430 | val 0.13815
  Epoch 021 - train 0.11202 | val 0.13825
  Regression -> MSE: 0.000144, MAE: 0.009457, R²: -0.0403
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10973 | val 0.13565
  Epoch 020 - train 0.10847 | val 0.13572
  Epoch 021 - train 0.11111 | val 0.13549
  Regression -> MSE: 0.000227, MAE: 0.010746, R²: -0.0082
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11562 | val 0.21928
  Epoch 020 - train 0.11438 | val 0.21862
  Epoch 021 - train 0.11626 | val 0.21896
  Regression -> MSE: 0.000364, MAE: 0.016242, R²: -0.0037
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11492 | val 0.11973
  Epoch 020 - train 0.12324 | val 0.11705
  Epoch 021 - train 0.11541 | val 0.11729
  Regression -> MSE: 0.000111, MAE: 0.008237, R²: -0.0265
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11136 | val 0.18214
  Epoch 020 - train 0.10589 | val 0.18288
  Epoch 021 - train 0.11204 | val 0.18170
  Regression -> MSE: 0.000155, MAE: 0.009510, R²: 0.0035
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12264 | val 0.11379
  Epoch 020 - train 0.11884 | val 0.11070
  Epoch 021 - train 0.11941 | val 0.11101
  Regression -> MSE: 0.000272, MAE: 0.012887, R²: -0.0011
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11000 | val 0.14066
  Epoch 020 - train 0.11580 | val 0.13790
  Epoch 021 - train 0.10472 | val 0.13879
  Regression -> MSE: 0.000152, MAE: 0.008751, R²: -0.0184
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11871 | val 0.19767
  Epoch 020 - train 0.11564 | val 0.18911
  Epoch 021 - train 0.11653 | val 0.18630
  Regression -> MSE: 0.000235, MAE: 0.011013, R²: -0.0397
  Directional -> Accuracy: 0.4133, MCC: -0.1603, F1: 0.3889

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11460 | val 0.13226
  Epoch 020 - train 0.10559 | val 0.13207
  Epoch 021 - train 0.11235 | val 0.13190
  Regression -> MSE: 0.000150, MAE: 0.008684, R²: -0.0462
  Directional -> Accuracy: 0.6042, MCC: -0.1130, F1: 0.7532

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10408 | val 0.12545
  Epoch 020 - train 0.11135 | val 0.12381
  Epoch 021 - train 0.11252 | val 0.12325
  Regression -> MSE: 0.000177, MAE: 0.010313, R²: -0.0733
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11426 | val 0.12619
  Epoch 020 - train 0.11756 | val 0.12533
  Epoch 021 - train 0.11622 | val 0.12544
  Regression -> MSE: 0.000088, MAE: 0.007217, R²: -0.0370
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10180 | val 0.15022
  Epoch 020 - train 0.11035 | val 0.14391
  Epoch 021 - train 0.10726 | val 0.14616
  Regression -> MSE: 0.000213, MAE: 0.011072, R²: -0.0042
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10734 | val 0.11546
  Epoch 020 - train 0.11127 | val 0.11214
  Epoch 021 - train 0.10785 | val 0.11116
  Regression -> MSE: 0.000094, MAE: 0.008092, R²: -0.0158
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11450 | val 0.09151
  Epoch 020 - train 0.11567 | val 0.09023
  Epoch 021 - train 0.11531 | val 0.09028
  Regression -> MSE: 0.000109, MAE: 0.008977, R²: -0.0530
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11393 | val 0.09594
  Epoch 020 - train 0.11488 | val 0.09575
  Epoch 021 - train 0.11671 | val 0.09576
  Regression -> MSE: 0.000235, MAE: 0.012656, R²: -0.0139
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11153 | val 0.12770
  Epoch 020 - train 0.10842 | val 0.12840
  Epoch 021 - train 0.11068 | val 0.12828
  Regression -> MSE: 0.000185, MAE: 0.008072, R²: -0.1142
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12814 | val 0.09726
  Epoch 020 - train 0.12671 | val 0.09829
  Epoch 021 - train 0.11849 | val 0.09801
  Regression -> MSE: 0.000237, MAE: 0.011901, R²: -0.0038
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11662 | val 0.16502
  Epoch 020 - train 0.11081 | val 0.16608
  Epoch 021 - train 0.11294 | val 0.16610
  Regression -> MSE: 0.000231, MAE: 0.009957, R²: -0.0041
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11535 | val 0.15304
  Epoch 020 - train 0.13080 | val 0.15502
  Epoch 021 - train 0.12030 | val 0.15569
  Regression -> MSE: 0.000135, MAE: 0.008195, R²: 0.0012
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11406 | val 0.13165
  Epoch 020 - train 0.10449 | val 0.13180
  Epoch 021 - train 0.11250 | val 0.13196
  Regression -> MSE: 0.000193, MAE: 0.010455, R²: -0.0269
  Directional -> Accuracy: 0.5600, MCC: 0.2235, F1: 0.3889

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10442 | val 0.11559
  Epoch 020 - train 0.10233 | val 0.11386
  Epoch 021 - train 0.09896 | val 0.11314
  Regression -> MSE: 0.000268, MAE: 0.010575, R²: -0.0230
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11456 | val 0.08836
  Epoch 020 - train 0.10590 | val 0.09119
  Epoch 021 - train 0.09942 | val 0.09201
  Regression -> MSE: 0.000167, MAE: 0.010358, R²: -0.0046
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12156 | val 0.11580
  Epoch 020 - train 0.10853 | val 0.11736
  Epoch 021 - train 0.11606 | val 0.11770
  Regression -> MSE: 0.000183, MAE: 0.010409, R²: -0.0145
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11026 | val 0.09462
  Epoch 020 - train 0.11506 | val 0.09328
  Epoch 021 - train 0.10441 | val 0.09347
  Regression -> MSE: 0.000344, MAE: 0.011692, R²: -0.0038
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12733 | val 0.06881
  Epoch 020 - train 0.11819 | val 0.06917
  Epoch 021 - train 0.11897 | val 0.06918
  Regression -> MSE: 0.000114, MAE: 0.008346, R²: -0.0846
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12114 | val 0.14258
  Epoch 020 - train 0.11126 | val 0.14389
  Epoch 021 - train 0.11933 | val 0.14554
  Regression -> MSE: 0.000219, MAE: 0.011289, R²: -0.0022
  Directional -> Accuracy: 0.6491, MCC: 0.3109, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11568 | val 0.17318
  Epoch 020 - train 0.10764 | val 0.17236
  Epoch 021 - train 0.11852 | val 0.17258
  Regression -> MSE: 0.000084, MAE: 0.007145, R²: -0.0812
  Directional -> Accuracy: 0.5106, MCC: 0.0584, F1: 0.5306

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11551 | val 0.07700
  Epoch 020 - train 0.11005 | val 0.07646
  Epoch 021 - train 0.10768 | val 0.07621
  Regression -> MSE: 0.000318, MAE: 0.014364, R²: -0.0322
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13082 | val 0.06705
  Epoch 020 - train 0.12506 | val 0.07387
  Epoch 021 - train 0.11654 | val 0.07430
  Regression -> MSE: 0.000251, MAE: 0.011495, R²: -0.0285
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11518 | val 0.12200
  Epoch 020 - train 0.11079 | val 0.12267
  Epoch 021 - train 0.10319 | val 0.12242
  Regression -> MSE: 0.000081, MAE: 0.007078, R²: -0.0011
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10773 | val 0.13498
  Epoch 020 - train 0.10750 | val 0.13405
  Epoch 021 - train 0.10908 | val 0.13280
  Regression -> MSE: 0.000307, MAE: 0.014509, R²: -0.0018
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12418 | val 0.12907
  Epoch 020 - train 0.11110 | val 0.13476
  Epoch 021 - train 0.12030 | val 0.13428
  Regression -> MSE: 0.000101, MAE: 0.007107, R²: -0.0317
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12407 | val 0.11947
  Epoch 020 - train 0.11118 | val 0.11926
  Epoch 021 - train 0.11907 | val 0.11932
  Regression -> MSE: 0.000171, MAE: 0.009672, R²: 0.0029
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 00:25:48,367] Trial 61 finished with value: -0.011425947415052045 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 1.5452490037233733e-05, 'weight_decay': 2.0621753628965413e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.15150293615229152, 'early_stopping_min_delta': 0.007061830711004267}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.11644 | val 0.14979
  Epoch 021 - train 0.11228 | val 0.14957
  Regression -> MSE: 0.000242, MAE: 0.012357, R²: -0.0206
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07919 | val 0.09230
  Epoch 020 - train 0.07844 | val 0.09169
  Epoch 021 - train 0.07685 | val 0.09163
  Regression -> MSE: 0.000249, MAE: 0.012564, R²: -0.0053
  Directional -> Accuracy: 0.5065, MCC: 0.0190, F1: 0.5000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08072 | val 0.07151
  Epoch 020 - train 0.07359 | val 0.07095
  Epoch 021 - train 0.07343 | val 0.07085
  Regression -> MSE: 0.000691, MAE: 0.019433, R²: -0.0098
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.08372 | val 0.12403
  Epoch 020 - train 0.08239 | val 0.12253
  Epoch 021 - train 0.08206 | val 0.12213
  Regression -> MSE: 0.000317, MAE: 0.014500, R²: -0.0206
  Directional -> Accuracy: 0.4468, MCC: -0.1039, F1: 0.0714

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06955 | val 0.06522
  Epoch 020 - train 0.07047 | val 0.06364
  Epoch 021 - train 0.06798 | val 0.06358
  Regression -> MSE: 0.000354, MAE: 0.014681, R²: -0.0145
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.08100 | val 0.07518
  Epoch 020 - train 0.08125 | val 0.07361
  Epoch 021 - train 0.08448 | val 0.07392
  Regression -> MSE: 0.000206, MAE: 0.010103, R²: -0.0115
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07515 | val 0.13857
  Epoch 020 - train 0.07745 | val 0.13600
  Epoch 021 - train 0.08048 | val 0.13691
  Regression -> MSE: 0.000593, MAE: 0.018828, R²: -0.0676
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.08372 | val 0.09421
  Epoch 020 - train 0.08573 | val 0.09146
  Epoch 021 - train 0.08139 | val 0.09094
  Regression -> MSE: 0.000247, MAE: 0.012237, R²: -0.0061
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08448 | val 0.09536
  Epoch 020 - train 0.08313 | val 0.09733
  Epoch 021 - train 0.08419 | val 0.09694
  Regression -> MSE: 0.000626, MAE: 0.019829, R²: -0.0476
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07992 | val 0.08315
  Epoch 020 - train 0.07532 | val 0.08314
  Epoch 021 - train 0.07228 | val 0.08324
  Regression -> MSE: 0.000394, MAE: 0.015947, R²: -0.0269
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07984 | val 0.09124
  Epoch 020 - train 0.07783 | val 0.09055
  Epoch 021 - train 0.07730 | val 0.09066
  Regression -> MSE: 0.000243, MAE: 0.012084, R²: -0.0051
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.07565 | val 0.11474
  Epoch 020 - train 0.07311 | val 0.11541
  Epoch 021 - train 0.07385 | val 0.11507
  Regression -> MSE: 0.000311, MAE: 0.013717, R²: 0.0000
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08396 | val 0.08465
  Epoch 020 - train 0.08289 | val 0.08567
  Epoch 021 - train 0.08129 | val 0.08568
  Regression -> MSE: 0.000677, MAE: 0.019470, R²: 0.0003
  Directional -> Accuracy: 0.5172, MCC: 0.0394, F1: 0.3636

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07684 | val 0.07699
  Epoch 020 - train 0.07751 | val 0.07790
  Epoch 021 - train 0.07625 | val 0.07817
  Regression -> MSE: 0.000138, MAE: 0.009122, R²: 0.0001
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.07185 | val 0.09695
  Epoch 020 - train 0.07572 | val 0.09639
  Epoch 021 - train 0.07281 | val 0.09684
  Regression -> MSE: 0.000228, MAE: 0.010791, R²: -0.0140
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07573 | val 0.14853
  Epoch 020 - train 0.08060 | val 0.14849
  Epoch 021 - train 0.07944 | val 0.14854
  Regression -> MSE: 0.000362, MAE: 0.016098, R²: -0.0000
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.08087 | val 0.07921
  Epoch 020 - train 0.08130 | val 0.08006
  Epoch 021 - train 0.07878 | val 0.07997
  Regression -> MSE: 0.000111, MAE: 0.007968, R²: -0.0316
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08358 | val 0.14254
  Epoch 020 - train 0.07746 | val 0.13952
  Epoch 021 - train 0.08036 | val 0.13991
  Regression -> MSE: 0.000157, MAE: 0.009548, R²: -0.0088
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08022 | val 0.08456
  Epoch 020 - train 0.08359 | val 0.08343
  Epoch 021 - train 0.08278 | val 0.08519
  Regression -> MSE: 0.000279, MAE: 0.012898, R²: -0.0267
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08093 | val 0.10180
  Epoch 020 - train 0.07551 | val 0.10054
  Epoch 021 - train 0.07496 | val 0.10067
  Regression -> MSE: 0.000157, MAE: 0.008819, R²: -0.0477
  Directional -> Accuracy: 0.5385, MCC: 0.0702, F1: 0.5833

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.08634 | val 0.10694
  Epoch 020 - train 0.08007 | val 0.10516
  Epoch 021 - train 0.08393 | val 0.10529
  Regression -> MSE: 0.000235, MAE: 0.011008, R²: -0.0368
  Directional -> Accuracy: 0.4400, MCC: -0.1145, F1: 0.4474

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07866 | val 0.08850
  Epoch 020 - train 0.07909 | val 0.08939
  Epoch 021 - train 0.08283 | val 0.08970
  Regression -> MSE: 0.000149, MAE: 0.008631, R²: -0.0361
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.08078 | val 0.08648
  Epoch 020 - train 0.07850 | val 0.08531
  Epoch 021 - train 0.07528 | val 0.08516
  Regression -> MSE: 0.000165, MAE: 0.010497, R²: -0.0008
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08579 | val 0.09051
  Epoch 020 - train 0.08496 | val 0.09028
  Epoch 021 - train 0.08299 | val 0.09016
  Regression -> MSE: 0.000086, MAE: 0.007100, R²: -0.0121
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.08027 | val 0.08902
  Epoch 020 - train 0.07942 | val 0.09027
  Epoch 021 - train 0.07772 | val 0.09005
  Regression -> MSE: 0.000214, MAE: 0.011419, R²: -0.0115
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07598 | val 0.06949
  Epoch 020 - train 0.07545 | val 0.06954
  Epoch 021 - train 0.06951 | val 0.06939
  Regression -> MSE: 0.000103, MAE: 0.008256, R²: -0.1194
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07894 | val 0.06684
  Epoch 020 - train 0.08102 | val 0.07022
  Epoch 021 - train 0.07837 | val 0.07003
  Regression -> MSE: 0.000105, MAE: 0.008855, R²: -0.0205
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.08387 | val 0.12026
  Epoch 020 - train 0.08301 | val 0.12663
  Epoch 021 - train 0.08051 | val 0.12471
  Regression -> MSE: 0.000240, MAE: 0.012841, R²: -0.0379
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07662 | val 0.08438
  Epoch 020 - train 0.07633 | val 0.08499
  Epoch 021 - train 0.07842 | val 0.08500
  Regression -> MSE: 0.000182, MAE: 0.007999, R²: -0.0916
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08927 | val 0.07269
  Epoch 020 - train 0.08894 | val 0.07478
  Epoch 021 - train 0.07425 | val 0.07422
  Regression -> MSE: 0.000242, MAE: 0.012100, R²: -0.0214
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07616 | val 0.11023
  Epoch 020 - train 0.07837 | val 0.10991
  Epoch 021 - train 0.07714 | val 0.10990
  Regression -> MSE: 0.000231, MAE: 0.009862, R²: -0.0015
  Directional -> Accuracy: 0.4651, MCC: -0.0716, F1: 0.4390

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.08805 | val 0.09030
  Epoch 020 - train 0.08011 | val 0.09079
  Epoch 021 - train 0.08297 | val 0.09074
  Regression -> MSE: 0.000137, MAE: 0.008279, R²: -0.0136
  Directional -> Accuracy: 0.5814, MCC: 0.1934, F1: 0.5263

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07844 | val 0.09164
  Epoch 020 - train 0.07867 | val 0.09193
  Epoch 021 - train 0.08071 | val 0.09170
  Regression -> MSE: 0.000197, MAE: 0.010619, R²: -0.0461
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07955 | val 0.10132
  Epoch 020 - train 0.07382 | val 0.09795
  Epoch 021 - train 0.07143 | val 0.09919
  Regression -> MSE: 0.000261, MAE: 0.010688, R²: 0.0044
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07486 | val 0.05987
  Epoch 020 - train 0.07718 | val 0.06877
  Epoch 021 - train 0.08030 | val 0.06996
  Regression -> MSE: 0.000168, MAE: 0.010356, R²: -0.0076
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.07681 | val 0.07878
  Epoch 020 - train 0.07541 | val 0.07921
  Epoch 021 - train 0.07174 | val 0.07939
  Regression -> MSE: 0.000180, MAE: 0.010289, R²: -0.0003
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07990 | val 0.07209
  Epoch 020 - train 0.08084 | val 0.07211
  Epoch 021 - train 0.08089 | val 0.07197
  Regression -> MSE: 0.000344, MAE: 0.012055, R²: -0.0048
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08595 | val 0.04976
  Epoch 020 - train 0.08362 | val 0.05053
  Epoch 021 - train 0.08141 | val 0.05075
  Regression -> MSE: 0.000118, MAE: 0.008353, R²: -0.1253
  Directional -> Accuracy: 0.4651, MCC: -0.0977, F1: 0.0800

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.08419 | val 0.10270
  Epoch 020 - train 0.08113 | val 0.10255
  Epoch 021 - train 0.08007 | val 0.10228
  Regression -> MSE: 0.000224, MAE: 0.011422, R²: -0.0255
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.08525 | val 0.14023
  Epoch 020 - train 0.08394 | val 0.13539
  Epoch 021 - train 0.08345 | val 0.13609
  Regression -> MSE: 0.000081, MAE: 0.007005, R²: -0.0396
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08120 | val 0.07245
  Epoch 020 - train 0.08078 | val 0.07319
  Epoch 021 - train 0.07961 | val 0.07303
  Regression -> MSE: 0.000354, MAE: 0.015780, R²: -0.1508
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.08485 | val 0.04582
  Epoch 020 - train 0.08607 | val 0.05609
  Epoch 021 - train 0.07873 | val 0.05717
  Regression -> MSE: 0.000253, MAE: 0.011496, R²: -0.0376
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08376 | val 0.08454
  Epoch 020 - train 0.07449 | val 0.08562
  Epoch 021 - train 0.08388 | val 0.08576
  Regression -> MSE: 0.000085, MAE: 0.007081, R²: -0.0532
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.08368 | val 0.08993
  Epoch 020 - train 0.07702 | val 0.08933
  Epoch 021 - train 0.07851 | val 0.08910
  Regression -> MSE: 0.000313, MAE: 0.014513, R²: -0.0201
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08781 | val 0.07213
  Epoch 020 - train 0.08614 | val 0.06998
  Epoch 030 - train 0.08732 | val 0.06981
  Regression -> MSE: 0.000100, MAE: 0.007258, R²: -0.0219
  Directional -> Accuracy: 0.5227, MCC: 0.0586, F1: 0.5333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08533 | val 0.09114
  Epoch 020 - train 0.08318 | val 0.09267
  Epoch 021 - train 0.08795 | val 0.09326
  Regression -> MSE: 0.000172, MAE: 0.009607, R²: -0.0005
  Directional -> Accuracy: 0.5102, MCC: -0.0521, F1: 0.3333

[84/88] Processing V...


[I 2026-02-24 00:28:27,913] Trial 62 finished with value: -0.01146340431316433 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 1.693314671984852e-05, 'weight_decay': 7.3043903718819195e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.10341934937425461, 'early_stopping_min_delta': 0.007188016887595175}. Best is trial 44 with value: -0.011362814469631832.

  Regression -> MSE: 0.000247, MAE: 0.012415, R²: -0.0432
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.19464 | val 0.28089
  Epoch 020 - train 0.19608 | val 0.28340
  Epoch 021 - train 0.19944 | val 0.28624
  Regression -> MSE: 0.000252, MAE: 0.012737, R²: -0.0189
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.19849 | val 0.19591
  Epoch 020 - train 0.18802 | val 0.20230
  Epoch 021 - train 0.20224 | val 0.20411
  Regression -> MSE: 0.000693, MAE: 0.019474, R²: -0.0116
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.21486 | val 0.38725
  Epoch 020 - train 0.20653 | val 0.37845
  Epoch 021 - train 0.19690 | val 0.37723
  Regression -> MSE: 0.000327, MAE: 0.014635, R²: -0.0535
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.16330 | val 0.24900
  Epoch 020 - train 0.15958 | val 0.24399
  Epoch 021 - train 0.16223 | val 0.24298
  Regression -> MSE: 0.000354, MAE: 0.014640, R²: -0.0130
  Directional -> Accuracy: 0.5467, MCC: 0.0409, F1: 0.6731

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.21028 | val 0.21157
  Epoch 020 - train 0.20131 | val 0.21626
  Epoch 021 - train 0.19962 | val 0.21552
  Regression -> MSE: 0.000205, MAE: 0.010175, R²: -0.0058
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.18947 | val 0.38428
  Epoch 020 - train 0.19141 | val 0.38707
  Epoch 021 - train 0.20664 | val 0.38871
  Regression -> MSE: 0.000559, MAE: 0.018187, R²: -0.0071
  Directional -> Accuracy: 0.4468, MCC: -0.1093, F1: 0.4091

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.22356 | val 0.24312
  Epoch 020 - train 0.20826 | val 0.23734
  Epoch 030 - train 0.20830 | val 0.23582
  Regression -> MSE: 0.000326, MAE: 0.014705, R²: -0.3270
  Directional -> Accuracy: 0.4348, MCC: 0.0049, F1: 0.5517

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.19332 | val 0.25930
  Epoch 020 - train 0.20147 | val 0.27080
  Epoch 021 - train 0.19650 | val 0.27106
  Regression -> MSE: 0.000622, MAE: 0.019715, R²: -0.0407
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.20722 | val 0.29971
  Epoch 020 - train 0.20277 | val 0.29661
  Epoch 021 - train 0.19546 | val 0.29622
  Regression -> MSE: 0.000384, MAE: 0.016164, R²: -0.0014
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.20945 | val 0.29764
  Epoch 020 - train 0.21527 | val 0.29005
  Epoch 021 - train 0.20970 | val 0.28815
  Regression -> MSE: 0.000245, MAE: 0.011623, R²: -0.0161
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.18024 | val 0.30592
  Epoch 020 - train 0.17096 | val 0.31421
  Epoch 021 - train 0.17995 | val 0.31577
  Regression -> MSE: 0.000312, MAE: 0.013637, R²: -0.0036
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.20405 | val 0.23554
  Epoch 020 - train 0.20515 | val 0.23397
  Epoch 021 - train 0.20749 | val 0.23416
  Regression -> MSE: 0.000677, MAE: 0.019506, R²: 0.0005
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.21696 | val 0.35484
  Epoch 020 - train 0.19900 | val 0.37340
  Epoch 021 - train 0.20044 | val 0.38213
  Regression -> MSE: 0.000139, MAE: 0.009016, R²: -0.0082
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.17274 | val 0.25880
  Epoch 020 - train 0.17704 | val 0.25436
  Epoch 030 - train 0.17339 | val 0.25044
  Regression -> MSE: 0.000218, MAE: 0.010694, R²: 0.0309
  Directional -> Accuracy: 0.5574, MCC: 0.1172, F1: 0.6301

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.20368 | val 0.42049
  Epoch 020 - train 0.19828 | val 0.42524
  Epoch 021 - train 0.19038 | val 0.42418
  Regression -> MSE: 0.000362, MAE: 0.016074, R²: 0.0000
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.20547 | val 0.20143
  Epoch 020 - train 0.21198 | val 0.19314
  Epoch 030 - train 0.19727 | val 0.18985
  Regression -> MSE: 0.000108, MAE: 0.008218, R²: -0.0017
  Directional -> Accuracy: 0.5000, MCC: 0.0202, F1: 0.4615

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.20203 | val 0.34986
  Epoch 020 - train 0.19721 | val 0.35019
  Epoch 021 - train 0.21172 | val 0.35038
  Regression -> MSE: 0.000157, MAE: 0.009711, R²: -0.0046
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.20132 | val 0.18967
  Epoch 020 - train 0.20540 | val 0.19139
  Epoch 021 - train 0.20161 | val 0.19191
  Regression -> MSE: 0.000286, MAE: 0.013664, R²: -0.0502
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.18268 | val 0.27194
  Epoch 020 - train 0.17390 | val 0.26926
  Epoch 021 - train 0.18211 | val 0.26984
  Regression -> MSE: 0.000159, MAE: 0.008876, R²: -0.0599
  Directional -> Accuracy: 0.5846, MCC: 0.1798, F1: 0.6087

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.20455 | val 0.29595
  Epoch 020 - train 0.20260 | val 0.29811
  Epoch 021 - train 0.20069 | val 0.29760
  Regression -> MSE: 0.000232, MAE: 0.010886, R²: -0.0263
  Directional -> Accuracy: 0.5600, MCC: 0.0875, F1: 0.7080

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.20112 | val 0.33022
  Epoch 020 - train 0.20760 | val 0.32070
  Epoch 021 - train 0.20623 | val 0.31625
  Regression -> MSE: 0.000145, MAE: 0.008434, R²: -0.0112
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.19489 | val 0.23043
  Epoch 020 - train 0.18119 | val 0.23031
  Epoch 021 - train 0.18129 | val 0.23054
  Regression -> MSE: 0.000167, MAE: 0.010315, R²: -0.0102
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.20991 | val 0.24047
  Epoch 020 - train 0.20430 | val 0.24225
  Epoch 021 - train 0.20375 | val 0.24242
  Regression -> MSE: 0.000086, MAE: 0.007108, R²: -0.0129
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.20454 | val 0.26920
  Epoch 020 - train 0.19942 | val 0.27640
  Epoch 021 - train 0.19991 | val 0.28221
  Regression -> MSE: 0.000212, MAE: 0.011200, R²: -0.0014
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.18817 | val 0.17270
  Epoch 020 - train 0.18387 | val 0.17252
  Epoch 021 - train 0.18576 | val 0.17166
  Regression -> MSE: 0.000094, MAE: 0.008090, R²: -0.0218
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.20976 | val 0.15790
  Epoch 020 - train 0.21495 | val 0.15604
  Epoch 021 - train 0.21265 | val 0.15637
  Regression -> MSE: 0.000107, MAE: 0.008899, R²: -0.0337
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.19664 | val 0.23586
  Epoch 020 - train 0.20203 | val 0.23684
  Epoch 021 - train 0.20362 | val 0.23523
  Regression -> MSE: 0.000243, MAE: 0.012915, R²: -0.0510
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.20387 | val 0.25269
  Epoch 020 - train 0.20385 | val 0.25077
  Epoch 021 - train 0.20060 | val 0.25040
  Regression -> MSE: 0.000171, MAE: 0.007818, R²: -0.0251
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.19666 | val 0.17378
  Epoch 020 - train 0.22385 | val 0.17634
  Epoch 021 - train 0.20225 | val 0.17599
  Regression -> MSE: 0.000242, MAE: 0.012096, R²: -0.0225
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.19697 | val 0.31801
  Epoch 020 - train 0.18805 | val 0.32038
  Epoch 021 - train 0.19268 | val 0.32016
  Regression -> MSE: 0.000232, MAE: 0.010011, R²: -0.0057
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.20389 | val 0.26425
  Epoch 020 - train 0.18863 | val 0.26775
  Epoch 021 - train 0.19633 | val 0.26756
  Regression -> MSE: 0.000135, MAE: 0.008257, R²: -0.0035
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.21425 | val 0.25200
  Epoch 020 - train 0.19845 | val 0.25366
  Epoch 021 - train 0.21042 | val 0.25292
  Regression -> MSE: 0.000200, MAE: 0.010693, R²: -0.0601
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.17775 | val 0.23579
  Epoch 020 - train 0.18274 | val 0.22828
  Epoch 021 - train 0.18426 | val 0.22662
  Regression -> MSE: 0.000263, MAE: 0.010568, R²: -0.0060
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.21072 | val 0.15568
  Epoch 020 - train 0.20891 | val 0.17705
  Epoch 029 - train 0.20214 | val 0.17753
  Regression -> MSE: 0.000164, MAE: 0.010229, R²: 0.0186
  Directional -> Accuracy: 0.4737, MCC: -0.0619, F1: 0.2857

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.18122 | val 0.20208
  Epoch 020 - train 0.19502 | val 0.20051
  Epoch 021 - train 0.18224 | val 0.20061
  Regression -> MSE: 0.000180, MAE: 0.010298, R²: -0.0016
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.19736 | val 0.17938
  Epoch 020 - train 0.18864 | val 0.17884
  Epoch 021 - train 0.17832 | val 0.17865
  Regression -> MSE: 0.000344, MAE: 0.011769, R²: -0.0051
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.21346 | val 0.13464
  Epoch 020 - train 0.21450 | val 0.13740
  Epoch 021 - train 0.21739 | val 0.13542
  Regression -> MSE: 0.000122, MAE: 0.008409, R²: -0.1647
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.21512 | val 0.30316
  Epoch 020 - train 0.19155 | val 0.30236
  Epoch 021 - train 0.19469 | val 0.29944
  Regression -> MSE: 0.000219, MAE: 0.011273, R²: -0.0002
  Directional -> Accuracy: 0.5614, MCC: 0.1520, F1: 0.1935

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.19644 | val 0.37122
  Epoch 020 - train 0.19774 | val 0.35676
  Epoch 021 - train 0.19385 | val 0.35557
  Regression -> MSE: 0.000093, MAE: 0.007552, R²: -0.2022
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.20890 | val 0.15066
  Epoch 020 - train 0.19972 | val 0.14535
  Epoch 030 - train 0.18378 | val 0.14322
  Regression -> MSE: 0.000319, MAE: 0.014692, R²: -0.0380
  Directional -> Accuracy: 0.4082, MCC: 0.0726, F1: 0.5397

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.23111 | val 0.11355
  Epoch 020 - train 0.19000 | val 0.12143
  Epoch 021 - train 0.20881 | val 0.12115
  Regression -> MSE: 0.000248, MAE: 0.011519, R²: -0.0177
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.19969 | val 0.22684
  Epoch 020 - train 0.18400 | val 0.23298
  Epoch 029 - train 0.18193 | val 0.23422
  Regression -> MSE: 0.000082, MAE: 0.007184, R²: -0.0166
  Directional -> Accuracy: 0.5333, MCC: 0.0808, F1: 0.6154

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.20219 | val 0.25201
  Epoch 020 - train 0.20073 | val 0.26616
  Epoch 025 - train 0.20288 | val 0.26590
  Regression -> MSE: 0.000306, MAE: 0.014577, R²: 0.0022
  Directional -> Accuracy: 0.4894, MCC: -0.0437, F1: 0.6129

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.21071 | val 0.21865
  Epoch 020 - train 0.19401 | val 0.21870
  Epoch 028 - train 0.18627 | val 0.21940
  Regression -> MSE: 0.000105, MAE: 0.007209, R²: -0.0738
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.20103 | val 0.23663
  Epoch 020 - train 0.20377 | val 0.24177
  Epoch 021 - train 0.20522 | val 0.24171
  Regression -> MSE: 0.000173, MAE: 0.009461, R²: -0.0070
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.19153 | val 0.22617
  Epoch 020 - train 0.17903 | val 0.22549

[I 2026-02-24 00:31:13,750] Trial 63 finished with value: -0.01148538557914826 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 2.7807369204951625e-05, 'weight_decay': 1.933646281377189e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.3136194357051745, 'early_stopping_min_delta': 0.007876307140971386}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.19970 | val 0.29264
  Epoch 021 - train 0.20131 | val 0.29339
  Regression -> MSE: 0.000245, MAE: 0.012377, R²: -0.0323
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15978 | val 0.19601
  Epoch 020 - train 0.16080 | val 0.19490
  Epoch 021 - train 0.15389 | val 0.19466
  Regression -> MSE: 0.000247, MAE: 0.012557, R²: -0.0291
  Directional -> Accuracy: 0.4474, MCC: -0.0249, F1: 0.6038

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.15960 | val 0.15695
  Epoch 020 - train 0.15476 | val 0.15574
  Epoch 021 - train 0.15613 | val 0.15635
  Regression -> MSE: 0.000703, MAE: 0.019633, R²: -0.0071
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.17677 | val 0.24732
  Epoch 020 - train 0.17664 | val 0.24566
  Epoch 021 - train 0.17924 | val 0.24529
  Regression -> MSE: 0.000327, MAE: 0.014539, R²: -0.0402
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14267 | val 0.16649
  Epoch 020 - train 0.14045 | val 0.19407
  Epoch 021 - train 0.13859 | val 0.19214
  Regression -> MSE: 0.000381, MAE: 0.015049, R²: -0.0796
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16317 | val 0.14602
  Epoch 020 - train 0.16669 | val 0.14410
  Epoch 021 - train 0.16412 | val 0.14373
  Regression -> MSE: 0.000209, MAE: 0.010138, R²: -0.0111
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.16391 | val 0.40680
  Epoch 020 - train 0.15626 | val 0.39660
  Epoch 021 - train 0.14845 | val 0.39478
  Regression -> MSE: 0.000649, MAE: 0.019766, R²: -0.1463
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.17450 | val 0.18308
  Epoch 020 - train 0.16848 | val 0.18397
  Epoch 021 - train 0.16484 | val 0.18422
  Regression -> MSE: 0.000252, MAE: 0.011989, R²: -0.0178
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.16219 | val 0.24036
  Epoch 020 - train 0.16128 | val 0.24224
  Epoch 021 - train 0.16530 | val 0.24405
  Regression -> MSE: 0.000702, MAE: 0.020755, R²: -0.1486
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.16422 | val 0.18957
  Epoch 020 - train 0.17070 | val 0.19096
  Epoch 021 - train 0.16336 | val 0.19043
  Regression -> MSE: 0.000386, MAE: 0.015768, R²: -0.0349
  Directional -> Accuracy: 0.5833, MCC: 0.1654, F1: 0.0909

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16858 | val 0.22474
  Epoch 020 - train 0.15743 | val 0.21735
  Epoch 021 - train 0.16084 | val 0.21777
  Regression -> MSE: 0.000246, MAE: 0.012078, R²: -0.0063
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.16379 | val 0.29344
  Epoch 020 - train 0.16953 | val 0.29177
  Epoch 021 - train 0.16227 | val 0.29815
  Regression -> MSE: 0.000337, MAE: 0.014493, R²: -0.0791
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.17044 | val 0.18050
  Epoch 020 - train 0.18369 | val 0.17941
  Epoch 021 - train 0.16996 | val 0.17920
  Regression -> MSE: 0.000695, MAE: 0.019753, R²: -0.0141
  Directional -> Accuracy: 0.4912, MCC: -0.0048, F1: 0.1212

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16881 | val 0.16340
  Epoch 020 - train 0.16977 | val 0.16356
  Epoch 021 - train 0.16751 | val 0.16346
  Regression -> MSE: 0.000139, MAE: 0.009057, R²: -0.0055
  Directional -> Accuracy: 0.4286, MCC: -0.1350, F1: 0.4286

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.16361 | val 0.20175
  Epoch 020 - train 0.15539 | val 0.20029
  Epoch 029 - train 0.15284 | val 0.19823
  Regression -> MSE: 0.000228, MAE: 0.010935, R²: -0.0076
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16654 | val 0.30884
  Epoch 020 - train 0.15995 | val 0.30943
  Epoch 021 - train 0.16905 | val 0.30957
  Regression -> MSE: 0.000374, MAE: 0.015999, R²: -0.0203
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.17309 | val 0.17089
  Epoch 020 - train 0.17443 | val 0.17459
  Epoch 021 - train 0.16518 | val 0.17183
  Regression -> MSE: 0.000113, MAE: 0.008110, R²: -0.0458
  Directional -> Accuracy: 0.4638, MCC: -0.1027, F1: 0.5542

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15542 | val 0.24748
  Epoch 020 - train 0.15835 | val 0.24809
  Epoch 021 - train 0.15455 | val 0.24784
  Regression -> MSE: 0.000165, MAE: 0.010238, R²: -0.0467
  Directional -> Accuracy: 0.5000, MCC: -0.0914, F1: 0.6133

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16790 | val 0.15324
  Epoch 020 - train 0.15142 | val 0.15210
  Epoch 021 - train 0.17016 | val 0.15199
  Regression -> MSE: 0.000278, MAE: 0.013259, R²: -0.0170
  Directional -> Accuracy: 0.5067, MCC: -0.1582, F1: 0.6542

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.15029 | val 0.21711
  Epoch 020 - train 0.15302 | val 0.21336
  Epoch 021 - train 0.14893 | val 0.21334
  Regression -> MSE: 0.000192, MAE: 0.010100, R²: -0.2663
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16495 | val 0.21863
  Epoch 020 - train 0.15671 | val 0.21544
  Epoch 021 - train 0.15276 | val 0.21636
  Regression -> MSE: 0.000234, MAE: 0.010944, R²: -0.0283
  Directional -> Accuracy: 0.5676, MCC: 0.0816, F1: 0.7037

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16246 | val 0.19830
  Epoch 020 - train 0.16168 | val 0.19785
  Epoch 021 - train 0.15924 | val 0.19800
  Regression -> MSE: 0.000146, MAE: 0.008478, R²: -0.0107
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15100 | val 0.18203
  Epoch 020 - train 0.16387 | val 0.18070
  Epoch 021 - train 0.14745 | val 0.18106
  Regression -> MSE: 0.000170, MAE: 0.010398, R²: -0.0281
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16659 | val 0.18795
  Epoch 020 - train 0.17024 | val 0.18732
  Epoch 021 - train 0.16969 | val 0.18656
  Regression -> MSE: 0.000087, MAE: 0.007149, R²: -0.0061
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16796 | val 0.19575
  Epoch 020 - train 0.15931 | val 0.19714
  Epoch 021 - train 0.16320 | val 0.19662
  Regression -> MSE: 0.000219, MAE: 0.011079, R²: -0.0396
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.16346 | val 0.13984
  Epoch 020 - train 0.15148 | val 0.13540
  Epoch 021 - train 0.14201 | val 0.13544
  Regression -> MSE: 0.000095, MAE: 0.008060, R²: -0.0601
  Directional -> Accuracy: 0.4182, MCC: -0.1733, F1: 0.4667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18016 | val 0.21764
  Epoch 020 - train 0.17678 | val 0.22053
  Epoch 021 - train 0.14878 | val 0.21930
  Regression -> MSE: 0.000127, MAE: 0.009489, R²: -0.2728
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16903 | val 0.22362
  Epoch 020 - train 0.17012 | val 0.21813
  Epoch 021 - train 0.16041 | val 0.22119
  Regression -> MSE: 0.000257, MAE: 0.013440, R²: -0.0844
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.17088 | val 0.17989
  Epoch 020 - train 0.17686 | val 0.17824
  Epoch 021 - train 0.16755 | val 0.17901
  Regression -> MSE: 0.000176, MAE: 0.007935, R²: -0.0417
  Directional -> Accuracy: 0.5357, MCC: -0.1211, F1: 0.6977

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16364 | val 0.11947
  Epoch 020 - train 0.17573 | val 0.12161
  Epoch 029 - train 0.17261 | val 0.12177
  Regression -> MSE: 0.000239, MAE: 0.012333, R²: 0.0134
  Directional -> Accuracy: 0.5000, MCC: 0.0205, F1: 0.4737

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.18700 | val 0.24852
  Epoch 020 - train 0.16140 | val 0.24777
  Epoch 021 - train 0.16527 | val 0.24777
  Regression -> MSE: 0.000236, MAE: 0.010081, R²: -0.0024
  Directional -> Accuracy: 0.5238, MCC: 0.1168, F1: 0.6429

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18182 | val 0.16521
  Epoch 020 - train 0.16916 | val 0.16210
  Epoch 021 - train 0.18467 | val 0.16196
  Regression -> MSE: 0.000141, MAE: 0.008347, R²: -0.0221
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.17552 | val 0.19180
  Epoch 020 - train 0.15879 | val 0.19197
  Epoch 021 - train 0.16047 | val 0.19199
  Regression -> MSE: 0.000194, MAE: 0.010392, R²: -0.0572
  Directional -> Accuracy: 0.4898, MCC: 0.1358, F1: 0.0741

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.16774 | val 0.19696
  Epoch 020 - train 0.15101 | val 0.19493
  Epoch 021 - train 0.16749 | val 0.19378
  Regression -> MSE: 0.000271, MAE: 0.011123, R²: -0.0217
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14991 | val 0.15715
  Epoch 020 - train 0.16284 | val 0.15950
  Epoch 021 - train 0.14191 | val 0.15893
  Regression -> MSE: 0.000185, MAE: 0.010446, R²: -0.0085
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16727 | val 0.14759
  Epoch 020 - train 0.15598 | val 0.14724
  Epoch 021 - train 0.15365 | val 0.14759
  Regression -> MSE: 0.000345, MAE: 0.012261, R²: 0.0073
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.17842 | val 0.10761
  Epoch 020 - train 0.16834 | val 0.10905
  Epoch 021 - train 0.20019 | val 0.10842
  Regression -> MSE: 0.000124, MAE: 0.008509, R²: -0.1772
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17029 | val 0.20552
  Epoch 020 - train 0.15937 | val 0.20535
  Epoch 021 - train 0.15782 | val 0.20505
  Regression -> MSE: 0.000224, MAE: 0.011437, R²: -0.0167
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16603 | val 0.27139
  Epoch 020 - train 0.16384 | val 0.26800
  Epoch 021 - train 0.15581 | val 0.26763
  Regression -> MSE: 0.000092, MAE: 0.007520, R²: -0.2491
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.17865 | val 0.12362
  Epoch 020 - train 0.17398 | val 0.12259
  Epoch 021 - train 0.17193 | val 0.12396
  Regression -> MSE: 0.000319, MAE: 0.014244, R²: -0.0240
  Directional -> Accuracy: 0.3750, MCC: 0.1080, F1: 0.5312

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16109 | val 0.18825
  Epoch 020 - train 0.15174 | val 0.19147
  Epoch 021 - train 0.15279 | val 0.19083
  Regression -> MSE: 0.000079, MAE: 0.006984, R²: -0.0081
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17076 | val 0.19615
  Epoch 020 - train 0.17028 | val 0.19696
  Epoch 021 - train 0.16324 | val 0.19536
  Regression -> MSE: 0.000304, MAE: 0.014405, R²: -0.0090
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14816 | val 0.20139
  Epoch 020 - train 0.16166 | val 0.20316
  Epoch 021 - train 0.16185 | val 0.20405
  Regression -> MSE: 0.000107, MAE: 0.007193, R²: -0.0569
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.19496 | val 0.19491
  Epoch 020 - train 0.17676 | val 0.19551
  Epoch 021 - train 0.17527 | val 0.19482
  Regression -> MSE: 0.000178, MAE: 0.010263, R²: -0.0155
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13996 | val 0.16226
  Epoch 020 - train 0.14912 | val 0.16235
  Epoch 021 - train 0.14766 | val 0.16210
  Regression -> MSE: 0.000226, MAE: 0.011831, R²: -0.0015
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.16647 | val 0.18046

[I 2026-02-24 00:36:45,951] Trial 64 finished with value: -0.01163870267944109 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 1.1840159178973276e-05, 'weight_decay': 3.3561554095800233e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2286559778704761, 'early_stopping_min_delta': 0.006706716377418126}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.15821 | val 0.21556
  Regression -> MSE: 0.000243, MAE: 0.012436, R²: -0.0114
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12039 | val 0.15271
  Epoch 020 - train 0.12123 | val 0.15264
  Epoch 021 - train 0.11924 | val 0.15283
  Regression -> MSE: 0.000267, MAE: 0.013163, R²: -0.0767
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10664 | val 0.09998
  Epoch 020 - train 0.10730 | val 0.10038
  Epoch 021 - train 0.10585 | val 0.10035
  Regression -> MSE: 0.000698, MAE: 0.019572, R²: -0.0197
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12029 | val 0.16837
  Epoch 020 - train 0.11418 | val 0.16986
  Epoch 021 - train 0.10983 | val 0.16986
  Regression -> MSE: 0.000313, MAE: 0.014417, R²: -0.0083
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09705 | val 0.09182
  Epoch 020 - train 0.09788 | val 0.09239
  Epoch 021 - train 0.09817 | val 0.09252
  Regression -> MSE: 0.000350, MAE: 0.014581, R²: -0.0017
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11631 | val 0.10762
  Epoch 020 - train 0.11553 | val 0.10918
  Epoch 021 - train 0.12008 | val 0.10919
  Regression -> MSE: 0.000205, MAE: 0.010254, R²: -0.0052
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10755 | val 0.19745
  Epoch 020 - train 0.10568 | val 0.19717
  Epoch 021 - train 0.10441 | val 0.19703
  Regression -> MSE: 0.000588, MAE: 0.018740, R²: -0.0594
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12132 | val 0.13288
  Epoch 020 - train 0.12805 | val 0.13270
  Epoch 021 - train 0.11950 | val 0.13274
  Regression -> MSE: 0.000247, MAE: 0.011917, R²: -0.0064
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12676 | val 0.12852
  Epoch 020 - train 0.12552 | val 0.11937
  Epoch 030 - train 0.11977 | val 0.11707
  Regression -> MSE: 0.000601, MAE: 0.019216, R²: -0.0067
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10975 | val 0.13350
  Epoch 020 - train 0.10464 | val 0.14460
  Epoch 021 - train 0.11079 | val 0.14458
  Regression -> MSE: 0.000389, MAE: 0.015987, R²: -0.0131
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11543 | val 0.13851
  Epoch 020 - train 0.11616 | val 0.13681
  Epoch 021 - train 0.11723 | val 0.13643
  Regression -> MSE: 0.000242, MAE: 0.012034, R²: -0.0020
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11267 | val 0.15177
  Epoch 020 - train 0.10614 | val 0.14952
  Epoch 021 - train 0.10401 | val 0.14881
  Regression -> MSE: 0.000311, MAE: 0.013754, R²: 0.0012
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11954 | val 0.12749
  Epoch 020 - train 0.11013 | val 0.13054
  Epoch 021 - train 0.11445 | val 0.13055
  Regression -> MSE: 0.000677, MAE: 0.019508, R²: 0.0005
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12599 | val 0.13103
  Epoch 020 - train 0.12482 | val 0.15546
  Epoch 021 - train 0.11897 | val 0.15462
  Regression -> MSE: 0.000141, MAE: 0.009008, R²: -0.0179
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10157 | val 0.14889
  Epoch 020 - train 0.10379 | val 0.14945
  Epoch 021 - train 0.10675 | val 0.14996
  Regression -> MSE: 0.000225, MAE: 0.010786, R²: 0.0001
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11271 | val 0.21165
  Epoch 020 - train 0.11606 | val 0.21202
  Epoch 021 - train 0.11308 | val 0.21200
  Regression -> MSE: 0.000362, MAE: 0.016075, R²: -0.0001
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11479 | val 0.12793
  Epoch 020 - train 0.11793 | val 0.12836
  Epoch 021 - train 0.11793 | val 0.12869
  Regression -> MSE: 0.000110, MAE: 0.008177, R²: -0.0159
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11109 | val 0.17679
  Epoch 020 - train 0.10741 | val 0.17998
  Epoch 021 - train 0.10985 | val 0.17981
  Regression -> MSE: 0.000158, MAE: 0.009921, R²: -0.0134
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12029 | val 0.14351
  Epoch 020 - train 0.11290 | val 0.14505
  Epoch 021 - train 0.12150 | val 0.14497
  Regression -> MSE: 0.000295, MAE: 0.013999, R²: -0.0857
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10677 | val 0.13891
  Epoch 020 - train 0.10854 | val 0.13789
  Epoch 021 - train 0.10485 | val 0.13796
  Regression -> MSE: 0.000154, MAE: 0.008751, R²: -0.0276
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11318 | val 0.15405
  Epoch 020 - train 0.11191 | val 0.15343
  Epoch 021 - train 0.11476 | val 0.15423
  Regression -> MSE: 0.000231, MAE: 0.010914, R²: -0.0228
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11426 | val 0.13224
  Epoch 020 - train 0.11035 | val 0.13357
  Epoch 021 - train 0.11417 | val 0.13341
  Regression -> MSE: 0.000145, MAE: 0.008428, R²: -0.0091
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11029 | val 0.12294
  Epoch 020 - train 0.11248 | val 0.12247
  Epoch 021 - train 0.11327 | val 0.12218
  Regression -> MSE: 0.000168, MAE: 0.010348, R²: -0.0162
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11346 | val 0.12869
  Epoch 020 - train 0.11568 | val 0.13047
  Epoch 021 - train 0.11299 | val 0.13018
  Regression -> MSE: 0.000086, MAE: 0.007108, R²: -0.0127
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11166 | val 0.13249
  Epoch 020 - train 0.11006 | val 0.13302
  Epoch 021 - train 0.10995 | val 0.13303
  Regression -> MSE: 0.000211, MAE: 0.011127, R²: 0.0019
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10229 | val 0.09822
  Epoch 020 - train 0.10951 | val 0.09868
  Epoch 021 - train 0.10740 | val 0.09859
  Regression -> MSE: 0.000095, MAE: 0.008091, R²: -0.0334
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11406 | val 0.09219
  Epoch 020 - train 0.12022 | val 0.10279
  Epoch 021 - train 0.11618 | val 0.10349
  Regression -> MSE: 0.000117, MAE: 0.009222, R²: -0.1300
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11692 | val 0.10143
  Epoch 020 - train 0.11420 | val 0.10088
  Epoch 021 - train 0.11146 | val 0.10100
  Regression -> MSE: 0.000239, MAE: 0.012801, R²: -0.0304
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11014 | val 0.13153
  Epoch 020 - train 0.11395 | val 0.13230
  Epoch 021 - train 0.11721 | val 0.13225
  Regression -> MSE: 0.000170, MAE: 0.007819, R²: -0.0235
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11751 | val 0.09084
  Epoch 020 - train 0.11530 | val 0.08859
  Epoch 021 - train 0.11751 | val 0.08819
  Regression -> MSE: 0.000237, MAE: 0.011876, R²: -0.0019
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11832 | val 0.17411
  Epoch 020 - train 0.11649 | val 0.19826
  Epoch 021 - train 0.10804 | val 0.19852
  Regression -> MSE: 0.000232, MAE: 0.009966, R²: -0.0072
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13064 | val 0.14648
  Epoch 020 - train 0.13429 | val 0.17037
  Epoch 021 - train 0.13134 | val 0.17047
  Regression -> MSE: 0.000145, MAE: 0.008761, R²: -0.0775
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11901 | val 0.12912
  Epoch 020 - train 0.11931 | val 0.13064
  Epoch 021 - train 0.12739 | val 0.13063
  Regression -> MSE: 0.000199, MAE: 0.010683, R²: -0.0569
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09718 | val 0.12258
  Epoch 020 - train 0.10022 | val 0.12221
  Epoch 021 - train 0.09979 | val 0.12208
  Regression -> MSE: 0.000280, MAE: 0.010953, R²: -0.0701
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11039 | val 0.09032
  Epoch 020 - train 0.10548 | val 0.09672
  Epoch 021 - train 0.11066 | val 0.09828
  Regression -> MSE: 0.000169, MAE: 0.010359, R²: -0.0141
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10984 | val 0.11083
  Epoch 020 - train 0.10566 | val 0.12146
  Epoch 021 - train 0.10846 | val 0.12163
  Regression -> MSE: 0.000180, MAE: 0.010249, R²: 0.0013
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10824 | val 0.10121
  Epoch 020 - train 0.10894 | val 0.10189
  Epoch 021 - train 0.10545 | val 0.10184
  Regression -> MSE: 0.000353, MAE: 0.012523, R²: -0.0298
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11928 | val 0.07055
  Epoch 020 - train 0.11627 | val 0.07304
  Epoch 021 - train 0.11720 | val 0.07300
  Regression -> MSE: 0.000126, MAE: 0.008472, R²: -0.1966
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11112 | val 0.14215
  Epoch 020 - train 0.11171 | val 0.14116
  Epoch 021 - train 0.11257 | val 0.14115
  Regression -> MSE: 0.000222, MAE: 0.011409, R²: -0.0157
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11322 | val 0.17814
  Epoch 020 - train 0.11082 | val 0.17777
  Epoch 021 - train 0.11091 | val 0.17810
  Regression -> MSE: 0.000086, MAE: 0.007253, R²: -0.1071
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11644 | val 0.08970
  Epoch 020 - train 0.11001 | val 0.08968
  Epoch 021 - train 0.10897 | val 0.08968
  Regression -> MSE: 0.000333, MAE: 0.015109, R²: -0.0829
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10872 | val 0.07290
  Epoch 020 - train 0.11489 | val 0.06761
  Epoch 021 - train 0.11070 | val 0.06699
  Regression -> MSE: 0.000262, MAE: 0.011516, R²: -0.0762
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12395 | val 0.13049
  Epoch 020 - train 0.12645 | val 0.13166
  Epoch 021 - train 0.12053 | val 0.13211
  Regression -> MSE: 0.000085, MAE: 0.007060, R²: -0.0535
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12662 | val 0.12791
  Epoch 020 - train 0.12394 | val 0.13100
  Epoch 021 - train 0.11740 | val 0.13113
  Regression -> MSE: 0.000311, MAE: 0.014540, R²: -0.0130
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11509 | val 0.11270
  Epoch 020 - train 0.11298 | val 0.11682
  Epoch 021 - train 0.11843 | val 0.11737
  Regression -> MSE: 0.000098, MAE: 0.007271, R²: 0.0003
  Directional -> Accuracy: 0.5455, MCC: 0.1623, F1: 0.4737

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11868 | val 0.12342
  Epoch 020 - train 0.12176 | val 0.12316
  Epoch 021 - train 0.12016 | val 0.12326
  Regression -> MSE: 0.000174, MAE: 0.010003, R²: -0.0098
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10840 | val 0.11988

[I 2026-02-24 00:38:42,031] Trial 65 finished with value: -0.011502427295397431 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 8.269115253424703e-06, 'weight_decay': 5.861156020615288e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.1553592277003366, 'early_stopping_min_delta': 0.0075146183717871625}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.11116 | val 0.14492
  Epoch 021 - train 0.11556 | val 0.14492
  Regression -> MSE: 0.000239, MAE: 0.012327, R²: -0.0087
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.27951 | val 0.32273
  Epoch 020 - train 0.23992 | val 0.32553
  Epoch 021 - train 0.25519 | val 0.32540
  Regression -> MSE: 0.000252, MAE: 0.012801, R²: -0.0279
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.27428 | val 0.36582
  Epoch 020 - train 0.30026 | val 0.34031
  Epoch 021 - train 0.27121 | val 0.33724
  Regression -> MSE: 0.000693, MAE: 0.019652, R²: -0.0030
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.28034 | val 0.41580
  Epoch 020 - train 0.25797 | val 0.41180
  Epoch 021 - train 0.27916 | val 0.41283
  Regression -> MSE: 0.000353, MAE: 0.015127, R²: -0.0224
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.24798 | val 0.31330
  Epoch 020 - train 0.22979 | val 0.31117
  Epoch 021 - train 0.23290 | val 0.30855
  Regression -> MSE: 0.000352, MAE: 0.014521, R²: -0.0205
  Directional -> Accuracy: 0.5132, MCC: -0.0077, F1: 0.6105

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.28729 | val 0.28294
  Epoch 020 - train 0.26633 | val 0.28026
  Epoch 021 - train 0.26408 | val 0.27610
  Regression -> MSE: 0.000205, MAE: 0.010118, R²: -0.0214
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.26375 | val 0.47727
  Epoch 020 - train 0.26291 | val 0.47574
  Epoch 021 - train 0.27317 | val 0.47586
  Regression -> MSE: 0.000612, MAE: 0.019048, R²: -0.0690
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.27982 | val 0.31326
  Epoch 020 - train 0.28629 | val 0.31165
  Epoch 021 - train 0.27594 | val 0.31040
  Regression -> MSE: 0.000247, MAE: 0.011979, R²: -0.0033
  Directional -> Accuracy: 0.6000, MCC: 0.0625, F1: 0.1765

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.27131 | val 0.34055
  Epoch 020 - train 0.26434 | val 0.34811
  Epoch 021 - train 0.27796 | val 0.34986
  Regression -> MSE: 0.000611, MAE: 0.019362, R²: -0.0460
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.27621 | val 0.36686
  Epoch 020 - train 0.27801 | val 0.36454
  Epoch 021 - train 0.27485 | val 0.36486
  Regression -> MSE: 0.000341, MAE: 0.014859, R²: -0.0099
  Directional -> Accuracy: 0.6190, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.25765 | val 0.31765
  Epoch 020 - train 0.26567 | val 0.32905
  Epoch 021 - train 0.25295 | val 0.32981
  Regression -> MSE: 0.000240, MAE: 0.012050, R²: -0.0074
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.27772 | val 0.46623
  Epoch 020 - train 0.25197 | val 0.48083
  Epoch 021 - train 0.25704 | val 0.48427
  Regression -> MSE: 0.000306, MAE: 0.013565, R²: 0.0004
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.27757 | val 0.30317
  Epoch 020 - train 0.28117 | val 0.29941
  Epoch 021 - train 0.26939 | val 0.30010
  Regression -> MSE: 0.000669, MAE: 0.019423, R²: 0.0014
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.28142 | val 0.26406
  Epoch 020 - train 0.28925 | val 0.27211
  Epoch 021 - train 0.30367 | val 0.27578
  Regression -> MSE: 0.000152, MAE: 0.009440, R²: -0.0115
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.28005 | val 0.38724
  Epoch 020 - train 0.27570 | val 0.37839
  Epoch 021 - train 0.25901 | val 0.37456
  Regression -> MSE: 0.000225, MAE: 0.010850, R²: -0.0024
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.27695 | val 0.58717
  Epoch 020 - train 0.26961 | val 0.58480
  Epoch 021 - train 0.27097 | val 0.58486
  Regression -> MSE: 0.000378, MAE: 0.016422, R²: -0.0045
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.31530 | val 0.51252
  Epoch 020 - train 0.31328 | val 0.45738
  Epoch 021 - train 0.30897 | val 0.45816
  Regression -> MSE: 0.000112, MAE: 0.007932, R²: -0.0545
  Directional -> Accuracy: 0.5352, MCC: 0.0000, F1: 0.6972

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.29101 | val 0.52883
  Epoch 020 - train 0.26579 | val 0.52253
  Epoch 021 - train 0.28029 | val 0.51721
  Regression -> MSE: 0.000160, MAE: 0.009911, R²: 0.0006
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.28239 | val 0.24954
  Epoch 020 - train 0.25206 | val 0.24869
  Epoch 021 - train 0.25690 | val 0.25062
  Regression -> MSE: 0.000279, MAE: 0.013439, R²: -0.0383
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.26816 | val 0.33232
  Epoch 020 - train 0.25045 | val 0.32982
  Epoch 021 - train 0.25415 | val 0.32931
  Regression -> MSE: 0.000169, MAE: 0.009133, R²: -0.1455
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.30629 | val 0.38665
  Epoch 020 - train 0.28670 | val 0.38785
  Epoch 021 - train 0.27749 | val 0.38682
  Regression -> MSE: 0.000248, MAE: 0.011309, R²: -0.0950
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.29970 | val 0.31364
  Epoch 020 - train 0.26661 | val 0.31050
  Epoch 021 - train 0.27389 | val 0.30831
  Regression -> MSE: 0.000163, MAE: 0.009171, R²: -0.0961
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.27169 | val 0.27074
  Epoch 020 - train 0.25870 | val 0.27083
  Epoch 025 - train 0.25714 | val 0.27072
  Regression -> MSE: 0.000209, MAE: 0.011606, R²: -0.1780
  Directional -> Accuracy: 0.4328, MCC: -0.1358, F1: 0.4571

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.27421 | val 0.28037
  Epoch 020 - train 0.28233 | val 0.28185
  Epoch 024 - train 0.28094 | val 0.28094
  Regression -> MSE: 0.000088, MAE: 0.007135, R²: -0.0541
  Directional -> Accuracy: 0.5254, MCC: 0.1068, F1: 0.4815

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.26790 | val 0.28842
  Epoch 020 - train 0.28774 | val 0.30010
  Epoch 021 - train 0.28037 | val 0.30070
  Regression -> MSE: 0.000223, MAE: 0.011276, R²: -0.0201
  Directional -> Accuracy: 0.5224, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.25694 | val 0.21928
  Epoch 020 - train 0.24814 | val 0.21730
  Epoch 021 - train 0.26256 | val 0.21682
  Regression -> MSE: 0.000093, MAE: 0.008143, R²: -0.0155
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28654 | val 0.16626
  Epoch 020 - train 0.28615 | val 0.17941
  Epoch 021 - train 0.27290 | val 0.17367
  Regression -> MSE: 0.000142, MAE: 0.009798, R²: -0.1326
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.29989 | val 0.21372
  Epoch 020 - train 0.29302 | val 0.21483
  Epoch 026 - train 0.29389 | val 0.21174
  Regression -> MSE: 0.000244, MAE: 0.012820, R²: -0.0260
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.30575 | val 0.29075
  Epoch 020 - train 0.28125 | val 0.28491
  Epoch 021 - train 0.27792 | val 0.28617
  Regression -> MSE: 0.000178, MAE: 0.007870, R²: -0.0877
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.29027 | val 0.17183
  Epoch 020 - train 0.27985 | val 0.17107
  Epoch 030 - train 0.26758 | val 0.17083
  Regression -> MSE: 0.000230, MAE: 0.012016, R²: 0.0189
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.24100 | val 0.37387
  Epoch 020 - train 0.25585 | val 0.37494
  Epoch 021 - train 0.26353 | val 0.37328
  Regression -> MSE: 0.000250, MAE: 0.010491, R²: 0.0003
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.26795 | val 0.35412
  Epoch 020 - train 0.26510 | val 0.35244
  Epoch 021 - train 0.29420 | val 0.35576
  Regression -> MSE: 0.000133, MAE: 0.008213, R²: -0.0025
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.28731 | val 0.31717
  Epoch 020 - train 0.26665 | val 0.31622
  Epoch 021 - train 0.25906 | val 0.31556
  Regression -> MSE: 0.000189, MAE: 0.010443, R²: -0.0007
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.23993 | val 0.35383
  Epoch 020 - train 0.24446 | val 0.34652
  Epoch 021 - train 0.24464 | val 0.34866
  Regression -> MSE: 0.000260, MAE: 0.010459, R²: -0.0082
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.27375 | val 0.20326
  Epoch 020 - train 0.21748 | val 0.21506
  Epoch 021 - train 0.23571 | val 0.21533
  Regression -> MSE: 0.000164, MAE: 0.010126, R²: -0.0084
  Directional -> Accuracy: 0.5128, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.25256 | val 0.27810
  Epoch 020 - train 0.25337 | val 0.27785
  Epoch 021 - train 0.25093 | val 0.27688
  Regression -> MSE: 0.000183, MAE: 0.010465, R²: -0.0032
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.26875 | val 0.24081
  Epoch 020 - train 0.26581 | val 0.23112
  Epoch 021 - train 0.25366 | val 0.23072
  Regression -> MSE: 0.000359, MAE: 0.012045, R²: -0.0284
  Directional -> Accuracy: 0.5735, MCC: 0.0000, F1: 0.7290

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.29776 | val 0.17827
  Epoch 020 - train 0.29959 | val 0.17890
  Epoch 021 - train 0.29026 | val 0.17886
  Regression -> MSE: 0.000128, MAE: 0.008390, R²: -0.2298
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.28398 | val 0.39333
  Epoch 020 - train 0.28189 | val 0.38360
  Epoch 021 - train 0.27333 | val 0.38536
  Regression -> MSE: 0.000215, MAE: 0.011168, R²: -0.0007
  Directional -> Accuracy: 0.5345, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.27624 | val 0.50726
  Epoch 020 - train 0.26329 | val 0.51718
  Epoch 021 - train 0.26476 | val 0.51794
  Regression -> MSE: 0.000085, MAE: 0.007236, R²: -0.0711
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.26308 | val 0.17333
  Epoch 020 - train 0.25536 | val 0.17040
  Epoch 028 - train 0.28095 | val 0.17025
  Regression -> MSE: 0.000355, MAE: 0.015384, R²: -0.0809
  Directional -> Accuracy: 0.4750, MCC: 0.0998, F1: 0.5116

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.29346 | val 0.15765
  Epoch 020 - train 0.28857 | val 0.16212
  Epoch 021 - train 0.31747 | val 0.16201
  Regression -> MSE: 0.000244, MAE: 0.011246, R²: -0.0252
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.27868 | val 0.29680
  Epoch 020 - train 0.27443 | val 0.29615
  Epoch 024 - train 0.26758 | val 0.29787
  Regression -> MSE: 0.000085, MAE: 0.007066, R²: -0.0570
  Directional -> Accuracy: 0.4868, MCC: -0.0264, F1: 0.4658

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.29032 | val 0.38678
  Epoch 020 - train 0.27705 | val 0.38013
  Epoch 021 - train 0.28911 | val 0.37707
  Regression -> MSE: 0.000363, MAE: 0.015303, R²: -0.0086
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.27024 | val 0.31821
  Epoch 020 - train 0.27115 | val 0.32962
  Epoch 021 - train 0.28284 | val 0.32558
  Regression -> MSE: 0.000099, MAE: 0.007117, R²: -0.0259
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.31185 | val 0.31309
  Epoch 020 - train 0.28027 | val 0.32899
  Epoch 025 - train 0.30630 | val 0.33013
  Regression -> MSE: 0.000183, MAE: 0.010499, R²: -0.0117
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357


[I 2026-02-24 00:40:42,956] Trial 66 finished with value: -0.01154811683581166 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 1.811452453386132e-05, 'weight_decay': 1.198024496896569e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.43450913346764536, 'early_stopping_min_delta': 0.005014297221740093}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 024 - train 0.28295 | val 0.35658
  Regression -> MSE: 0.000260, MAE: 0.012662, R²: -0.1136
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14426 | val 0.19975
  Epoch 020 - train 0.13635 | val 0.20120
  Epoch 021 - train 0.13611 | val 0.20184
  Regression -> MSE: 0.000247, MAE: 0.012510, R²: 0.0023
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14031 | val 0.15282
  Epoch 020 - train 0.13279 | val 0.16631
  Epoch 021 - train 0.13323 | val 0.16670
  Regression -> MSE: 0.000693, MAE: 0.019525, R²: -0.0127
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15237 | val 0.25124
  Epoch 020 - train 0.15024 | val 0.26166
  Epoch 030 - train 0.14311 | val 0.26351
  Regression -> MSE: 0.000319, MAE: 0.014557, R²: -0.0280
  Directional -> Accuracy: 0.5319, MCC: 0.0504, F1: 0.5926

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11937 | val 0.19646
  Epoch 020 - train 0.11576 | val 0.20661
  Epoch 021 - train 0.11975 | val 0.20341
  Regression -> MSE: 0.000363, MAE: 0.014796, R²: -0.0393
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15282 | val 0.16139
  Epoch 020 - train 0.14082 | val 0.16723
  Epoch 021 - train 0.14292 | val 0.16759
  Regression -> MSE: 0.000209, MAE: 0.010568, R²: -0.0241
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13676 | val 0.28905
  Epoch 020 - train 0.13330 | val 0.30418
  Epoch 030 - train 0.13229 | val 0.31206
  Regression -> MSE: 0.000520, MAE: 0.017613, R²: 0.0634
  Directional -> Accuracy: 0.5745, MCC: 0.1723, F1: 0.6429

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14893 | val 0.20466
  Epoch 020 - train 0.14422 | val 0.20852
  Epoch 021 - train 0.14038 | val 0.20832
  Regression -> MSE: 0.000248, MAE: 0.012425, R²: -0.0118
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14231 | val 0.18867
  Epoch 020 - train 0.13718 | val 0.19846
  Epoch 021 - train 0.13757 | val 0.20088
  Regression -> MSE: 0.000609, MAE: 0.019448, R²: -0.0188
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13804 | val 0.19514
  Epoch 020 - train 0.13020 | val 0.19217
  Epoch 021 - train 0.13084 | val 0.19216
  Regression -> MSE: 0.000385, MAE: 0.016045, R²: -0.0039
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13992 | val 0.20198
  Epoch 020 - train 0.13932 | val 0.20156
  Epoch 021 - train 0.14041 | val 0.20148
  Regression -> MSE: 0.000241, MAE: 0.011741, R²: 0.0012
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13144 | val 0.22339
  Epoch 020 - train 0.12966 | val 0.22722
  Epoch 021 - train 0.12685 | val 0.22789
  Regression -> MSE: 0.000323, MAE: 0.013605, R²: -0.0378
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15139 | val 0.18826
  Epoch 020 - train 0.14651 | val 0.20111
  Epoch 021 - train 0.14641 | val 0.20136
  Regression -> MSE: 0.000679, MAE: 0.019537, R²: -0.0028
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.15071 | val 0.15815
  Epoch 020 - train 0.14881 | val 0.17859
  Epoch 021 - train 0.14560 | val 0.17934
  Regression -> MSE: 0.000147, MAE: 0.009603, R²: -0.0649
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12960 | val 0.20782
  Epoch 020 - train 0.13157 | val 0.20467
  Epoch 021 - train 0.12990 | val 0.20440
  Regression -> MSE: 0.000226, MAE: 0.010723, R²: -0.0060
  Directional -> Accuracy: 0.4754, MCC: -0.1312, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14675 | val 0.34539
  Epoch 020 - train 0.14222 | val 0.37797
  Epoch 021 - train 0.13971 | val 0.37843
  Regression -> MSE: 0.000362, MAE: 0.016051, R²: 0.0011
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15568 | val 0.15135
  Epoch 020 - train 0.14842 | val 0.15164
  Epoch 026 - train 0.14366 | val 0.15306
  Regression -> MSE: 0.000105, MAE: 0.007822, R²: 0.0302
  Directional -> Accuracy: 0.4857, MCC: -0.0725, F1: 0.5909

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14069 | val 0.30114
  Epoch 020 - train 0.13631 | val 0.32556
  Epoch 021 - train 0.13515 | val 0.32588
  Regression -> MSE: 0.000156, MAE: 0.009693, R²: 0.0007
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15412 | val 0.15879
  Epoch 020 - train 0.14738 | val 0.15746
  Epoch 021 - train 0.14981 | val 0.15767
  Regression -> MSE: 0.000274, MAE: 0.012924, R²: -0.0073
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13131 | val 0.20847
  Epoch 020 - train 0.12476 | val 0.20700
  Epoch 021 - train 0.12313 | val 0.20741
  Regression -> MSE: 0.000152, MAE: 0.008738, R²: -0.0177
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14971 | val 0.22063
  Epoch 020 - train 0.14254 | val 0.22249
  Epoch 021 - train 0.14267 | val 0.22277
  Regression -> MSE: 0.000240, MAE: 0.011065, R²: -0.0601
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16347 | val 0.23235
  Epoch 020 - train 0.15779 | val 0.27447
  Epoch 021 - train 0.15675 | val 0.27585
  Regression -> MSE: 0.000160, MAE: 0.009082, R²: -0.1149
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13982 | val 0.17977
  Epoch 020 - train 0.13459 | val 0.17867
  Epoch 030 - train 0.13210 | val 0.17912
  Regression -> MSE: 0.000179, MAE: 0.010994, R²: -0.0848
  Directional -> Accuracy: 0.4697, MCC: -0.0845, F1: 0.6067

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15706 | val 0.18626
  Epoch 020 - train 0.14932 | val 0.18767
  Epoch 021 - train 0.14737 | val 0.18733
  Regression -> MSE: 0.000085, MAE: 0.007039, R²: 0.0037
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14622 | val 0.19688
  Epoch 020 - train 0.14287 | val 0.20457
  Epoch 021 - train 0.13781 | val 0.20692
  Regression -> MSE: 0.000215, MAE: 0.011014, R²: -0.0148
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14109 | val 0.13577
  Epoch 020 - train 0.13094 | val 0.13534
  Epoch 030 - train 0.12176 | val 0.13548
  Regression -> MSE: 0.000097, MAE: 0.007996, R²: -0.0584
  Directional -> Accuracy: 0.5536, MCC: 0.1704, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14836 | val 0.12776
  Epoch 020 - train 0.14411 | val 0.11723
  Epoch 030 - train 0.13383 | val 0.11926
  Regression -> MSE: 0.000105, MAE: 0.008667, R²: -0.0209
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15793 | val 0.16690
  Epoch 020 - train 0.15168 | val 0.18284
  Epoch 021 - train 0.15141 | val 0.18338
  Regression -> MSE: 0.000241, MAE: 0.012882, R²: -0.0421
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14575 | val 0.18051
  Epoch 020 - train 0.14120 | val 0.18396
  Epoch 021 - train 0.13956 | val 0.18403
  Regression -> MSE: 0.000174, MAE: 0.007838, R²: -0.0461
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.15415 | val 0.14139
  Epoch 020 - train 0.15154 | val 0.15373
  Epoch 021 - train 0.15385 | val 0.15444
  Regression -> MSE: 0.000239, MAE: 0.011961, R²: -0.0087
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14642 | val 0.26181
  Epoch 020 - train 0.14464 | val 0.29579
  Epoch 021 - train 0.14922 | val 0.29786
  Regression -> MSE: 0.000231, MAE: 0.009973, R²: -0.0042
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15836 | val 0.18026
  Epoch 020 - train 0.15331 | val 0.18757
  Epoch 021 - train 0.14853 | val 0.18823
  Regression -> MSE: 0.000135, MAE: 0.008173, R²: -0.0028
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14890 | val 0.19877
  Epoch 020 - train 0.14143 | val 0.20401
  Epoch 021 - train 0.13939 | val 0.20420
  Regression -> MSE: 0.000189, MAE: 0.010425, R²: -0.0027
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13106 | val 0.18178
  Epoch 020 - train 0.12716 | val 0.17576
  Epoch 021 - train 0.12740 | val 0.17532
  Regression -> MSE: 0.000268, MAE: 0.010587, R²: -0.0241
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13656 | val 0.13138
  Epoch 020 - train 0.13227 | val 0.13642
  Epoch 021 - train 0.13314 | val 0.13755
  Regression -> MSE: 0.000172, MAE: 0.010398, R²: -0.0295
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13913 | val 0.16442
  Epoch 020 - train 0.13081 | val 0.16741
  Epoch 021 - train 0.13328 | val 0.16706
  Regression -> MSE: 0.000182, MAE: 0.010401, R²: -0.0108
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13632 | val 0.15290
  Epoch 020 - train 0.13360 | val 0.15658
  Epoch 021 - train 0.13064 | val 0.15618
  Regression -> MSE: 0.000345, MAE: 0.012076, R²: -0.0077
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.15980 | val 0.10226
  Epoch 020 - train 0.15125 | val 0.11580
  Epoch 021 - train 0.15366 | val 0.11602
  Regression -> MSE: 0.000115, MAE: 0.008337, R²: -0.0939
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14935 | val 0.22559
  Epoch 020 - train 0.14413 | val 0.23196
  Epoch 021 - train 0.14120 | val 0.23289
  Regression -> MSE: 0.000218, MAE: 0.011274, R²: 0.0012
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14835 | val 0.27258
  Epoch 020 - train 0.14143 | val 0.29686
  Epoch 021 - train 0.13891 | val 0.29787
  Regression -> MSE: 0.000091, MAE: 0.007453, R²: -0.1690
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14249 | val 0.11912
  Epoch 020 - train 0.13259 | val 0.12056
  Epoch 021 - train 0.13399 | val 0.12153
  Regression -> MSE: 0.000317, MAE: 0.014336, R²: -0.0295
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15285 | val 0.09744
  Epoch 020 - train 0.15435 | val 0.11636
  Epoch 021 - train 0.15419 | val 0.11988
  Regression -> MSE: 0.000246, MAE: 0.011555, R²: -0.0078
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13599 | val 0.19806
  Epoch 020 - train 0.13187 | val 0.20182
  Epoch 021 - train 0.13141 | val 0.20227
  Regression -> MSE: 0.000082, MAE: 0.007157, R²: -0.0129
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.15072 | val 0.18926
  Epoch 020 - train 0.14095 | val 0.18527
  Epoch 021 - train 0.14177 | val 0.18572
  Regression -> MSE: 0.000311, MAE: 0.014536, R²: -0.0130
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14122 | val 0.17606
  Epoch 020 - train 0.13302 | val 0.17853
  Epoch 021 - train 0.13597 | val 0.17881
  Regression -> MSE: 0.000099, MAE: 0.007138, R²: -0.0112
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15791 | val 0.19234
  Epoch 020 - train 0.15217 | val 0.20416
  Epoch 021 - train 0.14653 | val 0.20488
  Regression -> MSE: 0.000173, MAE: 0.009464, R²: -0.0057
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13815 | val 0.18450

[I 2026-02-24 00:42:41,399] Trial 67 finished with value: -0.011417446975295486 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 3.8721842935290664e-05, 'weight_decay': 2.1800015824546427e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.24171614177148837, 'early_stopping_min_delta': 0.0063897771793565575}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.14881 | val 0.23896
  Epoch 021 - train 0.15139 | val 0.23924
  Regression -> MSE: 0.000238, MAE: 0.012475, R²: -0.0019
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.17582 | val 0.27678
  Epoch 020 - train 0.16478 | val 0.27535
  Epoch 021 - train 0.16648 | val 0.27595
  Regression -> MSE: 0.000253, MAE: 0.012779, R²: -0.0526
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16918 | val 0.19317
  Epoch 020 - train 0.16228 | val 0.21114
  Epoch 021 - train 0.16057 | val 0.21136
  Regression -> MSE: 0.000703, MAE: 0.019724, R²: -0.0078
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.7324

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.18082 | val 0.32431
  Epoch 020 - train 0.17459 | val 0.32007
  Epoch 030 - train 0.17336 | val 0.32895
  Regression -> MSE: 0.000317, MAE: 0.014393, R²: -0.0076
  Directional -> Accuracy: 0.5000, MCC: -0.0266, F1: 0.6102

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15618 | val 0.20406
  Epoch 020 - train 0.14913 | val 0.21519
  Epoch 021 - train 0.14712 | val 0.21652
  Regression -> MSE: 0.000354, MAE: 0.014668, R²: -0.0013
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.17755 | val 0.18880
  Epoch 020 - train 0.16981 | val 0.19081
  Epoch 021 - train 0.17088 | val 0.19180
  Regression -> MSE: 0.000208, MAE: 0.010135, R²: -0.0078
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.17311 | val 0.36393
  Epoch 020 - train 0.16536 | val 0.37280
  Epoch 021 - train 0.16733 | val 0.37286
  Regression -> MSE: 0.000581, MAE: 0.018554, R²: -0.0275
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.18100 | val 0.24973
  Epoch 020 - train 0.17285 | val 0.24945
  Epoch 021 - train 0.16999 | val 0.25232
  Regression -> MSE: 0.000250, MAE: 0.011979, R²: -0.0067
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.17682 | val 0.17741
  Epoch 020 - train 0.15752 | val 0.20151
  Epoch 021 - train 0.16129 | val 0.20587
  Regression -> MSE: 0.000615, MAE: 0.019537, R²: -0.0072
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.17041 | val 0.25524
  Epoch 020 - train 0.16142 | val 0.26858
  Epoch 021 - train 0.15893 | val 0.26971
  Regression -> MSE: 0.000374, MAE: 0.015759, R²: -0.0021
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.17534 | val 0.27866
  Epoch 020 - train 0.16700 | val 0.28804
  Epoch 021 - train 0.16711 | val 0.28598
  Regression -> MSE: 0.000245, MAE: 0.012064, R²: -0.0021
  Directional -> Accuracy: 0.4203, MCC: 0.0000, F1: 0.5918

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.16029 | val 0.28829
  Epoch 020 - train 0.14790 | val 0.28330
  Epoch 030 - train 0.14802 | val 0.29027
  Regression -> MSE: 0.000317, MAE: 0.013513, R²: -0.0155
  Directional -> Accuracy: 0.4898, MCC: -0.0778, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.18745 | val 0.29096
  Epoch 020 - train 0.17778 | val 0.31728
  Epoch 021 - train 0.17515 | val 0.32045
  Regression -> MSE: 0.000688, MAE: 0.019606, R²: -0.0025
  Directional -> Accuracy: 0.5088, MCC: 0.0744, F1: 0.1250

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17486 | val 0.23977
  Epoch 020 - train 0.16825 | val 0.34003
  Epoch 021 - train 0.16691 | val 0.34821
  Regression -> MSE: 0.000140, MAE: 0.009237, R²: -0.0152
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.16367 | val 0.25099
  Epoch 020 - train 0.15562 | val 0.25538
  Epoch 028 - train 0.14182 | val 0.26111
  Regression -> MSE: 0.000218, MAE: 0.010609, R²: 0.0365
  Directional -> Accuracy: 0.5500, MCC: 0.1028, F1: 0.4906

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.17067 | val 0.42688
  Epoch 020 - train 0.16075 | val 0.43214
  Epoch 021 - train 0.16192 | val 0.43115
  Regression -> MSE: 0.000367, MAE: 0.016253, R²: -0.0000
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.18045 | val 0.23969
  Epoch 020 - train 0.17984 | val 0.25609
  Epoch 021 - train 0.17611 | val 0.26224
  Regression -> MSE: 0.000110, MAE: 0.008165, R²: -0.0176
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.17083 | val 0.39434
  Epoch 020 - train 0.16529 | val 0.41654
  Epoch 021 - train 0.16646 | val 0.41204
  Regression -> MSE: 0.000157, MAE: 0.009643, R²: 0.0023
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.18395 | val 0.20468
  Epoch 020 - train 0.17895 | val 0.20328
  Epoch 021 - train 0.17777 | val 0.20394
  Regression -> MSE: 0.000276, MAE: 0.013161, R²: -0.0066
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.16101 | val 0.26546
  Epoch 020 - train 0.15280 | val 0.26790
  Epoch 021 - train 0.14657 | val 0.26785
  Regression -> MSE: 0.000155, MAE: 0.008879, R²: -0.0223
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.18556 | val 0.29246
  Epoch 020 - train 0.17381 | val 0.29729
  Epoch 021 - train 0.17511 | val 0.29672
  Regression -> MSE: 0.000239, MAE: 0.011053, R²: -0.0504
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17282 | val 0.25671
  Epoch 020 - train 0.16856 | val 0.28825
  Epoch 021 - train 0.16442 | val 0.28798
  Regression -> MSE: 0.000153, MAE: 0.008764, R²: -0.0661
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.16567 | val 0.23499
  Epoch 020 - train 0.15844 | val 0.23342
  Epoch 021 - train 0.15989 | val 0.23292
  Regression -> MSE: 0.000167, MAE: 0.010342, R²: -0.0056
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.18752 | val 0.24190
  Epoch 020 - train 0.18143 | val 0.23977
  Epoch 021 - train 0.18189 | val 0.23975
  Regression -> MSE: 0.000087, MAE: 0.007184, R²: -0.0052
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.17442 | val 0.32023
  Epoch 020 - train 0.17487 | val 0.32302
  Epoch 021 - train 0.16982 | val 0.32889
  Regression -> MSE: 0.000212, MAE: 0.011017, R²: -0.0073
  Directional -> Accuracy: 0.4923, MCC: -0.1163, F1: 0.0571

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.16581 | val 0.17938
  Epoch 020 - train 0.14910 | val 0.17536
  Epoch 030 - train 0.13773 | val 0.17425
  Regression -> MSE: 0.000100, MAE: 0.008064, R²: -0.1068
  Directional -> Accuracy: 0.6364, MCC: 0.2878, F1: 0.6296

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17830 | val 0.18167
  Epoch 020 - train 0.16977 | val 0.19732
  Epoch 021 - train 0.17445 | val 0.20057
  Regression -> MSE: 0.000120, MAE: 0.009280, R²: -0.2013
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.18967 | val 0.18379
  Epoch 020 - train 0.17691 | val 0.19077
  Epoch 021 - train 0.18254 | val 0.19118
  Regression -> MSE: 0.000238, MAE: 0.012842, R²: -0.0030
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.18345 | val 0.22682
  Epoch 020 - train 0.16804 | val 0.22234
  Epoch 030 - train 0.16514 | val 0.22704
  Regression -> MSE: 0.000201, MAE: 0.008595, R²: -0.1876
  Directional -> Accuracy: 0.5357, MCC: 0.1534, F1: 0.4091

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.20103 | val 0.16840
  Epoch 020 - train 0.18763 | val 0.17660
  Epoch 021 - train 0.18851 | val 0.17790
  Regression -> MSE: 0.000242, MAE: 0.012076, R²: 0.0008
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.17959 | val 0.33811
  Epoch 020 - train 0.15965 | val 0.37113
  Epoch 021 - train 0.16842 | val 0.36942
  Regression -> MSE: 0.000238, MAE: 0.010194, R²: -0.0079
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18611 | val 0.24086
  Epoch 020 - train 0.17357 | val 0.26013
  Epoch 021 - train 0.17524 | val 0.26073
  Regression -> MSE: 0.000147, MAE: 0.008863, R²: -0.0700
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.18033 | val 0.26104
  Epoch 020 - train 0.17329 | val 0.25638
  Epoch 030 - train 0.16052 | val 0.25463
  Regression -> MSE: 0.000223, MAE: 0.011809, R²: -0.2185
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15120 | val 0.22989
  Epoch 020 - train 0.13902 | val 0.23053
  Epoch 021 - train 0.14444 | val 0.23082
  Regression -> MSE: 0.000273, MAE: 0.010699, R²: -0.0290
  Directional -> Accuracy: 0.5139, MCC: -0.0691, F1: 0.6535

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15559 | val 0.20450
  Epoch 020 - train 0.14913 | val 0.22992
  Epoch 021 - train 0.15090 | val 0.22958
  Regression -> MSE: 0.000185, MAE: 0.010417, R²: -0.0066
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.17338 | val 0.19490
  Epoch 020 - train 0.16340 | val 0.19622
  Epoch 021 - train 0.16054 | val 0.19554
  Regression -> MSE: 0.000354, MAE: 0.011869, R²: -0.0187
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18780 | val 0.12383
  Epoch 020 - train 0.16622 | val 0.17474
  Epoch 021 - train 0.16642 | val 0.17478
  Regression -> MSE: 0.000120, MAE: 0.008416, R²: -0.1396
  Directional -> Accuracy: 0.4762, MCC: -0.0107, F1: 0.0833

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17474 | val 0.27584
  Epoch 020 - train 0.16709 | val 0.28374
  Epoch 021 - train 0.16187 | val 0.28430
  Regression -> MSE: 0.000221, MAE: 0.011339, R²: -0.0053
  Directional -> Accuracy: 0.4464, MCC: -0.2124, F1: 0.1143

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.17046 | val 0.36048
  Epoch 020 - train 0.16825 | val 0.36466
  Epoch 021 - train 0.16754 | val 0.36511
  Regression -> MSE: 0.000080, MAE: 0.006982, R²: -0.0818
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.18207 | val 0.12955
  Epoch 020 - train 0.16500 | val 0.13216
  Epoch 021 - train 0.16705 | val 0.13243
  Regression -> MSE: 0.000313, MAE: 0.013862, R²: -0.0063
  Directional -> Accuracy: 0.6458, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16686 | val 0.26614
  Epoch 020 - train 0.15718 | val 0.28135
  Epoch 021 - train 0.15908 | val 0.28094
  Regression -> MSE: 0.000078, MAE: 0.006933, R²: -0.0013
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17880 | val 0.25432
  Epoch 020 - train 0.16586 | val 0.27005
  Epoch 030 - train 0.15514 | val 0.28163
  Regression -> MSE: 0.000305, MAE: 0.014386, R²: -0.0139
  Directional -> Accuracy: 0.6000, MCC: 0.2257, F1: 0.6897

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.17055 | val 0.23144
  Epoch 020 - train 0.15727 | val 0.23264
  Epoch 021 - train 0.15759 | val 0.23310
  Regression -> MSE: 0.000103, MAE: 0.007280, R²: -0.0132
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.19673 | val 0.25310
  Epoch 020 - train 0.18375 | val 0.26522
  Epoch 021 - train 0.18509 | val 0.26727
  Regression -> MSE: 0.000182, MAE: 0.010528, R²: -0.0351
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.16110 | val 0.21502
  Epoch 020 - train 0.15542 | val 0.21920
  Epoch 028 - train 0.14944 | val 0.22373
  Regression -> MSE: 0.000237, MAE: 0.012376, R²: -0.0493
  Directional -> Accuracy: 0.4000, MCC: -0.3357, F1: 0.5600

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.18085 | val 0.26847

[I 2026-02-24 00:45:15,834] Trial 68 finished with value: -0.01154028861682709 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 9.410266487342827e-05, 'weight_decay': 4.053255101080198e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.3200881537489577, 'early_stopping_min_delta': 0.006270665788089862}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.17594 | val 0.30624
  Epoch 021 - train 0.17673 | val 0.30603
  Regression -> MSE: 0.000241, MAE: 0.012474, R²: -0.0046
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15159 | val 0.20220
  Epoch 020 - train 0.14447 | val 0.20127
  Epoch 027 - train 0.14543 | val 0.20229
  Regression -> MSE: 0.000252, MAE: 0.012765, R²: -0.0159
  Directional -> Accuracy: 0.4026, MCC: -0.1755, F1: 0.4651

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14825 | val 0.15288
  Epoch 020 - train 0.14345 | val 0.17169
  Epoch 021 - train 0.13634 | val 0.17049
  Regression -> MSE: 0.000715, MAE: 0.019888, R²: -0.0442
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15817 | val 0.27270
  Epoch 020 - train 0.15559 | val 0.27869
  Epoch 021 - train 0.15592 | val 0.27824
  Regression -> MSE: 0.000312, MAE: 0.014427, R²: -0.0045
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13859 | val 0.19090
  Epoch 020 - train 0.13029 | val 0.19118
  Epoch 021 - train 0.12972 | val 0.19268
  Regression -> MSE: 0.000396, MAE: 0.015385, R²: -0.1326
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14820 | val 0.16025
  Epoch 020 - train 0.14360 | val 0.16187
  Epoch 021 - train 0.14425 | val 0.16166
  Regression -> MSE: 0.000203, MAE: 0.010048, R²: 0.0049
  Directional -> Accuracy: 0.6078, MCC: 0.2079, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.14502 | val 0.30293
  Epoch 020 - train 0.13785 | val 0.30989
  Epoch 021 - train 0.13828 | val 0.31062
  Regression -> MSE: 0.000581, MAE: 0.018590, R²: -0.0458
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15898 | val 0.19478
  Epoch 020 - train 0.15278 | val 0.19546
  Epoch 021 - train 0.15227 | val 0.19554
  Regression -> MSE: 0.000246, MAE: 0.011930, R²: -0.0022
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14431 | val 0.21994
  Epoch 020 - train 0.13701 | val 0.23186
  Epoch 021 - train 0.14048 | val 0.23238
  Regression -> MSE: 0.000640, MAE: 0.020082, R²: -0.0710
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14425 | val 0.19861
  Epoch 020 - train 0.12926 | val 0.19727
  Epoch 021 - train 0.13244 | val 0.19779
  Regression -> MSE: 0.000387, MAE: 0.016073, R²: -0.0091
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14736 | val 0.21624
  Epoch 020 - train 0.14259 | val 0.21809
  Epoch 021 - train 0.14341 | val 0.21821
  Regression -> MSE: 0.000242, MAE: 0.011773, R²: -0.0019
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13700 | val 0.22110
  Epoch 020 - train 0.13622 | val 0.22658
  Epoch 027 - train 0.13401 | val 0.22988
  Regression -> MSE: 0.000323, MAE: 0.013613, R²: -0.0384
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15729 | val 0.20209
  Epoch 020 - train 0.15650 | val 0.21751
  Epoch 021 - train 0.15184 | val 0.21934
  Regression -> MSE: 0.000684, MAE: 0.019799, R²: -0.0106
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14716 | val 0.17183
  Epoch 020 - train 0.14259 | val 0.20084
  Epoch 021 - train 0.15048 | val 0.20146
  Regression -> MSE: 0.000138, MAE: 0.009157, R²: -0.0023
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13962 | val 0.20183
  Epoch 020 - train 0.13086 | val 0.20099
  Epoch 028 - train 0.13081 | val 0.19985
  Regression -> MSE: 0.000221, MAE: 0.010532, R²: 0.0191
  Directional -> Accuracy: 0.5410, MCC: 0.0952, F1: 0.4400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15248 | val 0.32716
  Epoch 020 - train 0.14857 | val 0.32376
  Epoch 030 - train 0.14100 | val 0.32540
  Regression -> MSE: 0.000356, MAE: 0.015603, R²: 0.0172
  Directional -> Accuracy: 0.6731, MCC: 0.3563, F1: 0.5405

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16605 | val 0.16420
  Epoch 020 - train 0.15771 | val 0.16321
  Epoch 021 - train 0.15412 | val 0.16273
  Regression -> MSE: 0.000109, MAE: 0.008140, R²: -0.0143
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14499 | val 0.26414
  Epoch 020 - train 0.14046 | val 0.28729
  Epoch 021 - train 0.14132 | val 0.28605
  Regression -> MSE: 0.000156, MAE: 0.009735, R²: -0.0029
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15872 | val 0.17840
  Epoch 020 - train 0.15667 | val 0.17294
  Epoch 021 - train 0.15582 | val 0.17155
  Regression -> MSE: 0.000272, MAE: 0.012936, R²: -0.0014
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13530 | val 0.21914
  Epoch 020 - train 0.13183 | val 0.21605
  Epoch 021 - train 0.13431 | val 0.21642
  Regression -> MSE: 0.000160, MAE: 0.008922, R²: -0.0727
  Directional -> Accuracy: 0.4923, MCC: 0.1307, F1: 0.3265

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15345 | val 0.23468
  Epoch 020 - train 0.14817 | val 0.24143
  Epoch 021 - train 0.14662 | val 0.24201
  Regression -> MSE: 0.000232, MAE: 0.010917, R²: -0.0251
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15496 | val 0.19705
  Epoch 020 - train 0.14870 | val 0.19851
  Epoch 030 - train 0.14633 | val 0.20067
  Regression -> MSE: 0.000149, MAE: 0.008612, R²: -0.0376
  Directional -> Accuracy: 0.6042, MCC: -0.1130, F1: 0.7532

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14437 | val 0.19881
  Epoch 020 - train 0.13568 | val 0.19829
  Epoch 021 - train 0.14065 | val 0.19816
  Regression -> MSE: 0.000168, MAE: 0.010270, R²: -0.0141
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16872 | val 0.19334
  Epoch 020 - train 0.15799 | val 0.18406
  Epoch 030 - train 0.15488 | val 0.18506
  Regression -> MSE: 0.000105, MAE: 0.007905, R²: -0.2315
  Directional -> Accuracy: 0.4483, MCC: 0.0461, F1: 0.1111

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15144 | val 0.19696
  Epoch 020 - train 0.15036 | val 0.20566
  Epoch 021 - train 0.14815 | val 0.20479
  Regression -> MSE: 0.000215, MAE: 0.011436, R²: -0.0150
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13683 | val 0.14879
  Epoch 020 - train 0.13416 | val 0.15135
  Epoch 021 - train 0.12921 | val 0.15122
  Regression -> MSE: 0.000093, MAE: 0.008098, R²: -0.0050
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16149 | val 0.12332
  Epoch 020 - train 0.16132 | val 0.12517
  Epoch 021 - train 0.15841 | val 0.12529
  Regression -> MSE: 0.000104, MAE: 0.008774, R²: -0.0057
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16144 | val 0.15653
  Epoch 020 - train 0.15475 | val 0.15897
  Epoch 021 - train 0.15342 | val 0.15934
  Regression -> MSE: 0.000244, MAE: 0.012943, R²: -0.0537
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14957 | val 0.18843
  Epoch 020 - train 0.14551 | val 0.18869
  Epoch 021 - train 0.14812 | val 0.18899
  Regression -> MSE: 0.000172, MAE: 0.007851, R²: -0.0363
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16700 | val 0.14936
  Epoch 020 - train 0.16721 | val 0.18327
  Epoch 021 - train 0.16754 | val 0.18427
  Regression -> MSE: 0.000240, MAE: 0.011995, R²: -0.0127
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14764 | val 0.25587
  Epoch 020 - train 0.14838 | val 0.27632
  Epoch 021 - train 0.14132 | val 0.27657
  Regression -> MSE: 0.000231, MAE: 0.009890, R²: -0.0023
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15866 | val 0.19964
  Epoch 020 - train 0.15519 | val 0.20959
  Epoch 021 - train 0.15519 | val 0.20992
  Regression -> MSE: 0.000137, MAE: 0.008291, R²: -0.0168
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15661 | val 0.20546
  Epoch 020 - train 0.14686 | val 0.21067
  Epoch 021 - train 0.14800 | val 0.21102
  Regression -> MSE: 0.000188, MAE: 0.010435, R²: -0.0006
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13092 | val 0.18205
  Epoch 020 - train 0.13030 | val 0.18356
  Epoch 021 - train 0.12756 | val 0.18352
  Regression -> MSE: 0.000264, MAE: 0.010508, R²: -0.0095
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15036 | val 0.13402
  Epoch 020 - train 0.13879 | val 0.13856
  Epoch 021 - train 0.14432 | val 0.13945
  Regression -> MSE: 0.000170, MAE: 0.010367, R²: -0.0186
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13965 | val 0.17857
  Epoch 020 - train 0.13833 | val 0.19596
  Epoch 021 - train 0.13452 | val 0.19643
  Regression -> MSE: 0.000184, MAE: 0.010506, R²: -0.0247
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14013 | val 0.15803
  Epoch 020 - train 0.13827 | val 0.16290
  Epoch 021 - train 0.13805 | val 0.16353
  Regression -> MSE: 0.000342, MAE: 0.011840, R²: 0.0033
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16514 | val 0.10669
  Epoch 020 - train 0.15100 | val 0.11960
  Epoch 021 - train 0.15856 | val 0.11838
  Regression -> MSE: 0.000126, MAE: 0.008484, R²: -0.2013
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15282 | val 0.21976
  Epoch 020 - train 0.14897 | val 0.22652
  Epoch 021 - train 0.14608 | val 0.22721
  Regression -> MSE: 0.000219, MAE: 0.011309, R²: -0.0022
  Directional -> Accuracy: 0.5965, MCC: 0.1893, F1: 0.4651

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15609 | val 0.27502
  Epoch 020 - train 0.14473 | val 0.30107
  Epoch 021 - train 0.14428 | val 0.30111
  Regression -> MSE: 0.000095, MAE: 0.007620, R²: -0.2276
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14649 | val 0.13661
  Epoch 020 - train 0.13875 | val 0.13745
  Epoch 021 - train 0.14509 | val 0.13679
  Regression -> MSE: 0.000339, MAE: 0.015327, R²: -0.1009
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.16211 | val 0.09606
  Epoch 020 - train 0.15917 | val 0.10099
  Epoch 021 - train 0.15988 | val 0.10193
  Regression -> MSE: 0.000250, MAE: 0.011507, R²: -0.0238
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14399 | val 0.20481
  Epoch 020 - train 0.14095 | val 0.20778
  Epoch 021 - train 0.13779 | val 0.20800
  Regression -> MSE: 0.000082, MAE: 0.007059, R²: -0.0193
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16297 | val 0.19448
  Epoch 020 - train 0.15650 | val 0.20213
  Epoch 021 - train 0.15590 | val 0.20274
  Regression -> MSE: 0.000313, MAE: 0.014546, R²: -0.0216
  Directional -> Accuracy: 0.4681, MCC: -0.0764, F1: 0.1379

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14864 | val 0.19608
  Epoch 020 - train 0.13675 | val 0.19158
  Epoch 030 - train 0.14098 | val 0.18673
  Regression -> MSE: 0.000099, MAE: 0.006887, R²: -0.0088
  Directional -> Accuracy: 0.6591, MCC: 0.3627, F1: 0.7692

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17078 | val 0.19434
  Epoch 020 - train 0.15894 | val 0.20713
  Epoch 021 - train 0.16331 | val 0.20777
  Regression -> MSE: 0.000172, MAE: 0.009678, R²: -0.0013
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...


[I 2026-02-24 00:47:23,349] Trial 69 finished with value: -0.011509825575347877 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 3.726199443698583e-05, 'weight_decay': 1.9133312758293498e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2492052169871899, 'early_stopping_min_delta': 0.005775485320838675}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.15081 | val 0.22178
  Epoch 021 - train 0.14986 | val 0.22187
  Regression -> MSE: 0.000249, MAE: 0.012462, R²: -0.0500
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 30
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42075 | val 0.74282
  Epoch 020 - train 0.40458 | val 0.75159
  Epoch 021 - train 0.38647 | val 0.76085
  Regression -> MSE: 0.000246, MAE: 0.012457, R²: -0.0280
  Directional -> Accuracy: 0.4800, MCC: 0.1507, F1: 0.6355

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 106). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.44071 | val 0.45775
  Epoch 020 - train 0.40958 | val 0.46991
  Epoch 021 - train 0.39567 | val 0.47292
  Regression -> MSE: 0.000740, MAE: 0.020474, R²: -0.0501
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 106). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.44309 | val 0.83782
  Epoch 020 - train 0.43402 | val 0.83625
  Epoch 021 - train 0.39989 | val 0.83758
  Regression -> MSE: 0.000325, MAE: 0.014832, R²: -0.0115
  Directional -> Accuracy: 0.5333, MCC: 0.0000, F1: 0.6957

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.34002 | val 0.50035
  Epoch 020 - train 0.34515 | val 0.49203
  Epoch 021 - train 0.36057 | val 0.47964
  Regression -> MSE: 0.000387, MAE: 0.015156, R²: -0.0844
  Directional -> Accuracy: 0.4658, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.38818 | val 0.39070
  Epoch 020 - train 0.40870 | val 0.37622
  Epoch 030 - train 0.38641 | val 0.36083
  Regression -> MSE: 0.000208, MAE: 0.010129, R²: 0.0134
  Directional -> Accuracy: 0.5306, MCC: 0.0661, F1: 0.4889

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39663 | val 0.76073
  Epoch 020 - train 0.37763 | val 0.74679
  Epoch 030 - train 0.37397 | val 0.74875
  Regression -> MSE: 0.000594, MAE: 0.018976, R²: -0.0346
  Directional -> Accuracy: 0.5778, MCC: 0.1935, F1: 0.3448

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45228 | val 0.57503
  Epoch 020 - train 0.42409 | val 0.57627
  Epoch 021 - train 0.41461 | val 0.57789
  Regression -> MSE: 0.000253, MAE: 0.012632, R²: -0.0063
  Directional -> Accuracy: 0.4030, MCC: 0.0000, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 106). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 106). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.41023 | val 0.42351
  Epoch 020 - train 0.43680 | val 0.46725
  Epoch 021 - train 0.42940 | val 0.46896
  Regression -> MSE: 0.000663, MAE: 0.020432, R²: -0.0601
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.44477 | val 0.59912
  Epoch 020 - train 0.40055 | val 0.60513
  Epoch 027 - train 0.41701 | val 0.60834
  Regression -> MSE: 0.000412, MAE: 0.016469, R²: -0.1017
  Directional -> Accuracy: 0.3191, MCC: -0.3661, F1: 0.2727

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 106). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 106). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 106). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.43848 | val 0.68340
  Epoch 020 - train 0.42328 | val 0.70932
  Epoch 021 - train 0.40171 | val 0.71094
  Regression -> MSE: 0.000242, MAE: 0.011979, R²: 0.0248
  Directional -> Accuracy: 0.5588, MCC: 0.1234, F1: 0.5312

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41975 | val 0.91135
  Epoch 020 - train 0.38201 | val 0.94823
  Epoch 021 - train 0.39673 | val 0.95003
  Regression -> MSE: 0.000323, MAE: 0.013729, R²: -0.0295
  Directional -> Accuracy: 0.4375, MCC: -0.1015, F1: 0.5091

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.45539 | val 0.59616
  Epoch 020 - train 0.42642 | val 0.63312
  Epoch 021 - train 0.43077 | val 0.63371
  Regression -> MSE: 0.000715, MAE: 0.019985, R²: -0.0249
  Directional -> Accuracy: 0.4821, MCC: -0.1289, F1: 0.6420

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 106). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41284 | val 0.55767
  Epoch 020 - train 0.43545 | val 0.60614
  Epoch 021 - train 0.43540 | val 0.61258
  Regression -> MSE: 0.000144, MAE: 0.009464, R²: -0.0142
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.6575

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 106). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39617 | val 0.69128
  Epoch 020 - train 0.40560 | val 0.68274
  Epoch 021 - train 0.40297 | val 0.68268
  Regression -> MSE: 0.000230, MAE: 0.011050, R²: -0.0044
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.44842 | val 1.11740
  Epoch 020 - train 0.41067 | val 1.14519
  Epoch 021 - train 0.38578 | val 1.14549
  Regression -> MSE: 0.000364, MAE: 0.016109, R²: 0.0064
  Directional -> Accuracy: 0.4400, MCC: -0.0247, F1: 0.6000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.42930 | val 0.55163
  Epoch 020 - train 0.42401 | val 0.51552
  Epoch 021 - train 0.42899 | val 0.52546
  Regression -> MSE: 0.000114, MAE: 0.008144, R²: -0.0508
  Directional -> Accuracy: 0.4412, MCC: -0.1222, F1: 0.0952

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 106). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44235 | val 0.97109
  Epoch 020 - train 0.38836 | val 0.97241
  Epoch 021 - train 0.41528 | val 0.97252
  Regression -> MSE: 0.000150, MAE: 0.009460, R²: -0.0056
  Directional -> Accuracy: 0.6140, MCC: 0.0000, F1: 0.7609

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.41890 | val 0.46487
  Epoch 020 - train 0.43276 | val 0.49426
  Epoch 021 - train 0.40313 | val 0.50039
  Regression -> MSE: 0.000290, MAE: 0.013236, R²: -0.0496
  Directional -> Accuracy: 0.5946, MCC: 0.0000, F1: 0.7458

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38799 | val 0.60212
  Epoch 020 - train 0.36448 | val 0.59967
  Epoch 030 - train 0.31804 | val 0.61049
  Regression -> MSE: 0.000221, MAE: 0.011311, R²: -0.4574
  Directional -> Accuracy: 0.4286, MCC: 0.0076, F1: 0.1429

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 106). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44875 | val 0.77512
  Epoch 020 - train 0.42964 | val 0.74410
  Epoch 030 - train 0.39911 | val 0.74858
  Regression -> MSE: 0.000248, MAE: 0.011459, R²: -0.1031
  Directional -> Accuracy: 0.4521, MCC: -0.0674, F1: 0.3750

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.45276 | val 0.61447
  Epoch 020 - train 0.41568 | val 0.61695
  Epoch 021 - train 0.43243 | val 0.61796
  Regression -> MSE: 0.000152, MAE: 0.008644, R²: -0.0351
  Directional -> Accuracy: 0.5652, MCC: 0.0094, F1: 0.6875

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 106). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 106). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 106). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.37421 | val 0.49922
  Epoch 020 - train 0.37387 | val 0.50942
  Epoch 021 - train 0.37064 | val 0.51193
  Regression -> MSE: 0.000174, MAE: 0.010287, R²: -0.0332
  Directional -> Accuracy: 0.6094, MCC: 0.2242, F1: 0.6479

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.43407 | val 0.54582
  Epoch 020 - train 0.46019 | val 0.55009
  Epoch 021 - train 0.45228 | val 0.55057
  Regression -> MSE: 0.000091, MAE: 0.007369, R²: -0.0403
  Directional -> Accuracy: 0.5714, MCC: 0.2764, F1: 0.4545

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42032 | val 0.77946
  Epoch 020 - train 0.40954 | val 0.93463
  Epoch 021 - train 0.40454 | val 0.92271
  Regression -> MSE: 0.000218, MAE: 0.011251, R²: -0.0194
  Directional -> Accuracy: 0.3594, MCC: -0.3040, F1: 0.4938

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.36756 | val 0.35558
  Epoch 020 - train 0.35612 | val 0.35005
  Epoch 030 - train 0.33275 | val 0.35497
  Regression -> MSE: 0.000109, MAE: 0.008509, R²: -0.1962
  Directional -> Accuracy: 0.5370, MCC: 0.1558, F1: 0.3590

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.43815 | val 0.37973
  Epoch 020 - train 0.44480 | val 0.35680
  Epoch 030 - train 0.37175 | val 0.34563
  Regression -> MSE: 0.000140, MAE: 0.009742, R²: -0.4520
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.5902

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45009 | val 0.25443
  Epoch 020 - train 0.42161 | val 0.25877
  Epoch 023 - train 0.43701 | val 0.25912
  Regression -> MSE: 0.000287, MAE: 0.013284, R²: -0.0535
  Directional -> Accuracy: 0.4490, MCC: -0.1691, F1: 0.5574

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40270 | val 0.55680
  Epoch 020 - train 0.40499 | val 0.54994
  Epoch 021 - train 0.36583 | val 0.55076
  Regression -> MSE: 0.000180, MAE: 0.007860, R²: -0.0596
  Directional -> Accuracy: 0.5455, MCC: 0.1077, F1: 0.5283

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47438 | val 0.31441
  Epoch 020 - train 0.45161 | val 0.30004
  Epoch 030 - train 0.38082 | val 0.28741
  Regression -> MSE: 0.000249, MAE: 0.012274, R²: 0.0102
  Directional -> Accuracy: 0.6579, MCC: 0.2996, F1: 0.7234

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.42733 | val 0.89931
  Epoch 020 - train 0.42203 | val 0.90635
  Epoch 021 - train 0.43929 | val 0.90992
  Regression -> MSE: 0.000233, MAE: 0.009905, R²: 0.0031
  Directional -> Accuracy: 0.5366, MCC: 0.1280, F1: 0.6545

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49980 | val 0.58472
  Epoch 020 - train 0.45069 | val 0.58641
  Epoch 021 - train 0.47156 | val 0.58594
  Regression -> MSE: 0.000146, MAE: 0.008702, R²: -0.0452
  Directional -> Accuracy: 0.4390, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43010 | val 0.57025
  Epoch 020 - train 0.38803 | val 0.56208
  Epoch 030 - train 0.39297 | val 0.56430
  Regression -> MSE: 0.000212, MAE: 0.011446, R²: -0.1357
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37524 | val 0.50751
  Epoch 020 - train 0.35227 | val 0.50533
  Epoch 028 - train 0.34663 | val 0.50752
  Regression -> MSE: 0.000347, MAE: 0.012618, R²: -0.3019
  Directional -> Accuracy: 0.4930, MCC: 0.0939, F1: 0.3077

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 106). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40036 | val 0.47389
  Epoch 020 - train 0.37571 | val 0.49825
  Epoch 021 - train 0.39118 | val 0.49823
  Regression -> MSE: 0.000189, MAE: 0.010699, R²: -0.0073
  Directional -> Accuracy: 0.5476, MCC: 0.1638, F1: 0.0952

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 106). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.42864 | val 0.39193
  Epoch 020 - train 0.41706 | val 0.39493
  Epoch 023 - train 0.38303 | val 0.39414
  Regression -> MSE: 0.000365, MAE: 0.012182, R²: -0.0362
  Directional -> Accuracy: 0.5538, MCC: -0.0015, F1: 0.6947

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.47888 | val 0.19980
  Epoch 020 - train 0.44091 | val 0.20739
  Epoch 025 - train 0.44352 | val 0.20919
  Regression -> MSE: 0.000128, MAE: 0.009015, R²: -0.1692
  Directional -> Accuracy: 0.3250, MCC: -0.3831, F1: 0.4255

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.45345 | val 0.73701
  Epoch 020 - train 0.40713 | val 0.74897
  Epoch 021 - train 0.40300 | val 0.74731
  Regression -> MSE: 0.000221, MAE: 0.011366, R²: 0.0113
  Directional -> Accuracy: 0.4909, MCC: -0.0913, F1: 0.2222

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.44984 | val 1.06903
  Epoch 020 - train 0.40434 | val 1.07166
  Epoch 021 - train 0.38967 | val 1.08365
  Regression -> MSE: 0.000074, MAE: 0.006639, R²: -0.0508
  Directional -> Accuracy: 0.6222, MCC: 0.0787, F1: 0.7536

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 106). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 106). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 106). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 106). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.45670 | val 0.29269
  Epoch 020 - train 0.38708 | val 0.30608
  Epoch 021 - train 0.41299 | val 0.31124
  Regression -> MSE: 0.000318, MAE: 0.013916, R²: 0.0009
  Directional -> Accuracy: 0.6304, MCC: -0.1483, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 106). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 106). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 106). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40450 | val 0.63583
  Epoch 020 - train 0.39111 | val 0.69105
  Epoch 022 - train 0.35506 | val 0.69213
  Regression -> MSE: 0.000075, MAE: 0.006858, R²: 0.0342
  Directional -> Accuracy: 0.4932, MCC: -0.0061, F1: 0.6186

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 106). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 106). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 106). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 106). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.45512 | val 0.67553
  Epoch 020 - train 0.46101 | val 0.67090
  Epoch 021 - train 0.44410 | val 0.66958
  Regression -> MSE: 0.000286, MAE: 0.013949, R²: -0.0261
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42399 | val 0.50066
  Epoch 020 - train 0.44673 | val 0.49344
  Epoch 021 - train 0.42078 | val 0.49342
  Regression -> MSE: 0.000104, MAE: 0.007210, R²: -0.0073
  Directional -> Accuracy: 0.5854, MCC: 0.0000, F1: 0.7385

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.42659 | val 0.64152
  Epoch 020 - train 0.40265 | val 0.65759
  Epoch 021 - train 0.44772 | val 0.65971
  Regression -> MSE: 0.000180, MAE: 0.010148, R²: -0.0077
  Directional -> Accuracy: 0.3696, MCC: 0.0000, F1: 0.5397

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.45562 | val 0.64293
  Epoch 020 - train 0.40762 | val 0.62902
  Epoch 021 - train 0.40393 | val 0.62734
  Regression -> MSE: 0.000251, MAE: 0.012439, R²: -0.1062
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.44412 | val 0.58626

[I 2026-02-24 00:53:27,566] Trial 70 finished with value: -0.011764618083325996 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 30, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 5.938109885838163e-05, 'weight_decay': 6.600251968998939e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.080903688872358, 'early_stopping_min_delta': 0.0069251861323567174}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.42254 | val 0.75148
  Regression -> MSE: 0.000245, MAE: 0.012605, R²: -0.0047
  Directional -> Accuracy: 0.4746, MCC: -0.0095, F1: 0.6353

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09163 | val 0.12200
  Epoch 020 - train 0.08930 | val 0.12087
  Epoch 021 - train 0.08826 | val 0.12065
  Regression -> MSE: 0.000256, MAE: 0.012891, R²: -0.0352
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08980 | val 0.09062
  Epoch 020 - train 0.09064 | val 0.09391
  Epoch 021 - train 0.08885 | val 0.09378
  Regression -> MSE: 0.000701, MAE: 0.019636, R²: -0.0243
  Directional -> Accuracy: 0.3913, MCC: -0.2539, F1: 0.4815

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09114 | val 0.14070
  Epoch 020 - train 0.09048 | val 0.13457
  Epoch 030 - train 0.08779 | val 0.13636
  Regression -> MSE: 0.000323, MAE: 0.014760, R²: -0.0428
  Directional -> Accuracy: 0.4468, MCC: -0.1448, F1: 0.5517

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07655 | val 0.16996
  Epoch 020 - train 0.07546 | val 0.18171
  Epoch 021 - train 0.07347 | val 0.18347
  Regression -> MSE: 0.000352, MAE: 0.014633, R²: -0.0089
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09709 | val 0.11197
  Epoch 020 - train 0.09504 | val 0.12135
  Epoch 021 - train 0.09621 | val 0.12125
  Regression -> MSE: 0.000209, MAE: 0.010605, R²: -0.0286
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08559 | val 0.16330
  Epoch 020 - train 0.08718 | val 0.16107
  Epoch 021 - train 0.08409 | val 0.16143
  Regression -> MSE: 0.000562, MAE: 0.018216, R²: -0.0130
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09046 | val 0.11210
  Epoch 020 - train 0.09211 | val 0.11123
  Epoch 021 - train 0.09027 | val 0.11125
  Regression -> MSE: 0.000250, MAE: 0.011944, R²: -0.0186
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08850 | val 0.13159
  Epoch 020 - train 0.08855 | val 0.12819
  Epoch 021 - train 0.09022 | val 0.12825
  Regression -> MSE: 0.000660, MAE: 0.020405, R²: -0.1051
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08420 | val 0.10743
  Epoch 020 - train 0.08269 | val 0.10753
  Epoch 021 - train 0.08140 | val 0.10754
  Regression -> MSE: 0.000401, MAE: 0.016075, R²: -0.0452
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09029 | val 0.11482
  Epoch 020 - train 0.08673 | val 0.11450
  Epoch 021 - train 0.08692 | val 0.11446
  Regression -> MSE: 0.000246, MAE: 0.011638, R²: -0.0192
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08553 | val 0.13502
  Epoch 020 - train 0.08234 | val 0.14300
  Epoch 021 - train 0.08252 | val 0.14364
  Regression -> MSE: 0.000318, MAE: 0.013598, R²: -0.0219
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09168 | val 0.11454
  Epoch 020 - train 0.09351 | val 0.11840
  Epoch 021 - train 0.08997 | val 0.11850
  Regression -> MSE: 0.000678, MAE: 0.019526, R²: -0.0016
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09153 | val 0.10509
  Epoch 020 - train 0.08908 | val 0.13073
  Epoch 021 - train 0.09021 | val 0.13313
  Regression -> MSE: 0.000139, MAE: 0.009115, R²: -0.0028
  Directional -> Accuracy: 0.4186, MCC: -0.1854, F1: 0.3243

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08076 | val 0.12208
  Epoch 020 - train 0.08163 | val 0.12143
  Epoch 021 - train 0.08184 | val 0.12137
  Regression -> MSE: 0.000227, MAE: 0.010852, R²: -0.0074
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08806 | val 0.17903
  Epoch 020 - train 0.08619 | val 0.18054
  Epoch 021 - train 0.08900 | val 0.18026
  Regression -> MSE: 0.000364, MAE: 0.015982, R²: -0.0050
  Directional -> Accuracy: 0.5577, MCC: 0.0906, F1: 0.2069

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09605 | val 0.10216
  Epoch 020 - train 0.09110 | val 0.09959
  Epoch 021 - train 0.09080 | val 0.09891
  Regression -> MSE: 0.000109, MAE: 0.008093, R²: -0.0081
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09049 | val 0.15730
  Epoch 020 - train 0.08537 | val 0.16044
  Epoch 021 - train 0.08735 | val 0.16030
  Regression -> MSE: 0.000156, MAE: 0.009599, R²: -0.0006
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08998 | val 0.09165
  Epoch 020 - train 0.08934 | val 0.09179
  Epoch 021 - train 0.08918 | val 0.09192
  Regression -> MSE: 0.000282, MAE: 0.013523, R²: -0.0364
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08324 | val 0.12830
  Epoch 020 - train 0.08012 | val 0.12707
  Epoch 021 - train 0.08186 | val 0.12670
  Regression -> MSE: 0.000158, MAE: 0.008862, R²: -0.0545
  Directional -> Accuracy: 0.5385, MCC: 0.1147, F1: 0.5312

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09639 | val 0.14352
  Epoch 020 - train 0.09248 | val 0.14224
  Epoch 021 - train 0.09376 | val 0.14169
  Regression -> MSE: 0.000235, MAE: 0.010986, R²: -0.0387
  Directional -> Accuracy: 0.3867, MCC: -0.2076, F1: 0.2581

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09446 | val 0.12456
  Epoch 020 - train 0.09498 | val 0.14115
  Epoch 021 - train 0.09400 | val 0.14107
  Regression -> MSE: 0.000150, MAE: 0.008688, R²: -0.0483
  Directional -> Accuracy: 0.6042, MCC: 0.1089, F1: 0.7077

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09800 | val 0.12162
  Epoch 020 - train 0.09463 | val 0.12027
  Epoch 021 - train 0.09647 | val 0.12050
  Regression -> MSE: 0.000186, MAE: 0.010416, R²: -0.1228
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09250 | val 0.11349
  Epoch 020 - train 0.09270 | val 0.11448
  Epoch 021 - train 0.09225 | val 0.11438
  Regression -> MSE: 0.000085, MAE: 0.007037, R²: -0.0006
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09356 | val 0.11088
  Epoch 020 - train 0.08959 | val 0.11102
  Epoch 021 - train 0.08970 | val 0.11107
  Regression -> MSE: 0.000212, MAE: 0.011077, R²: -0.0030
  Directional -> Accuracy: 0.5152, MCC: -0.0136, F1: 0.2381

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08307 | val 0.08497
  Epoch 020 - train 0.08277 | val 0.08447
  Epoch 021 - train 0.08320 | val 0.08469
  Regression -> MSE: 0.000097, MAE: 0.008162, R²: -0.0569
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09442 | val 0.07746
  Epoch 020 - train 0.09474 | val 0.07779
  Epoch 021 - train 0.09184 | val 0.07824
  Regression -> MSE: 0.000115, MAE: 0.009180, R²: -0.1180
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09607 | val 0.08759
  Epoch 020 - train 0.09288 | val 0.08794
  Epoch 021 - train 0.09369 | val 0.08812
  Regression -> MSE: 0.000236, MAE: 0.012715, R²: -0.0190
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.08981 | val 0.11425
  Epoch 020 - train 0.08804 | val 0.11559
  Epoch 021 - train 0.08770 | val 0.11585
  Regression -> MSE: 0.000173, MAE: 0.007842, R²: -0.0392
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09658 | val 0.07891
  Epoch 020 - train 0.10215 | val 0.08220
  Epoch 021 - train 0.09683 | val 0.08248
  Regression -> MSE: 0.000239, MAE: 0.011938, R²: -0.0097
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09066 | val 0.14319
  Epoch 020 - train 0.08681 | val 0.14364
  Epoch 021 - train 0.08733 | val 0.14399
  Regression -> MSE: 0.000232, MAE: 0.009954, R²: -0.0050
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09774 | val 0.12066
  Epoch 020 - train 0.09360 | val 0.12773
  Epoch 021 - train 0.09547 | val 0.12769
  Regression -> MSE: 0.000143, MAE: 0.008672, R²: -0.0630
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08900 | val 0.11811
  Epoch 020 - train 0.08815 | val 0.11869
  Epoch 021 - train 0.08791 | val 0.11869
  Regression -> MSE: 0.000188, MAE: 0.010531, R²: 0.0002
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08524 | val 0.10799
  Epoch 020 - train 0.08397 | val 0.10221
  Epoch 021 - train 0.08166 | val 0.10188
  Regression -> MSE: 0.000262, MAE: 0.010612, R²: 0.0004
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08940 | val 0.07776
  Epoch 020 - train 0.08641 | val 0.07904
  Epoch 021 - train 0.08808 | val 0.07943
  Regression -> MSE: 0.000171, MAE: 0.010390, R²: -0.0266
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08523 | val 0.09205
  Epoch 020 - train 0.08072 | val 0.09820
  Epoch 021 - train 0.08169 | val 0.09833
  Regression -> MSE: 0.000183, MAE: 0.010432, R²: -0.0163
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.08547 | val 0.08766
  Epoch 020 - train 0.08395 | val 0.08870
  Epoch 021 - train 0.08245 | val 0.08888
  Regression -> MSE: 0.000343, MAE: 0.011749, R²: -0.0015
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.09973 | val 0.06168
  Epoch 020 - train 0.09878 | val 0.06641
  Epoch 021 - train 0.09990 | val 0.06626
  Regression -> MSE: 0.000123, MAE: 0.008408, R²: -0.1670
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09274 | val 0.12146
  Epoch 020 - train 0.09054 | val 0.12184
  Epoch 021 - train 0.08834 | val 0.12160
  Regression -> MSE: 0.000221, MAE: 0.011355, R²: -0.0095
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09022 | val 0.16647
  Epoch 020 - train 0.09051 | val 0.17956
  Epoch 021 - train 0.08850 | val 0.18010
  Regression -> MSE: 0.000083, MAE: 0.007090, R²: -0.0641
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09044 | val 0.07834
  Epoch 020 - train 0.08828 | val 0.06871
  Epoch 030 - train 0.08402 | val 0.06737
  Regression -> MSE: 0.000348, MAE: 0.015759, R²: -0.1319
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10004 | val 0.05765
  Epoch 020 - train 0.09507 | val 0.06292
  Epoch 021 - train 0.09474 | val 0.06375
  Regression -> MSE: 0.000245, MAE: 0.011579, R²: -0.0069
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08875 | val 0.11477
  Epoch 020 - train 0.08673 | val 0.11547
  Epoch 021 - train 0.08739 | val 0.11557
  Regression -> MSE: 0.000082, MAE: 0.007066, R²: -0.0122
  Directional -> Accuracy: 0.5200, MCC: 0.1178, F1: 0.0526

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.08847 | val 0.11384
  Epoch 020 - train 0.08759 | val 0.10921
  Epoch 021 - train 0.08668 | val 0.10886
  Regression -> MSE: 0.000308, MAE: 0.014514, R²: -0.0028
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08679 | val 0.10355
  Epoch 020 - train 0.08409 | val 0.10320
  Epoch 021 - train 0.08190 | val 0.10291
  Regression -> MSE: 0.000099, MAE: 0.007133, R²: -0.0084
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.09874 | val 0.10516
  Epoch 020 - train 0.09737 | val 0.09998
  Epoch 021 - train 0.09892 | val 0.09994
  Regression -> MSE: 0.000174, MAE: 0.010028, R²: -0.0108
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 00:55:24,044] Trial 71 finished with value: -0.011489693337987576 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 1.0906091201347107e-05, 'weight_decay': 2.1226065549250176e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.13244782052657103, 'early_stopping_min_delta': 0.008102338062015914}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.08724 | val 0.13472
  Epoch 021 - train 0.09084 | val 0.13473
  Regression -> MSE: 0.000237, MAE: 0.012354, R²: -0.0008
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11623 | val 0.14341
  Epoch 020 - train 0.11846 | val 0.14198
  Epoch 021 - train 0.11882 | val 0.14196
  Regression -> MSE: 0.000252, MAE: 0.012746, R²: -0.0190
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11493 | val 0.10089
  Epoch 020 - train 0.11460 | val 0.10142
  Epoch 021 - train 0.11262 | val 0.10182
  Regression -> MSE: 0.000715, MAE: 0.019876, R²: -0.0441
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13192 | val 0.17595
  Epoch 020 - train 0.12471 | val 0.17633
  Epoch 021 - train 0.12536 | val 0.17622
  Regression -> MSE: 0.000310, MAE: 0.014405, R²: 0.0000
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10650 | val 0.12283
  Epoch 020 - train 0.09889 | val 0.12710
  Epoch 021 - train 0.10374 | val 0.12587
  Regression -> MSE: 0.000378, MAE: 0.015055, R²: -0.0820
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13643 | val 0.11500
  Epoch 020 - train 0.11432 | val 0.12043
  Epoch 021 - train 0.12448 | val 0.12054
  Regression -> MSE: 0.000209, MAE: 0.010581, R²: -0.0261
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11824 | val 0.20094
  Epoch 020 - train 0.11897 | val 0.20602
  Epoch 021 - train 0.11166 | val 0.20659
  Regression -> MSE: 0.000595, MAE: 0.018889, R²: -0.0720
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12488 | val 0.14365
  Epoch 020 - train 0.12202 | val 0.14061
  Epoch 021 - train 0.12519 | val 0.14038
  Regression -> MSE: 0.000246, MAE: 0.012160, R²: -0.0003
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11689 | val 0.13785
  Epoch 020 - train 0.11374 | val 0.13712
  Epoch 021 - train 0.10341 | val 0.13725
  Regression -> MSE: 0.000621, MAE: 0.019715, R²: -0.0394
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11564 | val 0.13241
  Epoch 020 - train 0.11114 | val 0.13140
  Epoch 021 - train 0.11404 | val 0.13154
  Regression -> MSE: 0.000390, MAE: 0.015991, R²: -0.0155
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12239 | val 0.15817
  Epoch 020 - train 0.11834 | val 0.15816
  Epoch 021 - train 0.12204 | val 0.15862
  Regression -> MSE: 0.000245, MAE: 0.011660, R²: -0.0160
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11812 | val 0.16382
  Epoch 020 - train 0.11491 | val 0.16748
  Epoch 021 - train 0.11107 | val 0.16822
  Regression -> MSE: 0.000311, MAE: 0.013719, R²: -0.0005
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13439 | val 0.12645
  Epoch 020 - train 0.11715 | val 0.12732
  Epoch 021 - train 0.12668 | val 0.12730
  Regression -> MSE: 0.000687, MAE: 0.019862, R²: -0.0145
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12798 | val 0.11083
  Epoch 020 - train 0.11823 | val 0.12559
  Epoch 021 - train 0.13274 | val 0.12520
  Regression -> MSE: 0.000141, MAE: 0.009326, R²: -0.0205
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11317 | val 0.13959
  Epoch 020 - train 0.10366 | val 0.13915
  Epoch 021 - train 0.10902 | val 0.13864
  Regression -> MSE: 0.000227, MAE: 0.010738, R²: -0.0074
  Directional -> Accuracy: 0.4918, MCC: -0.0043, F1: 0.1143

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12288 | val 0.21946
  Epoch 020 - train 0.12021 | val 0.22238
  Epoch 021 - train 0.11805 | val 0.22209
  Regression -> MSE: 0.000364, MAE: 0.015988, R²: -0.0044
  Directional -> Accuracy: 0.5192, MCC: 0.0000, F1: 0.3243

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11643 | val 0.11820
  Epoch 020 - train 0.11966 | val 0.11937
  Epoch 021 - train 0.11696 | val 0.11925
  Regression -> MSE: 0.000108, MAE: 0.008047, R²: 0.0014
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11348 | val 0.18541
  Epoch 020 - train 0.11859 | val 0.19130
  Epoch 021 - train 0.11574 | val 0.19099
  Regression -> MSE: 0.000159, MAE: 0.010060, R²: -0.0232
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11978 | val 0.11375
  Epoch 020 - train 0.11513 | val 0.11399
  Epoch 021 - train 0.11822 | val 0.11397
  Regression -> MSE: 0.000275, MAE: 0.013222, R²: -0.0120
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11337 | val 0.14247
  Epoch 020 - train 0.10784 | val 0.14216
  Epoch 021 - train 0.10624 | val 0.14225
  Regression -> MSE: 0.000166, MAE: 0.009092, R²: -0.1087
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12821 | val 0.16632
  Epoch 020 - train 0.11738 | val 0.16178
  Epoch 021 - train 0.12209 | val 0.16130
  Regression -> MSE: 0.000228, MAE: 0.010944, R²: -0.0077
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12062 | val 0.13568
  Epoch 020 - train 0.11996 | val 0.13378
  Epoch 021 - train 0.11820 | val 0.13417
  Regression -> MSE: 0.000143, MAE: 0.008292, R²: -0.0004
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11938 | val 0.13515
  Epoch 020 - train 0.10892 | val 0.13440
  Epoch 021 - train 0.12044 | val 0.13427
  Regression -> MSE: 0.000168, MAE: 0.010257, R²: -0.0139
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11783 | val 0.13176
  Epoch 020 - train 0.11837 | val 0.13129
  Epoch 021 - train 0.11513 | val 0.13084
  Regression -> MSE: 0.000086, MAE: 0.007119, R²: -0.0139
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11791 | val 0.15206
  Epoch 020 - train 0.11202 | val 0.15023
  Epoch 021 - train 0.11556 | val 0.15123
  Regression -> MSE: 0.000213, MAE: 0.011236, R²: -0.0046
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12555 | val 0.10889
  Epoch 020 - train 0.11868 | val 0.11081
  Epoch 021 - train 0.11712 | val 0.11002
  Regression -> MSE: 0.000093, MAE: 0.008122, R²: -0.0097
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12427 | val 0.08577
  Epoch 020 - train 0.11993 | val 0.09523
  Epoch 021 - train 0.12026 | val 0.09705
  Regression -> MSE: 0.000109, MAE: 0.009007, R²: -0.0584
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12670 | val 0.10670
  Epoch 020 - train 0.12407 | val 0.10759
  Epoch 021 - train 0.12164 | val 0.10718
  Regression -> MSE: 0.000233, MAE: 0.012505, R²: -0.0061
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10943 | val 0.12795
  Epoch 020 - train 0.11423 | val 0.12764
  Epoch 021 - train 0.11193 | val 0.12752
  Regression -> MSE: 0.000172, MAE: 0.007811, R²: -0.0331
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11801 | val 0.09185
  Epoch 020 - train 0.12064 | val 0.09172
  Epoch 021 - train 0.11850 | val 0.09207
  Regression -> MSE: 0.000237, MAE: 0.011881, R²: -0.0018
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11032 | val 0.18174
  Epoch 020 - train 0.12360 | val 0.20898
  Epoch 021 - train 0.11509 | val 0.20848
  Regression -> MSE: 0.000234, MAE: 0.010117, R²: -0.0149
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11878 | val 0.13128
  Epoch 020 - train 0.12242 | val 0.13128
  Epoch 021 - train 0.10186 | val 0.13157
  Regression -> MSE: 0.000137, MAE: 0.008284, R²: -0.0144
  Directional -> Accuracy: 0.4884, MCC: 0.0724, F1: 0.1538

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11516 | val 0.13844
  Epoch 020 - train 0.11243 | val 0.13901
  Epoch 021 - train 0.11942 | val 0.13901
  Regression -> MSE: 0.000188, MAE: 0.010474, R²: 0.0017
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10272 | val 0.12060
  Epoch 020 - train 0.10157 | val 0.11917
  Epoch 028 - train 0.10656 | val 0.11831
  Regression -> MSE: 0.000270, MAE: 0.011073, R²: -0.0300
  Directional -> Accuracy: 0.5479, MCC: 0.1128, F1: 0.5479

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10816 | val 0.09195
  Epoch 020 - train 0.11244 | val 0.09439
  Epoch 021 - train 0.10505 | val 0.09492
  Regression -> MSE: 0.000168, MAE: 0.010357, R²: -0.0071
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10487 | val 0.10788
  Epoch 020 - train 0.11569 | val 0.10775
  Epoch 021 - train 0.10902 | val 0.10780
  Regression -> MSE: 0.000182, MAE: 0.010357, R²: -0.0128
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11800 | val 0.10588
  Epoch 020 - train 0.11751 | val 0.10620
  Epoch 021 - train 0.11664 | val 0.10604
  Regression -> MSE: 0.000341, MAE: 0.011792, R²: 0.0048
  Directional -> Accuracy: 0.5970, MCC: 0.2264, F1: 0.5846

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11660 | val 0.07087
  Epoch 020 - train 0.12675 | val 0.07434
  Epoch 021 - train 0.11490 | val 0.07417
  Regression -> MSE: 0.000125, MAE: 0.008454, R²: -0.1877
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12620 | val 0.15051
  Epoch 020 - train 0.11767 | val 0.15291
  Epoch 021 - train 0.11281 | val 0.15305
  Regression -> MSE: 0.000221, MAE: 0.011344, R²: -0.0090
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11755 | val 0.18144
  Epoch 020 - train 0.12402 | val 0.18216
  Epoch 021 - train 0.12282 | val 0.18275
  Regression -> MSE: 0.000083, MAE: 0.007087, R²: -0.0636
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10889 | val 0.08973
  Epoch 020 - train 0.11227 | val 0.09787
  Epoch 021 - train 0.12116 | val 0.09849
  Regression -> MSE: 0.000321, MAE: 0.014557, R²: -0.0445
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12035 | val 0.07159
  Epoch 020 - train 0.11991 | val 0.07061
  Epoch 021 - train 0.12426 | val 0.07054
  Regression -> MSE: 0.000257, MAE: 0.011479, R²: -0.0559
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12228 | val 0.13503
  Epoch 020 - train 0.11943 | val 0.13764
  Epoch 021 - train 0.11755 | val 0.13794
  Regression -> MSE: 0.000087, MAE: 0.007094, R²: -0.0740
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12837 | val 0.13142
  Epoch 020 - train 0.12325 | val 0.15658
  Epoch 021 - train 0.12535 | val 0.15671
  Regression -> MSE: 0.000309, MAE: 0.014528, R²: -0.0085
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12112 | val 0.12101
  Epoch 020 - train 0.11944 | val 0.12083
  Epoch 021 - train 0.11751 | val 0.12071
  Regression -> MSE: 0.000099, MAE: 0.007193, R²: -0.0057
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11996 | val 0.13132
  Epoch 020 - train 0.12666 | val 0.13697
  Epoch 021 - train 0.12589 | val 0.13704
  Regression -> MSE: 0.000173, MAE: 0.009524, R²: -0.0044
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 00:57:20,630] Trial 72 finished with value: -0.011465569983107056 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 2.4766765138372175e-05, 'weight_decay': 5.344739534047528e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.16051747595970675, 'early_stopping_min_delta': 0.007083658166261492}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.11509 | val 0.16391
  Epoch 021 - train 0.12078 | val 0.16479
  Regression -> MSE: 0.000237, MAE: 0.012385, R²: -0.0008
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15299 | val 0.19421
  Epoch 020 - train 0.15227 | val 0.19383
  Epoch 021 - train 0.16163 | val 0.19429
  Regression -> MSE: 0.000255, MAE: 0.012866, R²: -0.0318
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.17455 | val 0.14269
  Epoch 020 - train 0.14945 | val 0.15710
  Epoch 021 - train 0.16298 | val 0.15682
  Regression -> MSE: 0.000688, MAE: 0.019411, R²: -0.0051
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.17036 | val 0.24152
  Epoch 020 - train 0.15344 | val 0.25595
  Epoch 021 - train 0.15128 | val 0.25539
  Regression -> MSE: 0.000335, MAE: 0.014659, R²: -0.0792
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14703 | val 0.17691
  Epoch 020 - train 0.14759 | val 0.16934
  Epoch 021 - train 0.14520 | val 0.16636
  Regression -> MSE: 0.000349, MAE: 0.014533, R²: 0.0020
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15847 | val 0.14532
  Epoch 020 - train 0.14845 | val 0.14215
  Epoch 021 - train 0.14808 | val 0.14226
  Regression -> MSE: 0.000204, MAE: 0.010091, R²: -0.0012
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13356 | val 0.27463
  Epoch 020 - train 0.14036 | val 0.29591
  Epoch 021 - train 0.15086 | val 0.29599
  Regression -> MSE: 0.000572, MAE: 0.018405, R²: -0.0308
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16330 | val 0.20098
  Epoch 020 - train 0.16867 | val 0.19913
  Epoch 021 - train 0.15927 | val 0.19864
  Regression -> MSE: 0.000246, MAE: 0.012119, R²: -0.0012
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15324 | val 0.19302
  Epoch 020 - train 0.17486 | val 0.19750
  Epoch 021 - train 0.16279 | val 0.19870
  Regression -> MSE: 0.000636, MAE: 0.020002, R²: -0.0637
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.17344 | val 0.18579
  Epoch 020 - train 0.16383 | val 0.20068
  Epoch 021 - train 0.16587 | val 0.20122
  Regression -> MSE: 0.000384, MAE: 0.016152, R²: -0.0008
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16578 | val 0.20263
  Epoch 020 - train 0.15789 | val 0.20066
  Epoch 021 - train 0.15485 | val 0.19893
  Regression -> MSE: 0.000246, MAE: 0.011655, R²: -0.0202
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15700 | val 0.20219
  Epoch 020 - train 0.15004 | val 0.20752
  Epoch 021 - train 0.15048 | val 0.20730
  Regression -> MSE: 0.000322, MAE: 0.013591, R²: -0.0354
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.17652 | val 0.17675
  Epoch 020 - train 0.16235 | val 0.18370
  Epoch 021 - train 0.16117 | val 0.18265
  Regression -> MSE: 0.000683, MAE: 0.019689, R²: -0.0086
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16811 | val 0.15139
  Epoch 020 - train 0.16545 | val 0.15634
  Epoch 021 - train 0.16720 | val 0.15505
  Regression -> MSE: 0.000138, MAE: 0.009053, R²: -0.0006
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14219 | val 0.18780
  Epoch 020 - train 0.14420 | val 0.18839
  Epoch 021 - train 0.14760 | val 0.18802
  Regression -> MSE: 0.000226, MAE: 0.010708, R²: -0.0058
  Directional -> Accuracy: 0.4426, MCC: -0.2148, F1: 0.6047

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16790 | val 0.28633
  Epoch 020 - train 0.15372 | val 0.28690
  Epoch 021 - train 0.14897 | val 0.28761
  Regression -> MSE: 0.000366, MAE: 0.015979, R²: -0.0104
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15356 | val 0.16616
  Epoch 020 - train 0.15490 | val 0.16427
  Epoch 021 - train 0.15733 | val 0.16327
  Regression -> MSE: 0.000110, MAE: 0.007952, R²: -0.0218
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14385 | val 0.24418
  Epoch 020 - train 0.15416 | val 0.25565
  Epoch 021 - train 0.14618 | val 0.25600
  Regression -> MSE: 0.000157, MAE: 0.009853, R²: -0.0065
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16950 | val 0.16712
  Epoch 020 - train 0.17214 | val 0.17401
  Epoch 021 - train 0.18171 | val 0.17402
  Regression -> MSE: 0.000295, MAE: 0.014035, R²: -0.0858
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14620 | val 0.19259
  Epoch 020 - train 0.14544 | val 0.19194
  Epoch 021 - train 0.13942 | val 0.19169
  Regression -> MSE: 0.000151, MAE: 0.008762, R²: -0.0084
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16884 | val 0.20951
  Epoch 020 - train 0.15924 | val 0.20804
  Epoch 021 - train 0.16761 | val 0.20799
  Regression -> MSE: 0.000227, MAE: 0.010898, R²: -0.0016
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16210 | val 0.20131
  Epoch 020 - train 0.16770 | val 0.24373
  Epoch 021 - train 0.17304 | val 0.24126
  Regression -> MSE: 0.000149, MAE: 0.008626, R²: -0.0364
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14450 | val 0.16634
  Epoch 020 - train 0.14431 | val 0.16457
  Epoch 021 - train 0.14600 | val 0.16478
  Regression -> MSE: 0.000165, MAE: 0.010438, R²: 0.0008
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.17198 | val 0.16750
  Epoch 020 - train 0.16019 | val 0.17082
  Epoch 021 - train 0.17079 | val 0.17078
  Regression -> MSE: 0.000092, MAE: 0.007396, R²: -0.0768
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.17491 | val 0.17246
  Epoch 020 - train 0.16143 | val 0.17284
  Epoch 021 - train 0.17646 | val 0.17270
  Regression -> MSE: 0.000215, MAE: 0.011068, R²: -0.0141
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.15221 | val 0.13027
  Epoch 020 - train 0.15455 | val 0.12889
  Epoch 021 - train 0.14527 | val 0.12954
  Regression -> MSE: 0.000099, MAE: 0.008199, R²: -0.0756
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17457 | val 0.12747
  Epoch 020 - train 0.17334 | val 0.16162
  Epoch 021 - train 0.17132 | val 0.16539
  Regression -> MSE: 0.000118, MAE: 0.009294, R²: -0.1483
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14830 | val 0.13514
  Epoch 020 - train 0.15628 | val 0.13501
  Epoch 021 - train 0.15514 | val 0.13521
  Regression -> MSE: 0.000232, MAE: 0.012563, R²: -0.0024
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15257 | val 0.17128
  Epoch 020 - train 0.14948 | val 0.17111
  Epoch 021 - train 0.14745 | val 0.17088
  Regression -> MSE: 0.000171, MAE: 0.007828, R²: -0.0295
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16067 | val 0.12493
  Epoch 020 - train 0.17191 | val 0.12518
  Epoch 021 - train 0.17360 | val 0.12521
  Regression -> MSE: 0.000238, MAE: 0.011923, R²: -0.0054
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16850 | val 0.24610
  Epoch 020 - train 0.16207 | val 0.30382
  Epoch 021 - train 0.16772 | val 0.30477
  Regression -> MSE: 0.000234, MAE: 0.010136, R²: -0.0170
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16509 | val 0.16275
  Epoch 020 - train 0.16916 | val 0.17977
  Epoch 021 - train 0.17161 | val 0.18004
  Regression -> MSE: 0.000136, MAE: 0.008179, R²: -0.0050
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.16426 | val 0.17549
  Epoch 020 - train 0.16500 | val 0.17349
  Epoch 021 - train 0.17491 | val 0.17359
  Regression -> MSE: 0.000193, MAE: 0.010457, R²: -0.0264
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15521 | val 0.17795
  Epoch 020 - train 0.15577 | val 0.17566
  Epoch 021 - train 0.15011 | val 0.17558
  Regression -> MSE: 0.000264, MAE: 0.010519, R²: -0.0097
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15229 | val 0.12022
  Epoch 020 - train 0.14252 | val 0.12372
  Epoch 021 - train 0.14787 | val 0.12451
  Regression -> MSE: 0.000167, MAE: 0.010381, R²: -0.0038
  Directional -> Accuracy: 0.4211, MCC: -0.2928, F1: 0.5926

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15246 | val 0.16321
  Epoch 020 - train 0.15592 | val 0.17117
  Epoch 021 - train 0.15528 | val 0.17108
  Regression -> MSE: 0.000189, MAE: 0.010679, R²: -0.0524
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14859 | val 0.14144
  Epoch 020 - train 0.15937 | val 0.14302
  Epoch 021 - train 0.15209 | val 0.14293
  Regression -> MSE: 0.000344, MAE: 0.011765, R²: -0.0031
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.17093 | val 0.09340
  Epoch 020 - train 0.15911 | val 0.10200
  Epoch 021 - train 0.17256 | val 0.10179
  Regression -> MSE: 0.000118, MAE: 0.008349, R²: -0.1195
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16652 | val 0.20840
  Epoch 020 - train 0.16368 | val 0.21853
  Epoch 021 - train 0.14630 | val 0.21834
  Regression -> MSE: 0.000223, MAE: 0.011409, R²: -0.0184
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15235 | val 0.24487
  Epoch 020 - train 0.15897 | val 0.25189
  Epoch 021 - train 0.15931 | val 0.25212
  Regression -> MSE: 0.000093, MAE: 0.007526, R²: -0.1940
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14643 | val 0.11029
  Epoch 020 - train 0.15330 | val 0.11727
  Epoch 021 - train 0.14796 | val 0.11834
  Regression -> MSE: 0.000315, MAE: 0.014228, R²: -0.0228
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15046 | val 0.09286
  Epoch 020 - train 0.16180 | val 0.08963
  Epoch 021 - train 0.14128 | val 0.08937
  Regression -> MSE: 0.000260, MAE: 0.011495, R²: -0.0648
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16070 | val 0.17583
  Epoch 020 - train 0.14486 | val 0.17595
  Epoch 021 - train 0.15414 | val 0.17565
  Regression -> MSE: 0.000081, MAE: 0.007068, R²: -0.0042
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16303 | val 0.17321
  Epoch 020 - train 0.16810 | val 0.16801
  Epoch 030 - train 0.14428 | val 0.16830
  Regression -> MSE: 0.000319, MAE: 0.014766, R²: -0.0397
  Directional -> Accuracy: 0.5319, MCC: 0.0745, F1: 0.4500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.15153 | val 0.15351
  Epoch 020 - train 0.16256 | val 0.16518
  Epoch 021 - train 0.14793 | val 0.16660
  Regression -> MSE: 0.000098, MAE: 0.007287, R²: 0.0011
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17719 | val 0.16757
  Epoch 020 - train 0.17106 | val 0.17567
  Epoch 021 - train 0.17625 | val 0.17655
  Regression -> MSE: 0.000172, MAE: 0.009719, R²: 0.0007
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13666 | val 0.16367
  Epoch 020 - train 0.14562 | val 0.16348
  Epoch 021 - train 0.14063 | val 0.16286
  Regression -> MSE: 0.000226, MAE: 0.011826, R²: -0.0129
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000


[I 2026-02-24 00:59:15,780] Trial 73 finished with value: -0.011456768009298093 and parameters: {'feature_set': 'emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 1.4234526252724208e-05, 'weight_decay': 1.2447537521440598e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.218260628725913, 'early_stopping_min_delta': 0.00665119587973574}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.16999 | val 0.20623
  Epoch 021 - train 0.15525 | val 0.20554
  Regression -> MSE: 0.000240, MAE: 0.012326, R²: -0.0134
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.16734 | val 0.24453
  Epoch 020 - train 0.16488 | val 0.24793
  Epoch 021 - train 0.16780 | val 0.24859
  Regression -> MSE: 0.000258, MAE: 0.012980, R²: -0.0506
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16794 | val 0.16075
  Epoch 020 - train 0.16710 | val 0.15857
  Epoch 021 - train 0.16633 | val 0.15768
  Regression -> MSE: 0.000692, MAE: 0.019607, R²: -0.0003
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.17342 | val 0.26236
  Epoch 020 - train 0.17011 | val 0.26386
  Epoch 029 - train 0.16871 | val 0.26651
  Regression -> MSE: 0.000329, MAE: 0.014505, R²: 0.0478
  Directional -> Accuracy: 0.6250, MCC: 0.2845, F1: 0.7353

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13961 | val 0.14154
  Epoch 020 - train 0.13846 | val 0.14590
  Epoch 021 - train 0.13727 | val 0.14775
  Regression -> MSE: 0.000351, MAE: 0.014511, R²: -0.0167
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.18085 | val 0.18218
  Epoch 020 - train 0.17586 | val 0.19578
  Epoch 021 - train 0.17955 | val 0.19543
  Regression -> MSE: 0.000206, MAE: 0.010515, R²: -0.0264
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15600 | val 0.30774
  Epoch 020 - train 0.15405 | val 0.30841
  Epoch 021 - train 0.15586 | val 0.30855
  Regression -> MSE: 0.000585, MAE: 0.018497, R²: -0.0221
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.17299 | val 0.21034
  Epoch 020 - train 0.17346 | val 0.20878
  Epoch 021 - train 0.17146 | val 0.20871
  Regression -> MSE: 0.000246, MAE: 0.011984, R²: 0.0002
  Directional -> Accuracy: 0.5857, MCC: -0.0983, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.17609 | val 0.21309
  Epoch 020 - train 0.17180 | val 0.21218
  Epoch 021 - train 0.17169 | val 0.21312
  Regression -> MSE: 0.000600, MAE: 0.019155, R²: -0.0270
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.16412 | val 0.25680
  Epoch 020 - train 0.16331 | val 0.27067
  Epoch 021 - train 0.16198 | val 0.26970
  Regression -> MSE: 0.000342, MAE: 0.014817, R²: -0.0100
  Directional -> Accuracy: 0.6190, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16831 | val 0.22367
  Epoch 020 - train 0.16444 | val 0.22307
  Epoch 021 - train 0.16456 | val 0.22296
  Regression -> MSE: 0.000245, MAE: 0.011553, R²: -0.0285
  Directional -> Accuracy: 0.5634, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.16256 | val 0.30260
  Epoch 020 - train 0.15776 | val 0.33635
  Epoch 021 - train 0.15502 | val 0.33530
  Regression -> MSE: 0.000306, MAE: 0.013637, R²: 0.0008
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.18656 | val 0.19336
  Epoch 020 - train 0.18421 | val 0.19497
  Epoch 021 - train 0.18375 | val 0.19520
  Regression -> MSE: 0.000671, MAE: 0.019423, R²: -0.0016
  Directional -> Accuracy: 0.4915, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16468 | val 0.16589
  Epoch 020 - train 0.16876 | val 0.17725
  Epoch 021 - train 0.16437 | val 0.17793
  Regression -> MSE: 0.000150, MAE: 0.009472, R²: -0.0013
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.3226

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15705 | val 0.22032
  Epoch 020 - train 0.15213 | val 0.21870
  Epoch 021 - train 0.15398 | val 0.21841
  Regression -> MSE: 0.000225, MAE: 0.010744, R²: -0.0007
  Directional -> Accuracy: 0.5161, MCC: 0.0752, F1: 0.6667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16693 | val 0.35493
  Epoch 020 - train 0.16364 | val 0.38121
  Epoch 021 - train 0.16420 | val 0.38096
  Regression -> MSE: 0.000384, MAE: 0.016326, R²: -0.0224
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.17471 | val 0.18157
  Epoch 020 - train 0.17024 | val 0.18322
  Epoch 021 - train 0.17070 | val 0.18308
  Regression -> MSE: 0.000108, MAE: 0.008082, R²: -0.0190
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.17105 | val 0.27827
  Epoch 020 - train 0.17176 | val 0.27887
  Epoch 021 - train 0.16524 | val 0.27914
  Regression -> MSE: 0.000161, MAE: 0.010054, R²: -0.0066
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16637 | val 0.16898
  Epoch 020 - train 0.16030 | val 0.16686
  Epoch 021 - train 0.16390 | val 0.16644
  Regression -> MSE: 0.000269, MAE: 0.012854, R²: -0.0008
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.15782 | val 0.22724
  Epoch 020 - train 0.15247 | val 0.22635
  Epoch 021 - train 0.15375 | val 0.22656
  Regression -> MSE: 0.000158, MAE: 0.008789, R²: -0.0716
  Directional -> Accuracy: 0.4394, MCC: -0.1177, F1: 0.4789

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.18092 | val 0.23627
  Epoch 020 - train 0.17472 | val 0.24078
  Epoch 021 - train 0.17410 | val 0.24139
  Regression -> MSE: 0.000230, MAE: 0.010933, R²: -0.0130
  Directional -> Accuracy: 0.5395, MCC: 0.0000, F1: 0.7009

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17439 | val 0.20430
  Epoch 020 - train 0.17430 | val 0.21068
  Epoch 021 - train 0.17046 | val 0.20981
  Regression -> MSE: 0.000164, MAE: 0.009237, R²: -0.1031
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15863 | val 0.19803
  Epoch 020 - train 0.15384 | val 0.19791
  Epoch 021 - train 0.15696 | val 0.19736
  Regression -> MSE: 0.000178, MAE: 0.010744, R²: -0.0028
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16903 | val 0.19679
  Epoch 020 - train 0.17165 | val 0.19721
  Epoch 021 - train 0.16808 | val 0.19701
  Regression -> MSE: 0.000085, MAE: 0.007034, R²: -0.0182
  Directional -> Accuracy: 0.5763, MCC: 0.0000, F1: 0.7312

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16680 | val 0.20087
  Epoch 020 - train 0.16470 | val 0.21299
  Epoch 021 - train 0.16474 | val 0.21568
  Regression -> MSE: 0.000219, MAE: 0.011439, R²: 0.0003
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14687 | val 0.14162
  Epoch 020 - train 0.14660 | val 0.14164
  Epoch 021 - train 0.14450 | val 0.14175
  Regression -> MSE: 0.000099, MAE: 0.008233, R²: -0.0847
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16983 | val 0.10228
  Epoch 020 - train 0.16688 | val 0.10891
  Epoch 021 - train 0.16683 | val 0.10977
  Regression -> MSE: 0.000136, MAE: 0.009611, R²: -0.0820
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.17360 | val 0.15483
  Epoch 020 - train 0.16889 | val 0.16047
  Epoch 021 - train 0.17014 | val 0.16097
  Regression -> MSE: 0.000253, MAE: 0.013230, R²: -0.0654
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.16789 | val 0.19911
  Epoch 020 - train 0.16556 | val 0.19807
  Epoch 021 - train 0.16642 | val 0.19773
  Regression -> MSE: 0.000175, MAE: 0.007786, R²: -0.0655
  Directional -> Accuracy: 0.5517, MCC: 0.1844, F1: 0.4348

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.17111 | val 0.13811
  Epoch 020 - train 0.17226 | val 0.14860
  Epoch 021 - train 0.16286 | val 0.14924
  Regression -> MSE: 0.000238, MAE: 0.012069, R²: -0.0171
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.17025 | val 0.24261
  Epoch 020 - train 0.16634 | val 0.23877
  Epoch 021 - train 0.16492 | val 0.23881
  Regression -> MSE: 0.000251, MAE: 0.010460, R²: -0.0024
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18175 | val 0.24064
  Epoch 020 - train 0.17956 | val 0.24849
  Epoch 021 - train 0.17920 | val 0.24867
  Regression -> MSE: 0.000138, MAE: 0.008437, R²: -0.0337
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.18477 | val 0.21438
  Epoch 020 - train 0.18051 | val 0.21680
  Epoch 021 - train 0.18455 | val 0.21701
  Regression -> MSE: 0.000199, MAE: 0.010752, R²: -0.0578
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15418 | val 0.20054
  Epoch 020 - train 0.14970 | val 0.20132
  Epoch 021 - train 0.14801 | val 0.20167
  Regression -> MSE: 0.000264, MAE: 0.010488, R²: -0.0228
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16330 | val 0.17206
  Epoch 020 - train 0.15936 | val 0.18127
  Epoch 021 - train 0.15824 | val 0.18312
  Regression -> MSE: 0.000168, MAE: 0.010263, R²: -0.0338
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.16060 | val 0.18590
  Epoch 020 - train 0.16506 | val 0.19758
  Epoch 021 - train 0.16345 | val 0.19729
  Regression -> MSE: 0.000190, MAE: 0.010757, R²: -0.0401
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16424 | val 0.16278
  Epoch 020 - train 0.16248 | val 0.15930
  Epoch 021 - train 0.16348 | val 0.15854
  Regression -> MSE: 0.000353, MAE: 0.011973, R²: -0.0122
  Directional -> Accuracy: 0.5735, MCC: 0.0000, F1: 0.7290

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.17992 | val 0.11364
  Epoch 020 - train 0.17958 | val 0.11217
  Epoch 021 - train 0.18123 | val 0.11173
  Regression -> MSE: 0.000110, MAE: 0.008235, R²: -0.0620
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17519 | val 0.25690
  Epoch 020 - train 0.17058 | val 0.26412
  Epoch 021 - train 0.17228 | val 0.26186
  Regression -> MSE: 0.000215, MAE: 0.011181, R²: -0.0002
  Directional -> Accuracy: 0.5345, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16252 | val 0.28574
  Epoch 020 - train 0.16069 | val 0.28312
  Epoch 030 - train 0.15834 | val 0.28464
  Regression -> MSE: 0.000087, MAE: 0.007302, R²: -0.0961
  Directional -> Accuracy: 0.5417, MCC: 0.1309, F1: 0.5600

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.16606 | val 0.12886
  Epoch 020 - train 0.16265 | val 0.13363
  Epoch 021 - train 0.16177 | val 0.13329
  Regression -> MSE: 0.000331, MAE: 0.014638, R²: -0.0100
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.18236 | val 0.11121
  Epoch 020 - train 0.18076 | val 0.10913
  Epoch 021 - train 0.17856 | val 0.10899
  Regression -> MSE: 0.000242, MAE: 0.011264, R²: -0.0186
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16509 | val 0.21946
  Epoch 020 - train 0.16114 | val 0.21728
  Epoch 021 - train 0.16270 | val 0.21685
  Regression -> MSE: 0.000081, MAE: 0.007050, R²: -0.0087
  Directional -> Accuracy: 0.5526, MCC: 0.1059, F1: 0.5750

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.18004 | val 0.18496
  Epoch 020 - train 0.17824 | val 0.18455
  Epoch 021 - train 0.17525 | val 0.18434
  Regression -> MSE: 0.000360, MAE: 0.015313, R²: -0.0007
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16046 | val 0.19983
  Epoch 020 - train 0.15944 | val 0.22223
  Epoch 021 - train 0.15841 | val 0.22405
  Regression -> MSE: 0.000097, MAE: 0.007223, R²: -0.0009
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.18346 | val 0.22143
  Epoch 020 - train 0.17890 | val 0.25138
  Epoch 021 - train 0.17525 | val 0.25206
  Regression -> MSE: 0.000182, MAE: 0.009801, R²: -0.0075
  Directional -> Accuracy: 0.6341, MCC: 0.0000, F1: 0.0000


[I 2026-02-24 01:00:40,006] Trial 74 finished with value: -0.011472326482096262 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 7.452727211910089e-06, 'weight_decay': 1.0038570494202866e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2707691547026048, 'early_stopping_min_delta': 0.00861211696650707}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.16770 | val 0.24511
  Epoch 021 - train 0.17017 | val 0.24502
  Regression -> MSE: 0.000245, MAE: 0.012355, R²: -0.0468
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.23685 | val 0.31864
  Epoch 020 - train 0.23231 | val 0.31577
  Epoch 021 - train 0.21329 | val 0.31539
  Regression -> MSE: 0.000250, MAE: 0.012645, R²: -0.0097
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.24981 | val 0.20895
  Epoch 020 - train 0.24209 | val 0.24429
  Epoch 021 - train 0.24340 | val 0.24232
  Regression -> MSE: 0.000718, MAE: 0.019901, R²: -0.0485
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.23929 | val 0.36581
  Epoch 020 - train 0.22864 | val 0.35863
  Epoch 030 - train 0.24062 | val 0.36176
  Regression -> MSE: 0.000295, MAE: 0.013914, R²: 0.0500
  Directional -> Accuracy: 0.6383, MCC: 0.2871, F1: 0.7213

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.20901 | val 0.19988
  Epoch 020 - train 0.19145 | val 0.20121
  Epoch 021 - train 0.20399 | val 0.20075
  Regression -> MSE: 0.000360, MAE: 0.014727, R²: -0.0306
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.24333 | val 0.21848
  Epoch 020 - train 0.22332 | val 0.21742
  Epoch 021 - train 0.23318 | val 0.21686
  Regression -> MSE: 0.000203, MAE: 0.010042, R²: 0.0008
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.24155 | val 0.43191
  Epoch 020 - train 0.22121 | val 0.42650
  Epoch 030 - train 0.24162 | val 0.43723
  Regression -> MSE: 0.000603, MAE: 0.018970, R²: -0.0870
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.24658 | val 0.27330
  Epoch 020 - train 0.23965 | val 0.27306
  Epoch 021 - train 0.23146 | val 0.27463
  Regression -> MSE: 0.000246, MAE: 0.012197, R²: -0.0027
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.23054 | val 0.31547
  Epoch 020 - train 0.21737 | val 0.37270
  Epoch 021 - train 0.21984 | val 0.37788
  Regression -> MSE: 0.000634, MAE: 0.019978, R²: -0.0619
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.23232 | val 0.27590
  Epoch 020 - train 0.24004 | val 0.29667
  Epoch 021 - train 0.21230 | val 0.29728
  Regression -> MSE: 0.000390, MAE: 0.015928, R²: -0.0170
  Directional -> Accuracy: 0.5306, MCC: 0.0818, F1: 0.5490

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.21748 | val 0.29594
  Epoch 020 - train 0.22504 | val 0.30598
  Epoch 021 - train 0.22917 | val 0.30650
  Regression -> MSE: 0.000244, MAE: 0.012219, R²: -0.0090
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.22052 | val 0.34336
  Epoch 020 - train 0.21861 | val 0.33984
  Epoch 021 - train 0.21627 | val 0.34118
  Regression -> MSE: 0.000313, MAE: 0.013819, R²: -0.0058
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.26420 | val 0.26576
  Epoch 020 - train 0.23984 | val 0.27176
  Epoch 021 - train 0.24740 | val 0.27269
  Regression -> MSE: 0.000677, MAE: 0.019466, R²: 0.0002
  Directional -> Accuracy: 0.5345, MCC: 0.1361, F1: 0.1818

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.23198 | val 0.22635
  Epoch 020 - train 0.22287 | val 0.25773
  Epoch 021 - train 0.23100 | val 0.25814
  Regression -> MSE: 0.000139, MAE: 0.009002, R²: -0.0057
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.22154 | val 0.27405
  Epoch 020 - train 0.22791 | val 0.27061
  Epoch 029 - train 0.20996 | val 0.27005
  Regression -> MSE: 0.000232, MAE: 0.010871, R²: -0.0319
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.25406 | val 0.47704
  Epoch 020 - train 0.23544 | val 0.48837
  Epoch 021 - train 0.24418 | val 0.48549
  Regression -> MSE: 0.000369, MAE: 0.015952, R²: -0.0190
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.24759 | val 0.22676
  Epoch 020 - train 0.23844 | val 0.22930
  Epoch 021 - train 0.26250 | val 0.22908
  Regression -> MSE: 0.000111, MAE: 0.007959, R²: -0.0273
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.22778 | val 0.38093
  Epoch 020 - train 0.22268 | val 0.40687
  Epoch 021 - train 0.22428 | val 0.40899
  Regression -> MSE: 0.000157, MAE: 0.009743, R²: -0.0064
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.22530 | val 0.22922
  Epoch 020 - train 0.24076 | val 0.23078
  Epoch 021 - train 0.23267 | val 0.23218
  Regression -> MSE: 0.000291, MAE: 0.013877, R²: -0.0700
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.22190 | val 0.31778
  Epoch 020 - train 0.21179 | val 0.31673
  Epoch 021 - train 0.22726 | val 0.31641
  Regression -> MSE: 0.000153, MAE: 0.008753, R²: -0.0218
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.23974 | val 0.33979
  Epoch 020 - train 0.24220 | val 0.34077
  Epoch 021 - train 0.23085 | val 0.34168
  Regression -> MSE: 0.000226, MAE: 0.010908, R²: 0.0002
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.25956 | val 0.28894
  Epoch 020 - train 0.25304 | val 0.30493
  Epoch 021 - train 0.26355 | val 0.30529
  Regression -> MSE: 0.000149, MAE: 0.008653, R²: -0.0387
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.23238 | val 0.27119
  Epoch 020 - train 0.21136 | val 0.27546
  Epoch 021 - train 0.22591 | val 0.27536
  Regression -> MSE: 0.000168, MAE: 0.010260, R²: -0.0188
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.25331 | val 0.27309
  Epoch 020 - train 0.25896 | val 0.27496
  Epoch 021 - train 0.25246 | val 0.27567
  Regression -> MSE: 0.000093, MAE: 0.007454, R²: -0.0923
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.23509 | val 0.31369
  Epoch 020 - train 0.22979 | val 0.32577
  Epoch 021 - train 0.21720 | val 0.32676
  Regression -> MSE: 0.000213, MAE: 0.011043, R²: -0.0079
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.22598 | val 0.19447
  Epoch 020 - train 0.21153 | val 0.18550
  Epoch 030 - train 0.21692 | val 0.18245
  Regression -> MSE: 0.000094, MAE: 0.007955, R²: -0.0162
  Directional -> Accuracy: 0.5357, MCC: 0.0167, F1: 0.6486

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.23508 | val 0.17389
  Epoch 020 - train 0.23905 | val 0.16887
  Epoch 030 - train 0.22311 | val 0.17097
  Regression -> MSE: 0.000103, MAE: 0.008568, R²: 0.0036
  Directional -> Accuracy: 0.6087, MCC: 0.2539, F1: 0.6250

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.23068 | val 0.21192
  Epoch 020 - train 0.23744 | val 0.21053
  Epoch 021 - train 0.23853 | val 0.21054
  Regression -> MSE: 0.000243, MAE: 0.012914, R²: -0.0482
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.22795 | val 0.25619
  Epoch 020 - train 0.23703 | val 0.24953
  Epoch 030 - train 0.23199 | val 0.25444
  Regression -> MSE: 0.000182, MAE: 0.008121, R²: -0.0952
  Directional -> Accuracy: 0.4737, MCC: -0.0596, F1: 0.5161

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.24530 | val 0.18604
  Epoch 020 - train 0.23796 | val 0.20620
  Epoch 021 - train 0.24362 | val 0.20757
  Regression -> MSE: 0.000237, MAE: 0.011854, R²: -0.0013
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.23121 | val 0.36217
  Epoch 020 - train 0.22401 | val 0.37507
  Epoch 021 - train 0.24213 | val 0.37411
  Regression -> MSE: 0.000231, MAE: 0.009881, R²: -0.0007
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.24539 | val 0.28916
  Epoch 020 - train 0.25900 | val 0.29032
  Epoch 021 - train 0.24898 | val 0.29068
  Regression -> MSE: 0.000143, MAE: 0.008619, R²: -0.0580
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.26708 | val 0.28182
  Epoch 020 - train 0.25119 | val 0.29615
  Epoch 021 - train 0.23376 | val 0.29652
  Regression -> MSE: 0.000206, MAE: 0.010988, R²: -0.0926
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.20708 | val 0.27033
  Epoch 020 - train 0.21064 | val 0.25476
  Epoch 030 - train 0.18921 | val 0.24782
  Regression -> MSE: 0.000328, MAE: 0.012244, R²: -0.2522
  Directional -> Accuracy: 0.5068, MCC: 0.1939, F1: 0.2500

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.20987 | val 0.18271
  Epoch 020 - train 0.23128 | val 0.18969
  Epoch 021 - train 0.23441 | val 0.19115
  Regression -> MSE: 0.000172, MAE: 0.010403, R²: -0.0301
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.24977 | val 0.21986
  Epoch 020 - train 0.20404 | val 0.22783
  Epoch 028 - train 0.21805 | val 0.22661
  Regression -> MSE: 0.000183, MAE: 0.010360, R²: -0.0173
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.20938 | val 0.21331
  Epoch 020 - train 0.21258 | val 0.21357
  Epoch 021 - train 0.22863 | val 0.21335
  Regression -> MSE: 0.000342, MAE: 0.011792, R²: 0.0032
  Directional -> Accuracy: 0.5970, MCC: 0.1641, F1: 0.6667

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.26294 | val 0.13721
  Epoch 020 - train 0.25178 | val 0.15262
  Epoch 021 - train 0.23051 | val 0.15366
  Regression -> MSE: 0.000116, MAE: 0.008347, R²: -0.0997
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.25151 | val 0.31190
  Epoch 020 - train 0.23098 | val 0.31196
  Epoch 021 - train 0.24534 | val 0.31239
  Regression -> MSE: 0.000220, MAE: 0.011336, R²: -0.0069
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.25135 | val 0.38915
  Epoch 020 - train 0.24551 | val 0.38068
  Epoch 030 - train 0.21759 | val 0.38923
  Regression -> MSE: 0.000123, MAE: 0.008750, R²: -0.5859
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.24166 | val 0.17754
  Epoch 020 - train 0.23849 | val 0.16781
  Epoch 030 - train 0.22517 | val 0.16283
  Regression -> MSE: 0.000418, MAE: 0.017529, R²: -0.3590
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.27467 | val 0.13499
  Epoch 020 - train 0.25073 | val 0.13230
  Epoch 021 - train 0.25503 | val 0.13189
  Regression -> MSE: 0.000256, MAE: 0.011469, R²: -0.0516
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.23210 | val 0.29204
  Epoch 020 - train 0.24668 | val 0.29122
  Epoch 021 - train 0.23412 | val 0.28974
  Regression -> MSE: 0.000084, MAE: 0.007047, R²: -0.0395
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.22507 | val 0.27228
  Epoch 020 - train 0.23755 | val 0.29229
  Epoch 021 - train 0.22812 | val 0.29124
  Regression -> MSE: 0.000310, MAE: 0.014521, R²: -0.0101
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.23597 | val 0.25726
  Epoch 020 - train 0.21083 | val 0.25848
  Epoch 021 - train 0.22450 | val 0.25826
  Regression -> MSE: 0.000101, MAE: 0.007113, R²: -0.0302
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.26582 | val 0.27062
  Epoch 020 - train 0.25749 | val 0.27538
  Epoch 021 - train 0.24835 | val 0.27637
  Regression -> MSE: 0.000176, MAE: 0.010270, R²: -0.0264
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.23651 | val 0.24848
  Epoch 020 - train 0.22212 | val 0.25004
  Epoch 021 - train 0.22598 | val 0.24937
  Regression -> MSE: 0.000226, MAE: 0.011826, R²: -0.0123
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.21279 | val 0.24825
  Epoch 020 - train 0.21313 | val 0.24952
  Epoch 021 - train 0.20029 | val 0.24989
  Regression -> MSE: 0.000096, MAE: 0.007916, R²: -0.0427

[I 2026-02-24 01:02:44,361] Trial 75 finished with value: -0.01159302300925526 and parameters: {'feature_set': 'sentinment', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 4.4935838635653526e-05, 'weight_decay': 2.2478427907105597e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.37120320104550575, 'early_stopping_min_delta': 0.007594194555863676}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.24426 | val 0.32458
  Epoch 021 - train 0.24923 | val 0.32555
  Regression -> MSE: 0.000244, MAE: 0.012358, R²: -0.0285
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10894 | val 0.15214
  Epoch 020 - train 0.11498 | val 0.15206
  Epoch 021 - train 0.11214 | val 0.15256
  Regression -> MSE: 0.000249, MAE: 0.012610, R²: -0.0059
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11177 | val 0.12428
  Epoch 020 - train 0.11023 | val 0.15892
  Epoch 021 - train 0.10415 | val 0.15607
  Regression -> MSE: 0.000687, MAE: 0.019386, R²: -0.0037
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11291 | val 0.17253
  Epoch 020 - train 0.11864 | val 0.17312
  Epoch 021 - train 0.11902 | val 0.17278
  Regression -> MSE: 0.000316, MAE: 0.014488, R²: -0.0187
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09309 | val 0.10181
  Epoch 020 - train 0.09610 | val 0.11018
  Epoch 021 - train 0.09701 | val 0.11033
  Regression -> MSE: 0.000349, MAE: 0.014542, R²: -0.0003
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11329 | val 0.10413
  Epoch 020 - train 0.11847 | val 0.10312
  Epoch 021 - train 0.10757 | val 0.10302
  Regression -> MSE: 0.000204, MAE: 0.010209, R²: -0.0008
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11439 | val 0.19175
  Epoch 020 - train 0.10705 | val 0.20851
  Epoch 021 - train 0.10677 | val 0.20867
  Regression -> MSE: 0.000562, MAE: 0.018212, R²: -0.0127
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11381 | val 0.12930
  Epoch 020 - train 0.11152 | val 0.12874
  Epoch 021 - train 0.10858 | val 0.12877
  Regression -> MSE: 0.000246, MAE: 0.012040, R²: -0.0018
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10564 | val 0.15469
  Epoch 020 - train 0.11689 | val 0.16435
  Epoch 021 - train 0.10373 | val 0.16437
  Regression -> MSE: 0.000657, MAE: 0.020344, R²: -0.1001
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10570 | val 0.12728
  Epoch 020 - train 0.10328 | val 0.12666
  Epoch 021 - train 0.10278 | val 0.12654
  Regression -> MSE: 0.000392, MAE: 0.015952, R²: -0.0225
  Directional -> Accuracy: 0.5306, MCC: -0.1303, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12081 | val 0.17458
  Epoch 020 - train 0.12230 | val 0.16388
  Epoch 021 - train 0.11599 | val 0.16316
  Regression -> MSE: 0.000246, MAE: 0.012363, R²: -0.0169
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10174 | val 0.16553
  Epoch 020 - train 0.10402 | val 0.17294
  Epoch 021 - train 0.09526 | val 0.17391
  Regression -> MSE: 0.000310, MAE: 0.013733, R²: 0.0035
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12426 | val 0.12680
  Epoch 020 - train 0.12361 | val 0.12890
  Epoch 021 - train 0.11478 | val 0.12847
  Regression -> MSE: 0.000681, MAE: 0.019526, R²: -0.0055
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10867 | val 0.12309
  Epoch 020 - train 0.10741 | val 0.13672
  Epoch 021 - train 0.10661 | val 0.13668
  Regression -> MSE: 0.000138, MAE: 0.009040, R²: -0.0006
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10533 | val 0.13859
  Epoch 020 - train 0.10337 | val 0.14713
  Epoch 021 - train 0.10073 | val 0.14774
  Regression -> MSE: 0.000227, MAE: 0.010737, R²: -0.0078
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11410 | val 0.21044
  Epoch 020 - train 0.10929 | val 0.21482
  Epoch 021 - train 0.11244 | val 0.21532
  Regression -> MSE: 0.000362, MAE: 0.016013, R²: 0.0004
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11313 | val 0.11031
  Epoch 020 - train 0.11167 | val 0.11038
  Epoch 021 - train 0.11109 | val 0.11063
  Regression -> MSE: 0.000108, MAE: 0.008082, R²: -0.0021
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11524 | val 0.17758
  Epoch 020 - train 0.11218 | val 0.18114
  Epoch 021 - train 0.11541 | val 0.18179
  Regression -> MSE: 0.000156, MAE: 0.009543, R²: -0.0027
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11635 | val 0.11488
  Epoch 020 - train 0.11280 | val 0.11357
  Epoch 021 - train 0.11334 | val 0.11285
  Regression -> MSE: 0.000275, MAE: 0.012930, R²: -0.0107
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09725 | val 0.14835
  Epoch 020 - train 0.09431 | val 0.14379
  Epoch 021 - train 0.10019 | val 0.14313
  Regression -> MSE: 0.000156, MAE: 0.008806, R²: -0.0448
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11540 | val 0.16191
  Epoch 020 - train 0.11053 | val 0.15807
  Epoch 021 - train 0.10970 | val 0.15803
  Regression -> MSE: 0.000228, MAE: 0.010926, R²: -0.0082
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11123 | val 0.13178
  Epoch 020 - train 0.10587 | val 0.13357
  Epoch 021 - train 0.11015 | val 0.13354
  Regression -> MSE: 0.000144, MAE: 0.008395, R²: -0.0049
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10097 | val 0.13107
  Epoch 020 - train 0.10188 | val 0.13160
  Epoch 021 - train 0.10623 | val 0.13186
  Regression -> MSE: 0.000177, MAE: 0.010288, R²: -0.0720
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12704 | val 0.12684
  Epoch 020 - train 0.11323 | val 0.12453
  Epoch 021 - train 0.11718 | val 0.12420
  Regression -> MSE: 0.000093, MAE: 0.007431, R²: -0.0886
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10998 | val 0.14351
  Epoch 020 - train 0.10796 | val 0.14520
  Epoch 021 - train 0.11414 | val 0.14586
  Regression -> MSE: 0.000212, MAE: 0.011108, R²: -0.0018
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11070 | val 0.09638
  Epoch 020 - train 0.10572 | val 0.09382
  Epoch 021 - train 0.10693 | val 0.09388
  Regression -> MSE: 0.000094, MAE: 0.008090, R²: -0.0218
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11430 | val 0.09110
  Epoch 020 - train 0.11749 | val 0.11017
  Epoch 021 - train 0.10778 | val 0.11217
  Regression -> MSE: 0.000113, MAE: 0.009136, R²: -0.0990
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12017 | val 0.10170
  Epoch 020 - train 0.11523 | val 0.10325
  Epoch 021 - train 0.11922 | val 0.10346
  Regression -> MSE: 0.000237, MAE: 0.012733, R²: -0.0218
  Directional -> Accuracy: 0.5814, MCC: 0.1539, F1: 0.6250

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10931 | val 0.13631
  Epoch 020 - train 0.11247 | val 0.13974
  Epoch 021 - train 0.11683 | val 0.13995
  Regression -> MSE: 0.000183, MAE: 0.008009, R²: -0.0980
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11116 | val 0.09018
  Epoch 020 - train 0.10289 | val 0.09112
  Epoch 021 - train 0.11294 | val 0.09142
  Regression -> MSE: 0.000237, MAE: 0.011858, R²: 0.0001
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10171 | val 0.16546
  Epoch 020 - train 0.11521 | val 0.17141
  Epoch 021 - train 0.11089 | val 0.17146
  Regression -> MSE: 0.000231, MAE: 0.009880, R²: -0.0014
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11347 | val 0.12313
  Epoch 020 - train 0.11309 | val 0.12948
  Epoch 021 - train 0.11874 | val 0.12980
  Regression -> MSE: 0.000135, MAE: 0.008184, R²: 0.0017
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11236 | val 0.13135
  Epoch 020 - train 0.11394 | val 0.13173
  Epoch 021 - train 0.11728 | val 0.13150
  Regression -> MSE: 0.000196, MAE: 0.010567, R²: -0.0408
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09901 | val 0.12628
  Epoch 020 - train 0.09765 | val 0.12460
  Epoch 021 - train 0.10158 | val 0.12449
  Regression -> MSE: 0.000263, MAE: 0.010523, R²: -0.0051
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11047 | val 0.08953
  Epoch 020 - train 0.10511 | val 0.09175
  Epoch 021 - train 0.10765 | val 0.09218
  Regression -> MSE: 0.000167, MAE: 0.010373, R²: -0.0035
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10079 | val 0.11921
  Epoch 020 - train 0.10926 | val 0.12881
  Epoch 021 - train 0.10285 | val 0.12823
  Regression -> MSE: 0.000185, MAE: 0.010556, R²: -0.0305
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10567 | val 0.10309
  Epoch 020 - train 0.10463 | val 0.10344
  Epoch 021 - train 0.10818 | val 0.10355
  Regression -> MSE: 0.000350, MAE: 0.012403, R²: -0.0213
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12114 | val 0.07066
  Epoch 020 - train 0.11590 | val 0.06846
  Epoch 021 - train 0.10872 | val 0.06849
  Regression -> MSE: 0.000110, MAE: 0.008320, R²: -0.0484
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11483 | val 0.14199
  Epoch 020 - train 0.11557 | val 0.14519
  Epoch 021 - train 0.11244 | val 0.14474
  Regression -> MSE: 0.000219, MAE: 0.011289, R²: -0.0029
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11347 | val 0.17972
  Epoch 020 - train 0.10626 | val 0.18423
  Epoch 021 - train 0.10599 | val 0.18444
  Regression -> MSE: 0.000086, MAE: 0.007272, R²: -0.1136
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11193 | val 0.08728
  Epoch 020 - train 0.11393 | val 0.10662
  Epoch 021 - train 0.11044 | val 0.10837
  Regression -> MSE: 0.000322, MAE: 0.014625, R²: -0.0466
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12447 | val 0.06580
  Epoch 020 - train 0.12124 | val 0.07006
  Epoch 021 - train 0.11098 | val 0.07096
  Regression -> MSE: 0.000250, MAE: 0.011499, R²: -0.0240
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10328 | val 0.12997
  Epoch 020 - train 0.10314 | val 0.12842
  Epoch 021 - train 0.10464 | val 0.12856
  Regression -> MSE: 0.000084, MAE: 0.007048, R²: -0.0350
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10710 | val 0.12823
  Epoch 020 - train 0.11035 | val 0.14243
  Epoch 021 - train 0.11696 | val 0.14339
  Regression -> MSE: 0.000312, MAE: 0.014547, R²: -0.0172
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10820 | val 0.12784
  Epoch 020 - train 0.10462 | val 0.13122
  Epoch 021 - train 0.11417 | val 0.13154
  Regression -> MSE: 0.000103, MAE: 0.007113, R²: -0.0493
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10954 | val 0.12467
  Epoch 020 - train 0.12493 | val 0.13244
  Epoch 021 - train 0.11714 | val 0.13286
  Regression -> MSE: 0.000173, MAE: 0.009873, R²: -0.0053
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10026 | val 0.11900
  Epoch 020 - train 0.10272 | val 0.12097
  Epoch 021 - train 0.09905 | val 0.12073
  Regression -> MSE: 0.000224, MAE: 0.011782, R²: -0.0036
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11669 | val 0.13871
  Epoch 020 - train 0.11539 | val 0.13976

[I 2026-02-24 01:04:34,954] Trial 76 finished with value: -0.01144208652543097 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 2.030875993549663e-05, 'weight_decay': 4.700762893286967e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.15535445881354515, 'early_stopping_min_delta': 0.008142054376096552}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.11228 | val 0.14477
  Epoch 021 - train 0.10884 | val 0.14466
  Regression -> MSE: 0.000242, MAE: 0.012344, R²: -0.0192
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.22514 | val 0.41080
  Epoch 020 - train 0.21411 | val 0.42830
  Epoch 021 - train 0.23116 | val 0.42980
  Regression -> MSE: 0.000241, MAE: 0.012315, R²: -0.0008
  Directional -> Accuracy: 0.5526, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.23593 | val 0.18089
  Epoch 020 - train 0.21850 | val 0.18514
  Epoch 021 - train 0.23632 | val 0.18609
  Regression -> MSE: 0.000742, MAE: 0.020441, R²: -0.0635
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.23363 | val 0.32751
  Epoch 020 - train 0.22693 | val 0.33185
  Epoch 021 - train 0.24099 | val 0.33152
  Regression -> MSE: 0.000324, MAE: 0.014532, R²: -0.0310
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.19073 | val 0.35957
  Epoch 020 - train 0.21055 | val 0.38020
  Epoch 021 - train 0.19563 | val 0.38581
  Regression -> MSE: 0.000358, MAE: 0.014737, R²: -0.0143
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.21716 | val 0.19583
  Epoch 020 - train 0.22131 | val 0.20123
  Epoch 021 - train 0.21306 | val 0.20246
  Regression -> MSE: 0.000208, MAE: 0.010133, R²: -0.0083
  Directional -> Accuracy: 0.5200, MCC: 0.0000, F1: 0.6842

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.23537 | val 0.35837
  Epoch 020 - train 0.21672 | val 0.37862
  Epoch 021 - train 0.19921 | val 0.37921
  Regression -> MSE: 0.000572, MAE: 0.018368, R²: -0.0103
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.24218 | val 0.27400
  Epoch 020 - train 0.23432 | val 0.27280
  Epoch 021 - train 0.23791 | val 0.27293
  Regression -> MSE: 0.000250, MAE: 0.012314, R²: -0.0066
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.24479 | val 0.16714
  Epoch 020 - train 0.22465 | val 0.16704
  Epoch 021 - train 0.21762 | val 0.16846
  Regression -> MSE: 0.000616, MAE: 0.019539, R²: -0.0075
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.21282 | val 0.23365
  Epoch 020 - train 0.22055 | val 0.23802
  Epoch 021 - train 0.20841 | val 0.23833
  Regression -> MSE: 0.000394, MAE: 0.015859, R²: -0.0555
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.23089 | val 0.26000
  Epoch 020 - train 0.21684 | val 0.25955
  Epoch 021 - train 0.22179 | val 0.25941
  Regression -> MSE: 0.000247, MAE: 0.011824, R²: -0.0085
  Directional -> Accuracy: 0.5797, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.19537 | val 0.29954
  Epoch 020 - train 0.19821 | val 0.29235
  Epoch 030 - train 0.19887 | val 0.29161
  Regression -> MSE: 0.000306, MAE: 0.014006, R²: 0.0193
  Directional -> Accuracy: 0.4490, MCC: -0.0212, F1: 0.6087

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.23110 | val 0.24141
  Epoch 020 - train 0.21494 | val 0.24854
  Epoch 021 - train 0.22652 | val 0.24882
  Regression -> MSE: 0.000697, MAE: 0.019975, R²: -0.0159
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.22389 | val 0.20681
  Epoch 020 - train 0.21629 | val 0.20550
  Epoch 021 - train 0.20466 | val 0.20553
  Regression -> MSE: 0.000140, MAE: 0.009232, R²: -0.0126
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.17743 | val 0.25816
  Epoch 020 - train 0.19558 | val 0.25818
  Epoch 028 - train 0.18350 | val 0.25732
  Regression -> MSE: 0.000224, MAE: 0.010786, R²: 0.0117
  Directional -> Accuracy: 0.4500, MCC: -0.1155, F1: 0.5600

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.21737 | val 0.40561
  Epoch 020 - train 0.21582 | val 0.39875
  Epoch 030 - train 0.20245 | val 0.39815
  Regression -> MSE: 0.000385, MAE: 0.016888, R²: -0.0490
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.22360 | val 0.21063
  Epoch 020 - train 0.23722 | val 0.21282
  Epoch 021 - train 0.23426 | val 0.21206
  Regression -> MSE: 0.000109, MAE: 0.008121, R²: -0.0114
  Directional -> Accuracy: 0.4638, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.21004 | val 0.34172
  Epoch 020 - train 0.20661 | val 0.35557
  Epoch 021 - train 0.20422 | val 0.35595
  Regression -> MSE: 0.000158, MAE: 0.009581, R²: -0.0013
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.21936 | val 0.22640
  Epoch 020 - train 0.21965 | val 0.22710
  Epoch 021 - train 0.23044 | val 0.22792
  Regression -> MSE: 0.000274, MAE: 0.013026, R²: 0.0004
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.19014 | val 0.30187
  Epoch 020 - train 0.21163 | val 0.30661
  Epoch 021 - train 0.20093 | val 0.30765
  Regression -> MSE: 0.000162, MAE: 0.008997, R²: -0.0639
  Directional -> Accuracy: 0.5000, MCC: -0.1376, F1: 0.6444

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.23730 | val 0.29652
  Epoch 020 - train 0.22181 | val 0.29948
  Epoch 025 - train 0.22749 | val 0.29976
  Regression -> MSE: 0.000255, MAE: 0.011413, R²: -0.1217
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.21811 | val 0.25503
  Epoch 020 - train 0.21102 | val 0.27031
  Epoch 021 - train 0.20744 | val 0.27101
  Regression -> MSE: 0.000147, MAE: 0.008477, R²: -0.0212
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.22228 | val 0.24434
  Epoch 020 - train 0.21319 | val 0.24942
  Epoch 021 - train 0.21962 | val 0.24981
  Regression -> MSE: 0.000174, MAE: 0.010291, R²: -0.0507
  Directional -> Accuracy: 0.4923, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.23172 | val 0.24760
  Epoch 020 - train 0.22312 | val 0.25504
  Epoch 021 - train 0.22859 | val 0.25520
  Regression -> MSE: 0.000087, MAE: 0.007149, R²: 0.0015
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.23468 | val 0.29753
  Epoch 020 - train 0.20378 | val 0.29867
  Epoch 021 - train 0.21078 | val 0.29742
  Regression -> MSE: 0.000212, MAE: 0.011288, R²: -0.0071
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.21506 | val 0.19362
  Epoch 020 - train 0.21549 | val 0.19591
  Epoch 021 - train 0.21272 | val 0.19567
  Regression -> MSE: 0.000090, MAE: 0.007976, R²: -0.0062
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.25785 | val 0.18811
  Epoch 020 - train 0.22969 | val 0.21993
  Epoch 021 - train 0.22163 | val 0.22514
  Regression -> MSE: 0.000123, MAE: 0.009396, R²: -0.2364
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.19768 | val 0.19963
  Epoch 020 - train 0.21716 | val 0.26037
  Epoch 021 - train 0.23761 | val 0.25581
  Regression -> MSE: 0.000237, MAE: 0.012802, R²: -0.0007
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.22024 | val 0.23492
  Epoch 020 - train 0.20510 | val 0.24187
  Epoch 021 - train 0.22377 | val 0.24247
  Regression -> MSE: 0.000191, MAE: 0.008184, R²: -0.1286
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22578 | val 0.17139
  Epoch 020 - train 0.22583 | val 0.16539
  Epoch 030 - train 0.22672 | val 0.16907
  Regression -> MSE: 0.000245, MAE: 0.012207, R²: -0.0113
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.22073 | val 0.32196
  Epoch 020 - train 0.22752 | val 0.31646
  Epoch 030 - train 0.20825 | val 0.31630
  Regression -> MSE: 0.000231, MAE: 0.010425, R²: 0.0220
  Directional -> Accuracy: 0.5000, MCC: 0.0561, F1: 0.6316

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.21665 | val 0.21573
  Epoch 020 - train 0.21987 | val 0.21562
  Epoch 021 - train 0.21632 | val 0.21565
  Regression -> MSE: 0.000138, MAE: 0.008308, R²: -0.0014
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.20703 | val 0.26369
  Epoch 020 - train 0.22465 | val 0.26830
  Epoch 021 - train 0.23072 | val 0.26812
  Regression -> MSE: 0.000187, MAE: 0.010246, R²: -0.0234
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.19795 | val 0.26295
  Epoch 020 - train 0.20946 | val 0.25870
  Epoch 021 - train 0.19851 | val 0.25990
  Regression -> MSE: 0.000269, MAE: 0.010609, R²: -0.0146
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.24222 | val 0.20132
  Epoch 020 - train 0.22765 | val 0.22662
  Epoch 029 - train 0.21517 | val 0.22420
  Regression -> MSE: 0.000191, MAE: 0.010651, R²: -0.0394
  Directional -> Accuracy: 0.4884, MCC: -0.0217, F1: 0.5000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.22936 | val 0.19744
  Epoch 020 - train 0.21065 | val 0.20009
  Epoch 021 - train 0.21160 | val 0.20037
  Regression -> MSE: 0.000353, MAE: 0.012438, R²: -0.0155
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.21963 | val 0.12499
  Epoch 020 - train 0.22497 | val 0.14462
  Epoch 021 - train 0.22939 | val 0.14535
  Regression -> MSE: 0.000122, MAE: 0.008454, R²: -0.1579
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.21778 | val 0.28174
  Epoch 020 - train 0.22417 | val 0.27788
  Epoch 021 - train 0.22110 | val 0.27767
  Regression -> MSE: 0.000227, MAE: 0.011474, R²: -0.0308
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.21615 | val 0.35747
  Epoch 020 - train 0.21278 | val 0.35562
  Epoch 021 - train 0.22081 | val 0.35548
  Regression -> MSE: 0.000077, MAE: 0.006846, R²: -0.0461
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.25001 | val 0.14518
  Epoch 020 - train 0.22330 | val 0.15874
  Epoch 021 - train 0.23496 | val 0.15993
  Regression -> MSE: 0.000333, MAE: 0.015021, R²: -0.0692
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.21591 | val 0.27136
  Epoch 020 - train 0.21781 | val 0.27425
  Epoch 021 - train 0.22445 | val 0.27420
  Regression -> MSE: 0.000081, MAE: 0.006892, R²: -0.0327
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.23107 | val 0.25813
  Epoch 020 - train 0.21174 | val 0.28638
  Epoch 021 - train 0.23170 | val 0.28782
  Regression -> MSE: 0.000302, MAE: 0.014382, R²: -0.0030
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.21931 | val 0.24359
  Epoch 020 - train 0.21453 | val 0.23188
  Epoch 030 - train 0.20694 | val 0.23227
  Regression -> MSE: 0.000107, MAE: 0.007355, R²: -0.0478
  Directional -> Accuracy: 0.5714, MCC: 0.0468, F1: 0.7097

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.22668 | val 0.24465
  Epoch 020 - train 0.24124 | val 0.24415
  Epoch 021 - train 0.21143 | val 0.24451
  Regression -> MSE: 0.000178, MAE: 0.010248, R²: -0.0120
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.21766 | val 0.22413
  Epoch 020 - train 0.20842 | val 0.22892
  Epoch 021 - train 0.21483 | val 0.22857
  Regression -> MSE: 0.000227, MAE: 0.011848, R²: -0.0080
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.22313 | val 0.23244
  Epoch 020 - train 0.24230 | val 0.23429
  Epoch 021 - train 0.20824 | val 0.23452
  Regression -> MSE: 0.000094, MAE: 0.007767, R²: -0.0058
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.22577 | val 0.32139
  Epoch 020 - train 0.23667 | val 0.34076
  Epoch 021 - train 0.23072 | val 0.34124
  Regression -> MSE: 0.000167, MAE: 0.010411, R²: -0.0005

[I 2026-02-24 01:07:02,892] Trial 77 finished with value: -0.011561808140824123 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 4.3121727595579626e-06, 'weight_decay': 1.4919379314344994e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.3190161370699097, 'early_stopping_min_delta': 0.0052599202279624635}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.23105 | val 0.36224
  Epoch 021 - train 0.21672 | val 0.36374
  Regression -> MSE: 0.000247, MAE: 0.012482, R²: -0.0294
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13744 | val 0.17530
  Epoch 020 - train 0.14025 | val 0.17672
  Epoch 025 - train 0.13768 | val 0.17595
  Regression -> MSE: 0.000257, MAE: 0.012999, R²: -0.0475
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14714 | val 0.12395
  Epoch 020 - train 0.15003 | val 0.12226
  Epoch 021 - train 0.14184 | val 0.12235
  Regression -> MSE: 0.000695, MAE: 0.019687, R²: -0.0045
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15457 | val 0.23083
  Epoch 020 - train 0.15682 | val 0.24034
  Epoch 021 - train 0.16126 | val 0.24096
  Regression -> MSE: 0.000345, MAE: 0.015122, R²: 0.0006
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13136 | val 0.22654
  Epoch 020 - train 0.12769 | val 0.22869
  Epoch 021 - train 0.12962 | val 0.22648
  Regression -> MSE: 0.000365, MAE: 0.014717, R²: -0.0591
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15046 | val 0.14002
  Epoch 020 - train 0.15437 | val 0.14272
  Epoch 021 - train 0.15615 | val 0.14323
  Regression -> MSE: 0.000202, MAE: 0.009959, R²: -0.0093
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13362 | val 0.25412
  Epoch 020 - train 0.13655 | val 0.26657
  Epoch 021 - train 0.13650 | val 0.26692
  Regression -> MSE: 0.000582, MAE: 0.018458, R²: -0.0172
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15069 | val 0.17465
  Epoch 020 - train 0.15094 | val 0.17474
  Epoch 021 - train 0.15311 | val 0.17459
  Regression -> MSE: 0.000247, MAE: 0.011993, R²: -0.0049
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15067 | val 0.17685
  Epoch 020 - train 0.15540 | val 0.19573
  Epoch 021 - train 0.15612 | val 0.19907
  Regression -> MSE: 0.000595, MAE: 0.019036, R²: -0.0172
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13600 | val 0.21181
  Epoch 020 - train 0.14335 | val 0.21827
  Epoch 021 - train 0.13822 | val 0.21744
  Regression -> MSE: 0.000339, MAE: 0.015117, R²: -0.0025
  Directional -> Accuracy: 0.3810, MCC: 0.0000, F1: 0.5517

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14620 | val 0.18771
  Epoch 020 - train 0.15044 | val 0.18848
  Epoch 021 - train 0.14774 | val 0.18846
  Regression -> MSE: 0.000239, MAE: 0.011636, R²: -0.0040
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14868 | val 0.18733
  Epoch 020 - train 0.14598 | val 0.18527
  Epoch 029 - train 0.14432 | val 0.18530
  Regression -> MSE: 0.000359, MAE: 0.014646, R²: -0.1733
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15441 | val 0.18437
  Epoch 020 - train 0.15304 | val 0.19473
  Epoch 021 - train 0.15535 | val 0.19415
  Regression -> MSE: 0.000670, MAE: 0.019430, R²: -0.0014
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14959 | val 0.13893
  Epoch 020 - train 0.14709 | val 0.14800
  Epoch 021 - train 0.14911 | val 0.14842
  Regression -> MSE: 0.000152, MAE: 0.009708, R²: -0.0116
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13565 | val 0.17780
  Epoch 020 - train 0.13345 | val 0.17855
  Epoch 028 - train 0.14028 | val 0.17831
  Regression -> MSE: 0.000230, MAE: 0.010920, R²: -0.0227
  Directional -> Accuracy: 0.4355, MCC: -0.2182, F1: 0.0541

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14680 | val 0.28018
  Epoch 020 - train 0.14818 | val 0.28072
  Epoch 021 - train 0.14752 | val 0.28086
  Regression -> MSE: 0.000394, MAE: 0.016327, R²: -0.0481
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15220 | val 0.17237
  Epoch 020 - train 0.15295 | val 0.17244
  Epoch 021 - train 0.14700 | val 0.17331
  Regression -> MSE: 0.000108, MAE: 0.008048, R²: -0.0126
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14439 | val 0.22584
  Epoch 020 - train 0.14414 | val 0.22597
  Epoch 021 - train 0.14088 | val 0.22585
  Regression -> MSE: 0.000161, MAE: 0.010096, R²: -0.0085
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13794 | val 0.15100
  Epoch 020 - train 0.14205 | val 0.15165
  Epoch 021 - train 0.13839 | val 0.15077
  Regression -> MSE: 0.000269, MAE: 0.012893, R²: -0.0009
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13663 | val 0.19933
  Epoch 020 - train 0.13712 | val 0.20009
  Epoch 021 - train 0.13964 | val 0.20042
  Regression -> MSE: 0.000160, MAE: 0.008869, R²: -0.0846
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15387 | val 0.21494
  Epoch 020 - train 0.15853 | val 0.21423
  Epoch 021 - train 0.15402 | val 0.21422
  Regression -> MSE: 0.000236, MAE: 0.011033, R²: -0.0391
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15934 | val 0.16843
  Epoch 020 - train 0.15016 | val 0.17270
  Epoch 021 - train 0.15692 | val 0.17296
  Regression -> MSE: 0.000153, MAE: 0.008811, R²: -0.0331
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14011 | val 0.17273
  Epoch 020 - train 0.14113 | val 0.17433
  Epoch 021 - train 0.13869 | val 0.17414
  Regression -> MSE: 0.000179, MAE: 0.010654, R²: -0.0130
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15296 | val 0.17687
  Epoch 020 - train 0.15160 | val 0.18193
  Epoch 021 - train 0.15481 | val 0.18089
  Regression -> MSE: 0.000086, MAE: 0.007066, R²: -0.0241
  Directional -> Accuracy: 0.5763, MCC: 0.0289, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14745 | val 0.17195
  Epoch 020 - train 0.14587 | val 0.17181
  Epoch 021 - train 0.14700 | val 0.17238
  Regression -> MSE: 0.000219, MAE: 0.011510, R²: -0.0029
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13179 | val 0.12015
  Epoch 020 - train 0.13505 | val 0.12023
  Epoch 021 - train 0.14033 | val 0.12049
  Regression -> MSE: 0.000100, MAE: 0.008242, R²: -0.0917
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14730 | val 0.09138
  Epoch 020 - train 0.14728 | val 0.09600
  Epoch 021 - train 0.14776 | val 0.09715
  Regression -> MSE: 0.000149, MAE: 0.009995, R²: -0.1859
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15685 | val 0.12915
  Epoch 020 - train 0.15431 | val 0.14331
  Epoch 021 - train 0.15870 | val 0.14401
  Regression -> MSE: 0.000244, MAE: 0.012974, R²: -0.0269
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15086 | val 0.17166
  Epoch 020 - train 0.14384 | val 0.17372
  Epoch 021 - train 0.14777 | val 0.17391
  Regression -> MSE: 0.000171, MAE: 0.007761, R²: -0.0435
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14654 | val 0.10934
  Epoch 020 - train 0.15028 | val 0.10599
  Epoch 021 - train 0.14714 | val 0.10568
  Regression -> MSE: 0.000234, MAE: 0.011924, R²: -0.0007
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.15489 | val 0.19813
  Epoch 020 - train 0.14913 | val 0.19079
  Epoch 030 - train 0.15098 | val 0.19103
  Regression -> MSE: 0.000259, MAE: 0.010649, R²: -0.0371
  Directional -> Accuracy: 0.4667, MCC: -0.0672, F1: 0.4783

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16251 | val 0.21622
  Epoch 020 - train 0.16377 | val 0.25512
  Epoch 021 - train 0.16866 | val 0.25579
  Regression -> MSE: 0.000141, MAE: 0.008659, R²: -0.0571
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14833 | val 0.18138
  Epoch 020 - train 0.13925 | val 0.18191
  Epoch 021 - train 0.14569 | val 0.18195
  Regression -> MSE: 0.000188, MAE: 0.010499, R²: 0.0012
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12691 | val 0.16987
  Epoch 020 - train 0.12883 | val 0.16968
  Epoch 021 - train 0.12459 | val 0.16985
  Regression -> MSE: 0.000272, MAE: 0.010707, R²: -0.0519
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13398 | val 0.12649
  Epoch 020 - train 0.13398 | val 0.12210
  Epoch 030 - train 0.13338 | val 0.12102
  Regression -> MSE: 0.000158, MAE: 0.010046, R²: 0.0291
  Directional -> Accuracy: 0.5641, MCC: 0.1289, F1: 0.5641

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15532 | val 0.16684
  Epoch 020 - train 0.14954 | val 0.19267
  Epoch 021 - train 0.15773 | val 0.19323
  Regression -> MSE: 0.000195, MAE: 0.010902, R²: -0.0668
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14139 | val 0.13588
  Epoch 020 - train 0.13762 | val 0.13653
  Epoch 021 - train 0.14066 | val 0.13649
  Regression -> MSE: 0.000352, MAE: 0.011935, R²: -0.0089
  Directional -> Accuracy: 0.5735, MCC: 0.0000, F1: 0.7290

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.15580 | val 0.09930
  Epoch 020 - train 0.15553 | val 0.09906
  Epoch 021 - train 0.15376 | val 0.09946
  Regression -> MSE: 0.000125, MAE: 0.008364, R²: -0.2020
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15430 | val 0.19073
  Epoch 020 - train 0.15546 | val 0.19173
  Epoch 021 - train 0.15261 | val 0.19193
  Regression -> MSE: 0.000215, MAE: 0.011179, R²: -0.0016
  Directional -> Accuracy: 0.5345, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15050 | val 0.23608
  Epoch 020 - train 0.14511 | val 0.24601
  Epoch 021 - train 0.14177 | val 0.24603
  Regression -> MSE: 0.000097, MAE: 0.007733, R²: -0.2219
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14280 | val 0.11144
  Epoch 020 - train 0.13966 | val 0.11639
  Epoch 021 - train 0.13730 | val 0.11627
  Regression -> MSE: 0.000331, MAE: 0.014699, R²: -0.0100
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14817 | val 0.10169
  Epoch 020 - train 0.15346 | val 0.09966
  Epoch 021 - train 0.14766 | val 0.09941
  Regression -> MSE: 0.000249, MAE: 0.011190, R²: -0.0469
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14344 | val 0.17175
  Epoch 020 - train 0.13884 | val 0.17202
  Epoch 021 - train 0.14508 | val 0.17209
  Regression -> MSE: 0.000080, MAE: 0.007068, R²: -0.0007
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14745 | val 0.17020
  Epoch 020 - train 0.15246 | val 0.21168
  Epoch 021 - train 0.15576 | val 0.21324
  Regression -> MSE: 0.000366, MAE: 0.015325, R²: -0.0178
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13700 | val 0.17859
  Epoch 020 - train 0.13518 | val 0.18436
  Epoch 021 - train 0.14192 | val 0.18449
  Regression -> MSE: 0.000099, MAE: 0.007109, R²: -0.0280
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15841 | val 0.17777
  Epoch 020 - train 0.15658 | val 0.18201
  Epoch 021 - train 0.16419 | val 0.18160
  Regression -> MSE: 0.000183, MAE: 0.009804, R²: -0.0104
  Directional -> Accuracy: 0.6341, MCC: 0.0000, F1: 0.0000


[I 2026-02-24 01:08:31,919] Trial 78 finished with value: -0.01152186727570898 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 1.6380259161911853e-06, 'weight_decay': 3.652693520944121e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.22055116563526805, 'early_stopping_min_delta': 0.005937253865531163}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.15768 | val 0.20104
  Epoch 021 - train 0.15415 | val 0.20054
  Regression -> MSE: 0.000242, MAE: 0.012282, R²: -0.0349
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.52198 | val 0.91977
  Epoch 020 - train 0.53253 | val 0.90607
  Epoch 021 - train 0.53336 | val 0.91376
  Regression -> MSE: 0.000266, MAE: 0.013152, R²: -0.0741
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.66253 | val 0.65406
  Epoch 020 - train 0.66037 | val 0.63582
  Epoch 021 - train 0.56016 | val 0.64615
  Regression -> MSE: 0.000728, MAE: 0.020067, R²: -0.0640
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.58904 | val 1.00885
  Epoch 020 - train 0.58170 | val 1.01085
  Epoch 021 - train 0.57822 | val 1.01042
  Regression -> MSE: 0.000310, MAE: 0.014410, R²: -0.0001
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.46221 | val 0.43588
  Epoch 020 - train 0.48077 | val 0.41984
  Epoch 021 - train 0.51559 | val 0.42861
  Regression -> MSE: 0.000351, MAE: 0.014619, R²: -0.0057
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.52954 | val 0.48720
  Epoch 020 - train 0.53826 | val 0.48823
  Epoch 021 - train 0.50073 | val 0.48624
  Regression -> MSE: 0.000205, MAE: 0.010100, R²: -0.0077
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.54037 | val 1.24196
  Epoch 020 - train 0.50189 | val 1.24242
  Epoch 021 - train 0.52343 | val 1.24236
  Regression -> MSE: 0.000571, MAE: 0.018392, R²: -0.0279
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.60880 | val 0.79727
  Epoch 020 - train 0.64710 | val 0.78743
  Epoch 021 - train 0.60291 | val 0.79276
  Regression -> MSE: 0.000247, MAE: 0.011907, R²: -0.0063
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.62434 | val 0.74472
  Epoch 020 - train 0.61029 | val 0.76801
  Epoch 021 - train 0.56607 | val 0.77386
  Regression -> MSE: 0.000634, MAE: 0.019993, R²: -0.0604
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50796 | val 0.70715
  Epoch 020 - train 0.56250 | val 0.71889
  Epoch 021 - train 0.52582 | val 0.71262
  Regression -> MSE: 0.000391, MAE: 0.015941, R²: -0.0180
  Directional -> Accuracy: 0.4490, MCC: -0.0714, F1: 0.5091

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.59670 | val 0.78769
  Epoch 020 - train 0.53483 | val 0.78444
  Epoch 021 - train 0.55691 | val 0.77811
  Regression -> MSE: 0.000241, MAE: 0.011821, R²: 0.0004
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52083 | val 0.77328
  Epoch 020 - train 0.53918 | val 0.78199
  Epoch 030 - train 0.52705 | val 0.77085
  Regression -> MSE: 0.000384, MAE: 0.014384, R²: -0.2353
  Directional -> Accuracy: 0.5000, MCC: -0.0234, F1: 0.3902

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.52197 | val 0.67382
  Epoch 020 - train 0.54891 | val 0.67802
  Epoch 021 - train 0.54965 | val 0.67189
  Regression -> MSE: 0.000678, MAE: 0.019547, R²: -0.0006
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.58978 | val 1.10775
  Epoch 020 - train 0.60143 | val 1.13758
  Epoch 021 - train 0.57280 | val 1.14828
  Regression -> MSE: 0.000139, MAE: 0.009018, R²: -0.0078
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.57835 | val 0.88392
  Epoch 020 - train 0.59530 | val 0.89600
  Epoch 021 - train 0.59043 | val 0.89161
  Regression -> MSE: 0.000224, MAE: 0.010729, R²: 0.0029
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.52676 | val 1.36353
  Epoch 020 - train 0.54686 | val 1.36760
  Epoch 024 - train 0.57738 | val 1.36115
  Regression -> MSE: 0.000369, MAE: 0.016055, R²: -0.0202
  Directional -> Accuracy: 0.5192, MCC: 0.0127, F1: 0.3902

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.60518 | val 0.63218
  Epoch 020 - train 0.64108 | val 0.61327
  Epoch 021 - train 0.59411 | val 0.61452
  Regression -> MSE: 0.000110, MAE: 0.008170, R²: -0.0171
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.51175 | val 1.02038
  Epoch 020 - train 0.50472 | val 1.01977
  Epoch 024 - train 0.53044 | val 1.01870
  Regression -> MSE: 0.000175, MAE: 0.010772, R²: -0.1203
  Directional -> Accuracy: 0.3220, MCC: -0.2666, F1: 0.2000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.61694 | val 0.64902
  Epoch 020 - train 0.62509 | val 0.65939
  Epoch 021 - train 0.59207 | val 0.65084
  Regression -> MSE: 0.000286, MAE: 0.013678, R²: -0.0516
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.43842 | val 0.75419
  Epoch 020 - train 0.48751 | val 0.75623
  Epoch 021 - train 0.47674 | val 0.75094
  Regression -> MSE: 0.000155, MAE: 0.008767, R²: -0.0331
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.51316 | val 0.92375
  Epoch 020 - train 0.55026 | val 0.93267
  Epoch 024 - train 0.54178 | val 0.92748
  Regression -> MSE: 0.000314, MAE: 0.013763, R²: -0.3894
  Directional -> Accuracy: 0.3467, MCC: -0.2938, F1: 0.2899

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.48880 | val 0.69545
  Epoch 020 - train 0.54028 | val 0.69384
  Epoch 026 - train 0.54027 | val 0.69305
  Regression -> MSE: 0.000155, MAE: 0.009103, R²: -0.0836
  Directional -> Accuracy: 0.5208, MCC: -0.1152, F1: 0.6567

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.53460 | val 0.83487
  Epoch 020 - train 0.56097 | val 0.83501
  Epoch 021 - train 0.49248 | val 0.84012
  Regression -> MSE: 0.000166, MAE: 0.010380, R²: -0.0055
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.63464 | val 0.75311
  Epoch 020 - train 0.57871 | val 0.74628
  Epoch 021 - train 0.67424 | val 0.74974
  Regression -> MSE: 0.000085, MAE: 0.007043, R²: -0.0023
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.55448 | val 0.72606
  Epoch 020 - train 0.59310 | val 0.73040
  Epoch 021 - train 0.60936 | val 0.73573
  Regression -> MSE: 0.000212, MAE: 0.011044, R²: -0.0026
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.49267 | val 0.46962
  Epoch 020 - train 0.54348 | val 0.46491
  Epoch 021 - train 0.48199 | val 0.47067
  Regression -> MSE: 0.000101, MAE: 0.008224, R²: -0.0964
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.58847 | val 0.36415
  Epoch 020 - train 0.57038 | val 0.38811
  Epoch 028 - train 0.58846 | val 0.38262
  Regression -> MSE: 0.000109, MAE: 0.009124, R²: -0.0609
  Directional -> Accuracy: 0.4783, MCC: 0.0793, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.57303 | val 0.46174
  Epoch 020 - train 0.54229 | val 0.46102
  Epoch 026 - train 0.58080 | val 0.46272
  Regression -> MSE: 0.000241, MAE: 0.012840, R²: -0.0431
  Directional -> Accuracy: 0.5116, MCC: 0.0866, F1: 0.4615

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.48557 | val 0.56466
  Epoch 020 - train 0.51040 | val 0.56634
  Epoch 030 - train 0.47421 | val 0.56698
  Regression -> MSE: 0.000205, MAE: 0.009203, R²: -0.2348
  Directional -> Accuracy: 0.4561, MCC: -0.0500, F1: 0.3922

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52912 | val 0.37132
  Epoch 020 - train 0.52302 | val 0.37808
  Epoch 021 - train 0.55401 | val 0.38615
  Regression -> MSE: 0.000243, MAE: 0.012155, R²: -0.0283
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.50348 | val 1.00062
  Epoch 020 - train 0.55716 | val 1.00403
  Epoch 021 - train 0.56913 | val 1.00530
  Regression -> MSE: 0.000230, MAE: 0.009863, R²: 0.0003
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.61293 | val 0.65732
  Epoch 020 - train 0.62588 | val 0.65633
  Epoch 021 - train 0.68164 | val 0.65957
  Regression -> MSE: 0.000135, MAE: 0.008180, R²: 0.0009
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.58631 | val 0.70720
  Epoch 020 - train 0.58011 | val 0.70763
  Epoch 021 - train 0.59821 | val 0.70927
  Regression -> MSE: 0.000196, MAE: 0.010576, R²: -0.0411
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.54311 | val 0.75498
  Epoch 020 - train 0.51900 | val 0.74689
  Epoch 021 - train 0.51033 | val 0.75215
  Regression -> MSE: 0.000262, MAE: 0.010549, R²: 0.0003
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.55288 | val 0.35433
  Epoch 020 - train 0.53645 | val 0.37719
  Epoch 028 - train 0.49082 | val 0.37631
  Regression -> MSE: 0.000165, MAE: 0.010241, R²: 0.0110
  Directional -> Accuracy: 0.6053, MCC: 0.2887, F1: 0.4000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.54181 | val 0.67053
  Epoch 020 - train 0.54519 | val 0.68618
  Epoch 021 - train 0.55948 | val 0.67002
  Regression -> MSE: 0.000189, MAE: 0.010635, R²: -0.0479
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.59263 | val 0.55309
  Epoch 020 - train 0.57083 | val 0.55449
  Epoch 021 - train 0.52968 | val 0.55242
  Regression -> MSE: 0.000350, MAE: 0.012366, R²: -0.0208
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.61029 | val 0.25305
  Epoch 020 - train 0.59087 | val 0.25537
  Epoch 021 - train 0.58721 | val 0.25538
  Regression -> MSE: 0.000117, MAE: 0.008320, R²: -0.1127
  Directional -> Accuracy: 0.6279, MCC: 0.3475, F1: 0.4667

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.60339 | val 0.94777
  Epoch 020 - train 0.63906 | val 0.94129
  Epoch 021 - train 0.59016 | val 0.94236
  Regression -> MSE: 0.000221, MAE: 0.011350, R²: -0.0094
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50029 | val 1.21014
  Epoch 020 - train 0.52381 | val 1.21292
  Epoch 021 - train 0.52419 | val 1.21684
  Regression -> MSE: 0.000084, MAE: 0.007144, R²: -0.0788
  Directional -> Accuracy: 0.3830, MCC: -0.1729, F1: 0.3556

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.57321 | val 0.27911
  Epoch 020 - train 0.62582 | val 0.30769
  Epoch 027 - train 0.60705 | val 0.30737
  Regression -> MSE: 0.000316, MAE: 0.013621, R²: -0.0279
  Directional -> Accuracy: 0.6122, MCC: -0.1100, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.61266 | val 0.24401
  Epoch 020 - train 0.66469 | val 0.28368
  Epoch 021 - train 0.60947 | val 0.28687
  Regression -> MSE: 0.000258, MAE: 0.011479, R²: -0.0580
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.50757 | val 0.61029
  Epoch 020 - train 0.49834 | val 0.60967
  Epoch 021 - train 0.52497 | val 0.60822
  Regression -> MSE: 0.000082, MAE: 0.007057, R²: -0.0093
  Directional -> Accuracy: 0.5600, MCC: 0.1287, F1: 0.4211

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.57879 | val 0.62521
  Epoch 020 - train 0.59663 | val 0.63339
  Epoch 027 - train 0.52481 | val 0.62975
  Regression -> MSE: 0.000297, MAE: 0.014130, R²: 0.0317
  Directional -> Accuracy: 0.6170, MCC: 0.2359, F1: 0.6087

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.56571 | val 0.71259
  Epoch 020 - train 0.56342 | val 0.78723
  Epoch 021 - train 0.58181 | val 0.78474
  Regression -> MSE: 0.000103, MAE: 0.007113, R²: -0.0438
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.54960 | val 0.74032
  Epoch 020 - train 0.52933 | val 0.73980
  Epoch 030 - train 0.58689 | val 0.74272
  Regression -> MSE: 0.000239, MAE: 0.010973, R²: -0.3883
  Directional -> Accuracy: 0.6122, MCC: 0.0475, F1: 0.0952

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.55220 | val 0.65901
  Epoch 020 - train 0.57272 | val 0.66259
  Epoch 021 - train 0.60841 | val 0.65816
  Regression -> MSE: 0.000229, MAE: 0.011810, R²: -0.0249
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000


[I 2026-02-24 01:11:15,402] Trial 79 finished with value: -0.011584621838069228 and parameters: {'feature_set': 'emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 2.7506442348846435e-06, 'weight_decay': 1.0331898465981797e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.648307771477111, 'early_stopping_min_delta': 0.004601144371546663}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.52954 | val 0.96303
  Epoch 021 - train 0.59229 | val 0.95923
  Regression -> MSE: 0.000241, MAE: 0.012332, R²: -0.0154
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10493 | val 0.16034
  Epoch 020 - train 0.10817 | val 0.16258
  Epoch 021 - train 0.10582 | val 0.16274
  Regression -> MSE: 0.000256, MAE: 0.012867, R²: -0.0329
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10330 | val 0.09747
  Epoch 020 - train 0.10165 | val 0.09947
  Epoch 021 - train 0.10360 | val 0.09907
  Regression -> MSE: 0.000700, MAE: 0.019607, R²: -0.0223
  Directional -> Accuracy: 0.5000, MCC: -0.0115, F1: 0.5490

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11574 | val 0.16263
  Epoch 020 - train 0.11415 | val 0.16293
  Epoch 021 - train 0.11147 | val 0.16304
  Regression -> MSE: 0.000329, MAE: 0.014613, R²: -0.0609
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09146 | val 0.08966
  Epoch 020 - train 0.08848 | val 0.09066
  Epoch 021 - train 0.09012 | val 0.09092
  Regression -> MSE: 0.000350, MAE: 0.014601, R²: -0.0018
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10833 | val 0.10954
  Epoch 020 - train 0.10815 | val 0.12555
  Epoch 021 - train 0.10714 | val 0.12610
  Regression -> MSE: 0.000203, MAE: 0.010122, R²: 0.0020
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10291 | val 0.18237
  Epoch 020 - train 0.09622 | val 0.19550
  Epoch 021 - train 0.10270 | val 0.19649
  Regression -> MSE: 0.000562, MAE: 0.018194, R²: -0.0116
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10911 | val 0.12663
  Epoch 020 - train 0.10613 | val 0.12683
  Epoch 021 - train 0.10768 | val 0.12663
  Regression -> MSE: 0.000249, MAE: 0.011932, R²: -0.0129
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10174 | val 0.14570
  Epoch 020 - train 0.10693 | val 0.16982
  Epoch 021 - train 0.10170 | val 0.17248
  Regression -> MSE: 0.000655, MAE: 0.020319, R²: -0.0960
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10186 | val 0.12036
  Epoch 020 - train 0.10292 | val 0.12727
  Epoch 021 - train 0.09714 | val 0.12730
  Regression -> MSE: 0.000400, MAE: 0.016055, R²: -0.0440
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10313 | val 0.13587
  Epoch 020 - train 0.10562 | val 0.13706
  Epoch 021 - train 0.10142 | val 0.13692
  Regression -> MSE: 0.000245, MAE: 0.011635, R²: -0.0134
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10405 | val 0.14214
  Epoch 020 - train 0.10303 | val 0.15151
  Epoch 021 - train 0.10339 | val 0.15230
  Regression -> MSE: 0.000322, MAE: 0.013594, R²: -0.0355
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11258 | val 0.12115
  Epoch 020 - train 0.10776 | val 0.12340
  Epoch 021 - train 0.10673 | val 0.12351
  Regression -> MSE: 0.000685, MAE: 0.019544, R²: -0.0115
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10236 | val 0.10366
  Epoch 020 - train 0.10562 | val 0.10765
  Epoch 021 - train 0.11033 | val 0.10751
  Regression -> MSE: 0.000138, MAE: 0.009127, R²: 0.0008
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09740 | val 0.12401
  Epoch 020 - train 0.09800 | val 0.12133
  Epoch 030 - train 0.09608 | val 0.12112
  Regression -> MSE: 0.000234, MAE: 0.011064, R²: -0.0388
  Directional -> Accuracy: 0.4918, MCC: -0.0030, F1: 0.0606

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10746 | val 0.19709
  Epoch 020 - train 0.10600 | val 0.19722
  Epoch 021 - train 0.09951 | val 0.19707
  Regression -> MSE: 0.000369, MAE: 0.015938, R²: -0.0177
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11561 | val 0.11590
  Epoch 020 - train 0.10574 | val 0.11938
  Epoch 021 - train 0.10746 | val 0.11842
  Regression -> MSE: 0.000111, MAE: 0.007958, R²: -0.0282
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11133 | val 0.19757
  Epoch 020 - train 0.10787 | val 0.20059
  Epoch 021 - train 0.10677 | val 0.19980
  Regression -> MSE: 0.000158, MAE: 0.009569, R²: -0.0132
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10591 | val 0.10732
  Epoch 020 - train 0.10590 | val 0.10827
  Epoch 021 - train 0.10717 | val 0.10825
  Regression -> MSE: 0.000274, MAE: 0.012931, R²: -0.0060
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10517 | val 0.14197
  Epoch 020 - train 0.09897 | val 0.14077
  Epoch 021 - train 0.10157 | val 0.14137
  Regression -> MSE: 0.000156, MAE: 0.008795, R²: -0.0418
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11556 | val 0.16066
  Epoch 020 - train 0.11447 | val 0.15728
  Epoch 021 - train 0.10972 | val 0.15669
  Regression -> MSE: 0.000235, MAE: 0.010994, R²: -0.0365
  Directional -> Accuracy: 0.4133, MCC: -0.1780, F1: 0.4500

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11329 | val 0.12492
  Epoch 020 - train 0.10523 | val 0.12486
  Epoch 021 - train 0.11120 | val 0.12520
  Regression -> MSE: 0.000153, MAE: 0.008796, R²: -0.0662
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10156 | val 0.11753
  Epoch 020 - train 0.10241 | val 0.11885
  Epoch 021 - train 0.09928 | val 0.11882
  Regression -> MSE: 0.000170, MAE: 0.010250, R²: -0.0312
  Directional -> Accuracy: 0.5152, MCC: 0.0727, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11233 | val 0.11816
  Epoch 020 - train 0.10556 | val 0.11822
  Epoch 021 - train 0.10648 | val 0.11803
  Regression -> MSE: 0.000088, MAE: 0.007193, R²: -0.0318
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11459 | val 0.18464
  Epoch 020 - train 0.10409 | val 0.20024
  Epoch 021 - train 0.10804 | val 0.19811
  Regression -> MSE: 0.000212, MAE: 0.011081, R²: -0.0017
  Directional -> Accuracy: 0.5455, MCC: 0.0949, F1: 0.5455

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09508 | val 0.09412
  Epoch 020 - train 0.09860 | val 0.09380
  Epoch 021 - train 0.09777 | val 0.09371
  Regression -> MSE: 0.000093, MAE: 0.008097, R²: -0.0054
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11805 | val 0.07948
  Epoch 020 - train 0.10534 | val 0.08352
  Epoch 021 - train 0.10735 | val 0.08450
  Regression -> MSE: 0.000106, MAE: 0.008891, R²: -0.0319
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10616 | val 0.10351
  Epoch 020 - train 0.10788 | val 0.11287
  Epoch 021 - train 0.10819 | val 0.11313
  Regression -> MSE: 0.000235, MAE: 0.012691, R²: -0.0169
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10776 | val 0.11686
  Epoch 020 - train 0.10238 | val 0.11838
  Epoch 021 - train 0.10156 | val 0.11830
  Regression -> MSE: 0.000184, MAE: 0.008038, R²: -0.1044
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11512 | val 0.08519
  Epoch 020 - train 0.11172 | val 0.08432
  Epoch 021 - train 0.10677 | val 0.08432
  Regression -> MSE: 0.000238, MAE: 0.011900, R²: -0.0056
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11426 | val 0.16410
  Epoch 020 - train 0.11769 | val 0.16866
  Epoch 021 - train 0.10935 | val 0.16907
  Regression -> MSE: 0.000238, MAE: 0.010311, R²: -0.0308
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10303 | val 0.11924
  Epoch 020 - train 0.10783 | val 0.12305
  Epoch 021 - train 0.10888 | val 0.12332
  Regression -> MSE: 0.000136, MAE: 0.008241, R²: -0.0044
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10818 | val 0.12561
  Epoch 020 - train 0.10180 | val 0.12801
  Epoch 021 - train 0.10777 | val 0.12809
  Regression -> MSE: 0.000191, MAE: 0.010397, R²: -0.0129
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09495 | val 0.11376
  Epoch 020 - train 0.09670 | val 0.11101
  Epoch 021 - train 0.09391 | val 0.11125
  Regression -> MSE: 0.000266, MAE: 0.010535, R²: -0.0151
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10034 | val 0.08536
  Epoch 020 - train 0.10495 | val 0.08643
  Epoch 021 - train 0.10348 | val 0.08662
  Regression -> MSE: 0.000167, MAE: 0.010375, R²: -0.0020
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09584 | val 0.09961
  Epoch 020 - train 0.09782 | val 0.09923
  Epoch 021 - train 0.09855 | val 0.09949
  Regression -> MSE: 0.000180, MAE: 0.010293, R²: 0.0009
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09694 | val 0.09172
  Epoch 020 - train 0.09912 | val 0.09284
  Epoch 021 - train 0.09864 | val 0.09302
  Regression -> MSE: 0.000343, MAE: 0.011799, R²: -0.0001
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10723 | val 0.06824
  Epoch 020 - train 0.10726 | val 0.08110
  Epoch 021 - train 0.10968 | val 0.08151
  Regression -> MSE: 0.000113, MAE: 0.008310, R²: -0.0728
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10730 | val 0.13182
  Epoch 020 - train 0.10332 | val 0.13553
  Epoch 021 - train 0.10829 | val 0.13538
  Regression -> MSE: 0.000219, MAE: 0.011288, R²: -0.0009
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10690 | val 0.16812
  Epoch 020 - train 0.10769 | val 0.17551
  Epoch 021 - train 0.11244 | val 0.17580
  Regression -> MSE: 0.000089, MAE: 0.007396, R²: -0.1501
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10701 | val 0.07885
  Epoch 020 - train 0.11133 | val 0.09151
  Epoch 021 - train 0.11111 | val 0.09299
  Regression -> MSE: 0.000312, MAE: 0.014052, R²: -0.0131
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11352 | val 0.06273
  Epoch 020 - train 0.11745 | val 0.06302
  Epoch 021 - train 0.12390 | val 0.06335
  Regression -> MSE: 0.000252, MAE: 0.011492, R²: -0.0339
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10583 | val 0.12681
  Epoch 020 - train 0.10183 | val 0.12750
  Epoch 021 - train 0.10224 | val 0.12739
  Regression -> MSE: 0.000081, MAE: 0.007077, R²: -0.0037
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10915 | val 0.12843
  Epoch 020 - train 0.11230 | val 0.12682
  Epoch 021 - train 0.11151 | val 0.12650
  Regression -> MSE: 0.000308, MAE: 0.014469, R²: -0.0030
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10950 | val 0.12488
  Epoch 020 - train 0.11545 | val 0.12988
  Epoch 021 - train 0.10624 | val 0.13064
  Regression -> MSE: 0.000105, MAE: 0.007123, R²: -0.0694
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12126 | val 0.11957
  Epoch 020 - train 0.11574 | val 0.12803
  Epoch 021 - train 0.12503 | val 0.12855
  Regression -> MSE: 0.000172, MAE: 0.009552, R²: -0.0020
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10125 | val 0.10815
  Epoch 020 - train 0.09663 | val 0.10809
  Epoch 021 - train 0.10135 | val 0.10908
  Regression -> MSE: 0.000223, MAE: 0.011748, R²: -0.0010
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10534 | val 0.11176
  Epoch 020 - train 0.10647 | val 0.11319
  Epoch 021 - train 0.10793 | val 0.11315

[I 2026-02-24 01:13:08,193] Trial 80 finished with value: -0.01140260787798208 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 1.3986309690168297e-05, 'weight_decay': 6.418079384392416e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.14631341541773019, 'early_stopping_min_delta': 0.008791464611027337}. Best is trial 44 with value: -0.011362814469631832.

  Regression -> MSE: 0.000240, MAE: 0.012337, R²: -0.0132
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10191 | val 0.12308
  Epoch 020 - train 0.09761 | val 0.12346
  Epoch 021 - train 0.09804 | val 0.12352
  Regression -> MSE: 0.000257, MAE: 0.012904, R²: -0.0363
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10024 | val 0.09042
  Epoch 020 - train 0.10168 | val 0.09330
  Epoch 021 - train 0.09605 | val 0.09327
  Regression -> MSE: 0.000720, MAE: 0.019949, R²: -0.0512
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10884 | val 0.15492
  Epoch 020 - train 0.10353 | val 0.15294
  Epoch 021 - train 0.10239 | val 0.15240
  Regression -> MSE: 0.000323, MAE: 0.014541, R²: -0.0413
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09402 | val 0.08632
  Epoch 020 - train 0.08905 | val 0.09649
  Epoch 021 - train 0.09075 | val 0.09778
  Regression -> MSE: 0.000381, MAE: 0.015108, R²: -0.0917
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09868 | val 0.09547
  Epoch 020 - train 0.10301 | val 0.09725
  Epoch 021 - train 0.09911 | val 0.09734
  Regression -> MSE: 0.000205, MAE: 0.010050, R²: -0.0080
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10256 | val 0.18688
  Epoch 020 - train 0.10412 | val 0.21087
  Epoch 021 - train 0.09930 | val 0.21131
  Regression -> MSE: 0.000598, MAE: 0.018929, R²: -0.0776
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10928 | val 0.11965
  Epoch 020 - train 0.10153 | val 0.11981
  Epoch 021 - train 0.09832 | val 0.12020
  Regression -> MSE: 0.000246, MAE: 0.011985, R²: -0.0006
  Directional -> Accuracy: 0.4638, MCC: 0.0075, F1: 0.5195

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10403 | val 0.11493
  Epoch 020 - train 0.10011 | val 0.11323
  Epoch 021 - train 0.11066 | val 0.11347
  Regression -> MSE: 0.000607, MAE: 0.019385, R²: -0.0155
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09673 | val 0.11775
  Epoch 020 - train 0.10233 | val 0.11765
  Epoch 021 - train 0.09878 | val 0.11782
  Regression -> MSE: 0.000387, MAE: 0.016066, R²: -0.0095
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09719 | val 0.12145
  Epoch 020 - train 0.09710 | val 0.12216
  Epoch 021 - train 0.09461 | val 0.12221
  Regression -> MSE: 0.000242, MAE: 0.011843, R²: -0.0003
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09304 | val 0.13521
  Epoch 020 - train 0.08830 | val 0.13466
  Epoch 021 - train 0.08342 | val 0.13532
  Regression -> MSE: 0.000312, MAE: 0.013713, R²: -0.0024
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10076 | val 0.11339
  Epoch 020 - train 0.09813 | val 0.11553
  Epoch 021 - train 0.09978 | val 0.11542
  Regression -> MSE: 0.000678, MAE: 0.019483, R²: -0.0010
  Directional -> Accuracy: 0.4655, MCC: -0.0851, F1: 0.2439

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09931 | val 0.11759
  Epoch 020 - train 0.09288 | val 0.17877
  Epoch 021 - train 0.10162 | val 0.17951
  Regression -> MSE: 0.000139, MAE: 0.009166, R²: -0.0033
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09377 | val 0.13844
  Epoch 020 - train 0.09295 | val 0.14440
  Epoch 021 - train 0.08817 | val 0.14422
  Regression -> MSE: 0.000225, MAE: 0.010692, R²: 0.0007
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10017 | val 0.18815
  Epoch 020 - train 0.09461 | val 0.18828
  Epoch 021 - train 0.09652 | val 0.18848
  Regression -> MSE: 0.000364, MAE: 0.016031, R²: -0.0041
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10246 | val 0.11945
  Epoch 020 - train 0.10095 | val 0.11921
  Epoch 021 - train 0.10088 | val 0.11897
  Regression -> MSE: 0.000110, MAE: 0.008185, R²: -0.0188
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09688 | val 0.15401
  Epoch 020 - train 0.09424 | val 0.16111
  Epoch 021 - train 0.09695 | val 0.16078
  Regression -> MSE: 0.000156, MAE: 0.009565, R²: 0.0006
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10198 | val 0.10163
  Epoch 020 - train 0.09820 | val 0.10194
  Epoch 021 - train 0.10015 | val 0.10241
  Regression -> MSE: 0.000279, MAE: 0.013352, R²: -0.0242
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09294 | val 0.12817
  Epoch 020 - train 0.09491 | val 0.12799
  Epoch 021 - train 0.09580 | val 0.12836
  Regression -> MSE: 0.000177, MAE: 0.009430, R²: -0.1854
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10430 | val 0.14385
  Epoch 020 - train 0.10180 | val 0.13869
  Epoch 021 - train 0.09963 | val 0.13806
  Regression -> MSE: 0.000228, MAE: 0.010919, R²: -0.0092
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10957 | val 0.11624
  Epoch 020 - train 0.10078 | val 0.11970
  Epoch 021 - train 0.10040 | val 0.11997
  Regression -> MSE: 0.000147, MAE: 0.008547, R²: -0.0267
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09460 | val 0.11499
  Epoch 020 - train 0.09554 | val 0.11443
  Epoch 021 - train 0.08978 | val 0.11441
  Regression -> MSE: 0.000166, MAE: 0.010621, R²: -0.0041
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10349 | val 0.11428
  Epoch 020 - train 0.10325 | val 0.11699
  Epoch 021 - train 0.09988 | val 0.11704
  Regression -> MSE: 0.000086, MAE: 0.007106, R²: -0.0119
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09675 | val 0.11988
  Epoch 020 - train 0.09446 | val 0.12050
  Epoch 021 - train 0.09490 | val 0.12018
  Regression -> MSE: 0.000213, MAE: 0.011076, R²: -0.0066
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09124 | val 0.09055
  Epoch 020 - train 0.09026 | val 0.09030
  Epoch 021 - train 0.09114 | val 0.09007
  Regression -> MSE: 0.000101, MAE: 0.008225, R²: -0.0998
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09444 | val 0.07902
  Epoch 020 - train 0.09547 | val 0.07695
  Epoch 021 - train 0.09874 | val 0.07692
  Regression -> MSE: 0.000112, MAE: 0.009086, R²: -0.0859
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10870 | val 0.09570
  Epoch 020 - train 0.10480 | val 0.12390
  Epoch 021 - train 0.10422 | val 0.12476
  Regression -> MSE: 0.000231, MAE: 0.012512, R²: 0.0005
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09895 | val 0.11507
  Epoch 020 - train 0.09513 | val 0.11561
  Epoch 021 - train 0.09778 | val 0.11586
  Regression -> MSE: 0.000178, MAE: 0.007923, R²: -0.0719
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09596 | val 0.08526
  Epoch 020 - train 0.10521 | val 0.08248
  Epoch 021 - train 0.10121 | val 0.08238
  Regression -> MSE: 0.000239, MAE: 0.011985, R²: -0.0097
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09237 | val 0.15142
  Epoch 020 - train 0.10136 | val 0.15131
  Epoch 021 - train 0.09543 | val 0.15154
  Regression -> MSE: 0.000233, MAE: 0.010055, R²: -0.0130
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09801 | val 0.11360
  Epoch 020 - train 0.09935 | val 0.11134
  Epoch 021 - train 0.10003 | val 0.11133
  Regression -> MSE: 0.000136, MAE: 0.008240, R²: -0.0057
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10219 | val 0.11965
  Epoch 020 - train 0.09697 | val 0.12148
  Epoch 021 - train 0.10560 | val 0.12139
  Regression -> MSE: 0.000203, MAE: 0.010874, R²: -0.0803
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09029 | val 0.10926
  Epoch 020 - train 0.08810 | val 0.10862
  Epoch 021 - train 0.08714 | val 0.10841
  Regression -> MSE: 0.000262, MAE: 0.010545, R²: -0.0014
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09254 | val 0.08361
  Epoch 020 - train 0.09159 | val 0.08604
  Epoch 021 - train 0.08848 | val 0.08657
  Regression -> MSE: 0.000167, MAE: 0.010368, R²: -0.0017
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09493 | val 0.09732
  Epoch 020 - train 0.09310 | val 0.10815
  Epoch 021 - train 0.09585 | val 0.10814
  Regression -> MSE: 0.000180, MAE: 0.010277, R²: 0.0013
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09593 | val 0.09412
  Epoch 020 - train 0.09670 | val 0.09531
  Epoch 021 - train 0.09642 | val 0.09519
  Regression -> MSE: 0.000343, MAE: 0.011967, R²: -0.0006
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10696 | val 0.06533
  Epoch 020 - train 0.10811 | val 0.08751
  Epoch 021 - train 0.11105 | val 0.08776
  Regression -> MSE: 0.000115, MAE: 0.008307, R²: -0.0905
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09847 | val 0.12583
  Epoch 020 - train 0.10122 | val 0.12603
  Epoch 021 - train 0.09917 | val 0.12603
  Regression -> MSE: 0.000224, MAE: 0.011442, R²: -0.0247
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09651 | val 0.16138
  Epoch 020 - train 0.09297 | val 0.16196
  Epoch 021 - train 0.10161 | val 0.16178
  Regression -> MSE: 0.000083, MAE: 0.007120, R²: -0.0734
  Directional -> Accuracy: 0.5745, MCC: -0.0074, F1: 0.7059

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09631 | val 0.07573
  Epoch 020 - train 0.10026 | val 0.07822
  Epoch 021 - train 0.09860 | val 0.07841
  Regression -> MSE: 0.000317, MAE: 0.014361, R²: -0.0312
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10364 | val 0.05806
  Epoch 020 - train 0.10292 | val 0.05591
  Epoch 021 - train 0.10512 | val 0.05592
  Regression -> MSE: 0.000246, MAE: 0.011566, R²: -0.0085
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09617 | val 0.12002
  Epoch 020 - train 0.09622 | val 0.11992
  Epoch 021 - train 0.09749 | val 0.12000
  Regression -> MSE: 0.000081, MAE: 0.007084, R²: -0.0004
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10049 | val 0.11698
  Epoch 020 - train 0.09497 | val 0.11457
  Epoch 021 - train 0.10518 | val 0.11446
  Regression -> MSE: 0.000307, MAE: 0.014501, R²: -0.0004
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09666 | val 0.10150
  Epoch 020 - train 0.09791 | val 0.09961
  Epoch 021 - train 0.10358 | val 0.09960
  Regression -> MSE: 0.000098, MAE: 0.007248, R²: -0.0026
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10190 | val 0.11277
  Epoch 020 - train 0.10139 | val 0.11772
  Epoch 021 - train 0.10322 | val 0.11806
  Regression -> MSE: 0.000175, MAE: 0.010169, R²: -0.0202
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09501 | val 0.11511
  Epoch 020 - train 0.09296 | val 0.11801
  Epoch 021 - train 0.09371 | val 0.11690
  Regression -> MSE: 0.000223, MAE: 0.011718, R²: -0.0001
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09705 | val 0.10609
  Epoch 020 - train 0.09901 | val 0.10613
  Epoch 021 - train 0.09509 | val 0.10653
  Regression -> MSE: 0.000095, MAE: 0.007809, R²: -0.0271
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429


[I 2026-02-24 01:15:01,448] Trial 81 finished with value: -0.011472974833667705 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 1.3569306422419078e-05, 'weight_decay': 6.745031225402552e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.13953987588525055, 'early_stopping_min_delta': 0.009586065389237189}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.10433 | val 0.14523
  Epoch 021 - train 0.09605 | val 0.14521
  Regression -> MSE: 0.000239, MAE: 0.012342, R²: -0.0092
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.19394 | val 0.36158
  Epoch 020 - train 0.20252 | val 0.37098
  Epoch 021 - train 0.19796 | val 0.37069
  Regression -> MSE: 0.000249, MAE: 0.012586, R²: -0.0048
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.18814 | val 0.19544
  Epoch 020 - train 0.18596 | val 0.23754
  Epoch 021 - train 0.19471 | val 0.23651
  Regression -> MSE: 0.000687, MAE: 0.019390, R²: -0.0042
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.20629 | val 0.30702
  Epoch 020 - train 0.20493 | val 0.31490
  Epoch 021 - train 0.20557 | val 0.31430
  Regression -> MSE: 0.000323, MAE: 0.014551, R²: -0.0416
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.17356 | val 0.21235
  Epoch 020 - train 0.17467 | val 0.19716
  Epoch 021 - train 0.17142 | val 0.19235
  Regression -> MSE: 0.000370, MAE: 0.014906, R²: -0.0602
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.19365 | val 0.19437
  Epoch 020 - train 0.19304 | val 0.19779
  Epoch 021 - train 0.19748 | val 0.19833
  Regression -> MSE: 0.000206, MAE: 0.010403, R²: -0.0130
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.18607 | val 0.34621
  Epoch 020 - train 0.17952 | val 0.37531
  Epoch 021 - train 0.17429 | val 0.37508
  Regression -> MSE: 0.000556, MAE: 0.018174, R²: -0.0021
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.19485 | val 0.22543
  Epoch 020 - train 0.19393 | val 0.22641
  Epoch 021 - train 0.19669 | val 0.22654
  Regression -> MSE: 0.000246, MAE: 0.012104, R²: -0.0009
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.19483 | val 0.21277
  Epoch 020 - train 0.19798 | val 0.19238
  Epoch 030 - train 0.18826 | val 0.18803
  Regression -> MSE: 0.000633, MAE: 0.019445, R²: -0.0598
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.20061 | val 0.21255
  Epoch 020 - train 0.18568 | val 0.21681
  Epoch 021 - train 0.19273 | val 0.21652
  Regression -> MSE: 0.000409, MAE: 0.016220, R²: -0.0652
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.20913 | val 0.26338
  Epoch 020 - train 0.19481 | val 0.25831
  Epoch 021 - train 0.19869 | val 0.25776
  Regression -> MSE: 0.000243, MAE: 0.012152, R²: -0.0079
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.18012 | val 0.29800
  Epoch 020 - train 0.18028 | val 0.34819
  Epoch 021 - train 0.17871 | val 0.34830
  Regression -> MSE: 0.000312, MAE: 0.013632, R²: -0.0036
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.19812 | val 0.20959
  Epoch 020 - train 0.20843 | val 0.21081
  Epoch 021 - train 0.20762 | val 0.21111
  Regression -> MSE: 0.000677, MAE: 0.019496, R²: 0.0006
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.20421 | val 0.17954
  Epoch 020 - train 0.18797 | val 0.19157
  Epoch 021 - train 0.19129 | val 0.19226
  Regression -> MSE: 0.000143, MAE: 0.009451, R²: -0.0384
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.18603 | val 0.24268
  Epoch 020 - train 0.17652 | val 0.24939
  Epoch 021 - train 0.18324 | val 0.25002
  Regression -> MSE: 0.000230, MAE: 0.010861, R²: -0.0223
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.20529 | val 0.38160
  Epoch 020 - train 0.19884 | val 0.39295
  Epoch 021 - train 0.19017 | val 0.39256
  Regression -> MSE: 0.000363, MAE: 0.016019, R²: -0.0027
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.20259 | val 0.17610
  Epoch 020 - train 0.19857 | val 0.17766
  Epoch 027 - train 0.19557 | val 0.17792
  Regression -> MSE: 0.000108, MAE: 0.007900, R²: 0.0015
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.19483 | val 0.32500
  Epoch 020 - train 0.19420 | val 0.33564
  Epoch 021 - train 0.19473 | val 0.33422
  Regression -> MSE: 0.000156, MAE: 0.009566, R²: 0.0007
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.19927 | val 0.19599
  Epoch 020 - train 0.19348 | val 0.19573
  Epoch 021 - train 0.20138 | val 0.19523
  Regression -> MSE: 0.000276, MAE: 0.013267, R²: -0.0157
  Directional -> Accuracy: 0.5789, MCC: -0.0368, F1: 0.7241

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.20416 | val 0.27893
  Epoch 020 - train 0.19200 | val 0.28021
  Epoch 021 - train 0.19835 | val 0.28156
  Regression -> MSE: 0.000157, MAE: 0.008834, R²: -0.0524
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.20285 | val 0.25697
  Epoch 020 - train 0.19357 | val 0.25626
  Epoch 021 - train 0.20391 | val 0.25718
  Regression -> MSE: 0.000229, MAE: 0.010891, R²: -0.0139
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.19538 | val 0.22666
  Epoch 020 - train 0.20131 | val 0.22955
  Epoch 021 - train 0.19926 | val 0.22955
  Regression -> MSE: 0.000146, MAE: 0.008499, R²: -0.0171
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.18553 | val 0.21604
  Epoch 020 - train 0.18498 | val 0.21539
  Epoch 021 - train 0.18635 | val 0.21560
  Regression -> MSE: 0.000169, MAE: 0.010281, R²: -0.0257
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.20351 | val 0.22015
  Epoch 020 - train 0.20892 | val 0.22956
  Epoch 021 - train 0.19572 | val 0.22846
  Regression -> MSE: 0.000086, MAE: 0.007069, R²: -0.0062
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.19160 | val 0.31855
  Epoch 020 - train 0.19655 | val 0.33431
  Epoch 021 - train 0.19794 | val 0.33906
  Regression -> MSE: 0.000214, MAE: 0.011389, R²: -0.0117
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.18383 | val 0.17286
  Epoch 020 - train 0.17995 | val 0.17335
  Epoch 021 - train 0.17751 | val 0.17269
  Regression -> MSE: 0.000099, MAE: 0.008198, R²: -0.0748
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18107 | val 0.15238
  Epoch 020 - train 0.18967 | val 0.15561
  Epoch 021 - train 0.19195 | val 0.15581
  Regression -> MSE: 0.000117, MAE: 0.009243, R²: -0.1350
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.19142 | val 0.17249
  Epoch 020 - train 0.19869 | val 0.17477
  Epoch 021 - train 0.19889 | val 0.17451
  Regression -> MSE: 0.000232, MAE: 0.012577, R²: -0.0030
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.20348 | val 0.21932
  Epoch 020 - train 0.19722 | val 0.21860
  Epoch 021 - train 0.19839 | val 0.21849
  Regression -> MSE: 0.000180, MAE: 0.007982, R²: -0.0841
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.18868 | val 0.15765
  Epoch 020 - train 0.19542 | val 0.16810
  Epoch 021 - train 0.20145 | val 0.16906
  Regression -> MSE: 0.000238, MAE: 0.011919, R²: -0.0053
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.22321 | val 0.28676
  Epoch 020 - train 0.22332 | val 0.30194
  Epoch 021 - train 0.21754 | val 0.30189
  Regression -> MSE: 0.000232, MAE: 0.009914, R²: -0.0059
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.20510 | val 0.23077
  Epoch 020 - train 0.20986 | val 0.23082
  Epoch 021 - train 0.20165 | val 0.23038
  Regression -> MSE: 0.000140, MAE: 0.008438, R²: -0.0380
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.19728 | val 0.23737
  Epoch 020 - train 0.19039 | val 0.24590
  Epoch 021 - train 0.19533 | val 0.24601
  Regression -> MSE: 0.000192, MAE: 0.010399, R²: -0.0181
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.17485 | val 0.21797
  Epoch 020 - train 0.17514 | val 0.21867
  Epoch 021 - train 0.17711 | val 0.21736
  Regression -> MSE: 0.000271, MAE: 0.010640, R²: -0.0351
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.19497 | val 0.15415
  Epoch 020 - train 0.18728 | val 0.15426
  Epoch 030 - train 0.18032 | val 0.19379
  Regression -> MSE: 0.000167, MAE: 0.010393, R²: -0.0002
  Directional -> Accuracy: 0.5263, MCC: 0.0555, F1: 0.4375

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.18760 | val 0.18786
  Epoch 020 - train 0.19000 | val 0.19088
  Epoch 021 - train 0.18187 | val 0.19102
  Regression -> MSE: 0.000185, MAE: 0.010496, R²: -0.0273
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.19952 | val 0.18114
  Epoch 020 - train 0.20016 | val 0.18115
  Epoch 021 - train 0.20938 | val 0.18162
  Regression -> MSE: 0.000350, MAE: 0.011794, R²: -0.0224
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.19769 | val 0.11480
  Epoch 020 - train 0.18989 | val 0.11777
  Epoch 021 - train 0.20478 | val 0.11775
  Regression -> MSE: 0.000124, MAE: 0.008429, R²: -0.1756
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.19730 | val 0.26891
  Epoch 020 - train 0.19646 | val 0.28640
  Epoch 021 - train 0.19108 | val 0.28598
  Regression -> MSE: 0.000219, MAE: 0.011279, R²: -0.0036
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.20033 | val 0.32139
  Epoch 020 - train 0.20536 | val 0.35604
  Epoch 021 - train 0.19251 | val 0.35513
  Regression -> MSE: 0.000097, MAE: 0.007678, R²: -0.2437
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.17765 | val 0.13583
  Epoch 020 - train 0.19664 | val 0.13970
  Epoch 021 - train 0.18320 | val 0.14074
  Regression -> MSE: 0.000313, MAE: 0.014138, R²: -0.0176
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.21940 | val 0.11313
  Epoch 020 - train 0.21781 | val 0.11483
  Epoch 021 - train 0.21101 | val 0.11502
  Regression -> MSE: 0.000257, MAE: 0.011475, R²: -0.0551
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.18082 | val 0.22530
  Epoch 020 - train 0.18116 | val 0.22337
  Epoch 021 - train 0.17853 | val 0.22363
  Regression -> MSE: 0.000085, MAE: 0.007062, R²: -0.0514
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.20896 | val 0.25284
  Epoch 020 - train 0.19450 | val 0.33091
  Epoch 021 - train 0.20315 | val 0.33169
  Regression -> MSE: 0.000311, MAE: 0.014491, R²: -0.0130
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.19268 | val 0.19519
  Epoch 020 - train 0.19451 | val 0.19290
  Epoch 021 - train 0.19298 | val 0.19356
  Regression -> MSE: 0.000098, MAE: 0.007263, R²: -0.0015
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.20481 | val 0.21908
  Epoch 020 - train 0.19501 | val 0.23240
  Epoch 021 - train 0.21295 | val 0.23441
  Regression -> MSE: 0.000173, MAE: 0.009909, R²: -0.0058
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.18094 | val 0.22369
  Epoch 020 - train 0.18225 | val 0.23665
  Epoch 021 - train 0.17897 | val 0.23856
  Regression -> MSE: 0.000223, MAE: 0.011766, R²: -0.0014
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.19411 | val 0.22359
  Epoch 020 - train 0.19181 | val 0.22529
  Epoch 021 - train 0.18478 | val 0.22523

[I 2026-02-24 01:16:53,754] Trial 82 finished with value: -0.011447627914840719 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 6.205375711833645e-06, 'weight_decay': 1.5898288524955446e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.28948768838814487, 'early_stopping_min_delta': 0.005042219238161742}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.20152 | val 0.49654
  Epoch 021 - train 0.20615 | val 0.50081
  Regression -> MSE: 0.000237, MAE: 0.012535, R²: -0.0015
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10418 | val 0.19225
  Epoch 020 - train 0.10895 | val 0.19030
  Epoch 021 - train 0.10581 | val 0.19061
  Regression -> MSE: 0.000250, MAE: 0.012645, R²: -0.0095
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10604 | val 0.09872
  Epoch 020 - train 0.10824 | val 0.09397
  Epoch 021 - train 0.10193 | val 0.09386
  Regression -> MSE: 0.000689, MAE: 0.019430, R²: -0.0070
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10894 | val 0.17424
  Epoch 020 - train 0.10637 | val 0.17951
  Epoch 021 - train 0.10866 | val 0.17966
  Regression -> MSE: 0.000311, MAE: 0.014418, R²: -0.0028
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10198 | val 0.15715
  Epoch 020 - train 0.09693 | val 0.15647
  Epoch 021 - train 0.09911 | val 0.15382
  Regression -> MSE: 0.000406, MAE: 0.015639, R²: -0.1634
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11026 | val 0.12264
  Epoch 020 - train 0.10584 | val 0.15164
  Epoch 021 - train 0.10684 | val 0.15297
  Regression -> MSE: 0.000204, MAE: 0.010093, R²: -0.0036
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10732 | val 0.19246
  Epoch 020 - train 0.09907 | val 0.19441
  Epoch 021 - train 0.10466 | val 0.19457
  Regression -> MSE: 0.000568, MAE: 0.018333, R²: -0.0236
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11193 | val 0.12831
  Epoch 020 - train 0.11349 | val 0.12736
  Epoch 021 - train 0.10911 | val 0.12724
  Regression -> MSE: 0.000251, MAE: 0.011968, R²: -0.0210
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10680 | val 0.14058
  Epoch 020 - train 0.11398 | val 0.14413
  Epoch 021 - train 0.10659 | val 0.14485
  Regression -> MSE: 0.000631, MAE: 0.019918, R²: -0.0569
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10204 | val 0.12350
  Epoch 020 - train 0.10415 | val 0.12407
  Epoch 021 - train 0.09837 | val 0.12425
  Regression -> MSE: 0.000404, MAE: 0.016121, R²: -0.0528
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10242 | val 0.13238
  Epoch 020 - train 0.10231 | val 0.13277
  Epoch 021 - train 0.10121 | val 0.13277
  Regression -> MSE: 0.000243, MAE: 0.012098, R²: -0.0050
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09861 | val 0.17129
  Epoch 020 - train 0.09511 | val 0.18882
  Epoch 021 - train 0.09836 | val 0.18910
  Regression -> MSE: 0.000312, MAE: 0.013793, R²: -0.0021
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11339 | val 0.12530
  Epoch 020 - train 0.11512 | val 0.13019
  Epoch 021 - train 0.10938 | val 0.13024
  Regression -> MSE: 0.000679, MAE: 0.019560, R²: -0.0019
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10697 | val 0.10237
  Epoch 020 - train 0.10725 | val 0.10392
  Epoch 021 - train 0.10694 | val 0.10375
  Regression -> MSE: 0.000139, MAE: 0.009178, R²: -0.0042
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09717 | val 0.14399
  Epoch 020 - train 0.10003 | val 0.14589
  Epoch 021 - train 0.09633 | val 0.14583
  Regression -> MSE: 0.000226, MAE: 0.010805, R²: -0.0030
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11275 | val 0.23392
  Epoch 020 - train 0.11110 | val 0.27352
  Epoch 021 - train 0.11327 | val 0.27395
  Regression -> MSE: 0.000363, MAE: 0.016090, R²: -0.0013
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12545 | val 0.12355
  Epoch 020 - train 0.11944 | val 0.12160
  Epoch 021 - train 0.11839 | val 0.12189
  Regression -> MSE: 0.000112, MAE: 0.007972, R²: -0.0379
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10519 | val 0.17862
  Epoch 020 - train 0.10652 | val 0.18165
  Epoch 021 - train 0.10539 | val 0.18226
  Regression -> MSE: 0.000155, MAE: 0.009606, R²: 0.0038
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11313 | val 0.10780
  Epoch 020 - train 0.10869 | val 0.10862
  Epoch 021 - train 0.10719 | val 0.10890
  Regression -> MSE: 0.000286, MAE: 0.013683, R²: -0.0513
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10056 | val 0.13629
  Epoch 020 - train 0.09383 | val 0.13588
  Epoch 021 - train 0.09545 | val 0.13584
  Regression -> MSE: 0.000150, MAE: 0.008724, R²: -0.0056
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10679 | val 0.18005
  Epoch 020 - train 0.10486 | val 0.18560
  Epoch 021 - train 0.10565 | val 0.18563
  Regression -> MSE: 0.000232, MAE: 0.010888, R²: -0.0256
  Directional -> Accuracy: 0.6133, MCC: 0.2198, F1: 0.7184

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10812 | val 0.13236
  Epoch 020 - train 0.10948 | val 0.13550
  Epoch 021 - train 0.11022 | val 0.13587
  Regression -> MSE: 0.000149, MAE: 0.008662, R²: -0.0428
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09914 | val 0.13523
  Epoch 020 - train 0.10227 | val 0.13567
  Epoch 021 - train 0.10047 | val 0.13592
  Regression -> MSE: 0.000165, MAE: 0.010553, R²: 0.0024
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10819 | val 0.12482
  Epoch 020 - train 0.10805 | val 0.12151
  Epoch 021 - train 0.11106 | val 0.12120
  Regression -> MSE: 0.000089, MAE: 0.007240, R²: -0.0418
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10549 | val 0.13549
  Epoch 020 - train 0.10620 | val 0.13767
  Epoch 021 - train 0.10406 | val 0.13847
  Regression -> MSE: 0.000212, MAE: 0.011143, R²: 0.0000
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11215 | val 0.10451
  Epoch 020 - train 0.11021 | val 0.10558
  Epoch 021 - train 0.10502 | val 0.10540
  Regression -> MSE: 0.000092, MAE: 0.008095, R²: -0.0033
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11455 | val 0.08303
  Epoch 020 - train 0.10995 | val 0.09153
  Epoch 021 - train 0.11058 | val 0.09201
  Regression -> MSE: 0.000104, MAE: 0.008792, R²: -0.0100
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10972 | val 0.10091
  Epoch 020 - train 0.10725 | val 0.10459
  Epoch 021 - train 0.10981 | val 0.10432
  Regression -> MSE: 0.000236, MAE: 0.012726, R²: -0.0201
  Directional -> Accuracy: 0.5581, MCC: -0.0137, F1: 0.6984

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10486 | val 0.12271
  Epoch 020 - train 0.10282 | val 0.12207
  Epoch 021 - train 0.10060 | val 0.12202
  Regression -> MSE: 0.000174, MAE: 0.007856, R²: -0.0467
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11033 | val 0.08986
  Epoch 020 - train 0.11025 | val 0.09362
  Epoch 021 - train 0.11077 | val 0.09444
  Regression -> MSE: 0.000237, MAE: 0.011865, R²: -0.0007
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10948 | val 0.16643
  Epoch 020 - train 0.11590 | val 0.16340
  Epoch 021 - train 0.10912 | val 0.16316
  Regression -> MSE: 0.000233, MAE: 0.010044, R²: -0.0118
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11850 | val 0.12372
  Epoch 020 - train 0.11447 | val 0.15115
  Epoch 021 - train 0.11673 | val 0.15199
  Regression -> MSE: 0.000135, MAE: 0.008170, R²: 0.0006
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10656 | val 0.13370
  Epoch 020 - train 0.10676 | val 0.13752
  Epoch 021 - train 0.10503 | val 0.13715
  Regression -> MSE: 0.000192, MAE: 0.010407, R²: -0.0180
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09429 | val 0.11280
  Epoch 020 - train 0.09479 | val 0.11413
  Epoch 021 - train 0.09282 | val 0.11401
  Regression -> MSE: 0.000266, MAE: 0.010527, R²: -0.0172
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09986 | val 0.08931
  Epoch 020 - train 0.10438 | val 0.09318
  Epoch 021 - train 0.09903 | val 0.09423
  Regression -> MSE: 0.000167, MAE: 0.010364, R²: -0.0015
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09911 | val 0.12474
  Epoch 020 - train 0.10285 | val 0.14401
  Epoch 021 - train 0.09770 | val 0.14437
  Regression -> MSE: 0.000190, MAE: 0.010700, R²: -0.0546
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10745 | val 0.09859
  Epoch 020 - train 0.10242 | val 0.10155
  Epoch 021 - train 0.10263 | val 0.10153
  Regression -> MSE: 0.000358, MAE: 0.012847, R²: -0.0456
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11366 | val 0.07043
  Epoch 020 - train 0.11905 | val 0.07360
  Epoch 021 - train 0.11251 | val 0.07346
  Regression -> MSE: 0.000125, MAE: 0.008450, R²: -0.1870
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11037 | val 0.14702
  Epoch 020 - train 0.10373 | val 0.15442
  Epoch 021 - train 0.10316 | val 0.15534
  Regression -> MSE: 0.000218, MAE: 0.011288, R²: 0.0006
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11112 | val 0.17659
  Epoch 020 - train 0.10898 | val 0.18441
  Epoch 021 - train 0.11188 | val 0.18374
  Regression -> MSE: 0.000096, MAE: 0.007626, R²: -0.2306
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10397 | val 0.08946
  Epoch 020 - train 0.11262 | val 0.09491
  Epoch 021 - train 0.10692 | val 0.09544
  Regression -> MSE: 0.000331, MAE: 0.015018, R²: -0.0759
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11357 | val 0.06977
  Epoch 020 - train 0.11338 | val 0.07310
  Epoch 021 - train 0.11606 | val 0.07359
  Regression -> MSE: 0.000258, MAE: 0.011479, R²: -0.0582
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10860 | val 0.13312
  Epoch 020 - train 0.10789 | val 0.13270
  Epoch 021 - train 0.10253 | val 0.13258
  Regression -> MSE: 0.000081, MAE: 0.007051, R²: -0.0056
  Directional -> Accuracy: 0.4800, MCC: -0.0400, F1: 0.5979

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10484 | val 0.13202
  Epoch 020 - train 0.10785 | val 0.13365
  Epoch 021 - train 0.10689 | val 0.13374
  Regression -> MSE: 0.000306, MAE: 0.014479, R²: 0.0016
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09995 | val 0.12010
  Epoch 020 - train 0.10828 | val 0.12196
  Epoch 021 - train 0.10756 | val 0.12200
  Regression -> MSE: 0.000100, MAE: 0.007139, R²: -0.0161
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12283 | val 0.12708
  Epoch 020 - train 0.11806 | val 0.13503
  Epoch 021 - train 0.12150 | val 0.13555
  Regression -> MSE: 0.000173, MAE: 0.009451, R²: -0.0068
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10363 | val 0.11981
  Epoch 020 - train 0.09939 | val 0.11976
  Epoch 021 - train 0.09873 | val 0.11925
  Regression -> MSE: 0.000225, MAE: 0.011769, R²: -0.0081
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11128 | val 0.11694
  Epoch 020 - train 0.10481 | val 0.11823
  Epoch 021 - train 0.10798 | val 0.11822

[I 2026-02-24 01:18:46,719] Trial 83 finished with value: -0.01148222316146273 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 32, 'learning_rate': 9.351257079822192e-06, 'weight_decay': 3.6605612312744654e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.15383795892928234, 'early_stopping_min_delta': 0.008616208090730647}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.11424 | val 0.23828
  Epoch 021 - train 0.11192 | val 0.23648
  Regression -> MSE: 0.000238, MAE: 0.012573, R²: -0.0049
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14183 | val 0.19410
  Epoch 020 - train 0.14188 | val 0.19461
  Epoch 021 - train 0.14347 | val 0.19442
  Regression -> MSE: 0.000249, MAE: 0.012610, R²: -0.0069
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13591 | val 0.13665
  Epoch 020 - train 0.14202 | val 0.14151
  Epoch 021 - train 0.13216 | val 0.14143
  Regression -> MSE: 0.000687, MAE: 0.019359, R²: -0.0031
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15289 | val 0.22883
  Epoch 020 - train 0.14053 | val 0.22488
  Epoch 030 - train 0.14364 | val 0.22680
  Regression -> MSE: 0.000325, MAE: 0.014373, R²: -0.0491
  Directional -> Accuracy: 0.4894, MCC: 0.0705, F1: 0.1429

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12207 | val 0.15058
  Epoch 020 - train 0.12077 | val 0.14251
  Epoch 021 - train 0.12289 | val 0.14284
  Regression -> MSE: 0.000350, MAE: 0.014599, R²: -0.0014
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14634 | val 0.13977
  Epoch 020 - train 0.14196 | val 0.14676
  Epoch 021 - train 0.14258 | val 0.14709
  Regression -> MSE: 0.000205, MAE: 0.010098, R²: -0.0064
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.14022 | val 0.26885
  Epoch 020 - train 0.13603 | val 0.27698
  Epoch 021 - train 0.13283 | val 0.27772
  Regression -> MSE: 0.000585, MAE: 0.018679, R²: -0.0536
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15051 | val 0.17274
  Epoch 020 - train 0.14282 | val 0.17393
  Epoch 021 - train 0.15168 | val 0.17404
  Regression -> MSE: 0.000248, MAE: 0.012339, R²: -0.0088
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14997 | val 0.16961
  Epoch 020 - train 0.13422 | val 0.18314
  Epoch 021 - train 0.14261 | val 0.18532
  Regression -> MSE: 0.000606, MAE: 0.019381, R²: -0.0144
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14674 | val 0.17334
  Epoch 020 - train 0.14988 | val 0.17647
  Epoch 021 - train 0.13374 | val 0.17669
  Regression -> MSE: 0.000395, MAE: 0.015964, R²: -0.0293
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14485 | val 0.20468
  Epoch 020 - train 0.13812 | val 0.20772
  Epoch 021 - train 0.13656 | val 0.20562
  Regression -> MSE: 0.000241, MAE: 0.011848, R²: 0.0004
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14726 | val 0.23852
  Epoch 020 - train 0.13801 | val 0.28726
  Epoch 021 - train 0.13468 | val 0.28833
  Regression -> MSE: 0.000310, MAE: 0.013631, R²: 0.0023
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15056 | val 0.17843
  Epoch 020 - train 0.15181 | val 0.18064
  Epoch 021 - train 0.15150 | val 0.18112
  Regression -> MSE: 0.000681, MAE: 0.019507, R²: -0.0062
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14457 | val 0.15444
  Epoch 020 - train 0.14484 | val 0.17791
  Epoch 021 - train 0.14311 | val 0.17946
  Regression -> MSE: 0.000139, MAE: 0.009029, R²: -0.0044
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13150 | val 0.18615
  Epoch 020 - train 0.13538 | val 0.18189
  Epoch 030 - train 0.12750 | val 0.18242
  Regression -> MSE: 0.000220, MAE: 0.010706, R²: 0.0228
  Directional -> Accuracy: 0.5574, MCC: 0.1602, F1: 0.6824

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14943 | val 0.28994
  Epoch 020 - train 0.14217 | val 0.28511
  Epoch 030 - train 0.13071 | val 0.29118
  Regression -> MSE: 0.000350, MAE: 0.015717, R²: 0.0326
  Directional -> Accuracy: 0.5000, MCC: 0.0602, F1: 0.6061

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14976 | val 0.15328
  Epoch 020 - train 0.15141 | val 0.15857
  Epoch 021 - train 0.14905 | val 0.15845
  Regression -> MSE: 0.000110, MAE: 0.007943, R²: -0.0168
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13771 | val 0.26809
  Epoch 020 - train 0.14253 | val 0.29603
  Epoch 021 - train 0.14069 | val 0.29617
  Regression -> MSE: 0.000157, MAE: 0.009606, R²: -0.0058
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16024 | val 0.15101
  Epoch 020 - train 0.14746 | val 0.15526
  Epoch 021 - train 0.14275 | val 0.15647
  Regression -> MSE: 0.000273, MAE: 0.012946, R²: -0.0033
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12736 | val 0.19304
  Epoch 020 - train 0.12274 | val 0.19297
  Epoch 021 - train 0.12480 | val 0.19285
  Regression -> MSE: 0.000158, MAE: 0.008842, R²: -0.0569
  Directional -> Accuracy: 0.6308, MCC: 0.2610, F1: 0.7600

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15242 | val 0.22284
  Epoch 020 - train 0.14315 | val 0.22133
  Epoch 021 - train 0.14878 | val 0.22199
  Regression -> MSE: 0.000247, MAE: 0.011205, R²: -0.0896
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14239 | val 0.19185
  Epoch 020 - train 0.14394 | val 0.20424
  Epoch 021 - train 0.15489 | val 0.20314
  Regression -> MSE: 0.000152, MAE: 0.008784, R²: -0.0602
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14445 | val 0.18306
  Epoch 020 - train 0.13490 | val 0.18268
  Epoch 021 - train 0.14241 | val 0.18234
  Regression -> MSE: 0.000165, MAE: 0.010587, R²: -0.0002
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14887 | val 0.16552
  Epoch 020 - train 0.14397 | val 0.16575
  Epoch 021 - train 0.15084 | val 0.16584
  Regression -> MSE: 0.000086, MAE: 0.007062, R²: -0.0054
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15167 | val 0.24573
  Epoch 020 - train 0.14295 | val 0.25161
  Epoch 021 - train 0.14259 | val 0.25382
  Regression -> MSE: 0.000212, MAE: 0.011071, R²: -0.0008
  Directional -> Accuracy: 0.5606, MCC: 0.1581, F1: 0.6234

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14645 | val 0.12561
  Epoch 020 - train 0.13142 | val 0.12368
  Epoch 030 - train 0.13130 | val 0.12340
  Regression -> MSE: 0.000106, MAE: 0.008156, R²: -0.1508
  Directional -> Accuracy: 0.5536, MCC: 0.1867, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14946 | val 0.11501
  Epoch 020 - train 0.14313 | val 0.11248
  Epoch 021 - train 0.14498 | val 0.11232
  Regression -> MSE: 0.000111, MAE: 0.009058, R²: -0.0772
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15514 | val 0.14307
  Epoch 020 - train 0.15087 | val 0.15054
  Epoch 021 - train 0.14876 | val 0.14981
  Regression -> MSE: 0.000240, MAE: 0.012852, R²: -0.0373
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14955 | val 0.17090
  Epoch 020 - train 0.14676 | val 0.16712
  Epoch 021 - train 0.13630 | val 0.16680
  Regression -> MSE: 0.000172, MAE: 0.007857, R²: -0.0357
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13768 | val 0.12316
  Epoch 020 - train 0.16024 | val 0.12298
  Epoch 021 - train 0.14931 | val 0.12522
  Regression -> MSE: 0.000239, MAE: 0.011969, R²: -0.0097
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14044 | val 0.23319
  Epoch 020 - train 0.14549 | val 0.24281
  Epoch 021 - train 0.14348 | val 0.24277
  Regression -> MSE: 0.000234, MAE: 0.010084, R²: -0.0136
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14566 | val 0.18623
  Epoch 020 - train 0.14406 | val 0.17708
  Epoch 030 - train 0.14367 | val 0.18172
  Regression -> MSE: 0.000140, MAE: 0.008339, R²: -0.0380
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14432 | val 0.18449
  Epoch 020 - train 0.14056 | val 0.19214
  Epoch 021 - train 0.14407 | val 0.19266
  Regression -> MSE: 0.000189, MAE: 0.010413, R²: -0.0052
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12516 | val 0.16230
  Epoch 020 - train 0.12767 | val 0.16086
  Epoch 021 - train 0.12478 | val 0.16071
  Regression -> MSE: 0.000266, MAE: 0.010535, R²: -0.0169
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15481 | val 0.12673
  Epoch 020 - train 0.13683 | val 0.12407
  Epoch 021 - train 0.14062 | val 0.12442
  Regression -> MSE: 0.000168, MAE: 0.010368, R²: -0.0073
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.16217 | val 0.16923
  Epoch 020 - train 0.14988 | val 0.18460
  Epoch 021 - train 0.13776 | val 0.18469
  Regression -> MSE: 0.000194, MAE: 0.010833, R²: -0.0794
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13291 | val 0.14589
  Epoch 020 - train 0.13789 | val 0.14726
  Epoch 021 - train 0.12738 | val 0.14743
  Regression -> MSE: 0.000349, MAE: 0.012323, R²: -0.0173
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.15992 | val 0.09479
  Epoch 020 - train 0.13988 | val 0.09422
  Epoch 021 - train 0.15688 | val 0.09453
  Regression -> MSE: 0.000109, MAE: 0.008358, R²: -0.0351
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15033 | val 0.19631
  Epoch 020 - train 0.14109 | val 0.19682
  Epoch 021 - train 0.13871 | val 0.19661
  Regression -> MSE: 0.000224, MAE: 0.011472, R²: -0.0270
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14184 | val 0.24551
  Epoch 020 - train 0.13674 | val 0.26396
  Epoch 021 - train 0.14929 | val 0.26598
  Regression -> MSE: 0.000094, MAE: 0.007561, R²: -0.2078
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13995 | val 0.11085
  Epoch 020 - train 0.12397 | val 0.11069
  Epoch 021 - train 0.14192 | val 0.11086
  Regression -> MSE: 0.000321, MAE: 0.014561, R²: -0.0423
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14861 | val 0.08809
  Epoch 020 - train 0.15283 | val 0.09118
  Epoch 021 - train 0.14648 | val 0.09211
  Regression -> MSE: 0.000252, MAE: 0.011488, R²: -0.0347
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14347 | val 0.19240
  Epoch 020 - train 0.13663 | val 0.19155
  Epoch 021 - train 0.14107 | val 0.19062
  Regression -> MSE: 0.000086, MAE: 0.007072, R²: -0.0650
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14952 | val 0.17561
  Epoch 020 - train 0.14440 | val 0.17181
  Epoch 030 - train 0.14004 | val 0.18455
  Regression -> MSE: 0.000315, MAE: 0.014509, R²: -0.0253
  Directional -> Accuracy: 0.5745, MCC: 0.2986, F1: 0.2857

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14576 | val 0.17424
  Epoch 020 - train 0.12587 | val 0.16585
  Epoch 030 - train 0.13387 | val 0.16468
  Regression -> MSE: 0.000098, MAE: 0.007285, R²: -0.0013
  Directional -> Accuracy: 0.5227, MCC: -0.0541, F1: 0.6557

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15576 | val 0.17486
  Epoch 020 - train 0.16261 | val 0.18467
  Epoch 021 - train 0.16828 | val 0.18547
  Regression -> MSE: 0.000172, MAE: 0.009557, R²: -0.0032
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14853 | val 0.16034
  Epoch 020 - train 0.13442 | val 0.16571
  Epoch 021 - train 0.13219 | val 0.16682
  Regression -> MSE: 0.000225, MAE: 0.011776, R²: -0.0095
  Directional -> Accuracy: 0.5000, MCC: 0.0340, F1: 0.3913

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14667 | val 0.17891
  Epoch 020 - train 0.13812 | val 0.18500
  Epoch 021 - train 0.14597 | val 0.18723

[I 2026-02-24 01:20:44,761] Trial 84 finished with value: -0.011435787394901607 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 7.320839290493222e-05, 'weight_decay': 1.7911298638781378e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.21997001568648492, 'early_stopping_min_delta': 0.008841880279099264}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.14171 | val 0.20033
  Epoch 021 - train 0.13607 | val 0.20033
  Regression -> MSE: 0.000241, MAE: 0.012327, R²: -0.0144
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 36
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15282 | val 0.23959
  Epoch 020 - train 0.15979 | val 0.23980
  Epoch 021 - train 0.14795 | val 0.23991
  Regression -> MSE: 0.000253, MAE: 0.012695, R²: -0.0736
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.6168

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 112). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16035 | val 0.17602
  Epoch 020 - train 0.15276 | val 0.18030
  Epoch 021 - train 0.16117 | val 0.18053
  Regression -> MSE: 0.000719, MAE: 0.019739, R²: -0.0084
  Directional -> Accuracy: 0.6047, MCC: 0.0000, F1: 0.7536

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for AEP (109 < 112). Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 112). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16016 | val 0.27535
  Epoch 020 - train 0.15463 | val 0.29168
  Epoch 021 - train 0.15884 | val 0.29276
  Regression -> MSE: 0.000321, MAE: 0.014592, R²: -0.0093
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14343 | val 0.21352
  Epoch 020 - train 0.13589 | val 0.19805
  Epoch 021 - train 0.15285 | val 0.21831
  Regression -> MSE: 0.000356, MAE: 0.014660, R²: 0.0018
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15751 | val 0.16132
  Epoch 020 - train 0.16296 | val 0.17560
  Epoch 021 - train 0.15116 | val 0.17572
  Regression -> MSE: 0.000213, MAE: 0.010271, R²: -0.0117
  Directional -> Accuracy: 0.5208, MCC: 0.0000, F1: 0.6849

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15446 | val 0.26741
  Epoch 020 - train 0.14849 | val 0.26992
  Epoch 021 - train 0.14529 | val 0.27034
  Regression -> MSE: 0.000592, MAE: 0.018637, R²: -0.0562
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.17503 | val 0.19280
  Epoch 020 - train 0.15981 | val 0.19205
  Epoch 021 - train 0.16470 | val 0.19163
  Regression -> MSE: 0.000261, MAE: 0.012841, R²: -0.0212
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 112). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 112). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.16630 | val 0.18621
  Epoch 020 - train 0.14988 | val 0.20639
  Epoch 021 - train 0.15992 | val 0.21000
  Regression -> MSE: 0.000603, MAE: 0.019365, R²: -0.0411
  Directional -> Accuracy: 0.4359, MCC: 0.0000, F1: 0.6071

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15471 | val 0.22364
  Epoch 020 - train 0.14996 | val 0.22765
  Epoch 021 - train 0.15354 | val 0.22754
  Regression -> MSE: 0.000382, MAE: 0.016120, R²: -0.0009
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 112). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 112). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 112). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16352 | val 0.20601
  Epoch 020 - train 0.15631 | val 0.21049
  Epoch 021 - train 0.15075 | val 0.21169
  Regression -> MSE: 0.000248, MAE: 0.011864, R²: -0.0035
  Directional -> Accuracy: 0.5821, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14593 | val 0.25486
  Epoch 020 - train 0.14786 | val 0.29994
  Epoch 021 - train 0.14368 | val 0.30148
  Regression -> MSE: 0.000315, MAE: 0.013356, R²: -0.0088
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15785 | val 0.19407
  Epoch 020 - train 0.15638 | val 0.19928
  Epoch 021 - train 0.16163 | val 0.19929
  Regression -> MSE: 0.000700, MAE: 0.019757, R²: -0.0071
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 112). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.15918 | val 0.16212
  Epoch 020 - train 0.15357 | val 0.20549
  Epoch 021 - train 0.15621 | val 0.20690
  Regression -> MSE: 0.000145, MAE: 0.009532, R²: -0.0019
  Directional -> Accuracy: 0.4792, MCC: 0.0000, F1: 0.6479

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 112). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13736 | val 0.21535
  Epoch 020 - train 0.13950 | val 0.21559
  Epoch 021 - train 0.14029 | val 0.21512
  Regression -> MSE: 0.000229, MAE: 0.010641, R²: 0.0004
  Directional -> Accuracy: 0.5172, MCC: 0.0000, F1: 0.6818

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16203 | val 0.34221
  Epoch 020 - train 0.16521 | val 0.36896
  Epoch 021 - train 0.15299 | val 0.36660
  Regression -> MSE: 0.000374, MAE: 0.016297, R²: -0.0003
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16700 | val 0.16169
  Epoch 020 - train 0.16207 | val 0.15889
  Epoch 030 - train 0.16363 | val 0.16126
  Regression -> MSE: 0.000115, MAE: 0.008138, R²: -0.0533
  Directional -> Accuracy: 0.5970, MCC: 0.1994, F1: 0.7097

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 112). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14760 | val 0.28596
  Epoch 020 - train 0.15684 | val 0.33679
  Epoch 021 - train 0.16284 | val 0.33942
  Regression -> MSE: 0.000153, MAE: 0.009479, R²: -0.0079
  Directional -> Accuracy: 0.6071, MCC: 0.0000, F1: 0.7556

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16309 | val 0.17651
  Epoch 020 - train 0.16136 | val 0.17456
  Epoch 021 - train 0.15922 | val 0.17671
  Regression -> MSE: 0.000277, MAE: 0.013083, R²: 0.0003
  Directional -> Accuracy: 0.5890, MCC: 0.0000, F1: 0.7414

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14909 | val 0.21632
  Epoch 020 - train 0.13466 | val 0.20824
  Epoch 021 - train 0.13929 | val 0.20830
  Regression -> MSE: 0.000160, MAE: 0.009012, R²: -0.0394
  Directional -> Accuracy: 0.5806, MCC: 0.0000, F1: 0.7347

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 112). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16902 | val 0.28112
  Epoch 020 - train 0.15633 | val 0.26847
  Epoch 021 - train 0.16069 | val 0.26759
  Regression -> MSE: 0.000237, MAE: 0.010958, R²: -0.0407
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15545 | val 0.20830
  Epoch 020 - train 0.16378 | val 0.21787
  Epoch 021 - train 0.15546 | val 0.21782
  Regression -> MSE: 0.000149, MAE: 0.008460, R²: -0.0093
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 112). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 112). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 112). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14409 | val 0.19307
  Epoch 020 - train 0.14969 | val 0.19338
  Epoch 021 - train 0.14727 | val 0.19324
  Regression -> MSE: 0.000171, MAE: 0.010619, R²: -0.0036
  Directional -> Accuracy: 0.4921, MCC: 0.0000, F1: 0.6596

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16915 | val 0.18519
  Epoch 020 - train 0.16157 | val 0.20624
  Epoch 021 - train 0.15906 | val 0.20729
  Regression -> MSE: 0.000097, MAE: 0.007673, R²: -0.0956
  Directional -> Accuracy: 0.4182, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16122 | val 0.21322
  Epoch 020 - train 0.15599 | val 0.26050
  Epoch 021 - train 0.15106 | val 0.25966
  Regression -> MSE: 0.000218, MAE: 0.011384, R²: -0.0053
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14816 | val 0.15403
  Epoch 020 - train 0.15008 | val 0.14981
  Epoch 021 - train 0.15505 | val 0.15052
  Regression -> MSE: 0.000094, MAE: 0.007989, R²: -0.0461
  Directional -> Accuracy: 0.5472, MCC: 0.0000, F1: 0.7073

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17017 | val 0.17774
  Epoch 020 - train 0.14497 | val 0.17346
  Epoch 021 - train 0.15053 | val 0.17253
  Regression -> MSE: 0.000112, MAE: 0.008916, R²: -0.2184
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.17236 | val 0.12068
  Epoch 020 - train 0.15766 | val 0.14841
  Epoch 021 - train 0.17629 | val 0.15467
  Regression -> MSE: 0.000278, MAE: 0.013130, R²: -0.0003
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.7368

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.16321 | val 0.20349
  Epoch 020 - train 0.15227 | val 0.20510
  Epoch 021 - train 0.15471 | val 0.20497
  Regression -> MSE: 0.000178, MAE: 0.007793, R²: -0.0342
  Directional -> Accuracy: 0.5370, MCC: 0.0000, F1: 0.6988

[49/88] Processing MDT...

Processing MDT (Healthcare)...
Insufficient data for proper time series validation for MDT. Skipping...

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16289 | val 0.26854
  Epoch 020 - train 0.15762 | val 0.28186
  Epoch 021 - train 0.15395 | val 0.28376
  Regression -> MSE: 0.000241, MAE: 0.010119, R²: -0.0047
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15883 | val 0.18096
  Epoch 020 - train 0.17392 | val 0.18963
  Epoch 021 - train 0.16802 | val 0.19003
  Regression -> MSE: 0.000149, MAE: 0.008752, R²: -0.0433
  Directional -> Accuracy: 0.4500, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15995 | val 0.20372
  Epoch 020 - train 0.15475 | val 0.20343
  Epoch 021 - train 0.15997 | val 0.20344
  Regression -> MSE: 0.000194, MAE: 0.010458, R²: -0.0163
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14184 | val 0.18428
  Epoch 020 - train 0.13435 | val 0.18343
  Epoch 021 - train 0.13822 | val 0.18342
  Regression -> MSE: 0.000272, MAE: 0.010532, R²: -0.0231
  Directional -> Accuracy: 0.5571, MCC: 0.0000, F1: 0.7156

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 112). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14612 | val 0.14094
  Epoch 020 - train 0.14295 | val 0.14978
  Epoch 021 - train 0.14808 | val 0.14941
  Regression -> MSE: 0.000215, MAE: 0.011218, R²: -0.0305
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.6389

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for PCG (101 < 112). Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14719 | val 0.15209
  Epoch 020 - train 0.14332 | val 0.16108
  Epoch 021 - train 0.14354 | val 0.16063
  Regression -> MSE: 0.000359, MAE: 0.012427, R²: -0.0048
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.15948 | val 0.11356
  Epoch 020 - train 0.16131 | val 0.11632
  Epoch 021 - train 0.15102 | val 0.11817
  Regression -> MSE: 0.000111, MAE: 0.007862, R²: -0.1470
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14795 | val 0.24290
  Epoch 020 - train 0.15219 | val 0.24831
  Epoch 021 - train 0.15586 | val 0.24846
  Regression -> MSE: 0.000218, MAE: 0.011245, R²: -0.0033
  Directional -> Accuracy: 0.4630, MCC: 0.0000, F1: 0.6329

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15227 | val 0.29752
  Epoch 020 - train 0.14723 | val 0.29881
  Epoch 021 - train 0.14950 | val 0.29902
  Regression -> MSE: 0.000075, MAE: 0.006675, R²: -0.0481
  Directional -> Accuracy: 0.6136, MCC: 0.0000, F1: 0.7606

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 112). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for PPL (108 < 112). Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 112). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 112). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 112). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15908 | val 0.11412
  Epoch 020 - train 0.16535 | val 0.10898
  Epoch 021 - train 0.16090 | val 0.10885
  Regression -> MSE: 0.000299, MAE: 0.013438, R²: -0.0002
  Directional -> Accuracy: 0.6667, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 112). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 112). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 112). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14755 | val 0.20437
  Epoch 020 - train 0.15564 | val 0.21840
  Epoch 021 - train 0.15159 | val 0.21993
  Regression -> MSE: 0.000081, MAE: 0.006939, R²: -0.0335
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 112). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 112). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 112). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 112). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17147 | val 0.24172
  Epoch 020 - train 0.16466 | val 0.27366
  Epoch 021 - train 0.15890 | val 0.27315
  Regression -> MSE: 0.000285, MAE: 0.013930, R²: -0.0092
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16423 | val 0.14846
  Epoch 020 - train 0.13818 | val 0.14699
  Epoch 021 - train 0.14710 | val 0.14684
  Regression -> MSE: 0.000111, MAE: 0.007553, R²: -0.0229
  Directional -> Accuracy: 0.5897, MCC: 0.0000, F1: 0.7419

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15918 | val 0.21646
  Epoch 020 - train 0.15796 | val 0.24416
  Epoch 021 - train 0.15662 | val 0.24611
  Regression -> MSE: 0.000188, MAE: 0.010632, R²: -0.0311
  Directional -> Accuracy: 0.3778, MCC: 0.0000, F1: 0.5484

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.15654 | val 0.18363
  Epoch 020 - train 0.16203 | val 0.18835
  Epoch 021 - train 0.15722 | val 0.18820
  Regression -> MSE: 0.000232, MAE: 0.011966, R²: -0.0021
  Directional -> Accuracy: 0.5472, MCC: 0.0000, F1: 0.7073

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.15487 | val 0.22230
  Epoch 020 - train 0.15212 | val 0.23981
  Epoch 021 - train 0.15579 | val 0.23937
  Regression -> MSE: 0.000089, MAE: 0.007612, R²: -0.0177
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.16964 | val 0.26141
  Epoch 020 - train 0.16797 | val 0.27988
  Epoch 021 - train 0.16330 | val 0.28021
  Regression -> MSE: 0.000170, MAE: 0.010521, R²: -0.0015
  Directional -> Accuracy: 0.4902, MCC: 0.0000, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.15717 | val 0.20907
  Epoch 020 - train 0.15376 | val 0.21751
  Epoch 021 - train 0.14340 | val 0.21729

[I 2026-02-24 01:23:54,442] Trial 85 finished with value: -0.011502464704523353 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 36, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 7.479523107643647e-05, 'weight_decay': 2.4405602787420514e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.24529753771874446, 'early_stopping_min_delta': 0.00889286920396861}. Best is trial 44 with value: -0.011362814469631832.

  Regression -> MSE: 0.000248, MAE: 0.012658, R²: -0.0018
  Directional -> Accuracy: 0.4828, MCC: -0.0445, F1: 0.4231

================================================================================
Pipeline completed: 47/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (47, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07185 | val 0.09256
  Epoch 020 - train 0.07067 | val 0.09137
  Epoch 021 - train 0.07061 | val 0.09133
  Regression -> MSE: 0.000250, MAE: 0.012648, R²: -0.0102
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07750 | val 0.07798
  Epoch 020 - train 0.07054 | val 0.10475
  Epoch 021 - train 0.07242 | val 0.10601
  Regression -> MSE: 0.000708, MAE: 0.019764, R²: -0.0337
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07347 | val 0.11545
  Epoch 020 - train 0.07470 | val 0.11787
  Epoch 021 - train 0.07259 | val 0.11740
  Regression -> MSE: 0.000311, MAE: 0.014396, R²: -0.0029
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06242 | val 0.10998
  Epoch 020 - train 0.06027 | val 0.12478
  Epoch 021 - train 0.05975 | val 0.12266
  Regression -> MSE: 0.000350, MAE: 0.014596, R²: -0.0032
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07055 | val 0.08001
  Epoch 020 - train 0.07324 | val 0.08266
  Epoch 021 - train 0.07429 | val 0.08308
  Regression -> MSE: 0.000207, MAE: 0.010472, R²: -0.0171
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07119 | val 0.13257
  Epoch 020 - train 0.06673 | val 0.13594
  Epoch 021 - train 0.06907 | val 0.13619
  Regression -> MSE: 0.000559, MAE: 0.018154, R²: -0.0073
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07490 | val 0.08910
  Epoch 020 - train 0.07021 | val 0.08955
  Epoch 021 - train 0.07249 | val 0.08940
  Regression -> MSE: 0.000246, MAE: 0.012127, R²: -0.0027
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07357 | val 0.08802
  Epoch 020 - train 0.07049 | val 0.09558
  Epoch 021 - train 0.06863 | val 0.09706
  Regression -> MSE: 0.000607, MAE: 0.019384, R²: -0.0161
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07198 | val 0.08831
  Epoch 020 - train 0.06812 | val 0.08975
  Epoch 021 - train 0.06954 | val 0.08986
  Regression -> MSE: 0.000390, MAE: 0.015931, R²: -0.0172
  Directional -> Accuracy: 0.5714, MCC: 0.2278, F1: 0.6441

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07345 | val 0.09424
  Epoch 020 - train 0.07165 | val 0.10080
  Epoch 021 - train 0.07187 | val 0.10067
  Regression -> MSE: 0.000242, MAE: 0.012048, R²: -0.0037
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06806 | val 0.10736
  Epoch 020 - train 0.06672 | val 0.11839
  Epoch 021 - train 0.06729 | val 0.11760
  Regression -> MSE: 0.000314, MAE: 0.013617, R²: -0.0105
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07285 | val 0.08846
  Epoch 020 - train 0.07675 | val 0.09331
  Epoch 021 - train 0.07329 | val 0.09343
  Regression -> MSE: 0.000678, MAE: 0.019529, R²: -0.0008
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07188 | val 0.07894
  Epoch 020 - train 0.07379 | val 0.09729
  Epoch 021 - train 0.07308 | val 0.09785
  Regression -> MSE: 0.000142, MAE: 0.009405, R²: -0.0311
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06688 | val 0.09873
  Epoch 020 - train 0.06808 | val 0.10033
  Epoch 021 - train 0.06683 | val 0.10034
  Regression -> MSE: 0.000225, MAE: 0.010697, R²: -0.0006
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07396 | val 0.14888
  Epoch 020 - train 0.07187 | val 0.15428
  Epoch 021 - train 0.07282 | val 0.15367
  Regression -> MSE: 0.000364, MAE: 0.015958, R²: -0.0054
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07646 | val 0.07890
  Epoch 020 - train 0.07273 | val 0.08033
  Epoch 021 - train 0.07563 | val 0.08060
  Regression -> MSE: 0.000110, MAE: 0.008183, R²: -0.0172
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07113 | val 0.14370
  Epoch 020 - train 0.06983 | val 0.16532
  Epoch 021 - train 0.07045 | val 0.16515
  Regression -> MSE: 0.000156, MAE: 0.009640, R²: 0.0000
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07979 | val 0.07918
  Epoch 020 - train 0.07697 | val 0.07908
  Epoch 021 - train 0.07946 | val 0.07846
  Regression -> MSE: 0.000278, MAE: 0.013330, R²: -0.0200
  Directional -> Accuracy: 0.3816, MCC: -0.1880, F1: 0.3562

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06689 | val 0.09688
  Epoch 020 - train 0.06726 | val 0.09566
  Epoch 021 - train 0.06634 | val 0.09571
  Regression -> MSE: 0.000169, MAE: 0.009182, R²: -0.1281
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07612 | val 0.12106
  Epoch 020 - train 0.07114 | val 0.12881
  Epoch 021 - train 0.07182 | val 0.12824
  Regression -> MSE: 0.000228, MAE: 0.010872, R²: -0.0064
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07297 | val 0.09197
  Epoch 020 - train 0.07475 | val 0.09213
  Epoch 021 - train 0.07405 | val 0.09285
  Regression -> MSE: 0.000154, MAE: 0.008885, R²: -0.0777
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07259 | val 0.08597
  Epoch 020 - train 0.07196 | val 0.08558
  Epoch 021 - train 0.06974 | val 0.08591
  Regression -> MSE: 0.000168, MAE: 0.010270, R²: -0.0196
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07694 | val 0.08566
  Epoch 020 - train 0.07495 | val 0.08712
  Epoch 021 - train 0.07643 | val 0.08702
  Regression -> MSE: 0.000090, MAE: 0.007293, R²: -0.0530
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07185 | val 0.09691
  Epoch 020 - train 0.07119 | val 0.09775
  Epoch 021 - train 0.07263 | val 0.09787
  Regression -> MSE: 0.000213, MAE: 0.011056, R²: -0.0043
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06693 | val 0.06573
  Epoch 020 - train 0.06728 | val 0.06409
  Epoch 021 - train 0.06552 | val 0.06402
  Regression -> MSE: 0.000094, MAE: 0.008099, R²: -0.0205
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07677 | val 0.06111
  Epoch 020 - train 0.07148 | val 0.06304
  Epoch 021 - train 0.07031 | val 0.06310
  Regression -> MSE: 0.000113, MAE: 0.009122, R²: -0.0987
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07588 | val 0.07510
  Epoch 020 - train 0.07591 | val 0.08097
  Epoch 021 - train 0.07435 | val 0.08025
  Regression -> MSE: 0.000242, MAE: 0.012906, R²: -0.0472
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07170 | val 0.08417
  Epoch 020 - train 0.07220 | val 0.08467
  Epoch 021 - train 0.07445 | val 0.08452
  Regression -> MSE: 0.000188, MAE: 0.008110, R²: -0.1274
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07332 | val 0.06418
  Epoch 020 - train 0.07688 | val 0.06554
  Epoch 021 - train 0.07960 | val 0.06552
  Regression -> MSE: 0.000237, MAE: 0.011869, R²: -0.0012
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07319 | val 0.11314
  Epoch 020 - train 0.07177 | val 0.12260
  Epoch 021 - train 0.07604 | val 0.12340
  Regression -> MSE: 0.000231, MAE: 0.009863, R²: -0.0007
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07178 | val 0.09447
  Epoch 020 - train 0.07234 | val 0.09132
  Epoch 021 - train 0.07135 | val 0.09157
  Regression -> MSE: 0.000145, MAE: 0.008703, R²: -0.0721
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07695 | val 0.09179
  Epoch 020 - train 0.07052 | val 0.09670
  Epoch 021 - train 0.07388 | val 0.09688
  Regression -> MSE: 0.000189, MAE: 0.010429, R²: -0.0036
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06695 | val 0.08061
  Epoch 020 - train 0.06541 | val 0.08168
  Epoch 028 - train 0.06515 | val 0.08211
  Regression -> MSE: 0.000287, MAE: 0.011770, R²: -0.0961
  Directional -> Accuracy: 0.5616, MCC: 0.1530, F1: 0.5429

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.06644 | val 0.06407
  Epoch 020 - train 0.06640 | val 0.06138
  Epoch 021 - train 0.06830 | val 0.06116
  Regression -> MSE: 0.000167, MAE: 0.010372, R²: -0.0035
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06710 | val 0.07422
  Epoch 020 - train 0.06746 | val 0.08293
  Epoch 021 - train 0.06793 | val 0.08347
  Regression -> MSE: 0.000182, MAE: 0.010393, R²: -0.0103
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07108 | val 0.06648
  Epoch 020 - train 0.06979 | val 0.06759
  Epoch 021 - train 0.06873 | val 0.06758
  Regression -> MSE: 0.000346, MAE: 0.011711, R²: -0.0086
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.07622 | val 0.04885
  Epoch 020 - train 0.07874 | val 0.05202
  Epoch 021 - train 0.07741 | val 0.05226
  Regression -> MSE: 0.000123, MAE: 0.008437, R²: -0.1745
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07507 | val 0.10492
  Epoch 020 - train 0.07580 | val 0.11481
  Epoch 021 - train 0.07647 | val 0.11445
  Regression -> MSE: 0.000219, MAE: 0.011291, R²: 0.0002
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07366 | val 0.12442
  Epoch 020 - train 0.07038 | val 0.14958
  Epoch 021 - train 0.07112 | val 0.15200
  Regression -> MSE: 0.000089, MAE: 0.007391, R²: -0.1478
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07218 | val 0.05518
  Epoch 020 - train 0.06812 | val 0.05369
  Epoch 021 - train 0.07083 | val 0.05384
  Regression -> MSE: 0.000309, MAE: 0.013735, R²: -0.0030
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07995 | val 0.04868
  Epoch 020 - train 0.07405 | val 0.04868
  Epoch 021 - train 0.07491 | val 0.04870
  Regression -> MSE: 0.000256, MAE: 0.011468, R²: -0.0496
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.06696 | val 0.08572
  Epoch 020 - train 0.06705 | val 0.08375
  Epoch 021 - train 0.06711 | val 0.08358
  Regression -> MSE: 0.000081, MAE: 0.007076, R²: 0.0011
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07322 | val 0.09402
  Epoch 020 - train 0.07226 | val 0.08983
  Epoch 021 - train 0.07574 | val 0.08978
  Regression -> MSE: 0.000311, MAE: 0.014494, R²: -0.0153
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07672 | val 0.08104
  Epoch 020 - train 0.07102 | val 0.08212
  Epoch 021 - train 0.06800 | val 0.08247
  Regression -> MSE: 0.000099, MAE: 0.007210, R²: -0.0032
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.07601 | val 0.08729
  Epoch 020 - train 0.07907 | val 0.09378
  Epoch 021 - train 0.07543 | val 0.09444
  Regression -> MSE: 0.000177, MAE: 0.010315, R²: -0.0317
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07026 | val 0.08267
  Epoch 020 - train 0.06844 | val 0.08293
  Epoch 021 - train 0.06655 | val 0.08330
  Regression -> MSE: 0.000228, MAE: 0.011839, R²: -0.0208
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07397 | val 0.07927
  Epoch 020 - train 0.06834 | val 0.07954
  Epoch 021 - train 0.07287 | val 0.07955
  Regression -> MSE: 0.000096, MAE: 0.007864, R²: -0.0363
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...

[I 2026-02-24 01:25:49,364] Trial 86 finished with value: -0.011469776352545404 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 4.6625623989502994e-05, 'weight_decay': 1.7259213360582223e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.10440453924306226, 'early_stopping_min_delta': 0.006273072004057777}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.07192 | val 0.14219
  Epoch 021 - train 0.07642 | val 0.14191
  Regression -> MSE: 0.000240, MAE: 0.012339, R²: -0.0117
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.24403 | val 0.33320
  Epoch 020 - train 0.23348 | val 0.33364
  Epoch 021 - train 0.23126 | val 0.33208
  Regression -> MSE: 0.000253, MAE: 0.012768, R²: -0.0213
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.24027 | val 0.22453
  Epoch 020 - train 0.24165 | val 0.25537
  Epoch 021 - train 0.23866 | val 0.25679
  Regression -> MSE: 0.000701, MAE: 0.019630, R²: -0.0242
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.24458 | val 0.40182
  Epoch 020 - train 0.24876 | val 0.40985
  Epoch 021 - train 0.24032 | val 0.40796
  Regression -> MSE: 0.000311, MAE: 0.014398, R²: -0.0016
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.20409 | val 0.23282
  Epoch 020 - train 0.19377 | val 0.29712
  Epoch 021 - train 0.19812 | val 0.30628
  Regression -> MSE: 0.000351, MAE: 0.014565, R²: -0.0043
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.24255 | val 0.23024
  Epoch 020 - train 0.24317 | val 0.22986
  Epoch 021 - train 0.24413 | val 0.22979
  Regression -> MSE: 0.000204, MAE: 0.010073, R²: 0.0004
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.22091 | val 0.45640
  Epoch 020 - train 0.22696 | val 0.47905
  Epoch 021 - train 0.22328 | val 0.47977
  Regression -> MSE: 0.000560, MAE: 0.018164, R²: -0.0085
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.25396 | val 0.28974
  Epoch 020 - train 0.24291 | val 0.28859
  Epoch 028 - train 0.24362 | val 0.29202
  Regression -> MSE: 0.000252, MAE: 0.012314, R²: -0.0283
  Directional -> Accuracy: 0.4493, MCC: 0.1171, F1: 0.5870

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.22918 | val 0.29974
  Epoch 020 - train 0.23261 | val 0.34267
  Epoch 021 - train 0.24196 | val 0.34662
  Regression -> MSE: 0.000609, MAE: 0.019437, R²: -0.0188
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.21911 | val 0.28954
  Epoch 020 - train 0.21743 | val 0.29710
  Epoch 021 - train 0.21791 | val 0.29762
  Regression -> MSE: 0.000391, MAE: 0.015930, R²: -0.0187
  Directional -> Accuracy: 0.6735, MCC: 0.3467, F1: 0.6522

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.24396 | val 0.32494
  Epoch 020 - train 0.22917 | val 0.32817
  Epoch 021 - train 0.22469 | val 0.32650
  Regression -> MSE: 0.000242, MAE: 0.011764, R²: -0.0025
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.21904 | val 0.38078
  Epoch 020 - train 0.21592 | val 0.42013
  Epoch 021 - train 0.22258 | val 0.41716
  Regression -> MSE: 0.000311, MAE: 0.013648, R²: 0.0001
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.24632 | val 0.27340
  Epoch 020 - train 0.24170 | val 0.30116
  Epoch 021 - train 0.24521 | val 0.30014
  Regression -> MSE: 0.000682, MAE: 0.019642, R²: -0.0075
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.23767 | val 0.24335
  Epoch 020 - train 0.23255 | val 0.27622
  Epoch 021 - train 0.23543 | val 0.27711
  Regression -> MSE: 0.000139, MAE: 0.009018, R²: -0.0065
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.23678 | val 0.32114
  Epoch 020 - train 0.22483 | val 0.32082
  Epoch 021 - train 0.22112 | val 0.32131
  Regression -> MSE: 0.000230, MAE: 0.010848, R²: -0.0221
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.21993 | val 0.51259
  Epoch 020 - train 0.22934 | val 0.50839
  Epoch 021 - train 0.23466 | val 0.50926
  Regression -> MSE: 0.000362, MAE: 0.016175, R²: -0.0007
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.23156 | val 0.22844
  Epoch 020 - train 0.24021 | val 0.23361
  Epoch 029 - train 0.23587 | val 0.23540
  Regression -> MSE: 0.000108, MAE: 0.008049, R²: 0.0012
  Directional -> Accuracy: 0.5286, MCC: 0.0387, F1: 0.5926

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.22242 | val 0.47575
  Epoch 020 - train 0.21742 | val 0.53766
  Epoch 021 - train 0.21661 | val 0.54003
  Regression -> MSE: 0.000159, MAE: 0.010003, R²: -0.0183
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.23828 | val 0.26600
  Epoch 020 - train 0.24001 | val 0.26672
  Epoch 021 - train 0.22617 | val 0.26770
  Regression -> MSE: 0.000283, MAE: 0.013575, R²: -0.0411
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.21241 | val 0.32794
  Epoch 020 - train 0.21436 | val 0.32327
  Epoch 021 - train 0.20564 | val 0.32434
  Regression -> MSE: 0.000153, MAE: 0.008751, R²: -0.0252
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.23872 | val 0.34312
  Epoch 020 - train 0.24386 | val 0.35441
  Epoch 021 - train 0.23206 | val 0.35437
  Regression -> MSE: 0.000236, MAE: 0.010984, R²: -0.0450
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.24965 | val 0.30391
  Epoch 020 - train 0.23422 | val 0.31114
  Epoch 021 - train 0.23991 | val 0.31087
  Regression -> MSE: 0.000153, MAE: 0.008807, R²: -0.0645
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.22240 | val 0.28656
  Epoch 020 - train 0.23315 | val 0.28808
  Epoch 021 - train 0.22908 | val 0.28792
  Regression -> MSE: 0.000167, MAE: 0.010274, R²: -0.0128
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.24435 | val 0.28319
  Epoch 020 - train 0.25727 | val 0.27826
  Epoch 021 - train 0.23829 | val 0.27857
  Regression -> MSE: 0.000090, MAE: 0.007328, R²: -0.0607
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.23377 | val 0.47821
  Epoch 020 - train 0.23406 | val 0.53011
  Epoch 021 - train 0.23937 | val 0.52520
  Regression -> MSE: 0.000215, MAE: 0.011021, R²: -0.0139
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.22775 | val 0.21382
  Epoch 020 - train 0.21987 | val 0.21201
  Epoch 021 - train 0.22917 | val 0.21176
  Regression -> MSE: 0.000101, MAE: 0.008229, R²: -0.0945
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.23994 | val 0.18785
  Epoch 020 - train 0.26002 | val 0.22111
  Epoch 021 - train 0.24928 | val 0.22441
  Regression -> MSE: 0.000109, MAE: 0.009010, R²: -0.0607
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.24370 | val 0.23228
  Epoch 020 - train 0.24419 | val 0.23843
  Epoch 021 - train 0.24133 | val 0.23987
  Regression -> MSE: 0.000242, MAE: 0.012895, R²: -0.0449
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.23933 | val 0.27638
  Epoch 020 - train 0.22569 | val 0.27207
  Epoch 021 - train 0.22914 | val 0.27235
  Regression -> MSE: 0.000178, MAE: 0.007938, R²: -0.0694
  Directional -> Accuracy: 0.4211, MCC: -0.2054, F1: 0.5217

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.23246 | val 0.19243
  Epoch 020 - train 0.23336 | val 0.20355
  Epoch 021 - train 0.24581 | val 0.20549
  Regression -> MSE: 0.000238, MAE: 0.011894, R²: -0.0047
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.24483 | val 0.38972
  Epoch 020 - train 0.22719 | val 0.45135
  Epoch 021 - train 0.22722 | val 0.45397
  Regression -> MSE: 0.000231, MAE: 0.009874, R²: -0.0008
  Directional -> Accuracy: 0.4186, MCC: -0.1746, F1: 0.3243

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.25442 | val 0.28635
  Epoch 020 - train 0.23393 | val 0.29511
  Epoch 021 - train 0.25160 | val 0.29581
  Regression -> MSE: 0.000136, MAE: 0.008250, R²: -0.0052
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.24196 | val 0.30201
  Epoch 020 - train 0.22059 | val 0.31390
  Epoch 021 - train 0.22248 | val 0.31450
  Regression -> MSE: 0.000192, MAE: 0.010406, R²: -0.0218
  Directional -> Accuracy: 0.4800, MCC: -0.0467, F1: 0.5185

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.22021 | val 0.27549
  Epoch 020 - train 0.20646 | val 0.26724
  Epoch 021 - train 0.20821 | val 0.26656
  Regression -> MSE: 0.000280, MAE: 0.010928, R²: -0.0678
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.25339 | val 0.19850
  Epoch 020 - train 0.24734 | val 0.20704
  Epoch 021 - train 0.23465 | val 0.20922
  Regression -> MSE: 0.000167, MAE: 0.010364, R²: -0.0028
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.20837 | val 0.29182
  Epoch 020 - train 0.21183 | val 0.37823
  Epoch 021 - train 0.21643 | val 0.37953
  Regression -> MSE: 0.000185, MAE: 0.010530, R²: -0.0260
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.21826 | val 0.22865
  Epoch 020 - train 0.22179 | val 0.23438
  Epoch 021 - train 0.22952 | val 0.23489
  Regression -> MSE: 0.000342, MAE: 0.011769, R²: 0.0005
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.25034 | val 0.14617
  Epoch 020 - train 0.25653 | val 0.16911
  Epoch 021 - train 0.26776 | val 0.16946
  Regression -> MSE: 0.000113, MAE: 0.008308, R²: -0.0747
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.23839 | val 0.33389
  Epoch 020 - train 0.23881 | val 0.33804
  Epoch 021 - train 0.23225 | val 0.33821
  Regression -> MSE: 0.000223, MAE: 0.011424, R²: -0.0211
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.24906 | val 0.41928
  Epoch 020 - train 0.22402 | val 0.42203
  Epoch 021 - train 0.24058 | val 0.42221
  Regression -> MSE: 0.000088, MAE: 0.007346, R²: -0.1346
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.23202 | val 0.17555
  Epoch 020 - train 0.22536 | val 0.16258
  Epoch 030 - train 0.23019 | val 0.16275
  Regression -> MSE: 0.000314, MAE: 0.014287, R²: -0.0193
  Directional -> Accuracy: 0.4694, MCC: 0.1901, F1: 0.5667

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.24677 | val 0.13947
  Epoch 020 - train 0.24639 | val 0.13553
  Epoch 030 - train 0.26458 | val 0.18058
  Regression -> MSE: 0.000262, MAE: 0.011559, R²: -0.0745
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.23411 | val 0.29702
  Epoch 020 - train 0.23276 | val 0.29587
  Epoch 021 - train 0.21901 | val 0.29526
  Regression -> MSE: 0.000082, MAE: 0.007051, R²: -0.0202
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.22928 | val 0.29189
  Epoch 020 - train 0.24887 | val 0.40177
  Epoch 021 - train 0.23965 | val 0.41215
  Regression -> MSE: 0.000307, MAE: 0.014497, R²: -0.0010
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.25707 | val 0.24890
  Epoch 020 - train 0.23603 | val 0.23904
  Epoch 030 - train 0.23534 | val 0.23982
  Regression -> MSE: 0.000099, MAE: 0.007435, R²: -0.0071
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.25544 | val 0.28958
  Epoch 020 - train 0.26003 | val 0.29915
  Epoch 021 - train 0.25943 | val 0.30003
  Regression -> MSE: 0.000177, MAE: 0.010275, R²: -0.0285
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.20884 | val 0.29072
  Epoch 020 - train 0.22065 | val 0.31250
  Epoch 021 - train 0.20985 | val 0.31299
  Regression -> MSE: 0.000225, MAE: 0.011761, R²: -0.0102
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.24683 | val 0.27197
  Epoch 020 - train 0.24139 | val 0.27360
  Epoch 021 - train 0.23531 | val 0.27475

[I 2026-02-24 01:27:46,908] Trial 87 finished with value: -0.0114534129571942 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 2.9988497193863027e-05, 'weight_decay': 3.0663603656509165e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.40412672579482845, 'early_stopping_min_delta': 0.009397054787011569}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.24880 | val 0.38447
  Epoch 021 - train 0.22824 | val 0.38502
  Regression -> MSE: 0.000237, MAE: 0.012487, R²: 0.0005
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11998 | val 0.18111
  Epoch 020 - train 0.12660 | val 0.18383
  Epoch 021 - train 0.11808 | val 0.18647
  Regression -> MSE: 0.000246, MAE: 0.012496, R²: -0.0031
  Directional -> Accuracy: 0.5385, MCC: -0.1028, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12803 | val 0.12493
  Epoch 020 - train 0.12597 | val 0.12295
  Epoch 021 - train 0.11580 | val 0.12415
  Regression -> MSE: 0.000685, MAE: 0.019441, R²: 0.0088
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13443 | val 0.21062
  Epoch 020 - train 0.13021 | val 0.21080
  Epoch 030 - train 0.12374 | val 0.21498
  Regression -> MSE: 0.000392, MAE: 0.015344, R²: -0.1338
  Directional -> Accuracy: 0.5833, MCC: 0.2223, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11591 | val 0.25828
  Epoch 020 - train 0.10934 | val 0.30678
  Epoch 021 - train 0.10366 | val 0.30377
  Regression -> MSE: 0.000366, MAE: 0.014742, R²: -0.0623
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12114 | val 0.12115
  Epoch 020 - train 0.11874 | val 0.12609
  Epoch 027 - train 0.11904 | val 0.12408
  Regression -> MSE: 0.000187, MAE: 0.009327, R²: 0.0668
  Directional -> Accuracy: 0.6538, MCC: 0.3880, F1: 0.5714

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12483 | val 0.23812
  Epoch 020 - train 0.11313 | val 0.23816
  Epoch 021 - train 0.13042 | val 0.23856
  Regression -> MSE: 0.000576, MAE: 0.018429, R²: -0.0060
  Directional -> Accuracy: 0.5102, MCC: 0.0000, F1: 0.6757

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13107 | val 0.18081
  Epoch 020 - train 0.12834 | val 0.19442
  Epoch 021 - train 0.12461 | val 0.19556
  Regression -> MSE: 0.000245, MAE: 0.012091, R²: 0.0023
  Directional -> Accuracy: 0.4286, MCC: -0.0292, F1: 0.5238

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12468 | val 0.29025
  Epoch 020 - train 0.11970 | val 0.27418
  Epoch 021 - train 0.11032 | val 0.27392
  Regression -> MSE: 0.000614, MAE: 0.019469, R²: -0.0495
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12678 | val 0.19345
  Epoch 020 - train 0.11147 | val 0.19228
  Epoch 021 - train 0.11470 | val 0.19196
  Regression -> MSE: 0.000340, MAE: 0.014935, R²: -0.0047
  Directional -> Accuracy: 0.3810, MCC: -0.1370, F1: 0.4583

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12909 | val 0.32361
  Epoch 020 - train 0.12479 | val 0.33501
  Epoch 021 - train 0.12426 | val 0.35101
  Regression -> MSE: 0.000241, MAE: 0.011505, R²: -0.0111
  Directional -> Accuracy: 0.5211, MCC: -0.0382, F1: 0.2609

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12168 | val 0.26073
  Epoch 020 - train 0.11305 | val 0.25984
  Epoch 021 - train 0.11705 | val 0.26045
  Regression -> MSE: 0.000304, MAE: 0.013571, R²: 0.0072
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.6400

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14061 | val 0.14939
  Epoch 020 - train 0.13139 | val 0.17537
  Epoch 021 - train 0.13582 | val 0.18223
  Regression -> MSE: 0.000674, MAE: 0.019613, R²: -0.0065
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13186 | val 0.20518
  Epoch 020 - train 0.12487 | val 0.23843
  Epoch 021 - train 0.12418 | val 0.24578
  Regression -> MSE: 0.000155, MAE: 0.009906, R²: -0.0378
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12793 | val 0.16259
  Epoch 020 - train 0.11943 | val 0.16355
  Epoch 027 - train 0.11789 | val 0.16421
  Regression -> MSE: 0.000221, MAE: 0.010910, R²: 0.0147
  Directional -> Accuracy: 0.6290, MCC: 0.2760, F1: 0.5490

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12198 | val 0.30967
  Epoch 020 - train 0.11611 | val 0.34909
  Epoch 021 - train 0.11925 | val 0.33932
  Regression -> MSE: 0.000373, MAE: 0.016327, R²: 0.0082
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13352 | val 0.17395
  Epoch 020 - train 0.12823 | val 0.16792
  Epoch 021 - train 0.12596 | val 0.16938
  Regression -> MSE: 0.000107, MAE: 0.007883, R²: -0.0050
  Directional -> Accuracy: 0.5070, MCC: -0.0526, F1: 0.6465

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12266 | val 0.26381
  Epoch 020 - train 0.12447 | val 0.26131
  Epoch 021 - train 0.12226 | val 0.26476
  Regression -> MSE: 0.000160, MAE: 0.010028, R²: 0.0028
  Directional -> Accuracy: 0.6500, MCC: 0.1950, F1: 0.7640

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12602 | val 0.20423
  Epoch 020 - train 0.12407 | val 0.20198
  Epoch 021 - train 0.12102 | val 0.20002
  Regression -> MSE: 0.000305, MAE: 0.014374, R²: -0.1351
  Directional -> Accuracy: 0.3896, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11445 | val 0.18458
  Epoch 020 - train 0.10575 | val 0.18280
  Epoch 028 - train 0.11334 | val 0.18440
  Regression -> MSE: 0.000292, MAE: 0.013470, R²: -0.9812
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13397 | val 0.18667
  Epoch 020 - train 0.13148 | val 0.18636
  Epoch 021 - train 0.13015 | val 0.18525
  Regression -> MSE: 0.000240, MAE: 0.011196, R²: -0.0577
  Directional -> Accuracy: 0.3421, MCC: -0.3115, F1: 0.3421

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12364 | val 0.16742
  Epoch 020 - train 0.12758 | val 0.15841
  Epoch 021 - train 0.12334 | val 0.15793
  Regression -> MSE: 0.000150, MAE: 0.008704, R²: -0.0128
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12788 | val 0.16290
  Epoch 020 - train 0.11930 | val 0.17646
  Epoch 021 - train 0.12630 | val 0.17715
  Regression -> MSE: 0.000177, MAE: 0.010593, R²: 0.0011
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13096 | val 0.18674
  Epoch 020 - train 0.13379 | val 0.20213
  Epoch 021 - train 0.13362 | val 0.20582
  Regression -> MSE: 0.000083, MAE: 0.006918, R²: 0.0112
  Directional -> Accuracy: 0.5593, MCC: 0.0789, F1: 0.6389

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12844 | val 0.26049
  Epoch 020 - train 0.12388 | val 0.28878
  Epoch 021 - train 0.12503 | val 0.28461
  Regression -> MSE: 0.000218, MAE: 0.011482, R²: 0.0026
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12496 | val 0.11669
  Epoch 020 - train 0.10684 | val 0.10485
  Epoch 030 - train 0.10668 | val 0.10734
  Regression -> MSE: 0.000120, MAE: 0.008352, R²: -0.3076
  Directional -> Accuracy: 0.5789, MCC: 0.2579, F1: 0.4783

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14866 | val 0.10690
  Epoch 020 - train 0.13724 | val 0.10892
  Epoch 021 - train 0.12733 | val 0.11193
  Regression -> MSE: 0.000127, MAE: 0.009219, R²: -0.0070
  Directional -> Accuracy: 0.5833, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14580 | val 0.16098
  Epoch 020 - train 0.13765 | val 0.18295
  Epoch 021 - train 0.13053 | val 0.18507
  Regression -> MSE: 0.000243, MAE: 0.012933, R²: -0.0224
  Directional -> Accuracy: 0.5682, MCC: -0.1269, F1: 0.7246

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12973 | val 0.15419
  Epoch 020 - train 0.12933 | val 0.16276
  Epoch 023 - train 0.12879 | val 0.16291
  Regression -> MSE: 0.000224, MAE: 0.009524, R²: -0.3663
  Directional -> Accuracy: 0.5345, MCC: 0.1948, F1: 0.3415

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14762 | val 0.12486
  Epoch 020 - train 0.13162 | val 0.11769
  Epoch 021 - train 0.13684 | val 0.11690
  Regression -> MSE: 0.000238, MAE: 0.011983, R²: -0.0158
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13416 | val 0.21732
  Epoch 020 - train 0.12022 | val 0.21350
  Epoch 021 - train 0.11396 | val 0.21501
  Regression -> MSE: 0.000253, MAE: 0.010656, R²: -0.0099
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13518 | val 0.23323
  Epoch 020 - train 0.12649 | val 0.22412
  Epoch 021 - train 0.13711 | val 0.22435
  Regression -> MSE: 0.000138, MAE: 0.008481, R²: -0.0385
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13051 | val 0.17008
  Epoch 020 - train 0.12667 | val 0.16841
  Epoch 024 - train 0.12040 | val 0.17001
  Regression -> MSE: 0.000200, MAE: 0.011104, R²: -0.0613
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12101 | val 0.15389
  Epoch 020 - train 0.11348 | val 0.15226
  Epoch 021 - train 0.11546 | val 0.15131
  Regression -> MSE: 0.000281, MAE: 0.011142, R²: -0.0872
  Directional -> Accuracy: 0.4324, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11676 | val 0.13148
  Epoch 020 - train 0.11192 | val 0.12127
  Epoch 021 - train 0.11439 | val 0.12059
  Regression -> MSE: 0.000162, MAE: 0.010096, R²: 0.0055
  Directional -> Accuracy: 0.5128, MCC: 0.0130, F1: 0.2963

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12971 | val 0.24723
  Epoch 020 - train 0.11634 | val 0.22568
  Epoch 021 - train 0.11571 | val 0.22410
  Regression -> MSE: 0.000184, MAE: 0.010515, R²: -0.0082
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12310 | val 0.14858
  Epoch 020 - train 0.11606 | val 0.15724
  Epoch 021 - train 0.12319 | val 0.15621
  Regression -> MSE: 0.000354, MAE: 0.012324, R²: -0.0132
  Directional -> Accuracy: 0.4118, MCC: -0.1417, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13417 | val 0.08887
  Epoch 020 - train 0.11737 | val 0.09397
  Epoch 029 - train 0.11267 | val 0.09887
  Regression -> MSE: 0.000123, MAE: 0.007902, R²: -0.1851
  Directional -> Accuracy: 0.6364, MCC: 0.3254, F1: 0.5000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12474 | val 0.18303
  Epoch 020 - train 0.12647 | val 0.19238
  Epoch 021 - train 0.13454 | val 0.18843
  Regression -> MSE: 0.000220, MAE: 0.011287, R²: -0.0214
  Directional -> Accuracy: 0.4655, MCC: 0.0000, F1: 0.6353

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12705 | val 0.27574
  Epoch 020 - train 0.11862 | val 0.29406
  Epoch 021 - train 0.11834 | val 0.29093
  Regression -> MSE: 0.000102, MAE: 0.007889, R²: -0.2772
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13622 | val 0.10937
  Epoch 020 - train 0.12642 | val 0.10407
  Epoch 030 - train 0.12244 | val 0.10811
  Regression -> MSE: 0.000372, MAE: 0.014321, R²: -0.1344
  Directional -> Accuracy: 0.5750, MCC: -0.0188, F1: 0.2609

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13517 | val 0.13366
  Epoch 020 - train 0.14202 | val 0.12618
  Epoch 021 - train 0.13132 | val 0.12531
  Regression -> MSE: 0.000256, MAE: 0.011269, R²: -0.0758
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12758 | val 0.28478
  Epoch 020 - train 0.11755 | val 0.27368
  Epoch 021 - train 0.11590 | val 0.27030
  Regression -> MSE: 0.000079, MAE: 0.006970, R²: 0.0169
  Directional -> Accuracy: 0.4868, MCC: -0.0294, F1: 0.5806

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14176 | val 0.19659
  Epoch 020 - train 0.12631 | val 0.25231
  Epoch 021 - train 0.12998 | val 0.24540
  Regression -> MSE: 0.000366, MAE: 0.015367, R²: -0.0170
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.2941

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13446 | val 0.16318
  Epoch 020 - train 0.12538 | val 0.17168
  Epoch 021 - train 0.12896 | val 0.17165
  Regression -> MSE: 0.000097, MAE: 0.007249, R²: 0.0013
  Directional -> Accuracy: 0.4667, MCC: 0.1348, F1: 0.0769

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13537 | val 0.23033
  Epoch 020 - train 0.13031 | val 0.24679
  Epoch 021 - train 0.13093 | val 0.24933
  Regression -> MSE: 0.000186, MAE: 0.010613, R²: -0.0260
  Directional -> Accuracy: 0.3659, MCC: 0.0000, F1: 0.5357

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13266 | val 0.21720
  Epoch 020 - train 0.12307 | val 0.24648
  Epoch 021 - train 0.12329 | val 0.24663
  Regression -> MSE: 0.000226, MAE: 0.011710, R²: -0.0305
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13088 | val 0.24911
  Epoch 020 - train 0.12192 | val 0.28275

[I 2026-02-24 01:31:20,412] Trial 88 finished with value: -0.011649647431691746 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 0.00011289847994399164, 'weight_decay': 2.8614211164172855e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.20386896897364237, 'early_stopping_min_delta': 0.005575624273727654}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.13646 | val 0.27937
  Regression -> MSE: 0.000238, MAE: 0.012222, R²: -0.0184
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.41272 | val 0.72753
  Epoch 020 - train 0.38890 | val 0.72581
  Epoch 028 - train 0.38099 | val 0.72195
  Regression -> MSE: 0.000261, MAE: 0.012902, R²: -0.0553
  Directional -> Accuracy: 0.4286, MCC: -0.1378, F1: 0.4211

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.44178 | val 0.43763
  Epoch 020 - train 0.40744 | val 0.43762
  Epoch 030 - train 0.39424 | val 0.44364
  Regression -> MSE: 0.000690, MAE: 0.019169, R²: -0.0077
  Directional -> Accuracy: 0.6304, MCC: 0.2307, F1: 0.7302

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45720 | val 0.97430
  Epoch 020 - train 0.44163 | val 1.02448
  Epoch 021 - train 0.43383 | val 1.02480
  Regression -> MSE: 0.000311, MAE: 0.014470, R²: -0.0035
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.37447 | val 0.94209
  Epoch 020 - train 0.36037 | val 0.98009
  Epoch 021 - train 0.35757 | val 0.99445
  Regression -> MSE: 0.000384, MAE: 0.015154, R²: -0.0982
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.42645 | val 0.43602
  Epoch 020 - train 0.39992 | val 0.42715
  Epoch 030 - train 0.37802 | val 0.42664
  Regression -> MSE: 0.000211, MAE: 0.010231, R²: -0.0346
  Directional -> Accuracy: 0.4902, MCC: -0.0387, F1: 0.5667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.41575 | val 1.09054
  Epoch 020 - train 0.38268 | val 1.11658
  Epoch 027 - train 0.39460 | val 1.12256
  Regression -> MSE: 0.000556, MAE: 0.018145, R²: -0.0021
  Directional -> Accuracy: 0.5106, MCC: 0.0045, F1: 0.0800

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44551 | val 0.63991
  Epoch 020 - train 0.42617 | val 0.64875
  Epoch 021 - train 0.42275 | val 0.65038
  Regression -> MSE: 0.000247, MAE: 0.012318, R²: -0.0082
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43953 | val 0.73920
  Epoch 020 - train 0.42029 | val 0.85606
  Epoch 021 - train 0.43371 | val 0.86378
  Regression -> MSE: 0.000650, MAE: 0.020263, R²: -0.0885
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.42551 | val 0.56727
  Epoch 020 - train 0.42058 | val 0.58432
  Epoch 021 - train 0.42082 | val 0.58132
  Regression -> MSE: 0.000402, MAE: 0.016077, R²: -0.0470
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42532 | val 0.71174
  Epoch 020 - train 0.39635 | val 0.72692
  Epoch 024 - train 0.40234 | val 0.72491
  Regression -> MSE: 0.000240, MAE: 0.011906, R²: 0.0070
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.39796 | val 0.74035
  Epoch 020 - train 0.38646 | val 0.79837
  Epoch 026 - train 0.37384 | val 0.80903
  Regression -> MSE: 0.000318, MAE: 0.013606, R²: -0.0240
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.44015 | val 0.60706
  Epoch 020 - train 0.44512 | val 0.61350
  Epoch 021 - train 0.43515 | val 0.61331
  Regression -> MSE: 0.000677, MAE: 0.019548, R²: -0.0002
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.41446 | val 0.51709
  Epoch 020 - train 0.41656 | val 0.57060
  Epoch 021 - train 0.40386 | val 0.56865
  Regression -> MSE: 0.000139, MAE: 0.009159, R²: -0.0034
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.38280 | val 0.70643
  Epoch 020 - train 0.37073 | val 0.70282
  Epoch 021 - train 0.37341 | val 0.70286
  Regression -> MSE: 0.000226, MAE: 0.010755, R²: -0.0038
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.42831 | val 1.30437
  Epoch 020 - train 0.42745 | val 1.32663
  Epoch 021 - train 0.42305 | val 1.32791
  Regression -> MSE: 0.000369, MAE: 0.015934, R²: -0.0192
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.45558 | val 0.49515
  Epoch 020 - train 0.42915 | val 0.47590
  Epoch 025 - train 0.41594 | val 0.47496
  Regression -> MSE: 0.000112, MAE: 0.008046, R²: -0.0339
  Directional -> Accuracy: 0.5143, MCC: -0.0761, F1: 0.6667

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42507 | val 1.05486
  Epoch 020 - train 0.41655 | val 1.06077
  Epoch 021 - train 0.41422 | val 1.06347
  Regression -> MSE: 0.000155, MAE: 0.009620, R²: 0.0042
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.43731 | val 0.65394
  Epoch 020 - train 0.43942 | val 0.65746
  Epoch 021 - train 0.43587 | val 0.65301
  Regression -> MSE: 0.000289, MAE: 0.013779, R²: -0.0616
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36307 | val 0.73323
  Epoch 020 - train 0.35456 | val 0.72999
  Epoch 021 - train 0.35273 | val 0.72886
  Regression -> MSE: 0.000167, MAE: 0.009097, R²: -0.1133
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.42749 | val 0.94237
  Epoch 020 - train 0.40377 | val 0.91136
  Epoch 023 - train 0.40619 | val 0.91051
  Regression -> MSE: 0.000274, MAE: 0.011944, R²: -0.2128
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42296 | val 0.70115
  Epoch 020 - train 0.40371 | val 0.70257
  Epoch 021 - train 0.41442 | val 0.70364
  Regression -> MSE: 0.000145, MAE: 0.008365, R²: -0.0083
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.40960 | val 0.54925
  Epoch 020 - train 0.38473 | val 0.55251
  Epoch 029 - train 0.37772 | val 0.55219
  Regression -> MSE: 0.000162, MAE: 0.010121, R²: 0.0192
  Directional -> Accuracy: 0.5909, MCC: 0.1978, F1: 0.6582

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45880 | val 0.63129
  Epoch 020 - train 0.46482 | val 0.63309
  Epoch 021 - train 0.45783 | val 0.63295
  Regression -> MSE: 0.000085, MAE: 0.007052, R²: -0.0029
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.43429 | val 0.63057
  Epoch 020 - train 0.40376 | val 0.63413
  Epoch 021 - train 0.41976 | val 0.63155
  Regression -> MSE: 0.000212, MAE: 0.011059, R²: -0.0013
  Directional -> Accuracy: 0.5606, MCC: 0.1052, F1: 0.3830

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.37555 | val 0.35218
  Epoch 020 - train 0.35443 | val 0.34673
  Epoch 030 - train 0.34817 | val 0.34315
  Regression -> MSE: 0.000095, MAE: 0.007839, R²: -0.0333
  Directional -> Accuracy: 0.6071, MCC: 0.1995, F1: 0.6562

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.45039 | val 0.34265
  Epoch 020 - train 0.43147 | val 0.34895
  Epoch 030 - train 0.43222 | val 0.35785
  Regression -> MSE: 0.000114, MAE: 0.009146, R²: -0.1010
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44968 | val 0.43523
  Epoch 020 - train 0.44683 | val 0.44843
  Epoch 021 - train 0.43544 | val 0.44979
  Regression -> MSE: 0.000233, MAE: 0.012596, R²: -0.0051
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.41188 | val 0.60990
  Epoch 020 - train 0.40449 | val 0.61928
  Epoch 021 - train 0.40557 | val 0.62091
  Regression -> MSE: 0.000180, MAE: 0.007996, R²: -0.0844
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.47473 | val 0.36624
  Epoch 020 - train 0.45727 | val 0.37150
  Epoch 021 - train 0.45819 | val 0.37308
  Regression -> MSE: 0.000244, MAE: 0.012153, R²: -0.0297
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.44642 | val 0.96598
  Epoch 020 - train 0.41924 | val 1.01460
  Epoch 030 - train 0.39584 | val 1.05010
  Regression -> MSE: 0.000243, MAE: 0.010282, R²: -0.0537
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.47519 | val 0.68289
  Epoch 020 - train 0.45802 | val 0.75959
  Epoch 021 - train 0.45205 | val 0.75892
  Regression -> MSE: 0.000141, MAE: 0.008467, R²: -0.0445
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43562 | val 0.67299
  Epoch 020 - train 0.41220 | val 0.67165
  Epoch 021 - train 0.42030 | val 0.67260
  Regression -> MSE: 0.000189, MAE: 0.010428, R²: -0.0032
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.37415 | val 0.61358
  Epoch 020 - train 0.36455 | val 0.59682
  Epoch 030 - train 0.35675 | val 0.59160
  Regression -> MSE: 0.000367, MAE: 0.013466, R²: -0.4006
  Directional -> Accuracy: 0.4521, MCC: -0.0422, F1: 0.3333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.52976 | val 0.38358
  Epoch 020 - train 0.49119 | val 0.57748
  Epoch 021 - train 0.51598 | val 0.61559
  Regression -> MSE: 0.000174, MAE: 0.010443, R²: -0.0417
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.40169 | val 0.52291
  Epoch 020 - train 0.38202 | val 0.54610
  Epoch 021 - train 0.37336 | val 0.54822
  Regression -> MSE: 0.000180, MAE: 0.010281, R²: -0.0023
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.41379 | val 0.41302
  Epoch 020 - train 0.38713 | val 0.41685
  Epoch 027 - train 0.39253 | val 0.41797
  Regression -> MSE: 0.000363, MAE: 0.012290, R²: -0.0592
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45680 | val 0.25496
  Epoch 020 - train 0.42169 | val 0.25862
  Epoch 030 - train 0.41340 | val 0.26104
  Regression -> MSE: 0.000128, MAE: 0.008619, R²: -0.2209
  Directional -> Accuracy: 0.4651, MCC: -0.0660, F1: 0.3429

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.42832 | val 0.82676
  Epoch 020 - train 0.41462 | val 0.84207
  Epoch 021 - train 0.40637 | val 0.84785
  Regression -> MSE: 0.000223, MAE: 0.011410, R²: -0.0210
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45496 | val 1.12551
  Epoch 020 - train 0.44157 | val 1.31927
  Epoch 021 - train 0.44132 | val 1.32501
  Regression -> MSE: 0.000086, MAE: 0.007245, R²: -0.1085
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.41865 | val 0.31501
  Epoch 020 - train 0.39373 | val 0.29882
  Epoch 030 - train 0.39010 | val 0.30703
  Regression -> MSE: 0.000350, MAE: 0.015703, R²: -0.1386
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.45621 | val 0.22566
  Epoch 020 - train 0.41289 | val 0.22966
  Epoch 021 - train 0.42999 | val 0.23189
  Regression -> MSE: 0.000261, MAE: 0.011502, R²: -0.0725
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.42440 | val 0.61281
  Epoch 020 - train 0.41368 | val 0.61324
  Epoch 021 - train 0.40861 | val 0.61263
  Regression -> MSE: 0.000081, MAE: 0.007101, R²: -0.0039
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.43204 | val 0.58057
  Epoch 020 - train 0.41758 | val 0.70143
  Epoch 028 - train 0.41288 | val 0.71560
  Regression -> MSE: 0.000310, MAE: 0.014513, R²: -0.0119
  Directional -> Accuracy: 0.4681, MCC: -0.1036, F1: 0.6032

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.46217 | val 0.52337
  Epoch 020 - train 0.42532 | val 0.47683
  Epoch 030 - train 0.40951 | val 0.46383
  Regression -> MSE: 0.000103, MAE: 0.007630, R²: -0.0487
  Directional -> Accuracy: 0.4091, MCC: -0.1394, F1: 0.3158

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.47594 | val 0.68756
  Epoch 020 - train 0.44123 | val 0.69651
  Epoch 021 - train 0.43493 | val 0.69665
  Regression -> MSE: 0.000172, MAE: 0.009585, R²: -0.0017
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 01:32:59,850] Trial 89 finished with value: -0.01157263282969876 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 3.626591327370185e-05, 'weight_decay': 8.431954598339548e-07, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.4508024042573195, 'early_stopping_min_delta': 0.008823073036491366}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.44811 | val 1.03720
  Epoch 021 - train 0.44515 | val 1.03443
  Regression -> MSE: 0.000238, MAE: 0.012506, R²: -0.0016
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.21825 | val 0.27286
  Epoch 020 - train 0.20984 | val 0.27218
  Epoch 021 - train 0.22174 | val 0.27270
  Regression -> MSE: 0.000251, MAE: 0.012766, R²: -0.0241
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.22076 | val 0.19355
  Epoch 020 - train 0.22371 | val 0.19871
  Epoch 021 - train 0.21277 | val 0.19737
  Regression -> MSE: 0.000701, MAE: 0.019781, R²: -0.0138
  Directional -> Accuracy: 0.5532, MCC: 0.0000, F1: 0.7123

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.23347 | val 0.34545
  Epoch 020 - train 0.22460 | val 0.33764
  Epoch 030 - train 0.21492 | val 0.33721
  Regression -> MSE: 0.000357, MAE: 0.014747, R²: -0.0347
  Directional -> Accuracy: 0.6667, MCC: 0.4345, F1: 0.5789

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.20168 | val 0.20230
  Epoch 020 - train 0.19303 | val 0.19263
  Epoch 021 - train 0.19490 | val 0.19256
  Regression -> MSE: 0.000356, MAE: 0.014583, R²: -0.0316
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.24296 | val 0.19962
  Epoch 020 - train 0.21989 | val 0.19171
  Epoch 030 - train 0.22336 | val 0.19158
  Regression -> MSE: 0.000195, MAE: 0.009840, R²: 0.0271
  Directional -> Accuracy: 0.5962, MCC: 0.2673, F1: 0.4878

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.21992 | val 0.39166
  Epoch 020 - train 0.21846 | val 0.39448
  Epoch 030 - train 0.22237 | val 0.41700
  Regression -> MSE: 0.000576, MAE: 0.018471, R²: -0.0059
  Directional -> Accuracy: 0.5102, MCC: 0.0379, F1: 0.3333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.22864 | val 0.27125
  Epoch 020 - train 0.22336 | val 0.27295
  Epoch 021 - train 0.22749 | val 0.27296
  Regression -> MSE: 0.000249, MAE: 0.011963, R²: -0.0126
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.21538 | val 0.25596
  Epoch 020 - train 0.23920 | val 0.30671
  Epoch 021 - train 0.22201 | val 0.30863
  Regression -> MSE: 0.000589, MAE: 0.018872, R²: -0.0067
  Directional -> Accuracy: 0.5778, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.19897 | val 0.31649
  Epoch 020 - train 0.21770 | val 0.32034
  Epoch 021 - train 0.21973 | val 0.31972
  Regression -> MSE: 0.000342, MAE: 0.014836, R²: -0.0104
  Directional -> Accuracy: 0.6190, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.21657 | val 0.28833
  Epoch 020 - train 0.22497 | val 0.29586
  Epoch 021 - train 0.22528 | val 0.29688
  Regression -> MSE: 0.000239, MAE: 0.011614, R²: -0.0032
  Directional -> Accuracy: 0.5070, MCC: 0.0632, F1: 0.5570

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.20392 | val 0.31253
  Epoch 020 - train 0.19661 | val 0.31231
  Epoch 021 - train 0.19854 | val 0.31209
  Regression -> MSE: 0.000307, MAE: 0.013536, R²: -0.0029
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.24338 | val 0.25329
  Epoch 020 - train 0.23739 | val 0.25210
  Epoch 021 - train 0.23268 | val 0.25363
  Regression -> MSE: 0.000682, MAE: 0.019822, R²: -0.0190
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.24810 | val 0.20526
  Epoch 020 - train 0.22636 | val 0.21369
  Epoch 021 - train 0.22683 | val 0.21492
  Regression -> MSE: 0.000150, MAE: 0.009597, R²: -0.0025
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.20964 | val 0.28442
  Epoch 020 - train 0.21690 | val 0.27933
  Epoch 030 - train 0.21744 | val 0.27761
  Regression -> MSE: 0.000228, MAE: 0.010934, R²: -0.0129
  Directional -> Accuracy: 0.5161, MCC: 0.0510, F1: 0.6512

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.22273 | val 0.49154
  Epoch 020 - train 0.21843 | val 0.54030
  Epoch 021 - train 0.21952 | val 0.53821
  Regression -> MSE: 0.000378, MAE: 0.016402, R²: -0.0050
  Directional -> Accuracy: 0.4717, MCC: 0.0000, F1: 0.6410

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.23628 | val 0.22161
  Epoch 020 - train 0.22670 | val 0.22139
  Epoch 021 - train 0.22659 | val 0.22084
  Regression -> MSE: 0.000106, MAE: 0.007926, R²: -0.0003
  Directional -> Accuracy: 0.4648, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.22376 | val 0.38515
  Epoch 020 - train 0.22719 | val 0.39837
  Epoch 021 - train 0.22872 | val 0.39702
  Regression -> MSE: 0.000163, MAE: 0.010234, R²: -0.0186
  Directional -> Accuracy: 0.5833, MCC: 0.0153, F1: 0.7126

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.21865 | val 0.24715
  Epoch 020 - train 0.21916 | val 0.25029
  Epoch 021 - train 0.21371 | val 0.25044
  Regression -> MSE: 0.000271, MAE: 0.012973, R²: -0.0077
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.20637 | val 0.28979
  Epoch 020 - train 0.22336 | val 0.29107
  Epoch 021 - train 0.21779 | val 0.29157
  Regression -> MSE: 0.000169, MAE: 0.009133, R²: -0.1447
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.23774 | val 0.35096
  Epoch 020 - train 0.23279 | val 0.34238
  Epoch 021 - train 0.24175 | val 0.34460
  Regression -> MSE: 0.000244, MAE: 0.011212, R²: -0.0759
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.22893 | val 0.27916
  Epoch 020 - train 0.22612 | val 0.29570
  Epoch 021 - train 0.22103 | val 0.29616
  Regression -> MSE: 0.000149, MAE: 0.008541, R²: -0.0016
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.21711 | val 0.24397
  Epoch 020 - train 0.21078 | val 0.24547
  Epoch 021 - train 0.21897 | val 0.24583
  Regression -> MSE: 0.000189, MAE: 0.010618, R²: -0.0686
  Directional -> Accuracy: 0.4925, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.22869 | val 0.25573
  Epoch 020 - train 0.22961 | val 0.26469
  Epoch 021 - train 0.23174 | val 0.26509
  Regression -> MSE: 0.000086, MAE: 0.007082, R²: -0.0262
  Directional -> Accuracy: 0.6102, MCC: 0.1830, F1: 0.6849

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.21503 | val 0.28468
  Epoch 020 - train 0.21669 | val 0.31631
  Epoch 021 - train 0.21165 | val 0.31819
  Regression -> MSE: 0.000219, MAE: 0.011312, R²: -0.0028
  Directional -> Accuracy: 0.5224, MCC: 0.0546, F1: 0.5556

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.19943 | val 0.17032
  Epoch 020 - train 0.19807 | val 0.16824
  Epoch 030 - train 0.19011 | val 0.16628
  Regression -> MSE: 0.000095, MAE: 0.007957, R²: -0.0410
  Directional -> Accuracy: 0.5439, MCC: 0.0996, F1: 0.5517

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.23470 | val 0.12649
  Epoch 020 - train 0.22902 | val 0.13635
  Epoch 021 - train 0.23190 | val 0.13787
  Regression -> MSE: 0.000135, MAE: 0.009592, R²: -0.0751
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.23292 | val 0.18767
  Epoch 020 - train 0.21978 | val 0.19850
  Epoch 021 - train 0.22830 | val 0.19919
  Regression -> MSE: 0.000245, MAE: 0.012987, R²: -0.0293
  Directional -> Accuracy: 0.5682, MCC: 0.0172, F1: 0.6984

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.22810 | val 0.23822
  Epoch 020 - train 0.21631 | val 0.23190
  Epoch 030 - train 0.20547 | val 0.23047
  Regression -> MSE: 0.000288, MAE: 0.012063, R²: -0.7573
  Directional -> Accuracy: 0.4483, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.24046 | val 0.15791
  Epoch 020 - train 0.22134 | val 0.16423
  Epoch 021 - train 0.23215 | val 0.16453
  Regression -> MSE: 0.000235, MAE: 0.011918, R²: -0.0023
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.22911 | val 0.30802
  Epoch 020 - train 0.21757 | val 0.33011
  Epoch 021 - train 0.21878 | val 0.32934
  Regression -> MSE: 0.000250, MAE: 0.010429, R²: 0.0013
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.23938 | val 0.30826
  Epoch 020 - train 0.23315 | val 0.29517
  Epoch 030 - train 0.21773 | val 0.29539
  Regression -> MSE: 0.000133, MAE: 0.008248, R²: -0.0018
  Directional -> Accuracy: 0.4889, MCC: -0.0854, F1: 0.6230

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.23454 | val 0.26981
  Epoch 020 - train 0.22905 | val 0.26631
  Epoch 021 - train 0.21888 | val 0.26621
  Regression -> MSE: 0.000189, MAE: 0.010443, R²: -0.0046
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.21242 | val 0.25620
  Epoch 020 - train 0.20411 | val 0.25141
  Epoch 021 - train 0.19857 | val 0.25232
  Regression -> MSE: 0.000263, MAE: 0.010454, R²: -0.0170
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.21679 | val 0.18278
  Epoch 020 - train 0.20686 | val 0.18517
  Epoch 021 - train 0.20219 | val 0.18613
  Regression -> MSE: 0.000163, MAE: 0.010150, R²: -0.0021
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.20238 | val 0.22623
  Epoch 020 - train 0.19144 | val 0.28071
  Epoch 021 - train 0.21080 | val 0.28040
  Regression -> MSE: 0.000190, MAE: 0.010696, R²: -0.0371
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.21074 | val 0.19502
  Epoch 020 - train 0.21377 | val 0.19724
  Epoch 021 - train 0.20824 | val 0.19695
  Regression -> MSE: 0.000354, MAE: 0.012454, R²: -0.0156
  Directional -> Accuracy: 0.4265, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.25883 | val 0.14257
  Epoch 020 - train 0.24811 | val 0.15955
  Epoch 021 - train 0.22348 | val 0.15949
  Regression -> MSE: 0.000117, MAE: 0.008242, R²: -0.1273
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.23827 | val 0.29495
  Epoch 020 - train 0.21846 | val 0.29590
  Epoch 021 - train 0.23833 | val 0.29660
  Regression -> MSE: 0.000216, MAE: 0.011228, R²: -0.0048
  Directional -> Accuracy: 0.4655, MCC: -0.0316, F1: 0.5867

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.22487 | val 0.35374
  Epoch 020 - train 0.22241 | val 0.37565
  Epoch 021 - train 0.21812 | val 0.37688
  Regression -> MSE: 0.000100, MAE: 0.007833, R²: -0.2583
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.22093 | val 0.18664
  Epoch 020 - train 0.21169 | val 0.19608
  Epoch 021 - train 0.21852 | val 0.19398
  Regression -> MSE: 0.000360, MAE: 0.016248, R²: -0.0956
  Directional -> Accuracy: 0.3500, MCC: 0.0000, F1: 0.5185

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.24611 | val 0.13349
  Epoch 020 - train 0.23090 | val 0.13805
  Epoch 021 - train 0.23884 | val 0.13820
  Regression -> MSE: 0.000240, MAE: 0.011315, R²: -0.0102
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.23065 | val 0.26801
  Epoch 020 - train 0.21836 | val 0.26864
  Epoch 021 - train 0.21542 | val 0.26935
  Regression -> MSE: 0.000081, MAE: 0.007064, R²: -0.0051
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.23423 | val 0.23896
  Epoch 020 - train 0.23154 | val 0.23649
  Epoch 030 - train 0.20943 | val 0.24067
  Regression -> MSE: 0.000369, MAE: 0.015358, R²: -0.0264
  Directional -> Accuracy: 0.5208, MCC: 0.0682, F1: 0.2069

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.22222 | val 0.25301
  Epoch 020 - train 0.21976 | val 0.26681
  Epoch 021 - train 0.21124 | val 0.26866
  Regression -> MSE: 0.000097, MAE: 0.007189, R²: -0.0063
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.24100 | val 0.27383
  Epoch 020 - train 0.24171 | val 0.30552
  Epoch 021 - train 0.23913 | val 0.30795
  Regression -> MSE: 0.000183, MAE: 0.009749, R²: -0.0118
  Directional -> Accuracy: 0.6341, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.21094 | val 0.24220
  Epoch 020 - train 0.19729 | val 0.24759
  Epoch 021 - train 0.21243 | val 0.25037
  Regression -> MSE: 0.000226, MAE: 0.011805, R²: -0.0303
  Directional -> Accuracy: 0.4561, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.23260 | val 0.22952

[I 2026-02-24 01:35:08,883] Trial 90 finished with value: -0.01158308509263445 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'LSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 1.9718608326897597e-05, 'weight_decay': 4.273921523628019e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.35743441073057863, 'early_stopping_min_delta': 0.007878477043306364}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.23711 | val 0.31999
  Epoch 021 - train 0.26077 | val 0.31933
  Regression -> MSE: 0.000234, MAE: 0.012244, R²: -0.0035
  Directional -> Accuracy: 0.4839, MCC: 0.0000, F1: 0.6522

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13937 | val 0.15651
  Epoch 020 - train 0.14477 | val 0.15635
  Epoch 021 - train 0.13350 | val 0.15632
  Regression -> MSE: 0.000257, MAE: 0.012915, R²: -0.0373
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14167 | val 0.11270
  Epoch 020 - train 0.13634 | val 0.12831
  Epoch 021 - train 0.14750 | val 0.12863
  Regression -> MSE: 0.000699, MAE: 0.019596, R²: -0.0209
  Directional -> Accuracy: 0.6087, MCC: 0.2942, F1: 0.5500

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13685 | val 0.18880
  Epoch 020 - train 0.14533 | val 0.18299
  Epoch 030 - train 0.14186 | val 0.18307
  Regression -> MSE: 0.000316, MAE: 0.014257, R²: -0.0174
  Directional -> Accuracy: 0.5532, MCC: 0.1174, F1: 0.5333

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12098 | val 0.10423
  Epoch 020 - train 0.11858 | val 0.10379
  Epoch 021 - train 0.11636 | val 0.10298
  Regression -> MSE: 0.000354, MAE: 0.014669, R²: -0.0148
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14566 | val 0.13071
  Epoch 020 - train 0.14378 | val 0.14340
  Epoch 021 - train 0.14034 | val 0.14417
  Regression -> MSE: 0.000209, MAE: 0.010165, R²: -0.0255
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.14113 | val 0.22034
  Epoch 020 - train 0.12533 | val 0.22488
  Epoch 021 - train 0.13628 | val 0.22485
  Regression -> MSE: 0.000557, MAE: 0.018196, R²: -0.0033
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14322 | val 0.17211
  Epoch 020 - train 0.15138 | val 0.17485
  Epoch 021 - train 0.14483 | val 0.17399
  Regression -> MSE: 0.000255, MAE: 0.012016, R²: -0.0384
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14930 | val 0.17305
  Epoch 020 - train 0.14090 | val 0.21767
  Epoch 021 - train 0.13286 | val 0.22273
  Regression -> MSE: 0.000653, MAE: 0.020307, R²: -0.0924
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13529 | val 0.14839
  Epoch 020 - train 0.12874 | val 0.14767
  Epoch 021 - train 0.13087 | val 0.14759
  Regression -> MSE: 0.000386, MAE: 0.016126, R²: -0.0064
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14165 | val 0.30364
  Epoch 020 - train 0.14244 | val 0.32507
  Epoch 021 - train 0.14072 | val 0.32413
  Regression -> MSE: 0.000247, MAE: 0.011616, R²: -0.0239
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12223 | val 0.17025
  Epoch 020 - train 0.12658 | val 0.17068
  Epoch 021 - train 0.11698 | val 0.17089
  Regression -> MSE: 0.000312, MAE: 0.013688, R²: -0.0021
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13818 | val 0.16195
  Epoch 020 - train 0.14406 | val 0.17664
  Epoch 021 - train 0.14367 | val 0.17704
  Regression -> MSE: 0.000680, MAE: 0.019496, R²: -0.0046
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13073 | val 0.11667
  Epoch 020 - train 0.13326 | val 0.11391
  Epoch 021 - train 0.13767 | val 0.11354
  Regression -> MSE: 0.000139, MAE: 0.009212, R²: -0.0058
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12087 | val 0.14924
  Epoch 020 - train 0.11697 | val 0.15440
  Epoch 021 - train 0.11276 | val 0.15420
  Regression -> MSE: 0.000225, MAE: 0.010692, R²: -0.0014
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14731 | val 0.24621
  Epoch 020 - train 0.14335 | val 0.25369
  Epoch 021 - train 0.14558 | val 0.25265
  Regression -> MSE: 0.000363, MAE: 0.016191, R²: -0.0013
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14539 | val 0.13131
  Epoch 020 - train 0.14639 | val 0.13359
  Epoch 021 - train 0.14877 | val 0.13272
  Regression -> MSE: 0.000112, MAE: 0.007976, R²: -0.0383
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12791 | val 0.19482
  Epoch 020 - train 0.12906 | val 0.19487
  Epoch 021 - train 0.12430 | val 0.19496
  Regression -> MSE: 0.000157, MAE: 0.009519, R²: -0.0082
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13509 | val 0.14083
  Epoch 020 - train 0.13804 | val 0.14149
  Epoch 021 - train 0.13883 | val 0.14274
  Regression -> MSE: 0.000282, MAE: 0.013550, R²: -0.0377
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12957 | val 0.17150
  Epoch 020 - train 0.12989 | val 0.17422
  Epoch 021 - train 0.13266 | val 0.17359
  Regression -> MSE: 0.000167, MAE: 0.009109, R²: -0.1148
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14560 | val 0.16799
  Epoch 020 - train 0.14941 | val 0.16855
  Epoch 021 - train 0.13365 | val 0.16813
  Regression -> MSE: 0.000246, MAE: 0.011223, R²: -0.0855
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12461 | val 0.14587
  Epoch 020 - train 0.13811 | val 0.14859
  Epoch 021 - train 0.13193 | val 0.14856
  Regression -> MSE: 0.000144, MAE: 0.008358, R²: -0.0043
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13553 | val 0.13879
  Epoch 020 - train 0.12837 | val 0.13921
  Epoch 021 - train 0.14198 | val 0.13931
  Regression -> MSE: 0.000174, MAE: 0.010300, R²: -0.0556
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14623 | val 0.13970
  Epoch 020 - train 0.14364 | val 0.13922
  Epoch 021 - train 0.14672 | val 0.13964
  Regression -> MSE: 0.000086, MAE: 0.007059, R²: -0.0054
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13181 | val 0.14106
  Epoch 020 - train 0.13353 | val 0.14123
  Epoch 021 - train 0.13038 | val 0.14124
  Regression -> MSE: 0.000213, MAE: 0.011339, R²: -0.0070
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12836 | val 0.10602
  Epoch 020 - train 0.12607 | val 0.10571
  Epoch 021 - train 0.12078 | val 0.10499
  Regression -> MSE: 0.000102, MAE: 0.008251, R²: -0.1038
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14085 | val 0.09285
  Epoch 020 - train 0.13319 | val 0.09503
  Epoch 021 - train 0.13036 | val 0.09557
  Regression -> MSE: 0.000104, MAE: 0.008787, R²: -0.0088
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14718 | val 0.12141
  Epoch 020 - train 0.15325 | val 0.13566
  Epoch 021 - train 0.15258 | val 0.13535
  Regression -> MSE: 0.000245, MAE: 0.012977, R²: -0.0597
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13688 | val 0.15257
  Epoch 020 - train 0.13490 | val 0.15462
  Epoch 021 - train 0.13992 | val 0.15497
  Regression -> MSE: 0.000169, MAE: 0.007836, R²: -0.0176
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14393 | val 0.10028
  Epoch 020 - train 0.14176 | val 0.09879
  Epoch 021 - train 0.13115 | val 0.09948
  Regression -> MSE: 0.000239, MAE: 0.011940, R²: -0.0110
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12991 | val 0.18511
  Epoch 020 - train 0.13318 | val 0.18606
  Epoch 021 - train 0.13727 | val 0.18620
  Regression -> MSE: 0.000231, MAE: 0.009874, R²: -0.0014
  Directional -> Accuracy: 0.4651, MCC: -0.0693, F1: 0.4651

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13767 | val 0.13610
  Epoch 020 - train 0.15127 | val 0.14654
  Epoch 021 - train 0.14630 | val 0.14698
  Regression -> MSE: 0.000135, MAE: 0.008178, R²: -0.0002
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13190 | val 0.15441
  Epoch 020 - train 0.13131 | val 0.15684
  Epoch 021 - train 0.14461 | val 0.15662
  Regression -> MSE: 0.000189, MAE: 0.010479, R²: -0.0024
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12681 | val 0.14837
  Epoch 020 - train 0.12616 | val 0.14802
  Epoch 021 - train 0.12804 | val 0.14849
  Regression -> MSE: 0.000261, MAE: 0.010516, R²: 0.0028
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12879 | val 0.09947
  Epoch 020 - train 0.12940 | val 0.09724
  Epoch 021 - train 0.12414 | val 0.09727
  Regression -> MSE: 0.000172, MAE: 0.010411, R²: -0.0328
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14030 | val 0.11892
  Epoch 020 - train 0.13045 | val 0.12329
  Epoch 021 - train 0.12704 | val 0.12299
  Regression -> MSE: 0.000180, MAE: 0.010269, R²: -0.0026
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13644 | val 0.11522
  Epoch 020 - train 0.13221 | val 0.11525
  Epoch 021 - train 0.14164 | val 0.11522
  Regression -> MSE: 0.000346, MAE: 0.011746, R²: -0.0095
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14215 | val 0.07876
  Epoch 020 - train 0.13590 | val 0.07930
  Epoch 021 - train 0.14137 | val 0.07921
  Regression -> MSE: 0.000125, MAE: 0.008452, R²: -0.1911
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13135 | val 0.15467
  Epoch 020 - train 0.13549 | val 0.15546
  Epoch 021 - train 0.13213 | val 0.15503
  Regression -> MSE: 0.000219, MAE: 0.011304, R²: -0.0016
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12464 | val 0.19929
  Epoch 020 - train 0.13318 | val 0.19973
  Epoch 021 - train 0.13456 | val 0.19956
  Regression -> MSE: 0.000088, MAE: 0.007344, R²: -0.1337
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13292 | val 0.10253
  Epoch 020 - train 0.13616 | val 0.11604
  Epoch 021 - train 0.13725 | val 0.11737
  Regression -> MSE: 0.000331, MAE: 0.015023, R²: -0.0753
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13131 | val 0.08167
  Epoch 020 - train 0.14073 | val 0.08108
  Epoch 021 - train 0.12948 | val 0.08119
  Regression -> MSE: 0.000264, MAE: 0.011534, R²: -0.0836
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13030 | val 0.13593
  Epoch 020 - train 0.13127 | val 0.13553
  Epoch 021 - train 0.12478 | val 0.13542
  Regression -> MSE: 0.000082, MAE: 0.007038, R²: -0.0156
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14250 | val 0.17104
  Epoch 020 - train 0.14371 | val 0.20924
  Epoch 021 - train 0.14621 | val 0.20877
  Regression -> MSE: 0.000318, MAE: 0.014551, R²: -0.0357
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13411 | val 0.14474
  Epoch 020 - train 0.13442 | val 0.15255
  Epoch 021 - train 0.12104 | val 0.15279
  Regression -> MSE: 0.000102, MAE: 0.007104, R²: -0.0411
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14025 | val 0.14032
  Epoch 020 - train 0.13310 | val 0.14594
  Epoch 021 - train 0.13571 | val 0.14628
  Regression -> MSE: 0.000172, MAE: 0.009786, R²: -0.0020
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11901 | val 0.14153
  Epoch 020 - train 0.11993 | val 0.14353
  Epoch 021 - train 0.13033 | val 0.14413
  Regression -> MSE: 0.000224, MAE: 0.011764, R²: -0.0032
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13247 | val 0.13061
  Epoch 020 - train 0.12156 | val 0.13036
  Epoch 021 - train 0.12645 | val 0.13032

[I 2026-02-24 01:37:03,801] Trial 91 finished with value: -0.011441883529767655 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 4.823966245189095e-06, 'weight_decay': 1.3343919815496042e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.17722303044613827, 'early_stopping_min_delta': 0.008102487350419608}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.14299 | val 0.17341
  Epoch 021 - train 0.14044 | val 0.17405
  Regression -> MSE: 0.000243, MAE: 0.012358, R²: -0.0232
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11842 | val 0.13798
  Epoch 020 - train 0.11392 | val 0.13768
  Epoch 021 - train 0.11132 | val 0.13822
  Regression -> MSE: 0.000261, MAE: 0.013025, R²: -0.0533
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11974 | val 0.10037
  Epoch 020 - train 0.11313 | val 0.11096
  Epoch 021 - train 0.11350 | val 0.11122
  Regression -> MSE: 0.000720, MAE: 0.019944, R²: -0.0513
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11439 | val 0.16310
  Epoch 020 - train 0.10626 | val 0.17257
  Epoch 021 - train 0.11712 | val 0.17235
  Regression -> MSE: 0.000317, MAE: 0.014470, R²: -0.0219
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09569 | val 0.08759
  Epoch 020 - train 0.10241 | val 0.08847
  Epoch 021 - train 0.09894 | val 0.08894
  Regression -> MSE: 0.000377, MAE: 0.015022, R²: -0.0780
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11111 | val 0.10291
  Epoch 020 - train 0.11138 | val 0.10908
  Epoch 021 - train 0.11813 | val 0.10916
  Regression -> MSE: 0.000203, MAE: 0.010083, R²: 0.0026
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11486 | val 0.18543
  Epoch 020 - train 0.11110 | val 0.18493
  Epoch 030 - train 0.11645 | val 0.18530
  Regression -> MSE: 0.000533, MAE: 0.017866, R²: 0.0398
  Directional -> Accuracy: 0.5532, MCC: 0.1069, F1: 0.4324

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11909 | val 0.12671
  Epoch 020 - train 0.11168 | val 0.12686
  Epoch 021 - train 0.11222 | val 0.12688
  Regression -> MSE: 0.000246, MAE: 0.011948, R²: -0.0041
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11357 | val 0.11584
  Epoch 020 - train 0.11487 | val 0.10762
  Epoch 030 - train 0.10906 | val 0.10539
  Regression -> MSE: 0.000602, MAE: 0.019066, R²: -0.0079
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11873 | val 0.11787
  Epoch 020 - train 0.11576 | val 0.12011
  Epoch 021 - train 0.12929 | val 0.12027
  Regression -> MSE: 0.000412, MAE: 0.016270, R²: -0.0733
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11623 | val 0.13601
  Epoch 020 - train 0.11588 | val 0.13753
  Epoch 021 - train 0.12236 | val 0.13770
  Regression -> MSE: 0.000241, MAE: 0.011893, R²: -0.0001
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10593 | val 0.14303
  Epoch 020 - train 0.11332 | val 0.14911
  Epoch 021 - train 0.11056 | val 0.14994
  Regression -> MSE: 0.000325, MAE: 0.013617, R²: -0.0439
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11439 | val 0.13134
  Epoch 020 - train 0.11692 | val 0.14175
  Epoch 021 - train 0.11248 | val 0.14209
  Regression -> MSE: 0.000675, MAE: 0.019432, R²: 0.0028
  Directional -> Accuracy: 0.6207, MCC: 0.2511, F1: 0.5600

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10982 | val 0.10197
  Epoch 020 - train 0.11651 | val 0.10870
  Epoch 021 - train 0.12115 | val 0.10898
  Regression -> MSE: 0.000139, MAE: 0.009245, R²: -0.0081
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10691 | val 0.12705
  Epoch 020 - train 0.10321 | val 0.12923
  Epoch 021 - train 0.10793 | val 0.12879
  Regression -> MSE: 0.000225, MAE: 0.010715, R²: 0.0000
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11868 | val 0.19824
  Epoch 020 - train 0.11285 | val 0.19802
  Epoch 021 - train 0.11015 | val 0.19826
  Regression -> MSE: 0.000363, MAE: 0.016176, R²: -0.0022
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11970 | val 0.10747
  Epoch 020 - train 0.11569 | val 0.10765
  Epoch 021 - train 0.12426 | val 0.10777
  Regression -> MSE: 0.000108, MAE: 0.008044, R²: -0.0026
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11655 | val 0.16805
  Epoch 020 - train 0.10515 | val 0.17390
  Epoch 021 - train 0.10822 | val 0.17320
  Regression -> MSE: 0.000157, MAE: 0.009522, R²: -0.0054
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11736 | val 0.12765
  Epoch 020 - train 0.11806 | val 0.12760
  Epoch 021 - train 0.12031 | val 0.12574
  Regression -> MSE: 0.000274, MAE: 0.012935, R²: -0.0061
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11111 | val 0.15242
  Epoch 020 - train 0.11156 | val 0.15438
  Epoch 021 - train 0.10837 | val 0.15448
  Regression -> MSE: 0.000151, MAE: 0.008788, R²: -0.0108
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11939 | val 0.14610
  Epoch 020 - train 0.12313 | val 0.14616
  Epoch 021 - train 0.11404 | val 0.14627
  Regression -> MSE: 0.000235, MAE: 0.010945, R²: -0.0366
  Directional -> Accuracy: 0.5067, MCC: 0.1052, F1: 0.3019

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11112 | val 0.12400
  Epoch 020 - train 0.11064 | val 0.12331
  Epoch 021 - train 0.10896 | val 0.12339
  Regression -> MSE: 0.000148, MAE: 0.008578, R²: -0.0296
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11899 | val 0.11645
  Epoch 020 - train 0.11853 | val 0.11660
  Epoch 021 - train 0.12351 | val 0.11652
  Regression -> MSE: 0.000184, MAE: 0.010364, R²: -0.1107
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12858 | val 0.11945
  Epoch 020 - train 0.12353 | val 0.11866
  Epoch 021 - train 0.11193 | val 0.11869
  Regression -> MSE: 0.000094, MAE: 0.007503, R²: -0.1046
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10811 | val 0.12175
  Epoch 020 - train 0.10909 | val 0.12120
  Epoch 021 - train 0.10573 | val 0.12101
  Regression -> MSE: 0.000212, MAE: 0.011127, R²: -0.0014
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11164 | val 0.09731
  Epoch 020 - train 0.10613 | val 0.10029
  Epoch 021 - train 0.11730 | val 0.10000
  Regression -> MSE: 0.000100, MAE: 0.008201, R²: -0.0812
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12560 | val 0.08808
  Epoch 020 - train 0.11988 | val 0.09608
  Epoch 021 - train 0.12184 | val 0.09738
  Regression -> MSE: 0.000116, MAE: 0.009202, R²: -0.1236
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11461 | val 0.09744
  Epoch 020 - train 0.10876 | val 0.10145
  Epoch 021 - train 0.11956 | val 0.10197
  Regression -> MSE: 0.000237, MAE: 0.012733, R²: -0.0219
  Directional -> Accuracy: 0.5349, MCC: 0.0593, F1: 0.5833

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10841 | val 0.12141
  Epoch 020 - train 0.11440 | val 0.12281
  Epoch 021 - train 0.11468 | val 0.12287
  Regression -> MSE: 0.000187, MAE: 0.008110, R²: -0.1243
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12088 | val 0.09092
  Epoch 020 - train 0.11866 | val 0.10239
  Epoch 021 - train 0.10888 | val 0.10331
  Regression -> MSE: 0.000237, MAE: 0.011894, R²: -0.0039
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12459 | val 0.15882
  Epoch 020 - train 0.12276 | val 0.16214
  Epoch 021 - train 0.11182 | val 0.16219
  Regression -> MSE: 0.000231, MAE: 0.009905, R²: -0.0004
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12166 | val 0.11985
  Epoch 020 - train 0.11581 | val 0.12567
  Epoch 021 - train 0.11984 | val 0.12598
  Regression -> MSE: 0.000135, MAE: 0.008224, R²: 0.0004
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11858 | val 0.12398
  Epoch 020 - train 0.11464 | val 0.12507
  Epoch 021 - train 0.11283 | val 0.12491
  Regression -> MSE: 0.000192, MAE: 0.010416, R²: -0.0221
  Directional -> Accuracy: 0.4800, MCC: -0.0401, F1: 0.5000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10898 | val 0.12624
  Epoch 020 - train 0.10058 | val 0.12785
  Epoch 021 - train 0.10487 | val 0.12781
  Regression -> MSE: 0.000262, MAE: 0.010485, R²: -0.0001
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11317 | val 0.08520
  Epoch 020 - train 0.10685 | val 0.08626
  Epoch 021 - train 0.10578 | val 0.08661
  Regression -> MSE: 0.000170, MAE: 0.010379, R²: -0.0207
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11112 | val 0.10462
  Epoch 020 - train 0.10265 | val 0.11404
  Epoch 021 - train 0.11311 | val 0.11320
  Regression -> MSE: 0.000181, MAE: 0.010352, R²: -0.0042
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10915 | val 0.10366
  Epoch 020 - train 0.10222 | val 0.10329
  Epoch 021 - train 0.11600 | val 0.10390
  Regression -> MSE: 0.000346, MAE: 0.011709, R²: -0.0102
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12158 | val 0.06757
  Epoch 020 - train 0.11802 | val 0.07016
  Epoch 021 - train 0.11543 | val 0.07022
  Regression -> MSE: 0.000125, MAE: 0.008448, R²: -0.1876
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11321 | val 0.14482
  Epoch 020 - train 0.11347 | val 0.15331
  Epoch 021 - train 0.11257 | val 0.15387
  Regression -> MSE: 0.000219, MAE: 0.011309, R²: -0.0019
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11357 | val 0.16522
  Epoch 020 - train 0.10955 | val 0.16761
  Epoch 021 - train 0.11791 | val 0.16726
  Regression -> MSE: 0.000096, MAE: 0.007623, R²: -0.2311
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12985 | val 0.08413
  Epoch 020 - train 0.12323 | val 0.08252
  Epoch 021 - train 0.10802 | val 0.08253
  Regression -> MSE: 0.000328, MAE: 0.014889, R²: -0.0662
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11017 | val 0.06302
  Epoch 020 - train 0.11993 | val 0.06282
  Epoch 021 - train 0.11924 | val 0.06302
  Regression -> MSE: 0.000251, MAE: 0.011498, R²: -0.0281
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11793 | val 0.13656
  Epoch 020 - train 0.12143 | val 0.13833
  Epoch 021 - train 0.11163 | val 0.13822
  Regression -> MSE: 0.000084, MAE: 0.007049, R²: -0.0449
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11172 | val 0.13166
  Epoch 020 - train 0.12258 | val 0.14371
  Epoch 021 - train 0.10765 | val 0.14399
  Regression -> MSE: 0.000308, MAE: 0.014478, R²: -0.0041
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11166 | val 0.11535
  Epoch 020 - train 0.11144 | val 0.11629
  Epoch 021 - train 0.11021 | val 0.11693
  Regression -> MSE: 0.000100, MAE: 0.007126, R²: -0.0181
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11957 | val 0.11914
  Epoch 020 - train 0.12241 | val 0.12088
  Epoch 021 - train 0.11725 | val 0.12124
  Regression -> MSE: 0.000175, MAE: 0.010123, R²: -0.0167
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10554 | val 0.11800
  Epoch 020 - train 0.10994 | val 0.12103
  Epoch 021 - train 0.10861 | val 0.12243
  Regression -> MSE: 0.000225, MAE: 0.011806, R²: -0.0079
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11361 | val 0.11030
  Epoch 020 - train 0.11705 | val 0.11122
  Epoch 021 - train 0.11119 | val 0.11122

[I 2026-02-24 01:38:59,009] Trial 92 finished with value: -0.011435728252514035 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 4.622293474700022e-06, 'weight_decay': 1.3032997478578747e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.14773479045743398, 'early_stopping_min_delta': 0.0074076220721743585}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.10910 | val 0.20530
  Epoch 021 - train 0.11073 | val 0.20357
  Regression -> MSE: 0.000239, MAE: 0.012307, R²: -0.0070
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.18872 | val 0.23061
  Epoch 020 - train 0.19722 | val 0.23071
  Epoch 021 - train 0.18102 | val 0.23021
  Regression -> MSE: 0.000248, MAE: 0.012507, R²: 0.0003
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.20938 | val 0.18146
  Epoch 020 - train 0.20110 | val 0.24152
  Epoch 021 - train 0.20266 | val 0.24215
  Regression -> MSE: 0.000721, MAE: 0.019960, R²: -0.0535
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.19756 | val 0.29658
  Epoch 020 - train 0.21544 | val 0.31061
  Epoch 021 - train 0.21369 | val 0.31051
  Regression -> MSE: 0.000314, MAE: 0.014453, R²: -0.0132
  Directional -> Accuracy: 0.5319, MCC: 0.0135, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.16929 | val 0.17333
  Epoch 020 - train 0.17061 | val 0.17871
  Epoch 021 - train 0.18026 | val 0.17616
  Regression -> MSE: 0.000370, MAE: 0.014903, R²: -0.0589
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.21445 | val 0.17961
  Epoch 020 - train 0.19879 | val 0.18297
  Epoch 021 - train 0.20983 | val 0.18284
  Regression -> MSE: 0.000204, MAE: 0.010151, R²: -0.0042
  Directional -> Accuracy: 0.3922, MCC: -0.2810, F1: 0.5231

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.19120 | val 0.33289
  Epoch 020 - train 0.19245 | val 0.33761
  Epoch 021 - train 0.19403 | val 0.33787
  Regression -> MSE: 0.000578, MAE: 0.018532, R²: -0.0404
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.19005 | val 0.21568
  Epoch 020 - train 0.20893 | val 0.21400
  Epoch 030 - train 0.19526 | val 0.21188
  Regression -> MSE: 0.000246, MAE: 0.012546, R²: -0.0028
  Directional -> Accuracy: 0.4348, MCC: 0.0227, F1: 0.5618

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.17777 | val 0.24666
  Epoch 020 - train 0.18317 | val 0.24770
  Epoch 021 - train 0.17610 | val 0.24832
  Regression -> MSE: 0.000646, MAE: 0.020193, R²: -0.0820
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.20254 | val 0.22837
  Epoch 020 - train 0.21065 | val 0.23727
  Epoch 021 - train 0.18198 | val 0.23817
  Regression -> MSE: 0.000384, MAE: 0.016173, R²: -0.0023
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.20483 | val 0.23717
  Epoch 020 - train 0.21314 | val 0.23925
  Epoch 021 - train 0.20233 | val 0.23889
  Regression -> MSE: 0.000242, MAE: 0.011840, R²: -0.0026
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.18122 | val 0.27989
  Epoch 020 - train 0.18515 | val 0.29855
  Epoch 021 - train 0.17374 | val 0.29812
  Regression -> MSE: 0.000310, MAE: 0.013804, R²: 0.0019
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.19177 | val 0.21309
  Epoch 020 - train 0.20700 | val 0.21884
  Epoch 021 - train 0.21959 | val 0.21922
  Regression -> MSE: 0.000678, MAE: 0.019501, R²: -0.0008
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.22123 | val 0.18751
  Epoch 020 - train 0.21456 | val 0.20095
  Epoch 021 - train 0.21388 | val 0.20044
  Regression -> MSE: 0.000140, MAE: 0.008990, R²: -0.0108
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.19440 | val 0.26742
  Epoch 020 - train 0.21938 | val 0.27677
  Epoch 021 - train 0.19874 | val 0.27895
  Regression -> MSE: 0.000228, MAE: 0.010963, R²: -0.0134
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.20908 | val 0.37459
  Epoch 020 - train 0.19107 | val 0.37570
  Epoch 021 - train 0.20545 | val 0.37641
  Regression -> MSE: 0.000364, MAE: 0.016238, R²: -0.0037
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.21876 | val 0.22141
  Epoch 020 - train 0.21732 | val 0.23428
  Epoch 021 - train 0.20820 | val 0.23235
  Regression -> MSE: 0.000110, MAE: 0.007952, R²: -0.0234
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.19834 | val 0.29324
  Epoch 020 - train 0.19922 | val 0.30180
  Epoch 021 - train 0.19965 | val 0.30062
  Regression -> MSE: 0.000157, MAE: 0.009839, R²: -0.0086
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.19171 | val 0.18259
  Epoch 020 - train 0.19421 | val 0.18305
  Epoch 021 - train 0.19226 | val 0.18291
  Regression -> MSE: 0.000282, MAE: 0.013495, R²: -0.0347
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.17007 | val 0.23023
  Epoch 020 - train 0.17347 | val 0.23079
  Epoch 021 - train 0.17853 | val 0.23117
  Regression -> MSE: 0.000154, MAE: 0.008766, R²: -0.0274
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.21050 | val 0.27194
  Epoch 020 - train 0.20928 | val 0.27296
  Epoch 021 - train 0.21269 | val 0.27330
  Regression -> MSE: 0.000242, MAE: 0.011116, R²: -0.0703
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.21656 | val 0.22296
  Epoch 020 - train 0.20618 | val 0.23744
  Epoch 021 - train 0.19355 | val 0.23783
  Regression -> MSE: 0.000144, MAE: 0.008329, R²: -0.0020
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.19039 | val 0.21445
  Epoch 020 - train 0.17936 | val 0.21503
  Epoch 021 - train 0.18382 | val 0.21490
  Regression -> MSE: 0.000166, MAE: 0.010290, R²: -0.0073
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.20751 | val 0.21137
  Epoch 020 - train 0.21262 | val 0.21329
  Epoch 021 - train 0.19989 | val 0.21342
  Regression -> MSE: 0.000089, MAE: 0.007266, R²: -0.0475
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.21182 | val 0.21203
  Epoch 020 - train 0.19891 | val 0.21283
  Epoch 021 - train 0.19756 | val 0.21278
  Regression -> MSE: 0.000215, MAE: 0.011057, R²: -0.0153
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.18474 | val 0.16687
  Epoch 020 - train 0.19842 | val 0.17043
  Epoch 021 - train 0.20172 | val 0.17125
  Regression -> MSE: 0.000093, MAE: 0.008103, R²: -0.0103
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.19966 | val 0.13442
  Epoch 020 - train 0.19545 | val 0.13893
  Epoch 021 - train 0.19635 | val 0.13961
  Regression -> MSE: 0.000104, MAE: 0.008798, R²: -0.0111
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.20938 | val 0.16913
  Epoch 020 - train 0.21363 | val 0.17000
  Epoch 021 - train 0.20064 | val 0.17169
  Regression -> MSE: 0.000232, MAE: 0.012546, R²: -0.0008
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.21077 | val 0.21607
  Epoch 020 - train 0.17915 | val 0.21900
  Epoch 021 - train 0.18569 | val 0.21921
  Regression -> MSE: 0.000184, MAE: 0.008025, R²: -0.1046
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22760 | val 0.14534
  Epoch 020 - train 0.18742 | val 0.14877
  Epoch 021 - train 0.21014 | val 0.14948
  Regression -> MSE: 0.000238, MAE: 0.011912, R²: -0.0079
  Directional -> Accuracy: 0.5122, MCC: -0.0474, F1: 0.6552

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.20460 | val 0.28073
  Epoch 020 - train 0.20613 | val 0.29752
  Epoch 021 - train 0.19316 | val 0.29831
  Regression -> MSE: 0.000231, MAE: 0.009915, R²: -0.0028
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.21394 | val 0.22142
  Epoch 020 - train 0.18624 | val 0.21998
  Epoch 021 - train 0.20777 | val 0.21907
  Regression -> MSE: 0.000139, MAE: 0.008351, R²: -0.0284
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.23520 | val 0.21931
  Epoch 020 - train 0.22463 | val 0.22049
  Epoch 021 - train 0.21324 | val 0.22050
  Regression -> MSE: 0.000199, MAE: 0.010673, R²: -0.0551
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.18119 | val 0.24681
  Epoch 020 - train 0.18860 | val 0.24883
  Epoch 021 - train 0.19172 | val 0.24887
  Regression -> MSE: 0.000279, MAE: 0.010890, R²: -0.0646
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.19328 | val 0.15629
  Epoch 020 - train 0.17914 | val 0.14960
  Epoch 030 - train 0.17881 | val 0.14744
  Regression -> MSE: 0.000167, MAE: 0.010349, R²: -0.0001
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.18255 | val 0.18117
  Epoch 020 - train 0.18396 | val 0.18158
  Epoch 021 - train 0.19069 | val 0.18163
  Regression -> MSE: 0.000182, MAE: 0.010399, R²: -0.0119
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.20052 | val 0.17629
  Epoch 020 - train 0.20416 | val 0.17634
  Epoch 021 - train 0.20779 | val 0.17674
  Regression -> MSE: 0.000360, MAE: 0.012913, R²: -0.0502
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.22532 | val 0.11370
  Epoch 020 - train 0.21079 | val 0.13084
  Epoch 021 - train 0.20774 | val 0.13260
  Regression -> MSE: 0.000116, MAE: 0.008334, R²: -0.1014
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.19327 | val 0.24627
  Epoch 020 - train 0.20013 | val 0.25222
  Epoch 021 - train 0.20289 | val 0.25266
  Regression -> MSE: 0.000219, MAE: 0.011305, R²: -0.0014
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.20483 | val 0.31164
  Epoch 020 - train 0.21850 | val 0.32830
  Epoch 021 - train 0.19948 | val 0.32793
  Regression -> MSE: 0.000083, MAE: 0.007099, R²: -0.0672
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.20453 | val 0.15517
  Epoch 020 - train 0.19588 | val 0.15104
  Epoch 021 - train 0.17622 | val 0.15150
  Regression -> MSE: 0.000347, MAE: 0.015600, R²: -0.1286
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.18512 | val 0.11734
  Epoch 020 - train 0.21380 | val 0.11596
  Epoch 021 - train 0.20844 | val 0.11573
  Regression -> MSE: 0.000264, MAE: 0.011533, R²: -0.0828
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.20324 | val 0.22987
  Epoch 020 - train 0.20599 | val 0.23193
  Epoch 021 - train 0.19904 | val 0.23206
  Regression -> MSE: 0.000086, MAE: 0.007078, R²: -0.0677
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.20634 | val 0.21746
  Epoch 020 - train 0.21241 | val 0.22554
  Epoch 021 - train 0.23227 | val 0.22594
  Regression -> MSE: 0.000310, MAE: 0.014531, R²: -0.0095
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.19842 | val 0.19208
  Epoch 020 - train 0.19240 | val 0.21071
  Epoch 021 - train 0.20680 | val 0.21282
  Regression -> MSE: 0.000098, MAE: 0.007261, R²: 0.0002
  Directional -> Accuracy: 0.6136, MCC: 0.2503, F1: 0.7463

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.20257 | val 0.22385
  Epoch 020 - train 0.24277 | val 0.24700
  Epoch 021 - train 0.21034 | val 0.24943
  Regression -> MSE: 0.000175, MAE: 0.009428, R²: -0.0157
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.20166 | val 0.23367
  Epoch 020 - train 0.20159 | val 0.25652
  Epoch 021 - train 0.22007 | val 0.25707
  Regression -> MSE: 0.000224, MAE: 0.011758, R²: -0.0036
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.19387 | val 0.19372
  Epoch 020 - train 0.18302 | val 0.19398
  Epoch 021 - train 0.18657 | val 0.19372

[I 2026-02-24 01:40:55,838] Trial 93 finished with value: -0.011505027192049221 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 3.8690938691723115e-06, 'weight_decay': 5.574920450704152e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2787951078277558, 'early_stopping_min_delta': 0.006920843817783529}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.18935 | val 0.26016
  Epoch 021 - train 0.18696 | val 0.26157
  Regression -> MSE: 0.000237, MAE: 0.012453, R²: -0.0007
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11231 | val 0.16031
  Epoch 020 - train 0.11365 | val 0.16029
  Epoch 021 - train 0.11495 | val 0.15919
  Regression -> MSE: 0.000262, MAE: 0.013053, R²: -0.0576
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13522 | val 0.11231
  Epoch 020 - train 0.12859 | val 0.11528
  Epoch 021 - train 0.12009 | val 0.11555
  Regression -> MSE: 0.000699, MAE: 0.019648, R²: -0.0216
  Directional -> Accuracy: 0.4783, MCC: 0.0370, F1: 0.3333

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10936 | val 0.16572
  Epoch 020 - train 0.11413 | val 0.16595
  Epoch 021 - train 0.11015 | val 0.16626
  Regression -> MSE: 0.000312, MAE: 0.014430, R²: -0.0066
  Directional -> Accuracy: 0.4255, MCC: -0.1988, F1: 0.5424

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09658 | val 0.08662
  Epoch 020 - train 0.09562 | val 0.08476
  Epoch 021 - train 0.09068 | val 0.08448
  Regression -> MSE: 0.000349, MAE: 0.014568, R²: -0.0002
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11368 | val 0.10893
  Epoch 020 - train 0.11418 | val 0.10799
  Epoch 021 - train 0.11824 | val 0.10792
  Regression -> MSE: 0.000205, MAE: 0.010346, R²: -0.0089
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11490 | val 0.18459
  Epoch 020 - train 0.11174 | val 0.18759
  Epoch 021 - train 0.11274 | val 0.18766
  Regression -> MSE: 0.000574, MAE: 0.018489, R²: -0.0346
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11467 | val 0.14639
  Epoch 020 - train 0.11218 | val 0.14213
  Epoch 021 - train 0.11830 | val 0.14186
  Regression -> MSE: 0.000263, MAE: 0.013014, R²: -0.0710
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11595 | val 0.14579
  Epoch 020 - train 0.10386 | val 0.15879
  Epoch 021 - train 0.10989 | val 0.15686
  Regression -> MSE: 0.000661, MAE: 0.020425, R²: -0.1058
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10688 | val 0.11940
  Epoch 020 - train 0.10898 | val 0.11978
  Epoch 021 - train 0.10690 | val 0.11978
  Regression -> MSE: 0.000391, MAE: 0.015920, R²: -0.0205
  Directional -> Accuracy: 0.5102, MCC: -0.0161, F1: 0.3684

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11576 | val 0.12378
  Epoch 020 - train 0.11774 | val 0.12429
  Epoch 021 - train 0.11387 | val 0.12429
  Regression -> MSE: 0.000244, MAE: 0.012110, R²: -0.0115
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10133 | val 0.15091
  Epoch 020 - train 0.10612 | val 0.15147
  Epoch 021 - train 0.10618 | val 0.15062
  Regression -> MSE: 0.000312, MAE: 0.013680, R²: -0.0020
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11662 | val 0.14085
  Epoch 020 - train 0.11357 | val 0.14094
  Epoch 021 - train 0.11644 | val 0.14012
  Regression -> MSE: 0.000677, MAE: 0.019571, R²: 0.0006
  Directional -> Accuracy: 0.4138, MCC: -0.2381, F1: 0.1053

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11261 | val 0.10308
  Epoch 020 - train 0.10799 | val 0.10355
  Epoch 021 - train 0.10558 | val 0.10388
  Regression -> MSE: 0.000139, MAE: 0.009006, R²: -0.0091
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10390 | val 0.15183
  Epoch 020 - train 0.10178 | val 0.15278
  Epoch 021 - train 0.10320 | val 0.15208
  Regression -> MSE: 0.000225, MAE: 0.010733, R²: -0.0022
  Directional -> Accuracy: 0.4918, MCC: -0.0073, F1: 0.2439

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11600 | val 0.20909
  Epoch 020 - train 0.11677 | val 0.21018
  Epoch 021 - train 0.11829 | val 0.20970
  Regression -> MSE: 0.000364, MAE: 0.016248, R²: -0.0057
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12682 | val 0.15257
  Epoch 020 - train 0.12211 | val 0.15020
  Epoch 021 - train 0.12701 | val 0.14939
  Regression -> MSE: 0.000113, MAE: 0.008001, R²: -0.0462
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11610 | val 0.18150
  Epoch 020 - train 0.10811 | val 0.18443
  Epoch 021 - train 0.11004 | val 0.18450
  Regression -> MSE: 0.000156, MAE: 0.009849, R²: -0.0007
  Directional -> Accuracy: 0.5932, MCC: 0.1302, F1: 0.6757

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11692 | val 0.10922
  Epoch 020 - train 0.11274 | val 0.10917
  Epoch 021 - train 0.11456 | val 0.10911
  Regression -> MSE: 0.000272, MAE: 0.012892, R²: 0.0004
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10501 | val 0.14415
  Epoch 020 - train 0.10832 | val 0.14289
  Epoch 021 - train 0.10995 | val 0.14358
  Regression -> MSE: 0.000163, MAE: 0.009055, R²: -0.0878
  Directional -> Accuracy: 0.4769, MCC: 0.0619, F1: 0.3462

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10871 | val 0.14048
  Epoch 020 - train 0.10696 | val 0.14084
  Epoch 021 - train 0.11343 | val 0.14080
  Regression -> MSE: 0.000243, MAE: 0.011102, R²: -0.0719
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11440 | val 0.13272
  Epoch 020 - train 0.10466 | val 0.13168
  Epoch 021 - train 0.11274 | val 0.13203
  Regression -> MSE: 0.000145, MAE: 0.008463, R²: -0.0133
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10673 | val 0.12135
  Epoch 020 - train 0.10876 | val 0.12195
  Epoch 021 - train 0.10835 | val 0.12191
  Regression -> MSE: 0.000167, MAE: 0.010782, R²: -0.0124
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10967 | val 0.12908
  Epoch 020 - train 0.11006 | val 0.12928
  Epoch 021 - train 0.11688 | val 0.12912
  Regression -> MSE: 0.000088, MAE: 0.007206, R²: -0.0344
  Directional -> Accuracy: 0.4828, MCC: -0.0882, F1: 0.5833

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10834 | val 0.13153
  Epoch 020 - train 0.10632 | val 0.13049
  Epoch 021 - train 0.11000 | val 0.12977
  Regression -> MSE: 0.000211, MAE: 0.010999, R²: 0.0018
  Directional -> Accuracy: 0.5758, MCC: 0.1493, F1: 0.3333

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10665 | val 0.10200
  Epoch 020 - train 0.09855 | val 0.10095
  Epoch 021 - train 0.09965 | val 0.10083
  Regression -> MSE: 0.000103, MAE: 0.008314, R²: -0.1221
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13024 | val 0.09585
  Epoch 020 - train 0.12004 | val 0.13572
  Epoch 021 - train 0.10918 | val 0.13660
  Regression -> MSE: 0.000102, MAE: 0.008630, R²: 0.0131
  Directional -> Accuracy: 0.5870, MCC: 0.1236, F1: 0.1739

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11847 | val 0.15091
  Epoch 020 - train 0.11222 | val 0.15916
  Epoch 021 - train 0.10949 | val 0.16001
  Regression -> MSE: 0.000254, MAE: 0.013229, R²: -0.0983
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10857 | val 0.11156
  Epoch 020 - train 0.11713 | val 0.11085
  Epoch 029 - train 0.11034 | val 0.11109
  Regression -> MSE: 0.000224, MAE: 0.009858, R²: -0.3485
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11389 | val 0.08503
  Epoch 020 - train 0.11491 | val 0.08449
  Epoch 021 - train 0.12118 | val 0.08421
  Regression -> MSE: 0.000237, MAE: 0.011904, R²: -0.0034
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10876 | val 0.15175
  Epoch 020 - train 0.10711 | val 0.15255
  Epoch 021 - train 0.11448 | val 0.15244
  Regression -> MSE: 0.000232, MAE: 0.009928, R²: -0.0046
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11150 | val 0.13397
  Epoch 020 - train 0.11432 | val 0.13622
  Epoch 021 - train 0.11268 | val 0.13617
  Regression -> MSE: 0.000144, MAE: 0.008725, R²: -0.0671
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12327 | val 0.12154
  Epoch 020 - train 0.11537 | val 0.12195
  Epoch 021 - train 0.11782 | val 0.12193
  Regression -> MSE: 0.000194, MAE: 0.010460, R²: -0.0306
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10803 | val 0.13168
  Epoch 020 - train 0.11566 | val 0.13062
  Epoch 021 - train 0.10445 | val 0.12946
  Regression -> MSE: 0.000274, MAE: 0.010735, R²: -0.0452
  Directional -> Accuracy: 0.4521, MCC: -0.1128, F1: 0.5122

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10624 | val 0.08942
  Epoch 020 - train 0.10216 | val 0.09436
  Epoch 021 - train 0.11563 | val 0.09514
  Regression -> MSE: 0.000166, MAE: 0.010339, R²: 0.0016
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11361 | val 0.11425
  Epoch 020 - train 0.10958 | val 0.11339
  Epoch 021 - train 0.10858 | val 0.11304
  Regression -> MSE: 0.000195, MAE: 0.010879, R²: -0.0847
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10758 | val 0.09799
  Epoch 020 - train 0.11138 | val 0.09676
  Epoch 021 - train 0.11126 | val 0.09674
  Regression -> MSE: 0.000350, MAE: 0.011944, R²: -0.0212
  Directional -> Accuracy: 0.4328, MCC: -0.1376, F1: 0.4722

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11619 | val 0.06776
  Epoch 020 - train 0.12797 | val 0.06834
  Epoch 021 - train 0.11885 | val 0.06824
  Regression -> MSE: 0.000113, MAE: 0.008391, R²: -0.0731
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11827 | val 0.13986
  Epoch 020 - train 0.11732 | val 0.14214
  Epoch 021 - train 0.12524 | val 0.14094
  Regression -> MSE: 0.000225, MAE: 0.011482, R²: -0.0284
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10307 | val 0.16773
  Epoch 020 - train 0.11113 | val 0.16679
  Epoch 021 - train 0.10590 | val 0.16676
  Regression -> MSE: 0.000095, MAE: 0.007599, R²: -0.2212
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11777 | val 0.07908
  Epoch 020 - train 0.10797 | val 0.07899
  Epoch 021 - train 0.10199 | val 0.07895
  Regression -> MSE: 0.000312, MAE: 0.014077, R²: -0.0138
  Directional -> Accuracy: 0.4490, MCC: 0.1555, F1: 0.5574

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11278 | val 0.08026
  Epoch 020 - train 0.12063 | val 0.09308
  Epoch 021 - train 0.11059 | val 0.09368
  Regression -> MSE: 0.000261, MAE: 0.011491, R²: -0.0714
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11340 | val 0.12216
  Epoch 020 - train 0.10534 | val 0.12194
  Epoch 021 - train 0.11408 | val 0.12172
  Regression -> MSE: 0.000081, MAE: 0.007109, R²: -0.0047
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12776 | val 0.14619
  Epoch 020 - train 0.13072 | val 0.15147
  Epoch 021 - train 0.12223 | val 0.15126
  Regression -> MSE: 0.000317, MAE: 0.014517, R²: -0.0318
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10631 | val 0.12573
  Epoch 020 - train 0.09984 | val 0.13096
  Epoch 021 - train 0.11250 | val 0.13131
  Regression -> MSE: 0.000105, MAE: 0.007106, R²: -0.0690
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12862 | val 0.13929
  Epoch 020 - train 0.12360 | val 0.15358
  Epoch 021 - train 0.12120 | val 0.15408
  Regression -> MSE: 0.000174, MAE: 0.009443, R²: -0.0135
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10699 | val 0.12293
  Epoch 020 - train 0.10663 | val 0.12319
  Epoch 021 - train 0.10351 | val 0.12238
  Regression -> MSE: 0.000226, MAE: 0.011884, R²: -0.0120
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11243 | val 0.12543
  Epoch 020 - train 0.11624 | val 0.12481
  Epoch 021 - train 0.11735 | val 0.12487

[I 2026-02-24 01:42:43,899] Trial 94 finished with value: -0.011546773033332413 and parameters: {'feature_set': 'finbert', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 6.684100246686834e-06, 'weight_decay': 1.0485578766028353e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.14665232547359794, 'early_stopping_min_delta': 0.007399551634562008}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.11222 | val 0.14636
  Epoch 021 - train 0.10788 | val 0.14722
  Regression -> MSE: 0.000237, MAE: 0.012382, R²: 0.0009
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14946 | val 0.21047
  Epoch 020 - train 0.16008 | val 0.21156
  Epoch 021 - train 0.14908 | val 0.21155
  Regression -> MSE: 0.000252, MAE: 0.012720, R²: -0.0169
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.17158 | val 0.15104
  Epoch 020 - train 0.15922 | val 0.16478
  Epoch 021 - train 0.15913 | val 0.16341
  Regression -> MSE: 0.000714, MAE: 0.019846, R²: -0.0426
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.17670 | val 0.26689
  Epoch 020 - train 0.17043 | val 0.27180
  Epoch 021 - train 0.16558 | val 0.27216
  Regression -> MSE: 0.000313, MAE: 0.014518, R²: -0.0075
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14532 | val 0.27158
  Epoch 020 - train 0.14864 | val 0.27394
  Epoch 021 - train 0.14294 | val 0.27190
  Regression -> MSE: 0.000388, MAE: 0.015238, R²: -0.1116
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15488 | val 0.15625
  Epoch 020 - train 0.15802 | val 0.16074
  Epoch 021 - train 0.15261 | val 0.16248
  Regression -> MSE: 0.000204, MAE: 0.010174, R²: -0.0003
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15647 | val 0.30574
  Epoch 020 - train 0.14482 | val 0.31377
  Epoch 021 - train 0.14829 | val 0.31386
  Regression -> MSE: 0.000580, MAE: 0.018568, R²: -0.0440
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16371 | val 0.19587
  Epoch 020 - train 0.16127 | val 0.19623
  Epoch 021 - train 0.16204 | val 0.19644
  Regression -> MSE: 0.000247, MAE: 0.012287, R²: -0.0052
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15580 | val 0.20592
  Epoch 020 - train 0.16253 | val 0.23415
  Epoch 021 - train 0.15556 | val 0.23518
  Regression -> MSE: 0.000612, MAE: 0.019506, R²: -0.0239
  Directional -> Accuracy: 0.5909, MCC: 0.0735, F1: 0.2500

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.16309 | val 0.18978
  Epoch 020 - train 0.14889 | val 0.19412
  Epoch 021 - train 0.14830 | val 0.19391
  Regression -> MSE: 0.000397, MAE: 0.015999, R²: -0.0349
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16342 | val 0.21041
  Epoch 020 - train 0.15957 | val 0.21112
  Epoch 021 - train 0.15720 | val 0.21036
  Regression -> MSE: 0.000241, MAE: 0.011848, R²: 0.0002
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15328 | val 0.22479
  Epoch 020 - train 0.16006 | val 0.23271
  Epoch 021 - train 0.14007 | val 0.23339
  Regression -> MSE: 0.000313, MAE: 0.013639, R²: -0.0052
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.16560 | val 0.19195
  Epoch 020 - train 0.15854 | val 0.20694
  Epoch 021 - train 0.16279 | val 0.20824
  Regression -> MSE: 0.000678, MAE: 0.019543, R²: -0.0017
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.15579 | val 0.18215
  Epoch 020 - train 0.15928 | val 0.27825
  Epoch 021 - train 0.15254 | val 0.27600
  Regression -> MSE: 0.000142, MAE: 0.009399, R²: -0.0310
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14845 | val 0.21490
  Epoch 020 - train 0.14054 | val 0.21999
  Epoch 021 - train 0.14864 | val 0.21966
  Regression -> MSE: 0.000230, MAE: 0.010889, R²: -0.0230
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16628 | val 0.32557
  Epoch 020 - train 0.15130 | val 0.32485
  Epoch 021 - train 0.15360 | val 0.32503
  Regression -> MSE: 0.000363, MAE: 0.016055, R²: -0.0026
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15577 | val 0.17784
  Epoch 020 - train 0.16856 | val 0.18171
  Epoch 021 - train 0.17139 | val 0.18111
  Regression -> MSE: 0.000110, MAE: 0.007939, R²: -0.0185
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15292 | val 0.27575
  Epoch 020 - train 0.16074 | val 0.30384
  Epoch 021 - train 0.15308 | val 0.30575
  Regression -> MSE: 0.000156, MAE: 0.009553, R²: -0.0032
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16708 | val 0.16675
  Epoch 020 - train 0.16443 | val 0.16675
  Epoch 021 - train 0.17248 | val 0.16657
  Regression -> MSE: 0.000278, MAE: 0.013360, R²: -0.0231
  Directional -> Accuracy: 0.4079, MCC: -0.1030, F1: 0.3284

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13958 | val 0.21895
  Epoch 020 - train 0.14626 | val 0.21765
  Epoch 021 - train 0.14033 | val 0.21773
  Regression -> MSE: 0.000157, MAE: 0.008793, R²: -0.0472
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15625 | val 0.25912
  Epoch 020 - train 0.16099 | val 0.26360
  Epoch 021 - train 0.15666 | val 0.26273
  Regression -> MSE: 0.000234, MAE: 0.010931, R²: -0.0339
  Directional -> Accuracy: 0.6000, MCC: 0.2571, F1: 0.5312

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16585 | val 0.19989
  Epoch 020 - train 0.15824 | val 0.20596
  Epoch 021 - train 0.16709 | val 0.20647
  Regression -> MSE: 0.000153, MAE: 0.008814, R²: -0.0664
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14868 | val 0.19677
  Epoch 020 - train 0.14897 | val 0.19854
  Epoch 021 - train 0.16603 | val 0.19851
  Regression -> MSE: 0.000165, MAE: 0.010376, R²: 0.0024
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16296 | val 0.18779
  Epoch 020 - train 0.17149 | val 0.18910
  Epoch 021 - train 0.15863 | val 0.18940
  Regression -> MSE: 0.000089, MAE: 0.007263, R²: -0.0453
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16644 | val 0.20131
  Epoch 020 - train 0.16488 | val 0.19958
  Epoch 021 - train 0.16024 | val 0.19950
  Regression -> MSE: 0.000216, MAE: 0.011024, R²: -0.0185
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.15102 | val 0.13583
  Epoch 020 - train 0.14020 | val 0.13771
  Epoch 030 - train 0.13684 | val 0.13730
  Regression -> MSE: 0.000094, MAE: 0.007912, R²: -0.0216
  Directional -> Accuracy: 0.5536, MCC: 0.1340, F1: 0.5283

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17008 | val 0.13077
  Epoch 020 - train 0.15976 | val 0.13429
  Epoch 021 - train 0.15253 | val 0.13443
  Regression -> MSE: 0.000111, MAE: 0.009078, R²: -0.0795
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15495 | val 0.16454
  Epoch 020 - train 0.16297 | val 0.18028
  Epoch 021 - train 0.17034 | val 0.18145
  Regression -> MSE: 0.000240, MAE: 0.012834, R²: -0.0357
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.16105 | val 0.18650
  Epoch 020 - train 0.15319 | val 0.18409
  Epoch 030 - train 0.15034 | val 0.18426
  Regression -> MSE: 0.000189, MAE: 0.008169, R²: -0.1365
  Directional -> Accuracy: 0.5263, MCC: 0.0784, F1: 0.5091

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.17498 | val 0.14287
  Epoch 020 - train 0.18134 | val 0.16468
  Epoch 021 - train 0.16525 | val 0.16617
  Regression -> MSE: 0.000238, MAE: 0.011903, R²: -0.0052
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.17624 | val 0.25395
  Epoch 020 - train 0.15433 | val 0.26183
  Epoch 021 - train 0.17028 | val 0.26359
  Regression -> MSE: 0.000230, MAE: 0.009882, R²: -0.0001
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16701 | val 0.20120
  Epoch 020 - train 0.16339 | val 0.19997
  Epoch 021 - train 0.15901 | val 0.19949
  Regression -> MSE: 0.000142, MAE: 0.008513, R²: -0.0508
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.16546 | val 0.20568
  Epoch 020 - train 0.15913 | val 0.21017
  Epoch 021 - train 0.16037 | val 0.21040
  Regression -> MSE: 0.000191, MAE: 0.010397, R²: -0.0121
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14426 | val 0.20806
  Epoch 020 - train 0.14729 | val 0.20575
  Epoch 021 - train 0.14603 | val 0.20624
  Regression -> MSE: 0.000266, MAE: 0.010533, R²: -0.0145
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16168 | val 0.13293
  Epoch 020 - train 0.15227 | val 0.14424
  Epoch 021 - train 0.15794 | val 0.14799
  Regression -> MSE: 0.000170, MAE: 0.010370, R²: -0.0196
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14777 | val 0.16421
  Epoch 020 - train 0.14493 | val 0.16672
  Epoch 021 - train 0.13972 | val 0.16623
  Regression -> MSE: 0.000188, MAE: 0.010614, R²: -0.0426
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15879 | val 0.15437
  Epoch 020 - train 0.14320 | val 0.15877
  Epoch 021 - train 0.15211 | val 0.15924
  Regression -> MSE: 0.000345, MAE: 0.011695, R²: -0.0071
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16978 | val 0.10572
  Epoch 020 - train 0.17896 | val 0.11188
  Epoch 021 - train 0.18145 | val 0.11215
  Regression -> MSE: 0.000128, MAE: 0.008530, R²: -0.2180
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16312 | val 0.21730
  Epoch 020 - train 0.15449 | val 0.22262
  Epoch 021 - train 0.16494 | val 0.22356
  Regression -> MSE: 0.000219, MAE: 0.011265, R²: -0.0024
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16920 | val 0.27536
  Epoch 020 - train 0.15577 | val 0.28114
  Epoch 021 - train 0.16019 | val 0.28209
  Regression -> MSE: 0.000086, MAE: 0.007267, R²: -0.1125
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.16882 | val 0.13874
  Epoch 020 - train 0.15902 | val 0.14647
  Epoch 021 - train 0.17164 | val 0.14696
  Regression -> MSE: 0.000337, MAE: 0.015252, R²: -0.0963
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.16917 | val 0.10561
  Epoch 020 - train 0.17850 | val 0.10310
  Epoch 021 - train 0.17706 | val 0.10308
  Regression -> MSE: 0.000261, MAE: 0.011499, R²: -0.0700
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16139 | val 0.19067
  Epoch 020 - train 0.14833 | val 0.18951
  Epoch 021 - train 0.15701 | val 0.18965
  Regression -> MSE: 0.000081, MAE: 0.007109, R²: -0.0024
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17346 | val 0.19838
  Epoch 020 - train 0.16493 | val 0.21588
  Epoch 030 - train 0.15439 | val 0.22238
  Regression -> MSE: 0.000312, MAE: 0.014523, R²: -0.0170
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16324 | val 0.17076
  Epoch 020 - train 0.15084 | val 0.17695
  Epoch 021 - train 0.15814 | val 0.17770
  Regression -> MSE: 0.000098, MAE: 0.007288, R²: 0.0009
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16696 | val 0.19206
  Epoch 020 - train 0.16875 | val 0.22057
  Epoch 021 - train 0.17128 | val 0.22342
  Regression -> MSE: 0.000176, MAE: 0.010220, R²: -0.0226
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.15021 | val 0.20093
  Epoch 020 - train 0.15244 | val 0.20982
  Epoch 021 - train 0.15938 | val 0.20824
  Regression -> MSE: 0.000224, MAE: 0.011746, R²: -0.0033
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.15720 | val 0.17797
  Epoch 020 - train 0.15414 | val 0.18737
  Epoch 021 - train 0.15240 | val 0.18722

[I 2026-02-24 01:44:43,885] Trial 95 finished with value: -0.011481073483568485 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 7.13028770781619e-05, 'weight_decay': 1.994286966882094e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.24857725006890194, 'early_stopping_min_delta': 0.007758250260389977}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.15768 | val 0.23464
  Epoch 021 - train 0.16469 | val 0.23465
  Regression -> MSE: 0.000238, MAE: 0.012320, R²: -0.0022
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15103 | val 0.20333
  Epoch 020 - train 0.15792 | val 0.20389
  Epoch 021 - train 0.15017 | val 0.20226
  Regression -> MSE: 0.000245, MAE: 0.012516, R²: -0.0203
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.15221 | val 0.14438
  Epoch 020 - train 0.14857 | val 0.14451
  Epoch 021 - train 0.15413 | val 0.14557
  Regression -> MSE: 0.000734, MAE: 0.020283, R²: -0.0517
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15182 | val 0.21626
  Epoch 020 - train 0.15350 | val 0.21523
  Epoch 030 - train 0.14654 | val 0.21441
  Regression -> MSE: 0.000334, MAE: 0.014615, R²: -0.0603
  Directional -> Accuracy: 0.5870, MCC: 0.1921, F1: 0.5366

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12510 | val 0.15488
  Epoch 020 - train 0.13058 | val 0.15172
  Epoch 021 - train 0.12417 | val 0.15767
  Regression -> MSE: 0.000355, MAE: 0.014669, R²: -0.0037
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15452 | val 0.16261
  Epoch 020 - train 0.14793 | val 0.15954
  Epoch 021 - train 0.14585 | val 0.15960
  Regression -> MSE: 0.000206, MAE: 0.010259, R²: 0.0001
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.14942 | val 0.25759
  Epoch 020 - train 0.15255 | val 0.25937
  Epoch 021 - train 0.15474 | val 0.25829
  Regression -> MSE: 0.000566, MAE: 0.018440, R²: 0.0006
  Directional -> Accuracy: 0.4783, MCC: 0.0000, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15508 | val 0.18042
  Epoch 020 - train 0.15028 | val 0.18271
  Epoch 021 - train 0.14980 | val 0.18316
  Regression -> MSE: 0.000253, MAE: 0.011958, R²: -0.0185
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14706 | val 0.10403
  Epoch 020 - train 0.15628 | val 0.09871
  Epoch 030 - train 0.14792 | val 0.09898
  Regression -> MSE: 0.000662, MAE: 0.020192, R²: -0.0839
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14247 | val 0.17450
  Epoch 020 - train 0.13553 | val 0.16959
  Epoch 021 - train 0.15451 | val 0.17051
  Regression -> MSE: 0.000379, MAE: 0.015623, R²: -0.0169
  Directional -> Accuracy: 0.5625, MCC: 0.0263, F1: 0.0870

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15547 | val 0.20958
  Epoch 020 - train 0.15266 | val 0.20691
  Epoch 021 - train 0.14374 | val 0.20843
  Regression -> MSE: 0.000249, MAE: 0.011816, R²: -0.0162
  Directional -> Accuracy: 0.5797, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13670 | val 0.28649
  Epoch 020 - train 0.13206 | val 0.28765
  Epoch 021 - train 0.14451 | val 0.28537
  Regression -> MSE: 0.000315, MAE: 0.013864, R²: -0.0088
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.17124 | val 0.19283
  Epoch 020 - train 0.16861 | val 0.19360
  Epoch 021 - train 0.16661 | val 0.19201
  Regression -> MSE: 0.000699, MAE: 0.019744, R²: -0.0188
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14501 | val 0.30244
  Epoch 020 - train 0.14066 | val 0.29661
  Epoch 021 - train 0.14174 | val 0.30402
  Regression -> MSE: 0.000141, MAE: 0.009276, R²: -0.0211
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13343 | val 0.19646
  Epoch 020 - train 0.12433 | val 0.19402
  Epoch 021 - train 0.13911 | val 0.19410
  Regression -> MSE: 0.000232, MAE: 0.010873, R²: -0.0227
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14817 | val 0.34175
  Epoch 020 - train 0.14800 | val 0.33768
  Epoch 021 - train 0.14710 | val 0.33535
  Regression -> MSE: 0.000370, MAE: 0.016005, R²: -0.0083
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16068 | val 0.14603
  Epoch 020 - train 0.15921 | val 0.14588
  Epoch 021 - train 0.14815 | val 0.14610
  Regression -> MSE: 0.000108, MAE: 0.007947, R²: 0.0006
  Directional -> Accuracy: 0.5507, MCC: 0.1304, F1: 0.7048

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14164 | val 0.24657
  Epoch 020 - train 0.14488 | val 0.25210
  Epoch 021 - train 0.14481 | val 0.25581
  Regression -> MSE: 0.000165, MAE: 0.010297, R²: -0.0492
  Directional -> Accuracy: 0.3793, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15436 | val 0.13738
  Epoch 020 - train 0.14537 | val 0.13696
  Epoch 021 - train 0.15140 | val 0.13673
  Regression -> MSE: 0.000286, MAE: 0.013606, R²: -0.0441
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13168 | val 0.21733
  Epoch 020 - train 0.13593 | val 0.21925
  Epoch 021 - train 0.13324 | val 0.22001
  Regression -> MSE: 0.000175, MAE: 0.009409, R²: -0.1533
  Directional -> Accuracy: 0.4219, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15374 | val 0.26850
  Epoch 020 - train 0.14934 | val 0.27143
  Epoch 021 - train 0.15382 | val 0.27145
  Regression -> MSE: 0.000255, MAE: 0.011404, R²: -0.1233
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14070 | val 0.18383
  Epoch 020 - train 0.13828 | val 0.18402
  Epoch 021 - train 0.14324 | val 0.18453
  Regression -> MSE: 0.000145, MAE: 0.008382, R²: -0.0057
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14088 | val 0.15879
  Epoch 020 - train 0.13994 | val 0.16121
  Epoch 025 - train 0.14166 | val 0.16015
  Regression -> MSE: 0.000192, MAE: 0.010926, R²: -0.1606
  Directional -> Accuracy: 0.5231, MCC: 0.0503, F1: 0.4746

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15682 | val 0.16845
  Epoch 020 - train 0.15801 | val 0.16766
  Epoch 021 - train 0.15795 | val 0.16802
  Regression -> MSE: 0.000092, MAE: 0.007442, R²: -0.0652
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15107 | val 0.18088
  Epoch 020 - train 0.15000 | val 0.17755
  Epoch 021 - train 0.15322 | val 0.17960
  Regression -> MSE: 0.000212, MAE: 0.011014, R²: -0.0036
  Directional -> Accuracy: 0.4615, MCC: -0.0636, F1: 0.5455

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13145 | val 0.14099
  Epoch 020 - train 0.13359 | val 0.13836
  Epoch 021 - train 0.13547 | val 0.13801
  Regression -> MSE: 0.000094, MAE: 0.008008, R²: -0.0418
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.15449 | val 0.11609
  Epoch 020 - train 0.15303 | val 0.11654
  Epoch 021 - train 0.14762 | val 0.11625
  Regression -> MSE: 0.000103, MAE: 0.008752, R²: -0.0397
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14904 | val 0.18037
  Epoch 020 - train 0.15383 | val 0.17920
  Epoch 021 - train 0.14852 | val 0.17969
  Regression -> MSE: 0.000246, MAE: 0.013119, R²: -0.0365
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13830 | val 0.15921
  Epoch 020 - train 0.14239 | val 0.15855
  Epoch 021 - train 0.14603 | val 0.15864
  Regression -> MSE: 0.000184, MAE: 0.008049, R²: -0.0842
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.15893 | val 0.12955
  Epoch 020 - train 0.15936 | val 0.14826
  Epoch 021 - train 0.15598 | val 0.14948
  Regression -> MSE: 0.000242, MAE: 0.012084, R²: -0.0005
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13418 | val 0.22843
  Epoch 020 - train 0.14568 | val 0.22671
  Epoch 021 - train 0.14920 | val 0.22683
  Regression -> MSE: 0.000238, MAE: 0.010240, R²: -0.0092
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15436 | val 0.16839
  Epoch 020 - train 0.15878 | val 0.16655
  Epoch 021 - train 0.15944 | val 0.16703
  Regression -> MSE: 0.000148, MAE: 0.008884, R²: -0.0729
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15565 | val 0.19525
  Epoch 020 - train 0.15077 | val 0.19418
  Epoch 021 - train 0.15344 | val 0.19408
  Regression -> MSE: 0.000186, MAE: 0.010162, R²: -0.0148
  Directional -> Accuracy: 0.5102, MCC: 0.0118, F1: 0.5556

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12364 | val 0.17162
  Epoch 020 - train 0.12810 | val 0.17296
  Epoch 021 - train 0.12556 | val 0.17026
  Regression -> MSE: 0.000275, MAE: 0.010773, R²: -0.0368
  Directional -> Accuracy: 0.4306, MCC: -0.0855, F1: 0.0889

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13872 | val 0.14485
  Epoch 020 - train 0.14036 | val 0.14545
  Epoch 021 - train 0.14748 | val 0.14726
  Regression -> MSE: 0.000186, MAE: 0.010494, R²: -0.0165
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14138 | val 0.13452
  Epoch 020 - train 0.14052 | val 0.13367
  Epoch 021 - train 0.14319 | val 0.13340
  Regression -> MSE: 0.000348, MAE: 0.011832, R²: -0.0007
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.15262 | val 0.09645
  Epoch 020 - train 0.16118 | val 0.09808
  Epoch 021 - train 0.15437 | val 0.09822
  Regression -> MSE: 0.000123, MAE: 0.008490, R²: -0.1682
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15745 | val 0.18833
  Epoch 020 - train 0.14111 | val 0.18846
  Epoch 021 - train 0.14893 | val 0.18776
  Regression -> MSE: 0.000223, MAE: 0.011374, R²: -0.0120
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15813 | val 0.29443
  Epoch 020 - train 0.14632 | val 0.29490
  Epoch 021 - train 0.15181 | val 0.29373
  Regression -> MSE: 0.000076, MAE: 0.006793, R²: -0.0328
  Directional -> Accuracy: 0.6087, MCC: 0.0000, F1: 0.7568

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15031 | val 0.10371
  Epoch 020 - train 0.16107 | val 0.10562
  Epoch 021 - train 0.15123 | val 0.10566
  Regression -> MSE: 0.000318, MAE: 0.014233, R²: -0.0203
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14398 | val 0.19865
  Epoch 020 - train 0.14790 | val 0.19806
  Epoch 021 - train 0.15022 | val 0.20024
  Regression -> MSE: 0.000078, MAE: 0.006965, R²: -0.0058
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14776 | val 0.19150
  Epoch 020 - train 0.14940 | val 0.19444
  Epoch 021 - train 0.15584 | val 0.19277
  Regression -> MSE: 0.000303, MAE: 0.014397, R²: -0.0058
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13506 | val 0.17087
  Epoch 020 - train 0.13967 | val 0.16990
  Epoch 021 - train 0.14473 | val 0.16980
  Regression -> MSE: 0.000105, MAE: 0.007207, R²: -0.0368
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15201 | val 0.18578
  Epoch 020 - train 0.14905 | val 0.19293
  Epoch 021 - train 0.16282 | val 0.19160
  Regression -> MSE: 0.000178, MAE: 0.010290, R²: -0.0149
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.5455

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14743 | val 0.16613
  Epoch 020 - train 0.14153 | val 0.16499
  Epoch 021 - train 0.14387 | val 0.16635
  Regression -> MSE: 0.000226, MAE: 0.011833, R²: -0.0037
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.15415 | val 0.18936
  Epoch 020 - train 0.13616 | val 0.19187
  Epoch 021 - train 0.14949 | val 0.19310
  Regression -> MSE: 0.000095, MAE: 0.007792, R²: -0.0089
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.6506

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.14606 | val 0.22110
  Epoch 020 - train 0.15301 | val 0.22171
  Epoch 021 - train 0.15406 | val 0.22088
  Regression -> MSE: 0.000171, MAE: 0.010433, R²: -0.0253

[I 2026-02-24 01:48:00,366] Trial 96 finished with value: -0.01154841379037446 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 1.0505695542872804e-05, 'weight_decay': 4.563079570486613e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.21132530564210486, 'early_stopping_min_delta': 0.006604632479090265}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.15185 | val 0.20734
  Regression -> MSE: 0.000240, MAE: 0.012517, R²: -0.0007
  Directional -> Accuracy: 0.4833, MCC: 0.0000, F1: 0.6517

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07905 | val 0.09808
  Epoch 020 - train 0.08226 | val 0.09806
  Epoch 021 - train 0.08120 | val 0.09866
  Regression -> MSE: 0.000249, MAE: 0.012595, R²: -0.0043
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07934 | val 0.06973
  Epoch 020 - train 0.07795 | val 0.06885
  Epoch 021 - train 0.08415 | val 0.06893
  Regression -> MSE: 0.000687, MAE: 0.019385, R²: -0.0035
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.08382 | val 0.11314
  Epoch 020 - train 0.08375 | val 0.10783
  Epoch 030 - train 0.08380 | val 0.10860
  Regression -> MSE: 0.000321, MAE: 0.014177, R²: -0.0334
  Directional -> Accuracy: 0.5106, MCC: 0.0092, F1: 0.5660

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06958 | val 0.08257
  Epoch 020 - train 0.06779 | val 0.08189
  Epoch 021 - train 0.07172 | val 0.08074
  Regression -> MSE: 0.000350, MAE: 0.014614, R²: -0.0024
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.08199 | val 0.08534
  Epoch 020 - train 0.08189 | val 0.09264
  Epoch 021 - train 0.08104 | val 0.09299
  Regression -> MSE: 0.000212, MAE: 0.010258, R²: -0.0405
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07581 | val 0.13759
  Epoch 020 - train 0.08158 | val 0.14032
  Epoch 021 - train 0.07977 | val 0.14027
  Regression -> MSE: 0.000583, MAE: 0.018631, R²: -0.0497
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07899 | val 0.09356
  Epoch 020 - train 0.08674 | val 0.09390
  Epoch 021 - train 0.08092 | val 0.09390
  Regression -> MSE: 0.000248, MAE: 0.011942, R²: -0.0085
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08525 | val 0.11029
  Epoch 020 - train 0.08432 | val 0.11936
  Epoch 021 - train 0.07787 | val 0.12015
  Regression -> MSE: 0.000672, MAE: 0.020583, R²: -0.1255
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08376 | val 0.08727
  Epoch 020 - train 0.08060 | val 0.09148
  Epoch 021 - train 0.07911 | val 0.09170
  Regression -> MSE: 0.000405, MAE: 0.016138, R²: -0.0550
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.08916 | val 0.09525
  Epoch 020 - train 0.08411 | val 0.09532
  Epoch 021 - train 0.08463 | val 0.09537
  Regression -> MSE: 0.000243, MAE: 0.011685, R²: -0.0063
  Directional -> Accuracy: 0.5571, MCC: 0.0227, F1: 0.2439

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08217 | val 0.10195
  Epoch 020 - train 0.08097 | val 0.09991
  Epoch 021 - train 0.07748 | val 0.10011
  Regression -> MSE: 0.000311, MAE: 0.013695, R²: 0.0000
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08499 | val 0.08517
  Epoch 020 - train 0.08549 | val 0.08537
  Epoch 021 - train 0.08373 | val 0.08510
  Regression -> MSE: 0.000684, MAE: 0.019724, R²: -0.0097
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.08423 | val 0.07766
  Epoch 020 - train 0.08573 | val 0.10105
  Epoch 021 - train 0.08189 | val 0.10065
  Regression -> MSE: 0.000147, MAE: 0.009587, R²: -0.0636
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08075 | val 0.10568
  Epoch 020 - train 0.08229 | val 0.10801
  Epoch 021 - train 0.08271 | val 0.10744
  Regression -> MSE: 0.000228, MAE: 0.010977, R²: -0.0135
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08309 | val 0.16210
  Epoch 020 - train 0.08599 | val 0.18392
  Epoch 021 - train 0.08079 | val 0.18453
  Regression -> MSE: 0.000363, MAE: 0.016229, R²: -0.0031
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.08720 | val 0.09599
  Epoch 020 - train 0.08764 | val 0.09743
  Epoch 021 - train 0.08328 | val 0.09700
  Regression -> MSE: 0.000109, MAE: 0.008092, R²: -0.0088
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08164 | val 0.13344
  Epoch 020 - train 0.08414 | val 0.13873
  Epoch 021 - train 0.08561 | val 0.13970
  Regression -> MSE: 0.000156, MAE: 0.009746, R²: -0.0029
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08198 | val 0.07996
  Epoch 020 - train 0.08252 | val 0.08026
  Epoch 021 - train 0.08201 | val 0.08012
  Regression -> MSE: 0.000283, MAE: 0.013545, R²: -0.0405
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07972 | val 0.10789
  Epoch 020 - train 0.08123 | val 0.10955
  Epoch 021 - train 0.07375 | val 0.10900
  Regression -> MSE: 0.000153, MAE: 0.008750, R²: -0.0224
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.08413 | val 0.12141
  Epoch 020 - train 0.08173 | val 0.12038
  Epoch 021 - train 0.08402 | val 0.12067
  Regression -> MSE: 0.000227, MAE: 0.010874, R²: -0.0021
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08846 | val 0.09390
  Epoch 020 - train 0.08579 | val 0.10045
  Epoch 021 - train 0.09123 | val 0.10055
  Regression -> MSE: 0.000145, MAE: 0.008444, R²: -0.0114
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.08157 | val 0.09344
  Epoch 020 - train 0.07870 | val 0.09387
  Epoch 021 - train 0.07764 | val 0.09383
  Regression -> MSE: 0.000166, MAE: 0.010391, R²: -0.0036
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08366 | val 0.08602
  Epoch 020 - train 0.08356 | val 0.08682
  Epoch 021 - train 0.08453 | val 0.08684
  Regression -> MSE: 0.000090, MAE: 0.007289, R²: -0.0522
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.08656 | val 0.09069
  Epoch 020 - train 0.08228 | val 0.09144
  Epoch 021 - train 0.08047 | val 0.09139
  Regression -> MSE: 0.000214, MAE: 0.011053, R²: -0.0111
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08194 | val 0.07134
  Epoch 020 - train 0.08401 | val 0.07247
  Epoch 021 - train 0.07728 | val 0.07237
  Regression -> MSE: 0.000101, MAE: 0.008222, R²: -0.0959
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.08825 | val 0.06121
  Epoch 020 - train 0.08387 | val 0.07017
  Epoch 021 - train 0.07842 | val 0.07092
  Regression -> MSE: 0.000108, MAE: 0.008957, R²: -0.0477
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.08092 | val 0.07079
  Epoch 020 - train 0.09077 | val 0.07169
  Epoch 021 - train 0.08631 | val 0.07151
  Regression -> MSE: 0.000232, MAE: 0.012577, R²: -0.0041
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07855 | val 0.10058
  Epoch 020 - train 0.08325 | val 0.10756
  Epoch 021 - train 0.08230 | val 0.10691
  Regression -> MSE: 0.000173, MAE: 0.007845, R²: -0.0383
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08262 | val 0.06412
  Epoch 020 - train 0.08802 | val 0.06729
  Epoch 021 - train 0.08662 | val 0.06747
  Regression -> MSE: 0.000237, MAE: 0.011883, R²: -0.0028
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.08626 | val 0.11271
  Epoch 020 - train 0.08561 | val 0.11195
  Epoch 021 - train 0.08525 | val 0.11196
  Regression -> MSE: 0.000230, MAE: 0.009851, R²: 0.0005
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.08525 | val 0.08991
  Epoch 020 - train 0.07624 | val 0.08760
  Epoch 021 - train 0.08198 | val 0.08758
  Regression -> MSE: 0.000138, MAE: 0.008313, R²: -0.0206
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08131 | val 0.09431
  Epoch 020 - train 0.07952 | val 0.09681
  Epoch 021 - train 0.08212 | val 0.09679
  Regression -> MSE: 0.000194, MAE: 0.010467, R²: -0.0283
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07574 | val 0.08131
  Epoch 020 - train 0.07093 | val 0.08098
  Epoch 021 - train 0.07251 | val 0.08117
  Regression -> MSE: 0.000264, MAE: 0.010502, R²: -0.0074
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08005 | val 0.06318
  Epoch 020 - train 0.08001 | val 0.06866
  Epoch 021 - train 0.07280 | val 0.07011
  Regression -> MSE: 0.000169, MAE: 0.010364, R²: -0.0118
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.07987 | val 0.07677
  Epoch 020 - train 0.08235 | val 0.08240
  Epoch 021 - train 0.07946 | val 0.08243
  Regression -> MSE: 0.000180, MAE: 0.010320, R²: -0.0014
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.08367 | val 0.07486
  Epoch 020 - train 0.08763 | val 0.07545
  Epoch 021 - train 0.08113 | val 0.07534
  Regression -> MSE: 0.000343, MAE: 0.011812, R²: 0.0003
  Directional -> Accuracy: 0.5672, MCC: 0.1552, F1: 0.5672

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08792 | val 0.05054
  Epoch 020 - train 0.08943 | val 0.06306
  Epoch 021 - train 0.08533 | val 0.06378
  Regression -> MSE: 0.000120, MAE: 0.008363, R²: -0.1456
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.08835 | val 0.10187
  Epoch 020 - train 0.08531 | val 0.10494
  Epoch 021 - train 0.08412 | val 0.10489
  Regression -> MSE: 0.000221, MAE: 0.011360, R²: -0.0103
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.08575 | val 0.12226
  Epoch 020 - train 0.08521 | val 0.12231
  Epoch 021 - train 0.08351 | val 0.12201
  Regression -> MSE: 0.000081, MAE: 0.007012, R²: -0.0422
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08266 | val 0.06215
  Epoch 020 - train 0.08177 | val 0.06544
  Epoch 021 - train 0.08241 | val 0.06589
  Regression -> MSE: 0.000327, MAE: 0.014878, R²: -0.0646
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07886 | val 0.04643
  Epoch 020 - train 0.08711 | val 0.04641
  Epoch 021 - train 0.07981 | val 0.04657
  Regression -> MSE: 0.000251, MAE: 0.011487, R²: -0.0287
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09182 | val 0.10096
  Epoch 020 - train 0.09128 | val 0.10125
  Epoch 021 - train 0.08759 | val 0.10172
  Regression -> MSE: 0.000084, MAE: 0.007055, R²: -0.0445
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.08525 | val 0.09207
  Epoch 020 - train 0.08248 | val 0.09675
  Epoch 021 - train 0.08375 | val 0.09661
  Regression -> MSE: 0.000307, MAE: 0.014494, R²: -0.0015
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08196 | val 0.08273
  Epoch 020 - train 0.08235 | val 0.08113
  Epoch 021 - train 0.08124 | val 0.08110
  Regression -> MSE: 0.000099, MAE: 0.007154, R²: -0.0121
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08569 | val 0.08684
  Epoch 020 - train 0.08519 | val 0.08611
  Epoch 021 - train 0.08886 | val 0.08618
  Regression -> MSE: 0.000175, MAE: 0.010125, R²: -0.0162
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08051 | val 0.09426
  Epoch 020 - train 0.08262 | val 0.10007
  Epoch 021 - train 0.07726 | val 0.10072
  Regression -> MSE: 0.000225, MAE: 0.011779, R²: -0.0072
  Directional -> Accuracy: 0.4286, MCC: -0.2777, F1: 0.5897

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07887 | val 0.08201
  Epoch 020 - train 0.07960 | val 0.08205
  Epoch 021 - train 0.08381 | val 0.08199
  Regression -> MSE: 0.000093, MAE: 0.007691, R²: -0.0085

[I 2026-02-24 01:50:00,249] Trial 97 finished with value: -0.011450351825564632 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 5.745022760006119e-06, 'weight_decay': 2.4217347466935193e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.10540306396393237, 'early_stopping_min_delta': 0.009067443377947211}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.08125 | val 0.11112
  Epoch 021 - train 0.08300 | val 0.11101
  Regression -> MSE: 0.000238, MAE: 0.012338, R²: -0.0036
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.20037 | val 0.24696
  Epoch 020 - train 0.20157 | val 0.24679
  Epoch 026 - train 0.20797 | val 0.24714
  Regression -> MSE: 0.000248, MAE: 0.012542, R²: -0.0002
  Directional -> Accuracy: 0.4935, MCC: 0.0539, F1: 0.5979

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.22263 | val 0.17857
  Epoch 020 - train 0.24278 | val 0.18829
  Epoch 021 - train 0.23865 | val 0.18915
  Regression -> MSE: 0.000711, MAE: 0.019814, R²: -0.0392
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.20008 | val 0.31349
  Epoch 020 - train 0.20167 | val 0.31504
  Epoch 021 - train 0.19205 | val 0.31473
  Regression -> MSE: 0.000310, MAE: 0.014439, R²: -0.0008
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.18373 | val 0.19422
  Epoch 020 - train 0.19427 | val 0.20042
  Epoch 021 - train 0.19058 | val 0.20027
  Regression -> MSE: 0.000352, MAE: 0.014647, R²: -0.0070
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.22947 | val 0.19349
  Epoch 020 - train 0.24613 | val 0.19560
  Epoch 021 - train 0.21227 | val 0.19387
  Regression -> MSE: 0.000203, MAE: 0.010028, R²: 0.0056
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.21586 | val 0.39252
  Epoch 020 - train 0.21816 | val 0.66495
  Epoch 021 - train 0.22160 | val 0.66962
  Regression -> MSE: 0.000565, MAE: 0.018244, R²: -0.0176
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.22160 | val 0.23604
  Epoch 020 - train 0.23171 | val 0.23592
  Epoch 021 - train 0.21763 | val 0.23625
  Regression -> MSE: 0.000248, MAE: 0.012402, R²: -0.0121
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.21393 | val 0.24219
  Epoch 020 - train 0.22339 | val 0.23670
  Epoch 021 - train 0.24321 | val 0.23454
  Regression -> MSE: 0.000616, MAE: 0.019627, R²: -0.0317
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.20663 | val 0.22733
  Epoch 020 - train 0.18602 | val 0.23167
  Epoch 021 - train 0.18238 | val 0.23206
  Regression -> MSE: 0.000393, MAE: 0.015927, R²: -0.0234
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.22655 | val 0.24701
  Epoch 020 - train 0.21187 | val 0.24642
  Epoch 021 - train 0.21597 | val 0.24639
  Regression -> MSE: 0.000249, MAE: 0.011648, R²: -0.0323
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.21147 | val 0.27863
  Epoch 020 - train 0.19669 | val 0.27117
  Epoch 030 - train 0.21211 | val 0.27164
  Regression -> MSE: 0.000320, MAE: 0.013714, R²: -0.0298
  Directional -> Accuracy: 0.5200, MCC: 0.0276, F1: 0.4545

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.20955 | val 0.22752
  Epoch 020 - train 0.22670 | val 0.23077
  Epoch 021 - train 0.22314 | val 0.23089
  Regression -> MSE: 0.000677, MAE: 0.019469, R²: 0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.21574 | val 0.20239
  Epoch 020 - train 0.20839 | val 0.24137
  Epoch 021 - train 0.21992 | val 0.24247
  Regression -> MSE: 0.000141, MAE: 0.009320, R²: -0.0185
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.20944 | val 0.27900
  Epoch 020 - train 0.20894 | val 0.29529
  Epoch 021 - train 0.20859 | val 0.29740
  Regression -> MSE: 0.000226, MAE: 0.010827, R²: -0.0041
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.20748 | val 0.39802
  Epoch 020 - train 0.22973 | val 0.40394
  Epoch 021 - train 0.21209 | val 0.40175
  Regression -> MSE: 0.000363, MAE: 0.016214, R²: -0.0023
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.23416 | val 0.20018
  Epoch 020 - train 0.22402 | val 0.20181
  Epoch 021 - train 0.22720 | val 0.20067
  Regression -> MSE: 0.000108, MAE: 0.007964, R²: 0.0004
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.20718 | val 0.32826
  Epoch 020 - train 0.20796 | val 0.34317
  Epoch 021 - train 0.20666 | val 0.34182
  Regression -> MSE: 0.000156, MAE: 0.009648, R²: -0.0002
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.20959 | val 0.20432
  Epoch 020 - train 0.21573 | val 0.20361
  Epoch 021 - train 0.22965 | val 0.20426
  Regression -> MSE: 0.000284, MAE: 0.013608, R²: -0.0441
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.20191 | val 0.25885
  Epoch 020 - train 0.18743 | val 0.25865
  Epoch 021 - train 0.20670 | val 0.25910
  Regression -> MSE: 0.000164, MAE: 0.009051, R²: -0.0970
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.22471 | val 0.28389
  Epoch 020 - train 0.21068 | val 0.28677
  Epoch 021 - train 0.22784 | val 0.28771
  Regression -> MSE: 0.000228, MAE: 0.010837, R²: -0.0083
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.21607 | val 0.23925
  Epoch 020 - train 0.21033 | val 0.25517
  Epoch 021 - train 0.21500 | val 0.25487
  Regression -> MSE: 0.000144, MAE: 0.008389, R²: -0.0067
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.20075 | val 0.22106
  Epoch 020 - train 0.19894 | val 0.21987
  Epoch 021 - train 0.19937 | val 0.21995
  Regression -> MSE: 0.000165, MAE: 0.010372, R²: -0.0001
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.21889 | val 0.21980
  Epoch 020 - train 0.22381 | val 0.22000
  Epoch 028 - train 0.22473 | val 0.21961
  Regression -> MSE: 0.000099, MAE: 0.007732, R²: -0.1598
  Directional -> Accuracy: 0.5172, MCC: 0.1339, F1: 0.3913

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.20511 | val 0.22633
  Epoch 020 - train 0.19654 | val 0.22602
  Epoch 021 - train 0.21056 | val 0.22614
  Regression -> MSE: 0.000215, MAE: 0.011044, R²: -0.0159
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.19618 | val 0.16540
  Epoch 020 - train 0.20217 | val 0.16279
  Epoch 030 - train 0.19576 | val 0.16216
  Regression -> MSE: 0.000102, MAE: 0.008428, R²: -0.1076
  Directional -> Accuracy: 0.4464, MCC: -0.1244, F1: 0.5079

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.22750 | val 0.14249
  Epoch 020 - train 0.23703 | val 0.13794
  Epoch 021 - train 0.20267 | val 0.13860
  Regression -> MSE: 0.000103, MAE: 0.008681, R²: 0.0029
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.22441 | val 0.17994
  Epoch 020 - train 0.21760 | val 0.20184
  Epoch 021 - train 0.21878 | val 0.20048
  Regression -> MSE: 0.000234, MAE: 0.012634, R²: -0.0106
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.23588 | val 0.22801
  Epoch 020 - train 0.22561 | val 0.23131
  Epoch 021 - train 0.21930 | val 0.23207
  Regression -> MSE: 0.000181, MAE: 0.007986, R²: -0.0873
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.21960 | val 0.15593
  Epoch 020 - train 0.20108 | val 0.15689
  Epoch 021 - train 0.21121 | val 0.15733
  Regression -> MSE: 0.000240, MAE: 0.011964, R²: -0.0143
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.22051 | val 0.29976
  Epoch 020 - train 0.21067 | val 0.30431
  Epoch 021 - train 0.23775 | val 0.30434
  Regression -> MSE: 0.000231, MAE: 0.009882, R²: -0.0022
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.24645 | val 0.25710
  Epoch 020 - train 0.24131 | val 0.25885
  Epoch 021 - train 0.21633 | val 0.25862
  Regression -> MSE: 0.000145, MAE: 0.008724, R²: -0.0719
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.20553 | val 0.23944
  Epoch 020 - train 0.21081 | val 0.24270
  Epoch 021 - train 0.21286 | val 0.24270
  Regression -> MSE: 0.000191, MAE: 0.010398, R²: -0.0158
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.19129 | val 0.24814
  Epoch 020 - train 0.17672 | val 0.24766
  Epoch 021 - train 0.17974 | val 0.24935
  Regression -> MSE: 0.000263, MAE: 0.010534, R²: -0.0031
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.22179 | val 0.15660
  Epoch 020 - train 0.20662 | val 0.15840
  Epoch 021 - train 0.20768 | val 0.15884
  Regression -> MSE: 0.000173, MAE: 0.010433, R²: -0.0373
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.20156 | val 0.20149
  Epoch 020 - train 0.20363 | val 0.22284
  Epoch 021 - train 0.19350 | val 0.22215
  Regression -> MSE: 0.000180, MAE: 0.010282, R²: 0.0019
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.23283 | val 0.18873
  Epoch 020 - train 0.23580 | val 0.18838
  Epoch 021 - train 0.23077 | val 0.18889
  Regression -> MSE: 0.000344, MAE: 0.011821, R²: -0.0042
  Directional -> Accuracy: 0.4627, MCC: -0.2558, F1: 0.6250

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.23527 | val 0.11753
  Epoch 020 - train 0.24200 | val 0.11985
  Epoch 021 - train 0.22921 | val 0.11988
  Regression -> MSE: 0.000124, MAE: 0.008448, R²: -0.1809
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.21588 | val 0.27974
  Epoch 020 - train 0.20647 | val 0.28924
  Epoch 021 - train 0.20154 | val 0.29091
  Regression -> MSE: 0.000219, MAE: 0.011316, R²: -0.0029
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.21677 | val 0.32018
  Epoch 020 - train 0.21721 | val 0.32133
  Epoch 021 - train 0.22530 | val 0.32167
  Regression -> MSE: 0.000092, MAE: 0.007502, R²: -0.1852
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.23674 | val 0.14105
  Epoch 020 - train 0.23222 | val 0.15132
  Epoch 021 - train 0.23843 | val 0.15256
  Regression -> MSE: 0.000310, MAE: 0.013900, R²: -0.0072
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.24468 | val 0.12071
  Epoch 020 - train 0.23732 | val 0.10875
  Epoch 030 - train 0.23731 | val 0.09979
  Regression -> MSE: 0.000264, MAE: 0.011778, R²: -0.0820
  Directional -> Accuracy: 0.5526, MCC: 0.0965, F1: 0.6047

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.21463 | val 0.23683
  Epoch 020 - train 0.21431 | val 0.23708
  Epoch 021 - train 0.21201 | val 0.23635
  Regression -> MSE: 0.000085, MAE: 0.007055, R²: -0.0523
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.21706 | val 0.23252
  Epoch 020 - train 0.22675 | val 0.23577
  Epoch 021 - train 0.21233 | val 0.23530
  Regression -> MSE: 0.000310, MAE: 0.014525, R²: -0.0093
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.22329 | val 0.19660
  Epoch 020 - train 0.20480 | val 0.19359
  Epoch 021 - train 0.20831 | val 0.19362
  Regression -> MSE: 0.000099, MAE: 0.007387, R²: -0.0039
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.23557 | val 0.23399
  Epoch 020 - train 0.23225 | val 0.28659
  Epoch 021 - train 0.23508 | val 0.29191
  Regression -> MSE: 0.000172, MAE: 0.009796, R²: -0.0012
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.19724 | val 0.21638
  Epoch 020 - train 0.20441 | val 0.22491
  Epoch 021 - train 0.21316 | val 0.22472
  Regression -> MSE: 0.000223, MAE: 0.011751, R²: -0.0016
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.23920 | val 0.23040
  Epoch 020 - train 0.21608 | val 0.24065
  Epoch 021 - train 0.22652 | val 0.24258
  Regression -> MSE: 0.000092, MAE: 0.007627, R²: 0.0001

[I 2026-02-24 01:52:07,873] Trial 98 finished with value: -0.01144036307492875 and parameters: {'feature_set': 'sentinment', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 2.3865011601873013e-06, 'weight_decay': 1.5478639381012243e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.30385316333111456, 'early_stopping_min_delta': 0.007253808158994138}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.20593 | val 0.28421
  Epoch 021 - train 0.20664 | val 0.28493
  Regression -> MSE: 0.000238, MAE: 0.012353, R²: -0.0030
  Directional -> Accuracy: 0.4590, MCC: -0.0745, F1: 0.6118

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11299 | val 0.15207
  Epoch 020 - train 0.10709 | val 0.15165
  Epoch 021 - train 0.10891 | val 0.15172
  Regression -> MSE: 0.000250, MAE: 0.012646, R²: -0.0105
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10746 | val 0.11383
  Epoch 020 - train 0.11087 | val 0.11585
  Epoch 021 - train 0.11152 | val 0.11581
  Regression -> MSE: 0.000684, MAE: 0.019353, R²: 0.0009
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12434 | val 0.18384
  Epoch 020 - train 0.11647 | val 0.18463
  Epoch 021 - train 0.12174 | val 0.18420
  Regression -> MSE: 0.000312, MAE: 0.014403, R²: -0.0057
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09802 | val 0.10068
  Epoch 020 - train 0.09210 | val 0.10326
  Epoch 021 - train 0.09294 | val 0.10289
  Regression -> MSE: 0.000373, MAE: 0.014963, R²: -0.0685
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11283 | val 0.11317
  Epoch 020 - train 0.11081 | val 0.11173
  Epoch 021 - train 0.11370 | val 0.11172
  Regression -> MSE: 0.000205, MAE: 0.010099, R²: -0.0087
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10588 | val 0.21895
  Epoch 020 - train 0.10600 | val 0.22106
  Epoch 021 - train 0.10538 | val 0.22224
  Regression -> MSE: 0.000588, MAE: 0.018733, R²: -0.0601
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11423 | val 0.15354
  Epoch 020 - train 0.12182 | val 0.15080
  Epoch 021 - train 0.11820 | val 0.15005
  Regression -> MSE: 0.000246, MAE: 0.011971, R²: -0.0039
  Directional -> Accuracy: 0.5797, MCC: 0.0432, F1: 0.2564

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11298 | val 0.15885
  Epoch 020 - train 0.11118 | val 0.15667
  Epoch 021 - train 0.11091 | val 0.15626
  Regression -> MSE: 0.000644, MAE: 0.020145, R²: -0.0775
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10760 | val 0.13702
  Epoch 020 - train 0.10530 | val 0.13698
  Epoch 021 - train 0.10432 | val 0.13697
  Regression -> MSE: 0.000390, MAE: 0.015982, R²: -0.0163
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11270 | val 0.14579
  Epoch 020 - train 0.10996 | val 0.14519
  Epoch 021 - train 0.10738 | val 0.14522
  Regression -> MSE: 0.000245, MAE: 0.011664, R²: -0.0135
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10364 | val 0.16135
  Epoch 020 - train 0.10692 | val 0.16689
  Epoch 021 - train 0.10672 | val 0.16739
  Regression -> MSE: 0.000323, MAE: 0.013601, R²: -0.0388
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11602 | val 0.13319
  Epoch 020 - train 0.11464 | val 0.13550
  Epoch 021 - train 0.11440 | val 0.13598
  Regression -> MSE: 0.000676, MAE: 0.019458, R²: 0.0015
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10909 | val 0.11665
  Epoch 020 - train 0.10858 | val 0.13114
  Epoch 021 - train 0.11084 | val 0.13147
  Regression -> MSE: 0.000140, MAE: 0.009269, R²: -0.0116
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11082 | val 0.16191
  Epoch 020 - train 0.10099 | val 0.16309
  Epoch 021 - train 0.10515 | val 0.16367
  Regression -> MSE: 0.000226, MAE: 0.010842, R²: -0.0037
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11046 | val 0.23680
  Epoch 020 - train 0.11447 | val 0.24430
  Epoch 021 - train 0.11307 | val 0.24583
  Regression -> MSE: 0.000366, MAE: 0.015944, R²: -0.0117
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12339 | val 0.11874
  Epoch 020 - train 0.12241 | val 0.12123
  Epoch 021 - train 0.11648 | val 0.12099
  Regression -> MSE: 0.000113, MAE: 0.007982, R²: -0.0431
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11064 | val 0.19330
  Epoch 020 - train 0.11192 | val 0.20165
  Epoch 021 - train 0.11030 | val 0.20209
  Regression -> MSE: 0.000156, MAE: 0.009773, R²: -0.0033
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11423 | val 0.14976
  Epoch 020 - train 0.11536 | val 0.15853
  Epoch 021 - train 0.11409 | val 0.15853
  Regression -> MSE: 0.000272, MAE: 0.013040, R²: -0.0004
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10054 | val 0.14748
  Epoch 020 - train 0.09932 | val 0.14762
  Epoch 029 - train 0.10161 | val 0.14752
  Regression -> MSE: 0.000191, MAE: 0.010145, R²: -0.2741
  Directional -> Accuracy: 0.4769, MCC: 0.0998, F1: 0.2917

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11590 | val 0.15587
  Epoch 020 - train 0.11586 | val 0.15594
  Epoch 027 - train 0.11667 | val 0.15641
  Regression -> MSE: 0.000310, MAE: 0.012825, R²: -0.3706
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12609 | val 0.15886
  Epoch 020 - train 0.12083 | val 0.17002
  Epoch 021 - train 0.12654 | val 0.16984
  Regression -> MSE: 0.000144, MAE: 0.008330, R²: -0.0017
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11171 | val 0.13259
  Epoch 020 - train 0.10878 | val 0.13289
  Epoch 021 - train 0.10729 | val 0.13292
  Regression -> MSE: 0.000176, MAE: 0.010284, R²: -0.0654
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12206 | val 0.13448
  Epoch 020 - train 0.10879 | val 0.13371
  Epoch 021 - train 0.11424 | val 0.13354
  Regression -> MSE: 0.000088, MAE: 0.007212, R²: -0.0343
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11283 | val 0.18540
  Epoch 020 - train 0.11239 | val 0.17436
  Epoch 021 - train 0.11086 | val 0.17425
  Regression -> MSE: 0.000215, MAE: 0.011405, R²: -0.0139
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10736 | val 0.11609
  Epoch 020 - train 0.10985 | val 0.11533
  Epoch 021 - train 0.10834 | val 0.11513
  Regression -> MSE: 0.000093, MAE: 0.008113, R²: -0.0059
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11561 | val 0.09430
  Epoch 020 - train 0.11549 | val 0.09843
  Epoch 021 - train 0.11078 | val 0.09919
  Regression -> MSE: 0.000114, MAE: 0.009128, R²: -0.1020
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11553 | val 0.11239
  Epoch 020 - train 0.11707 | val 0.12700
  Epoch 021 - train 0.11334 | val 0.12801
  Regression -> MSE: 0.000232, MAE: 0.012545, R²: -0.0017
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11641 | val 0.12899
  Epoch 020 - train 0.11240 | val 0.12985
  Epoch 021 - train 0.11494 | val 0.12975
  Regression -> MSE: 0.000191, MAE: 0.008184, R²: -0.1448
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11593 | val 0.09706
  Epoch 020 - train 0.11869 | val 0.09717
  Epoch 021 - train 0.12411 | val 0.09721
  Regression -> MSE: 0.000237, MAE: 0.011882, R²: -0.0034
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11237 | val 0.18165
  Epoch 020 - train 0.11058 | val 0.18084
  Epoch 021 - train 0.10964 | val 0.18079
  Regression -> MSE: 0.000233, MAE: 0.010046, R²: -0.0096
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12415 | val 0.14722
  Epoch 020 - train 0.11954 | val 0.14253
  Epoch 030 - train 0.11581 | val 0.14211
  Regression -> MSE: 0.000171, MAE: 0.009766, R²: -0.2703
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11964 | val 0.14826
  Epoch 020 - train 0.11119 | val 0.15227
  Epoch 021 - train 0.11220 | val 0.15225
  Regression -> MSE: 0.000188, MAE: 0.010510, R²: -0.0008
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11012 | val 0.12755
  Epoch 020 - train 0.10450 | val 0.12347
  Epoch 030 - train 0.10192 | val 0.12403
  Regression -> MSE: 0.000317, MAE: 0.012034, R²: -0.2115
  Directional -> Accuracy: 0.5479, MCC: 0.1851, F1: 0.4407

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11264 | val 0.09543
  Epoch 020 - train 0.11182 | val 0.09524
  Epoch 021 - train 0.10738 | val 0.09530
  Regression -> MSE: 0.000170, MAE: 0.010374, R²: -0.0170
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10233 | val 0.11873
  Epoch 020 - train 0.10249 | val 0.12833
  Epoch 021 - train 0.10266 | val 0.12810
  Regression -> MSE: 0.000181, MAE: 0.010377, R²: -0.0079
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10767 | val 0.11520
  Epoch 020 - train 0.10394 | val 0.11744
  Epoch 021 - train 0.11039 | val 0.11770
  Regression -> MSE: 0.000343, MAE: 0.011738, R²: -0.0016
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12652 | val 0.07897
  Epoch 020 - train 0.12428 | val 0.09234
  Epoch 021 - train 0.12416 | val 0.09372
  Regression -> MSE: 0.000130, MAE: 0.008573, R²: -0.2361
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11464 | val 0.15765
  Epoch 020 - train 0.11431 | val 0.16025
  Epoch 021 - train 0.11244 | val 0.16158
  Regression -> MSE: 0.000219, MAE: 0.011288, R²: -0.0003
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11544 | val 0.19241
  Epoch 020 - train 0.11323 | val 0.19489
  Epoch 021 - train 0.11329 | val 0.19508
  Regression -> MSE: 0.000093, MAE: 0.007541, R²: -0.1998
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10774 | val 0.08630
  Epoch 020 - train 0.10750 | val 0.08759
  Epoch 021 - train 0.10747 | val 0.08758
  Regression -> MSE: 0.000312, MAE: 0.014083, R²: -0.0142
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11454 | val 0.07234
  Epoch 020 - train 0.10508 | val 0.07532
  Epoch 021 - train 0.12330 | val 0.07602
  Regression -> MSE: 0.000256, MAE: 0.011465, R²: -0.0484
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10697 | val 0.15337
  Epoch 020 - train 0.10640 | val 0.15534
  Epoch 021 - train 0.10512 | val 0.15447
  Regression -> MSE: 0.000082, MAE: 0.007061, R²: -0.0191
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11253 | val 0.14276
  Epoch 020 - train 0.11199 | val 0.14232
  Epoch 030 - train 0.11110 | val 0.14756
  Regression -> MSE: 0.000305, MAE: 0.014513, R²: 0.0067
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11088 | val 0.12241
  Epoch 020 - train 0.11460 | val 0.12390
  Epoch 021 - train 0.11007 | val 0.12393
  Regression -> MSE: 0.000098, MAE: 0.007263, R²: -0.0014
  Directional -> Accuracy: 0.4773, MCC: -0.2757, F1: 0.6462

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12578 | val 0.13587
  Epoch 020 - train 0.12071 | val 0.14077
  Epoch 021 - train 0.12375 | val 0.14174
  Regression -> MSE: 0.000172, MAE: 0.009536, R²: -0.0013
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11417 | val 0.13078
  Epoch 020 - train 0.11056 | val 0.12952
  Epoch 021 - train 0.11768 | val 0.12942
  Regression -> MSE: 0.000230, MAE: 0.011918, R²: -0.0320
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10753 | val 0.12680
  Epoch 020 - train 0.11110 | val 0.12818
  Epoch 021 - train 0.10872 | val 0.12833

[I 2026-02-24 01:54:14,925] Trial 99 finished with value: -0.01154640660725636 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 2.3116668677951186e-05, 'weight_decay': 3.1665336824029925e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.16856627581022, 'early_stopping_min_delta': 0.004032987474582353}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.11208 | val 0.16189
  Epoch 021 - train 0.11405 | val 0.16213
  Regression -> MSE: 0.000236, MAE: 0.012384, R²: 0.0030
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.57036 | val 1.02344
  Epoch 020 - train 0.55135 | val 1.02649
  Regression -> MSE: 0.000243, MAE: 0.012431, R²: -0.0101
  Directional -> Accuracy: 0.3947, MCC: -0.2273, F1: 0.5577

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.53269 | val 0.48394
  Epoch 020 - train 0.54206 | val 0.48694
  Regression -> MSE: 0.000723, MAE: 0.020095, R²: -0.0361
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52336 | val 1.12998
  Epoch 020 - train 0.52524 | val 1.13434
  Regression -> MSE: 0.000316, MAE: 0.014522, R²: -0.0029
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.47588 | val 1.72605
  Epoch 020 - train 0.46192 | val 1.73886
  Regression -> MSE: 0.000377, MAE: 0.015004, R²: -0.0674
  Directional -> Accuracy: 0.4595, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.50081 | val 0.45309
  Epoch 020 - train 0.47684 | val 0.44869
  Regression -> MSE: 0.000207, MAE: 0.009819, R²: -0.0039
  Directional -> Accuracy: 0.5600, MCC: 0.1162, F1: 0.6562

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47060 | val 1.26968
  Epoch 020 - train 0.50834 | val 1.27470
  Regression -> MSE: 0.000547, MAE: 0.018029, R²: 0.0332
  Directional -> Accuracy: 0.6304, MCC: 0.2624, F1: 0.5405

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.53962 | val 0.88307
  Epoch 020 - train 0.56963 | val 0.88883
  Regression -> MSE: 0.000250, MAE: 0.011992, R²: -0.0072
  Directional -> Accuracy: 0.6029, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.49505 | val 0.47438
  Epoch 020 - train 0.49659 | val 0.52873
  Regression -> MSE: 0.000644, MAE: 0.020105, R²: -0.0548
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.49786 | val 0.72323
  Epoch 020 - train 0.50755 | val 0.72935
  Regression -> MSE: 0.000381, MAE: 0.015614, R²: -0.0213
  Directional -> Accuracy: 0.5625, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.52949 | val 0.82934
  Epoch 020 - train 0.52539 | val 0.83170
  Regression -> MSE: 0.000245, MAE: 0.011882, R²: -0.0020
  Directional -> Accuracy: 0.4638, MCC: 0.0682, F1: 0.5843

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.52625 | val 1.47944
  Epoch 020 - train 0.51996 | val 1.48376
  Regression -> MSE: 0.000313, MAE: 0.013749, R²: -0.0012
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.54190 | val 0.84441
  Epoch 020 - train 0.54507 | val 0.84476
  Regression -> MSE: 0.000689, MAE: 0.019714, R²: -0.0048
  Directional -> Accuracy: 0.5088, MCC: 0.0000, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.47691 | val 0.71998
  Epoch 020 - train 0.47492 | val 0.72801
  Regression -> MSE: 0.000140, MAE: 0.009260, R²: -0.0174
  Directional -> Accuracy: 0.4524, MCC: 0.0000, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.45236 | val 0.74378
  Epoch 020 - train 0.45148 | val 0.74253
  Regression -> MSE: 0.000232, MAE: 0.010900, R²: -0.0229
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5455

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.51709 | val 1.73901
  Epoch 020 - train 0.52754 | val 1.71534
  Regression -> MSE: 0.000380, MAE: 0.015970, R²: -0.0369
  Directional -> Accuracy: 0.5490, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.53001 | val 0.60883
  Epoch 020 - train 0.51335 | val 0.61366
  Regression -> MSE: 0.000112, MAE: 0.007967, R²: -0.0353
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.46485 | val 1.22445
  Epoch 020 - train 0.47901 | val 1.22759
  Regression -> MSE: 0.000160, MAE: 0.009958, R²: -0.0157
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.54737 | val 0.72615
  Epoch 020 - train 0.55734 | val 0.72281
  Regression -> MSE: 0.000277, MAE: 0.012999, R²: -0.0135
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.42042 | val 0.75473
  Epoch 020 - train 0.40164 | val 0.75089
  Regression -> MSE: 0.000163, MAE: 0.009215, R²: -0.0738
  Directional -> Accuracy: 0.5938, MCC: 0.1442, F1: 0.6750

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.50699 | val 1.05932
  Epoch 020 - train 0.49517 | val 1.04607
  Regression -> MSE: 0.000241, MAE: 0.010681, R²: -0.0591
  Directional -> Accuracy: 0.6486, MCC: 0.2990, F1: 0.6667

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.67649 | val 0.93215
  Epoch 020 - train 0.63597 | val 0.93755
  Regression -> MSE: 0.000159, MAE: 0.008984, R²: -0.1037
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.51992 | val 0.78903
  Epoch 020 - train 0.52129 | val 0.78779
  Regression -> MSE: 0.000168, MAE: 0.010428, R²: -0.0159
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51858 | val 0.70240
  Epoch 020 - train 0.55912 | val 0.70538
  Regression -> MSE: 0.000086, MAE: 0.007102, R²: 0.0065
  Directional -> Accuracy: 0.5439, MCC: 0.1198, F1: 0.5185

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.56908 | val 0.75750
  Epoch 020 - train 0.54971 | val 0.76573
  Regression -> MSE: 0.000216, MAE: 0.010986, R²: -0.0226
  Directional -> Accuracy: 0.5231, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.46695 | val 0.47879
  Epoch 020 - train 0.49030 | val 0.47192
  Regression -> MSE: 0.000097, MAE: 0.008062, R²: -0.0814
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.57904 | val 0.42776
  Epoch 020 - train 0.50241 | val 0.44653
  Regression -> MSE: 0.000109, MAE: 0.008943, R²: -0.0953
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.50949 | val 0.53656
  Epoch 020 - train 0.54960 | val 0.54696
  Regression -> MSE: 0.000238, MAE: 0.012877, R²: -0.0049
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.55916 | val 0.69688
  Epoch 020 - train 0.54398 | val 0.68966
  Regression -> MSE: 0.000182, MAE: 0.008007, R²: -0.0737
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.59989 | val 0.41513
  Epoch 020 - train 0.56618 | val 0.49998
  Regression -> MSE: 0.000245, MAE: 0.012234, R²: -0.0126
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.53595 | val 1.14761
  Epoch 020 - train 0.52919 | val 1.14869
  Regression -> MSE: 0.000236, MAE: 0.010160, R²: -0.0023
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.53659 | val 0.66281
  Epoch 020 - train 0.56364 | val 0.66865
  Regression -> MSE: 0.000138, MAE: 0.008336, R²: -0.0018
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.49783 | val 0.77787
  Epoch 020 - train 0.49646 | val 0.77511
  Regression -> MSE: 0.000191, MAE: 0.010389, R²: -0.0409
  Directional -> Accuracy: 0.4694, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.43935 | val 0.74080
  Epoch 020 - train 0.47559 | val 0.74924
  Regression -> MSE: 0.000269, MAE: 0.010639, R²: -0.0122
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.46351 | val 0.61098
  Epoch 020 - train 0.47444 | val 0.60968
  Regression -> MSE: 0.000188, MAE: 0.010598, R²: -0.0237
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.52508 | val 0.53089
  Epoch 020 - train 0.51425 | val 0.53190
  Regression -> MSE: 0.000358, MAE: 0.011930, R²: -0.0302
  Directional -> Accuracy: 0.5758, MCC: 0.0000, F1: 0.7308

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.56339 | val 0.26428
  Epoch 020 - train 0.56563 | val 0.26602
  Regression -> MSE: 0.000116, MAE: 0.008415, R²: -0.1017
  Directional -> Accuracy: 0.5238, MCC: 0.0000, F1: 0.6875

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.51759 | val 1.03975
  Epoch 020 - train 0.52388 | val 1.03074
  Regression -> MSE: 0.000226, MAE: 0.011474, R²: -0.0259
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.53626 | val 1.38560
  Epoch 020 - train 0.53720 | val 1.40770
  Regression -> MSE: 0.000077, MAE: 0.006835, R²: -0.0380
  Directional -> Accuracy: 0.6087, MCC: 0.0475, F1: 0.7500

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.54192 | val 0.38799
  Epoch 020 - train 0.57595 | val 0.41208
  Regression -> MSE: 0.000348, MAE: 0.015606, R²: -0.1164
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.51276 | val 0.72111
  Epoch 020 - train 0.50454 | val 0.71968
  Regression -> MSE: 0.000079, MAE: 0.006948, R²: -0.0061
  Directional -> Accuracy: 0.4865, MCC: 0.0000, F1: 0.6545

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.51918 | val 0.66587
  Epoch 020 - train 0.54555 | val 0.66325
  Regression -> MSE: 0.000314, MAE: 0.014600, R²: -0.0440
  Directional -> Accuracy: 0.4444, MCC: -0.1107, F1: 0.4444

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49326 | val 0.60467
  Epoch 020 - train 0.53282 | val 0.60575
  Regression -> MSE: 0.000108, MAE: 0.007322, R²: -0.0576
  Directional -> Accuracy: 0.5714, MCC: 0.0589, F1: 0.7000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56317 | val 0.84180
  Epoch 020 - train 0.56160 | val 0.86035
  Regression -> MSE: 0.000176, MAE: 0.009845, R²: -0.0021
  Directional -> Accuracy: 0.3542, MCC: -0.1883, F1: 0.5231

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.49735 | val 1.06713
  Epoch 020 - train 0.47497 | val 1.06210
  Regression -> MSE: 0.000231, MAE: 0.011927, R²: -0.0219
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.53197 | val 0.85075
  Epoch 020 - train 0.52852 | val 0.84613
  Regression -> MSE: 0.000094, MAE: 0.007736, R²: 0.0024
  Directional -> Accuracy: 0.5714, MCC: 0.1992, F1: 0.2500

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.54383 | val 1.11813
  Epoch 020 - train 0.51971 | val 1.11191
  Regression -> MSE: 0.000167, MAE: 0.010411, R²: 0.0004
  Directional -> Accuracy: 0.5094, MCC: 0.0000, F1: 0.6750

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.48220 | val 0.90258
  Epoch 020 - train 0.49137 | val 0.90765
  Regression -> MSE: 0.000123, MAE: 0.009122, R²: -0.0474
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.49742 | val 1.09260

[I 2026-02-24 01:57:20,073] Trial 100 finished with value: -0.011505929688493571 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 3.4132153628621248e-06, 'weight_decay': 1.8788378861429911e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 1.9768663356456773, 'early_stopping_min_delta': 0.006274176637674242}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.48459 | val 1.09737
  Regression -> MSE: 0.000245, MAE: 0.012464, R²: -0.0183
  Directional -> Accuracy: 0.5167, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.22966 | val 0.26567
  Epoch 020 - train 0.22799 | val 0.26655
  Epoch 025 - train 0.23026 | val 0.26702
  Regression -> MSE: 0.000262, MAE: 0.013058, R²: -0.0573
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.22903 | val 0.18842
  Epoch 020 - train 0.22785 | val 0.19325
  Epoch 021 - train 0.22636 | val 0.19452
  Regression -> MSE: 0.000715, MAE: 0.019891, R²: -0.0450
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.23884 | val 0.32862
  Epoch 020 - train 0.22367 | val 0.34773
  Epoch 021 - train 0.22144 | val 0.34764
  Regression -> MSE: 0.000310, MAE: 0.014405, R²: 0.0002
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.19727 | val 0.19753
  Epoch 020 - train 0.19330 | val 0.20256
  Epoch 021 - train 0.19371 | val 0.20071
  Regression -> MSE: 0.000372, MAE: 0.014943, R²: -0.0654
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.21398 | val 0.27199
  Epoch 020 - train 0.21220 | val 0.38319
  Epoch 021 - train 0.22457 | val 0.38083
  Regression -> MSE: 0.000203, MAE: 0.010082, R²: 0.0048
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.23267 | val 0.37583
  Epoch 020 - train 0.23054 | val 0.38630
  Epoch 021 - train 0.24327 | val 0.38677
  Regression -> MSE: 0.000556, MAE: 0.018146, R²: -0.0013
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.22037 | val 0.24113
  Epoch 020 - train 0.21808 | val 0.24209
  Epoch 021 - train 0.22121 | val 0.24197
  Regression -> MSE: 0.000247, MAE: 0.011922, R²: -0.0063
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.22286 | val 0.25671
  Epoch 020 - train 0.21797 | val 0.36451
  Epoch 021 - train 0.21400 | val 0.37639
  Regression -> MSE: 0.000608, MAE: 0.019394, R²: -0.0169
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.21175 | val 0.24926
  Epoch 020 - train 0.21651 | val 0.25440
  Epoch 021 - train 0.20712 | val 0.25491
  Regression -> MSE: 0.000387, MAE: 0.016146, R²: -0.0089
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.24470 | val 0.50021
  Epoch 020 - train 0.23899 | val 0.52024
  Epoch 021 - train 0.25344 | val 0.52028
  Regression -> MSE: 0.000244, MAE: 0.012195, R²: -0.0094
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.20654 | val 0.27508
  Epoch 020 - train 0.20591 | val 0.26965
  Epoch 030 - train 0.19574 | val 0.26945
  Regression -> MSE: 0.000342, MAE: 0.013728, R²: -0.0985
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.22231 | val 0.24906
  Epoch 020 - train 0.22309 | val 0.25921
  Epoch 021 - train 0.21959 | val 0.25858
  Regression -> MSE: 0.000678, MAE: 0.019513, R²: -0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.21388 | val 0.19759
  Epoch 020 - train 0.22276 | val 0.24910
  Epoch 021 - train 0.22652 | val 0.25025
  Regression -> MSE: 0.000140, MAE: 0.009301, R²: -0.0154
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.22156 | val 0.26801
  Epoch 020 - train 0.21765 | val 0.26653
  Epoch 021 - train 0.22564 | val 0.26765
  Regression -> MSE: 0.000226, MAE: 0.010876, R²: -0.0057
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.24577 | val 0.41046
  Epoch 020 - train 0.23275 | val 0.44069
  Epoch 021 - train 0.23157 | val 0.44290
  Regression -> MSE: 0.000364, MAE: 0.016027, R²: -0.0058
  Directional -> Accuracy: 0.3846, MCC: -0.2254, F1: 0.5000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.24565 | val 0.21946
  Epoch 020 - train 0.23396 | val 0.22338
  Epoch 021 - train 0.24302 | val 0.22287
  Regression -> MSE: 0.000109, MAE: 0.008134, R²: -0.0105
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.23145 | val 0.34110
  Epoch 020 - train 0.22012 | val 0.37504
  Epoch 021 - train 0.21017 | val 0.37204
  Regression -> MSE: 0.000157, MAE: 0.009637, R²: -0.0042
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.21091 | val 0.22416
  Epoch 020 - train 0.22701 | val 0.23118
  Epoch 021 - train 0.23006 | val 0.22958
  Regression -> MSE: 0.000272, MAE: 0.012992, R²: 0.0012
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.20479 | val 0.27599
  Epoch 020 - train 0.20283 | val 0.27978
  Epoch 021 - train 0.20709 | val 0.28006
  Regression -> MSE: 0.000157, MAE: 0.008828, R²: -0.0488
  Directional -> Accuracy: 0.5231, MCC: 0.0548, F1: 0.5507

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.23959 | val 0.28184
  Epoch 020 - train 0.21619 | val 0.28401
  Epoch 021 - train 0.21885 | val 0.28435
  Regression -> MSE: 0.000228, MAE: 0.010839, R²: -0.0098
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.21028 | val 0.26011
  Epoch 020 - train 0.22803 | val 0.28151
  Epoch 021 - train 0.21900 | val 0.27971
  Regression -> MSE: 0.000144, MAE: 0.008368, R²: -0.0037
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.20883 | val 0.24042
  Epoch 020 - train 0.20754 | val 0.24240
  Epoch 021 - train 0.19471 | val 0.24195
  Regression -> MSE: 0.000165, MAE: 0.010478, R²: -0.0010
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.21915 | val 0.22951
  Epoch 020 - train 0.22866 | val 0.23006
  Epoch 021 - train 0.21109 | val 0.22987
  Regression -> MSE: 0.000086, MAE: 0.007080, R²: -0.0056
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.21820 | val 0.51894
  Epoch 020 - train 0.21976 | val 0.54292
  Epoch 021 - train 0.22156 | val 0.55688
  Regression -> MSE: 0.000213, MAE: 0.011199, R²: -0.0034
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.20831 | val 0.18592
  Epoch 020 - train 0.20297 | val 0.18720
  Epoch 021 - train 0.21178 | val 0.18733
  Regression -> MSE: 0.000093, MAE: 0.008104, R²: -0.0135
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.22659 | val 0.15251
  Epoch 020 - train 0.23722 | val 0.15480
  Epoch 021 - train 0.23536 | val 0.15601
  Regression -> MSE: 0.000110, MAE: 0.009034, R²: -0.0664
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.22079 | val 0.18798
  Epoch 020 - train 0.22212 | val 0.19692
  Epoch 021 - train 0.21292 | val 0.19684
  Regression -> MSE: 0.000235, MAE: 0.012689, R²: -0.0164
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.22254 | val 0.23556
  Epoch 020 - train 0.21491 | val 0.23899
  Epoch 021 - train 0.20682 | val 0.23816
  Regression -> MSE: 0.000176, MAE: 0.007898, R²: -0.0602
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.24634 | val 0.16262
  Epoch 020 - train 0.25819 | val 0.18679
  Epoch 021 - train 0.25912 | val 0.18860
  Regression -> MSE: 0.000240, MAE: 0.011943, R²: -0.0135
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.21347 | val 0.31124
  Epoch 020 - train 0.22026 | val 0.31493
  Epoch 021 - train 0.21654 | val 0.31513
  Regression -> MSE: 0.000230, MAE: 0.009865, R²: 0.0034
  Directional -> Accuracy: 0.5581, MCC: 0.1463, F1: 0.6415

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.23955 | val 0.25507
  Epoch 020 - train 0.22964 | val 0.29244
  Epoch 021 - train 0.20229 | val 0.29392
  Regression -> MSE: 0.000141, MAE: 0.008430, R²: -0.0412
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.23982 | val 0.25401
  Epoch 020 - train 0.24221 | val 0.25901
  Epoch 021 - train 0.24073 | val 0.25913
  Regression -> MSE: 0.000192, MAE: 0.010410, R²: -0.0202
  Directional -> Accuracy: 0.5200, MCC: -0.0401, F1: 0.6667

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.20762 | val 0.27201
  Epoch 020 - train 0.21219 | val 0.27334
  Epoch 021 - train 0.19848 | val 0.27529
  Regression -> MSE: 0.000263, MAE: 0.010520, R²: -0.0043
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.24064 | val 0.16029
  Epoch 020 - train 0.22346 | val 0.18634
  Epoch 021 - train 0.20151 | val 0.19412
  Regression -> MSE: 0.000167, MAE: 0.010366, R²: -0.0001
  Directional -> Accuracy: 0.5263, MCC: 0.0555, F1: 0.5909

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.21224 | val 0.19931
  Epoch 020 - train 0.20048 | val 0.20880
  Epoch 021 - train 0.20163 | val 0.20926
  Regression -> MSE: 0.000180, MAE: 0.010242, R²: 0.0013
  Directional -> Accuracy: 0.5682, MCC: 0.1394, F1: 0.3448

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.22453 | val 0.18468
  Epoch 020 - train 0.20869 | val 0.18420
  Epoch 021 - train 0.20954 | val 0.18422
  Regression -> MSE: 0.000344, MAE: 0.011969, R²: -0.0028
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.24862 | val 0.12477
  Epoch 020 - train 0.23279 | val 0.12971
  Epoch 021 - train 0.24297 | val 0.13053
  Regression -> MSE: 0.000113, MAE: 0.008319, R²: -0.0718
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.24132 | val 0.29235
  Epoch 020 - train 0.22920 | val 0.29303
  Epoch 021 - train 0.24662 | val 0.29246
  Regression -> MSE: 0.000221, MAE: 0.011396, R²: -0.0135
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.20398 | val 0.34471
  Epoch 020 - train 0.20844 | val 0.36701
  Epoch 021 - train 0.20156 | val 0.36715
  Regression -> MSE: 0.000091, MAE: 0.007449, R²: -0.1673
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.21696 | val 0.15902
  Epoch 020 - train 0.23070 | val 0.16355
  Epoch 021 - train 0.21307 | val 0.16394
  Regression -> MSE: 0.000328, MAE: 0.014912, R²: -0.0677
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.23530 | val 0.11243
  Epoch 020 - train 0.24460 | val 0.11060
  Epoch 021 - train 0.22978 | val 0.11063
  Regression -> MSE: 0.000246, MAE: 0.011572, R²: -0.0072
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.23162 | val 0.25480
  Epoch 020 - train 0.22245 | val 0.25585
  Epoch 021 - train 0.23120 | val 0.25556
  Regression -> MSE: 0.000087, MAE: 0.007082, R²: -0.0709
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.23300 | val 0.24319
  Epoch 020 - train 0.22790 | val 0.24230
  Epoch 021 - train 0.23777 | val 0.24241
  Regression -> MSE: 0.000311, MAE: 0.014538, R²: -0.0147
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.23501 | val 0.22406
  Epoch 020 - train 0.22030 | val 0.22174
  Epoch 021 - train 0.20365 | val 0.22114
  Regression -> MSE: 0.000100, MAE: 0.007115, R²: -0.0231
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.21358 | val 0.23434
  Epoch 020 - train 0.23458 | val 0.23397
  Epoch 021 - train 0.22488 | val 0.23436
  Regression -> MSE: 0.000173, MAE: 0.009843, R²: -0.0038
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.19264 | val 0.22886
  Epoch 020 - train 0.18829 | val 0.22888
  Epoch 021 - train 0.18742 | val 0.22798
  Regression -> MSE: 0.000228, MAE: 0.011823, R²: -0.0205
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.22603 | val 0.21946
  Epoch 020 - train 0.23076 | val 0.22166
  Epoch 021 - train 0.23515 | val 0.22059
  Regression -> MSE: 0.000095, MAE: 0.007814, R²: -0.0274
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...


[I 2026-02-24 01:59:26,079] Trial 101 finished with value: -0.011443567097396428 and parameters: {'feature_set': 'sentinment', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 2.0582423508999998e-06, 'weight_decay': 1.4917729413046153e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.31834374327564546, 'early_stopping_min_delta': 0.007254137832698904}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.23189 | val 0.32826
  Epoch 021 - train 0.22172 | val 0.32920
  Regression -> MSE: 0.000237, MAE: 0.012429, R²: -0.0000
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10778 | val 0.12824
  Epoch 020 - train 0.10487 | val 0.12904
  Epoch 021 - train 0.09964 | val 0.12935
  Regression -> MSE: 0.000259, MAE: 0.012959, R²: -0.0442
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10341 | val 0.09193
  Epoch 020 - train 0.09474 | val 0.08937
  Epoch 021 - train 0.09960 | val 0.08964
  Regression -> MSE: 0.000686, MAE: 0.019375, R²: -0.0027
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10234 | val 0.14960
  Epoch 020 - train 0.10191 | val 0.15047
  Epoch 021 - train 0.10162 | val 0.15042
  Regression -> MSE: 0.000311, MAE: 0.014406, R²: -0.0032
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09151 | val 0.14797
  Epoch 020 - train 0.08812 | val 0.13042
  Epoch 021 - train 0.09281 | val 0.12819
  Regression -> MSE: 0.000352, MAE: 0.014598, R²: -0.0074
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09591 | val 0.09686
  Epoch 020 - train 0.09826 | val 0.09735
  Epoch 021 - train 0.09456 | val 0.09732
  Regression -> MSE: 0.000206, MAE: 0.010365, R²: -0.0117
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09891 | val 0.17130
  Epoch 020 - train 0.09473 | val 0.16996
  Epoch 021 - train 0.09543 | val 0.16989
  Regression -> MSE: 0.000579, MAE: 0.018557, R²: -0.0427
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10057 | val 0.11432
  Epoch 020 - train 0.10064 | val 0.11290
  Epoch 021 - train 0.09648 | val 0.11288
  Regression -> MSE: 0.000246, MAE: 0.012056, R²: -0.0017
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10728 | val 0.12580
  Epoch 020 - train 0.11858 | val 0.16044
  Epoch 021 - train 0.10336 | val 0.16450
  Regression -> MSE: 0.000626, MAE: 0.019814, R²: -0.0472
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10579 | val 0.10979
  Epoch 020 - train 0.09762 | val 0.11344
  Epoch 021 - train 0.09868 | val 0.11326
  Regression -> MSE: 0.000409, MAE: 0.016210, R²: -0.0650
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10367 | val 0.12162
  Epoch 020 - train 0.09702 | val 0.12070
  Epoch 021 - train 0.09930 | val 0.12070
  Regression -> MSE: 0.000243, MAE: 0.012189, R²: -0.0080
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10563 | val 0.16084
  Epoch 020 - train 0.09831 | val 0.19259
  Epoch 021 - train 0.09970 | val 0.19273
  Regression -> MSE: 0.000311, MAE: 0.013660, R²: 0.0001
  Directional -> Accuracy: 0.5000, MCC: 0.0602, F1: 0.6032

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10776 | val 0.11084
  Epoch 020 - train 0.10428 | val 0.11207
  Epoch 021 - train 0.09854 | val 0.11240
  Regression -> MSE: 0.000678, MAE: 0.019452, R²: -0.0004
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11168 | val 0.09954
  Epoch 020 - train 0.11156 | val 0.11314
  Epoch 021 - train 0.10993 | val 0.11552
  Regression -> MSE: 0.000139, MAE: 0.009203, R²: -0.0056
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09504 | val 0.11540
  Epoch 020 - train 0.09126 | val 0.11515
  Epoch 021 - train 0.09110 | val 0.11505
  Regression -> MSE: 0.000228, MAE: 0.010756, R²: -0.0117
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11095 | val 0.18568
  Epoch 020 - train 0.09773 | val 0.19682
  Epoch 021 - train 0.10721 | val 0.19670
  Regression -> MSE: 0.000362, MAE: 0.016103, R²: 0.0001
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10421 | val 0.09218
  Epoch 020 - train 0.09887 | val 0.09198
  Epoch 028 - train 0.10178 | val 0.09228
  Regression -> MSE: 0.000106, MAE: 0.007938, R²: 0.0202
  Directional -> Accuracy: 0.6000, MCC: 0.2152, F1: 0.5882

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10264 | val 0.16944
  Epoch 020 - train 0.10142 | val 0.18591
  Epoch 021 - train 0.10129 | val 0.18577
  Regression -> MSE: 0.000156, MAE: 0.009673, R²: -0.0011
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11191 | val 0.11647
  Epoch 020 - train 0.10298 | val 0.11625
  Epoch 021 - train 0.10654 | val 0.11536
  Regression -> MSE: 0.000279, MAE: 0.013368, R²: -0.0258
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09339 | val 0.14282
  Epoch 020 - train 0.09718 | val 0.14423
  Epoch 021 - train 0.09859 | val 0.14304
  Regression -> MSE: 0.000154, MAE: 0.008756, R²: -0.0306
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10520 | val 0.14220
  Epoch 020 - train 0.10065 | val 0.14426
  Epoch 021 - train 0.10095 | val 0.14557
  Regression -> MSE: 0.000254, MAE: 0.011404, R²: -0.1242
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10434 | val 0.12088
  Epoch 020 - train 0.10262 | val 0.13046
  Epoch 021 - train 0.10353 | val 0.12986
  Regression -> MSE: 0.000153, MAE: 0.008840, R²: -0.0698
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09155 | val 0.11024
  Epoch 020 - train 0.09373 | val 0.11120
  Epoch 021 - train 0.08725 | val 0.11131
  Regression -> MSE: 0.000181, MAE: 0.010328, R²: -0.0956
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10260 | val 0.11127
  Epoch 020 - train 0.09956 | val 0.11114
  Epoch 021 - train 0.09818 | val 0.11119
  Regression -> MSE: 0.000086, MAE: 0.007066, R²: -0.0049
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10523 | val 0.11906
  Epoch 020 - train 0.10450 | val 0.11602
  Epoch 021 - train 0.09922 | val 0.11546
  Regression -> MSE: 0.000212, MAE: 0.011153, R²: -0.0001
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10799 | val 0.08236
  Epoch 020 - train 0.09614 | val 0.08343
  Epoch 021 - train 0.09757 | val 0.08330
  Regression -> MSE: 0.000092, MAE: 0.008083, R²: -0.0024
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10392 | val 0.07430
  Epoch 020 - train 0.11053 | val 0.07480
  Epoch 021 - train 0.10820 | val 0.07476
  Regression -> MSE: 0.000108, MAE: 0.008955, R²: -0.0462
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10277 | val 0.09054
  Epoch 020 - train 0.10407 | val 0.10291
  Epoch 021 - train 0.10253 | val 0.10312
  Regression -> MSE: 0.000235, MAE: 0.012684, R²: -0.0146
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09685 | val 0.10724
  Epoch 020 - train 0.09774 | val 0.10684
  Epoch 021 - train 0.09776 | val 0.10679
  Regression -> MSE: 0.000179, MAE: 0.007921, R²: -0.0727
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11299 | val 0.07961
  Epoch 020 - train 0.10212 | val 0.08254
  Epoch 021 - train 0.10311 | val 0.08290
  Regression -> MSE: 0.000240, MAE: 0.011975, R²: -0.0162
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10294 | val 0.14914
  Epoch 020 - train 0.10806 | val 0.16916
  Epoch 021 - train 0.11178 | val 0.16904
  Regression -> MSE: 0.000233, MAE: 0.010037, R²: -0.0113
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11479 | val 0.10384
  Epoch 020 - train 0.10539 | val 0.11971
  Epoch 021 - train 0.11886 | val 0.11992
  Regression -> MSE: 0.000135, MAE: 0.008169, R²: -0.0023
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10672 | val 0.11621
  Epoch 020 - train 0.10379 | val 0.11598
  Epoch 021 - train 0.09937 | val 0.11610
  Regression -> MSE: 0.000200, MAE: 0.010705, R²: -0.0621
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09707 | val 0.10471
  Epoch 020 - train 0.09065 | val 0.10360
  Epoch 025 - train 0.09432 | val 0.10312
  Regression -> MSE: 0.000267, MAE: 0.010953, R²: -0.0179
  Directional -> Accuracy: 0.5479, MCC: 0.1054, F1: 0.5600

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11381 | val 0.07987
  Epoch 020 - train 0.10150 | val 0.08204
  Epoch 021 - train 0.09041 | val 0.08236
  Regression -> MSE: 0.000167, MAE: 0.010362, R²: -0.0006
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09871 | val 0.09912
  Epoch 020 - train 0.09885 | val 0.10007
  Epoch 021 - train 0.09589 | val 0.09977
  Regression -> MSE: 0.000183, MAE: 0.010456, R²: -0.0183
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09948 | val 0.09372
  Epoch 020 - train 0.09480 | val 0.09466
  Epoch 021 - train 0.09660 | val 0.09478
  Regression -> MSE: 0.000342, MAE: 0.011897, R²: 0.0017
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10604 | val 0.06302
  Epoch 020 - train 0.10940 | val 0.06374
  Epoch 021 - train 0.11036 | val 0.06374
  Regression -> MSE: 0.000111, MAE: 0.008297, R²: -0.0539
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10769 | val 0.12249
  Epoch 020 - train 0.10000 | val 0.12523
  Epoch 021 - train 0.10593 | val 0.12519
  Regression -> MSE: 0.000223, MAE: 0.011427, R²: -0.0222
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10198 | val 0.15665
  Epoch 020 - train 0.10327 | val 0.16207
  Epoch 021 - train 0.10960 | val 0.16096
  Regression -> MSE: 0.000084, MAE: 0.007175, R²: -0.0874
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10056 | val 0.08430
  Epoch 020 - train 0.09933 | val 0.09695
  Epoch 021 - train 0.10256 | val 0.09808
  Regression -> MSE: 0.000342, MAE: 0.015412, R²: -0.1109
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10091 | val 0.05931
  Epoch 020 - train 0.11304 | val 0.06589
  Epoch 021 - train 0.10483 | val 0.06709
  Regression -> MSE: 0.000251, MAE: 0.011493, R²: -0.0275
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09614 | val 0.11137
  Epoch 020 - train 0.09524 | val 0.11205
  Epoch 021 - train 0.10043 | val 0.11218
  Regression -> MSE: 0.000082, MAE: 0.007058, R²: -0.0167
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10502 | val 0.11578
  Epoch 020 - train 0.09656 | val 0.11514
  Epoch 021 - train 0.10019 | val 0.11483
  Regression -> MSE: 0.000307, MAE: 0.014477, R²: 0.0007
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10165 | val 0.09639
  Epoch 020 - train 0.09807 | val 0.09527
  Epoch 021 - train 0.10091 | val 0.09529
  Regression -> MSE: 0.000098, MAE: 0.007374, R²: -0.0027
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10737 | val 0.10796
  Epoch 020 - train 0.10506 | val 0.10943
  Epoch 021 - train 0.10242 | val 0.10983
  Regression -> MSE: 0.000172, MAE: 0.009526, R²: -0.0036
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10104 | val 0.10958
  Epoch 020 - train 0.09866 | val 0.11230
  Epoch 021 - train 0.09385 | val 0.11090
  Regression -> MSE: 0.000223, MAE: 0.011745, R²: -0.0005
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10808 | val 0.10139
  Epoch 020 - train 0.10572 | val 0.10133
  Epoch 021 - train 0.10168 | val 0.10153
  Regression -> MSE: 0.000092, MAE: 0.007641, R²: -0.0001

[I 2026-02-24 02:01:28,685] Trial 102 finished with value: -0.011474191461652714 and parameters: {'feature_set': 'sentinment', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 1.2815809389874686e-05, 'weight_decay': 8.872498622202913e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.13467035021585466, 'early_stopping_min_delta': 0.006869665817581153}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.09941 | val 0.13064
  Epoch 021 - train 0.10715 | val 0.13065
  Regression -> MSE: 0.000238, MAE: 0.012373, R²: -0.0036
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14306 | val 0.18953
  Epoch 020 - train 0.14211 | val 0.18605
  Epoch 021 - train 0.14189 | val 0.18523
  Regression -> MSE: 0.000253, MAE: 0.012784, R²: -0.0234
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13526 | val 0.12970
  Epoch 020 - train 0.14320 | val 0.16741
  Epoch 021 - train 0.13293 | val 0.17323
  Regression -> MSE: 0.000694, MAE: 0.019509, R²: -0.0144
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15124 | val 0.22788
  Epoch 020 - train 0.15080 | val 0.23137
  Epoch 021 - train 0.14766 | val 0.23118
  Regression -> MSE: 0.000318, MAE: 0.014481, R²: -0.0238
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12530 | val 0.12808
  Epoch 020 - train 0.11850 | val 0.14405
  Epoch 021 - train 0.11999 | val 0.14361
  Regression -> MSE: 0.000363, MAE: 0.014807, R²: -0.0391
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13726 | val 0.13866
  Epoch 020 - train 0.14815 | val 0.13813
  Epoch 021 - train 0.13306 | val 0.13752
  Regression -> MSE: 0.000203, MAE: 0.010044, R²: 0.0026
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15395 | val 0.26160
  Epoch 020 - train 0.13655 | val 0.25981
  Epoch 021 - train 0.12779 | val 0.25990
  Regression -> MSE: 0.000568, MAE: 0.018327, R²: -0.0233
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14887 | val 0.17540
  Epoch 020 - train 0.14463 | val 0.17401
  Epoch 021 - train 0.14673 | val 0.17415
  Regression -> MSE: 0.000249, MAE: 0.011932, R²: -0.0155
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15086 | val 0.16771
  Epoch 020 - train 0.13218 | val 0.20763
  Epoch 021 - train 0.13920 | val 0.21468
  Regression -> MSE: 0.000602, MAE: 0.019266, R²: -0.0079
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15165 | val 0.18186
  Epoch 020 - train 0.14998 | val 0.18037
  Epoch 021 - train 0.13299 | val 0.18020
  Regression -> MSE: 0.000383, MAE: 0.016183, R²: 0.0007
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14510 | val 0.18232
  Epoch 020 - train 0.13528 | val 0.19223
  Epoch 021 - train 0.13688 | val 0.19180
  Regression -> MSE: 0.000244, MAE: 0.011662, R²: -0.0103
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14112 | val 0.20803
  Epoch 020 - train 0.12871 | val 0.22940
  Epoch 021 - train 0.13098 | val 0.22907
  Regression -> MSE: 0.000312, MAE: 0.013643, R²: -0.0026
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15964 | val 0.16835
  Epoch 020 - train 0.13769 | val 0.17187
  Epoch 021 - train 0.14799 | val 0.17183
  Regression -> MSE: 0.000676, MAE: 0.019494, R²: 0.0013
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14117 | val 0.14689
  Epoch 020 - train 0.13761 | val 0.17950
  Epoch 021 - train 0.13667 | val 0.18031
  Regression -> MSE: 0.000139, MAE: 0.009247, R²: -0.0084
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12899 | val 0.17905
  Epoch 020 - train 0.12706 | val 0.17843
  Epoch 030 - train 0.12927 | val 0.17696
  Regression -> MSE: 0.000220, MAE: 0.010538, R²: 0.0231
  Directional -> Accuracy: 0.6230, MCC: 0.2470, F1: 0.6567

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15521 | val 0.29654
  Epoch 020 - train 0.14667 | val 0.29671
  Epoch 021 - train 0.13669 | val 0.29496
  Regression -> MSE: 0.000363, MAE: 0.016246, R²: -0.0037
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15317 | val 0.15307
  Epoch 020 - train 0.14774 | val 0.14953
  Epoch 021 - train 0.14146 | val 0.14986
  Regression -> MSE: 0.000108, MAE: 0.007987, R²: 0.0028
  Directional -> Accuracy: 0.6286, MCC: 0.2674, F1: 0.7292

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14650 | val 0.24664
  Epoch 020 - train 0.13273 | val 0.27252
  Epoch 021 - train 0.14026 | val 0.27417
  Regression -> MSE: 0.000158, MAE: 0.009875, R²: -0.0105
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15336 | val 0.14624
  Epoch 020 - train 0.13811 | val 0.14613
  Epoch 021 - train 0.15173 | val 0.14719
  Regression -> MSE: 0.000282, MAE: 0.013521, R²: -0.0369
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13996 | val 0.18989
  Epoch 020 - train 0.13214 | val 0.18781
  Epoch 021 - train 0.12807 | val 0.18754
  Regression -> MSE: 0.000166, MAE: 0.009092, R²: -0.1120
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15024 | val 0.20442
  Epoch 020 - train 0.14259 | val 0.20354
  Epoch 021 - train 0.14303 | val 0.20261
  Regression -> MSE: 0.000230, MAE: 0.010908, R²: -0.0185
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14835 | val 0.17391
  Epoch 020 - train 0.13310 | val 0.17406
  Epoch 021 - train 0.13449 | val 0.17374
  Regression -> MSE: 0.000144, MAE: 0.008320, R²: -0.0020
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13340 | val 0.16477
  Epoch 020 - train 0.13252 | val 0.17078
  Epoch 021 - train 0.13354 | val 0.17040
  Regression -> MSE: 0.000170, MAE: 0.010261, R²: -0.0286
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15594 | val 0.16638
  Epoch 020 - train 0.14258 | val 0.17393
  Epoch 021 - train 0.14868 | val 0.17513
  Regression -> MSE: 0.000087, MAE: 0.007169, R²: -0.0264
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14471 | val 0.24973
  Epoch 020 - train 0.14018 | val 0.22630
  Epoch 021 - train 0.13774 | val 0.23296
  Regression -> MSE: 0.000212, MAE: 0.011078, R²: -0.0022
  Directional -> Accuracy: 0.4545, MCC: -0.1149, F1: 0.3333

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14102 | val 0.12391
  Epoch 020 - train 0.12989 | val 0.12145
  Epoch 030 - train 0.13629 | val 0.12264
  Regression -> MSE: 0.000096, MAE: 0.007913, R²: -0.0447
  Directional -> Accuracy: 0.5179, MCC: 0.0696, F1: 0.4706

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17294 | val 0.10837
  Epoch 020 - train 0.15936 | val 0.11188
  Epoch 021 - train 0.14773 | val 0.11259
  Regression -> MSE: 0.000104, MAE: 0.008766, R²: -0.0042
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14499 | val 0.14769
  Epoch 020 - train 0.15473 | val 0.16720
  Epoch 021 - train 0.15227 | val 0.16697
  Regression -> MSE: 0.000244, MAE: 0.012941, R²: -0.0532
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13650 | val 0.16438
  Epoch 020 - train 0.14013 | val 0.16659
  Epoch 021 - train 0.14924 | val 0.16609
  Regression -> MSE: 0.000185, MAE: 0.008045, R²: -0.1118
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16535 | val 0.11911
  Epoch 020 - train 0.14869 | val 0.11912
  Epoch 021 - train 0.14260 | val 0.11961
  Regression -> MSE: 0.000236, MAE: 0.011851, R²: 0.0020
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14876 | val 0.22316
  Epoch 020 - train 0.14901 | val 0.24124
  Epoch 021 - train 0.14078 | val 0.24120
  Regression -> MSE: 0.000231, MAE: 0.009893, R²: -0.0017
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15136 | val 0.16582
  Epoch 020 - train 0.14278 | val 0.19703
  Epoch 021 - train 0.14970 | val 0.19668
  Regression -> MSE: 0.000134, MAE: 0.008172, R²: 0.0040
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14159 | val 0.17961
  Epoch 020 - train 0.14276 | val 0.18320
  Epoch 021 - train 0.14134 | val 0.18289
  Regression -> MSE: 0.000188, MAE: 0.010495, R²: -0.0001
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13840 | val 0.15666
  Epoch 020 - train 0.12490 | val 0.15362
  Epoch 030 - train 0.12344 | val 0.15083
  Regression -> MSE: 0.000332, MAE: 0.012333, R²: -0.2670
  Directional -> Accuracy: 0.5205, MCC: 0.1094, F1: 0.4262

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13705 | val 0.12686
  Epoch 020 - train 0.13873 | val 0.12049
  Epoch 030 - train 0.13753 | val 0.12409
  Regression -> MSE: 0.000166, MAE: 0.010354, R²: 0.0034
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13166 | val 0.14252
  Epoch 020 - train 0.13044 | val 0.15502
  Epoch 021 - train 0.13177 | val 0.15540
  Regression -> MSE: 0.000182, MAE: 0.010360, R²: -0.0121
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13510 | val 0.13420
  Epoch 020 - train 0.13778 | val 0.13707
  Epoch 021 - train 0.13090 | val 0.13664
  Regression -> MSE: 0.000351, MAE: 0.012456, R²: -0.0247
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.15458 | val 0.09020
  Epoch 020 - train 0.14501 | val 0.09326
  Epoch 021 - train 0.13659 | val 0.09395
  Regression -> MSE: 0.000130, MAE: 0.008577, R²: -0.2385
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13891 | val 0.19625
  Epoch 020 - train 0.12707 | val 0.20409
  Epoch 021 - train 0.14453 | val 0.20478
  Regression -> MSE: 0.000221, MAE: 0.011373, R²: -0.0095
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15121 | val 0.24203
  Epoch 020 - train 0.13683 | val 0.28564
  Epoch 021 - train 0.14470 | val 0.28395
  Regression -> MSE: 0.000095, MAE: 0.007605, R²: -0.2241
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15735 | val 0.12513
  Epoch 020 - train 0.13778 | val 0.12022
  Epoch 021 - train 0.15174 | val 0.12017
  Regression -> MSE: 0.000351, MAE: 0.015717, R²: -0.1419
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.16445 | val 0.08604
  Epoch 020 - train 0.15882 | val 0.08827
  Epoch 021 - train 0.12993 | val 0.08881
  Regression -> MSE: 0.000253, MAE: 0.011465, R²: -0.0388
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13965 | val 0.16922
  Epoch 020 - train 0.12931 | val 0.17353
  Epoch 021 - train 0.13625 | val 0.17466
  Regression -> MSE: 0.000081, MAE: 0.007073, R²: 0.0006
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14022 | val 0.17698
  Epoch 020 - train 0.14541 | val 0.16681
  Epoch 030 - train 0.14239 | val 0.16336
  Regression -> MSE: 0.000311, MAE: 0.014501, R²: -0.0137
  Directional -> Accuracy: 0.5106, MCC: 0.0045, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13647 | val 0.15181
  Epoch 020 - train 0.13398 | val 0.15449
  Epoch 021 - train 0.13749 | val 0.15508
  Regression -> MSE: 0.000098, MAE: 0.007234, R²: 0.0013
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15856 | val 0.16716
  Epoch 020 - train 0.14551 | val 0.18198
  Epoch 021 - train 0.15545 | val 0.18443
  Regression -> MSE: 0.000176, MAE: 0.010218, R²: -0.0224
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13501 | val 0.15534
  Epoch 020 - train 0.12880 | val 0.15554
  Epoch 021 - train 0.12969 | val 0.15586
  Regression -> MSE: 0.000224, MAE: 0.011759, R²: -0.0057
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13789 | val 0.15960
  Epoch 020 - train 0.13754 | val 0.17522
  Epoch 021 - train 0.13656 | val 0.17400
  Regression -> MSE: 0.000092, MAE: 0.007658, R²: -0.0003

[I 2026-02-24 02:03:35,393] Trial 103 finished with value: -0.01149400829295213 and parameters: {'feature_set': 'sentinment', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.00014182385671521094, 'weight_decay': 1.1699882245437878e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2129446878687098, 'early_stopping_min_delta': 0.007603000448837016}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.14902 | val 0.24094
  Epoch 021 - train 0.14804 | val 0.24041
  Regression -> MSE: 0.000239, MAE: 0.012328, R²: -0.0061
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.19914 | val 0.28780
  Epoch 020 - train 0.21428 | val 0.29257
  Epoch 021 - train 0.21916 | val 0.29226
  Regression -> MSE: 0.000248, MAE: 0.012571, R²: -0.0021
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.20130 | val 0.16804
  Epoch 020 - train 0.18730 | val 0.17191
  Epoch 021 - train 0.20434 | val 0.17245
  Regression -> MSE: 0.000691, MAE: 0.019462, R²: -0.0089
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.23449 | val 0.28763
  Epoch 020 - train 0.19271 | val 0.28788
  Epoch 030 - train 0.22158 | val 0.28845
  Regression -> MSE: 0.000318, MAE: 0.014531, R²: -0.0257
  Directional -> Accuracy: 0.4681, MCC: -0.0375, F1: 0.3243

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.16942 | val 0.27473
  Epoch 020 - train 0.17141 | val 0.28717
  Epoch 021 - train 0.17077 | val 0.28792
  Regression -> MSE: 0.000354, MAE: 0.014651, R²: -0.0126
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.20446 | val 0.18254
  Epoch 020 - train 0.21181 | val 0.18978
  Epoch 021 - train 0.21251 | val 0.19044
  Regression -> MSE: 0.000204, MAE: 0.010032, R²: -0.0004
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.19969 | val 0.33753
  Epoch 020 - train 0.18246 | val 0.38290
  Epoch 028 - train 0.19451 | val 0.39497
  Regression -> MSE: 0.000558, MAE: 0.018208, R²: -0.0047
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.20878 | val 0.24798
  Epoch 020 - train 0.21021 | val 0.25475
  Epoch 021 - train 0.19844 | val 0.25408
  Regression -> MSE: 0.000247, MAE: 0.011906, R²: -0.0045
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.23617 | val 0.26264
  Epoch 020 - train 0.22724 | val 0.25224
  Epoch 030 - train 0.23950 | val 0.25159
  Regression -> MSE: 0.000741, MAE: 0.021953, R²: -0.2408
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.19038 | val 0.21230
  Epoch 020 - train 0.19687 | val 0.21641
  Epoch 021 - train 0.19758 | val 0.21635
  Regression -> MSE: 0.000400, MAE: 0.016069, R²: -0.0440
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.20553 | val 0.23035
  Epoch 020 - train 0.20868 | val 0.23170
  Epoch 021 - train 0.19642 | val 0.23156
  Regression -> MSE: 0.000242, MAE: 0.011772, R²: -0.0018
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.19908 | val 0.24424
  Epoch 020 - train 0.20222 | val 0.24532
  Epoch 028 - train 0.20004 | val 0.24557
  Regression -> MSE: 0.000360, MAE: 0.014178, R²: -0.1574
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.20631 | val 0.21042
  Epoch 020 - train 0.21317 | val 0.21086
  Epoch 021 - train 0.21050 | val 0.21103
  Regression -> MSE: 0.000681, MAE: 0.019574, R²: -0.0055
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.18724 | val 0.21125
  Epoch 020 - train 0.19773 | val 0.25008
  Epoch 021 - train 0.19719 | val 0.25277
  Regression -> MSE: 0.000138, MAE: 0.009065, R²: 0.0005
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.17640 | val 0.25346
  Epoch 020 - train 0.18486 | val 0.25656
  Epoch 021 - train 0.18237 | val 0.25463
  Regression -> MSE: 0.000226, MAE: 0.010806, R²: -0.0032
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.19748 | val 0.38317
  Epoch 020 - train 0.19927 | val 0.39571
  Epoch 021 - train 0.19496 | val 0.39523
  Regression -> MSE: 0.000362, MAE: 0.016091, R²: 0.0005
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.20899 | val 0.19897
  Epoch 020 - train 0.19608 | val 0.19925
  Epoch 021 - train 0.20533 | val 0.19975
  Regression -> MSE: 0.000109, MAE: 0.008122, R²: -0.0091
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.19545 | val 0.30205
  Epoch 020 - train 0.19214 | val 0.31123
  Epoch 021 - train 0.19294 | val 0.31283
  Regression -> MSE: 0.000156, MAE: 0.009685, R²: -0.0005
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.20112 | val 0.18980
  Epoch 020 - train 0.19907 | val 0.19174
  Epoch 021 - train 0.19249 | val 0.19105
  Regression -> MSE: 0.000290, MAE: 0.013832, R²: -0.0655
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.19716 | val 0.26031
  Epoch 020 - train 0.19290 | val 0.26575
  Epoch 021 - train 0.19172 | val 0.26382
  Regression -> MSE: 0.000155, MAE: 0.008766, R²: -0.0374
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.20723 | val 0.27762
  Epoch 020 - train 0.21233 | val 0.27758
  Epoch 021 - train 0.21011 | val 0.27764
  Regression -> MSE: 0.000230, MAE: 0.010934, R²: -0.0184
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.19662 | val 0.26285
  Epoch 020 - train 0.20745 | val 0.35067
  Epoch 021 - train 0.18934 | val 0.35267
  Regression -> MSE: 0.000147, MAE: 0.008534, R²: -0.0241
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.19355 | val 0.22565
  Epoch 020 - train 0.19538 | val 0.22997
  Epoch 027 - train 0.20707 | val 0.22995
  Regression -> MSE: 0.000179, MAE: 0.010782, R²: -0.0813
  Directional -> Accuracy: 0.4697, MCC: -0.0845, F1: 0.6067

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.20649 | val 0.23146
  Epoch 020 - train 0.22603 | val 0.24251
  Epoch 021 - train 0.21820 | val 0.24284
  Regression -> MSE: 0.000085, MAE: 0.007035, R²: 0.0038
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.20575 | val 0.37281
  Epoch 020 - train 0.20351 | val 0.40395
  Epoch 021 - train 0.20904 | val 0.39589
  Regression -> MSE: 0.000218, MAE: 0.011051, R²: -0.0305
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.19243 | val 0.15833
  Epoch 020 - train 0.19159 | val 0.15934
  Epoch 021 - train 0.19411 | val 0.15950
  Regression -> MSE: 0.000099, MAE: 0.008203, R²: -0.0762
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18858 | val 0.13995
  Epoch 020 - train 0.19692 | val 0.14043
  Epoch 021 - train 0.20849 | val 0.14055
  Regression -> MSE: 0.000108, MAE: 0.008948, R²: -0.0465
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.20502 | val 0.17400
  Epoch 020 - train 0.23318 | val 0.18302
  Epoch 021 - train 0.21482 | val 0.18406
  Regression -> MSE: 0.000231, MAE: 0.012513, R²: 0.0001
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.21258 | val 0.22840
  Epoch 020 - train 0.21512 | val 0.23350
  Epoch 021 - train 0.21310 | val 0.23243
  Regression -> MSE: 0.000171, MAE: 0.007844, R²: -0.0274
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.18894 | val 0.14866
  Epoch 020 - train 0.19647 | val 0.15544
  Epoch 021 - train 0.21026 | val 0.15702
  Regression -> MSE: 0.000236, MAE: 0.011855, R²: 0.0002
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.20255 | val 0.29778
  Epoch 020 - train 0.20549 | val 0.31048
  Epoch 021 - train 0.20380 | val 0.31210
  Regression -> MSE: 0.000234, MAE: 0.010123, R²: -0.0169
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.21708 | val 0.21703
  Epoch 020 - train 0.21655 | val 0.21115
  Epoch 030 - train 0.22147 | val 0.21066
  Regression -> MSE: 0.000131, MAE: 0.008473, R²: 0.0269
  Directional -> Accuracy: 0.4186, MCC: -0.1934, F1: 0.5098

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.22121 | val 0.23763
  Epoch 020 - train 0.21657 | val 0.24880
  Epoch 021 - train 0.19936 | val 0.24813
  Regression -> MSE: 0.000188, MAE: 0.010461, R²: -0.0008
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.18054 | val 0.19991
  Epoch 020 - train 0.16548 | val 0.20016
  Epoch 028 - train 0.18039 | val 0.20020
  Regression -> MSE: 0.000280, MAE: 0.010924, R²: -0.0682
  Directional -> Accuracy: 0.5205, MCC: 0.1094, F1: 0.4262

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.19450 | val 0.14786
  Epoch 020 - train 0.18645 | val 0.15072
  Epoch 021 - train 0.16680 | val 0.15155
  Regression -> MSE: 0.000169, MAE: 0.010374, R²: -0.0119
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.19483 | val 0.20747
  Epoch 020 - train 0.21236 | val 0.24549
  Epoch 021 - train 0.20483 | val 0.24861
  Regression -> MSE: 0.000184, MAE: 0.010487, R²: -0.0250
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.20634 | val 0.16383
  Epoch 020 - train 0.20381 | val 0.16408
  Epoch 021 - train 0.21495 | val 0.16391
  Regression -> MSE: 0.000342, MAE: 0.011877, R²: 0.0016
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.21182 | val 0.11328
  Epoch 020 - train 0.22297 | val 0.11971
  Epoch 021 - train 0.21883 | val 0.11993
  Regression -> MSE: 0.000125, MAE: 0.008459, R²: -0.1882
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.21137 | val 0.25869
  Epoch 020 - train 0.21451 | val 0.26554
  Epoch 021 - train 0.19693 | val 0.26835
  Regression -> MSE: 0.000219, MAE: 0.011309, R²: -0.0021
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.20453 | val 0.31610
  Epoch 020 - train 0.20664 | val 0.32827
  Epoch 021 - train 0.23393 | val 0.32823
  Regression -> MSE: 0.000093, MAE: 0.007519, R²: -0.1919
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.19583 | val 0.13571
  Epoch 020 - train 0.19856 | val 0.14495
  Epoch 021 - train 0.19157 | val 0.14591
  Regression -> MSE: 0.000315, MAE: 0.014241, R²: -0.0232
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.19737 | val 0.10465
  Epoch 020 - train 0.21479 | val 0.10824
  Epoch 021 - train 0.20216 | val 0.10945
  Regression -> MSE: 0.000249, MAE: 0.011498, R²: -0.0228
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.19950 | val 0.21654
  Epoch 020 - train 0.20304 | val 0.21626
  Epoch 021 - train 0.18911 | val 0.21622
  Regression -> MSE: 0.000081, MAE: 0.007075, R²: 0.0004
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.21809 | val 0.22224
  Epoch 020 - train 0.20854 | val 0.23146
  Epoch 021 - train 0.21018 | val 0.23262
  Regression -> MSE: 0.000309, MAE: 0.014523, R²: -0.0076
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.21972 | val 0.20740
  Epoch 020 - train 0.19702 | val 0.20083
  Epoch 030 - train 0.20832 | val 0.19990
  Regression -> MSE: 0.000105, MAE: 0.007425, R²: -0.0718
  Directional -> Accuracy: 0.5227, MCC: 0.0459, F1: 0.5532

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.21575 | val 0.21775
  Epoch 020 - train 0.20801 | val 0.21389
  Epoch 030 - train 0.21734 | val 0.21239
  Regression -> MSE: 0.000196, MAE: 0.010614, R²: -0.1413
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.20399 | val 0.23643
  Epoch 020 - train 0.19786 | val 0.24255
  Epoch 021 - train 0.19098 | val 0.24549
  Regression -> MSE: 0.000231, MAE: 0.011905, R²: -0.0362
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.20396 | val 0.19502
  Epoch 020 - train 0.20495 | val 0.19545
  Epoch 028 - train 0.20454 | val 0.19607
  Regression -> MSE: 0.000093, MAE: 0.007611, R²: -0.0028

[I 2026-02-24 02:05:41,596] Trial 104 finished with value: -0.011508989214672425 and parameters: {'feature_set': 'sentinment', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 1.2781411688776302e-06, 'weight_decay': 3.891827064157391e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2849918055122792, 'early_stopping_min_delta': 0.004485906816243947}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.18058 | val 0.33070
  Epoch 021 - train 0.19047 | val 0.33146
  Regression -> MSE: 0.000245, MAE: 0.012368, R²: -0.0329
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.17823 | val 0.20885
  Epoch 020 - train 0.16507 | val 0.20938
  Epoch 021 - train 0.16908 | val 0.20970
  Regression -> MSE: 0.000250, MAE: 0.012657, R²: -0.0113
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.17569 | val 0.17334
  Epoch 020 - train 0.17045 | val 0.20910
  Epoch 021 - train 0.17281 | val 0.20987
  Regression -> MSE: 0.000685, MAE: 0.019357, R²: -0.0007
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16723 | val 0.25011
  Epoch 020 - train 0.17376 | val 0.24631
  Epoch 030 - train 0.18041 | val 0.24639
  Regression -> MSE: 0.000329, MAE: 0.014662, R²: -0.0608
  Directional -> Accuracy: 0.4468, MCC: -0.0872, F1: 0.3158

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.16011 | val 0.18493
  Epoch 020 - train 0.14921 | val 0.19116
  Epoch 021 - train 0.15897 | val 0.19169
  Regression -> MSE: 0.000349, MAE: 0.014520, R²: 0.0010
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.18377 | val 0.16407
  Epoch 020 - train 0.17202 | val 0.17538
  Epoch 021 - train 0.19387 | val 0.17658
  Regression -> MSE: 0.000206, MAE: 0.010105, R²: -0.0133
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15833 | val 0.30363
  Epoch 020 - train 0.15857 | val 0.29794
  Epoch 021 - train 0.16399 | val 0.29820
  Regression -> MSE: 0.000597, MAE: 0.018928, R²: -0.0759
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.18327 | val 0.21838
  Epoch 020 - train 0.17756 | val 0.22080
  Epoch 021 - train 0.17770 | val 0.22163
  Regression -> MSE: 0.000245, MAE: 0.011999, R²: 0.0015
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.18169 | val 0.21180
  Epoch 020 - train 0.17428 | val 0.17627
  Epoch 030 - train 0.17749 | val 0.17226
  Regression -> MSE: 0.000640, MAE: 0.019698, R²: -0.0716
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.17695 | val 0.19508
  Epoch 020 - train 0.16812 | val 0.19496
  Epoch 021 - train 0.17245 | val 0.19562
  Regression -> MSE: 0.000384, MAE: 0.016065, R²: -0.0015
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.17884 | val 0.20161
  Epoch 020 - train 0.16901 | val 0.20390
  Epoch 021 - train 0.17287 | val 0.20424
  Regression -> MSE: 0.000244, MAE: 0.011653, R²: -0.0105
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.17398 | val 0.22306
  Epoch 020 - train 0.17144 | val 0.22519
  Epoch 021 - train 0.16163 | val 0.22580
  Regression -> MSE: 0.000320, MAE: 0.013576, R²: -0.0294
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.17830 | val 0.18169
  Epoch 020 - train 0.18736 | val 0.18486
  Epoch 021 - train 0.18167 | val 0.18463
  Regression -> MSE: 0.000687, MAE: 0.019888, R²: -0.0144
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.19168 | val 0.16120
  Epoch 020 - train 0.18791 | val 0.16973
  Epoch 021 - train 0.20435 | val 0.16937
  Regression -> MSE: 0.000140, MAE: 0.009018, R²: -0.0123
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.17905 | val 0.20050
  Epoch 020 - train 0.16947 | val 0.20274
  Epoch 021 - train 0.15886 | val 0.20288
  Regression -> MSE: 0.000231, MAE: 0.010922, R²: -0.0261
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16949 | val 0.31342
  Epoch 020 - train 0.16663 | val 0.31319
  Epoch 021 - train 0.17386 | val 0.31284
  Regression -> MSE: 0.000368, MAE: 0.015936, R²: -0.0173
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.19349 | val 0.18634
  Epoch 020 - train 0.19585 | val 0.19192
  Epoch 021 - train 0.19463 | val 0.19182
  Regression -> MSE: 0.000111, MAE: 0.007959, R²: -0.0296
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.18266 | val 0.25525
  Epoch 020 - train 0.17775 | val 0.26183
  Epoch 021 - train 0.18547 | val 0.26145
  Regression -> MSE: 0.000157, MAE: 0.009835, R²: -0.0098
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.18406 | val 0.16686
  Epoch 020 - train 0.18921 | val 0.16812
  Epoch 021 - train 0.17183 | val 0.16752
  Regression -> MSE: 0.000273, MAE: 0.013072, R²: -0.0023
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.17323 | val 0.22154
  Epoch 020 - train 0.17355 | val 0.22318
  Epoch 021 - train 0.17716 | val 0.22338
  Regression -> MSE: 0.000167, MAE: 0.009127, R²: -0.1162
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.19034 | val 0.22058
  Epoch 020 - train 0.18105 | val 0.22041
  Epoch 021 - train 0.18326 | val 0.22058
  Regression -> MSE: 0.000234, MAE: 0.010926, R²: -0.0320
  Directional -> Accuracy: 0.6000, MCC: 0.1870, F1: 0.7115

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.18844 | val 0.21357
  Epoch 020 - train 0.18636 | val 0.24856
  Epoch 021 - train 0.18702 | val 0.24870
  Regression -> MSE: 0.000156, MAE: 0.008946, R²: -0.0898
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.17290 | val 0.18594
  Epoch 020 - train 0.16789 | val 0.18601
  Epoch 021 - train 0.16277 | val 0.18577
  Regression -> MSE: 0.000168, MAE: 0.010312, R²: -0.0157
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.18005 | val 0.19173
  Epoch 020 - train 0.18005 | val 0.18897
  Epoch 021 - train 0.18362 | val 0.18906
  Regression -> MSE: 0.000092, MAE: 0.007390, R²: -0.0775
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.17663 | val 0.19364
  Epoch 020 - train 0.16827 | val 0.19833
  Epoch 021 - train 0.16062 | val 0.19809
  Regression -> MSE: 0.000212, MAE: 0.011070, R²: -0.0032
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.18659 | val 0.13003
  Epoch 020 - train 0.18367 | val 0.13197
  Epoch 028 - train 0.18283 | val 0.13149
  Regression -> MSE: 0.000096, MAE: 0.008205, R²: -0.0456
  Directional -> Accuracy: 0.5357, MCC: -0.0017, F1: 0.6667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.20051 | val 0.12751
  Epoch 020 - train 0.17267 | val 0.15620
  Epoch 021 - train 0.18955 | val 0.16062
  Regression -> MSE: 0.000108, MAE: 0.008984, R²: -0.0517
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.18602 | val 0.15101
  Epoch 020 - train 0.19403 | val 0.15702
  Epoch 021 - train 0.18768 | val 0.15702
  Regression -> MSE: 0.000234, MAE: 0.012642, R²: -0.0099
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.17468 | val 0.17932
  Epoch 020 - train 0.17013 | val 0.18203
  Epoch 021 - train 0.18431 | val 0.18197
  Regression -> MSE: 0.000187, MAE: 0.008088, R²: -0.1240
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.19686 | val 0.13068
  Epoch 020 - train 0.19303 | val 0.16541
  Epoch 021 - train 0.18023 | val 0.17488
  Regression -> MSE: 0.000237, MAE: 0.011860, R²: -0.0004
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.17310 | val 0.24612
  Epoch 020 - train 0.17408 | val 0.24778
  Epoch 021 - train 0.16033 | val 0.24838
  Regression -> MSE: 0.000231, MAE: 0.009914, R²: -0.0024
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.20025 | val 0.20464
  Epoch 020 - train 0.20554 | val 0.25077
  Epoch 021 - train 0.19359 | val 0.25229
  Regression -> MSE: 0.000138, MAE: 0.008343, R²: -0.0189
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.19162 | val 0.19796
  Epoch 020 - train 0.17888 | val 0.19952
  Epoch 021 - train 0.18883 | val 0.19948
  Regression -> MSE: 0.000201, MAE: 0.010746, R²: -0.0670
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.17110 | val 0.22959
  Epoch 020 - train 0.16404 | val 0.22864
  Epoch 021 - train 0.16906 | val 0.22900
  Regression -> MSE: 0.000263, MAE: 0.010688, R²: -0.0034
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.19192 | val 0.14164
  Epoch 020 - train 0.20299 | val 0.13315
  Epoch 030 - train 0.17156 | val 0.12889
  Regression -> MSE: 0.000170, MAE: 0.010450, R²: -0.0205
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15861 | val 0.15991
  Epoch 020 - train 0.16458 | val 0.16434
  Epoch 021 - train 0.15748 | val 0.16461
  Regression -> MSE: 0.000181, MAE: 0.010366, R²: -0.0061
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16773 | val 0.14944
  Epoch 020 - train 0.16291 | val 0.14877
  Epoch 021 - train 0.17008 | val 0.14890
  Regression -> MSE: 0.000347, MAE: 0.012216, R²: -0.0128
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.17908 | val 0.10090
  Epoch 020 - train 0.18838 | val 0.11166
  Epoch 021 - train 0.17636 | val 0.11244
  Regression -> MSE: 0.000119, MAE: 0.008370, R²: -0.1274
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17135 | val 0.21454
  Epoch 020 - train 0.18183 | val 0.21385
  Epoch 021 - train 0.16885 | val 0.21378
  Regression -> MSE: 0.000222, MAE: 0.011402, R²: -0.0155
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.18032 | val 0.27060
  Epoch 020 - train 0.18491 | val 0.28136
  Epoch 021 - train 0.16890 | val 0.28146
  Regression -> MSE: 0.000096, MAE: 0.007627, R²: -0.2304
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.16721 | val 0.11635
  Epoch 020 - train 0.17366 | val 0.11642
  Epoch 021 - train 0.17275 | val 0.11628
  Regression -> MSE: 0.000309, MAE: 0.013802, R²: -0.0039
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17912 | val 0.09773
  Epoch 020 - train 0.20159 | val 0.09891
  Epoch 021 - train 0.18450 | val 0.09899
  Regression -> MSE: 0.000254, MAE: 0.011462, R²: -0.0429
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16006 | val 0.19211
  Epoch 020 - train 0.17171 | val 0.19245
  Epoch 021 - train 0.16828 | val 0.19251
  Regression -> MSE: 0.000085, MAE: 0.007058, R²: -0.0548
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17336 | val 0.20284
  Epoch 020 - train 0.18100 | val 0.22075
  Epoch 021 - train 0.18928 | val 0.22359
  Regression -> MSE: 0.000307, MAE: 0.014494, R²: 0.0003
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.18004 | val 0.19378
  Epoch 020 - train 0.18023 | val 0.20931
  Epoch 021 - train 0.18386 | val 0.21092
  Regression -> MSE: 0.000104, MAE: 0.007110, R²: -0.0581
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.20305 | val 0.18631
  Epoch 020 - train 0.19420 | val 0.17336
  Epoch 030 - train 0.18670 | val 0.17406
  Regression -> MSE: 0.000178, MAE: 0.010118, R²: -0.0337
  Directional -> Accuracy: 0.3878, MCC: -0.0861, F1: 0.5161

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.16395 | val 0.19677
  Epoch 020 - train 0.15828 | val 0.20575
  Epoch 021 - train 0.15042 | val 0.20630
  Regression -> MSE: 0.000224, MAE: 0.011737, R²: -0.0031
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.16487 | val 0.18784
  Epoch 020 - train 0.16357 | val 0.19636
  Epoch 021 - train 0.17098 | val 0.19701
  Regression -> MSE: 0.000094, MAE: 0.007704, R²: -0.0132

[I 2026-02-24 02:07:47,745] Trial 105 finished with value: -0.011451756283549348 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 2.5167058895591485e-06, 'weight_decay': 2.743441885674878e-06, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.24424639413365934, 'early_stopping_min_delta': 0.008442371285794266}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.16151 | val 0.22845
  Epoch 021 - train 0.17857 | val 0.22792
  Regression -> MSE: 0.000242, MAE: 0.012345, R²: -0.0219
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.28613 | val 0.33941
  Epoch 020 - train 0.26362 | val 0.33414
  Epoch 030 - train 0.28210 | val 0.33417
  Regression -> MSE: 0.000242, MAE: 0.012288, R²: 0.0225
  Directional -> Accuracy: 0.5974, MCC: 0.1799, F1: 0.5231

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.28965 | val 0.23569
  Epoch 020 - train 0.28077 | val 0.23202
  Epoch 021 - train 0.29782 | val 0.23205
  Regression -> MSE: 0.000691, MAE: 0.019465, R²: -0.0096
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.27279 | val 0.43532
  Epoch 020 - train 0.27424 | val 0.43770
  Epoch 021 - train 0.26893 | val 0.43827
  Regression -> MSE: 0.000311, MAE: 0.014402, R²: -0.0012
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.23696 | val 0.21585
  Epoch 020 - train 0.22515 | val 0.24674
  Epoch 021 - train 0.24065 | val 0.24686
  Regression -> MSE: 0.000350, MAE: 0.014557, R²: -0.0023
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.27716 | val 0.25115
  Epoch 020 - train 0.26615 | val 0.25201
  Epoch 021 - train 0.27623 | val 0.25189
  Regression -> MSE: 0.000207, MAE: 0.010111, R²: -0.0158
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.26616 | val 0.51177
  Epoch 020 - train 0.29896 | val 0.51313
  Epoch 021 - train 0.29100 | val 0.51361
  Regression -> MSE: 0.000590, MAE: 0.018776, R²: -0.0625
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.30023 | val 0.32045
  Epoch 020 - train 0.30186 | val 0.33864
  Epoch 021 - train 0.30859 | val 0.33874
  Regression -> MSE: 0.000246, MAE: 0.011936, R²: -0.0006
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.27886 | val 0.31402
  Epoch 020 - train 0.27759 | val 0.32002
  Epoch 021 - train 0.24639 | val 0.32098
  Regression -> MSE: 0.000606, MAE: 0.019381, R²: -0.0147
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.28872 | val 0.32846
  Epoch 020 - train 0.30972 | val 0.33619
  Epoch 021 - train 0.29532 | val 0.33747
  Regression -> MSE: 0.000384, MAE: 0.016122, R²: -0.0009
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.26981 | val 0.32944
  Epoch 020 - train 0.28230 | val 0.34311
  Epoch 021 - train 0.26684 | val 0.34350
  Regression -> MSE: 0.000243, MAE: 0.011678, R²: -0.0079
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.23696 | val 0.37136
  Epoch 020 - train 0.23621 | val 0.37032
  Epoch 021 - train 0.22718 | val 0.37003
  Regression -> MSE: 0.000314, MAE: 0.013593, R²: -0.0113
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.26617 | val 0.29800
  Epoch 020 - train 0.27351 | val 0.30955
  Epoch 021 - train 0.26903 | val 0.31098
  Regression -> MSE: 0.000678, MAE: 0.019518, R²: -0.0005
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.27504 | val 0.25589
  Epoch 020 - train 0.27817 | val 0.25296
  Epoch 021 - train 0.27390 | val 0.25306
  Regression -> MSE: 0.000139, MAE: 0.009117, R²: -0.0025
  Directional -> Accuracy: 0.4419, MCC: -0.0728, F1: 0.5200

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.24330 | val 0.33281
  Epoch 020 - train 0.24126 | val 0.34099
  Epoch 021 - train 0.23646 | val 0.34179
  Regression -> MSE: 0.000229, MAE: 0.010819, R²: -0.0165
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.28589 | val 0.55770
  Epoch 020 - train 0.25799 | val 0.59169
  Epoch 021 - train 0.29236 | val 0.59298
  Regression -> MSE: 0.000363, MAE: 0.016213, R²: -0.0020
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.29256 | val 0.27494
  Epoch 020 - train 0.28616 | val 0.30175
  Epoch 021 - train 0.28388 | val 0.30177
  Regression -> MSE: 0.000109, MAE: 0.008101, R²: -0.0076
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.26815 | val 0.43037
  Epoch 020 - train 0.26757 | val 0.42970
  Epoch 021 - train 0.26554 | val 0.42949
  Regression -> MSE: 0.000157, MAE: 0.009829, R²: -0.0056
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.30209 | val 0.27829
  Epoch 020 - train 0.29410 | val 0.35956
  Epoch 021 - train 0.30414 | val 0.36194
  Regression -> MSE: 0.000297, MAE: 0.014051, R²: -0.0898
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.23968 | val 0.33816
  Epoch 020 - train 0.24222 | val 0.35124
  Epoch 021 - train 0.23248 | val 0.35063
  Regression -> MSE: 0.000158, MAE: 0.008864, R²: -0.0589
  Directional -> Accuracy: 0.5692, MCC: 0.1037, F1: 0.6410

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.26339 | val 0.37108
  Epoch 020 - train 0.26296 | val 0.38129
  Epoch 021 - train 0.25728 | val 0.38171
  Regression -> MSE: 0.000241, MAE: 0.011080, R²: -0.0631
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.28158 | val 0.32771
  Epoch 020 - train 0.27153 | val 0.32917
  Epoch 021 - train 0.27749 | val 0.32975
  Regression -> MSE: 0.000143, MAE: 0.008292, R²: 0.0004
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.24639 | val 0.29483
  Epoch 020 - train 0.24418 | val 0.29630
  Epoch 021 - train 0.23871 | val 0.29641
  Regression -> MSE: 0.000180, MAE: 0.010330, R²: -0.0911
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.31250 | val 0.30400
  Epoch 020 - train 0.28653 | val 0.31526
  Epoch 021 - train 0.27760 | val 0.31686
  Regression -> MSE: 0.000086, MAE: 0.007065, R²: -0.0064
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.25792 | val 0.32349
  Epoch 020 - train 0.26896 | val 0.43303
  Epoch 021 - train 0.27390 | val 0.43640
  Regression -> MSE: 0.000214, MAE: 0.011021, R²: -0.0118
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.24690 | val 0.22665
  Epoch 020 - train 0.24361 | val 0.22682
  Epoch 021 - train 0.25195 | val 0.22678
  Regression -> MSE: 0.000099, MAE: 0.008203, R²: -0.0770
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.28950 | val 0.19690
  Epoch 020 - train 0.26387 | val 0.19585
  Epoch 021 - train 0.28942 | val 0.19572
  Regression -> MSE: 0.000109, MAE: 0.008998, R²: -0.0570
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.27825 | val 0.24130
  Epoch 020 - train 0.27649 | val 0.27003
  Epoch 021 - train 0.28308 | val 0.27707
  Regression -> MSE: 0.000232, MAE: 0.012562, R²: -0.0018
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.27466 | val 0.30274
  Epoch 020 - train 0.26419 | val 0.31301
  Epoch 021 - train 0.26954 | val 0.31428
  Regression -> MSE: 0.000178, MAE: 0.007943, R²: -0.0718
  Directional -> Accuracy: 0.4386, MCC: -0.1505, F1: 0.5152

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.28504 | val 0.20311
  Epoch 020 - train 0.25749 | val 0.20236
  Epoch 021 - train 0.27894 | val 0.20234
  Regression -> MSE: 0.000238, MAE: 0.011906, R²: -0.0052
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.27208 | val 0.43405
  Epoch 020 - train 0.29768 | val 0.44514
  Epoch 021 - train 0.28817 | val 0.44793
  Regression -> MSE: 0.000234, MAE: 0.010099, R²: -0.0147
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.27693 | val 0.29672
  Epoch 020 - train 0.28691 | val 0.30582
  Epoch 021 - train 0.28913 | val 0.30787
  Regression -> MSE: 0.000135, MAE: 0.008171, R²: -0.0030
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.28276 | val 0.33354
  Epoch 020 - train 0.24997 | val 0.34085
  Epoch 021 - train 0.26814 | val 0.34214
  Regression -> MSE: 0.000189, MAE: 0.010430, R²: -0.0018
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.24670 | val 0.29100
  Epoch 020 - train 0.25829 | val 0.29044
  Epoch 021 - train 0.23786 | val 0.29061
  Regression -> MSE: 0.000280, MAE: 0.010931, R²: -0.0683
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.29084 | val 0.21396
  Epoch 020 - train 0.25356 | val 0.21249
  Epoch 021 - train 0.24524 | val 0.21225
  Regression -> MSE: 0.000167, MAE: 0.010377, R²: -0.0021
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.27698 | val 0.28100
  Epoch 020 - train 0.26532 | val 0.28414
  Epoch 021 - train 0.23910 | val 0.28439
  Regression -> MSE: 0.000191, MAE: 0.010709, R²: -0.0604
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.32016 | val 0.25329
  Epoch 020 - train 0.29711 | val 0.28760
  Epoch 021 - train 0.30474 | val 0.28841
  Regression -> MSE: 0.000353, MAE: 0.011828, R²: -0.0306
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.28309 | val 0.15823
  Epoch 020 - train 0.27757 | val 0.15886
  Epoch 021 - train 0.28910 | val 0.15894
  Regression -> MSE: 0.000129, MAE: 0.008544, R²: -0.2280
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.27664 | val 0.36243
  Epoch 020 - train 0.28479 | val 0.36291
  Epoch 021 - train 0.28692 | val 0.36440
  Regression -> MSE: 0.000224, MAE: 0.011441, R²: -0.0229
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.27275 | val 0.45933
  Epoch 020 - train 0.26109 | val 0.47246
  Epoch 021 - train 0.25932 | val 0.47502
  Regression -> MSE: 0.000088, MAE: 0.007347, R²: -0.1348
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.30296 | val 0.20784
  Epoch 020 - train 0.27090 | val 0.20846
  Epoch 021 - train 0.29684 | val 0.20866
  Regression -> MSE: 0.000332, MAE: 0.015042, R²: -0.0782
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.30724 | val 0.15257
  Epoch 020 - train 0.28780 | val 0.15026
  Epoch 021 - train 0.29162 | val 0.15029
  Regression -> MSE: 0.000261, MAE: 0.011508, R²: -0.0690
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.27201 | val 0.31287
  Epoch 020 - train 0.26501 | val 0.32489
  Epoch 021 - train 0.26380 | val 0.32554
  Regression -> MSE: 0.000085, MAE: 0.007058, R²: -0.0514
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.28017 | val 0.32100
  Epoch 020 - train 0.28236 | val 0.33791
  Epoch 021 - train 0.27538 | val 0.34140
  Regression -> MSE: 0.000309, MAE: 0.014522, R²: -0.0074
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.28013 | val 0.27566
  Epoch 020 - train 0.25525 | val 0.27422
  Epoch 021 - train 0.26098 | val 0.27396
  Regression -> MSE: 0.000098, MAE: 0.007254, R²: -0.0003
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.28832 | val 0.31576
  Epoch 020 - train 0.27947 | val 0.31673
  Epoch 021 - train 0.28025 | val 0.31693
  Regression -> MSE: 0.000174, MAE: 0.010073, R²: -0.0138
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.27254 | val 0.28221
  Epoch 020 - train 0.25047 | val 0.32385
  Epoch 021 - train 0.25894 | val 0.33142
  Regression -> MSE: 0.000226, MAE: 0.011809, R²: -0.0126
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.27177 | val 0.28202
  Epoch 020 - train 0.27886 | val 0.28260
  Epoch 021 - train 0.25185 | val 0.28309

[I 2026-02-24 02:09:11,578] Trial 106 finished with value: -0.011455226317858194 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 8.13393946936176e-06, 'weight_decay': 4.534795578912685e-07, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.44729495210921066, 'early_stopping_min_delta': 0.007132473454261932}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.26905 | val 0.37979
  Epoch 021 - train 0.27555 | val 0.37970
  Regression -> MSE: 0.000238, MAE: 0.012370, R²: -0.0042
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14270 | val 0.15903
  Epoch 016 - train 0.14136 | val 0.15899
  Regression -> MSE: 0.000252, MAE: 0.012584, R²: -0.0181
  Directional -> Accuracy: 0.5325, MCC: 0.0398, F1: 0.4194

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.15034 | val 0.13885
  Epoch 011 - train 0.15504 | val 0.13976
  Regression -> MSE: 0.000739, MAE: 0.020189, R²: -0.0793
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13365 | val 0.20573
  Epoch 011 - train 0.14074 | val 0.20581
  Regression -> MSE: 0.000311, MAE: 0.014418, R²: -0.0036
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12052 | val 0.11760
  Epoch 011 - train 0.12714 | val 0.11969
  Regression -> MSE: 0.000349, MAE: 0.014507, R²: -0.0004
  Directional -> Accuracy: 0.5733, MCC: 0.1246, F1: 0.6444

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13577 | val 0.11921
  Epoch 017 - train 0.14389 | val 0.11831
  Regression -> MSE: 0.000212, MAE: 0.010069, R²: -0.0415
  Directional -> Accuracy: 0.5490, MCC: 0.0788, F1: 0.6667

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12715 | val 0.23975
  Epoch 011 - train 0.12525 | val 0.24071
  Regression -> MSE: 0.000565, MAE: 0.018234, R²: -0.0173
  Directional -> Accuracy: 0.5106, MCC: 0.0111, F1: 0.3030

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14269 | val 0.15190
  Epoch 011 - train 0.13775 | val 0.15168
  Regression -> MSE: 0.000244, MAE: 0.012254, R²: 0.0061
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14396 | val 0.14670
  Epoch 020 - train 0.13548 | val 0.13280
  Epoch 029 - train 0.12890 | val 0.13323
  Regression -> MSE: 0.000642, MAE: 0.019747, R²: -0.0746
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13986 | val 0.16564
  Epoch 011 - train 0.13307 | val 0.16792
  Regression -> MSE: 0.000384, MAE: 0.016084, R²: 0.0002
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14282 | val 0.15705
  Epoch 011 - train 0.12885 | val 0.15708
  Regression -> MSE: 0.000242, MAE: 0.011911, R²: -0.0034
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12524 | val 0.18078
  Epoch 011 - train 0.12958 | val 0.18084
  Regression -> MSE: 0.000315, MAE: 0.013586, R²: -0.0136
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13274 | val 0.14967
  Epoch 011 - train 0.14033 | val 0.14937
  Regression -> MSE: 0.000688, MAE: 0.019860, R²: -0.0157
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14820 | val 0.12449
  Epoch 011 - train 0.14382 | val 0.12473
  Regression -> MSE: 0.000146, MAE: 0.009560, R²: -0.0545
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13585 | val 0.15761
  Epoch 011 - train 0.13371 | val 0.15719
  Regression -> MSE: 0.000227, MAE: 0.010808, R²: -0.0113
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13297 | val 0.25746
  Epoch 011 - train 0.14624 | val 0.25856
  Regression -> MSE: 0.000373, MAE: 0.015960, R²: -0.0286
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14058 | val 0.12838
  Epoch 011 - train 0.13636 | val 0.12852
  Regression -> MSE: 0.000108, MAE: 0.007982, R²: -0.0034
  Directional -> Accuracy: 0.5857, MCC: 0.2306, F1: 0.7238

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13635 | val 0.21554
  Epoch 011 - train 0.13685 | val 0.21491
  Regression -> MSE: 0.000156, MAE: 0.009766, R²: -0.0003
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14369 | val 0.15434
  Epoch 011 - train 0.13863 | val 0.15517
  Regression -> MSE: 0.000272, MAE: 0.013091, R²: -0.0006
  Directional -> Accuracy: 0.6053, MCC: 0.0838, F1: 0.7321

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13138 | val 0.19332
  Epoch 011 - train 0.12950 | val 0.19173
  Regression -> MSE: 0.000150, MAE: 0.008763, R²: -0.0015
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15160 | val 0.21505
  Epoch 011 - train 0.14470 | val 0.21517
  Regression -> MSE: 0.000251, MAE: 0.011308, R²: -0.1072
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13355 | val 0.14889
  Epoch 011 - train 0.13919 | val 0.14922
  Regression -> MSE: 0.000147, MAE: 0.008566, R²: -0.0237
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13014 | val 0.14536
  Epoch 011 - train 0.12606 | val 0.14552
  Regression -> MSE: 0.000171, MAE: 0.010247, R²: -0.0322
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6452

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14735 | val 0.16143
  Epoch 011 - train 0.14919 | val 0.16089
  Regression -> MSE: 0.000086, MAE: 0.007073, R²: -0.0082
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15059 | val 0.15175
  Epoch 011 - train 0.13769 | val 0.15170
  Regression -> MSE: 0.000216, MAE: 0.010997, R²: -0.0189
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13666 | val 0.10499
  Epoch 014 - train 0.12860 | val 0.10529
  Regression -> MSE: 0.000101, MAE: 0.008368, R²: -0.0919
  Directional -> Accuracy: 0.3750, MCC: -0.2811, F1: 0.4615

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13700 | val 0.10044
  Epoch 011 - train 0.12554 | val 0.10082
  Regression -> MSE: 0.000106, MAE: 0.008901, R²: -0.0318
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14286 | val 0.12026
  Epoch 011 - train 0.13774 | val 0.12018
  Regression -> MSE: 0.000237, MAE: 0.012731, R²: -0.0243
  Directional -> Accuracy: 0.5581, MCC: 0.0573, F1: 0.6545

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14199 | val 0.16973
  Epoch 011 - train 0.13887 | val 0.16936
  Regression -> MSE: 0.000170, MAE: 0.007855, R²: -0.0186
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13756 | val 0.10835
  Epoch 011 - train 0.14439 | val 0.10862
  Regression -> MSE: 0.000237, MAE: 0.011849, R²: -0.0032
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13752 | val 0.19409
  Epoch 011 - train 0.13799 | val 0.19450
  Regression -> MSE: 0.000231, MAE: 0.009892, R²: -0.0012
  Directional -> Accuracy: 0.4419, MCC: -0.2093, F1: 0.0769

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13963 | val 0.16044
  Epoch 011 - train 0.14221 | val 0.16200
  Regression -> MSE: 0.000138, MAE: 0.008350, R²: -0.0212
  Directional -> Accuracy: 0.4419, MCC: -0.0933, F1: 0.2500

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15865 | val 0.15413
  Epoch 011 - train 0.14942 | val 0.15408
  Regression -> MSE: 0.000195, MAE: 0.010521, R²: -0.0374
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13688 | val 0.17264
  Epoch 011 - train 0.14070 | val 0.17166
  Regression -> MSE: 0.000271, MAE: 0.011036, R²: -0.0360
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13269 | val 0.10775
  Epoch 011 - train 0.13039 | val 0.10895
  Regression -> MSE: 0.000167, MAE: 0.010327, R²: -0.0014
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12426 | val 0.12930
  Epoch 011 - train 0.13541 | val 0.12994
  Regression -> MSE: 0.000185, MAE: 0.010445, R²: -0.0299
  Directional -> Accuracy: 0.4318, MCC: -0.1288, F1: 0.5098

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13477 | val 0.11640
  Epoch 011 - train 0.14177 | val 0.11641
  Regression -> MSE: 0.000348, MAE: 0.011795, R²: -0.0156
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14402 | val 0.07736
  Epoch 011 - train 0.14794 | val 0.07720
  Regression -> MSE: 0.000117, MAE: 0.008277, R²: -0.1164
  Directional -> Accuracy: 0.6047, MCC: 0.2379, F1: 0.5143

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13165 | val 0.17287
  Epoch 011 - train 0.14120 | val 0.17311
  Regression -> MSE: 0.000218, MAE: 0.011311, R²: 0.0005
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13844 | val 0.23299
  Epoch 011 - train 0.14241 | val 0.23389
  Regression -> MSE: 0.000081, MAE: 0.007022, R²: -0.0466
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13714 | val 0.09507
  Epoch 020 - train 0.13678 | val 0.09187
  Epoch 024 - train 0.13804 | val 0.09118
  Regression -> MSE: 0.000335, MAE: 0.014366, R²: -0.0898
  Directional -> Accuracy: 0.4082, MCC: -0.1424, F1: 0.3830

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14510 | val 0.08088
  Epoch 011 - train 0.16220 | val 0.08164
  Regression -> MSE: 0.000245, MAE: 0.011410, R²: -0.0061
  Directional -> Accuracy: 0.5000, MCC: -0.0326, F1: 0.6122

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12776 | val 0.15468
  Epoch 011 - train 0.12911 | val 0.15484
  Regression -> MSE: 0.000081, MAE: 0.007126, R²: -0.0055
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13960 | val 0.15370
  Epoch 020 - train 0.14323 | val 0.14954
  Epoch 028 - train 0.14442 | val 0.14890
  Regression -> MSE: 0.000314, MAE: 0.014914, R²: -0.0222
  Directional -> Accuracy: 0.5106, MCC: 0.0237, F1: 0.4889

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.15655 | val 0.13731
  Epoch 011 - train 0.13195 | val 0.13753
  Regression -> MSE: 0.000099, MAE: 0.007213, R²: -0.0095
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14566 | val 0.14338
  Epoch 011 - train 0.14502 | val 0.14349
  Regression -> MSE: 0.000174, MAE: 0.010066, R²: -0.0108
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12735 | val 0.15732
  Epoch 011 - train 0.13354 | val 0.16030
  Regression -> MSE: 0.000223, MAE: 0.011704, R²: 0.0009
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13044 | val 0.14701
  Epoch 011 - train 0.13863 | val 0.14643
  Regression -> MSE: 0.000098, MAE: 0.008032, R²: -0.0633
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.14680 | val 0.19500
  Epoch 011 - train 0.15070 | val 0.19519
  Regression -> MSE: 0.000164, MAE: 0.010275, R²: -0.0035
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.14416 | val 0.15128
  Epoch 011 - train 0.14147 | val 0.15129
  Regression -> MSE: 0.000118, MAE: 0.009014, R²: -0.0222
  Directional -> Accuracy: 0.5000, MCC: -0.0709, F1: 0.6585

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.14738 | val 0.24077

[I 2026-02-24 02:11:38,967] Trial 107 finished with value: -0.011458315171716478 and parameters: {'feature_set': 'emotion', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 4.812701849272022e-06, 'weight_decay': 6.716363024058264e-07, 'lr_patience': 5, 'lr_factor': 0.8, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.1855483172774834, 'early_stopping_min_delta': 0.003517531391245174}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 011 - train 0.14825 | val 0.24070
  Regression -> MSE: 0.000252, MAE: 0.012554, R²: -0.0644
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.21351 | val 0.27023
  Epoch 020 - train 0.22073 | val 0.26989
  Epoch 023 - train 0.22170 | val 0.26985
  Regression -> MSE: 0.000252, MAE: 0.012688, R²: -0.0164
  Directional -> Accuracy: 0.4416, MCC: -0.0745, F1: 0.5743

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.23416 | val 0.23171
  Epoch 020 - train 0.22831 | val 0.23179
  Epoch 021 - train 0.21785 | val 0.23169
  Regression -> MSE: 0.000702, MAE: 0.019542, R²: -0.0256
  Directional -> Accuracy: 0.5652, MCC: 0.0280, F1: 0.7143

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.24061 | val 0.34468
  Epoch 020 - train 0.22559 | val 0.34556
  Epoch 021 - train 0.23286 | val 0.34552
  Regression -> MSE: 0.000303, MAE: 0.014189, R²: 0.0235
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.17902 | val 0.22436
  Epoch 020 - train 0.19143 | val 0.22037
  Epoch 021 - train 0.19068 | val 0.22006
  Regression -> MSE: 0.000387, MAE: 0.015185, R²: -0.1074
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.23012 | val 0.22733
  Epoch 020 - train 0.25271 | val 0.22719
  Epoch 021 - train 0.24670 | val 0.22713
  Regression -> MSE: 0.000217, MAE: 0.010799, R²: -0.0668
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.21650 | val 0.39513
  Epoch 020 - train 0.21231 | val 0.39421
  Epoch 021 - train 0.21431 | val 0.39412
  Regression -> MSE: 0.000570, MAE: 0.018376, R²: -0.0267
  Directional -> Accuracy: 0.5319, MCC: 0.1506, F1: 0.0833

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.23851 | val 0.26472
  Epoch 020 - train 0.25077 | val 0.26365
  Epoch 021 - train 0.24425 | val 0.26359
  Regression -> MSE: 0.000251, MAE: 0.012228, R²: -0.0223
  Directional -> Accuracy: 0.5217, MCC: 0.0026, F1: 0.4000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.22836 | val 0.28053
  Epoch 020 - train 0.23115 | val 0.28115
  Epoch 021 - train 0.22511 | val 0.28116
  Regression -> MSE: 0.000630, MAE: 0.019817, R²: -0.0537
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.21418 | val 0.23390
  Epoch 020 - train 0.20172 | val 0.23413
  Epoch 026 - train 0.22122 | val 0.23419
  Regression -> MSE: 0.000420, MAE: 0.016592, R²: -0.0941
  Directional -> Accuracy: 0.5306, MCC: -0.0594, F1: 0.0800

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.22699 | val 0.29130
  Epoch 020 - train 0.22711 | val 0.28939
  Epoch 021 - train 0.21806 | val 0.28921
  Regression -> MSE: 0.000244, MAE: 0.012457, R²: -0.0125
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.21162 | val 0.33242
  Epoch 020 - train 0.22086 | val 0.33375
  Epoch 021 - train 0.21956 | val 0.33378
  Regression -> MSE: 0.000307, MAE: 0.013745, R²: 0.0122
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.22461 | val 0.24917
  Epoch 020 - train 0.22643 | val 0.24970
  Epoch 021 - train 0.22615 | val 0.24972
  Regression -> MSE: 0.000695, MAE: 0.019702, R²: -0.0262
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6420

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.23353 | val 0.22374
  Epoch 020 - train 0.22900 | val 0.22355
  Epoch 021 - train 0.23089 | val 0.22341
  Regression -> MSE: 0.000144, MAE: 0.009431, R²: -0.0413
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.22011 | val 0.28769
  Epoch 020 - train 0.20951 | val 0.28754
  Epoch 023 - train 0.20230 | val 0.28735
  Regression -> MSE: 0.000232, MAE: 0.010929, R²: -0.0307
  Directional -> Accuracy: 0.4426, MCC: -0.1136, F1: 0.4138

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.23422 | val 0.48594
  Epoch 020 - train 0.24693 | val 0.48642
  Epoch 021 - train 0.22680 | val 0.48631
  Regression -> MSE: 0.000390, MAE: 0.016078, R²: -0.0760
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.22768 | val 0.20943
  Epoch 020 - train 0.22632 | val 0.20908
  Epoch 021 - train 0.22647 | val 0.20907
  Regression -> MSE: 0.000113, MAE: 0.007983, R²: -0.0468
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.22517 | val 0.36139
  Epoch 020 - train 0.22539 | val 0.36122
  Epoch 021 - train 0.23969 | val 0.36118
  Regression -> MSE: 0.000164, MAE: 0.010038, R²: -0.0548
  Directional -> Accuracy: 0.5424, MCC: 0.0656, F1: 0.6087

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.23837 | val 0.30300
  Epoch 020 - train 0.24215 | val 0.30227
  Epoch 021 - train 0.23611 | val 0.30220
  Regression -> MSE: 0.000348, MAE: 0.015535, R²: -0.2797
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.19714 | val 0.28073
  Epoch 020 - train 0.20027 | val 0.28053
  Epoch 021 - train 0.19208 | val 0.28053
  Regression -> MSE: 0.000158, MAE: 0.008945, R²: -0.0594
  Directional -> Accuracy: 0.5231, MCC: 0.1873, F1: 0.3922

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.22978 | val 0.33690
  Epoch 020 - train 0.23106 | val 0.33340
  Epoch 021 - train 0.22633 | val 0.33315
  Regression -> MSE: 0.000225, MAE: 0.010855, R²: 0.0039
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.22222 | val 0.28913
  Epoch 020 - train 0.23149 | val 0.28948
  Epoch 021 - train 0.22974 | val 0.28948
  Regression -> MSE: 0.000149, MAE: 0.008688, R²: -0.0412
  Directional -> Accuracy: 0.4792, MCC: 0.0847, F1: 0.4186

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.21321 | val 0.26319
  Epoch 020 - train 0.21163 | val 0.26318
  Epoch 021 - train 0.21613 | val 0.26317
  Regression -> MSE: 0.000163, MAE: 0.010335, R²: 0.0155
  Directional -> Accuracy: 0.4848, MCC: -0.1240, F1: 0.6531

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.25159 | val 0.28498
  Epoch 020 - train 0.25293 | val 0.28431
  Epoch 021 - train 0.24506 | val 0.28423
  Regression -> MSE: 0.000100, MAE: 0.007775, R²: -0.1786
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.21722 | val 0.25961
  Epoch 020 - train 0.20299 | val 0.25949
  Epoch 021 - train 0.21223 | val 0.25950
  Regression -> MSE: 0.000213, MAE: 0.011015, R²: -0.0071
  Directional -> Accuracy: 0.5303, MCC: 0.0343, F1: 0.3404

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.20927 | val 0.21103
  Epoch 020 - train 0.20625 | val 0.21066
  Epoch 021 - train 0.21711 | val 0.21063
  Regression -> MSE: 0.000093, MAE: 0.008069, R²: -0.0114
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.22560 | val 0.17168
  Epoch 020 - train 0.24027 | val 0.18115
  Epoch 021 - train 0.24245 | val 0.18122
  Regression -> MSE: 0.000102, MAE: 0.008740, R²: 0.0079
  Directional -> Accuracy: 0.5000, MCC: 0.1274, F1: 0.6102

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.24389 | val 0.26974
  Epoch 020 - train 0.23755 | val 0.27180
  Epoch 021 - train 0.25602 | val 0.27163
  Regression -> MSE: 0.000236, MAE: 0.012622, R²: -0.0184
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.21190 | val 0.26417
  Epoch 020 - train 0.21502 | val 0.26402
  Epoch 021 - train 0.22158 | val 0.26400
  Regression -> MSE: 0.000175, MAE: 0.008168, R²: -0.0510
  Directional -> Accuracy: 0.5439, MCC: -0.1181, F1: 0.7045

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22116 | val 0.18016
  Epoch 020 - train 0.23279 | val 0.18285
  Epoch 021 - train 0.23125 | val 0.18285
  Regression -> MSE: 0.000238, MAE: 0.011963, R²: -0.0065
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.22699 | val 0.33179
  Epoch 020 - train 0.21568 | val 0.33227
  Epoch 021 - train 0.23067 | val 0.33227
  Regression -> MSE: 0.000231, MAE: 0.009890, R²: -0.0018
  Directional -> Accuracy: 0.4651, MCC: -0.1084, F1: 0.2069

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.22282 | val 0.26052
  Epoch 020 - train 0.23816 | val 0.26396
  Epoch 021 - train 0.23113 | val 0.26397
  Regression -> MSE: 0.000142, MAE: 0.008322, R²: -0.0500
  Directional -> Accuracy: 0.5116, MCC: 0.0023, F1: 0.5882

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.21239 | val 0.26782
  Epoch 020 - train 0.22254 | val 0.26790
  Epoch 021 - train 0.22913 | val 0.26790
  Regression -> MSE: 0.000193, MAE: 0.010496, R²: -0.0241
  Directional -> Accuracy: 0.4400, MCC: -0.0911, F1: 0.2632

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.20940 | val 0.26123
  Epoch 020 - train 0.19060 | val 0.26050
  Epoch 021 - train 0.20333 | val 0.26042
  Regression -> MSE: 0.000261, MAE: 0.010631, R²: 0.0021
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.19794 | val 0.22400
  Epoch 020 - train 0.20927 | val 0.25195
  Epoch 021 - train 0.20015 | val 0.25255
  Regression -> MSE: 0.000176, MAE: 0.010561, R²: -0.0532
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.19742 | val 0.21144
  Epoch 020 - train 0.19926 | val 0.21189
  Epoch 021 - train 0.21046 | val 0.21191
  Regression -> MSE: 0.000187, MAE: 0.010623, R²: -0.0416
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.21562 | val 0.20937
  Epoch 020 - train 0.21170 | val 0.20853
  Epoch 021 - train 0.21285 | val 0.20847
  Regression -> MSE: 0.000339, MAE: 0.011798, R²: 0.0093
  Directional -> Accuracy: 0.5672, MCC: 0.0948, F1: 0.6506

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.24390 | val 0.12293
  Epoch 020 - train 0.24970 | val 0.12258
  Epoch 021 - train 0.25017 | val 0.12258
  Regression -> MSE: 0.000116, MAE: 0.008488, R²: -0.1037
  Directional -> Accuracy: 0.4186, MCC: -0.2592, F1: 0.5763

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.22771 | val 0.28690
  Epoch 020 - train 0.22224 | val 0.28726
  Epoch 021 - train 0.23000 | val 0.28728
  Regression -> MSE: 0.000224, MAE: 0.011445, R²: -0.0260
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.23091 | val 0.43353
  Epoch 020 - train 0.23385 | val 0.43548
  Epoch 021 - train 0.24322 | val 0.43547
  Regression -> MSE: 0.000078, MAE: 0.006963, R²: 0.0008
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.23976 | val 0.20757
  Epoch 020 - train 0.23224 | val 0.21586
  Epoch 021 - train 0.21829 | val 0.21590
  Regression -> MSE: 0.000362, MAE: 0.016003, R²: -0.1761
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.23822 | val 0.11367
  Epoch 020 - train 0.23657 | val 0.11264
  Epoch 021 - train 0.22640 | val 0.11264
  Regression -> MSE: 0.000254, MAE: 0.011553, R²: -0.0400
  Directional -> Accuracy: 0.4737, MCC: -0.1217, F1: 0.6154

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.20902 | val 0.25161
  Epoch 020 - train 0.21917 | val 0.25158
  Epoch 021 - train 0.20968 | val 0.25158
  Regression -> MSE: 0.000084, MAE: 0.007012, R²: -0.0420
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.20881 | val 0.26163
  Epoch 020 - train 0.20108 | val 0.26137
  Epoch 021 - train 0.21813 | val 0.26136
  Regression -> MSE: 0.000309, MAE: 0.014473, R²: -0.0070
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.23115 | val 0.21345
  Epoch 020 - train 0.20814 | val 0.21139
  Epoch 028 - train 0.20552 | val 0.21153
  Regression -> MSE: 0.000101, MAE: 0.007399, R²: -0.0258
  Directional -> Accuracy: 0.5000, MCC: 0.0063, F1: 0.5217

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.23436 | val 0.24965
  Epoch 020 - train 0.23553 | val 0.25157
  Epoch 021 - train 0.24322 | val 0.25160
  Regression -> MSE: 0.000174, MAE: 0.009512, R²: -0.0107
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 02:12:36,547] Trial 108 finished with value: -0.01159595407029705 and parameters: {'feature_set': 'all_nlp', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 3.6948249514449085e-06, 'weight_decay': 1.5865594480055703e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.34016909355450164, 'early_stopping_min_delta': 0.006460076082226291}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.25700 | val 0.30610
  Epoch 021 - train 0.23869 | val 0.30608
  Regression -> MSE: 0.000237, MAE: 0.012512, R²: -0.0005
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10896 | val 0.14079
  Epoch 020 - train 0.11026 | val 0.13978
  Epoch 021 - train 0.10507 | val 0.13957
  Regression -> MSE: 0.000261, MAE: 0.013028, R²: -0.0542
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11061 | val 0.09412
  Epoch 020 - train 0.10531 | val 0.09399
  Epoch 021 - train 0.11679 | val 0.09396
  Regression -> MSE: 0.000684, MAE: 0.019309, R²: 0.0012
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12333 | val 0.18974
  Epoch 020 - train 0.11346 | val 0.18970
  Epoch 021 - train 0.11691 | val 0.18886
  Regression -> MSE: 0.000332, MAE: 0.014663, R²: -0.0718
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10182 | val 0.15915
  Epoch 020 - train 0.10311 | val 0.15388
  Epoch 021 - train 0.10072 | val 0.15291
  Regression -> MSE: 0.000349, MAE: 0.014580, R²: -0.0000
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10398 | val 0.09830
  Epoch 020 - train 0.10806 | val 0.09740
  Epoch 021 - train 0.10359 | val 0.09675
  Regression -> MSE: 0.000204, MAE: 0.010058, R²: -0.0001
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10983 | val 0.25455
  Epoch 020 - train 0.10734 | val 0.25551
  Epoch 021 - train 0.11185 | val 0.25649
  Regression -> MSE: 0.000607, MAE: 0.019154, R²: -0.0933
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10111 | val 0.12020
  Epoch 020 - train 0.11337 | val 0.12042
  Epoch 021 - train 0.10820 | val 0.12072
  Regression -> MSE: 0.000246, MAE: 0.012207, R²: -0.0026
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12077 | val 0.14444
  Epoch 020 - train 0.10652 | val 0.14507
  Epoch 021 - train 0.10965 | val 0.14387
  Regression -> MSE: 0.000664, MAE: 0.020468, R²: -0.1119
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11363 | val 0.11778
  Epoch 020 - train 0.10443 | val 0.11826
  Epoch 021 - train 0.09984 | val 0.11835
  Regression -> MSE: 0.000399, MAE: 0.016037, R²: -0.0404
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11201 | val 0.13753
  Epoch 020 - train 0.11296 | val 0.13908
  Epoch 021 - train 0.10288 | val 0.13942
  Regression -> MSE: 0.000245, MAE: 0.011664, R²: -0.0141
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11129 | val 0.13079
  Epoch 020 - train 0.10811 | val 0.13086
  Epoch 026 - train 0.10307 | val 0.13186
  Regression -> MSE: 0.000395, MAE: 0.014923, R²: -0.2695
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10872 | val 0.12336
  Epoch 020 - train 0.12025 | val 0.12383
  Epoch 021 - train 0.11569 | val 0.12404
  Regression -> MSE: 0.000686, MAE: 0.019563, R²: -0.0126
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12073 | val 0.15272
  Epoch 020 - train 0.11121 | val 0.15259
  Epoch 021 - train 0.11997 | val 0.15286
  Regression -> MSE: 0.000138, MAE: 0.009038, R²: -0.0010
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09940 | val 0.12686
  Epoch 020 - train 0.10053 | val 0.12653
  Epoch 026 - train 0.09459 | val 0.12627
  Regression -> MSE: 0.000228, MAE: 0.010801, R²: -0.0139
  Directional -> Accuracy: 0.4918, MCC: -0.0455, F1: 0.6353

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11028 | val 0.19256
  Epoch 020 - train 0.11145 | val 0.19302
  Epoch 021 - train 0.10333 | val 0.19357
  Regression -> MSE: 0.000367, MAE: 0.015913, R²: -0.0142
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11319 | val 0.11052
  Epoch 020 - train 0.11990 | val 0.11021
  Epoch 021 - train 0.11546 | val 0.10994
  Regression -> MSE: 0.000112, MAE: 0.007967, R²: -0.0348
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11003 | val 0.16379
  Epoch 020 - train 0.10497 | val 0.16248
  Epoch 021 - train 0.10844 | val 0.16249
  Regression -> MSE: 0.000155, MAE: 0.009562, R²: 0.0043
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10827 | val 0.10958
  Epoch 020 - train 0.11149 | val 0.10981
  Epoch 021 - train 0.11170 | val 0.11223
  Regression -> MSE: 0.000275, MAE: 0.013206, R²: -0.0102
  Directional -> Accuracy: 0.6053, MCC: 0.1287, F1: 0.7059

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10291 | val 0.12740
  Epoch 020 - train 0.10008 | val 0.12544
  Epoch 021 - train 0.09069 | val 0.12557
  Regression -> MSE: 0.000160, MAE: 0.008898, R²: -0.0700
  Directional -> Accuracy: 0.4923, MCC: -0.0885, F1: 0.6024

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11306 | val 0.15586
  Epoch 020 - train 0.11045 | val 0.15485
  Epoch 021 - train 0.10703 | val 0.15588
  Regression -> MSE: 0.000242, MAE: 0.011110, R²: -0.0700
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11001 | val 0.13957
  Epoch 020 - train 0.11204 | val 0.14215
  Epoch 021 - train 0.11426 | val 0.13882
  Regression -> MSE: 0.000144, MAE: 0.008327, R²: -0.0027
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11017 | val 0.11802
  Epoch 020 - train 0.11044 | val 0.11765
  Epoch 021 - train 0.11181 | val 0.11746
  Regression -> MSE: 0.000172, MAE: 0.010290, R²: -0.0412
  Directional -> Accuracy: 0.4394, MCC: -0.1213, F1: 0.4308

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10986 | val 0.12148
  Epoch 020 - train 0.10560 | val 0.11928
  Epoch 021 - train 0.10741 | val 0.11918
  Regression -> MSE: 0.000091, MAE: 0.007330, R²: -0.0637
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10883 | val 0.12654
  Epoch 020 - train 0.10587 | val 0.12545
  Epoch 021 - train 0.10946 | val 0.12634
  Regression -> MSE: 0.000212, MAE: 0.011098, R²: -0.0004
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11315 | val 0.09288
  Epoch 020 - train 0.11187 | val 0.09249
  Epoch 021 - train 0.11957 | val 0.09120
  Regression -> MSE: 0.000107, MAE: 0.008404, R²: -0.1652
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10592 | val 0.10481
  Epoch 020 - train 0.10591 | val 0.11834
  Epoch 021 - train 0.10913 | val 0.12135
  Regression -> MSE: 0.000105, MAE: 0.008824, R²: -0.0138
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11692 | val 0.14414
  Epoch 020 - train 0.11745 | val 0.14526
  Epoch 021 - train 0.12334 | val 0.14705
  Regression -> MSE: 0.000236, MAE: 0.012696, R²: -0.0181
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10985 | val 0.13171
  Epoch 020 - train 0.11282 | val 0.13048
  Epoch 021 - train 0.10991 | val 0.13067
  Regression -> MSE: 0.000169, MAE: 0.007847, R²: -0.0148
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12010 | val 0.08430
  Epoch 020 - train 0.12317 | val 0.08336
  Epoch 021 - train 0.11940 | val 0.08302
  Regression -> MSE: 0.000236, MAE: 0.011878, R²: 0.0004
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11057 | val 0.16051
  Epoch 020 - train 0.10888 | val 0.16210
  Epoch 021 - train 0.10467 | val 0.16171
  Regression -> MSE: 0.000234, MAE: 0.010068, R²: -0.0133
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11746 | val 0.12084
  Epoch 020 - train 0.10983 | val 0.12191
  Epoch 021 - train 0.10871 | val 0.12252
  Regression -> MSE: 0.000136, MAE: 0.008171, R²: -0.0041
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10763 | val 0.13219
  Epoch 020 - train 0.10970 | val 0.13229
  Epoch 021 - train 0.11865 | val 0.13240
  Regression -> MSE: 0.000198, MAE: 0.010621, R²: -0.0509
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09838 | val 0.11860
  Epoch 020 - train 0.09878 | val 0.11721
  Epoch 021 - train 0.09561 | val 0.11776
  Regression -> MSE: 0.000276, MAE: 0.010755, R²: -0.0525
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10780 | val 0.08560
  Epoch 020 - train 0.10426 | val 0.08542
  Epoch 021 - train 0.10511 | val 0.08605
  Regression -> MSE: 0.000167, MAE: 0.010370, R²: -0.0027
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10486 | val 0.09771
  Epoch 020 - train 0.09715 | val 0.09857
  Epoch 021 - train 0.09377 | val 0.09878
  Regression -> MSE: 0.000184, MAE: 0.010466, R²: -0.0204
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10208 | val 0.09228
  Epoch 020 - train 0.10290 | val 0.09189
  Epoch 021 - train 0.11136 | val 0.09209
  Regression -> MSE: 0.000344, MAE: 0.011678, R²: -0.0036
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12002 | val 0.07244
  Epoch 020 - train 0.12975 | val 0.07352
  Epoch 021 - train 0.11872 | val 0.07406
  Regression -> MSE: 0.000122, MAE: 0.008381, R²: -0.1628
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10759 | val 0.14327
  Epoch 020 - train 0.11498 | val 0.14235
  Epoch 021 - train 0.10205 | val 0.14289
  Regression -> MSE: 0.000221, MAE: 0.011373, R²: -0.0096
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11292 | val 0.16639
  Epoch 020 - train 0.11262 | val 0.16809
  Epoch 021 - train 0.11632 | val 0.16733
  Regression -> MSE: 0.000096, MAE: 0.007665, R²: -0.2403
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10342 | val 0.08424
  Epoch 020 - train 0.10046 | val 0.08467
  Epoch 021 - train 0.10257 | val 0.08463
  Regression -> MSE: 0.000332, MAE: 0.015083, R²: -0.0806
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12190 | val 0.07030
  Epoch 020 - train 0.12573 | val 0.08866
  Epoch 021 - train 0.11697 | val 0.08838
  Regression -> MSE: 0.000245, MAE: 0.011565, R²: -0.0057
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10791 | val 0.12648
  Epoch 020 - train 0.10829 | val 0.12595
  Epoch 021 - train 0.11265 | val 0.12605
  Regression -> MSE: 0.000081, MAE: 0.007090, R²: -0.0047
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10895 | val 0.12368
  Epoch 020 - train 0.11472 | val 0.12414
  Epoch 021 - train 0.11339 | val 0.12424
  Regression -> MSE: 0.000309, MAE: 0.014531, R²: -0.0079
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09820 | val 0.10573
  Epoch 020 - train 0.10830 | val 0.10718
  Epoch 021 - train 0.10456 | val 0.10718
  Regression -> MSE: 0.000098, MAE: 0.007233, R²: 0.0001
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12131 | val 0.13847
  Epoch 020 - train 0.11892 | val 0.15160
  Epoch 021 - train 0.11982 | val 0.15120
  Regression -> MSE: 0.000171, MAE: 0.009668, R²: 0.0038
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10261 | val 0.15231
  Epoch 020 - train 0.09910 | val 0.15183
  Epoch 021 - train 0.09602 | val 0.15084
  Regression -> MSE: 0.000223, MAE: 0.011708, R²: 0.0011
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11528 | val 0.11638
  Epoch 020 - train 0.10995 | val 0.11635
  Epoch 021 - train 0.10928 | val 0.11599

[I 2026-02-24 02:14:51,083] Trial 109 finished with value: -0.011492934893450713 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 1.6078190689241603e-05, 'weight_decay': 1.7542598535193498e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.14431086062825338, 'early_stopping_min_delta': 0.00824724557032314}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.10722 | val 0.14743
  Epoch 021 - train 0.11378 | val 0.14698
  Regression -> MSE: 0.000237, MAE: 0.012334, R²: -0.0007
  Directional -> Accuracy: 0.4918, MCC: 0.0196, F1: 0.6076

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.17173 | val 0.23234
  Epoch 020 - train 0.16501 | val 0.23057
  Epoch 021 - train 0.17459 | val 0.23055
  Regression -> MSE: 0.000258, MAE: 0.012944, R²: -0.0425
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16426 | val 0.16688
  Epoch 020 - train 0.17207 | val 0.17224
  Epoch 021 - train 0.16691 | val 0.17201
  Regression -> MSE: 0.000691, MAE: 0.019464, R²: -0.0089
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.18379 | val 0.28652
  Epoch 020 - train 0.17587 | val 0.28934
  Epoch 021 - train 0.18477 | val 0.28915
  Regression -> MSE: 0.000311, MAE: 0.014451, R²: -0.0021
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14926 | val 0.29304
  Epoch 020 - train 0.14434 | val 0.27317
  Epoch 021 - train 0.13915 | val 0.27235
  Regression -> MSE: 0.000352, MAE: 0.014596, R²: -0.0083
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.17564 | val 0.18244
  Epoch 020 - train 0.17400 | val 0.18662
  Epoch 021 - train 0.17896 | val 0.18918
  Regression -> MSE: 0.000204, MAE: 0.010271, R²: -0.0012
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.17151 | val 0.33596
  Epoch 020 - train 0.17383 | val 0.32378
  Epoch 030 - train 0.16436 | val 0.32322
  Regression -> MSE: 0.000564, MAE: 0.018284, R²: -0.0163
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.17788 | val 0.21194
  Epoch 020 - train 0.18024 | val 0.21376
  Epoch 021 - train 0.17344 | val 0.21394
  Regression -> MSE: 0.000246, MAE: 0.012134, R²: -0.0025
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.18483 | val 0.22131
  Epoch 020 - train 0.17420 | val 0.22230
  Epoch 030 - train 0.17514 | val 0.22926
  Regression -> MSE: 0.000610, MAE: 0.019301, R²: -0.0203
  Directional -> Accuracy: 0.5682, MCC: -0.1269, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.18495 | val 0.21038
  Epoch 020 - train 0.16890 | val 0.21463
  Epoch 021 - train 0.17265 | val 0.21511
  Regression -> MSE: 0.000394, MAE: 0.015953, R²: -0.0273
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.18470 | val 0.24111
  Epoch 020 - train 0.17535 | val 0.23187
  Epoch 021 - train 0.17250 | val 0.23283
  Regression -> MSE: 0.000246, MAE: 0.011611, R²: -0.0186
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.17457 | val 0.28082
  Epoch 020 - train 0.16823 | val 0.28193
  Epoch 021 - train 0.16381 | val 0.28103
  Regression -> MSE: 0.000311, MAE: 0.013757, R²: -0.0002
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.19727 | val 0.22292
  Epoch 020 - train 0.18754 | val 0.22306
  Epoch 021 - train 0.17551 | val 0.22320
  Regression -> MSE: 0.000682, MAE: 0.019727, R²: -0.0065
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.18867 | val 0.18693
  Epoch 020 - train 0.18279 | val 0.19128
  Epoch 021 - train 0.18512 | val 0.19171
  Regression -> MSE: 0.000140, MAE: 0.009047, R²: -0.0100
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.17178 | val 0.22597
  Epoch 020 - train 0.15800 | val 0.21729
  Epoch 030 - train 0.14903 | val 0.21620
  Regression -> MSE: 0.000223, MAE: 0.010663, R²: 0.0078
  Directional -> Accuracy: 0.5574, MCC: 0.1151, F1: 0.5574

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.17411 | val 0.34863
  Epoch 020 - train 0.17773 | val 0.34816
  Epoch 021 - train 0.17558 | val 0.34807
  Regression -> MSE: 0.000367, MAE: 0.015962, R²: -0.0125
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.19256 | val 0.18793
  Epoch 020 - train 0.17730 | val 0.18935
  Epoch 021 - train 0.18071 | val 0.18930
  Regression -> MSE: 0.000112, MAE: 0.007983, R²: -0.0375
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.17934 | val 0.30402
  Epoch 020 - train 0.17477 | val 0.31112
  Epoch 021 - train 0.16345 | val 0.31190
  Regression -> MSE: 0.000162, MAE: 0.010178, R²: -0.0369
  Directional -> Accuracy: 0.4407, MCC: 0.1006, F1: 0.2667

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.17898 | val 0.17832
  Epoch 020 - train 0.17881 | val 0.18317
  Epoch 021 - train 0.17238 | val 0.18334
  Regression -> MSE: 0.000278, MAE: 0.013360, R²: -0.0199
  Directional -> Accuracy: 0.4342, MCC: -0.1644, F1: 0.5169

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.16040 | val 0.22362
  Epoch 020 - train 0.15448 | val 0.21827
  Epoch 030 - train 0.14871 | val 0.21741
  Regression -> MSE: 0.000173, MAE: 0.009496, R²: -0.1576
  Directional -> Accuracy: 0.5231, MCC: 0.0127, F1: 0.5974

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.17848 | val 0.24817
  Epoch 020 - train 0.17649 | val 0.24100
  Epoch 021 - train 0.18433 | val 0.24099
  Regression -> MSE: 0.000263, MAE: 0.011616, R²: -0.1604
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17763 | val 0.21670
  Epoch 020 - train 0.18215 | val 0.21865
  Epoch 021 - train 0.17736 | val 0.21901
  Regression -> MSE: 0.000144, MAE: 0.008412, R²: -0.0061
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.16544 | val 0.20550
  Epoch 020 - train 0.17029 | val 0.20438
  Epoch 021 - train 0.16160 | val 0.20363
  Regression -> MSE: 0.000169, MAE: 0.010245, R²: -0.0223
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.18310 | val 0.20432
  Epoch 020 - train 0.18265 | val 0.20344
  Epoch 021 - train 0.18267 | val 0.20341
  Regression -> MSE: 0.000092, MAE: 0.007365, R²: -0.0747
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.17539 | val 0.22267
  Epoch 020 - train 0.17288 | val 0.22331
  Epoch 021 - train 0.17201 | val 0.22285
  Regression -> MSE: 0.000213, MAE: 0.011052, R²: -0.0051
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.16425 | val 0.14291
  Epoch 020 - train 0.14706 | val 0.14245
  Epoch 027 - train 0.15251 | val 0.14288
  Regression -> MSE: 0.000095, MAE: 0.007903, R²: -0.0274
  Directional -> Accuracy: 0.5536, MCC: 0.1566, F1: 0.4898

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18948 | val 0.13352
  Epoch 020 - train 0.17290 | val 0.13289
  Epoch 021 - train 0.18085 | val 0.13297
  Regression -> MSE: 0.000105, MAE: 0.008858, R²: -0.0205
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.18845 | val 0.17622
  Epoch 020 - train 0.18278 | val 0.19514
  Epoch 021 - train 0.17257 | val 0.19461
  Regression -> MSE: 0.000236, MAE: 0.012715, R²: -0.0189
  Directional -> Accuracy: 0.5116, MCC: -0.1607, F1: 0.6667

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.17820 | val 0.20630
  Epoch 020 - train 0.16580 | val 0.20584
  Epoch 021 - train 0.17132 | val 0.20557
  Regression -> MSE: 0.000176, MAE: 0.007874, R²: -0.0574
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.19128 | val 0.15612
  Epoch 020 - train 0.18841 | val 0.16156
  Epoch 021 - train 0.19176 | val 0.16218
  Regression -> MSE: 0.000241, MAE: 0.012071, R²: -0.0173
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.18124 | val 0.27850
  Epoch 020 - train 0.18346 | val 0.28906
  Epoch 021 - train 0.17025 | val 0.28906
  Regression -> MSE: 0.000231, MAE: 0.009896, R²: -0.0024
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18164 | val 0.19504
  Epoch 020 - train 0.19911 | val 0.20649
  Epoch 021 - train 0.17965 | val 0.20743
  Regression -> MSE: 0.000136, MAE: 0.008196, R²: -0.0049
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.17150 | val 0.21851
  Epoch 020 - train 0.17702 | val 0.22304
  Epoch 021 - train 0.17807 | val 0.22317
  Regression -> MSE: 0.000189, MAE: 0.010462, R²: -0.0020
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15764 | val 0.19180
  Epoch 020 - train 0.16116 | val 0.19262
  Epoch 024 - train 0.15208 | val 0.19245
  Regression -> MSE: 0.000275, MAE: 0.010935, R²: -0.0492
  Directional -> Accuracy: 0.5342, MCC: 0.1465, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.18495 | val 0.15806
  Epoch 020 - train 0.15091 | val 0.15719
  Epoch 021 - train 0.16522 | val 0.15668
  Regression -> MSE: 0.000173, MAE: 0.010413, R²: -0.0351
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.18257 | val 0.17551
  Epoch 020 - train 0.15921 | val 0.17368
  Epoch 021 - train 0.16841 | val 0.17330
  Regression -> MSE: 0.000180, MAE: 0.010367, R²: -0.0017
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16393 | val 0.16439
  Epoch 020 - train 0.15560 | val 0.16634
  Epoch 021 - train 0.16585 | val 0.16615
  Regression -> MSE: 0.000342, MAE: 0.011797, R²: 0.0004
  Directional -> Accuracy: 0.5672, MCC: 0.0697, F1: 0.6813

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18942 | val 0.10799
  Epoch 020 - train 0.18230 | val 0.11693
  Epoch 021 - train 0.17560 | val 0.11722
  Regression -> MSE: 0.000119, MAE: 0.008352, R²: -0.1329
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.18860 | val 0.23366
  Epoch 020 - train 0.17121 | val 0.23351
  Epoch 021 - train 0.17704 | val 0.23368
  Regression -> MSE: 0.000219, MAE: 0.011277, R²: -0.0006
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.17171 | val 0.31955
  Epoch 020 - train 0.17382 | val 0.34193
  Epoch 021 - train 0.16946 | val 0.34296
  Regression -> MSE: 0.000089, MAE: 0.007389, R²: -0.1449
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.18083 | val 0.14269
  Epoch 020 - train 0.15623 | val 0.13420
  Epoch 030 - train 0.16334 | val 0.13002
  Regression -> MSE: 0.000446, MAE: 0.018094, R²: -0.4502
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.19971 | val 0.10065
  Epoch 020 - train 0.18783 | val 0.10537
  Epoch 021 - train 0.17701 | val 0.10622
  Regression -> MSE: 0.000251, MAE: 0.011524, R²: -0.0281
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16745 | val 0.21267
  Epoch 020 - train 0.16709 | val 0.21138
  Epoch 021 - train 0.16827 | val 0.21176
  Regression -> MSE: 0.000086, MAE: 0.007082, R²: -0.0658
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.18039 | val 0.20502
  Epoch 020 - train 0.17296 | val 0.22471
  Epoch 027 - train 0.16882 | val 0.22807
  Regression -> MSE: 0.000314, MAE: 0.014565, R²: -0.0219
  Directional -> Accuracy: 0.4894, MCC: -0.0617, F1: 0.6364

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.18961 | val 0.19584
  Epoch 020 - train 0.18081 | val 0.19843
  Epoch 021 - train 0.17742 | val 0.19803
  Regression -> MSE: 0.000099, MAE: 0.007223, R²: -0.0067
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.19089 | val 0.20463
  Epoch 020 - train 0.18679 | val 0.21414
  Epoch 021 - train 0.19085 | val 0.21508
  Regression -> MSE: 0.000175, MAE: 0.010153, R²: -0.0187
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.16456 | val 0.18890
  Epoch 020 - train 0.15903 | val 0.20291
  Epoch 021 - train 0.15916 | val 0.20298
  Regression -> MSE: 0.000227, MAE: 0.011852, R²: -0.0177
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.16792 | val 0.20138
  Epoch 020 - train 0.16918 | val 0.20345
  Epoch 021 - train 0.17029 | val 0.20359
  Regression -> MSE: 0.000093, MAE: 0.007716, R²: -0.0116

[I 2026-02-24 02:16:22,796] Trial 110 finished with value: -0.011526037309165293 and parameters: {'feature_set': 'sentinment', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.0002587417182176061, 'weight_decay': 1.3180251519336122e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2686498798499176, 'early_stopping_min_delta': 0.006130081187614985}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.16955 | val 0.30771
  Epoch 021 - train 0.18675 | val 0.30557
  Regression -> MSE: 0.000240, MAE: 0.012324, R²: -0.0128
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12542 | val 0.15897
  Epoch 020 - train 0.12575 | val 0.15927
  Epoch 026 - train 0.13612 | val 0.15869
  Regression -> MSE: 0.000256, MAE: 0.012872, R²: -0.0337
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14024 | val 0.13336
  Epoch 020 - train 0.13311 | val 0.16311
  Epoch 021 - train 0.13936 | val 0.16352
  Regression -> MSE: 0.000689, MAE: 0.019438, R²: -0.0060
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13698 | val 0.19762
  Epoch 020 - train 0.13671 | val 0.19858
  Epoch 021 - train 0.14107 | val 0.19870
  Regression -> MSE: 0.000310, MAE: 0.014422, R²: 0.0010
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11546 | val 0.10873
  Epoch 020 - train 0.12192 | val 0.10663
  Epoch 021 - train 0.11771 | val 0.10675
  Regression -> MSE: 0.000357, MAE: 0.014717, R²: -0.0224
  Directional -> Accuracy: 0.5200, MCC: -0.0711, F1: 0.6727

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14059 | val 0.12771
  Epoch 020 - train 0.13906 | val 0.13108
  Epoch 021 - train 0.13971 | val 0.13205
  Regression -> MSE: 0.000206, MAE: 0.010111, R²: -0.0096
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.16320 | val 0.22279
  Epoch 020 - train 0.14231 | val 0.22390
  Epoch 021 - train 0.15190 | val 0.22420
  Regression -> MSE: 0.000558, MAE: 0.018221, R²: -0.0046
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14081 | val 0.14972
  Epoch 020 - train 0.13598 | val 0.14976
  Epoch 021 - train 0.13362 | val 0.14976
  Regression -> MSE: 0.000248, MAE: 0.011969, R²: -0.0119
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14144 | val 0.17129
  Epoch 020 - train 0.14356 | val 0.21508
  Epoch 021 - train 0.15539 | val 0.22006
  Regression -> MSE: 0.000639, MAE: 0.020068, R²: -0.0688
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13518 | val 0.14956
  Epoch 020 - train 0.13160 | val 0.15056
  Epoch 021 - train 0.13170 | val 0.15114
  Regression -> MSE: 0.000386, MAE: 0.016037, R²: -0.0065
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14652 | val 0.21462
  Epoch 020 - train 0.13449 | val 0.22603
  Epoch 021 - train 0.13596 | val 0.22619
  Regression -> MSE: 0.000242, MAE: 0.011869, R²: -0.0008
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12089 | val 0.17846
  Epoch 020 - train 0.12693 | val 0.18430
  Epoch 021 - train 0.13216 | val 0.18525
  Regression -> MSE: 0.000312, MAE: 0.013606, R²: -0.0048
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13136 | val 0.14088
  Epoch 020 - train 0.13561 | val 0.14353
  Epoch 021 - train 0.13780 | val 0.14351
  Regression -> MSE: 0.000678, MAE: 0.019512, R²: -0.0015
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13550 | val 0.12018
  Epoch 020 - train 0.13637 | val 0.13376
  Epoch 021 - train 0.13531 | val 0.13405
  Regression -> MSE: 0.000145, MAE: 0.009517, R²: -0.0498
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12595 | val 0.14634
  Epoch 020 - train 0.12334 | val 0.14531
  Epoch 030 - train 0.12602 | val 0.14513
  Regression -> MSE: 0.000227, MAE: 0.010809, R²: -0.0093
  Directional -> Accuracy: 0.4918, MCC: -0.0089, F1: 0.3111

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13785 | val 0.24420
  Epoch 020 - train 0.12826 | val 0.24181
  Epoch 021 - train 0.13017 | val 0.24217
  Regression -> MSE: 0.000366, MAE: 0.016322, R²: -0.0092
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14334 | val 0.12945
  Epoch 020 - train 0.14287 | val 0.12976
  Epoch 021 - train 0.13601 | val 0.12997
  Regression -> MSE: 0.000109, MAE: 0.008100, R²: -0.0063
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12554 | val 0.19082
  Epoch 020 - train 0.12853 | val 0.19414
  Epoch 021 - train 0.13593 | val 0.19391
  Regression -> MSE: 0.000161, MAE: 0.010129, R²: -0.0318
  Directional -> Accuracy: 0.4068, MCC: 0.0685, F1: 0.1463

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14691 | val 0.16781
  Epoch 020 - train 0.14256 | val 0.17566
  Epoch 021 - train 0.14074 | val 0.17518
  Regression -> MSE: 0.000280, MAE: 0.013436, R²: -0.0292
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14100 | val 0.19273
  Epoch 020 - train 0.13962 | val 0.19619
  Epoch 021 - train 0.14943 | val 0.19512
  Regression -> MSE: 0.000152, MAE: 0.008747, R²: -0.0132
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13853 | val 0.19320
  Epoch 020 - train 0.13337 | val 0.19393
  Epoch 021 - train 0.13715 | val 0.19381
  Regression -> MSE: 0.000228, MAE: 0.010909, R²: -0.0089
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12444 | val 0.15502
  Epoch 020 - train 0.13684 | val 0.17508
  Epoch 021 - train 0.13036 | val 0.17517
  Regression -> MSE: 0.000144, MAE: 0.008326, R²: -0.0035
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12449 | val 0.13777
  Epoch 020 - train 0.12195 | val 0.13819
  Epoch 021 - train 0.13033 | val 0.13791
  Regression -> MSE: 0.000185, MAE: 0.010424, R²: -0.1179
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14801 | val 0.14939
  Epoch 020 - train 0.13472 | val 0.15257
  Epoch 021 - train 0.14694 | val 0.15245
  Regression -> MSE: 0.000086, MAE: 0.007094, R²: -0.0096
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13571 | val 0.15157
  Epoch 020 - train 0.13887 | val 0.15167
  Epoch 021 - train 0.13274 | val 0.15091
  Regression -> MSE: 0.000212, MAE: 0.011236, R²: -0.0009
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12849 | val 0.10951
  Epoch 020 - train 0.12873 | val 0.11098
  Epoch 021 - train 0.12968 | val 0.11102
  Regression -> MSE: 0.000093, MAE: 0.008074, R²: -0.0077
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12801 | val 0.09899
  Epoch 020 - train 0.13438 | val 0.11121
  Epoch 021 - train 0.13309 | val 0.11292
  Regression -> MSE: 0.000110, MAE: 0.009020, R²: -0.0641
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13206 | val 0.13702
  Epoch 020 - train 0.13659 | val 0.19941
  Epoch 021 - train 0.14000 | val 0.19835
  Regression -> MSE: 0.000233, MAE: 0.012635, R²: -0.0083
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14121 | val 0.12988
  Epoch 020 - train 0.13535 | val 0.12876
  Epoch 029 - train 0.13007 | val 0.12869
  Regression -> MSE: 0.000254, MAE: 0.010699, R²: -0.5271
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13919 | val 0.10437
  Epoch 020 - train 0.13695 | val 0.12885
  Epoch 021 - train 0.13837 | val 0.13427
  Regression -> MSE: 0.000237, MAE: 0.011889, R²: -0.0030
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14375 | val 0.18788
  Epoch 020 - train 0.13454 | val 0.19847
  Epoch 021 - train 0.13659 | val 0.19875
  Regression -> MSE: 0.000230, MAE: 0.009863, R²: 0.0003
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13207 | val 0.14810
  Epoch 020 - train 0.12875 | val 0.15241
  Epoch 021 - train 0.14172 | val 0.15266
  Regression -> MSE: 0.000136, MAE: 0.008256, R²: -0.0095
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12830 | val 0.15654
  Epoch 020 - train 0.12986 | val 0.15957
  Epoch 021 - train 0.13366 | val 0.15953
  Regression -> MSE: 0.000189, MAE: 0.010467, R²: -0.0016
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13827 | val 0.15281
  Epoch 020 - train 0.12948 | val 0.15364
  Epoch 021 - train 0.13130 | val 0.15399
  Regression -> MSE: 0.000263, MAE: 0.010623, R²: -0.0031
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13568 | val 0.10106
  Epoch 020 - train 0.13961 | val 0.10560
  Epoch 021 - train 0.15138 | val 0.10732
  Regression -> MSE: 0.000167, MAE: 0.010366, R²: -0.0022
  Directional -> Accuracy: 0.5263, MCC: 0.0580, F1: 0.4000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13536 | val 0.12752
  Epoch 020 - train 0.13345 | val 0.13192
  Epoch 021 - train 0.12916 | val 0.13230
  Regression -> MSE: 0.000181, MAE: 0.010340, R²: -0.0041
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12452 | val 0.11900
  Epoch 020 - train 0.14668 | val 0.12039
  Epoch 021 - train 0.13888 | val 0.12032
  Regression -> MSE: 0.000347, MAE: 0.011732, R²: -0.0127
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14238 | val 0.08044
  Epoch 020 - train 0.14499 | val 0.07843
  Epoch 021 - train 0.13325 | val 0.07832
  Regression -> MSE: 0.000110, MAE: 0.008315, R²: -0.0452
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13376 | val 0.17725
  Epoch 020 - train 0.13727 | val 0.18545
  Epoch 021 - train 0.13780 | val 0.18571
  Regression -> MSE: 0.000222, MAE: 0.011410, R²: -0.0180
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13580 | val 0.21109
  Epoch 020 - train 0.13883 | val 0.22817
  Epoch 021 - train 0.13905 | val 0.22836
  Regression -> MSE: 0.000084, MAE: 0.007159, R²: -0.0843
  Directional -> Accuracy: 0.3830, MCC: -0.0508, F1: 0.0645

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13305 | val 0.09352
  Epoch 020 - train 0.12698 | val 0.09821
  Epoch 021 - train 0.12406 | val 0.09832
  Regression -> MSE: 0.000314, MAE: 0.014181, R²: -0.0204
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13381 | val 0.07465
  Epoch 020 - train 0.14065 | val 0.08502
  Epoch 021 - train 0.14084 | val 0.08810
  Regression -> MSE: 0.000248, MAE: 0.011545, R²: -0.0170
  Directional -> Accuracy: 0.4211, MCC: -0.1783, F1: 0.5000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13969 | val 0.14924
  Epoch 020 - train 0.13480 | val 0.14955
  Epoch 021 - train 0.14050 | val 0.14954
  Regression -> MSE: 0.000081, MAE: 0.007071, R²: -0.0021
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14679 | val 0.15187
  Epoch 020 - train 0.13397 | val 0.14940
  Epoch 030 - train 0.14477 | val 0.14974
  Regression -> MSE: 0.000304, MAE: 0.014386, R²: 0.0082
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13172 | val 0.13519
  Epoch 020 - train 0.11978 | val 0.14030
  Epoch 021 - train 0.13224 | val 0.14142
  Regression -> MSE: 0.000099, MAE: 0.007163, R²: -0.0102
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15302 | val 0.13853
  Epoch 020 - train 0.15464 | val 0.13032
  Epoch 030 - train 0.14131 | val 0.12973
  Regression -> MSE: 0.000175, MAE: 0.010060, R²: -0.0211
  Directional -> Accuracy: 0.3878, MCC: -0.1167, F1: 0.4828

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12552 | val 0.18928
  Epoch 020 - train 0.14066 | val 0.22318
  Epoch 021 - train 0.12660 | val 0.22229
  Regression -> MSE: 0.000223, MAE: 0.011725, R²: -0.0017
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13224 | val 0.14071
  Epoch 020 - train 0.13442 | val 0.14460
  Epoch 021 - train 0.12435 | val 0.14478

[I 2026-02-24 02:18:29,790] Trial 111 finished with value: -0.011483998479261251 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 4.763691898661949e-06, 'weight_decay': 2.3172243078540987e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.18010368595149887, 'early_stopping_min_delta': 0.007978443935659984}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.13684 | val 0.18599
  Epoch 021 - train 0.13500 | val 0.18574
  Regression -> MSE: 0.000237, MAE: 0.012394, R²: 0.0013
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07525 | val 0.09356
  Epoch 020 - train 0.08229 | val 0.09396
  Epoch 021 - train 0.07880 | val 0.09431
  Regression -> MSE: 0.000248, MAE: 0.012525, R²: -0.0012
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07795 | val 0.07204
  Epoch 020 - train 0.07781 | val 0.08053
  Epoch 021 - train 0.07609 | val 0.08053
  Regression -> MSE: 0.000689, MAE: 0.019438, R²: -0.0066
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.08202 | val 0.11798
  Epoch 020 - train 0.08722 | val 0.12125
  Epoch 021 - train 0.08332 | val 0.12134
  Regression -> MSE: 0.000319, MAE: 0.014503, R²: -0.0283
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07172 | val 0.06306
  Epoch 020 - train 0.07282 | val 0.06324
  Epoch 021 - train 0.07035 | val 0.06324
  Regression -> MSE: 0.000372, MAE: 0.014950, R²: -0.0647
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.08122 | val 0.08854
  Epoch 020 - train 0.08444 | val 0.10600
  Epoch 021 - train 0.08487 | val 0.10605
  Regression -> MSE: 0.000209, MAE: 0.010177, R²: -0.0249
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07987 | val 0.13760
  Epoch 020 - train 0.07041 | val 0.14443
  Epoch 021 - train 0.08024 | val 0.14470
  Regression -> MSE: 0.000594, MAE: 0.018862, R²: -0.0698
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.08655 | val 0.09392
  Epoch 020 - train 0.08344 | val 0.09453
  Epoch 021 - train 0.08821 | val 0.09462
  Regression -> MSE: 0.000254, MAE: 0.012019, R²: -0.0362
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07809 | val 0.09067
  Epoch 020 - train 0.07897 | val 0.09020
  Epoch 021 - train 0.07859 | val 0.09026
  Regression -> MSE: 0.000618, MAE: 0.019654, R²: -0.0336
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08143 | val 0.09295
  Epoch 020 - train 0.07593 | val 0.09834
  Epoch 021 - train 0.07589 | val 0.09827
  Regression -> MSE: 0.000385, MAE: 0.016241, R²: -0.0045
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.08314 | val 0.09000
  Epoch 020 - train 0.07824 | val 0.09049
  Epoch 021 - train 0.08337 | val 0.09061
  Regression -> MSE: 0.000241, MAE: 0.011848, R²: 0.0001
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.07780 | val 0.10114
  Epoch 020 - train 0.07701 | val 0.10153
  Epoch 021 - train 0.07170 | val 0.10133
  Regression -> MSE: 0.000318, MAE: 0.013590, R²: -0.0233
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07671 | val 0.08707
  Epoch 020 - train 0.08077 | val 0.08908
  Epoch 021 - train 0.08237 | val 0.08905
  Regression -> MSE: 0.000679, MAE: 0.019571, R²: -0.0033
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.08002 | val 0.08053
  Epoch 020 - train 0.08030 | val 0.08551
  Epoch 021 - train 0.08005 | val 0.08646
  Regression -> MSE: 0.000139, MAE: 0.009023, R²: -0.0038
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.07435 | val 0.08899
  Epoch 020 - train 0.07468 | val 0.08941
  Epoch 021 - train 0.07697 | val 0.08934
  Regression -> MSE: 0.000229, MAE: 0.010818, R²: -0.0188
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07322 | val 0.14286
  Epoch 020 - train 0.07809 | val 0.14933
  Epoch 021 - train 0.07986 | val 0.14942
  Regression -> MSE: 0.000362, MAE: 0.016074, R²: 0.0001
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.08829 | val 0.08224
  Epoch 020 - train 0.08786 | val 0.08281
  Epoch 021 - train 0.08862 | val 0.08294
  Regression -> MSE: 0.000110, MAE: 0.007967, R²: -0.0172
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07692 | val 0.11622
  Epoch 020 - train 0.07650 | val 0.11619
  Epoch 021 - train 0.07807 | val 0.11636
  Regression -> MSE: 0.000157, MAE: 0.009519, R²: -0.0055
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07958 | val 0.08803
  Epoch 020 - train 0.07840 | val 0.08945
  Epoch 021 - train 0.07956 | val 0.08989
  Regression -> MSE: 0.000273, MAE: 0.013084, R²: -0.0045
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07628 | val 0.10042
  Epoch 020 - train 0.07645 | val 0.10120
  Epoch 021 - train 0.06903 | val 0.10123
  Regression -> MSE: 0.000161, MAE: 0.008939, R²: -0.0757
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.08418 | val 0.10445
  Epoch 020 - train 0.08520 | val 0.10509
  Epoch 021 - train 0.08238 | val 0.10469
  Regression -> MSE: 0.000238, MAE: 0.011005, R²: -0.0527
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08379 | val 0.09894
  Epoch 020 - train 0.08253 | val 0.11092
  Epoch 021 - train 0.08602 | val 0.10992
  Regression -> MSE: 0.000144, MAE: 0.008404, R²: -0.0071
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07352 | val 0.08251
  Epoch 020 - train 0.07363 | val 0.08297
  Epoch 021 - train 0.07689 | val 0.08280
  Regression -> MSE: 0.000170, MAE: 0.010269, R²: -0.0301
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08929 | val 0.08603
  Epoch 020 - train 0.08199 | val 0.08699
  Epoch 021 - train 0.08142 | val 0.08692
  Regression -> MSE: 0.000087, MAE: 0.007134, R²: -0.0194
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07784 | val 0.11384
  Epoch 020 - train 0.08304 | val 0.12389
  Epoch 021 - train 0.08372 | val 0.12162
  Regression -> MSE: 0.000216, MAE: 0.011031, R²: -0.0183
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08039 | val 0.06860
  Epoch 020 - train 0.07697 | val 0.06969
  Epoch 021 - train 0.07855 | val 0.06967
  Regression -> MSE: 0.000093, MAE: 0.008075, R²: -0.0059
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07980 | val 0.05878
  Epoch 020 - train 0.08311 | val 0.06914
  Epoch 021 - train 0.08145 | val 0.07063
  Regression -> MSE: 0.000105, MAE: 0.008862, R²: -0.0221
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.08255 | val 0.07856
  Epoch 020 - train 0.08527 | val 0.08985
  Epoch 021 - train 0.08503 | val 0.08980
  Regression -> MSE: 0.000243, MAE: 0.012902, R²: -0.0483
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07897 | val 0.08950
  Epoch 020 - train 0.07900 | val 0.09037
  Epoch 021 - train 0.07697 | val 0.09031
  Regression -> MSE: 0.000177, MAE: 0.007926, R²: -0.0657
  Directional -> Accuracy: 0.4386, MCC: -0.2530, F1: 0.5897

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08087 | val 0.06661
  Epoch 020 - train 0.08406 | val 0.08602
  Epoch 021 - train 0.08682 | val 0.08721
  Regression -> MSE: 0.000237, MAE: 0.011899, R²: -0.0037
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07921 | val 0.11034
  Epoch 020 - train 0.08156 | val 0.11138
  Epoch 021 - train 0.08256 | val 0.11160
  Regression -> MSE: 0.000230, MAE: 0.009859, R²: 0.0002
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07612 | val 0.09273
  Epoch 020 - train 0.08662 | val 0.09326
  Epoch 021 - train 0.08421 | val 0.09281
  Regression -> MSE: 0.000142, MAE: 0.008560, R²: -0.0504
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08662 | val 0.09026
  Epoch 020 - train 0.08679 | val 0.09155
  Epoch 021 - train 0.08275 | val 0.09156
  Regression -> MSE: 0.000199, MAE: 0.010676, R²: -0.0549
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07672 | val 0.08035
  Epoch 020 - train 0.07520 | val 0.08021
  Epoch 021 - train 0.07708 | val 0.07993
  Regression -> MSE: 0.000265, MAE: 0.010504, R²: -0.0119
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07716 | val 0.06141
  Epoch 020 - train 0.07254 | val 0.06186
  Epoch 021 - train 0.08072 | val 0.06195
  Regression -> MSE: 0.000167, MAE: 0.010362, R²: -0.0015
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.07302 | val 0.07859
  Epoch 020 - train 0.07594 | val 0.07962
  Epoch 021 - train 0.07435 | val 0.07963
  Regression -> MSE: 0.000189, MAE: 0.010641, R²: -0.0480
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09184 | val 0.07488
  Epoch 020 - train 0.08674 | val 0.07463
  Epoch 021 - train 0.08625 | val 0.07488
  Regression -> MSE: 0.000343, MAE: 0.011853, R²: -0.0018
  Directional -> Accuracy: 0.3731, MCC: -0.2259, F1: 0.1250

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08295 | val 0.04887
  Epoch 020 - train 0.07723 | val 0.04826
  Epoch 021 - train 0.08066 | val 0.04834
  Regression -> MSE: 0.000114, MAE: 0.008331, R²: -0.0821
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.08296 | val 0.10651
  Epoch 020 - train 0.08228 | val 0.11729
  Epoch 021 - train 0.08236 | val 0.11700
  Regression -> MSE: 0.000220, MAE: 0.011350, R²: -0.0079
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.08546 | val 0.11886
  Epoch 020 - train 0.08311 | val 0.11968
  Epoch 021 - train 0.08015 | val 0.11974
  Regression -> MSE: 0.000094, MAE: 0.007561, R²: -0.2066
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08257 | val 0.06174
  Epoch 020 - train 0.08122 | val 0.06899
  Epoch 021 - train 0.07634 | val 0.06984
  Regression -> MSE: 0.000328, MAE: 0.014884, R²: -0.0659
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.08573 | val 0.04892
  Epoch 020 - train 0.08582 | val 0.04666
  Epoch 021 - train 0.08012 | val 0.04639
  Regression -> MSE: 0.000261, MAE: 0.011495, R²: -0.0692
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.07907 | val 0.09431
  Epoch 020 - train 0.07843 | val 0.09472
  Epoch 021 - train 0.07950 | val 0.09458
  Regression -> MSE: 0.000084, MAE: 0.007052, R²: -0.0336
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.08102 | val 0.09185
  Epoch 020 - train 0.08831 | val 0.11171
  Epoch 021 - train 0.07760 | val 0.11258
  Regression -> MSE: 0.000308, MAE: 0.014514, R²: -0.0040
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07777 | val 0.07710
  Epoch 020 - train 0.08221 | val 0.07969
  Epoch 021 - train 0.08236 | val 0.07985
  Regression -> MSE: 0.000098, MAE: 0.007312, R²: -0.0009
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08702 | val 0.08284
  Epoch 020 - train 0.08521 | val 0.07986
  Epoch 021 - train 0.08503 | val 0.07996
  Regression -> MSE: 0.000174, MAE: 0.009448, R²: -0.0099
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07873 | val 0.11146
  Epoch 020 - train 0.07556 | val 0.12810
  Epoch 021 - train 0.07956 | val 0.13151
  Regression -> MSE: 0.000231, MAE: 0.011935, R²: -0.0375
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.08338 | val 0.08754
  Epoch 020 - train 0.08568 | val 0.09188
  Epoch 021 - train 0.07675 | val 0.09204

[I 2026-02-24 02:20:35,133] Trial 112 finished with value: -0.011441109789544959 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 7.104004849974926e-06, 'weight_decay': 1.3219006489837183e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.10261261925875279, 'early_stopping_min_delta': 0.00865398310786794}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.08203 | val 0.10020
  Epoch 021 - train 0.07991 | val 0.10007
  Regression -> MSE: 0.000237, MAE: 0.012435, R²: 0.0003
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.08254 | val 0.10109
  Epoch 020 - train 0.08453 | val 0.10109
  Epoch 021 - train 0.08129 | val 0.10167
  Regression -> MSE: 0.000249, MAE: 0.012617, R²: -0.0063
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08495 | val 0.07130
  Epoch 020 - train 0.08211 | val 0.07007
  Epoch 021 - train 0.08114 | val 0.07011
  Regression -> MSE: 0.000690, MAE: 0.019444, R²: -0.0080
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.08596 | val 0.12635
  Epoch 020 - train 0.08716 | val 0.13548
  Epoch 021 - train 0.09235 | val 0.13569
  Regression -> MSE: 0.000330, MAE: 0.014608, R²: -0.0628
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07033 | val 0.06552
  Epoch 020 - train 0.06838 | val 0.06659
  Epoch 021 - train 0.07644 | val 0.06592
  Regression -> MSE: 0.000350, MAE: 0.014587, R²: -0.0025
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07843 | val 0.07492
  Epoch 020 - train 0.08070 | val 0.07484
  Epoch 021 - train 0.08224 | val 0.07486
  Regression -> MSE: 0.000204, MAE: 0.010037, R²: 0.0004
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09160 | val 0.13498
  Epoch 020 - train 0.08013 | val 0.15842
  Epoch 021 - train 0.08298 | val 0.16010
  Regression -> MSE: 0.000589, MAE: 0.018761, R²: -0.0608
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.08388 | val 0.09109
  Epoch 020 - train 0.08030 | val 0.09118
  Epoch 021 - train 0.08154 | val 0.09118
  Regression -> MSE: 0.000247, MAE: 0.011902, R²: -0.0053
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09247 | val 0.08753
  Epoch 020 - train 0.08966 | val 0.07991
  Epoch 030 - train 0.07757 | val 0.07843
  Regression -> MSE: 0.000595, MAE: 0.018957, R²: 0.0049
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07910 | val 0.08873
  Epoch 020 - train 0.07958 | val 0.09038
  Epoch 021 - train 0.07767 | val 0.09039
  Regression -> MSE: 0.000400, MAE: 0.016037, R²: -0.0416
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.08592 | val 0.09792
  Epoch 020 - train 0.08070 | val 0.09752
  Epoch 021 - train 0.08419 | val 0.09756
  Regression -> MSE: 0.000242, MAE: 0.012059, R²: -0.0035
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08032 | val 0.11540
  Epoch 020 - train 0.07907 | val 0.12011
  Epoch 021 - train 0.08179 | val 0.12040
  Regression -> MSE: 0.000312, MAE: 0.013774, R²: -0.0024
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08335 | val 0.09002
  Epoch 020 - train 0.08039 | val 0.09666
  Epoch 021 - train 0.08468 | val 0.09665
  Regression -> MSE: 0.000683, MAE: 0.019725, R²: -0.0084
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.08425 | val 0.07750
  Epoch 020 - train 0.08768 | val 0.07938
  Epoch 021 - train 0.08336 | val 0.07928
  Regression -> MSE: 0.000138, MAE: 0.009117, R²: -0.0006
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.07540 | val 0.09509
  Epoch 020 - train 0.07699 | val 0.09363
  Epoch 021 - train 0.07506 | val 0.09392
  Regression -> MSE: 0.000226, MAE: 0.010698, R²: -0.0041
  Directional -> Accuracy: 0.4918, MCC: -0.0244, F1: 0.5753

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08188 | val 0.14496
  Epoch 020 - train 0.07893 | val 0.14476
  Epoch 021 - train 0.07917 | val 0.14482
  Regression -> MSE: 0.000366, MAE: 0.015948, R²: -0.0116
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.08455 | val 0.07740
  Epoch 020 - train 0.08499 | val 0.07744
  Epoch 021 - train 0.08430 | val 0.07752
  Regression -> MSE: 0.000109, MAE: 0.007948, R²: -0.0127
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07943 | val 0.13380
  Epoch 020 - train 0.08734 | val 0.14484
  Epoch 021 - train 0.07953 | val 0.14450
  Regression -> MSE: 0.000162, MAE: 0.010172, R²: -0.0377
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08435 | val 0.09551
  Epoch 020 - train 0.08828 | val 0.09514
  Epoch 021 - train 0.08481 | val 0.09700
  Regression -> MSE: 0.000274, MAE: 0.012965, R²: -0.0065
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07940 | val 0.10533
  Epoch 020 - train 0.07874 | val 0.10619
  Epoch 021 - train 0.07974 | val 0.10616
  Regression -> MSE: 0.000157, MAE: 0.008815, R²: -0.0491
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.08942 | val 0.10503
  Epoch 020 - train 0.09118 | val 0.10537
  Epoch 021 - train 0.09268 | val 0.10535
  Regression -> MSE: 0.000227, MAE: 0.010902, R²: -0.0035
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08228 | val 0.09374
  Epoch 020 - train 0.08867 | val 0.09632
  Epoch 021 - train 0.08478 | val 0.09626
  Regression -> MSE: 0.000144, MAE: 0.008394, R²: -0.0052
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09052 | val 0.08933
  Epoch 020 - train 0.08968 | val 0.08967
  Epoch 021 - train 0.08602 | val 0.08972
  Regression -> MSE: 0.000191, MAE: 0.010507, R²: -0.1530
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08728 | val 0.08917
  Epoch 020 - train 0.08640 | val 0.09000
  Epoch 021 - train 0.08765 | val 0.09000
  Regression -> MSE: 0.000086, MAE: 0.007082, R²: -0.0057
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.08207 | val 0.11344
  Epoch 020 - train 0.08744 | val 0.11500
  Epoch 021 - train 0.08416 | val 0.11624
  Regression -> MSE: 0.000213, MAE: 0.011199, R²: -0.0041
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08448 | val 0.07193
  Epoch 020 - train 0.08708 | val 0.07459
  Epoch 021 - train 0.08326 | val 0.07494
  Regression -> MSE: 0.000094, MAE: 0.008106, R²: -0.0195
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07816 | val 0.05963
  Epoch 020 - train 0.08649 | val 0.06163
  Epoch 021 - train 0.08098 | val 0.06182
  Regression -> MSE: 0.000104, MAE: 0.008783, R²: -0.0089
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09020 | val 0.07221
  Epoch 020 - train 0.09103 | val 0.07399
  Epoch 021 - train 0.08557 | val 0.07401
  Regression -> MSE: 0.000235, MAE: 0.012675, R²: -0.0153
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.08214 | val 0.09592
  Epoch 020 - train 0.08784 | val 0.09735
  Epoch 021 - train 0.08747 | val 0.09718
  Regression -> MSE: 0.000174, MAE: 0.007867, R²: -0.0459
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08670 | val 0.06511
  Epoch 020 - train 0.07863 | val 0.07608
  Epoch 021 - train 0.08942 | val 0.07668
  Regression -> MSE: 0.000237, MAE: 0.011891, R²: -0.0039
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.08355 | val 0.11704
  Epoch 020 - train 0.08451 | val 0.11620
  Epoch 021 - train 0.07659 | val 0.11625
  Regression -> MSE: 0.000231, MAE: 0.009961, R²: -0.0038
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09474 | val 0.09785
  Epoch 020 - train 0.08573 | val 0.09600
  Epoch 021 - train 0.08945 | val 0.09566
  Regression -> MSE: 0.000145, MAE: 0.008676, R²: -0.0705
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08469 | val 0.09509
  Epoch 020 - train 0.08171 | val 0.09723
  Epoch 021 - train 0.08487 | val 0.09738
  Regression -> MSE: 0.000193, MAE: 0.010429, R²: -0.0251
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07887 | val 0.09906
  Epoch 020 - train 0.08632 | val 0.09961
  Epoch 021 - train 0.07931 | val 0.09898
  Regression -> MSE: 0.000271, MAE: 0.010637, R²: -0.0350
  Directional -> Accuracy: 0.4658, MCC: -0.0070, F1: 0.3390

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08535 | val 0.06422
  Epoch 020 - train 0.08367 | val 0.06519
  Epoch 021 - train 0.08113 | val 0.06532
  Regression -> MSE: 0.000167, MAE: 0.010368, R²: -0.0029
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08916 | val 0.08023
  Epoch 020 - train 0.08397 | val 0.07980
  Epoch 021 - train 0.08060 | val 0.07958
  Regression -> MSE: 0.000190, MAE: 0.010682, R²: -0.0556
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.08441 | val 0.07763
  Epoch 020 - train 0.08038 | val 0.07799
  Epoch 021 - train 0.08101 | val 0.07791
  Regression -> MSE: 0.000342, MAE: 0.011729, R²: 0.0029
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08734 | val 0.05283
  Epoch 020 - train 0.09498 | val 0.05485
  Epoch 021 - train 0.10015 | val 0.05527
  Regression -> MSE: 0.000109, MAE: 0.008334, R²: -0.0342
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.08411 | val 0.10709
  Epoch 020 - train 0.08594 | val 0.11113
  Epoch 021 - train 0.08371 | val 0.10930
  Regression -> MSE: 0.000225, MAE: 0.011464, R²: -0.0297
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.08214 | val 0.12987
  Epoch 020 - train 0.08495 | val 0.13299
  Epoch 021 - train 0.08298 | val 0.13282
  Regression -> MSE: 0.000084, MAE: 0.007162, R²: -0.0854
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08729 | val 0.06129
  Epoch 020 - train 0.08764 | val 0.06266
  Epoch 021 - train 0.08179 | val 0.06312
  Regression -> MSE: 0.000322, MAE: 0.014582, R²: -0.0461
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09196 | val 0.04653
  Epoch 020 - train 0.09426 | val 0.04507
  Epoch 021 - train 0.09395 | val 0.04484
  Regression -> MSE: 0.000247, MAE: 0.011533, R²: -0.0125
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08698 | val 0.08881
  Epoch 020 - train 0.08537 | val 0.08874
  Epoch 021 - train 0.08751 | val 0.08889
  Regression -> MSE: 0.000082, MAE: 0.007065, R²: -0.0096
  Directional -> Accuracy: 0.4667, MCC: -0.1219, F1: 0.6296

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.08620 | val 0.09156
  Epoch 020 - train 0.08000 | val 0.09307
  Epoch 021 - train 0.08278 | val 0.09297
  Regression -> MSE: 0.000307, MAE: 0.014480, R²: 0.0001
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08569 | val 0.07984
  Epoch 020 - train 0.07637 | val 0.08259
  Epoch 021 - train 0.09456 | val 0.08263
  Regression -> MSE: 0.000098, MAE: 0.007287, R²: 0.0026
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08730 | val 0.08950
  Epoch 020 - train 0.08460 | val 0.09272
  Epoch 021 - train 0.09124 | val 0.09292
  Regression -> MSE: 0.000172, MAE: 0.009701, R²: 0.0003
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07975 | val 0.09433
  Epoch 020 - train 0.08029 | val 0.09816
  Epoch 021 - train 0.07789 | val 0.10015
  Regression -> MSE: 0.000225, MAE: 0.011793, R²: -0.0079
  Directional -> Accuracy: 0.3750, MCC: -0.2677, F1: 0.4444

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.08486 | val 0.08958
  Epoch 020 - train 0.08233 | val 0.09130
  Epoch 021 - train 0.08708 | val 0.09149

[I 2026-02-24 02:22:40,334] Trial 113 finished with value: -0.011422464666475568 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 7.057760689656543e-06, 'weight_decay': 5.762188311881496e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.10722828376126452, 'early_stopping_min_delta': 0.007371120098836026}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.08575 | val 0.11368
  Epoch 021 - train 0.09322 | val 0.11380
  Regression -> MSE: 0.000241, MAE: 0.012329, R²: -0.0170
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.16599 | val 0.18792
  Epoch 020 - train 0.16280 | val 0.18748
  Epoch 027 - train 0.16442 | val 0.18722
  Regression -> MSE: 0.000252, MAE: 0.012695, R²: -0.0164
  Directional -> Accuracy: 0.4675, MCC: 0.0490, F1: 0.6239

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.15921 | val 0.13666
  Epoch 020 - train 0.15695 | val 0.13671
  Epoch 021 - train 0.16522 | val 0.13656
  Regression -> MSE: 0.000701, MAE: 0.019622, R²: -0.0237
  Directional -> Accuracy: 0.4348, MCC: -0.1641, F1: 0.5185

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.17282 | val 0.23192
  Epoch 020 - train 0.16269 | val 0.22897
  Epoch 030 - train 0.17275 | val 0.22892
  Regression -> MSE: 0.000324, MAE: 0.014323, R²: -0.0460
  Directional -> Accuracy: 0.5745, MCC: 0.1988, F1: 0.4737

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13297 | val 0.12859
  Epoch 020 - train 0.14407 | val 0.12979
  Epoch 021 - train 0.14558 | val 0.13108
  Regression -> MSE: 0.000350, MAE: 0.014600, R²: -0.0015
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15753 | val 0.14569
  Epoch 020 - train 0.14879 | val 0.14392
  Epoch 021 - train 0.15374 | val 0.14377
  Regression -> MSE: 0.000207, MAE: 0.010475, R²: -0.0183
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15337 | val 0.26571
  Epoch 020 - train 0.15144 | val 0.30293
  Epoch 021 - train 0.15921 | val 0.30442
  Regression -> MSE: 0.000561, MAE: 0.018190, R²: -0.0109
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.17227 | val 0.17928
  Epoch 020 - train 0.17321 | val 0.17955
  Epoch 021 - train 0.16383 | val 0.17938
  Regression -> MSE: 0.000252, MAE: 0.011991, R²: -0.0273
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.16105 | val 0.20487
  Epoch 020 - train 0.14966 | val 0.20340
  Epoch 021 - train 0.15965 | val 0.20286
  Regression -> MSE: 0.000654, MAE: 0.020306, R²: -0.0952
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15521 | val 0.17717
  Epoch 020 - train 0.16008 | val 0.18234
  Epoch 021 - train 0.15871 | val 0.18294
  Regression -> MSE: 0.000387, MAE: 0.016025, R²: -0.0100
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16726 | val 0.19288
  Epoch 020 - train 0.16409 | val 0.19522
  Epoch 021 - train 0.16890 | val 0.19562
  Regression -> MSE: 0.000241, MAE: 0.011790, R²: 0.0007
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15380 | val 0.27145
  Epoch 020 - train 0.15429 | val 0.34821
  Epoch 021 - train 0.16149 | val 0.34483
  Regression -> MSE: 0.000312, MAE: 0.013821, R²: -0.0031
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15421 | val 0.17983
  Epoch 020 - train 0.15443 | val 0.18981
  Epoch 021 - train 0.14812 | val 0.18937
  Regression -> MSE: 0.000676, MAE: 0.019467, R²: 0.0012
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17683 | val 0.15728
  Epoch 020 - train 0.17366 | val 0.17463
  Epoch 021 - train 0.18588 | val 0.17532
  Regression -> MSE: 0.000138, MAE: 0.009054, R²: -0.0020
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15716 | val 0.21553
  Epoch 020 - train 0.16121 | val 0.22760
  Epoch 021 - train 0.15415 | val 0.22574
  Regression -> MSE: 0.000228, MAE: 0.010787, R²: -0.0150
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15542 | val 0.29032
  Epoch 020 - train 0.16144 | val 0.29299
  Epoch 021 - train 0.15942 | val 0.29313
  Regression -> MSE: 0.000362, MAE: 0.016036, R²: -0.0001
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15922 | val 0.14881
  Epoch 020 - train 0.16410 | val 0.15179
  Epoch 027 - train 0.16849 | val 0.15107
  Regression -> MSE: 0.000111, MAE: 0.007992, R²: -0.0313
  Directional -> Accuracy: 0.5571, MCC: 0.0759, F1: 0.6869

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.16302 | val 0.25111
  Epoch 020 - train 0.15737 | val 0.27361
  Epoch 021 - train 0.16290 | val 0.27176
  Regression -> MSE: 0.000159, MAE: 0.009997, R²: -0.0177
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16690 | val 0.15518
  Epoch 020 - train 0.16963 | val 0.15608
  Epoch 021 - train 0.16501 | val 0.15501
  Regression -> MSE: 0.000273, MAE: 0.013081, R²: -0.0029
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.16603 | val 0.23024
  Epoch 020 - train 0.16318 | val 0.23184
  Epoch 021 - train 0.16063 | val 0.23252
  Regression -> MSE: 0.000151, MAE: 0.008765, R²: -0.0070
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15977 | val 0.21450
  Epoch 020 - train 0.15851 | val 0.21515
  Epoch 021 - train 0.15928 | val 0.21551
  Regression -> MSE: 0.000228, MAE: 0.010939, R²: -0.0076
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15602 | val 0.18026
  Epoch 020 - train 0.14934 | val 0.18646
  Epoch 021 - train 0.15779 | val 0.18513
  Regression -> MSE: 0.000146, MAE: 0.008509, R²: -0.0178
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.16025 | val 0.16656
  Epoch 020 - train 0.15910 | val 0.16700
  Epoch 021 - train 0.15614 | val 0.16718
  Regression -> MSE: 0.000181, MAE: 0.010329, R²: -0.0954
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.17198 | val 0.17115
  Epoch 020 - train 0.16867 | val 0.17154
  Epoch 021 - train 0.18123 | val 0.17167
  Regression -> MSE: 0.000085, MAE: 0.007053, R²: -0.0007
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16299 | val 0.17506
  Epoch 020 - train 0.16774 | val 0.17566
  Epoch 021 - train 0.15934 | val 0.17487
  Regression -> MSE: 0.000214, MAE: 0.011049, R²: -0.0104
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.15501 | val 0.12784
  Epoch 020 - train 0.14772 | val 0.12694
  Epoch 021 - train 0.15717 | val 0.12678
  Regression -> MSE: 0.000102, MAE: 0.008260, R²: -0.1121
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17310 | val 0.11823
  Epoch 020 - train 0.16435 | val 0.10927
  Epoch 030 - train 0.15027 | val 0.10855
  Regression -> MSE: 0.000107, MAE: 0.008942, R²: -0.0399
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.17511 | val 0.14275
  Epoch 020 - train 0.17085 | val 0.16547
  Epoch 021 - train 0.17032 | val 0.16659
  Regression -> MSE: 0.000232, MAE: 0.012510, R²: -0.0014
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15237 | val 0.17292
  Epoch 020 - train 0.14432 | val 0.17252
  Epoch 021 - train 0.15758 | val 0.17274
  Regression -> MSE: 0.000173, MAE: 0.007876, R²: -0.0400
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16232 | val 0.12569
  Epoch 020 - train 0.16388 | val 0.13897
  Epoch 021 - train 0.16926 | val 0.14096
  Regression -> MSE: 0.000237, MAE: 0.011866, R²: 0.0001
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.17279 | val 0.23327
  Epoch 020 - train 0.17374 | val 0.23329
  Epoch 021 - train 0.15281 | val 0.23338
  Regression -> MSE: 0.000234, MAE: 0.010117, R²: -0.0148
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16629 | val 0.17835
  Epoch 020 - train 0.15630 | val 0.16560
  Epoch 030 - train 0.15046 | val 0.16477
  Regression -> MSE: 0.000135, MAE: 0.008169, R²: 0.0027
  Directional -> Accuracy: 0.5349, MCC: 0.0154, F1: 0.6875

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.17673 | val 0.18254
  Epoch 020 - train 0.15886 | val 0.18324
  Epoch 021 - train 0.17128 | val 0.18337
  Regression -> MSE: 0.000190, MAE: 0.010394, R²: -0.0084
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15731 | val 0.17038
  Epoch 020 - train 0.15582 | val 0.17157
  Epoch 021 - train 0.15637 | val 0.17071
  Regression -> MSE: 0.000264, MAE: 0.010500, R²: -0.0071
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15938 | val 0.12554
  Epoch 020 - train 0.13902 | val 0.12752
  Epoch 021 - train 0.14603 | val 0.12805
  Regression -> MSE: 0.000167, MAE: 0.010367, R²: -0.0027
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15919 | val 0.14287
  Epoch 020 - train 0.15069 | val 0.14531
  Epoch 021 - train 0.15531 | val 0.14577
  Regression -> MSE: 0.000180, MAE: 0.010284, R²: 0.0013
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16284 | val 0.14247
  Epoch 020 - train 0.15478 | val 0.14331
  Epoch 021 - train 0.15821 | val 0.14229
  Regression -> MSE: 0.000343, MAE: 0.012034, R²: -0.0010
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18777 | val 0.09697
  Epoch 020 - train 0.18099 | val 0.11732
  Epoch 021 - train 0.18811 | val 0.11749
  Regression -> MSE: 0.000131, MAE: 0.008573, R²: -0.2478
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17987 | val 0.19415
  Epoch 020 - train 0.16958 | val 0.19620
  Epoch 021 - train 0.17139 | val 0.19664
  Regression -> MSE: 0.000218, MAE: 0.011251, R²: 0.0003
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15453 | val 0.25011
  Epoch 020 - train 0.14731 | val 0.26794
  Epoch 021 - train 0.16498 | val 0.26776
  Regression -> MSE: 0.000090, MAE: 0.007436, R²: -0.1632
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.17378 | val 0.12218
  Epoch 020 - train 0.17473 | val 0.13347
  Epoch 021 - train 0.16809 | val 0.13486
  Regression -> MSE: 0.000334, MAE: 0.015161, R²: -0.0860
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17407 | val 0.08738
  Epoch 020 - train 0.17326 | val 0.09406
  Epoch 021 - train 0.16858 | val 0.09523
  Regression -> MSE: 0.000246, MAE: 0.011553, R²: -0.0096
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15535 | val 0.17749
  Epoch 020 - train 0.15699 | val 0.17772
  Epoch 021 - train 0.15814 | val 0.17740
  Regression -> MSE: 0.000081, MAE: 0.007085, R²: -0.0008
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16500 | val 0.18282
  Epoch 020 - train 0.15261 | val 0.17601
  Epoch 030 - train 0.16758 | val 0.17304
  Regression -> MSE: 0.000308, MAE: 0.014496, R²: -0.0039
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.15650 | val 0.15244
  Epoch 020 - train 0.15684 | val 0.15377
  Epoch 021 - train 0.15109 | val 0.15417
  Regression -> MSE: 0.000098, MAE: 0.007314, R²: -0.0027
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17467 | val 0.16895
  Epoch 020 - train 0.16488 | val 0.16504
  Epoch 021 - train 0.17404 | val 0.16496
  Regression -> MSE: 0.000173, MAE: 0.009921, R²: -0.0064
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14875 | val 0.17143
  Epoch 020 - train 0.13870 | val 0.18525
  Epoch 021 - train 0.13997 | val 0.18447
  Regression -> MSE: 0.000224, MAE: 0.011780, R²: -0.0066
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14927 | val 0.15802
  Epoch 020 - train 0.14943 | val 0.16119
  Epoch 021 - train 0.15274 | val 0.16105

[I 2026-02-24 02:24:54,379] Trial 114 finished with value: -0.01144120913738899 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 9.307043749901955e-06, 'weight_decay': 1.0093317756174986e-07, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.21966514932284864, 'early_stopping_min_delta': 0.007049016730930728}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.17389 | val 0.21575
  Epoch 021 - train 0.16372 | val 0.21608
  Regression -> MSE: 0.000237, MAE: 0.012334, R²: 0.0013
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10307 | val 0.12836
  Epoch 020 - train 0.10290 | val 0.12875
  Epoch 021 - train 0.10225 | val 0.12879
  Regression -> MSE: 0.000254, MAE: 0.012791, R²: -0.0242
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11302 | val 0.10976
  Epoch 020 - train 0.10393 | val 0.14186
  Epoch 021 - train 0.11179 | val 0.14180
  Regression -> MSE: 0.000685, MAE: 0.019362, R²: -0.0000
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10605 | val 0.15472
  Epoch 020 - train 0.10263 | val 0.15472
  Epoch 021 - train 0.10368 | val 0.15454
  Regression -> MSE: 0.000328, MAE: 0.014578, R²: -0.0580
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08994 | val 0.08182
  Epoch 020 - train 0.09223 | val 0.08268
  Epoch 021 - train 0.08781 | val 0.08227
  Regression -> MSE: 0.000357, MAE: 0.014707, R²: -0.0223
  Directional -> Accuracy: 0.5200, MCC: 0.1714, F1: 0.2800

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10836 | val 0.09718
  Epoch 020 - train 0.10703 | val 0.09475
  Epoch 021 - train 0.10197 | val 0.09469
  Regression -> MSE: 0.000205, MAE: 0.010314, R²: -0.0069
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09686 | val 0.17330
  Epoch 020 - train 0.09578 | val 0.18025
  Epoch 021 - train 0.10060 | val 0.18048
  Regression -> MSE: 0.000570, MAE: 0.018362, R²: -0.0266
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10766 | val 0.13442
  Epoch 020 - train 0.10925 | val 0.13558
  Epoch 021 - train 0.10655 | val 0.13550
  Regression -> MSE: 0.000252, MAE: 0.011944, R²: -0.0246
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09838 | val 0.12066
  Epoch 020 - train 0.10118 | val 0.14933
  Epoch 021 - train 0.10308 | val 0.15122
  Regression -> MSE: 0.000609, MAE: 0.019430, R²: -0.0186
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10297 | val 0.11221
  Epoch 020 - train 0.09931 | val 0.11114
  Epoch 021 - train 0.10118 | val 0.11115
  Regression -> MSE: 0.000405, MAE: 0.016142, R²: -0.0552
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10216 | val 0.14556
  Epoch 020 - train 0.10927 | val 0.15087
  Epoch 021 - train 0.10662 | val 0.14983
  Regression -> MSE: 0.000241, MAE: 0.011914, R²: 0.0008
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09928 | val 0.12984
  Epoch 020 - train 0.09846 | val 0.13012
  Epoch 021 - train 0.10077 | val 0.13038
  Regression -> MSE: 0.000330, MAE: 0.013640, R²: -0.0603
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10609 | val 0.13093
  Epoch 020 - train 0.10835 | val 0.14310
  Epoch 021 - train 0.10779 | val 0.14357
  Regression -> MSE: 0.000680, MAE: 0.019506, R²: -0.0034
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10386 | val 0.09317
  Epoch 020 - train 0.10603 | val 0.09186
  Epoch 021 - train 0.10794 | val 0.09191
  Regression -> MSE: 0.000145, MAE: 0.009508, R²: -0.0485
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09328 | val 0.11714
  Epoch 020 - train 0.08970 | val 0.11605
  Epoch 030 - train 0.09749 | val 0.11597
  Regression -> MSE: 0.000225, MAE: 0.011091, R²: -0.0016
  Directional -> Accuracy: 0.5410, MCC: 0.1049, F1: 0.3913

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10274 | val 0.19921
  Epoch 020 - train 0.09699 | val 0.21361
  Epoch 021 - train 0.10325 | val 0.21331
  Regression -> MSE: 0.000373, MAE: 0.015943, R²: -0.0288
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10509 | val 0.13340
  Epoch 020 - train 0.10904 | val 0.13682
  Epoch 021 - train 0.10804 | val 0.13616
  Regression -> MSE: 0.000110, MAE: 0.007963, R²: -0.0207
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09734 | val 0.15469
  Epoch 020 - train 0.09396 | val 0.15668
  Epoch 021 - train 0.09953 | val 0.15649
  Regression -> MSE: 0.000158, MAE: 0.009911, R²: -0.0118
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10211 | val 0.11120
  Epoch 020 - train 0.10459 | val 0.11306
  Epoch 021 - train 0.10568 | val 0.11463
  Regression -> MSE: 0.000274, MAE: 0.012931, R²: -0.0055
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09116 | val 0.12449
  Epoch 020 - train 0.08682 | val 0.12443
  Epoch 021 - train 0.09334 | val 0.12446
  Regression -> MSE: 0.000168, MAE: 0.009169, R²: -0.1240
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10770 | val 0.14042
  Epoch 020 - train 0.10543 | val 0.14254
  Epoch 021 - train 0.10402 | val 0.14260
  Regression -> MSE: 0.000226, MAE: 0.010915, R²: -0.0009
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11120 | val 0.11798
  Epoch 020 - train 0.10944 | val 0.11960
  Epoch 021 - train 0.11569 | val 0.11911
  Regression -> MSE: 0.000154, MAE: 0.008879, R²: -0.0776
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09968 | val 0.11018
  Epoch 020 - train 0.09900 | val 0.11020
  Epoch 021 - train 0.09889 | val 0.11017
  Regression -> MSE: 0.000173, MAE: 0.010269, R²: -0.0441
  Directional -> Accuracy: 0.4697, MCC: -0.1768, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12102 | val 0.13239
  Epoch 020 - train 0.11977 | val 0.13758
  Epoch 021 - train 0.12092 | val 0.13766
  Regression -> MSE: 0.000092, MAE: 0.007405, R²: -0.0832
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10411 | val 0.12538
  Epoch 020 - train 0.11012 | val 0.12466
  Epoch 021 - train 0.10469 | val 0.12433
  Regression -> MSE: 0.000213, MAE: 0.011329, R²: -0.0036
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09615 | val 0.08554
  Epoch 020 - train 0.10115 | val 0.08643
  Epoch 021 - train 0.09998 | val 0.08675
  Regression -> MSE: 0.000096, MAE: 0.008116, R²: -0.0387
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10274 | val 0.07858
  Epoch 020 - train 0.10539 | val 0.08581
  Epoch 021 - train 0.09989 | val 0.08639
  Regression -> MSE: 0.000109, MAE: 0.009008, R²: -0.0599
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10429 | val 0.09060
  Epoch 020 - train 0.11439 | val 0.09609
  Epoch 021 - train 0.11172 | val 0.09778
  Regression -> MSE: 0.000231, MAE: 0.012521, R²: 0.0004
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10149 | val 0.11612
  Epoch 020 - train 0.10169 | val 0.11632
  Epoch 021 - train 0.10380 | val 0.11628
  Regression -> MSE: 0.000175, MAE: 0.007884, R²: -0.0531
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10374 | val 0.08329
  Epoch 020 - train 0.10313 | val 0.08701
  Epoch 021 - train 0.09916 | val 0.08740
  Regression -> MSE: 0.000237, MAE: 0.011873, R²: -0.0013
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10536 | val 0.14734
  Epoch 020 - train 0.10099 | val 0.14471
  Epoch 021 - train 0.10097 | val 0.14474
  Regression -> MSE: 0.000230, MAE: 0.009873, R²: 0.0005
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10706 | val 0.11183
  Epoch 020 - train 0.10286 | val 0.10844
  Epoch 030 - train 0.09928 | val 0.10837
  Regression -> MSE: 0.000143, MAE: 0.008457, R²: -0.0603
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10350 | val 0.12138
  Epoch 020 - train 0.10129 | val 0.12376
  Epoch 021 - train 0.09579 | val 0.12387
  Regression -> MSE: 0.000192, MAE: 0.010398, R²: -0.0177
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10073 | val 0.10919
  Epoch 020 - train 0.09209 | val 0.10883
  Epoch 021 - train 0.09690 | val 0.10934
  Regression -> MSE: 0.000261, MAE: 0.010575, R²: 0.0019
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09160 | val 0.08074
  Epoch 020 - train 0.09849 | val 0.08141
  Epoch 021 - train 0.09829 | val 0.08157
  Regression -> MSE: 0.000167, MAE: 0.010360, R²: -0.0030
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10207 | val 0.10280
  Epoch 020 - train 0.09874 | val 0.11967
  Epoch 021 - train 0.09685 | val 0.11960
  Regression -> MSE: 0.000181, MAE: 0.010275, R²: -0.0036
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09963 | val 0.08873
  Epoch 020 - train 0.09534 | val 0.08878
  Epoch 021 - train 0.09524 | val 0.08903
  Regression -> MSE: 0.000345, MAE: 0.012088, R²: -0.0068
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10537 | val 0.06365
  Epoch 020 - train 0.10683 | val 0.06434
  Epoch 021 - train 0.10966 | val 0.06423
  Regression -> MSE: 0.000125, MAE: 0.008447, R²: -0.1886
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10447 | val 0.13417
  Epoch 020 - train 0.09617 | val 0.14063
  Epoch 021 - train 0.10658 | val 0.14041
  Regression -> MSE: 0.000221, MAE: 0.011344, R²: -0.0098
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09671 | val 0.15869
  Epoch 020 - train 0.10211 | val 0.16810
  Epoch 021 - train 0.09861 | val 0.16797
  Regression -> MSE: 0.000086, MAE: 0.007271, R²: -0.1133
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10405 | val 0.07402
  Epoch 020 - train 0.09464 | val 0.07957
  Epoch 021 - train 0.10049 | val 0.08033
  Regression -> MSE: 0.000312, MAE: 0.014099, R²: -0.0157
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10643 | val 0.05951
  Epoch 020 - train 0.10620 | val 0.06075
  Epoch 021 - train 0.10556 | val 0.06099
  Regression -> MSE: 0.000247, MAE: 0.011561, R²: -0.0113
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09458 | val 0.12026
  Epoch 020 - train 0.11047 | val 0.12079
  Epoch 021 - train 0.10394 | val 0.12058
  Regression -> MSE: 0.000081, MAE: 0.007067, R²: 0.0008
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10522 | val 0.11452
  Epoch 020 - train 0.10817 | val 0.10858
  Epoch 030 - train 0.10842 | val 0.10894
  Regression -> MSE: 0.000310, MAE: 0.014474, R²: -0.0111
  Directional -> Accuracy: 0.5106, MCC: 0.0283, F1: 0.4390

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10497 | val 0.10649
  Epoch 020 - train 0.10166 | val 0.10808
  Epoch 021 - train 0.10190 | val 0.10826
  Regression -> MSE: 0.000099, MAE: 0.007178, R²: -0.0098
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10756 | val 0.11363
  Epoch 020 - train 0.11335 | val 0.12567
  Epoch 021 - train 0.10862 | val 0.12694
  Regression -> MSE: 0.000172, MAE: 0.009594, R²: 0.0007
  Directional -> Accuracy: 0.5510, MCC: 0.0908, F1: 0.4762

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10080 | val 0.10966
  Epoch 020 - train 0.10230 | val 0.11316
  Epoch 021 - train 0.10015 | val 0.11407
  Regression -> MSE: 0.000227, MAE: 0.011813, R²: -0.0158
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10435 | val 0.10283
  Epoch 020 - train 0.10411 | val 0.10380
  Epoch 021 - train 0.09870 | val 0.10421

[I 2026-02-24 02:27:06,855] Trial 115 finished with value: -0.01143152192865751 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 6.069073389820534e-06, 'weight_decay': 5.58242410720266e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.13908574644262625, 'early_stopping_min_delta': 0.007430526007939983}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.10241 | val 0.12975
  Epoch 021 - train 0.09570 | val 0.13009
  Regression -> MSE: 0.000240, MAE: 0.012346, R²: -0.0100
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09803 | val 0.11733
  Epoch 020 - train 0.10012 | val 0.11752
  Epoch 027 - train 0.09654 | val 0.11758
  Regression -> MSE: 0.000247, MAE: 0.012578, R²: 0.0006
  Directional -> Accuracy: 0.5455, MCC: 0.0652, F1: 0.4262

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09627 | val 0.08808
  Epoch 020 - train 0.09821 | val 0.08864
  Epoch 021 - train 0.09696 | val 0.08866
  Regression -> MSE: 0.000692, MAE: 0.019469, R²: -0.0104
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10576 | val 0.15069
  Epoch 020 - train 0.10488 | val 0.15255
  Epoch 021 - train 0.10563 | val 0.15254
  Regression -> MSE: 0.000321, MAE: 0.014535, R²: -0.0359
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08423 | val 0.10696
  Epoch 020 - train 0.08145 | val 0.11335
  Epoch 021 - train 0.08100 | val 0.11123
  Regression -> MSE: 0.000350, MAE: 0.014574, R²: -0.0006
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10617 | val 0.10099
  Epoch 020 - train 0.10427 | val 0.10355
  Epoch 021 - train 0.09652 | val 0.10372
  Regression -> MSE: 0.000205, MAE: 0.010085, R²: -0.0055
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10120 | val 0.18004
  Epoch 020 - train 0.10332 | val 0.19315
  Epoch 021 - train 0.09760 | val 0.19342
  Regression -> MSE: 0.000600, MAE: 0.019006, R²: -0.0812
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10489 | val 0.12792
  Epoch 020 - train 0.10331 | val 0.12855
  Epoch 021 - train 0.10886 | val 0.12884
  Regression -> MSE: 0.000255, MAE: 0.012016, R²: -0.0399
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09728 | val 0.13276
  Epoch 020 - train 0.09384 | val 0.13407
  Epoch 021 - train 0.10305 | val 0.13451
  Regression -> MSE: 0.000655, MAE: 0.020314, R²: -0.0960
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10091 | val 0.11358
  Epoch 020 - train 0.08829 | val 0.12153
  Epoch 021 - train 0.09418 | val 0.12126
  Regression -> MSE: 0.000394, MAE: 0.015950, R²: -0.0265
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10323 | val 0.12533
  Epoch 020 - train 0.09880 | val 0.13182
  Epoch 021 - train 0.09964 | val 0.13247
  Regression -> MSE: 0.000244, MAE: 0.011669, R²: -0.0117
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08970 | val 0.13244
  Epoch 020 - train 0.09642 | val 0.13579
  Epoch 021 - train 0.09377 | val 0.13605
  Regression -> MSE: 0.000315, MAE: 0.013588, R²: -0.0131
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10302 | val 0.10961
  Epoch 020 - train 0.10000 | val 0.11425
  Epoch 021 - train 0.10376 | val 0.11415
  Regression -> MSE: 0.000682, MAE: 0.019535, R²: -0.0075
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10260 | val 0.09029
  Epoch 020 - train 0.09424 | val 0.08997
  Epoch 021 - train 0.09812 | val 0.09080
  Regression -> MSE: 0.000141, MAE: 0.009356, R²: -0.0227
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09672 | val 0.11577
  Epoch 020 - train 0.09937 | val 0.11695
  Epoch 028 - train 0.09243 | val 0.11707
  Regression -> MSE: 0.000241, MAE: 0.011225, R²: -0.0703
  Directional -> Accuracy: 0.5410, MCC: 0.1202, F1: 0.3333

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10240 | val 0.20076
  Epoch 020 - train 0.10235 | val 0.22566
  Epoch 021 - train 0.09497 | val 0.22545
  Regression -> MSE: 0.000362, MAE: 0.016162, R²: 0.0006
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11091 | val 0.10387
  Epoch 020 - train 0.10210 | val 0.10365
  Epoch 021 - train 0.10492 | val 0.10354
  Regression -> MSE: 0.000109, MAE: 0.008139, R²: -0.0108
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09261 | val 0.15524
  Epoch 020 - train 0.09803 | val 0.15953
  Epoch 021 - train 0.09760 | val 0.15968
  Regression -> MSE: 0.000156, MAE: 0.009551, R²: -0.0002
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09915 | val 0.12737
  Epoch 020 - train 0.09780 | val 0.12145
  Epoch 021 - train 0.09926 | val 0.12173
  Regression -> MSE: 0.000274, MAE: 0.012943, R²: -0.0054
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09507 | val 0.13264
  Epoch 020 - train 0.09465 | val 0.13222
  Epoch 021 - train 0.09265 | val 0.13185
  Regression -> MSE: 0.000164, MAE: 0.009023, R²: -0.0959
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10634 | val 0.15347
  Epoch 020 - train 0.10795 | val 0.15084
  Epoch 021 - train 0.10739 | val 0.15109
  Regression -> MSE: 0.000229, MAE: 0.010950, R²: -0.0139
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10778 | val 0.12750
  Epoch 020 - train 0.09998 | val 0.13936
  Epoch 021 - train 0.10026 | val 0.14037
  Regression -> MSE: 0.000144, MAE: 0.008321, R²: -0.0013
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09716 | val 0.10827
  Epoch 020 - train 0.09545 | val 0.10837
  Epoch 021 - train 0.09260 | val 0.10851
  Regression -> MSE: 0.000167, MAE: 0.010322, R²: -0.0133
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10506 | val 0.11336
  Epoch 020 - train 0.10051 | val 0.11861
  Epoch 021 - train 0.10310 | val 0.11843
  Regression -> MSE: 0.000086, MAE: 0.007120, R²: -0.0140
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10038 | val 0.12382
  Epoch 020 - train 0.09929 | val 0.12465
  Epoch 021 - train 0.09777 | val 0.12400
  Regression -> MSE: 0.000214, MAE: 0.011363, R²: -0.0097
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09586 | val 0.08429
  Epoch 020 - train 0.09361 | val 0.08407
  Epoch 021 - train 0.08865 | val 0.08424
  Regression -> MSE: 0.000096, MAE: 0.008134, R²: -0.0379
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10997 | val 0.07293
  Epoch 020 - train 0.10451 | val 0.07562
  Epoch 021 - train 0.10579 | val 0.07619
  Regression -> MSE: 0.000103, MAE: 0.008749, R²: -0.0026
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10827 | val 0.09177
  Epoch 020 - train 0.10219 | val 0.10008
  Epoch 021 - train 0.10404 | val 0.09984
  Regression -> MSE: 0.000237, MAE: 0.012759, R²: -0.0250
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09876 | val 0.11599
  Epoch 020 - train 0.09482 | val 0.11695
  Epoch 021 - train 0.09909 | val 0.11720
  Regression -> MSE: 0.000179, MAE: 0.007930, R²: -0.0730
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11247 | val 0.08202
  Epoch 020 - train 0.10386 | val 0.10409
  Epoch 021 - train 0.10759 | val 0.10710
  Regression -> MSE: 0.000239, MAE: 0.011932, R²: -0.0096
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10009 | val 0.14681
  Epoch 020 - train 0.10494 | val 0.14842
  Epoch 021 - train 0.09942 | val 0.14857
  Regression -> MSE: 0.000231, MAE: 0.009962, R²: -0.0041
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10142 | val 0.10943
  Epoch 020 - train 0.10440 | val 0.11770
  Epoch 021 - train 0.10630 | val 0.11860
  Regression -> MSE: 0.000135, MAE: 0.008183, R²: -0.0031
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09812 | val 0.11838
  Epoch 020 - train 0.10041 | val 0.11963
  Epoch 021 - train 0.09975 | val 0.11960
  Regression -> MSE: 0.000191, MAE: 0.010383, R²: -0.0119
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09870 | val 0.10725
  Epoch 020 - train 0.09153 | val 0.10677
  Epoch 021 - train 0.09187 | val 0.10666
  Regression -> MSE: 0.000278, MAE: 0.010873, R²: -0.0635
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09075 | val 0.08132
  Epoch 020 - train 0.08679 | val 0.07841
  Epoch 021 - train 0.09287 | val 0.07796
  Regression -> MSE: 0.000167, MAE: 0.010367, R²: -0.0035
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09173 | val 0.09607
  Epoch 020 - train 0.09113 | val 0.09341
  Epoch 021 - train 0.09550 | val 0.09370
  Regression -> MSE: 0.000183, MAE: 0.010419, R²: -0.0153
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09739 | val 0.08959
  Epoch 020 - train 0.09680 | val 0.08952
  Epoch 021 - train 0.09319 | val 0.08958
  Regression -> MSE: 0.000342, MAE: 0.011818, R²: 0.0017
  Directional -> Accuracy: 0.5224, MCC: 0.0872, F1: 0.4839

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10029 | val 0.06248
  Epoch 020 - train 0.10074 | val 0.06367
  Epoch 021 - train 0.11101 | val 0.06376
  Regression -> MSE: 0.000124, MAE: 0.008438, R²: -0.1794
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11091 | val 0.12913
  Epoch 020 - train 0.10941 | val 0.13271
  Epoch 021 - train 0.10707 | val 0.13309
  Regression -> MSE: 0.000219, MAE: 0.011272, R²: -0.0008
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09715 | val 0.15907
  Epoch 020 - train 0.09414 | val 0.16369
  Epoch 021 - train 0.09759 | val 0.16340
  Regression -> MSE: 0.000084, MAE: 0.007171, R²: -0.0874
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09765 | val 0.07115
  Epoch 020 - train 0.09790 | val 0.07406
  Epoch 021 - train 0.09575 | val 0.07433
  Regression -> MSE: 0.000310, MAE: 0.013878, R²: -0.0065
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10373 | val 0.05999
  Epoch 020 - train 0.09537 | val 0.05449
  Epoch 030 - train 0.10289 | val 0.05213
  Regression -> MSE: 0.000261, MAE: 0.011587, R²: -0.0719
  Directional -> Accuracy: 0.5789, MCC: 0.2485, F1: 0.7143

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09632 | val 0.10988
  Epoch 020 - train 0.09949 | val 0.10968
  Epoch 021 - train 0.09368 | val 0.10971
  Regression -> MSE: 0.000083, MAE: 0.007046, R²: -0.0292
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10427 | val 0.11634
  Epoch 020 - train 0.10198 | val 0.12048
  Epoch 021 - train 0.11199 | val 0.12190
  Regression -> MSE: 0.000307, MAE: 0.014488, R²: 0.0003
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10455 | val 0.10617
  Epoch 020 - train 0.10027 | val 0.10473
  Epoch 021 - train 0.10066 | val 0.10518
  Regression -> MSE: 0.000100, MAE: 0.007145, R²: -0.0141
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10779 | val 0.10733
  Epoch 020 - train 0.10529 | val 0.10713
  Epoch 021 - train 0.10355 | val 0.10730
  Regression -> MSE: 0.000173, MAE: 0.009811, R²: -0.0040
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09914 | val 0.10498
  Epoch 020 - train 0.09956 | val 0.10423
  Epoch 021 - train 0.09552 | val 0.10416
  Regression -> MSE: 0.000228, MAE: 0.011874, R²: -0.0232
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10063 | val 0.11528
  Epoch 020 - train 0.10378 | val 0.11916
  Epoch 021 - train 0.09992 | val 0.11890

[I 2026-02-24 02:29:19,128] Trial 116 finished with value: -0.011429675629807411 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 6.17742268647635e-06, 'weight_decay': 9.595234908295253e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.13538147130428074, 'early_stopping_min_delta': 0.004749967461411344}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 028 - train 0.10207 | val 0.12472
  Regression -> MSE: 0.000246, MAE: 0.012502, R²: -0.0392
  Directional -> Accuracy: 0.5410, MCC: 0.0692, F1: 0.2222

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10362 | val 0.15913
  Epoch 020 - train 0.10093 | val 0.16074
  Epoch 021 - train 0.10476 | val 0.16046
  Regression -> MSE: 0.000258, MAE: 0.012941, R²: -0.0420
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10993 | val 0.12721
  Epoch 020 - train 0.11174 | val 0.14958
  Epoch 021 - train 0.10959 | val 0.14954
  Regression -> MSE: 0.000685, MAE: 0.019404, R²: -0.0007
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10904 | val 0.16455
  Epoch 020 - train 0.10436 | val 0.17984
  Epoch 021 - train 0.10715 | val 0.17988
  Regression -> MSE: 0.000328, MAE: 0.014600, R²: -0.0587
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08824 | val 0.14680
  Epoch 020 - train 0.08567 | val 0.15676
  Epoch 021 - train 0.08735 | val 0.15520
  Regression -> MSE: 0.000354, MAE: 0.014668, R²: -0.0143
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10490 | val 0.10204
  Epoch 020 - train 0.10787 | val 0.10596
  Epoch 021 - train 0.10398 | val 0.10591
  Regression -> MSE: 0.000204, MAE: 0.010213, R²: -0.0028
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10321 | val 0.19315
  Epoch 020 - train 0.09052 | val 0.25871
  Epoch 021 - train 0.10043 | val 0.26053
  Regression -> MSE: 0.000562, MAE: 0.018199, R²: -0.0125
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10255 | val 0.12349
  Epoch 020 - train 0.10313 | val 0.12522
  Epoch 021 - train 0.10417 | val 0.12502
  Regression -> MSE: 0.000246, MAE: 0.012166, R²: -0.0005
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10839 | val 0.14810
  Epoch 020 - train 0.11041 | val 0.19078
  Epoch 021 - train 0.10176 | val 0.19567
  Regression -> MSE: 0.000654, MAE: 0.020298, R²: -0.0939
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09950 | val 0.11824
  Epoch 020 - train 0.10048 | val 0.12080
  Epoch 021 - train 0.10621 | val 0.12092
  Regression -> MSE: 0.000397, MAE: 0.016004, R²: -0.0361
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10917 | val 0.13204
  Epoch 020 - train 0.10674 | val 0.13543
  Epoch 021 - train 0.10835 | val 0.13581
  Regression -> MSE: 0.000242, MAE: 0.011835, R²: -0.0022
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09391 | val 0.14809
  Epoch 020 - train 0.09546 | val 0.15639
  Epoch 021 - train 0.09662 | val 0.15580
  Regression -> MSE: 0.000315, MAE: 0.013611, R²: -0.0147
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10540 | val 0.11513
  Epoch 020 - train 0.10469 | val 0.11754
  Epoch 021 - train 0.10564 | val 0.11753
  Regression -> MSE: 0.000683, MAE: 0.019691, R²: -0.0081
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11113 | val 0.10594
  Epoch 020 - train 0.11083 | val 0.11089
  Epoch 021 - train 0.11197 | val 0.11045
  Regression -> MSE: 0.000138, MAE: 0.009036, R²: -0.0009
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09836 | val 0.12707
  Epoch 020 - train 0.09603 | val 0.12739
  Epoch 021 - train 0.10070 | val 0.12741
  Regression -> MSE: 0.000231, MAE: 0.010908, R²: -0.0261
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09857 | val 0.19756
  Epoch 020 - train 0.10460 | val 0.19562
  Epoch 021 - train 0.10061 | val 0.19537
  Regression -> MSE: 0.000363, MAE: 0.016180, R²: -0.0013
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10835 | val 0.11411
  Epoch 020 - train 0.10878 | val 0.11713
  Epoch 021 - train 0.10788 | val 0.11705
  Regression -> MSE: 0.000108, MAE: 0.008018, R²: -0.0017
  Directional -> Accuracy: 0.4000, MCC: -0.1984, F1: 0.4167

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12205 | val 0.21808
  Epoch 020 - train 0.12294 | val 0.25984
  Epoch 021 - train 0.11993 | val 0.25853
  Regression -> MSE: 0.000167, MAE: 0.010419, R²: -0.0711
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10472 | val 0.10676
  Epoch 020 - train 0.10530 | val 0.10573
  Epoch 021 - train 0.11243 | val 0.10525
  Regression -> MSE: 0.000273, MAE: 0.013080, R²: -0.0036
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09882 | val 0.12915
  Epoch 020 - train 0.09309 | val 0.12812
  Epoch 021 - train 0.09142 | val 0.12823
  Regression -> MSE: 0.000167, MAE: 0.009143, R²: -0.1195
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10888 | val 0.14671
  Epoch 020 - train 0.10572 | val 0.14945
  Epoch 021 - train 0.10556 | val 0.14974
  Regression -> MSE: 0.000228, MAE: 0.010938, R²: -0.0055
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10692 | val 0.12716
  Epoch 020 - train 0.10253 | val 0.13961
  Epoch 021 - train 0.09880 | val 0.14031
  Regression -> MSE: 0.000149, MAE: 0.008655, R²: -0.0390
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10329 | val 0.12259
  Epoch 020 - train 0.10126 | val 0.12240
  Epoch 021 - train 0.10489 | val 0.12221
  Regression -> MSE: 0.000178, MAE: 0.010309, R²: -0.0763
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10320 | val 0.12014
  Epoch 020 - train 0.10125 | val 0.12427
  Epoch 021 - train 0.10595 | val 0.12449
  Regression -> MSE: 0.000088, MAE: 0.007229, R²: -0.0382
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10679 | val 0.16661
  Epoch 020 - train 0.10479 | val 0.16241
  Epoch 021 - train 0.10374 | val 0.16106
  Regression -> MSE: 0.000215, MAE: 0.011498, R²: -0.0165
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09775 | val 0.09102
  Epoch 020 - train 0.09522 | val 0.09089
  Epoch 021 - train 0.09280 | val 0.09110
  Regression -> MSE: 0.000096, MAE: 0.008139, R²: -0.0470
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10151 | val 0.07752
  Epoch 020 - train 0.10137 | val 0.08066
  Epoch 021 - train 0.11008 | val 0.08147
  Regression -> MSE: 0.000103, MAE: 0.008717, R²: -0.0011
  Directional -> Accuracy: 0.6087, MCC: 0.2385, F1: 0.6087

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10773 | val 0.09552
  Epoch 020 - train 0.10522 | val 0.10023
  Epoch 021 - train 0.10381 | val 0.10042
  Regression -> MSE: 0.000233, MAE: 0.012594, R²: -0.0071
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10448 | val 0.11447
  Epoch 020 - train 0.10343 | val 0.11381
  Epoch 021 - train 0.09957 | val 0.11381
  Regression -> MSE: 0.000174, MAE: 0.007857, R²: -0.0464
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10444 | val 0.08651
  Epoch 020 - train 0.10503 | val 0.09058
  Epoch 021 - train 0.10602 | val 0.09078
  Regression -> MSE: 0.000236, MAE: 0.011852, R²: 0.0006
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10779 | val 0.16963
  Epoch 020 - train 0.10723 | val 0.20433
  Epoch 021 - train 0.10607 | val 0.20559
  Regression -> MSE: 0.000236, MAE: 0.010214, R²: -0.0226
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10728 | val 0.12349
  Epoch 020 - train 0.10648 | val 0.13707
  Epoch 021 - train 0.11087 | val 0.13760
  Regression -> MSE: 0.000137, MAE: 0.008275, R²: -0.0140
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10932 | val 0.12862
  Epoch 020 - train 0.10100 | val 0.13292
  Epoch 021 - train 0.10471 | val 0.13295
  Regression -> MSE: 0.000191, MAE: 0.010380, R²: -0.0118
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09204 | val 0.12291
  Epoch 020 - train 0.09462 | val 0.12186
  Epoch 021 - train 0.09604 | val 0.12181
  Regression -> MSE: 0.000271, MAE: 0.010673, R²: -0.0368
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10297 | val 0.08651
  Epoch 020 - train 0.09801 | val 0.09144
  Epoch 021 - train 0.10237 | val 0.09253
  Regression -> MSE: 0.000167, MAE: 0.010378, R²: -0.0029
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09918 | val 0.10806
  Epoch 020 - train 0.09777 | val 0.11596
  Epoch 021 - train 0.10265 | val 0.11571
  Regression -> MSE: 0.000187, MAE: 0.010614, R²: -0.0408
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10285 | val 0.09655
  Epoch 020 - train 0.09619 | val 0.09684
  Epoch 021 - train 0.09801 | val 0.09685
  Regression -> MSE: 0.000353, MAE: 0.012549, R²: -0.0293
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11168 | val 0.06911
  Epoch 020 - train 0.11139 | val 0.08601
  Epoch 021 - train 0.11034 | val 0.08715
  Regression -> MSE: 0.000111, MAE: 0.008309, R²: -0.0551
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10782 | val 0.13705
  Epoch 020 - train 0.10314 | val 0.13982
  Epoch 021 - train 0.10974 | val 0.13987
  Regression -> MSE: 0.000219, MAE: 0.011307, R²: -0.0008
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09723 | val 0.16955
  Epoch 020 - train 0.09694 | val 0.18113
  Epoch 021 - train 0.09686 | val 0.18050
  Regression -> MSE: 0.000090, MAE: 0.007421, R²: -0.1583
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10055 | val 0.07900
  Epoch 020 - train 0.10755 | val 0.08066
  Epoch 021 - train 0.10486 | val 0.08084
  Regression -> MSE: 0.000319, MAE: 0.014428, R²: -0.0357
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10818 | val 0.06157
  Epoch 020 - train 0.11166 | val 0.06296
  Epoch 021 - train 0.10890 | val 0.06325
  Regression -> MSE: 0.000250, MAE: 0.011511, R²: -0.0246
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09691 | val 0.11646
  Epoch 020 - train 0.09799 | val 0.11540
  Epoch 021 - train 0.09371 | val 0.11525
  Regression -> MSE: 0.000081, MAE: 0.007056, R²: -0.0064
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10507 | val 0.12582
  Epoch 020 - train 0.10410 | val 0.11753
  Epoch 030 - train 0.10139 | val 0.11673
  Regression -> MSE: 0.000297, MAE: 0.014302, R²: 0.0321
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10130 | val 0.11479
  Epoch 020 - train 0.09992 | val 0.11380
  Epoch 021 - train 0.10291 | val 0.11390
  Regression -> MSE: 0.000100, MAE: 0.007124, R²: -0.0230
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11710 | val 0.11629
  Epoch 020 - train 0.11384 | val 0.11687
  Epoch 021 - train 0.11380 | val 0.11718
  Regression -> MSE: 0.000175, MAE: 0.010102, R²: -0.0159
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09828 | val 0.11155
  Epoch 020 - train 0.09386 | val 0.11420
  Epoch 021 - train 0.09764 | val 0.11441
  Regression -> MSE: 0.000226, MAE: 0.011816, R²: -0.0130
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10332 | val 0.11442
  Epoch 020 - train 0.09969 | val 0.11434
  Epoch 021 - train 0.10221 | val 0.11428
  Regression -> MSE: 0.000093, MAE: 0.007675, R²: -0.0046

[I 2026-02-24 02:31:27,481] Trial 117 finished with value: -0.011481639922961771 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.1, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 6.161700843526895e-06, 'weight_decay': 5.4485840461407165e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.145367167574399, 'early_stopping_min_delta': 0.007389113340243054}. Best is trial 44 with value: -0.011362814469631832.

  Regression -> MSE: 0.000236, MAE: 0.012352, R²: 0.0045
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 12
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13945 | val 0.15948
  Epoch 020 - train 0.12229 | val 0.15864
  Epoch 024 - train 0.12642 | val 0.15995
  Regression -> MSE: 0.000262, MAE: 0.013124, R²: -0.0690
  Directional -> Accuracy: 0.4487, MCC: 0.0000, F1: 0.6195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 88). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14278 | val 0.11938
  Epoch 020 - train 0.13787 | val 0.11709
  Epoch 021 - train 0.13213 | val 0.11682
  Regression -> MSE: 0.000720, MAE: 0.020085, R²: -0.0413
  Directional -> Accuracy: 0.4468, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 88). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16218 | val 0.26819
  Epoch 020 - train 0.16327 | val 0.26303
  Epoch 021 - train 0.16166 | val 0.26329
  Regression -> MSE: 0.000347, MAE: 0.015145, R²: -0.0036
  Directional -> Accuracy: 0.5417, MCC: 0.0000, F1: 0.7027

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12722 | val 0.22359
  Epoch 020 - train 0.12828 | val 0.22478
  Epoch 021 - train 0.12393 | val 0.23018
  Regression -> MSE: 0.000392, MAE: 0.015243, R²: -0.1370
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13129 | val 0.12531
  Epoch 020 - train 0.13894 | val 0.12506
  Epoch 021 - train 0.13588 | val 0.12466
  Regression -> MSE: 0.000208, MAE: 0.010647, R²: -0.0370
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13240 | val 0.23150
  Epoch 020 - train 0.12961 | val 0.23148
  Epoch 021 - train 0.12839 | val 0.23204
  Regression -> MSE: 0.000581, MAE: 0.018440, R²: -0.0144
  Directional -> Accuracy: 0.4898, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13826 | val 0.16190
  Epoch 020 - train 0.13916 | val 0.16261
  Epoch 021 - train 0.13621 | val 0.16270
  Regression -> MSE: 0.000248, MAE: 0.012391, R²: -0.0099
  Directional -> Accuracy: 0.4000, MCC: 0.0000, F1: 0.5714

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 88). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 88). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14852 | val 0.17503
  Epoch 020 - train 0.14197 | val 0.19585
  Epoch 021 - train 0.15073 | val 0.19273
  Regression -> MSE: 0.000609, MAE: 0.019322, R²: -0.0421
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14053 | val 0.21060
  Epoch 020 - train 0.13888 | val 0.20674
  Epoch 021 - train 0.13543 | val 0.20722
  Regression -> MSE: 0.000341, MAE: 0.014828, R²: -0.0099
  Directional -> Accuracy: 0.6190, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 88). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 88). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13797 | val 0.18186
  Epoch 020 - train 0.14011 | val 0.19177
  Epoch 021 - train 0.13339 | val 0.19193
  Regression -> MSE: 0.000239, MAE: 0.011658, R²: -0.0024
  Directional -> Accuracy: 0.4366, MCC: 0.0000, F1: 0.6078

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14073 | val 0.25011
  Epoch 020 - train 0.13781 | val 0.26034
  Epoch 021 - train 0.13228 | val 0.25616
  Regression -> MSE: 0.000318, MAE: 0.013553, R²: -0.0388
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15332 | val 0.26039
  Epoch 020 - train 0.14792 | val 0.26002
  Epoch 021 - train 0.14296 | val 0.25774
  Regression -> MSE: 0.000676, MAE: 0.019603, R²: -0.0101
  Directional -> Accuracy: 0.5085, MCC: 0.0000, F1: 0.6742

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12505 | val 0.13991
  Epoch 020 - train 0.13540 | val 0.13749
  Epoch 021 - train 0.14189 | val 0.13759
  Regression -> MSE: 0.000153, MAE: 0.009769, R²: -0.0194
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 88). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13140 | val 0.16210
  Epoch 020 - train 0.12628 | val 0.16302
  Epoch 021 - train 0.13145 | val 0.16230
  Regression -> MSE: 0.000225, MAE: 0.010747, R²: -0.0003
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6437

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14311 | val 0.27785
  Epoch 020 - train 0.13999 | val 0.27313
  Epoch 021 - train 0.13127 | val 0.27229
  Regression -> MSE: 0.000388, MAE: 0.016331, R²: -0.0310
  Directional -> Accuracy: 0.5283, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14758 | val 0.15845
  Epoch 020 - train 0.13794 | val 0.16065
  Epoch 021 - train 0.14813 | val 0.16091
  Regression -> MSE: 0.000106, MAE: 0.007880, R²: -0.0010
  Directional -> Accuracy: 0.5352, MCC: 0.0000, F1: 0.6972

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for proper time series validation for DHR. Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12708 | val 0.22192
  Epoch 020 - train 0.13055 | val 0.22159
  Epoch 021 - train 0.13622 | val 0.22306
  Regression -> MSE: 0.000162, MAE: 0.010113, R²: -0.0139
  Directional -> Accuracy: 0.6167, MCC: 0.0000, F1: 0.7629

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13637 | val 0.16375
  Epoch 020 - train 0.13822 | val 0.15146
  Epoch 021 - train 0.14192 | val 0.15258
  Regression -> MSE: 0.000270, MAE: 0.012886, R²: -0.0067
  Directional -> Accuracy: 0.6104, MCC: 0.0000, F1: 0.7581

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13507 | val 0.17171
  Epoch 020 - train 0.12791 | val 0.17020
  Epoch 021 - train 0.12608 | val 0.16893
  Regression -> MSE: 0.000157, MAE: 0.008769, R²: -0.0678
  Directional -> Accuracy: 0.4697, MCC: -0.2056, F1: 0.6154

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 88). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14578 | val 0.19446
  Epoch 020 - train 0.14906 | val 0.19138
  Epoch 021 - train 0.15702 | val 0.19036
  Regression -> MSE: 0.000243, MAE: 0.011163, R²: -0.0740
  Directional -> Accuracy: 0.4605, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14097 | val 0.16321
  Epoch 020 - train 0.13919 | val 0.16272
  Epoch 021 - train 0.13896 | val 0.16203
  Regression -> MSE: 0.000157, MAE: 0.008979, R²: -0.0616
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.7750

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 88). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 88). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 88). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13849 | val 0.17916
  Epoch 020 - train 0.13696 | val 0.17671
  Epoch 021 - train 0.13471 | val 0.17782
  Regression -> MSE: 0.000178, MAE: 0.010883, R²: -0.0030
  Directional -> Accuracy: 0.5075, MCC: 0.0000, F1: 0.6733

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14792 | val 0.15452
  Epoch 020 - train 0.14897 | val 0.15762
  Epoch 021 - train 0.13987 | val 0.15789
  Regression -> MSE: 0.000089, MAE: 0.007254, R²: -0.0656
  Directional -> Accuracy: 0.4237, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14296 | val 0.16903
  Epoch 020 - train 0.13693 | val 0.16454
  Epoch 021 - train 0.13516 | val 0.16417
  Regression -> MSE: 0.000218, MAE: 0.011353, R²: 0.0030
  Directional -> Accuracy: 0.4776, MCC: 0.0000, F1: 0.6465

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12320 | val 0.10314
  Epoch 020 - train 0.11935 | val 0.10218
  Epoch 028 - train 0.12180 | val 0.10233
  Regression -> MSE: 0.000107, MAE: 0.008508, R²: -0.1663
  Directional -> Accuracy: 0.4386, MCC: -0.1304, F1: 0.4839

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14238 | val 0.08663
  Epoch 020 - train 0.14243 | val 0.09143
  Epoch 021 - train 0.13912 | val 0.09112
  Regression -> MSE: 0.000146, MAE: 0.009909, R²: -0.1652
  Directional -> Accuracy: 0.4167, MCC: 0.0000, F1: 0.5882

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14306 | val 0.16703
  Epoch 020 - train 0.13710 | val 0.15811
  Epoch 021 - train 0.14204 | val 0.15678
  Regression -> MSE: 0.000241, MAE: 0.012868, R²: -0.0126
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.7429

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14299 | val 0.15470
  Epoch 020 - train 0.14028 | val 0.15215
  Epoch 021 - train 0.14250 | val 0.15141
  Regression -> MSE: 0.000168, MAE: 0.007729, R²: -0.0273
  Directional -> Accuracy: 0.5517, MCC: 0.0000, F1: 0.7111

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14662 | val 0.10416
  Epoch 020 - train 0.14190 | val 0.11237
  Epoch 021 - train 0.14449 | val 0.11214
  Regression -> MSE: 0.000234, MAE: 0.011909, R²: -0.0003
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.15011 | val 0.24290
  Epoch 020 - train 0.14510 | val 0.24880
  Epoch 021 - train 0.14770 | val 0.24606
  Regression -> MSE: 0.000249, MAE: 0.010484, R²: 0.0036
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16343 | val 0.23719
  Epoch 020 - train 0.14722 | val 0.24954
  Epoch 021 - train 0.15379 | val 0.24670
  Regression -> MSE: 0.000140, MAE: 0.008629, R²: -0.0547
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14616 | val 0.16455
  Epoch 020 - train 0.13676 | val 0.16474
  Epoch 021 - train 0.14836 | val 0.16457
  Regression -> MSE: 0.000189, MAE: 0.010440, R²: -0.0011
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12354 | val 0.16779
  Epoch 020 - train 0.12515 | val 0.16662
  Epoch 021 - train 0.12893 | val 0.16731
  Regression -> MSE: 0.000261, MAE: 0.010439, R²: -0.0101
  Directional -> Accuracy: 0.5676, MCC: 0.0000, F1: 0.7241

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 88). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13589 | val 0.12276
  Epoch 020 - train 0.13049 | val 0.12745
  Epoch 021 - train 0.12394 | val 0.13030
  Regression -> MSE: 0.000162, MAE: 0.010173, R²: 0.0015
  Directional -> Accuracy: 0.4872, MCC: 0.0000, F1: 0.6552

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12253 | val 0.13819
  Epoch 020 - train 0.12974 | val 0.13842
  Epoch 021 - train 0.11195 | val 0.13957
  Regression -> MSE: 0.000185, MAE: 0.010536, R²: -0.0118
  Directional -> Accuracy: 0.4667, MCC: 0.0000, F1: 0.6364

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12923 | val 0.11724
  Epoch 020 - train 0.12886 | val 0.11828
  Epoch 021 - train 0.12681 | val 0.11840
  Regression -> MSE: 0.000349, MAE: 0.011992, R²: 0.0003
  Directional -> Accuracy: 0.5735, MCC: 0.0000, F1: 0.7290

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14584 | val 0.09641
  Epoch 020 - train 0.14179 | val 0.09744
  Epoch 021 - train 0.14006 | val 0.09722
  Regression -> MSE: 0.000117, MAE: 0.008223, R²: -0.1312
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14136 | val 0.17177
  Epoch 020 - train 0.13846 | val 0.17237
  Epoch 021 - train 0.13718 | val 0.17250
  Regression -> MSE: 0.000216, MAE: 0.011213, R²: -0.0039
  Directional -> Accuracy: 0.5172, MCC: -0.0403, F1: 0.1250

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13312 | val 0.25489
  Epoch 020 - train 0.13820 | val 0.26332
  Epoch 021 - train 0.12700 | val 0.26222
  Regression -> MSE: 0.000090, MAE: 0.007438, R²: -0.1268
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 88). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 88). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 88). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 88). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14552 | val 0.10536
  Epoch 020 - train 0.15368 | val 0.10436
  Epoch 021 - train 0.14539 | val 0.10468
  Regression -> MSE: 0.000330, MAE: 0.014341, R²: -0.0055
  Directional -> Accuracy: 0.6500, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 88). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13983 | val 0.08910
  Epoch 020 - train 0.14141 | val 0.09623
  Epoch 021 - train 0.15703 | val 0.09578
  Regression -> MSE: 0.000243, MAE: 0.011270, R²: -0.0200
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.7000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 88). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 88). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13218 | val 0.15935
  Epoch 020 - train 0.13089 | val 0.16082
  Epoch 021 - train 0.13585 | val 0.16026
  Regression -> MSE: 0.000081, MAE: 0.007054, R²: -0.0074
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for proper time series validation for TOT. Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 88). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 88). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 88). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12764 | val 0.16293
  Epoch 020 - train 0.13379 | val 0.16249
  Epoch 021 - train 0.14494 | val 0.15899
  Regression -> MSE: 0.000363, MAE: 0.015316, R²: -0.0087
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13071 | val 0.15925
  Epoch 020 - train 0.13372 | val 0.16296
  Epoch 021 - train 0.13055 | val 0.16323
  Regression -> MSE: 0.000097, MAE: 0.007200, R²: -0.0029
  Directional -> Accuracy: 0.5556, MCC: 0.0000, F1: 0.7143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13994 | val 0.17776
  Epoch 020 - train 0.14438 | val 0.18595
  Epoch 021 - train 0.14428 | val 0.18658
  Regression -> MSE: 0.000181, MAE: 0.009886, R²: -0.0018
  Directional -> Accuracy: 0.6341, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13890 | val 0.17511
  Epoch 020 - train 0.13693 | val 0.16218
  Epoch 021 - train 0.13568 | val 0.16006
  Regression -> MSE: 0.000221, MAE: 0.011678, R²: -0.0050
  Directional -> Accuracy: 0.5439, MCC: 0.0000, F1: 0.7045

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13304 | val 0.20496
  Epoch 020 - train 0.13281 | val 0.20945
  Epoch 021 - train 0.13625 | val 0.20558
  Regression -> MSE: 0.000093, MAE: 0.007694, R²: -0.0168

[I 2026-02-24 02:33:37,123] Trial 118 finished with value: -0.011529190811040107 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 12, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 1.1523418858542627e-05, 'weight_decay': 8.845842638691537e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.19841117472200154, 'early_stopping_min_delta': 0.006762015277081087}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.14858 | val 0.19181
  Epoch 021 - train 0.15578 | val 0.19132
  Regression -> MSE: 0.000240, MAE: 0.012262, R²: -0.0292
  Directional -> Accuracy: 0.5161, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10414 | val 0.13109
  Epoch 020 - train 0.10127 | val 0.13141
  Epoch 021 - train 0.10305 | val 0.13135
  Regression -> MSE: 0.000258, MAE: 0.012942, R²: -0.0407
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09832 | val 0.09809
  Epoch 020 - train 0.09479 | val 0.09146
  Epoch 021 - train 0.10445 | val 0.09107
  Regression -> MSE: 0.000684, MAE: 0.019307, R²: 0.0005
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11311 | val 0.15990
  Epoch 020 - train 0.10618 | val 0.16442
  Epoch 021 - train 0.10613 | val 0.16422
  Regression -> MSE: 0.000326, MAE: 0.014551, R²: -0.0513
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08893 | val 0.09506
  Epoch 020 - train 0.08783 | val 0.09360
  Epoch 021 - train 0.08821 | val 0.09309
  Regression -> MSE: 0.000355, MAE: 0.014689, R²: -0.0157
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11281 | val 0.10017
  Epoch 020 - train 0.11009 | val 0.10079
  Epoch 021 - train 0.10347 | val 0.10095
  Regression -> MSE: 0.000205, MAE: 0.010316, R²: -0.0058
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10506 | val 0.18156
  Epoch 020 - train 0.09888 | val 0.21266
  Epoch 021 - train 0.10617 | val 0.21327
  Regression -> MSE: 0.000555, MAE: 0.018137, R²: 0.0003
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10295 | val 0.12598
  Epoch 020 - train 0.10621 | val 0.12699
  Epoch 021 - train 0.10467 | val 0.12675
  Regression -> MSE: 0.000249, MAE: 0.011931, R²: -0.0148
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10462 | val 0.12146
  Epoch 020 - train 0.10033 | val 0.11174
  Epoch 030 - train 0.09834 | val 0.11455
  Regression -> MSE: 0.000596, MAE: 0.019070, R²: 0.0023
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10359 | val 0.12196
  Epoch 020 - train 0.10192 | val 0.11744
  Epoch 021 - train 0.10270 | val 0.11761
  Regression -> MSE: 0.000384, MAE: 0.016119, R²: -0.0023
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10178 | val 0.14125
  Epoch 020 - train 0.09909 | val 0.15107
  Epoch 021 - train 0.10330 | val 0.14911
  Regression -> MSE: 0.000242, MAE: 0.012050, R²: -0.0044
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09945 | val 0.13541
  Epoch 020 - train 0.09581 | val 0.13373
  Epoch 030 - train 0.09340 | val 0.13340
  Regression -> MSE: 0.000444, MAE: 0.015882, R²: -0.4287
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10703 | val 0.11686
  Epoch 020 - train 0.10178 | val 0.11991
  Epoch 021 - train 0.09909 | val 0.12032
  Regression -> MSE: 0.000681, MAE: 0.019519, R²: -0.0058
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10713 | val 0.10064
  Epoch 020 - train 0.10286 | val 0.13668
  Epoch 021 - train 0.11068 | val 0.13739
  Regression -> MSE: 0.000142, MAE: 0.009370, R²: -0.0256
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10119 | val 0.12948
  Epoch 020 - train 0.09816 | val 0.13123
  Epoch 021 - train 0.09617 | val 0.13138
  Regression -> MSE: 0.000228, MAE: 0.010791, R²: -0.0150
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10378 | val 0.19413
  Epoch 020 - train 0.10031 | val 0.19978
  Epoch 021 - train 0.09901 | val 0.19996
  Regression -> MSE: 0.000363, MAE: 0.016043, R²: -0.0032
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10837 | val 0.10423
  Epoch 020 - train 0.10994 | val 0.10156
  Epoch 021 - train 0.10663 | val 0.10150
  Regression -> MSE: 0.000108, MAE: 0.007947, R²: -0.0047
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10277 | val 0.16981
  Epoch 020 - train 0.09933 | val 0.17774
  Epoch 021 - train 0.10094 | val 0.17926
  Regression -> MSE: 0.000161, MAE: 0.010131, R²: -0.0312
  Directional -> Accuracy: 0.4576, MCC: 0.1322, F1: 0.3043

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10775 | val 0.10863
  Epoch 020 - train 0.10013 | val 0.10828
  Epoch 021 - train 0.10408 | val 0.10819
  Regression -> MSE: 0.000274, MAE: 0.012969, R²: -0.0072
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09432 | val 0.13430
  Epoch 020 - train 0.09650 | val 0.13358
  Epoch 021 - train 0.09875 | val 0.13346
  Regression -> MSE: 0.000154, MAE: 0.008744, R²: -0.0299
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10842 | val 0.14550
  Epoch 020 - train 0.10635 | val 0.14518
  Epoch 021 - train 0.10670 | val 0.14543
  Regression -> MSE: 0.000241, MAE: 0.011107, R²: -0.0654
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10600 | val 0.12044
  Epoch 020 - train 0.10049 | val 0.12510
  Epoch 021 - train 0.11043 | val 0.12661
  Regression -> MSE: 0.000144, MAE: 0.008378, R²: -0.0056
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10090 | val 0.11599
  Epoch 020 - train 0.09597 | val 0.11636
  Epoch 021 - train 0.09838 | val 0.11644
  Regression -> MSE: 0.000173, MAE: 0.010271, R²: -0.0496
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11181 | val 0.11099
  Epoch 020 - train 0.10505 | val 0.11090
  Epoch 021 - train 0.10332 | val 0.11088
  Regression -> MSE: 0.000088, MAE: 0.007212, R²: -0.0375
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10423 | val 0.12288
  Epoch 020 - train 0.09840 | val 0.12963
  Epoch 021 - train 0.09917 | val 0.12869
  Regression -> MSE: 0.000212, MAE: 0.011135, R²: 0.0001
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09981 | val 0.09208
  Epoch 020 - train 0.09027 | val 0.09019
  Epoch 021 - train 0.10090 | val 0.08992
  Regression -> MSE: 0.000103, MAE: 0.008276, R²: -0.1206
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11628 | val 0.07918
  Epoch 020 - train 0.11590 | val 0.08050
  Epoch 021 - train 0.10946 | val 0.08076
  Regression -> MSE: 0.000109, MAE: 0.009010, R²: -0.0597
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11432 | val 0.09672
  Epoch 020 - train 0.11423 | val 0.10334
  Epoch 021 - train 0.10637 | val 0.10362
  Regression -> MSE: 0.000238, MAE: 0.012789, R²: -0.0283
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10607 | val 0.11279
  Epoch 020 - train 0.10387 | val 0.11346
  Epoch 021 - train 0.10534 | val 0.11323
  Regression -> MSE: 0.000195, MAE: 0.008330, R²: -0.1689
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11277 | val 0.08735
  Epoch 020 - train 0.10341 | val 0.08860
  Epoch 021 - train 0.10412 | val 0.08934
  Regression -> MSE: 0.000238, MAE: 0.011943, R²: -0.0079
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11258 | val 0.15054
  Epoch 020 - train 0.11017 | val 0.14806
  Epoch 021 - train 0.11054 | val 0.14830
  Regression -> MSE: 0.000231, MAE: 0.009871, R²: -0.0017
  Directional -> Accuracy: 0.4884, MCC: -0.0288, F1: 0.4211

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11138 | val 0.11206
  Epoch 020 - train 0.10772 | val 0.12716
  Epoch 021 - train 0.11157 | val 0.12734
  Regression -> MSE: 0.000135, MAE: 0.008179, R²: -0.0031
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10774 | val 0.12982
  Epoch 020 - train 0.10989 | val 0.13513
  Epoch 021 - train 0.10229 | val 0.13495
  Regression -> MSE: 0.000189, MAE: 0.010561, R²: -0.0019
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09441 | val 0.11428
  Epoch 020 - train 0.09158 | val 0.11375
  Epoch 021 - train 0.09140 | val 0.11454
  Regression -> MSE: 0.000269, MAE: 0.010591, R²: -0.0255
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09765 | val 0.08520
  Epoch 020 - train 0.09331 | val 0.08586
  Epoch 021 - train 0.09064 | val 0.08658
  Regression -> MSE: 0.000167, MAE: 0.010369, R²: -0.0046
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09864 | val 0.10065
  Epoch 020 - train 0.10120 | val 0.10503
  Epoch 021 - train 0.10020 | val 0.10476
  Regression -> MSE: 0.000180, MAE: 0.010298, R²: -0.0027
  Directional -> Accuracy: 0.4545, MCC: -0.0981, F1: 0.4000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10682 | val 0.09727
  Epoch 020 - train 0.10487 | val 0.09660
  Epoch 021 - train 0.10350 | val 0.09660
  Regression -> MSE: 0.000345, MAE: 0.011978, R²: -0.0073
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11904 | val 0.06598
  Epoch 020 - train 0.10747 | val 0.07386
  Epoch 021 - train 0.10532 | val 0.07476
  Regression -> MSE: 0.000124, MAE: 0.008446, R²: -0.1786
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10255 | val 0.13278
  Epoch 020 - train 0.10434 | val 0.13325
  Epoch 021 - train 0.10195 | val 0.13327
  Regression -> MSE: 0.000224, MAE: 0.011456, R²: -0.0256
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10804 | val 0.16375
  Epoch 020 - train 0.10542 | val 0.16816
  Epoch 021 - train 0.10089 | val 0.16817
  Regression -> MSE: 0.000098, MAE: 0.007707, R²: -0.2566
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10971 | val 0.08763
  Epoch 020 - train 0.10489 | val 0.09028
  Epoch 021 - train 0.10943 | val 0.09023
  Regression -> MSE: 0.000345, MAE: 0.015524, R²: -0.1224
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11089 | val 0.06287
  Epoch 020 - train 0.11093 | val 0.06200
  Epoch 021 - train 0.10863 | val 0.06232
  Regression -> MSE: 0.000255, MAE: 0.011464, R²: -0.0452
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10493 | val 0.11190
  Epoch 020 - train 0.09803 | val 0.11508
  Epoch 021 - train 0.10026 | val 0.11513
  Regression -> MSE: 0.000081, MAE: 0.007103, R²: -0.0038
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10378 | val 0.12111
  Epoch 020 - train 0.10328 | val 0.11980
  Epoch 021 - train 0.09533 | val 0.11975
  Regression -> MSE: 0.000307, MAE: 0.014483, R²: -0.0004
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09939 | val 0.10070
  Epoch 020 - train 0.10201 | val 0.09935
  Epoch 021 - train 0.10543 | val 0.09916
  Regression -> MSE: 0.000099, MAE: 0.007434, R²: -0.0054
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11327 | val 0.11683
  Epoch 020 - train 0.10538 | val 0.11965
  Epoch 021 - train 0.11414 | val 0.11988
  Regression -> MSE: 0.000172, MAE: 0.009586, R²: 0.0012
  Directional -> Accuracy: 0.6531, MCC: 0.2497, F1: 0.5143

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10226 | val 0.12019
  Epoch 020 - train 0.09859 | val 0.12244
  Epoch 021 - train 0.10007 | val 0.12158
  Regression -> MSE: 0.000223, MAE: 0.011762, R²: -0.0010
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10537 | val 0.11776
  Epoch 020 - train 0.10043 | val 0.11977
  Epoch 021 - train 0.10864 | val 0.12019

[I 2026-02-24 02:35:44,272] Trial 119 finished with value: -0.01149976761720409 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 1.3894308222355178e-05, 'weight_decay': 1.7172987137393458e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.1430320725043452, 'early_stopping_min_delta': 0.007636614135665977}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.10733 | val 0.14713
  Epoch 021 - train 0.10567 | val 0.14640
  Regression -> MSE: 0.000242, MAE: 0.012340, R²: -0.0187
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 24
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15979 | val 0.20117
  Epoch 011 - train 0.16036 | val 0.20219
  Regression -> MSE: 0.000242, MAE: 0.012387, R²: -0.0059
  Directional -> Accuracy: 0.4474, MCC: 0.0000, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 100). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14675 | val 0.14505
  Epoch 011 - train 0.15903 | val 0.14608
  Regression -> MSE: 0.000717, MAE: 0.019983, R²: -0.0274
  Directional -> Accuracy: 0.3556, MCC: -0.2538, F1: 0.1212

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 100). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16449 | val 0.24227
  Epoch 011 - train 0.15620 | val 0.24125
  Regression -> MSE: 0.000318, MAE: 0.014485, R²: -0.0100
  Directional -> Accuracy: 0.4783, MCC: -0.2041, F1: 0.6471

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13596 | val 0.21497
  Epoch 011 - train 0.13753 | val 0.21213
  Regression -> MSE: 0.000360, MAE: 0.014787, R²: -0.0195
  Directional -> Accuracy: 0.5405, MCC: 0.0000, F1: 0.7018

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16509 | val 0.16313
  Epoch 011 - train 0.16781 | val 0.16551
  Regression -> MSE: 0.000208, MAE: 0.010354, R²: -0.0092
  Directional -> Accuracy: 0.4800, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15123 | val 0.26914
  Epoch 011 - train 0.14946 | val 0.26836
  Regression -> MSE: 0.000587, MAE: 0.018666, R²: -0.0370
  Directional -> Accuracy: 0.5217, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16084 | val 0.19414
  Epoch 011 - train 0.16948 | val 0.19297
  Regression -> MSE: 0.000249, MAE: 0.012172, R²: -0.0031
  Directional -> Accuracy: 0.3971, MCC: 0.0000, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 100). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 100). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15758 | val 0.12974
  Epoch 011 - train 0.16587 | val 0.12971
  Regression -> MSE: 0.000616, MAE: 0.019535, R²: -0.0077
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14745 | val 0.18997
  Epoch 011 - train 0.15919 | val 0.18986
  Regression -> MSE: 0.000376, MAE: 0.015711, R²: -0.0086
  Directional -> Accuracy: 0.4375, MCC: 0.0000, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 100). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 100). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for BUD (96 < 100). Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15217 | val 0.23380
  Epoch 011 - train 0.15694 | val 0.23867
  Regression -> MSE: 0.000246, MAE: 0.011845, R²: -0.0043
  Directional -> Accuracy: 0.5797, MCC: 0.0279, F1: 0.0645

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14910 | val 0.24533
  Epoch 011 - train 0.14618 | val 0.25347
  Regression -> MSE: 0.000313, MAE: 0.013600, R²: -0.0018
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15430 | val 0.18189
  Epoch 011 - train 0.16102 | val 0.18274
  Regression -> MSE: 0.000693, MAE: 0.019688, R²: -0.0102
  Directional -> Accuracy: 0.4912, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for CHL (96 < 100). Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16661 | val 0.16178
  Epoch 011 - train 0.17460 | val 0.16056
  Regression -> MSE: 0.000138, MAE: 0.008992, R²: -0.0013
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 100). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15639 | val 0.19588
  Epoch 017 - train 0.14301 | val 0.20106
  Regression -> MSE: 0.000237, MAE: 0.010888, R²: -0.0464
  Directional -> Accuracy: 0.5167, MCC: 0.0349, F1: 0.4314

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14786 | val 0.32514
  Epoch 011 - train 0.15947 | val 0.33284
  Regression -> MSE: 0.000367, MAE: 0.016187, R²: 0.0001
  Directional -> Accuracy: 0.4510, MCC: 0.0000, F1: 0.6216

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16098 | val 0.15274
  Epoch 011 - train 0.16409 | val 0.15271
  Regression -> MSE: 0.000111, MAE: 0.007950, R²: -0.0286
  Directional -> Accuracy: 0.5362, MCC: 0.0000, F1: 0.6981

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 100). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14125 | val 0.26316
  Epoch 011 - train 0.14841 | val 0.26577
  Regression -> MSE: 0.000159, MAE: 0.009902, R²: -0.0078
  Directional -> Accuracy: 0.6207, MCC: 0.0000, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15662 | val 0.16145
  Epoch 011 - train 0.15535 | val 0.16218
  Regression -> MSE: 0.000276, MAE: 0.012972, R²: -0.0087
  Directional -> Accuracy: 0.6000, MCC: 0.0000, F1: 0.7500

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14644 | val 0.20523
  Epoch 011 - train 0.14276 | val 0.20487
  Regression -> MSE: 0.000154, MAE: 0.008866, R²: -0.0119
  Directional -> Accuracy: 0.5781, MCC: 0.0000, F1: 0.7327

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 100). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16402 | val 0.23616
  Epoch 011 - train 0.15402 | val 0.23525
  Regression -> MSE: 0.000247, MAE: 0.011214, R²: -0.0842
  Directional -> Accuracy: 0.4459, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17500 | val 0.19694
  Epoch 011 - train 0.16893 | val 0.19803
  Regression -> MSE: 0.000144, MAE: 0.008267, R²: -0.0000
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 100). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 100). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 100). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15128 | val 0.18821
  Epoch 011 - train 0.15151 | val 0.19009
  Regression -> MSE: 0.000169, MAE: 0.010322, R²: -0.0189
  Directional -> Accuracy: 0.5077, MCC: 0.0000, F1: 0.6735

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16634 | val 0.18425
  Epoch 011 - train 0.17218 | val 0.18515
  Regression -> MSE: 0.000088, MAE: 0.007251, R²: -0.0188
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15493 | val 0.19346
  Epoch 011 - train 0.15772 | val 0.19517
  Regression -> MSE: 0.000212, MAE: 0.011238, R²: -0.0037
  Directional -> Accuracy: 0.4769, MCC: 0.0000, F1: 0.6458

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.15165 | val 0.15007
  Epoch 011 - train 0.15654 | val 0.15078
  Regression -> MSE: 0.000090, MAE: 0.007980, R²: -0.0059
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.7059

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16935 | val 0.13110
  Epoch 011 - train 0.16943 | val 0.13048
  Regression -> MSE: 0.000110, MAE: 0.008994, R²: -0.1077
  Directional -> Accuracy: 0.4222, MCC: 0.0000, F1: 0.5938

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16354 | val 0.14390
  Epoch 011 - train 0.16243 | val 0.14413
  Regression -> MSE: 0.000240, MAE: 0.012969, R²: -0.0141
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.7273

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15933 | val 0.17405
  Epoch 020 - train 0.15804 | val 0.17025
  Regression -> MSE: 0.000187, MAE: 0.008025, R²: -0.1032
  Directional -> Accuracy: 0.5536, MCC: 0.0867, F1: 0.6154

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.17330 | val 0.12994
  Epoch 011 - train 0.16592 | val 0.12995
  Regression -> MSE: 0.000243, MAE: 0.012123, R²: -0.0028
  Directional -> Accuracy: 0.5500, MCC: 0.0000, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16015 | val 0.24653
  Epoch 011 - train 0.15365 | val 0.24664
  Regression -> MSE: 0.000236, MAE: 0.010072, R²: -0.0008
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16750 | val 0.16658
  Epoch 011 - train 0.16399 | val 0.16742
  Regression -> MSE: 0.000138, MAE: 0.008267, R²: 0.0010
  Directional -> Accuracy: 0.5476, MCC: 0.0000, F1: 0.7077

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15796 | val 0.20086
  Epoch 011 - train 0.15752 | val 0.20164
  Regression -> MSE: 0.000185, MAE: 0.010157, R²: -0.0127
  Directional -> Accuracy: 0.5306, MCC: 0.0000, F1: 0.6933

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15242 | val 0.18759
  Epoch 011 - train 0.13745 | val 0.18569
  Regression -> MSE: 0.000282, MAE: 0.010960, R²: -0.0619
  Directional -> Accuracy: 0.4444, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 100). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
Insufficient data for proper time series validation for NVS. Skipping...

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14523 | val 0.16879
  Epoch 011 - train 0.14932 | val 0.16762
  Regression -> MSE: 0.000194, MAE: 0.010779, R²: -0.0592
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16103 | val 0.16087
  Epoch 011 - train 0.16442 | val 0.16185
  Regression -> MSE: 0.000359, MAE: 0.012833, R²: -0.0339
  Directional -> Accuracy: 0.4242, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16775 | val 0.09841
  Epoch 011 - train 0.16180 | val 0.09855
  Regression -> MSE: 0.000122, MAE: 0.008440, R²: -0.1583
  Directional -> Accuracy: 0.4762, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15134 | val 0.20775
  Epoch 011 - train 0.15235 | val 0.20782
  Regression -> MSE: 0.000228, MAE: 0.011515, R²: -0.0351
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.6341

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15249 | val 0.27608
  Epoch 011 - train 0.16399 | val 0.27840
  Regression -> MSE: 0.000080, MAE: 0.006967, R²: -0.0775
  Directional -> Accuracy: 0.3913, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 100). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 100). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 100). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 100). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.18217 | val 0.12156
  Epoch 011 - train 0.16707 | val 0.12175
  Regression -> MSE: 0.000353, MAE: 0.015787, R²: -0.1335
  Directional -> Accuracy: 0.3542, MCC: 0.0000, F1: 0.5231

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 100). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
Insufficient data for proper time series validation for SO. Skipping...

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 100). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 100). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15197 | val 0.19083
  Epoch 011 - train 0.14718 | val 0.19080
  Regression -> MSE: 0.000079, MAE: 0.006907, R²: -0.0091
  Directional -> Accuracy: 0.5135, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 100). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 100). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 100). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 100). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16215 | val 0.19858
  Epoch 011 - train 0.16212 | val 0.19802
  Regression -> MSE: 0.000302, MAE: 0.014348, R²: -0.0028
  Directional -> Accuracy: 0.5111, MCC: 0.0000, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.15434 | val 0.16819
  Epoch 011 - train 0.17310 | val 0.16797
  Regression -> MSE: 0.000102, MAE: 0.007453, R²: -0.0010
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.20167 | val 0.19160
  Epoch 011 - train 0.19465 | val 0.19157
  Regression -> MSE: 0.000179, MAE: 0.009564, R²: -0.0213
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14751 | val 0.17613
  Epoch 011 - train 0.14924 | val 0.17803
  Regression -> MSE: 0.000231, MAE: 0.011906, R²: -0.0234
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.15269 | val 0.18862
  Epoch 011 - train 0.16094 | val 0.19032
  Regression -> MSE: 0.000094, MAE: 0.007754, R²: -0.0012
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.16268 | val 0.23594
  Epoch 011 - train 0.17025 | val 0.23571
  Regression -> MSE: 0.000169, MAE: 0.010425, R²: -0.0128
  Directional -> Accuracy: 0.4906, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.15889 | val 0.18962
  Epoch 011 - train 0.16726 | val 0.19017
  Regression -> MSE: 0.000134, MAE: 0.009301, R²: -0.1385
  Directional -> Accuracy: 0.4727, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.16421 | val 0.23628
  Epoch 011 - train 0.15382 | val 0.24115
  Regression -> MSE: 0.000241, MAE: 0.012438, R²: -0.0048
  Directional -> Accuracy: 0.5333, MCC: 0.1346, F1: 0.0667

================================================================================
Pipeline completed: 48/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (48, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan

[I 2026-02-24 02:37:07,037] Trial 120 finished with value: -0.011525525573206427 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 24, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 7.625528325891369e-06, 'weight_decay': 6.653874863376548e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 20, 'huber_delta': 0.23369616154120004, 'early_stopping_min_delta': 0.009997073293046041}. Best is trial 44 with value: -0.011362814469631832.

Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.08424 | val 0.10004
  Epoch 020 - train 0.08401 | val 0.09965
  Epoch 021 - train 0.08060 | val 0.09941
  Regression -> MSE: 0.000251, MAE: 0.012697, R²: -0.0130
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08245 | val 0.07236
  Epoch 020 - train 0.07988 | val 0.07729
  Epoch 021 - train 0.08082 | val 0.07735
  Regression -> MSE: 0.000699, MAE: 0.019599, R²: -0.0209
  Directional -> Accuracy: 0.5435, MCC: 0.0339, F1: 0.6441

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.08509 | val 0.12910
  Epoch 020 - train 0.08443 | val 0.13754
  Epoch 021 - train 0.08853 | val 0.13735
  Regression -> MSE: 0.000316, MAE: 0.014469, R²: -0.0184
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07006 | val 0.06879
  Epoch 020 - train 0.07431 | val 0.06962
  Epoch 021 - train 0.06785 | val 0.06944
  Regression -> MSE: 0.000350, MAE: 0.014614, R²: -0.0030
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09187 | val 0.07896
  Epoch 020 - train 0.08759 | val 0.07980
  Epoch 021 - train 0.08676 | val 0.07967
  Regression -> MSE: 0.000204, MAE: 0.010033, R²: -0.0012
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07666 | val 0.13992
  Epoch 020 - train 0.08050 | val 0.13984
  Epoch 021 - train 0.07432 | val 0.13990
  Regression -> MSE: 0.000585, MAE: 0.018677, R²: -0.0545
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.08478 | val 0.09416
  Epoch 020 - train 0.08417 | val 0.09400
  Epoch 021 - train 0.08386 | val 0.09403
  Regression -> MSE: 0.000247, MAE: 0.011927, R²: -0.0056
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08296 | val 0.09415
  Epoch 020 - train 0.08079 | val 0.08259
  Epoch 030 - train 0.08012 | val 0.08198
  Regression -> MSE: 0.000682, MAE: 0.020430, R²: -0.1422
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07842 | val 0.09198
  Epoch 020 - train 0.08092 | val 0.09151
  Epoch 021 - train 0.07764 | val 0.09173
  Regression -> MSE: 0.000391, MAE: 0.015929, R²: -0.0194
  Directional -> Accuracy: 0.6735, MCC: 0.3783, F1: 0.4667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.08939 | val 0.10043
  Epoch 020 - train 0.08766 | val 0.09913
  Epoch 021 - train 0.08829 | val 0.09895
  Regression -> MSE: 0.000244, MAE: 0.012271, R²: -0.0117
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.07944 | val 0.11264
  Epoch 020 - train 0.07825 | val 0.11363
  Epoch 021 - train 0.08130 | val 0.11372
  Regression -> MSE: 0.000313, MAE: 0.013830, R²: -0.0052
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08610 | val 0.09199
  Epoch 020 - train 0.08991 | val 0.09263
  Epoch 021 - train 0.08801 | val 0.09283
  Regression -> MSE: 0.000679, MAE: 0.019565, R²: -0.0024
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07617 | val 0.09584
  Epoch 020 - train 0.08411 | val 0.14805
  Epoch 021 - train 0.07991 | val 0.14794
  Regression -> MSE: 0.000143, MAE: 0.009407, R²: -0.0326
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.07700 | val 0.09374
  Epoch 020 - train 0.07825 | val 0.09400
  Epoch 027 - train 0.07931 | val 0.09465
  Regression -> MSE: 0.000238, MAE: 0.011192, R²: -0.0597
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08365 | val 0.16284
  Epoch 020 - train 0.08482 | val 0.17899
  Epoch 021 - train 0.08122 | val 0.17908
  Regression -> MSE: 0.000363, MAE: 0.016168, R²: -0.0015
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.08527 | val 0.09027
  Epoch 020 - train 0.08653 | val 0.09164
  Epoch 021 - train 0.08979 | val 0.09133
  Regression -> MSE: 0.000111, MAE: 0.007955, R²: -0.0254
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08584 | val 0.15399
  Epoch 020 - train 0.07794 | val 0.16889
  Epoch 021 - train 0.08180 | val 0.16819
  Regression -> MSE: 0.000159, MAE: 0.010029, R²: -0.0209
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08371 | val 0.08150
  Epoch 020 - train 0.08418 | val 0.08165
  Epoch 021 - train 0.08043 | val 0.08125
  Regression -> MSE: 0.000296, MAE: 0.014041, R²: -0.0871
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07478 | val 0.10540
  Epoch 020 - train 0.07497 | val 0.10508
  Epoch 021 - train 0.07827 | val 0.10537
  Regression -> MSE: 0.000154, MAE: 0.008757, R²: -0.0325
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09057 | val 0.12006
  Epoch 020 - train 0.08654 | val 0.12045
  Epoch 021 - train 0.09057 | val 0.12051
  Regression -> MSE: 0.000248, MAE: 0.011205, R²: -0.0970
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08115 | val 0.09627
  Epoch 020 - train 0.08184 | val 0.10088
  Epoch 021 - train 0.08333 | val 0.10079
  Regression -> MSE: 0.000145, MAE: 0.008485, R²: -0.0148
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07866 | val 0.09585
  Epoch 020 - train 0.07756 | val 0.09599
  Epoch 021 - train 0.07982 | val 0.09570
  Regression -> MSE: 0.000166, MAE: 0.010612, R²: -0.0039
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08505 | val 0.09486
  Epoch 020 - train 0.08555 | val 0.09646
  Epoch 021 - train 0.08420 | val 0.09635
  Regression -> MSE: 0.000087, MAE: 0.007121, R²: -0.0164
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.08541 | val 0.10095
  Epoch 020 - train 0.07892 | val 0.10232
  Epoch 021 - train 0.08033 | val 0.10185
  Regression -> MSE: 0.000212, MAE: 0.011088, R²: -0.0018
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07434 | val 0.07311
  Epoch 020 - train 0.07333 | val 0.07308
  Epoch 021 - train 0.08651 | val 0.07271
  Regression -> MSE: 0.000101, MAE: 0.008248, R²: -0.1009
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.08677 | val 0.06139
  Epoch 020 - train 0.08751 | val 0.06234
  Epoch 021 - train 0.08941 | val 0.06228
  Regression -> MSE: 0.000106, MAE: 0.008884, R²: -0.0276
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.08357 | val 0.07429
  Epoch 020 - train 0.08419 | val 0.08462
  Epoch 021 - train 0.08871 | val 0.08515
  Regression -> MSE: 0.000238, MAE: 0.012779, R²: -0.0279
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.08415 | val 0.08709
  Epoch 020 - train 0.08453 | val 0.08602
  Epoch 021 - train 0.08134 | val 0.08623
  Regression -> MSE: 0.000179, MAE: 0.007951, R²: -0.0784
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08065 | val 0.06670
  Epoch 020 - train 0.08443 | val 0.06766
  Epoch 021 - train 0.08570 | val 0.06787
  Regression -> MSE: 0.000236, MAE: 0.011864, R²: 0.0005
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.08347 | val 0.12130
  Epoch 020 - train 0.08453 | val 0.12430
  Epoch 021 - train 0.08409 | val 0.12425
  Regression -> MSE: 0.000232, MAE: 0.010003, R²: -0.0075
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.08697 | val 0.09758
  Epoch 020 - train 0.08380 | val 0.10520
  Epoch 021 - train 0.08401 | val 0.10561
  Regression -> MSE: 0.000142, MAE: 0.008507, R²: -0.0512
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08662 | val 0.09402
  Epoch 020 - train 0.08590 | val 0.09414
  Epoch 021 - train 0.07821 | val 0.09416
  Regression -> MSE: 0.000196, MAE: 0.010562, R²: -0.0434
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07427 | val 0.08558
  Epoch 020 - train 0.07197 | val 0.08551
  Epoch 027 - train 0.07263 | val 0.08563
  Regression -> MSE: 0.000330, MAE: 0.012476, R²: -0.2616
  Directional -> Accuracy: 0.5205, MCC: 0.1094, F1: 0.4262

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07623 | val 0.06686
  Epoch 020 - train 0.07990 | val 0.06452
  Epoch 021 - train 0.08248 | val 0.06430
  Regression -> MSE: 0.000167, MAE: 0.010367, R²: -0.0039
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.07998 | val 0.07790
  Epoch 020 - train 0.08165 | val 0.08090
  Epoch 021 - train 0.08181 | val 0.08076
  Regression -> MSE: 0.000180, MAE: 0.010296, R²: 0.0001
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.08684 | val 0.07603
  Epoch 020 - train 0.08519 | val 0.07685
  Epoch 021 - train 0.08409 | val 0.07695
  Regression -> MSE: 0.000343, MAE: 0.011705, R²: -0.0008
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08773 | val 0.05128
  Epoch 020 - train 0.08575 | val 0.05018
  Epoch 021 - train 0.08676 | val 0.05013
  Regression -> MSE: 0.000115, MAE: 0.008329, R²: -0.0977
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.08078 | val 0.10171
  Epoch 020 - train 0.08796 | val 0.10309
  Epoch 021 - train 0.08536 | val 0.10278
  Regression -> MSE: 0.000219, MAE: 0.011267, R²: 0.0002
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.08459 | val 0.12589
  Epoch 020 - train 0.08797 | val 0.12662
  Epoch 021 - train 0.08187 | val 0.12677
  Regression -> MSE: 0.000090, MAE: 0.007424, R²: -0.1592
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07759 | val 0.06891
  Epoch 020 - train 0.07566 | val 0.06931
  Epoch 021 - train 0.08384 | val 0.06948
  Regression -> MSE: 0.000344, MAE: 0.015477, R²: -0.1175
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.08360 | val 0.04950
  Epoch 020 - train 0.08366 | val 0.05513
  Epoch 021 - train 0.08167 | val 0.05605
  Regression -> MSE: 0.000248, MAE: 0.011502, R²: -0.0174
  Directional -> Accuracy: 0.5000, MCC: -0.0429, F1: 0.6275

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08165 | val 0.09347
  Epoch 020 - train 0.08211 | val 0.09369
  Epoch 021 - train 0.08486 | val 0.09357
  Regression -> MSE: 0.000083, MAE: 0.007057, R²: -0.0285
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.08828 | val 0.09441
  Epoch 020 - train 0.08818 | val 0.09464
  Epoch 021 - train 0.08075 | val 0.09510
  Regression -> MSE: 0.000307, MAE: 0.014481, R²: -0.0000
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08711 | val 0.08468
  Epoch 020 - train 0.08830 | val 0.08652
  Epoch 021 - train 0.08383 | val 0.08665
  Regression -> MSE: 0.000099, MAE: 0.007185, R²: -0.0047
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08693 | val 0.08958
  Epoch 020 - train 0.08901 | val 0.08824
  Epoch 021 - train 0.08615 | val 0.08819
  Regression -> MSE: 0.000173, MAE: 0.009973, R²: -0.0077
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07878 | val 0.12073
  Epoch 020 - train 0.08006 | val 0.13867
  Epoch 021 - train 0.07821 | val 0.13955
  Regression -> MSE: 0.000224, MAE: 0.011748, R²: -0.0049
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07892 | val 0.09392
  Epoch 020 - train 0.08176 | val 0.09709
  Epoch 021 - train 0.08074 | val 0.09708
  Regression -> MSE: 0.000095, MAE: 0.007818, R²: -0.0262
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.08722 | val 0.11896
  Epoch 020 - train 0.08565 | val 0.12056
  Epoch 021 - train 0.08575 | val 0.12059
  Regression -> MSE: 0.000164, MAE: 0.010254, R²: 0.0003
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.08815 | val 0.09884
  Epoch 020 - train 0.08479 | val 0.10217
  Epoch 021 - train 0.08338 | val 0.10193
  Regression -> MSE: 0.000128, MAE: 0.009062, R²: -0.1019
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.08309 | val 0.11436

[I 2026-02-24 02:39:16,674] Trial 121 finished with value: -0.011553016276424122 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 5.588441499086845e-06, 'weight_decay': 4.3971224398441645e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.11011108097466853, 'early_stopping_min_delta': 0.004639765876446622}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.08115 | val 0.12317
  Epoch 021 - train 0.07914 | val 0.12395
  Regression -> MSE: 0.000239, MAE: 0.012333, R²: -0.0059
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11876 | val 0.16285
  Epoch 020 - train 0.11850 | val 0.16331
  Epoch 021 - train 0.12163 | val 0.16302
  Regression -> MSE: 0.000256, MAE: 0.012889, R²: -0.0355
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12813 | val 0.10709
  Epoch 020 - train 0.12097 | val 0.11745
  Epoch 021 - train 0.12146 | val 0.11686
  Regression -> MSE: 0.000700, MAE: 0.019622, R²: -0.0232
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.14286 | val 0.18807
  Epoch 020 - train 0.13347 | val 0.19759
  Epoch 021 - train 0.13443 | val 0.19772
  Regression -> MSE: 0.000310, MAE: 0.014442, R²: 0.0000
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10755 | val 0.10332
  Epoch 020 - train 0.10941 | val 0.10255
  Epoch 021 - train 0.11002 | val 0.10186
  Regression -> MSE: 0.000396, MAE: 0.015391, R²: -0.1350
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12615 | val 0.12419
  Epoch 020 - train 0.12340 | val 0.12765
  Epoch 021 - train 0.12505 | val 0.12780
  Regression -> MSE: 0.000205, MAE: 0.010301, R²: -0.0079
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11822 | val 0.21439
  Epoch 020 - train 0.11795 | val 0.21462
  Epoch 021 - train 0.11651 | val 0.21449
  Regression -> MSE: 0.000588, MAE: 0.018746, R²: -0.0589
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12687 | val 0.14248
  Epoch 020 - train 0.12306 | val 0.14251
  Epoch 021 - train 0.12564 | val 0.14256
  Regression -> MSE: 0.000246, MAE: 0.011930, R²: -0.0012
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11799 | val 0.14730
  Epoch 020 - train 0.12090 | val 0.13281
  Epoch 030 - train 0.12554 | val 0.12954
  Regression -> MSE: 0.000605, MAE: 0.019376, R²: -0.0130
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11557 | val 0.14070
  Epoch 020 - train 0.11403 | val 0.13725
  Epoch 030 - train 0.11650 | val 0.13724
  Regression -> MSE: 0.000421, MAE: 0.016341, R²: -0.0987
  Directional -> Accuracy: 0.6327, MCC: 0.2887, F1: 0.3571

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11893 | val 0.14624
  Epoch 020 - train 0.11961 | val 0.14657
  Epoch 021 - train 0.11790 | val 0.14656
  Regression -> MSE: 0.000243, MAE: 0.011669, R²: -0.0052
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12080 | val 0.19973
  Epoch 020 - train 0.11385 | val 0.23266
  Epoch 021 - train 0.12186 | val 0.23203
  Regression -> MSE: 0.000311, MAE: 0.013842, R²: -0.0015
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12689 | val 0.15545
  Epoch 020 - train 0.12957 | val 0.18002
  Epoch 021 - train 0.13405 | val 0.17782
  Regression -> MSE: 0.000680, MAE: 0.019580, R²: -0.0048
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12480 | val 0.11293
  Epoch 020 - train 0.12614 | val 0.12808
  Epoch 021 - train 0.12298 | val 0.12746
  Regression -> MSE: 0.000145, MAE: 0.009504, R²: -0.0487
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11375 | val 0.16748
  Epoch 020 - train 0.11436 | val 0.16894
  Epoch 021 - train 0.11727 | val 0.16862
  Regression -> MSE: 0.000227, MAE: 0.010902, R²: -0.0076
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11997 | val 0.25294
  Epoch 020 - train 0.12776 | val 0.30018
  Epoch 021 - train 0.12275 | val 0.29865
  Regression -> MSE: 0.000362, MAE: 0.016089, R²: 0.0004
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12543 | val 0.12069
  Epoch 020 - train 0.12943 | val 0.12202
  Epoch 021 - train 0.12812 | val 0.12194
  Regression -> MSE: 0.000108, MAE: 0.008074, R²: 0.0011
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12226 | val 0.20970
  Epoch 020 - train 0.12000 | val 0.22157
  Epoch 021 - train 0.12284 | val 0.22138
  Regression -> MSE: 0.000162, MAE: 0.010219, R²: -0.0417
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12901 | val 0.12051
  Epoch 020 - train 0.12960 | val 0.12062
  Epoch 021 - train 0.12995 | val 0.12049
  Regression -> MSE: 0.000276, MAE: 0.013268, R²: -0.0161
  Directional -> Accuracy: 0.5921, MCC: 0.1030, F1: 0.6931

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11201 | val 0.15434
  Epoch 020 - train 0.11168 | val 0.15406
  Epoch 021 - train 0.11242 | val 0.15372
  Regression -> MSE: 0.000162, MAE: 0.008991, R²: -0.0848
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12212 | val 0.15983
  Epoch 020 - train 0.12634 | val 0.15859
  Epoch 021 - train 0.11922 | val 0.15820
  Regression -> MSE: 0.000230, MAE: 0.010965, R²: -0.0167
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12149 | val 0.14913
  Epoch 020 - train 0.12920 | val 0.15517
  Epoch 021 - train 0.13493 | val 0.15492
  Regression -> MSE: 0.000144, MAE: 0.008407, R²: -0.0071
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12756 | val 0.14556
  Epoch 020 - train 0.12221 | val 0.14629
  Epoch 021 - train 0.12592 | val 0.14588
  Regression -> MSE: 0.000180, MAE: 0.010343, R²: -0.0911
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12660 | val 0.13617
  Epoch 020 - train 0.12350 | val 0.13530
  Epoch 021 - train 0.12920 | val 0.13484
  Regression -> MSE: 0.000089, MAE: 0.007246, R²: -0.0414
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13190 | val 0.16897
  Epoch 020 - train 0.12764 | val 0.17809
  Epoch 021 - train 0.13146 | val 0.17638
  Regression -> MSE: 0.000214, MAE: 0.011053, R²: -0.0091
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11983 | val 0.10241
  Epoch 020 - train 0.12005 | val 0.10393
  Epoch 021 - train 0.12509 | val 0.10404
  Regression -> MSE: 0.000094, MAE: 0.008081, R²: -0.0221
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13566 | val 0.09200
  Epoch 020 - train 0.11749 | val 0.09254
  Epoch 021 - train 0.11829 | val 0.09301
  Regression -> MSE: 0.000110, MAE: 0.009016, R²: -0.0627
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12597 | val 0.10848
  Epoch 020 - train 0.12590 | val 0.10866
  Epoch 021 - train 0.12577 | val 0.10847
  Regression -> MSE: 0.000231, MAE: 0.012542, R²: -0.0001
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11648 | val 0.14104
  Epoch 020 - train 0.12673 | val 0.14789
  Epoch 021 - train 0.12360 | val 0.14812
  Regression -> MSE: 0.000182, MAE: 0.007990, R²: -0.0910
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11958 | val 0.10064
  Epoch 020 - train 0.12757 | val 0.09994
  Epoch 021 - train 0.12231 | val 0.10032
  Regression -> MSE: 0.000238, MAE: 0.011930, R²: -0.0062
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13168 | val 0.17775
  Epoch 020 - train 0.12522 | val 0.17629
  Epoch 021 - train 0.12700 | val 0.17592
  Regression -> MSE: 0.000230, MAE: 0.009871, R²: 0.0006
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13005 | val 0.13790
  Epoch 020 - train 0.12467 | val 0.13546
  Epoch 021 - train 0.12550 | val 0.13555
  Regression -> MSE: 0.000136, MAE: 0.008256, R²: -0.0076
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12568 | val 0.15112
  Epoch 020 - train 0.12604 | val 0.15407
  Epoch 021 - train 0.12186 | val 0.15396
  Regression -> MSE: 0.000188, MAE: 0.010403, R²: -0.0006
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12117 | val 0.12467
  Epoch 020 - train 0.11785 | val 0.12487
  Epoch 026 - train 0.11626 | val 0.12519
  Regression -> MSE: 0.000274, MAE: 0.010948, R²: -0.0464
  Directional -> Accuracy: 0.5342, MCC: 0.1140, F1: 0.4848

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12196 | val 0.09970
  Epoch 020 - train 0.12578 | val 0.09775
  Epoch 021 - train 0.11467 | val 0.09755
  Regression -> MSE: 0.000167, MAE: 0.010367, R²: -0.0031
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11648 | val 0.11475
  Epoch 020 - train 0.12637 | val 0.11823
  Epoch 021 - train 0.11854 | val 0.11812
  Regression -> MSE: 0.000180, MAE: 0.010252, R²: -0.0015
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12209 | val 0.11292
  Epoch 020 - train 0.11730 | val 0.11295
  Epoch 021 - train 0.12555 | val 0.11283
  Regression -> MSE: 0.000346, MAE: 0.011692, R²: -0.0094
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13158 | val 0.07512
  Epoch 020 - train 0.13164 | val 0.09616
  Epoch 021 - train 0.12585 | val 0.09742
  Regression -> MSE: 0.000115, MAE: 0.008319, R²: -0.0958
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12853 | val 0.17931
  Epoch 020 - train 0.12011 | val 0.19180
  Epoch 021 - train 0.11940 | val 0.18788
  Regression -> MSE: 0.000220, MAE: 0.011319, R²: -0.0057
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11809 | val 0.19335
  Epoch 020 - train 0.11360 | val 0.19425
  Epoch 021 - train 0.12165 | val 0.19410
  Regression -> MSE: 0.000083, MAE: 0.007091, R²: -0.0648
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12660 | val 0.08723
  Epoch 020 - train 0.12746 | val 0.09180
  Epoch 021 - train 0.12144 | val 0.09271
  Regression -> MSE: 0.000310, MAE: 0.013910, R²: -0.0070
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12930 | val 0.07091
  Epoch 020 - train 0.13317 | val 0.07409
  Epoch 021 - train 0.12791 | val 0.07458
  Regression -> MSE: 0.000249, MAE: 0.011499, R²: -0.0213
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12986 | val 0.14498
  Epoch 020 - train 0.13273 | val 0.14493
  Epoch 021 - train 0.13441 | val 0.14478
  Regression -> MSE: 0.000085, MAE: 0.007061, R²: -0.0467
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14413 | val 0.16235
  Epoch 020 - train 0.14195 | val 0.22676
  Epoch 021 - train 0.14638 | val 0.22740
  Regression -> MSE: 0.000310, MAE: 0.014497, R²: -0.0109
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12322 | val 0.13958
  Epoch 020 - train 0.12714 | val 0.14484
  Epoch 021 - train 0.12602 | val 0.14487
  Regression -> MSE: 0.000104, MAE: 0.007110, R²: -0.0546
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13088 | val 0.13688
  Epoch 020 - train 0.12570 | val 0.15463
  Epoch 021 - train 0.12874 | val 0.15620
  Regression -> MSE: 0.000172, MAE: 0.009868, R²: -0.0025
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10564 | val 0.13066
  Epoch 020 - train 0.10427 | val 0.12973
  Epoch 030 - train 0.11256 | val 0.13030
  Regression -> MSE: 0.000234, MAE: 0.011526, R²: -0.0498
  Directional -> Accuracy: 0.5893, MCC: 0.2253, F1: 0.5106

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11788 | val 0.14342
  Epoch 020 - train 0.12453 | val 0.15443
  Epoch 021 - train 0.11792 | val 0.15476

[I 2026-02-24 02:41:28,164] Trial 122 finished with value: -0.011440498776575748 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 3.8825844985050995e-06, 'weight_decay': 1.0830520120097717e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.17028506144932176, 'early_stopping_min_delta': 0.004230151711782236}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.11675 | val 0.17166
  Epoch 021 - train 0.12619 | val 0.17110
  Regression -> MSE: 0.000241, MAE: 0.012343, R²: -0.0155
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07613 | val 0.09635
  Epoch 020 - train 0.07541 | val 0.09688
  Epoch 021 - train 0.07783 | val 0.09717
  Regression -> MSE: 0.000247, MAE: 0.012522, R²: 0.0009
  Directional -> Accuracy: 0.5455, MCC: 0.0214, F1: 0.1026

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07333 | val 0.07026
  Epoch 020 - train 0.07082 | val 0.06936
  Epoch 021 - train 0.07580 | val 0.06968
  Regression -> MSE: 0.000686, MAE: 0.019361, R²: -0.0027
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07598 | val 0.11911
  Epoch 020 - train 0.08159 | val 0.12430
  Epoch 021 - train 0.08072 | val 0.12419
  Regression -> MSE: 0.000314, MAE: 0.014443, R²: -0.0131
  Directional -> Accuracy: 0.5532, MCC: 0.0857, F1: 0.6557

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06668 | val 0.07565
  Epoch 020 - train 0.06929 | val 0.07982
  Epoch 021 - train 0.06987 | val 0.07771
  Regression -> MSE: 0.000350, MAE: 0.014574, R²: -0.0007
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.08072 | val 0.07625
  Epoch 020 - train 0.08315 | val 0.07880
  Epoch 021 - train 0.08240 | val 0.07855
  Regression -> MSE: 0.000206, MAE: 0.010153, R²: -0.0127
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07055 | val 0.13323
  Epoch 020 - train 0.07008 | val 0.13389
  Epoch 021 - train 0.07369 | val 0.13391
  Regression -> MSE: 0.000566, MAE: 0.018291, R²: -0.0205
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.08011 | val 0.09113
  Epoch 020 - train 0.07893 | val 0.09159
  Epoch 021 - train 0.08073 | val 0.09148
  Regression -> MSE: 0.000248, MAE: 0.012299, R²: -0.0084
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07915 | val 0.09413
  Epoch 020 - train 0.08084 | val 0.12591
  Epoch 021 - train 0.07880 | val 0.12854
  Regression -> MSE: 0.000612, MAE: 0.019525, R²: -0.0245
  Directional -> Accuracy: 0.4773, MCC: 0.0781, F1: 0.5660

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08073 | val 0.09045
  Epoch 020 - train 0.08055 | val 0.08841
  Epoch 021 - train 0.08004 | val 0.08829
  Regression -> MSE: 0.000385, MAE: 0.016097, R²: -0.0036
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07691 | val 0.09515
  Epoch 020 - train 0.07919 | val 0.09602
  Epoch 021 - train 0.07996 | val 0.09637
  Regression -> MSE: 0.000242, MAE: 0.011696, R²: -0.0033
  Directional -> Accuracy: 0.5714, MCC: 0.0657, F1: 0.2857

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.07515 | val 0.09941
  Epoch 020 - train 0.07350 | val 0.09890
  Epoch 021 - train 0.07130 | val 0.09910
  Regression -> MSE: 0.000325, MAE: 0.013607, R²: -0.0444
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08178 | val 0.08728
  Epoch 020 - train 0.08433 | val 0.08786
  Epoch 021 - train 0.08578 | val 0.08775
  Regression -> MSE: 0.000684, MAE: 0.019766, R²: -0.0107
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.08080 | val 0.07499
  Epoch 020 - train 0.07905 | val 0.08039
  Epoch 021 - train 0.07831 | val 0.08059
  Regression -> MSE: 0.000142, MAE: 0.009379, R²: -0.0274
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.07469 | val 0.10425
  Epoch 020 - train 0.07297 | val 0.10798
  Epoch 021 - train 0.07465 | val 0.10741
  Regression -> MSE: 0.000226, MAE: 0.010718, R²: -0.0051
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07777 | val 0.14818
  Epoch 020 - train 0.07851 | val 0.14981
  Epoch 021 - train 0.07769 | val 0.14991
  Regression -> MSE: 0.000361, MAE: 0.016061, R²: 0.0021
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07844 | val 0.07794
  Epoch 020 - train 0.07904 | val 0.07894
  Epoch 021 - train 0.08014 | val 0.07888
  Regression -> MSE: 0.000109, MAE: 0.007934, R²: -0.0087
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07624 | val 0.11715
  Epoch 020 - train 0.07647 | val 0.11924
  Epoch 021 - train 0.07687 | val 0.11933
  Regression -> MSE: 0.000156, MAE: 0.009608, R²: 0.0019
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08150 | val 0.07336
  Epoch 020 - train 0.08136 | val 0.07339
  Epoch 021 - train 0.07927 | val 0.07343
  Regression -> MSE: 0.000277, MAE: 0.013314, R²: -0.0197
  Directional -> Accuracy: 0.4211, MCC: 0.1328, F1: 0.0833

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07920 | val 0.10789
  Epoch 020 - train 0.07787 | val 0.10885
  Epoch 021 - train 0.07752 | val 0.10897
  Regression -> MSE: 0.000155, MAE: 0.008786, R²: -0.0387
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07847 | val 0.10393
  Epoch 020 - train 0.07932 | val 0.10333
  Epoch 021 - train 0.08069 | val 0.10357
  Regression -> MSE: 0.000243, MAE: 0.011150, R²: -0.0759
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07593 | val 0.08881
  Epoch 020 - train 0.07788 | val 0.08920
  Epoch 021 - train 0.07906 | val 0.08953
  Regression -> MSE: 0.000152, MAE: 0.008762, R²: -0.0578
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07922 | val 0.08858
  Epoch 020 - train 0.07688 | val 0.08920
  Epoch 021 - train 0.07203 | val 0.08921
  Regression -> MSE: 0.000177, MAE: 0.010306, R²: -0.0691
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08205 | val 0.09158
  Epoch 020 - train 0.08191 | val 0.09564
  Epoch 021 - train 0.08219 | val 0.09577
  Regression -> MSE: 0.000086, MAE: 0.007120, R²: -0.0144
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07860 | val 0.08866
  Epoch 020 - train 0.07562 | val 0.09028
  Epoch 021 - train 0.07920 | val 0.09002
  Regression -> MSE: 0.000212, MAE: 0.011169, R²: 0.0003
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07227 | val 0.06786
  Epoch 020 - train 0.07515 | val 0.06864
  Epoch 021 - train 0.07077 | val 0.06862
  Regression -> MSE: 0.000100, MAE: 0.008210, R²: -0.0850
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07465 | val 0.05792
  Epoch 020 - train 0.07776 | val 0.06236
  Epoch 021 - train 0.07750 | val 0.06324
  Regression -> MSE: 0.000106, MAE: 0.008869, R²: -0.0242
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.08003 | val 0.07368
  Epoch 020 - train 0.08020 | val 0.07807
  Epoch 021 - train 0.08130 | val 0.07855
  Regression -> MSE: 0.000237, MAE: 0.012770, R²: -0.0258
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07806 | val 0.08863
  Epoch 020 - train 0.07809 | val 0.09022
  Epoch 021 - train 0.07628 | val 0.09026
  Regression -> MSE: 0.000173, MAE: 0.007825, R²: -0.0401
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07624 | val 0.06277
  Epoch 020 - train 0.08336 | val 0.06106
  Epoch 021 - train 0.08213 | val 0.06100
  Regression -> MSE: 0.000237, MAE: 0.011860, R²: -0.0002
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.08016 | val 0.11266
  Epoch 020 - train 0.07674 | val 0.11208
  Epoch 021 - train 0.07568 | val 0.11201
  Regression -> MSE: 0.000231, MAE: 0.009903, R²: -0.0025
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.08210 | val 0.08569
  Epoch 020 - train 0.08075 | val 0.08891
  Epoch 021 - train 0.08394 | val 0.08883
  Regression -> MSE: 0.000135, MAE: 0.008219, R²: 0.0012
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07628 | val 0.09224
  Epoch 020 - train 0.07942 | val 0.09383
  Epoch 021 - train 0.08046 | val 0.09381
  Regression -> MSE: 0.000193, MAE: 0.010451, R²: -0.0244
  Directional -> Accuracy: 0.5200, MCC: 0.0788, F1: 0.4286

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07289 | val 0.08113
  Epoch 020 - train 0.06923 | val 0.08089
  Epoch 021 - train 0.07278 | val 0.08088
  Regression -> MSE: 0.000265, MAE: 0.010512, R²: -0.0139
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07854 | val 0.06428
  Epoch 020 - train 0.07165 | val 0.06363
  Epoch 021 - train 0.07634 | val 0.06366
  Regression -> MSE: 0.000167, MAE: 0.010366, R²: -0.0036
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.07456 | val 0.07411
  Epoch 020 - train 0.07123 | val 0.07605
  Epoch 021 - train 0.07066 | val 0.07600
  Regression -> MSE: 0.000182, MAE: 0.010404, R²: -0.0124
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07479 | val 0.07283
  Epoch 020 - train 0.07291 | val 0.07365
  Epoch 021 - train 0.07461 | val 0.07360
  Regression -> MSE: 0.000346, MAE: 0.012093, R²: -0.0084
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08451 | val 0.05005
  Epoch 020 - train 0.08418 | val 0.05082
  Epoch 021 - train 0.07861 | val 0.05096
  Regression -> MSE: 0.000113, MAE: 0.008323, R²: -0.0738
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.08625 | val 0.10795
  Epoch 020 - train 0.08685 | val 0.10682
  Epoch 021 - train 0.08497 | val 0.10757
  Regression -> MSE: 0.000228, MAE: 0.011564, R²: -0.0425
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07991 | val 0.12888
  Epoch 020 - train 0.08363 | val 0.13225
  Epoch 021 - train 0.07465 | val 0.13222
  Regression -> MSE: 0.000080, MAE: 0.006975, R²: -0.0349
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08120 | val 0.06166
  Epoch 020 - train 0.07377 | val 0.05785
  Epoch 021 - train 0.07857 | val 0.05770
  Regression -> MSE: 0.000328, MAE: 0.014898, R²: -0.0675
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.08581 | val 0.04631
  Epoch 020 - train 0.08804 | val 0.05149
  Epoch 021 - train 0.07933 | val 0.05244
  Regression -> MSE: 0.000249, MAE: 0.011503, R²: -0.0221
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.07321 | val 0.08539
  Epoch 020 - train 0.07212 | val 0.08601
  Epoch 021 - train 0.07776 | val 0.08607
  Regression -> MSE: 0.000081, MAE: 0.007063, R²: -0.0019
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07618 | val 0.08854
  Epoch 020 - train 0.07473 | val 0.08864
  Epoch 021 - train 0.07723 | val 0.08879
  Regression -> MSE: 0.000307, MAE: 0.014496, R²: -0.0003
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07969 | val 0.07588
  Epoch 020 - train 0.07747 | val 0.07122
  Epoch 030 - train 0.07744 | val 0.06948
  Regression -> MSE: 0.000097, MAE: 0.007460, R²: 0.0099
  Directional -> Accuracy: 0.5000, MCC: 0.2358, F1: 0.2143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08045 | val 0.08459
  Epoch 020 - train 0.07791 | val 0.09047
  Epoch 021 - train 0.08229 | val 0.09151
  Regression -> MSE: 0.000173, MAE: 0.009883, R²: -0.0042
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07400 | val 0.08706
  Epoch 020 - train 0.07165 | val 0.09373
  Epoch 021 - train 0.07075 | val 0.09393
  Regression -> MSE: 0.000224, MAE: 0.011772, R²: -0.0028
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.08313 | val 0.08027
  Epoch 020 - train 0.07692 | val 0.08057
  Epoch 021 - train 0.08084 | val 0.08030

[I 2026-02-24 02:43:35,701] Trial 123 finished with value: -0.011425482418633545 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 9.66473400936819e-06, 'weight_decay': 7.630208944306637e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.10381255477084265, 'early_stopping_min_delta': 0.005056486169413237}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.07788 | val 0.10252
  Epoch 021 - train 0.08172 | val 0.10272
  Regression -> MSE: 0.000237, MAE: 0.012394, R²: -0.0010
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09689 | val 0.12049
  Epoch 020 - train 0.09782 | val 0.12095
  Epoch 021 - train 0.09674 | val 0.12105
  Regression -> MSE: 0.000249, MAE: 0.012621, R²: -0.0072
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09732 | val 0.08723
  Epoch 020 - train 0.09575 | val 0.08723
  Epoch 021 - train 0.09952 | val 0.08729
  Regression -> MSE: 0.000694, MAE: 0.019503, R²: -0.0139
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10548 | val 0.15369
  Epoch 020 - train 0.09789 | val 0.16535
  Epoch 021 - train 0.10136 | val 0.16610
  Regression -> MSE: 0.000313, MAE: 0.014429, R²: -0.0094
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08386 | val 0.20764
  Epoch 020 - train 0.08890 | val 0.21509
  Epoch 021 - train 0.08619 | val 0.21283
  Regression -> MSE: 0.000367, MAE: 0.014851, R²: -0.0494
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10042 | val 0.08926
  Epoch 020 - train 0.10125 | val 0.08815
  Epoch 030 - train 0.09635 | val 0.08829
  Regression -> MSE: 0.000194, MAE: 0.009440, R²: 0.0455
  Directional -> Accuracy: 0.7255, MCC: 0.4491, F1: 0.7407

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08814 | val 0.16967
  Epoch 020 - train 0.09227 | val 0.17202
  Epoch 021 - train 0.09297 | val 0.17202
  Regression -> MSE: 0.000555, MAE: 0.018155, R²: -0.0003
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10286 | val 0.11585
  Epoch 020 - train 0.10093 | val 0.11549
  Epoch 021 - train 0.10142 | val 0.11545
  Regression -> MSE: 0.000248, MAE: 0.011935, R²: -0.0109
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09877 | val 0.14419
  Epoch 020 - train 0.10913 | val 0.17554
  Epoch 021 - train 0.10356 | val 0.17936
  Regression -> MSE: 0.000673, MAE: 0.020581, R²: -0.1257
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09624 | val 0.11258
  Epoch 020 - train 0.09880 | val 0.10916
  Epoch 030 - train 0.09420 | val 0.10951
  Regression -> MSE: 0.000526, MAE: 0.018183, R²: -0.3720
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10710 | val 0.11999
  Epoch 020 - train 0.10692 | val 0.12102
  Epoch 021 - train 0.10316 | val 0.12042
  Regression -> MSE: 0.000248, MAE: 0.011634, R²: -0.0269
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09815 | val 0.13273
  Epoch 020 - train 0.09383 | val 0.13378
  Epoch 021 - train 0.09616 | val 0.13403
  Regression -> MSE: 0.000313, MAE: 0.013604, R²: -0.0070
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09660 | val 0.11022
  Epoch 020 - train 0.10094 | val 0.11138
  Epoch 021 - train 0.09914 | val 0.11169
  Regression -> MSE: 0.000682, MAE: 0.019518, R²: -0.0068
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10705 | val 0.10457
  Epoch 020 - train 0.10321 | val 0.12329
  Epoch 021 - train 0.10728 | val 0.12402
  Regression -> MSE: 0.000138, MAE: 0.009086, R²: -0.0003
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09846 | val 0.12151
  Epoch 020 - train 0.09299 | val 0.11967
  Epoch 030 - train 0.09081 | val 0.11929
  Regression -> MSE: 0.000224, MAE: 0.010824, R²: 0.0043
  Directional -> Accuracy: 0.4918, MCC: -0.0264, F1: 0.5867

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09684 | val 0.18833
  Epoch 020 - train 0.09423 | val 0.19203
  Epoch 021 - train 0.09359 | val 0.19217
  Regression -> MSE: 0.000365, MAE: 0.015991, R²: -0.0082
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09882 | val 0.09638
  Epoch 020 - train 0.10755 | val 0.09679
  Epoch 021 - train 0.10708 | val 0.09677
  Regression -> MSE: 0.000109, MAE: 0.007947, R²: -0.0148
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10676 | val 0.17625
  Epoch 020 - train 0.09835 | val 0.19444
  Epoch 021 - train 0.10042 | val 0.19520
  Regression -> MSE: 0.000159, MAE: 0.010003, R²: -0.0204
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10542 | val 0.11496
  Epoch 020 - train 0.10049 | val 0.11879
  Epoch 021 - train 0.09482 | val 0.11774
  Regression -> MSE: 0.000271, MAE: 0.012980, R²: 0.0028
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09074 | val 0.12782
  Epoch 020 - train 0.09080 | val 0.12755
  Epoch 021 - train 0.09157 | val 0.12771
  Regression -> MSE: 0.000151, MAE: 0.008779, R²: -0.0123
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09956 | val 0.13076
  Epoch 020 - train 0.10057 | val 0.13073
  Epoch 021 - train 0.10135 | val 0.13091
  Regression -> MSE: 0.000230, MAE: 0.010888, R²: -0.0181
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09845 | val 0.12269
  Epoch 020 - train 0.10197 | val 0.14244
  Epoch 021 - train 0.09816 | val 0.14190
  Regression -> MSE: 0.000153, MAE: 0.008800, R²: -0.0639
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09179 | val 0.10784
  Epoch 020 - train 0.09303 | val 0.10795
  Epoch 021 - train 0.09591 | val 0.10790
  Regression -> MSE: 0.000169, MAE: 0.010238, R²: -0.0212
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10946 | val 0.11182
  Epoch 020 - train 0.10722 | val 0.11181
  Epoch 021 - train 0.09844 | val 0.11178
  Regression -> MSE: 0.000088, MAE: 0.007188, R²: -0.0270
  Directional -> Accuracy: 0.4483, MCC: -0.0687, F1: 0.4074

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10466 | val 0.12259
  Epoch 020 - train 0.10285 | val 0.12340
  Epoch 021 - train 0.10466 | val 0.12407
  Regression -> MSE: 0.000218, MAE: 0.011043, R²: -0.0289
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09602 | val 0.08428
  Epoch 020 - train 0.09482 | val 0.08531
  Epoch 021 - train 0.09724 | val 0.08532
  Regression -> MSE: 0.000094, MAE: 0.008076, R²: -0.0191
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10782 | val 0.07516
  Epoch 020 - train 0.10526 | val 0.10490
  Epoch 021 - train 0.10040 | val 0.10823
  Regression -> MSE: 0.000103, MAE: 0.008711, R²: -0.0021
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10487 | val 0.08935
  Epoch 020 - train 0.10469 | val 0.09500
  Epoch 021 - train 0.09895 | val 0.09569
  Regression -> MSE: 0.000232, MAE: 0.012498, R²: -0.0013
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10442 | val 0.11784
  Epoch 020 - train 0.09939 | val 0.11688
  Epoch 021 - train 0.10388 | val 0.11646
  Regression -> MSE: 0.000169, MAE: 0.007857, R²: -0.0139
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10143 | val 0.08040
  Epoch 020 - train 0.09972 | val 0.08527
  Epoch 021 - train 0.09806 | val 0.08574
  Regression -> MSE: 0.000237, MAE: 0.011867, R²: -0.0012
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10389 | val 0.14502
  Epoch 020 - train 0.10446 | val 0.14632
  Epoch 021 - train 0.10092 | val 0.14634
  Regression -> MSE: 0.000231, MAE: 0.009869, R²: -0.0023
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10006 | val 0.11118
  Epoch 020 - train 0.09851 | val 0.11972
  Epoch 021 - train 0.10057 | val 0.12016
  Regression -> MSE: 0.000135, MAE: 0.008212, R²: 0.0010
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10319 | val 0.12634
  Epoch 020 - train 0.10428 | val 0.12866
  Epoch 021 - train 0.09973 | val 0.12899
  Regression -> MSE: 0.000188, MAE: 0.010485, R²: 0.0004
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09112 | val 0.10454
  Epoch 020 - train 0.09040 | val 0.10466
  Epoch 025 - train 0.08711 | val 0.10473
  Regression -> MSE: 0.000259, MAE: 0.010513, R²: 0.0123
  Directional -> Accuracy: 0.5616, MCC: 0.1038, F1: 0.6190

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09218 | val 0.08092
  Epoch 020 - train 0.09276 | val 0.08360
  Epoch 021 - train 0.08956 | val 0.08410
  Regression -> MSE: 0.000167, MAE: 0.010370, R²: -0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09622 | val 0.09592
  Epoch 020 - train 0.10283 | val 0.10022
  Epoch 021 - train 0.09738 | val 0.10039
  Regression -> MSE: 0.000180, MAE: 0.010313, R²: -0.0029
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09883 | val 0.08808
  Epoch 020 - train 0.09321 | val 0.08847
  Epoch 021 - train 0.09949 | val 0.08841
  Regression -> MSE: 0.000351, MAE: 0.012492, R²: -0.0254
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10343 | val 0.06372
  Epoch 020 - train 0.10535 | val 0.07370
  Epoch 021 - train 0.10455 | val 0.07384
  Regression -> MSE: 0.000111, MAE: 0.008332, R²: -0.0569
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10026 | val 0.12520
  Epoch 020 - train 0.09760 | val 0.12530
  Epoch 021 - train 0.09548 | val 0.12568
  Regression -> MSE: 0.000219, MAE: 0.011337, R²: -0.0037
  Directional -> Accuracy: 0.4912, MCC: -0.0964, F1: 0.1212

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10094 | val 0.16231
  Epoch 020 - train 0.09927 | val 0.17929
  Epoch 021 - train 0.09851 | val 0.17916
  Regression -> MSE: 0.000093, MAE: 0.007529, R²: -0.1955
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10713 | val 0.07537
  Epoch 020 - train 0.10885 | val 0.08100
  Epoch 021 - train 0.09883 | val 0.08178
  Regression -> MSE: 0.000317, MAE: 0.014325, R²: -0.0300
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10152 | val 0.05677
  Epoch 020 - train 0.10869 | val 0.05569
  Epoch 021 - train 0.10987 | val 0.05562
  Regression -> MSE: 0.000247, MAE: 0.011544, R²: -0.0143
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09454 | val 0.10988
  Epoch 020 - train 0.09251 | val 0.11011
  Epoch 021 - train 0.09542 | val 0.11012
  Regression -> MSE: 0.000081, MAE: 0.007069, R²: -0.0013
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10125 | val 0.11635
  Epoch 020 - train 0.10270 | val 0.11723
  Epoch 021 - train 0.10764 | val 0.11747
  Regression -> MSE: 0.000307, MAE: 0.014489, R²: 0.0002
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11080 | val 0.10178
  Epoch 020 - train 0.10443 | val 0.10328
  Epoch 021 - train 0.11252 | val 0.10351
  Regression -> MSE: 0.000099, MAE: 0.007229, R²: -0.0047
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10947 | val 0.11470
  Epoch 020 - train 0.11932 | val 0.12740
  Epoch 021 - train 0.11261 | val 0.12833
  Regression -> MSE: 0.000178, MAE: 0.010376, R²: -0.0365
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09201 | val 0.10576
  Epoch 020 - train 0.09767 | val 0.10684
  Epoch 021 - train 0.09504 | val 0.10604
  Regression -> MSE: 0.000224, MAE: 0.011749, R²: -0.0049
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09668 | val 0.10531
  Epoch 020 - train 0.10355 | val 0.10712
  Epoch 021 - train 0.09508 | val 0.10724

[I 2026-02-24 02:45:47,558] Trial 124 finished with value: -0.011457371548780109 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 1.0198521358697799e-05, 'weight_decay': 8.220458553647857e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.13590913030214802, 'early_stopping_min_delta': 0.004885926550548641}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.10418 | val 0.17229
  Epoch 021 - train 0.10005 | val 0.17108
  Regression -> MSE: 0.000238, MAE: 0.012375, R²: -0.0017
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47363 | val 0.88470
  Epoch 020 - train 0.49265 | val 0.88650
  Epoch 021 - train 0.48469 | val 0.88507
  Regression -> MSE: 0.000249, MAE: 0.012594, R²: -0.0054
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.51347 | val 0.45927
  Epoch 020 - train 0.49489 | val 0.49062
  Epoch 021 - train 0.52342 | val 0.49069
  Regression -> MSE: 0.000702, MAE: 0.019638, R²: -0.0256
  Directional -> Accuracy: 0.4130, MCC: -0.1164, F1: 0.1290

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.52039 | val 0.89721
  Epoch 020 - train 0.47358 | val 0.90389
  Epoch 021 - train 0.52350 | val 0.90511
  Regression -> MSE: 0.000311, MAE: 0.014414, R²: -0.0039
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.42912 | val 0.45701
  Epoch 020 - train 0.44017 | val 0.42386
  Epoch 021 - train 0.42633 | val 0.42555
  Regression -> MSE: 0.000355, MAE: 0.014691, R²: -0.0174
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.51547 | val 0.43908
  Epoch 020 - train 0.49278 | val 0.44188
  Epoch 021 - train 0.48024 | val 0.44080
  Regression -> MSE: 0.000208, MAE: 0.010145, R²: -0.0211
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.49548 | val 1.04790
  Epoch 020 - train 0.47783 | val 1.02546
  Epoch 030 - train 0.46958 | val 1.02751
  Regression -> MSE: 0.000600, MAE: 0.018879, R²: -0.0813
  Directional -> Accuracy: 0.5319, MCC: 0.0687, F1: 0.2667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.48524 | val 0.60137
  Epoch 020 - train 0.47596 | val 0.59970
  Epoch 027 - train 0.49443 | val 0.59909
  Regression -> MSE: 0.000253, MAE: 0.012654, R²: -0.0321
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.47778 | val 0.61181
  Epoch 020 - train 0.54112 | val 0.56895
  Epoch 030 - train 0.47204 | val 0.55807
  Regression -> MSE: 0.000591, MAE: 0.018782, R²: 0.0107
  Directional -> Accuracy: 0.5682, MCC: 0.0365, F1: 0.2963

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50866 | val 0.59545
  Epoch 020 - train 0.50920 | val 0.58035
  Epoch 030 - train 0.46683 | val 0.58181
  Regression -> MSE: 0.000408, MAE: 0.016341, R²: -0.0623
  Directional -> Accuracy: 0.5918, MCC: 0.1687, F1: 0.5238

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.50229 | val 0.62664
  Epoch 020 - train 0.48316 | val 0.63063
  Epoch 021 - train 0.48259 | val 0.63088
  Regression -> MSE: 0.000244, MAE: 0.011673, R²: -0.0114
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.44071 | val 0.71323
  Epoch 020 - train 0.42268 | val 0.70807
  Epoch 030 - train 0.43589 | val 0.71258
  Regression -> MSE: 0.000327, MAE: 0.013538, R²: -0.0518
  Directional -> Accuracy: 0.5600, MCC: 0.1548, F1: 0.0833

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.50305 | val 0.55807
  Epoch 020 - train 0.49476 | val 0.55982
  Epoch 021 - train 0.50684 | val 0.56031
  Regression -> MSE: 0.000687, MAE: 0.019832, R²: -0.0143
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.49817 | val 0.45193
  Epoch 020 - train 0.47456 | val 0.44918
  Epoch 021 - train 0.48866 | val 0.44892
  Regression -> MSE: 0.000143, MAE: 0.009420, R²: -0.0339
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.42128 | val 0.73080
  Epoch 020 - train 0.43714 | val 0.74998
  Epoch 021 - train 0.44730 | val 0.75404
  Regression -> MSE: 0.000226, MAE: 0.010721, R²: -0.0047
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46748 | val 1.28794
  Epoch 020 - train 0.46404 | val 1.39801
  Epoch 021 - train 0.50220 | val 1.40743
  Regression -> MSE: 0.000362, MAE: 0.016019, R²: 0.0000
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.54196 | val 0.59147
  Epoch 020 - train 0.52936 | val 0.59200
  Epoch 021 - train 0.49428 | val 0.58868
  Regression -> MSE: 0.000108, MAE: 0.008047, R²: -0.0049
  Directional -> Accuracy: 0.4429, MCC: -0.0765, F1: 0.2041

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.47221 | val 0.95975
  Epoch 020 - train 0.46220 | val 0.97926
  Epoch 021 - train 0.46529 | val 0.97921
  Regression -> MSE: 0.000156, MAE: 0.009590, R²: 0.0013
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.50014 | val 0.53310
  Epoch 020 - train 0.50111 | val 0.53361
  Epoch 021 - train 0.52508 | val 0.52944
  Regression -> MSE: 0.000296, MAE: 0.014036, R²: -0.0869
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.43576 | val 0.68520
  Epoch 020 - train 0.41562 | val 0.68464
  Epoch 021 - train 0.41458 | val 0.68476
  Regression -> MSE: 0.000170, MAE: 0.009198, R²: -0.1345
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.48583 | val 0.85654
  Epoch 020 - train 0.47709 | val 0.84695
  Epoch 021 - train 0.50118 | val 0.84858
  Regression -> MSE: 0.000231, MAE: 0.010980, R²: -0.0207
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.53637 | val 0.64248
  Epoch 020 - train 0.53738 | val 0.64863
  Epoch 021 - train 0.50751 | val 0.64958
  Regression -> MSE: 0.000150, MAE: 0.008672, R²: -0.0446
  Directional -> Accuracy: 0.6458, MCC: 0.1556, F1: 0.7733

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.45647 | val 0.51133
  Epoch 020 - train 0.51844 | val 0.51680
  Epoch 028 - train 0.45345 | val 0.51712
  Regression -> MSE: 0.000185, MAE: 0.010499, R²: -0.1212
  Directional -> Accuracy: 0.5909, MCC: 0.2357, F1: 0.4000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.54175 | val 0.66482
  Epoch 020 - train 0.50785 | val 0.67064
  Epoch 021 - train 0.54656 | val 0.67693
  Regression -> MSE: 0.000093, MAE: 0.007428, R²: -0.0875
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.46017 | val 0.69606
  Epoch 020 - train 0.45809 | val 0.74021
  Epoch 024 - train 0.47000 | val 0.75288
  Regression -> MSE: 0.000209, MAE: 0.011127, R²: 0.0110
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.43469 | val 0.37177
  Epoch 020 - train 0.44742 | val 0.37047
  Epoch 021 - train 0.45608 | val 0.36959
  Regression -> MSE: 0.000100, MAE: 0.008210, R²: -0.0852
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.47791 | val 0.33391
  Epoch 020 - train 0.47236 | val 0.41560
  Epoch 021 - train 0.46702 | val 0.41843
  Regression -> MSE: 0.000107, MAE: 0.008940, R²: -0.0407
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.49829 | val 0.43084
  Epoch 020 - train 0.47384 | val 0.44756
  Epoch 021 - train 0.49464 | val 0.44850
  Regression -> MSE: 0.000233, MAE: 0.012591, R²: -0.0063
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47573 | val 0.54938
  Epoch 020 - train 0.46053 | val 0.54807
  Epoch 030 - train 0.45829 | val 0.55065
  Regression -> MSE: 0.000183, MAE: 0.008409, R²: -0.0985
  Directional -> Accuracy: 0.4035, MCC: -0.3426, F1: 0.5641

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.42100 | val 0.29625
  Epoch 020 - train 0.48651 | val 0.29245
  Epoch 030 - train 0.52194 | val 0.31941
  Regression -> MSE: 0.000234, MAE: 0.011904, R²: 0.0090
  Directional -> Accuracy: 0.5854, MCC: 0.1688, F1: 0.7018

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.53052 | val 0.86743
  Epoch 020 - train 0.53285 | val 0.93487
  Epoch 021 - train 0.50185 | val 0.93776
  Regression -> MSE: 0.000231, MAE: 0.009865, R²: -0.0016
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.56947 | val 0.58431
  Epoch 020 - train 0.57653 | val 0.59021
  Epoch 021 - train 0.57635 | val 0.59012
  Regression -> MSE: 0.000135, MAE: 0.008170, R²: -0.0025
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.55742 | val 0.65900
  Epoch 020 - train 0.49245 | val 0.67382
  Epoch 021 - train 0.51383 | val 0.67255
  Regression -> MSE: 0.000188, MAE: 0.010495, R²: 0.0026
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.43506 | val 0.61566
  Epoch 020 - train 0.41526 | val 0.61302
  Epoch 021 - train 0.41515 | val 0.61343
  Regression -> MSE: 0.000262, MAE: 0.010579, R²: -0.0014
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.44861 | val 0.37509
  Epoch 020 - train 0.52385 | val 0.36081
  Epoch 030 - train 0.46753 | val 0.35862
  Regression -> MSE: 0.000162, MAE: 0.010313, R²: 0.0260
  Directional -> Accuracy: 0.6053, MCC: 0.2887, F1: 0.7059

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.44020 | val 0.52402
  Epoch 020 - train 0.43655 | val 0.60450
  Epoch 021 - train 0.42511 | val 0.60638
  Regression -> MSE: 0.000180, MAE: 0.010253, R²: -0.0018
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.47082 | val 0.43858
  Epoch 020 - train 0.45408 | val 0.43893
  Epoch 021 - train 0.47885 | val 0.43942
  Regression -> MSE: 0.000342, MAE: 0.011823, R²: 0.0018
  Directional -> Accuracy: 0.4627, MCC: 0.0630, F1: 0.1818

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.50642 | val 0.26186
  Epoch 020 - train 0.55510 | val 0.31846
  Epoch 021 - train 0.51052 | val 0.31693
  Regression -> MSE: 0.000125, MAE: 0.008456, R²: -0.1893
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46733 | val 0.74329
  Epoch 020 - train 0.48119 | val 0.74995
  Epoch 021 - train 0.48335 | val 0.74989
  Regression -> MSE: 0.000219, MAE: 0.011287, R²: -0.0008
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.50334 | val 1.01038
  Epoch 020 - train 0.48521 | val 1.03944
  Epoch 021 - train 0.49220 | val 1.03946
  Regression -> MSE: 0.000086, MAE: 0.007241, R²: -0.1051
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.49707 | val 0.28302
  Epoch 020 - train 0.46835 | val 0.28021
  Epoch 030 - train 0.43314 | val 0.28672
  Regression -> MSE: 0.000306, MAE: 0.014031, R²: 0.0047
  Directional -> Accuracy: 0.4898, MCC: 0.2221, F1: 0.5763

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.51063 | val 0.21925
  Epoch 020 - train 0.45361 | val 0.21992
  Epoch 021 - train 0.48976 | val 0.22021
  Regression -> MSE: 0.000258, MAE: 0.011477, R²: -0.0580
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.44460 | val 0.57128
  Epoch 020 - train 0.42818 | val 0.57721
  Epoch 021 - train 0.44893 | val 0.57741
  Regression -> MSE: 0.000081, MAE: 0.007101, R²: -0.0033
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49892 | val 0.66634
  Epoch 020 - train 0.57401 | val 0.96587
  Epoch 021 - train 0.53651 | val 0.96953
  Regression -> MSE: 0.000307, MAE: 0.014483, R²: -0.0000
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.49734 | val 0.49944
  Epoch 020 - train 0.51215 | val 0.46353
  Epoch 030 - train 0.43204 | val 0.45901
  Regression -> MSE: 0.000095, MAE: 0.007362, R²: 0.0310
  Directional -> Accuracy: 0.4545, MCC: 0.0230, F1: 0.2000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.50214 | val 0.66131
  Epoch 020 - train 0.50131 | val 0.72131
  Epoch 021 - train 0.48800 | val 0.72642
  Regression -> MSE: 0.000172, MAE: 0.009697, R²: 0.0011
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 02:48:09,029] Trial 125 finished with value: -0.011461121670288399 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 8.37139390718189e-06, 'weight_decay': 1.3038351844771391e-05, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.2988217772320425, 'early_stopping_min_delta': 0.005723305461359818}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.48132 | val 0.80304
  Epoch 021 - train 0.51053 | val 0.80482
  Regression -> MSE: 0.000238, MAE: 0.012526, R²: -0.0037
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14639 | val 0.18115
  Epoch 020 - train 0.14048 | val 0.18292
  Epoch 021 - train 0.14195 | val 0.18300
  Regression -> MSE: 0.000247, MAE: 0.012541, R²: 0.0021
  Directional -> Accuracy: 0.4675, MCC: 0.0490, F1: 0.6239

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14401 | val 0.18657
  Epoch 020 - train 0.14648 | val 0.19191
  Epoch 021 - train 0.13031 | val 0.19114
  Regression -> MSE: 0.000684, MAE: 0.019351, R²: 0.0011
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.14769 | val 0.22100
  Epoch 020 - train 0.13824 | val 0.22325
  Epoch 021 - train 0.13819 | val 0.22317
  Regression -> MSE: 0.000310, MAE: 0.014406, R²: 0.0014
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12371 | val 0.18049
  Epoch 020 - train 0.11052 | val 0.18731
  Epoch 021 - train 0.11513 | val 0.18719
  Regression -> MSE: 0.000380, MAE: 0.015048, R²: -0.0874
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14171 | val 0.15211
  Epoch 020 - train 0.13938 | val 0.14997
  Epoch 021 - train 0.13636 | val 0.14976
  Regression -> MSE: 0.000204, MAE: 0.010272, R²: 0.0002
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13583 | val 0.29436
  Epoch 020 - train 0.14199 | val 0.32504
  Epoch 021 - train 0.13856 | val 0.32442
  Regression -> MSE: 0.000600, MAE: 0.018930, R²: -0.0805
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14142 | val 0.16487
  Epoch 020 - train 0.13734 | val 0.16455
  Epoch 021 - train 0.14049 | val 0.16457
  Regression -> MSE: 0.000244, MAE: 0.012052, R²: 0.0079
  Directional -> Accuracy: 0.3913, MCC: -0.1467, F1: 0.5625

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13861 | val 0.19745
  Epoch 020 - train 0.13843 | val 0.20758
  Epoch 021 - train 0.13717 | val 0.20773
  Regression -> MSE: 0.000647, MAE: 0.020154, R²: -0.0821
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15135 | val 0.16945
  Epoch 020 - train 0.13403 | val 0.17315
  Epoch 021 - train 0.14012 | val 0.17318
  Regression -> MSE: 0.000383, MAE: 0.015933, R²: 0.0011
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13770 | val 0.17957
  Epoch 020 - train 0.13655 | val 0.18344
  Epoch 021 - train 0.14179 | val 0.18351
  Regression -> MSE: 0.000240, MAE: 0.011947, R²: 0.0055
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13775 | val 0.19693
  Epoch 020 - train 0.12591 | val 0.20179
  Epoch 021 - train 0.12690 | val 0.20221
  Regression -> MSE: 0.000312, MAE: 0.013557, R²: -0.0028
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14395 | val 0.21910
  Epoch 020 - train 0.14774 | val 0.22310
  Epoch 021 - train 0.14327 | val 0.22297
  Regression -> MSE: 0.000693, MAE: 0.019666, R²: -0.0228
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13555 | val 0.13974
  Epoch 020 - train 0.13297 | val 0.14376
  Epoch 021 - train 0.13820 | val 0.14397
  Regression -> MSE: 0.000144, MAE: 0.009426, R²: -0.0396
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13346 | val 0.16674
  Epoch 020 - train 0.12595 | val 0.16439
  Epoch 029 - train 0.12719 | val 0.16300
  Regression -> MSE: 0.000231, MAE: 0.011260, R²: -0.0267
  Directional -> Accuracy: 0.5246, MCC: 0.0908, F1: 0.2564

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13166 | val 0.26721
  Epoch 020 - train 0.13526 | val 0.26795
  Epoch 021 - train 0.13926 | val 0.26792
  Regression -> MSE: 0.000364, MAE: 0.016063, R²: -0.0047
  Directional -> Accuracy: 0.4423, MCC: -0.0891, F1: 0.5397

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15967 | val 0.13852
  Epoch 020 - train 0.13830 | val 0.13708
  Epoch 021 - train 0.14513 | val 0.13702
  Regression -> MSE: 0.000109, MAE: 0.007966, R²: -0.0100
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14311 | val 0.28474
  Epoch 020 - train 0.13931 | val 0.28620
  Epoch 021 - train 0.13576 | val 0.28605
  Regression -> MSE: 0.000160, MAE: 0.009848, R²: -0.0249
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14023 | val 0.14987
  Epoch 020 - train 0.13952 | val 0.15222
  Epoch 021 - train 0.13515 | val 0.15248
  Regression -> MSE: 0.000274, MAE: 0.013129, R²: -0.0052
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12855 | val 0.20951
  Epoch 020 - train 0.13246 | val 0.20783
  Epoch 021 - train 0.12928 | val 0.20763
  Regression -> MSE: 0.000152, MAE: 0.008717, R²: -0.0174
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14731 | val 0.22270
  Epoch 020 - train 0.14359 | val 0.21505
  Epoch 021 - train 0.14566 | val 0.21449
  Regression -> MSE: 0.000235, MAE: 0.010934, R²: -0.0371
  Directional -> Accuracy: 0.4667, MCC: -0.1355, F1: 0.5918

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14714 | val 0.20667
  Epoch 020 - train 0.14120 | val 0.21523
  Epoch 021 - train 0.14179 | val 0.21500
  Regression -> MSE: 0.000160, MAE: 0.009102, R²: -0.1176
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12996 | val 0.16642
  Epoch 020 - train 0.13093 | val 0.16363
  Epoch 021 - train 0.12929 | val 0.16348
  Regression -> MSE: 0.000171, MAE: 0.010270, R²: -0.0365
  Directional -> Accuracy: 0.5303, MCC: 0.0786, F1: 0.6437

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15325 | val 0.17229
  Epoch 020 - train 0.14262 | val 0.17242
  Epoch 021 - train 0.15065 | val 0.17239
  Regression -> MSE: 0.000085, MAE: 0.006994, R²: 0.0057
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13922 | val 0.16266
  Epoch 020 - train 0.13986 | val 0.16145
  Epoch 021 - train 0.13388 | val 0.16149
  Regression -> MSE: 0.000212, MAE: 0.011080, R²: -0.0009
  Directional -> Accuracy: 0.5152, MCC: 0.0512, F1: 0.5676

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12437 | val 0.12183
  Epoch 020 - train 0.12914 | val 0.12060
  Epoch 021 - train 0.12919 | val 0.12066
  Regression -> MSE: 0.000093, MAE: 0.008071, R²: -0.0111
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14814 | val 0.11012
  Epoch 020 - train 0.13613 | val 0.11546
  Epoch 021 - train 0.14476 | val 0.11552
  Regression -> MSE: 0.000108, MAE: 0.008943, R²: -0.0463
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14436 | val 0.20386
  Epoch 020 - train 0.14611 | val 0.24020
  Epoch 021 - train 0.14710 | val 0.24060
  Regression -> MSE: 0.000241, MAE: 0.012872, R²: -0.0414
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14398 | val 0.16908
  Epoch 020 - train 0.13827 | val 0.16749
  Epoch 021 - train 0.14317 | val 0.16739
  Regression -> MSE: 0.000173, MAE: 0.007903, R²: -0.0380
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14228 | val 0.11297
  Epoch 020 - train 0.15239 | val 0.11343
  Epoch 021 - train 0.13333 | val 0.11346
  Regression -> MSE: 0.000237, MAE: 0.011894, R²: -0.0029
  Directional -> Accuracy: 0.5366, MCC: 0.0166, F1: 0.6885

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14101 | val 0.22248
  Epoch 020 - train 0.13358 | val 0.22834
  Epoch 021 - train 0.12574 | val 0.22854
  Regression -> MSE: 0.000234, MAE: 0.010073, R²: -0.0161
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14776 | val 0.16387
  Epoch 020 - train 0.14489 | val 0.16871
  Epoch 021 - train 0.14222 | val 0.16879
  Regression -> MSE: 0.000135, MAE: 0.008213, R²: 0.0034
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14535 | val 0.17266
  Epoch 020 - train 0.13808 | val 0.17299
  Epoch 021 - train 0.13400 | val 0.17297
  Regression -> MSE: 0.000195, MAE: 0.010513, R²: -0.0334
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13613 | val 0.16189
  Epoch 020 - train 0.13085 | val 0.15775
  Epoch 021 - train 0.13217 | val 0.15735
  Regression -> MSE: 0.000265, MAE: 0.010725, R²: -0.0139
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16510 | val 0.14907
  Epoch 020 - train 0.15731 | val 0.17619
  Epoch 021 - train 0.15453 | val 0.17749
  Regression -> MSE: 0.000178, MAE: 0.010574, R²: -0.0677
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13061 | val 0.17309
  Epoch 020 - train 0.13991 | val 0.18615
  Epoch 021 - train 0.13444 | val 0.18606
  Regression -> MSE: 0.000187, MAE: 0.010636, R²: -0.0396
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14159 | val 0.12980
  Epoch 020 - train 0.13832 | val 0.13114
  Epoch 021 - train 0.13073 | val 0.13129
  Regression -> MSE: 0.000344, MAE: 0.011940, R²: -0.0040
  Directional -> Accuracy: 0.4179, MCC: -0.1409, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.15496 | val 0.08954
  Epoch 020 - train 0.14521 | val 0.09104
  Epoch 021 - train 0.14527 | val 0.09102
  Regression -> MSE: 0.000114, MAE: 0.008328, R²: -0.0825
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14795 | val 0.19683
  Epoch 020 - train 0.13751 | val 0.20007
  Epoch 021 - train 0.14215 | val 0.20022
  Regression -> MSE: 0.000219, MAE: 0.011352, R²: -0.0023
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14739 | val 0.24402
  Epoch 020 - train 0.13924 | val 0.24547
  Epoch 021 - train 0.14147 | val 0.24543
  Regression -> MSE: 0.000080, MAE: 0.006953, R²: -0.0306
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14167 | val 0.09921
  Epoch 020 - train 0.13670 | val 0.10177
  Epoch 021 - train 0.13443 | val 0.10199
  Regression -> MSE: 0.000309, MAE: 0.013763, R²: -0.0057
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14693 | val 0.09294
  Epoch 020 - train 0.14154 | val 0.09827
  Epoch 021 - train 0.15295 | val 0.09874
  Regression -> MSE: 0.000262, MAE: 0.011527, R²: -0.0744
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13896 | val 0.16592
  Epoch 020 - train 0.12911 | val 0.16493
  Epoch 021 - train 0.12478 | val 0.16490
  Regression -> MSE: 0.000085, MAE: 0.007066, R²: -0.0477
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13385 | val 0.16737
  Epoch 020 - train 0.14520 | val 0.16477
  Epoch 021 - train 0.14845 | val 0.16507
  Regression -> MSE: 0.000309, MAE: 0.014565, R²: -0.0082
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13869 | val 0.14987
  Epoch 020 - train 0.14175 | val 0.15815
  Epoch 021 - train 0.14795 | val 0.15837
  Regression -> MSE: 0.000099, MAE: 0.007282, R²: -0.0095
  Directional -> Accuracy: 0.5227, MCC: -0.0790, F1: 0.6667

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15347 | val 0.15661
  Epoch 020 - train 0.15500 | val 0.16823
  Epoch 021 - train 0.15345 | val 0.16862
  Regression -> MSE: 0.000172, MAE: 0.009626, R²: -0.0017
  Directional -> Accuracy: 0.4286, MCC: -0.2560, F1: 0.1765

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14212 | val 0.16195
  Epoch 020 - train 0.12791 | val 0.16211
  Epoch 021 - train 0.12580 | val 0.16220
  Regression -> MSE: 0.000223, MAE: 0.011677, R²: 0.0015
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14241 | val 0.15051
  Epoch 020 - train 0.14822 | val 0.15011
  Epoch 021 - train 0.14901 | val 0.15014

[I 2026-02-24 02:49:19,620] Trial 126 finished with value: -0.011451430422268222 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 2.4240457960211655e-05, 'weight_decay': 3.535349934566184e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.20375024720366786, 'early_stopping_min_delta': 0.005305235602754978}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.14593 | val 0.20520
  Epoch 021 - train 0.15136 | val 0.20480
  Regression -> MSE: 0.000245, MAE: 0.012372, R²: -0.0346
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12074 | val 0.14907
  Epoch 016 - train 0.12007 | val 0.15023
  Regression -> MSE: 0.000248, MAE: 0.012516, R²: -0.0008
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11638 | val 0.10885
  Epoch 016 - train 0.10762 | val 0.10821
  Regression -> MSE: 0.000687, MAE: 0.019389, R²: -0.0039
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12784 | val 0.18966
  Epoch 016 - train 0.12464 | val 0.19178
  Regression -> MSE: 0.000317, MAE: 0.014483, R²: -0.0222
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10596 | val 0.10357
  Epoch 016 - train 0.10662 | val 0.09763
  Regression -> MSE: 0.000396, MAE: 0.015386, R²: -0.1333
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12432 | val 0.12355
  Epoch 016 - train 0.12475 | val 0.13219
  Regression -> MSE: 0.000209, MAE: 0.010608, R²: -0.0285
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11463 | val 0.22178
  Epoch 016 - train 0.11215 | val 0.22499
  Regression -> MSE: 0.000604, MAE: 0.019080, R²: -0.0890
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12246 | val 0.14126
  Epoch 020 - train 0.12521 | val 0.13846
  Epoch 028 - train 0.11704 | val 0.13895
  Regression -> MSE: 0.000241, MAE: 0.011935, R²: 0.0177
  Directional -> Accuracy: 0.5217, MCC: 0.1549, F1: 0.5823

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13103 | val 0.13788
  Epoch 016 - train 0.12643 | val 0.13826
  Regression -> MSE: 0.000605, MAE: 0.019334, R²: -0.0122
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11795 | val 0.13847
  Epoch 016 - train 0.11673 | val 0.13935
  Regression -> MSE: 0.000396, MAE: 0.015989, R²: -0.0336
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12210 | val 0.14675
  Epoch 016 - train 0.12153 | val 0.14824
  Regression -> MSE: 0.000243, MAE: 0.011698, R²: -0.0065
  Directional -> Accuracy: 0.5857, MCC: 0.1020, F1: 0.2927

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11244 | val 0.16601
  Epoch 020 - train 0.11389 | val 0.15736
  Epoch 030 - train 0.11127 | val 0.15681
  Regression -> MSE: 0.000394, MAE: 0.015357, R²: -0.2675
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12447 | val 0.13289
  Epoch 016 - train 0.12350 | val 0.13229
  Regression -> MSE: 0.000679, MAE: 0.019556, R²: -0.0032
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12291 | val 0.11718
  Epoch 016 - train 0.11946 | val 0.11855
  Regression -> MSE: 0.000139, MAE: 0.009219, R²: -0.0064
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10882 | val 0.15146
  Epoch 020 - train 0.11006 | val 0.14939
  Epoch 026 - train 0.10692 | val 0.15308
  Regression -> MSE: 0.000220, MAE: 0.010607, R²: 0.0231
  Directional -> Accuracy: 0.5082, MCC: 0.0064, F1: 0.6429

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11926 | val 0.23324
  Epoch 016 - train 0.12025 | val 0.24303
  Regression -> MSE: 0.000363, MAE: 0.016041, R²: -0.0034
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12996 | val 0.11848
  Epoch 020 - train 0.12495 | val 0.11512
  Epoch 028 - train 0.12532 | val 0.11597
  Regression -> MSE: 0.000105, MAE: 0.007889, R²: 0.0258
  Directional -> Accuracy: 0.6000, MCC: 0.2152, F1: 0.5882

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11514 | val 0.19023
  Epoch 016 - train 0.12304 | val 0.19074
  Regression -> MSE: 0.000156, MAE: 0.009530, R²: -0.0035
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12254 | val 0.11824
  Epoch 016 - train 0.12246 | val 0.11973
  Regression -> MSE: 0.000293, MAE: 0.013972, R²: -0.0770
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10556 | val 0.15449
  Epoch 016 - train 0.10889 | val 0.15714
  Regression -> MSE: 0.000157, MAE: 0.008807, R²: -0.0464
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12471 | val 0.16350
  Epoch 016 - train 0.12097 | val 0.16754
  Regression -> MSE: 0.000236, MAE: 0.010993, R²: -0.0449
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11569 | val 0.14276
  Epoch 016 - train 0.11951 | val 0.14503
  Regression -> MSE: 0.000144, MAE: 0.008412, R²: -0.0073
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11287 | val 0.13852
  Epoch 016 - train 0.11581 | val 0.14196
  Regression -> MSE: 0.000166, MAE: 0.010380, R²: -0.0025
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12442 | val 0.13913
  Epoch 016 - train 0.12174 | val 0.13944
  Regression -> MSE: 0.000092, MAE: 0.007406, R²: -0.0818
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11793 | val 0.14062
  Epoch 016 - train 0.11380 | val 0.14217
  Regression -> MSE: 0.000212, MAE: 0.011162, R²: -0.0010
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11199 | val 0.10474
  Epoch 016 - train 0.11532 | val 0.10256
  Regression -> MSE: 0.000100, MAE: 0.008208, R²: -0.0877
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11354 | val 0.09846
  Epoch 016 - train 0.12548 | val 0.09982
  Regression -> MSE: 0.000115, MAE: 0.009174, R²: -0.1128
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12820 | val 0.11008
  Epoch 016 - train 0.12277 | val 0.11021
  Regression -> MSE: 0.000232, MAE: 0.012568, R²: -0.0029
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11768 | val 0.13773
  Epoch 016 - train 0.11466 | val 0.14298
  Regression -> MSE: 0.000181, MAE: 0.007983, R²: -0.0871
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12135 | val 0.10070
  Epoch 016 - train 0.13167 | val 0.10179
  Regression -> MSE: 0.000237, MAE: 0.011866, R²: -0.0014
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12084 | val 0.18251
  Epoch 016 - train 0.11633 | val 0.18290
  Regression -> MSE: 0.000231, MAE: 0.009907, R²: -0.0030
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12988 | val 0.13796
  Epoch 016 - train 0.12164 | val 0.13754
  Regression -> MSE: 0.000136, MAE: 0.008231, R²: -0.0061
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12443 | val 0.14673
  Epoch 016 - train 0.12069 | val 0.14705
  Regression -> MSE: 0.000189, MAE: 0.010423, R²: -0.0022
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10966 | val 0.13171
  Epoch 020 - train 0.10454 | val 0.12998
  Epoch 026 - train 0.10198 | val 0.12991
  Regression -> MSE: 0.000268, MAE: 0.010680, R²: -0.0225
  Directional -> Accuracy: 0.5342, MCC: 0.0888, F1: 0.5278

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11914 | val 0.10665
  Epoch 016 - train 0.11035 | val 0.10515
  Regression -> MSE: 0.000171, MAE: 0.010394, R²: -0.0246
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11827 | val 0.12585
  Epoch 016 - train 0.11888 | val 0.13077
  Regression -> MSE: 0.000187, MAE: 0.010607, R²: -0.0391
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11367 | val 0.10616
  Epoch 016 - train 0.11439 | val 0.10588
  Regression -> MSE: 0.000342, MAE: 0.011891, R²: 0.0008
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13086 | val 0.07700
  Epoch 016 - train 0.12343 | val 0.07730
  Regression -> MSE: 0.000113, MAE: 0.008302, R²: -0.0745
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12292 | val 0.15567
  Epoch 016 - train 0.11680 | val 0.15891
  Regression -> MSE: 0.000220, MAE: 0.011354, R²: -0.0074
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12082 | val 0.19801
  Epoch 016 - train 0.11606 | val 0.20387
  Regression -> MSE: 0.000088, MAE: 0.007358, R²: -0.1376
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11219 | val 0.08885
  Epoch 016 - train 0.12001 | val 0.08857
  Regression -> MSE: 0.000313, MAE: 0.014150, R²: -0.0188
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12216 | val 0.07339
  Epoch 016 - train 0.12825 | val 0.07322
  Regression -> MSE: 0.000254, MAE: 0.011452, R²: -0.0432
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11275 | val 0.13978
  Epoch 016 - train 0.10984 | val 0.14121
  Regression -> MSE: 0.000081, MAE: 0.007062, R²: -0.0039
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12167 | val 0.14368
  Epoch 016 - train 0.11903 | val 0.14218
  Regression -> MSE: 0.000306, MAE: 0.014483, R²: 0.0013
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12039 | val 0.13232
  Epoch 016 - train 0.11481 | val 0.13338
  Regression -> MSE: 0.000099, MAE: 0.007125, R²: -0.0110
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12615 | val 0.13583
  Epoch 016 - train 0.12700 | val 0.13563
  Regression -> MSE: 0.000173, MAE: 0.009948, R²: -0.0064
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11379 | val 0.13437
  Epoch 016 - train 0.11518 | val 0.13891
  Regression -> MSE: 0.000225, MAE: 0.011768, R²: -0.0076
  Directional -> Accuracy: 0.6250, MCC: 0.2514, F1: 0.7123

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11586 | val 0.13301
  Epoch 016 - train 0.11713 | val 0.13551
  Regression -> MSE: 0.000096, MAE: 0.007881, R²: -0.0358
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.13206 | val 0.18590
  Epoch 016 - train 0.13080 | val 0.18999
  Regression -> MSE: 0.000168, MAE: 0.010307, R²: -0.0284
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.12302 | val 0.14493
  Epoch 016 - train 0.11791 | val 0.15619
  Regression -> MSE: 0.000118, MAE: 0.008962, R²: -0.0200
  Directional -> Accuracy: 0.5357, MCC: 0.0739, F1: 0.6750

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.11717 | val 0.15918

[I 2026-02-24 02:50:33,028] Trial 127 finished with value: -0.011483471570835447 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 64, 'learning_rate': 1.741914793045766e-05, 'weight_decay': 5.573803476997547e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.17213586785249585, 'early_stopping_min_delta': 0.00510341962411992}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 016 - train 0.12150 | val 0.16028
  Regression -> MSE: 0.000239, MAE: 0.012337, R²: -0.0071
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.16657 | val 0.22355
  Epoch 020 - train 0.16491 | val 0.23648
  Epoch 021 - train 0.16683 | val 0.23416
  Regression -> MSE: 0.000256, MAE: 0.012856, R²: -0.0330
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16878 | val 0.17024
  Epoch 020 - train 0.15728 | val 0.15966
  Epoch 021 - train 0.16570 | val 0.16032
  Regression -> MSE: 0.000685, MAE: 0.019389, R²: -0.0011
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.17799 | val 0.24701
  Epoch 020 - train 0.16241 | val 0.25372
  Epoch 027 - train 0.15941 | val 0.25506
  Regression -> MSE: 0.000325, MAE: 0.014501, R²: -0.0461
  Directional -> Accuracy: 0.6170, MCC: 0.2281, F1: 0.6897

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15304 | val 0.18970
  Epoch 020 - train 0.15716 | val 0.17480
  Epoch 021 - train 0.14603 | val 0.17951
  Regression -> MSE: 0.000365, MAE: 0.014854, R²: -0.0445
  Directional -> Accuracy: 0.4267, MCC: -0.1414, F1: 0.0444

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16573 | val 0.23784
  Epoch 020 - train 0.16151 | val 0.24907
  Epoch 021 - train 0.17115 | val 0.23756
  Regression -> MSE: 0.000205, MAE: 0.010028, R²: -0.0078
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15815 | val 0.33080
  Epoch 020 - train 0.16095 | val 0.33120
  Epoch 026 - train 0.16310 | val 0.33117
  Regression -> MSE: 0.000557, MAE: 0.018233, R²: -0.0035
  Directional -> Accuracy: 0.5745, MCC: 0.1882, F1: 0.3333

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.17670 | val 0.24164
  Epoch 020 - train 0.16691 | val 0.25013
  Epoch 021 - train 0.17009 | val 0.24832
  Regression -> MSE: 0.000244, MAE: 0.011989, R²: 0.0040
  Directional -> Accuracy: 0.4928, MCC: 0.0458, F1: 0.5205

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.17155 | val 0.31291
  Epoch 020 - train 0.15719 | val 0.36088
  Epoch 021 - train 0.16883 | val 0.36529
  Regression -> MSE: 0.000613, MAE: 0.019538, R²: -0.0262
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.17627 | val 0.19261
  Epoch 020 - train 0.16697 | val 0.19726
  Epoch 028 - train 0.16108 | val 0.20007
  Regression -> MSE: 0.000567, MAE: 0.018992, R²: -0.4781
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.17111 | val 0.22212
  Epoch 020 - train 0.17716 | val 0.21717
  Epoch 021 - train 0.17020 | val 0.21686
  Regression -> MSE: 0.000246, MAE: 0.011643, R²: -0.0173
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.16741 | val 0.25595
  Epoch 020 - train 0.15858 | val 0.27177
  Epoch 021 - train 0.15987 | val 0.27269
  Regression -> MSE: 0.000320, MAE: 0.013586, R²: -0.0284
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.18125 | val 0.21898
  Epoch 020 - train 0.17152 | val 0.20819
  Epoch 021 - train 0.17954 | val 0.20785
  Regression -> MSE: 0.000681, MAE: 0.019602, R²: -0.0052
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.18248 | val 0.18666
  Epoch 020 - train 0.17891 | val 0.17644
  Epoch 021 - train 0.16440 | val 0.17397
  Regression -> MSE: 0.000141, MAE: 0.009340, R²: -0.0212
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15166 | val 0.22824
  Epoch 020 - train 0.14649 | val 0.22491
  Epoch 021 - train 0.15563 | val 0.22363
  Regression -> MSE: 0.000228, MAE: 0.010760, R²: -0.0121
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.17038 | val 0.34475
  Epoch 020 - train 0.16156 | val 0.34282
  Epoch 021 - train 0.16349 | val 0.34262
  Regression -> MSE: 0.000362, MAE: 0.016134, R²: 0.0009
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.18591 | val 0.21646
  Epoch 020 - train 0.17818 | val 0.21579
  Epoch 021 - train 0.17085 | val 0.21454
  Regression -> MSE: 0.000108, MAE: 0.008005, R²: -0.0057
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.17461 | val 0.31609
  Epoch 020 - train 0.15839 | val 0.34537
  Epoch 021 - train 0.16345 | val 0.34447
  Regression -> MSE: 0.000161, MAE: 0.010107, R²: -0.0300
  Directional -> Accuracy: 0.6102, MCC: 0.0423, F1: 0.7416

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.18130 | val 0.19504
  Epoch 020 - train 0.16707 | val 0.18504
  Epoch 021 - train 0.17281 | val 0.18558
  Regression -> MSE: 0.000270, MAE: 0.012964, R²: 0.0060
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.15970 | val 0.28992
  Epoch 020 - train 0.15884 | val 0.27839
  Epoch 021 - train 0.14840 | val 0.27511
  Regression -> MSE: 0.000160, MAE: 0.008878, R²: -0.0674
  Directional -> Accuracy: 0.4308, MCC: -0.1784, F1: 0.5195

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.17178 | val 0.28043
  Epoch 020 - train 0.17094 | val 0.27698
  Epoch 021 - train 0.17629 | val 0.27481
  Regression -> MSE: 0.000226, MAE: 0.010819, R²: 0.0024
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17504 | val 0.26597
  Epoch 020 - train 0.16032 | val 0.27656
  Epoch 021 - train 0.17209 | val 0.27707
  Regression -> MSE: 0.000143, MAE: 0.008319, R²: -0.0001
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.16309 | val 0.19934
  Epoch 020 - train 0.15898 | val 0.20744
  Epoch 021 - train 0.16881 | val 0.20788
  Regression -> MSE: 0.000178, MAE: 0.010322, R²: -0.0799
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.18132 | val 0.23944
  Epoch 020 - train 0.18379 | val 0.23025
  Epoch 021 - train 0.17595 | val 0.23422
  Regression -> MSE: 0.000089, MAE: 0.007251, R²: -0.0464
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16303 | val 0.28948
  Epoch 020 - train 0.15887 | val 0.32330
  Epoch 021 - train 0.16681 | val 0.34109
  Regression -> MSE: 0.000213, MAE: 0.011077, R²: -0.0059
  Directional -> Accuracy: 0.5152, MCC: -0.0596, F1: 0.0588

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.16102 | val 0.14675
  Epoch 020 - train 0.15031 | val 0.14366
  Epoch 030 - train 0.15036 | val 0.14348
  Regression -> MSE: 0.000103, MAE: 0.008115, R²: -0.1222
  Directional -> Accuracy: 0.5536, MCC: 0.1704, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.19566 | val 0.19653
  Epoch 020 - train 0.18157 | val 0.24233
  Epoch 021 - train 0.18129 | val 0.24963
  Regression -> MSE: 0.000104, MAE: 0.008829, R²: -0.0122
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.18004 | val 0.27733
  Epoch 020 - train 0.17114 | val 0.31859
  Epoch 021 - train 0.17567 | val 0.31772
  Regression -> MSE: 0.000233, MAE: 0.012614, R²: -0.0065
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.17358 | val 0.20678
  Epoch 020 - train 0.16435 | val 0.20346
  Epoch 030 - train 0.17063 | val 0.20643
  Regression -> MSE: 0.000220, MAE: 0.009985, R²: -0.3200
  Directional -> Accuracy: 0.5439, MCC: -0.0076, F1: 0.6829

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16696 | val 0.14659
  Epoch 020 - train 0.16060 | val 0.15474
  Epoch 021 - train 0.16653 | val 0.15397
  Regression -> MSE: 0.000241, MAE: 0.012063, R²: -0.0191
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.18819 | val 0.27084
  Epoch 020 - train 0.17797 | val 0.26967
  Epoch 021 - train 0.17003 | val 0.27115
  Regression -> MSE: 0.000231, MAE: 0.009887, R²: -0.0036
  Directional -> Accuracy: 0.4419, MCC: -0.1140, F1: 0.4783

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18115 | val 0.20689
  Epoch 020 - train 0.16630 | val 0.21262
  Epoch 029 - train 0.16571 | val 0.22233
  Regression -> MSE: 0.000158, MAE: 0.008695, R²: -0.1737
  Directional -> Accuracy: 0.5116, MCC: 0.0089, F1: 0.5714

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.18405 | val 0.21867
  Epoch 020 - train 0.17214 | val 0.21929
  Epoch 021 - train 0.16493 | val 0.22029
  Regression -> MSE: 0.000191, MAE: 0.010391, R²: -0.0145
  Directional -> Accuracy: 0.5600, MCC: 0.1548, F1: 0.7105

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.16793 | val 0.22805
  Epoch 020 - train 0.14812 | val 0.20975
  Epoch 021 - train 0.15750 | val 0.21039
  Regression -> MSE: 0.000269, MAE: 0.010646, R²: -0.0288
  Directional -> Accuracy: 0.4658, MCC: -0.1602, F1: 0.5979

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16860 | val 0.14315
  Epoch 020 - train 0.15903 | val 0.15006
  Epoch 021 - train 0.15429 | val 0.15031
  Regression -> MSE: 0.000167, MAE: 0.010369, R²: -0.0029
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.1739

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15482 | val 0.21102
  Epoch 020 - train 0.15717 | val 0.21317
  Epoch 021 - train 0.15576 | val 0.21109
  Regression -> MSE: 0.000180, MAE: 0.010254, R²: 0.0007
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16307 | val 0.15858
  Epoch 020 - train 0.16230 | val 0.16228
  Epoch 021 - train 0.16000 | val 0.16192
  Regression -> MSE: 0.000344, MAE: 0.011947, R²: -0.0027
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16976 | val 0.10535
  Epoch 020 - train 0.17279 | val 0.11003
  Epoch 021 - train 0.18005 | val 0.10960
  Regression -> MSE: 0.000125, MAE: 0.008480, R²: -0.1933
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15971 | val 0.23965
  Epoch 020 - train 0.16930 | val 0.23558
  Epoch 021 - train 0.16695 | val 0.23578
  Regression -> MSE: 0.000219, MAE: 0.011312, R²: -0.0018
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16950 | val 0.28379
  Epoch 020 - train 0.16858 | val 0.30304
  Epoch 026 - train 0.17078 | val 0.30396
  Regression -> MSE: 0.000085, MAE: 0.007202, R²: -0.0909
  Directional -> Accuracy: 0.4894, MCC: -0.0805, F1: 0.5862

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.16822 | val 0.13547
  Epoch 020 - train 0.16426 | val 0.12996
  Epoch 021 - train 0.17951 | val 0.12836
  Regression -> MSE: 0.000312, MAE: 0.014074, R²: -0.0150
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17624 | val 0.10471
  Epoch 020 - train 0.16607 | val 0.13110
  Epoch 021 - train 0.17785 | val 0.12829
  Regression -> MSE: 0.000260, MAE: 0.011501, R²: -0.0655
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15940 | val 0.20582
  Epoch 020 - train 0.15315 | val 0.20825
  Epoch 021 - train 0.15691 | val 0.20807
  Regression -> MSE: 0.000084, MAE: 0.007054, R²: -0.0377
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.18449 | val 0.21413
  Epoch 020 - train 0.16584 | val 0.22022
  Epoch 025 - train 0.16139 | val 0.22903
  Regression -> MSE: 0.000311, MAE: 0.014465, R²: -0.0143
  Directional -> Accuracy: 0.4894, MCC: -0.0096, F1: 0.2500

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16878 | val 0.17956
  Epoch 020 - train 0.16066 | val 0.18201
  Epoch 030 - train 0.15922 | val 0.18237
  Regression -> MSE: 0.000095, MAE: 0.007208, R²: 0.0342
  Directional -> Accuracy: 0.5682, MCC: 0.1257, F1: 0.6122

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.18053 | val 0.20253
  Epoch 020 - train 0.18640 | val 0.20505
  Epoch 021 - train 0.18020 | val 0.20535
  Regression -> MSE: 0.000172, MAE: 0.009701, R²: 0.0007
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.15511 | val 0.18734
  Epoch 020 - train 0.15680 | val 0.18647
  Epoch 021 - train 0.16409 | val 0.18738
  Regression -> MSE: 0.000226, MAE: 0.011826, R²: -0.0118
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.18068 | val 0.18766
  Epoch 020 - train 0.16803 | val 0.19795
  Epoch 029 - train 0.16127 | val 0.19138
  Regression -> MSE: 0.000128, MAE: 0.008543, R²: -0.3865

[I 2026-02-24 02:52:58,999] Trial 128 finished with value: -0.011522394959320718 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 8.328280730762023e-05, 'weight_decay': 7.1078493753961175e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2640834807199716, 'early_stopping_min_delta': 0.005459168995603266}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.17212 | val 0.25225
  Epoch 021 - train 0.16989 | val 0.25757
  Regression -> MSE: 0.000242, MAE: 0.012339, R²: -0.0220
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15470 | val 0.19982
  Epoch 020 - train 0.16306 | val 0.19929
  Epoch 021 - train 0.15714 | val 0.19953
  Regression -> MSE: 0.000248, MAE: 0.012502, R²: -0.0014
  Directional -> Accuracy: 0.5714, MCC: 0.1203, F1: 0.4590

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16678 | val 0.18142
  Epoch 020 - train 0.16846 | val 0.17955
  Epoch 021 - train 0.17314 | val 0.18083
  Regression -> MSE: 0.000686, MAE: 0.019406, R²: -0.0026
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16236 | val 0.25454
  Epoch 020 - train 0.17352 | val 0.25471
  Epoch 021 - train 0.16976 | val 0.25484
  Regression -> MSE: 0.000330, MAE: 0.014639, R²: -0.0633
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14009 | val 0.16035
  Epoch 020 - train 0.13601 | val 0.15087
  Epoch 021 - train 0.13168 | val 0.15401
  Regression -> MSE: 0.000350, MAE: 0.014528, R²: -0.0009
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16321 | val 0.16847
  Epoch 020 - train 0.15976 | val 0.16815
  Epoch 021 - train 0.15954 | val 0.16812
  Regression -> MSE: 0.000210, MAE: 0.010483, R²: -0.0318
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.16963 | val 0.31862
  Epoch 020 - train 0.15210 | val 0.32908
  Epoch 021 - train 0.15959 | val 0.32859
  Regression -> MSE: 0.000586, MAE: 0.018716, R²: -0.0557
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16492 | val 0.19085
  Epoch 020 - train 0.15229 | val 0.19117
  Epoch 021 - train 0.15921 | val 0.19098
  Regression -> MSE: 0.000249, MAE: 0.011946, R²: -0.0163
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15656 | val 0.22451
  Epoch 020 - train 0.16597 | val 0.24774
  Epoch 021 - train 0.16327 | val 0.24972
  Regression -> MSE: 0.000626, MAE: 0.019838, R²: -0.0485
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.17244 | val 0.20178
  Epoch 020 - train 0.17339 | val 0.20359
  Epoch 021 - train 0.17056 | val 0.20343
  Regression -> MSE: 0.000389, MAE: 0.016248, R²: -0.0134
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16511 | val 0.22647
  Epoch 020 - train 0.16956 | val 0.23005
  Epoch 021 - train 0.15862 | val 0.23080
  Regression -> MSE: 0.000247, MAE: 0.011644, R²: -0.0248
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15463 | val 0.21307
  Epoch 020 - train 0.15822 | val 0.21476
  Epoch 025 - train 0.15644 | val 0.21523
  Regression -> MSE: 0.000314, MAE: 0.013601, R²: -0.0085
  Directional -> Accuracy: 0.5600, MCC: 0.0902, F1: 0.2667

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.17293 | val 0.18174
  Epoch 020 - train 0.17226 | val 0.18194
  Epoch 021 - train 0.17023 | val 0.18193
  Regression -> MSE: 0.000684, MAE: 0.019673, R²: -0.0099
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17851 | val 0.15776
  Epoch 020 - train 0.17757 | val 0.15811
  Epoch 021 - train 0.17707 | val 0.15822
  Regression -> MSE: 0.000143, MAE: 0.009427, R²: -0.0343
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15349 | val 0.22048
  Epoch 020 - train 0.14976 | val 0.21993
  Epoch 021 - train 0.15157 | val 0.21992
  Regression -> MSE: 0.000227, MAE: 0.010847, R²: -0.0101
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15023 | val 0.30410
  Epoch 020 - train 0.14770 | val 0.30475
  Epoch 021 - train 0.15261 | val 0.30463
  Regression -> MSE: 0.000362, MAE: 0.016197, R²: -0.0003
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16778 | val 0.16045
  Epoch 020 - train 0.16172 | val 0.16021
  Epoch 021 - train 0.16758 | val 0.16022
  Regression -> MSE: 0.000110, MAE: 0.008144, R²: -0.0166
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14919 | val 0.25580
  Epoch 020 - train 0.15137 | val 0.25773
  Epoch 021 - train 0.15196 | val 0.25774
  Regression -> MSE: 0.000155, MAE: 0.009562, R²: 0.0048
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15705 | val 0.16013
  Epoch 020 - train 0.15999 | val 0.16115
  Epoch 021 - train 0.15764 | val 0.16115
  Regression -> MSE: 0.000278, MAE: 0.013378, R²: -0.0231
  Directional -> Accuracy: 0.3684, MCC: -0.2036, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.16567 | val 0.23013
  Epoch 020 - train 0.15661 | val 0.22646
  Epoch 021 - train 0.16081 | val 0.22655
  Regression -> MSE: 0.000151, MAE: 0.008830, R²: -0.0075
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16648 | val 0.20733
  Epoch 020 - train 0.15712 | val 0.20541
  Epoch 028 - train 0.17026 | val 0.20507
  Regression -> MSE: 0.000246, MAE: 0.011407, R²: -0.0870
  Directional -> Accuracy: 0.4267, MCC: -0.1142, F1: 0.2456

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16307 | val 0.18391
  Epoch 020 - train 0.15559 | val 0.18373
  Epoch 021 - train 0.16033 | val 0.18380
  Regression -> MSE: 0.000147, MAE: 0.008551, R²: -0.0269
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.16549 | val 0.18314
  Epoch 020 - train 0.15763 | val 0.18216
  Epoch 021 - train 0.16362 | val 0.18184
  Regression -> MSE: 0.000191, MAE: 0.010492, R²: -0.1570
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.17040 | val 0.19253
  Epoch 020 - train 0.17406 | val 0.19136
  Epoch 021 - train 0.16868 | val 0.19189
  Regression -> MSE: 0.000088, MAE: 0.007173, R²: -0.0361
  Directional -> Accuracy: 0.4828, MCC: -0.0158, F1: 0.4828

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16779 | val 0.18429
  Epoch 020 - train 0.16376 | val 0.18506
  Epoch 021 - train 0.16475 | val 0.18504
  Regression -> MSE: 0.000213, MAE: 0.011215, R²: -0.0067
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14614 | val 0.13417
  Epoch 020 - train 0.14192 | val 0.13292
  Epoch 030 - train 0.13912 | val 0.13226
  Regression -> MSE: 0.000087, MAE: 0.007785, R²: 0.0526
  Directional -> Accuracy: 0.6071, MCC: 0.1883, F1: 0.6857

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16200 | val 0.11926
  Epoch 020 - train 0.15931 | val 0.12313
  Epoch 021 - train 0.16883 | val 0.12291
  Regression -> MSE: 0.000106, MAE: 0.008861, R²: -0.0310
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.17270 | val 0.14857
  Epoch 020 - train 0.17161 | val 0.14839
  Epoch 021 - train 0.15961 | val 0.14810
  Regression -> MSE: 0.000232, MAE: 0.012547, R²: -0.0008
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15486 | val 0.18737
  Epoch 020 - train 0.16857 | val 0.18839
  Epoch 021 - train 0.15700 | val 0.18862
  Regression -> MSE: 0.000190, MAE: 0.008151, R²: -0.1416
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16127 | val 0.14158
  Epoch 020 - train 0.15313 | val 0.15432
  Epoch 021 - train 0.16705 | val 0.15428
  Regression -> MSE: 0.000235, MAE: 0.011862, R²: 0.0070
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16238 | val 0.24196
  Epoch 020 - train 0.15971 | val 0.24678
  Epoch 021 - train 0.16139 | val 0.24635
  Regression -> MSE: 0.000232, MAE: 0.009962, R²: -0.0080
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.17012 | val 0.17269
  Epoch 020 - train 0.18054 | val 0.17491
  Epoch 021 - train 0.18155 | val 0.17491
  Regression -> MSE: 0.000135, MAE: 0.008164, R²: -0.0029
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15510 | val 0.19267
  Epoch 020 - train 0.15141 | val 0.19247
  Epoch 021 - train 0.15727 | val 0.19212
  Regression -> MSE: 0.000188, MAE: 0.010440, R²: -0.0000
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14508 | val 0.18030
  Epoch 020 - train 0.14905 | val 0.18020
  Epoch 021 - train 0.13956 | val 0.17926
  Regression -> MSE: 0.000262, MAE: 0.010523, R²: -0.0003
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16088 | val 0.13076
  Epoch 020 - train 0.16313 | val 0.12699
  Epoch 021 - train 0.15821 | val 0.12646
  Regression -> MSE: 0.000169, MAE: 0.010374, R²: -0.0154
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14678 | val 0.15094
  Epoch 020 - train 0.14284 | val 0.15212
  Epoch 021 - train 0.14319 | val 0.15227
  Regression -> MSE: 0.000182, MAE: 0.010375, R²: -0.0096
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15697 | val 0.14980
  Epoch 020 - train 0.15652 | val 0.14847
  Epoch 021 - train 0.15039 | val 0.14856
  Regression -> MSE: 0.000342, MAE: 0.011682, R²: 0.0027
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16491 | val 0.11005
  Epoch 020 - train 0.16436 | val 0.11263
  Epoch 021 - train 0.17210 | val 0.11270
  Regression -> MSE: 0.000110, MAE: 0.008354, R²: -0.0423
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16827 | val 0.20560
  Epoch 020 - train 0.15848 | val 0.20503
  Epoch 021 - train 0.16343 | val 0.20518
  Regression -> MSE: 0.000220, MAE: 0.011352, R²: -0.0080
  Directional -> Accuracy: 0.5439, MCC: 0.0974, F1: 0.5667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16152 | val 0.30897
  Epoch 020 - train 0.15915 | val 0.31210
  Epoch 021 - train 0.16343 | val 0.31388
  Regression -> MSE: 0.000081, MAE: 0.007017, R²: -0.0414
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15485 | val 0.11307
  Epoch 020 - train 0.16815 | val 0.11383
  Epoch 021 - train 0.16165 | val 0.11423
  Regression -> MSE: 0.000310, MAE: 0.013879, R²: -0.0066
  Directional -> Accuracy: 0.6939, MCC: 0.3340, F1: 0.5714

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.16527 | val 0.09608
  Epoch 020 - train 0.18176 | val 0.09990
  Epoch 021 - train 0.17333 | val 0.09991
  Regression -> MSE: 0.000256, MAE: 0.011473, R²: -0.0510
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15321 | val 0.18091
  Epoch 020 - train 0.15423 | val 0.18081
  Epoch 021 - train 0.15100 | val 0.18118
  Regression -> MSE: 0.000082, MAE: 0.007107, R²: -0.0087
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.15704 | val 0.20412
  Epoch 020 - train 0.16178 | val 0.20760
  Epoch 021 - train 0.16488 | val 0.20803
  Regression -> MSE: 0.000312, MAE: 0.014513, R²: -0.0179
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16583 | val 0.16389
  Epoch 020 - train 0.16056 | val 0.16598
  Epoch 021 - train 0.16129 | val 0.16630
  Regression -> MSE: 0.000102, MAE: 0.007286, R²: -0.0342
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17652 | val 0.18775
  Epoch 020 - train 0.16121 | val 0.19345
  Epoch 021 - train 0.19209 | val 0.19348
  Regression -> MSE: 0.000179, MAE: 0.010419, R²: -0.0400
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...


[I 2026-02-24 02:57:22,917] Trial 129 finished with value: -0.011429609679099036 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 6.608816715256969e-06, 'weight_decay': 9.237254191941367e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.23207063787710552, 'early_stopping_min_delta': 0.004881553842114373}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.16637 | val 0.21291
  Regression -> MSE: 0.000238, MAE: 0.012314, R²: -0.0055
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.42707 | val 0.60555
  Epoch 020 - train 0.43259 | val 0.60479
  Epoch 021 - train 0.43314 | val 0.60516
  Regression -> MSE: 0.000253, MAE: 0.012764, R²: -0.0204
  Directional -> Accuracy: 0.4545, MCC: -0.0149, F1: 0.6182

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.47758 | val 0.43564
  Epoch 020 - train 0.44828 | val 0.43685
  Epoch 021 - train 0.42499 | val 0.43855
  Regression -> MSE: 0.000721, MAE: 0.020190, R²: -0.0534
  Directional -> Accuracy: 0.3696, MCC: -0.3012, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.45066 | val 0.85971
  Epoch 020 - train 0.48258 | val 0.85715
  Epoch 021 - train 0.45762 | val 0.85754
  Regression -> MSE: 0.000336, MAE: 0.014767, R²: -0.0845
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.38057 | val 0.38561
  Epoch 020 - train 0.40192 | val 0.39155
  Epoch 021 - train 0.36059 | val 0.39040
  Regression -> MSE: 0.000358, MAE: 0.014712, R²: -0.0243
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.40177 | val 0.45341
  Epoch 020 - train 0.43416 | val 0.44852
  Epoch 021 - train 0.43676 | val 0.44939
  Regression -> MSE: 0.000208, MAE: 0.010250, R²: -0.0212
  Directional -> Accuracy: 0.5686, MCC: 0.1667, F1: 0.5000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.39790 | val 0.88243
  Epoch 020 - train 0.42412 | val 0.88226
  Epoch 029 - train 0.41533 | val 0.88440
  Regression -> MSE: 0.000560, MAE: 0.018768, R²: -0.0081
  Directional -> Accuracy: 0.4681, MCC: -0.0644, F1: 0.5902

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.45103 | val 0.56082
  Epoch 020 - train 0.46504 | val 0.55940
  Epoch 021 - train 0.44531 | val 0.56126
  Regression -> MSE: 0.000253, MAE: 0.012016, R²: -0.0295
  Directional -> Accuracy: 0.6087, MCC: 0.1133, F1: 0.1290

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43886 | val 0.46676
  Epoch 020 - train 0.44502 | val 0.47198
  Epoch 028 - train 0.43684 | val 0.47056
  Regression -> MSE: 0.000627, MAE: 0.019680, R²: -0.0496
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.39613 | val 0.47358
  Epoch 020 - train 0.42309 | val 0.47241
  Epoch 029 - train 0.41017 | val 0.47382
  Regression -> MSE: 0.000397, MAE: 0.015947, R²: -0.0348
  Directional -> Accuracy: 0.5918, MCC: 0.1563, F1: 0.3333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.41677 | val 0.55989
  Epoch 020 - train 0.40034 | val 0.56234
  Epoch 021 - train 0.44051 | val 0.56161
  Regression -> MSE: 0.000248, MAE: 0.011678, R²: -0.0253
  Directional -> Accuracy: 0.5571, MCC: -0.1043, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.41600 | val 0.63449
  Epoch 020 - train 0.37260 | val 0.63857
  Epoch 023 - train 0.38493 | val 0.63673
  Regression -> MSE: 0.000295, MAE: 0.013367, R²: 0.0506
  Directional -> Accuracy: 0.5600, MCC: 0.0898, F1: 0.3125

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.45579 | val 0.70051
  Epoch 020 - train 0.42711 | val 0.69599
  Epoch 021 - train 0.42631 | val 0.69892
  Regression -> MSE: 0.000686, MAE: 0.019534, R²: -0.0128
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.4314

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.44529 | val 0.48324
  Epoch 020 - train 0.48583 | val 0.48666
  Epoch 021 - train 0.41066 | val 0.48769
  Regression -> MSE: 0.000138, MAE: 0.009123, R²: -0.0003
  Directional -> Accuracy: 0.5349, MCC: 0.1036, F1: 0.5652

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37736 | val 0.56181
  Epoch 020 - train 0.38767 | val 0.56172
  Epoch 021 - train 0.38804 | val 0.56132
  Regression -> MSE: 0.000231, MAE: 0.010886, R²: -0.0277
  Directional -> Accuracy: 0.5082, MCC: 0.0549, F1: 0.1667

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.45052 | val 0.98965
  Epoch 020 - train 0.42387 | val 0.99172
  Epoch 021 - train 0.43271 | val 0.99100
  Regression -> MSE: 0.000368, MAE: 0.015904, R²: -0.0174
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.46908 | val 0.42355
  Epoch 020 - train 0.45744 | val 0.42196
  Epoch 021 - train 0.45542 | val 0.42219
  Regression -> MSE: 0.000105, MAE: 0.007969, R²: 0.0249
  Directional -> Accuracy: 0.5000, MCC: 0.0099, F1: 0.4928

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.42352 | val 0.85694
  Epoch 020 - train 0.44283 | val 0.85456
  Epoch 021 - train 0.45863 | val 0.85372
  Regression -> MSE: 0.000157, MAE: 0.009639, R²: -0.0097
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.45594 | val 0.42328
  Epoch 020 - train 0.42878 | val 0.42347
  Epoch 021 - train 0.44014 | val 0.42391
  Regression -> MSE: 0.000285, MAE: 0.013631, R²: -0.0478
  Directional -> Accuracy: 0.3816, MCC: -0.1268, F1: 0.1754

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.36383 | val 0.60187
  Epoch 020 - train 0.35469 | val 0.59690
  Epoch 030 - train 0.36891 | val 0.59091
  Epoch 040 - train 0.36638 | val 0.58736
  Epoch 050 - train 0.36462 | val 0.58549
  Regression -> MSE: 0.000162, MAE: 0.009264, R²: -0.0863
  Directional -> Accuracy: 0.5077, MCC: 0.0751, F1: 0.4667

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.44468 | val 0.65920
  Epoch 020 - train 0.43021 | val 0.65288
  Epoch 030 - train 0.42322 | val 0.64557
  Epoch 040 - train 0.44647 | val 0.64057
  Epoch 050 - train 0.42737 | val 0.63859
  Regression -> MSE: 0.000254, MAE: 0.011646, R²: -0.1210
  Directional -> Accuracy: 0.4267, MCC: -0.1414, F1: 0.0444

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43083 | val 0.59013
  Epoch 020 - train 0.45958 | val 0.58776
  Epoch 021 - train 0.43793 | val 0.58681
  Regression -> MSE: 0.000142, MAE: 0.008184, R²: 0.0072
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.38973 | val 0.47219
  Epoch 020 - train 0.40180 | val 0.46914
  Epoch 022 - train 0.43861 | val 0.47072
  Regression -> MSE: 0.000167, MAE: 0.010294, R²: -0.0137
  Directional -> Accuracy: 0.5606, MCC: 0.2108, F1: 0.6882

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.45963 | val 0.54554
  Epoch 020 - train 0.47765 | val 0.54335
  Epoch 021 - train 0.46367 | val 0.54350
  Regression -> MSE: 0.000095, MAE: 0.007371, R²: -0.1101
  Directional -> Accuracy: 0.4655, MCC: -0.0555, F1: 0.4746

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.42288 | val 0.56965
  Epoch 020 - train 0.38819 | val 0.57148
  Epoch 021 - train 0.40581 | val 0.57649
  Regression -> MSE: 0.000213, MAE: 0.011132, R²: -0.0058
  Directional -> Accuracy: 0.4697, MCC: -0.0286, F1: 0.5882

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39946 | val 0.35602
  Epoch 020 - train 0.37644 | val 0.35750
  Epoch 021 - train 0.37021 | val 0.35755
  Regression -> MSE: 0.000095, MAE: 0.008065, R²: -0.0364
  Directional -> Accuracy: 0.5357, MCC: 0.0393, F1: 0.6176

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.44083 | val 0.30143
  Epoch 020 - train 0.42894 | val 0.30485
  Epoch 021 - train 0.42514 | val 0.30488
  Regression -> MSE: 0.000108, MAE: 0.008958, R²: -0.0460
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.44328 | val 0.37815
  Epoch 020 - train 0.44178 | val 0.37913
  Epoch 021 - train 0.45227 | val 0.37851
  Regression -> MSE: 0.000234, MAE: 0.012720, R²: -0.0129
  Directional -> Accuracy: 0.5349, MCC: -0.1095, F1: 0.6875

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.44321 | val 0.49805
  Epoch 020 - train 0.41371 | val 0.49415
  Epoch 021 - train 0.45090 | val 0.49607
  Regression -> MSE: 0.000177, MAE: 0.008057, R²: -0.0619
  Directional -> Accuracy: 0.4561, MCC: -0.2218, F1: 0.6076

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.40298 | val 0.28560
  Epoch 020 - train 0.40979 | val 0.28237
  Epoch 030 - train 0.41042 | val 0.28374
  Epoch 033 - train 0.40980 | val 0.28161
  Regression -> MSE: 0.000233, MAE: 0.011951, R²: 0.0155
  Directional -> Accuracy: 0.5366, MCC: 0.0472, F1: 0.6275

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.45004 | val 0.83579
  Epoch 020 - train 0.48657 | val 0.84262
  Epoch 021 - train 0.42203 | val 0.83901
  Regression -> MSE: 0.000238, MAE: 0.010176, R²: -0.0313
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.44182 | val 0.52774
  Epoch 020 - train 0.43455 | val 0.52642
  Epoch 025 - train 0.44267 | val 0.53084
  Regression -> MSE: 0.000138, MAE: 0.008150, R²: -0.0230
  Directional -> Accuracy: 0.5814, MCC: 0.1533, F1: 0.6897

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.43986 | val 0.58654
  Epoch 020 - train 0.42978 | val 0.58634
  Epoch 021 - train 0.47549 | val 0.58513
  Regression -> MSE: 0.000187, MAE: 0.010403, R²: 0.0054
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38996 | val 0.51389
  Epoch 020 - train 0.38410 | val 0.51123
  Epoch 021 - train 0.38118 | val 0.51283
  Regression -> MSE: 0.000270, MAE: 0.010642, R²: -0.0305
  Directional -> Accuracy: 0.5342, MCC: 0.1237, F1: 0.4688

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.42689 | val 0.31096
  Epoch 020 - train 0.40000 | val 0.31220
  Epoch 029 - train 0.41448 | val 0.31620
  Regression -> MSE: 0.000185, MAE: 0.010653, R²: -0.1127
  Directional -> Accuracy: 0.4737, MCC: -0.1644, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.42111 | val 0.47636
  Epoch 020 - train 0.38695 | val 0.47827
  Epoch 021 - train 0.39109 | val 0.47783
  Regression -> MSE: 0.000184, MAE: 0.010381, R²: -0.0205
  Directional -> Accuracy: 0.4091, MCC: -0.1763, F1: 0.4583

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.40312 | val 0.38028
  Epoch 020 - train 0.42152 | val 0.38009
  Epoch 021 - train 0.41339 | val 0.38090
  Regression -> MSE: 0.000345, MAE: 0.011768, R²: -0.0073
  Directional -> Accuracy: 0.5373, MCC: -0.0930, F1: 0.6931

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.45225 | val 0.21069
  Epoch 020 - train 0.43159 | val 0.21081
  Epoch 021 - train 0.44843 | val 0.21018
  Regression -> MSE: 0.000114, MAE: 0.008403, R²: -0.0837
  Directional -> Accuracy: 0.4884, MCC: -0.0849, F1: 0.6452

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.44999 | val 0.61593
  Epoch 020 - train 0.44057 | val 0.61406
  Epoch 023 - train 0.43924 | val 0.61586
  Regression -> MSE: 0.000218, MAE: 0.011139, R²: 0.0032
  Directional -> Accuracy: 0.5439, MCC: 0.1409, F1: 0.0714

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.41228 | val 0.85606
  Epoch 020 - train 0.44788 | val 0.85417
  Epoch 021 - train 0.44757 | val 0.85408
  Regression -> MSE: 0.000104, MAE: 0.007989, R²: -0.3410
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46137 | val 0.35648
  Epoch 020 - train 0.45075 | val 0.37112
  Epoch 021 - train 0.44125 | val 0.37231
  Regression -> MSE: 0.000332, MAE: 0.015013, R²: -0.0790
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.47989 | val 0.17207
  Epoch 020 - train 0.46688 | val 0.17057
  Epoch 030 - train 0.46977 | val 0.16965
  Regression -> MSE: 0.000246, MAE: 0.011372, R²: -0.0091
  Directional -> Accuracy: 0.5789, MCC: 0.2079, F1: 0.4667

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.40628 | val 0.50273
  Epoch 020 - train 0.41257 | val 0.50375
  Epoch 021 - train 0.38980 | val 0.50319
  Regression -> MSE: 0.000083, MAE: 0.007052, R²: -0.0225
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.47231 | val 0.55533
  Epoch 020 - train 0.47742 | val 0.53186
  Epoch 030 - train 0.46695 | val 0.51702
  Epoch 040 - train 0.45112 | val 0.50550
  Epoch 050 - train 0.41257 | val 0.49860
  Regression -> MSE: 0.000304, MAE: 0.014366, R²: 0.0104
  Directional -> Accuracy: 0.4681, MCC: -0.0792, F1: 0.5614

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45417 | val 0.51180
  Epoch 020 - train 0.49084 | val 0.51614
  Epoch 021 - train 0.48412 | val 0.51509
  Regression -> MSE: 0.000105, MAE: 0.007219, R²: -0.0690
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...

[I 2026-02-24 03:01:27,685] Trial 130 finished with value: -0.011510503996768302 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 1.069295699726497e-05, 'weight_decay': 1.46980538243518e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.9575619405227369, 'early_stopping_min_delta': 0.004019007870223637}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.41189 | val 0.67053
  Regression -> MSE: 0.000237, MAE: 0.012221, R²: -0.0014
  Directional -> Accuracy: 0.5574, MCC: 0.1265, F1: 0.2286

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07580 | val 0.09420
  Epoch 020 - train 0.07533 | val 0.09404
  Epoch 021 - train 0.07528 | val 0.09421
  Regression -> MSE: 0.000247, MAE: 0.012496, R²: 0.0033
  Directional -> Accuracy: 0.5195, MCC: 0.0476, F1: 0.5195

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07339 | val 0.07562
  Epoch 020 - train 0.07849 | val 0.07670
  Epoch 021 - train 0.07295 | val 0.07719
  Regression -> MSE: 0.000722, MAE: 0.019991, R²: -0.0547
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.08122 | val 0.12017
  Epoch 020 - train 0.07985 | val 0.12028
  Epoch 021 - train 0.07887 | val 0.12031
  Regression -> MSE: 0.000321, MAE: 0.014557, R²: -0.0361
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06810 | val 0.05974
  Epoch 020 - train 0.06616 | val 0.06011
  Epoch 021 - train 0.06331 | val 0.06026
  Regression -> MSE: 0.000352, MAE: 0.014637, R²: -0.0086
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07948 | val 0.07500
  Epoch 020 - train 0.07891 | val 0.07496
  Epoch 021 - train 0.07663 | val 0.07490
  Regression -> MSE: 0.000208, MAE: 0.010054, R²: -0.0195
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07476 | val 0.13389
  Epoch 020 - train 0.07112 | val 0.13426
  Epoch 021 - train 0.07478 | val 0.13436
  Regression -> MSE: 0.000564, MAE: 0.018225, R²: -0.0162
  Directional -> Accuracy: 0.4468, MCC: -0.2556, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.08060 | val 0.08879
  Epoch 020 - train 0.07866 | val 0.08833
  Epoch 021 - train 0.07791 | val 0.08829
  Regression -> MSE: 0.000250, MAE: 0.012180, R²: -0.0168
  Directional -> Accuracy: 0.4348, MCC: -0.1192, F1: 0.4000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07520 | val 0.08151
  Epoch 020 - train 0.07553 | val 0.08204
  Epoch 021 - train 0.07548 | val 0.08213
  Regression -> MSE: 0.000603, MAE: 0.019260, R²: -0.0097
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07497 | val 0.08877
  Epoch 020 - train 0.07578 | val 0.08886
  Epoch 021 - train 0.07420 | val 0.08880
  Regression -> MSE: 0.000376, MAE: 0.015943, R²: 0.0207
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07732 | val 0.09896
  Epoch 020 - train 0.07632 | val 0.09625
  Epoch 021 - train 0.08054 | val 0.09584
  Regression -> MSE: 0.000243, MAE: 0.012179, R²: -0.0050
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06998 | val 0.10882
  Epoch 020 - train 0.06918 | val 0.10906
  Epoch 021 - train 0.07135 | val 0.10968
  Regression -> MSE: 0.000310, MAE: 0.013633, R²: 0.0045
  Directional -> Accuracy: 0.6000, MCC: 0.2274, F1: 0.2857

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07689 | val 0.09743
  Epoch 020 - train 0.07657 | val 0.09798
  Epoch 021 - train 0.07245 | val 0.09763
  Regression -> MSE: 0.000675, MAE: 0.019412, R²: 0.0035
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07659 | val 0.09228
  Epoch 020 - train 0.07345 | val 0.09384
  Epoch 021 - train 0.07982 | val 0.09329
  Regression -> MSE: 0.000140, MAE: 0.009031, R²: -0.0137
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.07819 | val 0.10358
  Epoch 020 - train 0.07531 | val 0.10310
  Epoch 021 - train 0.07388 | val 0.10293
  Regression -> MSE: 0.000227, MAE: 0.010768, R²: -0.0111
  Directional -> Accuracy: 0.5574, MCC: 0.2148, F1: 0.2703

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07556 | val 0.14810
  Epoch 020 - train 0.07619 | val 0.14816
  Epoch 021 - train 0.07695 | val 0.14857
  Regression -> MSE: 0.000365, MAE: 0.016276, R²: -0.0068
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07896 | val 0.08216
  Epoch 020 - train 0.07618 | val 0.08078
  Epoch 021 - train 0.07899 | val 0.08102
  Regression -> MSE: 0.000109, MAE: 0.007967, R²: -0.0095
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07663 | val 0.11481
  Epoch 020 - train 0.07690 | val 0.11550
  Epoch 021 - train 0.07721 | val 0.11551
  Regression -> MSE: 0.000158, MAE: 0.009936, R²: -0.0107
  Directional -> Accuracy: 0.6102, MCC: -0.1013, F1: 0.7579

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07544 | val 0.07435
  Epoch 020 - train 0.07368 | val 0.07445
  Epoch 021 - train 0.07581 | val 0.07451
  Regression -> MSE: 0.000274, MAE: 0.013059, R²: -0.0056
  Directional -> Accuracy: 0.5526, MCC: -0.0754, F1: 0.6964

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06903 | val 0.09230
  Epoch 020 - train 0.06900 | val 0.09188
  Epoch 021 - train 0.06679 | val 0.09201
  Regression -> MSE: 0.000169, MAE: 0.009221, R²: -0.1282
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07554 | val 0.09881
  Epoch 020 - train 0.07441 | val 0.09962
  Epoch 021 - train 0.07277 | val 0.10009
  Regression -> MSE: 0.000227, MAE: 0.010969, R²: -0.0038
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08736 | val 0.09140
  Epoch 020 - train 0.07580 | val 0.09152
  Epoch 021 - train 0.08159 | val 0.09143
  Regression -> MSE: 0.000152, MAE: 0.008745, R²: -0.0595
  Directional -> Accuracy: 0.5417, MCC: 0.1309, F1: 0.5600

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07785 | val 0.07765
  Epoch 020 - train 0.07204 | val 0.07715
  Epoch 021 - train 0.07376 | val 0.07726
  Regression -> MSE: 0.000176, MAE: 0.010320, R²: -0.0644
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.1538

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08335 | val 0.08075
  Epoch 020 - train 0.08223 | val 0.08057
  Epoch 021 - train 0.07754 | val 0.08072
  Regression -> MSE: 0.000084, MAE: 0.007025, R²: 0.0146
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07177 | val 0.09115
  Epoch 020 - train 0.06987 | val 0.09197
  Epoch 021 - train 0.07119 | val 0.09110
  Regression -> MSE: 0.000210, MAE: 0.011055, R²: 0.0074
  Directional -> Accuracy: 0.5303, MCC: 0.0859, F1: 0.5867

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07498 | val 0.07349
  Epoch 020 - train 0.07352 | val 0.07291
  Epoch 021 - train 0.07439 | val 0.07271
  Regression -> MSE: 0.000106, MAE: 0.008398, R²: -0.1562
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07615 | val 0.05917
  Epoch 020 - train 0.08246 | val 0.06257
  Epoch 021 - train 0.07864 | val 0.06253
  Regression -> MSE: 0.000104, MAE: 0.008818, R²: -0.0111
  Directional -> Accuracy: 0.3913, MCC: -0.1962, F1: 0.5484

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07999 | val 0.06827
  Epoch 020 - train 0.07921 | val 0.06813
  Epoch 021 - train 0.08076 | val 0.06826
  Regression -> MSE: 0.000233, MAE: 0.012572, R²: -0.0048
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07243 | val 0.08566
  Epoch 020 - train 0.07426 | val 0.08567
  Epoch 021 - train 0.06886 | val 0.08576
  Regression -> MSE: 0.000180, MAE: 0.007903, R²: -0.0817
  Directional -> Accuracy: 0.4737, MCC: 0.1044, F1: 0.1667

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08641 | val 0.06740
  Epoch 020 - train 0.09061 | val 0.06990
  Epoch 021 - train 0.08294 | val 0.06979
  Regression -> MSE: 0.000239, MAE: 0.011949, R²: -0.0118
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.08022 | val 0.10768
  Epoch 020 - train 0.07843 | val 0.10797
  Epoch 021 - train 0.07704 | val 0.10811
  Regression -> MSE: 0.000233, MAE: 0.010059, R²: -0.0130
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07444 | val 0.08817
  Epoch 020 - train 0.07371 | val 0.08881
  Epoch 021 - train 0.07575 | val 0.08866
  Regression -> MSE: 0.000139, MAE: 0.008311, R²: -0.0281
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07585 | val 0.08875
  Epoch 020 - train 0.07294 | val 0.08854
  Epoch 021 - train 0.07993 | val 0.08852
  Regression -> MSE: 0.000190, MAE: 0.010390, R²: -0.0079
  Directional -> Accuracy: 0.5600, MCC: 0.1548, F1: 0.7105

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06979 | val 0.08327
  Epoch 020 - train 0.07101 | val 0.08298
  Epoch 021 - train 0.06755 | val 0.08287
  Regression -> MSE: 0.000271, MAE: 0.010648, R²: -0.0334
  Directional -> Accuracy: 0.5205, MCC: 0.0162, F1: 0.5882

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08080 | val 0.06548
  Epoch 020 - train 0.08448 | val 0.07732
  Epoch 021 - train 0.08040 | val 0.07778
  Regression -> MSE: 0.000169, MAE: 0.010392, R²: -0.0140
  Directional -> Accuracy: 0.4737, MCC: -0.0976, F1: 0.6296

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06928 | val 0.07285
  Epoch 020 - train 0.06754 | val 0.07342
  Epoch 021 - train 0.07045 | val 0.07351
  Regression -> MSE: 0.000183, MAE: 0.010368, R²: -0.0172
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07806 | val 0.07034
  Epoch 020 - train 0.07818 | val 0.07010
  Epoch 021 - train 0.07189 | val 0.07015
  Regression -> MSE: 0.000354, MAE: 0.012685, R²: -0.0338
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.07935 | val 0.04650
  Epoch 020 - train 0.08033 | val 0.04771
  Epoch 021 - train 0.07862 | val 0.04805
  Regression -> MSE: 0.000132, MAE: 0.008666, R²: -0.2568
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07730 | val 0.09801
  Epoch 020 - train 0.07988 | val 0.09776
  Epoch 021 - train 0.07639 | val 0.09766
  Regression -> MSE: 0.000224, MAE: 0.011475, R²: -0.0241
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07875 | val 0.11872
  Epoch 020 - train 0.08045 | val 0.11757
  Epoch 021 - train 0.07642 | val 0.11775
  Regression -> MSE: 0.000098, MAE: 0.007719, R²: -0.2658
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07615 | val 0.06307
  Epoch 020 - train 0.07212 | val 0.06533
  Epoch 021 - train 0.07337 | val 0.06520
  Regression -> MSE: 0.000330, MAE: 0.015001, R²: -0.0718
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07534 | val 0.05231
  Epoch 020 - train 0.07707 | val 0.05796
  Epoch 021 - train 0.08837 | val 0.05819
  Regression -> MSE: 0.000257, MAE: 0.011472, R²: -0.0561
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.07176 | val 0.07984
  Epoch 020 - train 0.07197 | val 0.07992
  Epoch 021 - train 0.07361 | val 0.07993
  Regression -> MSE: 0.000080, MAE: 0.007056, R²: 0.0048
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07418 | val 0.08910
  Epoch 020 - train 0.07738 | val 0.09331
  Epoch 021 - train 0.07697 | val 0.09319
  Regression -> MSE: 0.000307, MAE: 0.014549, R²: -0.0017
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07617 | val 0.07981
  Epoch 020 - train 0.07890 | val 0.08185
  Epoch 021 - train 0.07278 | val 0.08198
  Regression -> MSE: 0.000098, MAE: 0.007183, R²: 0.0013
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08882 | val 0.09543
  Epoch 020 - train 0.08958 | val 0.09822
  Epoch 021 - train 0.08231 | val 0.09822
  Regression -> MSE: 0.000172, MAE: 0.009643, R²: -0.0035
  Directional -> Accuracy: 0.3878, MCC: -0.1312, F1: 0.4643

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 03:05:45,214] Trial 131 finished with value: -0.011467524718126393 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 6.5660594942022794e-06, 'weight_decay': 8.820386108344038e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.10092219240614018, 'early_stopping_min_delta': 0.004713518660360219}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.07995 | val 0.10020
  Regression -> MSE: 0.000241, MAE: 0.012399, R²: -0.0179
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14750 | val 0.21518
  Epoch 020 - train 0.14637 | val 0.21375
  Epoch 021 - train 0.14289 | val 0.21220
  Regression -> MSE: 0.000249, MAE: 0.012593, R²: -0.0064
  Directional -> Accuracy: 0.4805, MCC: 0.0962, F1: 0.6296

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14706 | val 0.19620
  Epoch 020 - train 0.14642 | val 0.20503
  Epoch 021 - train 0.14446 | val 0.20409
  Regression -> MSE: 0.000695, MAE: 0.019532, R²: -0.0154
  Directional -> Accuracy: 0.5652, MCC: 0.0280, F1: 0.7143

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16085 | val 0.24296
  Epoch 020 - train 0.14562 | val 0.24981
  Epoch 021 - train 0.15221 | val 0.25007
  Regression -> MSE: 0.000317, MAE: 0.014462, R²: -0.0224
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13410 | val 0.13605
  Epoch 020 - train 0.12942 | val 0.13950
  Epoch 021 - train 0.13058 | val 0.13853
  Regression -> MSE: 0.000350, MAE: 0.014554, R²: -0.0008
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14965 | val 0.17282
  Epoch 020 - train 0.15163 | val 0.17187
  Epoch 021 - train 0.14751 | val 0.17302
  Regression -> MSE: 0.000211, MAE: 0.010669, R²: -0.0348
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.14239 | val 0.30376
  Epoch 020 - train 0.13469 | val 0.32835
  Epoch 021 - train 0.13878 | val 0.32853
  Regression -> MSE: 0.000573, MAE: 0.018467, R²: -0.0314
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15926 | val 0.18908
  Epoch 020 - train 0.15003 | val 0.18895
  Epoch 021 - train 0.15325 | val 0.18894
  Regression -> MSE: 0.000243, MAE: 0.011905, R²: 0.0104
  Directional -> Accuracy: 0.5217, MCC: 0.0583, F1: 0.4923

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15602 | val 0.23358
  Epoch 020 - train 0.16997 | val 0.23834
  Epoch 021 - train 0.13958 | val 0.23709
  Regression -> MSE: 0.000688, MAE: 0.020797, R²: -0.1522
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13827 | val 0.17933
  Epoch 020 - train 0.14285 | val 0.18253
  Epoch 021 - train 0.14373 | val 0.18333
  Regression -> MSE: 0.000388, MAE: 0.015973, R²: -0.0107
  Directional -> Accuracy: 0.4694, MCC: 0.1303, F1: 0.6286

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15408 | val 0.21758
  Epoch 020 - train 0.14439 | val 0.22032
  Epoch 021 - train 0.13905 | val 0.22017
  Regression -> MSE: 0.000241, MAE: 0.011912, R²: 0.0022
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13825 | val 0.25733
  Epoch 020 - train 0.13240 | val 0.25704
  Epoch 021 - train 0.14059 | val 0.25697
  Regression -> MSE: 0.000312, MAE: 0.013740, R²: -0.0046
  Directional -> Accuracy: 0.4400, MCC: -0.1548, F1: 0.6111

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15981 | val 0.20490
  Epoch 020 - train 0.15292 | val 0.20241
  Epoch 021 - train 0.15521 | val 0.20308
  Regression -> MSE: 0.000678, MAE: 0.019534, R²: -0.0011
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.1714

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13793 | val 0.17702
  Epoch 020 - train 0.13564 | val 0.18573
  Epoch 021 - train 0.14268 | val 0.18535
  Regression -> MSE: 0.000138, MAE: 0.009203, R²: -0.0008
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13060 | val 0.19009
  Epoch 020 - train 0.12896 | val 0.19591
  Epoch 021 - train 0.13503 | val 0.19508
  Regression -> MSE: 0.000225, MAE: 0.010699, R²: -0.0004
  Directional -> Accuracy: 0.5410, MCC: 0.1744, F1: 0.2222

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15125 | val 0.32139
  Epoch 020 - train 0.14392 | val 0.32205
  Epoch 021 - train 0.14952 | val 0.32176
  Regression -> MSE: 0.000362, MAE: 0.015988, R²: 0.0017
  Directional -> Accuracy: 0.4231, MCC: -0.1670, F1: 0.5833

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16240 | val 0.15902
  Epoch 020 - train 0.15428 | val 0.15586
  Epoch 021 - train 0.14665 | val 0.15567
  Regression -> MSE: 0.000111, MAE: 0.008189, R²: -0.0245
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14156 | val 0.28299
  Epoch 020 - train 0.14255 | val 0.28623
  Epoch 021 - train 0.13914 | val 0.28610
  Regression -> MSE: 0.000156, MAE: 0.009720, R²: -0.0020
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14817 | val 0.16165
  Epoch 020 - train 0.14456 | val 0.16113
  Epoch 021 - train 0.14986 | val 0.16131
  Regression -> MSE: 0.000275, MAE: 0.013249, R²: -0.0091
  Directional -> Accuracy: 0.5263, MCC: -0.0869, F1: 0.6604

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12934 | val 0.19736
  Epoch 020 - train 0.12915 | val 0.20092
  Epoch 021 - train 0.12292 | val 0.20048
  Regression -> MSE: 0.000159, MAE: 0.008827, R²: -0.0647
  Directional -> Accuracy: 0.5385, MCC: 0.1028, F1: 0.5455

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15238 | val 0.21646
  Epoch 020 - train 0.14346 | val 0.21277
  Epoch 021 - train 0.14373 | val 0.21281
  Regression -> MSE: 0.000238, MAE: 0.010923, R²: -0.0505
  Directional -> Accuracy: 0.4800, MCC: 0.1507, F1: 0.0930

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16362 | val 0.19381
  Epoch 020 - train 0.15536 | val 0.19483
  Epoch 021 - train 0.14371 | val 0.19485
  Regression -> MSE: 0.000145, MAE: 0.008397, R²: -0.0115
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13421 | val 0.18636
  Epoch 020 - train 0.13494 | val 0.18608
  Epoch 021 - train 0.13316 | val 0.18608
  Regression -> MSE: 0.000163, MAE: 0.010356, R²: 0.0128
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15826 | val 0.17571
  Epoch 020 - train 0.15036 | val 0.17543
  Epoch 021 - train 0.14704 | val 0.17522
  Regression -> MSE: 0.000085, MAE: 0.007064, R²: -0.0015
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15840 | val 0.20368
  Epoch 020 - train 0.14812 | val 0.20272
  Epoch 021 - train 0.14513 | val 0.20246
  Regression -> MSE: 0.000217, MAE: 0.011033, R²: -0.0250
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13764 | val 0.14231
  Epoch 020 - train 0.13634 | val 0.14235
  Epoch 021 - train 0.13404 | val 0.14189
  Regression -> MSE: 0.000100, MAE: 0.008269, R²: -0.0880
  Directional -> Accuracy: 0.3929, MCC: -0.2052, F1: 0.3929

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14189 | val 0.12550
  Epoch 020 - train 0.14848 | val 0.13074
  Epoch 021 - train 0.15426 | val 0.13084
  Regression -> MSE: 0.000113, MAE: 0.009105, R²: -0.0980
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16916 | val 0.15727
  Epoch 020 - train 0.15008 | val 0.15932
  Epoch 021 - train 0.16074 | val 0.15872
  Regression -> MSE: 0.000239, MAE: 0.012777, R²: -0.0320
  Directional -> Accuracy: 0.3953, MCC: -0.1508, F1: 0.2778

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14061 | val 0.19803
  Epoch 020 - train 0.13881 | val 0.19845
  Epoch 021 - train 0.14673 | val 0.19868
  Regression -> MSE: 0.000174, MAE: 0.007975, R²: -0.0446
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13884 | val 0.13519
  Epoch 020 - train 0.16064 | val 0.14208
  Epoch 021 - train 0.15481 | val 0.14260
  Regression -> MSE: 0.000235, MAE: 0.011783, R²: 0.0074
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.15033 | val 0.25454
  Epoch 020 - train 0.15326 | val 0.26167
  Epoch 021 - train 0.15581 | val 0.26147
  Regression -> MSE: 0.000229, MAE: 0.009909, R²: 0.0042
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16259 | val 0.17689
  Epoch 020 - train 0.14397 | val 0.18111
  Epoch 021 - train 0.15622 | val 0.18101
  Regression -> MSE: 0.000136, MAE: 0.008263, R²: -0.0076
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14508 | val 0.18802
  Epoch 020 - train 0.14623 | val 0.18875
  Epoch 021 - train 0.15019 | val 0.18877
  Regression -> MSE: 0.000189, MAE: 0.010469, R²: -0.0045
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14135 | val 0.16579
  Epoch 020 - train 0.13832 | val 0.16565
  Epoch 021 - train 0.13635 | val 0.16590
  Regression -> MSE: 0.000282, MAE: 0.010960, R²: -0.0761
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14779 | val 0.12255
  Epoch 020 - train 0.13192 | val 0.13257
  Epoch 021 - train 0.14074 | val 0.13398
  Regression -> MSE: 0.000169, MAE: 0.010397, R²: -0.0112
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15175 | val 0.16228
  Epoch 020 - train 0.14263 | val 0.16183
  Epoch 021 - train 0.13094 | val 0.16155
  Regression -> MSE: 0.000181, MAE: 0.010386, R²: -0.0081
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14411 | val 0.14887
  Epoch 020 - train 0.14106 | val 0.14892
  Epoch 021 - train 0.14068 | val 0.14901
  Regression -> MSE: 0.000346, MAE: 0.012000, R²: -0.0109
  Directional -> Accuracy: 0.3881, MCC: -0.1940, F1: 0.0889

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.17434 | val 0.10401
  Epoch 020 - train 0.17375 | val 0.10377
  Epoch 021 - train 0.15285 | val 0.10392
  Regression -> MSE: 0.000135, MAE: 0.008640, R²: -0.2821
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15408 | val 0.22240
  Epoch 020 - train 0.14901 | val 0.22659
  Epoch 021 - train 0.15101 | val 0.22598
  Regression -> MSE: 0.000219, MAE: 0.011302, R²: -0.0015
  Directional -> Accuracy: 0.4737, MCC: -0.1700, F1: 0.0625

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14448 | val 0.33810
  Epoch 020 - train 0.15304 | val 0.35242
  Epoch 021 - train 0.14615 | val 0.35283
  Regression -> MSE: 0.000088, MAE: 0.007360, R²: -0.1345
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14783 | val 0.11426
  Epoch 020 - train 0.14708 | val 0.11885
  Epoch 021 - train 0.14307 | val 0.11898
  Regression -> MSE: 0.000307, MAE: 0.013773, R²: 0.0016
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15810 | val 0.09899
  Epoch 020 - train 0.15915 | val 0.12102
  Epoch 021 - train 0.13779 | val 0.12270
  Regression -> MSE: 0.000251, MAE: 0.011418, R²: -0.0306
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13573 | val 0.18629
  Epoch 020 - train 0.13560 | val 0.18422
  Epoch 021 - train 0.13654 | val 0.18504
  Regression -> MSE: 0.000081, MAE: 0.007066, R²: 0.0000
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14564 | val 0.18100
  Epoch 020 - train 0.14754 | val 0.18718
  Epoch 021 - train 0.15373 | val 0.18752
  Regression -> MSE: 0.000311, MAE: 0.014535, R²: -0.0142
  Directional -> Accuracy: 0.4894, MCC: -0.0815, F1: 0.6471

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14491 | val 0.19442
  Epoch 020 - train 0.14330 | val 0.20413
  Epoch 021 - train 0.15006 | val 0.20502
  Regression -> MSE: 0.000099, MAE: 0.007090, R²: -0.0033
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17016 | val 0.19167
  Epoch 020 - train 0.15461 | val 0.20148
  Epoch 021 - train 0.15855 | val 0.20144
  Regression -> MSE: 0.000172, MAE: 0.009703, R²: 0.0017
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 03:10:06,119] Trial 132 finished with value: -0.011450260042795996 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 5.681485633649734e-05, 'weight_decay': 1.0534471576782369e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.23330478024401, 'early_stopping_min_delta': 0.009158132799182645}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.15641 | val 0.27815
  Regression -> MSE: 0.000241, MAE: 0.012701, R²: -0.0171
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09894 | val 0.13229
  Epoch 020 - train 0.09823 | val 0.13200
  Epoch 021 - train 0.09633 | val 0.13164
  Regression -> MSE: 0.000264, MAE: 0.013101, R²: -0.0661
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09055 | val 0.10032
  Epoch 020 - train 0.09903 | val 0.10661
  Epoch 021 - train 0.09833 | val 0.10744
  Regression -> MSE: 0.000682, MAE: 0.019232, R²: 0.0038
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10154 | val 0.15720
  Epoch 020 - train 0.10052 | val 0.15760
  Epoch 021 - train 0.09297 | val 0.15751
  Regression -> MSE: 0.000312, MAE: 0.014385, R²: -0.0045
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09017 | val 0.15303
  Epoch 020 - train 0.08913 | val 0.16404
  Epoch 021 - train 0.08976 | val 0.16156
  Regression -> MSE: 0.000432, MAE: 0.016251, R²: -0.2357
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09491 | val 0.09436
  Epoch 020 - train 0.09445 | val 0.09234
  Epoch 021 - train 0.09282 | val 0.09223
  Regression -> MSE: 0.000204, MAE: 0.010114, R²: -0.0033
  Directional -> Accuracy: 0.4706, MCC: -0.0119, F1: 0.0690

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09649 | val 0.17603
  Epoch 020 - train 0.08980 | val 0.17759
  Epoch 021 - train 0.09843 | val 0.17733
  Regression -> MSE: 0.000593, MAE: 0.018838, R²: -0.0686
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10064 | val 0.11762
  Epoch 020 - train 0.10080 | val 0.11746
  Epoch 021 - train 0.09954 | val 0.11739
  Regression -> MSE: 0.000244, MAE: 0.012088, R²: 0.0051
  Directional -> Accuracy: 0.4928, MCC: 0.1044, F1: 0.5679

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09757 | val 0.12019
  Epoch 020 - train 0.09347 | val 0.12293
  Epoch 021 - train 0.09956 | val 0.12352
  Regression -> MSE: 0.000614, MAE: 0.019541, R²: -0.0280
  Directional -> Accuracy: 0.4091, MCC: -0.0872, F1: 0.5185

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09505 | val 0.12255
  Epoch 020 - train 0.09231 | val 0.12211
  Epoch 021 - train 0.09688 | val 0.12256
  Regression -> MSE: 0.000383, MAE: 0.016065, R²: 0.0022
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10035 | val 0.13128
  Epoch 020 - train 0.09642 | val 0.13119
  Epoch 021 - train 0.09712 | val 0.13179
  Regression -> MSE: 0.000242, MAE: 0.011852, R²: -0.0021
  Directional -> Accuracy: 0.4000, MCC: -0.1980, F1: 0.5714

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09505 | val 0.13489
  Epoch 020 - train 0.09155 | val 0.13694
  Epoch 021 - train 0.09679 | val 0.13702
  Regression -> MSE: 0.000312, MAE: 0.013684, R²: -0.0020
  Directional -> Accuracy: 0.4400, MCC: -0.0936, F1: 0.5882

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09690 | val 0.11234
  Epoch 020 - train 0.09821 | val 0.11397
  Epoch 021 - train 0.10249 | val 0.11364
  Regression -> MSE: 0.000679, MAE: 0.019601, R²: -0.0025
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10145 | val 0.09829
  Epoch 020 - train 0.09670 | val 0.09865
  Epoch 021 - train 0.09455 | val 0.09852
  Regression -> MSE: 0.000141, MAE: 0.009250, R²: -0.0220
  Directional -> Accuracy: 0.4651, MCC: 0.1373, F1: 0.6230

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09155 | val 0.11845
  Epoch 020 - train 0.09162 | val 0.11647
  Epoch 021 - train 0.08867 | val 0.11638
  Regression -> MSE: 0.000227, MAE: 0.010721, R²: -0.0073
  Directional -> Accuracy: 0.4918, MCC: -0.0043, F1: 0.1143

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09701 | val 0.19033
  Epoch 020 - train 0.09885 | val 0.19047
  Epoch 021 - train 0.09902 | val 0.19054
  Regression -> MSE: 0.000360, MAE: 0.016098, R²: 0.0048
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10855 | val 0.11012
  Epoch 020 - train 0.10273 | val 0.10886
  Epoch 021 - train 0.10274 | val 0.10816
  Regression -> MSE: 0.000109, MAE: 0.008047, R²: -0.0116
  Directional -> Accuracy: 0.4714, MCC: -0.1001, F1: 0.5747

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09474 | val 0.15712
  Epoch 020 - train 0.09635 | val 0.15764
  Epoch 021 - train 0.09759 | val 0.15773
  Regression -> MSE: 0.000157, MAE: 0.009913, R²: -0.0088
  Directional -> Accuracy: 0.6271, MCC: 0.0492, F1: 0.7660

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09986 | val 0.09858
  Epoch 020 - train 0.10046 | val 0.09866
  Epoch 021 - train 0.10374 | val 0.09896
  Regression -> MSE: 0.000271, MAE: 0.012930, R²: 0.0037
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09036 | val 0.12616
  Epoch 020 - train 0.08782 | val 0.12612
  Epoch 021 - train 0.08625 | val 0.12589
  Regression -> MSE: 0.000153, MAE: 0.008757, R²: -0.0204
  Directional -> Accuracy: 0.5692, MCC: 0.0093, F1: 0.7083

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10638 | val 0.14115
  Epoch 020 - train 0.10484 | val 0.14027
  Epoch 021 - train 0.10524 | val 0.14043
  Regression -> MSE: 0.000235, MAE: 0.010952, R²: -0.0402
  Directional -> Accuracy: 0.5333, MCC: 0.0424, F1: 0.6067

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09686 | val 0.11729
  Epoch 020 - train 0.09724 | val 0.11781
  Epoch 021 - train 0.09462 | val 0.11772
  Regression -> MSE: 0.000146, MAE: 0.008498, R²: -0.0195
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09998 | val 0.11539
  Epoch 020 - train 0.09702 | val 0.11621
  Epoch 021 - train 0.09246 | val 0.11633
  Regression -> MSE: 0.000166, MAE: 0.010671, R²: -0.0067
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10361 | val 0.11013
  Epoch 020 - train 0.10285 | val 0.11013
  Epoch 021 - train 0.10059 | val 0.11018
  Regression -> MSE: 0.000094, MAE: 0.007481, R²: -0.1042
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09672 | val 0.11391
  Epoch 020 - train 0.09757 | val 0.11474
  Epoch 021 - train 0.09313 | val 0.11521
  Regression -> MSE: 0.000212, MAE: 0.011082, R²: 0.0005
  Directional -> Accuracy: 0.5152, MCC: 0.0465, F1: 0.5556

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09487 | val 0.08696
  Epoch 020 - train 0.08881 | val 0.08665
  Epoch 021 - train 0.09000 | val 0.08687
  Regression -> MSE: 0.000096, MAE: 0.008124, R²: -0.0435
  Directional -> Accuracy: 0.5714, MCC: 0.0967, F1: 0.7073

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10241 | val 0.07518
  Epoch 020 - train 0.09377 | val 0.07468
  Epoch 021 - train 0.09608 | val 0.07465
  Regression -> MSE: 0.000108, MAE: 0.008982, R²: -0.0492
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10198 | val 0.09227
  Epoch 020 - train 0.09945 | val 0.09331
  Epoch 021 - train 0.10446 | val 0.09290
  Regression -> MSE: 0.000235, MAE: 0.012671, R²: -0.0157
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10052 | val 0.11532
  Epoch 020 - train 0.09948 | val 0.11559
  Epoch 021 - train 0.09601 | val 0.11560
  Regression -> MSE: 0.000175, MAE: 0.007800, R²: -0.0535
  Directional -> Accuracy: 0.5789, MCC: 0.1094, F1: 0.6842

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10914 | val 0.08679
  Epoch 020 - train 0.10150 | val 0.08951
  Epoch 021 - train 0.09982 | val 0.08972
  Regression -> MSE: 0.000237, MAE: 0.011827, R²: -0.0018
  Directional -> Accuracy: 0.5610, MCC: 0.1145, F1: 0.7000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09717 | val 0.15222
  Epoch 020 - train 0.09374 | val 0.15371
  Epoch 021 - train 0.10148 | val 0.15374
  Regression -> MSE: 0.000232, MAE: 0.009867, R²: -0.0048
  Directional -> Accuracy: 0.5581, MCC: 0.2261, F1: 0.1739

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10133 | val 0.12100
  Epoch 020 - train 0.09882 | val 0.12396
  Epoch 021 - train 0.09799 | val 0.12420
  Regression -> MSE: 0.000136, MAE: 0.008224, R²: -0.0061
  Directional -> Accuracy: 0.5116, MCC: -0.0724, F1: 0.6667

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10483 | val 0.13043
  Epoch 020 - train 0.10523 | val 0.12946
  Epoch 021 - train 0.10453 | val 0.12930
  Regression -> MSE: 0.000188, MAE: 0.010514, R²: 0.0023
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09106 | val 0.11902
  Epoch 020 - train 0.08928 | val 0.11874
  Epoch 021 - train 0.08779 | val 0.11831
  Regression -> MSE: 0.000263, MAE: 0.010609, R²: -0.0027
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09354 | val 0.08347
  Epoch 020 - train 0.10347 | val 0.08819
  Epoch 021 - train 0.09851 | val 0.08855
  Regression -> MSE: 0.000169, MAE: 0.010371, R²: -0.0136
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09160 | val 0.10527
  Epoch 020 - train 0.09119 | val 0.10513
  Epoch 021 - train 0.09046 | val 0.10531
  Regression -> MSE: 0.000185, MAE: 0.010539, R²: -0.0281
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09493 | val 0.08716
  Epoch 020 - train 0.09103 | val 0.08775
  Epoch 021 - train 0.09403 | val 0.08788
  Regression -> MSE: 0.000345, MAE: 0.011824, R²: -0.0057
  Directional -> Accuracy: 0.5075, MCC: -0.0432, F1: 0.6118

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.09758 | val 0.06517
  Epoch 020 - train 0.10133 | val 0.06538
  Epoch 021 - train 0.09738 | val 0.06529
  Regression -> MSE: 0.000112, MAE: 0.008337, R²: -0.0654
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10104 | val 0.13475
  Epoch 020 - train 0.10347 | val 0.13441
  Epoch 021 - train 0.09907 | val 0.13454
  Regression -> MSE: 0.000218, MAE: 0.011240, R²: 0.0019
  Directional -> Accuracy: 0.5263, MCC: 0.0101, F1: 0.0690

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09834 | val 0.16494
  Epoch 020 - train 0.09426 | val 0.16584
  Epoch 021 - train 0.09542 | val 0.16597
  Regression -> MSE: 0.000090, MAE: 0.007414, R²: -0.1528
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10296 | val 0.07971
  Epoch 020 - train 0.09235 | val 0.07711
  Epoch 021 - train 0.09884 | val 0.07690
  Regression -> MSE: 0.000351, MAE: 0.015690, R²: -0.1400
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10482 | val 0.05700
  Epoch 020 - train 0.10737 | val 0.05777
  Epoch 021 - train 0.09470 | val 0.05784
  Regression -> MSE: 0.000254, MAE: 0.011554, R²: -0.0436
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09352 | val 0.12315
  Epoch 020 - train 0.09435 | val 0.12289
  Epoch 021 - train 0.09332 | val 0.12257
  Regression -> MSE: 0.000083, MAE: 0.007038, R²: -0.0238
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10146 | val 0.12106
  Epoch 020 - train 0.09941 | val 0.12240
  Epoch 021 - train 0.10080 | val 0.12243
  Regression -> MSE: 0.000307, MAE: 0.014509, R²: 0.0009
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10186 | val 0.11591
  Epoch 020 - train 0.10262 | val 0.12104
  Epoch 021 - train 0.10084 | val 0.12122
  Regression -> MSE: 0.000100, MAE: 0.007120, R²: -0.0202
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11003 | val 0.10889
  Epoch 020 - train 0.10945 | val 0.10967
  Epoch 021 - train 0.10013 | val 0.10989
  Regression -> MSE: 0.000184, MAE: 0.009467, R²: -0.0692
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 03:14:27,474] Trial 133 finished with value: -0.011476369561819738 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 9.00593174087493e-06, 'weight_decay': 5.3766531698681575e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.1384746859565097, 'early_stopping_min_delta': 0.009495887601740624}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.09735 | val 0.13922
  Regression -> MSE: 0.000237, MAE: 0.012257, R²: 0.0007
  Directional -> Accuracy: 0.5410, MCC: 0.0745, F1: 0.1765

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12126 | val 0.16464
  Epoch 020 - train 0.12048 | val 0.16354
  Epoch 021 - train 0.11762 | val 0.16416
  Regression -> MSE: 0.000249, MAE: 0.012542, R²: -0.0047
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11742 | val 0.11962
  Epoch 020 - train 0.11430 | val 0.12147
  Epoch 021 - train 0.11543 | val 0.12153
  Regression -> MSE: 0.000690, MAE: 0.019498, R²: -0.0082
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12258 | val 0.19773
  Epoch 020 - train 0.12515 | val 0.19553
  Epoch 030 - train 0.12566 | val 0.19540
  Regression -> MSE: 0.000307, MAE: 0.014174, R²: 0.0100
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09774 | val 0.14334
  Epoch 020 - train 0.10295 | val 0.15038
  Epoch 021 - train 0.10345 | val 0.15377
  Regression -> MSE: 0.000349, MAE: 0.014533, R²: 0.0009
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12177 | val 0.12408
  Epoch 020 - train 0.12264 | val 0.12175
  Epoch 021 - train 0.12042 | val 0.12229
  Regression -> MSE: 0.000206, MAE: 0.009920, R²: -0.0103
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11512 | val 0.24246
  Epoch 020 - train 0.11644 | val 0.24286
  Epoch 021 - train 0.11278 | val 0.24171
  Regression -> MSE: 0.000584, MAE: 0.018632, R²: -0.0527
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12468 | val 0.14756
  Epoch 020 - train 0.12513 | val 0.15043
  Epoch 029 - train 0.12271 | val 0.15054
  Regression -> MSE: 0.000248, MAE: 0.012623, R²: -0.0121
  Directional -> Accuracy: 0.4493, MCC: 0.0572, F1: 0.5682

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12323 | val 0.16697
  Epoch 020 - train 0.12020 | val 0.16588
  Epoch 021 - train 0.12321 | val 0.16640
  Regression -> MSE: 0.000637, MAE: 0.020053, R²: -0.0656
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11263 | val 0.14303
  Epoch 020 - train 0.11422 | val 0.14414
  Epoch 021 - train 0.11212 | val 0.14420
  Regression -> MSE: 0.000400, MAE: 0.016056, R²: -0.0431
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11875 | val 0.16237
  Epoch 020 - train 0.11428 | val 0.16262
  Epoch 021 - train 0.11442 | val 0.16263
  Regression -> MSE: 0.000245, MAE: 0.011630, R²: -0.0140
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11937 | val 0.17467
  Epoch 020 - train 0.12074 | val 0.17655
  Epoch 021 - train 0.11402 | val 0.17627
  Regression -> MSE: 0.000328, MAE: 0.013634, R²: -0.0555
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13168 | val 0.14451
  Epoch 020 - train 0.12594 | val 0.14385
  Epoch 021 - train 0.12311 | val 0.14360
  Regression -> MSE: 0.000683, MAE: 0.019599, R²: -0.0091
  Directional -> Accuracy: 0.5172, MCC: 0.1325, F1: 0.6744

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12065 | val 0.14856
  Epoch 020 - train 0.11908 | val 0.15752
  Epoch 021 - train 0.11730 | val 0.15593
  Regression -> MSE: 0.000139, MAE: 0.009218, R²: -0.0031
  Directional -> Accuracy: 0.3953, MCC: -0.1987, F1: 0.5517

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11397 | val 0.17246
  Epoch 020 - train 0.11568 | val 0.16971
  Epoch 021 - train 0.11551 | val 0.16987
  Regression -> MSE: 0.000225, MAE: 0.010732, R²: -0.0013
  Directional -> Accuracy: 0.4918, MCC: -0.0549, F1: 0.6437

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11865 | val 0.24813
  Epoch 020 - train 0.12300 | val 0.24819
  Epoch 021 - train 0.11754 | val 0.24791
  Regression -> MSE: 0.000362, MAE: 0.016137, R²: -0.0002
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13189 | val 0.14797
  Epoch 020 - train 0.12444 | val 0.14870
  Epoch 021 - train 0.12438 | val 0.14937
  Regression -> MSE: 0.000108, MAE: 0.007941, R²: -0.0007
  Directional -> Accuracy: 0.6000, MCC: 0.2683, F1: 0.7308

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12270 | val 0.22977
  Epoch 020 - train 0.12126 | val 0.23076
  Epoch 021 - train 0.11593 | val 0.22995
  Regression -> MSE: 0.000157, MAE: 0.009655, R²: -0.0099
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11881 | val 0.13142
  Epoch 020 - train 0.12158 | val 0.13418
  Epoch 021 - train 0.12268 | val 0.13434
  Regression -> MSE: 0.000283, MAE: 0.013482, R²: -0.0402
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11250 | val 0.15999
  Epoch 020 - train 0.10354 | val 0.15925
  Epoch 029 - train 0.10377 | val 0.15875
  Regression -> MSE: 0.000310, MAE: 0.014488, R²: -1.0723
  Directional -> Accuracy: 0.5231, MCC: 0.1873, F1: 0.3922

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12568 | val 0.17497
  Epoch 020 - train 0.12003 | val 0.17681
  Epoch 021 - train 0.12308 | val 0.17681
  Regression -> MSE: 0.000242, MAE: 0.011111, R²: -0.0682
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11993 | val 0.16479
  Epoch 020 - train 0.12323 | val 0.16639
  Epoch 021 - train 0.12238 | val 0.16606
  Regression -> MSE: 0.000145, MAE: 0.008476, R²: -0.0142
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11410 | val 0.14327
  Epoch 020 - train 0.11367 | val 0.14673
  Epoch 021 - train 0.11177 | val 0.14635
  Regression -> MSE: 0.000167, MAE: 0.010314, R²: -0.0117
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12905 | val 0.14167
  Epoch 020 - train 0.12718 | val 0.14251
  Epoch 030 - train 0.12769 | val 0.14323
  Regression -> MSE: 0.000087, MAE: 0.007128, R²: -0.0174
  Directional -> Accuracy: 0.5517, MCC: 0.1780, F1: 0.4800

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11673 | val 0.16998
  Epoch 020 - train 0.12106 | val 0.16883
  Epoch 021 - train 0.12011 | val 0.16897
  Regression -> MSE: 0.000213, MAE: 0.011019, R²: -0.0060
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11352 | val 0.10691
  Epoch 020 - train 0.11195 | val 0.10498
  Epoch 030 - train 0.10431 | val 0.10381
  Regression -> MSE: 0.000100, MAE: 0.008196, R²: -0.0817
  Directional -> Accuracy: 0.5179, MCC: 0.1373, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11504 | val 0.10063
  Epoch 020 - train 0.11640 | val 0.10125
  Epoch 021 - train 0.11878 | val 0.10111
  Regression -> MSE: 0.000114, MAE: 0.009151, R²: -0.1043
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12534 | val 0.14673
  Epoch 020 - train 0.12489 | val 0.15179
  Epoch 021 - train 0.12187 | val 0.15313
  Regression -> MSE: 0.000238, MAE: 0.012800, R²: -0.0303
  Directional -> Accuracy: 0.3721, MCC: -0.2024, F1: 0.2286

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12045 | val 0.16821
  Epoch 020 - train 0.12372 | val 0.16728
  Epoch 021 - train 0.11936 | val 0.16722
  Regression -> MSE: 0.000179, MAE: 0.008017, R²: -0.0735
  Directional -> Accuracy: 0.4912, MCC: -0.0681, F1: 0.5915

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12424 | val 0.10324
  Epoch 020 - train 0.12582 | val 0.10749
  Epoch 021 - train 0.11732 | val 0.10862
  Regression -> MSE: 0.000236, MAE: 0.011854, R²: 0.0008
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11882 | val 0.19364
  Epoch 020 - train 0.11994 | val 0.19397
  Epoch 021 - train 0.12115 | val 0.19326
  Regression -> MSE: 0.000232, MAE: 0.009958, R²: -0.0084
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13054 | val 0.15731
  Epoch 020 - train 0.11874 | val 0.15983
  Epoch 021 - train 0.12988 | val 0.15967
  Regression -> MSE: 0.000142, MAE: 0.008402, R²: -0.0508
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11926 | val 0.15649
  Epoch 020 - train 0.12655 | val 0.15630
  Epoch 021 - train 0.12651 | val 0.15650
  Regression -> MSE: 0.000189, MAE: 0.010360, R²: -0.0014
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11189 | val 0.16147
  Epoch 020 - train 0.11008 | val 0.15718
  Epoch 021 - train 0.11679 | val 0.15756
  Regression -> MSE: 0.000261, MAE: 0.010593, R²: 0.0043
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10879 | val 0.10143
  Epoch 020 - train 0.11244 | val 0.09805
  Epoch 030 - train 0.10855 | val 0.10293
  Regression -> MSE: 0.000161, MAE: 0.010260, R²: 0.0343
  Directional -> Accuracy: 0.5263, MCC: 0.0778, F1: 0.6538

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11059 | val 0.13159
  Epoch 020 - train 0.11411 | val 0.13252
  Epoch 021 - train 0.11336 | val 0.13274
  Regression -> MSE: 0.000184, MAE: 0.010406, R²: -0.0226
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11121 | val 0.11929
  Epoch 020 - train 0.11142 | val 0.12073
  Epoch 021 - train 0.11277 | val 0.12074
  Regression -> MSE: 0.000345, MAE: 0.012001, R²: -0.0079
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13196 | val 0.08369
  Epoch 020 - train 0.12991 | val 0.08761
  Epoch 021 - train 0.13232 | val 0.08686
  Regression -> MSE: 0.000113, MAE: 0.008342, R²: -0.0744
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11953 | val 0.17251
  Epoch 020 - train 0.11822 | val 0.17539
  Epoch 021 - train 0.11805 | val 0.17513
  Regression -> MSE: 0.000218, MAE: 0.011259, R²: 0.0033
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12514 | val 0.22490
  Epoch 020 - train 0.12466 | val 0.23007
  Epoch 021 - train 0.12719 | val 0.22957
  Regression -> MSE: 0.000090, MAE: 0.007425, R²: -0.1610
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12841 | val 0.09266
  Epoch 020 - train 0.11854 | val 0.09091
  Epoch 030 - train 0.11261 | val 0.09113
  Regression -> MSE: 0.000307, MAE: 0.013660, R²: 0.0035
  Directional -> Accuracy: 0.4490, MCC: -0.0782, F1: 0.4000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12772 | val 0.07724
  Epoch 020 - train 0.13559 | val 0.08107
  Epoch 021 - train 0.13218 | val 0.08102
  Regression -> MSE: 0.000252, MAE: 0.011450, R²: -0.0331
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11362 | val 0.14422
  Epoch 020 - train 0.11612 | val 0.14597
  Epoch 021 - train 0.10893 | val 0.14623
  Regression -> MSE: 0.000085, MAE: 0.007047, R²: -0.0484
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12670 | val 0.14267
  Epoch 020 - train 0.12010 | val 0.15138
  Epoch 029 - train 0.12592 | val 0.15349
  Regression -> MSE: 0.000340, MAE: 0.015151, R²: -0.1094
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12271 | val 0.13879
  Epoch 020 - train 0.11509 | val 0.14568
  Epoch 021 - train 0.11780 | val 0.14584
  Regression -> MSE: 0.000098, MAE: 0.007189, R²: 0.0005
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13277 | val 0.15244
  Epoch 020 - train 0.13577 | val 0.15426
  Epoch 021 - train 0.13081 | val 0.15414
  Regression -> MSE: 0.000172, MAE: 0.009553, R²: -0.0005
  Directional -> Accuracy: 0.5510, MCC: 0.0167, F1: 0.3529

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11553 | val 0.14618
  Epoch 020 - train 0.11126 | val 0.14515
  Epoch 021 - train 0.11772 | val 0.14398
  Regression -> MSE: 0.000225, MAE: 0.011848, R²: -0.0112
  Directional -> Accuracy: 0.3929, MCC: -0.3116, F1: 0.5405

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12386 | val 0.14073
  Epoch 020 - train 0.11730 | val 0.14184
  Epoch 021 - train 0.11502 | val 0.14329
  Regression -> MSE: 0.000096, MAE: 0.007913, R²: -0.0422

[I 2026-02-24 03:18:55,875] Trial 134 finished with value: -0.01154242841193433 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 1.4241145652224476e-05, 'weight_decay': 2.839817930867416e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.18312224534933075, 'early_stopping_min_delta': 0.0048576415678434764}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.12786 | val 0.17615
  Regression -> MSE: 0.000250, MAE: 0.012428, R²: -0.0531
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.19330 | val 0.29233
  Epoch 020 - train 0.19058 | val 0.29422
  Epoch 021 - train 0.19003 | val 0.29208
  Regression -> MSE: 0.000262, MAE: 0.013055, R²: -0.0574
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.17915 | val 0.17560
  Epoch 020 - train 0.17452 | val 0.17778
  Epoch 021 - train 0.17593 | val 0.17798
  Regression -> MSE: 0.000687, MAE: 0.019373, R²: -0.0032
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.19454 | val 0.30514
  Epoch 020 - train 0.18152 | val 0.30343
  Epoch 021 - train 0.18690 | val 0.30353
  Regression -> MSE: 0.000312, MAE: 0.014405, R²: -0.0070
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15345 | val 0.15294
  Epoch 020 - train 0.15589 | val 0.15807
  Epoch 021 - train 0.15224 | val 0.15759
  Regression -> MSE: 0.000352, MAE: 0.014641, R²: -0.0089
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.18719 | val 0.18651
  Epoch 020 - train 0.17960 | val 0.18708
  Epoch 021 - train 0.18058 | val 0.18697
  Regression -> MSE: 0.000205, MAE: 0.010071, R²: -0.0046
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.18797 | val 0.35437
  Epoch 020 - train 0.18862 | val 0.36537
  Epoch 021 - train 0.18801 | val 0.36547
  Regression -> MSE: 0.000559, MAE: 0.018175, R²: -0.0078
  Directional -> Accuracy: 0.5319, MCC: 0.0764, F1: 0.2143

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.19847 | val 0.25382
  Epoch 020 - train 0.18821 | val 0.25380
  Epoch 021 - train 0.18829 | val 0.25316
  Regression -> MSE: 0.000249, MAE: 0.012385, R²: -0.0125
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.18909 | val 0.25559
  Epoch 020 - train 0.18808 | val 0.25305
  Epoch 021 - train 0.18495 | val 0.25316
  Regression -> MSE: 0.000641, MAE: 0.020120, R²: -0.0733
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.17489 | val 0.21929
  Epoch 020 - train 0.17298 | val 0.22148
  Epoch 021 - train 0.16146 | val 0.22191
  Regression -> MSE: 0.000399, MAE: 0.016035, R²: -0.0400
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.18854 | val 0.23362
  Epoch 020 - train 0.18417 | val 0.23282
  Epoch 021 - train 0.17828 | val 0.23282
  Regression -> MSE: 0.000241, MAE: 0.011707, R²: 0.0007
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.17337 | val 0.28375
  Epoch 020 - train 0.17281 | val 0.28651
  Epoch 021 - train 0.17023 | val 0.28657
  Regression -> MSE: 0.000310, MAE: 0.013761, R²: 0.0020
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.19797 | val 0.21177
  Epoch 020 - train 0.19591 | val 0.21361
  Epoch 021 - train 0.19148 | val 0.21362
  Regression -> MSE: 0.000682, MAE: 0.019651, R²: -0.0072
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.19383 | val 0.18580
  Epoch 020 - train 0.19242 | val 0.19206
  Epoch 030 - train 0.18718 | val 0.19272
  Regression -> MSE: 0.000144, MAE: 0.009341, R²: -0.0423
  Directional -> Accuracy: 0.4186, MCC: -0.1513, F1: 0.4186

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.16649 | val 0.24725
  Epoch 020 - train 0.16436 | val 0.24629
  Epoch 021 - train 0.16521 | val 0.24630
  Regression -> MSE: 0.000225, MAE: 0.010736, R²: 0.0003
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.17442 | val 0.38540
  Epoch 020 - train 0.17814 | val 0.39009
  Epoch 021 - train 0.17003 | val 0.38985
  Regression -> MSE: 0.000367, MAE: 0.015950, R²: -0.0121
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.19145 | val 0.19589
  Epoch 020 - train 0.19194 | val 0.19491
  Epoch 021 - train 0.19314 | val 0.19539
  Regression -> MSE: 0.000109, MAE: 0.008163, R²: -0.0150
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.18231 | val 0.34645
  Epoch 020 - train 0.17630 | val 0.36099
  Epoch 021 - train 0.17569 | val 0.35989
  Regression -> MSE: 0.000157, MAE: 0.009625, R²: -0.0044
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.18732 | val 0.18628
  Epoch 020 - train 0.18979 | val 0.18639
  Epoch 021 - train 0.19044 | val 0.18653
  Regression -> MSE: 0.000281, MAE: 0.013467, R²: -0.0331
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.17420 | val 0.25499
  Epoch 020 - train 0.16432 | val 0.25188
  Epoch 021 - train 0.16431 | val 0.25241
  Regression -> MSE: 0.000157, MAE: 0.008812, R²: -0.0507
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.20316 | val 0.29011
  Epoch 020 - train 0.20214 | val 0.28974
  Epoch 021 - train 0.20037 | val 0.29064
  Regression -> MSE: 0.000226, MAE: 0.010900, R²: -0.0004
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.18779 | val 0.23708
  Epoch 020 - train 0.18154 | val 0.24698
  Epoch 021 - train 0.18229 | val 0.24742
  Regression -> MSE: 0.000146, MAE: 0.008489, R²: -0.0173
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.18313 | val 0.23997
  Epoch 020 - train 0.18163 | val 0.24328
  Epoch 021 - train 0.18257 | val 0.24274
  Regression -> MSE: 0.000165, MAE: 0.010309, R²: -0.0013
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.19768 | val 0.21515
  Epoch 020 - train 0.19561 | val 0.21344
  Epoch 021 - train 0.19287 | val 0.21334
  Regression -> MSE: 0.000086, MAE: 0.007098, R²: -0.0090
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.18519 | val 0.22271
  Epoch 020 - train 0.18378 | val 0.21923
  Epoch 030 - train 0.18500 | val 0.21839
  Regression -> MSE: 0.000235, MAE: 0.012384, R²: -0.1106
  Directional -> Accuracy: 0.4545, MCC: -0.0861, F1: 0.6170

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.17263 | val 0.16591
  Epoch 020 - train 0.17359 | val 0.16759
  Epoch 021 - train 0.17126 | val 0.16762
  Regression -> MSE: 0.000101, MAE: 0.008224, R²: -0.0944
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18893 | val 0.14424
  Epoch 020 - train 0.18443 | val 0.14376
  Epoch 021 - train 0.18549 | val 0.14374
  Regression -> MSE: 0.000109, MAE: 0.008986, R²: -0.0538
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.20336 | val 0.17189
  Epoch 020 - train 0.18983 | val 0.17436
  Epoch 021 - train 0.19857 | val 0.17493
  Regression -> MSE: 0.000233, MAE: 0.012611, R²: -0.0069
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.18781 | val 0.21946
  Epoch 020 - train 0.18324 | val 0.22025
  Epoch 021 - train 0.18553 | val 0.21993
  Regression -> MSE: 0.000190, MAE: 0.008192, R²: -0.1408
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.20671 | val 0.15801
  Epoch 020 - train 0.19013 | val 0.15527
  Epoch 021 - train 0.19224 | val 0.15597
  Regression -> MSE: 0.000238, MAE: 0.011923, R²: -0.0053
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.19865 | val 0.31539
  Epoch 020 - train 0.19305 | val 0.32713
  Epoch 021 - train 0.19910 | val 0.32872
  Regression -> MSE: 0.000236, MAE: 0.010227, R²: -0.0239
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.19059 | val 0.22232
  Epoch 020 - train 0.18496 | val 0.21611
  Epoch 030 - train 0.18940 | val 0.21626
  Regression -> MSE: 0.000132, MAE: 0.008328, R²: 0.0225
  Directional -> Accuracy: 0.5581, MCC: 0.1107, F1: 0.6984

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.18964 | val 0.23745
  Epoch 020 - train 0.18297 | val 0.24534
  Epoch 021 - train 0.19046 | val 0.24548
  Regression -> MSE: 0.000197, MAE: 0.010623, R²: -0.0488
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.16045 | val 0.20132
  Epoch 020 - train 0.15885 | val 0.20049
  Epoch 027 - train 0.15983 | val 0.20016
  Regression -> MSE: 0.000263, MAE: 0.010494, R²: -0.0058
  Directional -> Accuracy: 0.5068, MCC: 0.0329, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.17813 | val 0.15340
  Epoch 020 - train 0.17325 | val 0.15492
  Epoch 021 - train 0.17393 | val 0.15524
  Regression -> MSE: 0.000172, MAE: 0.010413, R²: -0.0327
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.17070 | val 0.19553
  Epoch 020 - train 0.16073 | val 0.19891
  Epoch 021 - train 0.16629 | val 0.19931
  Regression -> MSE: 0.000183, MAE: 0.010447, R²: -0.0185
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.18896 | val 0.17099
  Epoch 020 - train 0.17514 | val 0.17365
  Epoch 021 - train 0.17728 | val 0.17351
  Regression -> MSE: 0.000342, MAE: 0.011796, R²: 0.0024
  Directional -> Accuracy: 0.5672, MCC: 0.2006, F1: 0.5085

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.20121 | val 0.11798
  Epoch 020 - train 0.19205 | val 0.12325
  Epoch 021 - train 0.19327 | val 0.12377
  Regression -> MSE: 0.000125, MAE: 0.008440, R²: -0.1879
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.18685 | val 0.24753
  Epoch 020 - train 0.18062 | val 0.24689
  Epoch 021 - train 0.18565 | val 0.24686
  Regression -> MSE: 0.000219, MAE: 0.011308, R²: -0.0009
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.18086 | val 0.32990
  Epoch 020 - train 0.18220 | val 0.33881
  Epoch 021 - train 0.18320 | val 0.33873
  Regression -> MSE: 0.000082, MAE: 0.007070, R²: -0.0576
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.19002 | val 0.17415
  Epoch 020 - train 0.18379 | val 0.19008
  Epoch 021 - train 0.19221 | val 0.19142
  Regression -> MSE: 0.000355, MAE: 0.015829, R²: -0.1544
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.19329 | val 0.11253
  Epoch 020 - train 0.19677 | val 0.10474
  Epoch 030 - train 0.19539 | val 0.10583
  Regression -> MSE: 0.000258, MAE: 0.011479, R²: -0.0563
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.17435 | val 0.23165
  Epoch 020 - train 0.17416 | val 0.23159
  Epoch 021 - train 0.17238 | val 0.23146
  Regression -> MSE: 0.000083, MAE: 0.007036, R²: -0.0282
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.19099 | val 0.23099
  Epoch 020 - train 0.18989 | val 0.22949
  Epoch 021 - train 0.19247 | val 0.22953
  Regression -> MSE: 0.000307, MAE: 0.014483, R²: -0.0006
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.18557 | val 0.19319
  Epoch 020 - train 0.18396 | val 0.19313
  Epoch 021 - train 0.17463 | val 0.19311
  Regression -> MSE: 0.000098, MAE: 0.007385, R²: -0.0019
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.18711 | val 0.21901
  Epoch 020 - train 0.19637 | val 0.21248
  Epoch 030 - train 0.19318 | val 0.21346
  Regression -> MSE: 0.000176, MAE: 0.009420, R²: -0.0269
  Directional -> Accuracy: 0.6327, MCC: 0.1814, F1: 0.1000

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 03:22:01,584] Trial 135 finished with value: -0.011489496966230533 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.30000000000000004, 'batch_size': 32, 'learning_rate': 4.427094848505083e-06, 'weight_decay': 2.549042850546795e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.29554133345364153, 'early_stopping_min_delta': 0.006584709049090897}. Best is trial 44 with value: -0.011362814469631832.

  Regression -> MSE: 0.000243, MAE: 0.012326, R²: -0.0231
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.16176 | val 0.18987
  Epoch 020 - train 0.16409 | val 0.18925
  Epoch 021 - train 0.16557 | val 0.18952
  Regression -> MSE: 0.000248, MAE: 0.012546, R²: -0.0011
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16995 | val 0.14380
  Epoch 020 - train 0.17065 | val 0.15801
  Epoch 021 - train 0.16808 | val 0.15811
  Regression -> MSE: 0.000717, MAE: 0.019905, R²: -0.0468
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.18118 | val 0.25510
  Epoch 020 - train 0.17925 | val 0.27267
  Epoch 021 - train 0.18338 | val 0.27306
  Regression -> MSE: 0.000313, MAE: 0.014523, R²: -0.0077
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13715 | val 0.15588
  Epoch 020 - train 0.13748 | val 0.15407
  Epoch 021 - train 0.14158 | val 0.15616
  Regression -> MSE: 0.000350, MAE: 0.014618, R²: -0.0027
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16616 | val 0.14896
  Epoch 020 - train 0.17049 | val 0.14756
  Epoch 030 - train 0.16703 | val 0.14686
  Regression -> MSE: 0.000218, MAE: 0.010522, R²: -0.0697
  Directional -> Accuracy: 0.5686, MCC: 0.1775, F1: 0.4762

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15317 | val 0.28112
  Epoch 020 - train 0.15029 | val 0.27325
  Epoch 030 - train 0.15606 | val 0.27296
  Regression -> MSE: 0.000556, MAE: 0.018331, R²: -0.0020
  Directional -> Accuracy: 0.4894, MCC: -0.0200, F1: 0.5000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16289 | val 0.19149
  Epoch 020 - train 0.15927 | val 0.19226
  Epoch 021 - train 0.16243 | val 0.19222
  Regression -> MSE: 0.000254, MAE: 0.012022, R²: -0.0362
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.17888 | val 0.16829
  Epoch 020 - train 0.17646 | val 0.16420
  Epoch 030 - train 0.15912 | val 0.17078
  Regression -> MSE: 0.000600, MAE: 0.019138, R²: -0.0038
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.16394 | val 0.19158
  Epoch 020 - train 0.14837 | val 0.19997
  Epoch 021 - train 0.15971 | val 0.19966
  Regression -> MSE: 0.000385, MAE: 0.016147, R²: -0.0025
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16114 | val 0.19362
  Epoch 020 - train 0.16674 | val 0.19428
  Epoch 021 - train 0.15804 | val 0.19451
  Regression -> MSE: 0.000242, MAE: 0.011818, R²: -0.0006
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15413 | val 0.20527
  Epoch 020 - train 0.15087 | val 0.20131
  Epoch 030 - train 0.15078 | val 0.20108
  Regression -> MSE: 0.000344, MAE: 0.014162, R²: -0.1080
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15587 | val 0.18827
  Epoch 020 - train 0.16302 | val 0.19657
  Epoch 021 - train 0.17165 | val 0.19638
  Regression -> MSE: 0.000676, MAE: 0.019446, R²: 0.0018
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16694 | val 0.16753
  Epoch 020 - train 0.17019 | val 0.17161
  Epoch 021 - train 0.16861 | val 0.17150
  Regression -> MSE: 0.000139, MAE: 0.009017, R²: -0.0090
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15410 | val 0.20442
  Epoch 020 - train 0.15652 | val 0.20985
  Epoch 021 - train 0.15826 | val 0.20957
  Regression -> MSE: 0.000226, MAE: 0.010707, R²: -0.0049
  Directional -> Accuracy: 0.5082, MCC: 0.0064, F1: 0.6429

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16480 | val 0.30983
  Epoch 020 - train 0.15976 | val 0.31671
  Epoch 021 - train 0.15699 | val 0.31591
  Regression -> MSE: 0.000363, MAE: 0.016194, R²: -0.0013
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.17390 | val 0.15531
  Epoch 020 - train 0.17374 | val 0.15614
  Epoch 021 - train 0.17094 | val 0.15613
  Regression -> MSE: 0.000109, MAE: 0.008166, R²: -0.0148
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15328 | val 0.25267
  Epoch 020 - train 0.15729 | val 0.25924
  Epoch 021 - train 0.15158 | val 0.25969
  Regression -> MSE: 0.000155, MAE: 0.009569, R²: 0.0044
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16756 | val 0.14828
  Epoch 020 - train 0.16965 | val 0.14835
  Epoch 021 - train 0.17392 | val 0.14788
  Regression -> MSE: 0.000284, MAE: 0.013580, R²: -0.0427
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.15117 | val 0.19268
  Epoch 020 - train 0.14948 | val 0.19241
  Epoch 021 - train 0.14628 | val 0.19257
  Regression -> MSE: 0.000163, MAE: 0.009036, R²: -0.0926
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16903 | val 0.21870
  Epoch 020 - train 0.16796 | val 0.21888
  Epoch 021 - train 0.17361 | val 0.21847
  Regression -> MSE: 0.000240, MAE: 0.011058, R²: -0.0622
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16175 | val 0.20234
  Epoch 020 - train 0.17511 | val 0.22751
  Epoch 021 - train 0.16684 | val 0.22770
  Regression -> MSE: 0.000155, MAE: 0.008888, R²: -0.0790
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.16652 | val 0.18362
  Epoch 020 - train 0.15328 | val 0.18494
  Epoch 021 - train 0.15289 | val 0.18543
  Regression -> MSE: 0.000167, MAE: 0.010291, R²: -0.0118
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16243 | val 0.18338
  Epoch 020 - train 0.16270 | val 0.18805
  Epoch 021 - train 0.16725 | val 0.18792
  Regression -> MSE: 0.000087, MAE: 0.007140, R²: -0.0196
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15645 | val 0.18853
  Epoch 020 - train 0.15007 | val 0.18663
  Epoch 021 - train 0.15692 | val 0.18712
  Regression -> MSE: 0.000212, MAE: 0.011145, R²: -0.0018
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14825 | val 0.12652
  Epoch 020 - train 0.14773 | val 0.12555
  Epoch 029 - train 0.14191 | val 0.12570
  Regression -> MSE: 0.000102, MAE: 0.008259, R²: -0.1067
  Directional -> Accuracy: 0.5179, MCC: 0.1373, F1: 0.3415

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16937 | val 0.12156
  Epoch 020 - train 0.17737 | val 0.14395
  Epoch 021 - train 0.16717 | val 0.14645
  Regression -> MSE: 0.000108, MAE: 0.008959, R²: -0.0460
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.17814 | val 0.14418
  Epoch 020 - train 0.16969 | val 0.16327
  Epoch 021 - train 0.18464 | val 0.16282
  Regression -> MSE: 0.000234, MAE: 0.012643, R²: -0.0112
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14773 | val 0.19011
  Epoch 020 - train 0.15311 | val 0.19613
  Epoch 021 - train 0.15125 | val 0.19564
  Regression -> MSE: 0.000177, MAE: 0.007898, R²: -0.0640
  Directional -> Accuracy: 0.5439, MCC: 0.0820, F1: 0.5806

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16398 | val 0.12733
  Epoch 020 - train 0.17015 | val 0.13079
  Epoch 021 - train 0.15965 | val 0.13142
  Regression -> MSE: 0.000236, MAE: 0.011856, R²: 0.0009
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.17770 | val 0.23442
  Epoch 020 - train 0.17209 | val 0.23239
  Epoch 021 - train 0.15705 | val 0.23264
  Regression -> MSE: 0.000231, MAE: 0.009875, R²: -0.0012
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16341 | val 0.16874
  Epoch 020 - train 0.17220 | val 0.20931
  Epoch 021 - train 0.17246 | val 0.21156
  Regression -> MSE: 0.000136, MAE: 0.008184, R²: -0.0061
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15633 | val 0.19419
  Epoch 020 - train 0.15499 | val 0.19997
  Epoch 021 - train 0.15275 | val 0.20007
  Regression -> MSE: 0.000198, MAE: 0.010636, R²: -0.0491
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15536 | val 0.19390
  Epoch 020 - train 0.14426 | val 0.19359
  Epoch 021 - train 0.15087 | val 0.19441
  Regression -> MSE: 0.000262, MAE: 0.010570, R²: -0.0008
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14355 | val 0.12773
  Epoch 020 - train 0.15646 | val 0.14336
  Epoch 021 - train 0.15383 | val 0.14713
  Regression -> MSE: 0.000168, MAE: 0.010375, R²: -0.0052
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14921 | val 0.15008
  Epoch 020 - train 0.14092 | val 0.15109
  Epoch 021 - train 0.16169 | val 0.15125
  Regression -> MSE: 0.000182, MAE: 0.010386, R²: -0.0092
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14349 | val 0.14169
  Epoch 020 - train 0.14581 | val 0.14319
  Epoch 021 - train 0.14755 | val 0.14369
  Regression -> MSE: 0.000343, MAE: 0.011685, R²: -0.0001
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.17310 | val 0.09783
  Epoch 020 - train 0.17646 | val 0.12255
  Epoch 021 - train 0.17475 | val 0.12275
  Regression -> MSE: 0.000112, MAE: 0.008306, R²: -0.0670
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16732 | val 0.22216
  Epoch 020 - train 0.16131 | val 0.22939
  Epoch 021 - train 0.17221 | val 0.22930
  Regression -> MSE: 0.000219, MAE: 0.011320, R²: -0.0025
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.17219 | val 0.25926
  Epoch 020 - train 0.16244 | val 0.26343
  Epoch 021 - train 0.15925 | val 0.26312
  Regression -> MSE: 0.000084, MAE: 0.007176, R²: -0.0877
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14687 | val 0.13750
  Epoch 020 - train 0.16113 | val 0.15463
  Epoch 021 - train 0.15845 | val 0.15741
  Regression -> MSE: 0.000348, MAE: 0.015597, R²: -0.1298
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.16087 | val 0.09144
  Epoch 020 - train 0.16475 | val 0.09939
  Epoch 021 - train 0.17091 | val 0.10071
  Regression -> MSE: 0.000250, MAE: 0.011504, R²: -0.0254
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15888 | val 0.17751
  Epoch 020 - train 0.15968 | val 0.17721
  Epoch 021 - train 0.15902 | val 0.17752
  Regression -> MSE: 0.000082, MAE: 0.007052, R²: -0.0108
  Directional -> Accuracy: 0.4667, MCC: -0.1182, F1: 0.1304

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17272 | val 0.20780
  Epoch 020 - train 0.17735 | val 0.36897
  Epoch 021 - train 0.18898 | val 0.37553
  Regression -> MSE: 0.000306, MAE: 0.014476, R²: 0.0032
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16416 | val 0.15488
  Epoch 020 - train 0.15614 | val 0.15099
  Epoch 021 - train 0.16467 | val 0.15048
  Regression -> MSE: 0.000099, MAE: 0.007412, R²: -0.0039
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16748 | val 0.18524
  Epoch 020 - train 0.15986 | val 0.20039
  Epoch 021 - train 0.17174 | val 0.20115
  Regression -> MSE: 0.000172, MAE: 0.009522, R²: -0.0025
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14921 | val 0.16543
  Epoch 020 - train 0.15263 | val 0.16691
  Epoch 021 - train 0.14329 | val 0.16651
  Regression -> MSE: 0.000224, MAE: 0.011788, R²: -0.0036
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.15589 | val 0.17759
  Epoch 020 - train 0.15585 | val 0.18490
  Epoch 021 - train 0.15724 | val 0.18558
  Regression -> MSE: 0.000093, MAE: 0.007686, R²: -0.0086
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429


[I 2026-02-24 03:24:09,235] Trial 136 finished with value: -0.011459285865800431 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 2.994314858492116e-06, 'weight_decay': 6.311289102172755e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.22990223839306395, 'early_stopping_min_delta': 0.00779385855812119}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.17206 | val 0.22602
  Epoch 021 - train 0.16595 | val 0.22637
  Regression -> MSE: 0.000236, MAE: 0.012430, R²: 0.0030
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10604 | val 0.15079
  Epoch 020 - train 0.10766 | val 0.15041
  Epoch 021 - train 0.10628 | val 0.14925
  Regression -> MSE: 0.000262, MAE: 0.013038, R²: -0.0599
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10955 | val 0.11844
  Epoch 020 - train 0.10994 | val 0.12090
  Epoch 021 - train 0.10604 | val 0.12166
  Regression -> MSE: 0.000705, MAE: 0.019683, R²: -0.0292
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11272 | val 0.18840
  Epoch 020 - train 0.11011 | val 0.19139
  Epoch 021 - train 0.11326 | val 0.19126
  Regression -> MSE: 0.000315, MAE: 0.014488, R²: -0.0162
  Directional -> Accuracy: 0.4894, MCC: -0.0200, F1: 0.5000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09260 | val 0.14376
  Epoch 020 - train 0.08979 | val 0.12549
  Epoch 021 - train 0.09056 | val 0.12839
  Regression -> MSE: 0.000351, MAE: 0.014624, R²: -0.0056
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10984 | val 0.11277
  Epoch 020 - train 0.10920 | val 0.11106
  Epoch 021 - train 0.11034 | val 0.11145
  Regression -> MSE: 0.000210, MAE: 0.010635, R²: -0.0324
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10149 | val 0.19509
  Epoch 020 - train 0.09874 | val 0.19339
  Epoch 021 - train 0.10038 | val 0.19315
  Regression -> MSE: 0.000595, MAE: 0.018901, R²: -0.0726
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10836 | val 0.13784
  Epoch 020 - train 0.10678 | val 0.13557
  Epoch 021 - train 0.10996 | val 0.13509
  Regression -> MSE: 0.000244, MAE: 0.011881, R²: 0.0074
  Directional -> Accuracy: 0.5362, MCC: -0.0075, F1: 0.3333

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10839 | val 0.18698
  Epoch 020 - train 0.10172 | val 0.22915
  Epoch 021 - train 0.10700 | val 0.22966
  Regression -> MSE: 0.000676, MAE: 0.020609, R²: -0.1315
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10168 | val 0.13160
  Epoch 020 - train 0.10416 | val 0.13279
  Epoch 021 - train 0.09954 | val 0.13263
  Regression -> MSE: 0.000392, MAE: 0.016080, R²: -0.0220
  Directional -> Accuracy: 0.4898, MCC: 0.1193, F1: 0.6269

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10938 | val 0.13768
  Epoch 020 - train 0.10818 | val 0.13637
  Epoch 021 - train 0.10732 | val 0.13655
  Regression -> MSE: 0.000243, MAE: 0.012126, R²: -0.0059
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10209 | val 0.14738
  Epoch 020 - train 0.10049 | val 0.14772
  Epoch 021 - train 0.09711 | val 0.14770
  Regression -> MSE: 0.000321, MAE: 0.013623, R²: -0.0316
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11200 | val 0.14414
  Epoch 020 - train 0.10933 | val 0.14622
  Epoch 021 - train 0.10867 | val 0.14632
  Regression -> MSE: 0.000676, MAE: 0.019480, R²: 0.0017
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11162 | val 0.13423
  Epoch 020 - train 0.10969 | val 0.14881
  Epoch 021 - train 0.11149 | val 0.14887
  Regression -> MSE: 0.000139, MAE: 0.009186, R²: -0.0078
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10113 | val 0.13521
  Epoch 020 - train 0.10475 | val 0.13468
  Epoch 021 - train 0.10743 | val 0.13458
  Regression -> MSE: 0.000230, MAE: 0.010839, R²: -0.0212
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10889 | val 0.28577
  Epoch 020 - train 0.10603 | val 0.28904
  Epoch 021 - train 0.10756 | val 0.28926
  Regression -> MSE: 0.000366, MAE: 0.016332, R²: -0.0111
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10697 | val 0.11765
  Epoch 020 - train 0.10833 | val 0.11662
  Epoch 021 - train 0.10845 | val 0.11719
  Regression -> MSE: 0.000107, MAE: 0.007992, R²: 0.0080
  Directional -> Accuracy: 0.4857, MCC: 0.1574, F1: 0.1000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10164 | val 0.18335
  Epoch 020 - train 0.10100 | val 0.18608
  Epoch 021 - train 0.10029 | val 0.18547
  Regression -> MSE: 0.000161, MAE: 0.010136, R²: -0.0297
  Directional -> Accuracy: 0.5593, MCC: 0.1647, F1: 0.5806

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11540 | val 0.16948
  Epoch 020 - train 0.11010 | val 0.16345
  Epoch 021 - train 0.11401 | val 0.16237
  Regression -> MSE: 0.000293, MAE: 0.013012, R²: -0.0762
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10107 | val 0.14031
  Epoch 020 - train 0.09547 | val 0.13940
  Epoch 021 - train 0.09840 | val 0.13950
  Regression -> MSE: 0.000156, MAE: 0.008815, R²: -0.0440
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10782 | val 0.16959
  Epoch 020 - train 0.10695 | val 0.16587
  Epoch 021 - train 0.10994 | val 0.16514
  Regression -> MSE: 0.000233, MAE: 0.010973, R²: -0.0293
  Directional -> Accuracy: 0.4533, MCC: -0.1732, F1: 0.5859

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11317 | val 0.13167
  Epoch 020 - train 0.10677 | val 0.13327
  Epoch 021 - train 0.10993 | val 0.13322
  Regression -> MSE: 0.000142, MAE: 0.008279, R²: 0.0059
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09848 | val 0.13390
  Epoch 020 - train 0.09822 | val 0.13411
  Epoch 021 - train 0.09935 | val 0.13348
  Regression -> MSE: 0.000171, MAE: 0.010258, R²: -0.0351
  Directional -> Accuracy: 0.4242, MCC: -0.1732, F1: 0.5366

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11209 | val 0.12804
  Epoch 020 - train 0.11245 | val 0.12712
  Epoch 021 - train 0.11126 | val 0.12732
  Regression -> MSE: 0.000087, MAE: 0.007152, R²: -0.0248
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10501 | val 0.13776
  Epoch 020 - train 0.10854 | val 0.13922
  Epoch 021 - train 0.10627 | val 0.14045
  Regression -> MSE: 0.000217, MAE: 0.011024, R²: -0.0248
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10052 | val 0.09320
  Epoch 020 - train 0.10058 | val 0.09200
  Epoch 021 - train 0.09928 | val 0.09223
  Regression -> MSE: 0.000092, MAE: 0.008045, R²: 0.0021
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11559 | val 0.09272
  Epoch 020 - train 0.11536 | val 0.10099
  Epoch 021 - train 0.11571 | val 0.10141
  Regression -> MSE: 0.000103, MAE: 0.008655, R²: -0.0034
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.0000

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10641 | val 0.10155
  Epoch 020 - train 0.10671 | val 0.10170
  Epoch 021 - train 0.10923 | val 0.10165
  Regression -> MSE: 0.000235, MAE: 0.012676, R²: -0.0167
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10774 | val 0.13254
  Epoch 020 - train 0.10904 | val 0.13248
  Epoch 021 - train 0.10684 | val 0.13237
  Regression -> MSE: 0.000168, MAE: 0.007827, R²: -0.0100
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10889 | val 0.09150
  Epoch 020 - train 0.10970 | val 0.09189
  Epoch 021 - train 0.10837 | val 0.09213
  Regression -> MSE: 0.000238, MAE: 0.011916, R²: -0.0080
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10933 | val 0.16777
  Epoch 020 - train 0.10667 | val 0.17241
  Epoch 021 - train 0.10670 | val 0.17243
  Regression -> MSE: 0.000232, MAE: 0.009979, R²: -0.0053
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11202 | val 0.12960
  Epoch 020 - train 0.10909 | val 0.14006
  Epoch 021 - train 0.10996 | val 0.13997
  Regression -> MSE: 0.000133, MAE: 0.008220, R²: 0.0179
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10966 | val 0.12828
  Epoch 020 - train 0.10611 | val 0.12814
  Epoch 029 - train 0.10688 | val 0.12854
  Regression -> MSE: 0.000298, MAE: 0.014030, R²: -0.5811
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09823 | val 0.12235
  Epoch 020 - train 0.09681 | val 0.12224
  Epoch 021 - train 0.09661 | val 0.12153
  Regression -> MSE: 0.000260, MAE: 0.010543, R²: 0.0078
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10777 | val 0.10328
  Epoch 020 - train 0.10110 | val 0.10939
  Epoch 021 - train 0.10333 | val 0.10872
  Regression -> MSE: 0.000171, MAE: 0.010394, R²: -0.0265
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09943 | val 0.12246
  Epoch 020 - train 0.09551 | val 0.12585
  Epoch 021 - train 0.09768 | val 0.12636
  Regression -> MSE: 0.000183, MAE: 0.010370, R²: -0.0157
  Directional -> Accuracy: 0.4545, MCC: -0.0807, F1: 0.5200

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10340 | val 0.10249
  Epoch 020 - train 0.10329 | val 0.10270
  Epoch 021 - train 0.10243 | val 0.10283
  Regression -> MSE: 0.000342, MAE: 0.011647, R²: 0.0033
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12543 | val 0.08330
  Epoch 020 - train 0.12527 | val 0.09083
  Epoch 021 - train 0.12650 | val 0.09170
  Regression -> MSE: 0.000109, MAE: 0.008432, R²: -0.0334
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10436 | val 0.15119
  Epoch 020 - train 0.10441 | val 0.15213
  Epoch 021 - train 0.10172 | val 0.15096
  Regression -> MSE: 0.000224, MAE: 0.011392, R²: -0.0226
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11016 | val 0.17784
  Epoch 020 - train 0.10684 | val 0.17725
  Epoch 021 - train 0.10753 | val 0.17731
  Regression -> MSE: 0.000084, MAE: 0.007143, R²: -0.0816
  Directional -> Accuracy: 0.5957, MCC: 0.1357, F1: 0.6780

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10837 | val 0.08709
  Epoch 020 - train 0.10496 | val 0.09403
  Epoch 021 - train 0.11013 | val 0.09429
  Regression -> MSE: 0.000309, MAE: 0.013763, R²: -0.0058
  Directional -> Accuracy: 0.5918, MCC: 0.0343, F1: 0.2857

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12113 | val 0.07196
  Epoch 020 - train 0.12311 | val 0.06996
  Epoch 021 - train 0.11808 | val 0.06976
  Regression -> MSE: 0.000267, MAE: 0.011536, R²: -0.0943
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10200 | val 0.13030
  Epoch 020 - train 0.10099 | val 0.13020
  Epoch 021 - train 0.09985 | val 0.13042
  Regression -> MSE: 0.000080, MAE: 0.007046, R²: 0.0095
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11082 | val 0.16708
  Epoch 020 - train 0.11140 | val 0.18077
  Epoch 021 - train 0.10759 | val 0.18164
  Regression -> MSE: 0.000319, MAE: 0.014575, R²: -0.0413
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11841 | val 0.13030
  Epoch 020 - train 0.11746 | val 0.12996
  Epoch 021 - train 0.11927 | val 0.12907
  Regression -> MSE: 0.000104, MAE: 0.007102, R²: -0.0626
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11829 | val 0.13092
  Epoch 020 - train 0.11723 | val 0.13458
  Epoch 021 - train 0.11680 | val 0.13428
  Regression -> MSE: 0.000173, MAE: 0.009494, R²: -0.0052
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10157 | val 0.11586
  Epoch 020 - train 0.09969 | val 0.11668
  Epoch 021 - train 0.10000 | val 0.11630
  Regression -> MSE: 0.000224, MAE: 0.011796, R²: -0.0051
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10994 | val 0.11648
  Epoch 020 - train 0.10944 | val 0.11412
  Epoch 021 - train 0.11010 | val 0.11353

[I 2026-02-24 03:26:00,704] Trial 137 finished with value: -0.011505075626119072 and parameters: {'feature_set': 'finbert', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 5.704455318942421e-06, 'weight_decay': 2.7316697667281576e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.15624201568175528, 'early_stopping_min_delta': 0.007516607768903574}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.10860 | val 0.17868
  Epoch 021 - train 0.10691 | val 0.17942
  Regression -> MSE: 0.000235, MAE: 0.012299, R²: 0.0089
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.40626 | val 0.47569
  Epoch 020 - train 0.39150 | val 0.47087
  Epoch 030 - train 0.39556 | val 0.46831
  Regression -> MSE: 0.000254, MAE: 0.012819, R²: -0.0271
  Directional -> Accuracy: 0.4026, MCC: -0.1944, F1: 0.3784

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.38578 | val 0.44027
  Epoch 020 - train 0.38534 | val 0.45063
  Epoch 021 - train 0.35703 | val 0.43851
  Regression -> MSE: 0.000684, MAE: 0.019307, R²: 0.0014
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.38296 | val 0.63448
  Epoch 020 - train 0.42986 | val 0.63457
  Epoch 021 - train 0.40590 | val 0.63470
  Regression -> MSE: 0.000318, MAE: 0.014471, R²: -0.0238
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.33202 | val 0.91459
  Epoch 020 - train 0.32308 | val 0.88255
  Epoch 021 - train 0.34012 | val 0.88831
  Regression -> MSE: 0.000362, MAE: 0.014766, R²: -0.0356
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.38645 | val 0.33632
  Epoch 020 - train 0.35380 | val 0.33545
  Epoch 029 - train 0.38493 | val 0.33499
  Regression -> MSE: 0.000214, MAE: 0.010206, R²: -0.0526
  Directional -> Accuracy: 0.4314, MCC: -0.2079, F1: 0.5672

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.44262 | val 0.95567
  Epoch 020 - train 0.35959 | val 0.96317
  Epoch 021 - train 0.34940 | val 0.96382
  Regression -> MSE: 0.000573, MAE: 0.018392, R²: -0.0324
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.39277 | val 0.47605
  Epoch 020 - train 0.40927 | val 0.46883
  Epoch 021 - train 0.38079 | val 0.46855
  Regression -> MSE: 0.000245, MAE: 0.011996, R²: 0.0033
  Directional -> Accuracy: 0.4058, MCC: -0.0592, F1: 0.5495

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.37502 | val 0.47217
  Epoch 020 - train 0.38931 | val 0.49324
  Epoch 021 - train 0.37728 | val 0.49736
  Regression -> MSE: 0.000612, MAE: 0.019527, R²: -0.0248
  Directional -> Accuracy: 0.4773, MCC: 0.1523, F1: 0.5965

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.37326 | val 0.49113
  Epoch 020 - train 0.36552 | val 0.49796
  Epoch 021 - train 0.39156 | val 0.49387
  Regression -> MSE: 0.000388, MAE: 0.016050, R²: -0.0102
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.37351 | val 0.49001
  Epoch 020 - train 0.38621 | val 0.48947
  Epoch 021 - train 0.39659 | val 0.48805
  Regression -> MSE: 0.000241, MAE: 0.011852, R²: 0.0020
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.38895 | val 0.66729
  Epoch 020 - train 0.36514 | val 0.67384
  Epoch 021 - train 0.34719 | val 0.67703
  Regression -> MSE: 0.000314, MAE: 0.013571, R²: -0.0110
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.39850 | val 0.48819
  Epoch 020 - train 0.46711 | val 0.48519
  Epoch 021 - train 0.42478 | val 0.48408
  Regression -> MSE: 0.000677, MAE: 0.019532, R²: 0.0002
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.33848 | val 0.49682
  Epoch 020 - train 0.37236 | val 0.49804
  Epoch 021 - train 0.36374 | val 0.50337
  Regression -> MSE: 0.000138, MAE: 0.009105, R²: -0.0013
  Directional -> Accuracy: 0.4419, MCC: -0.0644, F1: 0.5385

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.37456 | val 0.48226
  Epoch 020 - train 0.39443 | val 0.48642
  Epoch 021 - train 0.34872 | val 0.48473
  Regression -> MSE: 0.000225, MAE: 0.010687, R²: -0.0013
  Directional -> Accuracy: 0.4918, MCC: -0.0141, F1: 0.4561

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.41439 | val 0.79389
  Epoch 020 - train 0.38514 | val 0.79318
  Epoch 026 - train 0.40445 | val 0.79566
  Regression -> MSE: 0.000362, MAE: 0.015560, R²: -0.0007
  Directional -> Accuracy: 0.5962, MCC: 0.2673, F1: 0.2222

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.44274 | val 0.43045
  Epoch 020 - train 0.42205 | val 0.40512
  Epoch 021 - train 0.43012 | val 0.40973
  Regression -> MSE: 0.000111, MAE: 0.008237, R²: -0.0271
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39742 | val 0.70503
  Epoch 020 - train 0.38022 | val 0.69981
  Epoch 023 - train 0.40863 | val 0.69482
  Regression -> MSE: 0.000163, MAE: 0.010179, R²: -0.0463
  Directional -> Accuracy: 0.4746, MCC: -0.2408, F1: 0.6265

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.37249 | val 0.38476
  Epoch 020 - train 0.38104 | val 0.38658
  Epoch 021 - train 0.37269 | val 0.37978
  Regression -> MSE: 0.000279, MAE: 0.013395, R²: -0.0264
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.33084 | val 0.47933
  Epoch 020 - train 0.34963 | val 0.47905
  Epoch 021 - train 0.34323 | val 0.47948
  Regression -> MSE: 0.000162, MAE: 0.009001, R²: -0.0862
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.41925 | val 0.60043
  Epoch 020 - train 0.39056 | val 0.60198
  Epoch 021 - train 0.44623 | val 0.60357
  Regression -> MSE: 0.000249, MAE: 0.011259, R²: -0.0983
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.42411 | val 0.48011
  Epoch 020 - train 0.37487 | val 0.47853
  Epoch 021 - train 0.39197 | val 0.47485
  Regression -> MSE: 0.000147, MAE: 0.008543, R²: -0.0230
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.35177 | val 0.48576
  Epoch 020 - train 0.35417 | val 0.48532
  Epoch 021 - train 0.36319 | val 0.48755
  Regression -> MSE: 0.000166, MAE: 0.010622, R²: -0.0045
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.38524 | val 0.44879
  Epoch 020 - train 0.45023 | val 0.45040
  Epoch 021 - train 0.41858 | val 0.45142
  Regression -> MSE: 0.000087, MAE: 0.007140, R²: -0.0170
  Directional -> Accuracy: 0.5517, MCC: -0.0461, F1: 0.7045

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.38994 | val 0.47320
  Epoch 020 - train 0.40995 | val 0.46515
  Epoch 021 - train 0.42369 | val 0.46011
  Regression -> MSE: 0.000215, MAE: 0.011031, R²: -0.0154
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.39180 | val 0.30758
  Epoch 020 - train 0.33179 | val 0.30614
  Epoch 021 - train 0.40700 | val 0.30917
  Regression -> MSE: 0.000091, MAE: 0.008065, R²: 0.0075
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.38705 | val 0.38458
  Epoch 020 - train 0.38040 | val 0.39348
  Epoch 021 - train 0.45454 | val 0.39502
  Regression -> MSE: 0.000116, MAE: 0.009232, R²: -0.1288
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.41912 | val 0.33067
  Epoch 020 - train 0.44257 | val 0.33066
  Epoch 021 - train 0.40222 | val 0.33205
  Regression -> MSE: 0.000239, MAE: 0.012825, R²: -0.0331
  Directional -> Accuracy: 0.3953, MCC: -0.1377, F1: 0.0714

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.40154 | val 0.42448
  Epoch 020 - train 0.36624 | val 0.42448
  Epoch 021 - train 0.37932 | val 0.42487
  Regression -> MSE: 0.000174, MAE: 0.007897, R²: -0.0477
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.41259 | val 0.24607
  Epoch 020 - train 0.37132 | val 0.24261
  Epoch 030 - train 0.39058 | val 0.24369
  Regression -> MSE: 0.000295, MAE: 0.013162, R²: -0.2487
  Directional -> Accuracy: 0.4634, MCC: -0.0304, F1: 0.2143

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.38912 | val 0.64295
  Epoch 020 - train 0.39059 | val 0.64913
  Epoch 021 - train 0.40280 | val 0.65393
  Regression -> MSE: 0.000231, MAE: 0.009903, R²: -0.0026
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.43296 | val 0.49805
  Epoch 020 - train 0.45995 | val 0.50504
  Epoch 021 - train 0.44355 | val 0.50272
  Regression -> MSE: 0.000143, MAE: 0.008617, R²: -0.0582
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.38259 | val 0.43865
  Epoch 020 - train 0.38505 | val 0.44115
  Epoch 025 - train 0.35511 | val 0.44128
  Regression -> MSE: 0.000221, MAE: 0.011302, R²: -0.1713
  Directional -> Accuracy: 0.5200, MCC: 0.1411, F1: 0.2941

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38056 | val 0.56055
  Epoch 020 - train 0.38262 | val 0.55617
  Epoch 021 - train 0.37555 | val 0.55662
  Regression -> MSE: 0.000267, MAE: 0.010752, R²: -0.0199
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.44179 | val 0.38821
  Epoch 020 - train 0.33808 | val 0.57494
  Epoch 021 - train 0.36506 | val 0.58445
  Regression -> MSE: 0.000168, MAE: 0.010382, R²: -0.0091
  Directional -> Accuracy: 0.4474, MCC: -0.1291, F1: 0.5714

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.41633 | val 0.40757
  Epoch 020 - train 0.36921 | val 0.41214
  Epoch 021 - train 0.39726 | val 0.41145
  Regression -> MSE: 0.000181, MAE: 0.010283, R²: -0.0052
  Directional -> Accuracy: 0.5000, MCC: -0.1457, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.39590 | val 0.35812
  Epoch 020 - train 0.39838 | val 0.35947
  Epoch 021 - train 0.36285 | val 0.35854
  Regression -> MSE: 0.000345, MAE: 0.011920, R²: -0.0057
  Directional -> Accuracy: 0.3731, MCC: -0.2357, F1: 0.0870

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.35648 | val 0.19710
  Epoch 020 - train 0.41889 | val 0.19841
  Epoch 021 - train 0.36042 | val 0.19829
  Regression -> MSE: 0.000122, MAE: 0.008401, R²: -0.1618
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.38531 | val 0.53712
  Epoch 020 - train 0.37349 | val 0.53181
  Epoch 021 - train 0.39676 | val 0.53322
  Regression -> MSE: 0.000225, MAE: 0.011488, R²: -0.0314
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.36969 | val 0.81028
  Epoch 020 - train 0.39786 | val 0.80893
  Epoch 021 - train 0.34987 | val 0.80691
  Regression -> MSE: 0.000097, MAE: 0.007670, R²: -0.2465
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39503 | val 0.55883
  Epoch 020 - train 0.38426 | val 0.64179
  Epoch 021 - train 0.43719 | val 0.63619
  Regression -> MSE: 0.000351, MAE: 0.015689, R²: -0.1404
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.44799 | val 0.18881
  Epoch 020 - train 0.43555 | val 0.19492
  Epoch 021 - train 0.42063 | val 0.19604
  Regression -> MSE: 0.000257, MAE: 0.011479, R²: -0.0527
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.37757 | val 0.49006
  Epoch 020 - train 0.39196 | val 0.49012
  Epoch 021 - train 0.38338 | val 0.48698
  Regression -> MSE: 0.000081, MAE: 0.007075, R²: -0.0021
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.37983 | val 0.42723
  Epoch 020 - train 0.41371 | val 0.42971
  Epoch 026 - train 0.38902 | val 0.42943
  Regression -> MSE: 0.000297, MAE: 0.014208, R²: 0.0307
  Directional -> Accuracy: 0.5319, MCC: 0.0764, F1: 0.6667

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42724 | val 0.40264
  Epoch 020 - train 0.33087 | val 0.39097
  Epoch 030 - train 0.43250 | val 0.39002
  Regression -> MSE: 0.000097, MAE: 0.006823, R²: 0.0088
  Directional -> Accuracy: 0.6364, MCC: 0.2661, F1: 0.7500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.39826 | val 0.42948
  Epoch 020 - train 0.40218 | val 0.42866
  Epoch 030 - train 0.39391 | val 0.43192
  Regression -> MSE: 0.000189, MAE: 0.009770, R²: -0.0985
  Directional -> Accuracy: 0.5306, MCC: -0.1249, F1: 0.1481

[84/88] Processing V...


[I 2026-02-24 03:28:58,431] Trial 138 finished with value: -0.011513449471493551 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 7.467542295042905e-06, 'weight_decay': 1.4325588740690313e-05, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.7149432399489364, 'early_stopping_min_delta': 0.005902560042131268}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.38136 | val 0.56933
  Epoch 021 - train 0.38881 | val 0.56768
  Regression -> MSE: 0.000238, MAE: 0.012368, R²: -0.0024
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14524 | val 0.20255
  Epoch 020 - train 0.14679 | val 0.20412
  Epoch 021 - train 0.13508 | val 0.20600
  Regression -> MSE: 0.000257, MAE: 0.012897, R²: -0.0361
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14322 | val 0.13482
  Epoch 020 - train 0.14730 | val 0.14361
  Epoch 021 - train 0.14709 | val 0.14398
  Regression -> MSE: 0.000714, MAE: 0.019856, R²: -0.0435
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.14545 | val 0.22429
  Epoch 020 - train 0.14256 | val 0.22785
  Epoch 021 - train 0.14456 | val 0.22793
  Regression -> MSE: 0.000314, MAE: 0.014442, R²: -0.0120
  Directional -> Accuracy: 0.5319, MCC: 0.0135, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11539 | val 0.12565
  Epoch 020 - train 0.11883 | val 0.13057
  Epoch 021 - train 0.11555 | val 0.12981
  Regression -> MSE: 0.000369, MAE: 0.014906, R²: -0.0576
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14888 | val 0.13786
  Epoch 020 - train 0.14431 | val 0.13833
  Epoch 021 - train 0.14107 | val 0.13854
  Regression -> MSE: 0.000204, MAE: 0.010053, R²: -0.0009
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.14220 | val 0.25189
  Epoch 020 - train 0.14193 | val 0.29841
  Epoch 021 - train 0.13564 | val 0.29983
  Regression -> MSE: 0.000556, MAE: 0.018141, R²: -0.0023
  Directional -> Accuracy: 0.5106, MCC: 0.0200, F1: 0.4889

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14067 | val 0.17011
  Epoch 020 - train 0.14742 | val 0.16886
  Epoch 021 - train 0.14964 | val 0.16861
  Regression -> MSE: 0.000246, MAE: 0.011922, R²: -0.0033
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13905 | val 0.16513
  Epoch 020 - train 0.15152 | val 0.17479
  Epoch 021 - train 0.14799 | val 0.17539
  Regression -> MSE: 0.000604, MAE: 0.019322, R²: -0.0109
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14864 | val 0.18225
  Epoch 020 - train 0.14201 | val 0.20939
  Epoch 021 - train 0.15299 | val 0.20945
  Regression -> MSE: 0.000383, MAE: 0.016202, R²: 0.0025
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14019 | val 0.17653
  Epoch 020 - train 0.13684 | val 0.17509
  Epoch 021 - train 0.13594 | val 0.17566
  Regression -> MSE: 0.000242, MAE: 0.011768, R²: -0.0025
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13862 | val 0.20703
  Epoch 020 - train 0.13452 | val 0.21684
  Epoch 021 - train 0.13662 | val 0.21628
  Regression -> MSE: 0.000311, MAE: 0.013658, R²: -0.0015
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15059 | val 0.18004
  Epoch 020 - train 0.14866 | val 0.18354
  Epoch 021 - train 0.14958 | val 0.18361
  Regression -> MSE: 0.000684, MAE: 0.019528, R²: -0.0094
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14775 | val 0.13247
  Epoch 020 - train 0.13883 | val 0.14324
  Epoch 021 - train 0.14461 | val 0.14395
  Regression -> MSE: 0.000143, MAE: 0.009410, R²: -0.0324
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13434 | val 0.17418
  Epoch 020 - train 0.13224 | val 0.17089
  Epoch 030 - train 0.12888 | val 0.17072
  Regression -> MSE: 0.000213, MAE: 0.010401, R²: 0.0510
  Directional -> Accuracy: 0.6393, MCC: 0.2817, F1: 0.6765

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13906 | val 0.27379
  Epoch 020 - train 0.13674 | val 0.26880
  Epoch 030 - train 0.13723 | val 0.27003
  Regression -> MSE: 0.000509, MAE: 0.018925, R²: -0.4066
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14361 | val 0.14734
  Epoch 020 - train 0.14093 | val 0.14650
  Epoch 021 - train 0.13964 | val 0.14643
  Regression -> MSE: 0.000110, MAE: 0.008184, R²: -0.0171
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15585 | val 0.23231
  Epoch 020 - train 0.14474 | val 0.24031
  Epoch 021 - train 0.14709 | val 0.24206
  Regression -> MSE: 0.000161, MAE: 0.010152, R²: -0.0356
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14301 | val 0.14310
  Epoch 020 - train 0.14576 | val 0.14398
  Epoch 021 - train 0.14639 | val 0.14382
  Regression -> MSE: 0.000272, MAE: 0.013010, R²: -0.0003
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13892 | val 0.19137
  Epoch 020 - train 0.13604 | val 0.19067
  Epoch 021 - train 0.13413 | val 0.19063
  Regression -> MSE: 0.000175, MAE: 0.009382, R²: -0.1707
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14842 | val 0.19075
  Epoch 020 - train 0.14274 | val 0.18709
  Epoch 021 - train 0.14507 | val 0.18707
  Regression -> MSE: 0.000247, MAE: 0.011231, R²: -0.0922
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13984 | val 0.17043
  Epoch 020 - train 0.14839 | val 0.17290
  Epoch 021 - train 0.13557 | val 0.17320
  Regression -> MSE: 0.000144, MAE: 0.008411, R²: -0.0057
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13022 | val 0.16158
  Epoch 020 - train 0.13741 | val 0.16370
  Epoch 021 - train 0.13061 | val 0.16383
  Regression -> MSE: 0.000168, MAE: 0.010278, R²: -0.0195
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14822 | val 0.16232
  Epoch 020 - train 0.14429 | val 0.16145
  Epoch 021 - train 0.14651 | val 0.16176
  Regression -> MSE: 0.000085, MAE: 0.007034, R²: -0.0002
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14213 | val 0.17826
  Epoch 020 - train 0.14341 | val 0.17272
  Epoch 021 - train 0.14944 | val 0.17223
  Regression -> MSE: 0.000213, MAE: 0.011343, R²: -0.0075
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13382 | val 0.12581
  Epoch 020 - train 0.13432 | val 0.12405
  Epoch 021 - train 0.13123 | val 0.12389
  Regression -> MSE: 0.000094, MAE: 0.008110, R²: -0.0173
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14516 | val 0.10703
  Epoch 020 - train 0.15333 | val 0.11062
  Epoch 021 - train 0.14538 | val 0.11114
  Regression -> MSE: 0.000105, MAE: 0.008852, R²: -0.0207
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15838 | val 0.13138
  Epoch 020 - train 0.14737 | val 0.13310
  Epoch 021 - train 0.15175 | val 0.13291
  Regression -> MSE: 0.000237, MAE: 0.012744, R²: -0.0227
  Directional -> Accuracy: 0.4419, MCC: -0.0573, F1: 0.3684

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14703 | val 0.15659
  Epoch 020 - train 0.14104 | val 0.15724
  Epoch 021 - train 0.14067 | val 0.15735
  Regression -> MSE: 0.000179, MAE: 0.007924, R²: -0.0732
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14145 | val 0.11516
  Epoch 020 - train 0.15367 | val 0.11809
  Epoch 021 - train 0.14239 | val 0.11885
  Regression -> MSE: 0.000238, MAE: 0.011909, R²: -0.0058
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14684 | val 0.21767
  Epoch 020 - train 0.14262 | val 0.25757
  Epoch 021 - train 0.15140 | val 0.25929
  Regression -> MSE: 0.000230, MAE: 0.009864, R²: 0.0019
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15700 | val 0.17560
  Epoch 020 - train 0.14421 | val 0.17134
  Epoch 021 - train 0.14545 | val 0.17183
  Regression -> MSE: 0.000141, MAE: 0.008504, R²: -0.0456
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14478 | val 0.17590
  Epoch 020 - train 0.14591 | val 0.18020
  Epoch 021 - train 0.14152 | val 0.17972
  Regression -> MSE: 0.000190, MAE: 0.010373, R²: -0.0082
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13515 | val 0.17330
  Epoch 020 - train 0.13261 | val 0.17155
  Epoch 021 - train 0.13495 | val 0.17074
  Regression -> MSE: 0.000263, MAE: 0.010760, R²: -0.0057
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13676 | val 0.11542
  Epoch 020 - train 0.13268 | val 0.11128
  Epoch 021 - train 0.14083 | val 0.11125
  Regression -> MSE: 0.000167, MAE: 0.010368, R²: 0.0008
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13373 | val 0.14862
  Epoch 020 - train 0.13578 | val 0.16262
  Epoch 021 - train 0.13856 | val 0.16263
  Regression -> MSE: 0.000180, MAE: 0.010332, R²: -0.0014
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14009 | val 0.14128
  Epoch 020 - train 0.13720 | val 0.14365
  Epoch 021 - train 0.14268 | val 0.14419
  Regression -> MSE: 0.000350, MAE: 0.012356, R²: -0.0210
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14720 | val 0.08919
  Epoch 020 - train 0.14583 | val 0.08780
  Epoch 021 - train 0.14391 | val 0.08766
  Regression -> MSE: 0.000125, MAE: 0.008462, R²: -0.1872
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13963 | val 0.23482
  Epoch 020 - train 0.14577 | val 0.25412
  Epoch 021 - train 0.14481 | val 0.25452
  Regression -> MSE: 0.000220, MAE: 0.011348, R²: -0.0058
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14450 | val 0.23702
  Epoch 020 - train 0.14779 | val 0.24577
  Epoch 021 - train 0.14075 | val 0.24532
  Regression -> MSE: 0.000090, MAE: 0.007431, R²: -0.1618
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14280 | val 0.10087
  Epoch 020 - train 0.14668 | val 0.10115
  Epoch 021 - train 0.15369 | val 0.10123
  Regression -> MSE: 0.000308, MAE: 0.013656, R²: -0.0012
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15758 | val 0.08799
  Epoch 020 - train 0.16056 | val 0.08662
  Epoch 021 - train 0.16184 | val 0.08621
  Regression -> MSE: 0.000257, MAE: 0.011475, R²: -0.0534
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14394 | val 0.17309
  Epoch 020 - train 0.13936 | val 0.17248
  Epoch 021 - train 0.13681 | val 0.17270
  Regression -> MSE: 0.000083, MAE: 0.007069, R²: -0.0230
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14402 | val 0.16930
  Epoch 020 - train 0.14568 | val 0.16270
  Epoch 030 - train 0.14718 | val 0.16583
  Regression -> MSE: 0.000307, MAE: 0.014309, R²: 0.0001
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12891 | val 0.16146
  Epoch 020 - train 0.15175 | val 0.15498
  Epoch 030 - train 0.13325 | val 0.15315
  Regression -> MSE: 0.000099, MAE: 0.007052, R²: -0.0075
  Directional -> Accuracy: 0.5909, MCC: 0.1749, F1: 0.7353

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15438 | val 0.16066
  Epoch 020 - train 0.15345 | val 0.16364
  Epoch 021 - train 0.15509 | val 0.16409
  Regression -> MSE: 0.000173, MAE: 0.009873, R²: -0.0047
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14375 | val 0.20477
  Epoch 020 - train 0.13773 | val 0.22936
  Epoch 021 - train 0.14584 | val 0.23115
  Regression -> MSE: 0.000226, MAE: 0.011771, R²: -0.0147
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13682 | val 0.17119
  Epoch 020 - train 0.14604 | val 0.17987
  Epoch 021 - train 0.14388 | val 0.17828

[I 2026-02-24 03:31:04,703] Trial 139 finished with value: -0.011493936100435427 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 2.8723678213724164e-05, 'weight_decay': 8.252895704572539e-06, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.20797208225340735, 'early_stopping_min_delta': 0.006980250188891301}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.14312 | val 0.20260
  Epoch 021 - train 0.14712 | val 0.20137
  Regression -> MSE: 0.000238, MAE: 0.012368, R²: -0.0034
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.26192 | val 0.30102
  Epoch 020 - train 0.23800 | val 0.29950
  Epoch 021 - train 0.25115 | val 0.29968
  Regression -> MSE: 0.000248, MAE: 0.012573, R²: -0.0029
  Directional -> Accuracy: 0.4286, MCC: -0.1111, F1: 0.5600

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.23421 | val 0.25146
  Epoch 020 - train 0.23305 | val 0.28843
  Epoch 021 - train 0.25176 | val 0.29040
  Regression -> MSE: 0.000688, MAE: 0.019401, R²: -0.0051
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.27544 | val 0.38087
  Epoch 020 - train 0.26849 | val 0.37961
  Epoch 030 - train 0.27463 | val 0.37972
  Regression -> MSE: 0.000312, MAE: 0.014290, R²: -0.0065
  Directional -> Accuracy: 0.4894, MCC: -0.0845, F1: 0.6250

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.21596 | val 0.26556
  Epoch 020 - train 0.22152 | val 0.23817
  Epoch 021 - train 0.22622 | val 0.23805
  Regression -> MSE: 0.000349, MAE: 0.014571, R²: 0.0005
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.25236 | val 0.22775
  Epoch 020 - train 0.24076 | val 0.22911
  Epoch 021 - train 0.25131 | val 0.22967
  Regression -> MSE: 0.000206, MAE: 0.010103, R²: -0.0111
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.24352 | val 0.44065
  Epoch 020 - train 0.25358 | val 0.44008
  Epoch 021 - train 0.24016 | val 0.43968
  Regression -> MSE: 0.000565, MAE: 0.018248, R²: -0.0174
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.25898 | val 0.28224
  Epoch 020 - train 0.25265 | val 0.28170
  Epoch 021 - train 0.24217 | val 0.28150
  Regression -> MSE: 0.000246, MAE: 0.011946, R²: -0.0013
  Directional -> Accuracy: 0.5507, MCC: 0.0417, F1: 0.3922

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.23295 | val 0.27842
  Epoch 020 - train 0.25532 | val 0.28429
  Epoch 021 - train 0.25352 | val 0.28347
  Regression -> MSE: 0.000606, MAE: 0.019376, R²: -0.0142
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.25065 | val 0.27446
  Epoch 020 - train 0.24253 | val 0.27340
  Epoch 021 - train 0.25280 | val 0.27336
  Regression -> MSE: 0.000392, MAE: 0.015947, R²: -0.0230
  Directional -> Accuracy: 0.5510, MCC: 0.0519, F1: 0.3125

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.25809 | val 0.29598
  Epoch 020 - train 0.25003 | val 0.29262
  Epoch 021 - train 0.25587 | val 0.29228
  Regression -> MSE: 0.000242, MAE: 0.011894, R²: -0.0010
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.25967 | val 0.31880
  Epoch 020 - train 0.25200 | val 0.32009
  Epoch 021 - train 0.22777 | val 0.32036
  Regression -> MSE: 0.000335, MAE: 0.013714, R²: -0.0759
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.25225 | val 0.27254
  Epoch 020 - train 0.27099 | val 0.27523
  Epoch 021 - train 0.26879 | val 0.27522
  Regression -> MSE: 0.000678, MAE: 0.019559, R²: -0.0017
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.27785 | val 0.22867
  Epoch 020 - train 0.25225 | val 0.22908
  Epoch 029 - train 0.25633 | val 0.22906
  Regression -> MSE: 0.000145, MAE: 0.009430, R²: -0.0495
  Directional -> Accuracy: 0.3721, MCC: -0.2331, F1: 0.4255

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.24264 | val 0.31117
  Epoch 020 - train 0.24816 | val 0.31468
  Epoch 021 - train 0.24704 | val 0.31411
  Regression -> MSE: 0.000229, MAE: 0.010812, R²: -0.0168
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.27186 | val 0.48027
  Epoch 020 - train 0.26916 | val 0.47560
  Epoch 021 - train 0.25202 | val 0.47519
  Regression -> MSE: 0.000376, MAE: 0.015935, R²: -0.0388
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.26943 | val 0.26484
  Epoch 020 - train 0.26485 | val 0.25701
  Epoch 021 - train 0.27911 | val 0.25778
  Regression -> MSE: 0.000108, MAE: 0.008081, R²: -0.0037
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.26206 | val 0.41823
  Epoch 020 - train 0.24726 | val 0.44150
  Epoch 021 - train 0.25280 | val 0.44164
  Regression -> MSE: 0.000158, MAE: 0.009953, R²: -0.0137
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.26659 | val 0.23819
  Epoch 020 - train 0.27020 | val 0.24125
  Epoch 021 - train 0.24022 | val 0.24279
  Regression -> MSE: 0.000272, MAE: 0.013036, R²: 0.0002
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.24738 | val 0.30708
  Epoch 020 - train 0.22482 | val 0.30457
  Epoch 030 - train 0.23486 | val 0.30240
  Regression -> MSE: 0.000156, MAE: 0.009033, R²: -0.0431
  Directional -> Accuracy: 0.5231, MCC: 0.0548, F1: 0.5507

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.26047 | val 0.37457
  Epoch 020 - train 0.24603 | val 0.37530
  Epoch 021 - train 0.25366 | val 0.37689
  Regression -> MSE: 0.000234, MAE: 0.010945, R²: -0.0364
  Directional -> Accuracy: 0.4933, MCC: 0.1080, F1: 0.2083

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.24721 | val 0.30219
  Epoch 020 - train 0.28923 | val 0.30291
  Epoch 021 - train 0.26597 | val 0.30631
  Regression -> MSE: 0.000143, MAE: 0.008307, R²: 0.0008
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.26301 | val 0.27156
  Epoch 020 - train 0.25703 | val 0.27042
  Epoch 021 - train 0.23231 | val 0.27083
  Regression -> MSE: 0.000167, MAE: 0.010331, R²: -0.0080
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.26207 | val 0.28315
  Epoch 020 - train 0.27916 | val 0.28299
  Epoch 021 - train 0.27084 | val 0.28316
  Regression -> MSE: 0.000095, MAE: 0.007536, R²: -0.1168
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.26118 | val 0.33182
  Epoch 020 - train 0.25421 | val 0.38198
  Epoch 026 - train 0.27071 | val 0.39208
  Regression -> MSE: 0.000210, MAE: 0.010999, R²: 0.0074
  Directional -> Accuracy: 0.5303, MCC: 0.0589, F1: 0.5079

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.24695 | val 0.19503
  Epoch 020 - train 0.24086 | val 0.19385
  Epoch 030 - train 0.22022 | val 0.19385
  Regression -> MSE: 0.000099, MAE: 0.008250, R²: -0.0710
  Directional -> Accuracy: 0.5000, MCC: -0.0116, F1: 0.5484

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.24071 | val 0.17541
  Epoch 020 - train 0.26568 | val 0.18197
  Epoch 030 - train 0.29495 | val 0.18849
  Regression -> MSE: 0.000101, MAE: 0.008596, R²: 0.0207
  Directional -> Accuracy: 0.5870, MCC: 0.1313, F1: 0.4242

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.28110 | val 0.21877
  Epoch 020 - train 0.28802 | val 0.21528
  Epoch 021 - train 0.27735 | val 0.21488
  Regression -> MSE: 0.000231, MAE: 0.012512, R²: 0.0004
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.24490 | val 0.26676
  Epoch 020 - train 0.24208 | val 0.26636
  Epoch 021 - train 0.24341 | val 0.26634
  Regression -> MSE: 0.000179, MAE: 0.007922, R²: -0.0727
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.26816 | val 0.20733
  Epoch 020 - train 0.28690 | val 0.25089
  Epoch 021 - train 0.25540 | val 0.25505
  Regression -> MSE: 0.000241, MAE: 0.012059, R²: -0.0180
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.24433 | val 0.38420
  Epoch 020 - train 0.24905 | val 0.38286
  Epoch 021 - train 0.24578 | val 0.38358
  Regression -> MSE: 0.000234, MAE: 0.010105, R²: -0.0158
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.27156 | val 0.26318
  Epoch 020 - train 0.24795 | val 0.25891
  Epoch 030 - train 0.25118 | val 0.25916
  Regression -> MSE: 0.000139, MAE: 0.008239, R²: -0.0279
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.25732 | val 0.29264
  Epoch 020 - train 0.24884 | val 0.29562
  Epoch 021 - train 0.25334 | val 0.29577
  Regression -> MSE: 0.000192, MAE: 0.010410, R²: -0.0175
  Directional -> Accuracy: 0.5000, MCC: -0.1242, F1: 0.6575

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.23767 | val 0.25479
  Epoch 020 - train 0.24272 | val 0.25398
  Epoch 025 - train 0.23685 | val 0.25445
  Regression -> MSE: 0.000259, MAE: 0.010551, R²: 0.0105
  Directional -> Accuracy: 0.5342, MCC: 0.0742, F1: 0.5526

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.22755 | val 0.18671
  Epoch 020 - train 0.24169 | val 0.18508
  Epoch 021 - train 0.24454 | val 0.18492
  Regression -> MSE: 0.000168, MAE: 0.010372, R²: -0.0105
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.25743 | val 0.24399
  Epoch 020 - train 0.24350 | val 0.25408
  Epoch 021 - train 0.24219 | val 0.25461
  Regression -> MSE: 0.000186, MAE: 0.010565, R²: -0.0345
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.27474 | val 0.22717
  Epoch 020 - train 0.24746 | val 0.22706
  Epoch 021 - train 0.24466 | val 0.22613
  Regression -> MSE: 0.000350, MAE: 0.011792, R²: -0.0209
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.28657 | val 0.15870
  Epoch 020 - train 0.27213 | val 0.20529
  Epoch 021 - train 0.25151 | val 0.20277
  Regression -> MSE: 0.000110, MAE: 0.008356, R²: -0.0417
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.26301 | val 0.32900
  Epoch 020 - train 0.26377 | val 0.32512
  Epoch 021 - train 0.25723 | val 0.32474
  Regression -> MSE: 0.000222, MAE: 0.011414, R²: -0.0163
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.26171 | val 0.40773
  Epoch 020 - train 0.26639 | val 0.42244
  Epoch 021 - train 0.24762 | val 0.42270
  Regression -> MSE: 0.000092, MAE: 0.007499, R²: -0.1849
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.26692 | val 0.16556
  Epoch 020 - train 0.25321 | val 0.15971
  Epoch 030 - train 0.23512 | val 0.15756
  Regression -> MSE: 0.000335, MAE: 0.013472, R²: -0.0889
  Directional -> Accuracy: 0.6327, MCC: 0.0820, F1: 0.1818

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.26591 | val 0.13300
  Epoch 020 - train 0.27156 | val 0.13775
  Epoch 021 - train 0.27419 | val 0.13868
  Regression -> MSE: 0.000252, MAE: 0.011489, R²: -0.0348
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.26763 | val 0.28840
  Epoch 020 - train 0.25987 | val 0.28953
  Epoch 021 - train 0.24637 | val 0.28901
  Regression -> MSE: 0.000086, MAE: 0.007075, R²: -0.0656
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.26807 | val 0.29453
  Epoch 020 - train 0.25779 | val 0.29061
  Epoch 021 - train 0.25653 | val 0.29026
  Regression -> MSE: 0.000309, MAE: 0.014475, R²: -0.0067
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.24733 | val 0.24282
  Epoch 020 - train 0.26476 | val 0.26618
  Epoch 021 - train 0.27264 | val 0.26789
  Regression -> MSE: 0.000099, MAE: 0.007415, R²: -0.0036
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.29403 | val 0.27507
  Epoch 020 - train 0.26273 | val 0.27528
  Epoch 021 - train 0.27077 | val 0.27599
  Regression -> MSE: 0.000173, MAE: 0.009491, R²: -0.0045
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.24475 | val 0.25880
  Epoch 020 - train 0.25054 | val 0.25944
  Epoch 021 - train 0.24388 | val 0.26131
  Regression -> MSE: 0.000224, MAE: 0.011751, R²: -0.0055
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.24427 | val 0.25708
  Epoch 020 - train 0.22656 | val 0.25746
  Epoch 021 - train 0.25021 | val 0.25867
  Regression -> MSE: 0.000093, MAE: 0.007684, R²: -0.0081
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429


[I 2026-02-24 03:33:08,267] Trial 140 finished with value: -0.011385404795874809 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 1.1875120532619187e-05, 'weight_decay': 3.952152027246496e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.38564943127530255, 'early_stopping_min_delta': 0.007341823970853409}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.26243 | val 0.35303
  Epoch 021 - train 0.27336 | val 0.35163
  Regression -> MSE: 0.000246, MAE: 0.012397, R²: -0.0391
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.08223 | val 0.09464
  Epoch 020 - train 0.08143 | val 0.09450
  Epoch 021 - train 0.08213 | val 0.09471
  Regression -> MSE: 0.000249, MAE: 0.012614, R²: -0.0062
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08179 | val 0.06886
  Epoch 020 - train 0.08290 | val 0.07012
  Epoch 021 - train 0.08188 | val 0.07003
  Regression -> MSE: 0.000683, MAE: 0.019324, R²: 0.0020
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09004 | val 0.11704
  Epoch 020 - train 0.08401 | val 0.11689
  Epoch 021 - train 0.08446 | val 0.11690
  Regression -> MSE: 0.000311, MAE: 0.014460, R²: -0.0017
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07138 | val 0.07352
  Epoch 020 - train 0.07305 | val 0.07211
  Epoch 021 - train 0.07433 | val 0.07257
  Regression -> MSE: 0.000351, MAE: 0.014571, R²: -0.0036
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.08503 | val 0.07613
  Epoch 020 - train 0.08094 | val 0.07656
  Epoch 021 - train 0.08862 | val 0.07694
  Regression -> MSE: 0.000207, MAE: 0.010133, R²: -0.0156
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08733 | val 0.13205
  Epoch 020 - train 0.08144 | val 0.13637
  Epoch 021 - train 0.07212 | val 0.13655
  Regression -> MSE: 0.000558, MAE: 0.018182, R²: -0.0045
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.08560 | val 0.10139
  Epoch 020 - train 0.08865 | val 0.09966
  Epoch 021 - train 0.08712 | val 0.09959
  Regression -> MSE: 0.000251, MAE: 0.012533, R²: -0.0219
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08645 | val 0.08895
  Epoch 020 - train 0.08391 | val 0.09340
  Epoch 021 - train 0.08635 | val 0.09301
  Regression -> MSE: 0.000609, MAE: 0.019452, R²: -0.0197
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07897 | val 0.08499
  Epoch 020 - train 0.08009 | val 0.08521
  Epoch 021 - train 0.08330 | val 0.08522
  Regression -> MSE: 0.000404, MAE: 0.016119, R²: -0.0529
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.08373 | val 0.09525
  Epoch 020 - train 0.08306 | val 0.09516
  Epoch 021 - train 0.08079 | val 0.09534
  Regression -> MSE: 0.000247, MAE: 0.011623, R²: -0.0217
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.07793 | val 0.10334
  Epoch 020 - train 0.07825 | val 0.10427
  Epoch 021 - train 0.07480 | val 0.10405
  Regression -> MSE: 0.000315, MAE: 0.013620, R²: -0.0131
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08519 | val 0.11058
  Epoch 020 - train 0.08472 | val 0.11509
  Epoch 021 - train 0.08542 | val 0.11632
  Regression -> MSE: 0.000677, MAE: 0.019495, R²: 0.0005
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.08467 | val 0.08352
  Epoch 020 - train 0.08987 | val 0.09339
  Epoch 021 - train 0.09117 | val 0.09400
  Regression -> MSE: 0.000140, MAE: 0.009007, R²: -0.0139
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.07652 | val 0.09545
  Epoch 020 - train 0.08215 | val 0.09477
  Epoch 021 - train 0.07462 | val 0.09481
  Regression -> MSE: 0.000225, MAE: 0.010713, R²: -0.0009
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07824 | val 0.14355
  Epoch 020 - train 0.08202 | val 0.14585
  Epoch 021 - train 0.08411 | val 0.14552
  Regression -> MSE: 0.000368, MAE: 0.015927, R²: -0.0161
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.08056 | val 0.11156
  Epoch 020 - train 0.08554 | val 0.11147
  Epoch 021 - train 0.08074 | val 0.10945
  Regression -> MSE: 0.000111, MAE: 0.008250, R²: -0.0280
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08652 | val 0.13118
  Epoch 020 - train 0.08200 | val 0.13345
  Epoch 021 - train 0.08480 | val 0.13378
  Regression -> MSE: 0.000155, MAE: 0.009619, R²: 0.0033
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08444 | val 0.07948
  Epoch 020 - train 0.08543 | val 0.07845
  Epoch 021 - train 0.08218 | val 0.07823
  Regression -> MSE: 0.000273, MAE: 0.013050, R²: -0.0031
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07516 | val 0.09350
  Epoch 020 - train 0.07777 | val 0.09352
  Epoch 021 - train 0.07549 | val 0.09362
  Regression -> MSE: 0.000158, MAE: 0.008850, R²: -0.0578
  Directional -> Accuracy: 0.5692, MCC: -0.0366, F1: 0.7200

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.08146 | val 0.11343
  Epoch 020 - train 0.08216 | val 0.11485
  Epoch 021 - train 0.07462 | val 0.11541
  Regression -> MSE: 0.000229, MAE: 0.010899, R²: -0.0126
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08143 | val 0.09741
  Epoch 020 - train 0.08399 | val 0.10625
  Epoch 021 - train 0.08257 | val 0.10634
  Regression -> MSE: 0.000152, MAE: 0.008771, R²: -0.0599
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.08241 | val 0.08787
  Epoch 020 - train 0.08220 | val 0.08793
  Epoch 021 - train 0.08745 | val 0.08791
  Regression -> MSE: 0.000167, MAE: 0.010322, R²: -0.0136
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08863 | val 0.08712
  Epoch 020 - train 0.08382 | val 0.08741
  Epoch 021 - train 0.08911 | val 0.08747
  Regression -> MSE: 0.000086, MAE: 0.007076, R²: -0.0071
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.08661 | val 0.08872
  Epoch 020 - train 0.08183 | val 0.08900
  Epoch 021 - train 0.09010 | val 0.08884
  Regression -> MSE: 0.000215, MAE: 0.011069, R²: -0.0139
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08352 | val 0.07400
  Epoch 020 - train 0.07801 | val 0.07479
  Epoch 021 - train 0.08016 | val 0.07500
  Regression -> MSE: 0.000105, MAE: 0.008328, R²: -0.1414
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.08865 | val 0.06059
  Epoch 020 - train 0.07576 | val 0.06934
  Epoch 021 - train 0.08649 | val 0.07058
  Regression -> MSE: 0.000109, MAE: 0.009018, R²: -0.0618
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09239 | val 0.06940
  Epoch 020 - train 0.08033 | val 0.06991
  Epoch 021 - train 0.08550 | val 0.06990
  Regression -> MSE: 0.000232, MAE: 0.012565, R²: -0.0020
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07991 | val 0.08765
  Epoch 020 - train 0.08059 | val 0.08799
  Epoch 021 - train 0.07869 | val 0.08804
  Regression -> MSE: 0.000185, MAE: 0.008067, R²: -0.1143
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08584 | val 0.06574
  Epoch 020 - train 0.08849 | val 0.06688
  Epoch 021 - train 0.08173 | val 0.06732
  Regression -> MSE: 0.000239, MAE: 0.011950, R²: -0.0098
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09268 | val 0.11212
  Epoch 020 - train 0.09644 | val 0.11393
  Epoch 021 - train 0.08442 | val 0.11377
  Regression -> MSE: 0.000230, MAE: 0.009859, R²: 0.0010
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.08444 | val 0.09506
  Epoch 020 - train 0.09043 | val 0.09654
  Epoch 021 - train 0.08224 | val 0.09631
  Regression -> MSE: 0.000146, MAE: 0.008777, R²: -0.0793
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08885 | val 0.09172
  Epoch 020 - train 0.08538 | val 0.09329
  Epoch 021 - train 0.08691 | val 0.09300
  Regression -> MSE: 0.000194, MAE: 0.010489, R²: -0.0305
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07922 | val 0.08697
  Epoch 020 - train 0.07718 | val 0.08621
  Epoch 021 - train 0.08136 | val 0.08654
  Regression -> MSE: 0.000278, MAE: 0.010867, R²: -0.0610
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07962 | val 0.06233
  Epoch 020 - train 0.07910 | val 0.06333
  Epoch 021 - train 0.08148 | val 0.06354
  Regression -> MSE: 0.000171, MAE: 0.010385, R²: -0.0263
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08253 | val 0.07222
  Epoch 020 - train 0.07795 | val 0.07186
  Epoch 021 - train 0.08010 | val 0.07189
  Regression -> MSE: 0.000181, MAE: 0.010340, R²: -0.0052
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07776 | val 0.06895
  Epoch 020 - train 0.07657 | val 0.06930
  Epoch 021 - train 0.07712 | val 0.06945
  Regression -> MSE: 0.000346, MAE: 0.012094, R²: -0.0088
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.09393 | val 0.05041
  Epoch 020 - train 0.08501 | val 0.05304
  Epoch 021 - train 0.08729 | val 0.05297
  Regression -> MSE: 0.000111, MAE: 0.008296, R²: -0.0584
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.08592 | val 0.09742
  Epoch 020 - train 0.08149 | val 0.09846
  Epoch 021 - train 0.08365 | val 0.09832
  Regression -> MSE: 0.000223, MAE: 0.011387, R²: -0.0182
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.08294 | val 0.11977
  Epoch 020 - train 0.08643 | val 0.12347
  Epoch 021 - train 0.09193 | val 0.12339
  Regression -> MSE: 0.000092, MAE: 0.007510, R²: -0.1876
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07792 | val 0.05812
  Epoch 020 - train 0.08558 | val 0.06114
  Epoch 021 - train 0.08298 | val 0.06134
  Regression -> MSE: 0.000315, MAE: 0.014249, R²: -0.0241
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09475 | val 0.05163
  Epoch 020 - train 0.08518 | val 0.05451
  Epoch 021 - train 0.08228 | val 0.05525
  Regression -> MSE: 0.000265, MAE: 0.011551, R²: -0.0878
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.07900 | val 0.08933
  Epoch 020 - train 0.07579 | val 0.08912
  Epoch 021 - train 0.07745 | val 0.08911
  Regression -> MSE: 0.000082, MAE: 0.007153, R²: -0.0154
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.08514 | val 0.08724
  Epoch 020 - train 0.08613 | val 0.08769
  Epoch 021 - train 0.08619 | val 0.08759
  Regression -> MSE: 0.000308, MAE: 0.014499, R²: -0.0024
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07656 | val 0.08637
  Epoch 020 - train 0.07795 | val 0.08861
  Epoch 021 - train 0.07781 | val 0.08824
  Regression -> MSE: 0.000102, MAE: 0.007113, R²: -0.0379
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.09740 | val 0.08995
  Epoch 020 - train 0.09300 | val 0.10104
  Epoch 021 - train 0.08473 | val 0.10199
  Regression -> MSE: 0.000177, MAE: 0.010322, R²: -0.0327
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07566 | val 0.08204
  Epoch 020 - train 0.07770 | val 0.08200
  Epoch 021 - train 0.07758 | val 0.08211
  Regression -> MSE: 0.000224, MAE: 0.011752, R²: -0.0028
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977


[I 2026-02-24 03:35:11,183] Trial 141 finished with value: -0.011429031208523717 and parameters: {'feature_set': 'emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 1.050051041001094e-05, 'weight_decay': 3.4539607437974645e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.10359379820585957, 'early_stopping_min_delta': 0.006790077281151636}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.07760 | val 0.10540
  Epoch 021 - train 0.08191 | val 0.10623
  Regression -> MSE: 0.000241, MAE: 0.012331, R²: -0.0162
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09357 | val 0.11132
  Epoch 020 - train 0.09143 | val 0.11187
  Epoch 021 - train 0.09481 | val 0.11191
  Regression -> MSE: 0.000251, MAE: 0.012659, R²: -0.0119
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09732 | val 0.07897
  Epoch 020 - train 0.09204 | val 0.07775
  Epoch 021 - train 0.09220 | val 0.07783
  Regression -> MSE: 0.000695, MAE: 0.019538, R²: -0.0155
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09871 | val 0.13572
  Epoch 020 - train 0.09461 | val 0.13977
  Epoch 021 - train 0.10714 | val 0.13981
  Regression -> MSE: 0.000320, MAE: 0.014523, R²: -0.0321
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08103 | val 0.07310
  Epoch 020 - train 0.08728 | val 0.07301
  Epoch 021 - train 0.08157 | val 0.07471
  Regression -> MSE: 0.000371, MAE: 0.014937, R²: -0.0625
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09422 | val 0.08752
  Epoch 020 - train 0.09496 | val 0.08835
  Epoch 021 - train 0.10171 | val 0.08823
  Regression -> MSE: 0.000205, MAE: 0.010167, R²: -0.0065
  Directional -> Accuracy: 0.3137, MCC: -0.4015, F1: 0.4068

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09864 | val 0.15368
  Epoch 020 - train 0.09434 | val 0.15436
  Epoch 021 - train 0.08970 | val 0.15432
  Regression -> MSE: 0.000562, MAE: 0.018211, R²: -0.0132
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09983 | val 0.10142
  Epoch 020 - train 0.09361 | val 0.10158
  Epoch 021 - train 0.10123 | val 0.10170
  Regression -> MSE: 0.000251, MAE: 0.012577, R²: -0.0238
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08573 | val 0.11493
  Epoch 020 - train 0.08385 | val 0.13188
  Epoch 021 - train 0.09678 | val 0.13244
  Regression -> MSE: 0.000628, MAE: 0.019856, R²: -0.0517
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08628 | val 0.10249
  Epoch 020 - train 0.08811 | val 0.10109
  Epoch 021 - train 0.09040 | val 0.10111
  Regression -> MSE: 0.000388, MAE: 0.016019, R²: -0.0104
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09482 | val 0.11270
  Epoch 020 - train 0.09745 | val 0.11028
  Epoch 021 - train 0.09251 | val 0.10990
  Regression -> MSE: 0.000244, MAE: 0.012239, R²: -0.0099
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09154 | val 0.11866
  Epoch 020 - train 0.08706 | val 0.11889
  Epoch 021 - train 0.09067 | val 0.11874
  Regression -> MSE: 0.000319, MAE: 0.013585, R²: -0.0268
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10054 | val 0.10016
  Epoch 020 - train 0.10632 | val 0.10075
  Epoch 021 - train 0.10334 | val 0.10118
  Regression -> MSE: 0.000681, MAE: 0.019530, R²: -0.0056
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10143 | val 0.08290
  Epoch 020 - train 0.09758 | val 0.08549
  Epoch 021 - train 0.09810 | val 0.08549
  Regression -> MSE: 0.000141, MAE: 0.009342, R²: -0.0204
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09206 | val 0.11533
  Epoch 020 - train 0.08621 | val 0.11511
  Epoch 021 - train 0.09119 | val 0.11521
  Regression -> MSE: 0.000226, MAE: 0.010833, R²: -0.0064
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09405 | val 0.16936
  Epoch 020 - train 0.08396 | val 0.17311
  Epoch 021 - train 0.10072 | val 0.17360
  Regression -> MSE: 0.000368, MAE: 0.015950, R²: -0.0165
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10941 | val 0.09506
  Epoch 020 - train 0.10547 | val 0.09615
  Epoch 021 - train 0.11079 | val 0.09578
  Regression -> MSE: 0.000111, MAE: 0.007965, R²: -0.0276
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10553 | val 0.13416
  Epoch 020 - train 0.09298 | val 0.13650
  Epoch 021 - train 0.10281 | val 0.13672
  Regression -> MSE: 0.000156, MAE: 0.009523, R²: -0.0016
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09782 | val 0.08524
  Epoch 020 - train 0.09139 | val 0.08605
  Epoch 021 - train 0.09417 | val 0.08635
  Regression -> MSE: 0.000286, MAE: 0.013672, R²: -0.0506
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08388 | val 0.11047
  Epoch 020 - train 0.08588 | val 0.11068
  Epoch 021 - train 0.08650 | val 0.11042
  Regression -> MSE: 0.000174, MAE: 0.009343, R²: -0.1660
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09078 | val 0.12438
  Epoch 020 - train 0.10119 | val 0.12482
  Epoch 021 - train 0.09557 | val 0.12473
  Regression -> MSE: 0.000251, MAE: 0.011309, R²: -0.1098
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09237 | val 0.10138
  Epoch 020 - train 0.09046 | val 0.10372
  Epoch 021 - train 0.09139 | val 0.10409
  Regression -> MSE: 0.000144, MAE: 0.008342, R²: -0.0024
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09310 | val 0.11166
  Epoch 020 - train 0.09336 | val 0.11311
  Epoch 021 - train 0.09062 | val 0.11228
  Regression -> MSE: 0.000165, MAE: 0.010466, R²: 0.0031
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09813 | val 0.09855
  Epoch 020 - train 0.09970 | val 0.09731
  Epoch 021 - train 0.09789 | val 0.09715
  Regression -> MSE: 0.000086, MAE: 0.007081, R²: -0.0076
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09611 | val 0.10432
  Epoch 020 - train 0.09275 | val 0.10520
  Epoch 021 - train 0.09273 | val 0.10518
  Regression -> MSE: 0.000212, MAE: 0.011217, R²: -0.0022
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09544 | val 0.08039
  Epoch 020 - train 0.09361 | val 0.07998
  Epoch 021 - train 0.09237 | val 0.08005
  Regression -> MSE: 0.000094, MAE: 0.008096, R²: -0.0176
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10009 | val 0.06848
  Epoch 020 - train 0.09260 | val 0.06744
  Epoch 021 - train 0.08841 | val 0.06739
  Regression -> MSE: 0.000109, MAE: 0.008997, R²: -0.0564
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.08430 | val 0.08034
  Epoch 020 - train 0.09034 | val 0.08357
  Epoch 021 - train 0.09087 | val 0.08385
  Regression -> MSE: 0.000231, MAE: 0.012526, R²: -0.0001
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09701 | val 0.09764
  Epoch 020 - train 0.08705 | val 0.09788
  Epoch 021 - train 0.09796 | val 0.09798
  Regression -> MSE: 0.000184, MAE: 0.008040, R²: -0.1061
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10886 | val 0.08103
  Epoch 020 - train 0.10088 | val 0.10102
  Epoch 021 - train 0.10112 | val 0.10155
  Regression -> MSE: 0.000242, MAE: 0.012091, R²: -0.0231
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09751 | val 0.13087
  Epoch 020 - train 0.09348 | val 0.13385
  Epoch 021 - train 0.10224 | val 0.13408
  Regression -> MSE: 0.000231, MAE: 0.009902, R²: -0.0005
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09945 | val 0.10274
  Epoch 020 - train 0.09314 | val 0.10602
  Epoch 021 - train 0.09607 | val 0.10586
  Regression -> MSE: 0.000136, MAE: 0.008269, R²: -0.0051
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09925 | val 0.10705
  Epoch 020 - train 0.09483 | val 0.10882
  Epoch 021 - train 0.09659 | val 0.10903
  Regression -> MSE: 0.000190, MAE: 0.010396, R²: -0.0108
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09081 | val 0.10682
  Epoch 020 - train 0.08385 | val 0.10416
  Epoch 021 - train 0.08676 | val 0.10568
  Regression -> MSE: 0.000263, MAE: 0.010699, R²: -0.0058
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08254 | val 0.07263
  Epoch 020 - train 0.08689 | val 0.06932
  Epoch 021 - train 0.08381 | val 0.06920
  Regression -> MSE: 0.000167, MAE: 0.010367, R²: -0.0033
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09711 | val 0.09302
  Epoch 020 - train 0.09083 | val 0.09698
  Epoch 021 - train 0.08859 | val 0.09668
  Regression -> MSE: 0.000190, MAE: 0.010685, R²: -0.0559
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09105 | val 0.07843
  Epoch 020 - train 0.08646 | val 0.07723
  Epoch 021 - train 0.08671 | val 0.07715
  Regression -> MSE: 0.000348, MAE: 0.011750, R²: -0.0167
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.09919 | val 0.05915
  Epoch 020 - train 0.09919 | val 0.06732
  Epoch 021 - train 0.09175 | val 0.06780
  Regression -> MSE: 0.000112, MAE: 0.008331, R²: -0.0620
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09275 | val 0.11146
  Epoch 020 - train 0.09146 | val 0.11203
  Epoch 021 - train 0.09545 | val 0.11205
  Regression -> MSE: 0.000219, MAE: 0.011285, R²: -0.0004
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.08548 | val 0.14810
  Epoch 020 - train 0.08901 | val 0.15762
  Epoch 021 - train 0.08844 | val 0.15748
  Regression -> MSE: 0.000081, MAE: 0.007026, R²: -0.0472
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08798 | val 0.06398
  Epoch 020 - train 0.08979 | val 0.06414
  Epoch 021 - train 0.08989 | val 0.06427
  Regression -> MSE: 0.000308, MAE: 0.013760, R²: -0.0018
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09891 | val 0.05696
  Epoch 020 - train 0.09379 | val 0.06267
  Epoch 021 - train 0.09961 | val 0.06376
  Regression -> MSE: 0.000256, MAE: 0.011471, R²: -0.0517
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09302 | val 0.09777
  Epoch 020 - train 0.08751 | val 0.09822
  Epoch 021 - train 0.08566 | val 0.09851
  Regression -> MSE: 0.000081, MAE: 0.007053, R²: -0.0008
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.09918 | val 0.10298
  Epoch 020 - train 0.09389 | val 0.10400
  Epoch 021 - train 0.08327 | val 0.10331
  Regression -> MSE: 0.000309, MAE: 0.014525, R²: -0.0078
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09976 | val 0.10405
  Epoch 020 - train 0.10238 | val 0.11317
  Epoch 021 - train 0.09499 | val 0.11379
  Regression -> MSE: 0.000104, MAE: 0.007112, R²: -0.0546
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10136 | val 0.09788
  Epoch 020 - train 0.10068 | val 0.09834
  Epoch 021 - train 0.10616 | val 0.09835
  Regression -> MSE: 0.000172, MAE: 0.009760, R²: -0.0016
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08760 | val 0.10120
  Epoch 020 - train 0.09073 | val 0.10398
  Epoch 021 - train 0.08502 | val 0.10507
  Regression -> MSE: 0.000225, MAE: 0.011748, R²: -0.0072
  Directional -> Accuracy: 0.6607, MCC: 0.3646, F1: 0.6122

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09337 | val 0.09346
  Epoch 020 - train 0.09104 | val 0.09606
  Epoch 021 - train 0.08726 | val 0.09647
  Regression -> MSE: 0.000093, MAE: 0.007674, R²: -0.0039

[I 2026-02-24 03:37:11,929] Trial 142 finished with value: -0.011441020479637512 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 1.2697328695346405e-05, 'weight_decay': 3.993976938217026e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.12100520715515056, 'early_stopping_min_delta': 0.0073412343494133805}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.10036 | val 0.11876
  Epoch 021 - train 0.10054 | val 0.11882
  Regression -> MSE: 0.000244, MAE: 0.012352, R²: -0.0302
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.08145 | val 0.09585
  Epoch 020 - train 0.07474 | val 0.09518
  Epoch 021 - train 0.07496 | val 0.09473
  Regression -> MSE: 0.000248, MAE: 0.012508, R²: -0.0010
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08946 | val 0.06694
  Epoch 020 - train 0.08522 | val 0.07158
  Epoch 021 - train 0.08048 | val 0.07161
  Regression -> MSE: 0.000715, MAE: 0.019870, R²: -0.0441
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07993 | val 0.11445
  Epoch 020 - train 0.08153 | val 0.11735
  Epoch 021 - train 0.07882 | val 0.11729
  Regression -> MSE: 0.000318, MAE: 0.014491, R²: -0.0254
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06446 | val 0.09414
  Epoch 020 - train 0.06389 | val 0.09790
  Epoch 021 - train 0.06625 | val 0.09728
  Regression -> MSE: 0.000358, MAE: 0.014720, R²: -0.0254
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.08312 | val 0.07274
  Epoch 020 - train 0.07866 | val 0.07490
  Epoch 021 - train 0.07868 | val 0.07568
  Regression -> MSE: 0.000205, MAE: 0.010068, R²: -0.0046
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07638 | val 0.12978
  Epoch 020 - train 0.07068 | val 0.13186
  Epoch 021 - train 0.07512 | val 0.13192
  Regression -> MSE: 0.000563, MAE: 0.018205, R²: -0.0144
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07755 | val 0.08850
  Epoch 020 - train 0.07972 | val 0.08700
  Epoch 021 - train 0.07971 | val 0.08707
  Regression -> MSE: 0.000246, MAE: 0.012103, R²: -0.0018
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07752 | val 0.09881
  Epoch 020 - train 0.07784 | val 0.09582
  Epoch 021 - train 0.07386 | val 0.09544
  Regression -> MSE: 0.000657, MAE: 0.020360, R²: -0.1001
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08260 | val 0.08806
  Epoch 020 - train 0.07547 | val 0.09062
  Epoch 021 - train 0.07459 | val 0.09046
  Regression -> MSE: 0.000386, MAE: 0.016117, R²: -0.0055
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07986 | val 0.09043
  Epoch 020 - train 0.07876 | val 0.09090
  Epoch 021 - train 0.07940 | val 0.09082
  Regression -> MSE: 0.000242, MAE: 0.012054, R²: -0.0020
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08017 | val 0.09841
  Epoch 020 - train 0.07587 | val 0.09865
  Epoch 021 - train 0.07326 | val 0.09891
  Regression -> MSE: 0.000320, MAE: 0.013590, R²: -0.0302
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08690 | val 0.08787
  Epoch 020 - train 0.07983 | val 0.08870
  Epoch 021 - train 0.08161 | val 0.08867
  Regression -> MSE: 0.000680, MAE: 0.019533, R²: -0.0047
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07710 | val 0.07305
  Epoch 020 - train 0.07782 | val 0.07648
  Epoch 021 - train 0.07650 | val 0.07682
  Regression -> MSE: 0.000139, MAE: 0.009035, R²: -0.0037
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.07509 | val 0.09957
  Epoch 020 - train 0.07202 | val 0.10031
  Epoch 021 - train 0.06978 | val 0.10048
  Regression -> MSE: 0.000225, MAE: 0.010721, R²: -0.0019
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08184 | val 0.14137
  Epoch 020 - train 0.07962 | val 0.14345
  Epoch 021 - train 0.08151 | val 0.14344
  Regression -> MSE: 0.000371, MAE: 0.015917, R²: -0.0252
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07791 | val 0.07578
  Epoch 020 - train 0.08032 | val 0.07676
  Epoch 021 - train 0.08306 | val 0.07683
  Regression -> MSE: 0.000108, MAE: 0.007913, R²: -0.0032
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07919 | val 0.11584
  Epoch 020 - train 0.07520 | val 0.12057
  Epoch 021 - train 0.07455 | val 0.12010
  Regression -> MSE: 0.000156, MAE: 0.009600, R²: -0.0018
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08738 | val 0.07794
  Epoch 020 - train 0.08086 | val 0.07818
  Epoch 021 - train 0.08285 | val 0.07824
  Regression -> MSE: 0.000290, MAE: 0.013830, R²: -0.0651
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07063 | val 0.09901
  Epoch 020 - train 0.06943 | val 0.09805
  Epoch 021 - train 0.06893 | val 0.09786
  Regression -> MSE: 0.000152, MAE: 0.008751, R²: -0.0175
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.08132 | val 0.10088
  Epoch 020 - train 0.08241 | val 0.10011
  Epoch 021 - train 0.08342 | val 0.10013
  Regression -> MSE: 0.000228, MAE: 0.011008, R²: -0.0062
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08425 | val 0.08794
  Epoch 020 - train 0.08352 | val 0.08890
  Epoch 021 - train 0.07977 | val 0.08875
  Regression -> MSE: 0.000153, MAE: 0.008812, R²: -0.0671
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07265 | val 0.08326
  Epoch 020 - train 0.07683 | val 0.08215
  Epoch 021 - train 0.07245 | val 0.08207
  Regression -> MSE: 0.000165, MAE: 0.010640, R²: -0.0013
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08579 | val 0.08117
  Epoch 020 - train 0.08123 | val 0.08103
  Epoch 021 - train 0.08164 | val 0.08103
  Regression -> MSE: 0.000093, MAE: 0.007464, R²: -0.0941
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.08191 | val 0.08677
  Epoch 020 - train 0.07763 | val 0.08707
  Epoch 021 - train 0.07491 | val 0.08628
  Regression -> MSE: 0.000213, MAE: 0.011338, R²: -0.0060
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07452 | val 0.06400
  Epoch 020 - train 0.07261 | val 0.06429
  Epoch 021 - train 0.07338 | val 0.06428
  Regression -> MSE: 0.000093, MAE: 0.008097, R²: -0.0098
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.08683 | val 0.05712
  Epoch 020 - train 0.08165 | val 0.05454
  Epoch 021 - train 0.08166 | val 0.05450
  Regression -> MSE: 0.000111, MAE: 0.009062, R²: -0.0759
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.08284 | val 0.07072
  Epoch 020 - train 0.08359 | val 0.07241
  Epoch 021 - train 0.08035 | val 0.07200
  Regression -> MSE: 0.000243, MAE: 0.012914, R²: -0.0497
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.08130 | val 0.08518
  Epoch 020 - train 0.08005 | val 0.08443
  Epoch 021 - train 0.07967 | val 0.08436
  Regression -> MSE: 0.000172, MAE: 0.007862, R²: -0.0342
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08166 | val 0.06079
  Epoch 020 - train 0.08089 | val 0.06173
  Epoch 021 - train 0.07679 | val 0.06214
  Regression -> MSE: 0.000237, MAE: 0.011866, R²: -0.0008
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.08383 | val 0.10881
  Epoch 020 - train 0.08617 | val 0.10711
  Epoch 021 - train 0.07226 | val 0.10677
  Regression -> MSE: 0.000232, MAE: 0.009982, R²: -0.0061
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07670 | val 0.08716
  Epoch 020 - train 0.08354 | val 0.07981
  Epoch 030 - train 0.08463 | val 0.08009
  Regression -> MSE: 0.000139, MAE: 0.008411, R²: -0.0283
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07272 | val 0.08927
  Epoch 020 - train 0.07897 | val 0.08901
  Epoch 021 - train 0.07569 | val 0.08904
  Regression -> MSE: 0.000188, MAE: 0.010465, R²: 0.0009
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07216 | val 0.08489
  Epoch 020 - train 0.06974 | val 0.08373
  Epoch 021 - train 0.07356 | val 0.08343
  Regression -> MSE: 0.000269, MAE: 0.010609, R²: -0.0279
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07062 | val 0.06330
  Epoch 020 - train 0.07576 | val 0.06350
  Epoch 021 - train 0.07799 | val 0.06341
  Regression -> MSE: 0.000168, MAE: 0.010374, R²: -0.0080
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.07793 | val 0.07025
  Epoch 020 - train 0.07914 | val 0.07130
  Epoch 021 - train 0.07499 | val 0.07131
  Regression -> MSE: 0.000182, MAE: 0.010343, R²: -0.0114
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07952 | val 0.06749
  Epoch 020 - train 0.07532 | val 0.06751
  Epoch 021 - train 0.07708 | val 0.06750
  Regression -> MSE: 0.000345, MAE: 0.012057, R²: -0.0067
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08761 | val 0.05419
  Epoch 020 - train 0.08898 | val 0.06489
  Epoch 021 - train 0.08775 | val 0.06464
  Regression -> MSE: 0.000107, MAE: 0.008355, R²: -0.0214
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.08262 | val 0.11116
  Epoch 020 - train 0.07647 | val 0.11686
  Epoch 021 - train 0.07383 | val 0.11584
  Regression -> MSE: 0.000220, MAE: 0.011333, R²: -0.0064
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07796 | val 0.12159
  Epoch 020 - train 0.08416 | val 0.12565
  Epoch 021 - train 0.08756 | val 0.12558
  Regression -> MSE: 0.000092, MAE: 0.007491, R²: -0.1828
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07495 | val 0.05511
  Epoch 020 - train 0.07950 | val 0.05632
  Epoch 021 - train 0.07363 | val 0.05651
  Regression -> MSE: 0.000312, MAE: 0.014091, R²: -0.0156
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.08386 | val 0.04445
  Epoch 020 - train 0.08543 | val 0.04435
  Epoch 021 - train 0.08766 | val 0.04437
  Regression -> MSE: 0.000249, MAE: 0.011507, R²: -0.0224
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08020 | val 0.09064
  Epoch 020 - train 0.07594 | val 0.09048
  Epoch 021 - train 0.07424 | val 0.09082
  Regression -> MSE: 0.000081, MAE: 0.007055, R²: -0.0076
  Directional -> Accuracy: 0.5333, MCC: 0.1182, F1: 0.6602

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.08138 | val 0.08577
  Epoch 020 - train 0.08230 | val 0.08838
  Epoch 021 - train 0.08432 | val 0.08850
  Regression -> MSE: 0.000310, MAE: 0.014522, R²: -0.0096
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07893 | val 0.07405
  Epoch 020 - train 0.07733 | val 0.07459
  Epoch 021 - train 0.07450 | val 0.07471
  Regression -> MSE: 0.000098, MAE: 0.007343, R²: 0.0009
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08379 | val 0.08221
  Epoch 020 - train 0.07580 | val 0.08453
  Epoch 021 - train 0.08501 | val 0.08487
  Regression -> MSE: 0.000173, MAE: 0.009878, R²: -0.0055
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08027 | val 0.07894
  Epoch 020 - train 0.07843 | val 0.08022
  Epoch 021 - train 0.07770 | val 0.08034
  Regression -> MSE: 0.000224, MAE: 0.011767, R²: -0.0045
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977


[I 2026-02-24 03:39:16,251] Trial 143 finished with value: -0.01146670170782153 and parameters: {'feature_set': 'emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 1.9511249333058415e-05, 'weight_decay': 3.33740855610992e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.1004339265445518, 'early_stopping_min_delta': 0.007208173900887234}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.07873 | val 0.10779
  Epoch 021 - train 0.07902 | val 0.10774
  Regression -> MSE: 0.000243, MAE: 0.012346, R²: -0.0232
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12807 | val 0.18897
  Epoch 020 - train 0.12913 | val 0.19053
  Epoch 021 - train 0.12885 | val 0.19159
  Regression -> MSE: 0.000267, MAE: 0.013183, R²: -0.0780
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12584 | val 0.12168
  Epoch 020 - train 0.13325 | val 0.15074
  Epoch 021 - train 0.13298 | val 0.15084
  Regression -> MSE: 0.000686, MAE: 0.019345, R²: -0.0015
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13644 | val 0.18568
  Epoch 020 - train 0.13340 | val 0.18775
  Epoch 021 - train 0.13463 | val 0.18768
  Regression -> MSE: 0.000310, MAE: 0.014417, R²: -0.0000
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11666 | val 0.11069
  Epoch 020 - train 0.12143 | val 0.11120
  Epoch 021 - train 0.11290 | val 0.11228
  Regression -> MSE: 0.000383, MAE: 0.015130, R²: -0.0959
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11984 | val 0.12388
  Epoch 020 - train 0.11927 | val 0.12664
  Epoch 021 - train 0.12420 | val 0.12640
  Regression -> MSE: 0.000205, MAE: 0.010333, R²: -0.0076
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12276 | val 0.21837
  Epoch 020 - train 0.11816 | val 0.26583
  Epoch 021 - train 0.12459 | val 0.26687
  Regression -> MSE: 0.000559, MAE: 0.018206, R²: -0.0064
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12909 | val 0.14393
  Epoch 020 - train 0.11680 | val 0.14306
  Epoch 021 - train 0.12777 | val 0.14283
  Regression -> MSE: 0.000246, MAE: 0.011970, R²: -0.0012
  Directional -> Accuracy: 0.4348, MCC: -0.0102, F1: 0.5412

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12659 | val 0.17517
  Epoch 020 - train 0.14067 | val 0.19785
  Epoch 021 - train 0.14355 | val 0.19798
  Regression -> MSE: 0.000682, MAE: 0.020731, R²: -0.1412
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12200 | val 0.13237
  Epoch 020 - train 0.12048 | val 0.13595
  Epoch 021 - train 0.12324 | val 0.13607
  Regression -> MSE: 0.000403, MAE: 0.016113, R²: -0.0516
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13170 | val 0.15745
  Epoch 020 - train 0.12111 | val 0.15741
  Epoch 021 - train 0.12998 | val 0.15710
  Regression -> MSE: 0.000242, MAE: 0.011858, R²: -0.0010
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12571 | val 0.15883
  Epoch 020 - train 0.12563 | val 0.15851
  Epoch 021 - train 0.11943 | val 0.15908
  Regression -> MSE: 0.000314, MAE: 0.013603, R²: -0.0094
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13610 | val 0.14783
  Epoch 020 - train 0.12878 | val 0.15612
  Epoch 021 - train 0.13179 | val 0.15508
  Regression -> MSE: 0.000679, MAE: 0.019544, R²: -0.0028
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12809 | val 0.10830
  Epoch 020 - train 0.12310 | val 0.10610
  Epoch 021 - train 0.11845 | val 0.10631
  Regression -> MSE: 0.000144, MAE: 0.009470, R²: -0.0413
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11189 | val 0.14361
  Epoch 020 - train 0.11539 | val 0.14421
  Epoch 021 - train 0.11604 | val 0.14421
  Regression -> MSE: 0.000225, MAE: 0.010699, R²: -0.0017
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12938 | val 0.24059
  Epoch 020 - train 0.12460 | val 0.24984
  Epoch 021 - train 0.12771 | val 0.24985
  Regression -> MSE: 0.000362, MAE: 0.016073, R²: 0.0007
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12155 | val 0.12060
  Epoch 020 - train 0.13693 | val 0.12040
  Epoch 021 - train 0.12469 | val 0.12095
  Regression -> MSE: 0.000108, MAE: 0.007979, R²: -0.0018
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12093 | val 0.19426
  Epoch 020 - train 0.11962 | val 0.20110
  Epoch 021 - train 0.11280 | val 0.20071
  Regression -> MSE: 0.000160, MAE: 0.010034, R²: -0.0235
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12557 | val 0.12149
  Epoch 020 - train 0.13527 | val 0.12087
  Epoch 021 - train 0.12662 | val 0.12169
  Regression -> MSE: 0.000276, MAE: 0.013275, R²: -0.0153
  Directional -> Accuracy: 0.5395, MCC: -0.1641, F1: 0.6957

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12029 | val 0.15536
  Epoch 020 - train 0.11538 | val 0.15481
  Epoch 021 - train 0.11858 | val 0.15476
  Regression -> MSE: 0.000156, MAE: 0.008798, R²: -0.0439
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13043 | val 0.16425
  Epoch 020 - train 0.12881 | val 0.16216
  Epoch 021 - train 0.12995 | val 0.16209
  Regression -> MSE: 0.000234, MAE: 0.010944, R²: -0.0343
  Directional -> Accuracy: 0.5067, MCC: 0.0573, F1: 0.4127

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13701 | val 0.14807
  Epoch 020 - train 0.13249 | val 0.15244
  Epoch 021 - train 0.13828 | val 0.15227
  Regression -> MSE: 0.000143, MAE: 0.008325, R²: -0.0009
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12537 | val 0.13254
  Epoch 020 - train 0.12985 | val 0.13175
  Epoch 021 - train 0.12135 | val 0.13163
  Regression -> MSE: 0.000179, MAE: 0.010310, R²: -0.0821
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13631 | val 0.13547
  Epoch 020 - train 0.12961 | val 0.13794
  Epoch 021 - train 0.13169 | val 0.13834
  Regression -> MSE: 0.000086, MAE: 0.007062, R²: -0.0045
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13390 | val 0.13717
  Epoch 020 - train 0.12671 | val 0.13735
  Epoch 021 - train 0.12783 | val 0.13736
  Regression -> MSE: 0.000212, MAE: 0.011100, R²: -0.0005
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12703 | val 0.10649
  Epoch 020 - train 0.12441 | val 0.10806
  Epoch 021 - train 0.12363 | val 0.10788
  Regression -> MSE: 0.000093, MAE: 0.008069, R²: -0.0122
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13749 | val 0.09479
  Epoch 020 - train 0.13297 | val 0.11227
  Epoch 021 - train 0.13018 | val 0.11476
  Regression -> MSE: 0.000111, MAE: 0.009061, R²: -0.0742
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12895 | val 0.11256
  Epoch 020 - train 0.13228 | val 0.11499
  Epoch 021 - train 0.13478 | val 0.11493
  Regression -> MSE: 0.000242, MAE: 0.012909, R²: -0.0475
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12440 | val 0.13487
  Epoch 020 - train 0.11653 | val 0.13437
  Epoch 021 - train 0.11814 | val 0.13405
  Regression -> MSE: 0.000175, MAE: 0.007881, R²: -0.0539
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13372 | val 0.09694
  Epoch 020 - train 0.12895 | val 0.09718
  Epoch 021 - train 0.13616 | val 0.09723
  Regression -> MSE: 0.000239, MAE: 0.011928, R²: -0.0088
  Directional -> Accuracy: 0.4878, MCC: 0.0317, F1: 0.2759

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13320 | val 0.17601
  Epoch 020 - train 0.13772 | val 0.18077
  Epoch 021 - train 0.13061 | val 0.18072
  Regression -> MSE: 0.000230, MAE: 0.009856, R²: 0.0023
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13341 | val 0.15241
  Epoch 020 - train 0.13122 | val 0.16045
  Epoch 021 - train 0.12832 | val 0.16095
  Regression -> MSE: 0.000145, MAE: 0.008737, R²: -0.0764
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13116 | val 0.14523
  Epoch 020 - train 0.13710 | val 0.14570
  Epoch 021 - train 0.12916 | val 0.14536
  Regression -> MSE: 0.000188, MAE: 0.010499, R²: -0.0007
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11623 | val 0.14454
  Epoch 020 - train 0.12226 | val 0.14291
  Epoch 021 - train 0.12050 | val 0.14281
  Regression -> MSE: 0.000263, MAE: 0.010547, R²: -0.0033
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13236 | val 0.09622
  Epoch 020 - train 0.13526 | val 0.10096
  Epoch 021 - train 0.13642 | val 0.10317
  Regression -> MSE: 0.000168, MAE: 0.010371, R²: -0.0063
  Directional -> Accuracy: 0.5789, MCC: 0.1615, F1: 0.6190

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12753 | val 0.12967
  Epoch 020 - train 0.12892 | val 0.13741
  Epoch 021 - train 0.11635 | val 0.13770
  Regression -> MSE: 0.000189, MAE: 0.010669, R²: -0.0506
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12200 | val 0.10907
  Epoch 020 - train 0.11908 | val 0.10863
  Epoch 021 - train 0.11624 | val 0.10884
  Regression -> MSE: 0.000345, MAE: 0.012037, R²: -0.0067
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13911 | val 0.07545
  Epoch 020 - train 0.13269 | val 0.07554
  Epoch 021 - train 0.12685 | val 0.07538
  Regression -> MSE: 0.000125, MAE: 0.008460, R²: -0.1915
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15620 | val 0.17594
  Epoch 020 - train 0.13704 | val 0.17986
  Epoch 021 - train 0.14513 | val 0.18248
  Regression -> MSE: 0.000225, MAE: 0.011481, R²: -0.0277
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13257 | val 0.18899
  Epoch 020 - train 0.12716 | val 0.19028
  Epoch 021 - train 0.12971 | val 0.19032
  Regression -> MSE: 0.000093, MAE: 0.007551, R²: -0.2029
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11830 | val 0.09224
  Epoch 020 - train 0.11700 | val 0.09221
  Epoch 021 - train 0.11370 | val 0.09188
  Regression -> MSE: 0.000323, MAE: 0.014651, R²: -0.0491
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12513 | val 0.07091
  Epoch 020 - train 0.13832 | val 0.07224
  Epoch 021 - train 0.13288 | val 0.07288
  Regression -> MSE: 0.000252, MAE: 0.011489, R²: -0.0347
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12618 | val 0.13486
  Epoch 020 - train 0.12544 | val 0.13458
  Epoch 021 - train 0.12380 | val 0.13424
  Regression -> MSE: 0.000081, MAE: 0.007048, R²: -0.0083
  Directional -> Accuracy: 0.6000, MCC: 0.2042, F1: 0.6250

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13649 | val 0.13852
  Epoch 020 - train 0.13691 | val 0.13733
  Epoch 021 - train 0.13586 | val 0.13723
  Regression -> MSE: 0.000309, MAE: 0.014521, R²: -0.0080
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14236 | val 0.12380
  Epoch 020 - train 0.12957 | val 0.12637
  Epoch 021 - train 0.12127 | val 0.12671
  Regression -> MSE: 0.000099, MAE: 0.007248, R²: -0.0033
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13115 | val 0.13524
  Epoch 020 - train 0.13959 | val 0.14333
  Epoch 021 - train 0.13865 | val 0.14415
  Regression -> MSE: 0.000173, MAE: 0.009914, R²: -0.0066
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12362 | val 0.13529
  Epoch 020 - train 0.12243 | val 0.13973
  Epoch 021 - train 0.11763 | val 0.13807
  Regression -> MSE: 0.000223, MAE: 0.011748, R²: -0.0013
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12544 | val 0.12475
  Epoch 020 - train 0.13049 | val 0.12634
  Epoch 021 - train 0.12714 | val 0.12681
  Regression -> MSE: 0.000093, MAE: 0.007631, R²: -0.0033

[I 2026-02-24 03:41:18,674] Trial 144 finished with value: -0.011493136008507505 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 1.0211635324064888e-05, 'weight_decay': 4.955226548890476e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.1688259702247779, 'early_stopping_min_delta': 0.006863835315151616}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.13174 | val 0.17134
  Epoch 021 - train 0.13243 | val 0.17076
  Regression -> MSE: 0.000237, MAE: 0.012392, R²: 0.0020
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.18599 | val 0.23641
  Epoch 020 - train 0.19892 | val 0.23734
  Epoch 021 - train 0.19699 | val 0.23641
  Regression -> MSE: 0.000252, MAE: 0.012718, R²: -0.0164
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.18446 | val 0.15579
  Epoch 020 - train 0.17219 | val 0.16598
  Epoch 021 - train 0.17925 | val 0.16501
  Regression -> MSE: 0.000710, MAE: 0.019782, R²: -0.0366
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.20279 | val 0.27984
  Epoch 020 - train 0.20579 | val 0.28856
  Epoch 021 - train 0.19634 | val 0.28898
  Regression -> MSE: 0.000321, MAE: 0.014503, R²: -0.0334
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15616 | val 0.13887
  Epoch 020 - train 0.15442 | val 0.14261
  Epoch 021 - train 0.15481 | val 0.14210
  Regression -> MSE: 0.000353, MAE: 0.014668, R²: -0.0118
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.17764 | val 0.15876
  Epoch 020 - train 0.17588 | val 0.15493
  Epoch 030 - train 0.17237 | val 0.15444
  Regression -> MSE: 0.000206, MAE: 0.010293, R²: -0.0111
  Directional -> Accuracy: 0.5294, MCC: 0.1007, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.16901 | val 0.31858
  Epoch 020 - train 0.17529 | val 0.33553
  Epoch 021 - train 0.19127 | val 0.33727
  Regression -> MSE: 0.000561, MAE: 0.018168, R²: -0.0100
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.18395 | val 0.20523
  Epoch 020 - train 0.17365 | val 0.20543
  Epoch 021 - train 0.18280 | val 0.20514
  Regression -> MSE: 0.000246, MAE: 0.012147, R²: -0.0011
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.18641 | val 0.25441
  Epoch 020 - train 0.19096 | val 0.29311
  Epoch 021 - train 0.16712 | val 0.29699
  Regression -> MSE: 0.000661, MAE: 0.020413, R²: -0.1071
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.18435 | val 0.20297
  Epoch 020 - train 0.18321 | val 0.19806
  Epoch 021 - train 0.18088 | val 0.19788
  Regression -> MSE: 0.000388, MAE: 0.016058, R²: -0.0113
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.18466 | val 0.22905
  Epoch 020 - train 0.18738 | val 0.23775
  Epoch 021 - train 0.18223 | val 0.24051
  Regression -> MSE: 0.000242, MAE: 0.011794, R²: -0.0007
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.18603 | val 0.25431
  Epoch 020 - train 0.17345 | val 0.26620
  Epoch 021 - train 0.16771 | val 0.26292
  Regression -> MSE: 0.000311, MAE: 0.013635, R²: -0.0001
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.19470 | val 0.22613
  Epoch 020 - train 0.18665 | val 0.23501
  Epoch 021 - train 0.18357 | val 0.23557
  Regression -> MSE: 0.000680, MAE: 0.019559, R²: -0.0043
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17521 | val 0.16583
  Epoch 020 - train 0.17141 | val 0.17225
  Epoch 021 - train 0.18575 | val 0.17310
  Regression -> MSE: 0.000142, MAE: 0.009379, R²: -0.0276
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.16687 | val 0.23676
  Epoch 020 - train 0.18577 | val 0.23654
  Epoch 021 - train 0.18177 | val 0.23675
  Regression -> MSE: 0.000225, MAE: 0.010684, R²: -0.0008
  Directional -> Accuracy: 0.5082, MCC: 0.0081, F1: 0.6250

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.17994 | val 0.37989
  Epoch 020 - train 0.18708 | val 0.42379
  Epoch 021 - train 0.19451 | val 0.42180
  Regression -> MSE: 0.000363, MAE: 0.016209, R²: -0.0030
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.18806 | val 0.17861
  Epoch 020 - train 0.19061 | val 0.17747
  Epoch 021 - train 0.19721 | val 0.17548
  Regression -> MSE: 0.000108, MAE: 0.008012, R²: -0.0019
  Directional -> Accuracy: 0.5000, MCC: -0.0516, F1: 0.6154

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.18458 | val 0.30279
  Epoch 020 - train 0.18118 | val 0.31092
  Epoch 021 - train 0.17000 | val 0.31156
  Regression -> MSE: 0.000157, MAE: 0.009750, R²: -0.0092
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.18309 | val 0.16618
  Epoch 020 - train 0.18246 | val 0.16605
  Epoch 021 - train 0.18049 | val 0.16603
  Regression -> MSE: 0.000272, MAE: 0.012977, R²: 0.0010
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.18757 | val 0.23643
  Epoch 020 - train 0.17629 | val 0.23236
  Epoch 021 - train 0.16424 | val 0.23268
  Regression -> MSE: 0.000153, MAE: 0.008726, R²: -0.0209
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.19792 | val 0.24394
  Epoch 020 - train 0.18894 | val 0.24164
  Epoch 021 - train 0.19208 | val 0.24199
  Regression -> MSE: 0.000227, MAE: 0.010986, R²: -0.0032
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17825 | val 0.20973
  Epoch 020 - train 0.18822 | val 0.21177
  Epoch 021 - train 0.18303 | val 0.21184
  Regression -> MSE: 0.000143, MAE: 0.008315, R²: 0.0028
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.17031 | val 0.18963
  Epoch 020 - train 0.16870 | val 0.18912
  Epoch 021 - train 0.15688 | val 0.18900
  Regression -> MSE: 0.000166, MAE: 0.010327, R²: -0.0065
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.18529 | val 0.19397
  Epoch 020 - train 0.19398 | val 0.19568
  Epoch 021 - train 0.19716 | val 0.19606
  Regression -> MSE: 0.000089, MAE: 0.007252, R²: -0.0447
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.19330 | val 0.23303
  Epoch 020 - train 0.18154 | val 0.24320
  Epoch 021 - train 0.19926 | val 0.24350
  Regression -> MSE: 0.000214, MAE: 0.011019, R²: -0.0096
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.17132 | val 0.16398
  Epoch 020 - train 0.18138 | val 0.16525
  Epoch 021 - train 0.18403 | val 0.16467
  Regression -> MSE: 0.000094, MAE: 0.008111, R²: -0.0236
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18151 | val 0.13414
  Epoch 020 - train 0.18493 | val 0.13500
  Epoch 021 - train 0.18760 | val 0.13588
  Regression -> MSE: 0.000114, MAE: 0.009177, R²: -0.1090
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.20461 | val 0.15952
  Epoch 020 - train 0.20656 | val 0.18218
  Epoch 021 - train 0.21472 | val 0.18174
  Regression -> MSE: 0.000232, MAE: 0.012489, R²: -0.0028
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.18671 | val 0.19855
  Epoch 020 - train 0.18474 | val 0.19945
  Epoch 021 - train 0.19788 | val 0.19910
  Regression -> MSE: 0.000177, MAE: 0.007904, R²: -0.0610
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.20232 | val 0.14774
  Epoch 020 - train 0.19184 | val 0.14541
  Epoch 021 - train 0.20104 | val 0.14516
  Regression -> MSE: 0.000240, MAE: 0.012004, R²: -0.0145
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.19104 | val 0.25982
  Epoch 020 - train 0.18948 | val 0.26317
  Epoch 021 - train 0.19394 | val 0.26324
  Regression -> MSE: 0.000232, MAE: 0.009896, R²: -0.0055
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.21366 | val 0.22365
  Epoch 020 - train 0.21458 | val 0.24180
  Epoch 021 - train 0.18819 | val 0.24219
  Regression -> MSE: 0.000143, MAE: 0.008644, R²: -0.0628
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.17677 | val 0.20748
  Epoch 020 - train 0.19368 | val 0.20966
  Epoch 021 - train 0.18392 | val 0.21003
  Regression -> MSE: 0.000201, MAE: 0.010741, R²: -0.0650
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.17910 | val 0.21212
  Epoch 020 - train 0.19130 | val 0.21333
  Epoch 021 - train 0.18020 | val 0.20971
  Regression -> MSE: 0.000267, MAE: 0.010556, R²: -0.0208
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16148 | val 0.13724
  Epoch 020 - train 0.17188 | val 0.14004
  Epoch 021 - train 0.18268 | val 0.14084
  Regression -> MSE: 0.000170, MAE: 0.010364, R²: -0.0196
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.18022 | val 0.17721
  Epoch 020 - train 0.15618 | val 0.18952
  Epoch 021 - train 0.17493 | val 0.18831
  Regression -> MSE: 0.000180, MAE: 0.010288, R²: -0.0017
  Directional -> Accuracy: 0.4091, MCC: -0.1923, F1: 0.5357

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16576 | val 0.15642
  Epoch 020 - train 0.17701 | val 0.15731
  Epoch 021 - train 0.17087 | val 0.15738
  Regression -> MSE: 0.000343, MAE: 0.011916, R²: -0.0014
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.17884 | val 0.10874
  Epoch 020 - train 0.20107 | val 0.11426
  Epoch 021 - train 0.17943 | val 0.11401
  Regression -> MSE: 0.000111, MAE: 0.008337, R²: -0.0532
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.18897 | val 0.22216
  Epoch 020 - train 0.18303 | val 0.22223
  Epoch 021 - train 0.18321 | val 0.22305
  Regression -> MSE: 0.000219, MAE: 0.011325, R²: -0.0032
  Directional -> Accuracy: 0.4737, MCC: -0.1700, F1: 0.0625

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.19958 | val 0.28594
  Epoch 020 - train 0.19675 | val 0.29953
  Epoch 021 - train 0.19690 | val 0.29997
  Regression -> MSE: 0.000096, MAE: 0.007636, R²: -0.2314
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.18454 | val 0.13893
  Epoch 020 - train 0.20790 | val 0.14163
  Epoch 021 - train 0.18212 | val 0.14183
  Regression -> MSE: 0.000329, MAE: 0.014937, R²: -0.0689
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.18682 | val 0.10075
  Epoch 020 - train 0.19789 | val 0.12099
  Epoch 021 - train 0.19717 | val 0.12393
  Regression -> MSE: 0.000248, MAE: 0.011508, R²: -0.0167
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.18881 | val 0.20999
  Epoch 020 - train 0.19606 | val 0.21050
  Epoch 021 - train 0.19365 | val 0.21030
  Regression -> MSE: 0.000086, MAE: 0.007072, R²: -0.0628
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.18466 | val 0.20591
  Epoch 020 - train 0.18649 | val 0.20332
  Epoch 021 - train 0.18221 | val 0.20370
  Regression -> MSE: 0.000307, MAE: 0.014486, R²: 0.0003
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.20435 | val 0.17335
  Epoch 020 - train 0.17787 | val 0.17172
  Epoch 021 - train 0.18371 | val 0.17151
  Regression -> MSE: 0.000099, MAE: 0.007397, R²: -0.0037
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.23675 | val 0.20799
  Epoch 020 - train 0.21263 | val 0.22787
  Epoch 021 - train 0.22112 | val 0.22780
  Regression -> MSE: 0.000175, MAE: 0.009427, R²: -0.0205
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.17076 | val 0.19675
  Epoch 020 - train 0.16679 | val 0.19886
  Epoch 021 - train 0.17313 | val 0.19856
  Regression -> MSE: 0.000223, MAE: 0.011735, R²: -0.0015
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977


[I 2026-02-24 03:43:22,782] Trial 145 finished with value: -0.011451485580294683 and parameters: {'feature_set': 'emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 1.5438728306794946e-05, 'weight_decay': 2.297133678926005e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2592129002871646, 'early_stopping_min_delta': 0.007976870627154476}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.19691 | val 0.25497
  Epoch 021 - train 0.18326 | val 0.25462
  Regression -> MSE: 0.000243, MAE: 0.012341, R²: -0.0241
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.40714 | val 0.61074
  Epoch 020 - train 0.40367 | val 0.62035
  Epoch 021 - train 0.40311 | val 0.61689
  Regression -> MSE: 0.000248, MAE: 0.012519, R²: -0.0011
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.40107 | val 0.36049
  Epoch 020 - train 0.42121 | val 0.36373
  Epoch 021 - train 0.38368 | val 0.36446
  Regression -> MSE: 0.000689, MAE: 0.019404, R²: -0.0060
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.38878 | val 0.69735
  Epoch 020 - train 0.40472 | val 0.70123
  Epoch 021 - train 0.41595 | val 0.70172
  Regression -> MSE: 0.000317, MAE: 0.014486, R²: -0.0226
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.34699 | val 0.39660
  Epoch 020 - train 0.33566 | val 0.41199
  Epoch 021 - train 0.36239 | val 0.41174
  Regression -> MSE: 0.000366, MAE: 0.014855, R²: -0.0483
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.39980 | val 0.44538
  Epoch 020 - train 0.41450 | val 0.48828
  Epoch 021 - train 0.39146 | val 0.48508
  Regression -> MSE: 0.000204, MAE: 0.010212, R²: -0.0035
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.43049 | val 0.79114
  Epoch 020 - train 0.42726 | val 0.78888
  Epoch 029 - train 0.40248 | val 0.79212
  Regression -> MSE: 0.000551, MAE: 0.018088, R²: 0.0080
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.40497 | val 0.49906
  Epoch 020 - train 0.40357 | val 0.50003
  Epoch 021 - train 0.40704 | val 0.49886
  Regression -> MSE: 0.000251, MAE: 0.011953, R²: -0.0224
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.39722 | val 0.55624
  Epoch 020 - train 0.36449 | val 0.59076
  Epoch 021 - train 0.39734 | val 0.58913
  Regression -> MSE: 0.000640, MAE: 0.020081, R²: -0.0706
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.38289 | val 0.46962
  Epoch 020 - train 0.37370 | val 0.45442
  Epoch 030 - train 0.40901 | val 0.45427
  Regression -> MSE: 0.000442, MAE: 0.016850, R²: -0.1513
  Directional -> Accuracy: 0.4898, MCC: -0.1103, F1: 0.1935

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.42858 | val 0.50377
  Epoch 020 - train 0.40653 | val 0.49909
  Epoch 021 - train 0.42617 | val 0.49977
  Regression -> MSE: 0.000242, MAE: 0.011760, R²: -0.0027
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.37189 | val 0.59203
  Epoch 020 - train 0.38757 | val 0.59559
  Epoch 021 - train 0.36620 | val 0.60008
  Regression -> MSE: 0.000310, MAE: 0.013653, R²: 0.0034
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.43250 | val 0.47084
  Epoch 020 - train 0.42406 | val 0.48088
  Epoch 021 - train 0.41046 | val 0.48398
  Regression -> MSE: 0.000680, MAE: 0.019572, R²: -0.0039
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.42282 | val 0.37828
  Epoch 020 - train 0.46045 | val 0.35887
  Epoch 030 - train 0.42878 | val 0.35968
  Regression -> MSE: 0.000148, MAE: 0.009534, R²: -0.0701
  Directional -> Accuracy: 0.5349, MCC: 0.0905, F1: 0.5455

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.39071 | val 0.63096
  Epoch 020 - train 0.41228 | val 0.64824
  Epoch 021 - train 0.42079 | val 0.64853
  Regression -> MSE: 0.000226, MAE: 0.010891, R²: -0.0064
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.43136 | val 0.92560
  Epoch 020 - train 0.42375 | val 0.96978
  Epoch 021 - train 0.43462 | val 0.97274
  Regression -> MSE: 0.000364, MAE: 0.016020, R²: -0.0054
  Directional -> Accuracy: 0.4423, MCC: -0.1028, F1: 0.4727

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.41915 | val 0.41799
  Epoch 020 - train 0.41104 | val 0.41907
  Epoch 021 - train 0.40022 | val 0.41737
  Regression -> MSE: 0.000108, MAE: 0.008008, R²: -0.0021
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.39830 | val 0.69881
  Epoch 020 - train 0.40033 | val 0.70586
  Epoch 021 - train 0.38729 | val 0.70566
  Regression -> MSE: 0.000162, MAE: 0.010182, R²: -0.0383
  Directional -> Accuracy: 0.3220, MCC: -0.2608, F1: 0.1667

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48144 | val 0.49662
  Epoch 020 - train 0.42124 | val 0.50019
  Epoch 021 - train 0.43995 | val 0.49405
  Regression -> MSE: 0.000274, MAE: 0.012941, R²: -0.0054
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.43287 | val 0.71928
  Epoch 020 - train 0.40593 | val 0.70208
  Epoch 021 - train 0.41547 | val 0.70445
  Regression -> MSE: 0.000151, MAE: 0.008838, R²: -0.0078
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.43517 | val 0.63461
  Epoch 020 - train 0.41946 | val 0.63929
  Epoch 021 - train 0.42566 | val 0.63475
  Regression -> MSE: 0.000252, MAE: 0.011356, R²: -0.1155
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.44638 | val 0.55162
  Epoch 020 - train 0.41916 | val 0.56933
  Epoch 021 - train 0.42999 | val 0.57727
  Regression -> MSE: 0.000144, MAE: 0.008349, R²: -0.0041
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.36326 | val 0.51336
  Epoch 020 - train 0.38469 | val 0.51788
  Epoch 021 - train 0.35578 | val 0.51642
  Regression -> MSE: 0.000168, MAE: 0.010265, R²: -0.0141
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.41012 | val 0.50519
  Epoch 020 - train 0.42080 | val 0.51267
  Epoch 021 - train 0.41067 | val 0.51150
  Regression -> MSE: 0.000088, MAE: 0.007194, R²: -0.0314
  Directional -> Accuracy: 0.4138, MCC: -0.1741, F1: 0.4516

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.43479 | val 0.58919
  Epoch 020 - train 0.42778 | val 0.62610
  Epoch 021 - train 0.41398 | val 0.61324
  Regression -> MSE: 0.000215, MAE: 0.011049, R²: -0.0146
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.35044 | val 0.33100
  Epoch 020 - train 0.37656 | val 0.33461
  Epoch 021 - train 0.38812 | val 0.33481
  Regression -> MSE: 0.000093, MAE: 0.008112, R²: -0.0114
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.42704 | val 0.27152
  Epoch 020 - train 0.39021 | val 0.26792
  Epoch 021 - train 0.45205 | val 0.26950
  Regression -> MSE: 0.000106, MAE: 0.008883, R²: -0.0251
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.42093 | val 0.37644
  Epoch 020 - train 0.42427 | val 0.44817
  Epoch 021 - train 0.41333 | val 0.44208
  Regression -> MSE: 0.000239, MAE: 0.012804, R²: -0.0325
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.39797 | val 0.49881
  Epoch 020 - train 0.43608 | val 0.51601
  Epoch 021 - train 0.38152 | val 0.51267
  Regression -> MSE: 0.000176, MAE: 0.007899, R²: -0.0563
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.42716 | val 0.30600
  Epoch 020 - train 0.43882 | val 0.33356
  Epoch 021 - train 0.41708 | val 0.33737
  Regression -> MSE: 0.000239, MAE: 0.011966, R²: -0.0099
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.41848 | val 0.66427
  Epoch 020 - train 0.39132 | val 0.66920
  Epoch 021 - train 0.36106 | val 0.66954
  Regression -> MSE: 0.000231, MAE: 0.009872, R²: -0.0014
  Directional -> Accuracy: 0.4884, MCC: -0.0849, F1: 0.0833

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.40758 | val 0.45074
  Epoch 020 - train 0.42564 | val 0.45233
  Epoch 021 - train 0.43293 | val 0.45290
  Regression -> MSE: 0.000135, MAE: 0.008186, R²: 0.0032
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.42183 | val 0.51732
  Epoch 020 - train 0.39401 | val 0.54036
  Epoch 021 - train 0.37496 | val 0.53975
  Regression -> MSE: 0.000189, MAE: 0.010401, R²: -0.0034
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.38864 | val 0.60489
  Epoch 020 - train 0.41482 | val 0.60170
  Epoch 021 - train 0.42299 | val 0.59156
  Regression -> MSE: 0.000263, MAE: 0.010566, R²: -0.0042
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.42379 | val 0.32614
  Epoch 020 - train 0.41225 | val 0.33458
  Epoch 021 - train 0.44369 | val 0.33759
  Regression -> MSE: 0.000170, MAE: 0.010380, R²: -0.0192
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.38481 | val 0.38951
  Epoch 020 - train 0.35399 | val 0.40081
  Epoch 021 - train 0.40902 | val 0.40102
  Regression -> MSE: 0.000180, MAE: 0.010290, R²: -0.0028
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.46302 | val 0.37195
  Epoch 020 - train 0.42665 | val 0.36815
  Epoch 021 - train 0.43015 | val 0.36777
  Regression -> MSE: 0.000348, MAE: 0.011747, R²: -0.0155
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.43347 | val 0.21163
  Epoch 020 - train 0.42839 | val 0.21921
  Epoch 021 - train 0.41386 | val 0.22116
  Regression -> MSE: 0.000124, MAE: 0.008432, R²: -0.1759
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.40174 | val 0.56330
  Epoch 020 - train 0.42158 | val 0.57284
  Epoch 021 - train 0.41325 | val 0.57064
  Regression -> MSE: 0.000219, MAE: 0.011289, R²: -0.0008
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.46780 | val 0.77285
  Epoch 020 - train 0.44602 | val 0.84004
  Epoch 021 - train 0.46542 | val 0.84264
  Regression -> MSE: 0.000099, MAE: 0.007760, R²: -0.2740
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.39552 | val 0.25994
  Epoch 020 - train 0.42327 | val 0.27499
  Epoch 021 - train 0.40679 | val 0.27605
  Regression -> MSE: 0.000313, MAE: 0.014138, R²: -0.0176
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.48200 | val 0.19543
  Epoch 020 - train 0.42315 | val 0.20193
  Epoch 021 - train 0.45639 | val 0.20393
  Regression -> MSE: 0.000257, MAE: 0.011481, R²: -0.0555
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.41231 | val 0.49220
  Epoch 020 - train 0.40500 | val 0.49425
  Epoch 021 - train 0.39887 | val 0.49352
  Regression -> MSE: 0.000085, MAE: 0.007056, R²: -0.0503
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.41662 | val 0.49521
  Epoch 020 - train 0.40793 | val 0.45949
  Epoch 030 - train 0.41243 | val 0.45765
  Regression -> MSE: 0.000314, MAE: 0.014542, R²: -0.0250
  Directional -> Accuracy: 0.4255, MCC: -0.1723, F1: 0.5263

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.36041 | val 0.40927
  Epoch 020 - train 0.39991 | val 0.39821
  Epoch 030 - train 0.38349 | val 0.39258
  Regression -> MSE: 0.000096, MAE: 0.007365, R²: 0.0197
  Directional -> Accuracy: 0.5000, MCC: 0.1008, F1: 0.3529

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.44651 | val 0.49249
  Epoch 020 - train 0.41088 | val 0.48131
  Epoch 030 - train 0.45867 | val 0.48756
  Regression -> MSE: 0.000189, MAE: 0.009578, R²: -0.1027
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.36515 | val 0.46390
  Epoch 020 - train 0.38387 | val 0.48031
  Epoch 021 - train 0.40997 | val 0.48338
  Regression -> MSE: 0.000226, MAE: 0.011772, R²: -0.0116
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.41949 | val 0.44028
  Epoch 020 - train 0.36861 | val 0.44668
  Epoch 021 - train 0.40426 | val 0.44536
  Regression -> MSE: 0.000093, MAE: 0.007650, R²: -0.0089

[I 2026-02-24 03:45:29,049] Trial 146 finished with value: -0.011439726160112209 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 6.490679507260607e-06, 'weight_decay': 6.196562474605496e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.8290128919594089, 'early_stopping_min_delta': 0.008384245284949587}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.41057 | val 0.88422
  Epoch 021 - train 0.40598 | val 0.88619
  Regression -> MSE: 0.000237, MAE: 0.012463, R²: 0.0000
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09490 | val 0.12468
  Epoch 020 - train 0.09328 | val 0.12419
  Regression -> MSE: 0.000248, MAE: 0.012541, R²: -0.0023
  Directional -> Accuracy: 0.5325, MCC: -0.0165, F1: 0.1429

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09028 | val 0.09228
  Epoch 020 - train 0.09247 | val 0.10357
  Regression -> MSE: 0.000708, MAE: 0.019775, R²: -0.0345
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09970 | val 0.15684
  Epoch 020 - train 0.09701 | val 0.15980
  Regression -> MSE: 0.000310, MAE: 0.014443, R²: -0.0008
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08091 | val 0.08881
  Epoch 020 - train 0.07929 | val 0.09118
  Regression -> MSE: 0.000373, MAE: 0.014962, R²: -0.0674
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09192 | val 0.09377
  Epoch 020 - train 0.09333 | val 0.09364
  Regression -> MSE: 0.000204, MAE: 0.010021, R²: -0.0032
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08970 | val 0.17219
  Epoch 020 - train 0.08929 | val 0.19533
  Regression -> MSE: 0.000587, MAE: 0.018724, R²: -0.0575
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09425 | val 0.11882
  Epoch 020 - train 0.09481 | val 0.11927
  Regression -> MSE: 0.000245, MAE: 0.012010, R²: 0.0021
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09639 | val 0.12625
  Epoch 020 - train 0.09360 | val 0.15133
  Regression -> MSE: 0.000621, MAE: 0.019707, R²: -0.0392
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09124 | val 0.11262
  Epoch 020 - train 0.08651 | val 0.11199
  Regression -> MSE: 0.000396, MAE: 0.015994, R²: -0.0328
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09510 | val 0.13129
  Epoch 020 - train 0.09422 | val 0.12936
  Regression -> MSE: 0.000244, MAE: 0.012236, R²: -0.0098
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08310 | val 0.14590
  Epoch 020 - train 0.08365 | val 0.14994
  Regression -> MSE: 0.000311, MAE: 0.013657, R²: 0.0008
  Directional -> Accuracy: 0.4400, MCC: -0.0902, F1: 0.5758

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09579 | val 0.11065
  Epoch 020 - train 0.09500 | val 0.11112
  Regression -> MSE: 0.000680, MAE: 0.019492, R²: -0.0040
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09504 | val 0.09817
  Epoch 020 - train 0.09248 | val 0.10213
  Regression -> MSE: 0.000139, MAE: 0.009224, R²: -0.0074
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08899 | val 0.13679
  Epoch 020 - train 0.08927 | val 0.13784
  Regression -> MSE: 0.000225, MAE: 0.010698, R²: -0.0008
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09291 | val 0.19078
  Epoch 020 - train 0.09091 | val 0.19191
  Regression -> MSE: 0.000361, MAE: 0.016032, R²: 0.0022
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09692 | val 0.10352
  Epoch 020 - train 0.09504 | val 0.10552
  Regression -> MSE: 0.000108, MAE: 0.007941, R²: 0.0010
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09368 | val 0.16318
  Epoch 020 - train 0.09252 | val 0.17105
  Regression -> MSE: 0.000158, MAE: 0.009919, R²: -0.0117
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09682 | val 0.09922
  Epoch 020 - train 0.09506 | val 0.09924
  Regression -> MSE: 0.000288, MAE: 0.013769, R²: -0.0596
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08570 | val 0.13276
  Epoch 020 - train 0.08699 | val 0.13160
  Regression -> MSE: 0.000156, MAE: 0.008788, R²: -0.0397
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09766 | val 0.13494
  Epoch 020 - train 0.09585 | val 0.13755
  Regression -> MSE: 0.000244, MAE: 0.011161, R²: -0.0792
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09576 | val 0.11920
  Epoch 020 - train 0.09461 | val 0.12229
  Regression -> MSE: 0.000144, MAE: 0.008339, R²: -0.0057
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09148 | val 0.11603
  Epoch 020 - train 0.09040 | val 0.11555
  Regression -> MSE: 0.000170, MAE: 0.010254, R²: -0.0293
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09676 | val 0.11605
  Epoch 020 - train 0.09519 | val 0.11888
  Regression -> MSE: 0.000093, MAE: 0.007429, R²: -0.0864
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09270 | val 0.13460
  Epoch 020 - train 0.09153 | val 0.12945
  Regression -> MSE: 0.000213, MAE: 0.011285, R²: -0.0064
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08887 | val 0.08707
  Epoch 020 - train 0.08905 | val 0.08824
  Regression -> MSE: 0.000097, MAE: 0.008135, R²: -0.0505
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09475 | val 0.08524
  Epoch 020 - train 0.09212 | val 0.09116
  Regression -> MSE: 0.000118, MAE: 0.009263, R²: -0.1433
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09557 | val 0.09114
  Epoch 020 - train 0.09288 | val 0.09215
  Regression -> MSE: 0.000243, MAE: 0.012909, R²: -0.0487
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09442 | val 0.11873
  Epoch 020 - train 0.09298 | val 0.11886
  Regression -> MSE: 0.000169, MAE: 0.007796, R²: -0.0149
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09610 | val 0.08341
  Epoch 020 - train 0.09796 | val 0.08919
  Regression -> MSE: 0.000237, MAE: 0.011868, R²: -0.0004
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09769 | val 0.15705
  Epoch 020 - train 0.09971 | val 0.16514
  Regression -> MSE: 0.000237, MAE: 0.010276, R²: -0.0277
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09688 | val 0.11733
  Epoch 020 - train 0.09783 | val 0.12738
  Regression -> MSE: 0.000136, MAE: 0.008239, R²: -0.0044
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09354 | val 0.11825
  Epoch 020 - train 0.09234 | val 0.11898
  Regression -> MSE: 0.000189, MAE: 0.010420, R²: -0.0015
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09024 | val 0.13518
  Epoch 020 - train 0.08879 | val 0.13613
  Regression -> MSE: 0.000272, MAE: 0.010665, R²: -0.0369
  Directional -> Accuracy: 0.4247, MCC: -0.1536, F1: 0.4615

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08753 | val 0.08275
  Epoch 020 - train 0.08752 | val 0.08066
  Regression -> MSE: 0.000167, MAE: 0.010367, R²: -0.0017
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08728 | val 0.09431
  Epoch 020 - train 0.08641 | val 0.09678
  Regression -> MSE: 0.000180, MAE: 0.010252, R²: -0.0002
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.08881 | val 0.08891
  Epoch 020 - train 0.08930 | val 0.08999
  Regression -> MSE: 0.000342, MAE: 0.011861, R²: 0.0033
  Directional -> Accuracy: 0.4179, MCC: -0.0955, F1: 0.1333

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10066 | val 0.06408
  Epoch 020 - train 0.10016 | val 0.06449
  Regression -> MSE: 0.000115, MAE: 0.008341, R²: -0.0967
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09350 | val 0.13346
  Epoch 020 - train 0.09172 | val 0.13469
  Regression -> MSE: 0.000221, MAE: 0.011367, R²: -0.0112
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09829 | val 0.15794
  Epoch 020 - train 0.09321 | val 0.15818
  Regression -> MSE: 0.000097, MAE: 0.007694, R²: -0.2528
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09328 | val 0.07499
  Epoch 020 - train 0.09349 | val 0.08201
  Regression -> MSE: 0.000312, MAE: 0.014122, R²: -0.0155
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10244 | val 0.05844
  Epoch 020 - train 0.09861 | val 0.06037
  Regression -> MSE: 0.000246, MAE: 0.011560, R²: -0.0097
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09027 | val 0.11804
  Epoch 020 - train 0.08970 | val 0.11896
  Regression -> MSE: 0.000083, MAE: 0.007049, R²: -0.0332
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.09416 | val 0.11847
  Epoch 020 - train 0.09218 | val 0.11652
  Regression -> MSE: 0.000307, MAE: 0.014494, R²: -0.0001
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09735 | val 0.10824
  Epoch 020 - train 0.09374 | val 0.10578
  Regression -> MSE: 0.000100, MAE: 0.007126, R²: -0.0219
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10482 | val 0.11105
  Epoch 020 - train 0.10172 | val 0.10830
  Regression -> MSE: 0.000175, MAE: 0.010118, R²: -0.0167
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08690 | val 0.11146
  Epoch 020 - train 0.08722 | val 0.11105
  Regression -> MSE: 0.000223, MAE: 0.011785, R²: -0.0011
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09517 | val 0.10771
  Epoch 020 - train 0.09226 | val 0.10880
  Regression -> MSE: 0.000096, MAE: 0.007901, R²: -0.0405
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.10538 | val 0.14755
  Epoch 020 - train 0.10547 | val 0.15047
  Regression -> MSE: 0.000165, MAE: 0.010310, R²: -0.0069
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10123 | val 0.12154
  Epoch 020 - train 0.09794 | val 0.12324
  Regression -> MSE: 0.000129, MAE: 0.009073, R²: -0.1142
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.09698 | val 0.13879

[I 2026-02-24 03:47:28,134] Trial 147 finished with value: -0.011474568843139776 and parameters: {'feature_set': 'emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 9.117822748232305e-06, 'weight_decay': 2.97915039319602e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.13860293356440123, 'early_stopping_min_delta': 0.008806959752745811}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.09530 | val 0.14459
  Regression -> MSE: 0.000238, MAE: 0.012337, R²: -0.0032
  Directional -> Accuracy: 0.5738, MCC: 0.1593, F1: 0.3158

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12760 | val 0.19365
  Epoch 020 - train 0.11891 | val 0.21408
  Epoch 021 - train 0.11897 | val 0.21560
  Regression -> MSE: 0.000248, MAE: 0.012547, R²: -0.0009
  Directional -> Accuracy: 0.5584, MCC: 0.0778, F1: 0.3200

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13155 | val 0.12959
  Epoch 020 - train 0.12399 | val 0.14091
  Epoch 021 - train 0.12145 | val 0.14019
  Regression -> MSE: 0.000702, MAE: 0.019667, R²: -0.0257
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12847 | val 0.20930
  Epoch 020 - train 0.12908 | val 0.20789
  Epoch 021 - train 0.12819 | val 0.20751
  Regression -> MSE: 0.000316, MAE: 0.014430, R²: -0.0181
  Directional -> Accuracy: 0.5532, MCC: 0.1340, F1: 0.4878

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11193 | val 0.53927
  Epoch 020 - train 0.10817 | val 0.51637
  Epoch 021 - train 0.10403 | val 0.51137
  Regression -> MSE: 0.000499, MAE: 0.018003, R²: -0.4284
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13002 | val 0.16964
  Epoch 020 - train 0.11953 | val 0.17359
  Epoch 021 - train 0.12286 | val 0.17313
  Regression -> MSE: 0.000204, MAE: 0.010166, R²: 0.0003
  Directional -> Accuracy: 0.4902, MCC: 0.0687, F1: 0.1333

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12263 | val 0.23673
  Epoch 020 - train 0.11056 | val 0.24090
  Epoch 021 - train 0.10824 | val 0.24038
  Regression -> MSE: 0.000586, MAE: 0.018679, R²: -0.0558
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13255 | val 0.17157
  Epoch 020 - train 0.13221 | val 0.16876
  Epoch 021 - train 0.12852 | val 0.16822
  Regression -> MSE: 0.000248, MAE: 0.011903, R²: -0.0106
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14304 | val 0.14529
  Epoch 020 - train 0.12700 | val 0.15513
  Epoch 027 - train 0.12443 | val 0.16105
  Regression -> MSE: 0.000606, MAE: 0.019205, R²: -0.0146
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12876 | val 0.17243
  Epoch 020 - train 0.12106 | val 0.16798
  Epoch 021 - train 0.11815 | val 0.16764
  Regression -> MSE: 0.000383, MAE: 0.016151, R²: 0.0003
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13171 | val 0.16427
  Epoch 020 - train 0.12179 | val 0.16638
  Epoch 021 - train 0.12831 | val 0.16661
  Regression -> MSE: 0.000241, MAE: 0.011881, R²: 0.0001
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12424 | val 0.24448
  Epoch 020 - train 0.11100 | val 0.28539
  Epoch 021 - train 0.11485 | val 0.29026
  Regression -> MSE: 0.000319, MAE: 0.013551, R²: -0.0272
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14214 | val 0.21437
  Epoch 020 - train 0.12582 | val 0.18594
  Epoch 021 - train 0.13081 | val 0.18366
  Regression -> MSE: 0.000693, MAE: 0.019816, R²: -0.0237
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12624 | val 0.26240
  Epoch 020 - train 0.11453 | val 0.29344
  Epoch 021 - train 0.12858 | val 0.28598
  Regression -> MSE: 0.000142, MAE: 0.009372, R²: -0.0282
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11906 | val 0.19318
  Epoch 020 - train 0.11390 | val 0.18151
  Epoch 021 - train 0.11085 | val 0.18075
  Regression -> MSE: 0.000230, MAE: 0.010972, R²: -0.0221
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12523 | val 0.27486
  Epoch 020 - train 0.12496 | val 0.27833
  Epoch 021 - train 0.12051 | val 0.28050
  Regression -> MSE: 0.000361, MAE: 0.016027, R²: 0.0032
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13888 | val 0.14546
  Epoch 020 - train 0.13144 | val 0.14245
  Epoch 021 - train 0.13227 | val 0.14238
  Regression -> MSE: 0.000113, MAE: 0.008354, R²: -0.0510
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12902 | val 0.33670
  Epoch 020 - train 0.12144 | val 0.35113
  Epoch 021 - train 0.11925 | val 0.35180
  Regression -> MSE: 0.000158, MAE: 0.009950, R²: -0.0137
  Directional -> Accuracy: 0.6441, MCC: 0.1703, F1: 0.7789

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12418 | val 0.12875
  Epoch 020 - train 0.12387 | val 0.12798
  Epoch 021 - train 0.12356 | val 0.12799
  Regression -> MSE: 0.000271, MAE: 0.012962, R²: 0.0059
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10989 | val 0.17300
  Epoch 020 - train 0.11034 | val 0.17583
  Epoch 021 - train 0.10812 | val 0.17630
  Regression -> MSE: 0.000164, MAE: 0.009047, R²: -0.0979
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12546 | val 0.20600
  Epoch 020 - train 0.12346 | val 0.19178
  Epoch 021 - train 0.12851 | val 0.19102
  Regression -> MSE: 0.000277, MAE: 0.011967, R²: -0.2259
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12207 | val 0.17031
  Epoch 020 - train 0.13042 | val 0.17478
  Epoch 021 - train 0.12416 | val 0.17411
  Regression -> MSE: 0.000151, MAE: 0.008710, R²: -0.0539
  Directional -> Accuracy: 0.5833, MCC: 0.1511, F1: 0.6429

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12321 | val 0.17196
  Epoch 020 - train 0.12322 | val 0.17646
  Epoch 021 - train 0.12007 | val 0.17618
  Regression -> MSE: 0.000166, MAE: 0.010345, R²: -0.0065
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13236 | val 0.16838
  Epoch 020 - train 0.12712 | val 0.16669
  Epoch 021 - train 0.13434 | val 0.16596
  Regression -> MSE: 0.000086, MAE: 0.007097, R²: -0.0119
  Directional -> Accuracy: 0.5862, MCC: 0.1111, F1: 0.7273

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12164 | val 0.25596
  Epoch 020 - train 0.12331 | val 0.25940
  Epoch 021 - train 0.12368 | val 0.26645
  Regression -> MSE: 0.000216, MAE: 0.011529, R²: -0.0188
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11644 | val 0.10779
  Epoch 020 - train 0.10944 | val 0.10416
  Epoch 029 - train 0.10921 | val 0.10263
  Regression -> MSE: 0.000126, MAE: 0.009193, R²: -0.3640
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13983 | val 0.10423
  Epoch 020 - train 0.12495 | val 0.10738
  Epoch 021 - train 0.12652 | val 0.10760
  Regression -> MSE: 0.000111, MAE: 0.009069, R²: -0.0796
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13823 | val 0.14395
  Epoch 020 - train 0.12754 | val 0.15210
  Epoch 021 - train 0.12785 | val 0.15401
  Regression -> MSE: 0.000234, MAE: 0.012675, R²: -0.0120
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12628 | val 0.15958
  Epoch 020 - train 0.12197 | val 0.15742
  Epoch 021 - train 0.12229 | val 0.15738
  Regression -> MSE: 0.000171, MAE: 0.007868, R²: -0.0288
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14216 | val 0.12692
  Epoch 020 - train 0.12897 | val 0.13484
  Epoch 021 - train 0.13407 | val 0.13532
  Regression -> MSE: 0.000243, MAE: 0.012140, R²: -0.0253
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12254 | val 0.20358
  Epoch 020 - train 0.12524 | val 0.20719
  Epoch 021 - train 0.11392 | val 0.20733
  Regression -> MSE: 0.000233, MAE: 0.010042, R²: -0.0112
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13477 | val 0.16711
  Epoch 020 - train 0.13658 | val 0.16676
  Epoch 021 - train 0.13128 | val 0.16716
  Regression -> MSE: 0.000134, MAE: 0.008155, R²: 0.0065
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13355 | val 0.16010
  Epoch 020 - train 0.12936 | val 0.16401
  Epoch 021 - train 0.12374 | val 0.16443
  Regression -> MSE: 0.000189, MAE: 0.010407, R²: -0.0053
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11510 | val 0.15526
  Epoch 020 - train 0.11001 | val 0.14947
  Epoch 021 - train 0.10932 | val 0.14926
  Regression -> MSE: 0.000269, MAE: 0.010721, R²: -0.0264
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12880 | val 0.12121
  Epoch 020 - train 0.11526 | val 0.10965
  Epoch 021 - train 0.12860 | val 0.10955
  Regression -> MSE: 0.000168, MAE: 0.010355, R²: -0.0099
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11266 | val 0.13633
  Epoch 020 - train 0.11198 | val 0.13924
  Epoch 021 - train 0.11118 | val 0.13933
  Regression -> MSE: 0.000183, MAE: 0.010373, R²: -0.0154
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11758 | val 0.12091
  Epoch 020 - train 0.12088 | val 0.11961
  Epoch 021 - train 0.11400 | val 0.11946
  Regression -> MSE: 0.000338, MAE: 0.012031, R²: 0.0128
  Directional -> Accuracy: 0.4478, MCC: 0.1075, F1: 0.0513

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13592 | val 0.08464
  Epoch 020 - train 0.13098 | val 0.08649
  Epoch 021 - train 0.13008 | val 0.08644
  Regression -> MSE: 0.000115, MAE: 0.008388, R²: -0.0951
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13235 | val 0.17725
  Epoch 020 - train 0.12069 | val 0.18920
  Epoch 021 - train 0.11824 | val 0.18955
  Regression -> MSE: 0.000225, MAE: 0.011480, R²: -0.0279
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12580 | val 0.22960
  Epoch 020 - train 0.12066 | val 0.21659
  Epoch 021 - train 0.12293 | val 0.21602
  Regression -> MSE: 0.000092, MAE: 0.007493, R²: -0.1866
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13002 | val 0.09190
  Epoch 020 - train 0.12545 | val 0.09141
  Epoch 021 - train 0.12566 | val 0.09234
  Regression -> MSE: 0.000309, MAE: 0.013841, R²: -0.0060
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15395 | val 0.08671
  Epoch 020 - train 0.12969 | val 0.09347
  Epoch 021 - train 0.13883 | val 0.09350
  Regression -> MSE: 0.000253, MAE: 0.011423, R²: -0.0381
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12358 | val 0.17524
  Epoch 020 - train 0.11365 | val 0.18948
  Epoch 021 - train 0.11804 | val 0.19028
  Regression -> MSE: 0.000081, MAE: 0.007081, R²: 0.0028
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12973 | val 0.16436
  Epoch 020 - train 0.13379 | val 0.15980
  Epoch 021 - train 0.11407 | val 0.16005
  Regression -> MSE: 0.000306, MAE: 0.014505, R²: 0.0010
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13950 | val 0.13281
  Epoch 020 - train 0.12512 | val 0.13779
  Epoch 021 - train 0.12558 | val 0.13802
  Regression -> MSE: 0.000098, MAE: 0.007351, R²: 0.0045
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14286 | val 0.16659
  Epoch 020 - train 0.13810 | val 0.17396
  Epoch 021 - train 0.14111 | val 0.17454
  Regression -> MSE: 0.000177, MAE: 0.009399, R²: -0.0307
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12316 | val 0.16297
  Epoch 020 - train 0.11121 | val 0.15714
  Epoch 021 - train 0.11603 | val 0.15711
  Regression -> MSE: 0.000224, MAE: 0.011840, R²: -0.0048
  Directional -> Accuracy: 0.4464, MCC: -0.1899, F1: 0.5867

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12334 | val 0.18375
  Epoch 020 - train 0.11895 | val 0.18761
  Epoch 021 - train 0.11790 | val 0.18796
  Regression -> MSE: 0.000094, MAE: 0.007746, R²: -0.0181
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...


[I 2026-02-24 03:50:35,514] Trial 148 finished with value: -0.011551419632474066 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 3.646621955549643e-05, 'weight_decay': 4.145695317124751e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.19088017143844743, 'early_stopping_min_delta': 0.00746121082696694}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.11850 | val 0.17948
  Regression -> MSE: 0.000244, MAE: 0.012373, R²: -0.0309
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.22281 | val 0.29551
  Epoch 020 - train 0.22925 | val 0.29437
  Epoch 024 - train 0.22771 | val 0.29526
  Regression -> MSE: 0.000268, MAE: 0.013130, R²: -0.0839
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.22923 | val 0.19880
  Epoch 020 - train 0.21841 | val 0.19667
  Epoch 025 - train 0.22158 | val 0.19709
  Regression -> MSE: 0.000710, MAE: 0.019787, R²: -0.0378
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.24069 | val 0.36173
  Epoch 016 - train 0.24209 | val 0.36987
  Regression -> MSE: 0.000310, MAE: 0.014402, R²: -0.0005
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.21871 | val 0.22490
  Epoch 016 - train 0.20655 | val 0.23036
  Regression -> MSE: 0.000394, MAE: 0.015348, R²: -0.1278
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.24222 | val 0.22286
  Epoch 016 - train 0.23219 | val 0.22481
  Regression -> MSE: 0.000207, MAE: 0.010428, R²: -0.0150
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.22498 | val 0.42172
  Epoch 016 - train 0.22920 | val 0.44887
  Regression -> MSE: 0.000572, MAE: 0.018407, R²: -0.0302
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.24679 | val 0.27872
  Epoch 016 - train 0.24183 | val 0.28100
  Regression -> MSE: 0.000251, MAE: 0.011975, R²: -0.0244
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.23504 | val 0.25887
  Epoch 020 - train 0.24936 | val 0.24409
  Epoch 030 - train 0.21425 | val 0.24596
  Regression -> MSE: 0.000621, MAE: 0.019408, R²: -0.0393
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.22945 | val 0.24958
  Epoch 016 - train 0.21327 | val 0.25328
  Regression -> MSE: 0.000406, MAE: 0.016157, R²: -0.0575
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.22166 | val 0.28964
  Epoch 016 - train 0.21527 | val 0.28794
  Regression -> MSE: 0.000242, MAE: 0.011735, R²: -0.0040
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.22168 | val 0.35384
  Epoch 016 - train 0.22665 | val 0.37356
  Regression -> MSE: 0.000311, MAE: 0.013847, R²: -0.0009
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.22851 | val 0.24652
  Epoch 016 - train 0.23493 | val 0.25117
  Regression -> MSE: 0.000697, MAE: 0.020095, R²: -0.0291
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.23042 | val 0.22681
  Epoch 016 - train 0.24712 | val 0.24083
  Regression -> MSE: 0.000138, MAE: 0.009068, R²: 0.0013
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.21220 | val 0.28309
  Epoch 016 - train 0.21033 | val 0.28239
  Regression -> MSE: 0.000225, MAE: 0.010678, R²: 0.0002
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.22932 | val 0.44766
  Epoch 016 - train 0.21677 | val 0.44828
  Regression -> MSE: 0.000362, MAE: 0.016140, R²: -0.0003
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.24738 | val 0.22872
  Epoch 016 - train 0.24880 | val 0.22654
  Regression -> MSE: 0.000111, MAE: 0.008240, R²: -0.0265
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.21775 | val 0.36915
  Epoch 016 - train 0.22809 | val 0.38282
  Regression -> MSE: 0.000155, MAE: 0.009531, R²: 0.0045
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.23267 | val 0.22960
  Epoch 016 - train 0.24561 | val 0.23342
  Regression -> MSE: 0.000274, MAE: 0.013138, R²: -0.0066
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.20528 | val 0.28822
  Epoch 016 - train 0.20175 | val 0.28654
  Regression -> MSE: 0.000154, MAE: 0.008755, R²: -0.0286
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.24371 | val 0.33427
  Epoch 016 - train 0.24253 | val 0.33612
  Regression -> MSE: 0.000256, MAE: 0.011431, R²: -0.1297
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.23538 | val 0.27615
  Epoch 016 - train 0.23985 | val 0.27433
  Regression -> MSE: 0.000143, MAE: 0.008320, R²: -0.0000
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.22531 | val 0.25490
  Epoch 016 - train 0.21730 | val 0.25270
  Regression -> MSE: 0.000166, MAE: 0.010349, R²: -0.0041
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.24097 | val 0.24661
  Epoch 020 - train 0.23253 | val 0.24926
  Epoch 022 - train 0.23546 | val 0.24866
  Regression -> MSE: 0.000085, MAE: 0.007150, R²: 0.0064
  Directional -> Accuracy: 0.5862, MCC: 0.1741, F1: 0.6129

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.22433 | val 0.26450
  Epoch 016 - train 0.22532 | val 0.26609
  Regression -> MSE: 0.000214, MAE: 0.011056, R²: -0.0113
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.22822 | val 0.18647
  Epoch 016 - train 0.21921 | val 0.18284
  Regression -> MSE: 0.000099, MAE: 0.008198, R²: -0.0705
  Directional -> Accuracy: 0.4643, MCC: -0.0680, F1: 0.4828

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.25092 | val 0.17830
  Epoch 016 - train 0.23657 | val 0.18520
  Regression -> MSE: 0.000114, MAE: 0.009144, R²: -0.1043
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.22476 | val 0.20113
  Epoch 016 - train 0.23950 | val 0.20143
  Regression -> MSE: 0.000231, MAE: 0.012539, R²: -0.0001
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.23447 | val 0.24420
  Epoch 016 - train 0.22318 | val 0.24377
  Regression -> MSE: 0.000186, MAE: 0.008090, R²: -0.1183
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.24865 | val 0.17180
  Epoch 016 - train 0.23656 | val 0.17105
  Regression -> MSE: 0.000238, MAE: 0.011920, R²: -0.0076
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.24326 | val 0.34146
  Epoch 016 - train 0.22634 | val 0.35343
  Regression -> MSE: 0.000230, MAE: 0.009850, R²: 0.0013
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.24372 | val 0.25918
  Epoch 016 - train 0.23713 | val 0.25907
  Regression -> MSE: 0.000136, MAE: 0.008256, R²: -0.0095
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.25822 | val 0.28284
  Epoch 016 - train 0.25106 | val 0.28601
  Regression -> MSE: 0.000189, MAE: 0.010439, R²: -0.0041
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.23345 | val 0.26630
  Epoch 016 - train 0.21659 | val 0.26342
  Regression -> MSE: 0.000279, MAE: 0.010920, R²: -0.0649
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.23406 | val 0.17665
  Epoch 016 - train 0.21571 | val 0.18199
  Regression -> MSE: 0.000171, MAE: 0.010385, R²: -0.0241
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.21744 | val 0.23177
  Epoch 016 - train 0.22696 | val 0.24642
  Regression -> MSE: 0.000184, MAE: 0.010467, R²: -0.0207
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.22301 | val 0.20892
  Epoch 016 - train 0.22689 | val 0.20813
  Regression -> MSE: 0.000345, MAE: 0.011702, R²: -0.0074
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.26469 | val 0.12884
  Epoch 016 - train 0.23140 | val 0.12814
  Regression -> MSE: 0.000121, MAE: 0.008387, R²: -0.1499
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.24761 | val 0.30541
  Epoch 016 - train 0.23710 | val 0.31241
  Regression -> MSE: 0.000220, MAE: 0.011361, R²: -0.0076
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.23403 | val 0.38750
  Epoch 016 - train 0.24066 | val 0.40384
  Regression -> MSE: 0.000095, MAE: 0.007585, R²: -0.2179
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.23556 | val 0.16407
  Epoch 016 - train 0.20981 | val 0.16611
  Regression -> MSE: 0.000322, MAE: 0.014636, R²: -0.0480
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.23804 | val 0.11801
  Epoch 016 - train 0.25947 | val 0.11467
  Regression -> MSE: 0.000245, MAE: 0.011577, R²: -0.0053
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.20834 | val 0.26249
  Epoch 016 - train 0.20874 | val 0.26261
  Regression -> MSE: 0.000081, MAE: 0.007054, R²: -0.0005
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.24477 | val 0.27032
  Epoch 016 - train 0.23095 | val 0.27170
  Regression -> MSE: 0.000307, MAE: 0.014468, R²: 0.0008
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.21951 | val 0.23884
  Epoch 016 - train 0.22806 | val 0.25437
  Regression -> MSE: 0.000099, MAE: 0.007227, R²: -0.0034
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.23819 | val 0.26097
  Epoch 016 - train 0.26083 | val 0.26808
  Regression -> MSE: 0.000175, MAE: 0.010124, R²: -0.0161
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.21653 | val 0.27012
  Epoch 016 - train 0.22028 | val 0.27379
  Regression -> MSE: 0.000227, MAE: 0.011823, R²: -0.0161
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.23266 | val 0.23775
  Epoch 016 - train 0.22600 | val 0.23981
  Regression -> MSE: 0.000092, MAE: 0.007628, R²: -0.0010
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.23798 | val 0.36315
  Epoch 016 - train 0.23983 | val 0.37806
  Regression -> MSE: 0.000164, MAE: 0.010252, R²: -0.0016
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.24576 | val 0.32140
  Epoch 016 - train 0.24761 | val 0.32881
  Regression -> MSE: 0.000121, MAE: 0.008978, R²: -0.0435
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.22674 | val 0.35970

[I 2026-02-24 03:52:12,447] Trial 149 finished with value: -0.011481240126925401 and parameters: {'feature_set': 'emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 1.1468598583510357e-05, 'weight_decay': 7.605843551330084e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.3540527036177439, 'early_stopping_min_delta': 0.0077094348538432255}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 016 - train 0.23313 | val 0.37398
  Regression -> MSE: 0.000237, MAE: 0.012478, R²: -0.0009
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11602 | val 0.12627
  Epoch 011 - train 0.11061 | val 0.12642
  Regression -> MSE: 0.000250, MAE: 0.012628, R²: -0.0084
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10781 | val 0.09592
  Epoch 011 - train 0.10567 | val 0.09567
  Regression -> MSE: 0.000683, MAE: 0.019329, R²: 0.0026
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10808 | val 0.16302
  Epoch 011 - train 0.11655 | val 0.16323
  Regression -> MSE: 0.000311, MAE: 0.014471, R²: -0.0025
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09143 | val 0.09167
  Epoch 011 - train 0.09320 | val 0.09335
  Regression -> MSE: 0.000391, MAE: 0.015284, R²: -0.1189
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11482 | val 0.09762
  Epoch 011 - train 0.11114 | val 0.09729
  Regression -> MSE: 0.000204, MAE: 0.010029, R²: -0.0026
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10667 | val 0.18239
  Epoch 011 - train 0.11222 | val 0.18242
  Regression -> MSE: 0.000558, MAE: 0.018153, R²: -0.0056
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11639 | val 0.12399
  Epoch 011 - train 0.11520 | val 0.12409
  Regression -> MSE: 0.000247, MAE: 0.012208, R²: -0.0046
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10959 | val 0.12369
  Epoch 011 - train 0.09946 | val 0.12378
  Regression -> MSE: 0.000613, MAE: 0.019536, R²: -0.0260
  Directional -> Accuracy: 0.4773, MCC: 0.2251, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11053 | val 0.11859
  Epoch 011 - train 0.10492 | val 0.11857
  Regression -> MSE: 0.000397, MAE: 0.016003, R²: -0.0354
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11022 | val 0.12615
  Epoch 011 - train 0.10725 | val 0.12704
  Regression -> MSE: 0.000242, MAE: 0.012000, R²: -0.0031
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10479 | val 0.13912
  Epoch 011 - train 0.11870 | val 0.13941
  Regression -> MSE: 0.000326, MAE: 0.013629, R²: -0.0491
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11322 | val 0.11516
  Epoch 011 - train 0.11473 | val 0.11527
  Regression -> MSE: 0.000679, MAE: 0.019523, R²: -0.0020
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11650 | val 0.10177
  Epoch 011 - train 0.11697 | val 0.10151
  Regression -> MSE: 0.000139, MAE: 0.009062, R²: -0.0034
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09940 | val 0.13693
  Epoch 011 - train 0.10482 | val 0.13654
  Regression -> MSE: 0.000227, MAE: 0.010916, R²: -0.0095
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11142 | val 0.19874
  Epoch 011 - train 0.10556 | val 0.19899
  Regression -> MSE: 0.000363, MAE: 0.016062, R²: -0.0013
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11135 | val 0.10283
  Epoch 011 - train 0.11755 | val 0.10281
  Regression -> MSE: 0.000108, MAE: 0.008035, R²: 0.0003
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10585 | val 0.16104
  Epoch 011 - train 0.10999 | val 0.16118
  Regression -> MSE: 0.000156, MAE: 0.009617, R²: 0.0002
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11868 | val 0.11163
  Epoch 011 - train 0.11368 | val 0.11555
  Regression -> MSE: 0.000276, MAE: 0.012915, R²: -0.0151
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10291 | val 0.13054
  Epoch 011 - train 0.10148 | val 0.13042
  Regression -> MSE: 0.000172, MAE: 0.009266, R²: -0.1492
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11441 | val 0.13493
  Epoch 011 - train 0.11547 | val 0.13443
  Regression -> MSE: 0.000232, MAE: 0.010892, R²: -0.0263
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11893 | val 0.12220
  Epoch 011 - train 0.11657 | val 0.12218
  Regression -> MSE: 0.000145, MAE: 0.008412, R²: -0.0084
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10682 | val 0.11739
  Epoch 011 - train 0.10817 | val 0.11838
  Regression -> MSE: 0.000179, MAE: 0.010292, R²: -0.0806
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11422 | val 0.11865
  Epoch 011 - train 0.11126 | val 0.11877
  Regression -> MSE: 0.000088, MAE: 0.007177, R²: -0.0290
  Directional -> Accuracy: 0.3966, MCC: -0.1955, F1: 0.4068

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11414 | val 0.12443
  Epoch 011 - train 0.10769 | val 0.12537
  Regression -> MSE: 0.000212, MAE: 0.011201, R²: -0.0012
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10687 | val 0.09010
  Epoch 011 - train 0.10957 | val 0.08989
  Regression -> MSE: 0.000101, MAE: 0.008237, R²: -0.1020
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11768 | val 0.07863
  Epoch 011 - train 0.11299 | val 0.07866
  Regression -> MSE: 0.000105, MAE: 0.008853, R²: -0.0212
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12391 | val 0.09793
  Epoch 011 - train 0.12096 | val 0.09812
  Regression -> MSE: 0.000239, MAE: 0.012811, R²: -0.0313
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10973 | val 0.11657
  Epoch 011 - train 0.11171 | val 0.11669
  Regression -> MSE: 0.000181, MAE: 0.007983, R²: -0.0897
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11738 | val 0.08900
  Epoch 011 - train 0.12775 | val 0.08912
  Regression -> MSE: 0.000239, MAE: 0.011941, R²: -0.0085
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10767 | val 0.15524
  Epoch 011 - train 0.11040 | val 0.15508
  Regression -> MSE: 0.000232, MAE: 0.009927, R²: -0.0046
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11644 | val 0.12416
  Epoch 011 - train 0.12233 | val 0.12424
  Regression -> MSE: 0.000139, MAE: 0.008334, R²: -0.0316
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11363 | val 0.12441
  Epoch 011 - train 0.11661 | val 0.12449
  Regression -> MSE: 0.000194, MAE: 0.010494, R²: -0.0323
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10801 | val 0.11814
  Epoch 011 - train 0.10802 | val 0.11848
  Regression -> MSE: 0.000261, MAE: 0.010550, R²: 0.0014
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11794 | val 0.08461
  Epoch 011 - train 0.11163 | val 0.08467
  Regression -> MSE: 0.000170, MAE: 0.010388, R²: -0.0219
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11235 | val 0.09872
  Epoch 011 - train 0.11400 | val 0.09859
  Regression -> MSE: 0.000181, MAE: 0.010274, R²: -0.0042
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11394 | val 0.09592
  Epoch 011 - train 0.11183 | val 0.09660
  Regression -> MSE: 0.000344, MAE: 0.011716, R²: -0.0039
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11517 | val 0.07017
  Epoch 011 - train 0.11937 | val 0.07037
  Regression -> MSE: 0.000109, MAE: 0.008349, R²: -0.0356
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10993 | val 0.13490
  Epoch 011 - train 0.10846 | val 0.13504
  Regression -> MSE: 0.000221, MAE: 0.011382, R²: -0.0128
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10816 | val 0.16963
  Epoch 011 - train 0.10214 | val 0.16976
  Regression -> MSE: 0.000084, MAE: 0.007147, R²: -0.0809
  Directional -> Accuracy: 0.4468, MCC: 0.0497, F1: 0.3158

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10843 | val 0.08410
  Epoch 011 - train 0.10950 | val 0.08412
  Regression -> MSE: 0.000330, MAE: 0.014959, R²: -0.0715
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11277 | val 0.06112
  Epoch 011 - train 0.11093 | val 0.06113
  Regression -> MSE: 0.000248, MAE: 0.011534, R²: -0.0158
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10857 | val 0.12075
  Epoch 011 - train 0.11075 | val 0.12093
  Regression -> MSE: 0.000085, MAE: 0.007055, R²: -0.0507
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10792 | val 0.12304
  Epoch 011 - train 0.10617 | val 0.12300
  Regression -> MSE: 0.000307, MAE: 0.014503, R²: -0.0012
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11294 | val 0.10650
  Epoch 011 - train 0.11159 | val 0.10641
  Regression -> MSE: 0.000098, MAE: 0.007287, R²: -0.0022
  Directional -> Accuracy: 0.3864, MCC: -0.2294, F1: 0.4255

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11739 | val 0.11730
  Epoch 011 - train 0.11180 | val 0.11734
  Regression -> MSE: 0.000173, MAE: 0.010013, R²: -0.0096
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10724 | val 0.11279
  Epoch 011 - train 0.10638 | val 0.11315
  Regression -> MSE: 0.000223, MAE: 0.011761, R²: 0.0021
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11621 | val 0.11142
  Epoch 011 - train 0.10929 | val 0.11177
  Regression -> MSE: 0.000093, MAE: 0.007691, R²: -0.0094
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12133 | val 0.15599
  Epoch 011 - train 0.11297 | val 0.15610
  Regression -> MSE: 0.000167, MAE: 0.010317, R²: -0.0197
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.10290 | val 0.12089
  Epoch 011 - train 0.11165 | val 0.12101
  Regression -> MSE: 0.000122, MAE: 0.009008, R²: -0.0554
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 03:52:59,746] Trial 150 finished with value: -0.011430402422302144 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 2.0482714101448344e-05, 'weight_decay': 1.1269347492791708e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.14559075266400115, 'early_stopping_min_delta': 0.0064676555660051135}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 010 - train 0.11602 | val 0.13813
  Epoch 011 - train 0.11310 | val 0.13864
  Regression -> MSE: 0.000245, MAE: 0.012364, R²: -0.0321
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10937 | val 0.14450
  Epoch 011 - train 0.11280 | val 0.14658
  Regression -> MSE: 0.000266, MAE: 0.013142, R²: -0.0728
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10486 | val 0.09308
  Epoch 011 - train 0.11305 | val 0.09317
  Regression -> MSE: 0.000708, MAE: 0.019753, R²: -0.0345
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10922 | val 0.16261
  Epoch 011 - train 0.10640 | val 0.16285
  Regression -> MSE: 0.000310, MAE: 0.014440, R²: 0.0004
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10196 | val 0.10295
  Epoch 011 - train 0.09940 | val 0.11004
  Regression -> MSE: 0.000374, MAE: 0.014972, R²: -0.0714
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10900 | val 0.09753
  Epoch 011 - train 0.11200 | val 0.09721
  Regression -> MSE: 0.000207, MAE: 0.010132, R²: -0.0173
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10858 | val 0.18336
  Epoch 011 - train 0.11346 | val 0.18358
  Regression -> MSE: 0.000564, MAE: 0.018219, R²: -0.0152
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11864 | val 0.12565
  Epoch 011 - train 0.11466 | val 0.12648
  Regression -> MSE: 0.000248, MAE: 0.011943, R²: -0.0108
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10251 | val 0.14676
  Epoch 011 - train 0.10457 | val 0.14689
  Regression -> MSE: 0.000668, MAE: 0.020509, R²: -0.1180
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11263 | val 0.11603
  Epoch 011 - train 0.10477 | val 0.11609
  Regression -> MSE: 0.000413, MAE: 0.016289, R²: -0.0762
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10582 | val 0.12601
  Epoch 011 - train 0.10893 | val 0.12614
  Regression -> MSE: 0.000243, MAE: 0.011665, R²: -0.0073
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09974 | val 0.14014
  Epoch 011 - train 0.10768 | val 0.14041
  Regression -> MSE: 0.000321, MAE: 0.013598, R²: -0.0338
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11753 | val 0.11545
  Epoch 011 - train 0.12166 | val 0.11558
  Regression -> MSE: 0.000684, MAE: 0.019695, R²: -0.0105
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11308 | val 0.09809
  Epoch 011 - train 0.10815 | val 0.09806
  Regression -> MSE: 0.000143, MAE: 0.009437, R²: -0.0367
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10242 | val 0.13788
  Epoch 011 - train 0.10957 | val 0.13863
  Regression -> MSE: 0.000226, MAE: 0.010813, R²: -0.0027
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10749 | val 0.19810
  Epoch 011 - train 0.11564 | val 0.19842
  Regression -> MSE: 0.000364, MAE: 0.016015, R²: -0.0056
  Directional -> Accuracy: 0.4231, MCC: -0.1543, F1: 0.4000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11753 | val 0.10231
  Epoch 011 - train 0.11755 | val 0.10286
  Regression -> MSE: 0.000108, MAE: 0.007952, R²: -0.0016
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11022 | val 0.15969
  Epoch 011 - train 0.10899 | val 0.15962
  Regression -> MSE: 0.000156, MAE: 0.009737, R²: -0.0006
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11284 | val 0.10121
  Epoch 011 - train 0.11212 | val 0.10147
  Regression -> MSE: 0.000272, MAE: 0.012967, R²: -0.0010
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09992 | val 0.12894
  Epoch 011 - train 0.10025 | val 0.12857
  Regression -> MSE: 0.000163, MAE: 0.009013, R²: -0.0908
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11692 | val 0.13981
  Epoch 011 - train 0.11949 | val 0.13938
  Regression -> MSE: 0.000227, MAE: 0.010909, R²: -0.0025
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11280 | val 0.12273
  Epoch 011 - train 0.11743 | val 0.12271
  Regression -> MSE: 0.000151, MAE: 0.008776, R²: -0.0567
  Directional -> Accuracy: 0.3958, MCC: -0.0176, F1: 0.1714

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10466 | val 0.11507
  Epoch 011 - train 0.10293 | val 0.11503
  Regression -> MSE: 0.000174, MAE: 0.010267, R²: -0.0536
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12060 | val 0.11834
  Epoch 011 - train 0.12578 | val 0.11826
  Regression -> MSE: 0.000090, MAE: 0.007288, R²: -0.0530
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11219 | val 0.12263
  Epoch 011 - train 0.11485 | val 0.12271
  Regression -> MSE: 0.000214, MAE: 0.011396, R²: -0.0116
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10965 | val 0.08945
  Epoch 011 - train 0.10114 | val 0.08917
  Regression -> MSE: 0.000095, MAE: 0.008097, R²: -0.0302
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11214 | val 0.07862
  Epoch 011 - train 0.10930 | val 0.07863
  Regression -> MSE: 0.000105, MAE: 0.008819, R²: -0.0140
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11341 | val 0.09763
  Epoch 011 - train 0.11147 | val 0.09757
  Regression -> MSE: 0.000243, MAE: 0.012915, R²: -0.0495
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11416 | val 0.11825
  Epoch 011 - train 0.10533 | val 0.11767
  Regression -> MSE: 0.000171, MAE: 0.007817, R²: -0.0297
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11942 | val 0.08648
  Epoch 011 - train 0.12620 | val 0.08639
  Regression -> MSE: 0.000237, MAE: 0.011881, R²: -0.0020
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10560 | val 0.16314
  Epoch 011 - train 0.11615 | val 0.16322
  Regression -> MSE: 0.000237, MAE: 0.010266, R²: -0.0278
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11224 | val 0.12338
  Epoch 011 - train 0.10853 | val 0.12347
  Regression -> MSE: 0.000138, MAE: 0.008316, R²: -0.0221
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11481 | val 0.12711
  Epoch 011 - train 0.11392 | val 0.12716
  Regression -> MSE: 0.000189, MAE: 0.010453, R²: -0.0031
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10540 | val 0.11898
  Epoch 011 - train 0.10389 | val 0.11978
  Regression -> MSE: 0.000263, MAE: 0.010548, R²: -0.0034
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10150 | val 0.08774
  Epoch 011 - train 0.11345 | val 0.08767
  Regression -> MSE: 0.000167, MAE: 0.010377, R²: -0.0046
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10825 | val 0.09875
  Epoch 011 - train 0.10998 | val 0.09864
  Regression -> MSE: 0.000182, MAE: 0.010365, R²: -0.0133
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10686 | val 0.09384
  Epoch 011 - train 0.11280 | val 0.09411
  Regression -> MSE: 0.000347, MAE: 0.012177, R²: -0.0120
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11389 | val 0.06642
  Epoch 011 - train 0.11992 | val 0.06647
  Regression -> MSE: 0.000124, MAE: 0.008423, R²: -0.1759
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10925 | val 0.13252
  Epoch 011 - train 0.11267 | val 0.13277
  Regression -> MSE: 0.000219, MAE: 0.011301, R²: -0.0023
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10893 | val 0.16753
  Epoch 011 - train 0.10744 | val 0.16770
  Regression -> MSE: 0.000088, MAE: 0.007342, R²: -0.1334
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11837 | val 0.08265
  Epoch 011 - train 0.10699 | val 0.08278
  Regression -> MSE: 0.000330, MAE: 0.014980, R²: -0.0722
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12192 | val 0.06139
  Epoch 011 - train 0.11720 | val 0.06140
  Regression -> MSE: 0.000248, MAE: 0.011519, R²: -0.0155
  Directional -> Accuracy: 0.5789, MCC: 0.1556, F1: 0.6000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11940 | val 0.11926
  Epoch 011 - train 0.11123 | val 0.11933
  Regression -> MSE: 0.000082, MAE: 0.007130, R²: -0.0096
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10977 | val 0.12851
  Epoch 011 - train 0.10607 | val 0.12877
  Regression -> MSE: 0.000310, MAE: 0.014491, R²: -0.0097
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10334 | val 0.10515
  Epoch 011 - train 0.10917 | val 0.10515
  Regression -> MSE: 0.000098, MAE: 0.007328, R²: 0.0010
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12248 | val 0.11786
  Epoch 011 - train 0.12419 | val 0.11781
  Regression -> MSE: 0.000172, MAE: 0.009566, R²: -0.0002
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09876 | val 0.11118
  Epoch 011 - train 0.10094 | val 0.11119
  Regression -> MSE: 0.000225, MAE: 0.011803, R²: -0.0079
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10733 | val 0.11083
  Epoch 011 - train 0.11091 | val 0.11063
  Regression -> MSE: 0.000094, MAE: 0.007729, R²: -0.0153
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12318 | val 0.15523
  Epoch 011 - train 0.11281 | val 0.15535
  Regression -> MSE: 0.000165, MAE: 0.010263, R²: -0.0064
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.11318 | val 0.12096
  Epoch 011 - train 0.10621 | val 0.12092
  Regression -> MSE: 0.000134, MAE: 0.009184, R²: -0.1547
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 03:53:46,272] Trial 151 finished with value: -0.011487031173191995 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 1.9409100110176998e-05, 'weight_decay': 1.6772137742621418e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.1456166888767803, 'early_stopping_min_delta': 0.006750248795575591}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 010 - train 0.10637 | val 0.13660
  Epoch 011 - train 0.10433 | val 0.13703
  Regression -> MSE: 0.000241, MAE: 0.012337, R²: -0.0180
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07463 | val 0.09359
  Epoch 011 - train 0.07743 | val 0.09328
  Regression -> MSE: 0.000254, MAE: 0.012800, R²: -0.0249
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08210 | val 0.06698
  Epoch 011 - train 0.08244 | val 0.06693
  Regression -> MSE: 0.000696, MAE: 0.019565, R²: -0.0167
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07922 | val 0.11506
  Epoch 011 - train 0.08199 | val 0.11494
  Regression -> MSE: 0.000323, MAE: 0.014534, R²: -0.0416
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06799 | val 0.06094
  Epoch 011 - train 0.07055 | val 0.06145
  Regression -> MSE: 0.000351, MAE: 0.014605, R²: -0.0037
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07417 | val 0.07363
  Epoch 011 - train 0.07727 | val 0.07365
  Regression -> MSE: 0.000205, MAE: 0.010262, R²: -0.0051
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07648 | val 0.13134
  Epoch 011 - train 0.07369 | val 0.13127
  Regression -> MSE: 0.000578, MAE: 0.018552, R²: -0.0418
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.08089 | val 0.08733
  Epoch 011 - train 0.07772 | val 0.08723
  Regression -> MSE: 0.000247, MAE: 0.012203, R²: -0.0043
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07258 | val 0.09676
  Epoch 011 - train 0.07977 | val 0.09665
  Regression -> MSE: 0.000643, MAE: 0.020149, R²: -0.0760
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07768 | val 0.08499
  Epoch 011 - train 0.07617 | val 0.08494
  Regression -> MSE: 0.000398, MAE: 0.016010, R²: -0.0372
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.08690 | val 0.09075
  Epoch 011 - train 0.08267 | val 0.09092
  Regression -> MSE: 0.000243, MAE: 0.012150, R²: -0.0060
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.07747 | val 0.10376
  Epoch 011 - train 0.07513 | val 0.10375
  Regression -> MSE: 0.000311, MAE: 0.013736, R²: -0.0005
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08450 | val 0.08359
  Epoch 011 - train 0.08504 | val 0.08355
  Regression -> MSE: 0.000680, MAE: 0.019510, R²: -0.0047
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07990 | val 0.07233
  Epoch 011 - train 0.07430 | val 0.07240
  Regression -> MSE: 0.000140, MAE: 0.009275, R²: -0.0125
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08141 | val 0.08975
  Epoch 011 - train 0.07114 | val 0.08968
  Regression -> MSE: 0.000227, MAE: 0.010766, R²: -0.0113
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08295 | val 0.14126
  Epoch 011 - train 0.08130 | val 0.14142
  Regression -> MSE: 0.000363, MAE: 0.016087, R²: -0.0014
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.08363 | val 0.08313
  Epoch 011 - train 0.08361 | val 0.08458
  Regression -> MSE: 0.000112, MAE: 0.008309, R²: -0.0384
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07864 | val 0.11549
  Epoch 011 - train 0.07830 | val 0.11558
  Regression -> MSE: 0.000156, MAE: 0.009573, R²: 0.0020
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07947 | val 0.07195
  Epoch 011 - train 0.07527 | val 0.07191
  Regression -> MSE: 0.000274, MAE: 0.012921, R²: -0.0070
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07779 | val 0.09317
  Epoch 011 - train 0.07594 | val 0.09309
  Regression -> MSE: 0.000171, MAE: 0.009231, R²: -0.1436
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.08540 | val 0.09879
  Epoch 011 - train 0.07931 | val 0.09885
  Regression -> MSE: 0.000233, MAE: 0.010952, R²: -0.0297
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08201 | val 0.08819
  Epoch 011 - train 0.08539 | val 0.08834
  Regression -> MSE: 0.000150, MAE: 0.008681, R²: -0.0447
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07917 | val 0.08266
  Epoch 011 - train 0.07925 | val 0.08245
  Regression -> MSE: 0.000167, MAE: 0.010273, R²: -0.0089
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08293 | val 0.08409
  Epoch 011 - train 0.07751 | val 0.08403
  Regression -> MSE: 0.000086, MAE: 0.007073, R²: -0.0053
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07678 | val 0.08682
  Epoch 011 - train 0.08271 | val 0.08706
  Regression -> MSE: 0.000213, MAE: 0.011061, R²: -0.0074
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07338 | val 0.06510
  Epoch 011 - train 0.07059 | val 0.06501
  Regression -> MSE: 0.000096, MAE: 0.008119, R²: -0.0411
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.08514 | val 0.06025
  Epoch 011 - train 0.08227 | val 0.06026
  Regression -> MSE: 0.000113, MAE: 0.009110, R²: -0.0941
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.08024 | val 0.06906
  Epoch 011 - train 0.08356 | val 0.06933
  Regression -> MSE: 0.000232, MAE: 0.012585, R²: -0.0029
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.08085 | val 0.08403
  Epoch 011 - train 0.07830 | val 0.08405
  Regression -> MSE: 0.000178, MAE: 0.007920, R²: -0.0717
  Directional -> Accuracy: 0.4737, MCC: 0.1685, F1: 0.1176

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08094 | val 0.06202
  Epoch 011 - train 0.08182 | val 0.06204
  Regression -> MSE: 0.000237, MAE: 0.011881, R²: -0.0026
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.08272 | val 0.11205
  Epoch 011 - train 0.08625 | val 0.11194
  Regression -> MSE: 0.000232, MAE: 0.010021, R²: -0.0073
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.08806 | val 0.09224
  Epoch 011 - train 0.08514 | val 0.09247
  Regression -> MSE: 0.000141, MAE: 0.008500, R²: -0.0434
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.08489 | val 0.08889
  Epoch 011 - train 0.08528 | val 0.08889
  Regression -> MSE: 0.000201, MAE: 0.010783, R²: -0.0699
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07388 | val 0.08245
  Epoch 011 - train 0.07378 | val 0.08270
  Regression -> MSE: 0.000263, MAE: 0.010506, R²: -0.0030
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07553 | val 0.06112
  Epoch 011 - train 0.07122 | val 0.06107
  Regression -> MSE: 0.000166, MAE: 0.010361, R²: 0.0037
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.07798 | val 0.07632
  Epoch 011 - train 0.08011 | val 0.07643
  Regression -> MSE: 0.000185, MAE: 0.010523, R²: -0.0265
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07372 | val 0.06729
  Epoch 011 - train 0.07353 | val 0.06721
  Regression -> MSE: 0.000347, MAE: 0.012259, R²: -0.0131
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08303 | val 0.04807
  Epoch 011 - train 0.08552 | val 0.04805
  Regression -> MSE: 0.000123, MAE: 0.008405, R²: -0.1675
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.08254 | val 0.10156
  Epoch 011 - train 0.07797 | val 0.10198
  Regression -> MSE: 0.000227, MAE: 0.011542, R²: -0.0409
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07487 | val 0.11970
  Epoch 011 - train 0.08195 | val 0.11960
  Regression -> MSE: 0.000084, MAE: 0.007154, R²: -0.0828
  Directional -> Accuracy: 0.4043, MCC: 0.0267, F1: 0.1250

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07480 | val 0.06426
  Epoch 011 - train 0.07961 | val 0.06435
  Regression -> MSE: 0.000343, MAE: 0.015453, R²: -0.1160
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09341 | val 0.04451
  Epoch 011 - train 0.08880 | val 0.04445
  Regression -> MSE: 0.000245, MAE: 0.011589, R²: -0.0062
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.07420 | val 0.08598
  Epoch 011 - train 0.07895 | val 0.08611
  Regression -> MSE: 0.000084, MAE: 0.007052, R²: -0.0355
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07950 | val 0.09017
  Epoch 011 - train 0.07861 | val 0.09028
  Regression -> MSE: 0.000307, MAE: 0.014478, R²: -0.0022
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08438 | val 0.08046
  Epoch 011 - train 0.07594 | val 0.08050
  Regression -> MSE: 0.000099, MAE: 0.007154, R²: -0.0095
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.09662 | val 0.08664
  Epoch 011 - train 0.09959 | val 0.08664
  Regression -> MSE: 0.000175, MAE: 0.009428, R²: -0.0210
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08262 | val 0.07954
  Epoch 011 - train 0.07629 | val 0.07971
  Regression -> MSE: 0.000228, MAE: 0.011880, R²: -0.0211
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07876 | val 0.08163
  Epoch 011 - train 0.08031 | val 0.08165
  Regression -> MSE: 0.000096, MAE: 0.007877, R²: -0.0361
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.08004 | val 0.10895
  Epoch 011 - train 0.08069 | val 0.10878
  Regression -> MSE: 0.000165, MAE: 0.010278, R²: -0.0064
  Directional -> Accuracy: 0.4630, MCC: -0.0650, F1: 0.3556

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.08263 | val 0.08615
  Epoch 011 - train 0.08327 | val 0.08608
  Regression -> MSE: 0.000124, MAE: 0.009017, R²: -0.0693
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 03:54:33,061] Trial 152 finished with value: -0.01149042690241927 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 1.6223524224941705e-05, 'weight_decay': 9.538870163456057e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.10195222612784702, 'early_stopping_min_delta': 0.006389999073126153}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 010 - train 0.08185 | val 0.09790
  Epoch 011 - train 0.08222 | val 0.09791
  Regression -> MSE: 0.000237, MAE: 0.012363, R²: -0.0008
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.35619 | val 0.44817
  Epoch 011 - train 0.33208 | val 0.45439
  Regression -> MSE: 0.000248, MAE: 0.012589, R²: -0.0033
  Directional -> Accuracy: 0.4545, MCC: -0.0214, F1: 0.6111

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.36707 | val 0.29111
  Epoch 011 - train 0.34444 | val 0.29127
  Regression -> MSE: 0.000710, MAE: 0.019779, R²: -0.0369
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.35182 | val 0.57256
  Epoch 011 - train 0.35878 | val 0.57316
  Regression -> MSE: 0.000324, MAE: 0.014554, R²: -0.0453
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.30970 | val 0.28503
  Epoch 011 - train 0.30547 | val 0.29416
  Regression -> MSE: 0.000382, MAE: 0.015123, R²: -0.0941
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.33509 | val 0.32995
  Epoch 011 - train 0.33973 | val 0.32929
  Regression -> MSE: 0.000207, MAE: 0.010428, R²: -0.0167
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.36101 | val 0.65444
  Epoch 011 - train 0.37750 | val 0.65486
  Regression -> MSE: 0.000556, MAE: 0.018167, R²: -0.0021
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.34814 | val 0.40664
  Epoch 011 - train 0.35557 | val 0.40694
  Regression -> MSE: 0.000247, MAE: 0.011924, R²: -0.0046
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.34272 | val 0.44413
  Epoch 011 - train 0.37678 | val 0.44380
  Regression -> MSE: 0.000631, MAE: 0.019920, R²: -0.0567
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.37074 | val 0.38929
  Epoch 011 - train 0.33377 | val 0.38981
  Regression -> MSE: 0.000392, MAE: 0.015961, R²: -0.0226
  Directional -> Accuracy: 0.5102, MCC: -0.1193, F1: 0.0769

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.35217 | val 0.41339
  Epoch 011 - train 0.35606 | val 0.41222
  Regression -> MSE: 0.000242, MAE: 0.011891, R²: -0.0019
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.33988 | val 0.45863
  Epoch 011 - train 0.34822 | val 0.45863
  Regression -> MSE: 0.000327, MAE: 0.013625, R²: -0.0525
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.38493 | val 0.37339
  Epoch 011 - train 0.38402 | val 0.37372
  Regression -> MSE: 0.000683, MAE: 0.019717, R²: -0.0080
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.34805 | val 0.31520
  Epoch 011 - train 0.34754 | val 0.31572
  Regression -> MSE: 0.000140, MAE: 0.009295, R²: -0.0139
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.32611 | val 0.44038
  Epoch 011 - train 0.34304 | val 0.44104
  Regression -> MSE: 0.000225, MAE: 0.010709, R²: -0.0001
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.34797 | val 0.72174
  Epoch 011 - train 0.32771 | val 0.72344
  Regression -> MSE: 0.000362, MAE: 0.016066, R²: -0.0007
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.39295 | val 0.34519
  Epoch 011 - train 0.40742 | val 0.34865
  Regression -> MSE: 0.000115, MAE: 0.008024, R²: -0.0627
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.33118 | val 0.56554
  Epoch 011 - train 0.34431 | val 0.56653
  Regression -> MSE: 0.000156, MAE: 0.009617, R²: -0.0030
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.37846 | val 0.32986
  Epoch 011 - train 0.32654 | val 0.33672
  Regression -> MSE: 0.000277, MAE: 0.013308, R²: -0.0181
  Directional -> Accuracy: 0.4079, MCC: -0.0833, F1: 0.2857

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.32186 | val 0.43746
  Epoch 011 - train 0.31274 | val 0.43820
  Regression -> MSE: 0.000165, MAE: 0.009078, R²: -0.1059
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.33868 | val 0.49786
  Epoch 011 - train 0.38023 | val 0.49852
  Regression -> MSE: 0.000226, MAE: 0.010911, R²: 0.0006
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.35661 | val 0.42107
  Epoch 011 - train 0.36152 | val 0.42115
  Regression -> MSE: 0.000143, MAE: 0.008302, R²: 0.0013
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.31006 | val 0.37872
  Epoch 020 - train 0.31446 | val 0.36949
  Epoch 030 - train 0.29804 | val 0.37089
  Regression -> MSE: 0.000176, MAE: 0.010560, R²: -0.0661
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6024

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.35219 | val 0.38994
  Epoch 011 - train 0.36258 | val 0.39020
  Regression -> MSE: 0.000085, MAE: 0.007044, R²: 0.0004
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.37183 | val 0.41340
  Epoch 011 - train 0.36431 | val 0.42264
  Regression -> MSE: 0.000218, MAE: 0.011040, R²: -0.0302
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.34279 | val 0.27660
  Epoch 011 - train 0.35270 | val 0.27556
  Regression -> MSE: 0.000107, MAE: 0.008393, R²: -0.1624
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.39778 | val 0.23496
  Epoch 011 - train 0.37904 | val 0.23495
  Regression -> MSE: 0.000104, MAE: 0.008756, R²: -0.0046
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.35541 | val 0.29807
  Epoch 011 - train 0.36467 | val 0.29796
  Regression -> MSE: 0.000233, MAE: 0.012619, R²: -0.0077
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.31747 | val 0.38083
  Epoch 011 - train 0.32729 | val 0.38186
  Regression -> MSE: 0.000186, MAE: 0.008089, R²: -0.1193
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.35572 | val 0.24293
  Epoch 011 - train 0.37434 | val 0.24292
  Regression -> MSE: 0.000239, MAE: 0.011931, R²: -0.0090
  Directional -> Accuracy: 0.4878, MCC: 0.0474, F1: 0.2222

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.30693 | val 0.54800
  Epoch 011 - train 0.34387 | val 0.54856
  Regression -> MSE: 0.000231, MAE: 0.009906, R²: -0.0034
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.35879 | val 0.40305
  Epoch 011 - train 0.34145 | val 0.40347
  Regression -> MSE: 0.000138, MAE: 0.008308, R²: -0.0198
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.36064 | val 0.41840
  Epoch 011 - train 0.34216 | val 0.41865
  Regression -> MSE: 0.000189, MAE: 0.010378, R²: -0.0059
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.28847 | val 0.36846
  Epoch 018 - train 0.27096 | val 0.37733
  Regression -> MSE: 0.000267, MAE: 0.010532, R²: -0.0190
  Directional -> Accuracy: 0.5753, MCC: 0.1536, F1: 0.5974

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.37794 | val 0.25892
  Epoch 011 - train 0.31038 | val 0.25890
  Regression -> MSE: 0.000170, MAE: 0.010381, R²: -0.0194
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.36192 | val 0.31956
  Epoch 011 - train 0.33495 | val 0.31912
  Regression -> MSE: 0.000183, MAE: 0.010386, R²: -0.0168
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.33653 | val 0.29512
  Epoch 011 - train 0.32265 | val 0.29509
  Regression -> MSE: 0.000343, MAE: 0.011906, R²: -0.0016
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.32368 | val 0.18523
  Epoch 011 - train 0.33413 | val 0.18513
  Regression -> MSE: 0.000110, MAE: 0.008310, R²: -0.0450
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.39806 | val 0.45664
  Epoch 011 - train 0.40892 | val 0.45692
  Regression -> MSE: 0.000219, MAE: 0.011265, R²: -0.0033
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.32631 | val 0.60417
  Epoch 011 - train 0.34000 | val 0.60489
  Regression -> MSE: 0.000085, MAE: 0.007198, R²: -0.0944
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.36086 | val 0.22075
  Epoch 011 - train 0.33094 | val 0.22091
  Regression -> MSE: 0.000310, MAE: 0.013949, R²: -0.0086
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.38582 | val 0.16454
  Epoch 011 - train 0.34331 | val 0.16436
  Regression -> MSE: 0.000250, MAE: 0.011504, R²: -0.0269
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.31269 | val 0.39163
  Epoch 011 - train 0.32482 | val 0.39201
  Regression -> MSE: 0.000083, MAE: 0.007050, R²: -0.0328
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.37238 | val 0.44128
  Epoch 011 - train 0.36200 | val 0.44139
  Regression -> MSE: 0.000314, MAE: 0.014497, R²: -0.0219
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.32329 | val 0.34378
  Epoch 011 - train 0.34696 | val 0.34358
  Regression -> MSE: 0.000098, MAE: 0.007258, R²: 0.0013
  Directional -> Accuracy: 0.5455, MCC: -0.0029, F1: 0.6774

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.38550 | val 0.40695
  Epoch 011 - train 0.37544 | val 0.40722
  Regression -> MSE: 0.000172, MAE: 0.009626, R²: -0.0005
  Directional -> Accuracy: 0.4286, MCC: -0.0887, F1: 0.4400

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.33437 | val 0.37658
  Epoch 011 - train 0.32820 | val 0.37599
  Regression -> MSE: 0.000230, MAE: 0.011884, R²: -0.0302
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.33890 | val 0.34896
  Epoch 011 - train 0.36762 | val 0.34866
  Regression -> MSE: 0.000092, MAE: 0.007637, R²: 0.0015
  Directional -> Accuracy: 0.5088, MCC: -0.0132, F1: 0.3000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.34384 | val 0.54446
  Epoch 011 - train 0.36988 | val 0.54632
  Regression -> MSE: 0.000166, MAE: 0.010294, R²: -0.0126
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.36630 | val 0.39733
  Epoch 011 - train 0.30828 | val 0.39678
  Regression -> MSE: 0.000129, MAE: 0.009084, R²: -0.1166
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 03:55:22,428] Trial 153 finished with value: -0.011423452887519727 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 4.8205773585838776e-05, 'weight_decay': 7.1693904253123585e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.6229921549901394, 'early_stopping_min_delta': 0.007070735375107214}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 010 - train 0.35362 | val 0.48476
  Epoch 011 - train 0.34141 | val 0.48468
  Regression -> MSE: 0.000237, MAE: 0.012397, R²: 0.0005
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.34847 | val 0.44102
  Epoch 011 - train 0.32321 | val 0.44064
  Regression -> MSE: 0.000259, MAE: 0.012991, R²: -0.0480
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.30987 | val 0.29431
  Epoch 011 - train 0.33133 | val 0.29428
  Regression -> MSE: 0.000690, MAE: 0.019434, R²: -0.0081
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.38148 | val 0.54832
  Epoch 011 - train 0.37287 | val 0.54814
  Regression -> MSE: 0.000318, MAE: 0.014480, R²: -0.0262
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.27096 | val 0.25579
  Epoch 011 - train 0.27713 | val 0.25995
  Regression -> MSE: 0.000359, MAE: 0.014754, R²: -0.0272
  Directional -> Accuracy: 0.4267, MCC: -0.1277, F1: 0.3768

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.34037 | val 0.30477
  Epoch 011 - train 0.33742 | val 0.30408
  Regression -> MSE: 0.000209, MAE: 0.010206, R²: -0.0283
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.33500 | val 0.64650
  Epoch 020 - train 0.28970 | val 0.62441
  Epoch 030 - train 0.28778 | val 0.62771
  Regression -> MSE: 0.000577, MAE: 0.018779, R²: -0.0398
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.35358 | val 0.39543
  Epoch 011 - train 0.35656 | val 0.39558
  Regression -> MSE: 0.000246, MAE: 0.012002, R²: -0.0015
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.33784 | val 0.45918
  Epoch 011 - train 0.30602 | val 0.45948
  Regression -> MSE: 0.000648, MAE: 0.020233, R²: -0.0844
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.30121 | val 0.38095
  Epoch 011 - train 0.30542 | val 0.38080
  Regression -> MSE: 0.000390, MAE: 0.015954, R²: -0.0163
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.35948 | val 0.40243
  Epoch 011 - train 0.34743 | val 0.40236
  Regression -> MSE: 0.000242, MAE: 0.012009, R²: -0.0016
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.31505 | val 0.49275
  Epoch 011 - train 0.31835 | val 0.49364
  Regression -> MSE: 0.000310, MAE: 0.013749, R²: 0.0021
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.35429 | val 0.36012
  Epoch 011 - train 0.34516 | val 0.36063
  Regression -> MSE: 0.000680, MAE: 0.019657, R²: -0.0047
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.33318 | val 0.30343
  Epoch 011 - train 0.34288 | val 0.30345
  Regression -> MSE: 0.000143, MAE: 0.009418, R²: -0.0321
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.31305 | val 0.41404
  Epoch 011 - train 0.33185 | val 0.41403
  Regression -> MSE: 0.000229, MAE: 0.010840, R²: -0.0196
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.30133 | val 0.69524
  Epoch 011 - train 0.31681 | val 0.69700
  Regression -> MSE: 0.000367, MAE: 0.015939, R²: -0.0145
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.33410 | val 0.32150
  Epoch 011 - train 0.36782 | val 0.32183
  Regression -> MSE: 0.000109, MAE: 0.008123, R²: -0.0075
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.32318 | val 0.55175
  Epoch 011 - train 0.32659 | val 0.55283
  Regression -> MSE: 0.000155, MAE: 0.009628, R²: 0.0032
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.33570 | val 0.31210
  Epoch 011 - train 0.33901 | val 0.31377
  Regression -> MSE: 0.000272, MAE: 0.013019, R²: 0.0006
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.29295 | val 0.42147
  Epoch 011 - train 0.30851 | val 0.42080
  Regression -> MSE: 0.000171, MAE: 0.009211, R²: -0.1400
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.33439 | val 0.47146
  Epoch 011 - train 0.34237 | val 0.47177
  Regression -> MSE: 0.000236, MAE: 0.010956, R²: -0.0422
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.35279 | val 0.41435
  Epoch 011 - train 0.33162 | val 0.41380
  Regression -> MSE: 0.000144, MAE: 0.008319, R²: -0.0027
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.29987 | val 0.37052
  Epoch 011 - train 0.32681 | val 0.37165
  Regression -> MSE: 0.000170, MAE: 0.010254, R²: -0.0280
  Directional -> Accuracy: 0.4848, MCC: -0.1240, F1: 0.6531

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.34578 | val 0.37196
  Epoch 011 - train 0.34180 | val 0.37116
  Regression -> MSE: 0.000088, MAE: 0.007183, R²: -0.0296
  Directional -> Accuracy: 0.3793, MCC: -0.2006, F1: 0.1818

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.31332 | val 0.41545
  Epoch 011 - train 0.33781 | val 0.43366
  Regression -> MSE: 0.000217, MAE: 0.011037, R²: -0.0251
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.30790 | val 0.26828
  Epoch 011 - train 0.31595 | val 0.26811
  Regression -> MSE: 0.000094, MAE: 0.008101, R²: -0.0257
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.35310 | val 0.23047
  Epoch 011 - train 0.35209 | val 0.23045
  Regression -> MSE: 0.000104, MAE: 0.008781, R²: -0.0062
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.36536 | val 0.30244
  Epoch 011 - train 0.35623 | val 0.30324
  Regression -> MSE: 0.000243, MAE: 0.012928, R²: -0.0511
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.32475 | val 0.37207
  Epoch 011 - train 0.34004 | val 0.37314
  Regression -> MSE: 0.000182, MAE: 0.008009, R²: -0.0945
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.34489 | val 0.24075
  Epoch 011 - train 0.36675 | val 0.24101
  Regression -> MSE: 0.000237, MAE: 0.011887, R²: -0.0035
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.34288 | val 0.53594
  Epoch 011 - train 0.32256 | val 0.53624
  Regression -> MSE: 0.000232, MAE: 0.009962, R²: -0.0060
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.37354 | val 0.37106
  Epoch 011 - train 0.32962 | val 0.37192
  Regression -> MSE: 0.000135, MAE: 0.008172, R²: 0.0013
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.30888 | val 0.40364
  Epoch 011 - train 0.34396 | val 0.40382
  Regression -> MSE: 0.000192, MAE: 0.010409, R²: -0.0202
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.29909 | val 0.36082
  Epoch 020 - train 0.28223 | val 0.37657
  Regression -> MSE: 0.000274, MAE: 0.010851, R²: -0.0481
  Directional -> Accuracy: 0.4932, MCC: 0.0939, F1: 0.3019

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.36162 | val 0.26285
  Epoch 011 - train 0.33413 | val 0.26288
  Regression -> MSE: 0.000167, MAE: 0.010370, R²: -0.0024
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.29554 | val 0.31721
  Epoch 011 - train 0.31617 | val 0.31743
  Regression -> MSE: 0.000180, MAE: 0.010271, R²: -0.0018
  Directional -> Accuracy: 0.5000, MCC: -0.0021, F1: 0.4762

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.31993 | val 0.28342
  Epoch 011 - train 0.31146 | val 0.28285
  Regression -> MSE: 0.000345, MAE: 0.012081, R²: -0.0065
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.34587 | val 0.17630
  Epoch 011 - train 0.35088 | val 0.17631
  Regression -> MSE: 0.000115, MAE: 0.008339, R²: -0.0936
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.35455 | val 0.44455
  Epoch 011 - train 0.35868 | val 0.44447
  Regression -> MSE: 0.000220, MAE: 0.011350, R²: -0.0079
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.32400 | val 0.59237
  Epoch 011 - train 0.32132 | val 0.59283
  Regression -> MSE: 0.000083, MAE: 0.007094, R²: -0.0665
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.29241 | val 0.25293
  Epoch 011 - train 0.28783 | val 0.25298
  Regression -> MSE: 0.000334, MAE: 0.015135, R²: -0.0848
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.36573 | val 0.15941
  Epoch 011 - train 0.36250 | val 0.15936
  Regression -> MSE: 0.000247, MAE: 0.011532, R²: -0.0146
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.31946 | val 0.37598
  Epoch 011 - train 0.31522 | val 0.37598
  Regression -> MSE: 0.000081, MAE: 0.007067, R²: 0.0024
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.37429 | val 0.39336
  Epoch 011 - train 0.34411 | val 0.39298
  Regression -> MSE: 0.000307, MAE: 0.014494, R²: -0.0006
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.33915 | val 0.37805
  Epoch 011 - train 0.31642 | val 0.37809
  Regression -> MSE: 0.000102, MAE: 0.007104, R²: -0.0388
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.40752 | val 0.39202
  Epoch 011 - train 0.36894 | val 0.39201
  Regression -> MSE: 0.000173, MAE: 0.009886, R²: -0.0039
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.31868 | val 0.35935
  Epoch 011 - train 0.31097 | val 0.35881
  Regression -> MSE: 0.000225, MAE: 0.011762, R²: -0.0083
  Directional -> Accuracy: 0.4464, MCC: -0.1448, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.33755 | val 0.35062
  Epoch 011 - train 0.31665 | val 0.35001
  Regression -> MSE: 0.000095, MAE: 0.007768, R²: -0.0246
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.35152 | val 0.51449
  Epoch 011 - train 0.35273 | val 0.51459
  Regression -> MSE: 0.000164, MAE: 0.010236, R²: 0.0005
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.35455 | val 0.40666
  Epoch 011 - train 0.30851 | val 0.40687
  Regression -> MSE: 0.000116, MAE: 0.008918, R²: -0.0034
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 03:56:12,617] Trial 154 finished with value: -0.011460789230820884 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 6.056794029556709e-05, 'weight_decay': 1.053449477295271e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.5992615919108233, 'early_stopping_min_delta': 0.00707443760389245}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 010 - train 0.34805 | val 0.46315
  Epoch 011 - train 0.35675 | val 0.46346
  Regression -> MSE: 0.000243, MAE: 0.012358, R²: -0.0236
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14792 | val 0.18281
  Epoch 011 - train 0.14474 | val 0.18373
  Regression -> MSE: 0.000248, MAE: 0.012562, R²: -0.0017
  Directional -> Accuracy: 0.3506, MCC: -0.3095, F1: 0.2857

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14771 | val 0.12923
  Epoch 011 - train 0.14750 | val 0.12932
  Regression -> MSE: 0.000706, MAE: 0.019723, R²: -0.0310
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15731 | val 0.22667
  Epoch 011 - train 0.14874 | val 0.22654
  Regression -> MSE: 0.000311, MAE: 0.014390, R²: -0.0039
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12331 | val 0.12545
  Epoch 011 - train 0.13270 | val 0.12942
  Regression -> MSE: 0.000367, MAE: 0.014864, R²: -0.0513
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14850 | val 0.13795
  Epoch 011 - train 0.14823 | val 0.13804
  Regression -> MSE: 0.000205, MAE: 0.010074, R²: -0.0044
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.14718 | val 0.25885
  Epoch 011 - train 0.14882 | val 0.25867
  Regression -> MSE: 0.000562, MAE: 0.018195, R²: -0.0132
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15755 | val 0.17198
  Epoch 011 - train 0.15739 | val 0.17224
  Regression -> MSE: 0.000246, MAE: 0.011890, R²: -0.0017
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.16707 | val 0.16164
  Epoch 011 - train 0.16453 | val 0.16142
  Regression -> MSE: 0.000601, MAE: 0.019232, R²: -0.0055
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15672 | val 0.16118
  Epoch 011 - train 0.15088 | val 0.16113
  Regression -> MSE: 0.000416, MAE: 0.016356, R²: -0.0857
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15667 | val 0.17491
  Epoch 011 - train 0.14844 | val 0.17491
  Regression -> MSE: 0.000242, MAE: 0.011907, R²: -0.0004
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14678 | val 0.19665
  Epoch 011 - train 0.13525 | val 0.19680
  Regression -> MSE: 0.000317, MAE: 0.013590, R²: -0.0202
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.16172 | val 0.16167
  Epoch 011 - train 0.16784 | val 0.16201
  Regression -> MSE: 0.000676, MAE: 0.019478, R²: 0.0012
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16083 | val 0.14205
  Epoch 011 - train 0.15010 | val 0.14214
  Regression -> MSE: 0.000138, MAE: 0.009116, R²: -0.0014
  Directional -> Accuracy: 0.4651, MCC: -0.0027, F1: 0.5660

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14204 | val 0.17625
  Epoch 011 - train 0.13450 | val 0.17627
  Regression -> MSE: 0.000230, MAE: 0.010852, R²: -0.0219
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16046 | val 0.28359
  Epoch 011 - train 0.14975 | val 0.28368
  Regression -> MSE: 0.000364, MAE: 0.016233, R²: -0.0041
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16645 | val 0.14125
  Epoch 020 - train 0.15575 | val 0.13564
  Epoch 029 - train 0.15850 | val 0.13364
  Regression -> MSE: 0.000106, MAE: 0.007943, R²: 0.0156
  Directional -> Accuracy: 0.5571, MCC: 0.0822, F1: 0.6593

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14393 | val 0.23403
  Epoch 011 - train 0.14506 | val 0.23568
  Regression -> MSE: 0.000156, MAE: 0.009562, R²: -0.0024
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15945 | val 0.14097
  Epoch 011 - train 0.15739 | val 0.14199
  Regression -> MSE: 0.000280, MAE: 0.013421, R²: -0.0289
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14206 | val 0.18460
  Epoch 011 - train 0.13587 | val 0.18489
  Regression -> MSE: 0.000165, MAE: 0.009079, R²: -0.1016
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15602 | val 0.19955
  Epoch 011 - train 0.15875 | val 0.20023
  Regression -> MSE: 0.000253, MAE: 0.011384, R²: -0.1198
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17269 | val 0.17337
  Epoch 011 - train 0.16843 | val 0.17300
  Regression -> MSE: 0.000144, MAE: 0.008309, R²: -0.0013
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14717 | val 0.16403
  Epoch 011 - train 0.15305 | val 0.16404
  Regression -> MSE: 0.000167, MAE: 0.010286, R²: -0.0115
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16054 | val 0.16863
  Epoch 011 - train 0.15529 | val 0.16879
  Regression -> MSE: 0.000093, MAE: 0.007429, R²: -0.0883
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15855 | val 0.16980
  Epoch 011 - train 0.14844 | val 0.16950
  Regression -> MSE: 0.000214, MAE: 0.011394, R²: -0.0119
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14964 | val 0.12639
  Epoch 011 - train 0.13679 | val 0.12642
  Regression -> MSE: 0.000098, MAE: 0.008173, R²: -0.0622
  Directional -> Accuracy: 0.5714, MCC: 0.1054, F1: 0.7143

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.15545 | val 0.11683
  Epoch 011 - train 0.15763 | val 0.11670
  Regression -> MSE: 0.000115, MAE: 0.009193, R²: -0.1181
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16185 | val 0.13325
  Epoch 011 - train 0.16204 | val 0.13322
  Regression -> MSE: 0.000237, MAE: 0.012735, R²: -0.0227
  Directional -> Accuracy: 0.5349, MCC: 0.1734, F1: 0.4444

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14873 | val 0.16010
  Epoch 011 - train 0.14141 | val 0.15976
  Regression -> MSE: 0.000187, MAE: 0.008100, R²: -0.1249
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14976 | val 0.12124
  Epoch 011 - train 0.15007 | val 0.12121
  Regression -> MSE: 0.000238, MAE: 0.011908, R²: -0.0050
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.15067 | val 0.21757
  Epoch 011 - train 0.15916 | val 0.21766
  Regression -> MSE: 0.000230, MAE: 0.009869, R²: -0.0002
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.17129 | val 0.16802
  Epoch 011 - train 0.16142 | val 0.16873
  Regression -> MSE: 0.000135, MAE: 0.008206, R²: 0.0009
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15569 | val 0.17597
  Epoch 011 - train 0.14919 | val 0.17582
  Regression -> MSE: 0.000189, MAE: 0.010424, R²: -0.0040
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14397 | val 0.16816
  Epoch 011 - train 0.14319 | val 0.16825
  Regression -> MSE: 0.000262, MAE: 0.010577, R²: -0.0005
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14238 | val 0.12471
  Epoch 011 - train 0.13355 | val 0.12437
  Regression -> MSE: 0.000169, MAE: 0.010373, R²: -0.0128
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14567 | val 0.14566
  Epoch 011 - train 0.14904 | val 0.14517
  Regression -> MSE: 0.000185, MAE: 0.010526, R²: -0.0299
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15911 | val 0.13215
  Epoch 011 - train 0.15416 | val 0.13265
  Regression -> MSE: 0.000351, MAE: 0.012400, R²: -0.0232
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16756 | val 0.09221
  Epoch 011 - train 0.16582 | val 0.09213
  Regression -> MSE: 0.000111, MAE: 0.008323, R²: -0.0512
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16050 | val 0.18885
  Epoch 011 - train 0.14475 | val 0.18877
  Regression -> MSE: 0.000222, MAE: 0.011390, R²: -0.0150
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14650 | val 0.24257
  Epoch 011 - train 0.15440 | val 0.24280
  Regression -> MSE: 0.000082, MAE: 0.007052, R²: -0.0545
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13825 | val 0.12129
  Epoch 011 - train 0.15261 | val 0.12133
  Regression -> MSE: 0.000340, MAE: 0.015387, R²: -0.1065
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15642 | val 0.08576
  Epoch 011 - train 0.15227 | val 0.08565
  Regression -> MSE: 0.000255, MAE: 0.011469, R²: -0.0455
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14574 | val 0.16902
  Epoch 011 - train 0.14593 | val 0.16980
  Regression -> MSE: 0.000085, MAE: 0.007054, R²: -0.0460
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16239 | val 0.16861
  Epoch 011 - train 0.15649 | val 0.16829
  Regression -> MSE: 0.000310, MAE: 0.014526, R²: -0.0100
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16288 | val 0.14646
  Epoch 011 - train 0.16330 | val 0.14642
  Regression -> MSE: 0.000098, MAE: 0.007324, R²: -0.0016
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15308 | val 0.16395
  Epoch 011 - train 0.15566 | val 0.16399
  Regression -> MSE: 0.000173, MAE: 0.009856, R²: -0.0044
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13722 | val 0.15758
  Epoch 011 - train 0.13919 | val 0.15754
  Regression -> MSE: 0.000224, MAE: 0.011766, R²: -0.0023
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14713 | val 0.15318
  Epoch 011 - train 0.15247 | val 0.15371
  Regression -> MSE: 0.000092, MAE: 0.007653, R²: 0.0003
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.14904 | val 0.21907
  Epoch 011 - train 0.15512 | val 0.21899
  Regression -> MSE: 0.000166, MAE: 0.010313, R²: -0.0140
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.15552 | val 0.16795
  Epoch 011 - train 0.15134 | val 0.16782
  Regression -> MSE: 0.000127, MAE: 0.009056, R²: -0.0984
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 03:57:01,123] Trial 155 finished with value: -0.011464883753154138 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 4.69463861168354e-05, 'weight_decay': 1.1717603974587577e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.2114808034014942, 'early_stopping_min_delta': 0.006660361349181819}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 010 - train 0.16067 | val 0.19048
  Epoch 011 - train 0.15442 | val 0.19018
  Regression -> MSE: 0.000239, MAE: 0.012323, R²: -0.0076
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.47013 | val 0.63607
  Epoch 011 - train 0.45573 | val 0.63477
  Regression -> MSE: 0.000248, MAE: 0.012549, R²: -0.0016
  Directional -> Accuracy: 0.4545, MCC: -0.0311, F1: 0.5962

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.46736 | val 0.40836
  Epoch 011 - train 0.49053 | val 0.40983
  Regression -> MSE: 0.000704, MAE: 0.019639, R²: -0.0286
  Directional -> Accuracy: 0.4348, MCC: -0.0406, F1: 0.1333

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.48718 | val 0.82498
  Epoch 011 - train 0.46827 | val 0.82533
  Regression -> MSE: 0.000312, MAE: 0.014428, R²: -0.0054
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.34412 | val 0.39445
  Epoch 011 - train 0.36698 | val 0.41148
  Regression -> MSE: 0.000366, MAE: 0.014840, R²: -0.0469
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.39564 | val 0.41794
  Epoch 011 - train 0.41427 | val 0.41691
  Regression -> MSE: 0.000204, MAE: 0.010097, R²: -0.0034
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.42311 | val 0.98514
  Epoch 011 - train 0.42431 | val 0.98486
  Regression -> MSE: 0.000586, MAE: 0.018695, R²: -0.0554
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.44431 | val 0.56258
  Epoch 020 - train 0.46102 | val 0.55666
  Epoch 021 - train 0.45079 | val 0.55703
  Regression -> MSE: 0.000245, MAE: 0.012199, R²: 0.0021
  Directional -> Accuracy: 0.4783, MCC: 0.1799, F1: 0.6000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.43795 | val 0.59521
  Epoch 011 - train 0.41048 | val 0.59588
  Regression -> MSE: 0.000621, MAE: 0.019709, R²: -0.0395
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.50208 | val 0.57698
  Epoch 011 - train 0.47746 | val 0.57745
  Regression -> MSE: 0.000385, MAE: 0.016214, R²: -0.0028
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.45734 | val 0.59062
  Epoch 011 - train 0.43528 | val 0.59227
  Regression -> MSE: 0.000241, MAE: 0.011909, R²: 0.0015
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.42462 | val 0.68351
  Epoch 011 - train 0.41730 | val 0.68905
  Regression -> MSE: 0.000315, MAE: 0.013617, R²: -0.0134
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.48128 | val 0.53208
  Epoch 011 - train 0.49857 | val 0.53270
  Regression -> MSE: 0.000678, MAE: 0.019504, R²: -0.0013
  Directional -> Accuracy: 0.4138, MCC: -0.1741, F1: 0.3704

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.48224 | val 0.42774
  Epoch 011 - train 0.46234 | val 0.42819
  Regression -> MSE: 0.000141, MAE: 0.009367, R²: -0.0231
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.41462 | val 0.61063
  Epoch 011 - train 0.41345 | val 0.60963
  Regression -> MSE: 0.000225, MAE: 0.010701, R²: -0.0017
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.46023 | val 1.09455
  Epoch 011 - train 0.46021 | val 1.09429
  Regression -> MSE: 0.000370, MAE: 0.015925, R²: -0.0203
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48178 | val 0.44901
  Epoch 011 - train 0.48275 | val 0.45211
  Regression -> MSE: 0.000109, MAE: 0.007948, R²: -0.0094
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.44487 | val 0.82773
  Epoch 019 - train 0.43002 | val 0.84178
  Regression -> MSE: 0.000160, MAE: 0.010030, R²: -0.0282
  Directional -> Accuracy: 0.6102, MCC: 0.1437, F1: 0.7013

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.49111 | val 0.45132
  Epoch 011 - train 0.47923 | val 0.45434
  Regression -> MSE: 0.000288, MAE: 0.013747, R²: -0.0570
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.42004 | val 0.62529
  Epoch 011 - train 0.37014 | val 0.62949
  Regression -> MSE: 0.000168, MAE: 0.009112, R²: -0.1200
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45487 | val 0.75811
  Epoch 011 - train 0.46244 | val 0.76509
  Regression -> MSE: 0.000239, MAE: 0.011037, R²: -0.0581
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.43944 | val 0.58573
  Epoch 011 - train 0.45939 | val 0.58513
  Regression -> MSE: 0.000148, MAE: 0.008629, R²: -0.0357
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.43350 | val 0.50080
  Epoch 011 - train 0.42207 | val 0.50253
  Regression -> MSE: 0.000177, MAE: 0.010293, R²: -0.0692
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.50632 | val 0.54486
  Epoch 011 - train 0.46638 | val 0.54430
  Regression -> MSE: 0.000087, MAE: 0.007149, R²: -0.0197
  Directional -> Accuracy: 0.5690, MCC: 0.0636, F1: 0.6914

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.47437 | val 0.57361
  Epoch 011 - train 0.46022 | val 0.58086
  Regression -> MSE: 0.000215, MAE: 0.011066, R²: -0.0159
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41670 | val 0.34558
  Epoch 011 - train 0.41396 | val 0.34476
  Regression -> MSE: 0.000093, MAE: 0.008100, R²: -0.0116
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.48428 | val 0.32437
  Epoch 011 - train 0.48808 | val 0.32411
  Regression -> MSE: 0.000114, MAE: 0.009141, R²: -0.1024
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.48270 | val 0.40583
  Epoch 011 - train 0.50893 | val 0.40585
  Regression -> MSE: 0.000232, MAE: 0.012516, R²: -0.0020
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.45489 | val 0.52637
  Epoch 020 - train 0.42108 | val 0.51990
  Epoch 024 - train 0.44801 | val 0.52123
  Regression -> MSE: 0.000178, MAE: 0.007999, R²: -0.0668
  Directional -> Accuracy: 0.4737, MCC: -0.1000, F1: 0.5714

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.52842 | val 0.28300
  Epoch 011 - train 0.44278 | val 0.28270
  Regression -> MSE: 0.000238, MAE: 0.011891, R²: -0.0050
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.47280 | val 0.80789
  Epoch 011 - train 0.43104 | val 0.80768
  Regression -> MSE: 0.000231, MAE: 0.009880, R²: -0.0005
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.48594 | val 0.54614
  Epoch 011 - train 0.49705 | val 0.54728
  Regression -> MSE: 0.000135, MAE: 0.008173, R²: -0.0018
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45456 | val 0.57089
  Epoch 011 - train 0.44878 | val 0.57071
  Regression -> MSE: 0.000195, MAE: 0.010497, R²: -0.0348
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.40969 | val 0.54370
  Epoch 011 - train 0.38758 | val 0.54589
  Regression -> MSE: 0.000266, MAE: 0.010532, R²: -0.0172
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.49807 | val 0.35211
  Epoch 011 - train 0.50983 | val 0.35223
  Regression -> MSE: 0.000168, MAE: 0.010385, R²: -0.0084
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.46058 | val 0.44839
  Epoch 011 - train 0.44926 | val 0.44828
  Regression -> MSE: 0.000181, MAE: 0.010303, R²: -0.0061
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.44356 | val 0.40375
  Epoch 011 - train 0.43347 | val 0.40429
  Regression -> MSE: 0.000345, MAE: 0.012058, R²: -0.0055
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.51110 | val 0.22572
  Epoch 011 - train 0.50083 | val 0.22545
  Regression -> MSE: 0.000118, MAE: 0.008316, R²: -0.1179
  Directional -> Accuracy: 0.5116, MCC: 0.0849, F1: 0.1600

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.46828 | val 0.67085
  Epoch 011 - train 0.45204 | val 0.67060
  Regression -> MSE: 0.000218, MAE: 0.011285, R²: 0.0004
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.43155 | val 0.90961
  Epoch 011 - train 0.48634 | val 0.90916
  Regression -> MSE: 0.000095, MAE: 0.007607, R²: -0.2249
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46369 | val 0.26562
  Epoch 011 - train 0.45421 | val 0.26558
  Regression -> MSE: 0.000310, MAE: 0.013920, R²: -0.0082
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.45778 | val 0.20633
  Epoch 020 - train 0.51287 | val 0.19857
  Epoch 030 - train 0.44709 | val 0.19429
  Regression -> MSE: 0.000260, MAE: 0.011519, R²: -0.0649
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.45389 | val 0.54045
  Epoch 011 - train 0.42379 | val 0.54072
  Regression -> MSE: 0.000085, MAE: 0.007059, R²: -0.0541
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.50699 | val 0.63586
  Epoch 011 - train 0.50606 | val 0.63901
  Regression -> MSE: 0.000315, MAE: 0.014527, R²: -0.0262
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.42818 | val 0.47330
  Epoch 011 - train 0.42955 | val 0.47314
  Regression -> MSE: 0.000098, MAE: 0.007246, R²: 0.0008
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.56564 | val 0.60240
  Epoch 011 - train 0.52651 | val 0.60251
  Regression -> MSE: 0.000173, MAE: 0.009874, R²: -0.0039
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.42306 | val 0.51661
  Epoch 011 - train 0.44984 | val 0.51834
  Regression -> MSE: 0.000224, MAE: 0.011788, R²: -0.0037
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.45158 | val 0.49323
  Epoch 011 - train 0.42288 | val 0.49392
  Regression -> MSE: 0.000092, MAE: 0.007633, R²: 0.0011
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.46297 | val 0.79128
  Epoch 011 - train 0.46515 | val 0.79134
  Regression -> MSE: 0.000166, MAE: 0.010306, R²: -0.0124
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.42993 | val 0.56677
  Epoch 011 - train 0.44683 | val 0.56831
  Regression -> MSE: 0.000128, MAE: 0.009070, R²: -0.1080
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 03:57:52,052] Trial 156 finished with value: -0.011447928454266914 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 2.508306461309521e-05, 'weight_decay': 7.315571632519195e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 1.1212027593954685, 'early_stopping_min_delta': 0.007065368326822037}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 010 - train 0.52895 | val 0.71491
  Epoch 011 - train 0.52890 | val 0.71624
  Regression -> MSE: 0.000245, MAE: 0.012365, R²: -0.0315
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.28447 | val 0.37849
  Epoch 011 - train 0.29371 | val 0.37909
  Regression -> MSE: 0.000253, MAE: 0.012755, R²: -0.0203
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.30634 | val 0.25068
  Epoch 011 - train 0.30558 | val 0.25086
  Regression -> MSE: 0.000714, MAE: 0.019845, R²: -0.0424
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.28631 | val 0.46988
  Epoch 011 - train 0.30440 | val 0.46953
  Regression -> MSE: 0.000315, MAE: 0.014439, R²: -0.0150
  Directional -> Accuracy: 0.5319, MCC: 0.1529, F1: 0.3125

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.26197 | val 0.22863
  Epoch 011 - train 0.25007 | val 0.23486
  Regression -> MSE: 0.000360, MAE: 0.014750, R²: -0.0295
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.28837 | val 0.27156
  Epoch 011 - train 0.28998 | val 0.27141
  Regression -> MSE: 0.000206, MAE: 0.010112, R²: -0.0127
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.28404 | val 0.54551
  Epoch 011 - train 0.28909 | val 0.54500
  Regression -> MSE: 0.000570, MAE: 0.018390, R²: -0.0274
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.30033 | val 0.34730
  Epoch 011 - train 0.31471 | val 0.34720
  Regression -> MSE: 0.000252, MAE: 0.011975, R²: -0.0258
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.28532 | val 0.39305
  Epoch 011 - train 0.31237 | val 0.39323
  Regression -> MSE: 0.000646, MAE: 0.020189, R²: -0.0814
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.30039 | val 0.33308
  Epoch 011 - train 0.25241 | val 0.33336
  Regression -> MSE: 0.000394, MAE: 0.015982, R²: -0.0275
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.29275 | val 0.35385
  Epoch 011 - train 0.29201 | val 0.35365
  Regression -> MSE: 0.000249, MAE: 0.011630, R²: -0.0293
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.28349 | val 0.42907
  Epoch 011 - train 0.30580 | val 0.42942
  Regression -> MSE: 0.000312, MAE: 0.013851, R²: -0.0032
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.28810 | val 0.32310
  Epoch 011 - train 0.29075 | val 0.32424
  Regression -> MSE: 0.000678, MAE: 0.019483, R²: -0.0006
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.30817 | val 0.29230
  Epoch 011 - train 0.29096 | val 0.29375
  Regression -> MSE: 0.000139, MAE: 0.008998, R²: -0.0057
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.30256 | val 0.38327
  Epoch 011 - train 0.30014 | val 0.38386
  Regression -> MSE: 0.000226, MAE: 0.010873, R²: -0.0059
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.31515 | val 0.59431
  Epoch 011 - train 0.30411 | val 0.59538
  Regression -> MSE: 0.000362, MAE: 0.016028, R²: -0.0009
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.29734 | val 0.27984
  Epoch 011 - train 0.30004 | val 0.28009
  Regression -> MSE: 0.000108, MAE: 0.008057, R²: -0.0034
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.30108 | val 0.46333
  Epoch 011 - train 0.28885 | val 0.46309
  Regression -> MSE: 0.000162, MAE: 0.010202, R²: -0.0409
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.29099 | val 0.27141
  Epoch 011 - train 0.30648 | val 0.27079
  Regression -> MSE: 0.000284, MAE: 0.013599, R²: -0.0431
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.26831 | val 0.37955
  Epoch 011 - train 0.26889 | val 0.37983
  Regression -> MSE: 0.000151, MAE: 0.008750, R²: -0.0083
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.31551 | val 0.40364
  Epoch 011 - train 0.30491 | val 0.40324
  Regression -> MSE: 0.000242, MAE: 0.011113, R²: -0.0679
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.31997 | val 0.34742
  Epoch 011 - train 0.29649 | val 0.34764
  Regression -> MSE: 0.000145, MAE: 0.008459, R²: -0.0124
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.26618 | val 0.33991
  Epoch 011 - train 0.29731 | val 0.34205
  Regression -> MSE: 0.000165, MAE: 0.010571, R²: -0.0008
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.30672 | val 0.32937
  Epoch 011 - train 0.30735 | val 0.32835
  Regression -> MSE: 0.000091, MAE: 0.007338, R²: -0.0631
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.28972 | val 0.34066
  Epoch 019 - train 0.27466 | val 0.34821
  Regression -> MSE: 0.000214, MAE: 0.011230, R²: -0.0081
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.28585 | val 0.23967
  Epoch 011 - train 0.27818 | val 0.23938
  Regression -> MSE: 0.000094, MAE: 0.008106, R²: -0.0195
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.29438 | val 0.21568
  Epoch 011 - train 0.30983 | val 0.21566
  Regression -> MSE: 0.000111, MAE: 0.009062, R²: -0.0791
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.29325 | val 0.25957
  Epoch 011 - train 0.29535 | val 0.25941
  Regression -> MSE: 0.000239, MAE: 0.012830, R²: -0.0341
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.30704 | val 0.33956
  Epoch 011 - train 0.29193 | val 0.33956
  Regression -> MSE: 0.000170, MAE: 0.007844, R²: -0.0206
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.25481 | val 0.22355
  Epoch 011 - train 0.27548 | val 0.22360
  Regression -> MSE: 0.000237, MAE: 0.011870, R²: -0.0000
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.30129 | val 0.48045
  Epoch 011 - train 0.30824 | val 0.48117
  Regression -> MSE: 0.000236, MAE: 0.010234, R²: -0.0252
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.31197 | val 0.32693
  Epoch 011 - train 0.31981 | val 0.32717
  Regression -> MSE: 0.000135, MAE: 0.008201, R²: -0.0031
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.32568 | val 0.35100
  Epoch 011 - train 0.30394 | val 0.35136
  Regression -> MSE: 0.000193, MAE: 0.010413, R²: -0.0249
  Directional -> Accuracy: 0.5200, MCC: 0.1411, F1: 0.2941

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.26293 | val 0.31237
  Epoch 020 - train 0.24584 | val 0.30188
  Epoch 022 - train 0.24050 | val 0.30223
  Regression -> MSE: 0.000281, MAE: 0.010964, R²: -0.0717
  Directional -> Accuracy: 0.4932, MCC: 0.0797, F1: 0.3273

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.31717 | val 0.22354
  Epoch 011 - train 0.30903 | val 0.22363
  Regression -> MSE: 0.000170, MAE: 0.010370, R²: -0.0184
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.27344 | val 0.28903
  Epoch 011 - train 0.27350 | val 0.28827
  Regression -> MSE: 0.000186, MAE: 0.010541, R²: -0.0322
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.26875 | val 0.25465
  Epoch 011 - train 0.27348 | val 0.25504
  Regression -> MSE: 0.000342, MAE: 0.011923, R²: 0.0005
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.32043 | val 0.16043
  Epoch 011 - train 0.32687 | val 0.16032
  Regression -> MSE: 0.000114, MAE: 0.008310, R²: -0.0834
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.35296 | val 0.38406
  Epoch 011 - train 0.32498 | val 0.38492
  Regression -> MSE: 0.000219, MAE: 0.011307, R²: -0.0021
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.31332 | val 0.49993
  Epoch 011 - train 0.30787 | val 0.49981
  Regression -> MSE: 0.000084, MAE: 0.007156, R²: -0.0841
  Directional -> Accuracy: 0.3830, MCC: -0.0508, F1: 0.0645

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.28406 | val 0.20142
  Epoch 011 - train 0.28043 | val 0.20153
  Regression -> MSE: 0.000316, MAE: 0.014283, R²: -0.0266
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.32224 | val 0.14714
  Epoch 011 - train 0.30350 | val 0.14720
  Regression -> MSE: 0.000247, MAE: 0.011525, R²: -0.0130
  Directional -> Accuracy: 0.5000, MCC: 0.1560, F1: 0.0952

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.29168 | val 0.32822
  Epoch 011 - train 0.28993 | val 0.32899
  Regression -> MSE: 0.000081, MAE: 0.007061, R²: -0.0023
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.32031 | val 0.34372
  Epoch 011 - train 0.30444 | val 0.34364
  Regression -> MSE: 0.000307, MAE: 0.014495, R²: 0.0002
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.29442 | val 0.28530
  Epoch 011 - train 0.28084 | val 0.28521
  Regression -> MSE: 0.000098, MAE: 0.007386, R²: -0.0021
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.35469 | val 0.35035
  Epoch 011 - train 0.34993 | val 0.35064
  Regression -> MSE: 0.000174, MAE: 0.009461, R²: -0.0103
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.28389 | val 0.30737
  Epoch 011 - train 0.29473 | val 0.30792
  Regression -> MSE: 0.000227, MAE: 0.011845, R²: -0.0177
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.30865 | val 0.29847
  Epoch 011 - train 0.30520 | val 0.29916
  Regression -> MSE: 0.000092, MAE: 0.007626, R²: 0.0022
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.32984 | val 0.44326
  Epoch 011 - train 0.32145 | val 0.44431
  Regression -> MSE: 0.000164, MAE: 0.010249, R²: 0.0008
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.28453 | val 0.34027
  Epoch 011 - train 0.30899 | val 0.34096
  Regression -> MSE: 0.000123, MAE: 0.008997, R²: -0.0578
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 03:58:41,834] Trial 157 finished with value: -0.011464499840418947 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 3.565088167225829e-05, 'weight_decay': 5.013563680497512e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.4934906728673622, 'early_stopping_min_delta': 0.006374503764745504}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 010 - train 0.31565 | val 0.43394
  Epoch 011 - train 0.31133 | val 0.43975
  Regression -> MSE: 0.000238, MAE: 0.012548, R²: -0.0034
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.16858 | val 0.22254
  Epoch 011 - train 0.16904 | val 0.22221
  Regression -> MSE: 0.000259, MAE: 0.012970, R²: -0.0455
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16730 | val 0.15968
  Epoch 011 - train 0.16676 | val 0.16081
  Regression -> MSE: 0.000725, MAE: 0.020000, R²: -0.0595
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16640 | val 0.27195
  Epoch 011 - train 0.16734 | val 0.27251
  Regression -> MSE: 0.000312, MAE: 0.014376, R²: -0.0049
  Directional -> Accuracy: 0.5957, MCC: 0.1864, F1: 0.6885

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13982 | val 0.13928
  Epoch 011 - train 0.13939 | val 0.13869
  Regression -> MSE: 0.000354, MAE: 0.014679, R²: -0.0131
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.17498 | val 0.16229
  Epoch 011 - train 0.17557 | val 0.16206
  Regression -> MSE: 0.000209, MAE: 0.010165, R²: -0.0250
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.17580 | val 0.30711
  Epoch 011 - train 0.16433 | val 0.30702
  Regression -> MSE: 0.000557, MAE: 0.018149, R²: -0.0037
  Directional -> Accuracy: 0.4255, MCC: -0.2144, F1: 0.5846

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.17542 | val 0.19916
  Epoch 011 - train 0.16810 | val 0.19887
  Regression -> MSE: 0.000245, MAE: 0.011966, R²: 0.0026
  Directional -> Accuracy: 0.4928, MCC: -0.0009, F1: 0.4615

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.18044 | val 0.21146
  Epoch 011 - train 0.17045 | val 0.21275
  Regression -> MSE: 0.000613, MAE: 0.019553, R²: -0.0263
  Directional -> Accuracy: 0.4773, MCC: 0.2251, F1: 0.6102

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15872 | val 0.19547
  Epoch 011 - train 0.16107 | val 0.19664
  Regression -> MSE: 0.000406, MAE: 0.016199, R²: -0.0594
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.17020 | val 0.22893
  Epoch 011 - train 0.16528 | val 0.23159
  Regression -> MSE: 0.000242, MAE: 0.011710, R²: -0.0019
  Directional -> Accuracy: 0.5286, MCC: 0.1260, F1: 0.5823

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15314 | val 0.24995
  Epoch 011 - train 0.15183 | val 0.25247
  Regression -> MSE: 0.000311, MAE: 0.013640, R²: 0.0005
  Directional -> Accuracy: 0.5000, MCC: -0.0602, F1: 0.2424

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.17589 | val 0.19955
  Epoch 011 - train 0.17076 | val 0.20164
  Regression -> MSE: 0.000678, MAE: 0.019531, R²: -0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16777 | val 0.16846
  Epoch 011 - train 0.16446 | val 0.17108
  Regression -> MSE: 0.000143, MAE: 0.009463, R²: -0.0377
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15694 | val 0.21560
  Epoch 011 - train 0.15492 | val 0.21461
  Regression -> MSE: 0.000222, MAE: 0.010622, R²: 0.0117
  Directional -> Accuracy: 0.5082, MCC: 0.0098, F1: 0.6053

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16939 | val 0.34319
  Epoch 011 - train 0.15794 | val 0.34382
  Regression -> MSE: 0.000363, MAE: 0.016017, R²: -0.0011
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.17462 | val 0.16517
  Epoch 011 - train 0.17349 | val 0.16709
  Regression -> MSE: 0.000108, MAE: 0.007887, R²: 0.0008
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.16033 | val 0.28170
  Epoch 011 - train 0.16042 | val 0.28393
  Regression -> MSE: 0.000157, MAE: 0.009725, R²: -0.0058
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.17550 | val 0.17834
  Epoch 011 - train 0.16800 | val 0.18226
  Regression -> MSE: 0.000271, MAE: 0.013027, R²: 0.0050
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14285 | val 0.21393
  Epoch 011 - train 0.15059 | val 0.21372
  Regression -> MSE: 0.000168, MAE: 0.009134, R²: -0.1213
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.17046 | val 0.23242
  Epoch 011 - train 0.16724 | val 0.23296
  Regression -> MSE: 0.000250, MAE: 0.011296, R²: -0.1038
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16684 | val 0.21005
  Epoch 011 - train 0.14899 | val 0.21191
  Regression -> MSE: 0.000143, MAE: 0.008305, R²: 0.0004
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15455 | val 0.20491
  Epoch 011 - train 0.15104 | val 0.20541
  Regression -> MSE: 0.000166, MAE: 0.010433, R²: -0.0031
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16890 | val 0.19078
  Epoch 019 - train 0.16751 | val 0.19067
  Regression -> MSE: 0.000086, MAE: 0.007195, R²: -0.0146
  Directional -> Accuracy: 0.5517, MCC: 0.1248, F1: 0.5517

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16171 | val 0.20434
  Epoch 011 - train 0.15406 | val 0.20307
  Regression -> MSE: 0.000214, MAE: 0.011360, R²: -0.0081
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.15569 | val 0.14381
  Epoch 020 - train 0.14131 | val 0.13630
  Epoch 024 - train 0.14918 | val 0.13494
  Regression -> MSE: 0.000094, MAE: 0.007948, R²: -0.0243
  Directional -> Accuracy: 0.5714, MCC: 0.1476, F1: 0.5862

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17360 | val 0.13280
  Epoch 011 - train 0.18527 | val 0.13296
  Regression -> MSE: 0.000107, MAE: 0.008959, R²: -0.0401
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.18505 | val 0.15476
  Epoch 011 - train 0.17774 | val 0.15462
  Regression -> MSE: 0.000234, MAE: 0.012653, R²: -0.0118
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.16170 | val 0.19462
  Epoch 018 - train 0.15359 | val 0.19422
  Regression -> MSE: 0.000189, MAE: 0.008160, R²: -0.1341
  Directional -> Accuracy: 0.5263, MCC: 0.2741, F1: 0.2703

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.18121 | val 0.15340
  Epoch 011 - train 0.19294 | val 0.15389
  Regression -> MSE: 0.000242, MAE: 0.012114, R²: -0.0243
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16392 | val 0.26564
  Epoch 011 - train 0.16983 | val 0.26555
  Regression -> MSE: 0.000231, MAE: 0.009963, R²: -0.0032
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16007 | val 0.19310
  Epoch 011 - train 0.16399 | val 0.19368
  Regression -> MSE: 0.000135, MAE: 0.008164, R²: -0.0024
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.17009 | val 0.20306
  Epoch 011 - train 0.16249 | val 0.20261
  Regression -> MSE: 0.000192, MAE: 0.010416, R²: -0.0203
  Directional -> Accuracy: 0.6000, MCC: 0.2163, F1: 0.5833

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14464 | val 0.18429
  Epoch 020 - train 0.14565 | val 0.18051
  Regression -> MSE: 0.000277, MAE: 0.011025, R²: -0.0587
  Directional -> Accuracy: 0.4521, MCC: -0.0217, F1: 0.2593

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16246 | val 0.14293
  Epoch 011 - train 0.15611 | val 0.14301
  Regression -> MSE: 0.000167, MAE: 0.010392, R²: -0.0022
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15317 | val 0.16691
  Epoch 011 - train 0.15093 | val 0.16730
  Regression -> MSE: 0.000183, MAE: 0.010347, R²: -0.0175
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15438 | val 0.15560
  Epoch 011 - train 0.15100 | val 0.15612
  Regression -> MSE: 0.000343, MAE: 0.011980, R²: -0.0019
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18385 | val 0.10969
  Epoch 011 - train 0.18429 | val 0.10967
  Regression -> MSE: 0.000111, MAE: 0.008414, R²: -0.0513
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17471 | val 0.22169
  Epoch 011 - train 0.16366 | val 0.22187
  Regression -> MSE: 0.000219, MAE: 0.011290, R²: -0.0023
  Directional -> Accuracy: 0.5439, MCC: 0.1409, F1: 0.0714

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.17081 | val 0.29161
  Epoch 011 - train 0.15997 | val 0.29150
  Regression -> MSE: 0.000082, MAE: 0.007098, R²: -0.0598
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.17272 | val 0.12973
  Epoch 011 - train 0.16270 | val 0.13033
  Regression -> MSE: 0.000314, MAE: 0.014264, R²: -0.0218
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.18644 | val 0.10010
  Epoch 011 - train 0.17176 | val 0.10053
  Regression -> MSE: 0.000247, MAE: 0.011568, R²: -0.0114
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15027 | val 0.20062
  Epoch 011 - train 0.14974 | val 0.20151
  Regression -> MSE: 0.000082, MAE: 0.007082, R²: -0.0087
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.18138 | val 0.20235
  Epoch 011 - train 0.17579 | val 0.20224
  Regression -> MSE: 0.000308, MAE: 0.014508, R²: -0.0044
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16283 | val 0.17634
  Epoch 011 - train 0.16276 | val 0.17609
  Regression -> MSE: 0.000099, MAE: 0.007249, R²: -0.0056
  Directional -> Accuracy: 0.5455, MCC: -0.0029, F1: 0.6774

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16961 | val 0.20380
  Epoch 011 - train 0.17884 | val 0.20481
  Regression -> MSE: 0.000172, MAE: 0.009708, R²: -0.0020
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14952 | val 0.18722
  Epoch 011 - train 0.15442 | val 0.18798
  Regression -> MSE: 0.000223, MAE: 0.011725, R²: 0.0007
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.17281 | val 0.18198
  Epoch 011 - train 0.15788 | val 0.18335
  Regression -> MSE: 0.000092, MAE: 0.007638, R²: -0.0001
  Directional -> Accuracy: 0.5439, MCC: 0.1026, F1: 0.5806

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.17272 | val 0.25832
  Epoch 011 - train 0.17983 | val 0.25842
  Regression -> MSE: 0.000166, MAE: 0.010306, R²: -0.0133
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.16141 | val 0.20135
  Epoch 011 - train 0.15467 | val 0.20194
  Regression -> MSE: 0.000133, MAE: 0.009153, R²: -0.1481
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 03:59:47,193] Trial 158 finished with value: -0.011438195727734581 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 0.0001014097106934278, 'weight_decay': 6.272782263892096e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.25745826542160777, 'early_stopping_min_delta': 0.006127029918160401}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 010 - train 0.16416 | val 0.23683
  Epoch 011 - train 0.16876 | val 0.23914
  Regression -> MSE: 0.000236, MAE: 0.012385, R²: 0.0028
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12414 | val 0.14701
  Epoch 011 - train 0.11851 | val 0.14757
  Regression -> MSE: 0.000252, MAE: 0.012751, R²: -0.0185
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12904 | val 0.10326
  Epoch 011 - train 0.12569 | val 0.10327
  Regression -> MSE: 0.000712, MAE: 0.019834, R²: -0.0408
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12928 | val 0.17911
  Epoch 011 - train 0.13845 | val 0.17900
  Regression -> MSE: 0.000321, MAE: 0.014533, R²: -0.0357
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11295 | val 0.09912
  Epoch 011 - train 0.11452 | val 0.10070
  Regression -> MSE: 0.000351, MAE: 0.014573, R²: -0.0039
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13034 | val 0.10969
  Epoch 011 - train 0.12597 | val 0.10967
  Regression -> MSE: 0.000208, MAE: 0.010141, R²: -0.0230
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11465 | val 0.20640
  Epoch 011 - train 0.10649 | val 0.20639
  Regression -> MSE: 0.000578, MAE: 0.018543, R²: -0.0417
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13636 | val 0.13826
  Epoch 011 - train 0.12436 | val 0.13798
  Regression -> MSE: 0.000250, MAE: 0.012503, R²: -0.0188
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13592 | val 0.14430
  Epoch 011 - train 0.13124 | val 0.14492
  Regression -> MSE: 0.000619, MAE: 0.019680, R²: -0.0354
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12308 | val 0.13232
  Epoch 011 - train 0.11970 | val 0.13238
  Regression -> MSE: 0.000399, MAE: 0.016036, R²: -0.0395
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12998 | val 0.13846
  Epoch 011 - train 0.12696 | val 0.13866
  Regression -> MSE: 0.000243, MAE: 0.012050, R²: -0.0047
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11506 | val 0.15445
  Epoch 011 - train 0.11970 | val 0.15400
  Regression -> MSE: 0.000316, MAE: 0.013603, R²: -0.0155
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12505 | val 0.12908
  Epoch 011 - train 0.12608 | val 0.12940
  Regression -> MSE: 0.000679, MAE: 0.019595, R²: -0.0023
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12978 | val 0.11662
  Epoch 011 - train 0.12966 | val 0.11640
  Regression -> MSE: 0.000140, MAE: 0.009014, R²: -0.0162
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12416 | val 0.16082
  Epoch 011 - train 0.12246 | val 0.16318
  Regression -> MSE: 0.000226, MAE: 0.010870, R²: -0.0069
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12139 | val 0.21872
  Epoch 011 - train 0.12775 | val 0.21879
  Regression -> MSE: 0.000374, MAE: 0.015928, R²: -0.0323
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12913 | val 0.11611
  Epoch 011 - train 0.13518 | val 0.11701
  Regression -> MSE: 0.000112, MAE: 0.007994, R²: -0.0363
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12719 | val 0.18147
  Epoch 011 - train 0.12492 | val 0.18197
  Regression -> MSE: 0.000155, MAE: 0.009562, R²: 0.0037
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12450 | val 0.11655
  Epoch 011 - train 0.12726 | val 0.11797
  Regression -> MSE: 0.000288, MAE: 0.013803, R²: -0.0586
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12179 | val 0.14517
  Epoch 011 - train 0.11803 | val 0.14554
  Regression -> MSE: 0.000184, MAE: 0.009705, R²: -0.2298
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12720 | val 0.16063
  Epoch 011 - train 0.12321 | val 0.16130
  Regression -> MSE: 0.000248, MAE: 0.011271, R²: -0.0939
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13688 | val 0.13511
  Epoch 011 - train 0.13652 | val 0.13527
  Regression -> MSE: 0.000150, MAE: 0.008693, R²: -0.0435
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11577 | val 0.13016
  Epoch 011 - train 0.11491 | val 0.13049
  Regression -> MSE: 0.000166, MAE: 0.010343, R²: -0.0066
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12666 | val 0.13428
  Epoch 011 - train 0.12877 | val 0.13422
  Regression -> MSE: 0.000096, MAE: 0.007571, R²: -0.1298
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12557 | val 0.13333
  Epoch 011 - train 0.11988 | val 0.13356
  Regression -> MSE: 0.000211, MAE: 0.011137, R²: 0.0034
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11538 | val 0.10016
  Epoch 011 - train 0.11927 | val 0.09997
  Regression -> MSE: 0.000103, MAE: 0.008264, R²: -0.1143
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12440 | val 0.08624
  Epoch 011 - train 0.12175 | val 0.08619
  Regression -> MSE: 0.000103, MAE: 0.008730, R²: 0.0004
  Directional -> Accuracy: 0.4783, MCC: 0.1870, F1: 0.6250

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12665 | val 0.10929
  Epoch 011 - train 0.12908 | val 0.10952
  Regression -> MSE: 0.000240, MAE: 0.012829, R²: -0.0349
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12093 | val 0.13656
  Epoch 011 - train 0.11924 | val 0.13680
  Regression -> MSE: 0.000170, MAE: 0.007837, R²: -0.0217
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13554 | val 0.09695
  Epoch 011 - train 0.11710 | val 0.09734
  Regression -> MSE: 0.000237, MAE: 0.011842, R²: -0.0003
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12634 | val 0.17334
  Epoch 011 - train 0.12406 | val 0.17337
  Regression -> MSE: 0.000231, MAE: 0.009922, R²: -0.0033
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12162 | val 0.12772
  Epoch 011 - train 0.13234 | val 0.12750
  Regression -> MSE: 0.000135, MAE: 0.008192, R²: -0.0028
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13379 | val 0.14018
  Epoch 011 - train 0.11610 | val 0.14055
  Regression -> MSE: 0.000189, MAE: 0.010411, R²: -0.0065
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11631 | val 0.13073
  Epoch 011 - train 0.11259 | val 0.13167
  Regression -> MSE: 0.000266, MAE: 0.010525, R²: -0.0154
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13995 | val 0.09264
  Epoch 011 - train 0.12668 | val 0.09251
  Regression -> MSE: 0.000169, MAE: 0.010373, R²: -0.0133
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12563 | val 0.11096
  Epoch 011 - train 0.11867 | val 0.11046
  Regression -> MSE: 0.000179, MAE: 0.010273, R²: 0.0029
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12197 | val 0.10258
  Epoch 011 - train 0.11876 | val 0.10246
  Regression -> MSE: 0.000342, MAE: 0.011796, R²: 0.0012
  Directional -> Accuracy: 0.5522, MCC: -0.0188, F1: 0.7000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13368 | val 0.07302
  Epoch 011 - train 0.15805 | val 0.07307
  Regression -> MSE: 0.000113, MAE: 0.008359, R²: -0.0749
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12739 | val 0.15498
  Epoch 011 - train 0.12753 | val 0.15541
  Regression -> MSE: 0.000225, MAE: 0.011445, R²: -0.0277
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11548 | val 0.19298
  Epoch 011 - train 0.12261 | val 0.19358
  Regression -> MSE: 0.000082, MAE: 0.007032, R²: -0.0500
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11734 | val 0.09215
  Epoch 011 - train 0.12052 | val 0.09227
  Regression -> MSE: 0.000327, MAE: 0.014845, R²: -0.0622
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12751 | val 0.06832
  Epoch 011 - train 0.13344 | val 0.06844
  Regression -> MSE: 0.000250, MAE: 0.011464, R²: -0.0240
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12121 | val 0.13158
  Epoch 011 - train 0.12708 | val 0.13155
  Regression -> MSE: 0.000081, MAE: 0.007063, R²: -0.0084
  Directional -> Accuracy: 0.4800, MCC: -0.0570, F1: 0.6355

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12702 | val 0.13422
  Epoch 011 - train 0.12732 | val 0.13392
  Regression -> MSE: 0.000308, MAE: 0.014508, R²: -0.0040
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13277 | val 0.12301
  Epoch 011 - train 0.12190 | val 0.12304
  Regression -> MSE: 0.000098, MAE: 0.007195, R²: 0.0000
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14546 | val 0.13504
  Epoch 011 - train 0.13798 | val 0.13521
  Regression -> MSE: 0.000176, MAE: 0.010239, R²: -0.0232
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12633 | val 0.12466
  Epoch 011 - train 0.12146 | val 0.12479
  Regression -> MSE: 0.000223, MAE: 0.011720, R²: 0.0005
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11634 | val 0.12056
  Epoch 011 - train 0.12568 | val 0.12074
  Regression -> MSE: 0.000093, MAE: 0.007653, R²: -0.0069
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12785 | val 0.17044
  Epoch 011 - train 0.12175 | val 0.17038
  Regression -> MSE: 0.000164, MAE: 0.010250, R²: -0.0042
  Directional -> Accuracy: 0.5556, MCC: 0.1090, F1: 0.6571

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.11802 | val 0.13493
  Epoch 011 - train 0.11839 | val 0.13527
  Regression -> MSE: 0.000123, MAE: 0.009002, R²: -0.0638
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 04:00:18,908] Trial 159 finished with value: -0.01147731460547359 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 2.2614318158481407e-05, 'weight_decay': 3.518241081508808e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 50, 'huber_delta': 0.16355348377709444, 'early_stopping_min_delta': 0.007327058097284018}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 010 - train 0.13248 | val 0.15353
  Epoch 011 - train 0.12543 | val 0.15380
  Regression -> MSE: 0.000238, MAE: 0.012366, R²: -0.0044
  Directional -> Accuracy: 0.3934, MCC: -0.2112, F1: 0.3934

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.21910 | val 0.26924
  Epoch 011 - train 0.20759 | val 0.27195
  Regression -> MSE: 0.000254, MAE: 0.012791, R²: -0.0240
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.21880 | val 0.18125
  Epoch 011 - train 0.20853 | val 0.18152
  Regression -> MSE: 0.000722, MAE: 0.019969, R²: -0.0542
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.21355 | val 0.32486
  Epoch 011 - train 0.21024 | val 0.32517
  Regression -> MSE: 0.000315, MAE: 0.014464, R²: -0.0148
  Directional -> Accuracy: 0.3617, MCC: -0.3313, F1: 0.4828

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.18127 | val 0.17284
  Epoch 011 - train 0.19616 | val 0.17771
  Regression -> MSE: 0.000350, MAE: 0.014586, R²: -0.0017
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.22127 | val 0.20028
  Epoch 011 - train 0.22796 | val 0.20164
  Regression -> MSE: 0.000204, MAE: 0.010252, R²: -0.0036
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.20861 | val 0.37125
  Epoch 011 - train 0.19697 | val 0.37157
  Regression -> MSE: 0.000561, MAE: 0.018171, R²: -0.0098
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.21425 | val 0.24227
  Epoch 011 - train 0.20789 | val 0.24252
  Regression -> MSE: 0.000248, MAE: 0.011932, R²: -0.0103
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.22740 | val 0.26839
  Epoch 011 - train 0.20589 | val 0.26905
  Regression -> MSE: 0.000639, MAE: 0.020045, R²: -0.0689
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.21884 | val 0.24415
  Epoch 011 - train 0.19501 | val 0.24405
  Regression -> MSE: 0.000387, MAE: 0.016117, R²: -0.0089
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.22704 | val 0.24837
  Epoch 011 - train 0.21857 | val 0.24854
  Regression -> MSE: 0.000245, MAE: 0.011665, R²: -0.0162
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.18053 | val 0.29099
  Epoch 011 - train 0.17850 | val 0.29188
  Regression -> MSE: 0.000311, MAE: 0.013708, R²: 0.0005
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.23437 | val 0.22182
  Epoch 011 - train 0.22509 | val 0.22211
  Regression -> MSE: 0.000685, MAE: 0.019751, R²: -0.0111
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.22048 | val 0.20128
  Epoch 011 - train 0.22070 | val 0.20171
  Regression -> MSE: 0.000138, MAE: 0.009071, R²: -0.0006
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.20055 | val 0.26380
  Epoch 011 - train 0.20058 | val 0.26338
  Regression -> MSE: 0.000226, MAE: 0.010810, R²: -0.0032
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.22038 | val 0.40022
  Epoch 011 - train 0.22893 | val 0.40113
  Regression -> MSE: 0.000366, MAE: 0.015952, R²: -0.0116
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.21013 | val 0.19561
  Epoch 011 - train 0.21713 | val 0.19571
  Regression -> MSE: 0.000109, MAE: 0.007946, R²: -0.0112
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.21150 | val 0.32558
  Epoch 011 - train 0.20296 | val 0.32726
  Regression -> MSE: 0.000157, MAE: 0.009818, R²: -0.0049
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.21175 | val 0.19296
  Epoch 011 - train 0.21686 | val 0.19215
  Regression -> MSE: 0.000274, MAE: 0.012914, R²: -0.0083
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.19966 | val 0.25563
  Epoch 011 - train 0.21051 | val 0.25528
  Regression -> MSE: 0.000171, MAE: 0.009242, R²: -0.1462
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.20290 | val 0.27417
  Epoch 011 - train 0.19811 | val 0.27418
  Regression -> MSE: 0.000230, MAE: 0.010918, R²: -0.0180
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.21882 | val 0.24587
  Epoch 011 - train 0.21928 | val 0.24531
  Regression -> MSE: 0.000144, MAE: 0.008325, R²: -0.0019
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.21069 | val 0.22171
  Epoch 011 - train 0.22107 | val 0.22139
  Regression -> MSE: 0.000182, MAE: 0.010347, R²: -0.1007
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.22613 | val 0.23054
  Epoch 011 - train 0.22815 | val 0.22975
  Regression -> MSE: 0.000092, MAE: 0.007379, R²: -0.0740
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.22795 | val 0.23245
  Epoch 011 - train 0.22593 | val 0.23315
  Regression -> MSE: 0.000211, MAE: 0.011112, R²: 0.0019
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.20637 | val 0.17190
  Epoch 011 - train 0.19326 | val 0.17169
  Regression -> MSE: 0.000095, MAE: 0.008097, R²: -0.0270
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.20740 | val 0.15811
  Epoch 011 - train 0.22040 | val 0.15824
  Regression -> MSE: 0.000114, MAE: 0.009140, R²: -0.1013
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.22298 | val 0.18408
  Epoch 011 - train 0.21443 | val 0.18410
  Regression -> MSE: 0.000231, MAE: 0.012514, R²: 0.0004
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.21199 | val 0.23071
  Epoch 011 - train 0.21372 | val 0.23034
  Regression -> MSE: 0.000174, MAE: 0.007863, R²: -0.0451
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22812 | val 0.16931
  Epoch 011 - train 0.22574 | val 0.16930
  Regression -> MSE: 0.000239, MAE: 0.011976, R²: -0.0097
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.21689 | val 0.31282
  Epoch 011 - train 0.20411 | val 0.31299
  Regression -> MSE: 0.000231, MAE: 0.009914, R²: -0.0017
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.24045 | val 0.24720
  Epoch 011 - train 0.22624 | val 0.24753
  Regression -> MSE: 0.000140, MAE: 0.008421, R²: -0.0355
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.21487 | val 0.24542
  Epoch 011 - train 0.22596 | val 0.24568
  Regression -> MSE: 0.000193, MAE: 0.010429, R²: -0.0273
  Directional -> Accuracy: 0.5200, MCC: 0.1739, F1: 0.2500

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.18307 | val 0.22110
  Epoch 011 - train 0.19001 | val 0.22103
  Regression -> MSE: 0.000265, MAE: 0.010512, R²: -0.0134
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.21259 | val 0.15904
  Epoch 011 - train 0.21518 | val 0.15903
  Regression -> MSE: 0.000167, MAE: 0.010366, R²: -0.0049
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.18652 | val 0.19830
  Epoch 011 - train 0.20673 | val 0.19833
  Regression -> MSE: 0.000181, MAE: 0.010367, R²: -0.0066
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.20472 | val 0.17677
  Epoch 011 - train 0.21717 | val 0.17641
  Regression -> MSE: 0.000342, MAE: 0.011792, R²: 0.0012
  Directional -> Accuracy: 0.5970, MCC: 0.1480, F1: 0.7273

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.21838 | val 0.11961
  Epoch 011 - train 0.21248 | val 0.11952
  Regression -> MSE: 0.000119, MAE: 0.008353, R²: -0.1354
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.22451 | val 0.26518
  Epoch 011 - train 0.22263 | val 0.26526
  Regression -> MSE: 0.000220, MAE: 0.011341, R²: -0.0058
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.21521 | val 0.34190
  Epoch 011 - train 0.22001 | val 0.34221
  Regression -> MSE: 0.000084, MAE: 0.007133, R²: -0.0765
  Directional -> Accuracy: 0.5532, MCC: -0.1299, F1: 0.7042

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.22750 | val 0.16378
  Epoch 011 - train 0.23258 | val 0.16372
  Regression -> MSE: 0.000336, MAE: 0.015202, R²: -0.0909
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.23116 | val 0.11166
  Epoch 011 - train 0.23076 | val 0.11169
  Regression -> MSE: 0.000249, MAE: 0.011521, R²: -0.0227
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.21215 | val 0.23608
  Epoch 011 - train 0.21780 | val 0.23623
  Regression -> MSE: 0.000085, MAE: 0.007051, R²: -0.0482
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.22263 | val 0.25089
  Epoch 011 - train 0.21637 | val 0.25049
  Regression -> MSE: 0.000310, MAE: 0.014487, R²: -0.0097
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.22487 | val 0.23650
  Epoch 011 - train 0.19467 | val 0.23643
  Regression -> MSE: 0.000104, MAE: 0.007113, R²: -0.0606
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.23098 | val 0.23302
  Epoch 011 - train 0.22868 | val 0.23292
  Regression -> MSE: 0.000174, MAE: 0.010045, R²: -0.0107
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.19600 | val 0.21759
  Epoch 011 - train 0.19351 | val 0.21755
  Regression -> MSE: 0.000223, MAE: 0.011763, R²: -0.0007
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.21027 | val 0.21025
  Epoch 011 - train 0.20949 | val 0.21033
  Regression -> MSE: 0.000092, MAE: 0.007625, R²: 0.0015
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.22543 | val 0.30781
  Epoch 011 - train 0.21412 | val 0.30730
  Regression -> MSE: 0.000166, MAE: 0.010290, R²: -0.0115
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.21052 | val 0.23574
  Epoch 011 - train 0.22368 | val 0.23571
  Regression -> MSE: 0.000123, MAE: 0.009002, R²: -0.0640
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 04:01:46,442] Trial 160 finished with value: -0.011438373493329126 and parameters: {'feature_set': 'base', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 1.3006346016331095e-05, 'weight_decay': 4.725760052472074e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.3131273487633891, 'early_stopping_min_delta': 0.0044871034443958084}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 010 - train 0.22440 | val 0.27618
  Epoch 011 - train 0.23110 | val 0.27803
  Regression -> MSE: 0.000238, MAE: 0.012318, R²: -0.0053
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10771 | val 0.12299
  Epoch 020 - train 0.10700 | val 0.12291
  Epoch 021 - train 0.10206 | val 0.12287
  Regression -> MSE: 0.000250, MAE: 0.012643, R²: -0.0091
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10248 | val 0.09094
  Epoch 020 - train 0.10909 | val 0.09762
  Epoch 021 - train 0.10710 | val 0.09808
  Regression -> MSE: 0.000704, MAE: 0.019694, R²: -0.0291
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10031 | val 0.15573
  Epoch 020 - train 0.10062 | val 0.16964
  Epoch 021 - train 0.10505 | val 0.16984
  Regression -> MSE: 0.000316, MAE: 0.014475, R²: -0.0197
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09455 | val 0.26608
  Epoch 020 - train 0.09121 | val 0.28005
  Epoch 021 - train 0.09347 | val 0.27746
  Regression -> MSE: 0.000376, MAE: 0.014990, R²: -0.0754
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09721 | val 0.09532
  Epoch 020 - train 0.09611 | val 0.09747
  Epoch 021 - train 0.10294 | val 0.09721
  Regression -> MSE: 0.000204, MAE: 0.010090, R²: 0.0005
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10086 | val 0.16787
  Epoch 020 - train 0.10296 | val 0.17669
  Epoch 021 - train 0.10295 | val 0.17686
  Regression -> MSE: 0.000556, MAE: 0.018158, R²: -0.0009
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10782 | val 0.12439
  Epoch 020 - train 0.10789 | val 0.12395
  Epoch 021 - train 0.10498 | val 0.12351
  Regression -> MSE: 0.000247, MAE: 0.012268, R²: -0.0044
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10618 | val 0.11738
  Epoch 020 - train 0.10201 | val 0.11994
  Epoch 021 - train 0.09996 | val 0.11970
  Regression -> MSE: 0.000615, MAE: 0.019599, R²: -0.0300
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09948 | val 0.11783
  Epoch 020 - train 0.10339 | val 0.12482
  Epoch 021 - train 0.09672 | val 0.12420
  Regression -> MSE: 0.000384, MAE: 0.016153, R²: -0.0014
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10004 | val 0.11838
  Epoch 020 - train 0.10117 | val 0.11889
  Epoch 021 - train 0.09606 | val 0.11888
  Regression -> MSE: 0.000244, MAE: 0.011658, R²: -0.0092
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09361 | val 0.13031
  Epoch 020 - train 0.09540 | val 0.12929
  Epoch 021 - train 0.09823 | val 0.12933
  Regression -> MSE: 0.000312, MAE: 0.013741, R²: -0.0034
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11444 | val 0.11941
  Epoch 020 - train 0.11321 | val 0.12360
  Epoch 021 - train 0.12259 | val 0.12313
  Regression -> MSE: 0.000690, MAE: 0.019960, R²: -0.0186
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10477 | val 0.08986
  Epoch 020 - train 0.10982 | val 0.08920
  Epoch 021 - train 0.10395 | val 0.08946
  Regression -> MSE: 0.000141, MAE: 0.009341, R²: -0.0220
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09348 | val 0.13004
  Epoch 020 - train 0.09782 | val 0.13321
  Epoch 021 - train 0.09277 | val 0.13369
  Regression -> MSE: 0.000226, MAE: 0.010712, R²: -0.0030
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10797 | val 0.18216
  Epoch 020 - train 0.09677 | val 0.18396
  Epoch 021 - train 0.10207 | val 0.18383
  Regression -> MSE: 0.000369, MAE: 0.015933, R²: -0.0193
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10731 | val 0.10271
  Epoch 020 - train 0.10641 | val 0.10317
  Epoch 021 - train 0.10464 | val 0.10328
  Regression -> MSE: 0.000109, MAE: 0.007942, R²: -0.0115
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10278 | val 0.15784
  Epoch 020 - train 0.11500 | val 0.16666
  Epoch 021 - train 0.10686 | val 0.16744
  Regression -> MSE: 0.000158, MAE: 0.009898, R²: -0.0122
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10444 | val 0.10472
  Epoch 020 - train 0.10378 | val 0.10574
  Epoch 021 - train 0.10530 | val 0.10515
  Regression -> MSE: 0.000287, MAE: 0.013709, R²: -0.0537
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09994 | val 0.12072
  Epoch 020 - train 0.10097 | val 0.12085
  Epoch 021 - train 0.10252 | val 0.12052
  Regression -> MSE: 0.000167, MAE: 0.009118, R²: -0.1142
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10489 | val 0.15065
  Epoch 020 - train 0.10735 | val 0.15091
  Epoch 021 - train 0.11060 | val 0.15077
  Regression -> MSE: 0.000241, MAE: 0.011088, R²: -0.0646
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10423 | val 0.11389
  Epoch 020 - train 0.10359 | val 0.11587
  Epoch 021 - train 0.10324 | val 0.11590
  Regression -> MSE: 0.000153, MAE: 0.008816, R²: -0.0662
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09968 | val 0.11824
  Epoch 020 - train 0.10292 | val 0.12190
  Epoch 021 - train 0.09592 | val 0.12168
  Regression -> MSE: 0.000182, MAE: 0.010360, R²: -0.1023
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11223 | val 0.11558
  Epoch 020 - train 0.11280 | val 0.11972
  Epoch 021 - train 0.11647 | val 0.11907
  Regression -> MSE: 0.000089, MAE: 0.007249, R²: -0.0414
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10612 | val 0.11085
  Epoch 020 - train 0.11526 | val 0.11168
  Epoch 021 - train 0.10662 | val 0.11140
  Regression -> MSE: 0.000212, MAE: 0.011090, R²: 0.0009
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10458 | val 0.08974
  Epoch 020 - train 0.09571 | val 0.09154
  Epoch 021 - train 0.09997 | val 0.09150
  Regression -> MSE: 0.000102, MAE: 0.008265, R²: -0.1078
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09433 | val 0.07466
  Epoch 020 - train 0.10178 | val 0.08196
  Epoch 021 - train 0.10655 | val 0.08309
  Regression -> MSE: 0.000109, MAE: 0.008993, R²: -0.0568
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09864 | val 0.08814
  Epoch 020 - train 0.10468 | val 0.09375
  Epoch 021 - train 0.10433 | val 0.09405
  Regression -> MSE: 0.000232, MAE: 0.012562, R²: -0.0024
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10338 | val 0.11089
  Epoch 020 - train 0.09637 | val 0.11329
  Epoch 021 - train 0.09704 | val 0.11325
  Regression -> MSE: 0.000173, MAE: 0.007838, R²: -0.0423
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09564 | val 0.07905
  Epoch 020 - train 0.10162 | val 0.07950
  Epoch 021 - train 0.10392 | val 0.07964
  Regression -> MSE: 0.000237, MAE: 0.011868, R²: -0.0012
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10067 | val 0.14908
  Epoch 020 - train 0.09345 | val 0.15950
  Epoch 021 - train 0.10296 | val 0.15932
  Regression -> MSE: 0.000232, MAE: 0.010016, R²: -0.0071
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09746 | val 0.10911
  Epoch 020 - train 0.10256 | val 0.11202
  Epoch 021 - train 0.10150 | val 0.11200
  Regression -> MSE: 0.000136, MAE: 0.008212, R²: -0.0040
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10969 | val 0.11941
  Epoch 020 - train 0.11204 | val 0.12645
  Epoch 021 - train 0.11103 | val 0.12625
  Regression -> MSE: 0.000192, MAE: 0.010416, R²: -0.0207
  Directional -> Accuracy: 0.5600, MCC: 0.1143, F1: 0.5926

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10110 | val 0.10793
  Epoch 020 - train 0.10016 | val 0.10741
  Epoch 021 - train 0.10657 | val 0.10720
  Regression -> MSE: 0.000287, MAE: 0.011154, R²: -0.0968
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10437 | val 0.08411
  Epoch 020 - train 0.10006 | val 0.08223
  Epoch 021 - train 0.10418 | val 0.08216
  Regression -> MSE: 0.000169, MAE: 0.010367, R²: -0.0153
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09262 | val 0.10675
  Epoch 020 - train 0.09312 | val 0.13074
  Epoch 021 - train 0.09349 | val 0.13052
  Regression -> MSE: 0.000184, MAE: 0.010483, R²: -0.0229
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11050 | val 0.09468
  Epoch 020 - train 0.10905 | val 0.09485
  Epoch 021 - train 0.11715 | val 0.09512
  Regression -> MSE: 0.000355, MAE: 0.012718, R²: -0.0367
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10432 | val 0.06153
  Epoch 020 - train 0.11593 | val 0.08234
  Epoch 021 - train 0.11363 | val 0.08357
  Regression -> MSE: 0.000120, MAE: 0.008338, R²: -0.1392
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10997 | val 0.12073
  Epoch 020 - train 0.10604 | val 0.12047
  Epoch 021 - train 0.10766 | val 0.12023
  Regression -> MSE: 0.000219, MAE: 0.011287, R²: -0.0013
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10676 | val 0.16366
  Epoch 020 - train 0.10340 | val 0.17689
  Epoch 021 - train 0.10800 | val 0.17665
  Regression -> MSE: 0.000081, MAE: 0.007002, R²: -0.0397
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10200 | val 0.07507
  Epoch 020 - train 0.11152 | val 0.06994
  Epoch 030 - train 0.10467 | val 0.06960
  Regression -> MSE: 0.000322, MAE: 0.014313, R²: -0.0474
  Directional -> Accuracy: 0.4286, MCC: 0.0335, F1: 0.5172

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10815 | val 0.05620
  Epoch 020 - train 0.11641 | val 0.06236
  Epoch 021 - train 0.11593 | val 0.06398
  Regression -> MSE: 0.000249, MAE: 0.011515, R²: -0.0215
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10824 | val 0.11493
  Epoch 020 - train 0.11218 | val 0.11447
  Epoch 021 - train 0.10389 | val 0.11481
  Regression -> MSE: 0.000081, MAE: 0.007067, R²: -0.0046
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10346 | val 0.11492
  Epoch 020 - train 0.10019 | val 0.10991
  Epoch 030 - train 0.10286 | val 0.10972
  Regression -> MSE: 0.000300, MAE: 0.014576, R²: 0.0220
  Directional -> Accuracy: 0.4468, MCC: -0.1169, F1: 0.5185

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09689 | val 0.10365
  Epoch 020 - train 0.09157 | val 0.10880
  Epoch 021 - train 0.09595 | val 0.10937
  Regression -> MSE: 0.000099, MAE: 0.007166, R²: -0.0107
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10742 | val 0.10909
  Epoch 020 - train 0.11323 | val 0.10952
  Epoch 021 - train 0.10254 | val 0.10951
  Regression -> MSE: 0.000172, MAE: 0.009573, R²: -0.0026
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10105 | val 0.12194
  Epoch 020 - train 0.09991 | val 0.12986
  Epoch 021 - train 0.10370 | val 0.12886
  Regression -> MSE: 0.000223, MAE: 0.011714, R²: -0.0009
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977


[I 2026-02-24 04:03:49,529] Trial 161 finished with value: -0.011470799667921073 and parameters: {'feature_set': 'emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 5.377148420463101e-06, 'weight_decay': 2.1587519892674085e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.13311908552519636, 'early_stopping_min_delta': 0.006840149031804479}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.10273 | val 0.12318
  Epoch 021 - train 0.10800 | val 0.12323
  Regression -> MSE: 0.000238, MAE: 0.012349, R²: -0.0035
  Directional -> Accuracy: 0.4754, MCC: -0.0244, F1: 0.5897

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14690 | val 0.20023
  Epoch 020 - train 0.14756 | val 0.20026
  Epoch 021 - train 0.13947 | val 0.20183
  Regression -> MSE: 0.000262, MAE: 0.013042, R²: -0.0564
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12885 | val 0.11762
  Epoch 020 - train 0.13913 | val 0.12290
  Epoch 021 - train 0.13480 | val 0.12243
  Regression -> MSE: 0.000718, MAE: 0.019923, R²: -0.0492
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13824 | val 0.19457
  Epoch 020 - train 0.14631 | val 0.19213
  Epoch 021 - train 0.12025 | val 0.19237
  Regression -> MSE: 0.000320, MAE: 0.014509, R²: -0.0311
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12145 | val 0.10304
  Epoch 020 - train 0.10956 | val 0.10470
  Epoch 021 - train 0.11488 | val 0.10541
  Regression -> MSE: 0.000351, MAE: 0.014608, R²: -0.0052
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14333 | val 0.11910
  Epoch 020 - train 0.13762 | val 0.11992
  Epoch 021 - train 0.13055 | val 0.12066
  Regression -> MSE: 0.000205, MAE: 0.010111, R²: -0.0057
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12806 | val 0.22235
  Epoch 020 - train 0.13726 | val 0.22048
  Epoch 021 - train 0.13897 | val 0.22047
  Regression -> MSE: 0.000576, MAE: 0.018500, R²: -0.0375
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13709 | val 0.15935
  Epoch 020 - train 0.13916 | val 0.15863
  Epoch 021 - train 0.14389 | val 0.15868
  Regression -> MSE: 0.000250, MAE: 0.012425, R²: -0.0164
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12860 | val 0.15608
  Epoch 020 - train 0.14468 | val 0.16305
  Epoch 021 - train 0.14041 | val 0.16549
  Regression -> MSE: 0.000623, MAE: 0.019758, R²: -0.0427
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13032 | val 0.14673
  Epoch 020 - train 0.13497 | val 0.14214
  Epoch 030 - train 0.13606 | val 0.14191
  Regression -> MSE: 0.000434, MAE: 0.016695, R²: -0.1302
  Directional -> Accuracy: 0.5510, MCC: 0.0306, F1: 0.1538

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13241 | val 0.17579
  Epoch 020 - train 0.14538 | val 0.18597
  Epoch 021 - train 0.13407 | val 0.18525
  Regression -> MSE: 0.000243, MAE: 0.011690, R²: -0.0073
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13745 | val 0.18449
  Epoch 020 - train 0.13540 | val 0.20407
  Epoch 021 - train 0.12790 | val 0.20590
  Regression -> MSE: 0.000312, MAE: 0.013615, R²: -0.0039
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14307 | val 0.15434
  Epoch 020 - train 0.14747 | val 0.15954
  Epoch 021 - train 0.14480 | val 0.16034
  Regression -> MSE: 0.000682, MAE: 0.019535, R²: -0.0068
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13289 | val 0.12050
  Epoch 020 - train 0.12566 | val 0.12610
  Epoch 021 - train 0.14565 | val 0.12548
  Regression -> MSE: 0.000139, MAE: 0.009030, R²: -0.0027
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12703 | val 0.17924
  Epoch 020 - train 0.12497 | val 0.18300
  Epoch 021 - train 0.12656 | val 0.18217
  Regression -> MSE: 0.000226, MAE: 0.010874, R²: -0.0052
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13265 | val 0.24293
  Epoch 020 - train 0.13147 | val 0.24082
  Epoch 021 - train 0.13480 | val 0.24122
  Regression -> MSE: 0.000362, MAE: 0.016047, R²: 0.0011
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14408 | val 0.14393
  Epoch 020 - train 0.14563 | val 0.14442
  Epoch 021 - train 0.14145 | val 0.14225
  Regression -> MSE: 0.000109, MAE: 0.008040, R²: -0.0067
  Directional -> Accuracy: 0.4571, MCC: -0.0661, F1: 0.4062

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13374 | val 0.19972
  Epoch 020 - train 0.13664 | val 0.20447
  Epoch 021 - train 0.13685 | val 0.20426
  Regression -> MSE: 0.000162, MAE: 0.010159, R²: -0.0366
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14901 | val 0.14124
  Epoch 020 - train 0.14106 | val 0.14029
  Epoch 021 - train 0.14032 | val 0.14083
  Regression -> MSE: 0.000273, MAE: 0.013092, R²: -0.0037
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11991 | val 0.16270
  Epoch 020 - train 0.11623 | val 0.16255
  Epoch 021 - train 0.11960 | val 0.16256
  Regression -> MSE: 0.000150, MAE: 0.008764, R²: -0.0055
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14549 | val 0.19428
  Epoch 020 - train 0.14205 | val 0.19624
  Epoch 021 - train 0.14570 | val 0.19587
  Regression -> MSE: 0.000257, MAE: 0.011478, R²: -0.1360
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13767 | val 0.15781
  Epoch 020 - train 0.14105 | val 0.17778
  Epoch 021 - train 0.14187 | val 0.18013
  Regression -> MSE: 0.000147, MAE: 0.008578, R²: -0.0288
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13606 | val 0.14817
  Epoch 020 - train 0.12850 | val 0.14765
  Epoch 021 - train 0.12557 | val 0.14766
  Regression -> MSE: 0.000170, MAE: 0.010287, R²: -0.0299
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13490 | val 0.16679
  Epoch 020 - train 0.13208 | val 0.17749
  Epoch 021 - train 0.14056 | val 0.17734
  Regression -> MSE: 0.000086, MAE: 0.007114, R²: -0.0148
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14305 | val 0.16143
  Epoch 020 - train 0.13725 | val 0.17371
  Epoch 021 - train 0.13339 | val 0.16839
  Regression -> MSE: 0.000212, MAE: 0.011198, R²: 0.0011
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12873 | val 0.11583
  Epoch 020 - train 0.12190 | val 0.11600
  Epoch 021 - train 0.12784 | val 0.11586
  Regression -> MSE: 0.000102, MAE: 0.008254, R²: -0.1030
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.15124 | val 0.09874
  Epoch 020 - train 0.13607 | val 0.11395
  Epoch 021 - train 0.14428 | val 0.11539
  Regression -> MSE: 0.000107, MAE: 0.008937, R²: -0.0410
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14051 | val 0.12205
  Epoch 020 - train 0.14015 | val 0.13496
  Epoch 021 - train 0.13386 | val 0.13456
  Regression -> MSE: 0.000241, MAE: 0.012873, R²: -0.0418
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14622 | val 0.14880
  Epoch 020 - train 0.13753 | val 0.14686
  Epoch 021 - train 0.14442 | val 0.14702
  Regression -> MSE: 0.000168, MAE: 0.007807, R²: -0.0120
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14704 | val 0.10414
  Epoch 020 - train 0.14817 | val 0.12177
  Epoch 021 - train 0.14758 | val 0.12450
  Regression -> MSE: 0.000237, MAE: 0.011871, R²: -0.0010
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12801 | val 0.19030
  Epoch 020 - train 0.12819 | val 0.19073
  Epoch 021 - train 0.14183 | val 0.19094
  Regression -> MSE: 0.000231, MAE: 0.009923, R²: -0.0031
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14299 | val 0.15529
  Epoch 020 - train 0.12573 | val 0.14797
  Epoch 030 - train 0.13979 | val 0.14843
  Regression -> MSE: 0.000136, MAE: 0.008366, R²: -0.0097
  Directional -> Accuracy: 0.5116, MCC: -0.0047, F1: 0.6038

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13450 | val 0.14709
  Epoch 020 - train 0.13523 | val 0.14969
  Epoch 021 - train 0.12637 | val 0.14965
  Regression -> MSE: 0.000197, MAE: 0.010603, R²: -0.0450
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12162 | val 0.14374
  Epoch 020 - train 0.12689 | val 0.14369
  Epoch 021 - train 0.12238 | val 0.14391
  Regression -> MSE: 0.000263, MAE: 0.010528, R²: -0.0026
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11997 | val 0.10849
  Epoch 020 - train 0.12418 | val 0.10461
  Epoch 021 - train 0.12438 | val 0.10442
  Regression -> MSE: 0.000169, MAE: 0.010367, R²: -0.0143
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12455 | val 0.12085
  Epoch 020 - train 0.12940 | val 0.12239
  Epoch 021 - train 0.12327 | val 0.12288
  Regression -> MSE: 0.000180, MAE: 0.010264, R²: 0.0010
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13675 | val 0.12182
  Epoch 020 - train 0.14203 | val 0.12178
  Epoch 021 - train 0.13889 | val 0.12178
  Regression -> MSE: 0.000344, MAE: 0.012008, R²: -0.0039
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14905 | val 0.07901
  Epoch 020 - train 0.14193 | val 0.08166
  Epoch 021 - train 0.13775 | val 0.08179
  Regression -> MSE: 0.000117, MAE: 0.008337, R²: -0.1107
  Directional -> Accuracy: 0.4651, MCC: -0.2158, F1: 0.6349

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13457 | val 0.16292
  Epoch 020 - train 0.12526 | val 0.16358
  Epoch 021 - train 0.14149 | val 0.16330
  Regression -> MSE: 0.000219, MAE: 0.011288, R²: -0.0007
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15138 | val 0.23200
  Epoch 020 - train 0.15053 | val 0.27761
  Epoch 021 - train 0.14002 | val 0.27576
  Regression -> MSE: 0.000083, MAE: 0.007093, R²: -0.0649
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15031 | val 0.09821
  Epoch 020 - train 0.14730 | val 0.10545
  Epoch 021 - train 0.14965 | val 0.10638
  Regression -> MSE: 0.000318, MAE: 0.014430, R²: -0.0350
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13983 | val 0.07314
  Epoch 020 - train 0.14168 | val 0.07301
  Epoch 021 - train 0.14250 | val 0.07313
  Regression -> MSE: 0.000246, MAE: 0.011563, R²: -0.0098
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13656 | val 0.15062
  Epoch 020 - train 0.13926 | val 0.15014
  Epoch 021 - train 0.13633 | val 0.14998
  Regression -> MSE: 0.000081, MAE: 0.007061, R²: -0.0004
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13775 | val 0.15123
  Epoch 020 - train 0.13904 | val 0.14404
  Epoch 030 - train 0.13473 | val 0.14314
  Regression -> MSE: 0.000323, MAE: 0.014531, R²: -0.0527
  Directional -> Accuracy: 0.5106, MCC: 0.0237, F1: 0.4889

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12098 | val 0.13272
  Epoch 020 - train 0.12340 | val 0.14309
  Epoch 021 - train 0.12907 | val 0.14366
  Regression -> MSE: 0.000099, MAE: 0.007230, R²: -0.0040
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15298 | val 0.14093
  Epoch 020 - train 0.14678 | val 0.14197
  Epoch 021 - train 0.14320 | val 0.14300
  Regression -> MSE: 0.000172, MAE: 0.009604, R²: -0.0010
  Directional -> Accuracy: 0.6122, MCC: 0.0687, F1: 0.1739

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13875 | val 0.18818
  Epoch 020 - train 0.13966 | val 0.20980
  Epoch 021 - train 0.13985 | val 0.20864
  Regression -> MSE: 0.000232, MAE: 0.011927, R²: -0.0419
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13386 | val 0.13418
  Epoch 020 - train 0.13704 | val 0.13514

[I 2026-02-24 04:06:00,355] Trial 162 finished with value: -0.011465156607427439 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 8.016021768704776e-06, 'weight_decay': 2.6516680729063974e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.1809688911935717, 'early_stopping_min_delta': 0.0075189092020739685}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.14089 | val 0.17808
  Epoch 021 - train 0.13490 | val 0.17777
  Regression -> MSE: 0.000244, MAE: 0.012350, R²: -0.0295
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15306 | val 0.19682
  Epoch 020 - train 0.15189 | val 0.19965
  Epoch 026 - train 0.14849 | val 0.19748
  Regression -> MSE: 0.000261, MAE: 0.013047, R²: -0.0535
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16509 | val 0.15188
  Epoch 020 - train 0.16005 | val 0.17765
  Epoch 021 - train 0.16866 | val 0.17769
  Regression -> MSE: 0.000689, MAE: 0.019431, R²: -0.0063
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15832 | val 0.24003
  Epoch 020 - train 0.16484 | val 0.24370
  Epoch 021 - train 0.16282 | val 0.24313
  Regression -> MSE: 0.000311, MAE: 0.014397, R²: -0.0015
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13754 | val 0.26300
  Epoch 020 - train 0.13578 | val 0.26295
  Epoch 021 - train 0.13498 | val 0.25912
  Regression -> MSE: 0.000353, MAE: 0.014611, R²: -0.0109
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15901 | val 0.15281
  Epoch 020 - train 0.14765 | val 0.16340
  Epoch 021 - train 0.16122 | val 0.16458
  Regression -> MSE: 0.000203, MAE: 0.010061, R²: 0.0019
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15408 | val 0.27953
  Epoch 020 - train 0.15327 | val 0.30143
  Epoch 021 - train 0.15448 | val 0.30431
  Regression -> MSE: 0.000593, MAE: 0.018835, R²: -0.0681
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15736 | val 0.18211
  Epoch 020 - train 0.15913 | val 0.18267
  Epoch 021 - train 0.15548 | val 0.18256
  Regression -> MSE: 0.000248, MAE: 0.012422, R²: -0.0117
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15068 | val 0.19461
  Epoch 020 - train 0.15308 | val 0.21947
  Epoch 021 - train 0.15872 | val 0.22056
  Regression -> MSE: 0.000626, MAE: 0.019806, R²: -0.0479
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13799 | val 0.17859
  Epoch 020 - train 0.15441 | val 0.20224
  Epoch 021 - train 0.15941 | val 0.20269
  Regression -> MSE: 0.000394, MAE: 0.015972, R²: -0.0276
  Directional -> Accuracy: 0.5714, MCC: 0.1005, F1: 0.2759

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16158 | val 0.18207
  Epoch 020 - train 0.16505 | val 0.18577
  Epoch 021 - train 0.15043 | val 0.18515
  Regression -> MSE: 0.000242, MAE: 0.011930, R²: -0.0013
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14145 | val 0.20237
  Epoch 020 - train 0.14742 | val 0.20828
  Epoch 021 - train 0.13910 | val 0.20932
  Regression -> MSE: 0.000327, MAE: 0.013634, R²: -0.0513
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.17966 | val 0.19043
  Epoch 020 - train 0.16742 | val 0.20068
  Epoch 021 - train 0.17718 | val 0.20079
  Regression -> MSE: 0.000687, MAE: 0.019564, R²: -0.0144
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.15615 | val 0.14289
  Epoch 020 - train 0.16508 | val 0.16953
  Epoch 021 - train 0.16570 | val 0.16943
  Regression -> MSE: 0.000142, MAE: 0.009405, R²: -0.0299
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15148 | val 0.19995
  Epoch 020 - train 0.14864 | val 0.19755
  Epoch 021 - train 0.14771 | val 0.19826
  Regression -> MSE: 0.000226, MAE: 0.010872, R²: -0.0042
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14864 | val 0.29291
  Epoch 020 - train 0.15438 | val 0.29518
  Epoch 021 - train 0.14949 | val 0.29487
  Regression -> MSE: 0.000374, MAE: 0.015925, R²: -0.0330
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15982 | val 0.15963
  Epoch 020 - train 0.15506 | val 0.16499
  Epoch 021 - train 0.15815 | val 0.16320
  Regression -> MSE: 0.000108, MAE: 0.008056, R²: 0.0000
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15166 | val 0.25642
  Epoch 020 - train 0.14083 | val 0.26317
  Epoch 021 - train 0.14545 | val 0.26386
  Regression -> MSE: 0.000160, MAE: 0.010050, R²: -0.0235
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16602 | val 0.18099
  Epoch 020 - train 0.16581 | val 0.17562
  Epoch 021 - train 0.15731 | val 0.17671
  Regression -> MSE: 0.000279, MAE: 0.013406, R²: -0.0261
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14318 | val 0.21195
  Epoch 020 - train 0.13939 | val 0.21562
  Epoch 021 - train 0.14229 | val 0.21640
  Regression -> MSE: 0.000149, MAE: 0.008773, R²: 0.0022
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15444 | val 0.22207
  Epoch 020 - train 0.15542 | val 0.22531
  Epoch 021 - train 0.15227 | val 0.22577
  Regression -> MSE: 0.000227, MAE: 0.010940, R²: -0.0020
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15403 | val 0.17941
  Epoch 020 - train 0.16392 | val 0.18129
  Epoch 021 - train 0.15721 | val 0.18149
  Regression -> MSE: 0.000152, MAE: 0.008757, R²: -0.0580
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15619 | val 0.17636
  Epoch 020 - train 0.14078 | val 0.17417
  Epoch 021 - train 0.14942 | val 0.17409
  Regression -> MSE: 0.000166, MAE: 0.010668, R²: -0.0068
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15894 | val 0.17463
  Epoch 020 - train 0.16079 | val 0.17289
  Epoch 021 - train 0.15495 | val 0.17302
  Regression -> MSE: 0.000094, MAE: 0.007468, R²: -0.0977
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16934 | val 0.21852
  Epoch 020 - train 0.16133 | val 0.22202
  Epoch 021 - train 0.16177 | val 0.22572
  Regression -> MSE: 0.000217, MAE: 0.011030, R²: -0.0224
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14779 | val 0.12814
  Epoch 020 - train 0.14669 | val 0.12891
  Epoch 021 - train 0.14861 | val 0.12836
  Regression -> MSE: 0.000100, MAE: 0.008210, R²: -0.0875
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16341 | val 0.11787
  Epoch 020 - train 0.14296 | val 0.11591
  Epoch 021 - train 0.15645 | val 0.11604
  Regression -> MSE: 0.000112, MAE: 0.009078, R²: -0.0834
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15971 | val 0.14741
  Epoch 020 - train 0.15841 | val 0.16588
  Epoch 021 - train 0.16066 | val 0.16441
  Regression -> MSE: 0.000232, MAE: 0.012530, R²: -0.0006
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14200 | val 0.17382
  Epoch 020 - train 0.14665 | val 0.17343
  Epoch 021 - train 0.14507 | val 0.17338
  Regression -> MSE: 0.000169, MAE: 0.007810, R²: -0.0183
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.15638 | val 0.12708
  Epoch 020 - train 0.15037 | val 0.17177
  Epoch 021 - train 0.15418 | val 0.17880
  Regression -> MSE: 0.000237, MAE: 0.011867, R²: -0.0011
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16651 | val 0.24163
  Epoch 020 - train 0.15314 | val 0.25415
  Epoch 021 - train 0.15995 | val 0.25497
  Regression -> MSE: 0.000236, MAE: 0.010177, R²: -0.0230
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15625 | val 0.17329
  Epoch 020 - train 0.17004 | val 0.18378
  Epoch 021 - train 0.16019 | val 0.18437
  Regression -> MSE: 0.000135, MAE: 0.008221, R²: -0.0001
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15746 | val 0.18252
  Epoch 020 - train 0.15490 | val 0.18196
  Epoch 021 - train 0.15752 | val 0.18226
  Regression -> MSE: 0.000192, MAE: 0.010392, R²: -0.0192
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13788 | val 0.16322
  Epoch 020 - train 0.13333 | val 0.16290
  Epoch 021 - train 0.14078 | val 0.16302
  Regression -> MSE: 0.000267, MAE: 0.010564, R²: -0.0209
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14849 | val 0.12106
  Epoch 020 - train 0.15345 | val 0.12238
  Epoch 021 - train 0.14762 | val 0.12260
  Regression -> MSE: 0.000168, MAE: 0.010357, R²: -0.0056
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14906 | val 0.14588
  Epoch 020 - train 0.14812 | val 0.15165
  Epoch 021 - train 0.14952 | val 0.15192
  Regression -> MSE: 0.000181, MAE: 0.010278, R²: -0.0034
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15962 | val 0.14021
  Epoch 020 - train 0.14409 | val 0.14167
  Epoch 021 - train 0.15420 | val 0.14117
  Regression -> MSE: 0.000342, MAE: 0.011836, R²: 0.0033
  Directional -> Accuracy: 0.4627, MCC: 0.0930, F1: 0.1429

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.17077 | val 0.09292
  Epoch 020 - train 0.15680 | val 0.09912
  Epoch 021 - train 0.17301 | val 0.09813
  Regression -> MSE: 0.000113, MAE: 0.008321, R²: -0.0734
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14967 | val 0.19526
  Epoch 020 - train 0.15797 | val 0.19740
  Epoch 021 - train 0.14609 | val 0.19725
  Regression -> MSE: 0.000219, MAE: 0.011290, R²: -0.0002
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15015 | val 0.25106
  Epoch 020 - train 0.15034 | val 0.26475
  Epoch 021 - train 0.15316 | val 0.26499
  Regression -> MSE: 0.000084, MAE: 0.007172, R²: -0.0870
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15576 | val 0.10792
  Epoch 020 - train 0.16141 | val 0.10927
  Epoch 021 - train 0.15840 | val 0.10939
  Regression -> MSE: 0.000310, MAE: 0.013892, R²: -0.0062
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17830 | val 0.09411
  Epoch 020 - train 0.17037 | val 0.09504
  Epoch 021 - train 0.16310 | val 0.09494
  Regression -> MSE: 0.000258, MAE: 0.011478, R²: -0.0585
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15748 | val 0.18516
  Epoch 020 - train 0.15945 | val 0.18287
  Epoch 021 - train 0.15598 | val 0.18225
  Regression -> MSE: 0.000081, MAE: 0.007097, R²: -0.0029
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16815 | val 0.20263
  Epoch 020 - train 0.18060 | val 0.23734
  Epoch 021 - train 0.16456 | val 0.23736
  Regression -> MSE: 0.000316, MAE: 0.014534, R²: -0.0294
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.15243 | val 0.15368
  Epoch 020 - train 0.14104 | val 0.15821
  Epoch 021 - train 0.14010 | val 0.15875
  Regression -> MSE: 0.000098, MAE: 0.007372, R²: -0.0006
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16620 | val 0.17491
  Epoch 020 - train 0.17287 | val 0.17945
  Epoch 021 - train 0.18852 | val 0.17912
  Regression -> MSE: 0.000173, MAE: 0.009493, R²: -0.0057
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.15166 | val 0.16453
  Epoch 020 - train 0.15553 | val 0.16603
  Epoch 021 - train 0.14446 | val 0.16451
  Regression -> MSE: 0.000223, MAE: 0.011730, R²: 0.0003
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14852 | val 0.16794
  Epoch 020 - train 0.16597 | val 0.16692
  Epoch 021 - train 0.16031 | val 0.16648

[I 2026-02-24 04:08:08,876] Trial 163 finished with value: -0.011449238592400388 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 6.983560441134962e-06, 'weight_decay': 1.948309337548985e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.22131253898343362, 'early_stopping_min_delta': 0.005138262243996607}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.15235 | val 0.20570
  Epoch 021 - train 0.15659 | val 0.20547
  Regression -> MSE: 0.000237, MAE: 0.012409, R²: 0.0015
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.33488 | val 0.56983
  Epoch 020 - train 0.32109 | val 0.55304
  Epoch 021 - train 0.35039 | val 0.55809
  Regression -> MSE: 0.000267, MAE: 0.013144, R²: -0.0766
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.32315 | val 0.30831
  Epoch 020 - train 0.30388 | val 0.30368
  Epoch 021 - train 0.28985 | val 0.30042
  Regression -> MSE: 0.000682, MAE: 0.019306, R²: 0.0040
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.34670 | val 0.53041
  Epoch 020 - train 0.33989 | val 0.53099
  Epoch 021 - train 0.31742 | val 0.53028
  Regression -> MSE: 0.000310, MAE: 0.014447, R²: -0.0007
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.30033 | val 0.32820
  Epoch 020 - train 0.27614 | val 0.33307
  Epoch 021 - train 0.27931 | val 0.33895
  Regression -> MSE: 0.000361, MAE: 0.014807, R²: -0.0335
  Directional -> Accuracy: 0.4800, MCC: 0.0544, F1: 0.2041

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.30481 | val 0.27878
  Epoch 020 - train 0.30623 | val 0.28164
  Epoch 025 - train 0.31142 | val 0.28120
  Regression -> MSE: 0.000209, MAE: 0.009760, R²: -0.0275
  Directional -> Accuracy: 0.5882, MCC: 0.2176, F1: 0.7123

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.32823 | val 0.61273
  Epoch 020 - train 0.31827 | val 0.61600
  Epoch 021 - train 0.32782 | val 0.61740
  Regression -> MSE: 0.000591, MAE: 0.018794, R²: -0.0642
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.33920 | val 0.37822
  Epoch 020 - train 0.31951 | val 0.37417
  Epoch 021 - train 0.34122 | val 0.37626
  Regression -> MSE: 0.000246, MAE: 0.012161, R²: -0.0036
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.29050 | val 0.39584
  Epoch 020 - train 0.30456 | val 0.40253
  Epoch 030 - train 0.30916 | val 0.40909
  Regression -> MSE: 0.000598, MAE: 0.019341, R²: -0.0008
  Directional -> Accuracy: 0.4773, MCC: -0.0721, F1: 0.3784

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.30962 | val 0.36900
  Epoch 020 - train 0.29861 | val 0.36471
  Epoch 021 - train 0.31292 | val 0.36514
  Regression -> MSE: 0.000393, MAE: 0.016000, R²: -0.0240
  Directional -> Accuracy: 0.3469, MCC: -0.2961, F1: 0.3600

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.33424 | val 0.43768
  Epoch 020 - train 0.32264 | val 0.43161
  Epoch 021 - train 0.33836 | val 0.43054
  Regression -> MSE: 0.000241, MAE: 0.011810, R²: 0.0031
  Directional -> Accuracy: 0.4714, MCC: 0.1833, F1: 0.6186

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.32604 | val 0.47228
  Epoch 020 - train 0.29373 | val 0.48512
  Epoch 021 - train 0.32076 | val 0.48514
  Regression -> MSE: 0.000313, MAE: 0.013649, R²: -0.0075
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.34704 | val 0.35537
  Epoch 020 - train 0.33887 | val 0.36089
  Epoch 021 - train 0.34151 | val 0.35816
  Regression -> MSE: 0.000681, MAE: 0.019611, R²: -0.0057
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.32022 | val 0.29045
  Epoch 020 - train 0.27725 | val 0.28983
  Epoch 030 - train 0.32115 | val 0.29111
  Regression -> MSE: 0.000145, MAE: 0.009376, R²: -0.0519
  Directional -> Accuracy: 0.4884, MCC: 0.0068, F1: 0.5217

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.28082 | val 0.40595
  Epoch 020 - train 0.28854 | val 0.40477
  Epoch 021 - train 0.28455 | val 0.40884
  Regression -> MSE: 0.000228, MAE: 0.010747, R²: -0.0114
  Directional -> Accuracy: 0.4918, MCC: -0.0123, F1: 0.4151

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.33446 | val 0.66648
  Epoch 020 - train 0.30222 | val 0.66219
  Epoch 021 - train 0.30348 | val 0.66143
  Regression -> MSE: 0.000368, MAE: 0.015898, R²: -0.0161
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.33283 | val 0.35345
  Epoch 020 - train 0.32699 | val 0.33957
  Epoch 021 - train 0.32680 | val 0.33200
  Regression -> MSE: 0.000109, MAE: 0.008145, R²: -0.0116
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.28901 | val 0.57852
  Epoch 020 - train 0.30287 | val 0.58642
  Epoch 021 - train 0.27500 | val 0.59012
  Regression -> MSE: 0.000158, MAE: 0.009990, R²: -0.0139
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.35900 | val 0.30788
  Epoch 020 - train 0.33714 | val 0.31314
  Epoch 021 - train 0.33858 | val 0.31178
  Regression -> MSE: 0.000285, MAE: 0.013637, R²: -0.0480
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.30152 | val 0.46353
  Epoch 020 - train 0.28925 | val 0.44155
  Epoch 021 - train 0.29618 | val 0.44485
  Regression -> MSE: 0.000161, MAE: 0.008932, R²: -0.0794
  Directional -> Accuracy: 0.4615, MCC: 0.0914, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.31360 | val 0.48132
  Epoch 020 - train 0.31613 | val 0.48233
  Epoch 021 - train 0.33235 | val 0.48198
  Regression -> MSE: 0.000231, MAE: 0.010963, R²: -0.0190
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.32444 | val 0.42083
  Epoch 020 - train 0.29520 | val 0.41740
  Epoch 021 - train 0.32331 | val 0.41763
  Regression -> MSE: 0.000162, MAE: 0.009178, R²: -0.1306
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.29799 | val 0.34721
  Epoch 020 - train 0.29948 | val 0.34859
  Epoch 021 - train 0.30456 | val 0.34971
  Regression -> MSE: 0.000177, MAE: 0.010281, R²: -0.0723
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.34792 | val 0.38856
  Epoch 020 - train 0.33120 | val 0.38663
  Epoch 021 - train 0.32995 | val 0.38365
  Regression -> MSE: 0.000085, MAE: 0.007020, R²: 0.0000
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.32354 | val 0.37414
  Epoch 020 - train 0.31451 | val 0.37228
  Epoch 023 - train 0.30599 | val 0.37382
  Regression -> MSE: 0.000204, MAE: 0.010802, R²: 0.0364
  Directional -> Accuracy: 0.6212, MCC: 0.2383, F1: 0.5902

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.31085 | val 0.27087
  Epoch 020 - train 0.29994 | val 0.26912
  Epoch 021 - train 0.29174 | val 0.27044
  Regression -> MSE: 0.000096, MAE: 0.008135, R²: -0.0392
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.32360 | val 0.39280
  Epoch 020 - train 0.31681 | val 0.41112
  Epoch 021 - train 0.32495 | val 0.40718
  Regression -> MSE: 0.000119, MAE: 0.009308, R²: -0.1516
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.33339 | val 0.29967
  Epoch 020 - train 0.33305 | val 0.30155
  Epoch 021 - train 0.31622 | val 0.30323
  Regression -> MSE: 0.000232, MAE: 0.012560, R²: -0.0023
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.29811 | val 0.35684
  Epoch 020 - train 0.32211 | val 0.35740
  Epoch 021 - train 0.30557 | val 0.35678
  Regression -> MSE: 0.000182, MAE: 0.008021, R²: -0.0960
  Directional -> Accuracy: 0.4211, MCC: -0.1512, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.35899 | val 0.40379
  Epoch 020 - train 0.37937 | val 0.53172
  Epoch 021 - train 0.35139 | val 0.53767
  Regression -> MSE: 0.000238, MAE: 0.011897, R²: -0.0062
  Directional -> Accuracy: 0.5610, MCC: 0.1701, F1: 0.7097

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.31732 | val 0.57127
  Epoch 020 - train 0.30144 | val 0.57561
  Epoch 021 - train 0.31955 | val 0.57940
  Regression -> MSE: 0.000231, MAE: 0.009888, R²: -0.0029
  Directional -> Accuracy: 0.4884, MCC: -0.0051, F1: 0.6452

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.35594 | val 0.38096
  Epoch 020 - train 0.33748 | val 0.38266
  Epoch 021 - train 0.34546 | val 0.38243
  Regression -> MSE: 0.000137, MAE: 0.008273, R²: -0.0167
  Directional -> Accuracy: 0.4419, MCC: -0.1150, F1: 0.4545

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.32842 | val 0.39871
  Epoch 020 - train 0.35543 | val 0.39649
  Epoch 021 - train 0.34510 | val 0.39563
  Regression -> MSE: 0.000191, MAE: 0.010349, R²: -0.0138
  Directional -> Accuracy: 0.6400, MCC: 0.3215, F1: 0.7429

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.29477 | val 0.36332
  Epoch 020 - train 0.26986 | val 0.36076
  Epoch 021 - train 0.28983 | val 0.35925
  Regression -> MSE: 0.000267, MAE: 0.010532, R²: -0.0180
  Directional -> Accuracy: 0.5753, MCC: 0.1334, F1: 0.7257

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.33581 | val 0.26968
  Epoch 020 - train 0.33117 | val 0.28822
  Epoch 021 - train 0.31483 | val 0.28609
  Regression -> MSE: 0.000167, MAE: 0.010362, R²: -0.0011
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.30232 | val 0.33345
  Epoch 020 - train 0.30263 | val 0.33204
  Epoch 021 - train 0.30979 | val 0.33150
  Regression -> MSE: 0.000180, MAE: 0.010277, R²: -0.0027
  Directional -> Accuracy: 0.4545, MCC: -0.1314, F1: 0.2500

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.33186 | val 0.31685
  Epoch 020 - train 0.32130 | val 0.31461
  Epoch 021 - train 0.33687 | val 0.31127
  Regression -> MSE: 0.000350, MAE: 0.012460, R²: -0.0215
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.35805 | val 0.18207
  Epoch 020 - train 0.32569 | val 0.17840
  Epoch 030 - train 0.32962 | val 0.17745
  Regression -> MSE: 0.000125, MAE: 0.008457, R²: -0.1865
  Directional -> Accuracy: 0.4651, MCC: -0.0670, F1: 0.3030

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.32620 | val 0.44571
  Epoch 020 - train 0.30867 | val 0.44259
  Epoch 021 - train 0.32087 | val 0.44238
  Regression -> MSE: 0.000219, MAE: 0.011267, R²: -0.0002
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.32620 | val 0.61871
  Epoch 020 - train 0.31296 | val 0.61825
  Epoch 021 - train 0.32639 | val 0.61994
  Regression -> MSE: 0.000082, MAE: 0.007071, R²: -0.0576
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.32684 | val 0.26010
  Epoch 020 - train 0.32471 | val 0.26017
  Epoch 021 - train 0.30592 | val 0.26001
  Regression -> MSE: 0.000329, MAE: 0.014946, R²: -0.0680
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.36782 | val 0.17629
  Epoch 020 - train 0.35292 | val 0.19082
  Epoch 021 - train 0.32891 | val 0.19200
  Regression -> MSE: 0.000259, MAE: 0.011502, R²: -0.0611
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.30634 | val 0.37166
  Epoch 020 - train 0.30026 | val 0.37308
  Epoch 021 - train 0.28563 | val 0.37353
  Regression -> MSE: 0.000084, MAE: 0.007062, R²: -0.0393
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.33480 | val 0.43221
  Epoch 020 - train 0.33467 | val 0.41484
  Epoch 021 - train 0.34670 | val 0.41748
  Regression -> MSE: 0.000307, MAE: 0.014495, R²: 0.0002
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.32601 | val 0.31808
  Epoch 020 - train 0.29836 | val 0.31515
  Epoch 030 - train 0.27449 | val 0.31553
  Regression -> MSE: 0.000099, MAE: 0.007100, R²: -0.0086
  Directional -> Accuracy: 0.5455, MCC: -0.0538, F1: 0.6970

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.35781 | val 0.40647
  Epoch 020 - train 0.36792 | val 0.40901
  Epoch 021 - train 0.38377 | val 0.40350
  Regression -> MSE: 0.000177, MAE: 0.010264, R²: -0.0271
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...


[I 2026-02-24 04:10:36,997] Trial 164 finished with value: -0.011462838564642273 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 16, 'learning_rate': 2.9331104535094872e-05, 'weight_decay': 8.377170147021158e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.5510313442912471, 'early_stopping_min_delta': 0.0037047631367151715}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.32278 | val 0.47009
  Epoch 021 - train 0.31022 | val 0.46821
  Regression -> MSE: 0.000240, MAE: 0.012322, R²: -0.0109
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09681 | val 0.11817
  Epoch 020 - train 0.08929 | val 0.11798
  Epoch 021 - train 0.09216 | val 0.11789
  Regression -> MSE: 0.000251, MAE: 0.012689, R²: -0.0141
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09260 | val 0.08258
  Epoch 020 - train 0.08712 | val 0.08274
  Epoch 021 - train 0.08911 | val 0.08280
  Regression -> MSE: 0.000716, MAE: 0.019877, R²: -0.0452
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10497 | val 0.14791
  Epoch 020 - train 0.09812 | val 0.14900
  Epoch 021 - train 0.10393 | val 0.14847
  Regression -> MSE: 0.000311, MAE: 0.014477, R²: -0.0034
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07797 | val 0.09912
  Epoch 020 - train 0.07782 | val 0.11552
  Epoch 021 - train 0.07867 | val 0.11667
  Regression -> MSE: 0.000350, MAE: 0.014569, R²: -0.0009
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09020 | val 0.08846
  Epoch 020 - train 0.08655 | val 0.08687
  Epoch 021 - train 0.09539 | val 0.08680
  Regression -> MSE: 0.000205, MAE: 0.010047, R²: -0.0043
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08956 | val 0.17029
  Epoch 020 - train 0.08885 | val 0.16791
  Epoch 021 - train 0.08735 | val 0.16814
  Regression -> MSE: 0.000601, MAE: 0.019000, R²: -0.0820
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09625 | val 0.11142
  Epoch 020 - train 0.08816 | val 0.11181
  Epoch 021 - train 0.09667 | val 0.11198
  Regression -> MSE: 0.000246, MAE: 0.011973, R²: -0.0001
  Directional -> Accuracy: 0.4203, MCC: 0.0315, F1: 0.5745

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09744 | val 0.11319
  Epoch 020 - train 0.09229 | val 0.11208
  Epoch 021 - train 0.09589 | val 0.11259
  Regression -> MSE: 0.000618, MAE: 0.019633, R²: -0.0337
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09412 | val 0.10813
  Epoch 020 - train 0.08740 | val 0.10270
  Epoch 021 - train 0.08959 | val 0.10260
  Regression -> MSE: 0.000392, MAE: 0.016015, R²: -0.0229
  Directional -> Accuracy: 0.3061, MCC: -0.3764, F1: 0.3462

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09194 | val 0.11647
  Epoch 020 - train 0.09348 | val 0.11825
  Epoch 021 - train 0.08823 | val 0.11843
  Regression -> MSE: 0.000241, MAE: 0.011843, R²: 0.0013
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09054 | val 0.13726
  Epoch 020 - train 0.08055 | val 0.15098
  Epoch 021 - train 0.08730 | val 0.15138
  Regression -> MSE: 0.000314, MAE: 0.013602, R²: -0.0115
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09682 | val 0.10875
  Epoch 020 - train 0.09860 | val 0.11267
  Epoch 021 - train 0.09476 | val 0.11330
  Regression -> MSE: 0.000678, MAE: 0.019469, R²: -0.0010
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09677 | val 0.08986
  Epoch 020 - train 0.09169 | val 0.09157
  Epoch 021 - train 0.09017 | val 0.09259
  Regression -> MSE: 0.000138, MAE: 0.009094, R²: -0.0008
  Directional -> Accuracy: 0.4651, MCC: -0.0675, F1: 0.4390

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08603 | val 0.11187
  Epoch 020 - train 0.08533 | val 0.11059
  Epoch 021 - train 0.08418 | val 0.11058
  Regression -> MSE: 0.000226, MAE: 0.010696, R²: -0.0039
  Directional -> Accuracy: 0.4754, MCC: -0.0647, F1: 0.1111

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09383 | val 0.17668
  Epoch 020 - train 0.08880 | val 0.18168
  Epoch 021 - train 0.09326 | val 0.18148
  Regression -> MSE: 0.000373, MAE: 0.015920, R²: -0.0294
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09359 | val 0.09634
  Epoch 020 - train 0.09032 | val 0.09685
  Epoch 021 - train 0.09332 | val 0.09767
  Regression -> MSE: 0.000108, MAE: 0.007966, R²: -0.0002
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09057 | val 0.15138
  Epoch 020 - train 0.08668 | val 0.15765
  Epoch 021 - train 0.08695 | val 0.15800
  Regression -> MSE: 0.000159, MAE: 0.009970, R²: -0.0173
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09489 | val 0.09626
  Epoch 020 - train 0.09348 | val 0.09777
  Epoch 021 - train 0.09338 | val 0.09818
  Regression -> MSE: 0.000273, MAE: 0.012923, R²: -0.0048
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08048 | val 0.12242
  Epoch 020 - train 0.08245 | val 0.12049
  Epoch 021 - train 0.08595 | val 0.12052
  Regression -> MSE: 0.000154, MAE: 0.008759, R²: -0.0314
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09610 | val 0.12203
  Epoch 020 - train 0.09723 | val 0.12791
  Epoch 021 - train 0.09557 | val 0.12875
  Regression -> MSE: 0.000227, MAE: 0.010880, R²: -0.0027
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09418 | val 0.11619
  Epoch 020 - train 0.09522 | val 0.12209
  Epoch 021 - train 0.09972 | val 0.12352
  Regression -> MSE: 0.000150, MAE: 0.008669, R²: -0.0430
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09202 | val 0.11479
  Epoch 020 - train 0.08627 | val 0.11569
  Epoch 021 - train 0.09292 | val 0.11634
  Regression -> MSE: 0.000173, MAE: 0.010250, R²: -0.0496
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10556 | val 0.10963
  Epoch 020 - train 0.09595 | val 0.10551
  Epoch 021 - train 0.09295 | val 0.10533
  Regression -> MSE: 0.000091, MAE: 0.007337, R²: -0.0635
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09616 | val 0.14248
  Epoch 020 - train 0.09147 | val 0.13800
  Epoch 021 - train 0.08908 | val 0.13644
  Regression -> MSE: 0.000212, MAE: 0.011112, R²: -0.0014
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08826 | val 0.08170
  Epoch 020 - train 0.08479 | val 0.08245
  Epoch 021 - train 0.08239 | val 0.08254
  Regression -> MSE: 0.000095, MAE: 0.008109, R²: -0.0296
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09388 | val 0.07276
  Epoch 020 - train 0.09498 | val 0.07659
  Epoch 021 - train 0.09056 | val 0.07682
  Regression -> MSE: 0.000106, MAE: 0.008899, R²: -0.0291
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09384 | val 0.08673
  Epoch 020 - train 0.09599 | val 0.09472
  Epoch 021 - train 0.09419 | val 0.09601
  Regression -> MSE: 0.000231, MAE: 0.012532, R²: 0.0000
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09592 | val 0.10774
  Epoch 020 - train 0.09164 | val 0.10678
  Epoch 021 - train 0.09007 | val 0.10714
  Regression -> MSE: 0.000174, MAE: 0.007871, R²: -0.0468
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09786 | val 0.07859
  Epoch 020 - train 0.09230 | val 0.08024
  Epoch 021 - train 0.09714 | val 0.08011
  Regression -> MSE: 0.000236, MAE: 0.011856, R²: 0.0006
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09322 | val 0.14180
  Epoch 020 - train 0.09725 | val 0.14456
  Epoch 021 - train 0.09201 | val 0.14501
  Regression -> MSE: 0.000231, MAE: 0.009918, R²: -0.0018
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09669 | val 0.11074
  Epoch 020 - train 0.09223 | val 0.11178
  Epoch 021 - train 0.09807 | val 0.11181
  Regression -> MSE: 0.000136, MAE: 0.008270, R²: -0.0084
  Directional -> Accuracy: 0.5814, MCC: 0.1533, F1: 0.6897

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09595 | val 0.11491
  Epoch 020 - train 0.09480 | val 0.12092
  Epoch 021 - train 0.09333 | val 0.12120
  Regression -> MSE: 0.000204, MAE: 0.010886, R²: -0.0815
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07868 | val 0.09808
  Epoch 020 - train 0.08017 | val 0.09815
  Epoch 021 - train 0.08359 | val 0.09841
  Regression -> MSE: 0.000266, MAE: 0.010526, R²: -0.0173
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09513 | val 0.07729
  Epoch 020 - train 0.09234 | val 0.08104
  Epoch 021 - train 0.08847 | val 0.08189
  Regression -> MSE: 0.000171, MAE: 0.010384, R²: -0.0268
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08676 | val 0.09572
  Epoch 020 - train 0.08948 | val 0.10293
  Epoch 021 - train 0.08167 | val 0.10224
  Regression -> MSE: 0.000181, MAE: 0.010346, R²: -0.0033
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09134 | val 0.09768
  Epoch 020 - train 0.08746 | val 0.09858
  Epoch 021 - train 0.09153 | val 0.09864
  Regression -> MSE: 0.000346, MAE: 0.012207, R²: -0.0102
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10533 | val 0.06101
  Epoch 020 - train 0.09507 | val 0.06033
  Epoch 021 - train 0.08867 | val 0.06052
  Regression -> MSE: 0.000111, MAE: 0.008331, R²: -0.0572
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09997 | val 0.13684
  Epoch 020 - train 0.09355 | val 0.13643
  Epoch 021 - train 0.09438 | val 0.13553
  Regression -> MSE: 0.000226, MAE: 0.011493, R²: -0.0335
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.08947 | val 0.15622
  Epoch 020 - train 0.09130 | val 0.16602
  Epoch 021 - train 0.09198 | val 0.16620
  Regression -> MSE: 0.000089, MAE: 0.007388, R²: -0.1472
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08691 | val 0.07225
  Epoch 020 - train 0.08690 | val 0.07053
  Epoch 021 - train 0.08454 | val 0.07071
  Regression -> MSE: 0.000319, MAE: 0.014486, R²: -0.0386
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09942 | val 0.06027
  Epoch 020 - train 0.09954 | val 0.06058
  Epoch 021 - train 0.09274 | val 0.06127
  Regression -> MSE: 0.000260, MAE: 0.011496, R²: -0.0666
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09156 | val 0.10495
  Epoch 020 - train 0.08719 | val 0.10537
  Epoch 021 - train 0.08636 | val 0.10584
  Regression -> MSE: 0.000081, MAE: 0.007124, R²: -0.0067
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.09276 | val 0.11081
  Epoch 020 - train 0.09186 | val 0.11099
  Epoch 021 - train 0.09111 | val 0.11118
  Regression -> MSE: 0.000307, MAE: 0.014501, R²: -0.0007
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08799 | val 0.10604
  Epoch 020 - train 0.08478 | val 0.10453
  Epoch 021 - train 0.08516 | val 0.10452
  Regression -> MSE: 0.000101, MAE: 0.007109, R²: -0.0305
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.09874 | val 0.10634
  Epoch 020 - train 0.09788 | val 0.10765
  Epoch 021 - train 0.09690 | val 0.10806
  Regression -> MSE: 0.000173, MAE: 0.009972, R²: -0.0095
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09177 | val 0.10618
  Epoch 020 - train 0.08872 | val 0.11190
  Epoch 021 - train 0.08767 | val 0.11387
  Regression -> MSE: 0.000223, MAE: 0.011759, R²: -0.0014
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09204 | val 0.11206
  Epoch 020 - train 0.09055 | val 0.11777
  Epoch 021 - train 0.08844 | val 0.11825

[I 2026-02-24 04:12:45,296] Trial 165 finished with value: -0.011433410448836723 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 4.174851495837065e-05, 'weight_decay': 4.070978487336037e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.13118108798236075, 'early_stopping_min_delta': 0.008562700741212244}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.09511 | val 0.15121
  Epoch 021 - train 0.09117 | val 0.15111
  Regression -> MSE: 0.000238, MAE: 0.012308, R²: -0.0022
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07247 | val 0.09239
  Epoch 011 - train 0.07222 | val 0.09264
  Regression -> MSE: 0.000254, MAE: 0.012808, R²: -0.0248
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07086 | val 0.06671
  Epoch 011 - train 0.06914 | val 0.06694
  Regression -> MSE: 0.000711, MAE: 0.019796, R²: -0.0388
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07380 | val 0.10997
  Epoch 011 - train 0.07246 | val 0.10948
  Regression -> MSE: 0.000313, MAE: 0.014411, R²: -0.0083
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06376 | val 0.06519
  Epoch 011 - train 0.06208 | val 0.06498
  Regression -> MSE: 0.000356, MAE: 0.014697, R²: -0.0183
  Directional -> Accuracy: 0.5333, MCC: -0.0286, F1: 0.6847

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07522 | val 0.06812
  Epoch 011 - train 0.07138 | val 0.06868
  Regression -> MSE: 0.000204, MAE: 0.010069, R²: 0.0005
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07207 | val 0.12758
  Epoch 011 - train 0.06685 | val 0.12763
  Regression -> MSE: 0.000556, MAE: 0.018213, R²: -0.0018
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07192 | val 0.08527
  Epoch 011 - train 0.07200 | val 0.08534
  Regression -> MSE: 0.000246, MAE: 0.012036, R²: -0.0005
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07468 | val 0.09894
  Epoch 011 - train 0.06620 | val 0.10013
  Regression -> MSE: 0.000635, MAE: 0.019992, R²: -0.0624
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.06820 | val 0.08301
  Epoch 011 - train 0.06621 | val 0.08273
  Regression -> MSE: 0.000398, MAE: 0.016018, R²: -0.0376
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.06780 | val 0.09366
  Epoch 011 - train 0.07040 | val 0.09476
  Regression -> MSE: 0.000241, MAE: 0.011885, R²: 0.0020
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06384 | val 0.10364
  Epoch 011 - train 0.06464 | val 0.10724
  Regression -> MSE: 0.000321, MAE: 0.013574, R²: -0.0314
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07489 | val 0.08882
  Epoch 011 - train 0.07334 | val 0.09080
  Regression -> MSE: 0.000676, MAE: 0.019446, R²: 0.0019
  Directional -> Accuracy: 0.6379, MCC: 0.2843, F1: 0.5882

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.06818 | val 0.07805
  Epoch 011 - train 0.06932 | val 0.08333
  Regression -> MSE: 0.000140, MAE: 0.009285, R²: -0.0137
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06714 | val 0.09020
  Epoch 011 - train 0.06817 | val 0.08996
  Regression -> MSE: 0.000226, MAE: 0.010845, R²: -0.0052
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.06760 | val 0.13922
  Epoch 011 - train 0.07020 | val 0.13962
  Regression -> MSE: 0.000363, MAE: 0.016084, R²: -0.0012
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07636 | val 0.08477
  Epoch 011 - train 0.07320 | val 0.08546
  Regression -> MSE: 0.000108, MAE: 0.008100, R²: -0.0044
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.06792 | val 0.11505
  Epoch 011 - train 0.06998 | val 0.11716
  Regression -> MSE: 0.000160, MAE: 0.010070, R²: -0.0262
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.06960 | val 0.08405
  Epoch 011 - train 0.07189 | val 0.08471
  Regression -> MSE: 0.000295, MAE: 0.013984, R²: -0.0838
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06755 | val 0.09420
  Epoch 011 - train 0.06634 | val 0.09416
  Regression -> MSE: 0.000166, MAE: 0.009110, R²: -0.1116
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07187 | val 0.10087
  Epoch 011 - train 0.07228 | val 0.10335
  Regression -> MSE: 0.000229, MAE: 0.010877, R²: -0.0103
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07379 | val 0.09008
  Epoch 011 - train 0.07093 | val 0.09109
  Regression -> MSE: 0.000144, MAE: 0.008331, R²: -0.0019
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.06808 | val 0.08992
  Epoch 011 - train 0.06866 | val 0.09063
  Regression -> MSE: 0.000167, MAE: 0.010276, R²: -0.0085
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07588 | val 0.08347
  Epoch 011 - train 0.07429 | val 0.08425
  Regression -> MSE: 0.000088, MAE: 0.007204, R²: -0.0352
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07301 | val 0.09201
  Epoch 011 - train 0.07008 | val 0.09456
  Regression -> MSE: 0.000218, MAE: 0.011055, R²: -0.0276
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06892 | val 0.06298
  Epoch 011 - train 0.06582 | val 0.06279
  Regression -> MSE: 0.000099, MAE: 0.008201, R²: -0.0775
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07785 | val 0.05615
  Epoch 011 - train 0.07373 | val 0.05609
  Regression -> MSE: 0.000105, MAE: 0.008855, R²: -0.0203
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07447 | val 0.06765
  Epoch 011 - train 0.07449 | val 0.06802
  Regression -> MSE: 0.000232, MAE: 0.012552, R²: -0.0010
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07306 | val 0.07783
  Epoch 020 - train 0.06758 | val 0.07911
  Regression -> MSE: 0.000341, MAE: 0.014035, R²: -1.0467
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07796 | val 0.06170
  Epoch 011 - train 0.07703 | val 0.06167
  Regression -> MSE: 0.000237, MAE: 0.011906, R²: -0.0036
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07288 | val 0.11273
  Epoch 011 - train 0.07012 | val 0.11326
  Regression -> MSE: 0.000233, MAE: 0.010039, R²: -0.0106
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07150 | val 0.08780
  Epoch 011 - train 0.08048 | val 0.08817
  Regression -> MSE: 0.000136, MAE: 0.008282, R²: -0.0104
  Directional -> Accuracy: 0.5116, MCC: 0.0426, F1: 0.4615

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07387 | val 0.09105
  Epoch 011 - train 0.07237 | val 0.09194
  Regression -> MSE: 0.000191, MAE: 0.010383, R²: -0.0148
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06680 | val 0.07809
  Epoch 011 - train 0.06456 | val 0.07720
  Regression -> MSE: 0.000268, MAE: 0.010602, R²: -0.0251
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.06311 | val 0.05999
  Epoch 011 - train 0.06672 | val 0.05999
  Regression -> MSE: 0.000169, MAE: 0.010364, R²: -0.0117
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06486 | val 0.07091
  Epoch 011 - train 0.06364 | val 0.07166
  Regression -> MSE: 0.000180, MAE: 0.010303, R²: 0.0008
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.06808 | val 0.07056
  Epoch 011 - train 0.06633 | val 0.07129
  Regression -> MSE: 0.000346, MAE: 0.012115, R²: -0.0087
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08023 | val 0.04737
  Epoch 011 - train 0.07176 | val 0.04728
  Regression -> MSE: 0.000116, MAE: 0.008339, R²: -0.0993
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07457 | val 0.09635
  Epoch 011 - train 0.07511 | val 0.09599
  Regression -> MSE: 0.000224, MAE: 0.011436, R²: -0.0259
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07546 | val 0.12652
  Epoch 011 - train 0.07297 | val 0.12862
  Regression -> MSE: 0.000083, MAE: 0.007099, R²: -0.0670
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.06856 | val 0.05647
  Epoch 011 - train 0.08031 | val 0.05665
  Regression -> MSE: 0.000317, MAE: 0.014356, R²: -0.0305
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07477 | val 0.04625
  Epoch 011 - train 0.07693 | val 0.04655
  Regression -> MSE: 0.000245, MAE: 0.011550, R²: -0.0039
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.06483 | val 0.08581
  Epoch 011 - train 0.06864 | val 0.08597
  Regression -> MSE: 0.000081, MAE: 0.007075, R²: 0.0012
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07496 | val 0.08589
  Epoch 011 - train 0.07044 | val 0.08659
  Regression -> MSE: 0.000311, MAE: 0.014529, R²: -0.0129
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.06687 | val 0.07542
  Epoch 011 - train 0.06990 | val 0.07538
  Regression -> MSE: 0.000098, MAE: 0.007272, R²: -0.0002
  Directional -> Accuracy: 0.5455, MCC: 0.0737, F1: 0.6000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.07791 | val 0.08263
  Epoch 011 - train 0.07541 | val 0.08287
  Regression -> MSE: 0.000173, MAE: 0.009918, R²: -0.0051
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.06848 | val 0.08210
  Epoch 011 - train 0.06792 | val 0.08218
  Regression -> MSE: 0.000224, MAE: 0.011767, R²: -0.0030
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07000 | val 0.08186
  Epoch 011 - train 0.06909 | val 0.08275
  Regression -> MSE: 0.000093, MAE: 0.007674, R²: -0.0030
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.07403 | val 0.10867
  Epoch 011 - train 0.07454 | val 0.11023
  Regression -> MSE: 0.000165, MAE: 0.010257, R²: -0.0057
  Directional -> Accuracy: 0.5556, MCC: 0.1201, F1: 0.5200

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.06835 | val 0.09313
  Epoch 011 - train 0.07094 | val 0.09696
  Regression -> MSE: 0.000125, MAE: 0.009024, R²: -0.0742
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 04:13:53,106] Trial 166 finished with value: -0.011568613242585133 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 4.5181941426434096e-05, 'weight_decay': 3.69840771183274e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.10023694234397174, 'early_stopping_min_delta': 0.006536379872897702}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 010 - train 0.07421 | val 0.09585
  Epoch 011 - train 0.07041 | val 0.09599
  Regression -> MSE: 0.000239, MAE: 0.012337, R²: -0.0089
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10409 | val 0.12769
  Epoch 020 - train 0.10180 | val 0.12542
  Epoch 021 - train 0.10201 | val 0.12555
  Regression -> MSE: 0.000254, MAE: 0.012841, R²: -0.0276
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09791 | val 0.09059
  Epoch 020 - train 0.09643 | val 0.09243
  Epoch 021 - train 0.10232 | val 0.09264
  Regression -> MSE: 0.000705, MAE: 0.019690, R²: -0.0305
  Directional -> Accuracy: 0.4783, MCC: -0.0040, F1: 0.4286

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11085 | val 0.16897
  Epoch 020 - train 0.11095 | val 0.17375
  Epoch 021 - train 0.10573 | val 0.17425
  Regression -> MSE: 0.000334, MAE: 0.014732, R²: -0.0779
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09013 | val 0.11693
  Epoch 020 - train 0.08722 | val 0.12699
  Epoch 021 - train 0.09227 | val 0.12586
  Regression -> MSE: 0.000379, MAE: 0.015084, R²: -0.0864
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10298 | val 0.10486
  Epoch 020 - train 0.10239 | val 0.10510
  Epoch 021 - train 0.10960 | val 0.10526
  Regression -> MSE: 0.000204, MAE: 0.010297, R²: -0.0030
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09764 | val 0.19752
  Epoch 020 - train 0.09935 | val 0.19925
  Epoch 021 - train 0.09934 | val 0.19933
  Regression -> MSE: 0.000619, MAE: 0.019349, R²: -0.1157
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10760 | val 0.12458
  Epoch 020 - train 0.10558 | val 0.12568
  Epoch 021 - train 0.10230 | val 0.12575
  Regression -> MSE: 0.000245, MAE: 0.011924, R²: 0.0018
  Directional -> Accuracy: 0.5362, MCC: 0.0274, F1: 0.4074

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10815 | val 0.13045
  Epoch 020 - train 0.10296 | val 0.13173
  Epoch 021 - train 0.10726 | val 0.13161
  Regression -> MSE: 0.000621, MAE: 0.019702, R²: -0.0394
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10032 | val 0.11930
  Epoch 020 - train 0.09694 | val 0.12142
  Epoch 021 - train 0.09092 | val 0.12152
  Regression -> MSE: 0.000406, MAE: 0.016158, R²: -0.0571
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10462 | val 0.12515
  Epoch 020 - train 0.10238 | val 0.12673
  Epoch 021 - train 0.10291 | val 0.12660
  Regression -> MSE: 0.000240, MAE: 0.011949, R²: 0.0058
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09374 | val 0.14450
  Epoch 020 - train 0.09390 | val 0.14883
  Epoch 021 - train 0.09502 | val 0.14913
  Regression -> MSE: 0.000315, MAE: 0.013735, R²: -0.0136
  Directional -> Accuracy: 0.4200, MCC: -0.1445, F1: 0.5538

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11535 | val 0.11625
  Epoch 020 - train 0.10314 | val 0.11881
  Epoch 021 - train 0.10685 | val 0.11889
  Regression -> MSE: 0.000688, MAE: 0.019910, R²: -0.0162
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11274 | val 0.10726
  Epoch 020 - train 0.10328 | val 0.12190
  Epoch 021 - train 0.10565 | val 0.12267
  Regression -> MSE: 0.000139, MAE: 0.009092, R²: -0.0036
  Directional -> Accuracy: 0.5581, MCC: 0.0993, F1: 0.4865

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09206 | val 0.13028
  Epoch 020 - train 0.10036 | val 0.12899
  Epoch 021 - train 0.09721 | val 0.12909
  Regression -> MSE: 0.000224, MAE: 0.010692, R²: 0.0026
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10686 | val 0.20292
  Epoch 020 - train 0.10623 | val 0.20520
  Epoch 021 - train 0.10728 | val 0.20564
  Regression -> MSE: 0.000371, MAE: 0.016021, R²: -0.0258
  Directional -> Accuracy: 0.5192, MCC: -0.1296, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11062 | val 0.10502
  Epoch 020 - train 0.11223 | val 0.10435
  Epoch 021 - train 0.10824 | val 0.10428
  Regression -> MSE: 0.000114, MAE: 0.008020, R²: -0.0589
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10864 | val 0.17028
  Epoch 020 - train 0.10624 | val 0.17088
  Epoch 021 - train 0.10518 | val 0.17092
  Regression -> MSE: 0.000159, MAE: 0.009573, R²: -0.0197
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10928 | val 0.10920
  Epoch 020 - train 0.10868 | val 0.11270
  Epoch 021 - train 0.10600 | val 0.11258
  Regression -> MSE: 0.000289, MAE: 0.013790, R²: -0.0614
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10044 | val 0.13559
  Epoch 020 - train 0.09408 | val 0.13639
  Epoch 021 - train 0.09562 | val 0.13591
  Regression -> MSE: 0.000160, MAE: 0.008904, R²: -0.0702
  Directional -> Accuracy: 0.4923, MCC: -0.1193, F1: 0.6207

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10185 | val 0.14114
  Epoch 020 - train 0.10426 | val 0.14230
  Epoch 021 - train 0.10024 | val 0.14229
  Regression -> MSE: 0.000231, MAE: 0.010927, R²: -0.0216
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10607 | val 0.12313
  Epoch 020 - train 0.10466 | val 0.12162
  Epoch 021 - train 0.10664 | val 0.12169
  Regression -> MSE: 0.000145, MAE: 0.008444, R²: -0.0094
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10222 | val 0.11899
  Epoch 020 - train 0.09643 | val 0.11805
  Epoch 021 - train 0.09735 | val 0.11816
  Regression -> MSE: 0.000165, MAE: 0.010492, R²: 0.0010
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10476 | val 0.11657
  Epoch 020 - train 0.10828 | val 0.11674
  Epoch 021 - train 0.10091 | val 0.11659
  Regression -> MSE: 0.000088, MAE: 0.007182, R²: -0.0312
  Directional -> Accuracy: 0.5690, MCC: 0.2469, F1: 0.4681

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10536 | val 0.11926
  Epoch 020 - train 0.09922 | val 0.11953
  Epoch 021 - train 0.10112 | val 0.11965
  Regression -> MSE: 0.000214, MAE: 0.011414, R²: -0.0121
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09753 | val 0.08625
  Epoch 020 - train 0.09517 | val 0.08696
  Epoch 021 - train 0.09401 | val 0.08693
  Regression -> MSE: 0.000096, MAE: 0.008133, R²: -0.0395
  Directional -> Accuracy: 0.5000, MCC: -0.0684, F1: 0.6216

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11196 | val 0.08459
  Epoch 020 - train 0.10914 | val 0.08180
  Epoch 021 - train 0.10522 | val 0.08166
  Regression -> MSE: 0.000117, MAE: 0.009248, R²: -0.1366
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11061 | val 0.09711
  Epoch 020 - train 0.10673 | val 0.09879
  Epoch 021 - train 0.10599 | val 0.09887
  Regression -> MSE: 0.000234, MAE: 0.012646, R²: -0.0131
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10386 | val 0.11938
  Epoch 020 - train 0.09693 | val 0.11665
  Epoch 021 - train 0.09620 | val 0.11655
  Regression -> MSE: 0.000172, MAE: 0.007862, R²: -0.0339
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10727 | val 0.08955
  Epoch 020 - train 0.09951 | val 0.09296
  Epoch 021 - train 0.10352 | val 0.09328
  Regression -> MSE: 0.000237, MAE: 0.011888, R²: -0.0022
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10417 | val 0.15568
  Epoch 020 - train 0.09915 | val 0.15542
  Epoch 021 - train 0.10396 | val 0.15556
  Regression -> MSE: 0.000230, MAE: 0.009926, R²: 0.0003
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11174 | val 0.12021
  Epoch 020 - train 0.09750 | val 0.12274
  Epoch 021 - train 0.10659 | val 0.12314
  Regression -> MSE: 0.000139, MAE: 0.008286, R²: -0.0275
  Directional -> Accuracy: 0.5581, MCC: 0.0981, F1: 0.6885

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10289 | val 0.12538
  Epoch 020 - train 0.09919 | val 0.12814
  Epoch 021 - train 0.10827 | val 0.12832
  Regression -> MSE: 0.000204, MAE: 0.010866, R²: -0.0842
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08908 | val 0.11805
  Epoch 020 - train 0.09377 | val 0.11562
  Epoch 021 - train 0.09256 | val 0.11591
  Regression -> MSE: 0.000264, MAE: 0.010551, R²: -0.0101
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10629 | val 0.08577
  Epoch 020 - train 0.10565 | val 0.08705
  Epoch 021 - train 0.11144 | val 0.08718
  Regression -> MSE: 0.000171, MAE: 0.010365, R²: -0.0231
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10001 | val 0.09987
  Epoch 020 - train 0.09422 | val 0.10071
  Epoch 021 - train 0.09309 | val 0.10080
  Regression -> MSE: 0.000182, MAE: 0.010337, R²: -0.0092
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09505 | val 0.09342
  Epoch 020 - train 0.09662 | val 0.09533
  Epoch 021 - train 0.09292 | val 0.09535
  Regression -> MSE: 0.000346, MAE: 0.012038, R²: -0.0087
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11646 | val 0.06956
  Epoch 020 - train 0.11663 | val 0.07364
  Epoch 021 - train 0.11286 | val 0.07385
  Regression -> MSE: 0.000112, MAE: 0.008333, R²: -0.0634
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10978 | val 0.13740
  Epoch 020 - train 0.09837 | val 0.13928
  Epoch 021 - train 0.10449 | val 0.13930
  Regression -> MSE: 0.000223, MAE: 0.011357, R²: -0.0185
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09863 | val 0.16918
  Epoch 020 - train 0.10420 | val 0.17210
  Epoch 021 - train 0.10102 | val 0.17234
  Regression -> MSE: 0.000091, MAE: 0.007457, R²: -0.1702
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09833 | val 0.07789
  Epoch 020 - train 0.09673 | val 0.07881
  Epoch 021 - train 0.09883 | val 0.07890
  Regression -> MSE: 0.000310, MAE: 0.013903, R²: -0.0063
  Directional -> Accuracy: 0.6531, MCC: 0.1852, F1: 0.3704

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11078 | val 0.06519
  Epoch 020 - train 0.10640 | val 0.06982
  Epoch 021 - train 0.10428 | val 0.07054
  Regression -> MSE: 0.000255, MAE: 0.011520, R²: -0.0446
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10788 | val 0.11893
  Epoch 020 - train 0.10079 | val 0.11774
  Epoch 021 - train 0.10241 | val 0.11765
  Regression -> MSE: 0.000083, MAE: 0.007051, R²: -0.0232
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.09611 | val 0.12415
  Epoch 020 - train 0.09645 | val 0.12050
  Epoch 021 - train 0.10250 | val 0.12027
  Regression -> MSE: 0.000307, MAE: 0.014456, R²: 0.0001
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10221 | val 0.10553
  Epoch 020 - train 0.09602 | val 0.10567
  Epoch 021 - train 0.10313 | val 0.10581
  Regression -> MSE: 0.000098, MAE: 0.007252, R²: -0.0017
  Directional -> Accuracy: 0.5909, MCC: 0.1394, F1: 0.6786

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11305 | val 0.11711
  Epoch 020 - train 0.10961 | val 0.11782
  Epoch 021 - train 0.11267 | val 0.11788
  Regression -> MSE: 0.000180, MAE: 0.010440, R²: -0.0502
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 04:15:05,979] Trial 167 finished with value: -0.011496868559011839 and parameters: {'feature_set': 'all_nlp', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 4.348539458044023e-05, 'weight_decay': 5.843447202516792e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.14633500436811323, 'early_stopping_min_delta': 0.007018970664502109}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.10744 | val 0.14552
  Epoch 021 - train 0.10352 | val 0.14583
  Regression -> MSE: 0.000238, MAE: 0.012404, R²: -0.0041
  Directional -> Accuracy: 0.4098, MCC: -0.2783, F1: 0.5814

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12807 | val 0.16801
  Epoch 020 - train 0.11600 | val 0.16185
  Epoch 021 - train 0.12094 | val 0.16177
  Regression -> MSE: 0.000257, MAE: 0.012929, R²: -0.0394
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12040 | val 0.11277
  Epoch 020 - train 0.12072 | val 0.11450
  Epoch 021 - train 0.10341 | val 0.11377
  Regression -> MSE: 0.000683, MAE: 0.019352, R²: 0.0017
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12731 | val 0.19146
  Epoch 020 - train 0.11964 | val 0.19139
  Epoch 021 - train 0.12934 | val 0.19119
  Regression -> MSE: 0.000310, MAE: 0.014408, R²: -0.0002
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10450 | val 0.24677
  Epoch 020 - train 0.10578 | val 0.23849
  Epoch 021 - train 0.10131 | val 0.23330
  Regression -> MSE: 0.000356, MAE: 0.014685, R²: -0.0180
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11695 | val 0.11628
  Epoch 020 - train 0.11163 | val 0.11411
  Epoch 021 - train 0.12205 | val 0.11456
  Regression -> MSE: 0.000204, MAE: 0.010036, R²: -0.0003
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11659 | val 0.22001
  Epoch 020 - train 0.11192 | val 0.22073
  Epoch 030 - train 0.11435 | val 0.22380
  Regression -> MSE: 0.000549, MAE: 0.017994, R²: 0.0111
  Directional -> Accuracy: 0.5106, MCC: 0.0258, F1: 0.5490

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12238 | val 0.15219
  Epoch 020 - train 0.12270 | val 0.15325
  Epoch 021 - train 0.12210 | val 0.15344
  Regression -> MSE: 0.000249, MAE: 0.011936, R²: -0.0131
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12940 | val 0.14837
  Epoch 020 - train 0.12041 | val 0.16483
  Epoch 021 - train 0.11307 | val 0.16729
  Regression -> MSE: 0.000611, MAE: 0.019486, R²: -0.0219
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12385 | val 0.14409
  Epoch 020 - train 0.11080 | val 0.14482
  Epoch 021 - train 0.12204 | val 0.14522
  Regression -> MSE: 0.000392, MAE: 0.015979, R²: -0.0206
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12622 | val 0.15369
  Epoch 020 - train 0.11777 | val 0.16097
  Epoch 021 - train 0.12068 | val 0.16223
  Regression -> MSE: 0.000242, MAE: 0.012029, R²: -0.0036
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12516 | val 0.17088
  Epoch 020 - train 0.11448 | val 0.17258
  Epoch 021 - train 0.10919 | val 0.17289
  Regression -> MSE: 0.000318, MAE: 0.013595, R²: -0.0217
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12404 | val 0.15155
  Epoch 020 - train 0.12408 | val 0.16235
  Epoch 021 - train 0.12675 | val 0.16294
  Regression -> MSE: 0.000678, MAE: 0.019482, R²: -0.0011
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12249 | val 0.11590
  Epoch 020 - train 0.11767 | val 0.15732
  Epoch 021 - train 0.11405 | val 0.15756
  Regression -> MSE: 0.000145, MAE: 0.009525, R²: -0.0514
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10616 | val 0.15015
  Epoch 020 - train 0.10872 | val 0.15227
  Epoch 029 - train 0.10635 | val 0.15484
  Regression -> MSE: 0.000217, MAE: 0.010584, R²: 0.0334
  Directional -> Accuracy: 0.5246, MCC: 0.0468, F1: 0.6133

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11581 | val 0.23993
  Epoch 020 - train 0.11700 | val 0.23891
  Epoch 021 - train 0.11325 | val 0.23974
  Regression -> MSE: 0.000364, MAE: 0.015989, R²: -0.0052
  Directional -> Accuracy: 0.5769, MCC: 0.1350, F1: 0.4500

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12322 | val 0.14295
  Epoch 020 - train 0.13127 | val 0.14473
  Epoch 021 - train 0.12025 | val 0.14480
  Regression -> MSE: 0.000109, MAE: 0.008146, R²: -0.0118
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11718 | val 0.22174
  Epoch 020 - train 0.12095 | val 0.23982
  Epoch 021 - train 0.11474 | val 0.24217
  Regression -> MSE: 0.000156, MAE: 0.009662, R²: 0.0006
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12248 | val 0.12233
  Epoch 020 - train 0.12127 | val 0.12307
  Epoch 021 - train 0.12231 | val 0.12358
  Regression -> MSE: 0.000273, MAE: 0.013091, R²: -0.0038
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12177 | val 0.15716
  Epoch 020 - train 0.11131 | val 0.15622
  Epoch 021 - train 0.10417 | val 0.15577
  Regression -> MSE: 0.000171, MAE: 0.009223, R²: -0.1416
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12116 | val 0.16212
  Epoch 020 - train 0.11925 | val 0.16126
  Epoch 021 - train 0.11278 | val 0.16150
  Regression -> MSE: 0.000235, MAE: 0.010946, R²: -0.0388
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11661 | val 0.15094
  Epoch 020 - train 0.11681 | val 0.15693
  Epoch 021 - train 0.12311 | val 0.15772
  Regression -> MSE: 0.000144, MAE: 0.008391, R²: -0.0044
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11150 | val 0.14357
  Epoch 020 - train 0.11283 | val 0.14616
  Epoch 021 - train 0.10750 | val 0.14633
  Regression -> MSE: 0.000167, MAE: 0.010313, R²: -0.0114
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12577 | val 0.14209
  Epoch 020 - train 0.12500 | val 0.14795
  Epoch 021 - train 0.12141 | val 0.14761
  Regression -> MSE: 0.000092, MAE: 0.007415, R²: -0.0817
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11692 | val 0.14540
  Epoch 020 - train 0.12003 | val 0.14651
  Epoch 021 - train 0.11800 | val 0.14626
  Regression -> MSE: 0.000216, MAE: 0.011052, R²: -0.0197
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10791 | val 0.10728
  Epoch 020 - train 0.10069 | val 0.10577
  Epoch 021 - train 0.10811 | val 0.10564
  Regression -> MSE: 0.000092, MAE: 0.008060, R²: -0.0020
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12971 | val 0.09489
  Epoch 020 - train 0.12755 | val 0.10376
  Epoch 021 - train 0.12696 | val 0.10498
  Regression -> MSE: 0.000108, MAE: 0.008970, R²: -0.0519
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12454 | val 0.11435
  Epoch 020 - train 0.12244 | val 0.12949
  Epoch 021 - train 0.12300 | val 0.13235
  Regression -> MSE: 0.000232, MAE: 0.012553, R²: -0.0012
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11552 | val 0.13906
  Epoch 020 - train 0.11947 | val 0.13868
  Epoch 021 - train 0.12128 | val 0.13870
  Regression -> MSE: 0.000191, MAE: 0.008204, R²: -0.1486
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13356 | val 0.10141
  Epoch 020 - train 0.11549 | val 0.10320
  Epoch 021 - train 0.11657 | val 0.10351
  Regression -> MSE: 0.000237, MAE: 0.011872, R²: -0.0003
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13307 | val 0.18613
  Epoch 020 - train 0.12409 | val 0.19084
  Epoch 021 - train 0.12364 | val 0.19144
  Regression -> MSE: 0.000231, MAE: 0.009879, R²: -0.0004
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12586 | val 0.13923
  Epoch 020 - train 0.12881 | val 0.14821
  Epoch 021 - train 0.12343 | val 0.14860
  Regression -> MSE: 0.000135, MAE: 0.008168, R²: 0.0003
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12119 | val 0.15186
  Epoch 020 - train 0.12151 | val 0.15439
  Epoch 021 - train 0.11841 | val 0.15502
  Regression -> MSE: 0.000188, MAE: 0.010527, R²: 0.0001
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11324 | val 0.13562
  Epoch 020 - train 0.10991 | val 0.13447
  Epoch 021 - train 0.10608 | val 0.13385
  Regression -> MSE: 0.000289, MAE: 0.011245, R²: -0.1025
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11299 | val 0.10061
  Epoch 020 - train 0.11333 | val 0.10177
  Epoch 021 - train 0.10595 | val 0.10236
  Regression -> MSE: 0.000166, MAE: 0.010366, R²: 0.0018
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11811 | val 0.12564
  Epoch 020 - train 0.11078 | val 0.12831
  Epoch 021 - train 0.11286 | val 0.12866
  Regression -> MSE: 0.000186, MAE: 0.010551, R²: -0.0328
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12105 | val 0.11760
  Epoch 020 - train 0.11369 | val 0.11877
  Epoch 021 - train 0.11053 | val 0.11848
  Regression -> MSE: 0.000346, MAE: 0.011732, R²: -0.0099
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13366 | val 0.08209
  Epoch 020 - train 0.11978 | val 0.08332
  Epoch 021 - train 0.12366 | val 0.08288
  Regression -> MSE: 0.000109, MAE: 0.008337, R²: -0.0395
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11654 | val 0.16886
  Epoch 020 - train 0.11589 | val 0.17614
  Epoch 021 - train 0.11618 | val 0.17598
  Regression -> MSE: 0.000220, MAE: 0.011335, R²: -0.0074
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12052 | val 0.20357
  Epoch 020 - train 0.11684 | val 0.21611
  Epoch 021 - train 0.11690 | val 0.21593
  Regression -> MSE: 0.000094, MAE: 0.007571, R²: -0.2110
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12331 | val 0.09406
  Epoch 020 - train 0.11283 | val 0.10371
  Epoch 021 - train 0.11715 | val 0.10407
  Regression -> MSE: 0.000311, MAE: 0.013998, R²: -0.0101
  Directional -> Accuracy: 0.3469, MCC: -0.2133, F1: 0.4074

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13333 | val 0.07275
  Epoch 020 - train 0.13233 | val 0.07494
  Epoch 021 - train 0.12797 | val 0.07559
  Regression -> MSE: 0.000248, MAE: 0.011491, R²: -0.0190
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11276 | val 0.14640
  Epoch 020 - train 0.10377 | val 0.14844
  Epoch 021 - train 0.11156 | val 0.14862
  Regression -> MSE: 0.000081, MAE: 0.007062, R²: -0.0028
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11632 | val 0.14838
  Epoch 020 - train 0.12396 | val 0.14926
  Epoch 021 - train 0.11901 | val 0.14959
  Regression -> MSE: 0.000309, MAE: 0.014477, R²: -0.0082
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11107 | val 0.13803
  Epoch 020 - train 0.12062 | val 0.13628
  Epoch 021 - train 0.12286 | val 0.13661
  Regression -> MSE: 0.000101, MAE: 0.007114, R²: -0.0299
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13415 | val 0.13941
  Epoch 020 - train 0.12824 | val 0.14059
  Epoch 021 - train 0.13364 | val 0.14115
  Regression -> MSE: 0.000172, MAE: 0.009809, R²: -0.0015
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11296 | val 0.13920
  Epoch 020 - train 0.10897 | val 0.14010
  Epoch 021 - train 0.11616 | val 0.14060
  Regression -> MSE: 0.000229, MAE: 0.011861, R²: -0.0253
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12258 | val 0.14078
  Epoch 020 - train 0.11050 | val 0.14638
  Epoch 021 - train 0.11877 | val 0.14691

[I 2026-02-24 04:17:17,393] Trial 168 finished with value: -0.011421038364425668 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 7.294791806510476e-05, 'weight_decay': 1.2070960881897785e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.17775772657524896, 'early_stopping_min_delta': 0.00967646740622416}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.11935 | val 0.16216
  Epoch 021 - train 0.12124 | val 0.16288
  Regression -> MSE: 0.000237, MAE: 0.012405, R²: 0.0009
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11515 | val 0.17443
  Epoch 020 - train 0.11378 | val 0.16904
  Epoch 021 - train 0.11817 | val 0.16866
  Regression -> MSE: 0.000259, MAE: 0.012983, R²: -0.0470
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12346 | val 0.11305
  Epoch 020 - train 0.11518 | val 0.14258
  Epoch 021 - train 0.11899 | val 0.14266
  Regression -> MSE: 0.000701, MAE: 0.019613, R²: -0.0233
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11211 | val 0.18544
  Epoch 020 - train 0.11656 | val 0.18646
  Epoch 021 - train 0.11648 | val 0.18659
  Regression -> MSE: 0.000312, MAE: 0.014414, R²: -0.0050
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10103 | val 0.19952
  Epoch 020 - train 0.09816 | val 0.20456
  Epoch 021 - train 0.09724 | val 0.20281
  Regression -> MSE: 0.000351, MAE: 0.014624, R²: -0.0054
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11732 | val 0.11253
  Epoch 020 - train 0.11529 | val 0.11296
  Epoch 021 - train 0.11312 | val 0.11295
  Regression -> MSE: 0.000204, MAE: 0.010130, R²: -0.0029
  Directional -> Accuracy: 0.4118, MCC: -0.1674, F1: 0.2857

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11111 | val 0.21642
  Epoch 020 - train 0.11474 | val 0.21250
  Epoch 021 - train 0.11192 | val 0.21163
  Regression -> MSE: 0.000594, MAE: 0.018857, R²: -0.0693
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11989 | val 0.14640
  Epoch 020 - train 0.12090 | val 0.14567
  Epoch 021 - train 0.12113 | val 0.14484
  Regression -> MSE: 0.000246, MAE: 0.011930, R²: -0.0038
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12560 | val 0.13983
  Epoch 020 - train 0.11369 | val 0.15629
  Epoch 021 - train 0.11172 | val 0.15782
  Regression -> MSE: 0.000607, MAE: 0.019384, R²: -0.0160
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11076 | val 0.14162
  Epoch 020 - train 0.11102 | val 0.13667
  Epoch 021 - train 0.11387 | val 0.13652
  Regression -> MSE: 0.000385, MAE: 0.016156, R²: -0.0039
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11259 | val 0.14633
  Epoch 020 - train 0.11541 | val 0.14601
  Epoch 021 - train 0.11660 | val 0.14616
  Regression -> MSE: 0.000246, MAE: 0.011645, R²: -0.0197
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10914 | val 0.16760
  Epoch 020 - train 0.10778 | val 0.18047
  Epoch 021 - train 0.11226 | val 0.18066
  Regression -> MSE: 0.000312, MAE: 0.013659, R²: -0.0027
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12393 | val 0.14218
  Epoch 020 - train 0.11829 | val 0.14679
  Epoch 021 - train 0.12011 | val 0.14713
  Regression -> MSE: 0.000678, MAE: 0.019520, R²: -0.0010
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11886 | val 0.11436
  Epoch 020 - train 0.12113 | val 0.11728
  Epoch 021 - train 0.11263 | val 0.11662
  Regression -> MSE: 0.000142, MAE: 0.009392, R²: -0.0296
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10845 | val 0.16320
  Epoch 020 - train 0.10976 | val 0.16321
  Epoch 021 - train 0.11193 | val 0.16250
  Regression -> MSE: 0.000225, MAE: 0.010699, R²: -0.0022
  Directional -> Accuracy: 0.5082, MCC: 0.0455, F1: 0.2105

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11979 | val 0.22862
  Epoch 020 - train 0.11303 | val 0.22720
  Epoch 021 - train 0.11312 | val 0.22714
  Regression -> MSE: 0.000362, MAE: 0.016051, R²: 0.0006
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11954 | val 0.12065
  Epoch 020 - train 0.12093 | val 0.12109
  Epoch 021 - train 0.12693 | val 0.12124
  Regression -> MSE: 0.000113, MAE: 0.007993, R²: -0.0505
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10885 | val 0.21340
  Epoch 020 - train 0.11254 | val 0.23116
  Epoch 021 - train 0.11894 | val 0.23195
  Regression -> MSE: 0.000158, MAE: 0.009973, R²: -0.0152
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11905 | val 0.11617
  Epoch 020 - train 0.11688 | val 0.12223
  Epoch 021 - train 0.11564 | val 0.12231
  Regression -> MSE: 0.000273, MAE: 0.012986, R²: -0.0019
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11123 | val 0.15031
  Epoch 020 - train 0.10393 | val 0.14793
  Epoch 021 - train 0.10213 | val 0.14832
  Regression -> MSE: 0.000161, MAE: 0.008959, R²: -0.0793
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12008 | val 0.17334
  Epoch 020 - train 0.11949 | val 0.18165
  Epoch 021 - train 0.11219 | val 0.18236
  Regression -> MSE: 0.000230, MAE: 0.010892, R²: -0.0144
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12089 | val 0.15066
  Epoch 020 - train 0.11284 | val 0.16647
  Epoch 021 - train 0.10819 | val 0.16608
  Regression -> MSE: 0.000148, MAE: 0.008609, R²: -0.0341
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10868 | val 0.13846
  Epoch 020 - train 0.11231 | val 0.13973
  Epoch 021 - train 0.10710 | val 0.13906
  Regression -> MSE: 0.000166, MAE: 0.010659, R²: -0.0047
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11975 | val 0.14034
  Epoch 020 - train 0.11898 | val 0.14356
  Epoch 021 - train 0.12086 | val 0.14367
  Regression -> MSE: 0.000086, MAE: 0.007108, R²: -0.0108
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11789 | val 0.14254
  Epoch 020 - train 0.11394 | val 0.14960
  Epoch 021 - train 0.11131 | val 0.15138
  Regression -> MSE: 0.000216, MAE: 0.011513, R²: -0.0183
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10706 | val 0.10397
  Epoch 020 - train 0.10253 | val 0.10301
  Epoch 021 - train 0.10230 | val 0.10358
  Regression -> MSE: 0.000096, MAE: 0.008136, R²: -0.0452
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11559 | val 0.08907
  Epoch 020 - train 0.11644 | val 0.10546
  Epoch 021 - train 0.11628 | val 0.10763
  Regression -> MSE: 0.000104, MAE: 0.008798, R²: -0.0088
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12431 | val 0.10993
  Epoch 020 - train 0.12273 | val 0.11597
  Epoch 021 - train 0.12124 | val 0.11668
  Regression -> MSE: 0.000233, MAE: 0.012597, R²: -0.0063
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12069 | val 0.12860
  Epoch 020 - train 0.11165 | val 0.12971
  Epoch 021 - train 0.11134 | val 0.12976
  Regression -> MSE: 0.000183, MAE: 0.008010, R²: -0.0984
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13047 | val 0.09797
  Epoch 020 - train 0.11414 | val 0.09862
  Epoch 021 - train 0.12087 | val 0.09800
  Regression -> MSE: 0.000237, MAE: 0.011859, R²: -0.0005
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12026 | val 0.17800
  Epoch 020 - train 0.11671 | val 0.18514
  Epoch 021 - train 0.11952 | val 0.18550
  Regression -> MSE: 0.000230, MAE: 0.009863, R²: 0.0003
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12179 | val 0.13787
  Epoch 020 - train 0.11690 | val 0.15503
  Epoch 021 - train 0.12838 | val 0.15531
  Regression -> MSE: 0.000135, MAE: 0.008222, R²: -0.0013
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11756 | val 0.14782
  Epoch 020 - train 0.11443 | val 0.15053
  Epoch 021 - train 0.11430 | val 0.15075
  Regression -> MSE: 0.000188, MAE: 0.010556, R²: -0.0008
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10754 | val 0.12636
  Epoch 020 - train 0.10574 | val 0.12363
  Epoch 021 - train 0.10304 | val 0.12350
  Regression -> MSE: 0.000264, MAE: 0.010538, R²: -0.0084
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10843 | val 0.09544
  Epoch 020 - train 0.11040 | val 0.09813
  Epoch 021 - train 0.11066 | val 0.09912
  Regression -> MSE: 0.000168, MAE: 0.010373, R²: -0.0100
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10490 | val 0.11722
  Epoch 020 - train 0.10538 | val 0.12158
  Epoch 021 - train 0.11532 | val 0.12164
  Regression -> MSE: 0.000180, MAE: 0.010311, R²: 0.0005
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10817 | val 0.11089
  Epoch 020 - train 0.10976 | val 0.11297
  Epoch 021 - train 0.10821 | val 0.11266
  Regression -> MSE: 0.000343, MAE: 0.011956, R²: -0.0007
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12890 | val 0.07514
  Epoch 020 - train 0.11095 | val 0.08117
  Epoch 021 - train 0.11745 | val 0.08175
  Regression -> MSE: 0.000120, MAE: 0.008375, R²: -0.1451
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12135 | val 0.15355
  Epoch 020 - train 0.11617 | val 0.15892
  Epoch 021 - train 0.11470 | val 0.15920
  Regression -> MSE: 0.000226, MAE: 0.011502, R²: -0.0342
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11344 | val 0.19294
  Epoch 020 - train 0.11327 | val 0.19741
  Epoch 021 - train 0.10979 | val 0.19753
  Regression -> MSE: 0.000082, MAE: 0.007058, R²: -0.0555
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11483 | val 0.09136
  Epoch 020 - train 0.11271 | val 0.09502
  Epoch 021 - train 0.10965 | val 0.09524
  Regression -> MSE: 0.000319, MAE: 0.014442, R²: -0.0372
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12085 | val 0.07316
  Epoch 020 - train 0.11995 | val 0.07590
  Epoch 021 - train 0.11746 | val 0.07719
  Regression -> MSE: 0.000256, MAE: 0.011474, R²: -0.0511
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11147 | val 0.13526
  Epoch 020 - train 0.10982 | val 0.13414
  Epoch 021 - train 0.10727 | val 0.13372
  Regression -> MSE: 0.000083, MAE: 0.007058, R²: -0.0212
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11800 | val 0.14495
  Epoch 020 - train 0.11619 | val 0.13886
  Epoch 021 - train 0.12030 | val 0.13971
  Regression -> MSE: 0.000309, MAE: 0.014484, R²: -0.0087
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10752 | val 0.12605
  Epoch 020 - train 0.11034 | val 0.12463
  Epoch 021 - train 0.11296 | val 0.12498
  Regression -> MSE: 0.000099, MAE: 0.007177, R²: -0.0080
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13193 | val 0.13645
  Epoch 020 - train 0.12718 | val 0.14286
  Epoch 021 - train 0.12825 | val 0.14297
  Regression -> MSE: 0.000174, MAE: 0.010078, R²: -0.0138
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11272 | val 0.13711
  Epoch 020 - train 0.11394 | val 0.14333
  Epoch 021 - train 0.10556 | val 0.14284
  Regression -> MSE: 0.000226, MAE: 0.011796, R²: -0.0135
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11507 | val 0.13527
  Epoch 020 - train 0.11545 | val 0.15893
  Epoch 021 - train 0.11125 | val 0.15776

[I 2026-02-24 04:19:26,684] Trial 169 finished with value: -0.011433372602772614 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 5.3259975454561695e-05, 'weight_decay': 1.439564500611929e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.16881535071816559, 'early_stopping_min_delta': 0.00969134618997567}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.11578 | val 0.21584
  Epoch 021 - train 0.11744 | val 0.21783
  Regression -> MSE: 0.000239, MAE: 0.012327, R²: -0.0096
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.33504 | val 0.46233
  Epoch 020 - train 0.30145 | val 0.46066
  Epoch 026 - train 0.29966 | val 0.45956
  Regression -> MSE: 0.000256, MAE: 0.012854, R²: -0.0348
  Directional -> Accuracy: 0.4416, MCC: -0.1054, F1: 0.4557

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.29557 | val 0.31035
  Epoch 020 - train 0.29445 | val 0.38598
  Epoch 027 - train 0.29269 | val 0.38832
  Regression -> MSE: 0.000676, MAE: 0.019232, R²: 0.0119
  Directional -> Accuracy: 0.6087, MCC: 0.1757, F1: 0.7097

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.32571 | val 0.58266
  Epoch 020 - train 0.32617 | val 0.59006
  Epoch 021 - train 0.32922 | val 0.59014
  Regression -> MSE: 0.000313, MAE: 0.014429, R²: -0.0095
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.26547 | val 0.30672
  Epoch 020 - train 0.27915 | val 0.39249
  Epoch 024 - train 0.26959 | val 0.40487
  Regression -> MSE: 0.000347, MAE: 0.014483, R²: 0.0080
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.34375 | val 0.34198
  Epoch 020 - train 0.30793 | val 0.35546
  Epoch 021 - train 0.31876 | val 0.35337
  Regression -> MSE: 0.000204, MAE: 0.010152, R²: 0.0001
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.34444 | val 0.67106
  Epoch 020 - train 0.30920 | val 0.69729
  Epoch 028 - train 0.31559 | val 0.71681
  Regression -> MSE: 0.000555, MAE: 0.018075, R²: -0.0002
  Directional -> Accuracy: 0.4681, MCC: -0.1460, F1: 0.0741

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.33555 | val 0.43145
  Epoch 020 - train 0.33941 | val 0.43096
  Epoch 021 - train 0.33956 | val 0.42948
  Regression -> MSE: 0.000246, MAE: 0.012018, R²: -0.0002
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.35082 | val 0.45861
  Epoch 020 - train 0.32360 | val 0.44945
  Epoch 030 - train 0.30186 | val 0.46309
  Regression -> MSE: 0.000630, MAE: 0.019685, R²: -0.0546
  Directional -> Accuracy: 0.4773, MCC: -0.0212, F1: 0.4651

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.34174 | val 0.38769
  Epoch 020 - train 0.31189 | val 0.40744
  Epoch 021 - train 0.31236 | val 0.40867
  Regression -> MSE: 0.000411, MAE: 0.016261, R²: -0.0714
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.30874 | val 0.43135
  Epoch 020 - train 0.31417 | val 0.43944
  Epoch 021 - train 0.32294 | val 0.43839
  Regression -> MSE: 0.000244, MAE: 0.011625, R²: -0.0104
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.33042 | val 0.57957
  Epoch 020 - train 0.28948 | val 0.58971
  Epoch 021 - train 0.30277 | val 0.59417
  Regression -> MSE: 0.000311, MAE: 0.013749, R²: 0.0012
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.32666 | val 0.46132
  Epoch 020 - train 0.32954 | val 0.50038
  Epoch 021 - train 0.32295 | val 0.49976
  Regression -> MSE: 0.000679, MAE: 0.019552, R²: -0.0022
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.31968 | val 0.34489
  Epoch 020 - train 0.31275 | val 0.41522
  Epoch 021 - train 0.32031 | val 0.40997
  Regression -> MSE: 0.000139, MAE: 0.009249, R²: -0.0089
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.30268 | val 0.48774
  Epoch 020 - train 0.30995 | val 0.48339
  Epoch 021 - train 0.29953 | val 0.48454
  Regression -> MSE: 0.000225, MAE: 0.010740, R²: -0.0009
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.31753 | val 0.76650
  Epoch 020 - train 0.30987 | val 0.77715
  Epoch 021 - train 0.33005 | val 0.77817
  Regression -> MSE: 0.000372, MAE: 0.015934, R²: -0.0263
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.33396 | val 0.35187
  Epoch 020 - train 0.33438 | val 0.34662
  Epoch 021 - train 0.32739 | val 0.34517
  Regression -> MSE: 0.000109, MAE: 0.008154, R²: -0.0129
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.31124 | val 0.63554
  Epoch 020 - train 0.30093 | val 0.66104
  Epoch 021 - train 0.30968 | val 0.65975
  Regression -> MSE: 0.000156, MAE: 0.009663, R²: 0.0011
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.34899 | val 0.33172
  Epoch 020 - train 0.32574 | val 0.33321
  Epoch 021 - train 0.32710 | val 0.33347
  Regression -> MSE: 0.000272, MAE: 0.013064, R²: -0.0013
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.28763 | val 0.43543
  Epoch 020 - train 0.27287 | val 0.43627
  Epoch 030 - train 0.27366 | val 0.42811
  Regression -> MSE: 0.000187, MAE: 0.009910, R²: -0.2504
  Directional -> Accuracy: 0.4923, MCC: 0.0483, F1: 0.4407

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.32696 | val 0.49597
  Epoch 020 - train 0.31037 | val 0.51831
  Epoch 026 - train 0.32419 | val 0.51344
  Regression -> MSE: 0.000262, MAE: 0.011660, R²: -0.1558
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.33956 | val 0.41283
  Epoch 020 - train 0.31386 | val 0.40737
  Epoch 030 - train 0.30440 | val 0.41172
  Regression -> MSE: 0.000177, MAE: 0.009847, R²: -0.2345
  Directional -> Accuracy: 0.3542, MCC: -0.1920, F1: 0.2439

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.31051 | val 0.38429
  Epoch 020 - train 0.29046 | val 0.38756
  Epoch 027 - train 0.31012 | val 0.38940
  Regression -> MSE: 0.000166, MAE: 0.010276, R²: -0.0065
  Directional -> Accuracy: 0.4848, MCC: -0.0362, F1: 0.5952

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.33320 | val 0.40102
  Epoch 020 - train 0.32911 | val 0.40528
  Epoch 021 - train 0.32580 | val 0.40515
  Regression -> MSE: 0.000087, MAE: 0.007129, R²: -0.0152
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.33829 | val 0.57866
  Epoch 020 - train 0.31815 | val 0.60454
  Epoch 021 - train 0.30943 | val 0.60853
  Regression -> MSE: 0.000212, MAE: 0.011094, R²: -0.0023
  Directional -> Accuracy: 0.5000, MCC: 0.0501, F1: 0.6118

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.30420 | val 0.26150
  Epoch 020 - train 0.27800 | val 0.25980
  Epoch 030 - train 0.27161 | val 0.26177
  Regression -> MSE: 0.000085, MAE: 0.007605, R²: 0.0745
  Directional -> Accuracy: 0.6250, MCC: 0.2272, F1: 0.7042

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.36452 | val 0.23996
  Epoch 020 - train 0.32704 | val 0.26519
  Epoch 021 - train 0.33556 | val 0.26801
  Regression -> MSE: 0.000103, MAE: 0.008729, R²: -0.0002
  Directional -> Accuracy: 0.4783, MCC: 0.0553, F1: 0.5862

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.34539 | val 0.31309
  Epoch 020 - train 0.32611 | val 0.35874
  Epoch 021 - train 0.34200 | val 0.35885
  Regression -> MSE: 0.000235, MAE: 0.012676, R²: -0.0149
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.31935 | val 0.39833
  Epoch 020 - train 0.30182 | val 0.39447
  Epoch 030 - train 0.30194 | val 0.39704
  Regression -> MSE: 0.000179, MAE: 0.007929, R²: -0.0761
  Directional -> Accuracy: 0.4912, MCC: 0.0465, F1: 0.3830

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.31870 | val 0.25110
  Epoch 020 - train 0.35631 | val 0.24338
  Epoch 030 - train 0.32066 | val 0.27156
  Regression -> MSE: 0.000232, MAE: 0.011819, R²: 0.0207
  Directional -> Accuracy: 0.5366, MCC: 0.0241, F1: 0.6780

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.34174 | val 0.59841
  Epoch 020 - train 0.32145 | val 0.63960
  Epoch 021 - train 0.32580 | val 0.63898
  Regression -> MSE: 0.000236, MAE: 0.010187, R²: -0.0220
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.32903 | val 0.39402
  Epoch 020 - train 0.33741 | val 0.41304
  Epoch 021 - train 0.32231 | val 0.41346
  Regression -> MSE: 0.000135, MAE: 0.008190, R²: 0.0015
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.30484 | val 0.42819
  Epoch 020 - train 0.29685 | val 0.43132
  Epoch 021 - train 0.31263 | val 0.43100
  Regression -> MSE: 0.000192, MAE: 0.010407, R²: -0.0204
  Directional -> Accuracy: 0.4600, MCC: -0.2173, F1: 0.6197

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.28959 | val 0.37081
  Epoch 020 - train 0.28073 | val 0.36388
  Epoch 030 - train 0.26312 | val 0.36042
  Regression -> MSE: 0.000364, MAE: 0.013236, R²: -0.3887
  Directional -> Accuracy: 0.5068, MCC: 0.0735, F1: 0.4194

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.34019 | val 0.27678
  Epoch 020 - train 0.31525 | val 0.26863
  Epoch 030 - train 0.28003 | val 0.27996
  Regression -> MSE: 0.000171, MAE: 0.010390, R²: -0.0274
  Directional -> Accuracy: 0.5263, MCC: 0.0976, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.32083 | val 0.32480
  Epoch 020 - train 0.28519 | val 0.32253
  Epoch 030 - train 0.27610 | val 0.33259
  Regression -> MSE: 0.000192, MAE: 0.010617, R²: -0.0697
  Directional -> Accuracy: 0.5455, MCC: 0.1026, F1: 0.1667

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.33051 | val 0.31342
  Epoch 020 - train 0.30930 | val 0.31763
  Epoch 021 - train 0.29036 | val 0.31719
  Regression -> MSE: 0.000346, MAE: 0.011710, R²: -0.0098
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.33405 | val 0.18513
  Epoch 020 - train 0.33083 | val 0.18620
  Epoch 021 - train 0.34875 | val 0.18683
  Regression -> MSE: 0.000115, MAE: 0.008337, R²: -0.0983
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.33234 | val 0.48660
  Epoch 020 - train 0.31381 | val 0.52618
  Epoch 025 - train 0.28723 | val 0.51786
  Regression -> MSE: 0.000222, MAE: 0.011462, R²: -0.0167
  Directional -> Accuracy: 0.3684, MCC: -0.2584, F1: 0.4000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.33662 | val 0.61210
  Epoch 020 - train 0.32064 | val 0.60955
  Epoch 030 - train 0.31950 | val 0.62377
  Regression -> MSE: 0.000080, MAE: 0.007034, R²: -0.0266
  Directional -> Accuracy: 0.5957, MCC: 0.0814, F1: 0.7077

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.34198 | val 0.27359
  Epoch 020 - train 0.32669 | val 0.25780
  Epoch 030 - train 0.28455 | val 0.25744
  Regression -> MSE: 0.000363, MAE: 0.015979, R²: -0.1794
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.37413 | val 0.19348
  Epoch 020 - train 0.34584 | val 0.19566
  Epoch 021 - train 0.28519 | val 0.19773
  Regression -> MSE: 0.000264, MAE: 0.011524, R²: -0.0813
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.33140 | val 0.40523
  Epoch 020 - train 0.30989 | val 0.40420
  Epoch 021 - train 0.29606 | val 0.40526
  Regression -> MSE: 0.000081, MAE: 0.007085, R²: -0.0019
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.35189 | val 0.40823
  Epoch 020 - train 0.29722 | val 0.41612
  Epoch 030 - train 0.32040 | val 0.44839
  Regression -> MSE: 0.000308, MAE: 0.014486, R²: -0.0042
  Directional -> Accuracy: 0.5319, MCC: 0.0634, F1: 0.5417

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.33420 | val 0.36003
  Epoch 020 - train 0.29889 | val 0.33950
  Epoch 030 - train 0.28010 | val 0.34014
  Regression -> MSE: 0.000097, MAE: 0.007020, R²: 0.0140
  Directional -> Accuracy: 0.6364, MCC: 0.2661, F1: 0.7500

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.37936 | val 0.42672
  Epoch 020 - train 0.37248 | val 0.46480
  Epoch 021 - train 0.38269 | val 0.46786
  Regression -> MSE: 0.000175, MAE: 0.009416, R²: -0.0194
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 04:21:50,079] Trial 170 finished with value: -0.011517162189938203 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 6.097368650397642e-05, 'weight_decay': 2.0549285982810176e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.650666736004764, 'early_stopping_min_delta': 0.004178444983665223}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.32897 | val 0.51395
  Epoch 021 - train 0.31429 | val 0.51313
  Regression -> MSE: 0.000238, MAE: 0.012335, R²: -0.0040
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11504 | val 0.15305
  Epoch 020 - train 0.10868 | val 0.17048
  Epoch 021 - train 0.11006 | val 0.17298
  Regression -> MSE: 0.000255, MAE: 0.012825, R²: -0.0282
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10258 | val 0.11097
  Epoch 020 - train 0.10256 | val 0.12238
  Epoch 021 - train 0.09803 | val 0.12530
  Regression -> MSE: 0.000685, MAE: 0.019324, R²: -0.0002
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11727 | val 0.18171
  Epoch 020 - train 0.10860 | val 0.18422
  Epoch 030 - train 0.10883 | val 0.18741
  Regression -> MSE: 0.000320, MAE: 0.014342, R²: -0.0321
  Directional -> Accuracy: 0.5745, MCC: 0.1645, F1: 0.5455

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09426 | val 0.10340
  Epoch 020 - train 0.09248 | val 0.12106
  Epoch 021 - train 0.08612 | val 0.12165
  Regression -> MSE: 0.000388, MAE: 0.015226, R²: -0.1108
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10790 | val 0.12753
  Epoch 020 - train 0.09691 | val 0.12720
  Epoch 021 - train 0.10137 | val 0.12737
  Regression -> MSE: 0.000207, MAE: 0.010064, R²: -0.0145
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10813 | val 0.21007
  Epoch 020 - train 0.09823 | val 0.25034
  Epoch 021 - train 0.10711 | val 0.24940
  Regression -> MSE: 0.000563, MAE: 0.018233, R²: -0.0148
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11331 | val 0.14694
  Epoch 020 - train 0.10932 | val 0.14582
  Epoch 021 - train 0.10977 | val 0.14905
  Regression -> MSE: 0.000247, MAE: 0.012311, R²: -0.0060
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11169 | val 0.15206
  Epoch 020 - train 0.11092 | val 0.17077
  Epoch 021 - train 0.10308 | val 0.17236
  Regression -> MSE: 0.000615, MAE: 0.019577, R²: -0.0288
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10178 | val 0.13699
  Epoch 020 - train 0.10042 | val 0.13825
  Epoch 021 - train 0.09878 | val 0.13828
  Regression -> MSE: 0.000409, MAE: 0.016219, R²: -0.0654
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10751 | val 0.15672
  Epoch 020 - train 0.10304 | val 0.15775
  Epoch 021 - train 0.10423 | val 0.15525
  Regression -> MSE: 0.000242, MAE: 0.012073, R²: -0.0023
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10621 | val 0.19324
  Epoch 020 - train 0.10104 | val 0.20206
  Epoch 021 - train 0.10380 | val 0.19875
  Regression -> MSE: 0.000311, MAE: 0.013796, R²: 0.0003
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11607 | val 0.14816
  Epoch 020 - train 0.11173 | val 0.15555
  Epoch 021 - train 0.11060 | val 0.15697
  Regression -> MSE: 0.000682, MAE: 0.019736, R²: -0.0073
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10856 | val 0.14953
  Epoch 020 - train 0.10805 | val 0.18137
  Epoch 021 - train 0.10676 | val 0.18534
  Regression -> MSE: 0.000138, MAE: 0.009081, R²: -0.0003
  Directional -> Accuracy: 0.5581, MCC: 0.0259, F1: 0.0952

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10061 | val 0.14626
  Epoch 020 - train 0.09946 | val 0.14633
  Epoch 021 - train 0.09671 | val 0.14860
  Regression -> MSE: 0.000226, MAE: 0.010708, R²: -0.0038
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10845 | val 0.25117
  Epoch 020 - train 0.09814 | val 0.26346
  Epoch 021 - train 0.10070 | val 0.26691
  Regression -> MSE: 0.000363, MAE: 0.016039, R²: -0.0019
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11580 | val 0.13322
  Epoch 020 - train 0.10993 | val 0.13287
  Epoch 021 - train 0.10640 | val 0.13157
  Regression -> MSE: 0.000111, MAE: 0.007958, R²: -0.0256
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10023 | val 0.28387
  Epoch 020 - train 0.10712 | val 0.30090
  Epoch 021 - train 0.10499 | val 0.29421
  Regression -> MSE: 0.000160, MAE: 0.010107, R²: -0.0285
  Directional -> Accuracy: 0.5424, MCC: 0.0832, F1: 0.5970

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11177 | val 0.12299
  Epoch 020 - train 0.11134 | val 0.11805
  Epoch 021 - train 0.10853 | val 0.11816
  Regression -> MSE: 0.000277, MAE: 0.013283, R²: -0.0165
  Directional -> Accuracy: 0.5526, MCC: 0.1565, F1: 0.5526

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09955 | val 0.14606
  Epoch 020 - train 0.09426 | val 0.15024
  Epoch 021 - train 0.09317 | val 0.14935
  Regression -> MSE: 0.000163, MAE: 0.009004, R²: -0.0907
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11324 | val 0.17966
  Epoch 020 - train 0.10913 | val 0.17098
  Epoch 021 - train 0.10743 | val 0.17347
  Regression -> MSE: 0.000235, MAE: 0.010957, R²: -0.0400
  Directional -> Accuracy: 0.4933, MCC: 0.0890, F1: 0.2400

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12054 | val 0.14368
  Epoch 020 - train 0.10856 | val 0.15074
  Epoch 021 - train 0.11034 | val 0.15074
  Regression -> MSE: 0.000143, MAE: 0.008317, R²: 0.0003
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10412 | val 0.14324
  Epoch 020 - train 0.10327 | val 0.14501
  Epoch 021 - train 0.10269 | val 0.14550
  Regression -> MSE: 0.000165, MAE: 0.010377, R²: -0.0006
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11616 | val 0.13569
  Epoch 020 - train 0.11180 | val 0.13709
  Epoch 021 - train 0.11183 | val 0.13645
  Regression -> MSE: 0.000093, MAE: 0.007454, R²: -0.0939
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10996 | val 0.20922
  Epoch 020 - train 0.10375 | val 0.18158
  Epoch 021 - train 0.10748 | val 0.17430
  Regression -> MSE: 0.000212, MAE: 0.011054, R²: -0.0017
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09888 | val 0.09715
  Epoch 020 - train 0.09771 | val 0.09860
  Epoch 030 - train 0.09866 | val 0.10472
  Regression -> MSE: 0.000114, MAE: 0.008406, R²: -0.2398
  Directional -> Accuracy: 0.5536, MCC: 0.1704, F1: 0.4681

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11569 | val 0.08929
  Epoch 020 - train 0.10783 | val 0.09040
  Epoch 021 - train 0.10917 | val 0.09141
  Regression -> MSE: 0.000105, MAE: 0.008874, R²: -0.0228
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11752 | val 0.11920
  Epoch 020 - train 0.11310 | val 0.17863
  Epoch 021 - train 0.11249 | val 0.17827
  Regression -> MSE: 0.000238, MAE: 0.012771, R²: -0.0267
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11039 | val 0.13435
  Epoch 020 - train 0.10531 | val 0.14117
  Epoch 021 - train 0.10869 | val 0.14152
  Regression -> MSE: 0.000169, MAE: 0.007833, R²: -0.0160
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11736 | val 0.09812
  Epoch 020 - train 0.11362 | val 0.11046
  Epoch 021 - train 0.10559 | val 0.11209
  Regression -> MSE: 0.000237, MAE: 0.011873, R²: -0.0029
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11140 | val 0.18068
  Epoch 020 - train 0.10380 | val 0.20003
  Epoch 021 - train 0.10787 | val 0.20105
  Regression -> MSE: 0.000230, MAE: 0.009870, R²: 0.0004
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11152 | val 0.13709
  Epoch 020 - train 0.10744 | val 0.15750
  Epoch 021 - train 0.10920 | val 0.16617
  Regression -> MSE: 0.000135, MAE: 0.008246, R²: -0.0014
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10322 | val 0.15338
  Epoch 020 - train 0.10857 | val 0.16216
  Epoch 021 - train 0.10854 | val 0.16162
  Regression -> MSE: 0.000201, MAE: 0.010759, R²: -0.0672
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09747 | val 0.12515
  Epoch 020 - train 0.09378 | val 0.13331
  Epoch 021 - train 0.08895 | val 0.13381
  Regression -> MSE: 0.000262, MAE: 0.010528, R²: -0.0025
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10456 | val 0.09839
  Epoch 020 - train 0.09866 | val 0.10757
  Epoch 021 - train 0.09295 | val 0.11036
  Regression -> MSE: 0.000169, MAE: 0.010367, R²: -0.0150
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09870 | val 0.12675
  Epoch 020 - train 0.09134 | val 0.14203
  Epoch 021 - train 0.09654 | val 0.13865
  Regression -> MSE: 0.000181, MAE: 0.010376, R²: -0.0076
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11006 | val 0.11288
  Epoch 020 - train 0.09905 | val 0.11952
  Epoch 021 - train 0.10423 | val 0.12071
  Regression -> MSE: 0.000342, MAE: 0.011801, R²: 0.0015
  Directional -> Accuracy: 0.5672, MCC: 0.1461, F1: 0.5797

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11482 | val 0.07510
  Epoch 020 - train 0.10829 | val 0.08941
  Epoch 021 - train 0.10659 | val 0.08907
  Regression -> MSE: 0.000116, MAE: 0.008333, R²: -0.0996
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10979 | val 0.16458
  Epoch 020 - train 0.10333 | val 0.17210
  Epoch 021 - train 0.10260 | val 0.17452
  Regression -> MSE: 0.000220, MAE: 0.011341, R²: -0.0056
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10736 | val 0.20972
  Epoch 020 - train 0.10206 | val 0.26296
  Epoch 021 - train 0.10382 | val 0.26110
  Regression -> MSE: 0.000089, MAE: 0.007398, R²: -0.1500
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10629 | val 0.09063
  Epoch 020 - train 0.10631 | val 0.09645
  Epoch 021 - train 0.09915 | val 0.09854
  Regression -> MSE: 0.000313, MAE: 0.014157, R²: -0.0187
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12247 | val 0.07596
  Epoch 020 - train 0.10170 | val 0.08408
  Epoch 021 - train 0.10951 | val 0.08529
  Regression -> MSE: 0.000256, MAE: 0.011459, R²: -0.0498
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10323 | val 0.15091
  Epoch 020 - train 0.09918 | val 0.16742
  Epoch 021 - train 0.09569 | val 0.16142
  Regression -> MSE: 0.000081, MAE: 0.007111, R²: -0.0046
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11311 | val 0.13935
  Epoch 020 - train 0.10696 | val 0.19774
  Epoch 021 - train 0.10440 | val 0.19356
  Regression -> MSE: 0.000307, MAE: 0.014483, R²: -0.0009
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11013 | val 0.12823
  Epoch 020 - train 0.10591 | val 0.12578
  Epoch 021 - train 0.10013 | val 0.12610
  Regression -> MSE: 0.000100, MAE: 0.007146, R²: -0.0142
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12532 | val 0.13718
  Epoch 020 - train 0.10676 | val 0.15192
  Epoch 021 - train 0.12151 | val 0.15271
  Regression -> MSE: 0.000173, MAE: 0.009887, R²: -0.0054
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10450 | val 0.17891
  Epoch 020 - train 0.10154 | val 0.19041
  Epoch 021 - train 0.09827 | val 0.18801
  Regression -> MSE: 0.000225, MAE: 0.011778, R²: -0.0102
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10740 | val 0.14221
  Epoch 020 - train 0.10549 | val 0.15109
  Epoch 021 - train 0.10479 | val 0.15373

[I 2026-02-24 04:23:53,867] Trial 171 finished with value: -0.01144083888515514 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 0.0005100146545334924, 'weight_decay': 1.678964116847339e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.1702116394064166, 'early_stopping_min_delta': 0.009761216505849532}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.10708 | val 0.16940
  Epoch 021 - train 0.10923 | val 0.17549
  Regression -> MSE: 0.000239, MAE: 0.012327, R²: -0.0099
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09695 | val 0.12209
  Epoch 020 - train 0.09585 | val 0.12272
  Epoch 021 - train 0.09147 | val 0.12306
  Regression -> MSE: 0.000252, MAE: 0.012720, R²: -0.0169
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09057 | val 0.09274
  Epoch 020 - train 0.09245 | val 0.09371
  Epoch 021 - train 0.09300 | val 0.09387
  Regression -> MSE: 0.000686, MAE: 0.019344, R²: -0.0017
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10420 | val 0.15082
  Epoch 020 - train 0.09941 | val 0.14868
  Epoch 021 - train 0.10220 | val 0.14869
  Regression -> MSE: 0.000322, MAE: 0.014553, R²: -0.0389
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08156 | val 0.07915
  Epoch 020 - train 0.08100 | val 0.08878
  Epoch 021 - train 0.08125 | val 0.08920
  Regression -> MSE: 0.000384, MAE: 0.015155, R²: -0.0997
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10247 | val 0.10887
  Epoch 020 - train 0.09958 | val 0.12535
  Epoch 021 - train 0.09751 | val 0.12661
  Regression -> MSE: 0.000210, MAE: 0.010623, R²: -0.0314
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08876 | val 0.17598
  Epoch 020 - train 0.09492 | val 0.18302
  Epoch 021 - train 0.08733 | val 0.18297
  Regression -> MSE: 0.000583, MAE: 0.018637, R²: -0.0502
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09939 | val 0.11357
  Epoch 020 - train 0.09384 | val 0.11361
  Epoch 021 - train 0.09627 | val 0.11331
  Regression -> MSE: 0.000248, MAE: 0.012307, R²: -0.0086
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10279 | val 0.11406
  Epoch 020 - train 0.09264 | val 0.12089
  Epoch 021 - train 0.09629 | val 0.12116
  Regression -> MSE: 0.000605, MAE: 0.019325, R²: -0.0118
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09565 | val 0.11991
  Epoch 020 - train 0.09225 | val 0.12947
  Epoch 021 - train 0.09091 | val 0.12892
  Regression -> MSE: 0.000384, MAE: 0.016077, R²: -0.0003
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09806 | val 0.12320
  Epoch 020 - train 0.09354 | val 0.12527
  Epoch 021 - train 0.09313 | val 0.12425
  Regression -> MSE: 0.000242, MAE: 0.011960, R²: -0.0019
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09221 | val 0.13330
  Epoch 020 - train 0.09062 | val 0.13993
  Epoch 021 - train 0.08532 | val 0.14080
  Regression -> MSE: 0.000319, MAE: 0.013591, R²: -0.0269
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09860 | val 0.11744
  Epoch 020 - train 0.10375 | val 0.12191
  Epoch 021 - train 0.09904 | val 0.12193
  Regression -> MSE: 0.000677, MAE: 0.019496, R²: -0.0002
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10150 | val 0.12116
  Epoch 020 - train 0.09794 | val 0.14549
  Epoch 021 - train 0.10115 | val 0.14659
  Regression -> MSE: 0.000141, MAE: 0.009008, R²: -0.0180
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08992 | val 0.11677
  Epoch 020 - train 0.08386 | val 0.11537
  Epoch 030 - train 0.08047 | val 0.11527
  Regression -> MSE: 0.000221, MAE: 0.010542, R²: 0.0170
  Directional -> Accuracy: 0.5902, MCC: 0.1844, F1: 0.6479

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09784 | val 0.18908
  Epoch 020 - train 0.09425 | val 0.19394
  Epoch 021 - train 0.09547 | val 0.19404
  Regression -> MSE: 0.000363, MAE: 0.016043, R²: -0.0027
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10313 | val 0.11449
  Epoch 020 - train 0.10203 | val 0.10736
  Epoch 021 - train 0.09828 | val 0.10675
  Regression -> MSE: 0.000112, MAE: 0.008288, R²: -0.0345
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09190 | val 0.16088
  Epoch 020 - train 0.09167 | val 0.17752
  Epoch 021 - train 0.08971 | val 0.17761
  Regression -> MSE: 0.000155, MAE: 0.009628, R²: 0.0055
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09884 | val 0.10166
  Epoch 020 - train 0.09412 | val 0.10189
  Epoch 021 - train 0.09643 | val 0.10216
  Regression -> MSE: 0.000278, MAE: 0.013317, R²: -0.0206
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08760 | val 0.12317
  Epoch 020 - train 0.08475 | val 0.12187
  Epoch 021 - train 0.08620 | val 0.12185
  Regression -> MSE: 0.000163, MAE: 0.009005, R²: -0.0928
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09502 | val 0.16729
  Epoch 020 - train 0.09792 | val 0.17428
  Epoch 021 - train 0.09266 | val 0.17556
  Regression -> MSE: 0.000231, MAE: 0.010866, R²: -0.0224
  Directional -> Accuracy: 0.6400, MCC: 0.2812, F1: 0.7327

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09604 | val 0.11569
  Epoch 020 - train 0.09568 | val 0.11891
  Epoch 021 - train 0.09771 | val 0.11898
  Regression -> MSE: 0.000143, MAE: 0.008296, R²: -0.0009
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09370 | val 0.11132
  Epoch 020 - train 0.09006 | val 0.11168
  Epoch 021 - train 0.08893 | val 0.11152
  Regression -> MSE: 0.000164, MAE: 0.010498, R²: 0.0061
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09895 | val 0.11383
  Epoch 020 - train 0.09816 | val 0.11555
  Epoch 021 - train 0.09614 | val 0.11550
  Regression -> MSE: 0.000086, MAE: 0.007076, R²: -0.0045
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09672 | val 0.11362
  Epoch 020 - train 0.09038 | val 0.11672
  Epoch 021 - train 0.09116 | val 0.11670
  Regression -> MSE: 0.000212, MAE: 0.011086, R²: -0.0012
  Directional -> Accuracy: 0.5000, MCC: 0.1118, F1: 0.6452

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09015 | val 0.08108
  Epoch 020 - train 0.08847 | val 0.08064
  Epoch 021 - train 0.08532 | val 0.08055
  Regression -> MSE: 0.000094, MAE: 0.008095, R²: -0.0250
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10199 | val 0.08531
  Epoch 020 - train 0.10335 | val 0.10587
  Epoch 021 - train 0.10578 | val 0.10614
  Regression -> MSE: 0.000122, MAE: 0.009394, R²: -0.1791
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10569 | val 0.09476
  Epoch 020 - train 0.10416 | val 0.10015
  Epoch 021 - train 0.10020 | val 0.09962
  Regression -> MSE: 0.000245, MAE: 0.012952, R²: -0.0569
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09372 | val 0.10767
  Epoch 020 - train 0.08786 | val 0.11028
  Epoch 021 - train 0.09340 | val 0.11005
  Regression -> MSE: 0.000184, MAE: 0.008051, R²: -0.1086
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10522 | val 0.08266
  Epoch 020 - train 0.10290 | val 0.08815
  Epoch 021 - train 0.10265 | val 0.08920
  Regression -> MSE: 0.000237, MAE: 0.011907, R²: -0.0027
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09736 | val 0.14535
  Epoch 020 - train 0.09543 | val 0.15373
  Epoch 021 - train 0.09479 | val 0.15393
  Regression -> MSE: 0.000231, MAE: 0.009871, R²: -0.0007
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10060 | val 0.12280
  Epoch 020 - train 0.09760 | val 0.13116
  Epoch 021 - train 0.09761 | val 0.13128
  Regression -> MSE: 0.000144, MAE: 0.008648, R²: -0.0657
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10596 | val 0.11884
  Epoch 020 - train 0.10250 | val 0.12355
  Epoch 021 - train 0.09835 | val 0.12337
  Regression -> MSE: 0.000201, MAE: 0.010745, R²: -0.0670
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08368 | val 0.10249
  Epoch 020 - train 0.08603 | val 0.10224
  Epoch 021 - train 0.08263 | val 0.10195
  Regression -> MSE: 0.000267, MAE: 0.010545, R²: -0.0183
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09981 | val 0.07928
  Epoch 020 - train 0.09750 | val 0.08513
  Epoch 021 - train 0.08942 | val 0.08678
  Regression -> MSE: 0.000168, MAE: 0.010372, R²: -0.0108
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09718 | val 0.09286
  Epoch 020 - train 0.09386 | val 0.09839
  Epoch 021 - train 0.09342 | val 0.09846
  Regression -> MSE: 0.000181, MAE: 0.010334, R²: -0.0084
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09470 | val 0.08896
  Epoch 020 - train 0.08697 | val 0.08976
  Epoch 021 - train 0.09105 | val 0.08973
  Regression -> MSE: 0.000349, MAE: 0.011791, R²: -0.0195
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10171 | val 0.06169
  Epoch 020 - train 0.09992 | val 0.06564
  Epoch 021 - train 0.09753 | val 0.06553
  Regression -> MSE: 0.000115, MAE: 0.008309, R²: -0.0925
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09874 | val 0.12489
  Epoch 020 - train 0.09786 | val 0.12899
  Epoch 021 - train 0.09598 | val 0.13031
  Regression -> MSE: 0.000227, MAE: 0.011554, R²: -0.0404
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09209 | val 0.16405
  Epoch 020 - train 0.09555 | val 0.17197
  Epoch 021 - train 0.08685 | val 0.17238
  Regression -> MSE: 0.000080, MAE: 0.006980, R²: -0.0351
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09028 | val 0.07113
  Epoch 020 - train 0.08843 | val 0.07587
  Epoch 021 - train 0.08817 | val 0.07628
  Regression -> MSE: 0.000310, MAE: 0.013898, R²: -0.0062
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09987 | val 0.06178
  Epoch 020 - train 0.09981 | val 0.06492
  Epoch 021 - train 0.10207 | val 0.06554
  Regression -> MSE: 0.000260, MAE: 0.011493, R²: -0.0653
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09040 | val 0.11117
  Epoch 020 - train 0.08752 | val 0.11196
  Epoch 021 - train 0.08368 | val 0.11156
  Regression -> MSE: 0.000081, MAE: 0.007105, R²: -0.0028
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10200 | val 0.12078
  Epoch 020 - train 0.09634 | val 0.11665
  Epoch 021 - train 0.09539 | val 0.11620
  Regression -> MSE: 0.000310, MAE: 0.014500, R²: -0.0118
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09539 | val 0.09810
  Epoch 020 - train 0.09458 | val 0.09630
  Epoch 021 - train 0.09143 | val 0.09633
  Regression -> MSE: 0.000098, MAE: 0.007234, R²: -0.0027
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10937 | val 0.11257
  Epoch 020 - train 0.10327 | val 0.11804
  Epoch 021 - train 0.09634 | val 0.11850
  Regression -> MSE: 0.000173, MAE: 0.009520, R²: -0.0053
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08662 | val 0.10819
  Epoch 020 - train 0.08984 | val 0.11010
  Epoch 021 - train 0.09063 | val 0.11002
  Regression -> MSE: 0.000223, MAE: 0.011737, R²: -0.0001
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09973 | val 0.10131
  Epoch 020 - train 0.09343 | val 0.10142
  Epoch 021 - train 0.09676 | val 0.10144

[I 2026-02-24 04:25:54,928] Trial 172 finished with value: -0.011436099591173672 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 5.266026626610713e-05, 'weight_decay': 1.3415365470648754e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.13534453516263484, 'early_stopping_min_delta': 0.009217707606745631}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.09746 | val 0.14057
  Epoch 021 - train 0.09371 | val 0.14260
  Regression -> MSE: 0.000241, MAE: 0.012354, R²: -0.0167
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07738 | val 0.11172
  Epoch 020 - train 0.07776 | val 0.11001
  Epoch 021 - train 0.07601 | val 0.11074
  Regression -> MSE: 0.000254, MAE: 0.012800, R²: -0.0248
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07043 | val 0.07197
  Epoch 020 - train 0.07251 | val 0.07105
  Epoch 021 - train 0.07327 | val 0.07112
  Regression -> MSE: 0.000683, MAE: 0.019332, R²: 0.0027
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07689 | val 0.11451
  Epoch 020 - train 0.07856 | val 0.11240
  Epoch 021 - train 0.07904 | val 0.11229
  Regression -> MSE: 0.000311, MAE: 0.014466, R²: -0.0018
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06545 | val 0.06491
  Epoch 020 - train 0.06237 | val 0.06580
  Epoch 021 - train 0.06387 | val 0.06595
  Regression -> MSE: 0.000379, MAE: 0.015069, R²: -0.0861
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07502 | val 0.07282
  Epoch 020 - train 0.07282 | val 0.07719
  Epoch 021 - train 0.07510 | val 0.07709
  Regression -> MSE: 0.000203, MAE: 0.010072, R²: 0.0007
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.06856 | val 0.12884
  Epoch 020 - train 0.06997 | val 0.12906
  Epoch 021 - train 0.07009 | val 0.12908
  Regression -> MSE: 0.000557, MAE: 0.018166, R²: -0.0032
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07760 | val 0.08777
  Epoch 020 - train 0.07599 | val 0.08883
  Epoch 021 - train 0.07631 | val 0.08864
  Regression -> MSE: 0.000248, MAE: 0.012312, R²: -0.0086
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07367 | val 0.09679
  Epoch 020 - train 0.07319 | val 0.10015
  Epoch 021 - train 0.06960 | val 0.10039
  Regression -> MSE: 0.000638, MAE: 0.020039, R²: -0.0683
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07239 | val 0.08343
  Epoch 020 - train 0.06776 | val 0.08253
  Epoch 021 - train 0.07165 | val 0.08254
  Regression -> MSE: 0.000404, MAE: 0.016124, R²: -0.0527
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07280 | val 0.11309
  Epoch 020 - train 0.07419 | val 0.12948
  Epoch 021 - train 0.07507 | val 0.12935
  Regression -> MSE: 0.000243, MAE: 0.012112, R²: -0.0057
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.07068 | val 0.10094
  Epoch 020 - train 0.07058 | val 0.10359
  Epoch 021 - train 0.07040 | val 0.10379
  Regression -> MSE: 0.000312, MAE: 0.013693, R²: -0.0026
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07280 | val 0.08726
  Epoch 020 - train 0.07290 | val 0.09276
  Epoch 021 - train 0.07532 | val 0.09406
  Regression -> MSE: 0.000676, MAE: 0.019504, R²: 0.0013
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07353 | val 0.07124
  Epoch 020 - train 0.07469 | val 0.07752
  Epoch 021 - train 0.07326 | val 0.07924
  Regression -> MSE: 0.000138, MAE: 0.009048, R²: -0.0015
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.07433 | val 0.09384
  Epoch 020 - train 0.06718 | val 0.09303
  Epoch 021 - train 0.07084 | val 0.09283
  Regression -> MSE: 0.000225, MAE: 0.010788, R²: -0.0020
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07533 | val 0.14887
  Epoch 020 - train 0.07488 | val 0.15525
  Epoch 021 - train 0.07230 | val 0.15456
  Regression -> MSE: 0.000362, MAE: 0.016104, R²: 0.0005
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07904 | val 0.07422
  Epoch 020 - train 0.07414 | val 0.07424
  Epoch 021 - train 0.07274 | val 0.07436
  Regression -> MSE: 0.000108, MAE: 0.007999, R²: -0.0009
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07097 | val 0.11687
  Epoch 020 - train 0.07387 | val 0.11997
  Epoch 021 - train 0.07183 | val 0.12048
  Regression -> MSE: 0.000157, MAE: 0.009819, R²: -0.0049
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07756 | val 0.07266
  Epoch 020 - train 0.07473 | val 0.07317
  Epoch 021 - train 0.07402 | val 0.07322
  Regression -> MSE: 0.000276, MAE: 0.012924, R²: -0.0133
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06826 | val 0.10086
  Epoch 020 - train 0.06443 | val 0.09917
  Epoch 021 - train 0.06777 | val 0.09883
  Regression -> MSE: 0.000164, MAE: 0.009044, R²: -0.0960
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07450 | val 0.10146
  Epoch 020 - train 0.07490 | val 0.10347
  Epoch 021 - train 0.07348 | val 0.10375
  Regression -> MSE: 0.000246, MAE: 0.011194, R²: -0.0881
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07307 | val 0.09096
  Epoch 020 - train 0.07160 | val 0.09762
  Epoch 021 - train 0.07383 | val 0.09807
  Regression -> MSE: 0.000146, MAE: 0.008493, R²: -0.0164
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07345 | val 0.08181
  Epoch 020 - train 0.06963 | val 0.08223
  Epoch 021 - train 0.07188 | val 0.08222
  Regression -> MSE: 0.000181, MAE: 0.010328, R²: -0.0932
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07263 | val 0.08644
  Epoch 020 - train 0.07444 | val 0.08788
  Epoch 021 - train 0.07345 | val 0.08767
  Regression -> MSE: 0.000085, MAE: 0.007021, R²: 0.0036
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07589 | val 0.08793
  Epoch 020 - train 0.07695 | val 0.08680
  Epoch 021 - train 0.07166 | val 0.08679
  Regression -> MSE: 0.000212, MAE: 0.011098, R²: -0.0023
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06981 | val 0.06171
  Epoch 020 - train 0.07014 | val 0.06095
  Epoch 021 - train 0.06807 | val 0.06105
  Regression -> MSE: 0.000102, MAE: 0.008255, R²: -0.1077
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.08206 | val 0.05644
  Epoch 020 - train 0.07383 | val 0.05744
  Epoch 021 - train 0.08017 | val 0.05763
  Regression -> MSE: 0.000104, MAE: 0.008758, R²: -0.0045
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07730 | val 0.06959
  Epoch 020 - train 0.07807 | val 0.07086
  Epoch 021 - train 0.07410 | val 0.07094
  Regression -> MSE: 0.000236, MAE: 0.012724, R²: -0.0205
  Directional -> Accuracy: 0.6512, MCC: 0.2643, F1: 0.7541

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07273 | val 0.08158
  Epoch 020 - train 0.07031 | val 0.08080
  Epoch 021 - train 0.07051 | val 0.08080
  Regression -> MSE: 0.000175, MAE: 0.007880, R²: -0.0539
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08126 | val 0.06633
  Epoch 020 - train 0.07875 | val 0.06997
  Epoch 021 - train 0.07667 | val 0.07038
  Regression -> MSE: 0.000241, MAE: 0.012064, R²: -0.0179
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.06964 | val 0.11242
  Epoch 020 - train 0.07229 | val 0.12006
  Epoch 021 - train 0.07128 | val 0.12053
  Regression -> MSE: 0.000232, MAE: 0.009974, R²: -0.0070
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.08091 | val 0.09328
  Epoch 020 - train 0.07726 | val 0.11257
  Epoch 021 - train 0.07837 | val 0.11295
  Regression -> MSE: 0.000141, MAE: 0.008471, R²: -0.0420
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07772 | val 0.09111
  Epoch 020 - train 0.07430 | val 0.08955
  Epoch 021 - train 0.07763 | val 0.08954
  Regression -> MSE: 0.000188, MAE: 0.010489, R²: 0.0014
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06568 | val 0.08276
  Epoch 020 - train 0.06810 | val 0.08218
  Epoch 021 - train 0.06514 | val 0.08205
  Regression -> MSE: 0.000266, MAE: 0.010537, R²: -0.0143
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.06962 | val 0.06087
  Epoch 020 - train 0.07272 | val 0.06303
  Epoch 021 - train 0.07295 | val 0.06341
  Regression -> MSE: 0.000169, MAE: 0.010371, R²: -0.0153
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06907 | val 0.07405
  Epoch 020 - train 0.06916 | val 0.07658
  Epoch 021 - train 0.06523 | val 0.07648
  Regression -> MSE: 0.000184, MAE: 0.010482, R²: -0.0234
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07785 | val 0.07384
  Epoch 020 - train 0.07353 | val 0.07237
  Epoch 021 - train 0.07544 | val 0.07200
  Regression -> MSE: 0.000352, MAE: 0.011828, R²: -0.0279
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08726 | val 0.04894
  Epoch 020 - train 0.08076 | val 0.05107
  Epoch 021 - train 0.08473 | val 0.05115
  Regression -> MSE: 0.000128, MAE: 0.008509, R²: -0.2155
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07971 | val 0.10941
  Epoch 020 - train 0.08003 | val 0.11186
  Epoch 021 - train 0.07550 | val 0.11137
  Regression -> MSE: 0.000227, MAE: 0.011538, R²: -0.0381
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07212 | val 0.12365
  Epoch 020 - train 0.07565 | val 0.12872
  Epoch 021 - train 0.07103 | val 0.12863
  Regression -> MSE: 0.000086, MAE: 0.007262, R²: -0.1093
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07598 | val 0.05995
  Epoch 020 - train 0.07246 | val 0.06718
  Epoch 021 - train 0.06666 | val 0.06814
  Regression -> MSE: 0.000327, MAE: 0.014872, R²: -0.0636
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07885 | val 0.04492
  Epoch 020 - train 0.07461 | val 0.04575
  Epoch 021 - train 0.07144 | val 0.04603
  Regression -> MSE: 0.000247, MAE: 0.011552, R²: -0.0123
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.07241 | val 0.09194
  Epoch 020 - train 0.06933 | val 0.09220
  Epoch 021 - train 0.07088 | val 0.09214
  Regression -> MSE: 0.000083, MAE: 0.007037, R²: -0.0258
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07630 | val 0.08824
  Epoch 020 - train 0.07460 | val 0.08253
  Epoch 021 - train 0.07751 | val 0.08265
  Regression -> MSE: 0.000309, MAE: 0.014483, R²: -0.0067
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07229 | val 0.07930
  Epoch 020 - train 0.07020 | val 0.07944
  Epoch 021 - train 0.07549 | val 0.07966
  Regression -> MSE: 0.000099, MAE: 0.007187, R²: -0.0078
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.07968 | val 0.08281
  Epoch 020 - train 0.07390 | val 0.08352
  Epoch 021 - train 0.07622 | val 0.08358
  Regression -> MSE: 0.000172, MAE: 0.009798, R²: -0.0038
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07049 | val 0.08014
  Epoch 020 - train 0.06606 | val 0.08243
  Epoch 021 - train 0.06526 | val 0.08230
  Regression -> MSE: 0.000223, MAE: 0.011721, R²: -0.0004
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07037 | val 0.08893
  Epoch 020 - train 0.07494 | val 0.09340
  Epoch 021 - train 0.07312 | val 0.09312

[I 2026-02-24 04:27:56,971] Trial 173 finished with value: -0.011454927842510492 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 3.628896240954228e-05, 'weight_decay': 9.658450195069855e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.10115562180441404, 'early_stopping_min_delta': 0.009375946600561721}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.07333 | val 0.09944
  Epoch 021 - train 0.07447 | val 0.09959
  Regression -> MSE: 0.000249, MAE: 0.012469, R²: -0.0516
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12065 | val 0.17636
  Epoch 020 - train 0.11651 | val 0.17384
  Epoch 021 - train 0.11301 | val 0.17423
  Regression -> MSE: 0.000252, MAE: 0.012739, R²: -0.0187
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11360 | val 0.11656
  Epoch 020 - train 0.10759 | val 0.12419
  Epoch 021 - train 0.10750 | val 0.12385
  Regression -> MSE: 0.000691, MAE: 0.019468, R²: -0.0098
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11723 | val 0.20233
  Epoch 020 - train 0.11594 | val 0.19931
  Epoch 021 - train 0.11831 | val 0.19901
  Regression -> MSE: 0.000311, MAE: 0.014445, R²: -0.0011
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09795 | val 0.12017
  Epoch 020 - train 0.09821 | val 0.16719
  Epoch 021 - train 0.10072 | val 0.16693
  Regression -> MSE: 0.000351, MAE: 0.014595, R²: -0.0046
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11441 | val 0.15239
  Epoch 020 - train 0.11083 | val 0.16785
  Epoch 021 - train 0.11253 | val 0.16962
  Regression -> MSE: 0.000205, MAE: 0.010305, R²: -0.0052
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11079 | val 0.23155
  Epoch 020 - train 0.11041 | val 0.25947
  Epoch 021 - train 0.10731 | val 0.26147
  Regression -> MSE: 0.000566, MAE: 0.018277, R²: -0.0200
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12102 | val 0.15581
  Epoch 020 - train 0.11627 | val 0.15758
  Epoch 021 - train 0.11842 | val 0.15802
  Regression -> MSE: 0.000246, MAE: 0.012023, R²: -0.0010
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11055 | val 0.16327
  Epoch 020 - train 0.10590 | val 0.20247
  Epoch 021 - train 0.10671 | val 0.20612
  Regression -> MSE: 0.000615, MAE: 0.019590, R²: -0.0293
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11576 | val 0.15687
  Epoch 020 - train 0.10887 | val 0.15015
  Epoch 021 - train 0.10594 | val 0.14985
  Regression -> MSE: 0.000385, MAE: 0.016125, R²: -0.0044
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11160 | val 0.16951
  Epoch 020 - train 0.11272 | val 0.17048
  Epoch 021 - train 0.11386 | val 0.17008
  Regression -> MSE: 0.000241, MAE: 0.011826, R²: 0.0005
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10677 | val 0.19457
  Epoch 020 - train 0.10281 | val 0.20588
  Epoch 021 - train 0.10503 | val 0.20680
  Regression -> MSE: 0.000310, MAE: 0.013727, R²: 0.0043
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12379 | val 0.15965
  Epoch 020 - train 0.12183 | val 0.17215
  Epoch 021 - train 0.12068 | val 0.17137
  Regression -> MSE: 0.000685, MAE: 0.019747, R²: -0.0110
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11589 | val 0.14296
  Epoch 020 - train 0.11336 | val 0.17417
  Epoch 021 - train 0.10663 | val 0.17715
  Regression -> MSE: 0.000138, MAE: 0.009096, R²: 0.0005
  Directional -> Accuracy: 0.4884, MCC: -0.0373, F1: 0.4211

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10777 | val 0.15963
  Epoch 020 - train 0.10602 | val 0.16222
  Epoch 021 - train 0.10303 | val 0.16202
  Regression -> MSE: 0.000225, MAE: 0.010755, R²: -0.0022
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11565 | val 0.25970
  Epoch 020 - train 0.11316 | val 0.28681
  Epoch 021 - train 0.11117 | val 0.28264
  Regression -> MSE: 0.000369, MAE: 0.015948, R²: -0.0185
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12265 | val 0.13626
  Epoch 020 - train 0.11960 | val 0.14101
  Epoch 021 - train 0.11763 | val 0.14152
  Regression -> MSE: 0.000112, MAE: 0.007982, R²: -0.0420
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11618 | val 0.26853
  Epoch 020 - train 0.11373 | val 0.32280
  Epoch 021 - train 0.11199 | val 0.32595
  Regression -> MSE: 0.000155, MAE: 0.009596, R²: 0.0026
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12557 | val 0.15317
  Epoch 020 - train 0.12104 | val 0.15229
  Epoch 021 - train 0.12011 | val 0.15183
  Regression -> MSE: 0.000294, MAE: 0.013965, R²: -0.0822
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10584 | val 0.15753
  Epoch 020 - train 0.10064 | val 0.15414
  Epoch 030 - train 0.09872 | val 0.15415
  Regression -> MSE: 0.000259, MAE: 0.012662, R²: -0.7336
  Directional -> Accuracy: 0.4000, MCC: -0.1483, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11881 | val 0.19223
  Epoch 020 - train 0.11502 | val 0.21780
  Epoch 021 - train 0.11293 | val 0.21879
  Regression -> MSE: 0.000228, MAE: 0.010926, R²: -0.0083
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11609 | val 0.15911
  Epoch 020 - train 0.11347 | val 0.18815
  Epoch 021 - train 0.11541 | val 0.18853
  Regression -> MSE: 0.000144, MAE: 0.008425, R²: -0.0079
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10925 | val 0.15606
  Epoch 020 - train 0.10741 | val 0.16096
  Epoch 021 - train 0.10843 | val 0.16073
  Regression -> MSE: 0.000170, MAE: 0.010248, R²: -0.0301
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12526 | val 0.14834
  Epoch 020 - train 0.11685 | val 0.15611
  Epoch 021 - train 0.11870 | val 0.15707
  Regression -> MSE: 0.000090, MAE: 0.007285, R²: -0.0544
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11231 | val 0.16611
  Epoch 020 - train 0.11229 | val 0.18094
  Epoch 021 - train 0.11354 | val 0.17937
  Regression -> MSE: 0.000212, MAE: 0.011061, R²: -0.0023
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11458 | val 0.11033
  Epoch 020 - train 0.10960 | val 0.10815
  Epoch 021 - train 0.10900 | val 0.10814
  Regression -> MSE: 0.000103, MAE: 0.008306, R²: -0.1206
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12411 | val 0.10810
  Epoch 020 - train 0.11882 | val 0.10116
  Epoch 030 - train 0.11538 | val 0.10409
  Regression -> MSE: 0.000116, MAE: 0.009199, R²: -0.1296
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12292 | val 0.13957
  Epoch 020 - train 0.11907 | val 0.19328
  Epoch 021 - train 0.12457 | val 0.19108
  Regression -> MSE: 0.000238, MAE: 0.012803, R²: -0.0303
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11640 | val 0.14514
  Epoch 020 - train 0.11227 | val 0.15191
  Epoch 021 - train 0.11134 | val 0.15307
  Regression -> MSE: 0.000188, MAE: 0.008123, R²: -0.1297
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12557 | val 0.10625
  Epoch 020 - train 0.12258 | val 0.11069
  Epoch 021 - train 0.12174 | val 0.11123
  Regression -> MSE: 0.000239, MAE: 0.011922, R²: -0.0092
  Directional -> Accuracy: 0.5854, MCC: 0.2437, F1: 0.7213

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12130 | val 0.19992
  Epoch 020 - train 0.11457 | val 0.23028
  Epoch 021 - train 0.11896 | val 0.23106
  Regression -> MSE: 0.000231, MAE: 0.009874, R²: -0.0017
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11908 | val 0.14774
  Epoch 020 - train 0.11648 | val 0.15830
  Epoch 021 - train 0.11832 | val 0.15881
  Regression -> MSE: 0.000135, MAE: 0.008199, R²: -0.0006
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11766 | val 0.16607
  Epoch 020 - train 0.11117 | val 0.17554
  Epoch 021 - train 0.11422 | val 0.17577
  Regression -> MSE: 0.000196, MAE: 0.010602, R²: -0.0436
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10306 | val 0.14484
  Epoch 020 - train 0.09837 | val 0.15226
  Epoch 021 - train 0.10069 | val 0.15189
  Regression -> MSE: 0.000267, MAE: 0.010553, R²: -0.0198
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11149 | val 0.10437
  Epoch 020 - train 0.10554 | val 0.10915
  Epoch 021 - train 0.10889 | val 0.11060
  Regression -> MSE: 0.000167, MAE: 0.010363, R²: -0.0040
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10763 | val 0.13415
  Epoch 020 - train 0.10598 | val 0.13458
  Epoch 021 - train 0.10292 | val 0.13544
  Regression -> MSE: 0.000189, MAE: 0.010644, R²: -0.0485
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10861 | val 0.12387
  Epoch 020 - train 0.10818 | val 0.12772
  Epoch 021 - train 0.10800 | val 0.12811
  Regression -> MSE: 0.000343, MAE: 0.011956, R²: -0.0022
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12455 | val 0.08317
  Epoch 020 - train 0.12116 | val 0.09366
  Epoch 021 - train 0.12121 | val 0.09449
  Regression -> MSE: 0.000113, MAE: 0.008333, R²: -0.0723
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11748 | val 0.20385
  Epoch 020 - train 0.11229 | val 0.24717
  Epoch 021 - train 0.11314 | val 0.24609
  Regression -> MSE: 0.000219, MAE: 0.011281, R²: -0.0004
  Directional -> Accuracy: 0.5789, MCC: 0.1496, F1: 0.4545

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11432 | val 0.22578
  Epoch 020 - train 0.11016 | val 0.31798
  Epoch 021 - train 0.11027 | val 0.32213
  Regression -> MSE: 0.000088, MAE: 0.007349, R²: -0.1346
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11470 | val 0.10496
  Epoch 020 - train 0.10780 | val 0.09869
  Epoch 021 - train 0.11059 | val 0.09834
  Regression -> MSE: 0.000330, MAE: 0.014973, R²: -0.0731
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12131 | val 0.07663
  Epoch 020 - train 0.11682 | val 0.08112
  Epoch 021 - train 0.11955 | val 0.08193
  Regression -> MSE: 0.000245, MAE: 0.011563, R²: -0.0059
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11148 | val 0.16501
  Epoch 020 - train 0.10887 | val 0.16841
  Epoch 021 - train 0.10988 | val 0.16864
  Regression -> MSE: 0.000081, MAE: 0.007061, R²: -0.0010
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12005 | val 0.15167
  Epoch 020 - train 0.11638 | val 0.23483
  Epoch 030 - train 0.11286 | val 0.26861
  Regression -> MSE: 0.000321, MAE: 0.014693, R²: -0.0453
  Directional -> Accuracy: 0.4255, MCC: -0.1882, F1: 0.1290

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11476 | val 0.14207
  Epoch 020 - train 0.11101 | val 0.14221
  Epoch 021 - train 0.11122 | val 0.14162
  Regression -> MSE: 0.000100, MAE: 0.007124, R²: -0.0160
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.12884 | val 0.14980
  Epoch 020 - train 0.12475 | val 0.16790
  Epoch 021 - train 0.11989 | val 0.16922
  Regression -> MSE: 0.000173, MAE: 0.009922, R²: -0.0067
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11227 | val 0.14087
  Epoch 020 - train 0.10931 | val 0.16243
  Epoch 021 - train 0.11057 | val 0.16278
  Regression -> MSE: 0.000226, MAE: 0.011815, R²: -0.0152
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11530 | val 0.14821
  Epoch 020 - train 0.11314 | val 0.15252
  Epoch 021 - train 0.11225 | val 0.15260

[I 2026-02-24 04:29:59,552] Trial 174 finished with value: -0.011535154470105582 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 7.406759354980083e-05, 'weight_decay': 1.2955930791876907e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.1870115096259283, 'early_stopping_min_delta': 0.009940939231812483}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.11443 | val 0.19414
  Epoch 021 - train 0.11976 | val 0.19468
  Regression -> MSE: 0.000245, MAE: 0.012361, R²: -0.0329
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09354 | val 0.12623
  Epoch 020 - train 0.09546 | val 0.13022
  Epoch 021 - train 0.09508 | val 0.13009
  Regression -> MSE: 0.000248, MAE: 0.012528, R²: -0.0002
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09680 | val 0.08746
  Epoch 020 - train 0.09534 | val 0.09381
  Epoch 021 - train 0.09287 | val 0.09354
  Regression -> MSE: 0.000715, MAE: 0.019888, R²: -0.0447
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09556 | val 0.15193
  Epoch 020 - train 0.09598 | val 0.14896
  Epoch 021 - train 0.09352 | val 0.14841
  Regression -> MSE: 0.000311, MAE: 0.014459, R²: -0.0017
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07747 | val 0.14398
  Epoch 020 - train 0.08136 | val 0.15260
  Epoch 021 - train 0.07764 | val 0.15771
  Regression -> MSE: 0.000370, MAE: 0.014902, R²: -0.0588
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09456 | val 0.09486
  Epoch 020 - train 0.09620 | val 0.10133
  Epoch 021 - train 0.09437 | val 0.10332
  Regression -> MSE: 0.000204, MAE: 0.010068, R²: -0.0008
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09384 | val 0.17441
  Epoch 020 - train 0.08424 | val 0.17496
  Epoch 021 - train 0.08889 | val 0.17412
  Regression -> MSE: 0.000575, MAE: 0.018472, R²: -0.0352
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09407 | val 0.11452
  Epoch 020 - train 0.09343 | val 0.11521
  Epoch 021 - train 0.09479 | val 0.11527
  Regression -> MSE: 0.000247, MAE: 0.012279, R²: -0.0081
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09188 | val 0.11220
  Epoch 020 - train 0.09192 | val 0.12735
  Epoch 021 - train 0.09206 | val 0.12836
  Regression -> MSE: 0.000604, MAE: 0.019335, R²: -0.0114
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09249 | val 0.11593
  Epoch 020 - train 0.08742 | val 0.11149
  Epoch 021 - train 0.09123 | val 0.11126
  Regression -> MSE: 0.000386, MAE: 0.016077, R²: -0.0072
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09713 | val 0.12485
  Epoch 020 - train 0.09363 | val 0.12634
  Epoch 021 - train 0.09257 | val 0.12630
  Regression -> MSE: 0.000243, MAE: 0.011666, R²: -0.0085
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08929 | val 0.13341
  Epoch 020 - train 0.08789 | val 0.13606
  Epoch 021 - train 0.08490 | val 0.13629
  Regression -> MSE: 0.000319, MAE: 0.013594, R²: -0.0262
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09999 | val 0.10999
  Epoch 020 - train 0.09662 | val 0.11232
  Epoch 021 - train 0.09511 | val 0.11254
  Regression -> MSE: 0.000681, MAE: 0.019654, R²: -0.0059
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09244 | val 0.11077
  Epoch 020 - train 0.09171 | val 0.12594
  Epoch 021 - train 0.09147 | val 0.12511
  Regression -> MSE: 0.000138, MAE: 0.009027, R²: -0.0004
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09090 | val 0.12053
  Epoch 020 - train 0.08632 | val 0.12130
  Epoch 021 - train 0.08736 | val 0.12128
  Regression -> MSE: 0.000234, MAE: 0.011034, R²: -0.0390
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09515 | val 0.18979
  Epoch 020 - train 0.09118 | val 0.21091
  Epoch 021 - train 0.09394 | val 0.21106
  Regression -> MSE: 0.000363, MAE: 0.016014, R²: -0.0028
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10097 | val 0.10124
  Epoch 020 - train 0.09897 | val 0.10124
  Epoch 021 - train 0.09758 | val 0.10115
  Regression -> MSE: 0.000109, MAE: 0.007939, R²: -0.0097
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09526 | val 0.15592
  Epoch 020 - train 0.09183 | val 0.16178
  Epoch 021 - train 0.09154 | val 0.16217
  Regression -> MSE: 0.000158, MAE: 0.009539, R²: -0.0113
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09758 | val 0.12598
  Epoch 020 - train 0.09577 | val 0.12468
  Epoch 021 - train 0.09613 | val 0.12346
  Regression -> MSE: 0.000279, MAE: 0.013351, R²: -0.0237
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08366 | val 0.12304
  Epoch 020 - train 0.08245 | val 0.12323
  Epoch 021 - train 0.08628 | val 0.12278
  Regression -> MSE: 0.000153, MAE: 0.008743, R²: -0.0241
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09540 | val 0.13026
  Epoch 020 - train 0.09204 | val 0.12513
  Epoch 021 - train 0.09382 | val 0.12543
  Regression -> MSE: 0.000243, MAE: 0.011174, R²: -0.0754
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09723 | val 0.11707
  Epoch 020 - train 0.10397 | val 0.13419
  Epoch 021 - train 0.09597 | val 0.13304
  Regression -> MSE: 0.000143, MAE: 0.008276, R²: 0.0037
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09178 | val 0.11137
  Epoch 020 - train 0.09238 | val 0.11306
  Epoch 021 - train 0.09037 | val 0.11348
  Regression -> MSE: 0.000165, MAE: 0.010359, R²: -0.0008
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09717 | val 0.11027
  Epoch 020 - train 0.09610 | val 0.10990
  Epoch 021 - train 0.09618 | val 0.10931
  Regression -> MSE: 0.000087, MAE: 0.007156, R²: -0.0233
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09298 | val 0.11757
  Epoch 020 - train 0.09264 | val 0.11782
  Epoch 021 - train 0.09115 | val 0.11739
  Regression -> MSE: 0.000214, MAE: 0.011041, R²: -0.0122
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09048 | val 0.08269
  Epoch 020 - train 0.08332 | val 0.08360
  Epoch 021 - train 0.08706 | val 0.08369
  Regression -> MSE: 0.000099, MAE: 0.008204, R²: -0.0803
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09887 | val 0.07874
  Epoch 020 - train 0.09680 | val 0.09185
  Epoch 021 - train 0.09465 | val 0.09313
  Regression -> MSE: 0.000110, MAE: 0.009045, R²: -0.0698
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09701 | val 0.09049
  Epoch 020 - train 0.08807 | val 0.09964
  Epoch 021 - train 0.09638 | val 0.10019
  Regression -> MSE: 0.000232, MAE: 0.012554, R²: -0.0014
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09592 | val 0.11215
  Epoch 020 - train 0.09423 | val 0.10918
  Epoch 021 - train 0.09176 | val 0.10922
  Regression -> MSE: 0.000179, MAE: 0.007936, R²: -0.0728
  Directional -> Accuracy: 0.4912, MCC: -0.0199, F1: 0.5246

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09892 | val 0.08391
  Epoch 020 - train 0.09753 | val 0.08433
  Epoch 021 - train 0.10269 | val 0.08439
  Regression -> MSE: 0.000240, MAE: 0.012027, R²: -0.0140
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09639 | val 0.14483
  Epoch 020 - train 0.09552 | val 0.14816
  Epoch 021 - train 0.09652 | val 0.14786
  Regression -> MSE: 0.000230, MAE: 0.009868, R²: 0.0009
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09804 | val 0.11560
  Epoch 020 - train 0.09294 | val 0.12660
  Epoch 021 - train 0.09927 | val 0.12682
  Regression -> MSE: 0.000136, MAE: 0.008266, R²: -0.0088
  Directional -> Accuracy: 0.5814, MCC: 0.1627, F1: 0.7000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09849 | val 0.12257
  Epoch 020 - train 0.09960 | val 0.12795
  Epoch 021 - train 0.09908 | val 0.12785
  Regression -> MSE: 0.000197, MAE: 0.010588, R²: -0.0450
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08410 | val 0.10518
  Epoch 020 - train 0.08383 | val 0.10174
  Epoch 021 - train 0.08035 | val 0.10179
  Regression -> MSE: 0.000269, MAE: 0.010588, R²: -0.0260
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08824 | val 0.07944
  Epoch 020 - train 0.08630 | val 0.08091
  Epoch 021 - train 0.09411 | val 0.08115
  Regression -> MSE: 0.000168, MAE: 0.010366, R²: -0.0059
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09285 | val 0.09893
  Epoch 020 - train 0.08619 | val 0.10250
  Epoch 021 - train 0.09289 | val 0.10186
  Regression -> MSE: 0.000186, MAE: 0.010570, R²: -0.0356
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09316 | val 0.09292
  Epoch 020 - train 0.08733 | val 0.09612
  Epoch 021 - train 0.08686 | val 0.09641
  Regression -> MSE: 0.000348, MAE: 0.011762, R²: -0.0154
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10573 | val 0.06274
  Epoch 020 - train 0.09929 | val 0.06540
  Epoch 021 - train 0.10011 | val 0.06584
  Regression -> MSE: 0.000116, MAE: 0.008340, R²: -0.1024
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09430 | val 0.12825
  Epoch 020 - train 0.09107 | val 0.13029
  Epoch 021 - train 0.09428 | val 0.12993
  Regression -> MSE: 0.000221, MAE: 0.011359, R²: -0.0104
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09250 | val 0.15893
  Epoch 020 - train 0.08618 | val 0.16925
  Epoch 021 - train 0.08797 | val 0.16981
  Regression -> MSE: 0.000089, MAE: 0.007373, R²: -0.1424
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09867 | val 0.07818
  Epoch 020 - train 0.08764 | val 0.08353
  Epoch 021 - train 0.09253 | val 0.08399
  Regression -> MSE: 0.000326, MAE: 0.014813, R²: -0.0591
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09543 | val 0.06173
  Epoch 020 - train 0.09228 | val 0.06542
  Epoch 021 - train 0.09230 | val 0.06640
  Regression -> MSE: 0.000258, MAE: 0.011478, R²: -0.0572
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09096 | val 0.10876
  Epoch 020 - train 0.09331 | val 0.11355
  Epoch 021 - train 0.08182 | val 0.11406
  Regression -> MSE: 0.000081, MAE: 0.007100, R²: -0.0024
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10079 | val 0.11328
  Epoch 020 - train 0.10115 | val 0.13196
  Epoch 021 - train 0.08796 | val 0.13429
  Regression -> MSE: 0.000308, MAE: 0.014511, R²: -0.0026
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10207 | val 0.10409
  Epoch 020 - train 0.08963 | val 0.10269
  Epoch 021 - train 0.08472 | val 0.10260
  Regression -> MSE: 0.000099, MAE: 0.007174, R²: -0.0085
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10234 | val 0.10973
  Epoch 020 - train 0.10484 | val 0.10837
  Epoch 021 - train 0.10193 | val 0.10913
  Regression -> MSE: 0.000174, MAE: 0.010050, R²: -0.0114
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08753 | val 0.11056
  Epoch 020 - train 0.08632 | val 0.11156
  Epoch 021 - train 0.08725 | val 0.11200
  Regression -> MSE: 0.000224, MAE: 0.011748, R²: -0.0031
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09413 | val 0.10325
  Epoch 020 - train 0.08770 | val 0.10570
  Epoch 021 - train 0.09150 | val 0.10571

[I 2026-02-24 04:32:51,480] Trial 175 finished with value: -0.011431002612829788 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 5.119111928085673e-05, 'weight_decay': 1.162444508240809e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.13645857855142587, 'early_stopping_min_delta': 0.009544718808686481}. Best is trial 44 with value: -0.011362814469631832.

  Regression -> MSE: 0.000241, MAE: 0.012331, R²: -0.0153
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14838 | val 0.20423
  Epoch 020 - train 0.14796 | val 0.21274
  Epoch 026 - train 0.15804 | val 0.21436
  Regression -> MSE: 0.000260, MAE: 0.013040, R²: -0.0508
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14356 | val 0.14457
  Epoch 020 - train 0.14899 | val 0.14335
  Epoch 030 - train 0.14967 | val 0.16366
  Regression -> MSE: 0.000637, MAE: 0.018593, R²: 0.0695
  Directional -> Accuracy: 0.6739, MCC: 0.3261, F1: 0.7458

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16101 | val 0.24601
  Epoch 020 - train 0.15972 | val 0.25198
  Epoch 021 - train 0.15000 | val 0.25273
  Regression -> MSE: 0.000310, MAE: 0.014402, R²: 0.0016
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12813 | val 0.19054
  Epoch 020 - train 0.12646 | val 0.18909
  Epoch 021 - train 0.12646 | val 0.19152
  Regression -> MSE: 0.000349, MAE: 0.014580, R²: 0.0003
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15214 | val 0.15121
  Epoch 020 - train 0.14791 | val 0.18842
  Epoch 021 - train 0.14931 | val 0.18737
  Regression -> MSE: 0.000208, MAE: 0.010118, R²: -0.0194
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15767 | val 0.29037
  Epoch 020 - train 0.13959 | val 0.35324
  Epoch 021 - train 0.13441 | val 0.35747
  Regression -> MSE: 0.000554, MAE: 0.018178, R²: 0.0021
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15726 | val 0.19199
  Epoch 020 - train 0.15785 | val 0.19329
  Epoch 021 - train 0.14941 | val 0.19325
  Regression -> MSE: 0.000246, MAE: 0.011918, R²: -0.0017
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15503 | val 0.20255
  Epoch 020 - train 0.13525 | val 0.23414
  Epoch 021 - train 0.14155 | val 0.23699
  Regression -> MSE: 0.000616, MAE: 0.019604, R²: -0.0312
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15020 | val 0.18769
  Epoch 020 - train 0.14075 | val 0.19271
  Epoch 021 - train 0.13138 | val 0.19548
  Regression -> MSE: 0.000390, MAE: 0.015997, R²: -0.0164
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15296 | val 0.20146
  Epoch 020 - train 0.14768 | val 0.20267
  Epoch 021 - train 0.15123 | val 0.20307
  Regression -> MSE: 0.000242, MAE: 0.011925, R²: -0.0011
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15861 | val 0.27258
  Epoch 020 - train 0.13886 | val 0.32893
  Epoch 021 - train 0.14943 | val 0.32759
  Regression -> MSE: 0.000311, MAE: 0.013828, R²: -0.0017
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15163 | val 0.20028
  Epoch 020 - train 0.15469 | val 0.19943
  Epoch 021 - train 0.14579 | val 0.19935
  Regression -> MSE: 0.000678, MAE: 0.019487, R²: -0.0005
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14563 | val 0.17231
  Epoch 020 - train 0.14001 | val 0.20371
  Epoch 021 - train 0.14956 | val 0.20715
  Regression -> MSE: 0.000138, MAE: 0.009138, R²: -0.0003
  Directional -> Accuracy: 0.5349, MCC: 0.2232, F1: 0.6429

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14169 | val 0.19143
  Epoch 020 - train 0.13531 | val 0.19606
  Epoch 021 - train 0.13250 | val 0.19719
  Regression -> MSE: 0.000226, MAE: 0.010714, R²: -0.0049
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15507 | val 0.32554
  Epoch 020 - train 0.15697 | val 0.36861
  Epoch 021 - train 0.14741 | val 0.37387
  Regression -> MSE: 0.000375, MAE: 0.015957, R²: -0.0346
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.17210 | val 0.16829
  Epoch 020 - train 0.15296 | val 0.16909
  Epoch 021 - train 0.15616 | val 0.16790
  Regression -> MSE: 0.000108, MAE: 0.008063, R²: -0.0014
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14231 | val 0.32941
  Epoch 020 - train 0.14584 | val 0.40134
  Epoch 021 - train 0.14828 | val 0.40635
  Regression -> MSE: 0.000155, MAE: 0.009559, R²: 0.0027
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15453 | val 0.16879
  Epoch 020 - train 0.15284 | val 0.17047
  Epoch 021 - train 0.15348 | val 0.17183
  Regression -> MSE: 0.000273, MAE: 0.013053, R²: -0.0017
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13991 | val 0.20231
  Epoch 020 - train 0.13385 | val 0.19825
  Epoch 030 - train 0.12592 | val 0.19775
  Regression -> MSE: 0.000275, MAE: 0.012999, R²: -0.8398
  Directional -> Accuracy: 0.4154, MCC: -0.0306, F1: 0.0500

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15546 | val 0.22220
  Epoch 020 - train 0.15196 | val 0.23103
  Epoch 021 - train 0.14406 | val 0.23170
  Regression -> MSE: 0.000229, MAE: 0.010852, R²: -0.0105
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16302 | val 0.19287
  Epoch 020 - train 0.15545 | val 0.18935
  Epoch 021 - train 0.15566 | val 0.18936
  Regression -> MSE: 0.000143, MAE: 0.008288, R²: 0.0022
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14396 | val 0.18048
  Epoch 020 - train 0.13842 | val 0.18522
  Epoch 021 - train 0.14954 | val 0.18480
  Regression -> MSE: 0.000176, MAE: 0.010274, R²: -0.0669
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15997 | val 0.18314
  Epoch 020 - train 0.15436 | val 0.18059
  Epoch 021 - train 0.15510 | val 0.18082
  Regression -> MSE: 0.000093, MAE: 0.007456, R²: -0.0954
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14935 | val 0.19484
  Epoch 020 - train 0.15236 | val 0.19989
  Epoch 021 - train 0.14415 | val 0.20045
  Regression -> MSE: 0.000212, MAE: 0.011060, R²: -0.0029
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13500 | val 0.13158
  Epoch 020 - train 0.13368 | val 0.12948
  Epoch 021 - train 0.12909 | val 0.12959
  Regression -> MSE: 0.000097, MAE: 0.008148, R²: -0.0513
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.15662 | val 0.11962
  Epoch 020 - train 0.15652 | val 0.12090
  Epoch 021 - train 0.16948 | val 0.12207
  Regression -> MSE: 0.000107, MAE: 0.008897, R²: -0.0329
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15957 | val 0.14633
  Epoch 020 - train 0.15199 | val 0.15514
  Epoch 021 - train 0.15095 | val 0.15481
  Regression -> MSE: 0.000240, MAE: 0.012846, R²: -0.0376
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.16188 | val 0.17725
  Epoch 020 - train 0.15443 | val 0.17870
  Epoch 021 - train 0.14944 | val 0.17933
  Regression -> MSE: 0.000174, MAE: 0.007888, R²: -0.0429
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16107 | val 0.13137
  Epoch 020 - train 0.15324 | val 0.15694
  Epoch 021 - train 0.14836 | val 0.15911
  Regression -> MSE: 0.000238, MAE: 0.011912, R²: -0.0042
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16325 | val 0.24520
  Epoch 020 - train 0.15948 | val 0.25419
  Epoch 021 - train 0.15324 | val 0.25510
  Regression -> MSE: 0.000232, MAE: 0.009979, R²: -0.0089
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15694 | val 0.20446
  Epoch 020 - train 0.15292 | val 0.21586
  Epoch 021 - train 0.15370 | val 0.21703
  Regression -> MSE: 0.000143, MAE: 0.008614, R²: -0.0597
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15838 | val 0.20075
  Epoch 020 - train 0.15716 | val 0.20350
  Epoch 021 - train 0.15312 | val 0.20387
  Regression -> MSE: 0.000188, MAE: 0.010500, R²: 0.0012
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14272 | val 0.16742
  Epoch 020 - train 0.13473 | val 0.17707
  Epoch 026 - train 0.13101 | val 0.17662
  Regression -> MSE: 0.000284, MAE: 0.011212, R²: -0.0843
  Directional -> Accuracy: 0.5205, MCC: 0.0894, F1: 0.4615

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15737 | val 0.13626
  Epoch 020 - train 0.13947 | val 0.13230
  Epoch 030 - train 0.13512 | val 0.16998
  Regression -> MSE: 0.000164, MAE: 0.010373, R²: 0.0159
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13965 | val 0.16130
  Epoch 020 - train 0.13508 | val 0.17322
  Epoch 021 - train 0.13323 | val 0.17394
  Regression -> MSE: 0.000180, MAE: 0.010319, R²: -0.0019
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14343 | val 0.14602
  Epoch 020 - train 0.14875 | val 0.15444
  Epoch 021 - train 0.13677 | val 0.15302
  Regression -> MSE: 0.000347, MAE: 0.011740, R²: -0.0125
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16153 | val 0.10004
  Epoch 020 - train 0.16190 | val 0.10512
  Epoch 021 - train 0.16157 | val 0.10502
  Regression -> MSE: 0.000128, MAE: 0.008513, R²: -0.2140
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15050 | val 0.23206
  Epoch 020 - train 0.14655 | val 0.24228
  Epoch 021 - train 0.15025 | val 0.24129
  Regression -> MSE: 0.000219, MAE: 0.011314, R²: -0.0014
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15576 | val 0.26183
  Epoch 020 - train 0.15369 | val 0.27645
  Epoch 021 - train 0.14113 | val 0.27724
  Regression -> MSE: 0.000100, MAE: 0.007802, R²: -0.2864
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14902 | val 0.11481
  Epoch 020 - train 0.14830 | val 0.11701
  Epoch 021 - train 0.14941 | val 0.11723
  Regression -> MSE: 0.000309, MAE: 0.013829, R²: -0.0044
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.16575 | val 0.09392
  Epoch 020 - train 0.15038 | val 0.10152
  Epoch 021 - train 0.15516 | val 0.10237
  Regression -> MSE: 0.000245, MAE: 0.011580, R²: -0.0045
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14271 | val 0.20105
  Epoch 020 - train 0.14399 | val 0.19703
  Epoch 021 - train 0.14175 | val 0.19540
  Regression -> MSE: 0.000085, MAE: 0.007057, R²: -0.0495
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.15421 | val 0.18790
  Epoch 020 - train 0.14706 | val 0.26235
  Epoch 021 - train 0.15564 | val 0.26356
  Regression -> MSE: 0.000307, MAE: 0.014499, R²: -0.0005
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14542 | val 0.17759
  Epoch 020 - train 0.14834 | val 0.17360
  Epoch 021 - train 0.13567 | val 0.17332
  Regression -> MSE: 0.000100, MAE: 0.007113, R²: -0.0214
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16423 | val 0.18187
  Epoch 020 - train 0.15489 | val 0.18841
  Epoch 021 - train 0.17247 | val 0.19017
  Regression -> MSE: 0.000172, MAE: 0.009585, R²: -0.0008
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13526 | val 0.18071
  Epoch 020 - train 0.13965 | val 0.19475
  Epoch 021 - train 0.13862 | val 0.19340
  Regression -> MSE: 0.000227, MAE: 0.011769, R²: -0.0165
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14590 | val 0.17232
  Epoch 020 - train 0.14639 | val 0.17788
  Epoch 021 - train 0.14034 | val 0.17814
  Regression -> MSE: 0.000097, MAE: 0.007973, R²: -0.0527
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429


[I 2026-02-24 04:35:47,059] Trial 176 finished with value: -0.01148467741191819 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 8.468709802330677e-05, 'weight_decay': 1.150121723038145e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2373453224672601, 'early_stopping_min_delta': 0.009861472431274443}. Best is trial 44 with value: -0.011362814469631832.

Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12410 | val 0.18996
  Epoch 020 - train 0.11235 | val 0.17624
  Epoch 021 - train 0.11210 | val 0.17515
  Regression -> MSE: 0.000255, MAE: 0.012820, R²: -0.0313
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11830 | val 0.13838
  Epoch 020 - train 0.10673 | val 0.13977
  Epoch 021 - train 0.11628 | val 0.14030
  Regression -> MSE: 0.000709, MAE: 0.019826, R²: -0.0355
  Directional -> Accuracy: 0.4130, MCC: -0.1700, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12469 | val 0.21030
  Epoch 020 - train 0.11858 | val 0.20806
  Epoch 021 - train 0.12254 | val 0.20742
  Regression -> MSE: 0.000310, MAE: 0.014376, R²: 0.0001
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10714 | val 0.13776
  Epoch 020 - train 0.09662 | val 0.14286
  Epoch 021 - train 0.09968 | val 0.14380
  Regression -> MSE: 0.000353, MAE: 0.014736, R²: -0.0119
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11959 | val 0.14009
  Epoch 020 - train 0.12024 | val 0.14733
  Epoch 021 - train 0.11919 | val 0.14782
  Regression -> MSE: 0.000204, MAE: 0.010219, R²: -0.0031
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11856 | val 0.28668
  Epoch 020 - train 0.10686 | val 0.30206
  Epoch 021 - train 0.10482 | val 0.30793
  Regression -> MSE: 0.000560, MAE: 0.018179, R²: -0.0097
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12725 | val 0.18234
  Epoch 020 - train 0.11789 | val 0.18031
  Epoch 021 - train 0.11965 | val 0.17943
  Regression -> MSE: 0.000247, MAE: 0.011924, R²: -0.0044
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11803 | val 0.26957
  Epoch 020 - train 0.10887 | val 0.28271
  Epoch 021 - train 0.10932 | val 0.28285
  Regression -> MSE: 0.000632, MAE: 0.019902, R²: -0.0572
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11989 | val 0.17242
  Epoch 020 - train 0.11424 | val 0.17448
  Epoch 021 - train 0.11219 | val 0.17434
  Regression -> MSE: 0.000381, MAE: 0.016045, R²: 0.0073
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12086 | val 0.17463
  Epoch 020 - train 0.11347 | val 0.17573
  Epoch 021 - train 0.11585 | val 0.17598
  Regression -> MSE: 0.000242, MAE: 0.011985, R²: -0.0017
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11536 | val 0.25838
  Epoch 020 - train 0.10586 | val 0.25484
  Epoch 021 - train 0.10969 | val 0.25430
  Regression -> MSE: 0.000308, MAE: 0.013592, R²: 0.0092
  Directional -> Accuracy: 0.6200, MCC: 0.2766, F1: 0.3448

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12732 | val 0.17198
  Epoch 020 - train 0.12769 | val 0.17609
  Epoch 021 - train 0.12290 | val 0.17661
  Regression -> MSE: 0.000676, MAE: 0.019417, R²: 0.0014
  Directional -> Accuracy: 0.5517, MCC: 0.1843, F1: 0.2353

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12819 | val 0.30565
  Epoch 020 - train 0.11283 | val 0.31737
  Epoch 021 - train 0.11730 | val 0.32133
  Regression -> MSE: 0.000140, MAE: 0.009239, R²: -0.0108
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11280 | val 0.21594
  Epoch 020 - train 0.10193 | val 0.23099
  Epoch 021 - train 0.10569 | val 0.23274
  Regression -> MSE: 0.000226, MAE: 0.010673, R²: -0.0032
  Directional -> Accuracy: 0.5410, MCC: 0.0995, F1: 0.4167

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12035 | val 0.26955
  Epoch 020 - train 0.11640 | val 0.26833
  Epoch 021 - train 0.11781 | val 0.26758
  Regression -> MSE: 0.000365, MAE: 0.015993, R²: -0.0067
  Directional -> Accuracy: 0.5000, MCC: -0.0120, F1: 0.4348

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12745 | val 0.16276
  Epoch 020 - train 0.12012 | val 0.15843
  Epoch 021 - train 0.12556 | val 0.15944
  Regression -> MSE: 0.000110, MAE: 0.008198, R²: -0.0183
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11672 | val 0.26304
  Epoch 020 - train 0.11618 | val 0.27602
  Epoch 021 - train 0.11371 | val 0.27876
  Regression -> MSE: 0.000153, MAE: 0.009607, R²: 0.0160
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12381 | val 0.16039
  Epoch 020 - train 0.12027 | val 0.17007
  Epoch 021 - train 0.11571 | val 0.16995
  Regression -> MSE: 0.000274, MAE: 0.012998, R²: -0.0084
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10954 | val 0.17056
  Epoch 020 - train 0.10024 | val 0.16899
  Epoch 021 - train 0.10391 | val 0.16941
  Regression -> MSE: 0.000155, MAE: 0.008732, R²: -0.0340
  Directional -> Accuracy: 0.6308, MCC: 0.2029, F1: 0.7333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12092 | val 0.21390
  Epoch 020 - train 0.12021 | val 0.21208
  Epoch 021 - train 0.12706 | val 0.21204
  Regression -> MSE: 0.000262, MAE: 0.011569, R²: -0.1581
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11972 | val 0.16883
  Epoch 020 - train 0.11246 | val 0.17426
  Epoch 021 - train 0.10853 | val 0.17508
  Regression -> MSE: 0.000153, MAE: 0.008814, R²: -0.0655
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12051 | val 0.17456
  Epoch 020 - train 0.11088 | val 0.17224
  Epoch 021 - train 0.11049 | val 0.17228
  Regression -> MSE: 0.000180, MAE: 0.010332, R²: -0.0887
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13069 | val 0.16963
  Epoch 020 - train 0.12984 | val 0.16742
  Epoch 021 - train 0.12288 | val 0.16841
  Regression -> MSE: 0.000090, MAE: 0.007306, R²: -0.0611
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11738 | val 0.33226
  Epoch 020 - train 0.11507 | val 0.32234
  Epoch 021 - train 0.11353 | val 0.31216
  Regression -> MSE: 0.000210, MAE: 0.011259, R²: 0.0070
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11202 | val 0.11638
  Epoch 020 - train 0.10422 | val 0.11779
  Epoch 021 - train 0.10684 | val 0.11826
  Regression -> MSE: 0.000103, MAE: 0.008255, R²: -0.1147
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12663 | val 0.09981
  Epoch 020 - train 0.11539 | val 0.10534
  Epoch 029 - train 0.11576 | val 0.10651
  Regression -> MSE: 0.000115, MAE: 0.009252, R²: -0.1171
  Directional -> Accuracy: 0.4783, MCC: 0.0553, F1: 0.5862

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12570 | val 0.17584
  Epoch 020 - train 0.12749 | val 0.19099
  Epoch 021 - train 0.12766 | val 0.19408
  Regression -> MSE: 0.000235, MAE: 0.012624, R²: -0.0141
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12734 | val 0.14596
  Epoch 020 - train 0.11882 | val 0.14947
  Epoch 021 - train 0.11420 | val 0.14998
  Regression -> MSE: 0.000183, MAE: 0.008003, R²: -0.1019
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13154 | val 0.11545
  Epoch 020 - train 0.12430 | val 0.11380
  Epoch 021 - train 0.12771 | val 0.11391
  Regression -> MSE: 0.000240, MAE: 0.011974, R²: -0.0134
  Directional -> Accuracy: 0.4146, MCC: -0.2437, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12005 | val 0.20335
  Epoch 020 - train 0.11406 | val 0.20471
  Epoch 021 - train 0.11139 | val 0.20502
  Regression -> MSE: 0.000234, MAE: 0.010105, R²: -0.0170
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13240 | val 0.17865
  Epoch 020 - train 0.12371 | val 0.17777
  Epoch 021 - train 0.12640 | val 0.17766
  Regression -> MSE: 0.000142, MAE: 0.008524, R²: -0.0529
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12184 | val 0.17258
  Epoch 020 - train 0.11256 | val 0.17393
  Epoch 021 - train 0.11726 | val 0.17367
  Regression -> MSE: 0.000202, MAE: 0.010793, R²: -0.0712
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10691 | val 0.14593
  Epoch 020 - train 0.10317 | val 0.15304
  Epoch 021 - train 0.09912 | val 0.15221
  Regression -> MSE: 0.000264, MAE: 0.010509, R²: -0.0090
  Directional -> Accuracy: 0.5479, MCC: -0.0438, F1: 0.7027

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11752 | val 0.10539
  Epoch 020 - train 0.11062 | val 0.10991
  Epoch 021 - train 0.10747 | val 0.11027
  Regression -> MSE: 0.000167, MAE: 0.010365, R²: 0.0004
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11566 | val 0.17615
  Epoch 020 - train 0.11267 | val 0.17583
  Epoch 021 - train 0.10575 | val 0.17586
  Regression -> MSE: 0.000179, MAE: 0.010238, R²: 0.0037
  Directional -> Accuracy: 0.5000, MCC: -0.0153, F1: 0.3889

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11983 | val 0.12441
  Epoch 020 - train 0.11575 | val 0.12056
  Epoch 021 - train 0.11336 | val 0.12072
  Regression -> MSE: 0.000355, MAE: 0.012808, R²: -0.0351
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13457 | val 0.08273
  Epoch 020 - train 0.12080 | val 0.07969
  Epoch 021 - train 0.12041 | val 0.07927
  Regression -> MSE: 0.000119, MAE: 0.008388, R²: -0.1350
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11664 | val 0.17852
  Epoch 020 - train 0.10899 | val 0.18588
  Epoch 021 - train 0.11813 | val 0.18532
  Regression -> MSE: 0.000219, MAE: 0.011261, R²: -0.0002
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12300 | val 0.28563
  Epoch 020 - train 0.11365 | val 0.30784
  Epoch 021 - train 0.12092 | val 0.30674
  Regression -> MSE: 0.000082, MAE: 0.007058, R²: -0.0582
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12550 | val 0.09958
  Epoch 020 - train 0.11638 | val 0.10098
  Epoch 021 - train 0.11550 | val 0.10098
  Regression -> MSE: 0.000328, MAE: 0.014895, R²: -0.0660
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13876 | val 0.08030
  Epoch 020 - train 0.12060 | val 0.09265
  Epoch 021 - train 0.12635 | val 0.09278
  Regression -> MSE: 0.000248, MAE: 0.011561, R²: -0.0165
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11080 | val 0.18082
  Epoch 020 - train 0.10866 | val 0.18771
  Epoch 021 - train 0.10938 | val 0.18787
  Regression -> MSE: 0.000082, MAE: 0.007134, R²: -0.0092
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12887 | val 0.19061
  Epoch 020 - train 0.12176 | val 0.25407
  Epoch 025 - train 0.11948 | val 0.25537
  Regression -> MSE: 0.000299, MAE: 0.014097, R²: 0.0241
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11454 | val 0.15292
  Epoch 020 - train 0.11786 | val 0.15725
  Epoch 021 - train 0.10664 | val 0.15740
  Regression -> MSE: 0.000101, MAE: 0.007166, R²: -0.0263
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13728 | val 0.16151
  Epoch 020 - train 0.12542 | val 0.16491
  Epoch 021 - train 0.12728 | val 0.16461
  Regression -> MSE: 0.000171, MAE: 0.009635, R²: 0.0025
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12034 | val 0.16578
  Epoch 020 - train 0.10806 | val 0.16805
  Epoch 021 - train 0.11298 | val 0.16691
  Regression -> MSE: 0.000223, MAE: 0.011780, R²: -0.0020
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12188 | val 0.14874
  Epoch 020 - train 0.11627 | val 0.15625
  Epoch 021 - train 0.10850 | val 0.15737
  Regression -> MSE: 0.000094, MAE: 0.007722, R²: -0.0182
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.13530 | val 0.20244
  Epoch 020 - train 0.12150 | val 0.20695
  Epoch 021 - train 0.12164 | val 0.20673
  Regression -> MSE: 0.000165, MAE: 0.010276, R²: -0.0062
  Directional -> Accuracy: 0.5185, MCC: 0.0131, F1: 0.6579

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.11369 | val 0.19629
  Epoch 020 - train 0.11100 | val 0.19893
  Epoch 021 - train 0.11408 | val 0.19815
  Regression -> MSE: 0.000117, MAE: 0.008970, R²: -0.0072
  Directional -> Accuracy: 0.5179, MCC: 0.0124, F1: 0.6582

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.12006 | val 0.20093

[I 2026-02-24 04:38:31,578] Trial 177 finished with value: -0.011469356347810523 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 5.351796844478587e-05, 'weight_decay': 2.4037181020990654e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.19231196281756213, 'early_stopping_min_delta': 0.009056017823015466}. Best is trial 44 with value: -0.011362814469631832.

  Regression -> MSE: 0.000237, MAE: 0.012335, R²: -0.0006
  Directional -> Accuracy: 0.5246, MCC: 0.0633, F1: 0.5672

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09400 | val 0.12748
  Epoch 020 - train 0.09149 | val 0.12558
  Regression -> MSE: 0.000261, MAE: 0.013041, R²: -0.0559
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09570 | val 0.09030
  Epoch 020 - train 0.09781 | val 0.10828
  Regression -> MSE: 0.000687, MAE: 0.019422, R²: -0.0042
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10041 | val 0.14523
  Epoch 020 - train 0.09991 | val 0.14344
  Regression -> MSE: 0.000311, MAE: 0.014397, R²: -0.0011
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08293 | val 0.17306
  Epoch 020 - train 0.08226 | val 0.17316
  Regression -> MSE: 0.000409, MAE: 0.015713, R²: -0.1718
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09321 | val 0.10315
  Epoch 020 - train 0.09393 | val 0.10992
  Regression -> MSE: 0.000206, MAE: 0.010349, R²: -0.0100
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10304 | val 0.17094
  Epoch 020 - train 0.10189 | val 0.19111
  Regression -> MSE: 0.000554, MAE: 0.018192, R²: 0.0016
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09608 | val 0.11416
  Epoch 020 - train 0.09099 | val 0.11420
  Regression -> MSE: 0.000246, MAE: 0.012128, R²: -0.0022
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09735 | val 0.12044
  Epoch 020 - train 0.09418 | val 0.13601
  Regression -> MSE: 0.000621, MAE: 0.019705, R²: -0.0389
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08924 | val 0.11660
  Epoch 020 - train 0.08456 | val 0.11801
  Regression -> MSE: 0.000385, MAE: 0.016064, R²: -0.0046
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09774 | val 0.13098
  Epoch 020 - train 0.09613 | val 0.12640
  Regression -> MSE: 0.000243, MAE: 0.012127, R²: -0.0068
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08871 | val 0.13003
  Epoch 020 - train 0.08505 | val 0.13175
  Regression -> MSE: 0.000320, MAE: 0.013613, R²: -0.0293
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10000 | val 0.12032
  Epoch 020 - train 0.09536 | val 0.12691
  Regression -> MSE: 0.000682, MAE: 0.019728, R²: -0.0068
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09995 | val 0.09600
  Epoch 020 - train 0.09513 | val 0.11649
  Regression -> MSE: 0.000141, MAE: 0.009317, R²: -0.0177
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09294 | val 0.11620
  Epoch 020 - train 0.08449 | val 0.11512
  Regression -> MSE: 0.000225, MAE: 0.010745, R²: -0.0010
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09372 | val 0.21563
  Epoch 020 - train 0.09801 | val 0.24394
  Regression -> MSE: 0.000365, MAE: 0.015944, R²: -0.0081
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10123 | val 0.11455
  Epoch 020 - train 0.09749 | val 0.10931
  Regression -> MSE: 0.000110, MAE: 0.008192, R²: -0.0198
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09547 | val 0.16644
  Epoch 020 - train 0.09220 | val 0.16872
  Regression -> MSE: 0.000156, MAE: 0.009529, R²: 0.0018
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10213 | val 0.10000
  Epoch 020 - train 0.09415 | val 0.09971
  Regression -> MSE: 0.000283, MAE: 0.013564, R²: -0.0410
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09459 | val 0.12231
  Epoch 020 - train 0.08426 | val 0.12276
  Regression -> MSE: 0.000154, MAE: 0.008758, R²: -0.0294
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09859 | val 0.13550
  Epoch 020 - train 0.09497 | val 0.13573
  Regression -> MSE: 0.000238, MAE: 0.011005, R²: -0.0531
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09248 | val 0.11859
  Epoch 020 - train 0.09514 | val 0.12441
  Regression -> MSE: 0.000147, MAE: 0.008540, R²: -0.0261
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09360 | val 0.10488
  Epoch 020 - train 0.09259 | val 0.10502
  Regression -> MSE: 0.000165, MAE: 0.010372, R²: 0.0000
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09811 | val 0.12314
  Epoch 020 - train 0.09593 | val 0.12217
  Regression -> MSE: 0.000091, MAE: 0.007370, R²: -0.0732
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09838 | val 0.12766
  Epoch 020 - train 0.09852 | val 0.14344
  Regression -> MSE: 0.000212, MAE: 0.011253, R²: -0.0031
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09256 | val 0.08545
  Epoch 020 - train 0.08677 | val 0.08471
  Regression -> MSE: 0.000096, MAE: 0.008135, R²: -0.0466
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09684 | val 0.07560
  Epoch 020 - train 0.09939 | val 0.08021
  Regression -> MSE: 0.000108, MAE: 0.008938, R²: -0.0427
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10304 | val 0.09189
  Epoch 020 - train 0.09582 | val 0.10127
  Regression -> MSE: 0.000233, MAE: 0.012610, R²: -0.0063
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09490 | val 0.11423
  Epoch 020 - train 0.09618 | val 0.11415
  Regression -> MSE: 0.000183, MAE: 0.008060, R²: -0.1026
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09633 | val 0.08105
  Epoch 020 - train 0.10005 | val 0.09627
  Regression -> MSE: 0.000237, MAE: 0.011878, R²: -0.0025
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09896 | val 0.14267
  Epoch 020 - train 0.09742 | val 0.14281
  Regression -> MSE: 0.000231, MAE: 0.009864, R²: -0.0022
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10061 | val 0.10637
  Epoch 020 - train 0.09529 | val 0.11027
  Regression -> MSE: 0.000135, MAE: 0.008180, R²: -0.0006
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09512 | val 0.11463
  Epoch 020 - train 0.09407 | val 0.11689
  Regression -> MSE: 0.000193, MAE: 0.010420, R²: -0.0235
  Directional -> Accuracy: 0.4800, MCC: 0.1319, F1: 0.0714

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08651 | val 0.10596
  Epoch 020 - train 0.08521 | val 0.10218
  Regression -> MSE: 0.000263, MAE: 0.010552, R²: -0.0039
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09952 | val 0.08728
  Epoch 020 - train 0.09101 | val 0.09012
  Regression -> MSE: 0.000170, MAE: 0.010374, R²: -0.0193
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08611 | val 0.09554
  Epoch 020 - train 0.08691 | val 0.10230
  Regression -> MSE: 0.000181, MAE: 0.010314, R²: -0.0033
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09288 | val 0.09353
  Epoch 020 - train 0.08969 | val 0.09429
  Regression -> MSE: 0.000346, MAE: 0.012201, R²: -0.0109
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10268 | val 0.06220
  Epoch 020 - train 0.10082 | val 0.06477
  Regression -> MSE: 0.000124, MAE: 0.008440, R²: -0.1840
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09238 | val 0.12263
  Epoch 020 - train 0.09342 | val 0.12268
  Regression -> MSE: 0.000219, MAE: 0.011281, R²: -0.0027
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09743 | val 0.15600
  Epoch 020 - train 0.09345 | val 0.15792
  Regression -> MSE: 0.000087, MAE: 0.007276, R²: -0.1139
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09370 | val 0.07521
  Epoch 020 - train 0.09620 | val 0.07625
  Regression -> MSE: 0.000324, MAE: 0.014720, R²: -0.0519
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11332 | val 0.06029
  Epoch 020 - train 0.10737 | val 0.06282
  Regression -> MSE: 0.000254, MAE: 0.011481, R²: -0.0409
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09415 | val 0.11865
  Epoch 020 - train 0.09392 | val 0.11772
  Regression -> MSE: 0.000081, MAE: 0.007066, R²: -0.0049
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10045 | val 0.11635
  Epoch 020 - train 0.09610 | val 0.11997
  Regression -> MSE: 0.000308, MAE: 0.014499, R²: -0.0029
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10058 | val 0.10462
  Epoch 020 - train 0.10031 | val 0.09893
  Regression -> MSE: 0.000100, MAE: 0.007136, R²: -0.0154
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10170 | val 0.11408
  Epoch 020 - train 0.09760 | val 0.12628
  Regression -> MSE: 0.000173, MAE: 0.009483, R²: -0.0053
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09026 | val 0.10957
  Epoch 020 - train 0.09320 | val 0.11279
  Regression -> MSE: 0.000223, MAE: 0.011770, R²: -0.0005
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09226 | val 0.10466
  Epoch 020 - train 0.08948 | val 0.10431
  Regression -> MSE: 0.000093, MAE: 0.007678, R²: -0.0059
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.10536 | val 0.15743
  Epoch 020 - train 0.10207 | val 0.16815
  Regression -> MSE: 0.000166, MAE: 0.010302, R²: -0.0116
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.09821 | val 0.11353
  Epoch 020 - train 0.09544 | val 0.11347
  Regression -> MSE: 0.000123, MAE: 0.008996, R²: -0.0572
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.09707 | val 0.12850

[I 2026-02-24 04:41:10,437] Trial 178 finished with value: -0.011462905797417666 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 2.78311867400495e-05, 'weight_decay': 7.646144920106156e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.13539532530106144, 'early_stopping_min_delta': 0.009649539068747106}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.09376 | val 0.12951
  Regression -> MSE: 0.000237, MAE: 0.012422, R²: 0.0016
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.17424 | val 0.22897
  Epoch 020 - train 0.17601 | val 0.22837
  Epoch 021 - train 0.17197 | val 0.22915
  Regression -> MSE: 0.000250, MAE: 0.012649, R²: -0.0082
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.17009 | val 0.16604
  Epoch 020 - train 0.16010 | val 0.17781
  Epoch 021 - train 0.16842 | val 0.17813
  Regression -> MSE: 0.000700, MAE: 0.019596, R²: -0.0218
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5306

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.18970 | val 0.28707
  Epoch 020 - train 0.17693 | val 0.29205
  Epoch 021 - train 0.17858 | val 0.29005
  Regression -> MSE: 0.000316, MAE: 0.014449, R²: -0.0192
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14600 | val 0.44665
  Epoch 020 - train 0.15027 | val 0.45402
  Epoch 021 - train 0.14681 | val 0.47218
  Regression -> MSE: 0.000371, MAE: 0.014914, R²: -0.0607
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.18247 | val 0.16427
  Epoch 020 - train 0.16974 | val 0.18233
  Epoch 026 - train 0.17113 | val 0.18794
  Regression -> MSE: 0.000193, MAE: 0.009455, R²: 0.0522
  Directional -> Accuracy: 0.6471, MCC: 0.3495, F1: 0.7429

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.16743 | val 0.33232
  Epoch 020 - train 0.16917 | val 0.35385
  Epoch 027 - train 0.16610 | val 0.35636
  Regression -> MSE: 0.000550, MAE: 0.018157, R²: 0.0089
  Directional -> Accuracy: 0.5745, MCC: 0.1726, F1: 0.3750

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.18471 | val 0.22679
  Epoch 020 - train 0.18203 | val 0.23089
  Epoch 021 - train 0.17086 | val 0.22994
  Regression -> MSE: 0.000250, MAE: 0.011972, R²: -0.0204
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.17964 | val 0.23210
  Epoch 020 - train 0.18358 | val 0.25665
  Epoch 021 - train 0.18111 | val 0.25947
  Regression -> MSE: 0.000613, MAE: 0.019559, R²: -0.0257
  Directional -> Accuracy: 0.4545, MCC: -0.0271, F1: 0.5000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.16141 | val 0.20534
  Epoch 020 - train 0.16461 | val 0.20707
  Epoch 021 - train 0.16783 | val 0.20638
  Regression -> MSE: 0.000415, MAE: 0.016315, R²: -0.0810
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.18001 | val 0.25632
  Epoch 020 - train 0.17429 | val 0.26493
  Epoch 021 - train 0.17657 | val 0.26614
  Regression -> MSE: 0.000243, MAE: 0.011709, R²: -0.0069
  Directional -> Accuracy: 0.5143, MCC: 0.0083, F1: 0.4333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.16799 | val 0.39766
  Epoch 020 - train 0.16918 | val 0.40127
  Epoch 021 - train 0.16332 | val 0.39858
  Regression -> MSE: 0.000308, MAE: 0.013649, R²: 0.0083
  Directional -> Accuracy: 0.4800, MCC: 0.0254, F1: 0.6061

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.19351 | val 0.21493
  Epoch 020 - train 0.18310 | val 0.21180
  Epoch 021 - train 0.19140 | val 0.21152
  Regression -> MSE: 0.000691, MAE: 0.019934, R²: -0.0205
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16641 | val 0.21494
  Epoch 020 - train 0.16536 | val 0.22165
  Epoch 021 - train 0.15774 | val 0.21909
  Regression -> MSE: 0.000139, MAE: 0.009030, R²: -0.0047
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15736 | val 0.22982
  Epoch 020 - train 0.16146 | val 0.24280
  Epoch 021 - train 0.15783 | val 0.24375
  Regression -> MSE: 0.000226, MAE: 0.010698, R²: -0.0028
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.17412 | val 0.37972
  Epoch 020 - train 0.16737 | val 0.37959
  Epoch 021 - train 0.16955 | val 0.37957
  Regression -> MSE: 0.000372, MAE: 0.015934, R²: -0.0259
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.17802 | val 0.19079
  Epoch 020 - train 0.17296 | val 0.19090
  Epoch 021 - train 0.17578 | val 0.19247
  Regression -> MSE: 0.000108, MAE: 0.007997, R²: -0.0011
  Directional -> Accuracy: 0.5143, MCC: -0.0150, F1: 0.6222

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.17221 | val 0.38745
  Epoch 020 - train 0.17917 | val 0.41431
  Epoch 021 - train 0.16616 | val 0.41633
  Regression -> MSE: 0.000163, MAE: 0.010228, R²: -0.0456
  Directional -> Accuracy: 0.4237, MCC: -0.0129, F1: 0.3200

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.18302 | val 0.18138
  Epoch 020 - train 0.18079 | val 0.19183
  Epoch 021 - train 0.17426 | val 0.19162
  Regression -> MSE: 0.000272, MAE: 0.012937, R²: 0.0019
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.15615 | val 0.23641
  Epoch 020 - train 0.15990 | val 0.24045
  Epoch 021 - train 0.15636 | val 0.24478
  Regression -> MSE: 0.000154, MAE: 0.008979, R²: -0.0274
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16859 | val 0.25132
  Epoch 020 - train 0.17788 | val 0.25199
  Epoch 021 - train 0.17735 | val 0.25097
  Regression -> MSE: 0.000244, MAE: 0.011123, R²: -0.0790
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17491 | val 0.22893
  Epoch 020 - train 0.16454 | val 0.24678
  Epoch 021 - train 0.17214 | val 0.24580
  Regression -> MSE: 0.000145, MAE: 0.008394, R²: -0.0091
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.16179 | val 0.22365
  Epoch 020 - train 0.16899 | val 0.22414
  Epoch 021 - train 0.16859 | val 0.22464
  Regression -> MSE: 0.000165, MAE: 0.010486, R²: -0.0012
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.18195 | val 0.21359
  Epoch 020 - train 0.18743 | val 0.22374
  Epoch 025 - train 0.18299 | val 0.22501
  Regression -> MSE: 0.000093, MAE: 0.007357, R²: -0.0868
  Directional -> Accuracy: 0.5172, MCC: 0.1339, F1: 0.3913

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.17503 | val 0.25185
  Epoch 020 - train 0.16854 | val 0.30214
  Epoch 021 - train 0.16595 | val 0.30065
  Regression -> MSE: 0.000213, MAE: 0.011021, R²: -0.0042
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.16112 | val 0.13593
  Epoch 020 - train 0.16501 | val 0.13501
  Epoch 030 - train 0.15721 | val 0.13274
  Regression -> MSE: 0.000103, MAE: 0.008106, R²: -0.1242
  Directional -> Accuracy: 0.5536, MCC: 0.2064, F1: 0.4186

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18440 | val 0.13805
  Epoch 020 - train 0.17629 | val 0.13646
  Epoch 021 - train 0.17766 | val 0.13627
  Regression -> MSE: 0.000107, MAE: 0.008895, R²: -0.0340
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.17779 | val 0.19378
  Epoch 020 - train 0.18331 | val 0.21749
  Epoch 021 - train 0.18412 | val 0.21552
  Regression -> MSE: 0.000233, MAE: 0.012587, R²: -0.0061
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.17356 | val 0.20672
  Epoch 020 - train 0.16831 | val 0.20993
  Epoch 021 - train 0.16889 | val 0.20954
  Regression -> MSE: 0.000186, MAE: 0.008084, R²: -0.1176
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.17354 | val 0.14929
  Epoch 020 - train 0.18110 | val 0.14736
  Epoch 021 - train 0.18636 | val 0.14712
  Regression -> MSE: 0.000237, MAE: 0.011886, R²: -0.0017
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.17541 | val 0.28870
  Epoch 020 - train 0.17219 | val 0.30073
  Epoch 021 - train 0.17429 | val 0.30042
  Regression -> MSE: 0.000231, MAE: 0.009864, R²: -0.0010
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18220 | val 0.24131
  Epoch 020 - train 0.18228 | val 0.25208
  Epoch 021 - train 0.18740 | val 0.25076
  Regression -> MSE: 0.000142, MAE: 0.008584, R²: -0.0503
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.16248 | val 0.23450
  Epoch 020 - train 0.17235 | val 0.24067
  Epoch 021 - train 0.17242 | val 0.24126
  Regression -> MSE: 0.000201, MAE: 0.010763, R²: -0.0657
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15006 | val 0.19975
  Epoch 020 - train 0.15369 | val 0.20211
  Epoch 021 - train 0.15370 | val 0.20186
  Regression -> MSE: 0.000264, MAE: 0.010517, R²: -0.0085
  Directional -> Accuracy: 0.5753, MCC: 0.1768, F1: 0.5634

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16254 | val 0.14581
  Epoch 020 - train 0.15949 | val 0.15932
  Epoch 021 - train 0.16147 | val 0.16149
  Regression -> MSE: 0.000165, MAE: 0.010343, R²: 0.0076
  Directional -> Accuracy: 0.5263, MCC: 0.0580, F1: 0.4000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.17002 | val 0.22292
  Epoch 020 - train 0.16387 | val 0.22099
  Epoch 021 - train 0.16337 | val 0.22028
  Regression -> MSE: 0.000179, MAE: 0.010224, R²: 0.0056
  Directional -> Accuracy: 0.5682, MCC: 0.1412, F1: 0.5778

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15628 | val 0.16995
  Epoch 020 - train 0.15909 | val 0.17614
  Epoch 021 - train 0.16414 | val 0.17641
  Regression -> MSE: 0.000340, MAE: 0.011758, R²: 0.0081
  Directional -> Accuracy: 0.5522, MCC: 0.0807, F1: 0.6154

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18761 | val 0.11304
  Epoch 020 - train 0.17783 | val 0.11830
  Epoch 021 - train 0.18007 | val 0.11859
  Regression -> MSE: 0.000112, MAE: 0.008296, R²: -0.0614
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17024 | val 0.24503
  Epoch 020 - train 0.17615 | val 0.27408
  Epoch 021 - train 0.16919 | val 0.27214
  Regression -> MSE: 0.000220, MAE: 0.011294, R²: -0.0058
  Directional -> Accuracy: 0.5263, MCC: 0.0449, F1: 0.4706

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16904 | val 0.35606
  Epoch 020 - train 0.16398 | val 0.40235
  Epoch 021 - train 0.16888 | val 0.40179
  Regression -> MSE: 0.000086, MAE: 0.007258, R²: -0.1068
  Directional -> Accuracy: 0.4043, MCC: 0.1162, F1: 0.0667

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.17857 | val 0.14330
  Epoch 020 - train 0.16499 | val 0.13913
  Epoch 021 - train 0.17657 | val 0.13935
  Regression -> MSE: 0.000326, MAE: 0.014853, R²: -0.0583
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.18247 | val 0.10613
  Epoch 020 - train 0.19023 | val 0.11384
  Epoch 021 - train 0.19148 | val 0.11428
  Regression -> MSE: 0.000248, MAE: 0.011556, R²: -0.0182
  Directional -> Accuracy: 0.4737, MCC: -0.0882, F1: 0.5833

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16168 | val 0.21690
  Epoch 020 - train 0.15780 | val 0.21763
  Epoch 021 - train 0.15669 | val 0.21825
  Regression -> MSE: 0.000081, MAE: 0.007035, R²: -0.0044
  Directional -> Accuracy: 0.5333, MCC: 0.0699, F1: 0.3636

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17761 | val 0.21376
  Epoch 020 - train 0.17515 | val 0.29360
  Epoch 021 - train 0.17133 | val 0.29449
  Regression -> MSE: 0.000307, MAE: 0.014477, R²: 0.0005
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16683 | val 0.20909
  Epoch 020 - train 0.16531 | val 0.21934
  Epoch 021 - train 0.17377 | val 0.21952
  Regression -> MSE: 0.000098, MAE: 0.007234, R²: -0.0017
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.19918 | val 0.21593
  Epoch 020 - train 0.19491 | val 0.21744
  Epoch 021 - train 0.18257 | val 0.21884
  Regression -> MSE: 0.000176, MAE: 0.009437, R²: -0.0228
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.17378 | val 0.21507
  Epoch 020 - train 0.17358 | val 0.20953
  Epoch 021 - train 0.17843 | val 0.21086
  Regression -> MSE: 0.000241, MAE: 0.012245, R²: -0.0818
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.17582 | val 0.20554
  Epoch 020 - train 0.16077 | val 0.20460
  Epoch 021 - train 0.16538 | val 0.20515
  Regression -> MSE: 0.000093, MAE: 0.007672, R²: -0.0085
  Directional -> Accuracy: 0.4211, MCC: -0.1674, F1: 0.5600

[86/88] Processing WFC...


[I 2026-02-24 04:45:34,567] Trial 179 finished with value: -0.011425897275210189 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 4.0461712677515646e-05, 'weight_decay': 9.465531666995738e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.27984022256863716, 'early_stopping_min_delta': 0.00950835478080647}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.17405 | val 0.27894
  Regression -> MSE: 0.000239, MAE: 0.012355, R²: -0.0088
  Directional -> Accuracy: 0.4918, MCC: -0.0940, F1: 0.1143

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.16523 | val 0.24623
  Epoch 020 - train 0.16271 | val 0.24879
  Epoch 021 - train 0.17101 | val 0.24946
  Regression -> MSE: 0.000247, MAE: 0.012459, R²: 0.0041
  Directional -> Accuracy: 0.5974, MCC: 0.2048, F1: 0.5974

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.15770 | val 0.20161
  Epoch 020 - train 0.15469 | val 0.17512
  Epoch 021 - train 0.15303 | val 0.17980
  Regression -> MSE: 0.000673, MAE: 0.019082, R²: 0.0165
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.17687 | val 0.28161
  Epoch 020 - train 0.17890 | val 0.28904
  Epoch 026 - train 0.17380 | val 0.28954
  Regression -> MSE: 0.000349, MAE: 0.014946, R²: -0.1239
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.14143 | val 0.45613
  Epoch 020 - train 0.13454 | val 0.36684
  Epoch 021 - train 0.13648 | val 0.36944
  Regression -> MSE: 0.000388, MAE: 0.015206, R²: -0.1103
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16138 | val 0.19483
  Epoch 020 - train 0.16773 | val 0.20363
  Epoch 021 - train 0.15515 | val 0.20290
  Regression -> MSE: 0.000203, MAE: 0.010094, R²: 0.0008
  Directional -> Accuracy: 0.5490, MCC: 0.2223, F1: 0.3030

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.16070 | val 0.33710
  Epoch 020 - train 0.15463 | val 0.35780
  Epoch 021 - train 0.14384 | val 0.35901
  Regression -> MSE: 0.000562, MAE: 0.018200, R²: -0.0118
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16910 | val 0.23039
  Epoch 020 - train 0.16793 | val 0.23379
  Epoch 021 - train 0.16834 | val 0.23353
  Regression -> MSE: 0.000245, MAE: 0.011944, R²: 0.0039
  Directional -> Accuracy: 0.5362, MCC: 0.0937, F1: 0.5152

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.16386 | val 0.31959
  Epoch 020 - train 0.14902 | val 0.42178
  Epoch 021 - train 0.15960 | val 0.42276
  Regression -> MSE: 0.000627, MAE: 0.019786, R²: -0.0499
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.16429 | val 0.21672
  Epoch 020 - train 0.15443 | val 0.20832
  Epoch 030 - train 0.15639 | val 0.21568
  Regression -> MSE: 0.000486, MAE: 0.016942, R²: -0.2661
  Directional -> Accuracy: 0.5918, MCC: 0.1635, F1: 0.2857

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.16416 | val 0.24643
  Epoch 020 - train 0.16979 | val 0.23487
  Epoch 021 - train 0.15527 | val 0.23543
  Regression -> MSE: 0.000250, MAE: 0.011626, R²: -0.0360
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15621 | val 0.49771
  Epoch 020 - train 0.14300 | val 0.52385
  Epoch 021 - train 0.15066 | val 0.53606
  Regression -> MSE: 0.000311, MAE: 0.013564, R²: -0.0012
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.16744 | val 0.22772
  Epoch 020 - train 0.16092 | val 0.24114
  Epoch 021 - train 0.16877 | val 0.24339
  Regression -> MSE: 0.000678, MAE: 0.019532, R²: -0.0013
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16954 | val 0.28813
  Epoch 020 - train 0.15575 | val 0.30504
  Epoch 021 - train 0.15699 | val 0.30264
  Regression -> MSE: 0.000142, MAE: 0.008988, R²: -0.0300
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14537 | val 0.24755
  Epoch 020 - train 0.14993 | val 0.24821
  Epoch 024 - train 0.14823 | val 0.24099
  Regression -> MSE: 0.000219, MAE: 0.010554, R²: 0.0265
  Directional -> Accuracy: 0.5410, MCC: 0.0825, F1: 0.6216

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16900 | val 0.37976
  Epoch 020 - train 0.15948 | val 0.43511
  Epoch 021 - train 0.15524 | val 0.44703
  Regression -> MSE: 0.000361, MAE: 0.016000, R²: 0.0039
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16963 | val 0.18394
  Epoch 020 - train 0.16842 | val 0.18105
  Epoch 021 - train 0.16223 | val 0.18049
  Regression -> MSE: 0.000106, MAE: 0.008004, R²: 0.0142
  Directional -> Accuracy: 0.4857, MCC: 0.1024, F1: 0.1429

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.16742 | val 0.44021
  Epoch 020 - train 0.15565 | val 0.46011
  Epoch 021 - train 0.15774 | val 0.45745
  Regression -> MSE: 0.000159, MAE: 0.010021, R²: -0.0196
  Directional -> Accuracy: 0.6441, MCC: 0.1603, F1: 0.7586

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16828 | val 0.34630
  Epoch 020 - train 0.16722 | val 0.31411
  Epoch 021 - train 0.16086 | val 0.31045
  Regression -> MSE: 0.000271, MAE: 0.012943, R²: 0.0054
  Directional -> Accuracy: 0.5921, MCC: -0.0933, F1: 0.7438

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14692 | val 0.23128
  Epoch 020 - train 0.15065 | val 0.24503
  Epoch 030 - train 0.14223 | val 0.24817
  Regression -> MSE: 0.000506, MAE: 0.019624, R²: -2.3824
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16922 | val 0.26260
  Epoch 020 - train 0.16759 | val 0.27955
  Epoch 021 - train 0.16466 | val 0.27392
  Regression -> MSE: 0.000242, MAE: 0.011112, R²: -0.0711
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16039 | val 0.26767
  Epoch 020 - train 0.16295 | val 0.28538
  Epoch 021 - train 0.16503 | val 0.28303
  Regression -> MSE: 0.000150, MAE: 0.008687, R²: -0.0485
  Directional -> Accuracy: 0.6458, MCC: 0.3361, F1: 0.6667

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15784 | val 0.22725
  Epoch 020 - train 0.15702 | val 0.23371
  Epoch 021 - train 0.15783 | val 0.23438
  Regression -> MSE: 0.000168, MAE: 0.010151, R²: -0.0159
  Directional -> Accuracy: 0.5606, MCC: 0.1414, F1: 0.6506

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.17058 | val 0.22649
  Epoch 020 - train 0.17135 | val 0.22555
  Epoch 021 - train 0.17265 | val 0.22365
  Regression -> MSE: 0.000090, MAE: 0.007322, R²: -0.0539
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16798 | val 0.48570
  Epoch 020 - train 0.17060 | val 0.44395
  Epoch 021 - train 0.16642 | val 0.44694
  Regression -> MSE: 0.000215, MAE: 0.010986, R²: -0.0169
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14939 | val 0.14222
  Epoch 020 - train 0.14509 | val 0.13491
  Epoch 030 - train 0.14487 | val 0.13667
  Regression -> MSE: 0.000135, MAE: 0.009080, R²: -0.4677
  Directional -> Accuracy: 0.5714, MCC: 0.2385, F1: 0.4545

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17667 | val 0.13800
  Epoch 020 - train 0.17091 | val 0.14224
  Epoch 021 - train 0.16841 | val 0.14274
  Regression -> MSE: 0.000107, MAE: 0.008918, R²: -0.0413
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.17231 | val 0.18255
  Epoch 020 - train 0.17371 | val 0.21349
  Epoch 021 - train 0.18348 | val 0.22165
  Regression -> MSE: 0.000235, MAE: 0.012682, R²: -0.0153
  Directional -> Accuracy: 0.6047, MCC: 0.1428, F1: 0.7119

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.16054 | val 0.21463
  Epoch 020 - train 0.16576 | val 0.20871
  Epoch 021 - train 0.15639 | val 0.20891
  Regression -> MSE: 0.000174, MAE: 0.007908, R²: -0.0453
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16830 | val 0.14789
  Epoch 020 - train 0.16299 | val 0.14715
  Epoch 030 - train 0.15714 | val 0.15403
  Regression -> MSE: 0.000230, MAE: 0.011890, R²: 0.0271
  Directional -> Accuracy: 0.5610, MCC: 0.1065, F1: 0.6250

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.16734 | val 0.28643
  Epoch 020 - train 0.17268 | val 0.29254
  Epoch 021 - train 0.16607 | val 0.29117
  Regression -> MSE: 0.000231, MAE: 0.009891, R²: -0.0024
  Directional -> Accuracy: 0.4419, MCC: -0.1788, F1: 0.1429

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16625 | val 0.23630
  Epoch 020 - train 0.16344 | val 0.24208
  Epoch 021 - train 0.17314 | val 0.24065
  Regression -> MSE: 0.000140, MAE: 0.008382, R²: -0.0347
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.16582 | val 0.24409
  Epoch 020 - train 0.16389 | val 0.24833
  Epoch 021 - train 0.15974 | val 0.24649
  Regression -> MSE: 0.000190, MAE: 0.010423, R²: -0.0082
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14660 | val 0.21392
  Epoch 020 - train 0.14772 | val 0.21818
  Epoch 023 - train 0.14184 | val 0.21547
  Regression -> MSE: 0.000335, MAE: 0.012503, R²: -0.2808
  Directional -> Accuracy: 0.5342, MCC: 0.1465, F1: 0.4333

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14614 | val 0.14585
  Epoch 020 - train 0.15529 | val 0.21397
  Epoch 021 - train 0.14687 | val 0.21857
  Regression -> MSE: 0.000166, MAE: 0.010360, R²: 0.0035
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.15844 | val 0.20000
  Epoch 020 - train 0.15118 | val 0.19698
  Epoch 021 - train 0.15261 | val 0.20200
  Regression -> MSE: 0.000180, MAE: 0.010269, R²: 0.0017
  Directional -> Accuracy: 0.5455, MCC: 0.1041, F1: 0.5833

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16060 | val 0.17831
  Epoch 020 - train 0.15220 | val 0.18137
  Epoch 021 - train 0.15181 | val 0.18245
  Regression -> MSE: 0.000339, MAE: 0.011752, R²: 0.0112
  Directional -> Accuracy: 0.5970, MCC: 0.2509, F1: 0.5574

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.17035 | val 0.11704
  Epoch 020 - train 0.16454 | val 0.12700
  Epoch 021 - train 0.16467 | val 0.12734
  Regression -> MSE: 0.000115, MAE: 0.008319, R²: -0.0921
  Directional -> Accuracy: 0.6047, MCC: 0.2331, F1: 0.6909

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17577 | val 0.28247
  Epoch 020 - train 0.16498 | val 0.28627
  Epoch 021 - train 0.16658 | val 0.28644
  Regression -> MSE: 0.000219, MAE: 0.011245, R²: -0.0010
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16148 | val 0.40549
  Epoch 020 - train 0.15814 | val 0.42873
  Epoch 021 - train 0.15628 | val 0.43085
  Regression -> MSE: 0.000079, MAE: 0.006930, R²: -0.0154
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.16801 | val 0.15027
  Epoch 020 - train 0.15560 | val 0.14357
  Epoch 030 - train 0.14850 | val 0.13513
  Regression -> MSE: 0.000870, MAE: 0.026008, R²: -1.8277
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.16826 | val 0.11819
  Epoch 020 - train 0.17184 | val 0.13973
  Epoch 021 - train 0.16481 | val 0.14208
  Regression -> MSE: 0.000262, MAE: 0.011485, R²: -0.0757
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16305 | val 0.20927
  Epoch 020 - train 0.15179 | val 0.22627
  Epoch 025 - train 0.14998 | val 0.23726
  Regression -> MSE: 0.000086, MAE: 0.007313, R²: -0.0607
  Directional -> Accuracy: 0.5333, MCC: 0.2014, F1: 0.6789

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17026 | val 0.28066
  Epoch 020 - train 0.16573 | val 0.37148
  Epoch 025 - train 0.15776 | val 0.41077
  Regression -> MSE: 0.000312, MAE: 0.014518, R²: -0.0184
  Directional -> Accuracy: 0.5106, MCC: 0.0509, F1: 0.2581

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16448 | val 0.19340
  Epoch 020 - train 0.15763 | val 0.19470
  Epoch 021 - train 0.15797 | val 0.19519
  Regression -> MSE: 0.000097, MAE: 0.007197, R²: 0.0116
  Directional -> Accuracy: 0.6591, MCC: 0.3028, F1: 0.7541

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17374 | val 0.21200
  Epoch 020 - train 0.17747 | val 0.21939
  Epoch 021 - train 0.18351 | val 0.21686
  Regression -> MSE: 0.000178, MAE: 0.009422, R²: -0.0363
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.15598 | val 0.29587
  Epoch 020 - train 0.16153 | val 0.31721
  Epoch 021 - train 0.16109 | val 0.32058
  Regression -> MSE: 0.000223, MAE: 0.011749, R²: -0.0008
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.16656 | val 0.23281
  Epoch 020 - train 0.15976 | val 0.24926
  Epoch 021 - train 0.15941 | val 0.25086
  Regression -> MSE: 0.000096, MAE: 0.007872, R²: -0.0372
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...


[I 2026-02-24 04:50:13,624] Trial 180 finished with value: -0.011907862748319231 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.5, 'batch_size': 32, 'learning_rate': 0.00013294377771376573, 'weight_decay': 1.053499051768091e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2779181329157887, 'early_stopping_min_delta': 0.004880327042485127}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.16837 | val 0.43615
  Regression -> MSE: 0.000239, MAE: 0.012296, R²: -0.0086
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07308 | val 0.08765
  Epoch 020 - train 0.06974 | val 0.09006
  Epoch 021 - train 0.07389 | val 0.09020
  Regression -> MSE: 0.000250, MAE: 0.012631, R²: -0.0083
  Directional -> Accuracy: 0.4286, MCC: -0.1378, F1: 0.4211

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07424 | val 0.07103
  Epoch 020 - train 0.06980 | val 0.07338
  Epoch 021 - train 0.06623 | val 0.07379
  Regression -> MSE: 0.000682, MAE: 0.019238, R²: 0.0043
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07442 | val 0.10804
  Epoch 020 - train 0.07140 | val 0.10845
  Epoch 021 - train 0.07472 | val 0.10881
  Regression -> MSE: 0.000328, MAE: 0.014628, R²: -0.0564
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06496 | val 0.09963
  Epoch 020 - train 0.06312 | val 0.11805
  Epoch 021 - train 0.06126 | val 0.11642
  Regression -> MSE: 0.000346, MAE: 0.014513, R²: 0.0093
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07634 | val 0.07589
  Epoch 020 - train 0.07030 | val 0.08086
  Epoch 021 - train 0.07220 | val 0.08178
  Regression -> MSE: 0.000204, MAE: 0.010229, R²: 0.0001
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.06844 | val 0.12973
  Epoch 020 - train 0.06660 | val 0.13970
  Epoch 021 - train 0.06931 | val 0.13973
  Regression -> MSE: 0.000573, MAE: 0.018444, R²: -0.0320
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07436 | val 0.09040
  Epoch 020 - train 0.07552 | val 0.09064
  Epoch 021 - train 0.07176 | val 0.09055
  Regression -> MSE: 0.000254, MAE: 0.012015, R²: -0.0351
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.06758 | val 0.09898
  Epoch 020 - train 0.07070 | val 0.09979
  Epoch 021 - train 0.07264 | val 0.09823
  Regression -> MSE: 0.000669, MAE: 0.020515, R²: -0.1189
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.06913 | val 0.08175
  Epoch 020 - train 0.06777 | val 0.08233
  Epoch 021 - train 0.06579 | val 0.08256
  Regression -> MSE: 0.000405, MAE: 0.016130, R²: -0.0544
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07203 | val 0.09287
  Epoch 020 - train 0.07031 | val 0.09518
  Epoch 021 - train 0.07093 | val 0.09495
  Regression -> MSE: 0.000241, MAE: 0.011910, R²: 0.0019
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06731 | val 0.11304
  Epoch 020 - train 0.06812 | val 0.12201
  Epoch 021 - train 0.06755 | val 0.12274
  Regression -> MSE: 0.000313, MAE: 0.013702, R²: -0.0066
  Directional -> Accuracy: 0.4400, MCC: -0.0898, F1: 0.5625

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07778 | val 0.09697
  Epoch 020 - train 0.07437 | val 0.10163
  Epoch 021 - train 0.07541 | val 0.10104
  Regression -> MSE: 0.000677, MAE: 0.019430, R²: 0.0011
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07313 | val 0.07934
  Epoch 020 - train 0.07512 | val 0.07981
  Epoch 021 - train 0.06802 | val 0.08140
  Regression -> MSE: 0.000141, MAE: 0.009035, R²: -0.0181
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.07077 | val 0.10674
  Epoch 020 - train 0.06868 | val 0.10392
  Epoch 021 - train 0.07109 | val 0.10397
  Regression -> MSE: 0.000226, MAE: 0.010861, R²: -0.0034
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.06957 | val 0.14902
  Epoch 020 - train 0.06872 | val 0.14507
  Epoch 021 - train 0.07076 | val 0.14509
  Regression -> MSE: 0.000361, MAE: 0.015983, R²: 0.0042
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07234 | val 0.07871
  Epoch 020 - train 0.07479 | val 0.07538
  Epoch 021 - train 0.07210 | val 0.07543
  Regression -> MSE: 0.000106, MAE: 0.007930, R²: 0.0174
  Directional -> Accuracy: 0.5429, MCC: 0.0661, F1: 0.6098

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07196 | val 0.14262
  Epoch 020 - train 0.06669 | val 0.14965
  Epoch 021 - train 0.06981 | val 0.15200
  Regression -> MSE: 0.000158, MAE: 0.009960, R²: -0.0155
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.06932 | val 0.07877
  Epoch 020 - train 0.07049 | val 0.08712
  Epoch 021 - train 0.06983 | val 0.08775
  Regression -> MSE: 0.000273, MAE: 0.012969, R²: -0.0015
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06597 | val 0.09228
  Epoch 020 - train 0.06487 | val 0.09156
  Epoch 021 - train 0.06504 | val 0.09171
  Regression -> MSE: 0.000154, MAE: 0.008716, R²: -0.0274
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07084 | val 0.11275
  Epoch 020 - train 0.07242 | val 0.11161
  Epoch 021 - train 0.07266 | val 0.11217
  Regression -> MSE: 0.000251, MAE: 0.011306, R²: -0.1082
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07625 | val 0.08455
  Epoch 020 - train 0.06754 | val 0.08598
  Epoch 021 - train 0.07007 | val 0.08589
  Regression -> MSE: 0.000144, MAE: 0.008336, R²: -0.0078
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.06894 | val 0.08358
  Epoch 020 - train 0.06837 | val 0.08428
  Epoch 021 - train 0.06859 | val 0.08470
  Regression -> MSE: 0.000168, MAE: 0.010269, R²: -0.0153
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07466 | val 0.08407
  Epoch 020 - train 0.07406 | val 0.08290
  Epoch 021 - train 0.07320 | val 0.08307
  Regression -> MSE: 0.000085, MAE: 0.007034, R²: 0.0060
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07020 | val 0.08857
  Epoch 020 - train 0.06810 | val 0.10218
  Epoch 021 - train 0.07000 | val 0.10120
  Regression -> MSE: 0.000216, MAE: 0.011099, R²: -0.0216
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07096 | val 0.05988
  Epoch 020 - train 0.06738 | val 0.05834
  Epoch 021 - train 0.06497 | val 0.05796
  Regression -> MSE: 0.000101, MAE: 0.008267, R²: -0.0954
  Directional -> Accuracy: 0.3929, MCC: -0.2037, F1: 0.1053

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07456 | val 0.05590
  Epoch 020 - train 0.07287 | val 0.05733
  Epoch 021 - train 0.07137 | val 0.05755
  Regression -> MSE: 0.000104, MAE: 0.008794, R²: -0.0094
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07617 | val 0.08875
  Epoch 020 - train 0.07192 | val 0.09772
  Epoch 021 - train 0.07466 | val 0.09943
  Regression -> MSE: 0.000245, MAE: 0.012961, R²: -0.0597
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07124 | val 0.08131
  Epoch 020 - train 0.06956 | val 0.08190
  Epoch 021 - train 0.06939 | val 0.08174
  Regression -> MSE: 0.000182, MAE: 0.008020, R²: -0.0955
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.08495 | val 0.06131
  Epoch 020 - train 0.07945 | val 0.06424
  Epoch 021 - train 0.07756 | val 0.06388
  Regression -> MSE: 0.000242, MAE: 0.011973, R²: -0.0220
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07731 | val 0.11316
  Epoch 020 - train 0.07115 | val 0.11416
  Epoch 021 - train 0.07371 | val 0.11394
  Regression -> MSE: 0.000232, MAE: 0.010040, R²: -0.0073
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07346 | val 0.08958
  Epoch 020 - train 0.07286 | val 0.09098
  Epoch 021 - train 0.07032 | val 0.09074
  Regression -> MSE: 0.000137, MAE: 0.008329, R²: -0.0175
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07022 | val 0.09305
  Epoch 020 - train 0.06862 | val 0.09604
  Epoch 021 - train 0.07149 | val 0.09635
  Regression -> MSE: 0.000192, MAE: 0.010441, R²: -0.0175
  Directional -> Accuracy: 0.5200, MCC: 0.0088, F1: 0.6129

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06807 | val 0.07632
  Epoch 020 - train 0.06644 | val 0.07731
  Epoch 021 - train 0.06310 | val 0.07737
  Regression -> MSE: 0.000268, MAE: 0.010631, R²: -0.0234
  Directional -> Accuracy: 0.5890, MCC: 0.1778, F1: 0.6154

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07151 | val 0.05893
  Epoch 020 - train 0.06766 | val 0.05836
  Epoch 021 - train 0.06867 | val 0.05854
  Regression -> MSE: 0.000168, MAE: 0.010377, R²: -0.0057
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.07113 | val 0.07650
  Epoch 020 - train 0.06699 | val 0.08000
  Epoch 021 - train 0.06522 | val 0.08010
  Regression -> MSE: 0.000178, MAE: 0.010201, R²: 0.0108
  Directional -> Accuracy: 0.5682, MCC: 0.1727, F1: 0.2400

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.06869 | val 0.06961
  Epoch 020 - train 0.06990 | val 0.07234
  Epoch 021 - train 0.06806 | val 0.07216
  Regression -> MSE: 0.000352, MAE: 0.012600, R²: -0.0282
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.07850 | val 0.04667
  Epoch 020 - train 0.07452 | val 0.04703
  Epoch 021 - train 0.07896 | val 0.04706
  Regression -> MSE: 0.000118, MAE: 0.008414, R²: -0.1240
  Directional -> Accuracy: 0.2791, MCC: -0.4423, F1: 0.2439

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07768 | val 0.11889
  Epoch 020 - train 0.07425 | val 0.12015
  Epoch 021 - train 0.07312 | val 0.11819
  Regression -> MSE: 0.000218, MAE: 0.011214, R²: 0.0011
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07149 | val 0.13934
  Epoch 020 - train 0.07198 | val 0.15100
  Epoch 021 - train 0.06914 | val 0.14911
  Regression -> MSE: 0.000089, MAE: 0.007377, R²: -0.1419
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.06911 | val 0.05535
  Epoch 020 - train 0.06968 | val 0.05262
  Epoch 021 - train 0.06715 | val 0.05249
  Regression -> MSE: 0.000327, MAE: 0.014871, R²: -0.0634
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07648 | val 0.04727
  Epoch 020 - train 0.07956 | val 0.04956
  Epoch 021 - train 0.07440 | val 0.04956
  Regression -> MSE: 0.000252, MAE: 0.011413, R²: -0.0357
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.06820 | val 0.08517
  Epoch 020 - train 0.06446 | val 0.08444
  Epoch 021 - train 0.06585 | val 0.08448
  Regression -> MSE: 0.000082, MAE: 0.007048, R²: -0.0205
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07490 | val 0.08906
  Epoch 020 - train 0.07309 | val 0.08307
  Epoch 021 - train 0.07296 | val 0.08301
  Regression -> MSE: 0.000312, MAE: 0.014478, R²: -0.0179
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07497 | val 0.08476
  Epoch 020 - train 0.07150 | val 0.08414
  Epoch 021 - train 0.06939 | val 0.08464
  Regression -> MSE: 0.000102, MAE: 0.007128, R²: -0.0433
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.07908 | val 0.08741
  Epoch 020 - train 0.07307 | val 0.08859
  Epoch 021 - train 0.07350 | val 0.08883
  Regression -> MSE: 0.000172, MAE: 0.009588, R²: -0.0013
  Directional -> Accuracy: 0.4898, MCC: -0.0447, F1: 0.3902

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.06832 | val 0.08110
  Epoch 020 - train 0.06805 | val 0.08124
  Epoch 021 - train 0.06551 | val 0.08137
  Regression -> MSE: 0.000223, MAE: 0.011783, R²: -0.0021
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.07449 | val 0.07890
  Epoch 020 - train 0.07089 | val 0.08439
  Epoch 021 - train 0.06977 | val 0.08455
  Regression -> MSE: 0.000093, MAE: 0.007652, R²: -0.0098
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...


[I 2026-02-24 04:54:31,009] Trial 181 finished with value: -0.011444580108582738 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 3.491137277158216e-05, 'weight_decay': 1.539329143116563e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.10000684578546824, 'early_stopping_min_delta': 0.009632369706790801}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.07062 | val 0.10548
  Regression -> MSE: 0.000253, MAE: 0.012536, R²: -0.0650
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10784 | val 0.13991
  Epoch 020 - train 0.11014 | val 0.14395
  Epoch 021 - train 0.10563 | val 0.14509
  Regression -> MSE: 0.000253, MAE: 0.012782, R²: -0.0218
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10406 | val 0.12054
  Epoch 020 - train 0.10111 | val 0.12794
  Epoch 021 - train 0.10631 | val 0.12739
  Regression -> MSE: 0.000689, MAE: 0.019385, R²: -0.0060
  Directional -> Accuracy: 0.6957, MCC: 0.4075, F1: 0.7812

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11712 | val 0.17668
  Epoch 020 - train 0.11544 | val 0.17899
  Epoch 021 - train 0.10938 | val 0.17837
  Regression -> MSE: 0.000311, MAE: 0.014479, R²: -0.0016
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09243 | val 0.22930
  Epoch 020 - train 0.08928 | val 0.28459
  Epoch 021 - train 0.09089 | val 0.29389
  Regression -> MSE: 0.000389, MAE: 0.015241, R²: -0.1131
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10911 | val 0.10446
  Epoch 020 - train 0.10193 | val 0.11188
  Epoch 021 - train 0.10337 | val 0.11166
  Regression -> MSE: 0.000205, MAE: 0.010109, R²: -0.0086
  Directional -> Accuracy: 0.4902, MCC: -0.1289, F1: 0.6486

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09437 | val 0.20412
  Epoch 020 - train 0.10098 | val 0.21644
  Epoch 021 - train 0.09988 | val 0.21771
  Regression -> MSE: 0.000595, MAE: 0.018915, R²: -0.0721
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11652 | val 0.13976
  Epoch 020 - train 0.11174 | val 0.14161
  Epoch 021 - train 0.11158 | val 0.14201
  Regression -> MSE: 0.000245, MAE: 0.011949, R²: 0.0028
  Directional -> Accuracy: 0.5217, MCC: 0.0249, F1: 0.4407

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11581 | val 0.15892
  Epoch 020 - train 0.09942 | val 0.18863
  Epoch 021 - train 0.10990 | val 0.19035
  Regression -> MSE: 0.000638, MAE: 0.020062, R²: -0.0678
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10230 | val 0.13932
  Epoch 020 - train 0.10168 | val 0.13918
  Epoch 021 - train 0.09549 | val 0.13868
  Regression -> MSE: 0.000392, MAE: 0.016056, R²: -0.0220
  Directional -> Accuracy: 0.4490, MCC: -0.0212, F1: 0.6087

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10608 | val 0.14491
  Epoch 020 - train 0.11005 | val 0.16184
  Epoch 021 - train 0.10688 | val 0.16042
  Regression -> MSE: 0.000242, MAE: 0.011877, R²: -0.0015
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10234 | val 0.15828
  Epoch 020 - train 0.10294 | val 0.16929
  Epoch 021 - train 0.10190 | val 0.16922
  Regression -> MSE: 0.000316, MAE: 0.013574, R²: -0.0147
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11370 | val 0.14144
  Epoch 020 - train 0.11026 | val 0.14157
  Epoch 021 - train 0.11038 | val 0.14237
  Regression -> MSE: 0.000681, MAE: 0.019677, R²: -0.0058
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10775 | val 0.15415
  Epoch 020 - train 0.11013 | val 0.15349
  Epoch 021 - train 0.10606 | val 0.15184
  Regression -> MSE: 0.000143, MAE: 0.009027, R²: -0.0322
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10123 | val 0.13908
  Epoch 020 - train 0.10177 | val 0.13818
  Epoch 021 - train 0.09862 | val 0.13789
  Regression -> MSE: 0.000227, MAE: 0.010775, R²: -0.0109
  Directional -> Accuracy: 0.4918, MCC: -0.0030, F1: 0.0606

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10526 | val 0.26707
  Epoch 020 - train 0.10505 | val 0.24953
  Epoch 021 - train 0.10576 | val 0.24797
  Regression -> MSE: 0.000367, MAE: 0.015871, R²: -0.0132
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11205 | val 0.12351
  Epoch 020 - train 0.11398 | val 0.12700
  Epoch 021 - train 0.10955 | val 0.12639
  Regression -> MSE: 0.000106, MAE: 0.007934, R²: 0.0143
  Directional -> Accuracy: 0.6286, MCC: 0.2557, F1: 0.6486

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10817 | val 0.23834
  Epoch 020 - train 0.10758 | val 0.25915
  Epoch 021 - train 0.10713 | val 0.26083
  Regression -> MSE: 0.000159, MAE: 0.009616, R²: -0.0171
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11172 | val 0.14843
  Epoch 020 - train 0.10769 | val 0.14671
  Epoch 021 - train 0.11076 | val 0.14543
  Regression -> MSE: 0.000294, MAE: 0.013942, R²: -0.0809
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10633 | val 0.14796
  Epoch 020 - train 0.09841 | val 0.14933
  Epoch 021 - train 0.10091 | val 0.15020
  Regression -> MSE: 0.000154, MAE: 0.009126, R²: -0.0325
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10958 | val 0.15067
  Epoch 020 - train 0.11157 | val 0.15810
  Epoch 021 - train 0.11043 | val 0.15607
  Regression -> MSE: 0.000281, MAE: 0.012101, R²: -0.2434
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11621 | val 0.14681
  Epoch 020 - train 0.11268 | val 0.14504
  Epoch 021 - train 0.11348 | val 0.14485
  Regression -> MSE: 0.000159, MAE: 0.009064, R²: -0.1073
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10178 | val 0.13862
  Epoch 020 - train 0.10597 | val 0.13655
  Epoch 021 - train 0.10247 | val 0.13710
  Regression -> MSE: 0.000166, MAE: 0.010387, R²: -0.0071
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11509 | val 0.13343
  Epoch 020 - train 0.11863 | val 0.13944
  Epoch 021 - train 0.11104 | val 0.14058
  Regression -> MSE: 0.000091, MAE: 0.007367, R²: -0.0687
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10547 | val 0.24183
  Epoch 020 - train 0.11163 | val 0.23728
  Epoch 021 - train 0.10598 | val 0.24751
  Regression -> MSE: 0.000211, MAE: 0.011025, R²: 0.0052
  Directional -> Accuracy: 0.5455, MCC: 0.0787, F1: 0.4643

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.10368 | val 0.09176
  Epoch 020 - train 0.09407 | val 0.08976
  Epoch 030 - train 0.09448 | val 0.09062
  Regression -> MSE: 0.000107, MAE: 0.008203, R²: -0.1637
  Directional -> Accuracy: 0.5893, MCC: 0.2075, F1: 0.5660

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11869 | val 0.08780
  Epoch 020 - train 0.11781 | val 0.08709
  Epoch 021 - train 0.11750 | val 0.08716
  Regression -> MSE: 0.000107, MAE: 0.008922, R²: -0.0369
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11279 | val 0.11789
  Epoch 020 - train 0.11396 | val 0.11943
  Epoch 021 - train 0.11486 | val 0.12146
  Regression -> MSE: 0.000233, MAE: 0.012578, R²: -0.0068
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10767 | val 0.12605
  Epoch 020 - train 0.10331 | val 0.13050
  Epoch 021 - train 0.10516 | val 0.13066
  Regression -> MSE: 0.000184, MAE: 0.008012, R²: -0.1041
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10984 | val 0.09486
  Epoch 020 - train 0.10911 | val 0.09619
  Epoch 021 - train 0.11443 | val 0.09603
  Regression -> MSE: 0.000236, MAE: 0.011862, R²: 0.0019
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10908 | val 0.18279
  Epoch 020 - train 0.10884 | val 0.18592
  Epoch 021 - train 0.10529 | val 0.18663
  Regression -> MSE: 0.000232, MAE: 0.010068, R²: -0.0074
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11898 | val 0.15309
  Epoch 020 - train 0.11338 | val 0.15716
  Epoch 021 - train 0.11165 | val 0.15706
  Regression -> MSE: 0.000147, MAE: 0.008885, R²: -0.0915
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11249 | val 0.14401
  Epoch 020 - train 0.10891 | val 0.15046
  Epoch 021 - train 0.10867 | val 0.15038
  Regression -> MSE: 0.000191, MAE: 0.010421, R²: -0.0119
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10048 | val 0.12819
  Epoch 020 - train 0.10402 | val 0.13084
  Epoch 021 - train 0.09733 | val 0.13012
  Regression -> MSE: 0.000286, MAE: 0.011194, R²: -0.0921
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10176 | val 0.09845
  Epoch 020 - train 0.09325 | val 0.10869
  Epoch 021 - train 0.10803 | val 0.10847
  Regression -> MSE: 0.000170, MAE: 0.010384, R²: -0.0212
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09489 | val 0.14427
  Epoch 020 - train 0.10045 | val 0.14647
  Epoch 021 - train 0.10185 | val 0.14599
  Regression -> MSE: 0.000181, MAE: 0.010341, R²: -0.0066
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10082 | val 0.11074
  Epoch 020 - train 0.10115 | val 0.10958
  Epoch 021 - train 0.10340 | val 0.10927
  Regression -> MSE: 0.000341, MAE: 0.012127, R²: 0.0046
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11324 | val 0.07354
  Epoch 020 - train 0.11045 | val 0.07726
  Epoch 021 - train 0.11168 | val 0.07756
  Regression -> MSE: 0.000116, MAE: 0.008379, R²: -0.1071
  Directional -> Accuracy: 0.4651, MCC: -0.1084, F1: 0.5965

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10783 | val 0.15830
  Epoch 020 - train 0.10354 | val 0.16666
  Epoch 021 - train 0.10348 | val 0.16723
  Regression -> MSE: 0.000220, MAE: 0.011365, R²: -0.0054
  Directional -> Accuracy: 0.4035, MCC: -0.1963, F1: 0.3704

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11057 | val 0.21179
  Epoch 020 - train 0.10200 | val 0.22298
  Epoch 021 - train 0.10086 | val 0.22725
  Regression -> MSE: 0.000080, MAE: 0.006978, R²: -0.0351
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10211 | val 0.08430
  Epoch 020 - train 0.09991 | val 0.08457
  Epoch 021 - train 0.10550 | val 0.08447
  Regression -> MSE: 0.000309, MAE: 0.013772, R²: -0.0037
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11467 | val 0.07203
  Epoch 020 - train 0.11317 | val 0.08268
  Epoch 021 - train 0.11880 | val 0.08356
  Regression -> MSE: 0.000244, MAE: 0.011533, R²: -0.0009
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10089 | val 0.15161
  Epoch 020 - train 0.10319 | val 0.15192
  Epoch 021 - train 0.10143 | val 0.15463
  Regression -> MSE: 0.000084, MAE: 0.007035, R²: -0.0419
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10807 | val 0.13730
  Epoch 020 - train 0.11503 | val 0.18538
  Epoch 021 - train 0.11027 | val 0.18656
  Regression -> MSE: 0.000308, MAE: 0.014460, R²: -0.0052
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10632 | val 0.12644
  Epoch 020 - train 0.09855 | val 0.12711
  Epoch 021 - train 0.10532 | val 0.12641
  Regression -> MSE: 0.000098, MAE: 0.007194, R²: 0.0020
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11662 | val 0.13546
  Epoch 020 - train 0.11863 | val 0.14287
  Epoch 021 - train 0.11395 | val 0.14272
  Regression -> MSE: 0.000174, MAE: 0.009418, R²: -0.0141
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10485 | val 0.19205
  Epoch 020 - train 0.10288 | val 0.19646
  Epoch 021 - train 0.10441 | val 0.19331
  Regression -> MSE: 0.000223, MAE: 0.011679, R²: 0.0008
  Directional -> Accuracy: 0.6429, MCC: 0.2998, F1: 0.6296

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10427 | val 0.15011
  Epoch 020 - train 0.10407 | val 0.16339
  Epoch 021 - train 0.10382 | val 0.16408
  Regression -> MSE: 0.000092, MAE: 0.007616, R²: 0.0063
  Directional -> Accuracy: 0.5614, MCC: 0.1807, F1: 0.6479

[86/88] Processing WFC...


[I 2026-02-24 04:58:43,577] Trial 182 finished with value: -0.011493003663028037 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 6.489559244296672e-05, 'weight_decay': 8.911978916557144e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.16316242202270287, 'early_stopping_min_delta': 0.00948495452124845}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.11101 | val 0.18903
  Regression -> MSE: 0.000251, MAE: 0.012518, R²: -0.0577
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14256 | val 0.18724
  Epoch 020 - train 0.13716 | val 0.18367
  Epoch 021 - train 0.13714 | val 0.18318
  Regression -> MSE: 0.000267, MAE: 0.013167, R²: -0.0792
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13017 | val 0.13106
  Epoch 020 - train 0.13073 | val 0.14487
  Epoch 021 - train 0.13023 | val 0.14539
  Regression -> MSE: 0.000690, MAE: 0.019351, R²: -0.0076
  Directional -> Accuracy: 0.5870, MCC: 0.1236, F1: 0.7246

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.14171 | val 0.22941
  Epoch 020 - train 0.13516 | val 0.22577
  Epoch 021 - train 0.13989 | val 0.22543
  Regression -> MSE: 0.000315, MAE: 0.014541, R²: -0.0161
  Directional -> Accuracy: 0.4255, MCC: -0.1988, F1: 0.5424

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11413 | val 0.22804
  Epoch 020 - train 0.11176 | val 0.23997
  Epoch 021 - train 0.11263 | val 0.24541
  Regression -> MSE: 0.000353, MAE: 0.014641, R²: -0.0109
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13600 | val 0.12847
  Epoch 020 - train 0.13438 | val 0.12627
  Epoch 021 - train 0.12966 | val 0.12613
  Regression -> MSE: 0.000209, MAE: 0.010248, R²: -0.0285
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12841 | val 0.25540
  Epoch 020 - train 0.12603 | val 0.24759
  Epoch 030 - train 0.13491 | val 0.24901
  Regression -> MSE: 0.000564, MAE: 0.018499, R²: -0.0152
  Directional -> Accuracy: 0.4894, MCC: -0.0045, F1: 0.6471

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13942 | val 0.16813
  Epoch 020 - train 0.14111 | val 0.16869
  Epoch 021 - train 0.13706 | val 0.16847
  Regression -> MSE: 0.000245, MAE: 0.011902, R²: 0.0035
  Directional -> Accuracy: 0.5217, MCC: 0.0583, F1: 0.4923

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14426 | val 0.16637
  Epoch 020 - train 0.12685 | val 0.17065
  Epoch 021 - train 0.14183 | val 0.17416
  Regression -> MSE: 0.000607, MAE: 0.019351, R²: -0.0163
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14494 | val 0.16138
  Epoch 020 - train 0.13421 | val 0.16387
  Epoch 021 - train 0.13712 | val 0.16355
  Regression -> MSE: 0.000397, MAE: 0.016019, R²: -0.0355
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13840 | val 0.27909
  Epoch 020 - train 0.13785 | val 0.29580
  Epoch 021 - train 0.13496 | val 0.29760
  Regression -> MSE: 0.000241, MAE: 0.012013, R²: 0.0009
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12762 | val 0.21356
  Epoch 020 - train 0.12460 | val 0.23063
  Epoch 021 - train 0.13011 | val 0.22974
  Regression -> MSE: 0.000313, MAE: 0.013682, R²: -0.0081
  Directional -> Accuracy: 0.4200, MCC: -0.2368, F1: 0.1714

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14632 | val 0.16105
  Epoch 020 - train 0.14730 | val 0.16295
  Epoch 021 - train 0.13498 | val 0.16451
  Regression -> MSE: 0.000675, MAE: 0.019427, R²: 0.0037
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.5672

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.14105 | val 0.19729
  Epoch 020 - train 0.12951 | val 0.20748
  Epoch 021 - train 0.13328 | val 0.20621
  Regression -> MSE: 0.000137, MAE: 0.009084, R²: 0.0069
  Directional -> Accuracy: 0.5814, MCC: 0.1725, F1: 0.5714

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.13060 | val 0.16772
  Epoch 020 - train 0.12336 | val 0.17656
  Epoch 021 - train 0.12131 | val 0.17712
  Regression -> MSE: 0.000226, MAE: 0.010714, R²: -0.0058
  Directional -> Accuracy: 0.5574, MCC: 0.1199, F1: 0.6400

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13628 | val 0.27440
  Epoch 020 - train 0.13595 | val 0.27557
  Epoch 021 - train 0.12930 | val 0.27692
  Regression -> MSE: 0.000362, MAE: 0.016043, R²: -0.0004
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14271 | val 0.14187
  Epoch 020 - train 0.14171 | val 0.14352
  Epoch 021 - train 0.13416 | val 0.14354
  Regression -> MSE: 0.000111, MAE: 0.007971, R²: -0.0290
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13429 | val 0.27452
  Epoch 020 - train 0.13770 | val 0.29801
  Epoch 021 - train 0.14214 | val 0.30071
  Regression -> MSE: 0.000153, MAE: 0.009481, R²: 0.0167
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13746 | val 0.16958
  Epoch 020 - train 0.14060 | val 0.16722
  Epoch 021 - train 0.14257 | val 0.16529
  Regression -> MSE: 0.000300, MAE: 0.014232, R²: -0.1032
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12599 | val 0.17836
  Epoch 020 - train 0.12452 | val 0.17595
  Epoch 021 - train 0.12096 | val 0.17588
  Regression -> MSE: 0.000153, MAE: 0.008720, R²: -0.0240
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13903 | val 0.19315
  Epoch 020 - train 0.14157 | val 0.18928
  Epoch 021 - train 0.13577 | val 0.18908
  Regression -> MSE: 0.000263, MAE: 0.011631, R²: -0.1636
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13023 | val 0.16532
  Epoch 020 - train 0.12850 | val 0.16873
  Epoch 021 - train 0.13074 | val 0.16809
  Regression -> MSE: 0.000148, MAE: 0.008605, R²: -0.0324
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13554 | val 0.16416
  Epoch 020 - train 0.13297 | val 0.16128
  Epoch 021 - train 0.13914 | val 0.16124
  Regression -> MSE: 0.000169, MAE: 0.010257, R²: -0.0225
  Directional -> Accuracy: 0.4545, MCC: -0.1718, F1: 0.6170

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.15758 | val 0.15421
  Epoch 020 - train 0.14105 | val 0.15552
  Epoch 021 - train 0.14341 | val 0.15562
  Regression -> MSE: 0.000091, MAE: 0.007354, R²: -0.0691
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14734 | val 0.17122
  Epoch 020 - train 0.13535 | val 0.17968
  Epoch 021 - train 0.13612 | val 0.17916
  Regression -> MSE: 0.000217, MAE: 0.011019, R²: -0.0266
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13106 | val 0.10985
  Epoch 020 - train 0.12318 | val 0.10672
  Epoch 028 - train 0.12083 | val 0.10720
  Regression -> MSE: 0.000105, MAE: 0.008235, R²: -0.1420
  Directional -> Accuracy: 0.5000, MCC: 0.0684, F1: 0.3636

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14136 | val 0.10557
  Epoch 020 - train 0.13197 | val 0.10605
  Epoch 021 - train 0.14191 | val 0.10591
  Regression -> MSE: 0.000108, MAE: 0.008964, R²: -0.0440
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14853 | val 0.13533
  Epoch 020 - train 0.14586 | val 0.14279
  Epoch 021 - train 0.14176 | val 0.14374
  Regression -> MSE: 0.000233, MAE: 0.012610, R²: -0.0055
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13469 | val 0.16091
  Epoch 020 - train 0.12664 | val 0.16004
  Epoch 021 - train 0.13211 | val 0.15999
  Regression -> MSE: 0.000170, MAE: 0.007806, R²: -0.0228
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13036 | val 0.11463
  Epoch 020 - train 0.14003 | val 0.11486
  Epoch 021 - train 0.14340 | val 0.11501
  Regression -> MSE: 0.000236, MAE: 0.011854, R²: 0.0023
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13159 | val 0.23441
  Epoch 020 - train 0.13278 | val 0.25030
  Epoch 021 - train 0.13316 | val 0.24983
  Regression -> MSE: 0.000232, MAE: 0.010013, R²: -0.0084
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14032 | val 0.16566
  Epoch 020 - train 0.13636 | val 0.16807
  Epoch 021 - train 0.13805 | val 0.16733
  Regression -> MSE: 0.000135, MAE: 0.008245, R²: -0.0008
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13955 | val 0.17393
  Epoch 020 - train 0.13347 | val 0.17556
  Epoch 021 - train 0.13121 | val 0.17674
  Regression -> MSE: 0.000190, MAE: 0.010321, R²: -0.0086
  Directional -> Accuracy: 0.5600, MCC: 0.1048, F1: 0.7027

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12724 | val 0.16561
  Epoch 020 - train 0.12221 | val 0.16816
  Epoch 021 - train 0.12265 | val 0.16958
  Regression -> MSE: 0.000276, MAE: 0.010846, R²: -0.0547
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12614 | val 0.11396
  Epoch 020 - train 0.12685 | val 0.12586
  Epoch 021 - train 0.12252 | val 0.12746
  Regression -> MSE: 0.000166, MAE: 0.010347, R²: 0.0038
  Directional -> Accuracy: 0.5526, MCC: 0.1195, F1: 0.6383

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14148 | val 0.13268
  Epoch 020 - train 0.12391 | val 0.13788
  Epoch 021 - train 0.12454 | val 0.13811
  Regression -> MSE: 0.000181, MAE: 0.010305, R²: -0.0041
  Directional -> Accuracy: 0.4773, MCC: -0.0379, F1: 0.5106

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13322 | val 0.12872
  Epoch 020 - train 0.13264 | val 0.12969
  Epoch 021 - train 0.13094 | val 0.13013
  Regression -> MSE: 0.000345, MAE: 0.011799, R²: -0.0065
  Directional -> Accuracy: 0.5970, MCC: 0.1613, F1: 0.7327

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12710 | val 0.08633
  Epoch 020 - train 0.13702 | val 0.08871
  Epoch 021 - train 0.14018 | val 0.08859
  Regression -> MSE: 0.000113, MAE: 0.008322, R²: -0.0788
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14025 | val 0.18886
  Epoch 020 - train 0.13035 | val 0.19445
  Epoch 021 - train 0.13413 | val 0.19466
  Regression -> MSE: 0.000219, MAE: 0.011325, R²: -0.0018
  Directional -> Accuracy: 0.5263, MCC: 0.0181, F1: 0.1818

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13662 | val 0.24272
  Epoch 020 - train 0.13093 | val 0.24803
  Epoch 021 - train 0.12990 | val 0.24944
  Regression -> MSE: 0.000082, MAE: 0.007041, R²: -0.0495
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13251 | val 0.11061
  Epoch 020 - train 0.13342 | val 0.11746
  Epoch 021 - train 0.13181 | val 0.11694
  Regression -> MSE: 0.000328, MAE: 0.015018, R²: -0.0675
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14405 | val 0.08496
  Epoch 020 - train 0.13194 | val 0.09161
  Epoch 021 - train 0.14508 | val 0.09215
  Regression -> MSE: 0.000252, MAE: 0.011497, R²: -0.0352
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12652 | val 0.15415
  Epoch 020 - train 0.12463 | val 0.15368
  Epoch 021 - train 0.12344 | val 0.15358
  Regression -> MSE: 0.000081, MAE: 0.007072, R²: -0.0009
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13654 | val 0.17215
  Epoch 020 - train 0.12941 | val 0.20438
  Epoch 021 - train 0.13661 | val 0.20411
  Regression -> MSE: 0.000310, MAE: 0.014525, R²: -0.0114
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14386 | val 0.14876
  Epoch 020 - train 0.13160 | val 0.15246
  Epoch 021 - train 0.14119 | val 0.15196
  Regression -> MSE: 0.000098, MAE: 0.007262, R²: 0.0066
  Directional -> Accuracy: 0.5227, MCC: 0.0335, F1: 0.5714

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14838 | val 0.16032
  Epoch 020 - train 0.14307 | val 0.16506
  Epoch 021 - train 0.13864 | val 0.16555
  Regression -> MSE: 0.000173, MAE: 0.009987, R²: -0.0091
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12806 | val 0.15942
  Epoch 020 - train 0.12512 | val 0.17538
  Epoch 021 - train 0.12798 | val 0.17757
  Regression -> MSE: 0.000223, MAE: 0.011722, R²: -0.0014
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12989 | val 0.18381
  Epoch 020 - train 0.13040 | val 0.18091
  Epoch 021 - train 0.12646 | val 0.18227
  Regression -> MSE: 0.000092, MAE: 0.007662, R²: 0.0053
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...


[I 2026-02-24 05:02:55,001] Trial 183 finished with value: -0.011447081168334284 and parameters: {'feature_set': 'base', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 4.02870379578935e-05, 'weight_decay': 7.003828902278291e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.20191206761470293, 'early_stopping_min_delta': 0.009730490135565283}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.14213 | val 0.21387
  Regression -> MSE: 0.000237, MAE: 0.012364, R²: 0.0016
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15860 | val 0.19935
  Epoch 020 - train 0.15935 | val 0.20090
  Epoch 024 - train 0.16053 | val 0.20183
  Regression -> MSE: 0.000250, MAE: 0.012681, R²: -0.0087
  Directional -> Accuracy: 0.4416, MCC: -0.0825, F1: 0.5376

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.15527 | val 0.16248
  Epoch 020 - train 0.16319 | val 0.15702
  Epoch 021 - train 0.15580 | val 0.15748
  Regression -> MSE: 0.000685, MAE: 0.019354, R²: -0.0002
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16272 | val 0.24785
  Epoch 020 - train 0.16836 | val 0.24738
  Epoch 030 - train 0.16137 | val 0.24692
  Regression -> MSE: 0.000307, MAE: 0.014403, R²: 0.0108
  Directional -> Accuracy: 0.5319, MCC: 0.0135, F1: 0.6857

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13668 | val 0.15281
  Epoch 020 - train 0.12979 | val 0.17603
  Epoch 021 - train 0.13214 | val 0.18343
  Regression -> MSE: 0.000350, MAE: 0.014580, R²: -0.0023
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.17632 | val 0.18491
  Epoch 020 - train 0.17518 | val 0.18151
  Epoch 021 - train 0.16940 | val 0.18103
  Regression -> MSE: 0.000206, MAE: 0.010438, R²: -0.0097
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15585 | val 0.29637
  Epoch 020 - train 0.14680 | val 0.31444
  Epoch 021 - train 0.16055 | val 0.31583
  Regression -> MSE: 0.000575, MAE: 0.018493, R²: -0.0351
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.16493 | val 0.19588
  Epoch 020 - train 0.17110 | val 0.19686
  Epoch 021 - train 0.15280 | val 0.19710
  Regression -> MSE: 0.000250, MAE: 0.012500, R²: -0.0169
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.16322 | val 0.18188
  Epoch 020 - train 0.15246 | val 0.17796
  Epoch 030 - train 0.16499 | val 0.18069
  Regression -> MSE: 0.000599, MAE: 0.019203, R²: -0.0029
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15987 | val 0.18635
  Epoch 020 - train 0.14938 | val 0.19076
  Epoch 021 - train 0.15934 | val 0.19055
  Regression -> MSE: 0.000407, MAE: 0.016184, R²: -0.0607
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15680 | val 0.27105
  Epoch 020 - train 0.15549 | val 0.27381
  Epoch 021 - train 0.15488 | val 0.27522
  Regression -> MSE: 0.000242, MAE: 0.011846, R²: -0.0022
  Directional -> Accuracy: 0.3857, MCC: -0.2082, F1: 0.5474

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15635 | val 0.25992
  Epoch 020 - train 0.15564 | val 0.27561
  Epoch 021 - train 0.15291 | val 0.27621
  Regression -> MSE: 0.000317, MAE: 0.013568, R²: -0.0186
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.18698 | val 0.19613
  Epoch 020 - train 0.17004 | val 0.19780
  Epoch 021 - train 0.17134 | val 0.19813
  Regression -> MSE: 0.000672, MAE: 0.019434, R²: 0.0077
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.15348 | val 0.15964
  Epoch 020 - train 0.15764 | val 0.18097
  Epoch 021 - train 0.14824 | val 0.18321
  Regression -> MSE: 0.000142, MAE: 0.009356, R²: -0.0261
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15152 | val 0.20647
  Epoch 020 - train 0.14284 | val 0.20568
  Epoch 021 - train 0.14418 | val 0.20537
  Regression -> MSE: 0.000228, MAE: 0.010765, R²: -0.0126
  Directional -> Accuracy: 0.5246, MCC: 0.0539, F1: 0.4727

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15837 | val 0.39825
  Epoch 020 - train 0.15710 | val 0.41887
  Epoch 021 - train 0.16510 | val 0.41385
  Regression -> MSE: 0.000364, MAE: 0.016007, R²: -0.0063
  Directional -> Accuracy: 0.5192, MCC: 0.0127, F1: 0.3902

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.17172 | val 0.16641
  Epoch 020 - train 0.16460 | val 0.17020
  Epoch 021 - train 0.16202 | val 0.16949
  Regression -> MSE: 0.000108, MAE: 0.007937, R²: -0.0044
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15008 | val 0.29062
  Epoch 020 - train 0.16033 | val 0.29644
  Epoch 021 - train 0.16359 | val 0.29603
  Regression -> MSE: 0.000155, MAE: 0.009597, R²: 0.0074
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.17050 | val 0.16505
  Epoch 020 - train 0.16622 | val 0.17197
  Epoch 021 - train 0.16167 | val 0.17239
  Regression -> MSE: 0.000276, MAE: 0.013262, R²: -0.0132
  Directional -> Accuracy: 0.5921, MCC: -0.0933, F1: 0.7438

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.15739 | val 0.20815
  Epoch 020 - train 0.14672 | val 0.20901
  Epoch 021 - train 0.15288 | val 0.20867
  Regression -> MSE: 0.000169, MAE: 0.009211, R²: -0.1280
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16232 | val 0.22325
  Epoch 020 - train 0.17347 | val 0.22509
  Epoch 021 - train 0.16475 | val 0.22506
  Regression -> MSE: 0.000251, MAE: 0.011284, R²: -0.1115
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16563 | val 0.19537
  Epoch 020 - train 0.15130 | val 0.20199
  Epoch 021 - train 0.15979 | val 0.20216
  Regression -> MSE: 0.000154, MAE: 0.008882, R²: -0.0746
  Directional -> Accuracy: 0.4167, MCC: 0.1615, F1: 0.1250

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.15643 | val 0.18222
  Epoch 020 - train 0.16091 | val 0.18143
  Epoch 021 - train 0.15273 | val 0.18151
  Regression -> MSE: 0.000171, MAE: 0.010182, R²: -0.0335
  Directional -> Accuracy: 0.6061, MCC: 0.2137, F1: 0.5806

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.17382 | val 0.18349
  Epoch 020 - train 0.17095 | val 0.18205
  Epoch 021 - train 0.17657 | val 0.18168
  Regression -> MSE: 0.000086, MAE: 0.007096, R²: -0.0121
  Directional -> Accuracy: 0.5862, MCC: 0.1522, F1: 0.7333

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16020 | val 0.19712
  Epoch 020 - train 0.15918 | val 0.19237
  Epoch 021 - train 0.16083 | val 0.19203
  Regression -> MSE: 0.000213, MAE: 0.011115, R²: -0.0035
  Directional -> Accuracy: 0.4545, MCC: -0.1318, F1: 0.6250

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13901 | val 0.12640
  Epoch 020 - train 0.14172 | val 0.12419
  Epoch 027 - train 0.14266 | val 0.12650
  Regression -> MSE: 0.000092, MAE: 0.007829, R²: -0.0015
  Directional -> Accuracy: 0.5714, MCC: 0.2023, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17847 | val 0.12155
  Epoch 020 - train 0.15697 | val 0.12309
  Epoch 021 - train 0.16293 | val 0.12305
  Regression -> MSE: 0.000105, MAE: 0.008820, R²: -0.0223
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16469 | val 0.16002
  Epoch 020 - train 0.17762 | val 0.16331
  Epoch 021 - train 0.16973 | val 0.16424
  Regression -> MSE: 0.000239, MAE: 0.012817, R²: -0.0320
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.16255 | val 0.18200
  Epoch 020 - train 0.15663 | val 0.18231
  Epoch 021 - train 0.15697 | val 0.18230
  Regression -> MSE: 0.000187, MAE: 0.008093, R²: -0.1229
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.18091 | val 0.13294
  Epoch 020 - train 0.16775 | val 0.13607
  Epoch 021 - train 0.15934 | val 0.13596
  Regression -> MSE: 0.000239, MAE: 0.011920, R²: -0.0105
  Directional -> Accuracy: 0.4634, MCC: -0.0304, F1: 0.2143

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.18049 | val 0.25033
  Epoch 020 - train 0.16384 | val 0.24928
  Epoch 021 - train 0.15516 | val 0.24877
  Regression -> MSE: 0.000232, MAE: 0.010040, R²: -0.0069
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.17668 | val 0.20542
  Epoch 020 - train 0.17140 | val 0.20106
  Epoch 021 - train 0.17371 | val 0.20010
  Regression -> MSE: 0.000144, MAE: 0.008723, R²: -0.0654
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.17149 | val 0.20408
  Epoch 020 - train 0.16438 | val 0.20391
  Epoch 021 - train 0.15894 | val 0.20362
  Regression -> MSE: 0.000188, MAE: 0.010395, R²: 0.0005
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14585 | val 0.17580
  Epoch 020 - train 0.14742 | val 0.17783
  Epoch 021 - train 0.14405 | val 0.18013
  Regression -> MSE: 0.000268, MAE: 0.010590, R²: -0.0244
  Directional -> Accuracy: 0.5616, MCC: 0.0209, F1: 0.7143

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14303 | val 0.13381
  Epoch 020 - train 0.15103 | val 0.13204
  Epoch 021 - train 0.15650 | val 0.13270
  Regression -> MSE: 0.000168, MAE: 0.010370, R²: -0.0051
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14025 | val 0.16798
  Epoch 020 - train 0.13908 | val 0.16976
  Epoch 021 - train 0.15445 | val 0.17036
  Regression -> MSE: 0.000190, MAE: 0.010687, R²: -0.0541
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14915 | val 0.14937
  Epoch 020 - train 0.14901 | val 0.14975
  Epoch 021 - train 0.15503 | val 0.14988
  Regression -> MSE: 0.000340, MAE: 0.011825, R²: 0.0074
  Directional -> Accuracy: 0.4627, MCC: 0.0930, F1: 0.1429

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.17608 | val 0.09506
  Epoch 020 - train 0.16849 | val 0.09352
  Epoch 021 - train 0.16639 | val 0.09337
  Regression -> MSE: 0.000116, MAE: 0.008379, R²: -0.1008
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17128 | val 0.22206
  Epoch 020 - train 0.16413 | val 0.22289
  Epoch 021 - train 0.15675 | val 0.22294
  Regression -> MSE: 0.000221, MAE: 0.011391, R²: -0.0105
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15339 | val 0.30921
  Epoch 020 - train 0.16705 | val 0.32048
  Epoch 021 - train 0.15857 | val 0.32185
  Regression -> MSE: 0.000084, MAE: 0.007181, R²: -0.0847
  Directional -> Accuracy: 0.4043, MCC: -0.0615, F1: 0.2632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.16251 | val 0.13678
  Epoch 020 - train 0.16348 | val 0.14040
  Epoch 021 - train 0.15938 | val 0.14099
  Regression -> MSE: 0.000340, MAE: 0.015388, R²: -0.1068
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17614 | val 0.10127
  Epoch 020 - train 0.17318 | val 0.11691
  Epoch 021 - train 0.15936 | val 0.11806
  Regression -> MSE: 0.000257, MAE: 0.011504, R²: -0.0542
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16199 | val 0.19647
  Epoch 020 - train 0.15277 | val 0.19468
  Epoch 021 - train 0.15310 | val 0.19468
  Regression -> MSE: 0.000084, MAE: 0.007033, R²: -0.0359
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16629 | val 0.19617
  Epoch 020 - train 0.16631 | val 0.20674
  Epoch 021 - train 0.16239 | val 0.20744
  Regression -> MSE: 0.000315, MAE: 0.014564, R²: -0.0267
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.17517 | val 0.18885
  Epoch 020 - train 0.15549 | val 0.18596
  Epoch 021 - train 0.15535 | val 0.18568
  Regression -> MSE: 0.000104, MAE: 0.007111, R²: -0.0547
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17712 | val 0.18672
  Epoch 020 - train 0.17204 | val 0.18449
  Epoch 021 - train 0.17634 | val 0.18459
  Regression -> MSE: 0.000173, MAE: 0.009460, R²: -0.0055
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.15986 | val 0.28470
  Epoch 020 - train 0.15782 | val 0.28563
  Epoch 021 - train 0.16852 | val 0.28901
  Regression -> MSE: 0.000241, MAE: 0.012105, R²: -0.0789
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.17353 | val 0.16824
  Epoch 020 - train 0.15400 | val 0.17095
  Epoch 021 - train 0.16098 | val 0.17141
  Regression -> MSE: 0.000095, MAE: 0.007696, R²: -0.0268

[I 2026-02-24 05:07:07,862] Trial 184 finished with value: -0.011457919543674491 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 1.8035665475153643e-05, 'weight_decay': 5.791776920586868e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.24342850027698676, 'early_stopping_min_delta': 0.0093392629523214}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.15457 | val 0.25063
  Regression -> MSE: 0.000243, MAE: 0.012404, R²: -0.0250
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.44869 | val 0.84645
  Epoch 020 - train 0.42941 | val 0.82072
  Epoch 030 - train 0.44462 | val 0.81815
  Regression -> MSE: 0.000270, MAE: 0.012972, R²: -0.0920
  Directional -> Accuracy: 0.5195, MCC: 0.0905, F1: 0.5934

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.45656 | val 0.49847
  Epoch 020 - train 0.45253 | val 0.55405
  Epoch 021 - train 0.44031 | val 0.55401
  Regression -> MSE: 0.000699, MAE: 0.019600, R²: -0.0215
  Directional -> Accuracy: 0.5652, MCC: 0.0510, F1: 0.6970

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.47446 | val 1.04266
  Epoch 020 - train 0.45606 | val 1.05446
  Epoch 021 - train 0.46436 | val 1.05429
  Regression -> MSE: 0.000310, MAE: 0.014385, R²: -0.0008
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.38655 | val 1.07227
  Epoch 020 - train 0.38228 | val 1.19092
  Epoch 021 - train 0.38677 | val 1.20687
  Regression -> MSE: 0.000350, MAE: 0.014598, R²: -0.0022
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.45757 | val 0.45982
  Epoch 020 - train 0.41883 | val 0.44322
  Epoch 030 - train 0.41331 | val 0.45610
  Regression -> MSE: 0.000204, MAE: 0.010198, R²: 0.0005
  Directional -> Accuracy: 0.4510, MCC: -0.2223, F1: 0.6111

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.47559 | val 1.21194
  Epoch 020 - train 0.46663 | val 1.23405
  Epoch 030 - train 0.41485 | val 1.28639
  Regression -> MSE: 0.000558, MAE: 0.018274, R²: -0.0057
  Directional -> Accuracy: 0.5745, MCC: 0.2667, F1: 0.2308

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.48010 | val 0.71227
  Epoch 020 - train 0.46913 | val 0.69748
  Epoch 025 - train 0.44838 | val 0.69374
  Regression -> MSE: 0.000247, MAE: 0.012249, R²: -0.0054
  Directional -> Accuracy: 0.4058, MCC: -0.0331, F1: 0.5684

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.48118 | val 0.78229
  Epoch 020 - train 0.46123 | val 0.99606
  Epoch 021 - train 0.44630 | val 1.02169
  Regression -> MSE: 0.000639, MAE: 0.020069, R²: -0.0694
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.46293 | val 0.62606
  Epoch 020 - train 0.42673 | val 0.64243
  Epoch 027 - train 0.42918 | val 0.64782
  Regression -> MSE: 0.000384, MAE: 0.015827, R²: -0.0021
  Directional -> Accuracy: 0.5510, MCC: 0.1907, F1: 0.6333

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.48411 | val 0.75548
  Epoch 020 - train 0.47563 | val 0.89507
  Epoch 025 - train 0.45422 | val 0.87746
  Regression -> MSE: 0.000242, MAE: 0.012112, R²: -0.0003
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.43369 | val 0.93578
  Epoch 020 - train 0.41095 | val 1.19499
  Epoch 021 - train 0.44415 | val 1.21035
  Regression -> MSE: 0.000320, MAE: 0.013591, R²: -0.0277
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.49475 | val 0.71650
  Epoch 020 - train 0.47705 | val 0.87748
  Epoch 021 - train 0.45128 | val 0.87630
  Regression -> MSE: 0.000684, MAE: 0.019749, R²: -0.0104
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.46963 | val 0.60685
  Epoch 020 - train 0.44759 | val 0.76082
  Epoch 021 - train 0.44620 | val 0.75839
  Regression -> MSE: 0.000141, MAE: 0.009346, R²: -0.0221
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.44245 | val 0.76379
  Epoch 020 - train 0.43392 | val 0.75531
  Epoch 021 - train 0.43681 | val 0.75541
  Regression -> MSE: 0.000225, MAE: 0.010746, R²: -0.0023
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.44393 | val 1.52177
  Epoch 020 - train 0.44744 | val 1.60457
  Epoch 021 - train 0.44735 | val 1.60491
  Regression -> MSE: 0.000367, MAE: 0.015948, R²: -0.0127
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.48451 | val 0.52128
  Epoch 020 - train 0.45703 | val 0.49648
  Epoch 030 - train 0.42988 | val 0.48326
  Regression -> MSE: 0.000108, MAE: 0.007974, R²: 0.0024
  Directional -> Accuracy: 0.6000, MCC: 0.1814, F1: 0.6818

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.43201 | val 1.20317
  Epoch 020 - train 0.43492 | val 1.24483
  Epoch 021 - train 0.44250 | val 1.25040
  Regression -> MSE: 0.000157, MAE: 0.009817, R²: -0.0060
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.48873 | val 0.55436
  Epoch 020 - train 0.47524 | val 0.58803
  Epoch 021 - train 0.48563 | val 0.58617
  Regression -> MSE: 0.000273, MAE: 0.013079, R²: -0.0040
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.38746 | val 0.76193
  Epoch 020 - train 0.37150 | val 0.75747
  Epoch 030 - train 0.35878 | val 0.75461
  Regression -> MSE: 0.000289, MAE: 0.013609, R²: -0.9343
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.45507 | val 1.00417
  Epoch 020 - train 0.41290 | val 1.08427
  Epoch 026 - train 0.47228 | val 1.09775
  Regression -> MSE: 0.000289, MAE: 0.012425, R²: -0.2756
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.51562 | val 0.75984
  Epoch 020 - train 0.43507 | val 0.75077
  Epoch 030 - train 0.42013 | val 0.75583
  Regression -> MSE: 0.000203, MAE: 0.011043, R²: -0.4158
  Directional -> Accuracy: 0.3958, MCC: 0.1130, F1: 0.0645

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.45194 | val 0.58995
  Epoch 020 - train 0.45191 | val 0.60419
  Epoch 021 - train 0.43652 | val 0.60637
  Regression -> MSE: 0.000176, MAE: 0.010254, R²: -0.0680
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.51908 | val 0.70500
  Epoch 020 - train 0.46870 | val 0.71994
  Epoch 021 - train 0.47356 | val 0.71934
  Regression -> MSE: 0.000089, MAE: 0.007246, R²: -0.0411
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.43513 | val 1.02756
  Epoch 020 - train 0.45062 | val 1.28041
  Epoch 021 - train 0.45133 | val 1.25373
  Regression -> MSE: 0.000214, MAE: 0.011037, R²: -0.0101
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.41344 | val 0.35316
  Epoch 020 - train 0.41016 | val 0.34740
  Epoch 030 - train 0.37730 | val 0.33599
  Regression -> MSE: 0.000108, MAE: 0.008501, R²: -0.1693
  Directional -> Accuracy: 0.5536, MCC: 0.1566, F1: 0.4898

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.46665 | val 0.37961
  Epoch 020 - train 0.48992 | val 0.37461
  Epoch 021 - train 0.49383 | val 0.37056
  Regression -> MSE: 0.000113, MAE: 0.009134, R²: -0.0996
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.45144 | val 0.48766
  Epoch 020 - train 0.49438 | val 0.49562
  Epoch 021 - train 0.47142 | val 0.49588
  Regression -> MSE: 0.000242, MAE: 0.012896, R²: -0.0453
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.47148 | val 0.66855
  Epoch 020 - train 0.43865 | val 0.67096
  Epoch 021 - train 0.42952 | val 0.67247
  Regression -> MSE: 0.000172, MAE: 0.007862, R²: -0.0354
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.54561 | val 0.28769
  Epoch 020 - train 0.48093 | val 0.29528
  Epoch 021 - train 0.48266 | val 0.29585
  Regression -> MSE: 0.000239, MAE: 0.011945, R²: -0.0105
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.49051 | val 1.07183
  Epoch 020 - train 0.50955 | val 1.21894
  Epoch 021 - train 0.47311 | val 1.22851
  Regression -> MSE: 0.000231, MAE: 0.009869, R²: -0.0017
  Directional -> Accuracy: 0.4651, MCC: -0.0893, F1: 0.3030

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.49300 | val 0.68628
  Epoch 020 - train 0.44520 | val 0.71167
  Epoch 021 - train 0.45573 | val 0.71045
  Regression -> MSE: 0.000135, MAE: 0.008213, R²: -0.0018
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.45868 | val 0.76088
  Epoch 020 - train 0.45537 | val 0.81535
  Epoch 021 - train 0.44453 | val 0.81528
  Regression -> MSE: 0.000189, MAE: 0.010421, R²: -0.0022
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.41848 | val 0.61674
  Epoch 020 - train 0.39610 | val 0.60832
  Epoch 030 - train 0.39071 | val 0.61181
  Regression -> MSE: 0.000350, MAE: 0.012844, R²: -0.3369
  Directional -> Accuracy: 0.4521, MCC: 0.1041, F1: 0.0476

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.49914 | val 0.36503
  Epoch 020 - train 0.41540 | val 0.41609
  Epoch 021 - train 0.42040 | val 0.43174
  Regression -> MSE: 0.000169, MAE: 0.010384, R²: -0.0162
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.43579 | val 0.57203
  Epoch 020 - train 0.40740 | val 0.63580
  Epoch 021 - train 0.40480 | val 0.63361
  Regression -> MSE: 0.000181, MAE: 0.010377, R²: -0.0072
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.48146 | val 0.45702
  Epoch 020 - train 0.41967 | val 0.46391
  Epoch 021 - train 0.43745 | val 0.46433
  Regression -> MSE: 0.000348, MAE: 0.011741, R²: -0.0165
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.52350 | val 0.30769
  Epoch 020 - train 0.48863 | val 0.31708
  Epoch 021 - train 0.47639 | val 0.31380
  Regression -> MSE: 0.000136, MAE: 0.008687, R²: -0.2933
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.47186 | val 0.87383
  Epoch 020 - train 0.41379 | val 0.96744
  Epoch 028 - train 0.42524 | val 1.00513
  Regression -> MSE: 0.000229, MAE: 0.011680, R²: -0.0482
  Directional -> Accuracy: 0.5263, MCC: 0.1078, F1: 0.6301

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.45991 | val 1.21259
  Epoch 020 - train 0.41774 | val 1.42268
  Epoch 028 - train 0.43439 | val 1.51498
  Regression -> MSE: 0.000093, MAE: 0.007545, R²: -0.1937
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.46911 | val 0.35815
  Epoch 020 - train 0.47997 | val 0.35774
  Epoch 021 - train 0.45216 | val 0.35532
  Regression -> MSE: 0.000342, MAE: 0.015423, R²: -0.1101
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.45420 | val 0.20852
  Epoch 020 - train 0.42978 | val 0.21275
  Epoch 021 - train 0.46670 | val 0.21628
  Regression -> MSE: 0.000253, MAE: 0.011452, R²: -0.0391
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.43452 | val 0.65209
  Epoch 020 - train 0.42385 | val 0.67280
  Epoch 025 - train 0.41388 | val 0.67322
  Regression -> MSE: 0.000083, MAE: 0.007224, R²: -0.0243
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.49591 | val 0.62104
  Epoch 020 - train 0.44929 | val 0.98220
  Epoch 030 - train 0.43882 | val 1.02262
  Regression -> MSE: 0.000314, MAE: 0.014625, R²: -0.0243
  Directional -> Accuracy: 0.4255, MCC: -0.1515, F1: 0.3077

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.45179 | val 0.60763
  Epoch 020 - train 0.44133 | val 0.63305
  Epoch 021 - train 0.42461 | val 0.63366
  Regression -> MSE: 0.000100, MAE: 0.007125, R²: -0.0137
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.51626 | val 0.79276
  Epoch 020 - train 0.46401 | val 0.84197
  Epoch 021 - train 0.49226 | val 0.85105
  Regression -> MSE: 0.000172, MAE: 0.009685, R²: -0.0013
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.43585 | val 0.63575
  Epoch 020 - train 0.42110 | val 0.69505
  Epoch 021 - train 0.41899 | val 0.69214
  Regression -> MSE: 0.000223, MAE: 0.011765, R²: 0.0005
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...

[I 2026-02-24 05:10:20,862] Trial 185 finished with value: -0.011700241121023254 and parameters: {'feature_set': 'emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 5.437963563829897e-05, 'weight_decay': 1.2048640499795876e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 1.8989667857738666, 'early_stopping_min_delta': 0.009481284133354362}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.47833 | val 1.03624
  Epoch 021 - train 0.47757 | val 1.04177
  Regression -> MSE: 0.000242, MAE: 0.012342, R²: -0.0198
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10439 | val 0.13144
  Epoch 016 - train 0.10152 | val 0.13326
  Regression -> MSE: 0.000256, MAE: 0.012883, R²: -0.0351
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10193 | val 0.09435
  Epoch 016 - train 0.09933 | val 0.10398
  Regression -> MSE: 0.000685, MAE: 0.019391, R²: -0.0007
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10824 | val 0.16087
  Epoch 016 - train 0.10459 | val 0.16096
  Regression -> MSE: 0.000314, MAE: 0.014438, R²: -0.0122
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09744 | val 0.08534
  Epoch 016 - train 0.09358 | val 0.08621
  Regression -> MSE: 0.000351, MAE: 0.014567, R²: -0.0038
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10326 | val 0.10267
  Epoch 016 - train 0.10401 | val 0.10307
  Regression -> MSE: 0.000206, MAE: 0.010325, R²: -0.0094
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09628 | val 0.19001
  Epoch 016 - train 0.10067 | val 0.19549
  Regression -> MSE: 0.000590, MAE: 0.018764, R²: -0.0628
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10721 | val 0.12208
  Epoch 016 - train 0.11019 | val 0.12338
  Regression -> MSE: 0.000247, MAE: 0.012283, R²: -0.0045
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11221 | val 0.11524
  Epoch 016 - train 0.11195 | val 0.10928
  Regression -> MSE: 0.000602, MAE: 0.019298, R²: -0.0083
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10355 | val 0.12745
  Epoch 016 - train 0.09573 | val 0.12612
  Regression -> MSE: 0.000384, MAE: 0.016161, R²: -0.0001
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10369 | val 0.13003
  Epoch 016 - train 0.10367 | val 0.13027
  Regression -> MSE: 0.000244, MAE: 0.012223, R²: -0.0097
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10192 | val 0.15117
  Epoch 016 - train 0.10172 | val 0.16435
  Regression -> MSE: 0.000312, MAE: 0.013831, R²: -0.0033
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10836 | val 0.11973
  Epoch 016 - train 0.10531 | val 0.12391
  Regression -> MSE: 0.000681, MAE: 0.019696, R²: -0.0057
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10708 | val 0.10364
  Epoch 016 - train 0.10511 | val 0.12703
  Regression -> MSE: 0.000146, MAE: 0.009547, R²: -0.0562
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10156 | val 0.12685
  Epoch 016 - train 0.09629 | val 0.12814
  Regression -> MSE: 0.000227, MAE: 0.010743, R²: -0.0100
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10058 | val 0.20499
  Epoch 016 - train 0.10213 | val 0.20975
  Regression -> MSE: 0.000362, MAE: 0.016091, R²: -0.0000
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11336 | val 0.10721
  Epoch 016 - train 0.11192 | val 0.10786
  Regression -> MSE: 0.000111, MAE: 0.007959, R²: -0.0262
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10371 | val 0.19587
  Epoch 016 - train 0.10353 | val 0.20863
  Regression -> MSE: 0.000159, MAE: 0.010041, R²: -0.0210
  Directional -> Accuracy: 0.6271, MCC: 0.1188, F1: 0.7442

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10481 | val 0.12436
  Epoch 016 - train 0.10793 | val 0.12573
  Regression -> MSE: 0.000297, MAE: 0.014058, R²: -0.0916
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09466 | val 0.13304
  Epoch 016 - train 0.08769 | val 0.13370
  Regression -> MSE: 0.000151, MAE: 0.008743, R²: -0.0095
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10285 | val 0.13807
  Epoch 016 - train 0.10357 | val 0.13762
  Regression -> MSE: 0.000227, MAE: 0.010872, R²: -0.0017
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10386 | val 0.12592
  Epoch 016 - train 0.10594 | val 0.12822
  Regression -> MSE: 0.000146, MAE: 0.008512, R²: -0.0181
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.10180 | val 0.11796
  Epoch 016 - train 0.10066 | val 0.11855
  Regression -> MSE: 0.000171, MAE: 0.010255, R²: -0.0357
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6526

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11298 | val 0.11700
  Epoch 016 - train 0.10449 | val 0.11658
  Regression -> MSE: 0.000092, MAE: 0.007381, R²: -0.0772
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11028 | val 0.12256
  Epoch 016 - train 0.10657 | val 0.12423
  Regression -> MSE: 0.000216, MAE: 0.011044, R²: -0.0196
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09883 | val 0.08805
  Epoch 016 - train 0.09602 | val 0.08777
  Regression -> MSE: 0.000095, MAE: 0.008109, R²: -0.0308
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11407 | val 0.07931
  Epoch 016 - train 0.10928 | val 0.08432
  Regression -> MSE: 0.000104, MAE: 0.008770, R²: -0.0059
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11413 | val 0.11246
  Epoch 016 - train 0.10946 | val 0.12632
  Regression -> MSE: 0.000242, MAE: 0.012911, R²: -0.0461
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10003 | val 0.12252
  Epoch 016 - train 0.10013 | val 0.12367
  Regression -> MSE: 0.000183, MAE: 0.008018, R²: -0.0987
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10758 | val 0.08800
  Epoch 016 - train 0.11712 | val 0.09008
  Regression -> MSE: 0.000238, MAE: 0.011920, R²: -0.0049
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11200 | val 0.15716
  Epoch 016 - train 0.09825 | val 0.16924
  Regression -> MSE: 0.000230, MAE: 0.009857, R²: 0.0027
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11340 | val 0.13139
  Epoch 016 - train 0.11421 | val 0.13514
  Regression -> MSE: 0.000142, MAE: 0.008535, R²: -0.0514
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10867 | val 0.12564
  Epoch 016 - train 0.10427 | val 0.12864
  Regression -> MSE: 0.000198, MAE: 0.010659, R²: -0.0518
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09124 | val 0.11997
  Epoch 016 - train 0.09623 | val 0.12058
  Regression -> MSE: 0.000275, MAE: 0.010763, R²: -0.0490
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09551 | val 0.09055
  Epoch 016 - train 0.09535 | val 0.09065
  Regression -> MSE: 0.000169, MAE: 0.010367, R²: -0.0118
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09716 | val 0.10821
  Epoch 016 - train 0.09720 | val 0.11484
  Regression -> MSE: 0.000181, MAE: 0.010382, R²: -0.0081
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09833 | val 0.10174
  Epoch 016 - train 0.09455 | val 0.10454
  Regression -> MSE: 0.000346, MAE: 0.011707, R²: -0.0088
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11131 | val 0.06898
  Epoch 016 - train 0.11269 | val 0.06889
  Regression -> MSE: 0.000110, MAE: 0.008342, R²: -0.0451
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10135 | val 0.14300
  Epoch 016 - train 0.10214 | val 0.14442
  Regression -> MSE: 0.000219, MAE: 0.011335, R²: -0.0035
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10996 | val 0.16896
  Epoch 016 - train 0.09887 | val 0.17208
  Regression -> MSE: 0.000095, MAE: 0.007612, R²: -0.2252
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10959 | val 0.09265
  Epoch 016 - train 0.09269 | val 0.09840
  Regression -> MSE: 0.000347, MAE: 0.015597, R²: -0.1295
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12516 | val 0.06277
  Epoch 016 - train 0.11231 | val 0.06413
  Regression -> MSE: 0.000250, MAE: 0.011483, R²: -0.0269
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09935 | val 0.11943
  Epoch 016 - train 0.09929 | val 0.11960
  Regression -> MSE: 0.000081, MAE: 0.007094, R²: -0.0029
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10985 | val 0.12655
  Epoch 020 - train 0.09829 | val 0.11834
  Epoch 030 - train 0.10775 | val 0.12350
  Regression -> MSE: 0.000293, MAE: 0.014251, R²: 0.0464
  Directional -> Accuracy: 0.5319, MCC: 0.0926, F1: 0.6765

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10497 | val 0.11421
  Epoch 016 - train 0.09899 | val 0.11349
  Regression -> MSE: 0.000100, MAE: 0.007131, R²: -0.0138
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11636 | val 0.11885
  Epoch 016 - train 0.11088 | val 0.12438
  Regression -> MSE: 0.000172, MAE: 0.009836, R²: -0.0026
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09691 | val 0.12358
  Epoch 016 - train 0.09307 | val 0.13052
  Regression -> MSE: 0.000223, MAE: 0.011739, R²: 0.0000
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10121 | val 0.10879
  Epoch 016 - train 0.09654 | val 0.11246
  Regression -> MSE: 0.000093, MAE: 0.007659, R²: -0.0028
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.11265 | val 0.15205
  Epoch 016 - train 0.11306 | val 0.15755
  Regression -> MSE: 0.000164, MAE: 0.010280, R²: -0.0035
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.09966 | val 0.12403
  Epoch 016 - train 0.10331 | val 0.12383
  Regression -> MSE: 0.000129, MAE: 0.009086, R²: -0.1150
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.10579 | val 0.13742

[I 2026-02-24 05:12:29,629] Trial 186 finished with value: -0.01149775348224651 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 4.7208224602712276e-05, 'weight_decay': 4.591959543453986e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 15, 'max_epochs': 30, 'huber_delta': 0.14668049381099954, 'early_stopping_min_delta': 0.009188545655964005}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 016 - train 0.10479 | val 0.13617
  Regression -> MSE: 0.000243, MAE: 0.012343, R²: -0.0251
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13326 | val 0.15904
  Epoch 020 - train 0.12942 | val 0.15994
  Epoch 021 - train 0.12990 | val 0.16016
  Regression -> MSE: 0.000248, MAE: 0.012511, R²: -0.0001
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12144 | val 0.11585
  Epoch 020 - train 0.12410 | val 0.12151
  Epoch 021 - train 0.12373 | val 0.12051
  Regression -> MSE: 0.000688, MAE: 0.019376, R²: -0.0051
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13673 | val 0.19776
  Epoch 020 - train 0.13068 | val 0.20085
  Epoch 021 - train 0.13477 | val 0.20068
  Regression -> MSE: 0.000324, MAE: 0.014559, R²: -0.0433
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10901 | val 0.12721
  Epoch 020 - train 0.10161 | val 0.11680
  Epoch 021 - train 0.10933 | val 0.11597
  Regression -> MSE: 0.000355, MAE: 0.014677, R²: -0.0167
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13317 | val 0.12762
  Epoch 020 - train 0.13152 | val 0.13189
  Epoch 021 - train 0.13138 | val 0.13191
  Regression -> MSE: 0.000205, MAE: 0.010094, R²: -0.0043
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12272 | val 0.21964
  Epoch 020 - train 0.11839 | val 0.25533
  Epoch 021 - train 0.11770 | val 0.25735
  Regression -> MSE: 0.000555, MAE: 0.018159, R²: 0.0008
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12452 | val 0.14863
  Epoch 020 - train 0.11997 | val 0.14731
  Epoch 021 - train 0.12896 | val 0.14690
  Regression -> MSE: 0.000246, MAE: 0.012085, R²: -0.0004
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12527 | val 0.13970
  Epoch 020 - train 0.13141 | val 0.12643
  Epoch 030 - train 0.13135 | val 0.12463
  Regression -> MSE: 0.000668, MAE: 0.020072, R²: -0.1176
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11824 | val 0.14983
  Epoch 020 - train 0.11817 | val 0.15074
  Epoch 021 - train 0.12348 | val 0.15058
  Regression -> MSE: 0.000385, MAE: 0.016080, R²: -0.0027
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12598 | val 0.20001
  Epoch 020 - train 0.13174 | val 0.21582
  Epoch 021 - train 0.13341 | val 0.21698
  Regression -> MSE: 0.000251, MAE: 0.011641, R²: -0.0381
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12190 | val 0.20771
  Epoch 020 - train 0.11844 | val 0.24923
  Epoch 021 - train 0.11351 | val 0.24832
  Regression -> MSE: 0.000311, MAE: 0.013773, R²: -0.0013
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12814 | val 0.17591
  Epoch 020 - train 0.12896 | val 0.21433
  Epoch 021 - train 0.13291 | val 0.21545
  Regression -> MSE: 0.000676, MAE: 0.019469, R²: 0.0014
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12419 | val 0.13417
  Epoch 020 - train 0.12812 | val 0.17788
  Epoch 021 - train 0.12323 | val 0.17725
  Regression -> MSE: 0.000138, MAE: 0.009110, R²: 0.0004
  Directional -> Accuracy: 0.4884, MCC: 0.1965, F1: 0.6333

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12790 | val 0.18314
  Epoch 020 - train 0.13138 | val 0.18777
  Epoch 021 - train 0.13000 | val 0.18705
  Regression -> MSE: 0.000230, MAE: 0.011042, R²: -0.0204
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12420 | val 0.24350
  Epoch 020 - train 0.12321 | val 0.24624
  Epoch 021 - train 0.12480 | val 0.24643
  Regression -> MSE: 0.000373, MAE: 0.015932, R²: -0.0301
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12885 | val 0.12753
  Epoch 020 - train 0.12950 | val 0.12697
  Epoch 021 - train 0.13031 | val 0.12731
  Regression -> MSE: 0.000108, MAE: 0.007997, R²: 0.0017
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11851 | val 0.19810
  Epoch 020 - train 0.11564 | val 0.20523
  Epoch 021 - train 0.11374 | val 0.20550
  Regression -> MSE: 0.000156, MAE: 0.009609, R²: 0.0005
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12614 | val 0.12201
  Epoch 020 - train 0.13040 | val 0.12385
  Epoch 021 - train 0.12514 | val 0.12418
  Regression -> MSE: 0.000272, MAE: 0.013054, R²: 0.0001
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11307 | val 0.16117
  Epoch 020 - train 0.12085 | val 0.16152
  Epoch 021 - train 0.11151 | val 0.16167
  Regression -> MSE: 0.000166, MAE: 0.009113, R²: -0.1108
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12625 | val 0.18411
  Epoch 020 - train 0.12371 | val 0.18554
  Epoch 021 - train 0.13060 | val 0.18579
  Regression -> MSE: 0.000230, MAE: 0.010884, R²: -0.0145
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12487 | val 0.15600
  Epoch 020 - train 0.12697 | val 0.16058
  Epoch 021 - train 0.12468 | val 0.16130
  Regression -> MSE: 0.000144, MAE: 0.008354, R²: -0.0029
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12398 | val 0.14314
  Epoch 020 - train 0.12828 | val 0.14265
  Epoch 021 - train 0.12313 | val 0.14285
  Regression -> MSE: 0.000166, MAE: 0.010349, R²: -0.0061
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13030 | val 0.15487
  Epoch 020 - train 0.13113 | val 0.15471
  Epoch 021 - train 0.13450 | val 0.15441
  Regression -> MSE: 0.000088, MAE: 0.007171, R²: -0.0278
  Directional -> Accuracy: 0.5517, MCC: 0.0861, F1: 0.6061

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13242 | val 0.14210
  Epoch 020 - train 0.12565 | val 0.14506
  Epoch 021 - train 0.12733 | val 0.14456
  Regression -> MSE: 0.000212, MAE: 0.011088, R²: -0.0011
  Directional -> Accuracy: 0.4697, MCC: -0.0225, F1: 0.6067

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12429 | val 0.11348
  Epoch 020 - train 0.11612 | val 0.11319
  Epoch 021 - train 0.11770 | val 0.11368
  Regression -> MSE: 0.000104, MAE: 0.008323, R²: -0.1277
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12755 | val 0.09374
  Epoch 020 - train 0.13337 | val 0.10017
  Epoch 021 - train 0.13427 | val 0.10159
  Regression -> MSE: 0.000105, MAE: 0.008826, R²: -0.0137
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13433 | val 0.11469
  Epoch 020 - train 0.13271 | val 0.11652
  Epoch 021 - train 0.13750 | val 0.11676
  Regression -> MSE: 0.000236, MAE: 0.012732, R²: -0.0213
  Directional -> Accuracy: 0.6047, MCC: 0.1508, F1: 0.7018

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12193 | val 0.13708
  Epoch 020 - train 0.12140 | val 0.13468
  Epoch 030 - train 0.12254 | val 0.13410
  Regression -> MSE: 0.000184, MAE: 0.008025, R²: -0.1037
  Directional -> Accuracy: 0.4912, MCC: 0.1491, F1: 0.2162

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13557 | val 0.10793
  Epoch 020 - train 0.13815 | val 0.10654
  Epoch 021 - train 0.13584 | val 0.10687
  Regression -> MSE: 0.000241, MAE: 0.012089, R²: -0.0193
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13295 | val 0.18528
  Epoch 020 - train 0.13498 | val 0.18776
  Epoch 021 - train 0.12678 | val 0.18753
  Regression -> MSE: 0.000231, MAE: 0.009869, R²: -0.0013
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13359 | val 0.15467
  Epoch 020 - train 0.13014 | val 0.17082
  Epoch 021 - train 0.13691 | val 0.17054
  Regression -> MSE: 0.000140, MAE: 0.008422, R²: -0.0397
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12601 | val 0.15176
  Epoch 020 - train 0.12606 | val 0.15409
  Epoch 021 - train 0.12751 | val 0.15425
  Regression -> MSE: 0.000188, MAE: 0.010492, R²: 0.0000
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11202 | val 0.14253
  Epoch 020 - train 0.11317 | val 0.14011
  Epoch 021 - train 0.10946 | val 0.14051
  Regression -> MSE: 0.000269, MAE: 0.010601, R²: -0.0271
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12591 | val 0.09938
  Epoch 020 - train 0.11661 | val 0.09823
  Epoch 021 - train 0.12599 | val 0.09847
  Regression -> MSE: 0.000167, MAE: 0.010370, R²: -0.0044
  Directional -> Accuracy: 0.5263, MCC: 0.0679, F1: 0.3077

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11325 | val 0.13911
  Epoch 020 - train 0.12811 | val 0.15962
  Epoch 021 - train 0.12022 | val 0.15991
  Regression -> MSE: 0.000188, MAE: 0.010656, R²: -0.0473
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11684 | val 0.11477
  Epoch 020 - train 0.11944 | val 0.11481
  Epoch 021 - train 0.11571 | val 0.11472
  Regression -> MSE: 0.000344, MAE: 0.012007, R²: -0.0032
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13214 | val 0.07906
  Epoch 020 - train 0.12430 | val 0.08886
  Epoch 021 - train 0.13571 | val 0.09004
  Regression -> MSE: 0.000124, MAE: 0.008429, R²: -0.1776
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12732 | val 0.17573
  Epoch 020 - train 0.12620 | val 0.18255
  Epoch 021 - train 0.12388 | val 0.18343
  Regression -> MSE: 0.000219, MAE: 0.011264, R²: -0.0018
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14332 | val 0.20880
  Epoch 020 - train 0.13494 | val 0.23207
  Epoch 021 - train 0.12719 | val 0.23216
  Regression -> MSE: 0.000090, MAE: 0.007414, R²: -0.1557
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11792 | val 0.08932
  Epoch 020 - train 0.12356 | val 0.09225
  Epoch 021 - train 0.12727 | val 0.09319
  Regression -> MSE: 0.000309, MAE: 0.013874, R²: -0.0058
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13195 | val 0.07376
  Epoch 020 - train 0.14023 | val 0.08091
  Epoch 021 - train 0.11767 | val 0.08233
  Regression -> MSE: 0.000249, MAE: 0.011514, R²: -0.0231
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12182 | val 0.15012
  Epoch 020 - train 0.11804 | val 0.14899
  Epoch 021 - train 0.12388 | val 0.14900
  Regression -> MSE: 0.000081, MAE: 0.007081, R²: 0.0017
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13087 | val 0.15393
  Epoch 020 - train 0.12876 | val 0.15598
  Epoch 021 - train 0.12624 | val 0.15598
  Regression -> MSE: 0.000310, MAE: 0.014484, R²: -0.0099
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11771 | val 0.12748
  Epoch 020 - train 0.11169 | val 0.13502
  Epoch 021 - train 0.11791 | val 0.13599
  Regression -> MSE: 0.000098, MAE: 0.007296, R²: 0.0002
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13046 | val 0.14174
  Epoch 020 - train 0.14510 | val 0.15104
  Epoch 021 - train 0.13800 | val 0.15238
  Regression -> MSE: 0.000173, MAE: 0.009512, R²: -0.0052
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.11376 | val 0.14687
  Epoch 020 - train 0.11908 | val 0.15899
  Epoch 021 - train 0.11766 | val 0.15828
  Regression -> MSE: 0.000224, MAE: 0.011774, R²: -0.0043
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.11700 | val 0.13365
  Epoch 020 - train 0.11976 | val 0.13441
  Epoch 021 - train 0.11526 | val 0.13429
  Regression -> MSE: 0.000094, MAE: 0.007738, R²: -0.0166
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...


[I 2026-02-24 05:14:24,860] Trial 187 finished with value: -0.011411653803289184 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 1.1058743330469475e-05, 'weight_decay': 1.905367838403719e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.17750172336554565, 'early_stopping_min_delta': 0.007213086384462357}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.12896 | val 0.16693
  Epoch 021 - train 0.12834 | val 0.16684
  Regression -> MSE: 0.000243, MAE: 0.012341, R²: -0.0230
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.17802 | val 0.29691
  Epoch 020 - train 0.17848 | val 0.29031
  Epoch 021 - train 0.17923 | val 0.29195
  Regression -> MSE: 0.000263, MAE: 0.013091, R²: -0.0640
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.18820 | val 0.18949
  Epoch 020 - train 0.18376 | val 0.18812
  Epoch 021 - train 0.19144 | val 0.18431
  Regression -> MSE: 0.000724, MAE: 0.020016, R²: -0.0576
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.18463 | val 0.31438
  Epoch 020 - train 0.17515 | val 0.30945
  Epoch 021 - train 0.18142 | val 0.30963
  Regression -> MSE: 0.000312, MAE: 0.014421, R²: -0.0054
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15189 | val 0.21342
  Epoch 020 - train 0.14967 | val 0.19185
  Epoch 021 - train 0.14896 | val 0.19369
  Regression -> MSE: 0.000350, MAE: 0.014527, R²: -0.0010
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.18266 | val 0.17764
  Epoch 020 - train 0.17514 | val 0.18043
  Epoch 021 - train 0.17169 | val 0.17941
  Regression -> MSE: 0.000204, MAE: 0.010131, R²: -0.0008
  Directional -> Accuracy: 0.3333, MCC: -0.3652, F1: 0.1053

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.18173 | val 0.33402
  Epoch 020 - train 0.17831 | val 0.34611
  Epoch 021 - train 0.18110 | val 0.34802
  Regression -> MSE: 0.000557, MAE: 0.018149, R²: -0.0041
  Directional -> Accuracy: 0.5532, MCC: 0.1357, F1: 0.2759

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.18353 | val 0.22681
  Epoch 020 - train 0.18455 | val 0.22647
  Epoch 021 - train 0.17911 | val 0.22773
  Regression -> MSE: 0.000245, MAE: 0.011972, R²: 0.0001
  Directional -> Accuracy: 0.5217, MCC: 0.0819, F1: 0.5217

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.18526 | val 0.23059
  Epoch 020 - train 0.17100 | val 0.24186
  Epoch 021 - train 0.18241 | val 0.24286
  Regression -> MSE: 0.000629, MAE: 0.019884, R²: -0.0536
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.17506 | val 0.21855
  Epoch 020 - train 0.17528 | val 0.21867
  Epoch 021 - train 0.16528 | val 0.21946
  Regression -> MSE: 0.000389, MAE: 0.016006, R²: -0.0143
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.18386 | val 0.22038
  Epoch 020 - train 0.17728 | val 0.22038
  Epoch 021 - train 0.17819 | val 0.22281
  Regression -> MSE: 0.000245, MAE: 0.011664, R²: -0.0132
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15418 | val 0.26681
  Epoch 020 - train 0.15360 | val 0.27035
  Epoch 021 - train 0.15679 | val 0.26876
  Regression -> MSE: 0.000312, MAE: 0.013651, R²: -0.0027
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.18935 | val 0.21295
  Epoch 020 - train 0.18636 | val 0.21443
  Epoch 021 - train 0.18887 | val 0.21335
  Regression -> MSE: 0.000683, MAE: 0.019730, R²: -0.0084
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17745 | val 0.29595
  Epoch 020 - train 0.17091 | val 0.30888
  Epoch 021 - train 0.16624 | val 0.32169
  Regression -> MSE: 0.000139, MAE: 0.009202, R²: -0.0048
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.16063 | val 0.25703
  Epoch 020 - train 0.15400 | val 0.25930
  Epoch 024 - train 0.15309 | val 0.25925
  Regression -> MSE: 0.000223, MAE: 0.010811, R²: 0.0080
  Directional -> Accuracy: 0.5082, MCC: 0.0161, F1: 0.5161

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16877 | val 0.38649
  Epoch 020 - train 0.16940 | val 0.39008
  Epoch 021 - train 0.17418 | val 0.38847
  Regression -> MSE: 0.000366, MAE: 0.015955, R²: -0.0119
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.17979 | val 0.16645
  Epoch 020 - train 0.17821 | val 0.17360
  Epoch 024 - train 0.18042 | val 0.17236
  Regression -> MSE: 0.000110, MAE: 0.007998, R²: -0.0176
  Directional -> Accuracy: 0.5857, MCC: 0.1909, F1: 0.7184

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.17393 | val 0.31987
  Epoch 020 - train 0.16286 | val 0.33715
  Epoch 021 - train 0.16628 | val 0.33955
  Regression -> MSE: 0.000156, MAE: 0.009676, R²: -0.0022
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.18125 | val 0.18399
  Epoch 020 - train 0.17638 | val 0.18287
  Epoch 021 - train 0.18178 | val 0.18181
  Regression -> MSE: 0.000272, MAE: 0.012961, R²: 0.0020
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.18310 | val 0.25824
  Epoch 020 - train 0.16590 | val 0.24978
  Epoch 021 - train 0.17456 | val 0.24971
  Regression -> MSE: 0.000154, MAE: 0.008779, R²: -0.0274
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.18787 | val 0.26986
  Epoch 020 - train 0.18544 | val 0.27733
  Epoch 021 - train 0.18648 | val 0.27660
  Regression -> MSE: 0.000233, MAE: 0.010955, R²: -0.0286
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.18288 | val 0.21143
  Epoch 020 - train 0.18156 | val 0.21242
  Epoch 021 - train 0.18487 | val 0.21227
  Regression -> MSE: 0.000148, MAE: 0.008629, R²: -0.0358
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.17028 | val 0.20861
  Epoch 020 - train 0.17076 | val 0.20411
  Epoch 021 - train 0.16442 | val 0.20282
  Regression -> MSE: 0.000167, MAE: 0.010289, R²: -0.0136
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.18407 | val 0.20868
  Epoch 020 - train 0.18055 | val 0.21349
  Epoch 021 - train 0.18668 | val 0.21367
  Regression -> MSE: 0.000091, MAE: 0.007351, R²: -0.0677
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.17840 | val 0.44870
  Epoch 020 - train 0.18509 | val 0.43857
  Epoch 021 - train 0.17464 | val 0.44775
  Regression -> MSE: 0.000216, MAE: 0.011012, R²: -0.0183
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.16398 | val 0.16678
  Epoch 020 - train 0.16523 | val 0.16290
  Epoch 021 - train 0.16204 | val 0.16257
  Regression -> MSE: 0.000095, MAE: 0.008108, R²: -0.0288
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.17840 | val 0.13845
  Epoch 020 - train 0.17015 | val 0.14086
  Epoch 021 - train 0.16967 | val 0.14147
  Regression -> MSE: 0.000108, MAE: 0.008935, R²: -0.0434
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.18359 | val 0.19874
  Epoch 020 - train 0.18793 | val 0.19408
  Epoch 021 - train 0.18953 | val 0.20214
  Regression -> MSE: 0.000232, MAE: 0.012574, R²: -0.0036
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.17640 | val 0.25548
  Epoch 020 - train 0.18381 | val 0.25399
  Epoch 021 - train 0.17414 | val 0.25185
  Regression -> MSE: 0.000170, MAE: 0.007867, R²: -0.0206
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.19068 | val 0.16193
  Epoch 020 - train 0.18508 | val 0.19711
  Epoch 021 - train 0.17764 | val 0.19698
  Regression -> MSE: 0.000237, MAE: 0.011864, R²: -0.0007
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.17478 | val 0.27454
  Epoch 020 - train 0.17349 | val 0.27597
  Epoch 021 - train 0.16808 | val 0.27702
  Regression -> MSE: 0.000231, MAE: 0.009900, R²: -0.0007
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18227 | val 0.23105
  Epoch 020 - train 0.19072 | val 0.22751
  Epoch 021 - train 0.19531 | val 0.22698
  Regression -> MSE: 0.000136, MAE: 0.008190, R²: -0.0059
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.17955 | val 0.23188
  Epoch 020 - train 0.17816 | val 0.23199
  Epoch 021 - train 0.18733 | val 0.23171
  Regression -> MSE: 0.000190, MAE: 0.010393, R²: -0.0074
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15321 | val 0.19245
  Epoch 020 - train 0.14791 | val 0.19324
  Epoch 021 - train 0.15072 | val 0.19318
  Regression -> MSE: 0.000280, MAE: 0.010908, R²: -0.0685
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16054 | val 0.14766
  Epoch 020 - train 0.15599 | val 0.15552
  Epoch 030 - train 0.16893 | val 0.15614
  Regression -> MSE: 0.000161, MAE: 0.010342, R²: 0.0351
  Directional -> Accuracy: 0.5789, MCC: 0.1664, F1: 0.6364

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.17710 | val 0.23798
  Epoch 020 - train 0.17861 | val 0.23993
  Epoch 021 - train 0.16248 | val 0.23905
  Regression -> MSE: 0.000180, MAE: 0.010308, R²: 0.0011
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.18453 | val 0.18197
  Epoch 020 - train 0.17509 | val 0.17427
  Epoch 021 - train 0.17621 | val 0.17444
  Regression -> MSE: 0.000353, MAE: 0.011829, R²: -0.0310
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18195 | val 0.11232
  Epoch 020 - train 0.18856 | val 0.11395
  Epoch 021 - train 0.18131 | val 0.11387
  Regression -> MSE: 0.000115, MAE: 0.008310, R²: -0.0950
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.17497 | val 0.27346
  Epoch 020 - train 0.16614 | val 0.26896
  Epoch 021 - train 0.16339 | val 0.26799
  Regression -> MSE: 0.000223, MAE: 0.011416, R²: -0.0189
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.19313 | val 0.32895
  Epoch 020 - train 0.18192 | val 0.34167
  Epoch 021 - train 0.19349 | val 0.33948
  Regression -> MSE: 0.000094, MAE: 0.007567, R²: -0.2084
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.18548 | val 0.16871
  Epoch 020 - train 0.18238 | val 0.18790
  Epoch 021 - train 0.18653 | val 0.18861
  Regression -> MSE: 0.000327, MAE: 0.014849, R²: -0.0614
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17732 | val 0.11495
  Epoch 020 - train 0.18978 | val 0.15049
  Epoch 021 - train 0.17870 | val 0.15073
  Regression -> MSE: 0.000260, MAE: 0.011498, R²: -0.0653
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16383 | val 0.23511
  Epoch 020 - train 0.16947 | val 0.23913
  Epoch 021 - train 0.16720 | val 0.23978
  Regression -> MSE: 0.000082, MAE: 0.007041, R²: -0.0180
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17357 | val 0.21537
  Epoch 020 - train 0.17109 | val 0.21374
  Epoch 029 - train 0.17436 | val 0.21317
  Regression -> MSE: 0.000315, MAE: 0.014727, R²: -0.0279
  Directional -> Accuracy: 0.4468, MCC: -0.1997, F1: 0.6061

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.17435 | val 0.20574
  Epoch 020 - train 0.18665 | val 0.21284
  Epoch 021 - train 0.18704 | val 0.21384
  Regression -> MSE: 0.000100, MAE: 0.007118, R²: -0.0205
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.18884 | val 0.22889
  Epoch 020 - train 0.18992 | val 0.23246
  Epoch 021 - train 0.19073 | val 0.23250
  Regression -> MSE: 0.000173, MAE: 0.009472, R²: -0.0095
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.17069 | val 0.22384
  Epoch 020 - train 0.16876 | val 0.22022
  Epoch 021 - train 0.16928 | val 0.21981
  Regression -> MSE: 0.000223, MAE: 0.011746, R²: -0.0022
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.17965 | val 0.20549
  Epoch 020 - train 0.17436 | val 0.20225
  Epoch 021 - train 0.17654 | val 0.20127
  Regression -> MSE: 0.000092, MAE: 0.007639, R²: 0.0002
  Directional -> Accuracy: 0.4912, MCC: -0.0516, F1: 0.2927


[I 2026-02-24 05:16:59,625] Trial 188 finished with value: -0.011420897660121198 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 1.1791953135891552e-05, 'weight_decay': 1.6488745426607158e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.272611832259105, 'early_stopping_min_delta': 0.007221030940730536}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.17803 | val 0.24230
  Regression -> MSE: 0.000237, MAE: 0.012395, R²: 0.0027
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.22493 | val 0.34247
  Epoch 013 - train 0.22166 | val 0.34109
  Regression -> MSE: 0.000247, MAE: 0.012507, R²: 0.0025
  Directional -> Accuracy: 0.4935, MCC: 0.1347, F1: 0.6355

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.21372 | val 0.31138
  Epoch 011 - train 0.22644 | val 0.31142
  Regression -> MSE: 0.000713, MAE: 0.019853, R²: -0.0422
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.24498 | val 0.39270
  Epoch 011 - train 0.24382 | val 0.39246
  Regression -> MSE: 0.000327, MAE: 0.014552, R²: -0.0533
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.18297 | val 0.20125
  Epoch 011 - train 0.18915 | val 0.19567
  Regression -> MSE: 0.000379, MAE: 0.015054, R²: -0.0849
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.22920 | val 0.25176
  Epoch 011 - train 0.22753 | val 0.24931
  Regression -> MSE: 0.000205, MAE: 0.010349, R²: -0.0075
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.21227 | val 0.44259
  Epoch 011 - train 0.21878 | val 0.44533
  Regression -> MSE: 0.000562, MAE: 0.018206, R²: -0.0127
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.22873 | val 0.29150
  Epoch 011 - train 0.22631 | val 0.29191
  Regression -> MSE: 0.000247, MAE: 0.012265, R²: -0.0067
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.24993 | val 0.31075
  Epoch 011 - train 0.22714 | val 0.32191
  Regression -> MSE: 0.000611, MAE: 0.019498, R²: -0.0228
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.22468 | val 0.28162
  Epoch 011 - train 0.22621 | val 0.28022
  Regression -> MSE: 0.000387, MAE: 0.016056, R²: -0.0090
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.24420 | val 0.29799
  Epoch 011 - train 0.23377 | val 0.29784
  Regression -> MSE: 0.000247, MAE: 0.011592, R²: -0.0223
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.21015 | val 0.41941
  Epoch 011 - train 0.21184 | val 0.42200
  Regression -> MSE: 0.000313, MAE: 0.013633, R²: -0.0066
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.25323 | val 0.28195
  Epoch 011 - train 0.26023 | val 0.28136
  Regression -> MSE: 0.000680, MAE: 0.019521, R²: -0.0044
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.22582 | val 0.22793
  Epoch 011 - train 0.23244 | val 0.22888
  Regression -> MSE: 0.000139, MAE: 0.009235, R²: -0.0070
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.21152 | val 0.30380
  Epoch 011 - train 0.19506 | val 0.30131
  Regression -> MSE: 0.000230, MAE: 0.010859, R²: -0.0228
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.23379 | val 0.60755
  Epoch 011 - train 0.23820 | val 0.59859
  Regression -> MSE: 0.000378, MAE: 0.015959, R²: -0.0438
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.23168 | val 0.24506
  Epoch 011 - train 0.22862 | val 0.24571
  Regression -> MSE: 0.000107, MAE: 0.008009, R²: 0.0058
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.22439 | val 0.38948
  Epoch 011 - train 0.21992 | val 0.39102
  Regression -> MSE: 0.000164, MAE: 0.010269, R²: -0.0519
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.23331 | val 0.32504
  Epoch 011 - train 0.23934 | val 0.32905
  Regression -> MSE: 0.000273, MAE: 0.013068, R²: -0.0037
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.19780 | val 0.30728
  Epoch 011 - train 0.21191 | val 0.30559
  Regression -> MSE: 0.000152, MAE: 0.008763, R²: -0.0189
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.23226 | val 0.33495
  Epoch 011 - train 0.22762 | val 0.33530
  Regression -> MSE: 0.000232, MAE: 0.010875, R²: -0.0249
  Directional -> Accuracy: 0.6400, MCC: 0.2672, F1: 0.7158

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.22473 | val 0.28054
  Epoch 011 - train 0.22008 | val 0.28095
  Regression -> MSE: 0.000143, MAE: 0.008347, R²: 0.0005
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.20969 | val 0.26368
  Epoch 016 - train 0.20885 | val 0.26393
  Regression -> MSE: 0.000179, MAE: 0.010344, R²: -0.0840
  Directional -> Accuracy: 0.5606, MCC: 0.2108, F1: 0.2564

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.23857 | val 0.27924
  Epoch 011 - train 0.25008 | val 0.27847
  Regression -> MSE: 0.000086, MAE: 0.007101, R²: -0.0125
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.24362 | val 0.36210
  Epoch 011 - train 0.24141 | val 0.35528
  Regression -> MSE: 0.000212, MAE: 0.011176, R²: -0.0012
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.21262 | val 0.19202
  Epoch 020 - train 0.21974 | val 0.18742
  Epoch 021 - train 0.21323 | val 0.18730
  Regression -> MSE: 0.000137, MAE: 0.009747, R²: -0.4858
  Directional -> Accuracy: 0.4286, MCC: -0.1018, F1: 0.2727

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.22353 | val 0.17912
  Epoch 020 - train 0.21212 | val 0.17384
  Epoch 027 - train 0.23273 | val 0.17343
  Regression -> MSE: 0.000156, MAE: 0.010338, R²: -0.5121
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.24181 | val 0.23852
  Epoch 011 - train 0.24634 | val 0.24032
  Regression -> MSE: 0.000231, MAE: 0.012519, R²: 0.0008
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.22949 | val 0.26131
  Epoch 011 - train 0.22664 | val 0.25956
  Regression -> MSE: 0.000184, MAE: 0.008040, R²: -0.1035
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22275 | val 0.19165
  Epoch 011 - train 0.23314 | val 0.19513
  Regression -> MSE: 0.000237, MAE: 0.011869, R²: -0.0004
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.23866 | val 0.37198
  Epoch 011 - train 0.22889 | val 0.37485
  Regression -> MSE: 0.000231, MAE: 0.009874, R²: -0.0029
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.24018 | val 0.27391
  Epoch 011 - train 0.24750 | val 0.27455
  Regression -> MSE: 0.000137, MAE: 0.008278, R²: -0.0130
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.22867 | val 0.29423
  Epoch 011 - train 0.22906 | val 0.29549
  Regression -> MSE: 0.000193, MAE: 0.010430, R²: -0.0246
  Directional -> Accuracy: 0.4600, MCC: -0.0350, F1: 0.2286

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.20642 | val 0.26300
  Epoch 011 - train 0.20707 | val 0.26103
  Regression -> MSE: 0.000264, MAE: 0.010506, R²: -0.0074
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.23244 | val 0.21455
  Epoch 011 - train 0.22625 | val 0.22768
  Regression -> MSE: 0.000169, MAE: 0.010369, R²: -0.0129
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.20524 | val 0.26734
  Epoch 011 - train 0.19810 | val 0.27262
  Regression -> MSE: 0.000183, MAE: 0.010447, R²: -0.0179
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.22223 | val 0.20226
  Epoch 011 - train 0.22043 | val 0.20209
  Regression -> MSE: 0.000344, MAE: 0.011829, R²: -0.0026
  Directional -> Accuracy: 0.5522, MCC: 0.0956, F1: 0.5946

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.25520 | val 0.15347
  Epoch 011 - train 0.25747 | val 0.15918
  Regression -> MSE: 0.000116, MAE: 0.008332, R²: -0.1065
  Directional -> Accuracy: 0.5581, MCC: 0.2261, F1: 0.6984

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.21926 | val 0.33420
  Epoch 011 - train 0.22499 | val 0.33940
  Regression -> MSE: 0.000219, MAE: 0.011286, R²: -0.0012
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.22381 | val 0.44684
  Epoch 011 - train 0.23556 | val 0.45161
  Regression -> MSE: 0.000085, MAE: 0.007218, R²: -0.0980
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.23335 | val 0.21631
  Epoch 011 - train 0.22937 | val 0.22402
  Regression -> MSE: 0.000329, MAE: 0.014956, R²: -0.0701
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.23199 | val 0.13122
  Epoch 020 - train 0.24600 | val 0.12099
  Epoch 026 - train 0.25302 | val 0.12181
  Regression -> MSE: 0.000257, MAE: 0.011417, R²: -0.0545
  Directional -> Accuracy: 0.5789, MCC: 0.2485, F1: 0.7143

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.21877 | val 0.28043
  Epoch 011 - train 0.22022 | val 0.28069
  Regression -> MSE: 0.000081, MAE: 0.007071, R²: -0.0012
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.22249 | val 0.29209
  Epoch 011 - train 0.21076 | val 0.28955
  Regression -> MSE: 0.000307, MAE: 0.014490, R²: -0.0006
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.23617 | val 0.27966
  Epoch 011 - train 0.23663 | val 0.28417
  Regression -> MSE: 0.000101, MAE: 0.007110, R²: -0.0323
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.26659 | val 0.29950
  Epoch 011 - train 0.25502 | val 0.30362
  Regression -> MSE: 0.000173, MAE: 0.009540, R²: -0.0049
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.20591 | val 0.28994
  Epoch 011 - train 0.19735 | val 0.28545
  Regression -> MSE: 0.000224, MAE: 0.011770, R²: -0.0043
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.23050 | val 0.24429
  Epoch 014 - train 0.22370 | val 0.24612
  Regression -> MSE: 0.000099, MAE: 0.007903, R²: -0.0756
  Directional -> Accuracy: 0.4737, MCC: -0.1409, F1: 0.1176

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.24356 | val 0.35458
  Epoch 011 - train 0.25192 | val 0.35430
  Regression -> MSE: 0.000164, MAE: 0.010309, R²: -0.0045
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.22765 | val 0.27890
  Epoch 011 - train 0.22431 | val 0.27797
  Regression -> MSE: 0.000125, MAE: 0.009030, R²: -0.0764
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 05:18:25,952] Trial 189 finished with value: -0.011482560685210651 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 1.1962702811283942e-05, 'weight_decay': 1.8668011495651898e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.37680581102366617, 'early_stopping_min_delta': 0.007208808408457395}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 010 - train 0.23654 | val 0.40095
  Epoch 011 - train 0.23771 | val 0.40664
  Regression -> MSE: 0.000238, MAE: 0.012361, R²: -0.0037
  Directional -> Accuracy: 0.4918, MCC: 0.0647, F1: 0.6437

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.19957 | val 0.31554
  Epoch 020 - train 0.19755 | val 0.31727
  Epoch 021 - train 0.19136 | val 0.32050
  Regression -> MSE: 0.000261, MAE: 0.013010, R²: -0.0524
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.18441 | val 0.18869
  Epoch 020 - train 0.18986 | val 0.18795
  Epoch 021 - train 0.18970 | val 0.18791
  Regression -> MSE: 0.000710, MAE: 0.019811, R²: -0.0372
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.19388 | val 0.29373
  Epoch 020 - train 0.19152 | val 0.29422
  Epoch 027 - train 0.18934 | val 0.29308
  Regression -> MSE: 0.000303, MAE: 0.013932, R²: 0.0243
  Directional -> Accuracy: 0.5745, MCC: 0.1723, F1: 0.7059

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15790 | val 0.23617
  Epoch 020 - train 0.15042 | val 0.23068
  Epoch 021 - train 0.16759 | val 0.22351
  Regression -> MSE: 0.000384, MAE: 0.015143, R²: -0.1004
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.18817 | val 0.18713
  Epoch 020 - train 0.19023 | val 0.18404
  Epoch 021 - train 0.19797 | val 0.18274
  Regression -> MSE: 0.000205, MAE: 0.010221, R²: -0.0087
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.19662 | val 0.34083
  Epoch 020 - train 0.18118 | val 0.34383
  Epoch 027 - train 0.17588 | val 0.34222
  Regression -> MSE: 0.000666, MAE: 0.019725, R²: -0.1990
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.21064 | val 0.23530
  Epoch 020 - train 0.20372 | val 0.23234
  Epoch 021 - train 0.20227 | val 0.23157
  Regression -> MSE: 0.000248, MAE: 0.012285, R²: -0.0120
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.18003 | val 0.24447
  Epoch 020 - train 0.18643 | val 0.24278
  Epoch 021 - train 0.19375 | val 0.24476
  Regression -> MSE: 0.000620, MAE: 0.019670, R²: -0.0377
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.17926 | val 0.23755
  Epoch 020 - train 0.19721 | val 0.23567
  Epoch 021 - train 0.17721 | val 0.23521
  Regression -> MSE: 0.000396, MAE: 0.016022, R²: -0.0335
  Directional -> Accuracy: 0.4286, MCC: -0.2877, F1: 0.0667

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.19278 | val 0.27741
  Epoch 020 - train 0.18727 | val 0.27199
  Epoch 021 - train 0.19404 | val 0.27845
  Regression -> MSE: 0.000242, MAE: 0.011740, R²: -0.0021
  Directional -> Accuracy: 0.4571, MCC: 0.0236, F1: 0.5778

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.16732 | val 0.25833
  Epoch 020 - train 0.18104 | val 0.25990
  Epoch 021 - train 0.18018 | val 0.25888
  Regression -> MSE: 0.000314, MAE: 0.013599, R²: -0.0104
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.18703 | val 0.28991
  Epoch 020 - train 0.19869 | val 0.28643
  Epoch 021 - train 0.20199 | val 0.28356
  Regression -> MSE: 0.000679, MAE: 0.019513, R²: -0.0030
  Directional -> Accuracy: 0.4138, MCC: -0.1794, F1: 0.4848

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.19520 | val 0.18777
  Epoch 020 - train 0.17815 | val 0.18649
  Epoch 021 - train 0.19126 | val 0.18545
  Regression -> MSE: 0.000139, MAE: 0.009224, R²: -0.0077
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.18442 | val 0.27553
  Epoch 020 - train 0.18089 | val 0.27424
  Epoch 021 - train 0.18285 | val 0.27536
  Regression -> MSE: 0.000227, MAE: 0.010937, R²: -0.0099
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.18302 | val 0.38275
  Epoch 020 - train 0.18522 | val 0.38429
  Epoch 021 - train 0.18596 | val 0.38454
  Regression -> MSE: 0.000363, MAE: 0.016037, R²: -0.0026
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.20280 | val 0.20247
  Epoch 020 - train 0.20142 | val 0.19928
  Epoch 021 - train 0.20798 | val 0.20121
  Regression -> MSE: 0.000110, MAE: 0.008206, R²: -0.0173
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.19142 | val 0.42537
  Epoch 020 - train 0.20154 | val 0.41954
  Epoch 021 - train 0.19203 | val 0.41564
  Regression -> MSE: 0.000160, MAE: 0.009524, R²: -0.0271
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.19688 | val 0.20433
  Epoch 020 - train 0.20548 | val 0.20407
  Epoch 021 - train 0.20173 | val 0.20507
  Regression -> MSE: 0.000279, MAE: 0.013305, R²: -0.0238
  Directional -> Accuracy: 0.5000, MCC: 0.2770, F1: 0.2963

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.17319 | val 0.23478
  Epoch 020 - train 0.17321 | val 0.23370
  Epoch 028 - train 0.17180 | val 0.23372
  Regression -> MSE: 0.000224, MAE: 0.011066, R²: -0.4980
  Directional -> Accuracy: 0.5077, MCC: 0.1193, F1: 0.4074

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.19225 | val 0.26725
  Epoch 020 - train 0.19103 | val 0.26651
  Epoch 021 - train 0.19197 | val 0.26730
  Regression -> MSE: 0.000238, MAE: 0.011093, R²: -0.0514
  Directional -> Accuracy: 0.3467, MCC: -0.2934, F1: 0.2687

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.20603 | val 0.36412
  Epoch 020 - train 0.21142 | val 0.35890
  Epoch 021 - train 0.20969 | val 0.35863
  Regression -> MSE: 0.000146, MAE: 0.008485, R²: -0.0189
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.18888 | val 0.21788
  Epoch 020 - train 0.18096 | val 0.21887
  Epoch 021 - train 0.18421 | val 0.21868
  Regression -> MSE: 0.000169, MAE: 0.010337, R²: -0.0207
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.19371 | val 0.24291
  Epoch 020 - train 0.18951 | val 0.24383
  Epoch 021 - train 0.19450 | val 0.24241
  Regression -> MSE: 0.000087, MAE: 0.007163, R²: -0.0247
  Directional -> Accuracy: 0.5517, MCC: -0.1153, F1: 0.7111

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.19341 | val 0.36391
  Epoch 020 - train 0.21062 | val 0.36664
  Epoch 021 - train 0.20734 | val 0.35286
  Regression -> MSE: 0.000215, MAE: 0.011032, R²: -0.0160
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.16926 | val 0.16113
  Epoch 020 - train 0.18028 | val 0.16002
  Epoch 021 - train 0.17921 | val 0.16020
  Regression -> MSE: 0.000101, MAE: 0.008232, R²: -0.1018
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.19207 | val 0.17163
  Epoch 020 - train 0.21050 | val 0.17203
  Epoch 021 - train 0.19186 | val 0.17931
  Regression -> MSE: 0.000117, MAE: 0.009257, R²: -0.1387
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.20540 | val 0.18882
  Epoch 020 - train 0.20753 | val 0.19158
  Epoch 021 - train 0.21030 | val 0.18881
  Regression -> MSE: 0.000231, MAE: 0.012504, R²: 0.0003
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.18591 | val 0.22320
  Epoch 020 - train 0.17933 | val 0.22198
  Epoch 021 - train 0.18735 | val 0.22267
  Regression -> MSE: 0.000182, MAE: 0.008010, R²: -0.0953
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.20464 | val 0.16134
  Epoch 020 - train 0.17793 | val 0.16697
  Epoch 021 - train 0.20258 | val 0.16746
  Regression -> MSE: 0.000238, MAE: 0.011913, R²: -0.0060
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.21139 | val 0.32808
  Epoch 020 - train 0.20235 | val 0.32725
  Epoch 021 - train 0.19903 | val 0.32943
  Regression -> MSE: 0.000238, MAE: 0.010316, R²: -0.0321
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18925 | val 0.24217
  Epoch 020 - train 0.18909 | val 0.24605
  Epoch 021 - train 0.18968 | val 0.24409
  Regression -> MSE: 0.000139, MAE: 0.008383, R²: -0.0281
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.18790 | val 0.23459
  Epoch 020 - train 0.19457 | val 0.23400
  Epoch 021 - train 0.18529 | val 0.23397
  Regression -> MSE: 0.000188, MAE: 0.010455, R²: -0.0010
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.18352 | val 0.20223
  Epoch 020 - train 0.18217 | val 0.20235
  Epoch 023 - train 0.17830 | val 0.20159
  Regression -> MSE: 0.000272, MAE: 0.010807, R²: -0.0397
  Directional -> Accuracy: 0.5068, MCC: 0.0329, F1: 0.5000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.18300 | val 0.15659
  Epoch 020 - train 0.17207 | val 0.15823
  Epoch 021 - train 0.18288 | val 0.15727
  Regression -> MSE: 0.000167, MAE: 0.010368, R²: -0.0047
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.17860 | val 0.18577
  Epoch 020 - train 0.17038 | val 0.18470
  Epoch 021 - train 0.17685 | val 0.18496
  Regression -> MSE: 0.000183, MAE: 0.010420, R²: -0.0149
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.18164 | val 0.18345
  Epoch 020 - train 0.17793 | val 0.18271
  Epoch 021 - train 0.17932 | val 0.18390
  Regression -> MSE: 0.000345, MAE: 0.011746, R²: -0.0065
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.21770 | val 0.12352
  Epoch 020 - train 0.20113 | val 0.12328
  Epoch 021 - train 0.20539 | val 0.12164
  Regression -> MSE: 0.000115, MAE: 0.008353, R²: -0.0894
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.19983 | val 0.30929
  Epoch 020 - train 0.19825 | val 0.30268
  Epoch 021 - train 0.19664 | val 0.30479
  Regression -> MSE: 0.000230, MAE: 0.011660, R²: -0.0525
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.17548 | val 0.35152
  Epoch 020 - train 0.18690 | val 0.35563
  Epoch 021 - train 0.18884 | val 0.35497
  Regression -> MSE: 0.000084, MAE: 0.007167, R²: -0.0860
  Directional -> Accuracy: 0.4894, MCC: 0.0958, F1: 0.4286

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.19063 | val 0.13466
  Epoch 020 - train 0.18838 | val 0.13389
  Epoch 030 - train 0.18395 | val 0.13365
  Regression -> MSE: 0.000369, MAE: 0.016139, R²: -0.2005
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.20685 | val 0.12852
  Epoch 020 - train 0.19102 | val 0.15493
  Epoch 021 - train 0.19698 | val 0.15542
  Regression -> MSE: 0.000251, MAE: 0.011481, R²: -0.0304
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.17613 | val 0.22299
  Epoch 020 - train 0.18044 | val 0.22303
  Epoch 021 - train 0.17924 | val 0.22267
  Regression -> MSE: 0.000081, MAE: 0.007049, R²: 0.0002
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.19310 | val 0.28372
  Epoch 020 - train 0.18884 | val 0.28713
  Epoch 021 - train 0.18687 | val 0.28406
  Regression -> MSE: 0.000307, MAE: 0.014459, R²: -0.0009
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.19553 | val 0.23822
  Epoch 020 - train 0.18946 | val 0.24226
  Epoch 021 - train 0.18996 | val 0.24111
  Regression -> MSE: 0.000105, MAE: 0.007123, R²: -0.0672
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.21271 | val 0.26130
  Epoch 020 - train 0.20591 | val 0.26842
  Epoch 021 - train 0.22025 | val 0.26849
  Regression -> MSE: 0.000172, MAE: 0.009641, R²: 0.0010
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.16558 | val 0.20529
  Epoch 020 - train 0.17917 | val 0.20433
  Epoch 021 - train 0.17941 | val 0.20434
  Regression -> MSE: 0.000223, MAE: 0.011788, R²: 0.0004
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.22013 | val 0.43204
  Epoch 020 - train 0.22618 | val 0.43006
  Epoch 021 - train 0.22867 | val 0.42503
  Regression -> MSE: 0.000106, MAE: 0.008515, R²: -0.1537
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[I 2026-02-24 05:19:56,291] Trial 190 finished with value: -0.011569256099031781 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 64, 'hidden2': 32, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 16, 'learning_rate': 9.764480763743779e-06, 'weight_decay': 2.8522572480707705e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2912936803692335, 'early_stopping_min_delta': 0.006826738738300454}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.18468 | val 0.25868
  Epoch 021 - train 0.19204 | val 0.25792
  Regression -> MSE: 0.000242, MAE: 0.012362, R²: -0.0210
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13835 | val 0.18427
  Epoch 020 - train 0.13231 | val 0.18354
  Epoch 021 - train 0.13747 | val 0.18538
  Regression -> MSE: 0.000249, MAE: 0.012608, R²: -0.0053
  Directional -> Accuracy: 0.4156, MCC: -0.1491, F1: 0.4706

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13641 | val 0.13971
  Epoch 020 - train 0.13757 | val 0.13629
  Epoch 021 - train 0.13476 | val 0.13624
  Regression -> MSE: 0.000715, MAE: 0.019867, R²: -0.0443
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13749 | val 0.23118
  Epoch 020 - train 0.14098 | val 0.23107
  Epoch 021 - train 0.14350 | val 0.23058
  Regression -> MSE: 0.000322, MAE: 0.014556, R²: -0.0389
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12403 | val 0.16970
  Epoch 020 - train 0.11937 | val 0.17813
  Epoch 021 - train 0.12154 | val 0.16996
  Regression -> MSE: 0.000366, MAE: 0.014848, R²: -0.0489
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14493 | val 0.22339
  Epoch 020 - train 0.14835 | val 0.22729
  Epoch 021 - train 0.14924 | val 0.22653
  Regression -> MSE: 0.000211, MAE: 0.010727, R²: -0.0358
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12442 | val 0.25660
  Epoch 020 - train 0.13353 | val 0.25822
  Epoch 021 - train 0.13309 | val 0.25810
  Regression -> MSE: 0.000563, MAE: 0.018222, R²: -0.0135
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13988 | val 0.17881
  Epoch 020 - train 0.14591 | val 0.18403
  Epoch 021 - train 0.14213 | val 0.18249
  Regression -> MSE: 0.000250, MAE: 0.011936, R²: -0.0174
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.14114 | val 0.16180
  Epoch 020 - train 0.13024 | val 0.16367
  Epoch 030 - train 0.13361 | val 0.17017
  Regression -> MSE: 0.000608, MAE: 0.019466, R²: -0.0180
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14098 | val 0.16863
  Epoch 020 - train 0.13221 | val 0.16752
  Epoch 021 - train 0.14032 | val 0.16698
  Regression -> MSE: 0.000389, MAE: 0.016033, R²: -0.0134
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14423 | val 0.17952
  Epoch 020 - train 0.14269 | val 0.18103
  Epoch 021 - train 0.14283 | val 0.18025
  Regression -> MSE: 0.000242, MAE: 0.012094, R²: -0.0040
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12538 | val 0.23157
  Epoch 020 - train 0.12737 | val 0.23922
  Epoch 021 - train 0.13306 | val 0.24230
  Regression -> MSE: 0.000319, MAE: 0.013582, R²: -0.0267
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15107 | val 0.16856
  Epoch 020 - train 0.15732 | val 0.16774
  Epoch 021 - train 0.14936 | val 0.16651
  Regression -> MSE: 0.000687, MAE: 0.019853, R²: -0.0151
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13527 | val 0.15509
  Epoch 020 - train 0.14021 | val 0.16162
  Epoch 021 - train 0.12841 | val 0.16216
  Regression -> MSE: 0.000142, MAE: 0.009404, R²: -0.0304
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12898 | val 0.19916
  Epoch 020 - train 0.12137 | val 0.19650
  Epoch 021 - train 0.12865 | val 0.19921
  Regression -> MSE: 0.000226, MAE: 0.010794, R²: -0.0037
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14260 | val 0.35101
  Epoch 020 - train 0.14690 | val 0.35102
  Epoch 021 - train 0.14331 | val 0.34470
  Regression -> MSE: 0.000373, MAE: 0.015940, R²: -0.0289
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14299 | val 0.16566
  Epoch 020 - train 0.14457 | val 0.16990
  Epoch 021 - train 0.13970 | val 0.16869
  Regression -> MSE: 0.000108, MAE: 0.008096, R²: -0.0037
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14011 | val 0.23925
  Epoch 020 - train 0.13289 | val 0.24442
  Epoch 021 - train 0.13547 | val 0.24690
  Regression -> MSE: 0.000156, MAE: 0.009754, R²: -0.0005
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15083 | val 0.15110
  Epoch 020 - train 0.14865 | val 0.15358
  Epoch 021 - train 0.14819 | val 0.15407
  Regression -> MSE: 0.000280, MAE: 0.012900, R²: -0.0289
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13185 | val 0.20368
  Epoch 020 - train 0.12716 | val 0.19826
  Epoch 021 - train 0.12232 | val 0.19684
  Regression -> MSE: 0.000164, MAE: 0.009002, R²: -0.0933
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13766 | val 0.18872
  Epoch 020 - train 0.14232 | val 0.18954
  Epoch 025 - train 0.13913 | val 0.19059
  Regression -> MSE: 0.000353, MAE: 0.014133, R²: -0.5621
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16336 | val 0.19487
  Epoch 020 - train 0.15688 | val 0.18980
  Epoch 021 - train 0.15621 | val 0.19067
  Regression -> MSE: 0.000143, MAE: 0.008299, R²: 0.0015
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13465 | val 0.17445
  Epoch 020 - train 0.12936 | val 0.17473
  Epoch 021 - train 0.14140 | val 0.17325
  Regression -> MSE: 0.000165, MAE: 0.010598, R²: -0.0016
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14882 | val 0.16186
  Epoch 020 - train 0.13772 | val 0.16544
  Epoch 021 - train 0.14414 | val 0.16672
  Regression -> MSE: 0.000087, MAE: 0.007155, R²: -0.0214
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14109 | val 0.17193
  Epoch 020 - train 0.14394 | val 0.17614
  Epoch 021 - train 0.14380 | val 0.17516
  Regression -> MSE: 0.000213, MAE: 0.011232, R²: -0.0035
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13693 | val 0.11680
  Epoch 020 - train 0.12842 | val 0.11408
  Epoch 028 - train 0.13139 | val 0.11232
  Regression -> MSE: 0.000107, MAE: 0.008739, R²: -0.1643
  Directional -> Accuracy: 0.3929, MCC: -0.2642, F1: 0.5000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14954 | val 0.11798
  Epoch 020 - train 0.14306 | val 0.12030
  Epoch 021 - train 0.14694 | val 0.12094
  Regression -> MSE: 0.000104, MAE: 0.008819, R²: -0.0124
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14293 | val 0.13084
  Epoch 020 - train 0.14326 | val 0.13051
  Epoch 021 - train 0.14106 | val 0.13050
  Regression -> MSE: 0.000232, MAE: 0.012501, R²: -0.0006
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14394 | val 0.15769
  Epoch 020 - train 0.14157 | val 0.15843
  Epoch 021 - train 0.13976 | val 0.15886
  Regression -> MSE: 0.000191, MAE: 0.008183, R²: -0.1465
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13954 | val 0.12515
  Epoch 020 - train 0.13952 | val 0.13620
  Epoch 021 - train 0.14118 | val 0.13606
  Regression -> MSE: 0.000237, MAE: 0.011871, R²: -0.0017
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14342 | val 0.22305
  Epoch 020 - train 0.14298 | val 0.22485
  Epoch 021 - train 0.14614 | val 0.22453
  Regression -> MSE: 0.000236, MAE: 0.010207, R²: -0.0230
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.15009 | val 0.16320
  Epoch 020 - train 0.14549 | val 0.16256
  Epoch 026 - train 0.14800 | val 0.16224
  Regression -> MSE: 0.000137, MAE: 0.008231, R²: -0.0142
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13673 | val 0.17749
  Epoch 020 - train 0.13901 | val 0.17800
  Epoch 021 - train 0.14215 | val 0.17881
  Regression -> MSE: 0.000193, MAE: 0.010471, R²: -0.0269
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12685 | val 0.15317
  Epoch 020 - train 0.12500 | val 0.15295
  Epoch 021 - train 0.12255 | val 0.15293
  Regression -> MSE: 0.000276, MAE: 0.010806, R²: -0.0544
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13161 | val 0.11568
  Epoch 020 - train 0.12977 | val 0.13901
  Epoch 021 - train 0.13243 | val 0.13947
  Regression -> MSE: 0.000167, MAE: 0.010365, R²: 0.0007
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13054 | val 0.13913
  Epoch 020 - train 0.12998 | val 0.14100
  Epoch 021 - train 0.12980 | val 0.14106
  Regression -> MSE: 0.000184, MAE: 0.010472, R²: -0.0239
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13667 | val 0.13417
  Epoch 020 - train 0.13398 | val 0.13458
  Epoch 021 - train 0.13560 | val 0.13403
  Regression -> MSE: 0.000344, MAE: 0.011689, R²: -0.0045
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14962 | val 0.09092
  Epoch 020 - train 0.14512 | val 0.09107
  Epoch 021 - train 0.15101 | val 0.09048
  Regression -> MSE: 0.000123, MAE: 0.008415, R²: -0.1710
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14324 | val 0.19959
  Epoch 020 - train 0.13835 | val 0.19080
  Epoch 021 - train 0.13336 | val 0.19044
  Regression -> MSE: 0.000222, MAE: 0.011417, R²: -0.0169
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13959 | val 0.23173
  Epoch 020 - train 0.13927 | val 0.23231
  Epoch 021 - train 0.13533 | val 0.23252
  Regression -> MSE: 0.000093, MAE: 0.007518, R²: -0.1920
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13684 | val 0.10434
  Epoch 020 - train 0.13766 | val 0.10168
  Epoch 030 - train 0.13399 | val 0.10162
  Regression -> MSE: 0.000311, MAE: 0.014170, R²: -0.0104
  Directional -> Accuracy: 0.4490, MCC: 0.0707, F1: 0.5263

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15310 | val 0.09622
  Epoch 020 - train 0.15451 | val 0.11396
  Epoch 021 - train 0.14280 | val 0.11368
  Regression -> MSE: 0.000265, MAE: 0.011544, R²: -0.0856
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13747 | val 0.15900
  Epoch 020 - train 0.13186 | val 0.16725
  Epoch 021 - train 0.13497 | val 0.16714
  Regression -> MSE: 0.000081, MAE: 0.007059, R²: 0.0013
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14239 | val 0.16789
  Epoch 020 - train 0.14154 | val 0.17040
  Epoch 028 - train 0.14779 | val 0.16946
  Regression -> MSE: 0.000330, MAE: 0.014760, R²: -0.0756
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13294 | val 0.15834
  Epoch 020 - train 0.13227 | val 0.15772
  Epoch 021 - train 0.13665 | val 0.15797
  Regression -> MSE: 0.000101, MAE: 0.007106, R²: -0.0301
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13956 | val 0.16577
  Epoch 020 - train 0.16173 | val 0.17226
  Epoch 021 - train 0.15071 | val 0.17334
  Regression -> MSE: 0.000172, MAE: 0.009617, R²: -0.0014
  Directional -> Accuracy: 0.4490, MCC: -0.1289, F1: 0.3415

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13363 | val 0.15706
  Epoch 020 - train 0.13259 | val 0.15585
  Epoch 021 - train 0.13287 | val 0.15670
  Regression -> MSE: 0.000224, MAE: 0.011745, R²: -0.0024
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14941 | val 0.17565
  Epoch 020 - train 0.14134 | val 0.17656
  Epoch 021 - train 0.14693 | val 0.17895
  Regression -> MSE: 0.000098, MAE: 0.007996, R²: -0.0579

[I 2026-02-24 05:22:34,719] Trial 191 finished with value: -0.011531299565805222 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.5, 'batch_size': 16, 'learning_rate': 1.4214613779590332e-05, 'weight_decay': 3.493086818394956e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.20959606364063704, 'early_stopping_min_delta': 0.007216267497578194}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.14330 | val 0.20027
  Epoch 021 - train 0.14234 | val 0.20136
  Regression -> MSE: 0.000238, MAE: 0.012353, R²: -0.0023
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.17524 | val 0.21413
  Epoch 020 - train 0.16533 | val 0.21256
  Epoch 030 - train 0.16895 | val 0.21118
  Regression -> MSE: 0.000254, MAE: 0.012698, R²: -0.0279
  Directional -> Accuracy: 0.5325, MCC: 0.0120, F1: 0.2800

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16823 | val 0.15454
  Epoch 020 - train 0.16731 | val 0.15518
  Epoch 021 - train 0.15498 | val 0.15468
  Regression -> MSE: 0.000717, MAE: 0.019921, R²: -0.0471
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.17565 | val 0.32206
  Epoch 020 - train 0.18158 | val 0.31857
  Epoch 021 - train 0.17741 | val 0.31597
  Regression -> MSE: 0.000320, MAE: 0.014542, R²: -0.0329
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15244 | val 0.15153
  Epoch 020 - train 0.15177 | val 0.14939
  Epoch 021 - train 0.15244 | val 0.16460
  Regression -> MSE: 0.000352, MAE: 0.014607, R²: -0.0083
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16865 | val 0.15881
  Epoch 020 - train 0.16799 | val 0.15948
  Epoch 026 - train 0.16237 | val 0.16378
  Regression -> MSE: 0.000199, MAE: 0.009817, R²: 0.0218
  Directional -> Accuracy: 0.6667, MCC: 0.3835, F1: 0.6047

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.17297 | val 0.33920
  Epoch 020 - train 0.16349 | val 0.34255
  Epoch 021 - train 0.16056 | val 0.34164
  Regression -> MSE: 0.000557, MAE: 0.018168, R²: -0.0026
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.6571

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.17651 | val 0.21035
  Epoch 020 - train 0.17419 | val 0.21036
  Epoch 021 - train 0.17011 | val 0.20960
  Regression -> MSE: 0.000246, MAE: 0.012091, R²: -0.0019
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.17397 | val 0.22771
  Epoch 020 - train 0.17306 | val 0.27603
  Epoch 022 - train 0.17050 | val 0.27336
  Regression -> MSE: 0.000621, MAE: 0.019718, R²: -0.0400
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.16915 | val 0.23561
  Epoch 020 - train 0.16945 | val 0.23585
  Epoch 021 - train 0.16896 | val 0.23445
  Regression -> MSE: 0.000387, MAE: 0.016068, R²: -0.0076
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.18796 | val 0.23820
  Epoch 020 - train 0.18425 | val 0.23595
  Epoch 022 - train 0.18733 | val 0.23384
  Regression -> MSE: 0.000241, MAE: 0.011983, R²: 0.0001
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15511 | val 0.25749
  Epoch 020 - train 0.15300 | val 0.26178
  Epoch 021 - train 0.15711 | val 0.26139
  Regression -> MSE: 0.000313, MAE: 0.013650, R²: -0.0072
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.18935 | val 0.21960
  Epoch 020 - train 0.17090 | val 0.21757
  Epoch 021 - train 0.18188 | val 0.21821
  Regression -> MSE: 0.000686, MAE: 0.019799, R²: -0.0126
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17450 | val 0.19900
  Epoch 020 - train 0.16722 | val 0.19819
  Epoch 021 - train 0.17901 | val 0.19749
  Regression -> MSE: 0.000139, MAE: 0.009184, R²: -0.0033
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15980 | val 0.21270
  Epoch 020 - train 0.16352 | val 0.21116
  Epoch 030 - train 0.15289 | val 0.20961
  Regression -> MSE: 0.000241, MAE: 0.011564, R²: -0.0723
  Directional -> Accuracy: 0.5082, MCC: 0.0197, F1: 0.4643

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.17314 | val 0.33038
  Epoch 020 - train 0.16184 | val 0.33203
  Epoch 026 - train 0.17374 | val 0.33093
  Regression -> MSE: 0.000394, MAE: 0.015737, R²: -0.0877
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.17632 | val 0.19768
  Epoch 020 - train 0.16828 | val 0.19661
  Epoch 022 - train 0.17613 | val 0.19421
  Regression -> MSE: 0.000108, MAE: 0.007883, R²: -0.0030
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.18369 | val 0.27782
  Epoch 020 - train 0.17893 | val 0.26935
  Epoch 024 - train 0.17978 | val 0.26842
  Regression -> MSE: 0.000173, MAE: 0.010687, R²: -0.1073
  Directional -> Accuracy: 0.3220, MCC: -0.2688, F1: 0.0476

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.18173 | val 0.22455
  Epoch 020 - train 0.17327 | val 0.20897
  Epoch 021 - train 0.17596 | val 0.20369
  Regression -> MSE: 0.000292, MAE: 0.013915, R²: -0.0737
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.16451 | val 0.22155
  Epoch 020 - train 0.16050 | val 0.22031
  Epoch 030 - train 0.15642 | val 0.21831
  Regression -> MSE: 0.000166, MAE: 0.009909, R²: -0.1082
  Directional -> Accuracy: 0.5538, MCC: -0.0531, F1: 0.7010

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.17500 | val 0.25137
  Epoch 020 - train 0.17245 | val 0.24865
  Epoch 023 - train 0.17017 | val 0.25045
  Regression -> MSE: 0.000256, MAE: 0.011485, R²: -0.1313
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17857 | val 0.20628
  Epoch 020 - train 0.17232 | val 0.20781
  Epoch 025 - train 0.16996 | val 0.20524
  Regression -> MSE: 0.000148, MAE: 0.008650, R²: -0.0357
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.16783 | val 0.19310
  Epoch 020 - train 0.15745 | val 0.19475
  Epoch 027 - train 0.15240 | val 0.19638
  Regression -> MSE: 0.000233, MAE: 0.012899, R²: -0.4124
  Directional -> Accuracy: 0.4697, MCC: -0.0845, F1: 0.6067

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.17234 | val 0.19470
  Epoch 020 - train 0.17561 | val 0.19136
  Epoch 030 - train 0.17497 | val 0.19133
  Regression -> MSE: 0.000083, MAE: 0.006973, R²: 0.0315
  Directional -> Accuracy: 0.5000, MCC: -0.0571, F1: 0.6027

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.16605 | val 0.20436
  Epoch 020 - train 0.17297 | val 0.20561
  Epoch 023 - train 0.15931 | val 0.20768
  Regression -> MSE: 0.000212, MAE: 0.011287, R²: 0.0007
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.16072 | val 0.15358
  Epoch 020 - train 0.15783 | val 0.15071
  Epoch 021 - train 0.15853 | val 0.15092
  Regression -> MSE: 0.000101, MAE: 0.008242, R²: -0.0965
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16753 | val 0.13134
  Epoch 020 - train 0.17569 | val 0.13213
  Epoch 021 - train 0.17589 | val 0.13247
  Regression -> MSE: 0.000107, MAE: 0.008913, R²: -0.0333
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.18523 | val 0.24447
  Epoch 020 - train 0.18201 | val 0.22818
  Epoch 021 - train 0.17395 | val 0.22921
  Regression -> MSE: 0.000234, MAE: 0.012659, R²: -0.0104
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.17257 | val 0.20344
  Epoch 020 - train 0.17212 | val 0.20039
  Epoch 021 - train 0.16674 | val 0.20045
  Regression -> MSE: 0.000172, MAE: 0.007858, R²: -0.0357
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.17749 | val 0.13850
  Epoch 020 - train 0.18288 | val 0.14404
  Epoch 028 - train 0.18727 | val 0.14332
  Regression -> MSE: 0.000234, MAE: 0.011902, R²: 0.0110
  Directional -> Accuracy: 0.5366, MCC: 0.0528, F1: 0.6122

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.17543 | val 0.30199
  Epoch 020 - train 0.19034 | val 0.30993
  Epoch 021 - train 0.17199 | val 0.30909
  Regression -> MSE: 0.000237, MAE: 0.010299, R²: -0.0298
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.20022 | val 0.25860
  Epoch 020 - train 0.17926 | val 0.25928
  Epoch 021 - train 0.18063 | val 0.26080
  Regression -> MSE: 0.000140, MAE: 0.008469, R²: -0.0390
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.21415 | val 0.24994
  Epoch 020 - train 0.19488 | val 0.24217
  Epoch 021 - train 0.18801 | val 0.24137
  Regression -> MSE: 0.000189, MAE: 0.010476, R²: -0.0014
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15436 | val 0.17983
  Epoch 020 - train 0.14954 | val 0.18160
  Epoch 024 - train 0.14880 | val 0.18129
  Regression -> MSE: 0.000392, MAE: 0.013701, R²: -0.4982
  Directional -> Accuracy: 0.5068, MCC: 0.2396, F1: 0.2174

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.17198 | val 0.13878
  Epoch 020 - train 0.16943 | val 0.14941
  Epoch 029 - train 0.15196 | val 0.14849
  Regression -> MSE: 0.000161, MAE: 0.010284, R²: 0.0329
  Directional -> Accuracy: 0.5526, MCC: 0.2357, F1: 0.6909

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.17767 | val 0.17340
  Epoch 020 - train 0.17071 | val 0.16585
  Epoch 024 - train 0.16529 | val 0.16933
  Regression -> MSE: 0.000179, MAE: 0.010172, R²: 0.0074
  Directional -> Accuracy: 0.5909, MCC: 0.1923, F1: 0.4000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16106 | val 0.14619
  Epoch 020 - train 0.15948 | val 0.14680
  Epoch 029 - train 0.15332 | val 0.14754
  Regression -> MSE: 0.000356, MAE: 0.013280, R²: -0.0388
  Directional -> Accuracy: 0.5970, MCC: 0.1899, F1: 0.6301

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18720 | val 0.11519
  Epoch 020 - train 0.18637 | val 0.11892
  Epoch 021 - train 0.17111 | val 0.11826
  Regression -> MSE: 0.000124, MAE: 0.008446, R²: -0.1793
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16439 | val 0.25112
  Epoch 020 - train 0.16141 | val 0.24923
  Epoch 021 - train 0.16603 | val 0.24897
  Regression -> MSE: 0.000219, MAE: 0.011295, R²: -0.0012
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.17650 | val 0.29328
  Epoch 020 - train 0.16853 | val 0.29307
  Epoch 021 - train 0.16286 | val 0.29353
  Regression -> MSE: 0.000094, MAE: 0.007569, R²: -0.2103
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.16435 | val 0.12180
  Epoch 020 - train 0.16229 | val 0.12028
  Epoch 030 - train 0.15783 | val 0.12068
  Regression -> MSE: 0.000367, MAE: 0.016256, R²: -0.1918
  Directional -> Accuracy: 0.3469, MCC: -0.1627, F1: 0.4839

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.18134 | val 0.10154
  Epoch 020 - train 0.16978 | val 0.10543
  Epoch 030 - train 0.18112 | val 0.10728
  Regression -> MSE: 0.000259, MAE: 0.011447, R²: -0.0620
  Directional -> Accuracy: 0.5526, MCC: 0.1733, F1: 0.7018

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.18049 | val 0.20006
  Epoch 020 - train 0.16930 | val 0.20983
  Epoch 024 - train 0.15674 | val 0.21089
  Regression -> MSE: 0.000083, MAE: 0.007192, R²: -0.0260
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.17895 | val 0.23791
  Epoch 020 - train 0.15371 | val 0.25914
  Epoch 026 - train 0.17555 | val 0.25726
  Regression -> MSE: 0.000326, MAE: 0.014733, R²: -0.0637
  Directional -> Accuracy: 0.4681, MCC: -0.0926, F1: 0.0741

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16519 | val 0.17417
  Epoch 020 - train 0.16223 | val 0.16605
  Epoch 030 - train 0.15342 | val 0.16643
  Regression -> MSE: 0.000100, MAE: 0.007305, R²: -0.0166
  Directional -> Accuracy: 0.4773, MCC: -0.0586, F1: 0.5306

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.18799 | val 0.21896
  Epoch 020 - train 0.19616 | val 0.22406
  Epoch 021 - train 0.18123 | val 0.22419
  Regression -> MSE: 0.000172, MAE: 0.009516, R²: -0.0023
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.15281 | val 0.19067
  Epoch 020 - train 0.15828 | val 0.18913
  Epoch 021 - train 0.16035 | val 0.18802
  Regression -> MSE: 0.000226, MAE: 0.011831, R²: -0.0113
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.17727 | val 0.18624
  Epoch 020 - train 0.17000 | val 0.18706
  Epoch 021 - train 0.16849 | val 0.18505
  Regression -> MSE: 0.000092, MAE: 0.007625, R²: 0.0043
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[I 2026-02-24 05:25:45,125] Trial 192 finished with value: -0.011688885834785986 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 1.1180670968677533e-05, 'weight_decay': 2.075777677281245e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2550820790368306, 'early_stopping_min_delta': 0.000722480498745264}. Best is trial 44 with value: -0.011362814469631832.

Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12628 | val 0.16209
  Epoch 020 - train 0.12786 | val 0.16147
  Epoch 021 - train 0.12226 | val 0.16348
  Regression -> MSE: 0.000253, MAE: 0.012751, R²: -0.0202
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13525 | val 0.15041
  Epoch 020 - train 0.12869 | val 0.15503
  Epoch 021 - train 0.14270 | val 0.15448
  Regression -> MSE: 0.000712, MAE: 0.019811, R²: -0.0396
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12947 | val 0.19969
  Epoch 020 - train 0.13345 | val 0.19713
  Epoch 021 - train 0.12616 | val 0.19755
  Regression -> MSE: 0.000310, MAE: 0.014412, R²: -0.0006
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11673 | val 0.11083
  Epoch 020 - train 0.10961 | val 0.10957
  Epoch 021 - train 0.11438 | val 0.11251
  Regression -> MSE: 0.000373, MAE: 0.014970, R²: -0.0689
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12871 | val 0.13152
  Epoch 020 - train 0.12630 | val 0.13233
  Epoch 021 - train 0.12269 | val 0.13175
  Regression -> MSE: 0.000205, MAE: 0.010301, R²: -0.0057
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11710 | val 0.22815
  Epoch 020 - train 0.12113 | val 0.22774
  Epoch 021 - train 0.11568 | val 0.22879
  Regression -> MSE: 0.000577, MAE: 0.018517, R²: -0.0389
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13749 | val 0.16537
  Epoch 020 - train 0.13853 | val 0.16714
  Epoch 021 - train 0.13473 | val 0.16533
  Regression -> MSE: 0.000257, MAE: 0.012061, R²: -0.0473
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13274 | val 0.15507
  Epoch 020 - train 0.13092 | val 0.15268
  Epoch 030 - train 0.13129 | val 0.14865
  Regression -> MSE: 0.000606, MAE: 0.019355, R²: -0.0136
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12505 | val 0.14340
  Epoch 020 - train 0.11724 | val 0.14281
  Epoch 021 - train 0.12306 | val 0.14267
  Regression -> MSE: 0.000393, MAE: 0.015944, R²: -0.0233
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13468 | val 0.15626
  Epoch 020 - train 0.13245 | val 0.15589
  Epoch 021 - train 0.12749 | val 0.15594
  Regression -> MSE: 0.000249, MAE: 0.011663, R²: -0.0313
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12522 | val 0.17174
  Epoch 020 - train 0.11938 | val 0.17984
  Epoch 021 - train 0.12527 | val 0.18058
  Regression -> MSE: 0.000312, MAE: 0.013648, R²: -0.0025
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13350 | val 0.14892
  Epoch 020 - train 0.12551 | val 0.15102
  Epoch 021 - train 0.13523 | val 0.15173
  Regression -> MSE: 0.000688, MAE: 0.019915, R²: -0.0165
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12455 | val 0.17956
  Epoch 020 - train 0.12064 | val 0.18433
  Epoch 021 - train 0.11787 | val 0.18119
  Regression -> MSE: 0.000142, MAE: 0.009373, R²: -0.0259
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12390 | val 0.16811
  Epoch 020 - train 0.11038 | val 0.16838
  Epoch 021 - train 0.11623 | val 0.16618
  Regression -> MSE: 0.000226, MAE: 0.010727, R²: -0.0062
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13047 | val 0.28990
  Epoch 020 - train 0.13227 | val 0.28091
  Epoch 021 - train 0.12740 | val 0.28247
  Regression -> MSE: 0.000365, MAE: 0.016307, R²: -0.0078
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13708 | val 0.11754
  Epoch 020 - train 0.12955 | val 0.11629
  Epoch 021 - train 0.13217 | val 0.11647
  Regression -> MSE: 0.000111, MAE: 0.007955, R²: -0.0329
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13359 | val 0.23771
  Epoch 020 - train 0.13034 | val 0.23921
  Epoch 021 - train 0.12534 | val 0.23814
  Regression -> MSE: 0.000157, MAE: 0.009681, R²: -0.0044
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13828 | val 0.19706
  Epoch 020 - train 0.13533 | val 0.19152
  Epoch 021 - train 0.13778 | val 0.18989
  Regression -> MSE: 0.000300, MAE: 0.014177, R²: -0.1010
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11796 | val 0.15661
  Epoch 020 - train 0.11023 | val 0.15641
  Epoch 021 - train 0.11374 | val 0.15620
  Regression -> MSE: 0.000167, MAE: 0.009114, R²: -0.1151
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13269 | val 0.16816
  Epoch 020 - train 0.13107 | val 0.16561
  Epoch 021 - train 0.12675 | val 0.16563
  Regression -> MSE: 0.000245, MAE: 0.011173, R²: -0.0815
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13108 | val 0.15695
  Epoch 020 - train 0.12613 | val 0.15747
  Epoch 021 - train 0.13080 | val 0.16004
  Regression -> MSE: 0.000151, MAE: 0.008705, R²: -0.0512
  Directional -> Accuracy: 0.5833, MCC: 0.1943, F1: 0.6154

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12112 | val 0.14142
  Epoch 020 - train 0.11713 | val 0.14281
  Epoch 021 - train 0.12176 | val 0.14297
  Regression -> MSE: 0.000166, MAE: 0.010708, R²: -0.0066
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13010 | val 0.14870
  Epoch 020 - train 0.12699 | val 0.15131
  Epoch 021 - train 0.12732 | val 0.15071
  Regression -> MSE: 0.000086, MAE: 0.007080, R²: -0.0068
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13074 | val 0.26563
  Epoch 020 - train 0.12602 | val 0.25815
  Epoch 021 - train 0.11956 | val 0.25791
  Regression -> MSE: 0.000211, MAE: 0.011070, R²: 0.0037
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12025 | val 0.12592
  Epoch 020 - train 0.12381 | val 0.11904
  Epoch 021 - train 0.12053 | val 0.12003
  Regression -> MSE: 0.000094, MAE: 0.008140, R²: -0.0244
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13233 | val 0.10045
  Epoch 020 - train 0.12962 | val 0.10536
  Epoch 021 - train 0.13396 | val 0.10479
  Regression -> MSE: 0.000106, MAE: 0.008881, R²: -0.0269
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13138 | val 0.11578
  Epoch 020 - train 0.12845 | val 0.11867
  Epoch 021 - train 0.13348 | val 0.11911
  Regression -> MSE: 0.000233, MAE: 0.012608, R²: -0.0062
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12398 | val 0.14468
  Epoch 020 - train 0.12790 | val 0.14407
  Epoch 021 - train 0.12387 | val 0.14443
  Regression -> MSE: 0.000171, MAE: 0.007838, R²: -0.0246
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13492 | val 0.10649
  Epoch 020 - train 0.13989 | val 0.16632
  Epoch 028 - train 0.13326 | val 0.15553
  Regression -> MSE: 0.000237, MAE: 0.011972, R²: -0.0008
  Directional -> Accuracy: 0.4634, MCC: -0.0872, F1: 0.5217

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14698 | val 0.20035
  Epoch 020 - train 0.13616 | val 0.20089
  Epoch 021 - train 0.14172 | val 0.19957
  Regression -> MSE: 0.000230, MAE: 0.009849, R²: 0.0014
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13205 | val 0.14144
  Epoch 020 - train 0.13199 | val 0.14032
  Epoch 030 - train 0.12744 | val 0.14048
  Regression -> MSE: 0.000135, MAE: 0.008508, R²: 0.0020
  Directional -> Accuracy: 0.4651, MCC: -0.1062, F1: 0.5660

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13192 | val 0.14841
  Epoch 020 - train 0.12815 | val 0.14957
  Epoch 021 - train 0.13102 | val 0.14958
  Regression -> MSE: 0.000196, MAE: 0.010551, R²: -0.0400
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11875 | val 0.19300
  Epoch 020 - train 0.11800 | val 0.18918
  Epoch 021 - train 0.11244 | val 0.18915
  Regression -> MSE: 0.000262, MAE: 0.010654, R²: -0.0023
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11372 | val 0.12035
  Epoch 020 - train 0.11430 | val 0.19846
  Epoch 021 - train 0.12515 | val 0.19732
  Regression -> MSE: 0.000168, MAE: 0.010364, R²: -0.0063
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13039 | val 0.20756
  Epoch 020 - train 0.13014 | val 0.20285
  Epoch 021 - train 0.12519 | val 0.19935
  Regression -> MSE: 0.000189, MAE: 0.010685, R²: -0.0486
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12698 | val 0.12018
  Epoch 020 - train 0.12522 | val 0.11700
  Epoch 021 - train 0.12691 | val 0.11681
  Regression -> MSE: 0.000351, MAE: 0.012383, R²: -0.0245
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14725 | val 0.09849
  Epoch 020 - train 0.13988 | val 0.10343
  Epoch 021 - train 0.13739 | val 0.10321
  Regression -> MSE: 0.000109, MAE: 0.008354, R²: -0.0413
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13165 | val 0.16702
  Epoch 020 - train 0.12736 | val 0.16747
  Epoch 021 - train 0.12751 | val 0.16718
  Regression -> MSE: 0.000220, MAE: 0.011362, R²: -0.0053
  Directional -> Accuracy: 0.3333, MCC: -0.3604, F1: 0.2083

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13060 | val 0.21886
  Epoch 020 - train 0.12621 | val 0.22022
  Epoch 021 - train 0.12665 | val 0.21991
  Regression -> MSE: 0.000081, MAE: 0.006985, R²: -0.0367
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13027 | val 0.09877
  Epoch 020 - train 0.12264 | val 0.10446
  Epoch 021 - train 0.12034 | val 0.10369
  Regression -> MSE: 0.000311, MAE: 0.014039, R²: -0.0125
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13349 | val 0.07492
  Epoch 020 - train 0.13567 | val 0.07471
  Epoch 021 - train 0.12802 | val 0.07575
  Regression -> MSE: 0.000259, MAE: 0.011486, R²: -0.0606
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12838 | val 0.15746
  Epoch 020 - train 0.12372 | val 0.15610
  Epoch 021 - train 0.12286 | val 0.15459
  Regression -> MSE: 0.000081, MAE: 0.007099, R²: -0.0041
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13593 | val 0.16076
  Epoch 020 - train 0.12844 | val 0.16183
  Epoch 021 - train 0.12581 | val 0.16015
  Regression -> MSE: 0.000307, MAE: 0.014486, R²: -0.0005
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12753 | val 0.13629
  Epoch 020 - train 0.11772 | val 0.14496
  Epoch 021 - train 0.11963 | val 0.14480
  Regression -> MSE: 0.000099, MAE: 0.007232, R²: -0.0053
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14505 | val 0.16446
  Epoch 020 - train 0.14710 | val 0.17205
  Epoch 021 - train 0.14858 | val 0.17266
  Regression -> MSE: 0.000175, MAE: 0.010160, R²: -0.0186
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12629 | val 0.15746
  Epoch 020 - train 0.12421 | val 0.15982
  Epoch 021 - train 0.12226 | val 0.15667
  Regression -> MSE: 0.000227, MAE: 0.011869, R²: -0.0195
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12487 | val 0.16731
  Epoch 020 - train 0.12574 | val 0.16476
  Epoch 021 - train 0.12168 | val 0.16676
  Regression -> MSE: 0.000092, MAE: 0.007625, R²: 0.0020
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.12674 | val 0.19084
  Epoch 020 - train 0.12905 | val 0.19183
  Epoch 021 - train 0.13062 | val 0.19144
  Regression -> MSE: 0.000164, MAE: 0.010242, R²: -0.0015
  Directional -> Accuracy: 0.5556, MCC: 0.1131, F1: 0.6667

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.12013 | val 0.14904
  Epoch 020 - train 0.12320 | val 0.15013
  Epoch 021 - train 0.12346 | val 0.14951
  Regression -> MSE: 0.000118, MAE: 0.008958, R²: -0.0165
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.13565 | val 0.16847
  Epoch 020 - train 0.13242 | val 0.16826
  Epoch 021 - train 0.12932 | val 0.16831

[I 2026-02-24 05:28:37,201] Trial 193 finished with value: -0.011482911885978902 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 8.34496827815995e-06, 'weight_decay': 1.5274263639770246e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.17964678946086368, 'early_stopping_min_delta': 0.006636043254312476}. Best is trial 44 with value: -0.011362814469631832.

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15101 | val 0.19749
  Epoch 020 - train 0.15098 | val 0.19034
  Epoch 030 - train 0.15048 | val 0.19285
  Regression -> MSE: 0.000272, MAE: 0.013278, R²: -0.0973
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16349 | val 0.13580
  Epoch 020 - train 0.14964 | val 0.14360
  Epoch 021 - train 0.17032 | val 0.14539
  Regression -> MSE: 0.000711, MAE: 0.019813, R²: -0.0379
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15873 | val 0.23857
  Epoch 020 - train 0.15891 | val 0.23813
  Epoch 021 - train 0.14713 | val 0.23815
  Regression -> MSE: 0.000310, MAE: 0.014380, R²: 0.0012
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12924 | val 0.12163
  Epoch 020 - train 0.12564 | val 0.12299
  Epoch 021 - train 0.13068 | val 0.12285
  Regression -> MSE: 0.000366, MAE: 0.014854, R²: -0.0492
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.16003 | val 0.14795
  Epoch 020 - train 0.16151 | val 0.15300
  Epoch 021 - train 0.15162 | val 0.15323
  Regression -> MSE: 0.000210, MAE: 0.010187, R²: -0.0292
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.16140 | val 0.28387
  Epoch 020 - train 0.15635 | val 0.28795
  Epoch 021 - train 0.15874 | val 0.28858
  Regression -> MSE: 0.000616, MAE: 0.019400, R²: -0.1090
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15301 | val 0.17978
  Epoch 020 - train 0.15614 | val 0.17873
  Epoch 021 - train 0.15003 | val 0.17887
  Regression -> MSE: 0.000246, MAE: 0.011962, R²: -0.0008
  Directional -> Accuracy: 0.5797, MCC: 0.0948, F1: 0.4082

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.16775 | val 0.21515
  Epoch 020 - train 0.16920 | val 0.21480
  Epoch 021 - train 0.17146 | val 0.21486
  Regression -> MSE: 0.000664, MAE: 0.020459, R²: -0.1121
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.15308 | val 0.17318
  Epoch 020 - train 0.15291 | val 0.17307
  Epoch 021 - train 0.15268 | val 0.17315
  Regression -> MSE: 0.000402, MAE: 0.016090, R²: -0.0474
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15390 | val 0.18730
  Epoch 020 - train 0.15295 | val 0.19184
  Epoch 021 - train 0.15501 | val 0.19207
  Regression -> MSE: 0.000246, MAE: 0.011632, R²: -0.0185
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15489 | val 0.20301
  Epoch 020 - train 0.15627 | val 0.20049
  Epoch 021 - train 0.15069 | val 0.20025
  Regression -> MSE: 0.000326, MAE: 0.013613, R²: -0.0472
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15439 | val 0.16960
  Epoch 020 - train 0.15519 | val 0.18267
  Epoch 021 - train 0.14943 | val 0.18507
  Regression -> MSE: 0.000678, MAE: 0.019508, R²: -0.0007
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.15310 | val 0.15361
  Epoch 020 - train 0.14994 | val 0.16825
  Epoch 021 - train 0.15255 | val 0.17163
  Regression -> MSE: 0.000138, MAE: 0.009080, R²: -0.0022
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15450 | val 0.20559
  Epoch 020 - train 0.16032 | val 0.20932
  Epoch 021 - train 0.15651 | val 0.20937
  Regression -> MSE: 0.000228, MAE: 0.010967, R²: -0.0130
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16118 | val 0.29371
  Epoch 020 - train 0.15506 | val 0.29249
  Epoch 021 - train 0.14444 | val 0.29249
  Regression -> MSE: 0.000371, MAE: 0.015927, R²: -0.0246
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16132 | val 0.14696
  Epoch 020 - train 0.16029 | val 0.14713
  Epoch 021 - train 0.15702 | val 0.14719
  Regression -> MSE: 0.000108, MAE: 0.007960, R²: 0.0011
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.16580 | val 0.23960
  Epoch 020 - train 0.15225 | val 0.27678
  Epoch 021 - train 0.14484 | val 0.28073
  Regression -> MSE: 0.000156, MAE: 0.009650, R²: 0.0002
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15633 | val 0.14677
  Epoch 020 - train 0.15452 | val 0.14905
  Epoch 021 - train 0.14729 | val 0.14911
  Regression -> MSE: 0.000272, MAE: 0.013067, R²: -0.0006
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13456 | val 0.19157
  Epoch 020 - train 0.13380 | val 0.18802
  Epoch 021 - train 0.13393 | val 0.18792
  Regression -> MSE: 0.000164, MAE: 0.009032, R²: -0.0959
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.17418 | val 0.21598
  Epoch 020 - train 0.16786 | val 0.24024
  Epoch 021 - train 0.17014 | val 0.24023
  Regression -> MSE: 0.000227, MAE: 0.010937, R²: -0.0030
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.16832 | val 0.18430
  Epoch 020 - train 0.17063 | val 0.19023
  Epoch 021 - train 0.16433 | val 0.19124
  Regression -> MSE: 0.000144, MAE: 0.008320, R²: -0.0035
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14836 | val 0.17540
  Epoch 020 - train 0.14654 | val 0.17797
  Epoch 021 - train 0.15394 | val 0.17822
  Regression -> MSE: 0.000165, MAE: 0.010469, R²: 0.0002
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16584 | val 0.17835
  Epoch 020 - train 0.16406 | val 0.17580
  Epoch 021 - train 0.15374 | val 0.17529
  Regression -> MSE: 0.000096, MAE: 0.007562, R²: -0.1245
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15076 | val 0.17527
  Epoch 020 - train 0.14800 | val 0.17440
  Epoch 021 - train 0.14912 | val 0.17475
  Regression -> MSE: 0.000215, MAE: 0.011051, R²: -0.0153
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.15652 | val 0.13457
  Epoch 020 - train 0.14744 | val 0.13533
  Epoch 021 - train 0.14732 | val 0.13559
  Regression -> MSE: 0.000093, MAE: 0.008105, R²: -0.0129
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.15055 | val 0.11365
  Epoch 020 - train 0.15581 | val 0.11370
  Epoch 021 - train 0.15219 | val 0.11377
  Regression -> MSE: 0.000106, MAE: 0.008875, R²: -0.0244
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16979 | val 0.14400
  Epoch 020 - train 0.17721 | val 0.15189
  Epoch 021 - train 0.16575 | val 0.15320
  Regression -> MSE: 0.000242, MAE: 0.012909, R²: -0.0474
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15291 | val 0.18063
  Epoch 020 - train 0.14940 | val 0.18779
  Epoch 021 - train 0.15509 | val 0.18856
  Regression -> MSE: 0.000169, MAE: 0.007828, R²: -0.0178
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.15290 | val 0.12528
  Epoch 020 - train 0.15384 | val 0.12760
  Epoch 021 - train 0.15887 | val 0.12808
  Regression -> MSE: 0.000237, MAE: 0.011866, R²: -0.0001
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14231 | val 0.23518
  Epoch 020 - train 0.14927 | val 0.23607
  Epoch 021 - train 0.14982 | val 0.23643
  Regression -> MSE: 0.000232, MAE: 0.009995, R²: -0.0078
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.17102 | val 0.17614
  Epoch 020 - train 0.16418 | val 0.17212
  Epoch 021 - train 0.16964 | val 0.17153
  Regression -> MSE: 0.000136, MAE: 0.008247, R²: -0.0082
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.15644 | val 0.18599
  Epoch 020 - train 0.15994 | val 0.18449
  Epoch 021 - train 0.15801 | val 0.18433
  Regression -> MSE: 0.000189, MAE: 0.010425, R²: -0.0036
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14461 | val 0.16638
  Epoch 020 - train 0.13973 | val 0.17757
  Epoch 021 - train 0.13817 | val 0.17721
  Regression -> MSE: 0.000266, MAE: 0.010533, R²: -0.0177
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13658 | val 0.12165
  Epoch 020 - train 0.14730 | val 0.12151
  Epoch 021 - train 0.13651 | val 0.12149
  Regression -> MSE: 0.000170, MAE: 0.010378, R²: -0.0228
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14464 | val 0.16185
  Epoch 020 - train 0.14527 | val 0.16700
  Epoch 021 - train 0.14363 | val 0.16755
  Regression -> MSE: 0.000190, MAE: 0.010680, R²: -0.0536
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.16590 | val 0.13883
  Epoch 020 - train 0.15331 | val 0.14292
  Epoch 021 - train 0.15970 | val 0.14318
  Regression -> MSE: 0.000349, MAE: 0.012347, R²: -0.0200
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16181 | val 0.09408
  Epoch 020 - train 0.15519 | val 0.09418
  Epoch 021 - train 0.15736 | val 0.09419
  Regression -> MSE: 0.000120, MAE: 0.008363, R²: -0.1408
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15849 | val 0.20185
  Epoch 020 - train 0.15256 | val 0.19931
  Epoch 021 - train 0.15262 | val 0.19951
  Regression -> MSE: 0.000225, MAE: 0.011467, R²: -0.0293
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.16138 | val 0.24804
  Epoch 020 - train 0.15453 | val 0.24913
  Epoch 021 - train 0.15736 | val 0.24960
  Regression -> MSE: 0.000093, MAE: 0.007532, R²: -0.1968
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.16013 | val 0.11490
  Epoch 020 - train 0.15553 | val 0.11538
  Epoch 021 - train 0.15266 | val 0.11544
  Regression -> MSE: 0.000316, MAE: 0.014286, R²: -0.0275
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.18000 | val 0.08621
  Epoch 020 - train 0.16927 | val 0.08540
  Epoch 021 - train 0.19421 | val 0.08529
  Regression -> MSE: 0.000246, MAE: 0.011580, R²: -0.0095
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.16016 | val 0.17774
  Epoch 020 - train 0.15197 | val 0.18738
  Epoch 021 - train 0.15491 | val 0.18762
  Regression -> MSE: 0.000084, MAE: 0.007054, R²: -0.0413
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16336 | val 0.17898
  Epoch 020 - train 0.15787 | val 0.17520
  Epoch 021 - train 0.15961 | val 0.17480
  Regression -> MSE: 0.000308, MAE: 0.014516, R²: -0.0054
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.15412 | val 0.15850
  Epoch 020 - train 0.15488 | val 0.16005
  Epoch 021 - train 0.15776 | val 0.16030
  Regression -> MSE: 0.000098, MAE: 0.007259, R²: 0.0007
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16489 | val 0.17511
  Epoch 020 - train 0.15710 | val 0.17440
  Epoch 021 - train 0.15730 | val 0.17430
  Regression -> MSE: 0.000172, MAE: 0.009511, R²: -0.0025
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14535 | val 0.17085
  Epoch 020 - train 0.13997 | val 0.17303
  Epoch 021 - train 0.15050 | val 0.17380
  Regression -> MSE: 0.000228, MAE: 0.011839, R²: -0.0240
  Directional -> Accuracy: 0.4643, MCC: 0.0000, F1: 0.0000

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14726 | val 0.15895
  Epoch 020 - train 0.15761 | val 0.15925
  Epoch 021 - train 0.15033 | val 0.15938
  Regression -> MSE: 0.000093, MAE: 0.007649, R²: -0.0064
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.16182 | val 0.22496
  Epoch 020 - train 0.15257 | val 0.22904
  Epoch 021 - train 0.16474 | val 0.22982

[I 2026-02-24 05:30:04,402] Trial 194 finished with value: -0.011482785103528528 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 64, 'learning_rate': 1.5020130791532522e-05, 'weight_decay': 1.2952239811342314e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.22407465184261605, 'early_stopping_min_delta': 0.0069731329202942895}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.16293 | val 0.23954
  Epoch 021 - train 0.16809 | val 0.24197
  Regression -> MSE: 0.000238, MAE: 0.012519, R²: -0.0026
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.20602 | val 0.29770
  Epoch 020 - train 0.21414 | val 0.29625
  Epoch 021 - train 0.20194 | val 0.29585
  Regression -> MSE: 0.000260, MAE: 0.012999, R²: -0.0492
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.18880 | val 0.18652
  Epoch 020 - train 0.21042 | val 0.18803
  Epoch 021 - train 0.19672 | val 0.18785
  Regression -> MSE: 0.000692, MAE: 0.019473, R²: -0.0109
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.22141 | val 0.33255
  Epoch 020 - train 0.21128 | val 0.32982
  Epoch 030 - train 0.21452 | val 0.33032
  Epoch 032 - train 0.21119 | val 0.32888
  Regression -> MSE: 0.000316, MAE: 0.014130, R²: -0.0170
  Directional -> Accuracy: 0.5957, MCC: 0.2037, F1: 0.5778

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.17610 | val 0.35036
  Epoch 020 - train 0.18327 | val 0.37302
  Epoch 021 - train 0.17004 | val 0.37710
  Regression -> MSE: 0.000375, MAE: 0.014991, R²: -0.0735
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.22792 | val 0.19056
  Epoch 020 - train 0.21898 | val 0.18794
  Epoch 030 - train 0.21397 | val 0.18786
  Regression -> MSE: 0.000191, MAE: 0.009458, R²: 0.0607
  Directional -> Accuracy: 0.6863, MCC: 0.4167, F1: 0.6364

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.19895 | val 0.41227
  Epoch 020 - train 0.20165 | val 0.43363
  Epoch 021 - train 0.20438 | val 0.43102
  Regression -> MSE: 0.000589, MAE: 0.018753, R²: -0.0619
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.20310 | val 0.24915
  Epoch 020 - train 0.21282 | val 0.25229
  Epoch 021 - train 0.21282 | val 0.25179
  Regression -> MSE: 0.000247, MAE: 0.012243, R²: -0.0043
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.22547 | val 0.29834
  Epoch 020 - train 0.22544 | val 0.33530
  Epoch 021 - train 0.22984 | val 0.33579
  Regression -> MSE: 0.000648, MAE: 0.020209, R²: -0.0845
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.20211 | val 0.25070
  Epoch 020 - train 0.20380 | val 0.25225
  Epoch 021 - train 0.19630 | val 0.25261
  Regression -> MSE: 0.000387, MAE: 0.016051, R²: -0.0077
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.21417 | val 0.27552
  Epoch 020 - train 0.21146 | val 0.26447
  Epoch 021 - train 0.21083 | val 0.26278
  Regression -> MSE: 0.000245, MAE: 0.012293, R²: -0.0133
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.19183 | val 0.29648
  Epoch 020 - train 0.18689 | val 0.30614
  Epoch 021 - train 0.18714 | val 0.30625
  Regression -> MSE: 0.000319, MAE: 0.013588, R²: -0.0262
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.22061 | val 0.23995
  Epoch 020 - train 0.21921 | val 0.24105
  Epoch 021 - train 0.22074 | val 0.24112
  Regression -> MSE: 0.000677, MAE: 0.019478, R²: 0.0004
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.20166 | val 0.23873
  Epoch 020 - train 0.19641 | val 0.31601
  Epoch 021 - train 0.20464 | val 0.31689
  Regression -> MSE: 0.000143, MAE: 0.009427, R²: -0.0343
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.21695 | val 0.27805
  Epoch 020 - train 0.21144 | val 0.27549
  Epoch 030 - train 0.20020 | val 0.27467
  Epoch 032 - train 0.21368 | val 0.27607
  Regression -> MSE: 0.000223, MAE: 0.010597, R²: 0.0073
  Directional -> Accuracy: 0.5574, MCC: 0.2312, F1: 0.6966

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.20937 | val 0.43544
  Epoch 020 - train 0.22633 | val 0.44858
  Epoch 021 - train 0.21941 | val 0.44764
  Regression -> MSE: 0.000373, MAE: 0.015941, R²: -0.0287
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.22778 | val 0.21543
  Epoch 020 - train 0.22318 | val 0.21591
  Epoch 021 - train 0.22186 | val 0.21556
  Regression -> MSE: 0.000108, MAE: 0.007941, R²: -0.0002
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.21108 | val 0.37029
  Epoch 020 - train 0.21220 | val 0.40860
  Epoch 021 - train 0.20894 | val 0.41012
  Regression -> MSE: 0.000161, MAE: 0.010162, R²: -0.0340
  Directional -> Accuracy: 0.3729, MCC: -0.1188, F1: 0.2128

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.20380 | val 0.20315
  Epoch 020 - train 0.20780 | val 0.20526
  Epoch 021 - train 0.21309 | val 0.20459
  Regression -> MSE: 0.000274, MAE: 0.012913, R²: -0.0082
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.19721 | val 0.29055
  Epoch 020 - train 0.19612 | val 0.29181
  Epoch 021 - train 0.19384 | val 0.29021
  Regression -> MSE: 0.000151, MAE: 0.008740, R²: -0.0075
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.21551 | val 0.29330
  Epoch 020 - train 0.20586 | val 0.28386
  Epoch 030 - train 0.20968 | val 0.28187
  Epoch 040 - train 0.20535 | val 0.28647
  Epoch 041 - train 0.19947 | val 0.28692
  Regression -> MSE: 0.000280, MAE: 0.012286, R²: -0.2364
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.20951 | val 0.25331
  Epoch 020 - train 0.19754 | val 0.27173
  Epoch 021 - train 0.20797 | val 0.27315
  Regression -> MSE: 0.000144, MAE: 0.008361, R²: -0.0032
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.20439 | val 0.24798
  Epoch 020 - train 0.19408 | val 0.24853
  Epoch 021 - train 0.20693 | val 0.24891
  Regression -> MSE: 0.000165, MAE: 0.010505, R²: 0.0041
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.23225 | val 0.24892
  Epoch 020 - train 0.22807 | val 0.24785
  Epoch 021 - train 0.22064 | val 0.24821
  Regression -> MSE: 0.000085, MAE: 0.007031, R²: -0.0014
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.21490 | val 0.33708
  Epoch 020 - train 0.21002 | val 0.38844
  Epoch 021 - train 0.21637 | val 0.38653
  Regression -> MSE: 0.000213, MAE: 0.011072, R²: -0.0050
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.18810 | val 0.18808
  Epoch 020 - train 0.19308 | val 0.18587
  Epoch 021 - train 0.18514 | val 0.18638
  Regression -> MSE: 0.000094, MAE: 0.008101, R²: -0.0206
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.22461 | val 0.15954
  Epoch 020 - train 0.20853 | val 0.15638
  Epoch 030 - train 0.22875 | val 0.16091
  Epoch 033 - train 0.22536 | val 0.16025
  Regression -> MSE: 0.000105, MAE: 0.008797, R²: -0.0154
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.21606 | val 0.21471
  Epoch 020 - train 0.22196 | val 0.26382
  Epoch 021 - train 0.21741 | val 0.26511
  Regression -> MSE: 0.000246, MAE: 0.012987, R²: -0.0614
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.21841 | val 0.23942
  Epoch 020 - train 0.20894 | val 0.23832
  Epoch 021 - train 0.20514 | val 0.23796
  Regression -> MSE: 0.000175, MAE: 0.007873, R²: -0.0504
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.22825 | val 0.17085
  Epoch 020 - train 0.22513 | val 0.20501
  Epoch 021 - train 0.21058 | val 0.20859
  Regression -> MSE: 0.000237, MAE: 0.011862, R²: -0.0004
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.22011 | val 0.32520
  Epoch 020 - train 0.20537 | val 0.32355
  Epoch 021 - train 0.20902 | val 0.32383
  Regression -> MSE: 0.000231, MAE: 0.009923, R²: -0.0019
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.21575 | val 0.24436
  Epoch 020 - train 0.21434 | val 0.25375
  Epoch 021 - train 0.21057 | val 0.25446
  Regression -> MSE: 0.000135, MAE: 0.008237, R²: -0.0031
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.22758 | val 0.27423
  Epoch 020 - train 0.21851 | val 0.27289
  Epoch 021 - train 0.22578 | val 0.27307
  Regression -> MSE: 0.000188, MAE: 0.010502, R²: 0.0005
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.18857 | val 0.22871
  Epoch 020 - train 0.18595 | val 0.22577
  Epoch 029 - train 0.18315 | val 0.22628
  Regression -> MSE: 0.000288, MAE: 0.011114, R²: -0.1006
  Directional -> Accuracy: 0.5342, MCC: 0.1345, F1: 0.4516

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.20338 | val 0.16805
  Epoch 020 - train 0.19553 | val 0.17975
  Epoch 021 - train 0.21531 | val 0.18392
  Regression -> MSE: 0.000166, MAE: 0.010365, R²: 0.0022
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.19567 | val 0.20481
  Epoch 020 - train 0.20046 | val 0.21894
  Epoch 021 - train 0.18739 | val 0.21881
  Regression -> MSE: 0.000180, MAE: 0.010273, R²: 0.0013
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.20845 | val 0.18659
  Epoch 020 - train 0.20185 | val 0.18540
  Epoch 021 - train 0.18644 | val 0.18512
  Regression -> MSE: 0.000347, MAE: 0.011733, R²: -0.0136
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.23782 | val 0.13287
  Epoch 020 - train 0.24416 | val 0.15235
  Epoch 021 - train 0.24979 | val 0.15259
  Regression -> MSE: 0.000110, MAE: 0.008336, R²: -0.0498
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.22951 | val 0.28582
  Epoch 020 - train 0.20800 | val 0.30537
  Epoch 021 - train 0.21901 | val 0.30814
  Regression -> MSE: 0.000218, MAE: 0.011305, R²: 0.0004
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.20931 | val 0.36256
  Epoch 020 - train 0.19148 | val 0.37039
  Epoch 021 - train 0.21796 | val 0.36939
  Regression -> MSE: 0.000082, MAE: 0.007048, R²: -0.0523
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.20456 | val 0.15169
  Epoch 020 - train 0.20590 | val 0.14530
  Epoch 030 - train 0.19821 | val 0.14108
  Epoch 040 - train 0.19227 | val 0.14016
  Epoch 041 - train 0.19621 | val 0.14023
  Regression -> MSE: 0.000391, MAE: 0.016367, R²: -0.2712
  Directional -> Accuracy: 0.4898, MCC: 0.2221, F1: 0.5763

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.22947 | val 0.11739
  Epoch 020 - train 0.22423 | val 0.11720
  Epoch 021 - train 0.21299 | val 0.11727
  Regression -> MSE: 0.000252, MAE: 0.011476, R²: -0.0354
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.21352 | val 0.23982
  Epoch 020 - train 0.19110 | val 0.25077
  Epoch 021 - train 0.20594 | val 0.25123
  Regression -> MSE: 0.000081, MAE: 0.007111, R²: -0.0062
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.21564 | val 0.28248
  Epoch 020 - train 0.23209 | val 0.32345
  Epoch 021 - train 0.22862 | val 0.32408
  Regression -> MSE: 0.000315, MAE: 0.014528, R²: -0.0264
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.20964 | val 0.23572
  Epoch 020 - train 0.22903 | val 0.23547
  Epoch 021 - train 0.20467 | val 0.23461
  Regression -> MSE: 0.000101, MAE: 0.007116, R²: -0.0242
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.24141 | val 0.24520
  Epoch 020 - train 0.23062 | val 0.24229
  Epoch 021 - train 0.23735 | val 0.24272
  Regression -> MSE: 0.000176, MAE: 0.010264, R²: -0.0270
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.19109 | val 0.23140
  Epoch 020 - train 0.18840 | val 0.23378
  Epoch 021 - train 0.19344 | val 0.23392
  Regression -> MSE: 0.000225, MAE: 0.011808, R²: -0.0102
  Directional -> Accuracy: 0.4464, MCC: -0.0965, F1: 0.0606


[I 2026-02-24 05:32:18,835] Trial 195 finished with value: -0.011508570022453868 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 32, 'learning_rate': 2.1187498921587423e-05, 'weight_decay': 9.671135246151749e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 50, 'huber_delta': 0.3317852887509689, 'early_stopping_min_delta': 0.007655981579819861}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.22923 | val 0.32102
  Epoch 021 - train 0.21806 | val 0.31720
  Regression -> MSE: 0.000248, MAE: 0.012410, R²: -0.0437
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12663 | val 0.16020
  Epoch 020 - train 0.12420 | val 0.16155
  Epoch 021 - train 0.13599 | val 0.16132
  Regression -> MSE: 0.000249, MAE: 0.012605, R²: -0.0062
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12594 | val 0.10973
  Epoch 020 - train 0.12843 | val 0.10851
  Epoch 021 - train 0.12220 | val 0.10876
  Regression -> MSE: 0.000690, MAE: 0.019437, R²: -0.0086
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13438 | val 0.18716
  Epoch 020 - train 0.14427 | val 0.21416
  Epoch 021 - train 0.13345 | val 0.21431
  Regression -> MSE: 0.000312, MAE: 0.014404, R²: -0.0043
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11959 | val 0.16410
  Epoch 020 - train 0.12169 | val 0.16846
  Epoch 021 - train 0.11486 | val 0.16802
  Regression -> MSE: 0.000350, MAE: 0.014574, R²: -0.0032
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12922 | val 0.13927
  Epoch 020 - train 0.13112 | val 0.16519
  Epoch 021 - train 0.12769 | val 0.16292
  Regression -> MSE: 0.000203, MAE: 0.010158, R²: 0.0027
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12748 | val 0.23142
  Epoch 020 - train 0.11936 | val 0.31617
  Epoch 021 - train 0.13917 | val 0.31798
  Regression -> MSE: 0.000588, MAE: 0.018737, R²: -0.0601
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13198 | val 0.13831
  Epoch 020 - train 0.12323 | val 0.13792
  Epoch 021 - train 0.12527 | val 0.13795
  Regression -> MSE: 0.000245, MAE: 0.011947, R²: 0.0002
  Directional -> Accuracy: 0.5362, MCC: 0.1791, F1: 0.5897

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12592 | val 0.18423
  Epoch 020 - train 0.13355 | val 0.26924
  Epoch 021 - train 0.12287 | val 0.27876
  Regression -> MSE: 0.000669, MAE: 0.020508, R²: -0.1204
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11679 | val 0.13536
  Epoch 020 - train 0.12233 | val 0.13635
  Epoch 021 - train 0.11879 | val 0.13668
  Regression -> MSE: 0.000401, MAE: 0.016058, R²: -0.0441
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12827 | val 0.14747
  Epoch 020 - train 0.12688 | val 0.14803
  Epoch 021 - train 0.13475 | val 0.14800
  Regression -> MSE: 0.000243, MAE: 0.012125, R²: -0.0048
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11807 | val 0.16010
  Epoch 020 - train 0.11890 | val 0.15951
  Epoch 030 - train 0.11008 | val 0.16130
  Regression -> MSE: 0.000359, MAE: 0.013918, R²: -0.1539
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12922 | val 0.13871
  Epoch 020 - train 0.12983 | val 0.14113
  Epoch 021 - train 0.13752 | val 0.14138
  Regression -> MSE: 0.000677, MAE: 0.019467, R²: -0.0001
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13898 | val 0.11638
  Epoch 020 - train 0.12827 | val 0.12300
  Epoch 021 - train 0.13252 | val 0.12416
  Regression -> MSE: 0.000139, MAE: 0.009229, R²: -0.0061
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11904 | val 0.15404
  Epoch 020 - train 0.11372 | val 0.15052
  Epoch 030 - train 0.11365 | val 0.15037
  Regression -> MSE: 0.000219, MAE: 0.010700, R²: 0.0270
  Directional -> Accuracy: 0.4754, MCC: -0.0522, F1: 0.5152

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12851 | val 0.23646
  Epoch 020 - train 0.12530 | val 0.24936
  Epoch 021 - train 0.13459 | val 0.24991
  Regression -> MSE: 0.000364, MAE: 0.015979, R²: -0.0051
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13108 | val 0.12518
  Epoch 020 - train 0.12542 | val 0.12478
  Epoch 021 - train 0.12350 | val 0.12467
  Regression -> MSE: 0.000109, MAE: 0.008098, R²: -0.0060
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13190 | val 0.18942
  Epoch 020 - train 0.13076 | val 0.19100
  Epoch 021 - train 0.12341 | val 0.19050
  Regression -> MSE: 0.000157, MAE: 0.009670, R²: -0.0051
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12777 | val 0.14803
  Epoch 020 - train 0.12218 | val 0.14988
  Epoch 021 - train 0.12085 | val 0.15032
  Regression -> MSE: 0.000272, MAE: 0.012973, R²: 0.0019
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11697 | val 0.17640
  Epoch 020 - train 0.11769 | val 0.18118
  Epoch 021 - train 0.11737 | val 0.17992
  Regression -> MSE: 0.000160, MAE: 0.008882, R²: -0.0675
  Directional -> Accuracy: 0.4769, MCC: -0.0548, F1: 0.5278

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.14013 | val 0.17207
  Epoch 020 - train 0.12862 | val 0.17190
  Epoch 021 - train 0.12540 | val 0.17223
  Regression -> MSE: 0.000233, MAE: 0.010909, R²: -0.0283
  Directional -> Accuracy: 0.6133, MCC: 0.2086, F1: 0.7010

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12644 | val 0.14476
  Epoch 020 - train 0.12889 | val 0.14719
  Epoch 021 - train 0.13004 | val 0.14695
  Regression -> MSE: 0.000153, MAE: 0.008840, R²: -0.0703
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11947 | val 0.13458
  Epoch 020 - train 0.12667 | val 0.13401
  Epoch 021 - train 0.11515 | val 0.13436
  Regression -> MSE: 0.000166, MAE: 0.010407, R²: -0.0033
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13228 | val 0.13445
  Epoch 020 - train 0.12801 | val 0.13507
  Epoch 021 - train 0.12917 | val 0.13518
  Regression -> MSE: 0.000086, MAE: 0.007086, R²: -0.0063
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13355 | val 0.15486
  Epoch 020 - train 0.13503 | val 0.15609
  Epoch 021 - train 0.13313 | val 0.15588
  Regression -> MSE: 0.000215, MAE: 0.011471, R²: -0.0145
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11748 | val 0.11274
  Epoch 020 - train 0.12301 | val 0.11318
  Epoch 021 - train 0.12053 | val 0.11287
  Regression -> MSE: 0.000093, MAE: 0.008109, R²: -0.0069
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13438 | val 0.09128
  Epoch 020 - train 0.12691 | val 0.10873
  Epoch 021 - train 0.14135 | val 0.11020
  Regression -> MSE: 0.000103, MAE: 0.008752, R²: -0.0033
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13207 | val 0.10942
  Epoch 020 - train 0.14040 | val 0.10988
  Epoch 021 - train 0.12998 | val 0.11016
  Regression -> MSE: 0.000232, MAE: 0.012547, R²: -0.0011
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12306 | val 0.12984
  Epoch 020 - train 0.12651 | val 0.12924
  Epoch 030 - train 0.11980 | val 0.12965
  Regression -> MSE: 0.000191, MAE: 0.008447, R²: -0.1449
  Directional -> Accuracy: 0.4386, MCC: -0.1620, F1: 0.5294

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13453 | val 0.10523
  Epoch 020 - train 0.14842 | val 0.12113
  Epoch 021 - train 0.13419 | val 0.12254
  Regression -> MSE: 0.000239, MAE: 0.011976, R²: -0.0088
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13070 | val 0.17825
  Epoch 020 - train 0.13269 | val 0.18173
  Epoch 021 - train 0.13275 | val 0.18230
  Regression -> MSE: 0.000230, MAE: 0.009858, R²: 0.0023
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13685 | val 0.15716
  Epoch 020 - train 0.14554 | val 0.16223
  Epoch 021 - train 0.14111 | val 0.16182
  Regression -> MSE: 0.000147, MAE: 0.008841, R²: -0.0898
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13049 | val 0.14945
  Epoch 020 - train 0.13943 | val 0.15453
  Epoch 021 - train 0.12907 | val 0.15460
  Regression -> MSE: 0.000193, MAE: 0.010457, R²: -0.0269
  Directional -> Accuracy: 0.5000, MCC: 0.1884, F1: 0.1379

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12290 | val 0.17207
  Epoch 020 - train 0.12686 | val 0.16804
  Epoch 021 - train 0.12329 | val 0.16495
  Regression -> MSE: 0.000264, MAE: 0.010581, R²: -0.0067
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12030 | val 0.10094
  Epoch 020 - train 0.12480 | val 0.09702
  Epoch 030 - train 0.12052 | val 0.09472
  Regression -> MSE: 0.000165, MAE: 0.010367, R²: 0.0123
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12829 | val 0.11892
  Epoch 020 - train 0.12322 | val 0.11820
  Epoch 021 - train 0.12061 | val 0.11826
  Regression -> MSE: 0.000186, MAE: 0.010562, R²: -0.0331
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13033 | val 0.11019
  Epoch 020 - train 0.12143 | val 0.11061
  Epoch 021 - train 0.12094 | val 0.11073
  Regression -> MSE: 0.000342, MAE: 0.011875, R²: 0.0026
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13152 | val 0.07910
  Epoch 020 - train 0.14168 | val 0.07710
  Epoch 021 - train 0.13815 | val 0.07695
  Regression -> MSE: 0.000109, MAE: 0.008367, R²: -0.0354
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14161 | val 0.15853
  Epoch 020 - train 0.12589 | val 0.16778
  Epoch 021 - train 0.12993 | val 0.16710
  Regression -> MSE: 0.000220, MAE: 0.011338, R²: -0.0056
  Directional -> Accuracy: 0.3684, MCC: -0.2721, F1: 0.3077

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11973 | val 0.19131
  Epoch 020 - train 0.12580 | val 0.18704
  Epoch 030 - train 0.11772 | val 0.18782
  Regression -> MSE: 0.000090, MAE: 0.007390, R²: -0.1577
  Directional -> Accuracy: 0.4894, MCC: 0.0958, F1: 0.4286

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13256 | val 0.09359
  Epoch 020 - train 0.12961 | val 0.08640
  Epoch 030 - train 0.12300 | val 0.08400
  Regression -> MSE: 0.000325, MAE: 0.013319, R²: -0.0551
  Directional -> Accuracy: 0.5918, MCC: 0.1013, F1: 0.4118

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13406 | val 0.07002
  Epoch 020 - train 0.13441 | val 0.07041
  Epoch 021 - train 0.13411 | val 0.07059
  Regression -> MSE: 0.000246, MAE: 0.011546, R²: -0.0096
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12689 | val 0.14337
  Epoch 020 - train 0.12751 | val 0.14362
  Epoch 021 - train 0.12129 | val 0.14359
  Regression -> MSE: 0.000085, MAE: 0.007066, R²: -0.0563
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12992 | val 0.15538
  Epoch 020 - train 0.13282 | val 0.17961
  Epoch 021 - train 0.13839 | val 0.17976
  Regression -> MSE: 0.000311, MAE: 0.014495, R²: -0.0132
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14524 | val 0.12678
  Epoch 020 - train 0.14227 | val 0.12819
  Epoch 021 - train 0.14445 | val 0.12804
  Regression -> MSE: 0.000099, MAE: 0.007239, R²: -0.0036
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.14305 | val 0.13433
  Epoch 020 - train 0.13380 | val 0.13350
  Epoch 021 - train 0.14015 | val 0.13353
  Regression -> MSE: 0.000172, MAE: 0.009708, R²: -0.0019
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12211 | val 0.13031
  Epoch 020 - train 0.12122 | val 0.13181
  Epoch 021 - train 0.12228 | val 0.13107
  Regression -> MSE: 0.000225, MAE: 0.011764, R²: -0.0069
  Directional -> Accuracy: 0.5893, MCC: 0.2556, F1: 0.7229

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.13441 | val 0.13244
  Epoch 020 - train 0.12855 | val 0.13667
  Epoch 021 - train 0.13323 | val 0.13667
  Regression -> MSE: 0.000092, MAE: 0.007641, R²: -0.0002
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000


[I 2026-02-24 05:34:24,003] Trial 196 finished with value: -0.01143960031475058 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 9.514556566059577e-06, 'weight_decay': 8.026532126243941e-06, 'lr_patience': 7, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.17106860941086094, 'early_stopping_min_delta': 0.004556672071986626}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.13026 | val 0.16499
  Epoch 021 - train 0.13560 | val 0.16514
  Regression -> MSE: 0.000238, MAE: 0.012365, R²: -0.0026
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.08983 | val 0.11249
  Epoch 020 - train 0.08485 | val 0.11262
  Epoch 021 - train 0.08548 | val 0.11275
  Regression -> MSE: 0.000249, MAE: 0.012586, R²: -0.0055
  Directional -> Accuracy: 0.4545, MCC: -0.0214, F1: 0.6111

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10000 | val 0.09275
  Epoch 020 - train 0.09429 | val 0.09541
  Epoch 021 - train 0.09830 | val 0.09551
  Regression -> MSE: 0.000685, MAE: 0.019405, R²: 0.0001
  Directional -> Accuracy: 0.6739, MCC: 0.3795, F1: 0.6667

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09525 | val 0.13940
  Epoch 020 - train 0.09675 | val 0.14023
  Epoch 021 - train 0.09294 | val 0.14015
  Regression -> MSE: 0.000309, MAE: 0.014393, R²: 0.0033
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08485 | val 0.07412
  Epoch 020 - train 0.08256 | val 0.07519
  Epoch 021 - train 0.07945 | val 0.07485
  Regression -> MSE: 0.000351, MAE: 0.014614, R²: -0.0046
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.08760 | val 0.09218
  Epoch 020 - train 0.09238 | val 0.09088
  Epoch 021 - train 0.08852 | val 0.09110
  Regression -> MSE: 0.000211, MAE: 0.010261, R²: -0.0369
  Directional -> Accuracy: 0.5098, MCC: -0.0466, F1: 0.6575

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08755 | val 0.16707
  Epoch 020 - train 0.09070 | val 0.16677
  Epoch 021 - train 0.09219 | val 0.16711
  Regression -> MSE: 0.000560, MAE: 0.018222, R²: -0.0093
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09100 | val 0.10708
  Epoch 020 - train 0.09309 | val 0.10729
  Epoch 021 - train 0.09814 | val 0.10719
  Regression -> MSE: 0.000251, MAE: 0.012595, R²: -0.0240
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10123 | val 0.10585
  Epoch 020 - train 0.09375 | val 0.10857
  Epoch 021 - train 0.09784 | val 0.10840
  Regression -> MSE: 0.000603, MAE: 0.019297, R²: -0.0094
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08613 | val 0.10915
  Epoch 020 - train 0.07906 | val 0.10895
  Epoch 021 - train 0.08558 | val 0.10892
  Regression -> MSE: 0.000390, MAE: 0.016001, R²: -0.0164
  Directional -> Accuracy: 0.4286, MCC: -0.1118, F1: 0.5882

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09495 | val 0.11406
  Epoch 020 - train 0.09576 | val 0.11212
  Epoch 021 - train 0.09773 | val 0.11222
  Regression -> MSE: 0.000241, MAE: 0.012015, R²: 0.0005
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08660 | val 0.12553
  Epoch 020 - train 0.08518 | val 0.12906
  Epoch 021 - train 0.08467 | val 0.12911
  Regression -> MSE: 0.000306, MAE: 0.013578, R²: 0.0156
  Directional -> Accuracy: 0.5000, MCC: 0.0393, F1: 0.5763

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09251 | val 0.11178
  Epoch 020 - train 0.09669 | val 0.11181
  Epoch 021 - train 0.08854 | val 0.11225
  Regression -> MSE: 0.000678, MAE: 0.019454, R²: -0.0013
  Directional -> Accuracy: 0.4828, MCC: -0.0778, F1: 0.0625

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09663 | val 0.10291
  Epoch 020 - train 0.08833 | val 0.10449
  Epoch 021 - train 0.09317 | val 0.10529
  Regression -> MSE: 0.000141, MAE: 0.009083, R²: -0.0188
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08998 | val 0.11571
  Epoch 020 - train 0.08242 | val 0.11613
  Epoch 021 - train 0.08936 | val 0.11599
  Regression -> MSE: 0.000226, MAE: 0.010803, R²: -0.0057
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08915 | val 0.18122
  Epoch 020 - train 0.08764 | val 0.18020
  Epoch 021 - train 0.08784 | val 0.17938
  Regression -> MSE: 0.000374, MAE: 0.015892, R²: -0.0334
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09556 | val 0.09795
  Epoch 020 - train 0.09282 | val 0.09708
  Epoch 021 - train 0.09460 | val 0.09700
  Regression -> MSE: 0.000110, MAE: 0.008131, R²: -0.0186
  Directional -> Accuracy: 0.3714, MCC: -0.2810, F1: 0.0833

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08785 | val 0.13857
  Epoch 020 - train 0.09209 | val 0.13941
  Epoch 021 - train 0.08882 | val 0.13965
  Regression -> MSE: 0.000157, MAE: 0.009904, R²: -0.0086
  Directional -> Accuracy: 0.6441, MCC: 0.1708, F1: 0.7529

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09332 | val 0.09261
  Epoch 020 - train 0.09267 | val 0.09160
  Epoch 021 - train 0.09357 | val 0.09127
  Regression -> MSE: 0.000278, MAE: 0.013036, R²: -0.0228
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08509 | val 0.11213
  Epoch 020 - train 0.08671 | val 0.11254
  Epoch 021 - train 0.08391 | val 0.11253
  Regression -> MSE: 0.000165, MAE: 0.009031, R²: -0.1019
  Directional -> Accuracy: 0.4615, MCC: 0.0914, F1: 0.2222

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.08939 | val 0.12495
  Epoch 020 - train 0.08964 | val 0.12449
  Epoch 021 - train 0.08575 | val 0.12429
  Regression -> MSE: 0.000242, MAE: 0.011271, R²: -0.0690
  Directional -> Accuracy: 0.3467, MCC: -0.2940, F1: 0.2462

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09741 | val 0.11176
  Epoch 020 - train 0.09433 | val 0.11227
  Epoch 021 - train 0.09509 | val 0.11216
  Regression -> MSE: 0.000145, MAE: 0.008315, R²: -0.0085
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.08713 | val 0.10312
  Epoch 020 - train 0.09001 | val 0.10336
  Epoch 021 - train 0.08831 | val 0.10348
  Regression -> MSE: 0.000174, MAE: 0.010223, R²: -0.0505
  Directional -> Accuracy: 0.4697, MCC: -0.0928, F1: 0.1463

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09605 | val 0.10817
  Epoch 020 - train 0.10024 | val 0.10756
  Epoch 021 - train 0.09317 | val 0.10736
  Regression -> MSE: 0.000087, MAE: 0.007146, R²: -0.0224
  Directional -> Accuracy: 0.5517, MCC: 0.0116, F1: 0.6829

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.08766 | val 0.10601
  Epoch 020 - train 0.08728 | val 0.10608
  Epoch 021 - train 0.08921 | val 0.10619
  Regression -> MSE: 0.000213, MAE: 0.011116, R²: -0.0075
  Directional -> Accuracy: 0.4697, MCC: -0.0429, F1: 0.5333

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08453 | val 0.07848
  Epoch 020 - train 0.08931 | val 0.07812
  Epoch 021 - train 0.08238 | val 0.07794
  Regression -> MSE: 0.000093, MAE: 0.008025, R²: -0.0109
  Directional -> Accuracy: 0.5357, MCC: -0.1211, F1: 0.6977

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10136 | val 0.07938
  Epoch 020 - train 0.09806 | val 0.08104
  Epoch 021 - train 0.09788 | val 0.08081
  Regression -> MSE: 0.000120, MAE: 0.009331, R²: -0.1637
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09590 | val 0.08745
  Epoch 020 - train 0.09210 | val 0.08742
  Epoch 021 - train 0.09153 | val 0.08753
  Regression -> MSE: 0.000244, MAE: 0.012912, R²: -0.0537
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09269 | val 0.11561
  Epoch 020 - train 0.09427 | val 0.11524
  Epoch 021 - train 0.09167 | val 0.11496
  Regression -> MSE: 0.000169, MAE: 0.008062, R²: -0.0181
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09554 | val 0.08064
  Epoch 020 - train 0.09766 | val 0.08165
  Epoch 021 - train 0.09771 | val 0.08165
  Regression -> MSE: 0.000236, MAE: 0.011806, R²: 0.0019
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09422 | val 0.15151
  Epoch 020 - train 0.09227 | val 0.15376
  Epoch 021 - train 0.09222 | val 0.15358
  Regression -> MSE: 0.000237, MAE: 0.010189, R²: -0.0268
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09491 | val 0.10421
  Epoch 020 - train 0.09643 | val 0.10481
  Epoch 021 - train 0.09586 | val 0.10452
  Regression -> MSE: 0.000134, MAE: 0.008143, R²: 0.0107
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09326 | val 0.11364
  Epoch 020 - train 0.09753 | val 0.11346
  Epoch 021 - train 0.09293 | val 0.11344
  Regression -> MSE: 0.000191, MAE: 0.010505, R²: -0.0164
  Directional -> Accuracy: 0.4600, MCC: -0.0983, F1: 0.5263

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08316 | val 0.10715
  Epoch 020 - train 0.08069 | val 0.10605
  Epoch 021 - train 0.08272 | val 0.10568
  Regression -> MSE: 0.000265, MAE: 0.010742, R²: -0.0139
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08384 | val 0.07705
  Epoch 020 - train 0.08346 | val 0.08307
  Epoch 021 - train 0.08958 | val 0.08278
  Regression -> MSE: 0.000165, MAE: 0.010377, R²: 0.0072
  Directional -> Accuracy: 0.5263, MCC: 0.0619, F1: 0.6250

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08892 | val 0.09598
  Epoch 020 - train 0.09149 | val 0.09606
  Epoch 021 - train 0.09044 | val 0.09605
  Regression -> MSE: 0.000182, MAE: 0.010353, R²: -0.0099
  Directional -> Accuracy: 0.4545, MCC: -0.2585, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.08725 | val 0.09089
  Epoch 020 - train 0.09114 | val 0.09111
  Epoch 021 - train 0.08456 | val 0.09117
  Regression -> MSE: 0.000346, MAE: 0.012059, R²: -0.0084
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.09519 | val 0.06351
  Epoch 020 - train 0.09675 | val 0.06433
  Epoch 021 - train 0.09981 | val 0.06428
  Regression -> MSE: 0.000109, MAE: 0.008269, R²: -0.0391
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09003 | val 0.11850
  Epoch 020 - train 0.09144 | val 0.11884
  Epoch 021 - train 0.08942 | val 0.11888
  Regression -> MSE: 0.000219, MAE: 0.011317, R²: -0.0015
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.08904 | val 0.14481
  Epoch 020 - train 0.08609 | val 0.14630
  Epoch 021 - train 0.08401 | val 0.14629
  Regression -> MSE: 0.000093, MAE: 0.007542, R²: -0.1968
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10494 | val 0.10075
  Epoch 020 - train 0.10390 | val 0.11090
  Epoch 021 - train 0.10331 | val 0.11119
  Regression -> MSE: 0.000365, MAE: 0.016093, R²: -0.1862
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09722 | val 0.05869
  Epoch 020 - train 0.09907 | val 0.06419
  Epoch 021 - train 0.10178 | val 0.06459
  Regression -> MSE: 0.000253, MAE: 0.011453, R²: -0.0380
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08966 | val 0.10425
  Epoch 020 - train 0.08292 | val 0.10423
  Epoch 021 - train 0.08621 | val 0.10418
  Regression -> MSE: 0.000083, MAE: 0.007078, R²: -0.0272
  Directional -> Accuracy: 0.5200, MCC: 0.0400, F1: 0.3077

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10153 | val 0.12930
  Epoch 020 - train 0.10156 | val 0.13137
  Epoch 021 - train 0.10495 | val 0.13146
  Regression -> MSE: 0.000316, MAE: 0.014505, R²: -0.0293
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08879 | val 0.10762
  Epoch 020 - train 0.08498 | val 0.11182
  Epoch 021 - train 0.08599 | val 0.11147
  Regression -> MSE: 0.000099, MAE: 0.007200, R²: -0.0031
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.09890 | val 0.10444
  Epoch 020 - train 0.09942 | val 0.10587
  Epoch 021 - train 0.09731 | val 0.10580
  Regression -> MSE: 0.000172, MAE: 0.009762, R²: 0.0003
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...


[I 2026-02-24 05:37:13,337] Trial 197 finished with value: -0.011464609287981091 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 64, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.6000000000000001, 'batch_size': 32, 'learning_rate': 1.2986586859712214e-05, 'weight_decay': 1.0325246186508691e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.12759002748444148, 'early_stopping_min_delta': 0.007314549222496315}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.09664 | val 0.11850
  Epoch 021 - train 0.09221 | val 0.11847
  Regression -> MSE: 0.000243, MAE: 0.012381, R²: -0.0232
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.17868 | val 0.23256
  Epoch 020 - train 0.17810 | val 0.23486
  Epoch 021 - train 0.18074 | val 0.23305
  Regression -> MSE: 0.000248, MAE: 0.012552, R²: -0.0007
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.19921 | val 0.22585
  Epoch 020 - train 0.18338 | val 0.22456
  Epoch 021 - train 0.18476 | val 0.22426
  Regression -> MSE: 0.000726, MAE: 0.020062, R²: -0.0599
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.20071 | val 0.30356
  Epoch 020 - train 0.17493 | val 0.30168
  Epoch 021 - train 0.17897 | val 0.30115
  Regression -> MSE: 0.000322, MAE: 0.014532, R²: -0.0372
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.15780 | val 0.22447
  Epoch 020 - train 0.15215 | val 0.26899
  Epoch 021 - train 0.15023 | val 0.25623
  Regression -> MSE: 0.000350, MAE: 0.014582, R²: -0.0006
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.18050 | val 0.18809
  Epoch 020 - train 0.17495 | val 0.18685
  Epoch 021 - train 0.17631 | val 0.18870
  Regression -> MSE: 0.000204, MAE: 0.010038, R²: -0.0031
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.17486 | val 0.33337
  Epoch 020 - train 0.18420 | val 0.34869
  Epoch 021 - train 0.17696 | val 0.34741
  Regression -> MSE: 0.000556, MAE: 0.018129, R²: -0.0008
  Directional -> Accuracy: 0.5745, MCC: 0.1969, F1: 0.6667

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.18745 | val 0.21962
  Epoch 020 - train 0.17738 | val 0.22134
  Epoch 021 - train 0.18274 | val 0.22163
  Regression -> MSE: 0.000246, MAE: 0.012033, R²: -0.0009
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.19547 | val 0.18050
  Epoch 020 - train 0.18086 | val 0.18206
  Epoch 029 - train 0.20021 | val 0.18215
  Regression -> MSE: 0.000657, MAE: 0.019971, R²: -0.1002
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.17924 | val 0.23578
  Epoch 020 - train 0.18075 | val 0.23255
  Epoch 021 - train 0.17209 | val 0.23231
  Regression -> MSE: 0.000386, MAE: 0.016028, R²: -0.0069
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.18399 | val 0.22719
  Epoch 020 - train 0.18090 | val 0.22893
  Epoch 021 - train 0.18421 | val 0.22945
  Regression -> MSE: 0.000245, MAE: 0.011647, R²: -0.0136
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.17769 | val 0.29628
  Epoch 020 - train 0.17858 | val 0.29934
  Epoch 021 - train 0.17249 | val 0.29846
  Regression -> MSE: 0.000316, MAE: 0.013602, R²: -0.0175
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.17860 | val 0.24282
  Epoch 020 - train 0.17923 | val 0.24198
  Epoch 021 - train 0.17813 | val 0.24495
  Regression -> MSE: 0.000678, MAE: 0.019568, R²: -0.0009
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.18099 | val 0.18160
  Epoch 020 - train 0.18230 | val 0.18992
  Epoch 021 - train 0.17094 | val 0.18975
  Regression -> MSE: 0.000143, MAE: 0.009428, R²: -0.0353
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.17552 | val 0.23664
  Epoch 020 - train 0.16960 | val 0.23583
  Epoch 021 - train 0.16756 | val 0.23552
  Regression -> MSE: 0.000229, MAE: 0.010826, R²: -0.0163
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.18473 | val 0.37274
  Epoch 020 - train 0.17326 | val 0.37007
  Epoch 021 - train 0.17335 | val 0.37233
  Regression -> MSE: 0.000368, MAE: 0.015991, R²: -0.0169
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.18559 | val 0.19355
  Epoch 020 - train 0.18600 | val 0.18513
  Epoch 021 - train 0.18115 | val 0.18756
  Regression -> MSE: 0.000108, MAE: 0.007954, R²: -0.0055
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.17292 | val 0.29594
  Epoch 020 - train 0.17135 | val 0.30241
  Epoch 021 - train 0.17604 | val 0.30433
  Regression -> MSE: 0.000158, MAE: 0.009936, R²: -0.0145
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.18351 | val 0.17967
  Epoch 020 - train 0.18252 | val 0.17971
  Epoch 021 - train 0.17610 | val 0.17942
  Regression -> MSE: 0.000275, MAE: 0.013226, R²: -0.0116
  Directional -> Accuracy: 0.5921, MCC: 0.0373, F1: 0.7257

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.16894 | val 0.26680
  Epoch 020 - train 0.16834 | val 0.24828
  Epoch 021 - train 0.16617 | val 0.25174
  Regression -> MSE: 0.000157, MAE: 0.008773, R²: -0.0495
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.18746 | val 0.27820
  Epoch 020 - train 0.19055 | val 0.27312
  Epoch 021 - train 0.18430 | val 0.27287
  Regression -> MSE: 0.000229, MAE: 0.010937, R²: -0.0126
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.18212 | val 0.22094
  Epoch 020 - train 0.18265 | val 0.21930
  Epoch 021 - train 0.17906 | val 0.21973
  Regression -> MSE: 0.000143, MAE: 0.008285, R²: 0.0021
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.17789 | val 0.20470
  Epoch 020 - train 0.17088 | val 0.20329
  Epoch 021 - train 0.17525 | val 0.20433
  Regression -> MSE: 0.000168, MAE: 0.010311, R²: -0.0184
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.20194 | val 0.23557
  Epoch 020 - train 0.18434 | val 0.24125
  Epoch 021 - train 0.18640 | val 0.24034
  Regression -> MSE: 0.000087, MAE: 0.007133, R²: -0.0178
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.19430 | val 0.27760
  Epoch 020 - train 0.18057 | val 0.26387
  Epoch 021 - train 0.17275 | val 0.26939
  Regression -> MSE: 0.000212, MAE: 0.011041, R²: -0.0013
  Directional -> Accuracy: 0.5455, MCC: 0.0679, F1: 0.2857

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.16851 | val 0.15603
  Epoch 020 - train 0.15604 | val 0.15639
  Epoch 021 - train 0.16522 | val 0.15894
  Regression -> MSE: 0.000094, MAE: 0.008103, R²: -0.0162
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.18335 | val 0.14306
  Epoch 020 - train 0.18066 | val 0.14831
  Epoch 021 - train 0.19596 | val 0.14937
  Regression -> MSE: 0.000107, MAE: 0.008907, R²: -0.0334
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.19458 | val 0.17647
  Epoch 020 - train 0.19520 | val 0.18034
  Epoch 021 - train 0.18820 | val 0.18026
  Regression -> MSE: 0.000238, MAE: 0.012773, R²: -0.0293
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.18421 | val 0.19915
  Epoch 020 - train 0.17192 | val 0.20093
  Epoch 021 - train 0.17645 | val 0.20084
  Regression -> MSE: 0.000179, MAE: 0.007938, R²: -0.0782
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.20327 | val 0.17705
  Epoch 020 - train 0.19240 | val 0.19987
  Epoch 021 - train 0.20088 | val 0.20086
  Regression -> MSE: 0.000240, MAE: 0.012034, R²: -0.0150
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.18343 | val 0.30073
  Epoch 020 - train 0.17484 | val 0.30176
  Epoch 021 - train 0.18693 | val 0.30237
  Regression -> MSE: 0.000232, MAE: 0.009926, R²: -0.0062
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.18905 | val 0.27272
  Epoch 020 - train 0.18099 | val 0.27506
  Epoch 021 - train 0.19946 | val 0.27532
  Regression -> MSE: 0.000136, MAE: 0.008238, R²: -0.0054
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.17859 | val 0.23493
  Epoch 020 - train 0.18975 | val 0.23398
  Epoch 021 - train 0.18344 | val 0.23334
  Regression -> MSE: 0.000188, MAE: 0.010512, R²: 0.0017
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.15954 | val 0.20910
  Epoch 020 - train 0.15798 | val 0.20938
  Epoch 021 - train 0.15695 | val 0.21041
  Regression -> MSE: 0.000260, MAE: 0.010476, R²: 0.0081
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.16699 | val 0.14496
  Epoch 020 - train 0.17528 | val 0.14739
  Epoch 021 - train 0.17069 | val 0.14791
  Regression -> MSE: 0.000171, MAE: 0.010386, R²: -0.0266
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.17188 | val 0.18946
  Epoch 020 - train 0.15481 | val 0.19094
  Epoch 021 - train 0.15906 | val 0.19095
  Regression -> MSE: 0.000180, MAE: 0.010333, R²: -0.0014
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.17349 | val 0.18165
  Epoch 020 - train 0.18374 | val 0.17544
  Epoch 021 - train 0.18651 | val 0.17510
  Regression -> MSE: 0.000350, MAE: 0.011796, R²: -0.0216
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.18486 | val 0.14105
  Epoch 020 - train 0.19475 | val 0.13984
  Epoch 021 - train 0.19297 | val 0.14343
  Regression -> MSE: 0.000115, MAE: 0.008330, R²: -0.0966
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.18832 | val 0.24273
  Epoch 020 - train 0.17100 | val 0.24449
  Epoch 021 - train 0.17995 | val 0.24565
  Regression -> MSE: 0.000218, MAE: 0.011244, R²: 0.0007
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.20146 | val 0.32803
  Epoch 020 - train 0.17622 | val 0.33057
  Epoch 021 - train 0.18102 | val 0.33039
  Regression -> MSE: 0.000091, MAE: 0.007437, R²: -0.1653
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.18054 | val 0.19469
  Epoch 020 - train 0.18409 | val 0.21128
  Epoch 021 - train 0.18761 | val 0.21090
  Regression -> MSE: 0.000342, MAE: 0.015448, R²: -0.1125
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.19330 | val 0.10651
  Epoch 020 - train 0.20749 | val 0.12412
  Epoch 021 - train 0.19486 | val 0.12537
  Regression -> MSE: 0.000248, MAE: 0.011536, R²: -0.0168
  Directional -> Accuracy: 0.5000, MCC: 0.0175, F1: 0.4242

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.18438 | val 0.23211
  Epoch 020 - train 0.16634 | val 0.23073
  Epoch 021 - train 0.16263 | val 0.22907
  Regression -> MSE: 0.000081, MAE: 0.007058, R²: -0.0035
  Directional -> Accuracy: 0.5333, MCC: 0.0754, F1: 0.5977

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.18744 | val 0.34137
  Epoch 020 - train 0.18819 | val 0.33123
  Epoch 021 - train 0.18989 | val 0.32528
  Regression -> MSE: 0.000313, MAE: 0.014501, R²: -0.0198
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.19801 | val 0.18576
  Epoch 020 - train 0.15161 | val 0.19461
  Epoch 021 - train 0.17099 | val 0.19444
  Regression -> MSE: 0.000099, MAE: 0.007379, R²: -0.0040
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.22171 | val 0.23873
  Epoch 020 - train 0.19842 | val 0.24334
  Epoch 021 - train 0.21201 | val 0.24363
  Regression -> MSE: 0.000176, MAE: 0.010234, R²: -0.0239
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 05:41:48,445] Trial 198 finished with value: -0.011447136179385486 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.7000000000000001, 'batch_size': 16, 'learning_rate': 1.7324006341713432e-05, 'weight_decay': 6.713330661652122e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2784466063882537, 'early_stopping_min_delta': 0.009980628161667024}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.18276 | val 0.31988
  Regression -> MSE: 0.000237, MAE: 0.012398, R²: 0.0022
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.07376 | val 0.09250
  Epoch 020 - train 0.07272 | val 0.09394
  Epoch 021 - train 0.07161 | val 0.09390
  Regression -> MSE: 0.000252, MAE: 0.012714, R²: -0.0166
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07280 | val 0.06701
  Epoch 020 - train 0.07260 | val 0.07123
  Epoch 021 - train 0.07430 | val 0.07127
  Regression -> MSE: 0.000689, MAE: 0.019411, R²: -0.0066
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07551 | val 0.11410
  Epoch 020 - train 0.07772 | val 0.11832
  Epoch 021 - train 0.07781 | val 0.11840
  Regression -> MSE: 0.000316, MAE: 0.014463, R²: -0.0183
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07095 | val 0.06595
  Epoch 020 - train 0.06731 | val 0.06525
  Epoch 021 - train 0.06571 | val 0.06504
  Regression -> MSE: 0.000355, MAE: 0.014686, R²: -0.0175
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07969 | val 0.07226
  Epoch 020 - train 0.07565 | val 0.07414
  Epoch 021 - train 0.07554 | val 0.07415
  Regression -> MSE: 0.000206, MAE: 0.010415, R²: -0.0108
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.07010 | val 0.13368
  Epoch 020 - train 0.07200 | val 0.16492
  Epoch 021 - train 0.06991 | val 0.16691
  Regression -> MSE: 0.000563, MAE: 0.018218, R²: -0.0149
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07557 | val 0.08929
  Epoch 020 - train 0.07761 | val 0.08833
  Epoch 021 - train 0.07643 | val 0.08832
  Regression -> MSE: 0.000246, MAE: 0.012064, R²: -0.0002
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08115 | val 0.10017
  Epoch 020 - train 0.07287 | val 0.10088
  Epoch 021 - train 0.07329 | val 0.10196
  Regression -> MSE: 0.000657, MAE: 0.020350, R²: -0.0989
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.07800 | val 0.08507
  Epoch 020 - train 0.07874 | val 0.08781
  Epoch 021 - train 0.07229 | val 0.08826
  Regression -> MSE: 0.000391, MAE: 0.016014, R²: -0.0180
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.07528 | val 0.09174
  Epoch 020 - train 0.07247 | val 0.09188
  Epoch 021 - train 0.07688 | val 0.09186
  Regression -> MSE: 0.000243, MAE: 0.012128, R²: -0.0057
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08221 | val 0.09604
  Epoch 020 - train 0.07706 | val 0.09762
  Epoch 021 - train 0.08093 | val 0.09776
  Regression -> MSE: 0.000330, MAE: 0.013656, R²: -0.0620
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.08293 | val 0.09765
  Epoch 020 - train 0.08037 | val 0.11540
  Epoch 021 - train 0.07719 | val 0.11508
  Regression -> MSE: 0.000695, MAE: 0.020069, R²: -0.0269
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07921 | val 0.07571
  Epoch 020 - train 0.07671 | val 0.10148
  Epoch 021 - train 0.07956 | val 0.10172
  Regression -> MSE: 0.000144, MAE: 0.009458, R²: -0.0396
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.07672 | val 0.10528
  Epoch 020 - train 0.06833 | val 0.11594
  Epoch 021 - train 0.06867 | val 0.11587
  Regression -> MSE: 0.000225, MAE: 0.010737, R²: -0.0019
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.07369 | val 0.13884
  Epoch 020 - train 0.07529 | val 0.14170
  Epoch 021 - train 0.07373 | val 0.14167
  Regression -> MSE: 0.000362, MAE: 0.016056, R²: 0.0004
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.08427 | val 0.07846
  Epoch 020 - train 0.07697 | val 0.07983
  Epoch 021 - train 0.07818 | val 0.07980
  Regression -> MSE: 0.000111, MAE: 0.008249, R²: -0.0306
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.07479 | val 0.11452
  Epoch 020 - train 0.07585 | val 0.13416
  Epoch 021 - train 0.07383 | val 0.13439
  Regression -> MSE: 0.000158, MAE: 0.009964, R²: -0.0163
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.08491 | val 0.08361
  Epoch 020 - train 0.07997 | val 0.08396
  Epoch 021 - train 0.08111 | val 0.08385
  Regression -> MSE: 0.000281, MAE: 0.013459, R²: -0.0328
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06940 | val 0.11619
  Epoch 020 - train 0.06858 | val 0.11739
  Epoch 021 - train 0.07058 | val 0.11704
  Regression -> MSE: 0.000151, MAE: 0.008743, R²: -0.0124
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.08328 | val 0.12242
  Epoch 020 - train 0.08176 | val 0.12639
  Epoch 021 - train 0.07585 | val 0.12642
  Regression -> MSE: 0.000234, MAE: 0.011050, R²: -0.0352
  Directional -> Accuracy: 0.5467, MCC: 0.0276, F1: 0.6909

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07655 | val 0.08737
  Epoch 020 - train 0.07381 | val 0.09854
  Epoch 021 - train 0.07288 | val 0.09862
  Regression -> MSE: 0.000144, MAE: 0.008413, R²: -0.0069
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.07365 | val 0.08094
  Epoch 020 - train 0.07236 | val 0.08021
  Epoch 021 - train 0.07403 | val 0.08021
  Regression -> MSE: 0.000167, MAE: 0.010315, R²: -0.0128
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.08192 | val 0.08586
  Epoch 020 - train 0.08491 | val 0.08631
  Epoch 021 - train 0.07721 | val 0.08620
  Regression -> MSE: 0.000095, MAE: 0.007524, R²: -0.1145
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07843 | val 0.08819
  Epoch 020 - train 0.07448 | val 0.08969
  Epoch 021 - train 0.07533 | val 0.08971
  Regression -> MSE: 0.000212, MAE: 0.011220, R²: -0.0022
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.07775 | val 0.06098
  Epoch 020 - train 0.07071 | val 0.05905
  Epoch 021 - train 0.06975 | val 0.05903
  Regression -> MSE: 0.000099, MAE: 0.008176, R²: -0.0773
  Directional -> Accuracy: 0.4643, MCC: 0.0292, F1: 0.1667

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07271 | val 0.05791
  Epoch 020 - train 0.08014 | val 0.06108
  Epoch 021 - train 0.07990 | val 0.06157
  Regression -> MSE: 0.000108, MAE: 0.008972, R²: -0.0502
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.08406 | val 0.07009
  Epoch 020 - train 0.07806 | val 0.07948
  Epoch 021 - train 0.08157 | val 0.07940
  Regression -> MSE: 0.000235, MAE: 0.012679, R²: -0.0158
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.08245 | val 0.08495
  Epoch 020 - train 0.07911 | val 0.08395
  Epoch 021 - train 0.07742 | val 0.08384
  Regression -> MSE: 0.000171, MAE: 0.007817, R²: -0.0257
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07770 | val 0.06104
  Epoch 020 - train 0.08036 | val 0.06673
  Epoch 021 - train 0.08298 | val 0.06754
  Regression -> MSE: 0.000238, MAE: 0.011904, R²: -0.0042
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.07565 | val 0.11481
  Epoch 020 - train 0.07911 | val 0.13331
  Epoch 021 - train 0.07955 | val 0.13512
  Regression -> MSE: 0.000236, MAE: 0.010218, R²: -0.0234
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07770 | val 0.08771
  Epoch 020 - train 0.08441 | val 0.09686
  Epoch 021 - train 0.08121 | val 0.09755
  Regression -> MSE: 0.000137, MAE: 0.008275, R²: -0.0148
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07927 | val 0.09144
  Epoch 020 - train 0.07847 | val 0.09314
  Epoch 021 - train 0.07412 | val 0.09308
  Regression -> MSE: 0.000188, MAE: 0.010514, R²: 0.0005
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06978 | val 0.08760
  Epoch 020 - train 0.06975 | val 0.08706
  Epoch 021 - train 0.07205 | val 0.08701
  Regression -> MSE: 0.000264, MAE: 0.010520, R²: -0.0094
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07940 | val 0.06025
  Epoch 020 - train 0.07833 | val 0.06008
  Epoch 021 - train 0.08086 | val 0.06007
  Regression -> MSE: 0.000167, MAE: 0.010372, R²: -0.0034
  Directional -> Accuracy: 0.4737, MCC: -0.0976, F1: 0.6296

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.07530 | val 0.07009
  Epoch 020 - train 0.06690 | val 0.07875
  Epoch 021 - train 0.07435 | val 0.07884
  Regression -> MSE: 0.000181, MAE: 0.010351, R²: -0.0038
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07583 | val 0.07806
  Epoch 020 - train 0.07792 | val 0.07895
  Epoch 021 - train 0.07728 | val 0.07876
  Regression -> MSE: 0.000343, MAE: 0.011850, R²: -0.0007
  Directional -> Accuracy: 0.4328, MCC: -0.0822, F1: 0.3214

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.08439 | val 0.05020
  Epoch 020 - train 0.09281 | val 0.07204
  Epoch 021 - train 0.08169 | val 0.07356
  Regression -> MSE: 0.000130, MAE: 0.008579, R²: -0.2385
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07970 | val 0.09324
  Epoch 020 - train 0.07721 | val 0.09548
  Epoch 021 - train 0.08002 | val 0.09547
  Regression -> MSE: 0.000223, MAE: 0.011408, R²: -0.0191
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07917 | val 0.12346
  Epoch 020 - train 0.07626 | val 0.15858
  Epoch 021 - train 0.07722 | val 0.15900
  Regression -> MSE: 0.000093, MAE: 0.007549, R²: -0.2024
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07535 | val 0.06459
  Epoch 020 - train 0.07519 | val 0.06579
  Epoch 021 - train 0.08150 | val 0.06578
  Regression -> MSE: 0.000347, MAE: 0.015590, R²: -0.1279
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07657 | val 0.04801
  Epoch 020 - train 0.07736 | val 0.05182
  Epoch 021 - train 0.07965 | val 0.05249
  Regression -> MSE: 0.000257, MAE: 0.011467, R²: -0.0532
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08263 | val 0.08917
  Epoch 020 - train 0.08196 | val 0.08921
  Epoch 021 - train 0.07902 | val 0.08917
  Regression -> MSE: 0.000085, MAE: 0.007062, R²: -0.0546
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07332 | val 0.09059
  Epoch 020 - train 0.07991 | val 0.09099
  Epoch 021 - train 0.07553 | val 0.09120
  Regression -> MSE: 0.000310, MAE: 0.014491, R²: -0.0109
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08012 | val 0.08546
  Epoch 020 - train 0.08136 | val 0.10048
  Epoch 021 - train 0.07799 | val 0.10272
  Regression -> MSE: 0.000102, MAE: 0.007108, R²: -0.0376
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08268 | val 0.08378
  Epoch 020 - train 0.08540 | val 0.08601
  Epoch 021 - train 0.08221 | val 0.08622
  Regression -> MSE: 0.000174, MAE: 0.010123, R²: -0.0152
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.07322 | val 0.09299
  Epoch 020 - train 0.07190 | val 0.11212
  Epoch 021 - train 0.07244 | val 0.11215
  Regression -> MSE: 0.000223, MAE: 0.011730, R²: 0.0015
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.08085 | val 0.08612
  Epoch 020 - train 0.08341 | val 0.09155
  Epoch 021 - train 0.08311 | val 0.09144
  Regression -> MSE: 0.000093, MAE: 0.007657, R²: -0.0100
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...


[I 2026-02-24 05:43:55,201] Trial 199 finished with value: -0.011507117641831094 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 7.862581261420507e-06, 'weight_decay': 1.7829428778467615e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.10058258214520405, 'early_stopping_min_delta': 0.0070521383185021625}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.07651 | val 0.10578
  Regression -> MSE: 0.000237, MAE: 0.012391, R²: -0.0012
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiLSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12329 | val 0.16504
  Epoch 020 - train 0.12160 | val 0.16520
  Epoch 021 - train 0.12477 | val 0.16488
  Regression -> MSE: 0.000246, MAE: 0.012471, R²: 0.0048
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12593 | val 0.12082
  Epoch 020 - train 0.12191 | val 0.13703
  Epoch 021 - train 0.11649 | val 0.13748
  Regression -> MSE: 0.000699, MAE: 0.019580, R²: -0.0210
  Directional -> Accuracy: 0.5870, MCC: 0.1313, F1: 0.6780

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12937 | val 0.21196
  Epoch 020 - train 0.12923 | val 0.21531
  Epoch 021 - train 0.12977 | val 0.21536
  Regression -> MSE: 0.000311, MAE: 0.014457, R²: -0.0013
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11805 | val 0.15147
  Epoch 020 - train 0.11457 | val 0.13904
  Epoch 021 - train 0.11897 | val 0.13598
  Regression -> MSE: 0.000357, MAE: 0.014690, R²: -0.0225
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12643 | val 0.12506
  Epoch 020 - train 0.12561 | val 0.12384
  Epoch 021 - train 0.12587 | val 0.12373
  Regression -> MSE: 0.000205, MAE: 0.010082, R²: -0.0047
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12390 | val 0.23494
  Epoch 020 - train 0.11606 | val 0.24240
  Epoch 030 - train 0.11484 | val 0.24361
  Regression -> MSE: 0.000575, MAE: 0.018533, R²: -0.0360
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12691 | val 0.15870
  Epoch 020 - train 0.12964 | val 0.16037
  Epoch 021 - train 0.12753 | val 0.16029
  Regression -> MSE: 0.000248, MAE: 0.012379, R²: -0.0105
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13080 | val 0.15353
  Epoch 020 - train 0.13052 | val 0.15232
  Epoch 021 - train 0.13221 | val 0.15198
  Regression -> MSE: 0.000608, MAE: 0.019424, R²: -0.0174
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11762 | val 0.15256
  Epoch 020 - train 0.12126 | val 0.15548
  Epoch 021 - train 0.12120 | val 0.15550
  Regression -> MSE: 0.000397, MAE: 0.016003, R²: -0.0359
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12709 | val 0.17202
  Epoch 020 - train 0.12547 | val 0.17670
  Epoch 021 - train 0.12210 | val 0.17622
  Regression -> MSE: 0.000242, MAE: 0.011847, R²: -0.0013
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.13598 | val 0.17461
  Epoch 020 - train 0.13302 | val 0.17498
  Epoch 021 - train 0.12648 | val 0.17539
  Regression -> MSE: 0.000324, MAE: 0.013600, R²: -0.0414
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13262 | val 0.15380
  Epoch 020 - train 0.13010 | val 0.15447
  Epoch 021 - train 0.12899 | val 0.15367
  Regression -> MSE: 0.000682, MAE: 0.019674, R²: -0.0076
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13760 | val 0.13719
  Epoch 020 - train 0.13174 | val 0.15665
  Epoch 021 - train 0.13391 | val 0.15789
  Regression -> MSE: 0.000139, MAE: 0.009210, R²: -0.0056
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12317 | val 0.16480
  Epoch 020 - train 0.12122 | val 0.16397
  Epoch 021 - train 0.11861 | val 0.16407
  Regression -> MSE: 0.000229, MAE: 0.010788, R²: -0.0164
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13171 | val 0.26153
  Epoch 020 - train 0.12373 | val 0.26624
  Epoch 021 - train 0.12684 | val 0.26702
  Regression -> MSE: 0.000366, MAE: 0.015977, R²: -0.0103
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13171 | val 0.13007
  Epoch 020 - train 0.12734 | val 0.12960
  Epoch 021 - train 0.12832 | val 0.12981
  Regression -> MSE: 0.000109, MAE: 0.007933, R²: -0.0063
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12471 | val 0.21563
  Epoch 020 - train 0.11966 | val 0.22502
  Epoch 021 - train 0.11948 | val 0.22440
  Regression -> MSE: 0.000159, MAE: 0.009997, R²: -0.0179
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12689 | val 0.12814
  Epoch 020 - train 0.12193 | val 0.12817
  Epoch 021 - train 0.12611 | val 0.12805
  Regression -> MSE: 0.000275, MAE: 0.013192, R²: -0.0106
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12006 | val 0.17529
  Epoch 020 - train 0.12057 | val 0.17612
  Epoch 021 - train 0.11740 | val 0.17616
  Regression -> MSE: 0.000173, MAE: 0.009307, R²: -0.1569
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12564 | val 0.17877
  Epoch 020 - train 0.12651 | val 0.18091
  Epoch 021 - train 0.12584 | val 0.18079
  Regression -> MSE: 0.000240, MAE: 0.011070, R²: -0.0620
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12534 | val 0.15384
  Epoch 020 - train 0.12530 | val 0.15373
  Epoch 030 - train 0.12419 | val 0.15382
  Regression -> MSE: 0.000153, MAE: 0.008762, R²: -0.0670
  Directional -> Accuracy: 0.5833, MCC: 0.3077, F1: 0.5455

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12448 | val 0.15211
  Epoch 020 - train 0.12130 | val 0.15115
  Epoch 021 - train 0.12031 | val 0.15117
  Regression -> MSE: 0.000165, MAE: 0.010464, R²: -0.0001
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13113 | val 0.15812
  Epoch 020 - train 0.13062 | val 0.15746
  Epoch 021 - train 0.13194 | val 0.15785
  Regression -> MSE: 0.000086, MAE: 0.007061, R²: -0.0050
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12574 | val 0.17467
  Epoch 020 - train 0.12698 | val 0.17560
  Epoch 021 - train 0.12452 | val 0.17591
  Regression -> MSE: 0.000214, MAE: 0.011036, R²: -0.0108
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11456 | val 0.11187
  Epoch 020 - train 0.11520 | val 0.11105
  Epoch 030 - train 0.11622 | val 0.11123
  Regression -> MSE: 0.000098, MAE: 0.008049, R²: -0.0699
  Directional -> Accuracy: 0.5179, MCC: 0.0518, F1: 0.5091

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12867 | val 0.10043
  Epoch 020 - train 0.12805 | val 0.10463
  Epoch 021 - train 0.13129 | val 0.10489
  Regression -> MSE: 0.000108, MAE: 0.008958, R²: -0.0481
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12966 | val 0.12866
  Epoch 020 - train 0.13815 | val 0.14043
  Epoch 021 - train 0.12674 | val 0.14115
  Regression -> MSE: 0.000234, MAE: 0.012628, R²: -0.0093
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12546 | val 0.15894
  Epoch 020 - train 0.12532 | val 0.16093
  Epoch 021 - train 0.12177 | val 0.16101
  Regression -> MSE: 0.000173, MAE: 0.007832, R²: -0.0397
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12835 | val 0.10671
  Epoch 020 - train 0.12689 | val 0.11054
  Epoch 021 - train 0.12781 | val 0.11038
  Regression -> MSE: 0.000237, MAE: 0.011865, R²: -0.0007
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12263 | val 0.20390
  Epoch 020 - train 0.12343 | val 0.21404
  Epoch 021 - train 0.12492 | val 0.21427
  Regression -> MSE: 0.000231, MAE: 0.009910, R²: -0.0010
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13729 | val 0.17150
  Epoch 020 - train 0.13564 | val 0.20251
  Epoch 021 - train 0.12995 | val 0.20305
  Regression -> MSE: 0.000142, MAE: 0.008505, R²: -0.0487
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13301 | val 0.16533
  Epoch 020 - train 0.12617 | val 0.16800
  Epoch 021 - train 0.12204 | val 0.16789
  Regression -> MSE: 0.000191, MAE: 0.010394, R²: -0.0150
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11733 | val 0.15512
  Epoch 020 - train 0.11988 | val 0.15278
  Epoch 021 - train 0.11616 | val 0.15276
  Regression -> MSE: 0.000263, MAE: 0.010701, R²: -0.0047
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12068 | val 0.11002
  Epoch 020 - train 0.11607 | val 0.10774
  Epoch 021 - train 0.11921 | val 0.10751
  Regression -> MSE: 0.000167, MAE: 0.010376, R²: -0.0040
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11228 | val 0.12902
  Epoch 020 - train 0.11647 | val 0.13513
  Epoch 021 - train 0.11045 | val 0.13513
  Regression -> MSE: 0.000182, MAE: 0.010317, R²: -0.0087
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12462 | val 0.12012
  Epoch 020 - train 0.11946 | val 0.12413
  Epoch 021 - train 0.12225 | val 0.12428
  Regression -> MSE: 0.000341, MAE: 0.011761, R²: 0.0034
  Directional -> Accuracy: 0.5373, MCC: -0.0278, F1: 0.6737

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13213 | val 0.08124
  Epoch 020 - train 0.13085 | val 0.08195
  Epoch 021 - train 0.12857 | val 0.08205
  Regression -> MSE: 0.000129, MAE: 0.008548, R²: -0.2264
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12441 | val 0.17577
  Epoch 020 - train 0.12274 | val 0.17748
  Epoch 021 - train 0.12336 | val 0.17757
  Regression -> MSE: 0.000219, MAE: 0.011286, R²: -0.0007
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12802 | val 0.22787
  Epoch 020 - train 0.12184 | val 0.23797
  Epoch 021 - train 0.11867 | val 0.23779
  Regression -> MSE: 0.000084, MAE: 0.007146, R²: -0.0789
  Directional -> Accuracy: 0.4255, MCC: 0.0074, F1: 0.2703

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12432 | val 0.10987
  Epoch 020 - train 0.12621 | val 0.11160
  Epoch 021 - train 0.12163 | val 0.11184
  Regression -> MSE: 0.000338, MAE: 0.015294, R²: -0.0973
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14197 | val 0.07796
  Epoch 020 - train 0.14025 | val 0.08348
  Epoch 021 - train 0.14582 | val 0.08429
  Regression -> MSE: 0.000247, MAE: 0.011554, R²: -0.0137
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12008 | val 0.15468
  Epoch 020 - train 0.11502 | val 0.15750
  Epoch 021 - train 0.12015 | val 0.15729
  Regression -> MSE: 0.000081, MAE: 0.007104, R²: -0.0042
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12707 | val 0.15599
  Epoch 020 - train 0.12732 | val 0.15912
  Epoch 021 - train 0.12188 | val 0.15958
  Regression -> MSE: 0.000306, MAE: 0.014484, R²: 0.0018
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12174 | val 0.14623
  Epoch 020 - train 0.12379 | val 0.14267
  Epoch 021 - train 0.12076 | val 0.14345
  Regression -> MSE: 0.000100, MAE: 0.007122, R²: -0.0224
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13926 | val 0.15136
  Epoch 020 - train 0.13827 | val 0.15995
  Epoch 021 - train 0.13535 | val 0.16057
  Regression -> MSE: 0.000172, MAE: 0.009659, R²: -0.0007
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 05:47:53,495] Trial 200 finished with value: -0.011444398096295523 and parameters: {'feature_set': 'all_nlp', 'model_type': 'BiLSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.4, 'batch_size': 32, 'learning_rate': 1.0662064193054749e-05, 'weight_decay': 2.3154224536429135e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.19078912687730148, 'early_stopping_min_delta': 0.0053858406991268825}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.13378 | val 0.19589
  Regression -> MSE: 0.000238, MAE: 0.012413, R²: -0.0031
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09021 | val 0.12026
  Epoch 020 - train 0.08692 | val 0.12241
  Epoch 021 - train 0.08820 | val 0.12189
  Regression -> MSE: 0.000258, MAE: 0.012938, R²: -0.0416
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08671 | val 0.08991
  Epoch 020 - train 0.08214 | val 0.09062
  Epoch 021 - train 0.08417 | val 0.09076
  Regression -> MSE: 0.000689, MAE: 0.019405, R²: -0.0063
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09104 | val 0.14867
  Epoch 020 - train 0.09238 | val 0.14748
  Epoch 021 - train 0.09002 | val 0.14750
  Regression -> MSE: 0.000311, MAE: 0.014466, R²: -0.0016
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07539 | val 0.19645
  Epoch 020 - train 0.07535 | val 0.19402
  Epoch 021 - train 0.07380 | val 0.19313
  Regression -> MSE: 0.000365, MAE: 0.014840, R²: -0.0449
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.08960 | val 0.09011
  Epoch 020 - train 0.08604 | val 0.08992
  Epoch 021 - train 0.08450 | val 0.09001
  Regression -> MSE: 0.000204, MAE: 0.010243, R²: 0.0005
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08902 | val 0.16924
  Epoch 020 - train 0.08471 | val 0.19840
  Epoch 021 - train 0.08596 | val 0.19814
  Regression -> MSE: 0.000572, MAE: 0.018415, R²: -0.0303
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09120 | val 0.11560
  Epoch 020 - train 0.08833 | val 0.11764
  Epoch 021 - train 0.08903 | val 0.11774
  Regression -> MSE: 0.000246, MAE: 0.011985, R²: -0.0008
  Directional -> Accuracy: 0.3913, MCC: -0.1133, F1: 0.5532

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.08805 | val 0.12096
  Epoch 020 - train 0.08595 | val 0.12823
  Epoch 021 - train 0.08677 | val 0.12871
  Regression -> MSE: 0.000622, MAE: 0.019731, R²: -0.0409
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08425 | val 0.10899
  Epoch 020 - train 0.08116 | val 0.10790
  Epoch 021 - train 0.08059 | val 0.10777
  Regression -> MSE: 0.000407, MAE: 0.016195, R²: -0.0617
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.08819 | val 0.12520
  Epoch 020 - train 0.08504 | val 0.12500
  Epoch 021 - train 0.08614 | val 0.12506
  Regression -> MSE: 0.000241, MAE: 0.011945, R²: 0.0004
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08360 | val 0.12830
  Epoch 020 - train 0.08110 | val 0.13068
  Epoch 021 - train 0.08371 | val 0.13145
  Regression -> MSE: 0.000315, MAE: 0.013589, R²: -0.0140
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09106 | val 0.11391
  Epoch 020 - train 0.09261 | val 0.11641
  Epoch 021 - train 0.08973 | val 0.11645
  Regression -> MSE: 0.000679, MAE: 0.019558, R²: -0.0025
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.08684 | val 0.11124
  Epoch 020 - train 0.08445 | val 0.12613
  Epoch 021 - train 0.08615 | val 0.12797
  Regression -> MSE: 0.000140, MAE: 0.009008, R²: -0.0100
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08349 | val 0.11269
  Epoch 020 - train 0.07869 | val 0.11465
  Epoch 021 - train 0.07803 | val 0.11479
  Regression -> MSE: 0.000229, MAE: 0.010828, R²: -0.0200
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08607 | val 0.18246
  Epoch 020 - train 0.08355 | val 0.18154
  Epoch 021 - train 0.08198 | val 0.18092
  Regression -> MSE: 0.000366, MAE: 0.015966, R²: -0.0099
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09328 | val 0.10370
  Epoch 020 - train 0.09168 | val 0.10374
  Epoch 021 - train 0.09249 | val 0.10381
  Regression -> MSE: 0.000109, MAE: 0.007962, R²: -0.0099
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09144 | val 0.19073
  Epoch 020 - train 0.08737 | val 0.20976
  Epoch 021 - train 0.08755 | val 0.21018
  Regression -> MSE: 0.000163, MAE: 0.010226, R²: -0.0443
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09063 | val 0.09945
  Epoch 020 - train 0.08949 | val 0.10031
  Epoch 021 - train 0.08953 | val 0.09987
  Regression -> MSE: 0.000272, MAE: 0.013013, R²: -0.0007
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.07889 | val 0.12491
  Epoch 020 - train 0.07810 | val 0.12541
  Epoch 021 - train 0.07803 | val 0.12562
  Regression -> MSE: 0.000158, MAE: 0.008834, R²: -0.0539
  Directional -> Accuracy: 0.6000, MCC: 0.1140, F1: 0.7234

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09058 | val 0.13194
  Epoch 020 - train 0.08827 | val 0.13883
  Epoch 021 - train 0.08765 | val 0.13961
  Regression -> MSE: 0.000234, MAE: 0.010967, R²: -0.0336
  Directional -> Accuracy: 0.4933, MCC: -0.1208, F1: 0.6415

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09121 | val 0.11911
  Epoch 020 - train 0.08827 | val 0.13781
  Epoch 021 - train 0.08889 | val 0.13848
  Regression -> MSE: 0.000144, MAE: 0.008373, R²: -0.0059
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.08406 | val 0.11697
  Epoch 020 - train 0.08460 | val 0.11973
  Epoch 021 - train 0.08548 | val 0.11953
  Regression -> MSE: 0.000177, MAE: 0.010286, R²: -0.0739
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09221 | val 0.11012
  Epoch 020 - train 0.09084 | val 0.11260
  Epoch 021 - train 0.08983 | val 0.11353
  Regression -> MSE: 0.000085, MAE: 0.007036, R²: -0.0027
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.08996 | val 0.18842
  Epoch 020 - train 0.08666 | val 0.20901
  Epoch 021 - train 0.08527 | val 0.21151
  Regression -> MSE: 0.000212, MAE: 0.011218, R²: -0.0002
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08256 | val 0.08342
  Epoch 020 - train 0.08146 | val 0.08351
  Epoch 021 - train 0.07856 | val 0.08342
  Regression -> MSE: 0.000094, MAE: 0.008099, R²: -0.0225
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09248 | val 0.07752
  Epoch 020 - train 0.08737 | val 0.07426
  Epoch 021 - train 0.08997 | val 0.07391
  Regression -> MSE: 0.000111, MAE: 0.009060, R²: -0.0746
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09361 | val 0.08997
  Epoch 020 - train 0.09255 | val 0.11719
  Epoch 021 - train 0.09080 | val 0.11772
  Regression -> MSE: 0.000232, MAE: 0.012534, R²: -0.0007
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09183 | val 0.11382
  Epoch 020 - train 0.08589 | val 0.11605
  Epoch 021 - train 0.08694 | val 0.11592
  Regression -> MSE: 0.000179, MAE: 0.007943, R²: -0.0763
  Directional -> Accuracy: 0.4561, MCC: -0.0157, F1: 0.2791

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09211 | val 0.08012
  Epoch 020 - train 0.09141 | val 0.08117
  Epoch 021 - train 0.09261 | val 0.08136
  Regression -> MSE: 0.000237, MAE: 0.011885, R²: -0.0022
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.08996 | val 0.14901
  Epoch 020 - train 0.09044 | val 0.17338
  Epoch 021 - train 0.08696 | val 0.17409
  Regression -> MSE: 0.000231, MAE: 0.009883, R²: -0.0025
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09422 | val 0.11516
  Epoch 020 - train 0.08916 | val 0.12990
  Epoch 021 - train 0.09045 | val 0.12992
  Regression -> MSE: 0.000136, MAE: 0.008266, R²: -0.0045
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09029 | val 0.12137
  Epoch 020 - train 0.08753 | val 0.12887
  Epoch 021 - train 0.08837 | val 0.12909
  Regression -> MSE: 0.000191, MAE: 0.010378, R²: -0.0152
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.07825 | val 0.10447
  Epoch 020 - train 0.07784 | val 0.10789
  Epoch 021 - train 0.07565 | val 0.10714
  Regression -> MSE: 0.000269, MAE: 0.010600, R²: -0.0272
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09061 | val 0.08762
  Epoch 020 - train 0.08793 | val 0.08474
  Epoch 021 - train 0.08435 | val 0.08449
  Regression -> MSE: 0.000171, MAE: 0.010402, R²: -0.0280
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08118 | val 0.09687
  Epoch 020 - train 0.07986 | val 0.10001
  Epoch 021 - train 0.07886 | val 0.10079
  Regression -> MSE: 0.000182, MAE: 0.010396, R²: -0.0105
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.08389 | val 0.08597
  Epoch 020 - train 0.08124 | val 0.08842
  Epoch 021 - train 0.08222 | val 0.08871
  Regression -> MSE: 0.000347, MAE: 0.011757, R²: -0.0139
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10015 | val 0.06527
  Epoch 020 - train 0.09594 | val 0.06985
  Epoch 021 - train 0.09343 | val 0.07064
  Regression -> MSE: 0.000131, MAE: 0.008596, R²: -0.2490
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.08839 | val 0.12514
  Epoch 020 - train 0.08809 | val 0.12656
  Epoch 021 - train 0.08839 | val 0.12666
  Regression -> MSE: 0.000219, MAE: 0.011297, R²: -0.0012
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.08957 | val 0.16504
  Epoch 020 - train 0.08755 | val 0.16956
  Epoch 021 - train 0.08696 | val 0.17056
  Regression -> MSE: 0.000080, MAE: 0.006963, R²: -0.0309
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08541 | val 0.07252
  Epoch 020 - train 0.08487 | val 0.07679
  Epoch 021 - train 0.08681 | val 0.07713
  Regression -> MSE: 0.000311, MAE: 0.014025, R²: -0.0106
  Directional -> Accuracy: 0.4490, MCC: 0.1555, F1: 0.5574

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09365 | val 0.06241
  Epoch 020 - train 0.09297 | val 0.06460
  Epoch 021 - train 0.08807 | val 0.06561
  Regression -> MSE: 0.000261, MAE: 0.011505, R²: -0.0692
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08384 | val 0.10956
  Epoch 020 - train 0.08220 | val 0.11042
  Epoch 021 - train 0.08281 | val 0.11037
  Regression -> MSE: 0.000081, MAE: 0.007058, R²: 0.0024
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.09266 | val 0.11384
  Epoch 020 - train 0.08935 | val 0.11495
  Epoch 021 - train 0.08874 | val 0.11643
  Regression -> MSE: 0.000307, MAE: 0.014507, R²: -0.0019
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.08452 | val 0.11084
  Epoch 020 - train 0.08496 | val 0.10888
  Epoch 021 - train 0.08574 | val 0.10862
  Regression -> MSE: 0.000102, MAE: 0.007113, R²: -0.0363
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.09591 | val 0.10859
  Epoch 020 - train 0.09422 | val 0.10836
  Epoch 021 - train 0.09443 | val 0.10856
  Regression -> MSE: 0.000173, MAE: 0.009859, R²: -0.0038
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08392 | val 0.10584
  Epoch 020 - train 0.08521 | val 0.10713
  Epoch 021 - train 0.08366 | val 0.10727
  Regression -> MSE: 0.000224, MAE: 0.011795, R²: -0.0040
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.08607 | val 0.11007
  Epoch 020 - train 0.08630 | val 0.11685
  Epoch 021 - train 0.08597 | val 0.11706
  Regression -> MSE: 0.000093, MAE: 0.007666, R²: -0.0026

[I 2026-02-24 05:50:01,873] Trial 201 finished with value: -0.011402729693793603 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 4.1322455735153325e-05, 'weight_decay': 1.2312572521698998e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.13554937054341493, 'early_stopping_min_delta': 0.006781949889734084}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.09019 | val 0.12878
  Epoch 021 - train 0.09058 | val 0.12835
  Regression -> MSE: 0.000245, MAE: 0.012370, R²: -0.0313
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10001 | val 0.13998
  Epoch 020 - train 0.10113 | val 0.14039
  Epoch 021 - train 0.10131 | val 0.14060
  Regression -> MSE: 0.000251, MAE: 0.012701, R²: -0.0148
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10169 | val 0.11121
  Epoch 020 - train 0.10030 | val 0.16280
  Epoch 021 - train 0.09894 | val 0.16209
  Regression -> MSE: 0.000717, MAE: 0.019898, R²: -0.0481
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10998 | val 0.17024
  Epoch 020 - train 0.10697 | val 0.17212
  Epoch 021 - train 0.10853 | val 0.17220
  Regression -> MSE: 0.000310, MAE: 0.014454, R²: -0.0001
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09140 | val 0.09580
  Epoch 020 - train 0.08851 | val 0.09101
  Epoch 021 - train 0.09059 | val 0.09165
  Regression -> MSE: 0.000350, MAE: 0.014596, R²: -0.0015
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.10254 | val 0.10810
  Epoch 020 - train 0.10525 | val 0.11032
  Epoch 021 - train 0.10525 | val 0.10962
  Regression -> MSE: 0.000206, MAE: 0.010360, R²: -0.0125
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09835 | val 0.19293
  Epoch 020 - train 0.09409 | val 0.20625
  Epoch 021 - train 0.10057 | val 0.20709
  Regression -> MSE: 0.000561, MAE: 0.018190, R²: -0.0105
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10626 | val 0.12531
  Epoch 020 - train 0.10559 | val 0.12377
  Epoch 021 - train 0.10365 | val 0.12385
  Regression -> MSE: 0.000246, MAE: 0.012168, R²: -0.0023
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10260 | val 0.13003
  Epoch 020 - train 0.09881 | val 0.12119
  Epoch 030 - train 0.09804 | val 0.12332
  Regression -> MSE: 0.000601, MAE: 0.019159, R²: -0.0062
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11031 | val 0.12040
  Epoch 020 - train 0.10755 | val 0.12538
  Epoch 021 - train 0.10739 | val 0.12569
  Regression -> MSE: 0.000410, MAE: 0.016242, R²: -0.0693
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10969 | val 0.17947
  Epoch 020 - train 0.10740 | val 0.18253
  Epoch 021 - train 0.10623 | val 0.18411
  Regression -> MSE: 0.000246, MAE: 0.011642, R²: -0.0173
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09490 | val 0.14368
  Epoch 020 - train 0.09775 | val 0.14314
  Epoch 021 - train 0.09620 | val 0.14309
  Regression -> MSE: 0.000321, MAE: 0.013590, R²: -0.0323
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10659 | val 0.13092
  Epoch 020 - train 0.10552 | val 0.14103
  Epoch 021 - train 0.10570 | val 0.14042
  Regression -> MSE: 0.000678, MAE: 0.019475, R²: -0.0009
  Directional -> Accuracy: 0.5517, MCC: 0.1037, F1: 0.5667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10581 | val 0.10261
  Epoch 020 - train 0.10255 | val 0.10521
  Epoch 021 - train 0.10354 | val 0.10447
  Regression -> MSE: 0.000145, MAE: 0.009527, R²: -0.0520
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09834 | val 0.14987
  Epoch 020 - train 0.09401 | val 0.15507
  Epoch 021 - train 0.09473 | val 0.15517
  Regression -> MSE: 0.000225, MAE: 0.010700, R²: -0.0012
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10100 | val 0.20556
  Epoch 020 - train 0.09884 | val 0.20554
  Epoch 021 - train 0.09821 | val 0.20547
  Regression -> MSE: 0.000369, MAE: 0.015945, R²: -0.0197
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10646 | val 0.10433
  Epoch 020 - train 0.10628 | val 0.10452
  Epoch 021 - train 0.10544 | val 0.10500
  Regression -> MSE: 0.000108, MAE: 0.007953, R²: -0.0037
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10306 | val 0.16412
  Epoch 020 - train 0.09914 | val 0.16746
  Epoch 021 - train 0.09994 | val 0.16806
  Regression -> MSE: 0.000156, MAE: 0.009545, R²: 0.0024
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10345 | val 0.10815
  Epoch 020 - train 0.10390 | val 0.10801
  Epoch 021 - train 0.10346 | val 0.10768
  Regression -> MSE: 0.000272, MAE: 0.012972, R²: -0.0001
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09662 | val 0.14017
  Epoch 020 - train 0.09274 | val 0.14041
  Epoch 021 - train 0.09419 | val 0.14056
  Regression -> MSE: 0.000153, MAE: 0.008761, R²: -0.0221
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11170 | val 0.16954
  Epoch 020 - train 0.11072 | val 0.16524
  Epoch 021 - train 0.11053 | val 0.16540
  Regression -> MSE: 0.000229, MAE: 0.010907, R²: -0.0136
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10650 | val 0.12933
  Epoch 020 - train 0.10217 | val 0.13018
  Epoch 021 - train 0.10425 | val 0.13033
  Regression -> MSE: 0.000144, MAE: 0.008317, R²: -0.0013
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09658 | val 0.13023
  Epoch 020 - train 0.09532 | val 0.13132
  Epoch 021 - train 0.09775 | val 0.13163
  Regression -> MSE: 0.000166, MAE: 0.010362, R²: -0.0043
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10865 | val 0.12900
  Epoch 020 - train 0.10635 | val 0.13012
  Epoch 021 - train 0.10695 | val 0.13016
  Regression -> MSE: 0.000094, MAE: 0.007483, R²: -0.1035
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10974 | val 0.13313
  Epoch 020 - train 0.10980 | val 0.14291
  Epoch 021 - train 0.10804 | val 0.14058
  Regression -> MSE: 0.000217, MAE: 0.011034, R²: -0.0256
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09605 | val 0.09513
  Epoch 020 - train 0.09600 | val 0.09507
  Epoch 021 - train 0.09513 | val 0.09554
  Regression -> MSE: 0.000094, MAE: 0.008084, R²: -0.0212
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10480 | val 0.08881
  Epoch 020 - train 0.10507 | val 0.09126
  Epoch 021 - train 0.10384 | val 0.09132
  Regression -> MSE: 0.000117, MAE: 0.009229, R²: -0.1323
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10875 | val 0.10834
  Epoch 020 - train 0.10499 | val 0.12158
  Epoch 021 - train 0.10553 | val 0.12095
  Regression -> MSE: 0.000232, MAE: 0.012520, R²: -0.0005
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11305 | val 0.14010
  Epoch 020 - train 0.11068 | val 0.14116
  Epoch 021 - train 0.10966 | val 0.14088
  Regression -> MSE: 0.000169, MAE: 0.007874, R²: -0.0136
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11055 | val 0.08907
  Epoch 020 - train 0.10635 | val 0.10194
  Epoch 021 - train 0.10974 | val 0.10488
  Regression -> MSE: 0.000239, MAE: 0.011936, R²: -0.0085
  Directional -> Accuracy: 0.5610, MCC: 0.1241, F1: 0.5714

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12013 | val 0.16117
  Epoch 020 - train 0.11763 | val 0.16495
  Epoch 021 - train 0.11324 | val 0.16522
  Regression -> MSE: 0.000231, MAE: 0.009884, R²: -0.0020
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10420 | val 0.13005
  Epoch 020 - train 0.10717 | val 0.13579
  Epoch 021 - train 0.10487 | val 0.13588
  Regression -> MSE: 0.000138, MAE: 0.008319, R²: -0.0233
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10695 | val 0.12774
  Epoch 020 - train 0.10808 | val 0.12983
  Epoch 021 - train 0.10686 | val 0.12990
  Regression -> MSE: 0.000190, MAE: 0.010407, R²: -0.0071
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09360 | val 0.11915
  Epoch 020 - train 0.09209 | val 0.11793
  Epoch 021 - train 0.09176 | val 0.11776
  Regression -> MSE: 0.000262, MAE: 0.010569, R²: -0.0008
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09480 | val 0.08764
  Epoch 020 - train 0.09461 | val 0.08814
  Epoch 021 - train 0.09706 | val 0.08828
  Regression -> MSE: 0.000168, MAE: 0.010361, R²: -0.0059
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09382 | val 0.11545
  Epoch 020 - train 0.09564 | val 0.11911
  Epoch 021 - train 0.09532 | val 0.11919
  Regression -> MSE: 0.000188, MAE: 0.010640, R²: -0.0454
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11097 | val 0.10551
  Epoch 020 - train 0.10970 | val 0.10586
  Epoch 021 - train 0.10760 | val 0.10556
  Regression -> MSE: 0.000347, MAE: 0.012238, R²: -0.0135
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11231 | val 0.06850
  Epoch 020 - train 0.10982 | val 0.06818
  Epoch 021 - train 0.10904 | val 0.06832
  Regression -> MSE: 0.000117, MAE: 0.008337, R²: -0.1115
  Directional -> Accuracy: 0.5116, MCC: 0.0111, F1: 0.6316

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10518 | val 0.14753
  Epoch 020 - train 0.10481 | val 0.15508
  Epoch 021 - train 0.10403 | val 0.15473
  Regression -> MSE: 0.000219, MAE: 0.011280, R²: -0.0007
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10131 | val 0.17658
  Epoch 020 - train 0.10264 | val 0.18440
  Epoch 021 - train 0.10517 | val 0.18438
  Regression -> MSE: 0.000098, MAE: 0.007729, R²: -0.2642
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10814 | val 0.09357
  Epoch 020 - train 0.10663 | val 0.09261
  Epoch 021 - train 0.10652 | val 0.09305
  Regression -> MSE: 0.000344, MAE: 0.015512, R²: -0.1197
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11580 | val 0.06285
  Epoch 020 - train 0.11370 | val 0.06186
  Epoch 021 - train 0.11243 | val 0.06191
  Regression -> MSE: 0.000245, MAE: 0.011549, R²: -0.0062
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10633 | val 0.13374
  Epoch 020 - train 0.10533 | val 0.13390
  Epoch 021 - train 0.10464 | val 0.13396
  Regression -> MSE: 0.000082, MAE: 0.007074, R²: -0.0160
  Directional -> Accuracy: 0.4667, MCC: -0.2014, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10467 | val 0.12554
  Epoch 020 - train 0.10176 | val 0.13388
  Epoch 021 - train 0.10164 | val 0.13425
  Regression -> MSE: 0.000306, MAE: 0.014481, R²: 0.0016
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10271 | val 0.12412
  Epoch 020 - train 0.10053 | val 0.11299
  Epoch 030 - train 0.09952 | val 0.10849
  Regression -> MSE: 0.000097, MAE: 0.006965, R²: 0.0094
  Directional -> Accuracy: 0.5909, MCC: 0.1216, F1: 0.7188

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11057 | val 0.12468
  Epoch 020 - train 0.10852 | val 0.12970
  Epoch 021 - train 0.10994 | val 0.13050
  Regression -> MSE: 0.000173, MAE: 0.009503, R²: -0.0047
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09634 | val 0.11979
  Epoch 020 - train 0.09647 | val 0.12034
  Epoch 021 - train 0.09587 | val 0.12036
  Regression -> MSE: 0.000224, MAE: 0.011779, R²: -0.0045
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10179 | val 0.11499
  Epoch 020 - train 0.10318 | val 0.11547
  Epoch 021 - train 0.10234 | val 0.11533

[I 2026-02-24 05:52:09,666] Trial 202 finished with value: -0.01143310540952367 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 6.015253586688127e-06, 'weight_decay': 1.418105088623257e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.15296392484560123, 'early_stopping_min_delta': 0.006760932010621105}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.10504 | val 0.16677
  Epoch 021 - train 0.10394 | val 0.16499
  Regression -> MSE: 0.000237, MAE: 0.012393, R²: 0.0010
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10266 | val 0.17170
  Epoch 020 - train 0.10302 | val 0.17224
  Epoch 021 - train 0.10230 | val 0.17257
  Regression -> MSE: 0.000268, MAE: 0.013211, R²: -0.0830
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09383 | val 0.09638
  Epoch 020 - train 0.09217 | val 0.12408
  Epoch 021 - train 0.09144 | val 0.12398
  Regression -> MSE: 0.000684, MAE: 0.019312, R²: 0.0014
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09949 | val 0.15373
  Epoch 020 - train 0.10033 | val 0.15457
  Epoch 030 - train 0.10081 | val 0.15436
  Regression -> MSE: 0.000320, MAE: 0.014129, R²: -0.0328
  Directional -> Accuracy: 0.5106, MCC: 0.0516, F1: 0.4103

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08613 | val 0.15578
  Epoch 020 - train 0.08468 | val 0.15497
  Epoch 021 - train 0.08577 | val 0.15266
  Regression -> MSE: 0.000397, MAE: 0.015410, R²: -0.1355
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09901 | val 0.09929
  Epoch 020 - train 0.10087 | val 0.09648
  Epoch 030 - train 0.09734 | val 0.09501
  Regression -> MSE: 0.000217, MAE: 0.011143, R²: -0.0667
  Directional -> Accuracy: 0.5882, MCC: 0.2986, F1: 0.4000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09729 | val 0.18471
  Epoch 020 - train 0.09277 | val 0.18408
  Epoch 021 - train 0.09707 | val 0.18372
  Regression -> MSE: 0.000576, MAE: 0.018500, R²: -0.0378
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10073 | val 0.12824
  Epoch 020 - train 0.10045 | val 0.12826
  Epoch 021 - train 0.10040 | val 0.12837
  Regression -> MSE: 0.000246, MAE: 0.012207, R²: -0.0013
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09537 | val 0.13911
  Epoch 020 - train 0.09240 | val 0.15128
  Epoch 021 - train 0.09467 | val 0.15232
  Regression -> MSE: 0.000644, MAE: 0.020160, R²: -0.0781
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09348 | val 0.12097
  Epoch 020 - train 0.09214 | val 0.11377
  Epoch 030 - train 0.09023 | val 0.11359
  Regression -> MSE: 0.000418, MAE: 0.016230, R²: -0.0886
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10321 | val 0.13126
  Epoch 020 - train 0.10087 | val 0.13084
  Epoch 021 - train 0.10039 | val 0.13093
  Regression -> MSE: 0.000243, MAE: 0.011773, R²: -0.0046
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10120 | val 0.15781
  Epoch 020 - train 0.09801 | val 0.17837
  Epoch 021 - train 0.10019 | val 0.17837
  Regression -> MSE: 0.000312, MAE: 0.013855, R²: -0.0048
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10400 | val 0.11589
  Epoch 020 - train 0.09876 | val 0.11600
  Epoch 021 - train 0.10342 | val 0.11611
  Regression -> MSE: 0.000678, MAE: 0.019501, R²: -0.0014
  Directional -> Accuracy: 0.4483, MCC: -0.1843, F1: 0.6098

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09677 | val 0.10481
  Epoch 020 - train 0.09413 | val 0.11344
  Epoch 021 - train 0.09665 | val 0.11327
  Regression -> MSE: 0.000140, MAE: 0.009012, R²: -0.0106
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09033 | val 0.12517
  Epoch 020 - train 0.08976 | val 0.12405
  Epoch 021 - train 0.08831 | val 0.12377
  Regression -> MSE: 0.000228, MAE: 0.010770, R²: -0.0131
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09903 | val 0.20950
  Epoch 020 - train 0.09847 | val 0.23323
  Epoch 021 - train 0.09948 | val 0.23163
  Regression -> MSE: 0.000362, MAE: 0.016143, R²: 0.0009
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10341 | val 0.10492
  Epoch 020 - train 0.10224 | val 0.10273
  Epoch 021 - train 0.10313 | val 0.10297
  Regression -> MSE: 0.000108, MAE: 0.008009, R²: -0.0024
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09620 | val 0.16742
  Epoch 020 - train 0.09365 | val 0.17516
  Epoch 021 - train 0.09383 | val 0.17540
  Regression -> MSE: 0.000162, MAE: 0.010182, R²: -0.0376
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09945 | val 0.10129
  Epoch 020 - train 0.09925 | val 0.10183
  Epoch 021 - train 0.09969 | val 0.10176
  Regression -> MSE: 0.000272, MAE: 0.013009, R²: 0.0015
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08680 | val 0.13843
  Epoch 020 - train 0.08661 | val 0.13931
  Epoch 021 - train 0.08601 | val 0.13935
  Regression -> MSE: 0.000161, MAE: 0.008944, R²: -0.0763
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10132 | val 0.14203
  Epoch 020 - train 0.09979 | val 0.13914
  Epoch 021 - train 0.10221 | val 0.13872
  Regression -> MSE: 0.000229, MAE: 0.010896, R²: -0.0135
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10183 | val 0.12395
  Epoch 020 - train 0.10080 | val 0.12595
  Epoch 021 - train 0.09951 | val 0.12510
  Regression -> MSE: 0.000143, MAE: 0.008310, R²: 0.0005
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09567 | val 0.12104
  Epoch 020 - train 0.09682 | val 0.12083
  Epoch 021 - train 0.09467 | val 0.12085
  Regression -> MSE: 0.000174, MAE: 0.010273, R²: -0.0531
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10539 | val 0.12798
  Epoch 020 - train 0.10538 | val 0.13358
  Epoch 021 - train 0.10288 | val 0.13499
  Regression -> MSE: 0.000086, MAE: 0.007062, R²: -0.0068
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10058 | val 0.13578
  Epoch 020 - train 0.09851 | val 0.13467
  Epoch 021 - train 0.09554 | val 0.13339
  Regression -> MSE: 0.000214, MAE: 0.011041, R²: -0.0100
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09221 | val 0.08660
  Epoch 020 - train 0.08883 | val 0.08754
  Epoch 021 - train 0.08936 | val 0.08762
  Regression -> MSE: 0.000099, MAE: 0.008185, R²: -0.0724
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10078 | val 0.07984
  Epoch 020 - train 0.10230 | val 0.08977
  Epoch 021 - train 0.10229 | val 0.09033
  Regression -> MSE: 0.000105, MAE: 0.008856, R²: -0.0205
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10451 | val 0.09512
  Epoch 020 - train 0.10643 | val 0.09716
  Epoch 021 - train 0.10266 | val 0.09712
  Regression -> MSE: 0.000231, MAE: 0.012510, R²: 0.0007
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09985 | val 0.11712
  Epoch 020 - train 0.10071 | val 0.11893
  Epoch 021 - train 0.09844 | val 0.11909
  Regression -> MSE: 0.000181, MAE: 0.007985, R²: -0.0889
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10031 | val 0.08518
  Epoch 020 - train 0.10240 | val 0.08677
  Epoch 021 - train 0.10152 | val 0.08694
  Regression -> MSE: 0.000239, MAE: 0.011949, R²: -0.0112
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10276 | val 0.15789
  Epoch 020 - train 0.10085 | val 0.16127
  Epoch 021 - train 0.10442 | val 0.16127
  Regression -> MSE: 0.000233, MAE: 0.010059, R²: -0.0108
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10050 | val 0.13010
  Epoch 020 - train 0.10079 | val 0.13591
  Epoch 021 - train 0.10221 | val 0.13624
  Regression -> MSE: 0.000144, MAE: 0.008657, R²: -0.0644
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09982 | val 0.12833
  Epoch 020 - train 0.09935 | val 0.13055
  Epoch 021 - train 0.09923 | val 0.13053
  Regression -> MSE: 0.000189, MAE: 0.010383, R²: -0.0044
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08752 | val 0.13524
  Epoch 020 - train 0.08710 | val 0.13509
  Epoch 021 - train 0.08605 | val 0.13683
  Regression -> MSE: 0.000275, MAE: 0.010790, R²: -0.0486
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09061 | val 0.09198
  Epoch 020 - train 0.09311 | val 0.09096
  Epoch 021 - train 0.09287 | val 0.09074
  Regression -> MSE: 0.000171, MAE: 0.010392, R²: -0.0238
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09219 | val 0.10645
  Epoch 020 - train 0.08774 | val 0.12304
  Epoch 021 - train 0.09052 | val 0.12292
  Regression -> MSE: 0.000180, MAE: 0.010331, R²: -0.0020
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09543 | val 0.09096
  Epoch 020 - train 0.09435 | val 0.08935
  Epoch 021 - train 0.09311 | val 0.08926
  Regression -> MSE: 0.000344, MAE: 0.012018, R²: -0.0035
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11458 | val 0.06540
  Epoch 020 - train 0.10975 | val 0.06811
  Epoch 021 - train 0.10734 | val 0.06871
  Regression -> MSE: 0.000115, MAE: 0.008367, R²: -0.0914
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10509 | val 0.13747
  Epoch 020 - train 0.10499 | val 0.13690
  Epoch 021 - train 0.10288 | val 0.13639
  Regression -> MSE: 0.000222, MAE: 0.011409, R²: -0.0172
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10171 | val 0.16421
  Epoch 020 - train 0.10036 | val 0.17129
  Epoch 021 - train 0.09879 | val 0.17127
  Regression -> MSE: 0.000083, MAE: 0.007109, R²: -0.0714
  Directional -> Accuracy: 0.5957, MCC: -0.0267, F1: 0.7397

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10344 | val 0.07476
  Epoch 020 - train 0.09390 | val 0.07410
  Epoch 021 - train 0.09844 | val 0.07402
  Regression -> MSE: 0.000308, MAE: 0.013749, R²: -0.0026
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11758 | val 0.06412
  Epoch 020 - train 0.11435 | val 0.06762
  Epoch 021 - train 0.11707 | val 0.06795
  Regression -> MSE: 0.000257, MAE: 0.011469, R²: -0.0534
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10808 | val 0.12405
  Epoch 020 - train 0.10119 | val 0.12138
  Epoch 021 - train 0.10596 | val 0.12166
  Regression -> MSE: 0.000081, MAE: 0.007115, R²: -0.0065
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.09947 | val 0.11872
  Epoch 020 - train 0.09878 | val 0.12018
  Epoch 021 - train 0.09690 | val 0.12015
  Regression -> MSE: 0.000310, MAE: 0.014542, R²: -0.0089
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09597 | val 0.11739
  Epoch 020 - train 0.09700 | val 0.12319
  Epoch 021 - train 0.09733 | val 0.12385
  Regression -> MSE: 0.000101, MAE: 0.007111, R²: -0.0248
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10935 | val 0.11497
  Epoch 020 - train 0.10601 | val 0.11669
  Epoch 021 - train 0.10567 | val 0.11703
  Regression -> MSE: 0.000172, MAE: 0.009777, R²: -0.0028
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.09091 | val 0.12673
  Epoch 020 - train 0.08932 | val 0.13329
  Epoch 021 - train 0.09029 | val 0.13205
  Regression -> MSE: 0.000224, MAE: 0.011746, R²: -0.0033
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.10817 | val 0.11912
  Epoch 020 - train 0.10480 | val 0.11886

[I 2026-02-24 05:54:11,318] Trial 203 finished with value: -0.011457395960390254 and parameters: {'feature_set': 'unified_emotion', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 6.001268146002977e-06, 'weight_decay': 8.89590317235856e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.1449907831541587, 'early_stopping_min_delta': 0.0068209650665273045}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.09975 | val 0.13982
  Epoch 021 - train 0.09817 | val 0.13934
  Regression -> MSE: 0.000244, MAE: 0.012339, R²: -0.0288
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14378 | val 0.19148
  Epoch 020 - train 0.14074 | val 0.19108
  Epoch 021 - train 0.14060 | val 0.19065
  Regression -> MSE: 0.000255, MAE: 0.012829, R²: -0.0282
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13957 | val 0.13355
  Epoch 020 - train 0.13655 | val 0.13878
  Epoch 021 - train 0.13578 | val 0.13884
  Regression -> MSE: 0.000714, MAE: 0.019841, R²: -0.0423
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15626 | val 0.24407
  Epoch 020 - train 0.15162 | val 0.25233
  Epoch 021 - train 0.14992 | val 0.25189
  Regression -> MSE: 0.000321, MAE: 0.014546, R²: -0.0342
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.12155 | val 0.12695
  Epoch 020 - train 0.12016 | val 0.14350
  Epoch 021 - train 0.11797 | val 0.14356
  Regression -> MSE: 0.000353, MAE: 0.014634, R²: -0.0094
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.14177 | val 0.14568
  Epoch 020 - train 0.14038 | val 0.14338
  Epoch 021 - train 0.13916 | val 0.14301
  Regression -> MSE: 0.000206, MAE: 0.010401, R²: -0.0127
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13595 | val 0.26758
  Epoch 020 - train 0.13255 | val 0.26703
  Epoch 021 - train 0.13054 | val 0.26710
  Regression -> MSE: 0.000560, MAE: 0.018169, R²: -0.0090
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14986 | val 0.18860
  Epoch 020 - train 0.14818 | val 0.18577
  Epoch 021 - train 0.15034 | val 0.18544
  Regression -> MSE: 0.000254, MAE: 0.012696, R²: -0.0327
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13448 | val 0.20152
  Epoch 020 - train 0.13775 | val 0.21599
  Epoch 021 - train 0.13655 | val 0.21610
  Regression -> MSE: 0.000644, MAE: 0.020156, R²: -0.0785
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14639 | val 0.18126
  Epoch 020 - train 0.13913 | val 0.17438
  Epoch 030 - train 0.13883 | val 0.17239
  Regression -> MSE: 0.000432, MAE: 0.016552, R²: -0.1251
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.14709 | val 0.18522
  Epoch 020 - train 0.14311 | val 0.18606
  Epoch 021 - train 0.14173 | val 0.18566
  Regression -> MSE: 0.000246, MAE: 0.011638, R²: -0.0187
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12877 | val 0.21386
  Epoch 020 - train 0.12832 | val 0.21898
  Epoch 021 - train 0.12710 | val 0.21919
  Regression -> MSE: 0.000311, MAE: 0.013657, R²: -0.0009
  Directional -> Accuracy: 0.5600, MCC: 0.1548, F1: 0.0833

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14585 | val 0.19591
  Epoch 020 - train 0.14663 | val 0.21115
  Epoch 021 - train 0.14421 | val 0.21030
  Regression -> MSE: 0.000678, MAE: 0.019470, R²: -0.0012
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13953 | val 0.14813
  Epoch 020 - train 0.14039 | val 0.15409
  Epoch 021 - train 0.13857 | val 0.15408
  Regression -> MSE: 0.000138, MAE: 0.009106, R²: 0.0017
  Directional -> Accuracy: 0.4186, MCC: -0.1155, F1: 0.5614

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12829 | val 0.19204
  Epoch 020 - train 0.12444 | val 0.19465
  Epoch 021 - train 0.12628 | val 0.19463
  Regression -> MSE: 0.000225, MAE: 0.010695, R²: 0.0011
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.13559 | val 0.29259
  Epoch 020 - train 0.13503 | val 0.29440
  Epoch 021 - train 0.13313 | val 0.29458
  Regression -> MSE: 0.000369, MAE: 0.015944, R²: -0.0199
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14945 | val 0.15494
  Epoch 020 - train 0.14975 | val 0.15425
  Epoch 021 - train 0.14654 | val 0.15379
  Regression -> MSE: 0.000108, MAE: 0.008056, R²: -0.0050
  Directional -> Accuracy: 0.4429, MCC: -0.0890, F1: 0.0488

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14107 | val 0.23430
  Epoch 020 - train 0.13923 | val 0.25573
  Epoch 021 - train 0.13959 | val 0.25617
  Regression -> MSE: 0.000157, MAE: 0.009783, R²: -0.0051
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14622 | val 0.14668
  Epoch 020 - train 0.14260 | val 0.14749
  Epoch 021 - train 0.14481 | val 0.14693
  Regression -> MSE: 0.000292, MAE: 0.013923, R²: -0.0724
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12790 | val 0.19174
  Epoch 020 - train 0.12573 | val 0.19003
  Epoch 021 - train 0.12509 | val 0.19028
  Regression -> MSE: 0.000152, MAE: 0.008752, R²: -0.0149
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15000 | val 0.19831
  Epoch 020 - train 0.14331 | val 0.19446
  Epoch 030 - train 0.14339 | val 0.19398
  Regression -> MSE: 0.000437, MAE: 0.016289, R²: -0.9318
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.14296 | val 0.17683
  Epoch 020 - train 0.14192 | val 0.18003
  Epoch 021 - train 0.14091 | val 0.17987
  Regression -> MSE: 0.000146, MAE: 0.008487, R²: -0.0151
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.13276 | val 0.17432
  Epoch 020 - train 0.13162 | val 0.17712
  Epoch 021 - train 0.13442 | val 0.17633
  Regression -> MSE: 0.000166, MAE: 0.010654, R²: -0.0042
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14814 | val 0.16664
  Epoch 020 - train 0.14199 | val 0.17126
  Epoch 021 - train 0.14329 | val 0.17169
  Regression -> MSE: 0.000087, MAE: 0.007157, R²: -0.0227
  Directional -> Accuracy: 0.6034, MCC: 0.2171, F1: 0.7416

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14678 | val 0.19973
  Epoch 020 - train 0.14464 | val 0.21555
  Epoch 021 - train 0.14772 | val 0.21679
  Regression -> MSE: 0.000212, MAE: 0.011163, R²: 0.0004
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13995 | val 0.13541
  Epoch 020 - train 0.14130 | val 0.13609
  Epoch 021 - train 0.13796 | val 0.13595
  Regression -> MSE: 0.000092, MAE: 0.008104, R²: -0.0043
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16318 | val 0.11068
  Epoch 020 - train 0.16194 | val 0.12665
  Epoch 021 - train 0.16134 | val 0.12790
  Regression -> MSE: 0.000105, MAE: 0.008855, R²: -0.0195
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15021 | val 0.13682
  Epoch 020 - train 0.14912 | val 0.13400
  Epoch 030 - train 0.15104 | val 0.13385
  Regression -> MSE: 0.000230, MAE: 0.012596, R²: 0.0047
  Directional -> Accuracy: 0.5581, MCC: -0.1309, F1: 0.7164

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14365 | val 0.15785
  Epoch 020 - train 0.14325 | val 0.15727
  Epoch 029 - train 0.14197 | val 0.15770
  Regression -> MSE: 0.000285, MAE: 0.012134, R²: -0.7105
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.15225 | val 0.12121
  Epoch 020 - train 0.15287 | val 0.12586
  Epoch 021 - train 0.15022 | val 0.12772
  Regression -> MSE: 0.000237, MAE: 0.011863, R²: -0.0004
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13695 | val 0.22703
  Epoch 020 - train 0.13740 | val 0.22980
  Epoch 021 - train 0.13733 | val 0.23040
  Regression -> MSE: 0.000231, MAE: 0.009905, R²: -0.0021
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14750 | val 0.18017
  Epoch 020 - train 0.14952 | val 0.18583
  Epoch 021 - train 0.15002 | val 0.18540
  Regression -> MSE: 0.000139, MAE: 0.008343, R²: -0.0301
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14009 | val 0.18215
  Epoch 020 - train 0.14275 | val 0.18779
  Epoch 021 - train 0.13985 | val 0.18765
  Regression -> MSE: 0.000195, MAE: 0.010519, R²: -0.0348
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12472 | val 0.15719
  Epoch 020 - train 0.12266 | val 0.15832
  Epoch 021 - train 0.12437 | val 0.15782
  Regression -> MSE: 0.000273, MAE: 0.010735, R²: -0.0433
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13500 | val 0.12032
  Epoch 020 - train 0.13091 | val 0.12966
  Epoch 021 - train 0.12970 | val 0.13239
  Regression -> MSE: 0.000167, MAE: 0.010361, R²: -0.0005
  Directional -> Accuracy: 0.5526, MCC: 0.1066, F1: 0.5854

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12799 | val 0.15425
  Epoch 020 - train 0.12911 | val 0.17753
  Epoch 021 - train 0.12570 | val 0.17650
  Regression -> MSE: 0.000180, MAE: 0.010297, R²: -0.0006
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14077 | val 0.13633
  Epoch 020 - train 0.13872 | val 0.13537
  Epoch 021 - train 0.13537 | val 0.13541
  Regression -> MSE: 0.000348, MAE: 0.011751, R²: -0.0167
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.15523 | val 0.09445
  Epoch 020 - train 0.15665 | val 0.09841
  Epoch 021 - train 0.15376 | val 0.09809
  Regression -> MSE: 0.000113, MAE: 0.008329, R²: -0.0773
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.15055 | val 0.20407
  Epoch 020 - train 0.14735 | val 0.20512
  Epoch 021 - train 0.14602 | val 0.20276
  Regression -> MSE: 0.000223, MAE: 0.011396, R²: -0.0185
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14113 | val 0.24356
  Epoch 020 - train 0.14221 | val 0.24772
  Epoch 021 - train 0.13951 | val 0.24782
  Regression -> MSE: 0.000090, MAE: 0.007409, R²: -0.1534
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15080 | val 0.11040
  Epoch 020 - train 0.15424 | val 0.12230
  Epoch 021 - train 0.15135 | val 0.12351
  Regression -> MSE: 0.000312, MAE: 0.014054, R²: -0.0127
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.15061 | val 0.08951
  Epoch 020 - train 0.15068 | val 0.10278
  Epoch 021 - train 0.15108 | val 0.10465
  Regression -> MSE: 0.000246, MAE: 0.011571, R²: -0.0072
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13985 | val 0.18014
  Epoch 020 - train 0.13779 | val 0.17985
  Epoch 021 - train 0.13984 | val 0.17968
  Regression -> MSE: 0.000082, MAE: 0.007061, R²: -0.0176
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13962 | val 0.17183
  Epoch 020 - train 0.14167 | val 0.17217
  Epoch 021 - train 0.13967 | val 0.17255
  Regression -> MSE: 0.000313, MAE: 0.014539, R²: -0.0206
  Directional -> Accuracy: 0.4894, MCC: 0.0000, F1: 0.0000

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14101 | val 0.17055
  Epoch 020 - train 0.13369 | val 0.16662
  Epoch 021 - train 0.13562 | val 0.16626
  Regression -> MSE: 0.000102, MAE: 0.007107, R²: -0.0396
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15723 | val 0.17620
  Epoch 020 - train 0.16237 | val 0.19498
  Epoch 021 - train 0.15641 | val 0.19587
  Regression -> MSE: 0.000175, MAE: 0.010180, R²: -0.0190
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.13047 | val 0.18734
  Epoch 020 - train 0.13279 | val 0.19679
  Epoch 021 - train 0.13173 | val 0.19820
  Regression -> MSE: 0.000223, MAE: 0.011735, R²: 0.0010
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.14249 | val 0.16394
  Epoch 020 - train 0.13733 | val 0.16379
  Epoch 021 - train 0.14040 | val 0.16426

[I 2026-02-24 05:56:10,783] Trial 204 finished with value: -0.011656750621461067 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 7.033928089163744e-06, 'weight_decay': 1.135857031890316e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.21889998911023315, 'early_stopping_min_delta': 0.006563596991331904}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.14208 | val 0.21048
  Epoch 021 - train 0.14070 | val 0.21090
  Regression -> MSE: 0.000238, MAE: 0.012302, R²: -0.0019
  Directional -> Accuracy: 0.5574, MCC: 0.1049, F1: 0.3721

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.08962 | val 0.11982
  Epoch 020 - train 0.08943 | val 0.11974
  Epoch 021 - train 0.09042 | val 0.11962
  Regression -> MSE: 0.000252, MAE: 0.012739, R²: -0.0186
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09731 | val 0.09781
  Epoch 020 - train 0.09508 | val 0.13277
  Epoch 021 - train 0.09577 | val 0.13423
  Regression -> MSE: 0.000712, MAE: 0.019841, R²: -0.0397
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09500 | val 0.14576
  Epoch 020 - train 0.09380 | val 0.14421
  Epoch 021 - train 0.09417 | val 0.14417
  Regression -> MSE: 0.000311, MAE: 0.014460, R²: -0.0020
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07737 | val 0.11093
  Epoch 020 - train 0.07719 | val 0.11581
  Epoch 021 - train 0.07881 | val 0.11749
  Regression -> MSE: 0.000372, MAE: 0.014952, R²: -0.0656
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09572 | val 0.09731
  Epoch 020 - train 0.09384 | val 0.09644
  Epoch 021 - train 0.09504 | val 0.09699
  Regression -> MSE: 0.000207, MAE: 0.010499, R²: -0.0189
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.08896 | val 0.17683
  Epoch 020 - train 0.09047 | val 0.17446
  Epoch 021 - train 0.08971 | val 0.17397
  Regression -> MSE: 0.000619, MAE: 0.019463, R²: -0.1147
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09569 | val 0.11985
  Epoch 020 - train 0.09598 | val 0.11948
  Epoch 021 - train 0.09571 | val 0.11942
  Regression -> MSE: 0.000247, MAE: 0.012295, R²: -0.0079
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09244 | val 0.11014
  Epoch 020 - train 0.09444 | val 0.11779
  Epoch 021 - train 0.09198 | val 0.11877
  Regression -> MSE: 0.000607, MAE: 0.019392, R²: -0.0152
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09427 | val 0.11864
  Epoch 020 - train 0.09222 | val 0.12105
  Epoch 021 - train 0.09364 | val 0.12164
  Regression -> MSE: 0.000384, MAE: 0.016165, R²: -0.0022
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09368 | val 0.11588
  Epoch 020 - train 0.09377 | val 0.11650
  Epoch 021 - train 0.09379 | val 0.11650
  Regression -> MSE: 0.000242, MAE: 0.011983, R²: -0.0015
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08533 | val 0.12739
  Epoch 020 - train 0.08502 | val 0.12762
  Epoch 021 - train 0.08510 | val 0.12796
  Regression -> MSE: 0.000311, MAE: 0.013647, R²: -0.0005
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.09826 | val 0.10900
  Epoch 020 - train 0.09595 | val 0.11002
  Epoch 021 - train 0.09537 | val 0.11008
  Regression -> MSE: 0.000681, MAE: 0.019515, R²: -0.0060
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09552 | val 0.09608
  Epoch 020 - train 0.09139 | val 0.10762
  Epoch 021 - train 0.09126 | val 0.10673
  Regression -> MSE: 0.000145, MAE: 0.009501, R²: -0.0459
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08357 | val 0.11108
  Epoch 020 - train 0.08411 | val 0.11011
  Epoch 030 - train 0.08299 | val 0.11017
  Regression -> MSE: 0.000235, MAE: 0.010969, R²: -0.0462
  Directional -> Accuracy: 0.5410, MCC: 0.2237, F1: 0.1765

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.08915 | val 0.18523
  Epoch 020 - train 0.08878 | val 0.19428
  Epoch 021 - train 0.08759 | val 0.19469
  Regression -> MSE: 0.000370, MAE: 0.015939, R²: -0.0214
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09733 | val 0.10530
  Epoch 020 - train 0.09566 | val 0.10443
  Epoch 021 - train 0.09517 | val 0.10432
  Regression -> MSE: 0.000110, MAE: 0.007958, R²: -0.0218
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08766 | val 0.15377
  Epoch 020 - train 0.08853 | val 0.15887
  Epoch 021 - train 0.08783 | val 0.15900
  Regression -> MSE: 0.000157, MAE: 0.009826, R²: -0.0079
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09142 | val 0.10254
  Epoch 020 - train 0.09055 | val 0.10442
  Epoch 021 - train 0.08871 | val 0.10434
  Regression -> MSE: 0.000279, MAE: 0.013373, R²: -0.0239
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08505 | val 0.12297
  Epoch 020 - train 0.08354 | val 0.12340
  Epoch 021 - train 0.08527 | val 0.12341
  Regression -> MSE: 0.000163, MAE: 0.009015, R²: -0.0893
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09422 | val 0.13813
  Epoch 020 - train 0.09433 | val 0.13695
  Epoch 021 - train 0.09299 | val 0.13689
  Regression -> MSE: 0.000241, MAE: 0.011084, R²: -0.0636
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09349 | val 0.11604
  Epoch 020 - train 0.09065 | val 0.11863
  Epoch 021 - train 0.09114 | val 0.11902
  Regression -> MSE: 0.000152, MAE: 0.008770, R²: -0.0581
  Directional -> Accuracy: 0.3750, MCC: -0.1491, F1: 0.2857

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.08890 | val 0.10861
  Epoch 020 - train 0.08320 | val 0.10826
  Epoch 021 - train 0.08568 | val 0.10822
  Regression -> MSE: 0.000167, MAE: 0.010685, R²: -0.0086
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09417 | val 0.10651
  Epoch 020 - train 0.09281 | val 0.10610
  Epoch 021 - train 0.09359 | val 0.10606
  Regression -> MSE: 0.000085, MAE: 0.007073, R²: -0.0029
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09306 | val 0.11135
  Epoch 020 - train 0.09156 | val 0.11096
  Epoch 021 - train 0.09182 | val 0.11102
  Regression -> MSE: 0.000213, MAE: 0.011348, R²: -0.0076
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08818 | val 0.09090
  Epoch 020 - train 0.08649 | val 0.09254
  Epoch 021 - train 0.08705 | val 0.09273
  Regression -> MSE: 0.000094, MAE: 0.008089, R²: -0.0198
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09017 | val 0.07726
  Epoch 020 - train 0.09054 | val 0.07494
  Epoch 021 - train 0.09156 | val 0.07498
  Regression -> MSE: 0.000115, MAE: 0.009187, R²: -0.1199
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09496 | val 0.09773
  Epoch 020 - train 0.09249 | val 0.11971
  Epoch 021 - train 0.09265 | val 0.11905
  Regression -> MSE: 0.000233, MAE: 0.012608, R²: -0.0084
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.08953 | val 0.10664
  Epoch 020 - train 0.08902 | val 0.10665
  Epoch 021 - train 0.08899 | val 0.10664
  Regression -> MSE: 0.000184, MAE: 0.008030, R²: -0.1042
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09910 | val 0.07829
  Epoch 020 - train 0.09197 | val 0.08466
  Epoch 021 - train 0.09392 | val 0.08664
  Regression -> MSE: 0.000240, MAE: 0.011941, R²: -0.0129
  Directional -> Accuracy: 0.4634, MCC: 0.0000, F1: 0.0000

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10397 | val 0.15297
  Epoch 020 - train 0.10350 | val 0.16902
  Epoch 021 - train 0.10535 | val 0.16945
  Regression -> MSE: 0.000236, MAE: 0.010223, R²: -0.0225
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09477 | val 0.10844
  Epoch 020 - train 0.09540 | val 0.10982
  Epoch 021 - train 0.09586 | val 0.11010
  Regression -> MSE: 0.000135, MAE: 0.008203, R²: -0.0000
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09169 | val 0.11879
  Epoch 020 - train 0.09027 | val 0.12125
  Epoch 021 - train 0.09043 | val 0.12134
  Regression -> MSE: 0.000197, MAE: 0.010612, R²: -0.0471
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08205 | val 0.10327
  Epoch 020 - train 0.08122 | val 0.10116
  Epoch 021 - train 0.08152 | val 0.10109
  Regression -> MSE: 0.000276, MAE: 0.010820, R²: -0.0551
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.08597 | val 0.08101
  Epoch 020 - train 0.08703 | val 0.08807
  Epoch 021 - train 0.08780 | val 0.08916
  Regression -> MSE: 0.000167, MAE: 0.010372, R²: -0.0041
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08621 | val 0.09736
  Epoch 020 - train 0.08680 | val 0.10194
  Epoch 021 - train 0.08356 | val 0.10151
  Regression -> MSE: 0.000185, MAE: 0.010517, R²: -0.0301
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.08714 | val 0.08304
  Epoch 020 - train 0.08591 | val 0.08258
  Epoch 021 - train 0.08350 | val 0.08254
  Regression -> MSE: 0.000342, MAE: 0.011794, R²: 0.0015
  Directional -> Accuracy: 0.5821, MCC: 0.1137, F1: 0.6818

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.09810 | val 0.06149
  Epoch 020 - train 0.09987 | val 0.07100
  Epoch 021 - train 0.09731 | val 0.07143
  Regression -> MSE: 0.000124, MAE: 0.008447, R²: -0.1752
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09884 | val 0.13517
  Epoch 020 - train 0.10063 | val 0.13886
  Epoch 021 - train 0.09818 | val 0.13673
  Regression -> MSE: 0.000227, MAE: 0.011506, R²: -0.0367
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.08763 | val 0.15851
  Epoch 020 - train 0.08830 | val 0.16766
  Epoch 021 - train 0.08910 | val 0.16762
  Regression -> MSE: 0.000087, MAE: 0.007316, R²: -0.1253
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08985 | val 0.07007
  Epoch 020 - train 0.08903 | val 0.07140
  Epoch 021 - train 0.08844 | val 0.07179
  Regression -> MSE: 0.000310, MAE: 0.013944, R²: -0.0070
  Directional -> Accuracy: 0.6327, MCC: 0.1393, F1: 0.3571

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09686 | val 0.05656
  Epoch 020 - train 0.09657 | val 0.05638
  Epoch 021 - train 0.09775 | val 0.05655
  Regression -> MSE: 0.000246, MAE: 0.011547, R²: -0.0111
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08670 | val 0.11192
  Epoch 020 - train 0.08549 | val 0.11207
  Epoch 021 - train 0.08448 | val 0.11216
  Regression -> MSE: 0.000082, MAE: 0.007052, R²: -0.0162
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.09019 | val 0.11490
  Epoch 020 - train 0.09279 | val 0.12365
  Epoch 021 - train 0.08879 | val 0.12276
  Regression -> MSE: 0.000307, MAE: 0.014509, R²: -0.0011
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09448 | val 0.10915
  Epoch 020 - train 0.09135 | val 0.09882
  Epoch 030 - train 0.09114 | val 0.09581
  Regression -> MSE: 0.000104, MAE: 0.007359, R²: -0.0544
  Directional -> Accuracy: 0.5000, MCC: -0.1008, F1: 0.6333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.09696 | val 0.10763
  Epoch 020 - train 0.09873 | val 0.11027
  Epoch 021 - train 0.09930 | val 0.11034
  Regression -> MSE: 0.000172, MAE: 0.009823, R²: -0.0036
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08631 | val 0.10240
  Epoch 020 - train 0.08489 | val 0.10602
  Epoch 021 - train 0.08679 | val 0.10558
  Regression -> MSE: 0.000223, MAE: 0.011734, R²: 0.0015
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.08823 | val 0.10125
  Epoch 020 - train 0.08780 | val 0.10145
  Epoch 021 - train 0.08846 | val 0.10146

[I 2026-02-24 05:58:09,857] Trial 205 finished with value: -0.011507822418891455 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.0, 'batch_size': 32, 'learning_rate': 5.8344006250031506e-06, 'weight_decay': 1.2386609244609875e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.1333877839215977, 'early_stopping_min_delta': 0.006350654645870612}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.09352 | val 0.13851
  Epoch 021 - train 0.09279 | val 0.13782
  Regression -> MSE: 0.000239, MAE: 0.012298, R²: -0.0092
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with GRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.06807 | val 0.09576
  Epoch 011 - train 0.06791 | val 0.09671
  Regression -> MSE: 0.000248, MAE: 0.012524, R²: -0.0003
  Directional -> Accuracy: 0.5844, MCC: 0.1707, F1: 0.5676

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.06584 | val 0.06683
  Epoch 011 - train 0.06623 | val 0.06680
  Regression -> MSE: 0.000694, MAE: 0.019469, R²: -0.0131
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07413 | val 0.11234
  Epoch 011 - train 0.07365 | val 0.11228
  Regression -> MSE: 0.000311, MAE: 0.014378, R²: -0.0028
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.05855 | val 0.06148
  Epoch 011 - train 0.05960 | val 0.06198
  Regression -> MSE: 0.000352, MAE: 0.014680, R²: -0.0083
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07217 | val 0.07509
  Epoch 011 - train 0.07181 | val 0.07523
  Regression -> MSE: 0.000208, MAE: 0.010511, R²: -0.0190
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.06551 | val 0.12789
  Epoch 011 - train 0.06504 | val 0.12784
  Regression -> MSE: 0.000590, MAE: 0.018780, R²: -0.0634
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07170 | val 0.08882
  Epoch 011 - train 0.07112 | val 0.08892
  Regression -> MSE: 0.000244, MAE: 0.011868, R²: 0.0048
  Directional -> Accuracy: 0.5362, MCC: -0.0500, F1: 0.2381

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.06821 | val 0.10632
  Epoch 011 - train 0.06578 | val 0.10668
  Regression -> MSE: 0.000655, MAE: 0.020278, R²: -0.0965
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.06412 | val 0.08455
  Epoch 011 - train 0.06679 | val 0.08486
  Regression -> MSE: 0.000405, MAE: 0.016155, R²: -0.0557
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.06721 | val 0.08960
  Epoch 011 - train 0.06656 | val 0.08984
  Regression -> MSE: 0.000241, MAE: 0.011681, R²: 0.0033
  Directional -> Accuracy: 0.5143, MCC: 0.1277, F1: 0.5952

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06239 | val 0.10721
  Epoch 011 - train 0.06328 | val 0.10869
  Regression -> MSE: 0.000309, MAE: 0.013647, R²: 0.0065
  Directional -> Accuracy: 0.5200, MCC: 0.1191, F1: 0.6250

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07357 | val 0.08292
  Epoch 011 - train 0.07171 | val 0.08318
  Regression -> MSE: 0.000684, MAE: 0.019790, R²: -0.0106
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.06874 | val 0.07361
  Epoch 011 - train 0.06900 | val 0.07433
  Regression -> MSE: 0.000139, MAE: 0.009210, R²: -0.0077
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06321 | val 0.09424
  Epoch 011 - train 0.06325 | val 0.09399
  Regression -> MSE: 0.000227, MAE: 0.010794, R²: -0.0074
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.06884 | val 0.13955
  Epoch 011 - train 0.07083 | val 0.13993
  Regression -> MSE: 0.000364, MAE: 0.016211, R²: -0.0044
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07237 | val 0.07186
  Epoch 011 - train 0.07193 | val 0.07183
  Regression -> MSE: 0.000110, MAE: 0.007928, R²: -0.0207
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.06659 | val 0.12067
  Epoch 011 - train 0.06689 | val 0.12247
  Regression -> MSE: 0.000156, MAE: 0.009886, R²: -0.0028
  Directional -> Accuracy: 0.6271, MCC: 0.1466, F1: 0.7317

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07048 | val 0.07429
  Epoch 011 - train 0.07145 | val 0.07511
  Regression -> MSE: 0.000278, MAE: 0.013328, R²: -0.0219
  Directional -> Accuracy: 0.4342, MCC: 0.1637, F1: 0.1224

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06414 | val 0.09476
  Epoch 011 - train 0.06426 | val 0.09495
  Regression -> MSE: 0.000158, MAE: 0.008885, R²: -0.0572
  Directional -> Accuracy: 0.5385, MCC: 0.0807, F1: 0.5714

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07102 | val 0.10034
  Epoch 011 - train 0.07121 | val 0.10228
  Regression -> MSE: 0.000234, MAE: 0.010964, R²: -0.0363
  Directional -> Accuracy: 0.4667, MCC: -0.0816, F1: 0.5238

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07141 | val 0.08586
  Epoch 011 - train 0.07104 | val 0.08567
  Regression -> MSE: 0.000144, MAE: 0.008394, R²: -0.0024
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.06656 | val 0.07883
  Epoch 011 - train 0.06555 | val 0.07865
  Regression -> MSE: 0.000175, MAE: 0.010223, R²: -0.0596
  Directional -> Accuracy: 0.5303, MCC: 0.0845, F1: 0.2791

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.06996 | val 0.08226
  Epoch 011 - train 0.07049 | val 0.08255
  Regression -> MSE: 0.000089, MAE: 0.007262, R²: -0.0457
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.06771 | val 0.09373
  Epoch 011 - train 0.06707 | val 0.09766
  Regression -> MSE: 0.000210, MAE: 0.011102, R²: 0.0066
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06442 | val 0.06332
  Epoch 011 - train 0.06360 | val 0.06306
  Regression -> MSE: 0.000096, MAE: 0.008142, R²: -0.0457
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.06987 | val 0.05802
  Epoch 011 - train 0.06932 | val 0.05803
  Regression -> MSE: 0.000106, MAE: 0.008876, R²: -0.0282
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.06764 | val 0.06694
  Epoch 011 - train 0.07096 | val 0.06697
  Regression -> MSE: 0.000236, MAE: 0.012679, R²: -0.0177
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.06742 | val 0.08495
  Epoch 011 - train 0.06736 | val 0.08501
  Regression -> MSE: 0.000173, MAE: 0.007837, R²: -0.0412
  Directional -> Accuracy: 0.5088, MCC: -0.0154, F1: 0.5882

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07167 | val 0.06157
  Epoch 011 - train 0.07021 | val 0.06167
  Regression -> MSE: 0.000237, MAE: 0.011893, R²: -0.0034
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.06798 | val 0.11047
  Epoch 011 - train 0.06781 | val 0.11064
  Regression -> MSE: 0.000229, MAE: 0.009846, R²: 0.0085
  Directional -> Accuracy: 0.5116, MCC: 0.0397, F1: 0.6038

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07150 | val 0.08397
  Epoch 011 - train 0.06922 | val 0.08449
  Regression -> MSE: 0.000135, MAE: 0.008175, R²: 0.0003
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07081 | val 0.09009
  Epoch 011 - train 0.06967 | val 0.09051
  Regression -> MSE: 0.000192, MAE: 0.010399, R²: -0.0201
  Directional -> Accuracy: 0.4600, MCC: -0.0602, F1: 0.4000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06141 | val 0.07924
  Epoch 011 - train 0.06127 | val 0.07925
  Regression -> MSE: 0.000275, MAE: 0.010774, R²: -0.0513
  Directional -> Accuracy: 0.4521, MCC: 0.1041, F1: 0.0476

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.06441 | val 0.06100
  Epoch 011 - train 0.06500 | val 0.06090
  Regression -> MSE: 0.000166, MAE: 0.010347, R²: 0.0069
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06287 | val 0.07182
  Epoch 011 - train 0.06278 | val 0.07180
  Regression -> MSE: 0.000180, MAE: 0.010356, R²: -0.0010
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.07120 | val 0.06841
  Epoch 011 - train 0.06889 | val 0.06836
  Regression -> MSE: 0.000352, MAE: 0.011860, R²: -0.0277
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.07269 | val 0.04852
  Epoch 011 - train 0.07329 | val 0.04858
  Regression -> MSE: 0.000113, MAE: 0.008364, R²: -0.0773
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07018 | val 0.09445
  Epoch 011 - train 0.07066 | val 0.09480
  Regression -> MSE: 0.000222, MAE: 0.011329, R²: -0.0162
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07101 | val 0.11642
  Epoch 011 - train 0.06981 | val 0.11634
  Regression -> MSE: 0.000096, MAE: 0.007651, R²: -0.2378
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.06950 | val 0.06313
  Epoch 011 - train 0.06996 | val 0.06347
  Regression -> MSE: 0.000328, MAE: 0.014875, R²: -0.0672
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07224 | val 0.04545
  Epoch 011 - train 0.06865 | val 0.04565
  Regression -> MSE: 0.000252, MAE: 0.011490, R²: -0.0337
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.06788 | val 0.08561
  Epoch 011 - train 0.06782 | val 0.08562
  Regression -> MSE: 0.000085, MAE: 0.007049, R²: -0.0492
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07039 | val 0.08963
  Epoch 011 - train 0.07076 | val 0.08954
  Regression -> MSE: 0.000308, MAE: 0.014529, R²: -0.0031
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.06832 | val 0.07785
  Epoch 011 - train 0.06905 | val 0.07806
  Regression -> MSE: 0.000099, MAE: 0.007258, R²: -0.0058
  Directional -> Accuracy: 0.4773, MCC: -0.2127, F1: 0.6349

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.07360 | val 0.08218
  Epoch 011 - train 0.07084 | val 0.08228
  Regression -> MSE: 0.000173, MAE: 0.009475, R²: -0.0056
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.06462 | val 0.07967
  Epoch 011 - train 0.06344 | val 0.08053
  Regression -> MSE: 0.000225, MAE: 0.011728, R²: -0.0075
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.06742 | val 0.07977
  Epoch 011 - train 0.06846 | val 0.08049
  Regression -> MSE: 0.000092, MAE: 0.007646, R²: 0.0019
  Directional -> Accuracy: 0.4737, MCC: -0.0449, F1: 0.5000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.07458 | val 0.10744
  Epoch 011 - train 0.07430 | val 0.10759
  Regression -> MSE: 0.000164, MAE: 0.010248, R²: -0.0008
  Directional -> Accuracy: 0.5185, MCC: 0.0000, F1: 0.6829

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.06675 | val 0.09202
  Epoch 011 - train 0.06630 | val 0.09268
  Regression -> MSE: 0.000116, MAE: 0.008918, R²: 0.0000
  Directional -> Accuracy: 0.5179, MCC: 0.0000, F1: 0.6824

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 05:58:45,788] Trial 206 finished with value: -0.011440974180484762 and parameters: {'feature_set': 'emotion', 'model_type': 'GRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 64, 'learning_rate': 3.036592012573408e-05, 'weight_decay': 7.62403385427633e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.10067636962688989, 'early_stopping_min_delta': 0.006718848903314924}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 010 - train 0.07108 | val 0.10821
  Epoch 011 - train 0.06962 | val 0.11091
  Regression -> MSE: 0.000239, MAE: 0.012356, R²: -0.0081
  Directional -> Accuracy: 0.5410, MCC: 0.1356, F1: 0.0667

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11702 | val 0.15166
  Epoch 020 - train 0.11590 | val 0.15141
  Epoch 021 - train 0.11707 | val 0.15131
  Regression -> MSE: 0.000248, MAE: 0.012561, R²: -0.0030
  Directional -> Accuracy: 0.4675, MCC: -0.0120, F1: 0.5773

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11107 | val 0.10736
  Epoch 020 - train 0.10790 | val 0.11224
  Epoch 021 - train 0.10446 | val 0.11264
  Regression -> MSE: 0.000689, MAE: 0.019418, R²: -0.0062
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.11578 | val 0.18719
  Epoch 020 - train 0.11531 | val 0.18857
  Epoch 021 - train 0.11456 | val 0.18826
  Regression -> MSE: 0.000310, MAE: 0.014425, R²: -0.0001
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09253 | val 0.11335
  Epoch 020 - train 0.09155 | val 0.11060
  Epoch 021 - train 0.09308 | val 0.10955
  Regression -> MSE: 0.000365, MAE: 0.014844, R²: -0.0451
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11960 | val 0.11406
  Epoch 020 - train 0.11406 | val 0.11524
  Epoch 021 - train 0.11145 | val 0.11512
  Regression -> MSE: 0.000206, MAE: 0.010104, R²: -0.0125
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10996 | val 0.21968
  Epoch 020 - train 0.10700 | val 0.23311
  Epoch 021 - train 0.10683 | val 0.23328
  Regression -> MSE: 0.000564, MAE: 0.018230, R²: -0.0159
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11717 | val 0.14614
  Epoch 020 - train 0.11486 | val 0.14537
  Epoch 021 - train 0.11508 | val 0.14528
  Regression -> MSE: 0.000246, MAE: 0.012199, R²: -0.0022
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11647 | val 0.14023
  Epoch 020 - train 0.11826 | val 0.13988
  Epoch 021 - train 0.11140 | val 0.14079
  Regression -> MSE: 0.000611, MAE: 0.019498, R²: -0.0224
  Directional -> Accuracy: 0.5682, MCC: -0.1269, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11088 | val 0.14080
  Epoch 020 - train 0.11038 | val 0.14276
  Epoch 021 - train 0.11287 | val 0.14293
  Regression -> MSE: 0.000388, MAE: 0.015938, R²: -0.0103
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11902 | val 0.14608
  Epoch 020 - train 0.11515 | val 0.14617
  Epoch 021 - train 0.11599 | val 0.14609
  Regression -> MSE: 0.000242, MAE: 0.011946, R²: -0.0022
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10471 | val 0.16499
  Epoch 020 - train 0.10133 | val 0.16537
  Epoch 021 - train 0.10357 | val 0.16506
  Regression -> MSE: 0.000311, MAE: 0.013765, R²: -0.0015
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11783 | val 0.14439
  Epoch 020 - train 0.11511 | val 0.14616
  Epoch 021 - train 0.11611 | val 0.14597
  Regression -> MSE: 0.000681, MAE: 0.019500, R²: -0.0048
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11910 | val 0.11208
  Epoch 020 - train 0.11248 | val 0.11242
  Epoch 030 - train 0.10785 | val 0.11243
  Regression -> MSE: 0.000148, MAE: 0.009549, R²: -0.0699
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10923 | val 0.17708
  Epoch 020 - train 0.10770 | val 0.18180
  Epoch 021 - train 0.10831 | val 0.18131
  Regression -> MSE: 0.000225, MAE: 0.010787, R²: -0.0025
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10965 | val 0.24335
  Epoch 020 - train 0.10733 | val 0.26418
  Epoch 021 - train 0.10867 | val 0.26462
  Regression -> MSE: 0.000367, MAE: 0.015974, R²: -0.0135
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11897 | val 0.12165
  Epoch 020 - train 0.11667 | val 0.11975
  Epoch 021 - train 0.11371 | val 0.11862
  Regression -> MSE: 0.000109, MAE: 0.008150, R²: -0.0118
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11174 | val 0.19559
  Epoch 020 - train 0.11002 | val 0.20327
  Epoch 021 - train 0.10992 | val 0.20367
  Regression -> MSE: 0.000156, MAE: 0.009584, R²: -0.0014
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11334 | val 0.12025
  Epoch 020 - train 0.11215 | val 0.12238
  Epoch 021 - train 0.11317 | val 0.12282
  Regression -> MSE: 0.000272, MAE: 0.012997, R²: -0.0014
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10016 | val 0.15633
  Epoch 020 - train 0.09847 | val 0.15637
  Epoch 021 - train 0.09952 | val 0.15645
  Regression -> MSE: 0.000152, MAE: 0.008726, R²: -0.0189
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11468 | val 0.17097
  Epoch 020 - train 0.11208 | val 0.16885
  Epoch 021 - train 0.11375 | val 0.16853
  Regression -> MSE: 0.000238, MAE: 0.011067, R²: -0.0529
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11777 | val 0.14472
  Epoch 020 - train 0.11422 | val 0.14501
  Epoch 021 - train 0.11405 | val 0.14497
  Regression -> MSE: 0.000144, MAE: 0.008322, R²: -0.0011
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11743 | val 0.12936
  Epoch 020 - train 0.11322 | val 0.12852
  Epoch 021 - train 0.11317 | val 0.12844
  Regression -> MSE: 0.000181, MAE: 0.010326, R²: -0.0939
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11844 | val 0.13542
  Epoch 020 - train 0.11537 | val 0.13502
  Epoch 021 - train 0.11374 | val 0.13514
  Regression -> MSE: 0.000085, MAE: 0.007055, R²: -0.0023
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11137 | val 0.13975
  Epoch 020 - train 0.10772 | val 0.14249
  Epoch 021 - train 0.10724 | val 0.14190
  Regression -> MSE: 0.000211, MAE: 0.011077, R²: 0.0024
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11154 | val 0.10705
  Epoch 020 - train 0.10717 | val 0.10770
  Epoch 021 - train 0.10615 | val 0.10802
  Regression -> MSE: 0.000095, MAE: 0.008108, R²: -0.0286
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12040 | val 0.10391
  Epoch 020 - train 0.11851 | val 0.12626
  Epoch 021 - train 0.11693 | val 0.12758
  Regression -> MSE: 0.000119, MAE: 0.009303, R²: -0.1495
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12036 | val 0.11052
  Epoch 020 - train 0.12074 | val 0.11225
  Epoch 021 - train 0.11864 | val 0.11244
  Regression -> MSE: 0.000232, MAE: 0.012546, R²: -0.0007
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11050 | val 0.13781
  Epoch 020 - train 0.10982 | val 0.13950
  Epoch 021 - train 0.11063 | val 0.13938
  Regression -> MSE: 0.000183, MAE: 0.008034, R²: -0.0987
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11491 | val 0.09799
  Epoch 020 - train 0.12120 | val 0.10133
  Epoch 021 - train 0.11669 | val 0.10166
  Regression -> MSE: 0.000238, MAE: 0.011902, R²: -0.0053
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.11963 | val 0.18644
  Epoch 020 - train 0.11333 | val 0.20938
  Epoch 021 - train 0.11348 | val 0.21028
  Regression -> MSE: 0.000231, MAE: 0.009926, R²: -0.0038
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12200 | val 0.14069
  Epoch 020 - train 0.12232 | val 0.15000
  Epoch 021 - train 0.12002 | val 0.15009
  Regression -> MSE: 0.000137, MAE: 0.008291, R²: -0.0126
  Directional -> Accuracy: 0.3953, MCC: -0.2203, F1: 0.1333

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11502 | val 0.14540
  Epoch 020 - train 0.11378 | val 0.14467
  Epoch 021 - train 0.11375 | val 0.14467
  Regression -> MSE: 0.000189, MAE: 0.010390, R²: -0.0055
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10239 | val 0.14105
  Epoch 020 - train 0.10269 | val 0.13897
  Epoch 021 - train 0.10245 | val 0.13835
  Regression -> MSE: 0.000261, MAE: 0.010565, R²: 0.0025
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10469 | val 0.09701
  Epoch 020 - train 0.10123 | val 0.09628
  Epoch 021 - train 0.10238 | val 0.09638
  Regression -> MSE: 0.000167, MAE: 0.010372, R²: -0.0028
  Directional -> Accuracy: 0.4737, MCC: -0.0778, F1: 0.6154

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10577 | val 0.11270
  Epoch 020 - train 0.10566 | val 0.11134
  Epoch 021 - train 0.10327 | val 0.11132
  Regression -> MSE: 0.000182, MAE: 0.010350, R²: -0.0125
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11079 | val 0.11099
  Epoch 020 - train 0.10522 | val 0.11177
  Epoch 021 - train 0.10491 | val 0.11165
  Regression -> MSE: 0.000348, MAE: 0.012238, R²: -0.0146
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11863 | val 0.07494
  Epoch 020 - train 0.12066 | val 0.08372
  Epoch 021 - train 0.11819 | val 0.08435
  Regression -> MSE: 0.000119, MAE: 0.008377, R²: -0.1362
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11606 | val 0.16050
  Epoch 020 - train 0.11290 | val 0.16219
  Epoch 021 - train 0.11452 | val 0.16220
  Regression -> MSE: 0.000222, MAE: 0.011389, R²: -0.0143
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11184 | val 0.19814
  Epoch 020 - train 0.11401 | val 0.19917
  Epoch 021 - train 0.11152 | val 0.19920
  Regression -> MSE: 0.000083, MAE: 0.007110, R²: -0.0705
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11197 | val 0.09294
  Epoch 020 - train 0.11012 | val 0.09338
  Epoch 021 - train 0.11160 | val 0.09400
  Regression -> MSE: 0.000326, MAE: 0.014804, R²: -0.0590
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11912 | val 0.07090
  Epoch 020 - train 0.11955 | val 0.06498
  Epoch 030 - train 0.11300 | val 0.06275
  Regression -> MSE: 0.000254, MAE: 0.011345, R²: -0.0423
  Directional -> Accuracy: 0.5526, MCC: 0.1132, F1: 0.6909

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11057 | val 0.13726
  Epoch 020 - train 0.10608 | val 0.13726
  Epoch 021 - train 0.10591 | val 0.13716
  Regression -> MSE: 0.000081, MAE: 0.007066, R²: -0.0035
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11746 | val 0.13939
  Epoch 020 - train 0.11750 | val 0.17287
  Epoch 021 - train 0.11769 | val 0.17377
  Regression -> MSE: 0.000309, MAE: 0.014520, R²: -0.0073
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11060 | val 0.13326
  Epoch 020 - train 0.11036 | val 0.13665
  Epoch 021 - train 0.11137 | val 0.13679
  Regression -> MSE: 0.000099, MAE: 0.007140, R²: -0.0086
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11914 | val 0.13778
  Epoch 020 - train 0.12133 | val 0.14471
  Epoch 021 - train 0.11884 | val 0.14540
  Regression -> MSE: 0.000172, MAE: 0.009603, R²: -0.0024
  Directional -> Accuracy: 0.5714, MCC: -0.1642, F1: 0.0000

[84/88] Processing V...


[I 2026-02-24 06:00:52,266] Trial 207 finished with value: -0.011406183200018148 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 8.8862533189803e-06, 'weight_decay': 4.8142468193744734e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.17093386520868756, 'early_stopping_min_delta': 0.0071154553905431826}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.11525 | val 0.18701
  Epoch 021 - train 0.11327 | val 0.19003
  Regression -> MSE: 0.000240, MAE: 0.012333, R²: -0.0103
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15606 | val 0.22993
  Epoch 020 - train 0.15183 | val 0.22834
  Epoch 021 - train 0.15230 | val 0.22822
  Regression -> MSE: 0.000247, MAE: 0.012519, R²: 0.0034
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.15914 | val 0.16165
  Epoch 020 - train 0.15282 | val 0.16917
  Epoch 021 - train 0.15136 | val 0.16930
  Regression -> MSE: 0.000693, MAE: 0.019473, R²: -0.0119
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16439 | val 0.26235
  Epoch 020 - train 0.16033 | val 0.26369
  Epoch 021 - train 0.16028 | val 0.26362
  Regression -> MSE: 0.000317, MAE: 0.014409, R²: -0.0203
  Directional -> Accuracy: 0.5319, MCC: 0.0934, F1: 0.4500

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13090 | val 0.18619
  Epoch 020 - train 0.13030 | val 0.17254
  Epoch 021 - train 0.12762 | val 0.17164
  Regression -> MSE: 0.000359, MAE: 0.014710, R²: -0.0290
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15769 | val 0.15721
  Epoch 020 - train 0.15384 | val 0.15485
  Epoch 026 - train 0.15260 | val 0.15346
  Regression -> MSE: 0.000208, MAE: 0.010370, R²: -0.0238
  Directional -> Accuracy: 0.5098, MCC: 0.0698, F1: 0.3243

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15673 | val 0.31367
  Epoch 020 - train 0.15273 | val 0.31217
  Epoch 021 - train 0.15092 | val 0.31204
  Regression -> MSE: 0.000598, MAE: 0.018894, R²: -0.0764
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15861 | val 0.20748
  Epoch 020 - train 0.15686 | val 0.20491
  Epoch 021 - train 0.15622 | val 0.20473
  Regression -> MSE: 0.000249, MAE: 0.011944, R²: -0.0160
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15158 | val 0.20732
  Epoch 020 - train 0.15378 | val 0.21439
  Epoch 021 - train 0.15140 | val 0.21458
  Regression -> MSE: 0.000616, MAE: 0.019588, R²: -0.0305
  Directional -> Accuracy: 0.4318, MCC: 0.1269, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.16155 | val 0.19180
  Epoch 020 - train 0.15781 | val 0.19461
  Epoch 021 - train 0.15664 | val 0.19455
  Regression -> MSE: 0.000405, MAE: 0.016117, R²: -0.0556
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15845 | val 0.20175
  Epoch 020 - train 0.15509 | val 0.20487
  Epoch 021 - train 0.15516 | val 0.20505
  Regression -> MSE: 0.000241, MAE: 0.011713, R²: 0.0008
  Directional -> Accuracy: 0.4714, MCC: -0.0254, F1: 0.4932

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15225 | val 0.23560
  Epoch 020 - train 0.14615 | val 0.23751
  Epoch 021 - train 0.14599 | val 0.23760
  Regression -> MSE: 0.000319, MAE: 0.013568, R²: -0.0269
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15940 | val 0.19498
  Epoch 020 - train 0.15627 | val 0.19568
  Epoch 021 - train 0.15933 | val 0.19572
  Regression -> MSE: 0.000674, MAE: 0.019425, R²: 0.0042
  Directional -> Accuracy: 0.5345, MCC: 0.0913, F1: 0.3077

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16353 | val 0.18822
  Epoch 020 - train 0.16169 | val 0.18859
  Epoch 021 - train 0.16184 | val 0.18816
  Regression -> MSE: 0.000151, MAE: 0.009786, R²: -0.0954
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.15174 | val 0.21675
  Epoch 020 - train 0.14447 | val 0.21428
  Epoch 030 - train 0.14168 | val 0.21178
  Regression -> MSE: 0.000245, MAE: 0.011552, R²: -0.0874
  Directional -> Accuracy: 0.4426, MCC: -0.1699, F1: 0.5854

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.16243 | val 0.32763
  Epoch 020 - train 0.15828 | val 0.32891
  Epoch 021 - train 0.15963 | val 0.32894
  Regression -> MSE: 0.000366, MAE: 0.016022, R²: -0.0104
  Directional -> Accuracy: 0.5192, MCC: 0.0416, F1: 0.5098

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.17352 | val 0.16526
  Epoch 020 - train 0.16809 | val 0.16461
  Epoch 021 - train 0.16909 | val 0.16459
  Regression -> MSE: 0.000112, MAE: 0.008008, R²: -0.0426
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.15500 | val 0.27012
  Epoch 020 - train 0.15190 | val 0.27017
  Epoch 021 - train 0.15338 | val 0.27021
  Regression -> MSE: 0.000157, MAE: 0.009602, R²: -0.0099
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15900 | val 0.17328
  Epoch 020 - train 0.15830 | val 0.17102
  Epoch 021 - train 0.15675 | val 0.17089
  Regression -> MSE: 0.000272, MAE: 0.013003, R²: -0.0003
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14644 | val 0.21717
  Epoch 020 - train 0.14188 | val 0.21606
  Epoch 021 - train 0.14207 | val 0.21599
  Regression -> MSE: 0.000155, MAE: 0.008833, R²: -0.0360
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.16100 | val 0.22878
  Epoch 020 - train 0.15698 | val 0.22400
  Epoch 021 - train 0.15669 | val 0.22385
  Regression -> MSE: 0.000230, MAE: 0.010861, R²: -0.0161
  Directional -> Accuracy: 0.5733, MCC: 0.1136, F1: 0.6863

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15924 | val 0.24526
  Epoch 020 - train 0.15882 | val 0.24878
  Epoch 021 - train 0.15711 | val 0.24874
  Regression -> MSE: 0.000151, MAE: 0.008702, R²: -0.0536
  Directional -> Accuracy: 0.5208, MCC: 0.2176, F1: 0.4390

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14808 | val 0.18184
  Epoch 020 - train 0.14680 | val 0.18046
  Epoch 026 - train 0.14375 | val 0.18006
  Regression -> MSE: 0.000177, MAE: 0.010988, R²: -0.0704
  Directional -> Accuracy: 0.4848, MCC: -0.1240, F1: 0.6531

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16765 | val 0.21946
  Epoch 020 - train 0.16682 | val 0.21487
  Epoch 021 - train 0.16635 | val 0.21443
  Regression -> MSE: 0.000090, MAE: 0.007237, R²: -0.0505
  Directional -> Accuracy: 0.5000, MCC: 0.0455, F1: 0.4528

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15917 | val 0.19463
  Epoch 020 - train 0.15427 | val 0.19669
  Epoch 021 - train 0.15233 | val 0.19682
  Regression -> MSE: 0.000212, MAE: 0.011279, R²: 0.0012
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14952 | val 0.16775
  Epoch 020 - train 0.14812 | val 0.16756
  Epoch 021 - train 0.14783 | val 0.16750
  Regression -> MSE: 0.000096, MAE: 0.008196, R²: -0.0402
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.15873 | val 0.13584
  Epoch 020 - train 0.15693 | val 0.13609
  Epoch 021 - train 0.15740 | val 0.13601
  Regression -> MSE: 0.000120, MAE: 0.009379, R²: -0.1672
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15428 | val 0.16877
  Epoch 020 - train 0.15473 | val 0.17134
  Epoch 021 - train 0.15333 | val 0.17136
  Regression -> MSE: 0.000239, MAE: 0.012818, R²: -0.0311
  Directional -> Accuracy: 0.4419, MCC: 0.1309, F1: 0.0769

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14918 | val 0.20597
  Epoch 020 - train 0.14923 | val 0.20565
  Epoch 021 - train 0.14814 | val 0.20559
  Regression -> MSE: 0.000181, MAE: 0.008025, R²: -0.0888
  Directional -> Accuracy: 0.4386, MCC: -0.0841, F1: 0.3600

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.15959 | val 0.15091
  Epoch 020 - train 0.15878 | val 0.15413
  Epoch 021 - train 0.15627 | val 0.15410
  Regression -> MSE: 0.000241, MAE: 0.012029, R²: -0.0185
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.15959 | val 0.25817
  Epoch 020 - train 0.15832 | val 0.26647
  Epoch 021 - train 0.15743 | val 0.26659
  Regression -> MSE: 0.000231, MAE: 0.009883, R²: -0.0037
  Directional -> Accuracy: 0.5116, MCC: 0.0318, F1: 0.5714

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16185 | val 0.18229
  Epoch 020 - train 0.16265 | val 0.18163
  Epoch 029 - train 0.15799 | val 0.18232
  Regression -> MSE: 0.000143, MAE: 0.008229, R²: -0.0558
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.16528 | val 0.20496
  Epoch 020 - train 0.16157 | val 0.20511
  Epoch 021 - train 0.15815 | val 0.20510
  Regression -> MSE: 0.000191, MAE: 0.010494, R²: -0.0143
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13725 | val 0.17496
  Epoch 020 - train 0.13361 | val 0.17479
  Epoch 021 - train 0.13453 | val 0.17478
  Regression -> MSE: 0.000272, MAE: 0.010773, R²: -0.0388
  Directional -> Accuracy: 0.4384, MCC: -0.0605, F1: 0.2545

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14858 | val 0.13368
  Epoch 020 - train 0.14525 | val 0.13873
  Epoch 029 - train 0.14229 | val 0.14180
  Regression -> MSE: 0.000164, MAE: 0.010414, R²: 0.0184
  Directional -> Accuracy: 0.4474, MCC: -0.1443, F1: 0.5882

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14222 | val 0.19133
  Epoch 020 - train 0.14023 | val 0.19549
  Epoch 021 - train 0.14225 | val 0.19549
  Regression -> MSE: 0.000179, MAE: 0.010272, R²: 0.0055
  Directional -> Accuracy: 0.4773, MCC: -0.0547, F1: 0.4103

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15099 | val 0.15685
  Epoch 020 - train 0.14795 | val 0.15749
  Epoch 021 - train 0.14963 | val 0.15753
  Regression -> MSE: 0.000355, MAE: 0.012690, R²: -0.0362
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16713 | val 0.10223
  Epoch 020 - train 0.16609 | val 0.10199
  Epoch 021 - train 0.16405 | val 0.10198
  Regression -> MSE: 0.000122, MAE: 0.008379, R²: -0.1596
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16152 | val 0.23706
  Epoch 020 - train 0.15870 | val 0.23913
  Epoch 021 - train 0.15816 | val 0.23914
  Regression -> MSE: 0.000220, MAE: 0.011265, R²: -0.0072
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15142 | val 0.28392
  Epoch 020 - train 0.14817 | val 0.28609
  Epoch 021 - train 0.15092 | val 0.28623
  Regression -> MSE: 0.000089, MAE: 0.007362, R²: -0.1438
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15655 | val 0.13628
  Epoch 020 - train 0.15414 | val 0.13980
  Epoch 021 - train 0.15191 | val 0.13986
  Regression -> MSE: 0.000333, MAE: 0.015067, R²: -0.0835
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.16936 | val 0.09799
  Epoch 020 - train 0.16911 | val 0.10238
  Epoch 021 - train 0.16812 | val 0.10262
  Regression -> MSE: 0.000247, MAE: 0.011566, R²: -0.0120
  Directional -> Accuracy: 0.3947, MCC: -0.2153, F1: 0.2069

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15279 | val 0.20004
  Epoch 020 - train 0.15076 | val 0.20020
  Epoch 021 - train 0.14955 | val 0.20022
  Regression -> MSE: 0.000080, MAE: 0.007061, R²: 0.0040
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.15817 | val 0.24162
  Epoch 020 - train 0.15598 | val 0.25266
  Epoch 021 - train 0.15515 | val 0.25236
  Regression -> MSE: 0.000307, MAE: 0.014444, R²: -0.0014
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16951 | val 0.22155
  Epoch 020 - train 0.16818 | val 0.24246
  Epoch 021 - train 0.16524 | val 0.24270
  Regression -> MSE: 0.000105, MAE: 0.007159, R²: -0.0649
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.17508 | val 0.19447
  Epoch 020 - train 0.17450 | val 0.19865
  Epoch 021 - train 0.17145 | val 0.19871
  Regression -> MSE: 0.000174, MAE: 0.009389, R²: -0.0130
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...


[I 2026-02-24 06:01:56,810] Trial 208 finished with value: -0.011498560058447602 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 1, 'inter_rnn_drop': 0.30000000000000004, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 1.160087653733563e-05, 'weight_decay': 6.247584130945477e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2493290915165536, 'early_stopping_min_delta': 0.007123928163949391}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.14857 | val 0.22450
  Epoch 021 - train 0.14895 | val 0.22452
  Regression -> MSE: 0.000244, MAE: 0.012340, R²: -0.0304
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11490 | val 0.16026
  Epoch 020 - train 0.11491 | val 0.15949
  Epoch 021 - train 0.11696 | val 0.15986
  Regression -> MSE: 0.000255, MAE: 0.012834, R²: -0.0290
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11562 | val 0.11209
  Epoch 020 - train 0.11093 | val 0.11601
  Epoch 021 - train 0.11315 | val 0.11593
  Regression -> MSE: 0.000716, MAE: 0.019894, R²: -0.0465
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12339 | val 0.19406
  Epoch 020 - train 0.11780 | val 0.19734
  Epoch 021 - train 0.11863 | val 0.19767
  Regression -> MSE: 0.000311, MAE: 0.014407, R²: -0.0019
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10032 | val 0.11408
  Epoch 020 - train 0.09850 | val 0.11984
  Epoch 021 - train 0.09585 | val 0.11888
  Regression -> MSE: 0.000351, MAE: 0.014574, R²: -0.0045
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12267 | val 0.12276
  Epoch 020 - train 0.12144 | val 0.12419
  Epoch 021 - train 0.12089 | val 0.12407
  Regression -> MSE: 0.000209, MAE: 0.010182, R²: -0.0259
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.10995 | val 0.22526
  Epoch 020 - train 0.10932 | val 0.22621
  Epoch 021 - train 0.10824 | val 0.22628
  Regression -> MSE: 0.000595, MAE: 0.018878, R²: -0.0727
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12092 | val 0.14712
  Epoch 020 - train 0.12012 | val 0.14621
  Epoch 021 - train 0.12163 | val 0.14617
  Regression -> MSE: 0.000248, MAE: 0.012232, R²: -0.0086
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13487 | val 0.14758
  Epoch 020 - train 0.13673 | val 0.13247
  Epoch 030 - train 0.12877 | val 0.13018
  Regression -> MSE: 0.000587, MAE: 0.018929, R²: 0.0170
  Directional -> Accuracy: 0.6591, MCC: 0.3251, F1: 0.2857

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11629 | val 0.14355
  Epoch 020 - train 0.11156 | val 0.15505
  Epoch 021 - train 0.11254 | val 0.15562
  Regression -> MSE: 0.000406, MAE: 0.016162, R²: -0.0574
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11618 | val 0.15142
  Epoch 020 - train 0.11546 | val 0.15261
  Epoch 021 - train 0.11658 | val 0.15256
  Regression -> MSE: 0.000241, MAE: 0.011870, R²: 0.0005
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11873 | val 0.16391
  Epoch 020 - train 0.11510 | val 0.16296
  Epoch 021 - train 0.11688 | val 0.16344
  Regression -> MSE: 0.000324, MAE: 0.013604, R²: -0.0429
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11824 | val 0.14641
  Epoch 020 - train 0.11664 | val 0.15186
  Epoch 021 - train 0.11920 | val 0.15220
  Regression -> MSE: 0.000679, MAE: 0.019576, R²: -0.0019
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13126 | val 0.13259
  Epoch 020 - train 0.12567 | val 0.13976
  Epoch 021 - train 0.12462 | val 0.13982
  Regression -> MSE: 0.000141, MAE: 0.009001, R²: -0.0194
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10990 | val 0.15113
  Epoch 020 - train 0.10635 | val 0.15446
  Epoch 021 - train 0.10990 | val 0.15470
  Regression -> MSE: 0.000229, MAE: 0.010841, R²: -0.0198
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11519 | val 0.25158
  Epoch 020 - train 0.11297 | val 0.25722
  Epoch 021 - train 0.11277 | val 0.25648
  Regression -> MSE: 0.000373, MAE: 0.015941, R²: -0.0294
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12265 | val 0.11824
  Epoch 020 - train 0.12188 | val 0.11851
  Epoch 021 - train 0.12191 | val 0.11821
  Regression -> MSE: 0.000111, MAE: 0.007965, R²: -0.0326
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11424 | val 0.19023
  Epoch 020 - train 0.11284 | val 0.19220
  Epoch 021 - train 0.11292 | val 0.19227
  Regression -> MSE: 0.000156, MAE: 0.009613, R²: -0.0030
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.11965 | val 0.13048
  Epoch 020 - train 0.11709 | val 0.13096
  Epoch 021 - train 0.11825 | val 0.13119
  Regression -> MSE: 0.000296, MAE: 0.014046, R²: -0.0880
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10773 | val 0.16391
  Epoch 020 - train 0.10506 | val 0.16428
  Epoch 021 - train 0.10385 | val 0.16419
  Regression -> MSE: 0.000168, MAE: 0.009173, R²: -0.1246
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.11509 | val 0.17191
  Epoch 020 - train 0.11459 | val 0.17124
  Epoch 021 - train 0.11481 | val 0.17111
  Regression -> MSE: 0.000231, MAE: 0.010954, R²: -0.0211
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12069 | val 0.14715
  Epoch 020 - train 0.11957 | val 0.14673
  Epoch 021 - train 0.11936 | val 0.14666
  Regression -> MSE: 0.000144, MAE: 0.008419, R²: -0.0080
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11125 | val 0.14053
  Epoch 020 - train 0.10892 | val 0.14171
  Epoch 021 - train 0.10996 | val 0.14164
  Regression -> MSE: 0.000176, MAE: 0.010274, R²: -0.0674
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12285 | val 0.14860
  Epoch 020 - train 0.12057 | val 0.15059
  Epoch 021 - train 0.11770 | val 0.15016
  Regression -> MSE: 0.000086, MAE: 0.007055, R²: -0.0038
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11523 | val 0.16043
  Epoch 020 - train 0.11255 | val 0.15902
  Epoch 021 - train 0.11358 | val 0.15923
  Regression -> MSE: 0.000213, MAE: 0.011078, R²: -0.0059
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11302 | val 0.10865
  Epoch 020 - train 0.10903 | val 0.10929
  Epoch 021 - train 0.10704 | val 0.10902
  Regression -> MSE: 0.000098, MAE: 0.008166, R²: -0.0687
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11623 | val 0.09503
  Epoch 020 - train 0.11845 | val 0.09808
  Epoch 030 - train 0.11677 | val 0.10209
  Regression -> MSE: 0.000102, MAE: 0.008659, R²: 0.0125
  Directional -> Accuracy: 0.5000, MCC: -0.0488, F1: 0.3429

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12137 | val 0.11580
  Epoch 020 - train 0.12141 | val 0.11778
  Epoch 021 - train 0.12057 | val 0.11784
  Regression -> MSE: 0.000236, MAE: 0.012711, R²: -0.0184
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12390 | val 0.14239
  Epoch 020 - train 0.11891 | val 0.14319
  Epoch 021 - train 0.11843 | val 0.14331
  Regression -> MSE: 0.000192, MAE: 0.008270, R²: -0.1553
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12380 | val 0.10345
  Epoch 020 - train 0.12102 | val 0.11674
  Epoch 021 - train 0.12467 | val 0.11764
  Regression -> MSE: 0.000239, MAE: 0.011927, R²: -0.0091
  Directional -> Accuracy: 0.4878, MCC: 0.0733, F1: 0.1600

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12157 | val 0.18660
  Epoch 020 - train 0.12072 | val 0.19755
  Epoch 021 - train 0.12022 | val 0.19810
  Regression -> MSE: 0.000231, MAE: 0.009875, R²: -0.0003
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12278 | val 0.15595
  Epoch 020 - train 0.12506 | val 0.16107
  Epoch 021 - train 0.12207 | val 0.16062
  Regression -> MSE: 0.000143, MAE: 0.008629, R²: -0.0597
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12153 | val 0.14878
  Epoch 020 - train 0.11817 | val 0.14808
  Epoch 021 - train 0.11861 | val 0.14816
  Regression -> MSE: 0.000190, MAE: 0.010389, R²: -0.0110
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10570 | val 0.15465
  Epoch 020 - train 0.10487 | val 0.15124
  Epoch 021 - train 0.10420 | val 0.15283
  Regression -> MSE: 0.000270, MAE: 0.010621, R²: -0.0322
  Directional -> Accuracy: 0.4795, MCC: -0.0894, F1: 0.5778

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.11425 | val 0.10080
  Epoch 020 - train 0.11311 | val 0.10200
  Epoch 021 - train 0.10890 | val 0.10218
  Regression -> MSE: 0.000168, MAE: 0.010382, R²: -0.0072
  Directional -> Accuracy: 0.4474, MCC: -0.1291, F1: 0.2222

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10626 | val 0.13748
  Epoch 020 - train 0.10524 | val 0.16863
  Epoch 021 - train 0.10326 | val 0.16909
  Regression -> MSE: 0.000180, MAE: 0.010333, R²: 0.0003
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10965 | val 0.11524
  Epoch 020 - train 0.10995 | val 0.11525
  Epoch 021 - train 0.10833 | val 0.11526
  Regression -> MSE: 0.000344, MAE: 0.011940, R²: -0.0030
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12523 | val 0.08146
  Epoch 020 - train 0.12429 | val 0.08362
  Epoch 021 - train 0.12201 | val 0.08364
  Regression -> MSE: 0.000110, MAE: 0.008318, R²: -0.0508
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11725 | val 0.16652
  Epoch 020 - train 0.11453 | val 0.17277
  Epoch 021 - train 0.11225 | val 0.17224
  Regression -> MSE: 0.000219, MAE: 0.011300, R²: -0.0022
  Directional -> Accuracy: 0.5614, MCC: 0.1326, F1: 0.2424

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11654 | val 0.20325
  Epoch 020 - train 0.11444 | val 0.21848
  Epoch 021 - train 0.11531 | val 0.21874
  Regression -> MSE: 0.000095, MAE: 0.007596, R²: -0.2167
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11413 | val 0.09005
  Epoch 020 - train 0.11489 | val 0.09499
  Epoch 021 - train 0.11345 | val 0.09556
  Regression -> MSE: 0.000309, MAE: 0.013876, R²: -0.0054
  Directional -> Accuracy: 0.6327, MCC: 0.0000, F1: 0.0000

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12614 | val 0.07208
  Epoch 020 - train 0.12546 | val 0.06968
  Epoch 021 - train 0.12775 | val 0.06948
  Regression -> MSE: 0.000251, MAE: 0.011486, R²: -0.0310
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11712 | val 0.14722
  Epoch 020 - train 0.11643 | val 0.14712
  Epoch 021 - train 0.11572 | val 0.14725
  Regression -> MSE: 0.000085, MAE: 0.007058, R²: -0.0522
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11606 | val 0.14806
  Epoch 020 - train 0.11807 | val 0.14461
  Epoch 021 - train 0.11978 | val 0.14400
  Regression -> MSE: 0.000307, MAE: 0.014475, R²: 0.0008
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11191 | val 0.12822
  Epoch 020 - train 0.11060 | val 0.14110
  Epoch 021 - train 0.11012 | val 0.14112
  Regression -> MSE: 0.000098, MAE: 0.007375, R²: -0.0003
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13161 | val 0.13880
  Epoch 020 - train 0.12838 | val 0.13978
  Epoch 021 - train 0.12523 | val 0.13986
  Regression -> MSE: 0.000173, MAE: 0.009883, R²: -0.0055
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 06:04:06,100] Trial 209 finished with value: -0.011436762677013303 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 8.013589049307518e-06, 'weight_decay': 6.01823745236962e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.17720749989706758, 'early_stopping_min_delta': 0.0073898035407562734}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.12299 | val 0.19318
  Epoch 021 - train 0.12290 | val 0.19259
  Regression -> MSE: 0.000244, MAE: 0.012350, R²: -0.0269
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13666 | val 0.20504
  Epoch 020 - train 0.13091 | val 0.20504
  Epoch 021 - train 0.13213 | val 0.20458
  Regression -> MSE: 0.000247, MAE: 0.012524, R²: 0.0017
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13106 | val 0.18397
  Epoch 020 - train 0.12706 | val 0.19200
  Epoch 021 - train 0.12789 | val 0.19407
  Regression -> MSE: 0.000686, MAE: 0.019365, R²: -0.0014
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.15354 | val 0.28093
  Epoch 020 - train 0.14414 | val 0.27486
  Epoch 021 - train 0.14646 | val 0.27388
  Regression -> MSE: 0.000324, MAE: 0.014540, R²: -0.0446
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11673 | val 0.12668
  Epoch 020 - train 0.11275 | val 0.12795
  Epoch 021 - train 0.11229 | val 0.12874
  Regression -> MSE: 0.000353, MAE: 0.014630, R²: -0.0096
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13886 | val 0.14682
  Epoch 020 - train 0.13346 | val 0.14821
  Epoch 021 - train 0.13285 | val 0.14851
  Regression -> MSE: 0.000208, MAE: 0.010103, R²: -0.0211
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.13620 | val 0.26624
  Epoch 020 - train 0.12659 | val 0.26959
  Epoch 021 - train 0.12795 | val 0.26923
  Regression -> MSE: 0.000555, MAE: 0.018126, R²: 0.0003
  Directional -> Accuracy: 0.4681, MCC: -0.0764, F1: 0.6154

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.14724 | val 0.29677
  Epoch 020 - train 0.14579 | val 0.29241
  Epoch 021 - train 0.14721 | val 0.29090
  Regression -> MSE: 0.000248, MAE: 0.011930, R²: -0.0122
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13890 | val 0.15994
  Epoch 020 - train 0.12792 | val 0.15977
  Epoch 030 - train 0.13068 | val 0.16041
  Regression -> MSE: 0.000612, MAE: 0.019397, R²: -0.0241
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13334 | val 0.16444
  Epoch 020 - train 0.12155 | val 0.16593
  Epoch 028 - train 0.12363 | val 0.16661
  Regression -> MSE: 0.000445, MAE: 0.016716, R²: -0.1610
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13310 | val 0.27235
  Epoch 020 - train 0.13149 | val 0.28171
  Epoch 021 - train 0.13097 | val 0.28013
  Regression -> MSE: 0.000242, MAE: 0.012052, R²: -0.0019
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12370 | val 0.20245
  Epoch 020 - train 0.12201 | val 0.21061
  Epoch 021 - train 0.12215 | val 0.21039
  Regression -> MSE: 0.000319, MAE: 0.013592, R²: -0.0263
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14550 | val 0.18954
  Epoch 020 - train 0.14159 | val 0.19004
  Epoch 021 - train 0.13829 | val 0.19037
  Regression -> MSE: 0.000690, MAE: 0.019850, R²: -0.0185
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13568 | val 0.14548
  Epoch 020 - train 0.13258 | val 0.14482
  Epoch 021 - train 0.13252 | val 0.14446
  Regression -> MSE: 0.000138, MAE: 0.009145, R²: -0.0002
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12211 | val 0.18898
  Epoch 020 - train 0.11809 | val 0.19232
  Epoch 028 - train 0.11916 | val 0.19316
  Regression -> MSE: 0.000242, MAE: 0.011232, R²: -0.0739
  Directional -> Accuracy: 0.4918, MCC: -0.0197, F1: 0.5373

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.14010 | val 0.30752
  Epoch 020 - train 0.13496 | val 0.30688
  Epoch 021 - train 0.13350 | val 0.31038
  Regression -> MSE: 0.000363, MAE: 0.016158, R²: -0.0028
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.14017 | val 0.13609
  Epoch 020 - train 0.13504 | val 0.13730
  Epoch 021 - train 0.13289 | val 0.14105
  Regression -> MSE: 0.000108, MAE: 0.007984, R²: -0.0048
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13079 | val 0.23318
  Epoch 020 - train 0.12876 | val 0.23982
  Epoch 021 - train 0.12806 | val 0.23948
  Regression -> MSE: 0.000160, MAE: 0.010041, R²: -0.0237
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15010 | val 0.19485
  Epoch 020 - train 0.14548 | val 0.18662
  Epoch 021 - train 0.14568 | val 0.18873
  Regression -> MSE: 0.000308, MAE: 0.014403, R²: -0.1306
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12664 | val 0.19711
  Epoch 020 - train 0.12500 | val 0.19607
  Epoch 021 - train 0.12324 | val 0.19610
  Regression -> MSE: 0.000161, MAE: 0.008937, R²: -0.0788
  Directional -> Accuracy: 0.4308, MCC: -0.1659, F1: 0.5067

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13799 | val 0.20154
  Epoch 020 - train 0.13740 | val 0.19889
  Epoch 021 - train 0.13657 | val 0.19885
  Regression -> MSE: 0.000263, MAE: 0.011640, R²: -0.1640
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13791 | val 0.19900
  Epoch 020 - train 0.13131 | val 0.19806
  Epoch 021 - train 0.13288 | val 0.19757
  Regression -> MSE: 0.000145, MAE: 0.008455, R²: -0.0121
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12906 | val 0.19194
  Epoch 020 - train 0.12802 | val 0.19068
  Epoch 021 - train 0.12541 | val 0.19152
  Regression -> MSE: 0.000178, MAE: 0.010274, R²: -0.0749
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.14024 | val 0.16284
  Epoch 020 - train 0.13837 | val 0.16430
  Epoch 021 - train 0.14098 | val 0.16434
  Regression -> MSE: 0.000090, MAE: 0.007319, R²: -0.0583
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.13529 | val 0.23267
  Epoch 020 - train 0.13315 | val 0.21408
  Epoch 021 - train 0.13039 | val 0.21162
  Regression -> MSE: 0.000212, MAE: 0.011103, R²: -0.0001
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12281 | val 0.13324
  Epoch 020 - train 0.11906 | val 0.13144
  Epoch 021 - train 0.12204 | val 0.13325
  Regression -> MSE: 0.000096, MAE: 0.008133, R²: -0.0449
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14021 | val 0.10633
  Epoch 020 - train 0.13722 | val 0.10701
  Epoch 021 - train 0.13334 | val 0.10745
  Regression -> MSE: 0.000104, MAE: 0.008802, R²: -0.0118
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14540 | val 0.15649
  Epoch 020 - train 0.14614 | val 0.15718
  Epoch 021 - train 0.14470 | val 0.15672
  Regression -> MSE: 0.000237, MAE: 0.012746, R²: -0.0232
  Directional -> Accuracy: 0.4419, MCC: -0.0713, F1: 0.4000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13532 | val 0.18014
  Epoch 020 - train 0.13188 | val 0.18048
  Epoch 021 - train 0.13005 | val 0.18041
  Regression -> MSE: 0.000187, MAE: 0.008075, R²: -0.1243
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.14522 | val 0.12036
  Epoch 020 - train 0.13892 | val 0.11642
  Epoch 030 - train 0.12970 | val 0.11934
  Regression -> MSE: 0.000237, MAE: 0.012031, R²: -0.0010
  Directional -> Accuracy: 0.5122, MCC: -0.1469, F1: 0.6774

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13515 | val 0.22198
  Epoch 020 - train 0.13102 | val 0.22926
  Epoch 021 - train 0.12996 | val 0.23032
  Regression -> MSE: 0.000231, MAE: 0.009908, R²: -0.0041
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14222 | val 0.18457
  Epoch 020 - train 0.13455 | val 0.18968
  Epoch 021 - train 0.13623 | val 0.18847
  Regression -> MSE: 0.000137, MAE: 0.008271, R²: -0.0126
  Directional -> Accuracy: 0.5116, MCC: -0.0124, F1: 0.6182

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14488 | val 0.18197
  Epoch 020 - train 0.13465 | val 0.18327
  Epoch 021 - train 0.13791 | val 0.18315
  Regression -> MSE: 0.000191, MAE: 0.010408, R²: -0.0119
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12356 | val 0.15837
  Epoch 020 - train 0.12142 | val 0.15772
  Epoch 027 - train 0.11541 | val 0.15653
  Regression -> MSE: 0.000312, MAE: 0.012303, R²: -0.1929
  Directional -> Accuracy: 0.5753, MCC: 0.1334, F1: 0.7257

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13531 | val 0.13126
  Epoch 020 - train 0.12967 | val 0.12613
  Epoch 021 - train 0.13285 | val 0.12506
  Regression -> MSE: 0.000169, MAE: 0.010361, R²: -0.0143
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11945 | val 0.16562
  Epoch 020 - train 0.11708 | val 0.16227
  Epoch 021 - train 0.11919 | val 0.16253
  Regression -> MSE: 0.000182, MAE: 0.010399, R²: -0.0134
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.13004 | val 0.13230
  Epoch 020 - train 0.12558 | val 0.13424
  Epoch 021 - train 0.12668 | val 0.13450
  Regression -> MSE: 0.000341, MAE: 0.011782, R²: 0.0042
  Directional -> Accuracy: 0.5821, MCC: 0.0955, F1: 0.7143

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.14495 | val 0.10022
  Epoch 020 - train 0.13934 | val 0.10151
  Epoch 021 - train 0.14501 | val 0.10110
  Regression -> MSE: 0.000121, MAE: 0.008385, R²: -0.1469
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13170 | val 0.20106
  Epoch 020 - train 0.13177 | val 0.20314
  Epoch 021 - train 0.13200 | val 0.20335
  Regression -> MSE: 0.000220, MAE: 0.011344, R²: -0.0063
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13435 | val 0.26788
  Epoch 020 - train 0.12947 | val 0.27086
  Epoch 021 - train 0.12961 | val 0.26983
  Regression -> MSE: 0.000084, MAE: 0.007171, R²: -0.0873
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.13297 | val 0.10797
  Epoch 020 - train 0.13067 | val 0.10592
  Epoch 028 - train 0.12412 | val 0.10631
  Regression -> MSE: 0.000352, MAE: 0.015916, R²: -0.1445
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14103 | val 0.09900
  Epoch 020 - train 0.13865 | val 0.10716
  Epoch 021 - train 0.14091 | val 0.10749
  Regression -> MSE: 0.000254, MAE: 0.011450, R²: -0.0429
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.13134 | val 0.17304
  Epoch 020 - train 0.12943 | val 0.17388
  Epoch 021 - train 0.13273 | val 0.17401
  Regression -> MSE: 0.000084, MAE: 0.007081, R²: -0.0401
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13448 | val 0.16687
  Epoch 020 - train 0.13753 | val 0.16492
  Epoch 030 - train 0.13181 | val 0.16436
  Regression -> MSE: 0.000304, MAE: 0.014129, R²: 0.0106
  Directional -> Accuracy: 0.4681, MCC: -0.1036, F1: 0.6032

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.14308 | val 0.15145
  Epoch 020 - train 0.13731 | val 0.15406
  Epoch 021 - train 0.13515 | val 0.15437
  Regression -> MSE: 0.000099, MAE: 0.007181, R²: -0.0046
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.15133 | val 0.17641
  Epoch 020 - train 0.14518 | val 0.17864
  Epoch 021 - train 0.14809 | val 0.17768
  Regression -> MSE: 0.000173, MAE: 0.009474, R²: -0.0087
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...


[I 2026-02-24 06:06:53,197] Trial 210 finished with value: -0.011519394145660404 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 16, 'learning_rate': 1.4945816287329633e-05, 'weight_decay': 4.394825138260028e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.21385617854776395, 'early_stopping_min_delta': 0.00751785517617926}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.13694 | val 0.22508
  Epoch 021 - train 0.13699 | val 0.22714
  Regression -> MSE: 0.000237, MAE: 0.012460, R²: -0.0009
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.10294 | val 0.15926
  Epoch 020 - train 0.10325 | val 0.15956
  Epoch 021 - train 0.10403 | val 0.15896
  Regression -> MSE: 0.000250, MAE: 0.012636, R²: -0.0084
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.10946 | val 0.09746
  Epoch 020 - train 0.10549 | val 0.09990
  Epoch 021 - train 0.10296 | val 0.09998
  Regression -> MSE: 0.000691, MAE: 0.019469, R²: -0.0089
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10376 | val 0.17331
  Epoch 020 - train 0.10443 | val 0.17516
  Epoch 021 - train 0.10488 | val 0.17520
  Regression -> MSE: 0.000313, MAE: 0.014435, R²: -0.0102
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09047 | val 0.09913
  Epoch 020 - train 0.08877 | val 0.09634
  Epoch 021 - train 0.08708 | val 0.09540
  Regression -> MSE: 0.000352, MAE: 0.014584, R²: -0.0067
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11257 | val 0.10622
  Epoch 020 - train 0.11099 | val 0.10475
  Epoch 021 - train 0.10649 | val 0.10446
  Regression -> MSE: 0.000206, MAE: 0.010354, R²: -0.0110
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09955 | val 0.19112
  Epoch 020 - train 0.09807 | val 0.20628
  Epoch 021 - train 0.09976 | val 0.20576
  Regression -> MSE: 0.000556, MAE: 0.018128, R²: -0.0012
  Directional -> Accuracy: 0.5532, MCC: 0.1997, F1: 0.6769

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10878 | val 0.13718
  Epoch 020 - train 0.10676 | val 0.13569
  Epoch 021 - train 0.10574 | val 0.13545
  Regression -> MSE: 0.000248, MAE: 0.012248, R²: -0.0090
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.10210 | val 0.15138
  Epoch 020 - train 0.09967 | val 0.14305
  Epoch 030 - train 0.09775 | val 0.14117
  Regression -> MSE: 0.000617, MAE: 0.019356, R²: -0.0319
  Directional -> Accuracy: 0.4773, MCC: 0.0534, F1: 0.5490

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10550 | val 0.13004
  Epoch 020 - train 0.09981 | val 0.13478
  Epoch 021 - train 0.10033 | val 0.13510
  Regression -> MSE: 0.000388, MAE: 0.016029, R²: -0.0116
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.10611 | val 0.13271
  Epoch 020 - train 0.10561 | val 0.13325
  Epoch 021 - train 0.10423 | val 0.13321
  Regression -> MSE: 0.000242, MAE: 0.011955, R²: -0.0018
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.09294 | val 0.15194
  Epoch 020 - train 0.09383 | val 0.15396
  Epoch 021 - train 0.09269 | val 0.15467
  Regression -> MSE: 0.000310, MAE: 0.013671, R²: 0.0027
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10854 | val 0.11910
  Epoch 020 - train 0.10775 | val 0.12069
  Epoch 021 - train 0.10884 | val 0.12103
  Regression -> MSE: 0.000680, MAE: 0.019576, R²: -0.0041
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10552 | val 0.12303
  Epoch 020 - train 0.10285 | val 0.15174
  Epoch 021 - train 0.10169 | val 0.15165
  Regression -> MSE: 0.000139, MAE: 0.009176, R²: -0.0028
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09569 | val 0.13649
  Epoch 020 - train 0.09491 | val 0.13399
  Epoch 021 - train 0.09622 | val 0.13371
  Regression -> MSE: 0.000225, MAE: 0.010713, R²: -0.0001
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10271 | val 0.21759
  Epoch 020 - train 0.10157 | val 0.23076
  Epoch 021 - train 0.10139 | val 0.23031
  Regression -> MSE: 0.000367, MAE: 0.015961, R²: -0.0147
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.10651 | val 0.11463
  Epoch 020 - train 0.10883 | val 0.11373
  Epoch 021 - train 0.10588 | val 0.11467
  Regression -> MSE: 0.000108, MAE: 0.007952, R²: -0.0000
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10172 | val 0.17242
  Epoch 020 - train 0.10166 | val 0.17432
  Epoch 021 - train 0.10137 | val 0.17425
  Regression -> MSE: 0.000156, MAE: 0.009594, R²: -0.0025
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10399 | val 0.10795
  Epoch 020 - train 0.10249 | val 0.10832
  Epoch 021 - train 0.10358 | val 0.10847
  Regression -> MSE: 0.000279, MAE: 0.013377, R²: -0.0239
  Directional -> Accuracy: 0.3947, MCC: -0.0630, F1: 0.1154

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.09612 | val 0.14176
  Epoch 020 - train 0.09274 | val 0.14103
  Epoch 021 - train 0.09462 | val 0.14135
  Regression -> MSE: 0.000153, MAE: 0.008725, R²: -0.0219
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10980 | val 0.17441
  Epoch 020 - train 0.10854 | val 0.16877
  Epoch 021 - train 0.10778 | val 0.16832
  Regression -> MSE: 0.000228, MAE: 0.010889, R²: -0.0084
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10757 | val 0.13510
  Epoch 020 - train 0.10366 | val 0.13594
  Epoch 021 - train 0.10531 | val 0.13579
  Regression -> MSE: 0.000143, MAE: 0.008312, R²: 0.0020
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09837 | val 0.12944
  Epoch 020 - train 0.09741 | val 0.13010
  Epoch 021 - train 0.09718 | val 0.12985
  Regression -> MSE: 0.000167, MAE: 0.010299, R²: -0.0098
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11022 | val 0.12594
  Epoch 020 - train 0.10975 | val 0.12817
  Epoch 021 - train 0.11057 | val 0.12853
  Regression -> MSE: 0.000091, MAE: 0.007386, R²: -0.0728
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.10219 | val 0.13305
  Epoch 020 - train 0.10135 | val 0.13070
  Epoch 021 - train 0.09968 | val 0.13119
  Regression -> MSE: 0.000215, MAE: 0.011394, R²: -0.0129
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09882 | val 0.09361
  Epoch 020 - train 0.09590 | val 0.09343
  Epoch 021 - train 0.09526 | val 0.09338
  Regression -> MSE: 0.000101, MAE: 0.008225, R²: -0.0965
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10305 | val 0.09049
  Epoch 020 - train 0.10386 | val 0.09135
  Epoch 021 - train 0.10295 | val 0.09155
  Regression -> MSE: 0.000117, MAE: 0.009227, R²: -0.1323
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11019 | val 0.10353
  Epoch 020 - train 0.10721 | val 0.10971
  Epoch 021 - train 0.10877 | val 0.10895
  Regression -> MSE: 0.000241, MAE: 0.012885, R²: -0.0427
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10293 | val 0.12926
  Epoch 020 - train 0.10307 | val 0.12940
  Epoch 021 - train 0.10412 | val 0.12961
  Regression -> MSE: 0.000175, MAE: 0.007878, R²: -0.0488
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10595 | val 0.09213
  Epoch 020 - train 0.10587 | val 0.09259
  Epoch 021 - train 0.10356 | val 0.09283
  Regression -> MSE: 0.000237, MAE: 0.011873, R²: -0.0034
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.10563 | val 0.16730
  Epoch 020 - train 0.10553 | val 0.17600
  Epoch 021 - train 0.10262 | val 0.17624
  Regression -> MSE: 0.000232, MAE: 0.009986, R²: -0.0083
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.11004 | val 0.13644
  Epoch 020 - train 0.11024 | val 0.14882
  Epoch 021 - train 0.10922 | val 0.14919
  Regression -> MSE: 0.000139, MAE: 0.008391, R²: -0.0330
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.11093 | val 0.13313
  Epoch 020 - train 0.10837 | val 0.13475
  Epoch 021 - train 0.10945 | val 0.13478
  Regression -> MSE: 0.000201, MAE: 0.010773, R²: -0.0692
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09242 | val 0.12865
  Epoch 020 - train 0.09135 | val 0.12735
  Epoch 021 - train 0.09140 | val 0.12641
  Regression -> MSE: 0.000265, MAE: 0.010501, R²: -0.0130
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10029 | val 0.08939
  Epoch 020 - train 0.09715 | val 0.09103
  Epoch 021 - train 0.09425 | val 0.09157
  Regression -> MSE: 0.000169, MAE: 0.010364, R²: -0.0140
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.09840 | val 0.11085
  Epoch 020 - train 0.09723 | val 0.11029
  Epoch 021 - train 0.09654 | val 0.11026
  Regression -> MSE: 0.000185, MAE: 0.010505, R²: -0.0260
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.10038 | val 0.10526
  Epoch 020 - train 0.09787 | val 0.10686
  Epoch 021 - train 0.09620 | val 0.10639
  Regression -> MSE: 0.000348, MAE: 0.012285, R²: -0.0145
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11323 | val 0.06909
  Epoch 020 - train 0.11080 | val 0.06903
  Epoch 021 - train 0.10681 | val 0.06893
  Regression -> MSE: 0.000122, MAE: 0.008399, R²: -0.1641
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11104 | val 0.14180
  Epoch 020 - train 0.10890 | val 0.14372
  Epoch 021 - train 0.10700 | val 0.14369
  Regression -> MSE: 0.000221, MAE: 0.011350, R²: -0.0091
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.10435 | val 0.17383
  Epoch 020 - train 0.10287 | val 0.17580
  Epoch 021 - train 0.10415 | val 0.17620
  Regression -> MSE: 0.000088, MAE: 0.007360, R²: -0.1388
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11243 | val 0.09370
  Epoch 020 - train 0.10600 | val 0.11480
  Epoch 021 - train 0.10888 | val 0.11725
  Regression -> MSE: 0.000342, MAE: 0.015457, R²: -0.1133
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11377 | val 0.06497
  Epoch 020 - train 0.10773 | val 0.06819
  Epoch 021 - train 0.11521 | val 0.06854
  Regression -> MSE: 0.000246, MAE: 0.011575, R²: -0.0090
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10253 | val 0.12450
  Epoch 020 - train 0.10100 | val 0.12519
  Epoch 021 - train 0.10012 | val 0.12531
  Regression -> MSE: 0.000082, MAE: 0.007135, R²: -0.0104
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10558 | val 0.13309
  Epoch 020 - train 0.10649 | val 0.12996
  Epoch 021 - train 0.10382 | val 0.12989
  Regression -> MSE: 0.000310, MAE: 0.014485, R²: -0.0115
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10246 | val 0.11087
  Epoch 020 - train 0.10132 | val 0.11409
  Epoch 021 - train 0.09938 | val 0.11437
  Regression -> MSE: 0.000098, MAE: 0.007326, R²: 0.0015
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11125 | val 0.12314
  Epoch 020 - train 0.10959 | val 0.12503
  Epoch 021 - train 0.11270 | val 0.12514
  Regression -> MSE: 0.000173, MAE: 0.009898, R²: -0.0047
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 06:08:58,787] Trial 211 finished with value: -0.011467482311113737 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 9.03989195068712e-06, 'weight_decay': 0.00010769213476041089, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.1546720427189588, 'early_stopping_min_delta': 0.006908980163529284}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.10772 | val 0.14684
  Epoch 021 - train 0.10706 | val 0.14694
  Regression -> MSE: 0.000246, MAE: 0.012377, R²: -0.0354
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09098 | val 0.12197
  Epoch 020 - train 0.09112 | val 0.12216
  Epoch 021 - train 0.09118 | val 0.12272
  Regression -> MSE: 0.000249, MAE: 0.012595, R²: -0.0040
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.08987 | val 0.08525
  Epoch 020 - train 0.09121 | val 0.08541
  Epoch 021 - train 0.08843 | val 0.08561
  Regression -> MSE: 0.000706, MAE: 0.019753, R²: -0.0318
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09448 | val 0.14730
  Epoch 020 - train 0.09379 | val 0.14732
  Epoch 021 - train 0.09427 | val 0.14709
  Regression -> MSE: 0.000311, MAE: 0.014390, R²: -0.0010
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.07738 | val 0.10442
  Epoch 020 - train 0.07598 | val 0.11351
  Epoch 021 - train 0.07679 | val 0.11234
  Regression -> MSE: 0.000368, MAE: 0.014890, R²: -0.0528
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09442 | val 0.10504
  Epoch 020 - train 0.09097 | val 0.11801
  Epoch 021 - train 0.09566 | val 0.11784
  Regression -> MSE: 0.000205, MAE: 0.010105, R²: -0.0077
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09156 | val 0.16780
  Epoch 020 - train 0.08846 | val 0.17808
  Epoch 021 - train 0.08782 | val 0.17835
  Regression -> MSE: 0.000556, MAE: 0.018128, R²: -0.0019
  Directional -> Accuracy: 0.5745, MCC: 0.1506, F1: 0.5833

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09383 | val 0.12193
  Epoch 020 - train 0.09356 | val 0.12214
  Epoch 021 - train 0.09296 | val 0.12200
  Regression -> MSE: 0.000245, MAE: 0.012000, R²: 0.0005
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09687 | val 0.10905
  Epoch 020 - train 0.09352 | val 0.09792
  Epoch 030 - train 0.09619 | val 0.09719
  Regression -> MSE: 0.000647, MAE: 0.019841, R²: -0.0821
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.08902 | val 0.11451
  Epoch 020 - train 0.08616 | val 0.11290
  Epoch 021 - train 0.08724 | val 0.11300
  Regression -> MSE: 0.000386, MAE: 0.016085, R²: -0.0052
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09243 | val 0.11666
  Epoch 020 - train 0.08909 | val 0.11682
  Epoch 021 - train 0.08858 | val 0.11699
  Regression -> MSE: 0.000241, MAE: 0.011844, R²: 0.0006
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08286 | val 0.13551
  Epoch 020 - train 0.08435 | val 0.14217
  Epoch 021 - train 0.08386 | val 0.14253
  Regression -> MSE: 0.000313, MAE: 0.013606, R²: -0.0053
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10421 | val 0.12095
  Epoch 020 - train 0.10207 | val 0.12640
  Epoch 021 - train 0.10273 | val 0.12703
  Regression -> MSE: 0.000680, MAE: 0.019565, R²: -0.0038
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09329 | val 0.09220
  Epoch 020 - train 0.08969 | val 0.09443
  Epoch 021 - train 0.09171 | val 0.09447
  Regression -> MSE: 0.000142, MAE: 0.009371, R²: -0.0251
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.09072 | val 0.11372
  Epoch 020 - train 0.08909 | val 0.11281
  Epoch 021 - train 0.09068 | val 0.11284
  Regression -> MSE: 0.000231, MAE: 0.010925, R²: -0.0263
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09495 | val 0.18186
  Epoch 020 - train 0.09206 | val 0.18476
  Epoch 021 - train 0.09398 | val 0.18575
  Regression -> MSE: 0.000364, MAE: 0.015984, R²: -0.0059
  Directional -> Accuracy: 0.5192, MCC: -0.0403, F1: 0.1379

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09867 | val 0.09808
  Epoch 020 - train 0.09553 | val 0.09851
  Epoch 021 - train 0.09700 | val 0.09831
  Regression -> MSE: 0.000108, MAE: 0.007971, R²: -0.0006
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.08894 | val 0.16957
  Epoch 020 - train 0.08870 | val 0.17880
  Epoch 021 - train 0.09005 | val 0.17965
  Regression -> MSE: 0.000161, MAE: 0.010147, R²: -0.0338
  Directional -> Accuracy: 0.4068, MCC: -0.0642, F1: 0.3137

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.09824 | val 0.12262
  Epoch 020 - train 0.09935 | val 0.11956
  Epoch 021 - train 0.09939 | val 0.12067
  Regression -> MSE: 0.000275, MAE: 0.012889, R²: -0.0095
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08367 | val 0.12017
  Epoch 020 - train 0.08386 | val 0.11961
  Epoch 021 - train 0.08118 | val 0.11967
  Regression -> MSE: 0.000162, MAE: 0.008965, R²: -0.0858
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.09621 | val 0.13430
  Epoch 020 - train 0.09557 | val 0.13255
  Epoch 021 - train 0.09394 | val 0.13247
  Regression -> MSE: 0.000240, MAE: 0.011104, R²: -0.0612
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.08917 | val 0.11581
  Epoch 020 - train 0.09001 | val 0.12059
  Epoch 021 - train 0.09131 | val 0.12023
  Regression -> MSE: 0.000146, MAE: 0.008531, R²: -0.0212
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.08748 | val 0.10563
  Epoch 020 - train 0.08747 | val 0.10731
  Epoch 021 - train 0.08755 | val 0.10744
  Regression -> MSE: 0.000179, MAE: 0.010296, R²: -0.0848
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.09906 | val 0.11116
  Epoch 020 - train 0.09634 | val 0.11469
  Epoch 021 - train 0.09469 | val 0.11439
  Regression -> MSE: 0.000086, MAE: 0.007072, R²: -0.0093
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09938 | val 0.11338
  Epoch 020 - train 0.09656 | val 0.11557
  Epoch 021 - train 0.09736 | val 0.11502
  Regression -> MSE: 0.000217, MAE: 0.011037, R²: -0.0258
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.08639 | val 0.08571
  Epoch 020 - train 0.08590 | val 0.08518
  Epoch 021 - train 0.08663 | val 0.08533
  Regression -> MSE: 0.000105, MAE: 0.008335, R²: -0.1408
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.09850 | val 0.07804
  Epoch 020 - train 0.09513 | val 0.08380
  Epoch 021 - train 0.09237 | val 0.08443
  Regression -> MSE: 0.000115, MAE: 0.009171, R²: -0.1128
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.09501 | val 0.09163
  Epoch 020 - train 0.09662 | val 0.09165
  Epoch 021 - train 0.09709 | val 0.09177
  Regression -> MSE: 0.000243, MAE: 0.012914, R²: -0.0484
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09425 | val 0.11913
  Epoch 020 - train 0.09342 | val 0.12326
  Epoch 021 - train 0.09201 | val 0.12314
  Regression -> MSE: 0.000178, MAE: 0.007906, R²: -0.0693
  Directional -> Accuracy: 0.5088, MCC: 0.2428, F1: 0.2222

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.09707 | val 0.08137
  Epoch 020 - train 0.09845 | val 0.08565
  Epoch 021 - train 0.09600 | val 0.08621
  Regression -> MSE: 0.000237, MAE: 0.011869, R²: -0.0020
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.08858 | val 0.14459
  Epoch 020 - train 0.08906 | val 0.15091
  Epoch 021 - train 0.08908 | val 0.15084
  Regression -> MSE: 0.000231, MAE: 0.009884, R²: -0.0006
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.09736 | val 0.11502
  Epoch 020 - train 0.09555 | val 0.10826
  Epoch 030 - train 0.09590 | val 0.10861
  Regression -> MSE: 0.000142, MAE: 0.008215, R²: -0.0520
  Directional -> Accuracy: 0.4884, MCC: -0.2060, F1: 0.6562

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09314 | val 0.11291
  Epoch 020 - train 0.09247 | val 0.11407
  Epoch 021 - train 0.09584 | val 0.11403
  Regression -> MSE: 0.000189, MAE: 0.010404, R²: -0.0061
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.08278 | val 0.10410
  Epoch 020 - train 0.07947 | val 0.10278
  Epoch 021 - train 0.08207 | val 0.10257
  Regression -> MSE: 0.000269, MAE: 0.010589, R²: -0.0266
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09063 | val 0.07884
  Epoch 020 - train 0.09137 | val 0.08768
  Epoch 021 - train 0.09030 | val 0.09022
  Regression -> MSE: 0.000170, MAE: 0.010367, R²: -0.0180
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08717 | val 0.09322
  Epoch 020 - train 0.08468 | val 0.09205
  Epoch 021 - train 0.08378 | val 0.09205
  Regression -> MSE: 0.000181, MAE: 0.010336, R²: -0.0035
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.08766 | val 0.08609
  Epoch 020 - train 0.08645 | val 0.08639
  Epoch 021 - train 0.08767 | val 0.08637
  Regression -> MSE: 0.000342, MAE: 0.011967, R²: 0.0005
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.09914 | val 0.06207
  Epoch 020 - train 0.09859 | val 0.06366
  Epoch 021 - train 0.09941 | val 0.06349
  Regression -> MSE: 0.000125, MAE: 0.008459, R²: -0.1917
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09413 | val 0.13152
  Epoch 020 - train 0.09234 | val 0.13926
  Epoch 021 - train 0.09308 | val 0.13963
  Regression -> MSE: 0.000219, MAE: 0.011325, R²: -0.0016
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09465 | val 0.16159
  Epoch 020 - train 0.09518 | val 0.17328
  Epoch 021 - train 0.09536 | val 0.17291
  Regression -> MSE: 0.000083, MAE: 0.007100, R²: -0.0669
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.08699 | val 0.07747
  Epoch 020 - train 0.09071 | val 0.08233
  Epoch 021 - train 0.08886 | val 0.08261
  Regression -> MSE: 0.000330, MAE: 0.014978, R²: -0.0721
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.09716 | val 0.05688
  Epoch 020 - train 0.09314 | val 0.05841
  Epoch 021 - train 0.09440 | val 0.05881
  Regression -> MSE: 0.000248, MAE: 0.011524, R²: -0.0159
  Directional -> Accuracy: 0.4474, MCC: -0.1789, F1: 0.5882

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.08848 | val 0.10879
  Epoch 020 - train 0.08612 | val 0.10811
  Epoch 021 - train 0.08561 | val 0.10817
  Regression -> MSE: 0.000081, MAE: 0.007060, R²: 0.0015
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.09191 | val 0.11292
  Epoch 020 - train 0.09138 | val 0.11840
  Epoch 021 - train 0.09308 | val 0.11843
  Regression -> MSE: 0.000310, MAE: 0.014522, R²: -0.0095
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09072 | val 0.11213
  Epoch 020 - train 0.08628 | val 0.10971
  Epoch 021 - train 0.08615 | val 0.11000
  Regression -> MSE: 0.000104, MAE: 0.007115, R²: -0.0621
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.09870 | val 0.10696
  Epoch 020 - train 0.10021 | val 0.10520
  Epoch 021 - train 0.09668 | val 0.10523
  Regression -> MSE: 0.000172, MAE: 0.009743, R²: -0.0017
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.08823 | val 0.10289
  Epoch 020 - train 0.08407 | val 0.10434
  Epoch 021 - train 0.08316 | val 0.10426
  Regression -> MSE: 0.000223, MAE: 0.011723, R²: -0.0021
  Directional -> Accuracy: 0.5357, MCC: 0.0248, F1: 0.6750

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.09394 | val 0.11075
  Epoch 020 - train 0.09066 | val 0.11494
  Epoch 021 - train 0.09203 | val 0.11513

[I 2026-02-24 06:11:02,783] Trial 212 finished with value: -0.01144182069305362 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 4.9283466777731155e-06, 'weight_decay': 9.224805572231933e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.1335994123787662, 'early_stopping_min_delta': 0.007201644160262066}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.09077 | val 0.13366
  Epoch 021 - train 0.08961 | val 0.13450
  Regression -> MSE: 0.000238, MAE: 0.012327, R²: -0.0031
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11662 | val 0.16052
  Epoch 020 - train 0.11428 | val 0.16078
  Epoch 021 - train 0.11500 | val 0.16072
  Regression -> MSE: 0.000254, MAE: 0.012814, R²: -0.0278
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11347 | val 0.11036
  Epoch 020 - train 0.11357 | val 0.10863
  Epoch 021 - train 0.11125 | val 0.10850
  Regression -> MSE: 0.000697, MAE: 0.019553, R²: -0.0180
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12137 | val 0.19818
  Epoch 020 - train 0.12286 | val 0.20436
  Epoch 021 - train 0.12024 | val 0.20386
  Regression -> MSE: 0.000324, MAE: 0.014568, R²: -0.0432
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10622 | val 0.12036
  Epoch 020 - train 0.10746 | val 0.12808
  Epoch 021 - train 0.10843 | val 0.12772
  Regression -> MSE: 0.000384, MAE: 0.015160, R²: -0.1005
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11783 | val 0.11556
  Epoch 020 - train 0.11556 | val 0.11501
  Epoch 021 - train 0.11490 | val 0.11475
  Regression -> MSE: 0.000206, MAE: 0.010067, R²: -0.0117
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12948 | val 0.24034
  Epoch 020 - train 0.12745 | val 0.27587
  Epoch 021 - train 0.12896 | val 0.27621
  Regression -> MSE: 0.000623, MAE: 0.019574, R²: -0.1217
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.11969 | val 0.14548
  Epoch 020 - train 0.11857 | val 0.14610
  Epoch 021 - train 0.11861 | val 0.14636
  Regression -> MSE: 0.000245, MAE: 0.012020, R²: 0.0003
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12275 | val 0.17745
  Epoch 020 - train 0.12166 | val 0.17809
  Epoch 021 - train 0.11986 | val 0.17850
  Regression -> MSE: 0.000680, MAE: 0.020710, R²: -0.1380
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.11256 | val 0.13930
  Epoch 020 - train 0.10962 | val 0.13440
  Epoch 030 - train 0.11062 | val 0.13425
  Regression -> MSE: 0.000461, MAE: 0.017106, R²: -0.2015
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11806 | val 0.17193
  Epoch 020 - train 0.11389 | val 0.17785
  Epoch 021 - train 0.11481 | val 0.17697
  Regression -> MSE: 0.000249, MAE: 0.011637, R²: -0.0303
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11111 | val 0.15955
  Epoch 020 - train 0.11110 | val 0.16015
  Epoch 030 - train 0.10745 | val 0.16001
  Regression -> MSE: 0.000395, MAE: 0.015044, R²: -0.2702
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12399 | val 0.14085
  Epoch 020 - train 0.12571 | val 0.14166
  Epoch 021 - train 0.12401 | val 0.14180
  Regression -> MSE: 0.000694, MAE: 0.020032, R²: -0.0241
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.11808 | val 0.11795
  Epoch 020 - train 0.11574 | val 0.12402
  Epoch 021 - train 0.11545 | val 0.12371
  Regression -> MSE: 0.000146, MAE: 0.009571, R²: -0.0596
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10961 | val 0.16548
  Epoch 020 - train 0.10824 | val 0.16678
  Epoch 021 - train 0.10670 | val 0.16675
  Regression -> MSE: 0.000227, MAE: 0.010919, R²: -0.0109
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11326 | val 0.24011
  Epoch 020 - train 0.11226 | val 0.24324
  Epoch 021 - train 0.11515 | val 0.24307
  Regression -> MSE: 0.000363, MAE: 0.016041, R²: -0.0030
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.12345 | val 0.13164
  Epoch 020 - train 0.12030 | val 0.13284
  Epoch 021 - train 0.12192 | val 0.13496
  Regression -> MSE: 0.000108, MAE: 0.008016, R²: 0.0012
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.11607 | val 0.22235
  Epoch 020 - train 0.11563 | val 0.22775
  Epoch 021 - train 0.11498 | val 0.22842
  Regression -> MSE: 0.000156, MAE: 0.009533, R²: -0.0009
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12133 | val 0.11648
  Epoch 020 - train 0.11980 | val 0.11778
  Epoch 021 - train 0.11877 | val 0.11770
  Regression -> MSE: 0.000285, MAE: 0.013629, R²: -0.0470
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.10783 | val 0.17041
  Epoch 020 - train 0.10432 | val 0.16766
  Epoch 021 - train 0.10601 | val 0.16907
  Regression -> MSE: 0.000163, MAE: 0.008957, R²: -0.0868
  Directional -> Accuracy: 0.4462, MCC: -0.0365, F1: 0.3571

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12860 | val 0.21966
  Epoch 020 - train 0.12404 | val 0.22018
  Epoch 021 - train 0.12390 | val 0.21960
  Regression -> MSE: 0.000256, MAE: 0.011460, R²: -0.1334
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.11551 | val 0.14824
  Epoch 020 - train 0.11433 | val 0.15290
  Epoch 021 - train 0.11573 | val 0.15188
  Regression -> MSE: 0.000150, MAE: 0.008682, R²: -0.0454
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11409 | val 0.15293
  Epoch 020 - train 0.11465 | val 0.15024
  Epoch 021 - train 0.11394 | val 0.14972
  Regression -> MSE: 0.000167, MAE: 0.010752, R²: -0.0107
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11880 | val 0.14400
  Epoch 020 - train 0.12161 | val 0.14462
  Epoch 021 - train 0.11934 | val 0.14447
  Regression -> MSE: 0.000086, MAE: 0.007068, R²: -0.0033
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11302 | val 0.15339
  Epoch 020 - train 0.11337 | val 0.15474
  Epoch 021 - train 0.11100 | val 0.15474
  Regression -> MSE: 0.000213, MAE: 0.011244, R²: -0.0034
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11165 | val 0.10398
  Epoch 020 - train 0.10753 | val 0.10330
  Epoch 021 - train 0.10800 | val 0.10342
  Regression -> MSE: 0.000104, MAE: 0.008352, R²: -0.1343
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11550 | val 0.09197
  Epoch 020 - train 0.11404 | val 0.09667
  Epoch 021 - train 0.11997 | val 0.09716
  Regression -> MSE: 0.000104, MAE: 0.008749, R²: -0.0038
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.11830 | val 0.12181
  Epoch 020 - train 0.11701 | val 0.14100
  Epoch 021 - train 0.11752 | val 0.14099
  Regression -> MSE: 0.000234, MAE: 0.012625, R²: -0.0093
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.11370 | val 0.14480
  Epoch 020 - train 0.11517 | val 0.14616
  Epoch 021 - train 0.11766 | val 0.14625
  Regression -> MSE: 0.000175, MAE: 0.007906, R²: -0.0523
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12476 | val 0.10177
  Epoch 020 - train 0.12206 | val 0.09819
  Epoch 021 - train 0.11824 | val 0.09816
  Regression -> MSE: 0.000237, MAE: 0.011880, R²: -0.0026
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12298 | val 0.18253
  Epoch 020 - train 0.12032 | val 0.18336
  Epoch 021 - train 0.11943 | val 0.18333
  Regression -> MSE: 0.000230, MAE: 0.009856, R²: 0.0010
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12921 | val 0.13769
  Epoch 020 - train 0.12760 | val 0.14185
  Epoch 030 - train 0.12476 | val 0.14237
  Regression -> MSE: 0.000153, MAE: 0.008847, R²: -0.1359
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12094 | val 0.14701
  Epoch 020 - train 0.11731 | val 0.14667
  Epoch 021 - train 0.11478 | val 0.14662
  Regression -> MSE: 0.000188, MAE: 0.010464, R²: 0.0013
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11064 | val 0.17347
  Epoch 020 - train 0.10830 | val 0.16916
  Epoch 021 - train 0.10930 | val 0.17050
  Regression -> MSE: 0.000263, MAE: 0.010631, R²: -0.0057
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12347 | val 0.10904
  Epoch 020 - train 0.12243 | val 0.13357
  Epoch 021 - train 0.12361 | val 0.13770
  Regression -> MSE: 0.000168, MAE: 0.010375, R²: -0.0102
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11634 | val 0.12941
  Epoch 020 - train 0.11601 | val 0.14723
  Epoch 021 - train 0.11627 | val 0.14748
  Regression -> MSE: 0.000184, MAE: 0.010427, R²: -0.0216
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.11386 | val 0.11220
  Epoch 020 - train 0.11187 | val 0.11279
  Epoch 021 - train 0.11034 | val 0.11305
  Regression -> MSE: 0.000343, MAE: 0.011746, R²: -0.0002
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12896 | val 0.07937
  Epoch 020 - train 0.12849 | val 0.08152
  Epoch 021 - train 0.13064 | val 0.08203
  Regression -> MSE: 0.000113, MAE: 0.008320, R²: -0.0755
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.11443 | val 0.15503
  Epoch 020 - train 0.11413 | val 0.15744
  Epoch 021 - train 0.11339 | val 0.15759
  Regression -> MSE: 0.000219, MAE: 0.011331, R²: -0.0032
  Directional -> Accuracy: 0.4912, MCC: -0.1231, F1: 0.0645

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12228 | val 0.20423
  Epoch 020 - train 0.12127 | val 0.21236
  Epoch 021 - train 0.11881 | val 0.21246
  Regression -> MSE: 0.000081, MAE: 0.007004, R²: -0.0421
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.11984 | val 0.10043
  Epoch 020 - train 0.11797 | val 0.09833
  Epoch 021 - train 0.12043 | val 0.09849
  Regression -> MSE: 0.000338, MAE: 0.015294, R²: -0.0995
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12440 | val 0.07730
  Epoch 020 - train 0.12497 | val 0.07533
  Epoch 021 - train 0.12493 | val 0.07558
  Regression -> MSE: 0.000259, MAE: 0.011495, R²: -0.0628
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11509 | val 0.14654
  Epoch 020 - train 0.11349 | val 0.14948
  Epoch 021 - train 0.11409 | val 0.14928
  Regression -> MSE: 0.000081, MAE: 0.007099, R²: -0.0030
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11939 | val 0.16397
  Epoch 020 - train 0.11722 | val 0.21511
  Epoch 021 - train 0.11711 | val 0.21507
  Regression -> MSE: 0.000307, MAE: 0.014481, R²: -0.0020
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.11114 | val 0.13419
  Epoch 020 - train 0.10877 | val 0.13540
  Epoch 021 - train 0.11002 | val 0.13514
  Regression -> MSE: 0.000099, MAE: 0.007165, R²: -0.0112
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13432 | val 0.14527
  Epoch 020 - train 0.13769 | val 0.15687
  Epoch 021 - train 0.13508 | val 0.15779
  Regression -> MSE: 0.000176, MAE: 0.010254, R²: -0.0256
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 06:13:07,080] Trial 213 finished with value: -0.01159264204275094 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 6.634377067607304e-06, 'weight_decay': 1.537403682168646e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.17572226353244533, 'early_stopping_min_delta': 0.0061099092064802315}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.12735 | val 0.19911
  Epoch 021 - train 0.12616 | val 0.19835
  Regression -> MSE: 0.000237, MAE: 0.012480, R²: -0.0003
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.12711 | val 0.17220
  Epoch 020 - train 0.12746 | val 0.17386
  Epoch 021 - train 0.12871 | val 0.17385
  Regression -> MSE: 0.000248, MAE: 0.012564, R²: -0.0014
  Directional -> Accuracy: 0.4156, MCC: -0.1437, F1: 0.5361

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12247 | val 0.12304
  Epoch 020 - train 0.12155 | val 0.12781
  Epoch 021 - train 0.12096 | val 0.12790
  Regression -> MSE: 0.000704, MAE: 0.019709, R²: -0.0289
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13400 | val 0.22018
  Epoch 020 - train 0.13321 | val 0.23195
  Epoch 021 - train 0.13541 | val 0.23168
  Regression -> MSE: 0.000310, MAE: 0.014442, R²: 0.0003
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10954 | val 0.16204
  Epoch 020 - train 0.10858 | val 0.18507
  Epoch 021 - train 0.10569 | val 0.18124
  Regression -> MSE: 0.000354, MAE: 0.014647, R²: -0.0124
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.13292 | val 0.13010
  Epoch 020 - train 0.13034 | val 0.12866
  Epoch 021 - train 0.13029 | val 0.12853
  Regression -> MSE: 0.000205, MAE: 0.010226, R²: -0.0049
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12272 | val 0.24434
  Epoch 020 - train 0.12103 | val 0.24568
  Epoch 021 - train 0.11929 | val 0.24533
  Regression -> MSE: 0.000573, MAE: 0.018439, R²: -0.0323
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13316 | val 0.16159
  Epoch 020 - train 0.12808 | val 0.15787
  Epoch 021 - train 0.12854 | val 0.15787
  Regression -> MSE: 0.000247, MAE: 0.012355, R²: -0.0080
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12377 | val 0.15706
  Epoch 020 - train 0.12285 | val 0.18718
  Epoch 021 - train 0.11940 | val 0.18982
  Regression -> MSE: 0.000603, MAE: 0.019284, R²: -0.0089
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12130 | val 0.16644
  Epoch 020 - train 0.11798 | val 0.16199
  Epoch 021 - train 0.11860 | val 0.16194
  Regression -> MSE: 0.000383, MAE: 0.016129, R²: 0.0019
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.13907 | val 0.18841
  Epoch 020 - train 0.13332 | val 0.19863
  Epoch 021 - train 0.13314 | val 0.20003
  Regression -> MSE: 0.000251, MAE: 0.011655, R²: -0.0376
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.11997 | val 0.18550
  Epoch 020 - train 0.11764 | val 0.18762
  Epoch 021 - train 0.11885 | val 0.18808
  Regression -> MSE: 0.000312, MAE: 0.013684, R²: -0.0022
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.13187 | val 0.15260
  Epoch 020 - train 0.12997 | val 0.15447
  Epoch 021 - train 0.12962 | val 0.15446
  Regression -> MSE: 0.000678, MAE: 0.019506, R²: -0.0008
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13060 | val 0.12855
  Epoch 020 - train 0.12524 | val 0.13475
  Epoch 021 - train 0.12681 | val 0.13676
  Regression -> MSE: 0.000138, MAE: 0.009069, R²: -0.0001
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11348 | val 0.16434
  Epoch 020 - train 0.11459 | val 0.16242
  Epoch 021 - train 0.11131 | val 0.16218
  Regression -> MSE: 0.000227, MAE: 0.010748, R²: -0.0094
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12462 | val 0.26837
  Epoch 020 - train 0.12732 | val 0.28241
  Epoch 021 - train 0.12483 | val 0.28318
  Regression -> MSE: 0.000368, MAE: 0.015954, R²: -0.0153
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13359 | val 0.13647
  Epoch 020 - train 0.13061 | val 0.14292
  Epoch 021 - train 0.13163 | val 0.14326
  Regression -> MSE: 0.000109, MAE: 0.007953, R²: -0.0125
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12970 | val 0.25183
  Epoch 020 - train 0.12297 | val 0.26530
  Epoch 021 - train 0.12688 | val 0.26517
  Regression -> MSE: 0.000156, MAE: 0.009717, R²: -0.0026
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.13276 | val 0.13601
  Epoch 020 - train 0.12980 | val 0.13483
  Epoch 021 - train 0.12874 | val 0.13514
  Regression -> MSE: 0.000276, MAE: 0.013258, R²: -0.0160
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11624 | val 0.18519
  Epoch 020 - train 0.11944 | val 0.18603
  Epoch 021 - train 0.11334 | val 0.18616
  Regression -> MSE: 0.000158, MAE: 0.008833, R²: -0.0558
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13345 | val 0.18101
  Epoch 020 - train 0.12948 | val 0.18280
  Epoch 021 - train 0.12643 | val 0.18336
  Regression -> MSE: 0.000231, MAE: 0.010921, R²: -0.0204
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13003 | val 0.16512
  Epoch 020 - train 0.12886 | val 0.17358
  Epoch 021 - train 0.12673 | val 0.17365
  Regression -> MSE: 0.000148, MAE: 0.008604, R²: -0.0332
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12399 | val 0.15312
  Epoch 020 - train 0.12198 | val 0.15437
  Epoch 021 - train 0.12216 | val 0.15460
  Regression -> MSE: 0.000165, MAE: 0.010529, R²: 0.0039
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13767 | val 0.16308
  Epoch 020 - train 0.13354 | val 0.16716
  Epoch 021 - train 0.13295 | val 0.16689
  Regression -> MSE: 0.000085, MAE: 0.007032, R²: 0.0014
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12625 | val 0.16340
  Epoch 020 - train 0.12758 | val 0.15904
  Epoch 021 - train 0.12556 | val 0.15932
  Regression -> MSE: 0.000213, MAE: 0.011266, R²: -0.0035
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11399 | val 0.11105
  Epoch 020 - train 0.11505 | val 0.11082
  Epoch 029 - train 0.11492 | val 0.11064
  Regression -> MSE: 0.000096, MAE: 0.007907, R²: -0.0429
  Directional -> Accuracy: 0.5536, MCC: 0.1867, F1: 0.4444

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.12652 | val 0.11122
  Epoch 020 - train 0.12903 | val 0.10535
  Epoch 021 - train 0.12698 | val 0.10520
  Regression -> MSE: 0.000118, MAE: 0.009263, R²: -0.1413
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13772 | val 0.14174
  Epoch 020 - train 0.13761 | val 0.19243
  Epoch 021 - train 0.13839 | val 0.19320
  Regression -> MSE: 0.000238, MAE: 0.012791, R²: -0.0286
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13055 | val 0.14431
  Epoch 020 - train 0.12364 | val 0.14305
  Epoch 029 - train 0.12331 | val 0.14314
  Regression -> MSE: 0.000195, MAE: 0.008259, R²: -0.1699
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13606 | val 0.11115
  Epoch 020 - train 0.12825 | val 0.11084
  Epoch 021 - train 0.13165 | val 0.11092
  Regression -> MSE: 0.000237, MAE: 0.011872, R²: -0.0007
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13609 | val 0.20323
  Epoch 020 - train 0.13114 | val 0.20271
  Epoch 021 - train 0.13108 | val 0.20291
  Regression -> MSE: 0.000231, MAE: 0.009927, R²: -0.0038
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.13378 | val 0.16991
  Epoch 020 - train 0.13052 | val 0.17867
  Epoch 021 - train 0.13310 | val 0.17851
  Regression -> MSE: 0.000142, MAE: 0.008483, R²: -0.0486
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12876 | val 0.16338
  Epoch 020 - train 0.12872 | val 0.16536
  Epoch 021 - train 0.12822 | val 0.16549
  Regression -> MSE: 0.000192, MAE: 0.010408, R²: -0.0215
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11577 | val 0.15767
  Epoch 020 - train 0.11124 | val 0.15555
  Epoch 021 - train 0.11204 | val 0.15663
  Regression -> MSE: 0.000262, MAE: 0.010529, R²: 0.0010
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12099 | val 0.11202
  Epoch 020 - train 0.11889 | val 0.11146
  Epoch 021 - train 0.12320 | val 0.11166
  Regression -> MSE: 0.000166, MAE: 0.010371, R²: 0.0014
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11886 | val 0.13118
  Epoch 020 - train 0.12146 | val 0.13779
  Epoch 021 - train 0.12010 | val 0.13805
  Regression -> MSE: 0.000182, MAE: 0.010331, R²: -0.0104
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12583 | val 0.12097
  Epoch 020 - train 0.12361 | val 0.11727
  Epoch 030 - train 0.12283 | val 0.11939
  Regression -> MSE: 0.000367, MAE: 0.013607, R²: -0.0725
  Directional -> Accuracy: 0.5522, MCC: 0.0444, F1: 0.6591

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13634 | val 0.08382
  Epoch 020 - train 0.13391 | val 0.08686
  Epoch 021 - train 0.12926 | val 0.08716
  Regression -> MSE: 0.000124, MAE: 0.008444, R²: -0.1798
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.13450 | val 0.18037
  Epoch 020 - train 0.13167 | val 0.18257
  Epoch 021 - train 0.13183 | val 0.18228
  Regression -> MSE: 0.000223, MAE: 0.011419, R²: -0.0215
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.12862 | val 0.22461
  Epoch 020 - train 0.12530 | val 0.23292
  Epoch 021 - train 0.12830 | val 0.23309
  Regression -> MSE: 0.000090, MAE: 0.007432, R²: -0.1614
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12994 | val 0.10384
  Epoch 020 - train 0.12303 | val 0.10329
  Epoch 021 - train 0.12716 | val 0.10350
  Regression -> MSE: 0.000324, MAE: 0.014720, R²: -0.0533
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.13396 | val 0.07971
  Epoch 020 - train 0.13419 | val 0.08246
  Epoch 021 - train 0.12952 | val 0.08324
  Regression -> MSE: 0.000252, MAE: 0.011484, R²: -0.0323
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12221 | val 0.16081
  Epoch 020 - train 0.11928 | val 0.15963
  Epoch 021 - train 0.12115 | val 0.15897
  Regression -> MSE: 0.000083, MAE: 0.007052, R²: -0.0333
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13300 | val 0.17613
  Epoch 020 - train 0.13805 | val 0.19026
  Epoch 021 - train 0.13475 | val 0.18906
  Regression -> MSE: 0.000311, MAE: 0.014493, R²: -0.0141
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.13346 | val 0.14059
  Epoch 020 - train 0.13367 | val 0.14189
  Epoch 021 - train 0.12820 | val 0.14202
  Regression -> MSE: 0.000098, MAE: 0.007286, R²: -0.0014
  Directional -> Accuracy: 0.4091, MCC: -0.1394, F1: 0.3158

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13836 | val 0.15710
  Epoch 020 - train 0.14003 | val 0.16873
  Epoch 021 - train 0.13909 | val 0.16992
  Regression -> MSE: 0.000175, MAE: 0.010199, R²: -0.0208
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12300 | val 0.16262
  Epoch 020 - train 0.11935 | val 0.17590
  Epoch 021 - train 0.11668 | val 0.17486
  Regression -> MSE: 0.000223, MAE: 0.011768, R²: -0.0013
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.12403 | val 0.14692
  Epoch 020 - train 0.12377 | val 0.15026
  Epoch 021 - train 0.12484 | val 0.15009

[I 2026-02-24 06:15:07,262] Trial 214 finished with value: -0.011481727607457044 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 9.91169947955402e-06, 'weight_decay': 1.1433747627101673e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.19593351169237178, 'early_stopping_min_delta': 0.006979384181390025}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.12754 | val 0.18393
  Epoch 021 - train 0.12785 | val 0.18365
  Regression -> MSE: 0.000242, MAE: 0.012337, R²: -0.0194
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.06923 | val 0.09436
  Epoch 020 - train 0.06792 | val 0.09351
  Epoch 021 - train 0.06861 | val 0.09346
  Regression -> MSE: 0.000257, MAE: 0.012916, R²: -0.0384
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.07316 | val 0.07348
  Epoch 020 - train 0.06864 | val 0.07856
  Epoch 021 - train 0.07010 | val 0.07883
  Regression -> MSE: 0.000728, MAE: 0.020063, R²: -0.0630
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.07311 | val 0.11418
  Epoch 020 - train 0.07137 | val 0.11548
  Epoch 021 - train 0.07065 | val 0.11550
  Regression -> MSE: 0.000310, MAE: 0.014393, R²: 0.0010
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06066 | val 0.09324
  Epoch 020 - train 0.05958 | val 0.08033
  Epoch 021 - train 0.06124 | val 0.08121
  Regression -> MSE: 0.000357, MAE: 0.014677, R²: -0.0226
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07072 | val 0.07582
  Epoch 020 - train 0.07020 | val 0.08008
  Epoch 021 - train 0.07018 | val 0.08046
  Regression -> MSE: 0.000204, MAE: 0.010222, R²: -0.0031
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.06690 | val 0.13391
  Epoch 020 - train 0.06714 | val 0.13557
  Epoch 021 - train 0.06894 | val 0.13522
  Regression -> MSE: 0.000603, MAE: 0.019041, R²: -0.0862
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07068 | val 0.08744
  Epoch 020 - train 0.07062 | val 0.08857
  Epoch 021 - train 0.07052 | val 0.08869
  Regression -> MSE: 0.000246, MAE: 0.011908, R²: -0.0026
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.06793 | val 0.10436
  Epoch 020 - train 0.06786 | val 0.13311
  Epoch 021 - train 0.06553 | val 0.13494
  Regression -> MSE: 0.000645, MAE: 0.020157, R²: -0.0789
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.06602 | val 0.08646
  Epoch 020 - train 0.06589 | val 0.08600
  Epoch 021 - train 0.06510 | val 0.08574
  Regression -> MSE: 0.000389, MAE: 0.015986, R²: -0.0128
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.06999 | val 0.09970
  Epoch 020 - train 0.06848 | val 0.10607
  Epoch 021 - train 0.06677 | val 0.10621
  Regression -> MSE: 0.000242, MAE: 0.011985, R²: -0.0014
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06647 | val 0.09907
  Epoch 020 - train 0.06436 | val 0.10573
  Epoch 021 - train 0.06400 | val 0.10647
  Regression -> MSE: 0.000325, MAE: 0.013608, R²: -0.0441
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07190 | val 0.08658
  Epoch 020 - train 0.07049 | val 0.09282
  Epoch 021 - train 0.07142 | val 0.09338
  Regression -> MSE: 0.000678, MAE: 0.019493, R²: -0.0014
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.06879 | val 0.07299
  Epoch 020 - train 0.06575 | val 0.07480
  Epoch 021 - train 0.06816 | val 0.07484
  Regression -> MSE: 0.000139, MAE: 0.009014, R²: -0.0075
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06459 | val 0.09662
  Epoch 020 - train 0.06157 | val 0.09627
  Epoch 021 - train 0.06288 | val 0.09645
  Regression -> MSE: 0.000226, MAE: 0.010858, R²: -0.0062
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.06970 | val 0.14511
  Epoch 020 - train 0.07062 | val 0.15362
  Epoch 021 - train 0.06889 | val 0.15355
  Regression -> MSE: 0.000364, MAE: 0.016051, R²: -0.0038
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07324 | val 0.07339
  Epoch 020 - train 0.07232 | val 0.07436
  Epoch 021 - train 0.07153 | val 0.07435
  Regression -> MSE: 0.000112, MAE: 0.007980, R²: -0.0401
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.06985 | val 0.12021
  Epoch 020 - train 0.06953 | val 0.12047
  Epoch 021 - train 0.06800 | val 0.12059
  Regression -> MSE: 0.000157, MAE: 0.009561, R²: -0.0094
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07243 | val 0.07526
  Epoch 020 - train 0.07311 | val 0.07547
  Epoch 021 - train 0.07131 | val 0.07637
  Regression -> MSE: 0.000284, MAE: 0.013620, R²: -0.0448
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06297 | val 0.09127
  Epoch 020 - train 0.06313 | val 0.09075
  Epoch 021 - train 0.06188 | val 0.09074
  Regression -> MSE: 0.000174, MAE: 0.009351, R²: -0.1635
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07055 | val 0.11098
  Epoch 020 - train 0.06870 | val 0.11220
  Epoch 021 - train 0.06912 | val 0.11207
  Regression -> MSE: 0.000246, MAE: 0.011188, R²: -0.0856
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.07399 | val 0.08734
  Epoch 020 - train 0.07320 | val 0.08849
  Epoch 021 - train 0.07322 | val 0.08849
  Regression -> MSE: 0.000144, MAE: 0.008366, R²: -0.0054
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.06629 | val 0.08842
  Epoch 020 - train 0.06486 | val 0.08918
  Epoch 021 - train 0.06561 | val 0.08939
  Regression -> MSE: 0.000166, MAE: 0.010653, R²: -0.0024
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07373 | val 0.08313
  Epoch 020 - train 0.07041 | val 0.08474
  Epoch 021 - train 0.07130 | val 0.08483
  Regression -> MSE: 0.000086, MAE: 0.007106, R²: -0.0108
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.07657 | val 0.08765
  Epoch 020 - train 0.07453 | val 0.09132
  Epoch 021 - train 0.07190 | val 0.09087
  Regression -> MSE: 0.000214, MAE: 0.011068, R²: -0.0121
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06301 | val 0.06337
  Epoch 020 - train 0.06239 | val 0.06382
  Epoch 021 - train 0.06357 | val 0.06377
  Regression -> MSE: 0.000100, MAE: 0.008210, R²: -0.0899
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.07619 | val 0.05663
  Epoch 020 - train 0.07438 | val 0.06052
  Epoch 021 - train 0.07333 | val 0.06124
  Regression -> MSE: 0.000105, MAE: 0.008866, R²: -0.0222
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07246 | val 0.06804
  Epoch 020 - train 0.07148 | val 0.06929
  Epoch 021 - train 0.07009 | val 0.06945
  Regression -> MSE: 0.000234, MAE: 0.012652, R²: -0.0114
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.07080 | val 0.08291
  Epoch 020 - train 0.06918 | val 0.07992
  Epoch 030 - train 0.06897 | val 0.07904
  Regression -> MSE: 0.000212, MAE: 0.009461, R²: -0.2728
  Directional -> Accuracy: 0.5614, MCC: 0.3307, F1: 0.3590

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07023 | val 0.06151
  Epoch 020 - train 0.07020 | val 0.06187
  Epoch 021 - train 0.07011 | val 0.06192
  Regression -> MSE: 0.000237, MAE: 0.011862, R²: -0.0004
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.06850 | val 0.11172
  Epoch 020 - train 0.06992 | val 0.11752
  Epoch 021 - train 0.06949 | val 0.11768
  Regression -> MSE: 0.000231, MAE: 0.009922, R²: -0.0037
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.07386 | val 0.09048
  Epoch 020 - train 0.07181 | val 0.08910
  Epoch 021 - train 0.07197 | val 0.08953
  Regression -> MSE: 0.000143, MAE: 0.008590, R²: -0.0576
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07071 | val 0.09011
  Epoch 020 - train 0.06799 | val 0.08871
  Epoch 021 - train 0.07068 | val 0.08875
  Regression -> MSE: 0.000188, MAE: 0.010516, R²: -0.0001
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06389 | val 0.07855
  Epoch 020 - train 0.06329 | val 0.07830
  Epoch 021 - train 0.06138 | val 0.07845
  Regression -> MSE: 0.000261, MAE: 0.010591, R²: 0.0019
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.06837 | val 0.06616
  Epoch 020 - train 0.06500 | val 0.06287
  Epoch 021 - train 0.06466 | val 0.06243
  Regression -> MSE: 0.000171, MAE: 0.010388, R²: -0.0243
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06913 | val 0.07373
  Epoch 020 - train 0.06831 | val 0.08023
  Epoch 021 - train 0.06916 | val 0.08058
  Regression -> MSE: 0.000182, MAE: 0.010361, R²: -0.0128
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.06558 | val 0.06335
  Epoch 020 - train 0.06492 | val 0.06367
  Epoch 021 - train 0.06378 | val 0.06375
  Regression -> MSE: 0.000343, MAE: 0.011946, R²: -0.0011
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.07644 | val 0.04912
  Epoch 020 - train 0.07685 | val 0.05034
  Epoch 021 - train 0.07456 | val 0.05039
  Regression -> MSE: 0.000110, MAE: 0.008335, R²: -0.0503
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07011 | val 0.10163
  Epoch 020 - train 0.06750 | val 0.10819
  Epoch 021 - train 0.06850 | val 0.10837
  Regression -> MSE: 0.000219, MAE: 0.011321, R²: -0.0038
  Directional -> Accuracy: 0.5263, MCC: 0.2236, F1: 0.6667

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.06925 | val 0.11733
  Epoch 020 - train 0.06986 | val 0.12417
  Epoch 021 - train 0.06917 | val 0.12467
  Regression -> MSE: 0.000096, MAE: 0.007639, R²: -0.2328
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.06749 | val 0.06011
  Epoch 020 - train 0.06623 | val 0.05702
  Epoch 021 - train 0.06567 | val 0.05671
  Regression -> MSE: 0.000333, MAE: 0.015108, R²: -0.0821
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07557 | val 0.04462
  Epoch 020 - train 0.07337 | val 0.04707
  Epoch 021 - train 0.07517 | val 0.04757
  Regression -> MSE: 0.000250, MAE: 0.011503, R²: -0.0260
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.06677 | val 0.08413
  Epoch 020 - train 0.06515 | val 0.08434
  Epoch 021 - train 0.06452 | val 0.08437
  Regression -> MSE: 0.000082, MAE: 0.007050, R²: -0.0158
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.07101 | val 0.08950
  Epoch 020 - train 0.06883 | val 0.08668
  Epoch 021 - train 0.06937 | val 0.08660
  Regression -> MSE: 0.000308, MAE: 0.014468, R²: -0.0049
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.06626 | val 0.07543
  Epoch 020 - train 0.06738 | val 0.07473
  Epoch 021 - train 0.06691 | val 0.07462
  Regression -> MSE: 0.000098, MAE: 0.007284, R²: -0.0021
  Directional -> Accuracy: 0.4545, MCC: -0.0621, F1: 0.4286

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.08267 | val 0.08742
  Epoch 020 - train 0.08197 | val 0.09203
  Epoch 021 - train 0.08119 | val 0.09244
  Regression -> MSE: 0.000174, MAE: 0.009417, R²: -0.0154
  Directional -> Accuracy: 0.6122, MCC: 0.0000, F1: 0.0000

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.06413 | val 0.08690
  Epoch 020 - train 0.06593 | val 0.09071
  Epoch 021 - train 0.06556 | val 0.09068
  Regression -> MSE: 0.000223, MAE: 0.011745, R²: 0.0011
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.06935 | val 0.07957
  Epoch 020 - train 0.06838 | val 0.07964
  Epoch 021 - train 0.06909 | val 0.07962
  Regression -> MSE: 0.000093, MAE: 0.007656, R²: -0.0066
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000


[I 2026-02-24 06:17:05,005] Trial 215 finished with value: -0.01151599535414473 and parameters: {'feature_set': 'base', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 1.2643660973920878e-05, 'weight_decay': 5.124551644535777e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.10047389297453513, 'early_stopping_min_delta': 0.006555935142964245}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.06851 | val 0.11163
  Epoch 021 - train 0.06996 | val 0.11104
  Regression -> MSE: 0.000240, MAE: 0.012321, R²: -0.0129
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.09846 | val 0.12485
  Epoch 020 - train 0.09696 | val 0.12737
  Epoch 021 - train 0.09495 | val 0.12757
  Regression -> MSE: 0.000248, MAE: 0.012521, R²: -0.0014
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.09521 | val 0.09572
  Epoch 020 - train 0.09121 | val 0.09592
  Epoch 021 - train 0.09298 | val 0.09614
  Regression -> MSE: 0.000694, MAE: 0.019511, R²: -0.0135
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.09841 | val 0.16074
  Epoch 020 - train 0.09560 | val 0.16073
  Epoch 021 - train 0.09662 | val 0.16094
  Regression -> MSE: 0.000313, MAE: 0.014409, R²: -0.0095
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.08421 | val 0.09963
  Epoch 020 - train 0.08374 | val 0.09990
  Epoch 021 - train 0.08070 | val 0.10057
  Regression -> MSE: 0.000350, MAE: 0.014575, R²: -0.0026
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.09774 | val 0.09641
  Epoch 020 - train 0.09543 | val 0.09692
  Epoch 021 - train 0.09541 | val 0.09683
  Regression -> MSE: 0.000205, MAE: 0.010011, R²: -0.0059
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09775 | val 0.18111
  Epoch 020 - train 0.08826 | val 0.17927
  Epoch 021 - train 0.08956 | val 0.17914
  Regression -> MSE: 0.000557, MAE: 0.018155, R²: -0.0038
  Directional -> Accuracy: 0.5106, MCC: 0.0617, F1: 0.6462

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.09664 | val 0.12701
  Epoch 020 - train 0.09606 | val 0.12918
  Epoch 021 - train 0.09777 | val 0.12928
  Regression -> MSE: 0.000248, MAE: 0.012374, R²: -0.0090
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.09075 | val 0.14592
  Epoch 020 - train 0.09184 | val 0.15175
  Epoch 021 - train 0.08930 | val 0.15209
  Regression -> MSE: 0.000654, MAE: 0.020301, R²: -0.0947
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.09282 | val 0.11523
  Epoch 020 - train 0.09003 | val 0.11353
  Epoch 021 - train 0.08764 | val 0.11347
  Regression -> MSE: 0.000406, MAE: 0.016162, R²: -0.0571
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.09881 | val 0.13639
  Epoch 020 - train 0.09503 | val 0.13929
  Epoch 021 - train 0.09420 | val 0.13862
  Regression -> MSE: 0.000248, MAE: 0.011624, R²: -0.0276
  Directional -> Accuracy: 0.5714, MCC: 0.0000, F1: 0.0000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.08618 | val 0.13701
  Epoch 020 - train 0.08543 | val 0.13862
  Epoch 030 - train 0.08199 | val 0.14139
  Regression -> MSE: 0.000405, MAE: 0.015528, R²: -0.3029
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.10030 | val 0.12154
  Epoch 020 - train 0.09711 | val 0.13622
  Epoch 021 - train 0.09892 | val 0.13742
  Regression -> MSE: 0.000679, MAE: 0.019622, R²: -0.0026
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.09164 | val 0.10575
  Epoch 020 - train 0.08994 | val 0.11847
  Epoch 021 - train 0.08900 | val 0.11786
  Regression -> MSE: 0.000138, MAE: 0.009036, R²: -0.0017
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.08860 | val 0.14042
  Epoch 020 - train 0.09057 | val 0.14143
  Epoch 021 - train 0.08973 | val 0.14107
  Regression -> MSE: 0.000225, MAE: 0.010718, R²: -0.0017
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.09633 | val 0.20426
  Epoch 020 - train 0.09433 | val 0.20767
  Epoch 021 - train 0.09463 | val 0.20770
  Regression -> MSE: 0.000362, MAE: 0.016174, R²: -0.0003
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.09970 | val 0.10121
  Epoch 020 - train 0.09875 | val 0.10060
  Epoch 021 - train 0.09839 | val 0.10032
  Regression -> MSE: 0.000110, MAE: 0.007956, R²: -0.0217
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.09330 | val 0.17295
  Epoch 020 - train 0.09157 | val 0.18056
  Epoch 021 - train 0.09266 | val 0.18015
  Regression -> MSE: 0.000156, MAE: 0.009547, R²: -0.0025
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10049 | val 0.10824
  Epoch 020 - train 0.09811 | val 0.10635
  Epoch 021 - train 0.09870 | val 0.10571
  Regression -> MSE: 0.000274, MAE: 0.012925, R²: -0.0052
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.08720 | val 0.14713
  Epoch 020 - train 0.08587 | val 0.14815
  Epoch 021 - train 0.08470 | val 0.14785
  Regression -> MSE: 0.000171, MAE: 0.009205, R²: -0.1400
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10027 | val 0.13934
  Epoch 020 - train 0.09553 | val 0.13469
  Epoch 021 - train 0.09480 | val 0.13445
  Regression -> MSE: 0.000230, MAE: 0.010890, R²: -0.0150
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.09759 | val 0.12192
  Epoch 020 - train 0.09395 | val 0.12597
  Epoch 021 - train 0.09729 | val 0.12601
  Regression -> MSE: 0.000143, MAE: 0.008295, R²: 0.0009
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.09893 | val 0.11248
  Epoch 020 - train 0.09092 | val 0.11435
  Epoch 021 - train 0.09175 | val 0.11426
  Regression -> MSE: 0.000184, MAE: 0.010369, R²: -0.1121
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.10037 | val 0.11321
  Epoch 020 - train 0.09732 | val 0.11250
  Epoch 021 - train 0.09793 | val 0.11265
  Regression -> MSE: 0.000090, MAE: 0.007309, R²: -0.0569
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.09350 | val 0.12160
  Epoch 020 - train 0.09256 | val 0.12156
  Epoch 021 - train 0.09301 | val 0.12148
  Regression -> MSE: 0.000212, MAE: 0.011149, R²: -0.0030
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.09016 | val 0.08891
  Epoch 020 - train 0.08807 | val 0.08947
  Epoch 021 - train 0.08715 | val 0.08923
  Regression -> MSE: 0.000094, MAE: 0.008101, R²: -0.0177
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.10144 | val 0.07890
  Epoch 020 - train 0.09947 | val 0.07815
  Epoch 021 - train 0.09638 | val 0.07821
  Regression -> MSE: 0.000108, MAE: 0.008964, R²: -0.0481
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10490 | val 0.09570
  Epoch 020 - train 0.10023 | val 0.10124
  Epoch 021 - train 0.10109 | val 0.10140
  Regression -> MSE: 0.000232, MAE: 0.012546, R²: -0.0023
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.09912 | val 0.13308
  Epoch 020 - train 0.09840 | val 0.13569
  Epoch 021 - train 0.09620 | val 0.13579
  Regression -> MSE: 0.000172, MAE: 0.007831, R²: -0.0330
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.10441 | val 0.08572
  Epoch 020 - train 0.10265 | val 0.10161
  Epoch 021 - train 0.10093 | val 0.10275
  Regression -> MSE: 0.000237, MAE: 0.011880, R²: 0.0001
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.09945 | val 0.15501
  Epoch 020 - train 0.09344 | val 0.16232
  Epoch 021 - train 0.09574 | val 0.16238
  Regression -> MSE: 0.000230, MAE: 0.009872, R²: 0.0010
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10019 | val 0.12885
  Epoch 020 - train 0.09561 | val 0.12532
  Epoch 021 - train 0.09683 | val 0.12499
  Regression -> MSE: 0.000143, MAE: 0.008603, R²: -0.0588
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.09746 | val 0.12634
  Epoch 020 - train 0.09625 | val 0.12863
  Epoch 021 - train 0.09516 | val 0.12874
  Regression -> MSE: 0.000193, MAE: 0.010460, R²: -0.0263
  Directional -> Accuracy: 0.4200, MCC: -0.2212, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.09456 | val 0.11669
  Epoch 020 - train 0.08940 | val 0.11652
  Epoch 021 - train 0.08998 | val 0.11596
  Regression -> MSE: 0.000283, MAE: 0.011044, R²: -0.0823
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09412 | val 0.08352
  Epoch 020 - train 0.09645 | val 0.08374
  Epoch 021 - train 0.09276 | val 0.08426
  Regression -> MSE: 0.000168, MAE: 0.010365, R²: -0.0088
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.08963 | val 0.10893
  Epoch 020 - train 0.08689 | val 0.12672
  Epoch 021 - train 0.08999 | val 0.12665
  Regression -> MSE: 0.000181, MAE: 0.010271, R²: -0.0047
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.09214 | val 0.09778
  Epoch 020 - train 0.09083 | val 0.09955
  Epoch 021 - train 0.09013 | val 0.09972
  Regression -> MSE: 0.000344, MAE: 0.011778, R²: -0.0052
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.10939 | val 0.06803
  Epoch 020 - train 0.10357 | val 0.06950
  Epoch 021 - train 0.10318 | val 0.06925
  Regression -> MSE: 0.000110, MAE: 0.008306, R²: -0.0469
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.09584 | val 0.13357
  Epoch 020 - train 0.09287 | val 0.13593
  Epoch 021 - train 0.09371 | val 0.13624
  Regression -> MSE: 0.000222, MAE: 0.011402, R²: -0.0171
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.09612 | val 0.17563
  Epoch 020 - train 0.09239 | val 0.18451
  Epoch 021 - train 0.09207 | val 0.18490
  Regression -> MSE: 0.000083, MAE: 0.007105, R²: -0.0693
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.09469 | val 0.08170
  Epoch 020 - train 0.09144 | val 0.09257
  Epoch 021 - train 0.09495 | val 0.09398
  Regression -> MSE: 0.000321, MAE: 0.014547, R²: -0.0439
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.10642 | val 0.06227
  Epoch 020 - train 0.09960 | val 0.06597
  Epoch 021 - train 0.10373 | val 0.06659
  Regression -> MSE: 0.000246, MAE: 0.011544, R²: -0.0087
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.09128 | val 0.12191
  Epoch 020 - train 0.08930 | val 0.12357
  Epoch 021 - train 0.08912 | val 0.12383
  Regression -> MSE: 0.000081, MAE: 0.007095, R²: -0.0020
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.10717 | val 0.13857
  Epoch 020 - train 0.10387 | val 0.18301
  Epoch 021 - train 0.10515 | val 0.18286
  Regression -> MSE: 0.000310, MAE: 0.014482, R²: -0.0091
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.09292 | val 0.10693
  Epoch 020 - train 0.08964 | val 0.11005
  Epoch 021 - train 0.09114 | val 0.11005
  Regression -> MSE: 0.000099, MAE: 0.007235, R²: -0.0053
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.10050 | val 0.11868
  Epoch 020 - train 0.10066 | val 0.13045
  Epoch 021 - train 0.10197 | val 0.13090
  Regression -> MSE: 0.000172, MAE: 0.009699, R²: -0.0011
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 06:19:05,751] Trial 216 finished with value: -0.011453220810254194 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.1, 'batch_size': 32, 'learning_rate': 2.1239393808375718e-05, 'weight_decay': 5.985777069002685e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.14534828714070622, 'early_stopping_min_delta': 0.006746158778921624}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.09719 | val 0.14056
  Epoch 021 - train 0.09699 | val 0.14052
  Regression -> MSE: 0.000242, MAE: 0.012339, R²: -0.0216
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15940 | val 0.21694
  Epoch 020 - train 0.15688 | val 0.21865
  Regression -> MSE: 0.000247, MAE: 0.012480, R²: 0.0010
  Directional -> Accuracy: 0.5455, MCC: 0.0000, F1: 0.0000

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.14802 | val 0.15370
  Epoch 020 - train 0.15011 | val 0.16735
  Regression -> MSE: 0.000696, MAE: 0.019531, R²: -0.0165
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.16033 | val 0.26040
  Epoch 020 - train 0.15733 | val 0.26124
  Regression -> MSE: 0.000310, MAE: 0.014412, R²: 0.0001
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13373 | val 0.32920
  Epoch 020 - train 0.12870 | val 0.36263
  Regression -> MSE: 0.000369, MAE: 0.014894, R²: -0.0575
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15834 | val 0.16214
  Epoch 020 - train 0.15960 | val 0.16422
  Regression -> MSE: 0.000208, MAE: 0.010133, R²: -0.0206
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.15673 | val 0.29280
  Epoch 020 - train 0.14732 | val 0.29907
  Regression -> MSE: 0.000562, MAE: 0.018196, R²: -0.0125
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15733 | val 0.19378
  Epoch 020 - train 0.15679 | val 0.19498
  Regression -> MSE: 0.000246, MAE: 0.011958, R²: -0.0026
  Directional -> Accuracy: 0.5362, MCC: 0.0046, F1: 0.3600

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.16033 | val 0.18311
  Epoch 020 - train 0.15553 | val 0.17592
  Regression -> MSE: 0.000609, MAE: 0.019505, R²: -0.0201
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14989 | val 0.19071
  Epoch 020 - train 0.15210 | val 0.20558
  Regression -> MSE: 0.000401, MAE: 0.016056, R²: -0.0444
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15339 | val 0.22322
  Epoch 020 - train 0.14719 | val 0.22141
  Regression -> MSE: 0.000242, MAE: 0.011962, R²: -0.0016
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.15566 | val 0.21467
  Epoch 020 - train 0.14736 | val 0.21890
  Regression -> MSE: 0.000360, MAE: 0.014114, R²: -0.1588
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.15592 | val 0.19590
  Epoch 020 - train 0.15491 | val 0.21464
  Regression -> MSE: 0.000679, MAE: 0.019578, R²: -0.0025
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.17069 | val 0.16119
  Epoch 020 - train 0.15326 | val 0.16375
  Regression -> MSE: 0.000140, MAE: 0.009154, R²: -0.0097
  Directional -> Accuracy: 0.5581, MCC: 0.2275, F1: 0.6415

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14062 | val 0.22800
  Epoch 020 - train 0.14251 | val 0.22862
  Regression -> MSE: 0.000225, MAE: 0.010745, R²: 0.0008
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15225 | val 0.32153
  Epoch 020 - train 0.15174 | val 0.31944
  Regression -> MSE: 0.000362, MAE: 0.016184, R²: -0.0006
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.16872 | val 0.17021
  Epoch 020 - train 0.16383 | val 0.17520
  Regression -> MSE: 0.000112, MAE: 0.007975, R²: -0.0352
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.16292 | val 0.26796
  Epoch 020 - train 0.15844 | val 0.28162
  Regression -> MSE: 0.000166, MAE: 0.010376, R²: -0.0647
  Directional -> Accuracy: 0.3729, MCC: 0.0000, F1: 0.0000

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.15785 | val 0.17105
  Epoch 020 - train 0.15591 | val 0.17106
  Regression -> MSE: 0.000282, MAE: 0.013511, R²: -0.0347
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.13690 | val 0.22044
  Epoch 020 - train 0.13935 | val 0.21748
  Regression -> MSE: 0.000162, MAE: 0.008958, R²: -0.0821
  Directional -> Accuracy: 0.4462, MCC: -0.0256, F1: 0.3333

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15282 | val 0.22996
  Epoch 020 - train 0.15801 | val 0.23164
  Regression -> MSE: 0.000233, MAE: 0.010934, R²: -0.0284
  Directional -> Accuracy: 0.4800, MCC: -0.1205, F1: 0.6139

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.15249 | val 0.20325
  Epoch 020 - train 0.15320 | val 0.22753
  Regression -> MSE: 0.000145, MAE: 0.008467, R²: -0.0117
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14273 | val 0.19294
  Epoch 020 - train 0.14820 | val 0.19594
  Regression -> MSE: 0.000173, MAE: 0.010262, R²: -0.0464
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.16068 | val 0.18695
  Epoch 020 - train 0.15690 | val 0.18874
  Regression -> MSE: 0.000085, MAE: 0.007032, R²: 0.0026
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15607 | val 0.19736
  Epoch 020 - train 0.14957 | val 0.21304
  Regression -> MSE: 0.000212, MAE: 0.011113, R²: -0.0008
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.14656 | val 0.14503
  Epoch 020 - train 0.14364 | val 0.14241
  Regression -> MSE: 0.000100, MAE: 0.008206, R²: -0.0836
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16255 | val 0.13890
  Epoch 020 - train 0.15682 | val 0.18049
  Regression -> MSE: 0.000115, MAE: 0.009186, R²: -0.1156
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.15446 | val 0.16127
  Epoch 020 - train 0.16187 | val 0.20086
  Regression -> MSE: 0.000232, MAE: 0.012574, R²: -0.0028
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.15167 | val 0.18303
  Epoch 020 - train 0.15055 | val 0.18196
  Regression -> MSE: 0.000279, MAE: 0.011788, R²: -0.6794
  Directional -> Accuracy: 0.4561, MCC: 0.1181, F1: 0.0606

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16337 | val 0.13718
  Epoch 020 - train 0.15884 | val 0.13889
  Regression -> MSE: 0.000238, MAE: 0.011920, R²: -0.0061
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.15586 | val 0.25725
  Epoch 020 - train 0.15240 | val 0.25605
  Regression -> MSE: 0.000234, MAE: 0.010153, R²: -0.0175
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.16397 | val 0.18906
  Epoch 020 - train 0.16668 | val 0.18053
  Regression -> MSE: 0.000139, MAE: 0.008308, R²: -0.0331
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.16325 | val 0.20185
  Epoch 020 - train 0.16183 | val 0.20608
  Regression -> MSE: 0.000200, MAE: 0.010720, R²: -0.0623
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.14012 | val 0.19335
  Epoch 020 - train 0.13700 | val 0.18700
  Regression -> MSE: 0.000263, MAE: 0.010518, R²: -0.0038
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.14516 | val 0.13216
  Epoch 020 - train 0.13512 | val 0.13288
  Regression -> MSE: 0.000166, MAE: 0.010359, R²: 0.0049
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13657 | val 0.15973
  Epoch 020 - train 0.13936 | val 0.16286
  Regression -> MSE: 0.000181, MAE: 0.010367, R²: -0.0055
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.15263 | val 0.15375
  Epoch 020 - train 0.14718 | val 0.15478
  Regression -> MSE: 0.000348, MAE: 0.011742, R²: -0.0166
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16386 | val 0.10002
  Epoch 020 - train 0.16545 | val 0.11599
  Regression -> MSE: 0.000125, MAE: 0.008464, R²: -0.1905
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16047 | val 0.21247
  Epoch 020 - train 0.15526 | val 0.21281
  Regression -> MSE: 0.000219, MAE: 0.011285, R²: -0.0030
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.15216 | val 0.27444
  Epoch 020 - train 0.15110 | val 0.27334
  Regression -> MSE: 0.000082, MAE: 0.007051, R²: -0.0537
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.15492 | val 0.12514
  Epoch 020 - train 0.15809 | val 0.13785
  Regression -> MSE: 0.000321, MAE: 0.014558, R²: -0.0425
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.16701 | val 0.10281
  Epoch 020 - train 0.16171 | val 0.10125
  Regression -> MSE: 0.000263, MAE: 0.011525, R²: -0.0797
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.14839 | val 0.18951
  Epoch 020 - train 0.14598 | val 0.19221
  Regression -> MSE: 0.000081, MAE: 0.007093, R²: 0.0000
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.16168 | val 0.20309
  Epoch 020 - train 0.16103 | val 0.21553
  Regression -> MSE: 0.000308, MAE: 0.014467, R²: -0.0026
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.15686 | val 0.17251
  Epoch 020 - train 0.15447 | val 0.15531
  Regression -> MSE: 0.000097, MAE: 0.007169, R²: 0.0093
  Directional -> Accuracy: 0.6136, MCC: 0.1873, F1: 0.7018

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16587 | val 0.18565
  Epoch 020 - train 0.16528 | val 0.18713
  Regression -> MSE: 0.000172, MAE: 0.009764, R²: 0.0009
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.14588 | val 0.17738
  Epoch 020 - train 0.14268 | val 0.17677
  Regression -> MSE: 0.000225, MAE: 0.011827, R²: -0.0090
  Directional -> Accuracy: 0.5357, MCC: 0.0000, F1: 0.6977

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.15445 | val 0.18843
  Epoch 020 - train 0.15352 | val 0.19240
  Regression -> MSE: 0.000098, MAE: 0.008020, R²: -0.0617
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.16226 | val 0.25898
  Epoch 020 - train 0.15349 | val 0.26938
  Regression -> MSE: 0.000166, MAE: 0.010283, R²: -0.0111
  Directional -> Accuracy: 0.4815, MCC: 0.0000, F1: 0.0000

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.16778 | val 0.23768
  Epoch 020 - train 0.16846 | val 0.25179
  Regression -> MSE: 0.000137, MAE: 0.009248, R²: -0.1782
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...
  Epoch 010 - train 0.15233 | val 0.26480

[I 2026-02-24 06:21:54,091] Trial 217 finished with value: -0.011530599553417991 and parameters: {'feature_set': 'finbert', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 256, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.2, 'batch_size': 32, 'learning_rate': 7.439579235676196e-06, 'weight_decay': 7.2211528967830665e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 20, 'huber_delta': 0.24387015834366296, 'early_stopping_min_delta': 0.004761107658742495}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.15711 | val 0.27571
  Regression -> MSE: 0.000236, MAE: 0.012404, R²: 0.0039
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with BiGRU model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.27137 | val 0.37730
  Epoch 011 - train 0.26890 | val 0.38368
  Regression -> MSE: 0.000258, MAE: 0.012956, R²: -0.0424
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.26694 | val 0.21872
  Epoch 011 - train 0.25852 | val 0.21958
  Regression -> MSE: 0.000686, MAE: 0.019362, R²: -0.0024
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.28497 | val 0.39583
  Epoch 011 - train 0.27307 | val 0.39544
  Regression -> MSE: 0.000310, MAE: 0.014396, R²: 0.0018
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.22795 | val 0.22430
  Epoch 011 - train 0.23139 | val 0.22767
  Regression -> MSE: 0.000349, MAE: 0.014597, R²: 0.0017
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.27110 | val 0.23975
  Epoch 011 - train 0.26240 | val 0.24006
  Regression -> MSE: 0.000212, MAE: 0.010248, R²: -0.0406
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.28211 | val 0.45514
  Epoch 011 - train 0.25497 | val 0.45469
  Regression -> MSE: 0.000560, MAE: 0.018179, R²: -0.0082
  Directional -> Accuracy: 0.4681, MCC: -0.1036, F1: 0.1935

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.25762 | val 0.29828
  Epoch 011 - train 0.26805 | val 0.29852
  Regression -> MSE: 0.000249, MAE: 0.012350, R²: -0.0133
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.27906 | val 0.30814
  Epoch 011 - train 0.28801 | val 0.30913
  Regression -> MSE: 0.000617, MAE: 0.019684, R²: -0.0334
  Directional -> Accuracy: 0.4318, MCC: 0.1269, F1: 0.5902

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.24492 | val 0.28233
  Epoch 011 - train 0.26193 | val 0.28223
  Regression -> MSE: 0.000398, MAE: 0.016016, R²: -0.0375
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.26050 | val 0.30638
  Epoch 011 - train 0.27901 | val 0.30587
  Regression -> MSE: 0.000243, MAE: 0.011701, R²: -0.0061
  Directional -> Accuracy: 0.5857, MCC: 0.1154, F1: 0.3830

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.24970 | val 0.37358
  Epoch 011 - train 0.25567 | val 0.37502
  Regression -> MSE: 0.000312, MAE: 0.013859, R²: -0.0022
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.6301

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.27045 | val 0.27619
  Epoch 011 - train 0.27458 | val 0.27725
  Regression -> MSE: 0.000676, MAE: 0.019520, R²: 0.0023
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.24983 | val 0.24873
  Epoch 011 - train 0.28036 | val 0.24901
  Regression -> MSE: 0.000139, MAE: 0.009030, R²: -0.0054
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.25349 | val 0.31035
  Epoch 016 - train 0.25373 | val 0.31056
  Regression -> MSE: 0.000223, MAE: 0.010692, R²: 0.0083
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.28324 | val 0.51081
  Epoch 011 - train 0.27276 | val 0.51166
  Regression -> MSE: 0.000366, MAE: 0.016333, R²: -0.0109
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.25770 | val 0.23858
  Epoch 011 - train 0.27573 | val 0.23957
  Regression -> MSE: 0.000108, MAE: 0.007965, R²: 0.0001
  Directional -> Accuracy: 0.5857, MCC: 0.1721, F1: 0.7129

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.25976 | val 0.40513
  Epoch 011 - train 0.25869 | val 0.40840
  Regression -> MSE: 0.000153, MAE: 0.009507, R²: 0.0174
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.27018 | val 0.26939
  Epoch 011 - train 0.27702 | val 0.27436
  Regression -> MSE: 0.000279, MAE: 0.012966, R²: -0.0235
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.24766 | val 0.30491
  Epoch 018 - train 0.24947 | val 0.30282
  Regression -> MSE: 0.000170, MAE: 0.009498, R²: -0.1390
  Directional -> Accuracy: 0.4923, MCC: -0.1193, F1: 0.6207

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.28057 | val 0.36548
  Epoch 011 - train 0.27665 | val 0.36591
  Regression -> MSE: 0.000246, MAE: 0.011256, R²: -0.0873
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.27014 | val 0.29690
  Epoch 011 - train 0.26102 | val 0.29717
  Regression -> MSE: 0.000147, MAE: 0.008561, R²: -0.0250
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.26033 | val 0.28545
  Epoch 011 - train 0.25342 | val 0.28619
  Regression -> MSE: 0.000174, MAE: 0.010248, R²: -0.0537
  Directional -> Accuracy: 0.5152, MCC: 0.1240, F1: 0.0588

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.29022 | val 0.29969
  Epoch 011 - train 0.29184 | val 0.30032
  Regression -> MSE: 0.000095, MAE: 0.007494, R²: -0.1098
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.25671 | val 0.28632
  Epoch 011 - train 0.25648 | val 0.28634
  Regression -> MSE: 0.000212, MAE: 0.011232, R²: -0.0030
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.23964 | val 0.20533
  Epoch 011 - train 0.23586 | val 0.20428
  Regression -> MSE: 0.000093, MAE: 0.008091, R²: -0.0058
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.26725 | val 0.19043
  Epoch 011 - train 0.27158 | val 0.19154
  Regression -> MSE: 0.000108, MAE: 0.008963, R²: -0.0494
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.27882 | val 0.22224
  Epoch 011 - train 0.25762 | val 0.22248
  Regression -> MSE: 0.000232, MAE: 0.012600, R²: -0.0041
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.25951 | val 0.28783
  Epoch 011 - train 0.26967 | val 0.28824
  Regression -> MSE: 0.000172, MAE: 0.007803, R²: -0.0331
  Directional -> Accuracy: 0.5614, MCC: 0.0841, F1: 0.6479

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.28163 | val 0.20217
  Epoch 011 - train 0.29084 | val 0.20312
  Regression -> MSE: 0.000237, MAE: 0.011892, R²: -0.0040
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.25219 | val 0.39086
  Epoch 011 - train 0.28721 | val 0.39158
  Regression -> MSE: 0.000229, MAE: 0.009868, R²: 0.0044
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.27533 | val 0.29705
  Epoch 019 - train 0.28260 | val 0.29189
  Regression -> MSE: 0.000143, MAE: 0.008345, R²: -0.0597
  Directional -> Accuracy: 0.4651, MCC: -0.0435, F1: 0.3429

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.27414 | val 0.30168
  Epoch 011 - train 0.25493 | val 0.30211
  Regression -> MSE: 0.000194, MAE: 0.010503, R²: -0.0327
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.22944 | val 0.27521
  Epoch 011 - train 0.23177 | val 0.27732
  Regression -> MSE: 0.000271, MAE: 0.010636, R²: -0.0356
  Directional -> Accuracy: 0.4384, MCC: -0.2255, F1: 0.5773

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.27087 | val 0.19620
  Epoch 011 - train 0.21891 | val 0.19660
  Regression -> MSE: 0.000169, MAE: 0.010345, R²: -0.0130
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.23125 | val 0.23530
  Epoch 011 - train 0.27060 | val 0.23546
  Regression -> MSE: 0.000181, MAE: 0.010271, R²: -0.0049
  Directional -> Accuracy: 0.4318, MCC: -0.2471, F1: 0.0741

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.27556 | val 0.26166
  Epoch 011 - train 0.26612 | val 0.26463
  Regression -> MSE: 0.000370, MAE: 0.013349, R²: -0.0790
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.28406 | val 0.14334
  Epoch 011 - train 0.27541 | val 0.14318
  Regression -> MSE: 0.000113, MAE: 0.008319, R²: -0.0720
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.28538 | val 0.34189
  Epoch 011 - train 0.27586 | val 0.34378
  Regression -> MSE: 0.000222, MAE: 0.011414, R²: -0.0174
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.29849 | val 0.41056
  Epoch 011 - train 0.25555 | val 0.41025
  Regression -> MSE: 0.000091, MAE: 0.007460, R²: -0.1724
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.26418 | val 0.18653
  Epoch 011 - train 0.25322 | val 0.18645
  Regression -> MSE: 0.000324, MAE: 0.014689, R²: -0.0527
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.28350 | val 0.13548
  Epoch 011 - train 0.31197 | val 0.13620
  Regression -> MSE: 0.000246, MAE: 0.011544, R²: -0.0089
  Directional -> Accuracy: 0.3947, MCC: -0.2544, F1: 0.0800

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.27658 | val 0.29144
  Epoch 011 - train 0.27974 | val 0.29227
  Regression -> MSE: 0.000084, MAE: 0.007056, R²: -0.0413
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.25229 | val 0.28437
  Epoch 011 - train 0.27197 | val 0.28378
  Regression -> MSE: 0.000309, MAE: 0.014507, R²: -0.0065
  Directional -> Accuracy: 0.4894, MCC: -0.1443, F1: 0.6571

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.22421 | val 0.24872
  Epoch 011 - train 0.22731 | val 0.24867
  Regression -> MSE: 0.000098, MAE: 0.007293, R²: 0.0018
  Directional -> Accuracy: 0.5000, MCC: 0.2358, F1: 0.2143

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.29330 | val 0.29582
  Epoch 011 - train 0.28150 | val 0.29664
  Regression -> MSE: 0.000173, MAE: 0.009706, R²: -0.0049
  Directional -> Accuracy: 0.4082, MCC: -0.0552, F1: 0.5085

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.25861 | val 0.28413
  Epoch 011 - train 0.25725 | val 0.28561
  Regression -> MSE: 0.000227, MAE: 0.011904, R²: -0.0177
  Directional -> Accuracy: 0.3929, MCC: -0.2067, F1: 0.2273

[85/88] Processing VZ...

Processing VZ (Technology)...
  Epoch 010 - train 0.27651 | val 0.25086
  Epoch 011 - train 0.28385 | val 0.25066
  Regression -> MSE: 0.000092, MAE: 0.007602, R²: 0.0025
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[86/88] Processing WFC...

Processing WFC (Financial)...
  Epoch 010 - train 0.28524 | val 0.37585
  Epoch 011 - train 0.26764 | val 0.37641
  Regression -> MSE: 0.000165, MAE: 0.010281, R²: -0.0052
  Directional -> Accuracy: 0.5000, MCC: -0.0409, F1: 0.6400

[87/88] Processing WMT...

Processing WMT (Services)...
  Epoch 010 - train 0.26008 | val 0.30054
  Epoch 011 - train 0.27851 | val 0.30362
  Regression -> MSE: 0.000132, MAE: 0.009145, R²: -0.1420
  Directional -> Accuracy: 0.4821, MCC: 0.0000, F1: 0.0000

[88/88] Processing XOM...

Processing XOM (Basic Matierials)...

[I 2026-02-24 06:23:10,871] Trial 218 finished with value: -0.011472356817131737 and parameters: {'feature_set': 'finbert', 'model_type': 'BiGRU', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.4, 'dropout': 0.8, 'batch_size': 64, 'learning_rate': 8.830921456459092e-06, 'weight_decay': 0.00024383152938293342, 'lr_patience': 5, 'lr_factor': 0.4, 'early_stopping_patience': 10, 'max_epochs': 30, 'huber_delta': 0.4023840644314976, 'early_stopping_min_delta': 0.007311150950205091}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 010 - train 0.28147 | val 0.34136
  Epoch 011 - train 0.27317 | val 0.34153
  Regression -> MSE: 0.000238, MAE: 0.012380, R²: -0.0021
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11989 | val 0.15510
  Epoch 020 - train 0.12593 | val 0.15519
  Epoch 021 - train 0.11530 | val 0.15556
  Regression -> MSE: 0.000248, MAE: 0.012537, R²: -0.0005
  Directional -> Accuracy: 0.5195, MCC: -0.0327, F1: 0.2128

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.12642 | val 0.12057
  Epoch 020 - train 0.11438 | val 0.14377
  Epoch 021 - train 0.12048 | val 0.14368
  Regression -> MSE: 0.000686, MAE: 0.019363, R²: -0.0018
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12110 | val 0.17723
  Epoch 020 - train 0.11884 | val 0.17803
  Epoch 021 - train 0.12142 | val 0.17802
  Regression -> MSE: 0.000314, MAE: 0.014439, R²: -0.0117
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.10750 | val 0.09498
  Epoch 020 - train 0.10577 | val 0.09581
  Epoch 021 - train 0.10748 | val 0.09490
  Regression -> MSE: 0.000359, MAE: 0.014743, R²: -0.0266
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12567 | val 0.11118
  Epoch 020 - train 0.12247 | val 0.11279
  Epoch 021 - train 0.13053 | val 0.11294
  Regression -> MSE: 0.000206, MAE: 0.010430, R²: -0.0138
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.11207 | val 0.20047
  Epoch 020 - train 0.12438 | val 0.20353
  Epoch 021 - train 0.12055 | val 0.20326
  Regression -> MSE: 0.000561, MAE: 0.018195, R²: -0.0112
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.12050 | val 0.13501
  Epoch 020 - train 0.11571 | val 0.13498
  Epoch 021 - train 0.11596 | val 0.13505
  Regression -> MSE: 0.000248, MAE: 0.011941, R²: -0.0116
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12992 | val 0.13676
  Epoch 020 - train 0.12752 | val 0.12343
  Epoch 030 - train 0.12191 | val 0.12251
  Regression -> MSE: 0.000586, MAE: 0.018990, R²: 0.0196
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12106 | val 0.13806
  Epoch 020 - train 0.11664 | val 0.13878
  Epoch 021 - train 0.11599 | val 0.13875
  Regression -> MSE: 0.000385, MAE: 0.016139, R²: -0.0036
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12980 | val 0.16311
  Epoch 020 - train 0.12626 | val 0.16732
  Epoch 021 - train 0.12604 | val 0.16830
  Regression -> MSE: 0.000243, MAE: 0.011678, R²: -0.0045
  Directional -> Accuracy: 0.5429, MCC: 0.0189, F1: 0.3333

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12729 | val 0.16254
  Epoch 020 - train 0.11316 | val 0.16603
  Epoch 021 - train 0.12530 | val 0.16665
  Regression -> MSE: 0.000315, MAE: 0.013596, R²: -0.0140
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.12332 | val 0.12857
  Epoch 020 - train 0.12570 | val 0.12947
  Epoch 021 - train 0.12916 | val 0.12961
  Regression -> MSE: 0.000678, MAE: 0.019496, R²: -0.0016
  Directional -> Accuracy: 0.4828, MCC: -0.1325, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.12881 | val 0.10837
  Epoch 020 - train 0.12087 | val 0.11402
  Epoch 021 - train 0.12411 | val 0.11419
  Regression -> MSE: 0.000141, MAE: 0.009328, R²: -0.0182
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11915 | val 0.14785
  Epoch 020 - train 0.11497 | val 0.14726
  Epoch 021 - train 0.11155 | val 0.14728
  Regression -> MSE: 0.000227, MAE: 0.010890, R²: -0.0081
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.11794 | val 0.21379
  Epoch 020 - train 0.11864 | val 0.21371
  Epoch 021 - train 0.11875 | val 0.21367
  Regression -> MSE: 0.000364, MAE: 0.015986, R²: -0.0064
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13523 | val 0.10705
  Epoch 020 - train 0.12647 | val 0.10584
  Epoch 021 - train 0.12693 | val 0.10604
  Regression -> MSE: 0.000109, MAE: 0.007966, R²: -0.0078
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12090 | val 0.17942
  Epoch 020 - train 0.11863 | val 0.18453
  Epoch 021 - train 0.12144 | val 0.18412
  Regression -> MSE: 0.000161, MAE: 0.010144, R²: -0.0318
  Directional -> Accuracy: 0.4576, MCC: 0.1322, F1: 0.3043

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12609 | val 0.11256
  Epoch 020 - train 0.12943 | val 0.11283
  Epoch 021 - train 0.12243 | val 0.11274
  Regression -> MSE: 0.000274, MAE: 0.013101, R²: -0.0054
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11125 | val 0.15006
  Epoch 020 - train 0.11550 | val 0.15039
  Epoch 021 - train 0.11228 | val 0.15061
  Regression -> MSE: 0.000165, MAE: 0.009059, R²: -0.1017
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.12079 | val 0.16988
  Epoch 020 - train 0.12482 | val 0.17142
  Epoch 021 - train 0.12409 | val 0.17127
  Regression -> MSE: 0.000229, MAE: 0.010904, R²: -0.0132
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12169 | val 0.14106
  Epoch 020 - train 0.12238 | val 0.14260
  Epoch 021 - train 0.13329 | val 0.14279
  Regression -> MSE: 0.000143, MAE: 0.008301, R²: 0.0010
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11606 | val 0.14034
  Epoch 020 - train 0.11540 | val 0.14152
  Epoch 021 - train 0.11392 | val 0.14173
  Regression -> MSE: 0.000167, MAE: 0.010331, R²: -0.0116
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13482 | val 0.13420
  Epoch 020 - train 0.12216 | val 0.13504
  Epoch 021 - train 0.13694 | val 0.13517
  Regression -> MSE: 0.000092, MAE: 0.007397, R²: -0.0831
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12084 | val 0.14005
  Epoch 020 - train 0.12090 | val 0.13906
  Epoch 021 - train 0.12275 | val 0.13992
  Regression -> MSE: 0.000213, MAE: 0.011092, R²: -0.0041
  Directional -> Accuracy: 0.5152, MCC: 0.0421, F1: 0.5429

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11642 | val 0.09684
  Epoch 020 - train 0.10675 | val 0.09724
  Epoch 021 - train 0.12117 | val 0.09734
  Regression -> MSE: 0.000098, MAE: 0.008172, R²: -0.0622
  Directional -> Accuracy: 0.5357, MCC: 0.0464, F1: 0.6061

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13633 | val 0.08586
  Epoch 020 - train 0.14587 | val 0.12238
  Epoch 021 - train 0.13118 | val 0.12673
  Regression -> MSE: 0.000107, MAE: 0.008921, R²: -0.0350
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.12781 | val 0.10482
  Epoch 020 - train 0.13687 | val 0.10836
  Epoch 021 - train 0.12403 | val 0.10877
  Regression -> MSE: 0.000232, MAE: 0.012544, R²: -0.0009
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12661 | val 0.12064
  Epoch 020 - train 0.12638 | val 0.11945
  Epoch 028 - train 0.12171 | val 0.11965
  Regression -> MSE: 0.000188, MAE: 0.007994, R²: -0.1274
  Directional -> Accuracy: 0.4912, MCC: 0.0739, F1: 0.3256

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.12444 | val 0.09328
  Epoch 020 - train 0.11528 | val 0.09320
  Epoch 021 - train 0.11500 | val 0.09303
  Regression -> MSE: 0.000237, MAE: 0.011868, R²: -0.0005
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12271 | val 0.17189
  Epoch 020 - train 0.12934 | val 0.18325
  Epoch 021 - train 0.12831 | val 0.18299
  Regression -> MSE: 0.000231, MAE: 0.009882, R²: -0.0011
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12621 | val 0.13104
  Epoch 020 - train 0.12023 | val 0.13117
  Epoch 021 - train 0.11764 | val 0.13113
  Regression -> MSE: 0.000136, MAE: 0.008265, R²: -0.0073
  Directional -> Accuracy: 0.5349, MCC: 0.0000, F1: 0.6970

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.13069 | val 0.14212
  Epoch 020 - train 0.12677 | val 0.14487
  Epoch 021 - train 0.12187 | val 0.14513
  Regression -> MSE: 0.000189, MAE: 0.010420, R²: -0.0064
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.10991 | val 0.12296
  Epoch 020 - train 0.11194 | val 0.12202
  Epoch 021 - train 0.11345 | val 0.12260
  Regression -> MSE: 0.000270, MAE: 0.010629, R²: -0.0323
  Directional -> Accuracy: 0.4658, MCC: -0.0742, F1: 0.5063

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.10197 | val 0.09373
  Epoch 020 - train 0.11557 | val 0.10059
  Epoch 021 - train 0.12031 | val 0.10193
  Regression -> MSE: 0.000167, MAE: 0.010362, R²: 0.0010
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.11628 | val 0.10894
  Epoch 020 - train 0.11761 | val 0.11282
  Epoch 021 - train 0.11692 | val 0.11282
  Regression -> MSE: 0.000181, MAE: 0.010282, R²: -0.0057
  Directional -> Accuracy: 0.5227, MCC: 0.0000, F1: 0.0000

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12668 | val 0.10488
  Epoch 020 - train 0.11926 | val 0.10528
  Epoch 021 - train 0.11086 | val 0.10549
  Regression -> MSE: 0.000343, MAE: 0.011835, R²: -0.0005
  Directional -> Accuracy: 0.4328, MCC: -0.0759, F1: 0.2963

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13777 | val 0.07049
  Epoch 020 - train 0.13879 | val 0.06983
  Epoch 021 - train 0.12499 | val 0.06972
  Regression -> MSE: 0.000112, MAE: 0.008321, R²: -0.0695
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12435 | val 0.15433
  Epoch 020 - train 0.11122 | val 0.15552
  Epoch 021 - train 0.13063 | val 0.15523
  Regression -> MSE: 0.000222, MAE: 0.011422, R²: -0.0158
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13960 | val 0.19659
  Epoch 020 - train 0.13299 | val 0.20890
  Epoch 021 - train 0.13403 | val 0.20948
  Regression -> MSE: 0.000081, MAE: 0.007016, R²: -0.0443
  Directional -> Accuracy: 0.6170, MCC: 0.0000, F1: 0.7632

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10760 | val 0.09501
  Epoch 020 - train 0.12294 | val 0.09547
  Epoch 021 - train 0.11282 | val 0.09541
  Regression -> MSE: 0.000338, MAE: 0.015300, R²: -0.0990
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12842 | val 0.06551
  Epoch 020 - train 0.13297 | val 0.06360
  Epoch 021 - train 0.12514 | val 0.06352
  Regression -> MSE: 0.000248, MAE: 0.011556, R²: -0.0187
  Directional -> Accuracy: 0.4737, MCC: -0.0124, F1: 0.0909

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.11751 | val 0.13448
  Epoch 020 - train 0.11161 | val 0.13471
  Epoch 021 - train 0.11619 | val 0.13476
  Regression -> MSE: 0.000081, MAE: 0.007081, R²: -0.0008
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.12933 | val 0.14049
  Epoch 020 - train 0.12264 | val 0.14035
  Epoch 021 - train 0.11569 | val 0.14045
  Regression -> MSE: 0.000312, MAE: 0.014521, R²: -0.0184
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10832 | val 0.12390
  Epoch 020 - train 0.12310 | val 0.12168
  Epoch 021 - train 0.11733 | val 0.12180
  Regression -> MSE: 0.000099, MAE: 0.007147, R²: -0.0126
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13165 | val 0.12727
  Epoch 020 - train 0.13550 | val 0.13139
  Epoch 021 - train 0.13095 | val 0.13252
  Regression -> MSE: 0.000172, MAE: 0.009835, R²: -0.0036
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...


[I 2026-02-24 06:25:15,558] Trial 219 finished with value: -0.011409940943328607 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 4.2507889180979634e-06, 'weight_decay': 9.757010244593566e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.16080937586742472, 'early_stopping_min_delta': 0.007822269574014185}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.12148 | val 0.18445
  Epoch 021 - train 0.12005 | val 0.18468
  Regression -> MSE: 0.000238, MAE: 0.012354, R²: -0.0029
  Directional -> Accuracy: 0.4918, MCC: 0.1229, F1: 0.6517

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.15412 | val 0.19001
  Epoch 020 - train 0.15446 | val 0.19089
  Epoch 021 - train 0.15306 | val 0.19088
  Regression -> MSE: 0.000259, MAE: 0.012970, R²: -0.0466
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.16457 | val 0.13694
  Epoch 020 - train 0.15798 | val 0.14656
  Epoch 021 - train 0.15515 | val 0.14656
  Regression -> MSE: 0.000700, MAE: 0.019646, R²: -0.0232
  Directional -> Accuracy: 0.4130, MCC: -0.1202, F1: 0.2286

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.17152 | val 0.23515
  Epoch 020 - train 0.16865 | val 0.25753
  Epoch 021 - train 0.16199 | val 0.25757
  Regression -> MSE: 0.000326, MAE: 0.014564, R²: -0.0493
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.13740 | val 0.14750
  Epoch 020 - train 0.13505 | val 0.14288
  Epoch 021 - train 0.13644 | val 0.14256
  Regression -> MSE: 0.000349, MAE: 0.014591, R²: 0.0003
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.15706 | val 0.13694
  Epoch 020 - train 0.15738 | val 0.13687
  Epoch 021 - train 0.15205 | val 0.13677
  Regression -> MSE: 0.000203, MAE: 0.010096, R²: 0.0026
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.17078 | val 0.25366
  Epoch 020 - train 0.14289 | val 0.25180
  Epoch 030 - train 0.14577 | val 0.25310
  Regression -> MSE: 0.000586, MAE: 0.018814, R²: -0.0558
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.15375 | val 0.16903
  Epoch 020 - train 0.16519 | val 0.16986
  Epoch 021 - train 0.16509 | val 0.16984
  Regression -> MSE: 0.000246, MAE: 0.012084, R²: -0.0006
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.15558 | val 0.16702
  Epoch 020 - train 0.14982 | val 0.18971
  Epoch 021 - train 0.15885 | val 0.19204
  Regression -> MSE: 0.000605, MAE: 0.019339, R²: -0.0124
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.14652 | val 0.16317
  Epoch 020 - train 0.15552 | val 0.16585
  Epoch 021 - train 0.15253 | val 0.16595
  Regression -> MSE: 0.000397, MAE: 0.016011, R²: -0.0358
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.15052 | val 0.17883
  Epoch 020 - train 0.16000 | val 0.17938
  Epoch 021 - train 0.14337 | val 0.17938
  Regression -> MSE: 0.000241, MAE: 0.011836, R²: 0.0010
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.14935 | val 0.19998
  Epoch 020 - train 0.14816 | val 0.20456
  Epoch 021 - train 0.13917 | val 0.20461
  Regression -> MSE: 0.000312, MAE: 0.013683, R²: -0.0029
  Directional -> Accuracy: 0.4400, MCC: -0.1048, F1: 0.6000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.17019 | val 0.17953
  Epoch 020 - train 0.16333 | val 0.19091
  Epoch 021 - train 0.16273 | val 0.19093
  Regression -> MSE: 0.000676, MAE: 0.019454, R²: 0.0014
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.16214 | val 0.14850
  Epoch 020 - train 0.15792 | val 0.15394
  Epoch 021 - train 0.16103 | val 0.15401
  Regression -> MSE: 0.000139, MAE: 0.009043, R²: -0.0029
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.14994 | val 0.16806
  Epoch 020 - train 0.14561 | val 0.16930
  Epoch 027 - train 0.13891 | val 0.16930
  Regression -> MSE: 0.000230, MAE: 0.010963, R²: -0.0208
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.15353 | val 0.29427
  Epoch 020 - train 0.15056 | val 0.32623
  Epoch 021 - train 0.14598 | val 0.32621
  Regression -> MSE: 0.000365, MAE: 0.015986, R²: -0.0076
  Directional -> Accuracy: 0.5385, MCC: 0.0000, F1: 0.0000

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.15831 | val 0.14031
  Epoch 020 - train 0.15499 | val 0.14097
  Epoch 021 - train 0.15037 | val 0.14095
  Regression -> MSE: 0.000111, MAE: 0.007960, R²: -0.0294
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.14957 | val 0.24724
  Epoch 020 - train 0.14865 | val 0.26133
  Epoch 021 - train 0.14716 | val 0.26146
  Regression -> MSE: 0.000157, MAE: 0.009835, R²: -0.0040
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.16726 | val 0.14475
  Epoch 020 - train 0.16129 | val 0.14494
  Epoch 021 - train 0.16800 | val 0.14491
  Regression -> MSE: 0.000278, MAE: 0.013362, R²: -0.0233
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.14954 | val 0.18567
  Epoch 020 - train 0.13628 | val 0.18644
  Epoch 021 - train 0.13707 | val 0.18643
  Regression -> MSE: 0.000156, MAE: 0.008793, R²: -0.0454
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.15872 | val 0.19579
  Epoch 020 - train 0.15967 | val 0.19506
  Epoch 021 - train 0.15393 | val 0.19503
  Regression -> MSE: 0.000226, MAE: 0.010902, R²: 0.0006
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.17476 | val 0.18984
  Epoch 020 - train 0.15765 | val 0.20887
  Epoch 021 - train 0.16465 | val 0.20886
  Regression -> MSE: 0.000144, MAE: 0.008343, R²: -0.0050
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.14622 | val 0.16047
  Epoch 020 - train 0.15157 | val 0.15966
  Epoch 021 - train 0.14761 | val 0.15957
  Regression -> MSE: 0.000169, MAE: 0.010259, R²: -0.0222
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.17276 | val 0.17462
  Epoch 020 - train 0.16102 | val 0.17813
  Epoch 021 - train 0.16670 | val 0.17810
  Regression -> MSE: 0.000091, MAE: 0.007354, R²: -0.0717
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.15280 | val 0.30725
  Epoch 020 - train 0.16560 | val 0.33235
  Epoch 021 - train 0.15247 | val 0.33192
  Regression -> MSE: 0.000212, MAE: 0.011185, R²: -0.0017
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.13645 | val 0.12656
  Epoch 020 - train 0.14316 | val 0.12838
  Epoch 021 - train 0.13829 | val 0.12837
  Regression -> MSE: 0.000097, MAE: 0.008142, R²: -0.0500
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.16338 | val 0.10983
  Epoch 020 - train 0.15412 | val 0.11882
  Epoch 021 - train 0.16282 | val 0.11989
  Regression -> MSE: 0.000105, MAE: 0.008842, R²: -0.0181
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.16106 | val 0.13134
  Epoch 020 - train 0.14156 | val 0.13361
  Epoch 021 - train 0.14260 | val 0.13372
  Regression -> MSE: 0.000236, MAE: 0.012733, R²: -0.0213
  Directional -> Accuracy: 0.4884, MCC: -0.0680, F1: 0.5769

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.14764 | val 0.18624
  Epoch 020 - train 0.15286 | val 0.19178
  Epoch 021 - train 0.15636 | val 0.19177
  Regression -> MSE: 0.000171, MAE: 0.007826, R²: -0.0301
  Directional -> Accuracy: 0.5614, MCC: 0.0000, F1: 0.7191

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.16819 | val 0.12826
  Epoch 020 - train 0.18321 | val 0.15063
  Epoch 021 - train 0.17500 | val 0.15155
  Regression -> MSE: 0.000241, MAE: 0.012036, R²: -0.0177
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.14748 | val 0.21884
  Epoch 020 - train 0.14048 | val 0.23059
  Epoch 021 - train 0.16141 | val 0.23117
  Regression -> MSE: 0.000232, MAE: 0.009947, R²: -0.0054
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.17854 | val 0.19389
  Epoch 020 - train 0.17888 | val 0.24222
  Epoch 021 - train 0.17668 | val 0.24355
  Regression -> MSE: 0.000146, MAE: 0.008794, R²: -0.0822
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.16543 | val 0.17838
  Epoch 020 - train 0.15388 | val 0.18177
  Epoch 021 - train 0.16084 | val 0.18179
  Regression -> MSE: 0.000197, MAE: 0.010612, R²: -0.0463
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.13569 | val 0.18192
  Epoch 020 - train 0.13950 | val 0.18275
  Epoch 021 - train 0.13599 | val 0.18268
  Regression -> MSE: 0.000280, MAE: 0.010969, R²: -0.0708
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.15215 | val 0.11862
  Epoch 020 - train 0.14021 | val 0.11513
  Epoch 021 - train 0.16183 | val 0.11506
  Regression -> MSE: 0.000167, MAE: 0.010369, R²: -0.0014
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.14993 | val 0.14021
  Epoch 020 - train 0.14481 | val 0.14657
  Epoch 021 - train 0.14737 | val 0.14650
  Regression -> MSE: 0.000184, MAE: 0.010487, R²: -0.0214
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14918 | val 0.14106
  Epoch 020 - train 0.15433 | val 0.14245
  Epoch 021 - train 0.15194 | val 0.14242
  Regression -> MSE: 0.000352, MAE: 0.012550, R²: -0.0277
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.16567 | val 0.08988
  Epoch 020 - train 0.15542 | val 0.10067
  Epoch 021 - train 0.15240 | val 0.10125
  Regression -> MSE: 0.000118, MAE: 0.008342, R²: -0.1266
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.16141 | val 0.19670
  Epoch 020 - train 0.15903 | val 0.19945
  Epoch 021 - train 0.16835 | val 0.19937
  Regression -> MSE: 0.000219, MAE: 0.011328, R²: -0.0031
  Directional -> Accuracy: 0.4561, MCC: -0.1810, F1: 0.1143

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.14906 | val 0.23670
  Epoch 020 - train 0.14771 | val 0.23671
  Epoch 021 - train 0.15654 | val 0.23681
  Regression -> MSE: 0.000084, MAE: 0.007126, R²: -0.0760
  Directional -> Accuracy: 0.5957, MCC: 0.0615, F1: 0.7164

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.17113 | val 0.10660
  Epoch 020 - train 0.15415 | val 0.10241
  Epoch 021 - train 0.15704 | val 0.10270
  Regression -> MSE: 0.000320, MAE: 0.014538, R²: -0.0417
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.17448 | val 0.08707
  Epoch 020 - train 0.18177 | val 0.09679
  Epoch 021 - train 0.17472 | val 0.09839
  Regression -> MSE: 0.000253, MAE: 0.011478, R²: -0.0392
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.15143 | val 0.18136
  Epoch 020 - train 0.15981 | val 0.18138
  Epoch 021 - train 0.15931 | val 0.18131
  Regression -> MSE: 0.000082, MAE: 0.007131, R²: -0.0098
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.15533 | val 0.17613
  Epoch 020 - train 0.15854 | val 0.16840
  Epoch 030 - train 0.14571 | val 0.16790
  Regression -> MSE: 0.000309, MAE: 0.014551, R²: -0.0087
  Directional -> Accuracy: 0.4255, MCC: -0.1506, F1: 0.4490

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.16687 | val 0.16264
  Epoch 020 - train 0.15166 | val 0.15565
  Epoch 030 - train 0.15978 | val 0.15362
  Regression -> MSE: 0.000098, MAE: 0.006925, R²: 0.0020
  Directional -> Accuracy: 0.6364, MCC: 0.2404, F1: 0.7333

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.16112 | val 0.16607
  Epoch 020 - train 0.16319 | val 0.18182
  Epoch 021 - train 0.15366 | val 0.18333
  Regression -> MSE: 0.000172, MAE: 0.009676, R²: -0.0003
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...


[I 2026-02-24 06:27:17,923] Trial 220 finished with value: -0.011452452871695799 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.0, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 3.843104874882557e-06, 'weight_decay': 9.319660239238429e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.2098276376945823, 'early_stopping_min_delta': 0.007729767193473106}. Best is trial 44 with value: -0.011362814469631832.

  Regression -> MSE: 0.000238, MAE: 0.012489, R²: -0.0034
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.11021 | val 0.13268
  Epoch 020 - train 0.10866 | val 0.13218
  Epoch 021 - train 0.10497 | val 0.13270
  Regression -> MSE: 0.000264, MAE: 0.013110, R²: -0.0671
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11098 | val 0.09114
  Epoch 020 - train 0.11249 | val 0.10185
  Epoch 021 - train 0.11164 | val 0.10216
  Regression -> MSE: 0.000714, MAE: 0.019860, R²: -0.0427
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.10834 | val 0.15497
  Epoch 020 - train 0.11379 | val 0.15686
  Epoch 021 - train 0.10941 | val 0.15668
  Regression -> MSE: 0.000319, MAE: 0.014501, R²: -0.0270
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.09441 | val 0.08356
  Epoch 020 - train 0.09089 | val 0.08299
  Epoch 021 - train 0.09056 | val 0.08372
  Regression -> MSE: 0.000377, MAE: 0.015022, R²: -0.0779
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.11422 | val 0.09769
  Epoch 020 - train 0.10759 | val 0.10359
  Epoch 021 - train 0.11275 | val 0.10391
  Regression -> MSE: 0.000204, MAE: 0.010076, R²: -0.0001
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.09675 | val 0.17380
  Epoch 020 - train 0.09690 | val 0.17567
  Epoch 021 - train 0.10015 | val 0.17597
  Regression -> MSE: 0.000568, MAE: 0.018312, R²: -0.0223
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.10842 | val 0.12357
  Epoch 020 - train 0.11230 | val 0.12345
  Epoch 021 - train 0.10326 | val 0.12361
  Regression -> MSE: 0.000247, MAE: 0.012230, R²: -0.0057
  Directional -> Accuracy: 0.4058, MCC: 0.0000, F1: 0.5773

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.11161 | val 0.12099
  Epoch 020 - train 0.10083 | val 0.15335
  Epoch 021 - train 0.11125 | val 0.15553
  Regression -> MSE: 0.000606, MAE: 0.019365, R²: -0.0138
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.10755 | val 0.11295
  Epoch 020 - train 0.09956 | val 0.11410
  Epoch 021 - train 0.10211 | val 0.11426
  Regression -> MSE: 0.000396, MAE: 0.015980, R²: -0.0318
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.11645 | val 0.15915
  Epoch 020 - train 0.11368 | val 0.16184
  Epoch 021 - train 0.11337 | val 0.16177
  Regression -> MSE: 0.000241, MAE: 0.011770, R²: 0.0026
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.10775 | val 0.14456
  Epoch 020 - train 0.10462 | val 0.15018
  Epoch 021 - train 0.10852 | val 0.15024
  Regression -> MSE: 0.000309, MAE: 0.013656, R²: 0.0049
  Directional -> Accuracy: 0.4200, MCC: -0.1405, F1: 0.5397

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.11281 | val 0.11151
  Epoch 020 - train 0.11001 | val 0.11221
  Epoch 021 - train 0.10996 | val 0.11195
  Regression -> MSE: 0.000676, MAE: 0.019507, R²: 0.0015
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.10130 | val 0.09764
  Epoch 020 - train 0.10246 | val 0.10455
  Epoch 021 - train 0.09018 | val 0.10425
  Regression -> MSE: 0.000138, MAE: 0.009154, R²: -0.0019
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.10194 | val 0.13296
  Epoch 020 - train 0.09960 | val 0.13342
  Epoch 021 - train 0.10220 | val 0.13441
  Regression -> MSE: 0.000225, MAE: 0.010833, R²: -0.0023
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.10602 | val 0.18768
  Epoch 020 - train 0.10986 | val 0.18909
  Epoch 021 - train 0.10460 | val 0.18957
  Regression -> MSE: 0.000364, MAE: 0.015977, R²: -0.0044
  Directional -> Accuracy: 0.5769, MCC: 0.1670, F1: 0.2143

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.11908 | val 0.09493
  Epoch 020 - train 0.10775 | val 0.09523
  Epoch 021 - train 0.11262 | val 0.09511
  Regression -> MSE: 0.000109, MAE: 0.008153, R²: -0.0127
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.10916 | val 0.15308
  Epoch 020 - train 0.10456 | val 0.15356
  Epoch 021 - train 0.10955 | val 0.15334
  Regression -> MSE: 0.000156, MAE: 0.009700, R²: -0.0014
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.10787 | val 0.11351
  Epoch 020 - train 0.10977 | val 0.11403
  Epoch 021 - train 0.11041 | val 0.11486
  Regression -> MSE: 0.000285, MAE: 0.013657, R²: -0.0484
  Directional -> Accuracy: 0.3947, MCC: 0.0000, F1: 0.0000

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11020 | val 0.12765
  Epoch 020 - train 0.09772 | val 0.12758
  Epoch 021 - train 0.10000 | val 0.12766
  Regression -> MSE: 0.000161, MAE: 0.008957, R²: -0.0788
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.10426 | val 0.13954
  Epoch 020 - train 0.11160 | val 0.13941
  Epoch 021 - train 0.11197 | val 0.13865
  Regression -> MSE: 0.000247, MAE: 0.011224, R²: -0.0912
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.10624 | val 0.12242
  Epoch 020 - train 0.11105 | val 0.12618
  Epoch 021 - train 0.10680 | val 0.12552
  Regression -> MSE: 0.000143, MAE: 0.008317, R²: 0.0003
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.11107 | val 0.10912
  Epoch 020 - train 0.11133 | val 0.10889
  Epoch 021 - train 0.10876 | val 0.10869
  Regression -> MSE: 0.000184, MAE: 0.010391, R²: -0.1142
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.11752 | val 0.12053
  Epoch 020 - train 0.11595 | val 0.12335
  Epoch 021 - train 0.11517 | val 0.12351
  Regression -> MSE: 0.000085, MAE: 0.007032, R²: 0.0020
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.11075 | val 0.12098
  Epoch 020 - train 0.11587 | val 0.11998
  Epoch 021 - train 0.11392 | val 0.12002
  Regression -> MSE: 0.000216, MAE: 0.011557, R²: -0.0222
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.11019 | val 0.08390
  Epoch 020 - train 0.10900 | val 0.08433
  Epoch 021 - train 0.09865 | val 0.08417
  Regression -> MSE: 0.000101, MAE: 0.008245, R²: -0.0986
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.11759 | val 0.07505
  Epoch 020 - train 0.11546 | val 0.07898
  Epoch 021 - train 0.11504 | val 0.07932
  Regression -> MSE: 0.000103, MAE: 0.008706, R²: 0.0006
  Directional -> Accuracy: 0.6087, MCC: 0.1953, F1: 0.5263

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.10722 | val 0.09284
  Epoch 020 - train 0.10696 | val 0.09471
  Epoch 021 - train 0.10606 | val 0.09463
  Regression -> MSE: 0.000239, MAE: 0.012818, R²: -0.0345
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.10601 | val 0.11816
  Epoch 020 - train 0.11034 | val 0.11954
  Epoch 021 - train 0.11238 | val 0.11961
  Regression -> MSE: 0.000177, MAE: 0.007923, R²: -0.0641
  Directional -> Accuracy: 0.4386, MCC: -0.3307, F1: 0.6098

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.11143 | val 0.08185
  Epoch 020 - train 0.11751 | val 0.08550
  Epoch 021 - train 0.10874 | val 0.08626
  Regression -> MSE: 0.000236, MAE: 0.011858, R²: 0.0004
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12798 | val 0.14729
  Epoch 020 - train 0.11560 | val 0.15024
  Epoch 021 - train 0.11626 | val 0.15019
  Regression -> MSE: 0.000230, MAE: 0.009866, R²: -0.0001
  Directional -> Accuracy: 0.4884, MCC: -0.0397, F1: 0.3125

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.10922 | val 0.12684
  Epoch 020 - train 0.10230 | val 0.13612
  Epoch 021 - train 0.10742 | val 0.13658
  Regression -> MSE: 0.000143, MAE: 0.008631, R²: -0.0574
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.10876 | val 0.12093
  Epoch 020 - train 0.10860 | val 0.12420
  Epoch 021 - train 0.12242 | val 0.12441
  Regression -> MSE: 0.000193, MAE: 0.010463, R²: -0.0264
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.11234 | val 0.12220
  Epoch 020 - train 0.10766 | val 0.12422
  Epoch 021 - train 0.10609 | val 0.12375
  Regression -> MSE: 0.000282, MAE: 0.011036, R²: -0.0783
  Directional -> Accuracy: 0.4384, MCC: 0.0000, F1: 0.0000

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.09452 | val 0.08045
  Epoch 020 - train 0.10102 | val 0.07920
  Epoch 021 - train 0.10452 | val 0.07908
  Regression -> MSE: 0.000166, MAE: 0.010355, R²: 0.0022
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.10588 | val 0.09523
  Epoch 020 - train 0.09860 | val 0.09423
  Epoch 021 - train 0.10671 | val 0.09451
  Regression -> MSE: 0.000180, MAE: 0.010241, R²: 0.0018
  Directional -> Accuracy: 0.6591, MCC: 0.3754, F1: 0.4828

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12045 | val 0.10414
  Epoch 020 - train 0.11253 | val 0.10366
  Epoch 021 - train 0.11329 | val 0.10368
  Regression -> MSE: 0.000350, MAE: 0.012344, R²: -0.0206
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.11206 | val 0.06413
  Epoch 020 - train 0.10777 | val 0.06546
  Epoch 021 - train 0.11131 | val 0.06526
  Regression -> MSE: 0.000124, MAE: 0.008439, R²: -0.1819
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.10787 | val 0.12724
  Epoch 020 - train 0.10623 | val 0.12782
  Epoch 021 - train 0.10646 | val 0.12776
  Regression -> MSE: 0.000219, MAE: 0.011340, R²: -0.0036
  Directional -> Accuracy: 0.4211, MCC: -0.2148, F1: 0.1951

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.11505 | val 0.16231
  Epoch 020 - train 0.11512 | val 0.17306
  Epoch 021 - train 0.10735 | val 0.17286
  Regression -> MSE: 0.000094, MAE: 0.007587, R²: -0.2154
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.10313 | val 0.07621
  Epoch 020 - train 0.10253 | val 0.07611
  Epoch 021 - train 0.10532 | val 0.07616
  Regression -> MSE: 0.000320, MAE: 0.014525, R²: -0.0415
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.11607 | val 0.06499
  Epoch 020 - train 0.11343 | val 0.06547
  Epoch 021 - train 0.10630 | val 0.06564
  Regression -> MSE: 0.000261, MAE: 0.011496, R²: -0.0700
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.10664 | val 0.12214
  Epoch 020 - train 0.10770 | val 0.12209
  Epoch 021 - train 0.10565 | val 0.12218
  Regression -> MSE: 0.000083, MAE: 0.007061, R²: -0.0215
  Directional -> Accuracy: 0.5067, MCC: 0.0000, F1: 0.0000

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.11103 | val 0.11858
  Epoch 020 - train 0.10870 | val 0.11839
  Epoch 021 - train 0.11361 | val 0.11845
  Regression -> MSE: 0.000307, MAE: 0.014504, R²: -0.0012
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.10819 | val 0.10526
  Epoch 020 - train 0.09914 | val 0.10168
  Epoch 021 - train 0.09927 | val 0.10130
  Regression -> MSE: 0.000099, MAE: 0.007155, R²: -0.0118
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.11417 | val 0.11610
  Epoch 020 - train 0.13412 | val 0.12361
  Epoch 021 - train 0.11763 | val 0.12435
  Regression -> MSE: 0.000179, MAE: 0.010395, R²: -0.0398
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.10202 | val 0.11539
  Epoch 020 - train 0.10694 | val 0.11863

[I 2026-02-24 06:29:19,954] Trial 221 finished with value: -0.011491579239383877 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 4.786843588447753e-06, 'weight_decay': 1.3528549583101022e-05, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.13847412213081806, 'early_stopping_min_delta': 0.00720525986348859}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 021 - train 0.11538 | val 0.16474
  Regression -> MSE: 0.000237, MAE: 0.012355, R²: 0.0017
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.14520 | val 0.14539
  Epoch 020 - train 0.13542 | val 0.14458
  Epoch 021 - train 0.13583 | val 0.14431
  Regression -> MSE: 0.000247, MAE: 0.012519, R²: 0.0014
  Directional -> Accuracy: 0.5584, MCC: 0.0858, F1: 0.1053

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.11427 | val 0.10853
  Epoch 020 - train 0.11235 | val 0.11006
  Epoch 021 - train 0.11518 | val 0.10995
  Regression -> MSE: 0.000698, MAE: 0.019585, R²: -0.0195
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.12566 | val 0.18609
  Epoch 020 - train 0.12853 | val 0.18779
  Epoch 021 - train 0.13107 | val 0.18811
  Regression -> MSE: 0.000311, MAE: 0.014433, R²: -0.0010
  Directional -> Accuracy: 0.5319, MCC: 0.0000, F1: 0.6944

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11266 | val 0.10693
  Epoch 020 - train 0.10819 | val 0.10775
  Epoch 021 - train 0.11162 | val 0.10938
  Regression -> MSE: 0.000353, MAE: 0.014636, R²: -0.0108
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12381 | val 0.11290
  Epoch 020 - train 0.12675 | val 0.11374
  Epoch 021 - train 0.12914 | val 0.11381
  Regression -> MSE: 0.000207, MAE: 0.010105, R²: -0.0152
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12059 | val 0.21655
  Epoch 020 - train 0.11686 | val 0.22769
  Epoch 021 - train 0.13362 | val 0.22851
  Regression -> MSE: 0.000567, MAE: 0.018309, R²: -0.0215
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13337 | val 0.16384
  Epoch 020 - train 0.13351 | val 0.16209
  Epoch 021 - train 0.13135 | val 0.16242
  Regression -> MSE: 0.000247, MAE: 0.011965, R²: -0.0060
  Directional -> Accuracy: 0.5942, MCC: 0.0476, F1: 0.1250

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.12597 | val 0.14002
  Epoch 020 - train 0.12858 | val 0.13464
  Epoch 030 - train 0.13375 | val 0.13509
  Regression -> MSE: 0.000611, MAE: 0.019207, R²: -0.0229
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.12685 | val 0.13979
  Epoch 020 - train 0.12294 | val 0.14090
  Epoch 021 - train 0.12116 | val 0.14095
  Regression -> MSE: 0.000387, MAE: 0.016047, R²: -0.0099
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12328 | val 0.14358
  Epoch 020 - train 0.13497 | val 0.14335
  Epoch 021 - train 0.13327 | val 0.14323
  Regression -> MSE: 0.000241, MAE: 0.011778, R²: -0.0001
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12235 | val 0.15612
  Epoch 020 - train 0.11964 | val 0.15685
  Epoch 021 - train 0.12786 | val 0.15669
  Regression -> MSE: 0.000314, MAE: 0.013619, R²: -0.0105
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14117 | val 0.15265
  Epoch 020 - train 0.13264 | val 0.15970
  Epoch 021 - train 0.13487 | val 0.15929
  Regression -> MSE: 0.000684, MAE: 0.019760, R²: -0.0104
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13350 | val 0.11890
  Epoch 020 - train 0.13156 | val 0.12314
  Epoch 021 - train 0.12790 | val 0.12334
  Regression -> MSE: 0.000139, MAE: 0.009015, R²: -0.0053
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.11788 | val 0.14830
  Epoch 020 - train 0.11949 | val 0.14915
  Epoch 021 - train 0.12106 | val 0.14897
  Regression -> MSE: 0.000227, MAE: 0.010746, R²: -0.0090
  Directional -> Accuracy: 0.4918, MCC: 0.0000, F1: 0.0000

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12519 | val 0.22819
  Epoch 020 - train 0.12126 | val 0.23012
  Epoch 021 - train 0.12054 | val 0.23028
  Regression -> MSE: 0.000363, MAE: 0.016012, R²: -0.0029
  Directional -> Accuracy: 0.4423, MCC: -0.0869, F1: 0.5797

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13727 | val 0.13488
  Epoch 020 - train 0.14002 | val 0.13611
  Epoch 021 - train 0.13044 | val 0.13607
  Regression -> MSE: 0.000112, MAE: 0.007976, R²: -0.0395
  Directional -> Accuracy: 0.5429, MCC: 0.0000, F1: 0.7037

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.13464 | val 0.26524
  Epoch 020 - train 0.12902 | val 0.29444
  Epoch 021 - train 0.13813 | val 0.29286
  Regression -> MSE: 0.000156, MAE: 0.009558, R²: -0.0012
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.12362 | val 0.11343
  Epoch 020 - train 0.12564 | val 0.11355
  Epoch 021 - train 0.12566 | val 0.11363
  Regression -> MSE: 0.000272, MAE: 0.012969, R²: 0.0012
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.11444 | val 0.15126
  Epoch 020 - train 0.11650 | val 0.14989
  Epoch 021 - train 0.10899 | val 0.14993
  Regression -> MSE: 0.000152, MAE: 0.008726, R²: -0.0168
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13567 | val 0.17464
  Epoch 020 - train 0.13593 | val 0.17328
  Epoch 021 - train 0.12851 | val 0.17368
  Regression -> MSE: 0.000242, MAE: 0.011086, R²: -0.0677
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.12406 | val 0.14125
  Epoch 020 - train 0.12634 | val 0.14524
  Epoch 021 - train 0.12780 | val 0.14537
  Regression -> MSE: 0.000146, MAE: 0.008501, R²: -0.0183
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12875 | val 0.17166
  Epoch 020 - train 0.13283 | val 0.17368
  Epoch 021 - train 0.13066 | val 0.17337
  Regression -> MSE: 0.000165, MAE: 0.010485, R²: -0.0007
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.12676 | val 0.13447
  Epoch 020 - train 0.12853 | val 0.13422
  Epoch 021 - train 0.12498 | val 0.13440
  Regression -> MSE: 0.000086, MAE: 0.007113, R²: -0.0110
  Directional -> Accuracy: 0.5690, MCC: 0.0000, F1: 0.7253

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.12979 | val 0.16119
  Epoch 020 - train 0.12980 | val 0.15645
  Epoch 021 - train 0.12837 | val 0.15447
  Regression -> MSE: 0.000215, MAE: 0.011465, R²: -0.0164
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12154 | val 0.11018
  Epoch 020 - train 0.11978 | val 0.11432
  Epoch 021 - train 0.12386 | val 0.11310
  Regression -> MSE: 0.000104, MAE: 0.008307, R²: -0.1253
  Directional -> Accuracy: 0.4464, MCC: 0.0000, F1: 0.0000

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.14524 | val 0.09143
  Epoch 020 - train 0.13544 | val 0.12897
  Epoch 021 - train 0.13459 | val 0.13437
  Regression -> MSE: 0.000104, MAE: 0.008806, R²: -0.0118
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.13856 | val 0.11925
  Epoch 020 - train 0.13372 | val 0.12466
  Epoch 021 - train 0.13916 | val 0.12443
  Regression -> MSE: 0.000246, MAE: 0.013001, R²: -0.0640
  Directional -> Accuracy: 0.4186, MCC: 0.0000, F1: 0.0000

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.13718 | val 0.12873
  Epoch 020 - train 0.13784 | val 0.12880
  Epoch 021 - train 0.13387 | val 0.12888
  Regression -> MSE: 0.000185, MAE: 0.008059, R²: -0.1090
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13143 | val 0.09501
  Epoch 020 - train 0.13489 | val 0.08997
  Epoch 021 - train 0.13854 | val 0.09016
  Regression -> MSE: 0.000237, MAE: 0.011889, R²: -0.0035
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.12316 | val 0.17575
  Epoch 020 - train 0.12584 | val 0.17846
  Epoch 021 - train 0.13231 | val 0.17887
  Regression -> MSE: 0.000231, MAE: 0.009896, R²: -0.0039
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.12574 | val 0.14150
  Epoch 020 - train 0.12796 | val 0.15408
  Epoch 021 - train 0.12496 | val 0.15463
  Regression -> MSE: 0.000136, MAE: 0.008270, R²: -0.0097
  Directional -> Accuracy: 0.5814, MCC: 0.1819, F1: 0.5500

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.12974 | val 0.14328
  Epoch 020 - train 0.12448 | val 0.14182
  Epoch 021 - train 0.12432 | val 0.14191
  Regression -> MSE: 0.000188, MAE: 0.010483, R²: 0.0004
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.7013

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12761 | val 0.13875
  Epoch 020 - train 0.12253 | val 0.13944
  Epoch 021 - train 0.11951 | val 0.13876
  Regression -> MSE: 0.000270, MAE: 0.010634, R²: -0.0330
  Directional -> Accuracy: 0.4521, MCC: -0.1128, F1: 0.5122

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.12115 | val 0.09507
  Epoch 020 - train 0.11554 | val 0.10439
  Epoch 021 - train 0.11567 | val 0.10717
  Regression -> MSE: 0.000167, MAE: 0.010350, R²: -0.0019
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.13420 | val 0.14103
  Epoch 020 - train 0.12810 | val 0.17114
  Epoch 021 - train 0.12189 | val 0.17108
  Regression -> MSE: 0.000191, MAE: 0.010726, R²: -0.0600
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.12061 | val 0.10567
  Epoch 020 - train 0.11476 | val 0.10572
  Epoch 021 - train 0.11898 | val 0.10577
  Regression -> MSE: 0.000347, MAE: 0.011719, R²: -0.0113
  Directional -> Accuracy: 0.5672, MCC: 0.0000, F1: 0.7238

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.12862 | val 0.07671
  Epoch 020 - train 0.13932 | val 0.07859
  Epoch 021 - train 0.13238 | val 0.07812
  Regression -> MSE: 0.000133, MAE: 0.008625, R²: -0.2624
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.14380 | val 0.16157
  Epoch 020 - train 0.13900 | val 0.16584
  Epoch 021 - train 0.14392 | val 0.16531
  Regression -> MSE: 0.000219, MAE: 0.011335, R²: -0.0031
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.0000

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13776 | val 0.20172
  Epoch 020 - train 0.12553 | val 0.21334
  Epoch 021 - train 0.12776 | val 0.21361
  Regression -> MSE: 0.000087, MAE: 0.007287, R²: -0.1169
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.14330 | val 0.08903
  Epoch 020 - train 0.14457 | val 0.09435
  Epoch 021 - train 0.13596 | val 0.09473
  Regression -> MSE: 0.000320, MAE: 0.014472, R²: -0.0386
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.12566 | val 0.06749
  Epoch 020 - train 0.13120 | val 0.06632
  Epoch 021 - train 0.12979 | val 0.06641
  Regression -> MSE: 0.000247, MAE: 0.011547, R²: -0.0152
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.0000

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12124 | val 0.14173
  Epoch 020 - train 0.12325 | val 0.14195
  Epoch 021 - train 0.12506 | val 0.14211
  Regression -> MSE: 0.000081, MAE: 0.007083, R²: 0.0009
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.13987 | val 0.14354
  Epoch 020 - train 0.14264 | val 0.13486
  Epoch 030 - train 0.13926 | val 0.13469
  Regression -> MSE: 0.000316, MAE: 0.014649, R²: -0.0300
  Directional -> Accuracy: 0.5532, MCC: 0.1043, F1: 0.6038

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12782 | val 0.12002
  Epoch 020 - train 0.12834 | val 0.12226
  Epoch 021 - train 0.13034 | val 0.12284
  Regression -> MSE: 0.000098, MAE: 0.007322, R²: -0.0016
  Directional -> Accuracy: 0.4318, MCC: 0.0000, F1: 0.0000

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13171 | val 0.13395
  Epoch 020 - train 0.13124 | val 0.13856
  Epoch 021 - train 0.12986 | val 0.13893
  Regression -> MSE: 0.000174, MAE: 0.010086, R²: -0.0132
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...
  Epoch 010 - train 0.12118 | val 0.13104

[I 2026-02-24 06:31:21,787] Trial 222 finished with value: -0.01142810742994536 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 5.390081946647325e-06, 'weight_decay': 7.985853476779958e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.16820447264732388, 'early_stopping_min_delta': 0.007510301061178353}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.13015 | val 0.16362
  Epoch 021 - train 0.12965 | val 0.16397
  Regression -> MSE: 0.000240, MAE: 0.012335, R²: -0.0108
  Directional -> Accuracy: 0.5246, MCC: 0.0000, F1: 0.0000

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.13349 | val 0.15185
  Epoch 020 - train 0.13024 | val 0.15164
  Epoch 021 - train 0.13297 | val 0.15128
  Regression -> MSE: 0.000248, MAE: 0.012540, R²: -0.0009
  Directional -> Accuracy: 0.5455, MCC: 0.0149, F1: 0.0541

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.13302 | val 0.11413
  Epoch 020 - train 0.13589 | val 0.13175
  Epoch 021 - train 0.13245 | val 0.13187
  Regression -> MSE: 0.000689, MAE: 0.019441, R²: -0.0066
  Directional -> Accuracy: 0.5652, MCC: 0.0000, F1: 0.7222

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.13410 | val 0.18520
  Epoch 020 - train 0.13115 | val 0.17984
  Epoch 030 - train 0.13229 | val 0.17999
  Regression -> MSE: 0.000328, MAE: 0.014525, R²: -0.0582
  Directional -> Accuracy: 0.5532, MCC: 0.1053, F1: 0.5714

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.11820 | val 0.12297
  Epoch 020 - train 0.11865 | val 0.12068
  Epoch 021 - train 0.11671 | val 0.12030
  Regression -> MSE: 0.000352, MAE: 0.014596, R²: -0.0076
  Directional -> Accuracy: 0.5467, MCC: 0.0000, F1: 0.7069

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.12781 | val 0.12006
  Epoch 020 - train 0.14004 | val 0.12130
  Epoch 021 - train 0.13015 | val 0.12152
  Regression -> MSE: 0.000207, MAE: 0.010387, R²: -0.0148
  Directional -> Accuracy: 0.4706, MCC: 0.0000, F1: 0.0000

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.12341 | val 0.22571
  Epoch 020 - train 0.13092 | val 0.24008
  Epoch 021 - train 0.12217 | val 0.24033
  Regression -> MSE: 0.000597, MAE: 0.018931, R²: -0.0759
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.13579 | val 0.17058
  Epoch 020 - train 0.13554 | val 0.17257
  Epoch 021 - train 0.12251 | val 0.17188
  Regression -> MSE: 0.000245, MAE: 0.011968, R²: 0.0025
  Directional -> Accuracy: 0.5362, MCC: 0.1985, F1: 0.6000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.13476 | val 0.14661
  Epoch 020 - train 0.13494 | val 0.15722
  Epoch 021 - train 0.14079 | val 0.15759
  Regression -> MSE: 0.000611, MAE: 0.019503, R²: -0.0225
  Directional -> Accuracy: 0.5909, MCC: 0.0000, F1: 0.0000

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.13507 | val 0.14685
  Epoch 020 - train 0.13345 | val 0.16177
  Epoch 021 - train 0.13893 | val 0.16173
  Regression -> MSE: 0.000389, MAE: 0.016011, R²: -0.0130
  Directional -> Accuracy: 0.4490, MCC: 0.0000, F1: 0.6197

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.12671 | val 0.15255
  Epoch 020 - train 0.12939 | val 0.15402
  Epoch 021 - train 0.13082 | val 0.15409
  Regression -> MSE: 0.000243, MAE: 0.012138, R²: -0.0056
  Directional -> Accuracy: 0.4286, MCC: 0.0000, F1: 0.6000

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.12725 | val 0.15926
  Epoch 020 - train 0.12272 | val 0.15857
  Epoch 021 - train 0.11712 | val 0.15844
  Regression -> MSE: 0.000317, MAE: 0.013574, R²: -0.0194
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.14735 | val 0.15400
  Epoch 020 - train 0.14233 | val 0.16106
  Epoch 021 - train 0.14478 | val 0.16205
  Regression -> MSE: 0.000678, MAE: 0.019478, R²: -0.0013
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0000

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.13930 | val 0.14126
  Epoch 020 - train 0.13972 | val 0.15741
  Epoch 021 - train 0.14138 | val 0.15796
  Regression -> MSE: 0.000141, MAE: 0.008976, R²: -0.0206
  Directional -> Accuracy: 0.5581, MCC: 0.0000, F1: 0.0000

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.12491 | val 0.15280
  Epoch 020 - train 0.13455 | val 0.15224
  Epoch 021 - train 0.12837 | val 0.15237
  Regression -> MSE: 0.000225, MAE: 0.010720, R²: 0.0015
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.12664 | val 0.23491
  Epoch 020 - train 0.12617 | val 0.23534
  Epoch 021 - train 0.12461 | val 0.23494
  Regression -> MSE: 0.000363, MAE: 0.016054, R²: -0.0026
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.13583 | val 0.14400
  Epoch 020 - train 0.13035 | val 0.14375
  Epoch 021 - train 0.13302 | val 0.14456
  Regression -> MSE: 0.000109, MAE: 0.008108, R²: -0.0066
  Directional -> Accuracy: 0.4571, MCC: 0.0000, F1: 0.0000

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.12957 | val 0.19387
  Epoch 020 - train 0.13310 | val 0.19720
  Epoch 021 - train 0.13167 | val 0.19661
  Regression -> MSE: 0.000158, MAE: 0.009944, R²: -0.0135
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.14127 | val 0.14831
  Epoch 020 - train 0.14140 | val 0.14692
  Epoch 021 - train 0.14307 | val 0.14589
  Regression -> MSE: 0.000272, MAE: 0.013019, R²: -0.0014
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.12180 | val 0.15636
  Epoch 020 - train 0.11095 | val 0.15716
  Epoch 021 - train 0.11259 | val 0.15703
  Regression -> MSE: 0.000156, MAE: 0.008775, R²: -0.0409
  Directional -> Accuracy: 0.5846, MCC: 0.0000, F1: 0.7379

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.13619 | val 0.16880
  Epoch 020 - train 0.14112 | val 0.16953
  Epoch 021 - train 0.13382 | val 0.16905
  Regression -> MSE: 0.000234, MAE: 0.010951, R²: -0.0360
  Directional -> Accuracy: 0.4533, MCC: -0.1058, F1: 0.5060

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.13239 | val 0.14497
  Epoch 020 - train 0.13803 | val 0.14733
  Epoch 021 - train 0.12997 | val 0.14736
  Regression -> MSE: 0.000143, MAE: 0.008296, R²: 0.0028
  Directional -> Accuracy: 0.6250, MCC: 0.0000, F1: 0.7692

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.12100 | val 0.15150
  Epoch 020 - train 0.11834 | val 0.15278
  Epoch 021 - train 0.11967 | val 0.15264
  Regression -> MSE: 0.000166, MAE: 0.010341, R²: -0.0034
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.13426 | val 0.14970
  Epoch 020 - train 0.13810 | val 0.15460
  Epoch 021 - train 0.13798 | val 0.15445
  Regression -> MSE: 0.000088, MAE: 0.007183, R²: -0.0285
  Directional -> Accuracy: 0.5345, MCC: 0.0278, F1: 0.6197

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.14102 | val 0.21215
  Epoch 020 - train 0.13281 | val 0.21938
  Epoch 021 - train 0.14498 | val 0.21491
  Regression -> MSE: 0.000218, MAE: 0.011046, R²: -0.0275
  Directional -> Accuracy: 0.5303, MCC: 0.0000, F1: 0.0000

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.12539 | val 0.11418
  Epoch 020 - train 0.12048 | val 0.11616
  Epoch 021 - train 0.12005 | val 0.11583
  Regression -> MSE: 0.000095, MAE: 0.008114, R²: -0.0327
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.13018 | val 0.09108
  Epoch 020 - train 0.15105 | val 0.09547
  Epoch 021 - train 0.12945 | val 0.09602
  Regression -> MSE: 0.000106, MAE: 0.008892, R²: -0.0288
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.14907 | val 0.11484
  Epoch 020 - train 0.14085 | val 0.11753
  Epoch 021 - train 0.14779 | val 0.11818
  Regression -> MSE: 0.000236, MAE: 0.012705, R²: -0.0182
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.12876 | val 0.13819
  Epoch 020 - train 0.13270 | val 0.13854
  Epoch 021 - train 0.12876 | val 0.13865
  Regression -> MSE: 0.000185, MAE: 0.008062, R²: -0.1099
  Directional -> Accuracy: 0.4386, MCC: 0.0000, F1: 0.0000

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.13132 | val 0.10017
  Epoch 020 - train 0.13339 | val 0.10392
  Epoch 021 - train 0.14878 | val 0.10393
  Regression -> MSE: 0.000236, MAE: 0.011852, R²: 0.0018
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.13712 | val 0.18319
  Epoch 020 - train 0.12858 | val 0.17867
  Epoch 021 - train 0.13573 | val 0.17894
  Regression -> MSE: 0.000231, MAE: 0.009928, R²: -0.0044
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.6562

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.14124 | val 0.15205
  Epoch 020 - train 0.13737 | val 0.15762
  Epoch 021 - train 0.14308 | val 0.15732
  Regression -> MSE: 0.000143, MAE: 0.008597, R²: -0.0590
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.14380 | val 0.14211
  Epoch 020 - train 0.13962 | val 0.13965
  Epoch 021 - train 0.13386 | val 0.13983
  Regression -> MSE: 0.000199, MAE: 0.010684, R²: -0.0574
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.12349 | val 0.15000
  Epoch 020 - train 0.13074 | val 0.14920
  Epoch 021 - train 0.12833 | val 0.14938
  Regression -> MSE: 0.000262, MAE: 0.010658, R²: -0.0010
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.13145 | val 0.10677
  Epoch 020 - train 0.14032 | val 0.11077
  Epoch 021 - train 0.12145 | val 0.11152
  Regression -> MSE: 0.000168, MAE: 0.010358, R²: -0.0069
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.12628 | val 0.13483
  Epoch 020 - train 0.12900 | val 0.14436
  Epoch 021 - train 0.12393 | val 0.14453
  Regression -> MSE: 0.000185, MAE: 0.010516, R²: -0.0253
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.14046 | val 0.11238
  Epoch 020 - train 0.13402 | val 0.11228
  Epoch 021 - train 0.13484 | val 0.11239
  Regression -> MSE: 0.000350, MAE: 0.012340, R²: -0.0215
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.13551 | val 0.07959
  Epoch 020 - train 0.13435 | val 0.08353
  Epoch 021 - train 0.14768 | val 0.08367
  Regression -> MSE: 0.000111, MAE: 0.008328, R²: -0.0551
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.6769

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.12872 | val 0.16222
  Epoch 020 - train 0.13860 | val 0.16335
  Epoch 021 - train 0.12854 | val 0.16326
  Regression -> MSE: 0.000220, MAE: 0.011365, R²: -0.0074
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.13260 | val 0.19626
  Epoch 020 - train 0.13215 | val 0.19621
  Epoch 021 - train 0.12331 | val 0.19631
  Regression -> MSE: 0.000089, MAE: 0.007377, R²: -0.1443
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.12065 | val 0.09969
  Epoch 020 - train 0.12575 | val 0.10023
  Epoch 021 - train 0.13587 | val 0.10055
  Regression -> MSE: 0.000332, MAE: 0.015084, R²: -0.0802
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.14381 | val 0.07170
  Epoch 020 - train 0.13255 | val 0.06877
  Epoch 021 - train 0.14277 | val 0.06857
  Regression -> MSE: 0.000249, MAE: 0.011498, R²: -0.0207
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.12564 | val 0.14610
  Epoch 020 - train 0.12599 | val 0.14659
  Epoch 021 - train 0.13142 | val 0.14657
  Regression -> MSE: 0.000081, MAE: 0.007108, R²: -0.0048
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.14721 | val 0.15406
  Epoch 020 - train 0.15401 | val 0.17504
  Epoch 021 - train 0.14655 | val 0.17461
  Regression -> MSE: 0.000309, MAE: 0.014504, R²: -0.0072
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.12957 | val 0.13912
  Epoch 020 - train 0.12846 | val 0.12491
  Epoch 030 - train 0.12866 | val 0.12232
  Regression -> MSE: 0.000094, MAE: 0.006953, R²: 0.0475
  Directional -> Accuracy: 0.6591, MCC: 0.2936, F1: 0.7458

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.13465 | val 0.13859
  Epoch 020 - train 0.12846 | val 0.14363
  Epoch 021 - train 0.14134 | val 0.14404
  Regression -> MSE: 0.000173, MAE: 0.009938, R²: -0.0059
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 06:33:26,340] Trial 223 finished with value: -0.011451984945044614 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 5.340143979099654e-06, 'weight_decay': 7.831853859532965e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.17445463234784994, 'early_stopping_min_delta': 0.007568062427178373}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.14226 | val 0.18959
  Epoch 021 - train 0.13593 | val 0.19016
  Regression -> MSE: 0.000238, MAE: 0.012542, R²: -0.0052
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Pipeline initialized for a 'regression' problem with horizon 1 steps. Device: cpu
Processing 88 companies with LSTM model...
Problem type: regression
Sequence length: 18
Features: ['open', 'high', 'low', 'close', 'volume', 'ema_12', 'ema_26', 'ema_50', 'macd_12_26_9', 'macdh_12_26_9', 'macds_12_26_9', 'rsi_14', 'stochrsik_14_14_3_3', 'stochrsid_14_14_3_3', 'atrr_14', 'bb_upper', 'bb_middle', 'bb_lower', 'obv', 'sentiment', 'emotion_anger', 'emotion_disgust', 'emotion_fear', 'emotion_joy', 'emotion_neutral', 'emotion_sadness', 'emotion_surprize', 'emotion_anger_pct', 'emotion_disgust_pct', 'emotion_fear_pct', 'emotion_joy_pct', 'emotion_neutral_pct', 'emotion_sadness_pct', 'emotion_surprize_pct', 'positive_emotion', 'negative_emotion', 'uncertainty_emotion', 'positive_emotion_pct', 'negative_emotion_pct', 'uncertainty_emotion_pct', 'stance_label', 'stance_score', 'finbert_label', 'finbert_score', 'finbert_up', 'finbert_down', 'finbert_neutral']

[1/88] Processing AAPL...

Processing AAPL (Consumer Goods)...
  Epoch 010 - train 0.06695 | val 0.09377
  Epoch 020 - train 0.06448 | val 0.10046
  Epoch 021 - train 0.06355 | val 0.10368
  Regression -> MSE: 0.000252, MAE: 0.012721, R²: -0.0162
  Directional -> Accuracy: 0.4545, MCC: 0.0000, F1: 0.6250

[2/88] Processing ABB...

Processing ABB (Industrial Goods)...
Insufficient data for ABB (62 < 94). Skipping...

[3/88] Processing ABBV...

Processing ABBV (Healthcare)...
  Epoch 010 - train 0.06831 | val 0.07141
  Epoch 020 - train 0.06103 | val 0.08022
  Epoch 021 - train 0.06223 | val 0.08236
  Regression -> MSE: 0.000712, MAE: 0.019849, R²: -0.0402
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.0000

[4/88] Processing AEP...

Processing AEP (Utilities)...
Insufficient data for proper time series validation for AEP. Skipping...

[5/88] Processing AGFS...

Processing AGFS (Conglomerates)...
Insufficient data for AGFS (2 < 94). Skipping...

[6/88] Processing AMGN...

Processing AMGN (Healthcare)...
  Epoch 010 - train 0.06814 | val 0.11176
  Epoch 020 - train 0.06629 | val 0.11529
  Epoch 021 - train 0.06508 | val 0.11616
  Regression -> MSE: 0.000323, MAE: 0.014544, R²: -0.0424
  Directional -> Accuracy: 0.4681, MCC: 0.0000, F1: 0.0000

[7/88] Processing AMZN...

Processing AMZN (Services)...
  Epoch 010 - train 0.06138 | val 0.06692
  Epoch 020 - train 0.05529 | val 0.08027
  Epoch 021 - train 0.05650 | val 0.08600
  Regression -> MSE: 0.000372, MAE: 0.014961, R²: -0.0661
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[8/88] Processing BA...

Processing BA (Industrial Goods)...
  Epoch 010 - train 0.07377 | val 0.07659
  Epoch 020 - train 0.06385 | val 0.08012
  Epoch 021 - train 0.06761 | val 0.08285
  Regression -> MSE: 0.000204, MAE: 0.010071, R²: -0.0033
  Directional -> Accuracy: 0.5294, MCC: 0.0000, F1: 0.6923

[9/88] Processing BABA...

Processing BABA (Services)...
  Epoch 010 - train 0.06719 | val 0.12906
  Epoch 020 - train 0.05917 | val 0.15306
  Epoch 021 - train 0.06237 | val 0.15681
  Regression -> MSE: 0.000584, MAE: 0.018653, R²: -0.0519
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.0000

[10/88] Processing BAC...

Processing BAC (Financial)...
  Epoch 010 - train 0.07087 | val 0.08750
  Epoch 020 - train 0.06368 | val 0.08877
  Epoch 021 - train 0.06458 | val 0.08765
  Regression -> MSE: 0.000248, MAE: 0.011904, R²: -0.0114
  Directional -> Accuracy: 0.5942, MCC: 0.0000, F1: 0.0000

[11/88] Processing BBL...

Processing BBL (Basic Matierials)...
Insufficient data for BBL (69 < 94). Skipping...

[12/88] Processing BCH...

Processing BCH (Financial)...
Insufficient data for BCH (5 < 94). Skipping...

[13/88] Processing BHP...

Processing BHP (Basic Matierials)...
  Epoch 010 - train 0.07596 | val 0.10543
  Epoch 020 - train 0.07009 | val 0.12952
  Epoch 021 - train 0.06671 | val 0.13320
  Regression -> MSE: 0.000624, MAE: 0.019786, R²: -0.0450
  Directional -> Accuracy: 0.4091, MCC: 0.0000, F1: 0.5806

[14/88] Processing BP...

Processing BP (Basic Matierials)...
  Epoch 010 - train 0.06736 | val 0.08556
  Epoch 020 - train 0.06289 | val 0.08828
  Epoch 021 - train 0.06117 | val 0.08899
  Regression -> MSE: 0.000401, MAE: 0.016072, R²: -0.0453
  Directional -> Accuracy: 0.5510, MCC: 0.0000, F1: 0.0000

[15/88] Processing BRK-A...

Processing BRK-A (Financial)...
Insufficient data for BRK-A (13 < 94). Skipping...

[16/88] Processing BSAC...

Processing BSAC (Financial)...
Insufficient data for BSAC (11 < 94). Skipping...

[17/88] Processing BUD...

Processing BUD (Consumer Goods)...
Insufficient data for proper time series validation for BUD. Skipping...

[18/88] Processing C...

Processing C (Financial)...
  Epoch 010 - train 0.06796 | val 0.09196
  Epoch 020 - train 0.06486 | val 0.09762
  Epoch 021 - train 0.06462 | val 0.09807
  Regression -> MSE: 0.000243, MAE: 0.011663, R²: -0.0076
  Directional -> Accuracy: 0.5714, MCC: 0.0248, F1: 0.0625

[19/88] Processing CAT...

Processing CAT (Industrial Goods)...
  Epoch 010 - train 0.06362 | val 0.12724
  Epoch 020 - train 0.06334 | val 0.14611
  Epoch 021 - train 0.05977 | val 0.15176
  Regression -> MSE: 0.000315, MAE: 0.013572, R²: -0.0117
  Directional -> Accuracy: 0.5400, MCC: 0.0000, F1: 0.0000

[20/88] Processing CELG...

Processing CELG (Healthcare)...
  Epoch 010 - train 0.07434 | val 0.10092
  Epoch 020 - train 0.06762 | val 0.10172
  Epoch 021 - train 0.06603 | val 0.10042
  Regression -> MSE: 0.000682, MAE: 0.019733, R²: -0.0074
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[21/88] Processing CHL...

Processing CHL (Technology)...
Insufficient data for proper time series validation for CHL. Skipping...

[22/88] Processing CHTR...

Processing CHTR (Services)...
Insufficient data for proper time series validation for CHTR. Skipping...

[23/88] Processing CMCSA...

Processing CMCSA (Services)...
  Epoch 010 - train 0.07441 | val 0.07433
  Epoch 020 - train 0.06353 | val 0.08207
  Epoch 021 - train 0.06136 | val 0.08232
  Regression -> MSE: 0.000148, MAE: 0.009606, R²: -0.0682
  Directional -> Accuracy: 0.4419, MCC: 0.0000, F1: 0.6129

[24/88] Processing CODI...

Processing CODI (Conglomerates)...
Insufficient data for CODI (29 < 94). Skipping...

[25/88] Processing CSCO...

Processing CSCO (Technology)...
  Epoch 010 - train 0.06465 | val 0.09041
  Epoch 020 - train 0.06176 | val 0.10502
  Epoch 021 - train 0.06258 | val 0.10193
  Regression -> MSE: 0.000224, MAE: 0.010685, R²: 0.0048
  Directional -> Accuracy: 0.5082, MCC: 0.0000, F1: 0.6739

[26/88] Processing CVX...

Processing CVX (Basic Matierials)...
  Epoch 010 - train 0.06956 | val 0.14684
  Epoch 020 - train 0.06229 | val 0.14966
  Epoch 021 - train 0.06075 | val 0.15141
  Regression -> MSE: 0.000362, MAE: 0.016054, R²: 0.0017
  Directional -> Accuracy: 0.4615, MCC: 0.0000, F1: 0.6316

[27/88] Processing D...

Processing D (Utilities)...
  Epoch 010 - train 0.07394 | val 0.07373
  Epoch 020 - train 0.06831 | val 0.07425
  Epoch 021 - train 0.06344 | val 0.07397
  Regression -> MSE: 0.000107, MAE: 0.007946, R²: 0.0108
  Directional -> Accuracy: 0.6429, MCC: 0.2895, F1: 0.7312

[28/88] Processing DHR...

Processing DHR (Industrial Goods)...
Insufficient data for DHR (91 < 94). Skipping...

[29/88] Processing DIS...

Processing DIS (Services)...
  Epoch 010 - train 0.06970 | val 0.11859
  Epoch 020 - train 0.06098 | val 0.12238
  Epoch 021 - train 0.05989 | val 0.12269
  Regression -> MSE: 0.000156, MAE: 0.009701, R²: 0.0014
  Directional -> Accuracy: 0.6271, MCC: 0.0000, F1: 0.7708

[30/88] Processing DUK...

Processing DUK (Utilities)...
Insufficient data for proper time series validation for DUK. Skipping...

[31/88] Processing EXC...

Processing EXC (Utilities)...
Insufficient data for proper time series validation for EXC. Skipping...

[32/88] Processing FB...

Processing FB (Technology)...
  Epoch 010 - train 0.07093 | val 0.07892
  Epoch 020 - train 0.06802 | val 0.07362
  Epoch 021 - train 0.06613 | val 0.07571
  Regression -> MSE: 0.000273, MAE: 0.013066, R²: -0.0026
  Directional -> Accuracy: 0.6053, MCC: 0.0000, F1: 0.7541

[33/88] Processing GD...

Processing GD (Industrial Goods)...
Insufficient data for proper time series validation for GD. Skipping...

[34/88] Processing GE...

Processing GE (Industrial Goods)...
  Epoch 010 - train 0.06304 | val 0.09247
  Epoch 020 - train 0.05889 | val 0.09332
  Epoch 021 - train 0.05687 | val 0.09391
  Regression -> MSE: 0.000174, MAE: 0.009343, R²: -0.1613
  Directional -> Accuracy: 0.4154, MCC: 0.0000, F1: 0.0000

[35/88] Processing GMRE...

Processing GMRE (Conglomerates)...
Insufficient data for GMRE (0 < 94). Skipping...

[36/88] Processing GOOG...

Processing GOOG (Technology)...
  Epoch 010 - train 0.07136 | val 0.11014
  Epoch 020 - train 0.06818 | val 0.10453
  Epoch 021 - train 0.06435 | val 0.11281
  Regression -> MSE: 0.000251, MAE: 0.011309, R²: -0.1107
  Directional -> Accuracy: 0.4533, MCC: 0.0000, F1: 0.0000

[37/88] Processing HD...

Processing HD (Services)...
  Epoch 010 - train 0.06676 | val 0.08713
  Epoch 020 - train 0.06356 | val 0.09711
  Epoch 021 - train 0.06200 | val 0.09709
  Regression -> MSE: 0.000153, MAE: 0.008806, R²: -0.0659
  Directional -> Accuracy: 0.3750, MCC: 0.0000, F1: 0.0000

[38/88] Processing HON...

Processing HON (Industrial Goods)...
Insufficient data for proper time series validation for HON. Skipping...

[39/88] Processing HRG...

Processing HRG (Conglomerates)...
Insufficient data for HRG (30 < 94). Skipping...

[40/88] Processing HSBC...

Processing HSBC (Financial)...
Insufficient data for HSBC (71 < 94). Skipping...

[41/88] Processing IEP...

Processing IEP (Conglomerates)...
Insufficient data for IEP (58 < 94). Skipping...

[42/88] Processing INTC...

Processing INTC (Technology)...
  Epoch 010 - train 0.06483 | val 0.08393
  Epoch 020 - train 0.05967 | val 0.08377
  Epoch 021 - train 0.05831 | val 0.08465
  Regression -> MSE: 0.000173, MAE: 0.010238, R²: -0.0497
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.0571

[43/88] Processing JNJ...

Processing JNJ (Healthcare)...
  Epoch 010 - train 0.07435 | val 0.08446
  Epoch 020 - train 0.06737 | val 0.08477
  Epoch 021 - train 0.06595 | val 0.08869
  Regression -> MSE: 0.000090, MAE: 0.007282, R²: -0.0511
  Directional -> Accuracy: 0.4310, MCC: 0.0000, F1: 0.0000

[44/88] Processing JPM...

Processing JPM (Financial)...
  Epoch 010 - train 0.06573 | val 0.12883
  Epoch 020 - train 0.06422 | val 0.09116
  Epoch 021 - train 0.06414 | val 0.09038
  Regression -> MSE: 0.000215, MAE: 0.011479, R²: -0.0166
  Directional -> Accuracy: 0.4697, MCC: 0.0000, F1: 0.6392

[45/88] Processing KO...

Processing KO (Consumer Goods)...
  Epoch 010 - train 0.06014 | val 0.06981
  Epoch 020 - train 0.05574 | val 0.06697
  Epoch 021 - train 0.05851 | val 0.07135
  Regression -> MSE: 0.000093, MAE: 0.008097, R²: -0.0113
  Directional -> Accuracy: 0.5536, MCC: 0.0000, F1: 0.7126

[46/88] Processing LMT...

Processing LMT (Industrial Goods)...
  Epoch 010 - train 0.06936 | val 0.06153
  Epoch 020 - train 0.06746 | val 0.05835
  Epoch 021 - train 0.06725 | val 0.05901
  Regression -> MSE: 0.000118, MAE: 0.009272, R²: -0.1446
  Directional -> Accuracy: 0.4348, MCC: 0.0000, F1: 0.6061

[47/88] Processing MA...

Processing MA (Financial)...
  Epoch 010 - train 0.07396 | val 0.09478
  Epoch 020 - train 0.06525 | val 0.08358
  Epoch 021 - train 0.06932 | val 0.08363
  Regression -> MSE: 0.000234, MAE: 0.012624, R²: -0.0102
  Directional -> Accuracy: 0.5814, MCC: 0.0000, F1: 0.7353

[48/88] Processing MCD...

Processing MCD (Services)...
  Epoch 010 - train 0.06791 | val 0.08499
  Epoch 020 - train 0.06225 | val 0.08881
  Epoch 021 - train 0.06238 | val 0.08866
  Regression -> MSE: 0.000177, MAE: 0.007879, R²: -0.0620
  Directional -> Accuracy: 0.5614, MCC: 0.1505, F1: 0.5455

[49/88] Processing MDT...

Processing MDT (Healthcare)...
  Epoch 010 - train 0.07952 | val 0.06139
  Epoch 020 - train 0.06789 | val 0.06191
  Epoch 021 - train 0.06966 | val 0.06203
  Regression -> MSE: 0.000238, MAE: 0.011912, R²: -0.0061
  Directional -> Accuracy: 0.5366, MCC: 0.0000, F1: 0.6984

[50/88] Processing MMM...

Processing MMM (Industrial Goods)...
  Epoch 010 - train 0.06941 | val 0.11462
  Epoch 020 - train 0.06074 | val 0.12839
  Epoch 021 - train 0.06260 | val 0.13144
  Regression -> MSE: 0.000230, MAE: 0.009860, R²: 0.0004
  Directional -> Accuracy: 0.5116, MCC: 0.0000, F1: 0.0000

[51/88] Processing MO...

Processing MO (Consumer Goods)...
  Epoch 010 - train 0.06795 | val 0.09693
  Epoch 020 - train 0.06642 | val 0.09940
  Epoch 021 - train 0.06575 | val 0.10059
  Regression -> MSE: 0.000145, MAE: 0.008754, R²: -0.0771
  Directional -> Accuracy: 0.4651, MCC: 0.0000, F1: 0.0000

[52/88] Processing MRK...

Processing MRK (Healthcare)...
  Epoch 010 - train 0.07082 | val 0.09407
  Epoch 020 - train 0.06771 | val 0.09450
  Epoch 021 - train 0.06531 | val 0.09453
  Regression -> MSE: 0.000198, MAE: 0.010653, R²: -0.0538
  Directional -> Accuracy: 0.4600, MCC: 0.0000, F1: 0.0000

[53/88] Processing MSFT...

Processing MSFT (Technology)...
  Epoch 010 - train 0.06339 | val 0.07944
  Epoch 020 - train 0.05951 | val 0.07879
  Epoch 021 - train 0.05888 | val 0.07867
  Regression -> MSE: 0.000260, MAE: 0.010537, R²: 0.0069
  Directional -> Accuracy: 0.5616, MCC: 0.0000, F1: 0.7193

[54/88] Processing NEE...

Processing NEE (Utilities)...
Insufficient data for proper time series validation for NEE. Skipping...

[55/88] Processing NGG...

Processing NGG (Utilities)...
Insufficient data for NGG (28 < 94). Skipping...

[56/88] Processing NVS...

Processing NVS (Healthcare)...
  Epoch 010 - train 0.07610 | val 0.06158
  Epoch 020 - train 0.06329 | val 0.06691
  Epoch 021 - train 0.06018 | val 0.06854
  Regression -> MSE: 0.000167, MAE: 0.010370, R²: -0.0020
  Directional -> Accuracy: 0.5000, MCC: 0.0000, F1: 0.6667

[57/88] Processing ORCL...

Processing ORCL (Technology)...
  Epoch 010 - train 0.06538 | val 0.07641
  Epoch 020 - train 0.06024 | val 0.07854
  Epoch 021 - train 0.05657 | val 0.07749
  Regression -> MSE: 0.000185, MAE: 0.010540, R²: -0.0277
  Directional -> Accuracy: 0.4773, MCC: 0.0000, F1: 0.6462

[58/88] Processing PCG...

Processing PCG (Utilities)...
Insufficient data for proper time series validation for PCG. Skipping...

[59/88] Processing PCLN...

Processing PCLN (Services)...
  Epoch 010 - train 0.06700 | val 0.07042
  Epoch 020 - train 0.06040 | val 0.07121
  Epoch 021 - train 0.06182 | val 0.07125
  Regression -> MSE: 0.000348, MAE: 0.012290, R²: -0.0171
  Directional -> Accuracy: 0.4328, MCC: 0.0000, F1: 0.0000

[60/88] Processing PEP...

Processing PEP (Consumer Goods)...
  Epoch 010 - train 0.07249 | val 0.04751
  Epoch 020 - train 0.06459 | val 0.05130
  Epoch 021 - train 0.06275 | val 0.05150
  Regression -> MSE: 0.000125, MAE: 0.008484, R²: -0.1924
  Directional -> Accuracy: 0.4884, MCC: 0.0000, F1: 0.0000

[61/88] Processing PFE...

Processing PFE (Healthcare)...
  Epoch 010 - train 0.07013 | val 0.10517
  Epoch 020 - train 0.06512 | val 0.10786
  Epoch 021 - train 0.06065 | val 0.10578
  Regression -> MSE: 0.000221, MAE: 0.011369, R²: -0.0118
  Directional -> Accuracy: 0.4737, MCC: 0.0000, F1: 0.6429

[62/88] Processing PG...

Processing PG (Consumer Goods)...
  Epoch 010 - train 0.07169 | val 0.13445
  Epoch 020 - train 0.06457 | val 0.14951
  Epoch 021 - train 0.06337 | val 0.14959
  Regression -> MSE: 0.000093, MAE: 0.007550, R²: -0.2034
  Directional -> Accuracy: 0.3830, MCC: 0.0000, F1: 0.0000

[63/88] Processing PICO...

Processing PICO (Conglomerates)...
Insufficient data for PICO (16 < 94). Skipping...

[64/88] Processing PM...

Processing PM (Consumer Goods)...
Insufficient data for proper time series validation for PM. Skipping...

[65/88] Processing PPL...

Processing PPL (Utilities)...
Insufficient data for proper time series validation for PPL. Skipping...

[66/88] Processing PTR...

Processing PTR (Basic Matierials)...
Insufficient data for PTR (44 < 94). Skipping...

[67/88] Processing RDS-B...

Processing RDS-B (Basic Matierials)...
Insufficient data for RDS-B (3 < 94). Skipping...

[68/88] Processing REX...

Processing REX (Conglomerates)...
Insufficient data for REX (70 < 94). Skipping...

[69/88] Processing SLB...

Processing SLB (Basic Matierials)...
  Epoch 010 - train 0.07103 | val 0.05371
  Epoch 020 - train 0.06488 | val 0.05502
  Epoch 021 - train 0.06463 | val 0.05557
  Regression -> MSE: 0.000314, MAE: 0.014149, R²: -0.0193
  Directional -> Accuracy: 0.3673, MCC: 0.0000, F1: 0.5373

[70/88] Processing SNP...

Processing SNP (Basic Matierials)...
Insufficient data for SNP (23 < 94). Skipping...

[71/88] Processing SNY...

Processing SNY (Healthcare)...
Insufficient data for proper time series validation for SNY. Skipping...

[72/88] Processing SO...

Processing SO (Utilities)...
  Epoch 010 - train 0.07147 | val 0.04788
  Epoch 020 - train 0.07200 | val 0.05462
  Epoch 021 - train 0.06137 | val 0.05451
  Regression -> MSE: 0.000252, MAE: 0.011499, R²: -0.0334
  Directional -> Accuracy: 0.5263, MCC: 0.0000, F1: 0.6897

[73/88] Processing SPLP...

Processing SPLP (Conglomerates)...
Insufficient data for SPLP (5 < 94). Skipping...

[74/88] Processing SRE...

Processing SRE (Utilities)...
Insufficient data for SRE (69 < 94). Skipping...

[75/88] Processing T...

Processing T (Technology)...
  Epoch 010 - train 0.06344 | val 0.09054
  Epoch 020 - train 0.06199 | val 0.09389
  Epoch 021 - train 0.05864 | val 0.09473
  Regression -> MSE: 0.000081, MAE: 0.007062, R²: 0.0004
  Directional -> Accuracy: 0.4933, MCC: 0.0000, F1: 0.6607

[76/88] Processing TM...

Processing TM (Consumer Goods)...
Insufficient data for proper time series validation for TM. Skipping...

[77/88] Processing TOT...

Processing TOT (Basic Matierials)...
Insufficient data for TOT (93 < 94). Skipping...

[78/88] Processing TSM...

Processing TSM (Technology)...
Insufficient data for TSM (87 < 94). Skipping...

[79/88] Processing UL...

Processing UL (Consumer Goods)...
Insufficient data for UL (61 < 94). Skipping...

[80/88] Processing UN...

Processing UN (Consumer Goods)...
Insufficient data for UN (54 < 94). Skipping...

[81/88] Processing UNH...

Processing UNH (Healthcare)...
  Epoch 010 - train 0.06740 | val 0.08737
  Epoch 020 - train 0.06069 | val 0.09412
  Epoch 021 - train 0.06428 | val 0.09962
  Regression -> MSE: 0.000310, MAE: 0.014490, R²: -0.0108
  Directional -> Accuracy: 0.5106, MCC: 0.0000, F1: 0.6761

[82/88] Processing UPS...

Processing UPS (Services)...
  Epoch 010 - train 0.07090 | val 0.07992
  Epoch 020 - train 0.06577 | val 0.07801
  Epoch 021 - train 0.06117 | val 0.07796
  Regression -> MSE: 0.000099, MAE: 0.007243, R²: -0.0086
  Directional -> Accuracy: 0.5682, MCC: 0.0000, F1: 0.7246

[83/88] Processing UTX...

Processing UTX (Industrial Goods)...
  Epoch 010 - train 0.07444 | val 0.08358
  Epoch 020 - train 0.07122 | val 0.09237
  Epoch 021 - train 0.06689 | val 0.09616
  Regression -> MSE: 0.000175, MAE: 0.010139, R²: -0.0175
  Directional -> Accuracy: 0.3878, MCC: 0.0000, F1: 0.5588

[84/88] Processing V...

Processing V (Financial)...

[I 2026-02-24 06:35:27,556] Trial 224 finished with value: -0.01150247521539297 and parameters: {'feature_set': 'all_nlp', 'model_type': 'LSTM', 'sequence_length': 18, 'horizon_steps': 1, 'hidden1': 128, 'hidden2': 128, 'num_layers': 2, 'inter_rnn_drop': 0.2, 'dropout': 0.8, 'batch_size': 32, 'learning_rate': 0.0014574759093332892, 'weight_decay': 6.1266289995116195e-06, 'lr_patience': 10, 'lr_factor': 0.4, 'early_stopping_patience': 20, 'max_epochs': 30, 'huber_delta': 0.1014773671550398, 'early_stopping_min_delta': 0.007884652292596184}. Best is trial 44 with value: -0.011362814469631832.

  Epoch 020 - train 0.06376 | val 0.10108
  Epoch 021 - train 0.06599 | val 0.09995
  Regression -> MSE: 0.000237, MAE: 0.012470, R²: -0.0013
  Directional -> Accuracy: 0.4754, MCC: 0.0000, F1: 0.6444

================================================================================
Pipeline completed: 50/88 companies processed successfully
================================================================================
[DEBUG] results_df shape: (50, 23)
[DEBUG] results_df columns: ['company', 'sector', 'model_type', 'problem_type', 'horizon_steps', 'mse', 'mae', 'r2', 'mcc', 'f1', 'precision', 'recall', 'directional_accuracy', 'val_directional_accuracy', 'val_mcc', 'val_f1', 'val_precision', 'val_recall', 'n_samples', 'train_samples', 'val_samples', 'test_samples', 'epochs_trained']
[DEBUG] val_mcc: nan
Saved Optuna results to ../results/benchmarking/regression/optuna_tuning_NLP_1H.csv